### ISSUE TITLE
tensorboard script fails due to failing import

### ISSUE THREAD

**Issue by ptc-swalk** [tensorflow/tensorflow#1000]
It seems commit 8a59748c087a2fee535c0d5067dbabb01920e812 has done this move:  tensorflow/tensorboard/{ → backend}/tensorboard.py but the import in the tensorboard script that gets installed by pip uses the old location (I think that's defined by https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L46 ). Thus, invoking tensorboard fails with a failing import, but if you insert "backend." into the script at the appropriate location it works again.

**Comment by stefan-w** [comment]
This should be fixed by #1020 - will close when I had the chance to verify.

**Comment by panmari** [comment]
I fixed this bug in #1020, I think this issue can be closed @ptc-swalk

**Comment by martinwicke** [comment]
Thanks!
