### ISSUE TITLE
In reader.py, line 17 throws error on python 3.5. The decode phrase should be removed, and then it works

### ISSUE THREAD

**Issue by ndvbd** [tensorflow/tensorflow#10004]
In reader.py, line 17 throws error on python 3.5. The decode phrase should be removed, and then it works

**Comment by skye** [comment]
Are you talking about tensorflow/contrib/saved_model/python/saved_model/reader.py? I suggest trying the saved_model functionality that's now in core TensorFlow: https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/python/saved_model/README.md

**Comment by nadavb** [comment]
I am talking about this one:

https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/reader.py

**Comment by skye** [comment]
Line 17 is a comment, do you mean that needs to be removed? Can you post the error you're seeing?

**Comment by nadavb** [comment]
Sorry, it's line 30

**Comment by skye** [comment]
Please provide details about what platform you are using  (operating system, architecture), and the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new). This seems like it might be platform-specific. We'll need to be able to repro the problems ourselves to fix.

**Comment by nadavb** [comment]
Hi Skye! Hope all is well.

I'm talking about python 3.5, and TF 1.1

The code outputs the following error: AttributeError: 'str' object has no attribute 'decode'
at the line:   return f.read().decode("utf-8").replace("\n", "<eos>").split()

That's because the string is already decoded.

If you change the line to: return f.read().replace("\n", "<eos>").split()   - all works well.

**Comment by aselle** [comment]
@nadavb, could you prepare a pull-request that  makes this change (in a way that doesn't break python2 of course)

**Comment by nadavb** [comment]
That's the pull request - https://github.com/tensorflow/models/pull/1512

It asks me to sign some CLA agreement, which I will skip for now.

**Comment by michaelisard** [comment]
Marking contributions welcome while we are waiting for the PR.

**Comment by rthadur** [comment]
We do not see this file in the models repo anymore , so this issue is not relevant ,closing this issue. Thank you
