### ISSUE TITLE
Segmentation fault on quit() tensorflow-ppc64

### ISSUE THREAD

**Issue by davideleoni90** [tensorflow/tensorflow#10001]
### System information
- **Fedora 24 4.7.4-200.fc24.ppc64 #1 SMP Thu Sep 22 17:40:37 UTC 2016 ppc64 ppc64 ppc64 GNU/Linux**:
- **TensorFlow installed from source**
- **TensorFlow version:  1.1.0-rc1**
- **Bazel version: 0.4.5-2017-05-12**
- **Exact command to reproduce**:

1. `python`
2. `import tensorflow as tf`
3. `hello = tf.constant('Hello, TensorFlow!')`
4. `sess = tf.Session()`
5. `print(sess.run(hello))`
6. `quit()`

### Describe the problem
Even with the simple above example, when I import tensorflow in python I get a segmentation fault at the moment of terminating python; all commands before `quit()` are executed correctly

### Source code / logs
`Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00003fffae6b8d78 in .std::_Function_handler<void (tensorflow::OpKernel*), tensorflow::DirectSession::GetOrCreateExecutors(tensorflow::thread::ThreadPool*, tensorflow::gtl::ArraySlice<std::string>, tensorflow::gtl::ArraySlice<std::string>, tensorflow::gtl::ArraySlice<std::string>, tensorflow::DirectSession::ExecutorsAndKeys**, tensorflow::DirectSession::RunStateArgs*)::{lambda(tensorflow::OpKernel*)#2}>::_M_invoke(std::_Any_data const&, tensorflow::OpKernel*&&) ()
   from /home/shady/dleoni/python_build/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so`

**Comment by drpngx** [comment]
@npanpaliya any idea?

@davideleoni90 could you try with asan perhaps? Any chance to get line numbers?

**Comment by npanpaliya** [comment]
I checked it on a system "Linux f9b14d7ac714 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:55:30 UTC 2017 ppc64le ppc64le ppc64le GNU/Linux" with tensorflow 1.1.0 and quit() didn't give segmentation fault. Could you please try upgrading Tensorflow to 1.1.0 (final release)?

**Comment by davideleoni90** [comment]
@npanpaliya I had installed the last version from this fork

[https://github.com/PPC64/tensorflow](https://github.com/PPC64/tensorflow)

I have just tried with final release (1.1.0) from

[https://github.com/tensorflow/tensorflow](https://github.com/tensorflow/tensorflow)

but I get the following error during the build process:

`ERROR: /home/shady/dleoni/bazel_output_base_final/external/protobuf/BUILD:609:1: C++ compilation of rule '@protobuf//:python/google/protobuf/internal/_api_implementation.so' failed: gcc failed: error executing command 
  (cd /home/shady/dleoni/bazel_output_base_final/execroot/tensorflow_final && \
  exec env - \
    LD_LIBRARY_PATH=/home/shady/dleoni/python_build/lib/engines:/home/shady/dleoni/openssl_build/lib:/usr/lib64/openssl:/home/shady/dleoni/python_build/lib \
    PATH=/home/shady/dleoni/bazel/output:/home/shady/dleoni/python_build/bin:/home/shady/dleoni/python_build/include/python2.7:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/shady/.local/bin:/home/shady/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/home/shady/dleoni/python_build/bin/python \
    PYTHON_LIB_PATH=/home/shady/dleoni/python_build/lib/python2.7/site-packages \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL=0 \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-march=native' '-std=c++0x' '-march=native' '-D_GLIBCXX_USE_CXX11_ABI=0' -MD -MF bazel-out/local-opt/bin/external/protobuf/_objs/python/google/protobuf/internal/_api_implementation.so/external/protobuf/python/google/protobuf/internal/api_implementation.pic.d '-frandom-seed=bazel-out/local-opt/bin/external/protobuf/_objs/python/google/protobuf/internal/_api_implementation.so/external/protobuf/python/google/protobuf/internal/api_implementation.pic.o' -fPIC -iquote external/protobuf -iquote bazel-out/local-opt/genfiles/external/protobuf -iquote external/local_config_python -iquote bazel-out/local-opt/genfiles/external/local_config_python -iquote external/bazel_tools -iquote bazel-out/local-opt/genfiles/external/bazel_tools -isystem external/local_config_python/python_include -isystem bazel-out/local-opt/genfiles/external/local_config_python/python_include -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -DPYTHON_PROTO2_CPP_IMPL_V2 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/protobuf/python/google/protobuf/internal/api_implementation.cc -o bazel-out/local-opt/bin/external/protobuf/_objs/python/google/protobuf/internal/_api_implementation.so/external/protobuf/python/google/protobuf/internal/api_implementation.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error: unrecognized command line option '-march=native'; did you mean '-mcpu=native'?
gcc: error: unrecognized command line option '-march=native'; did you mean '-mcpu=native'?
Target //tensorflow/tools/pip_package:build_pip_package failed to build`

@drpngx I have never used asan: can you please give me some indication on how to debug with asan?
The version of my gcc compiler is

`gcc version 6.2.1 20160916 (Red Hat 6.2.1-2) (GCC) `

Thank you both

**Comment by npanpaliya** [comment]
This build error is because of gcc version being used for building. We use gcc 5.4.0 and tensorflow works perfectly with that version. 
If you want to try with gcc 6, then for above mentioned error, try changing "default_cc_opt_flags" in tensorflow/configure script to use -mcpu instead of -march, as the error suggests.

**Comment by davideleoni90** [comment]
I replace `march` with `mcpu` and the building process went forward, but not much, and I got the following error:

`ERROR: /home/shady/dleoni/tensorflow_final/tensorflow/tensorboard/components/tf_graph_common_d3v4/BUILD:26:1: Executing genrule //tensorflow/tensorboard/components/tf_graph_common_d3v4:ts failed: bash failed: error executing command 
  (cd /home/shady/dleoni/bazel_output_base_final/execroot/tensorflow_final && \
  exec env - \
    LD_LIBRARY_PATH=/home/shady/dleoni/python_build/lib/engines:/home/shady/dleoni/openssl_build/lib:/usr/lib64/openssl:/home/shady/dleoni/python_build/lib \
    PATH=/home/shady/dleoni/bazel/output:/home/shady/dleoni/python_build/bin:/home/shady/dleoni/python_build/include/python2.7:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/shady/.local/bin:/home/shady/bin \
    PYTHON_BIN_PATH=/home/shady/dleoni/python_build/bin/python \
    PYTHON_LIB_PATH=/home/shady/dleoni/python_build/lib/python2.7/site-packages \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/genfiles/external/com_microsoft_typescript/tsc.sh --inlineSourceMap --inlineSources --noResolve --declaration --outDir bazel-out/local-opt/genfiles/tensorflow/tensorboard/components/tf_graph_common_d3v4 external/com_microsoft_typescript/lib.es6.d.ts bazel-out/local-opt/genfiles/tensorflow/tensorboard/components/tf_imports_d3v4/d3.d.ts external/org_definitelytyped/lodash.d.ts external/org_definitelytyped/polymer.d.ts external/org_definitelytyped/webcomponents.js.d.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/annotation.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/colors.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/common.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/contextmenu.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/edge.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/externs.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/graph.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/hierarchy.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/layout.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/minimap.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/node.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/parser.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/proto.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/render.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/scene.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/template.ts tensorflow/tensorboard/components/tf_graph_common_d3v4/util.ts'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 126.
bazel-out/host/genfiles/external/com_microsoft_typescript/tsc.sh: line 6: /home/shady/dleoni/bazel_output_base_final/execroot/tensorflow_final/external/org_nodejs/bin/node: cannot execute binary file: Exec format error
bazel-out/host/genfiles/external/com_microsoft_typescript/tsc.sh: line 6: /home/shady/dleoni/bazel_output_base_final/execroot/tensorflow_final/external/org_nodejs/bin/node: Success
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 28.696s, Critical Path: 23.67s`

**Comment by npanpaliya** [comment]
@davideleoni90 , could you tell me the build steps that you are executing with configure options? Because I've never seen this error.

**Comment by davideleoni90** [comment]
@npanpaliya Here are the steps:

1. `mkdir tensorflow_build`
2. `./configure --prefix=/home/shady/dleoni/tensorflow_build`
3. `mkdir bazel_output_base`
4. `mkdir bazel_output_user_root`
5. `bazel --output_base=/home/shady/dleoni/bazel_output_base --output_user_root=/home/shady/dleoni/bazel_output_user_root build --config=opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package`

**Comment by davideleoni90** [comment]
Uninstalling the pip package and recompiling with bazel issuing the following command

`bazel --output_base=/home/shady/dleoni/bazel_output_base --output_user_root=/home/shady/dleoni/bazel_output_user_root build -c opt -c dbg --strip=never --verbose_failures --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package`

magically solved the problem.

Thank you all for your support
