### ISSUE TITLE
[feature] sparse_reduce_max and sparse_reduce_max_sparse 

### ISSUE THREAD

**Issue by asiakaczmar** [tensorflow/tensorflow#10002]
Hi guys,

Currently we work on sparse tensors, and we are missing some sparse operations. Is there any way you could add sparse_reduce_max and sparse_reduce_max_sparse operations as functions equivalent to existing tf.sparse_reduce_sum and tf.sparse_reduce_sum_sparse but with max operation as reducing function?

Thank you,

Joanna

**Comment by skye** [comment]
FYI @concretevitamin @jhseu

**Comment by concretevitamin** [comment]
I don't think we have immediate plans to implement these - happy to review PRs!  

In `sparse_reduce_sum_op.cc`, most logic can be factored out, and only [the aggregate function 
 .sum() here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sparse_reduce_sum_op.cc#L198) needs to be changed, I think.

**Comment by yongtang** [comment]
Created a PR #10056 to support the feature. Please take a look.

**Comment by AnishShah** [comment]
I think, this issue can be closed

**Comment by jhseu** [comment]
Yep

**Comment by prafiny** [comment]
Hi,
Is it tricky to implement the gradient for these kernels ?
Cheers,
Maxime
