### ISSUE TITLE
unable to install for new versin tensorflow 1.2

### ISSUE THREAD

**Issue by jeansely** [tensorflow/tensorflow#10015]
Hi,
 already installed  tensorflow 1.1 in python3.5 and OS  win64. but now for upgrade to "tensorflow-1.2.0rc0-cp35-cp35m-win_amd64.whl" the python TAKE error " unable to install tensorflow 1.2"

**Comment by jubjamie** [comment]
Can please provide much more information. Please post full console output. What was the full pip command you used? Are you within an environment. Can you confirm you are only installing the CPU version too.

**Comment by jeansely** [comment]
i tried for installing with "WinPython Control Panel" this modulo install files with ".whl"  format. i use CPU version. 
python= 3.5 , OS is windows. the message box was "unable to install tensorflow 1.2"

**Comment by gunan** [comment]
That looks like an issue in WinPython, please try looking through product forums of that tool.
This google search tells me a lot of users of this tool faced similar issues:
https://www.google.com/search?q=%22unable+to+install%22+winpython&oq=%22unable+to+install%22+winpython&aqs=chrome..69i64j46l3j69i57.1513j0j7&sourceid=chrome&ie=UTF-8

I will close this issue, as it is not a TF bug.

**Comment by jeansely** [comment]
I mean that I have not installed it "tensorflow1.2" with pip . i installed with "WinPython Control Panel" 

also already install tensorflow 1.1 with ""WinPython Control Panel"
