### ISSUE TITLE
feature request: make placeholder_with_default work in batch prediction

### ISSUE THREAD

**Issue by brandondutra** [tensorflow/tensorflow#10014]
cc @qimingj

I ran into an issue with building a model that has missing values. During training, I can fill in missing values via the options to tf.decode_csv or tf.parse_example. I want to make my exported saved model also handle missing values. I know how to do this if the model reads from tf.example string or csv string, but this is impossible if the model takes each input tensor individually through placeholders. 

I looked at tf.placeholder_with_default(), but this function has useless behavior in batch prediction. As an example:

```
import tensorflow as tf

with tf.Session() as sess:
	default = tf.placeholder_with_default([1], shape=[None])
	regular = tf.placeholder(tf.int32, shape=[None])

	id_default = tf.identity(default)
	id_regular = tf.identity(regular)

	print('1) normal 1 example', sess.run([id_default, id_regular], feed_dict={default: [2], regular: [5]}))
	print('2) normal batch example', sess.run([id_default, id_regular], feed_dict={default: [2, 2], regular: [5, 5]}))
	print('3) missing 1 column in batch', sess.run([id_default, id_regular], feed_dict={regular: [5, 5]}))
	print('4) missing some data', sess.run([id_default, id_regular], feed_dict={default: [2, None], regular: [5, 5]}))	
```
The output is
```
('1) normal 1 example', [array([2], dtype=int32), array([5], dtype=int32)])
('2) normal batch example', [array([2, 2], dtype=int32), array([5, 5], dtype=int32)])
('3) missing 1 column in batch', [array([1], dtype=int32), array([5, 5], dtype=int32)])
Traceback (most recent call last):
  File "placeholders.py", line 13, in <module>
    print('4) missing some data', sess.run([id_default, id_regular], feed_dict={default: [2, None], regular: [5, 5]}))
  File "/usr/local/google/home/brandondutra/miniconda2/envs/cml/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/google/home/brandondutra/miniconda2/envs/cml/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 938, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/usr/local/google/home/brandondutra/miniconda2/envs/cml/lib/python2.7/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: long() argument must be a string or a number, not 'NoneType'
```

Note how line 3 is incorrect: I expected a result of [1,1], [5,5]

Also, placeholder_with_default does not allow some values to be missing in a batch as line 4 shows. 

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04.1
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: ('v1.0.0-65-g4763edf-dirty', '1.0.1')
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: n/a

**Comment by brandondutra** [comment]
forgot to say, I do not know my batch size during prediction.

**Comment by skye** [comment]
FYI @mrry

**Comment by mrry** [comment]
Out of curiosity, why would you expect

```python
sess.run([id_default, id_regular], feed_dict={regular: [5, 5]})
```

...to return `[1, 1], [5, 5]`? The contract for `tf.placeholder_with_default()` is pretty simple: it produces its default value unless you feed it (and it offers some latitude for feeding values of different shapes). There's nothing in the program that associates `id_default` with the value of placeholder `regular` (no edge between them in the graph), so the value you feed for `regular` will never influence the value or `id_default`. 

I suspect you're looking for a higher-level input that maintains an association between two (or more?) tensors. That might well be a fine thing, but we'll need more information about the behavior you expect before we can tell if it's a reasonable thing to include.

**Comment by brandondutra** [comment]
I was comparing them to how tf.parse_example would work. If instead I passed two tf.examples (that had features named 'default' and 'regular'), and they both were missing the 'default' feature, and the feature spec had a default value for the 'default' feature, both examples would inject the default value when I call session.run. Now, this default injection would happen at tf.parse_example and not the placeholder.

I fully agree the values of regular do not influence id_default. During bath prediction of a trained model, I'm thinking of the line (note I changed the data)

`sess.run([id_default, id_regular], feed_dict={regular: [5, 6]})`

as a batch prediction request. I'm think of this as if there are two requests

Request 1) get id_default, id_regular given {regular=5} (so id_default would use the default value, and I would get id_default=1, id_regular=5

Request 2) get id_default, id_regular given {regular=6} (so id_default would use the default value, and I would get id_default=1, id_regular=6

I guess the wall I'm running into is that I cannot tell TF I want to run batch prediction and it should replace None with that tensor's placeholder. For example, I would like 

`sess.run([id_default, id_regular], feed_dict={regular: [5, 6, 7], default: [None, 3, None]})`

To return [1,3,1], [5,6,7]. Is this possible using placeholders? Or is there some kind of 'session.batch_run'? I think the only way to get this working currently is to use csv input or tf.example input, and not tensor input.

**Comment by qimingj** [comment]
In the case 3): sess.run([id_default, id_regular], feed_dict={regular: [5, 5]})

In order to get it working as expected we'll need:

  default = tf.placeholder_with_default(tf.ones_like(regular), shape=[None])

It connects "regular" with "default" that way. Otherwise, you do need a "batch_run" so TF can infer the batch size.

In the case 4): sess.run([id_default, id_regular], feed_dict={default: [2, None], regular: [5, 5]})

It doesn't complain if you use tf.float32, and you get:

('4) missing some data', [array([  2.,  nan], dtype=float32), array([ 5.,  5.], dtype=float32)])

Don't know why it doesn't work for int types. If it works, we may be able to use tf.scan to update "nan" values to default values.

**Comment by michaelisard** [comment]
@brandondutra how is that workaround for you?

**Comment by brandondutra** [comment]
I abandoned this and instead used 1 placeholder of a csv string, and I let decode_csv deal with the defaults. I still think placeholder_with_default is broken for batch prediction.

**Comment by michaelisard** [comment]
Closing for now in the absence of a specific feature request for a different design.
