### ISSUE TITLE
Java Api String tensors support

### ISSUE THREAD

**Issue by dhasegan** [tensorflow/tensorflow#10019]
from [Tensor.java](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/java/src/main/java/org/tensorflow/Tensor.java#L90):
**non-scalar DataType.STRING tensors are not supported yet**

Is there a plan for adding them for the Java interface?

**Comment by asimshankar** [comment]
Closing this as a duplicate of #8531 
@erranli was working on this, not sure of the current status.
