### ISSUE TITLE
tensorboard fails with `Fatal error in launcher: Unable to create process using '"'`

### ISSUE THREAD

**Issue by darthdeus** [tensorflow/tensorflow#10017]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A, tensorboard command line issue
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 x64
- **TensorFlow installed from (source or binary)**: binary with Python 3.5, installed via pip
- **TensorFlow version (use command below)**: b'unknown' 1.1.0 (gpu version of TF)
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 8, cuDNN 5.1.10
- **GPU model and memory**: GTX 1080ti 11GB
- **Exact command to reproduce**: run `tensorboard`, get `Fatal error in launcher: Unable to create process using '"'`

### Describe the problem

Running `tensorboard` fails with `Fatal error in launcher: Unable to create process using '"'` no matter the command line arguments I pass.

**Comment by ali01** [comment]
Are you passing in any command line flags to tensorboard? It requires --logdir at the very least. Is there any additional output on standard out? Please provide the exact command you are running as well as any additional information that might help us debug this problem.

**Comment by darthdeus** [comment]
@ali01 I've tried multiple ways, but they all result in the same error

```
>tensorboard
Fatal error in launcher: Unable to create process using '"'
>mkdir foo
>tensorboard --logdir=foo
Fatal error in launcher: Unable to create process using '"'
>tensorboard --logdir foo
Fatal error in launcher: Unable to create process using '"'
```

**Comment by darthdeus** [comment]
Turns out the problem was not actually caused by TF, but after moving the `conda` environment where it was installed (renaming the env), see https://github.com/winpython/winpython/issues/410. I didn't use tensorboard before the rename so I thought it just didn't work from the beginning.

Anyway, removing the `conda` env and re-creating a new one and re-installing TF solved the issue.

**Comment by stepanveret** [comment]
I had the same problem. Intsted 
`tensorboard --logdir=/tmp/tboard --port=7007 &` and any of such comands this worked:
`python -m tensorflow.tensorboard --logdir=/tmp/tboard --port=7007 &`

**Comment by crazysal** [comment]
Facing same issue. 
###### System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N/A, tensorboard command line issue
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
TensorFlow installed from (source or binary): conda install -c anaconda tensorflow-tensorboard 
TensorFlow version (use command below): 1.4.0
Bazel version (if compiling from source): N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: run tensorboard, get Fatal error in launcher: Unable to create process using '"'
> (tensorflow) C:\Users\salee>tensorboard
> Fatal error in launcher: Unable to create process using '"'
> 
> (tensorflow) C:\Users\salee> E:
> 
> (tensorflow) E:\>cd repos
> 
> (tensorflow) E:\repos>cd deep-siamese-text-similarity
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity>cd runs
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs>cd 1521406230
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230>cd summaries
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230\summaries>cd train
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230\summaries\train>tensorboard --logdir events.out.tfevents.1521406241.MAUVE-JEDI
> Fatal error in launcher: Unable to create process using '"'
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230\summaries\train>tensorboard --logdir ./events.out.tfevents.1521406241.MAUVE-JEDI
> Fatal error in launcher: Unable to create process using '"'
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230\summaries\train>python -m tensorflow.tensorboard --logdir=./events.out.tfevents.1521406241.MAUVE-JEDI --port=7007
> C:\Users\salee\Anaconda3\envs\tensorflow\python.exe: No module named tensorflow.tensorboard
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230\summaries\train>python -m tensorboard --logdir=./events.out.tfevents.1521406241.MAUVE-JEDI --port=7007
> C:\Users\salee\Anaconda3\envs\tensorflow\python.exe: No module named tensorboard.__main__; 'tensorboard' is a package and cannot be directly executed
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230\summaries\train>tensorboard --logdir=./events.out.tfevents.1521406241.MAUVE-JEDI --port=7007
> Fatal error in launcher: Unable to create process using '"'
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230\summaries\train>tensorboard --logdir=./ --port=7007
> Fatal error in launcher: Unable to create process using '"'
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230\summaries\train>tensorboard --logdir=/ --port=7007
> Fatal error in launcher: Unable to create process using '"'
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230\summaries\train>tensorboard --logdir=./ --port=7007
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230\summaries\train>cd ..
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230\summaries>tensorboard --logdir=train --port=7007
> Fatal error in launcher: Unable to create process using '"'
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230\summaries>tensorboard --logdir=train --port=7007
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230\summaries>cd ..
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs\1521406230>cd ..
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity\runs>cd ..
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity>tensorboard --logdir=runs\1521480347\summaries\train --port=7007
> Fatal error in launcher: Unable to create process using '"'
> 
> (tensorflow) E:\repos\deep-siamese-text-similarity>tensorboard --logdir="runs/1521480347/summaries/train" --port=7007
> Fatal error in launcher: Unable to create process using '"'

**Comment by YoungC2015** [comment]
@darthdeus This works, that means the problem probably is the space in "program files".  I usually has this problem while using powershell. Besides, adding space("\x20") doesn't work for me, I change mine to "python3.exe" plus some NULL char("\x00").

**Comment by darthdeus** [comment]
I'm confused, why would the null char help?

**Comment by kochul2000** [comment]
@dreamhuan you are a GENIUS

**Comment by zzhixin** [comment]
Same problem after rename conda env. Solved it by reinstall tensorboard using pip.

**Comment by dreamhuan** [comment]
--------------------------------------您好，您发给我的信件已经收到。谢谢！傅凯琪--------------------------------------
