### ISSUE TITLE
about tf.train.ExponentialMovingAverage

### ISSUE THREAD

**Issue by hhwhbf** [tensorflow/tensorflow#10029]
Hi,I met a little problem when use this API.
"/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?"
And I saw someone written same problem in this issue https://github.com/tensorflow/tensorflow/issues/5827
but in comments of the issue,I did not find a efficient method to solve this problem.
By the way,a code ,such as 
```
def f(v):
    ema = tf.train.ExponentialMovingAverage(0.9)
    vema = ema.apply([v])
    return vema

with tf.variable_scope('s'):
    v1 = tf.get_variable('W', shape=[])
    v1 = v1 + 1
    f(v1)
with tf.variable_scope('s', reuse=True):
    v2 = tf.get_variable('W', shape=[])
    v2 = v2 + 2
    `f(v2)```
```
can normally run with tensorflow 0.11 but can't run with tensorflow 0.12 or higher version.
I hope there will be a valid method to solve this problem.

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
