### ISSUE TITLE
Error while executing TF program with TF_CPP_MIN_VLOG_LEVEL=1

### ISSUE THREAD

**Issue by karanaggarwal1994** [tensorflow/tensorflow#10023]
I got this error when I exported TF_CPP_MIN_VLOG_LEVEL=1 and TF_CPP_MIN_LOG_LEVEL=1 to see the LOG files . I got this error.
> SetArgvFromEnv
> [libprotobuf ERROR external/protobuf/src/google/protobuf/io/zero_copy_stream_impl_lite.cc:173] Cannot allocate buffer larger than kint32max for StringOutputStream.
> 2017-05-19 10:13:31.716688: F tensorflow/compiler/tf2xla/dump_graph.cc:67] Non-OK-status: WriteTextProto(Env::Default(), path, graph_def) status: Failed precondition: Unable to convert proto to text.
> Aborted

**Comment by drpngx** [comment]
Your graph is too large to dump out. Just comment out that line or don't use VLOG.
