### ISSUE TITLE
Allow Disabling Password and Token Requirement in Jupyter Notebook

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#10045]
Jupyter Notebook [allows disabling password / token requirements](http://jupyter-notebook.readthedocs.io/en/latest/security.html#alternatives-to-token-authentication) however the way `jupyter_notebook_config.py` is coded does not allow for this.
```
c.NotebookApp.password = passwd(os.environ['PASSWORD'])
```
should be be written as:
```
password = os.environ['PASSWORD']
if password:
   c.NotebookApp.password = passwd(password)
else:
   c.NotebookApp.password = ''
```

since `passwd('') == 'sha1:7d18ca389fad:8b3a353d37eb3caf006aa47a5cd6559511979278'`

**Comment by ali01** [comment]
Thanks @cancan101, for pointing this out. @mrry, are we intentionally disallowing the disabling of jupyter's password/token requirements, or is it ok to do as suggested by @cancan101.

**Comment by mrry** [comment]
I have no idea about that file. The fix sounds reasonable though!
