### ISSUE TITLE
Error happens when using tensorboard:No handlers could be found for logger "werkzeug"

### ISSUE THREAD

**Issue by phipps553** [tensorflow/tensorflow#10077]
I install the tensorflow-gpu 1.1.0 by anaconda-pip, but every time i open http://0.0.0.0:6006 to start tensorboard the error happens.I have already installed  "werkzeug".

`No handlers could be found for logger "werkzeug"`

**Comment by wqj97** [comment]
i have the same problem
have u solved it ?

**Comment by abhishekg2389** [comment]
I am also facing this issue. Has anybody solved this issue?

**Comment by jart** [comment]
Does this problem happen with 1.2.0rc0? What operating system are you guys using?

**Comment by abhishekg2389** [comment]
@jart I am using ubuntu-xenial-16.04 and installed tensorflow using "sudo pip install --upgrade tensorflow".

**Comment by wqj97** [comment]
@jart 
This problem also happen with 1.2.0rc1
System: OSX 10.12.5
Python: 2.7.13
tensorflow: 1.2.0rc1

**Comment by wqj97** [comment]
@jart 
I found a way to fix this
If use relative path like
```
tensorboard --logdir=./logs/
```
This problem will happen
But if I use absolute path like
```
tensorboard --logdir=/Users/wanqianjun/Desktop/logs
```
It works well

**Comment by abhishekg2389** [comment]
@wqj97 It is still giving that problem with absolute path

**Comment by jewdore** [comment]
I move the logs folder to home dir (~) ,fix the problem

**Comment by wqj97** [comment]
@abhishekg2389 
```
cd ~
tensorboard --logdir= "absolute path"
```

**Comment by phipps553** [comment]
@wqj97 @jewdore Your way fix the problem.Thanks a lot!

**Comment by gcucurull** [comment]
I had the same problem and I suspect that having non-ASCII characters in the path was the cause, removing accents from the path solved the problem for me (in addition to using an absolute path).

**Comment by hedongya** [comment]
The true reason for this problem is that there shouldn't be Chinese words in the parth
