### ISSUE TITLE
Nightly binaries are not being built successfully

### ISSUE THREAD

**Issue by terrytangyuan** [tensorflow/tensorflow#10081]
Seems like the nightly builds have been failing for a while. For example, Python 3 Mac GPU build history [here](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-mac-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=gpu-mac/). Is this something being worked on since it's been a month or so.

**Comment by yaroslavvb** [comment]
According to @martinwicke Mac slaves are down (Google IO craziness?)
I've put a macos version built from head 4 days here: https://github.com/yaroslavvb/tensorflow-community-wheels/issues/18

**Comment by terrytangyuan** [comment]
Thanks! @yaroslavvb

**Comment by gunan** [comment]
If you are interested in mac-gpu pip packages, we are dropping support for them starting 1.2, as announced during 1.1 release.
The rest, we are now triaging all remaining issues.

**Comment by terrytangyuan** [comment]
Thanks! Please keep me posted.

**Comment by terrytangyuan** [comment]
This was fixed long time ago but seems like it's failing again. For example, last successful [MAC CPU nightly build](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=mac-slave/) was on June 28th. Just in case you are not aware of this.

**Comment by gunan** [comment]
As nightlies run a much larger suite of tests, their breakages are expected. We try to fix them before each release.
@av8ramit could you take a look into the failures to see if they are flakes or actual failures.
Please escalate to owners of components if you find actual breakages.

**Comment by av8ramit** [comment]
http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/544/
Nightlies are passing now!

**Comment by terrytangyuan** [comment]
Great. Thanks!
