### ISSUE TITLE
Type check failed in piecewise_constant.

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#10086]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:archlinux
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:v1.1.0-rc2-1140-g513b1e4 1.1.0-rc2 

```python
global_step = tf.get_variable('gs', trainable=False, dtype=tf.int32, shape=[])
global_step = tf.get_default_graph().get_tensor_by_name('gs:0')
boundaries = [100000, 110000]
values = [1.0, 0.5, 0.1]
learning_rate = tf.train.piecewise_constant(global_step, boundaries, values)
```
```
    learning_rate = tf.train.piecewise_constant(global_step, boundaries, values)
  File "/xxx/.local/lib/python3.6/site-packages/tensorflow/python/training/learning_rate_decay.py", line 144, in piecewise_constant
    b.dtype, x.dtype))
ValueError: Boundaries (<dtype: 'int32'>) must have the same dtype as x (<dtype: 'int32_ref'>).
```
I wonder if the check is over strict? Is there a reason to distinguish `int32` and `int32_ref` here?

**Comment by jmchen-g** [comment]
@vrv Could you take a look please? Thanks.

**Comment by vrv** [comment]
No, we should probably be checking base dtype there. Would you like to send a PR?
