### ISSUE TITLE
pip install  --user  tensorflow==1.2.0rc0

### ISSUE THREAD

**Issue by ChakritRakuang** [tensorflow/tensorflow#10085]
Error occurred:
Non-zero exit code(1)
![untitled](https://cloud.githubusercontent.com/assets/25774969/26286789/70e3d8be-3e97-11e7-8e60-6bcb27257d52.jpg)

**Comment by jubjamie** [comment]
I had issues downloading via pip so just used the latest whl from the last stable build from jenkins.

**Comment by pbilling** [comment]
I am also unable to download via pip.

    $ pip install tensorflow
    Collecting tensorflow
      Could not find a version that satisfies the requirement tensorflow (from versions: )
    No matching distribution found for tensorflow

**Comment by jubjamie** [comment]
Are you using Windows 10? CPU version? More information please.

**Comment by pbilling** [comment]
1) I tried downloading tensorflow on my local machine running Mac OS 10.10.5 on a 3GHz i7 using pip 9.0.1 for python 2.7 & 3.5 and both failed with the same "Could not find a version..." error.

```
$ pip --version
pip 9.0.1 from /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (python 3.5)
$ pip install tensorflow
Collecting tensorflow
    Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
```
```
$ pip2 --version
pip 9.0.1 from /Library/Python/2.7/site-packages (python 2.7)
$ pip2 install tensorflow
Collecting tensorflow
    Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
```

2) I tried the same process on our linux cluster running CentOS 6.9: using pip 9.0.1 to install tensorflow for python 2.7 & 3.5. This time, I was able to successfully install tensorflow-1.2.0rc0 using pip for python 3.5, but the python 2.7 install failed.

```
$ pip2 --version
pip 9.0.1 from /srv/gsfs0/software/python/python-2.7/lib/python2.7/site-packages (python 2.7)
$ pip2 install tensorflow==1.2.0rc0
Collecting tensorflow==1.2.0rc0
  Could not find a version that satisfies the requirement tensorflow==1.2.0rc0 (from versions: )
No matching distribution found for tensorflow==1.2.0rc0
```

```
$ pip3 --version
pip 9.0.1 from /srv/gsfs0/software/python/3.5.1/lib/python3.5/site-packages (python 3.5)
$ pip3 install tensorflow==1.2.0rc0
Collecting tensorflow==1.2.0rc0
  Downloading tensorflow-1.2.0rc0-cp35-cp35m-manylinux1_x86_64.whl (34.6MB)
    100% |████████████████████████████████| 34.6MB 44kB/s
...
Successfully installed bleach-1.5.0 html5lib-0.9999999 markdown-2.2.0 tensorflow-1.2.0rc0
```

3) I also tried installing tensorflow on the stock python:2.7.13 Docker image running Debian GNU/Linux 8 (jessie), on the same mac from step 1. Here I was able to successfully install tensorflow-1.2.0rc0 for python 2.7.

```
# pip install tensorflow==1.2.0rc0
Collecting tensorflow==1.2.0rc0
  Downloading tensorflow-1.2.0rc0-cp27-cp27mu-manylinux1_x86_64.whl (34.6MB)
...
eSuccessfully installed bleach-1.5.0 html5lib-0.9999999 markdown-2.2.0 tensorflow-1.2.0rc0
```

**Comment by Tim15** [comment]
Same issue: Trying to `pip install tensorflow`, but get 
```
Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
```
I'm running on a Docker image (`python:3-alpine`). Weirdly, I can install it on the Docker image `python`. Am I missing something with regard to `pip`?
```
# uname -a
Linux b2a048fac069 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 Linux
```

**Comment by jubjamie** [comment]
Have you tried installing the .whl's directly from pypi and seeing if they work. For example a macos CPU build for python 3.5 might be [this .whl file here](https://pypi.python.org/packages/01/4b/46b6208bddd2ff076ba2ade287394a293be2ae3344917c2c69393bfeffb6/tensorflow-1.2.0rc0-cp35-cp35m-macosx_10_11_x86_64.whl#md5=ef588a86efadd4a8a2c540658373fbcc).

[See the full list here](https://pypi.python.org/pypi/tensorflow) and see if you can install directly like this. Not a permanent solution but i've had pip get upset before and say there isn't a compatible version when i know that there is. Hope this helps!

**Comment by jart** [comment]
Yes try installing the whl file. It's possible that whatever version of pip inside IntelliJ is less than 8.1. See https://www.tensorflow.org/install/install_linux

I'm not sure why other people in this thread who have pip 9 would have problems. Any thoughts @yifeif?

**Comment by yifeif** [comment]
Could you try `python -c "from pip import pep425tags;print(pep425tags.supported_tags)"` to check what are supported tags on your system?

**Comment by pbilling** [comment]
I am also unable to install tensorflow using the whl file.

```
$ pip install https://pypi.python.org/packages/b1/35/62fdae318152cc1860cd7e4155165cbda6944b5727f09b6fc5a53c96d486/tensorflow-1.2.0rc0-cp27-cp27m-macosx_10_11_x86_64.whl#md5=772ab0dd05fd7e1da59bb8d642fd126c
tensorflow-1.2.0rc0-cp27-cp27m-macosx_10_11_x86_64.whl is not a supported wheel on this platform.
```

@yifeif Here are my supported tags:

```
$ python -c "from pip import pep425tags;print(pep425tags.supported_tags)"
[('cp27', 'cp27m', 'macosx_10_10_x86_64'), ('cp27', 'cp27m', 'macosx_10_10_intel'), ('cp27', 'cp27m', 'macosx_10_10_fat64'), ('cp27', 'cp27m', 'macosx_10_10_fat32'), ('cp27', 'cp27m', 'macosx_10_10_universal'), ('cp27', 'cp27m', 'macosx_10_9_x86_64'), ('cp27', 'cp27m', 'macosx_10_9_intel'), ('cp27', 'cp27m', 'macosx_10_9_fat64'), ('cp27', 'cp27m', 'macosx_10_9_fat32'), ('cp27', 'cp27m', 'macosx_10_9_universal'), ('cp27', 'cp27m', 'macosx_10_8_x86_64'), ('cp27', 'cp27m', 'macosx_10_8_intel'), ('cp27', 'cp27m', 'macosx_10_8_fat64'), ('cp27', 'cp27m', 'macosx_10_8_fat32'), ('cp27', 'cp27m', 'macosx_10_8_universal'), ('cp27', 'cp27m', 'macosx_10_7_x86_64'), ('cp27', 'cp27m', 'macosx_10_7_intel'), ('cp27', 'cp27m', 'macosx_10_7_fat64'), ('cp27', 'cp27m', 'macosx_10_7_fat32'), ('cp27', 'cp27m', 'macosx_10_7_universal'), ('cp27', 'cp27m', 'macosx_10_6_x86_64'), ('cp27', 'cp27m', 'macosx_10_6_intel'), ('cp27', 'cp27m', 'macosx_10_6_fat64'), ('cp27', 'cp27m', 'macosx_10_6_fat32'), ('cp27', 'cp27m', 'macosx_10_6_universal'), ('cp27', 'cp27m', 'macosx_10_5_x86_64'), ('cp27', 'cp27m', 'macosx_10_5_intel'), ('cp27', 'cp27m', 'macosx_10_5_fat64'), ('cp27', 'cp27m', 'macosx_10_5_fat32'), ('cp27', 'cp27m', 'macosx_10_5_universal'), ('cp27', 'cp27m', 'macosx_10_4_intel'), ('cp27', 'cp27m', 'macosx_10_4_fat32'), ('cp27', 'cp27m', 'macosx_10_4_universal'), ('cp27', 'cp27m', 'macosx_10_3_fat32'), ('cp27', 'cp27m', 'macosx_10_3_universal'), ('cp27', 'cp27m', 'macosx_10_2_fat32'), ('cp27', 'cp27m', 'macosx_10_2_universal'), ('cp27', 'cp27m', 'macosx_10_1_fat32'), ('cp27', 'cp27m', 'macosx_10_1_universal'), ('cp27', 'cp27m', 'macosx_10_0_fat32'), ('cp27', 'cp27m', 'macosx_10_0_universal'), ('cp27', 'none', 'macosx_10_10_x86_64'), ('cp27', 'none', 'macosx_10_10_intel'), ('cp27', 'none', 'macosx_10_10_fat64'), ('cp27', 'none', 'macosx_10_10_fat32'), ('cp27', 'none', 'macosx_10_10_universal'), ('cp27', 'none', 'macosx_10_9_x86_64'), ('cp27', 'none', 'macosx_10_9_intel'), ('cp27', 'none', 'macosx_10_9_fat64'), ('cp27', 'none', 'macosx_10_9_fat32'), ('cp27', 'none', 'macosx_10_9_universal'), ('cp27', 'none', 'macosx_10_8_x86_64'), ('cp27', 'none', 'macosx_10_8_intel'), ('cp27', 'none', 'macosx_10_8_fat64'), ('cp27', 'none', 'macosx_10_8_fat32'), ('cp27', 'none', 'macosx_10_8_universal'), ('cp27', 'none', 'macosx_10_7_x86_64'), ('cp27', 'none', 'macosx_10_7_intel'), ('cp27', 'none', 'macosx_10_7_fat64'), ('cp27', 'none', 'macosx_10_7_fat32'), ('cp27', 'none', 'macosx_10_7_universal'), ('cp27', 'none', 'macosx_10_6_x86_64'), ('cp27', 'none', 'macosx_10_6_intel'), ('cp27', 'none', 'macosx_10_6_fat64'), ('cp27', 'none', 'macosx_10_6_fat32'), ('cp27', 'none', 'macosx_10_6_universal'), ('cp27', 'none', 'macosx_10_5_x86_64'), ('cp27', 'none', 'macosx_10_5_intel'), ('cp27', 'none', 'macosx_10_5_fat64'), ('cp27', 'none', 'macosx_10_5_fat32'), ('cp27', 'none', 'macosx_10_5_universal'), ('cp27', 'none', 'macosx_10_4_intel'), ('cp27', 'none', 'macosx_10_4_fat32'), ('cp27', 'none', 'macosx_10_4_universal'), ('cp27', 'none', 'macosx_10_3_fat32'), ('cp27', 'none', 'macosx_10_3_universal'), ('cp27', 'none', 'macosx_10_2_fat32'), ('cp27', 'none', 'macosx_10_2_universal'), ('cp27', 'none', 'macosx_10_1_fat32'), ('cp27', 'none', 'macosx_10_1_universal'), ('cp27', 'none', 'macosx_10_0_fat32'), ('cp27', 'none', 'macosx_10_0_universal'), ('py2', 'none', 'macosx_10_10_x86_64'), ('py2', 'none', 'macosx_10_10_intel'), ('py2', 'none', 'macosx_10_10_fat64'), ('py2', 'none', 'macosx_10_10_fat32'), ('py2', 'none', 'macosx_10_10_universal'), ('py2', 'none', 'macosx_10_9_x86_64'), ('py2', 'none', 'macosx_10_9_intel'), ('py2', 'none', 'macosx_10_9_fat64'), ('py2', 'none', 'macosx_10_9_fat32'), ('py2', 'none', 'macosx_10_9_universal'), ('py2', 'none', 'macosx_10_8_x86_64'), ('py2', 'none', 'macosx_10_8_intel'), ('py2', 'none', 'macosx_10_8_fat64'), ('py2', 'none', 'macosx_10_8_fat32'), ('py2', 'none', 'macosx_10_8_universal'), ('py2', 'none', 'macosx_10_7_x86_64'), ('py2', 'none', 'macosx_10_7_intel'), ('py2', 'none', 'macosx_10_7_fat64'), ('py2', 'none', 'macosx_10_7_fat32'), ('py2', 'none', 'macosx_10_7_universal'), ('py2', 'none', 'macosx_10_6_x86_64'), ('py2', 'none', 'macosx_10_6_intel'), ('py2', 'none', 'macosx_10_6_fat64'), ('py2', 'none', 'macosx_10_6_fat32'), ('py2', 'none', 'macosx_10_6_universal'), ('py2', 'none', 'macosx_10_5_x86_64'), ('py2', 'none', 'macosx_10_5_intel'), ('py2', 'none', 'macosx_10_5_fat64'), ('py2', 'none', 'macosx_10_5_fat32'), ('py2', 'none', 'macosx_10_5_universal'), ('py2', 'none', 'macosx_10_4_intel'), ('py2', 'none', 'macosx_10_4_fat32'), ('py2', 'none', 'macosx_10_4_universal'), ('py2', 'none', 'macosx_10_3_fat32'), ('py2', 'none', 'macosx_10_3_universal'), ('py2', 'none', 'macosx_10_2_fat32'), ('py2', 'none', 'macosx_10_2_universal'), ('py2', 'none', 'macosx_10_1_fat32'), ('py2', 'none', 'macosx_10_1_universal'), ('py2', 'none', 'macosx_10_0_fat32'), ('py2', 'none', 'macosx_10_0_universal'), ('cp27', 'none', 'any'), ('cp2', 'none', 'any'), ('py27', 'none', 'any'), ('py2', 'none', 'any'), ('py26', 'none', 'any'), ('py25', 'none', 'any'), ('py24', 'none', 'any'), ('py23', 'none', 'any'), ('py22', 'none', 'any'), ('py21', 'none', 'any'), ('py20', 'none', 'any')]
```

Tags in text format:
[('cp27', 'cp27m', 'macosx_10_10_x86_64'), ('cp27', 'cp27m', 'macosx_10_10_intel'), ('cp27', 'cp27m', 'macosx_10_10_fat64'), ('cp27', 'cp27m', 'macosx_10_10_fat32'), ('cp27', 'cp27m', 'macosx_10_10_universal'), ('cp27', 'cp27m', 'macosx_10_9_x86_64'), ('cp27', 'cp27m', 'macosx_10_9_intel'), ('cp27', 'cp27m', 'macosx_10_9_fat64'), ('cp27', 'cp27m', 'macosx_10_9_fat32'), ('cp27', 'cp27m', 'macosx_10_9_universal'), ('cp27', 'cp27m', 'macosx_10_8_x86_64'), ('cp27', 'cp27m', 'macosx_10_8_intel'), ('cp27', 'cp27m', 'macosx_10_8_fat64'), ('cp27', 'cp27m', 'macosx_10_8_fat32'), ('cp27', 'cp27m', 'macosx_10_8_universal'), ('cp27', 'cp27m', 'macosx_10_7_x86_64'), ('cp27', 'cp27m', 'macosx_10_7_intel'), ('cp27', 'cp27m', 'macosx_10_7_fat64'), ('cp27', 'cp27m', 'macosx_10_7_fat32'), ('cp27', 'cp27m', 'macosx_10_7_universal'), ('cp27', 'cp27m', 'macosx_10_6_x86_64'), ('cp27', 'cp27m', 'macosx_10_6_intel'), ('cp27', 'cp27m', 'macosx_10_6_fat64'), ('cp27', 'cp27m', 'macosx_10_6_fat32'), ('cp27', 'cp27m', 'macosx_10_6_universal'), ('cp27', 'cp27m', 'macosx_10_5_x86_64'), ('cp27', 'cp27m', 'macosx_10_5_intel'), ('cp27', 'cp27m', 'macosx_10_5_fat64'), ('cp27', 'cp27m', 'macosx_10_5_fat32'), ('cp27', 'cp27m', 'macosx_10_5_universal'), ('cp27', 'cp27m', 'macosx_10_4_intel'), ('cp27', 'cp27m', 'macosx_10_4_fat32'), ('cp27', 'cp27m', 'macosx_10_4_universal'), ('cp27', 'cp27m', 'macosx_10_3_fat32'), ('cp27', 'cp27m', 'macosx_10_3_universal'), ('cp27', 'cp27m', 'macosx_10_2_fat32'), ('cp27', 'cp27m', 'macosx_10_2_universal'), ('cp27', 'cp27m', 'macosx_10_1_fat32'), ('cp27', 'cp27m', 'macosx_10_1_universal'), ('cp27', 'cp27m', 'macosx_10_0_fat32'), ('cp27', 'cp27m', 'macosx_10_0_universal'), ('cp27', 'none', 'macosx_10_10_x86_64'), ('cp27', 'none', 'macosx_10_10_intel'), ('cp27', 'none', 'macosx_10_10_fat64'), ('cp27', 'none', 'macosx_10_10_fat32'), ('cp27', 'none', 'macosx_10_10_universal'), ('cp27', 'none', 'macosx_10_9_x86_64'), ('cp27', 'none', 'macosx_10_9_intel'), ('cp27', 'none', 'macosx_10_9_fat64'), ('cp27', 'none', 'macosx_10_9_fat32'), ('cp27', 'none', 'macosx_10_9_universal'), ('cp27', 'none', 'macosx_10_8_x86_64'), ('cp27', 'none', 'macosx_10_8_intel'), ('cp27', 'none', 'macosx_10_8_fat64'), ('cp27', 'none', 'macosx_10_8_fat32'), ('cp27', 'none', 'macosx_10_8_universal'), ('cp27', 'none', 'macosx_10_7_x86_64'), ('cp27', 'none', 'macosx_10_7_intel'), ('cp27', 'none', 'macosx_10_7_fat64'), ('cp27', 'none', 'macosx_10_7_fat32'), ('cp27', 'none', 'macosx_10_7_universal'), ('cp27', 'none', 'macosx_10_6_x86_64'), ('cp27', 'none', 'macosx_10_6_intel'), ('cp27', 'none', 'macosx_10_6_fat64'), ('cp27', 'none', 'macosx_10_6_fat32'), ('cp27', 'none', 'macosx_10_6_universal'), ('cp27', 'none', 'macosx_10_5_x86_64'), ('cp27', 'none', 'macosx_10_5_intel'), ('cp27', 'none', 'macosx_10_5_fat64'), ('cp27', 'none', 'macosx_10_5_fat32'), ('cp27', 'none', 'macosx_10_5_universal'), ('cp27', 'none', 'macosx_10_4_intel'), ('cp27', 'none', 'macosx_10_4_fat32'), ('cp27', 'none', 'macosx_10_4_universal'), ('cp27', 'none', 'macosx_10_3_fat32'), ('cp27', 'none', 'macosx_10_3_universal'), ('cp27', 'none', 'macosx_10_2_fat32'), ('cp27', 'none', 'macosx_10_2_universal'), ('cp27', 'none', 'macosx_10_1_fat32'), ('cp27', 'none', 'macosx_10_1_universal'), ('cp27', 'none', 'macosx_10_0_fat32'), ('cp27', 'none', 'macosx_10_0_universal'), ('py2', 'none', 'macosx_10_10_x86_64'), ('py2', 'none', 'macosx_10_10_intel'), ('py2', 'none', 'macosx_10_10_fat64'), ('py2', 'none', 'macosx_10_10_fat32'), ('py2', 'none', 'macosx_10_10_universal'), ('py2', 'none', 'macosx_10_9_x86_64'), ('py2', 'none', 'macosx_10_9_intel'), ('py2', 'none', 'macosx_10_9_fat64'), ('py2', 'none', 'macosx_10_9_fat32'), ('py2', 'none', 'macosx_10_9_universal'), ('py2', 'none', 'macosx_10_8_x86_64'), ('py2', 'none', 'macosx_10_8_intel'), ('py2', 'none', 'macosx_10_8_fat64'), ('py2', 'none', 'macosx_10_8_fat32'), ('py2', 'none', 'macosx_10_8_universal'), ('py2', 'none', 'macosx_10_7_x86_64'), ('py2', 'none', 'macosx_10_7_intel'), ('py2', 'none', 'macosx_10_7_fat64'), ('py2', 'none', 'macosx_10_7_fat32'), ('py2', 'none', 'macosx_10_7_universal'), ('py2', 'none', 'macosx_10_6_x86_64'), ('py2', 'none', 'macosx_10_6_intel'), ('py2', 'none', 'macosx_10_6_fat64'), ('py2', 'none', 'macosx_10_6_fat32'), ('py2', 'none', 'macosx_10_6_universal'), ('py2', 'none', 'macosx_10_5_x86_64'), ('py2', 'none', 'macosx_10_5_intel'), ('py2', 'none', 'macosx_10_5_fat64'), ('py2', 'none', 'macosx_10_5_fat32'), ('py2', 'none', 'macosx_10_5_universal'), ('py2', 'none', 'macosx_10_4_intel'), ('py2', 'none', 'macosx_10_4_fat32'), ('py2', 'none', 'macosx_10_4_universal'), ('py2', 'none', 'macosx_10_3_fat32'), ('py2', 'none', 'macosx_10_3_universal'), ('py2', 'none', 'macosx_10_2_fat32'), ('py2', 'none', 'macosx_10_2_universal'), ('py2', 'none', 'macosx_10_1_fat32'), ('py2', 'none', 'macosx_10_1_universal'), ('py2', 'none', 'macosx_10_0_fat32'), ('py2', 'none', 'macosx_10_0_universal'), ('cp27', 'none', 'any'), ('cp2', 'none', 'any'), ('py27', 'none', 'any'), ('py2', 'none', 'any'), ('py26', 'none', 'any'), ('py25', 'none', 'any'), ('py24', 'none', 'any'), ('py23', 'none', 'any'), ('py22', 'none', 'any'), ('py21', 'none', 'any'), ('py20', 'none', 'any')]

**Comment by yifeif** [comment]
@pbilling thanks for the tags info. Looks like you have Mac OS X 10.10 installed. The pypi binary requires to have at least 10.11. One workaround is that you can try our uploaded binaries [here](https://www.tensorflow.org/install/install_mac#python_27). For example:
`pip install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.2.0rc0-py2-none-any.whl`

**Comment by pbilling** [comment]
@yifeif OK, good to know. I think a Docker solution will work for me, but thanks for following up!

**Comment by gunan** [comment]
@ChakritRakuang For your issue, you are using the wrong python version.
As our installation guide for windows states, TF only has support for python 3.5 on windows.

You can search through old issues for the technical challenges that made us decide not support python 2.7 on windows.

**Comment by afsharshamsi** [comment]
tf-nightly 1.14.1.dev20190304 has requirement protobuf>=3.6.1, but you'll have protobuf 3.0.0b2 which is incompatible.
tb-nightly 1.14.0a20190304 has requirement protobuf>=3.6.0, but you'll have protobuf 3.0.0b2 which is incompatible.
what should i do?
