### ISSUE TITLE
tf.assign does not change the shape of variables correctly

### ISSUE THREAD

**Issue by Catk1ns0n** [tensorflow/tensorflow#10091]
Hi,

I have discovered what I believe to be a bug with tf.assign. This occurs when I have a matrix with a shape, e.g. (2, 3), and assign it a new, larger matrix, e.g. with the shape (2, 4). When you get the shape of your updated variable, its shape has not changed i.e. (2, 3) is returned. Furthermore, if you use tf.add on your new matrix and a matrix with the same shape (2, 4) as the updated matrix an exception is thrown:
`ValueError: Dimensions must be equal, but are 3 and 4 for 'Add_2' (op: 'Add') with input shapes: [2,3], [2,4].`

Similar exceptions are also thrown when you try and use tf.matmult, tf.subtract, etc. on your updated variable.

Below is an example of this issue.

<pre><code>import tensorflow as tf

import numpy as np

# Initialise some variables
sess = tf.Session()
x = tf.Variable(tf.ones([2, 3]))
y = tf.Variable(tf.ones([2, 3]))
z = tf.Variable(tf.ones([2, 4]))
sess.run(tf.variables_initializer([x, y, z]))

# Print information about the original matrix
print(x.get_shape())
print(x.eval(session=sess))
print(tf.add(x, y).eval(session=sess))
print()

# Enlarge the matrix by assigning it a new set of values
sess.run(tf.assign(x, np.ones([2, 4]), validate_shape=False))

# Print information about the new matrix
print(x.get_shape())
print(x.eval(session=sess))
print()

# Try add the updated matrix to a matrix with the same ORIGINAL shape
# I would expect this to fail because I have changed the shape
try:
  print(tf.add(x, y).eval(session=sess))
except:
  print("Could not add x and y")
print()

# Try add the updated matrix to a matrix with the same shape
# I would NOT expect this to fail because they both have the same shapes
try:
  print(tf.add(x, z).eval(session=sess))
except:
  print("Could not add x and z")
print()

# Try add the updated matrix to a matrix that had the same ORIGINAL
# shape as it, but has been updated so their actual shapes are the same
a = tf.Variable(tf.ones([2, 3]))
sess.run(tf.variables_initializer([a,]))
sess.run(tf.assign(a, np.ones([2, 4]), validate_shape=False))
print(tf.add(x, a).eval(session=sess))
</code></pre>

The output of this code is:

<code><pre>(2, 3)
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 2.  2.  2.]
 [ 2.  2.  2.]]

(2, 3)
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]

Could not add x and y

Could not add x and z

[[ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]]
</code></pre>

**Comment by jart** [comment]
@mrry is `validate_shape=False` supposed to cause this?

```pycon
>>> import tensorflow as tf
>>> sess = tf.Session()
>>> x = tf.Variable(tf.ones([2, 3]))
>>> y = tf.Variable(tf.ones([2, 3]))
>>> sess.run(tf.variables_initializer([x, y]))

>>> print(tf.add(x, y).eval(session=sess))
[[ 2.  2.  2.]
 [ 2.  2.  2.]]

>>> sess.run(tf.assign(x, tf.ones([2, 4]), validate_shape=False))
array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]], dtype=float32)

>>> print(tf.add(x, y).eval(session=sess))
InvalidArgumentError (see above for traceback): Incompatible shapes: [2,4] vs. [2,3]

>>> x
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32_ref>
>>> y
<tf.Variable 'Variable_1:0' shape=(2, 3) dtype=float32_ref>
```

**Comment by mrry** [comment]
Right, I think `tf.assign(..., validate_shape=False)` is unsafe wrt shape inference (which, for sanity's sake, assume that, once inferred, shape information is never invalidated).

If you want to use `tf.assign(..., validate_shape=False)` to change the shape of a variable later, you must construct the variable as `x = tf.Variable(tf.ones([2, 3]), validate_shape=False)`.

**Comment by Catk1ns0n** [comment]
I'm sorry I do not fully understand you. Essentially I am trying to achieve is this:

<pre><code>
import tensorflow as tf
import numpy as np

sess = tf.Session()
x = tf.Variable(tf.truncated_normal([2, 4], stddev=0.04))
sess.run(tf.variables_initializer([x,]))

# Inefficient declaration of z because values are copied not shared
z = tf.Variable(tf.concat((x, tf.truncated_normal([1, 4], stddev=0.04)), axis=0))
sess.run(tf.variables_initializer([z,]))

print(tf.add(z, np.ones([3, 4])).eval(session=sess))
</pre></code>

Except I do not want to waste space in memory because variable z contains the exact values found in x (plus a few extra) and I will never need the matrix x anymore. The reason why I want this functionality is because I want to declare a weight matrix in my neural network which will become larger each iteration but I do not want to waste space by having copies of the previous smaller matrix still in memory.

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by gyglim** [comment]
> If you want to use tf.assign(..., validate_shape=False) to change the shape of a variable later, you must construct the variable as x = tf.Variable(tf.ones([2, 3]), validate_shape=False).
@mrry Is there a way to change `validate_shape` at a later point? This would be useful to modify networks restored from a metagraph definition
