### ISSUE TITLE
Neural Translation Model example fails due to missing EN tokens 

### ISSUE THREAD

**Issue by rameshdom** [tensorflow/tensorflow#101]
The S2S Neural Translation example (tensorflow/models/rnn/translate)  runs into this error:
> tensorflow.python.platform.default._gfile.FileError: [Errno 2] No such file or directory: 'data/giga-fren.release2.ids40000.en'

The issue seems to be in prepare_wmt_data of data_utils.py. Here, instead of creating a new file for the EN tokens, the FR tokens are overwritten by EN tokens:
> data_to_token_ids(train_path + ".en", fr_train_ids_path, fr_vocab_path)

The fix seems to be as simple as changing that line to:
> data_to_token_ids(train_path + ".en", en_train_ids_path, en_vocab_path)

**Comment by ludimagister** [comment]
Yes, sorry, this will soon be fixed.

**Comment by vrv** [comment]
Fixed in a recent commit, thanks!

**Comment by tiennv147** [comment]
@rameshdom  thanks.
