### ISSUE TITLE
Feature request: polarized gradient in tensorboard embeddings

### ISSUE THREAD

**Issue by bruchansky** [tensorflow/tensorflow#10105]
Currently, default tensorboard color gradient goes from light yellow to dark blue (see screenshot), which works great for highlighting positive values (yellow dots become nearly invisible).

But it doesn't work well for displaying, let's say, sentiment scales (going from -1 to +1). The ability to choose a gradient going from red to blue would be helpful for visualizing polarized scales.
![screen shot 2017-05-22 at 11 39 04](https://cloud.githubusercontent.com/assets/12895366/26317262/e66f4c88-3ee4-11e7-8cb8-7bfad7cd5a35.png)

**Comment by jart** [comment]
@dsmilkov Thoughts on this feature request?

**Comment by chihuahua** [comment]
I have migrated this issue to tensorflow/tensorboard#45 because TensorBoard has migrated to a different repo. Lets continue discussion there - sorry about how this issue is still open.
