### ISSUE TITLE
Feature request: improve tensorboard embeddings search

### ISSUE THREAD

**Issue by bruchansky** [tensorflow/tensorflow#10106]
Currently, when making a search query using a custom variable, let's say a relevance score, then results display relevance scores. This is not always helpful. In my application, I have word embeddings that I would like to filter by a custom variable (relevance score), and I can't see what word is corresponding to each relevance score (see screenshot).

It would be better to have a separate field so that users can define how they would like to see the results of their search query.
![screen shot 2017-05-22 at 11 54 44](https://cloud.githubusercontent.com/assets/12895366/26317930/3acefc0e-3ee7-11e7-8f17-5b9866679e5f.png)

**Comment by dandelionmane** [comment]
I've migrated this to tensorflow/tensorboard.
