### ISSUE TITLE
models/slim download_and_convert_data.py, unicodeDecodeError

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#10103]
Windows 10 x64 build 1703
Anaconda 4.3.1 with Python 3.6.1 x64
Geforce GTX1080
Tensorflow-gpu 1.1.0

![image](https://cloud.githubusercontent.com/assets/4515120/26315004/b640ffbe-3f4a-11e7-8474-2e399af66960.png)

**Comment by jart** [comment]
@mrry Did you run into UnicodeDecodeError problems when working on the Windows port? If so, this might be an easy question for you.

**Comment by mrry** [comment]
My guess is that the `tf.gfile.FastGFile(filenames[i], "r")` in the stack trace should really be `tf.gfile.FastGFile(filenames[i], "rb")`, because it seems to be barfing on a binary file, and Windows handles text and binary files differently.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
