### ISSUE TITLE
Tensorflow Library not loading in macOS (ImportError)

### ISSUE THREAD

**Issue by bedbest24x7** [tensorflow/tensorflow#10107]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No. I've strictly followed the on-site tutorial
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
macOS Sierra
- **TensorFlow installed from (source or binary)**:
binary (https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-1.1.0-py2-none-any.whl)
- **TensorFlow version (use command below)**:
latest (same as that of on-site tutorial version)
- **Bazel version (if compiling from source)**:
Not used as it isn't given in tutorial
- **CUDA/cuDNN version**:
CUDA - 8.0
cuDNN - 6.0
- **GPU model and memory**:
GPU: NVIDIA GeForce GTX 775M 2048 MB
Memory: 8 GB 1600 MHz DDR3
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:
https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh
You can obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
ImportError: Traceback (most recent call last):
  File "/Users/dwdcw/miniconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/dwdcw/miniconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/dwdcw/miniconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dlopen(/Users/dwdcw/miniconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcudnn.5.dylib
  Referenced from: /Users/dwdcw/miniconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found

Failed to load the native TensorFlow runtime.

**Comment by gunan** [comment]
We have dropped support for Mac-GPU setups, starting with 1.2 release.
But your problem is caused by mismatch in cuDNN versions.

All TF binaries are built with cuDNN 5 support.
For use with cuDNN 6, you will need to build from sources.

**Comment by amylizxy** [comment]
I had the same problem 'ImportError: dlopen(/Users/dwdcw/miniconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, ' .
I solved this by using VirtualEnv to install tensorflow and then success.
I think maybe VirtualEnv can provide more clear enviroment. You can try

**Comment by whizzalan** [comment]
I have tried tensorflow-1.10 but got the same problem.
It works on tensorflow-1.9.0

**Comment by pekaalto** [comment]
Same problem. tensorflow-1.9.0 works but 1.10 doesn't.
