### ISSUE TITLE
Memory leak in Java API due to missing TF_DeleteStatus

### ISSUE THREAD

**Issue by jpangburn** [tensorflow/tensorflow#10119]
This is a leak confirmed on [StackOverflow](https://stackoverflow.com/questions/44082297/memory-leak-using-tensorflow-for-java) by [ash](https://stackoverflow.com/users/6708503/ash).

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes.  There's a short example in the above StackOverflow link and a [working JUNIT test written in a maven project on github](https://github.com/jpangburn/tensorflowmemorytest) that demonstrates the problem.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS Sierra using TF 1.1, and CentOS7 using both TF 1.1 and TF 1.2_rc0.
- **TensorFlow installed from (source or binary)**: binary from Maven
- **TensorFlow version (use command below)**: On Mac uses Maven `<version>1.1.0</version>`, on CentOS7 `<version>1.2.0-rc0</version>`

- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: See above for the short example on the StackOverflow link or the full Java file at the github example project.

### Describe the problem
Running the example code given causes the process memory (outside the JDK, not heap space) to grow until the process exits.  Leaked was agreed to be in TensorFlow by ash at StackOverflow:

> I believe there is indeed a leak (in particular a missing TF_DeleteStatus corresponding to the [allocation in JNI code](https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/java/src/main/native/session_jni.cc#L191)) 

### Source code / logs
The test file is [here](https://github.com/jpangburn/tensorflowmemorytest/blob/master/src/test/java/com/jessepangburn/tftest/tensorflowtest/AppTest.java) within the above reference github project.

Thank you for providing this amazing tool!

**Comment by asimshankar** [comment]
Thanks for pointing this out and the detailed report (and ability to reproduce).
This has been fixed internally and should be reflected in Github during our next sync (within the next day) and will be part of the next release candidate for 1.2.

**Comment by jpangburn** [comment]
Very glad to be able to give back a tiny bit!  Thanks again!

**Comment by asimshankar** [comment]
For the record, https://github.com/tensorflow/tensorflow/commit/24f243deee41d8008bf37ae98d825f8f9f050de4
fixes this.

**Comment by riklopfer** [comment]
Does this fix apply to the GPU version of the libraries as well? Specifically, I'm wonder about `libtensorflow_jni-gpu-linux-x86_64-1.3.0-rc1.tar.gz`. I run out of memory when running with that library on an Nvidia card.

**Comment by asimshankar** [comment]
Yes, the fix applies to both. You might be running into something else. Please file a new issue, ideally with steps to reproduce the problem. Thanks!

**Comment by riklopfer** [comment]
@asimshankar, see #11948
