### ISSUE TITLE
Incorrect behavior from `tf.layers.batch_normalization()` when `training=0`

### ISSUE THREAD

**Issue by zo7** [tensorflow/tensorflow#10118]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: ('v1.1.0-rc0-61-g1ec6ed5', '1.1.0')
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 8/5
- **GPU model and memory**: Nvidia Titan X 
- **Exact command to reproduce**: [gist](https://gist.github.com/zo7/87735a3f06a41e0f2b3c10f9950d07a3)

### Describe the problem

I've noticed that `tf.layers.batch_normalization` doesn't seem to give reasonable results when `training=0` (i.e. use distribution statistics instead of just the batch), especially if you apply BN *before* activations (e.g. ResNet-like architectures).

Using the Gist above, if you try to fit a model to noise with SGD (lr=0.01) using repeated applications of dense matrix multiplication -> batch normalization -> ReLU activations, you get this loss for the _same_ inputs over time: (blue: `training=1`, green: `training=0`)

![image](https://cloud.githubusercontent.com/assets/3229244/26330609/9f3fa0ca-3f01-11e7-8f73-81d67e64be97.png)

Using an Adam (lr=0.001) optimizer instead gets even weirder results:

![image](https://cloud.githubusercontent.com/assets/3229244/26330754/49c94eb0-3f02-11e7-9ff6-7d48ad471ea2.png)

However, if I use my own implementation of batch norm (included in gist) I get reasonable results, with the loss for each being similar to each other: (Adam has similar behavior)

![image](https://cloud.githubusercontent.com/assets/3229244/26330911/1922c81c-3f03-11e7-86bf-56f0e38e3ff3.png)

(Interestingly this doesn't seem to be as much of a problem if you have ReLU before BN, I haven't thought too deeply about why.)

Am I seeing things and just have some misunderstanding about what that function is doing, or is this actually a bug?

**Comment by ppwwyyxx** [comment]
The document of `tf.layers.batch_norm` said this:
```
Note: the operations which update the moving_mean and moving_variance variables will not be added as dependencies of your training operation and so must be run separately. For example:
extra_update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
sess.run([train_op, extra_update_ops], ...)
```
But you didn't use it in your code.

**Comment by zo7** [comment]
Where did you find that? The [API reference](https://www.tensorflow.org/api_docs/python/tf/layers/batch_normalization) says *nothing* about needing to run extra operations or adding extra operations to `UPDATE_OPS`.

The entire description:

> Defined in tensorflow/python/layers/normalization.py.
>
> Functional interface for the batch normalization layer.
>
> Reference: http://arxiv.org/abs/1502.03167
>
> "Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift"
>
> Sergey Ioffe, Christian Szegedy

**Comment by ppwwyyxx** [comment]
Sorry I was reading an old version of the doc. The way to run the update may have changed.

**Comment by ppwwyyxx** [comment]
No. I was actually reading a newer version of doc. See here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/normalization.py#L338

**Comment by zo7** [comment]
Oh wow, surprised that's not on the website... I'll close this then, since it looks like the change to the doc has already been made.

**Comment by 3rd3** [comment]
Just for the sake of completeness, here is the recommended code from the docs:

          update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
          with tf.control_dependencies(update_ops):
            train_op = optimizer.minimize(loss)

**Comment by akssieg** [comment]
I am using 
update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
then..
sess.run(train_step,update_ops,feed_dict={x: batch[0], y_: batch[1],istrain:True})

but it is showing error as 
TypeError: run() got multiple values for argument 'feed_dict'.

Could anyone tell that what's wrong:

**Comment by zo7** [comment]
@akssieg 1. You should make `update_ops` a dependency as mentioned above, and 2. you're not calling `sess.run()` correctly – all of your fetches/ops should be a single list/dict, not multiple arguments.

Try using:
```python
sess.run([train_step, update_ops], feed_dict={...})
```
(notice the square brackets)
