### ISSUE TITLE
[feature request] decode_raw for uint16 and other dtype

### ISSUE THREAD

**Issue by Jiaming-Liu** [tensorflow/tensorflow#10124]
### System information
- NO
- NOT RELATED
- NOT RELATED
- NOT RELATED
- NOT RELATED
- NOT RELATED
- NOT RELATED
- NOT RELATED

### Describe the problem
Current decode_raw only supports `tf.half, tf.float32, tf.float64, tf.int32, tf.uint8, tf.int16, tf.int8, tf.int64`. It would be helpful if more types are available.

**Comment by jmchen-g** [comment]
@keveman Could you take a look at this please? Thanks.

**Comment by yongtang** [comment]
Added PR #12719 to support uint16 for tf.decode_raw.
