### ISSUE TITLE
TF ignore the computation graph and output the feeding value directly.

### ISSUE THREAD

**Issue by Zehaos** [tensorflow/tensorflow#10132]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.1.0-rc0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
```
import tensorflow as tf

with tf.Graph().as_default():
  a = tf.placeholder(dtype=tf.float32, shape=[1])
  a = tf.multiply(a, 2)
  with tf.Session() as sess:
    output = sess.run(a, feed_dict={a: [1]})
    print(output)
```
```
[ 1.]
```

### Describe the problem
As the code above, I feed a value into the graph to do some computation. Notice that the input tensor's name is the same as the output tensor's name.
Maybe the naming is a little confusing, but I think it is used quite often. 
I think it is a bug of tensorflow.

**Comment by yaroslavvb** [comment]
This is not a bug, you overwrote your value of "a" with `tf.multiply`, so you are feeding the output of tf.multiply and reading the same output simultaneously
