### ISSUE TITLE
tf.contrib.data: No op named OneShotIterator in defined operations

### ISSUE THREAD

**Issue by EdeMeijer** [tensorflow/tensorflow#10130]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary (nightly build from May 23rd)
- **TensorFlow version (use command below)**: v1.2.0-rc0-172-g9e25de3
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

```
python3 save.py
python3 load.py
```

### Describe the problem
I'm playing around with the new `tf.contrib.data` stuff because it looks awesome and can make a lot of my code a lot simpler. However, I'm trying to save and restore a graph that contains these new ops. Saving works fine, but loading doesn't work. If I inspect the saved file, it seems to be serializing everything correctly, I recognize the structure of all the data set ops I added in the code so that seems fine. In the case of the below example, I'm getting an error `No op named OneShotIterator in defined operations` when trying to load the graph again.

### Source code / logs
save.py
```python
import tensorflow as tf

dataset = tf.contrib.data.Dataset.range(10)
dataset = dataset.map(lambda x: x + 2)
batched_dataset = dataset.batch(4)

iterator = batched_dataset.make_one_shot_iterator()
next_element = iterator.get_next()

tf.add_to_collection('next', next_element)
tf.train.export_meta_graph(filename='graph', as_text=True)
```
load.py
```python
import tensorflow as tf

tf.train.import_meta_graph('graph')
next_element = tf.get_collection('next')[0]

sess = tf.Session()

print(sess.run(next_element))
```

load.py output
```
Traceback (most recent call last):
  File "/home/ede/test/load.py", line 3, in <module>
    tf.train.import_meta_graph('graph')
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1683, in import_meta_graph
    **kwargs)
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/meta_graph.py", line 504, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 283, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named OneShotIterator in defined operations.
```

**Comment by EdeMeijer** [comment]
Here's the saved graph file (in text format)
[graph.txt](https://github.com/tensorflow/tensorflow/files/1021408/graph.txt)

**Comment by mrry** [comment]
I think this is a general problem with ops defined in the `tf.contrib` namespace, because they are lazily registered on the first use of any `tf.contrib` module. If you add the statement `dir(tf.contrib)` (or something else that uses `tf.contrib`) before calling `tf.train.import_meta_graph()`, it should work.

**Comment by EdeMeijer** [comment]
Wow really. Will try that first thing tomorrow.

**Comment by EdeMeijer** [comment]
Yes, that fixed it. Thanks!

**Comment by rajnamitha** [comment]
@EdeMeijer Could you please share the code that made it work? Because I face similar problem for a quantized graph of inception resnet model. I get .
I get "ValueError: No op named QuantizedAdd in defined operations"

 I tried using "dir(tf.contrib)". However, it didn't work for me. I am not sure if I am using it right way.

**Comment by EdeMeijer** [comment]
@rajnamitha the Python file I used it in literally starts like this
```python
import numpy as np
import tensorflow as tf

# Force load contrib ops
dir(tf.contrib)

```
and the rest is just ordinary TensorFlow code. If you're doing the same thing and still running into your problem my advise would be to open a new issue.

**Comment by rajnamitha** [comment]
@EdeMeijer : It is still not solving the problem in my case, so opened an issue. Hope to get a solution. Thanks for your information :)

**Comment by 1int** [comment]
I get this: ValueError: No op named SSTableReader in defined operations when trying to freeze resnet_v2 graph. 
Searching by all tensorflow code doesn't find 'SSTableReader' anywhere. Some help, please?

**Comment by rajnamitha** [comment]
@1int : I didn't face "No op named... " error while freezing though. But maybe it is similar case as mine, where I got "No op named..." error while loading the quantized graph. 
With what helped me, I suggest you to build tensorflow from latest source code rather than binary version.
As maybe you are using latest script  for freezing the graph but the tensorflow version you are using could be a older one. Building tensorflow from source code could help to avoid this problem.

**Comment by sxs4337** [comment]
I get the same error-
ValueError: No op named SSTableReader in defined operations.
while running tf.train.import_meta_graph on the meta file. The dir(tf.contrib) solution did not help.

I am using a pre-trained model from-
https://github.com/openimages/dataset

Thanks.

**Comment by mrry** [comment]
@1int @sxs4337 What was the source of the graph/metagraph containing an `SSTableReader` op? That is not part of the TensorFlow API, so it sounds like whoever built that graph inadvertently included some proprietary/custom ops in the graph....

**Comment by sxs4337** [comment]
I had used the graph from pre-trained model on OpenImages dataset. I was able to get a workaround as discussed in this post-
https://github.com/openimages/dataset/issues/21

Thanks.

**Comment by mrry** [comment]
OK, judging by the comments that issue, it's a bug in the released graph, which shouldn't contain an `SSTableReader` op in the first place. Glad to hear that you've found a workaround!

**Comment by eggie5** [comment]
@EdeMeijer your solution worked for my VGG16 graph: https://gist.github.com/eggie5/7d9c31c08462ec42ed8d927f2c0c3e55

```
import tensorflow as tf
dir(tf.contrib) #hack per https://github.com/tensorflow/tensorflow/issues/10130
with tf.Session() as sess:  
    tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], 'model/export/1509295446/')
    print [n.name for n in tf.get_default_graph().as_graph_def().node]
```

Before I was getting that same error as you.
