### ISSUE TITLE
Segmentation fault: `help(tf.ConfigProto)` failed on python3

### ISSUE THREAD

**Issue by FrankWork** [tensorflow/tensorflow#10133]
tensorflow for python3 failed while ran the following code:

    $ python3
    Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
    >>> import tensorflow as tf
    >>> tf.__version__
    '1.1.0'
    >>> help(tf.ConfigProto)
    段错误 (核心已转储) In English: Segmentation fault (core dumped)

    $ python3
    Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import tensorflow as tf
    >>> tf.__version__
    '1.2.0-rc0'
    >>> help(tf.ConfigProto)
    段错误 (核心已转储) In English: Segmentation fault (core dumped)

tensorflow for python2 worked fine.

    $ python2
    Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
    [GCC 5.4.0 20160609] on linux2
    >>> import tensorflow as tf
    >>> tf.__version__
    '1.1.0-rc1'
    >>> help(tf.ConfigProto)

    >>>

**Comment by jart** [comment]
You seem to be using RHEL 4. TensorFlow only supports RHEL 7+.

**Comment by FrankWork** [comment]
My OS is Ubuntu 16.04. The following result was on python3 without Anaconda. Failed

    $ python3
    Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
    [GCC 5.4.0 20160609] on linux
    >>> import tensorflow as tf
    >>> tf.__version__
    '1.1.0'
    >>> help(tf.ConfigProto)
    段错误 (核心已转储)
