### ISSUE TITLE
tf.contrib.distributions.Logistic   log_cdf method has wrong sign

### ISSUE THREAD

**Issue by goldingn** [tensorflow/tensorflow#10131]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes?
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sierra 10.12.3
- **TensorFlow installed from (source or binary)**: binary, via pip
- **TensorFlow version (use command below)**: 1.1.0 (v1.1.0-rc0-61-g1ec6ed5)
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
```python
import tensorflow as tf
logistic = tf.contrib.distributions.Logistic(loc = 0., scale = 1.) 
logistic.log_cdf(0.).eval(session = tf.Session())
```
### Describe the problem
`tf.contrib.distributions.Logistic`'s `log_cdf()` method has the wrong sign. The above code returns `0.69314718`, but it should be `-0.69314718` (i.e. `log(0.5`).
Appears to be the same for all parameters and values.
The `cdf()` method is fine.
I've not seen this problem with `log_cdf()` in any of the other distributions, so it looks like an isolated bug.

**Comment by jart** [comment]
@langmore Could you take a look at this one?

**Comment by jart** [comment]
Punting this issue to @jvdillon. PTAL.

**Comment by jvdillon** [comment]
Thanks for finding this bug! I have created a fix and it should be in head within a few days.
