### ISSUE TITLE
pip default installs TF1.1 still. On purpose?

### ISSUE THREAD

**Issue by jubjamie** [tensorflow/tensorflow#10135]
On both my Windows 10 and Ubuntu 16.10 instances, trying to upgrade with pip still installs 1.1 even though 1.2.0rc0 is quite clearly available there. On ubuntu I managed to get it by forcing the version. Wondering if this is intentional?

Note: Will check again that this is the case on Windows still as it was yesterday.

**Comment by nelson-liu** [comment]
yes, this behavior is version. RC versions = release candidate and thus are not officially released yet to PyPI.

**Comment by jubjamie** [comment]
Ok well that makes perfect sense. Considering I know what a release candidate is i'm annoyed my brain didn't make that connection. It's been a very very slow day in the office today.

Thanks @nelson-liu . Closing.
