### ISSUE TITLE
CUDA_ERROR_INVALID_DEVICE

### ISSUE THREAD

**Issue by kemaswill** [tensorflow/tensorflow#10146]
Got the following error when trying to run tensorflow on GPU:

> E tensorflow/core/common_runtime/direct_session.cc:137] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE
> Traceback (most recent call last):
>   File "main.py", line 200, in <module>
>     model = PNN2(**pnn2_params)
>   File "/homes/jwpan/Github/DL_MultiField_Categorical_Data/python/models.py", line 767, in __init__
>     self.sess = tf.Session(config=config)
>   File "/projects/ml/mlas/tensorflow/1.0.8/gpu/python2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1176, in __init__
>     super(Session, self).__init__(target, graph, config=config)
>   File "/projects/ml/mlas/tensorflow/1.0.8/gpu/python2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 552, in __init__
>     self._session = tf_session.TF_NewDeprecatedSession(opts, status)
>   File "/projects/ml/mlas/tensorflow/1.0.8/gpu/python2.7/lib/python2.7/contextlib.py", line 24, in __exit__
>     self.gen.next()
>   File "/projects/ml/mlas/tensorflow/1.0.8/gpu/python2.7/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
>     pywrap_tensorflow.TF_GetCode(status))
> tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

Have tried to set CUDA_VISIBLE_DEVICES but still does not work.
Here is the output of nvidia-smi, just wonder why all GPUs are "Off"?

> Tue May 23 21:28:08 2017
> +------------------------------------------------------+
> | NVIDIA-SMI 352.39     Driver Version: 352.39         |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  Tesla K80           On   | 0000:06:00.0     Off |                    0 |
> | N/A   37C    P0    62W / 149W |  10983MiB / 11519MiB |      0%   E. Process |
> +-------------------------------+----------------------+----------------------+
> |   1  Tesla K80           On   | 0000:07:00.0     Off |                    0 |
> | N/A   57C    P0    73W / 149W |  10983MiB / 11519MiB |      0%   E. Process |
> +-------------------------------+----------------------+----------------------+
> |   2  Tesla K80           On   | 0000:0A:00.0     Off |                    0 |
> | N/A   38C    P0    60W / 149W |  10983MiB / 11519MiB |      0%   E. Process |
> +-------------------------------+----------------------+----------------------+
> |   3  Tesla K80           On   | 0000:0B:00.0     Off |                    0 |
> | N/A   54C    P0    73W / 149W |  10983MiB / 11519MiB |      0%   E. Process |
> +-------------------------------+----------------------+----------------------+
> |   4  Tesla K80           On   | 0000:0E:00.0     Off |                    0 |
> | N/A   37C    P0    61W / 149W |  10983MiB / 11519MiB |      0%   E. Process |
> +-------------------------------+----------------------+----------------------+
> |   5  Tesla K80           On   | 0000:0F:00.0     Off |                    0 |
> | N/A   59C    P0    75W / 149W |  10983MiB / 11519MiB |      0%   E. Process |
> +-------------------------------+----------------------+----------------------+
> |   6  Tesla K80           On   | 0000:12:00.0     Off |                    0 |
> | N/A   39C    P0    61W / 149W |  10983MiB / 11519MiB |      0%   E. Process |
> +-------------------------------+----------------------+----------------------+
> |   7  Tesla K80           On   | 0000:13:00.0     Off |                    0 |
> | N/A   62C    P0    74W / 149W |  10983MiB / 11519MiB |      0%   E. Process |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID  Type  Process name                               Usage      |
> |=============================================================================|
> |    0     24673    C   /homes/bjaros/sw/python2.7-bigml/bin/python  10959MiB |
> |    1     16902    C   /homes/bjaros/sw/python2.7-bigml/bin/python  10959MiB |
> |    2     27468    C   /homes/bjaros/sw/python2.7-bigml/bin/python  10959MiB |
> |    3     11704    C   /homes/bjaros/sw/python2.7-bigml/bin/python  10959MiB |
> |    4     13475    C   /homes/bjaros/sw/python2.7-bigml/bin/python  10959MiB |
> |    5     16115    C   /homes/bjaros/sw/python2.7-bigml/bin/python  10959MiB |
> |    6      2095    C   /homes/bjaros/sw/python2.7-bigml/bin/python  10959MiB |
> |    7     23351    C   /homes/bjaros/sw/python2.7-bigml/bin/python  10959MiB |
> +-----------------------------------------------------------------------------+

**Comment by gunan** [comment]
Searching through our issues points to some similar problems:
https://github.com/NVIDIA/nvidia-docker/issues/262

Did you try the recommendations there?
