### ISSUE TITLE
Error when feeding model

### ISSUE THREAD

**Issue by Jacobh2** [tensorflow/tensorflow#1015]
Hi!

I have downloaded and tried the [RNN tutorial](https://www.tensorflow.org/versions/0.6.0/tutorials/recurrent/index.html), it works great and I want to mod it to use it for another project.

I have managed to write my own "reader" which uses my desired data and training the model seems to work, somewhat, I think. I feed my model the following dict:
```
feed_dict = {m.input_data: x, m.targets: y, m.initial_state: state}
cost, state, _ = session.run([m.cost, m.final_state, eval_op], feed_dict=feed_dict)
```
where `x` and `y` are the outputs from the `reader.iterator` method (the one I wrote, but nearly identical to the ptb_iterator used in the tutorial).

I have also created a "runner" module which only imports a already trained model and runs it. But I am unable to run this code. I import a saved checkpoint into my session using the saver.restore method and that seems to work. But for the "runner" code I changed the `feed_dict` to be:
`feed_dict = {m.input_data: input_id_list, m.initial_state: state}`
since I do not have an output this time, this is what I want the network to come up with.
I also have this in the session.run:
`session.run([m.cost, m.targets, eval_op], feed_dict=feed_dict)`
So this time (in contrast to the "trainer" code) I want to have the output of `m.targets`.

But when I try to run the "runner" code, I get this output:
[log.txt](https://github.com/tensorflow/tensorflow/files/121384/log.txt)

I have checked so the shape of `input_id_list` is (1, 4). That is also what is printed on the first line in the log file. And from the error message I can see that the Tensorflow placeholder is of shape (1,4) as well. All this makes sense since my config is set to `batch_size=1` and `num_steps=4`.

It also mentions that the input is of wrong type, not a int32, but it is the same input as when I run the "trainer" version of the code, so why would it work then but not now?

Thank you for all help and feedback! Let me know if I should submit more code/logs/etc!

**Comment by girving** [comment]
@ebrevdo: Do you have any ideas here?

**Comment by ebrevdo** [comment]
Just saw this!  Without seeing the code that you wrote it's hard to see what the problem is.  Perhaps when you call .run or .eval you forget to pass the feed_dict to it?  Or perhaps when you call initialize_all_variables, sometimes that needs a feed_dict as well.  Are you sure the values you're feeding it are the correct numpy dtype?

**Comment by girving** [comment]
Closing for now due to lack of response.  Please reopen if it's still an issue!
