### ISSUE TITLE
tf.reshape modify the value of tensor

### ISSUE THREAD

**Issue by lizaigaoge550** [tensorflow/tensorflow#10150]
![kaywxxy2r62q pv063 _ve](https://cloud.githubusercontent.com/assets/12975526/26388007/7e87051a-4084-11e7-941e-f9d38e37e3c8.png)
![nf8b f d1ae4_gi 9an](https://cloud.githubusercontent.com/assets/12975526/26388013/8154563a-4084-11e7-89b9-dfaf03761171.png)
when i reshape the samples, the value of it is modified, why?

**Comment by PatWie** [comment]
Because all the time TF draws a sample from your distribution. Try:
```python
with tf.Session() as sess:
  print sess.run([samples,ss])
```
instead
