### ISSUE TITLE
Incorrect RNN documentation

### ISSUE THREAD

**Issue by rdipietro** [tensorflow/tensorflow#1016]
In the `tensorflow.python.ops.rnn.rnn` docs:

>   Dynamic calculation returns, at time t:
>     (t >= max(sequence_length)
>         ? (zeros(output_shape), zeros(state_shape))
>         : cell(input, state)

But if we look at `_dynamic_rnn_step`, what seems more reasonable is happening: the old state gets passed through unaltered if `t >= max(sequence_length)`.

**Comment by evanthebouncy** [comment]
okay I've just had the same problem haha so I'll continue here.

It seems the older version of tensorflow uses the unreasonable 0 everything approach in rnn.rnn
but the newer version of tensorflow uses the reasonable approach in _dynamic_rnn_step, and it has yet to go back to rnn to change its comments

I've discovered this by trying to use the rnn and upgrading tensorflow from an old version to 0.6.0 just now.

would be nice to have an official clarification though

**Comment by ebrevdo** [comment]
Documentation should be fixed in the next sync
