### ISSUE TITLE
about cudnn version

### ISSUE THREAD

**Issue by cxwx** [tensorflow/tensorflow#10173]
which version of cud should I use?
I saw cudnn has developed to v8, but the tensorflow recommend https://www.tensorflow.org/install/install_mac (V5.1)
should I use a new one

**Comment by gunan** [comment]
You are confusing CUDA with cuDNN.
Our website says we support cuDNN 5.1 for prebuilt binaries, so anything else wont work.

Moreover, with TensorFlow 1.2, we are dropping support for GPUs on MacOS.
I recomment switching to linux if you need to run TF on GPUs.
