### ISSUE TITLE
tensorflow: How to access and reuse feature column values?

### ISSUE THREAD

**Issue by whatbeg** [tensorflow/tensorflow#10182]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution Linux Ubuntu 16.04**:
- **TensorFlow installed from pip**:
- **TensorFlow version 1.1.0**:

### problem

In tensorflow's wide & deep model tutorial, it constructed some feature columns like:

```
wide_columns = [gender, native_country, education, occupation, workclass,
              relationship, age_buckets,
              tf.contrib.layers.crossed_column([education, occupation],
                                               hash_bucket_size=int(1e4)),
              tf.contrib.layers.crossed_column(
                  [age_buckets, education, occupation],
                  hash_bucket_size=int(1e6)),
              tf.contrib.layers.crossed_column([native_country, occupation],
                                               hash_bucket_size=int(1e4))]
```
I want to directly reuse his columns result/values to construct my wide & deep model with another deep learning library, but how can I access these values after feed inputs ? or how to save into file ? （I didn't found any method that export true data）

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
