### ISSUE TITLE
Bug in r1.2rc

### ISSUE THREAD

**Issue by argman** [tensorflow/tensorflow#10186]
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/image/kernels/image_ops.h#L69](url)

static will cause a compile error(Its a TODO:) )

**Comment by zhaokai410** [comment]
Do you upgrade via pip? I want to upgrade to 1.2 while it's still 1.1 in pip.

**Comment by gunan** [comment]
Our CI does not indicate any failure.
Could you include more information?
What OS do you use, what is your compiler version?
If you can provide all the information requested in the issue template, we may be able to help.
Otherwise, as I said our CI does not catch a failure here, so I will have to close the issue.

**Comment by argman** [comment]
Linux 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
VERSION="7 (Core)"
VERSION_ID="7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

== are we in docker =============================================
No

== compiler =====================================================
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


== uname -a =====================================================
Linux 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.12.0)
protobuf (3.3.0)
tensorflow (1.2.0rc0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.2.0-rc0
tf.GIT_VERSION = unknown
tf.COMPILER_VERSION = unknown
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /opt/intel/mkl/lib/intel64/:/usr/local/cuda-7.5/lib64:/usr/local/compiled_program/lib:
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Fri May 26 10:17:12 2017       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          Off  | 0000:02:00.0     Off |                    0 |
| N/A   29C    P0    61W / 235W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K40m          Off  | 0000:03:00.0     Off |                    0 |
| N/A   31C    P0    62W / 235W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K40m          Off  | 0000:83:00.0     Off |                    0 |
| N/A   30C    P0    62W / 235W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K40m          Off  | 0000:84:00.0     Off |                    0 |
| N/A   29C    P0    66W / 235W |     22MiB / 11519MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-7.5/lib64/libcudart.so.7.5.18
/usr/local/cuda-7.5/lib64/libcudart_static.a
/usr/local/cuda-7.5/lib/libcudart.so.7.5.18
/usr/local/cuda-7.5/lib/libcudart_static.a
/usr/local/cuda-7.5/doc/man/man7/libcudart.so.7
/usr/local/cuda-7.5/doc/man/man7/libcudart.7

**Comment by gunan** [comment]
I see that you are using cuda 7.5.
We have support for cuda 8, it is possible build with cuda 7.5 is broken.
I recommend upgrading CUDA installed in your system.

**Comment by argman** [comment]
Ok, tks, I post it here just to remind others if they encounter the same problem, i think it will be fixed in the future.
