### ISSUE TITLE
When could it be upgraded to 1.2 from pip? 

### ISSUE THREAD

**Issue by zhaokai410** [tensorflow/tensorflow#10193]
I noticed that 1.2 has released in official website. I tried to upgrade to 1.2 via pip, but it is still 1.1.
How could I upgrade to 1.2?

**Comment by czy941030** [comment]
I think you can upgrade via pip with `pip install --upgrade 'tensorflow==1.2.0rc0'`.
1.2.0 is still a rc version.

**Comment by gunan** [comment]
Once the 1.2 release is final, you can use `pip install --upgrade tensorflow` command to upgrade to 1.2.
Until then, you can do as @czy941030 described.
