### ISSUE TITLE
Tensorflow Android not building for non-arm architectures.

### ISSUE THREAD

**Issue by renats** [tensorflow/tensorflow#1019]
I am trying to build the Tensorflow Android Camera Demo for x86 (or x86_64, or mips) architecture but bazel seems to be ignoring the --android_cpu flag and always builds for armeabi-v7a. 

I have also tried using the --fat_apk_cpu flag but I am getting compilation error about the: unrecognized command line option -mfpu=neon.

**Comment by andrewharp** [comment]
Hi, does it work if you remove the mfpu flag entirely? It significantly optimizes things on ARM, but since x86 doesn't support NEON I'm not surprised it breaks there.

**Comment by renats** [comment]
Hello! 

Yes, it worked after removing the mfpu flag entirely for x86.

For arm64-v8a, we also had to remove the "--icf=all" inside the compile option "-Wl,--icf=all".

For mips we cannot still compile it. The problem seems to be different there, after removing the flag:
 undefined reference to `__atomic_fetch_add_8'

Full output for mips compile, here:

`INFO: Found 1 target...
INFO: From Linking tensorflow/examples/android/libtensorflow_demo.so:
bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/core/libandroid_tensorflow_lib.a(constant_folding.o): In function `tensorflow::(anonymous namespace)::ReplaceTensorWithConstant(tensorflow::Graph*, std::pair<tensorflow::Node*, int>, tensorflow::Tensor const&)':
constant_folding.cc:(.text._ZN10tensorflow12_GLOBAL__N_125ReplaceTensorWithConstantEPNS_5GraphESt4pairIPNS_4NodeEiERKNS_6TensorE+0x248): undefined reference to `__atomic_fetch_add_8'
bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/core/libandroid_tensorflow_lib.a(resource_mgr.o): In function `tensorflow::ContainerInfo::Init(tensorflow::ResourceMgr*, tensorflow::NodeDef const&, bool)':
resource_mgr.cc:(.text._ZN10tensorflow13ContainerInfo4InitEPNS_11ResourceMgrERKNS_7NodeDefEb+0x6a4): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
ERROR: /home/enrico/projects/tensorflow/tensorflow/examples/android/BUILD:10:1: Linking of rule '//tensorflow/examples/android:libtensorflow_demo.so' failed: mipsel-linux-android-gcc failed: error executing command 
  (cd /home/enrico/.cache/bazel/_bazel_enrico/a722061e4e14ee10d0cf53e5e96fcc56/tensorflow && \
  exec env - \
  external/androidndk/ndk/toolchains/mipsel-linux-android-4.9/prebuilt/linux-x86_64/bin/mipsel-linux-android-gcc -shared -o bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/libtensorflow_demo.so -Wl,-whole-archive '-Wl,-rpath,$ORIGIN/../../../_solib_mips/_U_S_Stensorflow_Sexamples_Sandroid_Clibtensorflow_Udemo.so___Utensorflow_Sexamples_Sandroid' -Lbazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/_solib_mips/_U_S_Stensorflow_Sexamples_Sandroid_Clibtensorflow_Udemo.so___Utensorflow_Sexamples_Sandroid bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/imageutils_jni.o bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/jni_utils.o bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/rgb2yuv.o bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/tensorflow_jni.o bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/yuv2rgb.o -lpthread bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/core/libandroid_tensorflow_lib.a bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/external/re2/libre2.a bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/core/libprotos_all_cc.a bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/google/protobuf/libprotobuf.a bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/google/protobuf/libprotobuf_lite.a -Wl,-no-whole-archive external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips/libgnustl_static.a external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips/libsupc++.a -landroid -ljnigraphics -llog -lm -z defs -s -Wl,--exclude-libs,ALL -pthread -lpthread -static-libgcc -no-canonical-prefixes -Wl,-S '--sysroot=external/androidndk/ndk/platforms/android-21/arch-mips'): mipsel-linux-android-gcc failed: error executing command 
  (cd /home/enrico/.cache/bazel/_bazel_enrico/a722061e4e14ee10d0cf53e5e96fcc56/tensorflow && \
  exec env - \
  external/androidndk/ndk/toolchains/mipsel-linux-android-4.9/prebuilt/linux-x86_64/bin/mipsel-linux-android-gcc -shared -o bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/libtensorflow_demo.so -Wl,-whole-archive '-Wl,-rpath,$ORIGIN/../../../_solib_mips/_U_S_Stensorflow_Sexamples_Sandroid_Clibtensorflow_Udemo.so___Utensorflow_Sexamples_Sandroid' -Lbazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/_solib_mips/_U_S_Stensorflow_Sexamples_Sandroid_Clibtensorflow_Udemo.so___Utensorflow_Sexamples_Sandroid bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/imageutils_jni.o bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/jni_utils.o bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/rgb2yuv.o bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/tensorflow_jni.o bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/yuv2rgb.o -lpthread bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/core/libandroid_tensorflow_lib.a bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/external/re2/libre2.a bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/tensorflow/core/libprotos_all_cc.a bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/google/protobuf/libprotobuf.a bazel-out/android-mipsel-linux-android-4.9-gnu-libstdcpp-fastbuild/bin/google/protobuf/libprotobuf_lite.a -Wl,-no-whole-archive external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips/libgnustl_static.a external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips/libsupc++.a -landroid -ljnigraphics -llog -lm -z defs -s -Wl,--exclude-libs,ALL -pthread -lpthread -static-libgcc -no-canonical-prefixes -Wl,-S '--sysroot=external/androidndk/ndk/platforms/android-21/arch-mips').
Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 2.265s, Critical Path: 1.92s`

Thank you.

**Comment by andrewharp** [comment]
Ok, thanks for the info. I'll look into selecting build flags dynamically by platform for x86 and x86_64, but in the meantime it's fine to just remove the flags locally.

Tensorflow doesn't support MIPs currently. It looks like you're running into this: http://stackoverflow.com/questions/23065501/stdatomicunsiged-long-long-undefined-reference-to-atomic-fetch-add-8, where an 8-byte atomic add is simply not in the instruction set.

**Comment by renats** [comment]
Thank you for the feedback!

**Comment by CalmWaves** [comment]
Hi renats,
Please tell me the bazel commands that you used to build project for x86 and x86_64.

**Comment by renats** [comment]
@CalmWaves Hello! Just use:
bazel build --fat_apk_cpu=x86,x86_x64 //tensorflow/examples/android:tensorflow_demo --verbose_failures

**Comment by CalmWaves** [comment]
Thank you very much for your reply. but there is very simple mistake.
it should be like

bazel build --fat_apk_cpu=x86,**x86_64 **//tensorflow/examples/android:tensorflow_demo --verbose_failures

Again I am so grateful for your generosity.
