### ISSUE TITLE
Error when serializing LAYER_NAME_UIDS

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#10197]
### System information
- **Have I written custom code**: yes
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from**: source
- **TensorFlow version**: v1.2.0-rc0-312-g0b72359 1.2.0-rc0
- **Bazel version**: 0.4.5
- **CUDA/cuDNN version**: 8.0/5.1
- **GPU model and memory**: NVIDIA GeForce GTX 750 Ti

After recompiling TensorFlow I got this strange log message.
I doesn't seem to affect any of the computation.
All of the other tools behave as expected.

```
WARNING:tensorflow:Error encountered when serializing LAYER_NAME_UIDS.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
```

**Comment by Androbin** [comment]
This was triggered here:
`tf.train.export_meta_graph("model.ckpt.meta")`

**Comment by Androbin** [comment]
Just found this related issue: #9939

**Comment by jart** [comment]
Closing out duplicate. Thanks for the report.
