### ISSUE TITLE
SVG or HTML Summary

### ISSUE THREAD

**Issue by thinxer** [tensorflow/tensorflow#10207]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: 5ae244ed0b702e50fd6bb7bc73d45b9188c4239d
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem

TensorBoard supports image summaries, which is great for visualization. However, TensorFlow doesn't have rich operators for drawing, and people have to rely on Python libraries like `PIL` or `cv2` for rendering. Those libraries typically use software rendering and are not very fast.

Considering TensorBoard is a web app, and browsers already have rich support for rendering, why don't we offload the rendering to browsers? For example, SVG is a simple XML format, which supports vector graphics, text and embedded bitmap images. Outputting an SVG seems to be a fairly easy job with some text templates.

**Comment by jart** [comment]
I'm not sure how HTML summaries would work, but I could see the image dashboard supporting SVG summaries. Thoughts @dandelionmane?

**Comment by wchargin** [comment]
Thanks for the suggestion! I've gone ahead and migrated this to our new repository at https://github.com/tensorflow/tensorboard/issues/50. Feel free to submit a PR there!
