### ISSUE TITLE
pre-trained inception v3 model should accept batches as well as singletons

### ISSUE THREAD

**Issue by dave-andersen** [tensorflow/tensorflow#1021]
At present, the inception v3 model seems to only accept size 1 for the batch size.

**Comment by shlens** [comment]
Inception-v3 may now run on batches of arbitrary size by using the newly released code here:
https://github.com/tensorflow/models/tree/master/inception

In particular, one can adapt this script to accept arbitrary data sets:
https://github.com/tensorflow/models/blob/master/inception/imagenet_eval.py

**Comment by KernelSight** [comment]
The imagenet_eval file doesn't exist anymore?

**Comment by shlens** [comment]
Hmm. Are you possibly not using the latest version of the repo? It seems to
still be there, no?
https://github.com/tensorflow/models/blob/master/inception/inception/imagenet_eval.py

**Comment by KernelSight** [comment]
It is! Ah, in true inception style the new link is inside the inception folder, inside another inception folder. I just tried to find it by clicking on the above link. Thanks shlens.

**Comment by ulgus** [comment]
If I get this code right, the fix works for evaluation purposes only (i.e., computing top-k-error). Is there a way to extract the bottleneck vectors themselves (pool_3:0) in a batched fashion?

Cmp. this thread, for example: http://stackoverflow.com/questions/35274457/inceptionv3-and-transfer-learning-with-tensorflow/40709836#40709836

Thanks in advance -

**Comment by universewill** [comment]
Is there any solutions now? I am also looking for a way to extract the bottleneck output as pre-computing for transfer learning  @ulgus

**Comment by QiJune** [comment]
The same problem @universewill @ulgus, is there any solutions? 
Thank you!

**Comment by ulgus** [comment]
I (kind of) got it to work with inception_eval:
https://github.com/tensorflow/models/blob/master/inception/inception/inception_eval.py 

inception_eval contains a method inference() which I used:
`from inception import inception_model as inception
image = ... # some image
some_images = np.array(10 * [image]).astype('float32') # stack 10 images into np.array
image_tensor = tf.constant(some_images)
inception.inference(image_tensor, 1001) # works with 10 images`

The problem: Internally, this code sets up the whole flow graph *every time* you call inference(), i.e. there is no elegant placeholder mechanism. This leads to quite a bit of overhead: On my Tesla K40, it takes 7 seconds to setup the network and then 28 seconds for to bulk-process 500 images.

**Comment by sandys** [comment]
@universewill @ulgus @shlens  is there a current solution to this ? we need a nightly batch processing of 100 of K of images. I have been considering using this method combining it with spark - http://go.databricks.com/hubfs/notebooks/TensorFlow/Distributed_processing_of_images_using_TensorFlow.html 

sc = pyspark Context

**Comment by ideaRunner** [comment]
The link provided by @shlens  is unreachable, I have found this 
 https://github.com/tensorflow/models/blob/master/research/inception/inception/imagenet_eval.py
But it cannot do batch prediction via the pre-trained pb model in http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz

The batch size has been fixed to 1 in this pb model, which cost too much unnecessary time on the inference stage if I need to predict lots of images.  
Could you release the batch prediction version of this pb model?

**Comment by shlens** [comment]
The code in the `inception` repository is deprecated. Please use the [slim](https://github.com/tensorflow/models/tree/master/research/slim) version of Inception-v3 instead.
