### ISSUE TITLE
Eye Iris Identification using Tensorflow

### ISSUE THREAD

**Issue by mobiksasd** [tensorflow/tensorflow#10211]
Hello, 

In my android app, I'm looking to build eye iris identification for each user. Can I do this with Tensorflow lite? The user would use their native camera to put infront of their eyes, Tensorflow will detect if this is identified or not from our database.

Thank you,
Kind Regards,

**Comment by andrewharp** [comment]
This is more of a model design question than a TF issue, and would be more appropriately asked on StackOverflow.

But note that if you can do it in TensorFlow Lite (which is unreleased) you would also be able to do it today in TensorFlow. See the [TF Android demo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) for an example of how to get started integrating TF into an app.
