### ISSUE TITLE
tf.summary.image bug with input_queues

### ISSUE THREAD

**Issue by AndreiCostinescu** [tensorflow/tensorflow#10210]
### System information
- **Have I written custom code**: yes
- **OS Platform and Distribution**: Windows 10, Linux Ubuntu 14.04.02
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.1.0
- **CUDA/cuDNN version**: 8.0
- **Exact command to reproduce**: python error_reading_with_summary.py

### Describe the problem
When creating `tf.summary.image()` summaries when using `tf.train.slice_input_producer()` for generating the images, the input queue gets emptied very fast and I end up with less data for training... 
For example: When having 5 images, the first image gets read but when I try collecting the second image I get a `tf.errors.OutOfRangeError` error. This is not a problem with how I input the images because when I leave out the summaries I can read all images.
I get multiple warnings like
```
2017-05-26 08:33:43.017260: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Out of range: FIFOQueue '_6_input_producer/input_producer' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: input_producer/input_producer_Dequeue = QueueDequeueV2[component_types=[DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/input_producer)]]
```
when I create the summary operation and then run the summary operation.
Interestingly enough, I also get this warning when I run the summary operation without any summaries created. But at least then all my images get read.
When I don't have any summaries and don't run any summary operation this warning doesn't appear at all.

The attached archive contains a minimal replicating example. The `tf.summary.image()` is at line 15-16 in the `get_batch()` function and the `merged_summary_op` is created at line 31 and run at line 45 in the `test_read_images_summary()` function.
Run `python error_reading_with_summaries` to execute all 4 cases: 
1. When the summary isn't created and the summary operation isn't executed.
2. When the summary is created but the summary operation isn't executed.
3. When the summary isn't created but the summary operation is executed.
4. When the summary is created and the summary operation is executed.

Use the option `-s` for only creating the summary and `-r` only for executing the summary operation and use both `-r -s` for creating and executing the summary operation.

### Source code / logs
Source code, traceback and images are included: [error_reading_with_summary.zip](https://github.com/tensorflow/tensorflow/files/1031025/error_reading_with_summary.zip)
Run `python error_reading_with_summaries.py` or `python error_reading_with_summaries.py -h` for help.

**Comment by jart** [comment]
Please see https://github.com/tensorflow/tensorflow/issues/923.

**Comment by AndreiCostinescu** [comment]
@jart
Thanks for replying :)
The "problem" at #932 isn't the same as this described bug. My code behaves differently when running the summary operation as opposed to when not running the summary operation.

The main difference is that there are 10 images in my dataset and when not running the summary op, I can read all images this way. However if I run the summary operation I can only read one image before getting these warnings saying that the queue is closed. 
Does the summary operation read internally more images? Because I can't explain why this different behavior occurs. 
That's also why I opened this issue, instead of going to stackoverflow to post an implementation wuestion :)

**Comment by jart** [comment]
This issue tracker is for bugs and feature requests. Issues like these can easily be misconfiguration. The [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) community exists to support TensorFlow users.

**Comment by AndreiCostinescu** [comment]
@jart 
Thanks for pointing me to the direction of StackOverflow. There I found the problem related to this "issue".
Apparently, a summary op triggers a dequeue everytime it is run.
https://stackoverflow.com/questions/40723307/tensorflow-how-to-run-summary-operation-without-triggering-dequeue

Could it be possible to implement the summary_op in such a way, that it doesn't automatically do a dequeue operation in the context of a normal session?

**Comment by AndreiCostinescu** [comment]
Or should we update the documentation stating *somewhere* that the summary operation will trigger a dequeue operation?
