### ISSUE TITLE
Add an option to enable CORS in TensorBoard

### ISSUE THREAD

**Issue by darthdeus** [tensorflow/tensorflow#10227]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:  b'unknown' 1.1.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 8, cuDNN 5.1
- **GPU model and memory**: 1080ti 11GB
- **Exact command to reproduce**: N/A

### Describe the problem

The [DeepDream notebook example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/deepdream/deepdream.ipynb) in TensorFlow provides a snippet that uses https://tensorboard.appspot.com to embed `<iframe>`s inside a Jupyter notebook. Changing this snippet to point to a local instance of TensorBoard fails with a CORS error

![](http://i.imgur.com/WogWPOR.png)

Having the option to enable CORS when starting TensorBoard, or enabling it by default, would make it really easy to use the snippet to visualize directly in Jupyter using a local instance of TensorBoard.

### Source code / logs

Here's the snippet in its whole, with modified URL to point to `http://localhost:6006` instead of `https://tensorboard.appspot.com`

```python
# TensorFlow Graph visualizer code
import numpy as np
from IPython.display import clear_output, Image, display, HTML

def strip_consts(graph_def, max_const_size=32):
    """Strip large constant values from graph_def."""
    strip_def = tf.GraphDef()
    for n0 in graph_def.node:
        n = strip_def.node.add() 
        n.MergeFrom(n0)
        if n.op == 'Const':
            tensor = n.attr['value'].tensor
            size = len(tensor.tensor_content)
            if size > max_const_size:
                tensor.tensor_content = "<stripped %d bytes>"%size
    return strip_def

def show_graph(graph_def, max_const_size=32):
    """Visualize TensorFlow graph."""
    if hasattr(graph_def, 'as_graph_def'):
        graph_def = graph_def.as_graph_def()
    strip_def = strip_consts(graph_def, max_const_size=max_const_size)
    code = """
        <script src="//cdnjs.cloudflare.com/ajax/libs/polymer/0.3.3/platform.js"></script>
        <script>
          function load() {{
            document.getElementById("{id}").pbtxt = {data};
          }}
        </script>
        <link rel="import" href="http://localhost:6006/tf-graph-basic.build.html" onload=load()>
        <div style="height:600px">
          <tf-graph-basic id="{id}"></tf-graph-basic>
        </div>
    """.format(data=repr(str(strip_def)), id='graph'+str(np.random.rand()))

    iframe = """
        <iframe seamless style="width:1200px;height:620px;border:0" srcdoc="{}"></iframe>
    """.format(code.replace('"', '&quot;'))
    display(HTML(iframe))
```

**Comment by jart** [comment]
I would recommend working around this with nginx.

```nginx
server {
  listen 80 default_server;
  listen [::]:80 default_server ipv6only=on;

  location / {
    proxy_http_version 1.1;
    proxy_pass http://127.0.0.1:6006;
    add_header 'Access-Control-Allow-Origin' '$cors_origin';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Custom-Header-1';
  }
}
```

@dandelionmane Should we add an `--insecure_cors` flag? Or a `--header=Foo:bar` flag where the user repeats all that, and it gets applied to all responses?

**Comment by jart** [comment]
Since the NGINX workaround seems sufficient, I'm going to close this one out.

Please note that we're planning to productionize TensorBoard. Things like CORS will be part of our configuration scripts. Please follow https://github.com/tensorflow/tensorboard/issues/92 for more information.

With that said, I'm going to close this one out. If anyone feel strongly that header customization or CORS should be part of TensorBoard core, let me know.

**Comment by Inouyasha** [comment]
![image](https://github.com/tensorflow/tensorflow/assets/34400225/78f10a86-afae-4f16-bd76-7325aab68edd)

**Comment by p3sp12** [comment]
@Inouyasha 
I was struggled to the same problem and this worked!! Thank you so much.
