### ISSUE TITLE
can not run   “bazel build inception/download_and_preprocess_imagenet”

### ISSUE THREAD

**Issue by yuhaimahaiyin** [tensorflow/tensorflow#10239]
it always give error:"no such target '//:inception/download_and_preprocess_imagenet': target 'inception/download_and_preprocess_imagenet' not declared in package '' defined by /home/hank/tensorflow/BUILD."
the BUILD file is empty.

**Comment by jart** [comment]
It looks like the inception model docs are out of date. We would gladly welcome contributions improving the documentation. https://github.com/tensorflow/models/tree/master/inception

**Comment by jart** [comment]
On second thought, let me take care of this for you.

**Comment by yuhaimahaiyin** [comment]
Thanks a lot. I have figured it out, i built in a wrong folder. :(

bst rgds

**Comment by jart** [comment]
I had a feeling people might get confused by that.

The good news is that, thanks to you, no one will experience that same pain in the future. I added `cd` statements to all the README examples in https://github.com/tensorflow/models/pull/1510.
