### ISSUE TITLE
Update tensorboard development instructions

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tensorflow#10234]
I want to be able to run tensorboard in development mode and make some changes.

from the [DEVELOPMENT document:](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/DEVELOPMENT.md)

> bazel run third_party/tensorflow/tensorboard/components/tf_tensorboard:demo

but this command seems to be obsolete from the directory structure (there is no target inside /third_party).

also seems there is a `.idea` folder committed in the repository. 
Would be nice to know how the core team setups their environment.

**Comment by asimshankar** [comment]
@dandelionmane @jart : Mind taking a look?

**Comment by wchargin** [comment]
[The `README.md` is currently up-to-date.](https://github.com/tensorflow/tensorboard/blob/master/README.md#usage) We should, as you indicate, update `DEVELOPMENT.md`. I'll just go ahead and do this in our new repository at https://github.com/tensorflow/tensorboard. Thanks for reporting.

As to development environments, it's just everyone's own taste; we don't have a single unified setup. In fact, we're all quite different: I believe we've got Linux with vim, Linux/Mac with Sublime, Linux on emacs/IntelliJ, and using a Google-internal web IDE. :-)
