### ISSUE TITLE
module 'tensorflow.contrib' has no attribute 'signal'

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#10232]
Previously, I got the `signal` package merged into `contrib`: #9236

But now that I recompiled it all after a while, I got this when trying to use it:
`AttributeError: module 'tensorflow.contrib' has no attribute 'signal'`

Since all the tests went through, how can it be it can't even be found?
Could I have missed adding yet another reference to the package somewhere?

`tf.contrib.layers.batch_norm` does work
`tf.contrib.signal.frames` does not work

**Comment by Androbin** [comment]
@vrv Any ideas?

**Comment by vrv** [comment]
I think you need to add an import to tensorflow/contrib/__init__.py

**Comment by vrv** [comment]
(The tests don't import the public API; otherwise all tests would be run on any change to any file).

**Comment by Androbin** [comment]
Thanks @vrv, what about other unlisted `contrib` packages like:
`android, batching, benchmark_tools, boosted_trees, cmake, hooks, hvx, imperative, makefile, mpi, pi_examples, verbs, xla_tf_graph`
Are all of these not included intentionally or should they be added as well?

**Comment by vrv** [comment]
I am not sure, I suspect we should leave as is for now. Thanks!
