### ISSUE TITLE
Implement Focused Online Learning which converges faster than SGD

### ISSUE THREAD

**Issue by futurely** [tensorflow/tensorflow#10245]
![image](https://cloud.githubusercontent.com/assets/9004594/26520117/ec115938-42fe-11e7-9350-8da77dc6488e.png)
Shai Shalev-Shwartz and Yonatan Wexler. Minimizing the Maximal Loss: How and Why?. ICML, 2016.
http://proceedings.mlr.press/v48/shalev-shwartzb16.pdf
http://arxiv.org/abs/1602.01690
https://www.cs.huji.ac.il/~shais/talks/FOL_talk.pdf

**Comment by jart** [comment]
Thoughts on this feature request @fchollet?

**Comment by fchollet** [comment]
What would be the proposed API?
