### ISSUE TITLE
Feature Request:   Tensorflow for Python 3.6 

### ISSUE THREAD

**Issue by Moondra** [tensorflow/tensorflow#10252]
Hi,

I was wondering if there are plans to release tensorflow for Python 3.6  and if so is there ETA?

Thank you.

**Comment by caisq** [comment]
@Moondra, can you please clarify what operating system(s) you question is about? Thanks.

**Comment by Niu5056** [comment]
I assume "cp36" refers to "python 3.6". If that's the case, it is already out.

**Comment by larcai** [comment]
I cannot seem to find the TF on py3.6 on windows
I tried both CPU and GPU versions at https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.1.0-cp36-cp36m-win_amd64.whl

**Comment by caisq** [comment]
@gunan

**Comment by gunan** [comment]
It is not available yet.
Closing this issue as a duplicate of #6999

**Comment by Moondra** [comment]
@caisq  Hi, I was looking for the Windows version. Thank you.
