### ISSUE TITLE
Support for custom input producers

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#10251]
This is a request for custom functions to feed examples into input pipelines. Existing ops are designed to read pre-defined formats. Although it is entirely possible to pre-process all the data beforehand, I felt like it shouldn't be necessary, especially in realtime environments. It'd be more convenient to pass TensorFlow a lambda to use to generate the batches instead of pre-processing them into TFRecords or dealing with nasty IO or using the not scalable option of python dicts.

[Please tell me if there already exists such a solution, I didn't find a way to do it.]

**Comment by ppwwyyxx** [comment]
I think the performance guide already mentions that the solution is to use queues.

**Comment by Androbin** [comment]
@ppwwyyxx I am referring to how the data is introduced, not how it is processed afterwards.

**Comment by Androbin** [comment]
What currently can be done: Loading TFRecords, CSV files and whatever format has support
What currently isn't as easy: Loading a unknown/custom format and/or applying custom pre-processing before enqueuing the data

**Comment by ppwwyyxx** [comment]
You can load whatever custom formats and apply custom pre-processing, and feed them into queues.

**Comment by jart** [comment]
Thanks for helping our friend @ppwwyyxx.

If queues don't work for your use case, let me know and I'll reopen.
