### ISSUE TITLE
Retrain.py try download remote archive 

### ISSUE THREAD

**Issue by Radzhab** [tensorflow/tensorflow#10259]
I want manually set input directory, but retrain.py downloading remote archive. Why so?

`python retrain.py --image_dir=D:\123\flower_photos\`

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
