### ISSUE TITLE
Possible Bug: tensorflow.cholesky_solve

### ISSUE THREAD

**Issue by jim24** [tensorflow/tensorflow#10265]
I wrote a script to compare the output of a very simple linear system with simple matrix inversion a la [tensorflow.matrix_inverse](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops/matrix_math_functions#matrix_inverse), the non-cholesky based matrix equation solver [tensorflow.matrix_solve](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops/matrix_math_functions#matrix_solve), and [tensorflow.cholesky_solve](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops/matrix_math_functions#cholesky_solve).

According to my understanding of the docs I've linked, these three cases should all yield a solution of the `I/2`, but this is not the case for `tensorflow.cholesky_solve`. Perhaps I'm misunderstanding the docs? 

    import tensorflow as tf
    
    I = tf.eye(2, dtype=tf.float32)
    X = 2 * tf.eye(2, dtype=tf.float32)
    X_inv = tf.matrix_inverse(X)
    X_solve = tf.matrix_solve(X, I)
    X_chol_solve = tf.cholesky_solve(tf.cholesky(X), I)
    
    with tf.Session() as sess:
        for x in [X_inv, X_solve, X_chol_solve]:
            print('{}:\n{}'.format(x.name, sess.run(x)))
            print

yielding output:

    MatrixInverse:0:
    [[ 0.5  0. ]
     [ 0.   0.5]]
    
    MatrixSolve:0:
    [[ 0.5  0. ]
     [ 0.   0.5]]
    
    cholesky_solve/MatrixTriangularSolve_1:0:
    [[ 1.  0.]
     [ 0.  1.]]    
    
    Process finished with exit code 0

### System information
- **OS: Ubuntu 16.04 xenial**
- **Kernel: x86_64 Linux 4.8.0-52-generic**
- **TensorFlow installed from binary**
- **TensorFlow version ('v1.1.0-rc0-61-g1ec6ed5', '1.1.0')**
- **Cuda compilation tools, release 8.0, V8.0.61**
- **GTX 1070 8GB**

**Comment by asimshankar** [comment]
@langmore @rmlarsen : Mind taking a look?

**Comment by langmore** [comment]
Hello @jim24 .  Your understanding is correct, and on my system all three methods give the same result.  Could you try running again on CPU, by using:

`with tf.Session() as sess, tf.device('/cpu:0'):`

**Comment by jim24** [comment]
Hi Ian.

I ran the script again, with your modifications, on a different machine (info posted at the bottom).

```
import tensorflow as tf

I = tf.eye(2, dtype=tf.float32)
X = 2 * tf.eye(2, dtype=tf.float32)
X_inv = tf.matrix_inverse(X)
X_solve = tf.matrix_solve(X, I)
X_chol_solve = tf.cholesky_solve(tf.cholesky(X), I)

for device in ['/cpu:0', '/gpu:0']:
    with tf.Session() as sess, tf.device(device):
        for x in [X_inv, X_solve, X_chol_solve]:
            print('{}\t{}:\n\t{}'.format(device, x.name, sess.run(x)))
            print
```

which now gives output:

/cpu:0	MatrixInverse:0:
[[ 0.5  0. ]
 [ 0.   0.5]]
/cpu:0	MatrixSolve:0:
[[ 0.5  0. ]
 [ 0.   0.5]]
/cpu:0	cholesky_solve/MatrixTriangularSolve_1:0:
[[ 1.  0.]
 [ 0.  1.]]
/gpu:0	MatrixInverse:0:
[[ 0.5  0. ]
 [ 0.   0.5]]
/gpu:0	MatrixSolve:0:
[[ 0.5  0. ]
 [ 0.   0.5]]
/gpu:0	cholesky_solve/MatrixTriangularSolve_1:0:
[[ 1.  0.]
 [ 0.  1.]]

### System 2 information
- **Windows 7 SP1**
- **TensorFlow installed from binary**
- **TensorFlow version: b'unknown' 1.1.0**
- **Cuda compilation tools, release 8.0, V8.0.60**
- **gtx 660 1.5GB (x2)** :

**Comment by Joshuaalbert** [comment]
I can confirm odd behaviour. I get:

```
MatrixInverse:0:
[[ 0.5  0. ]
 [ 0.   0.5]]
MatrixSolve:0:
[[ 0.5  0. ]
 [ 0.   0.5]]
cholesky_solve/MatrixTriangularSolve_1:0:
[[ 0.49999997  0.        ]
 [ 0.          0.49999997]]
```

**Comment by jim24** [comment]
Hmmm, well I've upgraded tensorflow to 1.2.1 since this issue occurred and now I get your result for `cholesky_solve/MatrixTriangularSolve_1:0:`. I'll close my issues because the only difference seems to be floating point imprecisions.
