### ISSUE TITLE
TF 1.2.0-rc1: Build with MKL failed

### ISSUE THREAD

**Issue by untom** [tensorflow/tensorflow#10275]
Hi!
I just tried building TF 1.2.0-rc1 with MKL, using:

    bazel build --config=opt --config=cuda --config=mkl --copt="-DEIGEN_USE_VML" -c opt //tensorflow/tools/pip_package:build_pip_package

Where, in the `'./configure` step I said "yes" to both using MKL and to downloading it from the web. I get the following error:

    ERROR: /dataSSD/untom/tmp/tensorflow-1.2.0-rc1/tensorflow/core/BUILD:1544:1: undeclared inclusion(s) in rule '//tensorflow/core:core_cpu_base':
    this rule is missing dependency declarations for the following files included by 'tensorflow/core/graph/mkl_tfconversion_pass.cc':
      '/dataSSD/untom/tmp/tensorflow-1.2.0-rc1/tensorflow/core/common_runtime/function.h'
      '/dataSSD/untom/tmp/tensorflow-1.2.0-rc1/tensorflow/core/common_runtime/device_mgr.h'
      '/dataSSD/untom/tmp/tensorflow-1.2.0-rc1/tensorflow/core/common_runtime/optimization_registry.h'
      '/dataSSD/untom/tmp/tensorflow-1.2.0-rc1/tensorflow/core/common_runtime/device_set.h'.
    Target //tensorflow/tools/pip_package:build_pip_package failed to build
    Use --verbose_failures to see the command lines of failed build steps.

EDIT: I used bazel 0.4.5 and Python 3.6.1

**Comment by vdevaram** [comment]
Not sure about the right fix. 
Take the changes in the below file to the file tensorflow/core/BUILD and try
[BUILD.txt](https://github.com/tensorflow/tensorflow/files/1038430/BUILD.txt)

**Comment by nhasabni** [comment]
@untom This is a duplicate of #9979 
It has been fixed in the master. Looks like the fix - PR #9986 - is not in 1.2.0-rc1.

**Comment by asimshankar** [comment]
@av8ramit : Should the PR references above be included in 1.2.0-rc2 (or 1.2.0 final)?

**Comment by av8ramit** [comment]
@asimshankar I'll add them into rc2.

**Comment by untom** [comment]
Can confirm that the problem is gone with rc2
