### ISSUE TITLE
ImportError:_pywrap_tensorflow_internal.so: __sprintf_chk: symbol  not found

### ISSUE THREAD

**Issue by Luxios** [tensorflow/tensorflow#10283]
# OS
Host: Windows 10 Professional  64bit
Docker container :  Alpine
`/ # cat /etc/issue`
Welcome to Alpine Linux 3.6
Kernel \r on an \m (\l)

`/ # uname -a`
Linux 3b851449cb60 4.9.27-moby #1 SMP Thu May 11 04:01:18 UTC 2017 x86_64 Linux

# Installation
- Part of my dockerfile

`FROM frolvlad/alpine-glibc`
`RUN apk update && apk add --no-cache \
        wget ca-certificates unzip vim git \
        gcc g++ python python-dev py-numpy-dev && \
    apk add --no-cache --virtual=build-dependencies \
        libffi-dev libressl-dev zlib-dev jpeg-dev freetype-dev libpng-dev `

`RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && rm get-pip.py && \
    ln -s /usr/include/locale.h /usr/include/xlocale.h && \
    pip --no-cache-dir install requests[security] ipykernel jupyter matplotlib scipy scikit-learn pandas seaborn \
    https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.2.0rc1-cp27-none-linux_x86_64.whl && \
    python -m ipykernel.kernelspec `

The dockerfile was built successfully. But when `import tensorflow` in a container , the following happened

>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: Error relocating /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: __sprintf_chk: symbol
 not found
Failed to load the native TensorFlow runtime.

**Comment by annanay25** [comment]
Are you in the tensorflow source root directory? Can you try and ```cd``` into another folder and running the same?

**Comment by asimshankar** [comment]
From a quick search and from https://github.com/gliderlabs/docker-alpine/issues/149#issuecomment-194435282 and #103, I believe Alpine uses a different C library than glibc, which unfortunately isn't supported.

You might want to try to install glibc and/or build from source. However, since this isn't a supported configuration, I'm afraid we won't be able to guide you through the process here.
