### ISSUE TITLE
Test CMake entries against filetree

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#10296]
There were some invalid entries in `tensorflow/contrib/cmake/tf_python.cmake` which are removed as of #10294 and which were discovered alongside #10264 @drpngx where I proposed extracting all file glob entries from all CMake files for better management as well as automated testing for their validity to keep things safe and sound.

**Comment by gunan** [comment]
For multiple reasons, bazel will stay as our primary build system.
cmake wont be promoted to core.
I am not against the test itself, I am happy to accept a test as you described as a contribution, and run it under contrib/cmake. But it is not a priority for us.

**Comment by Androbin** [comment]
@gunan Understandable, would you go ahead and label this as `contributions welcome`?

**Comment by drpngx** [comment]
Feel free to describe your design before you send a PR if you'd like some clarification.

**Comment by Androbin** [comment]
@mrry PR #14877 already covers the extraction. I'll write the tests, too. First, make sure to include existing subpackages of name `python`, `python/ops` and `python/kernels`. Second, make sure not to include non-existent packages. I'll try to assemble a PR later this day.

**Comment by Androbin** [comment]
Quick clarification: Where should the tests go?
Maybe `tf_tests.cmake` > `tensorflow_BUILD_PYTHON_TESTS` ?

**Comment by Androbin** [comment]
In `CMakeLists.txt` what is the difference between `tensorflow_BUILD_PYTHON_TESTS` and `tensorflow_BUILD_MORE_PYTHON_TESTS` ?

**Comment by mrry** [comment]
Since the Bazel build is the ground truth, I'd guess the easiest approach would probably be to add a Bazel test that compares the list of submodules in the built PIP artifact to the list of submodules in `tensorflow/contrib/cmake/python_modules.txt`.

**Comment by Androbin** [comment]
@mrry My original intent was to test `python_modules.txt` etc. against the filetree.

**Comment by Androbin** [comment]
Maybe @gunan can tell where to place the tests?

**Comment by Androbin** [comment]
We could of course run the tests directly as part of the `cmake` build.
But I wonder if a separate test might be good to have.

**Comment by gunan** [comment]
Sorry, missed this.
I agree with @mrry that this should be a bazel test, as that is our ground truth.
We should add a BUILD file under contrib/cmake, and have a py_test for this in that BUILD file. It will be picked up by our contrib builds automatically.

**Comment by Androbin** [comment]
Sorry @gunan, already sent this PR #15166
I will turn it into a bazel test, if you want.

**Comment by Androbin** [comment]
I added bazel tests as you requested.

**Comment by Androbin** [comment]
@gunan @mrry Do we want this for (let's say) `tf_core_kernels.cmake` and `tf_tests.cmake` as well?

**Comment by Androbin** [comment]
When the `tf_python.cmake` tests are merged, I will look into the other `cmake` files.
@gunan Which of them would probably benefit the most from (extraction and) testing?

**Comment by Androbin** [comment]
> We should add a `BUILD` file under `contrib/cmake`, and have a `py_test` for this in that `BUILD` file.

@gunan What is the difference between `py_test` and `tf_py_test` ?

**Comment by gunan** [comment]
If you mean comparison to bazel built pip package, any cmakefile with a list in them can benefit.
However, if you mean just comparing to the file tree, we already run the full cmake build itself, so i dont think we need an extra test for comparing cmakefile entries to the files in the tree.

Response to deleted comment:
`tf_py_test` is just a convenience wrapper around `py_test` rule which hides some complexity for a few of our options like xla and grpc. In this case, we definitely do not need it.

**Comment by Androbin** [comment]
> we already run the full cmake build itself

So, why didn't it catch the [invalid entries](https://github.com/tensorflow/tensorflow/pull/15368/files) in `tf_python.cmake` ?

**Comment by gunan** [comment]
OK, maybe I can rephrase this.
As python code simply needs to be copied by cmake, and no compilation or other processing is needed, old files that do not exist anymore are just noop statements, they will try copying but will immediately return success because there is nothing to copy.
For anything else, the build will fail because it will try compiling a non-existent file, or something similar.

Either way, either the entries are noops, or get caught by the build.
The change you have should be able to catch all noops, anything else should be caught by the cmake build.

**Comment by Androbin** [comment]
@gunan Thanks for the clarification.
So, `tf_python.cmake` and `tf_tests.cmake` would benefit, others wouldn't, right?

**Comment by gunan** [comment]
Good catch, the test blacklist in tf_tests.cmake may also contain old entries.
