### ISSUE TITLE
tf.split should allow negative axis arguments

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#10290]
`tf.concat` does, for instance.

**Comment by Androbin** [comment]
Are you sure about `tf.concat`? The documentation at `https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/array_ops.cc#L369` doesn't say so. This might be a consistency issue.

**Comment by girving** [comment]
Yep, just confirmed in a shell.  I'll fix the documentation for `tf.concat`.

**Comment by girving** [comment]
@vrv @cwhipkey Fixed by someone else two hours before I submitted my CL.
