### ISSUE TITLE
FEATURE: Label scalar summaries

### ISSUE THREAD

**Issue by orome** [tensorflow/tensorflow#10292]
Often I log scalar summaries at intervals that are meaningful in their own right — e.g. at epochs or min-batch boundaries — and report this, rather than the global step, as the x-value with something like

    some_writer.add_summary(a_value, epoch_number)

or

    some_writer.add_summary(a_value, batch_number)

But the API has no way of indicating that these x-values are not "steps", and reports them in the TensorBoard UI as "Steps", which they are not.

_It would be nice to have a way of changing the "Steps" label to some other string (here, for example "Epoch" or "Batch")._

**Comment by asimshankar** [comment]
CC @dandelionmane @jart

**Comment by chihuahua** [comment]
I have migrated this issue to tensorflow/tensorboard#75 because TensorBoard has moved into its own repository. Lets continue discussion there.
