### ISSUE TITLE
Alpine Linux: __isnanf: symbol not found 

### ISSUE THREAD

**Issue by SydOps** [tensorflow/tensorflow#103]
I build tensorflow in alpine Linux in docker successfully, but when run the test, I got below error. Anything I missed?
```
$ python
>>> import tensorflow as tf
...
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: Error relocating /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: __isnanf: symbol not found
>>> exit()

/ # nm /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so |grep isnanf
                 U __isnanf@@GLIBC_2.2.5
/ #
```

How to fix the issue `__isnanf: symbol not found`

`Dockerfile` for your reference: https://github.com/BWITS/Docker-builder/blob/master/tensorflow/alpine/Dockerfile

**Comment by vrv** [comment]
From quick searches on that error message, it looks like this is Alpine specific: alpine seems to use a different c library than glibc, which we probably don't support. :(

**Comment by SydOps** [comment]
Thanks @vrv .

Your answer gives me hints, that I can install glibc in alpine:

https://github.com/jeanblanchard/docker-alpine-glibc/blob/master/Dockerfile
https://github.com/gliderlabs/docker-alpine/issues/11

**Comment by SydOps** [comment]
ticket can be closed, I have built it in alpine with `miniconda` which has Python compiled for glibc

**Comment by richfelker** [comment]
It should also be possible to build the C components from source so that they're linked to the correct libc rather than installing binaries from a foreign (glibc-based) system. This would be a less drastic solution.
