### ISSUE TITLE
TensorBoard Embeddings fail if a "+" character is in LOG_DIR subdirectory filename

### ISSUE THREAD

**Issue by austinstover** [tensorflow/tensorflow#10301]
### System information
- **Occurs in Tutorial**: DandelionMane's TF Dev Summit 2017 TensorBoard Tutorial
  - If learning_rate >= 1 (not that you would want to do that)
- **OS Platform**: Windows 10
- **TensorFlow install**: Binary
- **TensorFlow version**: 1.1.0
- **Exact command to reproduce**: Use a plus sign in the filename of one of LOG_DIR's subdirectories

### Problem
The tensorboard embeddings tab throws an "Error fetching projector config" if a + sign is used in a log_dir subdirectory; that is, if the projector_config.pbtxt is in that subdirectory.

**Comment by jart** [comment]
@dsmilkov Maybe we need to URLencode the projector config filename?

**Comment by jart** [comment]
This issue has been migrated to https://github.com/tensorflow/tensorboard/issues/73.
