### ISSUE TITLE
mnist_with_summaries does not produce node statistics

### ISSUE THREAD

**Issue by tazr** [tensorflow/tensorflow#10317]
### System information
- Windows 7 Enterprise 64
- TF 1.1.0 installed from pip
- CUDA 8.0/cuDNN 5.1.5
- GeForce GTX TITAN X
- command: python mnist_with_summaries.py

### Describe the problem
In https://www.tensorflow.org/get_started/graph_viz, mnist_with_summaries is given as an illustration of how to use tensorboard to show node statistics. However, it does not produce node statistics on my computer. Everything else is working correctly (the graph is there, summaries as well, the training goes smoothly).

### Source code / logs
https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py

**Comment by jart** [comment]
@chihuahua Mind taking a look at this? Could be some type of regression in tf_graph.

**Comment by chihuahua** [comment]
I am trying to repro the issue. This is what I see in the graphs tab. I clicked the Memory radio button on the left side and then selected a node. What do you see?

<img width="778" alt="screen shot 2017-06-04 at 3 23 26 am" src="https://cloud.githubusercontent.com/assets/4221553/26760745/701b65a8-48d5-11e7-935f-477fb63c0b35.png">

**Comment by chihuahua** [comment]
One small nit: Maybe you've tried this, but users have to select a Session run (to see node-specific stats for that run).
<img width="206" alt="screen shot 2017-06-04 at 3 26 34 am" src="https://cloud.githubusercontent.com/assets/4221553/26760761/d5b447ea-48d5-11e7-9b5c-70c181306f06.png">

**Comment by tazr** [comment]
Thanks, problem solved.
