### ISSUE TITLE
[Feature request] dynamically catch exceptions in TensorFlow as part of the graph execution

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#10332]
Via [this StackOverflow question](https://stackoverflow.com/questions/44137542/dynamically-catch-exceptions-in-tensorflow-as-part-of-the-graph-execution):

E.g. the `QueueBase.dequeue` function can raise an `OutOfRangeError` exception which I will receive in Python from the `Session.run` call. It would be nice to catch the exception inside the graph, similar as `tf.cond`. E.g. something like:

    result = tf.on_exception(queue.dequeue(), lambda: 42)

Maybe also the first argument would need to be a `lambda` such that it can properly set the context.
To make this work, like in `tf.cond`, the result from both arguments would need to be of the same type.

**Comment by jart** [comment]
This would be a very radical change to TensorFlow. What is the use case?

**Comment by albertz** [comment]
I was thinking about having some special logic inside my graph which does something different depending on whether there was such an exception or not.
Also, as I have multiple queues in my graph, I could do some more fine-grained handling.
But I see that this requires quite radical changes, and I can also solve my tasks in other ways, so maybe just let's close this.

**Comment by jart** [comment]
Sounds good. Glad to hear you're able to solve your problem in other ways.

**Comment by Joshuaalbert** [comment]
Can this be reopened? I have a use case. In my case, I am trying to use cholesky decomposition to solve a system, however sometimes it is not pos semi definite in which case it throws an error. I would like in this case to use SVD.
I need to do this check on each sub batch, i.e. using tf.unstack and doing the solve on each sub matrix.
It would be nice to be able to do 
```
result = tf.stack([tf.on_exception(_with_cholesky, _without)(...) for ... in tf.unstack(...)],axis=0)
```

**Comment by jart** [comment]
@Joshuaalbert Would it be possible to solve this problem with `tf.cond`?

**Comment by Joshuaalbert** [comment]
This is possible if there are a few conds and if the number of conds is static. But what I need to do is unstack along batch and perform the solve for each batch with a possible exception for each.

**Comment by jart** [comment]
Yes but even if an exception catching API was provided, it would most likely be designed in a way where you would need to say which specific error type and/or message regex you would want to catch, rather than catch-all. If you know what the error could be in advance, then it would most likely be possible to perform an expression on the input to see if it would result in an error, and if so, branch.

In your case, since you're working with batches, is it possible to maybe break the problem up into multiple sess.run calls?

**Comment by Joshuaalbert** [comment]
Yes in my case (and in all cases that I can imagine using this API) I know what the exception would be.
Indeed, one could sequentially do multiple sess.run calls with a try/catch around the sess.run pointing to different implementations, but this would, firstly, unparallelize the procedure completely, and also obfuscate the program structure. Ideally, it would maintain the python principles of readability so that collaborators can easily understand the code.

**Comment by Joshuaalbert** [comment]
There is another use case. The team who is creating GPflow then TF version of GPy (Gaussian processes for python) has an issue when cholesky fails/doesn't give numpy equivalent (https://github.com/GPflow/GPflow/issues/78).

**Comment by jart** [comment]
While I'm still not sure if in-graph exception handling is something we can do, your recent comments suggest you might be interested in [Eager execution mode](https://research.googleblog.com/2017/10/eager-execution-imperative-define-by.html). It's also possible @josh11b, @asimshankar, or @clattner might want to weigh in on this issue.

**Comment by Joshuaalbert** [comment]
@jart Eager execution mode sounds like https://github.com/yaroslavvb/imperative but more full featured. I was actually hoping something like this would come along. Indeed this gives access to pythonic control flow. But is there not a pretty large efficiency penalty as there can be no cse optimization?

**Comment by jart** [comment]
I'm not sure how graph optimizations work in Eager. It's possible something like `@tf.defun` would be able to apply those sorts of optimizations to your critical sections of code. [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) would be a better place to ask (I'm just a triager.)

TensorFlow graphs are turing complete ([example](https://github.com/akimach/EsotericTensorFlow/blob/master/brain_fuck.py)) and have [data flow ops](https://www.tensorflow.org/api_docs/cc/group/data-flow-ops) like queues. So it should be *possible* to do what you want to do, today, using a high performance pure graph without exceptions. While obtaining this kind of performance generally requires making tradeoffs on elegance, there's actually a lot of people on the team working on much more radical solutions that will let us eat our cake and have it too. They will take time.

**Comment by asimshankar** [comment]
@Joshuaalbert : At this point, depending on the precise computation there may be efficiency penalties with eager execution (it really depends on the model. For example, see the [eager example benchmarks](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/eager/python/examples/resnet50), some of which are are competitive with graph execution, some of which are not), and we're working towards addressing those.

As @jart pointed out, we're unlikely to have the bandwidth to design or pursue in-graph exception handling in the near future.

**Comment by erzel** [comment]
Here's another use-case. I'd like to loop, reading from a dataset until that dataset is exhausted. I need to do this in the sub-graph initializing a variable in my model. AFAIK, dataset iterator signals the end by throwing an exception. 
Perhaps, this can be more easily solved, if the iterator API would allow to test end-of-range?
