### ISSUE TITLE
Compilation error when install with CUDA 7.0: image_ops_gpu.cu.pic.o was not created

### ISSUE THREAD

**Issue by SealLive** [tensorflow/tensorflow#10342]
Similar to 
[https://github.com/tensorflow/tensorflow/issues/10258](url) 
and 
[https://stackoverflow.com/questions/44116381/error-when-install-tensorflow-from-source](url), 
no working solutions yet.
When I'm trying to install tensorflow r1.1 from source with CUDA 7.0, this error comes up:
```
1 error detected in the compilation of "/tmp/tmpxft_00005478_00000000-10_image_ops_gpu.cu.compute_52.cpp1.ii".
ERROR: /root/workspace/tensorflow/tensorflow/contrib/image/BUILD:20:1: output 'tensorflow/contrib/image/_objs/python/ops/_image_ops_gpu/tensorflow/contrib/image/kernels/image_ops_gpu.cu.pic.o' was not created.
ERROR: /root/workspace/tensorflow/tensorflow/contrib/image/BUILD:20:1: not all outputs were created or valid.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
Environment is Ubuntu 14.04, CUDA 7.0, CUDNN 4, gcc 4.8.4, bazel 0.4.5, tensorflow r1.1.
Because I don't have the privilege to upgrade the cuda driver version 346.46, which does not support CUDA 7.5 or 8.0, I have to stay on CUDA 7.0.
Could anyone help me? Thanks!

**Comment by gunan** [comment]
We currently support building with CUDA 8.0.
Building with earlier CUDA versions is supported only as best effort. However these days there are a few higher priority issues we need to focus on.
I will mark this issue as community support, maybe someone from the community can help.
