### ISSUE TITLE
TensorFlow build: protobuf/pyext/_message.so' failed

### ISSUE THREAD

**Issue by Spenhouet** [tensorflow/tensorflow#10357]
I'm trying to build TensorFlow with Bazel on Windows.

But i'm getting this error:

    ERROR: C:/users/spenh/appdata/local/temp/_bazel_spen/icnq02mb/external/protobuf/BUILD:623:1: 
    C++ compilation of rule '@protobuf//:python/google/protobuf/pyext/_message.so' failed: 
    msvc_cl.bat failed: error executing command 
    external/local_config_cc/wrapper/bin/msvc_cl.bat /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS ... (remaining 42 argument(s) skipped): 
    com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 2.
    ...
    C:\users\spenh\appdata\local\temp\_bazel_spen\icnq02mb\execroot\org_tensorflow\external\protobuf\python\google\protobuf\pyext\repeated_scalar_container.cc(307): fatal error C1057: Unerwartetes Dateiende bei der Erweiterung eines Makros
    C:\users\spenh\appdata\local\temp\_bazel_spen\icnq02mb\execroot\org_tensorflow\external\protobuf\python\google\protobuf\pyext\repeated_scalar_container.cc(307): fatal error C1057: Unerwartetes Dateiende bei der Erweiterung eines Makros
        
    Target //tensorflow/tools/pip_package:build_pip_package failed to build

Any idea what i can try to solve this? Or what information i could provide you to solve this?

 - Bazel: git/master (30.05.2017)
 - TensorFlow: git/master (30.05.2017) 
 - Python 3.6.1 x64
 - Visual Studio: 2017 x64
 - Cuda: 8.0
 - Java JDK 1.8.0_60
 - Windows 10
 - Nvidia 1080

Build command:

    bazel build -c opt --config=win-cuda --cpu=x64_windows_msvc --host_cpu=x64_windows_msvc --copt=-w --host_copt=-w tensorflow/tools/pip_package:build_pip_package

Stackoverflow link: https://stackoverflow.com/questions/44264801/tensorflow-bazel-build-protobuf-pyext-message-so-failed

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

(As per https://www.tensorflow.org/install/install_sources - building from source on Windows isn't supported yet, in that we don't have the bandwidth to debug various configurations. You might want to try the CMake build https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake)

**Comment by Spenhouet** [comment]
@asimshankar 
Why is this not a bug? How do you know?

**Comment by asimshankar** [comment]
@Spenhouet :  You snippet suggest that it is failing to build the protocol buffer library (not TensorFlow code) when using a particular version of MSVC.

What I meant to convey in the previous comment is that this is not a configuration that we have the bandwidth to support or debug. Figuring this out would require some experience/expertise with bazel-on-windows-building-protobuf-using-MSVC. You're likely to get more help on this from StackOverflow where there is a larger community.

We try to keep the github issues focused on bugs (on supported platforms) or feature requests.

Hope that makes sense. Thanks!

**Comment by Spenhouet** [comment]
@asimshankar I can't find my self to resolve this issue. I thought about trying CMake but on the GitHub page it says 
> It is not possible to load a custom Op library.
What i want to do, and why i think i need to build tensorflow in the first place, is to add a new optimization algorithm. So if i understand correct i don't even need to try to build with CMake because it wouldn't allow me to add any optimizer?

**Comment by kalaspuffar** [comment]
@Spenhouet Well your not alone atleast. I've built tensorflow HEAD, r1.1 and r1.0 with Visual Studio 2015 and 2017. Also tried with Bazel 0.4.5, 0.5.0, 0.5.1 and all of them fail. Tried it on Windows 7 and Windows 10.

**Comment by snnn** [comment]
Me too.

Hi @Spenhouet , the document is outdated.  You can load a custom op library dll or a filesystem dll on Windows. It's doable.
