### ISSUE TITLE
Python3 test failure: //tensorflow/python:saver_test

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorflow#1035]
Using the Python-3 configure, run command:
`bazel test -c opt //tensorflow/python:saver_test`

See below for the log of the failed test, with the key lines highlighted

........../usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-opt/bin/tensorflow/python/saver_test.runfiles/tensorflow/python/training/saver.py:848: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logging.warning("Ignoring: %s", str(e))
WARNING:tensorflow:Ignoring: [Errno 2] No such file or directory: '/tmp/saver_test/max_to_keep_sharded/s1-00001-of-00002.meta'
WARNING:tensorflow:Ignoring: [Errno 2] No such file or directory: '/tmp/saver_test/max_to_keep_sharded/s1-00000-of-00002.meta'
../usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-opt/bin/tensorflow/python/saver_test.runfiles/tensorflow/python/training/saver.py:1088: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  "match field type in CollectionDef.\n%s" % str(e))
WARNING:tensorflow:Type is unsupported, or the types of the items don't match field type in CollectionDef.
**'hello' has type str, but expected one of: bytes**
WARNING:tensorflow:Type is unsupported, or the types of the items don't match field type in CollectionDef.
name 'long' is not defined
WARNING:tensorflow:Type is unsupported, or the types of the items don't match field type in CollectionDef.
name 'long' is not defined
WARNING:tensorflow:Type is unsupported, or the types of the items don't match field type in CollectionDef.
name 'long' is not defined
WARNING:tensorflow:Type is unsupported, or the types of the items don't match field type in CollectionDef.
**'queue_name: "test_queue"\n' has type str, but expected one of: bytes**
F/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-opt/bin/tensorflow/python/saver_test.runfiles/tensorflow/python/training/saver.py:1063: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  "serialized. This key has %s" % type(key))
**WARNING:tensorflow:Only collections with string type keys will be serialized. This key has <class 'tensorflow.python.training.saver.Saver'>**
WARNING:tensorflow:Type is unsupported, or the types of the items don't match field type in CollectionDef.
name 'long' is not defined
.WARNING:tensorflow:Type is unsupported, or the types of the items don't match field type in CollectionDef.
name 'long' is not defined
WARNING:tensorflow:Type is unsupported, or the types of the items don't match field type in CollectionDef.
name 'long' is not defined
E.......W tensorflow/core/common_runtime/executor.cc:1094] 0x33a34d0 Compute status: Not found: Tensor name "v1" not found in checkpoint files /tmp/saver_test/basics
         [[Node: save_1/restore_slice_1 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/restore_slice_1/tensor_name, save_1/restore_slice_1/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1094] 0x33a34d0 Compute status: Not found: Tensor name "v0" not found in checkpoint files /tmp/saver_test/basics
         [[Node: save_1/restore_slice = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/restore_slice/tensor_name, save_1/restore_slice/shape_and_slice)]]
...........
======================================================================
ERROR: testGraphExtension (__main__.MetaGraphTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-opt/bin/tensorflow/python/saver_test.runfiles/tensorflow/python/training/saver_test.py", line 968, in testGraphExtension
    self._testGraphExtensionRestore()
  File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-opt/bin/tensorflow/python/saver_test.runfiles/tensorflow/python/training/saver_test.py", line 952, in _testGraphExtensionRestore
    logits = tf.get_collection("logits")[0]
**IndexError: list index out of range**

======================================================================
FAIL: testAddCollectionDef (__main__.MetaGraphTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-opt/bin/tensorflow/python/saver_test.runfiles/tensorflow/python/training/saver_test.py", line 760, in testAddCollectionDef
    self.assertEqual(len(collection_def), 9)
**AssertionError: 4 != 9**

**Comment by girving** [comment]
@sherrym: I fixed some of the issues in https://github.com/tensorflow/tensorflow/compare/master...girving:py3?expand=1, but more remain.

**Comment by caisq** [comment]
With other GPU/Mac/Python3 test failures fixed or soon-to-be-fixed, this test failure is becoming the issue blocking release.

**Comment by girving** [comment]
I seem to be swamped today, so can you or @sherrym take a look?

**Comment by sherrym** [comment]
This has been fixed and will be available with the next sync.
