### ISSUE TITLE
worker.pb.h file not found

### ISSUE THREAD

**Issue by ashokbugude** [tensorflow/tensorflow#10364]
I am trying to find the file worker.ph.h file which is included in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/grpc_remote_worker.cc

Can I know if need to run any command like below one to generate the file
**bazel build tensorflow/cc:cc_ops** as indicated in https://github.com/tensorflow/tensorflow/issues/3017 to generate the respective ops files

**Comment by gunan** [comment]
pb.h files are generated from protocol buffers.
Bazel creates these once you have the dependencies set up correctly.
In this case, `"//tensorflow/core:worker_proto_cc",` dependency is the correct proto dependency we use.

**Comment by jart** [comment]
Yeah when you bazel build it, you can find it by fishing around in the bazel-bin/ or bazel-genfiles/ directory.

**Comment by ashokbugude** [comment]
Is there any command to build all core files at a time, instead of building
each such files.

**Comment by jart** [comment]
`bazel build //tensorflow/core/...`
