### ISSUE TITLE
Weird bugs after successful running until reboot computer

### ISSUE THREAD

**Issue by lfwin** [tensorflow/tensorflow#10374]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
r0.9
- **Bazel version (if compiling from source)**:
0.2.3
- **CUDA/cuDNN version**:
v4
- **GPU model and memory**:
k80

Due to need debug some old Tensorflow code, i need to install TF0.9 version, after i installed, it could run code, everything goes okey. But after rebooting computer, run tensorflow code once, it can not run again, it trapped in tf.Session() funtion.

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
