### ISSUE TITLE
Lack support of qint32 in tf.nn.tanh

### ISSUE THREAD

**Issue by frankyjuang** [tensorflow/tensorflow#10376]
According to the [doc](https://www.tensorflow.org/versions/master/api_docs/python/tf/tanh), the `tanh` operation supports floating point inputs as well as fixed point inputs of type qint32. However, in the latest master, a `TypeError` raised when running following code:
```
import tensorflow as tf
sess = tf.InteractiveSession()
x = tf.constant([1.,2.,3.], dtype=tf.float32)

from tensorflow.python.ops.gen_array_ops import quantize_v2
x_quant = quantize_v2(x, min_range=0., max_range=4., T=tf.qint32)
y_quant = tf.nn.tanh(x_quant[0])
```
The complete error message is 
```
TypeError: Value passed to parameter 'x' has DataType qint32 not in list of allowed values: float16, float32, float64, complex64, complex128
```

According to the backend function `_tanh` in `gen_math_ops.py`:
```
def _tanh(x, name=None):
  r"""Computes hyperbolic tangent of `x` element-wise.

  Args:
    x: A `Tensor`. Must be one of the following types: `half`, `float32`, `float64`, `complex64`, `complex128`.
    name: A name for the operation (optional).
```
It shows that it doesn't support qint32.

**Comment by jart** [comment]
@dr4b The Python docstring for `tanh` and `sigmoid` says they support various types, e.g. qint32, but fail when those types are passed.

CC: @girving

**Comment by dr4b** [comment]
We gladly accept pull requests on the docs!

(or I can go change the docstring.  What is the actual list of possible types?  We currently seem to say "float, double, int32, complex64, int64, or qint32" which is quite a bit off from "float16, float32, float64, complex64, complex128" in the error message OR the backend "`half`, `float32`, `float64`, `complex64`, `complex128`".)

**Comment by girving** [comment]
This is just a Python doc error: the C++ op registrations use a reasonable set of types (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/math_ops.cc#L193) but the Python wrapper does not (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_ops.py#L2061).
