### ISSUE TITLE
tf.contrib.data.Dataset fails to batch elements that are tuples

### ISSUE THREAD

**Issue by edgimar** [tensorflow/tensorflow#10377]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution**: Linux Ubuntu 16.04.2 LTS
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: ('v1.2.0-rc0-312-g0b72359', '1.2.0-rc0')
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: TITAN X (Pascal) / 12186MiB

### Issue

With the new `tf.contrib.data.Dataset` API, it seems not possible to batch the outputs of a Dataset instance whose elements are tuples.  Code demonstrating problem:

```
ds = tf.contrib.data.Dataset.range(100).map(lambda x: (x, 2*x))
batched_ds = ds.batch(4)
batched_iter = batched_ds.make_one_shot_iterator()
nxt = batched_iter.get_next()

with tf.Session() as sess:
    val = sess.run(nxt)
    print(type(val))  # => <type 'tuple'>
    print(len(val))  # => 2
```
It seems that `sess.run(nxt)` should provide an object having 4 elements.

**Comment by asimshankar** [comment]
`val` is a tuple of batches, in this case, `print(val)` yields:

```python
(array([0, 1, 2, 3]), array([0, 2, 4, 6]))
```

@mrry for comments on how batch is intended to and documented to deal with tuples.

**Comment by edgimar** [comment]
On second thought, I think this is the expected behavior -- seemed unintuitive though because the batching is done by grouping elements of a series of tuples, rather than grouping the series of tuples where each tuple is a row in the output 'batch tensor'.
