### ISSUE TITLE
sequence_loss_by_example()  type error for rnn/ptb

### ISSUE THREAD

**Issue by corbyrosset** [tensorflow/tensorflow#1038]
Hi 

I downloaded 0.6.0 for python 2.7 and I tried running the rnn/ptb example but got a type error:

$ python ptb_word_lm.py --data_path=/this/path/ --model small

I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 8
I tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter op parallelism threads: 8
Traceback (most recent call last):
  File "ptb_word_lm.py", line 303, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "ptb_word_lm.py", line 280, in main
    m = PTBModel(is_training=True, config=config)
  File "ptb_word_lm.py", line 135, in __init__
    [tf.ones([batch_size * num_steps])])
TypeError: sequence_loss_by_example() takes at least 4 arguments (3 given)

It seems that this sequence_loss_by_example() method is imported from seq2seq which imports it from tensorflow.python.ops.seq2seq. Beyond that I'm not really sure how this happened.

Thanks

**Comment by vrv** [comment]
If you installed the 0.6.0 pip, make sure to also clone the repo at the 0.6.0 tag -- if you fetch from master, the pip binary may not currently work with master, since we're still in a rapid development phase.

**Comment by lukaszkaiser** [comment]
It's as VIjay says, it works ok on head.
