### ISSUE TITLE
error ，a configure error! help!

### ISSUE THREAD

**Issue by lulinyuan** [tensorflow/tensorflow#10390]
➜  tensorflow git:(master) ✗ ./configure
Please specify the location of python. [Default is /usr/bin/python]: 
Found possible Python library paths:
  /opt/ros/kinetic/lib/python2.7/dist-packages
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/opt/ros/kinetic/lib/python2.7/dist-packages]

Using python library path: /opt/ros/kinetic/lib/python2.7/dist-packages
Do you wish to build TensorFlow with MKL support? [y/N] 
No MKL support will be enabled for TensorFlow
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] 
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Do you wish to build TensorFlow with VERBS support? [y/N] 
No VERBS support will be enabled for TensorFlow
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] u
Invalid selection:  u
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Do you want to use clang as CUDA compiler? [y/N] n
nvcc will be used as CUDA compiler
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the cuDNN version you want to use. [Leave empty to use system default]: 
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
Do you wish to build TensorFlow with MPI support? [y/N] n
MPI support will not be enabled for TensorFlow
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading options for 'clean' from /home/lulin/tensorflow/tools/bazel.rc:
  Inherited 'build' options: --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --genrule_strategy=standalone -c opt
INFO: Reading options for 'clean' from /home/lulin/tensorflow/.tf_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python --action_env PYTHON_LIB_PATH=/opt/ros/kinetic/lib/python2.7/dist-packages --define PYTHON_BIN_PATH=/usr/bin/python --define PYTHON_LIB_PATH=/opt/ros/kinetic/lib/python2.7/dist-packages --force_python=py2 --host_force_python=py2 --python2_path=/usr/bin/python --define with_jemalloc=true --action_env TF_NEED_CUDA=1 --action_env TF_NEED_OPENCL=0 --action_env TF_CUDA_CLANG=0 --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda --action_env TF_CUDA_VERSION=8.0 --action_env GCC_HOST_COMPILER_PATH=/usr/bin/gcc --action_env TF_CUDNN_VERSION= --action_env CUDNN_INSTALL_PATH=/usr/local/cuda-8.0 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2
Unrecognized option: --action_env

bazel is 0.3.0;cuda8.0;cudnn5.0.

**Comment by gunan** [comment]
You need to upgrade bazel.
TF at head requires bazel version 0.4.5 or higher.

**Comment by lulinyuan** [comment]
thank!.i had got it.the error is the bazel! thanks
