### ISSUE TITLE
Build Error gcc: error: ”-DEIGEN_USE_VML”: No such file or directory

### ISSUE THREAD

**Issue by mstfldmr** [tensorflow/tensorflow#10406]
$ bazel build --config=mkl --copt=”-DEIGEN_USE_VML” -c opt //tensorflow/tools/pip_package:build_pip_package
WARNING: /home/mstf/workspace/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/mstf/workspace/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
ERROR: /home/mstf/.cache/bazel/_bazel_mstf/ac8273660b2bd94e42901d7fff45bcd5/external/grpc/BUILD.bazel:71:1: C++ compilation of rule '@grpc//:gpr' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 34 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error: ”-DEIGEN_USE_VML”: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 119.271s, Critical Path: 14.01s

**Comment by mrsabhar** [comment]
Can you share the solution for this error? 
**gcc: error: ”-DEIGEN_USE_VML”: No such file or directory**

**Comment by jmugan** [comment]
I have the same error.

**Comment by Paeans** [comment]
--copt=-DEIGEN_USE_VML
Without using the quotation marks, I have compiled the code with no this error.
Please let me know if it's right.

**Comment by wj1066** [comment]
I have the same error too, anyone has solutions?
@mstfldmr @mrsabhar @Paeans

**Comment by jmugan** [comment]
I think I ended up updating the compiler. It was one of those situations where I did a lot of stuff, and at the end, it wasn't clear what fixed it.

**Comment by carabolic** [comment]
I've had the same problem, copied the build command from an [intel blog article](https://software.intel.com/en-us/articles/tensorflow-optimizations-on-modern-intel-architecture). As it turns out it really was the quotation marks, as @Paeans pointed out. Simply replace `”` (stylish quotation marks) with `"` (simply double ticks).
