### ISSUE TITLE
Operation functions return operations, not Tensors

### ISSUE THREAD

**Issue by orome** [tensorflow/tensorflow#10405]
The way the return value for many TensorFlow operations is described in the documentation is a potential (and actual, from experience) source of confusion. 

For example the [docs for `tf.acos`][1] say (like many ops): 

> "Returns: A Tensor. ..." 

But that's not true, is it: Tensors are graph *edges* (pipes through with values flow), while `tf.acos` is a graph *node* (an operation that needs to be executed to put a value into the pipe). Right?

Shouldn't the documentation say that these functions return _operations_, which, when evaluated, produce a Tensor? (And if not why does the TensorFlow documentation say that these operations return Tensors?)

**Comment by asimshankar** [comment]
`tf.acos` does not return a node in the graph, it creates a node in the graph and returns a [`tf.Tensor`]
(https://www.tensorflow.org/api_docs/python/tf/Tensor) Python object that is a handle to the output of that operation. For example, in the snippet:

```python
x = tf.acos(tf.constant(1))
y = tf.cos(x)
```

The `x` refers to the value (the "Tensor") that is flowing on the "edges" between the "acos" and "cos" nodes.

Hope that helps.

**Comment by orome** [comment]
@asimshankar — Yes, it does help. 

I think what's confusing me is the notion of running or evaluating operations. But now I think I see. 

Functions like `tf.cos` add a node to the graph and return an edge, and when I `run` or `eval` I'm tugging on the edge and _that_, rather than directly "running" the operation, is what invokes the operation (and so on for any edges it tugs on in turn).

In effect, if you will, I don't make the machinery go by pressing the button on the op (which is what I naively expect), but but by drawing from the pipe that comes out of it; and its that action that fills all the pipes in the graph with values. That's why I'm handed back a pipes (`tf.Tensor`): everything operates on them, not the operations they emerge from.

(I'm still a bit [puzzled about this](https://stackoverflow.com/q/44335033/656912) though, which is what sent me down the road to this misunderstanding in the first place.)
