### ISSUE TITLE
Unimplement: Op TopK is not available in GraphDef version 8.

### ISSUE THREAD

**Issue by ziiw** [tensorflow/tensorflow#1040]
Hi !

I've just finish to install TensorFlow on my OSX 10.11.13.

When I do: `bazel-bin/tensorflow/examples/label_image`

`E tensorflow/core/common_runtime/executor.cc:275] Executor failed to create kernel. Unimplemented: Op TopK is not available in GraphDef version 8. It has been removed in version 7. Use TopKV2 instead.
     [[Node: top_k = TopK[T=DT_FLOAT, k=5, sorted=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Const/_0)]]
E tensorflow/examples/label_image/main.cc:321] Running print failed: Unimplemented: Op TopK is not available in GraphDef version 8. It has been removed in version 7. Use TopKV2 instead.
     [[Node: top_k = TopK[T=DT_FLOAT, k=5, sorted=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Const/_0)]]`

Did someone already seen this ?

**Comment by girving** [comment]
@petewarden is hitting the same thing.  Looking at it now.

**Comment by girving** [comment]
Diagnosed: we deprecated the C++ `TopK` op in favor of `TopKV2` but that didn't affect the C++ graph builder API.  Fix for label_image coming up, and I'll file a more detailed bug to add a deprecation feature when registering ops.

**Comment by girving** [comment]
Fix in review.

**Comment by ziiw** [comment]
Hey thx !

On the tensorflow-0.6.0, just download, I run: `./configure` && `bazel build -c opt //tensorflow/tools/pip_package:build_pip_package`

then I got this: `ERROR: /Users/user/tensorflow/tensorflow-0.6.0/tensorflow/tensorboard/BUILD:44:1: error loading package 'tensorflow/python': Every .bzl file must have a corresponding package, but 'google/protobuf' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist. and referenced by '//tensorflow/tensorboard:tensorboard'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 15,841s`

Did I forgot something ?

**Comment by ziiw** [comment]
Thx, how can I access this review ?

**Comment by nysalad** [comment]
FYI if you just want to get the label_image working locally,reverting the file works for me
git checkout 3ede5506acf6a026f09eda33277d46e34ac7ed10 tensorflow/core/kernels/topk_op.cc

**Comment by ziiw** [comment]
Nice thx @nysalad :)

I've got some trouble installing tensorflow for label_images, I'm gonna uninstall all and re-install ;)

**Comment by girving** [comment]
@vrv: Will there be a push to github soon?  Looks like the last one was Tuesday.

**Comment by vrv** [comment]
Probably some time today

**Comment by girving** [comment]
@ziiw: master should work for you now, let me know if not.

**Comment by HamedMP** [comment]
@ziiw I just pull again from master, compiled the source, installed the wheel and compiled the code for image_label, the same error, nothing changed
