### ISSUE TITLE
Could not create Tensorflow Graph: Invalid argument: No OpKernel was registered to support Op 'Const' with these attrs

### ISSUE THREAD

**Issue by ashokbugude** [tensorflow/tensorflow#10410]
I am try to create to Graph by running below command
tensorflow::Status s = session->Create(tensorflow_graph);
But I get below error 

Could not create Tensorflow Graph: Invalid argument: No OpKernel was registered to support Op 'Const' with these attrs.  Registered devices: [CPU], Registered kernels: \<no registered kernels\>

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by ashokbugude** [comment]
Thanks
But I figured out the issue..
I am trying to use TensorFlow Libraries in android ndk.
If I place libraries of both 'arm64-v8a' and 'armeabiv-7a' libraries in my project , it works fine. If I remove either of these the above error is thrown.

**Comment by ashokbugude** [comment]
I have built Tensoflow using bazel. 
I have taken the libraries from tensorflow and used in android ndk, by stetting abi as either of  'arm64-v8a' or 'armeabiv-7a' and am executing 
tensorflow::Status s = session->Create(tensorflow_graph); in android ndk from 
https://github.com/miyosuda/TensorFlowAndroidMNIST/blob/master/jni-build/jni/tensorflow_jni.cc

**Comment by jart** [comment]
OpKernels not loading when with Android is a common issue. It might have something to do with what's in this talk: https://youtu.be/0r9w3V923rk?t=19m39s. There's also a bunch of [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) issues. Let us know if you're certain there's a bug in TensorFlow.
