### ISSUE TITLE
ValueError: Attempt to have a second RNNCell use the weights of a variable scope that already has weights: 

### ISSUE THREAD

**Issue by dhirajpatnaik16297** [tensorflow/tensorflow#10415]
'generator/rnn_cell/rnn/basic_rnn_cell'; and the cell was not constructed as BasicRNNCell(..., reuse=True).  To share the weights of an RNNCell, simply reuse it in your second calculation, or create a new one with the argument reuse=True.

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
