### ISSUE TITLE
Random crop a patch from a various-sized image read in TFRecord

### ISSUE THREAD

**Issue by hgffly** [tensorflow/tensorflow#10413]
I have posted my question on stackoverflow but no ones answered me. [here](https://stackoverflow.com/questions/44152661/random-crop-a-patch-from-a-various-sized-image-read-in-tfrecord)
I found another similar question posted more than one year ago on stackoverflow as well, [How to read images with different size in a TFRecord file.
](https://stackoverflow.com/questions/35028173/how-to-read-images-with-different-size-in-a-tfrecord-file)
I tried the method someone suggested in the page, image = tf.reshape(image_data, tf.pack([image_rows, image_cols, 3])), but it still fails.

And I read the comments given by  Yaroslav Bulatov, performing randomly crop and resize them to a fixed size before converting them to TFRecord. It should be available, but it may increase the size of TFRecord file for saving a lot of cropped images. 
But what I'm curious about is that if the image size can't be utilized during training, why the [example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/how_tos/reading_data/convert_to_records.py) provided by the tutorial document of Tensorflow would write the width, height and depth of the image in TFRecord? That really confuses me. So is it possible to read images with different size in a TFRecord file? If it's possible, how to do it? Thanks

**Comment by asimshankar** [comment]
`tf.pack` existed in versions of TensorFlow prior to 1.0.
That has been replaced by [`tf.stack`](https://www.tensorflow.org/api_docs/python/tf/stack) since then.

Closing this out as we aim to keep Github issues focused on bugs and feature requests.
