### ISSUE TITLE
Separate tensorboard from tensorflow (core)

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#10429]
I suggest to separate tensorboard from tensorflow.

This could mean:
* break tensorboard to its own repos (under the same organization)
* publish a separate tensorboard wheel / package on pypi. 

The advantages of this are:
* simpler building of tensorboard which will make it easier for non core tensorflow members to contribute to the development of the project.
* tensorboard to operate on its own release cycle
* simpler installation of tensorboard (it can be installed on its own without needing full install of tensorflow)

**Comment by jart** [comment]
I agree. We're actually currently working on exactly that. Assigning to @dandelionmane.

However TensorBoard will continue to be installed when you install the TensorFlow pip package. So this change will mostly impact developers, and should have zero user facing impact.

**Comment by cancan101** [comment]
You could still create a second wheel / pypi package for tensorboard and have the tensorflow package install / depend on that.

**Comment by dandelionmane** [comment]
This is now complete. Please check out the new repo here: [https://github.com/tensorflow/tensorboard](https://github.com/tensorflow/tensorboard). You can also pip install latest tensorboard by running `pip install tensorflow-tensorboard`. (We're working on getting `pip install tensorboard` to work too.)

Also, @cancan101, I know we've been a bit unresponsive on your TensorBoard issues and pull requests. Now that we're in our own repo, we're committing to be more responsive to GitHub issues and PRS. :)

**Comment by wookayin** [comment]
Great job!

Just a question -- is the (legacy) [tensorboard module](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tensorboard) in the original tensorflow repository going to removed, or will it be kept?

**Comment by bydsky** [comment]
@dandelionmane 

> (We're working on getting pip install tensorboard to work too.)

It seems tensorboard is used by https://github.com/dmlc/tensorboard.
Is there a plan to provide a tf independent package which can be used by other ML frameworks?

**Comment by weiliu620** [comment]
After upgrading TF to 1.3rc1, I have this error when start tensorboard
```
No such file or directory: '/usr/local/lib/python3.4/dist-packages/tensorflow/tensorboard/TAG'
```
I reported the issue at #12270

**Comment by david-waterworth** [comment]
Is the plan to also move tf.summary to tensorboard? Currently tensorboard still requires tensorflow to be importable, and if you want to generate a file yourself I assume you also need to use tf.summary? Not a big deal but it seems like tf.summary  and tensorboard are coupled
