### ISSUE TITLE
Ability to add to an existing named scope

### ISSUE THREAD

**Issue by orome** [tensorflow/tensorflow#10422]
Currently it is impossible to use `tf.name_scope` to add additional elements to an existing scope. Using the same name a second time creates a new scope (with an appended index). This means that any elements that need to be in the same scope must be defined close together in source, which is not always consistent with the logic of the code.

A desirable feature would be the ability to add to an existing named scope, either with a new named parameter for `tf.name_scope` (e.g. Boolean `add_to_existing`), or with a new related function (e.g., `tf.existing_name_scope`).

**Comment by ppwwyyxx** [comment]
Vote for it. 
Discussed (but closed) in #6007.

**Comment by orome** [comment]
Actually [this](https://github.com/tensorflow/tensorflow/issues/6007#issuecomment-264322793) is a satisfactory solution (I don't know why it didn't occur to me!).

**Comment by michaelisard** [comment]
Closing for now since it seems there's a workable solution. Please reopen if there's still an issue.
