### ISSUE TITLE
Specify which scopes are removed from TensorBoard main graph by default

### ISSUE THREAD

**Issue by orome** [tensorflow/tensorflow#10421]
The heuristics used by TensorBoard to determine which scopes are added to the "main graph" and which are not by default often results in scopes being included that obscure the underlying network structure.

It would be nice to have an additional named parameter for `tf.name_scope` that indicated whether that scope should be removed (or included) in the main graph by default.

**Comment by dandelionmane** [comment]
Migrating to tensorflow/tensorboard
