### ISSUE TITLE
Android TF Classify: Reduce input size 

### ISSUE THREAD

**Issue by anonym24** [tensorflow/tensorflow#10438]
I'm trying to reduce input size in ClassifierActivity, but I get ` java.lang.IllegalArgumentException: Input to reshape is a tensor with 128 values, but the requested shape requires a multiple of 2048`

```
  private static final int INPUT_SIZE = 96; // original 224
  private static final int IMAGE_MEAN = 117;
  private static final float IMAGE_STD = 1;
  private static final String INPUT_NAME = "input";
  private static final String OUTPUT_NAME = "output";
```

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/ClassifierActivity.java#L61

What should I do to reduce it? (my cropped image is also 96x96)

Also do I have to change `IMAGE_MEAN` ? Not sure what it means

**Comment by jubjamie** [comment]
_Warning: As this doesn't appear to be a bug with Tensorflow, the devs may ask for this to be moved to Stack Ovefrlow._

Can I confirm that you are using a new model? You aren't just trying to change in input size? Can you post some more information about what you are doing?

**Comment by anonym24** [comment]
model downloaded by default: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/download-models.gradle

I wanted to know how to reduce input image to speed-up processing?

I did something like this for tiny yolo (TF Yolo Detector), I reduced input resolution to get more fps (of course it reduces quality for recognition but I also use different methods to crop interested parts for processing in my image, not just whole frame from camera)

**Comment by jubjamie** [comment]
Yeah that won't work if you're using the default model. You have to give it the correct image size otherwise it will fail. CNNs carefully construct their architectures for a certain image size, you can't give them any size usually without some form of resize of reshape happening. If you read up CNNs hopefully you'll better understand the issue and ways to get around it. Sorry.

**Comment by anonym24** [comment]
It's ok, thanks. I expected that it would be something like this. So this is why I prefer to use more yolo detector than others demos for android devices

**Comment by jubjamie** [comment]
I'm pretty sure yolo just scales the image back up/down to the correct size.

**Comment by anonym24** [comment]
Hm.. I guess for yolo it can be any px size multiple by 32 as I know (64x64, 96x96, 416x416)
and when reducing this input size we get more fps
so there is difference (the smaller images the faster but less accuracy of course)

**Comment by jubjamie** [comment]
Hmm fair enough.

**Comment by andrewharp** [comment]
@anonym24 That's correct, the default Inception model requires a 224x224 input. Closing as this is neither a bug nor feature request.
