### ISSUE TITLE
Failed to build on Mac OSX: "Could not find python binary"

### ISSUE THREAD

**Issue by tillahoffmann** [tensorflow/tensorflow#10436]
I am trying to compile tensorflow from source but cannot build `master`. The build for the pip package fails with the following error message

```
ERROR: /Users/till/git/tensorflow/tensorflow/tensorboard/components/vz_sorting/BUILD:8:1: Compiling 2 TypeScript files failed: execrooter failed: error executing command 
  (cd /private/var/tmp/_bazel_till/3e885964b28c274cf7e8652af4ed1911/execroot/tensorflow && \
  exec env - \
  bazel-out/host/bin/tensorflow/tensorboard/scripts/execrooter bazel-out/local-py3-opt/bin/tensorflow/tensorboard/components/vz_sorting/vz_sorting-tsc-execroot.json): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "bazel-out/host/bin/tensorflow/tensorboard/scripts/execrooter", line 168, in <module>
    Main()
  File "bazel-out/host/bin/tensorflow/tensorboard/scripts/execrooter", line 148, in Main
    raise AssertionError('Could not find python binary: ' + PYTHON_BINARY)
AssertionError: Could not find python binary: python3
```

I am running Mac OSX 10.12.4, bazel 0.4.5, python 3.6.1 in a conda virtual environment, Apple LLVM version 8.1.0 (clang-802.0.42). This might be related to https://github.com/bazelbuild/bazel/issues/2752.

Any suggestions would be greatly appreciated.

**Comment by gunan** [comment]
What is the output of `which python3` in the terminal you are trying to build TF?
Also, did you run configure before building?

**Comment by tillahoffmann** [comment]
@gunan, thanks for looking into this. Yes, I have run configure. Here is the output.

```
tensorflow git:(master) ./configure
Please specify the location of python. [Default is /Users/till/miniconda3/envs/tensorflow/bin/python]: 
Found possible Python library paths:
  /Users/till/miniconda3/envs/tensorflow/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/Users/till/miniconda3/envs/tensorflow/lib/python3.6/site-packages]

Using python library path: /Users/till/miniconda3/envs/tensorflow/lib/python3.6/site-packages
Do you wish to build TensorFlow with MKL support? [y/N] 
No MKL support will be enabled for TensorFlow
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Do you wish to build TensorFlow with VERBS support? [y/N] 
No VERBS support will be enabled for TensorFlow
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] 
No CUDA support will be enabled for TensorFlow
Do you wish to build TensorFlow with MPI support? [y/N] 
MPI support will not be enabled for TensorFlow
.........
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Configuration finished
```

And some more diagnostics:

```
which python  # /Users/till/miniconda3/envs/tensorflow/bin/python
which python3  # /Users/till/miniconda3/envs/tensorflow/bin/python3
python3 --version  # Python 3.6.1 :: Continuum Analytics, Inc.
```

**Comment by gunan** [comment]
All looks good, thanks.
What is the exact bazel command you are running after configure?

**Comment by tillahoffmann** [comment]
I have tried the following both with the same error:

```
bazel build //tensorflow/tools/pip_package:build_pip_package
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
```

Also, here is the full environment.

```
pip freeze
appnope==0.1.0
bleach==1.5.0
cycler==0.10.0
decorator==4.0.11
entrypoints==0.2.2
html5lib==0.999
ipykernel==4.6.1
ipython==6.1.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
MarkupSafe==0.23
matplotlib==2.0.2
mistune==0.7.4
nbconvert==5.2.1
nbformat==4.3.0
notebook==5.0.0
numpy==1.12.1
pandocfilters==1.4.1
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.14
ptyprocess==0.5.1
Pygments==2.2.0
pyparsing==2.1.4
python-dateutil==2.6.0
pytz==2017.2
pyzmq==16.0.2
qtconsole==4.3.0
scipy==0.19.0
simplegeneric==0.8.1
six==1.10.0
terminado==0.6
testpath==0.3
tornado==4.5.1
tqdm==4.14.0
traitlets==4.3.2
wcwidth==0.1.7
widgetsnbextension==2.0.0
```

**Comment by gunan** [comment]
I see, configuration and bazel command all looks good.
@jart This looks related to https://github.com/tensorflow/tensorflow/commit/b659bc39f27e81b3249f73710671059589c5daa1#diff-f0892bf77329d113fc9bd987ae1d7ec3
Any ideas?

**Comment by jart** [comment]
does it work if you disable sandbox?

**Comment by tillahoffmann** [comment]
@jart, I have tried `bazel build --config=opt --genrule_strategy=standalone --spawn_strategy=standalone //tensorflow/tools/pip_package:build_pip_package
` without success. Is there another way to turn of sandboxing?

**Comment by jart** [comment]
@nlopezgi wrote the Python auto configure script IIRC.

**Comment by MatthiasWinkelmann** [comment]
I'm quite sure this is related to https://github.com/bazelbuild/bazel/issues/2752. Until that fix percolates through the releases: I got the build to move on without tensorboard by deleting line https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/BUILD#L162, i. e.

```"//tensorflow/tensorboard",```

I also tried changing the 239 occurrences of ```PYTHON_?(BIN)(ARY)?_?(PATH)? ?=``` in 132 files, plus the other 196 occurrences in 108 files in ```/tmp/_bazel/```, but bazel apparently checks hashes for the files it generates.

**Comment by tillahoffmann** [comment]
@MatthiasWinkelmann, thanks for the suggestion.

I've just tried compiling with the new bazel 0.5.1 but get the same error.

**Comment by tillahoffmann** [comment]
I can compile tensorflow using the current `master` of bazel so hopefully this issue will be fixed in bazel 0.5.2.

**Comment by justprotato** [comment]
@tillahoffmann , could you tell me how to install the master version of bazel? so that I can solve the problem like yours? Thank you!

**Comment by WorksWellWithOthers** [comment]
@justprotato 

To test out bazel, you need to compile it. To compile a development version of Bazel, you need the latest released version of bazel, which can be compiled from source.

bazel build //src:bazel builds the Bazel binary using bazel from your PATH and the resulting binary can be found at bazel-bin/src/bazel. This is the recommended way of rebuilding Bazel once you have bootstrapped it.

1. Install a release version of Bazel

2. git clone the master branch of Bazel then checkout HEAD (https://github.com/bazelbuild/bazel/issues/2140)

3. Run:  `bazel build //src:bazel` in the directory where you have the master branch files.

4. The output files are in the src folder inside the bazel-bin folder.

5. Replace your bazel file (example: /usr/local/bin/bazel) with the one in the bazel-bin/src folder.

**Comment by 50417** [comment]
`ERROR: /private/var/tmp/_bazel_sohilshrestha/ae3fc0f2acf0ccc3faaa1a969a080e66/external/base/image/BUILD:6:1: Couldn't build file external/base/image/003.tar.gz.nogz.sha256: SHA256 external/base/image/003.tar.gz.nogz.sha256 failed (Exit 1): sha256 failed: error executing command 
  (cd /private/var/tmp/_bazel_sohilshrestha/ae3fc0f2acf0ccc3faaa1a969a080e66/execroot/phd && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/build_defs/hash/sha256 bazel-out/darwin-opt/bin/external/base/image/003.tar.gz.nogz bazel-out/darwin-opt/bin/external/base/image/003.tar.gz.nogz.sha256)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "bazel-out/host/bin/external/bazel_tools/tools/build_defs/hash/sha256", line 203, in <module>
    Main()
  File "bazel-out/host/bin/external/bazel_tools/tools/build_defs/hash/sha256", line 176, in Main
    raise AssertionError('Could not find python binary: ' + PYTHON_BINARY)
AssertionError: Could not find python binary: python3.6`

`which python3
/usr/local/bin/python3`

Similar ERROR encountered. Any help please?

**Comment by WorksWellWithOthers** [comment]
What version of Python are you running?
Is it 3.6?
Different topic but I just read that:
'Note: As of version 1.2, TensorFlow no longer provides GPU support on macOS.'

I'm not sure if you want to train without a GPU.

**Comment by 50417** [comment]
I am running python 3.6. 
GPU support was disabled with configuring.

**Comment by nlopezgi** [comment]
The error you are getting does not seem to me to be related at all with this thread (this thread was for issues with python related to TF configure, while your error is occurring when trying to run a python script located in bazel_tools/tools/build_defs/hash/sha256.
My first impression is that you need to have python in your path (not just python3) as this script under bazel_tools might just have it hardcoded somewhere (i.e. this error is not coming from TF code, its native bazel tools).

**Comment by 50417** [comment]
@nlopezgi Sorry for posting it in this thread. Will post in Bazel issue. However i tried keeping python3 path in PATH variable. But it will still generate the same error.

**Comment by nlopezgi** [comment]
did you add a symlink from usr/local/bin/python -> python3
(all that this script requires is likely for usr/local/bin/python to exist and point to some python)
