### ISSUE TITLE
How to do element wise operation for two Tensors?

### ISSUE THREAD

**Issue by kemaswill** [tensorflow/tensorflow#10443]
Say, I have two Tensors A and B, both with shape [-1, m, d]. How could I get a Tensor C with shape [-1, m*(m-1)/2, d] so than C_ij = A_i + B_j? Where + is an element wise addition. I know there is an element-wise operation named tf.add, but how should I use it? Thanks a lot.

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
