### ISSUE TITLE
Tensorflow Errors with uint8 addition

### ISSUE THREAD

**Issue by blake-varden** [tensorflow/tensorflow#10447]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
8.0
- **GPU model and memory**:
Nvidia Titan X Pascal 
- **Exact command to reproduce**:
```
import tensorflow as tf
a=tf.constant([1],dtype=tf.uint8)
b=tf.constant([2],dtype=tf.uint8)
c=a+b
session=tf.Session()
with session.as_default():
    session.run(c)
```
### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

It appears as thought uint8 addition is not supported.  This is odd.  When running the above code I get the error:

```
InvalidArgumentError: No OpKernel was registered to support Op 'Add' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  device='CPU'; T in [DT_STRING]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_INT64]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_INT32]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]

	 [[Node: add = Add[T=DT_UINT8](Const, Const_1)]]

```

**Comment by blake-varden** [comment]
The documentation, claims that uint8 addition is supported.
https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops/arithmetic_operators

**Comment by michaelisard** [comment]
@cwhipkey do you know why the docs and op registration differ?

**Comment by cwhipkey** [comment]
The documentation comes from the op registration in core/ops/math_ops.cc, which uses a macro.  It seems from the history that uint8 was added to the macro as part of enabling uint8 for Div.

The kernel registrations are in core/kernels/cwise_op_add_1.cc and core/kernels/cwise_op_add_2.cc (split into separate registrations across of the files to speed up compilation).  None of the REGISTER calls refer to uint8.
------
We can either fix the docs or add the missing registration.

**Comment by lakshayg** [comment]
Is someone working on this issue? If not then I would like to take this up and add the missing registration.

**Comment by cwhipkey** [comment]
No one is working on this currently as far as I know, so it would be great if you could take it!  Feel free to take it and add the missing registration (and update the test for the op(s) to include a test of the newly registered type).
