### ISSUE TITLE
Default CUDA / cuDNN version not used in template string

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#10456]
When leaving version for CUDA / cuDNN empty, to default to 8.0 / 6, they are not properly used in the template at marks **_blank_**

Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 8.0]:
Please specify the location where CUDA **_blank_** toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 6.0]:
Please specify the location where cuDNN **_blank_** library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:

Instead, there is just a two-space gap.
The script seems to miss a proper fallback for `TF_CUDA_VERSION` / `TF_CUDNN_VERSION` unset.

**Comment by martinwicke** [comment]
@yifeif can you fix this while rewriting configure?

**Comment by yifeif** [comment]
This was from #10307. I'll send a fix. cc @gunan FYI.

**Comment by Androbin** [comment]
@yifeif This doesn't seem resolved yet?

We probably should set defaults
```
# Set default CUDNN version if not set
if [ -z "$TF_CUDNN_VERSION" ]; then
  TF_CUDNN_VERSION="6"
  export TF_CUDNN_VERSION
fi
```

right after assigning them explicitly

```
# Configure the cuDNN version to use.
if [ -z "$TF_CUDNN_VERSION" ]; then
  read -p "Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 6.0]: " TF_CUDNN_VERSION
fi
```

The same applies to other variables as well.

**Comment by yifeif** [comment]
@Androbin thanks for the ping. It should be fixed now. Could you try the latest master?

**Comment by Androbin** [comment]
@yifeif Seems to work just fine now!
