### ISSUE TITLE
//tensorflow/core/kernels:sparse_matmul_op_test_gpu is failing on ppc64le with "Actual: false but Expected: true"

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#10459]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
   Ubuntu 16.04 (ppc64le)
- **TensorFlow installed from (source or binary)**:
    Installed from source (v1.0.1)
- **TensorFlow version (use command below)**:
    ('v1.0.1-0-ge895d5c-dirty', '1.0.1')
- **Bazel version (if compiling from source)**:
     0.4.4-2017-05-26 (@80a07b5)
- **CUDA/cuDNN version**:
     CUDA = 8.0 and cuDNN = 5.1
- **GPU model and memory**:
    GPU 0: Tesla P100-SXM2-16GB
    GPU 1: Tesla P100-SXM2-16GB
- **Exact command to reproduce**:
     bazel test --config=opt --config=cuda //tensorflow/core/kernels:sparse_matmul_op_test_gpu

### Describe the problem
This test is passing successfully on X86, however getting failure on ppc64le with following errors:

### Source code / logs
```
$  bazel test --config=opt --config=cuda //tensorflow/core/kernels:sparse_matmul_op_test_gpu

exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Running main() from test_main.cc
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from SparseMatmulOpTest
[ RUN      ] SparseMatmulOpTest.BroadcastPacketTest
[0.170094 0.170094 0.170094 0.170094] != [  0.170094    0.14922 -0.0823886   0.026985], differences: [         0 -0.0208738  -0.252482  -0.143109]
tensorflow/core/kernels/sparse_matmul_op_test.cc:257: Failure
Value of: areApprox(ref, data2, PacketSize)
  Actual: false
Expected: true
[  FAILED  ] SparseMatmulOpTest.BroadcastPacketTest (0 ms)
[ RUN      ] SparseMatmulOpTest.InterleavePacketTest
[       OK ] SparseMatmulOpTest.InterleavePacketTest (0 ms)
[ RUN      ] SparseMatmulOpTest.Bfloat16ExpandTest
[       OK ] SparseMatmulOpTest.Bfloat16ExpandTest (0 ms)
[ RUN      ] SparseMatmulOpTest.Bfloat16LoadTest
[       OK ] SparseMatmulOpTest.Bfloat16LoadTest (0 ms)
[----------] 4 tests from SparseMatmulOpTest (0 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (0 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SparseMatmulOpTest.BroadcastPacketTest

 1 FAILED TEST
```
I went through the file tensorflow/core/kernels/sparse_matmul_op_test.cc to find the root cause, but couldn't understand the code. Please provide your suggestions/comments on this.Thanks!

**Comment by michaelisard** [comment]
Marking community support since we don't directly support PPC builds.

**Comment by sandipmgiri** [comment]
Started looking into the issue starting from the file tensorflow/core/kernels/sparse_matmul_op_test.cc
As per initial analysis found that following code returning incorrect results on ppc64le https://github.com/tensorflow/tensorflow/blob/v1.0.1/tensorflow/core/kernels/sparse_matmul_op_test.cc#L255-L256 

```
TEST_F(SparseMatmulOpTest, BroadcastPacketTest) {
  for (int i = 0; i < PacketSize; ++i) ref[i] = data1[0];
  internal::pstoreu(data2, internal::pbroadcast_first<Packet>(
                              internal::ploadu<Packet>(data1)));
   ASSERT_TRUE(areApprox(ref, data2, PacketSize));

```

Here we are getting incorrect results for data2 array (`[  0.170094    0.14922 -0.0823886   0.026985]` VS expected `[0.170094 0.170094 0.170094 0.170094]`).
Currently I am investigating further on this. Please provide comments/suggestions if any. Thanks!

**Comment by sandipmgiri** [comment]
With a little more investigation I found the following things : 
 https://github.com/tensorflow/tensorflow/blob/v1.0.1/tensorflow/core/kernels/sparse_matmul_op_test.cc#L255-L256
```
 internal::pstoreu(data2, internal::pbroadcast_first<Packet>(
                              internal::ploadu<Packet>(data1)));
```

For `internal::pbroadcast_first<Packet>`  line, on both the platform executed different functions, see below -
 
On x86 executed  `EIGEN_STRONG_INLINE Packet4f pbroadcast_first<Packet4f>(const Packet4f& a)` function (https://github.com/tensorflow/tensorflow/blob/v1.0.1/tensorflow/core/kernels/sparse_matmul_op.h#L197)
And on ppc64le executed `EIGEN_DEVICE_FUNC inline Packet pbroadcast_first(const Packet& a)` function (https://github.com/tensorflow/tensorflow/blob/v1.0.1/tensorflow/core/kernels/sparse_matmul_op.h#L92)

That is why our test case is failing on ppc64le. Investigating this further, if could get any suggestions/pointers to why this may be happening that would be great!

**Comment by sandipmgiri** [comment]
To find the root cause , started comparing ppc64le and x86 results  :

For that started putting print statements in Eigen's broadcasting code and checking control of each and every function on both the platform, also printing return values and its data types.
As per initial analysis I found that  - we are getting different data type name for internal::ploadu<Packet>(data1) on the both the platform (see below):

std::cout << typeid(internal::ploadu<Packet>(data1)).name();

on ppc64le = U8__vectorf  and
on x86 = Dv4_f

This might be the reason of incorrect code flow on power; because this function return value passing as input to internal::pbroadcast_first<Packet> function.

**Comment by sandipmgiri** [comment]
Fixed in PR https://github.com/tensorflow/tensorflow/pull/12138
