### ISSUE TITLE
how to restore a tensor defined in a dictionary?

### ISSUE THREAD

**Issue by dengyuning** [tensorflow/tensorflow#10451]
I wrote the following definitions in my program.
`first_layer = {'w_1': tf.Variable(tf.truncated_normal([600, 300]), name='w_1'), 'b_1':tf.Variable(tf.truncated_normal([300]), name='b_1')}
`
And I use the following two lines to save my trained model.
`   saver = tf.train.Saver()
    saver.save(sess, os.path.join(model, 'model'))`
How can I restore the tensor with the name w_1 ?
The following codes didn't work out.
`  saver = tf.train.import_meta_graph(os.path.join(c_dir, 'model.meta'))
    sess.run(tf.global_variables_initializer())
    saver.restore(sess, tf.train.latest_checkpoint(c_dir))
   graph = tf.get_default_graph()
    w_1 = graph.get_tensor_by_name("w_1:0")`

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
