### ISSUE TITLE
tf.import_graph_def() does not return list of tensors or operations

### ISSUE THREAD

**Issue by abishgj-rzt** [tensorflow/tensorflow#10460]
I read the documentation for `tf.import_graph_def` [here](https://www.tensorflow.org/api_docs/python/tf/import_graph_def).

As the documentation says: 
Returns: A list of Operation and/or Tensor objects from the imported graph, corresponding to the names in return_elements.

I tried that with this sample code but the method returns `None` for me.

I had to run some tests using this feature. But stuck at this issue.

Sample code:

```python3
import tensorflow as tf
g = tf.Graph()
with g.as_default():
    c = tf.constant(30.0)
    b = tf.constant(20.0)
    a = tf.add(b, c)
gdef = g.as_graph_def()
print(tf.import_graph_def(gdef))```

**Comment by mrry** [comment]
The crucial part of the documentation is "corresponding to the names in `return_elements`." To get the function to return some operations or tensors, you must specify a list names of operations or tensors. If you don't specify `return_elements` when calling `tf.import_graph_def()`, the function will return `None`.

**Comment by abishgj-rzt** [comment]
Ok got it. Since it did not throw any exception for mandatory parameter, I thought it is optional.

Thanks :)

**Comment by mrry** [comment]
Perhaps the documentation is confusing here! It's definitely an optional parameter… if you don't pass `return_elements` then the import will still happen (as a side effect) but the function won't return anything.
