### ISSUE TITLE
Where are quantization dependencies?

### ISSUE THREAD

**Issue by fferroni** [tensorflow/tensorflow#10463]
In https://www.tensorflow.org/performance/quantization tutorial, there is //tensorflow/contrib/quantization and //tensorflow/contrib/quantization/kernels required to use a quantized graph.

I cannot find this in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/quantization 

Has the location been updated?

```
# Note: You need to add the dependencies of the quantization operation to the
#       cc_binary in the BUILD file of the label_image program:
#
#     //tensorflow/contrib/quantization:cc_ops
#     //tensorflow/contrib/quantization/kernels:quantized_ops

bazel build tensorflow/examples/label_image:label_image
bazel-bin/tensorflow/examples/label_image/label_image \
--image=<input-image> \
--graph=/tmp/quantized_graph.pb \
--labels=/tmp/imagenet_synset_to_human_label_map.txt \
--input_width=299 \
--input_height=299 \
--input_mean=128 \
--input_std=128 \
--input_layer="Mul:0" \
--output_layer="softmax:0"
```

**Comment by michaelisard** [comment]
The quantization ops all moved into core tensorflow so you shouldn't need a separate contrib dependency for those ops now. However, I can't vouch for what is needed to make that tutorial work. @petewarden  is anyone maintaining this tutorial?

**Comment by Androbin** [comment]
The tutorial references the outdated `quantize_graph` tool which is a bit buggy now.
This should be updated to make use of the new `transform_graph` tool.

**Comment by petewarden** [comment]
Thanks @androbin! I'll close this bug since that fixes the documentation.

**Comment by korrawat** [comment]
@petewarden So should the code comments about dependencies be removed as well?
```bash
# Note: You need to add the dependencies of the quantization operation to the
#       cc_binary in the BUILD file of the label_image program:
#
#     //tensorflow/contrib/quantization:cc_ops
#     //tensorflow/contrib/quantization/kernels:quantized_ops
```
