### ISSUE TITLE
Tensor names prepended with "import/" when loaded from protobuf

### ISSUE THREAD

**Issue by josauder** [tensorflow/tensorflow#10461]
When I load a (frozen) Tensorflow model from disk using:

```
    graph = tf.Graph()
    with graph.as_default():
        f = gfile.FastGFile("frozen_graph.pb", "rb")
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        tf.import_graph_def(graph_def)
```

It seems that all tensor names are prepended with `import/`.
This is the code I use to print the names:
```
with tf.Session(graph=graph) as sess:
        all_ops = sess.graph.get_operations()
        op_values =  [op.values() for op in all_ops]
        for values in op_values:
            for each in value:
                print each.name

```
Why? Is this some kind of default option that can be overriden? Or can I rely on this in my code? I could not find this documented anyhwere, can anybody point me to references regarding this?

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by apollo-time** [comment]
That is the default value specified in tf.import_graph_def.
You can pass in a name argument to use a different prefix.

https://stackoverflow.com/questions/44518790/are-tensor-names-always-prepended-with-import-when-loaded-from-protobuf
