### ISSUE TITLE
[TF:XLA] XLA does not recognize symbol Polly.

### ISSUE THREAD

**Issue by annanay25** [tensorflow/tensorflow#10471]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: ('v1.0.0-1783-g4c3bb1a', '1.0.0')
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: - 
- **GPU model and memory**: -
- **Exact command to reproduce**: -

### Problem description
I have written my custom build file to integrate Polly into XLA's LLVM build. I have included a dependency to ```@llvm//:polly``` in my [tensorflow/blob/master/tensorflow/compiler/xla/service/cpu/BUILD](https://gitlab.com/annanay25/tensorflow/blob/master/tensorflow/compiler/xla/service/cpu/BUILD#L294) file under the ```compiler_functor``` rule (Since this is the file with the LLVM PassManagerBuilder defined). 
I also added the header 
```
#include "external/llvm/tools/polly/include/polly/RegisterPasses.h"
```
in this file.
Somehow, this does not seem to be enough for XLA to recognize Polly. When I add - 

```
polly::registerPollyPasses(...)
```
to this file, it fails to compile with 
```
ERROR: Symbol polly was not declared here
```

I am unable to fix this (possibly linking) issue.

@hawkinsp - Could you please take a look at this?

Please refer to #10288 for more relevant information.

**Comment by michaelisard** [comment]
@hawkinsp please unassign if you don't have time to look into this.

**Comment by annanay25** [comment]
I got this working with   
```
::polly::registerPollyPasses(...)
```
