### ISSUE TITLE
TF 0.6.0 build fails with bazel 0.1.5

### ISSUE THREAD

**Issue by AlexJoz** [tensorflow/tensorflow#1047]
Try to build TF ver. 0.6  with Bazel 0.1.5, got this:

`ERROR: /tensorflow/WORKSPACE:70:1: new_git_repository rule //external:iron-ajax'
s name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:77:1: new_git_repository rule //external:iron-dropd
own's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:84:1: new_git_repository rule //external:accessibil
ity-developer-tools's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:91:1: new_git_repository rule //external:iron-doc-v
iewer's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:98:1: new_git_repository rule //external:iron-icons
's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:105:1: new_git_repository rule //external:paper-ico
n-button's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:119:1: new_git_repository rule //external:paper-dro
pdown-menu's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:126:1: new_git_repository rule //external:iron-flex
-layout's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:133:1: new_git_repository rule //external:iron-auto
grow-textarea's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:147:1: new_git_repository rule //external:iron-comp
onent-page's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:161:1: new_git_repository rule //external:paper-sty
les's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:168:1: new_git_repository rule //external:paper-inp
ut's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:175:1: new_git_repository rule //external:paper-ite
m's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:182:1: new_git_repository rule //external:marked-el
ement's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:196:1: new_git_repository rule //external:paper-pro
gress's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:203:1: new_git_repository rule //external:iron-chec
ked-element-behavior's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:210:1: new_git_repository rule //external:paper-too
lbar's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:224:1: new_git_repository rule //external:es6-promi
se's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:231:1: new_git_repository rule //external:promise-p
olyfill's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:238:1: new_git_repository rule //external:font-robo
to's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:245:1: new_git_repository rule //external:paper-men
u's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:252:1: new_git_repository rule //external:iron-icon
's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:259:1: new_git_repository rule //external:iron-meta
's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:273:1: new_git_repository rule //external:iron-resi
zable-behavior's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:280:1: new_git_repository rule //external:iron-fit-
behavior's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:287:1: new_git_repository rule //external:iron-over
lay-behavior's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:294:1: new_git_repository rule //external:neon-anim
ation's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:301:1: new_git_repository rule //external:iron-a11y
-keys-behavior's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:322:1: new_git_repository rule //external:iron-vali
datable-behavior's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:329:1: new_git_repository rule //external:sinon-cha
i's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:336:1: new_git_repository rule //external:paper-but
ton's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:343:1: new_git_repository rule //external:iron-inpu
t's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:350:1: new_git_repository rule //external:iron-menu
-behavior's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:357:1: new_git_repository rule //external:paper-sli
der's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:364:1: new_git_repository rule //external:iron-list
's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:378:1: new_git_repository rule //external:paper-mat
erial's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:385:1: new_git_repository rule //external:iron-rang
e-behavior's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:392:1: new_git_repository rule //external:svg-typew
riter's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:399:1: new_git_repository rule //external:web-anima
tions-js's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:413:1: new_git_repository rule //external:web-compo
nent-tester's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:420:1: new_git_repository rule //external:paper-tog
gle-button's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:427:1: new_git_repository rule //external:paper-beh
aviors's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:434:1: new_git_repository rule //external:paper-rad
io-group's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:441:1: new_git_repository rule //external:iron-sele
ctor's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:448:1: new_git_repository rule //external:iron-form
-element-behavior's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:469:1: new_git_repository rule //external:iron-beha
viors's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:483:1: new_git_repository rule //external:iron-coll
apse's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:490:1: new_git_repository rule //external:paper-che
ckbox's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:497:1: new_git_repository rule //external:paper-rad
io-button's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:504:1: new_git_repository rule //external:paper-hea
der-panel's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:511:1: new_git_repository rule //external:prism-ele
ment's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:525:1: new_git_repository rule //external:paper-men
u-button's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:539:1: new_git_repository rule //external:paper-rip
ple's name field must be a legal workspace name.
ERROR: /tensorflow/WORKSPACE:546:1: new_git_repository rule //external:iron-icon
set-svg's name field must be a legal workspace name.
ERROR: Error evaluating WORKSPACE file.
ERROR: no such package 'external': Package 'external' contains errors.
____Elapsed time: 2.171s`

I think should consider [this commit](https://github.com/bazelbuild/bazel/commit/d21c2d6653a3d9bc3376bcb190ba0ac31f52195b)

**Comment by vrv** [comment]
Yes, don't build TF with bazel 0.1.4+ before d21c2d6653a3d9bc3376bcb190ba0ac31f52195b :)

**Comment by vrv** [comment]
(I can't find the commit right now, but there was a commit a week or so ago that essentially broke backwards compat.)

**Comment by vrv** [comment]
This one: d6f732205870e87b495e1c01d7b79c6512339021

**Comment by AlexJoz** [comment]
aw, in Master.. ok =) thnx
