### ISSUE TITLE
Map function error: index cleared after previous read

### ISSUE THREAD

**Issue by james-ough** [tensorflow/tensorflow#10476]
I'm trying to efficiently calculate the Jacobian by using `tf.map_fn`.

```python
import tensorflow as tf

a = tf.constant([5., 3., 2.])
b = tf.square(a)

fn = lambda x: tf.gradients(x, a)[0]
out = tf.map_fn(fn, b)

with tf.Session() as sess:
    out_eval = sess.run(out)
    print(out_eval)
```

This throws a weird error:

```
InvalidArgumentError (see above for traceback): TensorArray map/TensorArray_1@map/while/gradients: Could not read index 0 twice because it was cleared after a previous read (perhaps try setting clear_after_read = false?).
```

How can I get this working? Thanks.

**Comment by michaelisard** [comment]
I'm sorry that error message is so unhelpful. There is a longish discussion in #675 about this issue, culminating in what I hope is a solution you can use. Closing for now but please reopen if #675 is not relevant to your issue.

**Comment by james-ough** [comment]
Hey Michael, thanks for your help. I've already tried the method suggested in [#675](https://github.com/tensorflow/tensorflow/issues/675), but it was too slow.

I'm hoping that a map function will be more efficient, but I haven't figured out how to get past the error.

**Comment by jjough** [comment]
So could you reopen, please?

**Comment by james-ough** [comment]
So could you reopen, please?

**Comment by cooijmanstim** [comment]
@james-ough The error has to do with differentiation inside dynamic loops; it doesn't seem to work if the differentiation crosses loop iteration boundaries. Consider that `x` in your lambda function is a tensor that, as far as Tensorflow can tell, is not connected to `a` in any way.

What you can do instead to make this work is call `tf.map_fn` on a sequence of indices, i.e. `tf.range(tf.shape(a)[0])`, and inside the lambda call `tf.gradients(b[i], a)`. Now both the tensor being differentiated (`b`) and the tensor being differentiated with respect to (`a`) are outside of the dynamic loop created by `tf.map_fn`, and the error should disappear.
