### ISSUE TITLE
Unable to install tensorflow-gpu==0.11.0

### ISSUE THREAD

**Issue by arunpatro** [tensorflow/tensorflow#10485]
I am having issues with installing the v0.11.0 version of tensorflow-gpu. My code works on `tensorflow==0.11.0` but really slow. I had a `tensorflow-gpu==0.11.0` but i had lost it due to an upgrade. The pip repository doesn't have a v0.11 anymore and starts with v0.12 only. I got the v0.11 wheel from the TF_BINARY_URLs for v0.11. I am able to install `tensorflow==0.11.0` using the wheel at `export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl`

but I am unable to install the GPU version of `tensorflow-gpu==0.11.0` using the corresponding link at export `TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl`

The link looks same to me with just the folder different from `gpu/` and `cpu/`. Upon using the link for GPU, it installs `tensorflow==0.11.0` and not `tensorflow-gpu=0.11.0`. Where can I find a `tensorflow-gpu==0.11.0` wheel?

**Comment by gunan** [comment]
When we released 0.11, our GPU pip packages were not names `tensorflow-gpu`, it was just tensorflow.
The link you have will get you the tensorflow pip package with GPU support.
