### ISSUE TITLE
How to reduce the package size?

### ISSUE THREAD

**Issue by StarRain-L** [tensorflow/tensorflow#10483]
Even if I only use arm64 size is 98.2 M, how to reduce the size?Please answer
![snip20170607_1](https://user-images.githubusercontent.com/8908244/26865045-7de7b23a-4b8d-11e7-9503-6f07943645a8.png)

**Comment by jubjamie** [comment]
_Warning: As this doesn't appear to be a bug with Tensorflow, the devs may ask for this to be moved to Stack Ovefrlow._

It looks like you're using iOS. Have you tried reading through [these instructions](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/ios_examples#reducing-the-binary-size) to reduce the binary size? The idea is that you manually remove the kernels you are not using to reduce the size. This may help you.

**Comment by StarRain-L** [comment]
Thank you for your reply, I according to some of the size of the official document, just libtensorflow - the size of the core cannot be reduced, if support arvmc7 and arm64, release AppStore after increasing the size of the probably how much?

**Comment by jubjamie** [comment]
I'm awfully sorry but i'm struggling to understand your reply. I don't think I can help you much more than pointing you to that documentation. It states that each binary should be around 11Mb so perhaps there is a problem with your binary compilation method. As I don't have experience with Tensorflow on iOS then i'm not sure whether you've come across a bug or not. Hopefully someone more qualified can come and help you. I know when I had issues with Android sometimes just starting fresh and running through the docs again sometimes helped. Good luck!

**Comment by StarRain-L** [comment]
I'm sorry I can't express clearly in English, but thank you very much for your reply!"Libtensorflow - core. a"
![767ce499-260e-4951-84c3-c043b14d95c6](https://user-images.githubusercontent.com/8908244/26875754-dbd0a3ac-4bb5-11e7-94c8-27bea6a0ac84.png)
 is given by the official, and I'm not sure if it will  cause package very big, let me very worried

**Comment by michaelisard** [comment]
@petewarden is this expected?

**Comment by petewarden** [comment]
The intermediate sizes of the library files on disk don't reflect the size that's added to the binary. The only impact of this file size is on your local drive, it shouldn't affect the size of the application package.

**Comment by StarRain-L** [comment]
Thank you for your reply.
The libtensorflow-core.a lib will be linded to my app which will Increase the package size ,so I want to reduce it.   how can I  modify makefile to remove files that I dont need .
![snip20170611_1](https://user-images.githubusercontent.com/8908244/27010878-957f0536-4ee1-11e7-8bdb-3eb9eb4e8d85.png)

**Comment by jubjamie** [comment]
What Pete is saying is that once your app is built it should compress. It's similar with the android app when you quantise. It shows as full size but once built in it compresses. Try putting it the app and then analysing for size to see if it's compressed as @petewarden suggested.

**Comment by StarRain-L** [comment]
Thank you for your reply. What do you mean don't need to change the"makefile",  the binary file that upload  to apple store  will be compressed ?

**Comment by StarRain-L** [comment]
Thank you for your reply. I tried, as you said,the package  is compressed,  an'd  the size of the ibrary files can accept, thank you very much for your answer!!!!!!

**Comment by jubjamie** [comment]
You're welcome. But thank @petewarden for his helpful comment that I totally forgot! Embarrassing as I only went through a similar phase of my project not too recently. If this is solved please close the issue. Good luck with your project!

**Comment by StarRain-L** [comment]
Thank @petewarden , also  thank you. can close this issue now!!

**Comment by jakiechris** [comment]
facing the same issue , is any one would tell me how to reduce size ?
 the doc only said that config tf_op_files.txt .. 

1. need we also config other files such as  tf_pb_text_files.txt ,  proto_text_cc_files.txt  ... for reducing?
2. is there any other thinking for reducing than configuring the txt files Exhaustive Attackly ?

**Comment by jubjamie** [comment]
@jakiechris are your library sizes not reduced once you compile or analyse your app? They appear bigger than on disk as @petewarden noted.

**Comment by jakiechris** [comment]
@jubjamie you are right, final app increased in smaller size.
   
and i compeleted the reduce work several months before, only cut tf_op_files.txt is enough.

here's my reduce for android:
[tf_op_files.txt](https://github.com/tensorflow/tensorflow/files/1255296/tf_op_files.txt)

**Comment by Kika-Xumengwei** [comment]
Hi @jubjamie @petewarden really appreciate your insights as I was also disturbed by the fact that the lib generated for Android is so large (more than 100MB). I am curiously what is the logic behind it? Why after compiled in Android Studio the lib size can be compressed so much? I think when I use selective registration I have already omit unnecessary ops?
