### ISSUE TITLE
incorrect documentation in _SliceHelper

### ISSUE THREAD

**Issue by edgimar** [tensorflow/tensorflow#10494]
The outputs shown for several of the examples in the `_SliceHelper` docstring are incorrect (based on some previous examples?).

See, for example, this line: https://github.com/tensorflow/tensorflow/blob/359d6f9716c0bb9bd8201ce600da98b0481a8049/tensorflow/python/ops/array_ops.py#L412

**Comment by Androbin** [comment]
The first two section seem correct. The last two seem two be based on the output of the second example.
