### ISSUE TITLE
Typo in text

### ISSUE THREAD

**Issue by arianaa30** [tensorflow/tensorflow#10493]
Typo at this address: https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/Graph
I thought it primes in our mind that TensorFlow for Java is not yet mature. Fixing it might help new comers!

WARNING: Resources consumed by the Graph object **msut** be explicitly freed by invoking the close() method then the Graph object is no longer needed.

**Comment by josephholsten** [comment]
resolved in https://github.com/tensorflow/tensorflow/pull/9852, do we need to wait for a new release for the doc to be regenerated?

**Comment by martinwicke** [comment]
The API docs point to the latest stable release. Fixes to the API docs are reflected the next time that docset is published, or for the default one, whenever the stable version switches. 

To change this, we'd have to backport the fix to 1.1, and redeploy the 1.1 docs. 

@wolffg FYI -- I know of no plans to redeploy old docs regularly.

**Comment by michaelisard** [comment]
Unfortunately it looks as if this didn't make the 1.2 docs, but it will be fixed in 1.3.
