### ISSUE TITLE
Read images with various sizes from TFRecord

### ISSUE THREAD

**Issue by hgffly** [tensorflow/tensorflow#10492]
I posted this issue in [StackOverflow](https://stackoverflow.com/questions/44152661/random-crop-a-patch-from-a-various-sized-image-read-in-tfrecord) and I got a response as well. However the replied answer would raise a **ValueError: All shapes must be fully defined** .
I'm just wondering might it be a limitation or even a bug that it's impossible to read images with various sizes from TFRecord?

**Comment by michaelisard** [comment]
I think stackoverflow looks like the right discussion going on here, since there seem to be some workarounds proposed for you and no indication of a bug in TensorFlow so far.

**Comment by baodingge** [comment]
def distorted_inputs(filenames, batch_size, imagesize, img_channel):

	filename_queue = tf.train.string_input_producer(filenames)
	reader = tf.TFRecordReader()
	_, serialized_example = reader.read(filename_queue)

	features = tf.parse_single_example(serialized_example, features={
				'abs_path': tf.FixedLenFeature([], tf.string),
				'height':tf.FixedLenFeature([], tf.int64),
				'width' :tf.FixedLenFeature([], tf.int64),
				'img_raw':tf.FixedLenFeature([], tf.string),
				'label':tf.FixedLenFeature([], tf.int64)})
	height = tf.cast(features['height'], tf.int32)
	width = tf.cast(features['width'], tf.int32)
	images = tf.decode_raw(features['img_raw'], tf.float32)
	images = tf.reshape(images, [height, width, img_channel])
	
	distorted_image = tf.random_crop(images, [530, 530, img_channel])
	distorted_image = tf.image.random_flip_left_right(distorted_image)
	distorted_image = tf.image.random_brightness(distorted_image, max_delta=63)
	distorted_image = tf.image.random_contrast(distorted_image, lower=0.2, upper=1.8)
	distorted_image = tf.image.resize_images(distorted_image, (imagesize,imagesize))
	float_image = tf.image.per_image_standardization(distorted_image)
	
	label = tf.cast(features['label'], tf.int64)
	label = tf.reshape(label, [1])
	min_after_dequeue = 1000
	capacity = min_after_dequeue + 3*batch_size
	return tf.train.shuffle_batch(
			[float_image, label],
			batch_size = batch_size,
			capacity = capacity,
			min_after_dequeue = min_after_dequeue)

I alse meet this problem a month ago, I test my code line by line, this is code can works well.
The core problem is this : images = tf.reshape(images, [height, width, img_channel]).I think this can help you.Any question call me.

**Comment by hgffly** [comment]
baodingge, thanks for response so much.
After reading and trying your codes, I just found what's the problem with my codes, 
My modified codes are listed as below:

    def read_and_decode(filename, img_size=-1, distorted=True, get_float_img=True):

    filename_queue = tf.train.string_input_producer([filename])  # specifying parameter "num_epochs" would raised an error, which I don't know how to resolve yet

    reader = tf.TFRecordReader()

    _, serialized_example = reader.read(filename_queue)

    features = tf.parse_single_example(serialized_example,
                                       features={
                                           'img_h': tf.FixedLenFeature([], tf.int64),
                                           'img_w': tf.FixedLenFeature([], tf.int64),
                                           'img_lbl': tf.FixedLenFeature([], tf.int64),
                                           'img_raw': tf.FixedLenFeature([], tf.string)
                                       })

    img_h = tf.cast(features['img_h'], tf.int32)
    img_w = tf.cast(features['img_w'], tf.int32)
    img = tf.decode_raw(features['img_raw'], tf.uint8)

    img = tf.reshape(img, [img_h, img_w, 3])  # reshape to a 2-D image
    label = tf.cast(features['img_lbl'], tf.int32)

    img = tf.random_crop(img, [20, 20, 3])  <==  After reshaping the tensor, I need to add this line to get images with specific size

    return img, label

Thanks so much!!!

**Comment by baodingge** [comment]
# specifying parameter "num_epochs" would raised an error, which I don't know how to resolve yet
this question is not so difficult, I know the answer is quite.when you use num_epoch explicitly, string_input_producer will creat a variable. So you have to use tf.local_variables_initializer() alone.
Or use init_op = tf.group(tf.global_variables_initializer(), tf.local_variables_initializer()).
this may be the answer.
