### ISSUE TITLE
I update libprotobuf but tendoflow still use the old version

### ISSUE THREAD

**Issue by noldmess** [tensorflow/tensorflow#10523]
i update libprotobuf 

>    ldconfig -p
>         libprotobuf.so.13 (libc6,x86-64) => /usr/local/lib/libprotobuf.so.13
>         libprotobuf.so.10 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libprotobuf.so.10
>         libprotobuf.so (libc6,x86-64) => /usr/local/lib/libprotobuf.so
>         libprotobuf-lite.so.13 (libc6,x86-64) => /usr/local/lib/libprotobuf-lite.so.13
>         libprotobuf-lite.so.10 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.10
>         libprotobuf-lite.so (libc6,x86-64) => /usr/local/lib/libprotobuf-lite.so

and it worked 
     

>   protoc --version
>           libprotoc 3.3.0

but tensorflow still use uses the 3.0.0. version

> 
>   [libprotobuf FATAL google/protobuf/stubs/common.cc:67] This program requires version 3.3.0 of the   Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
 terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.3.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)

can someone help me

**Comment by martinwicke** [comment]
Please fill out the template -- with only the information given it is very hard to help you.

It may be that your version of TF is linked against 3.0.0 and remembers this.
