### ISSUE TITLE
source build fails: cannot find python bin due to empty environment

### ISSUE THREAD

**Issue by ribx** [tensorflow/tensorflow#10529]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Gentoo Linux
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master (commit 02dbe153afe2c7f418fcf9044e2e3a8795a21d3a)
- **Bazel version (if compiling from source)**:  0.4.5
- **CUDA/cuDNN version**: No CUDA
- **GPU model and memory**: No CUDA
- **Exact command to reproduce**: `./configure && bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

### Environment
```== cat /etc/issue ===============================================
Linux mace 4.8.17-hardened-r2 #2 SMP Thu Jun 1 15:39:15 CEST 2017 x86_64 Intel(R) Xeon(R) CPU E5-2407 v2 @ 2.40GHz GenuineIntel GNU/Linux

== are we in docker =============================================
No

== compiler =====================================================
c++ (Gentoo Hardened 4.9.4 p1.0, pie-0.6.4) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


== uname -a =====================================================
Linux mace 4.8.17-hardened-r2 #2 SMP Thu Jun 1 15:39:15 CEST 2017 x86_64 Intel(R) Xeon(R) CPU E5-2407 v2 @ 2.40GHz GenuineIntel GNU/Linux

== check pips ===================================================
numpy (1.13.0)

== check for virtualenv =========================================
True

== tensorflow import ============================================
Traceback (most recent call last):
  File "/root/src/tensorflow_src/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
ImportError: No module named 'tensorflow.python.pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/src/tensorflow_src/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/root/src/tensorflow_src/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/root/src/tensorflow_src/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/root/src/tensorflow_src/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
ImportError: No module named 'tensorflow.python.pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================

== cuda libs  ===================================================
```

### Describe the problem

I configured the source code (with MKL, no CUDA, nothing else enabled) and the bazel build fails 120s with
```ERROR: /root/src/tensorflow_src/tensorflow/tensorboard/components/vz_sorting/BUILD:8:1: Compiling 4 TypeScript files //tensorflow/tensorboard/components/vz_sorting:vz_sorting failed: execrooter failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/07ee3a30c05d85d959138fae6c764ebf/execroot/tensorflow_src && \
  exec env - \
  bazel-out/host/bin/tensorflow/tensorboard/scripts/execrooter bazel-out/local-py3-opt/bin/tensorflow/tensorboard/components/vz_sorting/vz_sorting-tsc-execroot.json): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127.
python: unable to find executable in PATH.
```

While the command runs ok, when I omit running inside a clean environment `env -`. I am running inside a virtualenv. But also without a virtual env I am running into this problem:

```$ which python
/usr/bin/python
$ env - which python 
which: no python in ((null))
```

**Comment by martinwicke** [comment]
From the `env` man page: 

    The env utility uses the PATH environment variable to locate the
    requested utility if the name contains no `/' characters, unless the -P
    option has been specified.

So it appears your PATH is empty, or python is not in the path, but is instead an alias set in your shell.

Either way, this doesn't appear to be a problem with TensorFlow itself. I'll close this issue. Please comment to reopen if you have new information that suggests there is a bug in TensorFlow.

**Comment by ribx** [comment]
Yes, my path is empty (I thought that is the purpose of "env -"). Python is install into `/usr/bin/python`. Never the less, I don't want to build with my systems default python binary, but with the one inside my virtualenv. This is not possible, if the environment is cleared before (with `env -`).

Why is it even cleared?

**Comment by byronyi** [comment]
If you are in a `virtualenv` when building, then it's tied to that `virtualenv`. I don't think there's any need to do `env -` either way.

**Comment by ribx** [comment]
To the real question: which component creates this command and why? It looks like some javascript/typescript stuff. I cannot find it in the code, so it may be some third party problem.

**Comment by ribx** [comment]
To the real question: which component creates this command and why? It looks like some javascript/typescript stuff. I cannot find it in the code, so it may be some third party problem.

**Comment by martinwicke** [comment]
The command is generated by bazel. It tries to make the build hermetic, and it should use the python binary that you gave it when you configured TensorFlow.

**Comment by ribx** [comment]
my workaround is to replace the env binary with
```bash
#!/bin/bash

[[ "$1" == "-" ]] && shift

exec $@
```

quite a bit ugly, but works for now. I still think, this should be reopened and investigated. Btw I have this problem on all my Gentoo systems.

**Comment by martinwicke** [comment]
@damienmg I don't know why the right python isn't used in @ribx's case, but the env workaround is clearly not in the spirit of bazel. Is this an error in how TF does python config? Or is it a bug in bazel's treatment of python?

**Comment by ribx** [comment]
It looks like the whole generated command is wrong:

the last line:
```
bazel-out/host/bin/tensorflow/tensorboard/scripts/execrooter bazel-out/local-py3-opt/bin/tensorflow/tensorboard/components/vz_sorting/vz_sorting-tsc-execroot.json
```
tries to execute the json file. The "execrooter" script is a python script that tries to rebuild the environment and then execute the first commandline argument, which is in this case a json script.

I forgot to mention that everything worked fine with the version I compiled 2 weeks ago.

I will clean my env reclone the git repo and try again.

**Comment by ribx** [comment]
Just as a note: everything works fine when I compile outside my virtualenv.
