### ISSUE TITLE
Quantized inception-resnet-v2 doesn't predict the images correctly

### ISSUE THREAD

**Issue by rajnamitha** [tensorflow/tensorflow#10532]
I did quantization on inception-resnet-v2 model using https://www.tensorflow.org/performance/quantization#how_can_you_quantize_your_models. Size of freezed graph(input for quantization) is 224,6 MB and quantized graph is 58,6 MB. I ran some tests for quantized graph and the predicted output is totally wrong. I ran accuracy test for certain dataset wherein, for freezed graph the accuracy is 97.4% whereas for quantized graph it is 0%.

Is there a different way to quantize the model for inception-resnet versions? or, for inception-resnet model, quantization is not support at all?

**Comment by kwotsin** [comment]
I met with a similar problem like this. Try using `graph_transform` instead of `quantize_graph`
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms

Be sure to use `quantize_weights` and `quantize_nodes` successively in the command for graph transform.

**Comment by rajnamitha** [comment]
@kwotsin : With this I understand I need to use command like this? Eight-bit Calculations - https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms#eight-bit-calculations
Isn't it?

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
