### ISSUE TITLE
tf.layers: Add weights, biases and activations to the respective collections

### ISSUE THREAD

**Issue by thertweck** [tensorflow/tensorflow#10537]
For generating weight, bias and activation summaries one needs to have access to these tensors. Similar to how regularization losses are added to the GraphKeys.REGULARIZATION_LOSSES collection, it would make sense to add weights, biases and activations to the collections GraphKeys.WEIGHTS, GraphKeys.BIASES and GraphKeys.ACTIVATIONS. Right now, layers only add the weights and bias tensors to GraphKeys.TRAINABLE_VARIABLES. 

The summarization of the these collections is already supported [here](https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/contrib/layers/python/layers/summaries.py).

**Comment by fchollet** [comment]
I believe the pattern of "one global collection for everything" has been abandoned some time ago, in favor of fewer collections, and generally a move aways from global objects and towards "layers as objects", with kernels/biases/activations being attributes of these objects.

You can retrieve weights and biases from `TRAINABLE_VARIABLES` (they have different names indicating whether they are kernels or biases). To store activations when using functional layers, you should maintain your own dictionary of activations.
