### ISSUE TITLE
incorrect documentation for deep_cnn tutorial

### ISSUE THREAD

**Issue by gliboc** [tensorflow/tensorflow#10545]
### System information
not relevant to issue

### Describe the problem
The addresses provided for seeing the code in the "Code Organization" chapter of this tutorial https://www.tensorflow.org/tutorials/deep_cnn are no longer valid. 

I think the right place could be https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10

### Source code / logs
Address of the tutorial: https://www.tensorflow.org/tutorials/deep_cnn
One the addresses provided for the code: https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow_models/tutorials/image/cifar10/

**Comment by dr4b** [comment]
Hey, we have fixed this, but it won't show up in root until Tensorflow 1.2 becomes the default.

Check it out though: https://www.tensorflow.org/versions/r1.2/tutorials/deep_cnn#code_organization
