### ISSUE TITLE
BAZEL_BUILD_ONLY_CMD appears unused

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#10548]
In the bash script [`tensorflow/tools/ci_build/ci_parameterized_build.sh`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/ci_parameterized_build.sh) the variable `BAZEL_BUILD_ONLY_CMD` declared in [line 129](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/ci_parameterized_build.sh#L129) appears to be unused.

Variables not used for anything are often associated with bugs.
Could someone take a look at this?

**Comment by gunan** [comment]
This script is for our Internal CI use only.
Users should never need this script.

But we are slowly moving away from it, too.
Ill let @av8ramit evaluate whether it is worth fixing the script, or waiting for it to be deleted completely.

**Comment by Androbin** [comment]
I'll just drop the complete list here:

In ./tensorflow/tools/dist_test/scripts/dist_census_widendeep_test.sh line 37:
TIMEOUT=120  # Timeout for MNIST replica sessions

In ./tensorflow/tools/dist_test/scripts/dist_census_widendeep_test.sh line 60:
    SYNC_REPLICAS="1"

In ./tensorflow/tools/dist_test/scripts/dist_mnist_test.sh line 151:
  PS=($PS_HOSTS)

In ./tensorflow/tools/dist_test/local_test.sh line 66:
LOCAL_K8S_CACHE=${HOME}/kubernetes

In ./tensorflow/tools/dist_test/local_test.sh line 94:
    MODEL_NAME_FLAG="--model_name ${MODEL_NAME}"

In ./tensorflow/tools/ci_build/windows/bazel/bazel_test_lib.sh line 97:
exclude_gpu_cc_tests="${extra_failing_gpu_cc_tests} + ${exclude_cpu_cc_tests}"

In ./tensorflow/tools/ci_build/builds/integration_tests.sh line 42:
TIMEOUT=1800

In ./tensorflow/tools/ci_build/builds/run_pip_tests.sh line 100:
  PYTHON_BIN_PATH="$(which python)"

In ./tensorflow/tools/ci_build/builds/run_pip_tests.sh line 116:
    PAR_TEST_JOBS=$TF_GPU_COUNT

In ./tensorflow/tools/ci_build/builds/builds_common.sh line 134:
  TEST_BLACKLIST_SR=$3

In ./tensorflow/tools/ci_build/builds/builds_common.sh line 199:
    for TEST_NAME in ${FAILED_TESTS}; do

In ./tensorflow/tools/ci_build/builds/test_tutorials.sh line 46:
TIMEOUT=1800

In ./tensorflow/tools/ci_build/builds/libtensorflow.sh line 54:
  BAZEL="bazel --bazelrc ./tensorflow/tools/ci_build/install/.bazelrc"

In ./tensorflow/tools/ci_build/ci_parameterized_build.sh line 129:
BAZEL_BUILD_ONLY_CMD="bazel build"

In ./tensorflow/contrib/makefile/compile_ios_protobuf.sh line 39:
IPHONEOS_PLATFORM=`xcrun --sdk iphoneos --show-sdk-platform-path`

In ./tensorflow/contrib/makefile/compile_ios_protobuf.sh line 41:
IPHONESIMULATOR_PLATFORM=`xcrun --sdk iphonesimulator --show-sdk-platform-path`

In ./tensorflow/contrib/makefile/samples/build_and_run_inception_hexagon.sh line 229:
    for i in $(seq 1 "${TEST_COUNT}"); do

In ./tools/tf_env_collect.sh line 26:
uname=`uname -s`

**Comment by av8ramit** [comment]
Thank you @Androbin for bringing this to our attention. We have plans to migrate away from ci_parameterized_build.sh, so issues with that file should be resolved. As for the complete list, I think those variables are fine for now, but in the event you notice a breakage please feel free to file a PR with a fix.
