### ISSUE TITLE
MODEL_NAME_FLAG appears unused

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#10559]
In the bash script [`tensorflow/tools/dist_test/local_test.sh`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/local_test.sh) the variable `MODEL_NAME_FLAG` declared in [line 94](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/local_test.sh#L94) appears to be unused.

Variables not used for anything are often associated with bugs.
Could someone take a look at this?

**Comment by gunan** [comment]
@caisq could you take a look?
