### ISSUE TITLE
LOCAL_K8S_CACHE appears unused

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#10558]
In the bash script [`tensorflow/tools/dist_test/local_test.sh`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/local_test.sh) the variable `LOCAL_K8S_CACHE` declared in [line 66](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/local_test.sh#L66) appears to be unused.

Variables not used for anything are often associated with bugs.
Could someone take a look at this?

**Comment by gunan** [comment]
@caisq could you take a look?
