### ISSUE TITLE
Optimized build across different architecture

### ISSUE THREAD

**Issue by jrabary** [tensorflow/tensorflow#1056]
I built a pip package with  ̀-c opt` in one machine and use the same package on another machine. They don't have different version of core i7 processor. With the second machine, Tensorflow runs 10x slower than with the first. Could it be a compilation optimization problem ?

**Comment by martinwicke** [comment]
It could be any number of things -- different amount/type of memory, onboard graphics card competing, different BLAS libraries... We'd need a lot more information to diagnose this. If those were the same computer with the same OS installed, it may be mysterious.

**Comment by girving** [comment]
Closed for now due to lack of activity.  Feel free to reopen if more information is available.
