### ISSUE TITLE
OOM error after some number of steps ( Inputsize remains constant)

### ISSUE THREAD

**Issue by ujjwal-researcher** [tensorflow/tensorflow#10576]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Custom Code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux version 3.10.0-229.11.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) )
- **TensorFlow installed from (source or binary)**:
Installed from sources

- **TensorFlow version (use command below)**:
'v1.1.0-rc2-1003-g3792dd9' 1.1.0-rc2
- **Bazel version (if compiling from source)**:
0.4.5
- **CUDA/cuDNN version**:
  CUDA 8.0
: CuDNN 5.1
- **GPU model and memory**:
: NVidia GTX 1080 (Pascal)

### Describe the problem
While running training on a six layer CNN on 2 GPUs, the training starts fine, but after about 450 iterations, the OOM error comes up. During the whole time, the input size remains the same `[2, 221, 221, 3]` . I am unable to find any anomaly in the tensorboard or in my data.  Complete output and error log below

### Source code / logs
attached with the post

[stderr.txt](https://github.com/tensorflow/tensorflow/files/1062484/stderr.txt)
[stdout.txt](https://github.com/tensorflow/tensorflow/files/1062485/stdout.txt)

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
