### ISSUE TITLE
Simplify getting variable by name

### ISSUE THREAD

**Issue by wielandbrendel** [tensorflow/tensorflow#10588]
Suppose we created a variable `foo/v`
```
with tf.variable_scope("foo"):
    v = tf.get_variable("v", [1])
```
To get this variable from its name one currently needs to write two lines:
```
with tf.variable_scope("foo", reuse=True):
    v1 = tf.get_variable("v")
```
Instead, it would be much more intuitive to just write:
```
v1 = tf.get_variable("foo/v", reuse=True)
```

**Comment by Androbin** [comment]
You can do `v = sess.graph.get_tensor_by_name("foo/v:0")`

**Comment by wielandbrendel** [comment]
@Androbin : that's an interesting option I wasn't aware about! But it might still make sense to simplify the standard tf.get_variable call as suggested above.

**Comment by Androbin** [comment]
It should be possible to split the name and then place the scope as a hack.
I'll try to submit a PR to do so.

**Comment by Androbin** [comment]
Seems like `tf.get_variable` should already do that:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/variable_scope.py#L1069

**Comment by Androbin** [comment]
@wielandbrendel Can you confirm that `tf.get_variable` accepts this `name` layout?

**Comment by wielandbrendel** [comment]
@Androbin : Sorry, but could you explain in more detail?

**Comment by Androbin** [comment]
The documentation suggests that at least one of these should work:
`v = tf.get_variable("foo/v")`
`v = tf.get_variable("foo/v:0")`

**Comment by wielandbrendel** [comment]
```
with tf.variable_scope("foo"):
    v = tf.get_variable("v", [1])
    
v1 = tf.get_variable("foo/v")
```
throws a ValueError
```
ValueError: Variable foo/v already exists, disallowed. 
Did you mean to set reuse=True in VarScope? 
```

**Comment by girving** [comment]
@wielandbrendel `get_variable` doesn't return old variables unless `reuse=True` in order to prevent subtle bugs.  It seems like the behavior you want is already available either via `reuse=True` or `sess.graph.get_tensor_by_name`.

**Comment by jacksonloper** [comment]
Get tensor by name gets a tensor, not a variable object.  It would be nice to add a reuse keyword to tf.get_variable so we could grab variables directly.
