### ISSUE TITLE
TensorFlow is failing on ci.bazel.io with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [tensorflow/tensorflow#10587]
http://ci.bazel.io/job/TensorFlow/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/870/console

```
==== bazel version ====
...........
Build label: 
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jun 8 20:25:30 2017 (1496953530)
Build timestamp: 1496953530
Build timestamp as int: 1496953530


+ ./tensorflow/tools/ci_build/builds/configured CPU
~/workspace/TensorFlow/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64 ~/workspace/TensorFlow/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64
You have bazel  installed.
Please upgrade your bazel installation to version 0.4.5 or higher to build TensorFlow!
Exiting...
```
The reason is Bazel@HEAD doesn't generate a version number, the new way of version check introduced in 88d648f3beedfa6123efabb756be372f69382983 fails.

Maybe skip the check if the version number is empty? Because this also means users cannot use their custom bazel to build TF unless they add `--embed_label ${version_number}` as a build option.

**Comment by girving** [comment]
@martinwicke Can you take a look?

**Comment by gunan** [comment]
I am OK with having the version check succeed if the version string returned is empty

**Comment by martinwicke** [comment]
Agreed. @meteorcloudy do you want to fix the configure script, or @yifeif are you going to do it as part of pythonification?

**Comment by yifeif** [comment]
yea, but will send a fix for this now to unblock.

**Comment by meteorcloudy** [comment]
Thanks for the fix!
