### ISSUE TITLE
Pretrain NLP embeddings

### ISSUE THREAD

**Issue by Scitator** [tensorflow/tensorflow#10599]
I found a lot of pretrain CNN models in `tf.contrib.keras.applications`. Nevertheless, for NLP researchers there is no even well-know GoogleNews word2vec vectors or Glove, or...something. 

Is it possible to add functionality for simplified embedding download and future usage? Some official `maybe_download_google_news_w2v` or something like that.

**Comment by girving** [comment]
This is outside the scope of TensorFlow Github issues, which are about bugs or feature requests to the core library.
