### ISSUE TITLE
Saving embeddings or output evaluations in parallel to training

### ISSUE THREAD

**Issue by prannayk** [tensorflow/tensorflow#10590]
Feature request to create an async embedding saving buffer, which runs on the processor while the code trains on a GPU

The aim would be make sure that training is not affected by saving the model. That anyway takes a single thread, therefore it is a process that is done using an async buffer, it could optimize the training of models.
------------------------

### System information
- Linux Ubuntu 16.04:
- Installed from source with GPU implementation:
- 1.0.1:
- CUDA, cuDNN : 7.5
- GPU: Nividia Titan X

There was a **57x** slowdown to in line saving.

**Comment by girving** [comment]
You should be able to just spawn your own thread and run a saver op there.  I don't think this needs any TensorFlow changes, since multiple `session.run` calls already execute concurrently.
