### ISSUE TITLE
TensorBoard:  enable text-selection (for copy/paste) of tf.summary.text items

### ISSUE THREAD

**Issue by edgimar** [tensorflow/tensorflow#10602]
The way tensorboard is currently implemented seems to prevent one from selecting (in a web browser) the text of tf.summary.text summaries.  It would be nice if it were possible to copy/paste such text.

**Comment by girving** [comment]
@dandelionmane Do you know what the problem might be?

**Comment by wchargin** [comment]
This is easy to fix; there's a `user-select: none` that should be overridden by the text dashboard.

I've migrated this to https://github.com/tensorflow/tensorboard/issues/33, and should be able to fix it soon. :-)
