### ISSUE TITLE
[feature] Support S3 Filesystem for Tensorflow

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#10616]
At the moment Tensorflow supports distributed file system implementations such as HDFS or GCS which has been very useful for handling cases in a distributed environment. Both of them utilize Tensorflow's FileSystem C++ interface.

In case Tensorflow is used in AWS, it would be great to have a S3 Filesystem for Tensorflow as well.

We have a preliminary implementation of S3 Filesystem on Tensorflow, based on AWS's C++ SDK:
https://github.com/tensorflow/tensorflow/compare/master...yongtang:s3

The code is placed under the directory of tensorflow/contrib/s3.

As AWS is widely used, I am just wondering if it make sense to have a pull request to add S3 File system on Tensorflow?

It will be better to have feedback from community so that we could improve our implementation and help those deploying Tensorflow on AWS.

**Comment by aselle** [comment]
@jhseu, it would be great if you could comment on this and provide guidance. @yongtang prepared a patch linked above.

**Comment by jhseu** [comment]
@yongtang Yes, please make a pull request with your changes! This would be a very useful feature for a lot of people.

**Comment by yongtang** [comment]
Closed through #11089
