### ISSUE TITLE
[1.2.0 rc2] Tensorboard does not show graph on Windows 10

### ISSUE THREAD

**Issue by Netzeband** [tensorflow/tensorflow#10611]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:

I used the following minimal example:
```python
import tensorflow as tf
a = tf.constant(5)
b = tf.constant(4)
c = a+b
with tf.Session() as sess:
  Writer = tf.summary.FileWriter("Test", sess.graph)
  Writer.close()
```

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: 

I installed the wheel: https://ci.tensorflow.org/job/tf-master-win-gpu-cmake/lastSuccessfulBuild/artifact/cmake_build/tf_python/dist/tensorflow_gpu-1.2.0rc2-cp35-cp35m-win_amd64.whl
Which is the build "694" on Jenkins of the job "tf-master-win-gpu-cmake"

On version 1.1 (provided by pip), the graph was shown correctly. I needed to update to this version to get text-events in Tensorboard.

- **TensorFlow version (use command below)**: 1.2.0-rc2 (build 694 of job "tf-master-win-gpu-cmake")
- **Bazel version (if compiling from source)**: - 
- **CUDA/cuDNN version**: 8.0/5.1
- **GPU model and memory**: GTX680 with 4 GB
- **Exact command to reproduce**:
```
tensorboard --logdir=Test
```

If I use "inspect" I get the following output:

```
tensorboard --logdir=Test --inspect
======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Found event files in:
Test

These tags are in Test:
audio -
histograms -
images -
scalars -
tensor -
======================================================================

Event statistics for Test:
audio -
graph
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []
histograms -
images -
scalars -
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -
======================================================================

```
I'm using Chrome Browser for Tensorboard (Firefox does not show anything for that version).

### Describe the problem
No Graph is shown on Tensorboard.

### Source code / logs
See above

**Comment by zismylove** [comment]
i had meet this problem too.someone can help?

**Comment by Netzeband** [comment]
@zismylove
Do you use exactly the same version of tensorflow like I did?
Are you also working on Windows?

Maybe this information is helpful for the devs.

Furthermore there are new nightly builds available:
https://ci.tensorflow.org/job/tf-master-win-gpu-cmake/ (698)
Maybe this will work? I did not try so far...

**Comment by zismylove** [comment]
@Netzeband 
no,it don't work.

**Comment by Netzeband** [comment]
@zismylove Thanks for testing.

**Comment by dandelionmane** [comment]
@Netzeband Can you show us what messages (if any) are printed to the console in Chrome/Windows?

**Comment by Netzeband** [comment]
@deannalinchen It is simply the message, that no graph data was found:

![nograph](https://user-images.githubusercontent.com/26524132/27052746-fc5e104c-4fba-11e7-8110-0cdc782ea423.PNG)

The strange thing is, that the graph was found by the inspect command.

Thanks for taking care about that issue.

**Comment by dandelionmane** [comment]
@Netzeband Can you show a screenshot of the Chrome debugger console output (as found when you use the inspect command), and show a screenshot of what you mean when you say "the graph was found by the inspect command"?

**Comment by Netzeband** [comment]
@dandelionmane To be honest, I have no idea how to activate the Chrome debugger console. Can you explain it to me? If you mean the console, I can open with [Ctrl]+[Shift]+J, there is nothing inside. Do I need to activate any special mode? 

In the very first post, I paste the output of the terminal, when I start tensorboard with `--inspect` argument. Here you can see, that the graph is found by tensorboard inside the event file.

**Comment by kinderry** [comment]
meet this problem too.

**Comment by kinderry** [comment]
#7856 may help you

**Comment by Netzeband** [comment]
@kinderry Thanks for the hint with the other issue, but seems to be a completely different topic. 
Here, I use a relative pathname. This means tensorboard is indeed started from the same drive, it is even started from the parent directory of the summary-dir. And furthermore all data are shown, except of the graph.

**Comment by Netzeband** [comment]
@all
Good news. I tried today the official Tensorflow 1.2 release from this night and the graph is shown correctly now. Thus this issue can be closed. 
Thanks to all, who contributed to solve this issue.

**Comment by EarlitoW** [comment]
Try Firefox. I t worked for me ! ! !
On Chrome and IE, TensorBoard would not display Graphs, Histograms or Embeddings.
However, FireFox 55.0.0 displayed everything.
My Chrome is at 62.0.3202.94
My IE is at 11.0x
On Windows 7

BTW: This issue might me the same as #9701

**Comment by Mzmat** [comment]
same problem firefox fixed it

**Comment by alberduris** [comment]
I get this problem eventually. I don't know why sometimes it works and sometimes doesn't, but the work around is opening it with Firefox. 

I can't really understand how a Google Product like Tensorboard doesn't work on Chrome and does it on Firefox, but that's it.
