### ISSUE TITLE
how can convert pascal voc dataset  labels?

### ISSUE THREAD

**Issue by jeansely** [tensorflow/tensorflow#10610]
Hi,
how can conversioning  the pascal voc 2012 dataset and the berkely extended version.
has the tensorflow  solution for this  problem. or a link for download with prepossessing annotation.

Thanks.

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
