### ISSUE TITLE
Implement components for "Self-normalizing networks"

### ISSUE THREAD

**Issue by lakshayg** [tensorflow/tensorflow#10612]
Hochreiter's group has recently come up with a new dropout technique and activation function in a recent paper (https://arxiv.org/abs/1706.02515). Presented experiments demonstrate that these lead to better learning in standard feed forward networks. 

I would like to implement these components in TensorFlow. Creating this issue to gauge the community's interest level in such components. Feedback will be extremely helpful.

**Comment by lakshayg** [comment]
The following need to be implemented in order to complete this task

- [  ] SELU Activation function
- [  ] Alpha-dropout
- [  ] The recommended for weight initialization

**Comment by AnishShah** [comment]
Can I work on Alpha dropout?

**Comment by lakshayg** [comment]
Yeah, sure!

**Comment by cgarciae** [comment]
Very interested in testing this! How is it comming out?

**Comment by lakshayg** [comment]
Selu is already done. I don't think alpha dropout has been merged.

**Comment by cgarciae** [comment]
When will this ship?

**Comment by thesuperzapper** [comment]
Alpha-dropout just got merged. #11357
