### ISSUE TITLE
Feature Request: Tensorboard visualization of what parts of a given training image were deemed as 'important' after a inception v3 has been retrained

### ISSUE THREAD

**Issue by John12341234** [tensorflow/tensorflow#10619]
After retraining inception v3 on my own image set, I'm running into where any new image that I ask it to recognize, that _shouldn't_ match any of the training categories, is confidently scored as one of the image categories. 

For example, if I train it on two types of steering wheels that are exactly the same except one category/type has two buttons on the right. After training has finished, if I show inception an image of some other random thing, like a horse, it confidently scores it as one of the steering wheel categories! 

The issue is that there is no way to get insight as to _why_ this is happening. In other words, there is no way to tell that the model has correctly learned that the real difference between the two steering wheel categories is presence or absence of the the two buttons on the right. It would be extremely useful to be able to upload an image in tensorboard and have it show you a heat map, overlaid on the image, of what specific parts of the image the model deemed important when classifying it as a particular category. 

To elaborate further, if you have two categories that you retrained inception on, you would be able to upload an image, and you would see different regions of the image highlighted using two different colors (one color per category). Then you would be able to clearly see that the model has or has not correctly learned the real difference between the images. In addition, you could upload a image that should not be classified as one of the two categories and you would be able to see _why_ it incorrectly thought it was one of the two categories.
![00c0c_jygsfznatmv_600x450](https://user-images.githubusercontent.com/13044220/27007360-baed3810-4e05-11e7-9e68-5e895fd5562b.jpg)
![112_0905_04z-2010_toyota_prius-interior_view](https://user-images.githubusercontent.com/13044220/27007362-c6e05bc0-4e05-11e7-9280-4f40c4585545.jpg)

**Comment by aselle** [comment]
Since this is more of a machine learning research question (rather than a concrete bug or feature request), it really is better asked on StackOverflow. Thanks!
