### ISSUE TITLE
clip_by_value doesn't work with float64

### ISSUE THREAD

**Issue by evanthebouncy** [tensorflow/tensorflow#1061]
error message:

    Traceback (most recent call last):
      File "_script_nn_skipgram1.py", line 3, in <module>
        nn_skip = NN_SKIP()
      File "nn_skipgram1.py", line 122, in __init__
        self.train_step = optimizer.apply_gradients(zip(grads, tvars))
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 282, in     apply_gradients
        self._assert_valid_dtypes([g, v])
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 354, in _assert_valid_dtypes
        dtype, t.name, [v for v in valid_dtypes]))
    ValueError: Invalid type tf.float64 for clip_by_value:0, expected: [tf.float32].

original thread:
https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/A_qsCKiEKGE

**Comment by siddharth-agrawal** [comment]
I looked into this issue, and as far as I can tell, the issue comes from [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/optimizer.py#L379) in the `class Optimizer()` implementation, and not the `clip_by_value` op. Also none of the optimizers override the `_valid_dtypes()` method. I don't have background information as to why the dtypes did not include float64. Can one of the admins comment on this?

**Comment by yaroslavvb** [comment]
I suspect it's historical -- in the beginning few ops had working float64
implementations. Someone should try adding dtypes.float64 to that line and
seeing if it works.

On Sat, May 14, 2016 at 6:26 AM, Siddharth Agrawal <notifications@github.com

**Comment by siddharth-agrawal** [comment]
Tried that, it works. Tested on a modified version (replaced all float32s by float64s) of @evanthebouncy's code [here](https://github.com/evanthebouncy/matching_parenthesis_rnn/blob/master/matching.py), using which the bug was reported I presume. Should I send out a PR?

**Comment by yaroslavvb** [comment]
Nice, good to know the fix is so simple. A PR seems like a generally good thing to do, although I don't know how overwhelmed the people in charge of merging are right now, I'll let someone else comment

**Comment by siddharth-agrawal** [comment]
@yaroslavvb Fix for the issue was merged as referenced above, this can be closed.
