### ISSUE TITLE
Issue adding external Library (OpenCL)

### ISSUE THREAD

**Issue by ashokbugude** [tensorflow/tensorflow#10614]
Description of the problem / feature request / question:

I am trying to use bazel to build TensorFlow Library. It builds fine.

Additional Feature :
I would like to add OpenCL code in one of the files of TensorFlow. Added all the required code
AND added the following in one of the build files (tensorflow/core/BUILD), considering 'opencl' as the root directory of opencl.

cc_library(
name = "opencl",
hdrs=glob(["opencl/include/CL/*h"]),
visibility =["//visibility:public"],
)

cc_library(
name="all_kernels" ,
visibility= ["//visibility:public"],
copts=tf_copts() + ["-Ithird_party/opencl/include"],
deps= [
"//third_party/opencl",
],

If possible, provide a minimal example to reproduce the problem:

By running
bazel build //tensorflow/examples/android:tensorflow_demo --fat_apk_cpu=armeabi-v7a --copt="-Ithird_party/opencl/include"

Issues Faced while building :
error: undefined reference to 'clEnqueueReadBuffer'
error: undefined reference to 'clReleaseMemObject'
error: undefined reference to 'clReleaseMemObject'

etc

Environment info

Operating System: Ubuntu 17.04

Bazel version (output of bazel info release): release 0.5.1

Have you found anything relevant by searching the web?

https://stackoverflow.com/questions/37761469/how-to-add-external-header-files-during-bazel-tensorflow-build/37844376

Anything else, information or logs or outputs that would be helpful?

bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/kernels/libandroid_tensorflow_kernels.lo(conv_ops.o):conv_ops.cc:function matrixMul(float*, float*, int, int, int, int, int, int): error: undefined reference to 'clGetPlatformIDs'
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/kernels/libandroid_tensorflow_kernels.lo(conv_ops.o):conv_ops.cc:function matrixMul(float*, float*, int, int, int, int, int, int): error: undefined reference to 'clGetDeviceIDs'
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/kernels/libandroid_tensorflow_kernels.lo(conv_ops.o):conv_ops.cc:function matrixMul(float*, float*, int, int, int, int, int, int): error: undefined reference to 'clCreateContext'

I tried linking directly to libOpenCL.so as shown below by referring https://bazel.build/versions/master/docs/tutorial/cpp.html#adding-dependencies-on-precompiled-libraries
, but still same issue

cc_library(
    name = "opencl",
    srcs = glob(["lib/x86_64/*.so"]),
    hdrs = glob(["include/CL/*.h"]),
visibility = ["//visibility:public"],
)

Please help me in resolving the issuee

**Comment by ashokbugude** [comment]
The libOpenCL.so was red in color in terminal, which meant it was archived, replaced the file and issue is resolved

**Comment by rodburns** [comment]
I'm not sure entirely what you are trying to do, but are you aware of the OpenCL implementation effort discussed [here,](https://github.com/tensorflow/tensorflow/issues/22) with instructions on how to try it out [here](https://www.codeplay.com/products/computesuite/computecpp/guides/how-to-setup-tensorflow-with-computecpp)
