### ISSUE TITLE
Failed cuda build from master 

### ISSUE THREAD

**Issue by AlexJoz** [tensorflow/tensorflow#1063]
Use Docker 1.10 with official nvidia image: nvidia/cuda:7.0-cudnn2-devel 
Have tried Bazel 1.0.0, 1.0.4, 1.0.5
TF version from current git master
Whats wrong?

`____From Compiling tensorflow/core/kernels/cwise_op_not_equal_to.cc:
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
ERROR: /tensorflow/tensorflow/core/BUILD:355:1: C++ compilation of rule '//tenso
rflow/core:kernel_lib' failed: gcc failed: error executing command /usr/bin/gcc
-U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set
-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ff
unction-sections ... (remaining 77 argument(s) skipped): com.google.devtools.bui
ld.lib.shell.BadExitStatusException: Process exited with status 4.
____Building complete.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
____Elapsed time: 1975.401s, Critical Path: 1894.23s
The command '/bin/sh -c bazel build -c opt --config=cuda //tensorflow/cc:tutoria
ls_example_trainer' returned a non-zero code: 1`

**Comment by AlexJoz** [comment]
i found that 4 is often out of memory error.. 
But i build it on system with 16 GB RAM and no more than 3GB is used through the whole job..

**Comment by vrv** [comment]
Try the instructions mentioned here: https://github.com/tensorflow/tensorflow/issues/349

**Comment by AlexJoz** [comment]
i saw that, but it does not help =(

**Comment by vrv** [comment]
Can you file a bug with the bazel team to see if you can get more help?

**Comment by AlexJoz** [comment]
Sorry, it's my fault with VM settings) Works well if u have 8 or more GB VM RAM
Could use smth like this to create nice docker machine: 
`docker-machine create —driver virtualbox —virtualbox-memory 8192 —virtualbox-cpu-count 4 MachineName`
