### ISSUE TITLE
i get an error when i build tensorflow by bazel on windows

### ISSUE THREAD

**Issue by mmdlearn** [tensorflow/tensorflow#10631]
PS C:\WINDOWS\system32> cd tensorflow
PS C:\WINDOWS\system32\tensorflow> bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --cop
t=-msse4.2 --copt=-msse --copt=-msse2 --copt=-msse3 --copt=-msse4.1 //tensorflow/tools/pip_package:build_pip_package
>>
.....................
ERROR: C:/windows/system32/tensorflow/tensorflow/tools/pip_package/BUILD:27:1: error loading package 'tensorflow/core':
Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Traceback (most recent cal
l last):
        File "C:/windows/system32/tensorflow/tensorflow/workspace.bzl", line 117
                _apply_patch(repo_ctx, repo_ctx.attr.patch_file)
        File "C:/windows/system32/tensorflow/tensorflow/workspace.bzl", line 108, in _apply_patch
                _execute_and_check_ret_code(repo_ctx, cmd)
        File "C:/windows/system32/tensorflow/tensorflow/workspace.bzl", line 92, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ..., <2 more arguments>))
Non-zero return code(127) when executing 'C:\tools\msys64\usr\bin\bash.exe -c patch -p1 -d C:/users/godw/appdata/local/t
emp/_bazel_godw/nseddbsr/external/protobuf -i C:/windows/system32/tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
 and referenced by '//tensorflow/tools/pip_package:included_headers_gather'.

**Comment by mmdlearn** [comment]
i realy want to know ho to solve this problem

**Comment by mmdlearn** [comment]
i installed the patch tool on my meachine ，but then，get this error
----------------------------------
ERROR: C:/windows/system32/tensorflow/tensorflow/tools/pip_package/BUILD:27:1: error loading package 'tensorflow/core':
Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Traceback (most recent cal
l last):
        File "C:/windows/system32/tensorflow/tensorflow/workspace.bzl", line 117
                _apply_patch(repo_ctx, repo_ctx.attr.patch_file)
        File "C:/windows/system32/tensorflow/tensorflow/workspace.bzl", line 108, in _apply_patch
                _execute_and_check_ret_code(repo_ctx, cmd)
        File "C:/windows/system32/tensorflow/tensorflow/workspace.bzl", line 92, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ..., <2 more arguments>))
Non-zero return code(2) when executing 'C:\tools\msys64\usr\bin\bash.exe -c patch -p1 -d C:/users/godw/appdata/local/tem
p/_bazel_godw/nseddbsr/external/protobuf -i C:/windows/system32/tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout:
Stderr: C:\Program Files (x86)\GnuWin32\bin\patch.exe: **** Can't open patch file C:/windows/system32/tensorflow/third_p
arty/protobuf/add_noinlines.patch : No such file or directory
 and referenced by '//tensorflow/tools/pip_package:included_headers_gather'.

-------------------
but the file is in that directory........

**Comment by aselle** [comment]
Perhaps try cmake? Be sure to read everything here.
https://www.tensorflow.org/install/install_sources
Unfortunately building from source (particularly on Windows) is quite difficult and not recommended unless you are comfortable diagnosing the kind of errors that come from these tools.

**Comment by Spenhouet** [comment]
I think i had a similar issue. Mysys is missing the patch command. You need to install it.
I think i did this with the command `pacman -Syuu patch` in the command line.

Maybe it also helps to follow some of these steps: [Bazel build with Windows](https://bazel.build/versions/master/docs/windows.html)

Sadly i can't build tensorflow on windows too... i just can't get it to work in anyway. :( I'm totally stuck but i really would need this to work.

**Comment by joseortiz3** [comment]
I just had the same error compiling on Windows 10 with Cuda 10.0, the latest release of msys64, and the latest release of bazel. Just as @Spenhouet said, `patch` can't be found because msys doesn't have it by default for some reason.

**Comment by kannufromhld** [comment]
Hi joserotiz3 how did you solved it?

**Comment by Christopheraburns** [comment]
patch must be added after msys2 is installed.  In the directions for installing MSYS2 here: https://www.tensorflow.org/install/source_windows  You can see the instructions to run the following command: pacman -S git patch unzip.  Here is a screen grab from my attempt to update msys2:  https://s3.amazonaws.com/chris-pub-share/msys2_patch.png   HOWEVER, I ran this command nearly 20 minutes ago and I am getting no confirmation that the process is running properly or complete.

**Comment by Christopheraburns** [comment]
So... where it says to run pacman in Cmd.exe - it means to run the pacman command in Cmd.exe, not powershell (like I did above).  Running in powershell you never see a prompt to "continue(Y/N)" you do see it in Cmd.exe

**Comment by simpleKiriath** [comment]
yea trying to get this stuff to work on windows is absolute crap.

**Comment by satyamedh** [comment]
I imstalled it, and spent a good whole day finding why it didnt work in the pycharm CMD, turn out, you have to restart pycharm entirly for env vars to chnge! also mods close this one

**Comment by mihaimaruseac** [comment]
Closing as requested, also because it's old and patch setup has since changed
