### ISSUE TITLE
Might be a bug for contrib.legacy_seq2seq

### ISSUE THREAD

**Issue by liu115** [tensorflow/tensorflow#10638]
Hi, 

I am using the embedding_attention_seq2seq with output_projection. The document from https://www.tensorflow.org/api_docs/python/tf/contrib/legacy_seq2seq/embedding_rnn_decoder says,
> outputs: A list of the same length as decoder_inputs of 2D Tensors with shape [batch_size x num_decoder_symbols] containing the generated outputs.

But the output seems to be the output before projection when I used it. So I go through the source code from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py , 

embedding_attention_seq2seq is base on the embedding_attention_decoder and attention_decoder. It has to give output_size to attention_decoder, but output_size is set to None when output_projection is not None.
```python
def embedding_attention_seq2seq(encoder_inputs,
                                decoder_inputs,
                                cell,
                                num_encoder_symbols,
                                num_decoder_symbols,
                                embedding_size,
                                num_heads=1,
                                output_projection=None,
                                feed_previous=False,
                                dtype=None,
                                scope=None,
                                initial_state_attention=False):
    ... # skip
    output_size = None
    if output_projection is None:
      cell = core_rnn_cell.OutputProjectionWrapper(cell, num_decoder_symbols)
      output_size = num_decoder_symbols

    if isinstance(feed_previous, bool):
      return embedding_attention_decoder(
          decoder_inputs,
          encoder_state,
          attention_states,
          cell,
          num_decoder_symbols,
          embedding_size,
          num_heads=num_heads,
          output_size=output_size,
          output_projection=output_projection,
          feed_previous=feed_previous,
          initial_state_attention=initial_state_attention)
```

When output_size is None, the output_size is simply the cell's output_size. And so the shape of output for embedding_attention_seq2seq will be [batch_size x cell's output_size]  rather than [batch_size x num_decoder_symbols]
```python
def attention_decoder(decoder_inputs,
                      initial_state,
                      attention_states,
                      cell,
                      output_size=None,
                      num_heads=1,
                      loop_function=None,
                      dtype=None,
                      scope=None,
                      initial_state_attention=False):
  ... # skip
  if output_size is None:
    output_size = cell.output_size
  ... # skip
      with variable_scope.variable_scope("AttnOutputProjection"):
        output = linear([cell_output] + attns, output_size, True)
      if loop_function is not None:
        prev = output
      outputs.append(output)

  return outputs, state
```

Thanks.

**Comment by aselle** [comment]
Please take a look @ebrevdo. Thanks!

**Comment by jcomfort4** [comment]
+1 I am observing this same behavior in embedding_rnn_decoder -- are there any updates or workarounds here? Is there a way to get the output_projection weights and multiple them?

My current workaround is to create a dense later that takes in outputs and converts to the num_decoder_size, but this feels inaccurate.

**Comment by lukaszkaiser** [comment]
I'm not sure what you want to achieve: when `output_projection` is given, you are passing the variables to the dense layer yourself, right? In that case, `num_decoder__symbols` is ignored, as I think we specify. Could you explain the problem?

**Comment by jcomfort4** [comment]
So I am actually trying to point out the opposite.  When output_projection = None, then num_decoder_symbols should not be ignored and the outputs should be a list of outputs with shape [batch_size x num_decoder_symbols], but what is actually happening is that with output_projection = None the outputs are coming out as [batch_size x cell.output_size] so I am actually being forced to pass the variables to the dense layer myself.  I would like to not have to use output_projection if it can be avoided, but it seems there is no way to avoid it at the moment.

**Comment by lukaszkaiser** [comment]
I can hardly believe this is ignored, it's in the code above:

```
if output_projection is None:
      cell = core_rnn_cell.OutputProjectionWrapper(cell, num_decoder_symbols)
      output_size = num_decoder_symbols
```

So if `output_projection` is None, then we wrap the decoder cell and make sure it outputs `num_decoder_symbols`. How comes it doesn't work for you?

**Comment by jcomfort4** [comment]
I am actually using [embedding_rnn_decoder] (https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py#L233) (sorry if that caused confusion) so I don't see where num_symbols is passed into the cell?  The line you mentioned is in the embedding_rnn_seq2seq, but the functionality is not replicated in the embedding_rnn_decoder. I think that if the code snippet you mentioned was added before cell was passed then the issue I am seeing would be solved?

**Comment by jcomfort4** [comment]
At the very least, the documentation is misleading for embedding_rnn_decoder as it suggests that if output_projection is None that the output projection layer will be wrapped automatically.

**Comment by lukaszkaiser** [comment]
Yes - the functionality isn't replicated in `embedding_rnn_decoder` because you can just wrap the cell before passing it there. It's also not claimed anywhere that `embedding_rnn_decoder` does this, it doesn't even have a parameter `num_decoder_symbols`. So this is solved, I'm still unclear about the original issue, which was clearly with output_projection.

**Comment by jcomfort4** [comment]
Maybe we are reading different documentation, because it is claimed that embedding_rnn_decoder does this.

embedding_rnn_decoder has a parameter [num_symbols](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py#L236) which is the same as num_decoder_symbols and hte [documentation](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py#L273) says "It is of shape [batch_size x num_decoder_symbols] when output_projection is None." so at the very least it seems that this documentation is in fact unclear.  Would you prefer if I open up a separate issue for this?
