### ISSUE TITLE
The official code about:Reading data from Tfrecord file, I do not this it is a good way.Because it do not real random shuffle data, any one have a better way, and how to sample data with tfrecord file. 

### ISSUE THREAD

**Issue by baodingge** [tensorflow/tensorflow#10645]
tensorflow official code about read data from tfrecord like this:
1. creat a shuffle file queue
2. several thread read data from file that dequeue from file queue(The reader will read data from the file until the file is empty, and then the file queue dequeue a new file)
3. put the data read by the reader to a randomshufflequeue, to make a batch data for training or testing.(this way likes one people drinking sweet water problem:drinking a mouthful of sweet water, and adding equal water.)
Even though you shuffle data before convert it to tfrecord, it is not real random.
If you convert each data to a tfrecord file, I think this is real random, but the efficiency is reduced.
Any one has a better way?
Imbalance data is common, sample is a good way to solve this problem, how to sample data with tfrecord file.
Thanks

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
