### ISSUE TITLE
Python3 unit test failure: //tensorflow/contrib/layers:summaries_test

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorflow#1064]
This failure occurs under Python3, but not Python2. 
`bazel test -c opt //tensorflow/contrib/layers:summaries_test`

Other environment info: 
OS: "Linux", kernel: "4.2.0-18-generic", architecture: "x86_64", processor: "Intel(R) Xeon(R) CPU @ 2.50GHz", processor_count: "32", memory_total: "61845920 kB", swap_total: "0 kB", Bazel_version: "Build label: 0.1.4", Java_version: "1.8.0_72-internal", pp_version: "g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4"

> ==================== Test output for //tensorflow/contrib/layers:summaries_test:
> F./var/lib/jenkins/workspace/tensorflow-master-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/contrib/layers/summaries_test.runfiles/tensorflow/contrib/layers/python/layers/summaries_test.py:57: DeprecationWarning: Please use assertEqual instead.
>   self.assertEquals(len(names), 1)
> ......
> ======================================================================
> FAIL: test_duplicate_tag (__main__.SummariesTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/var/lib/jenkins/workspace/tensorflow-master-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/contrib/layers/summaries_test.runfiles/tensorflow/contrib/layers/python/layers/summaries_test.py", line 35, in test_duplicate_tag
>     tf.contrib.layers.summarize_tensor(var)
> AssertionError: ValueError not raised
> 
> ----------------------------------------------------------------------
> Ran 8 tests in 0.058s
> 
> FAILED (failures=1)

**Comment by caisq** [comment]
This error occurs on both CPU and GPU builds. Any plan to fix it?

**Comment by martinwicke** [comment]
I'm looking.
