### ISSUE TITLE
[1.1.0-gpu image] Can't open shared object file libcuda.so.1

### ISSUE THREAD

**Issue by DjangoPeng** [tensorflow/tensorflow#10642]
#### Version info
GPU: Nvidia K40 and K80
Docker : 1.12.6
Image tag: 1.1.0-gpu and latest-gpu
#### Reproduce
I pulled the [tensorflow/tensorflow:1.1.0-gpu](https://hub.docker.com/r/tensorflow/tensorflow/tags/) docker image and I got the error as below when I started to run it:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.
```

**Comment by aselle** [comment]
Are you using nvidia-docker?

**Comment by DjangoPeng** [comment]
No, I'm running on Kubernetes 1.6.4, and followed this [guide](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/) to schedule GPUs. I installed CUDA 8.0 and copied all shared object files about Nvidia GPU driver. Although, I got new error and the reason is seems like the container needs `/dev/nvidia-uvm`. I'm not sure whether it's an issue on TensorFlow image or Kubernetes.
```
 tf.global_variables_initializer().run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1552, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3776, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device to node 'Variable': Could not satisfy explicit device specification '/device:GPU:0' because no devi
ces matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
```

**Comment by therc** [comment]
Is there a libcuda.so.1 in your /usr/lib/nvidia-367 directory? You might have to mess with ldconfig.
I'm not sure how you reached the conclusion that you need nvidia-uvm, but that should be taken care of by the kubelet if you use the gpu resource.

**Comment by DjangoPeng** [comment]
libcuda.so.1 is in my `/usr/local/cuda/lib64`, I attached the ldconfig of `_pywrap_tensorflow_internal.so` as below:
```
        linux-vdso.so.1 =>  (0x00007fffdd3fa000)
        libcublas.so.8.0 => /usr/local/nvidia/lib64/libcublas.so.8.0 (0x00007fca1a1d9000)
        libcuda.so.1 => /usr/local/nvidia/lib64/libcuda.so.1 (0x00007fca197f5000)
        libcudnn.so.5 => /usr/local/nvidia/lib64/libcudnn.so.5 (0x00007fca14a20000)
        libcufft.so.8.0 => /usr/local/nvidia/lib64/libcufft.so.8.0 (0x00007fca0bbd2000)
        libcurand.so.8.0 => /usr/local/nvidia/lib64/libcurand.so.8.0 (0x00007fca07c69000)
        libcudart.so.8.0 => /usr/local/nvidia/lib64/libcudart.so.8.0 (0x00007fca07a02000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fca077f4000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fca075d7000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fca073d2000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fca070c9000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fca06d47000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fca06b30000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fca06767000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fca292fa000)
        libnvidia-fatbinaryloader.so.367.48 => /usr/local/nvidia/lib64/libnvidia-fatbinaryloader.so.367.48 (0x00007fca06519000)
```

**Comment by aselle** [comment]
Also, the usual gpu thing on docker or raw metal is to run nvidia-smi to see if the gpu is visible. I'd try that too (if it applies to kubernetes).

**Comment by sachin-r** [comment]
We are facing the same issue of
`ImportError: libcuda.so.1: cannot open shared object file: No such file or directory`
when upgrading from TF 1.0.0 to 1.1.0 seems others have has the issue as well -
 https://github.com/tensorflow/tensorflow/issues/9969  
Seems this was failing silently in TF1.0.0 - https://github.com/tensorflow/tensorflow/issues/10073
we are using https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/8.0/runtime/Dockerfile no issues while using TF1.0.0 , Please advise

**Comment by cmluciano** [comment]
Is this a version mismatch? Do the libraries on your disk match those within the containers?

**Comment by DjangoPeng** [comment]
@aselle Since nvidia-smi is in `/usr/bin`, I don't think it's a good way to mount `/usr/bin` into container. Do you have some advice to map nvidia-smi into container? 
@cmluciano My host OS is redhat7 with 3.10.0l-514.21.1.e17.x86_64 kernel, and TensorFlow 1.1.0 image is based on Ubuntu 16.04. Do you think there is a version mismatch of Nvidia drivier of them?

**Comment by cmluciano** [comment]
It is possible. Can you check the versions of the cuda and or nvidia-driver packages?

**Comment by therc** [comment]
Is there a libcuda.so in the Docker image? I have seen cases where the image has a libcuda.so from a CUDA installation, but the Kubernetes node had a mix of libraries from the Linux driver installation (e.g. 367.48 vs 367.57 or 375.66).

**Comment by therc** [comment]
Actually, I see that there's a libnvidia-fatbinaryloader.so.367.48 in the lddconfig output. What does the libcuda.so.1 symlink point to? Perhaps _pywrap_tensorflow_internal.so has been linked against 367.48 and you need libcuda.so.1 to really point to libcuda.so.367.48. (Why does it have to link against libnvidia-fatbinaryloader.so in the first place?)

**Comment by therc** [comment]
This looks like the same as https://github.com/tensorflow/tensorflow/issues/9071

**Comment by aselle** [comment]
I'd install the cuda toolkit on the image as #9071 recommends. that would give you access to nvidia-smi. Anyways, my point is that you should verify CUDA GPU is working independent of TensorFlow first.

**Comment by therc** [comment]
That sounds like asking for trouble. You want the nvidia-smi binary and kernel driver to match. So that means that the binary should live outside of the image entirely and should live in a directory on the Kubernetes node that is kept in sync with the driver by the cluster administrator. Then the pod mounts the host directory as e.g. /usr/local/bin or /opt/bin. That's what we've been doing for the past year, going through 4-5 versions of the Nvidia drivers and never had issues (save one with nvprof, where we had erroneously included a few libraries in the image). It sucks that you have to add a couple of volumes and mounts to all your GPU YAMLs, but I have filed a feature request for Kubernetes to extend PodPreset so that you can say, e.g. "when someone asks for GPU resources, always inject these volumes and mountpoints in the pod".

**Comment by aselle** [comment]
Fair enough. The real question is whether or not the GPU install is working or not or if it is a Tensorflow bug. Using some other GPU program like nvidia-smi that is simpler is a common way to separate the problem. LD_DEBUG is a great debugging tool for seeing why shared libraries aren't loading

LD_DEBUG=libs python -c "import tensorflow"
pipe it to a file and find where it is trying to load libcuda and it will tell you exactly what locations its trying for which libraries.

Maybe google for others that have gotten tenosrflow on kubernetes. 
https://medium.com/jim-fleming/running-tensorflow-on-kubernetes-ca00d0e67539

**Comment by DjangoPeng** [comment]
@cmluciano Cuda version is 8.0.44, and the nvidia driver version is 375.66.  I uninstalled the nvidia driver When I realize CUDA includes Nvidia driver actually.
@therc After uninstalled the nvidia driver, the nvidia-smi shows that the nvidia driver, a part of CUDA, version is 367.48. What's more, I can locate the `nvidia-uvm` and `nvidia0` in the container. 
```
$ nvidia-smi
Mon Jun 19 10:04:35 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          Off  | 0000:04:00.0     Off |                    0 |
| N/A   45C    P0    71W / 235W |      0MiB / 11439MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

When I run the `deviceQuery` in the container, a cuda sample I built in host, I got the `Permission denied` error. 
```
# ./deviceQuery
/bin/sh: 8: ./deviceQuery: Permission denied
```
 But if run it outside the container, everything goes well. (The container run as root user too)
```
# ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "Tesla K40m"
  CUDA Driver Version / Runtime Version          8.0 / 8.0
  CUDA Capability Major/Minor version number:    3.5
  Total amount of global memory:                 11440 MBytes (11995578368 bytes)
  (15) Multiprocessors, (192) CUDA Cores/MP:     2880 CUDA Cores
  GPU Max Clock rate:                            745 MHz (0.75 GHz)
  Memory Clock rate:                             3004 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 1572864 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Enabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 4 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 8.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = Tesla K40m
Result = PASS
```
Both `libcuda.so.1` and `libnvidia-fatbinaryloader.so.367.48` are copied from `/usr/lib64` to `/usr/local/nvidia/lib64` in host, and mounted into container later. The same as other shared object files about Nvidia driver.
@aselle I agreed with @therc , if install the cuda toolkit into container, it would cause a mismatch problem between nvidia-smi binary and kernel driver.

**Comment by DjangoPeng** [comment]
Hi guys, although I can't run `deviceQuery` in container, but it doesn't matter. I reallocate the device to GPU in mnist_softmax, and it runs well. I think the key point is copying shared object files in cuda into `/usr/local/nvidia/lib64` and mount them into container. **Don't install nvidia driver individually, just install CUDA which includes a matched nvidia driver**.
Close the issue~

**Comment by DjangoPeng** [comment]
PS: If the `nvidia-uvm` is not found in `/dev/`, you need to run the NVIDIA_SAMPLE such as `deviceQuery` to load the `nvidia-uvm`. I think it's a problem of Nvidia.

**Comment by bhack** [comment]
@DjangoPeng so have you solved with kubernetes? Have you found the minimum set of nvidia files to share from node to pod?

**Comment by sumsuddin** [comment]
Make sure to run with `nvidia-docker`

**Comment by oolekk** [comment]
may be nvidia-docker-plugin is not running, try:
sudo nvidia-docker-plugin

**Comment by thebeancounter** [comment]
> Make sure to run with `nvidia-docker`

solved it for me

**Comment by xinghalo** [comment]
> https://hub.docker.com/r/tensorflow/tensorflow/



> Are you using nvidia-docker? e.g. https://hub.docker.com/r/tensorflow/tensorflow/

```
docker run --runtime=nvidia -p xxxxxxx -t tensorflow/serving:1.12.0-gpu 
```

**Comment by zhangalex** [comment]
Yes, just append --runtime=nvidia to your docker command. The reason is nvidia-docker v1 uses the nvidia-docker alias, where v2 uses docker --runtime=nvidia.
