### ISSUE TITLE
Estimator missing `tf.convert_to_tensor`

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#10640]
#10623 shows, there is `tf.convert_to_tensor` missing somewhere.
@magixsno Could you provide the whole stacktrace, please?

**Comment by magixsno** [comment]
I no longer have access to the machine I was developing on, but I'll get you the stack trace as soon as I get my home machine set up.

**Comment by Androbin** [comment]
@magixsno Any updates on this?

**Comment by magixsno** [comment]
When I set up on my local machine, I have been unable to reproduce, unfortunately.

**Comment by Androbin** [comment]
@magixsno 
Did you checkout the old commit?

**Comment by Androbin** [comment]
Just notices, they renamed the file and changed the lines of the matter: [estimator.md](https://github.com/tensorflow/tensorflow/commit/5479240a00e904b0f05fa4ae3760cb4deedb864c)

**Comment by ali01** [comment]
Community resolved.
