### ISSUE TITLE
SyntaxError: invalid syntax when import tensorflow-gpu as tf  

### ISSUE THREAD

**Issue by dycasxe101** [tensorflow/tensorflow#10647]
hiiiii,,,,
iam newbie in tensorflow, i have followed tutorial from https://www.tensorflow.org/versions/r0.12/get_started/os_setup#using_conda. Every step that i take,  no error,

but when import tensorflow, it's appears error, like this

> import tensorflow-gpu as tf
  File "<stdin>", line 1
    import tensorflow-gpu as tf
                     ^
SyntaxError: invalid syntax

please help me

**Comment by artcg** [comment]
The package on pypi is called tensorflow-gpu but you just import it with "tensorflow"

so...

```import tensorflow as tf```

**Comment by dycasxe101** [comment]
thank u somemuch @artcg :) 👍 👍 👍 thanks for everything 👍

**Comment by GitHubMurt** [comment]
I feel that this issue may be open

```
(Python 3.7) MacBook-xxxe:python xxx$ python3 tensorflow1.py
  File "tensorflow1.py", line 3
    import tensorflow-gpu as tf
                     ^
SyntaxError: invalid syntax
```

**Comment by chez8990** [comment]
@GitHubMurt it's a non-issue, as artcg has said just do 
`import tensorflow as tf`

**Comment by GitHubMurt** [comment]
hmm currently i'm not able to run it with python3 I can do it but with python 2

**Comment by nicolajbky** [comment]
then you need to install it with pip3. instead of just with pip
so:
pip3 install tensorflow-gpu

**Comment by Talent25** [comment]
Suppose I have run both pip install tensorflow-gpu and pip3 install tensorflow-gpu, So, I have two different instances of tensor flow. I am I correct?

Now I assume two instances of tf is installed, does it mean when I run my script with python3 tfsample.py, it goes and use tensorflow-gpu installed by pip3 and when I  use python2.7 tfsample.py, it goes and use tensorflow-gpu installed by pip?

**Comment by harshitsankhla** [comment]
"Suppose I have run both pip install tensorflow-gpu and pip3 install tensorflow-gpu, So, I have two different instances of tensor flow. I am I correct?" -> yes, for python 2.x and 3.x each
