### ISSUE TITLE
C++ unit test failure under GPU config: //tensorflow/core:ops_array_grad_test

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorflow#1065]
Using Python 2, Linux. This failure doesn't occur under the CPU config
`bazel test -c opt --config=cuda //tensorflow/core:ops_array_grad_test`

Error log:

> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so.7.0 lo
> cally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so.6.5 loc
> ally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so.7.0 locally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so locally
> I tensorflow/stream_executor/dso_loader.cc:99] Couldn't open CUDA library libcurand.so.7.0. LD_LIBRARY_PATH: 
> I tensorflow/stream_executor/cuda/cuda_rng.cc:333] Unable to load cuRAND DSO.
> Running main() from test_main.cc
> [==========] Running 10 tests from 1 test case.
> [----------] Global test environment set-up.
> [----------] 10 tests from ArrayGradTest
> [ RUN      ] ArrayGradTest.PackGrad
> I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
> name: Quadro K620
> major: 5 minor: 0 memoryClockRate (GHz) 1.124
> pciBusID 0000:02:00.0
> Total memory: 2.00GiB
> Free memory: 1.57GiB
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:713] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro K620, pci bus id: 0000:02:00.0)
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 1.0KiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 2.0KiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 4.0KiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 8.0KiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 16.0KiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 32.0KiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 64.0KiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 128.0KiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 256.0KiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 512.0KiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 1.00MiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 2.00MiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 4.00MiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 8.00MiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 16.00MiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 32.00MiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 64.00MiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 128.00MiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 256.00MiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 512.00MiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 1.00GiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 2.00GiB
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:73] Allocating 1.37GiB bytes.
> I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:83] GPU 0 memory begins at 0xb011c0000 extends to 0xb58f68000
> [       OK ] ArrayGradTest.PackGrad (65832 ms)
> [ RUN      ] ArrayGradTest.UnpackGrad
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:713] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro K620, pci bus id: 0000:02:00.0)
> [       OK ] ArrayGradTest.UnpackGrad (4 ms)
> [ RUN      ] ArrayGradTest.ConcatGrad
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:713] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro K620, pci bus id: 0000:02:00.0)
> external/bazel_tools/tools/test/test-setup.sh: line 51: 112821 Segmentation fault      (core dumped) "$@"

**Comment by vrv** [comment]
Known -- test is currently not expected to run on GPU.  Will keep it open until we fix.

**Comment by wookayin** [comment]
Just a related question --- If test is not run under GPU (CUDA) configuration, how can we convince ourselves that CUDA kernels for several TF operations do work correctly?

**Comment by girving** [comment]
@vrv, @zffchen78: Is this still an issue?

**Comment by zffchen78** [comment]
Should have been closed.

**Comment by shenh10** [comment]
> Known -- test is currently not expected to run on GPU. Will keep it open until we fix.
Does the issue be solved?
