### ISSUE TITLE
seq2seq.dynamic_rnn_decoder not working for multilayered encoder in TF 1.0

### ISSUE THREAD

**Issue by adakum** [tensorflow/tensorflow#10659]
I am trying to implement **Multilayer Bidirectional Attention based seq2seq** in **TF 1.0** using `**tf.contrib.seq2seq library**`. 
[This is my implementation.](https://github.com/adakum/seq2seq/blob/master/seq2seq_model.py)
It works perfectly fine for single layered encoder and decoder but gives error with multi layer. 

`Error : "ValueError: Shape must be rank 2 but is rank 4 for 'Decoder/dynamic_rnn_decoder/Decoder/attention_decoder/concat' (op: 'ConcatV2') with input shapes: [?,10], [2,2,?,20], []."`

The problem is , when running single layer, the encoder just returns **LSTM state tuple**(for 1 layer) but in multi layer it returns an **array of LSTMStateTuple(i.e. one for each layer.)** which is fed into the decoder and creating problem I guess. 

So isn't `seq2seq.dynamic_rnn_decoder` made to work `MultiRNNCell  `, i.e. multilayered decoder ? 

Encoder part is running perfectly fine for multi layers and **returning encoder states for each layer**. 

**_If u want to run my implementation : 
1.	clone repo
2.	switch to tf 1.0 env
3.	python generate_questions.py 

This will just create computation graph. In case of `num_layer=1`, graph is created is successfully but fails with `num_layer>1`._**

**Comment by Scitator** [comment]
@adakum All works well, you just need to specify projection correctly (use same number of layers, or something like that) for encoder and decoder.
For code, you can look [here](https://github.com/Scitator/TF-seq2seq/tree/feature/seq2symbol).

**Comment by adakum** [comment]
@Scitator  Your implementation is only for single layer encoder right ? 
But yeah u are right. The problem was with concatenation. Right way to concatenate is as follows:
```
self.encoder_state = []

    for i in range(self.num_layers):
        if isinstance(encoder_fw_state[i], LSTMStateTuple):

            encoder_state_c = tf.concat((encoder_fw_state[i].c, encoder_bw_state[i].c), 1, name='bidirectional_concat_c')
            encoder_state_h = tf.concat((encoder_fw_state[i].h, encoder_bw_state[i].h), 1, name='bidirectional_concat_h')
            encoder_state = LSTMStateTuple(c=encoder_state_c, h=encoder_state_h)
        elif isinstance(encoder_fw_state[i], tf.Tensor):
            encoder_state = tf.concat((encoder_fw_state[i], encoder_bw_state[i]), 1, name='bidirectional_concat')
        self.encoder_state.append(encoder_state)

    self.encoder_state = tuple(self.encoder_state)

```

**Comment by Scitator** [comment]
@adakum Yeap, master branch is only for simple model. But in other one, I am using MultiRnnCell and projection looks like - [link](github.com/Scitator/TF-seq2seq/blob/tf_master_seq2seq/seq2seq/rnn_encoder.py#L101)

**Comment by adakum** [comment]
@Scitator The link which u provided seems to be broken

**Comment by Scitator** [comment]
@adakum Sorry, have released the [repo](https://github.com/Scitator/YATS2S) yesterday :)
The code:
```
                if isinstance(encoder_fw_state, rnn.LSTMStateTuple):  # LstmCell
                    state_c = tf.concat(
                        (encoder_fw_state.c, encoder_bw_state.c), 1, name="bidirectional_concat_c")
                    state_h = tf.concat(
                        (encoder_fw_state.h, encoder_bw_state.h), 1, name="bidirectional_concat_h")
                    self.state = rnn.LSTMStateTuple(c=state_c, h=state_h)
                elif isinstance(encoder_fw_state, tuple) \
                        and isinstance(encoder_fw_state[0], rnn.LSTMStateTuple):  # MultiLstmCell
                    self.state = tuple(map(
                        lambda fw_state, bw_state: rnn.LSTMStateTuple(
                            c=tf.concat((fw_state.c, bw_state.c), 1,
                                        name="bidirectional_concat_c"),
                            h=tf.concat((fw_state.h, bw_state.h), 1,
                                        name="bidirectional_concat_h")),
                        encoder_fw_state, encoder_bw_state))
                else:
                    self.state = tf.concat(
                        (encoder_fw_state, encoder_bw_state), 1,
                        name="bidirectional_state_concat")
```
[working link](https://github.com/Scitator/YATS2S/blob/versions/tf_1.2/seq2seq/rnn_encoder.py#L91)
