### ISSUE TITLE
tf.reshape does not take tf.Dimension as argument 

### ISSUE THREAD

**Issue by artcg** [tensorflow/tensorflow#10650]
Minimal code to reproduce

```
import tensorflow as tf
t = tf.constant([1, 2, 3])
d = tf.Dimension(3)
t = tf.reshape(t, [-1, d])
```

Gives stack trace:

```
TypeError: Expected binary or unicode string, got -1
```

The reason this would be useful to allow is because when you access tensor shapes (with, e.g. ```t.shape```) you get it in tf.Dimension so if you want to assign relative to the current shape then you don't need to convert to int

If there is some reason why tensorflow doesn't allow this behaviour than I think at least the stack trace should be more verbose (e.g. in the example above it shouldn't be complaining about -1, it should be complaining about the value in tf.Dimension class)

**Comment by aselle** [comment]
Yes, I can reproduce this. @lukaszkaiser can comment further, but reuse in variable scope is one of those things in the API that is somewhat confusing and we have been working on making more consistent.

**Comment by lukaszkaiser** [comment]
Sorry guys, is this the right github id? I don't see how this has anything to do with variables, what am I missing?

**Comment by artcg** [comment]
Yes I don't think this has anything to do with variable scope, possible confusion between a different GitHub issue

**Comment by hgaiser** [comment]
I'm facing this exact issue, is there a workaround for this?

**Comment by artcg** [comment]
Yeah there is a workaround, cast the element to an int (that message telling you cast to a supported type is new since this issue was created so that is good.)

**Comment by artcg** [comment]
In fact I think the new error message is satisfactory enough that I will close the issue

**Comment by hgaiser** [comment]
@artcg that'd work in this specific use case, but in my actual case the dimension was unknown at that point. Casting it to int wouldn't help.

**Comment by artcg** [comment]
I think you should be able to just wrap an int() over wherever you are passing the tf.Dimension object?

Can you post your code to re-create?

**Comment by kirk86** [comment]
I still find this error in `tf.reshape` whenever the list of indicating the new shape includes a `None`. This might be useful in the case where we don't know the exact shape or the shape might change dynamically according to the data input.
