### ISSUE TITLE
Feature Request: Add an optional command-line argument for a prefix URL

### ISSUE THREAD

**Issue by mebersole** [tensorflow/tensorflow#10655]
Would like to add a command-line argument that allows TensorBoard to run at a different URL location than the root domain.  So for example:
* command-line: `--base_url runhere`
* URL location: `http://<address>:6006/runhere/`

Motivation for request: There are locations where only minimal ports are open and it would be great to use nginx (or similar) to route TensorBoard through port 80.

**Comment by aselle** [comment]
@dandelionmane, could you take a look at this feature request. Thanks!

**Comment by dandelionmane** [comment]
I've migrated this issue to our new repo over at tensorflow/tensorboard.
