### ISSUE TITLE
TF_BINARY_URL

### ISSUE THREAD

**Issue by davidlary** [tensorflow/tensorflow#10662]
Would be so grateful for some guidance.

Please advise on the appropriate TF_BINARY_URL for compiling Tensor Flow on an Odroid XU4 which uses a Samsung Exynos5422 Cortex™-A15 2Ghz and Cortex™-A7 Octa core CPUs and a Mali-T628 MP6(OpenGL ES 3.1/2.0/1.1 and OpenCL 1.2 Full profile).

Please advise on the TF_BINARY_URL to use for:
Ubuntu/Linux 64-bit, CPU only, Python 2.7
Ubuntu/Linux 64-bit, CPU only, Python 3.5

Is there a GPU version that supports the Mali-T628 MP6(OpenGL ES 3.1/2.0/1.1 and OpenCL 1.2 Full profile) on the Odroid XU4

Thank you!

**Comment by aselle** [comment]
OpenCL support is currently quite primitive, so there aren't any binaries yet. You'd have to compile from source, and it will likely not be super smooth to use yet. Thanks!

**Comment by aselle** [comment]
See #22

**Comment by davidlary** [comment]
Thanks Andrew, appreciate it!

The key part of the question was not so much about the GPU, but how to compile a version of tensor flow NOT using a GPU on the Odroid XU, any pointers please?

Thanks 

David

**Comment by aselle** [comment]
Perhaps this...
https://forum.odroid.com/viewtopic.php?f=140&t=24385
Also it is probably similar to rasbperry pi or other android builds.

**Comment by davidlary** [comment]
Thanks, will take a look, appreciate it!
