### ISSUE TITLE
tf.train.Scaffold missing global_step attribute

### ISSUE THREAD

**Issue by edgimar** [tensorflow/tensorflow#10661]
According to the docstring of `tf.train.Scaffold`, there is a `global_step` attribute with the following description:

* `global_step`: A tensor containing the global step counter.  Picked
    from and stored into the `GLOBAL_STEP` collection in the graph by default.

(see https://github.com/tensorflow/tensorflow/blob/f60b6bdcb59f5538f3301207eabc30c10a9b6d46/tensorflow/python/training/monitored_session.py#L84)

The problem is that no such attribute actually exists.

**Comment by aselle** [comment]
@ispirmustafa, could you take a look?

**Comment by tatatodd** [comment]
Any updates @ispirmustafa?

**Comment by ispirmustafa** [comment]
It's a wrong documentation. I'll fix the documentation. History: Global step was part of the Scaffold when we were prototyping the first versions. We removed it while it was getting mature.
