### ISSUE TITLE
Forcing symmetric quantization

### ISSUE THREAD

**Issue by settle** [tensorflow/tensorflow#10664]
### Describe the problem
For various hardware and software performance reasons I want to force a symmetric quantization.  I figure the quickest way to try this out and compare its accuracy with the existing asymmetric quantization is to set the quantization max to be the negative of the min everywhere in "ls tensorflow/core/kernels/\*quant\*".  Am I missing any other files that need to be modified?  Is there a better more centralized way to achieve the desired behavior?

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
