### ISSUE TITLE
DSP process time investigation

### ISSUE THREAD

**Issue by Tanno0518** [tensorflow/tensorflow#10676]
Hello,

I am evaluating the DSP process time by the bellows source code.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/hexagon/hexagon_graph_execution_test.cc

And, The result was short process time.
As one factor, I think that the reason is quantization to input data of  DSP.
Could you please tell me a change procedure for quantization ?
And, Could I please have the pb file(NOT quantizate) before the bellows quantization pb file ?

tensorflow_inception_v3_stripped_optimized_quantized.pb 

I want to compare between DSP process time(quantizate input data) and CPU process time(NOT quantizate input data)

**Comment by aselle** [comment]
@satok16, could you please take a look?

**Comment by satok16** [comment]
The input data type to HVX is floating point not quantized data type for fairness purposes.
The quantization (of the graph) is a pre-process before running the inference.
See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md for more details.
In this link, you can find a download link for non-quantized model.
