### ISSUE TITLE
Linux CPU smoke tests failing due to merged API change

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#10671]
This commit appears to break the Linux CPU tests (at least for me).  It seems that when the smoke tests passed for this commit, the Linux CPU tests didn't include the api_compatibility_test, but now they do.  However, the golden API and the real API have already diverged, so there isn't any possibility of successful passing any more.

```
commit e6f58186363279496c46563e6f065ce7ea16c501
Author: Bo Wang <david.b.wang@gmail.com>
Date:   Mon Jun 5 11:41:32 2017 -0700
```

**Comment by aselle** [comment]
@gunan, please take a look.

**Comment by gunan** [comment]
The goldens are supposed to be updated with each API change.
The test seems to be back to healthy now:
http://ci.tensorflow.org/job/tensorflow-master-cpu/2449/
