### ISSUE TITLE
Tensor flow importing error please help very important

### ISSUE THREAD

**Issue by uttamgoli** [tensorflow/tensorflow#10674]
![error1](https://user-images.githubusercontent.com/29398681/27076888-0a944dde-504c-11e7-8549-6882eda7cff9.PNG)
![error2](https://user-images.githubusercontent.com/29398681/27076889-0a947b9c-504c-11e7-8c59-4de236a9d328.PNG)

**Comment by caisq** [comment]
Did you read this section? https://www.tensorflow.org/install/install_windows#common_installation_problems

It might provide some useful information.

**Comment by AFAgarap** [comment]
@uttamgoli As for the first error, have you set the environment variable for Python? And for the second, following the advice of @caisq, you may want to read up on [this](https://stackoverflow.com/questions/42011070/on-windows-running-import-tensorflow-generates-no-module-named-pywrap-tenso).

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
