### ISSUE TITLE
Use external repository rather than git submodule for protobuf dependency

### ISSUE THREAD

**Issue by davidzchen** [tensorflow/tensorflow#1069]
Currently, TensorFlow vendors its protobuf dependency using a Git submodule due to the [hack](https://github.com/google/protobuf/blob/master/BUILD#L487) that is required for protobuf Python support.

I have made a change (bazelbuild/bazel#702) to add an [`imports` attribute](http://bazel.io/docs/be/python.html#py_library.imports) to Bazel's Python rules, which allows us to add directories to the `PYTHONPATH` and thus allows us to remove the hack in protobuf.

I have a patch to remove the hack for protobuf Python support (see google/protobuf#1230). I am testing this change using a corresponding change to TensorFlow which removes the git submodule and includes the protobuf dependency using a Bazel external repository instead. Once my patch for google/protobuf#1230 has been submitted, I will send out my corresponding patch to TensorFlow for review.

**Comment by martinwicke** [comment]
This is exciting and if it all works I would love that change.

**Comment by damienmg** [comment]
We need bazel 0.2 to have this work.

**Comment by davidzchen** [comment]
This will also require the next protobuf release that contains google/protobuf#1233 as well.

**Comment by kcgthb** [comment]
Any update on this? The protobuf git submodule seems to have been removed sometime before v0.7.1 was tagged, but the new external repo doesn't appaear to be there yet.

Fresh pull:
``` 
$ git clone https://github.com/tensorflow/tensorflow.git
$ cd tensorflow
$ git checkout v0.7.1
$ ./configure
$ bazel build -c opt --config=cuda --verbose_failures //tensorflow/cc:tutorials_example_trainer
.......
ERROR: /share/sw/admin/sources/t/tensorflow/tensorflow/cc/BUILD:63:1: error loading package 'tensorflow/core': Extension file not found. Unable to load package for '//google/protobuf:protobuf.bzl': BUILD file not found on package path and referenced by '//tensorflow/cc:tutorials_example_trainer'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 1.988s
```

What's the current way of compiling Tensorflow from source?

**Comment by davidzchen** [comment]
@kcgthb - I don't think the protobuf Git submodule has been removed yet. Does running `git submodule update --init` work for you?

In any case, since my patch to protobuf has been merged (see google/protobuf#1233), I have just opened a PR to switch to an external repository in tensorflow (see #1289).

**Comment by kcgthb** [comment]
Ah right, was missing `--recursive` for the inital clone, sorry for the noise.

**Comment by trinity77** [comment]
Trigger Closed
