### ISSUE TITLE
RDMA transport should support variable sized tensor

### ISSUE THREAD

**Issue by llhe** [tensorflow/tensorflow#10699]
RDMA transport disabled variable size tensor https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L738 and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L759.

However, in the embedding lookup model, the tensor has variable size. It's a common model parallelism case.

**Comment by llhe** [comment]
@junshi15 @anfeng  Any comments?

**Comment by junshi15** [comment]
Current design only allows string tensors to change size, when a larger string tensor is requested, the buffer size increases. To allow other tensor to increase size (smaller tensors are fine), we need to remove this check https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L738. 

Note there is no mechanism to shrink the buffer size, so in the end, the buffer is as large as the largest tensor seen so far. If the large tensor tensor is rare, we probably should shrink the buffer to save the memory usage. But maybe this is not an issue in most cases.

**Comment by llhe** [comment]
@junshi15 Both L738 and L759 should be removed. The common usage pattern is still unknown, so don't know what is the best policy. Maybe we can remove the checks and first document this potential memory wastage as a warning?

**Comment by junshi15** [comment]
yes, both changes are needed. I am fine with changing "assert" to "LOG(WARNING)".
