### ISSUE TITLE
Truncated backprop docs are confusing

### ISSUE THREAD

**Issue by allentran** [tensorflow/tensorflow#107]
The docs (http://tensorflow.org/tutorials/recurrent/index.md) imply that to truncate backprop, you feed blocks of fixed (time) length (`num_steps`) to `RNNCell`.  

Does this mean that if I have sentences of length 100 and I want to truncate by 20 time steps, I would send tensors of shape `batch_size x 20`?

If I'm right and you are supposed to feed blocks of fixed length inputs in an inner loop, don't I need to initialize the initial state from the previous block for the forward pass to be right.  But if I do use the final hidden state of the previous block as the next initial state, won't the autograd backpropagate all the way through.  In other words, looping over blocks of intervals and then within each in block while connecting the previous block's hidden state to the next block's initial state seems equivalent to just looping over time in the first place.

Am I missing something?

**Comment by raingo** [comment]
A guess:

If you look at line224-230 of ptb_word_lm.py, the initial state is in the data feeder dictionary, which is set as the state from the previous batch.

**Comment by allentran** [comment]
Thanks, I get it now.

For other Theano users reading this, here is an explanation.  In Theano, you build the graph iterating all the way through time, but making sure to set `truncate=num_steps` in `scan()`.  In TensorFlow, you literally construct the graph for `num_steps` and pass in data with length equal to num_steps while making sure to initialize the state to the previous iteration's final hidden state.
