### ISSUE TITLE
[Feature Request] can tfdbg support printing or writing into file the whole (complete) tensor ?

### ISSUE THREAD

**Issue by whatbeg** [tensorflow/tensorflow#10706]
### Describe the problem

I used tensorflow's new debugger named tfdbg to debug tensorflow's application, which I need to see some intermediate tensors, but, for example, I tried to debug `wide_n_deep_tutorial.py`, 
when I type command like 
`print_tensor linear/linear/native_country/native_country_weights/embedding_lookup_sparse:0`

it gives me following lines:
```
Tensor "linear/linear/native_country/native_country_weights/embedding_lookup_sparse:0:DebugIdentity":
  dtype: float32
  shape: (32561, 1)

array([[-0.11688102],
       [-0.11688102],
       [-0.11688102],
       ..., 
       [-0.11688102],
       [-0.11688102],
       [-0.11688102]], dtype=float32)
```

if I run redirect it to a local file, it also appear like above.

So, there is any method that can print / save the whole tensor ?
If not, can tensorflow add this feature ?
thanks in advance.

###  Source Code

add
```
hooks = None
  if FLAGS.debug:
      debug_hook = tf_debug.LocalCLIDebugHook(ui_type=FLAGS.ui_type)
      debug_hook.add_tensor_filter("has_inf_or_nan", tf_debug.has_inf_or_nan)
      hooks = [debug_hook]
      m.fit(input_fn=lambda: input_fn(df_train),
                steps=train_steps,
                monitors=hooks)

      results = m.evaluate(input_fn=lambda: input_fn(df_test), steps=1)
      for key in sorted(results):
        print("%s: %s" % (key, results[key]))
  else:
      m.fit(input_fn=lambda: input_fn(df_train),
            steps=train_steps)
```
after `wide_n_deep_tutorial.py` 's `m = build_estimator(..)`
and add some args in main function :
```
parser.add_argument(
      "--ui_type",
      type=str,
      default="curses",
      help="Command-line user interface type (curses | readline)")
  parser.add_argument(
      "--debug",
      type="bool",
      nargs="?",
      const=True,
      default=False,
      help="Use debugger to track down bad values during training")
```

**Comment by aselle** [comment]
@caisq, could you address this feature request, please. Thanks!

**Comment by caisq** [comment]
@whatbeg this is already supported. All you need to do is adding the `-a` option:

tfdbg> pt -a <tensor_name>

If you don't want to type the whole command yourself, you can click the tensor to see the incomplete display, and hit Up Array key to navigate to the last command, which is an automatically entered `pt <tensor_name>` command. Then you can just append ` -a` and hit Enter.

**Comment by caisq** [comment]
Also note that it can be a little slow if the tensor is large (like in your case). You can use numpy-type slicing in the command, e.g.,

tfdbg> pt linear/linear/native_country/native_country_weights/embedding_lookup_sparse:0[500:1000]

This table contains a list of the commands and their option flags: https://www.tensorflow.org/programmers_guide/debugger#tfdbg_cli_frequently-used_commands

**Comment by whatbeg** [comment]
@caisq thank you very much, I should check the programmers_guide in detail before asking. : )

**Comment by yogi81** [comment]
but how to write the output of pt -a <tensorname> to a FILE ?

**Comment by caisq** [comment]
@yogi81, please use command:

tfdbg> pt -a my_tensor > /tmp/my_file.txt
