### ISSUE TITLE
[Documentation] cifar10_input.py is referenced but missing on master

### ISSUE THREAD

**Issue by DSLituiev** [tensorflow/tensorflow#10713]
### Describe the problem
File `cifar10_input.py` is referenced in documentation, but is missing on `master`.

Documentation piece:
https://www.tensorflow.org/programmers_guide/reading_data

r0.7 version
https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/models/image/cifar10/cifar10_input.py

**Comment by aselle** [comment]
@wolffg, please take a look!

**Comment by leckie-chn** [comment]
also missing on [cifar10 tutorial](https://www.tensorflow.org/tutorials/deep_cnn)
in r1.2 version
[tensorflow_models/tutorials/image/cifar10/](https://www.github.com/tensorflow/tensorflow/blob/r1.1/tensorflow_models/tutorials/image/cifar10/)

**Comment by leckie-chn** [comment]
see this issue: https://github.com/tensorflow/tensorflow/issues/10711 
seems to need a fix on the tutorial doc

**Comment by wolffg** [comment]
This is now fixed.
