### ISSUE TITLE
Broken Link for CIFAR-10 tutorial

### ISSUE THREAD

**Issue by GChaudhary** [tensorflow/tensorflow#10711]
On the main page of Tensorflow tutorial for CIFAR-10 i.e.
( [https://www.tensorflow.org/tutorials/deep_cnn#model_inputs](url) ), the links in the **[Code Organisation](https://www.tensorflow.org/tutorials/deep_cnn#code_organization)** section are ALL broken. 
To be precise, the on clicking them - **Github** page says '_Page not found_'

Please remove this bug ASAP

**Comment by nathanin** [comment]
They were all moved into another repo

https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10

**Comment by aselle** [comment]
@wolffg, I've verified this. Could you take a look?

**Comment by wolffg** [comment]
This is now fixed.
