### ISSUE TITLE
tf.nn.max_pool wrong docs?

### ISSUE THREAD

**Issue by jkschin** [tensorflow/tensorflow#10729]
### System information
Not Applicable

### Describe the problem
[API](https://www.tensorflow.org/api_docs/python/tf/nn/max_pool) states that ksize has length >= 4, the size of window for each dimension of the input tensor. However, value is a 4-D Tensor so doesn't this mean that ksize should be length == 4? Same for strides.

Digging into maxpooling_op.cc shows that there's some check that does `==`. Line 212:

```
    OP_REQUIRES(context, ksize_.size() == 4,
                errors::InvalidArgument("Sliding window ksize field must "
                                        "specify 4 dimensions"));
```

**Comment by aselle** [comment]
@martinwicke, @josh11b , this seems to come from the attribute specifier only allowing a >= optionally and not ==. 
i.e.
```
REGISTER_OP("AvgPool")
    .Input("value: T")
    .Output("output: T")
    .Attr("ksize: list(int) >= 4")
    .Attr("strides: list(int) >= 4")
    .Attr(GetPaddingAttrString())
    .Attr(GetConvnetDataFormatAttrString())
    .Attr("T: {half, float, double}")
    .SetShapeFn(shape_inference::AvgPoolShape)
    .Doc(R"doc(
```
We can't make it list(int) == 4, because the op registration class doesn't support that for Attr. However, since the attribute constraint gets auto placed in the docs i.e. here:
https://www.tensorflow.org/api_docs/python/tf/nn/max_pool

It is confusing, maybe we shouldn't include the list constraints in auto-generated documentation.

**Comment by josh11b** [comment]
Two things we can do: support more constraint types (good, but work), and add support for = at the beginning of the doc string for attrs suppressing the generated prefix (which currently works for tensor inputs).

**Comment by jkschin** [comment]
If you are accepting PRs for this and could point me to some resources to study how this works in detail (like the op registration class for one), I'd be happy to do one.

**Comment by martinwicke** [comment]
If you want to fix the >= / = / == parsing issue, the code that processes that lives here in tensorflow/core/framework/op_def_builder.cc line 221ff. You could allow == as a token, and then we could use that in the Op registrations. There's no documentation for this, just the code.

We would love a PR for that.

**Comment by aselle** [comment]
Josh also suggested there is a := syntax that lets you remove the constraint part in the docs and provide your own text completely.

**Comment by yongtang** [comment]
Added PR #11925 for the fix. As both `max_pool` and `avg_pool` are wrapped in the python code, the fix only changes the docstring in tensorflow/python/ops/nn_ops.py.
