### ISSUE TITLE
freeze_graph problem

### ISSUE THREAD

**Issue by wm901115nwpu** [tensorflow/tensorflow#10720]
When I use freeze_graph, the --input_checkpoint=model.ckpt-8361242, the data is V1 version. But I use the tensorflow v1.1,the data save as model.ckpt-569500.data-00000-of-00001,model.ckpt-569500.index,model.ckpt-569500.meta.How can I deal with?

**Comment by aselle** [comment]
I believe you can just give "model" and it will find the other files or provide the directory containing the model. Perhaps @concretevitamin can comment.

**Comment by concretevitamin** [comment]
The old way of doing things, `--input_checkpoint=model.ckpt-8361242` (namely, feeding the prefix of those files), still holds.
