### ISSUE TITLE
[BUG] Get different image value each feed

### ISSUE THREAD

**Issue by gongbudaizhe** [tensorflow/tensorflow#10735]
### System information
- OS: Centos 7
- TensorFlow installed from source
- Tensorflow version: both 1.1.0rc1 and 1.2.0rc1
- Bazel version: 0.4.5-jdk7
- CUDA 8.0/ cuDNN 5.1
- GeForce GTX 1080 / 8G

### Describe the problem
Get different values of the same feeded image. 

### Source code
Below is a minimal script that reproduce the problem:
```python
import tensorflow as tf
import numpy as np
from scipy.misc import imread

test_im = some-test-img-path
im = imread(test_im)
im_batch = np.stack([im])

img_feed = tf.placeholder(tf.uint8, (None, None, None, 3))
img_mean = tf.reduce_mean(tf.to_float(img_feed))

with tf.Session() as sess:
  for i in range(10):
    img_mean_tf = sess.run(img_mean, feed_dict={img_feed: im_batch})
    img_mean_np = np.mean(im_batch)
    print('tf img mean: {}, np img mean: {}'.format(img_mean_tf, img_mean_np))
```

**Comment by gongbudaizhe** [comment]
It works as expected in CPU though. Looks like it is related to GPU computation.

**Comment by ppwwyyxx** [comment]
If the difference is not large this is not a bug. Reduction operations on GPU are non-deterministic.

**Comment by aselle** [comment]
@gongbudaizhe, @ppwwyyxx is correct about reproducibility. Please guantify the difference.

**Comment by gongbudaizhe** [comment]
Ok, so this means GPU is inherently non-deterministic... that explains a lot of things... 

In terms of reproducibility, for me, the effect turns out to be minimal. Thanks guys.
