### ISSUE TITLE
hexagon graph execution has put checks for inputs to be of square dimensions, why is it so?

### ISSUE THREAD

**Issue by kzos** [tensorflow/tensorflow#10738]
OS: Ubuntu 16.04 64bits
Android Version: 7.1 (Nougat)
NDK Version: android-ndk-r12b
HEXAGON SDK: 3.1
nnlib source: https://source.codeaurora.org/quic/hexagon_nn/nnlib

I want to test against input shape 1 640 480 3
Below check is returning with error as it is looking for square dimensions.
(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/hexagon/hexagon_graph_execution_test.cc#L136)
`CHECK(fsize >= (WIDTH + 1) * WIDTH * 3 + header_size);`

I am not sure whether I can comment that and I did following that I got this error:
(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/hexagon/hexagon_graph_execution_test.cc#L147)
```
CHECK(src_pos + 2 + header_size < fsize);
CHECK(dst_pos + 2 < pixel_count);
```

Also cannot give input graph as argument while running -> hexagon_graph_execution.
it needs to be changed @ 
(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/hexagon/hexagon_graph_execution_test.cc#L52)
```

constexpr const char* const IMAGE_FILENAME = "/data/local/tmp/img_299x299.bmp";
constexpr const char* const MODEL_FILENAME =
"/data/local/tmp/tensorflow_inception_v3_stripped_optimized_quantized.pb";
```

any plans for standard interface to change 
1) input shape
2) model filename
3) Image filename

thanks,

**Comment by kzos** [comment]
@satok16 , Would be glad and thankful, to provide workaround from your re-factoring code base.

**Comment by satok16** [comment]
@kzos, hexagon_graph_execution_test.cc is a test application intended to run the inception models.  If you want to run an inference on HVX in a more generic way, you should write your own program to follow tensorflow inference steps.  Anyway, the upcoming refactoring will allow you to benchmark arbitrary graph on HVX by benchmark_model.cc without using hexagon_graph_execution_test.cc, and that will help you to understand these tensorflow steps.

**Comment by kzos** [comment]
@satok16, Ok, Already I am making changes for my own interface, got stuck in few op's not being supported by hexagon. Will fix that first, meanwhile, I hope refactored changes would get pushed. BTW you have any tentative date for pushing?

**Comment by satok16** [comment]
@kzos 
Most of the code is already submitted internally.  The remaining part will be submitted in a week, hopefully in a few days.  Stay tuned.

**Comment by kanshuzhi** [comment]
@satok16 May I know currently whether I can run generic graph with HVX and any example for that?
Thanks.

**Comment by satok16** [comment]
That's partially yes, but not easy.  You should transform a graph by using graph_transforms like:

bazel run tensorflow/tools/graph_transforms:transform_graph -- \
--in_graph="${SRC_FILE_NAME}" \
--out_graph="${DST_FILE_NAME}" \
--inputs="${INPUTS}" --outputs="${OUTPUTS}" \
--transforms="\
fuse_remote_graph(\
input_types=\"${INPUT_TYPES}\",\
input_shapes=\"${INPUT_SHAPES}\",\
border_inputs=\"${BORDER_INPUTS}\",\
border_outputs=\"${BORDER_OUTPUTS}\",\
remote_fused_graph_executor_name=\"${REMOTE_FUSED_GRAPH_EXECUTOR_NAME}\",\
remote_fused_graph_node_name=\"${REMOTE_FUSED_GRAPH_NODE_NAME}\"\
)"

You should specify inputs (border_inputs) and outputs (border_outputs) of a subgraph where all ops are supported by HVX.

Currently, I'm away from this work and there are no good examples.  So, the contribution is welcome.

Anyway, the original topic has been already implemented which can be used via the command I noted above.

If you want to add further functionalities, contributions are always welcome.

**Comment by kanshuzhi** [comment]
@satok16 Thanks.
But may I know whether fuse_remote_graph in transform_graph is necessary?
As my understanding, we can use graph transform to make the following transformations.
FP32 model->quantized model->fused hexagon quantized model.
Can I feed FP32 model or quantized model directly into tensorflow with hexagon implement?

Thanks for your help.

**Comment by satok16** [comment]
No, the transform is required in order to let the tensorflow know which ops should be run on HVX because some HVX ops are not optimized and may be much slower than CPU.  So, user needs to optimize the graph manually by using fuse_remote_graph.
