### ISSUE TITLE
[PIP] Markdown version locked to `2.2.0`

### ISSUE THREAD

**Issue by chenliu0831** [tensorflow/tensorflow#10744]
This markdown version lock could cause versioning conflict for downstream (e.g. if requirements are compiled and resolved by pip-compile). Wondering If there's a reason to lock this version. And it's already not sync with the [CI install script](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_pip_packages.sh) (those `--upgrade` with locked version also doesn't seem right to me).

**Comment by chenliu0831** [comment]
A tiny [PR](https://github.com/tensorflow/tensorflow/pull/10743)

**Comment by dandelionmane** [comment]
The markdown requirement is going to leave setup.py for TensorFlow shortly, because it's only needed by TensorBoard, and TensorBoard is exiting to its own repo. So I'm going to close this here, and migrate to TensorBoard.
