### ISSUE TITLE
[go] bug in Shape.size for dim == NumDimensions

### ISSUE THREAD

**Issue by daviddengcn** [tensorflow/tensorflow#10741]
### System information
This does not matter.

### Describe the problem
(go) when dim equals s.NumDimensions(), the function should return -1, instead it panics.

### Source code / logs
In [shape.go](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/shape.go#L62), `Shape.Size` method

        func (s Shape) Size(dim int) int64 {
    ---   if dim < 0 || dim > s.NumDimensions() {
            return -1
should be:

        func (s Shape) Size(dim int) int64 {
    +++   if dim < 0 || dim >= s.NumDimensions() {
            return -1

**Comment by aselle** [comment]
Thanks for the report, please specify the filename (link is even better) in the future to make it clear what you are talking about.  Thanks!
