### ISSUE TITLE
RunMetadata giving inconsistent RAM values

### ISSUE THREAD

**Issue by 3rd3** [tensorflow/tensorflow#10769]
When viewing the GPU memory usage of a run metadata in TensorBoard, it shows for example one node "model" with 9.99 GB and another node "optimization" with 14.1 GB. The sum of these values exceeds the available memory on the GPU (12 GB) by far.

**Comment by dandelionmane** [comment]
Redirecting to @mrry because he understands the RunMetadata api. In the past, he's told me it's very confusing to interpret these numbers.

**Comment by mrry** [comment]
I'm not sure exactly what TensorBoard is visualizing, but it [looks like](https://github.com/tensorflow/tensorboard/blob/6aa3dba050c7a89e826051443a836f07c2e82913/tensorboard/plugins/graphs/tf_graph_common/graph.ts#L427) it's summing up the `total_bytes` fields from some subset of the nodes in a graph. These values represent the sum of all bytes *allocated* during the execution of an op, but don't account for when those bytes are *deallocated*. Therefore it's perfectly reasonable for them to sum to a larger value than the total memory in a device.

**Comment by yaroslavvb** [comment]
@3rd3 you could build more accurate image of maximum memory by parsing memory deallocation messages like in https://github.com/yaroslavvb/memory_util

**Comment by MrWanter** [comment]
@mrry Currently what is the suggest way for tracking down GPU memory usage ?
