### ISSUE TITLE
tensorboard not working on latest sources 11 th feb 2016

### ISSUE THREAD

**Issue by psnegi** [tensorflow/tensorflow#1076]
Hi I have build tensorfow from latest source  on 11 Feb 2016.

I also followed instruction for building tensorboard.

I ran cifar10_train.py. When using tensorboard there is nothing in browser when I  connect to it. 
Browser output is 

No scalar summary tags were found.
Maybe data hasn't loaded yet, or maybe you need to add some tf.scalar_summary ops to your graph, and serialize them using the tf.training.summary_io.SummaryWriter.

I tried adding flush for SummaryWriter. Still same message.  Any suggestion will help me a lot for my work. 

Attaching the console output

when training this is the Error
===============================
/batch)
2016-02-12 11:49:26.445613: step 170, loss = 4.38 (405.8 examples/sec; 0.315 sec/batch)
2016-02-12 11:49:29.575018: step 180, loss = 4.36 (442.2 examples/sec; 0.289 sec/batch)
2016-02-12 11:49:32.828157: step 190, loss = 4.35 (407.5 examples/sec; 0.314 sec/batch)
WARNING:tensorflow:Error encountered when serializing moving_average_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
unbound method to_proto() must be called with Variable instance as first argument (got Tensor instance instead)

When using tensorboard this is the message on console
====================================================

./bazel-bin/tensorflow/tensorboard/tensorboard --logdir=/tmp/cifar10_train
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so.6.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so.7.0 locally
Starting TensorBoard 13 on port 6006
(You can navigate to http://0.0.0.0:6006)
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET / HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /lib/css/global.css HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/lodash/lodash.min.js HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/d3/d3.min.js HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/plottable/plottable.min.js HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/plottable/plottable.css HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/graphlib/dist/graphlib.core.min.js HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/dagre/dist/dagre.core.min.js HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/polymer/polymer.html HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/webcomponentsjs/webcomponents-lite.min.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/iron-ajax/iron-ajax.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/iron-ajax/iron-ajax.html
130.253.128.188 - - [12/Feb/2016 11:50:11] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/iron-ajax/iron-ajax.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/iron-list/iron-list.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/iron-list/iron-list.html
130.253.128.188 - - [12/Feb/2016 11:50:11] code 404, message Not Found
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-button/paper-button.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-button/paper-button.html
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/iron-list/iron-list.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:11] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/paper-button/paper-button.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/iron-collapse/iron-collapse.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/iron-collapse/iron-collapse.html
130.253.128.188 - - [12/Feb/2016 11:50:11] code 404, message Not Found
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-checkbox/paper-checkbox.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-checkbox/paper-checkbox.html
130.253.128.188 - - [12/Feb/2016 11:50:11] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/iron-collapse/iron-collapse.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/paper-checkbox/paper-checkbox.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-dropdown-menu/paper-dropdown-menu.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-dropdown-menu/paper-dropdown-menu.html
130.253.128.188 - - [12/Feb/2016 11:50:11] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/paper-dropdown-menu/paper-dropdown-menu.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-header-panel/paper-header-panel.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-header-panel/paper-header-panel.html
130.253.128.188 - - [12/Feb/2016 11:50:11] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:11] "GET /external/paper-header-panel/paper-header-panel.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-icon-button/paper-icon-button.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-icon-button/paper-icon-button.html
130.253.128.188 - - [12/Feb/2016 11:50:12] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/paper-icon-button/paper-icon-button.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-input/paper-input.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-input/paper-input.html
130.253.128.188 - - [12/Feb/2016 11:50:12] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/paper-input/paper-input.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-item/paper-item.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-item/paper-item.html
130.253.128.188 - - [12/Feb/2016 11:50:12] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/paper-item/paper-item.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-menu/paper-menu.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-menu/paper-menu.html
130.253.128.188 - - [12/Feb/2016 11:50:12] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/paper-menu/paper-menu.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-progress/paper-progress.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-progress/paper-progress.html
130.253.128.188 - - [12/Feb/2016 11:50:12] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/paper-progress/paper-progress.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-radio-button/paper-radio-button.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-radio-button/paper-radio-button.html
130.253.128.188 - - [12/Feb/2016 11:50:12] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/paper-radio-button/paper-radio-button.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-radio-group/paper-radio-group.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-radio-group/paper-radio-group.html
130.253.128.188 - - [12/Feb/2016 11:50:12] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/paper-radio-group/paper-radio-group.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-slider/paper-slider.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-slider/paper-slider.html
130.253.128.188 - - [12/Feb/2016 11:50:12] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/paper-slider/paper-slider.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-styles/paper-styles.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-styles/paper-styles.html
130.253.128.188 - - [12/Feb/2016 11:50:12] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/paper-styles/paper-styles.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-toggle-button/paper-toggle-button.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-toggle-button/paper-toggle-button.html
130.253.128.188 - - [12/Feb/2016 11:50:12] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/paper-toggle-button/paper-toggle-button.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-toolbar/paper-toolbar.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-toolbar/paper-toolbar.html
130.253.128.188 - - [12/Feb/2016 11:50:12] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/paper-toolbar/paper-toolbar.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-tabs/paper-tabs.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-tabs/paper-tabs.html
130.253.128.188 - - [12/Feb/2016 11:50:12] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/paper-tabs/paper-tabs.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /dist/tf-tensorboard.html HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/polymer/polymer-mini.html HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:12] "GET /external/polymer/polymer-micro.html HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET / HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /lib/css/global.css HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/lodash/lodash.min.js HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/plottable/plottable.css HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/plottable/plottable.min.js HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/d3/d3.min.js HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/graphlib/dist/graphlib.core.min.js HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/dagre/dist/dagre.core.min.js HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/polymer/polymer.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/iron-ajax/iron-ajax.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/iron-ajax/iron-ajax.html
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/webcomponentsjs/webcomponents-lite.min.js HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/iron-ajax/iron-ajax.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/iron-collapse/iron-collapse.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/iron-collapse/iron-collapse.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/iron-collapse/iron-collapse.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/iron-list/iron-list.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/iron-list/iron-list.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/iron-list/iron-list.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-button/paper-button.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-button/paper-button.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-button/paper-button.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-checkbox/paper-checkbox.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-checkbox/paper-checkbox.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-checkbox/paper-checkbox.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-dropdown-menu/paper-dropdown-menu.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-dropdown-menu/paper-dropdown-menu.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-dropdown-menu/paper-dropdown-menu.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-header-panel/paper-header-panel.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-header-panel/paper-header-panel.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-header-panel/paper-header-panel.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-icon-button/paper-icon-button.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-icon-button/paper-icon-button.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-input/paper-input.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-input/paper-input.html
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-icon-button/paper-icon-button.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-item/paper-item.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-item/paper-item.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-menu/paper-menu.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-menu/paper-menu.html
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-item/paper-item.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-input/paper-input.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-progress/paper-progress.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-progress/paper-progress.html
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-menu/paper-menu.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-progress/paper-progress.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-radio-button/paper-radio-button.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-radio-button/paper-radio-button.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-radio-group/paper-radio-group.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-radio-group/paper-radio-group.html
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-radio-button/paper-radio-button.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-radio-group/paper-radio-group.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-styles/paper-styles.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-styles/paper-styles.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-styles/paper-styles.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-toolbar/paper-toolbar.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-toolbar/paper-toolbar.html
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /dist/tf-tensorboard.html HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-tabs/paper-tabs.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-tabs/paper-tabs.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-slider/paper-slider.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-slider/paper-slider.html
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-toolbar/paper-toolbar.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-tabs/paper-tabs.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-toggle-button/paper-toggle-button.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-toggle-button/paper-toggle-button.html
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-slider/paper-slider.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-toggle-button/paper-toggle-button.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/plottable/plottable.min.js HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/polymer/polymer.html HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/polymer/polymer-mini.html HTTP/1.1" 200 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/polymer/polymer-micro.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-button/paper-button.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-button/paper-button.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-button/paper-button.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-checkbox/paper-checkbox.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-checkbox/paper-checkbox.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-checkbox/paper-checkbox.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-header-panel/paper-header-panel.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-header-panel/paper-header-panel.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
WARNING:tensorflow:IOError [Errno 2] No such file or directory: ' /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-item/paper-item.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-item/paper-item.html
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-header-panel/paper-header-panel.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-item/paper-item.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-radio-button/paper-radio-button.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-radio-button/paper-radio-button.html
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-radio-group/paper-radio-group.html' on path /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-radio-group/paper-radio-group.html
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-radio-button/paper-radio-button.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:15] code 404, message Not Found
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /external/paper-radio-group/paper-radio-group.html HTTP/1.1" 404 -
130.253.128.188 - - [12/Feb/2016 11:50:15] "GET /dist/tf-tensorboard.html HTTP/1.1" 200 -

These seems to be some issue with path like 

WARNING:tensorflow:IOError [Errno 2] No such file or directory: ' /home/psnegi/Software/tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/external/paper-item/paper-item.html'

After checking path on my system , there is an error in path name
**paper-item**. It should be **paper_item**

Thanks,
Pooran

**Comment by cesarsalgado** [comment]
Same problem here. I have built from source yesterday (11 Feb). Tested in Chrome and Firefox.

**Comment by vrv** [comment]
@danmane fixed it on our release branch here: https://github.com/tensorflow/tensorflow/commit/68e8b0f1e02f1e0e10f4fdd689ede80f973e2756

I'm upstreaming the change to master soon, but in case you want to get up and running, that commit should help.

**Comment by jkschin** [comment]
I built from source today. 15th February. I believe the TensorBoard problem is solved, but the train issue mentioned above is not fixed.

2016-02-15 16:05:17.401242: step 0, loss = 4.68 (22.1 examples/sec; 5.802 sec/batch)
WARNING:tensorflow:Error encountered when serializing moving_average_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
unbound method to_proto() must be called with Variable instance as first argument (got Tensor instance instead)
2016-02-15 16:05:24.678296: step 10, loss = 4.66 (203.6 examples/sec; 0.629 sec/batch)
2016-02-15 16:05:30.914946: step 20, loss = 4.65 (213.1 examples/sec; 0.601 sec/batch)
2016-02-15 16:05:37.341557: step 30, loss = 4.63 (201.4 examples/sec; 0.636 sec/batch)

**Comment by bernardopires** [comment]
I can also confirm that I have the same 'tensorflow:Error encountered when serializing moving_average_variables.' when compiling from source. Running cifar10_train.py will reproduce the issue.

**Comment by martinwicke** [comment]
Please file a new issue for this separate problem to avoid confusion. Thanks.
