### ISSUE TITLE
Feature Request : Tensor Roll

### ISSUE THREAD

**Issue by nicaogr** [tensorflow/tensorflow#10761]
Could you add an equivalent to [Numpy roll](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.roll.html) on Tensor in tensorflow in order to allow the user to roll a Tensor along one of the axis of the tensor ?

**Comment by aselle** [comment]
We definitely would welcome pr's to implement this functionality. Thanks!

**Comment by Zardinality** [comment]
It should be easy to implement it using slice and concat. Does it need to be implemented in a C++ kernel?

**Comment by jain98** [comment]
Hello, I am new to open source and would like to implement this feature. How do I determine which file to implement this feature in?

**Comment by martinwicke** [comment]
Usually a feature like this will involve several files. The best thing to do is to look at a similar op (say, `transpose`, maybe), and find all the files that have to be touched for that op.

There will be at least some files in core/ops, core/kernels, and python/kernel_tests, plus the BUILD files.

If the op is a pure python op, you may get away with only changing/adding a file in python/ops. This is probably not a python op, unless I'm missing a simple way to construct it from existing ops.

**Comment by albertz** [comment]
I implemented that with existing TF operations, see [here](https://github.com/rwth-i6/returnn/blob/master/TFUtil.py) `circular_pad`.

**Comment by kobejean** [comment]
I'd like try to implement this op. Should this go directly into core or somewhere in the contrib directory?

**Comment by asimshankar** [comment]
It's fine to put it in core I think, though not sure what module it should be in (`tf.roll` or `tf.<something>.roll`). Deferring to @aselle for placement.
