### ISSUE TITLE
 Unable to install tenser flow  on python 3.6.1 on windows 10 x64

### ISSUE THREAD

**Issue by Vishurao06** [tensorflow/tensorflow#10786]
![pip](https://user-images.githubusercontent.com/29494774/27248510-24b7f1f6-5322-11e7-9067-1ba4dfb700ac.PNG)

Unable to install tenserflow

**Comment by Carmezim** [comment]
@Vishurao06 You're installing a wheel for Python 3.5. `tensorflow-1.0.0**cp35-cpm35**`. You need the corresponding wheel for Python 3.6 that you can download [here](http://ci.tensorflow.org/view/Nightly/job/nightly-win/M=windows,PY=36/lastSuccessfulBuild/artifact/cmake_build/tf_python/dist/tensorflow-1.2.0rc2-cp36-cp36m-win_amd64.whl)

**Comment by Vishurao06** [comment]
Thanks , but the issue is still the same

![pip](https://user-images.githubusercontent.com/29494774/27249079-a02954d0-532a-11e7-8d6d-e869d0568ebd.PNG)

**Comment by martinwicke** [comment]
@yifeif looks like we're not stripping the amd64 suffix, but we should?

**Comment by Vishurao06** [comment]
thanks i fixed it , actually the pip scripts were default at 32 bit as in the below image 
![pip2](https://user-images.githubusercontent.com/29494774/27249257-8f990634-532e-11e7-99fb-1d66191ee5f0.PNG)

so i changed both path and script path to python36  instead of default python 36-32

**Comment by Carmezim** [comment]
@Vishurao06 glad you solved. TensorFlow requires Python 64-bit on Windows.
