### ISSUE TITLE
build fails for r1.2 on linux

### ISSUE THREAD

**Issue by kshaeffer** [tensorflow/tensorflow#10784]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No

OS: Ubuntu 16.04.2 LTS
I have cloned tensorflow from github.
checked out release r1.2

I have rune the configure script:
$ ./configure
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3
Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.5/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]
/usr/lib/python3/dist-packages
Do you wish to build TensorFlow with MKL support? [y/N] N
No MKL support will be enabled for TensorFlow
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: -march=native
Do you wish to use jemalloc as the malloc implementation? [Y/n] Y
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] N
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] N
No XLA JIT support will be enabled for TensorFlow
Do you wish to build TensorFlow with VERBS support? [y/N] N
No VERBS support will be enabled for TensorFlow
Do you wish to build TensorFlow with OpenCL support? [y/N] N
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] N
No CUDA support will be enabled for TensorFlow
..................................................
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Configuration finished
shaeffer@ip-10-164-47-27:/srv/projects/c++/tfgit1.2$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
ERROR: /srv/projects/c++/tfgit1.2/third_party/py/python_configure.bzl:285:20: unexpected keyword 'environ' in call to repository_rule(implementation: function, *, attrs: dict or NoneType = None, local: bool = False).
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'third_party/py/python_configure.bzl' has errors.
INFO: Elapsed time: 3.281s

The tensorflow r1.2 build fails as described directly above.

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**: GitHub clone of source code
- **TensorFlow version (use command below)**: r1.2

- **Bazel version (if compiling from source)**:

$ bazel version
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261

- **Exact command to reproduce**:

$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Comment by aselle** [comment]
Try upgrading bazel to at least 0.4.5.

**Comment by kshaeffer** [comment]
Ok, upgraded bazel

$ bazel version
Build label: 0.5.1

This has resolved the build failure.
Thank you.
