### ISSUE TITLE
Feature Request-Randomized Hashing

### ISSUE THREAD

**Issue by smrtslckr** [tensorflow/tensorflow#10785]
This is feature request to see if randomized hashing can be implemented to relevant part of the library to allow the option to be utilized for better computational resource utilization:

https://arxiv.org/abs/1602.08194

**Comment by aselle** [comment]
We will likely not work on this in the foreseeable future, but marking contributions welcome to see if there is additional interest.

**Comment by byronyi** [comment]
I am wondering the exact use case you are trying to address, as we already have randomised hashing in `sklearn` ([here](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.FeatureHasher.html) and [there](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.HashingVectorizer.html)).

Or you would like to implement this in C/C++ and export the symbol to bindings of other languages?

**Comment by Erstwild** [comment]
@byronyi Thank you for pointing this functionality in sklearn out for me.  The use case I am trying accomplish is the randomized hashing to radically reduce training time/resource consumption for deep neural networks in Keras/TensorFlow (as demonstrated in the paper).  I will reread the paper to see if it will be as simple initial feature extraction or a more complex architecture.  I suspect it is latter case.

**Comment by horance-liu** [comment]
@Erstwild Has it been implemented yet? Or is it in progress?

**Comment by sushreebarsa** [comment]
@smrtslckr TensorFlow's tf.feature_column.categorical_column_with_hash_bucket provides a hashing mechanism for categorical features, but not specifically designed for embedding layers. But tf.feature_column is not recommended for new code. Instead, feature preprocessing can be done directly using either [Keras preprocessing layers](https://www.tensorflow.org/guide/migrate/migrating_feature_columns) or through the one-stop utility [tf.keras.utils.FeatureSpace](https://www.tensorflow.org/api_docs/python/tf/keras/utils/FeatureSpace) built on top of them. See the [migration guide](https://tensorflow.org/guide/migrate) for details.

Thank you!
