### ISSUE TITLE
1.2 release python pip version is incorrect

### ISSUE THREAD

**Issue by apcode** [tensorflow/tensorflow#10780]
The python pip package still has the version label 1.2.0-rc2 even though 1.2.0 was released proper today. Can you change please.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L32

**Comment by caisq** [comment]
@apcode, the master branch hasn't been updated yet. The release is generated from the r1.2 branch, which is in the process of being merged back to the master branch. Once the merge is done, master will be at 1.2.0 as well.

**Comment by aselle** [comment]
That usually happens when we remerge the 1.2.0 branch back into master. This is normal. Thanks for the comment.
