### ISSUE TITLE
Compiler is out of heap space

### ISSUE THREAD

**Issue by borablanca** [tensorflow/tensorflow#10799]
I am compiling tensorflow on windows 10 laptop, i7 6700hq 16GB ram with Visual Studio 2015 and all dependencies are ok as it is explained on readme. However at the end of compilation I get the following error:

```
"D:\PRJ\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
"D:\PRJ\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (default target) (3) ->
"D:\PRJ\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal_static.vcxproj" (default target) (4) ->
"D:\PRJ\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj" (default target) (105) ->
(ClCompile target) ->
  d:\prj\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBase
.h(832): fatal error C1060: compiler is out of heap space (compiling source file D:\PRJ\tensorflow\tensorflow\core\kern
els\reverse_op.cc) [D:\PRJ\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  d:\prj\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\eigen\src\core\../plugins/MatrixCwiseBinaryOp
s.h(116): fatal error C1060: compiler is out of heap space (compiling source file D:\PRJ\tensorflow\tensorflow\core\ker
nels\self_adjoint_eig_v2_op.cc) [D:\PRJ\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  d:\prj\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\eigen\src/Core/CoreEvaluators.h(599): fatal e
rror C1060: compiler is out of heap space (compiling source file D:\PRJ\tensorflow\tensorflow\core\kernels\svd_op_doubl
e.cc) [D:\PRJ\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
```
How can I solve this problem?

**Comment by aselle** [comment]
This seems to be a compiler bug... try following advice here.
https://stackoverflow.com/questions/43140529/compiler-is-out-of-heap-space

**Comment by borablanca** [comment]
I increased the maximum number of concurrent processes and it did the job with no errors. Also with the huge decrease in compilation time: from ~60 mins to 5 mins !! I compiled with the following code by increasing the concurrent processes to 4 (where the default was 1)

`D:\...\build> MSBuild /m:4 /p:Configuration=Release tf_python_build_pip_package.vcxproj`

Also I want to mention as a side note that I tested both pre-compiled version of tensorflow-gpu and the version that I compiled on training a simple cnn. The speedup is very noticable. Totally worth it!

**Comment by sumsuddin** [comment]
for the ones who are still suffering, take a look [here](http://twonightmare.blogspot.com/2017/08/tensorflow-gpu-build-for-windows-for.html).

**Comment by chrisplyn** [comment]
@borablanca how did you manage to build tensor-gpu? I am consistently failing...

**Comment by Evil-Spirit** [comment]
I just leave it here https://twitter.com/Evl_Spirit/status/993777818294276096
