### ISSUE TITLE
Compiling against Cuda compute environment 3.0 causes TF to take huge virtual memory

### ISSUE THREAD

**Issue by snakecharmer1024** [tensorflow/tensorflow#1079]
I run tensorflow program with htop in another terminal. Standard installation for cpu or gpu doesn't take more than half a GB of virtual memory. If I compile from source, using 

TF_UNOFFICIAL_SETTING=1 ./configure

and using cuda compute environment 3.0 (not 3.5 or 5.2) then the same program uses 38GB of virtual memory. I don't understand cuda well enough to postulate why this would be. It's not a huge problem unless you have lots of them running at once. 

I only do this bc I want to work on AWS GPU instance and they only have K520 or something like that.

**Comment by vrv** [comment]
https://groups.google.com/forum/#!topic/theano-users/-ZT-QObECXQ may be relevant -- probably has something to do with the cuda driver, not TensorFlow specifically.  If you find that TensorFlow is doing something specifically to trigger this problem, please feel free to leave a comment and we'll reopen.
