### ISSUE TITLE
TF Detect to work with the new Object Detection API model

### ISSUE THREAD

**Issue by bryancresswell** [tensorflow/tensorflow#10798]
Hi there, if I replace the current TF Detect model with the new Object Detection API model, will it still work?

**Comment by jch1** [comment]
@bryancresswell  - are you referring to the Android Detection demo?

**Comment by bryancresswell** [comment]
@jch1 yup!

**Comment by jch1** [comment]
It currently won't work (it was actually trained using an older version of the API) - I plan to update it to use the new models over the next couple of weeks.

**Comment by bryancresswell** [comment]
Alright, sounds great! Looking forward to the updates! Thanks for the quick response.

**Comment by bmount** [comment]
@bryancresswell I added an Android example using the Object Detection API (MobileNet w/ SSD) here: https://github.com/bmount/tensorflow/tree/android-demo-mobilenet-ssd (patch: https://github.com/bmount/tensorflow/commit/24b59a4a7797623a9da9311ee1214ac334478ed3 ). You can download the model graphs and labels from the links in the comments in the configuration section of the SSD_ variables. Curious to see how it works for you, I've only tested on 1 high-end phone, latency is not ideal but the quality of detection and tracking is pretty great.

@jch1 I gather you are working on a fuller update to the detection examples -- really looking forward to that. The Object Detection API is so nicely ergonomic (thank you!) that something simple like the above link may be enough to get people started, if it's useful for the demo I could make it PR-able. General feedback toward the other update effort is just: the Single Shot + MobileNet model (from the zoo) with the current tracker is pretty great and would be a reasonable default for the detector activity and build-time downloads, if it performs reasonably on enough devices. An example of feeding RGB inputs with fewer intermediate steps than the examples that assume FP32 inputs would be helpful for demo code (if that's possible.)

**Comment by Savash2016** [comment]
hey @bmount ,

I want to try your project and get your project start on my smartphone (Samsung S7).
I dont have any idea how i can get your finished work  (https://github.com/bmount/tensorflow/tree/android-demo-mobilenet-ssd) on my smartphone. Please can you help me an upload your work as a finished android app ??

best wishes
Savash

**Comment by bmount** [comment]
Hi @Savash2016, here's a large "everything" apk: https://storage.googleapis.com/bmount/ssd-mobilenet-v1-coco/tensorflow_demo.apk . If you have trouble installing, steps to build are: 1) check out https://github.com/bmount/tensorflow/tree/android-demo-mobilenet-ssd 2) run `bazel build -c opt //tensorflow/examples/android:tensorflow_demo` 3) run `adb install -r bazel-bin/tensorflow/examples/android/tensorflow_demo.apk` to install on device. Curious how this runs on your phone, have heard some decent results from people who landed on this thread.

**Comment by Savash2016** [comment]
Niceeeeeee! Hi @bmount,
thank you! I can work with both ways without any problems! 
Previously I work with darkflow/yolo to make an app in android and it was quite the same.

Again, thank you and keep doing!

**Comment by anandcu3** [comment]
@Savash2016  I tried compiling and got the following error..

`No OpKernel was registered to support Op 'Switch' with these attrs.  Registered devices: [CPU], Registered kernels:
                                                                     device='GPU'; T in [DT_STRING]
                                                                     device='GPU'; T in [DT_BOOL]
                                                                     device='GPU'; T in [DT_INT32]
                                                                     device='GPU'; T in [DT_FLOAT]
                                                                     device='CPU'; T in [DT_FLOAT]
                                                                     device='CPU'; T in [DT_INT32]
[[Node: Postprocessor/BatchMultiClassNonMaxSuppression/PadOrClipBoxList/cond/Switch = Switch[T=DT_BOOL](Postprocessor/BatchMultiClassNonMaxSuppression/PadOrClipBoxList/Greater, Postprocessor/BatchMultiClassNonMaxSuppression/PadOrClipBoxList/Greater)]]
                                                                       at org.tensorflow.Session.run(Native Method)
                                                                       at org.tensorflow.Session.access$100(Session.java:48)
                                                                       at org.tensorflow.Session$Runner.runHelper(Session.java:295)
                                                                       at org.tensorflow.Session$Runner.run(Session.java:245)
                                                                       at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:142)
                                                                       at org.tensorflow.demo.TensorFlowSingleShotDetector.recognizeImage(TensorFlowSingleShotDetector.java:105)
                                                                       at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:337)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)`

Can you help me out?

Since I am on Windows, I am using Gradle and using the prebuilt Tensorflow .so and .aar files.

**Comment by Savash2016** [comment]
Hi,
@anandcu3 sorry I dont have an solution for this.

But I would advise you to do your work in linux (ubuntu).
Previously I work with windows  too and after a lot of problems (with bazel and tensorflow) I switched to Ubuntu.

**Comment by bmount** [comment]
@anandcu3 I think I hit the Switch kernel registration issue too and the workaround was this little change in register_types.h:  https://github.com/bmount/tensorflow/commit/24b59a4a7797623a9da9311ee1214ac334478ed3#diff-76e272a58ca1535b3e0ec93499779a14 which I believe I found here: https://github.com/tensorflow/tensorflow/issues/2680 . That patch is part of the commit with the ssd demo, so you should be able to build from that commit, any additional errors would be Windows and I probably wouldn't be helpful debugging.

**Comment by anandcu3** [comment]
@bmount  I took time and got a VM setup with Ubuntu 16 64bit. and used the tensorflow repo from your fork. Now the  Switch kernel registration issue is solved but i get this error. I have enabled the Verbose Failures option.

`ERROR:/home/anand/.cache/bazel/_bazel_anand/5f4d98f843335b68cd2cff2b911e38a7/external/protobuf_archive/BUILD:133:1: C++ compilation of rule '@protobuf_archive//:protobuf' failed (Exit 1): false failed: error executing command `

  `(exec env - \ 
    PWD=/proc/self/cwd \
  /bin/false -MD -MF bazel-out/stub_armeabi-v7a-opt/bin/external/protobuf_archive/_objs/protobuf/external/protobuf_archive/src/google/protobuf/timestamp.pb.pic.d '-frandom-seed=bazel-out/stub_armeabi-v7a-opt/bin/external/protobuf_archive/_objs/protobuf/external/protobuf_archive/src/google/protobuf/timestamp.pb.pic.o' -fPIC -iquote external/protobuf_archive -iquote bazel-out/stub_armeabi-v7a-opt/genfiles/external/protobuf_archive -iquote external/bazel_tools -iquote bazel-out/stub_armeabi-v7a-opt/genfiles/external/bazel_tools -isystem external/protobuf_archive/src -isystem bazel-out/stub_armeabi-v7a-opt/genfiles/external/protobuf_archive/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -c external/protobuf_archive/src/google/protobuf/timestamp.pb.cc -o bazel-out/stub_armeabi-v7a-opt/bin/external/protobuf_archive/_objs/protobuf/external/protobuf_archive/src/google/protobuf/timestamp.pb.pic.o)
` 

Could you please help me debug this? And provide more information about the Bazel and NDK versions used.

**Comment by bmount** [comment]
@anandcu3 The required toolchain is the one in NDK 12b (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android#install-bazel-and-android-prerequisites), IIRC I initially tried with a more recent release too and had a similar problem.

**Comment by anandcu3** [comment]
@bmount I'm using NDK12b as well.. Posted an issue regarding this separately as well..

https://github.com/tensorflow/tensorflow/issues/12109

**Comment by zvadaszi** [comment]
Thanks @bmount ! Tested your apk on a Moto G5 Plus, detection takes ~2-3 seconds but quality is pretty good. Will try to build your detection class and test different quantizations to see if it improves the detection speed.

**Comment by LiangHao92** [comment]
@jch1 thanks for your work first. and I wonder when the updated API can be released.

**Comment by lugq1990** [comment]
@bmount I want to make the .pkt for the object detection on the mobile. And I want to make the the label to be chinese, so I want to know the label of the mobilenet on the tensorflow, but I can't find the label file by downloading the model from the tensorflow model zoo. Maybe can you tell me where to find the label file for the mobilenet? thank you so much! hope your message!

**Comment by bmount** [comment]
@lugq1990 the TensorFlow team has pushed a full update a few days ago that includes MobileNet + Single Shot detector by default, and references to and automatic downloading of models and label files: https://github.com/tensorflow/tensorflow/commit/53aabd5cb0ffcc1fd33cbd00eb468dd8d8353df2

You can download them separately here: http://storage.googleapis.com/download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_android_export.zip -- in COCO a number of classes were removed after labeling had begun, so there are gaps represented by "???", otherwise you should be able to replace each English label with the Chinese equivalent in that word list.

**Comment by lugq1990** [comment]
@bmount that's what I want. Really thank you !!! wish you a good day!

**Comment by wm901115nwpu** [comment]
@bmount When I apply the  TensorFlow team pushed android demo, in the object detection, in my mobilephone can't get any boundingbox,I don't know what it occurs?

**Comment by andrewharp** [comment]
@wm901115nwpu please open a new issue and fill out the template form with all relevant details, including a full description of what you're seeing on the screen and trying to recognize. This will make the problem much easier to diagnose, thanks.

**Comment by anandcu3** [comment]
@wm901115nwpu @andrewharp 

Faced the same issue. I got around that by setting 

`useCamera2API = true`

instead of 

`useCamera2API = isHardwareLevelSupported(characteristics,
            CameraCharacteristics.INFO_SUPPORTED_HARDWARE_LEVEL_FULL);`

at https://github.com/tensorflow/tensorflow/blob/3686ef0d51047d2806df3e2ff6c1aac727456c1d/tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java#L300

**Comment by wm901115nwpu** [comment]
@anandcu3 it works well, thank you.

**Comment by andrewharp** [comment]
@wm901115nwpu @anandcu3 can you please provide details about your devices so that we can further tailor the Camera API selection?

It should still draw boxes on detections using API 1, so if it doesn't then that is also an issue.

**Comment by anandcu3** [comment]
@andrewharp 

I'm on OnePlus X with Marshmallow 6.0.1 (API 23) .

**Comment by wm901115nwpu** [comment]
@andrewharp I'm on HongMi Note4 with MIUI8.5.

**Comment by switchedfabric** [comment]
Huawei P9 Lite: "useCamera2API = true" also made the detection demo work.  No boxes before that.

**Comment by zvadaszi** [comment]
Same issue with a Motorola G5 Plus, got it working with useCamera2API = true

**Comment by thaodhbk0406** [comment]
Do you know How to use direct camera to detect object?
