### ISSUE TITLE
Error compiling in Linux Mint

### ISSUE THREAD

**Issue by DanielLowry** [tensorflow/tensorflow#10806]
I am trying to compile this from source, but currently getting the following issue:

sudo bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures
....................................................................................
WARNING: /home/dan/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/dan/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
ERROR: /home/dan/.cache/bazel/_bazel_root/113acdcc7c9d2b1e2c757002415fbd3e/external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/server/BUILD:48:1: error executing shell command: 'JAR='external/local_jdk/bin/jar' OUTPUT='bazel-out/host/bin/external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/server/libbuild_info_java_proto_srcjar.srcjar' PROTO_COMPILER='exter...' failed: bash failed: error executing command 
  (cd /home/dan/.cache/bazel/_bazel_root/113acdcc7c9d2b1e2c757002415fbd3e/execroot/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
  /bin/bash -c 'JAR='\''external/local_jdk/bin/jar'\'' OUTPUT='\''bazel-out/host/bin/external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/server/libbuild_info_java_proto_srcjar.srcjar'\'' PROTO_COMPILER='\''external/com_google_protobuf_protoc/bin/protoc'\'' SOURCE='\''external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/server/build_info.proto'\'' INCLUDES='\''-I. -Iexternal/io_bazel_rules_closure'\'' bazel-out/host/bin/external/io_bazel_rules_closure/closure/private/gensrcjar'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/com_google_protobuf_protoc/bin/protoc: 1: external/com_google_protobuf_protoc/bin/protoc: cannot create �/@@��: Directory nonexistent
external/com_google_protobuf_protoc/bin/protoc: 1: external/com_google_protobuf_protoc/bin/protoc: ELF: not found
external/com_google_protobuf_protoc/bin/protoc: 2: external/com_google_protobuf_protoc/bin/protoc: Syntax error: ")" unexpected
gensrcjar: proto_compiler failed
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 339.557s, Critical Path: 54.04s
Can anyone help on this?

Thanks.

**Comment by gunan** [comment]
Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
