### ISSUE TITLE
Could a 3.7 alpha wheel of tensorflow be provided on pip?

### ISSUE THREAD

**Issue by kootenpv** [tensorflow/tensorflow#10807]
Python 3.7 alpha exists, I would like to be able to install a wheel. Any idea when tensorflow could be added on pypi for 3.7?

**Comment by aselle** [comment]
This is currently unsupported. You can just try renaming the wheel (which is how we generate our python 3.6 binary). Until Python 3.7 is an actual release (not beta, alpha) we will not support it. You can of course build for it .from source, but that is unsupported.

**Comment by gunan** [comment]
We will not release a 3.7 binary until Python 3.7 is officially released.
Until then, as @aselle suggested you can just rename 3.6 wheel file and install it (except for windows).

**Comment by kootenpv** [comment]
@gunan @aselle Thanks, that worked! I would have never thought python would use a file naming convention to throw an error!
