### ISSUE TITLE
New changes in tf 1.2 and the seq2seq model

### ISSUE THREAD

**Issue by hassanzadeh** [tensorflow/tensorflow#10809]
In the change log it reads: "The strictness described
in the TensorFlow 1.1 release is gone: The first time an RNNCell is used,
it caches its scope. All future uses of the RNNCell will reuse variables from
that same scope."

Based on which the seq2seq model (with UNtied decoder weights) no longer remain untied. Can you confirm that this is addressed? I don't see anywhere in the seq2seq model that this is addressed.

**Comment by tatatodd** [comment]
@hassanzadeh Can you clarify the exact issue you're running into?  E.g. it would help if you could provide a short code example describing your problem.

**Comment by hassanzadeh** [comment]
Thanks, I think I figured out what I was missing. I did not notice the fact that the encoder cell is deep copied  ( through copy.deepcopy).

**Comment by tatatodd** [comment]
Cool, glad you figured things out.  I'll close this out.
