### ISSUE TITLE
TensorBoard Histogram Dashboard link broken

### ISSUE THREAD

**Issue by tibbe** [tensorflow/tensorflow#10803]
The link (https://www.tensorflow.org/get_started/tensorboard_histograms) to the "TensorBoard Histogram Dashboard" documentation is broken (404). If that section is currently in the process of being written perhaps add a dummy page saying so.

**Comment by aselle** [comment]
PTAL @wolffg. Thanks!

**Comment by wolffg** [comment]
This is now fixed.
