### ISSUE TITLE
seq2seq for dynamic length sequences

### ISSUE THREAD

**Issue by hassanzadeh** [tensorflow/tensorflow#10810]
The seq2seq model is based on the static_rnn, what should I do if my sequence lengths is not known?

**Comment by rickyhan** [comment]
You use padding tokens after the end token. Please close this issue because it's a general question

**Comment by hassanzadeh** [comment]
Thanks but padding causes the context (c) to change.

**Comment by Scitator** [comment]
@hassanzadeh I have recently release [dynamic seq2seq model](https://github.com/Scitator/YATS2S), you can try it out.

**Comment by hassanzadeh** [comment]
Thanks

**Comment by rickyhan** [comment]
I believe the 1.0 version seq2seq is based on dynamic_rnn. It uses `raw_rnn` and a symbolic tf.while loop. For more information watch [this talk at TF summit](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=6&ved=0ahUKEwjKv8bP_czUAhWGPT4KHSAqCPkQtwIINjAF&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DRIR_-Xlbp7s&usg=AFQjCNFW6bVrYXBNmMCYCN0rkgh22dD44g&sig2=a3n-hbpEk74jet27OJsa2A)

**Comment by hassanzadeh** [comment]
It's not you can find the code here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py

**Comment by hassanzadeh** [comment]
Unless this is not the latest code.

**Comment by rickyhan** [comment]
You are right it doesn't use raw_rnn because it implements the symbolic while loop here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/seq2seq/python/ops/decoder.py#L278

**Comment by rickyhan** [comment]
You should use the new API instead of legacy_seq2seq.

**Comment by hassanzadeh** [comment]
Thanks, that was what I was missing.

**Comment by aselle** [comment]
Looks like it is resolved, but generally speaking, this would have been a good question for StackOverflow. Thanks!

**Comment by hassanzadeh** [comment]
Thanks.
