### ISSUE TITLE
`tf.Summary` comparison operator overloading?

### ISSUE THREAD

**Issue by martiansideofthemoon** [tensorflow/tensorflow#10812]
So I was trying to use a comparison operation (`>`) with a `tf.Summary` object. It does not throw an error, but the results are incorrect. I couldn't find any help for this on the [official documentation](https://www.tensorflow.org/api_docs/python/tf/Summary/Value).
Here are my logs --> 
```
(Pdb) type(losses[0])
<class 'tensorflow.core.framework.summary_pb2.Summary'>
(Pdb) type(losses[1])
<class 'tensorflow.core.framework.summary_pb2.Summary'>
(Pdb) losses
[value {
  tag: "CTC Loss"
  simple_value: 40.2547607422
}
, value {
  tag: "CTC Loss"
  simple_value: 42.1486358643
}
]
(Pdb) losses[0] > losses[1]
True
```
The objects were created using `tf.Summary(value=[tf.Summary.Value(tag=tag, simple_value=value)])`. What do you think? @dandelionmane ?

**Comment by dandelionmane** [comment]
These are protocol buffer. I have no expectation that the protocol buffer framework will have a > operator defined in a way that is aware of the semantic meaning of summary values. 

It may be that you can find some documentation on the protobuf site that explains how this operator works, if you're really curious. https://developers.google.com/protocol-buffers/docs/reference/python-generated
