### ISSUE TITLE
Tensorflow Android API version 1.2 not in JCenter

### ISSUE THREAD

**Issue by andreas-eberle** [tensorflow/tensorflow#10819]
The freshly released version 1.2 of the tensorflow APIs is not yet fully available in JCenter ( https://bintray.com/google/tensorflow/tensorflow-android/1.2.0). There is a version 1.2.0 but it does not contain any files. 

Can you push these files to the repository?

**Comment by aselle** [comment]
@petewarden, I have no idea if we support this or about JCenter in general. Could you point me to the right direction or right person?

**Comment by andrewharp** [comment]
Shawn has created the listing
<https://bintray.com/google/tensorflow/tensorflow-android/1.2.0> for it, so
I believe he just needs to upload the AAR and pull the switch to make it
the latest version now.

**Comment by andrewharp** [comment]
1.2.0 files for TF Android are now available on JCenter!
