### ISSUE TITLE
TensorFlow C library now available for Windows?

### ISSUE THREAD

**Issue by BowieHsu** [tensorflow/tensorflow#10817]
Does anyone know where  to find the available TensorFlow C library for Windows?
I only get the information about C library on Linux and MacOs.

**Comment by asimshankar** [comment]
You can download this from:
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.2.0.zip

We haven't yet updated the website, but as of the 1.2 release are producing the C library binary artifacts for Windows.

**Comment by BowieHsu** [comment]
many thanks! @asimshankar

**Comment by sebesbal** [comment]
Where can I find the .lib file for this dll?

**Comment by Merlin2013** [comment]
@sebesbal try to create a .lib file from .dll, 
references: https://adrianhenke.wordpress.com/2008/12/05/create-lib-file-from-dll/
you will need to use lib  /MACHINE:X86 or X64 params for different platform.
eg. lib /MACHINE:X86  /def:C:\mypath\mylib.def /OUT:C:\mypath\mylib.lib

**Comment by BowieHsu** [comment]
@sebesbal I compiled GPU version tensorflow lib and dll on windows7 with CUDA8.0 and cudnn5.1, may it help you https://github.com/BowieHsu/Tensorflow-windows-dll

**Comment by nikita-astronaut** [comment]
Can anyone please tell how to compile and run the code that uses windows C tensorflow library? I have MinGW g++ compiler and VS2015 cl compiler. But nothing I try works. Maybe @asimshankar  or @BowieHsu can help? I only need CPU version, simple

**Comment by BowieHsu** [comment]
https://github.com/BowieHsu/Tensorflow-windows-dll/issues/5 check it out.

**Comment by nikita-astronaut** [comment]
@BowieHsu thanks for your response!

I have no problem downloading the library, but I don't understand how to COMPILE with this library using CL VS2015 compiler. Can you please help me with the compilation?

**Comment by Neargye** [comment]
@nikita-astronaut [here examples](https://github.com/Neargye/hello_tf_win_c_api) TensorFlow C API on Windows.
