### ISSUE TITLE
Excessive chatter in VLOG(1)

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#10823]
IMO:  tensorflow/core/framework/op.cc:82 is rather a chatty and specific output to be included at VLOG(1).

Could it be changed to VLOG(2) or better still VLOG(3)

one person's useful output is 100's of peoples noise.

**Comment by byronyi** [comment]
Not in TF team, but I guess there's a reason to name VLOG differently from LOG :)

Jokes aside, you should consider writing some scripts to analyze the VLOG. It's really not for looking into with you bare eyes.

**Comment by vincentvanhoucke** [comment]
I would expect a PR moving it to higher VLOG levels to be swiftly approved.
