### ISSUE TITLE
how to compile tensorflow for sse4.1 sse 4.2, avx, and sycl?

### ISSUE THREAD

**Issue by tiagmoraismorgado** [tensorflow/tensorflow#10820]
how can i compile tensorflow for sse4.1 sse 4.2, avx, and sycl?
is there some guide available online?

**Comment by byronyi** [comment]
For SSE and AVX, just add ` -copt=-msse4.1 -copt=-mavx` to your `bazel build` options. SYCL I believe requires you to manually set the `OpenCL` switch when running `./configure`, but I could be wrong.

**Comment by byronyi** [comment]
Also `-copt=-msse4.2`, but you get the idea.

**Comment by tiagmoraismorgado** [comment]
thank you @byronyi

**Comment by rodburns** [comment]
The following guide will help for SYCL. 
https://www.codeplay.com/products/computesuite/computecpp/guides/how-to-setup-tensorflow-with-computecpp
