### ISSUE TITLE
Constant operator is not appropriate for variable initialize

### ISSUE THREAD

**Issue by fesun** [tensorflow/tensorflow#10824]
Tensorflow uses const tensor to initialize variables(for example ones_initializer, zeros_initializer and some optimizer slot creation), this will prevent `AssignOp `to transfer ownership from rhs to lhs and waster a lot of memory when variable shape is very large(for example sparse model). see #9823 #9742

**Comment by aselle** [comment]
I don't understand the problem. Ones_initializer and zeros_initializer don't store a constant with a bunch of zeros or ones in them. What alternative are you suggesting?

**Comment by fesun** [comment]
@aselle I saw ones_initializer and zeros_initializer have been changed in latest version, I haven't read the latest code carefully. But for v1.0.1, https://github.com/tensorflow/tensorflow/blob/v1.0.1/tensorflow/python/ops/init_ops.py#L62, ones_initializer and zeros_initializer calls constant_op.constant to create constant tensors storing a bunch of ones and zeros inside them. Constant tensors prevent assign op to transfer buffer ownership from input tensor to input variable.

`a = tf.get_variable("BigVar", [1024 * 1024 * 1024], dtype=tf.float32, initializer=tf.zeros_initializer(dtype=tf.float32))` will first create one constant tensor with shape [1024 * 1024 * 1024], then assign it to variable "BigVar", assign op can't transfer buffer ownership from the constant tensor to "BigVar" even it's only used for creating "BigVar" because constant tensor reference count is always greater than 1. This wastes a lot of memory when creating very large variables.
My suggestion is adding operators creating non-constant tensors for one_initializer and zeros_intializer, then assign op could try it's best to avoid memory copy.

**Comment by michaelisard** [comment]
You are right unfortunately that the initializer is making a large constant. @jhseu I see you have been making changes here recently: any thoughts of how to e.g. make it broadcast from a scalar instead?

**Comment by jhseu** [comment]
Yeah, I don't think there's a way to avoid the extra memory usage right now.

It's probably worth having a general broadcasting assign op that matches [XLA's broadcasting semantics](https://www.tensorflow.org/performance/xla/broadcasting). Then the initializer can use a scalar constant.

I'll mark this as contributions welcome.

**Comment by fesun** [comment]
To update, I will try to implement the broadcasting recently.

**Comment by sachinprasadhs** [comment]
Hi, Is your issue resolved? If yes, can you close this issue. Thanks!
