### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by ryanhalabi** [tensorflow/tensorflow#10836]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: win10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: latest from pip
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:  8/5.1
- **GPU model and memory**: Quadro K620
- **Exact command to reproduce**: import tensorflow

### Describe the problem
Have installed CUDA 8 / cuDNN 5.1, get the below error when attempting to import tensorflow.  Have seen other threads on here that all describe this as a $PATH$ issue.  I've ensured the cuDNN/CUDA necessities are in the path and have used @mrry installation check script https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c

it returned 

ERROR: Failed to import the TensorFlow module.

- Python version is 3.5.

- TensorFlow is installed at: c:\users\rhalabi\appdata\local\programs\python\python35\lib\site-packages\tensorflow

- All required DLLs are present. Please open an issue on the
  TensorFlow GitHub page: https://github.com/tensorflow/tensorflow/issues
An exception has occurred, use %tb to see the full traceback.

SystemExit: -1

### Source code / logs

In [4]: import tensorflow
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
c:\users\rhalabi\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     17         try:
---> 18             return importlib.import_module(mname)
     19         except ImportError:

c:\users\rhalabi\appdata\local\programs\python\python35\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127

c:\users\rhalabi\appdata\local\programs\python\python35\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

c:\users\rhalabi\appdata\local\programs\python\python35\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

c:\users\rhalabi\appdata\local\programs\python\python35\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

c:\users\rhalabi\appdata\local\programs\python\python35\lib\importlib\_bootstrap.py in _load_unlocked(spec)

c:\users\rhalabi\appdata\local\programs\python\python35\lib\importlib\_bootstrap.py in module_from_spec(spec)

c:\users\rhalabi\appdata\local\programs\python\python35\lib\importlib\_bootstrap_external.py in create_module(self, spec)

c:\users\rhalabi\appdata\local\programs\python\python35\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
c:\users\rhalabi\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     40     sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 41   from tensorflow.python.pywrap_tensorflow_internal import *
     42   from tensorflow.python.pywrap_tensorflow_internal import __version__

c:\users\rhalabi\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>()
     20             return importlib.import_module('_pywrap_tensorflow_internal')
---> 21     _pywrap_tensorflow_internal = swig_import_helper()
     22     del swig_import_helper

c:\users\rhalabi\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     19         except ImportError:
---> 20             return importlib.import_module('_pywrap_tensorflow_internal')
     21     _pywrap_tensorflow_internal = swig_import_helper()

c:\users\rhalabi\appdata\local\programs\python\python35\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127

ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-4-a649b509054f> in <module>()
----> 1 import tensorflow

c:\users\rhalabi\appdata\local\programs\python\python35\lib\site-packages\tensorflow\__init__.py in <module>()
     22
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26

c:\users\rhalabi\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\__init__.py in <module>()
     47 import numpy as np
     48
---> 49 from tensorflow.python import pywrap_tensorflow
     50
     51 # Protocol buffers

c:\users\rhalabi\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     50 for some common reasons and solutions.  Include the entire stack trace
     51 above this error message when asking for help.""" % traceback.format_exc()
---> 52   raise ImportError(msg)
     53
     54 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "c:\users\rhalabi\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "c:\users\rhalabi\appdata\local\programs\python\python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\rhalabi\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\rhalabi\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\rhalabi\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "c:\users\rhalabi\appdata\local\programs\python\python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

In [5]:

**Comment by printdhruv** [comment]
The @mrry script which you are using to confirm tensor flow installation, do check for both GPU/CPU 
options. Somehow, your Cuda isn't configured correctly. 

- I think I would suggest looking over [https://www.stackoverflow.com/questions/42011070/on-windows-running-import-tensorflow-generates-no-module-named-pywrap-tenso](url)

- Also, you may try first with the CPU only option on Windows from scratch than trying to jump on GPU if you like?

**Comment by ryanhalabi** [comment]
it's working!  The steps I took were to
-re-download and reinstall CUDA 8.0 x86_64,  cuDNN v5.1 for CUDA 8.0.  
-created a separate virtual env to install tensorflow gpu in

**Comment by ryanhalabi** [comment]
bad news, reinstalled my computer and now the same exact issue is back...

**Comment by printdhruv** [comment]
Hi,
     Can you elobrate more what steps you took? Before it was working and now it stopped ?

**Comment by ryanhalabi** [comment]
I've solved the problem.  Every time I installed CUDA, my 2nd monitor (plugged into a GTX 330) would stop working but tensorflow-gpu would work.

After this I would try to get the 2nd monitor to work by updating its driver which would then cause importing tensorflow to fail.  Looks like tensorflow doesn't play well with this GPU, probably cause its so old.

**Comment by printdhruv** [comment]
- As a suggestion I would say that clearly, windows approach is highly experimental hence if you can dual boot Ubuntu than would be so easy to get the best out of Tensor flow even with Two GPU.

- Alienware laptops come up with an external graphic amplifier port where you can put 1,2,4.. external graphic cards which currently I am using.
