### ISSUE TITLE
Missing variable on MNIST tutorial

### ISSUE THREAD

**Issue by LecJackS** [tensorflow/tensorflow#1084]
I'm writing this here because I can't find a better way to contact someone about this.

In short, first Tensorflow tutorial about MNIST:
https://www.tensorflow.org/versions/v0.6.0/tutorials/mnist/beginners/index.html#the-mnist-data

First piece of code:
```
import tensorflow.examples.tutorials.mnist.input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True) 
```

where it should be:
```
import tensorflow.examples.tutorials.mnist.input_data as input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True) 
```
**"as input_data"** is missing, so when running the second line of code, python doesn't know whats input_data.whatever.

Hope someone can edit that, because it's a begginer tutorial, and can be very frustrating to fail running the very first piece of code of the first and most basic tutorial.

**Comment by vrv** [comment]
Checked in the change to our docs for version 0.6.0 (it was fixed in master).  We'll push the website this upcoming week hopefully as part of our next release.  Thanks for the report.
