### ISSUE TITLE
Compiling tensorflow fails with error: no matching function for call to 'Permute(tensorflow::gtl::ArraySlice<long long int>&, const std::vector<llvm::Value*, std::allocator<llvm::Value*> >&)'

### ISSUE THREAD

**Issue by svenstaro** [tensorflow/tensorflow#10843]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch Linux
- **TensorFlow installed from (source or binary)**: Trying to compile from source
- **TensorFlow version (use command below)**: 1.2.0 release
- **Bazel version (if compiling from source)**: 0.5.1
- **CUDA/cuDNN version**: 8.0.61/6.0.21
- **GPU model and memory**: 1080 Ti 11 GB
- **Exact command to reproduce**: The PKGBUILD https://paste.xinu.at/XaChkb/
If you are not familiar with this format, basically just execute `prepare()` and then `build()`.

### Describe the problem
I'm the packager for the official tensorflow package in Arch Linux and I was trying to update 1.1.0 to 1.2.0 and it fails to build. Full build log attached. We always build in clean chroots.

llvm 4.0, gcc 7.1.1

### Source code / logs
[log.txt](https://github.com/tensorflow/tensorflow/files/1087523/log.txt)

**Comment by tatatodd** [comment]
@svenstaro It seems that the version of gcc you're using doesn't support the same template argument deduction that we get with the version that we're using:

```
ERROR: /build/tensorflow/src/tensorflow-1.2.0/tensorflow/compiler/xla/service/llvm_ir/BUILD:60:1: C++ compilation of rule '//tensorflow/compiler/xla/service/llvm_ir:ir_array' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 133 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
tensorflow/compiler/xla/service/llvm_ir/ir_array.cc: In member function 'xla::llvm_ir::IrArray::Index xla::llvm_ir::IrArray::Index::SourceIndexOfTranspose(const xla::Shape&, const xla::Shape&, tensorflow::gtl::ArraySlice<long long int>, llvm::IRBuilder<>*) const':
tensorflow/compiler/xla/service/llvm_ir/ir_array.cc:161:44: error: no matching function for call to 'Permute(tensorflow::gtl::ArraySlice<long long int>&, const std::vector<llvm::Value*, std::allocator<llvm::Value*> >&)'
       Permute(dimension_mapping, multidim());
                                            ^
In file included from tensorflow/compiler/xla/service/llvm_ir/ir_array.cc:24:0:
./tensorflow/compiler/xla/util.h:197:16: note: candidate: template<template<class ...> class C, class T> std::vector<T> xla::Permute(tensorflow::gtl::ArraySlice<long long int>, C<T>)
 std::vector<T> Permute(tensorflow::gtl::ArraySlice<int64> permutation,
                ^~~~~~~
./tensorflow/compiler/xla/util.h:197:16: note:   template argument deduction/substitution failed:
tensorflow/compiler/xla/service/llvm_ir/ir_array.cc:161:44: note:   candidate expects 1 argument, 2 provided
       Permute(dimension_mapping, multidim());
                                            ^
tensorflow/compiler/xla/service/llvm_ir/ir_array.cc:161:44: note:   candidate expects 1 argument, 2 provided
tensorflow/compiler/xla/service/llvm_ir/ir_array.cc:161:44: note:   'std::vector<llvm::Value*, std::allocator<llvm::Value*> >' is not derived from 'C<T>'
```

A possible (untested) fix is to change this line:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/llvm_ir/ir_array.cc#L161

from:
```
  std::vector<llvm::Value*> operand_multidim_index =
      Permute(dimension_mapping, multidim());
```

to:
```
  std::vector<llvm::Value*> operand_multidim_index =
      Permute<std::vector, llvm::Value*>(dimension_mapping, multidim());
```

Can you try that out to see if it fixes things?  And if it works, would you mind creating a PR for this fix?  I'm suggesting this route since it'll ensure it actually fixes the problem for you.  Thanks!

**Comment by svenstaro** [comment]
Sorry but could you provide a patch?

**Comment by tatatodd** [comment]
@svenstaro Can you try PR #10868, which has the change I outlined above?

**Comment by svenstaro** [comment]
Doesn't work, there seem to be other places where the same problem occurs. Full build log: 
[log.txt](https://github.com/tensorflow/tensorflow/files/1092836/log.txt)

**Comment by tatatodd** [comment]
@svenstaro Can you give the latest version of PR #10868 another try?

**Comment by svenstaro** [comment]
Yep, that one works fine!

**Comment by tatatodd** [comment]
Cool, PR #10868 has been merged and should fix this issue.
