### ISSUE TITLE
Differentiate Variable (Model Parameters) and Mutable Tensor

### ISSUE THREAD

**Issue by melvinma** [tensorflow/tensorflow#10855]
In the current tensorflow, the concept of variables is about same as model parameters and mutable tensors. I would like to see them separate out. For example, it seems perfect legit to me to use tf.scatter_nd_update to update a tensor. However all scatter APIs require "mutable tensor". That made operations on tensors with "batch" parameter close to impossible.  Having the concept of mutable tensor will help a lot.

**Comment by tatatodd** [comment]
@melvinma I think you might have a misunderstanding about variables.  From the documentation:

```
Variables are in-memory buffers containing tensors.
```

Here are some links to further reading.
https://www.tensorflow.org/versions/master/programmers_guide/variables
https://www.tensorflow.org/versions/master/api_docs/python/tf/Variable
https://www.tensorflow.org/versions/master/api_guides/python/state_ops#Variables

Note that this question is better suited for stackoverflow; we use github for tracking bugs and feature requests.  If you have further questions about variables, please ask them on stackoverflow.  Thanks!
