### ISSUE TITLE
Mismatched delete in mkl_tfconv_op.cc

### ISSUE THREAD

**Issue by maddin200** [tensorflow/tensorflow#10853]
tensorflow\core\kernels\mkl_tfconv_op.cc line 120
delete in_sizes;

should be: delete [] in_sizes;

**Comment by tatatodd** [comment]
@maddin200 Thanks for filing the bug, you're right.  Would you like to submit a PR to fix this?  Thanks!

**Comment by maddin200** [comment]
Better somebody more familiar with the code will do the change.

**Comment by yongtang** [comment]
Added PR #10955 for the fix.
