### ISSUE TITLE
control_dependencies possibly broken

### ISSUE THREAD

**Issue by yaringal** [tensorflow/tensorflow#10860]
Hi all, I've been playing with control_dependencies in the latest stable version, and I get different results to version 1.0.1. The code below is adapted from the TF Adam optimiser, which might be affected as well.

The code I ran is
```
import tensorflow as tf
import numpy as np

graph = tf.Graph()

with graph.as_default():
    x = tf.Variable(1.0, dtype=tf.float32, name='x')    
    y = tf.Variable(10., dtype=tf.float32, name='y')
    update_x = tf.assign(x, y)
    with tf.control_dependencies([update_x]):
        update_y = tf.assign(y, x * y)
    update_op = tf.group(update_x, update_y)
    init_op = tf.global_variables_initializer()
print tf.__version__

res = []
for _ in range(10):
    if 'sess' in locals():
        locals()['sess'].close()
    if 'sess' in globals():
        globals()['sess'].close()

    sess = tf.Session(graph=graph)
    sess.run(init_op)
    res += [sess.run([update_op, x, y])]
print np.mean([r[-1] for r in res])
print np.mean([r[-2] for r in res])
```

And get results 
```
1.0.1
100.0
10.0
```
vs
```
1.2.0
28.0
5.5
```
suggesting that the control dependencies are not used as expected in version 1.2.0. 
Can anyone spot any mistakes in the way I use the control dependencies?
Cheers,
Yarin

**Comment by ppwwyyxx** [comment]
You evaluate update_op, x and y with sess.run. And there is no guarantee that x and y should be evaluated before or after update_op. Therefore the program is expected to give you random results.

**Comment by yaringal** [comment]
changing the code above to
```
    sess.run(update_op)
    res += [sess.run([x, y])]
```
does indeed result in 
```
1.2.0
100.0
10.0
```
as expected. Is this intended behaviour? (the execution order of the list of ops changing randomly with each call)

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
