### ISSUE TITLE
Splitting model and using threads.

### ISSUE THREAD

**Issue by abhi-rf** [tensorflow/tensorflow#10873]
Hello everyone. I am new to tensorflow and had a doubt. How can I split a pre trained model into two parts and then load it onto the GPU simultaneously using different threads ? Is it possible, if yes, please guide me for the same. Thanks :) :)

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
