### ISSUE TITLE
how do i retrain net after quantization?

### ISSUE THREAD

**Issue by xzj6795365** [tensorflow/tensorflow#10875]
i had used tensorflow tool, quantization_graph.py, to quantize my graph successfully. how do i retrain this net after quantization? since the tool requires using freeze_graph.py to convert variables in graph to constant. 

BTW, can i set up my graph using quantize ops, and train from the scratch? if can, is there any example?

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
