### ISSUE TITLE
[win7-64bit,Anaconda,tensorflow 1.2.0,chrome]Tensorboard : No scalar was found 

### ISSUE THREAD

**Issue by cnzjhdx** [tensorflow/tensorflow#10872]
I can't see any data. It turned out to be : No scalar

 was found 

when I run the tensorboard ,there is no error or warning

**Environment info**

Windows 7 64-bit
Anaconda Python 3.5
Tensoflow installed from binary pip package
tensorflow version:1.2.0
Browser: Chrome 58

**About the code**

I just run the example code mnist_with_summries.py

it is in D:\Anaconda\Lib\site-packages\tensorflow\examples\tutorials\mnist\mnist_with_summaries.py

**What have you tried?**

I can see a log file called events.out.tfevents.*  in the folder I set. The file is about 16Mb big.

I call tensorboard --logdir=/tmp/tensorflow/mnist/logs/mnist_with_summaries --debug and I can verify the log dir is correct.

On the browser I can't see any data or graph is shown.

If I call tensorboard --inspect --logdir=/tmp/tensorflow/mnist/logs/mnist_with_summaries  It shows how  the tfevent file contains.

**Comment by ali01** [comment]
This is a question better asked on the tensorboard repository:
https://github.com/tensorflow/tensorboard/issues
