### ISSUE TITLE
IOS Expected namespace tensorflow::ops

### ISSUE THREAD

**Issue by JcmeLs** [tensorflow/tensorflow#10888]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
    No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
    OS X 10.11.6
- **TensorFlow installed from (source or binary)**:
    binary(pip install)
- **TensorFlow version (use command below)**:
    1.1.0 CPU Only
- **Bazel version (if compiling from source)**:
    0.4.5

### Describe the problem
I want to use pb file in IOS.And I must use `tensorflow::ops::reshape` and ` tensorflow::ops::argmax ` api.But when I add ` using namespace tensorflow::ops; `I get a error --` Expected namespace name `.My TensorFlow-experimental come from Pod.  
How to add namespace tensorflow::ops...

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
