### ISSUE TITLE
 C++ compilation of rule '//tensorflow/python:tf_session_helper' failed

### ISSUE THREAD

**Issue by markusdr** [tensorflow/tensorflow#109]
I am trying to compile build_pip_package on Ubuntu 12.04 with gcc 4.8, but it gives an error during compilation:

    $ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures

    tensorflow/python/client/tf_session_helper.cc:418:41: error: 'PyArray_SHAPE' was not declared in this scope
       dims.push_back(PyArray_SHAPE(array)[i]);

    ERROR: /home/local/ANT/x/tensorflow/tensorflow/python/BUILD:666:1: C++ compilation of rule '//tensorflow/python:tf_session_helper' failed: gcc failed: error executing command 
      (cd /home/local/ANT/x/.cache/bazel/_bazel_x/29843df2d2b24eaae7acd7ee881b7bec/tensorflow && \
      exec env - \
        INTERCEPT_LOCALLY_EXECUTABLE=1 \
        PATH=/home/local/ANT/x/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin \
      /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -iquote . -iquote bazel-out/local_linux-opt/genfiles -isystem google/protobuf/src -isystem bazel-out/local_linux-opt/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-opt/genfiles/external/re2 -isystem third_party/gpus/cuda -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda -isystem third_party/gpus/cuda/include -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda/include -isystem third_party/eigen3 -isystem bazel-out/local_linux-opt/genfiles/third_party/eigen3 -I/usr/include/python2.7 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-opt/bin/tensorflow/python/_objs/tf_session_helper/tensorflow/python/client/tf_session_helper.pic.o' -MD -MF bazel-out/local_linux-opt/bin/tensorflow/python/_objs/tf_session_helper/tensorflow/python/client/tf_session_helper.pic.d -fPIC -c tensorflow/python/client/tf_session_helper.cc -o bazel-out/local_linux-opt/bin/tensorflow/python/_objs/tf_session_helper/tensorflow/python/client/tf_session_helper.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: gcc failed: error executing command 
      (cd /home/local/ANT/x/.cache/bazel/_bazel_x/29843df2d2b24eaae7acd7ee881b7bec/tensorflow && \
      exec env - \
        INTERCEPT_LOCALLY_EXECUTABLE=1 \
        PATH=/home/local/ANT/x/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin:/home/local/ANT/x/bin \
      /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -iquote . -iquote bazel-out/local_linux-opt/genfiles -isystem google/protobuf/src -isystem bazel-out/local_linux-opt/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-opt/genfiles/external/re2 -isystem third_party/gpus/cuda -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda -isystem third_party/gpus/cuda/include -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda/include -isystem third_party/eigen3 -isystem bazel-out/local_linux-opt/genfiles/third_party/eigen3 -I/usr/include/python2.7 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-opt/bin/tensorflow/python/_objs/tf_session_helper/tensorflow/python/client/tf_session_helper.pic.o' -MD -MF bazel-out/local_linux-opt/bin/tensorflow/python/_objs/tf_session_helper/tensorflow/python/client/tf_session_helper.pic.d -fPIC -c tensorflow/python/client/tf_session_helper.cc -o bazel-out/local_linux-opt/bin/tensorflow/python/_objs/tf_session_helper/tensorflow/python/client/tf_session_helper.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    Target //tensorflow/tools/pip_package:build_pip_package failed to build
    INFO: Elapsed time: 3.223s, Critical Path: 2.46s

**Comment by markusdr** [comment]
I can compile that particular source file after adding this to the gcc command:

    -I/usr/local/lib/python2.7/dist-packages/numpy/core/include/

But when I rerun the bazel command it tries to compile it again without the needed include path and fails.

**Comment by vrv** [comment]
@markusdr: what version of numpy do you have installed, by any chance?  I have a suspicion that it's probably earlier than numpy 1.8.2 :)

**Comment by markusdr** [comment]
I believe it's numpy 1.9.2.

**Comment by vrv** [comment]
Gotcha -- that version does have PyArray_SHAPE.  Do you have any other numpy directories installed on your machine that might be interfering somehow?

If not, can you try changing tf_session_helper.cc to switch from PyArray_SHAPE to PyArray_DIMS ? (That one is available in earlier versions of numpy and apparently PyArray_SHAPE is an alias)

**Comment by markusdr** [comment]
Right, the installation is using /usr/include/python2.7/, which doesntt have PyArray_SHAPE. 

It is defined in /usr/**local**/lib/python2.7/dist-packages/numpy/core/include.

How can I tell bazel to use the latter python installation path?

**Comment by markusdr** [comment]
When I add the correct numpy include path to the tensorflow/python/BUILD file it seems to compile, but at the end it complains:

    $ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package 
    tensorflow/python/BUILD:666:1: in cc_library rule //tensorflow/python:tf_session_helper: 
    The include path '/usr/local/lib/python2.7/dist-packages/numpy/core/include' references 
    a path outside of the execution root..

**Comment by markusdr** [comment]
OK, this workaround gets it to compile:

    cd third_party
    ln -s /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy .

Then add `-Ithird_party` to the includes in `tensorflow/python/BUILD` and `tensorflow/tensorflow.bzl`

**Comment by ebrevdo** [comment]
There may be a way to infer the numpy header  location at compile time. I'll take a look.

**Comment by auroua** [comment]
@markusdr 
how to add -Ithird_part to ```tensorflow/python/BUILD``` and ```tensorflow/tensorflow.bzl```
thanks

**Comment by markusdr** [comment]
@auroua Here is the diff:

    diff --git a/tensorflow/python/BUILD b/tensorflow/python/BUILD
    -    copts = numpy_macosx_include_dir + ["-I/usr/include/python2.7"],
    +    copts = numpy_macosx_include_dir + ["-Ithird_party", "-I/usr/include/python2.7"],

    diff --git a/tensorflow/tensorflow.bzl b/tensorflow/tensorflow.bzl
    -                    ] + ["-I/usr/include/python2.7"],
    +                    ] + ["-Ithird_party", "-I/usr/include/python2.7"],

Alternatively, I could have symlinked `/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy` into `/usr/include/python2.7`, but I didn't have root access.

**Comment by auroua** [comment]
@markusdr 
I have a problem in #251. Can you help me to solve this problems.
I tried you method but it not working.
thanks

**Comment by noisychannel** [comment]
Does @markusdr 's changes still apply? I don't think that the diff corresponds to the current version of tensorflow/python/BUILD anymore. Suggestions?

**Comment by noisychannel** [comment]
Symlinking the numpy headers in util/python worked for me. python_config took care of the rest.

**Comment by vrv** [comment]
If you sync to HEAD you should be able to use ./configure to select which python to use.

**Comment by noisychannel** [comment]
@vrv Is configure auto detecting the location of numpy headers now (from distconfig possibly?). If not, this issue will still exist.

**Comment by vrv** [comment]
I believe so:  ./configure will call python_config.sh (https://github.com/tensorflow/tensorflow/blob/master/configure#L25) which gets the numpy headers from https://github.com/tensorflow/tensorflow/blob/master/util/python/python_config.sh#L64

**Comment by noisychannel** [comment]
Confirmed. python_config auto detects the location of numpy. None of the changes suggested in this thread are needed anymore as long as python has access to the correct numpy location. Thanks, @vrv.
