### ISSUE TITLE
Feature Request for BitwiseXOR for Tensor

### ISSUE THREAD

**Issue by yylonly** [tensorflow/tensorflow#10953]
My project requests a new layer, which needs the new operator of Tensor to compute bitwiseXOR between input x and constant Key k.
E.g. x = 4 (bit form: 100), k = 7 (111), the bitwiseXOR(x, k) expects as 3 (011).

As far as I know, Tensor only has LogicXOR operator for bool type. Luckily, Tensorflow has the extended ability to have a new Op. However, I read the document in https://www.tensorflow.org/extend/adding_an_op, I can get the basic idea, but that is far from the implementation, maybe because of the lack of c++ knowledge. If you guys could help to implement the new operator that will be helpful. Then I can use that new Op of Tensor to build the new layers.

**Comment by asimshankar** [comment]
The bitwise ops were added recently and will be integrated when PR https://github.com/tensorflow/tensorflow/pull/10859 is merged in (specifically commit https://github.com/tensorflow/tensorflow/pull/10859/commits/a94a333762b4d2c3fcae0a9e610d654bba6980de).

Once that is merged, you should have these available if you build from sources and in the next release.

**Comment by lakshayg** [comment]
I would like to take up this issue if TensorFlow devs decide to incorporate this in the library.
