### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.tensorboard.tensorboard'

### ISSUE THREAD

**Issue by captify-alazorenko** [tensorflow/tensorflow#10959]
Tensorboard not working on Tensorflow built from sources

### System information
- **Linux Ubuntu 16.04**
- **TensorFlow installed from sources using Bazel**
- **TensorFlow version v1.2.0-1126-gb7acb6a**
- **Bazel version 0.51**
- **CUDA/cuDNN version 8.0/6.0**
- **Found device 0 with properties: 
name: GeForce GTX 1070
major: 6 minor: 1 memoryClockRate (GHz) 1.683
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 5.15GiB**
- **Exact command to reproduce**: `$ tensorboard`
Installed into fresh anaconda3 environment 'tensorflow', environment is activated when performing command.
### Source code / logs
```
$ tensorboard
Traceback (most recent call last):
  File "/home/gpu/anaconda3/envs/tensorflow/bin/tensorboard", line 7, in <module>
    from tensorflow.tensorboard.tensorboard import main
ModuleNotFoundError: No module named 'tensorflow.tensorboard.tensorboard'
```

**Comment by tatatodd** [comment]
@captify-alazorenko It sounds like there's some problem with your installation.  How exactly did you install from sources?

Perhaps you can try this:
```
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> tensorflow
<module 'tensorflow' from '/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.pyc'>
>>> quit()
$ ls /usr/local/lib/python2.7/dist-packages/tensorflow 
__init__.py   contrib  examples  python       tools
__init__.pyc  core     include   tensorboard
```

The idea is to figure out where your tensorflow installation is, and see whether it makes sense.  You might be able to debug more depending on what you find there.

**Comment by StevenLOL** [comment]
I got same problem, installed via whl

```
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> tensorflow
<module 'tensorflow' from '/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.pyc'>
>>> exit()
steven@ubuntu-1080:/data/gits/models/adversarial_text/models$ ls /usr/local/lib/python2.7/dist-packages/tensorflow/
contrib  core  examples  include  __init__.py  __init__.pyc  python  tensorboard  tools

```

**Comment by captify-alazorenko** [comment]
I installed from sources using the guide on tensorflow page. More specifically, after configuring tensorflow, I executed the following:

```
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
cd /tmp/tensorflow_pkg
pip install /tmp/tensorflow_pkg/tensorflow-1.2.0-cp36-cp36m-linux_x86_64.whl
```
I also attach the results of aforementioned command:
```
(tensorflow) gpu@gpuserver:/tmp/tensorflow_pkg$ python
Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> tensorflow
<module 'tensorflow' from '/home/gpu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/__init__.py'>
>>> quit()
(tensorflow) gpu@gpuserver:/tmp/tensorflow_pkg$ ls /home/gpu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow
contrib  examples  __init__.py  python       tools
core     include   __pycache__  tensorboard
```

**Comment by tatatodd** [comment]
@dandelionmane Do you have any ideas on what might be going wrong here?

**Comment by dandelionmane** [comment]
We took TensorBoard out of the TensorFlow repo and into http://github.com/tensorflow/tensorboard.

So it's expected that attempting to build or depend on TensorBoard source from the TF repo won't work.

Ah, but if the pip command is broken, I should look into that.

**Comment by dandelionmane** [comment]
Ok, I installed tensorflow via pip from the nightly, and tensorboard works fine.

Generally speaking, it's not expected that running tensorflow/tensorboard/tensorboard will work if you install the TF repo, since TensorBoard has moved out. I'm going to close this as WAI, and scrub the docs for referneces to doing this.

**Comment by jcomfort4** [comment]
cc: @dandelionmane 

I am having issues with tensorboard when I updated to 1.3 this morning. I ran the following command from my conda environment based on the suggestions [here](https://www.tensorflow.org/install/install_mac).

`pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.3.0-py2-none-any.whl`

However, when I try to run tensorboard '`python -m tensorflow.tensorboard --logdir=$MODEL_DIR`' I am getting the error 'No module named tensorflow.tensorboard'.

Further, if I look in my tensorflow package, I am not seeing tensorboard.

```
ls /Users/username/anaconda/envs/tensorflow-cloud/lib/python2.7/site-packages/tensorflow
__init__.py	contrib		examples	python
__init__.pyc	core		include		tools
```
This seems like the pip command is not working anymore, unless I am doing something wrong here?

Thanks!

**Comment by jcomfort4** [comment]
Also, looking back at the logs it does look like the pip package collected and isntalled tensorflow-tensorboard but somehow it seems to not be getting placed in the proper place (likely a conflict with conda?): 

```
Collecting setuptools (from protobuf>=3.3.0->tensorflow==1.3.0)
  Using cached setuptools-36.2.7-py2.py3-none-any.whl
Installing collected packages: funcsigs, pbr, six, mock, setuptools, protobuf, html5lib, bleach, numpy, wheel, markdown, werkzeug, tensorflow-tensorboard, backports.weakref, tensorflow
Successfully installed backports.weakref-1.0rc1 bleach-1.5.0 funcsigs-1.0.2 html5lib-0.9999999 markdown-2.6.9 mock-2.0.0 numpy-1.13.1 pbr-3.1.1 protobuf-3.4.0 setuptools-36.2.7 six-1.10.0 tensorflow-1.3.0 tensorflow-tensorboard-0.1.4 werkzeug-0.12.2 wheel-0.29.0
```

Thanks for any advice you can provide.

**Comment by jcomfort4** [comment]
For anybody else finding this issue, since tensorboard was split out from tensorflow the command to run is just `tensorboard --logdir=$MODEL_DIR` instead of `python -m tensorflow.tensorboard --logdir=$MODEL_DIR` as it was previously.

**Comment by bryanlimy** [comment]
Running `tensorboard --logdir=$MODEL_DIR` works for me but not `python -m tensorflow.tensorboard --logdir=$MODEL_DIR`. Intalled TF 1.3.0 throught `pip install --upgrade tensorflow-gpu`.

**Comment by phi-dbq** [comment]
Would you please update the documentation https://www.tensorflow.org/get_started/summaries_and_tensorboard 
to reflect this change? 
It still states that we can use `python -m tensorflow.tensorboard --logdir=$MODEL_DIR` to launch TensorBoard.

**Comment by vossthor** [comment]
Windows users might want to check out these two batch lines:
```
cd C:/Users/$USERNAME/AppData/Local/Programs/Python/Python35/Scripts/
tensorboard.exe --logdir=$MODEL_DIR
```

**Comment by GalMoore** [comment]
Thanks @jcomfort4. After Cloud SDK update 171.0.0 I had the same issue. Solved with 
`tensorboard --logdir=output` as replacement for: `python -m tensorflow.tensorboard --logdir=output`. Please update https://cloud.google.com/ml-engine/docs/how-tos/getting-started-training-prediction

**Comment by monajalal** [comment]
getting this error:

```
Mon Nov 13 00:11:49 :~$ sudo pip install tensorboard
Password:
The directory '/Users/mona/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/mona/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting tensorboard
  Downloading tensorboard-1.0.0a6-cp27-cp27m-macosx_10_12_x86_64.whl (10.8MB)
    100% |████████████████████████████████| 10.8MB 94kB/s
Collecting numpy>=1.11.0 (from tensorboard)
  Downloading numpy-1.13.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.6MB)
    100% |████████████████████████████████| 4.6MB 139kB/s
Collecting mock>=2.0.0 (from tensorboard)
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 2.1MB/s
Requirement already satisfied: wheel in /Library/Python/2.7/site-packages (from tensorboard)
Collecting protobuf>=3.1.0 (from tensorboard)
  Downloading protobuf-3.4.0-py2.py3-none-any.whl (375kB)
    100% |████████████████████████████████| 378kB 1.0MB/s
Collecting Pillow>=4.0.0 (from tensorboard)
  Downloading Pillow-4.3.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.5MB)
    100% |████████████████████████████████| 3.6MB 159kB/s
Requirement already satisfied: six>=1.10.0 in /Library/Python/2.7/site-packages (from tensorboard)
Collecting werkzeug>=0.11.10 (from tensorboard)
  Downloading Werkzeug-0.12.2-py2.py3-none-any.whl (312kB)
    100% |████████████████████████████████| 317kB 1.2MB/s
Requirement already satisfied: pbr>=0.11 in /Library/Python/2.7/site-packages (from mock>=2.0.0->tensorboard)
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->tensorboard)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./Library/Python/2.7/lib/python/site-packages (from protobuf>=3.1.0->tensorboard)
Collecting olefile (from Pillow>=4.0.0->tensorboard)
  Downloading olefile-0.44.zip (74kB)
    100% |████████████████████████████████| 81kB 1.9MB/s
Requirement already satisfied: packaging>=16.8 in /Library/Python/2.7/site-packages (from setuptools->protobuf>=3.1.0->tensorboard)
Requirement already satisfied: appdirs>=1.4.0 in /Library/Python/2.7/site-packages (from setuptools->protobuf>=3.1.0->tensorboard)
Requirement already satisfied: pyparsing in ./Library/Python/2.7/lib/python/site-packages (from packaging>=16.8->setuptools->protobuf>=3.1.0->tensorboard)
Installing collected packages: numpy, funcsigs, mock, protobuf, olefile, Pillow, werkzeug, tensorboard
  Found existing installation: numpy 1.8.0
    Uninstalling numpy-1.8.0:
      Successfully uninstalled numpy-1.8.0
  Found existing installation: mock 1.3.0
    Uninstalling mock-1.3.0:
      Successfully uninstalled mock-1.3.0
  Running setup.py install for olefile ... done
  Found existing installation: Pillow 2.9.0
    Uninstalling Pillow-2.9.0:
      Successfully uninstalled Pillow-2.9.0
  Found existing installation: Werkzeug 0.10.4
    Uninstalling Werkzeug-0.10.4:
      Successfully uninstalled Werkzeug-0.10.4
Successfully installed Pillow-4.3.0 funcsigs-1.0.2 mock-2.0.0 numpy-1.13.3 olefile-0.44 protobuf-3.4.0 tensorboard-1.0.0a6 werkzeug-0.12.2
Mon Nov 13 00:19:57 :~$ tensorboard --logdir=/var/folders/bk/2b2d879912bgnl5s768s7crh0000gn/T/tmpzy0cj6xc
Traceback (most recent call last):
  File "/Users/mona/anaconda/bin/tensorboard", line 4, in <module>
    import tensorflow.tensorboard.tensorboard
ModuleNotFoundError: No module named 'tensorflow.tensorboard'
Mon Nov 13 00:22:01 :~$
```

**Comment by YouYueHuang** [comment]
I use python -m `tensorflow.tensorboard --logdir=output` and it works.
But `tensorboard --logdir=output` showed ModuleNotFound error

**Comment by alinawazT** [comment]
"conda install -c anaconda tensorflow-tensorboard" in cmd solve my this problem for anaconda notebook

**Comment by aransil** [comment]
I've been getting the same set of errors

Using macOSX Sierra, and spyder with a tensorflow environment installed through conda.

Anaconda navigator says that tensorboard is installed in _both_ the base and tensorflow environments, and there are two tensorboard executables: one in /anaconda3/bin and the other in /anaconda3/envs/tensorflow/bin. Just running either of these files on its own gives two different errors. The base tensorboard file gives: 
**ModuleNotFoundError: No module named 'tensorflow'** 

The tensorflow env version gives:
**ValueError: A logdir must be specified when db is not specified. Run `tensorboard --help` for details and examples.**

Trying to run some of the above suggested fixes from the terminal gives the following
python -m tensorflow.tensorboard
**/anaconda3/bin/python: Error while finding module specification for 'tensorflow.tensorboard' (ModuleNotFoundError: No module named 'tensorflow')**

tensorboard
**ModuleNotFoundError: No module named 'tensorflow'**

As a workaround, on my configuration I can run the tensorflow env tensorboard file from the terminal:
/anaconda3/envs/tensorflow/bin/tensorboard --logdir=path

I hope that helps anyone struggling with the same issue. Taking tensorboard out of tensorflow seems to have caused a problem with the conda install (at least if you use multiple environments) that isn't fixed yet.
