### ISSUE TITLE
Cannnot convert Graphs/Models via DarkFlow

### ISSUE THREAD

**Issue by anonym24** [tensorflow/tensorflow#10952]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/DetectorActivity.java#L69
> // ./flow --model cfg/tiny-yolo-voc.cfg --load bin/tiny-yolo-voc.weights --savepb --verbalise=True

I already reported about this on **darkflow** git https://github.com/thtrieu/darkflow/issues/295 but still didn't get any reply

I shows next error:

`ERROR - Invalid argument: --verbalise=True`

**Comment by abagshaw** [comment]
This issue can be closed as it is not related to tensorflow, but to how CLI arguments are handled in darkflow.

**Comment by anonym24** [comment]
solved

**Comment by patrick-ucr** [comment]
May I ask how you solved the issue? I am having the same now.

**Comment by anonym24** [comment]
@patrick-ucr --verbalise true
