### ISSUE TITLE
tf.TensorArray.stack(name="aname") bug

### ISSUE THREAD

**Issue by melvinma** [tensorflow/tensorflow#10963]
### System information
- **Code + Interpreter**: Notice the print out is "stackme/stackme:0" instead of "stackme:0".
This is a really minor error. But I had spent at least half an hour wondering why my operation was called twice. Would be really nice to be fixed :)

```
imemory = tf.TensorArray(tf.float32, size=0, dynamic_size=True, name="memory")
imemory.write(0, tf.constant(0))
imemory = imemory.write(0, tf.constant(0))
imemory = imemory.write(1, tf.constant(1))
imemory = imemory.write(2, tf.constant(2))
result = imemory.stack(name="stackme")
print(result)

<print out>Tensor("stackme/stackme:0", shape=(?,), dtype=float32)

```

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
v1.1.0-rc0-61-g1ec6ed5 1.1.0

**Comment by tatatodd** [comment]
@melvinma Thanks for the very clear issue including all necessary info!

I believe this is working-as-intended.  Note that when you call `TensorArray.stack`, more than one operation gets added to the graph.  Thus the `name=stackme` you're passing in is used both as a name scope for all of the operations, as well as the name of the last operation.

The behavior may be more clear if you try removing the name:
```
imemory = tf.TensorArray(tf.float32, size=0, dynamic_size=True, name="memory")
result = imemory.stack()
print(result)

<output> Tensor("TensorArrayStack/TensorArrayGatherV3:0", dtype=float32)
```

Here the first component `TensorArrayStack` is the name scope for all operations, and the second component `TensorArrayGatherV3` is the name of the last operation.
