### ISSUE TITLE
TensorFlow 1.2.0 update still not supporting Python 3.6.1 on Windows 10

### ISSUE THREAD

**Issue by Shanky2304** [tensorflow/tensorflow#10971]
### System information
- **Windows 10 (64-bit)**
- **Python 3.6.1**

Even with the new update the command:

`pip install tensorflow_gpu-1.2.0-cp36-cp36m-win_amd64.whl` 

OR as in the official documentation

`pip3 install --upgrade tensorflow`

returns

> tensorflow_gpu-1.2.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

AND

> Could not find a version that satisfies the requirement tensorflow (from versions: )
> No matching distribution found for tensorflow

respectively.

**Comment by mrry** [comment]
What output do you get when you run `pip --version` and `pip3 --version`?

**Comment by Shanky2304** [comment]
Looks like I had the 32-bit version of Python 3.6.1.
My sincere apologies.

**Comment by mrry** [comment]
Don't worry about it - thanks for confirming!
