### ISSUE TITLE
tensorflow-0.6.0-cp34-none-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by vladalonso** [tensorflow/tensorflow#1097]
INSTALLATION ERROR:
$ sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp34-none-linux_x86_64.whl
sudo: pip3: command not found

CONDITIONS
I am running iPython using Python 3.4.3 | Anaconda 2.2.0 (64-bit), running on Ubuntu/Linux 14.04 LTS (64-bit) OS.  

DESCRIPTION: 
The Tensorflow installation fails using PIP  for Python 3, as suggested here: (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md).

# Ubuntu/Linux 64-bit
$ sudo apt-get install python-pip python-dev

# Ubuntu/Linux 64-bit, CPU only:
$ sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp34-none-linux_x86_64.whl

DETAILS:
tensorflow-0.6.0-cp34-none-linux_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 168, in from_line
    raise UnsupportedWheel("%s is not a supported wheel on this platform." % wheel.filename)
UnsupportedWheel: tensorflow-0.6.0-cp34-none-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by martinwicke** [comment]
For some reason, pip3 seems to be using python2.7 pip internally (see the
stacktrace). It appears there's something amiss in your pip installation.

**Comment by vrv** [comment]
sudo apt-get install python3-dev and python3-pip ?

**Comment by vladalonso** [comment]
$ pip --version
$ pip 8.0.2 from ... anaconda3/lib/python3.4/site-packages (python 3.4)

**Comment by martinwicke** [comment]
pip3 --version?

**Comment by vladalonso** [comment]
$ pip3 --version
pip 8.0.2 from /home/vladimir/anaconda3/lib/python3.4/site-packages (python 3.4)

**Comment by martinwicke** [comment]
The sudo command probably messes with your environment. Your backtrace
shows that you are using files from /usr/lib/python2.7/dist-packages/pip.

Since you're using anaconda, you should be able to install without sudo,
can you try that?

Or, run `sudo pip3 --version` to verify my hunch.

**Comment by vladalonso** [comment]
$ sudo pip3 --version
sudo: pip3: command not found

**Comment by vladalonso** [comment]
I have RESOLVED - As follow: 
conda install -c https://conda.anaconda.org/jjhelmus tensorflow
REFERENCE:
I found that suggestions on http://stackoverflow.com/questions/33646541/tensorflow-and-anaconda-on-ubuntu. 
TESTED:
I ran the suggested TEST form the Command Line, and also from the Notebook using Python3 , and it works all fine :)

Thank you so much for all the collaboration. -

**Comment by vrv** [comment]
Glad you were able to make progress!

**Comment by pannous** [comment]
solved here by renaming
```
mv tensorflow-0.7.0-py2-none-linux_x86_64.whl tensorflow-0.7.0-cp27-none-linux_x86_64.whl
mv tensorflow-0.7.0-py2-none-linux_x86_64.whl tensorflow-0.7.0-py2-none-any.whl
```
