### ISSUE TITLE
The issue template has an incorrect link.

### ISSUE THREAD

**Issue by jubjamie** [tensorflow/tensorflow#10975]
Ironically, I think the issue template is wrong. I presume that point 3 below is meant to point to the tensorboard repo issue tracker `https://github.com/tensorflow/tensorboard/issues` but as you can see it just points back to the main repo issue tracker! Judging by the activity on that issue tracker perhaps this is on purpose but I doubt it!

`3. It shouldn't be a TensorBoard issue. Those go [here](https://github.com/tensorflow/tensorflow/issues).`

1. It must be a bug or a feature request.
2. The form below must be filled out.
3. It shouldn't be a TensorBoard issue. Those go >>> [here](https://github.com/tensorflow/tensorflow/issues). <<<

Cheers

**Comment by tatatodd** [comment]
@jubjamie Haha, thanks for reporting the issue.  I just sent a PR to fix this.

Yeah, a real facepalm moment.  :)

**Comment by tatatodd** [comment]
Closing this out, now that #11018 has been merged.

**Comment by jubjamie** [comment]
No worries. Made me chuckle too :)
