### ISSUE TITLE
Please modify the tensorflow/workspace.bzl's eigen version to make Nvidia TX2 compilation successful

### ISSUE THREAD

**Issue by yynil** [tensorflow/tensorflow#10970]
Hi,all
   I just managed to compile Tensorflow 1.2 successfully in Nvidia TX2. Despite the patches made by this article: http://www.jetsonhacks.com/2017/04/02/tensorflow-on-nvidia-jetson-tx2-development-kit/ , the workspace.bzl file needs to be modified to use the latest eigen version.
Specifically, you need to change the following lines:

>  native.new_http_archive(
>       name = "eigen_archive",
>       urls = [
>           "http://mirror.bazel.build/bitbucket.org/eigen/eigen/get/f3a22f35b044.tar.gz",
>           "https://bitbucket.org/eigen/eigen/get/f3a22f35b044.tar.gz",
>       ],
>       sha256 = "ca7beac153d4059c02c8fc59816c82d54ea47fe58365e8aded4082ded0b820c4",
>       strip_prefix = "eigen-eigen-f3a22f35b044",
>       build_file = str(Label("//third_party:eigen.BUILD")),
>   )

to:

>  native.new_http_archive(
>       name = "eigen_archive",
>       urls = [
>           #"http://mirror.bazel.build/bitbucket.org/eigen/eigen/get/f3a22f35b044.tar.gz",
>           #"https://bitbucket.org/eigen/eigen/get/f3a22f35b044.tar.gz",
>           "https://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz",
>       ],
>       sha256 = "the sha256 value you used to verify",
>       strip_prefix = "eigen-eigen-5a0156e40feb",
>       build_file = str(Label("//third_party:eigen.BUILD")),
>   )

Since I'm not sure if the newest eigen works well in other platform, I don't have confidence to ask for a PR.
I just post this issue in case some of you guys can't compile tensor flow 1.2 in nvidia TX2.

**Comment by rohan100jain** [comment]
I think the best course forward here would be to propose this as a PR. We can then review it and see whether it makes sense to make this change. Thanks!
