### ISSUE TITLE
What should be my --output_node_names for freeze_graph.py ?

### ISSUE THREAD

**Issue by abhiML** [tensorflow/tensorflow#10986]
I am trying to freeze graph a .pb and .ckpt file of a trained Inception model. I cannot understand what shall by my output-node-names?

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
