### ISSUE TITLE
run on gpu in tensorflow backend .

### ISSUE THREAD

**Issue by jeansely** [tensorflow/tensorflow#10990]
Hi,
How can  be sure that the tensorflow+keras  run on GPU?i use tensorflow+keras with backend   . 

Although in keras manual Written ;"If you are running on the TensorFlow or CNTK backends, your code will automatically run on GPU if any available GPU is detected"

How can this be checked?
Thanks.

**Comment by rohan100jain** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
