### ISSUE TITLE
`TF_AddGradients` incorrectly reports `Add` has no gradient 

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorflow#11002]
### System information

OS X with a CPU libtensorflow.so built off master (2336cdf)

### Describe the problem

`TF_AddGradients` reports 

```
No gradient defined for op: Add. Please see https://www.tensorflow.org/code/tensorflow/cc/gradients/README.md for instructions on how to add C++ gradients.
```

when asked to compute dz/dx for z=x+y (see code example). 

and yet `Add` has a [registered gradient](https://github.com/tensorflow/tensorflow/blob/2336cdf7f00434c24f1eb394f255d7de071bdc08/tensorflow/core/ops/math_grad.cc#L372). `Mul` also doesn't work, although gradients of other operations (like `Sin`) do work. 

### Source code / logs

```c
#include "c_api.h"

void check_status(TF_Status* status) {
  auto code = TF_GetCode(status);
  if (code != TF_OK) {
    cout<<TF_Message(status)<<endl;
    exit(0);
  }
}

int main() {
  auto graph = TF_NewGraph();
  auto x_desc = TF_NewOperation(graph, "Placeholder", "x");
  TF_SetAttrType(x_desc, "dtype", TF_FLOAT);
  auto status = TF_NewStatus();
  auto x = TF_FinishOperation(x_desc, status);
  auto y_desc = TF_NewOperation(graph, "Placeholder", "y");
  TF_SetAttrType(y_desc, "dtype", TF_FLOAT);
  auto y = TF_FinishOperation(y_desc, status);
  auto z_desc = TF_NewOperation(graph, "Add", "z");
  TF_AddInput(z_desc, {x, 0});
  TF_AddInput(z_desc, {y, 0});
  auto z = TF_FinishOperation(z_desc, status);
  TF_Output output = {z, 0};
  TF_Output input = {x, 0};
  TF_Output grad;
  TF_AddGradients(graph, &output, 1, &input, 1, NULL, status, &grad);
  check_status(status);
  return 0;
}

```

**Comment by asimshankar** [comment]
@suharshs : Mind taking a look?

(FYI @skye @iganichev )

**Comment by suharshs** [comment]
The cc gradients are registered in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/cc/gradients. What you have linked is the gradients for function defs, which do not apply to cc gradients. (This is a point of confusion that we should consolidate).
So for your specific ops, check that your gradients are in this file: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/gradients/math_grad.cc

If not, please create a pull request or an issue for the desired ops following instructions at, https://www.tensorflow.org/code/tensorflow/cc/gradients/README.md

Thanks!

**Comment by malmaud** [comment]
Oh I see, `Add` is not actually a registered C++ gradient yet. Sorry for the confusion.

**Comment by suharshs** [comment]
No worries, the confusion is completely understandable given the duplicate gradient registries. I'll see if we can solve that issue. Thanks!
