### ISSUE TITLE
provide project ide setting support

### ISSUE THREAD

**Issue by haiy** [tensorflow/tensorflow#11007]
I'm trying to debug the c++ source code to figure out the function call relation.But I find it's very difficult to import the code to any existing ide on Mac.I had to use the bazel command  to build and test. using gdb to debug is a bit frustrating.If there are some useful tool chains, would you please give some tips which will make it easily for developers to try such great tensorflow?Thanks so much.

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
