### ISSUE TITLE
Upgrade to jemalloc 5.0.0

### ISSUE THREAD

**Issue by jhseu** [tensorflow/tensorflow#11000]
Contributions welcome! (I won't have bandwidth to do this in the short-term.)

**Comment by joshua-xia** [comment]
change workspace.bzl:

temp_workaround_http_archive(
      name = "jemalloc",
      urls = [
          "http://mirror.bazel.build/github.com/jemalloc/jemalloc/archive/4.4.0.tar.gz",
          "https://github.com/jemalloc/jemalloc/archive/4.4.0.tar.gz",
      ],
      sha256 = "3c8f25c02e806c3ce0ab5fb7da1817f89fc9732709024e2a81b6b82f7cc792a8",
      strip_prefix = "jemalloc-4.4.0",
      build_file = str(Label("//third_party:jemalloc.BUILD")),
      repository = tf_repo_name,
  )

to be jemalloc-5.0.0?

I found https://github.com/jemalloc/jemalloc/archive/5.0.0.tar.gz work.
but http://mirror.bazel.build/github.com/jemalloc/jemalloc/archive/5.0.0.tar.gz not exist yet.

Is there other things need to be changed?
Thanks

**Comment by jhseu** [comment]
Yeah, this BUILD file has to be updated as well:
https://github.com/tensorflow/tensorflow/blob/master/third_party/jemalloc.BUILD

The configurations were created by running ./configure on an Ubuntu 14.04 machine and copying it over. If you don't have access to Ubuntu, you can use Docker.

**Comment by joshua-xia** [comment]
Please assign to me, Thanks

**Comment by joshua-xia** [comment]
update: I already successfully build tensorflow using jemalloc 5.0.0, need a little more time to change jemalloc.BUILD because the jemalloc.h generate method is changed.

**Comment by dynamicwebpaige** [comment]
It looks like jemalloc was [removed](https://github.com/tensorflow/tensorflow/commit/52574f95279d8cd5ec22cfc24668b9586e41367a) from the BUILD files recently, along with other dead configuration options. Is it okay to close this feature request, or would it still be useful to have support?

**Comment by rthadur** [comment]
https://github.com/tensorflow/tensorflow/blob/master/third_party/jemalloc.BUILD as the build files are removed , closing this issue. Thank you
