### ISSUE TITLE
Link to README.md is broken in NativeLibrary.java

### ISSUE THREAD

**Issue by rola93** [tensorflow/tensorflow#11015]
I'm trying to run TensorFlow in Java, following [this instructions](https://www.tensorflow.org/install/install_java)

I'm using Ubuntu 16 and java 8. I'm not sure what did I wrong, but error message says: 

`$ java -cp libtensorflow-1.2.0.jar:. -Djava.library.path=~/jni HelloTF`

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: linux, architecture: x86_64. See https://github.com/tensorflow/tensorflow/tree/master/java/README.md `

`for possible solutions (such as building the library from source).`
	`at org.tensorflow.NativeLibrary.load(NativeLibrary.java:66)`
	`at org.tensorflow.TensorFlow.init(TensorFlow.java:36)`
	`at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:40)`
	`at org.tensorflow.Graph.<clinit>(Graph.java:194)`
	`at HelloTF.main(HelloTF.java:8)`

But following  **https://github.com/tensorflow/tensorflow/tree/master/java/README.md**  gets 404 - page not found.

**Comment by asimshankar** [comment]
Thanks for the report, I'll update the link (the correct link is https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md)

That said, looking at your erro message it seems that ti cannot find the native library. Can do run the following commands to help verify what might be missing in your setup?

```
ls ~/jni
file ~/jni/*
```

Alternatively, if it makes sense for you, I'd suggest using a build tool like maven or gradle or something as that will involve much less command-line tweaking. See [instructions on the website](https://www.tensorflow.org/install/install_java#using_tensorflow_with_a_maven_project) for maven, or if you use other build tools (like gradle), then see the corresponding dependency information section [here](http://search.maven.org/#artifactdetails%7Corg.tensorflow%7Ctensorflow%7C1.2.0%7C)

**Comment by rola93** [comment]
Thanks! I solved it giving the correct path to jni :smile:

**Comment by tatatodd** [comment]
Cool, looks like this issue is resolved, so I'm closing it out.

**Comment by tatatodd** [comment]
Oops I spoke too soon; the real problem is fixed, but this issue is about fixing the README link.  :)

**Comment by asimshankar** [comment]
Closing this as it's been fixed in https://github.com/tensorflow/tensorflow/pull/11094/commits/4cc35257f1f3613aae65a42b96e5ea5bba785f66
