### ISSUE TITLE
bazel does not co-operate with Ubuntu's update-alternatives

### ISSUE THREAD

**Issue by esafak** [tensorflow/tensorflow#11021]
### System information

TF 1.2, Ubuntu 17.04 on GCE, CUDA 8.0, gcc 4.9.4

### Describe the problem
bazel fails to compile tensorflow when multiple versions of gcc are present and the default points to `/etc/alternatives/gcc`. Specifically, it fails to find the C and C++ header files. However, all works well when `configure` is set to use `/usr/bin/gcc`.

**Comment by caisq** [comment]
Maybe this is a more appropriate place to file this bazel issue:

https://github.com/bazelbuild/bazel/issues

**Comment by tatatodd** [comment]
@esafak Yes as @caisq suggests, please file a bazel bug for this instead.

If you feel there are tensorflow-specific issues, just comment on this issue and I'll re-open.
