### ISSUE TITLE
Bug: placeholder input to tf.one_hot leads to hang

### ISSUE THREAD

**Issue by anishathalye** [tensorflow/tensorflow#11023]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.1.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 8.0 / cuDNN 6.0
- **GPU model and memory**: GTX 1080 Ti 11GB
- **Exact command to reproduce**: see below

### Describe the problem

I'm not sure if you're not supposed to feed in a placeholder to `tf.one_hot`, but if you do, it hangs and chews up 100% CPU.

### Source code / logs

Minimal example to reproduce bug:

```python
import tensorflow as tf

sess = tf.Session()
p = tf.placeholder(tf.uint8, 1)
x = tf.one_hot(p, depth=10)
res = sess.run(x, feed_dict={p: [3]})
print(res)
```

The expected result should be either (1) it works and prints `[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]`, or (2) it produces some kind of error.

**Comment by snowsky** [comment]
I got the output of [[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]]. So this can be closed?

**Comment by anishathalye** [comment]
Oh hmm, I upgraded to 1.2.0 and now it works.
