### ISSUE TITLE
install with MKL and OpenCL without locate command

### ISSUE THREAD

**Issue by shitian-ni** [tensorflow/tensorflow#11029]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Description:	SUSE Linux Enterprise Server 11 (x86_64)
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:master branch
- **Bazel version (if compiling from source)**:0.5.1
- **CUDA/cuDNN version**:7.5
- **GPU model and memory**:Tesla K20Xm
- **Exact command to reproduce**:./configure

### Describe the problem
I am trying to install tensorflow on Tokyo Institute of Technology Supercomputer TSUBAME.
I want to install with MKL support, but locate command is required.
The university says that because TSUBAME is a public service and `locate` can be used to see files from other users, the command is not going to be installed. So it means MKL can't be used even it is installed in the supercomputer.
I suggest a feature to install tensorflow with the supports without locate command.
I guess tensorflow is used in a lot of supercomputers, the same problem may occur elsewhere.

### Source code / logs
`Do you wish to build TensorFlow with MKL support? [y/N] y
MKL support will be enabled for TensorFlow
Do you wish to download MKL LIB from the web? [Y/n] n
Please specify the location where MKL is installed. [Default is /opt/intel/mklml]: /usr/apps.sp3/isv/intel/xe2013.1.046/composer_xe_2013_sp1.2.144/mkl
./configure: line 279: locate: command not found`

**Comment by joshua-xia** [comment]
can you use whereis command? or find? In TSUBAME

**Comment by hotchkiss87** [comment]
Locate is not installed by default on some systems, like Gentoo. It's a nice tool to have though (sometimes it's called 'mlocate' though, and it doesn't have a standard, so it's generally not a great idea to use it in scripts.) If you don't want locate though, you can manually change the line to this:
```bash
loc="$(find / -mount -name 'libdl.so.2' -print 2>/dev/null | head -n1)"
```
It looks like that section is going to change a lot in the future, so it might be better just edit the config instead of merging a change someone else will have to remove.

**Comment by gunan** [comment]
MKL build should now not depend on locate command, if you are building from master branch.
