### ISSUE TITLE
Error building bazel "gcc: unrecognized option '-no-canonical-prefixes'"

### ISSUE THREAD

**Issue by shitian-ni** [tensorflow/tensorflow#11031]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Description:	SUSE Linux Enterprise Server 11 (x86_64)
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:master branch
- **Bazel version (if compiling from source)**:0.5.1
- **CUDA/cuDNN version**:7.5
- **GPU model and memory**:Tesla K20Xm
- **Exact command to reproduce**:`bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures`

### Describe the problem
Can't build bazel

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
![screen shot 2017-06-24 at 7 49 54 pm](https://user-images.githubusercontent.com/20103571/27507974-b650c51c-5916-11e7-978c-3a2e5ade2b2c.png)

**Comment by skye** [comment]
It looks like you need a newer version of gcc. Unfortunately you're not building on an officially-supported OS, so most likely you'll have to figure out how to upgrade gcc or use Ubuntu. I'm going to close this issue since it's not a TensorFlow bug or feature request.
