### ISSUE TITLE
There should be tf.fill_like

### ISSUE THREAD

**Issue by 3rd3** [tensorflow/tensorflow#11034]

**Comment by lakshayg** [comment]
Did you mean tf.full_like (Ref: [`np.full_like`](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.full_like.html))?

**Comment by 3rd3** [comment]
Yes, exactly. Sorry for the lack of details.

**Comment by lakshayg** [comment]
@3rd3 is there really a need for this function? I guess the same effect can be achieved by using `k * tf.ones_like(x)`

**Comment by bbbbbbbbba** [comment]
@lakshayg Or `k + tf.zeros_like(x)`. But I am not sure which one is optimal, or whether either of them is.

**Comment by rrrokhtar** [comment]
Shouldn't it be closed?

**Comment by yongtang** [comment]
I think this issue can be closed as the functionality can be easily achieved at the python level.
