### ISSUE TITLE
Documentation Error in TenserFlow website

### ISSUE THREAD

**Issue by redblood53** [tensorflow/tensorflow#11042]
On website page:
https://www.tensorflow.org/get_started/get_started#a_custom_model

There is a missing line in the sample code provide for Custom Model:
 After this line 
 `input_fn = tf.contrib.learn.io.numpy_input_fn({"x": x_train}, y_train, 4, num_epochs=1000)`.
in sample code there should be one more line for variable `eval_input_fn ` which is missing right now in the docs.
single line of code to be added in sample code is 
`eval_input_fn = tf.contrib.learn.io.numpy_input_fn({"x": x_eval}, y_eval,4, num_epochs=1000)`

**Comment by ali01** [comment]
Thanks for pointing this out, this line seems to be there now.

**Comment by JasperDeKort** [comment]
i came here to report this same issue.
for the version of the site that i see the line is not there. 

please note that in the section above it, the line is there.
