### ISSUE TITLE
tf.contrib.xprof not supported on Windows

### ISSUE THREAD

**Issue by soukira** [tensorflow/tensorflow#11046]
opts = tf.contrib.tfprof.model_analyzer.TRAINABLE_VARS_PARAMS_STAT_OPTIONS
AttributeError: module 'tensorflow.contrib.tfprof' has no attribute 'model_analyzer'

I have tensorflow version 1.2 and have made all the other transitioning changes and the above error was thrown later. 
Has the contrib support been resolved for Windows? Please help

**Comment by mrry** [comment]
The `tf.contrib.xprof` submodule is not yet supported on Windows. @panyx0718 is currently working to add support for this submodule, so assigning this bug to him as a placeholder.

**Comment by panyx0718** [comment]
I think it supports Windows now. Note: Now the api is: tf.profiler
Let me know if it doesn't work
