### ISSUE TITLE
C lib for windows with GPU support

### ISSUE THREAD

**Issue by tcmxx** [tensorflow/tensorflow#11062]
I know that there is a windows c library built for cpu https://github.com/tensorflow/tensorflow/issues/10817.

However, I could not find one with gpu support. I've tried https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-1.2.0.zip, but obvious it does not exist. 

Is it possible to have one?

Thank you!

**Comment by tcmxx** [comment]
Or if anybody can tell me how to do that myself..Just like the official cpu version...?

**Comment by snnn** [comment]
Hi @tcmxx , it was built by bazel.  Please try to follow these 2 guides:

https://docs.bazel.build/versions/master/install.html
https://www.tensorflow.org/install/install_sources

And 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/windows/libtensorflow_cpu.sh

**Comment by tcmxx** [comment]
@snnn Thanks！
Just tried it and it worked! There is already the function to configure GPU build in the scripts and I only need to modify a little of it to make it work.
