### ISSUE TITLE
Global Variables of graph not loaded on different computer

### ISSUE THREAD

**Issue by piordanov** [tensorflow/tensorflow#11068]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:l
- MacOSx :
- **TensorFlow installed from binary** (pip install):
- Tensorflow version 1.1.0

### Describe the problem
I have been having issues trying to load a model from a checkpoint file. When trying to access any of the global variables created in our tensorflow model (for example `print sess.run(W)`, we get an error 

> NameError: global name 'W' is not defined

We expect W and other global variables to be present, but none are. Thanks for the help.

### Source code / logs

```
        init_op = tf.global_variables_initializer()
        with tf.Session() as sess:
            sess.run(init_op)
            saver = tf.train.import_meta_graph('FinalTensorflowModel/model.ckpt.meta')
            saver.restore(sess,"FinalTensorflowModel/model.ckpt")
            print sess.run(W)
            for idx, row in df.iterrows():
                profitability = tf.matmul(row,W) + b
                print sess.run(profitability)
```

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
