### ISSUE TITLE
Unable to install TensorFlow properly on windows for python. Please help!

### ISSUE THREAD

**Issue by deep-r** [tensorflow/tensorflow#11065]
I am trying to install TensorFlow on Windows 10 for Python 3.5 64 bit. It says "successfully installed" but when I test it using "import tensorflow as tf" command in the command prompt, it shows a long error saying "DLL load failed" and "failed to load native tensorflow runtime".

I had tried installing it earlier but it didn't work. When I uninstalled from cmd: pip uninstall tensorflow, it said "successfully uninstalled". But when I try reinstalling, it says, "requirement already satisfied" and gives the same long error (DLL load failed etc.) when i type "import tensorflow as tf". This doesn't make sense. Please help.

Please see images.
![image](https://user-images.githubusercontent.com/26795925/27552208-0fd2058e-5ac4-11e7-82d1-c3e16bc74261.png)

![image](https://user-images.githubusercontent.com/26795925/27552227-1e0670f4-5ac4-11e7-9ee8-60969c0a91b9.png)

**Comment by mrry** [comment]
Try running the script here to diagnose DLL problems with TensorFlow on Windows: https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c

**Comment by printdhruv** [comment]
Hi,
          In order to get tensor flow working with `Windows 10 `with old version of `Python,cUDNN,Nvidia.` Classical solution link will be [https://github.com/tensorflow/tensorflow/issues/10994](https://github.com/tensorflow/tensorflow/issues/10994)

**Comment by jolee3299** [comment]
Hi
Did you solve the problem of installing TensorFlow on Windows 10 for Python 3.5 64 bit?
I got exactly same problem like you.
Can advise me to solve hat problem with your experience?
I am teaching java in school but novice user in Python and Deep learning. Now I am studying those.
So please guide me detailly how to solve tensorflow installing problems in Windows.
Thiank you

**Comment by printdhruv** [comment]
Hi,
      Yes, It works. Please follow this thread and this link  : [Windows_10 install](https://stackoverflow.com/questions/42011070/on-windows-running-import-tensorflow-generates-no-module-named-pywrap-tenso)

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ruthyaneth** [comment]
https://youtu.be/OiPjSnKAmSI

**Comment by printdhruv** [comment]
@ruthyaneth Now,it's far more stable.You can do it far more easily with nightly builds.

**Comment by luckylehana** [comment]
After searching a lot and trying to install and reinstall Python, i found the solution was very simple

use the following for windows

python -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl

change to following on mac

python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl

for Anaconda use corresponding conda

**Comment by priyansh985** [comment]
i am solve this problem 
you type  this follow this process 
right click to windows button and open windows power shell
and write this    pip install tensorflow==2.3.0
ok and give time to his computer to download this
and check the tensorflow to using import command 
you type import tensorflow
and computer gives you no errors 
you did it your tensorflow successfuly installed thank you ...
