### ISSUE TITLE
how use tensorflow distributed use mpi version ??

### ISSUE THREAD

**Issue by guoying1030** [tensorflow/tensorflow#11072]
how use tensorflow distributed use mpi version ??how use tensorflow distributed use mpi version ??how use tensorflow distributed use mpi version ??

how use tensorflow distributed use mpi version ??how use tensorflow distributed use mpi version ??

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
