### ISSUE TITLE
Is it possible to add a feature to tf.Print , so that it will be capable to save tensor value to file?

### ISSUE THREAD

**Issue by JerrikEph** [tensorflow/tensorflow#11076]
Since the while_loop operation is hard to debug, usually we use `tf.Print` to visual tensors in the loop. but `tf.Print` only print a summarization of a tensor. Sometimes I need to get all the value in a tensor, and it is not possible to use `sess.run()` to eval the intermediate tensor value in a loop unless use `TensorArray`. any body would add a **save-to-file** option in `tf.Print` .

**Comment by joshua-xia** [comment]
Redirect all log out to file

**Comment by JerrikEph** [comment]
Would it redirect the whole tensor to a file, or it would just output the summary?

**Comment by frreiss** [comment]
@JerrikEph If you don't mind having long lines in your primary log output, you can increase the size of the tensor summaries with the `summarize` argument of `tf.Print`.  You can also use the `message` argument of `tf.Print` to prepend an easy-to-grep string to every tensor it outputs. For example, `tf.Print( ... , message='BIGTENSOR', summarize=1000000, ...)` will print up to 1 million entries of each input tensor and will prepend each tensor with the string "BIGTENSOR". You could then copy all those tensors into a separate file by searching for lines containing the string "BIGTENSOR" in the original log file; or you could filter those big tensors out by grepping for lines that don't contain that string.

**Comment by aespielberg** [comment]
These solutions don't really work though when what you want is an easily readable CSV file.

**Comment by JerrikEph** [comment]
Tensorflow version 2.0.0 of `tf.print` now support the **save-to-file** feature.
