### ISSUE TITLE
something wrong with attentionwrapper?

### ISSUE THREAD

**Issue by sunxiaoben** [tensorflow/tensorflow#11077]
I am trying to write a seq2seq model with attention. But it gets the following error:

    cell_inputs = self._cell_input_fn(inputs, state.attention)
AttributeError: 'tuple' object has no attribute 'attention'

It seems the state which initialize by the encoder state that does't has the attribute 'attention'.
How should I call AttentionWrapper?

Here is my code:

        cell_list = []
        for layer_i in xrange(hps.num_layers):
            cell_list.append( tf.contrib.rnn.LSTMCell(hps.num_hidden) )
            with tf.variable_scope('encoder%d'%layer_i):
                cell_list.append( tf.contrib.rnn.LSTMCell(hps.num_hidden) )
        enc_cell = tf.contrib.rnn.MultiRNNCell(cell_list)

        encoder_outputs, encoder_state = tf.contrib.rnn.static_rnn(enc_cell, enc_inp, dtype=dtype)

        cell_list = []
        for layer_i in xrange(hps.num_layers):
            with tf.variable_scope('decoder%d'%layer_i):
                cell_list.append( tf.contrib.rnn.LSTMCell(hps.num_hidden) )
        dec_cell = tf.contrib.rnn.MultiRNNCell(cell_list)

        new_enc_out = tf.reshape(encoder_outputs, [hps.batch_size, 30, 256])
        attn_mech = tf.contrib.seq2seq.BahdanauAttention(
                num_units = 128, # depth of query mechanism
                memory = new_enc_out, # hidden states to attend (output of RNN)
                normalize=False, # normalize energy term
                name='BahdanauAttention')

        attn_cell = tf.contrib.seq2seq.AttentionWrapper(
                cell = dec_cell,# Instance of RNNCell
                attention_mechanism = attn_mech, # Instance of AttentionMechanism
                name="attention_wrapper")

        if hps.mode=="train":
            # TrainingHelper does no sampling, only uses inputs
            helper = tf.contrib.seq2seq.TrainingHelper(
                    inputs = dec_inp[:decoder_size], # decoder inputs
                    sequence_length = [1]*decoder_size, # decoder input length
                    name = "decoder_training_helper")

            decoder = tf.contrib.seq2seq.BasicDecoder(
                    cell = attn_cell,
                    helper = helper, # A Helper instance
                    initial_state = encoder_state, # initial state of decoder
                    output_layer = None) # instance of tf.layers.Layer, like Dense

        decoder_outputs, final_state, _ = tf.contrib.seq2seq.dynamic_decode(decoder)

**Comment by skye** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by Songweiping** [comment]
You provide wrong initial state while constructing the decoder in: 

```
decoder = tf.contrib.seq2seq.BasicDecoder(
                cell = attn_cell,
                helper = helper, # A Helper instance
                initial_state = encoder_state, # initial state of decoder
                output_layer = None) # instance of tf.layers.Layer, like Dense
)
```
`encoder_state` is not an instance of the AttentionWrapperState,  and naturally it has no attribute named "attention". You should provide an instance of AttentionWrapperState as initial_state, such as `attn_cell.zero_state(...)`.

**Comment by madhurcodes** [comment]
You can use  `initial_state = wrapper.zero_state(...).clone(cell_state=encoder_state)` if you need to pass the encoder state initially.

**Comment by PratsBhatt** [comment]
I am getting issue related to miss match of state and output. But I am unable to figure the issue.
It would be really appreciated if someone can guide me. Thanks in advance.
I am using tensorfow-gpu==1.2.1, with 1080 Ti graphics. 

Error is as below:
ValueError: Shapes (8, 522) and (8, 512) are incompatible

Error occurs in the file "attention_wrapper.py" in the method named "call" at line 708 

`cell_output, next_cell_state = self._cell(cell_inputs, cell_state)`

I was able to figure out that it is adding the attention_size to the shape and so there is a mismatch.
But I have no idea how to fix it. 
The code is as below,  hyper-parameters are declared as below (test purpose).
` 
batch_size= 8
number_of_units_per_layer= 512
number_of_layers = 3   
attn_size= 10
def build_decoder_cell(enc_output, enc_state, source_sequence_length, attn_size, batch_size):

        encoder_outputs = enc_output
        encoder_last_state = enc_state
        encoder_inputs_length = source_sequence_length

        attention_mechanism = attention_wrapper.LuongAttention(
                num_units=attn_size, memory=encoder_outputs,
                memory_sequence_length=encoder_inputs_length,
                scale=True,
                name='LuongAttention' )

        # Building decoder_cell
        decoder_cell_list = [
            build_single_cell() for i in range(num_layers)]

        decoder_initial_state = encoder_last_state

        def attn_decoder_input_fn(inputs, attention):
            #if not self.attn_input_feeding:
            #    return inputs

            # Essential when use_residual=True
            _input_layer = Dense(size, dtype=tf.float32,
                                name='attn_input_feeding')
            return _input_layer(array_ops.concat([inputs, attention], -1))


        # AttentionWrapper wraps RNNCell with the attention_mechanism
        # Note: We implement Attention mechanism only on the top decoder layer
        decoder_cell_list[-1] = attention_wrapper.AttentionWrapper(
            cell=decoder_cell_list[-1],
            attention_mechanism=attention_mechanism,
            attention_layer_size=attn_size,
            #cell_input_fn=attn_decoder_input_fn,
            initial_cell_state=encoder_last_state[-1],
            alignment_history=False,
            name='Attention_Wrapper')

        # To be compatible with AttentionWrapper, the encoder last state
        # of the top layer should be converted into the AttentionWrapperState form
        # We can easily do this by calling AttentionWrapper.zero_state

        # Also if beamsearch decoding is used, the batch_size argument in .zero_state
        # should be ${decoder_beam_width} times to the origianl batch_size
        #batch_size = self.batch_size if not self.use_beamsearch_decode \
        #    else self.batch_size * self.beam_width
        initial_state = [state for state in encoder_last_state]

        initial_state[-1] = decoder_cell_list[-1].zero_state(
            batch_size=batch_size, dtype=tf.float32)
        decoder_initial_state = tuple(initial_state)

        return tf.contrib.rnn.MultiRNNCell(decoder_cell_list), decoder_initial_state`

Thank you once again.

**Comment by niraj-bhujel** [comment]
@madhurcodes  I am trying to pass the encoder state into the decoder using the 

> clone, however I got an error AttributeError: 'tuple' object has no attribute 'clone'. Could you please help. Thanks
A part of my code is as below;
`
enc_output, self.enc_state = tf.nn.bidirectional_dynamic_rnn(encoder_cell_fw, encoder_cell_bw, enc_embed_input,   initial_state_fw=init_state_fw,  initial_state_bw=init_state_bw, dype=tf.float32, time_major=False) 
att_fn = BahdanauAttention(config.rnn_size, enc_output)
decoder_cell = tf.nn.rnn_cell.MultiRNNCell(
                                [tf.contrib.seq2seq.AttentionWrapper(lstm_cell(), att_fn) for _ in range(num_layers)])
dec_init_state = decoder_cell.zero_state(5, tf.float32).clone(cell_state=enc_state)`
