### ISSUE TITLE
model_with_buckets in seq2seq.py

### ISSUE THREAD

**Issue by zhang-jian** [tensorflow/tensorflow#1107]
Hi all,

The online version of https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/seq2seq.py#L873

```
def model_with_buckets(encoder_inputs, decoder_inputs, targets, weights,
                       buckets, seq2seq, softmax_loss_function=None,
                       per_example_loss=False, name=None):
```

is different with the one installed from tensorflow-0.6.0-cp27-none-linux_x86_64.whl
```
def model_with_buckets(encoder_inputs, decoder_inputs, targets, weights,
                       buckets, num_decoder_symbols, seq2seq,
                       softmax_loss_function=None, name=None):
```

(extra **num_decoder_symbols** parameter) which caused 
```
TypeError: model_with_buckets() takes at least 7 arguments (7 given) 
```
when running https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/seq2seq_model.py#L133.

Which one should I use?

Thanks,

**Comment by vrv** [comment]
If you have installed 0.6.0 from pip, always check out the code repository at the same branch/tag -- they should be compatible.

If you want the latest changes from master, you'll have to build the pip package from sources.
