### ISSUE TITLE
[feature] Option to Selectively Disable Certain Graph Optimizations

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#11087]
repost from: https://github.com/tensorflow/tensorflow/commit/999b794c137d12d73adbf41dcbe9383a0cd94769#commitcomment-22789669 (CC @petewarden).

On iOS when using a graph that has been "memory mapped", you want to disable constant folding to prevent the optimization pass from copying all of the weight data. The current way to do so is to set optimization [level `L0` which disables all optimizations](https://github.com/tensorflow/tensorflow/blob/12f033df4c8fa3feb88ce936eb1581eaa92b303e/tensorflow/core/protobuf/config.proto#L101-L102). Ideally there is a way to keep Common subexpression elimination and function inlining, but prevent constant folding.

**Comment by frreiss** [comment]
It looks like the optimization level is actually the logical OR of the Boolean flags in the OptimizerOptions and the optimization level. See the code at  [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/graph_optimizer.cc#L27-L32].

So you can get the semantics you want with something like:
```opt_opts = options.config.mutable_graph_options()->mutable_optimizer_options();
opt_opts->set_opt_level(::tensorflow::OptimizerOptions::L0);
opt_opts->set_do_common_subexpression_elimination(true);
opt_opts->set_do_function_inlining(true);
```
