### ISSUE TITLE
Basic support for trigonometric operations

### ISSUE THREAD

**Issue by fxsuper** [tensorflow/tensorflow#1108]
I'd like to request support for basic trigonometric ops. Nothing fancy, but just simple stuff like tan and the arc complement (arcsin, arctan, etc). All that's there right now is sin and cos.

**Comment by martinwicke** [comment]
And, of course, tanh. :)

That's a good idea.

**Comment by girving** [comment]
Also all the hyperbolic trig functions.

**Comment by Mistobaan** [comment]
I gave a shot at implementing the first ones.

**Comment by fxsuper** [comment]
#483 is related as well.

**Comment by girving** [comment]
#483 is probably separate since it involves a dtype change, and can't participate in the same pile of macros.

**Comment by fxsuper** [comment]
I guess atan2 would get us part of the way there. Perhaps it can be included with the other elementary trig functions?

**Comment by webmaven** [comment]
Can this issue be closed? It looks like changes (in PR #1573) were merged into master back in May.

**Comment by vrv** [comment]
Sure!

**Comment by SystemErrorWang** [comment]
Hope these functions can support batch input
