### ISSUE TITLE
configure script hardcodes location of cuda that makes it fail on OSX

### ISSUE THREAD

**Issue by delip** [tensorflow/tensorflow#111]
Cuda installation on OSX is at $CUDA_TOOLKIT_PATH/lib (not lib64), and on OSX the shared libraries are end in .dylib (not .so).

```
  if [ -e "$CUDA_TOOLKIT_PATH/lib64/libcudart.so.7.0" ]; then
    break
  fi
  echo "Invalid path to CUDA 7.0 toolkit. ${CUDA_TOOLKIT_PATH}/lib64/libcudart.so.7.0 cannot be found"
```

**Comment by vrv** [comment]
Hey @delip, we currently don't have support for GPUs on Mac OS X.

Out of curiosity, what GPU are you trying to get working with TensorFlow?

**Comment by dhess** [comment]
I'm not OP, but in my case, it would be the D700 and D500 as found on Mac Pro (Late 2013) models (which require OpenCL, of course).

**Comment by zheng-xq** [comment]
We don't support OpenCL right now. You need a NV GPU with at least compute 3.0 capability.

**Comment by dhess** [comment]
I understand. I was just replying to @vrv's question about GPUs people are using on OS X.

**Comment by delip** [comment]
Hey @vrv, I'm on a Mac Pro (late 2013) like Drew. Also, a lot of my friends
develop on their macbook pros.

**Comment by vrv** [comment]
@delip: so do you also have AMD GPUs?

**Comment by delip** [comment]
That's correct. I also tried this on the latest iMac 5K which also contains
a AMD GPU (AMD Radeon R9 M290X)

**Comment by vrv** [comment]
Gotcha, so that would require OpenCL support, which we're tracking here: https://github.com/tensorflow/tensorflow/issues/22.  I'll de-dupe with that feature request.
