### ISSUE TITLE
Batch normalization layer has new name for each call to `__init__`

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#11103]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OSX 10.12.5
- **TensorFlow installed from (source or binary)**: `pip install`
- **TensorFlow version (use command below)**: 1.1.0
- **CUDA/cuDNN version**: no GPU
- **Exact command to reproduce**:
```python
import tensorflow as tf
x = tf.placeholder(tf.float32, [None, 28])
x_test = tf.placeholder(tf.float32, [None, 28])
normalized_x = tf.layers.batch_normalization(x, training=True, reuse=None)
normalized_x_test = tf.layers.batch_normalization(x_test, training=False, reuse=True)
```

### Describe the problem
This is the error I get:
```
ValueError: Variable batch_normalization_1/beta does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
```
However, I can fix it by setting the name of the batch normalization layer. I think the default behavior should not set a new name each time I create a new batch normalization layer (even if it's an easy thing to debug).

### Source code / logs
Working piece of code:
```python
import tensorflow as tf
x = tf.placeholder(tf.float32, [None, 28])
x_test = tf.placeholder(tf.float32, [None, 28])
normalized_x = tf.layers.batch_normalization(x, training=True, reuse=None, name="batch_normalization")
normalized_x_test = tf.layers.batch_normalization(x_test, training=False, reuse=True, name="batch_normalization")
```

**Comment by skye** [comment]
@fchollet can you comment?

**Comment by fchollet** [comment]
User error; in order to reuse a layer by name you should be giving it a name via the `name` argument:

```python
normalized_x = tf.layers.batch_normalization(
    x, training=True, reuse=None, name='my_bn')
normalized_x_test = tf.layers.batch_normalization(
    x_test, training=False, reuse=True, name='my_bn')
```

Indeed, if you don't provide a name to your layer, TF has no way to know *which* layer you are referring to when specifying `reuse=True`.

**Comment by zaccharieramzi** [comment]
Sorry to answer only now. I understand the fix that you suggested and had applied it.
However, I don't understand with your explanation how the following works:
```python
import tensorflow as tf
x = tf.placeholder(tf.float32, [None, 28])
x_test = tf.placeholder(tf.float32, [None, 28])
with tf.variable_scope("forward"):
        normalized_x = tf.layers.batch_normalization(
            x, training=True, reuse=None)
with tf.variable_scope("forward"):
        normalized_x_test = tf.layers.batch_normalization(
            x_test, training=False, reuse=True)
```
 and this doesn't:
```python
import tensorflow as tf
x = tf.placeholder(tf.float32, [None, 28])
x_test = tf.placeholder(tf.float32, [None, 28])
with tf.variable_scope("forward"):
        normalized_x = tf.layers.batch_normalization(
            x, training=True, reuse=None)
        normalized_x_test = tf.layers.batch_normalization(
            x_test, training=False, reuse=True)
```
