### ISSUE TITLE
What is the possible substitute of cc_ops for android/mobile environment

### ISSUE THREAD

**Issue by kzos** [tensorflow/tensorflow#11112]
OS: Ubuntu 16.04 64bits
Android Version: 7.1 (Nougat)
NDK Version: android-ndk-r12b
Development: develop shared library that exposes op's to NDK CPP application.

I am aware, that there is no explicit support for cc_ops on android/mobile env,
I am using few methods in my application. 

```
tensorflow::ops::ReadFile` 
DecodeJpeg
Const(root.WithOpName("size"), {input_height, input_width})
```

I just copied these headers from **//bazel-out** to **//tensorflow**
but it requires dependencies, 

```
this rule is missing dependency declarations for the following files included by 'tensorflow/imgproject/imgproject_model.cc':
  '/tensorflow/tensorflow/tensorflow/tensorflow/cc/ops/const_op.h'
  '/tensorflow/tensorflow/tensorflow/tensorflow/cc/framework/ops.h'
  '/tensorflow/tensorflow/tensorflow/tensorflow/cc/framework/scope.h'
  '/tensorflow/tensorflow/tensorflow/tensorflow/cc/ops/array_ops.h'
  '/tensorflow/tensorflow/tensorflow/tensorflow/cc/ops/io_ops.h'
  '/tensorflow/tensorflow/tensorflow/tensorflow/cc/ops/image_ops.h'
  '/tensorflow/tensorflow/tensorflow/tensorflow/cc/ops/math_ops.h
```

I am not sure whether libtensorflow_inference.so can be used with this
Is there any possible substitute for above op's in android/mobile?
please provide pointers.

--
thanks

**Comment by andrewharp** [comment]
You probably want to be using [tensorflow/core:android_tensorflow_lib](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/BUILD#L989) or //tensorflow/contrib/android:libtensorflow_inference.so

You can attempt to add ops to the dependencies of those libraries but note that DecodeJpeg is not guaranteed to work on Android without some hassle (I'd recommend stripping out that node with optimize_for_inference and passing in the image raster directly to the nodes it feeds).

For further assistance on this issue please refer to StackOverflow, as this is neither a bug nor a feature request. You'll find more community support there.
