### ISSUE TITLE
reset_default_graph awkwardly breaks graph nesting.

### ISSUE THREAD

**Issue by Thenerdstation** [tensorflow/tensorflow#11121]
### System information
- **Linux Ubuntu 16.04**:
- **TF version 1.1.0, though it should still be present in master**:

### Bug
Running this:
```python
import tensorflow as tf

g = tf.Graph()
with g.as_default():
  tf.reset_default_graph()
  # Build something...
  a = tf.constant(1.0)
  b = tf.constant(1.0)
  c = a + b
  # Bug happens on exit of the with statement
```
Causes this

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-af7c5ed96704> in <module>()
      7   a = tf.constant(1.0)
      8   b = tf.constant(1.0)
----> 9   c = a + b

/usr/lib/python3.5/contextlib.py in __exit__(self, type, value, traceback)
     64         if type is None:
     65             try:
---> 66                 next(self.gen)
     67             except StopIteration:
     68                 return

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py in get_controller(self, default)
   3626     finally:
   3627       if self._enforce_nesting:
-> 3628         if self.stack[-1] is not default:
   3629           raise AssertionError(
   3630               "Nesting violated for default stack of %s objects"

IndexError: list index out of range
```

This bug causes a confusing error message. The stack should either include the new default graph created by reset_default_graph or a warning/error message should happen when you reset the default within nested graphs.

**Comment by printdhruv** [comment]
The default graph is a property of the current thread. `tf.reset_default_graph()` function applies only to the current thread. Calling this function while a tf.Session or tf.InteractiveSession is active will result in undefined behavior. Using any previously created tf.Operation or tf.Tensor objects after calling this function will result in undefined behavior.

```
import tensorflow as tf
g = tf.Graph()
with g.as_default():
  a = tf.constant(1.0)
  b = tf.constant(1.0)
  c = a + b
```

**Comment by Thenerdstation** [comment]
Right, but you don't need an active session or any previously created ops/tensors to cause the error. Just calling reset_default_graph within nested graphs causes a confusing error.

Just this:
```python
import tensorflow as tf

g = tf.Graph()
with g.as_default():
  tf.reset_default_graph()
```

Also breaks with the same error. 
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-8377d035bd16> in <module>()
      3 g = tf.Graph()
      4 with g.as_default():
----> 5   tf.reset_default_graph()

/usr/lib/python3.5/contextlib.py in __exit__(self, type, value, traceback)
     64         if type is None:
     65             try:
---> 66                 next(self.gen)
     67             except StopIteration:
     68                 return

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py in get_controller(self, default)
   3813     finally:
   3814       if self._enforce_nesting:
-> 3815         if self.stack[-1] is not default:
   3816           raise AssertionError(
   3817               "Nesting violated for default stack of %s objects"

IndexError: list index out of range
```

I think it would be better if it actually threw the AssertionError rather than break on an index error. I'll see if I can make a PR for the fix tonight.

**Comment by mrry** [comment]
For historical context, `tf.reset_default_graph()` was never designed to be used with `with g.as_default():` context managers. I think the proper fix here is to make `tf.reset_default_graph()` fail with an informative error message when used inside a `with g.as_default():` context. I think this could be done by checking that `ops._default_graph_stack` is empty before resetting.

**Comment by printdhruv** [comment]
@mrry You are right. Many errors in tensorflow should be written in human friendly manner so that they don't have to research so hard for its cause.

**Comment by skye** [comment]
I agree we should fail with a more informative error message. @Thenerdstation @printdhruv would either of you be willing to create a PR for this?

**Comment by printdhruv** [comment]
@skye It would be so easy for author of that specific code do this. I don't have specific guidelines but let me see how can I approach this?

**Comment by Thenerdstation** [comment]
@skye Ill gladly make the PR tonight

**Comment by skye** [comment]
Great, thank you @Thenerdstation! I realize getting started with TensorFlow development is non-trivial, and  there are many small issues like this that collectively would take up a lot of the team's time, so we really appreciate external contributions!

As Derek said, you can detect if you're in a default graph context by checking if `_default_graph_stack` is empty. This will probably involve adding a new method to the `_DefaultGraph` class. Don't forget to add a unit test :)

**Comment by printdhruv** [comment]
@skye Let me try in your direction. I am enjoying this work!

**Comment by yurijvolkov** [comment]
As far as I understand `graph.as_default` adds graph on the top of stack and `tf.reset_default_graph` resets whole stack. Is it non-unintuitively? Would it be better to make `tf.reset_default_graph` remove graph from top of stack? So that it would work with nested graphs. @mrry
