### ISSUE TITLE
ios compile failed : checking whether the C compiler works... no

### ISSUE THREAD

**Issue by jakiechris** [tensorflow/tensorflow#11126]
pls help..

my config.log file:

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by Protocol Buffers configure 3.2.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --host=i386-apple-darwin14.0.0 --disable-shared --enable-cross-compile --with-protoc=/Users/jakie/tensorflow-master/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc --prefix=/Users/jakie/tensorflow-master/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_386 --exec-prefix=/Users/jakie/tensorflow-master/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_386 CFLAGS=-DNDEBUG -Os -pipe -fPIC -fno-exceptions -mios-simulator-version-min=8.0 -arch i386 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk CXX= CXXFLAGS=-DNDEBUG -Os -pipe -fPIC -fno-exceptions -std=c++11 -stdlib=libc++ -mios-simulator-version-min=8.0 -arch i386 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk LDFLAGS=-arch i386 -fembed-bitcode -mios-simulator-version-min=8.0 -stdlib=libc++ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/lib/ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/lib/system LIBS=-lc++ -lc++abi

## --------- ##

hostname = jakiedeMac.local
uname -m = x86_64
uname -r = 14.0.0
uname -s = Darwin
uname -v = Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64
Kernel configured for up to 4 processors.
4 processors are physically available.
4 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3
Primary memory available: 8.00 gigabytes
Default processor set: 102 tasks, 394 threads, 4 processors
Load average: 2.19, Mach factor: 1.88
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin

## ----------- ##

configure:2601: checking whether to enable maintainer-specific portions of Makefiles
configure:2610: result: yes
configure:2685: checking build system type
configure:2699: result: x86_64-apple-darwin14.0.0
configure:2719: checking host system type
configure:2732: result: i386-apple-darwin14.0.0
configure:2752: checking target system type
configure:2765: result: i386-apple-darwin14.0.0
configure:2808: checking for a BSD-compatible install
configure:2876: result: /usr/bin/install -c
configure:2887: checking whether build environment is sane
configure:2942: result: yes
configure:3001: checking for i386-apple-darwin14.0.0-strip
configure:3031: result: no
configure:3041: checking for strip
configure:3057: found /usr/bin/strip
configure:3068: result: strip
configure:3093: checking for a thread-safe mkdir -p
configure:3132: result: ./install-sh -c -d
configure:3139: checking for gawk
configure:3169: result: no
configure:3139: checking for mawk
configure:3169: result: no
configure:3139: checking for nawk
configure:3169: result: no
configure:3139: checking for awk
configure:3155: found /usr/bin/awk
configure:3166: result: awk
configure:3177: checking whether make sets $(MAKE)
configure:3199: result: yes
configure:3228: checking whether make supports nested variables
configure:3245: result: yes
configure:3334: checking whether UID '501' is supported by ustar format
configure:3337: result: yes
configure:3344: checking whether GID '20' is supported by ustar format
configure:3347: result: yes
configure:3355: checking how to create a ustar tar archive
configure:3366: tar --version
bsdtar 2.8.3 - libarchive 2.8.3
configure:3369: $? = 0
configure:3409: tardir=conftest.dir && eval tar --format=ustar -chf - "$tardir" >conftest.tar
configure:3412: $? = 0
configure:3416: tar -xf - <conftest.tar
configure:3419: $? = 0
configure:3421: cat conftest.dir/file
GrepMe
configure:3424: $? = 0
configure:3437: result: gnutar
configure:3515: checking for i386-apple-darwin14.0.0-gcc
configure:3545: result: no
configure:3555: checking for gcc
configure:3571: found /usr/bin/gcc
configure:3582: result: gcc
configure:3811: checking for C compiler version
configure:3820: gcc --version >&5
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
configure:3831: $? = 0
configure:3820: gcc -v >&5
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
configure:3831: $? = 0
configure:3820: gcc -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:3831: $? = 1
configure:3820: gcc -qversion >&5
clang: error: unknown argument: '-qversion'
clang: error: no input files
configure:3831: $? = 1
configure:3851: checking whether the C compiler works
configure:3873: gcc -DNDEBUG -Os -pipe -fPIC -fno-exceptions -mios-simulator-version-min=8.0 -arch i386 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk  -arch i386 -fembed-bitcode -mios-simulator-version-min=8.0 -stdlib=libc++ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/lib/ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/lib/system conftest.c -lc++ -lc++abi >&5
clang: error: unknown argument: '-fembed-bitcode'
clang: error: unknown argument: '-fembed-bitcode'
configure:3877: $? = 1
configure:3915: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Protocol Buffers"
| #define PACKAGE_TARNAME "protobuf"
| #define PACKAGE_VERSION "3.2.0"
| #define PACKAGE_STRING "Protocol Buffers 3.2.0"
| #define PACKAGE_BUGREPORT "protobuf@googlegroups.com"
| #define PACKAGE_URL ""
| #define PACKAGE "protobuf"
| #define VERSION "3.2.0"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3920: error: in `/Users/jakie/tensorflow-master/tensorflow/contrib/makefile/downloads/protobuf':
configure:3922: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_build=x86_64-apple-darwin14.0.0
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-DNDEBUG -Os -pipe -fPIC -fno-exceptions -mios-simulator-version-min=8.0 -arch i386 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk'
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=set
ac_cv_env_CXXFLAGS_value='-DNDEBUG -Os -pipe -fPIC -fno-exceptions -std=c++11 -stdlib=libc++ -mios-simulator-version-min=8.0 -arch i386 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk'
ac_cv_env_CXX_set=set
ac_cv_env_CXX_value=
ac_cv_env_DIST_LANG_set=
ac_cv_env_DIST_LANG_value=
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-arch i386 -fembed-bitcode -mios-simulator-version-min=8.0 -stdlib=libc++ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/lib/ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/lib/system'
ac_cv_env_LIBS_set=set
ac_cv_env_LIBS_value='-lc++ -lc++abi'
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_OBJCFLAGS_set=
ac_cv_env_OBJCFLAGS_value=
ac_cv_env_OBJC_set=
ac_cv_env_OBJC_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=i386-apple-darwin14.0.0
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=i386-apple-darwin14.0.0
ac_cv_path_install='/usr/bin/install -c'
ac_cv_prog_AWK=awk
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_ac_ct_STRIP=strip
ac_cv_prog_make_make_set=yes
ac_cv_target=i386-apple-darwin14.0.0
am_cv_make_support_nested_variables=yes
am_cv_prog_tar_ustar=gnutar

## ----------------- ##

ACLOCAL='${SHELL} /Users/jakie/tensorflow-master/tensorflow/contrib/makefile/downloads/protobuf/missing aclocal-1.15'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AR=''
AUTOCONF='${SHELL} /Users/jakie/tensorflow-master/tensorflow/contrib/makefile/downloads/protobuf/missing autoconf'
AUTOHEADER='${SHELL} /Users/jakie/tensorflow-master/tensorflow/contrib/makefile/downloads/protobuf/missing autoheader'
AUTOMAKE='${SHELL} /Users/jakie/tensorflow-master/tensorflow/contrib/makefile/downloads/protobuf/missing automake-1.15'
AWK='awk'
BUILD_EXEEXT=''
BUILD_OBJEXT=''
CC='gcc'
CCDEPMODE=''
CC_FOR_BUILD=''
CFLAGS='-DNDEBUG -Os -pipe -fPIC -fno-exceptions -mios-simulator-version-min=8.0 -arch i386 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk'
CFLAGS_FOR_BUILD=''
CPP=''
CPPFLAGS=''
CPPFLAGS_FOR_BUILD=''
CPP_FOR_BUILD=''
CXX=''
CXXCPP=''
CXXCPPFLAGS_FOR_BUILD=''
CXXCPP_FOR_BUILD=''
CXXDEPMODE=''
CXXFLAGS='-DNDEBUG -Os -pipe -fPIC -fno-exceptions -std=c++11 -stdlib=libc++ -mios-simulator-version-min=8.0 -arch i386 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk'
CXXFLAGS_FOR_BUILD=''
CXX_FOR_BUILD=''
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
DIST_LANG='all'
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP=''
EXEEXT=''
FGREP=''
GCC_FALSE=''
GCC_TRUE=''
GREP=''
HAVE_CXX11=''
HAVE_PTHREAD_FALSE=''
HAVE_PTHREAD_TRUE=''
HAVE_ZLIB_FALSE=''
HAVE_ZLIB_TRUE=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
ISAINFO=''
LD=''
LDFLAGS='-arch i386 -fembed-bitcode -mios-simulator-version-min=8.0 -stdlib=libc++ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/lib/ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/lib/system'
LDFLAGS_FOR_BUILD=''
LIBOBJS=''
LIBS='-lc++ -lc++abi'
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LT_SYS_LIBRARY_PATH=''
MAINT=''
MAINTAINER_MODE_FALSE='#'
MAINTAINER_MODE_TRUE=''
MAKEINFO='${SHELL} /Users/jakie/tensorflow-master/tensorflow/contrib/makefile/downloads/protobuf/missing makeinfo'
MANIFEST_TOOL=''
MKDIR_P='./install-sh -c -d'
NM=''
NMEDIT=''
OBJC=''
OBJCDEPMODE=''
OBJCFLAGS=''
OBJC_CONFORMANCE_TEST_FALSE=''
OBJC_CONFORMANCE_TEST_TRUE=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE='protobuf'
PACKAGE_BUGREPORT='protobuf@googlegroups.com'
PACKAGE_NAME='Protocol Buffers'
PACKAGE_STRING='Protocol Buffers 3.2.0'
PACKAGE_TARNAME='protobuf'
PACKAGE_URL=''
PACKAGE_VERSION='3.2.0'
PATH_SEPARATOR=':'
POW_LIB=''
PROTOBUF_OPT_FLAG=''
PROTOC=''
PTHREAD_CC=''
PTHREAD_CFLAGS=''
PTHREAD_LIBS=''
RANLIB=''
SED=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP='strip'
USE_EXTERNAL_PROTOC_FALSE=''
USE_EXTERNAL_PROTOC_TRUE=''
VERSION='3.2.0'
ac_ct_AR=''
ac_ct_CC='gcc'
ac_ct_CC_FOR_BUILD=''
ac_ct_CXX=''
ac_ct_CXX_FOR_BUILD=''
ac_ct_DUMPBIN=''
ac_ct_OBJC=''
acx_pthread_config=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__fastdepOBJC_FALSE=''
am__fastdepOBJC_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='tar --format=ustar -chf - "$$tardir"'
am__untar='tar -xf -'
bindir='${exec_prefix}/bin'
build='x86_64-apple-darwin14.0.0'
build_alias=''
build_cpu='x86_64'
build_os='darwin14.0.0'
build_vendor='apple'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='/Users/jakie/tensorflow-master/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_386'
host='i386-apple-darwin14.0.0'
host_alias='i386-apple-darwin14.0.0'
host_cpu='i386'
host_os='darwin14.0.0'
host_vendor='apple'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /Users/jakie/tensorflow-master/tensorflow/contrib/makefile/downloads/protobuf/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/Users/jakie/tensorflow-master/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_386'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
subdirs=''
sysconfdir='${prefix}/etc'
target='i386-apple-darwin14.0.0'
target_alias=''
target_cpu='i386'
target_os='darwin14.0.0'
target_vendor='apple'

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "Protocol Buffers"
#define PACKAGE_TARNAME "protobuf"
#define PACKAGE_VERSION "3.2.0"
#define PACKAGE_STRING "Protocol Buffers 3.2.0"
#define PACKAGE_BUGREPORT "protobuf@googlegroups.com"
#define PACKAGE_URL ""
#define PACKAGE "protobuf"
#define VERSION "3.2.0"

configure: exit 77

**Comment by jakiechris** [comment]
control console outputs: 


Making distclean in benchmarks
 rm -f generate-datasets cpp-benchmark
test -z "benchmarks.pb.cc benchmarks.pb.h benchmark_messages_proto3.pb.cc benchmark_messages_proto3.pb.h benchmark_messages_proto2.pb.cc benchmark_messages_proto2.pb.h protoc_middleman protoc_middleman2 dataset.*" || rm -f benchmarks.pb.cc benchmarks.pb.h benchmark_messages_proto3.pb.cc benchmark_messages_proto3.pb.h benchmark_messages_proto2.pb.cc benchmark_messages_proto2.pb.h protoc_middleman protoc_middleman2 dataset.*
rm -rf .libs _libs
rm -f *.o
rm -f *.lo
rm -f *.tab.c
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -rf ./.deps
rm -f Makefile
rm -rf .libs _libs
Cleaning any ObjC pyc files
rm -f *.lo
test -z "protobuf.pc protobuf-lite.pc" || rm -f protobuf.pc protobuf-lite.pc
test . = "." || test -z "" || rm -f 
rm -f config.h stamp-h1
rm -f libtool config.lt
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -f cscope.out cscope.in.out cscope.po.out cscope.files
rm -f config.status config.cache config.log configure.lineno config.status.lineno
rm -f Makefile
+ ./configure --host=i386-apple-darwin14.0.0 --disable-shared --enable-cross-compile --with-protoc=/Users/jakie/tensorflow-master/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc --prefix=/Users/jakie/tensorflow-master/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_386 --exec-prefix=/Users/jakie/tensorflow-master/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_386 'CFLAGS=-DNDEBUG -Os -pipe -fPIC -fno-exceptions -mios-simulator-version-min=8.0 -arch i386 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk' CXX= 'CXXFLAGS=-DNDEBUG -Os -pipe -fPIC -fno-exceptions -std=c++11 -stdlib=libc++ -mios-simulator-version-min=8.0 -arch i386 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk' 'LDFLAGS=-arch i386 -fembed-bitcode -mios-simulator-version-min=8.0 -stdlib=libc++ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/lib/ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/lib/system' 'LIBS=-lc++ -lc++abi'
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-apple-darwin14.0.0
checking host system type... i386-apple-darwin14.0.0
checking target system type... i386-apple-darwin14.0.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for i386-apple-darwin14.0.0-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking for i386-apple-darwin14.0.0-gcc... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/jakie/tensorflow-master/tensorflow/contrib/makefile/downloads/protobuf':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by jakiechris** [comment]
jakiedeMac:~ jakie$ /usr/bin/gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
jakiedeMac:~ jakie$ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.0.0

**Comment by jakiechris** [comment]
my mac os version is 10.10
there seems a solution that brew install apple-gcc42 , but faild on my osx:


jakiedeMac:~ jakie$ brew install apple-gcc42
Updating Homebrew...

apple-gcc42: This formula either does not compile or function as expected on macOS
versions newer than Mavericks due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.

**Comment by wenkesj** [comment]
I had this problem as well!

I had `/usr/bin/gcc` symlinked to a `homebrew` installation `/usr/local/bin/gcc` which was `gcc4.9`. The `homebrew` distribution of `gcc` threw the same error you're getting. 

I fixed this by unlinking the `brew` installation from `/usr/local/bin/gcc` and kept the `clang` that is originally installed on **macOS Sierra**  (`/usr/bin/gcc`).

```sh
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Note:** It may be necessary, but not recommended to use
```sh
$ sudo tensorflow/contrib/makefile/build_all_ios.sh
```

**Comment by wenkesj** [comment]
@jakiechris As a precursor, ensure you have updated `xcode` tools from the `Terminal` or `App Store`.

```sh
$ xcode-select --install
```

**Comment by jakiechris** [comment]
@wenkesj 
Hi Sam：
      thks 4 reply
      
      problem solved~  i used osx 10.10 and a low version of xcode, which cannot work well. 
      
      solution:
      1. osx 10.12 on vmware 12
      2. xcode 8.3.2
      3. CommandLineToolsforXcode8.3.2.dmg

**Comment by wenkesj** [comment]
@jakiechris good to hear!

**Comment by ali01** [comment]
Glad this was resolved!
