### ISSUE TITLE
No module named '_pywrap_tensorflow_internal'

### ISSUE THREAD

**Issue by laiyi55** [tensorflow/tensorflow#11139]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
D:\Users\laiyi\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     17         try:
---> 18             return importlib.import_module(mname)
     19         except ImportError:

D:\Users\laiyi\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127

D:\Users\laiyi\Anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

D:\Users\laiyi\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

D:\Users\laiyi\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

D:\Users\laiyi\Anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

D:\Users\laiyi\Anaconda3\lib\importlib\_bootstrap.py in module_from_spec(spec)

D:\Users\laiyi\Anaconda3\lib\importlib\_bootstrap_external.py in create_module(self, spec)

D:\Users\laiyi\Anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
D:\Users\laiyi\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     40     sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 41   from tensorflow.python.pywrap_tensorflow_internal import *
     42   from tensorflow.python.pywrap_tensorflow_internal import __version__

D:\Users\laiyi\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>()
     20             return importlib.import_module('_pywrap_tensorflow_internal')
---> 21     _pywrap_tensorflow_internal = swig_import_helper()
     22     del swig_import_helper

D:\Users\laiyi\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     19         except ImportError:
---> 20             return importlib.import_module('_pywrap_tensorflow_internal')
     21     _pywrap_tensorflow_internal = swig_import_helper()

D:\Users\laiyi\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127

ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-a649b509054f> in <module>()
----> 1 import tensorflow

D:\Users\laiyi\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>()
     22
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26

D:\Users\laiyi\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>()
     47 import numpy as np
     48
---> 49 from tensorflow.python import pywrap_tensorflow
     50
     51 # Protocol buffers

D:\Users\laiyi\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     50 for some common reasons and solutions.  Include the entire stack trace
     51 above this error message when asking for help.""" % traceback.format_exc()
---> 52   raise ImportError(msg)
     53
     54 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "D:\Users\laiyi\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Users\laiyi\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\laiyi\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Users\laiyi\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Users\laiyi\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "D:\Users\laiyi\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by Frefreak** [comment]
additional information: pytorch seems to [work](https://img.vim-cn.com/1a/2cd097681a938130249c2cd21cdda990101561.jpg) correctly

**Comment by laiyi55** [comment]
already solved problem， convert cudnn version from 6.0 to 5.1

**Comment by summerlove66** [comment]
Hi ,
can you tell me ,how to solved this problem .I got the same problme now  . it is make me crazy ..

**Comment by zfogg** [comment]
@summerlove66 you should try @laiyi55 's advice! switching to `cudnn-8.0-windows10-x64-v5.1` was the solution for me. even on CUDA 9.0 RC1

**Comment by liuny05** [comment]
Solved my problem. Note that the cudnn version depends on you tensorflow version. In tensorflow1.3.0 on windows the version of cudnn should be v6.0 or v6.1.

**Comment by user7654** [comment]
On Win7, W7, Windows 7 try to install   Microsoft Visual C++ 2015 Redistributable Update 3 
    https://www.microsoft.com/en-us/download/details.aspx?id=53587
first. It helped for me.
see: https://github.com/tensorflow/tensorflow/issues/5949
