### ISSUE TITLE
wide_n_deep Tutorial example not working

### ISSUE THREAD

**Issue by sddi** [tensorflow/tensorflow#11137]
**cd** tensorflow/tensorflow/examples/learn/
**python** wide_n_deep_tutorial.py
## it shows that :
Traceback (most recent call last):
  File "wide_n_deep_tutorial.py", line 36, in <module>
    gender = tf.feature_column.categorical_column_with_vocabulary_list(
AttributeError: 'module' object has no attribute 'feature_column'
My tensorflow is '1.0.0-rc2', and do i need to upgrade?
thank you!

**Comment by terrytangyuan** [comment]
Yes you need to upgrade

**Comment by sddi** [comment]
Hi, @terrytangyuan ,  after upgrade the tf, I got another problem while running wide_n_deep_tutorial.py, they say that:
  File "wide_n_deep_tutorial.py", line 149, in 
    m = tf.estimator.DNNLinearCombinedClassifier(
AttributeError: 'module' object has no attribute 'DNNLinearCombinedClassifier'

**Comment by terrytangyuan** [comment]
A lot of changes have been merged in today. I think it should work once you try the new nightly build tomorrow or so.

**Comment by sddi** [comment]
ok, tomorrow i will try the newest~~~ :D

**Comment by sddi** [comment]
@terrytangyuan  I try the newest wide_n_deep tutorial , but I get the msg like this:
  File "wide_n_deep_tutorial.py", line 147, in build_estimator
    m = tf.estimator.DNNLinearCombinedClassifier(
AttributeError: 'module' object has no attribute 'DNNLinearCombinedClassifier'
how can i run it ?
