### ISSUE TITLE
Self-contained source code package of tensorflow

### ISSUE THREAD

**Issue by datainfer** [tensorflow/tensorflow#11149]
Dear TensorFlow development team,
    Government regularization on medical software requires software to be compiled from fully controllable source code. Downloading from outside of the manufacture is not permitted. This literally implies that medical software should be able to compile without Internet connection. Currently, the bazel compilation procedure download from Internet. We post this request for a self-contained package of tensorflow.

**Comment by MarvinTeichmann** [comment]
+1 for me. There are many reasonable situations when it is not desired and/or feasible to download additional packages at compile time.

**Comment by joshua-xia** [comment]
There are several third-party open source source code are download  when build, maybe you can download manually and store on local machine and modify the url of the source repository so that you can build without download again.

**Comment by Saduf2019** [comment]
@datainfer 
Is this still an issue, could you please check in the latest version as many issues have been fixed in the latest version
