### ISSUE TITLE
Cannot build TensorFlow on macOS 10.12

### ISSUE THREAD

**Issue by wenhan-wu** [tensorflow/tensorflow#11180]
When I trying to build TensorFlow with avx, avx2, fma, sse4,1 sse4,2, it shown that
```
clang: error: no such file or directory: 'msse4.1'
clang: error: no such file or directory: 'msse4.2'
```
clang doesn't support sse4.1 and sse4.2?
And I can not change the bazel compiler to gcc anyway

**Comment by ali01** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by vade** [comment]
Building on OS X with optimizations totally works (sans GPU of course). Something like:

bazel build  -c opt --copt=-mavx --copt=-mfma --copt=-mavx2 //tensorflow:libtensorflow_cc.so

**Comment by wwh2259253** [comment]
@vade when I trying to execute
`bzael build -c opt --copt=-marx --copt=-mavx2 --copt=-mfma --copt=-msse4.1 --copt=-msse4.2 //tensorflow:libtensorflow_cc.so`
I always got this error.

**Comment by wwh2259253** [comment]
@ali01 
Sorry, this is the first time I post an issue.
```
hardware: mid-2015 Macbook Pro with R370X
os: macOS Sierra 10.12
tf version: 1.2
```
```
$ ./configure
WARNING: ignoring http_proxy in environment.
...............
You have bazel 0.5.2-homebrew installed.
Please specify the location of python. [Default is /XXX/anaconda/bin/python]:
Found possible Python library paths:
  /XXX/anaconda/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/XXX/anaconda/lib/python3.6/site-packages]

Using python library path: /XXX/anaconda/lib/python3.6/site-packages
Do you wish to build TensorFlow with MKL support? [y/N] n
No MKL support will be enabled for TensorFlow
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: -march=-mavx2,-mfma,-mavx,-msse4.1,-msse4.2
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] n
No XLA JIT support will be enabled for TensorFlow
Do you wish to build TensorFlow with VERBS support? [y/N] n
No VERBS support will be enabled for TensorFlow
Do you wish to build TensorFlow with OpenCL support? [y/N] n
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] n
No CUDA support will be enabled for TensorFlow
Do you wish to build TensorFlow with MPI support? [y/N] n
MPI support will not be enabled for TensorFlow
Configuration finished

$ bazel build --config=opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=msse4.1 --copt=msse4.2 //tensorflow/tools/pip_package:build_pip_package
WARNING: ignoring http_proxy in environment.
WARNING: /XXX/Downloads/tensorflow-master/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /XXX/Downloads/tensorflow-master/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_XXX/18bc397ce425ce2714a2948ab0a1ec62/external/farmhash_archive/BUILD.bazel:19:1: C++ compilation of rule '@farmhash_archive//:farmhash' failed: wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 38 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
clang: error: no such file or directory: 'msse4.1'
clang: error: no such file or directory: 'msse4.2'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.786s, Critical Path: 0.27s
```

**Comment by gunan** [comment]
if you are going to use tf on the same machine, why not just use `-march=native`, or our convenience option, `--config=opt`?

**Comment by vade** [comment]
I suspect thats the issue, and the comma's etc are not parsed by the config script correctly.

**Comment by cy89** [comment]
@wwh2259253, would you please try @gunan's suggestion, and let us know whether it helps?

**Comment by peterhanneman** [comment]
I was experiencing numerous issues including this one and finally solved them all by installing the latest Xcode v8.3.3 then running:

```bazel clean --expunge```
```./configure``` (accepting the default ```-march=native``` option)
```bazel build --config=opt --xcode_version=8.3.3 --macos_sdk_version=10.12 //tensorflow/tools/pip_package:build_pip_package```

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
