### ISSUE TITLE
why use "x_is_dict" to check y?

### ISSUE THREAD

**Issue by ylmeng** [tensorflow/tensorflow#11192]
In tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py
On L325:
`self._y = None if y is None else \
      dict([(k, check_array(v, v.dtype)) for k, v in list(y.items())]) if x_is_dict else check_array(y, y.dtype)
`
   
I happened to have a implementation where x is a dict but y is a numpy array, so I got an error. I wonder why we do not use y_is_dict here?

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ylmeng** [comment]
Ok thanks. I do think it is a bug though. A wrong variable is used here.

**Comment by cy89** [comment]
Sorry, I missed that. I agree.

**Comment by cy89** [comment]
#10403 looks like the same problem, with a little more context about the x/y confusion.
