### ISSUE TITLE
AttributeError: 'module' object has no attribute 'prepare_attention'

### ISSUE THREAD

**Issue by dylib** [tensorflow/tensorflow#11199]
**Tensorflow Version**:
```
('v1.1.0-rc0-61-g1ec6ed5', '1.1.0')
```
**Issue**:
```
$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.contrib.seq2seq.prepare_attention()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'prepare_attention'
```
I'm not sure what why the tf.contrib.seq2seq cannot find [`prepare_attention`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/seq2seq/prepare_attention), any clue to why that is would be appreciated.

**Comment by printdhruv** [comment]
Hi,

1. It won't compile as you have `tensor-flow API 1.1.0` which doesn't have `tf.contrib.seq2seq.prepare_attention()` and the link which you are referring is for `API 1.0`.

2. For your existing version `1.1.0` the ` tf.contrib.seq2seq.DynamicAttentionWrapper` will work. Refer link [https://www.tensorflow.org/versions/r1.1/api_docs/python/tf/contrib/seq2seq/DynamicAttentionWrapper](https://www.tensorflow.org/versions/r1.1/api_docs/python/tf/contrib/seq2seq/DynamicAttentionWrapper)

3. If you want to use your existing code than you have to upgrade your version of tensor flow by executing i.e. `pip3 install --upgrade tensorflow`
 
4. Please refer suggestions and guidelines listed here [link](https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md) before raising an issue.

**Comment by dylib** [comment]
Regarding your item #3, I suppose you mean downgrade instead of upgrade? In the API documentation for `1.2.x` it doesn't appear `prepare_attention` went beyond `1.0` ... 

Also, sorry for raising the issue, I was used to seeing `deprecated` labels next to the old functions and was completely oblivious to the fact I was looking at `1.0` API documentation. Apparently you guys aren't bothering with that perhaps anymore...

Anyway, thank you! Your information was helpful.

**Comment by printdhruv** [comment]
Hi,
     Google hasn't hired me unfortunately.Yes, you are right that for item(3) you have to use the latest API , not your existing one.

**Comment by andydavis1** [comment]
@printdhruv thanks for your help on this one!
