### ISSUE TITLE
EC2 g2.2xlarge: Ignoring gpu device (GRID K520) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.

### ISSUE THREAD

**Issue by markusdr** [tensorflow/tensorflow#112]
I got this error while running on an Amazon EC2 g2.2xlarge instance:

    tensorflow/core/common_runtime/gpu/gpu_device.cc:611
     Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) 
    with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
    Invalid argument: Cannot assign a device to node 'Const/_2': Could not satisfy explicit device specification '/gpu:0'
	 [[Node: Const/_2 = Const[dtype=DT_INT32, value=Tensor<type: int32 shape: [] values: 0>, _device="/gpu:0"]()]])

**Comment by vrv** [comment]
De-duping with https://github.com/tensorflow/tensorflow/issues/25
