### ISSUE TITLE
L-Op and R-Op in Tensorflow?

### ISSUE THREAD

**Issue by hyperdo** [tensorflow/tensorflow#11203]
Are there currently equivalents of [theano.gradient.Lop](http://deeplearning.net/software/theano/tutorial/gradients.html#l-operator) and [theano.gradient.Rop](http://deeplearning.net/software/theano/tutorial/gradients.html#r-operator) implemented in Tensorflow? If not, is this a feature that is in the pipeline? I'm trying to port some code over but can't seem to find a way to do this yet. Thank you!

**Comment by adler-j** [comment]
`Lop` is equivalent to `tf.gradients`, but tensorflow does not explicitly have `Rop` built in.

With that said, [you can use some tricks to get it done](https://www.reddit.com/r/MachineLearning/comments/6gvv0o/r_first_blog_post_a_new_trick_for_calculating/).

**Comment by hyperdo** [comment]
Thanks so much! Closing now.

**Comment by yang-song** [comment]
`Rop` can be implemented with `tf.gradients` as well. See, e.g., https://gist.github.com/yang-song/07392ed7d57a92a87968e774aef96762
