### ISSUE TITLE
gridlstm

### ISSUE THREAD

**Issue by jeansely** [tensorflow/tensorflow#11219]
Hello,
 
1- where can find an example for GRIDLSTM(2D) or multi_diagonal . i search in net but not found.
2- known that tensorflow support from keras . how can insert a tensorflow layer in keras .

THANKS

**Comment by AFAgarap** [comment]
I think it's the other way around; Keras may be implemented in TensorFlow. I haven't heard of TF in Keras yet. @jeansely

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
