### ISSUE TITLE
Error encountered when serializing moving_average_variables

### ISSUE THREAD

**Issue by bernardopires** [tensorflow/tensorflow#1123]
I compiled Tensorflow from source. Running cifar10_train.py outputs the following warning message:

WARNING:tensorflow:Error encountered when serializing moving_average_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
unbound method to_proto() must be called with Variable instance as first argument (got Tensor instance instead)

**Comment by vrv** [comment]
Also @shlens in case he knows.

**Comment by ZhengBitFusion** [comment]
Have the same issue. And the training command freezes. In fact, even the mnist example on setup page freezes too.

**Comment by mrry** [comment]
Thanks for pointing out this warning! It's benign (for the training process), but unfortunate to have this in an example model. I have a patch in the pipeline that will fix the root cause for the warning.

**Comment by trinity77** [comment]
Issue Cleanup
