### ISSUE TITLE
quantify the mobilenet

### ISSUE THREAD

**Issue by wm901115nwpu** [tensorflow/tensorflow#11235]
I try to quantify the mobilenet(in the https://github.com/tensorflow/models/blob/master/object_detection/g3doc/detection_model_zoo.md ssd_mobilenet_v1_coco), the tensorflow I use is v1.2,
bazel build tensorflow/tools/quantization:quantize_graph \
&& bazel-bin/tensorflow/tools/quantization/quantize_graph \
--input=bazel build tensorflow/tools/quantization:quantize_graph \
&& bazel-bin/tensorflow/tools/quantization/quantize_graph \
--input=ssd_mobilenet_v1_coco_11_06_2017/frozen_inference_graph.pb
--output_node_names="  " --print_nodes --output=/tmp/quantized_graph.pb \
--mode=eightbit --logtostderr
but I don't decide the out_node_names .

**Comment by nisseb** [comment]
I don't have a working solution but I have come a little longer on this issue.

You can use this tool to summarize your graph:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms#inspecting-graphs

It will give you suggestions for outputs:
Found 4 possible outputs: (name=detection_boxes, op=Identity) (name=detection_scores, op=Identity) (name=detection_classes, op=Identity) (name=num_detections, op=Identity)

So you write:
--output_node_names="detection_boxes,detection_scores,detection_classes,num_detections".

However, this will not work either and it might be related to the comment by mddrill 23may:
https://github.com/tensorflow/tensorflow/issues/8347

He basically states that the output nodes in the MobileNet are op=Identity which are removed by quantize_graph.py. 

His fix does not work for me since my quantized graph is the same size as before quantization. It seems like the script ends up doing nothing.

I'm not sure if the summarize tool lists the wrong nodes for the output or if the quantization tool does not work properly on the op=Identity.

Best

**Comment by wm901115nwpu** [comment]
@nisseb for output_node_name in output_node_names
KeyError: 'detection_boxes'

**Comment by nisseb** [comment]
Yes, that is what I got as well, because of what I wrote after:
"However, this will not work either ..."

If you run the inspecting graphs script you see that all output nodes are IdentityOp which are removed by the quantize graph script (I think (?)).

Maybe try your luck with transform_graph:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms#inspecting-graphs
Which unfortunately also has an issue posted:
https://stackoverflow.com/questions/44832492/tensorflow-ssd-mobilenet-model-accuracy-drop-after-quantization-using-transform

Let me know if you solve it!

Best

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by wujiahongPKU** [comment]
I have the same question and I do not know how to resolve it ,could give me some sugessions

**Comment by wm901115nwpu** [comment]
I still solve it.

**Comment by wm901115nwpu** [comment]
@wujiahongPKU I still solve it.

**Comment by wujiahongPKU** [comment]
@wm901115nwpu  please tell me the way to solve it,as detailed as possible,Thanks!

**Comment by offbye** [comment]
I have quantized the ssd-mobilenet_v1 model success, but when I run on android demo, the model can not be loaded.  i have create a issue [here](https://github.com/tensorflow/models/issues/2853)

**Comment by shinya321** [comment]
I have the same issue. Does anyone solve it?
KeyError: 'detection_boxes'

**Comment by alexcdot** [comment]
@shinya321 If you're using "--mode=quantize" on the latest master commit of tensorflow, I found that there is a bug in the code that produces a KeyError at https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/tools/quantization/quantize_graph.py#L490

That line should be changed from:
```
if self.already_visited[current_node.name]:
```
to:
```
if current_node.name in self.already_visited and self.already_visited[current_node.name]:
```

**Comment by shinya321** [comment]
@alexcdot Thank you so much for replying me!
I updated "quantize_graph.py" as you said, and try to quantize ssd-mobilenet v1 model as below:
<pre>
python quantize_graph_new.py --input=frozen_inference_graph.pb --output_node_names="detection_scores,detection_classes,num_detections" --output=frozen_8bit_graph.pb --mode=eightbit
</pre>

Next I try to execute inference by using frozen graph "frozen_8bit_graph.pb",
but still it does not work.... like this.↓↓
<pre>
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
c:\users\s120077.sei\appdata\local\continuum\anaconda3\envs\takubo\lib\site-packages\tensorflow\python\framework\importer.py in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    488           results = c_api.TF_GraphImportGraphDefWithResults(
--> 489               graph._c_graph, serialized, options)  # pylint: disable=protected-access
    490           results = c_api_util.ScopedTFImportGraphDefResults(results)

InvalidArgumentError: Node 'FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/BatchNorm/batchnorm/mul_1_eightbit_reshape___hat__FeatureExtractor/Assert/Assert': Control dependencies must come after regular dependencies

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-5-88c9617d43b8> in <module>()
     15     serialized_graph = fid.read()
     16     od_graph_def.ParseFromString(serialized_graph)
---> 17     tf.import_graph_def(od_graph_def, name='')
     18 
     19 

c:\users\s120077.sei\appdata\local\continuum\anaconda3\envs\takubo\lib\site-packages\tensorflow\python\util\deprecation.py in new_func(*args, **kwargs)
    430                 'in a future version' if date is None else ('after %s' % date),
    431                 instructions)
--> 432       return func(*args, **kwargs)
    433     return tf_decorator.make_decorator(func, new_func, 'deprecated',
    434                                        _add_deprecated_arg_notice_to_docstring(

c:\users\s120077.sei\appdata\local\continuum\anaconda3\envs\takubo\lib\site-packages\tensorflow\python\framework\importer.py in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    491         except errors.InvalidArgumentError as e:
    492           # Convert to ValueError for backwards compatibility.
--> 493           raise ValueError(str(e))
    494 
    495       # Create _DefinedFunctions for any imported functions.

ValueError: Node 'FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/BatchNorm/batchnorm/mul_1_eightbit_reshape___hat__FeatureExtractor/Assert/Assert': Control dependencies must come after regular dependencies

</pre>

I could execute inference program by using no quantized model.
If you know, please tell me why the program does not work.

**Comment by daixiangzi** [comment]
> @alexcdot Thank you so much for replying me!
> I updated "quantize_graph.py" as you said, and try to quantize ssd-mobilenet v1 model as below:
> 
> python quantize_graph_new.py --input=frozen_inference_graph.pb --output_node_names="detection_scores,detection_classes,num_detections" --output=frozen_8bit_graph.pb --mode=eightbit
> Next I try to execute inference by using frozen graph "frozen_8bit_graph.pb",
> but still it does not work.... like this.↓↓
> 
> ---------------------------------------------------------------------------
> InvalidArgumentError                      Traceback (most recent call last)
> c:\users\s120077.sei\appdata\local\continuum\anaconda3\envs\takubo\lib\site-packages\tensorflow\python\framework\importer.py in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
>     488           results = c_api.TF_GraphImportGraphDefWithResults(
> --> 489               graph._c_graph, serialized, options)  # pylint: disable=protected-access
>     490           results = c_api_util.ScopedTFImportGraphDefResults(results)
> 
> InvalidArgumentError: Node 'FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/BatchNorm/batchnorm/mul_1_eightbit_reshape___hat__FeatureExtractor/Assert/Assert': Control dependencies must come after regular dependencies
> 
> During handling of the above exception, another exception occurred:
> 
> ValueError                                Traceback (most recent call last)
>  in ()
>      15     serialized_graph = fid.read()
>      16     od_graph_def.ParseFromString(serialized_graph)
> ---> 17     tf.import_graph_def(od_graph_def, name='')
>      18 
>      19 
> 
> c:\users\s120077.sei\appdata\local\continuum\anaconda3\envs\takubo\lib\site-packages\tensorflow\python\util\deprecation.py in new_func(*args, **kwargs)
>     430                 'in a future version' if date is None else ('after %s' % date),
>     431                 instructions)
> --> 432       return func(*args, **kwargs)
>     433     return tf_decorator.make_decorator(func, new_func, 'deprecated',
>     434                                        _add_deprecated_arg_notice_to_docstring(
> 
> c:\users\s120077.sei\appdata\local\continuum\anaconda3\envs\takubo\lib\site-packages\tensorflow\python\framework\importer.py in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
>     491         except errors.InvalidArgumentError as e:
>     492           # Convert to ValueError for backwards compatibility.
> --> 493           raise ValueError(str(e))
>     494 
>     495       # Create _DefinedFunctions for any imported functions.
> 
> ValueError: Node 'FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/BatchNorm/batchnorm/mul_1_eightbit_reshape___hat__FeatureExtractor/Assert/Assert': Control dependencies must come after regular dependencies
> 
> I could execute inference program by using no quantized model.
> If you know, please tell me why the program does not work.

i meet same problem,appear error,when i run inference program use quanrtized pd file.
ValueError: Node 'FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/convolution_eightbit_reshape___hat__FeatureExtractor/Assert/Assert': Control dependencies must come after regular dependencies
