### ISSUE TITLE
About if tensorflow can use flask to mount in IIS, use like as an web API to use? 

### ISSUE THREAD

**Issue by jxua** [tensorflow/tensorflow#11233]
I set up a tensorflow system, use flask grammar to set up . And in local computer, all run ok, no error.
But when I mount it in IIS, as Web API to use, It always show FASTCGI error. Does tensorflow  incompatiable with IIS?

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
