### ISSUE TITLE
[solved, solution is on the bottom] link libtensorflow-core.a to c++ cross comple project

### ISSUE THREAD

**Issue by jakiechris** [tensorflow/tensorflow#11231]
Hi ~ all~

   i followed:
      https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/README.md
  and successfully got ios, android, linux lib files in contrib\makefile\gen\lib.

  i'm developing a cross platform sdk lib which is written by c++.  my plan is using my sdk c++ code to call tensorflow lib. 

   here is my question: where are the h files according to the tensorflow lib file ? 

   commenly, a lib project's out put is not only a binary file , but also h files .

**Comment by jakiechris** [comment]
some one help me~~

**Comment by jakiechris** [comment]
under linux , i copied libtensorflow-core.a to /usr/local/lib and tensorflow folder to /usr/local/include,
then i copied benchmark_model.cc and benchmark_model.h to my own project , 
and i -ltensorflow-core in my project, then run into a runtime issue:

/root/61_ecg_sdk/src/mytensorflow/benchmark_model.cc:533: undefined reference to `tensorflow::TestReporter::TestReporter(std::string const&, std::string const&)'


pls tell me how to get complete header files according to the binary file of libtensorflow-core.a ?

**Comment by jakiechris** [comment]
this link said the libtensorflow-core.a is incomplete..

https://github.com/tensorflow/tensorflow/issues/7813

**Comment by jakiechris** [comment]
some one help me..

**Comment by jakiechris** [comment]
is all header files of libtensorflow-core.a in tensorflow\contrib\makefile\gen\proto\tensorflow ?

**Comment by jakiechris** [comment]
i searched the compile trace log , found that only part of the objs are packed into libtensorflow-core.a.

tensorflow/core/util/reporter.o is not packed to libtensorflow-core.a , which benchmark needed .

**Comment by jakiechris** [comment]
found a link to test libtensorflow-core.a
https://tebesu.github.io/posts/Training-a-TensorFlow-graph-in-C++-API

**Comment by jakiechris** [comment]
this post helps me a lot:
https://github.com/tensorflow/tensorflow/issues/3308

**Comment by jakiechris** [comment]
there are really several important notations of tensorflow/contrib/makefile :

the header files of libtensorflow.a consists of generated h files in tensorflow/contrib/makefile/gen and in tensor source.

tensor depends on protobuf to serial class objects to file. fortunely, protobuf lib file is also generated in gen folder.

all platforms has different shell scripts to build tensor, but share the same Makefile , who is in tensorflow/contrib/makefile/ and determines which source file would be added to libtensorflow.a. 
Defaultly libtensorflow.a contains very few source files. we need change Makefile content to solve
runtime issues. 

after reading the Makefile carefully, we found that we just simply config tf_op_files.txt to add and delete source files in tensorflow/core/kernels.

**Comment by jakiechris** [comment]
so when you have your own c++ project , 
i recommend you to compile tensor first, 
and then copy the entire tensorflow folder to your c++ project, 
in your c++ project , config -I    -L    -l  paths to point to the tensorflow folder.

compile errors always caused by -I -L path not found and easy to solve
if there are runtime errors , modify  tensorflow/contrib/makefile/gen/Makefile to add sources to libtensorflow.a, then re-run your c++ project after  the new libtensorflow.a is built.

**Comment by arnaldog12** [comment]
Hi, @jakiechris 
thanks for your instructions. I did a Medium post about it to help others as well:
https://medium.com/me/stats/post/5c762dbdd5d4
