### ISSUE TITLE
The data type conversion between int32 and float32

### ISSUE THREAD

**Issue by yylonly** [tensorflow/tensorflow#11245]
My project require convert the data type of tensor (dtype=float32) to int32, and then I need turn the dtype back (from int32 to float32) after some operations.
 The code is

>  y = tf.to_int32(x)
>  bitwiseXor = tf.bitwise.bitwise_xor(y, key)
>  z = tf.to_float(bitwiseXor)

But following errors appears, how to solve it?

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
>     preferred_dtype=default_dtype)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 675, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
>     tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_util.py", line 364, in make_tensor_proto
>     raise ValueError("None values not supported.")
> ValueError: None values not supported.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 504, in apply_op
>     values, as_ref=input_arg.is_ref).dtype.name
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 675, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
>     tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_util.py", line 364, in make_tensor_proto
>     raise ValueError("None values not supported.")
> ValueError: None values not supported.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/win1/Ubuntu_App/RemotePython/EncNN/My_EncML.py", line 134, in <module>
>     model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, validation_data=(x_test, y_test))
>   File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 1458, in fit
>     self._make_train_function()
>   File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 1002, in _make_train_function
>     self.total_loss)
>   File "/usr/local/lib/python3.4/dist-packages/keras/optimizers.py", line 326, in get_updates
>     new_a = self.rho * a + (1. - self.rho) * K.square(g)
>   File "/usr/local/lib/python3.4/dist-packages/keras/backend/tensorflow_backend.py", line 1225, in square
>     return tf.square(x)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/math_ops.py", line 428, in square
>     return gen_math_ops.square(x, name=name)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 2544, in square
>     result = _op_def_lib.apply_op("Square", x=x, name=name)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 508, in apply_op
>     (input_name, err))
> ValueError: Tried to convert 'x' to a tensor and failed. Error: None values not supported.
> 
> Process finished with exit code 1

**Comment by printdhruv** [comment]
Here are some suggestions: -

(1) `ValueError: Tried to convert 'x' to a tensor and failed. Error: None values not supported.` which implies the value of `x` used in first line of your code `y = tf.to_int32(x)` is missing.

(2) Please review guidelines for raising an issue here. [https://github.com/printdhruv/tensorflow/blob/master/ISSUE_TEMPLATE.md](https://github.com/printdhruv/tensorflow/blob/master/ISSUE_TEMPLATE.md)

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by shadiakiki1986** [comment]
Answered on StackOverflow [here](https://stackoverflow.com/a/45025025/4126114)
