### ISSUE TITLE
AttributeError when calling train in tf.estimator.DNNClassifier

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#11252]
### System information
- I wrote a custom script, using the tf.estimator.DNNclassifier. Source code below.
- **OS Platform and Distribution**: MacOS 10.12.5
- **TensorFlow installed from**: source
- **TensorFlow version**:  v1.2.0-1741-g88633a8eb 1.2.1
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.5.2
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
- **Additional libraries**: numpy (1.13.0), protobuf (3.3.0), tensorflow-tensorboard (0.1.2)

### Describe the problem
When using tf.estimator.DNNClassifier train function, I get the an AttributeError listed below in the logs, relate to the definition of `values=tuple(six.itervalues(features))` in `_dnn_model_fn`.
Note: when using `tensorflow.contrib.learn.DNNClassifier` instead (with `fit`, instead of `train`) no error occurs.

### Source code

```
import tensorflow.contrib.learn as skflow
feature_columns = skflow.infer_real_valued_columns_from_input(totA.astype(np.float32))
clf = tf.estimator.DNNClassifier(feature_columns=feature_columns,hidden_units=dnntfDef.hidden_layers,
                               optimizer=dnntfDef.optimizer, n_classes=numTotClasses,
                               activation_fn=dnntfDef.activationFn, model_dir=model_directory)

clf.train(input_fn=lambda: input_fn(A, Cl2), steps=2000
```

### logs

`    
clf.train(input_fn=lambda: input_fn(A, Cl2), steps=dnntfDef.trainingSteps)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 616, in _train_model
    model_fn_lib.ModeKeys.TRAIN)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 601, in _call_model_fn
    features=features, labels=labels, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/estimator/canned/dnn.py", line 265, in _model_fn
    config=config)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/estimator/canned/dnn.py", line 84, in _dnn_model_fn
    values=tuple(six.itervalues(features)),
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py", line 578, in itervalues
    return iter(d.values(**kw))
AttributeError: 'Tensor' object has no attribute 'values'
`

**Comment by cy89** [comment]
Pardon me for not understanding all of the context, but should totA be defined, or come from an import, in your example?

**Comment by feranick** [comment]
Sorry for the missing information. totA come from an import. In details:

    `totA = np.vstack((A, A_test))`

where A is my training tensor, and A_test is my validation tensor.

As I said, the code is exactly the same for when I run DNNClassifier through tf.estimator or through 
tensorflow.contrib.learn

Please let me know if you have any more questions.

**Comment by cy89** [comment]
OK, I built a stand-in for totA using a random normal numpy array. 
Now the example breaks with "NameError: name 'dnntfDef' is not defined".
Is there something else I should stub out to replicate?

**Comment by feranick** [comment]
Sorry about that, those were previously defined variables. Given a train set A, with related classes Cl, and a test set A_test, with related labels Cl_test, the code proceeds as follows:

```
totA = np.vstack((A, A_test))
totCl = np.append(Cl, Cl_test)
numTotClasses = np.unique(totCl).size

import tensorflow.contrib.learn as skflow
feature_columns = skflow.infer_real_valued_columns_from_input(totA.astype(np.float32))
clf = tf.estimator.DNNClassifier(feature_columns=feature_columns,hidden_units=[20],
                               optimizer="Adagrad", n_classes=numTotClasses,
                               activation_fn="tanh", model_dir=model_directory)

clf.train(input_fn=lambda: input_fn(A, Cl2), steps=200)
```

The code using tensorflow.contrib.learn is the same other than the last two lines:
```
clf = tensorflow.contrib.learn.DNNClassifier(feature_columns=feature_columns,hidden_units=[20],
                                        optimizer="Adagrad", n_classes=numTotClasses,
                                        activation_fn="tanh", model_dir=model_directory)
clf.fit(input_fn=lambda: input_fn(A, Cl2), steps=200)
```
I hope this helps. Thanks for your help.

**Comment by michaelisard** [comment]
@jhseu any ideas?

**Comment by jhseu** [comment]
Since you switched to core canned Estimators, can you try switching to core FeatureColumns as well?
https://www.tensorflow.org/versions/master/api_docs/python/tf/feature_column

**Comment by feranick** [comment]
Interesting suggestion, will try. What is the closest API in tf.feature_column to the one I used from learn: https://www.tensorflow.org/api_docs/python/tf/contrib/learn/infer_real_valued_columns_from_input

Thanks

**Comment by feranick** [comment]
OK, instead of using:
`feature_columns = skflow.infer_real_valued_columns_from_input(totA.astype(np.float32))`
I used:
`feature_columns = tf.feature_column.numeric_column(key='totA', shape=totA.shape)`
 
This still gives the exact same error.

**Comment by jhseu** [comment]
Can you paste a full runnable example? Specifically I need to see what your input_fn is returning.

From what I can tell, that error shouldn't happen unless you have some mixed Tensor/dict type.

**Comment by feranick** [comment]
Here it is. Will provide train and test files to run shortly

`#!/usr/bin/env python3

import numpy as np
import sys, os.path
#**********************************************
''' Main '''
#**********************************************
def main():
    print(" Using training file: ", sys.argv[1],"\n")
        
    En, Cl, A = readLearnFile(sys.argv[1])
    En_test, Cl_test, A_test = readLearnFile(sys.argv[2])
    learnFileRoot = os.path.splitext(sys.argv[1])[0]
    clf_dnntf, le_dnntf  = trainDNNTF(A, Cl, A_test, Cl_test, learnFileRoot)

#**********************************************
''' DNNClassifier '''
#**********************************************
def trainDNNTF(A, Cl, A_test, Cl_test, Root):
    import tensorflow as tf
    import tensorflow.contrib.learn as skflow
    from sklearn import preprocessing
    
    model_directory = Root + "/DNN-TF_"
    print("\n  Training model saved in: ", model_directory, "\n")
    
    #**********************************************
    ''' Initialize Estimator and training data '''
    #**********************************************
    print(' Initializing TensorFlow...')
    tf.reset_default_graph()

    totA = np.vstack((A, A_test))
    totCl = np.append(Cl, Cl_test)
    numTotClasses = np.unique(totCl).size
    
    le = preprocessing.LabelEncoder()
    totCl2 = le.fit_transform(totCl)
    Cl2 = le.transform(Cl)
    Cl2_test = le.transform(Cl_test)
    
    feature_columns = skflow.infer_real_valued_columns_from_input(totA.astype(np.float32))
    
    ''' tf.estimator version '''
    #clf = tf.estimator.DNNClassifier(feature_columns=[totA], hidden_units=[20],
    #                           optimizer="Adagrad", n_classes=numTotClasses,
    #                           activation_fn="tanh", model_dir=model_directory)
    
    ''' tf.contrib.learn version '''
    clf = skflow.DNNClassifier(feature_columns=feature_columns, hidden_units=[20],
                                    optimizer="Adagrad", n_classes=numTotClasses,
                                    activation_fn="tanh", model_dir=model_directory)

    #**********************************************
    ''' Train '''
    #**********************************************
    
    ''' tf.estimator version '''
    #clf.train(input_fn=lambda: input_fn(A, Cl2), steps=2000)
    
    ''' tf.contrib.learn version '''
    clf.fit(input_fn=lambda: input_fn(A, Cl2), steps=100)
    
    
    accuracy_score = clf.evaluate(input_fn=lambda: input_fn(A_test, Cl2_test), steps=1)
    print('\n  ================================')
    print('  \033[1mDNN-TF\033[0m - Accuracy')
    print('  ================================')
    print("\n  Accuracy: {:.2f}%".format(100*accuracy_score["accuracy"]))
    print("  Loss: {:.2f}".format(accuracy_score["loss"]))
    print("  Global step: {:.2f}\n".format(accuracy_score["global_step"]))
    print('  ================================\n')

    return clf, le

#**********************************************
''' Format input data for Estimator '''
#**********************************************
def input_fn(A, Cl2):
    import tensorflow as tf
    x = tf.constant(A.astype(np.float32))
    y = tf.constant(Cl2)
    return x,y

#**********************************************
''' Read learn File '''
#**********************************************
def readLearnFile(learnFile):
    try:
        with open(learnFile, 'r') as f:
            M = np.loadtxt(f, unpack =False)
    except:
        print('\033[1m' + ' Learning file not found \n' + '\033[0m')
        return
    
    En = np.delete(np.array(M[0,:]),np.s_[0:1],0)
    M = np.delete(M,np.s_[0:1],0)
    Cl = ['{:.2f}'.format(x) for x in M[:,0]]
    A = np.delete(M,np.s_[0:1],1)
    return En, Cl, A

#************************************
''' Main initialization routine '''
#************************************
if __name__ == "__main__":
    sys.exit(main())`

**Comment by feranick** [comment]
The zipped train+test files can be found here:
https://goo.gl/2no9AA

to run the code above (assuming it's called DNNClassifier.py):
`./DNNClassifier.py train.txt test.txt`

You can toggle between the tf.estimator and tf.contrib.learn version within the code.

**Comment by jhseu** [comment]
There are many issues with the script, but it works for me with many modifications:
- feature_columns must be an array
- input_fn must return a dictionary for features where the key matches the feature column key.
- activation can't be a string in the new version
- You'll have to get shapes right. It would probably be easier just to change your input_fn to use numpy_input_fn: https://www.tensorflow.org/versions/master/api_docs/python/tf/estimator/inputs/numpy_input_fn

Closing because there's no bug here.

**Comment by jhseu** [comment]
(Note that we'll have some new tutorials for core estimators up soon. They're not up for core canned estimators because they're not in an official release yet.)

**Comment by jhseu** [comment]
Actually, will reopen and reassign to improve the error message.
