### ISSUE TITLE
pip or package issues

### ISSUE THREAD

**Issue by rogerguess** [tensorflow/tensorflow#11253]
Over the past few hours I have tried to run pip install --upgrade tensorflow_gpu  roughly 20 times, and keep getting read time out from pypi.python.org.  I finally added the --verbose and -- timeout 10000 to troubleshoot. Now I get this:

  Using version 1.2.1 (newest of versions: 1.2.0, 1.2.1)
  Looking up "https://pypi.python.org/packages/47/81/2b8020393615b06af06e0d7c32d74b9a844ebebf4385f9eb00cfdfdbdd92/tensorflow_gpu-1.2.1-cp36-cp36m-win_amd64.whl" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /packages/47/81/2b8020393615b06af06e0d7c32d74b9a844ebebf4385f9eb00cfdfdbdd92/tensorflow_gpu-1.2.1-cp36-cp36m-win_amd64.whl HTTP/1.1" 200 51299687
  Downloading tensorflow_gpu-1.2.1-cp36-cp36m-win_amd64.whl (51.3MB)
  Downloading from URL https://pypi.python.org/packages/47/81/2b8020393615b06af06e0d7c32d74b9a844ebebf4385f9eb00cfdfdbdd92/tensorflow_gpu-1.2.1-cp36-cp36m-win_amd64.whl#md5=46bb283df033c7fb7c233346eb26d40f (from https://pypi.python.org/simple/tensorflow-gpu/)
    12% |████                            | 6.3MB 6.4kB/s eta 1:57:37
Cleaning up...
**THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    tensorflow_gpu from https://pypi.python.org/packages/47/81/2b8020393615b06af06e0d7c32d74b9a844ebebf4385f9eb00cfdfdbdd92/tensorflow_gpu-1.2.1-cp36-cp36m-win_amd64.whl#md5=46bb283df033c7fb7c233346eb26d40f:
        Expected md5 46bb283df033c7fb7c233346eb26d40f
             Got        7ba60530da51fdc733b89f9dd3b660fc**

Exception information:
Traceback (most recent call last):
  File "c:\users\roger\envs\tensorflow_attention_ocr\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\roger\envs\tensorflow_attention_ocr\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "c:\users\roger\envs\tensorflow_attention_ocr\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\users\roger\envs\tensorflow_attention_ocr\lib\site-packages\pip\req\req_set.py", line 386, in prepare_files
    raise hash_errors
pip.exceptions.HashErrors: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    tensorflow_gpu from https://pypi.python.org/packages/47/81/2b8020393615b06af06e0d7c32d74b9a844ebebf4385f9eb00cfdfdbdd92/tensorflow_gpu-1.2.1-cp36-cp36m-win_amd64.whl#md5=46bb283df033c7fb7c233346eb26d40f:
        Expected md5 46bb283df033c7fb7c233346eb26d40f
             Got        7ba60530da51fdc733b89f9dd3b660fc

**Comment by printdhruv** [comment]
I think the latest attempt to `Build #227 (Jul 3, 2017 2:25:07 AM) ` failed for `Windows GPU.` 

I believe the most recent and stable version built was `tensorflow_gpu-1.2.0-cp36-cp36m-win_amd64.whl`.

However, the `pip install --upgrade tensorflow_gpu ` is attempting to download the `tensorflow_gpu-1.2.1-cp36-cp36m-win_amd64.whl` which is not the `build : pass` so it's not working I guess.

Hope it answers your question. Also, no one can temper hashes :)

**Comment by rogerguess** [comment]
Ah, ok. Thank you. I am not familiar with pip. Can I change the command to force 1.2.0?

**Comment by rogerguess** [comment]
Still feels like something else is wrong. When I first kit it off, I get fast download speeds. and now:

` 33% |██████████▊                     | 17.2MB 530bytes/s eta 17:51:51`

**Comment by printdhruv** [comment]
I tried and successfully installed the latest release via `pip install --upgrade tensorflow_gpu` . I would suggest the easy way to uninstall everything and try from scratch with `pip uninstall tensorflow` and try again :)

See installation @ [https://github.com/tensorflow/tensorflow](https://github.com/tensorflow/tensorflow). In your case choose `Windows GPU build history 3.5 / 3.6)` and find out the build which you want to upgrade.

**Comment by rogerguess** [comment]
uninstall? this is virtualenv? there is nothing to uninstall unless I have no clue what I am doing (which is possible.. first time trying all of this)... 

I am on Windows 10... I can do tensorflow 101 examples that can clearly see my GPU. But when I start a virtualenv it cannot see tensorflow. I assume that is by design?

**Comment by gunan** [comment]
The issue here is definitely not related to TF code itself, more user issues around pip and virtualenv. I will therefore close this issue.
Please reach out to pip and virtualenv user manuals, or stackoverflow for such issues not related to bugs in TF code itself.

**Comment by rogerguess** [comment]
brilliant

**Comment by printdhruv** [comment]
@rogerguess Please review guidelines before raising an issue.[https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md](https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md)

Also, note that `Anaconda` is not officially supported by tensorflow. It's community maintained
package in case you have used that for Windows 10.

I encourage you to follow Installation guidelines with pip.
