### ISSUE TITLE
Feature request:  do not reload latest checkpoint on each DNNRegressor.predict() call

### ISSUE THREAD

**Issue by alexvays** [tensorflow/tensorflow#11255]
### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

Each DNNRegressor.predict (or predict_scores) call reloads model parameters from the latest saved model checkpoint, even if the checkpoint hasn't changed between predict() calls.  This slows down generation of predictions.  It will be helpful to be able to disable reloading of model parameters after the initial loading, and/or to be able to reload the latest checkpoint manually via a separate function call.

**Comment by andydavis1** [comment]
@honkentuber can you comment on this one?

**Comment by honkentuber** [comment]
train, evaluate, and predict always build the full graph and load from checkpoint. You can get multiple predictions, while loading the graph only once, by feeding multiple batches via `input_fn` and iterating over the results.

@ispirmustafa @martinwicke

**Comment by martinwicke** [comment]
You can also use the generator_input_fn if your inputs come via a generator. 

We like to keep the Estimator state 100% on disk. This is crucial for distributed training since we wouldn't want to maintain a consistent state ourselves.

**Comment by alexvays** [comment]
The specific use case is:
- input data for prediction arrives at random points in time;
- DNNRegressor.predict() is invoked to generate prediction.
As it stands, there is approximately 3-4 seconds latency for each prediction when running on Google App Engine flex with model_dir in a Google Storage bucket.  The latency seems to be to a substantial extent due to reloading the model from a gs:// path.   Given that data for prediction arrives in online mode (i.e. it's not available ahead of time), how can input_fn be written to return multiple batches?  The ultimate goal is to minimize latency when generating each prediction, from several seconds down to milliseconds.

**Comment by martinwicke** [comment]
You can also try contrib/predictor.
