### ISSUE TITLE
bug in "MNIST For ML Beginners"?

### ISSUE THREAD

**Issue by davidmeyer** [tensorflow/tensorflow#1126]
Under the heading The MNIST Data (https://www.tensorflow.org/versions/v0.6.0/tutorials/mnist/beginners/index.html) it appears that 

import tensorflow.examples.tutorials.mnist.input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

should say

import tensorflow.examples.tutorials.mnist.input_data as input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

thx,

--dmm

**Comment by vrv** [comment]
Thanks -- we've fixed this in the source already, we'll push out a new version of the website hopefully today.

**Comment by davidmeyer** [comment]
thx
