### ISSUE TITLE
Inconsistent default value

### ISSUE THREAD

**Issue by minhlab** [tensorflow/tensorflow#11267]
In this doc:

> https://www.tensorflow.org/api_docs/python/tf/assign

the default value for `validate_shape` and `use_locking` is different between the method signature and the explanation below it.

```
assign(
    ref,
    value,
    validate_shape=None,
    use_locking=None,
    name=None
)
```

vs. 

```
validate_shape: An optional bool. Defaults to True. ...
use_locking: An optional bool. Defaults to True. ...
```

**Comment by drpngx** [comment]
Hi @minhlab the documentation is correct. When `None` is passed, the operator will get the [default](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/op_def_library.py#L304), which is defined in the op [def](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/state_ops.cc#L162).

**Comment by minhlab** [comment]
Still, it's counter-intuitive. I think the documentation can be better.
