### ISSUE TITLE
error in tensorflow/tensorflow/examples/tutorials/word2vec/word2vec_basic.py

### ISSUE THREAD

**Issue by lidawei** [tensorflow/tensorflow#11272]
### System information
== cat /etc/issue ===============================================
Linux ai 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch

== are we in docker =============================================
No

== compiler =====================================================
c++ (GCC) 4.9.3
Copyright © 2015 Free Software Foundation, Inc.

== uname -a =====================================================
Linux ai 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.13.0)
protobuf (3.3.0)
tensorflow (1.1.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.2.1
tf.GIT_VERSION = v1.2.0-5-g435cdfc
tf.COMPILER_VERSION = v1.2.0-5-g435cdfc
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /usr/local/lib64:/usr/local/lib:
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./newfile.sh: line 85: nvidia-smi: command not found

== cuda libs  ===================================================

### Describe the problem
I change the data set and encounter error which is "TypeError: sequence index must be integer, not 'slice'" in line 117. 

### Source code / logs
The code what i have changed is as below
![image](https://user-images.githubusercontent.com/524093/27833171-297c04ee-6104-11e7-88c6-90e963fc7f9c.png)

### What I Do
Change buffer[:] = data[:span] To buffer.extend(data[:span]) in line 117 and work well. Please check the code.  
Thank you for your attention.

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
