### ISSUE TITLE
Matrix Inverse in TensorFlow

### ISSUE THREAD

**Issue by more-more-tea** [tensorflow/tensorflow#11297]
I have a problem related to calculating matrix inverse in TensorFlow python interface version 1.1.0 on Linux. What I'm now trying to do is that, I have an input vector as `tensorflow.float64`, say `S` and a value `V`. I augment the vector `S` to be polynomial fashion in the form ![A=[ 1, S, S^2, S^3 ]](https://latex.codecogs.com/gif.download?A%3D%5B%201%2C%20S%2C%20S%5E2%2C%20S%5E3%20%5D) and want to do a regression on `V`. I choose to compute the linear regression myself instead of using the infrastructure from tensorflow, where the regression is conducted as ![\beta=(A^TA)^{-1}A^T\times V](https://latex.codecogs.com/gif.download?%5Cbeta%3D%28A%5ETA%29%5E%7B-1%7DA%5ET%5Ctimes%20V). The problem occurs at the ![(A^TA)^{-1}](https://latex.codecogs.com/gif.download?%28A%5ETA%29%5E%7B-1%7D) step, where the inverse multiply the original matrix does not give an identity. However, if I feed the ![A^TA](https://latex.codecogs.com/gif.download?A%5ETA) as a constant matrix containing the same value as the preprocessed input, the result is really the inverse of itself.

The code below is a runnable version with parameter `control=True` turns on the constant input matrix version where the inverse behaves correctly. Three matrices are output by running the program, the original matrix, the "inverse" by `tf.matrix_inverse`, and the multiplication of the "inverse" with the original matrix aiming to recover an identify. `control=False` gives the same original matrix as `control=True` run, however, the recovered "identity" is not correct with `control=False`. I suspect something wrong with the data flow during preprocessing. However, limited by my experience with TensorFlow, I cannot spot it. Would you mind a help why the `tf.matrix_inverse` does not work as expected?

    import tensorflow as tf
    import pprint
    
    def matrixInverse( control=False ):
        '''Compute inverse of a matrix.
    
    Parameters
    ----------
    control : bool
        whether to use control group or not.
        '''
        X = tf.constant( [ [100. , 100., 100., 100.],
             [ 101.75497118 ,  92.84824314 ,  95.09528336 , 103.24955959],
             [ 92.33287485 ,  95.86868862 ,  84.70664178 , 107.9505686 ],
             [ 85.86109085 ,  99.05621029 ,  94.24396596 , 119.60257907] ], dtype=tf.float64 )
    
        # extract input X
        s = tf.slice( X, [ 2, 0 ], [ 1, 4 ])
        s = tf.squeeze(s)
        s1 = tf.multiply( tf.ones( 4, dtype=tf.float64 ), s )
        s2 = tf.multiply( s, s )
        s3 = tf.multiply( tf.multiply( s, s ), s )
    
        A = tf.concat( [ tf.ones( 4, dtype=tf.float64 ), s1, s2, s3 ], 0 )
        A = tf.reshape( A, [ 4, 4 ] )
    
        # filter only the first element in the selected row
        itm = tf.constant( [ True, False, False, False ], dtype=tf.bool )
    
        A = tf.boolean_mask( tf.transpose(A), itm )
    
        if control:
            ATA = tf.constant([[  1.00000000e+00,   9.23328748e+01,   8.52535978e+03,   7.87170977e+05],
                         [  9.23328748e+01,   8.52535978e+03,   7.87170977e+05,   7.26817593e+07],
                         [  8.52535978e+03,   7.87170977e+05,   7.26817593e+07,   6.71091579e+09],
                         [  7.87170977e+05,   7.26817593e+07,   6.71091579e+09,   6.19638148e+11]], dtype = tf.float64)
        else:
            ATA = tf.matmul( tf.transpose( A ), A )
    
        inverseATA = tf.matrix_inverse( ATA )
    
        sess = tf.Session()
        pprint.pprint( sess.run( [ ATA, inverseATA, tf.matmul( ATA, inverseATA ) ] ) )

**Comment by more-more-tea** [comment]
It looks in the given case, the matrix is not invertible. However, why for the same input to `matrix_inverse` the output is different? The forward computation should be deterministic, right?

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
