### ISSUE TITLE
undefined reference to 'soc_interface_AllocateInOutNodeBuffers'  Hexagon build failed with latest commit

### ISSUE THREAD

**Issue by kzos** [tensorflow/tensorflow#11299]
OS: Ubuntu 16.04 64bits
 Android Version: 7.1 (Nougat)
 NDK Version: android-ndk-r12b
 HEXAGON SDK: 3.1
 nnlib source: https://source.codeaurora.org/quic/hexagon_nn/nnlib

I have cloned to git commit id - 43a819e1386195f7010f8ca9c74ed96ab81913d8

when I try to build executable for hexagon,
`CC_PREFIX=${CC_PREFIX} NDK_ROOT=${NDK_ROOT} "${BUILD_ALL_ANDROID_PATH}" -x "${GEN_LIBS_DIR}" -s "${TF_ROOT_DIR}/tensorflow/contrib/makefile/sub_makefiles/hexagon_graph_execution/Makefile.in" -t hexagon_graph_execution`

I am getting build error,
```
tensorflow/tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a(hexagon_control_wrapper.o):hexagon_control_wrapper.cc:function tensorflow::HexagonControlWrapper::Init(tensorflow::RemoteFusedGraphExecuteInfo const&): error: undefined reference to 'soc_interface_AllocateInOutNodeBuffers'
collect2: error: ld returned 1 exit status
```

build changes are moved partially out of `tensorflow/contrib/makefile/sub_makefiles/hexagon_graph_execution/Makefile.in`

is this the possible cause for error.

I am not sure I can pull out latest commit and build over that, but right now I am stuck at build fail.
Help me with a fix .

**Comment by kzos** [comment]
@Satok provide pointers.

**Comment by andydavis1** [comment]
Is this issue still open?

**Comment by satok16** [comment]
Sorry, I'm on it.  Will be fixed asap.

**Comment by kzos** [comment]
@satok16, keep me posted.

**Comment by satok16** [comment]
It's fixed last week.

**Comment by kzos** [comment]
@satok16 , I missed it, I guess this is the commit id-06d25a7e, will check with this, 
thanks.
