### ISSUE TITLE
tf.reverse doesn't support tensor with unknown shape

### ISSUE THREAD

**Issue by vanpersie32** [tensorflow/tensorflow#11293]
### System information
   ubuntu 14.04
   tensorflow installed from binary
   tensorflow version: tensorflow-gpu  1.2.1
   python version: python 2.7
   CUDA/CuDNN version: cuda 8.0/ CUDNN 5.1
   GPU model
   
You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

### Describe the problem
Hey tensorflow community. I want to feed an unknown shape tensor into tf.placeholder. Then it is reversed. But it reports errors
a = tf.placeholder(dtype = tf.int64,shape = [None])
b = tf.reverse(a,axis = 0)

### Source code / logs
![1](https://user-images.githubusercontent.com/15981416/27864587-c449c5d4-61c1-11e7-852d-fa8911f9e429.png)
![2](https://user-images.githubusercontent.com/15981416/27864596-ca4d3790-61c1-11e7-9568-bc822a9917bb.png)

**Comment by mrry** [comment]
The docs for `tf.reverse()` indicate (perhaps too subtly...) that the `axis` argument must be one-dimensional, so you should instead pass `axis=[0]`. The following code works as intended:

```python
a = tf.placeholder(dtype=tf.int64, shape=[None])
b = tf.reverse(a, axis=[0])
sess = tf.Session()
print sess.run(b, feed_dict={a: [1, 2, 3]})  # Prints "[3, 2, 1]".
```

**Comment by vanpersie32** [comment]
@mrry thank you mrry.
