### ISSUE TITLE
State of GPU support for commercial Android devices

### ISSUE THREAD

**Issue by PKUEcho** [tensorflow/tensorflow#11300]
Question has been asked in  [this thread](https://github.com/tensorflow/tensorflow/issues/663) but got no answer. Just curious what's the plans of TF team to support Android GPUs (or no plan at all) for commercial devices such as Nexus. I understand OpenCL is not included in Android now, but we still have RenderScript. And [some work](https://github.com/nesl/RSTensorFlow/tree/matmul_and_conv/tensorflow/contrib/android_renderscript_ops) has already been put to this end.

It would be great to know it from TF developers.

**Comment by cy89** [comment]
@petewarden and @andrewharp: can you offer any guidance?

**Comment by andrewharp** [comment]
Most mobile acceleration work being done currently is for the Hexagon DSP, which can offer an order of magnitude speedup. @satok16 has been working on this and may be able to offer more details.

We may also support CUDA on Android in the future, but this would be limited to select Nvidia devices like the TX1/TX2.

**Comment by PKUEcho** [comment]
@andrewharp Thanks Andre for your reply. So is there any workable toy that I can play with now on any Android GPU? And I saw TF supports OpenCL now (as I configure it it asks me if I want to add OpenCL support). If I have a OpenCL library on my Android device, is it possible that TF can work without further modification?

**Comment by andrewharp** [comment]
@PKUEcho See [master/tensorflow/contrib/hvx](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/hvx) for instructions on running HVX-accelerated TF on supported devices.

We don't currently have internal plans to add OpenCL support on Android, but if the community wants to add it that would be great. I have no idea what sort of issues might be run into though.

Otherwise I'd suggest the HVX option or waiting on CUDA support.

**Comment by PKUEcho** [comment]
Thanks @andrewharp for your reply!

**Comment by llhe** [comment]
@PKUEcho For deep learning framework with mobile phone GPU support, you can have a look at [MACE](https://github.com/xiaomi/mace) and [some benchmark results](https://github.com/XiaoMi/mace/issues/1).
