### ISSUE TITLE
TensorFlow on Kieler Open Source und Linux Tage?

### ISSUE THREAD

**Issue by m23project** [tensorflow/tensorflow#11304]
Hi,

I didn't find any contact information for the TensorFlow project, so I try it here :-)

We are organising our 15th "Kieler Open Source und Linux Tage" (northern of Germany, www.kielux.de), a conference with 4 parallel tracks with talks and workshops and a smal exhibition for open source community projects and companies.

Is there anybody who would like to hold a talk and/or give a TensorFlow workshop and/or make a booth on our event (14th - 16th September)?

Please answer by eMail to kontakt @ kilux.de .

Cu Hauke

**Comment by cy89** [comment]
This seems like a better request to post to the TensorFlow Discuss mailing list (https://groups.google.com/a/tensorflow.org/forum/#!forum/discuss), rather than to this issue tracking tool. Please try there, and have a great workshop!
