### ISSUE TITLE
tf.gfile.FastGFile(filename, 'r').read()  error: 'utf-8' codec can't decode byte 0xff

### ISSUE THREAD

**Issue by zsz02** [tensorflow/tensorflow#11312]
### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
TensorFlow 1.2.0

image_data = tf.gfile.FastGFile(filename, 'r').read()   
python2.7 is good，but Python3.5 error ：  'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

why???

**Comment by mrry** [comment]
Python 3 introduces a distinction between the "r" and "rb" modes for [opening a file](https://docs.python.org/3/library/functions.html#open). Using the "r" mode will cause Python to interpret the file contents as text&mdash;in your case (and the common case) using an UTF-8 encoding&mdash;but the error message indicates that data is binary format (presumably some image format, based on your variable name). Changing the code to use the mode "rb"  should fix the problem and work in both versions of Python:

```python
image_data = tf.gfile.FastGFile(filename, 'rb').read()
```

**Comment by ELI95** [comment]
def read_pickle_from_file(filename):
  with tf.gfile.Open(filename, 'rb') as f:
    data_dict = pickle.load(f)
  return data_dict

UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 6: ordinal not in range(128)

**Comment by dndusdndus12** [comment]
JUST change it.

with tf.gfile.Open(filename, 'r') as f:
    data_dict = cPickle.load(f)
to
  with open(filename, 'rb') as f:
    data_dict = cPickle.load(f, encoding='bytes')

important thing is mode 'rb' and encoding='bytes'
If you working on some open sources, you will encounter additional errors about the variable type. 
But the problems are easier to manage than this file open and encoding problem, so it's a good idea to fix this way.

I had done with in CIFAR 10 python code. which is:
https://github.com/dndusdndus12/models/tree/master/tutorials/image/cifar10_estimator
generate_cifar10_tfrecords.py

**Comment by donghwicha** [comment]
I think this issue should be fixed.

**Comment by codexponent** [comment]
@mrry comment solved my problem. :)
