### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'assign_add'

### ISSUE THREAD

**Issue by Nicolas99-9** [tensorflow/tensorflow#11311]
I'm trying to use "assign_add" : 
https://www.tensorflow.org/api_docs/python/tf/assign_add

my code : 
accum_ops = tf.assign_add(accum_grad, grad, name=name)

Output ; 
AttributeError: 'Tensor' object has no attribute 'assign_add'

Has the name changed ?

**Comment by ScorpioCPH** [comment]
Please show me the `version` of `TensorFlow`:

```python
import tensorflow as tf
print tf.__version__
```

**Comment by Nicolas99-9** [comment]
>>> import tensorflow as tf
>>> print tf.__version__
1.2.1

**Comment by ScorpioCPH** [comment]
As this method defined:

```python
tf.assign_add

assign_add(
    ref,
    value,
    use_locking=None,
    name=None
)
```

**Args:**

- ref: A mutable Tensor.

So `accum_grad` must be reference-typed.

> The most common way to create a reference-typed tensor is to define a tf.Variable

From [stackoverflow](https://stackoverflow.com/a/37959933/3167471)

**Comment by mrry** [comment]
If the statement `accum_ops = tf.assign_add(accum_grad, grad, name=name)` yields the error `AttributeError: 'Tensor' object has no attribute 'assign_add'`, then I'm betting that you've accidentally created a tensor called `tf`, which has overwritten the module alias `import tensorflow as tf`. Such are the joys of a dynamic language like Python! The solution would be to rename that tensor to something other than `tf`.

Feel free to reopen if I'm wrong here....

**Comment by idofr** [comment]
I fear you're wrong here, at least in my case.
I've followed the learning rate decay page
https://www.tensorflow.org/versions/r0.12/api_docs/python/train/decaying_the_learning_rate

and set 'global_itr' to a placeholder which is provided with a feed_dict
`
self.symb_global_itr = tf.placeholder(
            tf.int32,
            shape=(),
            name='global_itr'
        )

lrate = tf.train.exponential_decay(
            self.opts.learning_rate,
            self.symb_global_itr,
            5000,
            0.96,
            staircase=True
        )

  optimiser = tf.train.AdamOptimizer(
      lrate,
  ).minimize(
      loss,
      var_list=g_vars,
      global_step=self.symb_global_itr
  )
`

Any ideas what I'm doing wrong here?

**Comment by swethmandava** [comment]
@Nicolas99-9 How did you fix it? I have the same issue

**Comment by michav1510** [comment]
@Nicolas99-9 I have the same issue.

**Comment by michav1510** [comment]
@swethmandava As here referred : https://github.com/tensorflow/tensorflow/issues/30468
I change the 
`tf.assign_add()`
with
` tf.compat.v1.assign_add()`
