### ISSUE TITLE
TypeError: Input 'strides' of 'StridedSlice' Op has type int32 that does not match type int64 of argument 'begin'.

### ISSUE THREAD

**Issue by minhlab** [tensorflow/tensorflow#11318]
I just want to get a slice of a tensor. It works for int32 but not for int64:

```
In [35]: import tensorflow as tf
    ...: a=tf.Variable([0,1,2], dtype=tf.int64)
    ...: i = tf.constant(1, dtype=tf.int64)
    ...: a[i]
    ...:
<long stack trace>
TypeError: Input 'strides' of 'StridedSlice' Op has type int32 that does not match type int64 of argument 'begin'.
In [36]: import tensorflow as tf
    ...: a=tf.Variable([0,1,2], dtype=tf.int32)
    ...: i = tf.constant(1, dtype=tf.int32)
    ...: a[i]
    ...:
Out[36]: <tf.Tensor 'strided_slice_22:0' shape=() dtype=int32>
```

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by minhlab** [comment]
It looks like a bug for me... I mean, why can't int64 be used as a simple index? What happen if I have a vector of more than 2^32 elements?

**Comment by cy89** [comment]
Invoking @vrv who has suffered a long time working on the differences in behavior between int32 and int64. 

Can you not do a cast from int64 to int32 to get the effect you want? I.e., do you really have a >4B-element vector that you want to access in practice?

**Comment by vrv** [comment]
StridedSlice definitely supports int64 indices, I think the problem is that the datatype of 'begin' is int64 and the datatype of 'strides' is int32, and that's a type mismatch.

@aselle: my guess is that there's some kind of missing cast to match the dtype of 'begin' somewhere in the SliceHelper.  Do you know the code well enough to know what the fix is quickly?

**Comment by vrv** [comment]
@minhlab knowing the version of TensorFlow and all the information requested in the template would help to make sure it's not already fixed.

**Comment by vrv** [comment]
In fact, I think this was already fixed two months ago in https://github.com/tensorflow/tensorflow/pull/9000/files, and you are probably using an older version of TF that doesn't have the bug fix.

**Comment by minhlab** [comment]
Hi @vrv, you're right. After running pip install --upgrade, the problem was gone.
