### ISSUE TITLE
My problem---tensor-flow connect with Windows IIS?Hello,i just ask a question three days ago, but no response,can you spend some time to reply me?

### ISSUE THREAD

**Issue by jxua** [tensorflow/tensorflow#11310]
I set up a tensorflow system, use flask grammar to set up . And in local computer, all run ok, no error.
But when I mount it in IIS, as Web API to use, It always show FASTCGI error. Does tensorflow incompatiable with IIS?

**Comment by ScorpioCPH** [comment]
Sorry i don't understand 

> mount it in IIS, as Web API to use

can you show me an `example` with more details?

**Comment by gunan** [comment]
I am not sure what do you mean by web API.
tensorflow does not have any web API.

With the little amount of information provided, we have no idea how to help out.
I will close this issue. But please feel free to file a new issue, and this time make sure to provide all the information required by the template.

**Comment by jxua** [comment]
Sorry, i just have time to reply you. Thanks for replying me.
I means I use Flask to call tensor-flow py. And mount Flask to windows IIS. Local run ok. But in IIS will show FastCgi error. Check local run is ok,no error. But when in IIS, when i import keras, it will show fastcgi error. but when don't import keras, it will ok. If tensor-flow isun-incompatible with IIS?
![image](https://user-images.githubusercontent.com/22673941/28155106-ad5993c6-67df-11e7-8213-1ebd62ee9772.png)
![image](https://user-images.githubusercontent.com/22673941/28155154-f8f86406-67df-11e7-8df8-8c980d042834.png)
![image](https://user-images.githubusercontent.com/22673941/28155181-1faf8642-67e0-11e7-98f8-a3c8dbb15f85.png)
![image](https://user-images.githubusercontent.com/22673941/28155934-3ccda850-67e3-11e7-94e4-feeb92533f87.png)
![image](https://user-images.githubusercontent.com/22673941/28157236-6a36720e-67e8-11e7-807f-31fdbe7e7196.png)
![image](https://user-images.githubusercontent.com/22673941/28157302-a0157e42-67e8-11e7-987c-165e227e618c.png)
![image](https://user-images.githubusercontent.com/22673941/28157368-d98ddc8c-67e8-11e7-82a0-1a90c0208534.png)

**Comment by gunan** [comment]
We do not have direct support for neither Flask, or use with IIS. The issue you are seeing seems to be coming from these.
If everything runs OK locally, there does not seem to be any issues with running/installing TF.

I recommend reaching out to developers of flask, or Microsoft for support with these components.
