### ISSUE TITLE
Is 'tf.concat' 's API is wrong?

### ISSUE THREAD

**Issue by lizekui** [tensorflow/tensorflow#11321]
According 'tf.concat' 's API (0.12):

`t1 = [[1, 2, 3], [4, 5, 6]]`
`t2 = [[7, 8, 9], [10, 11, 12]]`
`tf.concat(0, [t1, t2])`

while console returns:

`tf.concat(0, [t1, t2])
Traceback (most recent call last):`
`File "<ipython-input-65-5990b998f0fa>", line 1, in <module>
    tf.concat(0, [t1, t2])`
`File "E:\SDK\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1044, in concat
    ).assert_is_compatible_with(tensor_shape.scalar())`
`File "E:\SDK\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 732, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))`
`ValueError: Shapes (2, 2, 3) and () are incompatible`

**BUT I try to swap the params' position, it is well.**

`t1 = [[1, 2, 3], [4, 5, 6]]`
`t2 = [[7, 8, 9], [10, 11, 12]]`
`tf.concat([t1, t2], 0)`

**Comment by ScorpioCPH** [comment]
As this API defined [here](https://www.tensorflow.org/api_docs/python/tf/concat):

```python
tf.concat

concat(
    values,
    axis,
    name='concat'
)
```

And args must follow:

- `values`: A list of `Tensor` objects or a single `Tensor`.
- `axis`: 0-D int32 `Tensor`. Dimension along which to concatenate.
- `name`: A name for the operation (optional).

**Comment by lizekui** [comment]
@ScorpioCPH 
I have some problems when clicking your URL (Maybe my HOSTS is not correctly haha )

I wonder know what's difference between your URL and below API:
[https://www.tensorflow.org/versions/r0.12/api_docs/python/array_ops.html#concat](tf.concat)

Thanks a lot !
