### ISSUE TITLE
TypeError: concat() got an unexpected keyword argument 'concat_dim'

### ISSUE THREAD

**Issue by datomnurdin** [tensorflow/tensorflow#11324]
I got this error message regarding to tf.concat

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-bf534f0e5e9f> in <module>()
     42 
     43 combined_mask = tf.concat(concat_dim=2, values=[bit_mask_class,
---> 44                                                 bit_mask_background])
     45 
     46 # Lets reshape our input so that it becomes suitable for

TypeError: concat() got an unexpected keyword argument 'concat_dim'
```

Code: https://github.com/datomnurdin/tensorflow-image-segmentation/blob/master/index.ipynb

Please advice. Thank you.

**Comment by mrry** [comment]
It looks like that code was written for an older version of TensorFlow. From TensorFlow 1.0 onwards, [`tf.concat()`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/concat) takes the arguments `values` and `axis`. Replacing `concat_dim` with `axis` will fix the problem.

**Comment by datomnurdin** [comment]
It worked!! Thanks!!
