### ISSUE TITLE
Error: Not Found TensorFlow How-Tos

### ISSUE THREAD

**Issue by chowraid** [tensorflow/tensorflow#1132]
**TensorFlow Mechanics 101** brings up an error when trying to view tutorial.

![404](https://cloud.githubusercontent.com/assets/7181734/13099384/55fd2918-d4e6-11e5-8cdb-6c7fc698f63b.png)

**Comment by martinwicke** [comment]
Should be fixed. Sorry.

**Comment by chowraid** [comment]
No problem. :+1:
