### ISSUE TITLE
[Doc] tf.abs + complex numbers

### ISSUE THREAD

**Issue by elbaro** [tensorflow/tensorflow#11347]
TF 1.2.0

`tf.abs` already supports complex numbers but this is not documented.

https://www.tensorflow.org/api_docs/python/tf/abs

**Comment by dr4b** [comment]
Do you have a suggestion for how you'd like it to read, or do you want to submit a PR with a specific fix?

**Comment by rryan** [comment]
Dupe of #9827?

**Comment by elbaro** [comment]
Yes, this is a dupe.
