### ISSUE TITLE
Tensorboard graphs broken in v0.7.0 [Fixed in source, will be in next binary release]

### ISSUE THREAD

**Issue by has2k1** [tensorflow/tensorflow#1134]
After upgrading from `v0.6.0` to `v0.7.0` via

```
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.0-py2-none-linux_x86_64.whl
```

Tensorboard graph functionality is empty, while the rest of tensorboard seems fine.

Image shows what I get at `http://0.0.0.0:6006/#graphs`

![tensorboard-bug](https://cloud.githubusercontent.com/assets/780341/13100050/767a898e-d4fe-11e5-8f53-da72be8c9e9a.png)

**Comment by Charlie-Huang** [comment]
I am having the same problem. The brower will give an error something like Uncaught  TypeError: Polymer.dom(...).unobserveNodes is not a function when I click the graph tab

**Comment by vrv** [comment]
Looks like another instance of #1046.  Going to leave this one open since I suspect a lot of people are going to be running into this one.

**Comment by Azukikuru** [comment]
I have had the same problem ever since I first tried to use tensorboard a few days ago (with 0.6.0). The problem persists in Firefox, Konqueror, AND Chrome (!), and it is not fixed by reinstalling as a git clone after issue #650 nor by updating any of the dependencies as suggested on various other threads. I'm using CentOS 7. However, I am not seeing any error message such as reported by Charlie-Huang.

**Comment by martinwicke** [comment]
Could you try updating polymer to at least 1.2? That has fixed it for at least some people.

**Comment by dsmilkov** [comment]
Hi guys,

If you open the console while your browser is pointed to 0.0.0.0:6006 and type `Polymer.version` do you get `1.1.5` or `1.2.4` or something else?

If you get `1.1.5` when you need to update to `1.2.4`. To do this, [download polymer 1.2.4](https://github.com/Polymer/polymer/archive/v1.2.4.zip). Unzip and copy the 3 html files (polymer*.html) into the external polymer directory under site-packages dir: /usr/lib/python2.7/site-packages/external/polymer (overwrite the previous files).

Let me know how it goes. We will also be releasing a patch for 0.7.0 where we ship Polymer 1.2.4 with it.

**Comment by has2k1** [comment]
Updating polymer fixes the problem.

**Comment by Azukikuru** [comment]
I had polymer 1.1.5; after martinwicke's comment, I git-cloned polymer, copied the html files, and the version became "master", which didn't work either; then, after dsmilkov's comment, I downloaded the ZIP file and put in the 1.2.4 files, but it still didn't work. The end result is still as in has2k1's original picture with the toolbar showing but nothing in the big panel, as opposed to running an empty session, when it does say that the required files are missing. And still no error messages in the terminal from which I launch tensorboard when I try to access the graph mode, but there was one earlier (I just noticed) about favicon.ico being missing from the .../tensorboard.runfiles/... directory, but I put some random .ico file in the required location and that didn't fix it either.

Just to clarify, I'm using the MNIST tutorial (mnist_with_summaries.py), which as far as I understand should produce something visible in the graph mode. The events and histograms work perfectly, but as I'm only using tensorboard for the first time, I've never seen the graph mode work, so it could be something unrelated. I've googled everything I could think of before posting here, but unfortunately, I'm at a loss.

**Comment by Azukikuru** [comment]
Sorry, I should mention that I'm still on 0.6.0. It's just that has2k1's description of the problem and the attached picture match my problem exactly.

**Comment by mebersole** [comment]
Going to 1.2.4 of polymer works for me and I'm using 0.6.0

**Comment by vrv** [comment]
Okay, we're going to cherry-pick the 1.2.4 version change into r0.7 branch and will include this fix in the next patch release.

**Comment by vrv** [comment]
Ok, we have candidate wheels for 0.7.1 here: https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/g3doc/get_started/os_setup.md -- let us know if there are any problems.  If all looks good we'll update our docs to officially recommend 0.7.1 late this week.

**Comment by has2k1** [comment]
My experience with

```zsh
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
```

`0.7.1` works if installed anew and not as an upgrade from `0.7.0`. When upgrading it is necessary to first uninstall `protobuf`. `protobuf` does not get sanely upgraded, there is a mess of things in `site-packages/google/protobuf`.

Also, a separate unreported issue that is solved, for Python `3.4` I had `0.7.0` fail with a segmentation fault, not any more for `0.7.1`.

**Comment by Smerity** [comment]
Just wanted to note that uninstalling `protobuf` and reinstalling TF 0.7.1 worked well for me on Mac OS X - the Polymer version issue is gone and graphs are visible. Thanks!

**Comment by roestigraben** [comment]
Hi, the proposed upgrade for Polymer worked just fine for me. I am using anaconda
