### ISSUE TITLE
Does tensorflow support mfcc now?

### ISSUE THREAD

**Issue by liuzqt** [tensorflow/tensorflow#11343]
Is mfcc support in tensorflow now? I found this https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/mfcc.h

but I can't find this op in Python API in tensorflow. 

So is that not open yet? Or it's wrapped in some other Python api?

**Comment by asimshankar** [comment]
Closing this as a duplicate of #11339. Let's continue discussion there.
