### ISSUE TITLE
MonitoredTrainingSession to have accessible summary writer.

### ISSUE THREAD

**Issue by coopie** [tensorflow/tensorflow#11350]
**Tensorflow version: 1.2.1**

I am using `MonitoredTrainingSession` extensively to train models, and for the most part does exactly what I want it to do. However, I would like to be able to extract (or pass in) a `FileWriter` object so I can report other summaries from inside my evaluation routines. This is because only one` FileWriter` can write to the events log:

At the moment, this is the best workaround I can do:

```python
sess = tf.train.MonitoredTrainingSession(
       ...
    )

# HACK: this is so we use the same summary writer obj for both summaries, only way to do it.
summary_writer = sess._hooks[1]._summary_writer
```

Then I can use the `summary_writer` to manually report summaries in the evaluation part of my code:

```python
mean_test_loss = ...
summary = tf.Summary(value=[
    tf.Summary.Value(tag='mean_test_loss', simple_value=mean_test_loss)
])
summary_writer.add_summary(summary, current_step)

```

It would be nice to have a non-hacky way to get the `summary_writer` from the session so only one `FileWriter` writes to the events file.

One thought I had is to have a `FileWriter` object as part of the `Scaffold` that is used to build the session. That way anyone can get hold of the scaffold and use the one `summary_writer` designated to write to the events log.

I would be happy to help implementing this if other people are interested.

**Comment by vierja** [comment]
You can use `SummaryWriterCache`. (`from tensorflow.python.training.summary_io import SummaryWriterCache`).

This is what the the [basic session hooks](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/python/training/basic_session_run_hooks.py) use.

**Comment by DjangoPeng** [comment]
It sounds fine for me, and the workaround is make sense. What is the progress of the implementation? If you want, I can send a PR to implement the feature. It's good if you would like do me a favor.

**Comment by spk921** [comment]
@vierja  Could you give example? I have a problem adding summary operation with MonitoredTrainingSession.

**Comment by Anjum48** [comment]
@spk921 Here's how I did it:

```python
sess = tf.train.MonitoredTrainingSession(master=self.server.target, is_chief=(self.wid == 0),
                                         checkpoint_dir=SUMMARY_DIR,
                                         save_summaries_steps=None, save_summaries_secs=None, hooks=hooks)

writer = SummaryWriterCache.get(SUMMARY_DIR)
```

where `SUMMARY_DIR` is the path to your summary directory

**Comment by spk921** [comment]
@Anjum48 Could you add link to the origin code?

**Comment by Anjum48** [comment]
@spk921 Here's a link to a working version of DeepMind's DPPO algorithm using the above code https://github.com/Anjum48/rl-examples/blob/master/dppo/dppo.py#L283

**Comment by wt-huang** [comment]
Closing this issue since there is a working solution
