### ISSUE TITLE
Support for 1D convolutions

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#1136]
There is no conv1d method and it would be very welcome.

Or is conv2d implemented in such a way that (h=1, w, channels) would work with no issues and no compute penalties?

It might even be a good idea to implement an arbitrary convxd function, there are instances where high dimensional inputs have spatial relevance.

**Comment by vrv** [comment]
Yes, conv2d can work with h=1, though it's possible one could write a faster kernel if you knew it was 1d.  If someone was willing to write a kernel (CPU and GPU) and benchmarks for this, we'd be happy to accept it.  Same with convxd.  #150 for a similar request, but for 3D, which we'd also love contributions for.

**Comment by alphaf52** [comment]
conv2d can work with h=1 indeed. However, when i want to set stride > 1 for 1d conv using conv2d with h = 1, i got an error "ValueError: Current implementation only supports equal length strides in the row and column dimensions". And as i set h = 1, i can't have a stride wrt h which is greater than 1. I want to know if there is a way i can do this.

**Comment by jramapuram** [comment]
Fractional striding on 1d convolutions would be helpful to downsample 1d signals. Currently there is no way to do this with 2d convolutions as mentioned by @alphaf52 .

**Comment by girving** [comment]
@jramapuram Fractional striding is hard to implement efficiently using anything like direct convolution; normally I'd just write it using FFTs (which already works).

**Comment by vrv** [comment]
@alphaf52 I believe conv2d now supports unequal strides in the h and w dimensions.  separable/depthwise don't yet, but for most people's purposes, that should be addressed.

**Comment by renesax14** [comment]
are there examples or docs that explain how to actually use the 1D convolution?

**Comment by renesax14** [comment]
example: http://stackoverflow.com/questions/38114534/basic-1d-convolution-in-tensorflow/38117279#comment65079952_38117279

**Comment by shoyer** [comment]
I believe this is actually done. See:
https://www.tensorflow.org/versions/r0.11/api_docs/python/nn.html#conv1d

**Comment by renesax14** [comment]
@shoyer I'm pretty sure thats new, and it seems it doesn't have BN automatically included in it like the other convolution, which is a big draw back.

**Comment by shoyer** [comment]
@renesax14 sorry, "BN"?

**Comment by renesax14** [comment]
sorry, I didn't even realize I wrote the acronym. Batch Normalization.

**Comment by shoyer** [comment]
@renesax14 Maybe you are referring to the conv functions in `tf.contrib.layers`? As far as I can tell, none of the conv functions `tf.nn` have anything related to batch normalization built in.

**Comment by renesax14** [comment]
@shoyer yes I think thats right.

**Comment by shoyer** [comment]
OK, closing this as fixed. Note that the current implementation just uses `conv2d` under the covers. Contributions to add this to `tf.contrib.layers` would also be welcome, should be pretty easy.
