### ISSUE TITLE
py_func does not properly

### ISSUE THREAD

**Issue by meijieru** [tensorflow/tensorflow#11376]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.2
- **Python version**: 
3.6
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
Cudnn v5.1
- **GPU model and memory**:
Pascal Titan X
- **Exact command to reproduce**:
```
import tensorflow as tf
import numpy as np

def fun(x):
    return np.ones([5]), np.ones([5])


aa, b = tf.py_func(fun, [1], tf.uint8)
```

### Describe the problem
The `py_func` does work properly

### Source code / logs
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    a, b = ab
  File "/home/jrmei/lib/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 541, in __iter__
    raise TypeError("'Tensor' object is not iterable.")
TypeError: 'Tensor' object is not iterable.
```

**Comment by ilovin** [comment]
I met the same problem,
after reshape a tensor,  py_func raise TypeError("'Tensor' object is not iterable.")
how did you solve this problem?

**Comment by meijieru** [comment]
It should be
```
a, b = tf.py_func(fun, [params], [tf.uint8, tf.uint8])
```
