### ISSUE TITLE
Feeding TensorArray when running a session using feed_dict

### ISSUE THREAD

**Issue by mishajw** [tensorflow/tensorflow#11383]
Currently there is no way to define a placeholder for a `tf.TensorArray`. A solution is to zero-pad a `tf.Tensor` and then unstack and slice it into a `tf.TensorArray`. However, this adds unpadding overhead which would have to be done for every batch.

A possible change would be to add a new placeholder type for feeding a `tf.TensorArray` to the graph, for example called `tf.tensor_array_placeholder`.

This could work as follows:
```python
# Define an input TensorArray with three elements
ta_input = tf.tensor_array_placeholder(dtype=tf.float32, size=3)
# Take the second element from the TensorArray
ta_second = ta.read(1)
# Sum its values
result = tf.reduce_sum(ta_second)

with tf.Session() as sess:
    run_result = sess.run(
        [result],
        # Feed raw values into ta_input. These could also be NumPy arrays
        { ta_input: [[1, 2, 3], [4, 5], [6, 7, 8, 9]] })

   print(run_result)  # Should print 9
```

**Comment by jart** [comment]
@ebrevdo Here's a feature request relating to TensorArray.

**Comment by ebrevdo** [comment]
The unstacking would have to be done even if you use a special placehoder, because TensorArray internal representation is unstacked.  You wouldn't win anything in terms of performance.  Anyway you don't need to pad your input array... Just feed the placeholders tf.shape(placeholder)[0] as the size of the TensorArray you create and unstack.

**Comment by ebrevdo** [comment]
Oh I see, you want to feed varying shape entries all at once.  Since all inputs into tensorflow must be representable as a numpy array, and numpy arrays don't allow this, I don't see how it would work.

**Comment by mishajw** [comment]
Yes exactly - this is a feature request.

Would it not be possible to feed a python array of numpy arrays to the proposed `tf.tensor_array_placeholder`? Or something similar? I understand this could be quite a niche use case that might require quite a large change, but when working with TensorFlow tools such as `tf.while_loop` that use TensorArrays heavily this could be very useful.

**Comment by ebrevdo** [comment]
You can get something similar by creating some N write operations, like so:

```
ta = tf.TensorArray(size=placeholder_size)
ta_arr = []
ta_arr.append(tf.cond(placeholder_size >= 1, lambda: ta.write(0, placeholders[0]), lambda: ta))
ta_arr.append(tf.cond(palceholder_size >= 2, lambda: ta.write(1, placeholders[1]), lambda: ta_arr[-1])
...
ta_arr = tf.cond(placeholder_size >= n, lambda: ta.write(n - 1, placeholders[n-1], lambda: ta_arr[-1])
...
...

and then feed in placeholder_size and as many placeholders[i] as you want.

can even wrap this in a helper function call, probably.

**Comment by mishajw** [comment]
Hi @ebrevdo, sorry I've just gotten time to try this out.

This approach seems to work, but could you speak for how fast this compared to the usual method of feeding single placeholder for Tensors that don't have varying sizes? I am concerned that this method, while clean once inside a helper function call, might be slow when training.
