### ISSUE TITLE
Gradients are not registered

### ISSUE THREAD

**Issue by DimanNe** [tensorflow/tensorflow#11395]
(System information probably is not relevant to the issue, so I moved it below)

## The Problem

It seems that the code, generated by macros `REGISTER_GRADIENT_OP` in [math_grad.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/gradients/math_grad.cc) is never executed:
`static bool unused_ret_val_123 = ::tensorflow::ops::GradOpRegistry::Global()->Register(name, fn);`

My `BUILD` file:
```
cc_binary(
    name = "bitwise_operations",
    srcs = [
       "main.cpp"
    ],
    deps = [
        "//tensorflow/cc:grad_ops",
        "//tensorflow/cc:cc_ops",
        "//tensorflow/cc:client_session",
        "//tensorflow/core:tensorflow",
        "//tensorflow/cc/DimanNe/tensorflow_utils:tensorflow_utils",
    ],
)
```

## The cause

`Bazel` generates such `tensorflow/bazel-out/local-dbg/bin/tensorflow/cc/DimanNe/bitwise_operations/bitwise_operations-2.params` that instructs linker to put `math_grad.pic.o` in separate static library, here is how it looks in the params file containing linking instructions:
```
--start-lib
bazel-out/local-dbg/bin/tensorflow/cc/_objs/real_math_grad/tensorflow/cc/gradients/real_math_grad.pic.o
--end-lib
```
And [here1](https://www.google.ru/search?q=global+symbols+in+static+libraries&oq=global+symbols+in+static+libraries&aqs=chrome..69i57.7343j0j7&client=ubuntu&sourceid=chrome&ie=UTF-8#newwindow=1&q=global+initializer+in+static+libraries)/[here2](https://stackoverflow.com/questions/9459980/c-global-variable-not-initialized-when-linked-through-static-libraries-but-ok) you can find a lot of complaints about static global variables not being initialized, being linked as static libraries.

## The solution
Add `alwayslink = 1,` to `math_grad` library in `tensorflow/cc/BUILD` (and actually any *_grad library, since all of them use the same mechanism of registration of gradients).
Exactly the same has already been done here - `tensorflow/core/BUILD`.

It the solution is OK, I can make a pull-request.

## System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Kubuntu 17.04
- **TensorFlow installed from (source or binary)**:
Compiled from sources
- **TensorFlow version (use command below)**:
`remotes/origin/r1.2`
- **Python version**: 
Do not use it
- **Bazel version (if compiling from source)**:
$ bazel version
Build label: 0.5.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 6 10:34:11 2017 (1496745251)
Build timestamp: 1496745251
Build timestamp as int: 1496745251
- **CUDA/cuDNN version**:
no cude
- **GPU model and memory**:
01:00.0 VGA compatible controller: NVIDIA Corporation GK106 [GeForce GTX 650 Ti Boost] (rev a1)
- **Exact command to reproduce**:

**Comment by drpngx** [comment]
Thanks for spotting this. Yes, a PR would be nice.

**Comment by wt-huang** [comment]
Closing this issue as PR is in place
