### ISSUE TITLE
Feature request: explicit state interfaces

### ISSUE THREAD

**Issue by netheril96** [tensorflow/tensorflow#11403]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: source 
- **TensorFlow version (use command below)**: 1.2.0
- **Python version**: 2.7.12
 
### Description:

The current API is immensely stateful. Each function and object creation affects and is affected by countless mutable global states. Running a declaration of `Variable` or summary mutates the graph and collections and may return different results based on the current `NameScope` or `VariableScope` or `control_dependencies`. A function running twice can easily return wildly different result, even though it *looks* pure (but it isn't because almost no tensorflow function is pure). Declaring something and then deleting it won't restore the global state, as it may or may not be added somewhere in the graph or the collections or some other hidden objects. Reasoning about what changes what is incredibly difficult.

What I would like to see is a API where all state mutations are explicit. When I declare a variable, it is just a variable, and not added to anything unless I call `add`. The current entangled interfaces can be built on top of that, preserving convenience functions such as `global_variable_initializers` for those who prefer.

**Comment by jart** [comment]
I agree with you that APIs which are free of side effects are awesome. I'm not sure how we would do something like that with TensorFlow, since it would be quite a paradigm shift. I'm sure the original designers carefully considered these trade-offs of the current approach years ago. I'm going to close this one out but CC: @mrry in case he wants to weigh in on this feedback.
