### ISSUE TITLE
cuDNN version issues

### ISSUE THREAD

**Issue by AdityaShirvalkar** [tensorflow/tensorflow#11401]
I am trying to train a ConvNet on my Windows laptop and I got this error.

Loaded runtime CuDNN library: 5005 (compatibility version 5000) but source was compiled with 5105 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.

I am already using cudnn v5.1, so I have no clue why this is happening

**Comment by h313** [comment]
What version of Tensorflow are you using? Is it a compiled version?

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by jart** [comment]
Could you fill out the form in the new issue template? Here's a similar recent issue about cudnn: https://github.com/tensorflow/tensorflow/issues/11389

**Comment by guschmue** [comment]
Maybe there is a old cudnn.dll in your path. Run
```where cudnn64_5.dll```
if there are multiple dll's.

**Comment by AdityaShirvalkar** [comment]
There was a old cudnn.dll in my path! Thanks for the help @guschmue
