### ISSUE TITLE
KL divergence not in tf.contrib.distributions as of 1.2.0

### ISSUE THREAD

**Issue by atabakd** [tensorflow/tensorflow#11419]
Apparently KL divergence is no longer in contrib.distributions.
This page is broken:
https://www.tensorflow.org/api_docs/python/tf/contrib/distributions/kl

and this file is removed:
tensorflow/contrib/distributions/python/ops/kullback_leibler.py

but I couldn't find it being mentioned in the changelog. Did I miss it?

**Comment by printdhruv** [comment]
I didn't understand your question correctly. But, If you are referring `API r1.2` than see the link [https://www.tensorflow.org/api_docs/python/tf/contrib/distributions/kl_divergence](https://www.tensorflow.org/api_docs/python/tf/contrib/distributions/kl_divergence)

**Comment by atabakd** [comment]
Oh I see. So it is just a name change from `kl` to `kl_divergence`

**Comment by printdhruv** [comment]
I also encourage you to review guidelines and follow template [here](https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md) before raising an issue.
