### ISSUE TITLE
NameError: name 'eval_input_fn' is not defined

### ISSUE THREAD

**Issue by LiYaHX** [tensorflow/tensorflow#11428]
OS : MacOS 10.12
TensorVersion : 1.2
PythonVersion : 2.7

Run the example of 'A custom model' in the document '[Getting Started With TensorFlow](https://www.tensorflow.org/get_started/get_started#a_custom_model)', occur the exception:
`Traceback (most recent call last):
  File "linear_regression_tf_contrib_learn_custom_model.py", line 35, in <module>
    eval_loss = estimator.evaluate(input_fn=eval_input_fn)
NameError: name 'eval_input_fn' is not defined`.

Fix : Need to add the code `eval_input_fn = tf.contrib.learn.io.numpy_input_fn({"x": x_eval}, y_eval, 4, num_epochs=1000)` at line 30.

**Comment by michaelisard** [comment]
Thanks! @dr4b could you take a look?

**Comment by dr4b** [comment]
This is a duplicate of #11123 and has been fixed in the master branch but won't show up as root until 1.3 is released.
