### ISSUE TITLE
Resource exhausted error for translate.py  Seq2seq model (CPU)

### ISSUE THREAD

**Issue by soukira** [tensorflow/tensorflow#11426]
Windows 10
Tensorflow: 1.0.0
Python version : 3.5
 I get the following error when i try to run translate.py for Seq2seq model 

Resource exhausted: OOM when allocating tensor with shape[576,1024]
Is there any way i could reduce the size in translate.py so that the error does not occur?
Thanks

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
