### ISSUE TITLE
wrong with tf.norm, it will produce nan

### ISSUE THREAD

**Issue by zklgame** [tensorflow/tensorflow#11427]
I use version 1.0.0 in server, in my code, the result will be nan if i use :
```
result = tf.square(tf.norm(penalize))
``` 
but if i change it to be:
```
result = tf.reduce_sum(tf.square(penalize))
```
everything will be ok, and result is some float between 0 and 1.

**Comment by lakshayg** [comment]
I was unable to reproduce the problem with v1.2.1. Could you please post a code snippet to reproduce the problem. BTW I would suggest that you use `tf.reduce_sum(...)` over `tf.square(...)` as it will likely be more efficient to compute.

**Comment by zklgame** [comment]
my related code snipper is:
```        
# softmax
# A.shape is [2, t]
A = tf.nn.softmax(A)

penalize = tf.matmul(A, tf.transpose(A)) - tf.diag(tf.ones(2))
penalize = tf.reduce_sum(tf.square(penalize))

# penalize = tf.square(tf.norm(penalize))
```

and what's the implement of your suggestion about use tf.reduce_sum(...) over tf.square(...)? Thx.

**Comment by lakshayg** [comment]
I tried this code snippet and it works perfectly fine on my machine with tf v1.2.1. Let me know if I'm missing something.

```python
import tensorflow as tf

A = tf.constant([[0.1, 0.2, 0.5], [0.3, 0.1, 0.2]])
A = tf.nn.softmax(A)

penalize = tf.matmul(A, tf.transpose(A)) - tf.diag(tf.ones(2))
result1 = tf.reduce_sum(tf.square(penalize))
result2 = tf.square(tf.norm(penalize))

with tf.Session() as sess:
    print(sess.run(result1))
    print(sess.run(result2))
```

When I said that you should prefer tf.reduce_sum(...) over tf.square(...), I meant that you should prefer `result = tf.reduce_sum(tf.square(penalize))` over `result = tf.square(tf.norm(penalize))`

**Comment by zklgame** [comment]
this simple program works fine in my server, too. but my original program is quite big and it takes time to run and print related logs. So I hope I can find what exactly happens with the numbers some day ...

**Comment by jart** [comment]
Thanks for helping our friend @lakshayg.
