### ISSUE TITLE
interpreter crashes with SIGSEGV (tf 0.7.0-cpu, python 3.5)

### ISSUE THREAD

**Issue by bmcfee** [tensorflow/tensorflow#1143]
I pip-installed the 0.7.0-cpu (linux) release on a python 3.5 conda environment, and now get the following error:

```
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
fish: “python” terminated by signal SIGSEGV (Address boundary error)
```

I also installed the 2.7 version in a separate conda environment, and everything works fine.  Both environments are up-to-date (`conda upgrade --all`).  Any ideas?

**Comment by chrisburr** [comment]
I've just seen the same issue, building and installing v0.7.0 from source (without gpu support) in a Python 3.5 conda environment works fine. Also installing tensorflow using pip in a Python 3.4 conda environment also works.

**Comment by elmar-haussmann** [comment]
Same here. Anaconda interpreter 3.5 crashes. 3.4 and 2.7 works fine. All with GPU support...

**Comment by vrv** [comment]
When you build the pip package from sources, what do your wheel package names look like?  I have a suspicion that the wheels we provided were too specific.

**Comment by chrisburr** [comment]
My wheel was named `tensorflow-0.7.0-py3-none-any.whl`

**Comment by dvbuntu** [comment]
I think I may have the same problem.  I'm using the wheel specified on the main TF website, `tensorflow-0.7.0-py3-none-linux_x86_64.whl`.  My system only reports `2663 segmentation fault (core dumped)  python` when trying to import, but doing `gdb python` and attempting to import reveals that it's a `SIGSEGV` underneath.  I've attached a backtrace in that situation if it helps.

On the surface, it looks like maybe a problem with `google::protobuf::python::message_meta`.  I updated this to the most recent version, tried uninstalling it.  No luck.  I am running ArchLinux underneath if it matters.
[backtrace.txt](https://github.com/tensorflow/tensorflow/files/135396/backtrace.txt)

**Comment by ogrisel** [comment]
If this is an ABI issue, then the following should help:

https://www.python.org/dev/peps/pep-0513/  # recently accepted spec for glibc based binary wheels for debian, ubuntu, redhat, centos, arch linux...

https://github.com/pypa/manylinux  # tooling based on docker + centos 5 for building wheels

https://github.com/pypa/auditwheel  # tooling to check and fix manylinux compatible wheels

**Comment by jjhelmus** [comment]
It looks like the segmentation fault is being caused when protobuf is imported, specifically the following:
``` Python
from google.protobuf import descriptor_pb2
```

This causes a segmentation fault when tensorflow 0.7.0 is installed but not when protobuf 3.0.0a3 is installed without installing tensorflow.

**Comment by bmcfee** [comment]
> This causes a segmentation fault when tensorflow 0.7.0 is installed but not when protobuf 3.0.0a3 is installed without installing tensorflow.

Indeed -- doing a `pip install protobuf==3.0.0a3` on this environment fixes the segfault, but now dies with a TypeError on import you mention:

```python
In [1]: import tensorflow as tf
[snip]
/home/bmcfee/miniconda/envs/py35/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py in <module>()
      8 from google.protobuf import reflection as _reflection
      9 from google.protobuf import symbol_database as _symbol_database
---> 10 from google.protobuf import descriptor_pb2
     11 # @@protoc_insertion_point(imports)
     12 
/home/bmcfee/miniconda/envs/py35/lib/python3.5/site-packages/google/protobuf/descriptor_pb2.py in <module>()
   1531 FileDescriptorSet = _reflection.GeneratedProtocolMessageType('FileDescriptorSet', (_message.Message,), dict(
   1532   DESCRIPTOR = _FILEDESCRIPTORSET,
-> 1533   __module__ = 'google.protobuf.descriptor_pb2'
   1534   # @@protoc_insertion_point(class_scope:google.protobuf.FileDescriptorSet)
   1535   ))
[snip]
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by jjhelmus** [comment]
The root of this issue seems to be coming from the 
`.../site-packages/google/protobuf/internal/_api_implementation.so` file.  Deleting this file allows tensorflow be imported in Python 3.5, although I cannot comment on if the resulting package is functional.  

I noticed while tracking this down that although the wheel file lists protobuf 3.0.0a3 as a required dependency, it also includes a complete copy of protobuf 3.0.0b2.  I believe that either the dependency or the copy of protobuf should be removed from the wheel.

**Comment by vrv** [comment]
@jjhelmus: I removed the copy of the protobuf from the wheel package in 76989f9839f4824aa9f5c1c1907fba3a02c1c83a, we now just rely on the whl dependency on 3.0.0b2.  I'm hoping this resolves most of the problems -- I'll try to push this out as part of our next 0.7.1 patch release.

In the meantime, my guess is you could probably get around this by pip uninstalling protobuf and then pip install protobuf=3.0.0b2, to remove the version we accidentally clobber and then reinstall the right version.

**Comment by jjhelmus** [comment]
@vrv The changes in 76989f9 look good and should fix the issue when new wheels are created.  Thanks for the quick fix.

I do not think a pip uninstall/install of protobuf will fix this issue with the 0.7.0 Python 3 wheel.  pip uninstall only removes files that were added by the package in question so the compiled libraries which are installed by tensorflow are not removed.  pip install protobuf installs the Python API so no new shared libraries are created and the broken ones from the tensorflow wheel are still in place.  

I think the best option is to change the wheel names to include the cp34 tag as the files contain libraries which will only work with CPython 3.4, although I'm guessing this ship has already sailed.

Should also note that the same behavior occurs when the 0.7.0 Python 3 linux wheels are installed in Python 3.3.

**Comment by vrv** [comment]
Agreed, we'll try to fix this for 0.7.1.

I guess we have to create 3-4 different wheels for each version of python.

**Comment by vrv** [comment]
Ok, updated wheels for 0.7.1 available.

We haven't yet built for python 3.5 on linux since it looks like only conda supports that.  @jjhelmus: since you seem to be maintaining the conda packages for tensorflow, do you want to take a stab for now at building from sources for conda?

**Comment by ogrisel** [comment]
> We haven't yet built for python 3.5 on linux since it looks like only conda supports that.

What is specific to the Python 3.5 / conda combo? I built tensorflow from the source using Python 3.5 installed from the [deadsnakes ppa](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes) on ubuntu trusty and everything seem to work fine.

You can also install build Python 3.5 from source but arguably getting it from anaconda is probably faster.

**Comment by jjhelmus** [comment]
I'll check into building tensorflow 0.7.1 conda packages from source this week.  Just need to find some free time to get bazel installed.

**Comment by jjhelmus** [comment]
I was able to create tensorflow 0.7.1 conda packages and wheel files from source which should work with the Python shipped with Anaconda.  Files are available for both linux-64 and osx-64 for Python 2.7, 3.4 and 3.5 in my [Anaconda.org channel](https://anaconda.org/jjhelmus/tensorflow).  

I believe with the release of 0.7.1 this issue can be closed.

**Comment by yoavram** [comment]
@jjhelmus I installed from your anaconda channel on py3.5 linux-64 and got the following error:
```
(tf)root@db6998cb4f9d:/# python -c "import tensorflow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/tf/lib/python3.5/site-packages/tensorflow/__init__.py",
line 23, in <module>
    from tensorflow.python import *
  File "/opt/conda/envs/tf/lib/python3.5/site-packages/tensorflow/python/__init_
_.py", line 49, in <module>
    from tensorflow import contrib
  File "/opt/conda/envs/tf/lib/python3.5/site-packages/tensorflow/contrib/__init
__.py", line 23, in <module>
    from tensorflow.contrib import layers
  File "/opt/conda/envs/tf/lib/python3.5/site-packages/tensorflow/contrib/layers
/__init__.py", line 68, in <module>
    from tensorflow.contrib.layers.python.layers import *
  File "/opt/conda/envs/tf/lib/python3.5/site-packages/tensorflow/contrib/layers
/python/layers/__init__.py", line 22, in <module>
    from tensorflow.contrib.layers.python.layers.initializers import *
  File "/opt/conda/envs/tf/lib/python3.5/site-packages/tensorflow/contrib/layers
/python/layers/initializers.py", line 24, in <module>
    from tensorflow.python.ops import random_ops
  File "/opt/conda/envs/tf/lib/python3.5/site-packages/tensorflow/python/ops/ran
dom_ops.py", line 23, in <module>
    from tensorflow.python.framework import ops
  File "/opt/conda/envs/tf/lib/python3.5/site-packages/tensorflow/python/framewo
rk/ops.py", line 39, in <module>
    from tensorflow.python.framework import versions
  File "/opt/conda/envs/tf/lib/python3.5/site-packages/tensorflow/python/framewo
rk/versions.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/opt/conda/envs/tf/lib/python3.5/site-packages/tensorflow/python/pywrap_
tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/opt/conda/envs/tf/lib/python3.5/site-packages/tensorflow/python/pywrap_
tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/opt/conda/envs/tf/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/envs/tf/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (re
quired by /opt/conda/envs/tf/lib/python3.5/site-packages/tensorflow/python/_pywr
ap_tensorflow.so)
```

**Comment by jjhelmus** [comment]
@yoavram What Linux are you running running this on?  Unfortunately due to the method in which tensorflow is built (Bazel) it will likely only run on Linux systems with a version of glibc equal too or newer than the one present on Ubunutu 14.04 (glibc 2.19).

**Comment by yoavram** [comment]
I'm not sure, it was a docker machine. I've managed since then to install using pip from a different docker machine. But maybe you can specify what you just said about glibc in the Anaconda page or in the conda package? Maybe try to check the version in  
Pre install script (http://conda.pydata.org/docs/building/build-scripts.html)?

**Comment by jjhelmus** [comment]
The whl files provided by Google and installed using pip also have the mentioned dependence on a minimum version of glibc.  Specially, the following external version symbols must be provided by system provided shared libraries:

```
GLIBC_2.14
CXXABI_1.3.5
GCC_3.0
GLIBCXX_3.4.19
```

I can try to add information about this dependency to the conda packages, although I will probably wait until the next release.

**Comment by yoavram** [comment]
Sounds good. Even having this info on this thread is probably helpful, thanks!

**Comment by girving** [comment]
@vrv Is this still an issue?

**Comment by vrv** [comment]
I mean I suspect it's always going to be an issue due to bazel, and all the information available is here, so we'll close this.
