### ISSUE TITLE
My CNN is not learning ,who can help me fix this problem? Thx !

### ISSUE THREAD

**Issue by FightingZhen** [tensorflow/tensorflow#11434]
[CNN.txt](https://github.com/tensorflow/tensorflow/files/1139040/CNN.txt)

That's the whole code of my CNN, the data for training, validation, test are all organized myself, which is not the problem.
While training this CNN, the result in Console showed that all weights and biases did not change. If I replace the RELU in six convolutional layers with Sigmoid, the CNN performed well.
Who can help me fix this problem? Thanks anyway ~

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
