### ISSUE TITLE
Rank calculated incorrectly using 'gen_array_ops.rank()'

### ISSUE THREAD

**Issue by namrata-ibm** [tensorflow/tensorflow#11431]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 'v1.2.1-0-gb4957ff', '1.2.1'
- **Python version**:  2.7.12
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: No GPU
- **GPU model and memory**: No GPU
- **Exact command to reproduce**: //tensorflow/python/kernel_tests:transpose_op_test

### The problem
While running TensorFlow tests such as  `//tensorflow/python/kernel_tests:transpose_op_test
` or `//tensorflow/contrib/distributions:mixture_test`, 
on a big endian system they fail with error: `ValueError: Dimension must be 2 but is 0 for 'Mixture_1/sample/Categorical/sample/transpose' (op: 'Transpose') with input shapes: [1,4], [0].`  

After debugging a little, realized that, while calculating `rank` of a tensor in [transpose method](https://github.com/tensorflow/tensorflow/blob/v1.2.1/tensorflow/python/ops/array_ops.py#L1276), the rank is calculated incorrectly via `gen_array_ops.rank(a)`.

I tried replacing `rank = gen_array_ops.rank(a)` to use the `array_ops.rank(a)` method instead and it works perfectly fine.

I tried the same change on an x86 machine and it doesn't break anything there.

I am unable to understand the difference between the two methods though. Also is there some major impact of above change which is not very obvious?

**Comment by mrry** [comment]
Switching to `array_ops.rank(a)` presumably fixes the problem because it's using the statically inferred rank from Python. I expect this would fail if, for some reason, `a` had a statically unknown rank (e.g. `a = tf.placeholder(tf.float32, shape=None)`).

Given the type punning involved in the [implementation of `TensorShape::dims()`](https://github.com/tensorflow/tensorflow/blob/99a38ffd9d77c55ca6d0c373c6d4b72686284ac5/tensorflow/core/framework/tensor_shape.h#L219), I'm not totally surprised that it fails on a big-endian machine. Hopefully this provides a pointer to the correct solution.

**Comment by namrata-ibm** [comment]
Thanks @mrry for your comments.

So switching to `array_ops.rank(a)` would not be the right thing to do even though majority of the tests are passing with this!  
I am going through `tensor_shape.h` and trying to figure out where exactly things are going wrong on big endian.
Another point to note is that `gen_array_ops.rank(a)` was working fine in TensorFlow version 0.10.0 and transpose tests were passing there.  There are no major changes in tensor_shape.h from v0.10.0 to v1.2.1 !

Have a question : Could you please point which rank definition does the `gen_array_ops.rank(a)` pick? The `def rank` from `gen_array_ops.py` just seems to call `_op_def_lib.apply_op("Rank", input=input, name=name)`.

**Comment by frreiss** [comment]
@namrata-ibm `gen_array_ops.rank()` is a generated wrapper for the `Rank` operator, which is defined at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/array_ops.cc?utf8=%E2%9C%93#L2191-L2212 .
The kernel associated with that operator is defined at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/shape_ops.h#L85-L98 .
The code that puts in place the mapping between kernel and operator is at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/shape_ops.cc#L193-L248 .

**Comment by namrata-ibm** [comment]
@frreiss, Thank you for your reply.

I am debugging this further, and realized that 
[const int rank = inp.dims();](https://github.com/tensorflow/tensorflow/blob/v1.2.1/tensorflow/core/kernels/shape_ops.h#L91) returns value `2` as expected. 
May be the output tensor is going wrong somewhere. Needs more debugging here.

**Comment by frreiss** [comment]
IIRC the size of an `int` on POWER is 64 bits. Perhaps the assignment at line 94 (`out->scalar<int32>()() = rank;`) is writing 8 bytes into the Tensor instead of 4? What happens if you change the type of `rank` from `int` to `int32_t`?
Source code for `Tensor::scalar()` is at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.h?utf8=%E2%9C%93#L641-L645 .
That function is a thin veneer over `TensorMap::operator()`, which is defined at https://bitbucket.org/eigen/eigen/src/8d1ccfd9c5a0bf1a662bd0fe35858f4e527d2bac/unsupported/Eigen/CXX11/src/Tensor/TensorMap.h?at=default&fileviewer=file-view-default#TensorMap.h-221:226

**Comment by namrata-ibm** [comment]
@frreiss, I am working on s390x arch. Replacing `int` to `int32_t` yields the same result.
The `rank` kernel hasn't changed much since v0.10.0 where the same was working. 
Inspecting `Tensor::scalar()` further now.

**Comment by shahidhs-ibm** [comment]
@frreiss @mrry We are able to narrow down the issue to the point of failure. For s390x, we are getting issue with [TF_RETURN_IF_ERROR(c->WithValue(perm_elems, rank, &perm_elems));](https://github.com/tensorflow/tensorflow/blob/v1.2.1/tensorflow/core/ops/array_ops.cc#L1797)

Adding a check is solving the issue for us:
```
if (!c->ValueKnown(perm_elems))
TF_RETURN_IF_ERROR(c->WithValue(perm_elems, rank, &perm_elems)); 
```

Please let us know if the solution looks ok to you.

**Comment by namrata-ibm** [comment]
@mrry, I was looking at the statically inferred rank vs statically unknown rank calculation. 
From the [code](https://github.com/tensorflow/tensorflow/blob/v1.2.1/tensorflow/python/ops/array_ops.py#L1276) : 
```
  with ops.name_scope(name, "transpose", [a]) as name: 
      if perm is None: 
        rank = gen_array_ops.rank(a) 
        perm = (rank - 1) - gen_math_ops._range(0, rank, 1) 
```

I printed the `range` calculated above, in 2 scenarios
1.  when , rank = gen_array_ops.rank(a) 
```
(Pdb) p gen_math_ops._range(0, rank, 1)
<tf.Tensor 'transpose/Range:0' shape=(0,) dtype=int32>
```
whereas 
2. If we change,  rank_a = rank(a)
```
(Pdb) p gen_math_ops._range(0, rank_a, 1)
<tf.Tensor 'transpose/Range:0' shape=(2,) dtype=int32>
```

In both cases, **rank / rank_a** is:
```
(Pdb) p rank
<tf.Tensor 'transpose/Rank:0' shape=() dtype=int32>
(Pdb) p rank.shape
TensorShape([])
(Pdb) p rank.eval()
2
(Pdb) p (gen_math_ops._range(0, rank, 1)).eval()
array([0, 1], dtype=int32)
```

Is there some other property of rank tensor which I haven't printed and is affecting the calaculation of shape of `Range`?

**Comment by mrry** [comment]
Can you also try tracing the execution of `tf.contrib.util.constant_value(gen_array_ops.rank(a))`? My suspicion is that it's returning `0` incorrectly, but I'm not sure why that would be.

**Comment by namrata-ibm** [comment]
@mrry, I had to use `tensor_util.constant_value(gen_array_ops.rank(a))` as ` tf.contrib.util.constant_value(gen_array_ops.rank(a))` gave errors like tf, contrib modules missing. I assume the former is equivalent in v1.2.1. 

The same failure is seen with this too.  :( 
This change works on Intel x86 though.


Little analysis:
```
(Pdb) p rank_a
array(0, dtype=int32)
(Pdb) p rank_a.shape
()
(Pdb) p rank_a.eval()
*** AttributeError: AttributeError("'numpy.ndarray' object has no attribute 'eval'",)
(Pdb) p (gen_math_ops._range(0, rank_a, 1)).eval()
array([], dtype=int32)

(Pdb) p tensor_util.constant_value(gen_array_ops.rank(a))
array(0, dtype=int32)
```

I could see calls made to [cpp_shape_handler.cc/ProtoFromShapeHandle](https://github.com/tensorflow/tensorflow/blob/v1.2.1/tensorflow/python/framework/cpp_shape_inference.cc#L34) . This implementation seems to be added after v0.10.0. Are these files involved during tensor object conversion from python to cpp?

**Comment by shahidhs-ibm** [comment]
Got the root cause of the issue. The conversion from ndarray to Tensor is causing trouble on big endian machine. Following is the change in file `tensorflow/python/framework/tensor_util.py` which is solving the problem (this file is from tag 1.3.0) :
```
--- a/tensorflow/python/framework/tensor_util.py
+++ b/tensorflow/python/framework/tensor_util.py
@@ -617,8 +617,9 @@ def _ConstantValue(tensor):
   elif tensor.op.type == "Rank":
     input_shape = tensor.op.inputs[0].get_shape()
     if input_shape.ndims is not None:
-      return np.ndarray(shape=(), buffer=np.array([input_shape.ndims]),
-                        dtype=np.int32)
+      return np.array([input_shape.ndims], np.int32) 
```
Now the tests failing on rank for big endian are passing.

**Comment by shahidhs-ibm** [comment]
Correcting the fix given in the above comment:
```
--- a/tensorflow/python/framework/tensor_util.py
+++ b/tensorflow/python/framework/tensor_util.py
@@ -617,7 +617,7 @@ def _ConstantValue(tensor):
   elif tensor.op.type == "Rank":
     input_shape = tensor.op.inputs[0].get_shape()
     if input_shape.ndims is not None:
-      return np.ndarray(shape=(), buffer=np.array([input_shape.ndims]),
+      return np.ndarray(shape=(), buffer=np.array([input_shape.ndims], dtype=np.int32),
                         dtype=np.int32)
     else:
       return None
```
The missing data type in the nparray is behaving differently on the big endian machines. This solution works fine for Intel as well zSystems architecture. Will create a PR for same.

**Comment by mrry** [comment]
Thanks for digging into that, @shahidhs-ibm! I'd be delighted to accept a PR that fixes this on your architecture. Is it possible that you've uncovered a bug in the underlying NumPy implementation as well?

**Comment by shahidhs-ibm** [comment]
@mrry Yes, indeed this is a bug in NumPy implementation.

On Intel:
```
# python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> z = np.ndarray(shape=(), buffer=np.array([1,2,3]), dtype=np.int32)
>>> z
array(1, dtype=int32)
>>> z = np.ndarray(shape=(), buffer=np.array([1,2,3], dtype=np.int32), dtype=np.int32)
>>> z
array(1, dtype=int32)
>>>

```
On zSystems:
```
# python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> z = np.ndarray(shape=(), buffer=np.array([1,2,3]), dtype=np.int32)
>>> z
array(0, dtype=int32)
>>> z = np.ndarray(shape=(), buffer=np.array([1,2,3], dtype=np.int32), dtype=np.int32)
>>> z
array(1, dtype=int32)
>>>
```
We will log a bug on NumPy for the incorrect conversion happening for ndarray.

**Comment by namrata-ibm** [comment]
Closing this issue as it is resolved
