### ISSUE TITLE
wide_n_deep Tutorial processing large data

### ISSUE THREAD

**Issue by sddi** [tensorflow/tensorflow#11441]
I am a freshman of tensorflow, and want to use the wide & deep network.
## I confuse if the data is large maybe 5 GB or more, and I cannot read all the data in memory, and how can I processing it? 

Thank you~~~

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
