### ISSUE TITLE
The window in tf.contrib.rnn.AttentionCellWrapper()

### ISSUE THREAD

**Issue by DaveYin** [tensorflow/tensorflow#11442]
It is very strange to have a fixed-sized window in the implementation of AttentionCellWrapper, because there is no description about it in the Bahdanau paper. Of course, the behave of the window is not clear, which makes me confused. Can anyone explain it?

**Comment by ebrevdo** [comment]
This is old legacy code.  I hope we can delete it soon.  Use the attention mechanism in tf.contrib.seq2seq instead.

**Comment by MtDersvan** [comment]
@ebrevdo Is there a way then to harness the new AttentionWrapper (from tf.contrib.seq2seq) for sequence classification (attention reduction)? E.g. as a words-to-sentence reduction step.
I mostly refer to the [Hierarchical Attention Networks for Document Classification](https://www.cs.cmu.edu/~diyiy/docs/naacl16.pdf) paper. tensorflow/nmt tutorial mostly shows it in use with a decoder.
Thanks.
