### ISSUE TITLE
Specify --no-install-recommends in apt-get install in Dockerfiles

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#1145]
Explicitly list needed packaged in Dockerfile and then add `--no-install-recommends` so that unneeded packaged are not added. For example right now install OpenJDK tried to install fuse.

* `unzip` needs to be added to the list of packages to install.

**Comment by girving** [comment]
Martin's unassignment of @jendap was an accident.

**Comment by cancan101** [comment]
See: https://github.com/4Catalyzer/tensorflow/commit/83ebb0a0f1995441af66f476a19a97524748be95

**Comment by caisq** [comment]
Fixed by commit e19437c09af0ba8eb83b282ffd4b76a2444f01d3
