### ISSUE TITLE
How to use pre-trained models for fine tuning on different dataset ?

### ISSUE THREAD

**Issue by indra215** [tensorflow/tensorflow#11457]
Hi,

I have downloaded a pre-trained model for inception v3 (inception_v3_2016_08_28.tar.gz file)from [https://github.com/tensorflow/models/tree/master/slim#Pretrained](url) which contains the file inception_v3.ckpt. Could anyone please help me how to use this file to fine-tune on a different dataset ?

Thanks in advance.

**Comment by carlthome** [comment]
The resource you've already linked has a thorough example, no? Anyway, try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) for help. I believe GitHub is meant for bug reports and feature requests.

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
