### ISSUE TITLE
GPU-Isolated docker containers fail in a distributed training with more than one worker.

### ISSUE THREAD

**Issue by MtDersvan** [tensorflow/tensorflow#11456]
### System information
- **Have I written custom code**: Yes
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: No
- **TensorFlow version**: v1.2.0-rc2-21-g12f033d 1.2.0
- **Python version**: Python 3.5.2
- **Bazel version**: -
- **CUDA/cuDNN version**: 'CUDA_VERSION': '8.0.61' / 'CUDNN_VERSION': '5.1.10'
- **GPU model and memory**: 8x GCE K80 Tesla

### Context:
1) I have created a Cloud Compute Engine instance with 8 GPUs.
2) I have started a couple of GPU-isolated containers with intention to run each as a separate worker:
`sudo NV_GPU=0 nvidia-docker run -it --name tf_worker_0 -p 8000:8000 -v /$(pwd)/repo:/notebooks/repo gcr.io/tensorflow/tensorflow:latest-gpu-py3 /bin/bash` 

3) To create a loopback to the host I run following:
`echo $(netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}') dockerhost >> /etc/hosts`
Through `dockerhost` it properly detects and pings all the open ports on the host including processes running in other containers that are exposed with `-p hostport:containerport`.

### Problem:
*Case 1 - Normal*: When I run a distributed TensorFlow script using `dockerhost` with only one `worker` and any number of `ps` servers (e.g.  `--ps_hosts=dockerhost:7000,dockerhost:7001 --worker_hosts=dockerhost:8000`) everything works as intended - local grcp servers are launched, worker and ps communicate well. 

*Case 2 - Issue*: When I increase the number of worker jobs (e.g.  `--worker_hosts=dockerhost:8000,dockerhost:8001`) i get `Master init: Unavailable` and `Master init: Internal` Errors. 

*Case 3 - Normal*: BTW, everything works smoothly when I run all the workers inside a single container isolating GPUs with `CUDA_VISIBLE_DEVICES`.

*Case 4 - Issue*: Also, it is worth mentioning here, that using queues solution to shutdown `ps` proposed in https://github.com/tensorflow/tensorflow/issues/4713 fails in both Case 1 and Case 2. This results in immediate `tensorflow.python.framework.errors_impl.UnavailableError` when starting `ps`.

### Statement:
Is this an intended behaviour? Or does such setting is insufficient for a distributed training and a special `master` server or a cluster manager is needed? It just seems interesting that it would work for one worker but not for more.

**Reproducible Toy Example**:
[repr.txt](https://github.com/tensorflow/tensorflow/files/1142032/repr.txt)

**Log**:
[worker_log.txt](https://github.com/tensorflow/tensorflow/files/1142041/worker_log.txt)

**Comment by MtDersvan** [comment]
Also, I posted an SO question under `tensorflow` tag and it was not answered by a tensorflow team just yet:
https://stackoverflow.com/questions/44804982/google-compute-engine-tesla-k80-has-additional-htod-an-dtoh-ops-and-a-way-lower
It would be really nice to get an answer to it.

**Comment by mrry** [comment]
It sounds like the two docker containers aren't reachable from one another. Can you verify that if you start a  `tf.train.Server` in one container, you can connect to it (create a `tf.Session(server_target)` where `server_target` is the address you expect the server to have) in the other?

**Comment by MtDersvan** [comment]
Thanks for a quick reply @mrry.
If I understand you correctly, here are my steps:

**Container I: port:8000**
1] Launch `tf_worker_0`:
```
sudo NV_GPU=0 nvidia-docker run -it --name tf_worker_0 -p 8000:8000 -v /$(pwd)/repo:/notebooks/repo gcr.io/tensorflow/tensorflow:latest-gpu-py3 /bin/bash
```
2] Install dependencies and establish a loopback connection:
```
apt-get update && apt-get upgrade &&  apt-get install net-tools
echo $(netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}') dockerhost >> /etc/hosts
```
3] In `tf_worker_0` run and launch a local server:
```
import tensorflow as tf
cluster = tf.train.ClusterSpec({"local": ["dockerhost:8000", "dockerhost:8001"]})
server = tf.train.Server(cluster, job_name="local", task_index=0)
```
Out: `... Started server with target: grpc://localhost:8000 ...`

**Container II: port:8001**
1] Launch `tf_worker_1`:
```
sudo NV_GPU=1 nvidia-docker run -it --name tf_worker_1 -p 8001:8001 -v /$(pwd)/repo:/notebooks/repo gcr.io/tensorflow/tensorflow:latest-gpu-py3 /bin/bash
```
2] Install dependencies and establish a loopback connection:
```
apt-get update && apt-get upgrade &&  apt-get install net-tools
echo $(netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}') dockerhost >> /etc/hosts
```
3] In `tf_worker_1` launch:
```
import tensorflow as tf
cluster = tf.train.ClusterSpec({"local": ["dockerhost:8000", "dockerhost:8001"]})
server = tf.train.Server(cluster, job_name="local", task_index=1)
```
Out: `... Started server with target: grpc://localhost:8001 ...`

4] Run an op on a Container I:
```
with tf.Session('grpc://dockerhost:8000'.encode()) as sess:
print(sess.run(tf.constant(0)))
```
Out: `0`. 

So it looks like they reach each other properly.

Meanwhile the issue persists. Here are the commands to reproduce issue from `repr.py` toy example:
```
CUDA_VISIBLE_DEVICES='' python3 repr.py --ps_hosts=dockerhost:7000 --worker_hosts=dockerhost:8000,dockerhost:8001 --job_name=ps --task_index=0
python3 repr.py --ps_hosts=dockerhost:7000 --worker_hosts=dockerhost:8000,dockerhost:8001 --job_name=worker --task_index=0
python3 repr.py --ps_hosts=dockerhost:7000 --worker_hosts=dockerhost:8000,dockerhost:8001 --job_name=worker --task_index=1
```

**Comment by mrry** [comment]
Can you try expanding the working example to include three servers in two jobs (i.e. using the same `tf.train.ClusterSpec`, but just creating a `tf.Session` and running a single op)?

**Comment by MtDersvan** [comment]
@mrry do you mean keeping the same `tf.train.ClusterSpec`:
```
cluster = tf.train.ClusterSpec({"local": ["dockerhost:8000", "dockerhost:8001"]})
```
, but just creating three `tf.Session` or `tf.train.Server`? With what targets?

Creating the same `tf.train.Server(cluster, job_name="local", task_index=1)` not surprisingly shows `UnknownError: Could not start gRPC server`, because `task_index` job is already started.

Running this:
```
with tf.Session('grpc://dockerhost:8000'.encode()) as sess:
    print(sess.run(tf.constant(0)))
```
multiple times with any targets (8000 or 8001) does not show any errors.

If this is not what you wanted me to reproduce, please, provide a snippet to run, thanks.

**Comment by mrry** [comment]
Catching up on very old issues: I don't have a way to reproduce this issue, and it is most likely a Docker configuration problem rather than a TensorFlow problem, so I'm going to mark it as "community support".

**Comment by MtDersvan** [comment]
I have already migrated from this setup, so feel free to close this, as it's not relevant any more.

**Comment by mrry** [comment]
Thanks!
