### ISSUE TITLE
python create model and c++ uses model without bazel

### ISSUE THREAD

**Issue by yjl9122** [tensorflow/tensorflow#11453]
I just have used python to create ckpt model. But i have to use c++ to test my picture without bazel. Some one can help me? I am so eager to solve this problem! Thanks!!

**Comment by carlthome** [comment]
Here's [a tutorial](https://www.tensorflow.org/performance/xla/tfcompile) for compiling standalone programs from a TensorFlow graph.

PS: Your question is more suited for [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) with the tag tensorflow because it's not a bug report.
