### ISSUE TITLE
Retrieving LLVM IR from AOT tfcompile

### ISSUE THREAD

**Issue by williamjeremy** [tensorflow/tensorflow#11462]
Is it possible to get LLVM intermediate representation (.ll) files from tfcompile instead of object code? If so, how can it be done? Alternatively, can one get source code instead of object code from tfcompile?

**Comment by tatatodd** [comment]
@williamjeremy there isn't a mechanism right now, but I'm adding simple support for this right now.  Once it's in, you'll be able to set the --xla_dump_ir_to flag to specify a directory to dump out the LLVM IR, pre and post optimization.

There is no way to dump source code, if by "source code" you mean something like C or C++.  tfcompile takes as input the TensorFlow graph, which is lowered to XLA HLO, which is lowered to LLVM IR, which is lowered to machine code.

I'll update this issue once the support has been merged.

**Comment by tatatodd** [comment]
https://github.com/tensorflow/tensorflow/commit/201fa224e178b76ece4723c433a17df10005341c added the `--xla_dump_ir_to` support to the AOT codepath, so I'm closing this out.

**Comment by vsahil** [comment]
> Is it possible to get LLVM intermediate representation (.ll) files from tfcompile instead of object code? If so, how can it be done? Alternatively, can one get source code instead of object code from tfcompile?

@williamjeremy were you able to get the LLVM files, if yes, can you please send a complete example with the commands. Thank you in advance!
