### ISSUE TITLE
Custom Beam Search Decoder with sampling

### ISSUE THREAD

**Issue by yangshao** [tensorflow/tensorflow#11466]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.1.0
- **Python version**: 3.4.3
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 7.5
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
I want to incorporating sampling into the  beam search decoder for seq2seq model. Is there any example or document on how to implement it?

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by jihopark** [comment]
@yangshao hi i also want to implement this. any progress?
