### ISSUE TITLE
Cannot restore faster_rcnn checkpoint

### ISSUE THREAD

**Issue by MloveDaxiong** [tensorflow/tensorflow#11476]
I want to reload faster_rcnn_resnet101 model parameters and run as follows: 

python export_inference_graph.py --input_type image_tensor --pipeline_config_path samples/configs/faster_rcnn_resnet101_coco.config --checkpoint_path checkpoints/faster_rcnn_resnet101_coco_checkpoint/model.ckpt --inference_graph_path checkpoints/faster_rcnn_resnet101_coco_checkpoint/test.pb

But it poses OutOfRangeError.
OutOfRangeError (see above for traceback): Read less bytes than requested
	 [[Node: save/RestoreV2_408 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_408/tensor_names, save/RestoreV2_408/shape_and_slices)]]
	 [[Node: save/RestoreV2_528/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1164_save/RestoreV2_528", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

What can I do for this error?

**Comment by MloveDaxiong** [comment]
@petewarden I can't find a node named "save/RestoreV2_528/_1". En.. Can you give me some advices about this?

**Comment by shreyneil** [comment]
There seems to be a problem with the checkpoint file you are using. Due to the use of a wrong checkpoint value it might be throwing this error. Please try to verify and get back.

**Comment by MloveDaxiong** [comment]
@shreyneil Yes, I think so. However, this checkpoint is unzip from tensorflow official website(github). And now, I am trying to decrease tensorflow version to r1.1.0(Because, yesterday I found that the same code about tensorboard worked well on r1.1.0, but wrong for r1.2.0). Hope that will be useful.

**Comment by shreyneil** [comment]
I hope that works and make sure you close the issue if it does so. If you get any further errors please get back.

**Comment by MloveDaxiong** [comment]
It works.
