### ISSUE TITLE
Does inception model detect multiple object in one image?

### ISSUE THREAD

**Issue by ManojPabani** [tensorflow/tensorflow#11478]
I have use retrain.py to train tensorflow with my own dataset of traffic sign but it seems it doesn't capture multi-object in one image.I am using the label_image.py to detect the object in my image.I have an image of two road sign which exists in my dataset but i get only one sign with high accuracy.It doesn't detect other sign.

**Comment by vincentvanhoucke** [comment]
Inception is a classification model, not a detection model. It only labels entire images. Please don't use bugs as a question forum, prefer StackOverflow for that.
