### ISSUE TITLE
'return_state' in keras rnn layers

### ISSUE THREAD

**Issue by junja94** [tensorflow/tensorflow#11487]
Im using tensorflow r1.2.
 In the original Keras, There's an option to get the last hidden state of a rnn layer. (
https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L99 )
And it disappeared in tensorflow version of the keras.
(https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/contrib/keras/python/keras/layers/recurrent.py#L89)

Is there any reason for this?? I think the 'return_state' option is quite useful.

**Comment by jart** [comment]
@fchollet Here's a question about changes to Keras for you.

**Comment by junja94** [comment]
Ah I just figured out that there is the 'return_state' option in the latest code.
I'll wait for r1.3 :)

**Comment by fchollet** [comment]
Yes, it will be in the next release. It is already on `master`.
