### ISSUE TITLE
tf.device with function leads to incompatible device names

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#11484]
### System information
- **OS Platform and Distribution: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: ('v1.2.0-rc2-21-g12f033d', '1.2.0')
- **Python version**:  2

```python
import tensorflow as tf
with tf.device('/gpu:0'):
    x = tf.constant([1, 2, 3])
    print(x.device)
with tf.device(lambda op: '/gpu:0'):
    y = tf.constant([1, 2, 3])
    print(y.device)
G = tf.get_default_graph()
with G.colocate_with(y):
    with tf.device('/gpu:0'):
        z = tf.constant([1,2,3])
        print(z.device)
```

Outputs:
```
/device:GPU:0
/gpu:0
WARNING:tensorflow:Tried to colocate Const_2 with an op Const_1 that had a different device: /device:GPU:0 vs /gpu:0. Ignoring colocation property.
/device:GPU:0
```

When using device function, '/gpu:0' doesn't get translated to '/device:GPU:0'. This can lead to very confusing warning messages when used together with colocate.

**Comment by michaelisard** [comment]
@vrv I'm not sure who has taken this over from you. The names should be canonicalized I guess.

**Comment by vrv** [comment]
eh, I added the code recently, I'll fix this one.

**Comment by ppwwyyxx** [comment]
https://github.com/tensorflow/benchmarks/issues/44
Seems like the device names are not canonicalized in other places either.
