### ISSUE TITLE
Link for iOS doc doesn't work

### ISSUE THREAD

**Issue by massoud12345** [tensorflow/tensorflow#11486]
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/ios_examples/

**Comment by michaelisard** [comment]
Thanks for the report. Could you point to where the source of the bad link was?

**Comment by massoud12345** [comment]
Sure: https://www.tensorflow.org/mobile/

**Comment by michaelisard** [comment]
Thanks!

**Comment by dr4b** [comment]
We are deprecating/updating that page soon, but I've fixed the link for you for now.

**Comment by massoud12345** [comment]
Thank you very much. I'm happy to use whatever is the current reference. This is the page I was led to by tensorflow.org. Thanks
