### ISSUE TITLE
Issue and Pull Request Templates

### ISSUE THREAD

**Issue by herpdederp** [tensorflow/tensorflow#1148]
Would help with organization and getting all the relevant info. Requires adding files issue_template.md and pull_request_template.md

**Comment by jimfleming** [comment]
Context: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by vrv** [comment]
Indeed, I have a pending change to add this (that we can iterate on)

**Comment by vrv** [comment]
Okay added one here: https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md
