### ISSUE TITLE
MultiGPU multi-session 

### ISSUE THREAD

**Issue by surajkamal** [tensorflow/tensorflow#11495]
It would be nice if there is an official way to do limit devices initialised by tensorflow other than the os level environment variable settings specifically as in[ this](https://stackoverflow.com/a/34776814) answer posted by @mrry in stackoverflow. As of my understanding the setup mentioned in [another](https://stackoverflow.com/a/34200194) answer by @mrry will not prevent tensorflow from grabbing all the GPU resources available on a same workstation at initialization as it is in by `tf.train.Server()`.  It would be essentially helpful for those sharing a machine among multiple users, so that they could independently initiate tensorflow graphs in different GPU units. Although this could be achieved via `nvidia-docker `or other resource orchestration tools, a native API would be a great addition to tensorflow.  Please ignore this if there is already an official way or my understanding is wrong.

**Comment by jubjamie** [comment]
Does [Manual GPU Device Placement](https://www.tensorflow.org/tutorials/using_gpu#manual_device_placement) answer your question?

**Comment by surajkamal** [comment]
I think it may not, because tensorflow grabs all the available GPU RAM (a good share of it) while a call to `tf.train.Server()` is made from one process, so other process that could possibly co-exist with it may not get enough RAM which would essentially fail.  The option of  manual device placement or allocating finite amount of GPU RAM might sounds to be a solution, but the previous condition do not allows that, if I understood it correctly. I have tried `config.gpu_options.visible_device_list` also but it didn't help. In the stackoverflow answer @mrry points out as calling separate process with a prefix from the shell, and similarly [here](https://stackoverflow.com/a/37901914) in the python code itself. Both of it works but it would be great if there is a native way to do this in tensorflow API to make thing straight forward. This would be particularly preferable when a node with many GPU is shared among multiple users, so that each of them could independently run their task on the same node. It may not be a problem with `ingraphreplication` because as you mentioned all GPUs are utilised by a single process with manual device placement. Is there anything fundamentally prevents from doing this, such as os level GPU arbitration or something?. Though `apache mesos` or similar systems provides much higher level ways to do this, it would be nice if this could be done with the native tensorflow code.

**Comment by mrry** [comment]
Are you creating a `tf.train.Server` in your program? In that case you can programmatically limit the GPUs used by passing a `tf.ConfigProto` (with `config.gpu_options.visible_device_list` set as desired) as the `config` argument to the `Server` initializer. (The same option will be ignored when you create a `tf.Session` against a server, because the GPU devices are configured at server construction time, and shared between all sessions that use that server.)

**Comment by surajkamal** [comment]
Thanks for the response. Yes I am creating a `tf.train.Server` from the program. As exactly @mrry mentioned the  `config.gpu_options.visible_device_list` has been passed into a` tf.Session`, where it is mostly expected and definitely it is ignored by the session. I will try passing the option to server initialiser and let you know.
```
    config = tf.ConfigProto(log_device_placement=False, allow_soft_placement=True)
    config.gpu_options.per_process_gpu_memory_fraction = 0.4
    config.gpu_options.allow_growth=True
    config.gpu_options.visible_device_list = str(task_index)
    server = tf.train.Server(spec, job_name=job_name, task_index=task_index, config=config)
```

Yes, it is working, I should add the GPU RAM fraction specification is also working while it is passed to the server initialiser nicely (what are the `tf.ConfigProto` options that the `tf.Session` takes in really?).  However this is not clear from the current documentation, in fact not in many other discussions on the same matter. Hope this would help other people trying to get the same functionality with Tensorflow without depending on other complicated resource scheduling schemes. Great work, thank you.

**Comment by drpngx** [comment]
@surajkamal closing, since it seems that it is working out for you. Please re-open if I misunderstood.

/CC @MarkDaoust for consideration of the documentation.
