### ISSUE TITLE
Tensorflow-serving(CPU) for xbox one/ps4/switch ?

### ISSUE THREAD

**Issue by glaporte** [tensorflow/tensorflow#11497]
Hello,
First of all I would like to thank the developer of tensorflow for this great library.

Can tensorflow-serving(CPU) works on xbox1 or ps4? (i mean to compile it)

Thank you.

**Comment by asimshankar** [comment]
TensorFlow can be built from sources (see https://www.tensorflow.org/install/install_sources). However, the platforms you mention are not officially supported and we might not be able to provide much help in dealing with problems that arise.

That said, we encourage community contributions, so if you do get things to work, we'd encourage you to contribute back with the changes to code and/or documentation necessary.

Thanks!
