### ISSUE TITLE
tf.einsum does not have "name" variable

### ISSUE THREAD

**Issue by mjs-wpi** [tensorflow/tensorflow#11501]
I noticed there is no ability to name a tensor generated from from tf.einsum(). Is this on purpose?

**Comment by mrry** [comment]
It sounds like an oversight! Would you like to send a PR to fix this?

**Comment by jart** [comment]
This sounds like an good opportunity for a community member to become a TensorFlow contributor.

**Comment by yongtang** [comment]
Added PR #11510

**Comment by mjs-wpi** [comment]
@jart I'm so new to coding that I wouldn't even know where to start; I'm math guy who just learned what a pull request was now.
