### ISSUE TITLE
import_pb_to_tensorboard.py fails with TypeError

### ISSUE THREAD

**Issue by daj** [tensorflow/tensorflow#11519]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No.
- **OS Platform and Distribution**: Mac OSX Sierra 10.12.5
- **TensorFlow installed from**: Source.
- **TensorFlow version**: ('v0.10.0-1727-g484ca8a-dirty', '0.11.0rc0')
- **Python version**: 2.7.6
- **Bazel version**: 0.4.4-homebrew
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
```
python import_pb_to_tensorboard.py --model_dir ~/Code/AndroidTensorFlowMNISTExample/app/src/main/assets/mnist_model_graph.pb --log_dir /tmp/tensorboard/
```

### Describe the problem
I'm trying to use `import_pb_to_tensorboard.py` to import an existing TensorFlow model into TensorBoard.  It appears to always return a TypeError due to line 74:

```
python import_pb_to_tensorboard.py --model_dir ~/Code/AndroidTensorFlowMNISTExample/app/src/main/assets/mnist_model_graph.pb --log_dir /tmp/tensorboard/
Traceback (most recent call last):
  File "import_pb_to_tensorboard.py", line 74, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
TypeError: run() got an unexpected keyword argument 'argv'
```

I discovered `import_pb_to_tensorboard.py` in [this Stackoverflow answer](https://stackoverflow.com/a/44955005/112705).

**Comment by asimshankar** [comment]
Marking this as "Contributions Welcome" since it seems you already have a PR to improve the tool.

**Comment by iskenderunlu** [comment]
Is there anyone who can assign the problem to me ? Thanks

**Comment by AswinBlue** [comment]
I recommend you to reference these methods.
It must be run 0.12 tensorflow.

https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/examples/learn/text_classification.py

https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/python/platform/app.py

**Comment by AswinBlue** [comment]
I recommend you to reference these methods.
It must be run 0.12 tensorflow.

https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/examples/learn/text_classification.py
![image](https://user-images.githubusercontent.com/29457193/29652320-e338afce-88df-11e7-822e-e2c4aebd0153.png)
He references another import.

https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/python/platform/app.py
He use sys.exit() function.

**Comment by easyhangul** [comment]
I recommend you to reference these methods.
It must be run 0.12 tensorflow.

https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/examples/learn/text_classification.py
![image](https://user-images.githubusercontent.com/29457193/29652320-e338afce-88df-11e7-822e-e2c4aebd0153.png)
He references another import.

https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/python/platform/app.py
He use sys.exit() function.

**Comment by daj** [comment]
Thanks to @easyhangul, that was the problem!  I followed [the instructions to upgrade my TensorFlow](https://www.tensorflow.org/install/install_mac) installation, and then  `import_pb_to_tensorboard.py` ran without errors.  

Enhancement suggestion: it would be great if the Python tools could check that the local installation of TensorFlow is at the required minimum version.  The error returned here is not very user-friendly.

**STEPS TO FIX**

I had to upgrade `pip` from 8.1.2 to 9.0.1, then I ran `pip install --upgrade tensorflow`.

Now I'm running v1.3.0:
```
$ python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
('v1.3.0-rc2-20-g0787eee', '1.3.0')
```
...and `import_pb_to_tensorboard.py` appears to run successfully:
```
$ python import_pb_to_tensorboard.py --model_dir ~/Code/AndroidTensorFlowMNISTExample-daj/model/mnist_model_graph.pb --log_dir /tmp/tensorflow_logdir
<warnings snipped>
Model Imported. Visualize by running: > tensorboard --logdir=/tmp/tensorflow_logdir
```
I can now see something in my TensorBoard:
![screen shot 2017-08-27 at 3 20 26 pm](https://user-images.githubusercontent.com/739125/29753258-4ee90c70-8b3b-11e7-8b44-6b5aee0aaeab.png)
This doesn't seem entirely correct, but this particular GitHub issue is resolved.

**Comment by flankechen** [comment]
@daj I got the same error with tensorflow 1.4.0. Could you specify more about this?
`('v1.4.0-rc1-11-g130a514', '1.4.0')`

`Traceback (most recent call last):
  File "import_pb_to_tensorboard.py", line 76, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "import_pb_to_tensorboard.py", line 58, in main
    import_to_tensorboard(FLAGS.model_dir, FLAGS.log_dir)
  File "import_pb_to_tensorboard.py", line 48, in import_to_tensorboard
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message`

**Comment by wt-huang** [comment]
Closing as this is resolved
