### ISSUE TITLE
ImportError: No module named pbr.version

### ISSUE THREAD

**Issue by ns92** [tensorflow/tensorflow#11517]
Hi everybody. I've this problem also when i run openstack --version. Solutions?

**Comment by printdhruv** [comment]
Please review guidlines before raising an issue here. [https://github.com/printdhruv/tensorflow/blob/master/ISSUE_TEMPLATE.md](https://github.com/printdhruv/tensorflow/blob/master/ISSUE_TEMPLATE.md)

**Comment by junlulocky** [comment]
hey, my solution:
for windows:
sudo /bin/env pip uninstall pbr ## important
sudo /bin/env python pip install pbr

for MAC
sudo /usr/bin/env pip uninstall pbr ## important
sudo /usr/bin/env python pip install pbr

checkout this link for why use '/usr/bin/env' beforehand: http://www.junlulocky.com/blog/pythontricks

**Comment by stardolphin** [comment]
On mac, pip was not available outside of the virtualenv, so:
sudo easy_install pbr

did the trick.

**Comment by blueskea** [comment]
sudo pip install pbr --ignore-installed
