### ISSUE TITLE
Build fails on FreeBSD 11

### ISSUE THREAD

**Issue by yurivict** [tensorflow/tensorflow#11524]
```
external/grpc/src/core/lib/iomgr/socket_utils_common_posix.c:101:39: error: use of undeclared identifier 'IP_PKTINFO'
  if (0 != setsockopt(fd, IPPROTO_IP, IP_PKTINFO, &get_local_ip,
                                      ^
```

**Comment by byronyi** [comment]
Seems like a gRPC portability issue. 

TF currently doesn't support BSD officially, but contributions are always welcomed.

**Comment by asimshankar** [comment]
Thanks @yurivict . As @byronyi pointed out, FreeBSD is not officially supported but this does seem to be an incompatibility in GRPC. I'd encourage you to make a fix to [grpc](https://github.com/grpc/grpc/blob/7897ae9/src/core/lib/iomgr/socket_utils_common_posix.c#L85) (perhaps by ensuring that `GRPC_HAVE_IP_PKTINFO` is false for FreeBSD).
