### ISSUE TITLE
Feature request: GPU support for tf.bincount

### ISSUE THREAD

**Issue by iurilarosa** [tensorflow/tensorflow#11554]
Hi. In my opinion, `tf.bincount` is a very useful and simple function to build weighted histograms like in the example below, but recently i learned that unfortunately does not have GPU support. It could be very useful to run it on GPU, since i can't figure any simple way to do a weighted histogram efficiently. Thanks.

```
sess = tf.Session()

values = tf.random_uniform((1,50),10,20,dtype = tf.int32)
weights = tf.random_uniform((1,50),0,1,dtype = tf.float32)

counts = tf.bincount(values, weights = weights)

histogram = sess.run(counts)
print(histogram)
```

**Comment by asimshankar** [comment]
I don't believe anyone is actively working on this at this point, but it seems like a fine thing to pursue.
Contributions are welcome.

FYI @ringw @ekelsen

**Comment by ekelsen** [comment]
This should be pretty easy to do now that CUB is part of the TF release, I'll look into it.

**Comment by iurilarosa** [comment]
Thank you. Anyone can imagine another way to build a weighted histogram with tf functions on GPU? Maybe with sparse matrices? I know that when you build a sparse matrix values with the same coordinates are summed.

**Comment by ekelsen** [comment]
It isn't as easy as I thought to add the CUB version, the cub histogram doesn't support weights.

For now, it would be pretty easy to use unsorted_segment_sum to mimic a (possibly weighted) histogram.  data=weights (could be all ones) and segment_ids=keys.

**Comment by iurilarosa** [comment]
Thank you so much! I didn't know this function, only the sorted version. It returns exactly the same values, with the bonus that i can choose the number of bins with the third argument. It runs quite fast, albeit doubles the time of `bincount` on CPU. It could still be very interesting to know if, with `bincount` on GPU, i can improve performance of my code. Unfortunately i have to do weighted histograms with a big amount of data.

**Comment by ekelsen** [comment]
How many bins?

**Comment by iurilarosa** [comment]
Around 10^4 bins for arrays around 2.5 x 10^6 elements. Here is a simplified example of my program.

```
import numpy
import tensorflow as tf

#first i build a matrix of some x positions vs time datas in a sparse format
matrix = numpy.random.randint(2, size = 100).astype(float).reshape(10,10)

x = numpy.nonzero(matrix)[0]
times = numpy.nonzero(matrix)[1]
weights = numpy.random.rand(x.size)

#then i define an array of y positions
nStepsY = 5
y = numpy.arange(1,nStepsY+1)

#this is only an example, in my work these arrays are the input
#from a file or a preceding function

nRows = nStepsY
nColumns = 80

x = tf.constant(x, dtype = tf.float32)
times = tf.constant(times, dtype = tf.float32)
weights = tf.constant(weights, dtype = tf.float32)
y = tf.constant(y, dtype = tf.float32)


def itermatrix(ithStep):
    yTimed = tf.multiply(y[ithStep],times)

    positions = tf.round((x-yTimed)+50)
    positions = tf.cast(positions, dtype=tf.int32)

    values = tf.unsorted_segment_sum(weights, positions, nColumns)

    return values

imageMapped = tf.map_fn(itermatrix, tf.range(0,nRows), dtype=tf.float32)

sess = tf.Session()

image = sess.run(imageMapped)
```


The problem is that i have to do these histograms for around 100 y steps, building and storing `image` for thousands of input matrices. The `position` transformation could be vectorized, but the binning part of each row is independent so i used `tf.map_fn` to manage the single input matrix. Now that thanks to you the histogram problem is solved, I'm working on the big data problem.

**Comment by ekelsen** [comment]
If the number of bins fit into the shared memory of the GPU (48kb / 4bytes ~ 12,000 bins max) then you might be able to write a faster version of unsorted_segment_sum that does atomics in shared memory and then to global memory.  I think right now everything goes straight to global memory.

**Comment by iurilarosa** [comment]
At the moment I'm not quite good both with GPU programming and Tensorflow to do this, but i hope i will improve my experience. However, i checked my data and I'm afraid the number of bins is 10^5 and not 10^4.

**Comment by yongtang** [comment]
Added a PR #13813 for the GPU kernel of bincount. Didn't use CUB as the weight issue mentioned. Please take a look.
