### ISSUE TITLE
Segmentation fault occured when I install tensorflow r1.2  with bazel

### ISSUE THREAD

**Issue by lumiaomiao** [tensorflow/tensorflow#11550]
------------------------
Hi, when I builded tensorflow r1.2 I got following error:
`tensorflow-1.2--mkl/tensorflow/contrib/framework/BUILD:108:1: Executing genrule //tensorflow/contrib/framework:gen_variable_ops_pygenrule failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 11.
/bin/bash: line 1: 133735 Segmentation fault      (core dumped) bazel-out/host/bin/tensorflow/contrib/framework/gen_gen_variable_ops_py_wrappers_cc 0 > bazel-out/local-opt/genfiles/tensorflow/contrib/framework/python/ops/gen_variable_ops.py
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps`
### System information
- System: Red Hat 4.8.5
- Python: 2.7.5
- bazel: 0.5.2
- Tensorflow: r1.2

### Commands:
```
wget https://github.com/bazelbuild/bazel/releases/download/0.5.2/bazel-0.5.2-installer-linux-x86_64.sh
chmod +x bazel-0.5.2-installer-linux-x86_64.sh
sudo sh ./zel-0.5.2-installer-linux-x86_64.sh

git clone https://github.com/tensorflow/tensorflow/
cd tensorflow
git checkout r1.2
./configure
 
Please specify the location of python. [Default is /vir_tensorflow/bin/python]: 
Found possible Python library paths:
  /vir_tensorflow/lib/python2.7/site-packages
Please input the desired Python library path to use.  Default is [/vir_tensorflow/lib/python2.7/site-packages]

Using python library path: /vir_tensorflow/lib/python2.7/site-packages
Do you wish to build TensorFlow with MKL support? [y/N] y
MKL support will be enabled for TensorFlow
Do you wish to download MKL LIB from the web? [Y/n] y
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] 
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Do you wish to build TensorFlow with VERBS support? [y/N] 
No VERBS support will be enabled for TensorFlow
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] 
No CUDA support will be enabled for TensorFlow
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Configuration finished

bazel build --config=opt --config=mkl --copt="-DEIGEN_USE_VML" //tensorflow/tools/pip_package:build_pip_package
```
Are there any mistakes ?

**Comment by asimshankar** [comment]
Could you run with `--verbose_failures`. That flag (mentioned in the error message above) should help narrow down precisely which of the sub-commands initiated by bazel is failing. Something like:

```
bazel build --config=opt --config=mkl --copt="-DEIGEN_USE_VML" --verbose_failures \
   //tensorflow/tools/pip_package:build_pip_package
```

**Comment by lumiaomiao** [comment]
@asimshankar I used the following command you said,
`bazel build --config=opt --config=mkl --copt="-DEIGEN_USE_VML" --verbose_failures \
   //tensorflow/tools/pip_package:build_pip_package`

and I got the following error messages,

/export/lumiao/tensorflow-1.2-mkl/tensorflow/cc/BUILD:326:1: Executing genrule //tensorflow/cc:math_ops_genrule failed: bash failed: error executing command 
  (cd /export/lumiao/home/lumiao/.cache/bazel/_bazel_lumiao/29603fe0fae46f041d7c5d3a0957b1d1/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/lib/python2.7/site-packages \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorflow/cc/ops/math_ops_gen_cc bazel-out/local-opt/genfiles/tensorflow/cc/ops/math_ops.h bazel-out/local-opt/genfiles/tensorflow/cc/ops/math_ops.cc tensorflow/cc/ops/op_gen_overrides.pbtxt 0'): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 11.
/bin/bash: line 1: 27671 Segmentation fault      (core dumped) bazel-out/host/bin/tensorflow/cc/ops/math_ops_gen_cc bazel-out/local-opt/genfiles/tensorflow/cc/ops/math_ops.h bazel-out/local-opt/genfiles/tensorflow/cc/ops/math_ops.cc tensorflow/cc/ops/op_gen_overrides.pbtxt 0
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by asimshankar** [comment]
It appears that this is failing because the program to generate the header and source files for the math operations is failing. It's hard to say why this is happening, but it appears you're running an old Linux distribution (I believe RedHat 4.8 is from 2009), which may have various shared libraries (such as `libc`) or tools (`gcc` versions) that are not compatible with the source tree.

Perhaps you can debug the failing command:

```
bazel-out/host/bin/tensorflow/cc/ops/math_ops_gen_cc \
  bazel-out/local-opt/genfiles/tensorflow/cc/ops/math_ops.h \
  bazel-out/local-opt/genfiles/tensorflow/cc/ops/math_ops.cc \
  tensorflow/cc/ops/op_gen_overrides.pbtxt 0
```

to figure out what is causing it to segfault. 

Unfortunately, we don't have the bandwidth to debug installation on the Linux distribution you're having trouble with. Officially, only Ubuntu is supported as per https://www.tensorflow.org/install/install_sources and we rely on community support for other distributions.

**Comment by lumiaomiao** [comment]
@asimshankar  Thank you very much， I compiled Tensorflowr1.2 on Ubuntu16.04 successfully.
