### ISSUE TITLE
initial_state in keras rnn

### ISSUE THREAD

**Issue by junja94** [tensorflow/tensorflow#11553]
I'm trying to put different initial hidden state into recurrent layers. I saw many issues about initializing states using keras and most of the solutions were using **layer.reset_state(state)**. But in my application, I have to set stateful = False and I cannot use reset_state.
As it is written in the document, I tried **initial_state** argument in calling layers.

Using the code below, I compared the outputs and the resulting outputs were always the same.
I tried different initializers and different initial states but the both outputs were the same.

**When the stateful is False, is there other possible way to set initial hidden state???**

        for size in dimension[1:]:
            initial_ = tf.ones(shape=[batchnum, size])
            recurrent_layer = GRU(units=size, return_sequences=True, kernel_initializer=one,
                                         recurrent_initializer=one)
            recurrent_layertest = GRU(units=size, return_sequences=True, kernel_initializer=one,
                                         recurrent_initializer=one)

            x = recurrent_layer(inputs=x)
            xtest = recurrent_layertest(inputs=xtest, **initial_state = initial_**)

**Comment by junja94** [comment]
I think the call() function is ignoring the initial_state.

**Comment by drpngx** [comment]
Yes, the first element in `input` is taken as the initial state in [`call`](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/keras/python/keras/layers/recurrent.py#L327).

**Comment by junja94** [comment]
@junja94
