### ISSUE TITLE
Still seeing 'missing dependency declarations' when building with Bazel 0.1.4/0.1.5

### ISSUE THREAD

**Issue by gevapatz** [tensorflow/tensorflow#1157]
I'm still getting the error from #469, even with the fix in #788.

Debian, gcc 4.9.2, bazel 0.1.5 (tried 0.1.4 as well with the same results).

Command line:

```
bazel build -c opt --config=cuda --verbose_failures --spawn_strategy=standalone  //tensorflow/cc:tutorials_example_trainer
```

Error output:

```
ERROR: /usr/local/src/tensorflow/tensorflow/core/BUILD:334:1: undeclared inclusion(s) in rule '//tensorflow/core:gpu_kernels':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/cwise_op_gpu_cos.cu.cc':
  '/usr/local/cuda/include/vector_types.h'
  '/usr/local/cuda/include/math_constants.h'
  '/usr/local/cuda/include/cuda_runtime.h'
  '/usr/local/cuda/include/curand_kernel.h'
  '/usr/local/cuda/include/curand.h'
  '/usr/local/cuda/include/curand_discrete.h'
  '/usr/local/cuda/include/curand_precalc.h'
  '/usr/local/cuda/include/curand_mrg32k3a.h'
  '/usr/local/cuda/include/curand_mtgp32_kernel.h'
  '/usr/local/cuda/include/cuda.h'
  '/usr/local/cuda/include/curand_mtgp32.h'
  '/usr/local/cuda/include/curand_philox4x32_x.h'
  '/usr/local/cuda/include/curand_globals.h'
  '/usr/local/cuda/include/curand_uniform.h'
  '/usr/local/cuda/include/curand_normal.h'
  '/usr/local/cuda/include/curand_normal_static.h'
  '/usr/local/cuda/include/curand_lognormal.h'
  '/usr/local/cuda/include/curand_poisson.h'
  '/usr/local/cuda/include/curand_discrete2.h'.
Target //tensorflow/cc:tutorials_example_trainer failed to build
```

**Comment by vrv** [comment]
@damienmg, any more ideas? :)

**Comment by emogenet** [comment]
I am seeing the exact same problem.

OS:

```
mgix@alphanor:~/tensorflow$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
```

Bazel is built from github head:

```
mgix@alphanor:~/tensorflow$ bazel version
Build label: head (@12ecc0b)
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Mar 5 01:35:18 2016 (1457141718)
Build timestamp: 1457141718
Build timestamp as int: 1457141718
```

gcc is gcc 4.9.3
```
mgix@alphanor:~/tensorflow$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc-4.9
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9.3-5ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.3 (Ubuntu 4.9.3-5ubuntu1) 
```

Building tensorflow from head with GPU on:
```
mgix@alphanor:~/tensorflow$ pwd; git log | head -1
/home/mgix/tensorflow
commit 6eb0f2ee3db263791f292f6147a2cda600dd6a1f
```

Trying to build with --spawn_strategy=standalone
```
mgix@alphanor:~/tensorflow$ bazel build --spawn_strategy=standalone  --verbose_failures -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
INFO: Found 1 target...
INFO: From Compiling tensorflow/core/kernels/cwise_op_minimum.cc:
In file included from ./tensorflow/core/platform/default/logging.h:23:0,
                 from ./tensorflow/core/platform/logging.h:24,
                 from ./tensorflow/core/lib/core/status.h:24,
                 from ./tensorflow/core/framework/op_def_builder.h:25,
                 from ./tensorflow/core/framework/op.h:23,
                 from ./tensorflow/core/kernels/cwise_ops_common.h:25,
                 from tensorflow/core/kernels/cwise_op_minimum.cc:16:
./tensorflow/core/platform/default/logging.h: In instantiation of 'std::__cxx11::string* tensorflow::internal::Check_EQImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int; std::__cxx11::string = std::__cxx11::basic_string<char>]':
./tensorflow/core/kernels/cwise_ops_common.h:64:5:   required from 'static Eigen::array<long int, NDIMS> tensorflow::BinaryOpShared::ToIndexArray(const Vec&) [with int NDIMS = 2; tensorflow::BCast::Vec = tensorflow::gtl::InlinedVector<long long int, 4>]'
./tensorflow/core/kernels/cwise_ops_common.h:122:26:   required from 'void tensorflow::BinaryOp<Device, Functor>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::GpuDevice; Functor = tensorflow::functor::minimum<long long int>]'
tensorflow/core/kernels/cwise_op_minimum.cc:36:1:   required from here
./tensorflow/core/platform/default/logging.h:194:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                         == )  // Compilation error with CHECK_EQ(NULL, x)?
                         ^
./tensorflow/core/platform/macros.h:54:28: note: in definition of macro 'TF_PREDICT_TRUE'
 #define TF_PREDICT_TRUE(x) x
                            ^
./tensorflow/core/platform/default/logging.h:193:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_EQ,
 ^
ERROR: /data/home/mgix/tensorflow/tensorflow/core/kernels/BUILD:205:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:gather_op_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/gather_op_gpu.cu.cc':
  '/usr/local/cuda/targets/x86_64-linux/include/vector_types.h'
  '/usr/local/cuda/targets/x86_64-linux/include/cuda_fp16.h'
  '/usr/local/cuda/targets/x86_64-linux/include/math_constants.h'
  '/usr/local/cuda/targets/x86_64-linux/include/cuda_runtime.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_kernel.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_discrete.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_precalc.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_mrg32k3a.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_mtgp32_kernel.h'
  '/usr/local/cuda/targets/x86_64-linux/include/cuda.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_mtgp32.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_philox4x32_x.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_globals.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_uniform.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_normal.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_normal_static.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_lognormal.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_poisson.h'
  '/usr/local/cuda/targets/x86_64-linux/include/curand_discrete2.h'.
nvcc-real warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc-real warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
Target //tensorflow/cc:tutorials_example_trainer failed to build
INFO: Elapsed time: 18.195s, Critical Path: 18.09s
```

**Comment by emogenet** [comment]
Adding

`cxx_builtin_include_directory: "/usr/local/cuda/targets/x86_64-linux/include"`

to file `tensorflow/third_party/gpus/crosstool/CROSSTOOL`

seem to be a workaround.

**Comment by damienmg** [comment]
Oh gosh, sorry @vrv, I totally missed that message.

Yes missing cxx_builtin_include_directory is the usual suspect when you have such message.

Note that I am rolling out a mechanism in Bazel to auto-configure those include dir (see https://groups.google.com/forum/#!msg/bazel-discuss/MSunz2ZUOq0/U5tE7uQLJQAJ), using it in TF would significantly reduce those bug reports

**Comment by kirilg** [comment]
@damienmg I'm having the same issue with TensorFlow Serving compiled with cuda. Adding `cxx_builtin_include_directory: "/usr/local/cuda-7.0/include"` to the CROSSTOOL file works, but changing it to `"/usr/local/cuda/include` (symlink) fails with the same error above (this rule is missing dependency declarations...)
The path that works is user specific, so we can't add it as is.

I tried to auto-configure using the link you provided, and got stuck in other places. The relevant part of the error message including the command it generated is:
`  /usr/bin/gcc -shared -o bazel-out/local-opt/bin/tensorflow_serving/resources/libresource_values.so -no-canonical-prefixes -B/usr/bin -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,rpath,/usr/local/cuda-7.0/lib -L/usr/local/cuda-7.0/lib -Wl,rpath,/usr/local/cuda-7.0/lib64 -L/usr/local/cuda-7.0/lib64 -Wl,--gc-sections -Wl,@bazel-out/local-opt/bin/tensorflow_serving/resources/libresource_values.so-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/bin/ld: cannot find rpath: No such file or directory
/usr/bin/ld: cannot find /usr/local/cuda-7.0/lib: File format not recognized
/usr/bin/ld: cannot find rpath: No such file or directory
/usr/bin/ld: cannot find /usr/local/cuda-7.0/lib64: File format not recognized
collect2: error: ld returned 1 exit status`

note that it's using /usr/bin/gcc but TensorFlow's crosstool config uses clang/bin/crosstool_wrapper_driver_is_not_gcc. I only added
`load("@bazel_tools//tools/cpp:cc_configure.bzl", "cc_configure")
cc_configure()`
and not sure if there's a way to configure the tool_path for gcc since cc_configure() is the only public function and it takes no parameters.

**Comment by damienmg** [comment]
cc_configure is for general gcc (it is rolled-out by default now on Bazel @HEAD by the way).

There was an error in cc_configure in 0.2.1 that prevents rpath from working correctly and you are hitting it (it should be `-Wl,-rpath,...` not `-Wl,rpath,...`)

cc_configure.bzl probably needs to be adapted for the cuda crosstool for TensorFlow, will be happy to provide guidance on doing it.

**Comment by girving** [comment]
@martinwicke You could do further triage on this?  Taking advantage of @damienmg's new feature seems worth doing if it reduces further bug reports.

**Comment by martinwicke** [comment]
Do I understand correcly that this issue will be resolved once current bazel head lands in a release?

**Comment by damienmg** [comment]
Sorry I made myself unclear. Bazel @HEAD (since 0.2.2) as made C++ auto-configuration the default. I am proposing to adapt the script we use for CUDA configuration. Which is what @davidzchen has started to do IIUC. I also sent a PR for doing the same for python.

Doing that would:
  1. Remove issues with CUDA configuration.
  2. Remove needs for ./configure (which can be kept for user interface), helping people depends on TensorFlow without needing for calling the ./configure script.

Internal reference: b/29006900

**Comment by davidzchen** [comment]
I have started working on the CUDA autoconf. With this and Python detection, I think the only thing left that the configure script manages is whether to build with GCP support.

**Comment by martinwicke** [comment]
@davidzchen @damienmg that is exciting.

**Comment by davidzchen** [comment]
Here is the tracking bug for cuda autoconf: #2873

**Comment by martinwicke** [comment]
Will close this bug in favor of #2873.

**Comment by ZiangYan** [comment]
@kirilg You save my day. In my case, add `cxx_builtin_include_directory: "/usr/local/cuda-7.5/include"` works, but `cxx_builtin_include_directory: "/usr/local/cuda/include"` doesn't.

**Comment by slowbull** [comment]
@ZiangYan  cxx_builtin_include_directory: "/usr/local/cuda-7.5/include" works for me too!

**Comment by dbikard** [comment]
I'm having similar issues. However adding `cxx_builtin_include_directory: "/usr/local/cuda-7.5/include" ` to CROSSTOOL gave me the following error:

```
 ERROR: java.io.IOException: Could not read the crosstool configuration file 'CROSSTOOL file /home/david/tensorflow/third_party/gpus/crosstool/CROSSTOOL', because of a parser error (4:1: Message type "com.google.devtools.build.lib.view.config.crosstool.CrosstoolRelease" has no field named "cxx_builtin_include_directory".).
```
Any suggestion?

**Comment by davidzchen** [comment]
@ZiangYan We are actively working on improving Bazel's autoconfiguration support. We appreciate your patience.

@lberki, @ulfjack - it seems that the C++ toolchain configuration does not follow symlinks for builtin include directories. I ran into this issue as well while working on #2873. Even though `/usr/local/cuda` is a symlink to `/usr/local/cuda-7.5`, as other users have pointed out, `cxx_builtin_include_directory: "/usr/local/cuda/include"` still produces this error while `cxx_builtin_include_directory: "/usr/local/cuda-7.5/include"` does not. Is this a bug?

**Comment by davidzchen** [comment]
@dbikard - You may have added your `cxx_builtin_include_directory:` entry to the wrong part of the config. Can you paste a snippet illustrating where in your CROSSTOOL config you added that entry to?

FYI, the CROSSTOOL config file is in text Protocol Buffer format and is parsed into a `CToolchain` Protocol Buffer message. Here is the message definition, which serves as the schema for the CROSSTOOL config file, and here is where the `cxx_builtin_include_directory` field is in the message: https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/crosstool_config.proto#L370

**Comment by dbikard** [comment]
@davidzchen Thanks, that was indeed my mistake. I realized that shortly after posting here, so I deleted my message. I have now managed to build tensorflow. Thanks for your help!

**Comment by landinggao** [comment]
I have same problem when building r0.9 without cudn, always such errors:
ERROR: /home/hadoop/.cache/bazel/_bazel_hadoop/688bf433e3d98b943fba735d08e17b8c/external/jpeg_archive/BUILD:77:1: undeclared inclusion(s) in rule '@jpeg_archive//:jpeg':
this rule is missing dependency declarations for the following files included by 'external/jpeg_archive/jpeg-9a/jdatasrc.c':
  'bazel-out/host/genfiles/external/jpeg_archive/jconfig.h'.

the error file is changed if I run bazel build again.

there is no problem when I build TF master version 0.11.

**Comment by zyavrik** [comment]
Fixed the same error on my system with the following commands:

```
export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export CUDA_HOME=/usr/local/cuda
```

**Comment by andrewor14** [comment]
Hey guys I had the same problem and fixed it by:
1. Uninstalling and re-installing gcc and g++
2. Removing ~/.cache/bazel
I also restarted the machine but I think (2) was the one that really fixed it for me.

**Comment by RGTHENO** [comment]
> Adding
> 
> `cxx_builtin_include_directory: "/usr/local/cuda/targets/x86_64-linux/include"`
> 
> to file `tensorflow/third_party/gpus/crosstool/CROSSTOOL`
> 
> seem to be a workaround.

Hi there, 
Inside crosstool folder, I dont have CROSSTOOL file, so in which file I have to add the code line that you propose to fix this issue.
THanks in advance!

**Comment by RGTHENO** [comment]
> Hey guys I had the same problem and fixed it by:
> 
> 1. Uninstalling and re-installing gcc and g++
> 2. Removing ~/.cache/bazel
> 
> I also restarted the machine but I think (2) was the one that really fixed it for me.

step (2) Removing ~/.cache/bazel did work for me!.
Many thanks
