### ISSUE TITLE
How to install tensorflow c#

### ISSUE THREAD

**Issue by delphiy** [tensorflow/tensorflow#11572]
Hi,
I am trying to build email spam filtering .I have already done when email has text only but the problem when deal with images

Any help how to install tensorflow and deal with images. 

Thanks

**Comment by gunan** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
