### ISSUE TITLE
Unclear about how to make BeamSearchDecoder work

### ISSUE THREAD

**Issue by zhedongzheng** [tensorflow/tensorflow#11598]
Hello, I am trying to understand the way to use BeamSearchDecoder in a seq2seq model by following the tutorial of [nmt](https://github.com/tensorflow/nmt#beam-search). However, both the documentation and error message seem to be very unclear for starters. I have wrote the minimal code for a common seq2seq purpose with beam search:
``` python
import tensorflow as tf
from tensorflow.python.layers.core import Dense

# INPUTS
X = tf.placeholder(tf.int32, [None, None])
Y = tf.placeholder(tf.int32, [None, None])
X_seq_len = tf.placeholder(tf.int32, [None])
Y_seq_len = tf.placeholder(tf.int32, [None])

# ENCODER         
encoder_out, encoder_state = tf.nn.dynamic_rnn(
    cell = tf.nn.rnn_cell.BasicLSTMCell(128), 
    inputs = tf.contrib.layers.embed_sequence(X, 10000, 128),
    sequence_length = X_seq_len,
    dtype = tf.float32)

# DECODER COMPONENTS
Y_vocab_size = 10000
decoder_embedding = tf.Variable(tf.random_uniform([Y_vocab_size, 128], -1.0, 1.0))
projection_layer = Dense(Y_vocab_size)
decoder_cell = tf.nn.rnn_cell.BasicLSTMCell(128)

# TRAINING DECODER
training_helper = tf.contrib.seq2seq.TrainingHelper(
    inputs = tf.nn.embedding_lookup(decoder_embedding, Y),
    sequence_length = Y_seq_len,
    time_major = False)
training_decoder = tf.contrib.seq2seq.BasicDecoder(
    cell = decoder_cell,
    helper = training_helper,
    initial_state = encoder_state,
    output_layer = projection_layer)
training_decoder_output, _, _ = tf.contrib.seq2seq.dynamic_decode(
    decoder = training_decoder,
    impute_finished = True,
    maximum_iterations = tf.reduce_max(Y_seq_len))
training_logits = training_decoder_output.rnn_output

# PREDICTING_DECODER
predicting_decoder = tf.contrib.seq2seq.BeamSearchDecoder(
    cell = decoder_cell,
    embedding = decoder_embedding,
    start_tokens = tf.tile(tf.constant([1], dtype=tf.int32), [128]),
    end_token = 2,
    initial_state = tf.contrib.seq2seq.tile_batch(encoder_state, multiplier=10),
    beam_width = 10,
    output_layer = projection_layer,
    length_penalty_weight = 0.0)
predicting_decoder_output, _, _ = tf.contrib.seq2seq.dynamic_decode(
    decoder = predicting_decoder,
    impute_finished = True,
    maximum_iterations = 2 * tf.reduce_max(Y_seq_len))
predicting_logits = predicting_decoder_output.sample_id

# LOSS
masks = tf.sequence_mask(Y_seq_len, tf.reduce_max(Y_seq_len), dtype=tf.float32)
loss = tf.contrib.seq2seq.sequence_loss(logits = training_logits, targets = Y, weights = masks)

# BACKWARD
params = tf.trainable_variables()
gradients = tf.gradients(loss, params)
clipped_gradients, _ = tf.clip_by_global_norm(gradients, 5.0)
train_op = tf.train.AdamOptimizer().apply_gradients(zip(clipped_gradients, params))
```
The error occurs at BeamSearchDecoder:
```
Traceback (most recent call last):
  File "test.py", line 48, in <module>
    length_penalty_weight = 0.0)
  File "/Users/l2015005/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py", line 175, in __init__
    initial_state, self._cell.state_size)
  File "/Users/l2015005/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/nest.py", line 319, in map_structure
    assert_same_structure(structure[0], other, check_types=check_types)
  File "/Users/l2015005/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/nest.py", line 146, in assert_same_structure
    % (nest1, nest2))
ValueError: The two structures don't have the same number of elements. First structure: Tensor("tile_batch/Reshape:0", shape=(20, ?, 128), dtype=float32), second structure: LSTMStateTuple(c=128, h=128).
```

**Comment by zhedongzheng** [comment]
@ebrevdo do you mind having a look? Thanks.

**Comment by zhedongzheng** [comment]
@Songweiping do you have any insight of this?

**Comment by ebrevdo** [comment]
Your initial state should be decoder_cell(...).clone(cell_state=tile_batch(encoder_state, ...))

**Comment by ebrevdo** [comment]
Err decoder_cell.zero_state(...).clone(...)

**Comment by zhedongzheng** [comment]
```
initial_state = decoder_cell.zero_state(128, tf.float32).clone(
        cell_state=tf.contrib.seq2seq.tile_batch(encoder_state, multiplier=10)),
```
@ ebrevdo
if I don't use attention, the error says:
'LSTMStateTuple' object has no attribute 'clone'
is beam search forced to be used with attention?

**Comment by ebrevdo** [comment]
If you don't use attention then you can directly pass the tiled encoder
state as the initial state (assuming your encoder and decoder cells are the
same architecture).

**Comment by zhedongzheng** [comment]
@ebrevdo yes, that's exactly my problem at the first place. i directly pass the tiled encoder state, however the error message says:
```
ValueError: The two structures don't have the same number of elements. First structure: Tensor("tile_batch/Reshape:0", shape=(20, ?, 128), dtype=float32), second structure: LSTMStateTuple(c=128, h=128).
```

**Comment by ebrevdo** [comment]
Ah I see. Let me look more carefully.

**Comment by ebrevdo** [comment]
Hm.  What version of tf are you using?

**Comment by zhedongzheng** [comment]
@ebrevdo latest tf 1.2.1, sorry I should mention this earlier.

**Comment by ebrevdo** [comment]
I'll look more carefully tomorrow.

**Comment by zhedongzheng** [comment]
hi  @ebrevdo  are you still investigating this?

**Comment by JerrikEph** [comment]
Try this:
```
initial_state = tf.nn.rnn_cell.LSTMStateTuple([tf.contrib.seq2seq.tile_batch(o, multiplier=10) for o in encoder_state])
```
Because encoder_state is a LSTMStateTuple, so you can't simply tile a tuple, but tile every element in a tuple, then pack it as LSTMStateTuple.

**Comment by zhedongzheng** [comment]
@JerrikEph After changing code to this:
``` python
    initial_state = tf.nn.rnn_cell.LSTMStateTuple(tf.contrib.seq2seq.tile_batch(encoder_state[0], multiplier=10),
                                                  tf.contrib.seq2seq.tile_batch(encoder_state[1], multiplier=10)),
```
The old problem is solved, however a new error occurs as:
```
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 671, in _
call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "D:\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in rai
se_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes must be equal rank, but are 3 a
nd 2 for 'decoder_1/while/Select_4' (op: 'Select') with input shapes: [128,10], [128,10,128], [128,1
0,128].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 53, in <module>
    maximum_iterations = 2 * tf.reduce_max(Y_seq_len))
  File "D:\Anaconda3\lib\site-packages\tensorflow\contrib\seq2seq\python\ops\decoder.py", line 286,
in dynamic_decode
    swap_memory=swap_memory)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2770, in whi
le_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2599, in Bui
ldLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2549, in _Bu
ildLoop
    body_result = body(*packed_vars_for_body)
  File "D:\Anaconda3\lib\site-packages\tensorflow\contrib\seq2seq\python\ops\decoder.py", line 269,
in body
    _maybe_copy_state, decoder_state, state)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\util\nest.py", line 325, in map_structure
    structure[0], [func(*x) for x in entries])
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\util\nest.py", line 325, in <listcomp>
    structure[0], [func(*x) for x in entries])
  File "D:\Anaconda3\lib\site-packages\tensorflow\contrib\seq2seq\python\ops\decoder.py", line 265,
in _maybe_copy_state
    return new if pass_through else array_ops.where(finished, cur, new)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2328, in where
    return gen_math_ops._select(condition=condition, t=x, e=y, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2145, in _select

    name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in
apply_op
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1873, in set_shapes
_for_outputs
    shapes = shape_func(op)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in call_with_
requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 610, in c
all_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 676, in _
call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shapes must be equal rank, but are 3 and 2 for 'decoder_1/while/Select_4' (op: 'Select')
 with input shapes: [128,10], [128,10,128], [128,10,128].
```
The error seems pretty hard to understand

**Comment by ebrevdo** [comment]
You closed the issue, can you record for posterity how you resolved it?

**Comment by zhedongzheng** [comment]
okay, the key is to:
* tile the encoder state separately
* make sure impute_finished is False
the complete code is:
```
import tensorflow as tf
from tensorflow.python.layers.core import Dense

# INPUTS
X = tf.placeholder(tf.int32, [None, None])
Y = tf.placeholder(tf.int32, [None, None])
X_seq_len = tf.placeholder(tf.int32, [None])
Y_seq_len = tf.placeholder(tf.int32, [None])

# ENCODER         
encoder_out, encoder_state = tf.nn.dynamic_rnn(
    cell = tf.nn.rnn_cell.BasicLSTMCell(128), 
    inputs = tf.contrib.layers.embed_sequence(X, 10000, 128),
    sequence_length = X_seq_len,
    dtype = tf.float32)

# DECODER COMPONENTS
Y_vocab_size = 10000
decoder_embedding = tf.Variable(tf.random_uniform([Y_vocab_size, 128], -1.0, 1.0))
projection_layer = Dense(Y_vocab_size)
decoder_cell = tf.nn.rnn_cell.BasicLSTMCell(128)

# TRAINING DECODER
training_helper = tf.contrib.seq2seq.TrainingHelper(
    inputs = tf.nn.embedding_lookup(decoder_embedding, Y),
    sequence_length = Y_seq_len,
    time_major = False)
training_decoder = tf.contrib.seq2seq.BasicDecoder(
    cell = decoder_cell,
    helper = training_helper,
    initial_state = encoder_state,
    output_layer = projection_layer)
training_decoder_output, _, _ = tf.contrib.seq2seq.dynamic_decode(
    decoder = training_decoder,
    impute_finished = True,
    maximum_iterations = tf.reduce_max(Y_seq_len))
training_logits = training_decoder_output.rnn_output

# PREDICTING_DECODER
predicting_decoder = tf.contrib.seq2seq.BeamSearchDecoder(
    cell = decoder_cell,
    embedding = decoder_embedding,
    start_tokens = tf.tile(tf.constant([1], dtype=tf.int32), [128]),
    end_token = 2,
    initial_state = tf.nn.rnn_cell.LSTMStateTuple(
        tf.contrib.seq2seq.tile_batch(encoder_state[0], multiplier=10),
        tf.contrib.seq2seq.tile_batch(encoder_state[1], multiplier=10)),,
    beam_width = 10,
    output_layer = projection_layer,
    length_penalty_weight = 0.0)
predicting_decoder_output, _, _ = tf.contrib.seq2seq.dynamic_decode(
    decoder = predicting_decoder,
    impute_finished = False,
    maximum_iterations = 2 * tf.reduce_max(Y_seq_len))
predicting_logits = predicting_decoder_output.sample_id

# LOSS
masks = tf.sequence_mask(Y_seq_len, tf.reduce_max(Y_seq_len), dtype=tf.float32)
loss = tf.contrib.seq2seq.sequence_loss(logits = training_logits, targets = Y, weights = masks)

# BACKWARD
params = tf.trainable_variables()
gradients = tf.gradients(loss, params)
clipped_gradients, _ = tf.clip_by_global_norm(gradients, 5.0)
train_op = tf.train.AdamOptimizer().apply_gradients(zip(clipped_gradients, params))
```

**Comment by lecun** [comment]
> zhedongzheng commented on Jul 30 • edited
> okay, the key is to:
> 
> tile the encoder state separately for LSTMStateTuple
> make sure impute_finished is False
> the complete code is:
@zhedongzheng 
Hi, Here why  should we make sure impute_finished is False.? I encounter an Error when I use impute_finished ＝True with BeamSearchDecoder using dynamic_decode . False , will be right without bug .The error points the shape of finished corresponding the  line 265 in https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/contrib/seq2seq/python/ops/decoder.py
my verison of tensorflow is r1.3.
log:Err : Shapes must be equal rank, but are 3 and 2. detail here:
File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 286, in dynamic_decode
    swap_memory=swap_memory)
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2775, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2604, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2554, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 269, in body
    _maybe_copy_state, decoder_state, state)
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/python/util/nest.py", line 379, in map_structure
    structure[0], [func(*x) for x in entries])
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 265, in _maybe_copy_state
    return new if pass_through else array_ops.where(finished, cur, new)
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2367, in where
    return gen_math_ops._select(condition=condition, t=x, e=y, name=name)
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2255, in _select
    name=name)
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2632, in create_op
    set_shapes_for_outputs(ret)
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1911, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1861, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 595, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/aisp/virtualenv/tensflow/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 659, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)

**Comment by zhedongzheng** [comment]
@lecun hi, this is related to the internal implementation of beam search decoder. Currently, impute_finished must be turned off when beam search decoding is performed. I think the TF team will make this right in next versions (1.4 or 1.5).

**Comment by ebrevdo** [comment]
Sounds like there's a bug between using impute_finished and the beam search
decoder.  We'll take a look next week.

**Comment by lecun** [comment]
@zhedongzheng @ebrevdo  Thanks very much.

**Comment by georgesterpu** [comment]
Hi Eugene ( @ebrevdo ), is there any update on inpute_finished=True in dynamic_decode with a BeamSearchDecoder ? 

I still have this problem on tf1.4 and cannot tell how correct it is to have it on False, judging from the docstring. It says that the gradient back-propagation would be wrong for a padded batch, but we cannot use the BeamSearchDecoder in training anyway.

**Comment by ebrevdo** [comment]
You should be able to use `impute_finished=False` and then mask the outputs with `tf.sequence_mask` using the final sequence lengths returned by the decoder.  Does that solve your problem?

**Comment by georgesterpu** [comment]
Sorry for missing this, @ebrevdo.
Yes, as I don't use the decoder states, masking the outputs would do it.
I am now concerned about `impute_finished` and `dynamic_decode` during training. 

```
self._decoder_train_outputs, self._final_states, self._final_seq_lens = seq2seq.dynamic_decode(
            self._decoder_train,
            output_time_major=False,
            impute_finished=True,
            swap_memory=False)
self._train_prediction = tf.argmax(self._decoder_train_outputs.rnn_output, axis=-1, output_type=tf.int32)
```

While checking for some predictions, I could see that sometimes the network predicts the EOS token before the actual EOS in the ground truth. However, decoding does not stop there during training, as `ScheduledEmbeddingTrainingHelper` will keep feeding the entire label stream. This results in a decoded sequence having multiple EOS tokens, and `impute_finished` adds zeros only after the last EOS in the ground truth. This also implies that there is a possibility for an EOS prediction to be sampled for being fed again to the decoder's input, thus adding some noise during training. Is there any way of preventing this behaviour ? It does not seem that `ScheduledEmbeddingTrainingHelper` could swap a sampled EOS token with the true label at the moment, as it does not take the `end_token` argument unlike `GreedyEmbeddingHelper` or `BeamSearchDecoder`.

**Comment by fword** [comment]
hi，@zhedongzheng

你的意思是在tensorflow 1.2.1以及更高的版本中，
initial_state = tf.contrib.seq2seq.tile_batch(encoder_state, multiplier=10)
和
initial_state = tf.nn.rnn_cell.LSTMStateTuple(
        tf.contrib.seq2seq.tile_batch(encoder_state[0], multiplier=10),
        tf.contrib.seq2seq.tile_batch(encoder_state[1], multiplier=10)),,
是一个效果了吗？

**Comment by zhedongzheng** [comment]
@fword 是的，因为tf在1.2.1以后，会自动识别出LSTMStateTuple并组装，不需要自己手动解决了

yes, after TF 1.2.1, The LSTM state tuple will be automatically correctly handled by tile_batch()

**Comment by fword** [comment]
谢谢
thanks

**Comment by weiwancheng** [comment]
@georgesterpu hi, I found the beam search does not stop  when generated EOS tokens. So, it will generate multiple EOS tokens,and beam_size sentences will alike. such as:
beam_size=5,result:
sentence1： 给您带来不好的体验了，小曦也是十分抱歉的 eos unk unk unk unk unk
sentence2： 给您带来不好的体验了，非常抱歉 eos eos eos eos eos eos eos eos eos eos eos
sentence3： 给您带来不好的体验了，非常抱歉 eos eos eos eos eos eos eos eos eos eos unk
sentence4： 给您带来不好的体验了，非常抱歉 eos eos eos eos eos eos eos unk unk unk unk
sentence5： 给您带来不好的体验了，非常抱歉 eos unk unk unk unk unk unk unk unk unk unk
Do you solve this problem?

**Comment by niket1594** [comment]
Input 0 of layer lstm_cell_3 is incompatible with the layer: expected ndim=2, found ndim=3. Full shape received: [512, None, 256]..
i am getting this error when implementing beam search.
