### ISSUE TITLE
Cross compile TensorFlow for armeabi-v7a failed

### ISSUE THREAD

**Issue by ychen404** [tensorflow/tensorflow#11592]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
1.2.1
- **Python version**:
 2.7.12
- **Bazel version (if compiling from source)**:
0.5.2
- **CUDA/cuDNN version**:
n/a
- **GPU model and memory**:
n/a
- **Exact command to reproduce**:
bazel build -c opt tensorflow/core:android_tensorflow_lib --crosstool_top=//external:android/crosstool --cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
I was able to cross-compile TensorFlow to armeabi-v7a using TensorFlow 1.0. But when I used the same command using TensorFlow 1.2.1, the compilation failed. Please find the detailed error message in the Source code/logs section. 

The command I used is as follows:
bazel build -c opt tensorflow/core:android_tensorflow_lib --crosstool_top=//external:android/crosstool --cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

ERROR: /home/yitao/.cache/bazel/_bazel_yitao/c0c4f6e5ab173d18db201c4c55c4dc60/external/protobuf/BUILD:133:1: C++ compilation of rule '@protobuf//:protobuf' failed: false failed: error executing command /bin/false -MD -MF bazel-out/stub_armeabi-v7a-opt/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/stubs/substitute.pic.d ... (remaining 26 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/core:android_tensorflow_lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 42.154s, Critical Path: 6.27s

**Comment by andrewharp** [comment]
@ychen404 Do you have the SDK API/build tools levels specified in WORKSPACE installed? The default changed between 1.0 and 1.2.

**Comment by ychen404** [comment]
@andrewharp Thanks for your reply. It's working now after specifying the proper SDK level.

**Comment by lingbao00** [comment]
I am doing cross compile too now, but i had test many ways ,all failed,i download the tensorflow 1.2 source code and under linux i want to compile .so file for android,canyou help me ,the command of bazel build what

**Comment by ychen404** [comment]
The bazel command to cross-compile is as below: 
bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so \
   --crosstool_top=//external:android/crosstool \
   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
   --cpu=armeabi-v7a

You also need to edit you WORKSPACE file to make sure the paths and versions of SDK and NDK are correct.
