### ISSUE TITLE
//tensorflow/python:nn_test is failing on ppc64le with AssertionError: False is not true 

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#11603]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
     Ubuntu 16.04 (ppc64le)
- **TensorFlow installed from (source or binary)**:
      Installed from source (v1.2.1)
- **TensorFlow version (use command below)**:
      ('v1.2.1-0-gb4957ff', '1.2.1')
- **Python version**: 
     Python 2.7.5
- **Bazel version (if compiling from source)**:
       0.4.5-2017-07-13 (@037b9b9)
- **CUDA/cuDNN version**:
     NA
- **GPU model and memory**:
      NA
- **Exact command to reproduce**:
      bazel test //tensorflow/python:nn_test

### Describe the problem
Here  testNaNs is failing , see relevant code-
https://github.com/tensorflow/tensorflow/blob/v1.2.1/tensorflow/python/ops/nn_test.py#L835-L841

```
def testNaNs(self):
    # Test that relu(nan) = nan for various sizes.
    for i in range(18):
      x = np.zeros(i) + np.nan
      with self.test_session():
        z = nn_ops.relu(constant_op.constant(x)).eval()
        print("\n current i value is ", i)
        print("\n z value is ", z)
        self.assertTrue(np.isnan(z).all())
```
This test is failing ,because nn_ops.relu function returning incorrect results on ppc64le (0 vs expected nan).......(for i = 2 to 18 )

for` i = 0`  :   z value =   []    ............... (ok)
for `i = 1`  :   z value =  [ nan]  ........... (ok)
for `i = 2`  :   z value =  [ 0.  0.]  ...........(not ok on ppc64le, bcz `0. != nan`)

It looks like this is a bug in the nn_ops.relu function for ppc64le, currently I am trying to understand the reason. Please provide comments/suggestions if any. Thanks!
### Source code / logs

```
$ bazel test --test_output=errors //tensorflow/python:nn_test

......................../root/.cache/bazel/_bazel_root/725e77151072daec43bc353cb6fcb26c/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/nn_test.runfiles/org_tensorflow/tensorflow/python/ops/nn_test.py:108: RuntimeWarning: divide by zero encountered in log
  stirling_approx = z * np.log(z) - z + 0.5 * np.log(2. * np.pi * z)
/root/.cache/bazel/_bazel_root/725e77151072daec43bc353cb6fcb26c/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/nn_test.runfiles/org_tensorflow/tensorflow/python/ops/nn_test.py:108: RuntimeWarning: invalid value encountered in multiply
  stirling_approx = z * np.log(z) - z + 0.5 * np.log(2. * np.pi * z)
................F.......
======================================================================
FAIL: testNaNs (__main__.ReluTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/725e77151072daec43bc353cb6fcb26c/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/nn_test.runfiles/org_tensorflow/tensorflow/python/ops/nn_test.py", line 841, in testNaNs
    self.assertTrue(np.isnan(z).all())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 48 tests in 7.253s

FAILED (failures=1)
0.0208333333333
0.00566666666667
0.0075
0.0208333333333
0.00566666666667
0.0075
0.0208333333333
0.00566666666667
0.0075
L2Loss gradient err = 9.6958e-12
L2Normalize gradient err = 4.2424e-08
L2Normalize gradient err = 5.45829e-07
L2Normalize gradient err = 7.61142e-05
================================================================================

```

**Comment by drpngx** [comment]
@npanpaliya any idea?

**Comment by sandipmgiri** [comment]
Tried to run sample code using TF Relu API , but getting same issue -

```
import tensorflow as tf
import numpy as np
sess = tf.Session()
x = np.zeros(2) + np.nan
z = tf.nn.relu(tf.constant(x))
result = sess.run(z)
np.isnan(result).all()           # fails on ppc64le: [0. 0.] vs expected [nan nan]
```
I was debugging this issue and could able to reach at https://github.com/tensorflow/tensorflow/blob/v1.2.1/tensorflow/python/framework/op_def_library.py#L288  

Now trying to understand apply_op function for Relu operation, looks like different graph operations performed here.
Any comments/suggestions on this would help! Thanks.

**Comment by sandipmgiri** [comment]
As per this doc - https://www.tensorflow.org/api_docs/python/tf/nn/relu
Relu function computes rectified linear: `max(features, 0)`, and I tried computing maximum value 

```
x = np.zeros(2) + np.nan   // x = [nan nan]
sess.run(tf.maximum(x, 0))  // fails [0. 0.] VS expected [nan nan]
```

@drpngx , @gunan - any idea ?

**Comment by drpngx** [comment]
Oh, I remember a PR where we changed that behavior to match `numpy`, for GPU and CPU. That is the behavior that we want. Do you want to send a PR?

**Comment by sandipmgiri** [comment]
@drpngx  tf and numpy aren't behaving same
So, do you want to modify this behavior of tf or modify the test to adjust as per current behavior of TF ?

**Comment by drpngx** [comment]
In general we would like for them to behave the same, unless the behavior is undefined.

**Comment by vaibhavsood** [comment]
Hi @drpngx , all

Investigating this further, the relu function from gen_nn_ops calls cwiseMax(..) in eigen here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/relu_op_functor.h#L35

Tried to go down further from here, cwiseMax goes to the eigen source code, under eigen found a issue as below:

**There is a bug filed under Eigen which switches the parameters to pmax etc**

http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1373

The corresponding PR makes changes to Eigen/src/core code files (PacketMath* etc), im not sure if these changes are present under the tensorflow source tree

Should these changes be incorporated into tensorflow sources? (specifically the ppc changes in files AVX/PacketMath.h etc) 

Also the eigen source files in tensorflow look different from the ones in the eigen repository (for eg. tf has file called PacketMathAVX2.h while eigen has AVX/PacketMath.h), if could get some pointers where these changes would need to be made in tensorflow if needed to fix this issue?

I am still learning/understanding this part of the code, any further pointers will help a lot!

Thanks for any help!

**Comment by drpngx** [comment]
Thanks for figuring this out!

@benoitsteiner and @rmlarsen are the experts.

**Comment by vaibhavsood** [comment]
Hi @benoitsteiner , @rmlarsen ,

Wanted to check if can get any inputs on this issue.. thanks!

**Comment by npanpaliya** [comment]
Tried the change done in Eigen's PR in Power specific files Altivec/PacketMath.h. However, just swapping the arguments of max function didn't work on Power.
Then I wrote a small program to see the behavior of vec_max and _mm_max_ps on Power and x86 respectively, which are called in Eigen's max function. And from the output of the program, it seems Power's builtin function for max calculation has a different behavior as compared to x86's intrinsics.
Checked std::max too and it always gives 1st argument on both Power and x86.

Output on Power:
`Output of vecMaxFunc(vector of NaNs, Vector of zeros)
Vec output at location [0] is 0
Vec output at location [1] is 0
Vec output at location [2] is 0
Vec output at location [3] is 0

Output of vecMaxFunc(vector of zeros, Vector of NaNs)
Vec output at location [0] is 0
Vec output at location [1] is 0
Vec output at location [2] is 0
Vec output at location [3] is 0

std::max NaN compared with 0: nan
std::max 0 compared with NaN: 0
`

Output on X86:
`Output of vecMaxFunc(vector of NaNs, Vector of zeros)
Vec output at location [0] is 0
Vec output at location [1] is 0
Vec output at location [2] is 0
Vec output at location [3] is 0

Output of vecMaxFunc(vector of zeros, Vector of NaNs)
Vec output at location [0] is nan
Vec output at location [1] is nan
Vec output at location [2] is nan
Vec output at location [3] is nan

std::max NaN compared with 0: nan
std::max 0 compared with NaN: 0
`
I'm still working on this to see if we can get some work-around or fix from IBM's respective team.

**Comment by npanpaliya** [comment]
I missed attaching my test program earlier.
[testmax.cpp.txt](https://github.com/tensorflow/tensorflow/files/1535017/testmax.cpp.txt)

**Comment by edelsohn** [comment]
max on Power currently uses the vec_max intrinsic, which maps to xsmaxsp instruction.  It appears that TensorFlow and Eigen want the "c" version of the instruction, xsmaxcsp.  There currently is no compiler intrinsic to access that version, but one can use GCC or LLVM inline assembly to generate xsmaxcsp instead of xsmaxsp.

**Comment by edelsohn** [comment]
Note that xsmaxcsp (and xsmaxjsp) are new in Power ISA 3.0 (Power9).

**Comment by npanpaliya** [comment]
@drpngx : We want to understand the impact of this behavior of min/max function in the tensorflow (usage of Relu/Max operator). 
As per [IEEE754 ](https://msdn.microsoft.com/en-us/library/windows/desktop/jj218760(v=vs.85).aspx#alpha_754_Deviations) standard, max(x, Nan) = max(Nan, x) = x. So, it seems Power's behavior is as per IEEE rule.

**Comment by drpngx** [comment]
OK, what would you need to understand?

**Comment by npanpaliya** [comment]
I want to understand the use or area/feature of tensorflow where Relu operator or Max operator is used. And specially this particular test case where these operators may have NaNs and based on the results, something is decided. So, in case we change the behavior of this operator for NaNs, what features would be impacted or where can we see the difference in the TF's functionality.

**Comment by edelsohn** [comment]
How does TensorFlow rely on this specific NaN behavior that apparently is probed in the testsuite? Is this documented in TensorFlow as semantics of its API?

**Comment by sandipmgiri** [comment]
This issue is fixed here - http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1494

Patch - http://eigen.tuxfamily.org/bz_attachmentbase/attachment.cgi?id=831
