### ISSUE TITLE
who can tell me ,where is gru backward code?i want modify it

### ISSUE THREAD

**Issue by guoying1030** [tensorflow/tensorflow#11601]
who can tell me ,where is gru backward code?i want modify it

i want implete https://arxiv.org/pdf/1606.03401.pdf

reduce gru size

**Comment by rryan** [comment]
`tf.contrib.rnn.GRUCell` is implemented from [fine-grained ops](https://github.com/tensorflow/tensorflow/blob/cf7c008ab150ac8e5edb3ed053d38b2919699796/tensorflow/python/ops/rnn_cell_impl.py#L262) that have their own gradients, so there is no "backward" implementation for GRU itself. You can use tf.contrib.rnn.GRUBlockCell, which does have an explicit gradient implementation [here](https://github.com/tensorflow/tensorflow/blob/3737ac321e67410bf061257d5f644eae8abbf79b/tensorflow/contrib/rnn/kernels/gru_ops.h#L122).

**Comment by drpngx** [comment]
Thanks @rryan ! Closing.
