### ISSUE TITLE
[on the way] Reducing the binary size

### ISSUE THREAD

**Issue by jakiechris** [tensorflow/tensorflow#11605]
Hi , all ~
    i am now succeed in using a cross compiled lib project call tensorflow. 
    now i got tensorflow run on ios , android and linux , using one same app code . 
    any one has any questions can ask me for help.

    so my question now is turned to "Reducing the binary size". 
    many posts told that to config  tf_op_files.txt, but my questions are:
    1. need we also config other files such as  tf_pb_text_files.txt ,  proto_text_cc_files.txt  ... for reducing?
    2. is there any other thinking for reducing than configuring the txt files Exhaustive Attackly ?

**Comment by drpngx** [comment]
I'm assuming you're talking about Android?

@andrewharp might know if there's a better procedure than culling ops by hand.

**Comment by andrewharp** [comment]
See [print_selective_registration_header.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/print_selective_registration_header.py) for a tool that will automatically generate a ops_to_register.h header given a GraphDef proto.

You shouldn't need to manipulate any of those other txt files.

**Comment by jakiechris** [comment]
thx for the helps from  drpngx and andrewharp !

my goal is:
 1 to do prediction on ios and android,  using a trained pb file .
 2 using one same c++ code to call tensorflow in ios and android

i tried  print_selective_registration_header.py

#ifndef OPS_TO_REGISTER
#define OPS_TO_REGISTER
constexpr inline bool ShouldRegisterOp(const char op[]) {
  return false
     || (strcmp(op, "ArgMax") == 0)
     || (strcmp(op, "BiasAdd") == 0)
     || (strcmp(op, "Const") == 0)
     || (strcmp(op, "Conv2D") == 0)
     || (strcmp(op, "ExpandDims") == 0)
     || (strcmp(op, "Identity") == 0)
     || (strcmp(op, "MatMul") == 0)
     || (strcmp(op, "MaxPool") == 0)
     || (strcmp(op, "NoOp") == 0)
     || (strcmp(op, "Placeholder") == 0)
     || (strcmp(op, "Relu") == 0)
     || (strcmp(op, "Reshape") == 0)
     || (strcmp(op, "Squeeze") == 0)
     || (strcmp(op, "StridedSlice") == 0)
     || (strcmp(op, "_Recv") == 0)
     || (strcmp(op, "_Send") == 0)
  ;
}
#define SHOULD_REGISTER_OP(op) ShouldRegisterOp(op)


    namespace {
      constexpr const char* skip(const char* x) {
        return (*x) ? (*x == ' ' ? skip(x + 1) : x) : x;
      }

      constexpr bool isequal(const char* x, const char* y) {
        return (*skip(x) && *skip(y))
                   ? (*skip(x) == *skip(y) && isequal(skip(x) + 1, skip(y) + 1))
                   : (!*skip(x) && !*skip(y));
      }

      template<int N>
      struct find_in {
        static constexpr bool f(const char* x, const char* const y[N]) {
          return isequal(x, y[0]) || find_in<N - 1>::f(x, y + 1);
        }
      };

      template<>
      struct find_in<0> {
        static constexpr bool f(const char* x, const char* const y[]) {
          return false;
        }
      };
    }  // end namespace
    constexpr const char* kNecessaryOpKernelClasses[] = {
"ArgMaxOp<CPUDevice, float>",
"BiasOp<CPUDevice, float>",
"ConstantOp",
"Conv2DOp<CPUDevice, float>",
"ExpandDimsOp",
"IdentityOp",
"MatMulOp<CPUDevice, float, false >",
"MaxPoolingOp<CPUDevice, float>",
"NoOp",
"PlaceholderOp",
"ReluOp<CPUDevice, float>",
"ReshapeOp",
"SqueezeOp",
"StridedSliceOp<CPUDevice, float>",
"RecvOp",
"SendOp",
};
#define SHOULD_REGISTER_OP_KERNEL(clz) (find_in<sizeof(kNecessaryOpKernelClasses) / sizeof(*kNecessaryOpKernelClasses)>::f(clz, kNecessaryOpKernelClasses))

#define SHOULD_REGISTER_OP_GRADIENT false
#endif

**Comment by jakiechris** [comment]
print_selective_registration_header.py result:


#ifndef OPS_TO_REGISTER
#define OPS_TO_REGISTER
constexpr inline bool ShouldRegisterOp(const char op[]) {
  return false
     || (strcmp(op, "ArgMax") == 0)
     || (strcmp(op, "BiasAdd") == 0)
     || (strcmp(op, "Const") == 0)
     || (strcmp(op, "Conv2D") == 0)
     || (strcmp(op, "ExpandDims") == 0)
     || (strcmp(op, "Identity") == 0)
     || (strcmp(op, "MatMul") == 0)
     || (strcmp(op, "MaxPool") == 0)
     || (strcmp(op, "NoOp") == 0)
     || (strcmp(op, "Placeholder") == 0)
     || (strcmp(op, "Relu") == 0)
     || (strcmp(op, "Reshape") == 0)
     || (strcmp(op, "Squeeze") == 0)
     || (strcmp(op, "StridedSlice") == 0)
     || (strcmp(op, "_Recv") == 0)
     || (strcmp(op, "_Send") == 0)
  ;
}
#define SHOULD_REGISTER_OP(op) ShouldRegisterOp(op)


    namespace {
      constexpr const char* skip(const char* x) {
        return (*x) ? (*x == ' ' ? skip(x + 1) : x) : x;
      }

      constexpr bool isequal(const char* x, const char* y) {
        return (*skip(x) && *skip(y))
                   ? (*skip(x) == *skip(y) && isequal(skip(x) + 1, skip(y) + 1))
                   : (!*skip(x) && !*skip(y));
      }

      template<int N>
      struct find_in {
        static constexpr bool f(const char* x, const char* const y[N]) {
          return isequal(x, y[0]) || find_in<N - 1>::f(x, y + 1);
        }
      };

      template<>
      struct find_in<0> {
        static constexpr bool f(const char* x, const char* const y[]) {
          return false;
        }
      };
    }  // end namespace
    constexpr const char* kNecessaryOpKernelClasses[] = {
"ArgMaxOp<CPUDevice, float>",
"BiasOp<CPUDevice, float>",
"ConstantOp",
"Conv2DOp<CPUDevice, float>",
"ExpandDimsOp",
"IdentityOp",
"MatMulOp<CPUDevice, float, false >",
"MaxPoolingOp<CPUDevice, float>",
"NoOp",
"PlaceholderOp",
"ReluOp<CPUDevice, float>",
"ReshapeOp",
"SqueezeOp",
"StridedSliceOp<CPUDevice, float>",
"RecvOp",
"SendOp",
};
#define SHOULD_REGISTER_OP_KERNEL(clz) (find_in<sizeof(kNecessaryOpKernelClasses) / sizeof(*kNecessaryOpKernelClasses)>::f(clz, kNecessaryOpKernelClasses))

#define SHOULD_REGISTER_OP_GRADIENT false
#endif

**Comment by jakiechris** [comment]
my  c++ code ：

int MyTensorflow::OfflineTensorFlowIsAf(deque<double> & section)
{
    Session* session;
    GraphDef graph_def;
    SessionOptions opts;
    std::vector<Tensor> outputs;
    std::vector<Tensor> y_outputs;
    int i;
    int sectionLen;

//    QPrint("begin:%u\n", GetSystemTime());
    QPrint("1MyTensorflow::OfflineTensorFlowIsAf:pbPathFile:%s\n", pbPathFile.c_str());
    if (pbPathFile == "")
    {
        QPrint("MyTensorflow::OfflineTensorFlowIsAf:fatal error: pbPathFile is empty\n");
        return 0;
    }

    TF_CHECK_OK(ReadBinaryProto(Env::Default(), pbPathFile, &graph_def));

    TF_CHECK_OK(NewSession(opts, &session));

    TF_CHECK_OK(session->Create(graph_def));

    Tensor x(DT_FLOAT, TensorShape({1, 321}));

    sectionLen = section.size();

    for (i = 0; i < 321; i++)
    {
        if (i < sectionLen)
        {
            x.matrix<float>()(i) = section[i];
        }
        else
        {
            x.matrix<float>()(i) = 0;
        }
    }

    TF_CHECK_OK(session->Run({{"inputx", x}}, {"aFclass"}, {}, &y_outputs)); // Get y_out

    float y_out = y_outputs[0].scalar<int>()(0);

    QPrint("MyTensorflow::OfflineTensorFlowIsAf:y_out:%f,sectionLen:%d\n", y_out, sectionLen);

//    QPrint("end:%u\n", GetSystemTime());

    if (0 == FloatCompares(y_out, 0))
    {
        return 0;
    }
    else
    {
        return 1;
    }
}

**Comment by jakiechris** [comment]
i do reducing on linux , that's means ,  is adjust tf_op_files.txt, then build_all_linux.sh , then try my application code . until one day , there are no runtime erro. 

i tried to cut tf_op_files.txt to only one line left:
tensorflow/core/kernels/ops_util.cc

**Comment by jakiechris** [comment]
and adding these ones:

tensorflow/core/kernels/argmax_op.cc
tensorflow/core/kernels/quantized_bias_add_op.cc
tensorflow/core/kernels/constant_op.cc
tensorflow/core/kernels/deep_conv2d.cc
tensorflow/core/kernels/xsmm_conv2d.cc
tensorflow/core/kernels/identity_op.cc
tensorflow/core/kernels/matmul_op.cc
tensorflow/core/kernels/maxpooling_op.cc
tensorflow/core/kernels/no_op.cc
tensorflow/core/kernels/relu_op.cc
tensorflow/core/kernels/reshape_op.cc
tensorflow/core/kernels/strided_slice_op.cc
tensorflow/core/kernels/sendrecv_ops.cc

according to 
"ArgMaxOp<CPUDevice, float>",
"BiasOp<CPUDevice, float>",
"ConstantOp",
"Conv2DOp<CPUDevice, float>",
"ExpandDimsOp",
"IdentityOp",
"MatMulOp<CPUDevice, float, false >",
"MaxPoolingOp<CPUDevice, float>",
"NoOp",
"PlaceholderOp",
"ReluOp<CPUDevice, float>",
"ReshapeOp",
"SqueezeOp",
"StridedSliceOp<CPUDevice, float>",
"RecvOp",
"SendOp",

**Comment by jakiechris** [comment]
so i did not find cc file in tf_op_files.txt according to : "ExpandDimsOp", "PlaceholderOp"

so which cc files in tf_op_files.txt are according to "ExpandDimsOp", "PlaceholderOp" ?

**Comment by jakiechris** [comment]
now here is my  tf_op_files.txt , and it cannot pass the compilation.

tensorflow/core/kernels/ops_util.cc
tensorflow/core/kernels/argmax_op.cc
tensorflow/core/kernels/quantized_bias_add_op.cc
tensorflow/core/kernels/constant_op.cc
tensorflow/core/kernels/deep_conv2d.cc
tensorflow/core/kernels/xsmm_conv2d.cc
tensorflow/core/kernels/identity_op.cc
tensorflow/core/kernels/matmul_op.cc
tensorflow/core/kernels/maxpooling_op.cc
tensorflow/core/kernels/no_op.cc
tensorflow/core/kernels/relu_op.cc
tensorflow/core/kernels/reshape_op.cc
tensorflow/core/kernels/strided_slice_op.cc
tensorflow/core/kernels/sendrecv_ops.cc

**Comment by jakiechris** [comment]
seems that placeholder is in ：tensorflow/core/ops/array_ops.cc

tensorflow::ops::Placeholder
#include <array_ops.h>

A placeholder op for a value that will be fed into the computation.

**Comment by jakiechris** [comment]
it seems that "ExpandDimsOp", "PlaceholderOp" are all in tensorflow/core/ops/array_ops.cc

tensorflow::ops::ExpandDims
#include <array_ops.h>

Inserts a dimension of 1 into a tensor's shape.

**Comment by jakiechris** [comment]
struggled in getting familiar with tensor core for several nights, i finally found a way to do reducing.

1. use  print_selective_registration_header.py  to find files probably cannot be cut in tf_op_files.txt, 
    just probably , not for sure.

2. cut some of the files in tf_op_files.txt, if come into compile err or runtime err, restore some files.

3. if there is no compile err and runtime err, continue to cut files.


it's foolish, simple,  but works.

**Comment by reedwm** [comment]
I'm not quite sure what you're trying to do, but it looks you succeeded. I'm closing this issue but if you need further help, I recommend StackOverflow.

**Comment by jakiechris** [comment]
@reedwm yes it's solved.

android: 
[tf_op_files.txt](https://github.com/tensorflow/tensorflow/files/1255300/tf_op_files.txt)

ios:
[tf_op_files.txt](https://github.com/tensorflow/tensorflow/files/1255302/tf_op_files.txt)

centos:
[tf_op_files.txt](https://github.com/tensorflow/tensorflow/files/1255303/tf_op_files.txt)

**Comment by NickolasHu** [comment]
The pb generating files consume lots of binary space. for example, 160.1396kb by test_log.pb.o, 144.4404kb by meta_graph.pb.o which may not be used or appropriate on a mobile device. Is there any solution to remove or replace them?

The following file is a size analysis by link map file, sorted by size.
[text_section_size.txt](https://github.com/tensorflow/tensorflow/files/1449828/text_section_size.txt)
