### ISSUE TITLE
Feature request: tensordot GPU kernel

### ISSUE THREAD

**Issue by tklos96** [tensorflow/tensorflow#11619]
Hi,

I have two placeholder tensors with some matching axes that I would like to multiply element-wise and sum across. Implementation with tf.tensordot works perfectly on cpu, but it looks like there is no gpu kernel available for this op. Would it be possible to have one added? Or is there a workaround using simpler operations such as multiply and reduce_sum that are currently gpu-supported?

Specifically I would like to be able to run something equivalent to the following on gpu:
`a=tf.placeholder(shape=[None,16,17,18]) #e.g.`
`b=tf.placeholder(shape=[5,17,18,20]) `
`c=tf.tensordot(a,b,axes=[[2,3],[1,2]])`
`#shape of c: [None,16,5,20]`

When I run c in a session using tf.device('/gpu:0') I get the following error:
`InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'Tensordot/ListDiff': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: Tensordot/ListDiff = ListDiff[T=DT_INT32, out_idx=DT_INT32, _device="/device:GPU:0"](Tensordot/range, Tensordot/add_1)]]`

**Comment by drpngx** [comment]
@aselle wdyt?

**Comment by yaroslavvb** [comment]
@tklos96 what if you use tf.einsum? Both tensordot/einsum reduce to tf.matmul for the actual work

**Comment by tklos96** [comment]
Oooh thanks that could be good. Although I also got it working by stacking some extra dimensions at the end, and then using the broadcasting capability of tf.multiply

**Comment by SmileGoat** [comment]
solution：
  sess_config = tf.ConfigProto(allow_soft_placement=False) 
    sess = tf.Session(config = sess_config)

 // Whether soft placement is allowed. If allow_soft_placement is true,
  // an op will be placed on CPU if
  //   1. there's no GPU implementation for the OP
  // or
  //   2. no GPU devices are known or registered
  // or
  //   3. need to co-locate with reftype input(s) which are from CPU.
  bool allow_soft_placement = 7;
