### ISSUE TITLE
estimators/SVM_test.py included in test suite?

### ISSUE THREAD

**Issue by waltermblair** [tensorflow/tensorflow#11611]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.2 LTS (Xenial Xerus)"
- **TensorFlow installed from (source or binary)**:
Installed from source, master branch
- **TensorFlow version (use command below)**:
>>> print(tensorflow.VERSION)
1.2.1
>>> print(tensorflow.GIT_VERSION)
b'v1.2.0-2149-gf092326'
- **Python version**: 
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
- **Bazel version (if compiling from source)**:
[bazel release 0.5.2]
- **CUDA/cuDNN version**:
n/a
- **GPU model and memory**:
n/a
- **Exact command to reproduce**:
bazel test //tensorflow/python/... --test_verbose_timeout_warnings

### Describe the problem
I am troubleshooting my usage of estimators/SVM (https://stackoverflow.com/questions/45194171/tensorflow-svm-code-update-to-v1-2), and along the way it seems like svm_test.py isn't executed when running the bazel test command above. I'm a tensorflow newb, so it would be super helpful for me to understand what I'm missing here.

### Source code / logs
`[...]
//tensorflow/python:decorator_utils_test                        (cached) PASSED in 1.2s
  WARNING: //tensorflow/python:decorator_utils_test: Test execution time (1.2s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow/python:deprecation_test                            (cached) PASSED in 1.1s
  WARNING: //tensorflow/python:deprecation_test: Test execution time (1.1s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow/python:dequantize_op_test                          (cached) PASSED in 1.1s
//tensorflow/python:device_lib_test                             (cached) PASSED in 1.1s
//tensorflow/python:device_setter_test                          (cached) PASSED in 1.2s
//tensorflow/python/estimator:dnn_linear_combined_test          (cached) PASSED in 19.0s
  Stats over 4 runs: max = 19.0s, min = 11.8s, avg = 15.4s, dev = 2.5s
//tensorflow/python/estimator:dnn_test                          (cached) PASSED in 22.8s
//tensorflow/python/estimator:estimator_test                    (cached) PASSED in 9.5s
//tensorflow/python/estimator:export_output_test                (cached) PASSED in 1.2s
//tensorflow/python/estimator:export_test                       (cached) PASSED in 5.3s
//tensorflow/python/estimator:feeding_functions_test            (cached) PASSED in 1.3s
//tensorflow/python/estimator:feeding_queue_runner_test         (cached) PASSED in 2.5s
//tensorflow/python/estimator:head_test                         (cached) PASSED in 7.2s
//tensorflow/python/estimator:linear_test                       (cached) PASSED in 35.3s
//tensorflow/python/estimator:model_fn_test                     (cached) PASSED in 1.2s
//tensorflow/python/estimator:numpy_io_test                     (cached) PASSED in 1.3s
//tensorflow/python/estimator:optimizers_test                   (cached) PASSED in 1.0s
//tensorflow/python/estimator:pandas_io_test                    (cached) PASSED in 1.5s
//tensorflow/python/estimator:parsing_utils_test                (cached) PASSED in 1.5s
//tensorflow/python/estimator:run_config_test                   (cached) PASSED in 1.2s
//tensorflow/python/estimator:util_test                         (cached) PASSED in 1.0s
  WARNING: //tensorflow/python/estimator:util_test: Test execution time (1.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow/python:events_writer_test                          (cached) PASSED in 0.9s
//tensorflow/python/feature_column:feature_column_test          (cached) PASSED in 5.2s
  WARNING: //tensorflow/python/feature_column:feature_column_test: Test execution time (5.2s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow/python:file_io_test                                (cached) PASSED in 1.9s
[...]
`

**Comment by drpngx** [comment]
You can test it by running: 
```
bazel test tensorflow/contrib/learn:svm_test
```
which executes [`svm_test.py`](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/svm_test.py#L1).
