### ISSUE TITLE
Unable to optimise the graph

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#11618]
I have frozen the tensorflow graph and I have noticed that the using the graph in realtime for prediction is too slow. so I would like to do graph optimization.

Within my project file, I have got a folder called model which contains the model file (pb file).

Now I tried running the following command inside the model dir
```
 bazel build tensorflow/python/tools:strip_unused
```
But it is firing the following error,

>  bazel build tensorflow/python/tools:strip_unused
> ERROR: no such package 'tensorflow/python/tools': BUILD file not found on package path.
> 
>

**Comment by shreyneil** [comment]
The error is not related to your project file used for optimisation, it is related to the build file in the directory,please verify the path of the build file and get back.

**Comment by Zumbalamambo** [comment]
where should I put my model file for optimizing it? How the directory structure has to be?

**Comment by shreyneil** [comment]
Your model file should be inside the package path (tensorflow/python/tools) provided by you.The build file should also be in the same location.Please try to verify and get back as the above is thrown due to some glitch in the location of the files.

**Comment by Zumbalamambo** [comment]
Should I download [tensorflow](https://github.com/tensorflow/tensorflow) and put the model file in tensorflow/python/tools?
May I know what do you mean by build file?

**Comment by shreyneil** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/BUILD
The above build file should pe present in the package path and  your model too.
Yes all of these should be present inside tensorflow.
Please verify and get back.

**Comment by Zumbalamambo** [comment]
By `package path` , do you mean the path where tensorflow is installed?

**Comment by shreyneil** [comment]
Yes insde the tensorflow folder.
tensorflow/python/tools

**Comment by Zumbalamambo** [comment]
I have installed it in anaconda. May I know where it is in my mac?

**Comment by Zumbalamambo** [comment]
Okay i did so. I got the following errors,

	```
fail("%sPython Configuration Error:%s...))
Python Configuration Error: 'PYTHON_BIN_PATH' environment variable is not set
 and referenced by '//third_party/py/numpy:headers'.
ERROR: Analysis of target '//tensorflow/python/tools:strip_unused' failed; build aborted.
```

**Comment by shreyneil** [comment]
Try this:
https://github.com/tensorflow/tensorflow/issues/9436

**Comment by shreyneil** [comment]
This is a link error probably, this might help:
https://github.com/tensorflow/tensorflow/issues/4458

**Comment by Zumbalamambo** [comment]
thank you... still the same error...any other go?

**Comment by shreyneil** [comment]
Can try to run configure,
please follow this and links available online on how to run configure:
https://github.com/tensorflow/tensorflow/issues/4279

**Comment by asimshankar** [comment]
It seems you're building from within your model directory as opposed to building in the TensorFlow source directory.

Alternatively, if you want to avoid building TensorFlow from source, you could use the library function directly using something like:

```python
from tensorflow.python.tools.strip_unused import strip_unused_lib

help(strip_unused_lib.strip_unused_from_files)
```

Which is [what is being invoked by the tool](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/python/tools/strip_unused.py#L55)

Since this issue doesn't correspond to a bug, I'm going to close it. If you need more help, I'd recommend asking on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
