### ISSUE TITLE
Trouble importing tensorflow after installing with virtualenv

### ISSUE THREAD

**Issue by emersoncloud** [tensorflow/tensorflow#1161]
### Environment info
Fedora 19
Python2.7.8
pip 8.0.2

### Steps to reproduce
1. I installed tensorflow from the Download and Setup page using virtualenv. 
2. When I typed "import tensorflow as tf" I got the following error:

">>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/emerson/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/emerson/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 69, in <module>
    from tensorflow.python.training import training as train
  File "/home/emerson/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/training.py", line 149, in <module>
    from tensorflow.python.training.saver import generate_checkpoint_state_proto
  File "/home/emerson/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 29, in <module>
    from google.protobuf.any_pb2 import Any
ImportError: No module named any_pb2"

I have searched for this error and have not seen a clear solution. I am new with linux and tensorflow. I think I might need to set the PYTHONPATH or get out of the working directory that contains tensorflow. However I am not sure how to do either of those things. 

Thanks

**Comment by kmader** [comment]
What was the solution to the problem? I didn't get it with 0.5 but now get it with 0.7 using both the official version or the anaconda repository verisons

**Comment by emersoncloud** [comment]
I never found a solution to virtualenv. I assume it had something to do with the issue I had when I installed normally without Virtualenv. 

After the Virtualenv problems I went back to trying to install normally and my python wouldn't recognize TensorFlow to import.  I had to uninstall protobuf before I installed TesnorFlow because it needed a specific protobuf version for TensorFlow to work.

**Comment by ankitgyawali** [comment]
Im also having trouble importing tensorflow via ipython notebook while i can import the module from shell on ubuntu 14.04. I am using anoconda rep to install tensorflow. Is there a workaround to this so that i can import tensorflow on my notebook?

```
 27 import six
     28 
---> 29 from google.protobuf.any_pb2 import Any
     30 from google.protobuf import text_format
     31 

ImportError: No module named any_pb2
```

**Comment by julie1** [comment]
I had the same problem and tried all sorts of solutions which didn't work.  After upgrading my 
virtualenv: sudo pip install --upgrade virtualenv
It now works.

**Comment by ankitgyawali** [comment]
For anyone else who is running into the same issue, I was also having similar problems when trying to import tensorflow on notebook via jupyter. The modules were installed using conda. After spending two days on it without any success (kept getting the same, no module any_pb2/contrib), it was obvious it was a notebook problem and not tensorflow related since I could import tensorflow from python shell. So I decided to switch back to vanilla python and installed everything manually (tensorflow via pip & got rid of jupyter & installed ipython instead) and now I am able to import tensorflow from my ipython notebook.

**Comment by ymshao** [comment]
@ankitgyawali  
Hi there,
Just for your information.
I have the same problem as your description. But I solved it by following this post and did not reinstall anything.http://stackoverflow.com/a/37081342/4837894
