### ISSUE TITLE
missing line of code in get_started tutorial on website

### ISSUE THREAD

**Issue by JasperDeKort** [tensorflow/tensorflow#11629]
as mentioned by an issue closed 19 days ago [https://github.com/tensorflow/tensorflow/issues/11042](https://github.com/tensorflow/tensorflow/issues/11042) there is a line missing in the tutorial code at [https://www.tensorflow.org/get_started/get_started#a_custom_model](https://www.tensorflow.org/get_started/get_started#a_custom_model).
this earlier issue was closed, but on the current version of the site that i see, the issue still persists.

the missing line is:
 `eval_input_fn = tf.contrib.learn.io.numpy_input_fn({"x": x_eval}, y_eval,4, num_epochs=1000)`
 which should appear after: 
`input_fn = tf.contrib.learn.io.numpy_input_fn({"x": x_train}, y_train, 4, num_epochs=1000)`

please note that these same lines appear in the code above the mentioned block in the "basic usage" section.

also, i hope opening a new issue is the correct action in this case. if i should have done something else, please let me know

**Comment by drpngx** [comment]
@MarkDaoust do you know where it's at?

**Comment by shreyneil** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/get_started/get_started.md
Sir the custom model has been updated but is not being reflected on the website.
Please look through this.

**Comment by MarkDaoust** [comment]
Thanks for tracking that down shreyneil@. 

The "root" section of the website is synced to releases, but this fix is already visible in the [tf 1.3 docs](https://www.tensorflow.org/versions/r1.3/get_started/get_started).

This these docs will become "root" when 1.3 is released.
