### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [tensorflow/tensorflow#11620]
Would you like to [wrap any pointer data members](https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/core/lib/io/recordio_test.cc#L105 "Update candidate: RecordioTest class") with the template class “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for usage of smart pointers")”?

**Comment by asimshankar** [comment]
Smart pointers are used in various parts of the TensorFlow codebase ([e.g. `unique_ptr`](https://github.com/tensorflow/tensorflow/search?utf8=%E2%9C%93&q=std%3A%3Aunique_ptr&type=)), albeit not in every place.

We encourage the use of such pointers where it makes sense - whether in new code or when making changes to existing code. I do not think, however, that there is a particularly pressing need to comb through the whole code base to switch to smart pointers everywhere.

If you have a particular scenario that leads to unsafe pointer dereferences, please feel free to file a specific issue or send a pull request. Thanks very much

**Comment by elfring** [comment]
>I do not think, however, that there is a particularly pressing need to comb through the whole code base to switch to smart pointers everywhere.

* I would prefer a more consistent and safer software implementation.
* Further usage of smart pointers could also [reduce unnecessary null pointer checks a bit more](https://github.com/tensorflow/tensorflow/blob/fe589d9e7caea582beed160ad47e55f537a8403e/tensorflow/core/common_runtime/sycl/sycl_allocator.cc#L22 "Update candidate: Destructor for SYCLAllocator"), couldn't it?
