### ISSUE TITLE
when connect mnist,download mnist data,show network connection error.

### ISSUE THREAD

**Issue by jxua** [tensorflow/tensorflow#11633]
![image](https://user-images.githubusercontent.com/22673941/28404110-88b436e0-6d5a-11e7-9344-596a22f5d64b.png)
I know if the error show ,just our company can not connect to mnist, can i manual download mnist data, and use it? how can i do this?

**Comment by jhole89** [comment]
Your companies proxy is probably getting in the way. Try setting HTTP_PROXY and HTTPS_PROXY, either in your IDE or Global settings. For windows this is: 
System Properties-> Advanced -> Environment Variables -> System variables -> New System Variable.  You'll need to get the address and port from your IT team.
