### ISSUE TITLE
when i train a GAN model AdamOptimizer get ValueError 

### ISSUE THREAD

**Issue by liguanlin** [tensorflow/tensorflow#11637]
with tf.variable_scope(tf.get_variable_scope(),reuse=None):
        d_optim = tf.train.AdamOptimizer(learning_rate=learning_rate, beta1=0.5).minimize(d_loss, var_list=d_vars, global_step=global_step)
        g_optim = tf.train.AdamOptimizer(learning_rate=learning_rate, beta1=0.5).minimize(g_loss, var_list=g_vars, global_step=global_step)

i set reuse=None but it still has ValueError: Variable d_bn2/beta/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
i even tried set it to False ,but it still has the error
is that a bug in version r1.2?

**Comment by drpngx** [comment]
did you create the variable before?

**Comment by liguanlin** [comment]
d_loss_real=tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=tf.ones_like(D),logits=D_log))
    d_loss_fake=tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=tf.zeros_like(D_),logits=D_log_))
    d_loss=d_loss_fake+d_loss_real
    g_loss=tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=tf.ones_like(D_),logits=D_log_))
    boolean_error_real=tf.cast(tf.not_equal(tf.reshape(tf.to_int32(tf.round(D_log)),[batch_size,128]),tf.reshape(K,[batch_size,128])),tf.int32)
    bit_error_real=tf.reduce_sum(boolean_error_real,[1])
    boolean_error_fake = tf.cast(tf.not_equal(tf.reshape(tf.to_int32(tf.round(D_log_)),[batch_size,128]), tf.reshape(K, [batch_size, 128])), tf.int32)
    bit_error_fake = tf.reduce_sum(boolean_error_fake, [1])

    z_sum = tf.summary.histogram("z", z)
    d_sum = tf.summary.histogram("d", D)
    d__sum = tf.summary.histogram("d_", D_)
    G_sum = tf.summary.histogram("G", G)

    d_loss_real_sum = tf.summary.scalar("d_loss_real", d_loss_real)
    d_loss_fake_sum = tf.summary.scalar("d_loss_fake", d_loss_fake)
    d_loss_sum = tf.summary.scalar("d_loss", d_loss)
    g_loss_sum = tf.summary.scalar("g_loss", g_loss)
    bit_error_real_sum=tf.summary.scalar("bit_error_real",bit_error_real)
    bit_error_fake_sum=tf.summary.scalar("bit_error_fake",bit_error_fake)

    # 合并各自的总结
    g_sum = tf.summary.merge([z_sum, d__sum, G_sum, d_loss_fake_sum, g_loss_sum])
    d_sum = tf.summary.merge([z_sum, d_sum, d_loss_real_sum, d_loss_sum])

    # 生成器和判别器要更新的变量，用于 tf.train.Optimizer 的 var_list
    t_vars = tf.trainable_variables()
    d_vars = [var for var in t_vars if 'd_' in var.name]
    g_vars = [var for var in t_vars if 'g_' in var.name]

    saver = tf.train.Saver()
    #tf.get_variable_scope().reuse_variables()
    # 优化算法采用 Adam
    with tf.variable_scope(tf.get_variable_scope(),reuse=None):
        d_optim = tf.train.AdamOptimizer(learning_rate=learning_rate, beta1=0.5).minimize(d_loss, var_list=d_vars, global_step=global_step)
        g_optim = tf.train.AdamOptimizer(learning_rate=learning_rate, beta1=0.5).minimize(g_loss, var_list=g_vars, global_step=global_step)

yes,i did @drpngx

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
