### ISSUE TITLE
mnist_with_summaries.py kills gpu

### ISSUE THREAD

**Issue by jben-hun** [tensorflow/tensorflow#11640]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Antergos GNU/Linux x86_64
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2.1
- **Python version**: 3.6.1
- **CUDA/cuDNN version**: 8.0.61 / 6.0.21
- **GPU model and memory**: Nvidia GeForce 840m (Optimus), 2GB memory
- **Exact command to reproduce**: python mnist_with_summaries.py

### Description
Running the following tutorial code produces an error(see below), and renders the gpu unusable until the system is rebooted:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py

If we comment out line 167:
#run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
and line 171:
#options=run_options,
then the code runs fine without error.

### Source code / logs
2017-07-20 11:55:43.203763: I tensorflow/stream_executor/dso_loader.cc:129] Couldn't open CUDA library libcupti.so.8.0. LD_LIBRARY_PATH: /usr/lib/nvidia:/usr/lib32/nvidia:/usr/lib:/usr/lib32:/usr/lib:
2017-07-20 11:55:43.203810: F ./tensorflow/stream_executor/lib/statusor.h:205] Non-OK-status: status_ status: Failed precondition: could not dlopen DSO: libcupti.so.8.0; dlerror: libcupti.so.8.0: cannot open shared object file: No such file or directory

**Comment by asimshankar** [comment]
This seems similar to #8830, could you try the resolution there?

**Comment by jben-hun** [comment]
Thanks @asimshankar, it worked with the corresponding path for the archlinux cuda package directory layout: https://www.archlinux.org/packages/community/x86_64/cuda/

`export LD_LIBRARY_PATH=/opt/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH`

**Comment by eduardomacetas** [comment]
Thank You!

**Comment by sunpeng981712364** [comment]
It doesn't work.
