### ISSUE TITLE
1.3.0rc0 GPU Windows Binaries are broken.

### ISSUE THREAD

**Issue by jubjamie** [tensorflow/tensorflow#11645]
UPDATE: This is most likely due to the new cuDNN requirement not being specified. Users stumbling across this issue should check what cuDNN version they have installed as 1.3 binaries are built with cuDNN v6.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Win10-64
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.3.0rc0 GPU
- **Python version**: 3.6
- **CUDA/cuDNN version**: 8/5.1
- **GPU model and memory**: k40 12gb
- **Exact command to reproduce**: `import tensorflow as tf`

### Describe the problem
_Only tried GPU versions_
Despite what the release config matrix says here: https://ci.tensorflow.org/view/Release/job/release-win/lastBuild/ it appears that the binaries (pip and from ci) for 1.3.0rc0 do not work on windows. Each time will return the pywrap/DLL error etc. Checked with @mrry check script and everything is ok. Tried with python 3.5 and 3.6. 1.2.1 works on both those python versions just fine. I noticed that the 3.5 build for win-gpu was failing but jenkins reckons 3.6 build is ok but i'm unable to replicate a successful install.

Note that I have been running tf-gpu on this machine for a while now so not a dll problem etc. Epecially as a) mrry check script is ok and b) 1.2.1 works just 

### Source code / logs
*insert pywrap/DLL error here*

**Comment by jubjamie** [comment]
Update: @mrry reckons that 1.3 binaries use cuDNN6 by default. Could this be the cause?

**Comment by gunan** [comment]
Yes, 1.3 (even the RCs) are built with cudnn 6 by default.
@av8ramit Could you add this to the release notes?
@jubjamie Do you think if we simply update release notes, would that be sufficient to close this issue?

**Comment by jubjamie** [comment]
@gunan As long as the different cuDNN version is the reason for them not working then I think a clear message to indicate to users there is a change is reasonable. 

Just aware that some users with less patience than me may eventually upgrade to 1.3 and, unless you read the release notes, you may not realise that cuDNN requirements have changed. This could cause an increase in install error reports. I guess that's up to you what is sufficient to placate the issue!

Paging @mrry to perhaps see if he can edit his excellent check script to warn of incompatible cuDNN based on TF version as currently it identifies that cuDNN is installed but turns out it's the wrong version.

**Comment by av8ramit** [comment]
PR is out.
https://github.com/tensorflow/tensorflow/pull/11649

**Comment by av8ramit** [comment]
Release notes are updated. Assigning to @mrry to close or pursue further.

**Comment by mrry** [comment]
I updated the gist: https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c

It's not perfect, since you can't tell what version of TensorFlow is installed without importing the TensorFlow native extension, which would presumably fail! (Perhaps there's some way to scrape `pip` for this information, but I haven't tried.)

Closing this issue for now.

**Comment by mrry** [comment]
(Incidentally #9170 is probably the best place to discuss how to provide better error messages in this case.)
