### ISSUE TITLE
Is there a way to visualise the hidden layer during the Seq2Seq translation in translate.py 

### ISSUE THREAD

**Issue by soukira** [tensorflow/tensorflow#11644]
Is there any way I could visualise the hidden layer process during the translation process in Sequence to Sequence Modelling using Tensorflow.

Tensorflow version: 1.0 CPU version Python: 2.7 Windows

**Comment by caisq** [comment]
Have you tried

1. [TensorBoard](https://www.tensorflow.org/get_started/summaries_and_tensorboard)
or
2. [TensorFlow Debugger (tfdbg)](https://www.tensorflow.org/versions/master/programmers_guide/debugger)

?

**Comment by soukira** [comment]
I did try using tensorboard and couldn't find the metadata file

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
