### ISSUE TITLE
Different behavior tf.contrib.data.Dataset.unbatch() TF ver. 1.2.1 and ver 1.3.0-rc0

### ISSUE THREAD

**Issue by vbystricky** [tensorflow/tensorflow#11666]
Code for reproduce problem:
```python
import tensorflow as tf
print(tf.__version__)
dataset = (tf.contrib.data.Dataset.range(10)
           .batch(5)
           .unbatch())
iterator = dataset.make_initializable_iterator()
print(iterator.get_next())
```

results in TF ver. 1.2.1:
```
1.2.1                                                  
Tensor("IteratorGetNext:0", shape=(), dtype=int64)     
```

results in TF ver. 1.3.0-rc0:
```
1.3.0-rc0
(<tf.Tensor 'IteratorGetNext:0' shape=() dtype=int64>,)
```

**Comment by mrry** [comment]
@ebrevdo I've tried and failed to track down the commit that modified the behavior of `Dataset.unbatch()`, but it looks like we're inappropriately converting single-component datasets to tupled datasets. Can you please take a look?

**Comment by ebrevdo** [comment]
I remember that change. I'll point you to it when at a computer.
