### ISSUE TITLE
Unsupported Wheel

### ISSUE THREAD

**Issue by Tarbo** [tensorflow/tensorflow#1167]
### Environment info
Operating System: Ubuntu 15.10

If installed from binary pip package, provide:

1. pip package: pip3
### Steps to reproduce
1. I installed pip3 and Python3 along with the build-essentials setup
2. I installed Scipy Pack comprising numpy, and the rest.
3. I tried the pip3 install for CPU using the instructions provided [here](https://www.tensorflow.org/versions/r0.7/get_started/os_setup.html#pip-installation) for 64 bits CPU

### What have you tried?
1. I read the error file but I did not understand it

### Logs or other output that would be helpful
------------------------------------------------------------
/usr/bin/pip3 run on Thu Feb 18 04:37:08 2016
tensorflow-0.7.0-py3-none-linux_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python3/dist-packages/pip/req.py", line 168, in from_line
    raise UnsupportedWheel("%s is not a supported wheel on this platform." % wheel.filename)
pip.exceptions.UnsupportedWheel: tensorflow-0.7.0-py3-none-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by HellMood** [comment]
I found a workaround for this problem. See [here](https://github.com/tensorflow/tensorflow/issues/1142).

**Comment by Tarbo** [comment]
Thank you so much for your prompt reply. It worked

**Comment by vrv** [comment]
Thanks @HellMood, we'll take further discussion to that bug and we'll try to fix it in the next patch release.
