### ISSUE TITLE
retrain inception-v3 error

### ISSUE THREAD

**Issue by WangLei-UESTC** [tensorflow/tensorflow#11685]

**Comment by WangLei-UESTC** [comment]
when I retrain inception-v3 on my data set ,running "bazel build -c opt --copt=-mavx tensorflow/examples/image_retraining:retrain" successfully ,but when I run " sudo bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir ~/res",I got this :sudo: bazel-bin/tensorflow/examples/image_retraining/retrain：command not found.
      then I went to the tensorflow root and found the file bazel-bin ,I could not open it ,"无法使用此链接，因为其目标“/root/.cache/bazel/_bazel_root/942963faa10f2c8f4c9028b108793856/execroot/org_tensorflow/bazel-out/local-opt/bin”不存在。"
      please help me ,how can I solve this problem?

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
