### ISSUE TITLE
Program using GPU and CPU mix got slower in  Tensorflow 0.7

### ISSUE THREAD

**Issue by jesuisnicolasdavid** [tensorflow/tensorflow#1168]
I have a Titan X, 
On 0.6, code running well and fast 5 sec for 10 epoch.
I upgrade to 0.7, code running so slow 85 sec for 10 epoch and no matter python2.7 or python3.4.
GPU always on and detected so no CPU is used (unless it has to : "allow_soft_placement=True").
With nvidia-smi, i checked that the GPU was 40 % used in 0.6 version. And it is 97% used in 0.7 version.
So, the GPU is more used for a worst training time ?

**Comment by vrv** [comment]
My guess is that more ops than before are now supported on GPU, so there may be more copying of data between CPU and GPU if you are not careful (e.g., you set allow_soft_placement=True, which means surprising placement decisions could be made :).  Try turning on log_device_placement in the ConfigProto to see what might have changed.

**Comment by girving** [comment]
Closing since we'd need more information to debug.  Please comment or open a new issue if more information arises.
