### ISSUE TITLE
Distributed Tensorflow Authorization

### ISSUE THREAD

**Issue by crohkohl** [tensorflow/tensorflow#11689]
Could somebody comment on the security design of distributed tensorflow? 
Is there some kind of authorization in place for the grpc calls in distributed tensorflow?
E.g., are the clients validated based on the IP or anything else?

If not, how difficult would it be to add authorization support and what would be the best place in the code to get started?

**Comment by reedwm** [comment]
/CC @mrry, can you comment on TensorFlow's security?

**Comment by byronyi** [comment]
Given the comments [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/grpc_server_lib.h#L72), there has been some considerations for adding such feature.

**Comment by mrry** [comment]
TensorFlow is designed to run on private networks that rely on other mechanisms (firewalls, VLANs, VPC, etc.) for network security. The present implementation performs no additional authentication, authorization, or encryption of requests or responses. As the comments in `grpc_server_lib.h` suggest, it would be possible to override the gRPC server and client classes to employ encryption, but there is no API for doing this at present.

**Comment by nartes** [comment]
@mrry,
1. How to specify a host for the server?
As of now the source code does as follows:
- starts a grpc server and binds it to every interface, host is not being used;
[tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc#L194](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc#L194)
- [original commit](https://github.com/tensorflow/tensorflow/commit/00986d48bb646daab659503ad3a713919865f32d#diff-20455d3b7c774e29dbf2f3eafe4ce546R98);
- port option inside ClusterSpec is being used though.
2. The latest commit which treated ```host:port``` better is [00986d48bb646daab659503ad3a713919865f32d](https://github.com/tensorflow/tensorflow/commit/00986d48bb646daab659503ad3a713919865f32d):
- Here AddListeningPort takes server_addr based on task specification;
- [TranslateTask](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/grpc_channel.cc#L209);
- [Commit That Removes That Logic](https://github.com/tensorflow/tensorflow/commit/77887d9f79d0573ceb6254cd322fdbe79f106978).

**Comment by nartes** [comment]
> TensorFlow is designed to run on **private networks that rely on other mechanisms** (firewalls, VLANs, VPC, etc.) for network security. The present implementation performs no additional authentication, authorization, or encryption of requests or responses. As the comments in `grpc_server_lib.h` suggest, it would be possible to override the gRPC server and client classes to employ encryption, but there is no API for doing this at present.

Is there a better option rather than a client source addr pinning?
```
sudo iptables -A INPUT -p tcp --dport <tensorflow_server_port> ! -s <tensorflow_client_host> -j REJECT --reject-with icmp-port-unreachable
```

**Comment by nartes** [comment]
pretty sarcastic comment from a bot. need to add ChatGPT here, to make it a complete echo chamber.
