### ISSUE TITLE
Different GPU memory not all allocated

### ISSUE THREAD

**Issue by ZhongBaby** [tensorflow/tensorflow#11681]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
win10
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.1
- **Python version**: 
3.6
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
cuda8.0,cudnn5.5
- **GPU model and memory**:
GTX Titan 6GB, GTX 1080Ti 11GB

### Describe the problem
Note that tensorflow will allocate tensor/op to all available gpus, but i only got 1080Ti occupied, I wonder if it's a bug or tensorflow doesn't support different gpu models.

**Comment by reedwm** [comment]
Can you clarify what the problem is? Are you saying TensorFlow is only using the 1080 Ti, even though you additionally have a GTX titan? If that is the case, you can use `tf.device(...)` to specify which GPU to use, see the [Using GPUs](https://www.tensorflow.org/tutorials/using_gpu) tutorial.

**Comment by ZhongBaby** [comment]
@reedwm Thanks for response.

Yes, it only use 1080Ti, but I heared tensorflow can automatically take all detected devices' memory.

I have tried to use `tf.device(...)`, but it unhandy for me to place it manually. My question may now be does tensorflow automatically use all devices' memory?

**Comment by reedwm** [comment]
TensorFlow will automatically allocate all the GPUs' memory when it starts. While a TensorFlow is running, the `nvidia-smi` command should show this. But, only the first GPU (in your case, the 1080 Ti) will be used by default. TensorFlow does not automatically place ops on different GPUs so you need to use `tf.device(...)` if you want to use the GTX Titan.

**Comment by ZhongBaby** [comment]
Ok, I think the neural network layers are ops, so they won't be automatically placed on different GPU. So the best practice is to use same type of GPUs, and get them synchronized parameters, asynchronously trained on different batches.
