### ISSUE TITLE
Broken link in "A Tool Developer's Guide..." for graph_metrics.py

### ISSUE THREAD

**Issue by HamedMP** [tensorflow/tensorflow#1169]
Here is the link for `graph_metrics.py` in [this tutorial](https://www.tensorflow.org/versions/r0.7/how_tos/tool_developers/index.html#graphdef) but it's broken:

https://github.com/tensorflow/tensorflow/blob/master/tensorfl%0Aow/python/tools/graph_metrics.py

Update:
Just found other links to the files, such as `freeze_graph()` and `tensorflow/core/framework/tensor.proto` also not working.

**Comment by petewarden** [comment]
Thanks for the report! I'd accidentally added new-lines to some URLs when I was formatting the markdown to an 80-column width, but I've just pushed a fix internally. This bug should be updated automatically once the change goes in, and then the website should get a push soon after that.

**Comment by petewarden** [comment]
Actually I rolled back my internal change since it looks like #1174 / #1175 fix this and we don't want merging conflicts. Closing this bug.
