### ISSUE TITLE
TensorBoard logdir path, if relative, is relative to $HOME

### ISSUE THREAD

**Issue by technopolymath** [tensorflow/tensorflow#117]
It took me a while to figure this out and I'm not entirely sure that my interpretation is correct, but even if I'm not in $HOME, running tensorboard --logdir=. will give a list of directories in my home, and passing an absolute path appears to pick things up correctly. It is somewhat counterintuitive to me that relative paths are not relative to the current directory, so maybe that's something to document, disallow, or change?

Thanks, this library is amazing!

**Comment by danmane** [comment]
Thanks for reporting this, I'm looking into it.

**Comment by pirate** [comment]
@danmane Filed a PR for this, should be a simple fix.  I don't have access to a Windows machine to run the test suite at the moment, but I doubt it'll break anything.

**Comment by pirate** [comment]
Thanks @vrv for reviewing, we should be able to close this out now.

**Comment by vrv** [comment]
Indeed, should be fixed by https://github.com/tensorflow/tensorflow/pull/337
