### ISSUE TITLE
Most of embedding_lookup/embedding_lookup_sparse computations are on CPU,  Most of the GPU time is transferring data.

### ISSUE THREAD

**Issue by nolanliou** [tensorflow/tensorflow#11709]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Centos 7
- **TenorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
r.12
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
0.5.2
- **CUDA/cuDNN version**:
8.0
- **GPU model and memory**:
P40

### Describe the problem
I have done some profiling about *embedding_lookup_sparse*, i have use `tf.device('\gpu:0')` to specify where the ops run. But the results show:

- Most of the operations are performed on the CPU.
- GPU was transferring data at most of time.

After I looked into the codes, there are some Ops without GPU version, including `dynamic_partition`,  `segment_sum`, `strided_slice`. So I'm a little confused.

Is this intended behavior? Or are these Ops not implemented yet? Thanks for the explanations.

Here is some profiling result:
### tfprof
```
I tensorflow/core/common_runtime/simple_placer.cc:841] hidden/embed/embedding_lookup_sparse/embedding_lookup/DynamicPartition:(DynamicPartition)/job:localhost/replica:0/task:0/cpu:0
hidden/embed/embedding_lookup_sparse: (SegmentSum): /job:localhost/replica:0/task:0/cpu:0
hidden/embed/embedding_lookup_sparse/strided_slice: (StridedSlice): /job:localhost/replica:0/task:0/cpu:0
```
### nvprof
```
==4762== Profiling result:
Time(%)      Time     Calls       Avg       Min       Max  Name
 44.07%  130.029s    240276  541.17us     768ns  8.1151ms  [CUDA memcpy DtoH]
 25.20%  74.3504s    480619  154.70us     992ns  8.9016ms  [CUDA memcpy HtoD]
  9.84%  29.0339s    330000  87.981us  61.922us  610.68us  void tensorflow::GatherOpKernel<float, int>(float const *, int const *, tensorflow::GatherOpKernel<float, int>*, __int64, __int64, __int64)
```

**Comment by reedwm** [comment]
Can you provide the code you ran that demonstrates `embedding_lookup_sparse` performance, and the tfprof commands you used to generate the output? Thank you

**Comment by nolanliou** [comment]
Code: [embedding_lookup_sparse](https://gist.github.com/nolanliou/c00af5938b2aecfdc5ea1189426b8624). 

tfprof code to do the profiling: 
```
  tf.contrib.tfprof.model_analyzer.print_model_analysis(
    tf.get_default_graph(),
    run_meta=run_metadata,
    tfprof_options=tf.contrib.tfprof.model_analyzer.PRINT_ALL_TIMING_MEMORY)
````

**Comment by reedwm** [comment]
/CC @alextp Can you take a look? When I run, all ops are put on the CPU.

**Comment by nolanliou** [comment]
@reedwm there are some ops in GPU like `gather`. did you use gpu? By the way I add `with tf.device('/gpu:0')`, maybe you can have another try. Thanks.

**Comment by alextp** [comment]
`embedding_lookup` and friends should only rely on dynamic partition and other cpu-heavy ops when you have partitioned embedding variables.

Most of the use cases I've seen for partitioning embedding variables put them on remote parameter servers (since there's no point in sharding locally) and most setups I know of involving parameter servers are more efficient when the partitioned variables are on the CPU than when they are on the GPU.

Are you using GPU-placed partitioned variables? If so, why?

I don't think it's easy using our current setup to get rid of dynamic_partition for partitioned embedding lookup.

**Comment by nolanliou** [comment]
I just tested the local situation. I got your point, I'll have a try. Thank you very much for the detailed answers.

**Comment by nolanliou** [comment]
@alextp
### System information
* ***Code***
[embedding_lookup_sparse](https://gist.github.com/nolanliou/c00af5938b2aecfdc5ea1189426b8624)
* ***Params***
100M * 1K
* ***Id***
256 * 1000
* ***CPU***
32-cores
* ***Tensorflow***
r1.3
### Conclusion
On a single machine,  profiling the `embedding_lookup_sparse` with tfprof, the result shows that `gather` Op takes a lot of time. I checked the code and found that the CPU version `gather` op is single-thread. 
Then I modify the `gather` Op to multi-threads, the result shows about 6x speedup, which benifites a lot of cases. If neccessary, I can post a PR.

### Profiling result
```
node name | requested bytes | total execution time | accelerator execution t    ime | cpu execution time`
# old `gather`
Gather     2048.00MB (100.00%, 2.27%),   622.96ms (99.99%, 22.97%),    0us (0.00%, 0.00%),  622.96ms (99.99%, 22.97%)
# multi-thread `gather`
Gather    2048.00MB (100.00%, 49.96%),   107.91ms (99.99%, 5.50%),     0us (0.00%, 0.00%),   107.91ms (99.99%, 5.50%)
```

**Comment by alextp** [comment]
Please send a PR!

**Comment by nolanliou** [comment]
@alextp I have sent a PR, please review it if you have time. Thanks.

**Comment by nolanliou** [comment]
@alextp following question.
Same environment with last comment.
