### ISSUE TITLE
error in installation instructions

### ISSUE THREAD

**Issue by sameermahajan** [tensorflow/tensorflow#11708]
In instructions specified at: https://www.tensorflow.org/install/install_linux#ValidateYourInstallation

it states:

 For example, the following command installs the CPU-only version of TensorFlow for Python 2.7:

 (tensorflow)$ pip install --ignore-installed --upgrade \
 https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.2.1-cp34-cp34m-linux_x86_64.whl

However it is for Python **3.4** (not 2.7)

**Comment by asimshankar** [comment]
Thanks for pointing this out, will fix it.
