### ISSUE TITLE
Using higher order operators within tf.contrib.data.Dataset.map raises a segmentation fault

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#11715]
### System information

- **Have I written custom code**: Yes
- **OS Platform and Distribution**: Ubuntu 16.04
- **TensorFlow installed from**: binary
- **TensorFlow version**: `('v1.2.0-2323-geaa7a8e', '1.3.0-rc0')`
- **Python version**: 2.7.6
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: GTX 1080 (8GB)
- **Exact command to reproduce**: see the code snippet below

### Describe the problem

When using a higher order operator (such as `tf.map_fn`) within the `tf.contrib.data.Dataset.map` method, the program exits with a `Segmentation fault`.

### Source code / logs

```python
import tensorflow as tf

dataset = tf.contrib.data.Dataset.from_tensor_slices([
  tf.constant([1, 2, 3, 4, 5, 6])])

dataset = dataset.map(lambda elems: tf.map_fn(lambda x: x * x, elems))

iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

with tf.Session() as sess:
  print(sess.run(next_element))
```

---

My particular use case is to split a sentence into tokens and then map a function on each token to build tensors of characters.

**Comment by jrabary** [comment]
+1 In my case I added a tf.map_fn to decode a set of images. I noticed that the simple fact of adding tf.map_fn in the graph causes this problem.

**Comment by mrry** [comment]
Looks like the problem is a missing `ScopedStepContainer` in the context when you run the function in `Dataset.map()`. The same problem also afflicts `Dataset.filter()`, although perhaps it would be less common for a predicate to use `tf.map_fn()`. I have a change in the works!
