### ISSUE TITLE
tf_cnn_benchmarks.py stuck when running with multiple GPUs and ImageNet data with protocol grpc+verbs

### ISSUE THREAD

**Issue by shamoya** [tensorflow/tensorflow#11725]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, running tf_cnn_benchmarks.py from benchmarks repo
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.2 LTS
- **TensorFlow installed from (source or binary)**: Unmodified source with RDMA Verbs enabled
- **TensorFlow version (use command below)**: 1.3.0-rc0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.5.1
- **CUDA/cuDNN version**: 8.0/6
- **GPU model and memory**: NVIDIA Tesla P100 PCIe 16GB (8 per node)
- **Exact command to reproduce**: 

PS: CUDA_VISIBLE_DEVICES='' python tf_cnn_benchmarks.py --ps_hosts 12.12.12.43:20000 --worker_hosts 12.12.12.44:20000,12.12.12.41:20000 --batch_size=64 --model=inception3 --variable_update=parameter_server --local_parameter_device=cpu --job_name=ps --task_index=0 --server_protocol grpc+verbs

Worker0: CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6,7' python tf_cnn_benchmarks.py --ps_hosts 12.12.12.43:20000 --worker_hosts 12.12.12.44:20000,12.12.12.41:20000 --batch_size=64 --model=inception3 --variable_update=parameter_server --local_parameter_device=cpu --job_name=worker --task_index=0 --num_gpus=8 --data_dir=/data/imagenet_data/ --train_dir=/data/imagenet_train/ --server_protocol grpc+verbs

Worker1: CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6,7' python tf_cnn_benchmarks.py --ps_hosts 12.12.12.43:20000 --worker_hosts 12.12.12.44:20000,12.12.12.41:20000 --batch_size=64 --model=inception3 --variable_update=parameter_server --local_parameter_device=cpu --job_name=worker --task_index=1 --num_gpus=8 --data_dir=/data/imagenet_data/ --train_dir=/data/imagenet_train/ --server_protocol grpc+verbs

- **RDMA driver version**: MLNX_OFED_LINUX-4.1-1.0.2.0

### Describe the problem
When running the above commands (Inception V3 synchronized data parallelism training with 2 workers and 1 external ps), the tf_cnn_benchmarks application hangs forever after some iterations (usually in warm up).

It happens only when real data is involved (ImageNet), and with >4 GPUs. (More GPUs, less iterations before it hangs). Doesn't happen with grpc protocol, or when running with "synthetic" data.

The master_service in the workers is stuck [here](
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/master_session.cc#L608), which I guess means some operations in the computation have not been completed.

The RDMA protocol looks valid and clean, all messages corresponds to the protocol (see below logs). 
There some tensors requested by the workers which they don't receive, but they are passed by the RDMA Verbs transport to the BaseRendezvoudMgr with RecvLocalAsync in a valid way, and for some reason the higher level worker service doesn't trigger the Send kernel on those tensors.

Any help is much appreciated!
If there are some debug mechanisms I can use to understand which tensors/operations have not been completed it can greatly help. I was mostly debugging this from the RDMA Verbs layer till now, without much success, and I feel I don't have enough information there to understand what's missing.
Also I feel we don't have enough knowledge on how the step_id acts (diving into this in the code now, but there's some higher level documentation it can greatly help).

My initial guess was an occurrence of a racy condition when loading the data, since it creates a gap in execution time (worker0 starts the first training step 30-60 seconds after worker1, since it does the preprocessing of the data twice for a reason I couldn't understand yet), but after the first iteration (which usually passes successfully) the time is synchronized between workers.

### Source code / logs
Those are the logs of the runtime after moving the logging in [rdma.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc) to VLOG(0) (also adding Tensor name and step id for all cases, in some cases the step_id doesn't mean anything like BUFFER_REQUEST/RESPONSE for example), and also some VLOG in [master_session.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/master_session.cc)

[worker0](https://gist.github.com/shamoya/15a42f421e088473b8f02bf00c16d0fc)
[worker1](https://gist.github.com/shamoya/dd3126c02c73990a6e28b534d9a9ddf6)
[ps](https://gist.github.com/shamoya/0c856365802ae4d42b38baf988149574)

Unfortunately they are fairly large, but it's better then to cut the log files IMO.
Example for analysis I did in the verbs layer, comparing the Sent Tensor requests to the actual received tensors writes in both workers:

worker 0:
 -  /job:ps/replica:0/task:0/cpu:0;f3c10d28b54074c0;/job:worker/replica:0/task:0/gpu:0;edge_116943_group_deps_2/NoOp_1;0:0 80661058974090965
-  /job:worker/replica:0/task:1/cpu:0;1a50d5c51cd9c5d1;/job:worker/replica:0/task:0/gpu:0;edge_116947_group_deps_3/NoOp_1;0:0 80661058974090965
- /job:worker/replica:0/task:1/gpu:2;7f00fadabfe781f5;/job:worker/replica:0/task:0/gpu:0;edge_111078_group_deps_1/NoOp_2;0:0 80661058974090965
- /job:worker/replica:0/task:1/gpu:4;b07185dd19f62088;/job:worker/replica:0/task:0/gpu:0;edge_111080_group_deps_1/NoOp_4;0:0 80661058974090965

worker 1:
- /job:ps/replica:0/task:0/cpu:0;f3c10d28b54074c0;/job:worker/replica:0/task:1/cpu:0;edge_155113_AssignAdd;0:0 80661058974090965
- /job:worker/replica:0/task:0/gpu:0;f3df8abf03739fe8;/job:worker/replica:0/task:1/cpu:0;edge_116948_group_deps_3;0:0 80661058974090965

The tensors requests received well by the other side and passed to RecvLocalAsync, but are not called later.

Thanks a lot.

**Comment by junshi15** [comment]
I was able to reproduce the issue. I also tried 'alexnet', it hung as well. I will take a close look in the coming days. Thanks for reporting.

**Comment by reedwm** [comment]
Thank you for looking into this @junshi15!

**Comment by shamoya** [comment]
+ @mrry @jhseu @poxvoculi , just a small question.
I'm trying to understand why execution hangs in [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/master_session.cc#L608).
What (I think) I need is to get the Executor(s) which doesn't end in [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/graph_mgr.cc#L541).
I tried passing tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE) to sess.run but then I get a huge file I can't really understand.  Is this the right way ?

**Comment by suiyuan2009** [comment]
I think `global_step` should be protected by a lock.I raised [an issue](https://github.com/tensorflow/benchmarks/issues/38). I'm not sure if tensorflow has some special code for `global_step`.

**Comment by poxvoculi** [comment]
When I'm trying to debug a hung concurrent program the first step is
usually to try to find a small case that exhibits the problem, i.e. try to
find the least number of workers and GPUs that still hangs.  It's much
easier to debug a small case than a large one.  Then, if it's a really
small case you might be able to set the logging level high and read all the
log files.  Usually though, I form some hypotheses about where the problem
might be (e.g. a missing lock, a race that might result in deadlock, logic
error that always deadlocks) and start putting in LOG(INFO) statements
around the suspicious points to confirm or refute each hypothesis.

**Comment by reedwm** [comment]
@tfboyd I'm unassigning myself because I know very little about the RPC layer and know nothing about VERBs. I don't think this is a bug with tf_cnn_benchmarks, because #11416 also has the same issue with a different model.

@suiyuan2009 I don't think tensorflow/benchmarks#38 is the same issue, since this issue only occurs with verbs, and it occurs with another model with verbs. I'll take a look at tensorflow/benchmarks#38 though.

**Comment by shamoya** [comment]
Thanks @poxvoculi 
Sadly the smallest case which repro the issue is 3 nodes (2 workers 1 ps) with InveptionV3 and ImageNet, with the tf_cnn_benchmark.py (haven't checked others).
I had ~15 hypotheses which turn out to be false.
Added a lot of prints, but still couldn't understand which tensor is the rebel.
I feel the trace_log mechanism (tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)) can help me here, but I have no idea how to parse it. Is there a parsing tool or format for it ?

**Comment by suiyuan2009** [comment]
after adding  a lock to `global step`, I didn't meet stuck problem.
but I got error when running vgg benchmark code.
```
2017-07-26 21:21:26.691844: F tensorflow/contrib/verbs/rdma.cc:683] Check failed: status.ok() RecvLocalAsync was not ok, key/job:worker/replica:0/task:2/gpu:1;b0903effc6e4881e;/job:ps/replica:0/task:0/cpu:0;edge_2493_Mul_1;0:0;138139939197237012 error message: Step 138139939197237012
```

**Comment by byronyi** [comment]
@suiyuan2009 Your error might be caused by another process (PS or worker) in your job. We have met the same problem and it turns out when one process terminated the connection, its peers will print out such odd error log.

**Comment by byronyi** [comment]
@shamoya For a simpler model, you could try `--model=trivial` (the default one) and set your number of batches to a smaller value. 

Sorry that I am busying working on migrating my own patch and have little time to reproduce this particular bug right now.

**Comment by junshi15** [comment]
@shamoya Can you try what @suiyuan2009 and @byronyi suggested.

1) try the simple model to see if it hangs `--model=trivial`.

2) add a lock around global_step. something like
```
  with self.lock:
        inc_global_step = global_step.assign_add(1)
        fetches.append(inc_global_step)
```)

  some where in the init function, you define the lock:
       `self.lock = threading.Lock()`

I was unable to get an infiniband setup yesterday. I will try again today.

**Comment by poxvoculi** [comment]
@shamoya 
The tracing data is available in a pre-parsed (protobuf) format.  See the run_metadata option to Session.run, which returns tracing data in StepStats.

**Comment by suiyuan2009** [comment]
@junshi15 @shamoya 
note that `global_step` is also a part of computing graph, `assign_add` op has a `use_locking` arg.

**Comment by shamoya** [comment]
@byronyi , you're the best ! it's reproduced on trivial case (with ImageNet data).
Now it will be much easier to debug, going full VLOG now - let's hope I'll have update soon.

@suiyuan2009, it's not related to the global_step.
I changed to have only the chief increment it and it doesn't have any affect.

**Comment by suiyuan2009** [comment]
@byronyi, do your GDR patch have met same problem like stuck or failure?

**Comment by byronyi** [comment]
No I have not met such kind of problems, at least not during our internal testing. But my patch uses vastly different design compared to current verbs implementation so there is little I can tell about this particular issue.

**Comment by junshi15** [comment]
My observation agrees with @shamoya 's.

1) the program got stuck with the trivial model, but it needed 8 GPUs per worker. Even 7 GPUs do not result in hang (after running 1000 iterations).
2) the program got stuck either at warm-up or early iterations (< 100).
3) locking global_step does not help.
4) At the very beginning, some tensors changed size as shown below. This may not be an issue, but it will be good to find out why.

```
tensor and buffer size do not agree! buffer_size = 653 requested tensor size = 593 Tensor<type: int64 shape: [0,1] values: > key = /job:ps/replica:0/task:0/cpu:0;ccc0db7aa974ba53;/job:worker/replica:0/task:0/gpu:0;edge_37_report_uninitialized_variables/boolean_mask/Where;0:0

tensor and buffer size do not agree! buffer_size = 649 requested tensor size = 589 Tensor<type: int64 shape: [0] values: > key = /job:worker/replica:0/task:0/gpu:0;62e354fc58da5afa;/job:ps/replica:0/task:0/cpu:0;edge_39_report_uninitialized_variables/boolean_mask/Squeeze;0:0
```

**Comment by shamoya** [comment]
+ @katyakats @bkovalev
Ok, after reviewing the full logs, this is what we think is the root cause: 
A single GPU (in worker1) doesn't complete loading of the model parameters from the CPU.
For this GPU we don't see "Async kernel done" for the SEND/RECV operation (CPU:0 -> GPU:x locally).

The reason why it happens only with RDMA (and not with gRPC) is not known yet.
Thought about possibly interrupts issue due to excessive interrupts (8 GPUs + NIC + NVMe drive which holds the ImageNet data, all on the same PCIe bus). however polling mode of Process_CQ (no interrupts from the NIC at all) didn't resolve the issue.

[This](https://gist.github.com/shamoya/824d452be527d95902f20b59f868b391) is the problematic GPU relevant logs.

**Comment by byronyi** [comment]
Just a wild guess, if the callback passed into the local async recv kernel is an erroneous remote send, would it appear to be stuck at the local recv? What's the downstream operator of that local recv?

**Comment by junshi15** [comment]
@shamoya intriguing discovery. Local tensor transfer is handled by BaseRemoteRendezvous. There is one difference between gRPC and RDMA: tolerate_dup_recv is set to `false` in [the former](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/core/distributed_runtime/rpc/rpc_rendezvous_mgr.cc#L42) and `true` in [the latter](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/contrib/verbs/rdma_rendezvous_mgr.cc#L34). The reason: gRPC only receives a tensor once, with verbs we have multiple receive attempts, since the tx/rx buffer may not be ready at early attempts. I ran some experiments by changing that to `true` in gPRC model, no hang was observed. However [this patch](https://github.com/tensorflow/tensorflow/commit/cbfd50ff0f01e1825922230a8bc6e5766da98dd7#diff-b9ae16e68ba80801fe243bb5e19bac51) totally broke the verbs code. I had to raise an issue [here](https://github.com/tensorflow/tensorflow/issues/11825). Something to worry about after this debug.

A correction to what I said early, I finally saw hang with 7 GPUs per worker, after 2000 steps.

**Comment by shamoya** [comment]
Thanks @junshi15 for noticing this commit.
Not sure I understand why you say BaseRemoteRendezvous is used in the case of local tensor transfer between GPU and CPU on the same worker.
[This](https://gist.github.com/shamoya/36beb1d093d4b95a523e27d4deda16ea) is a more detailed log of the all the occurences of affine1/biases in the last iteration in worker1. We can see the RdmaRemoteRendezvous has completed successfully from the PS.
I'm not so sure anymore this issue is even related to the Verbs code.

**Comment by junshi15** [comment]
@shamoya RdmaRemoteRendezvous is a derived class of BaseRemoteRendezvous. The local send/receive functions are defined in the base class. RdmaRemoteRendezvous only overrides RecvFromRemoteAsync().

**Comment by byronyi** [comment]
I noticed the date of that commit is 6 days ago, but I remember, if correctly, the issue came out earlier than that.

Please ignore me if I'm wrong. Maybe you guys could revert that commit locally first and test if the issue could still be reproduced.

**Comment by junshi15** [comment]
That patch is unrelated to this bug.  I am testing code prior to that. With that patch, the RDMA path won't run, and you will get an immediate crash.

**Comment by katyakats** [comment]
I digged a little deeper into the bug.
One of the NoOps from a single GPU is never sent (the thread is stuck in  CopyGPUTensorToCPUSync method). It appears that this method is not called from the grpc, but only from the verbs code. 
Reverting commit  626d8d905aa412aaca02d171e5e0b4a1c407656b (Improve RDMA rendezvous speed) that made changes in this code area did not resolve the issue. 
Does anyone have any ideas?

**Comment by junshi15** [comment]
CopyGPUTensorToCPUSync  is a synchronous wrapper for GPUUtil::CopyGPUTensorToCPU.
It was stuck only because CopyGPUTensorToCPU did not complete or did not send notification.
But grpc uses CopyGPUTensorToCPU, not sure why this is not an issue.

**Comment by katyakats** [comment]
thanks @junshi15 
Do you have any thoughts on why CopyGPUTensorToCPU does not complete or send notification?

**Comment by junshi15** [comment]
I am looking at [CopyGPUTensorToCPU](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/core/common_runtime/gpu/gpu_util.cc#L304-L347). It eventually calls [ThenMemcpy](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/stream_executor/stream.h#L1492-L1497). The comment says the host memory needs to be registered. I am not familiar with this piece of code, but this is not done in the verbs code. If it is indeed required, then it is what's missing.

**Comment by byronyi** [comment]
Did you check for the 3 odd edge cases mentioned [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/grpc_worker_service.cc#L338)? Just a wild guess, if it is a `NoOps` it might be related to the `is_dead` parameter.

**Comment by junshi15** [comment]
@byronyi I don't see all 3 odd cases are checked in your link (I don't see zero-size and is_dead is checked). Equivalent code in verbs is [here](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/contrib/verbs/rdma.cc#L707-L719), pretty much follows that link. is_dead is fed to SetProtoFromGPUSync, but zero-size is not checked in both cases.

**Comment by junshi15** [comment]
@katyakats When you reverted commit 626d8d9 (Improve RDMA rendezvous speed), where did the code hang? SetProtoFromGPUSync?

**Comment by katyakats** [comment]
@junshi15 thank you! we will check this direction! 
I did not check what method is stuck when I reverted the commit. Will check this as well

**Comment by shamoya** [comment]
Hi @junshi15 , following the discussion [here](https://github.com/tensorflow/tensorflow/issues/11825) and in this bug and after I review the code, I think we have a serious issue with tolerate_dup_recv mechanism (maybe this is why it was removed ? ).

I think [this](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/core/framework/rendezvous.cc#L209) is wrong in case We don't don't do a duplicate receive (if we have a buffer already in some step), becasue no one will UnRef it, in case the Recv will not be called.
Do u think it might be the issue ?

**Comment by junshi15** [comment]
@shamoya UnRef is in [Recv](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/core/framework/rendezvous.cc#L264). In what case Recv will not be called? In verbs case, Send only is only called once, but Recv is called multiple times.

**Comment by shamoya** [comment]
If Recv was called before the SEND ?

**Comment by junshi15** [comment]
If the first Recv is called before Send, then the waiting table does not have the tensor yet, Recv will put a callback in the table and return. Now, if a second Recv is called and still before Send, I think there is an issue since we allow multiple Recvs. In this case, [an empty tensor will be received](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/core/framework/rendezvous.cc#L246). We will have trouble in the downstream. Is this what you are referring to?

**Comment by shamoya** [comment]
No @junshi15, you didn't follow me, I'll try to be more clear.

Let's say RECV is called before SEND, and puts [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L678) callback in the table a u said. And let's say there's already a buffer for this tensor, meaning this callback will be called once (trigger TENSOR_WRITE).
now SEND flow performs [this](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/core/framework/rendezvous.cc#L209) Ref() before calling the callback, since it assumes the RECV **can** be duplicated and called again.
But in this case it doesn't, and no one will do [this](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/core/framework/rendezvous.cc#L264) Unref.

When we are stuck in the bug, I noticed there's a huge diff between Refs and Unref on the GPU that is "stuck" (hundernds).

Now, I do see [this](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/core/framework/rendezvous.cc#L323) Unref, in the Item destructor, which might do the missing Unref, but I need to check if it happens.

**Comment by junshi15** [comment]
@shamoya Thanks for the explanation. A Recv-Send sequence does increase the reference count by one for send_dev_context. This can be a problem. I tried adding Unref right after [this](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/core/framework/rendezvous.cc#L219), it crashed right away.

@katyakats mentioned hang at `CopyGPUTensorToCPU`. I see similar issue. Here is a [stack trace](https://gist.github.com/junshi15/af3063e5bd22c911c30fcaafee060fa1) I captured with gdb when the program hung. It was stuck while trying to lock a mutex. Frame #2 is `SetProtoFromGPUSync` and Frame #20 is `CopyCPUTensorToGPU`. Note both of them call `ThenExecute`, which uses the same lock. So a nesting call like this tries to acquire a already obtained lock, a recipe for hang. Not sure what caused this situation.

**Comment by shamoya** [comment]
Wowww @junshi15, looks like this is it ! 

I've ran the test with inter/intra_op_parallelism_threads = 500 and it passed (multiple times).
It workaround the problem by reducing the probability to have this scenario (Schedule of the threadpool more likely to choose an idle thread).
It also explains why it happens when working with real data (queue readers also use the same threads)!

@poxvoculi
Really not clear to me how Schedule is possible on a thread which holds a mutex.
Can't understand also where the context switch happens in this thread while it performs ThenExecute.

Thanks @junshi15 !

**Comment by yanivbl6** [comment]
By reducing the number of threads to 1 inter_thread I managed to reproduce the bug in a system with 2 GPUs per host and 2 hosts only  (2ps + 2 workers). I believe its the same issue because it occurs only when using verbs and I am getting the same backtrace as @junshi15 did. so I think we are close.

But I don't think **ThenExecute** is the problem.
I've added VLOG prints before and after the critical section, And counted them afterward. No one seems to be 'stuck' inside (locks and unlocks were equal).

**Comment by junshi15** [comment]
@shamoya Glad we are making some progress.
@yanastali Thanks for your help. This [line](https://gist.github.com/junshi15/af3063e5bd22c911c30fcaafee060fa1#file-gistfile1-txt-L2) seems to be waiting for a mutex. We need to identify the mutex inside `SetProtoFromGPUSync`.

**Comment by junshi15** [comment]
This [line](https://gist.github.com/junshi15/af3063e5bd22c911c30fcaafee060fa1#file-gistfile1-txt-L37) is not `CopyCPUTensorToGPU` itself. It looks like a lambda function (callback?) inside `CopyCPUTensorToGPU`.

**Comment by yanivbl6** [comment]
I think this line relate to the condition variable of "Notification n", which requires a mutex. (for waiting).
If I got this right The condition variable is waiting for the callback, that was scheduled after the stream in ThenExecute.

**Comment by yanivbl6** [comment]
I think the problem rises because the Sync deviceToDevice operation blocks the thread, preventing the earlier Async Device to Device operation from finishing- which, for some reason, blocks the later operation.

What I did to check this was change the [call to the wrapper sync function](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L724) to a call to the async function, and inserted the rest of the code (that which is executed after the sync wrapper) into then lambda callback function ("done"). With this setting, the application no longer hangs (Tested multipile times, few of which in 8 gpus system). 
@junshi15 , is there an additional motivation for the usage of the sync wrappers, beside the pending operations we execute after the operation is completed?

**Comment by junshi15** [comment]
@yanivbl6 Thanks for looking into it. There is another sync wrapper function, [SetProtoFromGPUSync](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L730). We should convert that back to async as well. 

The motivation for using sync wrapper is mainly for simplicity. Otherwise, you end up with chained call-backs, which is actually fairly common in tensorflow code.

Please submit a PR if you have a fix.

**Comment by shamoya** [comment]
Great job @yanivbl6 , looks like this is it.
Waiting for the PR with the fix.

Looking now in the gRPC code, they are doing this flow aysnc, this is probably why we didn't see it when running with gRPC.

**Comment by bkovalev** [comment]
Thanks to all to solve it! Great job!  Go to check it !
Need to put it in r1.3 and master.

**Comment by junshi15** [comment]
@poxvoculi We found some of [the wrapper functions](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/verbs_util.cc#L23-L70) caused hang. Do you know whether we are not supposed to use the sync version of these functions? I know CPU/GPU transfer can be slow,  but I did not expect it to hang. Thanks.

**Comment by poxvoculi** [comment]
I would avoid using any sync version of a function where an async version with callback is available.  The sync versions suspend a thread which could lead to a deadlock if you run out of threads.  It may be that by blocking you've also introduced a deadlock some other way, where the callback is waiting on something whose execution would have been triggered after the async invocation returned.

**Comment by junshi15** [comment]
@poxvoculi What we saw matches your description. Hang happens when 4+ GPUs are used. It goes away when we increase the number of threads. @yanivbl6 is working on a [fix](https://github.com/tensorflow/tensorflow/pull/12361).

**Comment by shamoya** [comment]
#12361 merged to master

**Comment by nicolefinnie** [comment]
> @poxvoculi What we saw matches your description. Hang happens when 4+ GPUs are used. It goes away when we increase the number of threads. @yanivbl6 is working on a [fix](https://github.com/tensorflow/tensorflow/pull/12361).

@junshi15  Cool thanks, I hit a very similar problem and got stuck during the warm up. As you suggested, I increased `inter_op_parallelism_threads` to work around the problem. 

before changing the number of threads, I couldn't get this far. 
`2018-10-20 01:54:02.736996: I tensorflow/stream_executor/dso_loader.cc:151] successfully opened CUDA library libcupti.so.9.2 locally`

**Comment by yanivbl6** [comment]
@nicolefinnie - did you experience an hang with grpc+verbs?
This issue was (At least, to my knowledge) fixed already.
What TF version are you experiencing this issue with?

**Comment by nicolefinnie** [comment]
@yanivbl6  Thanks for your response. It's tensorflow `1.11` and I didn't change the server protocol so it's `grpc` by default.

**Comment by junshi15** [comment]
@nicolefinnie The thread is about an issue related to grpc+verbs, and it has been fixed by @yanivbl6.
I do not know why you are experiencing the issue with grpc only.

**Comment by yanivbl6** [comment]
I experienced an hang with the master branch and vanilla grpc about a week ago, and it was already fixed in master. I would suggest trying to pull the latest commit.
