### ISSUE TITLE
Problems with viewing a graph using the mnist tutorial code

### ISSUE THREAD

**Issue by McMDA** [tensorflow/tensorflow#1173]
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

### Environment info
Operating System:Ubuntu 14.0

If installed from binary pip package, provide:

1. Which pip package you installed. 
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.06
If installed from sources, provide the commit hash:

### Steps to reproduce

1. This doesn't make generate a graph
summary_writer = tf.train.SummaryWriter(train_dir,graph_def=sess.graph_def)
2. This generates a graph
summary_writer= tf.python.training.summary_io.SummaryWriter(train_dir,graph_def=sess.graph_def)

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by vrv** [comment]
(Try upgrading to 0.7.1 -- there have been many bug fixes since that release).

**Comment by McMDA** [comment]
Thanks.

Donald McMenemy

**Comment by mrry** [comment]
Closing this issue, since the upgrade seems to have worked. Let us know if it didn't!
