### ISSUE TITLE
Docker :: Restoring from a model outside the container returns FailedPreconditionError

### ISSUE THREAD

**Issue by ilchemla** [tensorflow/tensorflow#11742]
### System information
- **OS Platform and Distribution**: Docker Tensorflow CPU Image
- **TensorFlow version (use command below)**: 1.2.1
- **Python version**: Python 2.7.12

### Source code / logs
```python
saver = tf.train.Saver()
with tf.Session(config=config) as sess:
    saver.restore(sess, checkpoint_file)
```

### The Issue
I'm binding a host `models` directory to `/data/models` inside the container.
When trying to restore, I got a `Failed precondition`
Everything's okay when I'm not using Docker
Everything's okay when I'm building a Docker Image with the models already copied into it (but not flexible)

```
INFO:tensorflow:Restoring parameters from /data/models/OSVOS_parent.ckpt-50000
2017-07-25 08:53:42.434679: W tensorflow/core/framework/op_kernel.cc:1158] Failed precondition: /data/models/OSVOS_parent.ckpt-50000.index
///
tensorflow.python.framework.errors_impl.FailedPreconditionError: /data/models/OSVOS_parent.ckpt-50000.index
	 [[Node: save/RestoreV2_20 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_20/tensor_names, save/RestoreV2_20/shape_and_slices)]]

FailedPreconditionError (see above for traceback): /data/models/OSVOS_parent.ckpt-50000.index
	 [[Node: save/RestoreV2_20 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_20/tensor_names, save/RestoreV2_20/shape_and_slices)]]
```

**Comment by caisq** [comment]
@ilchemla what are the versions of your tensorflow inside and outside the docker container?

**Comment by ilchemla** [comment]
Same `tensorflow (1.2.1)`

**Comment by aselle** [comment]
How are you mounting? with -v on the docker run? Are they read-only? If you copy the checkpoint into the docker cotnainer rather than -v mounted directory does it work (slightly different than just pre-loading it into the image)?

**Comment by ilchemla** [comment]
Yes I'm using `-v` argument

`docker run -ti -v /Users/work/data/models/:/data/models/ -v /Users/work/tensorflow-example:/opt/tensorflow-example tensorflow/tensorflow python -u /opt/tensorflow-example/train.py --model /data/models/OSVOS_parent.ckpt-50000`

The issue doesn't reproduce 100% but for most call it happen.
