### ISSUE TITLE
Using AOT compilation on network with bidirectionnal layer fails because of missing Exit on Switch node

### ISSUE THREAD

**Issue by lissyx** [tensorflow/tensorflow#11745]
I have been reproducing that for a while, ranging from 1.0.1 builds to current master. Running `tfcompile` fails like this:

```
tensorflow/bazel-bin/tensorflow/compiler/aot/tfcompile --graph=test.pb  --config=native_client/tfcompile.config.pbtxt
2017-07-13 13:29:55.989141: I tensorflow/compiler/xla/service/platform_util.cc:58] platform Host present with 4 visible devices
INVALID ARGUMENTS: Missing Exit successor to bidirectional_rnn/fw/fw/while/Switch
```

I have been able to find that this was 100% repro when we have the bidirectionnal layer in the network:
```
tf.nn.bidirectional_dynamic_rnn(...)
```

As long as there are no more bidirectionnal layers, then it is fine. I searched and I have not been able to find any documentation (but maybe I missed it?) that would state properly the status of the `Exit` node wrt `Switch` node. Further investigation would show that some of the `Switch` nodes in the network would be followed by one `Exit` but that this one was being followed by `Identity`.

I assumed that the checks performed by `tfcompile` were too tight, and took a chance:
```
diff --git a/tensorflow/compiler/tf2xla/functionalize_control_flow.cc b/tensorflow/compiler/tf2xla/functionalize_control_flow.cc
index faa88ecfe..fda3cbd00 100644
--- a/tensorflow/compiler/tf2xla/functionalize_control_flow.cc
+++ b/tensorflow/compiler/tf2xla/functionalize_control_flow.cc
@@ -383,8 +383,8 @@ Status FunctionalizeLoop(Graph* graph, Frame* frame,
         }
       }
       if (arg.exit == nullptr) {
-        return errors::InvalidArgument("Missing Exit successor to ",
-                                       arg.switch_node->name());
+        // return errors::InvalidArgument("Missing Exit successor to ",
+        //                                arg.switch_node->name());
       }
     }
   }
@@ -454,7 +454,7 @@ Status FunctionalizeLoop(Graph* graph, Frame* frame,
       graph->AddEdge(in_edge->src(), in_edge->src_output(), while_node, i);
     }
 
-    if (!arg.is_loop_invariant) {
+    if (arg.exit != nullptr && !arg.is_loop_invariant) {
       std::vector<const Edge*> edges(arg.exit->out_edges().begin(),
                                      arg.exit->out_edges().end());
       for (const Edge* edge : edges) {
```

This indeed worked and I have been able to build (even cross-build for ARM/RPi3) a RNN-based network (using `BasicRNN` cells or `BasicLSTM` cells).

So I guess that the questions is really: am I just lucky that it works because one `Switch` MUST really have an `Exit` node (and thus, is there something wrong in the current model), or is it just being picky ?

**Comment by lissyx** [comment]
Looks like I should have had a more close look at issue #11275

**Comment by carlthome** [comment]
@lissyx did you manage to solve this?

**Comment by lissyx** [comment]
Short answer, yes. Long answer I has to work on some TaskCluster bits to have more tooling, and there are still issues related to upstream but I managed to get it working even with ARM cross compilation targeting RPi3.
