### ISSUE TITLE
how to assign a tensor to a sub part of another tensor

### ISSUE THREAD

**Issue by sun-peach** [tensorflow/tensorflow#11755]
Hi, dear all,

I am new to tensorflow. Previously I use theano. Now I want to assign a tensor to a sub part of another tensor. e.g.:

a = 
[[0,0,0,0],
[0,0,0,0],
[0,0,0,0],
[0,0,0,0]]
b = 
[[1],
[3],
[4].
[5]]
I would assign to a[0,:], like this
a = 
[[1,0,0,0],
[3,0,0,0],
[4,0,0,0],
[5,0,0,0]]
in theano we use set_subtensor, what should I do with tensorflow? Thank you very much!

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
