### ISSUE TITLE
app crashed on android device of api level = 19 when load library "libtensorflow_inference.so"

### ISSUE THREAD

**Issue by scucheri** [tensorflow/tensorflow#11774]
### System information
- Os version 4.4.4
-sdk level 19

### logcat:
07-26 15:01:59.429 6521-6521/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: al.omid.tfdroid, PID: 6521
                                                 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rand" referenced by "libtensorflow_inference.so"...
                                                     at java.lang.Runtime.loadLibrary(Runtime.java:364)
                                                     at java.lang.System.loadLibrary(System.java:526)
                                                     at al.omid.tfdroid.MainActivity.<clinit>(MainActivity.java:28)
                                                     at java.lang.Class.newInstanceImpl(Native Method)
                                                     at java.lang.Class.newInstance(Class.java:1208)
                                                     at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2114)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:143)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1209)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5120)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
                                                     at dalvik.system.NativeStart.main(Native Method)
07-26 15:02:01.179 6521-6521/al.omid.tfdroid W/System.err:     at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:94)

### Describe the problem
Could  you pleas tell me how can I solve this ?  Is "libtensorflow_inference.so" usable for android devices of api level < 20 ?

**Comment by jubjamie** [comment]
Are you using only the library or are you trying to use the demo app? IIRC the demo app uses Camera2 so needs >21 but the actual library only requires >14.

[Perhaps this comment chain](https://github.com/tensorflow/tensorflow/issues/6763#issuecomment-272529963) from @andrewharp on #6763 will help you.

**Comment by scucheri** [comment]
I only used the library. I guess it's because I used an old version library file.  It runs ok now when I use library of version r1.2. Thank you very much ~  

BTW, I want to ask another question: I see some android example using tensorflow. For example, mnist and de demo app of tensorflow classifier,  They all need to write some c code and generate a new .so file containing both c code written by developer and tensorflow library so.

 Is it necessary to write c code and generate a custom .so file when implement a complicate deep learning task ? 

 And how can I build my own c code together with tensorflow library .so file to generate a new one ?

Hope for your answer . Thank you so much ~

**Comment by jubjamie** [comment]
Ah that was going to be my next question because your issue appeared to be fixed in a later release! I've not got around to writing my own android libraries. That might not necessarily be required to create your own program. A lot of it can be done in android/java itself and you can use the inference library for when it's needed. I don't think it contains every op however so there might be some extra work to add in something which you need. 

Perhaps you can find some more information here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/android

I'll let someone else answer your questions properly as I don't have the experience. Good luck!

**Comment by andrewharp** [comment]
@scucheri: @jubjamie is correct, you should be able to accomplish almost any inference task (i.e. non-training) using the Java API and TensorFlowInferenceInterface.java similarily to the examples in the Android demo. You can use the prebuilt Android TF binaries in almost all cases unless you need to add new custom ops.

For further support on non-bug/feature requests we suggest referring your questions to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) as there is a larger community there. Thanks!

**Comment by andrewharp** [comment]
Note that https://github.com/tensorflow/tensorflow/pull/10771, which adds camera 1 support, should enable the demo to run on devices < API 21.

**Comment by scucheri** [comment]
Thank you ~
 
I had post this question here : [](https://stackoverflow.com/questions/45340713/is-it-necessary-to-write-c-code-and-generate-a-custom-so-file-when-use-tensorfl/45340732#45340732)

**Comment by jakiechris** [comment]
i run into the same issue last week , and it has been solved . 
any question about cross compile tensor to mobile can contact me, i'm willing to help others cause google members and other guys always helps me.
here's my way for solving this issue:

target:
 i'm using c++ interface and cross compile to ios \ android \ linux \ ...  , and let the app call the interface. android is using jni to call c++ interface. 

steps:

1  for android 4.4, we need ndk r12b and api level 14 , my android colleague tells  me that 19 is also for android 4.4, well i didn't try it, i tested api level 14 and it works for android 4.4 \ 6.0 \ 7.0

2  modify the Makefile file in folder contrib/makefile:
        modify:  --sysroot $(NDK_ROOT)/platforms/android-21/arch-arm \
        to :         --sysroot $(NDK_ROOT)/platforms/android-14/arch-arm \
        
3  modify the compile_android_protobuf.sh file in folder contrib/makefile:
        modify:  android_api_version="${ANDROID_API_VERSION:-21}"
        to :         android_api_version="${ANDROID_API_VERSION:-14}"
 
4 run build_all_android.sh to compile tensorflow and protobuf(which depended by tensorflow).
   also see https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile for detail 

5 get the .h file and .so file .

in my circumstance, i packeted tensorflow lib to my own lib project , pls aware that my own lib set api level to 19, my own lib also can set to 14.  Theoretically libs in level 19 can call libs in level 14, and 14 cannot call 19.  And also aware that api level above 19 is not support android 4.4.

**Comment by malik-anhar** [comment]
Hi @jakiechris , how about to build the aar by using docker? I'm trying to use lower NDK version but getting some error like
```
ERROR: /tmpfs/bazel_output/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/external/androidndk/BUILD.bazel:43:18: Traceback (most recent call last):
	File "/tmpfs/bazel_output/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/external/androidndk/BUILD.bazel", line 41
		cc_toolchain_suite(<2 more arguments>)
	File "/tmpfs/bazel_output/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/external/androidndk/BUILD.bazel", line 43, in cc_toolchain_suite
		{"arm64-v8a": ":aarch64-linux-android-4.9-gnu-libstdcpp", "arm64-v8a|gcc-4.9": ":aarch64-linux-android-4.9-gnu-libstdcpp", "arm64-v8a": ":aarch64-linux-android-clang3.8-gnu-libstdcpp", "arm64-v8a|clang3.8": ":aarch64-linux-android-clang3.8-gnu-libstdcpp", "armeabi": ":arm-linux-androideabi-4.9-gnu-libstdcpp", "armeabi|gcc-4.9": ":arm-linux-androideabi-4.9-gnu-libstdcpp", "armeabi-v7a": ":arm-linux-androideabi-4.9-v7a-gnu-libstdcpp", "armeabi-v7a|gcc-4.9": ":arm-linux-androideabi-4.9-v7a-gnu-libstdcpp", "armeabi": ":arm-linux-androideabi-clang3.8-gnu-libstdcpp", "armeabi|clang3.8": ":arm-linux-androideabi-clang3.8-gnu-libstdcpp", "armeabi-v7a": ":arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp", "armeabi-v7a|clang3.8": ":arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp", "mips64": ":mips64el-linux-android-4.9-gnu-libstdcpp", "mips64|gcc-4.9": ":mips64el-linux-android-4.9-gnu-libstdcpp", "mips64": ":mips64el-linux-android-clang3.8-gnu-libstdcpp", "mips64|clang3.8": ":mips64el-linux-android-clang3.8-gnu-libstdcpp", "mips": ":mipsel-linux-android-4.9-gnu-libstdcpp", "mips|gcc-4.9": ":mipsel-linux-android-4.9-gnu-libstdcpp", "mips": ":mipsel-linux-android-clang3.8-gnu-libstdcpp", "mips|clang3.8": ":mipsel-linux-android-clang3.8-gnu-libstdcpp", "x86": ":x86-4.9-gnu-libstdcpp", "x86|gcc-4.9": ":x86-4.9-gnu-libstdcpp", "x86": ":x86-clang3.8-gnu-libstdcpp", "x86|clang3.8": ":x86-clang3.8-gnu-libstdcpp", "x86_64": ":x86_64-4.9-gnu-libstdcpp", "x86_64|gcc-4.9": ":x86_64-4.9-gnu-libstdcpp", "x86_64": ":x86_64-clang3.8-gnu-libstdcpp", "x86_64|clang3.8": ":x86_64-clang3.8-gnu-libstdcpp"}
Duplicated key "arm64-v8a" when creating dictionary
```
Here is the configuration i used
```
ENV ANDROID_API_LEVEL 14
ENV ANDROID_NDK_API_LEVEL 12
ENV ANDROID_NDK_FILENAME android-ndk-r12b-linux-x86_64.zip
```
the rest is just the same as in [here](https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/dockerfiles/tflite-android.Dockerfile)
