### ISSUE TITLE
tf.contrib.data.Dataset filter documentation broken

### ISSUE THREAD

**Issue by JohnScolaro** [tensorflow/tensorflow#11770]
With the old input pipeline functions, in tf.train.batch() you could specify the "allow_smaller_final_batch" parameter, which would allow or disallow a smaller final batch. With the new input pipeline functions in tf.contrib.data, the batch function allows a smaller final batch by default, and (to the best of my knowledge) there is no way to skip this last half-batch to ensure all batch sizes are equal.

Is there a possibility that a "allow_smaller_final_batch" flag could be added to the new batch function?

**Comment by vrv** [comment]
My guess is that this is more cleanly accomplished using the filter() method on Dataset, where the predicate is one that checks that tf.shape(value)[batch_dim] == batch_size.  So something like

dataset = .. your dataset
dataset = dataset.filter(lambda t: tf.equal(tf.shape(t)[0], batch_size))

and then your iterator will only yield values where the Tensor matches the expected batch size.

**Comment by JohnScolaro** [comment]
Thanks a bunch @vrv. That does exactly what I wanted it too, and much neater than just catching an exception and not training on that specific batch.

It might be worth bringing this up though: The reason I wasn't able to find the filter function is because the file located [here](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/contrib/data/python/ops/dataset_ops.py) is missing a ``` to end the code example, and (on line 632) and this has included the filter function in the Enumerate sections code, rendering it unsearchable. [See here](https://www.tensorflow.org/api_docs/python/tf/contrib/data/TFRecordDataset#enumerate)

Is this something that can be fixed?

Thanks again for the help.

**Comment by vrv** [comment]
Definitely, I'll retitle the bug accordingly!  I'll also point you towards the following, which is also a helpful reference:  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/programmers_guide/datasets.md

**Comment by dr4b** [comment]
Hey, this specific bug has been fixed by the deprecation of enumerate() to enumerate_dataset()

(see here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/data/python/ops/enumerate_ops.py)

So I'm closing this out unless there's a reason to keep it open?
