### ISSUE TITLE
Add support for XLA cross products

### ISSUE THREAD

**Issue by fxsuper** [tensorflow/tensorflow#11788]
XLA currently supports basic trigonometric operations but does not natively support cross products. Cross products are fundamental to many geometric operations, and TF has a `tf.cross` function. Note relevant discussion in #8315 ([comment](https://github.com/tensorflow/tensorflow/issues/8315#issuecomment-317947166)), and preliminary work [here](https://gist.github.com/learyg/4019bae1cfc5bacbcdb318fd882b4d5d).

**Comment by learyg** [comment]
So it seems like there's not a mechanism for desugaring Python tf.cross directly to the Python you provided, but we *can* go implement it in the tf2xla bridge along these lines. I'll take a shot at that.

**Comment by learyg** [comment]
Submitting an implementation and tests downstream, should be available in the next merge.

**Comment by fxsuper** [comment]
Fantastic. I look forward to it!

**Comment by learyg** [comment]
Landed in 32e198f2d5787ca81aba89bf073e4eb380769253

Thanks for filing! Let us know if you have other issues.
