### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [tensorflow/tensorflow#1178]
Would you like to [replace any double quotes](https://github.com/tensorflow/tensorflow/blob/31849e0a44a1c9c99c4524a65c9ee90e80c41499/tensorflow/core/common_runtime/device.h#L35 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by martinwicke** [comment]
Hm... since the tensorflow include files are not usually placed in the system directory (yet), that would be the wrong thing to do. However, as we create deb packages that actually install headers into system paths, we should do it. @josh11b, opinions?

**Comment by girving** [comment]
I'd agree that we should use angle brackets outside Google.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by girving** [comment]
@josh11b: Opinions?  This might only matter in the future when the C++ API stabilizes.

**Comment by josh11b** [comment]
I've been at Google too long to know what the rest of the world expects, but I could imagine the regexp that would do this if we decide it is a good idea.  Would this just be for examples, or inside the core library?  Manjunath would probably be a better person to ask.

**Comment by keveman** [comment]
@elfring Can you please clarify a few things? What ARE the "consequences" of the wording that you point to? i.e., can you give an example of what could go wrong if TensorFlow continues to use double quotes for header inclusion? Also, what do you mean by "duplicated file search"?

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
* Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?

**Comment by keveman** [comment]
@elfring Thanks a lot for bringing this to our notice. Those two issues are not high priority for us now, and unlikely to be the case in the foreseeable future. I am closing this issue for now. If we do see a real bug due to the double quotes inclusion in the future, we will definitely re-visit this, and of course we know whom to consult :)

**Comment by elfring** [comment]
Can you imagine use cases where you would like to exclude the search in "local" directories?
