### ISSUE TITLE
CUDA_ERROR_LAUNCH_FAILED when using conv2d/max_pool on Tensorflow GPU (Windows 10)

### ISSUE THREAD

**Issue by rktamplayo** [tensorflow/tensorflow#11782]
When using conv2d and/or max_pool, the error below shows and stops the code. I used the code available here: [https://github.com/dennybritz/cnn-text-classification-tf](https://github.com/dennybritz/cnn-text-classification-tf)

```
2017-07-26 21:41:27.467585: E c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\stream_executor\cuda\cuda_driver.cc:1068] failed to synchronize the stop event: CUDA_ERROR_LAUNCH_FAILED
2017-07-26 21:41:27.467797: E c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\stream_executor\cuda\cuda_timer.cc:54] Internal: error destroying CUDA event in context 000001178B37E810: CUDA_ERROR_LAUNCH_FAILED
2017-07-26 21:41:27.468679: E c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\stream_executor\cuda\cuda_timer.cc:59] Internal: error destroying CUDA event in context 000001178B37E810: CUDA_ERROR_LAUNCH_FAILED
2017-07-26 21:41:27.469846: F c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\stream_executor\cuda\cuda_dnn.cc:2479] failed to enqueue convolution on stream: CUDNN_STATUS_EXECUTION_FAILED
```

**What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?**

I have searched through all websites including GitHub and StackOverflow, and these two are the most relevant results and why they did not help:

1. [https://github.com/tensorflow/tensorflow/issues/6783](https://github.com/tensorflow/tensorflow/issues/6783) - The issue pertains to tf.one_hot. Is this function used in either one of the functions above? The issue seems to be not solved too. I tried using the code on a Linux/GPU and on a Windows/CPU setting as well and it worked.
2. [https://github.com/dennybritz/cnn-text-classification-tf/issues/90](https://github.com/dennybritz/cnn-text-classification-tf/issues/90) - They kind of 'resolved' the issue by reducing the batch size. I tried this and it worked, but it does not make sense. For one thing, I tried using the code on another Windows machine with an older GPU and it works well.

**Environment info**

- Tensorflow 1.2.1
- Python 3.5.3
- CUDA 8.0
- cuDNN 5.1
- OS: Windows 10
- GPU: GeForce GTX 1060

[EDITED] edited the links

**Comment by aselle** [comment]
The link you provided does not work for me. Could you provide a minimal reproducible test case? Are other models working? Could it be that your driver / cuda toolkit need updating?

**Comment by rktamplayo** [comment]
Hey. I forgot to include the links themselves. They should be fixed now.

Other models (such as LSTMs, etc.) are working fine. The [original theano version](https://github.com/yoonkim/CNN_sentence) of the code works well too. I have my CUDA and cuDNN updated to the latest version (as specified)

A reproducible test case would be:

```
input_x = tf.placeholder(tf.int32, [None, sequence_length], name="input_x")

embedding = tf.Variable(tf.random_uniform([vocab_size, embedding_size], -0.1, 0.1), name="embedding")
embedded_chars = tf.nn.embedding_lookup(embedding, input_x)
embedded_chars_expanded = tf.expand_dims(embedded_chars, -1)

W = tf.Variable(tf.truncated_normal(filter_shape, stddev=0.1), name="W")
b = tf.Variable(tf.constant(0.0, shape=[num_filters]), "b")
conv = tf.nn.conv2d(
                embedded_chars_expanded,
                W,
                strides=[1, 1, 1, 1],
                padding="VALID",
                name="conv")
h = tf.nn.relu(tf.nn.bias_add(conv, b), name="relu")
pooled = tf.nn.max_pool(
                h,
                ksize=[1, sequence_length-filter_size+1, 1, 1],
                strides=[1, 1, 1, 1],
                padding="VALID",
                name="pool")
```

However, I cannot seem to reproduce this issue on other machines. Although [some people](https://github.com/dennybritz/cnn-text-classification-tf/issues/90) experienced this error before too.

**Comment by aselle** [comment]
If you try it in other machines, do those other machines have the same gpu and driver versions. You might swap the working card from another machine to this one. Otherwise, I don't really have any other ideas. Perhaps @mrry, knows something I don't.

**Comment by rktamplayo** [comment]
I am working on a laptop (MSI GS73VR), so swapping the GPU card may be impossible..

The other machines I have tested have the same driver versions, but with different (older) GPUs.

**Comment by rktamplayo** [comment]
Oh wait, I just saw the Tensorflow 1.3.0 release with cuDNN 6 support. I upgraded TF and cuDNN to the latest versions and solved the issue.

Thanks!
