### ISSUE TITLE
bitwise_ops and gen_bitwise_ops cannot be imported

### ISSUE THREAD

**Issue by PiyushDatta** [tensorflow/tensorflow#11798]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 7
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.1.0
- **Python version**:  3.5.3
- **CUDA/cuDNN version**: 8.0.60
- **GPU model and memory**:  NVIDIA GeForce GT 730
- **Exact command to reproduce**:

In the bitwise_ops_test.py file, located in the ops folder in python, this code is there:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import six

from tensorflow.python.framework import constant_op
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import test_util
from tensorflow.python.ops import bitwise_ops
from tensorflow.python.ops import gen_bitwise_ops
from tensorflow.python.platform import googletest
```

These two lines are giving an error:

```
from tensorflow.python.ops import bitwise_ops
from tensorflow.python.ops import gen_bitwise_ops
```

I get an import error saying:

```
from tensorflow.python.ops import bitwise_ops
ImportError: cannot import name 'bitwise_ops'
```

Also theres no gen_bitwise_ops file in the ops folder, and the method isn't available in the init file.

**Comment by aselle** [comment]
What is the exact command you are running to produce this error? Is this just doing import tensorflow as tf from a python shell?}

**Comment by PiyushDatta** [comment]
I wanted to run bitwise_ops_test.py, which runs this code:
`if __name__ == "__main__":
  googletest.main()`

And no, I'm running it on an IDE, on a anaconda environment.

**Comment by mrry** [comment]
It appears that you are using TensorFlow 1.1.0, but the `tensorflow.python.ops.bitwise_ops` module was added in TensorFlow 1.3. You'll need to upgrade to the latest version of TensorFlow (currently in the release candidate stage) or a nightly build to import that module.
