### ISSUE TITLE
Cannot build Tensorflow: 'GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by kaizhang** [tensorflow/tensorflow#11805]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.2.1
- **Python version**: 3.6.1
- **Bazel version (if compiling from source)**: 0.5.2
- **CUDA/cuDNN version**: 8.0/5.0
- **GPU model and memory**: GTX1080, 8G
- **Exact command to reproduce**: bazel build --verbose_failures --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

### Describe the problem

I cannot build Tensorflow from source. I have gcc libraries installed in "/opt/ohpc/pub/compiler/gcc/5.4.0/lib64". But the installer was not able to pick it up. It always tries to use the one in "/usr/lib64". I have set "LDFLAGS" "LD_LIBRARY_PATH", etc. Nothing works.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

$ bazel build --verbose_failures --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

WARNING: ignoring http_proxy in environment.
WARNING: Output base '/home/kai/.cache/bazel/_bazel_kai/e5757f5d9b24da3fc563b551b579ddc3' is on NFS. This may lead to surprising failures and undetermined behavior.
WARNING: /home/kai/test/tensorflow-1.2.1/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/kai/test/tensorflow-1.2.1/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
ERROR: /home/kai/test/tensorflow-1.2.1/tensorflow/contrib/training/BUILD:339:1: null failed: protoc failed: error executing command
  (cd /home/kai/.cache/bazel/_bazel_kai/e5757f5d9b24da3fc563b551b579ddc3/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/protobuf/protoc '--python_out=bazel-out/local_linux-py3-opt/genfiles/' -I. -Iexternal/protobuf/python -Ibazel-out/local_linux-py3-opt/genfiles/external/protobuf/python tensorflow/contrib/training/python/training/hparam.proto): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/home/kai/.cache/bazel/_bazel_kai/e5757f5d9b24da3fc563b551b579ddc3/execroot/org_tensorflow/_bin/process-wrapper: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/kai/.cache/bazel/_bazel_kai/e5757f5d9b24da3fc563b551b579ddc3/execroot/org_tensorflow/_bin/process-wrapper)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3.922s, Critical Path: 0.03s

**Comment by reedwm** [comment]
This seems similar to #3261. Can you try the workarounds described [here](https://github.com/tensorflow/tensorflow/issues/3261#issuecomment-234147379) or [here](https://github.com/bazelbuild/bazel/issues/1358#issuecomment-258501870)?

@martinwicke any thoughts? Similar issues (#3261, bazelbuild/bazel#1358, bazelbuild/bazel#898) have been posted before.

**Comment by kaizhang** [comment]
I had read this before posting the issue. But no, it did work. Also the file `third_party/gpus/crosstool/CROSSTOOL` no longer exists. I tried both `third_party/gpus/crosstool/CROSSTOOL_nvcc.tpl` and `third_party/gpus/crosstool/CROSSTOOL_clang.tpl`, but none of them worked.

**Comment by kaizhang** [comment]
Right now I can use the pip wheel. So I don't need workarounds here, at least now. If this is an intended behavior or you know how to fix this in future release, feel free to close it. Otherwise, let me know what I can help.

**Comment by martinwicke** [comment]
This is an issue with bazel not picking up the right environment -- I don't believe we can fix this on the TF side. I'll close this issue.
