### ISSUE TITLE
Installation Issue 0.7

### ISSUE THREAD

**Issue by newterminator** [tensorflow/tensorflow#1180]
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

### Environment info
Operating System:
**Ubuntu 14.04**

**Python 2.7.11**

If installed from binary pip package, provide:

1. Which pip package you installed.
```
Name: pip
Version: 8.0.2
```
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/noname/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/noname/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/noname/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/noname/tensorflow/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/noname/tensorflow/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: /home/noname/tensorflow/lib/python2.7/site-packages/google/protobuf/pyext/_message.so: undefined symbol: PyUnicodeUCS4_FromEncodedObject


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```
If installed from sources, provide the commit hash:

### Steps to reproduce
1. ```pip install --upgrade virtualenv```

2. ```virtualenv --system-site-packages ~/tensorflow```

3. Download Cuda Toolkit v 7.5 from: http://developer.download.nvidia.com/compute/cuda/7.5/Prod/local_installers/cuda-repo-ubuntu1404-7-5-local_7.5-18_amd64.deb

4. Install cuda toolkit 7.5:
```sudo dpkg -i cuda-repo-ubuntu1404-7-5-local_7.5-18_amd64.deb```
`sudo apt-get update`
`sudo apt-get install cuda`

5. Download cuDNN v4: https://developer.nvidia.com/rdp/assets/cudnn-70-linux-x64-v40

6.  Followed by: 
`tar xvzf cudnn-7.0-linux-x64-v4.0-prod.tgz`
`sudo cp cuda/include/cudnn.h /usr/local/cuda/include`
`sudo cp cuda/lib64/libcudnn* /usr/local/cuda/lib64`
`sudo chmod a+r /usr/local/cuda/lib64/libcudnn*  `

7. Add the following to the end of ~/.bashrc file:
```export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64" ```
```export CUDA_HOME=/usr/local/cuda ```

8. Activate the Virtualenv environment created in step 2: ```source ~/tensorflow/bin/activate ```

9. Finally install tensorflow with GPU support enabled: ```pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.0-py2-none-linux_x86_64.whl```

### What have you tried?
1. I have tried to test the tensorflow installation as described here: https://www.tensorflow.org/versions/r0.7/get_started/os_setup.html#test-the-tensorflow-installation
and it gives me the same import error as above.
2. I deleted all of the virtual folder (incl contents) and removed cuda toolkit and cudNN and installed them, repeating 3 times, but it doesn't seem to go pass the import error. 

Please if anyone could help out, a whole lot of time has gone by with this ...

**Comment by vrv** [comment]
can you try pip install protobuf==3.0.0b2 ?

**Comment by newterminator** [comment]
Hey @vrv  Vijay, thanks for looking into my issue and responding. I did like you mentioned 'pip install protobuf==3.0.0b2' but its still the same error...

**Comment by vrv** [comment]
A similar error at https://github.com/psi4/psi4/issues/94 seems to suggest an issue due to mixed versions of python.  You might want to install from sources rather than using our wheels, at least until we can figure this out more generally.

**Comment by newterminator** [comment]
Hi @vrv Vijay, Thanks for searching the issue and responding so quickly. So I will go ahead and install it from the source. On a side note, I just installed the cpu version with Virtualenv environment on my mac laptop and there are no errors on testing the installation.

**Comment by newterminator** [comment]
@vrv Vijay, Just to add on to the page, since the link mentions about different python versions, and it suggests to check `which python` and `which python-config`. 
And this is what I got when I do in the active environment: 
```
(tensorflow) noname@noname-desktop:~/Downloads/software$ which python
/home/noname/tensorflow/bin/python
(tensorflow) noname@noname-desktop:~/Downloads/software$ which python-config
/home/noname/tensorflow/bin/python-config
```
And then this is the output outside the environment:
```
noname@noname-desktop:~$ which python
/home/noname/.linuxbrew/bin/python
noname@noname-desktop:~$ which python-config
/home/noname/.linuxbrew/bin/python-config
```

**Comment by newterminator** [comment]
I wanted to add that I was able to successfully install and test Tensorflow version 0.6 with Cuda toolkit version 7.0 and cudNN v2.
However, when I upgraded to version 0.7 with Cuda toolkit version 7.0 and cudNN v2, I get the same import error as stated in the beginning of this issue.
Attached is the image for confirmation of Tensorflow version 0.6 working.

![selection_001](https://cloud.githubusercontent.com/assets/5087437/13186653/33c7f662-d715-11e5-8f6b-23ab4e45f3a8.png)

**Comment by vrv** [comment]
Ok try our new 0.7.1 wheel (cleanly uninstall tensorflow 0.7.0 and protobuf, then install 0.7.1).  The pip installation requires cudnn v4 though.  Otherwise you'll need to install from sources.

**Comment by newterminator** [comment]
Hi @vrv Vijay, I did exactly as you recommended, and hey hey hey its working...What an excellent start to the week. Thanks so much for clearing up the issue. Great work!

**Comment by sergeyf** [comment]
Thanks @vrv this also worked for me.
