### ISSUE TITLE
tensorflow.gfile.Open() error with MNIST example in python 3.4

### ISSUE THREAD

**Issue by hemanthdv** [tensorflow/tensorflow#1181]
The `tf.gfile.Open(filename)` function throws an error when a bytestream is read. The issue arises in tensorflow/examples/tutorials/mnist using python 3.4

### Environment info
Operating System:
Ubuntu LTS 14.04 64bit

1. pip package installed: 
`sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.0-cp34-none-linux_x86_64.whl`
2. The output from python -c "import tensorflow; print(tensorflow.__version__)". 
`python3 -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.7.0
`
### Steps to reproduce
Run the mnist example in tensorflow with python3
`from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)`

### Steps to overcome
Got rid of the tf.gfile.Open function call. Replaced the line:
`with tf.gfile.Open(filename) as f, gzip.GzipFile(fileobj=f) as bytestream:`
with
`with gzip.GzipFile(filename=filename) as bytestream:`

### Logs
`Extracting MNIST_data/train-labels-idx1-ubyte.gz`
`Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.`
`Extracting MNIST_data/train-images-idx3-ubyte.gz`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/local/lib/python3.4/dist-packages/tensorflow/examples/tutorials/mnist/input_data.py", line 202, in read_data_sets`
`    train_images = extract_images(local_file)`
`  File "/usr/local/lib/python3.4/dist-packages/tensorflow/examples/tutorials/mnist/input_data.py", line 58, in extract_images`
`    magic = _read32(bytestream)`
`  File "/usr/local/lib/python3.4/dist-packages/tensorflow/examples/tutorials/mnist/input_data.py", line 51, in _read32`
`    return numpy.frombuffer(bytestream.read(4), dtype=dt)[0]`
`  File "/usr/lib/python3.4/gzip.py", line 365, in read`
`    if not self._read(readsize):`
`  File "/usr/lib/python3.4/gzip.py", line 433, in _read`
`    if not self._read_gzip_header():`
`  File "/usr/lib/python3.4/gzip.py", line 292, in _read_gzip_header`
`    magic = self.fileobj.read(2)`
`  File "/usr/lib/python3.4/gzip.py", line 90, in read`
`    self.file.read(size-self._length+read)`
`  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/default/_gfile.py", line 45, in sync`
`    return fn(self, *args, **kwargs)`
`  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/default/_gfile.py", line 199, in read`
`    return self._fp.read(n)`
`  File "/usr/lib/python3.4/codecs.py", line 319, in decode`
`    (result, consumed) = self._buffer_decode(data, self.errors, final)`
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte`

**Comment by vrv** [comment]
This was fixed in 555e73da8f171992085c68614f74b23b8180292c, which we will hopefully cherry-pick to 0.7.1 soon.

**Comment by hemanthdv** [comment]
Thank you @vrv

**Comment by vrv** [comment]
We have some new candidate wheels that have the fix here: https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/g3doc/get_started/os_setup.md -- let us know if those are good for you.

**Comment by hemanthdv** [comment]
Thank you @vrv
