### ISSUE TITLE
Looks like a bug tensorflow 1.2.1 with gpu error during basic_gpu_test

### ISSUE THREAD

**Issue by shirishr** [tensorflow/tensorflow#11817]
### System information
- **No custom code
- **OS Windows 10
- **TensorFlow installed from:https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.2.1-cp35-cp35m-win_amd64.whl
- **TensorFlow version (use command below)**: 1.2.1
- **Python version**: 3.5 (Anaconda environment)
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**:
- **Exact command to reproduce**: python basic_gpu_test.py

The trace:

.....C:\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\test_util.py:591: RuntimeWarning: invalid value encountered in greater
  np.abs(a - b) > atol + rtol * np.abs(b), np.isnan(a) != np.isnan(b))
not close where =  (array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))
not close lhs =  []
not close rhs =  []
not close dif =  []
not close tol =  []
dtype = float32, shape = (1, 3, 5)
......E.
======================================================================
ERROR: testTypes (__main__.MathBuiltinUnaryTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basic_gpu_test.py", line 136, in testTypes
    self._testDtype(dtype, use_gpu=True)
  File "basic_gpu_test.py", line 114, in _testDtype
    self._compare(data, np.arcsinh, math_ops.asinh, use_gpu)
AttributeError: module 'tensorflow.python.ops.math_ops' has no attribute 'asinh'

----------------------------------------------------------------------
Ran 13 tests in 12.158s

FAILED (errors=1)

**Comment by shirishr** [comment]
Same error is associated with
acosh, cosh, sinh, atanh

as well.

**Comment by reedwm** [comment]
You should run tests with bazel instead of directly running the .py files.

For example, to run `tensorflow/python/kernel_tests/basic_gpu_test.py`:
```
bazel test --config=opt --config=cuda  tensorflow/python/kernel_tests:basic_gpu_test
```

**Comment by shirishr** [comment]
I am on windows platform...I did install chocolatey (which installed python 2.7 outside of conda) and then installed bazel which failed because in windows I have msys2_shell.bat (and not msys2.exe)
So a generally futile exercise. I commented out the 5 lines associated with asinh, acosh, cosh, sinh, atanh from basic_gpu_test to make sure that my gpu is playing nicely with tensorflow_gpu.
Thank you for your help though.
Looks like none of these tools (chocolately, bazel and for that matter even CUDA are not meant for Windows. Looks like my next machine must be Ubuntu with CUDA.
Thanks for your help (I think) though.

**Comment by aselle** [comment]
@gunan, is there anyway to run the tests using the easier to use cmake build?

**Comment by gunan** [comment]
While the recommended way is to use bazel, most of our tests "should" run without bazel, just by running `python <filename>`.
For the equivalent of what we are running on our CI for windows, you may check this script:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build/windows/gpu/cmake

**Comment by shirishr** [comment]
Thank you gunan,

That is exactly how I ran the test:


>>>python basic_gpu_test.py


and that is how I got the error message described in the issue.

No big deal..I commented the line out. and..commented out every line that lead to similar error.


I was only interested in checking if my gpu is working at all. The test (with few lines commented out) did tell me it was working alright.


I felt obliged to let wonderful people at google that asinh (and 4 other functions) is not being supported by tensor 1.2.1


Feel free to ignore it


Bye for now,
Shirish


________________________________

**Comment by gunan** [comment]
To check if my GPU is working or not, I like to use `tf.test.is_gpu_available()` method.
This only checks if the GPU is accessible. The computations are still best checked by unit tests.

**Comment by shirishr** [comment]
Thank you sir !

Will try that out !!

Bye for now,
Shirish


________________________________

**Comment by aselle** [comment]
Thanks gunan
