### ISSUE TITLE
Snappy related tests are failing

### ISSUE THREAD

**Issue by duane-ibm** [tensorflow/tensorflow#11816]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 'v1.2.1-0-gb4957ff', '1.2.1'
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: No GPU
- **GPU model and memory**: No GPU
- **Exact command to reproduce**: bazel test //tensorflow/core:lib_io_snappy_snappy_buffers_test

### The problem:
While executing test `TEST(SnappyBuffers, MultipleWritesWithoutFlush)`. It fails when `Snappy_Uncompress()` method is called which internally calls `snappy::RawUncompress()`.
Compared the same on intel x86 where it works fine; However the data somehow gets lost on s390x.

I am aware that Snappy behaves differently on s390x as compared to others.

There is another test `//tensorflow/core:lib_io_table_test` which fails when snappy compress/uncompress is used.
Would like to know if the mentioned test-cases are used to test some complex functionality of TensorFlow? Can they be ignored?

### Source code / logs
Running main() from test_main.cc
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from SnappyBuffers
[ RUN      ] SnappyBuffers.MultipleWritesWithoutFlush
2017-07-27 12:25:34.898300: F tensorflow/core/lib/io/snappy/snappy_buffers_test.cc:148] Non-OK-status: TestMultipleWrites(10000, 10000, 10000, 10000, 2) status: Data loss: Snappy_Uncompress failed
external/bazel_tools/tools/test/test-setup.sh: line 159: 17664 Aborted                 (core dumped) "${TEST_PATH}" "$@"

**Comment by aselle** [comment]
Most likely it is a big-endian vs little endian issue in snappy buffers.  As usual, we don't really have a great way to debug this, but you should be able to look at the code and find raw buffer interpretations that need endian swaps included for the big-endian case.

**Comment by rposts** [comment]
This problem no longer appears in TF 2.3.1.

**Comment by sushreebarsa** [comment]
@duane-ibm Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks !
