### ISSUE TITLE
Slow to import tensorflow.contrib with Python 3 because inspect.stack is slow

### ISSUE THREAD

**Issue by patrikerdes** [tensorflow/tensorflow#11829]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sierra 10.12.5
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.2.0-2420-g2b4a0f9a4 1.3.0-rc0
- **Python version**: 3.6.2
- **Bazel version (if compiling from source)**: 0.5.2-homebrew
- **CUDA/cuDNN version**: CPU only build
- **GPU model and memory**: CPU only build
- **Exact command to reproduce**: time python3 -c "import tensorflow.contrib"

### The problem
Doing `import tensorflow.contrib` take 7.5 seconds on my machine when doing it with Python 3.6.2. With Python 2.7.13 it takes 3.2 seconds.

Investigating this revealed that a lot of time is spent in `_inspect.stack()` in the function `make_decorator` in  `python/util/tf_decorator.py`. The stack is inspected to find the name of the caller of the function. With Python2 `inspect.stack()` is fast, but with Python 3 each call to `inspect.stack()` take approximately 0.2 seconds and there are 23 calls made, which account for the difference in time between Python 2 and 3.

### References
Keras by default imports tensorflow.contrib when the Tensorflow backend is used. Therefore Keras is slow to import when using Python 3: https://github.com/fchollet/keras/issues/7408

There is a stackoverflow question referencing this issue: https://stackoverflow.com/questions/45093653/import-tensorflow-contrib-module-is-slow-in-tensorflow-1-2-1

**Comment by poxvoculi** [comment]
Is this PR also useful?  https://github.com/tensorflow/tensorflow/pull/11919
Waiting on this PR: https://github.com/tensorflow/tensorflow/pull/11830

**Comment by konstunn** [comment]
I use TensorFlow and PythonTeX to make reproducible dynamic reports. Every time I update the code chunk that uses `tf.contrib` I have to wait about 10 seconds till the module is imported. It's so annoying. Fix it, please or suggest temporary workaround to speed up this import.

**Comment by drpngx** [comment]
@konstunn did you sync past #11829?

**Comment by konstunn** [comment]
@drpngx not sure. Should I install from sources? I used to install TensorFlow from PyPI.

**Comment by drpngx** [comment]
Ah, yes, you have to install from source and pull from head. Alternatively, you can use a binary that we distribute. We're releasing release candidates for 1.4, which is the next version. Closer to cutting edge are (assuming you have a GPU): https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/
There's a corresponding CPU version.

**Comment by konstunn** [comment]
Thanks, I've simply done: `$ sudo -H pip3 install tf-nightly` to install a nightly build from PyPI. Now `import tensorflow.contrib` takes 1.4 seconds to run. An order of magnitude better! Good job!

**Comment by drpngx** [comment]
Woohoo!
