### ISSUE TITLE
Small bug in TensorBoard: Visualizing Learning tutorial [FIXED, pending website pushes]

### ISSUE THREAD

**Issue by robwell** [tensorflow/tensorflow#1182]
There is a small bug in the code on the site: https://www.tensorflow.org/versions/r0.7/how_tos/summaries_and_tensorboard/index.html

b = tf.Variable(tf.zeros([10], name='bias'))
should be:

b = tf.Variable(tf.zeros([10]), name='bias')

The consequence is that when you view the graph, the 'bias' variable has no useful label and is simply Variable.

**Comment by vrv** [comment]
This was fixed earlier today in: https://github.com/tensorflow/tensorflow/commit/5df9ff89a58a17e6efca7f186b57f22430130768

We'll probably amend our docs to fix this eventually.  Going to leave this open until then.

**Comment by yash14123** [comment]
Are the docs fixed? I can take this one to begin with.

**Comment by danmane** [comment]
This is fixed for docs versions later than 0.7. Do we have a policy on backporting documentation fixes to older versions?
@martinwicke want to chime in?

**Comment by danmane** [comment]
FWIW I would be fine just closing this because I don't think many people will find the 0.7 docs.

**Comment by martinwicke** [comment]
@robwell (or anyone else), if you are motivated enough to send a fixing PR against 0.7 we'll happily accept it. But I will close this issue, it's not enough of a problem since it's fixed in 0.8 and master.
