### ISSUE TITLE
tfcompile of tf.sin and tf.cos

### ISSUE THREAD

**Issue by jo89er** [tensorflow/tensorflow#11822]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow version (use command below)**: ('v1.2.0-5-g435cdfc', '1.2.1')
- **Python version**: 2.7.12

### Describe the problem
I tried to use tfcompile for AOT compilation of a graph where are use tf.sin and tf.cos functions.
tfcompile raises following error:
```
E tensorflow/core/common_runtime/executor.cc:594] Executor failed to create kernel. Not found: No registered 'Sin' OpKernel for XLA_CPU_JIT devices compatible with node Sin = Sin[T=DT_FLOAT](alpha/read)
	.  Registered:  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]

	 [[Node: Sin = Sin[T=DT_FLOAT](alpha/read)]]
F tensorflow/compiler/aot/tfcompile_main.cc:140] Check failed: ::tensorflow::Status::OK() == (tensorflow::tfcompile::Main(flags)) (OK vs. Not found: No registered 'Sin' OpKernel for XLA_CPU_JIT devices compatible with node Sin = Sin[T=DT_FLOAT](alpha/read)
	.  Registered:  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]

	 [[Node: Sin = Sin[T=DT_FLOAT](alpha/read)]])
```

**Comment by aselle** [comment]
It looks like xla doesn't support double size complex #'s. Does this happen when you use tf.complex64 instead?
@tatatodd, is anyone working on extending complex support in xla?

**Comment by jo89er** [comment]
This happens when I use any of the float data types.
Using tf.complex64 or tf.complex128 raises:

```
F tensorflow/compiler/aot/tfcompile_main.cc:140] Check failed: ::tensorflow::Status::OK() == (tensorflow::tfcompile::Main(flags)) (OK vs. Invalid argument: Unsupported type in DataTypeToPrimitiveType complex64)
```
```
F tensorflow/compiler/aot/tfcompile_main.cc:140] Check failed: ::tensorflow::Status::OK() == (tensorflow::tfcompile::Main(flags)) (OK vs. Invalid argument: Unsupported type in DataTypeToPrimitiveType complex128)
```

**Comment by learyg** [comment]
FYI I believe sin/cos for floating types should be supported now, but I don't know that complex types are currently supported by the tf2xla bridge.

**Comment by jo89er** [comment]
You are right. I just rebuild tfcompile with the current version of the code.
sin/cos for floating types is supported now.

The complex types are not supported:
```
INVALID ARGUMENTS: Unsupported type in DataTypeToPrimitiveType complex64
```
