### ISSUE TITLE
Fractional 3d Max Pooling

### ISSUE THREAD

**Issue by shamazharikh** [tensorflow/tensorflow#11846]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2.0
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:8/5
- **GPU model and memory**:Nvidia 740M

### Describe the problem
There is a fractional maxpool op for 4D tensors. For medical imaging, data is available in the form of 3d images. Hence a fractional maxpool/avgpool  op for 5D tensors i.e., [batch_size, n_channels, depth, height, width] would be really useful.

**Comment by aselle** [comment]
As far as I know we're not working on this currently, but it would make a useful feature.

**Comment by wuharvey** [comment]
I'd like to try working on this.

**Comment by wuharvey** [comment]
What is the guideline for test coverage? Should I write tests analogous to the 2D op?

**Comment by Riksi** [comment]
@wuharvey Hi did you work on this? If the issue is still open and it would be a useful contribution I am interested in working on it.

**Comment by sushreebarsa** [comment]
@shamazharikh Could you up-sample its 3D data to a higher resolution before applying regular max/avg pooling. This offers some control over the output size but adds computational overhead. Please refer to [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/lite.py)https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/lite.py) doc as well. 
Thank you!
