### ISSUE TITLE
tf.contrib.rnn.static_rnn not found

### ISSUE THREAD

**Issue by jasdeep06** [tensorflow/tensorflow#11844]
I am using tensorflow version 0.12.1 and trying to implement simple RNN using static_rnn.

    lstm_layer=tf.contrib.rnn.LayerNormBasicLSTMCell(n_hidden,forget_bias=1)
    outputs, states = tf.contrib.rnn.static_rnn(lstm_cell, x, dtype=tf.float32)

The IDE is not able to resolve `static_rnn`.

In tensorflow documentation `tf.contrib.rnn.static_rnn` is listed [here](https://www.tensorflow.org/api_guides/python/contrib.rnn).But on clicking on it it redirects to 404 page.Is there a change in `static_rnn` in tensorflow?If yes then whats the new alternative/implementation?

**Comment by anjany** [comment]
You seem to be using an older version of tensorflow. 'contrib' module was introduced after TF1.0, I guess. You can either upgrade to a newer version of TF or use the `tf.nn` module which has what you need.

Any reason why you didn't fill the form?

**Comment by jasdeep06** [comment]
Thanks for the response.My mistake.Pycharm and console show different version of tensorflow.I've resolved it.I was pretty sure it was version problem but pycharm indicated otherwise.
