### ISSUE TITLE
'No module named tensorflow'  error in jupyter notebook after installing tensorflow-gpu using pip in the same virtual environment. I am using python 2.7.12.

### ISSUE THREAD

**Issue by arthitag** [tensorflow/tensorflow#11851]
I am trying to use tensorflow-gpu on Ubuntu16.04. I installed tensorflow via pip inside virtual environment, and other required libraries. When I start jupyter notebook in the same environment and try to run a code that uses tensorflow, the line 'import tensorflow as tf' gives an error. 
It says no module named tensorflow. I had a similar problem with skimage(I initially installed scikit-image instead of python-skimage and I was getting an error. But it got resolved after I installed the right library. However I can't make sense of why it can't find the tensorflow module.

**Comment by arthitag** [comment]
I also tried "import tensorflow-gpu as tf" but it gives an "invalid syntax" error. 
in the terminal, inside the virtual environment for tensorflow, "pip show tensorflow" yields nothing. However "pip show tensorflow-gpu" shows the version information below:
Name: tensorflow-gpu
Version: 1.2.1
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: ~/venv4Tensorflow/lib/python2.7/site-packages
Requires: mock, numpy, bleach, markdown, wheel, six, protobuf, backports.weakref, html5lib, werkzeug

**Comment by arthitag** [comment]
$ pip freeze
adium-theme-ubuntu==0.3.4
backports.shutil-get-terminal-size==1.0.0
backports.weakref==1.0rc1
bleach==1.5.0
configparser==3.5.0
cycler==0.10.0
Cython==0.23.4
decorator==4.0.6
entrypoints==0.2.2
enum34==1.1.6
extractframes==0.16
funcsigs==1.0.2
functools32==3.2.3.post2
h5py==2.7.0
html5lib==0.9999999
imageio==2.2.0
ipykernel==4.6.1
ipython==5.4.1
ipython-genutils==0.2.0
ipywidgets==6.0.0
Jinja2==2.8
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
Markdown==2.6.8
MarkupSafe==0.23
matplotlib==2.0.2
mistune==0.7.4
mock==2.0.0
nbconvert==5.2.1
nbformat==4.3.0
networkx==1.11
nose==1.3.7
notebook==5.0.0
numpy==1.13.1
olefile==0.44
opencv==1.0.1
opencv-python==3.2.0.7
pandocfilters==1.4.1
pathlib2==2.2.1
pbr==3.1.1
pexpect==4.0.1
pickleshare==0.7.4
Pillow==4.1.1
pkg-resources==0.0.0
progressbar==2.3
prompt-toolkit==1.0.14
protobuf==3.3.0
ptyprocess==0.5
pycurl==7.43.0
Pygments==2.2.0
PyMySQL==0.7.2
pyparsing==2.2.0
Pyste==0.9.10
python-apt==1.1.0b1
python-dateutil==2.6.0
pytz==2017.2
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==15.2.0
qtconsole==4.3.0
scandir==1.5
scikit-image==0.13.0
scikit-learn==0.18.1
scikit-video==0.1.2
scipy==0.19.0
simplegeneric==0.8.1
six==1.10.0
sklearn==0.0
subprocess32==3.2.7
tensorflow-gpu==1.2.1
terminado==0.6
testpath==0.3.1
torch==0.1.12.post2
torchvision==0.1.8
tornado==4.2.1
traitlets==4.3.2
unity-lens-photos==1.0
virtualenv==15.0.1
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.12.2
widgetsnbextension==2.0.0

**Comment by arthitag** [comment]
I think I have a hint about the source of the problem:

~$ which python
~/venv4Tensorflow/bin/python
~$ which jupyter
/usr/local/bin/jupyter
~$ which ipython
/usr/local/bin/ipython

**Comment by arthitag** [comment]
And here's the solution:
http://help.pythonanywhere.com/pages/IPythonNotebookVirtualenvs
Hope this helps anyone else who gets stuck with this issue.

**Comment by reedwm** [comment]
Thank you for posting the solution once you resolved the issue.

**Comment by yvettewang** [comment]
thank you so much! it works well!

**Comment by sirius0503** [comment]
> And here's the solution:
> http://help.pythonanywhere.com/pages/IPythonNotebookVirtualenvs
> Hope this helps anyone else who gets stuck with this issue.

@arthitag : This solution didn't work for me, I have tensorflow installed in a venv virtualenv and my jupyter-notebook is installed in miniconda global install
