### ISSUE TITLE
error in docs

### ISSUE THREAD

**Issue by jeremy-rutman** [tensorflow/tensorflow#11866]
The docs [here]( https://www.tensorflow.org/versions/r0.12/api_docs/python/image/working_with_bounding_boxes)  for bounding boxes  have an error :
The paragraph reading 

`For example, if an image is 100 x 200 pixels and the bounding box is [0.1, 0.2, 0.5, 0.9], the bottom-left and upper-right coordinates of the bounding box will be (10, 40) to (50, 180).`

would better go something like:

`For example, if an image is 100 x 200 pixels and the bounding box is [0.1, 0.2, 0.5, 0.9], the upper-left and bottom-right coordinates of the bounding box will be (10, 40) to (50, 180), using a somewhat idiosyncratic (y,x) notation, or (40,10) to (180,50) using the rather more common (x,y) notation for points in a plane.  All this is with 'usual' coordinate axes (origin in the top left corner, increasing x to right and increasing y going down)`

**Comment by clemens-tolboom** [comment]
Is it really _height x width_ ? Yes as said on https://www.tensorflow.org/versions/r0.12/api_docs/python/image/working_with_bounding_boxes

> The coordinates of the each bounding box in boxes are encoded as [y_min, x_min, y_max, x_max].

You could create a PR for around line 700 in 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/image_ops.cc#L700

I agree It is not intuitive but it's mentioned as swapped.

---
Wouldn't it be better to mention __width__ and __height__ to trigger the users?

> For example, if an image is 100 __height__ x 200 __width__ pixels

or
> For example, if an image is 100 x 200 (__height__  x __width__) pixels

**Comment by jeremy-rutman** [comment]
I tried doing a pr [11889](https://github.com/tensorflow/tensorflow/pull/11889) as you suggested, thanks.

**Comment by aselle** [comment]
see #11889 for fix.

**Comment by divyam3897** [comment]
Hi, it should be closed if fixed?

**Comment by jeremy-rutman** [comment]
the pr was merged so I suppse you are right, will close if I can
