### ISSUE TITLE
Error during compilation of tensorflow-GPU using bazel 0.5.3

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#11871]
Using Bazel 0.5.3 (from installer, both sh and deb) on Ubuntu 16.04 to compile tensorflow-gpu, I get the following error that fails compilation:

` Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/nicola/Software/tensorflow/gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 1039
		_create_local_cuda_repository(repository_ctx)
	File "/home/nicola/Software/tensorflow/gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 976, in _create_local_cuda_repository
		_host_compiler_includes(repository_ctx, cc)
	File "/home/nicola/Software/tensorflow/gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
		get_cxx_inc_directories(repository_ctx, cc)
	File "/home/nicola/Software/tensorflow/gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
		set(includes_cpp)
depsets cannot contain mutable items
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/nicola/Software/tensorflow/gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 1039
		_create_local_cuda_repository(repository_ctx)
	File "/home/nicola/Software/tensorflow/gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 976, in _create_local_cuda_repository
		_host_compiler_includes(repository_ctx, cc)
	File "/home/nicola/Software/tensorflow/gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
		get_cxx_inc_directories(repository_ctx, cc)
	File "/home/nicola/Software/tensorflow/gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
		set(includes_cpp)`

Compilation proceeds just fine using Bazel 0.5.2. Note: the error occurs when I try to compile ANY version of tensorflow (tested 1.2.1, 1.3rc0, 1.3rc1, git).

------------------------

### System information
- **Have I written custom code**: No
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from **: source
- **TensorFlow version**: v1.2.0-2210-g49961e5 1.2.1, v.1.3 (rc0, rc1), HEAD
- **Python version**: 3.5.2
- **Bazel version**: (Both 0.5.2 and 0.5.3 from deb installer, and sh installer)
- **CUDA/cuDNN version**: CUDA 8, CuDNN 6.1
- **GPU model and memory**: GeForce 1050Ti - 4Gb

### Describe the problem###
Make sure you clean the bazel cache. 
Install bazel 0.5.2 (from installer, deb or sh).
Try compilation of tensorflow-gpu. it should work fine. 
Remove bazel 0.5.2 and clean its cache. 
Instal bazel 0.5.3 (from installer, deb or sh)
Repeat compilation of tensorflow and the error appears, preventing the full compilation.

**Comment by allenlavoie** [comment]
I ran into this too building Bazel from head. Looks like we can just cast the returned paths from _get_cxx_inc_directories_impl with str() to make them immutable (not sure what they are by default, but apparently not strings). I'll make that a pull request.

**Comment by feranick** [comment]
Is this fixed also in the r1.3 branch?

**Comment by allenlavoie** [comment]
No, just master. You could apply the same change to the r1.3 branch manually; it's a bit late to merge it.

**Comment by feranick** [comment]
While I can do this easily, it's not clear to the end user without any advisory why it will fail to compile  r1.3 with bazel 0.5.3... A note on the  "known issues" in the release notes would be helpful.

**Comment by allenlavoie** [comment]
@av8ramit can we put something in the release notes about building with Bazel 0.5.3 and CUDA? https://github.com/tensorflow/tensorflow/pull/11949 does fix it, but I'm guessing cherrypicks over.

**Comment by av8ramit** [comment]
@allenlavoie I'll create a PR to 1.3 and add you as a reviewer.

**Comment by av8ramit** [comment]
https://github.com/tensorflow/tensorflow/pull/12092/files

**Comment by ahundt** [comment]
I'm still encountering this, even on r1.3

**Comment by ahundt** [comment]
Oh... I install from apt-get... how do I get a different version?

**Comment by feranick** [comment]
This is fixed in head, but it still present in 1.3. 

You can patch the source as indicated above (so you can use bazel 0.5.3).

**Comment by av8ramit** [comment]
Closing as this will be fixed in 1.4 and we have listed a workaround for 1.3
