### ISSUE TITLE
Why tf.FIFOQueue didn't removed when using tf.reset_default_graph?

### ISSUE THREAD

**Issue by ericyue** [tensorflow/tensorflow#11877]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Pip
- **TensorFlow version (use command below)**:  1.2.1
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: None
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**:

### Describe the problem
I want to empty the entire session and grapth while every loop . But the FIFOQueue seems didn't  removed when I  using tf.reset_default_graph.  

So how to make everything clean in currrent process(without create a subprocess \ or change FIFO's name)?

### Source code / logs
```
import tensorflow as tf

cluster = tf.train.ClusterSpec({"ps": ["localhost:65062"], "worker": ["localhost:65063"]})
ps = tf.train.Server(cluster, job_name="ps", task_index=0)
worker = tf.train.Server(cluster, job_name="worker", task_index=0)

while True:
  print "begin a new job"

  print("PS: {0}".format(ps.target))
  print("Worker: {0}".format(worker.target))

  with tf.Session(worker.target) as sess:
    with tf.device("/job:ps/task:0"):
        W = tf.Variable(tf.zeros([784, 10]))
        b = tf.Variable(tf.zeros([10]))
        file_queue = tf.FIFOQueue(10,
                                     [tf.int32, tf.bool, tf.string, tf.string],
                                     shared_name = 'global_queue')
    init = tf.global_variables_initializer()
    sess.run([init, file_queue.close()])

  tf.reset_default_graph()
  time.sleep(2)
```

### ERROR
```
CancelledError (see above for traceback): Queue 'global_queue' is already closed.
	 [[Node: fifo_queue_Close = QueueCloseV2[cancel_pending_enqueues=false, _device="/job:ps/replica:0/task:0/cpu:0"](fifo_queue)]]
```

**Comment by yaroslavvb** [comment]
I believe this is working as intended (you have to reset the session/containers to get rid of persistent ops)

**Comment by ericyue** [comment]
I have already reset the session by using `tf.reset_default_graph()`  @yaroslavvb

**Comment by Mazecreator** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mazecreator@gmail.com
    Domain mazecreator.com has exceeded the max emails per hour (30/25 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:62857)
	by server2.lowesthostingrates.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-e6d9-mazecreator=mazecreator.com@sgmail.github.com>)
	id 1dcDpx-0004VZ-83
	for mazecreator@mazecreator.com; Mon, 31 Jul 2017 11:47:03 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=WYoOVBfeONo9LRetAs4v7YBhTcQ=; b=ZgbISU+AtkiLQLrz
	t330bqsAVZMKcsOJLDemohwG4DdbkGycxsRQm5cI6UijVYHOAl4QEWAkLn5tNwyC
	2ajKdFPa4RLM/pDYo8xaR+hS3vhUe1fq2w9/m8OmsHIQisOAPMtWptzDhkOELpno
	c7Xw9y3K5jZLXPtldUkNEth/fHE=
Received: by filter1157p1mdw1.sendgrid.net with SMTP id filter1157p1mdw1-3486-597F6161-1E
        2017-07-31 16:57:05.685394948 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0037p1mdw1.sendgrid.net (SG) with ESMTP id 7_cXyGsZT4OtelFaQAmRoQ
	for <mazecreator@mazecreator.com>; Mon, 31 Jul 2017 16:57:05.647 +0000 (UTC)
Date: Mon, 31 Jul 2017 16:57:06 +0000 (UTC)
