### ISSUE TITLE
All Windows GPU build links are broken.

### ISSUE THREAD

**Issue by glhfgg1024** [tensorflow/tensorflow#11876]
The link (bolded) is broken in the webpage of "https://github.com/tensorflow/tensorflow".

<li>Windows GPU: <a href="**https://ci.tensorflow.org/view/Nightly/job/nightly-win/M=windows-gpu,PY=35/lastSuccessfulBuild/artifact/cmake_build/tf_python/dist/tensorflow_gpu-1.3.0rc1-cp35-cp35m-win_amd64.whl**">Python 3.5 64-bit</a> (<a href="https://ci.tensorflow.org/view/Nightly/job/nightly-win/M=windows-gpu,PY=35/">build history</a>) / <a href="https://ci.tensorflow.org/view/Nightly/job/nightly-win/M=windows-gpu,PY=36/lastSuccessfulBuild/artifact/cmake_build/tf_python/dist/tensorflow_gpu-1.3.0rc1-cp36-cp36m-win_amd64.whl">Python 3.6 64-bit</a> (<a href="https://ci.tensorflow.org/view/Nightly/job/nightly-win/M=windows-gpu,PY=36/">build history</a>)</li>

Some other links in this webpage are also broken. 

But the file of the corresponding link in the webpage of the "Build history" can be downloaded.

**Comment by clemens-tolboom** [comment]
The link https://github.com/tensorflow/tensorflow works for me.

Which link pointing to what page is broken?

**Comment by glhfgg1024** [comment]
@clemens-tolboom I mean the link pointed to "Python 3.6 64-bit" is 

https://ci.tensorflow.org/view/Nightly/job/nightly-win/M=windows-gpu,PY=36/lastSuccessfulBuild/artifact/cmake_build/tf_python/dist/tensorflow_gpu-1.3.0rc1-cp36-cp36m-win_amd64.whl

is broken.

**Comment by clemens-tolboom** [comment]
tnx ... Maybe change the title to

> All Windows build link are broken.

**Comment by glhfgg1024** [comment]
@clemens-tolboom yeah, that would be better. Thanks.

**Comment by aselle** [comment]
@gunan, @av8ramit, could you take a look

**Comment by av8ramit** [comment]
https://github.com/tensorflow/tensorflow/pull/11914

**Comment by av8ramit** [comment]
The original links are working now.

**Comment by glhfgg1024** [comment]
@av8ramit thanks for revisions.
