### ISSUE TITLE
How to shutdown a tf.train.Server's port?

### ISSUE THREAD

**Issue by ericyue** [tensorflow/tensorflow#11872]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Pip
- **TensorFlow version (use command below)**:  1.2.1
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: None
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**:

### Describe the problem
When I  createt a tf.train.Server object, It's open a port immediately, But I can not find any way to close the Server(I means the port tf.train.Server started).   

What can I do if I want to start-run-stop a tf.train.Server in a loop?

I need to start tf.train.Server in a while loop.

**one more thing: on my macbook, the code  can run without error, but on a linux server failed.**

### Source code / logs
```
import tensorflow as tf

while True:
  print "begin a new job"
  cluster = tf.train.ClusterSpec({"ps": ["localhost:65062"], "worker": ["localhost:65063"]})
  ps = tf.train.Server(cluster, job_name="ps", task_index=0)
  worker = tf.train.Server(cluster, job_name="worker", task_index=0)

  print("PS: {0}".format(ps.target))
  print("Worker: {0}".format(worker.target))

  with tf.Session(worker.target) as sess:
    with tf.device("/job:ps/task:0"):
        W = tf.Variable(tf.zeros([784, 10]))
        b = tf.Variable(tf.zeros([10]))

    init = tf.global_variables_initializer()
    print("RUNNING SESSION")
    sess.run(init)
    print("SESSION FINISHED")
  tf.reset_default_graph()
  time.sleep(2)
```

Error
```
E0730 01:49:45.923951794   57304 server_chttp2.c:159]        {"created":"@1501350585.923875462","description":"No address added out of total 1 resolved","file":"external/grpc/src/core/ext/transport/chttp2/server/insecure/server_chttp2.c","file_line":125,"referenced_errors":[{"created":"@1501350585.923871295","description":"Failed to add port to server","file":"external/grpc/src/core/lib/iomgr/tcp_server_posix.c","file_line":634,"referenced_errors":[{"created":"@1501350585.923863108","description":"Unable to configure socket","fd":18,"file":"external/grpc/src/core/lib/iomgr/tcp_server_posix.c","file_line":355,"referenced_errors":[{"created":"@1501350585.923845040","description":"OS Error","errno":98,"file":"external/grpc/src/core/lib/iomgr/tcp_server_posix.c","file_line":331,"os_error":"Address already in use","syscall":"bind"}]}],"target_address":"ipv6:[::]:65062"}]}
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    ps = tf.train.Server(cluster, job_name="ps", task_index=0)
  File "/home/mk/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/server_lib.py", line 145, in __init__
    self._server_def.SerializeToString(), status)
  File "/home/mk/anaconda2/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/mk/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.UnknownError: Could not start gRPC server
```

**Comment by hongjic** [comment]
#4713  this issue might help you.
Also checkout [Coordinator and QueueRunner](https://www.tensorflow.org/versions/r0.12/api_docs/python/train/coordinator_and_queuerunner) 
and there is a high level class [Supervisor](https://www.tensorflow.org/programmers_guide/supervisor) you may be interested.

**Comment by yaroslavvb** [comment]
There was an attempt to add this functionality in this PR https://github.com/tensorflow/tensorflow/pull/6185 by @llhe 

Otherwise server stays open until the parent Python process quits.

In current situation you could implement this functionality by having a parent process running `while` loop and launching child Python processes which actually start the server

**Comment by ericyue** [comment]
@yaroslavvb  thanks, it's exactly what I want to know. It seems that using a subprocess is a good choice currently since the grpc shutdown's incomplete  :)
