### ISSUE TITLE
python ImportError: No module named 'scipy'

### ISSUE THREAD

**Issue by lifewadwdv** [tensorflow/tensorflow#11881]
In [1]:from sklearn import linear_model
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a6ebbebad697> in <module>()
----> 1 from sklearn import linear_model
C:\ProgramData\Anaconda3\envs\tensorflow-gpu\lib\site-packages\sklearn\__init__.py in <module>()
     55 else:
     56     from . import __check_build
---> 57     from .base import clone
     58     __check_build  # avoid flakes unused variable error
     59 

C:\ProgramData\Anaconda3\envs\tensorflow-gpu\lib\site-packages\sklearn\base.py in <module>()
      8 
      9 import numpy as np
---> 10 from scipy import sparse
     11 from .externals import six
     12 from .utils.fixes import signature

ImportError: No module named 'scipy'

**Comment by tomzhang** [comment]
have you check the scipy installation by issue command "pip list "?
can you import scipy from python originally? 
anyway, this issue should report from forum rather than tensorflow issue list

**Comment by lifewadwdv** [comment]
@tomzhang 
”import scipy from python originally” is done,
 but i just want to use "from sklearn  @import linear_model" in the environment of tensorflow-gpu，may i ？

**Comment by lifewadwdv** [comment]
@tomzhang I work it out by in install scipy-0.19.1-cp35-cp35m-win_amd64.whl，thank U very much！
