### ISSUE TITLE
No registered 'MirrorPad' OpKernel for XLA_CPU_JIT

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#11890]
`tf.pad(..., mode='REFLECT')` doesn't work with tfcompile. Will this be supported and when? 

It's somewhat urgent on my part, and it seems like it should be a simple enough addition unlike control flow as in https://github.com/tensorflow/tensorflow/issues/11275

**Comment by learyg** [comment]
I think this might be quite simple to add to the tf2xla bridge. I'll take a look.

**Comment by learyg** [comment]
This may be able to make it into the merge tomorrow, I'll ping the issue when it's on the merge train.

**Comment by learyg** [comment]
I think this should be resolved, take a look at let us know how it goes.
