### ISSUE TITLE
'//tensorflow/contrib/verbs:rdma

### ISSUE THREAD

**Issue by pocandraspoc** [tensorflow/tensorflow#11891]
Build fails 
Thanks for help in advance

1. It must be a **bug** 

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:yes
- **TensorFlow version (use command below)**:Latest git
- **Python version**: 2.7.13
- **Bazel version (if compiling from source)**:Build label: 0.5.2
- **CUDA/cuDNN version**:
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
- **GPU model and memory**:  [GeForce GTX 860M] 4044MiB Driver Version: 375.66
- **Exact command to reproduce**:
bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --config=cuda //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
Build fails with carefully chosen configs:
Please specify the location of python. [Default is /home/op/anaconda2/bin/python]:
input the desired Python library path to use.  Default is /home/op/anaconda2/lib/python2.7/site-packages

y jemalloc as malloc support
n Google Cloud Platform
n Hadoop File System support
y XLA JIT support

y  VERBS support
n OpenCL support
y  CUDA support

CUDA SDK version: 8.0
CUDA 8.0 toolkit is installed /usr/local/cuda-8.0

cuDNN 6.0
 cuDNN 6 library is installed: /usr/local/cuda-8.0

Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 5.0]

clang as CUDA compiler? [y/N]: n
nvcc will be used as CUDA compiler
gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]
MPI support? [y/N]: n

flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
### Source code / logs
ERROR: /home/op/Downloads/tensorflow/tensorflow/contrib/verbs/BUILD:136:1: C++ compilation of rule '//tensorflow/contrib/verbs:rdma' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 150 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from tensorflow/contrib/verbs/rdma.cc:18:0:
./tensorflow/contrib/verbs/rdma.h:21:30: fatal error: infiniband/verbs.h: No such file or directory
 #include <infiniband/verbs.h>
                              ^
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3203.696s, Critical Path: 206.50s

**Comment by shamoya** [comment]
Hi @pocandraspoc 
Why "y VERBS support" ? 
It means you have chosen to compile with RDMA Verbs support, but you don't have the SW stack (libibverbs, etc..), and I guess you didn't want to have anyway.
Run configure and choose No for Verbs support.

**Comment by pocandraspoc** [comment]
Thanks I will check it!

**Comment by pocandraspoc** [comment]
Sorry to make false bug report,
I made the mistake wit my configurations.
