### ISSUE TITLE
RandomShuffleQueue seems not random when one class one file.

### ISSUE THREAD

**Issue by Queequeg92** [tensorflow/tensorflow#11910]
I split cifar-10 dataset to ten files, where each file contains one class of samples. When I use the split files   as the input of a classification model and use RandomShuffleQueue to handle the input, data in one batch  is not an approximate uniform sampling of the ten classes. The hisogram of the labels in one batch indicates RandomShuffleQueue seems not do a real random dequeue operation. Can anyone explain the details of RandomShuffleQueue dequeen operation? Thanks.
![screenshot from 2017-07-31 21-39-45](https://user-images.githubusercontent.com/8766653/28781032-5187f2bc-763b-11e7-91a8-24a1c0e2ce2b.png)

**Comment by yaroslavvb** [comment]
This may be better suited for stackoverflow. Amount of mixing is controlled by min_after_dequeue and capacity parameters. For best level of mixing you could shuffle the dataset before feeding it to tensorflow
