### ISSUE TITLE
tensorflow-1.2.1 import tensorflow Segmentation fault

### ISSUE THREAD

**Issue by lemonsee** [tensorflow/tensorflow#11911]
hi ,
I installed tensorflow-1.2.1 in my machine, and met a segment fault as below. 

```
stm-zk5:~ # python
Python 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow
段错误
```

### System information
```
stm-zk5:~ #  cat /etc/redhat-release
CentOS Linux release 6.2 (Final)

```

###  Installing 
I do : 
`pip install --ignore-installed --upgrade  https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.2.1-cp27-none-linux_x86_64.whl`

so , would someone help me to solve this problem ?🤕 ，thx !

**Comment by poxvoculi** [comment]
I see in one of our internal documents that Centos is only supported for version 7 and up.  I can't find a public document that addresses this issue, though I suspect it's your problem.  If upgrading to Centos 7 is infeasible,  you might try on stackoverflow to see whether the community has figured out how to make it work on your version.

**Comment by mohantym** [comment]
Hi! @lemonsee .We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.5 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!
