### ISSUE TITLE
How to make full use of multicore(only cpu mode) on android phone?

### ISSUE THREAD

**Issue by Wenstery** [tensorflow/tensorflow#11929]
### System information
 Platform : android 6.0, arm64-v8a
 TensorFlow installed from source(cpu mode only):
 TensorFlow version (1.2.0)
  Bazel version (0.5.2)

### Describe the problem
When I trained a model by using google object-detection api, I put it to my android env, and use c++ api to run the pb file model on my phone, it has a slow running speed, and only 2 cpus are fully utilized when there are 8 cpus on my device. What should I do to make full use of the remaining cpus on my mobile phone? 

I use c++ api to run the model, here is my config to session of tensorflow, but it is useless.Could some one help me?

### Source code / logs
tensorflow::SessionOptions options;
tensorflow::ConfigProto &config = options.config;
config.mutable_device_count()->insert(google::protobuf::MapPair<std::string, google::protobuf::int32>("cpu",8));
config.set_intra_op_parallelism_threads(8);

**Comment by snnn** [comment]
@Wenstery This is not the place for asking help.  Please go to Stackoverflow.

**Comment by Wenstery** [comment]
If you talk about things that have noting to do with the problem of tensorflow, I'll ignore it.

**Comment by Wenstery** [comment]
@snnn  If you talk about things that have nothing to do with the problem of tensorflow, I'll ignore it.

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
