### ISSUE TITLE
I am unable to extract the hidden layer values from Seq2Seq model in Tensorflow for NMt

### ISSUE THREAD

**Issue by soukira** [tensorflow/tensorflow#11938]
Has anyone tried to extract the hidden layer values since the code explicitly doesn't specify the hidden layer  in translate.py or in seq2seq_model.py. ?

tensorflow version: 1.0
OS : CentOS
Python: 2.7

Is there any other program i need to look into for printing the hidden layer values?

**Comment by allenlavoie** [comment]
Let's keep this to StackOverflow (https://stackoverflow.com/questions/45434572/unable-to-extract-the-hidden-layer-values-during-neural-machine-translation-in-t for anyone interested in following up).
