### ISSUE TITLE
built 1.3.0 from source, got version 1.2.0 

### ISSUE THREAD

**Issue by suiyuan2009** [tensorflow/tensorflow#11933]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:ubuntu 16.04
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:v1.2.0-2651-g82456f9 1.2.1-rc1
- **Python version**: Python 3.5.2
- **Bazel version (if compiling from source)**: 0.5.2
- **CUDA/cuDNN version**: 8.0/6.0
- **GPU model and memory**: titanx, 12GB
- **Exact command to reproduce**: no

### Describe the problem
`git log` shows latest commit is `82456f9fee7c4b5e9beb100e59ba8dc5eb688b28`, my python install package file is named `tensorflow-1.3.0rc1-cp35-cp35m-linux_x86_64.whl`, but `python3 -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` output `v1.2.0-2651-g82456f9 1.2.1-rc1`. I use python help to see some api doc, and find they are same as [1.3.0-rc1 ](https://github.com/tensorflow/tensorflow/releases/tag/v1.3.0-rc1) says.

**Comment by av8ramit** [comment]
Hi @suiyuan2009 do you mind sending over a list of commands that you used from start to finish? Thanks!

**Comment by yaroslavvb** [comment]
@suiyuan2009 it looks like you are building from master. Versioning is non-linear, the master is at 1.2.1 (in [version.h](https://github.com/tensorflow/tensorflow/blob/ced7455a9c3d2ff1570f9752c9ca432af1913167/tensorflow/core/public/version.h#L21)) whereas 1.3 only exists in a branch

**Comment by yaroslavvb** [comment]
PS, you get the commit hash from git_version after the "-g" part
```
#!/usr/bin/env python
import os
import tensorflow as tf
version=tf.__version__
print("version: %s"%(version,))
commit = tf.__git_version__
print("__git_version__: %s"%(commit,))
# commit looks like this
# 'v1.0.0-65-g4763edf-dirty'
commit = commit.replace("'","")
if commit.endswith('-dirty'):
  dirty = True
  commit = commit[:-len('-dirty')]
commit=commit.rsplit('-g', 1)[1]
url = 'https://github.com/tensorflow/tensorflow/commit/'+commit
print("Commit %s" %(url,))

```

**Comment by suiyuan2009** [comment]
@yaroslavvb , I got
```
version: 1.2.1-rc1
__git_version__: v1.2.0-2651-g82456f9
Commit https://github.com/tensorflow/tensorflow/commit/82456f9
```

**Comment by suiyuan2009** [comment]
@av8ramit ,
```
git pull origin master

bazel --output_base=/mnt/local0/ clean

./configure

bazel --output_base=/mnt/local0/ --output_user_root=/mnt/local0/zdong build --config=opt --config=cuda --copt=-march=native //tensorflow/tools/pip_package:build_pip_package -j 31

bazel-bin/tensorflow/tools/pip_package/build_pip_package ~/tensorflow_pkg

sudo -E pip install tensorflow_pkg/tensorflow-1.3.0rc1-cp35-cp35m-linux_x86_64.whl --upgrade

python3 -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

**Comment by yaroslavvb** [comment]
@suiyuan2009 the reason you are seeing this is because versioning is non-linear. Some commits go directly into version branch. Right now master is behind 1.3 version branch by 1 commit.

**Comment by suiyuan2009** [comment]
thank you @yaroslavvb . The version `1.2.1-rc1` I got from `tf.__version__` confused me, I thought I installed a wrong version.

**Comment by gunan** [comment]
Closing based on latest comments.
