### ISSUE TITLE
TPU support

### ISSUE THREAD

**Issue by tampler** [tensorflow/tensorflow#11937]
I wanna add support for my Tensor Processing Unit chip in TensorFlow. 

My TPU is implemented as an accelerator for ARM v7 32bit processor and implements multiple arithmetic kernels, similar to GPU. It implements a simple memory mapped interface, SGDMA and vector instructions over tensors. I added vector extension to GCC 7.1.1 and can run bare metal C++ nets on embedded Ubuntu 16.04

I also checked the TF port  for Raspberry Pi 3, but it looks outdated and barely supported.

I'm not currently aware about the scope of work, but believe that should not be that complex, given open examples from GPU vendors and already existing port for Google TPU

Anyone interested in joining this project is highly welcome! Advise, links and code examples are much appreciated

Thank you

**Comment by yaroslavvb** [comment]
New hardware is typically added through XLA interface. A discussion group is here -- https://groups.google.com/forum/#!forum/xla-dev

**Comment by tampler** [comment]
@yaroslavvb > New hardware is typically added through XLA interface
Well, XLA is a graph compiler and a relatively new feature. It relies on LLVM backend to generate instructions for a (co)processor.  In my case, I need a memory mapped device support with a direct access to local TF memory, e.g shared buffers. TF should directly call my API methods, wrapped as C++ kernels, instead of generating an instruction stream thru LLVM XLA

My TPU comes into a play when TF launches the session run() method. I need to call my kernels, such as conv2 or add and pass pointers to shared buffers to my DMA implementation.

Something similar was implemented to support GPUs. However, I need a more lightweight implementation with a limited number of kernels

**Comment by yaroslavvb** [comment]
I see. TF was more recently ported to run on Qualcomm Hexagon DSP, so maybe that has useful lessons -- https://github.com/tensorflow/tensorflow/tree/b00fc538638f87ac45be9105057b9865f0f9418b/tensorflow/contrib/hvx
