### ISSUE TITLE
does libtensorflow_inference.so contains both  "code for training .pb file"  and "code for analyzing .pb file"?

### ISSUE THREAD

**Issue by scucheri** [tensorflow/tensorflow#11936]
### Describe the problem
 I'd like to import "libtensorflow_inference.so" to an android app to and make it possible to make some machine learning in the app. But the size of "libtensorflow_inference.so"  file is too large which is 9.8M .

Because  I just want to import generated models(.pb file) to predict and don't need to train models in android app. Could you please tell me which code is used to import and analyze the .pb file and witch code is used to train a .pb file in tensorflow project?  

does libtensorflow_inference.so contains both  "code for training .pb file"  and "code for analyzing .pb file"? Is possible to remove the "code for training .pb file" to minimize its size  if it contains that?

**Comment by andrewharp** [comment]
@scucheri The Android TF library is inference only, so there is no training code to remove.

However, we include a large set of ops by default.  You can probably save quite a bit of space by using selective registration. This will strip the binary down to just the ops needed for your model pb. See [print_selective_registration_header.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/print_selective_registration_header.py) for details.

Closing as this is neither a bug nor a feature request.

**Comment by scucheri** [comment]
Thank you very much ~
