### ISSUE TITLE
Where can I find "gen_checkpoint_ops"

### ISSUE THREAD

**Issue by aweichina** [tensorflow/tensorflow#11941]
_**When I was debuging inception v4, there has a message:**_
"22 from tensorflow.contrib.framework.python.ops import gen_checkpoint_ops
     23 from tensorflow.contrib.util import loader
     24 from tensorflow.python.framework import dtypes

ImportError: cannot import name gen_checkpoint_ops
".
_**But I can't find a module or package named "gen_checkpoint_ops".**_
_**I don't know how to resolve this problem.**_ 
#  Help!

**Comment by yaroslavvb** [comment]
This is probably better for stackoverflow or tensorflow/models repo. I'm guessing you need to use a different version of TF
