### ISSUE TITLE
Feature Request: Video Decoder

### ISSUE THREAD

**Issue by jrbtaylor** [tensorflow/tensorflow#11944]
A video decoder would make it much easier to work with video. For instance, something like tf.image.decode_jpeg, but for mp4 videos (or some other format perhaps).

**Comment by shivaniag** [comment]
@shlens do you have any comments on this?

**Comment by Mazecreator** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mazecreator@gmail.com
    Domain mazecreator.com has exceeded the max emails per hour (25/25 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:55577 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server2.lowesthostingrates.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dd0dn-0000oV-98
	for mazecreator@mazecreator.com; Wed, 02 Aug 2017 15:53:45 -0500
Date: Wed, 02 Aug 2017 14:03:55 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1501707835;
	bh=EyEO8HgDzelVPm6JF8SJAuCP4eW1o6FWPg/7sgLIjuQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=FyMLw/GRmnUB9praeZmx4aAq8VvNif0hkwhWVXFC7hXj7RqcHJ7h1CBVryr0yxGo1
	 I0+OKPIOS6IBgwaka37yTLNIYFwqb+oiXJoS+EcmIAWnxNOxUFkVvAK1hHHbeojVjN
	 hIUzZHpYZ7BK2EXI/vZFyLmZ4gxqIWwQL5by3qU8=

**Comment by shlens** [comment]
We are generally reluctant to add more dependencies to tensorflow on external libraries. In particular, many external open-source video decoding libraries (e.g. ffmpeg) tend to be quite large and bring in many dependencies. In addition, decoding a video on the fly can be computationally expensive and may detract from the training speed.

That said, one can always build a stand-alone script that imports arbitrary libraries and provides a one-time conversion for individual video frames to tf.Example's that may be processed by TensorFlow with ease.

**Comment by futurely** [comment]
FFmpeg has already been integrated.
https://github.com/tensorflow/tensorflow/search?utf8=%E2%9C%93&q=ffmpeg&type=

Duplicate of https://github.com/tensorflow/tensorflow/issues/6265.

**Comment by scotthuang1989** [comment]
@shlens  If I want to do on-line video classification. An integrated video infrastructure will speed up the inference time according to my profiling on my application.
