### ISSUE TITLE
No module named 'tensorflow.contrib.keras.datasets'

### ISSUE THREAD

**Issue by jinyeom** [tensorflow/tensorflow#11947]
In the documentation, in order to import Keras dataset, you have to

```python
import tensorflow.contrib.keras.datasets
``` 
But instead, it only works when

```python
import tensorflow.contrib.keras.python.keras.datasets
``` 
I think this problem would occur not just for datasets but anything else in Keras.

**Comment by poxvoculi** [comment]
I'm not able to find the import statement you cite.  Could you tell me where it is?

**Comment by jinyeom** [comment]
https://www.tensorflow.org/api_docs/python/tf/contrib/keras/datasets/mnist/load_data

**Comment by poxvoculi** [comment]
I'm afraid I still don't see it.  Are you talking about the module names, in the left column?

**Comment by jinyeom** [comment]
I might be doing something wrong, but since the documentation suggests 'tf.contrib.keras.datasets.mnist' as the module name, I assumed that I import it by 
```python
import tensorflow.contrib.keras.datasets
```
but that didn't work.

**Comment by poxvoculi** [comment]
It appears that the module names in the documentation are frequently not the same as the include paths. 
 This appears to be intentional.  The documentation often gives a specific path where a particular module is defined.

**Comment by Mazecreator** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mazecreator@gmail.com
    Domain mazecreator.com has exceeded the max emails per hour (25/25 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:49132)
	by server2.lowesthostingrates.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-e6d9-mazecreator=mazecreator.com@sgmail.github.com>)
	id 1dcxkT-0001C4-Fv
	for mazecreator@mazecreator.com; Wed, 02 Aug 2017 12:48:27 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=f5+n68l/4GpsLN1qcMXq1bJCPAc=; b=f3xdCKBBPrrDXpaw
	db0Ed+gmwWgEzLEmEghLlUCGZs2tfcmMrar/9z9UYG7jaDhJayySKdZedUrnbRFB
	156Lt8XEMwtlQ1LAJzeY/b829sFc029rqq14g/KKAsQt1PEhQIW/QPYf7kogH0Wh
	aqYj1/XSIQB4n9+P4f4oBoMjO88=
Received: by filter1183p1mdw1.sendgrid.net with SMTP id filter1183p1mdw1-4011-598212CD-4
        2017-08-02 17:58:37.141982529 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id QSYq8lRUQ2-QET19N8RkSA
	for <mazecreator@mazecreator.com>; Wed, 02 Aug 2017 17:58:37.094 +0000 (UTC)
Date: Wed, 02 Aug 2017 17:58:37 +0000 (UTC)
