### ISSUE TITLE
Incorrect tfBinaryURL for installing with Anaconda on Linux

### ISSUE THREAD

**Issue by orangeagles** [tensorflow/tensorflow#11955]
There is incorrect tfBinaryURL at tensorflow.org.

In case of Installing with Anaconda in Linux, the example shows the following command for Python 2.7.
(tensorflow)$ pip install --ignore-installed --upgrade \
 https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.2.1-cp34-cp34m-linux_x86_64.whl
But this is for Python 3.4 so correct command is below.
(tensorflow)$ pip install --ignore-installed --upgrade \
 https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.2.1-cp27-none-linux_x86_64.whl

**Comment by poxvoculi** [comment]
Thanks for pointing this out.

**Comment by dr4b** [comment]
So, we already have fixed this in the source, as you can see here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/install/install_linux.md#InstallingAnaconda

It just hasn't propagated out to be the root version of the documentation on tensorflow.org yet, but that should happen fairly soon.
