### ISSUE TITLE
Dynamic Partition Gradient

### ISSUE THREAD

**Issue by altaetran** [tensorflow/tensorflow#1195]
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

### Environment info
Operating System: Linux (CentOS) cluster, custom build. tensorflow built from source by IT folks managing the cluster. 

If installed from sources, provide the commit hash:

### Steps to reproduce
1. The functions of interest contain many dynamic_partitions
2. I then compute the gradient with respect to the variables for optimization
3. I obtain the following error

    train_op = optimizer.minimize(loss_instance, global_step=global_step)
  File "/share/sw/free/tensorflow/0.6.0/tensorflow/python/training/optimizer.py", line 186, in minimize
    aggregation_method=aggregation_method)
  File "/share/sw/free/tensorflow/0.6.0/tensorflow/python/training/optimizer.py", line 232, in compute_gradients
    aggregation_method=aggregation_method)
  File "/share/sw/free/tensorflow/0.6.0/tensorflow/python/ops/gradients.py", line 426, in gradients
    (op.name, op.type))
LookupError: No gradient defined for operation 'DynamicPartition_1' (op type: DynamicPartition)

### What have you tried?
1. I am currently trying to see if I can remove the dynamic partition from my code, but it would be nice if we could keep the dynamic partition inside; however, I understand why the dynamic partition might not be differentiable if variable indices are used. In my case, I just have a constant placeholder that performs that indexing. Could there be a way to compute gradients in this case? Thank you so much!

**Comment by mrry** [comment]
Gradients for `tf.dynamic_partition()` should be supported as of https://github.com/tensorflow/tensorflow/commit/2b672c4a2f6aeaea8457fd4941f48f5a9e80d283 (and certainly in the 0.7 release). Does you custom build pre-date that change?

**Comment by altaetran** [comment]
Ahh ok. Thanks, it does. I won't be able to update it right now unfortunately. Do you know if in 0.6.0 there is slice gradient support? I think I can work with that if it does.

**Comment by mrry** [comment]
I bring good news! You can just paste the implementation from that commit into your program somewhere (with the appropriate changes as below):

```python
@tf.RegisterGradient("DynamicPartition")
def _DynamicPartitionGrads(op, *grads):
  """Gradients for DynamicPartition."""
  data = op.inputs[0]
  indices = op.inputs[1]
  num_partitions = op.get_attr("num_partitions")

  prefix_shape = tf.shape(indices)
  original_indices = tf.reshape(tf.range(tf.reduce_prod(prefix_shape)), prefix_shape)
  partitioned_indices = tf.dynamic_partition(original_indices, indices, num_partitions)
  reconstructed = tf.dynamic_stitch(partitioned_indices, grads)
  reconstructed = tf.reshape(reconstructed, tf.shape(data))
  return [reconstructed, None]
```

...then the gradient will be available from your code.
