### ISSUE TITLE
Is `tf.matrix_inverse()` supported for TF v.1.2?

### ISSUE THREAD

**Issue by RuofanKong** [tensorflow/tensorflow#11953]
I notice that the Tensorlfow computation op `tf.matrix_inverse()` was not supported running on GPU in the previous versions, and I wonder if it's supported for Tensorflow v.1.2 now. If it's still not, can we make a feature request for it? Thanks!

**Comment by yaroslavvb** [comment]
@RuofanKong it's supported in head, benchmark numbers are in https://github.com/tensorflow/tensorflow/pull/12116/commits/e57e11b74b983d663f612d40facd97b83189bbac
