### ISSUE TITLE
tensorflow using cpu+2 gpus turns out 3 times slower than theano using 1 gpu

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#1196]
1. Does tensorflow automatically use all cpus and gpus to run the computational task?

2.I found that tensorflow use 1 5960X cpu and 2 Titan X gpus cost 300% time compared to theano use only 1 Titan X gpu, is there anything wrong with my configuration? I use the same model generated by keras, using different backend(theano and tensorflow)

I installed on Ubuntu 15.10, cuda 7.5, cudnn 4, gcc 4.9, installed from source code, built with GPU support.

**Comment by Dringite** [comment]
Another question is about parallelism. When you use python to prepare and augment the data you feed to the compute graph, does that happen in a separate thread or will there be a bottleneck you have to account for with purposeful parallel code?

**Comment by fayeshine** [comment]
@Dringite I didn't do data augmentation, and the data preparing time is not counted in the total training time

**Comment by martinwicke** [comment]
1) yes, Tensorflow uses all available GPUs and CPUs, although not necessarily in an optimal fashion.
2) I cannot comment on what keras exports, so it's entirely possible that it restricts to run only on some devices. I would take this up with people who know about keras first, or dig into the code that keras generated and ask about that.

From your description, it is very hard to tell what, if anything, is wrong with TensorFlow, so this is probably a better question for the mailing list, or, if you have a more specific question about using multiple devices, for stackoverflow. 

I will close this bug for now. Please reopen this if you find a more specific problem.

**Comment by pinkeshbadjatiya** [comment]
Even I experienced similar slow down when I first used tensorflow, but tensorflow gives huge speed boost with large batch sizes as it is able to utilize memory of multiple GPUs much effectively.
