### ISSUE TITLE
Training_ops_test assertion failures on Ubuntu 16.04

### ISSUE THREAD

**Issue by namrata-ibm** [tensorflow/tensorflow#11967]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:  'v1.2.1-0-gb4957ff', '1.2.1'
- **Python version**:  2.7.12
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: No GPU
- **GPU model and memory**: No GPU
- **Exact command to reproduce**: bazel test -c opt //tensorflow/python:training_ops_test

### The problem
The `//tensorflow/python:training_ops_test` is failing on s390x with AssertionError in `_testTypesForFtrl` method. I have added test log below.

A single value differs as below in the result:
```
lhs =  [-2.9473114]
rhs =  [-2.94730377]
```

@gunan, I saw your suggestion in [issue](https://github.com/tensorflow/tensorflow/issues/8945#issuecomment-291763267), that the test tolerance bounds are too tight.

So I tried increasing tolerance to `4e-06 ` as below and test passes.

```
- self.assertAllClose(linear_update, linear.eval())
+ self.assertAllClose(linear_update, linear.eval(), rtol=4e-06, atol=4e-06)
```  
Is this tolerance level acceptable?    

   
    
    

### Source code / logs   
```
AssertionError:
Not equal to tolerance rtol=1e-06, atol=1e-06
None
(mismatch 1.0%)
 x: array([  1.020000e+02,   1.038411e+02,   1.050863e+02,   1.055917e+02,
         1.053070e+02,   1.042043e+02,   1.022649e+02,   9.947507e+01,
         9.582399e+01,   9.130299e+01,   8.590485e+01,   7.962347e+01,...
 y: array([  1.020000e+02,   1.038411e+02,   1.050863e+02,   1.055917e+02,
         1.053070e+02,   1.042043e+02,   1.022649e+02,   9.947507e+01,
         9.582399e+01,   9.130299e+01,   8.590485e+01,   7.962347e+01,...

----------------------------------------------------------------------

Ran 9 tests in 4.704s

FAILED (failures=1)
not close where =  (array([19]),)
not close lhs =  [-2.9473114]
not close rhs =  [-2.94730377]
not close dif =  [  7.62939453e-06]
not close tol =  [  3.94730387e-06]
dtype = float32, shape = (100,)
```

**Comment by poxvoculi** [comment]
Which test specifically is failing?  If it's one where the final values are the result of multiple math ops, then 1e-6 is not a very high tolerance.

**Comment by namrata-ibm** [comment]
@poxvoculi , [testApplyFtrl](https://github.com/tensorflow/tensorflow/blob/v1.2.1/tensorflow/python/training/training_ops_test.py#L131) is failing at [this](https://github.com/tensorflow/tensorflow/blob/v1.2.1/tensorflow/python/training/training_ops_test.py#L119).

Without change in tolerance, the test passes if I run in `debug` mode: 
`bazel test -c dbg //tensorflow/python:training_ops_test
`
However it fails with `opt` or `fastbuild` compilation modes:
```
bazel test -c opt //tensorflow/python:training_ops_test
bazel test //tensorflow/python:training_ops_test
```

**Comment by poxvoculi** [comment]
Internal bug opened to raise the error tolerance at this point.

**Comment by namrata-ibm** [comment]
@poxvoculi, Thank you for you support.

On similar lines I found a test failure in `//tensorflow/python/kernel_tests:summary_image_op_test`.
Here the error tolerance increase needed is even lower ( i.e. 2e-06) at [assert](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/summary_image_op_test.py#L83).

Also test passes when run in debug mode without tolerance increase.

Adding the log below:

```
F..
======================================================================
FAIL: testImageSummary (__main__.SummaryImageOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/.cache/bazel/_bazel_test/24685d064c07f7346b48c2d13ec3ad69/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/summary_image_op_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/summary_image_op_test.py", line 83, in testImageSummary
    self.assertAllClose(image, adjusted[0])
  File "/home/test/.cache/bazel/_bazel_test/24685d064c07f7346b48c2d13ec3ad69/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/summary_image_op_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 634, in assertAllClose
    self._assertArrayLikeAllClose(a, b, rtol=rtol, atol=atol)
  File "/home/test/.cache/bazel/_bazel_test/24685d064c07f7346b48c2d13ec3ad69/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/summary_image_op_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 604, in _assertArrayLikeAllClose
    np.testing.assert_allclose(a, b, rtol=rtol, atol=atol, err_msg=msg)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-06, atol=1e-06
None
(mismatch 2.85714285714%)
 x: array([[[221],
        [102],
        [129],...
 y: array([[[ 221.],
        [ 102.],
        [ 129.],...

----------------------------------------------------------------------
Ran 3 tests in 0.069s

FAILED (failures=1)
not close where =  (array([3]), array([6]), array([0]))
not close lhs =  [0]
not close rhs =  [ 1.]
not close dif =  [ 1.]
not close tol =  [  1.99999999e-06]
dtype = uint8, shape = (5, 7, 1)

```

**Comment by poxvoculi** [comment]
Thanks, I've added that one to the change.

**Comment by poxvoculi** [comment]
Will be fixed in upcoming release.
