### ISSUE TITLE
How to Retrain Final Layer for New Categories

### ISSUE THREAD

**Issue by GeorgeHamilton** [tensorflow/tensorflow#11976]
Could there be another or newer classification algorithm for image classification like ResNet etc? There are a lot of new neural nets with less classification error than Inception. ImageNet results: [http://image-net.org/challenges/LSVRC/2017/results](INCR)

**Comment by jubjamie** [comment]
Tensorflow has a model "zoo" accessible here: https://github.com/tensorflow/models including ResNet. There is a great collection of models old and new there.

p.s. your link appears to be broken.

**Comment by ali01** [comment]
Closing this issue. Feel free to reopen with follow up questions.
