### ISSUE TITLE
API request: MonitoredSession.run_without_hooks

### ISSUE THREAD

**Issue by netheril96** [tensorflow/tensorflow#11971]
Currently it is not possible to run a `MonitoredSession` without also calling the `before_run` and `after_run` methods of session hooks. But sometimes it is necessary. For example, I want to modify certain variables in the graph, but sometimes the `SummarySaverHook` decides it is time to collect summary, right when I am loading new values into the dependent variables, and then `Tensorboad` shows inconsistent results.

A `run_without_hooks` method will be immensely helpful.

**Comment by ppwwyyxx** [comment]
As a workaround you can call `monitored_session._tf_sess()` to get the underlying `tf.Session` object.
But I also hope there is a public API for it.

**Comment by netheril96** [comment]
If I access the raw session object, I lose the ability to auto recover session from errors.

**Comment by Mazecreator** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mazecreator@gmail.com
    Domain mazecreator.com has exceeded the max emails per hour (26/25 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:15392)
	by server2.lowesthostingrates.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-e6d9-mazecreator=mazecreator.com@sgmail.github.com>)
	id 1ddCtZ-0001cV-Vm
	for mazecreator@mazecreator.com; Thu, 03 Aug 2017 04:58:52 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Ayl8meCKAIQqUp1rNnHRvdykcDY=; b=OM3UNsmExvgJNqmS
	8pzFCBHdaWQGnpF1+LMgMeKvhZm9l5Kxf+kjedtTTDxUyktSbeqBuu7k+zLKbW93
	iOkbEEA6fwXkGNHLjCrDemh/ziRU/vSK9T2Kj5/XhDGiNQpCAiWLQ+EphHg7tjwO
	VB/7/xB1WKU/9mCSUNZxmHPTDtU=
Received: by filter0946p1mdw1.sendgrid.net with SMTP id filter0946p1mdw1-6752-5982F63E-41
        2017-08-03 10:09:02.70116664 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0038p1mdw1.sendgrid.net (SG) with ESMTP id ppjHDmtcTdq2ep_x12b6dA
	for <mazecreator@mazecreator.com>; Thu, 03 Aug 2017 10:09:02.673 +0000 (UTC)
Date: Thu, 03 Aug 2017 10:09:02 +0000 (UTC)

**Comment by isaprykin** [comment]
We added MonitoredSession.run_step_fn.  We hope it satisfies the use case.
