### ISSUE TITLE
CMake build with -Dtensorflow_BUILD_ALL_KERNELS=OFF does not work

### ISSUE THREAD

**Issue by MaxSavenkov** [tensorflow/tensorflow#11975]
Problem:

When building Tensorflow via CMake, specifying option tensorflow_BUILD_ALL_KERNELS=OFF leads to failed linker step due to unresolved external functions, because many important files (that are not kernels, but are necessary) are not included in build's list of sources (like ops_util.cc, but also other files).

Reproduction:

Follow instruction in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md, specify -Dtensorflow_BUILD_ALL_KERNELS=OFF to cmake.

**Comment by mrry** [comment]
We'd welcome fixes to the CMake build that make this work.

**Comment by yongtang** [comment]
Created a PR #13722 to fix the error in CMAKE + `Dtensorflow_BUILD_ALL_KERNELS=OFF`. With the PR, the cmake with `-Dtensorflow_BUILD_ALL_KERNELS=OFF` should work now (tested on Linux).
