### ISSUE TITLE
Problem with OpenCV - Initializing TensorFlow variables takes very long

### ISSUE THREAD

**Issue by tomrunia** [tensorflow/tensorflow#1197]
For some reason, the variable initialization of TensorFlow takes a very long time when OpenCV is imported (`import cv2`). Running the operation `tf.init_all_variables()` takes less than 1 second without OpenCV, but as soon as I import `cv2` this takes 22 seconds (!). See attachment for the simple - Hello World - code that I run. [hello_world.txt](https://github.com/tensorflow/tensorflow/files/138119/hello_world.txt) 

This problem occurs in TensorFlow 0.6 and 0.7. During the initialization the CPU load is 100%, GPU is idle but all available memory is initialized by TensorFlow.

```
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.7.0
```

TensorFlow is installed in an virtualenv using `pip` after installing CUDA Toolkit 7.5 and CuDNN v3. My OpenCV installation is from sources (GitHub, master), so this is version 3.1+. Some possibly relevant installation parameters are `WITH_CUDA=ON`, `WITH_CUBLAS=OFF`.

I am using a powerful machine running Linux Mint, 32 CPU cores and an Titan X.

**Comment by martinwicke** [comment]
Mysterious. I don't know what cv2 does, but since you are building it with Cuda, it could be preallocating GPU memory (similar to what tensorflow does). The symptom is decidedly odd though. @zheng-xq, do you have an idea?

**Comment by tomrunia** [comment]
Oke, I just recompiled OpenCV 3.1 without CUDA support (i.e. `WITH_CUDA=OFF`) and this solved the problem. TensorFlow initialization with and without `import cv2` is now fast. So it seems like there is an incompatibility with TensorFlow and OpenCV compiled with CUDA. Like you said, probably both TF and OpenCV are initializing GPU memory at the same time which causes trouble?

**Comment by zheng-xq** [comment]
TF takes most of the GPU memory upon its initialization. You can set the following session config to use smaller amount of memory:

config.gpu_options.per_process_gpu_memory_fraction

If that doesn't work, then it is useful to look at some profiling results and see where the cycles are spent.

**Comment by girving** [comment]
Closing for now.  For better or worse, TensorFlow assumes it owns the whole GPU, so other libraries trying to use the GPU at the same time will cause issues.
