### ISSUE TITLE
tensorflow Makefile build does not support building arm64-v8a static library for Android

### ISSUE THREAD

**Issue by AngryPowman** [tensorflow/tensorflow#11996]
Currently tensorflow has only support build static library in `armeabi-v7a` for Android.  

And the build script has not support the other platforms yet as we can see in:
 [`tensorflow/tensorflow/contrib/makefile/Makefile`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/Makefile#L219)

Our team would like to build all the architecture for Android if possible, and we tried to fixed the `makefile` that expect to link with our Android project but got many linking errors except `armeabi-v7a`.

So, I was just wondering if tensorflow will support those platform: `arm64-v8a`, `x86`, `x88_64`?

**Comment by gautam1858** [comment]
Tensorflow has support for arm64-v8a armeabi armeabi-v7a armeabi-v7a-hard mips mips64 x86 x86_64

**Comment by AngryPowman** [comment]
@gautam1858 There is a TODO tips comment in makefile says: it will support all architectures but currently only supported `armeabi-v7a`. I mean, the static libraries.

**Comment by gautam1858** [comment]
It had worked for, I build the object file with bazel and --cpu=arm64-v8a architecture

**Comment by andrewharp** [comment]
@AngryPowman As @gautam1858 notes, you can build TF for all supported mobile architectures with Bazel.

These libraries are also published in the [prebuilt nightly libs](https://ci.tensorflow.org/view/Nightly/job/nightly-android/) and the TensorFlow AAR also contains them (usage described [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/android)), which is the recommended way of integrating TF if you don't need custom functionality.

We don't have build support for other architectures using the Makefile build yet, but user contributions are welcome to remedy that.
