### ISSUE TITLE
tensorflow multi label classification

### ISSUE THREAD

**Issue by latoureiffel** [tensorflow/tensorflow#11998]
How does tensorflow CNN implement multi label classification, specifically how to input multi tags and output multi label prediction results?

**Comment by gautam1858** [comment]
You could have a look at this #113

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
