### ISSUE TITLE
Remote worker configuration

### ISSUE THREAD

**Issue by kmatzen** [tensorflow/tensorflow#12]
Does this release support remote workers out of the box?  I couldn't find details in the tutorials, but the whitepaper and ```tensorflow/core/common_runtime/device.h``` talked about adding remote devices through RPC.  Is a parameter server or alternative already implemented in here somewhere?  If remote workers are supported out of the box, what is the execution model?  Is there a daemon or do you have to configure a session in a certain way to act as one?

**Comment by ebrevdo** [comment]
This release does not support distributed computation.

**Comment by vrv** [comment]
Hi kmatzen: As mentioned in our FAQ, this release does not have an RPC and distributed implementation available yet: http://tensorflow.org/resources/faq.md#running_a_tensorflow_computation, but we are working on it and hope to make it available when it's ready.

As a short-term proxy, you can see the Cifar tutorial for an example of how training and distributing among multiple GPUs works -- http://tensorflow.org/tutorials/deep_cnn/index.md

**Comment by vrv** [comment]
(De-duping with https://github.com/tensorflow/tensorflow/issues/23)
