### ISSUE TITLE
Expose Tensorflow Go library as cgo_library rule in Bazel

### ISSUE THREAD

**Issue by amlinux** [tensorflow/tensorflow#12009]
Currently it's not possible to reference @org_tensorflow//tensorflow/go:go_default_library from a BUILD file. It would be great to have this ability.

**Comment by asimshankar** [comment]
Currently, the go libraries are structured to be friendly to the common use of the go toolchain (i.e., the common use with `go get`). 

Could you elaborate a bit on the feature requested here? Is it that you have a project that uses `bazel` as the build system and want to build all of tensorflow (including the go libraries) from source after adding tensorflow as an external dependency to the `WORKSPACE` of your project? If so, it's unlikely that anyone on the TensorFlow team will get to making that work in the near future. Or is it something else?

**Comment by amlinux** [comment]
That's exactly what I want. If no one objects against this idea, I'll probably spend some time implementing it.

**Comment by asimshankar** [comment]
Sure, if the change isn't particularly intrusive, we'd be happy to accept it.
Marking this as contributions welcome.

**Comment by sushreebarsa** [comment]
@amlinux A reference could be [golang-tensorflow](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md)  that provides Go wrappers for TensorFlow C++.
If you still have a concern then please create a new ticket as you are using an older version of TF which is not actively supported.
Thank you!
