### ISSUE TITLE
Missing tensorflow/core/debug/debug_service.grpc.pb.h header file

### ISSUE THREAD

**Issue by rlegithub** [tensorflow/tensorflow#12018]
Hi,

debug_io_utils.h includes a header file tensorflow/core/debug/debug_service.grpc.pb.h, which is missing from the repo. This causes build on Linux failed. 

`// TODO(cais): Support grpc:// debug URLs in open source once Python grpc
//   genrule becomes available. See b/23796275.

#ifndef PLATFORM_WINDOWS
#include "tensorflow/core/debug/debug_service.grpc.pb.h"
`
Anyone see this issue?

Thanks,
RLE

**Comment by rlegithub** [comment]
@caisq I think this change may relates to the problem: https://github.com/tensorflow/tensorflow/commit/41803db36d4f4a3239bd81e5d460eb0e6e2eea88

That changes #if defined(PLATFORM_GOOGLE) to #ifndef PLATFORM_WINDOWS, which essentially allows it to #include "tensorflow/core/debug/debug_service.grpc.pb.h" on Linux but that file does not exist on the master branch.

Could you help taking a look?

**Comment by caisq** [comment]
`debug_service_grpc.pb.h` is an automatically generated file from this bazel BUILD rule:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/debug/BUILD#L45

So there should be no problem building TF is you are using bazel. What build tool are you using?

**Comment by rlegithub** [comment]
I used Linux Continuous Integration Build steps from this link: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md

**Comment by caisq** [comment]
So I see that you are running cmake build on Linux. This is our nightly build:
http://ci.tensorflow.org/view/Nightly/job/nightly-cmake-cpu/

It seems to be okay. You can look at the log to see what commands / configuration it uses:
http://ci.tensorflow.org/view/Nightly/job/nightly-cmake-cpu/368/consoleFull

**Comment by gmaher** [comment]
On Ubuntu 16 with anaconda 2.7, when running 

cmake -DCMAKE_BUILD_TYPE=Release ../tensorflow/contrib/cmake
make -j6 all

I get the error: fatal error: tensorflow/core/debug/debug_service.grpc.pb.h: No such file or directory

Any ideas how to resolve this?

**Comment by yongtang** [comment]
Encountered the similar issue. The 
```
tensorflow/core/debug/debug_service.pb.h
```
was generated but not
```
tensorflow/core/debug/debug_service.grpc.pb.h
```
so the make fails.

I assume `*.grpc.pb.h` might be generated with grpc plugins though I am not familiar with cmake so not sure how to fix it.

**Comment by kaspermarstal** [comment]
Confirmed on Mac OS X using CMake 3.7.2.

**Comment by yongtang** [comment]
Created a PR #13145 that should fix the cmake issue on Linux.
