### ISSUE TITLE
run within PHP 

### ISSUE THREAD

**Issue by billidani7** [tensorflow/tensorflow#1201]
Is it possible to run 

`bazel-bin/tensorflow/examples/label_image/label_image`

inside PHP script and echo the output of main.cc to PHP script?

Is there any way to remotely call and get the results?

**Comment by krzysztof-magosa** [comment]
There is separate project named TensorFlow Serving.
You could call API from PHP.

**Comment by girving** [comment]
This is a question about how to use PHP to invoke processes, not a TensorFlow issues.
