### ISSUE TITLE
Parallelize bottleneck creation in retraining script

### ISSUE THREAD

**Issue by yousufzu** [tensorflow/tensorflow#12025]
Hi

It might be possible to parallelize the creation of the bottleneck files in the Inception retraining script. Currently it can only do a few images per second and if you have 100s of thousands of images, it takes forever. I could do it myself also and create a pull request, if that's fine.

Thanks

**Comment by yaroslavvb** [comment]
If you have an improved version, you should just go ahead with a pull request (I'm guessing it's under files in tensorflow/models repo)
