### ISSUE TITLE
tf.contrib.distributions.percentile returning AttributeError

### ISSUE THREAD

**Issue by abuvaneswari** [tensorflow/tensorflow#12024]
Hello,

I am trying to utilize tf.contrib.distributiions.percentile as described in:
https://www.tensorflow.org/api_docs/python/tf/contrib/distributions/percentile 

- OS Platform and Distribution :  Ubuntu 14.04
- TensorFlow installed from binary
- TensorFlow version : 1.2.0
- Python version: 3.4.5

My invocation is as follows:
pctl_val = tf.contrib.distributions.percentile(grad_values, pctl)

Here is the error message that I get:
AttributeError: 'module' object has no attribute 'percentile'

I understand that the percentile feature was not available in 1.1.0 and it is now available in 1.2.0. Still, why do I get the error?

**Comment by shivaniag** [comment]
With Tensorflow version 1.2.0, I am not getting this error. Could you please check if your Tensorflow version has been upgraded correctly. 
Feel free to reopen this issue if this problem persists.
