### ISSUE TITLE
Model callbacks don't work in TF r1.2 and Keras functional API (Python 3.6 + windows 10)

### ISSUE THREAD

**Issue by NatLun091238** [tensorflow/tensorflow#12039]
Two test cases were constructed in order to show better the problem with "Model callbacks, which don't work in TF r1.2 and Keras functional API".

1/ Callbackes were used in the following way:
#------------ checkpoints -------------------------------
import tensorflow.contrib.keras as K
filedest="./models/weights_model011a.best.hdf5"
checkpoint = K.callbacks.ModelCheckpoint(filedest, monitor='val_acc', verbose=1, 
                             save_best_only=True, mode='max')

checkRLR = K.callbacks.ReduceLROnPlateau(monitor='val_acc', factor=0.1, 
                                         patience=7,min_lr=1.0e-10)

earlyStop = K.callbacks.EarlyStopping(monitor='val_acc', patience=30)
tbgraph = K.callbacks.TensorBoard(log_dir='./graphs', histogram_freq=1, 
                      write_graph=True, write_images=False, 
                      embeddings_freq=1)

callbacks_list = [checkpoint,earlyStop,checkRLR,tbgraph]

and then:
history = model.fit(X_train, y_train[:11200], validation_data=(X_test, y_tst_cat[:7200]),
          epochs=epochs, batch_size=40,shuffle=True,
          callbacks=callbacks_list, verbose=0)

That resulted in successful run through the training session, but with the following info:
INFO:tensorflow:Summary name embedding/embeddings:0 is illegal; using embedding/embeddings_0 instead.
INFO:tensorflow:Summary name conv1d/kernel:0 is illegal; using conv1d/kernel_0 instead.
INFO:tensorflow:Summary name conv1d/bias:0 is illegal; using conv1d/bias_0 instead.
INFO:tensorflow:Summary name conv1d_1/kernel:0 is illegal; using conv1d_1/kernel_0 instead.
INFO:tensorflow:Summary name conv1d_1/bias:0 is illegal; using conv1d_1/bias_0 instead.
INFO:tensorflow:Summary name conv1d_2/kernel:0 is illegal; using conv1d_2/kernel_0 instead.
INFO:tensorflow:Summary name conv1d_2/bias:0 is illegal; using conv1d_2/bias_0 instead.
INFO:tensorflow:Summary name conv1d_3/kernel:0 is illegal; using conv1d_3/kernel_0 instead.
INFO:tensorflow:Summary name conv1d_3/bias:0 is illegal; using conv1d_3/bias_0 instead.
INFO:tensorflow:Summary name conv1d_4/kernel:0 is illegal; using conv1d_4/kernel_0 instead.
INFO:tensorflow:Summary name conv1d_4/bias:0 is illegal; using conv1d_4/bias_0 instead.
INFO:tensorflow:Summary name dense/kernel:0 is illegal; using dense/kernel_0 instead.
INFO:tensorflow:Summary name dense/bias:0 is illegal; using dense/bias_0 instead.

2/ Callbacks were used with Keras functional API in similar way, described above. The run resulted in similar info message PLUS the following:
C:\path\AppData\Local\Continuum\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\keras\python\keras\callbacks.py:411: RuntimeWarning: Can save best model only with val_acc available, skipping.
  'skipping.' % (self.monitor), RuntimeWarning)
C:\path\AppData\Local\Continuum\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\keras\python\keras\callbacks.py:499: RuntimeWarning: Early stopping requires val_acc available!
  RuntimeWarning)
Traceback (most recent call last):

  File "<ipython-input-1-70e23aa02b0a>", line 1, in <module>
    runfile('C:/path_to_the files/Test_bugs/NonTagTFmodel_local_v011.py', wdir='C:/path_to_the files/Test_bugs')

  File "C:\path\AppData\Local\Continuum\Miniconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\path\AppData\Local\Continuum\Miniconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/path/Documents/Python Scripts/Recognition/Run09recipes/Test_bugs/NonTagTFmodel_local_v011.py", line 149, in <module>
    callbacks=callbacks_list, verbose=0)

  File "C:\path\AppData\Local\Continuum\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\keras\python\keras\engine\training.py", line 1495, in fit
    initial_epoch=initial_epoch)

  File "C:\path\AppData\Local\Continuum\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\keras\python\keras\engine\training.py", line 1158, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)

  File "C:\path\AppData\Local\Continuum\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\keras\python\keras\callbacks.py", line 96, in on_epoch_end
    callback.on_epoch_end(epoch, logs)

  File "C:\path\AppData\Local\Continuum\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\keras\python\keras\callbacks.py", line 501, in on_epoch_end
    if self.monitor_op(current - self.min_delta, self.best):

TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

The same code (TF r1.2 and Keras functional API) runs perfectly alright if 'callbacks=None':
history = model.fit(X_train, [Y_tr_hot,y_tr_cat[:11200]], validation_data=(X_test, [Y_ts_hot,y_ts_cat[:7200]]),
          epochs=epochs, batch_size=40, shuffle=True,
          callbacks=None, verbose=1)

What can be the reason for Model callbacks not working???

**Comment by poxvoculi** [comment]
It's not clear to me whether you have evidence for a bug in TensorFlow, or are looking for help in understanding how to use Keras with TensorFlow.  Unless this is a bug report, please ask your question on stackoverflow, where there is a larger and more active community addressing usage questions.

If you believe there is a bug, please provide all of the information requested in the issue template, along with a minimal reproducible example.   Note that the windows port of TF is not fully functional (see [notes](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md)).

**Comment by NatLun091238** [comment]
Sorry, I found mistake in my code. Everything is working now as it should.
