### ISSUE TITLE
RDMA+verbs stuck in some nodes

### ISSUE THREAD

**Issue by sj6077** [tensorflow/tensorflow#12035]
System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
Yes, I made custom distributed inception code
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 14.04
TensorFlow installed from (source or binary): Unmodified source with RDMA Verbs enabled
TensorFlow version (use command below): 1.3.0-rc1
Python version: 2.7.12
Bazel version (if compiling from source): 0.5.1
CUDA/cuDNN version: 8.0/5.1.5
GPU model and memory: NVIDIA TITAN Xp PCIe 12GB (4 per node)

The code works for normal grpc, but stuck between some nodes, not between all nodes.
I've tested all nodes with ib_write_bw and ibv_rc_pingpong, communication between all of the nodes works fine.

**Comment by byronyi** [comment]
Maybe it is related to #11416 and #11725.

Could you provide a minimal reproducing script? Some logs help, too.

**Comment by sj6077** [comment]
There are no explicit logs, but just hanging. 
It's the hardware information for the failed node. 

ibv_devinfo | grep board_id
	board_id:			DEL2180110032
	board_id:			MT_2180110032

The hardware information is different in successful nodes. Can it be related?
ibv_devinfo | grep board_id
       board_id:			DEL2180110032
       board_id:			DEL2180110032

**Comment by shamoya** [comment]
@sj6077 , how many GPUs per node ? how many node ?
Are u training Inception in Sync data parallelism ? 
As @byronyi mentioned, sounds like #11725 , which is still under investigation.

**Comment by sj6077** [comment]
There are 4 GPUs per node, and I tested with 3 nodes, 6 workers(2 workers per node nad 2 GPUs per worker). Yes, I trained with inception in sync data parallelism. Then I can wait with  #11725.

**Comment by shamoya** [comment]
@sj6077 - Didn't tried Cifar10 but it happens with ResNet and trivial models as well when running [tf_cnn_benchmark](https://github.com/tensorflow/benchmarks/blob/master/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py). Which GPUs are you using ? One thing we suspect is that it relates to Pascal GPUs only 
Also what is the Parameter Servers configuration (1 dedicated, in each node, etc..) ?

**Comment by sj6077** [comment]
I used dedicated and colocated parameter server with worker both, I used same GPUs for all of the machines, which is TITAN Xp.

**Comment by shamoya** [comment]
Hi @sj6077, 

Per progress in #11725, can please configure the Session with high values of  inter/intra_op_parallelism_threads (I tried 500) and recheck ?
It's just a workaround, to see if we indeed experiencing the same issue.

**Comment by sj6077** [comment]
I tried with inter/intra_op_parallelism_threads=500, 3000, but it doesn't work. In my case, sessions are not created for some nodes.

**Comment by shamoya** [comment]
Thanks @sj6077, maybe it's too much threads for your system.
Anyway @yanivbl6 found has a real fix (not workaround) for the problem.
Once he will PR it, I'll ping you to try it to verify it works.

**Comment by shamoya** [comment]
@sj6077 , The fix in #12361 , feel free to try it out.

**Comment by shamoya** [comment]
@sj6077, can we close this one?

**Comment by sj6077** [comment]
Sure! Thank you for the fix.
