### ISSUE TITLE
Missing tf_python_protos_cc library dependency in tf_tutorials.cmake

### ISSUE THREAD

**Issue by rasitsimsek** [tensorflow/tensorflow#12037]
### System information
Windows10
VisualStudio 2017
TensorFlow 1.3.0
Python 3.5.3
CMake 3.8.1

### Describe the problem
I can't build **tf_tutorials_example_trainer** due missing library dependency to tf_python_protos_cc.lib. A lot of linking errors occurred. If the bold line is added into tf_tutorials.cmake then the compilation works:

target_link_libraries(tf_tutorials_example_trainer PUBLIC
    tf_protos_cc
    **tf_python_protos_cc**
    ${tf_core_gpu_kernels_lib}
    ${tensorflow_EXTERNAL_LIBRARIES}
)

CMake is used build the project files for VisualStudio. 

![image](https://user-images.githubusercontent.com/30691148/28971246-95f12174-792b-11e7-8d9f-5bb5542a5ce0.png)

### Source code / logs
`1>------ Build started: Project: tf_tutorials_example_trainer, Configuration: Release x64 ------
1>   Creating library C:/Development/dev/test_projects/deeplearning/tensorflow_build64/Release/tf_tutorials_example_trainer.lib and object C:/Development/dev/test_projects/deeplearning/tensorflow_build64/Release/tf_tutorials_example_trainer.exp
1>ensemble_optimizer_ops.cc.obj : error LNK2019: unresolved external symbol "public: __cdecl tensorflow::boosted_trees::trees::DecisionTreeConfig::DecisionTreeConfig(void)" (??0DecisionTreeConfig@trees@boosted_trees@tensorflow@@QEAA@XZ) referenced in function "public: static class tensorflow::boosted_trees::trees::DecisionTreeConfig * __cdecl google::protobuf::Arena::CreateMessage<class tensorflow::boosted_trees::trees::DecisionTreeConfig>(class google::protobuf::Arena *)" (??$CreateMessage@VDecisionTreeConfig@trees@boosted_trees@tensorflow@@@Arena@protobuf@google@@SAPEAVDecisionTreeConfig@trees@boosted_trees@tensorflow@@PEAV012@@Z)
1>prediction_ops.cc.obj : error LNK2001: unresolved external symbol "public: __cdecl tensorflow::boosted_trees::trees::DecisionTreeConfig::DecisionTreeConfig(void)" (??0DecisionTreeConfig@trees@boosted_trees@tensorflow@@QEAA@XZ)
1>training_ops.cc.obj : error LNK2001: unresolved external symbol "public: __cdecl tensorflow::boosted_trees::trees::DecisionTreeConfig::DecisionTreeConfig(void)" (??0DecisionTreeConfig@trees@boosted_trees@tensorflow@@QEAA@XZ)
1>ensemble_optimizer_ops.cc.obj : error LNK2019: unresolved external symbol "public: void __cdecl tensorflow::boosted_trees::trees::DecisionTreeConfig::Swap(class tensorflow::boosted_trees::trees::DecisionTreeConfig *)" (?Swap@DecisionTreeConfig@trees@boosted_trees@tensorflow@@QEAAXPEAV1234@@Z) referenced in function "public: virtual void __cdecl tensorflow::AddTreesToEnsembleOp::Compute(class tensorflow::OpKernelContext * const)" (?Compute@AddTreesToEnsembleOp@tensorflow@@UEAAXQEAVOpKernelContext@2@@Z)
1>ensemble_optimizer_ops.cc.obj : error LNK2019: unresolved external symbol "protected: __cdecl tensorflow::boosted_trees::trees::DecisionTreeConfig::DecisionTreeConfig(class google::protobuf::Arena *)" (??0DecisionTreeConfig@trees@boosted_trees@tensorflow@@IEAA@PEAVArena@protobuf@google@@@Z) referenced in function "public: static class tensorflow::boosted_trees::trees::DecisionTreeConfig * __cdecl google::protobuf::Arena::CreateMessage<class tensorflow::boosted_trees::trees::DecisionTreeConfig>(class google::protobuf::Arena *)" (??$CreateMessage@VDecisionTreeConfig@trees@boosted_trees@tensorflow@@@Arena@protobuf@google@@SAPEAVDecisionTreeConfig@trees@boosted_trees@tensorflow@@PEAV012@@Z)
1>training_ops.cc.obj : error LNK2001: unresolved external symbol "protected: __cdecl tensorflow::boosted_trees::trees::DecisionTreeConfig::DecisionTreeConfig(class google::protobuf::Arena *)" (??0DecisionTreeConfig@trees@boosted_trees@tensorflow@@IEAA@PEAVArena@protobuf@google@@@Z)
1>ensemble_optimizer_ops.cc.obj : error LNK2019: unresolved external symbol "public: __cdecl tensorflow::boosted_trees::trees::DecisionTreeMetadata::DecisionTreeMetadata(void)" (??0DecisionTreeMetadata@trees@boosted_trees@tensorflow@@QEAA@XZ) referenced in function "public: static class tensorflow::boosted_trees::trees::DecisionTreeMetadata * __cdecl google::protobuf::Arena::CreateMessage<class tensorflow::boosted_trees::trees::DecisionTreeMetadata>(class google::protobuf::Arena *)" (??$CreateMessage@VDecisionTreeMetadata@trees@boosted_trees@tensorflow@@@Arena@protobuf@google@@SAPEAVDecisionTreeMetadata@trees@boosted_trees@tensorflow@@PEAV012@@Z)
1>training_ops.cc.obj : error LNK2001: unresolved external symbol "public: __cdecl tensorflow::boosted_trees::trees::DecisionTreeMetadata::DecisionTreeMetadata(void)" (??0DecisionTreeMetadata@trees@boosted_trees@tensorflow@@QEAA@XZ)
1>ensemble_optimizer_ops.cc.obj : error LNK2019: unresolved external symbol "protected: __cdecl tensorflow::boosted_trees::trees::DecisionTreeMetadata::DecisionTreeMetadata(class google::protobuf::Arena *)" (??0DecisionTreeMetadata@trees@boosted_trees@tensorflow@@IEAA@PEAVArena@protobuf@google@@@Z) referenced in function "public: static class tensorflow::boosted_trees::trees::DecisionTreeMetadata * __cdecl google::protobuf::Arena::CreateMessage<class tensorflow::boosted_trees::trees::DecisionTreeMetadata>(class google::protobuf::Arena *)" (??$CreateMessage@VDecisionTreeMetadata@trees@boosted_trees@tensorflow@@@Arena@protobuf@google@@SAPEAVDecisionTreeMetadata@trees@boosted_trees@tensorflow@@PEAV012@@Z)
1>training_ops.cc.obj : error LNK2001: unresolved external symbol "protected: __cdecl tensorflow::boosted_trees::trees::DecisionTreeMetadata::DecisionTreeMetadata(class google::protobuf::Arena *)" (??0DecisionTreeMetadata@trees@boosted_trees@tensorflow@@IEAA@PEAVArena@protobuf@google@@@Z)

**...**

1>C:\Development\dev\test_projects\deeplearning\tensorflow_build64\Release\tf_tutorials_example_trainer.exe : fatal error LNK1120: 85 unresolved externals
1>Done building project "tf_tutorials_example_trainer.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by poxvoculi** [comment]
I'm puzzled that if this is broken, we don't have a failing test.  Could it be something in your environment?  Meanwhile, pinging our very overcommitted @mrry.

**Comment by rasitsimsek** [comment]
In the tf_tutorials_example_trainer project they are dependency to tensorflow::boosted_trees. The declarations and definitions for bosstet_trees module is in the tf_python_protos_cc project what I have found.

**Comment by mrry** [comment]
Which branch are you building? (It looks like b4056fcc2c1a7003c190e1345b8b534d8353e21a affects how `boosted_trees` is built in CMake, but I can't tell if it's included in your change or not.)

I'm puzzled about why adding `tf_python_protos_cc` fixes things, since (i) the example binary is a pure C++ binary, and (ii) it doesn't appear to depend on any of the `boosted_trees` code....

/cc @ThomasColthurst

**Comment by mrry** [comment]
PS. @poxvoculi to answer your puzzlement, we don't build this as part of any of the CI builds, because it isn't a binary that we ship, and we're constrained on testing resources :(.

**Comment by arena** [comment]
The code in the original comment wasn't formatted as code so all the local variables are interpreted as usernames.

**Comment by j30206868** [comment]
The same problems happened to me.
My system information:
Windows 7
Visual Studio 2015
Tensorflow v1.3.0-rc2
Python 3.5.2
cmake version 3.6.2
And my cmake setting
![image](https://user-images.githubusercontent.com/4746227/29161448-dfa05d78-7de8-11e7-9ef8-46e823105891.png)

**In addition the issue occurs in 6 other projects to me**:
compare_graph 
summarize_graph 
transform_graph 
benchmark_model
tf_label_image_example
grpc_tensorflow_server 

**So i apply to same modification** to below three cmake files **as what rasitsimsek have done to tf_tutorials.cmake**
- tf_tools.cmake 
- tf_core_distributed_runtime.cmake 
- tf_label_image_example.cmake

**Comment by rasitsimsek** [comment]
j30206868 is right. There are more lack of dependencies in other projects. The tensorflow project is mainly focused on Python and not other languages like C++ only projects. I have managed to build a C++ CMake project on without in the tensorflow environment. Under C++ it is not running out of the box. There is a lot research needed to put all library and include dependencies together.
