### ISSUE TITLE
Possible bug in    master/tensorflow/python/ops/rnn.py

### ISSUE THREAD

**Issue by nddk** [tensorflow/tensorflow#1204]
in rnn.py and the function def _rnn_step(...):

line 261: copy_cond = (time >= sequence_length)

sequence_length is a vector of ints and time is an int,  should time be compared with one element of sequence_length, instead of the whole thing? 

(Is this function still work in progress?)

**Comment by ebrevdo** [comment]
The inequality broadcasts, and the resulting variable is a vector. The vector decides for each batch entry whether to copy through or not.

It's a feature, not a bug!

**Comment by eZii-jester-data** [comment]
Hey, what's the status of this "feature"?
