### ISSUE TITLE
[docs] Broken link on Tool Developer's page

### ISSUE THREAD

**Issue by MatthewScholefield** [tensorflow/tensorflow#12042]
Source page: https://www.tensorflow.org/extend/tool_developers/

Bad link (`graph_run_run2.pbtxt`): https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/components/tf_tensorboard/test/data/graph_run_run2.pbtxt

**Comment by shivaniag** [comment]
@wolffg could you please update it.

**Comment by alanyee** [comment]
@MatthewScholefield @shivaniag The bad link is already fixed here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/extend/tool_developers/index.md

You have to wait until they update the website, so please close this issue for now.

**Comment by wolffg** [comment]
This commit (https://github.com/tensorflow/tensorflow/commit/d30efdbaa2b80bf4eb8db9e0b94501fdbd4107d8) fixes the link.  However, the root version of tensorflow.org docs represents what's in the current public binary branch; in this case, it reflects the docs as they were when we cut r1.2.  Unless that's cherrypicked back into r1.2, documentation won't get updated.  This is a known limitation/feature of having versioned documentation.

However, as r1.3 will be coming soon to root, I've submitted that CL to be cherrypicked back into r1.3, so when r1.3 is up this link will be fixed.

I'm closing this, then, as there's no further action needed.
