### ISSUE TITLE
tf.contrib.util.make_ndarray is slow the first time it is run

### ISSUE THREAD

**Issue by chrisranderson** [tensorflow/tensorflow#12043]
### System information

**Output of tf_env_collect.sh:** [tf_env.txt](https://github.com/tensorflow/tensorflow/files/1201133/tf_env.txt)

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.3.0-rc1-479-g82456f9 1.2.1-rc1
- **Python version**: Python 3.5.2
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**:
== cuda libs  ===================================================
/usr/local/cuda-8.0/doc/man/man7/libcudart.7
/usr/local/cuda-8.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-8.0/lib64/libcudart.so.8.0.61
/usr/local/cuda-8.0/lib64/libcudart_static.a
/usr/local/lib/python3.5/dist-packages/torch/lib/libcudart.so.8.0
/usr/local/cuda-7.5/doc/man/man7/libcudart.7
/usr/local/cuda-7.5/doc/man/man7/libcudart.so.7
/usr/local/cuda-7.5/lib/libcudart.so.7.5.18
/usr/local/cuda-7.5/lib/libcudart_static.a
/usr/local/cuda-7.5/lib64/libcudart.so.7.5.18
/usr/local/cuda-7.5/lib64/libcudart_static.a

- **GPU model and memory**:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 381.22                 Driver Version: 381.22                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 0000:01:00.0      On |                  N/A |
| N/A   48C    P0    28W /  N/A |    591MiB /  6064MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

```
- **Exact command to reproduce**:
Download  [frame.summary.zip](https://github.com/tensorflow/tensorflow/files/1201101/frame.summary.zip) and extract it to `frame.summary`. Some info about it:

```
tensor_proto dtype: DT_UINT8
tensor_shape {
  dim {
    size: 1059
  }
  dim {
    size: 768
  }
}
```

Run the following:

```python
import time
from google.protobuf import message
import tensorflow as tf

for i in range(2):
  path = 'frame.summary'
  with open(path, 'rb') as summary_file:
    summary_string = summary_file.read()

  summary_proto = tf.Summary()
  summary_proto.ParseFromString(summary_string)
  tensor_proto = summary_proto.value[0].tensor
  a = time.time()
  array = tf.contrib.util.make_ndarray(tensor_proto)
  b = time.time()
  print('b-a', b-a)
```

### Describe the problem
The first time `make_ndarray` is run, it takes a long time. For this isolated example, the output is this on my machine:
```
b-a 2.810185194015503
b-a 0.00030040740966796875
```
In my project, it took 105.96585726737976 for the first run, and 0.0005743503570556641 the second time (and closer to 0.0003 afterwards).

### Source code / logs
Here is the branch I was using : https://github.com/chrisranderson/beholder/tree/bug-report
And the line that took ~105 seconds: https://github.com/chrisranderson/beholder/blob/b54d4203d803492af9852b7c8453e8a1e5342f46/beholder/file_system_tools.py#L34

**Comment by chrisranderson** [comment]
I don't have the same problem with `tf.make_ndarray` (thanks @wchargin!).
```
b-a 0.0008018016815185547
b-a 0.0006482601165771484
```

**Comment by wchargin** [comment]
I can reproduce your issue, and fix it as follows:
```diff
--- sumbench.py	2017-08-04 10:50:21.550342085 -0700
+++ sumbench2.py	2017-08-04 10:50:26.258294226 -0700
@@ -10,6 +10,7 @@
   summary_proto = tf.Summary()
   summary_proto.ParseFromString(summary_string)
   tensor_proto = summary_proto.value[0].tensor
+  tf.contrib.util
   a = time.time()
   array = tf.contrib.util.make_ndarray(tensor_proto)
   b = time.time()
```
(My results aren't quite as bad as yours—0.2448s vs. 0.0004s—but I assume that we're hitting the same thing.)

It's just a benchmarking error: you're loading all of `tf.contrib` during your benchmark.

You can similarly fix this without the above change by using `tf.make_ndarray` instead of `tf.contrib.util.make_ndarray`, for the same reason.

**Comment by wchargin** [comment]
(Relevant: [one](https://github.com/tensorflow/tensorflow/blob/0542739b9a88bebb2f74b8e9a6db15c5a845d480/tensorflow/__init__.py#L28), [two](https://github.com/tensorflow/tensorflow/blob/0542739b9a88bebb2f74b8e9a6db15c5a845d480/tensorflow/python/util/lazy_loader.py).)

**Comment by yaroslavvb** [comment]
As @wchargin points out, it's due to loading of tf.contrib. Here's a self-contained benchmark which doesn't show the difference


```
import time
import tensorflow as tf
import numpy as np

a = [1]*10000
tf.contrib.util.make_ndarray
for i in range(5):
  from tensorflow.python.framework import tensor_util
  tensor_proto = tensor_util.make_tensor_proto(a)
  a = time.time()
  array = tf.contrib.util.make_ndarray(tensor_proto)
  b = time.time()
  print('b-a', b-a)
```

**Comment by chrisranderson** [comment]
Thank you both! Any idea why it took 105 seconds in the context of my application? Feel free to close if you'd like.

**Comment by wchargin** [comment]
I have no idea.
