### ISSUE TITLE
tf.contrib.distributions - Additional Distributions

### ISSUE THREAD

**Issue by Arvinds-ds** [tensorflow/tensorflow#12057]
Are there plans to add additional distributions in the tf.contrib.distributions module like Scaled Inverse Chi-Sq, LKJ, Gumbel etc?  Could mirror the distribution list supported by STAN

**Comment by tatatodd** [comment]
@jvdillon @langmore @rsepassi Can you comment on this?  Thanks!

**Comment by jvdillon** [comment]
Sorry for our delayed response. We're working on adding a batch of new distributions. Ill make sure these (and Stan's) are on our list.

**Comment by Arvinds-ds** [comment]
Thanks
