### ISSUE TITLE
Inconsistent memory usage between CPU and GPU

### ISSUE THREAD

**Issue by jstaker7** [tensorflow/tensorflow#1205]
Running a large network on CPU uses ~2GB memory, whereas running the same network on GPU takes ~6GB of memory (the full size of the card). Is it just allocating all the available GPU memory even though it might not all be utilized? This is using the recent 0.7 pip version.

**Comment by petewarden** [comment]
The memory optimizations between the CPU and GPU approaches are very different. In particular the GPU version will often allocate more memory to take advantage of batching and other approaches that speed up operations on CUDA devices. Is this causing an issue for you, or are you just interested in the inconsistency?

**Comment by jstaker7** [comment]
I wouldn't necessarily call it an issue blocking me from completing my work, but I was interested in using nvidia-smi to gauge how resource intensive my network is so that I could evaluate scaling potential. Not a big deal though since I can increase batch size until the network fails to load onto the GPU.

**Comment by vrv** [comment]
We'll have better tools to understand memory utilization soon, I hope.  Closing for now, thanks!
