### ISSUE TITLE
an API to tell TF ABI

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#12051]
This is a feature request.
TF pip packages might be built with different C++ ABI. The released binaries are built with old ABI. If a user manually compile it with gcc>=5, the default is to use new CXX11 ABI (unless explicitly changed).

As someone who wrote custom ops, this could cause trouble: the op has to be compiled with the same ABI, otherwise there will be issues like #10714 #9137. Therefore the user of my ops would need to be aware of what ABI he's using, and change the flags manually.

I hope there is an API simply tells what ABI should be used when compiling user ops, similar to `tf.sysconfig.get_include()` which tells what path to include.

**Comment by yaroslavvb** [comment]
cc @keveman

**Comment by tatatodd** [comment]
@asimshankar Do you have any suggestions here?  C++ ABI compatibility is a can of worms.  :)

**Comment by ppwwyyxx** [comment]
Uber has a complicated way to test TF ABI:
https://github.com/uber/horovod/blob/10835d25eccf4b198a23a0795edddf0896f6563d/setup.py#L72-L100

**Comment by ppwwyyxx** [comment]
Fixed by https://github.com/tensorflow/tensorflow/pull/13496
