### ISSUE TITLE
what's the purpose of class StatsPublisherInterface?

### ISSUE THREAD

**Issue by YongCHN** [tensorflow/tensorflow#12068]
### Describe the problem
Tensorflow Open source version contains the class StatsPublisherInterface and a dummy implementation, NoOpStatsPublisher. I was wondering the design purpose of this class. From the class name it seems that there is some other system that can subscribe the statistics of tensorflow step and display the information in realtime.  Can someone help ex

### Source code / logs
https://github.com/tensorflow/tensorflow/blob/0a4f5b6bda405814af59803829216762e030728d/tensorflow/core/common_runtime/stats_publisher_interface.h

**Comment by yaroslavvb** [comment]
it looks like it's part of refactoring of an existing system that lets you display tensorflow timeline, cc @suharshs

**Comment by suharshs** [comment]
Thanks @yaroslavvb . Yes that's correct. Eventually if we can implement a proper StatsPublisherInterface to have stats more/better visualizations.

**Comment by YongCHN** [comment]
thanks.
