### ISSUE TITLE
the efficiency of StagingArea on gpu

### ISSUE THREAD

**Issue by suiyuan2009** [tensorflow/tensorflow#12061]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:ubuntu 16.04
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:v1.2.0-2809-g7add4e6 1.2.1-rc2
- **Python version**: Python 3.5.2
- **Bazel version (if compiling from source)**:0.5.2
- **CUDA/cuDNN version**:8.0/6.0
- **GPU model and memory**:8 1080ti cards, each 11172MB
- **Exact command to reproduce**: see below

### Describe the problem
I test the efficiency of StagingArea(as described in https://www.tensorflow.org/performance/performance_models) on GPU compared to direct feed_dict to session.run input method.
The script shows these two methods have almost same speed, all about 34 seconds. But if I put all inputs to StagingArea first, the script just need 23 seconds to run. StagingArea method can't hide data copy time.

### Source code / logs
https://gist.github.com/suiyuan2009/99fb21567e7ce3716ae25772754c7543

**Comment by ppwwyyxx** [comment]
After a quick glance at your code. One thing is that your code doesn't use latency hiding.
You still use feed_dict in the critical loop with `sess.run([put_op, loss], feed_dict=xxx)`. Even though it is fed into staging area, Python->TF copy will still have to finish before any op really runs.

**Comment by suiyuan2009** [comment]
@ppwwyyxx , I put one item into StagingArea before actual run. I used profiler to check it's non-blocking.

**Comment by suiyuan2009** [comment]
so there is no hack method if we insist on using `feed_dict`.

**Comment by ppwwyyxx** [comment]
Feed latency should be hidden if you use `feed_dict` in a different thread.

**Comment by suiyuan2009** [comment]
I'll try thread method again. I use a thread to enqueue inputs in my first version code, but it didn't help. I'll use a fixed size queue on cpu and a staging area on gpu to see if I can beat GIL.

**Comment by suiyuan2009** [comment]
excited! direct feed_dict method 30 seconds vs no fixed size queue before staging area method 23 seconds vs fixed size queue before staging area method 22.5 seconds.

**Comment by ppwwyyxx** [comment]
@suiyuan2009 have you compared with using queues only (no stagingarea)? Recently I seem to observe that StagingArea doesn't help much on top of queues.
