### ISSUE TITLE
[XLA] Should we disable `REGISTER_XLA_BACKEND(GPU)` if there is no GPU installed on the machine? 

### ISSUE THREAD

**Issue by ScorpioCPH** [tensorflow/tensorflow#12070]
I install TensorFlow from source with `XLA` and `TF_CPP_MIN_VLOG_LEVEL` enabled (without `GPU`), after trying `XLA` example, I got these logs:

```shell
...
XLA op registration: device: XLA_CPU_JIT op: AssignAddVariableOp
XLA op registration: device: XLA_GPU_JIT op: AssignAddVariableOp
XLA op registration: device: XLA_CPU_JIT op: _UnsafeReadVariable
XLA op registration: device: XLA_GPU_JIT op: _UnsafeReadVariable
XLA op registration: device: XLA_CPU_JIT op: Unpack
XLA op registration: device: XLA_GPU_JIT op: Unpack
...
```

But there is no `GPU` installed on my machine, so I don't enable `CUDA` option, but it still do

```cpp
REGISTER_XLA_BACKEND(DEVICE_GPU_XLA_JIT, kGpuAllTypes, GpuOpFilter);
```

Should we disable `REGISTER_XLA_BACKEND(GPU)` if there is no `GPU` installed on the machine?

@tatatodd @hawkinsp WDYT?

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
  No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
  Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
  Source
- **TensorFlow version (use command below)**:
  v1.2.1
- **Python version**: 
  2.7
- **Bazel version (if compiling from source)**:
  0.4.5
- **CUDA/cuDNN version**:
  N/A
- **GPU model and memory**:
  N/A
- **Exact command to reproduce**:

**Comment by ScorpioCPH** [comment]
ping @tatatodd @hawkinsp

**Comment by hawkinsp** [comment]
Thanks for the bug report!

These messages are benign — I would just ignore them. They won't hurt anything and they only show up if you turn on verbose logging; at worst they could slow down startup a very tiny amount.

We could maybe try to avoid creating op registrations if not building with CUDA, but if it isn't causing a problem I don't think it's a high priority.

However if you want to send a PR to fix it I wouldn't object :-)

**Comment by ScorpioCPH** [comment]
@hawkinsp Thanks for your reply!

I will send a PR to fix it later :)
