### ISSUE TITLE
tf.contrib.data.Iterator.make_initializer operation lacks name

### ISSUE THREAD

**Issue by jrbtaylor** [tensorflow/tensorflow#12083]
I'm using tf.contrib.data for my input pipeline. Since it feeds the model without placeholders, I need to be able to reload both the model and input pipeline in order to resume training later. However, the make_initializer method of tf.contrib.data.Iterator does not have a name argument like most (all?) other Tensorflow operations, making it impossible (or at best, error-prone) to find these ops in the reloaded graph. Unless I'm mistaken, this seems like a standard use-case and the missing name argument is inconsistent with the rest of Tensorflow.

**Comment by Mazecreator** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mazecreator@gmail.com
    Domain mazecreator.com has exceeded the max emails per hour (27/25 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:21528)
	by server2.lowesthostingrates.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-e6d9-mazecreator=mazecreator.com@sgmail.github.com>)
	id 1dem6p-00010w-TV
	for mazecreator@mazecreator.com; Mon, 07 Aug 2017 12:47:01 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=vIpSQZRSGLJvoZmWvy+whtLSUTc=; b=i+ggCBd9VC6vFnfc
	qldH1BzUgaRq4OkldPzk3EOwj/R/SpUVnoIKeqoSVqAiiqDTym0k6D8NRqQls7hd
	nr4DpbkGDj8zxvANEruFDyCfX2cLpUUO4f2mqxF6r+23W/lhAa/AC7BRu9qVekOj
	MILauzAc3ZzgjH6A1g/Niv7Io54=
Received: by filter0932p1mdw1.sendgrid.net with SMTP id filter0932p1mdw1-25425-5988AA04-31
        2017-08-07 17:57:24.726128496 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0040p1mdw1.sendgrid.net (SG) with ESMTP id E9ME3ay9QwyT__Q6MmKBNw
	for <mazecreator@mazecreator.com>; Mon, 07 Aug 2017 17:57:24.677 +0000 (UTC)
Date: Mon, 07 Aug 2017 17:57:24 +0000 (UTC)

**Comment by jrbtaylor** [comment]
A general solution would be something similar to tf.identity(..., name) but for operations.

**Comment by yaroslavvb** [comment]
Could this be added along the lines of https://github.com/tensorflow/tensorflow/pull/11510 ?

**Comment by yongtang** [comment]
Added PR #12122.

**Comment by yaroslavvb** [comment]
lol, that was fast
