### ISSUE TITLE
Compiling from source

### ISSUE THREAD

**Issue by Ntweat** [tensorflow/tensorflow#12091]
I am trying to compile tensorflow from source as the pip version is compiled on older version of cuDNN 

### System information
- **OS Platform and Distribution ** : Linux Ubuntu 16.04
- **TensorFlow installed from** source:
- **TensorFlow version (use command below)**: 
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:  Build label: 0.5.3
- **CUDA/cuDNN version**: CUDA 8, cuDNN 7.0.1
- **GPU model and memory**: GTX 1080 Ti and VRAM 11GB, RAM 32 GB
- **Exact command to reproduce**:
Trying to compile with   :  https://www.tensorflow.org/install/install_sources

### Describe the problem
Unable to compile from source. I tried the binary but it uses an old version of cuDNN I am using 7.0.1

### Source code / logs
ERROR: /home/ntweat/tensorflow/tensorflow/stream_executor/BUILD:39:1: C++ compilation of rule '//tensorflow/stream_executor:cuda_platform' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-8.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python2.7 \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=6.1 \
    TF_CUDA_VERSION=8.0 \
    TF_CUDNN_VERSION=7.0.1 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL=0 \

**Comment by tatatodd** [comment]
@Ntweat Please include the full error log

**Comment by Ntweat** [comment]
Hi
It was issue with cuDNN, I think Tensorflow does not work with cuDNN 7. 
I downgraded cuDNN to v6 and it compiled without any issues.

**Comment by tatatodd** [comment]
Ah yes, please see #12052 for the cuDNN 7 status

**Comment by Ntweat** [comment]
Thank you 👍  I will look out for updates on cuDNN 7
