### ISSUE TITLE
tf.string_split didn't behave the same as that split in python

### ISSUE THREAD

**Issue by jiqiujia** [tensorflow/tensorflow#12108]
In python, if we split the following string `'a#'.split('#')`, we will get a list of two elements: `['a', '']`.
While in tensorflow, if we use `tf.string_split`, we will get an sparsetensor with only one elements. 
For reproduction, you can run the following piece of code
```
a = tf.constant("#2")
b = tf.string_split([a], "#")
with tf.Session() as ss:
    ss.run(tf.local_variables_initializer())
    print(ss.run(b))
```
As a result, when we use `tf.string_split`, we don't know whether the `2` is before or after the `#`. I think such behavior is undesirable since we usually have missing values when decoding csv files.

**Comment by yongtang** [comment]
In current implementation, by default empty results are skipped:
https://github.com/tensorflow/tensorflow/blob/7280dafca161eb3413ea120d3dd07c63e5254e72/tensorflow/core/kernels/string_split_op.cc#L33

I think it probably makes sense to add an additional argument in `tf.string_split` with `skip_empty`:
```
def string_split(source, delimiter=" ", skip_empty=True):
...
```

I can submit a PR if tensorflow team is OK with that.

**Comment by rohan100jain** [comment]
It seems reasonable to add a skip_empty additional argument to string_split to enable this behavior. Thanks @yongtang for volunteering to create a PR with this.

**Comment by yongtang** [comment]
Added a PR #12125 for this issue.

**Comment by jiqiujia** [comment]
@yongtang Thanks. So must I wait for the next release to use this feature after it's merged?
