### ISSUE TITLE
Please add predict_proba to estimators class not in TF1.3 DNN

### ISSUE THREAD

**Issue by dartdog** [tensorflow/tensorflow#12119]
### Describe the problem

Feature Request:
The TF.learn library in TF1.2 has perdict_proba for getting probability estimates for predictions it is particularly helpful for setting probability levels up or down or just measuring them.. it is a super helpful function for analysis as well as correlations can be drawn to input variables...

There are many use cases where you may want to accept a prediction with less than a 50/50 (think unbalanced classs)
and there are other cases where you want greater certainty,  for some medical decisions or credit scoring..

The DNN class in TF 1.3 with the estimator does not seem to have this function. (while tf.learn dnn in TF1.2 does...)

Estimators seem to be the way of the future, but at least IMHO we need this to make that move..

**Comment by terrytangyuan** [comment]
You can use tf.estimator now with e.g. predict(..., predict_keys="probabilities")

**Comment by dartdog** [comment]
ahh!!!
