### ISSUE TITLE
Where is device_attributes.pb.h 

### ISSUE THREAD

**Issue by Zealoe** [tensorflow/tensorflow#12128]
I have to use the  device_attributes.pb.h  and I don't know where it is.

Thank you !

**Comment by FiveTechSoft** [comment]
Create it as an empty dummy file

**Comment by asimshankar** [comment]
Closing this as a duplicate of #11899 - like for the file mentioned there, `device_attributes.pb.h` is generated during the build and is placed in `bazel-genfiles`
