### ISSUE TITLE
Where is NumTraits.h ?

### ISSUE THREAD

**Issue by FiveTechSoft** [tensorflow/tensorflow#12126]
https://stackoverflow.com/questions/45579072/compiling-tensorflow-api-c-cc-using-mingw-gcc

**Comment by rohan100jain** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
