### ISSUE TITLE
[Feature] [Java]: Inspect tensors in a Graph

### ISSUE THREAD

**Issue by borissmidt** [tensorflow/tensorflow#12133]
Dear Tensorflow maintainers,

First of all i really like it that tensorflow allows easy interop from keras to tensorflow and then allows for interference to Java.

I have noticed that when you load an invalid graph, for example an empty byte array, then it will just accept it without giving an error. An exception will be thrown when we try to run the graph.

Thus i would propose two improvements for the tensorflow java API,
* throw an exception when loading an invalide graph.
* add api functionality to inspect the tensors contained in the graph

I also noticed in the example for java that you wrapped the graph builder in a convenience java class and it seems that this could be implemented in a really clean way in scala, I would gladly offer you my assistance to implement a scala wrapper. 

Kind regards, Boris

**Comment by tatatodd** [comment]
@asimshankar Can you comment on the suggestions from @borissmidt ?  Thanks!

**Comment by asimshankar** [comment]
@borissmidt : Thanks for the notes. Some thoughts:

- In general, `importGraphDef` will raise an exception when provided an invalid serialized `GraphDef` protocol message. It's just that the empty byte array is a valid serialization of an empty graph :). So I think it's working correctly for an empty graph. Are there invalid graphs for which you do not see an exception raised?

- For the other two, yeah, that seems fine to add. Though, what kinds of inspection were you interested in? You can get tensors by name using something like [`Graph.operation(String name)`](https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/Graph.html#operation(java.lang.String)). If you'd want some form of graph traversal, that will require some implementation work, but the underlying C API does have the functions you need to build on (e.g., [`TF_OperationOutputConsumers`](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/c/c_api.h#L601))

We (TensorFlow maintainters) will probably not get to it in the near future, but if anyone would like to contribute a PR, we'd be more than happy to take a look. Just please do outline the proposed additions to the Java API first :)

Thanks!

**Comment by borissmidt** [comment]
@asimshankar 
Thanks for noting me that there is a function named `Graph.operation(String name)`, it is really useful and it could be further improved with a function like `Graph.getOperations()` which returns a list of operations in the graph. This would allow us the inspect the graph directly and see if the correct one is loaded. 

I'm thinking about the empty graph behavior, since it seems like an odd thing to load an empty graph on purpose?

I know this happened because of a simple bug in my code but it was just a bit hard to track with the current api. I loaded an empty graph :(.

**Comment by quaeler** [comment]
@borissmidt So it sounds like you're asking for `List<Operation> getOperations ();` to be added to `org.tensorflow.Graph`

Which would entail, @asimshankar, (((i think, having looked at the code for the first time this morning))) additionally adding
`private static native long[] allOperations(long handle);`
to `Graph.java`

`JNIEXPORT jlongArray JNICALL Java_org_tensorflow_Graph_allOperations(JNIEnv *, jclass, jlong);`
to `graph_ini.h`

In the implementation of that in `graph_ini.cc`, we'd call a new function to be implemented in `c_api`, stubbed in the `.h` as
`TF_CAPI_EXPORT extern void TF_GraphAllOperations(TF_Graph* graph, TF_Operation** operations);`
and implemented in the `.cc` aggregating out of `graph->name_map`

Sound about right?

**Comment by borissmidt** [comment]
Yes this would make it easier to analyze the graph that is loaded :)

**Comment by quaeler** [comment]
@borissmidt An iterator which provides this functionality has been merged into master. Please let me know if that suffices to close this issue!

**Comment by borissmidt** [comment]
@quaeler Thank you very much, it works as expected and it is really useful to inspect if you are using the right input/outputs for interference or if you have loaded the correct model.

So thanks again for making the java api more flexible and easier to debug, i couldn't have done it myself.
