### ISSUE TITLE
[XLA] Assert when running XLA unit test

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#12140]
If I run the test //tensorflow/compiler/xla/tests:tuple_test_cpu with a VLOG level of >=2 , then I receive the following assert:

```
Check failed: current_id >= 0 (-1 vs. 0)-1: 0x7ff6b960bd60: instruction may not have parent computation
```

I don't think that this is due to any changes that I have in my own repo.

**Comment by meheffernan** [comment]
An internal change went in a couple days ago which fixes this issue. To verify I repro'd the problem with the change rolledback. And I see it landed in the repo with f431494. Let me know if you still run into the problem. Closing speculatively.
