### ISSUE TITLE
Link to Linux and Mac OS broken in TF for Java README

### ISSUE THREAD

**Issue by deepali-c** [tensorflow/tensorflow#12141]
The link to `Linux `and `Mac OS` under section [Building from Source](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/README.md#building-from-source) is broken.

**Comment by yongtang** [comment]
The Linux should point to:
https://www.tensorflow.org/install/install_sources#PrepareLinux

Added a PR #12145 for the fix.
