### ISSUE TITLE
Tiny error about set CLASSPATH  in Deploy Doc

### ISSUE THREAD

**Issue by weberxie** [tensorflow/tensorflow#12165]
In https://www.tensorflow.org/deploy/hadoop this page,
When introduce to set CLASSPATH,
`shell CLASSPATH=$($HADOOP_HDFS_HOME}/bin/hadoop classpath --glob)`
There is an extra parenthesis after **$HADOOP_HDFS_HOME**

**Comment by yongtang** [comment]
See #10293. I think the issue has been fixed in the master branch.

**Comment by tatatodd** [comment]
Thanks for filing the issue @weberxie , and thanks for pointing out the PR @yongtang !

Closing this out.
