### ISSUE TITLE
TFRecord usage

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#12167]
### Describe the problem
Can I get meta data of record in TFRecord file using tf queue pipeline, which type is an int or np.ndarry without a Tensor?

So I can use this meta data to tf.shuffle_batch example, and I do not want use a another Sesson to fecth from Tensors.

May this can be a Feature for tf.

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
