### ISSUE TITLE
Cannot include '*.pb.h' files in tf_tutorials.cmake

### ISSUE THREAD

**Issue by martinrosevear** [tensorflow/tensorflow#12164]
**System information**

Windows10
VisualStudio 2015
TensorFlow 1.3.0
Python 3.5.3
CMake 3.9.0

I am generating C++ tensorflow 'GPU' version of _tf_tutorials_example_trainer_ example as defined in (https://github.com/tensorflow/tensorflow/tree/r0.12/tensorflow/contrib/cmake) using Cmake and MSbuild. 

**Describe the problem**

Build failing due to missing header files ../contrib/boosted_trees/proto/*.ph.h. 

The *.proto files are present, and I can use protoc.exe to manually generate the *.ph.h files.  This removes the 'cannot include' errors.  BUT now there are linker errors when building the tf_tutorials_example_trainer.exe as it can't find the routines/structures defined in the  *.pb.h files.

NOTE: *.proto files in other directories are also not expanded to *.pb.h equivalents.

**Source code / logs**

"c:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\cmake\build\tf_tutorials_example_trainer.vcxproj" (default target) (1) ->
"C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj" (default target) (104) ->
(ClCompile target) -> 
  C:\Users\Martin Rosevear\tensorflow\tensorflow/contrib/boosted_trees/lib/trees/decision_tree.h(19): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/tree_config.pb.h': No such file or directory (compiling source file C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\boosted_trees\lib\learner\common\partitioners\example_partitioner.cc) [C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  C:\Users\Martin Rosevear\tensorflow\tensorflow/contrib/boosted_trees/lib/learner/stochastic/stats/node-stats.h(21): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/learner.pb.h': No such file or directory (compiling source file C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\boosted_trees\lib\learner\stochastic\handlers\categorical-feature-column-handler.cc) [C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  C:\Users\Martin Rosevear\tensorflow\tensorflow/contrib/boosted_trees/lib/learner/stochastic/stats/node-stats.h(21): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/learner.pb.h': No such file or directory (compiling source file C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\boosted_trees\lib\learner\stochastic\handlers\bias-feature-column-handler.cc) [C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  C:\Users\Martin Rosevear\tensorflow\tensorflow/contrib/boosted_trees/lib/learner/stochastic/stats/node-stats.h(21): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/learner.pb.h': No such file or directory (compiling source file C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\boosted_trees\lib\learner\stochastic\handlers\dense-quantized-feature-column-handler.cc) [C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  C:\Users\Martin Rosevear\tensorflow\tensorflow/contrib/boosted_trees/lib/utils/dropout_utils.h(21): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/learner.pb.h': No such file or directory (compiling source file C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\boosted_trees\lib\utils\dropout_utils.cc) [C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  C:\Users\Martin Rosevear\tensorflow\tensorflow/contrib/boosted_trees/lib/learner/stochastic/stats/node-stats.h(21): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/learner.pb.h': No such file or directory (compiling source file C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\boosted_trees\lib\learner\stochastic\handlers\sparse-quantized-feature-column-handler.cc) [C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  C:\Users\Martin Rosevear\tensorflow\tensorflow/contrib/boosted_trees/lib/trees/decision_tree.h(19): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/tree_config.pb.h': No such file or directory (compiling source file C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\boosted_trees\lib\trees\decision_tree.cc) [C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  C:\Users\Martin Rosevear\tensorflow\tensorflow/contrib/boosted_trees/lib/models/multiple_additive_trees.h(21): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/tree_config.pb.h': No such file or directory (compiling source file C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\boosted_trees\lib\models\multiple_additive_trees.cc) [C:\Users\Martin Rosevear\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]

**Comment by reedwm** [comment]
@mrry can you take a look?
