### ISSUE TITLE
build_all_xxx.sh support for Tizen target

### ISSUE THREAD

**Issue by leemgs** [tensorflow/tensorflow#12162]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 LTS 64bit
- **TensorFlow installed from (source or binary)**: Yes
- **TensorFlow version (use command below)**: 1.2.1
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.1.3
- **CUDA/cuDNN version**: 8.0/6.0
- **GPU model and memory**: GTX Titan XP
- **Exact command to reproduce**:

### Describe the problem
I can find appropriate build scripts for iOS, Android, and Linux at the below webpage.
- https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile/

Where can I also find a build script in case that I want to build Tensorflow on the Tizen  target device ?

- Tizen (for platform developers): https://source.tizen.org/
- Tizen (for application developers): https://developer.tizen.org/

### Source code / logs
Nothing

**Comment by yaroslavvb** [comment]
This sounds like a good issue for community to support. Maybe Samsung wants to help integration? cc @yunjey in case they know people in Samsung to take it on

**Comment by leemgs** [comment]
In case of Caffe2, I have merged(https://github.com/caffe2/caffe2/pull/877) a build script to run Caffe2 library on the Tizen software platform previously. 

Anyone who tried to do related works to support the Tizen platform in case of Tensorflow? Any comments and experiences will be helpful to us.

**Comment by leemgs** [comment]
Yesterday, Google officially announced how to use Neural Network API on Android 8.1. @yaroslavvb Do they are planning to open Tensorflow-Lite (for mobile) as well as Tensorflow?

@yunjey Can I give you some questions to try to enable Tensorflow (or Tensorflow Lite) on Tizen platform? As a first question, Can we use Cmake instead of Bazel  to build Tensorflow on real arm device (or on QEMU-ARM emulator)

**Comment by krantideep95** [comment]
Some work is being done here : <https://review.tizen.org/gerrit/#/admin/projects/platform/upstream/tensorflow>
Currently, Tensorflow Lite from r1.7 is built for tizen platform.

**Comment by leemgs** [comment]
We have worked to build Tensorflow-lite only. We have to also enable how to build Tensorflow as well as Tensorflow-lite

**Comment by mohantym** [comment]
Hi @leemgs! 
We are checking to see whether you still need help with this issue . Have you checked this [document](https://docs.tizen.org/application/native/guides/machine-learning/machine-learning-inference/) for deploying Tensorflow in Tizen OS yet?
