### ISSUE TITLE
No builds for Linux Py3.6-gpu TF1.3 RC2?

### ISSUE THREAD

**Issue by dartdog** [tensorflow/tensorflow#12187]
Using Python 3.6 in Anaconda on Ubuntu 16.04

```
source activate py36env 
pip install --upgrade \
> https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.3.0rc2-cp35-cp35m-manylinux1_x86_64.whl
tensorflow_gpu-1.3.0rc2-cp35-cp35m-manylinux1_x86_64.whl is not a supported wheel on this platform. 
```
I checked the build stream and don't see a Linux PY3.6 GPU being built?

Seems to me that since I have TF 1.2 installed (it had the PY3.6GPU support that new RC's should also include builds for Py3.6/GPU or a lot of people just won't build a separt downgraded test environment for the RC?

Or is the intention to drop support?? (I hope not!)

**Comment by ppwwyyxx** [comment]
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.3.0rc2-cp36-cp36m-linux_x86_64.whl

**Comment by dartdog** [comment]
Awesome Thanks for the quick response!

**Comment by dartdog** [comment]
grr now I just have to upgrade my cdnn, for libcudnn.so.6 which will probably break the older TF env but I think that is fixable with a symlink..

**Comment by skye** [comment]
Hi @dartdog, has your issue been resolved?
