### ISSUE TITLE
Windows Installation?

### ISSUE THREAD

**Issue by hugman** [tensorflow/tensorflow#122]
Is it possible to install TF in windows environment?
I checked "pip install" is not supported in windows. 

Any plan for it?

**Comment by nowrock** [comment]
I have the same question.

**Comment by icoxfog417** [comment]
Please refer #17.

**Comment by mrry** [comment]
Closing this as a duplicate of #17 - please feel free to continue the discussion there.

**Comment by zkl99999** [comment]
C:\Users\\Desktop>docker run -it b.gcr.io/tensorflow/tensorflow

Unable to find image 'b.gcr.io/tensorflow/tensorflow:latest' locally

docker: Error response from daemon: unable to ping registry endpoint https://b.g
cr.io/v0/
v2 ping attempt failed with error: Get https://b.gcr.io/v2/: dial tcp 64.233.188
.82:443: i/o timeout
