### ISSUE TITLE
Document changes in notMNIST data sets

### ISSUE THREAD

**Issue by jowagner** [tensorflow/tensorflow#12208]
### Describe the problem
The notMNIST data set used in Assignment 1 and maybe elsewhere in this repo repeatedly changed size over the last 12 months. Last year, in issue #4693, a size of about 50 MB is reported for notMNIST_large.tar.gz. Now this file is 236 MB. People doing the assignment are comparing their classifier accuracy to results published by previous assignment takers and some are talking about publishing research using this data set. If the data set is modified unknowingly to the users, observed accuracy figures are not comparable and can mislead people to wrong conclusions.

@yaroslavvb The files is also bigger now on your personal website. However, the time stamps of the .atr.gz and all files inside are still from 2011.

### Source code / logs
The changes in size can also be tracked in changes to the calls of maybe_download() in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/1_notmnist.ipynb

### Suggestions

- The .tar.gz files should contain a readme and changelog with version information.
- The filename should include the version number.
- References to the data set in the assignments should be changed from "the notMNIST dataset" to "version 1.23 of the notMNIST dataset".
- Result tables produced by code should quote the version of the data set.

**Comment by vincentvanhoucke** [comment]
As far as I know, there has been no updates to the dataset whatsoever. I would not recommend using this dataset to publish, it adds nothing compared to MNIST.

**Comment by jowagner** [comment]
Thanks. Diving deeper into the git log for `1_notmnist.ipynb` and reading more threads mentioning issues with the size of the data set downloads, it seems indeed more plausible that the files did not change on the server and the deviant sizes were related to unexpected interactions between http server and client with the presence or absence of certain http headers and/or proxy servers.
