### ISSUE TITLE
tensorflow/contrib/session_bundle/example/export_half_plus_two.py fails with ValueError: invalid option

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#12210]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: ('v1.2.1-0-gb4957ff', '1.2.1')
- **Python version**: Python 2.7.9
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: Not used
- **Exact command to reproduce**: python tensorflow/contrib/session_bundle/example/export_half_plus_two.py

### Describe the problem
The given script is used to generate testdata for savedmodel. 
`python tensorflow/contrib/session_bundle/example/export_half_plus_two.py` Fails with below error

```
Traceback (most recent call last):
  File "tensorflow/contrib/session_bundle/example/export_half_plus_two.py", line 159, in <module>
    help="If true, write v2 checkpoint files."
  File "/usr/lib/python2.7/argparse.py", line 1280, in add_argument
    kwargs = self._get_optional_kwargs(*args, **kwargs)
  File "/usr/lib/python2.7/argparse.py", line 1410, in _get_optional_kwargs
    raise ValueError(msg % tup)
ValueError: invalid option string 'bool': must start with a character '-'
```

### Source code / logs
tensorflow/contrib/session_bundle/example/export_half_plus_two.py

**Comment by Nayana-ibm** [comment]
Below code patch resolves this issue:
```
diff --git a/tensorflow/contrib/session_bundle/example/export_half_plus_two.py b/tensorflow/contrib/session_bundle/example/export_half_plus_two.py
index 4a56509..a822e9f 100644
--- a/tensorflow/contrib/session_bundle/example/export_half_plus_two.py
+++ b/tensorflow/contrib/session_bundle/example/export_half_plus_two.py
@@ -152,7 +152,7 @@ if __name__ == "__main__":
   )
   parser.add_argument(
       "--use_checkpoint_v2",
-      "bool",
+      "--bool",
       nargs="?",
       const=True,
       default=False,
```

Should I submit a PR for this change?

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/17bc79f4eb0608f5fd82fe08bb50688773a41bc7/tensorflow/python/tools/optimize_for_inference.py#L126

is probably a better form of using 'booleans', along with

https://github.com/tensorflow/tensorflow/blob/17bc79f4eb0608f5fd82fe08bb50688773a41bc7/tensorflow/python/tools/optimize_for_inference.py#L105

Would you like to send a PR?

**Comment by vrv** [comment]
Oh it does look the same pattern is being employed.  Let me try to reproduce first.

**Comment by vrv** [comment]
It's just missing a named argument, I can send a PR.

**Comment by thoangnguyen1308** [comment]
usage: extract_embeddings.py [-h] -i DATASET/XUAN/ -e OUTPUT/EMBEDDINGS.PICKLE
                             -d FACE_DETECTION_MODEL -m
                             OPENFACE_NN4.SMALL2.V1.T7 [-c CONFIDENCE]
extract_embeddings.py: error: the following arguments are required: -i/--dataset/Xuan/, -e/--output/embeddings.pickle, -d/--face_detection_model, -m/--openface_nn4.small2.v1.t7
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
