### ISSUE TITLE
MonitoredSession has no `close`

### ISSUE THREAD

**Issue by kinsumliu** [tensorflow/tensorflow#12224]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Minimum custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: mac os 10.12.6
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2.1
- **Python version**: 2.7.13
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**:

### Describe the problem
Bug: MonitoredSession has no `close` but it should have according to https://www.tensorflow.org/api_docs/python/tf/train/MonitoredSession#close

I think in some cases, self._sess is not initialized.

### Source code / logs
minimum code to reproduce:
with tf.train.MonitoredTrainingSession() as sess:
  sess.close()

compared to working code using simple session:
with tf.Session() as sess:
  sess.close()

**Comment by quaeler** [comment]
I see it in the current master - private class _MonitoredSession implements it here https://github.com/tensorflow/tensorflow/blob/863d7e7f0202cf5b513f2e3e691e7686562c8d74/tensorflow/python/training/monitored_session.py#L525
and MonitoredSession subclasses that class here https://github.com/tensorflow/tensorflow/blob/863d7e7f0202cf5b513f2e3e691e7686562c8d74/tensorflow/python/training/monitored_session.py#L589

**Comment by yongtang** [comment]
The issue is not about the existence of `close()` as `close()` has already been defined. The issue is that:
```
with tf.train.MonitoredTrainingSession() as sess:
    sess.close()
```
actually invokes `_close_internal()` twice. One in the `sess.close()` call and another in the `__exit__()` call at the end of the with statement. The second call triggered a None:
```
>>> import tensorflow as tf
>>> with tf.train.MonitoredTrainingSession() as sess:
...   sess.close()
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 534, in __exit__
    self._close_internal(exception_type)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 569, in _close_internal
    self._sess.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

Created a PR #12229 to fix the exception issue.

**Comment by kinsumliu** [comment]
@yongtang Thanks. Your explanation makes sense to me.
