### ISSUE TITLE
Check failed: params_->device->RequiresRecordingAccessedTensors() == record_tensor_accesses_ 

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#1222]
The code used to run ok on both CPU or  GPU mode, but I don't know what happend , now it will fail whether cpu or gpu version
python -c "import tensorflow; print(tensorflow.__version__)"

F /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/op_kernel.h:1087] Check failed: params_->device->RequiresRecordingAccessedTensors() == record_tensor_accesses_

**Comment by petewarden** [comment]
Jeff, it looks like this check was recently added. Can you add some background on why it might be triggered? Thanks!

**Comment by chenghuige** [comment]
I find the problem is associate with the user defined op(I write one auc.cc -> auc.so), which used to work.
If remove running auc op, then the script can run.

**Comment by chenghuige** [comment]
Hi, now after rebuilding auc.so on centos platform, now everything is fine, might due to mismatch of platform(auc.so was generated on another ubuntu platform before).
@jeffreyadean Close this if not an issue.

**Comment by petewarden** [comment]
Thanks for the update! I'll close this.
