### ISSUE TITLE
request: Make tensorflow checkpoints portable

### ISSUE THREAD

**Issue by ALLYOURSR** [tensorflow/tensorflow#12225]
### System information
Not applicable, this is a general feature request.

### Describe the problem
Feature request: make checkpoint files portable.
Checkpoint files are not portable, because they use absolute paths. If I move the directory containing a trained graph, and then try to restore from a checkpoint, I get "unable to match files" errors because tensorflow does not know to look in the checkpoint directory for checkpoint files.

**Comment by ppwwyyxx** [comment]
`tf.train.Saver(save_relative_paths=True)`
