### ISSUE TITLE
Invalid argument: NodeDef mentions attr 'Tshape' not in Op<name=Reshape; signature=tensor:T, shape:int32 -> output:T; attr=T:type>;

### ISSUE THREAD

**Issue by datomnurdin** [tensorflow/tensorflow#12227]
I got this kind of error message once my Android app launced.

Error message

    08-12 10:28:32.307 25515-25533/? E/native: executor.cc:334 Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'Tshape' not in Op<name=Reshape; signature=tensor:T, shape:int32 -> output:T; attr=T:type>; NodeDef: pool_3/_reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](pool_3, pool_3/_reshape/shape)
                                               	 [[Node: pool_3/_reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](pool_3, pool_3/_reshape/shape)]]
    08-12 10:28:32.352 25515-25533/? I/native: tensorflow_jni.cc:299 End computing. Ran in 786ms (786ms avg over 1 runs)
    08-12 10:28:32.357 25515-25533/? A/native: tensorflow_jni.cc:304 Error during inference: Invalid argument: NodeDef mentions attr 'Tshape' not in Op<name=Reshape; signature=tensor:T, shape:int32 -> output:T; attr=T:type>; NodeDef: pool_3/_reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](pool_3, pool_3/_reshape/shape)
                                               	 [[Node: pool_3/_reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](pool_3, pool_3/_reshape/shape)]]
    08-12 10:28:32.357 25515-25533/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 25533 (InferenceThread)

These two line of codes that possibility produced the error message

1. https://github.com/datomnurdin/AndroidTensorFlowBirdExample/blob/master/app/src/main/jni/include/tensorflow/core/common_runtime/executor.cc

2. https://github.com/datomnurdin/AndroidTensorFlowBirdExample/blob/master/app/src/main/jni/tensorflow_jni.cc

Please advice. Thank you.

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by fastlater** [comment]
@datomnurdin any update about this issue? I am having the same error
