### ISSUE TITLE
Default Python lib paths are not matched with the Python exe user inputted when 'configure'

### ISSUE THREAD

**Issue by LiyuCode** [tensorflow/tensorflow#12232]
Here is the output of 'configure':
```
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3
Found possible Python library paths:
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is /usr/local/lib/python2.7/dist-packages
...
```
In above,  user typed `Python3` for the location but the library paths found are with `Python2`. 

### 1. Env
  1.1 OS: Ubuntu 16.04 LTS (64 bit) with CUDA 8
  1.2 Bazel Build label: 0.5.3
  1.3 Python:
        - Python 2.7 and Python 3.5 are installed
        - Default `python` cmd in this OS is `python2.7`
  1.4 Tensorflow `git rev-parse HEAD`:  863d7e7f0202cf5b513f2e3e691e7686562c8d74
### 2. Desc
  Using `python3 configure.py` to start configuration instead of `./configure` would save the trouble directly, but may not preferable to others.

**Comment by yongtang** [comment]
Added a PR #12238 to address the issue.
