### ISSUE TITLE
Tensorflow inception speed issue

### ISSUE THREAD

**Issue by rox321** [tensorflow/tensorflow#12231]
hello this is Rohan Naik,
i developed an app which interact with tensorflow running on server and shows parking spaces available for your car.
i am using inception model which was retrained and modified to process live video and tell the users where parking slots are available.
The issue is it takes a 10 seconds to process 8 thread which run the image recognition function. Is there any way i can make it run faster.
Is "tensorflow slim" model can process the images faster?
[code.txt](https://github.com/tensorflow/tensorflow/files/1219473/code.txt)

**Comment by ALLYOURSR** [comment]
If your concern is speed, I saw a ~25% improvement when I switched to c++ over python for image classification (not training). I know in theory the heavy lifting in python is handled by compiled c/c++ binaries, but in practice it looks like there is still some slowdown.

Also, you may see substantial speedup if you use a GPU, assuming you are running many images through the classifier.

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
