### ISSUE TITLE
add new op for tensorflow in windows os

### ISSUE THREAD

**Issue by jeansely** [tensorflow/tensorflow#12233]
Hello,
how can create new op in window os (a example or manual).

the same link in  linux ( https://www.tensorflow.org/extend/adding_an_op#build_the_op_library)

Thanks.

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
