### ISSUE TITLE
Broken download links of the Windows GPU

### ISSUE THREAD

**Issue by VanitarNordic** [tensorflow/tensorflow#12242]
Hi,

`Windows GPU` download link are broken.

**Comment by reedwm** [comment]
@av8ramit, can you check why the Windows GPU links are broken in [README.md](https://github.com/tensorflow/tensorflow/blob/master/README.md)?

**Comment by av8ramit** [comment]
Trying again after merging a fix for hash mismatch error in cmake: https://github.com/tensorflow/tensorflow/pull/12271

**Comment by gunan** [comment]
I think the nightly GPU build is still broken.
We will keep looking into a fix.

**Comment by av8ramit** [comment]
Fixed!
