### ISSUE TITLE
Error importing tensorflow-gpu

### ISSUE THREAD

**Issue by shauryaksingh** [tensorflow/tensorflow#12245]
![capture](https://user-images.githubusercontent.com/20387587/29246512-8065cd0a-801a-11e7-8916-0e10817a1dce.PNG)

I installed Cuda Toolkit, cuDNN 5.1 on windows 8.1
I also installed tensorflow-gpu using pip3
When I tried importing tensorflow in python, I got the above error
Can you please help me out?

**Comment by harwee** [comment]
Install cudNN and if you have already installed and this error occurs, you can use this code to check if cudNN is properly installed. Generally it should work by renaming cudnn64_7.dll to cudnn64_5.dll if you downloaded the latest cudNN
