### ISSUE TITLE
Fail to tune the number of CPU for training

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#12255]
### System information

== uname -a =====================================================
Linux aws-prophet-tf01 4.4.53-1.el7.centos.x86_64 #1 SMP Sun Mar 12 12:38:41 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.13.1)
protobuf (3.3.0)
tensorflow (1.2.1)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.2.1
tf.GIT_VERSION = v1.2.0-5-g435cdfc
tf.COMPILER_VERSION = v1.2.0-5-g435cdfc
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

### Describe the problem

We are using TensorFlow to benchmark and train an simple neural network model. We found that the usage of CPU was around 200% while we have more idle CPUs. And we have manually set the configuration of session like this which will not work.

```
config = tf.ConfigProto(device_count={"CPU": 4}, # limit to num_cpu_core CPU usage  
                inter_op_parallelism_threads = 1,   
                intra_op_parallelism_threads = 4,  
                log_device_placement=True)  
with tf.Session(config = config) as sess:  
```

Here is my script to benchmark and using `tf.embedding_lookup_sparse` for the space dataset in https://github.com/tobegit3hub/tensorflow_template_application/blob/master/sparse_classifier.py .

### Source code / logs

The usage of CPU looked like this.

<img width="762" alt="screen shot 2017-08-11 at 5 15 29 pm" src="https://user-images.githubusercontent.com/2715000/29255695-4dd7deb6-80d6-11e7-8d7b-2c9f7ef3d687.png">

Although we had set the configuration of session. It seemed that all op are placed in `cpu:0`. The log looks like this.

```
2017-08-14 01:44:00.058798: I tensorflow/core/common_runtime/simple_placer.cc:847] ParseExample/Parse[54/1040]
parse_keys_0: (Const)/job:localhost/replica:0/task:0/cpu:0
ParseExample/ParseExample/names: (Const): /job:localhost/replica:0/task:0/cpu:0
2017-08-14 01:44:00.058818: I tensorflow/core/common_runtime/simple_placer.cc:847] ParseExample/ParseExample/names: (Const)/job:localhost/replica:0/task:0/cpu:0
ParseExample/Const: (Const): /job:localhost/replica:0/task:0/cpu:0                                            2017-08-14 01:44:00.058849: I tensorflow/core/common_runtime/simple_placer.cc:847] ParseExample/Const: (Const)/job:localhost/replica:0/task:0/cpu:0
shuffle_batch/n: (Const): /job:localhost/replica:0/task:0/cpu:0
2017-08-14 01:44:00.058868: I tensorflow/core/common_runtime/simple_placer.cc:847] shuffle_batch/n: (Const)/job:localhost/replica:0/task:0/cpu:0
shuffle_batch/fraction_over_100_of_1024_full/tags: (Const): /job:localhost/replica:0/task:0/cpu:0
2017-08-14 01:44:00.058886: I tensorflow/core/common_runtime/simple_placer.cc:847] shuffle_batch/fraction_over_100_of_1024_full/tags: (Const)/job:localhost/replica:0/task:0/cpu:0
shuffle_batch/mul/y: (Const): /job:localhost/replica:0/task:0/cpu:0
2017-08-14 01:44:00.058901: I tensorflow/core/common_runtime/simple_placer.cc:847] shuffle_batch/mul/y: (Const)/job:localhost/replica:0/task:0/cpu:0
```

**Comment by yaroslavvb** [comment]
By default `cpu:0` refers to all CPU cores on the system. You can create virtual CPU devices like "cpu:1", but there's no physical pinning of cores, so ops pinned to "cpu:1" will run on same cores as ops pinned to "cpu:0". To see what cores are actually being used to run ops you need to use something like `ktrace` utility.

Furthermore, I don't see anything in your script that will place ops onto `cpu:1` virtual device, so that's why you see `cpu:0` messages from placement algorithm

It's common to see less than full utilization because parallelization is hard (ie, some core are idle because they are waiting for input).

**Comment by tobegit3hub** [comment]
Thanks @yaroslavvb . It's reasonable and we have increase the utility of all CPUs by adding the number of thread for reading TFRecords files.

So is it right if we don't need to specify `cpu:1` and we may get the best performance?

**Comment by yaroslavvb** [comment]
Correct. BTW unless you are pretty sure it's a bug, it's better to ask these questions on stackoverflow, you'll get response faster and it'll be easier to find by others

**Comment by tobegit3hub** [comment]
Well, thanks @yaroslavvb very much 😃
