### ISSUE TITLE
Principle of setting 'hash_bucket_size' parameter ?

### ISSUE THREAD

**Issue by gaoisbest** [tensorflow/tensorflow#12254]
Question 1: 
In [`wide_n_deep_tutorial.py`,](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/wide_n_deep_tutorial.py) there is a hyper-parameter named `hash_bucket_size` for both `tf.feature_column.categorical_column_with_hash_bucket` and `tf.feature_column.crossed_column` methods,  and the value is `hash_bucket_size=1000`.

But why `1000`? How to set this parameter ?

Question 2:
The second question about `crossed_columns `, that is,
`crossed_columns = [
    tf.feature_column.crossed_column(
        ["education", "occupation"], hash_bucket_size=1000),
    tf.feature_column.crossed_column(
        [age_buckets, "education", "occupation"], hash_bucket_size=1000),
    tf.feature_column.crossed_column(
        ["native_country", "occupation"], hash_bucket_size=1000)
]
` in [`wide_n_deep_tutorial.py`,](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/wide_n_deep_tutorial.py)

Why choose `["education", "occupation"]`, `[age_buckets, "education", "occupation"]` and `["native_country", "occupation"]` as crossed_columns , are there any rule of thumb ?

**Comment by rohan100jain** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
