### ISSUE TITLE
variable_scope.name is not displayed correctly

### ISSUE THREAD

**Issue by wqkx** [tensorflow/tensorflow#12258]
![snip20170814_1](https://user-images.githubusercontent.com/25893395/29259398-45c4299a-80f5-11e7-854e-6cdcfd76f5d7.png)

As shown, scope2's name should be new_scope_1

**Comment by ppwwyyxx** [comment]
No. `new_scope_1` is the name of the name scope. The name of the variable scope is still `new_scope`.
