### ISSUE TITLE
tensorflow compile error

### ISSUE THREAD

**Issue by wm901115nwpu** [tensorflow/tensorflow#12259]
When I run :bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --config=opt --config=cuda //tensorflow/...
ERROR: /home/wangmeng/tools/tensorflow/tensorflow/compiler/xla/tools/BUILD:109:1: Linking of rule '//tensorflow/compiler/xla/tools:replay_computation_hlo_evaluator' failed (Exit 1)
bazel-out/local_linux-opt/bin/tensorflow/compiler/plugin/executor/libplugin_lib.lo(device.o): In function `tensorflow::{lambda(tensorflow::OpKernelConstruction*)#1}::_FUN(tensorflow::OpKernelConstruction*)':
device.cc:(.text._ZN10tensorflowUlPNS_20OpKernelConstructionEE_4_FUNES1_+0x1e): undefined reference to `tensorflow::XlaDeviceLaunchOp::XlaDeviceLaunchOp(tensorflow::OpKernelConstruction*)'
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 61.551s, Critical Path: 36.75s
FAILED: Build did NOT complete successfully

tensorflow r1.3,bazel 0.5.3

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by smitshilu** [comment]
@wm901115nwpu do you have an answer for this?
