### ISSUE TITLE
No module named 'tensorflow'

### ISSUE THREAD

**Issue by Vapster** [tensorflow/tensorflow#12256]
I downloaded the Anaconda 4.1.1 For Windows with Python 3.5.2 version.

Create a conda environment named tensorflow by invoking the following command:
C:> conda create -n tensorflow

Activate the conda environment by issuing the following command:
C:> activate tensorflow
(tensorflow)C:> 

I install the CPU-only version of TensorFlow

I installed it successfully.
but then....

c>python
python version 3.5.2 .... (anaconda).............

import tensorflow as tf
[it appears this Error : ]
Traceback :
File "", line 1, in 
ModuleNotFoundError: No module named 'tensorflow'

**Comment by changliang-sun** [comment]
Maybe you need to use command "cd ( Tensorflow Interpreter Path )" to try it

**Comment by jubjamie** [comment]
Make sure you are not sitting inside your anaconda directory. cd to somewhere else (like C), **ensure that you activate your environment** then try again. From your issue file it suggests that you weren't inside your tensorflow environment when entering your python console.

**Comment by Vapster** [comment]
in command Prompt after I activate tensorflow it works fine,
but I am using sublime and I am not able to build it

**Comment by shivam9654** [comment]
Activate tensorflow in your command prompt then write your code in sublime and run
(tensorflow)C:> python yourfilename.py

**Comment by Vapster** [comment]
thanks for your support
