### ISSUE TITLE
Android demo - SDD-Mobilenet model download failed

### ISSUE THREAD

**Issue by Pelups** [tensorflow/tensorflow#12265]
**System information**

OS Platform and Distribution:Windows 10
TensorFlow installed from:Source
TensorFlow version:master branch
Python version: 2.7.12
Bazel version:NA
CUDA/cuDNN version:NA
GPU model and memory:NA

**Describe the problem**
Hi,
I'm trying to compile the android demo example project just released the August 11, 2017.
I'm building it with Android Studio and gradlle.
The build fails downloading the SSD-Mobilenet model with this error : 
```
Execution failed for task ':downloadFile'.
> org.apache.http.client.ClientProtocolException: Forbidden
```

I can download the other models, but not this one.
How can I fix it ?
Thanks

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by andrewharp** [comment]
It looks like the model archive is available at 
http://storage.googleapis.com/download.tensorflow.org/models/**object_detection**/ssd_mobilenet_v1_android_export.zip, while the download-models.gradle script expects it at http://storage.googleapis.com/download.tensorflow.org/models/ssd_mobilenet_v1_android_export.zip.

@jch1 @martinwicke All of our other models (include multibox, which is also for object detection) are just under the models/ dir -- is there a strong argument for keeping this one under models/object_detection?

Besides copying the file, the most straightforward fix may be to just add "object_detect/" to the beginning of the entry in [download-models.gradle](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/download-models.gradle#L13).

**Comment by martinwicke** [comment]
I think in general it would be better to place new models in subfolders, in particular if they have several files. We also shouldn't move downloadable assets around. 

I would fix the gradle file, that seems like the simplest solution.

**Comment by petewarden** [comment]
I ran into this just now, and as a temporary fix (since it's blocking anyone from building the Android demos with the top-of-tree code) I've copied the relevant file to the location it's expected. We should also fix the code, but the simplest fix (adding a prefix to the name) failed because it's used as a file name for the destination of the download.

**Comment by andrewharp** [comment]
I've fixed this internally using a split to separate the filename from the url -- should be included in the next push.

**Comment by Pelups** [comment]
Perfect ! 
Thanks.
