### ISSUE TITLE
compile using `bazel test`  failed on mac

### ISSUE THREAD

**Issue by facaiy** [tensorflow/tensorflow#12266]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac 10.11.6 
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: 0.5.3-homebrew
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**:

### Describe the problem

It seems that tensorflow cannot work with clang of Mac.  And even though I install gcc 4.8 with brew, and set `export CC=gcc_4_8_install_dir`,  compile still failed. 

```bash
~ ❯❯❯ clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### Source code / logs

```python
~/W/g/tensorflow ❯❯❯ bazel test -c opt //tensorflow/contrib/learn:estimators_test
WARNING: /Users/facai/Workshop/github/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
WARNING: /Users/facai/Workshop/github/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately.
INFO: Found 1 test target...
ERROR: /private/var/tmp/_bazel_facai/c1230027f58dd63b64621179de2d0b21/external/boringssl/BUILD:116:1: C++ compilation of rule '@boringssl//:crypto' failed (Exit 1).
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wno-free-nonheap-object'; did you mean '-Wno-sequence-point'? [-Werror,-Wunknown-warning-option]
Target //tensorflow/contrib/learn:estimators_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.079s, Critical Path: 0.07s

Executed 0 out of 1 test: 1 fails to build.
```

**Comment by reedwm** [comment]
@gunan do you know what the problem is?

**Comment by gunan** [comment]
```
ERROR: /private/var/tmp/_bazel_facai/c1230027f58dd63b64621179de2d0b21/external/boringssl/BUILD:116:1: C++ compilation of rule '@boringssl//:crypto' failed (Exit 1).
error: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wno-free-nonheap-object'; did you mean '-Wno-sequence-point'? [-Werror,-Wunknown-warning-option]
```

This is the problem. Maybe we setup our  build on MAC to specificly use clang? not sure why these errors are being thrown. Did you try googling these error messages?

**Comment by facaiy** [comment]
Thanks for your quick reply.

GCC is 4.2.1 in Mac, while it works well without any warning on ubuntu (GCC 5.4.0).  Hence I guess that these warnings are related to gcc version. 

It seems that many people try to update gcc, while most get in trouble, see #336, #75, #649.

In all, if tensorflow supports to compile with the default compiler on Mac (or more detailed  Instruction about how to test on Mac for developer), life will be easy.

**Comment by quaeler** [comment]
Just piping up with some anecdotal (and so useless) news, but when i run tests (e.g `bazel test //tensorflow/c:c_api_test`) on my Mac (10.12.6) with current XCode and no attempted gcc updates, it uses clang successfully.
```
autogenic:tensorflow xx$ clang -v
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
autogenic:tensorflow xx$ 
```

The only peeps of complaint regarding flags that i see are
```
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
```

I also just reran the c_api_test including `-c opt` to see if that triggered a similar warning but saw no new problems.

**Comment by gunan** [comment]
As @quaeler stated, we build and test TensorFlow on MacOS using default clang that comes with Xcode. Our build system has some hardcoded compile and link options based on OS, and the MacOS options in the system may not match what GCC on MacOS provides.

@facaiy Would it be possible for you to try using clang (that is distributed with Xcode) on your machine instead of GCC?

**Comment by facaiy** [comment]
Thanks, @gunan and @quaeler .

I indeed use default clang, sorry for misunderstanding. However, my mac is 10.11.6, which is older than @quaeler . Perhaps upgrading system can solve my problem, I'll try to upgrade later.

**Comment by quaeler** [comment]
I tried briefly to find a changelog which might describe what was changed between Apple's clang 800.0.42.1 and 802.0.42 but could not.

I noticed the issue you cited cropped up during the build of BoringSSL, and there is also this open issue https://github.com/tensorflow/tensorflow/issues/12123 so perhaps you are both experiencing the same problem?

**Comment by facaiy** [comment]
@quaeler I agree with you. #12123 is exactly the same issue. I'll close the issue because it is a duplicate of #12123. 

Thanks.

**Comment by gdemichillie** [comment]
Just noticing I too am seeing this issue as well. In my case, clang version is:

gregde@gregde-macbookpro:~/tensorflow$ clang -v
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by RenatoUtsch** [comment]
@gunan This seems to be a bug with newer Bazel releases. My non-tensorflow-related Bazel project started throwing these warnings since I updated Bazel.

**Comment by RenatoUtsch** [comment]
@gunan This seems to be a bug with newer Bazel releases. I started having this with all my C++ projects that use Bazel.

It looks like it adds these two flags when compiling with clang (I'm on Linux), even though it shouldn't.
