### ISSUE TITLE
Simple EditDistance constructor is missing in C++

### ISSUE THREAD

**Issue by rasitsimsek** [tensorflow/tensorflow#12264]
### System information
- **Windows 10**
- **TensorFlow installed from source**
- **TensorFlow version 1.3-rc2**
- **Python version 3.5.3**:
- **Bazel N/A**
- **CUDA/cuDNN version N/A**
- **GPU model and memory N/A**
- **N/A**

### Describe the problem
There is no simplier EditDistance::EditDistance() constructor there which only accept sparse::SparseTensor arguments. The EditDistance constructor wants a lot of arguments

`EditDistance::EditDistance(const ::tensorflow::Scope& scope,
                           ::tensorflow::Input hypothesis_indices,
                           ::tensorflow::Input hypothesis_values,
                           ::tensorflow::Input hypothesis_shape,
                           ::tensorflow::Input truth_indices,
                           ::tensorflow::Input truth_values,
                           ::tensorflow::Input truth_shape, const
                           EditDistance::Attrs& attrs)`

instead of

`EditDistance::EditDistance(const ::tensorflow::Scope& scope,
                           const sparse::SparseTensor& hypothesis,
                            const sparse::SparseTensor& truth,
                           EditDistance::Attrs& attrs)`

Internally all hypothesis and truth parameters are put into SparseTensor object. Why SparseTensor parameters are not used in the constructor?

### Source code / logs
N/A

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by skye** [comment]
`sparse::SpareTensor` represents a sparse value, not a symbolic input to an op. Note that SparseTensor is used in op kernels, but not in the C++ graph-building API.

I agree though that it would be useful to have a symbolic SparseTensor concept in the C++ API, similar to in the Python API. I'll mark this as a feature request.

**Comment by sharathppss** [comment]
Hello I was looking to take it up. At this moment it looks like a straightforward fix (I am looking at the python edit distance function and mimic that). Please let me know if there are any specific points to beware of while going ahead with this.

**Comment by skye** [comment]
Hey @sharathppss, thanks for your interest, but I don't think this will be a good feature for a TF newbie. This will require some design work and it's best to get familiar using/working with the code first.

**Comment by sharathppss** [comment]
Thanks @skye. Yeah I was looking at the code, this might be a bit much to get started.

**Comment by sushreebarsa** [comment]
@rasitsimsek One workaround could be to wrap the existing EditDistance class with a custom constructor that takes the desired parameters and sets the options internally. Please upgrade to the latest TF version and if you still have a concern then please create a new ticket. Thank you!
