### ISSUE TITLE
Using Bazel to bulid a tensorflow C++ source in Windows, but stuck at this problem. 

### ISSUE THREAD

**Issue by changliang-sun** [tensorflow/tensorflow#12261]
OS Platform and Distribution : Windows 10
Bazel version :0.5.3

I download the source on https://github.com/tensorflow/tensorflow, and I want to build the example from it. But when I use command "bazel build ...", it prompt error.

(tensorflow) D:\FsCode\tensorflow>bazel build tensorflow/examples/label_image/...
ERROR: D:/fscode/tensorflow/tensorflow/core/BUILD:1528:1: no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by D:/fscode/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: D:/fscode/tensorflow/tensorflow/core/BUILD:1528:1: no such target '//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by D:/fscode/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: D:/fscode/tensorflow/tensorflow/core/BUILD:1528:1: no such target '//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by D:/fscode/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: Analysis of target '//tensorflow/examples/label_image:label_image' failed; build aborted.
INFO: Elapsed time: 1.569s

I search the problem on issues. Somebody suggest to run ./configure. But in Windows system, this can not be run.

**Comment by changliang-sun** [comment]
I found the answer. I have installed msys2, which includes a bash shell. This shell can run command ./configure, and use this shell to build.

The next problem is compile error:
`.\tensorflow/core/platform/profile_utils/cpu_utils.h(46) : error C2146: 语法错误: 缺少“;”(在标识符“int64”的前面)
.\tensorflow/core/platform/profile_utils/cpu_utils.h(46) : error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
.\tensorflow/core/platform/profile_utils/cpu_utils.h(47) : error C2146: 语法错误: 缺少“;”(在标识符“uint64”的前面)
.\tensorflow/core/platform/profile_utils/cpu_utils.h(47) : error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
.\tensorflow/core/platform/profile_utils/cpu_utils.h(47) : error C2086: “int tensorflow::profile_utils::CpuUtils::constexpr”: 重定义
        .\tensorflow/core/platform/profile_utils/cpu_utils.h(46) : 参见“tensorflow::profile_utils::CpuUtils::constexpr”的 声明
.\tensorflow/core/platform/profile_utils/cpu_utils.h(93) : error C2597: 对非静态成员“tensorflow::profile_utils::CpuUtils::DUMMY_CYCLE_CLOCK”的非法引用
.\tensorflow/core/platform/profile_utils/cpu_utils.h(129) : error C2327: “tensorflow::profile_utils::CpuUtils::DUMMY_CYCLE_CLOCK”: 不是类型名称、静态或枚举数
.\tensorflow/core/platform/profile_utils/cpu_utils.h(129) : error C2065: “DUMMY_CYCLE_CLOCK”: 未声明的标识符
.\tensorflow/core/platform/profile_utils/cpu_utils.h(131) : error C2327: “tensorflow::profile_utils::CpuUtils::INVALID_FREQUENCY”: 不是类型名称、静态或枚举数
.\tensorflow/core/platform/profile_utils/cpu_utils.h(131) : error C2065: “INVALID_FREQUENCY”: 未声明的标识符
注意: 包含文件:  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\mutex
注意: 包含文件:   C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\thr/xthread
注意: 包含文件:    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\thr/xtime
注意: 包含文件:    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\thr/xthreads.h
注意: 包含文件:   C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\functional
注意: 包含文件:    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xfunctional
注意: 包含文件:    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\tuple
注意: 包含文件:  .\tensorflow/core/platform/logging.h
注意: 包含文件:   .\tensorflow/core/platform/default/logging.h
注意: 包含文件:    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\sstream
注意: 包含文件:  .\tensorflow/core/platform/profile_utils/android_armv7a_cpu_utils_helper.h
注意: 包含文件:   C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\sys/types.h
tensorflow/core/platform/profile_utils/cpu_utils.cc(27) : error C2146: 语法错误: 缺少“;”(在标识符“int64”的前面)
tensorflow/core/platform/profile_utils/cpu_utils.cc(27) : error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
tensorflow/core/platform/profile_utils/cpu_utils.cc(27) : error C2761: “tensorflow::int64 tensorflow::profile_utils::CpuUtils::INVALID_FREQUENCY”: 不允许成员函数重新声明
tensorflow/core/platform/profile_utils/cpu_utils.cc(103) : error C2597: 对非静态成员“tensorflow::profile_utils::CpuUtils::INVALID_FREQUENCY”的非法引用
INFO: Elapsed time: 48.502s, Critical Path: 10.16s`

I will try to use VS2015. 

Continue...

**Comment by skye** [comment]
Thank you for posting your solution! We suggest that people post to [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) with build problems, as GitHub issues are reserved for bugs and feature requests. Thanks!
