### ISSUE TITLE
Where is gen_logging_ops source code?

### ISSUE THREAD

**Issue by BinhangYuan** [tensorflow/tensorflow#12262]
Hi,

I have a question about this import from tensorflow/tensorflow/python/summary/summary.py line 53:
`from tensorflow.python.ops import gen_logging_ops as _gen_logging_ops`

When I go to the directory  tensorflow/python/ops, there is no such file called gen_logging_ops.

I am wondering how this worked out? BTW, I am tracking the r1.3 version.

Any suggestion is highly appreciated!

Best wishes,
Binhang

**Comment by rohan100jain** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
