### ISSUE TITLE
Integrating both Tensorflow an Caffe in C++

### ISSUE THREAD

**Issue by Yevgeniyr1** [tensorflow/tensorflow#12278]
------------------------

### System information
- I  wrote custom code
- Ubuntu 14.04:
- TensorFlow installed from source
- TF 1.2.1:
-  C++ API 
-  No Bazel
- CUDA 7.5

### Describe the problem
Hello!

I am trying to write a code in C++ using the Eclipse IDE without Bazel. To get my project to do this I had to perform some hacks to generate the Tensorflow C++ APIs. Tensorflow C++ seems to be working fine. I can load a model and perform predictions. I have another code that uses a Caffe library to do something else. These both seem to work fine separately.

I want to integrate BOTH Tensorflow and Caffe in my code. When I include both libraries I get issues that seem to imply that both TF C++ and Caffe(which uses glog) redefine certain things. This leads to my code not working.
 
Is there a way to make TF use glog? Am I doing something wrong? It seems that this is a bug....

Thank you for any help

### Source code / logs
In file included from /usr/local/include/tf/tensorflow/core/platform/logging.h:25:0,
                 from /usr/local/include/tf/tensorflow/core/lib/core/status.h:25,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:28,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:87:0: warning: "LOG" redefined [enabled by default]
 #define LOG(severity) _TF_LOG_##severity
 ^
In file included from /bin/caffe-master/distribute/include/caffe/common.hpp:6:0,
                 from /bin/caffe-master/distribute/include/caffe/blob.hpp:8,
                 from /bin/caffe-master/distribute/include/caffe/caffe.hpp:7,
                 from /home/yevgeniy/Desktop/tovarish/ExtraLibraries/GOTURN-master/src/network/regressor.h:4,
                 from ../ME_T42.cpp:24:
/usr/include/glog/logging.h:483:0: note: this is the location of the previous definition
 #define LOG(severity) COMPACT_GOOGLE_LOG_ ## severity.stream()
 ^
In file included from /usr/local/include/tf/tensorflow/core/platform/logging.h:25:0,
                 from /usr/local/include/tf/tensorflow/core/lib/core/status.h:25,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:28,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:117:0: warning: "VLOG_IS_ON" redefined [enabled by default]
 #define VLOG_IS_ON(lvl) _VLOG_IS_ON(lvl, __FILE__)
 ^
In file included from /usr/include/glog/logging.h:490:0,
                 from /bin/caffe-master/distribute/include/caffe/common.hpp:6,
                 from /bin/caffe-master/distribute/include/caffe/blob.hpp:8,
                 from /bin/caffe-master/distribute/include/caffe/caffe.hpp:7,
                 from /home/yevgeniy/Desktop/tovarish/ExtraLibraries/GOTURN-master/src/network/regressor.h:4,
                 from ../ME_T42.cpp:24:
/usr/include/glog/vlog_is_on.h:82:0: note: this is the location of the previous definition
 #define VLOG_IS_ON(verboselevel)                                \
 ^
In file included from /usr/local/include/tf/tensorflow/core/platform/logging.h:25:0,
                 from /usr/local/include/tf/tensorflow/core/lib/core/status.h:25,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:28,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:119:0: warning: "VLOG" redefined [enabled by default]
 #define VLOG(lvl)                                   \
 ^
In file included from /bin/caffe-master/distribute/include/caffe/common.hpp:6:0,
                 from /bin/caffe-master/distribute/include/caffe/blob.hpp:8,
                 from /bin/caffe-master/distribute/include/caffe/caffe.hpp:7,
                 from /home/yevgeniy/Desktop/tovarish/ExtraLibraries/GOTURN-master/src/network/regressor.h:4,
                 from ../ME_T42.cpp:24:
/usr/include/glog/logging.h:1068:0: note: this is the location of the previous definition
 #define VLOG(verboselevel) LOG_IF(INFO, VLOG_IS_ON(verboselevel))
 ^
In file included from /usr/local/include/tf/tensorflow/core/platform/logging.h:25:0,
                 from /usr/local/include/tf/tensorflow/core/lib/core/status.h:25,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:28,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:127:0: warning: "CHECK" redefined [enabled by default]
 #define CHECK(condition)              \
 ^
In file included from /bin/caffe-master/distribute/include/caffe/common.hpp:6:0,
                 from /bin/caffe-master/distribute/include/caffe/blob.hpp:8,
                 from /bin/caffe-master/distribute/include/caffe/caffe.hpp:7,
                 from /home/yevgeniy/Desktop/tovarish/ExtraLibraries/GOTURN-master/src/network/regressor.h:4,
                 from ../ME_T42.cpp:24:
/usr/include/glog/logging.h:561:0: note: this is the location of the previous definition
 #define CHECK(condition)  \
 ^
In file included from /usr/local/include/tf/tensorflow/core/platform/logging.h:25:0,
                 from /usr/local/include/tf/tensorflow/core/lib/core/status.h:25,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:28,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:268:0: warning: "CHECK_OP_LOG" redefined [enabled by default]
 #define CHECK_OP_LOG(name, op, val1, val2)                            \
 ^
In file included from /bin/caffe-master/distribute/include/caffe/common.hpp:6:0,
                 from /bin/caffe-master/distribute/include/caffe/blob.hpp:8,
                 from /bin/caffe-master/distribute/include/caffe/caffe.hpp:7,
                 from /home/yevgeniy/Desktop/tovarish/ExtraLibraries/GOTURN-master/src/network/regressor.h:4,
                 from ../ME_T42.cpp:24:
/usr/include/glog/logging.h:719:0: note: this is the location of the previous definition
 #define CHECK_OP_LOG(name, op, val1, val2, log)                         \
 ^
In file included from /usr/local/include/tf/tensorflow/core/platform/logging.h:25:0,
                 from /usr/local/include/tf/tensorflow/core/lib/core/status.h:25,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:28,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:276:0: warning: "CHECK_OP" redefined [enabled by default]
 #define CHECK_OP(name, op, val1, val2) CHECK_OP_LOG(name, op, val1, val2)
 ^
In file included from /bin/caffe-master/distribute/include/caffe/common.hpp:6:0,
                 from /bin/caffe-master/distribute/include/caffe/blob.hpp:8,
                 from /bin/caffe-master/distribute/include/caffe/caffe.hpp:7,
                 from /home/yevgeniy/Desktop/tovarish/ExtraLibraries/GOTURN-master/src/network/regressor.h:4,
                 from ../ME_T42.cpp:24:
/usr/include/glog/logging.h:740:0: note: this is the location of the previous definition
 #define CHECK_OP(name, op, val1, val2) \
 ^
In file included from /usr/local/include/tf/tensorflow/core/platform/logging.h:25:0,
                 from /usr/local/include/tf/tensorflow/core/lib/core/status.h:25,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:28,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:279:0: warning: "CHECK_EQ" redefined [enabled by default]
 #define CHECK_EQ(val1, val2) CHECK_OP(Check_EQ, ==, val1, val2)
 ^
In file included from /bin/caffe-master/distribute/include/caffe/common.hpp:6:0,
                 from /bin/caffe-master/distribute/include/caffe/blob.hpp:8,
                 from /bin/caffe-master/distribute/include/caffe/caffe.hpp:7,
                 from /home/yevgeniy/Desktop/tovarish/ExtraLibraries/GOTURN-master/src/network/regressor.h:4,
                 from ../ME_T42.cpp:24:
/usr/include/glog/logging.h:765:0: note: this is the location of the previous definition
 #define CHECK_EQ(val1, val2) CHECK_OP(_EQ, ==, val1, val2)
 ^
In file included from /usr/local/include/tf/tensorflow/core/platform/logging.h:25:0,
                 from /usr/local/include/tf/tensorflow/core/lib/core/status.h:25,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:28,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:280:0: warning: "CHECK_NE" redefined [enabled by default]
 #define CHECK_NE(val1, val2) CHECK_OP(Check_NE, !=, val1, val2)
 ^
In file included from /bin/caffe-master/distribute/include/caffe/common.hpp:6:0,
                 from /bin/caffe-master/distribute/include/caffe/blob.hpp:8,
                 from /bin/caffe-master/distribute/include/caffe/caffe.hpp:7,
                 from /home/yevgeniy/Desktop/tovarish/ExtraLibraries/GOTURN-master/src/network/regressor.h:4,
                 from ../ME_T42.cpp:24:
/usr/include/glog/logging.h:766:0: note: this is the location of the previous definition
 #define CHECK_NE(val1, val2) CHECK_OP(_NE, !=, val1, val2)
 ^
In file included from /usr/local/include/tf/tensorflow/core/platform/logging.h:25:0,
                 from /usr/local/include/tf/tensorflow/core/lib/core/status.h:25,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:28,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:281:0: warning: "CHECK_LE" redefined [enabled by default]
 #define CHECK_LE(val1, val2) CHECK_OP(Check_LE, <=, val1, val2)
 ^
In file included from /bin/caffe-master/distribute/include/caffe/common.hpp:6:0,
                 from /bin/caffe-master/distribute/include/caffe/blob.hpp:8,
                 from /bin/caffe-master/distribute/include/caffe/caffe.hpp:7,
                 from /home/yevgeniy/Desktop/tovarish/ExtraLibraries/GOTURN-master/src/network/regressor.h:4,
                 from ../ME_T42.cpp:24:
/usr/include/glog/logging.h:767:0: note: this is the location of the previous definition
 #define CHECK_LE(val1, val2) CHECK_OP(_LE, <=, val1, val2)
 ^
In file included from /usr/local/include/tf/tensorflow/core/platform/logging.h:25:0,
                 from /usr/local/include/tf/tensorflow/core/lib/core/status.h:25,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:28,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:282:0: warning: "CHECK_LT" redefined [enabled by default]
 #define CHECK_LT(val1, val2) CHECK_OP(Check_LT, <, val1, val2)
 ^
In file included from /bin/caffe-master/distribute/include/caffe/common.hpp:6:0,
                 from /bin/caffe-master/distribute/include/caffe/blob.hpp:8,
                 from /bin/caffe-master/distribute/include/caffe/caffe.hpp:7,
                 from /home/yevgeniy/Desktop/tovarish/ExtraLibraries/GOTURN-master/src/network/regressor.h:4,
                 from ../ME_T42.cpp:24:
/usr/include/glog/logging.h:768:0: note: this is the location of the previous definition
 #define CHECK_LT(val1, val2) CHECK_OP(_LT, < , val1, val2)
 ^
In file included from /usr/local/include/tf/tensorflow/core/platform/logging.h:25:0,
                 from /usr/local/include/tf/tensorflow/core/lib/core/status.h:25,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:28,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:283:0: warning: "CHECK_GE" redefined [enabled by default]
 #define CHECK_GE(val1, val2) CHECK_OP(Check_GE, >=, val1, val2)
 ^
In file included from /bin/caffe-master/distribute/include/caffe/common.hpp:6:0,
                 from /bin/caffe-master/distribute/include/caffe/blob.hpp:8,
                 from /bin/caffe-master/distribute/include/caffe/caffe.hpp:7,
                 from /home/yevgeniy/Desktop/tovarish/ExtraLibraries/GOTURN-master/src/network/regressor.h:4,
                 from ../ME_T42.cpp:24:
/usr/include/glog/logging.h:769:0: note: this is the location of the previous definition
 #define CHECK_GE(val1, val2) CHECK_OP(_GE, >=, val1, val2)
 ^
In file included from /usr/local/include/tf/tensorflow/core/platform/logging.h:25:0,
                 from /usr/local/include/tf/tensorflow/core/lib/core/status.h:25,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:28,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:284:0: warning: "CHECK_GT" redefined [enabled by default]
 #define CHECK_GT(val1, val2) CHECK_OP(Check_GT, >, val1, val2)
 ^
In file included from /bin/caffe-master/distribute/include/caffe/common.hpp:6:0,
                 from /bin/caffe-master/distribute/include/caffe/blob.hpp:8,
                 from /bin/caffe-master/distribute/include/caffe/caffe.hpp:7,
                 from /home/yevgeniy/Desktop/tovarish/ExtraLibraries/GOTURN-master/src/network/regressor.h:4,
                 from ../ME_T42.cpp:24:
/usr/include/glog/logging.h:770:0: note: this is the location of the previous definition
 #define CHECK_GT(val1, val2) CHECK_OP(_GT, > , val1, val2)
 ^
In file included from /usr/local/include/tf/tensorflow/core/platform/logging.h:25:0,
                 from /usr/local/include/tf/tensorflow/core/lib/core/status.h:25,
                 from /usr/local/include/tf/tensorflow/core/framework/variant.h:28,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:285:0: warning: "CHECK_NOTNULL" redefined [enabled by default]
 #define CHECK_NOTNULL(val)                                 \
 ^
In file included from /bin/caffe-master/distribute/include/caffe/common.hpp:6:0,
                 from /bin/caffe-master/distribute/include/caffe/blob.hpp:8,
                 from /bin/caffe-master/distribute/include/caffe/caffe.hpp:7,
                 from /home/yevgeniy/Desktop/tovarish/ExtraLibraries/GOTURN-master/src/network/regressor.h:4,
                 from ../ME_T42.cpp:24:
/usr/include/glog/logging.h:775:0: note: this is the location of the previous definition
 #define CHECK_NOTNULL(val) \
 ^
In file included from ../ME_T42.cpp:62:0:
/usr/local/include/tf/tensorflow/core/lib/core/status.h:37:7: error: expected identifier before ‘int’
 class Status {
       ^
In file included from /usr/local/include/tf/tensorflow/core/framework/variant.h:28:0,
                 from /usr/local/include/tf/tensorflow/core/framework/allocator.h:26,
                 from /usr/local/include/tf/tensorflow/core/framework/tensor.h:22,
                 from /usr/local/include/tf/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tf/tensorflow/cc/ops/const_op.h:19,
                 from ../ME_T42.cpp:297:
/usr/local/include/tf/tensorflow/core/lib/core/status.h:37:14: error: expected unqualified-id before ‘{’ token
 class Status {
              ^
../ME_T42.cpp:2862:1: error: expected ‘}’ at end of input
 }
 ^
../ME_T42.cpp:197:12: warning: ‘c’ defined but not used [-Wunused-variable]
 static int c=0;
            ^
make: *** [ME_T42.o] Error 1

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by warunapww** [comment]
@Yevgeniyr1 
Were you able to find a solution/work around for this problem?
I'm having similar issues with TensorFlow with OpenGL libraries.

**Comment by warunapww** [comment]
OK in my case, X11/Xlib.h file defines Status to int. But TensorFlow also has a Status class which conflicts with the define macro. 

I undefined the Status (using #undef Status) which solved the problem for me.
