### ISSUE TITLE
sequence2sequence model padding 

### ISSUE THREAD

**Issue by nddk** [tensorflow/tensorflow#1228]
In the seq2seq models, paddings are applied to make all sequences in a bucket have the same lengths. And apart from this, it looks like no special handling is applied to the paddings: 

- the encoder encodes the paddings as well
- the basic decoder w/o attention decodes using the last encoding which encodes the paddings
- the decoder with attention attends to the hidden states of the padding inputs too

It would be really helpful if this could be clarified: is it true that, basically the paddings are just a special id/embedding, and the current seq2seq implementation treats them just like other embeddings? And no special mechanism is needed to ignore these padding, for example when encoding a sequence containing paddings; or to decode a sequence containing paddings using the attention-based decoder? So after padding, nothing special is done to the paddings, we can just pretend a padding is just another embedding  (apart from maybe when doing the weighted x-entropy using target_weights)?

If the above is true, then when testing a trained model, is padding needed at all (since at test time, each sentence is decoded separately and not in a batch)? --- It looks like from the code, at test time an input sentence is still bucketed first and then padded?

**Comment by vrv** [comment]
This is a question better suited to StackOverflow, since it is not a bug / feature request.
