### ISSUE TITLE
build_all_ios.sh fail with Error： redefinition of 'NoBarrier_CompareAndSwap'

### ISSUE THREAD

**Issue by jakajacky** [tensorflow/tensorflow#12285]
```
./google/protobuf/stubs/atomicops_internals_atomicword_compat.h:53:19: error: redefinition of
      'NoBarrier_CompareAndSwap'
inline AtomicWord NoBarrier_CompareAndSwap(volatile AtomicWord* ptr,
                  ^
./google/protobuf/stubs/atomicops_internals_x86_gcc.h:55:17: note: previous definition is here
inline Atomic32 NoBarrier_CompareAndSwap(volatile Atomic32* ptr
```

**Comment by skye** [comment]
@petewarden

**Comment by petewarden** [comment]
Could you provide information about which OS and Xcode tools versions you're using? I'm not able to reproduce this with MacOS Sierra 10.12.6 and Xcode 8.3.3.

**Comment by jakajacky** [comment]
@petewarden 
macOS Sierra 10.12.4   Xcode8.3.3  bazel 0.5.3 , download tensorflow  r1.2。It is worth mentioning that i can build older one downloaded on 2017/3/31 , however i forget about the version。

**Comment by aselle** [comment]
@petewarden, PTAL
