### ISSUE TITLE
Loss stays a constant 0.6931 while training 

### ISSUE THREAD

**Issue by linyia01** [tensorflow/tensorflow#12287]
i just add the out maps to a  big value

= >   step: 0 loss: 0.6773 accuracy:0.61
= >   step: 1 loss: 2.4587 accuracy:0.66
= >   step: 2 loss: 5.3353 accuracy:0.32
= >   step: 3 loss: 1.0234 accuracy:0.52
= >   step: 4 loss: 10.6901 accuracy:0.67
= >   step: 5 loss: 1.9899 accuracy:0.62
= >   step: 6 loss: 3.5713 accuracy:0.63
= >   step: 7 loss: 0.6869 accuracy:0.64
= >   step: 8 loss: 0.6931 accuracy:0.65
= >   step: 9 loss: 0.6931 accuracy:0.60
= >  = = = = = =  > > > > > >    step: 9 loss: 0.6931 accuracy:0.66
= >   step: 10 loss: 0.6931 accuracy:0.70
= >   step: 11 loss: 0.6931 accuracy:0.58
= >   step: 12 loss: 0.6931 accuracy:0.72
= >   step: 13 loss: 0.6931 accuracy:0.81
= >   step: 14 loss: 0.6931 accuracy:0.67
= >   step: 15 loss: 0.6931 accuracy:0.68
= >   step: 16 loss: 0.6931 accuracy:0.72
= >   step: 17 loss: 0.6931 accuracy:0.72
= >   step: 18 loss: 0.6931 accuracy:0.71
= >   step: 19 loss: 0.6931 accuracy:0.72
= >  = = = = = =  > > > > > >    step: 19 loss: 0.6931 accuracy:0.66
= >   step: 20 loss: 0.6931 accuracy:0.60
= >   step: 21 loss: 0.6931 accuracy:0.66
= >   step: 22 loss: 0.6931 accuracy:0.70
= >   step: 23 loss: 0.6931 accuracy:0.73
= >   step: 24 loss: 0.6931 accuracy:0.69
= >   step: 25 loss: 0.6931 accuracy:0.59
= >   step: 26 loss: 0.6931 accuracy:0.69
= >   step: 27 loss: 0.6931 accuracy:0.76
= >   step: 28 loss: 0.6931 accuracy:0.72
= >   step: 29 loss: 0.6931 accuracy:0.67
= >  = = = = = =  > > > > > >    step: 29 loss: 0.6931 accuracy:0.67
= >   step: 30 loss: 0.6931 accuracy:0.66
= >   step: 31 loss: 0.6931 accuracy:0.74
= >   step: 32 loss: 0.6931 accuracy:0.75
= >   step: 33 loss: 0.6931 accuracy:0.80
= >   step: 34 loss: 0.6931 accuracy:0.57
.........................

**Comment by linyia01** [comment]
http://www.huangzhicheng.com.cn/2017/05/02/%E8%A7%A3%E5%86%B3Caffe%E8%AE%AD%E7%BB%83%E8%BF%87%E7%A8%8B%E4%B8%ADloss%E4%B8%8D%E5%8F%98%E9%97%AE%E9%A2%98/    the same problem

**Comment by yaroslavvb** [comment]
Closing because this doesn't seem like a bug in TensorFlow

**Comment by xu9010** [comment]
-log(0.5) = 0.6931
