### ISSUE TITLE
Tensorflow Bug (load avg rises very high, cannot kill process, system freeze)

### ISSUE THREAD

**Issue by dlaj** [tensorflow/tensorflow#12291]
The following script run.sh will increase load avg to several 100 (it takes usually 100 iterations)

run.sh
```
#!/bin/bash
var=0
while :
do
        echo "round --->" $((var++))
        python testTF.py
        sleep 3
done
```

testTF.py
```
#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'


import tensorflow as tf
print("START SESSION...")
session = tf.Session()
print("...SESSION DONE")

```

The error started to appear in Ubuntu 14.04 (where it freezes the workstation).
Updating to Ubuntu 16.04 makes the workstation more responsible, but a reboot is still necessary.
observations:
* I can not kill the PID of the python process when the load avg rises
* changing to python3 did not resolve the issue
* compiling tf (1.3.0) from source did not resolve the issue

== cat /etc/issue ===============================================
Linux bipower6 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.3 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux bipower6 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.13.1)
protobuf (3.3.0)
tensorflow-gpu (1.2.1)

== check for virtualenv =========================================
True

== tensorflow import ============================================
tf.VERSION = 1.2.1
tf.GIT_VERSION = v1.2.0-5-g435cdfc
tf.COMPILER_VERSION = v1.2.0-5-g435cdfc
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /home/a/torch/install/lib:/home/a/torch/install/lib::/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/:/usr/local/lib/:/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/:/usr/local/lib/
DYLD_LIBRARY_PATH /home/a/torch/install/lib:/home/a/torch/install/lib:

== nvidia-smi ===================================================
Tue Aug 15 11:25:32 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:02:00.0     Off |                  N/A |
| 29%   44C    P0    41W / 180W |      0MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    Off  | 0000:04:00.0     Off |                  N/A |
|  0%   52C    P0    56W / 250W |      0MiB / 12189MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           Off  | 0000:83:00.0     Off |                    0 |
| N/A   69C    P0   128W / 250W |  21897MiB / 22912MiB |     93%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    2     89766    C   /home/a/dl/bin/python                        21895MiB |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-8.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-8.0/doc/man/man7/libcudart.7
/usr/local/cuda-8.0/lib64/libcudart_static.a
/usr/local/cuda-8.0/lib64/libcudart.so.8.0.61
/usr/local/cuda-7.5/doc/man/man7/libcudart.so.7
/usr/local/cuda-7.5/doc/man/man7/libcudart.7
/usr/local/cuda-7.5/lib/libcudart_static.a
/usr/local/cuda-7.5/lib/libcudart.so.7.5.18
/usr/local/cuda-7.5/lib64/libcudart_static.a
/usr/local/cuda-7.5/lib64/libcudart.so.7.5.18
(END)

**Comment by skye** [comment]
I wasn't able to reproduce this. I'm gonna mark this as community support in case anyone else has run into similar issues, but we should probably close this if no one else can repro.

**Comment by dlaj** [comment]
Updating to the new NVidia driver (384.59) resolves the issue.

If you have the same problem, do not use the driver included in the Cuda8 package.
