### ISSUE TITLE
Cant install, Mac - El Capitan - not a supported wheel

### ISSUE THREAD

**Issue by act65** [tensorflow/tensorflow#123]
I try using this command in terminal 
$ pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
but i get "tensorflow-0.5.0-py2-none-any.whl is not a supported wheel on this platform."

I dont know what I did wrong, i am pretty sure pip is up to date, and I just downloaded homebrew for this...

I am using python with the anaconda package if that effects anything?

I have no idea what I am doing here, help please.

**Comment by yyttr3** [comment]
I get the same issue. I can not install TensorFlow.
"tensorflow-0.5.0-py2-none-any.whl is not a supported wheel on this platform."

**Comment by act65** [comment]
whatever you managed to do doesnt seem to want to work for me

the result of running "pip --version" was 
"pip 7.1.2 from /Users/act65/anaconda/lib/python3.4/site-packages (python 3.4)"

i dont get any errors my reinstalling pip
running 
"$ pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl"
i get the same error, not a supported wheel...
i tried running sudo pip ... and got
"The directory '/Users/act65/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag."

I have tried a few different things but now have run out of ideas, I tried using docker instead and I think it worked, but how do i get the docker environment over into anaconda and thus sypder, my IDE???

I also tried using the virtualenv thing, but that doesnt work either - 
i run 
"$ virtualenv --system-site-packages ~/tensorflow)
and get
"ERROR: The executable /Users/act65/tensorflow/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/Users/act65' (should be '/Users/act65/tensorflow')
ERROR: virtualenv is not compatible with this system or executable"

**Comment by yyttr3** [comment]
pip --version ought output something similar to "pip 7.1.2 from /Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg (python 2.7)". 

otherwise it will not download. easy_install will provide you with the correct version of pip to use in this case.

**Comment by act65** [comment]
ok, so that could/would mean that the problem is with using anaconda?

**Comment by act65** [comment]
ok, i tried something else and I might be getting somewhere? i downloaded the source files and tried just running this

$ pip install tensorflow

which returned

"Requirement already satisfied (use --upgrade to upgrade): tensorflow in ./anaconda/lib/python3.4/site-packages
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.9.2 in ./anaconda/lib/python3.4/site-packages (from tensorflow)
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in ./anaconda/lib/python3.4/site-packages/six-1.10.0-py3.4.egg (from tensorflow)"

and i am a little confused as to what it is trying to tell me

**Comment by yyttr3** [comment]
You should be able download python 2.7 concurrently with python 3.4.

Look at the requirements on tensorflow.org. Python 3.4 is not supported.

**Comment by act65** [comment]
ah...
my bad
thanks

**Comment by saleeh93** [comment]
Thanks @yyttr3 You help me put

**Comment by KOHMA** [comment]
Hey, I had the same issue when trying to install Tensorflow in the Anaconda distribution of Python. I could fix it by installing tensorflow via this site: https://conda.anaconda.org/jjhelmus

I found this in this thread: https://github.com/tensorflow/tensorflow/issues/1097

Cheers and keep on deep learning :)
