### ISSUE TITLE
Exception when shutting down TensorFlow after running some ops

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorflow#12307]
## Error

The following error appears when exiting the Python session after a TensorFlow op has been run in a session:
```
Exception TypeError: "'NoneType' object is not callable" in <bound method Context.__del__ of <tensorflow.python.eager.context.Context object at 0x7fcd7f98b450>> ignored
```

The Python session still exits cleanly (status 0).

## Repro

```
$ cat test.py
import sys
import tensorflow as tf
tf.Session().run(tf.square(0))
sys.stderr.write("Done.\n")
$ . tensorflow-nightly-20170814/bin/activate
$ python test.py 2>&1 | grep -Fv 'could speed up CPU computations'
Done.
$ . tensorflow-nightly-20170815/bin/activate
$ python test.py 2>&1 | grep -Fv 'could speed up CPU computations'
Done.
Exception TypeError: "'NoneType' object is not callable" in <bound method Context.__del__ of <tensorflow.python.eager.context.Context object at 0x7f9d8795c450>> ignored
```

Most ops seem to trigger this: I tried `tf.square`, `tf.add`, and `tf.summary.scalar` and `tf.summary.text`, and they all do. However, `tf.constant` does not.

## Introduction

Bug introduced between 20170814 and 20170815 nightlies. (In particular, [build 588] does not have the bug, while [build 589] does.) The changelog for these two builds is b93fd37e143bcdd6339f8e6081c948384a262e0b...1d33a59a9d554be863cfb06e9aa0ce1fa33ce9e6, which does include changes to eager.

[build 588]: http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/588/
[build 589]: http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/589/

**Comment by carlthome** [comment]
Maybe not related, but shouldn't you `close()` the tf.Session object to ensure safe termination?

**Comment by wchargin** [comment]
@carlthome: Unfortunately, `python -c 'import tensorflow as tf; sess = tf.Session(); sess.run(tf.square(0)); sess.close()'` exhibits the same behavior, as does `python -c $'import tensorflow as tf\nwith tf.Session() as sess: sess.run(tf.square(0))'`.

**Comment by wchargin** [comment]
This behavior no longer happens in tensorflow-nightly-20170816:
```
$ python -c 'import tensorflow as tf; tf.Session().run(tf.square(0))'
2017-08-16 09:48:29.949554: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
```
Build 591 has the bug, while build 592 does not. The diff is d480ac587a0040acfc21bc2f63faa12cfd3194cc...3686ef0d51047d2806df3e2ff6c1aac727456c1d.

From the commit description, I suspect that 9e6183e4a fixed this.
