### ISSUE TITLE
Imagenet example error

### ISSUE THREAD

**Issue by cracker0dks** [tensorflow/tensorflow#1230]
### Environment info
Operating System: Windows with latest docker image (only cpu)

after running: python classify_image.py and loading the model I got the folling error:

`Succesfully downloaded inception-2015-12-05.tgz 88931400 bytes.                                                                                                    [libprotobuf ERROR google/protobuf/src/google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.                             Traceback (most recent call last):                                                                                                                                   File "classify_image.py", line 213, in <module>                                                                                                                      tf.app.run()                                                                                                                                                     File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run                                                            sys.exit(main(sys.argv))                                                                                                                                         File "classify_image.py", line 209, in main                                                                                                                          run_inference_on_image(image)                                                                                                                                    File "classify_image.py", line 159, in run_inference_on_image                                                                                                        create_graph()                                                                                                                                                   File "classify_image.py", line 141, in create_graph                                                                                                                  graph_def.ParseFromString(f.read())                                                                                                                            google.protobuf.message.DecodeError: Error parsing message `   

what can I do ?

**Comment by tmaila** [comment]
This is likely the same issue as issue [582](https://github.com/tensorflow/tensorflow/issues/582).

**Comment by tmaila** [comment]
For a quick solution type the following before running tensorflow

`export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`

**Comment by ritsu1228** [comment]
Were you using a precompiled version or building from source? 

I used to see the same problem. If you are building from source, updating to the latest code and doing a rebuild should solve the problem (it seems to be fixed in 2f756013f5bcc39ee288eed9da8d27cf4ec16f7e).

**Comment by tmaila** [comment]
@ritsu1228 I'm experiencing this with the official prebuilt 0.7.0 development docker image.

**Comment by ritsu1228** [comment]
@tmaila Seems like 0.7.0 was released before commit 2f756013f5bcc39ee288eed9da8d27cf4ec16f7e. So I think 0.7.0 should have this problem and your solution works perfect. If you upgrade to 0.7.1, you won't need to do `export`.

**Comment by cracker0dks** [comment]
yeah with the latest image I get no errors anymore. Sry for the late response.
Thanks for your help guys!
