### ISSUE TITLE
memory leak bug

### ISSUE THREAD

**Issue by babak-badnava** [tensorflow/tensorflow#12302]
Hi, I have seen many issues reporting Tensorflow memory leak, so I wanted to report another sample of leak. 
I was testing the GA3C code and after a while (about a day) the process taking all of 32g of memory.
system spec is 
OS : Ubuntu 17.04
tensorflow version : 1.2.1 binary instalation
cuda version : 7.5
gpu : GeForce GTX 1080 SLI, 8gig of gpu memory

you can get the code from : 
https://github.com/babak-badnava/GA3C

with many thanks

**Comment by reedwm** [comment]
This seems similar to #11721. If possible, can you post a simpler example? It is difficult to debug this issues on large projects, and it is unknown if the memory leak is in TensorFlow itself or in the GA3C code.

Marking as contributions welcome if anyone wants to take a stab at finding where the memory leak is in the GA3C or TensorFlow code.

**Comment by ciphx** [comment]
I want to start contributing to this. Can you tell me where to start?

**Comment by reedwm** [comment]
@ciphx see if you can reproduce the problem. If you can, try removing parts of GA3C, checking if the problem still occurs as you remove pieces of it. The goal would be to get a small and simple piece of code that reproduces the problem.

You can also enable verbose logging and look at the \_\_LOG_MEMORY\_\_  messages to see if there are many Tensors being allocated without being deallocated.

**Comment by sushreebarsa** [comment]
@babak-badnava Could you please upgrade to the latest TF version as we are unable to reproduce the same on the new code base. Kindly have a look at this migration [doc](https://www.tensorflow.org/guide/migrate).
If you still have a concern then please create a new ticket!
Thank you!
