### ISSUE TITLE
Tensorflow installation fails on python 3.3.6

### ISSUE THREAD

**Issue by jeevandev** [tensorflow/tensorflow#12309]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: See below
- **TensorFlow installed from (source or binary)**: Tried with pip3
- **TensorFlow version (use command below)**: 
- **Python version**: 3.3.6
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:
== cat /etc/issue ===============================================
Linux 11bb6e68305e 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="14.04.5 LTS, Trusty Tahr"
VERSION_ID="14.04"

== are we in docker =============================================
Yes

== compiler =====================================================
c++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux 11bb6e68305e 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================

== check for virtualenv =========================================
True

== tensorflow import ============================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'tensorflow'

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

### Describe the problem
When i try to install tensorflow on Ubunutu 14.04 (python 3.3.6, pip 9.0.1) it fails because of numpy version >=1.11.0 which requires Python version 2.7 or >= 3.4. I followed the installations steps mentioned in https://www.tensorflow.org/install/install_linux. Installation works fine on python 3.4/3.6. I think it would be good to specify if 3.3 is not supported here (make Python: 3.4+) https://www.tensorflow.org/install/install_linux#prerequisite_python_and_pip

### Source code / logs
(env33)root@11bb6e68305e:/home# python --version
Python 3.3.6

(env33)root@11bb6e68305e:/home# pip3 install --upgrade
You must give at least one requirement to install (see "pip help install")
(env33)root@11bb6e68305e:/home# pip3 install --upgrade pip
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Uninstalling pip:
      Successfully uninstalled pip
Successfully installed pip
Cleaning up...

(env33)root@11bb6e68305e:/home# pip3 install --upgrade tensorflow
Collecting tensorflow
  Downloading tensorflow-1.2.1-cp33-cp33m-manylinux1_x86_64.whl (35.0MB)
    100% |################################| 35.0MB 58kB/s
Collecting numpy>=1.11.0 (from tensorflow)
  Downloading numpy-1.12.1.zip (4.8MB)
    100% |################################| 4.8MB 429kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bbyh55/numpy/setup.py", line 34, in <module>
        raise RuntimeError("Python version 2.7 or >= 3.4 required.")
    RuntimeError: Python version 2.7 or >= 3.4 required.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bbyh55/numpy/

(env33)root@11bb6e68305e:/home# pip --version
pip 9.0.1 from /home/env33/lib/python3.3/site-packages (python 3.3)

**Comment by carlthome** [comment]
Python 3.3.6 is really old. You have to update Python for TensorFlow to work.

**Comment by jeevandev** [comment]
Yes we did that, i think it would be good if we can specify https://www.tensorflow.org/install/install_linux#prerequisite_python_and_pip explicitly that 3.4+ is supported, currently it says 3.3+
