### ISSUE TITLE
`fit()` instance method of `skflow.TensorFlowDNNClassifier` raises unexpected error

### ISSUE THREAD

**Issue by Kautenja** [tensorflow/tensorflow#12311]
### System information

- **Custom code?** no, elementary example for classifying the Iris dataset
- **Operating System**: MacOS 10.12.6
- **TensorFlow installed from (source or binary)**: binary using `pip3 install tensorflow` and later `pip3 install skflow`
- **TensorFlow version (use command below)**: v1.2.0-5-g435cdfc 1.2.1
- **Python version**: Python 3.6.2
- **GPU model and memory**: Intel Iris integrated graphics
- **Exact command to reproduce**: the `fit` instance method of `skflow.TensorFlowDNNClassifier`

### Describe the problem

Calling `fit` on instances of `skflow.TensorFlowDNNClassifier` produces an `AttributeError` about `tensorflow` not having an attribute called `histogram_summary`.

### Source code / logs

```python
import skflow
from sklearn import datasets, metrics
 
iris = datasets.load_iris()
clf = skflow.TensorFlowDNNClassifier(hidden_units=[10, 20, 10], n_classes=3)
clf.fit(iris.data, iris.target)
```

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/skflow/estimators/base.py", line 200, in fit
    self._setup_training()
  File "/usr/local/lib/python3.6/site-packages/skflow/estimators/base.py", line 133, in _setup_training
    tf.histogram_summary("X", self._inp)
AttributeError: module 'tensorflow' has no attribute 'histogram_summary'
```

**Comment by skye** [comment]
@ispirmustafa can you comment or redirect to someone who can? Thanks.

**Comment by terrytangyuan** [comment]
@Kautenja you are using SUPER old code. I am surprised to see the reference to the word "skflow". Check out `tf.estimator`.
