### ISSUE TITLE
Indexing problem in tensorflow with tf.where()

### ISSUE THREAD

**Issue by shaifugpt** [tensorflow/tensorflow#12320]
I want to clip the variable 'a' values which are less than or equal to max_val.

     ValueError: Shape must be rank 1 but is rank 3 for 'strided_slice_1' (op: 'StridedSlice') with input shapes: [13,20], [1,?,2], [1,?,2], [1].

     tf.clip_by_value(a[tf.where(tf.less_equal(a,max_val))],0,0)

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
