### ISSUE TITLE
Jenkins' PR builds have been failing regularly since Aug. 10

### ISSUE THREAD

**Issue by quaeler** [tensorflow/tensorflow#12331]
I don't know if the commonality is the state of master when the branches for these changes were taken, or if there is something endemic to the current builders, or ? but the failures appear to have nothing to do with actual code changes being submitted in at least some cases.

https://ci.tensorflow.org/job/tensorflow-pull-requests-multijob/

**Comment by skye** [comment]
@gunan 

I think our builds have been unstable the last few days. Also, please refrain from using vulgar terms, this is a family-friendly github project (I edited your original post accordingly).

**Comment by quaeler** [comment]
What vulgar terms??

**Comment by gunan** [comment]
Pull requests exclusively test unsubmitted code, so it is possible for them to be broken most of the time.
However I see that we have some breakages on github master:
https://ci.tensorflow.org/view/Tensorflow%20Jenkins%20Monitored%20builds/

**Comment by quaeler** [comment]
@gunan I can only speak to my PR builds as far as intimate details, but the failures in the two build attempts are in code base areas that don't touch my changes.

**Comment by gunan** [comment]
At the moment, I see breakages in `tensorflow-master-*` builds in python3 and mac here:
https://ci.tensorflow.org/view/Tensorflow%20Jenkins%20Monitored%20builds/
But I do not see any long time trends. We will still look into what is going on, and see if there are any infrastructure issues we can address.

**Comment by quaeler** [comment]
Ok - thanks & much appreciated; please feel free to close this if it is being tracked elsewhere (out of bounds or not.)
