### ISSUE TITLE
[Feature Request] provide a option to not call SessionRunHook in sess.run()

### ISSUE THREAD

**Issue by hongjic** [tensorflow/tensorflow#12343]
### Describe the problem
It is not necessary to execute all the bundled SessionRunHooks in some ```sess.run()``` cases.
For example, `sess.run(enqueue)` in another thread.
its better to have an option like this:
`session.run(run_hooks=True)`

I would like to contribute this if someone think its a good idea.

**Comment by skye** [comment]
@ispirmustafa can you comment? Thanks.

**Comment by ispirmustafa** [comment]
@isaprykin is looking in to this.

**Comment by isaprykin** [comment]
We added MonitoredSession.run_step_fn.  We hope it satisfies the use case.
