### ISSUE TITLE
convert .ckpt to .pb

### ISSUE THREAD

**Issue by LiangHao92** [tensorflow/tensorflow#12348]
I trained my own model using ssd_mobilenets in object_detection, and it works well on my computer. I see the update of android demo, I want to use the ssd_mobilenets model on my android phone. But I only have .ckpt files, and do not know how to trans .ckpt to .pb, because the graph is too comlex to see which is the final tensor name. Does only one know how to genetate .pb of ssd_mobilenets

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
