### ISSUE TITLE
Tensorflow android can not check results for optimized model

### ISSUE THREAD

**Issue by astrung** [tensorflow/tensorflow#12351]
I used this tutorial to run model on android : https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2/index.html?index=..%2F..%2Findex#4 . But after pruning `DecodeJpeg` by command : 

    python -m tensorflow.python.tools.optimize_for_inference \
    --input=tf_files/retrained_graph.pb \
    --output=tf_files/optimized_graph.pb \
    --input_names="Cast" \
    --output_names="final_result"
I can not check the result with this command : 

    python -m scripts.label_image \
    tf_files/flower_photos/daisy/21652746_cc379e0eea_m.jpg \
    tf_files/optimized_graph.pb

,it shows error : `TypeError: Cannot interpret feed_dict key as Tensor: The name 'DecodeJpeg/contents:0' refers to a Tensor which does not exist. The operation, 'DecodeJpeg/contents', does not exist in the graph.`. So how can i check result for optimized android model on computer ?

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
