### ISSUE TITLE
404 for linux GPU python2 download

### ISSUE THREAD

**Issue by houjincheng1992** [tensorflow/tensorflow#12355]
HTTP ERROR 404

Click the url in readme, following occurs:
Problem accessing /view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-1.3.0rc2-cp27-none-linux_x86_64.whl. Reason:
 Not Found

**Comment by skye** [comment]
@gunan do you know what the URL should be? It's specifically for the Linux GPU: Python 2 link under the Installation section of https://github.com/tensorflow/tensorflow

**Comment by gunan** [comment]
The new URL should not have the rc2.

@av8ramit  could you take a look?

**Comment by av8ramit** [comment]
Yeah I'll take a look!

**Comment by av8ramit** [comment]
https://github.com/tensorflow/tensorflow/pull/12370

**Comment by av8ramit** [comment]
https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-1.3.0-cp27-none-linux_x86_64.whl
