### ISSUE TITLE
tf.contrib.slim evaluation: outdated documentation

### ISSUE THREAD

**Issue by fabiosony** [tensorflow/tensorflow#12357]
https://github.com/tensorflow/tensorflow/blob/d7fa7ae8ac15118393b6a549eb98ec9ca23497c0/tensorflow/contrib/slim/python/slim/evaluation.py
The documentation to this, in the first section (Evaluating metrics) uses this code to do the evaluation of the metrics directly (within an existing session, without having to reference a specific checkpoint):
```
  with tf.Session() as sess:
    metric_values = slim.evaluation(
        sess,
        num_evals=1,
        inital_op=initial_op,
        eval_op=names_to_updates.values(),
        final_op=name_to_values.values())
```
This code, however, does not work anymore, as the function `slim.evaluation` doesn't exist now.
what would now be the preferred way to do this?

**Comment by skye** [comment]
@sguada can you comment or redirect to someone who can? Thanks.

**Comment by sguada** [comment]
Not sure I understand what is the problem, could you clarify it?

**Comment by sguada** [comment]
Ok got it, now I understand.

Yeah the documentation need to be updated, do you want to do it?

**Comment by fabiosony** [comment]
I could do that - however, the function evaluate_once() is not equivalent to the one in the documentation, which would have been useful for cases like evaluating the current model (not checkpointed) while in the training loop. Is there a reason why that functionality has been removed? Or has it been replaced by something else?

**Comment by XFeiF** [comment]
@sguada I made some changes. Can you review this? #21020
