### ISSUE TITLE
Windows 7 :  python mnist_with_summaries.py, having the error

### ISSUE THREAD

**Issue by angel1288** [tensorflow/tensorflow#12350]
## When running " python tensorflow/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py ", it has occurred the following error: 

- 
![image](https://user-images.githubusercontent.com/20549473/29401037-213d52c6-8362-11e7-818d-58cf652e5efa.png)

**Comment by aaronzs** [comment]
Try to create a `tmp` folder yourself in `C:\tmp`.
or
You can go to `line 204` and `line 210` of `mnist_with_summaries.py` and change `/tmp` to wherever you want, for example `/tmp` -> `.`.

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by angel1288** [comment]
@aaronzs 

- According to your method, I have successfully modified. Thank you! 

- I changed _line 204_ and _line 210_ of _mnist_with_summaries.py_ to the _local directory_.

**Comment by BoyInBlackHat** [comment]
@angel1288 
I do as what you told,but I get a new problem.Can you tell how to slove this?
![image](https://user-images.githubusercontent.com/32335442/30921956-581ff0da-a3da-11e7-82c4-e783d03e7409.png)

**Comment by BoyInBlackHat** [comment]
I really need help
