### ISSUE TITLE
tensorflow with cocos2d-x failed to build the project

### ISSUE THREAD

**Issue by basitjawaidgranjur** [tensorflow/tensorflow#12362]
**tensorflow with cocos2d-x failed to build the project
when building project the terminal throws error**

`jni/../../../../tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory  #include "unsupported/Eigen/CXX11/Tensor"`

**Comment by reedwm** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by basitjawaidgranjur** [comment]
@reedwm actually I have successfully able to build the .so file for arm-v7 architecture from the sources, and also create a jar file, after that I have tried to build the cocos2d-x project with prebuilt .so file of tensorflow, but while compiling it throws error mentioned above

for OS : Android 
Architecture arm-v7
Cocos2d-x 3.14 c++
Development environment Mac OS x 
let me know if need anything else

**Comment by reedwm** [comment]
@gunan any thoughts? I do not know what cocos2d-x is or how it relates to TensorFlow. If the TensorFlow binary is prebuilt, why is it giving an error when building a cocos2d-x project?

**Comment by gunan** [comment]
I have no idea what cocos2d-x is. I recommend reaching out to the maintainers of the library. If in those discussions you can come up with something actionable for tensorflow, we will be happy to help.

@andrewharp @petewarden just in case they know anything

**Comment by basitjawaidgranjur** [comment]
@reedwm @gunan cocos2d-x is a cross-platform gaming engine based on C++, for Android we have to build cocos2d-x library source and c++ classes with NDK, and to add prebuilt libraries we simply put in a directory and let android.mk know about it.
the problem arises when we try to build app with NDK it successfully able to detect the prebuilt library, and compile classes (contains tensor.h), but throws the above error.

The reason according to my understanding might be
> either the eigen is not supported or has issue with android 
> either the prebuilt eigen is not compatible with native android NDK. 

can you please look into this issue, I have to deliver this app soon

**Comment by andrewharp** [comment]
Sorry, but we can't support Android.mk based builds of TF. Bazel, Makefile, and to some extent cmake are the supported options for Android. You may be able to find the assistance you need over at StackOverflow.

That said, might be worth checking out #4680 to see if any of the workarounds apply at all.
