### ISSUE TITLE
Estimator classification export feature request: input single string Tensor input limitation.

### ISSUE THREAD

**Issue by Ouwen** [tensorflow/tensorflow#12367]
Within class `ClassificationOutput` contains the `as_signature_def` method. I was wondering why there is a limitation that this method only allows recievor_tensors of length 1.

https://github.com/tensorflow/tensorflow/blob/53aef8a3a5920e53f7da3ea2140374546d1bf708/tensorflow/python/estimator/export/export_output.py#L109-L118

For example the following code should seemingly just "work" for the model created from the [wide and deep model tutorial.
](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/examples/learn/wide_n_deep_tutorial.py)

```
feature_inputs = {
        'age': tf.placeholder(dtype=tf.float32, shape=[1,1], name='age'),
        'capital_gain': tf.placeholder(dtype=tf.float32, shape=[1,1], name='age'),
        'capital_loss': tf.placeholder(dtype=tf.float32, shape=[1,1], name='capital_loss'),
        'education': tf.placeholder(dtype=tf.string, shape=[1,1], name='education'),
        'education_num': tf.placeholder(dtype=tf.float32, shape=[1,1], name='education_num'),
        'gender': tf.placeholder(dtype=tf.string, shape=[1,1], name='gender'),
        'hours_per_week': tf.placeholder(dtype=tf.float32, shape=[1,1], name='hours_per_week'),
        'native_country': tf.placeholder(dtype=tf.string, shape=[1,1], name='native_country'),
        'occupation': tf.placeholder(dtype=tf.string, shape=[1,1], name='occupation'),
        'relationship': tf.placeholder(dtype=tf.string, shape=[1,1], name='relationship'),
        'workclass': tf.placeholder(dtype=tf.string, shape=[1,1], name='workclass') 
    }

serving_input_receiver_fn = tf.estimator.export.build_raw_serving_input_receiver_fn(feature_inputs)

# model is the loaded wide and deep model produced
model.export_savedmodel("./my_dir",  serving_input_receiver_fn)
```

However there is an error here:
```
/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/export/export.pyc in build_all_signature_defs(receiver_tensors, export_outputs)
    158       '{}'.format(output_key or 'None'):
    159       export_output.as_signature_def(receiver_tensors)
--> 160       for output_key, export_output in export_outputs.items()}
    161 
    162   return signature_def_map

/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/export/export.pyc in <dictcomp>((output_key, export_output))
    158       '{}'.format(output_key or 'None'):
    159       export_output.as_signature_def(receiver_tensors)
--> 160       for output_key, export_output in export_outputs.items()}
    161 
    162   return signature_def_map

/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/export/export_output.pyc in as_signature_def(self, receiver_tensors)
    110     if len(receiver_tensors) != 1:
    111       raise ValueError('Classification input must be a single string Tensor; '
--> 112                        'got {}'.format(receiver_tensors))
    113     (_, examples), = receiver_tensors.items()
    114     if dtypes.as_dtype(examples.dtype) != dtypes.string:

ValueError: Classification input must be a single string Tensor; got {'hours_per_week': <tf.Tensor 'hours_per_week_14_1:0' shape=(?, 1) dtype=float32>, 'native_country': <tf.Tensor 'native_country_14_1:0' shape=(?, 1) dtype=string>, 'relationship': <tf.Tensor 'relationship_14_1:0' shape=(?, 1) dtype=string>, 'gender': <tf.Tensor 'gender_14_1:0' shape=(?, 1) dtype=string>, 'age': <tf.Tensor 'age_14_1:0' shape=(?, 1) dtype=float32>, 'capital_gain': <tf.Tensor 'capital_gain_14_1:0' shape=(?, 1) dtype=float32>, 'workclass': <tf.Tensor 'workclass_14_1:0' shape=(?, 1) dtype=string>, 'capital_loss': <tf.Tensor 'capital_loss_14_1:0' shape=(?, 1) dtype=float32>, 'education': <tf.Tensor 'education_14_1:0' shape=(?, 1) dtype=string>, 'education_num': <tf.Tensor 'education_num_14_1:0' shape=(?, 1) dtype=float32>, 'occupation': <tf.Tensor 'occupation_14_1:0' shape=(?, 1) dtype=string>}
```

**Comment by skye** [comment]
@martinwicke can you comment or redirect to someone who can? Thanks.

**Comment by martinwicke** [comment]
@nfiedel for restrictions on classification.

This is a class meant to fit in with tensorflow/serving, for which the classification signature always goes for a single string tensor (which typically contains a serialized tf.Example record) to a classification result.

We also export a generic signature, which takes any input tensors and returns any input tensors.

**Comment by Ouwen** [comment]
Correct me if I'm wrong, the generic signature you are referring to seems to be the `PredictOutput` class

https://github.com/tensorflow/tensorflow/blob/2133b83376a3439924a0bb9bac7b4a8b716a6fc0/tensorflow/python/estimator/export/export_output.py#L153-L159

However, for the canned estimator model it is using a head which doesn't include the `PredictOutput` class as an export output.

https://github.com/tensorflow/tensorflow/blob/2133b83376a3439924a0bb9bac7b4a8b716a6fc0/tensorflow/python/estimator/canned/head.py#L661-L673.

Is there a clean way for the inputs to a `SavedModel` estimator model to be multiple tensors as opposed to 1 serialized string tensor?

**Comment by nfiedel** [comment]
Adding to Martin's reply, SavedModel's Signatures (SignatureDef) support arbitrarily many input and output tensors.

Many Canned Estimators are built to match 1:1 with the TensorFlow Serving APIs, most notably for various types of Regression & Classification models. The Predict API supports full generality of arbitrarily many inputs and outputs.

You can see an enumeration of these Signature method_names and Tensor names here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/signature_constants.py

So I think the remaining question is how to get the input data into your particular model. The options at a high level are, I think:

1. Convert your input data to tf.Example
2. Figure out how to construct & save a model that takes multiple input tensors.

**Comment by pk11** [comment]
We have a similar model [DNNRegressor](https://www.tensorflow.org/api_docs/python/tf/estimator/DNNRegressor) that seems to require a single string tensor. `saved_model_cli` also seems to suggest that it has only a single head i.e.
```$ saved_model_cli show  --dir /tmp/saved_model_dir --tag_set serve --signature_def serving_default
The given SavedModel SignatureDef contains the following input(s):
inputs['inputs'] tensor_info:
    dtype: DT_STRING
    shape: (-1)
    name: input_example_tensor:0
The given SavedModel SignatureDef contains the following output(s):
outputs['outputs'] tensor_info:
    dtype: DT_FLOAT
    shape: (-1, 1)
    name: dnn/head/logits:0
Method name is: tensorflow/serving/regress```

@nfiedel 

> Figure out how to construct & save a model that takes multiple input tensors.

Do you have any suggestions on how to save the `tf.Estimator` model so that it would take multiple input tensors?

**Comment by sudododo** [comment]
Regression estimators also have the constraint. Since tf.estimator.export provides two ways of exporting a model, build_raw_serving_input_receiver_fn and build_parsing_serving_input_receiver_fn, I would say build_parsing_serving_input_receiver_fn is meant to work with TensorFlow Serving, and build_raw_serving_input_receiver_fn is meant to restore models without help of TensorFlow Serving. I think that's the message that "parsing" and "raw" try to convey. Otherwise how would you restore models without TensorFlow Serving for scoring? Personally I think it's a good feature to add.

**Comment by martinwicke** [comment]
We have removed this restriction. Please check out the code at head, or in the upcoming 1.4 RC. Please reopen if there are issues with it.

**Comment by rutadesai** [comment]
@sudododo -- I am trying to use export_savedmodel() to save a trained DNNLinearCombinedRegressor after training. I do not want to use Tensorflow serving as I have a simple local desktop application. When I use build_parsing_serving_input_receiver_fn(), I am able to export the model using:  servable_model_path = regressor.export_savedmodel(export_dir_base = servable_model_dir, serving_input_fn = export_input_fn, as_text= True). However, when I use the build_raw_serving_input_receiver_fn() (as I should be, since I don't want to use Tensorflow Serving), I get the following error:
`AttributeError: 'FixedLenFeature' object has no attribute 'get_shape'
`
The only thing I did different was creation of export_input_fn. Instead of doing -- 
`export_input_fn = tf.contrib.learn.utils.build_parsing_serving_input_fn(feature_spec)`, I did this:
`export_input_fn = tf.estimator.export.build_raw_serving_input_receiver_fn(feature_spec)`

Here feature_spec is created as follows:
`feature_spec = tf.feature_column.make_parse_example_spec(feature_cols)`

where feature cols are real_valued and embedding columns.

Thanks for your help!

**Comment by sudododo** [comment]
@rutadesai Sorry for the late reply. build_parsing_serving_input_fn and build_raw_serving_input_receiver_fn are expecting different inputs. build_parsing_serving_input_fn expect feature_spec which you could consider as some sort of "data contract" so that TensorFlow serving can translate the request. So what you did is valid for build_parsing_serving_input_fn. However, it you serve the mode locally (without TensorFlow serving), you need to define the input tensor of your graph. Therefore you have to define a placeholder. Actually if you check the input names of two functions, build_parsing_serving_input_fn is "feature_spec" vs "feature" for build_raw_serving_input_receiver_fn.

**Comment by apcode** [comment]
@martinwicke You said this restriction was removed in 1.4 but I still see it.

build_raw_serving_input_receiver_fn is designed to build multiple placeholders for each input (receiving tensors).
ClassificationOutput.as_signature_def still checks for a single receiving tensor.

So to me the restriction is still in place and you can't use ClassificationOutput with build_raw_serving_input_receiver_fn with a saved model.

It seems wrong that these two functions are incompatible.

**Comment by martinwicke** [comment]
ClassificationOutput is a specific to tensorflow/serving. Do not use it. You want to use PredictOutput. 

@davidsoergel, @nfiedel, maybe we should make this much more clear, and maybe even deprecate ClassificationOutput and RegressionOutput?

**Comment by kiminh** [comment]
I use the same code and ` tf 1.4.0` version, get the `save_model.pbtxt`, the stucture of `signature_def` is
```
  signature_def {
    key: "predict"
    value {
      inputs {
        key: "age"
        value {
          name: "age:0"
          dtype: DT_FLOAT
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      inputs {
        key: "capital_gain"
        value {
          name: "capital_gain:0"
          dtype: DT_FLOAT
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      inputs {
        key: "capital_loss"
        value {
          name: "capital_loss:0"
          dtype: DT_FLOAT
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      inputs {
        key: "education"
        value {
          name: "education:0"
          dtype: DT_STRING
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      inputs {
        key: "education_num"
        value {
          name: "education_num:0"
          dtype: DT_FLOAT
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      inputs {
        key: "hours_per_week"
        value {
          name: "hours_per_week:0"
          dtype: DT_FLOAT
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      inputs {
        key: "marital_status"
        value {
          name: "marital_status:0"
          dtype: DT_STRING
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      inputs {
        key: "occupation"
        value {
          name: "occupation:0"
          dtype: DT_STRING
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      inputs {
        key: "relationship"
        value {
          name: "relationship:0"
          dtype: DT_STRING
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      inputs {
        key: "workclass"
        value {
          name: "workclass:0"
          dtype: DT_STRING
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      outputs {
        key: "class_ids"
        value {
          name: "head/predictions/classes:0"
          dtype: DT_INT64
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      outputs {
        key: "classes"
        value {
          name: "head/predictions/str_classes:0"
          dtype: DT_STRING
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      outputs {
        key: "logistic"
        value {
          name: "head/predictions/logistic:0"
          dtype: DT_FLOAT
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      outputs {
        key: "logits"
        value {
          name: "head/predictions/logits:0"
          dtype: DT_FLOAT
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      outputs {
        key: "probabilities"
        value {
          name: "head/predictions/probabilities:0"
          dtype: DT_FLOAT
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 2
            }
          }
        }
      }
      method_name: "tensorflow/serving/predict"
    }
  }
```

I'm working on using Pure Java binding of tensorflow to do prediction.

**Comment by mathlf2015** [comment]
@Ouwen ,I have encountered the same problem, how do you solve this problem , look forward to your reply?
