### ISSUE TITLE
Freeze tensor_forest graph for Android problem

### ISSUE THREAD

**Issue by es007** [tensorflow/tensorflow#12363]
Hi,

I built a aimple Random Forest model in tensorflow, and want to freeze & optimize it for android.
I used the following function for building the tesnor_forest estimator:

      def build_estimator(_model_dir, _num_classes, _num_features, _num_trees, _max_nodes):
      params = tensor_forest.ForestHParams(
      num_classes=_num_classes, num_features=_num_features,
      num_trees=_num_trees, max_nodes=_max_nodes, min_split_samples=3)

    graph_builder_class = tensor_forest.RandomForestGraphs
    return random_forest.TensorForestEstimator(
      params, graph_builder_class=graph_builder_class,
      model_dir=_model_dir)

This function stores the textual model to graph.pbtxt file in the specified model directory.

Then I train it using:

    est = build_estimator(output_model_dir, 3,np.size(features_eval,1), 5,6)
    train_X = features_eval.astype(dtype=np.float32)
    train_Y = labels_y.astype(dtype=np.float32)
    est.fit(x=train_X, y=train_Y, batch_size=np.size(features_eval,0))

(in this simple example: number of trees = 5, max_nodes=6)

Now I want to freeze the model, so I call this function:
`
def save_model_android(model_path):
    checkpoint_state_name = "model.ckpt-1"
    input_graph_name = "graph.pbtxt"
    output_graph_name = "freezed_model.pb"
    checkpoint_path = os.path.join(model_path, checkpoint_state_name)

    input_graph_path = os.path.join(model_path, input_graph_name)
    input_saver_def_path = None
    input_binary = False
    output_node_names = "output"
    restore_op_name = "save/restore_all"
    filename_tensor_name = "save/Const:0"
    output_graph_path = os.path.join(model_path, output_graph_name)
    clear_devices = True

    freeze_graph(input_graph_path, input_saver_def_path,
                              input_binary, checkpoint_path,
                              output_node_names, restore_op_name,
                              filename_tensor_name, output_graph_path,
                              clear_devices, "")
`

and in the freezed_model.pb file generated I get only 1 op which is the output node.
in the console I get the following message when the freeze_graph function is called:

> Converted 0 variables to const ops.
1 ops in the final graph.

Does anyone knows why only one node get exported when calling to freeze_graph?

I'm using Tensorflow version  1.2.1 with cuda support , installed from sources on linux

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
