### ISSUE TITLE
ssd_mobilenets model faild using in android demo

### ISSUE THREAD

**Issue by LiangHao92** [tensorflow/tensorflow#12378]
I am glad to see android demo is updated to be available for ssd_mobilenets models. I tried the demo on my phone, and it works well. But when I tried my own model, the app can not work normally. 
1.I used  `export_inference_graph.py` in object_detection to convert .ckpt to .pb files
2.I replaced the original model by my .pb file
3. Also, I changed the label_list.txt. 
After doing this, I generate the app, but the app crushed. Is there anything wrong with my handle?

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
