### ISSUE TITLE
 Who can explain the usage of this c++ api

### ISSUE THREAD

**Issue by zhouzebiao** [tensorflow/tensorflow#12380]
Who can explain the usage of this api：
Status Run(
  const FeedType & inputs,
  const std::vector< Output > & fetch_outputs,
  const std::vector< Operation > & run_outputs,
  std::vector< Tensor > *outputs
) const 

I read the doc but i still can not understand it ....
I don‘t know  the role of each parameter.

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
