### ISSUE TITLE
using two different models for prediction

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#12382]
Im using the following code to import graph def since i want to use two model files individually.

```
def initialSetup():
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
    start_time = timeit.default_timer()

    # This takes 2-5 seconds to run
    # Unpersists graph from file
    with tf.gfile.FastGFile('age/output_graph.pb', 'rb') as f:
        age_graph_def = tf.GraphDef()
        age_graph_def.ParseFromString(f.read())
        tf.import_graph_def(age_graph_def, name='')

    with tf.gfile.FastGFile('output_graph.pb', 'rb') as f:
        gender_graph_def = tf.GraphDef()
        gender_graph_def.ParseFromString(f.read())
        tf.import_graph_def(gender_graph_def, name='')

    print ('Took {} seconds to unpersist the graph'.format(timeit.default_timer() - start_time))

```

but how do I use them after importing individually ? I tried adding name ='age' and name = 'gender' to differentiate but it is not working out as well.

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Zumbalamambo** [comment]
@reedwm I have asked but no one is responding. Can you please check [this](https://stackoverflow.com/questions/45747769/using-two-different-models-in-tensorflow)
