### ISSUE TITLE
Slim.learning.train support tf-debug

### ISSUE THREAD

**Issue by irmowan** [tensorflow/tensorflow#12385]
tfdbg is a great tool for debugging TensorFlow programs. But if I use slim for training(like in TensorFlow object detection API), it seems not support to use tf-dbg, and brings inconvenience.

**Comment by caisq** [comment]
cc @sguada

One way I can see we solve this problem is by adding a keyword argument, maybe called `tf_debug` or `debug` to the `slim.learning.train()` method. @sguada, please let me know what you think. Thanks.

**Comment by sguada** [comment]
I haven't use tf-dgb myself, but if the change is minor and defaults to False it should be ok.
