### ISSUE TITLE
Why my tensorflow-gpu runs only on cpu? Ubuntu

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#12388]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from **: `pip3 install tensorflow-gpu`
- **TensorFlow version**: ('v1.1.0-rc0-61-g1ec6ed5', '1.1.0')
- **Python version**:  Python 3.5.2
- **CUDA/cuDNN version**: Cuda compilation tools, release 8.0, V8.0.61

My tensorflow-gpu runs only on cpu, how to fix it?
I've already tried to set 
`CUDA_DEVICE_VISIBLE=all my gpus`  But it didn't work.

Then I tried to use this code:
`sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))`
The output is following:
`Device mapping: no known devices.`
`2017-08-18 16:44:44.654177: I tensorflow/core/common_runtime/direct_session.cc:300] Device mapping:`
Then nothing. It doesn't output the map.
I've also tried to install it with virtualenv and run the program in virtualenv or reinstall, still not working. 
Why is this happening? How can I fix it?

**Comment by ArturoDeza** [comment]
It is possible that you haven't installed the CUDA driver properly.

What is the output of:
`$nvcc -V`
and 
`$nvidia-smi`

Go to your CUDA Samples folder and run the ./deviceQuery script to check if your system is finding your graphics card.

**Comment by mykalu** [comment]
I've noticed that using `pip install tensorflow-gpu` also installs `tensorflow` as a dependency, but `pip install tensorflow-gpu==1.2.1` does not demonstrate this behavior. Is this an issue with the 1.3 rollout?

**Comment by ArturoDeza** [comment]
Something also to check: install Tensorflow from source (with Bazel). That's what I did, and it started running processes on GPU.

**Comment by DNXie** [comment]
@ArturoDeza 
The output of `$nvcc -V`:
`nvcc: NVIDIA (R) Cuda compiler driver`
`Copyright (c) 2005-2016 NVIDIA Corporation`
`Built on Tue_Jan_10_13:22:03_CST_2017`
`Cuda compilation tools, release 8.0, V8.0.61`

The output of `nvidia-smi`:
`| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:04:00.0     Off |                  N/A |
|  0%   24C    P8    11W / 180W |    113MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 0000:05:00.0     Off |                  N/A |
|  0%   25C    P8     6W / 180W |      2MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1080    Off  | 0000:08:00.0     Off |                  N/A |
|  0%   26C    P8     6W / 180W |      2MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 1080    Off  | 0000:09:00.0     Off |                  N/A |
|  0%   26C    P8     6W / 180W |      2MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 1080    Off  | 0000:85:00.0     Off |                  N/A |
|  0%   24C    P8     6W / 180W |      2MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 1080    Off  | 0000:86:00.0     Off |                  N/A |
|  0%   28C    P8     6W / 180W |      2MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 1080    Off  | 0000:89:00.0     Off |                  N/A |
|  0%   26C    P8     6W / 180W |      2MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 1080    Off  | 0000:8A:00.0     Off |                  N/A |
|  0%   27C    P8     6W / 180W |      2MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
`

**Comment by DNXie** [comment]
@mykalu 
Oh my god! It works! Tensorflow runs on gpus.
Thank you very much.
Is there something wrong with the latest tensorflow version?

**Comment by himkt** [comment]
I have encountered the same problem.
As mykalu-san said, my 'pip install tensorflow-gpu' also installed tensorflow.

**Comment by vell001** [comment]
same problem to me, I am using tensorflow(1.3.0)

**Comment by DNXie** [comment]
@vell001 
try to use this
`pip install tensorflow-gpu==1.2.1`

**Comment by skyoung** [comment]
Just as @mykalu said, it's really confusing that `pip3 install tensorflow-gpu` also install `tensorflow`. And it seems that this makes gpu version not work.

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by srowen** [comment]
@DNXie @skyoung @mykalu I had the same problem, but then found that I had `tensorflow-tensorboard` 0.1.4 installed which depends on `tensorflow`. That seemed to be the source of the erroneous dependency, and updating it to 0.1.5 made it all work for me because `tensorflow` wasn't installed anymore.

**Comment by mykalu** [comment]
@srowen Nice catch, that worked for me. Thanks!

**Comment by DNXie** [comment]
@srowen 
That's true. I have tensorboard on that version too. Thank you!

**Comment by SimonWalsh1000** [comment]
@mykalu when I run `pip install tensorflow-gpu==1.3.0` I also have a folder called tensorflow. Is this correct? I am having the same issue - my GPU is not being utilized.

**Comment by Inchini** [comment]
uninstalling tensorflow-gpu==1.3.0 and installing tensorflow-gpu==1.2.1 worked for me! thanks

**Comment by EddieOne** [comment]
So how about tf 1.4 with gpu? 😸

**Comment by jiforcen** [comment]
For me tf 1.4.1 works properly.

**Comment by caiosuzuki** [comment]
@jiforcen Could you tell me which method you used to install the CUDA toolkit, CuDNN and TensorFlow(GPU)? I've been trying several methods for days now and I just can't make tensorflow detect my GPU.

**Comment by jiforcen** [comment]
@caiosuzuki  I've followed the nvidia guide. [http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#introduction](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#introduction)
Don't forget to setup the environment variables!! [http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#post-installation-actions](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#post-installation-actions)
Check that your nvidia driver is configured and cuda toolkit is installed properly.
After that I've installed tensorflow gpu in a conda environment. I've problems with tensorflow gpu 1.3 but tensorflow gpu 1.4 works fine for me.

**Comment by shayan09** [comment]
My code was running on the CPU, so I changed tensorflow-gpu from version 1.4.1 to 1.2.1 and now it shows me the following error. Please help me out here.
----------------------------------------------------------------------------------------------------------------
Using TensorFlow backend.
Traceback (most recent call last):
  File "extract_features.py", line 16, in <module>
    from data import DataSet
  File "/home/shayan/five-video-classification-methods/data.py", line 12, in <module>
    from processor import process_image
  File "/home/shayan/five-video-classification-methods/processor.py", line 4, in <module>
    from keras.preprocessing.image import img_to_array, load_img
  File "/usr/local/lib/python2.7/dist-packages/keras/__init__.py", line 3, in <module>
    from . import activations
  File "/usr/local/lib/python2.7/dist-packages/keras/activations.py", line 3, in <module>
    from . import backend as K
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/__init__.py", line 64, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by zhanshi17** [comment]
@shayan09 Have you fixed this problem? I have got into the same situation with you.

**Comment by JennyyiqiWang** [comment]
@shayan09 Have you fixed the problem? I have got into the same trouble.

**Comment by shayan09** [comment]
The current version of CUDA is not supported by tensorflow. So just downgrade your CUDA version to 7.0 and then reinstall the normal tensorflow and then tensorflow-gpu. Worked for me.

**Comment by ironfroggy** [comment]
Having the same trouble and none of the advice works. Can't downgrade CUDA, tensorflow-gpu package looks for 9.0 DLLs explicitly. I can watch my CPU/GPU usage while its running and TF *says* its running through the GPU, but the CPU is pegged at 100% and the GPU usage hovers around 5%. I tried adjusting the batch size as high as I can get it without hitting OOM errors, but it seemed to make no difference. (elsewhere I read small batch sizes might make the GPU throughput suffer).

Are there known current issues with the windows binaries for the Tensorflow1.5.0/CUDA 9.0/cuDNN 7.0 combination? If there are known issues, is there a previous combination that might work? If there are other steps that might be overlooked to run on the GPU, are there guides for common missteps?

**Comment by hyperh** [comment]
Having similar problems as @ironfroggy

**Comment by VanitarNordic** [comment]
I have the same problem with Tensorflow 1.5 and Cuda 9.0 :-(

**Comment by VanitarNordic** [comment]
@ironfroggy 

I have the same problem as yours. Could you find a solution?

**Comment by adriancar** [comment]
@ironfroggy
@hyperh
@VanitarNordic

Likewise, same problem. tensorflow-gpu==1.5.0/Cuda9.0/cuDNN7.0/windows 7. 
I'll add that when I first encountered the problem I was getting an error importing tensorflow stating that it couldn't find cudart64_90.dll (it was in my path). After I restarted my computer, tensorflow successfully imported, but it just uses cpu.

**Comment by Euphemiasama** [comment]
I encountered the same problem. 
For me a simple reboot of the system did the trick, my tensorflow is running on GPU
`reboot`

**Comment by leomrocha** [comment]
Same issue with Tensorflow 1.8.0 and Cuda 8.0

**Comment by mmawada** [comment]
I have busted my head and eyes last few days to figure out why TF 1.8 is not running on gpu with cuda 9.2 installation and still have no answer  but close so I want to share my experience in case anyone have solved the problem.  I installed from scratch cuda 9.2 with cudnn 7.14 and ncc2.2.13 per nvidia website then installed TF from the source via bazel all were successful as I ran a toy code Hello and worked but when I checked devices it was only CPU and not GPU which was a disappointment.  Then per nvidia suggestion I downloaded the coda 9.2 samples and compiled and ran. /deviceQuery and I got the table which declares that cuda 9.2 and cunn 7.14 are configured correctly as it shows the GPU device and its compatibility with the runtime of Ubuntu software and finally s pass on the test!  So I don't know why on earth I cannot get TF 1.8 run on GPU.  This leaves me with suspiciousion that there is an incompatibility here between TF 1.8 gpu and cuda 9.2 that tensorflow website is not telling us.   I hope I am wrong and there is something I am missing to get gpu working. Let me know if anyone has ideas or suggestions.  Thank you

**Comment by erobic** [comment]
FYI, it works for me with CUDA 9.0 and tensorflow 1.8.0, when I install `tensorflow` and `tensorflow-gpu` separately:
```
pip uninstall tensorflow
pip uninstall tensorflow-gpu
pip install tensorflow==1.8.0
pip install tensorflow-gpu==1.8.0
```

**Comment by flynuxs** [comment]
@erobic thank you! that work for me

**Comment by jameswan** [comment]
I had the same problem where only the CPU was used. You need to uninstall tensorflow, and only have tensorflow-gpu installed

**Comment by vinitmuchhala** [comment]
@mmawada Try this link, it worked for me - TF==1.8, Cuda 9.2
https://www.pytorials.com/how-to-install-tensorflow-gpu-with-cuda-9-2-for-python-on-ubuntu/

**Comment by holianh** [comment]
Thank you!
```
conda create -n tt  anaconda python
source activate tt

conda install tensorflow-gpu==1.11 cudatoolkit==9.0 cudnn==7.1.2 h5py
pip install pillow h5py keras
pip uninstall tensorflow
pip install tensorflow-gpu

git clone https://github.com/fchollet/keras.git
cd keras/examples
python mnist_cnn.py
```

it worked for me!!!
tuananhktmt

**Comment by SystemErrorWang** [comment]
same problem here. I use ubuntu 16.4, tensorflow 1.12.0, gtx 1080 and cuda 9.0 with cudnn7.3.1.
My network was training normally when I went back home last friday. But in monday morning I found it unable to run evaluation on gpu, even if I set "with tf.device('/device:GPU:0')". I tried "nvidia-smi" in terminal, there is no problem with my gpu and driver

**Comment by holianh** [comment]
> same problem here. I use ubuntu 16.4, tensorflow 1.12.0, gtx 1080 and cuda 9.0 with cudnn7.3.1.
> My network was training normally when I went back home last friday. But in monday morning I found it unable to run evaluation on gpu, even if I set "with tf.device('/device:GPU:0')". I tried "nvidia-smi" in terminal, there is no problem with my gpu and driver

Mee too, just reinstall ubuntu :))

**Comment by RubensZimbres** [comment]
This solved for me, while training a Transformer Translation Model:

`pip install tf-nightly-gpu`

**Comment by emremrah** [comment]
> FYI, it works for me with CUDA 9.0 and tensorflow 1.8.0, when I install `tensorflow` and `tensorflow-gpu` separately:
> 
> ```
> pip uninstall tensorflow
> pip uninstall tensorflow-gpu
> pip install tensorflow==1.8.0
> pip install tensorflow-gpu==1.8.0
> ```

Do you guys think using cache would be a problem? Do I need use `--no_cache` option?

**Comment by AliRashidnejad** [comment]
hey guys it worked for me with tensorflow 2.0+ with: 
export CUDA_VISIBLE_DEVICES='0'

if you have more GPUs you need to set '0','1', etc

**Comment by nadechka** [comment]
Hi, guys! I have same problem. My OS is 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
I have this driver:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
I have this packages:
tb-nightly              2.3.0a20200615     
tensorboard             2.2.2              
tensorboard-plugin-wit  1.6.0.post3        
tensorflow              2.2.0              
tensorflow-estimator    2.2.0       
Why I can not use GPU in processing?       
tensorflow-gpu          2.2.0
