### ISSUE TITLE
Does StreamExecutor support OpenCL?

### ISSUE THREAD

**Issue by rlegithub** [tensorflow/tensorflow#12395]
I only see TENSORFLOW_STREAM_EXECUTOR_MACHINE_MANAGER_PREFER_OPENCL option in machine_manager.cc. However I don't see where SE links to OpenCL headers and libs. So I wonder of SE supports OpenCL?

Thanks,
RLE

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
