### ISSUE TITLE
tools/jdk: BUILD file not found on package path.

### ISSUE THREAD

**Issue by titubeta** [tensorflow/tensorflow#124]
While installing from source, I got this error

`ERROR: Loading of target '//tools/jdk:SingleJar_deploy.jar' failed; build aborted: no such package 'tools/jdk': BUILD file not found on package path.`
`ERROR: Loading failed; build aborted`

I already installed java8 as per bazel's instruction page.

**Comment by tarali** [comment]
Having the same issue. Not resolved yet. Please help.

**Comment by ebrevdo** [comment]
What version of bazel are you using?

**Comment by tarali** [comment]
Blaze version info: Build label: 0.1.0
Is this the right version?

**Comment by vrv** [comment]
Try using 0.1.1 -- our bazel install instructions have been updated here: http://www.tensorflow.org/get_started/os_setup.html#installation-for-linux

**Comment by mjpost** [comment]
Hi,

I have this same problem trying to install Tensor Flow from source on a CentOS 6.7 machine. I've tried with both bazel 0.1.1 and 0.1.3. With 0.1.1, I get:

    $ pwd
    $HOME/code/tensorflow
    $ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures --ignore_unsupported_sandboxing
    WARNING: Output base '$HOME/.cache/bazel/_bazel_mpost/891d341da8754b366638c3a40c9b09f5' is on NFS. This may lead to surprising failures and undetermined behavior.
    ERROR: Loading of target '//tools/jdk:GenClass_deploy.jar' failed; build aborted: no such target '//tools/jdk:GenClass_deploy.jar': target 'GenClass_deploy.jar' not declared in package 'tools/jdk' defined by $HOME/.bazel/base_workspace/tools/jdk/BUILD.
    ERROR: Loading failed; build aborted.
    INFO: Elapsed time: 0.034s

The documentation doesn't seem to address this. Do you have any suggestions?

**Comment by vogechri** [comment]
Same issue as mjpost here.

**Comment by mjpost** [comment]
Update: I think this occurred because we did not have a complete build of bazel. We switched to a CentOS 7.1 machine, and everything (both bazel and TF) built fine.

**Comment by zyzhang1992** [comment]
Hello, 

I have a similar problem when testing bazel with "bazel test": 

ERROR: /share/sw/free/zyzhang/bazel.Feb04/bazel-0.1.4.Feb012016/tools/defaults/BUILD:13:1: no such target '@bazel_tools//tools/jdk:GenClass_deploy.jar': target 'GenClass_deploy.jar' not declared in package 'tools/jdk' defined by /home/zyzhang/.cache/bazel/_bazel_zyzhang/3ac78c7468df3709b4ef704638238acf/external/bazel_tools/tools/jdk/BUILD and referenced by '//tools/defaults:genclass'.

To begin with, how do I make sure the bazel build was "complete", as mjpost encountered? What could I be missing in the bazel build? The bazel build was successful and I am doing "bazel test" with the bazel built from "bazel build"
