### ISSUE TITLE
InvalidArgument error with tf.scan()

### ISSUE THREAD

**Issue by danakianfar** [tensorflow/tensorflow#12403]
### System information
- No custom code
- Error encountered on Windows 10 and CentOS 6.7
- binary
- TF 1.1.0 and 1.2.1 respectively
- 3.6
- CUDA 8.0, CUDNN 5.1
- GeForce 940MX 2GB (ran out of memory in execution), Titan X 12 GB

### Describe the problem
I encountered this error when using `tf.scan` on an MultiRNNCell.

> InvalidArgumentError (see above for traceback): Max scatter index must be <= array size (141 vs. 141)

### Source code / logs
If you look here: **[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/tensor_array_ops.cc#L1072](url)**

``` 
OP_REQUIRES(
          ctx, max_index < array_size,
          errors::InvalidArgument("Max scatter index must be <= array size (",
                                  max_index, " vs. ", array_size, ")"));
    }
````

It seems that the condition (<) is not consistent with the error message (<=).

**Comment by danakianfar** [comment]
I think that this is just a matter of fixing the error message. The error condition seems just to be checking for correct indexing.

**Comment by AswinBlue** [comment]
The code's hyperlink address was moved to here
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/tensor_array_ops.cc#L1072

**Comment by yongtang** [comment]
Yes I think the error message should be fixed as index is 0-based. PR #12800.
