### ISSUE TITLE
Mac PIP 0.7.1 breaks protobuf installation

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#1242]
I just upgraded to the latest 0.7.1 on Mac OSX using the PIP package, and I can no longer run TF. When importing in Python 2.7 it reports that protobuf cannot be found, even though during the pip install it supposedly upgraded protobuf to 3.0.0b2.

**Comment by alquraishi** [comment]
Some finagling and reinstalling (of both protobuf and tensorflow) seems to have done the trick.

**Comment by vrv** [comment]
Yes, earlier wheels were doing bad things to the protobuf installation, and the only way to recover is to uninstall to 'start from scratch.'

**Comment by alquraishi** [comment]
Maybe worth noting this in the installation instructions so that people uninstall protobuf.
