### ISSUE TITLE
Feature: TF on mix environnment CPU-GPU

### ISSUE THREAD

**Issue by arita37** [tensorflow/tensorflow#12425]
When using TF-GPU, either switches to GPU depending on GPU availability.

When we have a mixed environnment,
CPU +GPU, it would be better to distribute across CPU and GPU available,
specify the core available to TF for full usage (keeping one for centralized processing).

**Comment by chhwang** [comment]
If what I understand is right, this requested feature is already implemented in TensorFlow. GPU version of TensorFlow always assume the "mixed environment of CPU and GPUs", and it is very natural because GPU-only environment doesn't exists.

**Comment by arita37** [comment]
Yes, it seems not using available CPU when GPU is present.
Do we need to explicitely write distributed code like this ?

for i in range(num_cpus):
     with tf.device('/cpu:'+str(i)):
         outputs.append(tf.matmul(inputs[i], b))





Changho Hwang wrote:

**Comment by chhwang** [comment]
TensorFlow uses every available CPUs as if they are unified all together as single CPU, which means that there is no such device like `'/cpu:1'` or `'/cpu:2'`, only `'/cpu:0'`is legal. You cannot distinguish each CPU over TensorFlow as far as I know, and maybe, you don't need to in most cases. You can just write:
``` python
with tf.device('/cpu:0'):
    for i in range(num_cpus):
        outputs.append(tf.matmul(inputs[i], b))
```
then it will use all available CPUs automatically.

**Comment by arita37** [comment]
Even this is GPU (TF GPu) is available,
CPU will be used ?

In my case, only GPU seems being used for training.....





On 20 Aug 2017, at 23:58, Changho Hwang <notifications@github.com> wrote:

TensorFlow uses every available CPUs as if they are unified all together as single CPU, which means that there is no such device like '/cpu:1' or '/cpu:2', only '/cpu:0'is legal. You cannot distinguish each CPU over TensorFlow as far as I know, and maybe, you don't need to in most cases. You can just write:

with tf.device('/cpu:0'):
    for i in range(num_cpus):
        outputs.append(tf.matmul(inputs[i], b))
then it will use all available CPUs automatically.

―

**Comment by chhwang** [comment]
Yes, you can always use your CPUs with any version of TensorFlow. It may be much helpful for you to ask in [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) tagging `tensorflow` for further issues.

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
