### ISSUE TITLE
ValueError: No attr named '_XlaCompile' and AttributeError: 'NoneType' object has no attribute 'back_prop' with tf.while_loop and templates

### ISSUE THREAD

**Issue by 3rd3** [tensorflow/tensorflow#12420]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow version (use command below)**: 1.2, 1.3
- **Python version**: 3.4
- **CUDA/cuDNN version**: 5, 6
- **GPU model and memory**: GTX 1080 Ti

### Describe the problem

When I run `tf.train.Optimizer().minimize(loss)` I receive the error message below. The code is a bit unwieldy, so I just provide the overall structure of my code:

```
x = { ... }
def some_template(..):
  bar(x[..])
def foo(..):
  return foobar(x[..])
template = tf.make_template("my_template", some_template)
def loop_body(inputs, ..):
  for i in range(x[..]):
    net = foo(inputs)
    net = template(net)
  return inputs, ..
net, *_ = tf.while_loop(cond, loop_body, vars)
```

The functions and templates that are called in the loop body access some Python variables from the outer scope (read-only, i.e. without side-effects), and they are, of course, expected to be constant at run-time. The graph construction seems to work perfectly fine. Only when I construct the first minimization operation, it fails at the first graph node that makes use of a variable (`Model/ModuleB_0/b_46/` in this case). One thing that might be unusual about my graph is that it uses an earlier part of the graph as target for the outputs, so the loss is defined as a function of `output_node` and `tf.stop_gradient(earlier_node)`. What might maybe also be interesting is that the `frame_name` below contains the same path concatenated twice `Model/ModuleB_0/while/Model/ModuleB_0/while/`. I also have some `trainable=True` variables which are not in the subgraph of the training op, but they are not in the `var_list` argument for the training op, so that should be fine. Is this a bug or am I doing something wrong?

### Source code / logs
```
Traceback (most recent call last):
  File "/media/other_dir/me/venv3/lib/python3.4/site-packages/tensorflow/python/ops/gradients_impl.
y", line 343, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "/media/other_dir/me/venv3/lib/python3.4/site-packages/tensorflow/python/framework/ops.py",
ine 1705, in get_attr
    str(self._node_def))
ValueError: No attr named '_XlaCompile' in name: "Model/ModuleB_0/while/Level_4/BottomRight/Conv2D
ayer_2/BiasAdd/Enter"
op: "Enter"
input: "Model/ModuleB_0/b_46/read"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "frame_name"
  value {
    s: "Model/ModuleB_0/while/Model/ModuleB_0/while/"
  }
}
attr {
  key: "is_constant"
  value {
    b: true
  }
}
attr {
  key: "parallel_iterations"
  value {
    i: 10
  }
}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 98, in <module>
    tf.app.run()
  File "/media/other_dir/me/venv3/lib/python3.4/site-packages/tensorflow/python/platform/app.py", li
ne 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 61, in main
    model = Model(tf.flags.FLAGS.__flags)
  File "/media/other_dir/me/Code/model/model.py", line 193, in __init__
    scope="Model/ModuleA_%i" % i)
  File "/media/other_dir/me/venv3/lib/python3.4/site-packages/tensorflow/python/training/optimizer.p
y", line 315, in minimize
    grad_loss=grad_loss)
  File "/media/other_dir/me/venv3/lib/python3.4/site-packages/tensorflow/python/training/optimizer.p
y", line 386, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/media/other_dir/me/venv3/lib/python3.4/site-packages/tensorflow/python/ops/gradients_impl.p
y", line 542, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/media/other_dir/me/venv3/lib/python3.4/site-packages/tensorflow/python/ops/gradients_impl.p
y", line 348, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/media/other_dir/me/venv3/lib/python3.4/site-packages/tensorflow/python/ops/gradients_impl.p
y", line 542, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/media/other_dir/me/venv3/lib/python3.4/site-packages/tensorflow/python/ops/control_flow_gra
d.py", line 208, in _EnterGrad
    if not grad_ctxt.back_prop:
AttributeError: 'NoneType' object has no attribute 'back_prop'

```

**Comment by carlthome** [comment]
Does it work without XLA?

**Comment by 3rd3** [comment]
XLA JIT is disabled by default, right? I did not enable it. To be sure I set `sess_config.graph_options.optimizer_options.global_jit_level = tf.OptimizerOptions.OFF`, but the error still occurs.

**Comment by 3rd3** [comment]
It seems the problem was that I defined several losses within the loop body of a while loop and added them to `tf.GraphKeys.LOSSES` collection. I did not realize at that point that `tf.add_to_collection` is not a dynamic graph operation. It is not even a graph operation after all.

**Comment by carlthome** [comment]
Aha! Yeah, changing the graph during execution should be avoided, I believe. Good thing you solved it. :+1: 

Don't forget to close the issue.

**Comment by JoeHRIsaac** [comment]
Excuse me but please explain the changing graph? I have the same error.
What you mean by changing the graph during execution?
