### ISSUE TITLE
can i used it by C#?

### ISSUE THREAD

**Issue by leehavin** [tensorflow/tensorflow#12423]
can i used it by C#?
What time can provide C # version？
Why isn't the official c # demo?
thanks

**Comment by asimshankar** [comment]
The TensorFlow project owners maintain language bindings in a few languages, C# is not one of them (see https://www.tensorflow.org/api_docs/). However, we do encourage the community to build and maintain bindings for other languages. You may find https://github.com/migueldeicaza/TensorFlowSharp to be of interest.

**Comment by leehavin** [comment]
@asimshankar Why is there no c # version?It is difficult to?

**Comment by asimshankar** [comment]
As you can imagine, we don't have enough cycles to do all that we'd like to. So we try to provide enough that can be extended by others in the community and appreciate efforts like TensorFlowSharp.

**Comment by leehavin** [comment]
@asimshankar I hope to support the c # version, after all, the usage rate is very high, and I hope that the team of tensorflow should not reject c #. Thank you
