### ISSUE TITLE
zeros_like doesn't fully respect the optimize argument

### ISSUE THREAD

**Issue by EFanZh** [tensorflow/tensorflow#12436]
[The definition of `zeros_like`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py#L1463) is:

```python
def zeros_like(tensor, dtype=None, name=None, optimize=True):
  with ops.name_scope(name, "zeros_like", [tensor]) as name:
    tensor = ops.convert_to_tensor(tensor, name="tensor")

    if tensor.shape.is_fully_defined():
      # We can produce a zeros tensor independent of the value of 'tensor',
      # since the shape is known statically.
      return zeros(tensor.shape, dtype=dtype or tensor.dtype, name=name)

    if dtype is not None and dtype != tensor.dtype:
      return zeros(
          shape_internal(tensor, optimize=optimize), dtype=dtype, name=name)
    else:
      return gen_array_ops._zeros_like(tensor, name=name)
```

We can see that if the shape of `tensor` is already known, the `optimize` parameter is ignored, which is inconsistent with the [documented behavior](https://www.tensorflow.org/api_docs/python/tf/zeros_like).

**Comment by yongtang** [comment]
I think `optimize` flag should be respected. Added a PR #12459 for it.

**Comment by ali01** [comment]
@benoitsteiner, could you please update this issue upon concluding review of #12459? Thanks
