### ISSUE TITLE
Train Multibox object detector included in the TF Detect Android demo

### ISSUE THREAD

**Issue by VajiraPrabuddhaka** [tensorflow/tensorflow#12439]
Can anyone guide me how to train our own multibox_model.pb included in the tensorflow android example??

**Comment by andrewharp** [comment]
@VajiraPrabuddhaka multibox_model.pb is deprecated, we now suggest using ssd mobilenet which is the current default in the TF Detect demo. This model may be trained using the [TF Object Detection API](https://github.com/tensorflow/models/tree/master/object_detection).

Closing as this is neither a bug nor feature request. For further assistance please see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) where there's a larger support community.

**Comment by syslogic** [comment]
TF Object Detection API is meanwhile located at
https://github.com/tensorflow/models/tree/master/research/object_detection
