### ISSUE TITLE
[android demo] UnsatisfiedLinkError exception on app start if build with nativeBuildSystem = 'none'

### ISSUE THREAD

**Issue by ArtsiomCh** [tensorflow/tensorflow#12431]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
app build at Android Studio 2.3.3 on Linux Ubuntu 16.04
app tested on Meizu M2 Note (Android 5.1, API 22) 
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
Master branch from GitHub
- **Python version**: 
2.7 (not used in that case)
- **Bazel version (if compiling from source)**:
0.5.3 (not used in that case) 
- **CUDA/cuDNN version**:
none
- **GPU model and memory**:
none
- **Exact command to reproduce**:
Android Studio/Run (build.gradle)

### Describe the problem
With `nativeBuildSystem = 'none'` app exit with UnsatisfiedLinkError exception (see log below).
Quick investigation shows call of `env.ImageUtils.convertYUV420SPToARGB8888(Native Method)` native method from `CameraActivity.onPreviewFrame(CameraActivity.java:113)`. 
`convertYUV420SPToARGB8888` suppose to be implemented in `libtensorflow_demo.so` wich is not created in case of `nativeBuildSystem = 'none'`. (With `nativeBuildSystem = 'cmake'` `libtensorflow_demo.so` created and `convertYUV420SPToARGB8888` works fine)
Quick fix may be obtained by including `libtensorflow_demo.so` into JCenter and download it like the TensorFlow Inference Interface package.
Another solution would be Java implementation of `convertYUV420SPToARGB8888`, the same as it been done for `convertYUV420ToARGB8888` in commit #003deb8 at PR #10771 "Refactor and implementation of the camera API 1, it fixes #8736 #10771".
I start working with that Java implementation of `convertYUV420SPToARGB8888` but I don't think I have enough skills to make it. At the moment I create Java wrapper for native convertYUV420SPToARGB8888 and make all native methods `private` to isolate the rest of the Java code from occasional use them:
[https://github.com/ArtsiomCh/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java](url)
[https://github.com/ArtsiomCh/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/env/ImageUtils.java](url)
Would be great if @osdamv (creator of Java implementation of `convertYUV420ToARGB8888`) can help in porting Java implementation of `convertYUV420ToARGB8888` for `convertYUV420SPToARGB8888`

### Source code / logs
08-20 13:28:38.212 19058-19058/? I/TensorFlowInferenceInterface: Model load took 1303ms, TensorFlow version: 1.2.0
08-20 13:28:38.217 19058-19058/? I/TensorFlowInferenceInterface: Successfully loaded model from 'file:///android_asset/tensorflow_inception_graph.pb'
08-20 13:28:38.219 19058-19058/? I/TensorFlowImageClassifier: Read 1001 labels, output layer size is 1008
08-20 13:28:38.219 19058-19058/? I/tensorflow: ClassifierActivity: Sensor orientation: 90, Screen orientation: 0
08-20 13:28:38.219 19058-19058/? I/tensorflow: ClassifierActivity: Initializing at size 640x480
08-20 13:28:38.223 19058-19058/? W/tensorflow: ImageUtils: Native library not found, native RGB -> YUV conversion may be unavailable.
08-20 13:28:38.225 19058-19058/? E/art: No implementation found for void org.tensorflow.demo.env.ImageUtils.convertYUV420SPToARGB8888(byte[], int[], int, int, boolean) (tried Java_org_tensorflow_demo_env_ImageUtils_convertYUV420SPToARGB8888 and Java_org_tensorflow_demo_env_ImageUtils_convertYUV420SPToARGB8888___3B_3IIIZ)
08-20 13:28:38.226 19058-19058/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.tensorflow.demo, PID: 19058
                                                   java.lang.UnsatisfiedLinkError: No implementation found for void org.tensorflow.demo.env.ImageUtils.convertYUV420SPToARGB8888(byte[], int[], int, int, boolean) (tried Java_org_tensorflow_demo_env_ImageUtils_convertYUV420SPToARGB8888 and Java_org_tensorflow_demo_env_ImageUtils_convertYUV420SPToARGB8888___3B_3IIIZ)
                                                       at org.tensorflow.demo.env.ImageUtils.convertYUV420SPToARGB8888(Native Method)
                                                       at org.tensorflow.demo.CameraActivity.onPreviewFrame(CameraActivity.java:113)
                                                       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1288)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5877)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
08-20 13:28:38.265 19058-19058/? I/Process: Sending signal. PID: 19058 SIG: 9

**Comment by andydavis1** [comment]
@andrewharp @petewarden Can either of you take a look?

**Comment by andrewharp** [comment]
@ArtsiomCh The missing conversion does need to be remedied, but in the meantime as a workaround you could try overriding CameraActivity.useCamera2API = true. This will force it to use the camera2 API, which we may be too aggressive in disabling in some cases.

**Comment by rsd-raul** [comment]
@andrewharp Overriding useCamera2API works for TF Classify, sadly it doesn't for TF Detect or TF Stylize, at least the errors are different, I'm assuming they are related to the 'nativeBuildSystem' as well as I get an error log about before the problem, maybe @ArtsiomCh can confirm that.

TF Detect Log:

```
...
08-23 17:28:24.072 1250-1293/org.tensorflow.demo D/tensorflow: CameraActivity: Initializing buffer 2 at size 153599
08-23 17:28:24.074 1250-1293/org.tensorflow.demo E/tensorflow: ObjectTracker: libtensorflow_demo.so not found, tracking unavailable
08-23 17:28:24.074 1250-1293/org.tensorflow.demo I/tensorflow: MultiBoxTracker: Initializing ObjectTracker: 640x480
08-23 17:28:24.077 1250-1293/org.tensorflow.demo E/tensorflow: ObjectTracker: Native object tracking support not found. See tensorflow/examples/android/README.md for details.
08-23 17:28:24.101 1250-1293/org.tensorflow.demo E/tensorflow: MultiBoxTracker: Object tracking support not found. See tensorflow/examples/android/README.md for details.
08-23 17:28:24.102 1250-1293/org.tensorflow.demo E/art: No implementation found for void org.tensorflow.demo.env.ImageUtils.convertYUV420ToARGB8888(byte[], byte[], byte[], int[], int, int, int, int, int, boolean) (tried Java_org_tensorflow_demo_env_ImageUtils_convertYUV420ToARGB8888 and Java_org_tensorflow_demo_env_ImageUtils_convertYUV420ToARGB8888___3B_3B_3B_3IIIIIIZ)
08-23 17:28:24.102 1250-1293/org.tensorflow.demo W/tensorflow: ImageUtils: Native YUV -> RGB implementation not found, falling back to Java implementation
08-23 17:28:24.419 1250-1294/org.tensorflow.demo V/RenderScript: 0x55a129a360 Launching thread(s), CPUs 6
08-23 17:28:24.684 1250-1292/org.tensorflow.demo E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[image_tensor], outputs:[detection_boxes, detection_scores, detection_classes, num_detections]
                                                                                 
                                                                                 --------- beginning of crash
08-23 17:28:24.685 1250-1292/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: inference
                                                                   Process: org.tensorflow.demo, PID: 1250
                                                                   java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'Switch' with these attrs.  Registered devices: [CPU], Registered kernels:
                                                                     device='CPU'; T in [DT_FLOAT]
                                                                     device='CPU'; T in [DT_INT32]
                                                                     device='GPU'; T in [DT_STRING]
                                                                     device='GPU'; T in [DT_BOOL]
                                                                     device='GPU'; T in [DT_INT32]
                                                                     device='GPU'; T in [DT_FLOAT]
                                                                   
                                                                   	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Switch = Switch[T=DT_BOOL](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Greater, Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Greater)]]
                                                                       at org.tensorflow.Session.run(Native Method)
                                                                       at org.tensorflow.Session.access$100(Session.java:48)
                                                                       at org.tensorflow.Session$Runner.runHelper(Session.java:295)
                                                                       at org.tensorflow.Session$Runner.run(Session.java:245)
                                                                       at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:142)
                                                                       at org.tensorflow.demo.TensorFlowObjectDetectionAPIModel.recognizeImage(TensorFlowObjectDetectionAPIModel.java:158)
                                                                       at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:340)
                                                                       at android.os.Handler.handleCallback(Handler.java:742)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
08-23 17:28:24.689 1250-1292/org.tensorflow.demo E/MQSEventManagerDelegate: failed to get MQSService.
...
```

TF Stylize Log:
```
...
08-23 17:31:24.363 3146-3187/org.tensorflow.demo D/tensorflow: CameraActivity: Initializing buffer 1 at size 460799
08-23 17:31:24.365 3146-3187/org.tensorflow.demo D/tensorflow: CameraActivity: Initializing buffer 2 at size 460799
08-23 17:31:24.369 3146-3187/org.tensorflow.demo W/tensorflow: ImageUtils: Native library not found, native RGB -> YUV conversion may be unavailable.
08-23 17:31:24.369 3146-3187/org.tensorflow.demo E/art: No implementation found for void org.tensorflow.demo.env.ImageUtils.convertYUV420ToARGB8888(byte[], byte[], byte[], int[], int, int, int, int, int, boolean) (tried Java_org_tensorflow_demo_env_ImageUtils_convertYUV420ToARGB8888 and Java_org_tensorflow_demo_env_ImageUtils_convertYUV420ToARGB8888___3B_3B_3B_3IIIIIIZ)
08-23 17:31:24.369 3146-3187/org.tensorflow.demo W/tensorflow: ImageUtils: Native YUV -> RGB implementation not found, falling back to Java implementation
08-23 17:31:24.589 3146-3187/org.tensorflow.demo I/tensorflow: StylizeActivity: Initializing at size preview size 1280x720, stylize size 256
08-23 17:31:24.620 3146-3186/org.tensorflow.demo I/tensorflow: StylizeActivity: Width: 256 , Height: 256
08-23 17:31:25.127 3146-3186/org.tensorflow.demo E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[input, style_num], outputs:[transformer/expand/conv3/conv/Sigmoid]
                                                                                 
                                                                                 --------- beginning of crash
08-23 17:31:25.128 3146-3186/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: inference
                                                                   Process: org.tensorflow.demo, PID: 3146
                                                                   java.lang.IllegalArgumentException: input_max_range must be larger than input_min_range.
                                                                   	 [[Node: transformer/contract/conv2/Relu_eightbit_quantize_transformer/contract/conv2/InstanceNorm/batchnorm/add_1 = QuantizeV2[T=DT_QUINT8, mode="MIN_FIRST", _device="/job:localhost/replica:0/task:0/cpu:0"](transformer/contract/conv2/InstanceNorm/batchnorm/add_1, transformer/contract/conv2/Relu_eightbit_min_transformer/contract/conv2/InstanceNorm/batchnorm/add_1, transformer/contract/conv2/Relu_eightbit_max_transformer/contract/conv2/InstanceNorm/batchnorm/add_1)]]
                                                                       at org.tensorflow.Session.run(Native Method)
                                                                       at org.tensorflow.Session.access$100(Session.java:48)
                                                                       at org.tensorflow.Session$Runner.runHelper(Session.java:295)
                                                                       at org.tensorflow.Session$Runner.run(Session.java:245)
                                                                       at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:142)
                                                                       at org.tensorflow.demo.StylizeActivity.stylizeImage(StylizeActivity.java:548)
                                                                       at org.tensorflow.demo.StylizeActivity.access$1200(StylizeActivity.java:70)
                                                                       at org.tensorflow.demo.StylizeActivity$3.run(StylizeActivity.java:500)
                                                                       at android.os.Handler.handleCallback(Handler.java:742)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
08-23 17:31:25.149 3146-3186/org.tensorflow.demo E/MQSEventManagerDelegate: failed to get MQSService.
08-23 17:31:25.183 3146-3146/org.tensorflow.demo I/RequestQueue: Repeating capture request cancelled.
...
```

**Comment by ArtsiomCh** [comment]
In my case, the workaround with useCamera2API works with both TF Classify and TF Stylize. And don't work with TF Detect (which it's not supposed to work as of #10771).

Any case, building with `nativeBuildSystem = 'cmake'` give us `libtensorflow_demo.so` with native implementations of `convertYUV420SPToARGB8888` and `convertYUV420ToARGB8888`. That makes the demo to work way faster than with Java implementations. I would suggest making that way to build as the default way as it gives the best experience. 
The only issue with TF Detect needs to be fixed.

I also found that Java implementation of `convertYUV420SPToARGB8888` may be not too complicated as I thought before. Hopefully, I'll be able to implement it within few days.

**Comment by rsd-raul** [comment]
@ArtsiomCh do you still have problems in TF Detect after building with cmake?

**Comment by ArtsiomCh** [comment]
Yes, TF Detect still not working even after cmake build. By the log output
it looks like something goes wrong inside Tensorflow. Will try to fix it
after finishing solution for the current issue, which I hope to make PR
tomorrow.
In the meantime, it would be great if you can create issue for TF Detect
case and describe what you had found. Then I'll top up it with errors I've
got and hopefully we'll be able to find a solution.

With Best regards,
Artsiom Chapialiou

On Aug 24, 2017 05:20, "Raúl Díaz" <notifications@github.com> wrote:

@ArtsiomCh <https://github.com/artsiomch> do you still have problems in TF
Detect after building with cmake?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/issues/12431#issuecomment-324580781>,
or mute the thread

**Comment by andrewharp** [comment]
Unfortunately the detector requires a newer version of the native libs than the current latest published ones in the TF AAR on bintray. This is due to a native code change in https://github.com/tensorflow/tensorflow/commit/53aabd5cb0ffcc1fd33cbd00eb468dd8d8353df2 which added the SSD detector model.

You can work around this most easily by downloading the nightly build of the tensorflow.aar [here](https://ci.tensorflow.org/view/Nightly/job/nightly-android/lastSuccessfulBuild/artifact/out/tensorflow.aar) and placing it into your project. The other option currently is to build the libraries yourself via bazel or make.

When 1.4 is released this issue should be remedied, but we can see about publishing a fix as this is a relatively major issue.

@jch1 @shawngit fyi

**Comment by andrewharp** [comment]
@ArtsiomCh What is the cmake error you're experiencing?

**Comment by ArtsiomCh** [comment]
@andrewharp  It was not a cmake error. I got a similar error as @rsd-raul above:
`..java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'Switch' with these attrs...`
Will check if your solution helps. Thank you for explanations.

**Comment by ArtsiomCh** [comment]
@andrewharp I've continued conversation about TF Detect at https://github.com/tensorflow/tensorflow/issues/12593#issuecomment-326760562

**Comment by andrewharp** [comment]
@ArtsiomCh We've pushed a 1.3.1-alpha AAR (built from master between 1.3.0 and any upcoming 1.3.1 branch) which contains the native patch necessary to run the model (fixes the Switch error). We'll add some notes for future incompatibilities of this nature to suggest, when using the 'none' build type, to download at a pinned revision branch and fixing the TF AAR version to ensure that a known compatible AAR is downloaded.

Closing this issue and tracking the missing `convertYUV420SPToARGB8888` method in #12593 (I see there is also a PR pending to add this as well)

**Comment by lavinachitara** [comment]
I did some modification in TF detect android app to detect person from loaded picture rather than clicking it by camera(Not using cameraActivity).

Everything is working fine except the function named ImageUtils.convertYUV420SPToARGB8888. This function returns distorted image (please find attachment)
![actual_image](https://user-images.githubusercontent.com/2331214/33017067-f6c5dd42-ce16-11e7-9cb0-7827cf490c8b.png)
![converted_image](https://user-images.githubusercontent.com/2331214/33017069-f6f60e2c-ce16-11e7-9772-89d0a7d22612.png)

Sharing part of code below:

            newbitmap = Bitmap.createScaledBitmap(bitmap, 640, 480, false);
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            newbitmap.compress(Bitmap.CompressFormat.JPEG, 100, output);
            imgbytes = output.toByteArray();

            imageConverter =
                new Runnable() {
                    @Override
                    public void run() {
                        ImageUtils.convertYUV420SPToARGB8888(imgbytes, previewWidth, previewHeight, rgbBytes);
                    }
                };

**Comment by ArtsiomCh** [comment]
@lavinachitara I'm not an expert, but if you use a loaded picture then isn't it already in RGB format and no needs to do YUV to RGB converting? Trying to apply YUV to RGB converting to RGB source will produce kind of trash we can see at your screenshot.

**Comment by lavinachitara** [comment]
@ArtsiomCh Thank you, yes I agree, I changed the way to use it +1:
