### ISSUE TITLE
external/eigen_archive/unsupported/Eigen/CXX11/Tensor:84:26: fatal error: cuda_runtime.h: No such file or directory

### ISSUE THREAD

**Issue by sanersbug** [tensorflow/tensorflow#12430]
1.when i use  "sudo bazel build //tensorflow/examples/android:tensorflow_demo"   to get .apk i meet the error:

ERROR: /home/saners/tensorflow/tensorflow/core/kernels/BUILD:4581:1: C++ compilation of rule '//tensorflow/core/kernels:android_tensorflow_kernels' failed: arm-linux-androideabi-gcc failed: error executing command external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -fstack-protector-strong -fpic -ffunction-sections -funwind-tables ... (remaining 77 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:0,
                 from ./tensorflow/core/kernels/bias_op_gpu.h:21,
                 from tensorflow/core/kernels/bias_op.cc:30:
external/eigen_archive/unsupported/Eigen/CXX11/Tensor:84:26: fatal error: cuda_runtime.h: No such file or directory
 #include <cuda_runtime.h>
                          ^
compilation terminated.
Target //tensorflow/examples/android:tensorflow_demo failed to build

2. when i use "bazel build //tensorflow/examples/android:tensorflow_demo" in the terminal
the error is changed : 
tensorflow/core/kernels/lrn_op.cc:34:31: fatal error: cuda/include/cuda.h: No such file or directory

my tensorflow has installed,but i don't know how to solve this problem.
Anyone can help me ? I'am very tired to deal with the error but no method works.
THANK YOU VERY MUCH!

**Comment by sanersbug** [comment]
please!

**Comment by andrewharp** [comment]
Can you please fill out the default form for TF github issues so that we can attempt to diagnose the issue?

**Comment by sanersbug** [comment]
@andrewharp I am sorry,this is my first question after registered，and i don't konw how to fill out the default form and where is is?

**Comment by andrewharp** [comment]
It's in the form when you first open a TensorFlow issue. If you create a new issue you'll see it.

**Comment by sanersbug** [comment]
@Thank you very much, i have re-edit my problems!
