### ISSUE TITLE
OpenMP/OpenACC support for tensorflow

### ISSUE THREAD

**Issue by abidmalik1967** [tensorflow/tensorflow#12434]
Is there any effort in porting the Tensorflow using OpenMP or OpenACC?

**Comment by yaroslavvb** [comment]
@andydavis1 and @benoitsteiner looked at it a while back. There were two issues
1. TensorFlow already has its own set of primitives for parallelizing work-loads
2. It was hard to make it build: compiling with -fopenmp made some seemingly unrelated parts of TensorFlow work incorrectly

**Comment by ali01** [comment]
Thank you, Yaroslav. Closing for now.

**Comment by masoodmortazavi** [comment]
In the exploration of this issue, was attention paid to using Eigen in multi-threaded applications.

Please see the note on calling Eigen::initParallel() before making application threads, in the following:
 https://eigen.tuxfamily.org/dox/TopicMultiThreading.html

**Comment by Tim15** [comment]
@yaroslavvb Could OpenACC be used to optimize parallel tasks like matmuls and convolutions (IDK if you use a library) on a wider range of accelerators (like AMD GPUs), that the CUDA kernels and CPU-oriented code are not targeting? I think that this could complement the existing Tensorflow primitives for parallelization.
