### ISSUE TITLE
std::system_error after restoring model

### ISSUE THREAD

**Issue by tomaird** [tensorflow/tensorflow#12449]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, used saving/restoring example [here](https://www.tensorflow.org/programmers_guide/saved_model)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Red Hat 4.4.7-1
- **TensorFlow installed from (source or binary)**: Anaconda
- **TensorFlow version (use command below)**: 1.2, CPU-only
- **Python version**: 3.5
- **Exact command to reproduce**: [See example here](https://www.tensorflow.org/programmers_guide/saved_model). Error occurs on line `saver.restore(sess, "/tmp/model.ckpt")`

### Describe the problem
When restoring the model using the simple example listed above, the program terminates with the error: 
```
terminate called after throwing and instance of 'std::system_error'
what(): Resource temporarily unavailable
```
Given such a simple example it can't be a memory issue, and there seems to be no other information about this error message online (eg. stackoverflow). Could it be a bug?

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
