### ISSUE TITLE
tensorflow cmake compile problem on vs2015

### ISSUE THREAD

**Issue by kyo055** [tensorflow/tensorflow#12446]
------------------------

### System information
- **windows10**:
- **install tensorflow**: from source by vs2015 
- **TensorFlow version**: r1.2
- **Python**: Anaconda 4.2.0, python3.5
-**SWIG**:  swigwin3.0.10
-**CMake**:  3.8.2
- **Command line to compile**:
`D:\Developer\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat`
`cd tensorflow\tensorflow\contrib\cmake`
` mkdir build`
`cd build`
`cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release ^`
`More? -DSWIG_EXECUTABLE=C:/tools/swigwin-3.0.10/swig.exe ^`
`More? -DPYTHON_EXECUTABLE=D:/Developer/Anaconda3/python.exe ^`
`More? -DPYTHON_LIBRARIES=D:/Developer/Anaconda3/libs/python35.lib ^`
`More? -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX`
### Describe the problem
after generate the configure files, run the command as bellow:
`MSBuild /M:10 /p:Configuration=Release tf_tutorials_example_trainer.vcxproj`   
I have used this command to compile the tensorflow c++ example project and some c++ libs successfully about a month ago.But now, I tried many times never success.

#### Error log
But this time it didn't work, and return the compile error :  
`"C:\Users\Administrator\Desktop\tensorflow\tensorflow\contrib\cmake\build\tf_tutorials_example_trainer.vcxproj"
       (default target) (1) ->
       "C:\Users\Administrator\Desktop\tensorflow\tensorflow\contrib\cmake\build\tf_core_framework.vcxproj" (default ta
       rget) (6) ->
       (CustomBuild target) ->
         C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd
       .exe" exited with code 1. [C:\Users\Administrator\Desktop\tensorflow\tensorflow\contrib\cmake\build\tf_core_fram
       ework.vcxproj]
    277 Warning(s)
    1 Error(s)`

**Comment by kyo055** [comment]
@mrry I hope you can look this problem and help me please.

**Comment by mrry** [comment]
Can you upload the full log from `MSBuild`? From that error message, it's not clear what went wrong.

**Comment by rniebecker** [comment]
Try compiling without:
-Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX

I only managed to compile with SIMD after doing some code changes in kernel classes, haven't tried 1.3 but would not surprised if the issue is still there.

Cheers,
Ralf

**Comment by kyo055** [comment]
@mrry  This is the log file, but it seems too big, and not too many obvious message, maybe I'm not familiar with compile technology and the tensorflow projects.
  [Example_trainer_ProjectOutput.txt](https://github.com/tensorflow/tensorflow/files/1240679/Example_trainer_ProjectOutput.txt)

**Comment by mrry** [comment]
The full logs give some more context for the error message:

```
                     Generating C:/Users/Administrator/Desktop/tensorflow/tensorflow/core/util/version_info.cc (TaskId:136)
                     Traceback (most recent call last): (TaskId:136)
                       File "C:/Users/Administrator/Desktop/tensorflow/tensorflow/tools/git/gen_git_source.py", line 266, in <module> (TaskId:136)
                         raw_generate(args.raw_generate) (TaskId:136)
                       File "C:/Users/Administrator/Desktop/tensorflow/tensorflow/tools/git/gen_git_source.py", line 230, in raw_generate (TaskId:136)
                         git_version = get_git_version(".") (TaskId:136)
                       File "C:/Users/Administrator/Desktop/tensorflow/tensorflow/tools/git/gen_git_source.py", line 156, in get_git_version (TaskId:136)
                         str("--work-tree=" + git_base_path), "describe", "--long", "--tags" (TaskId:136)
                       File "C:\Users\Administrator\Anaconda3\lib\subprocess.py", line 626, in check_output (TaskId:136)
                         **kwargs).stdout (TaskId:136)
                       File "C:\Users\Administrator\Anaconda3\lib\subprocess.py", line 693, in run (TaskId:136)
                         with Popen(*popenargs, **kwargs) as process: (TaskId:136)
                       File "C:\Users\Administrator\Anaconda3\lib\subprocess.py", line 947, in __init__ (TaskId:136)
                         restore_signals, start_new_session) (TaskId:136)
                       File "C:\Users\Administrator\Anaconda3\lib\subprocess.py", line 1224, in _execute_child (TaskId:136)
                         startupinfo) (TaskId:136)
                     FileNotFoundError: [WinError 2] The system cannot find the file specified (TaskId:136)
03:14:03.769     3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\Administrator\Desktop\tensorflow\tensorflow\contrib\cmake\build\tf_core_framework.vcxproj]
```

In this case, it looks like `git` can't be found in your `%PATH%`. Can you check that it is possible to run the command-line `git` tool from the command prompt where you started the build?

**Comment by kyo055** [comment]
@mrry  yes, I forget to add the `git` into my `Path`. Right now, I add it into my `Path` and rebuild the project, hope it will work.
