### ISSUE TITLE
Can't import tensorflow 0.7.1 It thinks I'm importing from source dir.

### ISSUE THREAD

**Issue by EderSantana** [tensorflow/tensorflow#1244]
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

### Environment info
Operating System: Ubuntu 64bit 
CUDA: 7.5

If installed from binary pip package, provide:
I tried installing using both pip CPU and GPU (making sure I uninstalled the previous first):
```
$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp34-none-linux_x86_64.whl

$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp34-none-linux_x86_64.wh
```

### Logs or other output that would be helpful
I get the following error using the new 0.7.1 wheel, although it is fine with the previous one 0.7.0

```
(If logs are large, please upload as attachment).
In [1]: import tensorflow as tf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-41389fad42b5> in <module>()
----> 1 import tensorflow as tf

/home/eders/anaconda/lib/python2.7/site-packages/tensorflow/__init__.py in <module>()
     21 from __future__ import print_function
     22
---> 23 from tensorflow.python import *

/home/eders/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py in <module>()
     39 please exit the tensorflow source tree, and relaunch your python interpreter
     40 from there.""" % traceback.format_exc()
---> 41   raise ImportError(msg)
     42
     43 from tensorflow.core.framework.summary_pb2 import *

ImportError: Traceback (most recent call last):
  File "/home/eders/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/eders/anaconda/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named protobuf


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

Note that I don't even have the source files on my computer. Any idea of what it might be?
Thanks for the help.

**Comment by EderSantana** [comment]
sorry, I forgot to pip install protobuf. I missed that line of the error. It seems to run with GPU under anaconda env btw.

**Comment by murraymack** [comment]
I have this same Error. When I pip install protobuf it says my requirements are satisfied but I still get the error. Any ideas?

**Comment by xiao-cheng** [comment]
@murraymack I resolved this issue by downgrading the protobuf library for now. The latest one is missing __init__.py, i.e. a broken package.

**Comment by mbeale** [comment]
I had this error on mac but then upgraded easy_install

`sudo easy_install --upgrade six`

**Comment by murraymack** [comment]
@xiao-cheng Yes. I did the same unintentionally. I ended up pip uninstalling tensorflow AND pip uninstalling protobuf, and then just pip installed tensorflow and it worked.

For anyone reading, I did this through a Python 2.7 virtual env created in Anaconda.

**Comment by zyy20853** [comment]
@murraymack  thanks for your methods, it works fine even with only pip installation.

**Comment by Sean-Hsueh** [comment]
Same issue, same fix as mentioned by @murraymack , thanks!!

**Comment by jacobmontiel** [comment]
@murraymack solution worked for me

**Comment by inteliL** [comment]
Same error occurred after upgrading Tensorflow to version 0.8 in Mac OS.
@murraymack solution works for me

**Comment by thatindiandude** [comment]
Upgrading to protobuf 3.0.0 from 3.0.0b seemed to solve this for me. Just did: 
`pip install protobuf --upgrade`

**Comment by O1Davies** [comment]
@thatindiandude above solution for upgrading protobuf did it for me on MacOS. Thx.

**Comment by LLPing123** [comment]
I did this through a Python 3.5 virtual env created in Anaconda. 
@murraymack solution is not  worked for me

**Comment by JavascriptMick** [comment]
I ended up using virtual env viz: https://www.tensorflow.org/get_started/os_setup#virtualenv_installation

**Comment by lancezlin** [comment]
pip install protobuf --upgrade and restart interpret works for me.

**Comment by zohairshafi** [comment]
@murraymack I've got the same issue, although, how do you get pip to install and uninstall from the virtual environment instead of the default one? (Python 3 in my case is the default)

**Comment by michaelosthege** [comment]
as of today,(17th January 2017) this issue is still not resolved.

I had it three days ago on my Windows 10 laptop and now I'm running into it again on a AWS EC2 instance.

Several times I've tried starting over with
```bash
conda create -n venv35 numpy python=3.5
```
followed by
```bash
source activate venv35
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp35-cp35m-linux_x86_64.whl
```
I've tried uninstalling/installing protobuf, but since I still get the same behaviour even if protobuf is not even installed, I don't believe that is has something to do with it.

This is very frustrating. Any help is appreciated.

**Comment by michaelosthege** [comment]
according to https://github.com/tensorflow/tensorflow/issues/5343#issuecomment-257765523
the recent tensorflow releases only support CUDA 8 !

I think in my case that's the reason for the incompability.

**Comment by gautamsreekumar** [comment]
@murraymack that worked for me.

the method where we edit /usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py didn't work for me

**Comment by zohairshafi** [comment]
@murraymack's method worked for me as well. Thank you!

**Comment by brando90** [comment]
What does it mean to be in the "source directory". I am also having the same issue however, I have no idea what the source directory is.

**Comment by jaspree** [comment]
c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\decoder.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\descriptor_database_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\descriptor_pool_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\descriptor_pool_test1_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\descriptor_pool_test2_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\descriptor_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\encoder.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\enum_type_wrapper.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\factory_test1_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\factory_test2_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\file_options_test_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\generator_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\import_test_package\__init__.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\import_test_package\__pycache__\__init__.cpython-35.pyc
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\import_test_package\__pycache__\inner_pb2.cpython-35.pyc
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\import_test_package\__pycache__\outer_pb2.cpython-35.pyc
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\import_test_package\inner_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\import_test_package\outer_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\json_format_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\message_factory_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\message_listener.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\message_set_extensions_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\message_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\missing_enum_values_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\more_extensions_dynamic_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\more_extensions_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\more_messages_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\packed_field_test_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\proto_builder_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\python_message.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\reflection_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\service_reflection_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\symbol_database_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\test_bad_identifiers_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\test_util.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\testing_refleaks.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\text_encoding_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\text_format_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\type_checkers.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\unknown_fields_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\well_known_types.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\well_known_types_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\wire_format.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\internal\wire_format_test.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\json_format.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\map_unittest_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\message.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\message_factory.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\proto_builder.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\pyext\__init__.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\pyext\__pycache__\__init__.cpython-35.pyc
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\pyext\__pycache__\cpp_message.cpython-35.pyc
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\pyext\__pycache__\python_pb2.cpython-35.pyc
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\pyext\cpp_message.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\pyext\python_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\reflection.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\service.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\service_reflection.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\source_context_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\struct_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\symbol_database.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\test_messages_proto3_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\text_encoding.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\text_format.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\timestamp_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\type_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\unittest_arena_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\unittest_custom_options_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\unittest_import_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\unittest_import_public_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\unittest_mset_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\unittest_mset_wire_format_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\unittest_no_arena_import_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\unittest_no_arena_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\unittest_no_generic_services_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\unittest_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\unittest_proto3_arena_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\util\__init__.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\util\__pycache__\__init__.cpython-35.pyc
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\util\__pycache__\json_format_proto3_pb2.cpython-35.pyc
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\util\json_format_proto3_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\google\
protobuf\wrappers_pb2.py
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\protobu
f-3.2.0-py2.7-nspkg.pth
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\protobu
f-3.2.0.dist-info\description.rst
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\protobu
f-3.2.0.dist-info\installer
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\protobu
f-3.2.0.dist-info\metadata
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\protobu
f-3.2.0.dist-info\metadata.json
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\protobu
f-3.2.0.dist-info\namespace_packages.txt
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\protobu
f-3.2.0.dist-info\record
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\protobu
f-3.2.0.dist-info\top_level.txt
  c:\users\jass\appdata\local\programs\python\python35\lib\site-packages\protobu
f-3.2.0.dist-info\wheel
Proceed (y/n)? y
  Successfully uninstalled protobuf-3.2.0

C:\>pip install tensorflow
Collecting tensorflow
  Using cached tensorflow-1.0.0-cp35-cp35m-win_amd64.whl
Collecting protobuf>=3.1.0 (from tensorflow)
  Using cached protobuf-3.2.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10.0 in c:\users\jass\appdata\local\progra
ms\python\python35\lib\site-packages (from tensorflow)
Requirement already satisfied: numpy>=1.11.0 in c:\users\jass\appdata\local\prog
rams\python\python35\lib\site-packages (from tensorflow)
Requirement already satisfied: wheel>=0.26 in c:\users\jass\appdata\local\progra
ms\python\python35\lib\site-packages (from tensorflow)
Requirement already satisfied: setuptools in c:\users\jass\appdata\local\program
s\python\python35\lib\site-packages (from protobuf>=3.1.0->tensorflow)
Requirement already satisfied: appdirs>=1.4.0 in c:\users\jass\appdata\local\pro
grams\python\python35\lib\site-packages (from setuptools->protobuf>=3.1.0->tenso
rflow)
Requirement already satisfied: packaging>=16.8 in c:\users\jass\appdata\local\pr
ograms\python\python35\lib\site-packages (from setuptools->protobuf>=3.1.0->tens
orflow)
Requirement already satisfied: pyparsing in c:\users\jass\appdata\local\programs
\python\python35\lib\site-packages (from packaging>=16.8->setuptools->protobuf>=
3.1.0->tensorflow)
Installing collected packages: protobuf, tensorflow
Successfully installed protobuf-3.2.0 tensorflow-1.0.0

C:\>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\importlib\__ini
t__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\importlib\__ini
t__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\importlib\__ini
t__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "C:\Users\JASS\AppData\Local\Programs\Python\Python35\lib\importlib\__ini
t__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_st
arted/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> i

**Comment by jaspree** [comment]
plz help me in this problem ..

**Comment by adilkaleem** [comment]
I'm doing it on a windows machine. None of the solutions given above worked for me; except I haven't yet tried through conda.

**Comment by apuayush** [comment]
Any concrete solution we have for this problem. I am struggling with it for quite some time now
