### ISSUE TITLE
The sample code on PROGRAMMER'S GUIDE has a problem

### ISSUE THREAD

**Issue by muchrooms** [tensorflow/tensorflow#12444]
Hello,

There is a problem on the PROGRAMMER'S GUIDE.
https://www.tensorflow.org/programmers_guide/variables#sharing_variables

In the second code snippet of the chapter "Sharing variables"
```Python
input1 = tf.random_normal([1,10,10,32])
input2 = tf.random_normal([1,20,20,32])
x = conv_relu(input1, kernel_shape=[5, 5, 1, 32], bias_shape=[32])
x = conv_relu(x, kernel_shape=[5, 5, 32, 32], bias_shape = [32])  # This fails.
```

### Problem
The shape doesn't match.

### Solution
Change the third line to
```Python
x = conv_relu(input1, kernel_shape=[5, 5, 32, 32], bias_shape=[32])
```

And the code after this also have the problem.

**Comment by yongtang** [comment]
Added PR #12452 for doc fix.
