### ISSUE TITLE
The tensorflow wasn't compiled to use AVX2 on Windows

### ISSUE THREAD

**Issue by RafaelFPinheiro** [tensorflow/tensorflow#12451]
I instaled the python 3 and the tensorflow from pip.
But when I run the program I receive the warnings:
![image](https://user-images.githubusercontent.com/29586672/29518621-76586372-8650-11e7-8a86-36e4fce5923d.png)

How to hidden or fix the warnings on Windows? Thank you so much!

**Comment by jubjamie** [comment]
They're just warnings informing you that you could get improved performance by compiling from source for your machine. You can safely ignore them. If you desperately want to suppress them then you can but you risk missing other warnings as afaik the only way to suppress is to set the over TF logging limit so not ideal. If you can live with them then it's fine. Nothing is really wrong!

**Comment by mrlzla** [comment]
I don't think so. AFAIK it's not possible now to compile tensorflow with AVX2 instructions on Windows because there are some intristics used that Visual Studio compiler doesn't support now.

**Comment by jubjamie** [comment]
Good to know. Either way, OP shouldn't be overly concerned about this unless they were expecting the binary to have AVX2!

**Comment by amar1** [comment]
Use below code in your .py file

`import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
`
