### ISSUE TITLE
README link to Linux GPU Python 3.5 nightly build is broken 

### ISSUE THREAD

**Issue by chrisranderson** [tensorflow/tensorflow#12461]
I figured you wouldn't need the form information. The link:

https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3.5,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-1.3.0-cp35-cp35m-linux_x86_64.whl

My response:

```
HTTP ERROR 404

Problem accessing /view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3.5,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-1.3.0-cp35-cp35m-linux_x86_64.whl. Reason:

    Not Found
Powered by Jetty://
```

**Comment by andydavis1** [comment]
They link worked for me. Please re-open if issue persists...
