### ISSUE TITLE
libtensorflow_framework.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#1248]
centos 7
python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.7.1

$ python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())'
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
/usr/lib/python2.7/site-packages/tensorflow/core

$ ls /usr/lib/python2.7/site-packages/tensorflow/core/
example/                    __init__.py                 kernels/                    libtensorflow_framework.so  util/                       
framework/                  __init__.pyc                lib/                        protobuf/                   

ipython
Python 2.7.5 (default, Nov 20 2015, 02:00:19) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally

In [2]: tf.load_op_library('./auc.so')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-32f9df443d84> in <module>()
----> 1 tf.load_op_library('./auc.so')

/usr/lib/python2.7/site-packages/tensorflow/python/framework/load_library.pyc in load_op_library(library_filename)
     55   try:
     56     if py_tf.TF_GetCode(status) != 0:
---> 57       raise RuntimeError(compat.as_text(py_tf.TF_Message(status)))
     58   finally:
     59     py_tf.TF_DeleteStatus(status)

RuntimeError: libtensorflow_framework.so: cannot open shared object file: No such file or directory

In [3]: 

I need to copy libtensorflow_framework.so to the working path to run script.

**Comment by keveman** [comment]
How do you build auc.so?
Like it says in the documentation [here](https://www.tensorflow.org/versions/master/how_tos/adding_an_op/index.html#building-the-op-library), make sure you have `-rpath $TF_LIB` in the command line arguments to `g++`. If you indeed pass that flag and it still doesn't work, try adding `$TF_LIB` to your `$LD_LIBRARY_PATH`. I verified that I can indeed load an op with `load_op_library` and didn't see the errors you are seeing. Closing the issue. Please reopen with more information, in case it still doesn't work.

**Comment by chenghuige** [comment]
@keveman  Thanks, the so is built on another ubuntu platform, and I miss this problem when using the so on centos, after rebuilding auc.so now every thing is Ok.
Another thing, might worth a look, in order to gen auc.so, I need to first install google protobuffer, then, I need to add below to my ~/.bashrc for a workaround for missing eigen related headers.
export CPLUS_INCLUDE_PATH=~/.cache/bazel/_bazel_gezi/90eddd4c58c33600d0766ab4c9609dbb/external/eigen_archive/:~/.cache/bazel/_bazel_gezi/90eddd4c58c33600d0766ab4c9609dbb/external/eigen_archive/eigen-eigen-70505a059011:~/.cache/bazel/_bazel_gezi/90eddd4c58c33600d0766ab4c9609dbb/external/tf/third_party/:~/other/tensorflow/
