### ISSUE TITLE
Feature request: stop requiring the same dtype for inputs in tf.shape_n

### ISSUE THREAD

**Issue by leandro-gracia-gil** [tensorflow/tensorflow#12486]
As for Tensorflow 1.3, [tf.shape_n](https://www.tensorflow.org/api_docs/python/tf/shape_n) takes a list of tensors as input to produce a list of shapes as output. However, it produces an error if tensors of different types are provided. As far as I can tell, whether tensors are the same type or not is completely irrelevant to the behavior of this function, making it an arbitrary constraint that limits its functionality for no particular reason.

Would it be possible to remove such restriction if there's no good reason to keep it?

**Comment by leandro-gracia-gil** [comment]
Note: this should probably have a very low priority since there's a quite simple workaround:

```python
def shape_n(input, out_type=tf.int32):
  return [tf.cast(tf.shape(t), out_type) for t in input]
```

That's not exactly equivalent since it's not a single named op with n outputs, but n unnamed ops with a single output. Yet, the result should be the same.

In any case, I'm merely rising the point for any future updates.

**Comment by ali01** [comment]
We currently don't have anybody working on this. It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thanks!

**Comment by ibrahimsharaf** [comment]
Hi @leandro-gracia-gil @ali01, I am new to open source, how can I start working on this?

**Comment by sushreebarsa** [comment]
@leandro-gracia-gil Other TensorFlow functions like tf.stack and tf.concat already support heterogeneous tensor inputs and automatically perform type casting if necessary.  It is a TF 1.x related issue which needs to be upgraded to the latest as older versions are not actively supported. Kindly refer to the migration doc [here](https://www.tensorflow.org/guide/migrate). Please create a new ticket if you still have a concern?
Thank you!
