### ISSUE TITLE
Feature request: manual parallel

### ISSUE THREAD

**Issue by mwsht** [tensorflow/tensorflow#12492]
when I run my code in that way:

    for i in range(num):
        with tf.control_dependencies(None):
            output[i] = tf.identity(deepnn(x))

TF will run the deepnn(x) one by one.
Would it be possible to parallel it manually like this:

    #pragma omp for

**Comment by AswinBlue** [comment]
As I know, if you don't use control_depencies(), tensorflow will treat 'for' loop in paralell

if you should use control_depencies(), How about using 
```
while_loop(
    cond,
    body,
    loop_vars,
    shape_invariants=None,
    parallel_iterations=10,
    back_prop=True,
    swap_memory=False,
    name=None
)
```
instead of ' for ' loop ?

**Comment by ali01** [comment]
Indeed, using TensorFlow's native control flow operations like tf.while is the best way to enable parallelism.

**Comment by caissalover** [comment]
Now that tf.function has become central in 2.0, a feature named tf.prange (parallel range) can be extremely helpful to manually place a single graph in parallel on GPU. This will help code to be debugged better.

I request you to reconsider this to enable easier and faster code in tf2.0
