### ISSUE TITLE
Can anyone install it with cuda7.5 and cudnn 7.0?

### ISSUE THREAD

**Issue by wuqiangch** [tensorflow/tensorflow#125]
I installed it from source code. Everything is OK. 
  But when I  run '"""bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu""" . 
  The errors are   1)Unable to load cuBLAS DSO,2)Unable to load cuDNN DSO,3)Unable to load cuFFT DSO,4)Unable to load cuRAND DSO.

**Comment by sibleyd** [comment]
see https://github.com/tensorflow/tensorflow/issues/54 or https://github.com/tensorflow/tensorflow/issues/20

**Comment by binary42** [comment]
This is vexing...plus looking at the other issues, this does not lend faith to this highly publicized software release...Forcing a dependency version prior to the latest version is just silly. Hope Google fixes this soon.

**Comment by vrv** [comment]
Yup, we're working on it.

**Comment by zhongliangong** [comment]
I got it to run. just manually modified all references to 7.5 (7.0 for cudnn).

Just do ```grep -r -n libcu *``` from inside the tensorflow directory and then open another window to manually adjust the source files. It appears to compile and run the sample training. 

My question to the tensorflow team would be whether the decision to not include R3 was based on incompatibilities in the API  (I had thought that nvidia's cuDNN libraries were meant to be drop-in upgradeable), or the lack of testing with R3.

**Comment by zheng-xq** [comment]
@zhongliangong, TensorFlow in its current form is extensively tested with Cudnn R2. You are welcome to modify the source and try with R3 locally. The official upgrade will happen when it is ready.

**Comment by mtanana** [comment]
Another (hacky) way to fix this:  on linux, in your cuda directory there are already symbolic links from the *.7.5 named file to the non-suffixed files.  Just create another symbolic link for each of those that is *.7.0 and it works like a charm!

**Comment by helxsz** [comment]
@mtanana  I tried your solution. It seems to be working, but there is some warmings, such as 
**
tensorflow/stream_executor/cuda/cuda_fft.cc:327] Unable to load cuFFT DSO.
I tensorflow/stream_executor/dso_loader.cc:77] LD_LIBRARY_PATH: /usr/local/cuda-7.5/lib64:/usr/local/cuda-7.5/lib64:/usr/local/cuda-7.5/lib64:
I tensorflow/stream_executor/cuda/cuda_rng.cc:317] Unable to load cuRAND DSO.
**

does these warming matters or we can ignore it?

**Comment by mtanana** [comment]
I think these warning means that it did not work.  (These were the warnings that went away after I made the symbolic links).  Did you make 6ish links in your /usr/local/cuda-7.5/lib64 folder?  For example, what did you name the one for cuRAND?  And what did it link to?
