### ISSUE TITLE
EditDistance crashes under C++ environment

### ISSUE THREAD

**Issue by rasitsimsek** [tensorflow/tensorflow#12501]
### System information
- **Windows 10**:
- **TensorFlow installed from source**:
- **TensorFlow version 1.3-rc2**:
- **Python version 3.5**:
- **VisualStudio 2017**:

### Describe the problem
I have created a C++ example with EditDistance and linked a debug version of tensorflow.dll which is created from tensorflow source.  The compiled EditDistance example crashed at **session.Run( outputs, &output_tensor );**. I have tried in this example also in the tensorflow environment it crashes also. It seems the EditDistance operator doesn't work under C++. I have searched another EditDistance examples but it seems nobody has tested it outside the python environment.

### Source code / logs
```
#include <iostream>
#include <vector>
#include <string>
#include <unordered_set>

#include "tensorflow/cc/client/client_session.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/lib/gtl/edit_distance.h"
#include "tensorflow/core/util/sparse/sparse_tensor.h"
#include "tensorflow/core/protobuf/config.pb.h"

using namespace std;
```

    int main( int argc, char *argv[] )
```
{
           using namespace tensorflow;
           using namespace tensorflow::ops;
           using namespace tensorflow::gtl;
           Scope root = Scope::NewRootScope();
```

           std::vector<Tensor> output_tensor;
           ClientSession session( root );

           Tensor hypho2_ix( DT_INT64, TensorShape( { static_cast<int64_t>( 4 ), 3 } ) );
           Tensor hypho2_vals( DT_STRING, TensorShape( {static_cast<int64_t>( 4 )} ) );

           makeIndex( {"bear"}, hypho2_ix );
           makeChar ( {"bear"}, hypho2_vals );

           Tensor truth2_ix( DT_INT64, TensorShape( { static_cast<int64_t>( 5 ), 3 } ) );
           Tensor truth2_vals( DT_STRING, TensorShape( {static_cast<int64_t>( 5 )} ) );

           makeIndex( { "beers" }, truth2_ix );
           makeChar ( { "beers" }, truth2_vals );

           // Declaration of edit distance
           auto address_dist = EditDistance( root
                                   , hypho2_ix
                                   , hypho2_vals
                                   , {3,1,1}// {static_cast<int64_t>(1),3}//test_address_shape
                                   , truth2_ix
                                   , truth2_vals
                                   , {3,1,1} //ref_address_shape
                                   , EditDistance::Normalize(false) );

                                      const std::vector<Output> outputs = {address_dist};
           session.Run( outputs, &output_tensor );
     }   
        void makeIndex( const std::vector<string>& rsoStringVector, tensorflow::Tensor& roIndexTensor )
        {
           auto ix_t = roIndexTensor.matrix<int64_t>();
           std::size_t stCounter = 0;
           for( std::size_t stX = 0; stX < rsoStringVector.size() ; stX++ )
           {
              const std::string& rsString = rsoStringVector[ stX ];
              for( std::size_t stY = 0; stY < rsString.size(); stY++ )
              {
                 ix_t( stCounter, 0 ) = stX;
                 ix_t( stCounter, 1 ) = 0;
                 ix_t( stCounter, 2 ) = stY;
                 stCounter++;
              }
           }
        }

        void makeChar( const std::vector<std::string>& rsoStringVector, tensorflow::Tensor& roCharTensor )
        {
           auto vals_t = roCharTensor.vec<std::string>();

           int64_t i64Index = 0;
           for( std::size_t stX = 0; stX < rsoStringVector.size(); stX++ )
           {
              const std::string& rsString = rsoStringVector[ stX ];
              for( std::size_t stY = 0; stY < rsString.size(); stY++ )
              {
                 vals_t( i64Index++ ) = ( rsString[ stY ] );
              }
           }
        }

**Comment by rasitsimsek** [comment]
I have figured out that the crash occurs  in ClientSessionRun::Run() method. The reason is the Output object in fetch_outputs vector is not correctly installed. The Node member of Output is null. This causes an exception at **output_tensor_names.push_back(output.name());**

```
Status ClientSession::Run(const RunOptions& run_options, const FeedType& inputs,
                          const std::vector<Output>& fetch_outputs,
                          const std::vector<Operation>& run_outputs,
                          std::vector<Tensor>* outputs,
                          RunMetadata* run_metadata) const {
  std::vector<std::pair<string, Tensor>> feeds;
  for (auto const& feed : inputs) {
    TF_RETURN_IF_ERROR(feed.second.status);
    feeds.emplace_back(feed.first.name(), feed.second.tensor);
  }
  std::vector<string> output_tensor_names;
  output_tensor_names.reserve(fetch_outputs.size());
  for (auto const& output : fetch_outputs) {
    output_tensor_names.push_back(output.name());
  }
  std::vector<string> target_node_names;
  target_node_names.reserve(run_outputs.size());
  for (auto const& output : run_outputs) {
    target_node_names.push_back(output.node()->name());
  }
  TF_RETURN_IF_ERROR(impl()->MaybeExtendGraph());
  return impl()->session_->Run(run_options, feeds, output_tensor_names,
                               target_node_names, outputs, run_metadata);
}
```

As I see the default Output object initializes the node member **op_** with null. The question is how the Output should be initialized? The documentation says it will be filled automatically. Is this not a discrepancy? 

```

/// Represents a tensor value produced by an Operation.
class Output {
 public:
  Output() = default;
  explicit Output(Node* n) : op_(n) {}
  Output(Node* n, int32 index) : op_(n), index_(index) {}
  Output(const Operation& op, int32 index) : op_(op), index_(index) {}

  Operation op() const { return op_; }
  Node* node() const { return op().node(); }
  int32 index() const { return index_; }
  DataType type() const { return op_.output_type(index_); }
  string name() const { return strings::StrCat(node()->name(), ":", index()); }
  bool operator==(const Output& other) const {
    return op_ == other.op_ && index_ == other.index_;
  }

  uint64 hash() const { return op_.hash(index_); }

 private:
  Operation op_ = Operation(nullptr);
  int32 index_ = 0;
};

```

**Comment by rasitsimsek** [comment]
I have found this errors:

- Input 'hypothesis_shape' passed int32 expected int64
- Input 'truth_shape' passed int32 expected int64

These errors are preventing to build the internal node. It is not obvious why EditDistance construction has failed and the node pointer is null.

**Comment by andydavis1** [comment]
@asimshankar Can you take a look of assign to another person? Thanks...

**Comment by rasitsimsek** [comment]
I have solved the problems. The main problem of Tensorflow usage in C++ environment is not checking the variable types at compile time. Tensorflow checks variable types at runtime, which makes troubleshooting more difficult.
E.g. Tensor hypho2_ix( DT_INT64, TensorShape( { 4, 3 } ) ); 
This definition of hypho2_ix is wrong due the numbers 4 and 3 parameters are not int64_t type. But the C++ compiler is not checking the type at compile time. If you using this defined tensor with operations which requires DT_INT64 (int64_t) type then you will have not obvious error. Why check parameter types of Tensor definitions at compile time?
