### ISSUE TITLE
Inconsistent use of naming `Backprop`

### ISSUE THREAD

**Issue by Corea** [tensorflow/tensorflow#12515]
### Describe the problem
Tensorflow code has two types of naming `Backprop` and `BackProp`. How about to rename all `BackProp` to `Backprop` for consistency?

### Source code / logs
- `Backprop` in code : [control_flow_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/control_flow_ops.py#L909), [op_level_cost_estimator.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/costs/op_level_cost_estimator.cc#L672)

**Comment by ngetahun** [comment]
Hi! I want to make this my first contribution to tensorflow. Has anyone started working on this?

**Comment by aseemraj** [comment]
Hey @ngetahun, I just started working on this. I can look for another starter issue if you want to pick this up. Saw your comment after I forked. Let me know. Doing a `grep -rn . -e 'BackProp'` lists some more places other than those mentioned above that we might want to rename from BackProp to Backprop.

**Comment by Corea** [comment]
Closed via https://github.com/tensorflow/tensorflow/pull/12623
