### ISSUE TITLE
install from source failed!

### ISSUE THREAD

**Issue by andyyuan78** [tensorflow/tensorflow#1251]
envy@ub1404:~/os_pri/github/tensorflow$ sudo rm -rf ~/.cache/bazel   # just try at second time

envy@ub1404:~/os_pri/github/tensorflow$ sudo bazel build -c opt --config=cuda --verbose_failures //tensorflow/cc:tutorials_example_trainer 
Extracting Bazel installation...
.....
INFO: Found 1 target...
INFO: From Executing genrule @png_archive//:configure [for host]:
src/main/tools/namespace-sandbox.c:460: mount(opt->sandbox_root, opt->sandbox_root, NULL, MS_BIND | MS_NOSUID, NULL): Permission denied
ERROR: /home/envy/.cache/bazel/_bazel_root/d161cc2b736082b8df6a4c27a7f7e3a8/external/png_archive/BUILD:23:1: Executing genrule @png_archive//:configure failed: bash failed: error executing command 
  (cd /home/envy/.cache/bazel/_bazel_root/d161cc2b736082b8df6a4c27a7f7e3a8/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; pushd external/png_archive/libpng-1.2.53; workdir=$(mktemp -d -t tmp.XXXXXXXXXX); cp -a * $workdir; pushd $workdir; ./configure --enable-shared=no --with-pic=no; popd; popd; cp $workdir/config.h bazel-out/host/genfiles/external/png_archive/libpng-1.2.53; rm -rf $workdir;'): bash failed: error executing command 
  (cd /home/envy/.cache/bazel/_bazel_root/d161cc2b736082b8df6a4c27a7f7e3a8/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; pushd external/png_archive/libpng-1.2.53; workdir=$(mktemp -d -t tmp.XXXXXXXXXX); cp -a * $workdir; pushd $workdir; ./configure --enable-shared=no --with-pic=no; popd; popd; cp $workdir/config.h bazel-out/host/genfiles/external/png_archive/libpng-1.2.53; rm -rf $workdir;').
Target //tensorflow/cc:tutorials_example_trainer failed to build
INFO: Elapsed time: 27.500s, Critical Path: 2.21s
envy@ub1404:~/os_pri/github/tensorflow$

**Comment by vrv** [comment]
You probably don't want to run bazel with 'sudo'.

**Comment by andyyuan78** [comment]
yes, that is the root cause.
since the first time I am have bazel installed without '--user' , I have to run with 'sudo'

now I reinstall bazel with --user, it works without sudo
