### ISSUE TITLE
tensorflow-0.7.1-cp27-none-any.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by maheshwarLigade** [tensorflow/tensorflow#1252]
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

### Environment info
Operating System:
yosemite os x
If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

If installed from sources, provide the commit hash:

### Steps to reproduce
1.
2.
3.

### What have you tried?
1.source ~/tensorflow/bin/activate
2.pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp27-none-any.whl

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
tensorflow-0.7.1-cp27-none-any.whl is not a supported wheel on this platform.

**Comment by vrv** [comment]
What do you get when you run

```
pip -- version
```

?

**Comment by maheshwarLigade** [comment]
pip 7.1.2 from /usr/local/lib/python3.5/site-packages (python 3.5)

**Comment by vrv** [comment]
Try installing the python3 wheel, not the python2 one.

**Comment by vrv** [comment]
(https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp35-none-any.whl)

**Comment by maheshwarLigade** [comment]
How i didn't get? can u drop me command?

**Comment by maheshwarLigade** [comment]
Exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 538, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/site-packages/external/__init__.py' -> '/var/folders/55/crqk_b7n0pn13rh7c0kwp5300000gn/T/pip-o8eda0ef-uninstall/usr/local/lib/python3.5/site-packages/external/__init__.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/usr/local/lib/python3.5/site-packages/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 553, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/site-packages/external/__init__.py'

**Comment by vrv** [comment]
Sounds like an issue with permissions -- consider installing in a virtualenv, as described on the install guide on tensorflow.org

**Comment by mwlow** [comment]
Getting the same thing:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/tensorflow-0.7.1.dist-info'

Trying to install in a conda env. The python 2 version works, but not python 3. It seems to want to install globally instead of in the env.

**Comment by maheshwarLigade** [comment]
Thanks  I resolved it, i installed globally instead in envirnoment
