### ISSUE TITLE
[CMake] fatal error: 'nsync_time_init.h' file not found on mac

### ISSUE THREAD

**Issue by kaspermarstal** [tensorflow/tensorflow#12534]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Darwin T-X.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
- **TensorFlow installed from (source or binary)**:
Source.
- **TensorFlow version (use command below)**:
Not applicable. Happens during build.
- **Python version**: 
Not applicable. Happens during build.
- **Bazel version (if compiling from source)**:
Not applicable. Compiling directory tensorflow/contrib/cmake using CMake 3.7.2 and clang Apple LLVM version 8.1.0 (clang-802.0.42).
- **CUDA/cuDNN version**:
Not applicable.
- **GPU model and memory**:
Not applicable.
- **Exact command to reproduce**:
cmake --build /Users/kasper/Development/tensorflow_pr/tensorflow/contrib/cmake --target all -- -j 8

### Describe the problem
This is a bug related to the CMake build of TensorFlow which fails on my system due to an error with the nsync build. The nsync build seems to not include some headers (see below). I have tested with TensorFlow v1.0.0, v1.1.0, v1.2.0 and the current master branch. I have not been able to investigate the nsync error because a standalone nsync build (i.e. clone->cmake->make) fails at an earlier step (`/Users/kasper/Development/nsync/platform/macos/platform.h:35:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t') typedef int clockid_t;`). Unfortunately, I have not been able to submit an issue to https://github.com/google/nsync and resolve this problem because issues are disabled for this repository.

### Source code / logs
[ 46%] Building CXX object CMakeFiles/nsync.dir/platform/c++11/src/time_rep_timespec.cc.o
no
/Users/kasper/Development/TensorFlowImageFilter/SuperBuild/cmake-build-debug/TensorFlow-build/nsync/src/nsync/platform/c++11/src/time_rep_timespec.cc:19:10: fatal error: 'nsync_time_init.h' file not found
#include "nsync_time_init.h"

**Comment by kaspermarstal** [comment]
Manually copying `nsync_time_init.h` from `nsync/platform/posix` to `nsync/platform/macos` fixes the issue. Closing since this is not a TensorFlow issue. Pinging @m3bm3b.

**Comment by kaspermarstal** [comment]
@m3bm3b The issue is still present in TensorFlow 1.4. Are you interested in a PR?

**Comment by m3bm3b** [comment]
Beware that the cmake build is not fully supported 
and not routinely tested on MacOS.  
The cmake build is there mostly for Windows.

However, at least for that particular error
     'nsync_time_init.h' file not found
the current master branch of TensorFlow should 
get past that point in the build.
The key difference from 1.4 that should fix the issue is in the file
   tensorflow/contrib/cmake/patches/nsync/CMakeLists.txt
and especially (new) line 64 of that file.

**Comment by kaspermarstal** [comment]
Okay, many thanks for the update! Appreciated.
