### ISSUE TITLE
FPGA Implementation on TensorFlow

### ISSUE THREAD

**Issue by jiawen11** [tensorflow/tensorflow#12538]
Hi all,

Recently, I read some papers about implementing Intel Xeon Phi on Tensorflow. Therefore, I want to make TensorFlow support FPGA board. But there is no information in Google and other forum/community.

For my understanding, we should implement the FPGA supporting in a class of TensorFlow which distributes tasks to different devices (like GPU/CPU). Is possible that implementing the FPGA supporting in that class? Or is there any good suggestions to make the progress to support FPGA on TensorFlow? 

I am looking forward any help or advice!

Thanks,
Kevin

**Comment by kinsumliu** [comment]
How about implement an ops of Tensorflow using FPGA?

https://www.tensorflow.org/extend/adding_an_op

**Comment by Piedone** [comment]
Related: https://github.com/tensorflow/tensorflow/issues/8820

**Comment by mohantym** [comment]
Hi @jiawen11 !
I do see an implementation of Tensorflow on FPGA board (1.8 version though) through [LeFlow](https://github.com/danielholanda/LeFlow). will connect with team on it though for feasibility of 2.x implementation.

Closing this issue  as duplicate to #8820  (Please comment in #8820)

Feel free to raise a PR from your end.

Thank you!
