### ISSUE TITLE
Is there any method to dump the IR and machine code of XLA compiler?

### ISSUE THREAD

**Issue by lijiansong** [tensorflow/tensorflow#12530]
Is there any method to dump the IR of tensorflow xla `from the compilers front end to the backend`, as detailed as better!
Such as the HLO IR to LLO IR and the machine code generated by xla backend? I wonder the details of TensorFlow XLA compiler, the official website isn't detailed...

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by learyg** [comment]
I posted some information on this here: https://stackoverflow.com/a/45518731

**Comment by lijiansong** [comment]
@learyg ok, thanks

**Comment by sunilanil** [comment]
I am not able to take ir dump using new flag --xla_dump_ir_to=/path
the previous flag I am able to get the dump xla_generate_hlo_text_to
