### ISSUE TITLE
Printing lines without logging prefix using tf.Print()

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#12537]
Right now, all messages printed via `tf.Print()` are prefixed by:

```
<timestamp>: I tensorflow/core/kernels/logging_ops.cc:79]
```

It would be useful to have a way to print user-friendly output from within the graph. Therefore, suggest adding a parameter for the logging format to `tf.Print()`, or at least adding a flag that disables the logging prefix.

**Comment by vrv** [comment]
The prefix comes from LOG(INFO) inside the logging_ops kernel.  The fix needs to be made at the C++ level, though I don't have a good recommendation as to how.
