### ISSUE TITLE
Feature Request - Dynamic Dispatch of optimized functions for deployment builds

### ISSUE THREAD

**Issue by vade** [tensorflow/tensorflow#12541]
P
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
NA
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Mac OS X 10.12.16 
- **TensorFlow installed from (source or binary)**:
N/A
- **TensorFlow version (use command below)**:
N/A
- **Python version**: 
N/A
- **Bazel version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
N/A

### Describe the problem

Hello. Thanks for TF.

Recently OpenCV has integrated dynamic dispatch allowing OpenCV library to leverage optimal code paths for supported hardware acceleration (sse, fma, avx, avx2 etc), from a single compiled binary. This is super useful for deployment builds when you are unsure what CPU family/features will potentially run your binary. 

I understand TF's execution model and potentially XLA may add complications, not even to say GPU support - but for CPU ops, or CPU only deployments I imagine something equivalent would be well received.

While we are speaking of deployment builds, are folks just shipping non-optimized-for-client-hardware binaries, or compiling different builds for different hardware features for end products?

Thank you.

**Comment by andydavis1** [comment]
If you build TF with MKL support, the MKL library will detect your CPU architecture (at runtime) and use the appropriate instruction set for that CPU (so you'll get optimizations that work for that particular CPU). Is this what you mean by dynamic dispatch?

**Comment by vade** [comment]
Hi @andydavis1 - yes, apologies if my terminology was incorrect or misleading - I was following OpenCVs terminology which I presumed was standard.

I didn't realize MKL supports this. Thats great news. I am happy to give that a shot. Does Master have working MKL compilation out of the box for Mac OS X? Happy to mark this issue closed and move commentary to #10685 if you feel that is appropriate.

**Comment by vade** [comment]
Interesting about the MKL on OS X performance though. Its never straightforward is it !?

**Comment by andydavis1** [comment]
Yes, please move commentary to #10685, I'll close this out.

**Comment by yaroslavvb** [comment]
IMHO it would be great to remove the need for instruction-specific builds. It seems technically hard to implement and possibly not priority for Google since it has small number of CPU configurations and an easy way to build separate binaries for them. MKL integration introduces dispatch for ops with MKL implementations (ie, subset of 500+ ops in TensorFlow), hopefully that covers all ops that matter for performance

**Comment by nietras** [comment]
I was also surprised to learn that TensorFlow does not do automatic CPU dispatch. MKL as such is fine but why not support it out of the box? Using an auto-vectorizing compiler like MSVC++ could do this for some algorithms.
