### ISSUE TITLE
tfdbg doesn't work when using start_queue_runners

### ISSUE THREAD

**Issue by KeithYin** [tensorflow/tensorflow#12545]
Today, i tried to use tfdbg to debug my tensorflow model, but i found that the run end CLI didn't show up when using start_queue_runners. here is my code.
```python
tf.global_variables_initializer().run()

tf.local_variables_initializer().run()

coord = tf.train.Coordinator()

threads = tf.train.start_queue_runners(sess=sess, coord=coord)

GLOBAL_STEP = 2

debug_sess = tf_debug.LocalCLIDebugWrapperSession(sess=sess)

try:
     while not coord.should_stop():
           model.train_n_iteration(sess=debug_sess, n=300, file_writer=file_writer)
           model.save_deeplabv3_ckpt(ckpt_path='ckpt/deeplabv3.ckpt', global_step=GLOBAL_STEP)
           GLOBAL_STEP += 1
except tf.errors.OutOfRangeError:
      print('num epoch exceeds the limits')
   
except KeyboardInterrupt:
      print('key board interrupt')
    
finally:
     coord.request_stop()
     coord.join(threads=threads)
```

**Comment by caisq** [comment]
@KeithYin, to make sure I understand the issue: are you trying to debug runs of the queues, or runs of some other main training ops on the main thread? 

Also, `model` and `train_n_iteration` seems to be custom (non-tensorflow) class and method. Can you point me to the code so I can see how uses `sess`?

**Comment by KeithYin** [comment]
@caisq Thanks for responding, I found a bug in my `train_n_iteration` code, i use the `tf.get_default_sesstion()` instead within `train_n_iteration`, that is why the *run end CLI* didn't show up.

Thanks again.
