### ISSUE TITLE
Error in installation guide for windows -- should use cuDNN v6.0 with tensorflow v1.3.0

### ISSUE THREAD

**Issue by VividNote** [tensorflow/tensorflow#12543]
In the installation guide for windows https://www.tensorflow.org/install/install_windows, where it says 'Requirements to run TensorFlow with GPU support' and 'cuDNN v5.1'.

Actually using cnDNN v5.1 will not work. Instead cnDNN v6.0 works.
This error would cause great waste of time for newbees. Please update the doc. Thanks.

**Comment by Edwin222** [comment]
## This is installation Window 10

This link is help you
https://nitishmutha.github.io/tensorflow/2017/01/22/TensorFlow-with-gpu-for-windows.html

And I have a question to you.

I want to fix the documents. But, I don't know where is fix document. I see two documents in website and github. What document should I fix? Please comment me. Thank you.

**Comment by jubjamie** [comment]
There is already an open issue for this at #11784

**Comment by andydavis1** [comment]
Closing as dup
