### ISSUE TITLE
[[Node: pool_3 = AvgPoolT=DT_FLOAT, data_format="NHWC", ksize=[1, 8, 8, 1], padding="VALID", strides=[1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/cpu:0"]]

### ISSUE THREAD

**Issue by tikamsingh** [tensorflow/tensorflow#12555]
iOS App - I have changes All the file name and Size , but still getting below error.

Source Code URL:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/ios/camera

Changes Code : const int wanted_input_width = 229;
const int wanted_input_height = 229;
const int wanted_input_channels = 3;
const float input_mean = 128.0f;
const float input_std = 128.0f;
const std::string input_layer_name = "Mul";
const std::string output_layer_name = "final_result";

computed output size would be negative
[[Node: pool_3 = AvgPoolT=DT_FLOAT, data_format="NHWC", ksize=[1, 8, 8, 1], padding="VALID", strides=[1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/cpu:0"]]

Please suggest what we are doing wrong .
In build pb and txt are working fine (imagenet_comp_graph_label_strings.txt, tensorflow_inception_graph.pb)

but created new pb and .txt is not working(rounded_graph.pb and retrained_labels.txt).
Note: I also rename the pb and txt file ,

**Comment by andydavis1** [comment]
@petewarden, @andrewharp can you comment on this?

**Comment by tikamsingh** [comment]
My Mistake, Fixed Issue.
