### ISSUE TITLE
MonitoredTrainingSession can't add summary and checkpoint hook

### ISSUE THREAD

**Issue by luvwinnie** [tensorflow/tensorflow#12556]
I trying to add summary and checkpoint to my distributed tensorflow training with custom data 

<pre>summary_hook = tf.train.SummarySaverHook(save_secs=600,output_dir=FLAGS.log_dir,summary_op=summary_op)
checkpoint_hook = tf.train.CheckpointSaverHook(save_steps=test_timing,checkpoint_dir=FLAGS.log_dir,saver=saver)
with tf.train.MonitoredTrainingSession(server.target,is_chief=is_chief,hooks=[sync_replicas_hook,summary_hook,checkpoint_hook],config=sess_config) as sess:</pre>

with above I can't run the sess with error of below
<pre>2017-08-24 19:38:31.250556: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1,13] has negative dimensions
2017-08-24 19:38:31.250633: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1,13] has negative dimensions
      [[Node: mfcc_input = Placeholder[dtype=DT_FLOAT, shape=[?,13], _device="/job:worker/replica:0/task:0/gpu:0"]()]]
2017-08-24 19:38:31.251688: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1,13] has negative dimensions
2017-08-24 19:38:31.251734: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1,13] has negative dimensions
      [[Node: mfcc_input = Placeholder[dtype=DT_FLOAT, shape=[?,13], _device="/job:worker/replica:0/task:0/gpu:0"]()]]
2017-08-24 19:38:31.253478: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1,3] has negative dimensions
2017-08-24 19:38:31.253522: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1,3] has negative dimensions
      [[Node: labels = Placeholder[dtype=DT_INT32, shape=[?,3], _device="/job:worker/replica:0/task:0/gpu:0"]()]]</pre>

how ever if I run without the summary and checkpoint hook it just work fine....
I want to specify which timing and which directory to view my summary and save the checkpoint.
Does anyone have an idea how to solve this problem?

**Comment by kinsumliu** [comment]
[This ](https://github.com/tensorflow/tensorflow/issues/11367) could be useful.

If you provide your full code, the community can provide more help.

**Comment by luvwinnie** [comment]
here is my full source:
info:
4 Nodes PC with Ubuntu 16.04LTS
1 parameter server and 3 worker
Parameter server specs:
2 GPUs
workers specs:
1: 1GPU,   2: 2 GPUs, 3: 1 GPU
The reason i use the 2Gpus for parameters server is because it has faster CPU for my code to process the queue input pipeline faster.
<pre>
`'''
192.168.1.7$ python example.py --job-name="ps" --task_index=0 
192.168.1.2$ python example.py --job-name="worker" --task_index=0 
192.168.1.8$ python example.py --job-name="worker" --task_index=1 
192.168.1.9$ python example.py --job-name="worker" --task_index=2 

reference from ischlag.github.io
'''
from __future__ import print_function
import os
#os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
from os import path
import tensorflow as tf
import numpy as np
import argparse
import time
import sys
import gzip

#cluster specification
parameter_servers = ["192.168.1.7:2223"]
workers = ["192.168.1.2:2223",
           "192.168.1.8:2223",
           "192.168.1.9:2223"]

cluster = tf.train.ClusterSpec({"ps": parameter_servers, "worker": workers})

# input flags
tf.app.flags.DEFINE_string("job_name", "", "Either 'ps' or 'worker'")
tf.app.flags.DEFINE_integer("task_index", 0, "Index of task within the job")
tf.app.flags.DEFINE_string(
    "log_dir", "lastest_train_log/sound_classifier/", """Log directory to view tensorboard""")
tf.app.flags.DEFINE_integer(
    "batch_size", 1024, """batch size to train [default:1024]""")
tf.app.flags.DEFINE_integer("epoch", 10, """epoch size [default:10]""")
tf.app.flags.DEFINE_integer(
    "test_timing_point", 512, """set a testing interval [default:512]""")
FLAGS = tf.app.flags.FLAGS

# start a server for a specific task
if FLAGS.job_name == "ps":
    os.environ['CUDA_VISIBLE_DEVICES'] = '1'
    server = tf.train.Server(cluster, 
                        job_name=FLAGS.job_name,
                        task_index=FLAGS.task_index)
else:
    server = tf.train.Server(cluster, 
                        job_name=FLAGS.job_name,
                        task_index=FLAGS.task_index)
#input config
num_input = 13
num_classes = 3
h_layer_units = 512
number_of_h_layer = 6
test_timing_point = 512
learning_rate = 1E-4

if FLAGS.job_name == "ps":
    print("calling join to serve")
    server.join()
elif FLAGS.job_name == "worker":

#-----function definition-------
    def extract_data_set(filename, batch_size, shuffle_batch=False,name=None):
        filename_queue = tf.train.string_input_producer([filename])
        reader = tf.TextLineReader()
        key, value = reader.read(filename_queue)
        record_default = [[1], [1.0], [1.0], [1.0], [1.0], [1.0], [
            1.0], [1.0], [1.0], [1.0], [1.0], [1.0], [1.0], [1.0]]
        labels, mfcc1, mfcc2, mfcc3, mfcc4, mfcc5, mfcc6, mfcc7, mfcc8, mfcc9, mfcc10, mfcc11, mfcc12, mfcc13 = tf.decode_csv(
            value, record_defaults=record_default)
        mfcc_features = tf.stack([mfcc1, mfcc2, mfcc3, mfcc4, mfcc5,
                                mfcc6, mfcc7, mfcc8, mfcc9, mfcc10, mfcc11, mfcc12, mfcc13])
        labels = tf.one_hot(labels,depth=3,dtype=tf.int32,name="labels_hot")
        labels_batch, mfcc_features_batch = tf.train.batch(
            [labels, mfcc_features], batch_size=batch_size, allow_smaller_final_batch=True)
        return labels_batch, mfcc_features_batch

    def hidden_layer(input, size_in, size_out, name="hidden_layer",reuse=False):
        with tf.name_scope(name):
            w = tf.Variable(tf.truncated_normal([size_in,size_out],stddev=0.1),name="W")
            b = tf.Variable(tf.constant(0.1,shape=[size_out]),name="B")
            act = tf.nn.tanh(tf.add(tf.matmul(input, w), b))
            tf.summary.histogram("weights", w)
            tf.summary.histogram("bias", b)
            tf.summary.histogram("activations", act)
            return act


    def fully_connected_layer(input, size_in, size_out, name="fc",reuse=False):
        with tf.name_scope(name):
            w = tf.Variable(tf.truncated_normal(shape=[size_in,size_out],stddev=0.1),name="W")
            b = tf.Variable(tf.constant(0.1,shape=[size_out]),name="B")
            act = tf.add(tf.matmul(input, w), b)
            tf.summary.histogram("weights", w)
            tf.summary.histogram("bias", b)
            tf.summary.histogram("activations", act)
            return act
#-------start program------------
    print("calling worker")
    with tf.device("/job:ps/task:0"):
        print("Calculating data size...")
        with gzip.open('csv_files/mfcc_combine_train_shuffled.gz') as f:
            text = f.readlines()
            size1 = len(text)
            print("train:{}".format(size1))
        with gzip.open('csv_files/mfcc_combine_test_shuffled.gz') as f:
            text = f.readlines()
            size2 = len(text)
            print("train:{}".format(size2))


        del text
        test_timing = (size2 / FLAGS.batch_size) / \
            (size1 / FLAGS.batch_size / FLAGS.test_timing_point)
        print("test timing:{}".format(test_timing))
        steps = size1 / FLAGS.batch_size
        print("steps:{}".format(steps))
    with tf.device("/job:ps/task:0"):
        train_labels_batch, train_mfcc_batch = extract_data_set(
            "csv_files/mfcc_combine_train_shuffled.csv", FLAGS.batch_size,"train")
        test_labels_batch, test_mfcc_batch = extract_data_set(
            "csv_files/mfcc_combine_test_shuffled.csv", FLAGS.batch_size,"test")

    # def sound_classifier_model(learning_rate, number_of_h_layer, h_layer_units, hparam):
        # tf.reset_default_graph()
    #saver = tf.train.Saver(sharded=True)
    
    # Between-graph replication model
    with tf.device(tf.train.replica_device_setter(worker_device="/job:worker/task:%d" %FLAGS.task_index,cluster=cluster)):
        is_chief = (FLAGS.task_index == 0)
        global_step = tf.get_variable('global_step', [], 
                                      initializer = tf.constant_initializer(0),dtype=tf.int32)
        # global_step = tf.Variable(0,name='global_step')
        #global_step=tf.get_variable('global_step', shape=[], initializer=tf.zeros_initializer(), dtype=tf.int32, trainable=False)
        x = tf.placeholder(tf.float32,shape=[None,num_input],name="mfcc_input")
        y = tf.placeholder(tf.int32,shape=[None,num_classes],name="labels")
        is_training = tf.placeholder(dtype=bool, shape=(), name="is_training")
        q_selector = tf.cond(is_training,lambda:[train_mfcc_batch,train_labels_batch],lambda:[test_mfcc_batch,test_labels_batch])

        h = []
        h.append(hidden_layer(x,num_input,h_layer_units))
        for i in range(number_of_h_layer):
            h.append(hidden_layer(h[i],h_layer_units,h_layer_units))

        output = fully_connected_layer(h[number_of_h_layer],h_layer_units,num_classes)
        saver = tf.train.Saver()
        with tf.name_scope("x-entropy"):
            xent = tf.reduce_mean(
            tf.nn.softmax_cross_entropy_with_logits(
                    logits=output, labels=y), name="x-entropy")

        with tf.name_scope("train"):
            grad_op = tf.train.AdamOptimizer(learning_rate)
            rep_op = tf.train.SyncReplicasOptimizer(grad_op,
                                                    replicas_to_aggregate=len(workers),
                                                    total_num_replicas=len(workers))
            train_op = rep_op.minimize(xent,global_step=global_step)
            sync_replicas_hook = rep_op.make_session_run_hook(is_chief)
            # grads = rep_op.compute_gradients(xent)
            # apply_gradients_op = rep_op.apply_gradients(grads,global_step=global_step)
            # with tf.control_dependencies([apply_gradients_op]):
                # train_op=tf.identity(xent,name='train_op')
            # train_step = rep_op.minimize(xent,global_step=global_step,aggregation_method=tf.AggregationMethod.ADD_N)
        init_token_op = rep_op.get_init_tokens_op()
        chief_queue_runner = rep_op.get_chief_queue_runner()
        with tf.name_scope("accuracy"):
            correct_prediction = tf.equal(tf.argmax(output,1),tf.argmax(y,1))
            accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))

        tf.summary.scalar("x-entropy", xent)
        tf.summary.scalar("accuracy",accuracy)
        
        summary_op = tf.summary.merge_all()
        global_init_op = tf.global_variables_initializer()
        local_init_op = tf.local_variables_initializer()
        
    #------------prepare for session------------
    # coord = tf.train.Coordinator()
    print("creating Supervisor...")
    # sv = tf.train.Supervisor(is_chief=is_cheif,
    #                         global_step=global_step,
    #                         saver = saver,
    #                         logdir=FLAGS.log_dir)
    print("making config...")
    sess_config = tf.ConfigProto(allow_soft_placement=True,log_device_placement=True,device_filters=["/job:ps","/job:worker/task:%d"%FLAGS.task_index])
    begin_time = time.time()
    summary_hook = tf.train.SummarySaverHook(save_secs=600,output_dir=FLAGS.log_dir,summary_op=summary_op)
    checkpoint_hook = tf.train.CheckpointSaverHook(save_steps=test_timing,checkpoint_dir=FLAGS.log_dir,saver=saver)

    #---------------training session--------------
    print("waiting for session prepare....")
    with tf.train.MonitoredTrainingSession(server.target,is_chief=is_chief,hooks=[sync_replicas_hook,summary_hook,checkpoint_hook],config=sess_config) as sess:
        while not sess.should_stop():
            '''
            # is cheif
            if FLAGS.task_index == 0:
                sv.start_queue_runners(sess,[cheif_queue_runner])
                sess.run(init_token_op)
            '''
            print("in session")
            # while not sv.should_stop():
                # coord = tf.train.Coordinator()
            # sess.run(tf.global_variables_initializer())
            # sess.run(tf.local_variables_initializer())
            # coord = tf.train.Coordinator()
            # if FLAGS.task_index == 0:
            tf.train.start_queue_runners(sess=sess)
             sess.run(init_token_op)
            # sv.start_queue_runners(sess=sess)
            with tf.device("/job:ps/task:0/cpu:0"):
                f = open(FLAGS.log_dir + "accuracy_" + str(learning_rate) +
                        "_with_" + str(number_of_h_layer) + "layers", "w+")
                print("loading data to queue....")
            
            print("done loading to queue")
            print("start adding summary")
            with tf.device("/job:ps/task:0/cpu:0"):
                f = open(FLAGS.log_dir+"accuracy_"+str(learning_rate)+"_with_"+str(number_of_h_layer)+"layers","w+")

                # writer = tf.summary.FileWriter(FLAGS.log_dir,graph=tf.get_default_graph())
                # writer = tf.summary.FileWriter(FLAGS.log_dir + "lr_%.0E layers:%d"%(learning_rate,6))
                # writer.add_graph(sess.graph)
                #perform training cycles
                start_time = time.time()

            print("start training")
            for i in range(steps):
                print("read data")
                mfcc_batch,label_batch = sess.run(q_selector,feed_dict={is_training:True})
                # label_batch = sess.run(tf.one_hot(y_batch,depth=3,dtype=tf.int32,name="labels"))
                [_,loss,glob_step,train_accuracy] = sess.run([train_op,xent,global_step,accuracy],feed_dict={x:mfcc_batch,y:label_batch})
                # [train_accuracy,s] = sess.run([accuracy,summary_op],feed_dict={x:mfcc_batch,y:label_batch})
                print("done")
                elapsed = round(time.time()-start_time,2)
                sys.stdout.write("\r")
                sys.stdout.write("learning_rate:{0},{1} layers , training:{2}/{3} , train_accuracy:{4} [elapsed_time:{5:.2f}] ".format(learning_rate,number_of_h_layer,i,steps,train_accuracy,elapsed))
                sys.stdout.flush()
                # writer.add_summary(summary,i)
                print("before train")
                # sess.run(global_step,init_token_op,chief_queue_runner)
                # sess.run(train_op,xent)
                print("after train")
                if i != 0 and i % test_timing == 0:
                    # saver.save(sess, os.path.join(FLAGS.log_dir, "model.ckpt"), i)
                    test_time += 1
                    for j in range(test_timing):
                        mfcc_batch,y_batch = sess.run(q_selector,feed_dict={is_training:False})
                        test_label = sess.run(tf.one_hot(y_batch,depth=3,dtype=tf.int32,name="test_label"))
                        test_accuracy = accuracy.eval(feed_dict={x:mfcc_batch,y:test_label})
                        sys.stdout.write("\r")
                        sys.stdout.write("{}layers: test_num:{} testing:{} test_accuracy:{}".format(number_of_h_layer,test_time,j,test_accuracy))
                        sys.stdout.flush()
                        with tf.device("/job:ps/task:0/cpu:0"):
                            f.write("{}layers: test_num:{} testing:{} test_accuracy:{}\n".format(number_of_h_layer,test_time,j,test_accuracy))
                            f.flush()

    f.write("total_training for lr {},{}layers time:{} minutes".format(learning_rate,number_of_h_layer,((time.time()-start_time)/60.0)))
    f.flush()
    f.close()
    print("-----%s minutes ------"%((time.time()-start_time)/60.0))
#    sv.stop()
    print("Done!")
`
</pre>

I run as the code provided comments in respective IP PC but it shows the error as previous

**Comment by kinsumliu** [comment]
I don't have a definite answer yet. I suspect that there is some problem with the data feeding mechanism in your code which will cause this error. You mention that it runs fine if you disable them. Have you checked that the data really goes in and some meaningful training is done?

Here is my suggestion:

1. MonitoredTrainingSession should create a Coordinator which start the queue runners. tf.train.start_queue_runners(sess=sess) looks duplicate to me and if you start the queue runners twice, I am not sure what will happen. Refer to [this](https://stackoverflow.com/questions/43245231/how-do-monitored-training-sessions-work) for what MonitoredTrainingSession can do

2. You can define the size for the placeholder. But as I understand it, it should not be the problem. No harm in trying :)

3. I dont know what these are doing:
```
with tf.device("/job:ps/task:0/cpu:0"):
                f = open(FLAGS.log_dir + "accuracy_" + str(learning_rate) +
                        "_with_" + str(number_of_h_layer) + "layers", "w+")
                print("loading data to queue....")
```
If you want to log accuracy, the worker (not ps) should log accuracy since the worker is doing the training.

4. Have you tried the non-distributed version of your code, does it work?

**Comment by kinsumliu** [comment]
```
import tensorflow as tf

filename_queue = tf.train.string_input_producer(["file0.csv", "file1.csv"])

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[1], [1], [1], [1], [1]]
col1, col2, col3, col4, col5 = tf.decode_csv(
    value, record_defaults=record_defaults)
features = tf.stack([col1, col2, col3, col4])
tf.summary.scalar("label", col5)
global_step = tf.get_variable('global_step', [],initializer = tf.constant_initializer(0),dtype=tf.int32)

server = tf.train.Server.create_local_server()
summary_op = tf.summary.merge_all()
summary_hook = tf.train.SummarySaverHook(save_secs=1,output_dir='.',summary_op=summary_op)

with tf.train.MonitoredTrainingSession(master=server.target, hooks=[summary_hook], is_chief=True) as sess:
#     tf.train.start_queue_runners(sess=sess)

    for i in range(30):
    # Retrieve a single instance:
        example, label, step = sess.run([features, col5, global_step])
        print example, label, step
```
Can you try my code in your environment?

1. Create two csv `file0.csv`, `file1.csv`. Each entry is just 5 ints separated by ",". (Example is 1,2,3,4,5)
2. Run the code with `tf.train.start_queue_runners(sess=sess)` commented out and not commented out.
3. Check whether `events.out.tfevents.XXXXXX` is created in the same directory.

**Comment by luvwinnie** [comment]
I'm actually trying to create 2 queues, one for training another one for testing after the test_timing for the file.

How does the string_input_producer really work when two files is given?
What I'm trying to do is :
[Queue 1(Train)  from csv file 1 ]   ,    [Queue 2(Test)   from csv file 2]
using these two Queue for training and testing within a program.


I tried your code with below
<pre>
`'''
pc-01$ python example.py --job-name="ps" --task_index=0 
pc-02$ python example.py --job-name="worker" --task_index=0 
pc-03$ python example.py --job-name="worker" --task_index=1 
pc-04$ python example.py --job-name="worker" --task_index=2 

reference from ischlag.github.io
'''
from __future__ import print_function
import os
#os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
from os import path
import tensorflow as tf
import numpy as np
import argparse
import time
import sys
import gzip

#cluster specification
parameter_servers = ["192.168.1.7:2223"]
workers = ["192.168.1.2:2223",
           "192.168.1.8:2223",
           "192.168.1.9:2223"]

cluster = tf.train.ClusterSpec({"ps": parameter_servers, "worker": workers})

# input flags
tf.app.flags.DEFINE_string("job_name", "", "Either 'ps' or 'worker'")
tf.app.flags.DEFINE_integer("task_index", 0, "Index of task within the job")
tf.app.flags.DEFINE_string(
    "log_dir", "lastest_train_log/sound_classifier/", """Log directory to view tensorboard""")
tf.app.flags.DEFINE_integer(
    "batch_size", 1024, """batch size to train [default:1024]""")
tf.app.flags.DEFINE_integer("epoch", 10, """epoch size [default:10]""")
tf.app.flags.DEFINE_integer(
    "test_timing_point", 512, """set a testing interval [default:512]""")
FLAGS = tf.app.flags.FLAGS

# start a server for a specific task
if FLAGS.job_name == "ps":
    os.environ['CUDA_VISIBLE_DEVICES'] = '1'
    server = tf.train.Server(cluster, 
                        job_name=FLAGS.job_name,
                        task_index=FLAGS.task_index)
else:
    server = tf.train.Server(cluster, 
                        job_name=FLAGS.job_name,
                        task_index=FLAGS.task_index)
#input config
num_input = 13
num_classes = 3
h_layer_units = 512
number_of_h_layer = 6
test_timing_point = 512
learning_rate = 1E-4

if FLAGS.job_name == "ps":
    print("calling join to serve")
    server.join()
elif FLAGS.job_name == "worker":
    
    filename_queue = tf.train.string_input_producer(["csv_files/mfcc_combine_train_shuffled.csv","csv_files/mfcc_combine_test_shuffled.csv"])
    reader = tf.TextLineReader()
    key, value = reader.read(filename_queue)
    record_default = [[1.0] for _ in range(14)]
    record_default[0] = [1]
    labels, mfcc1, mfcc2, mfcc3, mfcc4, mfcc5, mfcc6, mfcc7, mfcc8, mfcc9, mfcc10, mfcc11, mfcc12, mfcc13 = tf.decode_csv(value, record_defaults=record_default)
    mfcc_features = tf.stack([mfcc1, mfcc2, mfcc3, mfcc4, mfcc5,
                            mfcc6, mfcc7, mfcc8, mfcc9, mfcc10, mfcc11, mfcc12, mfcc13])
    # labels = tf.one_hot(labels,depth=3,dtype=tf.int32)
    tf.summary.scalar("label",labels)
    global_step = tf.get_variable('global_step',[],initializer=tf.constant_initializer(0),dtype=tf.int32)
    
    # server = tf.train.Server.create_local_server()
    summary_op = tf.summary.merge_all()
    summary_hook = tf.train.SummarySaverHook(save_secs=1,output_dir='./tmp_test',summary_op=summary_op)
    previous=[]
    with tf.train.MonitoredTrainingSession(master=server.target,hooks=[summary_hook],is_chief=True) as sess:
        tf.train.start_queue_runners(sess=sess)
        for i in range(1024):
            example,label,step = sess.run([mfcc_features,labels,global_step])
            if set(previous) == set(example):
                print("it's same!")
                sys.exit()
            else:
                previous = example
                print(example,label,step)
`
</pre>

this code work fine when the `tf.one_hot(labels,depth=3,dtype=tf.int32)` is not used.
however if I include the tf.one_hot transformation it show the error that I'm giving wrong op u'label'
<pre>
`Caused by op u'label', defined at:
  File "sound_classifier_distributed_test_input.py", line 74, in <module>
    tf.summary.scalar("label",labels_hot)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/summary.py", line 129, in scalar
    tags=scope.rstrip('/'), values=tensor, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 265, in _scalar_summary
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): tags and values not the same shape: [] != [3] (tag 'label')
         [[Node: label = ScalarSummary[T=DT_INT32, _device="/job:ps/replica:0/task:0/cpu:0"](label/tags, one_hot)]]
         [[Node: Merge/MergeSummary_S13 = _Recv[client_terminated=false, recv_device="/job:worker/replica:0/task:2/cpu:0", send_device="/job:ps/replica:0/task:0/cpu:0", send_device_incarnation=-9152570865690878554, tensor_name="edge_72_Merge/MergeSummary", tensor_type=DT_STRING, _device="/job:worker/replica:0/task:2/cpu:0"]()]]`
</pre>

But I'm trying to make the label to be one_hot for classification.
How am I suppose to:
1) Read data from csv file ---> data structure [label , feature , .... feature]
2) Convert label to one_hot
3) Batch up the one_hot labels and features to 1024 Batch size?

**Comment by luvwinnie** [comment]
@kinsumliu btw the code just work fine with and without `tf.train.start_queue_runners(sess=sess)`

3 workers run and events.out.tfevents.XXXXXX is created in same directory.....

**Comment by kinsumliu** [comment]
`tf.one_hot` return a tensor which is not a scalar.  `tf.summary.tensor_summary` this should work

**Comment by kinsumliu** [comment]
For the training and testing, you can run your program twice. First time training + checkpoint the model. Second time load up the checkpoint and do the inference on the testing data to get accuracy.

I believe the issues you faced is not related to the bug inside tensorflow. So stackoverflow should be a better place for your problem.

**Comment by luvwinnie** [comment]
However with the graph I build for training.

<pre>with tf.device(tf.train.replica_device_setter(worker_device="/job:worker/task:%d" %FLAGS.task_index,cluster=cluster)):
        is_chief = (FLAGS.task_index == 0)
        global_step = tf.get_variable('global_step',[],initializer=tf.constant_initializer(0),dtype=tf.int32)
        x = tf.placeholder(tf.float32,shape=[None,num_input],name="mfcc_input")
        y = tf.placeholder(tf.int32,shape=[None,num_classes],name="labels")
        # is_training = tf.placeholder(dtype=bool, shape=(), name="is_training")
        # q_selector = tf.cond(is_training,lambda:[train_mfcc_batch,train_labels_batch],lambda:[test_mfcc_batch,test_labels_batch])

        h = []
        h.append(hidden_layer(x,num_input,h_layer_units))
        for i in range(number_of_h_layer):
            h.append(hidden_layer(h[i],h_layer_units,h_layer_units))

        output = fully_connected_layer(h[number_of_h_layer],h_layer_units,num_classes)
        saver = tf.train.Saver()

        with tf.name_scope("x-entropy"):
            xent = tf.reduce_mean(
            tf.nn.softmax_cross_entropy_with_logits(
                    logits=output, labels=y), name="x-entropy")

        with tf.name_scope("train"):
            grad_op = tf.train.AdamOptimizer(learning_rate)
            rep_op = tf.train.SyncReplicasOptimizer(grad_op,
                                                    replicas_to_aggregate=len(workers),
                                                    total_num_replicas=len(workers))
            train_op = rep_op.minimize(xent,global_step=global_step)
            sync_replicas_hook = rep_op.make_session_run_hook(is_chief)
            
        init_token_op = rep_op.get_init_tokens_op()
        chief_queue_runner = rep_op.get_chief_queue_runner()
        with tf.name_scope("accuracy"):
            correct_prediction = tf.equal(tf.argmax(output,1),tf.argmax(y,1))
            accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))

        tf.summary.scalar("x-entropy", xent)
        tf.summary.scalar("accuracy",accuracy)
        
        summary_op = tf.summary.merge_all()
        global_init_op = tf.global_variables_initializer()
        local_init_op = tf.local_variables_initializer()</pre>

It still shows the following error 
`2017-08-25 16:04:20.162666: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1,13] has negative dimensions
2017-08-25 16:04:20.162748: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1,13] has negative dimensions
         [[Node: mfcc_input = Placeholder[dtype=DT_FLOAT, shape=[?,13], _device="/job:worker/replica:0/task:0/gpu:0"]()]]
2017-08-25 16:04:20.163809: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1,13] has negative dimensions
2017-08-25 16:04:20.163855: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1,13] has negative dimensions
         [[Node: mfcc_input = Placeholder[dtype=DT_FLOAT, shape=[?,13], _device="/job:worker/replica:0/task:0/gpu:0"]()]]
2017-08-25 16:04:20.165598: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1,3] has negative dimensions
2017-08-25 16:04:20.165643: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1,3] has negative dimensions
         [[Node: labels = Placeholder[dtype=DT_INT32, shape=[?,3], _device="/job:worker/replica:0/task:0/gpu:0"]()]]`

which I asked at the 1st comment

**Comment by luvwinnie** [comment]
I build up my code step by step. While the code to the `xent` calculation it still works fine.
But when I added the definition of the train_op as below:
<pre>
grad_op = tf.train.AdamOptimizer(learning_rate=learning_rate)
rep_op = tf.train.SyncReplicasOptimizer(grad_op,
                                                replicas_to_aggregate=3,
                                                total_num_replicas=3)
train_op = rep_op.minimize(xent,global_step=global_step)
sync_replicas_hook = rep_op.make_session_run_hook(is_chief)
init_token_op = rep_op.get_init_tokens_op()
chief_queue_runner = rep_op.get_chief_queue_runner()
</pre>
It's start show the error message getting the -1 negative dimension
looks like this issue have been open at  #11823
Is this the tensorflow version bugs?

**Comment by kinsumliu** [comment]
There are a few wrong things in your code, especially for your data feeding mechanism. So your first session run will fetch the data but `xent` cannot be computed so `tf.summary.scalar("x-entropy",xent)` causes problem. 

Check out my code below. It should work. Note that I use `train_op = tf.train.GradientDescentOptimizer(1.0).minimize(xent, global_step=global_step)` because I am doing it on a single machine. After you change to use `SyncReplicasOptimizer`, first turn off training to see the data feeding works by using `loss,glob_step= sess.run([xent,global_step])`.

```
from __future__ import print_function
import os
from os import path
import tensorflow as tf
import numpy as np
import argparse
import time
import sys
import gzip
import math

# input flags
tf.app.flags.DEFINE_string("job_name", "", "Either 'ps' or 'worker'")
tf.app.flags.DEFINE_integer("task_index", 0, "Index of task within the job")
tf.app.flags.DEFINE_string(
    "log_dir", "lastest_train_log/sound_classifier/", """Log directory to view tensorboard""")
tf.app.flags.DEFINE_integer(
    "batch_size", 1024, """batch size to train [default:1024]""")
tf.app.flags.DEFINE_integer("epoch", 10, """epoch size [default:10]""")
tf.app.flags.DEFINE_integer(
    "test_timing_point", 512, """set a testing interval [default:512]""")
FLAGS = tf.app.flags.FLAGS

#input config
num_input = 13
num_classes = 3
h_layer_units = 512
number_of_h_layer = 6
test_timing_point = 512
learning_rate = 1E-4
batch_size = 1

#-----function definition-------
def readData():
    filename_queue = tf.train.string_input_producer(["csv_files/mfcc_combine_train_shuffled.csv","csv_files/mfcc_combine_test_shuffled.csv"])
    reader = tf.TextLineReader()
    key, value = reader.read(filename_queue)
    record_default = [[1.0] for _ in range(14)]
    record_default[0] = [1]
    labels, mfcc1, mfcc2, mfcc3, mfcc4, mfcc5, mfcc6, mfcc7, mfcc8, mfcc9, mfcc10, mfcc11, mfcc12, mfcc13 = tf.decode_csv(value, record_defaults=record_default)
    mfcc_features = tf.stack([mfcc1, mfcc2, mfcc3, mfcc4, mfcc5,
                            mfcc6, mfcc7, mfcc8, mfcc9, mfcc10, mfcc11, mfcc12, mfcc13])
    labels1hot = tf.one_hot(labels,depth=3,dtype=tf.int32)
    labels_batch, mfcc_features_batch = tf.train.batch(
            [labels1hot, mfcc_features], batch_size=batch_size, allow_smaller_final_batch=True)
    return (mfcc_features_batch, labels_batch)

is_chief = True
global_step = tf.get_variable('global_step',[],initializer=tf.constant_initializer(0),dtype=tf.int32,trainable=False)
(x,y) = readData()
w1 = tf.Variable(tf.truncated_normal([num_input,512],stddev=0.1),name="W1")
b1 = tf.Variable(tf.constant(0.1,shape=[512]),name="B1")
act1 = tf.nn.tanh(tf.add(tf.matmul(tf.cast(x, tf.float32),w1),b1))

w2 = tf.Variable(tf.truncated_normal([512,512],stddev=0.1),name="W2")
b2 = tf.Variable(tf.constant(0.1,shape=[512]),name="B2")
act2 = tf.nn.tanh(tf.add(tf.matmul(act1,w2),b2))

w3 = tf.Variable(tf.truncated_normal([512,512],stddev=0.1),name="W3")
b3 = tf.Variable(tf.constant(0.1,shape=[512]),name="B3")
act3 = tf.nn.tanh(tf.add(tf.matmul(act2,w3),b3))

w4 = tf.Variable(tf.truncated_normal(shape=[512,3],stddev=0.1),name="W4")
b4 = tf.Variable(tf.truncated_normal(shape=[3],stddev=0.1),name="B4")
act4 = tf.add(tf.matmul(act3,w4),b4)

# #----loss----
xent = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits(
        logits=act4,labels=y),name="x-entropy")

# # ----train----
# grad_op = tf.train.AdamOptimizer(learning_rate=learning_rate)
# rep_op = tf.train.SyncReplicasOptimizer(grad_op,
#                                         replicas_to_aggregate=3,
#                                         total_num_replicas=3)
# train_op = rep_op.minimize(xent,global_step=global_step)

train_op = tf.train.GradientDescentOptimizer(1.0).minimize(xent, global_step=global_step)


# sync_replicas_hook = rep_op.make_session_run_hook(is_chief)
# init_token_op = rep_op.get_init_tokens_op()
tf.summary.scalar("x-entropy",xent)

server = tf.train.Server.create_local_server()
summary_op = tf.summary.merge_all()
summary_hook = tf.train.SummarySaverHook(save_secs=1,output_dir='.',summary_op=summary_op)
with tf.train.MonitoredTrainingSession(master=server.target,hooks=[summary_hook],is_chief=True) as sess:
    tf.train.start_queue_runners(sess=sess)
    for i in range(2):
        _,loss,glob_step= sess.run([train_op,xent,global_step])
        print (loss, glob_step)
```

**Comment by luvwinnie** [comment]
@kinsumliu Thanks you for taking time to solve the problem! It works with your code in single local PC! It seems like it is the problem with placeholder and feeding data. I will try to ask in [StackOverflow](https://stackoverflow.com/) and try not using the feed_dict. Thank you for help!

Since it is not a bug of tensorflow , closing this issue.

**Comment by kinsumliu** [comment]
@luvwinnie Good to know. If you have further problems related to this code, you can @ my username (LKS) in stackoverflow.
