### ISSUE TITLE
Usage of bit_casted_tensor() function with C++ api?(implementation on IOS)

### ISSUE THREAD

**Issue by Christ1992** [tensorflow/tensorflow#12575]
### Any tutorial on this bit_casted_tensor function?
I am building an app on IOS based on ios-tensorflow model. The model generated a tensor with type float. However, for my model, a unit8 format is required. So I want to transfer the tensor's format.

I found this, `bit_casted_tensor()`, maybe useful for directly transformation. But I when tried to use it in the code like the following,
`   tensorflow::TTypes<tensorflow::uint8>::Tensor a_new_tensor = bit_casted_tensor(image_tensor);` the issue `use of undeclared identifier 'bit_casted_tensor' ` always showed up.

According to reference, bit_casted_tensor function should use like this:

`TTypes< T, NDIMS >::ConstTensor bit_casted_tensor() const `

> Return the tensor data to an _Eigen::Tensor_ with the same size but a bitwise cast to the specified _dtype T_.
> 
> Using a bitcast is useful for move and copy operations. NOTE: this is the same as tensor() except a bitcast is allowed. 
[TF Reference Link](https://www.tensorflow.org/api_docs/cc/class/tensorflow/tensor#classtensorflow_1_1_tensor_1afced940422a1e726d9487cb3cb039630)

I am not sure if I use it correctly? Or it is due to the limited support of tensorflow function on IOS platform? 

## Keen for any kind of help !!

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
