### ISSUE TITLE
Attribute Error from Tensorboard.py following upgrade to v0.7.1 upgrade

### ISSUE THREAD

**Issue by McMDA** [tensorflow/tensorflow#1257]
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

### Environment info
Operating System:Ubuntu 14.0.4

If installed from binary pip package, provide:

1. Which pip package you installed.
sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl

2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.7.1
If installed from sources, provide the commit hash:

### Steps to reproduce
1.In the command prompt try to launch a tensorboard graph
2.
3.

### What have you tried?
1. I tried using the command      **tensorboard --logdir=/home/tattoo/Tabor_Stuff**
Previously for v0.6.0 the graph launched. However after installing v0.7.1 with the command above I get the following attribute error. Am I missing an install step or is this really an error?

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/tensorboard.py", line 117, in main
    multiplexer = event_multiplexer.AutoloadingMultiplexer(
AttributeError: 'module' object has no attribute 'AutoloadingMultiplexer'

**Comment by vrv** [comment]
Can you try uninstalling and re-installing TensorFlow?  That looks like a stale file (we no longer have AutoloadingMultiplexer).

**Comment by McMDA** [comment]
Hi Vijay,

How do I uninstall it?
I'm new to ubuntu.

Don

**Comment by facadev** [comment]
Yeah, re-installing fixed the problem. Just re-run the upgrade command.

**Comment by vrv** [comment]
pip uninstall tensorflow
pip uninstall protobuf
pip install url/to/the/tensorflow-...whl

**Comment by McMDA** [comment]
Hi Vijay,

Thanks for the tips.

I'm still getting the same error. Do I need to run these commands from a
particular directory?

Don

**Comment by McMDA** [comment]
Weird, I tried it again and I have it launch now. Thank you.

**Comment by McMDA** [comment]
We're good now. It's curious. Now I have to use the full path to the
tensorboard.py instead of simply the tensorboard --logdir=/stuff

**Comment by vrv** [comment]
Most likely you have a stale tensorboard.py in your /usr/local/bin dir (or some other bin path)

**Comment by scrawfor1** [comment]
Thank you Vijay.  I've been dealing with the same error after upgrade.  Tried 
pip uninstall tensorflow
pip uninstall protobuf
pip install url/to/the/tensorflow-...whl
but the problem persisted.  

Then tried 
pip uninstall tensorflow
pip uninstall protobuf
manually deleted tensorboard.py from /usr/local/bin
pip install url/to/the/tensorflow-...whl
tensorboard.py was recreated with the new tensorflow installation and the problem resolved.
