### ISSUE TITLE
No gradient for `cdf`, `sample` and other functions for several distributions in `tf.distributions`

### ISSUE THREAD

**Issue by lcnature** [tensorflow/tensorflow#12570]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary (pip)
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: CUDA 8.0 cuDNN 6
- **GPU model and memory**: nVIDIA K2100M, 2G
- **Exact command to reproduce**: See below
dist_par = tf.Variable(1.0)
dist = tf.distributions.Beta(dist_par,1.0)
print(tf.gradients(dist.cdf(0.5), dist_par))

>> [None]

The output says there is no gradient.

### Describe the problem
For several distributions such as `Beta` and `Gamma`, there is no gradient of their functions such as `cdf`, `log_cdf`, `sample` with respect to the parameters of these distributions. While gradients are provided for these functions of distributions such as `Normal` and `Laplace`.
I think theoretically the gradients should exist. And they are useful when people build a model in which samples drawn from these distributions as prior distributions are marginalized while the parameters of these distributions are optimized. It would be nice if they can be implemented
Thanks!

### Source code / logs
See above

**Comment by ali01** [comment]
We currently don't have anybody working on this. It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thanks!

**Comment by Thenerdstation** [comment]
I can work on this. It looks like you just need to add the gradient calculations here. https://github.com/tensorflow/tensorflow/blob/084d29e67a72e369958c18ae6abfe2752fcddcbf/tensorflow/python/ops/math_grad.py#L536 

I assume the issue is similar the reset of the distributions calculations. There's actually a todo in the code for this.

**Comment by lcnature** [comment]
@Thenerdstation Thanks a lot for help! I am not too familiar with the internal tensorflow code. A few other distributions seem to be marked TODO for their gradients as well.

**Comment by Thenerdstation** [comment]
Yeah I see that. I might have to make a few PRs to fix them all.

**Comment by Thenerdstation** [comment]
Well I see now why this gradient was put as a TODO.
https://www.wolframalpha.com/input/?i=derivative+with+respect+to++a+of+beta(x,+a,+b)

**Comment by lcnature** [comment]
Wow, that is much more complex than I thought

**Comment by stepelu** [comment]
Well, `sample` should be dealt with separately really, but for `log_cdf` please see 2.3 in:
https://arxiv.org/pdf/1509.01631.pdf
This should hopefully extend to non-log versions and to the Beta distribution.

**Comment by Thenerdstation** [comment]
Hey thanks for this!
Seeing how there is a lot of looping for the approximation, we might have to create a new op for this. Not sure on timeline but I'll keep at it.

**Comment by awav** [comment]
@Thenerdstation, do you know what's the status of that issue? :) 

I do like to find all these issues raised a long time ago, in time when you need them the most. But they are all forgotten...

**Comment by Thenerdstation** [comment]
I haven't worked on this in years haha.

I won't be able to work on this at this point, so if you wanna take it up go for it.

**Comment by Mossi8** [comment]
Hi, have there been any updates on this topic? I would find it very useful to use this distributions.

Thanks!

**Comment by sushreebarsa** [comment]
@lcnature  TensorFlow's tf.gradients function can be used to numerically approximate the gradients of these functions.
TF v 1.x is not actively supported and please check the migration [doc](https://www.tensorflow.org/guide/migrate). If you still have a concern we would request you to create a new ticket to get the right help. Thank you!
