### ISSUE TITLE
[Slim]No cross validation in inception?

### ISSUE THREAD

**Issue by micklexqg** [tensorflow/tensorflow#12595]
I run the code for fine tune inception in slim. but I find that only train split is used when training. so is there no  cross validation in inception?  how should I stop training(just at the max_steps)? what's validation split for? (evaluate the trained model?)

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
