### ISSUE TITLE
Feature request: QueueRunner for C++ API that initializes from queues and ops and start with ClientSession

### ISSUE THREAD

**Issue by dguerra** [tensorflow/tensorflow#12596]
Right now there is an implementation of QueueRunner in "tensorflow/cc/training/queue_runner.h". It's created from a QueueRunnerDef that is initialized with string names rather than queues and ops objects. QueueRunner's current implementation is also started by using the "Session" low level class rather than the newer "ClientSession" class.

**Comment by wt-huang** [comment]
@reedwm @yuefengz seems like there is a plan to change the implementation of QueueRunner from queues and ops. Could you take a look at this?

**Comment by reedwm** [comment]
Unassigning myself since I don't know anything about queue runners. @yuefengz, can you take a look, or unassign yourself and leave this as contributions welcome?

**Comment by yuefengz** [comment]
The QueueRunner is deprecated. It possible for you to use `tf.data` for input processing?

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tilakrayal** [comment]
@dguerra,
This API was designed for TensorFlow v1. Continue reading for details on how to migrate from this API to a native TensorFlow v2 equivalent. See the [TensorFlow v1 to TensorFlow v2 migration guide](https://www.tensorflow.org/guide/migrate) for instructions on how to migrate the rest of your code

QueueRunners are not compatible with eager execution. Instead, please use [tf.data](https://www.tensorflow.org/guide/data) to get data into your model.
https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/QueueRunner
Thank you!
