### ISSUE TITLE
Impossible to change variable inside checkpoint

### ISSUE THREAD

**Issue by dimaxano** [tensorflow/tensorflow#12605]
I have a checkpoint file and I want to change (increase) shapes of some Variables from this checkpoint.
It seems to be impossible using tf.assign 
Tried to use `tf.assign()`:

    `for var in tf.global_variables():
         if var.name == "22-convolutional/biases:0":
             assign = tf.assign(var, a, validate_shape=False)
             sess.run(assign)`

And then, when I am trying to execute 

`sess.run(tf.global_variables_initializer())`

I have an error

`Assign requires shapes of both tensors to match. lhs shape= [1,1,1024,60] rhs shape= [1,1,1024,55]
[[Node: 22-convolutional/kernel/Adam_1/Assign = Assign[T=DT_FLOAT, 
_class=["loc:@22-convolutional/kernel"], use_locking=true, validate_shape=true, 
_device="/job:localhost/replica:0/task:0/cpu:0"](22-convolutional/kernel/Adam_1, zeros_51)]]`

So, is it really impossible in TF? Could it be a feature request?

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by dimaxano** [comment]
I did it [here](https://stackoverflow.com/questions/45885504/cannot-assign-values-with-different-shapes-in-tensorflow)

**Comment by andydavis1** [comment]
I see a response on your stackoverflow question.
