### ISSUE TITLE
Android Demo - SpeechActivity - Fatal Exception

### ISSUE THREAD

**Issue by njflabs** [tensorflow/tensorflow#12618]
Samsung Galaxy J1 - Android ver. 5.1.1

08-26 11:56:55.226: I/TensorFlowInferenceInterface(14094): Model load took 41ms, TensorFlow version: 1.3.0
08-26 11:56:55.226: I/TensorFlowInferenceInterface(14094): Successfully loaded model from 'file:///android_asset/conv_actions_frozen.pb'
08-26 11:56:55.231: D/AndroidRuntime(14094): Shutting down VM
08-26 11:56:55.231: E/AndroidRuntime(14094): **FATAL EXCEPTION**: main
08-26 11:56:55.231: E/AndroidRuntime(14094): Process: org.tensorflow.demo, PID: 14094
08-26 11:56:55.231: E/AndroidRuntime(14094): java.lang.NoSuchMethodError: **No virtual method requestPermissions**([Ljava/lang/String;I)V in class Lorg/tensorflow/demo/SpeechActivity; or its super classes (declaration of 'org.tensorflow.demo.SpeechActivity' appears in /data/app/org.tensorflow.demo-1/base.apk)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at org.tensorflow.demo.SpeechActivity.requestMicrophonePermission(SpeechActivity.java:158)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at org.tensorflow.demo.SpeechActivity.onCreate(SpeechActivity.java:153)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at android.app.Activity.performCreate(Activity.java:6609)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3243)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at android.app.ActivityThread.access$1000(ActivityThread.java:218)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at android.os.Looper.loop(Looper.java:145)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at android.app.ActivityThread.main(ActivityThread.java:6917)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at java.lang.reflect.Method.invoke(Native Method)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at java.lang.reflect.Method.invoke(Method.java:372)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
08-26 11:56:55.231: E/AndroidRuntime(14094): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by ali01** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by njflabs** [comment]
this error occurs from installed apk both from github and jeeves repositories. i would guess its the same apk, latest version of apk.
It will give the above error when trying to load. actually all 4 activities throw dofferent fatal errors and do not load. i copied the error output from android monitor tool in sdk.

**Comment by njflabs** [comment]
it is running on:
Samsung Galaxy J1 - Android ver. 5.1.1
when clicking on the TF Speech launch icon, it does not load and android pops a dialog "Unfortunately,  Tensor Flow demo has stopped."

**Comment by petewarden** [comment]
This may be a problem with old versions of Android, since we're only testing on more recent OS's. We should have better version checking, but it's unlikely to be something we get to in the near term, so closing for now unless somebody external wants to take this on?
