### ISSUE TITLE
tf.gfile.FastGFile can't read french path

### ISSUE THREAD

**Issue by micklexqg** [tensorflow/tensorflow#12611]
tf.gfile.FastGFile(r'F:\train\Rubus_pedatifolius_Genév\4000.jpg', 'rb').read() failed,
but, tf.gfile.FastGFile(r'C:\Users\d\Desktop\4000.jpg', 'rb').read() successed!
so, is it  a bug or  tf.gfile.FastGFile can't read french path?

**Comment by yongtang** [comment]
PR #11562 fixed the issue of non-ASCII character in Windows path. That PR was merged in several weeks ago. Maybe it is not part of your local TensorFlow installment yet?

**Comment by micklexqg** [comment]
@yongtang , there are many other normal paths(non french) under the directory and they are OK. but only those french paths failed.

**Comment by mrry** [comment]
To help you, we'll need the information that is requested in the issue template. 

In particular, are you using the released build of TensorFlow 1.3 or a more recent version (e.g. a nightly build)?

**Comment by micklexqg** [comment]
@mrry ，TensorFlow 1.1 + Python3.5 + Windows7

**Comment by yongtang** [comment]
@micklexqg I believe TensorFlow 1.1 was unable to process non-ASCII characters in Windows. The French char `é` is non-ASCII so the issue you encountered is expected in 1.1. 

PR #11562 fixed the issue of non-ASCII character in Windows several weeks ago though it seems like the PR is not included in TensorFlow 1.3. 

I think you may give the nightly build a try or building TensorFlow from the source (https://www.tensorflow.org/install/install_sources) if you need this feature sooner.

**Comment by micklexqg** [comment]
@yongtang ， thanks，keep attention.

**Comment by mrry** [comment]
As @yongtang mentioned, this has been fixed at HEAD but not included in a release. It will be included in the TF 1.4 release, but you can try a nightly build in the mean time.

**Comment by micklexqg** [comment]
glad to hear that, @mrry
