### ISSUE TITLE
Setting momentum

### ISSUE THREAD

**Issue by saonim** [tensorflow/tensorflow#1261]
Hi,

I am trying to change the value of momentum for SGD. Can you please tell me where it is set?

Thanks!

**Comment by rdipietro** [comment]
Instead of using `GradientDescentOptimizer`, take a look at `MomentumOptimizer`

**Comment by cesarsalgado** [comment]
This kind of question should be asked in https://stackoverflow.com/questions/tagged/tensorflow. Please read the [community guide lines](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/resources/index.md#community) for more information.

**Comment by saonim** [comment]
Thanks @rdipietro ! @cesarsalgado : sure, next time :)
