### ISSUE TITLE
Import error when installing from the latest binaries on Ubuntu14, Python3.4

### ISSUE THREAD

**Issue by DSLituiev** [tensorflow/tensorflow#1262]
I wanted to updat tensorflow to the newest release and now cannot import it (I am not in a source tree).

### Environment info
Operating System:
Ubuntu 14

If installed from binary pip package, provide:

1. Which pip package you installed.
Latest 3.4 cpu Ubuntu
`sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl`

2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

If installed from sources, provide the commit hash:

### What have you tried?

` python3 -c "import tensorflow; print(tensorflow.__version__)".`

### Logs or other output that would be helpful

```
dima@dima-TP-T410s:~/data/repos$ python3 -c "import tensorflow; print(tensorflow.__version__)"
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: cannot import name 'descriptor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: cannot import name 'descriptor'


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

**Comment by vrv** [comment]
Can you try pip uninstalling tensorflow *and* protobuf, then reinstalling tensorflow?

**Comment by DSLituiev** [comment]
this solved the issue

**Comment by andyyuan78** [comment]
envy@ub1404:~/os_pri/github$ 
envy@ub1404:~/os_pri/github$ pip show protobuf
---
Name: protobuf
Version: 2.6.1
Location: /home/envy/.local/lib/python2.7/site-packages
Requires: setuptools
envy@ub1404:~/os_pri/github$ pip show tensorflow
---
Name: tensorflow
Version: 0.7.1
Location: /home/envy/.local/lib/python2.7/site-packages
Requires: six, protobuf, wheel, numpy
envy@ub1404:~/os_pri/github$ 


i got this error yet!

**Comment by hradhakrishnan** [comment]
Thanks guys that worked. When i installed tensorflow it uninstalled protobuf 2.6.1 with the latest 3.0 version required for tensorflow..works now
