### ISSUE TITLE
How to extract final embedding matrix from word2vec.py?

### ISSUE THREAD

**Issue by michelleowen** [tensorflow/tensorflow#1263]
I am using word2vec.py. I want to extract the final embedding matrix and save it to a txt file. How can I extract the final embedding?

**Comment by vrv** [comment]
this would be a better question for StackOverflow, GitHub issues are for bugs / feature requests.

**Comment by davidoak** [comment]
@michelleowen Have you solved the problem? I have the save question. Thanks

**Comment by michelleowen** [comment]
@davidoak yes, I did. Please refer to the stackoverflow: https://stackoverflow.com/questions/35582858/how-can-i-get-final-embeddings-from-word2vec-py/35611003?noredirect=1#comment76826763_35611003

**Comment by davidoak** [comment]
@michelleowen thank you! I was also wondering after generating the .txt embedding file, can I use this to implement KNN retrieval task? For example, displaying top 10 nearest words. If so, do you know how I can do it?
