### ISSUE TITLE
compile tensorlfow c++ object class as /clr project to make the dll  fail !!

### ISSUE THREAD

**Issue by kyo055** [tensorflow/tensorflow#12644]
------------------------

### System information
- **windows10**:
- **install tensorflow**: from source by vs2015 
- **TensorFlow version**: r1.2
-**CMake**:  3.8.2 build

### Error List
1. 
>#error instruction:  <condition_variable> is not supported when compiling with /clr or /clr:pure.	CppWrapper	d:\Developer\Microsoft Visual Studio 14.0\VC\include\condition_variable	17	
2. 
>#error instruction:  <mutex> is not supported when compiling with /clr or /clr:pure.	CppWrapper	d:\Developer\Microsoft Visual Studio 14.0\VC\include\mutex	8	
3.
> #error instruction:  <thread> is not supported when compiling with /clr or /clr:pure.	CppWrapper	d:\Developer\Microsoft Visual Studio 14.0\VC\include\thread	8	
4. 
 >e:\tensor\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\eigen\src/Core/ArithmeticSequence.h(205): fatal error C1001: An internal error has occurred in the compiler.

**Comment by mrry** [comment]
The TensorFlow codebase is not compatible with the `/clr` flag when building with Visual C++. The MSDN documentation outlines [some of the restrictions](https://msdn.microsoft.com/en-us/library/ffkc918h(v=vs.90).aspx) when you compile using that flag.

If there is a compelling reason to build TensorFlow with this flag, and the code changes to make this possible are not too invasive, we might consider accepting a contribution to do so.  Therefore I'll mark this as "Contributions Welcome" for now, and we'll keep the issue open if you can give us some more details about why you want to do this.

(For accessing the TensorFlow API from a managed language, check out [TensorFlowSharp](https://github.com/migueldeicaza/TensorFlowSharp) by @migueldeicaza. As far as I can tell, it uses P/Invoke to invoke TensorFlow API methods that are implemented in an unmanaged DLL.)

**Comment by kyo055** [comment]
I have build an console exe with tensorflow and opencv libraries for detecting and recognizing human. However, my team built a C# GUI system. They hope me to build the /clr project to make a DLL for their C# project to import and finish human face recognition. But we even don't know tensorflow can't compile with /clr flag. So this is really frustrating. 
I right now don't have some ideas about compiling the DLL, but I must do that. Maybe take a long time to find the correct trick or make some changes to Tensorflow source files.

**Comment by mrry** [comment]
I'd suggest building your console exe as a native DLL instead, and using P/Invoke to call into the DLL from the C# GUI.

**Comment by wt-huang** [comment]
@mrry suggestion would work
