### ISSUE TITLE
Is there any  class similar to tf.contrib.learn.monitors.ValidationMonitor in TF-Slim for evalution in logging?

### ISSUE THREAD

**Issue by qiushi223** [tensorflow/tensorflow#12640]
I want to evaluate my model using validation data when training and show the evalution result in logging,which is similar to tf.contrib.learn.monitors.ValidationMonitor,and i can customize my metrics to evaluate.Is there any one in TF-Slim?

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
