### ISSUE TITLE
It seems there is protobuf problem after building tensorflow 0.7 from source code

### ISSUE THREAD

**Issue by kepricon** [tensorflow/tensorflow#1264]
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

### Environment info
Operating System: ubuntu 1404

Hi all
 
I am caffe user.
I've executed caffe application since the end of the last year.
Until i tried to install tensorflow, my system is working well.
After install tensorflow 0.7 from source code.
it shows me some error like below.

Even though i installed protobuf 3.0 via pip and source code, i couldn't solve this problem.
I think there is some static variable for requiring specific version of protobuf(in this case 3.0).
Do you have any idea for this problem?

I0224 10:41:24.543294 19528 layer_factory.hpp:74] Creating layer data
[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.0.0 of the Protocol Buffer runtime library, but the installed version is 2.5.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/src/google/protobuf/any.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.0.0 of the Protocol Buffer runtime library, but the installed version is 2.5.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/src/google/protobuf/any.pb.cc".)

Thank you

**Comment by vrv** [comment]
I would suggest uninstalling protobuf and installing the protobuf version you want to make Caffe work.  I would then suggest installing TensorFlow in a virtualenv, so that you don't have to worry about having incompatible copies of protobuf in your system libraries.

**Comment by kepricon** [comment]
Thank you vrv.
It is working now.

**Comment by muzi-8** [comment]
@kepricon I faced the same error，so what can I do ? 
"[libprotobuf FATAL google/protobuf/src/google/protobuf/stubs/common.cc:67] This program requires version 3.2.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.2.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
"
Looking forward to your reply. Thanks！
