### ISSUE TITLE
tensorflow1.3 bazel-bin/tensorflow/examples/label_image/label_image failed to run.

### ISSUE THREAD

**Issue by JackGan999** [tensorflow/tensorflow#12647]
step 1:python tensorflow/examples/image_retraining/retrain.py    --architecture=inception_v3    --output_graph=inception_v3.pb  ....  
step2: bazel build tensorflow/examples/label_image
step3: bazel-bin/tensorflow/examples/label_image/label_image
then get the following error:
tensorflow/examples/label_image/main.cc:349] Running model failed: Not found: FeedInputs: unable to find feed output input.
Any step wrong? Could you give me some hint?

**Comment by quaeler** [comment]
What were the exact command line arguments you performed?

The [label_image code expects](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/main.cc#L281) the graph model to be named specifically `inception_v3_2016_08_28_frozen.pb` and [the labels file to be named](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/main.cc#L283) `imagenet_slim_labels.txt` unless you specify differently via command line flags.

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
