### ISSUE TITLE
DNN Classifier producing Blue Screen of Death every time

### ISSUE THREAD

**Issue by Bazman76** [tensorflow/tensorflow#12656]
Hi,  

When running inputs 9 10 and 11 from the below notebook, I get a blue screen of death every time?  

https://github.com/ageron/handson-ml/blob/master/10_introduction_to_artificial_neural_networks.ipynb

I'm using: 

Python ver 3.5.3
Tensorflow 1.2.1
Running on a windows 7 pro machine

Any tips on how to resolve this?

**Comment by michaelisard** [comment]
Would you please fill out the issue template including details of GPU and CUDA drivers, etc.?

**Comment by Bazman76** [comment]
Windows 7 Pro 64 bit (6.1, build 7601)
Tensorflow installed via anaconda
Tensorflow version 1.2.1
Python version 3.5.3
As for Cuda etc this PC was set up some time ago there is a GPU installed is that sufficient or should I install CUDA/cuDNN separately? I don't think I'm currently using the GPU.
GPU: AMD radeon 6900 series 4095MB

The problem arises when the last line of block 11 is run,

https://github.com/ageron/handson-ml/blob/master/10_introduction_to_artificial_neural_networks.ipynb

It also arises when block 11 of this notebook is run:

https://github.com/ageron/handson-ml/blob/master/10_introduction_to_artificial_neural_networks.ipynb

It does not crash immediately it gets to a test accuracy of 92% (so quite close to the end) before crashing and given a blue screen of death.

Anything else you need just let me know.

**Comment by michaelisard** [comment]
@mrry can you comment on the most helpful additional debugging information to collect to make progress on this?

**Comment by mrry** [comment]
I don't think TensorFlow does anything that could cause a BSOD. Are you using the CPU version of TensorFlow? (I'd assume so because you don't have a CUDA-capable GPU.)

**Comment by Bazman76** [comment]
Yes it is the CPU version. All I can say is that the BSOD are produced in the same place every time it does seem to be a bit of a coincidence? I guess it could be hardware overheating but I don't think these practive problems are that challenging?

**Comment by mrry** [comment]
I suspect that this is a problem with your hardware or operating system, and perhaps TensorFlow is aggravating it by allocating a large amount of memory. Since Windows 7 is now end-of-life, it's possible that there's a bug in the OS that won't be patched. I'd suggest upgrading to a new operating system to see if that helps the problem.

Unfortunately that is not something we're able to diagnose, and so I'm going to close this issue.

**Comment by Bazman76** [comment]
Re OS would you recommend switching to Linux?

**Comment by Earbaj** [comment]
I have the same problem i try to reinstalling windows but it doesn’t work when i installing tensorflow using anaconda navigator it shout down the pc and goes to the blue screen
