### ISSUE TITLE
Bundling tensorflow app to desktop

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#12671]
I have got a tensorflow based app which recognizes the objects state. I use opencv and tensorflow to get this done. The final application has to be a desktop app. How do I bundle all dependencies and export it for desktop?

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Zumbalamambo** [comment]
@asimshankar I have asked the same question in stackoverflow but it has been put on hold since they think that it is too broad
