### ISSUE TITLE
Running language model example on multiple GPUs?

### ISSUE THREAD

**Issue by Palang2014** [tensorflow/tensorflow#1268]
Hi all,

First of all thanks for this great library and state of the art examples provided.

I am trying to train a language model on multiple GPUs following your language model example(https://www.tensorflow.org/versions/r0.7/tutorials/recurrent/index.html). This is because (i) Dataset is huge (ii) Vocabulary is large. 

I tried to change ` with tf.device("/cpu:0"): ` in the code to something like: 
```python
for d in ['/gpu:0', '/gpu:1']:
    with tf.device(d):
        embedding = tf.get_variable("embedding", [vocab_size, size])
        inputs = tf.nn.embedding_lookup(embedding, self._input_data) 
```
But got an error from `MatMul`. It happened even when I set it to one GPU. To resolve the problem with one GPU I tried to use:
```python
def device_for_node(n):
  if n.type == "MatMul":
      return "/gpu:1"
  else:
      return "/cpu:0"
<some code>
with tf.Graph().as_default(), tf.Session() as session:
    with session.graph.device( device_for_node ):
```
which worked but speed dropped significantly, e.g., from 32,000 wps to 1200 wps which apparently means that it is not a good idea probably because TF optimizes both CPU and GPU usage. 
I still can not figure out how to use multiple GPUs without losing the speed for this example. Anyone has had the same problem?

Thanks!
Hamid

**Comment by girving** [comment]
We'll need more information to help: what is the error you're getting "from MatMul"?

**Comment by Palang2014** [comment]
Thanks for reply. Let me ask them separately, 

(1) Is it possible to use embedding layer with GPU? I think it is not because when I change `` with tf.device("/cpu:0") `` to ``with tf.device("/gpu:0")`` I get the following error which is caused by embedding look up. Is this because it is faster on CPU or it also supports GPU with a different syntax?
```
tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'model/embedding_lookup': Could not satisfy explicit device specification '/device:GPU:0'
	 [[Node: model/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/device:GPU:0"](model/embedding/read, model/Placeholder)]]
Caused by op u'model/embedding_lookup'
```

(2) For the rest of the code it uses just one GPU even if I made two GPUs visible for it with:
```
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
```
How I can set the language model example to use more than one GPU?

Thanks!
Hamid

**Comment by girving** [comment]
Oh no!  I appear to have missed a notification here.  Fortunately since this bug was filed we've added `tf.gather` for GPUs, so part (1) is fixed.

@zheng-xq: Do you want to comment on the multiple GPU bit?

**Comment by zheng-xq** [comment]
@Palang2014, a typical set up is to have all the variables on CPU, and all the computation on GPU. If you have multiple GPUs, it is a good idea to merge the gradients on them before sending the delta back to CPU. 

It is not a good idea to place some ops on one device, and others on another, with fine granularity. The problem with that is the data transfer. Each time your data flow across device boundary, the device needs to synchronize and copy the data over. This can easily defeats whatever computation gain you are getting.

**Comment by Palang2014** [comment]
Thank you girving and zheng-xq for explanations.

**Comment by aselle** [comment]
Given the lack of recent activity, I assume the question has been answered sufficiently. Closing now due to lack of recent activity. Please re-open or comment if further information becomes available.
