### ISSUE TITLE
Bundling tensorflow app to desktop

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#12695]
I have got a tensorflow based app which recognizes the objects state. I use opencv and tensorflow to get this done. The final application has to be a desktop app. How do I bundle all dependencies and export it for desktop?

**PS:** I have asked the same question in stackoverflow with no response for my question hence Im asking this here hoping for a positive reply

**Comment by snnn** [comment]
You may give a try on "libtensorflow", it has no extra dependency.

**Comment by Zumbalamambo** [comment]
@snnn can you please share the github url for the same

**Comment by snnn** [comment]
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/lib_package

**Comment by Zumbalamambo** [comment]
it again requires bazel for installation. How can it be bundled with the bazel dependency? Any working example will help a lot

**Comment by quaeler** [comment]
I think he is suggesting you build `libtensorflow.so` (which you can build via `bazel build --config=opt //tensorflow:libtensorflow.so`)  and then link that to your desktop application.

Once you've built the library, you no longer need involve bazel if you don't want to use it with your desktop application.)

**Comment by Zumbalamambo** [comment]
so after building tensorflow:libtensorflow.so, I have to write wrapper around it if I have to interface it with other languages?

**Comment by quaeler** [comment]
Yes, for example if you were writing an application in Scala, you'd need to write the native interface layer yourself for the wrapper around that. What language are you using?

**Comment by Zumbalamambo** [comment]
Im using python... i want them to install it without downloading tensorflow with pip...  im creating a standalone desktop app written in python

**Comment by Zumbalamambo** [comment]
if you can provide a sample code from github, it will be a great help for me.

**Comment by quaeler** [comment]
Hmm... you don't want to install tensorflow via pip at all? (In other words, not from a public repository and not using a locally built `.whl` archive?)

I cannot think of a "clean" way to deploy a desktop app written in Python in this situation that does not involve a package manager.

I would believe that there is a way - like building the `//tensorflow/tools/pip_package:build_pip_package` target and then selectively copying all of the generated library and python files from the `bazel-out` directory tree to a development directory structure for your own app - but that would require a knowledge of the python subsystem that i don't have.

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Zumbalamambo** [comment]
@jart if I ask this question in stackoverflow, people are redirecting me to github repo. if i ask this in github, people are redirecting me to stackoverflow. I have asked it [already](https://stackoverflow.com/questions/45931097/bundle-tensorflow-for-desktop) in stackoverflow but no answers so far

**Comment by Zumbalamambo** [comment]
@quaeler let me try that

**Comment by boduchkarolina** [comment]
Hi! 
I've the same problem right now.
I need to connect my tensorflow ML model to the desktop application written in python.
Could you share your experience with me? :)
