### ISSUE TITLE
Training model on Android 

### ISSUE THREAD

**Issue by humanlost** [tensorflow/tensorflow#12696]
I want to training my model on the Android mobile phones by using Tensorflow. How to train the model and save the model on Android mobile phone? I can not find corresponding functions on Java API of TensorFlow.

Is it possible to find a way to implement such functions on android mobile phone? maybe tensorflow on Android with Python bindings? Or other Deep learning framework？

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by xumengwei** [comment]
Hi @humanlost Have u figured out how to train a model on Android?

**Comment by rajatmonga** [comment]
This was answered in #17328

**Comment by saudet** [comment]
@humanlost @xumengwei This is something that is possible from Java with the [JavaCPP Presets for TensorFlow](https://github.com/bytedeco/javacpp-presets/tree/master/tensorflow) because the C++ API of TensorFlow supports training, and it works on Android too, as @rajatmonga pointed out.
