### ISSUE TITLE
TensorBoard executed stuck

### ISSUE THREAD

**Issue by DedongZhang** [tensorflow/tensorflow#12693]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Pro 1703
- **TensorFlow installed from (source or binary)**: install binary with GPU version by pip based on Python 3.5.2
- **TensorFlow version (use command below)**:('1.3.0')
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**:none
- **CUDA/cuDNN version**:cuda v8.0/cuDNN v6,0
- **GPU model and memory**:GeForce GTX 1080 Ti 11GB

### Describe the problem
I am trying to open TensorBoard after running mnist_with_summaries.py source code from the TensorBoard tutorials (https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py). However, 
After I run tensorboard --logdir=/tmp/tensorflow/mnist in cmd, it stuck and did not showing anything else.  I try to use tensorboard --logdir=/tmp/tensorflow/mnist --debug and have the same result. 
![capture](https://user-images.githubusercontent.com/16062793/29848367-ae4c35b0-8ce5-11e7-8e9e-0ee44058fda3.PNG)

**Comment by fastlater** [comment]
@DedongZhang any update? Did you figure out why the tensorboard stucks? I have the same problem. Windows 7, TF 1.3.

**Comment by DedongZhang** [comment]
@fastlater not yet, I try to use another pc, and the same thing happens.

**Comment by DedongZhang** [comment]
@fastlater it is working now. I try to open by type http://admin-pc:6006/ but never try localhost:6006. I guess my cmd some how just not show result message. I could open it by localhost:6006 now.Thank you very much!

**Comment by jart** [comment]
From what I understand, TensorBoard isn't showing logs output, but if you go to the web address, it still shows the GUI.

We recently made some changes to the logging code, that has special cases for Windows.

Is there any chance you could try locally modifying this piece of code right here: https://github.com/tensorflow/tensorboard/blob/master/tensorboard/util.py#L282 where it says `os.name != 'nt'`? We might need to update this, or something related.

**Comment by jart** [comment]
We've now pushed the [0.1.6](https://github.com/tensorflow/tensorboard/releases/tag/0.1.6) release to [PyPi](https://pypi.python.org/pypi/tensorflow-tensorboard/0.1.6) which should fix this issue. Please run:

```sh
pip install --upgrade tensorflow-tensorboard
```

**Comment by a1-mukul** [comment]
first pip uninstall tensorflow-tensorboard and then pip install tensorboard.
This will work
