### ISSUE TITLE
Speech Commands Example URL broken

### ISSUE THREAD

**Issue by RyanRamchandar** [tensorflow/tensorflow#12692]
Found here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/speech_commands#speech-commands-example

http://tensorflow.org/tutorials/audio_recognition is broken

**Comment by yongtang** [comment]
The audio recognition tutorial has only been added recently:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/tutorials/audio_recognition.md

I think the link will show up once `http://tensorflow.org` has been updated (from rebuilding `docs_src`).

**Comment by RyanRamchandar** [comment]
That makes sense. Thanks @yongtang.
