### ISSUE TITLE
During handling of the above exception. Another exception occured

### ISSUE THREAD

**Issue by sdlmw** [tensorflow/tensorflow#12697]
![qq 20170829141338](https://user-images.githubusercontent.com/13164077/29851834-e8c4b112-8d68-11e7-971e-f29455d764d5.png)
![qq 20170829141241](https://user-images.githubusercontent.com/13164077/29851833-e8c00a36-8d68-11e7-913b-82aafd793e75.png)
Does anyone know what is the cause of this?
My system environment：Ubuntu_16.04_X86_64; nvidia dirver version:v384.66 nvcc_version:v8.0 cuDNN:6.0 .
I dont know why.
Thank you before

**Comment by quaeler** [comment]
The first exception describes itself as the process having run out of memory - this would be your root problem. Often everything else being dealt with after running out of memory is just trying to land a plane that is on fire.

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by sdlmw** [comment]
@quaeler @jart  ok，thank you. But I'm running with 8G of RAM maximum use 2G.And then it ends. I processed the file 15M。Whether the TensorFlow itself causes an exception to be thrown

**Comment by quaeler** [comment]
@sdlmw This user also ran into your same issue: https://github.com/tensorflow/tensorflow/issues/10826

Perhaps reach out to them for assistance?

**Comment by sdlmw** [comment]
Finally I found out that the graphics card memory is low. thanks @quaeler @jart
