### ISSUE TITLE
cannot use bazel to compile tensorflow example codes

### ISSUE THREAD

**Issue by conandiy** [tensorflow/tensorflow#127]
tensorflow was successfully installed on my OSX10.11 system.
using "import tensorflow" in python donot report any error, and "hello world" application can be carried out.
but when i want to run the examples(http://tensorflow.org/tutorials/recurrent/index.md) in the tensorflow root directory, 
i typed "bazel build -c opt tensorflow/models/rnn/ptb:ptb_word_lm"
it showed that:
ERROR: /Users/aaa/Develop/tools/tensorflow/tensorflow/python/BUILD:1: Extension file not found: 'google/protobuf/protobuf.bzl'.
ERROR: error loading package 'tensorflow/python': Extension file not found: 'google/protobuf/protobuf.bzl'.
INFO: Elapsed time: 0.057s

i don't know what is wrong.
any comment is appreciated.

**Comment by davidzchen** [comment]
Seems that you might not have cloned the `protobuf` submodule? When you cloned the tensorflow repository, did you add the `--recurse-submodules` flag?

Try running `git submodule --init update` in the repository then building again.

**Comment by vrv** [comment]
Likely the culprit -- reopen if this was not the case!

**Comment by lionleaf** [comment]
Thanks, @davidzchen. For anyone Googling and copy pasting, it's
`git submodule update --init`

**Comment by davidzchen** [comment]
Sorry, there was a typo in the git submodule command in my comment. Thanks, @lionleaf!
