### ISSUE TITLE
how to find distance from camera to object?

### ISSUE THREAD

**Issue by BeginnerTensorflow** [tensorflow/tensorflow#12718]
hello.
i am a beginner.
how to find distance(Meter) from camera to object with tensorflow?
Thanks.

**Comment by BeginnerTensorflow** [comment]
please cove me.
nobody to answer my question?
Nobody knows the answer?
pls.

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
