### ISSUE TITLE
The installation instructions not updated for latest Mac OS X. 

### ISSUE THREAD

**Issue by harishkashyap** [tensorflow/tensorflow#12717]
Please update instructions; ML engineers dont have time to waste spending on configurations.

**Comment by gunan** [comment]
Could you be clearer on what issues you are seeing in our installation instructions?
Nothing should have changed on MacOS since we last updated our instructions, but we are happy to revise them.

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
