### ISSUE TITLE
uploads tensorflow as follow error:

### ISSUE THREAD

**Issue by molyswu** [tensorflow/tensorflow#12723]
uploads tensorflow as follow error:

ImportError: numpy.core.multiarray failed to import   Failed to load the native TensorFlow runtime.  See https://www.tensorflow.org/install/install_sources#common_installation_problems 

Thank you for your help!

**Comment by gunan** [comment]
Not sure I understand what you mean.
Are you asking us to update common installation problems with a new issue?
Could you elaborate?
