### ISSUE TITLE
dataset with tf.pyfunc error

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [tensorflow/tensorflow#12721]
The new IO API is awesome, but I found this error in my project.
![image](https://user-images.githubusercontent.com/25046619/29908076-feb68952-8e51-11e7-8bd2-feed44d143cb.png)
 I tried to get some index from dataset, then make a batch index, 
given the batch index, I got the features from memory which used tf.py_func API, but I found this error.
Invalid argument: Shapes of all inputs must match: values[0].shape = [4096] != values[3].shape = [4096,41]

**Comment by TomorrowIsAnOtherDay** [comment]
I solved the Problem: convert the results' type into tuple instead use of list.The official Guide document should update.

**Comment by gunan** [comment]
Thanks for the suggestion!
Would you like to send a pull request with your proposed fix?

**Comment by TomorrowIsAnOtherDay** [comment]
The official  Guide(https://www.tensorflow.org/programmers_guide/datasets) is different from that on master branch (tensorflow/tensorflow/docs_src/programmers_guide/datasets.md).The usage example from master branch is right.Can you update the official Guide? Additionally, why can't the API convert the list to tuple automatically?

**Comment by TomorrowIsAnOtherDay** [comment]
Oh, someone has made an issue before on this problem, Please update the official guide
#11786
