### ISSUE TITLE
AssertionError: Cannot find .runfiles directory for bazel-bin/tensorflow/python/tools/freeze_graph

### ISSUE THREAD

**Issue by willyycn** [tensorflow/tensorflow#12726]
After I install the tensorflow from source, i'm trying to use freeze_graph tool, and it appear this error. 
My OS is MacOS 10.12.5

**Comment by zbpjlc** [comment]
hi,how can you deel with the problems, I meet it now

**Comment by kiariendegwa** [comment]
Hi, what Bazel version are you using? There's a whole list of tensorflow native builds and their accompanying requirements. https://www.tensorflow.org/install/install_sources
