### ISSUE TITLE
docker run failed with the image

### ISSUE THREAD

**Issue by qdk0901** [tensorflow/tensorflow#1273]
### Environment info
Operating System: Ubuntu 14.04
Docker version: Docker version 1.10.2, build c3959b1
same result with or without proxy(I use tsocks for proxy)
### What have you tried?
1.  Failed when running tensorflow with docker using the following command
```
sudo docker run -it -p 8888:8888 b.gcr.io/tensorflow/tensorflow
```
the output
```
abc@abc:~/source$ sudo docker run -it -p 8888:8888 b.gcr.io/tensorflow/tensorflow
Unable to find image 'b.gcr.io/tensorflow/tensorflow:latest' locally
docker: Error response from daemon: unable to ping registry endpoint https://b.gcr.io/v0/
v2 ping attempt failed with error: Get https://b.gcr.io/v2/: dial tcp 74.125.204.82:443: i/o timeout
 v1 ping attempt failed with error: Get https://b.gcr.io/v1/_ping: dial tcp 74.125.204.82:443: i/o timeout.
See 'docker run --help'.

```

**Comment by qdk0901** [comment]
also tried `export ALL_PROXY=socks5://192.168.1.104:1080` but without luck, still failed when pulling image

**Comment by qdk0901** [comment]
forget this,
after using vpn, all things working fine.

**Comment by gangele397** [comment]
I am hitting same issue can somebody guide what is the issue?

**Comment by MingCHEN-Github** [comment]
@gangele397 @qdk0901Another easy solution. If you're under GFW, you can try the image of tensorflow in Docker Hub instead of Google's Cloud Platform. In your terminal, just run `sudo docker run -it -p 8888:8888 tensorflow/tensorflow` instead of running `sudo docker run -it -p 8888:8888 b.gcr.io/tensorflow/tensorflow`. It works for me. Hope it is helpful for you guys.

**Comment by qdinfish** [comment]
@MingCHEN-Github Hi, I got following error :(, do you know how to fix? thx

Unable to find image 'tensorflow/tensorflow:latest' locally
latest: Pulling from tensorflow/tensorflow
297061f60c36: Downloading [===>                                               ]  3.079MB/43.03MB
e9ccef17b516: Download complete 
dbc33716854d: Download complete 
8fe36b178d25: Download complete 
686596545a94: Download complete 
ed66f2c5f3d9: Downloading [=>                                                 ]  2.698MB/129.6MB
8405b6c3f141: Downloading [==================================================>]  4.244MB/4.244MB
070615ca3a03: Waiting 
306ac2321f8e: Waiting 
c30111bc1e74: Waiting 
7aa552c3f7f7: Waiting 
4db41af3662a: Waiting 
bf5fbadacf01: Waiting 
docker: read tcp 192.168.1.107:50572->104.18.124.25:443: read: connection reset by peer.
