### ISSUE TITLE
Has anyone tried to visualize this program with tensorboard? 

### ISSUE THREAD

**Issue by Sunflower4711** [tensorflow/tensorflow#12732]
I was trying to visualize the vectors with thensorboard, but it did not work, it was loading for over 30 minutes, what is wrong?

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
