### ISSUE TITLE
 bazel build tensorflow/python/tools:optimize_for_inference failed

### ISSUE THREAD

**Issue by AndyLin0128** [tensorflow/tensorflow#12751]
$ bazel build tensorflow/python/tools:optimize_for_inference
ERROR: /Users/andylin/Desktop/gitwork/tensorflow/tensorflow/core/BUILD:1416:1: no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by /Users/andylin/Desktop/gitwork/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /Users/andylin/Desktop/gitwork/tensorflow/tensorflow/core/BUILD:1416:1: no such target '//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by /Users/andylin/Desktop/gitwork/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /Users/andylin/Desktop/gitwork/tensorflow/tensorflow/core/BUILD:1416:1: no such target '//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by /Users/andylin/Desktop/gitwork/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: Analysis of target '//tensorflow/python/tools:optimize_for_inference' failed; build aborted.
INFO: Elapsed time: 0.875s

**Comment by gunan** [comment]
What I can tell from  the error messages is you did not run `configure` script before trying to build.
Please make sure to read our install from sources guide if you would like to build any part of tensorflow from sources.
https://www.tensorflow.org/install/install_sources

**Comment by AndyLin0128** [comment]
@gunan thanks。and run ./configure, no problem, but i run bazel-bin/tensorflow/python/tools/optimize_for_inference --input=~/Desktop/output_graph.pb --output=~/Desktop/optimized_graph.pb --input_names=Mul --output_names=final_result


bazel-bin/tensorflow/python/tools/optimize_for_inference --input=~/Desktop/output_graph.pb --output=~/Desktop/optimized_graph.pb --input_names=Mul --output_names=final_result
Traceback (most recent call last):
  File "/Users/andylin/Desktop/gitwork/tensorflow/bazel-bin/tensorflow/python/tools/optimize_for_inference.runfiles/org_tensorflow/tensorflow/python/tools/optimize_for_inference.py", line 65, in <module>
    from tensorflow.python.framework import dtypes
  File "/Users/andylin/Desktop/gitwork/tensorflow/bazel-bin/tensorflow/python/tools/optimize_for_inference.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 107, in <module>
    from tensorflow.python.platform import test
  File "/Users/andylin/Desktop/gitwork/tensorflow/bazel-bin/tensorflow/python/tools/optimize_for_inference.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 59, in <module>
    import mock                # pylint: disable=g-import-not-at-top,unused-import
ImportError: No module named mock

**Comment by AndyLin0128** [comment]
@gunan Thanks.
