### ISSUE TITLE
Three questions about ChiefSessionCreator?

### ISSUE THREAD

**Issue by gauss-clb** [tensorflow/tensorflow#12765]
* There are two parameters of [ChiefSessionCreator][1]: `checkpoint_dir` and `checkpoint_filename_with_path`,
what difference between them?

* And ChiefSessionCreator has a parameter [scaffold][2] which has a parameter `saver`, does it mean ChiefSessionCreator uses scaffold.saver to save and restore variables?

* And scaffold also has a parameter `init_fn`, and it can be used like 
init_fn=[assign_from_checkpoint_fn][3], assign_from_checkpoint_fn will new a saver with the parameter `var_list` of assign_from_checkpoint_fn. So here comes another question, ChiefSessionCreator will use scaffold.saver to restore variables or init_fn?

To answer the three questions above, you may need read the source code, but I am not capable to do it, so I need your help. Thanks.

  [1]: https://www.tensorflow.org/versions/master/api_docs/python/tf/train/ChiefSessionCreator
  [2]: https://www.tensorflow.org/versions/master/api_docs/python/tf/train/Scaffold
  [3]: https://www.tensorflow.org/versions/master/api_docs/python/tf/contrib/framework/assign_from_checkpoint_fn

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by gauss-clb** [comment]
It has been asked on stackoverflow, but no response.
