### ISSUE TITLE
typo in config.py (line 688)

### ISSUE THREAD

**Issue by DeliciousHair** [tensorflow/tensorflow#12760]
Currently is:

```
cudnn_path_from_ldconfig = re.search('.*libcudnn.so .* => (.*)',
```

should be:

```
cudnn_path_from_ldconfig = re.search('.*libcudnn.so.* => (.*)',
```

(note the extra space in the current version)

**Comment by printdhruv** [comment]
Opened issue at [Request](https://github.com/tensorflow/tensorflow/pull/12762)

**Comment by michaelisard** [comment]
Thanks! Marking contributions welcome for now pending the PR.

**Comment by yifeif** [comment]
The space here is intentional. 
It is supposed to get the link without the cudnn version number:
	`libcudnn.so (libc6,x86-64) => /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so`
@DeliciousHair was it causing any issue for you?

**Comment by DeliciousHair** [comment]
It was, the config script kept erroring on me when building from master until I removed that space (hence mentioning it). Wouldn't you want/need the version number though, since the script does in fact ask about it as well?

**Comment by yifeif** [comment]
Do you mind posting the error you are seeing? 
The script follows the regex match with this check:
`if os.path.exists('%s.%s' % (cudnn_path_from_ldconfig, tf_cudnn_version)):`, which is why it was looking for the link for libcudnn.so instead of libcudnn.so.<tf_cudnn_version>.

**Comment by DeliciousHair** [comment]
happy to, but will not be around the computer for about 16 hours.

**Comment by DeliciousHair** [comment]
Closing this, as I cannot seem to reproduce the original problem, that really did required me to remove the space to fix.

My only guess is that I rave rebooted the machine between then and now to get the cuda drivers to actually work as opposed to being just installed, and that seems to have fixed the problem somehow as well.

Sorry about that!
