### ISSUE TITLE
tf_library syntax error: '+' operator applied to incompatible types (select of string, list)

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#12767]
Forgive me if I'm missing something obvious here (new to Bazel) but the tf_library Bazel rule seems to assume that `tfcompile_flags` is a string, while similar rules allow lists (cc_binary's copts for example). This is a gotcha that probably could be fixed easily.

# Example
```
tf_library(
  name = "graph",
  cpp_class = "Graph",
  graph = "graph.pb",
  config = "graph.config.pb",
  tfcompile_flags = ["--target_cpu='core-avx2'", "--xla_enable_fast_math=false"]
)
```
will crash upon build with `'+' operator applied to incompatible types (select of string, list)`

The solution is to manually concatenate options in the BUILD file: 
```
tf_library(
  name = "graph",
  cpp_class = "Graph",
  graph = "graph.pb",
  config = "graph.config.pb",
  tfcompile_flags = "--target_cpu='core-avx2' --xla_enable_fast_math=false"
)
```

**Comment by yongtang** [comment]
@calthome Are you referring to tfcompile.bzl (below)?
https://github.com/tensorflow/tensorflow/blob/da3aa93758508a37741dad1d8b28e62782330171/tensorflow/compiler/aot/tfcompile.bzl#L148

I am new to Bazel as well though I think using `" ".join(tfcompile_flags or [])` instead will allows `tfcompile_flags` to be a list.

**Comment by yongtang** [comment]
Created a PR #12769 for this issue.

**Comment by jart** [comment]
I support making this change, so long as it maintains support for passing a string and the items in the list are shell quoted. I left that feedback in the review that @yongtang was generous enough to send us.
