### ISSUE TITLE
Allow to build tensorflow as a bazel external dependency.

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tensorflow#12761]
It would be nice to be able to just add a @org_tensorflow in bazel and be able to build it as a dependency.  

At the best of my knowledge the syntaxnet dockerfile is the best example on having tensorflow as a submodule.
https://github.com/tensorflow/models/blob/c259259299db3b486ccdfd6cdec44b884623053a/syntaxnet/Dockerfile#L63

But still building it is not straightforward and probably does not work if you activate CUDA/XLA/MLK because those depends on other bazel subprojects.

Are there any plans to support this use case or I am missing something in the best practices to build tensorflow as a subpackage ?

**Comment by gunan** [comment]
With the latest bazel releases, it should be possible to build TensorFlow as a subproject quite easily. Now you can avoid needing to run `configure` script with having a `bazelrc` file with the necessary options in your primary project. An example project that uses TensorFlow as a subproject you can look into `tensorflow/serving`. 
I know that there are still some kinks that need to be straightened out. We can discuss particular problems that immediately block you and try to work around them or apply necessary fixes to TensorFlow.

Could you specify any blocking issues you have?

**Comment by Mistobaan** [comment]
I tried to create a simple Python library that depends on the `./tensorflow` workspace configured like in #12735,  and then I try to create a pip package that contains everything embedded (tensorflow + your library). 
A simple rule like this will fail with the advanced options enabled. 
```python
py_library(
name = 'mylibrary',
deps = [
    "@org_tensorflow//tensorflow/tensorflow_py"
])
```
This is useful for training on Google ML Engine because you can have a single bazel target that packages everything and runs the job from a single project with the exact binary configuration. Otherwise, you have to do many steps separately (package Tensorflow, then package your library) and then specify it on the google cloud ml job library target both zips.  

Maybe I am doing something wrong. A small GitHub repo showing how is done using the extra configurations (XLA, MLK, CUDA) parameters would be useful as a reference.

**Comment by raraujosc** [comment]
The tensorflow/serving project still says we need to run ./configure to be able to build tensorflow: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md

Is there any example of anyone using tensorflow with bazel without running ./configure? We just tried and it fails because it can't find these files: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/git/BUILD#L10

**Comment by feliwir** [comment]
Any updates on this?

**Comment by sushreebarsa** [comment]
@Mistobaan This is not yet implemented nor any workaround available it seems, Please refer the existing projects like tensorflow/serving that build TensorFlow as an external dependency and could you try adapting their scripts to your specific needs. If you already have TensorFlow installed, setting up custom targets to link against it remains a viable option. You may also consider smaller libraries like TensorFlow Lite or TensorFlow.js if your project doesn't require the full TensorFlow stack.

Please create a new ticket if you still have a concern!
Thank you!
