### ISSUE TITLE
C++ tensorflow interface is taking too long to terminate and return the calculated graph output.

### ISSUE THREAD

**Issue by snageshrao** [tensorflow/tensorflow#12779]
Hi All,

I am loading a trained graph (from python) in c++ as explained in the below links,

1. https://medium.com/@hamedmp/exporting-trained-tensorflow-models-to-c-the-right-way-cf24b609d183

2. https://medium.com/jim-fleming/loading-a-tensorflow-graph-with-the-c-api-4caaff88463f

I am using this tf feature in larger c++ application, the working is as follows, main function creates a process that will load the graph, calculate and return the output.  This process will be called every  ~0.1 seconds.  The interface works fine, however it takes rather long (~1 second) to terminate and return the value to main.  I have also timed duration from loading the graph until return, within the tf api, it takes ~0.015 seconds. 

I am unable to figure out the reason for this delay, I am not sure if it is due to c++ createprocess or tf sesion handling, can someone help me to address this issue. 

I have also posted the same question in  stackoverflow, which got down voted a lot, as I am unable to solve this problem I am posting it here too, sorry if it is not the correct platform.

I am using python 3.5 (Anaconda 4.2.0) on a Windows 7 system. 
tensorflow CPU version 1.2.0
bazel 0.5.3
VS 2015
 
### Describe the problem
C++ tensorflow interface is taking too long to terminate/return the calcualted graph output. 

### Source code / logs
https://github.com/snageshrao/tfCPPExample

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by snageshrao** [comment]
Hi Justine,
I have already asked this question in stackoverflow and had no luck over there, it seems like the delay is caused due to loading of tensorflow dependencies which are linked during bazel build, can you suggest me how to address this issue. 
Thank you,
