### ISSUE TITLE
imagePickerController for iOS , not recognize 

### ISSUE THREAD

**Issue by tikamsingh** [tensorflow/tensorflow#12788]
Hello I have created pb and txt file for some specific images and want to test with same image. taking that image  from Gallery in iPhone Device and trying to recognise but its not working properly.

Can you please suggest.

How we can use tensor flow in Gallery Images. 
what size are required to use it.

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
