### ISSUE TITLE
Sqeezenet pretrained model

### ISSUE THREAD

**Issue by ashishagni5** [tensorflow/tensorflow#12787]
Where can I find the pretrained squeezenet model using CIFAR or image net data sets? (if possible on tensorflow)
I would like to use that to re train for some new classes for classification.

**Comment by nitish11** [comment]
There are few resources related to Squeezenet at the below link : 

https://github.com/DeepScale/SqueezeNet

**Comment by ashishagni5** [comment]
Ya this I have seen. But I am very new to ML field. I want to know how to use it too.
It is not so descriptive.

**Comment by ashishagni5** [comment]
@nitish11 Request you to answer specifically. Many generic resources are available online. My requirement is retraining for classification using image net, CIFAR for squeezenet.

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
