### ISSUE TITLE
Arch doesn't support it

### ISSUE THREAD

**Issue by Sherif89** [tensorflow/tensorflow#1279]
After `sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl` or as root, I got:
`tensorflow-0.7.1-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.`

It seems it doesn't work with Python 3. What should I do?

**Comment by ppwwyyxx** [comment]
Well you can use Python2 on Arch
```bash
sudo pacman -S python2-pip
sudo pip2 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
```

**Comment by vrv** [comment]
- Some people said that renaming cp34 to cp35 doesn't work for them, but you are welcome to try it before installing.
- If you want to install for python3, use the url the python3 wheel which is listed on our download page, and it should work.

**Comment by Sherif89** [comment]
Like `pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp35-none-linux_x86_64.whl`? The output is:
`  HTTP error 404 while getting https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp35-none-linux_x86_64.whl
  Could not install requirement tensorflow==0.7.1 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp35-none-linux_x86_64.whl because of error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp35-none-linux_x86_64.whl
Could not install requirement tensorflow==0.7.1 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp35-none-linux_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp35-none-linux_x86_64.whl for URL https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp35-none-linux_x86_64.whl`

**Comment by ppwwyyxx** [comment]
If you want to give a try to 3.4 prebuilt, you need to download the 3.4 binary and then rename it to 3.5:
```bash
wget https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp34-none-linux_x86_64.whl -O tensorflow-0.7.1-cp35-none-linux_x86_64.whl 
sudo pip install --upgrade tensorflow-0.7.1-cp35-none-linux_x86_64.whl 
```
There is no binary for 3.5, so this is just a hack that may not work.

**Comment by Sherif89** [comment]
OK. At least the python 2's one worked.

**Comment by goodmami** [comment]
Alternatively, install Python3.4 (e.g. from https://aur4.archlinux.org/packages/python34) then create the virtualenv for that version:

```bash
$ virtualenv -p python3.4 --system-site-packages ~/tensorflow
```
