### ISSUE TITLE
feature request: could tfdbg dump out debug data by specified step range?

### ISSUE THREAD

**Issue by luchensk** [tensorflow/tensorflow#12793]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.12.4(BuildVersion: 16E195) 
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: ('v1.3.0-rc1-1702-g512d3d086', '1.3.0')
- **Python version**: Python 2.7.13 (default, Apr  4 2017, 08:47:57)
- **Bazel version (if compiling from source)**: 0.5.4-homebrew(Build time: Fri Aug 25 16:55:29 2017 (1503680129))
- **CUDA/cuDNN version**: null
- **GPU model and memory**: null
- **Exact command to reproduce**: sess = dumping_wrapper.DumpingDebugWrapperSession(sess, session_root="<dump_path>", log_usage=False)

### feature request description
I find that DumpingDebugWrapperSession in [dumping_wrapper.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/debug/wrappers/dumping_wrapper.py#L31) dumps debug data for each step, which makes the training very slow with hundreds (thousands?) of small files being generated. In fact, sometimes it is not necessary for us to need the information of all steps to debug.
So, could tfdbg dump out debug data by specified step range? Thanks.

**Comment by caisq** [comment]
@luchensk 

The constructor of `tf_debug.DumpingDebugWrapper` provides a keyword argument called `watch_fn`, which can be used to control what tensors get watched on each run. `watch_fn` is a callable that takes fetch and feed names as input arguments and out puts an instance of [`tf_debug.WatchOptions`](https://www.tensorflow.org/api_docs/python/tfdbg/WatchOptions). The following example shows how to let the DumpingDebugWrapper dump to disk only for the 100th to 200th `Session.run()` calls:

``` python
counter = 0
def my_watch_fn(fetches, feeds):
  del fetches, feeds  # Not used. But you could use them to dump runs of specific fetches/feeds.
  watch_opt = tf_debug.WatchOptions(debug_ops="DebugIdentity", node_name_regex_whitelist=r".*" if (counter >= 100 and counter < 200) else r"$^") 
  counter += 1
  return watch_opt

sess = tf_debug.DumpingDebugWrapperSession(sess, watch_fn=my_watch_fn)
# ...
```

**Comment by luchensk** [comment]
@caisq Thanks, I will try it later.
