### ISSUE TITLE
UINT8 is used but only partly supported in the Java API.

### ISSUE THREAD

**Issue by andrewcmyers** [tensorflow/tensorflow#12797]
The datatype uint8 exists in the Java API (see DataType.UINT8) and is used by the LabelImage program. However, it does not seem to be fully supported. In particular, elemByteSize() in tensor_jni.cc does not have a case for TF_UINT8, which prevents uint8 tensors from being created or extracted from TensorFlow.

**Comment by drpngx** [comment]
/CC: @asimshankar 

It looks like you have a pending PR to fix this, LMK if you expect some action on our part.

**Comment by asimshankar** [comment]
@andrewcmyers : Thanks for pointing this out. Do you want to package the commit in your repository as an independent PR?

**Comment by andrewcmyers** [comment]
It's a bit entangled with the generics stuff. I could create a separate commit that fixes this problem, I guess. That would create some conflicts to iron out later.

**Comment by quaeler** [comment]
The genesis of the fix is due to [a merge down for the generics stuff,](https://github.com/tensorflow/tensorflow/pull/11535/commits/46981fb61c393a1b32b6e4569ac2e3e5c47b240f) so it makes more sense (imo) to include it in the PR for the generics stuff and not as a postscript to it.
