### ISSUE TITLE
tensorflow create myOwn_op.dll on windows

### ISSUE THREAD

**Issue by zhxx1987** [tensorflow/tensorflow#12803]
Hi tf developers, I have one request regarding tensorflow's windows version. 

I have tensorflow+gpu successfully built on windows 10 with visual studio 2015, from the source code.
as a result, I get tensorflow.dll and tensorflow.lib.
I have CUDA8.0 and cudnn 5.0; with a gtx 1080 gpu equipped. 

however, my question is not about building and compiling tensorflow.
it is about creating tensorflow plugins. 
I followed the tutorial https://www.tensorflow.org/extend/adding_an_op to construct my own "plug-in".
and then I tried to compile a windows .dll; so windows would not export symbols automatically for me .
then I compile a static lib first and used your tools 
 /tensorflow/contrib/cmake/tools/create_def_file.py
to create a .def file for me and eventually used that to compile the .dll.

however, in my python code, when I tried to __correlation__ =  tf.load_op_library(correlation.dll) and I called      __correlation__.correlation()
with Correlation registered using REGISTER_OP("Correlation");
it still tells me
 AttributeError: module '7b088d8b906b36d3e50721b0adbaaa6a' has no attribute 'correlation'

I think this is just  a windows (or cl compiler) issue, maybe what REGISTER_OP("Correlation") did is just not picked up by the compiler,

so is there any thing I can do to make this happen on windows??

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by zhxx1987** [comment]
Hi I think "making the tensorflow integration with windows more smooth"
should in general be a feature request,
consider it will benefit a large community such as real-time computer
graphics and video games etc.
