### ISSUE TITLE
Feature request - non-scalar Multinomial draws

### ISSUE THREAD

**Issue by tudaga** [tensorflow/tensorflow#12804]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.12.6 
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.2.0-rc2-21-g12f033d 1.2.0
- **Python version**: 3.6.2
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: NA

### Describe the problem
For Multinomial distribution the _sample_n method does not support total_count to be a vector and throws a 
```
NotImplementedError("Sample only supported for scalar number of draws.") 
```
[https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/python/ops/distributions/multinomial.py#L236](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/python/ops/distributions/multinomial.py#L236)
It would be a really useful feature to add. 

### Source code / logs
NA

**Comment by wt-huang** [comment]
Closing as this is resolved
