### ISSUE TITLE
Speech-Recognitin issue

### ISSUE THREAD

**Issue by Akansha62** [tensorflow/tensorflow#12807]
Hi,

While running  "python tensorflow/examples/speech_commands/train.py"

I am getting following issue.::
"ImportError: cannot import name audio_ops"

Please help.

**Comment by drpngx** [comment]
This is a known issue, we haven't released the drivers.

https://stackoverflow.com/questions/45952387/anaconda-install-of-tensorflow-missing-audio-ops-from-contrib-framework
