### ISSUE TITLE
Implementation of CW-RNN?

### ISSUE THREAD

**Issue by aidangomez** [tensorflow/tensorflow#1280]
Has anyone considered implementing the CW-RNN architecture discussed here: http://arxiv.org/abs/1402.3511 

The cited results seem extremely promising, and the structure is quite simple. If it's not in the pipeline or already present, I may try implementing it myself.

**Comment by yash14123** [comment]
@aidangomez I would like to help you out! :)

**Comment by aidangomez** [comment]
@yash14123 Awesome! We'll see what Google has to say about any already present implementations.

**Comment by girving** [comment]
We'd love to have it in the models repo if anyone writes it: https://github.com/tensorflow/models!

**Comment by elvinpoon** [comment]
I'm working on it

**Comment by aidangomez** [comment]
Just opened a pull request

**Comment by girving** [comment]
@aidangomez Can you link to the pull request?

**Comment by aidangomez** [comment]
Here: https://github.com/tensorflow/models/pull/198

**Comment by elvinpoon** [comment]
I see. Let me know if u need any help.


________________________________
发件人: Aidan Gomez <notifications@github.com>
发送时间: 2016年6月13日 23:45
收件人: tensorflow/tensorflow
抄送: elvinpoon; Manual
主题: Re: [tensorflow/tensorflow] Implementation of CW-RNN? (#1280)


Here: tensorflow/models#198<https://github.com/tensorflow/models/pull/198>

―

**Comment by aidangomez** [comment]
@girving The PR got updated recently and has a unit test that suggests everything is working as expected. Probably getting near what's acceptable for merger, do you mind having a look?

**Comment by girving** [comment]
@aidangomez On leave, so someone else will have to review.

**Comment by tfboyd** [comment]
Closing.  The PR is still open.  I am not sure why it did not get resolved and the discussion should continue there.
