### ISSUE TITLE
Wrong error message during compiling

### ISSUE THREAD

**Issue by eaperz** [tensorflow/tensorflow#12821]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Amazon Linux 2017.03
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: release v1.3.0
- **Python version**: 3.6.2
- **Bazel version (if compiling from source)**: 0.5.4
- **CUDA/cuDNN version**: CUDA 7.5/cuDNN 5.1.10
- **GPU model and memory**: Tesla K80
- **Exact command to reproduce**: remove _patch_ command and try to compile

### Describe the problem
There's a wrong error message when you try to compile TensorFlow without `patch` command installed. It's not a big deal but could take a couple of hours to figure it out.

### Source code / logs
`
ERROR: /home/ec2-user/workplace/tensorflow/tensorflow/tools/pip_package/BUILD:100:1: no such package '@boringssl//': Traceback (most recent call last):
	File "/home/ec2-user/workplace/tensorflow/tensorflow/workspace.bzl", line 116
		_apply_patch(repo_ctx, repo_ctx.attr.patch_file)
	File "/home/ec2-user/workplace/tensorflow/tensorflow/workspace.bzl", line 107, in _apply_patch
		_execute_and_check_ret_code(repo_ctx, cmd)
	File "/home/ec2-user/workplace/tensorflow/tensorflow/workspace.bzl", line 91, in _execute_and_check_ret_code
		fail("Non-zero return code({1}) when ...))
Non-zero return code(256) when executing 'patch -p1 -d /home/ec2-user/.cache/bazel/_bazel_ec2-user/4ee13f1db5bfc278f4537815cf99cd27/external/boringssl -i /home/ec2-user/workplace/tensorflow/third_party/boringssl/add_boringssl_s390x.patch':
Stdout:
Stderr: java.io.IOException: Cannot run program "patch" (in directory "/home/ec2-user/.cache/bazel/_bazel_ec2-user/4ee13f1db5bfc278f4537815cf99cd27/external/boringssl"): error=2, No such file or directory and referenced by '//tensorflow/tools/pip_package:licenses'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
`

**Comment by drpngx** [comment]
@MarkDaoust we should update the pre-requisites.

Thank for reporting this, @eaperz! If you want to send a PR, that's also great.

**Comment by facaiy** [comment]
Is it good to check whether `patch` is installed before it is invoked [here](https://github.com/tensorflow/tensorflow/blob/12a628a623a5dae81b8fc699792eaf414e6ace41/tensorflow/workspace.bzl#L110)?

**Comment by eaperz** [comment]
I think it should be checked in a pre-requisite stage, along with all other pre-requisites to build. Unfortunately it's my first contact with tensorflow and I have no idea where in the code is this verification.

**Comment by eaperz** [comment]
I think it should be checked in a pre-requisite stage, along with all other pre-requisites to build. Unfortunately it's my first contact with tensorflow and I have no idea where in the code is this verification done.

**Comment by facaiy** [comment]
@eaperz  I agree with you. Since I'm not familiar with bazel, I don't know how to do pre-check yet.

**Comment by drpngx** [comment]
Best place would probably be in the `configure`(https://github.com/tensorflow/tensorflow/blob/master/configure.py) script.
