### ISSUE TITLE
Get an error when building the Op library

### ISSUE THREAD

**Issue by MisayaZ** [tensorflow/tensorflow#1282]
When I Build the Op library, I got the error :1234: 
In file included from /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/op.h:22:0,
                 from zero_out.cc:1:
/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:22:35: fatal error: google/protobuf/arena.h: No such file or directory
 #include <google/protobuf/arena.h>

I install tensorflow by pip installation,branch r0.7.

**Comment by girving** [comment]
Can you explain what you mean by "when building the op library"?  Are you trying to build new C++ code (perhaps user defined ops) that depend on TensorFlow?

**Comment by jackpaparian** [comment]
Hi,

I tried to build the zero_out op example from the "Adding a New Op" tutorial, and I'm getting the same errors that MisayaZ got. It looks like the version of Protobuf (protobuf-3.0.0b2) that came with TensorFlow is newer and incompatible with the Protocol Buffer headers used in op_def.pb.h.

Any idea why there's an inconsistency with the versions of Protobuf? Thanks!

**Comment by jackpaparian** [comment]
I originally had the same error as MisayaZ, but it went away when I removed an old Protobuf package that I had installed with yum (I installed TensorFlow and its Protobuf dependency with Pip).

Now I'm getting a different error when I try to compile the ZeroOut Op from the "Adding a New Op" tutorial. This is my error:
In file included from /home/jpaparia/anaconda2/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/op.h:22:0,
                 from zero_out.cc:1:
/home/jpaparia/anaconda2/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/
framework/op_def.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
 #include <google/protobuf/stubs/common.h>
                                          ^
compilation terminated.

Any idea what might cause this error? Thanks!

**Comment by girving** [comment]
To confirm: You can build tensorflow just fine without the `ZeroOut` op, and that error shows up when you add `ZeroOut`?  @keveman: Have you seen that kind of error before?

**Comment by jackpaparian** [comment]
I never had to build TensorFlow before I tried adding the `ZeroOut` op. I just used the package installed through PIP (for Linux with GPU), and that worked without throwing errors.

**Comment by girving** [comment]
Can I see a branch with your change?

**Comment by jackpaparian** [comment]
The TensorFlow package I downloaded from Pip is [here](https://github.com/jackpaparian/tensorflow-package). The code for `ZeroOut` is [here](https://github.com/jackpaparian/tensorflow-package/blob/master/tensorflow/include/tensorflow/core/user_ops/zero_out.cc).
Thanks for your help!

**Comment by girving** [comment]
That's a strange setup.  If you're going to build from source, can you grab tensorflow via git normally rather than checking pip into git?

@keveman: Are we close to replacing the `user_ops` directory with something that doesn't require modifying the tensorflow tree?

**Comment by jackpaparian** [comment]
I was under the impression that we don't need to build from source in order to add a new op. The tutorial says 
> Must have installed the TensorFlow binary, or must have downloaded TensorFlow source, and be able to build it.

so I thought we could just add code to our TensorFlow package that we downloaded from Pip. Do we need to build from source in order to add a new op?

**Comment by keveman** [comment]
@jackpaparian, you are right, you should be able to build a new op with Tensorflow binary pip installed.  Can you try installing the pip package from [here](http://ci.tensorflow.org/job/tensorflow-master-gpu_pip/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.7.1-py2-none-any.whl) and then try compiling your user op? The pip package for r0.7 had some issues related to user ops. See #1569 for some related discussion.

**Comment by jackpaparian** [comment]
@keveman, thanks for your response. I installed TensorFlow from the pip package you pointed me to. I'm now getting a new error when I compile `ZeroOut`:

`In file included from zero_out.cc:1:0:
/home/jpaparia/anaconda2/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/op.h:26:62: fatal error: tensorflow/core/framework/selective_registration.h: 
No such file or directory
 #include "tensorflow/core/framework/selective_registration.h"
                                                                                               ^
compilation terminated.`

I don't seem to have the `selective_registration.h` file that `zero_out.cc` requires. Any idea why that file didn't get installed?

**Comment by keveman** [comment]
Looks like a bug that creeped in recently. Fix on the way. Sorry about that.

**Comment by keveman** [comment]
1a25c92 adds selective_registration.h to the pip package. Please verify with the most recent pip package [here](http://ci.tensorflow.org/job/tensorflow-master-gpu_pip/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.7.1-py2-none-any.whl) and close the issue if successful.

**Comment by jackpaparian** [comment]
I reinstalled TensorFlow with the most recent pip package, and unfortunately I'm still getting the same error about `selective_registration.h`.

**Comment by keveman** [comment]
I ran the following and things worked for me : 

    $ pip install -U http://ci.tensorflow.org/job/tensorflow-master-gpu_pip/lastStableBuild/artifact/pip_test/whl/tensorflow-0.7.1-py2-none-any.whl
    $ TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
    $ g++ -std=c++11 -shared zero_out.cc -o zero_out.so -fPIC -I $TF_INC

I ran this inside a virtualenv, on a Ubuntu 14.04. I can definitely see that the file is available

    $ ls local/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/selective_registration.h 
    local/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/selective_registration.h

Perhaps you are still somehow installing an older whl file.

**Comment by jackpaparian** [comment]
Cool, compiling with those flags worked for me too. I had been including extra compile flags used for r0.7. Thanks for your help!
