### ISSUE TITLE
Feature Request: ADAG

### ISSUE THREAD

**Issue by tmulc18** [tensorflow/tensorflow#12838]
It seems difficult to add [ADAG](http://joerihermans.com/ramblings/distributed-deep-learning-part-1-an-introduction/)  as an optimizer, because by default with tf.train.replica_device_setter(), all variables get assigned to a parameter server (ps).  Thus, it is difficult to update variables locally because the optimizer first pushes updates to the ps, allowing all other workers to see its updates.  If anyone know how to create local copies of variables, I can provide an example implementation.

**Comment by cy89** [comment]
@mrry, can you help?

**Comment by yaroslavvb** [comment]
@tmulc18 don't use replica_device_setter, instead write your own setter which does all the fancy logic

**Comment by tmulc18** [comment]
@yacoder thanks that tip helped!  I was able to implement ADAG but only with the worker updates using SDG.  When using any optimizer that creates variables, I'm having issues because the variables are by default global variables but they are assigned to the local device.  I'm able to get training to work by saying that each worker is the chief worker, which is a terrible hack. Is there a way to simply remove variables from collections, or have a collection scope similar to variable scope?

**Comment by tmulc18** [comment]
I posted a hacky solution [here](https://github.com/tmulc18/Distributed-TensorFlow-Guide/blob/master/ADAG/ADAG.py).  It would be nice to have an actually function call from within TensorFlow before closing this issue, though.

**Comment by wt-huang** [comment]
Closing as this has been resolved.
