### ISSUE TITLE
DEFINE_bool alias not working on Mac Python test-on-install

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorflow#1283]
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

### Environment info
Operating System: Mac

If installed from binary pip package, provide: This error occurs in Mac Python (2 and 3) test-on-install

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

If installed from sources, provide the commit hash:

### Steps to reproduce
1. Go to http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/9/TF_BUILD_CONTAINER_TYPE=CPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=mac-slave/console 
2. See failures in tests: 
tensorflow/python/platform/default/flags_test.py
tensorflow/python/tools/graph_metrics_test.py
3. Notice that both failures complain about "DEFINE_bool" not being an attribute. 

4. Interestingly, "DEFINE_bool" is found at: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/default/_flags.py#L111

But somehow it is not recognized during Python test-on-install on Mac. 

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
(See above)

**Comment by caisq** [comment]
@vrv This is related to CL 115364038

**Comment by caisq** [comment]
On closer examination, this seems to be a problem related to "pip install" on Mac.

**Comment by girving** [comment]
@caisq: Assigning to you; feel free to reassign.  What's the status currently?

**Comment by aselle** [comment]
Unless there any updates, I will close this issue in 7 days.

**Comment by girving** [comment]
@aselle Only Googlers have commented on this thread so far, so awaiting response seems inapplicable.

**Comment by caisq** [comment]
This issue has been fixed. The aforementioned two tests have been passing on Mac.
