### ISSUE TITLE
Unable to compile TF 1.3 from source using full MKL

### ISSUE THREAD

**Issue by qtdaniel** [tensorflow/tensorflow#12849]
Steps to reproduce:

    git clone https://github.com/tensorflow/tensorflow.git test
    cd test
    git checkout r1.3
    yes "" | TF_NEED_CUDA=0 TF_NEED_MKL=1 TF_DOWNLOAD_MKL=0 MKL_INSTALL_PATH=<path>/l_mkl_2017.3.196/inst/mkl ./configure
    bazel build --config=mkl -c opt --verbose_failures //tensorflow/tools/pip_package:build_pip_package

OS version: Ubuntu Linux 14.04
Bazel version: 0.5.3

Error message:

    ERROR: missing input file '//third_party/mkl:libmklml_intel.so'
    ERROR: <path>/tensorflow/test/third_party/mkl/BUILD:16:1: //third_party/mkl:intel_binary_blob: missing input file '//third_party/mkl:libmklml_intel.so'
    Target //tensorflow/tools/pip_package:build_pip_package failed to build
    ERROR: <path>/tensorflow/test/third_party/mkl/BUILD:16:1 1 input file(s) do not exist

The `configure` script is creating symlinks in `third_party/mkl/` for `libmkl_rt.so` ([see here](https://github.com/tensorflow/tensorflow/blob/r1.3/configure#L260)), which is fine, but not for `libmklml_intel.so` ([see here](https://github.com/tensorflow/tensorflow/blob/r1.3/configure#L264)), which doesn't exist in the full MKL distribution. However [`third_party/mkl/BUILD` references `libmklml_intel.so`](https://github.com/tensorflow/tensorflow/blob/r1.3/third_party/mkl/BUILD#L20). Is this a bug or is use of the full MKL library not supported in TensorFlow 1.3?

**Comment by drpngx** [comment]
@gunan do you happen to know on the top of your head?

**Comment by gunan** [comment]
AFAICT, my changes are not in 1.3 branch.
At master, you should only need to configure, then run `bazel build` with `--config=mkl`, and that should be it.
On 1.3, we still use the way contributed by intel. I believe this was not a very well tested build path, so it is likely this was broken all along.
I would recommend setting `TF_DOWNLOAD_MKL` to 1 and see if it works when configure downloads MKL itself.

**Comment by qtdaniel** [comment]
Yes, it works with `TF_DOWNLOAD_MKL=1` but this downloads MKL-DNN, not the full MKL. If one wants to build MKL support into Eigen then, I believe, one needs to use the full MKL but maybe MKL support in TensorFlow is limited to MKL-DNN? Comments in the r1.3 `configure` script seem to imply that it should support the full MKL which is why I tried it.

By the way, the [instructions on the Intel site](https://software.intel.com/en-us/articles/tensorflow-optimizations-on-modern-intel-architecture) for building TensorFlow with MKL (which have also been communicated on various TensorFlow support channels) are, I believe, incorrect. It says one should build with the command `bazel build --config=mkl --copt="-DEIGEN_USE_VML" -c opt //tensorflow/tools/pip_package:build_pip_package` but this has two potential errors:

1. One should include `--config=opt` in addition to `--config=mkl` to enable all the regular (non-MKL) CPU optimizations in addition to the MKL features.
2. The flag to compile MKL vector operations into Eigen is `EIGEN_USE_MKL_VML`, not `EIGEN_USE_VML` ([as explained here](https://eigen.tuxfamily.org/dox/TopicUsingIntelMKL.html)).

Correcting the second of these two potential errors yields a new issue in TensorFlow: it fails to compile with a bazel error (something about MKL header files getting included without them being declared in a BUILD file). I don't have the details of that error to hand but it should probably be logged as separate issue anyway and if the MKL build options are changing in the next release maybe it's best to just wait.

I hope the next version of TensorFlow will make clear which of the nine potential configurations of Eigen and TF each built with one of (no MKL, MKL-DNN, full MKL) is supported. It's also not clear whether the optional use of CUDA is an orthogonal consideration or could interact with the use (or not) of MKL/MKL-DNN.

**Comment by gunan** [comment]
@tobyboyd for more information on this.

MKL support is at the moment provided by Intel, not officially by us yet.
That is why installation guides are not on our webpage, but on intel's page.
I recommend reaching out to them for support with the above questions.

**Comment by qtdaniel** [comment]
Thanks. I've started corresponding with Intel here: https://software.intel.com/en-us/comment/1911911

**Comment by qtdaniel** [comment]
A workaround has been provided for using the full MKL with TF r1.3; details at the Intel forums link above.

Additional information about building TF with the full MKL, including Eigen-MKL integration, can be found in the comments attached to this document: https://software.intel.com/en-us/articles/tensorflow-optimizations-on-modern-intel-architecture
