### ISSUE TITLE
Unable to install tensorflow=1.0.0

### ISSUE THREAD

**Issue by ellurunaresh** [tensorflow/tensorflow#12846]
I have been trying to install tensorflow 1.0.0 using pip in Anaconda environment. I found the below error while installation. I have seen previous posts in github and stackover flow but I couldn't find the solution.

(C:\Users\naresh.kumar\AppData\Local\Continuum\Anaconda3) C:\Users\naresh.kumar>**pip install --ignore-installed --upgrade  https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0-cp35-cp35m-win_x86_64.whl**

pip = 9.0.1
python = 3.6.1
Anaconda=4.3.21
Please help me out how to solve this issue.

**Comment by aabirabubaker** [comment]
Have you tried
`conda install tensorflow`?
This is one of the best things about Anaconda - it simplifies package installation hugely.

**Comment by ellurunaresh** [comment]
Yes I have tried. But it installs tensorflow=1.3.

**Comment by georgh** [comment]
`conda install tensorflow=1.0 
`
works on my system. This question should be asked in Stackoverflow!

**Comment by gunan** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
