### ISSUE TITLE
tf.qint8: Quantized 8-bit signed integer (Definition, code piece, examples)

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/tensorflow#12854]
What does quantized mean in this scenario?  Could you please explain with an example and a descriptive definition along with the code used for this?

tf.qint8: Quantized 8-bit signed integer.
What does quantized mean in this scenario?

tf.quint8: Quantized 8-bit unsigned integer.
What does quantized mean in this scenario?

tf.qint16: Quantized 16-bit signed integer.
What does quantized mean in this scenario?

tf.quint16: Quantized 16-bit unsigned integer.
What does quantized mean in this scenario?

tf.qint32: Quantized 32-bit signed integer.
What does quantized mean in this scenario?

tf.resource: Handle to a mutable resource.
What does mutable resource mean?

**Comment by printdhruv** [comment]
I guess this [link](https://www.tensorflow.org/performance/quantization) might help you to understand Quantization!

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
