### ISSUE TITLE
Make RNN cells add bias to the bias variable collection

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#1286]
Currently helper layers like fully_connected add their bias variables to the 'bias' collection, which is a useful convenience. The RNN cell code doesn't do that, and it would be nice if it did for consistency. Needless to say the same is true for the main weights and the 'weights' collection.

**Comment by yash14123** [comment]
I am just confirming. The way they are added here right?
https://github.com/tensorflow/tensorflow/blob/39b332ba07db732ff8e0a07459e74995b92aaa83/tensorflow/contrib/layers/python/layers/layers_test.py

**Comment by alquraishi** [comment]
The way they're added [here](https://github.com/tensorflow/tensorflow/blob/39b332ba07db732ff8e0a07459e74995b92aaa83/tensorflow/contrib/layers/python/layers/layers.py#L111).

**Comment by yash14123** [comment]
Would work on it from tomorrow. :)

**Comment by ebrevdo** [comment]
This will happen once we stop using linear() in the rnn cells and use layers directly.  Lukasz is working on that.

**Comment by girving** [comment]
@lukaszkaiser: @ebrevdo says this will happen automatically as a consequence of other work you're already doing.  Is that right?

**Comment by lukaszkaiser** [comment]
Eugene is right that it'll happen when we replace linear with layers, which should happen (as part of the general move to layer/tf.learn, right?). I'm not working on it right now though.

**Comment by ebrevdo** [comment]
We need an ETA on the move of contrib.layers to core.

**Comment by lukaszkaiser** [comment]
Indeed. Should we mark this in some way to indicate it's blocked?

**Comment by girving** [comment]
@lukaszkaiser I don't know any way to do that, unfortunately.

**Comment by lukaszkaiser** [comment]
Since this is part of a general move of layers/slim into core and merging RNN with that, I'm closing it for now.
