### ISSUE TITLE
Is it a bug of tf.map_fn?

### ISSUE THREAD

**Issue by gauss-clb** [tensorflow/tensorflow#12879]
Look at the code:

```python
import tensorflow as tf
import numpy as np

elems = [tf.constant([1,2,3],dtype=tf.int64)]
alternates = tf.map_fn(lambda x: x, elems, dtype=tf.int64)
with tf.Session() as sess:
    print(sess.run(alternates))
```

It will raise a error, but when I use tuple instead of list, it works well.

```python
import tensorflow as tf
import numpy as np

elems = (tf.constant([1,2,3],dtype=tf.int64))
alternates = tf.map_fn(lambda x: x, elems, dtype=tf.int64)
with tf.Session() as sess:
    print(sess.run(alternates))
```
Is it a bug?
If you want to know more, llo at the discussion on [stackoverflow](https://stackoverflow.com/questions/46096767/how-to-explain-the-result-of-tf-map-fn).

**Comment by yongtang** [comment]
@gauss-clb I think to specify a tuple with one element you will need comma like `elems = (tf.constant([1,2,3],dtype=tf.int64),)`?

**Comment by gauss-clb** [comment]
Yes, you are right, but I don't know why it will raise a error. I think it can work according to [api](https://www.tensorflow.org/versions/master/api_docs/python/tf/map_fn).

**Comment by ppwwyyxx** [comment]
fn: The callable to be performed. It accepts one argument, which will have the same (possibly nested) structure as elems. Its output must have the same structure as dtype if one is provided, otherwise it must have the same structure as elems.


So the fix to the first snippet would be:
```python
elems = [tf.constant([1,2,3],dtype=tf.int64)]
alternates = tf.map_fn(lambda x: x[0], elems, dtype=tf.int64)
with tf.Session() as sess:
    print(sess.run(alternates))  # [1,2,3]
```
