### ISSUE TITLE
Efficient way to load a model over 2GiB with C++ interface?

### ISSUE THREAD

**Issue by suzhaolong** [tensorflow/tensorflow#12873]
Hi,all
When applying TF model with its C++ interface, freeze_graph operations, for the graph file and the cpk file, are required. This operation will then generate a dumped binary protobuffer file.

However, protobuffer does not support to dump a file that is larger than 2GiB.

In this case, what's the right way to load a big model in TF, with its C++ interface? Any clues will be appriciated.

Thank you

**Comment by drpngx** [comment]
The checkpoint should not be limited to 2GB for saving. You don't need to freeze the graph. You can create a saver in the graph, which you can use with `session.Run`.  Something like this:
```
  const tensorflow::Status status = session->Run(
      {{"save/Const", "/path/to/checkpoint"}}, {} /* no output */,
      {"save/restore_all"}, nullptr /* no output */);
```

**Comment by suzhaolong** [comment]
@drpngx  I have tried, it works, thank you!

**Comment by reedwm** [comment]
Closing since issue is resolved.
