### ISSUE TITLE
python wrapper around libtensorflow

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#12875]
I wish to use tensorflow as a standalone library. I  have  `libtensorflow.so`. How do I bridge it to python so I can use it for standalone purpose?or is there any github repo for the same

**Comment by quaeler** [comment]
If you have the tensorflow source checked out locally, you could build a pip installer package from that source and install it into a virtualenv as discussed here: https://github.com/tensorflow/tensorflow/issues/12722#issuecomment-326769780
