### ISSUE TITLE
error in Building tensor flow. [sun.security.validator.ValidatorException:]

### ISSUE THREAD

**Issue by ravispatil** [tensorflow/tensorflow#12874]
== cat /etc/issue ===============================================
Linux ravi 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.3 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux ravi 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Hello Below is compilation error i am getting.

$~/bin/bazel build -c opt --config=opt //tensorflow/tools/pip_package:build_pip_package
Extracting Bazel installation...
...........
ERROR: /home/ravi.spatil/LinuxShare/caffe_opecv_resources/mobilenet/tensorflow_ori/tensorflow/tools/pip_package/BUILD:101:1: no such package '@nsync//': Error downloading [https://github.com/google/nsync/archive/ad722c76c6e6653f66be2e1f69521b7f7517da55.tar.gz] to /home/ravi.spatil/.cache/bazel/_bazel_ravi.spatil/39b7c1709071717822a0ecd1200753ba/external/nsync/ad722c76c6e6653f66be2e1f69521b7f7517da55.tar.gz: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '//tensorflow/tools/pip_package:licenses'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted
INFO: Elapsed time: 28.497s
FAILED: Build did NOT complete successfully (106 packages loaded)

Below is system information.
--------------------------------------

== check pips ===================================================
numpy (1.13.1)
protobuf (3.4.0)
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.5)

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
../tools/tf_env_collect.sh: line 105: nvidia-smi: command not found

**Comment by quaeler** [comment]
It looks like the current nsync package has been signed in a manner which Bazel can't verify (is that correct @jart?)

**Comment by ravispatil** [comment]
Hello, i solved it by changing branch r1.3 ->./configure -> build.
May be issue with latest master code.
