### ISSUE TITLE
ImportError: cannot import name 'c_einsum'

### ISSUE THREAD

**Issue by ebonat** [tensorflow/tensorflow#12897]
I updated tensorflow from 1.1.0 to 1.3.0 using the wheel file: tensorflow-1.3.0-cp35-cp35m-win_amd64.whl and in the line:

`import tensorflow as tf`

I got the following error:

```
from numpy.core.multiarray import c_einsum
ImportError: cannot import name 'c_einsum'
```

Any help?

**Comment by drpngx** [comment]
Do you have the full stack trace? What's the numpy version?

**Comment by ebonat** [comment]
hi drpngx,

i have fixed this issue by updating numpy to version 1.13.1. 

thank you for a good question?

-ernest
