### ISSUE TITLE
dlopen error when using TF_LoadLibrary

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/tensorflow#12895]
I'm trying to use `TF_LoadLibrary` on a mac and I keep getting errors such as:
```
Caused by: org.platanios.tensorflow.jni.TensorFlow$NativeException: dlopen(/var/folders/rw/lqrc8nk52kqcc4_zq3c2b6dh0000gn/T/tensorflow_scala_native_libraries7467192138547554485/libtensorflow_ops.dylib, 6): Symbol not found: __ZN10tensorflow15shape_inference12UnknownShapeEPNS0_16InferenceContextE
  Referenced from: /var/folders/rw/lqrc8nk52kqcc4_zq3c2b6dh0000gn/T/tensorflow_scala_native_libraries7467192138547554485/libtensorflow_ops.dylib
  Expected in: flat namespace
 in /var/folders/rw/lqrc8nk52kqcc4_zq3c2b6dh0000gn/T/tensorflow_scala_native_libraries7467192138547554485/libtensorflow_ops.dylib
```
The same thing happens when I try to load the compiled dylib file through Python directly. It was compiled it using `-D_GLIBCXX_USE_CXX11_ABI=0` and `-undefined dynamic_lookup` for the linker. @asimshankar

**Comment by asimshankar** [comment]
Unfortunately, loading custom op libraries from the C API isn't fully functional now
(and worked around using [`RTLD_GLOBAL` in Python](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/python/pywrap_tensorflow.py#L40)).

The good news is that @allenlavoie is working on a fix. No immediate ETA, but long story short - loading custom op libraries might not work outside of Python yet, but we're on it.

(Related issue #10454)

**Comment by eaplatanios** [comment]
@asimshankar That's interesting because I also tried to load it using RTLD_GLOBAL. However, on my mac, even `tf.load_op_library(...)` in Python is not working and is throwing the same error.

**Comment by eaplatanios** [comment]
@asimshankar I found out that it's not just RTLD_GLOBAL that matters. The symbols are actually exported through `_pywrap_tensorflow_internal.so` in the Python API. I was only loading `libtensorflow.so` with RTLD_GLOBAL, but that is not enough to make things work. Is there any easy workaround that you can see, until the fix comes out? Thanks! :)

**Comment by eaplatanios** [comment]
A temporary solution would be to replace `exported_symbols.lds` and `version_script.lds` in the `c` directory with `tf_exported_symbols.lds` and `tf_version_script.lds`. This would export all the necessary symbols in `libtensorflow.so`. Is there a reason not to do that for now, until the fix comes out?

**Comment by eaplatanios** [comment]
I just made a PR (#12915) with this proposed fix.

**Comment by eaplatanios** [comment]
@asimshankar @allenlavoie I just realized (after trying it) that pulling the pywrap so file doesn't really work for me because it depends on the Python libraries. Is there no other temporary solution we can use until the fix comes out? Maybe having a separate build target "libtensorflow_all.so", or something like that, that exports everything. Would that be acceptable? Aside from breaking the API, which I agree is not great, the binary increases in size by about 9MB (from ~98MB to ~107MB for Mac). Therefore, I believe that having a separate build target might not be too bad.

I have a package I'm creating and releasing to Sonatype for my Scala API that can optionally include pre-compiled binaries. Given that I use some custom ops, I need to be able to distribute those too and that's why I'm trying to find a temporary solution for the next 1-2 months until the fix is out.

**Comment by eaplatanios** [comment]
As an alternative, I could also add my `ScalaCallback` and `ScalaCallbackStateless` ops with their kernel implementations (similar to that of `py_func`) to the main repository so they're included in the library by default. Would that be acceptable? I feel it interferes more than having a separate build target, but I'm not sure what your opinion is on this.

**Comment by allenlavoie** [comment]
This should be fixed by https://github.com/tensorflow/tensorflow/commit/5c7f9e316d8c7735308a217310350d416d7498cc. Would you mind taking a look? If you also need the C API symbols for your custom ops, you can link against libtensorflow.so (although that will make the custom ops non-portable to other languages).

**Comment by eaplatanios** [comment]
@allenlavoie That's actually great! Thanks! :) I get my code to compile with these changes. I only have one problem, which is that the JVM might invoke the op library loading function multiple times (even if I only do it from a synchronized static block). This is because the TensorFlow library might remain loaded in the background across multiple Java/Scala runs. This results in a fatal error where multiple kernels are registered for the same op. Is there a way to make `REGISTER_KERNEL_BUILDER` conditional on whether a kernel has already been registered for that op? Thanks a lot! :)

**Comment by eaplatanios** [comment]
@allenlavoie FYI, I'm currently doing the following which is a bit ugly:
```
namespace tensorflow {
namespace kernel_factory {

struct KernelRegistration {
  KernelRegistration(const KernelDef& d, StringPiece c,
                     kernel_factory::OpKernelRegistrar::Factory f)
      : def(d), kernel_class_name(c.ToString()), factory(f) {}
  const KernelDef def;
  const string kernel_class_name;
  const kernel_factory::OpKernelRegistrar::Factory factory;
};

auto jvmCallbackOpInitializer = []{
  auto* reg = reinterpret_cast<std::unordered_multimap<string, KernelRegistration>*>(GlobalKernelRegistry());
  if (reg->find(strings::StrCat("JVMCallback:", DeviceTypeString(DEVICE_CPU), ":")) == reg->end()) {
    REGISTER_KERNEL_BUILDER(Name("JVMCallback").Device(DEVICE_CPU), JVMCallbackOp);
    REGISTER_KERNEL_BUILDER(Name("JVMCallbackStateless").Device(DEVICE_CPU), JVMCallbackOp);
  }
  return 0;
}();

}
}
```

**Comment by eaplatanios** [comment]
@allenlavoie Also, would it be easy to also export symbols such as `tensorflow::Graph::AddEdge`, `tensorflow::Graph::RemoveEdge`, `tensorflow::Graph::kControlSlot`, `tensorflow::Node::set_requested_device`, `tensorflow::Node::input_edge`, `nsync::nsync_mu_lock`, and `nsync::nsync_mu_unlock`, in the framework binary?

**Comment by allenlavoie** [comment]
Huh. I'm surprised the static initializers are called multiple times just because the op library is dlopen()ed multiple times, considering that we never dlclose() it. Maybe we could just add RTLD_NODELETE to TF_LoadLibrary? I'll take a look.

At least the tensorflow::Graph symbols should be there already (from //tensorflow/core:framework_internal_impl)?

**Comment by eaplatanios** [comment]
Yeah I was also surprised at that behavior, but I noticed online that other people have had similar experiences by calling TF_LoadLibrary multiple times.

They don't seem to be. I get this error when trying to compile [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/python_api.cc) from outside bazel (i.e., from within my library):
```
Undefined symbols for architecture x86_64:
[error]   "tensorflow::Node::set_requested_device(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
[error]       tensorflow::SetRequestedDevice(TF_Graph*, TF_Operation*, char const*) in tf_python_api.cc.o
[error]   "tensorflow::Graph::RemoveEdge(tensorflow::Edge const*)", referenced from:
[error]       tensorflow::UpdateInput(TF_Graph*, TF_Operation*, int, TF_Output) in tf_python_api.cc.o
[error]       tensorflow::ClearControlInputs(TF_Graph*, TF_Operation*) in tf_python_api.cc.o
[error]   "tensorflow::Graph::kControlSlot", referenced from:
[error]       tensorflow::AddControlInput(TF_Graph*, TF_Operation*, TF_Operation*) in tf_python_api.cc.o
[error]       tensorflow::ClearControlInputs(TF_Graph*, TF_Operation*) in tf_python_api.cc.o
[error]   "tensorflow::Graph::AddEdge(tensorflow::Node*, int, tensorflow::Node*, int)", referenced from:
[error]       tensorflow::UpdateInput(TF_Graph*, TF_Operation*, int, TF_Output) in tf_python_api.cc.o
[error]       tensorflow::AddControlInput(TF_Graph*, TF_Operation*, TF_Operation*) in tf_python_api.cc.o
[error]   "nsync::nsync_mu_lock(nsync::nsync_mu_s_*)", referenced from:
[error]       tensorflow::UpdateInput(TF_Graph*, TF_Operation*, int, TF_Output) in tf_python_api.cc.o
[error]       tensorflow::AddControlInput(TF_Graph*, TF_Operation*, TF_Operation*) in tf_python_api.cc.o
[error]       tensorflow::ClearControlInputs(TF_Graph*, TF_Operation*) in tf_python_api.cc.o
[error]       tensorflow::SetRequestedDevice(TF_Graph*, TF_Operation*, char const*) in tf_python_api.cc.o
[error]   "nsync::nsync_mu_unlock(nsync::nsync_mu_s_*)", referenced from:
[error]       tensorflow::UpdateInput(TF_Graph*, TF_Operation*, int, TF_Output) in tf_python_api.cc.o
[error]       tensorflow::AddControlInput(TF_Graph*, TF_Operation*, TF_Operation*) in tf_python_api.cc.o
[error]       tensorflow::ClearControlInputs(TF_Graph*, TF_Operation*) in tf_python_api.cc.o
[error]       tensorflow::SetRequestedDevice(TF_Graph*, TF_Operation*, char const*) in tf_python_api.cc.o
[error]   "tensorflow::Node::input_edge(int, tensorflow::Edge const**) const", referenced from:
[error]       tensorflow::UpdateInput(TF_Graph*, TF_Operation*, int, TF_Output) in tf_python_api.cc.o
[error] ld: symbol(s) not found for architecture x86_64
```

**Comment by eaplatanios** [comment]
@allenlavoie Never mind my last comment. I was doing something wrong with linking. The `TF_LoadLibrary` issue is the only problem I can see at this point. Thanks a lot for getting this out and letting me know! :)

**Comment by eaplatanios** [comment]
Did you try to duplicate this line? `REGISTER_KERNEL_BUILDER(Name("Ackermann").Device(DEVICE_CPU), AckermannOp);` (i.e., the kernel registration)

**Comment by allenlavoie** [comment]
I'm familiar with the error, I'm trying to figure out why you're running into it. Is the name of the kernel library .so changing?
