### ISSUE TITLE
Update docs to instruct to use Bazel 0.1.1 installer

### ISSUE THREAD

**Issue by davidzchen** [tensorflow/tensorflow#129]
I noticed that the [TensorFlow Getting Started](http://tensorflow.org/get_started/os_setup.md#installing_from_sources) doc says to build Bazel 0.1.0 from source. It would be easier for users to use the Bazel installer to install Bazel instead as documented on the [Installing Bazel](http://bazel.io/docs/install.html) docs. The installers are available on the [Bazel releases](https://github.com/bazelbuild/bazel/releases) page.

Related: https://github.com/tensorflow/tensorflow/issues/130

**Comment by vrv** [comment]
David: should we wait for 0.1.1 before updating the docs, or just do this now?

**Comment by davidzchen** [comment]
@vrv Bazel 0.1.1 is already available, though I think we might be cutting 0.1.2 soon. I will check with the team to confirm whether we should wait for a new release or recommend using the 0.1.1 installer now.

**Comment by davidzchen** [comment]
@vrv I've checked with the Bazel team. There are some backwards incompatible changes at Bazel HEAD. Since 0.1.1 contains the fix for a number of bugs, such as bazelbuild/bazel#586, let's go ahead and update the TensorFlow docs to tell users to install Bazel 0.1.1 using the Bazel installer.

**Comment by vrv** [comment]
Okay, updated in https://github.com/tensorflow/tensorflow/commit/72a5a60dd4664a7caa4611344364ac7851464a60  -- thanks!
