### ISSUE TITLE
Generators in graphs

### ISSUE THREAD

**Issue by crackcomm** [tensorflow/tensorflow#12906]
I am wondering, is there any way to place a generator in a graph that would push values to lower parts of graph or asynchronous operations of this kind should be always placed outside of tensorflow graphs?

**Comment by rohan100jain** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by crackcomm** [comment]
You're right, thank you for the tip.
