### ISSUE TITLE
Input streaming data to tensorflow

### ISSUE THREAD

**Issue by YahaniManawadu** [tensorflow/tensorflow#12903]
Can you please reccommend a way to input streaming data which comes in json format to tensorflow

**Comment by mrry** [comment]
If you have Python code for connecting to the stream and parsing the JSON into arrays, you could wrap that logic in a Python generator and use `Dataset.from_generator()` (currently only available in the nightly build).

**Comment by YahaniManawadu** [comment]
Thanks you so much  mrry .
Actually, I was quite stucked at inputting streaming data to tensorflow in my project. So, Thanks a lot.

**Comment by YahaniManawadu** [comment]
Dear sir,
Actually, I was quite stucked at that question in my project.
Thank you so much Derek Murry .

regards,
Yahani Manawadu,
Undergraduate_Computer Science (Special)_4th year, University of Sri
Jayewardenepura.
Machine Learning Engineering Intern, nCinga Innovations Pvt. Ltd.
