### ISSUE TITLE
Change TanhGrad() operation definition with respect to documentation

### ISSUE THREAD

**Issue by Dorokhov** [tensorflow/tensorflow#12902]
Hello,

TanhGrad() documentation says: "Specifically, `grad = dy * (1 - y*y)`, where `y = tanh(x)`, and `dy`
is the corresponding input gradient." https://github.com/tensorflow/tensorflow/blob/bab2db47f60d59d843d661903a8d28227600dd60/tensorflow/core/ops/math_ops.cc#L323 which is correct and looks good.

But operation has following declaration of inputs:
  Input("x: T")                                                
  .Input("y: T")                                           
https://github.com/tensorflow/tensorflow/blob/bab2db47f60d59d843d661903a8d28227600dd60/tensorflow/core/ops/math_ops.cc#L200

what doesn't correlate with the documentated formula: grad = dy * (1 - y*y).
Could you please rename inputs with respect to documentation like this:

  Input("y: T")                                                
  .Input("dy: T")   

Thanks.

**Comment by yaroslavvb** [comment]
This means modifying UNARY_GRADIENT_COMPLEX macro and changing x to y and y to dy for every op that uses it, are you sure that wouldn't break things/contradict documentation for those other ops? BTW, you can press "y" in github to generate a permanent link with line number reference

**Comment by Dorokhov** [comment]
@yaroslavvb, it doesn't contradict documentation for other operations which use UNARY_GRADIENT_COMPLEX macros, because the other ops use 'y' and 'dy' names in docs.

Thanks for your suggestion, I updated the issue with permanent links.

**Comment by yaroslavvb** [comment]
@Dorokhov do you want to do a PR to fix it? If you do, make sure to run the tests locally first

**Comment by Dorokhov** [comment]
@yaroslavvb right, I will do
