### ISSUE TITLE
get_session_handle has no effect if not directly fetched

### ISSUE THREAD

**Issue by gaohuazuo** [tensorflow/tensorflow#12901]
Version `v1.3.0-rc1-1612-ga2e1a5e`, recent master.

```python
handle = tf.identity(tf.get_session_handle(tf.constant(0))).eval()
gen_data_flow_ops._get_session_tensor(handle, tf.int32).eval()
# InvalidArgumentError: The tensor with handle 'GetSessionHandle;0;/job:localhost/replica:0/task:0/device:GPU:0' is not in the session store.
```

```python
handle = tf.get_session_handle(tf.constant(0)).eval().handle
gen_data_flow_ops._get_session_tensor(handle, tf.int32).eval()
# OK
```

**Comment by drpngx** [comment]
Sorry, `get_session_handle` seems to be experimental. Have you tried the `_v2` version?

**Comment by gaohuazuo** [comment]
There is `GetSessionHandleV2` but no `GetSessionTensorV2`. 

```python
v = tf.Variable(gen_data_flow_ops._get_session_handle_v2(tf.constant(0)))
v.initializer.run()
gen_data_flow_ops._get_session_tensor(v, tf.int32).eval()
# ValueError: Incompatible type conversion requested to type 'string' for variable of type 'resource_ref'
```

**Comment by yaroslavvb** [comment]
@gaohuazuo this is by (suboptimal) design.

get_session_tensor requires a TensorHandle object in order to figure to pass some extra information (device assignment).

This object is obtained when you issue session.run on get_session_tensor op. In your failing case, you are evaluating a TF identity op, which gives you a regular numpy array rather than TensorHandle

See https://github.com/tensorflow/tensorflow/issues/6131

**Comment by gaohuazuo** [comment]
@yaroslavvb Looks like python wrapper is irrelevant.

```python
import tensorflow as tf
from tensorflow.python import pywrap_tensorflow
from tensorflow.python.ops import gen_data_flow_ops

config = tf.ConfigProto(graph_options=tf.GraphOptions(optimizer_options=tf.OptimizerOptions(opt_level=tf.OptimizerOptions.L0)))
print(config)
# graph_options {
#   optimizer_options {
#     opt_level: L0
#   }
# }

sess = tf.InteractiveSession(config=config)
def run(x):
    sess._extend_graph()
    with tf.errors.raise_exception_on_not_ok_status() as status:
        result, = pywrap_tensorflow.TF_Run(
            sess._session, None, {}, [x.name.encode()], [], status, None)
    return result

handle_tensor = gen_data_flow_ops._get_session_handle(tf.constant(0))
indirect_handle_tensor = tf.identity(handle_tensor)
handle_ph = tf.placeholder(tf.string, [])
session_tensor = gen_data_flow_ops._get_session_tensor(handle_ph, tf.int32)

handle = run(handle_tensor)
indirect_handle = run(indirect_handle_tensor)

session_tensor.eval(feed_dict={handle_ph: handle}) # OK
session_tensor.eval(feed_dict={handle_ph: indirect_handle}) # InvalidArgumentError
```

**Comment by yaroslavvb** [comment]
You are right, this seems to be a deeper runtime issue. It looks as if the tensor is added to session store when get_session_handle is fetched directly, and not added when it's executed as a dependency of a fetch

The relevant logic is in this commit
https://github.com/tensorflow/tensorflow/commit/098f930de4ef044021f3ef1d3cdd6848c23eddb0

Note that the author of this functionality has left Google

**Comment by tilakrayal** [comment]
@gaohuazuo,
The name **tf.get_session_handle** is deprecated. Please use **tf.compat.v1.get_session_handle** instead and also get_session_handle was experimental.

`tf.compat.v1.get_session_handle` was used to return the handle of data.
```
c = tf.multiply(a, b)
h = tf.compat.v1.get_session_handle(c)
h = sess.run(h)

p, a = tf.compat.v1.get_session_tensor(h.handle, tf.float32)
b = tf.multiply(a, 10)
c = sess.run(b, feed_dict={p: h.handle})
```
https://www.tensorflow.org/api_docs/python/tf/compat/v1/get_session_handle
Thank you!
