### ISSUE TITLE
inconsistent behavior in variable sharing 

### ISSUE THREAD

**Issue by malsulaimi** [tensorflow/tensorflow#12916]
hello , 

I have been struggling for few days with an issue that I'm facing in TensorFlow , I hesitated before opening this GitHub as an issue because I'm not sure if what I'm facing is a bug or a mere confusion on my side    . 

anyways it seems that I'm experiencing an inconsistent behavior in tensorFlow with variable name/reusing where I have a function that creates some cells and attentions objects : below is the function : 

```
def create_complete_cell(rnn_size,num_layers,encoder_outputs_tr,batch_size,encoder_state , beam_width ):

    with tf.variable_scope("InnerScope" , reuse=tf.AUTO_REUSE):
        encoder_outputs_tr =tf.contrib.seq2seq.tile_batch(encoder_outputs_tr, multiplier=beam_width) 
        encoder_state = tf.contrib.seq2seq.tile_batch(encoder_state, multiplier=beam_width) 
        batch_size =  batch_size * beam_width 
        dec_cell = tf.contrib.rnn.MultiRNNCell([create_cell(rnn_size) for _ in range(num_layers)])

        attention_mechanism = tf.contrib.seq2seq.BahdanauAttention(num_units=rnn_size, memory=encoder_outputs_tr ) 

        attn_cell = tf.contrib.seq2seq.AttentionWrapper(dec_cell, attention_mechanism , attention_layer_size=rnn_size , output_attention=False)
        attn_zero = attn_cell.zero_state(batch_size , tf.float32 )
        attn_zero = attn_zero.clone(cell_state = encoder_state)
    return attn_zero ,  attn_cell 
```

and then I call the function with scope reusing as shown below : 
```
with tf.variable_scope('scope' ):
    intial_train_state , train_cell = create_complete_cell(rnn_size,num_layers,encoder_outputs_tr,batch_size,encoder_state , 1  )
with tf.variable_scope('scope' ,reuse=True):
    intial_infer_state , infer_cell = create_complete_cell(rnn_size,num_layers,encoder_outputs_tr,batch_size,encoder_state , beam_width  )
print("intial_train_state" , intial_train_state)
print("intial_infer_state" , intial_infer_state)
```

the print commands parings the returned objects , first print outputs : 
`  ('intial_train_state', AttentionWrapperState(cell_state=(LSTMStateTuple(c=<tf.Tensor 'scope/InnerScope/tile_batch_1/Reshape:0' shape=(?, 512) dtype=float32>, h=<tf.Tensor 'scope/InnerScope/tile_batch_1/Reshape_1:0' shape=(?, 512) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'scope/InnerScope/tile_batch_1/Reshape_2:0' shape=(?, 512) dtype=float32>, h=<tf.Tensor 'scope/InnerScope/tile_batch_1/Reshape_3:0' shape=(?, 512) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'scope/InnerScope/tile_batch_1/Reshape_4:0' shape=(?, 512) dtype=float32>, h=<tf.Tensor 'scope/InnerScope/tile_batch_1/Reshape_5:0' shape=(?, 512) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'scope/InnerScope/tile_batch_1/Reshape_6:0' shape=(?, 512) dtype=float32>, h=<tf.Tensor 'scope/InnerScope/tile_batch_1/Reshape_7:0' shape=(?, 512) dtype=float32>)), attention=<tf.Tensor 'scope/InnerScope/AttentionWrapperZeroState/zeros_1:0' shape=(100, 512) dtype=float32>, time=<tf.Tensor 'scope/InnerScope/AttentionWrapperZeroState/zeros:0' shape=() dtype=int32>, alignments=<tf.Tensor 'scope/InnerScope/AttentionWrapperZeroState/zeros_2:0' shape=(100, ?) dtype=float32>, alignment_history=()))`

and the second print outputs : 
`  ('intial_infer_state', AttentionWrapperState(cell_state=(LSTMStateTuple(c=<tf.Tensor 'scope_1/InnerScope/tile_batch_1/Reshape:0' shape=(?, 512) dtype=float32>, h=<tf.Tensor 'scope_1/InnerScope/tile_batch_1/Reshape_1:0' shape=(?, 512) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'scope_1/InnerScope/tile_batch_1/Reshape_2:0' shape=(?, 512) dtype=float32>, h=<tf.Tensor 'scope_1/InnerScope/tile_batch_1/Reshape_3:0' shape=(?, 512) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'scope_1/InnerScope/tile_batch_1/Reshape_4:0' shape=(?, 512) dtype=float32>, h=<tf.Tensor 'scope_1/InnerScope/tile_batch_1/Reshape_5:0' shape=(?, 512) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'scope_1/InnerScope/tile_batch_1/Reshape_6:0' shape=(?, 512) dtype=float32>, h=<tf.Tensor 'scope_1/InnerScope/tile_batch_1/Reshape_7:0' shape=(?, 512) dtype=float32>)), attention=<tf.Tensor 'scope_1/InnerScope/AttentionWrapperZeroState/zeros_1:0' shape=(300, 512) dtype=float32>, time=<tf.Tensor 'scope_1/InnerScope/AttentionWrapperZeroState/zeros:0' shape=() dtype=int32>, alignments=<tf.Tensor 'scope_1/InnerScope/AttentionWrapperZeroState/zeros_2:0' shape=(300, ?) dtype=float32>, alignment_history=()))`

I was expecting that both output would be the same since I'm reusing the variables but as you can see that for example in the first variable the output has something like this 
**scope/InnerScope/tile_batch_1/Reshape_1:0**

and in the second variable 

**scope_1/InnerScope/tile_batch_1/Reshape_1:0**

I do not know why _1 is added to **scope** in the second call , and I'm a bit confused if the variable is being shared or not , further more when I set the reuse option to False , I get the below error in the second function call : 
`ValueError: Variable scope/memory_layer/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:`

which leads me to think that the function was reusing the variables when the reuse flag was True , but I still do not understand why is tensorFlow adding _1 to the variable name **scope_1** , and does that mean it not being reused ? and how do I fix this . 

I'm using Tensorflow 1.3 
ON MacOs 10.12.4

I have also opened a stackoverflow question : https://stackoverflow.com/questions/46081793/sharing-and-reusing-tensorflow-variables

thank you

**Comment by lukaszkaiser** [comment]
Hi @malsulaimi , thanks for writing. You need to be careful to distinguish variables from all other nodes in a TensorFlow graph. E.g., when you write this name above:

scope_1/InnerScope/tile_batch_1/Reshape_1:0

This is not a variable, this is just a node from the reshape op. Every node in the TF graph has its own unique name. When you reshape the same variable twice, for example, you'll get 2 different names for 2 different reshape nodes. It's just the variables that are shared. I hope this clarifies the confusion a bit!
