### ISSUE TITLE
autoconf error when running build_all_ios.sh

### ISSUE THREAD

**Issue by o2x7** [tensorflow/tensorflow#12921]
When running the build_all_ios.sh script on iOS I am getting the following error:

`+ autoreconf -f -i -Wall,no-obsolete
configure.ac:30: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1`

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Not getting to the point of running code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX High Sierra
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**:
- **Python version**: Python 2.7.10
- **Bazel version (if compiling from source)**: release 0.5.4-homebrew
- **CUDA/cuDNN version**:
- **GPU model and memory**: NVIDIA GeForce GT 750M 2GB
- **Exact command to reproduce**: ./tensorflow/contrib/makefile/build_all_ios.sh

**Comment by o2x7** [comment]
I was able to solve this by uninstalling libtool, autoconf, and automake and deleting all local cahecs that brew had.  From there a fresh install of automake, libtool fixed it

**Comment by drpngx** [comment]
Good to see you figured it out!
