### ISSUE TITLE
[RFE] tensorboard: provide a File->Open -like UI for saved model.pb files

### ISSUE THREAD

**Issue by quaeler** [tensorflow/tensorflow#12925]
This was originally solicited as https://github.com/tensorflow/tensorflow/issues/8854 by @brandondutra but got derailed with a very nice tools contribution from @jubjamie / @brandondutra

The original request would still, imo, make for a nice addition to tensorboard; specifically, were the UI of a running instance of TB to have something akin to a File->Open function to load a saved model .pb file, users who were tasked with the use case of "person gives them a saved model to inspect" would appreciate it.

**Comment by gunan** [comment]
As stated in our github issue template, you sould file this under tensorflow/tensorboard github repository.
