### ISSUE TITLE
Feature request: nightly build for python 3.6

### ISSUE THREAD

**Issue by tillahoffmann** [tensorflow/tensorflow#12935]
The [`tf-nightly`](https://pypi.org/project/tf-nightly/) pip packages are great! Would it be possible to add support for python 3.6 and/or provide a wheel for python 3.6 as part of the [standard nightly build](https://github.com/tensorflow/tensorflow#installation)?

In particular, the following succeeds

```
$ docker run --rm python:3 pip install tensorflow
```

whereas the following fails

```
$ docker run --rm python:3 pip install tf-nightly
Collecting tf-nightly
  Could not find a version that satisfies the requirement tf-nightly (from versions: )
No matching distribution found for tf-nightly
```

**Comment by gunan** [comment]
@av8ramit Do you think this would be easy to add?

**Comment by av8ramit** [comment]
Thanks @tillahoffmann, that is on our roadmap and I'll add that as soon as I can.

**Comment by tillahoffmann** [comment]
@av8ramit, that's great, thank you.

**Comment by tillahoffmann** [comment]
@av8ramit, do you have a rough estimate on when this is likely to happen? It would help us a lot with planning, e.g. should we push a binary to our internal pip server?

**Comment by av8ramit** [comment]
@tillahoffmann I'm aiming to have a 3.6 binary for CPU by late next week

**Comment by tillahoffmann** [comment]
@av8ramit, that's great thank you! We'll keep building a GPU version for now.

**Comment by av8ramit** [comment]
Hey @tillahoffmann can you give the [nightlies](https://pypi.python.org/pypi?:action=display&name=tf-nightly&version=1.4.0.dev20170921) from today a chance?

**Comment by tillahoffmann** [comment]
:tada:, thank you for the CPU build!

**Comment by av8ramit** [comment]
No problem! Please reopen if there are any issues.

**Comment by tillahoffmann** [comment]
It seems that some parts of the nightly build still relies on 3.5.

```
/usr/local/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
```

**Comment by av8ramit** [comment]
Yes, we unfortunately copy the 3.5 binary for 3.6 I'll look into creating a specific 3.6 binary for Linux.

**Comment by gunan** [comment]
Looks like we may need to change this, we used to not have such issues.
We will look into enhancing our builds to actually build with different python versions.

**Comment by KrishnaveniTK** [comment]
Hi @gunan ..is the fix available for 3.6 binary in linux?

**Comment by salman-bhai** [comment]
Any idea when the PR will be merged till?

**Comment by gunan** [comment]
There's no PR, we will need to make this change in the release workflow.

**Comment by ProZoom** [comment]
how i do on Mac？i hava this issue！

**Comment by cmccarthy15** [comment]
I also have this issue! Please help! 

pip install tf-nightly-gpu
Collecting tf-nightly-gpu
  Could not find a version that satisfies the requirement tf-nightly-gpu (from versions: )
No matching distribution found for tf-nightly-gpu

**Comment by av8ramit** [comment]
There is now a python binary for tf-nightly and tf-nightly-gpu that is built from python3.6 as of 12/06!

Closing this issue for now. @cmccarthy15 can you please provide more information? What OS and python version are you running?
