### ISSUE TITLE
Gradient for tf.diag

### ISSUE THREAD

**Issue by istaslis** [tensorflow/tensorflow#1293]
tf.diag doesn't support the gradient (as far as I can see here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_grad.py#L161)
Is it difficult to add support for that?
Thank you
Some simple example:
```
tSv = tf.Variable(tf.truncated_normal([r]))
t = tf.diag(tSv)
train = tf.train.GradientDescentOptimizer(0.01).minimize(t)

sess = tf.Session()
init = tf.initialize_all_variables()
sess.run(init)
sess.run(train)
...
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-96-28cf62ca1be1> in <module>()
      1 tSv = tf.Variable(tf.truncated_normal([r]))
      2 t = tf.diag(tSv)
----> 3 train = tf.train.GradientDescentOptimizer(0.0001).minimize(t)
      4 
      5 sess = tf.Session()
ValueError: No inputs provided
```

**Comment by cameronphchen** [comment]
Note quite sure what do you mean by minimizing a matrix `t` in your example.
If you want to optimize for matrix trace, there's a workaround. 
I do agree that it would be great to support gradient on tf.diag.

`import tensorflow as tf
import numpy as np

with tf.Graph().as_default():
    Y = np.random.rand(3,3).astype(np.float32)
    X = tf.Variable(np.random.rand(3,3).astype(np.float32))
    Z = tf.matmul(X,Y)
    
    ones = np.ones(3).astype(np.float32) 
    eye = tf.diag(ones)
    
    loss = tf.reduce_sum(tf.mul(Z, eye))
    optimizer = tf.train.AdagradOptimizer(0.01).minimize(loss)
    sess = tf.Session()
    sess.run(tf.initialize_all_variables())
    with sess.as_default():
        for i in range(100):
            sess.run(optimizer)
            print sess.run(loss)
            print X.eval()`

**Comment by istaslis** [comment]
Thank you very much, @cameronphchen! This is a very nice workaround which is worth mentioning in the documentation. I am new to tensorflow and it took me a while to realise that derivative on diag is not implemented.
Thanks again for your help, this resolves my issue.

**Comment by girving** [comment]
Once https://github.com/tensorflow/tensorflow/pull/1265 is in place this becomes very easy to fix.

**Comment by chemelnucfin** [comment]
I should have the python code implementation (which is like 2 lines).  I'll need to add tests though.

**Comment by cameronphchen** [comment]
@girving Yes, I have been following that thread. It would be great to add matrix trace operator as well! I can help with these when #1265 is done.

**Comment by cameronphchen** [comment]
@chemelnucfin Oh, that's great! Let me know if you need an extra hand.

**Comment by chemelnucfin** [comment]
@cameronphchen feel free to work on them!  But do the trace first.  I'm taking a look at something else at the moment.  I'll put a note here when I get back to the diag grad test.

**Comment by cameronphchen** [comment]
sounds good! I'll work on trace then.

**Comment by cameronphchen** [comment]
I have implemented trace and planning to start working on its gradient. The current approach is essentially using `reduce_sum` and `diag_part` for calculating trace. This behavior will be consistent within tensorflow but quite different from `numpy.trace` though. `numpy.trace` output trace of 2D subarrays specified by two input arguments `axis1` and `axis2`. Is this going to be an issue? 

Btw, this is my first time contributing to tensorflow, any guidance or suggestion would be appreciated. Thanks!
