### ISSUE TITLE
All tf.sets.* ops fail to reproduce their own official examples.

### ISSUE THREAD

**Issue by MtDersvan** [tensorflow/tensorflow#12969]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: ('v1.3.0-rc2-20-g0787eee', '1.3.0')
- **Python version**:  3.5
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a 
- **Exact command to reproduce**: n/a

### Context:
`tf.sets.*` ops documentation declares that: '_All but the last dimension of a and b must match._'.
Also, the example is provided:
```
a = [
    [
      [
        [1, 2],
        [3],
      ],
      [
        [4],
        [5, 6],
      ],
    ],
  ]
  b = [
    [
      [
        [1, 3],
        [2],
      ],
      [
        [4, 5],
        [5, 6, 7, 8],
      ],
    ],
  ]
tf.sets.set_intersection(a, b)
tf.sets. set_union(a, b)
tf.sets.set_size(a)
tf.sets.set_difference(a, b, aminusb=True)
```

### Problem:
When using `tf.sets.*` ops, the following error occurs:
```
ValueError: Argument must be a dense tensor: [[[[1, 2], [3]], [[4], [5, 6]]]] - got shape [1, 2, 2], but wanted [1, 2, 2, 2].
```
From this error it is deducible, that a dense tensor is needed. This statement contradicts the description of methods. Also, logically we would not want to have a dense tensor or any kind of padding in sets (this leads to excessive padding elements in sets - which defies the purpose).

### Statement:
Either the functionality or the description of `tf.sets` must be fixed.

**Comment by reedwm** [comment]
@honkentuber can you comment? The documentation is confusing since each row of a tensor must have the same number of elements, which is not the case in the example.

**Comment by martinwicke** [comment]
@dr4b @MarkDaoust can you look at this documentation issue? I don't know how pervasive this is, but it could affect all the sparse tensor ops.

**Comment by dr4b** [comment]
Sounds like Mark is going to take a stab at rewriting the samples.  We don't think this affects all of the sparse tensor ops, for now.

**Comment by MarkDaoust** [comment]
The docs for sparse tensors contain some non-runnable text representations, but they don't look like they're meant to run (as this one does).
