### ISSUE TITLE
Feature request: Google Authentication support for OAuth2 AccessTokenCredentials

### ISSUE THREAD

**Issue by Juta** [tensorflow/tensorflow#12964]
I would like to use the BigQueryReader to access  someone else's project with OAuth2 AccessTokenCredentials. I noticed that currently the google_auth_provider only uses application default credentials. I think it would be a great addition to add other methods of authentication as well.

**Comment by GeorgyZhou** [comment]
I am trying to work on this and send an update later

**Comment by tilakrayal** [comment]
@Juta,
Could you please take a look at this document [link](https://www.tensorflow.org/io/tutorials/bigquery) which provides the required information. Thank you!
