### ISSUE TITLE
Could not find `backports.weakref` while installing TensorFlow

### ISSUE THREAD

**Issue by andybergon** [tensorflow/tensorflow#12967]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: -
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sierra 10.12.6
- **TensorFlow installed from (source or binary)**: (Trying to install through package manager pip2)
- **TensorFlow version (use command below)**: 1.2.0
- **Python version**: 2.7.13
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: -
- **GPU model and memory**: -
- **Exact command to reproduce**: `pip2 install tensorflow==1.2.0`

### Describe the problem
While I try to install TF (1.2.0) on Python2.7 through the package manager Pip (`pip2 install tensorflow==1.2.0`) I get the following error:
```
Collecting tensorflow==1.2.0
  Downloading https://build.hubteam.com/pypi-mirror/packages/bf/a8/e98871dc5bfbe590ed41a38058fab1391647dc0553d5034f5fd6746f0a37/tensorflow-1.2.0-cp27-cp27m-macosx_10_11_x86_64.whl (33.6MB)
    100% |████████████████████████████████| 33.6MB 37kB/s
Requirement already satisfied: wheel in /usr/local/lib/python2.7/site-packages (from tensorflow==1.2.0)
Collecting backports.weakref==1.0rc1 (from tensorflow==1.2.0)
  Could not find a version that satisfies the requirement backports.weakref==1.0rc1 (from tensorflow==1.2.0) (from versions: )
No matching distribution found for backports.weakref==1.0rc1 (from tensorflow==1.2.0)
```

So it doesn't find the `backports.weakref` package in PyPl (even if I can see it [here](https://pypi.python.org/pypi/backports.weakref)).

Is this a known issue? What can I do to install this dependency manually?

**Comment by gunan** [comment]
@yifeif, any ideas?

@andybergon What version of pip are you using?
`pip2 --version` should be the command to show the version.

**Comment by yifeif** [comment]
Could you try `pip install backports.weakref==1.0rc1` first?

**Comment by andybergon** [comment]
This was an internal problem. Sorry about the noise.
`pip2 install --index-url https://pypi.python.org/simple tensorflow==1.2.0` worked.
