### ISSUE TITLE
Different confidence with same model.pb from android and python

### ISSUE THREAD

**Issue by sfshine** [tensorflow/tensorflow#12961]
I trained a model.pb with python, and put it in android. 
well, I find the confidence score that in android is always lower than python application  on my PC.
AFAIK, for android model.pb, I did not use DecodeJpeg because it not support on Android.

Is there anything wrong or different with DecodeJpeg in android example when processing image?

        Trace.beginSection("preprocessBitmap");
        // Preprocess the image data from 0-255 int to normalized float based
        // on the provided parameters.
        bitmap.getPixels(intValues, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());
        for (int i = 0; i < intValues.length; ++i) {
            final int val = intValues[i];
            floatValues[i * 3 + 0] = (((val >> 16) & 0xFF) - imageMean) / imageStd;
            floatValues[i * 3 + 1] = (((val >> 8) & 0xFF) - imageMean) / imageStd;
            floatValues[i * 3 + 2] = ((val & 0xFF) - imageMean) / imageStd;
        }
        Trace.endSection();

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
