### ISSUE TITLE
does new dataset api support pre read data?

### ISSUE THREAD

**Issue by chaos-dd** [tensorflow/tensorflow#12960]
I found that currently dataset api does not support pre read data as old reading data api. If we have so much train data the feature, the speed of reading data is critical.

**Comment by mrry** [comment]
The easiest way to prefetch data is to use [`dataset = dataset.prefetch(BUFFER_SIZE)`](https://www.tensorflow.org/versions/master/api_docs/python/tf/contrib/data/Dataset#prefetch), which is available in the nightly build. If you're using a release, you can get the same effect with `dataset = dataset.map(lambda x, y, z, ...: return (x, y, z, ...), num_threads=1, output_buffer_size=BUFFER_SIZE)`.

**Comment by chaos-dd** [comment]
I already try to add  thread unum and buffer size param to dataset method map, but it doed not speed up.  It seems that the two params  does not  used for pre read data accoding to the docs.

My problem is when I have multiple gpu in one machine, I want  data parallism to speed up training speed. So I add multiple dataset node in the tensorflow graph  one for a gpu, but it seems that multiple dataset read data seqnencely and in one dataset there's no data pre reading. Multiple gpu can not be fully used as reading data into tf takes so much time.

**Comment by mrry** [comment]
They certainly are used for prefetching. It's hard to say what the source of slowness is, without seeing the entire pipeline. It's possible that the input source (I'm guessing from files?) is limiting your overall throughput.
