### ISSUE TITLE
Exception thrown running  example/udacity/5_word2vec

### ISSUE THREAD

**Issue by jyegerlehner** [tensorflow/tensorflow#1297]
Hi all. Does anyone reproduce this? The description of the problem is below in the suggested format. A brief summary is: running the examples/udacity/4_convolutions.ipynb runs fine on gpu, but the 5_word2vec notebook fails  with an AdaGrad-related exception: 

`InvalidArgumentError: Cannot assign a device to node 'Adagrad/update_Variable_2/SparseApplyAdagrad': Could not satisfy explicit device specification '' because the node was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/GPU:0'`

though I never modified the code (except to print some things out). I never modified code to assign any ops to a device, as it seems to be claiming.

This looks at least superficially related to [this issue](https://github.com/tensorflow/tensorflow/issues/505).

Thanks,
Jim

### Environment info
Operating System: Ubuntu 14.04 LTS

**If installed from binary pip package, provide:**
Built from r0.7 source.

**1. Which pip package you installed.**
`sudo pip install --upgrade /tmp/tensorflow_pkg/tensorflow-0.7.1-cp27-none-linux_x86_64.whl`

**2. The output from python -c "import tensorflow; print(tensorflow.__version__)".**

```
jd@jd-All-Series:~/dev/thirdparty/scikit-learn/scikit-learn$ python -c "import tensorflow; print(tensorflow.__version__)"

I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so.7.0 locally

I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally

I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so.7.0 locally

I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally

I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so.7.0 locally

0.7.1
```

**If installed from sources, provide the commit hash:**
`41fcc7edd63c01dfd56382be4755c90f5a7eb565`

### Steps to reproduce
1. Run `jupyter notebook` in the examples/udacity/ directory.
2. Open the 5_word2vec.ipynb notebook in the web browser (from http://localhost:8888).
3. Execute each of the steps through the first (Google-provided) session.run().
4. Observe the exception when you get to the first session.run() after 'Train a skip-gram model.' step, which is provided by notebook (before I have to write any code). The exception happens on the line with session.run() invocation.

`InvalidArgumentError: Cannot assign a device to node 'Adagrad/update_Variable_2/SparseApplyAdagrad': Could not satisfy explicit device specification '' because the node was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/GPU:0'
	 [[Node: Adagrad/update_Variable_2/SparseApplyAdagrad = SparseApplyAdagrad[T=DT_FLOAT, Tindices=DT_INT64, use_locking=false](Variable_2, Variable_2/Adagrad, Adagrad/learning_rate, gradients/concat_2, gradients/concat_3)]]`

I have not modified the python code assign to do any device assignments in this notebook. 

### What have you tried?
1. I've been working through the Udacity DeepLearning course. After encountering this error, I killed the jupyter kernel for 5_word2vec, and re-run my previously-saved notebook for the fourth exercise, 4_convolutions.ipynb, and it executes without error on the gpu. Which I think must confirm that TensorFlow is installed OK. 

Done for the day, but when I come back, I will probably try building without gpu support, and see if that runs OK so I can at least carry on with the course.

### Logs or other output that would be helpful
Please let me know if there's anything you'd like me to log. Hardware is a Titan-X.

**Comment by vincentvanhoucke** [comment]
That other problem you reference should be fixed:
https://github.com/tensorflow/tensorflow/issues/1117
So that's likely a different issue. I have never tested the class notebooks on GPU.
Just to make sure: your setup works fine on CPU?

**Comment by vincentvanhoucke** [comment]
Does using:
`with tf.Session(graph=graph, config=tf.ConfigProto(allow_soft_placement=True)) as session:` fix it?

**Comment by jyegerlehner** [comment]
I hadn't tried that before.  So I just now tested on the cpu by adding tf.device as here:

```python
with graph.as_default():
     with tf.device('/cpu:0'):
```

and it did indeed run successfully. I'm not sure if there is some other way to make it run on the cpu, other than build without gpu support.

**Comment by jyegerlehner** [comment]
> Does using:
with tf.Session(graph=graph, config=tf.ConfigProto(allow_soft_placement=True)) as session: fix it?

No, I get a different exception. Namely, I removed the tf.device() (shown above) so that it goes back to trying to run on the gpu, and specified the config argument you specify, and now I get this exception on the session.run() call:

```InvalidArgumentError: AttrValue must not have reference type value of float_ref
	 for attr 'tensor_type'
	; NodeDef: Variable/Adagrad/_84 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_550_Variable/Adagrad", tensor_type=DT_FLOAT_REF, _device="/job:localhost/replica:0/task:0/cpu:0"](^gradients/concat_6/_86, ^gradients/concat_7/_88); Op<name=_Recv; signature= -> tensor:tensor_type; attr=tensor_type:type; attr=tensor_name:string; attr=send_device:string; attr=send_device_incarnation:int; attr=recv_device:string; attr=client_terminated:bool,default=false; is_stateful=true>
	 [[Node: Variable/Adagrad/_84 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_550_Variable/Adagrad", tensor_type=DT_FLOAT_REF, _device="/job:localhost/replica:0/task:0/cpu:0"](^gradients/concat_6/_86, ^gradients/concat_7/_88)]]
```

**Comment by vincentvanhoucke** [comment]
@mrry here is a tiny colab notebook which works fine on CPU, but fails on GPU even with soft placement in r0.7. Any idea?

**Comment by jyegerlehner** [comment]
As a sanity check: I rotated through each of the three states of the code and reproduced the behaviors in each case I described above: 1) original code, running on GPU fails, 2) adding tf.device('/cpu:0') runs successfully, 3) soft placement fails with the different exception.

Thanks for the help!

**Comment by mrry** [comment]
I think this is a known issue (at least offline), where running the initializer will cause all variables to be assigned to the GPU, then subsequently trying to run SparseApply<FOO> on one of those variables will fail because SparseApply<FOO> doesn't have a GPU implementation. (@vrv has an idea for how to fix it, but it might break other users, so we haven't pushed it yet :(.) The workaround is to pin just the offending variable to CPU using `with tf.device("/cpu:0"):`.

I think for the [notebook in question](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/5_word2vec.ipynb), this involves changing the line:

```python
embeddings = tf.Variable(
  tf.random_uniform([vocabulary_size, embedding_size], -1.0, 1.0))
```

...and replacing it with:

```python
with tf.device("/cpu:0"):
  embeddings = tf.Variable(
    tf.random_uniform([vocabulary_size, embedding_size], -1.0, 1.0))
```

**Comment by jyegerlehner** [comment]
@mrry Thanks!
Do you prefer me to close this, or leave it open?

**Comment by vincentvanhoucke** [comment]
Please leave it open. I need to add the workaround to the notebook. (PRs gladly accepted)

**Comment by jyegerlehner** [comment]
@mrry Hmm unfortunately just assigning `embeddings` to the cpu didn't work for me. Still got the same exception. So I resorted to the expedient of putting the whole graph on the cpu.

**Comment by mrry** [comment]
Sorry for the confusion... it looks like you might also need to pin the `softmax_weights` and `sotmax_biases` to `"/cpu:0"`. I hadn't read the following code closely: these are both used in `tf.nn.sampled_softmax_loss()`, which uses `tf.nn.embedding_lookup()` internally, and thus results in sparse updates in the training step.

**Comment by dpkay** [comment]
I ran into the same problem and can confirm that the workaround works when pinning all three of embeddings, softmax_weights and softmax_biases. Thanks!

**Comment by jyegerlehner** [comment]
Right, I confirm too.

**Comment by vincentvanhoucke** [comment]
Merged a workaround that pins everything to CPU. Please follow #1310 for the actual fix to make it work on GPU as well.
