### ISSUE TITLE
Default keras initializers parameters have changed

### ISSUE THREAD

**Issue by chrisc36** [tensorflow/tensorflow#12973]
At least in Tensorflow 1.3, some of the Keras initializers have changed they default parameters since Tensorflow 1.1:

In Tensorflow 1.1:

``
from tensorflow.contrib.keras.python.keras.initializers import TruncatedNormal
TruncatedNormal().stddev  # returns 0.05
``

In Tensorflow 1.3:
``
from tensorflow.contrib.keras.python.keras.initializers import TruncatedNormal
TruncatedNormal().stddev  # returns 1
``

I assume this was not intentional since this is a breaking change and I did not see it documented in the release notes.

**Comment by reedwm** [comment]
@fchollet can you comment?

**Comment by fchollet** [comment]
In TF 1.2, we removed the Keras `TruncatedNormal` initializer and instead simply imported the core version (from `init_ops`). The core version has a different default `stddev` value, hence the change. This was an oversight.

Code in contrib is subject to changes. Now the Keras API has moved to core, so such changes will not happen in the future.

In general, I would recommend not using `TruncatedNormal` (prefer scaling initializers such as glorot, etc) and I would recommend always specifying `stddev` if you are using it.
