### ISSUE TITLE
Feature missing? Ability to get Tensorboard output from provided "estimators"

### ISSUE THREAD

**Issue by dartdog** [tensorflow/tensorflow#12974]
This is opened here since it relates to Estimator and canned estimator models not providing a method to get output for TB

3. It shouldn't be a TensorBoard issue. And I attempted to get an answer at Stackoverflow.. (here https://stackoverflow.com/questions/46064056/no-easy-way-to-add-tensorboard-output-to-pre-defined-estimator-functions-dnnclas/46065066#46065066 )

I have been using the estimator interface in TF 1.3 including the creation of the data input function:

`training_input_fn = tf.estimator.inputs.pandas_input_fn(x=training_data, y=training_label, batch_size=64, shuffle=True, num_epochs=None)`

and building the NN:

`dnnclassifier = tf.estimator.DNNClassifier(
    feature_columns=dnn_features,
    hidden_units=[1024, 500, 100],
    n_classes=2, 
    model_dir='./tmp/ccsprop',
    optimizer=tf.train.ProximalAdagradOptimizer(
      learning_rate=0.001,
      l1_regularization_strength=0.01
    ))`

and executing it

`dnnclassifier.train(input_fn=training_input_fn, steps=1500)`

After much searching I see no easy way to add tensorboard output without resorting to recreating the model from scratch and indicated here https://www.tensorflow.org/extend/estimators

Following some of the help on SO:

` TBcall=tf.train.SummarySaverHook(save_steps=10, output_dir='./tb', summary_op=tf.summary.merge_all())`

`dnnclassifier.train(input_fn=training_input_fn, steps=1500, hooks=TBcall)`

that gives this error: Exactly one of scaffold or summary_op must be provided

The answer on SO has now been edited to show code from creating a model from scratch it seems.. So is there no way to get basic info from  tf.estimator.DNNClassifier to Tensorboard? And more generically from other tf.estimators ?? One would expect the canned estimators to provide this? For model introspection and tuning.

**Comment by cy89** [comment]
@dandelionmane would you please comment or refer someone?

**Comment by oceliktutan** [comment]
Hello, I ran into the same problem. Is there any progress on this issue?, or What could be the alternative solution? Many thanks!

**Comment by k-w-w** [comment]
@jart @chihuahua Can you take a look at this? We are thinking about adding a hook to a garden model that uses a canned estimator.

**Comment by dandelionmane** [comment]
@martinwicke @ispirmustafa I think there's essentially a missing API on the Estimator side for allowing TensorBoard integration. Is there a solution for this?

When I was playing with Estimators earlier I was able to get some coordination between TensorBoard and Estimators by creating a SummarySaverHook when defining my model code, and then passing that into the tf.estimator.EstimatorSpec. But I don't think that works in this case where you use an off-the-shelf estimator.

**Comment by martinwicke** [comment]
Unless I'm totally off, this would be extraordinarily surprising: Estimator (incl. DNNEstimator) uses MonitoredTrainingSession, which automatically creates a SummarySaverHook, by default every 10 minutes or 100 steps, whichever happens first. You can adjust this using the config constructor argument.

These summaries are saved to the model_dir.

**Comment by dartdog** [comment]
It is entirely possible that it is indeed a documentation/user issue, nonetheless, How does one create and use the summarySaverhook? but also as noticed seemingly not possible using the canned models?

**Comment by ispirmustafa** [comment]
Hi @dartdog,
SummarySaverHook is created for you automatically in estimators. You should not worry about it.
All the summaries should be automatically dumped to model_dir.

**Comment by dartdog** [comment]
Please note the original question which indicates something is not working!! @ispirmustafa Generating error message not output!

**Comment by Neergaard** [comment]
Unless I am totally mistaken, you are generating an error because you are passing a summarysaverHook to the estimator, when it already has one generated internally upon creation.

What you could do is passing a tf.estimator.RunConfig() object directly when you instantiate the estimator. Using your own code it would look like

`dnnclassifier = tf.estimator.DNNClassifier(feature_columns=dnn_features, hidden_units=[1024, 500, 100], n_classes=2, model_dir='./tmp/ccsprop', optimizer=tf.train.ProximalAdagradOptimizer( learning_rate=0.001, l1_regularization_strength=0.01, config=tf.estimator.RunConfig().replace(save_summary_steps=10) ))`

You do not have to include a summary_merge statement because the estimator will do that for you.

**Comment by dartdog** [comment]
I'll give it a go and respond..

**Comment by dartdog** [comment]
That did not work,  using :

    `dnnclassifier = tf.estimator.DNNClassifier(
    feature_columns=dnn_features,
    hidden_units=[1024, 500, 100],
    n_classes=2, 
    model_dir='./tmp/ccsprop',
    optimizer=tf.train.ProximalAdagradOptimizer(
      learning_rate=0.001,
      l1_regularization_strength=0.01,
      config=tf.estimator.RunConfig().replace(save_summary_steps=10)
    ))`
I just got:

    `     11       l1_regularization_strength=0.01,
    ---> 12       config=tf.estimator.RunConfig().replace(save_summary_steps=10)
         13     ))
         14 #note reducing the learning rate does seem to help!

      TypeError: __init__() got an unexpected keyword argument 'config'

**Comment by dartdog** [comment]
Note now trying with corrected syntax..:


    dnnclassifier = tf.estimator.DNNClassifier(
    feature_columns=dnn_features,
    hidden_units=[1024, 500, 100],
    n_classes=2, 
    model_dir='./tmp/ccsprop',
    optimizer=tf.train.ProximalAdagradOptimizer(
      learning_rate=0.001,
      l1_regularization_strength=0.01),
      config=tf.estimator.RunConfig().replace(save_summary_steps=10)
    )

**Comment by dartdog** [comment]
That now generates some seemingly useful Tensorboard output! Thank you so much. Anyway to modify the output Using Tensorboard commands or am I stuck with the standard output the canned model defines?

**Comment by martinwicke** [comment]
For the canned ones, you are stuck with what they provide. If you write a custom one (by writing a model_fn to give to Estimator) you can do whatever you want.

**Comment by dartdog** [comment]
FWIW some Doc addition would probably be nice :-)

**Comment by martinwicke** [comment]
What's the place in which you would have benefited most from additional documentation? 

If you send a PR, that would be great too.

**Comment by Neergaard** [comment]
@dartdog Sorry about that, I missed the fact that you called an optimizer directly. Great to hear that you got it to work.

I think you are stuck with what the canned models are defining in terms of metrics, but perhaps you can use the SessionRunHooks to log your own metrics that way?

**Comment by opalbert** [comment]
Hello does this solution still work for the current version of tf.estimator? I implemented the code structure and i get "No scalar data was found", "No graph definition files were found." It there another way I should do this?
Below is my code:
outdir = './gp_trained'
shutil.rmtree(outdir, ignore_errors = True) # start fresh each time
myopt = tf.train.AdamOptimizer(learning_rate = 0.01, beta1=0.9,beta2=0.999) #AdamOptimizer
model = tf.estimator.DNNRegressor(model_dir = outdir,
                                hidden_units = [50],
                                feature_columns = featcols.values(),
                                optimizer = myopt,
                                dropout = 0.1,
                                config=tf.estimator.RunConfig().replace(save_summary_steps=10))
NSTEPS = (100 * len(df_train)) / BATCH_SIZE
model.train(input_fn = train_input_fn, steps = NSTEPS)
print_rmse(model, 'eval', eval_input_fn)
Thank you.

**Comment by netskink** [comment]
Hmm. I am using the lab from the google/coursera class shown in this [directory](https://github.com/GoogleCloudPlatform/training-data-analyst/tree/master/courses/machine_learning/deepdive/03_tensorflow).  as a template for a DNNClassifier (binary).  Specifically I am using the notebook d_traineval.ipynb as my guide.  I also have the error with no data.

I used the approach above to but still nothing.  Here is my actual code for this step:

  ```
# To convert a model to distributed train and evaluate do four things
  estimator = tf.estimator.DNNClassifier(                         # 1. Estimator
                          model_dir = output_dir,
                          feature_columns = feature_cols, 
                          hidden_units=[160, 80, 40, 20],
                          n_classes=2,
                          optimizer=tf.train.ProximalAdagradOptimizer(   
                            learning_rate=0.001,
                            l1_regularization_strength=0.01),
                          config=tf.estimator.RunConfig().replace(save_summary_steps=10)  # 2. run config
                                                                                          # ODD. he mentions we need a run config in the videos, but it was missing in the lab
                                                                                          # notebook.  Later I found the bug report which gave me this bit of code.
                          )# 


```

**Comment by netskink** [comment]
Hmm. I modified the above code remove the optimizer parameter and I adjusted the save_summary_steps=10 to be save_summary_steps=2.  The result is that now I can see the accuracy and accuracy_baseline graphs.  Possibly my problem was that I have small dataset 802 total samples with 15 features and that the save summary steps was to big.

**Comment by netskink** [comment]
Hmm. further still. This specifically fixed it.
```
OUTDIR = './model_trained'
TensorBoard().start(OUTDIR)
```

Originally, I had it without the leading './' for the outdir specification.

**Comment by PHRABAL** [comment]
FYI - I had a similar problem - adding ./ before the folder name fixed it.
