### ISSUE TITLE
boringssl sha256 checksum mismatched

### ISSUE THREAD

**Issue by mylxiaoyi** [tensorflow/tensorflow#12986]
https://github.com/tensorflow/tensorflow/blob/5541ef4fbba56cf8930198373162dd3119e6ee70/tensorflow/workspace.bzl#L583

when download from https://github.com/google/boringssl/archive/e3860009a091cd1bd2bc189cdbc3c6d095abde84.tar.gz, the sha256 checksum is 
```
a9a3673b1f7bd80ef563e9de1d9ccdb5126dc0cce6377977009092148993c4fe
```

 , but expected is
```
02f5950f93c4fd3691771c07c9d04cf2999ab01383ff99da345249e93b0fcfb2 
```
.

Is there something wrong?

thanks.

**Comment by d4l3k** [comment]
Also at https://github.com/tensorflow/tensorflow/issues/12979

**Comment by kdatta** [comment]
Also at #12984

**Comment by cy89** [comment]
@gunan, can you please take a look?

**Comment by gunan** [comment]
Are we still seeing this?
The root cause is changes in github side.
They are just creating archives differently now. We are looking into if we can mirror our dependencies ourselves now.

**Comment by gunan** [comment]
deduping this against #12979 Please watch that issue for progress.
