### ISSUE TITLE
bazel build failed due to boringssl checksum mismatches

### ISSUE THREAD

**Issue by kdatta** [tensorflow/tensorflow#12984]
No custom code.
System snapshot:
GCC 5.3.1
Centos 7
Bazel 0.5.4

Building from commit id 79517578deb4ea2a8dea641f1a8fa4363c13f76b from master.

[user@master tensorflow]$ bazel build --config=mkl --copt="-march=knl" --copt="-O3" -s -c opt //tensorflow/tools/pip_package:build_pip_package
WARNING: ignoring http_proxy in environment.
ERROR: /home/user/tensorflow/tensorflow/tools/pip_package/BUILD:101:1: no such package '@boringssl//': java.io.IOException: Error downloading [http://mirror.bazel.build/github.com/google/boringssl/archive/e3860009a091cd1bd2bc189cdbc3c6d095abde84.tar.gz, https://github.com/google/boringssl/archive/e3860009a091cd1bd2bc189cdbc3c6d095abde84.tar.gz] to /home/user/.cache/bazel/_bazel_user/59b9d4cecf85aafc18f6c320e7734241/external/boringssl/e3860009a091cd1bd2bc189cdbc3c6d095abde84.tar.gz: Checksum was a9a3673b1f7bd80ef563e9de1d9ccdb5126dc0cce6377977009092148993c4fe but wanted 02f5950f93c4fd3691771c07c9d04cf2999ab01383ff99da345249e93b0fcfb2 and referenced by '//tensorflow/tools/pip_package:licenses'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 6.963s
[user@master tensorflow]$

**Comment by samwit** [comment]
I am having the same issue

**Comment by d4l3k** [comment]
Also at https://github.com/tensorflow/tensorflow/issues/12979

**Comment by Chao1155** [comment]
Have same issue.
build with cuda on Master branch of Sep.12

**Comment by Chao1155** [comment]
It seams change the checksum of boringssl in tensorflow/workspace.bzl works as a temporary workaround.

Change the checksum in line 583 of workspace.bzl from "02f***" to "a9a***" (The checksum you get).

**Comment by kdatta** [comment]
Yeah, @Chao1155 this is how I worked around this as well

**Comment by speak2me** [comment]
@Chao1155 thanks

**Comment by subashp** [comment]
Thanks, that worked.

Checksum was **a9a3673b1f7bd80ef563e9de1d9ccdb5126dc0cce6377977009092148993c4fe** but wanted **02f5950f93c4fd3691771c07c9d04cf2999ab01383ff99da345249e93b0fcfb2** and referenced by '//tensorflow/tools/pip_package:licenses

**Comment by oscarkfpang** [comment]
I've changed the line 583 of workspace.bzl to the new checksum as follows but still cannot build.

The error I got was 

no such package '@boringssl//': java.io.IOException: Error downloading .....

  patched_http_archive(
      name = "boringssl",
      urls = [
          "http://mirror.bazel.build/github.com/google/boringssl/archive/e3860009a091cd1bd2bc189cdbc3c6d095abde84.tar.gz",
          "https://github.com/google/boringssl/archive/e3860009a091cd1bd2bc189cdbc3c6d095abde84.tar.gz",  # 2017-07-07
      ],
      sha256 = "a9a3673b1f7bd80ef563e9de1d9ccdb5126dc0cce6377977009092148993c4fe",
      strip_prefix = "boringssl-e3860009a091cd1bd2bc189cdbc3c6d095abde84",
      # Add patch to boringssl code to support s390x
      patch_file = str(Label("//third_party/boringssl:add_boringssl_s390x.patch")),
  )

**Comment by kdatta** [comment]
@oscarkfpang what's the full text of the error?

**Comment by oscarkfpang** [comment]
@kdatta 
Sorry I didn't copy the full text of error. I tried to build the source on raspberry pi 3 and have encountered many times the error of check sum as above. Finally I give up and install tensorflow on Pi from pip.

**Comment by OleksandrMalinin** [comment]
similar issue
https://github.com/bazelbuild/bazel/issues/3737

**Comment by aselle** [comment]
@gunan, another example of this issue. 
see also #13080

**Comment by aselle** [comment]
Also #12979

**Comment by gunan** [comment]
deduping and merging all of these on #12979

**Comment by kdatta** [comment]
thanks
