### ISSUE TITLE
Does tensorflow is used for content based recommendations?

### ISSUE THREAD

**Issue by dilipbobby** [tensorflow/tensorflow#12990]
Hi,
I wanted to perform content based recommendation (context based) but I did not find any example of tensor flow doing it.can we use tensor flow for doing content based recommendations.

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by mariombaltazar** [comment]
Hi @dilipbobby,
Did you find anything with content based?
thanks

**Comment by dilipbobby** [comment]
No ! not yet ! I worked out that with normal python code.I will look into how to perform content based recommendations using tensor-flow when I have some free time.
