### ISSUE TITLE
Use Bazel 0.1.1

### ISSUE THREAD

**Issue by davidzchen** [tensorflow/tensorflow#130]
Currently, the [TensorFlow Getting Started](http://tensorflow.org/get_started/os_setup.md#installing_from_sources) doc recommends using Bazel 0.1.0. This is a pretty old release, and a number of bugs, such as bazelbuild/bazel#586, has been fixed since then.

This is a tracking bug to switch to a newer version of Bazel. I believe we are in the process of cutting a new release. I will ping this bug once we are ready to update the docs to recommend using a newer Bazel release.

Related: https://github.com/tensorflow/tensorflow/issues/129

**Comment by craigcitro** [comment]
:+1: we use `0.1.1` in the Docker builds, so I can confirm TF will build with it.

**Comment by davidzchen** [comment]
Let's go ahead and update the docs to recommend 0.1.1 since this release contains a number of fixes and improvements over 0.1.0 and is known to work for building TF. I'll combine this with #129.
