### ISSUE TITLE
pip error while training model on cloud

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [tensorflow/tensorflow#13006]
The replica master 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-9_013O-build/setup.py' The replica worker 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-QNtwDr-build/setup.py' The replica worker 1 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-pA8eBo-build/setup.py' The replica worker 2 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-Xk5nGm-build/setup.py' The replica worker 3 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-3VkzR6-build/setup.py' The replica worker 4 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-NIf2Jb-build/setup.py' The replica worker 5 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-RlyPFQ-build/setup.py' The replica worker 6 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-QXzr7y-build/setup.py' The replica worker 7 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-FvkZhP-build/setup.py' The replica worker 8 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-Ue8_oJ-build/setup.py' The replica ps 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-AxLdZ1-build/setup.py' The replica ps 1 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-7nE9PF-build/setup.py' The replica ps 2 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "<string>", line 1, in <module> IOError: [Errno 2] No such file or directory: '/tmp/pip-GSkkn1-build/setup.py' To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=802068032926&resource=ml_job%2Fjob_id%2Fhotifya9f40b85_e142_431b_82fc_8be28b5dc8c2&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22hotifya9f40b85_e142_431b_82fc_8be28b5dc8c2%22

**Comment by ramesh-chowdeshetty** [comment]
Could you please somebody help me to sort this out. I have already pip even though i am getting same

**Comment by yahirb** [comment]
Could you please make the logs public. Also, does your training work on your local computer?

**Comment by gunan** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
