### ISSUE TITLE
'load_csv_with_header' no longer works. Please suggest a solution.

### ISSUE THREAD

**Issue by chandu1909** [tensorflow/tensorflow#13009]
I've been trying to run the tutorial program on IRIS data set and everytime when I try to run the program am seeing this error.

'module' object has no attribute 'load_csv_with_header'

Please suggest me how to solve this.

**Comment by facaiy** [comment]
Could you paste the full stack trace of exception?

**Comment by reedwm** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by chandu1909** [comment]
@reedwm  Thank you for the reply. I'm using Ubuntu 16.04 64-bit.  Tensorflow version 0.9.0. I copied the code and saved it as peptide_trail.py. and I run this code with this command. I activated tensorflow with the following command. (source activate  tensorflow). After that I run this program with this command.
 (python peptide_trail.py). then I got the error saying 

AttributeError: 'module' object has no attribute 'load_csv_with_header'

**Comment by reedwm** [comment]
I assume you're referring to the tutorial [here](https://www.tensorflow.org/get_started/estimator#load_the_iris_csv_data_to_tensorflow). Upgrade to the latest version of TensorFlow, 1.3. I'm guessing the problem is that your TensorFlow version is too old.

**Comment by chandu1909** [comment]
@reedwm  I just updated my tensorflow and tried to run the program again. But, The error is completely insane. I don't understand why my university website link is in the error. Could you please explain me what's the error saying?

here is the error: (Filename is iristutorial)
Traceback (most recent call last):
  File "iristutorial.py", line 87, in <module>
    main()
  File "iristutorial.py", line 38, in main
    features_dtype=np.float32)
  File "/home/chandrasekhar/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 48, in load_csv_with_header
    n_samples = int(header[0])
ValueError: invalid literal for int() with base 10: "<html><head><META http-equiv='refresh' content='1;URL=https://ccas-zone1-1.wku.edu/auth/perfigo_weblogin.jsp?cm=ws32vklm&uri=http%3A%2F%2Fdownload.tensorflow.org%2Fdata%2Firis_test%2Ecsv'></head><body"

**Comment by reedwm** [comment]
My guess is that your university has some sort of login page before you can access the internet, and that the program is downloading the login page instead of the datasets. Try manually downloading the datasets in a web browser.

Ask on StackOverflow if you have more questions.
