### ISSUE TITLE
Add `Dataset.from_variable_length` to accept numpy arrays with varying length

### ISSUE THREAD

**Issue by rasmusbergpalm** [tensorflow/tensorflow#13018]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS x
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: `v1.3.0-rc2-20-g0787eee 1.3.0`
- **Python version**: `Python 3.5.2 :: Continuum Analytics, Inc.`
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: 
```
import numpy as np
from tensorflow.contrib.data import Dataset
a=[np.arange(3), np.arange(5)]
Dataset.from_tensor_slices(np.asarray(a))
```

### Describe the problem
`Dataset` has a nice `.padded_batch` feature which allows padding batches to ensure all tensors have the same size, which is very nice for the common use-case of having sequences of different lengths.

However, it seems impossible to create such a dataset from a list of numpy array with different lengths. See command above.

It would be very nice to have a `Dataset.from_variable_length_tensor_slices` or such that could take such inputs.

I know I'm supposed to use a `TextLineDataset` or something similar, and then use a series of map functions, but I think tensorflow should support doing all of the pre-processing outside of tensorflow instead of forcing it into a delayed execution graph paradigm, which is harder to reason about and debug. Also, my data is stored in JSON files, and requires complex pre-processing, so the `TextLineDataset/map` approach doesn't cut it.

**Comment by mrry** [comment]
You can use the new `Dataset.from_generator()` to do this (and in general wrap any Python code written as a generator in a `Dataset`):

```python
a = [np.arange(3), np.arange(5)]
dataset = tf.contrib.data.Dataset.from_generator(lambda: a, a[0].dtype)
```

**Comment by rasmusbergpalm** [comment]
Yes that works beautifully. Thanks!

One small change to the code:

```python
a = [np.arange(3), np.arange(5)]
dataset = tf.contrib.data.Dataset.from_generator(lambda: a, tf.int64)
```

**Comment by harpone** [comment]
It doesn't seem to be in 1.3... when will this be released? What's the minimal thing I can do the get it *now*? :smile_cat:

**Comment by mrry** [comment]
@harpone: `pip install tf-nightly` should do it!

But as you observed in EDIT2, the code in `Dataset.from_generator()` is built entirely out of transformations that were available in TF 1.3, so you can copy its implementation into your project and use it directly.

**Comment by harpone** [comment]
Yeah already installed a nightly build but thanks! BTW I'm getting some weirdness with (yesterday's) nightly: I'm doing

```
    def input_fn():
        """

        Returns:
            features: A dict containing key/value pairs that map feature column names to Tensors
                        containing the corresponding feature data
            targets: A Tensor containing label (target) values

        """
        if y is not None:
            data_this = [(x_, y_) for x_, y_ in zip(x, y)]
        else:
            data_this = x

        dataset = tf.contrib.data.Dataset.from_generator(lambda: data_this, (tf.float32, tf.float32))
        dataset = dataset.map(cropper)
        dataset = dataset.repeat(epochs)
        if shuffle:
            dataset = dataset.shuffle(buffer_size=10000)
        dataset = dataset.batch(batch_size)
        iterator = dataset.make_one_shot_iterator()

        if y is not None:
            features, targets = iterator.get_next()
            return features, targets
```
with a dataset formed of lists of same but varying shape x, y tensors. I get
`2017-09-23 12:26:55.844395: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: StopIteration: Iteration finished.` which repeats `epoch` number of before the actual training. If I just do `.repeat()` it just throws the Out of range message forever...

Anyway, I'm starting to really like the Dataset class (together with the Estimator). Really impressive work :)

**Comment by amitoengg** [comment]
`a = [np.arange(3), np.arange(5)]
dataset = tf.contrib.data.Dataset.from_generator(lambda: a, tf.int64)
ds1=dataset.repeat(10)
value = ds1.make_one_shot_iterator().get_next()
 sess.run(value)   /// first element
 sess.run(value)   /// second element
 sess.run(value) // Out of range message

throws OutOfRangeError : End of sequence

`

**Comment by amitoengg** [comment]
@harpone did just copying 
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/data/python/ops/dataset_ops.py](url) suffice when using 1.3 as the base installation ?

**Comment by harpone** [comment]
I actually got some other errors when I tried the copying, but yeah, no... I just created a new virtual env and installed the nightly.
