### ISSUE TITLE
nightly link broken on github README.md

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#13024]
On github page, nightly for Linux GPU Python 3.5 is broken, points to

https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3.5,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-1.4.0dev-cp35-cp35m-linux_x86_64.whl

![screenshot 2017-09-13 17 28 11](https://user-images.githubusercontent.com/23068/30406796-00aa9d00-98a9-11e7-8d7b-4226c2401df7.png)

![screenshot 2017-09-13 17 28 56](https://user-images.githubusercontent.com/23068/30406804-130eaa40-98a9-11e7-887d-00a39ec0bdc5.png)

**Comment by yaroslavvb** [comment]
cc @gunan in case he knows where those links come from

**Comment by gunan** [comment]
We just updated the way nightlies are versioned. tonight after the first pip packages are generated it should be fixed.
We are also planning to move all our nightly pip packages to pypi, which will resolve repeated breakage in nightly links.

**Comment by av8ramit** [comment]
We have rolled out [tf-nightly](https://pypi.python.org/pypi/tf-nightly) packages and I've [merged](https://github.com/tensorflow/tensorflow/pull/13198) a fix for the links. The package name has changed, but these are consistently built every night.
