### ISSUE TITLE
GMM clustering example not working

### ISSUE THREAD

**Issue by tranlm** [tensorflow/tensorflow#13029]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.12.6
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.0.0-rc2-15-g47bba63-dirty 1.0.0
- **Python version**: Python 3.6.0 |Anaconda 4.3.1 (x86_64)| (default, Dec 23 2016, 13:19:00) 
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: python gmm_test.py

### Describe the problem
I'm trying to use the gaussian mixed model clustering algorithm from contrib. However, the gmm class is really buggy and I'm unable to get the test cases in the gmm_test.py file to work. 

### Source code / logs
Using the iris dataset from sklearn, I've tried to update the gmm.fit step to use it (as opposed to an input_fn).

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
