### ISSUE TITLE
How to check tensorflow/inception - version number from an inception .pb-file?

### ISSUE THREAD

**Issue by IcyCheetah358** [tensorflow/tensorflow#13037]
Hi, I am trying to figure out which Tensorflow version an inception .pb file is (https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip). This file is used in a OpenCV-plugin to Unity3D game engine (OpenCV for Unity, Enox-software, wraps OpenCV 3.3.0). I replaced these files with a model I re-trained with TF 1.3.0 yesterday and it made the whole Unity3D editor crash. So I assume I have the wrong tensorflow/inception-version (as the default zip-version worked, and my re-trained model worked inside docker-test), but I do not know what is the right version to use due to lack of documentation / knowledle / being tf-noobie. Does anybody here know how to check the version from the .pb-file ?

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
