### ISSUE TITLE
cub::BlockReduce error while building tensorflow in windows using cmake

### ISSUE THREAD

**Issue by lalwaniabhi** [tensorflow/tensorflow#13038]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
    No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
    Windows 10 (64 bit)
- **TensorFlow installed from (source or binary)**:
    Using CMake and instructions present at (tensorflow/tensorflow/contrib/cmake)
- **TensorFlow version (use command below)**:
    -Using Master Branch
- **Python version**: 
    3.6.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
   CUDA-8.0.61
   cuDNN-5.1
- **GPU model and memory**:
   NVIDIA GeForce GTX TITAN X (382.05)
- **Exact command to reproduce**:
   MSBuild /p:Configuration=Release tf_label_image_example.vcxproj

### Describe the problem
I encounter the following error while building the tensorflow project for image recognition (tf_label_image_example.vcxproj). The error occurs when this image recognition project builds tf_core_gpu_kernels.vcxproj.

error : argument list for template "cub::BlockReduce<T, BLOCK_DIM_X, ALGORITHM, BLOCK_DIM_Y, BLOCK_DIM_Z, PTX_ARCH>::Reduce [with T=std::iterator_tra its<T>::value_type, BLOCK_DIM_X=num_threads, ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, BLOCK_DIM_Y=1, BLOCK_DIM_Z=1, PTX_ARCH=0]" is missing.

**Comment by tblattner** [comment]
I am having the same/similar issue in Windows 7, using the same CMake instructions you linked above.

Compilation: MSBuild /p:Configuration=Release tf_tutorials_example_trainer.vcxproj

Errors: 
"C:\Users\tjb3\tensorflow\tensorflow\contrib\cmake\build2\tf_tutorials_example_
trainer.vcxproj" (default target) (1) ->
"C:\Users\tjb3\tensorflow\tensorflow\contrib\cmake\build2\tf_core_gpu_kernels.v
cxproj" (default target) (113) ->
(CustomBuild target) ->
  C:/Users/tjb3/tensorflow\tensorflow/core/kernels/reduction_ops_gpu_kernels.h(
179): error : argument list for template "cub::BlockReduce<T, BLOCK_DIM_X, ALGO
RITHM, BLOCK_DIM_Y, BLOCK_DIM_Z, PTX_ARCH>::Reduce [with T=std::iterator_traits
<T>::value_type, BLOCK_DIM_X=num_threads, ALGORITHM=cub::BLOCK_REDUCE_WARP_REDU
CTIONS, BLOCK_DIM_Y=1, BLOCK_DIM_Z=1, PTX_ARCH=0]" is missing [C:\Users\tjb3\te
nsorflow\tensorflow\contrib\cmake\build2\tf_core_gpu_kernels.vcxproj]
  C:/Users/tjb3/tensorflow\tensorflow/core/kernels/reduction_ops_gpu_kernels.h(
214): error : argument list for template "cub::WarpReduce<T, LOGICAL_WARP_THREA
DS, PTX_ARCH>::Reduce [with T=std::iterator_traits<T>::value_type, LOGICAL_WARP
_THREADS=32, PTX_ARCH=0]" is missing [C:\Users\tjb3\tensorflow\tensorflow\contr
ib\cmake\build2\tf_core_gpu_kernels.vcxproj]

**Comment by mrry** [comment]
@ekelsen I think this is the same bug that was reported yesterday with a fix in the works... can you close this issue when the change makes it to `HEAD`?

**Comment by yaroslavvb** [comment]
btw, you can do "blabla, fixes #13038" in public changelist description, and github will automatically close the issue when commit gets merged into master

**Comment by lalwaniabhi** [comment]
I am receiving another error now in the file maxpooling_op.obj while trying to build tf_label_image_example.
This is the error message which was generated.

"C:\Users\alalwani\tensorflow\tensorflow\contrib\cmake\build\tf_label_image_example.vcxproj" (default target) (1) ->
(Link target) ->
  maxpooling_op.obj : error LNK2001: unresolved external symbol "public: bool __cdecl tensorflow::functor::MaxPoolForwardWithOptionalArgmax<struct Eigen::QInt8>::operator()(struct Eigen::QInt8 const *,int,int,int,int,int,int,int,int,int
,int,int,int,struct Eigen::QInt8 *,__int64 *,struct Eigen::GpuDevice const &)" (??R?$MaxPoolForwardWithOptionalArgmax@UQInt8@Eigen@@@functor@tensorflow@@QEAA_NPEBUQInt8@Eigen@@HHHHHHHHHHHHPEAU34@PEA_JAEBUGpuDevice@4@@Z) [C:\Users\alalwa
ni\tensorflow\tensorflow\contrib\cmake\build\tf_label_image_example.vcxproj]
  C:\Users\alalwani\tensorflow\tensorflow\contrib\cmake\build\Release\tf_label_image_example.exe : fatal error LNK1120: 1 unresolved externals [C:\Users\alalwani\tensorflow\tensorflow\contrib\cmake\build\tf_label_image_example.vcxproj]

**Comment by akashjobanputra** [comment]
Where's the solution ?

**Comment by ekelsen** [comment]
Are you sure you're at HEAD?  That line number doesn't correspond to anything anymore and the error you're referring to should be fixed.

**Comment by akashjobanputra** [comment]
Ok, my mistake. Did `git pull` and re-executed build commands. Now #13065 is encountered.
