### ISSUE TITLE
Broken links in C++ API docs

### ISSUE THREAD

**Issue by Styrke** [tensorflow/tensorflow#1303]
Apparently most of the links in the main part of the [index of the C++ API documentation](https://www.tensorflow.org/versions/r0.7/api_docs/cc/index.html) are broken.

The problem seems to be that the first letter of each file name is in lowercase, so the links look like this:
[https://www.tensorflow.org/versions/r0.7/api_docs/cc/classEnv.html](https://www.tensorflow.org/versions/r0.7/api_docs/cc/classEnv.html)
Instead of this:
[https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassEnv.html](https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassEnv.html)

**Comment by girving** [comment]
@chemelnucfin: Is this bug fixed now?

**Comment by chemelnucfin** [comment]
@girving see pull request #1314
