### ISSUE TITLE
Training a model using GPUs across different machines

### ISSUE THREAD

**Issue by amitaga** [tensorflow/tensorflow#1304]
Hi, if/how can TensorFlow's distributed runtime be used for training a model using GPU resources across machines in a cluster?

**Comment by mrry** [comment]
It certainly can! Have a look at the [readme](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/README.md) for how to get started. You can place nodes on GPUs on different machines using `tf.device()` statements:

```python
with tf.device("/job:worker/task:0/gpu:0"):
  # ...
with tf.device("/job:worker/task:0/gpu:1"):
  # ...
with tf.device("/job:worker/task:1/gpu:0"):
  # ...
# ...
```
