### ISSUE TITLE
Feature request: Dataset.from_py_func

### ISSUE THREAD

**Issue by qtdaniel** [tensorflow/tensorflow#13040]
I have an input pipeline that is especially complex. It is coded entirely in plain Python. While it *may* be possible to reimplement it in TensorFlow operations, that would be a huge amount of work and take far too much time to be worth it right now.

It would be great if I could hook my existing pipeline into the new Dataset approach via something like `Dataset.from_py_func`. One would pass a reference to a Python function that has no inputs and, when executed, acts as a generator that yields examples one-at-a-time as numpy arrays. For example:

    def generate():
        for example in complex_input_pipeline():
            yield example

    dataset = Dataset.from_py_func(generate)
    # Do normal things with dataset
        
I've been unable to figure out a way to do something like this using existing functionality so it would be great if it could be added.

**Comment by mrry** [comment]
Have a look at`Dataset.from_generator()` in the nightly build... it is almost exactly what you're looking for!
