### ISSUE TITLE
Can I install and run TensorFlow on my machine with this much of information----->

### ISSUE THREAD

**Issue by Shiv751** [tensorflow/tensorflow#13045]
C:\Users\SEM>python Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information. >>>

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
