### ISSUE TITLE
tf.graph_util.extract_sub_graph should raise a better error message

### ISSUE THREAD

**Issue by Sentient07** [tensorflow/tensorflow#13047]
Hi, 

I used `tf.graph_util.extract_sub_graph` to get a subgraph reaching a particular dest node. My dest_node is say `conv2d_transpose_7`. I by mistake gave it as a string in the second parameter. Python parses String too as a list and it raised an error `AssertionError: c is not in graph`. The `extract_sub_graph` should first check if the second parameter `isinstace` of a List so that it would be convenient to debug this kind of error in the future. A screenshot is attached.

Thanks, 

<img width="613" alt="screenshot at sep 14 23-53-32" src="https://user-images.githubusercontent.com/6195312/30446912-22e74a76-99a8-11e7-81b4-3479d2e49c09.png">

**Comment by facaiy** [comment]
Sounds reasonable, I can work on it.

**Comment by reedwm** [comment]
Marking as contributions welcome since @facaiy is working on it
