### ISSUE TITLE
Clarifying relations of high level APIs

### ISSUE THREAD

**Issue by JarnoRFB** [tensorflow/tensorflow#13059]
There are right now several high level APIs in TensorFlow (`tf.keras`, `tf.estimators`, `tf.layers`, `tf.contrib.learn`) that seem to be sometimes complementary and sometimes redundant. It is somewhat hard for me (and other parts of the internet I have searched) to understand which API to use for which purpose and how they relate to each other.

For me it would greatly help if it could be specified:
* What is the intended high level API for the future? Even so if none of them will be discontinued, it would be nice one could just get pointed to one preferred. All I could find the documentation right now is: 
"The higher level APIs are built on top of TensorFlow Core. These higher level APIs are typically easier to learn and use than TensorFlow Core. In addition, the higher level APIs make repetitive tasks easier and more consistent between different users. A high-level API like tf.estimator helps you manage data sets, estimators, training and inference."
* How different modules from `contrib` relate to those in core tensorflow. E. g. it seems that `tf.estimators` is a portion of `tf.contrib.learn` that made it into core.
* Why there are duplicate implementations like `tf.layers.contrib.conv2d` and `tf.layers.conv2d`?
* If modules have complementary or duplicate functionality. E.g. `tf.layers` can be used with `tf.estimators` to define the model, but probably one does not want to mix `tf.layers` and `tf.keras` .

It would be great if that could be specified in the Overview section of the respective documentations, instead of just saying it is a high level API

**Comment by yaroslavvb** [comment]
cc @martinwicke

**Comment by martinwicke** [comment]
Here are a few general guidelines:

- Everything in contrib is experimental. Some of it may move to core (tf.estimator is a piece of contrib.learn which moved to core), some of it may not. 
- There are strong API guarantees for things not in contrib, there are no such guarantees in contrib.
- Nevertheless, we avoid removing things without notice, so this process leaves duplicates (often with slight differences) in contrib.
- We will mark a lot of things in contrib to be explicitly deprecated in the coming months to make this clearer.
- Consequently, if there is an option to use that's not in contrib, use it. It's safe, won't change, and won't be removed.
- tf.layers in fact does work (mostly) with tf.keras. tf.keras is a full implementation of the Keras 2.0 spec, which is partly collected from other places in TensorFlow via simple aliases, and partly by extending functionality implemented elsewhere. If you rely on compatibility with Keras, use tf.keras. Mixing with other things in TensorFlow is generally ok, but some things may not work (e.g. tf.layers.Dense does not currently support serialization). All of TensorFlow can be used with tf.estimator.

I know the current state of contrib is confusing, and we're working on cleaning it up.

**Comment by facaiy** [comment]
Hi, @martinwicke . I noticed that contrib supports more features than core. Say, `tf.contrib.learn.estimator` supports `feature_enginerring_fn`, while `tf.estimator` not. If `tf.contrib.learn.estimator` is deprecated, where do we find the missing features?

**Comment by yaroslavvb** [comment]
@facaiy `tf.contrib` is experimental API, things in contrib can disappear/get renamed/etc. IE, no guarantee that `feature_enginerring_fn` from contrib will exist in future versions of TF

**Comment by martinwicke** [comment]
We decided not to further support feature_engineering_fn.

We experiment with designs in contrib. The things that work go to core. The
things that don't don't. feature_engineering_fn did not make the cut.

It's use case is unclear and it causes a bunch of gnarly problems.

**Comment by facaiy** [comment]
Thanks, @martinwicke . I understand `feature_engineering_fn` not a perfect solution. How about using pipeline? Will tensorflow plan to use pipeline to simply feature transform for training and predicting, like sklearn and spark?

**Comment by martinwicke** [comment]
Check out github.com/tensorflow/transform. I think it may be what you want.
