### ISSUE TITLE
distributed Tensorflow assign device issue

### ISSUE THREAD

**Issue by RuofanKong** [tensorflow/tensorflow#13075]
I recently found an interesting issue on device assignment when I ran the following simple code `test.py`:

```
import argparse
import tensorflow as tf

CLUSTER_SPEC = {"ps": ["localhost:2222"],
                "worker": ["localhost:1111", "localhost:1112"]}


def parse_command_arguments():
    """ Set up and parse the command line arguments. """
    parser = argparse.ArgumentParser(
        description="Parameters and Arguments for the Test.")
    parser.add_argument(
        "--job_name", type=str, default="", help="One of 'ps', 'worker'")
    parser.add_argument(
        "--task_index", type=int, default=0, help="Index of task")
    return parser.parse_args()


def start_server(job_name, task_index, tf_config):
    """ Create a server based on a cluster spec. """
    cluster = tf.train.ClusterSpec(CLUSTER_SPEC)
    server = tf.train.Server(
        cluster, config=tf_config, job_name=job_name, task_index=task_index)
    return server, cluster


def model(cluster=None, worker_device=None):
    """ Build up a simple estimator model. """
    with tf.device(tf.train.replica_device_setter(
            worker_device=worker_device, cluster=cluster)):
        W = tf.Variable([1.0], tf.float32)
        b = tf.Variable([10.0], tf.float32)
        x = tf.placeholder(tf.float32)
        y = W * x + b
    return W, b, x, y


if __name__ == "__main__":
    arguments = parse_command_arguments()
    job_name = arguments.job_name
    task_index = arguments.task_index
    # Set up tensorflow configuration.
    tf_config = tf.ConfigProto(
        allow_soft_placement=True, device_count={'GPU': 1},
        log_device_placement=True)
    # Start a server.
    server, cluster = start_server(job_name, task_index, tf_config)

    if job_name == "ps":
        server.join()
    else:
        worker_device = "/gpu:0"
        W, b, x, y = model(cluster, worker_device=worker_device)
        is_chief = (arguments.task_index == 0) and (
            arguments.job_name == 'worker')
        sess = tf.train.MonitoredTrainingSession(
             master=server.target, is_chief=is_chief, config=tf_config)
        # Run the model.
        step = 0
        x_train = [1, 2, 3, 4]
        y_train = [0, -1, -2, -3]
        while not sess.should_stop() and step < 1000:
            sess.run([y], {x: x_train, y: y_train})
            step += 1
```
As the code uses `tf.train.replica_device_setter()` with `worker_device="/gpu:0"`, I imagine all tensorflow `Variable` ops go to the parameter server, while all other type of ops stay in the worker.

However, if we run the above code:
`$ python test.py --job_name ps --task_index 0`
`$ python test.py --job_name worker --task_index 0`
`$ python test.py --job_name worker --task_index 1`
I notice that all tensorflow ops go to parameter server, for example in the worker log: 
`report_uninitialized_variables/boolean_mask/strided_slice/stack_2: (Const)/job:ps/replica:0/task:0/gpu:0`.

But if I change `worker_device="/gpu:0"` in the code to `worker_device="/job:worker/task:0/gpu:0"`, then the result is correct (all non-Variable ops go to worker). So does it mean there is a bug for `tf.train.replica_device_setter()` to automatically assign devices?

P.S The above code runs on single GPU (TITAN X (Pascal)/PCIe/SSE2) with Ubuntu 16.04, Python 3.5 and Tensorflow v1.2

**Comment by yaroslavvb** [comment]
Hm, that seems strange, from the logic [here](https://github.com/tensorflow/tensorflow/blob/0dfb1825ea20e7d4da6c57e4ba3710547562d423/tensorflow/python/training/device_setter.py#L119) it seems anything that's not a Variable will be assigned to be on worker_device.

Since only workers construct the graph, "/gpu:0" should resolve to worker's /gpu:0
Maybe you could add some print's in device_setter.py or add `print(graph_def.SerializeToString()` [here](https://github.com/tensorflow/tensorflow/blob/581f59447ac138857f07169f9fe7b1c2c5687a6b/tensorflow/python/client/session.py#L1351) to see what "device" annotation is given to those ops

**Comment by mrry** [comment]
@yaroslavvb wrote:
> Since only workers construct the graph, "/gpu:0" should resolve to worker's /gpu:0

That's not how the placement algorithm works. You must include `"/job:worker"` in the device spec to guarantee that the op will be placed on a task in the `worker` job.

If you override the default `worker_device` argument (which is `"/job:worker"`) with `"/gpu:0"`, there's no guarantee that the task will be placed in any particular task.

**Comment by RuofanKong** [comment]
@yaroslavvb @mrry Thanks for the reply! That makes sense. But I still don't understand why all tensorflow ops go to the parameter server, is it intentional? The other issue is I compared the performance for using `worker_device="/job:worker/task:0"` vs. `worker_device="/gpu:0"`, and I noticed that when `worker_device="/gpu:0"` where all ops go to parameter server, the training performance is much better than using `worker_device="/gpu:0"`. Is it also intentional?

**Comment by yaroslavvb** [comment]
@mrry interesting .... the the following example is similar, is it also going to run the op on an arbitrary machine?

```
server = tf.Server(...)
sess = tf.Session(server.target)
with tf.device("/gpu:0"):
   sess.run(tf.random_uniform())
```

**Comment by yaroslavvb** [comment]
It sounds like short form ("/gpu:0") for distributed is not really supported, I'll close it since it doesn't seem to be a bug, but if someone figures out where the logic lives, it would be useful to update it here

**Comment by niewuya** [comment]
@RuofanKong When the operation runs in worker's GPU, the worker needs to fetch the variables from the PS by network. It is slower than the operation runs in PS because  the variables are stored in  PS. Maybe you can use the tcpdump to catch the data in network to prove what I guess.
