### ISSUE TITLE
unit test tools print all failure logs if failed

### ISSUE THREAD

**Issue by facaiy** [tensorflow/tensorflow#13076]
When a PR is tested failed, Jenkins just reports failure and tells where to check log. However, at least for me, I don't know whether I have the permission, and where to find the logs. So I have to reproduce the failed test on my own machine, but maintaining all kinds of environment is an unnecessary burden for each developer (cpu, gpu, py2, py3, window...)

```bash
//tensorflow/tools/test:check_futures_test                               PASSED in 1.3s
//tensorflow/user_ops:ackermann_test                                     PASSED in 2.3s
//tensorflow/user_ops:duplicate_op_test                                  PASSED in 2.2s
//tensorflow/user_ops:invalid_op_test                                    PASSED in 2.1s
//tensorflow/python/kernel_tests:matrix_solve_ls_op_test                TIMEOUT in 65.0s
  /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/testlogs/tensorflow/python/kernel_tests/matrix_solve_ls_op_test/test.log

Executed 1205 out of 1205 tests: 1204 tests pass and 1 fails locally.
```

It will be more convenient to attach total failure content at the end for developers to debug, like reports of `py.test`:

```bash
$ pytest
======= test session starts ========
platform linux -- Python 3.x.y, pytest-3.x.y, py-1.x.y, pluggy-0.x.y
rootdir: $REGENDOC_TMPDIR, inifile:
collected 1 item

test_sample.py F

======= FAILURES ========
_______ test_answer ________

    def test_answer():
>       assert inc(3) == 5
E       assert 4 == 5
E        +  where 4 = inc(3)

test_sample.py:5: AssertionError
======= 1 failed in 0.12 seconds ========
```

**Comment by aselle** [comment]
@gunan, is there any way we can support a better workflow for accessing the failing logs. Perhaps with your new project?

**Comment by gunan** [comment]
Next week we should have something

**Comment by gunan** [comment]
Actually. in the full log, if you serarch in page for the failed test, you can find the full dump of the test logs.
However, I agree that they are difficult to find.
Next week, we will migrate to a better solution, which should solve this problem.

**Comment by facaiy** [comment]
Cool, since the issue will be fixed later, so I close it.
