### ISSUE TITLE
Deallocation messages broken

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#13087]
The only way to calculate peak memory in OSS TensorFlow is to make memory timeline by parsing allocation/deallocation messages (possibly using helpers like [this](github.com/yaroslavvb/memory_util))

Sometime between TF 1.0.1 and TF 1.1, the deallocation messages stopped including allocation id, so you can't track when each tensor got deallocated. 

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = ''
os.environ['TF_CPP_MIN_VLOG_LEVEL'] = '1'
os.environ['CUDA_VISIBLE_DEVICES'] = ''
import tensorflow as tf
import numpy as np

sess = tf.Session()
a = tf.ones((1000,1000))
sess.run(a)
```

In TF 1.0.1 you see this
`2017-09-16 13:24:28: I tensorflow/core/framework/log_memory.cc:35] __LOG_MEMORY__ MemoryLogTensorDeallocation { allocation_id: 1 allocator_name: "cpu" }
`

In latest TF you see this

`2017-09-16 13:25:04.422108: I tensorflow/core/framework/log_memory.cc:35] __LOG_MEMORY__ MemoryLogTensorDeallocation { allocator_name: "cpu" }
`

Note that deallocation id is missing in later version

cc @panyx0718 who mentioned ongoing work for tracking memory deallocation

**Comment by yaroslavvb** [comment]
BTW, this is only for CPU memory deallocation messages, GPU deallocation messages continue to work

**Comment by reedwm** [comment]
Fields are only printed if they are not zero, so if it doesn't appear, it's zero.

To see this, note the protobuf is printed at [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/log_memory.cc#L36). `ProtoShortDebugString` is defined in a generated file, which you can see after compiling tensorflow with `less bazel-genfiles/tensorflow/core/framework/log_memory.pb_text.cc`. That file has the function

```c++
void AppendProtoDebugString(
    ::tensorflow::strings::ProtoTextOutput* o,
    const ::tensorflow::MemoryLogTensorDeallocation& msg) {
  o->AppendNumericIfNotZero("allocation_id", msg.allocation_id());
  o->AppendStringIfNotEmpty("allocator_name", ProtobufStringToString(msg.allocator_name()));
}
```
