### ISSUE TITLE
How can I change value by threshold in tensor?

### ISSUE THREAD

**Issue by sunqianggg** [tensorflow/tensorflow#13082]
When I do some 2-class classify practices, I use sigmoid as output layer, and it return a value in [0,1], but I want 1 if the value greater than 0.5,else set the value 0. I can't find a function to finish it.  Thank you for help. 
Just like:
a=tf.constant([0.1,0.2,0.6,.0.7])--->turn to ---->a=tf.constant([0,0,1,1])

**Comment by ppwwyyxx** [comment]
`tf.to_int32(a > 0.5)`

**Comment by shreyneil** [comment]
You can make your customized activation function.
Follow the link as a guide to do it.

https://stackoverflow.com/questions/39921607/how-to-make-a-custom-activation-function-with-only-python-in-tensorflow

**Comment by aselle** [comment]
Although @ppwwyyxx  and @shreyneil, seem to have already answered your question...

This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
