### ISSUE TITLE
Help completely removing Tensorflow, pip and virtualenv

### ISSUE THREAD

**Issue by hasan9090** [tensorflow/tensorflow#13086]
Hey there,

I am new to all the tf and Python programming and have installed tensorflow through pip and virtualenv but now I read that in order to use Spyder for Python it is best to use Anaconda. I know that tf can be installed through conda as well but how do I go about it now? Do I have to completely remove the existing installations first and if yes, can someone explain in detail which and how I can do it?

Thanks in advance

**Comment by yaroslavvb** [comment]
This doesn't seem to be a bug in tensorflow, it's better q for stackoverflow
