### ISSUE TITLE
ImportError: cannot import name server

### ISSUE THREAD

**Issue by mmuppidi** [tensorflow/tensorflow#1308]
Operating System:
Ubuntu 14.04

Built tensor board from the source (from tensor flow git repo)

```sudo apt-get install nodejs nodejs-legacy npm```

```sudo npm install -g gulp bower```

cd tensorflow/tensorflow/tensorboard/

```npm install```

```bower install```

Everything goes fine. Now I try to run the TensorFlow using command

```>> python tensorflow/tensorflow/tensorboard/tensorboard.py --logdir=bla_logs```

```
Traceback (most recent call last):
  File "tensorflow/tensorflow/tensorboard/tensorboard.py", line 33, in <module>
    from tensorflow.tensorboard.backend import server
ImportError: cannot import name server
```

Then I changed the following line in tensorboard.py 

```from tensorflow.tensorboard.backend import server```

to

```from tensorflow.tensorboard.backend import tensorboard_server as server```

Now it works fine.

**Comment by vrv** [comment]
@danmane can you take a look?

**Comment by bxshi** [comment]
I was having the same issue yesterday and yes, changing `server` to `tensorboard_server` did solve the problem.

**Comment by mmuppidi** [comment]
@danmane @vrv  I have done some more digging into the issue. I have installed tensor flow using pip command and then cloned the git repository for examples. 

Inside the git cloned repo on master branch inside  tensorboard/backend there is a file called server.py

But in /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/backend there is no file names server.py instead there is a file named tensorboard_server.py, that it why my suggested change was working in my environment. So it looks like there no problem with master branch, once pip package is built using current master branch this issue would go away

hope this helps.

**Comment by vrv** [comment]
Ah, that makes sense.  In general, if you have installed the pip package, we recommend checking out the github repo at that branch, since we make improvements to master which often updates the code that goes into the binary pip package.  Thanks for the help!
