### ISSUE TITLE
mismatch between the reported values of tt.nn.zero_fraction

### ISSUE THREAD

**Issue by amirjamez** [tensorflow/tensorflow#13083]
Has anyone run into this issue before? 

[tt.nn.zero_fraction](https://www.tensorflow.org/api_docs/python/tf/nn/zero_fraction), defined in [nn_imply.py](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/python/ops/nn_impl.py) reports my convs layers in [MobileNet_v1 slim](https://github.com/tensorflow/models/blob/master/slim/nets/mobilenet_v1.py) net have around 0.5 sparsity (conv1-conv13). However, when I freeze the model's weights and look at them, there is none zero values:

```
>>>conv=sess.run('MobilenetV1/Logits/Conv2d_1c_1x1/weights/read:0')
>>>numpy.count_nonzero(conv)
5120
>>>numpy.count_nonzero(conv==0)
0

```

Looking at the histogram, there are many weights' values close to zero. Does that function do approximation? Can anyone verify this?

**Comment by facaiy** [comment]
What the type of conv? I mean, `type(conv)`?

```python
In [7]: np.count_nonzero([1, 0, 0])
Out[7]: 1

In [8]: np.count_nonzero([1, 0, 0] == 0)
Out[8]: 0

In [9]: np.count_nonzero(np.array([1, 0, 0]) == 0)
Out[9]: 2
```

**Comment by amirjamez** [comment]
I can not see your reply in that thread. Have you deleted it?

**Comment by facaiy** [comment]
Yes, I misunderstand your question, @amirjamez .

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
