### ISSUE TITLE
Incorrect protobuf SHA in workspace.bzl for v1.3.0

### ISSUE THREAD

**Issue by samwhitlock** [tensorflow/tensorflow#13080]
### System information

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.3.0 (the tagged version, specifically `9e76bf32`)
- **Python version**: 3.5.3
- **Bazel version (if compiling from source)**: 0.5.4
- **Exact command to reproduce**: `./configure` (with all the default answers, and the specified python version above), then `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

### Describe the problem

When attempting to build the pip package in the repository on the latest tagged release (v1.3.0), I get the following fatal build error:

`ERROR: /home/ubuntu/tensorflow/tools/pip_package/BUILD:100:1: no such package '@protobuf//': java.io.IOException: Error downloading [https://github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz, http://mirror.bazel.build/github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz] to /home/ubuntu/.cache/bazel/_bazel_whitlock/8ea56cff279f39ec6c0003641e649819/external/protobuf/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz: Checksum was e5fdeee6b28cf6c38d61243adff06628baa434a22b5ebb7432d2a7fbabbdb13d but wanted 6d43b9d223ce09e5d4ce8b0060cb8a7513577a35a64c7e3dad10f0703bf3ad93 and referenced by '//tensorflow/tools/pip_package:licenses'`

It looks to me like the SHA changed for that version was not specified correctly. However, this seems strange to me because I had built against this version within the last couple of weeks without issue. `master` does not have this problem.

Replacing the SHA in `tensorflow/workspace.bzl` with the one in the error message (`e5fdeee`...) solves this issue.

**Comment by mmatiaschek** [comment]
Same problem, same solution on branch r1.3 but with Ubuntu 16.04 and `bazel build --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=opt //tensorflow/tools/pip_package:build_pip_package`

i replaced the sha checksum with vi
`vi tensorflow/workspace.bzl
:s/6d43b9d223ce09e5d4ce8b0060cb8a7513577a35a64c7e3dad10f0703bf3ad93/e5fdeee6b28cf6c38d61243adff06628baa434a22b5ebb7432d2a7fbabbdb13d/g`

Thank you @samwhitlock for sharing

**Comment by yongtang** [comment]
I think this is related to GitHub changed the download file with different digest. See #12986 for related issues.

**Comment by aselle** [comment]
@gunan, PTAL. Thanks!

**Comment by gunan** [comment]
@av8ramit We should also patch master with your patch to 1.3

**Comment by cglong** [comment]
Out of curiosity, when can we see a release that includes these updates? I'd like to add TensorFlow into Homebrew (a macOS package manager) but we'll need a tagged source drop that contains this fix to use for the build.

**Comment by gunan** [comment]
Once we have all the archives mirrored, we will look into a new release.
For now, deduplicating this issue in favor of #12979
