### ISSUE TITLE
TensorFlow creates different node name for execution

### ISSUE THREAD

**Issue by sj6077** [tensorflow/tensorflow#13098]
-----------------------
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
TF v1.3
- **Bazel version (if compiling from source)**:
0.4.5
- **CUDA/cuDNN version**:
cuda 8.0/cudnn 5.1.5
- **GPU model and memory**:
Tesla P40 
- **Exact command to reproduce**:

### Describe the problem
This is the tracing result when I executed ptb-lstm application. I wonder the meaning of "sequence_loss_by_example/add/_1077". 
I wanted to create enqueue and dequeue ops for "sequence_loss_by_example/add", but dequeue op is never called, and different node name appears in the tracing file. 
Can you let me know what is happened inside session.run?

<img width="439" alt="2017-09-17 18 42 36" src="https://user-images.githubusercontent.com/2465713/30519717-24a28542-9bd8-11e7-9f2c-511275ec059c.png">

**Comment by yaroslavvb** [comment]
Maybe it's graph rewriting?
Could try

# linearize.linearize()
config = tf.ConfigProto(graph_options=tf.GraphOptions(optimizer_options=tf.OptimizerOptions(opt_level=tf.OptimizerOptions.L0)))
sess=tf.Session(config=config)

**Comment by aselle** [comment]
@sj6077 , did this solve your issue?

**Comment by sj6077** [comment]
Yes, it works now. Thank you!

**Comment by aselle** [comment]
If  your problem is resolved @sj6077, please close the issue.
