### ISSUE TITLE
Tensorflow not detecting my GPU 

### ISSUE THREAD

**Issue by collawolley** [tensorflow/tensorflow#13091]
hi @oelmekki @yaroslavvb did you managed to resolve the issue?
I have the same problem able to use GPU before updating tensorflow to V1.3.0. I have also upgraded my Cudnn to V6. My CUDA is v8.0 so I don't seem to understand where the problem is coming from. I can verify that my tensorflow is GPU version because I used tfBInaryUrl for Python2.7-PGU support. Aside this, I have also installed several times with 'pip install tensorflow-gpu' and I still cannot run my codes on gpu. Theano works fine and I could run code with GPU if I use theano. 

When I tried to force the computation to be run on GPU , my codes wouldn't run and now, I got this mesage "Device mapping: no known devices.

The frustrating thing is that I was using the GPU before I upgraded to v1.3.0/

I would appreciate any help as regards this problem.
"

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
