### ISSUE TITLE
Feature Request - SRU (Simple Recurrent Unit) Cell

### ISSUE THREAD

**Issue by desire2020** [tensorflow/tensorflow#13094]
ArXiv path: https://arxiv.org/abs/1709.02755

This is a recently proposed, parallelization-friendly RNN cell. The author released his own PyTorch version of the SRU. We are looking forward to an offical tensorflow implementation with Cudnn optimizations.

**Comment by tjingrant** [comment]
Hi, I'm interested in taking a crack at this. Will keep you updated.

**Comment by buptpriswang** [comment]
Hi, it's interesting RNN cell, will keep you updated

**Comment by argman** [comment]
Any progress?

**Comment by tjingrant** [comment]
Will submit the initial PR early next week. 
Sorry I started late because I have to clear some build errors on master.

**Comment by GeorgyZhou** [comment]
I am interested in this question as well. If @tjingrant have some problems, I can also join in.

**Comment by tjingrant** [comment]
I apologize for keeping everyone interested waiting and will do my best to release a PR early this week. @GeorgyZhou: thanks for your offer, I will let you know if I need extra hands!

**Comment by hadaev8** [comment]
Any news?

**Comment by stegben** [comment]
I'm working on a fused version of SRU (process on whole time steps)

**Comment by danijar** [comment]
Hi @stegben, what's the status of this? It sounds like the fused implementation is really what would make SRU most useful.

**Comment by tjingrant** [comment]
To be honest, after implementing the non-fused version, I suspect whether it's worth going deeper. The [paper](https://openreview.net/forum?id=rJBiunlAW) has been rejected on the ground that it is a special case of Quasi-RNN which makes sense. It's probably better for everyone to work on a better version of Quasi-RNN than keeping implementing SRU.

**Comment by raofengyun** [comment]
@tjingrant it's now published on EMNLP: https://aclanthology.info/papers/D18-1477/d18-1477  
we tried it on some dataset, and it really works good and fast, but we have to use pytorch, since the tf version SRUCell is NOT faster than GRUCell.  

could anyone implement a tf-version SRU instead of SRUCell?

**Comment by dynamicwebpaige** [comment]
Closing, as this feature is outside the scope of TensorFlow Core and no longer relevant, from a research perspective. If I'm mistaken, please feel free to reopen and we can route to [TensorFlow Addons](https://www.github.com/tensorflow/addons). Thanks! 🙂
