### ISSUE TITLE
CUDA 7.0 is hard-coded in `configure` script for Linux

### ISSUE THREAD

**Issue by davidzchen** [tensorflow/tensorflow#131]
I am running Ubuntu 15.04 with CUDA 7.5 installed. However, CUDA 7.0 is hard-coded in the `configure` script, and I am unable to configure to use CUDA 7.5:

```
❯❯❯ ./configure
Do you wish to build TensorFlow with GPU support? [y/n] y
GPU support will be enabled for TensorFlow

Please specify the location where CUDA 7.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Invalid path to CUDA 7.0 toolkit. /usr/local/cuda/lib64/libcudart.so.7.0 cannot be found
```

This is because CUDA 7.5's libraries have the `.7.5` suffix rather than `.7.0`:

```
❯❯❯ ls -l /usr/local/cuda/lib64/libcudart.so*
lrwxrwxrwx 1 root root     16 Aug 15 08:55 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Aug 15 08:55 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 383336 Aug 15 08:55 /usr/local/cuda/lib64/libcudart.so.7.5.18
```

**Comment by sibleyd** [comment]
see https://github.com/tensorflow/tensorflow/issues/54 or https://github.com/tensorflow/tensorflow/issues/20

**Comment by davidzchen** [comment]
Ah, thanks for pointing out those bugs. Feel free to de-dup this issue.

**Comment by attiladoor** [comment]
Hi, i had the same problem, and if you take a look about the configure script:

if [ -z "$CUDA_TOOLKIT_PATH" ]; then
    default_cuda_path=/usr/local/cuda
    read -p "Please specify the location where CUDA $TF_CUDA_VERSION toolkit is installed. Refer to README.md for more details. [Default is $default_cuda_path]: " CUDA_TOOLKIT_PATH

So you have nothingt to do, just find your nvidia toolkit, mine was located in:
/usr/lib32/nvidia-364

so just:

export CUDA_TOOLKIT_PATH=/usr/lib32/nvidia-364

And you are done
