### ISSUE TITLE
Feature Request: API for weights values conversion

### ISSUE THREAD

**Issue by AakashKumarNain** [tensorflow/tensorflow#13112]
It would be very nice if the TensorFlow developers can provide a simple API for converting the weight values, ported from other frameworks like `Theano, Torch, Caffe and Chainer`. A lot of researchers still use these frameworks. Most of the times when an individual convert weights values, obtained from some framework other than TF, the results are not reproducible which is not desirable. Providing such an API, can help the TF community to port the models from other frameworks to TF, proving that the same thing could have been done more easily in TF. The API can have a method that takes the following signature:

```
def port_weights_to_tf(weights values, framework=[Caffe or theano or Torch or chainer]):
       # Change the weight values for each layer and store in hdf5 with layer names
       return modified_weights
```

**Comment by aselle** [comment]
@AakashKumarNain, unfortunately, most TensorFlow developers are focused on developing Tensorflow, and we actually do not have the expertise to write such converters. Incidentally there is more to moving weights. It is also important to ensure that ops have exactly the same semantics and features, and we have been working on that. For example, explicit padding is not available in TensorFlow and so Caffe models that use it, cannot be necessarily matched. We are open to PRs that fix those types of incompatibilities, and we would consider linking to weight conversion tools that others write. Thanks!
