### ISSUE TITLE
Build problem :Configurable attribute "copts" doesn't match this configuration

### ISSUE THREAD

**Issue by darkbridge** [tensorflow/tensorflow#13115]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux pine64 3.10.104-2-pine64-longsleep aarch64 aarch64 aarch64 GNU/Linux
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:1.3.0-rc0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:0.4.5
- **CUDA/cuDNN version**: no
- **Exact command to reproduce**: `bazel build -c opt --copt="-funsafe-math-optimizations" --copt="-ftree-vectorize" --copt="-fomit-frame-pointer" --verbose_failures tensorflow/tools/pip_package:build_pip_package`

### Describe the problem
As  tensorflow supports ARM 64-bit CPU platform,so I build it on PINE64.But after I install bazel exactly, and try to install tensorflow,there is something wrong in building process.

### Source code / logs
```
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/external/nsync/BUILD:401:13: Configurable attribute "copts" doesn't match this configuration (would a default condition help?).
Conditions checked:
 @nsync//:android_arm
 @nsync//:android_arm64
 @nsync//:android_armeabi
 @nsync//:android_x86_32
 @nsync//:android_x86_64
 @nsync//:clang_macos_x86_64
 @nsync//:gcc_linux_aarch64
 @nsync//:gcc_linux_ppc64
 @nsync//:gcc_linux_x86_64_1
 @nsync//:gcc_linux_x86_64_2
 @nsync//:ios_x86_64
 @nsync//:msvc_windows_x86_64.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
```
As the logs errors indicate the file, so I looks the code ,and it indicates the cpp library configure as follow:
 ```
# The library compiled in C++11, rather than C.
397 cc_library(
398     name = "nsync_cpp",
399     srcs = NSYNC_SRC_GENERIC + NSYNC_SRC_PLATFORM_CPP,
400     hdrs = NSYNC_HDR_GENERIC,
401     copts = NSYNC_OPTS_CPP,
402     includes = ["public"],
403     textual_hdrs = NSYNC_INTERNAL_HEADERS + NSYNC_INTERNAL_HEADERS_PLATFORM,
404 )
```
I try to annotation the number 401 code,the errer above seems disapperence but other errer happens.
I appreciate ever help, thank you all very much.

**Comment by lengerrong** [comment]
hi, please refer to here:
just add in NSYNC_OPTS_GENERIC, it might be OK.
"//conditions:default": [],
https://lengerrong.blogspot.com/2017/09/fix-up-configurable-attribute-copts.html

**Comment by lissyx** [comment]
I do reproduce the same while cross-compiling for RPi3, maybe @petewarden can be interested :)

**Comment by lissyx** [comment]
It seems like root issue was documented as https://github.com/tensorflow/tensorflow/issues/12524 and a fix landed for Windows there: https://github.com/tensorflow/tensorflow/pull/12603

That fix seems to imply nsync-side changes in https://github.com/google/nsync/commit/d3bc53d38bee13bf66354ca61694956c92ffe879 though.

@m3bm3b Can you confirm that ?
