### ISSUE TITLE
Build Tensorflow on Windows with /MT option

### ISSUE THREAD

**Issue by alex-petrenko** [tensorflow/tensorflow#13127]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 64-bit
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.3.0 release
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: - (using CMake 3.9.1)
- **Exact command to reproduce**:

```
First: add /MT key to CMAKE_CXX_FLAGS_RELEASE in CMakeLists.txt
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT /D_ITERATOR_DEBUG_LEVEL=0")

Then, CMake and build:

$ cmake .. -G"Visual Studio 15 2017 Win64" -Dtensorflow_BUILD_PYTHON_BINDINGS=OFF -Dtensorflow_ENABLE_GRPC_SUPPORT=OFF -Dtensorflow_BUILD_SHARED_LIB=ON
$ MSBuild /m:2 /p:PreferredToolArchitecture=x64 /p:Configuration=Release tensorflow.vcxproj
```

### Describe the problem
I am getting a lot of link errors of the following type for many 3rd party libraries tensorflow links against:

```
(Link target) ->
         nsync.lib(mu.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in gen_proto_text_functions.obj [C:\all\lib\tensorflow\tensorflow\contrib\cmake\bu
       ild\proto_text.vcxproj]
```

I am not really sure if that's supposed to work, so it can be considered a feature request. I would really like to build tensorflow with /MT to make my application as portable as possible.
Currently, I build tensorflow.dll with Visual Studio 2017 and default switches (/MD), and therefore the resulting application requires Microsoft Redistributable C++ libraries for Visual Studio 2017.

If building with /MT is supposed to work, maybe someone could give me a hint how to get it right (and then we can close the issue)? I guess, digging into build options of every third-party library and adding /MT there?

**Comment by mrry** [comment]
If I remember correctly, we're using `/MD` by default in order to generate a DLL that's usable as a Python extension. I vaguely recall being able to build the example trainer program with `/MT` in the exploratory stages of the Windows port, but that was before most of the external dependencies were working.

I believe it should be enough to thread the option through to each of the external projects. Since we only use the CMake build for TensorFlow-on-Windows-using-Python release, it's unlikely that anyone on the team is going to look into this, but we would encourage contributions if this would be useful for you.

/cc @guschmue who might have encountered the same problem.

**Comment by alex-petrenko** [comment]
@mrry Thank you for the reply! Okay, I will look into passing the option to the libraries.
Will post here later how it went.

**Comment by gunan** [comment]
Any updates @alex-petrenko ?

**Comment by alex-petrenko** [comment]
It turns out you actually can do it; just like @mrry said you can pass /MT option to each and every 3rd party library tensorflow depends on. On Windows, all of them are built with CMake, so usually, you just need to add the flag to the CMake options.

In my case, I wanted to build a version with static runtime to simplify the deployment, to eliminate the dependency on the Microsoft C++ Runtime Libraries. However, I faced problems with other libraries that I use (namely, OpenCV) and I ended up just adding vcruntime140.dll (and a couple of other Microsoft dlls) to my distribution. I recommend this solution to anyone facing the same problem: it's easier to implement and is much less error-prone.

If you're building a standalone app for Windows and you have a separate installer, even better is to include the Microsoft C++ Redistributable Package into your installer. I didn't have an installer (because we build a [plugin](https://www.assetstore.unity3d.com/en/#!/content/100613), not a standalone app), so I just added Microsoft .dlls near the tensorflow.dll

**Comment by gunan** [comment]
Thank you very much for the explanation!
Now that we have possible workarounds and we confirmed that we can do this using the cmake build, I will mark this issue closed.

**Comment by DiogoDantas** [comment]
Hi, @alex-petrenko 

I read your instructions, but it is not too clear for me. Could you be more precise about the instructions to build Tensorflow with /MT option, please?

I mean, should I add

```
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")
```

to each **.cmake** file located in tensorflow\contrib\cmake\external or each **.BUILD** file located in third_party folder?

I had already passed flags like ```-DCMAKE_CXX_FLAGS_RELEASE="/MT"``` in my cmake command (they appear in CMakeCache), but when I run build, the libraries continues being built with /MD option.

**Comment by alex-petrenko** [comment]
@DiogoDantas sorry, I don't remember exactly how we did it, as I said, we ended up using a different solution which I recommend. But I think you should add this option to every *.cmake file in tensorflow\contrib\cmake\external 

All these dependencies are basically separate CMake projects, so you can just pass this option to every one of them. Some of them will have problems of their own handling the MT build.

As an example, you can take a look at the ExternalProject_Add command in protobuf.cmake file. It has both command line and CMakeCache arguments, I think at least one of the options should work. Feel free to post more detailed instructions if you manage to use this in production.

**Comment by arnaldog12** [comment]
For those who are interested, I wrote a [post on Medium](https://medium.com/@arnaldog12/how-to-build-tensorflow-on-windows-with-mt-42a8e4bea7e7) and created a [Github Repo](https://github.com/arnaldog12/Tensorflow-Build-MT) with detailed instruction about how to achieve this.

I hope it helps!

**Comment by jetjodh** [comment]
@arnaldog12 Will this repo work with tf v1.14?

**Comment by arnaldog12** [comment]
Hi, @jetjodh 
Sorry for the late response. I tried it with the version you mentioned (v1.14) and I had problems with some operations not defined by v1.4. However, I tested with version v1.13 and everything went fine.

If you really need to run it on v1.14, I can help you build it. If you have already done it, please let me know.

**Comment by jetjodh** [comment]
@arnaldog12 I found that c# was much better suited for my use case, so I used that instead. There are many bindings for TensorFlow in C# which surprisingly worked better than ones in C++.

**Comment by arnaldog12** [comment]
@jetjodh Nice! Can you please share the tutorials you followed our even your TensorFlow build for C# to help others as well? Thanks in advance.
