### ISSUE TITLE
label image run slower and slower?

### ISSUE THREAD

**Issue by aureosun** [tensorflow/tensorflow#13141]
Hello ,Everyone
Is there anybody who had ever run the code label_image.py in tensorflow/tensorflow/examples/label_image/label_image.py
I have modify it to run on a dataset and read and calssify image one by one,and as the number of images goes,the speed is slower and slower,at first,that's about ten images per second,and when the number of image goes to 1000,the time is about 7s,Incredibly!and  I find the problem is in the function  read_tensor_from_image_file in label_image.py and this part is read and preprocess images, so what's the matter?and I want to know how to speed up?and how to modify the code so as to making it run for batches ?

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by aureosun** [comment]
@shivaniag I guess it's a bug about memorry leak,Please make sure!

**Comment by nanshihui** [comment]
i got the same problem .when predit image more and more. the memory will leak
