### ISSUE TITLE
Error for slim dataset using fixed length reader

### ISSUE THREAD

**Issue by ybsave** [tensorflow/tensorflow#13157]
I want to use tensorflow slim data provider. All examples I can find only are only reading tfrecord files. However, I want to read binary files directly by my own reader. I use fixed length reader to extract Cifar10 binary data. 

However, "dataBytes = tf.decode_raw(data, tf.unit8)" always produce error that "AttributeError: module 'tensorflow' has no attribute 'unit8'" when using in slim DatasetDataProvider. 

But no such error occurs when I use the reader directly without using DatasetDataProvider. Did I not use it correctly or does DatasetDataProvider only support tfrecord readers? Thank you.

My codes are as below:  	

	CIFAR_LABEL_BYTE = 1
	CIFAR_HEIGHT = 32
	CIFAR_WIDTH = 32
	CIFAR_DEPTH = 3
	CIFAR_RECORD_BYTE = CIFAR_HEIGHT * CIFAR_WIDTH * CIFAR_DEPTH + CIFAR_LABEL_BYTE

	CIFAR_CLASS_NUM = 10
	CIFAR_TRAINING_NUM = 50000
	CIFAR_TEST_NUM = 10000

	_ITEMS_TO_DESCRIPTIONS = {
		'image': 'A [32 x 32 x 3] color image.',
		'label': 'A single integer between 0 and 9',
	}

    class CifarBinaryDecoder(DataDecoder):
	  def decode(self, data, items):
		outputs = []
		dataBytes = tf.decode_raw(data, tf.unit8)   #this is where the error occurs!
		for item in items:
		  if item == 'label':
			currLabel = tf.cast(tf.strided_slice(dataBytes, [0], CIFAR_LABEL_BYTE), tf.int32)
			outputs.append(currLabel)
		  if item == 'image':
			imageData = tf.reshpae(tf.strided_slice(dataBytes, [CIFAR_LABEL_BYTE],[CIFAR_RECORD_BYTE]), [CIFAR_DEPTH, CIFAR_HEIGHT, CIFAR_WIDTH])
			imageData = tf.transpose(imageData, [1, 2, 0])
			outputs.append(imageData)

		return outputs

	  def list_items(slef):
		return ['label', 'image']

	def get_cifar_training_dataset(binary_data_dir):
	  file_pattern = get_cifar10_training_filenames(binary_data_dir)
	  decoder = CifarBinaryDecoder()
	  labels_to_names = get_cifar_labels_to_names(binary_data_dir)
	  return slim.dataset.Dataset(data_sources = file_pattern,
								  reader = tf.FixedLengthRecordReader,
								  decoder = decoder,
								  num_samples = CIFAR_TRAINING_NUM,
								  items_to_descriptions = _ITEMS_TO_DESCRIPTIONS,
								  num_classes = CIFAR_CLASS_NUM)

	def main(_):  
	  dataset = get_cifar_training_dataset(FLAGS.cifar_data_dir)
	  print(dataset.data_sources)
	  provider = slim.dataset_data_provider.DatasetDataProvider(
		  dataset,
		  num_readers = 1,
		  common_queue_capacity = 1000,
		  common_queue_min = 500,
		  reader_kwargs={'record_bytes' : CIFAR_RECORD_BYTE})

	  [image, label] = provider.get(['image', 'label'])

	  with tf.Session() as sess:
		sess.run([image, label])
		sess.run(print('lalala'))

**Comment by mrry** [comment]
Looks like a typo: `tf.unit8` should be `tf.uint8`.

**Comment by ybsave** [comment]
@mrry Sorry for my mistake. I have corrected the typo, but it seems that the reader still does not work. I have added a line at the beginning of function decode as print(data.shape). Please see my modified codes in the original post.

It shows "unknown" in the output. The error message is "tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 1 but is rank 0 for 'StridedSlice' (op: 'StridedSlice') with input shapes: ?, [1], [], [1].".

Therefore, I guess the reader still doesn't work. I have double confirmed the file path & name, and I also tried to move the data file to the same folder as the code file. But it still doesn't work. Do I still have some more errors in my codes? Thank you.

**Comment by mrry** [comment]
Without the stack trace, it's difficult to say for certain. However, I suspect the problem is in one or both of the two calls to `tf.strided_slice()` in `CifarBinaryDecoder.decode()`.

**Comment by ybsave** [comment]
I finally find out. The original codes "currLabel = tf.cast(tf.strided_slice(dataBytes, [0], CIFAR_LABEL_BYTE), tf.int32)", should be currLabel = tf.cast(tf.strided_slice(dataBytes, [0], [CIFAR_LABEL_BYTE]), tf.int32).

It is another typo again! Sorry for the confusion, and thank you for your help.
