### ISSUE TITLE
Fail to build android example

### ISSUE THREAD

**Issue by AleksandrKrasnoperov** [tensorflow/tensorflow#13162]
Hi. I have the same problem - https://github.com/tensorflow/tensorflow/issues/11474

**System information**
bazel version:
Build label: 0.5.4-homebrew

java version: "1.8.0_144"

android/sdk/platforms/android-26
android/sdk/system-images/android-26
android-ndk-r14b

**workspace config:**
android_sdk_repository(
    name = "androidsdk",
    api_level = 26,
    build_tools_version = "26.0.1",
    path = "/Users/akrasnoperov/Library/Android/sdk",
)

android_ndk_repository(
    name="androidndk",
    path="/Users/akrasnoperov/Library/Android/android-ndk-r14b",
    api_level=14)

**Describe the problem**
Error when I run "bazel build -c opt //tensorflow/examples/android:tensorflow_demo"

**Source code / logs**
bazel build -c opt //tensorflow/examples/android:tensorflow_demo
ERROR: /private/var/tmp/_bazel_akrasnoperov/8a0891b65f3fddb9d9a6d9e66927aea5/external/androidsdk/BUILD.bazel:64:1: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_akrasnoperov/8a0891b65f3fddb9d9a6d9e66927aea5/external/androidsdk/BUILD.bazel", line 64
		create_system_images_filegroups(system_image_dirs = ["system-ima..."])
	File "/private/var/tmp/_bazel_akrasnoperov/8a0891b65f3fddb9d9a6d9e66927aea5/external/bazel_tools/tools/android/android_sdk_repository_template.bzl", line 298, in create_system_images_filegroups
		int(apidir.split("-")[1])
invalid literal for int() with base 10: "MNC".
ERROR: /private/var/tmp/_bazel_akrasnoperov/8a0891b65f3fddb9d9a6d9e66927aea5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:build-tools/26.0.1/lib/dx.jar' contains an error and its package is in error and referenced by '@androidsdk//:dx_jar'.
ERROR: /private/var/tmp/_bazel_akrasnoperov/8a0891b65f3fddb9d9a6d9e66927aea5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:dx_jar' contains an error and its package is in error and referenced by '@androidsdk//:dx_jar_import'.
ERROR: /Users/akrasnoperov/Developer/Repo/tensorflow/WORKSPACE:20:1: Target '@androidsdk//:dx_jar_import' contains an error and its package is in error and referenced by '//external:android/dx_jar_import'.
ERROR: Analysis of target '//tensorflow/examples/android:tensorflow_demo' failed; build aborted.
INFO: Elapsed time: 0,463s

**Comment by andrewharp** [comment]
@AleksandrKrasnoperov I don't have anything more to add on my comment in #11474, which was:

It seems the directory parsing is somehow getting confused and splitting -MNC out of one of the sdk/.../android-MNC/ dirs rather than the appropriate API level. Do you have the indicated APIs from your WORKSPACE file installed? You can check via sdk/tools/android.

Otherwise this might be an issue better asked over at  https://github.com/bazelbuild/bazel as this seems more like a Bazel configuration issue than a TF issue.

**Comment by AleksandrKrasnoperov** [comment]
I used new release - https://github.com/bazelbuild/bazel/releases/tag/0.6.1
Now it works
