### ISSUE TITLE
send/recv operators bug in constructing the graph.

### ISSUE THREAD

**Issue by dzhwinter** [tensorflow/tensorflow#13172]
Running the following snippet several times shows some weird operator in the graph.
```python
import tensorflow as tf

with tf.device("/gpu:0"):
    x = tf.constant(1.0)

graph_def = tf.get_default_graph().as_graph_def()
options = tf.RunOptions(output_partition_graphs=True)
metadata = tf.RunMetadata()
config = tf.ConfigProto(device_count={"CPU": 8},
                        inter_op_parallelism_threads=1,
                        intra_op_parallelism_threads=1)
sess = tf.Session(config=config)
sess.run(x, options=options, run_metadata=metadata)
for partition_graph_def in metadata.partition_graphs:
   print "\n" * 5
   print partition_graph_def
```
in the cpu part of graph, it shows
```text
node {
  name: "Const/_1"
  op: "_Recv"
  device: "/job:localhost/replica:0/task:0/cpu:0"
  attr {
    key: "client_terminated"
    value {
      b: false
    }
  }
  attr {
    key: "recv_device"
    value {
      s: "/job:localhost/replica:0/task:0/cpu:0"
    }
  }
  attr {
    key: "send_device"
    value {
      s: "/job:localhost/replica:0/task:0/gpu:0"
    }
  }
  attr {
    key: "send_device_incarnation"
    value {
      i: 1
    }
  }
  attr {
    key: "tensor_name"
    value {
      s: "edge_5_Const"
    }
  }
  attr {
    key: "tensor_type"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "_send_Const_0"
  op: "_Send"
  input: "Const/_1"
  device: "/job:localhost/replica:0/task:0/cpu:0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "client_terminated"
    value {
      b: true
    }
  }
  attr {
    key: "recv_device"
    value {
      s: "/job:localhost/replica:0/task:0/cpu:0"
    }
  }
  attr {
    key: "send_device"
    value {
      s: "/job:localhost/replica:0/task:0/cpu:0"
    }
  }
  attr {
    key: "send_device_incarnation"
    value {
      i: -3155862594799619836
    }
  }
  attr {
    key: "tensor_name"
    value {
      s: "Const:0"
    }
  }
}
versions {
  producer: 21
}
```
There is a weird operator in it. ` name: "_send_Const_0"` just send tensor from cpu0 to cpu0. This device already has the right result of `Add` operator.
And I notice the `send_device_incarnation` is a random number, which generates by [New64](https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/core/common_runtime/device.cc#L43). 

The whole log of this snippet available in https://gist.github.com/dzhwinter/3c2257351774260382dd3e130aaa072b. Thanks.

**Comment by yaroslavvb** [comment]
Not sure if this is a bug. Optimizers can do things behind the covers, extra send/recv ops are only a problem if they cause a significant performance penalty.

This copy could represent a copy of 1.0 from Python runtime to TensorFlow runtime. Also, constants have special optimizations, you get more pure look at underlying processes by using dynamic values (ie, tf.placeholder) and disabling optimizations with `config = tf.ConfigProto(graph_options=tf.GraphOptions(optimizer_options=tf.OptimizerOptions(opt_level=tf.OptimizerOptions.L0))`

**Comment by mrry** [comment]
This is not a bug. TensorFlow adds one op per tensor that you fetch (and one per tensor that you feed) in order to transfer the data to/from the client. Notice that the op has `"client_terminated": true` in its definition, which means that the value will be consumed by the client.

Note that in versions of TensorFlow since 858e0afcc45c39b6428bf82ab1444323e925cfd8 (i.e. 1.2 onwards) this is actually implemented using the `"_Retval"` (and `"_Arg"` for feeding) ops, which are a little more self-explanatory.
