### ISSUE TITLE
variable assign incorrect

### ISSUE THREAD

**Issue by wqkx** [tensorflow/tensorflow#13174]
**When the two assignment operations are the same:**
var = tf.Variable(1)
assign_1 = var.assign(tf.multiply(var, 2))
assign_2 = var.assign(tf.multiply(var, 2))

with tf.Session() as sess:
    sess.run(var.initializer)
    sess.run([assign_1, assign_2])
    print(sess.run(var))  # >>  2

**When the two assignment operations are not the same:**
var = tf.Variable(1)
assign_1 = var.assign(tf.multiply(var, 2))
assign_2 = var.assign(tf.multiply(var, 3))

with tf.Session() as sess:
    sess.run(var.initializer)
    sess.run([assign_1, assign_2])
    print(sess.run(var))  # >>  6

**Comment by yaroslavvb** [comment]
This is better question for stackoverflow. (you are missing some control dependencies to make sure assign_2 looks at the updated value of var)

**Comment by facaiy** [comment]
```python
# coding: utf-8
import tensorflow as tf

var = tf.Variable(1)
assign_1 = var.assign(tf.multiply(var, 2))

with tf.control_dependencies([assign_1]):
    assign_2 = var.assign(tf.multiply(var, 2))

with tf.Session() as sess:
    sess.run(var.initializer)
    sess.run([assign_2])
    print(sess.run(var))        # = 4
```
