### ISSUE TITLE
Lua API

### ISSUE THREAD

**Issue by ner0x652** [tensorflow/tensorflow#1318]
Hi!

Is somebody working on a Lua API? 
If not, are you interested on contributing to develop a Lua API?

Thanks!

**Comment by girving** [comment]
We wouldn't be able to actively support it, so a Lua layer would be best as a separate repo.  If you want to work on it, there is some discussion on https://github.com/tensorflow/tensorflow/issues/388 that may be relevant.

**Comment by asimshankar** [comment]
If anyone does choose to embark on this, please do try to build off [c_api.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h) using the approach outlined in the [how-to](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/language_bindings/index.md)

**Comment by mhyttsten** [comment]
Closing due to lack of recent activity. If there are any contributors interested in writing and maintaining this support then please reopen the issue. Thanks!

**Comment by saru95** [comment]
@asimshankar Could you re-link the `how-to` page?

**Comment by asimshankar** [comment]
Updated the link in the previous comment. For the record, it's: https://www.tensorflow.org/extend/language_bindings
