### ISSUE TITLE
"Controlling Dreams" in TensorFlow

### ISSUE THREAD

**Issue by leimao** [tensorflow/tensorflow#13183]
Hi guys,

I am trying to re-implement "controlling dreams" using TensorFlow which was implemented in the original google deepdreams algorithm using Caffe (see the last part of https://github.com/google/deepdream/blob/master/dream.ipynb). But I think I got problems. This "controlling dreams" part does not exist in this tutorial. I am looking for someone, who knows Caffe and deepdream, to help.

I have never used Caffe before, but I tried to understand what they were doing in the script. To "control the dream", they firstly input a small guide image (roughly 240 x 240) into the neural network, and extract the features in each channel in certain layer specified. These features are called "guide features". Then they input the large image, which they want to modify, into the model. The large image was "octaved". For each octave image, they input the octave image into the neural network, extract the features in each channel in the same layer specified to the guide image. Then they have to find the best matching guide features of certain channel to each of the features in the layer of octave image. Here "the best matching" means the dot product of the two feature vectors is the largest.

Here comes the question. They extract the guide features beforehand. Therefore the matrix shape of "guide features" is constant. But the shape of the feature matrix in octave can vary. This means that I may not be able to calculate the dot product of these two matrices. I believe I did not understand correctly their algorithm. I would like to have someone to explain to me or provide me a reference. Thank you.

Best,

Lei

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
