### ISSUE TITLE
how to avoid the flag --whole-archive when using the static library in windows

### ISSUE THREAD

**Issue by helen-medina** [tensorflow/tensorflow#13180]
Hi everyone,

I have built the static library of tensorflow for C++ in windows. And I am trying to use this library in qtCreator, however I have the issue (no session factory registered for the given options). But, it looks adding these flags in qtCreator doesn´t work so I still have the issue. Does someone know how to build the library in Tensorflow  so I can use the library without the flag -whole-archive?

**Comment by yaroslavvb** [comment]
See https://github.com/tensorflow/tensorflow/issues/4242 for explanation why you need whole-archive flag for TensorFlow

**Comment by helen-medina** [comment]
Hi yaroslavvb,

I have already check it that entry, but the issue I have is the flag /wholearchive doesn't work in qt. I am compiling my project with the compiler Microsoft visual 14 in Qt, however It seems there is a problem with Qt and it ignores the flag, so I still have the error "not session found ...". You can see below the discussion about this issue in Qt.

https://forum.qt.io/topic/83457/build-settings-for-the-compiler/11

Could you tell me please if I still need this flag if I build the tensorflow library with bazel in Windows? 
Could you give me some advise please?

Your help is very much appreciated.

**Comment by yaroslavvb** [comment]
I would expect this flag to be always needed. Default behavior of linkers is to strip out unused symbols, so this flag is what tells the linker to not do this

**Comment by hemecha** [comment]
It makes sense, but do you know if this flag is still needed if I build the .dll instead of the static library?

**Comment by yaroslavvb** [comment]
cc @allenlavoie who's been doing some restructuring of TensorFlow linking options

**Comment by hemecha** [comment]
Thanks for the information.

Kind regards.

**Comment by hemecha** [comment]
Hi yaroslavvb,

I have been able to build the tensorflow .dll  and it looks like the flag /wholearchive with the dinamic library is not needed.  
My project is working only linking with the following dependencies:
 libprotobuf.lib and tensorflow.lib. 

Thank you very much for your help, it has been very useful.

Kind regards.

**Comment by yaroslavvb** [comment]
OK, I guess it makes sense, dynamic linkers don't strip out symbols by default, as opposed to static linkers, since they don't know which symbols are needed
