### ISSUE TITLE
Renaming checkpoint directory

### ISSUE THREAD

**Issue by Rick-C-137** [tensorflow/tensorflow#13186]
If you want to rename a checkpoint directory, you currently need to also do a find-replace in the 'checkpoint' file. It might be nice to have that handled automatically.

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
