### ISSUE TITLE
TF Record Reader/Writer C API

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/tensorflow#13204]
@asimshankar Would you be open to adding support for reading/writing TF records using the C API? Similar to the `lib/io` stuff in the Python API.

**Comment by yaroslavvb** [comment]
sorry for drive-by comment -- providing readers lib/io in C_API feels a little weird -- the API comprises methods for managing computational graph. Parsing TF records is a form of computation, so it can be handled within computational graph as tf.TFRecordReader ops rather than a new method

For some reasons (performance?) people also added standalone utilities that can TF-related things without using TF runtime -- the record readers, and checkpoint readers. The lib/io seems to be one of those "standalone" utils

**Comment by eaplatanios** [comment]
Thanks for the comment! I think I agree for the most part. My concern though is that there is certain utilities that should be provided by the native library. For example, right now if I want to implement a "summary_writer" I would have to implement a writer for the right format and make sure it's compatible with tensorflow. And every other API, for other languages, should do the same. So, given that there is this agreed upon file format, doesn't it makes sense to provide utilities for working with it for other languages? And given that these utilities exist, maybe we could create a separate library (not part our C API), providing an interface for those utilities. What do you think? And please, let me know if there is currently another way to create a summary writer using the c api.

**Comment by eaplatanios** [comment]
Closing this since I ended up writing code for the file writers on the Scala side. I still believe though that it would be nice to have that code shared by all languages, given that the file format is fixed.

**Comment by yaroslavvb** [comment]
cc: @josh11b -- do you think there should be language-agnostic API for checkpoint readers/file readers? Right now record_reader seems to be Python-only -- https://github.com/tensorflow/tensorflow/tree/2b374f7d4ba578764e2b2e9f21da9ba52811a103/tensorflow/python/lib/io

**Comment by eaplatanios** [comment]
@yaroslavvb For checkpoint readers, there is already a simple C API [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/checkpoint_reader.h), which is not exposed. I think that exposing it (potentially along with summary reader/writer support), would not be a bad idea. I wrote readers/writers for summary files, but it's tedious and not sustainable (if something changes on the TensorFlow side, I will need to also change my code to imitate those changes, if I want my summaries to stay compatible with TensorBoard, etc.). And the same applies for checkpoint files, even though I haven't written a reader yet.

For checkpoint files it's actually interesting to see how the change from V1 to V2 required some not-so-nice changes to the checkpoint reader code. It would be good to not have to replicate those.
