### ISSUE TITLE
[feature request] set some dimension in row_shape to the maximum in each batch in tf.contrib.data.Dataset.dense_to_sparse_batch

### ISSUE THREAD

**Issue by arturml** [tensorflow/tensorflow#13216]
The docstring says:

**row_shape:** A `tf.TensorShape` or `tf.int64` vector tensor-like
    object representing the equivalent dense shape of a row in the
    resulting `tf.SparseTensor`. Each element of this dataset must
    have the same rank as `row_shape`, and must have size less
    than or equal to `row_shape` in each dimension.

The row_shape must be the same for every batch, so if the elements are sequences it's necessary to know the maximum length beforehand. It would be nice if it was possible to set some dimension of row_shape to -1, meaning that this dimension will be the maximum for each batch (just like padded_batch).

**Comment by mrry** [comment]
Sounds reasonable to me! This would make a great first contribution to the Dataset API, so I'm going to mark this as contributions welcome.

**Comment by facaiy** [comment]
Hi, @mrry. I'm interested in the issue. Do you have any advice for me?

**Comment by mrry** [comment]
Sure, have a look at how the equivalent feature is [implemented in `PaddedBatchDatasetOp`](https://github.com/tensorflow/tensorflow/blob/a6f856b2f7920d4f74d7ca4e71967258423cc9f0/tensorflow/core/kernels/padded_batch_dataset_op.cc#L308). It should be pretty easy to translate this to where the `row_shape` is [calculated in `DenseToSparseBatchDatasetOp`](https://github.com/tensorflow/tensorflow/blob/a6f856b2f7920d4f74d7ca4e71967258423cc9f0/tensorflow/core/kernels/dense_to_sparse_batch_dataset_op.cc#L222). Most of the work would be in adding appropriate tests!

**Comment by facaiy** [comment]
Thanks for you detailed guide, @mrry. I will take a try, and let you know if I get in trouble.

**Comment by DjangoPeng** [comment]
@mrry It seems like the feature has been merged. I think we'd better close the issue, right?

**Comment by DjangoPeng** [comment]
@facaiy What is the process of the PR now? Do you need help to pass all tests?

**Comment by mrry** [comment]
It's merged now and should be available in TF 1.4.
