### ISSUE TITLE
commit 5c7f9e3 breaks windows bazel build

### ISSUE THREAD

**Issue by snnn** [tensorflow/tensorflow#13227]
commit 5c7f9e316d8c7735308a217310350d416d7498cc in #13224 breaks windows bazel build

First, _rpath_linkopts() in tensorflow/tensorflow.bzl should not add rpath args to link.exe
Second,  the link command generated from bazel is incorrect, 

link.exe /nologo /OUT:bazel-out/host/bin/tensorflow/python/gen_set_ops_py_wrappers_cc.exe -Lbazel-out/host/bin/_solib_x64_windows/_U_S_Stensorflow_Spython_Cgen_Uset_Uops_Upy_Uwrappers_Ucc___Utensorflow **tensorflow_framework** /SUBSYSTEM:CONSOLE -pthread /MACHINE:X64 @bazel-out/host/bin/tensorflow/python/gen_set_ops_py_wrappers_cc.exe-2.params /DEFAULTLIB:msvcrt.lib

The addDynamicInputLinkOptions function in src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkActionBuilder.java doesn't support Windows.

**Comment by allenlavoie** [comment]
Will investigate, and possibly file a Bazel bug. In the meantime you should be able to use --config=monolithic to work around the issue.

**Comment by allenlavoie** [comment]
Actually it sounds like @meteorcloudy is aware of the issue and working on Windows dynamic linking. Sorry you ran into this!

**Comment by gunan** [comment]
I believe this was fixed. I think the build still fails, but due to a different issue now.
Closing.
