### ISSUE TITLE
Is there any tool to see the tensorflow net's topology?

### ISSUE THREAD

**Issue by hhuangfh** [tensorflow/tensorflow#13225]
As you known, we could use "http://ethereon.github.io/netscope/quickstart.html" to catch sight of the caffe network's  topology structure. Is there any one for tensorflow?

**Comment by mrry** [comment]
[TensorBoard](https://github.com/tensorflow/tensorboard) includes a graph visualizer, documented [here](https://www.tensorflow.org/get_started/graph_viz), with more details including a paper about it [here](http://idl.cs.washington.edu/papers/tfgraph/).
