### ISSUE TITLE
Leaky ReLU as part of tf.nn

### ISSUE THREAD

**Issue by sfikas** [tensorflow/tensorflow#13233]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Ν/Α
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: bazel release 0.5.4
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: GeForce 940MX, 4Gb
- **Exact command to reproduce**: N/A

### Describe the problem

A leaky relu function could be part of the standard tensorflow package, under tf.nn. or some other non-contrib module. It could be something like

```
tf.maximum(x, alpha * x)
```

Custom leaky relus, which is what people do now, may be largely non-efficient. See for example the discussion in https://stackoverflow.com/q/45307072/5615276 .

**Comment by yaroslavvb** [comment]
Efficiency issue could potentially be fixed by enabling XLA to fuse this pattern into a single op. That's better for maintainability than adding yet another native op (743 in the latest [count](https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/core/ops/ops.pbtxt))

/cc @hawkinsp in case he knows if that's close to being reality

**Comment by ebrevdo** [comment]
I think it's worth adding a leaky_relu to tf.contrib.nn for now. Using tf.maximum is fine.

**Comment by rryan** [comment]
I think this was added after r1.3, it's the `max(alpha * features, features)` variant.

https://www.tensorflow.org/versions/master/api_docs/python/tf/nn/leaky_relu
https://github.com/tensorflow/tensorflow/commit/7a8c63da365106048dc96affddb39e2fdc33da89#diff-7e066e8d1b9eff5c683b33517b35ae13

**Comment by sfikas** [comment]
@rryan Indeed, it is a very recent commit. Thanks!
