### ISSUE TITLE
the version of tensorflow on TensorFlow-experiment in iOS

### ISSUE THREAD

**Issue by xiaocui0803** [tensorflow/tensorflow#13234]
i get tensorflow from cocoapods, and the func TF_Version() in "c_api.h" can not run.
i want to get the version of tensorflow in "tensorflow-experiment",how can i know?

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
