### ISSUE TITLE
Makefile build symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by WellDone2094** [tensorflow/tensorflow#13231]
I'm trying to build tensorflow on a Mac OSx Sierra to be able to use it in a C++ project but when i compile it it gives me this error:
[https://pastebin.com/6K8qBNUF](https://pastebin.com/6K8qBNUF)

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
