### ISSUE TITLE
TensorFlow Debugger Colors Are Unreadable on Windows

### ISSUE THREAD

**Issue by johnsrude** [tensorflow/tensorflow#13238]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 7
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version 1.3.0**:
- **TensorFlow version (use command below)**: Python 3.5.2
- **Bazel version (if compiling from source)**: not applicable
- **CUDA/cuDNN version**: not applicable
- **GPU model and memory**: not applicable
- **Exact command to reproduce**:  https://www.tensorflow.org/versions/r1.1/programmers_guide/debugger

### Describe the problem
When I run the TensorFlow Debugger (tfdbg) on a Windows command prompt the colors on the tfdbg screen are practically unreadable on my monitor.   Screen capture in the comment below. The text color is indigo and the background color is black.

I have tried changing the colors on my command prompt but the curses package on tfdbg is changing both the foreground and the background colors on the blue text so that text remains unreadable.
 
Please change tfdbg so that default palette is readable on all monitors and so that colors can be modified.

### Source code / logs

Screen capture below.

**Comment by johnsrude** [comment]
![snip_20170922100000](https://user-images.githubusercontent.com/15482785/30756905-57a485d8-9f81-11e7-979d-9509270d97ea.png)

**Comment by yaroslavvb** [comment]
cc @caisq

**Comment by caisq** [comment]
@johnsrude, tfdbg also has a readline ui_type, which can be activated with something like

```python
sess = tf_debug.LocalCLIDebugWrapperSession(sess, ui_type="readline")
```

Would that suite your use case? Or do you still prefer to use the curses ui_type on Windows, which AFAIK not many users are using?

**Comment by johnsrude** [comment]
Tried `sess = debug.LocalCLIDebugWrapperSession(sess, ui_type="readline")` and got same result.

**Comment by caisq** [comment]
Ah, that's because the debugger will fall back to an available ui_type if it can't find the ui_type specified by the user. My guess is that you don't have pyrealine installed on your Windows. You can install it with something like:

```
"C:\Program Files\Anaconda3\Scripts\pip.exe" install pyreadline.
```

**Comment by johnsrude** [comment]
Problem is I can't use pip (pip3) because machine is offline (long story) . I have compiled pyreadline on my machine.  Where do I need to place it so that tfdbg will find it?

**Comment by caisq** [comment]
The dist_packages or site_packages folder of the python interpreter that you are using for tensorflow?

**Comment by johnsrude** [comment]
Got it.  Ran `python3 setup.py install` in pyreadline directory and all's good.
