### ISSUE TITLE
BasicLSTMCell cannot calculate output shape correctly when batchsize is 1

### ISSUE THREAD

**Issue by ronghanghu** [tensorflow/tensorflow#1323]
I found that `BasicLSTMCell` cannot infer output shape correctly when the input batchsize is 1, after my graph construction failed within this case.

Tensorflow version: 0.7.1, installed with pip. Operating system: Ubuntu 14.04

Minimum code snip to reproduce:
```
import tensorflow as tf

batchsize = 1
# batchsize = 2
D_in, D_out = 1000, 2000

input_ = tf.zeros([batchsize, D_in], tf.float32)
lstm_cell = tf.nn.rnn_cell.BasicLSTMCell(D_out)
state = lstm_cell.zero_state(batchsize, tf.float32)

output, _ = lstm_cell(input_, state)
print(output.get_shape().as_list())
```

When `batchsize = 2`, the shape of output is `[2, 2000]`, with the first dimension equal to batchsize. However, when `batchsize = 1`, the shape of output is `[None, 2000]` instead of `[1, 2000]`.

I'm not sure why the output shape is not correctly inferred as `[1, 2000]` when `batchsize = 1`. Could someone please have a look?

**Comment by lukaszkaiser** [comment]
Just to clarify: the code works, it's just that shape inference does not infer the batch size, right?

I think it's harder to infer sizes of 1 because they have different behaviour in terms of broadcasting. Assigning to Derek who know the shape inference code much better.

**Comment by mrry** [comment]
Yes, this seems to happen because, internally, we compute `tf.mul(x, y)` where `x` has shape `[None, 2000]` and `y` has shape `[batch_size, 1000]`. If `batch_size` is 1, then it can't tell whether `None` is actually `1` (i.e. there's no broadcasting), or a number greater than `1` (i.e. broadcasting happens).

The typical way to deal with issues like this - when shape inference is hard to do - is to have the higher-level library function (e.g. `BasicLSTMCell()`) call `Tensor.set_shape()` with the statically known shape.

**Comment by ronghanghu** [comment]
@lukaszkaiser Yes, it's just that shape inference does not infer the batch size. The code works after I explicitly set the shape.

Thanks for your fast response!

**Comment by lukaszkaiser** [comment]
I was thinking about this, and I'd like to know more about your use-case. While we could add the extra shape inference code to BasicLSTMCell, the question arises where else should we do it. In every LSTM cell? In every layer in contrib, in every layer we write anywhere? I mean -- that's the reason we have automatic shape inference, so we don't write (and maintain) this code at every point.

The above is the reason why I'm hesitating to add extra shape code, and is did not seem to be needed until this point. But of course we need to make your code work, so it would be good to see if it's just BasicLSTMCell or more places or an instance of a more general problem. Could you share more about your code and how the lack of the shape on batch dimension hurts you?

**Comment by girving** [comment]
@lukaszkaiser: Closing for now since the original issue is not fixable given broadcasting.
