### ISSUE TITLE
GLIBC error

### ISSUE THREAD

**Issue by omid55** [tensorflow/tensorflow#1324]
I searched for this issue but did not find any useful way. I installed tensorflow with pip and I am using Ubuntu 12.04 and python 2.7.3.
When in python I write import tensorflow, it raises the following error:

ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so)

Any useful suggestion?
Thanks

**Comment by liumilan** [comment]
Have you solve this issue finaly?

**Comment by omid55** [comment]
Yes. Tensor flow has a problem with Ubuntu 12. I installed Ubuntu 14.04 and that worked like a charm.
