### ISSUE TITLE
Compilation error since today morning with cudnn 5.1.10

### ISSUE THREAD

**Issue by abhishek-neurala** [tensorflow/tensorflow#13249]
------------------------

### System information
Memory : 16GB
Processor: Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8 
GPU: GeForce GTX 1060/PCIe/SSE2
OS Type- 64 bit

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.3
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.5.4
- **CUDA/cuDNN version**: CUDA 8.0 CUDNN 5.1.10
- **GPU model and memory**: GTX 1060 (6GB)
- **Exact command to reproduce**: bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
Since today morning, I've been getting this error in compiling TF with cudnn 5.1.10 where it seems to be looking for a v6 file even though I've configured it to use 5.1.10. I do not see the same error when building with cudnn6.0.  I compiled it last night with the same exact configuration and it was compiling fine. I've even wiped my system clean and reinstalled the whole environment to make sure there weren't any corrupted libraries. But the error still persists.

### Source code / logs
ERROR: /tensorflow/tensorflow/stream_executor/BUILD:52:1: C++ compilation of rule '//tensorflow/stream_executor:cuda_platform' failed (Exit 1).
tensorflow/stream_executor/cuda/cuda_dnn.cc: In member function 'cudnnStatus_t perftools::gputools::cuda::wrap::WrapperShim__cudnnSetRNNDescriptor_v6::operator()(perftools::gputools::cuda::CUDAExecutor*, Args ...)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:140:30: error: '::cudnnSetRNNDescriptor_v6' has not been declared
       cudnnStatus_t retval = ::__name(args...);                    \
                              ^
tensorflow/stream_executor/cuda/cuda_dnn.cc:235:3: note: in expansion of macro 'PERFTOOLS_GPUTOOLS_CUDNN_WRAP'
   __macro(cudnnSetRNNDescriptor_v6)                           \
   ^
tensorflow/stream_executor/cuda/cuda_dnn.cc:240:1: note: in expansion of macro 'CUDNN_DNN_ROUTINE_EACH_R5'
 CUDNN_DNN_ROUTINE_EACH_R5(PERFTOOLS_GPUTOOLS_CUDNN_WRAP)
 ^
tensorflow/stream_executor/cuda/cuda_dnn.cc: In function 'int perftools::gputools::cuda::{anonymous}::CudnnDataTypeToByteSize(cudnnDataType_t)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:902:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_dnn.cc: In member function 'int perftools::gputools::cuda::CudnnRnnParamsDescriptor::GetRegionCountPerLayer() const':
tensorflow/stream_executor/cuda/cuda_dnn.cc:1255:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_dnn.cc: In function 'cudnnRNNInputMode_t perftools::gputools::cuda::{anonymous}::ToCudnnRnnInputMode(perftools::gputools::dnn::RnnInputMode)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:865:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_dnn.cc: In function 'cudnnDirectionMode_t perftools::gputools::cuda::{anonymous}::ToCudnnRnnDirectionMode(perftools::gputools::dnn::RnnDirectionMode)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:877:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_dnn.cc: In function 'cudnnRNNMode_t perftools::gputools::cuda::{anonymous}::ToCudnnRnnMode(perftools::gputools::dnn::RnnMode)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:889:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_dnn.cc: In function 'cudnnDataType_t perftools::gputools::cuda::{anonymous}::ToCudnnDataType(perftools::gputools::dnn::DataType, perftools::gputools::dnn::DataLayout)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:853:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_dnn.cc: In function 'cudnnConvolutionFwdAlgo_t perftools::gputools::cuda::{anonymous}::ToConvForwardAlgo(perftools::gputools::dnn::AlgorithmDesc)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:297:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_dnn.cc: In function 'cudnnConvolutionBwdDataAlgo_t perftools::gputools::cuda::{anonymous}::ToConvBackwardDataAlgo(perftools::gputools::dnn::AlgorithmDesc)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:320:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_dnn.cc: In function 'cudnnConvolutionBwdFilterAlgo_t perftools::gputools::cuda::{anonymous}::ToConvBackwardFilterAlgo(perftools::gputools::dnn::AlgorithmDesc)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:342:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_dnn.cc: At global scope:
tensorflow/stream_executor/cuda/cuda_dnn.cc:560:13: warning: 'bool perftools::gputools::cuda::TensorOpMathEnabled()' defined but not used [-Wunused-function]
 static bool TensorOpMathEnabled() {
             ^
tensorflow/stream_executor/cuda/cuda_dnn.cc:129:26: warning: 'tensorflow::thread::ThreadPool* perftools::gputools::cuda::wrap::GetCudaThreadpool()' defined but not used [-Wunused-function]
 static port::ThreadPool* GetCudaThreadpool() {
                          ^
tensorflow/stream_executor/cuda/cuda_dnn.cc:2001:20: warning: 'perftools::gputools::dnn::AlgorithmDesc perftools::gputools::cuda::{anonymous}::GetCudnnConvolutionForwardAlgorithm(perftools::gputools::Stream*, perftools::gputools::cuda::CUDAExecutor*, void*, int, const perftools::gputools::dnn::AlgorithmConfig&, bool, const perftools::gputools::cuda::ScopedTensorDescriptor&, const perftools::gputools::cuda::ScopedFilterDescriptor&, const perftools::gputools::cuda::ScopedConvolutionDescriptor&, const perftools::gputools::cuda::ScopedTensorDescriptor&, perftools::gputools::ScratchAllocator*, perftools::gputools::DeviceMemory<unsigned char>*)' defined but not used [-Wunused-function]
 dnn::AlgorithmDesc GetCudnnConvolutionForwardAlgorithm(
                    ^
Target //tensorflow:libtensorflow_all.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 666.701s, Critical Path: 125.43s

**Comment by printdhruv** [comment]
@benbarsdell I am not sure `tf1.3` usability with `cudnn 5.1.10` even if you built it! The `tensorflow 1.3` with GPU support currently require  to have `cuDNN v6 or v6.1`

**Comment by abhishek-neurala** [comment]
@printdhruv that is true as long as you do not install grom sources. The page says so as well if you read further down. You can switch to previous versions by configuring TF to do so while building from sources.

**Comment by abhishek-neurala** [comment]
Also, thanks @benbarsdell for the fix!

**Comment by printdhruv** [comment]
@abhishek-neurala yes,I read that! But,I am not sure how tf 1.3 will be feasible with older cuDNN in terms of features and usability if you try to build it from source!

**Comment by abhishek-neurala** [comment]
I get your point. That'd come down to personal preferences I guess. If you're only using TF and can keep yourself up-to-date with the dependencies, your point is correct. However, if TF is just a small part of a larger codebase which is the case with me, then having backwards compatibility is important since the API changes in the newer versions might cause regression errors and updating the whole codebase to use the new API could become a challenge and might not be feasible. Hope that makes sense.

**Comment by sjdrc** [comment]
I had this same issue following this https://github.com/cjweeks/tensorflow-cmake with CUDA 8.0 and CUDNN 6.0. Applying https://github.com/tensorflow/tensorflow/pull/13255 fixed it.
