### ISSUE TITLE
Links to Object_detection model no longer work

### ISSUE THREAD

**Issue by priya-dwivedi** [tensorflow/tensorflow#13245]
Examples of broken links include

https://github.com/tensorflow/models/blob/master/object_detection/create_pascal_tf_record.py
https://github.com/tensorflow/models/blob/master/object_detection/g3doc/running_pets.md

Thanks!

**Comment by shivaniag** [comment]
Current models in the repository have been moved to the subfolder called 'research' , following are the new links:
https://github.com/tensorflow/models/blob/master/research/object_detection/create_pascal_tf_record.py
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md

Docs have been updated for the same, please point to the doc if you see any broken links there.

Thank you.

**Comment by zout** [comment]
Not on that location anymore either:
https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_pascal_tf_record.py
