### ISSUE TITLE
segfaults in Saver.restore with missing files

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#13256]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: centos 7
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.3.0-rc1-2456-g7abd587 1.4.0-dev20170922
- **Python version**: 3.6

```python
import tensorflow as tf
import os

a = tf.get_variable('W', shape=[1,1,256,60], dtype=tf.float32)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver = tf.train.Saver()
    saver.save(sess, './model')

os.remove('model.data-00000-of-00001')

with tf.Session() as sess:
    saver = tf.train.Saver()
    saver.restore(sess, './model')
```
The above code segfaults in today's nightly build. I expect an exception.

**Comment by printdhruv** [comment]
@ppwwyyxx You are right! It shut down python unexpectedly in windows as well.
I guess this issue is caused due to the changes in `tensorflow\include\tensorflow\core\grappler\grappler_item` file!

**Comment by paige-pruitt** [comment]
I appear having the same issues with a Windows build of tensorflow (installed via pip, version 1.3.0 for Python3.5). I found the problem when porting my scripts from Linux to windows, and I tested the sample code above and got the same result.

**Comment by TanguyMoreau** [comment]
Man ! I happened to rename my FILENAME.data-00000-to-00001 to NEWNAME.data-0000-to-00001 (forgetting one zero), and spend hours trying to find from where the seg fault was coming...

**Comment by ppwwyyxx** [comment]
Fixed already in master.
