### ISSUE TITLE
`params` is Not Used for Canned Estimators Implementations

### ISSUE THREAD

**Issue by terrytangyuan** [tensorflow/tensorflow#13263]
The canned estimators implementations do not seem to pass the `params` to their parent class `Estimator`. For example, `DNNClassifier` puts all the parameters, e.g. `hidden_units`, `optimizer`, etc. inside the `model_fn` and then pass the `model_fn` to the parent class [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/canned/dnn.py#L314). This makes it difficult for reporting or parameter tuning purposes. 

I saw [`params` is an exposed property for `Estimator`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/estimator.py#L188), however, it's mostly empty for canned estimators since it's not used. Is this on purpose?

Thanks!

**Comment by ispirmustafa** [comment]
Yes this is on purpose. There is no semantics on params. for example we cannot assume that each estimators params has a field 'learning_rate' or 'feature_column'. Framework developers depending on estimator should not rely on params.
User needs to control the construction of Estimator to play with hyper parameters.
