### ISSUE TITLE
ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients,

### ISSUE THREAD

**Issue by changiseng** [tensorflow/tensorflow#13260]
I am green in a tensorflow

I do not know where it is wrong

here is a warning

ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables ["", "

here is my code

import tensorflow as tf
import numpy as np
import pandas as pd
import math
from sklearn import tree
from sklearn.cross_validation import train_test_split

COLUMNS = ["CLD_A","DDI","DFS_A","DFS_B","deg1","deg2","y"]

filename="D:/outputs/train.csv"
file = pd.read_csv(filename, skipinitialspace=True,
                       skiprows=0, names=COLUMNS)

n_samples = file[['CLD_A','DDI','DFS_A','DFS_B','deg1','deg2']]
n_samples=n_samples.as_matrix()

n_features= file[['y']]
n_features=n_features.as_matrix()

train_X, test_X, train_y, test_y = train_test_split(n_samples, n_features, 
test_size = 0.8,random_state=0)

x=tf.placeholder(tf.int32,shape=[None, 6]) 
y=tf.placeholder(tf.int32,shape=[None, 1])

l1 = tf.layers.dense(x, 10, tf.nn.relu)          # hidden layer
output = tf.layers.dense(l1, 1) 

loss = tf.losses.mean_squared_error(y, output)
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train_op = optimizer.minimize(loss)
with tf.Session() as sess:
  init=tf.global_variables_initializer()
  sess = tf.Session()
  sess.run(init)
for i in range(1000):
    total_loss = 0
    for i in range(len(train_X)):
        feed={x:train_X,y:train_y}
        sess.run(train_op,feed_dict={x:train_X,y:train_y})
        if i%100==0:
            print(sess.run(loss, feed ={x:train_X,y:train_y}))

**Comment by carlthome** [comment]
Try asking here instead: https://stackoverflow.com/questions/tagged/tensorflow

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
