### ISSUE TITLE
CheckpointSaverHook does not check Graph of Saver

### ISSUE THREAD

**Issue by ngc92** [tensorflow/tensorflow#13265]
The following code will run just fine, but will not save any Variables to checkpoints:
```python
import tensorflow as tf

graph = tf.Graph()
with graph.as_default():
    v = tf.get_variable("test", shape=(100, 100), dtype=tf.float32)

save = tf.train.CheckpointSaverHook("test_dir", 10)
with graph.as_default():
    tf.train.create_global_step()
    a = tf.constant(1)
    with tf.train.MonitoredSession(hooks=[save]) as sess:
        sess.run(a)
```

This is because the `CheckpointSaverHook` does not find an existing Saver, so it creates a new one in its constructor, which is executed with a different default Graph.

**Comment by chrismolli** [comment]
Is it possible to set the graph manually? Got the same problem ...
https://stackoverflow.com/questions/46299112/tensorflow-how-to-setup-a-checkpointsaverhook

**Comment by gnedivad** [comment]
I'm assuming you want to save the variable `test`. The default saver created in the constructor of `CheckpointSaverHook` will execute on the same graph if it's initialized in the same graph scope as your variables.

```python
import tensorflow as tf

graph = tf.Graph()
with graph.as_default():
    v = tf.get_variable("test", shape=(100, 100), dtype=tf.float32)

    save = tf.train.CheckpointSaverHook("test_dir", 10)
    with graph.as_default():
        tf.train.create_global_step()
        a = tf.constant(1)
        with tf.train.MonitoredSession(hooks=[save]) as sess:
            sess.run(a)
```

The above code prints `[('test', [100, 100])]`.

**Comment by gnedivad** [comment]
You need to initialize the `CheckpointSaverHook` in the same scope as your variables.

```python
import tensorflow as tf

graph = tf.Graph()
with graph.as_default():
    v = tf.get_variable("test", shape=(100, 100), dtype=tf.float32)
    save = tf.train.CheckpointSaverHook("test_dir", 10)

with graph.as_default():
    tf.train.create_global_step()
    a = tf.constant(1)
    with tf.train.MonitoredSession(hooks=[save]) as sess:
        sess.run(a)
```

prints `[('test', [100, 100])]`.

**Comment by ngc92** [comment]
Maybe I should have been a bit clearer in my description, but my original issue was not meant as a question on how to fix the presented code (on the user side), but as code that I would have expected to work, but which did not. 
As the Hook has a dedicated `begin` which is called in the correct graph, and supposed to do any  modifications of that graph. So I think it is at least surprising that in this case the Saver is added during the `__init__` and not the `begin` call.
