### ISSUE TITLE
Add forget_bias option to LSTMCell

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#1326]
Currently `BasicLSTMCell` accepts a `forget_bias` option but `LSTMCell` does not and always defaults to a forget bias of 1 that cannot be controlled by the user.

**Comment by ebrevdo** [comment]
May not get to this till next week.

**Comment by alquraishi** [comment]
If it's not too much trouble :-), it'd be great if one can control the weight and bias initializers independently, as in the `tf.contrib.layers` functions like `fully_connected` and `convolution2d`, which accept separate `weight_init` and `bias_init` options. They would be separate from the forget bias of course.

**Comment by girving** [comment]
@ebrevdo: Are you still working on this, or should I mark it contributions welcome?

**Comment by aselle** [comment]
This seems to already be resolved, https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/LSTMCell, closing!
