### ISSUE TITLE
tensor flow optimizer

### ISSUE THREAD

**Issue by riyaj8888** [tensorflow/tensorflow#13276]
![desto](https://user-images.githubusercontent.com/29457825/30785133-38286aee-a17f-11e7-9130-2e271e4543a3.PNG)

**Comment by caisq** [comment]
https://stackoverflow.com/questions/tagged/tensorflow may be more suited for this sort of questions. 

But in your case, just change your line 5 to:
```python
sess = tf.Session()
sess.run(init)
```
