### ISSUE TITLE
default initializer for seq2seq example

### ISSUE THREAD

**Issue by zcyang** [tensorflow/tensorflow#1328]
What is the default initialization for the weight in seq2seq example? I can find it no where, it is completely not defined.

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/795f35da2d458cbae477ac2fe2bff80c1427a771/tensorflow/python/ops/rnn.py#L92 -- I think the initialization of the state in the rnn cells is zero.  Is that what you were wondering?

**Comment by zcyang** [comment]
no, I mean the weights parameters, the embedding, the weights of the grus, the output projects etc. no default initializer is provided. I cannot find it anywhere.
https://github.com/tensorflow/tensorflow/blob/795f35da2d458cbae477ac2fe2bff80c1427a771/tensorflow/python/ops/rnn_cell.py#L675

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/0e9240b72613aa084728dcba55f7fae3591e86ad/tensorflow/python/ops/variable_scope.py#L65

Does that help?

**Comment by zcyang** [comment]
I saw it, but the definition of ```UniformUnitScalingInitializer``` is missing. I assumed it is ```6/sqrt(n_in + n_out)```. But I manually check some of the initial weights, some of the weights follow the rule, some of them doesn't. Seems different weights have different initialization. For example, the output projection matrix and decoder embedding matrix have the same shape, but their initial values are quite different.

**Comment by nryant** [comment]
https://github.com/tensorflow/tensorflow/blob/0e9240b72613aa084728dcba55f7fae3591e86ad/tensorflow/python/ops/init_ops.py#L149
