### ISSUE TITLE
Feature request for graph visualizer: turn off node collapsing

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#13297]
There's a simple feed-forward pbtxt [here](https://github.com/yaroslavvb/stuff/blob/master/resnet_8_simple.pbtxt) 

It can be visualized without any edges crossing. However latest TensorBoard collapses Relu-Relu_6 nodes together, so that complicates the diagram and introduces edge crossings. It would be nice to have a way to visualize without node collapsing

![screenshot 2017-09-25 11 35 53](https://user-images.githubusercontent.com/23068/30824844-bf81f922-a1e5-11e7-9cf4-5995ba19e5a4.png)

cc @dsmilkov

**Comment by yaroslavvb** [comment]
Here's what it looks like when hacked to turn off node collapsing. Note that Dense layer is now at the top as expected.

![screenshot 2017-09-25 12 16 59](https://user-images.githubusercontent.com/23068/30826436-775c2f86-a1eb-11e7-8532-1d895014f17d.png)

**Comment by georgh** [comment]
that's a tensorboard issue isn't it?
https://github.com/tensorflow/tensorboard/issues

**Comment by yaroslavvb** [comment]
Good point, didn't realize that was separate
