### ISSUE TITLE
Our shell wrapper around swig is a bug according to bazel

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#1329]
Bazel likes to strip things it doesn't like out of `PATH`, as discussed at https://github.com/bazelbuild/bazel/issues/957.  For TensorFlow, this is a problem since we have a shell wrapper around swig that just says `swig "$@"`.  In my case, `swig` is in `~/homebrew/bin`.

Since Bazel considers this a bug in TensorFlow rather than in Bazel, it may be more useful to have the discussion here than on the Bazel site.

**Comment by girving** [comment]
Here is the problematic file: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/swig/swig.sh

**Comment by ebrevdo** [comment]
Perhaps we can use some kind of crosstool wrapper-type functionality?

**Comment by ebrevdo** [comment]
Alternatively set it up during the configure script, the way we do python: as a parameter in bazelrc.

**Comment by girving** [comment]
@ebrevdo: Yep, I think that's the way to go.

**Comment by hhclam** [comment]
I think using configure is also the best thing to do as well. configure can find a way to plugin the location of swig through command line or generate an external local repository for swig. It needs to configure SWIG_LIB as well.

**Comment by girving** [comment]
`configure` hack complete.  I'll send it for review soon.
