### ISSUE TITLE
Input Pipeline for High-performance Model

### ISSUE THREAD

**Issue by yuezhu1** [tensorflow/tensorflow#13294]
### Describe the problem
When using data_flow_op.RecordInput in input pipeline on distributed TensorFlow, every input thread seems load all files in the data_dir to the local buffer after shuffling and left-shifting all matched file names in data_dir (https://github.com/tensorflow/tensorflow/blob/40eef4473bda90442bb55fcc67842f097c024580/tensorflow/core/kernels/record_yielder.cc#L139). 
Based on the code, it seems like data input for each epoch ends with loading all files instead of part of the files on every worker.

 If I understand correctly, each input thread from each worker task should read a portion of the files, which should be the shift_ratio * file_num. It will be very helpful, if anyone can explain this.

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
