### ISSUE TITLE
Passing CPU value along with GPU tensor

### ISSUE THREAD

**Issue by andrei-pokrovsky** [tensorflow/tensorflow#13331]
Hello, i'm trying to pass a CPU value or a block of values from one custom op into another along with a GPU tensor but the framework seems to be converting everything to GPU tensor. There doesn't seem to be a mechanism for passing mixed GPU+CPU op results right now.

**Comment by poxvoculi** [comment]
Do you have a custom Op that produces both GPU-local and CPU-local tensors?  Can you be a bit more specific about what you're trying to do?

**Comment by andrei-pokrovsky** [comment]
Correct, it's a custom op that produces both CPU and GPU tensors but I can't seem to make the framework pass them both along through the graph pinned to their respective devices.

**Comment by poxvoculi** [comment]
Ok, let's get more specific.  You're trying to do something that probably wasn't anticipated in the early phases of design, but may be possible anyway.  An Op is supposed to allocate memory for its output tensors by calling OpKernelContext::allocate_output().  Two of the definitions take an AllocatorAttributes parameter, e.g. [this one](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/op_kernel.h#L808).  If the op is assigned to execute on a GPU (i.e. 'placed on' a GPU), then the allocator will by default allocate memory from GPU RAM, but AllocatorAttributes has an [on_host bit](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/allocator.h#L352) which if set should cause a GPU allocator to allocate from CPU RAM instead.

Are you allocating memory from the OpKernelContext::allocate_output function or some other way?

If from allocate_output, are you setting the on_host attribute of AllocatorAttributes in the request?

Can you confirm that you've actually allocated a CPU resident tensor within your Op prior to returning the value?

Is it the case that you successfully allocate CPU RAM and set it, but that the framework automatically converts it to a GPU value, or just fails to return it?

**Comment by andrei-pokrovsky** [comment]
Thank you, I did try AllocatorAttributes but the next custom op that consumes the input seemed to be getting a GPU address in a tensor that was allocated with on_host attribute in a previous op.

**Comment by poxvoculi** [comment]
So, you're allocating from allocate_output() with the on_host bit, and you've confirmed that the tensor is allocated from CPU RAM when you access it in your Op.  Then the next Op in the flow graph (let's call it B) is also a GPU-placed Op, and when B reads the tensor via OpKernelContext::inputs() you find that it's allocated from GPU memory, correct?

The TF execution environment will copy a CPU tensor to GPU RAM when the consuming Op is placed on a GPU, unless the Op specifies that that particular input is expected to be in CPU RAM.  This specification is static, done when the Op is registered.   I don't have access to an example of how, at the moment, but the OpKernel definition will end of with a HOST_MEMORY MemoryType attribute for that input.  Maybe you can figure out by looking for how [this](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/core/framework/op_kernel.h?q=op_kernel.h&dr=CSs&l=276) gets set.

So the next question is, has op B declared that the corresponding input is HOST_MEMORY?

**Comment by yaroslavvb** [comment]
TensorFlow GPU reductions used mixed inputs -- op is on GPU, input tensor is GPU, reduction indices are on CPU using host memory attribute

from /core/kernels/reduction_ops_min.cc
```
#define REGISTER_GPU_KERNELS(type)          \
  REGISTER_KERNEL_BUILDER(                  \
      Name("Min")                           \
          .Device(DEVICE_GPU)               \
          .TypeConstraint<type>("T")        \
          .TypeConstraint<int32>("Tidx")    \
          .HostMemory("reduction_indices"), \
      ReductionOp<GPUDevice, type, Eigen::internal::MinReducer<type>>);
REGISTER_GPU_KERNELS(float);
REGISTER_GPU_KERNELS(double);

```

**Comment by andrei-pokrovsky** [comment]
Ok, thank you. I missed the HostMemory bit in the custom ops doc.
