### ISSUE TITLE
Using CheckpointReader from another language

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/tensorflow#13344]
@asimshankar Is the checkpoint reader class (`checkpoint_reader.h`) currently exposed through any dynamic library?

**Comment by asimshankar** [comment]
I do not believe it is (and it isn't even C, it's C++ :).

What exactly do you want to do? As in, we could consider a pure-C API for reading checkpoints, but the [`SaveV2`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/io_ops.cc#L60) and [`RestoreV2`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/io_ops.cc#L100) operations deal with checkpoints - so presumably those could be used without needing to expose a lower level API?

**Comment by eaplatanios** [comment]
@asimshankar Actually never mind. @allenlavoie pointed me to the `libtensorflow_framework.so` binary yesterday, and I was able to build the bindings I needed using that ([here](https://github.com/eaplatanios/tensorflow_scala/blob/master/jni/src/main/native/checkpoint_reader.cc) is a one example). It's actually great because with this binary I can now implement an interface to the server code for distributed training, add while loop backprop support, etc. :)

This also resolves #13345 and so I'll go ahead and close it.
