### ISSUE TITLE
Diagnosis after running tensorflow_self_check.py

### ISSUE THREAD

**Issue by gmagen** [tensorflow/tensorflow#13346]
Hello

After running tensorflow_self_check.py with Jupyter, I get the following message:

ERROR: Failed to import the TensorFlow module.

- Python version is 3.5.

- TensorFlow is installed at: c:\users\gmagen\appdata\local\programs\python\python35\lib\site-packages\tensorflow

- All required DLLs appear to be present. Please open an issue on the
  TensorFlow GitHub page: https://github.com/tensorflow/tensorflow/issues
An exception has occurred, use %tb to see the full traceback.

SystemExit: -1

How do I solve it|

**Comment by yaroslavvb** [comment]
This may be better for stackoverflow, there's not enough information here to address it as a bug on tesnorflow site (ie, filling out the template)

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
