### ISSUE TITLE
Tensor Flow Installation issue: couldnot find a version that satisfies the requirement tensorflow

### ISSUE THREAD

**Issue by sethun** [tensorflow/tensorflow#13340]
I am trying to install Tensorflow through anaconda. Following is the error when I try to install
_"couldnot find a version that satisfies the requirement tensorflow"._

I tried to create two sessions - with Python 3.5 and Python 3.6 - but both of them returns the error identically.

Code used in the activated sessions: pip install tensorflow
 
Screenshot1 - Python 3.6 (Environment name: tenflow)
![image](https://user-images.githubusercontent.com/8396984/30917306-543b3d56-a3b9-11e7-91f8-aa705342e773.png)

Screenshot2 - Python 3.6 (Environment name: tflow)
![image](https://user-images.githubusercontent.com/8396984/30917325-603c716a-a3b9-11e7-9daf-c8e323d55bf2.png)

**Comment by Carmezim** [comment]
Assuming your Python distribution is 64-bit and not 32-bit, could you try then `conda install tensorflow` rather than using `pip`?

**Comment by sethun** [comment]
Thanks carmezium. My python is 32 bit. Now I realise there isn't tensorflow for 32 bit.

**Comment by Carmezim** [comment]
Glad you found the culprit. If there isn't any other question this issue can be closed now.
