### ISSUE TITLE
Tensorflow 1.3.0  and Python 3.5.2  Issue in Redhat RH 6.7 x86_64 issue in runtime

### ISSUE THREAD

**Issue by mukeshmantan** [tensorflow/tensorflow#13347]
** GLIBC version 2.12 ***
python -c "import tensorflow"
 File "/hdpapp/Anaconda3-4.2.0/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /hdpapp/Anaconda3-4.2.0/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Upgraded *** GLIB version to 2.14*****
python -c "import tensorflow" 
 File "/hdpapp/Anaconda3-4.2.0/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /opt/glibc-2.14/lib/libc.so.6: version `GLIBC_2.17' not found (required by /hdpapp/Anaconda3-4.2.0/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Upgraded *** GLIB version to 2.17*****
python -c "import tensorflow"
error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument

Any idea what configuration is not matching causing the runtime issue

**Comment by gunan** [comment]
We do not have official support for Redhat, or Anaconda. So I am marking this community support.

However, the following is possible.
It is possible anaconda python and tensorflow are looking for different versions of glibc.
Could you install pip and python through RPM and try again?

**Comment by sriharsha-sammeta** [comment]
`conda install tensorflow` works
