### ISSUE TITLE
parameterized_docker_build.sh fails

### ISSUE THREAD

**Issue by SaintNazaire** [tensorflow/tensorflow#13358]
### Issue

Executing parameterized_docker_build.sh fails to generate new docker image, throws out multiple error messages.

### System information
- **I have used a stock example script provided in TensorFlow**
- **Windows 10 professional**
- **TensorFlow not installed (looking for generating a dockerfile)**
- **TensorFlow version 1.3:latest (eventually looking for this version)**
- **Python version 3 (eventually looking for this version)**
- **Bazel version not yet installed**
- **CUDA/cuDNN version not relevant (CPU install)**
- **GPU model and memory not relevant (CPU install)**

### Set-up

```
>>> Docker run -it Ubuntu:latest /bin/bash
$ apt-get update
$ apt-get install curl
$ cd /opt
$ curl -O https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/docker/parameterized_docker_build.sh
$ curl -O https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/docker/parameterized_docker_build.sh
$ chmod +x opt/parameterized_docker_build.sh
$ export TF_DOCKER_BUILD_IS_DEVEL=NO
$ export TF_DOCKER_BUILD_TYPE=CPU
$ export TF_DOCKER_BUILD_PYTHON_VERSION=PYTHON3
$ export NIGHTLY_VERSION="1.head"
$ export TF_DOCKER_BUILD_CENTRAL_PIP=$(echo ${TF_DOCKER_BUILD_PYTHON_VERSION} | sed s^PYTHON2^http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=${TF_DOCKER_BUILD_PYTHON_VERSION},label=cpu-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-${NIGHTLY_VERSION}-cp27-cp27mu-manylinux1_x86_64.whl^ | sed s^PYTHON3^http://ci.tensorflow.org/view/Nightly/job/nightly-python35-linux-cpu/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-${NIGHTLY_VERSION}-cp35-cp35m-manylinux1_x86_64.whl^)
```

### Command triggering issue

`$ sh opt/parameterized_docker_build.sh`

### Error messages

> opt/parameterized_docker_build.sh: 70: opt/parameterized_docker_build.sh: Bad substitution
> opt/parameterized_docker_build.sh: 71: opt/parameterized_docker_build.sh: source: not found
> opt/parameterized_docker_build.sh: 81: opt/parameterized_docker_build.sh: to_lower: not found
> opt/parameterized_docker_build.sh: 82: opt/parameterized_docker_build.sh: to_lower: not found
> opt/parameterized_docker_build.sh: 83: opt/parameterized_docker_build.sh: to_lower: not found
> opt/parameterized_docker_build.sh: 84: opt/parameterized_docker_build.sh: to_lower: not found
> Required build parameters:
>   TF_DOCKER_BUILD_TYPE=
>   TF_DOCKER_BUILD_IS_DEVEL=
>   TF_DOCKER_BUILD_DEVEL_BRANCH=
> 
> Optional build parameters:
>   TF_DOCKER_BUILD_CENTRAL_PIP=http://ci.tensorflow.org/view/Nightly/job/nightly-python35-linux-cpu/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-1.head-cp35-cp35m-manylinux1_x86_64.whl
>   TF_DOCKER_BUILD_IMAGE_NAME=
>   TF_DOCKER_BUILD_VERSION=
>   TF_DOCKER_BUILD_PORT=
>   TF_DOCKER_BUILD_PUSH_CMD=
> opt/parameterized_docker_build.sh: 102: opt/parameterized_docker_build.sh: [[: not found
> opt/parameterized_docker_build.sh: 114: opt/parameterized_docker_build.sh: [[: not found
> opt/parameterized_docker_build.sh: 121: opt/parameterized_docker_build.sh: [[: not found
> opt/parameterized_docker_build.sh: 124: opt/parameterized_docker_build.sh: die: not found
> opt/parameterized_docker_build.sh: 128: opt/parameterized_docker_build.sh: [[: not found
> opt/parameterized_docker_build.sh: 130: opt/parameterized_docker_build.sh: [[: not found
> opt/parameterized_docker_build.sh: 141: opt/parameterized_docker_build.sh: die: not found
> opt/parameterized_docker_build.sh: 145: opt/parameterized_docker_build.sh: [[: not found
> opt/parameterized_docker_build.sh: 147: opt/parameterized_docker_build.sh: [[: not found
> opt/parameterized_docker_build.sh: 150: opt/parameterized_docker_build.sh: die: not found
> opt/parameterized_docker_build.sh: 156: opt/parameterized_docker_build.sh: [[: not found
> 
> FINAL_IMAGE_NAME: tensorflow/tensorflow
> FINAL_TAG: latest
> Original Dockerfile: //Dockerfile
> 
> Docker build will occur in temporary directory: /tmp/tmp.IItoQQJuhx
> cp: error reading '//proc/1/task/1/personality': Operation not permitted
> cp: error reading '//proc/1/task/1/syscall': Operation not permitted
> cp: cannot open '//proc/1/task/1/mem' for reading: Permission denied
> cp: error reading '//proc/1/task/1/clear_refs': Invalid argument

**Comment by evalsocket** [comment]
Use tensorflow's official [docker image ](https://hub.docker.com/r/tensorflow/tensorflow/)
CPU and GPU Support also available with their docker image just choose the [right tag](https://hub.docker.com/r/tensorflow/tensorflow/tags/)
`docker run -it -p 8888:8888 tensorflow/tensorflow`

**Comment by SaintNazaire** [comment]
Thank you but sorry the image launches a number of processes I don't need/like in particular Jupyter and I would like to build my own stripped down docker image.

**Comment by SaintNazaire** [comment]
You are correct thank you very much.

Let me explicit a bit your solution because I nearly failed to grasp it and this can be useful for future readership and eventual documentation.

If one docker pulls a developer image, it will contain the code. So for example let's docker pull tensorflow/tensorflow:1.3.0-devel-py3, then one should be able to run parameterized_docker_build.sh in the /tensorflow/tensorflow/tools/docker folder just  fine.

The smallest command line to generate a docker image will then be:
`docker run -it tensorflow/tensorflow:`[right tag](https://hub.docker.com/r/tensorflow/tensorflow/tags/)

Port mapping at 8888 `-p 8888:8888` is nice to have.
