### ISSUE TITLE
Changing compiler to gcc not works

### ISSUE THREAD

**Issue by formath** [tensorflow/tensorflow#13353]
In my macOS, I have set `export CC=/usr/local/bin/gcc-6` and `export CXX=/usr/local/bin/g++-6`. Then I built tensorflow from source using `sh tensorflow/contrib/makefile/build_all_ios.sh`. But I saw it also compile using `clang`. So, how to change compiler? @martinwicke

**Comment by martinwicke** [comment]
@petewarden knows more about the makefile.

**Comment by facaiy** [comment]
Hi, @formath . I prefer to using `clang` by default, since we seems not the only one who get stuck in `gcc` on Mac. see #336, #649, #75 ...

**Comment by formath** [comment]
@petewarden Hi. Have you checked it? Thanks
