### ISSUE TITLE
Installing Tensorflow 1.3.0 succeeds even when the cuDNN version is not correct

### ISSUE THREAD

**Issue by icefoxen** [tensorflow/tensorflow#13365]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7.4
- **TensorFlow installed from (source or binary)**: pip (binary?)
- **TensorFlow version (use command below)**: ('v1.3.0-rc2-20-g0787eee', '1.3.0')
- **Python version**: 2.7.5
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 8.0, cuDNN 5.1
- **GPU model and memory**: TITAN X (Pascal), 12GB
- **Exact command to reproduce**:  

 * Install tensorflow: `pip install tensorflow-gpu`
 * Try to use tensorflow: `python -c "import tensorflow;"

### Describe the problem
When imported, Tensorflow looks for `libcudnn.so.6` and does not find it, since only 5.1 is installed, and fails with an error message

What I would expect to happen is a) it either compiles against the version of libcudnn.so actually available, or b) it tries to check whether the correct version exists at install time and the install fails with a helpful message if it does not.

This is also not documented in https://www.tensorflow.org/install/install_linux or https://www.tensorflow.org/install/install_sources, in fact all it says for software requirements is "cuDNN (>= v3). We recommend version 5.1", which is what I had installed.

Thank you!

### Source code / logs

N/A

**Comment by poxvoculi** [comment]
Instructions at [https://www.tensorflow.org/install/install_linux](https://www.tensorflow.org/install/install_linux) say:

"If you have an earlier version of the preceding packages..." (such as cuDNN < 6.0) "...you may still run TensorFlow with GPU support, but only if you do the following:

Install TensorFlow from sources as documented in Installing TensorFlow from Sources."

Sorry the instructions are so long, I know it's easy to miss this.
