### ISSUE TITLE
Feature request: tf.reduce_median()

### ISSUE THREAD

**Issue by thjashin** [tensorflow/tensorflow#13360]
Hi, is there any plan to support a `tf.reduce_median` operator? Now one have to resort to `tf.nn.top_k` for implementing this.

**Comment by yaroslavvb** [comment]
could be a good idea for an external contribution -- name makes sense, doesn't need to be tested against existing models

**Comment by ppwwyyxx** [comment]
I guess technically median is not a reduce(fold) operation.

**Comment by thjashin** [comment]
@ppwwyyxx Yep. It only makes sense as a name. That doesn't matter though, I just want to say that it deserves an operator.

**Comment by aselle** [comment]
I am marking as contributions welcome, but I imagine this is actually a very difficult feature to implement efficiently as a streaming (accelerated) median calculation requires some thought.

**Comment by jinze1994** [comment]
@aselle I think it would be better if we implemented two separate op with tf.reduce_median and tf.contrib.metrics.streaming_median.

**Comment by nicaogr** [comment]
Don't you think that [tf.contrib.distributions.percentile(x,50.)](https://www.tensorflow.org/api_docs/python/tf/contrib/distributions/percentile) can be used to create a reduce_median function ?

**Comment by mohantym** [comment]
Hi @thjashin ! You can use[ tfp.stats.percentile](https://www.tensorflow.org/probability/api_docs/python/tfp/stats/percentile) to calculate the median of a distribution. Attaching relevant [thread](https://stackoverflow.com/a/47657076/11530462) for reference. Thank you!
