### ISSUE TITLE
'tensorflow.python.ops.nn' has no attribute 'selu'

### ISSUE THREAD

**Issue by arinbjornk** [tensorflow/tensorflow#13361]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: CUDA 8.0
- **GPU model and memory**: GTX 1080
- **Exact command to reproduce**: 
```
import tensorflow as tf
...
y = tf.nn.selu(x)
```

### Describe the problem
TensorFlow 1.3 cannot find selu activation. Relu and elu work fine.
Relevant documentation: [tf/nn/selu](https://www.tensorflow.org/versions/master/api_docs/python/tf/nn/selu)

### Source code / logs
```
Traceback (most recent call last):
  File "my_file.py", line 212, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/file/location", line 35, in model
   y = tf.nn.selu(x)
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'selu'
```

**Comment by AVCarreiro** [comment]
I think this is only available in the master branch of TF for now. Probably in TF 1.4?

**Comment by arinbjornk** [comment]
@AVCarreiro Thanks. Not sure why I missed that.

Case closed.
