### ISSUE TITLE
parameterized_docker_build.sh fails

### ISSUE THREAD

**Issue by SaintNazaire** [tensorflow/tensorflow#13379]
### Issue

Executing parameterized_docker_build.sh fails to generate new docker image, throws error message.

### System information
- I have used a stock example script provided in TensorFlow
- Windows 10 professional
- TensorFlow install as docker image tensorflow/tensorflow:1.3.0-devel-py3
- TensorFlow version 1.3
- Python version 3
- Bazel version 0.5.0
- CUDA/cuDNN version not relevant (CPU install)
- GPU model and memory not relevant (CPU install)

### Set-up

```
>>> docker pull tensorflow/tensorflow:1.3.0-devel-py3
>>> docker run -it tensorflow/tensorflow:1.3.0-devel-py3
$ cd /
$ cd /tensorflow/tensorflow/tools/docker
$ chmod +x  /tensorflow/tensorflow/tools/docker/parameterized_docker_build.sh
$ export TF_DOCKER_BUILD_IS_DEVEL=NO
$ export TF_DOCKER_BUILD_TYPE=CPU
$ export TF_DOCKER_BUILD_PYTHON_VERSION=PYTHON3
$ export NIGHTLY_VERSION="1.head"
$ export TF_DOCKER_BUILD_CENTRAL_PIP=$(echo ${TF_DOCKER_BUILD_PYTHON_VERSION} | sed s^PYTHON2^http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=${TF_DOCKER_BUILD_PYTHON_VERSION},label=cpu-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-${NIGHTLY_VERSION}-cp27-cp27mu-manylinux1_x86_64.whl^ | sed s^PYTHON3^http://ci.tensorflow.org/view/Nightly/job/nightly-python35-linux-cpu/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-${NIGHTLY_VERSION}-cp35-cp35m-manylinux1_x86_64.whl^)
```

### Command triggering issue

`$ /tensorflow/tensorflow/tools/docker/parameterized_docker_build.sh`

### Error messages

> Required build parameters:
>   TF_DOCKER_BUILD_TYPE=cpu
>   TF_DOCKER_BUILD_IS_DEVEL=no
>   TF_DOCKER_BUILD_DEVEL_BRANCH=NO
> 
> Optional build parameters:
>   TF_DOCKER_BUILD_CENTRAL_PIP=http://ci.tensorflow.org/view/Nightly/job/nightly-python35-linux-cpu/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-1.head-cp35-cp35m-manylinux1_x86_64.whl
>   TF_DOCKER_BUILD_IMAGE_NAME=
>   TF_DOCKER_BUILD_VERSION=
>   TF_DOCKER_BUILD_PORT=
>   TF_DOCKER_BUILD_PUSH_CMD=
> ERROR: docker is not available on path

**Comment by caisq** [comment]
As the error message includes, the script can't find docker on your path. Is docker available on your system? What is your "which docker" output?

**Comment by gunan** [comment]
Looks like this is a problem in user environment setup.
Closing.

**Comment by psawbridge** [comment]
Sorry for reopening this but I am having the same problem (host ubuntu 16.04, running on image latest-devel) and I don't understand how it is a user environment setup issue as the procedure he is following is exactly that defined in:
tensorflow/tensorflow/tools/docker/README.md

Shouldn't the development container (latest-devel) allow usage of docker natively or is there a magic trick to run the container so that it connects to docker running on the host? Doesn't seem like docker is included in the latest-devel image and the instruction explicitly state that the parametrized_docker_build.sh script must be run with a development image container.

Am I missing something?

**Comment by SaintNazaire** [comment]
One needs to [install docker](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#set-up-the-repository) in the container. On my system i.e. the environment was not set up properly so @gunan was right.

For example and depending on your machine:

```
$ apt-get update && \
    apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
   apt-get install docker-ce
```

`$which docker`
> /usr/bin/docker

I'm still stalled, suggest you check out #13784 if there is anything you can contribute, don't forget to edit the read me everytime you validate a solution. This repo has way too many contributors and no proper documentation.
