### ISSUE TITLE
Add python 3 iterator support for `tf.convert_to_tensor`

### ISSUE THREAD

**Issue by tongda** [tensorflow/tensorflow#13375]
I am working on TensorFlow 1.3.0 and Python 3.6.3.

I found that I have to write many unnecessary code to cast python iterator (such as return value of map, filter, zip and dict_keys) to `list` so that `tf.convert_to_tensor` could work. Supporting convert python iterator to tensor could not only help python 3 user write concise code without many `list(xxx)`, but also memory saving.

**Comment by martinwicke** [comment]
How exactly would you do it? We'd have to ensure that accidentally iterables (Tensors, numpy arrays, strings) are not caught up in this. If it's possible safely, it's a good idea.

**Comment by tongda** [comment]
Inside of the implementation of `tf.conver_to_tensor`, there is a `_tensor_conversion_func_registry` which includes the supported type and its conversion function. I am thinking of adding some `(type, conversion function)` pair to this registry, where the `type` is the specific name of the iterators, such as `zip`, `map`, `dict_keys`, etc.

Additionally, to avoid incidental false invoke, we can set the priority to be low. They will be called after the previous `Tensor`, `ndarray` check.

We can first call `numpy.fromiter` on the iterators to generate a `ndarray`, then call the existed conversion function on the `ndarray` to convert to `Tensor`. I guess TF will reuse the memory of numpy, so this could save memory and time from avoiding copy memory from Python VM to TF runtime.

**Comment by martinwicke** [comment]
That sounds like a fine plan to me. This would have to be tested quite rigorously, we've had problems with the errors generated by convert_tensors before and we'd want to test even the error behavior to make sure that it's informative.

But given those caveats, I'd welcome PRs for this.

**Comment by NicolaBernini** [comment]
Hi everybody, 
sorry in advance for the question (I'm new to TF contribtion) but isn't this type - conversion function association already performed by `register_tensor_conversion_function()` ? 

If so the `_tensor_conversion_func_registry` detail should not be needed: it should be possible to perform the function registration somewhere else in the framework 

Thanks

**Comment by facaiy** [comment]
Yes, @NicolaBernini is correct. Perhaps this is where to add conversion functions as @tongda proposed.

https://github.com/tensorflow/tensorflow/blob/0cfb16e025b3d20e8c8aca431fc0887814817c44/tensorflow/python/framework/constant_op.py#L212-L219

Since `tf.conver_to_tensor`, if broken , may affect lots of users. If I were you, perhaps it would be better to write down all iterator types we desired at the beginning.

Anyway, sounds reasonable and be extra careful.

**Comment by gauravdesale** [comment]
I was thinking of contributing to this project and this is a really good beginner issue so I made a simple python function to create a numb array of the constant. Im not sure if I am understanding this right. Is there any way I can push this onto one of the experimental branches?

**Comment by dynamicwebpaige** [comment]
Closing, as we should have iterator support in TensorFlow 2.0.
