### ISSUE TITLE
Error with conditional labelling of summary

### ISSUE THREAD

**Issue by Lee-L-Boyd** [tensorflow/tensorflow#13370]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip install tensorflow --upgrade
- **TensorFlow version (use command below)**:1.3.0
- **Python version**: Python 2.7.12
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: Cuda compilation tools, release 7.5, V7.5.17
- **GPU model and memory**: NVIDIA 1070 16G
- **Exact command to reproduce**: python model_wgraph2.py

### Describe the problem

I am attempting to vary my labels for the summary conditional on some tf.bool data type.  I get an error when I attempt to use the tf.cond.  

Per: https://github.com/tensorflow/tensor2tensor/issues/159,
this problem should have been fixed in version 1.1.0

"lukaszkaiser:

This was due to summaries not working with tf.conds right. Should be corrected in 1.1.0, please take a look and reopen if you see this again!"
--

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
	text2 = tf.cast('blah', tf.string)	
	text_summary = tf.summary.text("NULL", text2) #works fine without conditional	
	rightness = tf.cast(True, tf.bool)
	text_summary = tf.cond( rightness, lambda: tf.summary.text("TRUE", text2), lambda: tf.summary.text("FALSE", text2) ) #breaks with error below

###Error
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

**Comment by evalsocket** [comment]
Try with this may be it help you. change your code according to this change
`rightness = tf.cast(True, tf.bool)`

**Comment by Lee-L-Boyd** [comment]
Same error

**Comment by Lee-L-Boyd** [comment]
Solved:
        #For whatever reason don't try to instantiate the summary inside of the conditional
        text_summary_1 = tf.summary.text("TRUE", text)
	text_summary_2 = tf.summary.text("FALSE", text)
	text_summary = tf.cond( rightness, lambda: text_summary_1, lambda: text_summary_2 )

**Comment by Lee-L-Boyd** [comment]
Nix that from above, code runs but it adds both cases to the summary!?

**Comment by Lee-L-Boyd** [comment]
Okay so it looks like the key to making this work is making sure that the two summaries you make to put into the conditional do not get merged and put in the Tensorboard too.  This means you don't get to use the nice merge_all() functionality.  With merge_all() there is no way to differentiate between what your conditional chose, since they are all merged together.   Name-scoping the copy doesn't help, since the name-scope is apparently copied from whichever summary is branched in the conditional, which implies it is more a reference than a copy.  Either way, don't know, don't care, but this workaround seems to solve the immediate problem.

**Comment by zh794390558** [comment]
https://github.com/tensorflow/tensorflow/issues/10059

**Comment by jgmakin** [comment]
Looks like this has been solved in 1.5.0rc1: you can now use `merge_all` with (e.g.) `tf.while_loop`s again.  Thanks, tensorflowers.

**Comment by jgmakin** [comment]
Strike that, still broken (or anyway not naively usable) in 1.5.0:

"Cannot use 'while/...' as input to 'Merge/MergeSummary' because 'while/...' is in a while loop."

**Comment by aforslow** [comment]
Any updates on this issue? I just stumbled upon this problem in tensorflow 1.6.0. It feels logical to allow for conditional labelling.

My workaround now is, thanks to Lee-L-Boyd, to save the summaries in different collections in the conditional functions, i.e. `summary_lib.scalar(plot_name, val, collections=['train'])` and then use the `merged_summary = tf.summary.merge_all('train')` functionality. I suppose it is possible to create multiple merged summaries that collects from your conditional's collections. These could then be added to the same writer as different summaries. This is a workaround, however, and it would be a lot more logical to just provide functionality for conditional labelling.

**Comment by sh1ng** [comment]
I'm using TF 1.8 and faced the same problem, but when my target function contains condition like
`
y = tf.cond(y > eps, lambda: y * N, lambda: y)
`
where eps and N another op
