### ISSUE TITLE
Tensorflow - Error: Cannot convert value dtype('<f4') to a TensorFlow DType

### ISSUE THREAD

**Issue by claudefalbriard** [tensorflow/tensorflow#13384]
I receive an error when testing a Neural Style Transformation project with Tensorflow & OpenCV using the "lion" test image. The source of test project is:  [ [https://github.com/cysmith/neural-style-tf](https://github.com/cysmith/neural-style-tf) ]. Both Tensorflow and OpenCV packages were installed and compiled from source. The training model used is: imagenet-vgg-verydeep-19.mat and the runtime environment runs on a s390x CPU and does not use any CUDA support. The  current Python environment is 2.7 under Docker Linux Ubuntu 16.

Run command:
`bash stylize_image.sh ./image_input/lion.jpg ./styles/kandinsky.jpg`

The error message at log is:
```
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/dtypes.py", line 584, in as_dtype
    "Cannot convert value %r to a TensorFlow DType." % type_value)
TypeError: Cannot convert value dtype('<f4') to a TensorFlow DType.
```

Versions installed: 

```
python 2.7.12
import tensorflow as tf 
>>> print tf.VERSION
1.3.1
import cv2 
>>> print cv2.__version__ 
3.3.0
>>> print np.__version__
1.13.2

```
Is this a known issue?

**Comment by yaroslavvb** [comment]
This looks like an issue with neural-style-tf project (probably was developed for older version of tf)

**Comment by facaiy** [comment]
@claudefalbriard Perhaps `<f4` is forgot to be converted for neural-style-tf project.

```python
In [8]: import tensorflow as tf

In [9]: import numpy as np

In [10]: tf.as_dtype(np.dtype("<f4"))
Out[10]: tf.float32
```

**Comment by yaroslavvb** [comment]
Closing to keep issues focused on  TensorFlow-specific bugs

**Comment by claudefalbriard** [comment]
Thanks for the hints and orientation. The "<" symbol describes an array in "Little Endian" notation, while the runtime platform is a "Big Endian" CPU. The issue seems to point to the dtypes.py module in the tensorflow framework folder, which might not support it. I will check the demo project, or model file and see if its possible to adjust the data through a manual Numpy byte swapping, or TF casting function.  By adding the "<f4>" to the _NP_TO_TF translation table, I was able to correct the run-time exception, but got an erroneous result in the output file, likely explained by the missing endianness adjustment.
