### ISSUE TITLE
tf.read_file isn't in the informed folder

### ISSUE THREAD

**Issue by Silve1ra** [tensorflow/tensorflow#13397]
the documentation below:

https://www.tensorflow.org/api_docs/python/tf/read_file

Says that this function is here:

https://github.com/tensorflow/tensorflow/tree/r1.3/tensorflow/python/ops

But isn't .

------------------------

Thanks,

**Comment by facaiy** [comment]
Hi, @Silve1ra . 
Do you mean why `gen_io_ops.py` is missing? 
Yes, `gen_` prefix indicates those files are generated automatically from files (similar location in `core`) in  c++ side. Hence, `read_file` is at [tensorflow/core/ops/io_ops](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/core/ops/io_ops.cc) in fact.

https://github.com/tensorflow/tensorflow/blob/107cc777af7880c140d089e44ad898a6ba929286/tensorflow/core/ops/io_ops.cc#L824-L830

By the way, perhaps this is useful for understanding: [Adding a New Op](https://www.tensorflow.org/extend/adding_an_op)

**Comment by cy89** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
