### ISSUE TITLE
Error in installing the tensorflow on 32 bit Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by raj-maurya** [tensorflow/tensorflow#1340]
Hi Developers:

Please, guide me to fix the issue and help me to install the tensorflow on the 32bit Ubuntu 14.04 LTS.

Error i am getting :
hunter@hunter:~$ sudo pip install --upgrade 
![screenshot from 2016-03-01 13 00 32](https://cloud.githubusercontent.com/assets/9070249/13420607/b4ccc094-dfad-11e5-9e32-fd9880f4056f.png)
https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl

tensorflow-0.7.1-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.
Storing debug log for failure in /home/hunter/.pip/pip.log

Thanks you for your time in advance.

**Comment by vrv** [comment]
Unfortuately we don't have a pip package for 32-bit linux right now.  You'd have to build from sources, and I'm not even sure it's supported.

**Comment by JimmyJUNUCAS** [comment]
Aha, I have met the problem these days.The problem is caused by the failure of getting the root right. To solve the problem you can input the code 'sudo su -' to get the right of root. Good luck
