### ISSUE TITLE
tensorflow.contrib.data.Dataset

### ISSUE THREAD

**Issue by Clintonrocks13** [tensorflow/tensorflow#13405]
Issue with tensorflow.contrib.data module 

![screenshot from 2017-09-30 10-25-36](https://user-images.githubusercontent.com/13569817/31042660-9b2323a6-a5ca-11e7-88f9-2960cd7439d2.png)

**Comment by tongda** [comment]
What version of TF are you using? Dataset is introduced in 1.3.0.

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
