### ISSUE TITLE
Name/variable scopes of tensorflow.python.layers.base.Layer

### ISSUE THREAD

**Issue by kzm4269** [tensorflow/tensorflow#13429]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem

This is a tiny code that creates layers and connects them in series.

```python
import tensorflow as tf
from tensorflow.python.layers.base import Layer


class A(Layer):
    def build(self, input_shape):
        self.v = self.add_variable('v', (), tf.float32)
        self.built = True
    
    def call(self, inputs):
        return self.v * inputs
    

# Case 1
with tf.Graph().as_default() as graph:
    x = tf.placeholder(tf.float32, (), 'x')
   
    out = x
    out = A()(out)
    out = A()(out)
    out = A()(out)
    
    tf.summary.FileWriter('/tmp/tensorboard/1', graph=graph).close()

# Case 2
with tf.Graph().as_default() as graph:
    x = tf.placeholder(tf.float32, (), 'x')
   
    out = x
    out = A(name='a')(out)
    out = A(name='a_1')(out)
    out = A(name='a_2')(out)
    
    tf.summary.FileWriter('/tmp/tensorboard/2', graph=graph).close()

# Case 3
with tf.Graph().as_default() as graph:
    x = tf.placeholder(tf.float32, (), 'x')
   
    out = x
    out = A(name='a_1')(out)
    out = A(name='a_2')(out)
    out = A(name='a_3')(out)
    
    tf.summary.FileWriter('/tmp/tensorboard/3', graph=graph).close()
```

#### Results

Other than case 3, an unexpected graph is generated.
Is this a bug?

- Case 1

<img alt="result" height="450" src="https://user-images.githubusercontent.com/7009040/31054076-b290a772-a6e5-11e7-8e6a-2d97420b5e0e.png">

- Case 2

<img alt="result" height="450" src="https://user-images.githubusercontent.com/7009040/31054078-b2a7ca7e-a6e5-11e7-9a17-805fd56e6ea7.png">

- Case 3

<img alt="result" height="450" src="https://user-images.githubusercontent.com/7009040/31054077-b291b7c0-a6e5-11e7-9256-be7c986094ec.png">

**Comment by facaiy** [comment]
Interesting, I just wonder whether does the same problem occur with builtin layer, say `Dense`? Could you take a similar experiment for `Dense` and `dense`?

**Comment by kzm4269** [comment]
I replaced `A` by `tensorflow.python.layers.core.Dense` and obtained similar results.

```python
import tensorflow as tf
from tensorflow.python.layers.core import Dense


def A(**kwargs):
    return Dense(units=3, **kwargs)
    

# Case 1
with tf.Graph().as_default() as graph:
    x = tf.placeholder(tf.float32, (None, 3), 'x')
   
    out = x
    out = A()(out)
    out = A()(out)
    out = A()(out)
    
    tf.summary.FileWriter('/tmp/tensorboard/1', graph=graph).close()

# Case 2
with tf.Graph().as_default() as graph:
    x = tf.placeholder(tf.float32, (None, 3), 'x')
   
    out = x
    out = A(name='a')(out)
    out = A(name='a_1')(out)
    out = A(name='a_2')(out)
    
    tf.summary.FileWriter('/tmp/tensorboard/2', graph=graph).close()

# Case 3
with tf.Graph().as_default() as graph:
    x = tf.placeholder(tf.float32, (None, 3), 'x')
   
    out = x
    out = A(name='a_1')(out)
    out = A(name='a_2')(out)
    out = A(name='a_3')(out)
    
    tf.summary.FileWriter('/tmp/tensorboard/3', graph=graph).close()
```

- Case 1
<img alt="result" height="450" src="https://user-images.githubusercontent.com/7009040/31216908-2454165c-a9f0-11e7-9812-d85b3b4b1b2d.png"/>

- Case 2
<img alt="result" height="450" src="https://user-images.githubusercontent.com/7009040/31216909-25709ed4-a9f0-11e7-9033-3770d0f22d71.png"/>

- Case 3
<img alt="result" height="450" src="https://user-images.githubusercontent.com/7009040/31216915-2a201a90-a9f0-11e7-9418-9b8705ed20b6.png"/>

**Comment by facaiy** [comment]
Thank you very much, @kzm4269 . Since `dense` might be slightly different with `Dense` , could you test `dense` as well?

**Comment by kzm4269** [comment]
OK.
I have tried the following code but the result was exactly the same.

```python
import tensorflow as tf


def A(**kwargs):
    def layer(*args):
        return tf.layers.dense(*args, units=3, **kwargs)
    
    return layer

#...
```

**Comment by facaiy** [comment]
https://github.com/tensorflow/tensorflow/blob/b58c89129894618ab28a023fb2b2e610bbbdcf81/tensorflow/python/layers/base.py#L527-L530

```
self._scope: dense
self._scope.original_name_scope: dense/

self._scope: dense_1
self._scope.original_name_scope: dense_2/

self._scope: dense_2
self._scope.original_name_scope: dense_3/
```

As we known, `get_variable(xxx)` only uses `variable_scope` as prefix.
I believe that the bug is from the inconsistency between `variable_scope` and `name_scope`, which really surprises me.
I guess it critical to find why `name_scope` jumps over `dense_1`.

**Comment by facaiy** [comment]
Hi, @kzm4269 , just in case, could you test it on [nightly pip packages](https://github.com/tensorflow/tensorflow#installation)?

**Comment by facaiy** [comment]
I create a hotfix #13518 for the issue. Results look good after patched. However, the patch might introduce some side effects, I'll finish the PR after holiday.

case 1:
![case_1](https://user-images.githubusercontent.com/1112263/31264729-992841c6-aa9d-11e7-81cb-b89b754150cf.png)

case 2:
![case_2](https://user-images.githubusercontent.com/1112263/31264733-a0426c02-aa9d-11e7-8925-ac3084d228b0.png)

case 3:
![case_3](https://user-images.githubusercontent.com/1112263/31264741-a71b1466-aa9d-11e7-9744-4f355bbb7cbd.png)

**Comment by kzm4269** [comment]
Thank you @facaiy!

**Comment by kzm4269** [comment]
Hi, @facaiy .

I think that the bug caused by this line:

https://github.com/tensorflow/tensorflow/blob/97bcc65e4c218ec9e1af1c9353cb8aa0d84b7014/tensorflow/python/ops/variable_scope.py#L1785

This code was written to reuse the name scope, but since `name_scope` is relative, so a new unique name scope will be created. Properly it should be written like the following code:

```python
        name_scope = self._name_or_scope.name + "/"
```

**Comment by facaiy** [comment]
Thanks you for suggestion, @kzm4269 . I found that it is more complicated and subtle than I expected when `name_scope` intertwines with `variable_scope`. As far as I see now, the behavior (create a new name_scope when variable_scope is opened) is on purpose by tensorflow, see #6189. I cannot believe it...

**Comment by facaiy** [comment]
Hi, @lukaszkaiser , let's discuss here. (cc @fchollet , @ebrevdo who I believe might be interested in the issue.) 

I found that the bug roots from an unexpected behavior from `variable_scope`, which always creates a new `name_scope` when it is opened (or re-entered). This is a simple example from #6189:

```python
with tf.variable_scope('a') as scope:
    v = tf.get_variable('v', [], initializer=tf.constant_initializer(42., tf.float32))
with tf.variable_scope(scope):
    w = v * 2
print(w.name)    # expected: a/mul:0
#result:  'a_1/mul:0'
```

At the first glance, I believe it is a bug (that's what PR #13518 is opened to fix) until those test cases are found:

https://github.com/tensorflow/tensorflow/blob/a1ab2a3b5263c535bfece377f1bdd77c7ade3240/tensorflow/python/kernel_tests/variable_scope_test.py#L364-L371

The confusing behavior seems designed on purpose for tensorflow, and introduced from 79d872ef79a9a9f57dfcd82e3068b1d8bd9fe392 (if I’m not mistaken with `git blame`).  Could @lukaszkaiser, if you know, give more details? Might we correct the inconsistent behavior? Thanks.

**Comment by facaiy** [comment]
To help clarify our problem, I write a simpler version for `tf.layers.Layer`.  Please notice that  `a_1` name scope has been created in 1st layer. That's why for 2nd layer, name scope must start from `a_2`, while variable scope is from `a_1` (inconsistent scopes).

### code
```python
import tensorflow as tf

def print_tensors():
    print(tf.constant([1], name="t_const"))
    print(tf.Variable([1], name="t_var"))

def print_scope():
    print("variable_scope: {}, name_scope: {}".format(tf.get_variable_scope().name, tf.contrib.framework.get_name_scope()))

def layer(name):
    # `base._set_scope` method
    with tf.variable_scope(None, default_name=name) as scope:
        s = scope
        print_scope()

    # `base.add_variable` and `base.__call__` method
    with tf.variable_scope(s) as ss:
        print("---------------------")
        print("before using original_name_scope:")
        print_scope()
        with tf.name_scope(ss.original_name_scope) as n:
            print("after using original_name_scope:")
            print_scope()

with tf.Graph().as_default() as graph:
    print("1st layer:")
    a = layer("a")
    print("\n===============================\n")
    print("2nd layer:")
    a_1 = layer("a")
    print("\n===============================\n")
    print("3rd layer:")
    a_2 = layer("a")
```

### logs
```
1st layer:
variable_scope: a, name_scope: a
---------------------
before using original_name_scope:
variable_scope: a, name_scope: a_1
after using original_name_scope:
variable_scope: a, name_scope: a

===============================

2nd layer:
variable_scope: a_1, name_scope: a_2
---------------------
before using original_name_scope:
variable_scope: a_1, name_scope: a_1_1
after using original_name_scope:
variable_scope: a_1, name_scope: a_2

===============================

3rd layer:
variable_scope: a_2, name_scope: a_3
---------------------
before using original_name_scope:
variable_scope: a_2, name_scope: a_2_1
after using original_name_scope:
variable_scope: a_2, name_scope: a_3
```

**Comment by reedwm** [comment]
@ebrevdo, can you take a look at this issue?

**Comment by lukaszkaiser** [comment]
Hi @reedwm 

The re-opening of name-scope when re-entering a variable scope is entirely on puropse. In this example:

```
with tf.variable_scope('a') as scope:
    v = tf.get_variable('v', [], initializer=tf.constant_initializer(42., tf.float32))
with tf.variable_scope(scope):
    w = v * 2
print(w.name)    # expected: a/mul:0
#result:  'a_1/mul:0'
```

the current result, `a_1/mul:0`, is entirely expected. Imagine you're sharing a large subgraph, a large LSTM cell or a whole net. When you re-enter the scope of that graph, you'd rather add a `_1` to the root scope than add it to every single op, right? (Note that every op in the graph must have a unique name, so the `_1` will appear somewhere if you're re-creating a subgraph.)

The problem you note appears in a situation where you re-enter the scope not to re-create a subgraph but to continue some construction. This used to be more rare than reusing before, but with layers it's becoming more and more common, am I understanding this right? In any case, I think there is a simple way that was designed to do what you want, namely jump back to the original name scope, it's through `scope.original_name_scope`. So you can just rewrite your above example like this:

```
with tf.variable_scope('a') as scope:
    v = tf.get_variable('v', [], initializer=tf.constant_initializer(42., tf.float32))
with tf.variable_scope(scope):
   with tf.name_scope(scope.original_name_scope):
     w = v * 2
print(w.name)
```

Does that work? I thought we were doing that everywhere in Layer class where it makes sense, but now I'm less sure. Can you check? I think this should make it possible to just make changes in Layer and not touch variable_scope, but maybe there's a bug somewhere?

**Comment by facaiy** [comment]
Hi, @lukaszkaiser. Could you take a look at my tiny example above, which indeed uses scope.original_name_scope in layer. Unfortunately, it couldn't solve the mismatch problem here.

**Comment by lukaszkaiser** [comment]
Which one do you mean? Sorry, could you paste it again?

**Comment by facaiy** [comment]
To help clarify our problem, I write a simpler version for `tf.layers.Layer`.  Please notice that  `a_1` name scope has been created in 1st layer. That's why for 2nd layer, name scope must start from `a_2`, while variable scope is from `a_1` (inconsistent scopes).

### code
```python
import tensorflow as tf

def print_tensors():
    print(tf.constant([1], name="t_const"))
    print(tf.Variable([1], name="t_var"))

def print_scope():
    print("variable_scope: {}, name_scope: {}".format(tf.get_variable_scope().name, tf.contrib.framework.get_name_scope()))

def layer(name):
    # `base._set_scope` method
    with tf.variable_scope(None, default_name=name) as scope:
        s = scope
        print_scope()

    # `base.add_variable` and `base.__call__` method
    with tf.variable_scope(s) as ss:
        print("---------------------")
        print("before using original_name_scope:")
        print_scope()
        with tf.name_scope(ss.original_name_scope) as n:
            print("after using original_name_scope:")
            print_scope()

with tf.Graph().as_default() as graph:
    print("1st layer:")
    a = layer("a")
    print("\n===============================\n")
    print("2nd layer:")
    a_1 = layer("a")
    print("\n===============================\n")
    print("3rd layer:")
    a_2 = layer("a")
```

### logs
```
1st layer:
variable_scope: a, name_scope: a
---------------------
before using original_name_scope:
variable_scope: a, name_scope: a_1
after using original_name_scope:
variable_scope: a, name_scope: a

===============================

2nd layer:
variable_scope: a_1, name_scope: a_2
---------------------
before using original_name_scope:
variable_scope: a_1, name_scope: a_1_1
after using original_name_scope:
variable_scope: a_1, name_scope: a_2

===============================

3rd layer:
variable_scope: a_2, name_scope: a_3
---------------------
before using original_name_scope:
variable_scope: a_2, name_scope: a_2_1
after using original_name_scope:
variable_scope: a_2, name_scope: a_3
```

**Comment by facaiy** [comment]
@lukaszkaiser name scope jumps from a to a_2 for 2nd layer, though original_name_scope is used

**Comment by lukaszkaiser** [comment]
Ah, this is a different problem, I see. Here is the summary: the first time you create a scope with default_name everything works fine, right? The second time, it creates a new variable_scope name `a_1` (it's done here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/variable_scope.py#L1827).

The problem after that is that `name_scope` cannot re-open the scope `a_1` any more because it was already used in the previous call. So it increments it again, creating `a_2`, the new name scope. Which is preserved by `original_name_scope`.

So the problem would be that by entering a variable scope we create a name scope that's grabbing a name, even if it's empty and there's another re-opened name_scope just after that. One solution could be to try to prevent that somehow by checking things in the name_scope handler. Or adding functionality to clean up the reserved names if name_scope is empty. In all cases, it seems like it could be handled by changes to name_scope without touching variable_scope -- which is good, since this doesn't risk breaking compatibility.

**Comment by facaiy** [comment]
Yes, exactly right!

**Comment by facaiy** [comment]
@lukaszkaiser How about adding a new parameter, say `auxiliary_name_scope`, for ` tf.variable_scope`:
+ `auxiliary_name_scope=True`, create new name scope as before by default.
+ `auxiliary_name_scope=None` or `auxiliary_name_scope=False`, don't create any name scope.
+ `auxiliary_name_scope=some_name_scope`, reuse it if `some_name_scope`  is `name_scope`.

If so, we can write one line code to reuse both variable_scope and its name_scope:

```python
with tf.variable_scope(s, auxiliary_name_scope=s.original_name_scope) as ss:
        # do something
```
or
```python
with tf.variable_scope(s, auxiliary_name_scope=None) as ss:
     with tf.name_scope(ss.original_name_scope) as n:
          # do something
```

**Comment by lukaszkaiser** [comment]
That looks fine to me provided Martin and others agree to the API change.

**Comment by facaiy** [comment]
OK. Since the change is easy to implement, I'd like to propose a PR later for further discussion.

**Comment by facaiy** [comment]
Hi, all. #15471 is added to resolve the issue, could you take a look and comment? Thanks.
