### ISSUE TITLE
In what cases a OpKernel instance may be accessed concurrently?

### ISSUE THREAD

**Issue by x10000year** [tensorflow/tensorflow#13423]
In the documentation for adding new op, it is said that Compute method of OpKernel should be thread safe, because instances of your OpKernel may be accessed concurrently. I want to know in what cases an instance may be accessed concurrently. If the graph has no loop or any other control flow,does this guarantee that every OpKernel instance is accessed only once for each forward/backward pass?

Thank you.

**Comment by yaroslavvb** [comment]
I think the issue here is that multiple session.run calls can run in parallel and reuse the same OpKernel

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
