### ISSUE TITLE
Tensorflow does NOT utilize the memory from two GPUs in Windows 10

### ISSUE THREAD

**Issue by ybsave** [tensorflow/tensorflow#13434]
Tensorflow Version 1.3.0
OS: Windows 10
GPUs: Nvidia Quadro M4000 * 2 with 8G GPU memory for each
GPU modes: one for WDDM, one for TCC

I tested the official codes at https://github.com/tensorflow/models/blob/master/official/resnet/imagenet_main.py

I just add the GPU constraints in the main function as:

	def main(unused_argv):
	  os.environ['TF_ENABLE_WINOGRAD_NONFUSED'] = '1'

          # For this line, visible_divice_list set to only "0" and "0, 1" can only support the same batch_size
	  config = tf.ConfigProto(gpu_options=tf.GPUOptions(visible_device_list='0, 1')) 

	  resnet_classifier = tf.estimator.Estimator(
		  model_fn=imagenet_model_fn, model_dir=FLAGS.model_dir,
		  config=tf.contrib.learn.RunConfig(session_config=config))

	  for cycle in range(FLAGS.train_steps // FLAGS.steps_per_eval):
		tensors_to_log = {
			'learning_rate': 'learning_rate',
			'cross_entropy': 'cross_entropy',
			'train_accuracy': 'train_accuracy'
		}

		logging_hook = tf.train.LoggingTensorHook(
			tensors=tensors_to_log, every_n_iter=100)

		print('Starting a training cycle.')
		resnet_classifier.train(
			input_fn=lambda: input_fn(tf.estimator.ModeKeys.TRAIN),
			steps=FLAGS.first_cycle_steps or FLAGS.steps_per_eval,
			hooks=[logging_hook])
		FLAGS.first_cycle_steps = None

		print('Starting to evaluate.')
		eval_results = resnet_classifier.evaluate(
		  input_fn=lambda: input_fn(tf.estimator.ModeKeys.EVAL))
		print(eval_results)

In the training process, if I set the visible device list to "0, 1" or "0" only, both can run successfully with batch_size=48, but BOTH failed with batch_size=49! This indicates that the second GPU's memory is not utilized, as batch size could not be bigger when using two GPUs. I have use Nvidia-smi to confirm that only one or two GPUs are used in the above experiments.

My questions are:
1. Is there any way that I can use bigger batch_size when using two GPUs?
2. If the answer for Q1 is No in Windows, is there any way to do it in Linux? I am not familiar with Linux. In Linux, can I set all GPUs to TCC mode? Will the batch size be bigger when two GPUs are both in TCC mode? 

Thank you.

**Comment by zyavrik** [comment]
Very important question! Because batch size is everything in deep learning! But nobody cares... Why?

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

That said, I believe there is a misunderstanding here. TensorFlow does not automatically split a batch onto all available GPUs.  If you want to use multiple GPUs, at this time you must have your `model_fn` specify how to split the computation across multiple GPUs. See https://www.tensorflow.org/tutorials/using_gpu#using_multiple_gpus

Hope

**Comment by ybsave** [comment]
I suppose the Tensorflow is automatically doing this according to the manual. Therefore, I still believe it is a bug; or at least, I want to request this feature, as this is a commonly used issue for many users. Therefore, I think this question is better belonging to github than StackOverflow.

**Comment by asimshankar** [comment]
@ybsave : You might find some interesting information here: https://www.tensorflow.org/performance/performance_models#variable_distribution_and_gradient_aggregation 

We're making the process smoother, but at this point stackoverflow and/or the link above

Hope that helps

**Comment by ybsave** [comment]
@asimshankar Thank you very much. These materials seem really helpful.

**Comment by ybsave** [comment]
I have tried to distributed the data batch on two GPUs and the message does show allocation on two GPUs, but the problem still exists.

My modified codes are:
	_DEVICE_LIST = ['/gpu:0', '/gpu:1']
	def imagenet_model_fn(features, labels, mode):
	  split_batch = tf.split(features, len(_DEVICE_LIST))
	  split_labels = tf.split(labels, len(_DEVICE_LIST))

	  all_predictions = {
		'classes': [],
		'probabilities': []
	  }
	  all_cross_entropy = []
	  all_reg_loss = []

	  with tf.variable_scope(tf.get_variable_scope()):
		for dev_idx, (device, device_features, device_labels) in enumerate(zip(
		  _DEVICE_LIST, split_batch, split_labels)):
		  with tf.device(device):
			logits = network(inputs=device_features,
							 is_training=(mode == tf.estimator.ModeKeys.TRAIN))

			print(tf.argmax(logits, axis=1))
			all_predictions['classes'] = tf.concat([all_predictions['classes'],
													tf.argmax(logits, axis=1)], 0)
			print(all_predictions['classes'])
			all_predictions['probabilities'] = tf.concat(
			  [all_predictions['probabilities'], tf.argmax(logits, axis=1)], 0)
			
			if mode == tf.estimator.ModeKeys.TRAIN:
			  # Calculate loss, which includes softmax cross entropy and L2 regularization.
			  cross_entropy = tf.losses.softmax_cross_entropy(
				  logits=logits, onehot_labels=device_labels)
			  reg_loss = FLAGS.weight_decay * tf.add_n(
				[tf.nn.l2_loss(v) for v in tf.trainable_variables()])
			  
			  all_cross_entropy.append(cross_entropy)
			  all_reg_loss.append(reg_loss)

			tf.get_variable_scope().reuse_variables()

	  total_cross_entropy = tf.add_n(all_cross_entropy)
	  total_reg_loss = tf.add_n(all_reg_loss)
	  total_loss = total_cross_entropy + total_reg_loss

	  # Create a tensor named cross_entropy for logging purposes.
	  tf.identity(total_cross_entropy, name='cross_entropy')
	  tf.summary.scalar('cross_entropy', total_cross_entropy)

	  if mode == tf.estimator.ModeKeys.TRAIN:
		global_step = tf.train.get_or_create_global_step()

		# Multiply the learning rate by 0.1 at 30, 60, 120, and 150 epochs.
		boundaries = [
			int(batches_per_epoch * epoch) for epoch in [30, 60, 120, 150]]
		values = [
			_INITIAL_LEARNING_RATE * decay for decay in [1, 0.1, 0.01, 1e-3, 1e-4]]
		learning_rate = tf.train.piecewise_constant(
			tf.cast(global_step, tf.int32), boundaries, values)

		optimizer = tf.train.MomentumOptimizer(
			learning_rate=learning_rate,
			momentum=_MOMENTUM)

		# Batch norm requires update_ops to be added as a train_op dependency.
		update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
		with tf.control_dependencies(update_ops):
		  train_op = optimizer.minimize(total_loss, global_step)
	  else:
		train_op = None

	  return tf.estimator.EstimatorSpec(
		  mode=mode,
		  predictions=all_predictions,
		  loss=total_loss,
		  train_op=train_op)

The outputs do print the GPU locations for the two image features split set as:
	Tensor("ArgMax:0", dtype=int64, device=/device:GPU:0)
	Tensor("concat:0", shape=(?,), dtype=int64, device=/device:GPU:0)
	Tensor("ArgMax_3:0", dtype=int64, device=/device:GPU:1)
	Tensor("concat_2:0", shape=(?,), dtype=int64, device=/device:GPU:1)

but the memory allocation seems still only apply to one GPU only, as it prints that:
	Limit:                  8029880320
	InUse:                  8027254016
	MaxInUse:               8027255040
	NumAllocs:                    3744
	MaxAllocSize:           1427283712

Is there any way to use larger batch sizes for two GPUs? Is there any bug in my modified codes? Thank you.

**Comment by ybsave** [comment]
@asimshankar Would you please re-open this issue? As shown above, the two GPUs are actually both used, but it is weird that the batch size can still be the same as for single GPU.

I compared the above codes with two existing multi-GPU codes at:
https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py
https://github.com/tensorflow/models/blob/f87a58cd96d45de73c9a8330a06b2ab56749a7fa/research/inception/inception/imagenet_train.py 

My codes are just similar copy from those, but it still cannot support larger batch size.

To be clear, although those examples and the link you provided show how to "USE" multiple GPUs, but my mimic does not provide "LARGER batch size" even though the memory allocation does perform on two GPUs and shown above!

I cannot find a reasonable explanation for this problem. Therefore, I request to re-open this issue. Thanks.

**Comment by asimshankar** [comment]
Could you be a bit more specific on what the problem is?
In particular, please fill out all the details asked for in the new issue template, which include lots of metadata about your setup and instructions to reproduce the problem (for example, a single command line that one could run to reproduce the problem).

From what is described, it is hard to determine what the problem may be. For example, what error are you getting? How big are the input tensors?  Are there any other live tensors/variables etc. that are holding on to memory in GPU (hard to tell since I can't see the full code that's running this)? Is it possible that your `features` and `labels` tensors are placed on CPU and you're running out of host memory?

For example, to demonstrate that you can do more with two GPUs than one, consider the following:

```python
GPU_MEMORY_BYTES = 8 * 2**30 # Assuming your GPU has 8GB of memory, adjust accordingly

# Number of float32 elements (4 bytes) that consume 80% of GPU memory
NUM_ELEMS = (8 * GPU_MEMORY_BYTES / 10) / 4

with tf.device("/gpu:0"):
  t0 = tf.ones([NUM_ELEMS])  # Tensor that consumes 80% of GPU0's memory
  s0 = tf.reduce_sum(t0)
with tf.device("/gpu:1"):
  t1 = tf.ones([NUM_ELEMS])  # Tensor that consumes 80% of GPU1's memory
  s1 = tf.reduce_sum(t1)
s = tf.add(s0, s1)

with tf.Session() as sess:
  print(sess.run(s))
```
Computing `s` requires more than one GPU worth of memory, but with the computation and input split between two GPUs, this will succeed. As opposed to trying to do the following on a single GPU:

```
with tf.device("/gpu:0"):
  t = tf.ones([2 * NUM_ELEMS])
  s = tf.reduced_sum(t)
with tf.Session() as sess:
  print(sess.run(s)) # This should fail since it consumes more memory than exists in the GPU
```

**Comment by ybsave** [comment]
@asimshankar Thanks for your explanation. The codes I used are exactly the same as in https://github.com/tensorflow/models/blob/master/official/resnet/imagenet_main.py.

I only modified the "resnet_model_fn" for only a few lines (I labeled below).
	def resnet_model_fn(features, labels, mode):
	  """ Our model_fn for ResNet to be used with our Estimator."""
	  tf.summary.image('images', features, max_outputs=6)

	  with tf.device('/cpu:0'):    #modified by me
		all_cross_entropy = []   #modified by me
		with tf.device('/gpu:0'):  #modified by me
		  logits = network(
			inputs=features, is_training=(mode == tf.estimator.ModeKeys.TRAIN))
		  
		  predictions = {
			'classes': tf.argmax(logits, axis=1),
			'probabilities': tf.nn.softmax(logits, name='softmax_tensor')
		  }

		  if mode == tf.estimator.ModeKeys.PREDICT:
			return tf.estimator.EstimatorSpec(mode=mode, predictions=predictions)

		  # Calculate loss, which includes softmax cross entropy and L2 regularization.
		  cross_entropy = tf.losses.softmax_cross_entropy(
			logits=logits, onehot_labels=labels)

		  all_cross_entropy.append(cross_entropy)   #modified by me

		total_entropy = tf.add_n(all_cross_entropy)  #modified by me
		# Create a tensor named cross_entropy for logging purposes.
		tf.identity(total_entropy, name='cross_entropy')  #modified by me
		tf.summary.scalar('cross_entropy', total_entropy)  #modified by me

		# Add weight decay to the loss. We perform weight decay on all trainable
		# variables, which includes batch norm beta and gamma variables.
		reg_loss = FLAGS.weight_decay * tf.add_n(
		  [tf.nn.l2_loss(v) for v in tf.trainable_variables()])
		tf.summary.scalar('reg_loss', reg_loss)

		loss = total_entropy + reg_loss  #modified by me
		tf.summary.scalar('total_loss', loss)

		if mode == tf.estimator.ModeKeys.TRAIN:
		  global_step = tf.train.get_or_create_global_step()

		  # Multiply the learning rate by 0.1 at 30, 60, 120, and 150 epochs.
		  boundaries = [
			int(batches_per_epoch * epoch) for epoch in [30, 60, 120, 150]]
		  values = [
			_INITIAL_LEARNING_RATE * decay for decay in [1, 0.1, 0.01, 1e-3, 1e-4]]
		  learning_rate = tf.train.piecewise_constant(
			tf.cast(global_step, tf.int32), boundaries, values)

		  # Create a tensor named learning_rate for logging purposes.
		  tf.identity(learning_rate, name='learning_rate')
		  tf.summary.scalar('learning_rate', learning_rate)

		  optimizer = tf.train.MomentumOptimizer(
			learning_rate=learning_rate,
			momentum=_MOMENTUM)
		  
		  # Batch norm requires update_ops to be added as a train_op dependency.
		  update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
		  with tf.control_dependencies(update_ops):
			train_op = optimizer.minimize(loss, global_step)
		else:
		  train_op = None

		accuracy = tf.metrics.accuracy(
		  tf.argmax(labels, axis=1), predictions['classes'])
		metrics = {'accuracy': accuracy}

		# Create a tensor named train_accuracy for logging purposes.
		tf.identity(accuracy[1], name='train_accuracy')
		tf.summary.scalar('train_accuracy', accuracy[1])

		return tf.estimator.EstimatorSpec(
		  mode=mode,
		  predictions=predictions,
		  loss=loss,
		  train_op=train_op,
		  eval_metric_ops=metrics)

However, the error still shows:
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

If I remove my added cpu, gpu appointment, the codes have no problem to run. Is it possibly because some communications problem between CPU & GPU? What should I do for correct one?

I tried hardly to search for examples (multi-GPU using Estimator); however, I can only find how to distribute different layers of network at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/multiple_gpu.py. But I cannot find any example of splitting data into multi-GPU using Estimator. Would you please give me some help? Thank you so much.

**Comment by asimshankar** [comment]
@ybsave : I'm confused, I thought the issue was filed about GPU memory utilization, while the error you describe now seems orthogonal?

If that is indeed the case, please file a separate issue/stackoverflow question about that so we can keep discussion on this thread focused on the question raised at the beginning (and mentioned in the summary description)

**Comment by ybsave** [comment]
@asimshankar Yes, this seems a separate issue. I will submit another new issue. The reason for that is when I utilized two GPUs according to your suggestion, it does work and can support bigger batch size, but a NaN error occurs. After tracing back, I find the minimum modification of codes (above) already leads to the same error. I will update this multi-GPU issue later after the new problem solved. Thank you.

**Comment by ybsave** [comment]
I finally made a successful running codes which now use double batch size on both GPUs now. I have double checked that both GPUs are in use now. Thanks for all the help. The revised codes are:

	def average_gradients(tower_grads):
	  """Calculate the average gradient for each shared variable across all towers.
	  Note that this function provides a synchronization point across all towers.
	  Args:
		tower_grads: List of lists of (gradient, variable) tuples. The outer list
		  is over individual gradients. The inner list is over the gradient
		  calculation for each tower.
	  Returns:
		 List of pairs of (gradient, variable) where the gradient has been averaged
		 across all towers.
	  """
	  average_grads = []
	  for grad_and_vars in zip(*tower_grads):
		# Note that each grad_and_vars looks like the following:
		#   ((grad0_gpu0, var0_gpu0), ... , (grad0_gpuN, var0_gpuN))
		grads = []
		for g, _ in grad_and_vars:
		  # Add 0 dimension to the gradients to represent the tower.
		  expanded_g = tf.expand_dims(g, 0)

		  # Append on a 'tower' dimension which we will average over below.
		  grads.append(expanded_g)

		# Average over the 'tower' dimension.
		grad = tf.concat(axis=0, values=grads)
		grad = tf.reduce_mean(grad, 0)

		# Keep in mind that the Variables are redundant because they are shared
		# across towers. So .. we will just return the first tower's pointer to
		# the Variable.
		v = grad_and_vars[0][1]
		grad_and_var = (grad, v)
		average_grads.append(grad_and_var)
	  return average_grads


	def imagenet_model_fn(features, labels, mode):
	  """ Our model_fn for ResNet to be used with our Estimator."""
	  tf.summary.image('images', features, max_outputs=6)

	  with tf.device('/cpu:0'):
		split_batch = tf.split(features, len(_DEVICE_LIST))
		split_labels = tf.split(labels, len(_DEVICE_LIST))
		
		if mode == tf.estimator.ModeKeys.TRAIN:
		  global_step = tf.train.get_or_create_global_step()

		  # Multiply the learning rate by 0.1 at 30, 60, 120, and 150 epochs.
		  boundaries = [
			int(batches_per_epoch * epoch) for epoch in [30, 60, 120, 150]]
		  values = [
			_INITIAL_LEARNING_RATE * decay for decay in [1, 0.1, 0.01, 1e-3, 1e-4]]
		  learning_rate = tf.train.piecewise_constant(
			tf.cast(global_step, tf.int32), boundaries, values)

		  # Create a tensor named learning_rate for logging purposes.
		  tf.identity(learning_rate, name='learning_rate')
		  tf.summary.scalar('learning_rate', learning_rate)

		  optimizer = tf.train.MomentumOptimizer(
			learning_rate=learning_rate,
			momentum=_MOMENTUM)

		tower_grads = []
		tower_cross_entropy = []
		tower_reg_loss = []
		tower_accuracy = []

		with tf.variable_scope(tf.get_variable_scope()):
		  for dev_idx, (device, device_features, device_labels) in enumerate(zip(
			_DEVICE_LIST, split_batch, split_labels)):
			with tf.device(device):
			  with tf.name_scope('device_%d' % dev_idx):
				logits = network(inputs=device_features,
								 is_training=(mode == tf.estimator.ModeKeys.TRAIN))

				tf.get_variable_scope().reuse_variables()
		  
				predictions = {
				  'classes': tf.argmax(logits, axis=1),
				  'probabilities': tf.nn.softmax(logits, name='softmax_tensor')
				}

				cross_entropy = tf.losses.softmax_cross_entropy(
				  logits=logits, onehot_labels=device_labels)
				tower_cross_entropy.append(cross_entropy)

				reg_loss = 0.5 * FLAGS.weight_decay * tf.add_n(
				  [tf.nn.l2_loss(v) for v in tf.trainable_variables()])
				tower_reg_loss.append(reg_loss)            

				loss = cross_entropy + reg_loss

				if mode == tf.estimator.ModeKeys.TRAIN:          
				  grads = optimizer.compute_gradients(loss)
				  tower_grads.append(grads)

				accuracy = tf.metrics.accuracy(
				  tf.argmax(device_labels, axis=1), predictions['classes'])
				metrics = {'accuracy': accuracy}
				tower_accuracy.append(accuracy[1])

		cross_entropy = tf.add_n(tower_cross_entropy)
		tf.identity(cross_entropy, name='cross_entropy')
		tf.summary.scalar('cross_entropy', cross_entropy)

		reg_loss = tf.add_n(tower_reg_loss)
		tf.summary.scalar('reg_loss', reg_loss)

		loss = cross_entropy + reg_loss
		tf.summary.scalar('total_loss', loss)
		  
		if mode == tf.estimator.ModeKeys.TRAIN:
		  accuracy = tf.reduce_mean(tower_accuracy)
		  tf.identity(accuracy, name='train_accuracy')
		  tf.summary.scalar('train_accuracy', accuracy)
		  
		  # Batch norm requires update_ops to be added as a train_op dependency.
		  update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
		  with tf.control_dependencies(update_ops):
			grads = average_gradients(tower_grads)
			train_op = optimizer.apply_gradients(grads, global_step=global_step)
		else:
		  train_op = None

		return tf.estimator.EstimatorSpec(
		  mode=mode,
		  predictions=predictions,
		  loss=loss,
		  train_op=train_op,
		  eval_metric_ops=metrics)

**Comment by zyavrik** [comment]
Why does nobody want to include that code to the standard tensorflow package to make it work on multiple GPUs automatically???

**Comment by scheng123** [comment]
Because. Because of customization and it's different for scenarios. How about you tell us a foolproof idea that would be the most efficient. Submit it through a feature request.

There is no "correct way" of doing things. I guess you can say tensorflow kinda automatically does it for you, just that you have to select which one suits best for your needs. See https://www.tensorflow.org/guide/distributed_training
