### ISSUE TITLE
op.device no longer showing which device an op is actually placed on

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#1344]
Using the latest builds, it appears that `op.device` now returns the device that an op is supposed to be placed on, i.e. what the user specifies, as opposed to what it is actually placed on. I believe this is true because when I set `allow_soft_placement` to `False` when starting a `Session`, some ops, for example `global_step`, cannot be placed on the GPU. But if I assign them to the GPU and then allow soft placement, `op.device` returns `/gpu:0` for ops that were previously not placeable on the GPU.

This is a break from previous behavior, which showed the actual device an op is placed on. The new behavior makes it very difficult to debug device placement. Is there are any way to probe the actual device that an op is placed on?

P.S. I'm using a device function for my placement logic. Something like:

```
def _device_function(op):
    if complicated_logic_true:
        return '/cpu:0'
    else:
        return '/gpu:0'
```

**Comment by vrv** [comment]
op.device reflects what the user specified, because it is part of the GraphDef that is sent to TensorFlow.

If you use log_device_placement in the ConfigProto, you will get a log of what the assigned device is (after applying all soft_placement rules, etc).  I don't think op.device ever could reflect what the runtime actually did.

**Comment by alquraishi** [comment]
I may have been mistaken about the previous behavior. I do know about `log_device_placement`, but prefer op.device as it's easier to work with it programmatically, especially with very large unfolded graphs that have hundreds of thousands of nodes. If there's some way to provide an alternative mechanism to probe actual device placement programmatically from within python that would be fantastic.

**Comment by mrry** [comment]
An update here: you can call `Session.run()` passing a `RunOptions` protobuf that requests a trace, and fills in a `RunMetadata` protobuf with details of all the ops that ran, on which device they ran, and how long they took. I think this gives you the programmatic access that you're looking for. Here's an example:

https://github.com/tensorflow/tensorflow/blob/6f90ede2496134777a948fea872b17a67b4f6ef2/tensorflow/python/client/session_test.py#L913

**Comment by alquraishi** [comment]
Thanks, will take a look.

**Comment by atinzad** [comment]
Is there a way to check the device using an op.device? Note that after using the with tf.device(device_name) and then checking op.device all I observe is an empty string.

Is there a way to check device placement without referring to the logs (but rather through attributes of the operation(s))  ?

Note I am using Tensorflow v1.1.0 Thanks

**Comment by mrry** [comment]
@atinzad No, the `op.device` property is never filled in with the true device on which an op ran (and technically the op could be placed on multiple different devices, depending on how your session is configured). Using `RunOptions` and `RunMetadata` to extract the partitioned subgraphs [as I suggested above](https://github.com/tensorflow/tensorflow/issues/1344#issuecomment-210641516) is the best way to get this information programmatically.
