### ISSUE TITLE
Building for tensorflow.dll failed because architectures < sm35 are not supported

### ISSUE THREAD

**Issue by helen-medina** [tensorflow/tensorflow#13448]
Hi,
I am trying to compile the dynamic library tensorflow.dll with cmake for windows 10 and GPU enabled. However, the library tf_core_gpu_kernels failed because of the following error:
"Unable to compile CudaAtomicAdd for complex64  architectures < sm35 are not supported"

I am building for a device with a card graphic Gforce 1080Ti (compute 61). So my configuration in Visual Studio is:
Cuda C/C++-> Device -> Code generation: compute_61, sm_61. But, I am still having the error.
Is it related with any other configuration?. It would be great if someone could help with this issue.

Thanks in advance.

**Comment by ebrevdo** [comment]
Although I added the codepath for other compute values over the weekend (just git pull and you'll see the new fixed code), and it should compile for you now, it appears that the check isn't quite right in windows.  @mrry any reason why [this check](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/cuda_kernel_helper.h#L440) would fail in windows?

The reason I ask, is there are other functions in there, like ldg, which should be properly calling the __ldg intrinsic for a speedup on SM35+, but if those are falling back to the SM30 versions then the windows build could be unintentionally running slower GPU kernels.

**Comment by mrry** [comment]
[This line](http://google3/third_party/tensorflow/contrib/cmake/CMakeLists.txt?l=227&rcl=170746452) controls how `nvcc` builds on Windows. It looks like we build for `sm_30`, `sm_35` and `sm_52`. Is it possible that `__CUDA_ARCH__` takes the lowest of these? (I'm not particularly familiar with `nvcc` options, so you might need to find someone else to take a look....)

**Comment by helen-medina** [comment]
Hi,
Thank you for your help.

I have rebased ("git pull") and I have rebuilt again, but I am afraid I have more errors than before.
Also, this time I have the error below
/MatrixBase.h(472): fatal error C1060: insufficient heap space in compiler

I have faced this last error before,  when I was building the tensorflow library with GPU, however it works fine building it for CPU.
I am not sure if the issue is related with cmake or GPU. But, it seems some people have been able to build the library for GPU. Do you have any suggestion. I would be appreciated any help.

Note:
mrry, The link you added it doesn´t worked. Could it be possible to added here ?

Thanks in advance.

**Comment by helen-medina** [comment]
Hi again,

I have change my cudnn for the one recommended (5.1) and swigwin-3.0.10. Also, I have generated the project again after I rebased. It is building with no errors yet. So, I will let you know if it works.

Thanks again.

**Comment by helen-medina** [comment]
I build the project and I don´t have the previous error anymore. However, the tensorflow.dll wasn´t generated because of the following errors:

Line 44287: 147>  C:/Demos/TF_DLL_GPU/tensorflow/tensorflow/core/kernels/topk_op_gpu.cu.cc(550): note: vea la referencia a la creación de instancias de plantilla de función 'cudaError tensorflow::impl::LaunchTopKKernel<const T>(const cudaStream_t &,int,const T *,int,int,int,bool,T *,int *)' que se está compilando
	Line 49887: 151>cuda_dnn.obj : error LNK2019: símbolo externo cudnnConvolutionBiasActivationForward sin resolver al que se hace referencia en la función "private: bool __cdecl perftools::gputools::cuda::CudnnSupport::DoFusedConvolveImpl<signed char,float,float,5,4>(class perftools::gputools::Stream *,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::FilterDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,class perftools::gputools::dnn::ConvolutionDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,enum perftools::gputools::dnn::ActivationMode,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> *,class perftools::gputools::ScratchAllocator *,class perftools::gputools::dnn:...
	Line 49888: 152>cuda_dnn.obj : error LNK2019: símbolo externo cudnnConvolutionBiasActivationForward sin resolver al que se hace referencia en la función "private: bool __cdecl perftools::gputools::cuda::CudnnSupport::DoFusedConvolveImpl<signed char,float,float,5,4>(class perftools::gputools::Stream *,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::FilterDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,class perftools::gputools::dnn::ConvolutionDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,enum perftools::gputools::dnn::ActivationMode,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> *,class perftools::gputools::ScratchAllocator *,class perftools::gputools::dnn:...
	Line 49889: 150>cuda_dnn.obj : error LNK2019: símbolo externo cudnnConvolutionBiasActivationForward sin resolver al que se hace referencia en la función "private: bool __cdecl perftools::gputools::cuda::CudnnSupport::DoFusedConvolveImpl<signed char,float,float,5,4>(class perftools::gputools::Stream *,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::FilterDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,class perftools::gputools::dnn::ConvolutionDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,enum perftools::gputools::dnn::ActivationMode,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> *,class perftools::gputools::ScratchAllocator *,class perftools::gputools::dnn:...
	Line 49890: 151>cuda_dnn.obj : error LNK2019: símbolo externo cudnnSetRNNDescriptor_v6 sin resolver al que se hace referencia en la función "public: __cdecl perftools::gputools::cuda::CudnnRnnDescriptor::CudnnRnnDescriptor(class perftools::gputools::cuda::CUDAExecutor *,struct cudnnContext *,int,int,int,enum cudnnRNNInputMode_t,enum cudnnDirectionMode_t,enum cudnnRNNMode_t,enum cudnnDataType_t,float,unsigned __int64,class perftools::gputools::ScratchAllocator *)" (??0CudnnRnnDescriptor@cuda@gputools@perftools@@QEAA@PEAVCUDAExecutor@123@PEAUcudnnContext@@HHHW4cudnnRNNInputMode_t@@W4cudnnDirectionMode_t@@W4cudnnRNNMode_t@@W4cudnnDataType_t@@M_KPEAVScratchAllocator@23@@Z)
	Line 49891: 152>cuda_dnn.obj : error LNK2019: símbolo externo cudnnSetRNNDescriptor_v6 sin resolver al que se hace referencia en la función "public: __cdecl perftools::gputools::cuda::CudnnRnnDescriptor::CudnnRnnDescriptor(class perftools::gputools::cuda::CUDAExecutor *,struct cudnnContext *,int,int,int,enum cudnnRNNInputMode_t,enum cudnnDirectionMode_t,enum cudnnRNNMode_t,enum cudnnDataType_t,float,unsigned __int64,class perftools::gputools::ScratchAllocator *)" (??0CudnnRnnDescriptor@cuda@gputools@perftools@@QEAA@PEAVCUDAExecutor@123@PEAUcudnnContext@@HHHW4cudnnRNNInputMode_t@@W4cudnnDirectionMode_t@@W4cudnnRNNMode_t@@W4cudnnDataType_t@@M_KPEAVScratchAllocator@23@@Z)
	Line 49892: 150>cuda_dnn.obj : error LNK2019: símbolo externo cudnnSetRNNDescriptor_v6 sin resolver al que se hace referencia en la función "public: __cdecl perftools::gputools::cuda::CudnnRnnDescriptor::CudnnRnnDescriptor(class perftools::gputools::cuda::CUDAExecutor *,struct cudnnContext *,int,int,int,enum cudnnRNNInputMode_t,enum cudnnDirectionMode_t,enum cudnnRNNMode_t,enum cudnnDataType_t,float,unsigned __int64,class perftools::gputools::ScratchAllocator *)" (??0CudnnRnnDescriptor@cuda@gputools@perftools@@QEAA@PEAVCUDAExecutor@123@PEAUcudnnContext@@HHHW4cudnnRNNInputMode_t@@W4cudnnDirectionMode_t@@W4cudnnRNNMode_t@@W4cudnnDataType_t@@M_KPEAVScratchAllocator@23@@Z)
	Line 49893: 150>C:\Demos\TF_DLL_GPU\tensorflow\tensorflow\contrib\cmake\build\Release\summarize_graph.exe : fatal error LNK1120: 2 externos sin resolver
	Line 49894: 151>C:\Demos\TF_DLL_GPU\tensorflow\tensorflow\contrib\cmake\build\Release\compare_graphs.exe : fatal error LNK1120: 2 externos sin resolver
	Line 49895: 152>C:\Demos\TF_DLL_GPU\tensorflow\tensorflow\contrib\cmake\build\Release\benchmark_model.exe : fatal error LNK1120: 2 externos sin resolver
	Line 49896: 153>cuda_dnn.obj : error LNK2019: símbolo externo cudnnConvolutionBiasActivationForward sin resolver al que se hace referencia en la función "private: bool __cdecl perftools::gputools::cuda::CudnnSupport::DoFusedConvolveImpl<signed char,float,float,5,4>(class perftools::gputools::Stream *,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::FilterDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,class perftools::gputools::dnn::ConvolutionDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,enum perftools::gputools::dnn::ActivationMode,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> *,class perftools::gputools::ScratchAllocator *,class perftools::gputools::dnn:...
	Line 49897: 153>cuda_dnn.obj : error LNK2019: símbolo externo cudnnSetRNNDescriptor_v6 sin resolver al que se hace referencia en la función "public: __cdecl perftools::gputools::cuda::CudnnRnnDescriptor::CudnnRnnDescriptor(class perftools::gputools::cuda::CUDAExecutor *,struct cudnnContext *,int,int,int,enum cudnnRNNInputMode_t,enum cudnnDirectionMode_t,enum cudnnRNNMode_t,enum cudnnDataType_t,float,unsigned __int64,class perftools::gputools::ScratchAllocator *)" (??0CudnnRnnDescriptor@cuda@gputools@perftools@@QEAA@PEAVCUDAExecutor@123@PEAUcudnnContext@@HHHW4cudnnRNNInputMode_t@@W4cudnnDirectionMode_t@@W4cudnnRNNMode_t@@W4cudnnDataType_t@@M_KPEAVScratchAllocator@23@@Z)
	Line 49898: 153>C:\Demos\TF_DLL_GPU\tensorflow\tensorflow\contrib\cmake\build\Release\transform_graph.exe : fatal error LNK1120: 2 externos sin resolver
	Line 49928: 156>cuda_dnn.obj : error LNK2019: símbolo externo cudnnConvolutionBiasActivationForward sin resolver al que se hace referencia en la función "private: bool __cdecl perftools::gputools::cuda::CudnnSupport::DoFusedConvolveImpl<signed char,float,float,5,4>(class perftools::gputools::Stream *,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::FilterDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,class perftools::gputools::dnn::ConvolutionDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,enum perftools::gputools::dnn::ActivationMode,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> *,class perftools::gputools::ScratchAllocator *,class perftools::gputools::dnn:...
	Line 49929: 156>cuda_dnn.obj : error LNK2019: símbolo externo cudnnSetRNNDescriptor_v6 sin resolver al que se hace referencia en la función "public: __cdecl perftools::gputools::cuda::CudnnRnnDescriptor::CudnnRnnDescriptor(class perftools::gputools::cuda::CUDAExecutor *,struct cudnnContext *,int,int,int,enum cudnnRNNInputMode_t,enum cudnnDirectionMode_t,enum cudnnRNNMode_t,enum cudnnDataType_t,float,unsigned __int64,class perftools::gputools::ScratchAllocator *)" (??0CudnnRnnDescriptor@cuda@gputools@perftools@@QEAA@PEAVCUDAExecutor@123@PEAUcudnnContext@@HHHW4cudnnRNNInputMode_t@@W4cudnnDirectionMode_t@@W4cudnnRNNMode_t@@W4cudnnDataType_t@@M_KPEAVScratchAllocator@23@@Z)
	Line 49930: 156>C:\Demos\TF_DLL_GPU\tensorflow\tensorflow\contrib\cmake\build\Release\tf_label_image_example.exe : fatal error LNK1120: 2 externos sin resolver
	Line 49934: 157>cuda_dnn.obj : error LNK2019: símbolo externo cudnnConvolutionBiasActivationForward sin resolver al que se hace referencia en la función "private: bool __cdecl perftools::gputools::cuda::CudnnSupport::DoFusedConvolveImpl<signed char,float,float,5,4>(class perftools::gputools::Stream *,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::FilterDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,class perftools::gputools::dnn::ConvolutionDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,enum perftools::gputools::dnn::ActivationMode,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> *,class perftools::gputools::ScratchAllocator *,class perftools::gputools::dnn:...
	Line 49935: 157>cuda_dnn.obj : error LNK2019: símbolo externo cudnnSetRNNDescriptor_v6 sin resolver al que se hace referencia en la función "public: __cdecl perftools::gputools::cuda::CudnnRnnDescriptor::CudnnRnnDescriptor(class perftools::gputools::cuda::CUDAExecutor *,struct cudnnContext *,int,int,int,enum cudnnRNNInputMode_t,enum cudnnDirectionMode_t,enum cudnnRNNMode_t,enum cudnnDataType_t,float,unsigned __int64,class perftools::gputools::ScratchAllocator *)" (??0CudnnRnnDescriptor@cuda@gputools@perftools@@QEAA@PEAVCUDAExecutor@123@PEAUcudnnContext@@HHHW4cudnnRNNInputMode_t@@W4cudnnDirectionMode_t@@W4cudnnRNNMode_t@@W4cudnnDataType_t@@M_KPEAVScratchAllocator@23@@Z)
	Line 49936: 157>C:\Demos\TF_DLL_GPU\tensorflow\tensorflow\contrib\cmake\build\Release\tf_tutorials_example_trainer.exe : fatal error LNK1120: 2 externos sin resolver
	Line 50019: 161>c_api.cc.obj : error LNK2019: símbolo externo "class tensorflow::Status __cdecl tensorflow::ops::BuildWhileLoop(class tensorflow::Scope const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > const &,class std::function<class tensorflow::Status __cdecl(class tensorflow::Scope const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > const &,class tensorflow::Output *)> const &,class std::function<class tensorflow::Status __cdecl(class tensorflow::Scope const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > *)> const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > *,bool,class tensorflow::Output *)" (?BuildWhileLoop@ops@t...
	Line 50020: 161>while_gradients.obj : error LNK2001: símbolo externo "class tensorflow::Status __cdecl tensorflow::ops::BuildWhileLoop(class tensorflow::Scope const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > const &,class std::function<class tensorflow::Status __cdecl(class tensorflow::Scope const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > const &,class tensorflow::Output *)> const &,class std::function<class tensorflow::Status __cdecl(class tensorflow::Scope const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > *)> const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > *,bool,class tensorflow::Output *)" (?BuildWhileLoo...
	Line 50021: 161>cuda_dnn.obj : error LNK2019: símbolo externo cudnnConvolutionBiasActivationForward sin resolver al que se hace referencia en la función "private: bool __cdecl perftools::gputools::cuda::CudnnSupport::DoFusedConvolveImpl<signed char,float,float,5,4>(class perftools::gputools::Stream *,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::FilterDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,class perftools::gputools::dnn::ConvolutionDescriptor const &,class perftools::gputools::DeviceMemory<signed char> const &,float,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,enum perftools::gputools::dnn::ActivationMode,class perftools::gputools::dnn::BatchDescriptor const &,class perftools::gputools::DeviceMemory<signed char> *,class perftools::gputools::ScratchAllocator *,class perftools::gputools::dnn:...
	Line 50022: 161>cuda_dnn.obj : error LNK2019: símbolo externo cudnnSetRNNDescriptor_v6 sin resolver al que se hace referencia en la función "public: __cdecl perftools::gputools::cuda::CudnnRnnDescriptor::CudnnRnnDescriptor(class perftools::gputools::cuda::CUDAExecutor *,struct cudnnContext *,int,int,int,enum cudnnRNNInputMode_t,enum cudnnDirectionMode_t,enum cudnnRNNMode_t,enum cudnnDataType_t,float,unsigned __int64,class perftools::gputools::ScratchAllocator *)" (??0CudnnRnnDescriptor@cuda@gputools@perftools@@QEAA@PEAVCUDAExecutor@123@PEAUcudnnContext@@HHHW4cudnnRNNInputMode_t@@W4cudnnDirectionMode_t@@W4cudnnRNNMode_t@@W4cudnnDataType_t@@M_KPEAVScratchAllocator@23@@Z)
	Line 50023: 161>C:\Demos\TF_DLL_GPU\tensorflow\tensorflow\contrib\cmake\build\Release\tensorflow.dll : fatal error LNK1120: 3 externos sin resolver


Any help with this issue would be very much appreciated.

**Comment by helen-medina** [comment]
I have checked the linker and everything looks fine, apart from:
 wsock32.lib
ws2_32.lib
shlwapi.lib
advapi32.lib

I got rid of them, because they haven´t been created, and tensorflow is not complaing about them.

The issue see in:
1>c_api.cc.obj : error LNK2019: tensorflow::ops::BuildWhileLoop ...
1>while_gradients.obj : error LNK2001: tensorflow::ops::BuildWhileLoop ...
1>cuda_dnn.obj : error LNK2019: símbolo externo cudnnConvolutionBiasActivationForward ...
1>cuda_dnn.obj : error LNK2019: símbolo externo cudnnSetRNNDescriptor_v6 ... 
1>C:\Demos\TF_DLL_GPU\tensorflow\tensorflow\contrib\cmake\build\Release\tensorflow.dll : fatal error LNK1120: 3 externos sin resolver

The the libraries tf_c.lib, tf_cc.lib and tf_stream_executer have been created correctly, so not sure why tensorflow is complaying about c_api.cc , while_gradients and cuda_dnn.

Any ideas how to fix this issue?

Thanks for your time.

**Comment by mrry** [comment]
I think there are some object files missing from the `tensorflow_static` target in [`tf_shared_lib.cmake`](https://github.com/tensorflow/tensorflow/blob/635196732151e6d8638c189c52f4c4336ede81b6/tensorflow/contrib/cmake/tf_shared_lib.cmake). Can you try adding the following line [here](https://github.com/tensorflow/tensorflow/blob/635196732151e6d8638c189c52f4c4336ede81b6/tensorflow/contrib/cmake/tf_shared_lib.cmake#L38) and [here](https://github.com/tensorflow/tensorflow/blob/635196732151e6d8638c189c52f4c4336ede81b6/tensorflow/contrib/cmake/tf_shared_lib.cmake#L75)?

```
    $<TARGET_OBJECTS:tf_cc_while_loop>
```

The symbols `cudnnConvolutionBiasActivationForward` and `cudnnSetRNNDescriptor_v6` seem to be part of cuDNN 6. I'm not sure where you picked up the recommendation to use cuDNN 5.1, but I think that that might be incorrect. Upgrading to cuDNN 6 should fix this part of the build.

**Comment by helen-medina** [comment]
Hi mrry,
Thank you very much for your help. I have rebuilt and I have been able to generate the tensorflow.dll.
I have run the model resnet vs inception (trained with my own dataset) in a machine with card graphic GForce 1080Ti. The times measured to detect objects are below:
- CPU ~ 27.8 sec
- GPU ~ 6.79 sec

I can see with GPU enabled it works better, but still is not enough. Could you tell me please if there is any make it faster?

Thank you again for all help provided.

**Comment by mrry** [comment]
Glad to hear that it's building now! Since the original build problem is fixed, I'm going to close this issue.

It's difficult to guess reasons for poor performance, but I'd recommend that you take a look at the [performance guide](https://www.tensorflow.org/performance/performance_guide), and open a new issue if none of these suggestions help.

**Comment by helen-medina** [comment]
Ok. Thank you very much.

**Comment by cuevas1208** [comment]
@helen-medina what are the dependencies you use to run tensorflow-GPU models in visual studio?
it looks like I am missing something:
```
1>tf_core_kernels.lib(cudnn_rnn_ops.cc.obj) : error LNK2001: unresolved external symbol "public: virtual __cdecl perftools::gputools::ScratchAllocator::~ScratchAllocator(void)" (??1ScratchAllocator@gputools@perftools@@UEAA@XZ)
1>tf_core_kernels.lib(fft_ops.obj) : error LNK2001: unresolved external symbol "public: virtual __cdecl perftools::gputools::ScratchAllocator::~ScratchAllocator(void)" (??1ScratchAllocator@gputools@perftools@@UEAA@XZ)
1>tf_core_kernels.lib(conv_ops_3d.obj) : error LNK2001: unresolved external symbol "public: virtual __cdecl perftools::gputools::ScratchAllocator::~ScratchAllocator(void)" (??1ScratchAllocator@gputools@perftools@@UEAA@XZ)
1>tf_core_kernels.lib(conv_ops.obj) : error LNK2001: unresolved external symbol "public: virtual __cdecl perftools::gputools::ScratchAllocator::~ScratchAllocator(void)" (??1ScratchAllocator@gputools@perftools@@UEAA@XZ)
1>tf_core_kernels.lib(cudnn_rnn_ops.cc.obj) : error LNK2001: unresolved external symbol "public: class perftools::gputools::Stream & __cdecl perftools::gputools::Stream::ThenRnnForward(class perftools::gputools::dnn::RnnDescriptor const &,class perftools::gputools::dnn::RnnSequenceTensorDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::dnn::RnnSequenceTensorDescriptor const &,class perftools::gputools::DeviceMemory<float> *,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<float> *,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<float> *,bool,class perftools::gputools::ScratchAllocator *,class perftools::gputools::ScratchAllocator *)" (?ThenRnnForward@Stream@gputools@perftools@@QEAAAEAV123@AEBVRnnDescriptor@dnn@23@AEBVRnnSequenceTensorDescriptor@523@AEBV?$DeviceMemory@M@23@AEBVRnnStateTensorDescriptor@523@23221PEAV723@3434_NPEAVScratchAllocator@23@6@Z)
1>tf_core_kernels.lib(cudnn_rnn_ops.cc.obj) : error LNK2001: unresolved external symbol "public: class perftools::gputools::Stream & __cdecl perftools::gputools::Stream::ThenRnnForward(class perftools::gputools::dnn::RnnDescriptor const &,class perftools::gputools::dnn::RnnSequenceTensorDescriptor const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::dnn::RnnSequenceTensorDescriptor const &,class perftools::gputools::DeviceMemory<double> *,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<double> *,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<double> *,bool,class perftools::gputools::ScratchAllocator *,class perftools::gputools::ScratchAllocator *)" (?ThenRnnForward@Stream@gputools@perftools@@QEAAAEAV123@AEBVRnnDescriptor@dnn@23@AEBVRnnSequenceTensorDescriptor@523@AEBV?$DeviceMemory@N@23@AEBVRnnStateTensorDescriptor@523@23221PEAV723@3434_NPEAVScratchAllocator@23@6@Z)
1>tf_core_kernels.lib(cudnn_rnn_ops.cc.obj) : error LNK2001: unresolved external symbol "public: class perftools::gputools::Stream & __cdecl perftools::gputools::Stream::ThenRnnBackward(class perftools::gputools::dnn::RnnDescriptor const &,class perftools::gputools::dnn::RnnSequenceTensorDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::dnn::RnnSequenceTensorDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::DeviceMemory<float> const &,class perftools::gputools::DeviceMemory<float> *,class perftools::gputools::DeviceMemory<float> *,class perftools::gputools::DeviceMemory<float> *,class perftools::gputools::DeviceMemory<float> *,class perftools::gputools::DeviceMemory<unsigned char> *,class perftools::gputools::ScratchAllocator *)" (?ThenRnnBackward@Stream@gputools@perftools@@QEAAAEAV123@AEBVRnnDescriptor@dnn@23@AEBVRnnSequenceTensorDescriptor@523@AEBV?$DeviceMemory@M@23@AEBVRnnStateTensorDescriptor@523@2322123232222PEAV723@444PEAV?$DeviceMemory@E@23@PEAVScratchAllocator@23@@Z)
1>tf_core_kernels.lib(cudnn_rnn_ops.cc.obj) : error LNK2001: unresolved external symbol "public: class perftools::gputools::Stream & __cdecl perftools::gputools::Stream::ThenRnnBackward(class perftools::gputools::dnn::RnnDescriptor const &,class perftools::gputools::dnn::RnnSequenceTensorDescriptor const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::dnn::RnnSequenceTensorDescriptor const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::dnn::RnnStateTensorDescriptor const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::DeviceMemory<double> const &,class perftools::gputools::DeviceMemory<double> *,class perftools::gputools::DeviceMemory<double> *,class perftools::gputools::DeviceMemory<double> *,class perftools::gputools::DeviceMemory<double> *,class perftools::gputools::DeviceMemory<unsigned char> *,class perftools::gputools::ScratchAllocator *)" (?ThenRnnBackward@Stream@gputools@perftools@@QEAAAEAV123@AEBVRnnDescriptor@dnn@23@AEBVRnnSequenceTensorDescriptor@523@AEBV?$DeviceMemory@N@23@AEBVRnnStateTensorDescriptor@523@2322123232222PEAV723@444PEAV?$DeviceMemory@E@23@PEAVScratchAllocator@23@@Z)
1>tf_core_kernels.lib(cudnn_rnn_ops.cc.obj) : error LNK2001: unresolved external symbol "public: class perftools::gputools::port::StatusOr<class std::unique_ptr<class perftools::gputools::dnn::RnnDescriptor,struct std::default_delete<class perftools::gputools::dnn::RnnDescriptor> > > __cdecl perftools::gputools::StreamExecutor::createRnnDescriptor(int,int,int,enum perftools::gputools::dnn::RnnInputMode,enum perftools::gputools::dnn::RnnDirectionMode,enum perftools::gputools::dnn::RnnMode,enum perftools::gputools::dnn::DataType,float,unsigned __int64,class perftools::gputools::ScratchAllocator *)" (?createRnnDescriptor@StreamExecutor@gputools@perftools@@QEAA?AV?$StatusOr@V?$unique_ptr@VRnnDescriptor@dnn@gputools@perftools@@U?$default_delete@VRnnDescriptor@dnn@gputools@perftools@@@std@@@std@@@port@23@HHHW4RnnInputMode@dnn@23@W4RnnDirectionMode@723@W4RnnMode@723@W4DataType@723@M_KPEAVScratchAllocator@23@@Z)
1>tf_core_kernels.lib(cudnn_rnn_ops.cc.obj) : error LNK2001: unresolved external symbol "public: class perftools::gputools::port::StatusOr<class std::unique_ptr<class perftools::gputools::dnn::RnnSequenceTensorDescriptor,struct std::default_delete<class perftools::gputools::dnn::RnnSequenceTensorDescriptor> > > __cdecl perftools::gputools::StreamExecutor::createRnnSequenceTensorDescriptor(int,int,int,enum perftools::gputools::dnn::DataType)" (?createRnnSequenceTensorDescriptor@StreamExecutor@gputools@perftools@@QEAA?AV?$StatusOr@V?$unique_ptr@VRnnSequenceTensorDescriptor@dnn@gputools@perftools@@U?$default_delete@VRnnSequenceTensorDescriptor@dnn@gputools@perftools@@@std@@@std@@@port@23@HHHW4DataType@dnn@23@@Z)
1>tf_core_kernels.lib(cudnn_rnn_ops.cc.obj) : error LNK2001: unresolved external symbol "public: class perftools::gputools::port::StatusOr<class std::unique_ptr<class perftools::gputools::dnn::RnnStateTensorDescriptor,struct std::default_delete<class perftools::gputools::dnn::RnnStateTensorDescriptor> > > __cdecl perftools::gputools::StreamExecutor::createRnnStateTensorDescriptor(int,int,int,enum perftools::gputools::dnn::DataType)" (?createRnnStateTensorDescriptor@StreamExecutor@gputools@perftools@@QEAA?AV?$StatusOr@V?$unique_ptr@VRnnStateTensorDescriptor@dnn@gputools@perftools@@U?$default_delete@VRnnStateTensorDescriptor@dnn@gputools@perftools@@@std@@@std@@@port@23@HHHW4DataType@dnn@23@@Z)
1>tf_core_gpu_kernels.lib(tf_core_gpu_kernels_generated_avgpooling_op_gpu.cu.cc.obj) : error LNK2001: unresolved external symbol cudaMemcpyAsync
1>tf_core_gpu_kernels.lib(tf_core_gpu_kernels_generated_argmax_op_gpu.cu.cc.obj) : error LNK2001: unresolved external symbol cudaMemcpyAsync
1>tf_core_gpu_kernels.lib(tf_core_gpu_kernels_generated_adjust_contrast_op_gpu.cu.cc.obj) : error LNK2001: unresolved external symbol cudaMemcpyAsync
1>tf_core_gpu_kernels.lib(tf_core_gpu_kernels_generated_concat_lib_gpu_impl.cu.cc.obj) : error LNK2001: unresolved external symbol cudaMemcpyAsync
```
