### ISSUE TITLE
Feature request: Allow for custom hooks in Slim's `evaluate_once` to support TFDBG

### ISSUE THREAD

**Issue by rjbruin** [tensorflow/tensorflow#13444]
### System information
- **TensorFlow version**: `v1.3.0-rc2-20-g0787eee`

### Describe the problem
The evaluation functions provided by `contrib.slim.python.slim` are wrappers around methods from `contrib.training.python.training`. `contrib.slim.python.slim.evaluation_loop` provides argument `hooks` which attaches custom hooks to the evaluation loop. This can be used to hook the TFDBG debugger into evaluation. `contrib.slim.python.slim.evaluation_once` however does not provide the argument, even though the underlying `contrib.training.python.training.evaluate_once` does support the argument. The code to extend the hooks with custom hooks is already there in `contrib.slim.python.slim.evaluation_loop` but that fix somehow was not applied to `contrib.slim.python.slim.evaluation_once`.

The request is to implement the addition of custom hooks to `contrib.slim.python.slim.evaluation_once` so that TFDBG can be used with this method. This is a really easy fix that adds a lot of functionality.

**Comment by rjbruin** [comment]
@caisq Sorry to bother you, but could you give an indication of when you could get to this? It would really help me to have this in TensorFlow. :)

**Comment by caisq** [comment]
@rjbruin Sorry about the delay.

@sguada @rjbruin's FR makes sense to me. The change should be small and straightforward. I'll send you a change list to you soon.
