### ISSUE TITLE
[FeatureRequest] TFDBG change default limit depth for recursive checking tensors

### ISSUE THREAD

**Issue by kcyu1993** [tensorflow/tensorflow#13449]
Hi,

Recently, I was debugging with TFDBG for a neural network training. It is pretty useful, however, when I want to check some ill-conditioned tensors and their parent, by default TFDBG give me its parents up to a recursive level of 20, i.e. limit depth=20 by default. I could solve the problem by putting a "-d 1" to check its immediate parent each time but it is quite annoying to input this every time.

Would you consider adding a feature in this TFDBG allowing us to set a default value for recursive retrieval of a tensor's input nodes?

My TensorFlow version is
```('v1.3.0-rc2-20-g0787eee', '1.3.0')```

Here is an example of tracing a node's inputs when running the TFDBG currently 

``` 
Inputs to node "node name" (Depth limit = 20, controlled input included )
...
... some detail information
...
```
for command  ```>tfdbg li -c -r "node name" ```

**Comment by caisq** [comment]
Thanks for the feature request @kcyu1993 . I'll try to get that implemented at HEAD this week.
