### ISSUE TITLE
How to use config.gpu_options.per_process_gpu_memory_fraction in tf.estimator.Estimator(config=config)

### ISSUE THREAD

**Issue by chihyuwang** [tensorflow/tensorflow#13458]
I want to limit the total memory of each GPU in mnist,
https://www.tensorflow.org/tutorials/using_gpu

config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.4
session = tf.Session(config=config, ...)

and I added the above code to the mnis.py
https://github.com/tensorflow/models/tree/master/official/mnist

here is the modified code in mnis.py :
def main(unused_argv):

  config = tf.ConfigProto()
  config.gpu_options.per_process_gpu_memory_fraction = 0.4

  mnist_classifier = tf.estimator.Estimator(
      model_fn=mnist_model_fn, model_dir=FLAGS.model_dir,config=config)

but I get the below error:

Traceback (most recent call last):
  File "mnist.py", line 231, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "mnist.py", line 206, in main
    model_fn=mnist_model_fn, model_dir=FLAGS.model_dir,config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 142, in __init__
    config)
ValueError: config must be an instance of RunConfig, but provided gpu_options {
  per_process_gpu_memory_fraction: 0.4
}
.

My question is :
How to use config.gpu_options.per_process_gpu_memory_fraction in tf.estimator.Estimator(config=config)

**Comment by asimshankar** [comment]
`tf.estimator.Estimator` [expects a `RunConfig`](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#class_estimator) object as its argument. [`RunConfig`](https://www.tensorflow.org/api_docs/python/tf/estimator/RunConfig) in-turn contains the `ConfigProto` as `session_config`. So you could do something like the following:

```python
mnist_classifier = tf.estimator.Estimator(
  model_fn=mnist_model_fn, 
  model_dir=FLAGS.model_dir,
  config=tf.contrib.learn.RunConfig(session_config=config))
```

See docs for [`tf.contrib.learn.RunConfig`](https://www.tensorflow.org/api_docs/python/tf/contrib/learn/RunConfig) for details.

Though, I believe this complexity is in the process of being reduced.
@ispirmustafa : Does one have to use `tf.contrib.learn.RunConfig` to create an estimator with a specific `ConfigProto` as mentioned above? Or is there an alternative?

Hope that helps.

**Comment by chihyuwang** [comment]
it works.
thanks for your great help.

**Comment by ispirmustafa** [comment]
Yes, RunConfig is the way to add change arguments such as session_config, saving intervals, ...

**Comment by cipri-tom** [comment]
@asimshankar what is the difference between the contrib and the Estimator version of RunConfig ? You link to one, but give an example that is using the other. Should they be considered equivalent ?

**Comment by ispirmustafa** [comment]
@cipri-tom please use tf.estimator.* version. We'll deprecate contrib version of runconfig in coming releases.

**Comment by jidebingfeng** [comment]
it works.
thank you very much.
