### ISSUE TITLE
contrib/verbs only works on GPU

### ISSUE THREAD

**Issue by dariavel** [tensorflow/tensorflow#13466]
### System information
- **OS Linux readhat** 7.3
- **TensorFlow** installed from source
- **TensorFlow version** 1.3.0
- **Python version**:  2.7.5
- **Bazel version**:
Build label: 0.5.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Aug 25 10:00:00 2017 (1503655200)
Build timestamp: 1503655200
Build timestamp as int: 1503655200

- **CUDA/cuDNN version**: no CUDA
- **GPU model and memory**: no GPU
- **Exact command to reproduce**: Compilation with the following command fails:

 bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

ERROR: /root/tensorflow/tensorflow/contrib/verbs/BUILD:133:1: C++ compilation of rule '//tensorflow/contrib/verbs:rdma' failed (Exit 1).
In file included from ./tensorflow/core/platform/stream_executor.h:26:0,
                 from ./tensorflow/core/common_runtime/gpu/gpu_util.h:23,
                 from tensorflow/contrib/verbs/rdma.cc:24:
./tensorflow/stream_executor/dso_loader.h:32:30: fatal error: cuda/cuda_config.h: No such file or directory
 #include "cuda/cuda_config.h"
                              ^
compilation terminated.

The ./configure is done with all the defaults except enabling verbs.

Reverting the following commit fixes compilation:
commit 0d864630161d9f3b9eaef0b7c6ce7443654df97a
Author: A. Unique TensorFlower <gardener@tensorflow.org>
Date:   Fri Sep 22 13:48:33 2017 -0700

    Move GPU-specific dependencies of core/grappler:devices into
    cuda_deps.

    Fix #includes and deps of contrib/verbs:verbs_util, in particular
    removing an unnecessary #include of gpu_util.h that relied on a
    transitive dependency through :devices.

    PiperOrigin-RevId: 169732234

@junshi15

**Comment by junshi15** [comment]
The existing verbs implementation assumes GPU usage. For example the following line calls GPUUtil.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L714

You can make it work with CPU-only cases, with some code change, I suppose.

**Comment by tatatodd** [comment]
@dariavel Thanks for filing the issue.
@junshi15 Thanks for the quick update.

Note that packages under `contrib` are less well supported by the core TensorFlow team.
I'm marking this as contributions welcome, in case somebody in the community would like to attempt to add verbs support for non-GPU.

**Comment by dariavel** [comment]
PR #14290 fixed the issue.
