### ISSUE TITLE
Tensorflow Windows 64bit build for Python 2.7

### ISSUE THREAD

**Issue by mohammadul** [tensorflow/tensorflow#13464]
Dear All,

I happened to have seemingly successfully built **tensorflow 1.3.1 (CPU only) for Python 2.7 64bit** with Visual Studio 2015 on Windows.

Apart from numerous minor manual tweaks, the main things that I had to do are the following:

-  modify _tensorflow-1.3.1\tensorflow\contrib\cmake\tools\create_def_file.py_
-  modify _tensorflow-1.3.1\tensorflow\tools\git\gen_git_source.py_. 
-  modify some of the automatically generated _*.py_ files.
-  copy some folders like _tensorflow\core\profiler_ to _tensorflow\python\profiler_ for the final distribution package.
- add blank ___init__.py_ files in some folders for the final distribution package.
- translate some Cmake build routines to Matlab (as it was easier for me to debug, :p )

I have tested some example codes and found to be running as expected. I however believe to make thorough tests to claim whether my build is 100% okay or not.

I have found in different forums that many users had struggled to build for Python 2.7 64bit in Windows and even if built, ended up with import errors, missing files, etc. I don't know whether they had finally succeeded or not.

So, for those who are really desperate to have one, I have shared the wheel package [here](http://mohammadulhaque.alotspace.com/download.php?id=56287).

I am also ready to discuss in more detail regarding the build process.

Acknowledgement: _I would like to acknowledge [Wingware](https://wingware.com/) for providing me a professional license for Wing IDE, which I have used, and in general use, extensively for debugging purposes in Python._

Disclaimer:  _The above shared wheel package is for illustrative purposes only which, I hope, will provide some useful information regarding the build process. It is supplied "AS IS" without any warranties and support. I assume no responsibility or liability for its use of any kind._

**Comment by asimshankar** [comment]
Glad to hear that you were able to get this going @mohammadul .
We are unlikely to have the bandwidth to support any official Python 2.7 binary releases, but if you'd like to contribute the changes you had to made that would be great as it may help others that need to use Python 2.7 on Windows. Feel free to send a pull request.

Closing this out since it isn't a bug or feature request.

**Comment by pratistha** [comment]
Hi @mohammadul ,
As i want to use python 2.7 with tensorflow on windows.
I am not able to access your given link for whl file. Can you please provide me it will be quite helpful.
