### ISSUE TITLE
Can't run new ops in new session after sess.run RuntimeError

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#13492]
Scenario:
1. runtime error during session.run
2. create new session
3. new session fails to evaluate any tensor, giving same runtime error as in step 1.

The following example fails to evaluate `tf.constant` with error `tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'Diag`

Using 12-day old version from this commit: https://github.com/tensorflow/tensorflow/commit/ea94bbe9fa9f9b3d01fb057c02ef7873d76bf09c

```
import tensorflow as tf
def main():
  
  sess = tf.Session()
  with tf.device("/gpu:0"):
    bad_op = tf.diag([1, 1])
    
  print("About to run tensor ", bad_op)
  try:
    sess.run(bad_op)
  except:
    print("First run failed, trying something else")

  sess = tf.Session()
  good_op = tf.constant(1)
  sess.run(good_op)

main()
```

I thought it's something to do with `TF_ExtendGraph` not being called, but manually adding ExtendGraph before second call results in segmentation fault

```
import tensorflow as tf
def main():
  
  sess = tf.Session()
  with tf.device("/gpu:0"):
    bad_op = tf.diag([1, 1])
    
  print("About to run tensor ", bad_op)
  try:
    sess.run(bad_op)
  except:
    print("First run failed, trying something else")

  sess = tf.Session()
  good_op = tf.constant(1)
  from tensorflow.python import pywrap_tensorflow as tf_session
  from tensorflow.python.framework import errors
  with errors.raise_exception_on_not_ok_status() as status:
    tf_session.TF_ExtendGraph(sess._session, sess.graph.as_graph_def().SerializeToString(), None)
  sess.run(good_op)

main()

```

**Comment by dhruvmalik007** [comment]
Well seeing From Previous issue  [ here ]( https://github.com/tensorflow/tensorflow/issues/2292) , you may have  problem in the line `with tf.device("/gpu:0"):` , after searching , i found you need to set a particular variable called "allowed_soft_placement = true"  as  an parameter to  tf.configProto, you can also check out following  links  
[1](https://github.com/dpressel/rude-carnie/issues/24)
[2](https://github.com/tensorflow/tensorflow/issues/2285)

**Comment by facaiy** [comment]
Thank you, @dhruvmalik007 . It seems intentional by using `diag` with GPU to create a failure.

**Comment by dhruvmalik007** [comment]
Welcome ,  it is quite a long time i have got  positive response from issues .

**Comment by dhruvmalik007** [comment]
@facaiy , What is the alternative then?

**Comment by facaiy** [comment]
If I understand correctly, what the issue indeed cares is how to recovery session from RuntimeError. Good question, but sadly, I have no idea. So let's be patient to wait for reply from tensorflowers. 
By the way,  I would not be surprised that @yaroslavvb, if he would like, might solve it by himself before response :-)

**Comment by tatatodd** [comment]
@yaroslavvb Thanks for filing the issue!  Indeed this looks like a bug.

@asimshankar Can you suggest someone who might be available to look into a fix?

**Comment by asimshankar** [comment]
@skye : Could you take a look? (And whatever the fix is, should also work when we fully transition Python graph construction to the C API :)

**Comment by skye** [comment]
Hi @yaroslavvb, the problem is that the entire graph will be placed, not the pruned graph. This means that even when you're not attempting to run the diag op with the invalid device, it will still try to place it, causing the error. You can set place_pruned_graph to true in the ConfigOptions passed to a Session to avoid this, see https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/core/protobuf/config.proto#L153. You can also use InteractiveSession, which sets this automatically.

**Comment by rj1346** [comment]
node1= tf.constant(3.0, tf.float32)
node2= tf.constant(4.0)
sess= tf.compat.v1.Session()
print(sess.run(fetches=[node1,node2])

RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().
The above error is being shown. Can you please help!!!
