### ISSUE TITLE
Iterator.get_next() returning a tensor of shape ()

### ISSUE THREAD

**Issue by Bardeux** [tensorflow/tensorflow#13508]
### System information
- **Have I written custom code**: Yes
- **OS Platform and Distribution**: Windows 10 (also tested on Ubuntu 16.04)
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: b'unknown' 1.3.0
- **Python version**: 3.5.3
- **CUDA/cuDNN version**: 8.0/6.0

### Describe the problem
Hello,
I am currently trying to use the Dataset API with TFRecords. Using a (tested) dataset I made and refactoring working code, I wanted to switch from queues to Datasets. With the following code:
 
```Python
def parse_function(serialized_example):

    # Context features
    context_features = {
         "label": tf.FixedLenFeature([], dtype=tf.int64),
    }

    # Sequence features
    sequence_features = {
         "positions": tf.FixedLenSequenceFeature([], dtype=tf.string),
    }

    # Parsing the TFRecord
    context_parsed, sequence_parsed = tf.parse_single_sequence_example(
        serialized=serialized_example,
        context_features=context_features,
        sequence_features=sequence_features)

    label = tf.cast(context_parsed['label'], tf.int32)
    sequence = tf.decode_raw(sequence_parsed['positions'], tf.float32)

    return tf.reshape(sequence, [height, width, channels]), label

def main(_):
    dataset = tensorflow.contrib.data.TFRecordDataset("path")
    dataset.map(parse_function)
    dataset.batch(64)

    iterator = dataset.make_one_shot_iterator()
    sequences, labels = iterator.get_next()
    ...

```
the last line will raise a TypeError("'Tensor' object is not iterable."). iterator.get_next() returns in this case a tensor with shape (), but I believe it should return a tuple of batched sequences and labels, as defined in my parse_function. I tried with every iterator, in or out of a session, but no change.

Is it a bug or am I doing something wrong? Examples from https://www.tensorflow.org/programmers_guide/datasets#decoding_image_data_and_resizing_it
really suggest this is the way to go.

Thanks,
Quentin

**Comment by mrry** [comment]
I think there’s a bug in your code. The following lines:

```python
def main(_):
    dataset = tensorflow.contrib.data.TFRecordDataset("path")
    dataset.map(parse_function)
    dataset.batch(64)
```

...should be changed to:

```python
def main(_):
    dataset = tensorflow.contrib.data.TFRecordDataset("path")
    dataset = dataset.map(parse_function)
    dataset = dataset.batch(64)
```

The high-level point is that calling methods on a `Dataset` does not modify an existing object; instead it returns a new `Dataset`, so you must assign the returned value to a Python variable (or chain it with other methods that are eventually assigned to a Python variable).

**Comment by Bardeux** [comment]
Wow, sorry to have bothered you with that... Got stuck on it for 3 hours, thanks for your help.

**Comment by mrry** [comment]
No worries! I'm just glad it wasn't seriously broken :).
