### ISSUE TITLE
nan gradients with low memory gpu

### ISSUE THREAD

**Issue by raingo** [tensorflow/tensorflow#1350]
### Environment info
Operating System: 
`3.12.9-201.fc19.x86_64 #1 SMP Wed Jan 29 15:44:35 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

GPU card info from `lspci -v | grep gtx -i`
```
NVIDIA Corporation GK110 [GeForce GTX Titan] (rev a1)
```

If installed from binary pip package, provide:

1. pip package installed:
`https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl`
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
```
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally                                                                             
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally                                                                              
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally                                                                              
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally                                                                             
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally                                                                             
0.7.1                                                                        
```

### Steps to reproduce
1. Increase batch size, so that you see the following warning message
2. check the gradients, and there are `nan` values
3. decrease batch size, and do the same check. Everything is normal if I don't see the following warning message

### What have you tried?
1. reduce batch size

### Logs or other output that would be helpful
```
W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:131] Ran out of memory trying to allocate 1.85GiB. The caller indicates that this is not a failure, but may mean that th
ere could be performance gains if more memory is available.
```

**Comment by vrv** [comment]
It's possible this is not a bug -- changing the batch size often requires changing the learning rate.

**Comment by raingo** [comment]
I didn't apply the optimizer at all. Just check the gradients from the beginning.

**Comment by vrv** [comment]
I think we would need real code to reproduce this, and very strong evidence to suggest there is a bug to make it worth our time to investigate (we do have 276 open bugs and growing...)

**Comment by raingo** [comment]
Sure. I will create a test case soon.

**Comment by raingo** [comment]
I will reopen this when I have a solid example.

**Comment by vladfi1** [comment]
I believe this may be happening to me as well. I am running on a GeForce 770 with only 2GB memory (1.8GB free) and tensorflow claims to allocate 1.6GiB of memory. I'm not sure about the gradients, but when I output my loss I get nan. My model doesn't perform any operations that would produce nan (only additions, subtractions, and multiplications).

**Comment by raingo** [comment]
The problem occurs only with my model. I tried my best to reproduce using the examples, but everything was fine. @vladfi1 can you figure out a simple example to reproduce?

**Comment by vladfi1** [comment]
I read [here](http://stackoverflow.com/questions/34514324/error-using-tensorflow-with-gpu) that Tensorflow always reserves all but 200MB of the GPU's memory, so the memory usage is always going to be very high. I've drastically reduced my model down in size and am still getting the nan outputs (as well as other nonsensical values such as negative norms), so I'm not sure if memory use is the culprit.

**Comment by vladfi1** [comment]
I now suspect that the issue has to do with reduce_sum (on gpu). I kept simplifying my original program until I got to something trivial:
```python
import tensorflow as tf

test_input = tf.placeholder(tf.float32, [2])
test_output = tf.reduce_sum(test_input)

with tf.Session() as sess:
  [out] = sess.run([test_output], feed_dict = {test_input :  [1.0, 2.0]})
  print(out)
```
Executing on my gpu machine I get the following output:
```
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so.4 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so.7.5 locally
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 770
major: 3 minor: 0 memoryClockRate (GHz) 1.137
pciBusID 0000:02:00.0
Total memory: 2.00GiB
Free memory: 1.46GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:763] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 770, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 256B
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 512B
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 1.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 2.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 4.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 8.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 16.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 32.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 64.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 128.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 256.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 512.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 1.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 2.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 4.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 8.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 16.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 32.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 64.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 128.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 256.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:107] Allocating 1.26GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:118] GPU 0 memory begins at 0x4202380000 extends to 0x425335a000
0.0
```
The correct output should be 3.0, not 0.0. It is interesting that If I use a shape-```[1]``` array instead then I get the correct output.

**Comment by vladfi1** [comment]
Tested this and my original model on a different machine (with a 660) and it seems to work just fine...

**Comment by keskival** [comment]
I'm getting the same problem with the newest Tensorflow (0.8.0). For a bigger batch size I get NaN:s even when limiting gradients (could not reproduce with batch size of 1). Following the min and max of all learned variables does not show any explosions. Running the same program on CPU (CUDA_VISIBLE_DEVICES="") does not give the NaNs.
It might even have something to do with GPU memory allocation as updating to the newest Tensorflow started giving me out of memory errors, even if it worked without such errors with an older version.

**Comment by vladfi1** [comment]
@keskival Not sure if this is the issue, but the 970 has a strange architecture with 3.5GB of fast memory and 0.5GB of slow memory - from what I've read it isn't recommended to go over the 3.5GB when running cuda programs. This might interact poorly with tensorflow's default allocation of all available GPU memory, although I don't see why you would get NaNs.
