### ISSUE TITLE
Feature Request: collections scope

### ISSUE THREAD

**Issue by tmulc18** [tensorflow/tensorflow#13501]
The is currently no way to assign variables to collections during creation time other than specifying in the explicit function call to `tf.get_variable` or `tf.Variable`.  This is problematic anytime you'd like to use existing functions that create variables as part of their calls and you want those variables to be part of a certain collection.  It's even more problematic when you want variables to not be members of  `GraphKeys.GLOBAL_VARIABLES`, because this is the default for the `tf.get_variable` and `tf.Variable`.

**Comment by jenshinshao** [comment]
i agree with you

**Comment by yaroslavvb** [comment]
workaround
```
g = tf.get_default_graph()
s = tf.Variable("hi")
print("Global variables", tf.global_variables())
del g._collections[tf.GraphKeys.GLOBAL_VARIABLES][0]
print("Global variables", tf.global_variables())

```

**Comment by tmulc18** [comment]
@yaroslavvb thanks for the workaround! 

For anyone else who doesn't see how switching the collection would work, here is an example

```
g = tf.get_default_graph()
s = tf.Variable("hi")
print("Global variables", tf.global_variables())
add_to_local = tf.add_to_collection(tf.GraphKeys.LOCAL_VARIABLES,s)
print("Local variables", tf.local_variables())
del g._collections[tf.GraphKeys.GLOBAL_VARIABLES][0]
print("Global variables", tf.global_variables())
print("Local variables", tf.local_variables())
```
