### ISSUE TITLE
tf.image.pad_to_bounding_box crashes when passed bounds with dtype int64

### ISSUE THREAD

**Issue by kcolford** [tensorflow/tensorflow#13506]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:from pip in virtualenv
- **TensorFlow version (use command below)**:v1.3.0-rc2-20-g0787eee 1.3.0
- **Python version**: '3.5.2 (default, Nov 17 2016, 17:05:23) \n[GCC 5.4.0 20160609]'
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

## Description

Passing arguments of type int64 to `tf.image.pad_to_bounding_box` triggers a crash of the python interpreter. This is a bug because the type required by `tf.image.pad_to_bounding_box` not documented anywhere and just causes a crash with a cryptic error message.

## Sources/Logs

The following snippet crashes the whole python interpreter with a core dump.

    import tensorflow as tf
    i = tf.constant([0, 0, 3, 3], dtype=tf.int64)
    img = tf.ones([1,1,1], dtype=tf.float32)
    sess = tf.Session()
    sess.run(tf.image.pad_to_bounding_box(img, i[0], i[1], i[2], i[3]))

And leaves the following 

    2017-10-05 13:51:24.789715: F tensorflow/core/framework/tensor.cc:493] Check failed: dtype() == expected_dtype (9 vs. 3)

**Comment by yaroslavvb** [comment]
this is bad, it shouldn't crash Python even if type is wrong

**Comment by yongtang** [comment]
The crash is caused by the fact that int64 was never registered in the kernel of `tf.image.pad_to_bounding_box`. Instead, the `int64` of the `Tpadding` is directly used as `int32` without appropriate processing.

A PR #13517 has been created to address the crash.

**Comment by asimshankar** [comment]
Thanks for debugging and the PR @yongtang !
