### ISSUE TITLE
complex gradient update in optimization

### ISSUE THREAD

**Issue by kctezcan** [tensorflow/tensorflow#13521]
Is there a plan to allow complex optimization in Tensorflow in the future?

When you try to do it with version 1.3, you can calculate and evaluate gradients, but you cannot apply them with opt.apply_gradients(grds_and_vars). The error message you get is: 

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'ApplyAdadelta' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No

- **OS Platform and Distribution 
Distributor ID: Debian
Description:    Debian GNU/Linux 8.9 (jessie)
Release:        8.9

- **TensorFlow installed from (source or binary)**:
using pip install in a virtual conda environment

- **TensorFlow version (use command below)**:
1.3

- **Python version**: 
Python 3.5.2 |Anaconda 4.3.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 

- **Bazel version (if compiling from source)**:
not applicable

- **CUDA/cuDNN version**:
8.0/6.0

- **GPU model and memory**:
Tesla K40c, 11439MiB

- **Exact command to reproduce**:
not necessary, since feature request/question

### Describe the problem
problem description above

### Source code / logs
not applicable

**Comment by cy89** [comment]
@suharshs @kbsriram can you comment on future development plans, please?

**Comment by kbsriram** [comment]
@suharshs will be able to speak authoritatively on this.

Fwiw, as a participant in the "contributions welcome" set the team has been very receptive to PRs improving gradient support, complex or otherwise. (Based on this error though, it might also reflect a general request to grow the set of ops with kernels that accept complex inputs.)

**Comment by suharshs** [comment]
cc: @asimshankar  @ebrevdo 

I don't believe anyone is actively working on this. To me this seems like a "contributions welcome" to add complex kernels for the desired ops.

**Comment by ebrevdo** [comment]
Seems like it should be easy enough for external contributors to add.  +1 for contributions welcome.

**Comment by yongtang** [comment]
Added PR #15402.

**Comment by guyko81** [comment]
Hi, I was trying to work with complex64 recently and still have the issue mentioned above. All the optimizers has the restriction to work on non-complex numbers only. 
Has the PR been merged? I was a bit confused from the closed message. 
Thanks!

**Comment by spbroma** [comment]
Are there any plans of adding complex values for optimization?

**Comment by jaingaurav** [comment]
This has been fixed in bf9c196f37b9cbb3109b2891aaf9da85bf5f712a. I should be included in the 2.1 release.
