### ISSUE TITLE
Why is gen_ctc_op not visible in the github repository?

### ISSUE THREAD

**Issue by manucarbonell** [tensorflow/tensorflow#13524]
I want to take a look at the core of the ctc_loss implementation, and looking at ctc_ops.py shows it's imported from the gen_ctc_ops module but that module is impossible to find in the github repository. Where can I find it?
Thanks

**Comment by yaroslavvb** [comment]
btw, this question was answered on stackoverflow

**Comment by manucarbonell** [comment]
Could you share the link of the question please?

**Comment by yaroslavvb** [comment]
https://stackoverflow.com/questions/41147734/looking-for-source-code-of-from-gen-nn-ops-in-tensorflow/
