### ISSUE TITLE
fix build bug come from 8041c54

### ISSUE THREAD

**Issue by blueegg** [tensorflow/tensorflow#1352]
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

### Environment info
Operating System: OSX

If installed from sources, provide the commit hash: 8041c54

**tensorflow/contrib/linear_optimizer/BUILD**

    linkopts = [
         "-Wl,-Bsymbolic",
         "-lm",
    ],

**should change to:**

    linkopts = select({
        "//conditions:default": [
         "-Wl,-Bsymbolic",
         "-lm",
        ],
        "//tensorflow:darwin": [],
    }),

**Comment by vrv** [comment]
Thanks for the report, we'll get in a change tomorrow!

**Comment by vrv** [comment]
Fixed in c3c40b7a8950bba876b92456824e5b6a9505c0a7.  Still one more error to fix.
