### ISSUE TITLE
AttributeError: 'module' object has no attribute 'truncated_normal'

### ISSUE THREAD

**Issue by murraymack** [tensorflow/tensorflow#1353]
Operating System: **Ubuntu 14.04 LTS**
Environment: **Python 2.7.11 :: Continuum Analytics, Inc.**
IDE: **Spyder and IPython**
TensorFlow Version: **0.7.1**
Pip Package File: **tensorflow-0.7.1-cp27-none-linux_x86_64.whl 64-Bit CPU ONLY**
Pip Package File from: [https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl](https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl)

Trying to follow tutorial from Kaggle to implement Convolutional NN. `import tensorflow` seems to execute without returning an error.

Code to reproduce:

```
In [74]: 
def weight_variable(shape):
     initial = tf.truncated_normal(shape, stddev=0.1) #Outputs random values from truncated normal distribution.
     return tf.Variable(initial)

In [75]: 
W_convl = weight_variable([5,5,1,32])

Traceback (most recent call last):

  File "<ipython-input-75-65b9a0522cb2>", line 1, in <module>
    W_convl = weight_variable([5,5,1,32])

  File "<ipython-input-74-ae39e79c161a>", line 2, in weight_variable
    initial = tf.truncated_normal(shape, stddev=0.1) #Outputs random values from truncated normal distribution.

AttributeError: 'module' object has no attribute 'truncated_normal'
```

I have tried:

`import tensorflow as tf`

And:

`from tensorflow import truncated_normal`

Not sure what is going on.

**Comment by vrv** [comment]
That's really strange -- can you try installing in a virtualenv from scratch, to isolate the installation?

**Comment by mrry** [comment]
Also, if `import tensorflow` works, can you report the output of `dir(tensorflow)`?

**Comment by murraymack** [comment]
@vrv and @mrry 

Thanks for your reply guys! I have it working now. It seems like I had to again just pip uninstall tensorflow and protobuf and then pip install tensorflow. I'm not sure why but if it works it works!

**Comment by vrv** [comment]
Glad to hear it's working, and sorry for the installation trouble.

**Comment by Hanuman26** [comment]
### OS : Ubuntu 14.04
tensor flow GPU installation 
tensorflow.__version__  = 0.7.1
python anaconda2

Traceback (most recent call last):
  File "exp_mnist.py", line 56, in <module>
    w_conv1 = weight_variable([5,5,1,32])
  File "exp_mnist.py", line 40, in weight_variable
    initial = tf.truncate_normal(shape, stddev=0.1)
AttributeError: 'module' object has no attribute 'truncate_normal'

output of dir(tensorflow) =
['AggregationMethod', 'Assert', 'AttrValue', 'ConfigProto', 'DESCRIPTOR', 'DType', 'Dimension', 'Event', 'FIFOQueue', 'FixedLenFeature', 'FixedLenSequenceFeature', 'FixedLengthRecordReader', 'GPUOptions', 'GRAPH_DEF_VERSION', 'GRAPH_DEF_VERSION_MIN_CONSUMER', 'GRAPH_DEF_VERSION_MIN_PRODUCER', 'Graph', 'GraphDef', 'GraphKeys', 'GraphOptions', 'HistogramProto', 'IdentityReader', 'IndexedSlices', 'InteractiveSession', 'LogMessage', 'NameAttrList', 'NoGradient', 'NodeDef', 'OpError', 'Operation', 'OptimizerOptions', 'PaddingFIFOQueue', 'Print', 'QUANTIZED_DTYPES', 'QueueBase', 'RandomShuffleQueue', 'ReaderBase', 'RegisterGradient', 'RegisterShape', 'Session', 'SessionLog', 'SparseTensor', 'SparseTensorValue', 'Summary', 'TFRecordReader', 'Tensor', 'TensorShape', 'TextLineReader', 'VarLenFeature', 'Variable', 'WholeFileReader', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'abs', 'absolute_import', 'accumulate_n', 'add', 'add_check_numerics_ops', 'add_n', 'add_to_collection', 'all_variables', 'app', 'arg_max', 'arg_min', 'argmax', 'argmin', 'as_dtype', 'assert_variables_initialized', 'assign', 'assign_add', 'assign_sub', 'batch_cholesky', 'batch_matmul', 'batch_matrix_determinant', 'batch_matrix_inverse', 'batch_matrix_solve', 'batch_matrix_solve_ls', 'batch_matrix_triangular_solve', 'batch_self_adjoint_eig', 'bfloat16', 'bfloat16_ref', 'bool', 'bool_ref', 'boolean_mask', 'bytes', 'cast', 'ceil', 'check_numerics', 'cholesky', 'clip_by_average_norm', 'clip_by_global_norm', 'clip_by_norm', 'clip_by_value', 'compat', 'complex', 'complex64', 'complex64_ref', 'complex_abs', 'concat', 'cond', 'conj', 'constant', 'constant_initializer', 'contrib', 'control_dependencies', 'convert_to_tensor', 'convert_to_tensor_or_indexed_slices', 'core', 'cos', 'count_up_to', 'cross', 'decode_csv', 'decode_json_example', 'decode_raw', 'depth_to_space', 'deserialize_many_sparse', 'device', 'diag', 'div', 'division', 'double', 'double_ref', 'dynamic_partition', 'dynamic_stitch', 'edit_distance', 'equal', 'erf', 'erfc', 'errors', 'exp', 'expand_dims', 'fft2d', 'fill', 'flags', 'float32', 'float32_ref', 'float64', 'float64_ref', 'floor', 'floordiv', 'gather', 'get_collection', 'get_default_graph', 'get_default_session', 'get_seed', 'get_variable', 'get_variable_scope', 'gfile', 'global_norm', 'gradients', 'greater', 'greater_equal', 'group', 'histogram_summary', 'identity', 'ifft2d', 'imag', 'image', 'image_summary', 'import_graph_def', 'initialize_all_tables', 'initialize_all_variables', 'initialize_variables', 'int16', 'int16_ref', 'int32', 'int32_ref', 'int64', 'int64_ref', 'int8', 'int8_ref', 'inv', 'invert_permutation', 'is_finite', 'is_inf', 'is_nan', 'less', 'less_equal', 'lgamma', 'lin_space', 'linspace', 'list_diff', 'listdiff', 'load_op_library', 'log', 'logging', 'logical_and', 'logical_not', 'logical_or', 'logical_xor', 'make_template', 'matching_files', 'matmul', 'matrix_determinant', 'matrix_inverse', 'matrix_solve', 'matrix_solve_ls', 'matrix_triangular_solve', 'maximum', 'merge_all_summaries', 'merge_summary', 'minimum', 'mod', 'moving_average_variables', 'mul', 'name_scope', 'neg', 'nn', 'no_op', 'not_equal', 'ones', 'ones_like', 'op_scope', 'pack', 'pad', 'parse_example', 'parse_single_example', 'parse_single_sequence_example', 'placeholder', 'pow', 'print_function', 'py_func', 'python', 'python_io', 'qint16', 'qint16_ref', 'qint32', 'qint32_ref', 'qint8', 'qint8_ref', 'quint16', 'quint16_ref', 'quint8', 'quint8_ref', 'random_crop', 'random_normal', 'random_normal_initializer', 'random_shuffle', 'random_uniform', 'random_uniform_initializer', 'range', 'rank', 'read_file', 'real', 'reduce_all', 'reduce_any', 'reduce_max', 'reduce_mean', 'reduce_min', 'reduce_prod', 'reduce_sum', 'register_tensor_conversion_function', 'reset_default_graph', 'reshape', 'resource_loader', 'reverse', 'reverse_sequence', 'round', 'rsqrt', 'scalar_mul', 'scalar_summary', 'scatter_add', 'scatter_sub', 'scatter_update', 'segment_max', 'segment_mean', 'segment_min', 'segment_prod', 'segment_sum', 'select', 'self_adjoint_eig', 'serialize_many_sparse', 'serialize_sparse', 'set_random_seed', 'shape', 'shape_n', 'sigmoid', 'sign', 'sin', 'size', 'slice', 'space_to_depth', 'sparse_concat', 'sparse_fill_empty_rows', 'sparse_mask', 'sparse_matmul', 'sparse_reorder', 'sparse_retain', 'sparse_segment_mean', 'sparse_segment_mean_grad', 'sparse_segment_sqrt_n', 'sparse_segment_sqrt_n_grad', 'sparse_segment_sum', 'sparse_split', 'sparse_tensor_to_dense', 'sparse_to_dense', 'sparse_to_indicator', 'split', 'sqrt', 'square', 'squeeze', 'stop_gradient', 'string', 'string_ref', 'string_to_hash_bucket', 'string_to_number', 'sub', 'sysconfig', 'tanh', 'test', 'tile', 'to_bfloat16', 'to_double', 'to_float', 'to_int32', 'to_int64', 'train', 'trainable_variables', 'transpose', 'truediv', 'truncated_normal', 'truncated_normal_initializer', 'tuple', 'uint16', 'uint16_ref', 'uint8', 'uint8_ref', 'uniform_unit_scaling_initializer', 'unique', 'unique_with_counts', 'unpack', 'unsorted_segment_sum', 'user_ops', 'variable_op_scope', 'variable_scope', 'verify_tensor_all_finite', 'where', 'xrange', 'zeros', 'zeros_initializer', 'zeros_like']

Don't know what causing this error. it shows the "truncated_normal" module but error shows missing "truncate_normal" . is it just the definition error of the name of the module?

**Comment by August-us** [comment]
I was wondering if it was wrong to pass your parameters, The tf.truncated_normal(shape,mean,stddev...)

**Comment by vkmanojk** [comment]
Just replace tf with tf.compat.v1. It should work fine.

**Comment by vidkr** [comment]
> Just replace tf with tf.compat.v1. It should work fine.

thank you@vkmanojk, it works for me

**Comment by PurushothamanSrikanth** [comment]
> @vrv and @mrry
> 
> Thanks for your reply guys! I have it working now. It seems like I had to again just pip uninstall tensorflow and protobuf and then pip install tensorflow. I'm not sure why but if it works it works!

If we are using `tensorflow-gpu`, we can't install TensorFlow alongside, right?

**Comment by FMFigueroa** [comment]
replaces "tf.truncated_normal" by "tf.random.truncated_normal" in Tensorflow Core v2.x
