### ISSUE TITLE
How to decrease memory usage on GPU card

### ISSUE THREAD

**Issue by gaoteng-hi** [tensorflow/tensorflow#1354]
When I run example like mnist on GPU card, I see that it consumes almost all device memory of that card. It seems like the tensorflow reserves as much memory as possible for memory pool at the start of process.
However, we need to run the tensor flow on a shared GPU card, on which runs other users' processes. So we can't occupy all device memory of it. Is there any switch to turn this memory pool off, or decrease the memory pool to a user defined size?
Thanks a lot in advance!

**Comment by lglhuada** [comment]
I guess you are considering tensorflow for your online service. We intend to use it for models in our search engine as well, but the GPU usage is really an annoying problem. I am looking forward to positive feedback ;)

**Comment by yaroslavvb** [comment]
http://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory
