### ISSUE TITLE
https://www.tensorflow.org/ extremly sucks: cockie madness

### ISSUE THREAD

**Issue by jelmd** [tensorflow/tensorflow#13550]
https://www.tensorflow.org/* totally sucks because of its cookie popup dialog, which jumps into one's face __each__ time one goes to a different page on this site, NO matter whether one _has already clicked clicked_ OK or something else. No way to do any research on such annoying site ...

**Comment by asimshankar** [comment]
www.tensorflow.org should not be causing any popups. Perhaps there are some settings/plugins in your browser/environment that are making this happen.

**Comment by jelmd** [comment]
On 3 different, independent workstations, on Solaris as well as under Linux?
Sorry for not using Windows ...

**Comment by jelmd** [comment]
BTW: Added rules to block all *.js from tensorflow.org and google related sites, which fixes the problem. I'll give our students the advice to do the same.
So far to your "professional" analysis. Good job @asimshankar ...

**Comment by fidlej** [comment]
The issue is real.
The cookie popup is for Europe users. The popup says:
"We serve cookies on this site to analyse traffic, remember your preferences, and optimise your experience."

**Comment by asimshankar** [comment]
Thanks for adding the detail @fidlej 
Out of curiosity, have you explicitly disabled cookies in your browser? (Wondering if this is happening by default or if conflicting with some user settings)

CC @wolffg : Who might have some insight.

**Comment by fidlej** [comment]
I do not have cookies disabled.
The popup keep appearing even if using a clean incognito chrome window.

**Comment by gunan** [comment]
@dr4b @wolffg @jugglerix PTAL

**Comment by wolffg** [comment]
We've turned the permission off for now; you should be OK.

**Comment by fidlej** [comment]
Thanks. The popup is not appearing anymore.
