### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by e-lin** [tensorflow/tensorflow#1356]
MacOS, master branch pull minutes ago.
I intended to try this `bazel build -c opt //tensorflow/tools/pip_package:build_pip_package`

### Bazel version:
Build label: 0.1.5
Build target: bazel-out/local_darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 12:53:53 2016 (1453380833)
Build timestamp: 1453380833
Build timestamp as int: 1453380833
I've also tried on 0.1.4, same error as below.

### gcc --version:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix

### Logs:
ERROR: /Users/elin/gitHub_e-lin/tensorflow/tensorflow/contrib/linear_optimizer/BUILD:14:1: Linking of rule '//tensorflow/contrib/linear_optimizer:python/ops/_sdca_ops.so' failed: osx_gcc_wrapper.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_elin/c89d25ef263422ce5293ac2a19ea0c36/tensorflow && \
  exec env - \
  external/bazel_tools/tools/cpp/osx_gcc_wrapper.sh -shared -o bazel-out/local_darwin-opt/bin/tensorflow/contrib/linear_optimizer/python/ops/_sdca_ops.so -Wl,-all_load bazel-out/local_darwin-opt/bin/tensorflow/contrib/linear_optimizer/_objs/python/ops/_sdca_ops.so/tensorflow/contrib/linear_optimizer/kernels/sdca_ops.pic.o bazel-out/local_darwin-opt/bin/tensorflow/contrib/linear_optimizer/_objs/python/ops/_sdca_ops.so/tensorflow/contrib/linear_optimizer/ops/sdca_ops.pic.o bazel-out/local_darwin-opt/bin/tensorflow/core/libframework_internal.pic.lo bazel-out/local_darwin-opt/bin/tensorflow/core/liblib_internal.pic.a bazel-out/local_darwin-opt/bin/external/jpeg_archive/libjpeg.pic.a bazel-out/local_darwin-opt/bin/external/png_archive/libpng.pic.a bazel-out/local_darwin-opt/bin/external/re2/libre2.pic.a bazel-out/local_darwin-opt/bin/tensorflow/core/libprotos_all_cc.pic.a bazel-out/local_darwin-opt/bin/google/protobuf/libprotobuf.pic.a bazel-out/local_darwin-opt/bin/google/protobuf/libprotobuf_lite.pic.a -Wl,-noall_load -Wl,-Bsymbolic -lm -ldl -lm -ldl -lz -pthread -lpthread -lstdc++ -undefined dynamic_lookup -no-canonical-prefixes): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: osx_gcc_wrapper.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_elin/c89d25ef263422ce5293ac2a19ea0c36/tensorflow && \
  exec env - \
  external/bazel_tools/tools/cpp/osx_gcc_wrapper.sh -shared -o bazel-out/local_darwin-opt/bin/tensorflow/contrib/linear_optimizer/python/ops/_sdca_ops.so -Wl,-all_load bazel-out/local_darwin-opt/bin/tensorflow/contrib/linear_optimizer/_objs/python/ops/_sdca_ops.so/tensorflow/contrib/linear_optimizer/kernels/sdca_ops.pic.o bazel-out/local_darwin-opt/bin/tensorflow/contrib/linear_optimizer/_objs/python/ops/_sdca_ops.so/tensorflow/contrib/linear_optimizer/ops/sdca_ops.pic.o bazel-out/local_darwin-opt/bin/tensorflow/core/libframework_internal.pic.lo bazel-out/local_darwin-opt/bin/tensorflow/core/liblib_internal.pic.a bazel-out/local_darwin-opt/bin/external/jpeg_archive/libjpeg.pic.a bazel-out/local_darwin-opt/bin/external/png_archive/libpng.pic.a bazel-out/local_darwin-opt/bin/external/re2/libre2.pic.a bazel-out/local_darwin-opt/bin/tensorflow/core/libprotos_all_cc.pic.a bazel-out/local_darwin-opt/bin/google/protobuf/libprotobuf.pic.a bazel-out/local_darwin-opt/bin/google/protobuf/libprotobuf_lite.pic.a -Wl,-noall_load -Wl,-Bsymbolic -lm -ldl -lm -ldl -lz -pthread -lpthread -lstdc++ -undefined dynamic_lookup -no-canonical-prefixes): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
clang: warning: argument unused during compilation: '-pthread'
ld: warning: option -noall_load is obsolete and being ignored
ld: unknown option: -Bsymbolic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3.198s, Critical Path: 2.04s

**Comment by blueegg** [comment]
fix as: #1352

**Comment by e-lin** [comment]
@blueegg Thanks! This works for me! I close this case.
