### ISSUE TITLE
TF fails to build on PowerPC. Issues with BoringSSL.

### ISSUE THREAD

**Issue by tjingrant** [tensorflow/tensorflow#13587]
------------------------
BoringSSL doesn't seem to have their own issue board. So I'm guessing here's the closest alternative.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04.2 LTS
- **TensorFlow installed from (source or binary)**: source (github master, 10c871ed92a1d9b36c5e2e3a674d5812c67e82a1)
- **TensorFlow version (use command below)**:  (doesn't compile)
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.6.1
- **CUDA/cuDNN version**: (not relevant)
- **GPU model and memory**: Nvidia K40
- **Exact command to reproduce**: ```bazel --host_jvm_args=-XX:+IgnoreUnrecognizedVMOptions build -c opt --config=cuda  //tensorflow/tools/pip_package:build_pip_package --verbose_failures```

### Describe the problem
Latest TF master branch does not build on PowerPC. 
Problem seems to be with BoringSSL.
This [link](https://github.com/google/boringssl/blob/f21650709a6f76e829ddcc77fe221c9d6a5c12de/crypto/fipsmodule/bcm.c#L91) points to a file in BoringSSL that has the following inclusions:
```
#include "sha/sha1-altivec.c"
#include "sha/sha1.c"
```

Both files included seem to have their own definition of `sha1_block_data_order` and both are enabled on PowerPC. This seems to cause GCC 4.8.5 to freak out (did not test other versions of gcc). My temporary fix is to remove the altivec version of sha1 and it works. Hopefully someone working on BoringSSL can take a look.

Below is the exact error message:
```
ERROR: /gsa/yktgsa-h2/05/tjin/.cache/bazel/_bazel_tjin/5ebd35a31f2e08b1acf4a588141b13f1/external/boringssl/BUILD:118:1: C++ compilation of rule '@boringssl//:crypto' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /gsa/yktgsa-h2/05/tjin/.cache/bazel/_bazel_tjin/5ebd35a31f2e08b1acf4a588141b13f1/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-8.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64: \
    PATH=/usr/lib/jvm/java-8-openjdk-ppc64el/bin:/localhd/tjin/tensorflow_latest/bin:/gsa/yktgsa/home/t/j/tjin/anaconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda/bin:/localhd/tjin/tensorflow_latest/bazel/output:/usr/local/cuda/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/localhd/tjin/tensorflow_latest/bin/python \
    PYTHON_LIB_PATH=/localhd/tjin/tensorflow_latest/lib/python2.7/site-packages \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2 \
    TF_CUDA_VERSION=8.0 \
    TF_CUDNN_VERSION=5.1.5 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL=0 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/local_linux-opt/bin/external/boringssl/_objs/crypto/external/boringssl/src/crypto/fipsmodule/bcm.pic.d -fPIC -iquote external/boringssl -iquote bazel-out/local_linux-opt/genfiles/external/boringssl -iquote external/bazel_tools -iquote bazel-out/local_linux-opt/genfiles/external/bazel_tools -isystem external/boringssl/src/include -isystem bazel-out/local_linux-opt/genfiles/external/boringssl/src/include -isystem external/bazel_tools/tools/cpp/gcc3 -Wa,--noexecstack '-D_XOPEN_SOURCE=700' -Wall -Werror '-Wformat=2' -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -Wshadow -fno-common -DOPENSSL_NO_ASM '-std=c11' -Wmissing-prototypes -Wold-style-definition -Wstrict-prototypes -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c external/boringssl/src/crypto/fipsmodule/bcm.c -o bazel-out/local_linux-opt/bin/external/boringssl/_objs/crypto/external/boringssl/src/crypto/fipsmodule/bcm.pic.o).
In file included from external/boringssl/src/crypto/fipsmodule/bcm.c:92:0:
external/boringssl/src/crypto/fipsmodule/sha/sha1.c:125:6: error: static declaration of 'sha1_block_data_order' follows non-static declaration
 void sha1_block_data_order(uint32_t *state, const uint8_t *data, size_t num);
      ^
In file included from external/boringssl/src/crypto/fipsmodule/bcm.c:91:0:
external/boringssl/src/crypto/fipsmodule/sha/sha1-altivec.c:190:6: note: previous definition of 'sha1_block_data_order' was here
 void sha1_block_data_order(uint32_t *state, const uint8_t *data, size_t num) {
      ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 311.401s, Critical Path: 8.71s
```

**Comment by reedwm** [comment]
@gunan can you comment? Do we support PowerPC?

**Comment by gunan** [comment]
There is no official support for powerPC architecture for TensorFlow.
You will need to check with the community or reach out to stackoverflow for support.

Before I leave, two things that may help:
- @nayana-ibm how similar is powerPC to s390x?
- Boringssl should only be needed for GCS support or a very limited number of kernels. You could try modifying our build files and cut boringssl off and try building again. But no guarantees.

**Comment by tjingrant** [comment]
@gunan, I understand there's no official support for PowerPC for TF. In fact I'm trying to make sure that people can use Tensorflow on PowerPC. But the problem is with OpenSSL.

More importantly, looking at the history of the relevant OpenSSL file, especially [here](https://github.com/google/boringssl/commit/5f04b6bc3a46662323b67be31bc9a28be38b2844); I think the problem is not that there is no support for PPC; the problem is the support seems only half-way there. Since a PR to the TF repository will unlikely be of any help, are you suggesting that the best course of action is to debug OpenSSL and submit a PR to OpenSSL repository?

**Comment by gunan** [comment]
@Nayana-ibm already tried to submit fixes to boringSSL to support big-endian systems. Boring SSL team firmly refused and said they will never support big endian systems.
If you are working on PowerPC running in little-endian systems, even that is questionable for boring ssl team to accept.
But this question is better asked to them. At the moment, on TF side all you can do is not build the ops that require openssl, as I said above.

**Comment by tjingrant** [comment]
@gunan, thanks for your information. Optimally I would like TF to work out of the box and it has more or less been the case in the past, it would be a pity that we can no longer do it because of a less-than-often-used part. Can you tell me what's the best way to reach the BoringSSL team?

**Comment by gunan** [comment]
All I have about boringssl is here:
https://boringssl.googlesource.com/boringssl/

**Comment by davidben** [comment]
This sounds like the issue we fixed here:
https://boringssl.googlesource.com/boringssl/+/e7136a978f6f9d5b3f392b661e573e0793965f97

The issue affected the ppc64le + no-asm build.

**Comment by tjingrant** [comment]
@davidben looks like that's it! It appears in the master-with-bazel branch. Should I do a PR and update the boringssl archive [here](https://github.com/tensorflow/tensorflow/blob/a2d9b3bf5f9e96bf459074d079b01e1c74b25afa/tensorflow/workspace.bzl#L593)?

**Comment by davidben** [comment]
Sounds reasonable (though I can't speak for Tensorflow).

**Comment by gunan** [comment]
Please feel free to send a pill request to update the boringssl library we
depend on.
If you send it to me for review, I can also make sure the mirror is set up
before merging the pull request.

**Comment by nasica88** [comment]
@tjingrant, I have the same boringssl error on ppc64le Redhat 7.4 (AC922) with python3.  Can you pls let me know how this issue was addressed ?   IBM's technical preview edition for TF1.4 is for python2 only, so it does not help much.
