### ISSUE TITLE
InvalidArgumentError : Expected image (JPEG, PNG, or GIF), got unknown format starting with '255'

### ISSUE THREAD

**Issue by engahmed1190** [tensorflow/tensorflow#13583]
### System information
-  **OS Platform and Distribution**  :Linux Ubuntu 16.04
-  **TensorFlow installed from**  :binary
-  **TensorFlow version**  :1.1.0
-  **Python version** : 2.7.12

### Describe the problem
trying to feed a model an image encoded in string as the model require that as an input string
```
signature_def {
  key: "serving_default"
  value {
    inputs {
      key: "image_bytes"
      value {
        name: "Placeholder:0"
        dtype: DT_STRING
        tensor_shape {
          dim {
            size: -1
          }
        }
      }
    }
    inputs {
      key: "key"
      value {
        name: "Placeholder_1:0"
        dtype: DT_STRING
        tensor_shape {
          dim {
            size: -1
          }
        }
      }
    }
    outputs {
      key: "key"
      value {
        name: "Identity:0"
        dtype: DT_STRING
        tensor_shape {
          dim {
            size: -1
          }
        }
      }
    }
    outputs {
      key: "prediction"
      value {
        name: "ArgMax:0"
        dtype: DT_INT64
        tensor_shape {
          dim {
            size: -1
          }
        }
      }
    }
    outputs {
      key: "scores"
      value {
        name: "final_ops/softmax:0"
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: -1
          }
          dim {
            size: 3
          }
        }
      }
    }
    method_name: "tensorflow/serving/predict"
  }
}
```
Here is the code :-
```
def load_image( infilename ) :
    img = Image.open( infilename )
    img.load()
    data = np.asarray( img, dtype="string" )
    return data

export_dir = '.'
with tf.Session(graph=tf.Graph()) as sess:
	model = tf.saved_model.loader.load(sess, ['serve'], export_dir)
	input_dict, output_dict =_signature_def_to_tensors(model.signature_def['serving_default'])
	out = sess.run(output_dict, feed_dict={input_dict['image_bytes']: load_image("fullsize.jpeg").flatten()})
	print(input_dict)
```
Error returns  is :
```
InvalidArgumentError (see above for traceback): Expected image (JPEG, PNG, or GIF), got unknown format starting with '255'
	 [[Node: map/while/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](map/while/TensorArrayReadV3)]]
```

how i can solve that , any help

**Comment by asimshankar** [comment]
The error message suggests that the input isn't a valid JPEG image.
Are you sure that the image you're feeding (which seems to be a 3 byte file) is a valid JPEG image?

**Comment by engahmed1190** [comment]
I feed the Image using `np.array `and also tried to feed it with` tf.image.decode_jpeg` getting an error in both cases . when i am using `tf.image.decode_jpeg` as 
```
image_contents = tf.read_file("fullsize.jpeg")
image = tf.image.decode_jpeg(image_contents, channels=3)
```
i get this error 
```
    raise TypeError('The value of a feed cannot be a tf.Tensor object. '
TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.
```
how to validate if the image is valid or not and also the best way to feed the image . 

Thanks In Advance

**Comment by engahmed1190** [comment]
Sorry , **Edited the Error Message** i tried it again with the same values but represent this error , seems to be problem in the encoding

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

That said, a few things to note:

- `tf.image.decode_jpeg` expects the encoded-JPEG bytes (i.e., the contents of the file). The use of `PIL` and in particular `PIL.Image.load()` suggests that the numpy array you're creating consists of the decoded contents (decoded by `PIL`). Which is why the `sess.run()` call is failing as it expects an encoded JPEG but you're providing it a decoded one.

- To provide the raw contents of the file as a feed, you'd want to do something like so:

```python
def load_image(filename):
  with open('fullsize.jpeg') as f:
    return np.array(f.read())
```
Which will create the numpy array of the encoded JPEG bytes that you can feed to your session.

Hope that helps.

**Comment by clovking** [comment]
@engahmed1190 ,  I meet a silimar question with you when i train models on google TensorFlow Object Detection API, May i ask if the question has been solved? what's the problem and how to solved? thank you!

**Comment by clovking** [comment]
@keyankarthisdk , maybe the reason is some picture is not the JPEG format. You can use tf.image.decode_jpeg() to test which picture is not the right format for tensorflow and then discard. I use this way solve the problem.

**Comment by keyankarthisdk** [comment]
Thank you so much

**Comment by rohitkumar9989** [comment]
``Hello, I've been running through a similar problem and 

> @keyankarthisdk , maybe the reason is some picture is not the JPEG format. You can use tf.image.decode_jpeg() to test which picture is not the right format for tensorflow and then discard. I use this way solve the problem.

Like where should i use the decode_jpeg, because I'am working with Application API
Here is my code,

```
base_model=tf.keras.applications.EfficientNetB2(include_top=False, input_shape=(224, 224, 3))
base_model.trainable=False
inputs=tf.keras.layers.Input(shape=(224, 224, 3))
x=tf.keras.layers.GlobalAveragePooling2D()(inputs)
outputs=tf.keras.layers.Dense(2, activation='softmax')(x)
model_0=tf.keras.Model(inputs, outputs) 
model_0.compile(loss=tf.keras.losses.binary_crossentropy,
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])
model_0.fit(data_gen, epochs=5)
```
And when i executed this code I was getting this sort of error,

>InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-101-6769bac1fcee> in <module>()
      2                 optimizer=tf.keras.optimizers.Adam(),
      3                 metrics=['accuracy'])
----> 4 model_0.fit(data_gen, epochs=5)

6 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Unknown image file format. One of JPEG, PNG, GIF, BMP required.
	 [[{{node decode_image/DecodeImage}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_4]]
  (1) Invalid argument:  Unknown image file format. One of JPEG, PNG, GIF, BMP required.
	 [[{{node decode_image/DecodeImage}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_216368]

Function call stack:
train_function -> train_function

Thanks in advance

**Comment by rohitkumar9989** [comment]
> @keyankarthisdk , maybe the reason is some picture is not the JPEG format. You can use tf.image.decode_jpeg() to test which picture is not the right format for tensorflow and then discard. I use this way solve the problem.

Hello,
I'am currently working with Application API and where should i Insert the decode_jpeg function my code is as follows
```
base_model=tf.keras.applications.EfficientNetB2(include_top=False, input_shape=(224, 224, 3))
base_model.trainable=False
inputs=tf.keras.layers.Input(shape=(224, 224, 3))
x=tf.keras.layers.GlobalAveragePooling2D()(inputs)
outputs=tf.keras.layers.Dense(2, activation='softmax')(x)
model_0=tf.keras.Model(inputs, outputs)
```
```
model_0.compile(loss=tf.keras.losses.binary_crossentropy,
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])
model_0.fit(data_gen, epochs=5)
```
And when I executed this code I was getting this error
```
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-101-6769bac1fcee> in <module>()
      2                 optimizer=tf.keras.optimizers.Adam(),
      3                 metrics=['accuracy'])
----> 4 model_0.fit(data_gen, epochs=5)

6 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Unknown image file format. One of JPEG, PNG, GIF, BMP required.
	 [[{{node decode_image/DecodeImage}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_4]]
  (1) Invalid argument:  Unknown image file format. One of JPEG, PNG, GIF, BMP required.
	 [[{{node decode_image/DecodeImage}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_216368]

Function call stack:
train_function -> train_function
```

Please help me with this 
Thanks in advance

**Comment by DeepModiDev** [comment]
@rohitkumar9989  you can solve this problem with the below code:

    import cv2
    import tensorflow as tf
    import os

    def check_images(s_dir, ext_list):
        bad_images=[]
        bad_ext=[]
        s_list= os.listdir(s_dir)
        for klass in s_list:
            klass_path=os.path.join (s_dir, klass)
            print ('processing class directory ', klass)
            if os.path.isdir(klass_path):
                file_list=os.listdir(klass_path)
                for f in file_list:               
                    f_path=os.path.join (klass_path,f)
                    index=f.rfind('.')
                    ext=f[index+1:].lower()
                    if ext not in ext_list:
                        print('file ', f_path, ' has an invalid extension ', ext)
                        bad_ext.append(f_path)
                    if os.path.isfile(f_path):
                        try:
                            img=cv2.imread(f_path)
                            shape=img.shape
                            image_contents = tf.io.read_file(f_path)
                            image = tf.image.decode_jpeg(image_contents, channels=3)
                        except Exception as e:
                            print('file ', f_path, ' is not a valid image file')
                            print(e)
                            bad_images.append(f_path)
                    else:
                        print('*** fatal error, you a sub directory ', f, ' in class directory ', klass)
            else:
                print ('*** WARNING*** you have files in ', s_dir, ' it should only contain sub directories')
        return bad_images, bad_ext


For execution of the above code:

    source_dir =r'/data/validation/'
    good_exts=['jpg','jpeg'] # list of acceptable extensions
    bad_file_list, bad_ext_list=check_images(source_dir, good_exts)
    if len(bad_file_list) !=0:
        print('improper image files are listed below')
    
    print(bad_file_list)
    print(bad_ext_list)

**Comment by rohitkumar9989** [comment]
Yes thank you sir....  I've actually made a helper function that converts
all the images into JPEG format... So I wasn't able to see any error....

**Comment by DeepModiDev** [comment]
@rohitkumar9989 Okay, That's great. :)

**Comment by rohitkumar9989** [comment]
Awesome, thanks!
Thanks for your handy help...

**Comment by Tseema** [comment]
@rohitkumar9989  could you please tell me how did you build the helper class? 
Does this mean if I only have .jpg files to train on,I should be able to do?

**Comment by Omnitok** [comment]
I got a similar error message.
I had a big dataset of small *.png images (~10000 files) for object classification.
The problem was that I had several corrupt files that the program couldn't handle. I deleted the files and it works

**Comment by Omnitok** [comment]
I got a similar error message.
I had a big dataset of small *.png images (~10000 files) for object classification.
The problem was that I had several corrupt files that the program couldn't handle. I deleted the files and it works
