### ISSUE TITLE
Tensorflow Session Connects to Multiple Targets

### ISSUE THREAD

**Issue by RuofanKong** [tensorflow/tensorflow#13590]
I posted a question on [SO](https://stackoverflow.com/questions/46626879/can-one-tensorflow-session-connect-to-two-targets-at-the-same-time), where I wonder if a Tensorflow Session could connect to two (or more than two) targets at the same time. It looks the feature is not supported yet. Can we make a feature request on it?

**Comment by yaroslavvb** [comment]
What's the semantics of supporting multiple masters for tf.Session? Which master would execute `sess.run`?

**Comment by RuofanKong** [comment]
@yaroslavvb The point is to support one session to connect multiple server targets (or masters), and the goal is to make some of tensor computations run on one server, and others run on different servers. `sess.run` may specify which master (or target) to connect to. I wonder if it is possible.

**Comment by yaroslavvb** [comment]
I think it's a little vague for a feature request. Lets move it to SO
