### ISSUE TITLE
 module 'tensorflow.contrib.tfprof' has no attribute 'ProfileContext' 

### ISSUE THREAD

**Issue by johnsrude** [tensorflow/tensorflow#13597]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 7
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: tensorflow-gpu (1.3.0)
- **Python version**:  3.5
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: not relevant
- **GPU model and memory**: not relevant
- **Exact command to reproduce**: not relevant

### Describe the problem
Production machine not hooked up to Internet. Used pip3 to install [tensorflow_gpu-1.3.0-cp35-cp35m-win_amd64.whl](https://pypi.python.org/pypi/tensorflow-gpu)  It looks the profile code may be missing from the wheel.

When run tensorflow with the following code:
```
import tensorflow as tf
with tf.contrib.tfprof.ProfileContext(FLAGS.log_dir + '\\test', trace_steps=[], dump_steps=[]) as pctx:
```
get error:
`AttributeError: module 'tensorflow.contrib.tfprof' has no attribute 'ProfileContext'`
```
Directory of C:\Python35\Lib\site-packages\tensorflow\contrib\tfprof
08/25/2017  02:55 PM             4,132 model_analyzer.py
08/25/2017  02:55 PM             1,301 tfprof_logger.py
08/25/2017  02:55 PM             1,030 __init__.py
09/11/2017  10:54 AM    <DIR>          __pycache__
```
### Source code / logs
It appears that the examples in the https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/profiler Readme.md  may be obsolete.

**Comment by reedwm** [comment]
The readme for 1.3, https://github.com/tensorflow/tensorflow/tree/r1.3/tensorflow/core/profiler, does not contain a reference to `ProfileContext`. It appears `ProfileContext` was added after TensorFlow 1.3, so you have to use the master branch to use it.

**Comment by moakra** [comment]
Hi,
I am having the same error using Tensorflow 1.3 and have the error:
AttributeError: module 'tensorflow.contrib.tfprof' has no attribute 'ProfileContext'

when I use:
with tf.contrib.tfprof.ProfileContext('/tmp/train_dir', trace_steps=[], dump_steps=[]) as pctx:

When I try to import the profiler_context using:
from tensorflow.python.profiler import profile_context

I get: ImportError: cannot import name 'profile_context'

Where can I find the way to import the profiler in Tensorflow 1.3 ?

Thank you!

**Comment by reedwm** [comment]
`ProfileContext` was added after TensorFlow 1.3, so you cannot use it in 1.3. To use it, wait for TensorFlow 1.4 to be released, or use a [nightly TensorFlow binary](https://github.com/tensorflow/tensorflow#installation).
