### ISSUE TITLE
The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, str

### ISSUE THREAD

**Issue by Kwoks2017** [tensorflow/tensorflow#13619]
When i feed the value, unfortunately , it is a tensor.
i have already known that i should convert it to a array or other types to feed. But if i use sess.run() or .eval(). The speed makes me crazy, for the shape is [3600,14,25500].

if other ways are available?

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
