### ISSUE TITLE
Installation error "error: identifier "__shfl_down" is undefined"  (Trying with Compute Capability  2.0) 

### ISSUE THREAD

**Issue by cbonnett** [tensorflow/tensorflow#1361]
I'm trying to install tensor flow from source, as I would like to use GPU's 
that have compute capability == 2.0. (And I suspect that problems lies here and might be not have a trivial solution)

### Environment info
Operating System:
uname -or
3.16.0-4-amd64 GNU/Linux
bazel release 0.2.0
#Commit hash  
git log --pretty=format:'%h' -n 1
99952d6
git log -1 --format="%H"
99952d68444cd2b08e88af972bd9eb7034fbc1e7

I use TF_UNOFFICIAL_SETTING=1 ./configure 
and  choose Compute Capability  2.0 

bazel build -c opt  --config=cuda  --spawn_strategy=standalone --verbose_failures  //tensorflow/cc:tutorials_example_trainer

Full output here : https://gist.github.com/cbonnett/97aec5a35209f0501993

**What seems to be the key-error:**
INFO: From Compiling tensorflow/core/kernels/sparse_xent_op_gpu.cu.cc:
external/eigen_archive/eigen-eigen-017cff30cf74/unsupported/Eigen/CXX11/src/Tensor/TensorReductionCuda.h(111): **error: identifier "__shfl_down" is undefined**

It seems "__shfl_down" was added in Kepler (compute capability == 3.x )
https://devblogs.nvidia.com/parallelforall/faster-parallel-reductions-kepler/
and as my cards are pre-Kepler, this seems to be the culprit. Can anybody confirm this ? or might there be a solution ?

**Comment by vrv** [comment]
Yeah, I don't think TensorFlow's or Eigen's GPU kernels are written for pre 3.0 compute capability :(

**Comment by cbonnett** [comment]
I was afraid that was the case....

**Comment by asabater94** [comment]
Have you found the solution to undefined __shfl_down?
I am trying to install cunn for lua and I have the save issue:
> error: identifier "__shfl_down" is undefined

I am using a GPU with compute capability 2.1.

**Comment by BostjanBuh** [comment]
I'm having the same problem.

`/tmp/luarocks_cunn-scm-1-7288/cunn/lib/THCUNN/SpatialClassNLLCriterion.cu(16): error: identifier "__shfl_down" is undefined

1 error detected in the compilation of "/tmp/tmpxft_0000402e_00000000-20_SpatialClassNLLCriterion.compute_20.cpp1.ii".
CMake Error at THCUNN_generated_SpatialClassNLLCriterion.cu.o.cmake:264 (message):
  Error generating file
  /tmp/luarocks_cunn-scm-1-7288/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialClassNLLCriterion.cu.o


make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_SpatialClassNLLCriterion.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
`

Any ideas?

**Comment by zach-capalbo** [comment]
I found a `__shfl_down` replacement here: https://github.com/parallel-forall/code-samples/blob/master/posts/parallel_reduction_with_shfl/fake_shfl.h

That might help you get around this particular compile issues.

**Comment by cbonnett** [comment]
I never looked for a solution, I was lucky enough to find access to some newer cards.

**Comment by suiyuan2009** [comment]
I meet the same problem, @cbonnett did you find a solution?

**Comment by cbonnett** [comment]
nope, I got access to newer GPU cards so that solved my problem. Theano should work fine though.

**Comment by abrams90** [comment]
@zach-capalbo the replace func can compile well ,but is this func produce the same result as the offical one?

**Comment by JeanMaximilienCadic** [comment]
Try to move from cuda 10.1 to cuda 9.1 `sudo apt install nvidia-cuda-toolkit` and gcc-7 to gcc-5/gcc-6 . It worked for me after trying all solutions available so far.
