### ISSUE TITLE
Why the parameters aren't stored on ps server for distributed tensorflow ?

### ISSUE THREAD

**Issue by gauss-clb** [tensorflow/tensorflow#13623]
Please see more detail on [stackoverflow](https://stackoverflow.com/questions/46667790/distributed-tensorflow-of-between-graph-replication).

I don't start `ps` server, and parameters are stored on `worker` server.

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. Please refer to the answer of the StackOverflow question you linked. Thanks!
