### ISSUE TITLE
matrix_solve_ls_op Compile Error on gcc 4.8 (using typename error)

### ISSUE THREAD

**Issue by mranjbar** [tensorflow/tensorflow#1362]
I have been trying to compile tensorflow from source without success.
I could compile version 0.6.0 with no trouble, but trying to compile 0.7.1 produces the following error:

<blockquote>
tensorflow/core/kernels/matrix_solve_ls_op.cc: In member function 'void tensorflow::MatrixSolveLsOp<Scalar, SupportsBatchOperationT>::ComputeMatrix(tensorflow::OpKernelContext*, const typename tensorflow::BinaryLinearAlgebraOp<Scalar, SupportsBatchOperationT>::ConstMatrixMap&, const typename tensorflow::BinaryLinearAlgebraOp<Scalar, SupportsBatchOperationT>::ConstMatrixMap&, typename tensorflow::BinaryLinearAlgebraOp<Scalar, SupportsBatchOperationT>::MatrixMap*)':
tensorflow/core/kernels/matrix_solve_ls_op.cc:111:41: error: 'Matrix' is not a class, namespace, or enumeration
               (Scalar(l2_regularizer) * Matrix::Ones(cols, 1)).asDiagonal();
                                         ^
tensorflow/core/kernels/matrix_solve_ls_op.cc:131:41: error: 'Matrix' is not a class, namespace, or enumeration
               (Scalar(l2_regularizer) * Matrix::Ones(rows, 1)).asDiagonal();
                                         ^
In file included from ./tensorflow/core/framework/op_kernel.h:22:0,
                 from tensorflow/core/kernels/matrix_solve_ls_op.cc:23:
./tensorflow/core/framework/allocator.h: In member function 'virtual std::size_t tensorflow::Allocator::RequestedSize(void*)':
./tensorflow/core/framework/allocator.h:128:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
In file included from ./tensorflow/core/framework/op_kernel.h:25:0,
                 from tensorflow/core/kernels/matrix_solve_ls_op.cc:23:
./tensorflow/core/framework/device_base.h: In member function 'virtual tensorflow::Allocator* tensorflow::DeviceBase::GetAllocator(tensorflow::AllocatorAttributes)':
./tensorflow/core/framework/device_base.h:149:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
./tensorflow/core/framework/device_base.h: In member function 'virtual const tensorflow::DeviceAttributes& tensorflow::DeviceBase::attributes() const':
./tensorflow/core/framework/device_base.h:179:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
</blockquote>

I tried to find the definition of Matrix::Ones in all folders, but couldn't find anything. In fact 
> grep "Ones" tensorflow/* -R 

returns 

<blockquote>
core/kernels/matrix_solve_ls_op.cc:              (Scalar(l2_regularizer) * Matrix::Ones(cols, 1)).asDiagonal();
core/kernels/matrix_solve_ls_op.cc:              (Scalar(l2_regularizer) * Matrix::Ones(rows, 1)).asDiagonal();
python/kernel_tests/constant_op_test.py:class OnesTest(tf.test.TestCase):
python/kernel_tests/constant_op_test.py:  def _Ones(self, shape):
python/kernel_tests/constant_op_test.py:    self.assertTrue(np.array_equal(self._Ones([2, 3]), np.array([[1] * 3] * 2)))
python/kernel_tests/constant_op_test.py:class OnesLikeTest(tf.test.TestCase):
python/kernel_tests/constant_op_test.py:  def testOnesLike(self):
python/kernel_tests/constant_op_test.py:  def testOnesLikePartialShape(self):
python/kernel_tests/shape_ops_test.py:  def testSqueezeAllOnes(self):
python/kernel_tests/shape_ops_test.py:  def testSqueezeOnlyOnes(self):
</blockquote>

### Environment info
OS : CentOS 6.6, but I have gcc 4.8.2 installed.

### Steps to reproduce
> ./configure

say yes to GPU, cuda 7.5, cudnn 4

> bazel build --config=cuda --jobs 6 --verbose_failures --linkopt="-lrt" --linkopt="-lm" --genrule_strategy=standalone --spawn_strategy=standalone -c opt //tensorflow/tools/pip_package:build_pip_package

**Comment by vrv** [comment]
I don't have gcc 4.8 installed, and I think the problem is that gcc 4.8 can't understand the 'using typename' declaration there.

In https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/matrix_solve_ls_op.cc#L66, can you try changing the
'using' to just 'typedef' ?

**Comment by rdipietro** [comment]
This didn't work for me – resulted in further errors:

```
   typedef typename BinaryLinearAlgebraOp<Scalar, SupportsBatchOperationT>::Matrix;
                                                                            ^
tensorflow/core/kernels/matrix_solve_ls_op.cc:68:66: error: declaration does not declare anything [-fpermissive]
                                        SupportsBatchOperationT>::MatrixMap;
                                                                  ^
tensorflow/core/kernels/matrix_solve_ls_op.cc:70:66: error: declaration does not declare anything [-fpermissive]
                                        SupportsBatchOperationT>::ConstMatrixMap;
```

Any thoughts? If more error log would be helpful just let me know. Thanks!

**Comment by vrv** [comment]
you should do typedef typename BinaryLinear......::Matrix Matrix;

(Need to give it a name)

**Comment by mranjbar** [comment]
That's right. The following changes fixed the problem on gcc 4.8.2

<blockquote>
diff --git a/tensorflow/core/kernels/matrix_solve_ls_op.cc b/tensorflow/core/kernels/matrix_solve_ls_op.cc
index c69c93f..4ce6dff 100644
--- a/tensorflow/core/kernels/matrix_solve_ls_op.cc
+++ b/tensorflow/core/kernels/matrix_solve_ls_op.cc
@@ -63,11 +63,11 @@ class MatrixSolveLsOp
     }
   }
 
-  using typename BinaryLinearAlgebraOp<Scalar, SupportsBatchOperationT>::Matrix;
-  using typename BinaryLinearAlgebraOp<Scalar,
-                                       SupportsBatchOperationT>::MatrixMap;
-  using typename BinaryLinearAlgebraOp<Scalar,
-                                       SupportsBatchOperationT>::ConstMatrixMap;
+  typedef typename BinaryLinearAlgebraOp<Scalar, SupportsBatchOperationT>::Matrix Matrix;
+  typedef typename BinaryLinearAlgebraOp<Scalar,
+                                       SupportsBatchOperationT>::MatrixMap MatrixMap;
+  typedef typename BinaryLinearAlgebraOp<Scalar,
+                                       SupportsBatchOperationT>::ConstMatrixMap ConstMatrixMap;
</blockquote>

**Comment by vrv** [comment]
Let me submit a fix to this

**Comment by rdipietro** [comment]
This makes it compile (not quite there yet, as it now seg faults, but I think this is related to other solvable problems, so I think I'm close!). Thank you for the help.
