### ISSUE TITLE
HDFS user impersonation

### ISSUE THREAD

**Issue by kouzant** [tensorflow/tensorflow#13627]
TensorFlow  does support HDFS filesystem but there is no way to specify as which user to access the filesystem.

The native hdfs library provides a function to set the user name, hdfsBuilderSetUserName() similar to hdfsBuilderSetNameNode(). There is also hdfsConnectAsUser() where you can specify the user, builds the hdfsBuilder struct, set the username among other arguments and return the FileSystem handle.

Currently I don't see any way to provide a username in TensorFlow and more specifically in tensorflow/core/platform/hadoop/hadoop_file_system.cc

I suppose that something like the following would be sufficient.
https://github.com/kouzant/tensorflow/commit/eacef5cb81d09d0490403fde33de8e5526f212ad

**Comment by jimdowling** [comment]
We can install our own build of tensorflow. And submit a PR to tensorflow in the meantime.

**Comment by reedwm** [comment]
Marking as contributions weclome since it seems @jimdowling will submit a PR.

/CC @jhseu in case he has any comments.

**Comment by jimdowling** [comment]
Sorry, that was an internal comment for @kouzant  - who will submit the PR.

**Comment by mihaimaruseac** [comment]
Closing since HDFS is no longer provided by TF itself
