### ISSUE TITLE
Something wrong while using C++ Session.Run api. 

### ISSUE THREAD

**Issue by zhbbupt** [tensorflow/tensorflow#13625]
I use tensorflow C++ api to run my model. I flower this reference: [label_image](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/main.cc).
In my model, the outputs' shape is 2d,  I run model like this:

` std::vector<Tensor> outputs;`
`status = session->Run(m_feed_dict, {"model/wav_outputs"},{}, &outputs);`
However, I get this:
`
tensorflow/core/framework/tensor_shape.cc:44] Check failed: NDIMS == dims() (1 vs. 2)Asking for tensor of 1 dimensions from a tensor of 2 dimensions
`
Could anybody tell me how to fix this?
@petewarden.  @vclteam  #

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
