### ISSUE TITLE
[Import Error] Tensorflow is looking for wrong shared library; libnvidia-fatbinaryloader.so.375.88

### ISSUE THREAD

**Issue by anilbeereddy135** [tensorflow/tensorflow#13626]
### System information
- **OS Platform and Distribution**:  Ubuntu 16.04
- **TensorFlow installed from**: Binary
- **TensorFlow version**: 1.3.0 
- **Python version**: 2.7
- **CUDA/cuDNN version**: 6
- **GPU model and memory**: GTX 840M, 2GB
- **Exact command to reproduce**: import tensorflow as tf

When ever I try to import tensorflow (1.3.0), I encounter a ImportError where the system is unable to locate the shared library libnvidia-fatbinaryloader.so.375.88. I've looked in /usr/lib/nvidia-375 and found that another version of the .so exists (375.66). 
The issue is resolved if I downgrade to tensorflow version 1.2.1

**Comment by tatatodd** [comment]
@allenlavoie Do you have any thoughts on this?

**Comment by allenlavoie** [comment]
Ha. 1.3 is before the RTLD_GLOBAL change so I couldn't have broken it with that was my main thought.

Otherwise those look like driver version numbers. What is printed after "Driver Version:" in `nvidia-smi`?

**Comment by anilbeereddy135** [comment]
Driver Version output in nvidia-smi is375.66

**Comment by allenlavoie** [comment]
Sounds like a bug then. Does it work if you symlink/copy .66 to .88 in that folder?

**Comment by anilbeereddy135** [comment]
Symlinking .66 to .88 in the folder seems to be working, did not test extensively, but got tensorflow 1.3.0 working after symlink

**Comment by gunan** [comment]
I have seen such issues reported when the driver is upgraded through apt. However, I could not reproduce this myself.
Did you use to have 375.66 driver installed on this machine before?

**Comment by anilbeereddy135** [comment]
Actually, I'm not entirely sure of the driver version before the issue.

**Comment by anilbeereddy135** [comment]
The problem is not with TF versions, There was mismatch b/w libcuda and nvidia driver versions. Closing the issue
