### ISSUE TITLE
[Feature Request] Add partial_run and partial_run_setup to MonitoredSession

### ISSUE THREAD

**Issue by lukaszgrad** [tensorflow/tensorflow#13631]
Hello, 

as mentioned in the topic, I wonder if there is a chance in the near future for MonitoredSession to support partial graph computation.

**Comment by reedwm** [comment]
@ispirmustafa, any plans to support this?

**Comment by ispirmustafa** [comment]
We're adding a capability into MonitoredSession where you can use partialrun.

**Comment by isaprykin** [comment]
We added MonitoredSession.run_step_fn.  We hope it satisfies the use case.
