### ISSUE TITLE
[bug?] tf.nn.embedding_lookup returns 0 when ids out of range

### ISSUE THREAD

**Issue by chentingpc** [tensorflow/tensorflow#13642]
It seems tf.nn.embedding_lookup will simply return tensor of zeros when ids out of range (larger than the embedding table size):
```
import tensorflow as tf
embs = tf.ones([100, 100]) 
idx = tf.cast(tf.ones([1]) * 1000, tf.int32)
with tf.Session() as sess:
  emb = sess.run(tf.nn.embedding_lookup(embs, idx))
```
The emb will be tensor of zeros. I am not sure if this is a bug, or by design for efficiency concern? It would be nice if there is a runtime exception. That will do a big favor in avoiding hidden bugs that lead to performance degeneration.

(I am running tensorflow-gpu 1.3.0 in Ubuntu 16.04)

**Comment by tatatodd** [comment]
This is by-design, for performance reasons.

Note the docs describe this via the `validate_indices` argument, which is deprecated and always set to the `True` behavior.
https://www.tensorflow.org/api_docs/python/tf/nn/embedding_lookup

```
validate_indices: DEPRECATED. If this operation is assigned to CPU, values in indices are always validated to be within range. If assigned to GPU, out-of-bound indices result in safe but unspecified behavior, which may include raising an error.
```

**Comment by floydluo** [comment]
Now, when the id is out of the range, there will be an error, instead of returning zero tensor.

If I want to get zero tensors if the ids are out of the range, what should I do? (as the validate_indices is deprecated now)

Thanks

**Comment by tgsmith61591** [comment]
@floydluo did you ever figure out a solution? I'm hesitant to use the `embedding_lookup` function if I can't be sure it won't raise an `InvalidArgumentError`...

**Comment by floydluo** [comment]
@tgsmith61591 Hi, actually, I didn't find an elegant way. But I found a tentative one. Suppose `vocab_size` is N, where 0 is `pad__id`,  1 is `unknown_id`, and 2 to (N-1) are normal token ids. I construct an embedding as the snippet shows. This embedding always return zero vectors for `0` (`pad_id`) and `1` (`unknown_id`) during training, as the corresponding vectors are zero constants. 

```python
def get_embeddings_variable(vocab_size, embedding_size = 200):
    # input_size is vocab_size.
    # 0: pad id, 1: unk id, 2 to (vocab_size-1): normal token id
    # I want return zero vectors for pad and unk all the time.
    embed_shape = vocab_size, embedding_size
    embeddings = tf.Variable(tf.truncated_normal(embed_shape,  stddev=1.0 / np.sqrt(embedding_size)))
    always_zero_tokens_num = 2  # pad and unk
    embeddings = tf.concat([[tf.constant([0.] * embedding_size)] * always_zero_tokens_num, embeddings], axis = 0)
    return embeddings 
```
Then I process the input indexes. If any one is larger than N, I replace it with 1, `unknown_id`. Finally, the embeddings returns zero vectors for the ids which are out of range...
