### ISSUE TITLE
Add support for Mel Generalized Cepstrum Analysis to tf.signal.

### ISSUE THREAD

**Issue by rryan** [tensorflow/tensorflow#13644]
Requested via discuss@
https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/k6EI-BxbCMg

Please :+1: if you would like to see this feature in tf.contrib.signal.

**Comment by levivosWOW** [comment]
Hi, is this still open to contribute to? It seems like a very interesting module to help with.

**Comment by sushreebarsa** [comment]
@rryan [tf.contrib.signal](https://www.tensorflow.org/api_docs/python/tf/contrib/signal) has been renamed to [tf.signal](https://www.tensorflow.org/api_docs/python/tf/signal). [tf.contrib.signal](https://www.tensorflow.org/api_docs/python/tf/contrib/signal) module is not included in TensorFlow 2.x. We recommend you to kindly upgrade to the latest TF version(2.9.0) as older versions are not actively supported. Thank you!
