### ISSUE TITLE
histogram_summary does not respect name_scope

### ISSUE THREAD

**Issue by robwell** [tensorflow/tensorflow#1365]
I am getting a Duplicate tag error when I try to write out histogram summaries for a multi-layer network that I generate procedurally. The problem is that the name given to a histogram_summary (and I assume all summaries) does not respect name_scope. As a consequence, the names are not unique. This seems like a bug.

For example, in:
```
with tf.name_scope(some_unique_name):
  ...
  _ = tf.histogram_summary('weights', kernel_weights)
```
I'd assume that 'weights' would be scoped to some_unique_name but I'm suspecting that it is not. I added code to make the names unique and the Duplicate tag problem goes away.

### Environment info
Operating System: OSX
TensorFlow version: 0.7.0

**Comment by girving** [comment]
I think this is intended behavior, unfortunately.  A typical resolution to this is to pick `kernel_weights` to have a nice name and use

    `tf.histogram_summary(kernel_weights.name, kernel_weights)`
