### ISSUE TITLE
AttributeError: 'GFile' object has no attribute 'writelines

### ISSUE THREAD

**Issue by nicolettiant89** [tensorflow/tensorflow#13655]
Hi when i try to execute this code:

`from tensorflow.python.platform import gfile
... with gfile.GFile("%s_%s" % (target_path, len_d + len_q), mode="w") as tokens_file:
        tokens_file.writelines(results)...`

I obtain the following error:

`AttributeError: 'GFile' object has no attribute 'writelines'`

Why GFile haven't writelines attribute in verision 1.2? What method should i use instead? Thanks a lot.

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by kuthedk** [comment]
honestly this would be a great place to put this or maybe even linking the fix for the depreciation instead of just saying we wont help you.

**Comment by reedwm** [comment]
You're right, this should be treated as a feature request. What do you mean by "fix for the depreciation"?

/CC @rohan100jain @vrv, any plans to add this, to match the interface of Python files?

**Comment by kuthedk** [comment]
well, I have fixed this problem by refactoring the code to get it to *kinda* run on the newest version of TF. I forked the project and I believe the fix has been made there to at least get around this problem. I currently am working on updating the rest of this to be able to run on the newest version of TF with no problems, however that is proving to be a bit of a task.

**Comment by vrv** [comment]
@reedwm I have no personal plans to add this, but it seems easy enough and I'd like to encourage external contributions.

@kuthedk is it sufficient to just implement this via:

    def writelines(self, seq):
        for line in seq:
          self.write(line)

?

**Comment by vrv** [comment]
(Specifically, adding that function to file_io.py with tests, etc.)

**Comment by kuthedk** [comment]
@vrv omg I've been commenting in regards to the wrong project. my bad. please forgive me as I've been sick for a while and a lot of stuff has been blurring together. What you have added looks like it would work but what I ended up doing was just a simple 2 liner in the https://github.com/carpedm20/attentive-reader-tensorflow project. there is a PR that I made on that project that also kinda addresses this similar issue.
