### ISSUE TITLE
ImportError: No module named core.framework.graph_pb2

### ISSUE THREAD

**Issue by bonevbs** [tensorflow/tensorflow#1367]
Hello, I am trying to build tensorflow from source without CPU support. When I try to import it in python I am getting the error "ImportError: No module named core.framework.graph_pb2".

I have tried this on Arch Linux AND on Ubuntu which gives me the impression I might be doing something wrong. However I am exactly following the instructions on the TF homepage.

I would appreciate any help!!

#### Environment info
Operating System: Arch Linux
Commit hash: 263d00d2710779d5c4ac66e335b2ba07d8385b6b

### Steps to reproduce
1. ./configure
2. bazel build -c opt //tensorflow/cc:tutorials_example_trainer
3. python2
4. import tensorflow

### What have you tried?
1. I made sure I am not in the build directory
2. I have uninstalled protobuf and reinstalled it
3. I have reinstalled six
4. I tried with different versions of protobuf
5. I tried the same on Ubuntu 15.04 -> getting the same error ()

### Logs or other output that would be helpful
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../Development/tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/.../Development/tensorflow/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/.../Development/tensorflow/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
ImportError: No module named core.framework.graph_pb2

**Comment by bonevbs** [comment]
The problem was that I did not do the pip install step.

**Comment by 1LISA2** [comment]
Whites first, blacks trash，Why do black people exist, black people still have a lot of AIDS, black, ugly, poor and violent
