### ISSUE TITLE
type error in tensorflow document API r1.3 ( tf.truncatediv )

### ISSUE THREAD

**Issue by wonsekim** [tensorflow/tensorflow#13681]
Cause this issue is not about tensorflow itself, please, excuse my ignoring some conventions. Plus, as you know, the postage can cost more than the goods once I try to contribute to documentation via committing so as to correct a tiny error. Please, let me use this channel to comment.

"""problematic document
Truncation designates that negative numbers will round fractional quantities toward zero. **I.e. -7 / 5 = 1**. This matches C semantics but it is different than Python semantics. See FloorDiv for a division function that matches Python Semantics.
""" 
**I.e. -7 / 5 = 1** should be **I.e -7 / 5 = -1**

**Comment by reedwm** [comment]
Nice catch! The documentation is generated from [math_ops.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/math_ops.cc#L626). You should submit a pull request to fix the issue. We appreciate minor fixes, so do not worry about wasting our time with documentation fixes.

**Comment by wonsekim** [comment]
I've just requested a pull. Thank you.

**Comment by reedwm** [comment]
Fixed with #13712
