### ISSUE TITLE
Documentation truncated_normal does not match implementation

### ISSUE THREAD

**Issue by mrTsjolder** [tensorflow/tensorflow#13686]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Nope
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux CentOS 7.3
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.3.0-rc2-20-g0787eee 1.3.0
- **Python version**: Python 3.6.1
- **Bazel version (if compiling from source)**: N.A.
- **CUDA/cuDNN version**: 8.0 / 6.0
- **GPU model and memory**: Nvidia Tesla 12 GB
- **Exact command to reproduce**: ?

### Describe the problem
The documentation of `tf.truncated_normal`[https://www.tensorflow.org/api_docs/python/tf/truncated_normal] contains the following line for its parameter `stddev`: 

> The standard deviation of the truncated normal distribution.

However, the example below shows that the truncated normal does not have the given standard deviation. This means that the documentation would be correct if it said

> The standard deviation of the normal distribution, before truncation.

or if the standard deviation of the samples would be indeed the given standard deviation.

### Source code / logs

    import numpy as np
    import tensorflow as tf

    # standard deviation not 1
    with tf.Session():
        print(np.std(tf.truncated_normal([10000, ], stddev=1).eval()))

    # compared to scipy
    from scipy.stats import truncnorm
    print(truncnorm(-2, 2, loc=0, scale=1).std())

**Comment by dr4b** [comment]
I'd be delighted if you fixed this in tensorflow/docs_src and sent a pull request :)

**Comment by mrTsjolder** [comment]
@dr4b That would require me to sign legal documents and I am not quite sure whether I am ready for that sort of commitment. That's one of the reasons why I did not directly issue a pull request.

**Comment by dr4b** [comment]
Ok. I'll make the change (though I'm going to do it internally so it won't propagate out for a few days).
