### ISSUE TITLE
Feature request: Profiling with multiple workers in distributed settings and visualizing them individually

### ISSUE THREAD

**Issue by amathuri** [tensorflow/tensorflow#13680]
Hi,
I am running Tensorflow in distributed settings only using CPUs with multiple workers and parameter servers. I would like to find a way to generate timeline information of individual workers/parameter servers and visualize them together to check on potential scaling issues. 
Currently, I can generate timeline traces containing the profiles of all the parameter servers and a single worker.  But, visualizing all the workers in the same timeline trace would be beneficial. 

Thank you.

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
