### ISSUE TITLE
can any one reproduce this problew with tf.gather?

### ISSUE THREAD

**Issue by fword** [tensorflow/tensorflow#13682]
x = tf.constant([[0.22, 0.3,0.1,0.11],[0.4,0.5, 0.6,0.99],[0.8, 0.9,0.43,0.21]])
indices = tf.constant([[1,2],[0,1],[2,3]])
b=tf.gather_nd(x, indices）
sess = tf.InteractiveSession()
cc=sess.run([b], feed_dict={})
print cc

with tensorflow 1.0.1 it gets [array([ 0., 0., 0.], dtype=float32)]
is it a bug in 1.0.1, but with higher version,it gets right

**Comment by gunan** [comment]
Thanks for the report. But as you reported, this issue seems to be resolved with newer TF versions.
As 1.0 is now older than 7 months, we will not patch the release to fix this bug in 1.0.

Thank you very much for your report, and please let us know if you see this error in1.4 release
