### ISSUE TITLE
Linux compile v1.1.0 failed

### ISSUE THREAD

**Issue by fesun** [tensorflow/tensorflow#13685]
> ERROR: /home/fesun/.cache/bazel/_bazel_fesun/c44abb322eef8ca1d3dd1c34fcda8c3a/external/io_bazel_rules_closure/closure/private/defs.bzl:27:16: The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
> ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
> ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors

I added the flag --incompatible_disallow_set_constructor=false for all bazel command call, then:

> DEBUG: /home/fesun/.cache/bazel/_bazel_fesun/c44abb322eef8ca1d3dd1c34fcda8c3a/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:197:9: @//tensorflow/tools/lib_package:libtensorflow_jni: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
> DEBUG: /home/fesun/.cache/bazel/_bazel_fesun/c44abb322eef8ca1d3dd1c34fcda8c3a/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:197:9: @//tensorflow/tools/lib_package:cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
> DEBUG: /home/fesun/.cache/bazel/_bazel_fesun/c44abb322eef8ca1d3dd1c34fcda8c3a/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:197:9: @//tensorflow/tools/lib_package:clib: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
> DEBUG: /home/fesun/.cache/bazel/_bazel_fesun/c44abb322eef8ca1d3dd1c34fcda8c3a/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:197:9: @//tensorflow/tools/lib_package:clicenses: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
> ERROR: /home/fesun/tensorflow/tensorflow/core/kernels/BUILD:59:14: Traceback (most recent call last):
>         File "/home/fesun/tensorflow/tensorflow/core/kernels/BUILD", line 54
>                 config_setting(name = "xsmm_backward", values = {..."})
>         File "/home/fesun/tensorflow/tensorflow/core/kernels/BUILD", line 59, in config_setting
>                 {"define": "tensorflow_xsmm=1", "define": "tensorflow_xsmm_backward=1"}
> Duplicated key "define" when creating dictionary
> ERROR: package contains errors: tensorflow/core/kernels
> ERROR: error loading package 'tensorflow/core/kernels': Package 'tensorflow/core/kernels' contains errors
> 

Any solution for this?

**Comment by reedwm** [comment]
Try using the latest version of TensorFlow (1.3 or master) and Bazel.

**Comment by gunan** [comment]
Bazel had quite a few backwards incompatible changes this year, so the error is definitely due to using an incompatible bazel version. You have two options:
- Use a new branch as @reedwm suggested
- Or use the appropriate bazel version, as listed at the bottom of this page: 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/install/install_sources.md
