### ISSUE TITLE
tf.image.resize_bicubic is 2x slower than opencv.resize(interpolation=INTER_CUBIC)

### ISSUE THREAD

**Issue by ftokarev** [tensorflow/tensorflow#13693]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**: --
- **CUDA/cuDNN version**: 8/6
- **GPU model and memory**: GCP Tesla P100 16Gb
- **Exact command to reproduce**: https://gist.github.com/ftokarev/43adbf1afacaa4bd612c55354c17b29b

tf.image.resize_bicubic is 2x slower than opencv.resize when used on input data with lots of channels.

40 channels:
 - opencv: 152.23ms
 - tf: 297.71ms

With three channels they perform about the same:
 - opencv: 11.02ms
 - tf: 11.76ms

**Comment by reedwm** [comment]
Using a feed dict can have a performance impact, so you should use a variable instead. Still, when I remove the feed dict, I get similar results: opencv takes 267.98ms and tensorflow takes 267.98ms.

@cwhipkey do you have time to look into this?

**Comment by reedwm** [comment]
Whoops, I meant to say, opencv takes 267.98ms and tensorflow takes 403.34ms.

Also, the code without the feed dict is:
```python
import time

import cv2
import numpy as np
import tensorflow as tf


ITERS = 100
BATCH_SIZE = 12
INPUT_SIZE = 48
N_CHANNELS = 40
SCALE_FACTOR = 8


sess = tf.Session()

images_ = tf.Variable(tf.random_normal((BATCH_SIZE, INPUT_SIZE, INPUT_SIZE, N_CHANNELS), dtype=tf.float32))
resized = tf.image.resize_bicubic(images_, (INPUT_SIZE*SCALE_FACTOR, INPUT_SIZE*SCALE_FACTOR))


def upscale_using_opencv():
    results = []
    for i in range(ITERS):
        images = np.random.rand(BATCH_SIZE, INPUT_SIZE, INPUT_SIZE, N_CHANNELS)
        start_time = time.time()
        _ = [
            cv2.resize(image, (0,0), fx=SCALE_FACTOR, fy=SCALE_FACTOR, interpolation=cv2.INTER_CUBIC)
            for image in images]
        results.append(time.time() - start_time)
        print(i)
    print('opencv: %0.2fms' % (np.average(results)*1000))


def upscale_using_tf():
    results = []
    sess.run(tf.global_variables_initializer())
    for i in range(ITERS):
        start_time = time.time()
        _ = sess.run(resized)
        if i == 0:
            continue
        results.append(time.time() - start_time)
        print(i)
    print('tf: %0.2fms' % (np.average(results)*1000))


upscale_using_opencv()
upscale_using_tf()
```

**Comment by ftokarev** [comment]
Interestingly, I tried using tf.Variable, and the code performed about the same:

using tf.Variable:
 - opencv: 152.87ms
 - tf: 303.75ms

using tf.placeholder:
 - opencv: 151.65ms
 - tf: 296.09ms

**Comment by cwhipkey** [comment]
The resize_bicubic kernel, for channels!=3 cases, has inner loops over channel and then width:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/resize_bicubic_op.cc
Probably we need to change this to do something different when there a large number of channels, perhaps taking the 3-channel logic and doing chunks of that size (or even 4-channel case).

There is a benchmark in tensorflow/core/kernels/resize_bicubic_op_test.cc where we can add a channels=40 case and test to improve its performance.

**Comment by yongtang** [comment]
Created a PR #13840 to try to address this issue. I could see there are quite some improvements by reorganizing the loops (so that the logic for `num_channels=40` and `num_channels=3` are similar). Please take a look
