### ISSUE TITLE
Problem with CuDNN RNNs on Windows

### ISSUE THREAD

**Issue by pawarrick** [tensorflow/tensorflow#13696]
OS: Windows10
Keras version: master (as of today: 2.08+)
Tensorflow backend version: master (as of today ~1.4rc0)

GPU: Geforce GTX 1080Ti (11GB)
Cuda version: v8.0
cuDNN version: cudnn-8.0-windows10-x64-v6.0

First opened as a Keras GitHub issue here (includes full code and error output):
https://github.com/fchollet/keras/issues/8135

Francois Chollet suggested that this may be a Windows TF problem.

Hi, I tried keras.layers.CuDNNLSTM after seeing fchollet's tweet the other day. I have the latest Keras and Tensorflow, but there is a tensorflow problem with the Op 'CudnnRNN' not being registered.

Have I missed something?

Thanks

**Comment by montusharma550** [comment]
I got it fixed using just importing LSTM from tensorflow 2.1.0  as stated by someone in this nvidia forum:

https://devtalk.nvidia.com/default/topic/1064345/cudnn/importerror-cannot-import-name-cudnnlstm-from-tensorflow-keras-layers-/

Also you have to keep in mind that CuDNNLSTM uses 'tanh' as activation function. So add also the argument of tanh activation function wherever you are using LSTM. For example, as shown in this sample code:

![Screenshot (13)_LI](https://user-images.githubusercontent.com/38489138/76697673-e41b4300-66bf-11ea-87bf-e19dbf72f636.jpg)

It will then automatically use CuDNNLSTM.
