### ISSUE TITLE
Compatibility with Bazel 0.8

### ISSUE THREAD

**Issue by vladmos** [tensorflow/tensorflow#13691]
Starting from Bazel 0.8 support for `set` constructors will be removed completely. Currently one of the dependencies, grpc, is not compatible with this: tensorflow uses an old version of it. grpc has already been fixed, please update your dependencies to use grpc with the following commit included: https://github.com/grpc/grpc/pull/12571/commits/759c7029b18f8bbcf6a6399d512abed8b6e12436

grpc is loaded as a `patched_http_archive`, you can also update the file `third_party/grpc/grpc.patch` to include the one-line patch from the commit above if it's more convenient.

Just updating grpc to head or to to the commit that has the fix is not trivial because `third_party/grpc/grpc.patch` then has to be updated as well. and as I don't know why those changes were necessary I don't know if I should keep, update or delete them when I update grpc.

**Comment by reedwm** [comment]
@gunan @yifeif can you update GRPC or include the patch?

**Comment by gunan** [comment]
Looks to me like @jhseu created this patch file.

Jonathan, if we upgrade grpc to head, do we still need the patch file?
What is your recommendation here?

**Comment by jhseu** [comment]
My understanding is that we no longer need the patch if we upgrade gRPC. @vjpai was going to look at upgrading it, but if someone wants to work on it, feel free (but please chat with me since there are a few things to keep in mind).

**Comment by vladmos** [comment]
An update: Bazel 0.7 has been released, the next version (0.8) will be cut in the beginning of November (probably November 6th) and it will be incompatible with the version of GRPC currently used by Tensorflow. It would be nice to update it before November so that repositories that depend on Tensorflow (for example, TF_serving and TF_models) can be updated too.

**Comment by gunan** [comment]
Please internally reach out to @jhseu to discuss how we should upgrade.

**Comment by vjpai** [comment]
The grpc upgrade is in progress at #13958

**Comment by vladmos** [comment]
It seems that grpc has already been updated, therefore I'm closing this pull request.
