### ISSUE TITLE
NET::ERR_CERT_COMMON_NAME_INVALID visiting https://download.tensorflow.org

### ISSUE THREAD

**Issue by justinwiley** [tensorflow/tensorflow#13702]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:

No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Chrome, mac os latest

- **TensorFlow installed from (source or binary)**:
N/A

- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

I'm following a tensorflow tutorial: https://www.tensorflow.org/versions/master/tutorials/audio_recognition

The tutorial references 'Speech Commands dataset', which points to https://download.tensorflow.org/data/speech_commands_v0.01.tar.gz

I follow that link in chrome and get:

"Your connection is not private

Attackers might be trying to steal your information from download.tensorflow.org (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: *.storage.googleapis.com
Issuer: Google Internet Authority G2
Expires on: Dec 26, 2017
Current date: Oct 13, 2017"

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by andydavis1** [comment]
I think we had some cert problems that are now fixed. @martinwicke Can you comment?

**Comment by martinwicke** [comment]
The tutorial should use the http link: http://download.tensorflow.org/data/speech_commands_v0.01.tar.gz

or better, this https link:
https://storage.cloud.google.com/download.tensorflow.org/data/speech_commands_v0.01.tar.gz

Because we're using GCS in a pretty bare-bones way, we don't have HTTPS for direct download.tensorflow.org links.

**Comment by martinwicke** [comment]
I sent a fix. Closing for now, should be fixed next time we publish the docs.
