### ISSUE TITLE
/tensorflow/core/lib/io/record_reader.h:83:19: error: use of undeclared identifier  'InputStreamInterface'   std::unique_ptr<InputStreamInterface> input_stream_;

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/tensorflow#13706]
When try to build iOS dependencies got this error. I simply run:
```
./tensorflow/contrib/makefile/build_all_ios_ssd.sh
```
And here is my env:

* macOS 10.13
* XCode 9

Any help would be every appreciated!
More detail errors:

```
In file included from tensorflow/core/lib/db/sqlite.cc:17:
./tensorflow/core/lib/io/record_reader.h:83:19: error: use of undeclared identifier
      'InputStreamInterface'
  std::unique_ptr<InputStreamInterface> input_stream_;
                  ^
1 error generated.
make: *** [/Volumes/xs/CodeSpace/ng/ai/frameworks/tensorflow/tensorflow/contrib/makefile/gen/obj/ios_ARM64/tensorflow/core/lib/db/sqlite.o] Error 1
make: *** Waiting for unfinished jobs....
+ '[' 2 -ne 0 ']'
+ echo 'arm64 compilation failed.'
arm64 compilation failed.
+ exit 1
```

**Comment by mrry** [comment]
What is the source of the `build_all_ios_ssd.sh` script? (I haven't been able to find that in the TensorFlow repository.)

**Comment by jinfagang** [comment]
@mrry Hi, thanks for watching. I am pretty sure I can access like this:
```
➜  tensorflow git:(master) ✗ ./tensorflow/contrib/makefile/build_all_ios.sh
build_all_ios.sh*      build_all_ios_ssd.sh*
```
which the `build_all_ios_ssd.sh` lying.
But I can not find this script in master branch repo too, so weird.
I try to run build_ios.sh it seems this is right, but build_all_ios_ssd.sh always fails.

**Comment by mrry** [comment]
Just to confirm: if you run `build_all_ios.sh`, does it build correctly?

Also, if you clone the Git repository into a clean checkout, does it contain the file `build_all_ios_ssd.sh`? I suspect it may have been left behind by an old version, but I'm not sure what might have created it (since it doesn't appear in the project's version control history).

**Comment by jinfagang** [comment]
I just cloned tensorflow last few days. it's build fail with above error. I am trying to run the object dection demo on iOS, is there any newest tutorial or link for this?

**Comment by mrry** [comment]
Unfortunately I've no idea which tutorial you are following. If you can share a link, that'd be helpful. I'd suggest starting from scratch and documenting the exact steps as you're taking, so that someone on the TF team can reproduce the problem.

**Comment by mrry** [comment]
After some searching, is this the tutorial that you're following?

https://github.com/JieHe96/iOS_Tensorflow_ObjectDetection_Example

It looks like this tutorial adds its own `Makefile` for building the tutorial:

https://github.com/JieHe96/iOS_Tensorflow_ObjectDetection_Example/blob/452dbcb5a4fdd20de0d2b4df4a25bdd8f34c2bda/config/makefile/Makefile_ios

That `Makefile_ios` isn't compatible with the `master` branch of TensorFlow... I'd suggest filing an issue against that tutorial. However, it might be compatible with the `r1.4` branch of TensorFlow, so you could try checking out that branch then rerunning the script.

**Comment by jinfagang** [comment]
Thank you Pal, you are almost like a magician knows what I am exactly thinking.
