### ISSUE TITLE
MultiRNNCell with different cell sizes

### ISSUE THREAD

**Issue by joseangl** [tensorflow/tensorflow#1370]
When I try to create a MultiRNNCell with different number of units in the recurrent cells (e.g. 5-layer RNN with 32-64-32 GRUCells in the hidden layers) I got the following error:

`ValueError: In MultiRNNCell, the input size of each next cell must match the output size of the previous one. Mismatched output size in cell 0.`

Is it currently possible to create a MultiRNNCell with different number of hidden units?

**Comment by rdipietro** [comment]
It's pretty much what it says: when you construct the cells, every next cell's input must have the same size as the previous cell's output. Unless it's changed recently, BasicLSTMCell makes the input size and the hidden size = output size the same. So it can't be used for what you're trying to do. If you're using that, take a look at LSTMCell instead, where you can specify the sizes separately.

**Comment by nryant** [comment]
All the cells implemented in ``rnn_cell`` allow specification of the input size via ``input_size``, which by default is set to equal ``num_units``.

**Comment by rdipietro** [comment]
That wasn't true a short time ago. Just checked. If he's using 0.6.0 or r0.7, then `BasicLSTMCell` doesn't accept input size.

**Comment by joseangl** [comment]
Yes, I'm using TF r0.7 and, as Robert says, you can specify the output size only for the LSTMCell.

**Comment by girving** [comment]
@ebrevdo Is this still an issue?

**Comment by ebrevdo** [comment]
Should be fixed now.

**Comment by m-kammoun** [comment]
So how is it possible to stack multiple cells with different number of units ?

**Comment by archiki** [comment]
The LSTMCell does not seem to have output_size as a valid argument, so how should one stack lstm layers with different sizes ?
https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/LSTMCell
