### ISSUE TITLE
`tf.reverse_sequence` does not support bool sequence

### ISSUE THREAD

**Issue by ligaoheng** [tensorflow/tensorflow#13717]
It seems that `tf.reverse_sequence` can not reverse bool sequence.

**Comment by yongtang** [comment]
As #13719 is merged I think this issue could be closed.

You could also specify in then PR with things like `This PR fixes #13717.` Then when the PR is merged the associated issue will be closed automatically.

**Comment by betterenvi** [comment]
@yongtang 
Thanks!
