### ISSUE TITLE
--config=mkl leads to libmklml_intel.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by llealgt** [tensorflow/tensorflow#13711]
I compiled passing --config=mkl to bazel, it compiles fine and i get the .whl file, i install it with pip correctly, but when i launch a python session and type : import tensorflow as tf i get:
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

Any ideas?

**Comment by gunan** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by RenfengLiu** [comment]
I had the same problem, compiled successfully with --config=mkl on Ubuntu 16.04, and installed the whl with pip. But in python code, when you run  `import tensorflow as tf`, I got following error message
```
ImportError: Traceback (most recent call last):
  File "/home/robin/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/robin/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/robin/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by rylz** [comment]
I had the same problem and after many attempts to install the base intel-mkl distribution and finding that it did not include a library called libmklml_intel.so, I found the following Intel repo that builds this library: https://github.com/01org/mkl-dnn

I followed their installation instructions and tensorflow started working. Note that it installs to /usr/local/lib by default, so you may need to add that to your `LD_LIBRARY_PATH` depending on your current configuration.

**Comment by yingted** [comment]
I have the same problem. It looks like this error is caused by `libmklml_intel.so` not being included

Related commit: fbbe5cd5407a43feb858cacc2fd110804987cff6
Related issue: https://github.com/tensorflow/tensorflow/pull/12975

**Comment by Immexxx** [comment]
Verified Solution: If others hit this page, change the code as per @yingted git commit (instead of trying to install the base Intel-MKL), rebuild using bazel (which finished very quickly) and you should see that the new .whl is about 30M more that the previous one 

Using the new .whl to install (with the -I option if required) and the import should work correctly

**Comment by DakshMiglani** [comment]
Fix for this is:

```sh
# If you don't have cmake
sudo apt install cmake

git clone https://github.com/01org/mkl-dnn.git
cd mkl-dnn/scripts && ./prepare_mkl.sh && cd ..
mkdir -p build && cd build && cmake .. && make
sudo make install

# if using bash then
echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib' >> ~/.bashrc
```

If you're using zsh instead of bash, omit the last line with:
```sh 

echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib' >> ~/.bashrc

```

**Comment by syedmohsinbukhari** [comment]
@DakshMiglani Thanks. Do I have to compile tensorflow again?

**Comment by YerongLi** [comment]
Following MKL instruction here does not gives necessary libmklml_intel.so file in the library.
[https://github.com/mind/wheels#mkl](url). 

Anyone knows how to follow MKL README [https://github.com/intel/mkl-dnn](url) in order to generate **libmklml_intel.so**?

**Comment by krips89** [comment]
> ```shell
> prepare_mkl.sh
> ```

There is no prepare_mkl.sh  in the scripts directory

**Comment by mbrio** [comment]
I'm having the same problem, it would seem that all of these instructions are out dated because I can't even find a version of the MKL-DNN library specified above that has the prepare_mkl.sh file. I wish there was some place on the Tensorflow docs that described what versions were necessary of MKL and MKL-DNN because I think it's probably developed for an older version.

**Comment by mbrio** [comment]
I'd like to amend what I said in my previous post, it would seem as though the prepare_mkl.sh file exists in the v0.21.3 tag's files not the v1.1.3 tag.
