### ISSUE TITLE
 Build tensorflow 1.0.1 for bug on jetson TX2

### ISSUE THREAD

**Issue by molyswu** [tensorflow/tensorflow#13725]
Hi,
Build tensorflow 1.0.1 for bug on jetson TX2
$ ./cloneTensorFlow.sh$ 
$./setTensorFlowEV.sh
$ ./buildTensorFlow.sh

ERROR: /home/nvidia/tensorflow/tensorflow/core/kernels/BUILD:685:1: output 'tensorflow/core/kernels/_objs/tile_ops_gpu/tensorflow/core/kernels/tile_ops_gpu.cu.pic.o' was not created.
ERROR: /home/nvidia/tensorflow/tensorflow/core/kernels/BUILD:685:1: not all outputs were created or valid.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3022.881s, Critical Path: 2684.15s

Thank you for your help

**Comment by molyswu** [comment]
bazel build -c opt --jobs 1 --local_resources 2048,0.5,1.0 --verbose_failures --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Comment by drpngx** [comment]
Can you paste more logs to pastebin?

**Comment by wt-huang** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
