### ISSUE TITLE
Feature request: bitwise operations on boolean tensors

### ISSUE THREAD

**Issue by tsoernes** [tensorflow/tensorflow#13723]
Currently, bitwise operations such as OR, AND only take integers.
It would be nice to be able to feed boolean tensors, e.g. `tf.zeros(4, dtype=tf.bool)` or to be able to bitcast an axis of a boolean tensor to an int.

**Comment by facaiy** [comment]
Perhaps tf.cast could be useful.

**Comment by tsoernes** [comment]
Only much later do I realize that `logical_or` etc. does exactly what I'm asking for; hopefully these operations are as fast as the bitwise equivalent.
