### ISSUE TITLE
Compilation error: missing dependency declarations ... external/re2/util/rune.cc

### ISSUE THREAD

**Issue by rdipietro** [tensorflow/tensorflow#1372]
### Environment info
Operating System: CentOS 6.7

If installed from sources, provide the commit hash: eda89e930cfcbd992ecacafd40267d733e2153dc

### Steps to reproduce
1. ./configure (CUDA enabled)
2. bazel build -c opt --config=cuda --verbose_failures --genrule_strategy=standalone --spawn_strategy=standalone //tensorflow/cc:tutorials_example_trainer

### What have you tried?
1. Using --genrule_strategy=standalone --spawn_strategy=standalone as possible solutions from other errors that seem related, but this doesn't work.

### Logs or other output that would be helpful

```
WARNING: Output base '/home-4/rdipiet2@jhu.edu/.cache/bazel/_bazel_rdipiet2@jhu.edu/549db212089e33b4d213773753834e47'
 is on NFS. This may lead to surprising failures and undetermined behavior.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. Se
e http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ig
nore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /home-4/rdipiet2@jhu.edu/.cache/bazel/_bazel_rdipiet2@jhu.edu/549db212089e33b4d213773753834e47/external/re2/BU
ILD:9:1: undeclared inclusion(s) in rule '@re2//:re2':
this rule is missing dependency declarations for the following files included by 'external/re2/util/rune.cc':
  '/cm/shared/apps/gcc/4.8.2/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/include/stdarg.h'
  '/cm/shared/apps/gcc/4.8.2/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/include/stddef.h'
  '/cm/shared/apps/gcc/4.8.2/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/include/stdint.h'.
Target //tensorflow/cc:tutorials_example_trainer failed to build
INFO: Elapsed time: 5.291s, Critical Path: 2.47s
```

### Other Info

I was able to compile Bazel with older libc, and now I'm hoping I can compile TensorFlow on this server. Any help will be very much appreciated.

**Comment by vrv** [comment]
Are you able to use bazel to compile the re2 library from https://github.com/google/re2 by itself?  If not, you might want to file the issue with either re2 / bazel, since this looks like it's not Tensorflow related from a first glance.

**Comment by rdipietro** [comment]
I just cloned google/re2 alone and ran

`bazel build -c opt --config=cuda --verbose_failures --genrule_strategy=standalone --spawn_strategy=standalone :re2`

I get no errors and bazel-bin is populated appropriately.

**Comment by rdipietro** [comment]
I just realized that TensorFlow has a similar CROSSTOOL file with the same hard-coded paths as bazel. I'll try updating these in the same way that I did with bazel and see what happens / will update soon.

**Comment by rdipietro** [comment]
I got by this error but am still stuck. Will open another issue as it has nothing to do with this one. In case others have this problem:

See https://github.com/bazelbuild/bazel/issues/760

You need to edit tensorflow/third_party/gpus/crosstool/CROSSTOOL and make the same gcc / cpp / linker_flag / cxx_builtin_include_directory adjustments.
