### ISSUE TITLE
libtensorflow_cc.so need to work on single (but not specific) core. (feature request)

### ISSUE THREAD

**Issue by Bocharick** [tensorflow/tensorflow#13742]
I use self builded libtensorflow_cc.so shared library in my c++ model "player" program. I builded *.so for cpu-only usage. But by default in runtime it uses all cores. But I want to use only one core.
If i run my program through taskset, for example, I can use specific mask:
$taskset -c 0 ./my_program param1 param2
And it will perfectly work, but only on 0-th core of my cpu. And if I run several parallel programs with theese parameters all of them will work on 0-th core, while another cores are free.
I need that for my service, for several parallel program works on different cores.
How can I build libtensorflow_cc.so WITHOUT multi-threading? Or maybe how can I configure it for single-core (but I repeat, not specific core)?
Thank you.

**Comment by andydavis1** [comment]
You can control the number of threads in SessionConfig by setting inter and intra op parallelism.

In general questions like this should be asked on StackOverflow.
