### ISSUE TITLE
graph_editor uses deprecated API

### ISSUE THREAD

**Issue by peastman** [tensorflow/tensorflow#13754]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.12
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: b'v1.3.0-21-gc701d19b2' 1.3.0
- **Python version**: 3.6.0
- **Bazel version (if compiling from source)**: 0.5.1
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: See below

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
When I use graph_editor, my console fills up with dozens of repetitions of the following error message:

```
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
```
The number of repetitions of the message scales with the number of tensors being copied and can get very large.  To reproduce the problem, run the script below.

### Source code / logs
```python
import tensorflow as tf

x = tf.Variable(1.0)
y = tf.Variable(2.0)
a = x+1
replace = {tf.convert_to_tensor(x):tf.convert_to_tensor(y)}
b = tf.contrib.graph_editor.graph_replace(a, replace)
```

**Comment by yaroslavvb** [comment]
Work-around

`setattr(tf.GraphKeys, "VARIABLES", "variables")`

The reason this warning happens is because graph_editor programmatically scans all values in GraphKeys and each time you access tf.GraphKeys.VARIABLES, it issues a warning.

**Comment by andydavis1** [comment]
Thanks again @yaroslavvb!
