### ISSUE TITLE
How are threads bound to physical cores in TensorFlow runtime and inter/intra threadpools?

### ISSUE THREAD

**Issue by Jiawen1991** [tensorflow/tensorflow#13762]
Hi all,

If one CPU has 8 cores and each core has two threads, does TF runtime use the OS threads scheduler to match the logical cores and threads to the physical cores and threads? Or does it has its own policy to match the threads and cores? Does TF only recognize cores and but not the whole device(CPU) like the system does? (The OS only knows the number/id of cores and sockets and doesn't know how many CPU devices) Does the "device" in TF correspond to the physical core, e.g., TF recognizes 8 devices in the above CPU?

I found out that there are inter/intra global and local threadpools in /tensorflow/core/common_runtime/local_device.cc and /tensorflow/core/common_runtime/dirrect_session.cc. Does that mean each device (or core?) have its own local inter/intra threadpool and there is only one inter/intra global threadpool in the whole TF runtime?

Thank you for your time.

**Comment by andydavis1** [comment]
TF does not pin threads to cores (though if you build with MKL, I believe that Intel's internal thread pool implementation does (and probably makes use of hyperthreads if it makes sense.

Thanks for your question, but please ask these types of questions on Stackoverflow...
