### ISSUE TITLE
tf.reduce_sum gives value error when given int64 as input.

### ISSUE THREAD

**Issue by kevinj22** [tensorflow/tensorflow#13761]
Passing a tensor of dtype=int64 into tf.reduce sum I receive the following error:

Tensor("loss/diff:0", shape=(50,), dtype=int64)
ValueError: Invalid type tf.int64 for loss/Sum:0, expected: [tf.float32, tf.float64, tf.float16].

According to the documents from https://www.tensorflow.org/api_docs/python/tf/reduce_sum:

input_tensor: The tensor to reduce. Should have numeric type.

As int64 is a numeric type I am not sure what's wrong. 

To create the diff tensor I do:

```
        self.predictions = tf.argmax(self.logits, 1, name='predictions')

         # Loss
        with tf.name_scope("loss"):
            self.diff = tf.subtract(self.predictions, self.targets)
            self.diff = tf.multiply(self.diff,self.diff, name='diff')
            print self.diff
            self.diff = tf.reduce_sum(self.diff)
```

Where predictions is of type int64 and my targets placeholder is also of type int64.

Is this a tensorflow error or an error on my end?

**Comment by facaiy** [comment]
Could you list all the environment information required by issue template?

**Comment by kevinj22** [comment]
Sure:

System information

Linux Ubuntu 16.04
TensorFlow installed via pip from (source or binary)**:
Tensorflow Version: v1.3.0-rc2-20-g0787eee
Python 2.7.12
CUDA Version 8.0.61
cuDNN V5 (I believe)
GeForce GTX 1070 and GeForce GTX 780 Ti

**Comment by drpngx** [comment]
OK, looking at the comment in the code, it looks like we have `int32` as a special case, but not `int64`. There appears to be some subtlety around the implementation.

Maybe @mrry can clarify.

**Comment by drpngx** [comment]
Now it's coming back to me. IIRC, because meta-data information is stored on the host, running operations on GPU was slower because of the overhead. So we have traditionally stayed away from integer operations on GPU. Not sure if that changed.

In your case, you can still cast to int32 where the op is implemented.

**Comment by kevinj22** [comment]
I tried making all tensors involved into int32's:

```
self.targets = tf.placeholder(tf.int32, [batchSize])
self.predictions = tf.argmax(self.logits, 1, output_type=tf.int32, name='predictions')
```

Although I still receive the same error.

ValueError: Invalid type tf.int32 for loss/Sum:0, expected: [tf.float32, tf.float64, tf.float16].

I don't believe I can cast in this instance as casting is an operation that doesn't create a gradient. I initially tried casting both tensors to tf.float32 and using tf.losses.mean_squared_error but I received a 'ValueError: No gradients provided for any variable'. This is an attempt at a possible work around.

**Comment by drpngx** [comment]
Oh, when does it crash? If it's integer, I am not sure how the gradient would work. Instead of `argmax`, you'll want to train against the likelihood loss.

**Comment by kevinj22** [comment]
I am attempting to implement the one hot cnn as described here : https://arxiv.org/pdf/1412.1058.pdf

In the paper Rie Johnson mentions they minimize square loss. I also read https://arxiv.org/abs/1702.05659 which states that loss functions other than the most popular log loss sometimes produce better results.

I had the CNN working with cross entropy:

```
 losses = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=self.targets, logits=self.logits,
                name="xentropy")
            self.loss = tf.reduce_mean(losses)
```

but wish to try some other loss functions to see if I can get an accuracy boost. 

If I change my loss to:

self.loss = tf.reduce_mean(tf.losses.mean_squared_error(labels=self.targets, predictions=self.predictions))

This is the error message I receive:

```
Traceback (most recent call last):
  File "cnn_Sparse_TwoFilt.py", line 261, in <module>
    train_op = optimizer.minimize(cnn.loss, global_step=global_step)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 322, in minimize
    ([str(v) for _, v in grads_and_vars], loss))
ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables ["<tf.Variable 'conv-maxpool-1/W:0' shape=(28395, 50) dtype=float32_ref>", "<tf.Variable 'conv-maxpool-1/b:0' shape=(50,) dtype=float32_ref>", "<tf.Variable 'conv-maxpool-2/W:0' shape=(56790, 50) dtype=float32_ref>", "<tf.Variable 'conv-maxpool-2/b:0' shape=(50,) dtype=float32_ref>", "<tf.Variable 'output/W:0' shape=(100, 20) dtype=float32_ref>", "<tf.Variable 'output/b:0' shape=(20,) dtype=float32_ref>"] and loss Tensor("loss/Mean:0", shape=(), dtype=float32).
```

**Comment by drpngx** [comment]
Can you describe a bit more what `targets` are? It sounds strange. I think you're meaning to use
`[p(y|x)-I(x,y)]^2`.

**Comment by kevinj22** [comment]
The ground truth labels, they are integer's denoting the location of the proper class index.

**Comment by drpngx** [comment]
Right. So, is there a special order in the labels that would make you want to prefer that loss? In that case, if you misclassify `1` for `10`, it's not the same as if you misclassify `1` for `2`.

**Comment by kevinj22** [comment]
That is true, the further apart the classification indexes the larger the weight of that error would be. If the classification indexes were grouped closely together this might make a difference i.e cars, trucks, and vans could be 1,2,3 while something unrelated to these likes dogs and cats could be 9 and 10.

I recently saw https://arxiv.org/abs/1702.05659 which states that loss functions other than the most popular log loss sometimes produce better results for classification asks. It would be nice to have the option to try.

**Comment by drpngx** [comment]
In the sentiment classification case, it's better to use something like `p(like|x)`, then map from `0-1` to `1-5`. The point is that you want the soft estimate, which is differentiable. It can be made arbitrarily sharp by scaling the logits.

I will close this since this is not strictly a bug. Feel free to start a discussion on stackoverflow.

**Comment by rajanlagah** [comment]
Hey i am facing same type issue 
I want to feed calculated loss ( which is self.calc_loss and its value is 1.0288568 )
to 
`self.sess.run(tf.compat.v1.train.AdamOptimizer().minimize(d_reward_sum))`
then it shows error 

> AttributeError: 'numpy.dtype' object has no attribute 'base_dtype'

If i use placeholder 

```
self.calc_loss = tf.placeholder(tf.float32) 
self.train_opt = tf.compat.v1.train.AdamOptimizer().minimize(self.calc_loss)
...   
train_modal = self.sess.run([self.train_opt],feed_dict = {
            self.calc_loss :d_reward_sum ,
        })
```

then it give error 

> ([str(v) for _, v in grads_and_vars], loss))
> ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables ["<tf.Variable 'Variable:0' shape=(4, 24) dtype=float32_ref>", "<tf.Variable 'Variable_1:0' shape=(24,) dtype=float32_ref>", "<tf.Variable 'Variable_2:0' shape=(24, 12) dtype=float32_ref>", "<tf.Variable 'Variable_3:0' shape=(12,) dtype=float32_ref>", "<tf.Variable 'Variable_4:0' shape=(12, 4) dtype=float32_ref>", "<tf.Variable 'Variable_5:0' shape=(4,) dtype=float32_ref>", "<tf.Variable 'Variable_6:0' shape=(4, 2) dtype=float32_ref>"] and loss Tensor("Placeholder:0", dtype=float32).

**Comment by rajanlagah** [comment]
I also have stackoverflow question 
Unable to get help 
Will glad if any one can help 
https://stackoverflow.com/questions/61174513/tensorflow-custom-loss-feed

**Comment by drpngx** [comment]
You need to pass tensors. In the first example, it looks like you put a
numpy object. This needs to be a tensorflow object, otherwise we won't know
how to compute the gradient, because we need to keep track of the
computation that led to it. Same for the second example.

You need something like this:
```
v = tf.Variable([init_value])
# Example:
l = tf.reduce_sum((v - 1.) * (v - 1.))
opt = tf.AdamOptimizer().minimize(l)
```
