### ISSUE TITLE
Failure in TestNewTensor when running go test

### ISSUE THREAD

**Issue by vishvananda** [tensorflow/tensorflow#13764]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source (branch 1.4)
- **TensorFlow version (use command below)**: 1.4.0-dev
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 8.0/6.0
- **GPU model and memory**: nVidia 1080Ti 11G
- **Exact command to reproduce**: go test -v github.com/tensorflow/tensorflow/tensorflow/go

### Describe the problem

I'm trying to use the go bindings to the tensorflow c library. When I run the tests, I get a nil pointer dereference and a segfault. The details are below. Note that I've built the c library from source using the following options:

`bazel build -c opt --config=cuda --config=mkl -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 -c opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow:libtensorflow.so`

### Source code / logs
When I run go test -v github.com/tensorflow/tensorflow/tensorflow/go I get the following error:
```
2017-10-16 17:12:30.568054: E tensorflow/core/common_runtime/bfc_allocator.cc:244] tried to allocate 0 bytes
2017-10-16 17:12:30.568065: W tensorflow/core/common_runtime/allocator_retry.cc:32] Request to allocate 0 bytes
--- FAIL: TestNewTensor (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x536098]

goroutine 168 [running]:
testing.tRunner.func1(0xc42059c4e0)
        /usr/lib/go-1.8/src/testing/testing.go:622 +0x29d
panic(0x6a0b80, 0xa18e80)
        /usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
github.com/tensorflow/tensorflow/tensorflow/go.tensorData(0x7fa8f40195b0, 0xc420595900, 0x688a80, 0x6ffb90)
        /home/vishvananda/go/src/github.com/tensorflow/tensorflow/tensorflow/go/tensor.go:209 +0x48
github.com/tensorflow/tensorflow/tensorflow/go.NewTensor(0x683d20, 0xc4205945e0, 0xc42004d9a0, 0x2, 0x2)
        /home/vishvananda/go/src/github.com/tensorflow/tensorflow/tensorflow/go/tensor.go:92 +0x221
github.com/tensorflow/tensorflow/tensorflow/go.TestNewTensor(0xc42059c4e0)
        /home/vishvananda/go/src/github.com/tensorflow/tensorflow/tensorflow/go/tensor_test.go:92 +0x2526
testing.tRunner(0xc42059c4e0, 0x6ffbd0)
        /usr/lib/go-1.8/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
        /usr/lib/go-1.8/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL    github.com/tensorflow/tensorflow/tensorflow/go  0.443s
```
Adding some debugging, it turns out that the TestNewTensor test fails when attempting to create the following tensor `{[]int64{2, 0}, [][]int64{{}, {}}}`. If I comment out that line, the tests pass.

**Comment by vishvananda** [comment]
It looks like this is due to the fact that TF_TensorData returns nil if no data is allocated. Assuming this is correct behavior and nil needs to be checked for on the go side then the following patch fixes the problem:
```
diff --git a/tensorflow/go/tensor.go b/tensorflow/go/tensor.go
index e8fa21a..365ad94 100644
--- a/tensorflow/go/tensor.go
+++ b/tensorflow/go/tensor.go
@@ -206,7 +206,10 @@ func tensorData(c *C.TF_Tensor) []byte {
        // See: https://github.com/golang/go/wiki/cgo#turning-c-arrays-into-go-slices
        cbytes := C.TF_TensorData(c)
        length := int(C.TF_TensorByteSize(c))
-       slice := (*[1 << 30]byte)(unsafe.Pointer(cbytes))[:length:length]
+       slice := []byte{}
+       if cbytes != nil {
+               slice = (*[1 << 30]byte)(unsafe.Pointer(cbytes))[:length:length]
+       }
        return slice
 }
```

**Comment by asimshankar** [comment]
Thanks for the report @vishvananda. I'm unable to reproduce the problem using the [1.3.0 release binary]("https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-1.3.0.tar.gz"), or [1.4.0-rc0 release binary](https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-1.3.0.tar.gz) (will try rebuilding from source using the exact flags you're using). Do you see the same problem when using the release binaries of the C API?

Which version of `go` are you using? Also, is it possible that `LD_LIBRARY_PATH` is somehow bringing in an older version of the C API libraries that your go program ends up using?

It should be okay for `TF_TensorData` to return `nil`.

Any additional information in reproducing the environment will be helpful. (I'll try to dig into this a bit more by rebuilding from source using the command you provided above)

**Comment by vishvananda** [comment]
Fascinating, both the 1.3.0 and the 1.4.0-rc0 release binary return zero length from TF_TensorData but they return a pointer to an actual buffer instead of nil. I'm attempting my flags on the 1.3 branch to see if it is the flags that are causing it to return nil. Next, I'll try removing the extra flags one at a time to see if I can narrow it down. I suspect AllocateTensor ends up with a nil buffer in certain cases. In the successful versions I don't see this error message:
```
2017-10-16 21:31:57.797656: E tensorflow/core/common_runtime/bfc_allocator.cc:244] tried to allocate 0 bytes
2017-10-16 21:31:57.797690: W tensorflow/core/common_runtime/allocator_retry.cc:32] Request to allocate 0 bytes
```
In any case the nil check is probably good to have anyway.

**Comment by vishvananda** [comment]
Ok, I think I've tracked down the issue to building with MKL. If I build without `--config=mkl` the tests pass fine. The issue is that building with MKL uses the bfc_allocator to allocate memory. That allocator explicitly returns nil when an allocation of zero bytes is performed (As a side note, this probably should not be an error or warning if we expect it to happen when we request a zero length tensor). In the case of running without MKL, the allocation eventually calls malloc (or jemalloc or alloc_aligned). The man tells me that malloc(0) is implementation defined and our version returns a non-nil pointer so the code does not throw a null-pointer exception. I suggest using something like the patch I included above for the go side, and maybe downgrading the error and warning messages in bfc_allocator.cc and allocator_retry.cc to something a bit less scary (maybe Info?).

**Comment by asimshankar** [comment]
Thanks for the detailed trackdown @vishvananda, much appreciated.

Yes, what you said makes sense. For the Go side, would you like to contribute a pull request to make the fix? If not, let me know and I'm happy to make the change as well.

Thanks!
