### ISSUE TITLE
Packages missing in current channels: - tensorflow

### ISSUE THREAD

**Issue by waveroarer** [tensorflow/tensorflow#13768]
I typed the following in the Anaconda Prompt
"
conda create --name=IntroToTensorFlow python=3 anaconda
source activate IntroToTensorFlow
conda install -c conda-forge tensorflow"

Then it shows

Packages missing in current channels: 
      -  tensorflow
- http://conda.anaconda.org/conda-forge/win-32
- http://conda.anaconda.org/conda-forge/noarch
- http://repo.continuum.io/pkgs/main/win-32
- http://repo.continuum.io/pkgs/main/noarch
- http://repo.continuum.io/pkgs/free/win-32
- http://repo.continuum.io/pkgs/free/noarch
- http://repo.continuum.io/pkgs/r/win-32
- http://repo.continuum.io/pkgs/r/noarch
- http://repo.continuum.io/pkgs/pro/win-32
- http://repo.continuum.io/pkgs/pro/noarch
- http://repo.continuum.io/pkgs/msys2/win-32
- http://repo.continuum.io/pkgs/msys2/noarch

**Comment by yaroslavvb** [comment]
btw, conda-forge is community maintained, the maintainers may be able to answer https://github.com/conda-forge/tensorflow-feedstock/

**Comment by andydavis1** [comment]
Thanks @yaroslavvb. Please pose this question to the conda-forge community.
