### ISSUE TITLE
Cannot install Tensorflow with specific GCC version

### ISSUE THREAD

**Issue by wichtounet** [tensorflow/tensorflow#13774]
I'm trying to install Tensorflow 1.3 without success 

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Gentoo
- **TensorFlow installed from (source or binary)**: Trying from source
- **TensorFlow version (use command below)**: 1.3
- **Python version**: 3.4.5
- **Bazel version (if compiling from source)**: 0.5.2
- **CUDA/cuDNN version**: 8.0 / 5.1.5
- **GPU model and memory**: GTX 960
- **Exact command to reproduce**: bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

### Describe the problem

I'm trying to install Tensorflow 1.3 (branch r1.3) from sources on my Gentoo machine. 

The problem with the default compiler is that it it's a version 6.3 that is not supported by Tensorflow: I've tried and got an error indicating that GCC later than 5 are not supported. 
Therefore, I need to specify a specific GCC version. I'm setting it via $CC/$CXX and in the installation for CUDA:

`build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/gcc-5.4.0"`

But when I try to run bazel, I got the following error: 

> gcc-5.4.0: error trying to exec 'cc1': execvp: No such file or directory

What can I do to install Tensorflow using /usr/bin/gcc-5.4.0 and /usr/bin/g++-5.4.0 rather than /usr/bin/gcc ? 

I've seen this f0faf5139819e2c6d7b0437d9e03ffce71c7d6e5 that seems releated, but in my case, this is already done. And it seems to be used for clang compilation anyway. 

### Source code / logs

> ____Loading complete.  Analyzing...
> WARNING: /home/wichtounet/dev/tensorflow13/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately..
> WARNING: /home/wichtounet/dev/tensorflow13/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately..
> ____Found 1 target...
> ____Building...
> ____[3 / 255] Writing file external/snappy/libsnappy.a-2.params [for host]
> ERROR: /home/wichtounet/.cache/bazel/_bazel_wichtounet/bb5d0ce0cffd837b9339296f34d5478c/external/nasm/BUILD.bazel:8:1: C++ compilation of rule '@nasm//:nasm' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 34 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
> gcc-5.4.0: error trying to exec 'cc1': execvp: No such file or directory
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> ____Elapsed time: 0.285s, Critical Path: 0.08s

**Comment by andydavis1** [comment]
@jart Can you comment on how to override to a supported version of GCC here?
You might also try stackoverflow for some help...

**Comment by wichtounet** [comment]
I ended up changing the configuration of my computer in order to have GCC 4.9 as the default compiler to compile Tensorflow.
