### ISSUE TITLE
No OpKernel was registered to support Op 'StridedSlice'

### ISSUE THREAD

**Issue by formath** [tensorflow/tensorflow#13772]
I trained a model via python and load the freeze model for prediction using c++. When running prediction binary, some errors occur.

OS: macOS 10.12.6
Tensorflow: master. built from source via `makefile/build_all_ios.sh`

Deadly error:
```
Invalid argument: No OpKernel was registered to support Op 'StridedSlice' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BOOL]
  device='CPU'; T in [DT_BFLOAT16]

	 [[Node: emb_179/embedding_lookup_sparse/strided_slice = StridedSlice[Index=DT_INT32, T=DT_INT64, begin_mask=1, ellipsis_mask=0, end_mask=1, new_axis_mask=0, shrink_axis_mask=2](input/linear_179/index/Placeholder, emb_179/embedding_lookup_sparse/strided_slice/stack, emb_179/embedding_lookup_sparse/strided_slice/stack_1, emb_179/embedding_lookup_sparse/strided_slice/stack_2)]]
```

Full error message:
```
Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Session created successfully
Load graph protobuf successfully
2017-10-17 12:51:52.708004: E tensorflow/core/framework/op_kernel.cc:1142] OpKernel ('op: "PopulationCount" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } }') for unknown op: PopulationCount
2017-10-17 12:51:52.708091: E tensorflow/core/framework/op_kernel.cc:1142] OpKernel ('op: "BitwiseAnd" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT8 } } }') for unknown op: BitwiseAnd
2017-10-17 12:51:52.708111: E tensorflow/core/framework/op_kernel.cc:1142] OpKernel ('op: "BitwiseXor" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT8 } } }') for unknown op: BitwiseXor
2017-10-17 12:51:52.708138: E tensorflow/core/framework/op_kernel.cc:1142] OpKernel ('op: "EncodeWav" device_type: "CPU"') for unknown op: EncodeWav
2017-10-17 12:51:52.708147: E tensorflow/core/framework/op_kernel.cc:1142] OpKernel ('op: "DecodeWav" device_type: "CPU"') for unknown op: DecodeWav
2017-10-17 12:51:52.708188: E tensorflow/core/framework/op_kernel.cc:1142] OpKernel ('op: "Mfcc" device_type: "CPU"') for unknown op: Mfcc
2017-10-17 12:51:52.708205: E tensorflow/core/framework/op_kernel.cc:1142] OpKernel ('op: "Invert" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT8 } } }') for unknown op: Invert
2017-10-17 12:51:52.708277: E tensorflow/core/framework/op_kernel.cc:1142] OpKernel ('op: "BitwiseOr" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT8 } } }') for unknown op: BitwiseOr
2017-10-17 12:51:52.708346: E tensorflow/core/framework/op_kernel.cc:1142] OpKernel ('op: "AudioSpectrogram" device_type: "CPU"') for unknown op: AudioSpectrogram
Invalid argument: No OpKernel was registered to support Op 'StridedSlice' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BOOL]
  device='CPU'; T in [DT_BFLOAT16]

	 [[Node: emb_179/embedding_lookup_sparse/strided_slice = StridedSlice[Index=DT_INT32, T=DT_INT64, begin_mask=1, ellipsis_mask=0, end_mask=1, new_axis_mask=0, shrink_axis_mask=2](input/linear_179/index/Placeholder, emb_179/embedding_lookup_sparse/strided_slice/stack, emb_179/embedding_lookup_sparse/strided_slice/stack_1, emb_179/embedding_lookup_sparse/strided_slice/stack_2)]]
```

**Comment by andydavis1** [comment]
please include a reproducible test case. One way this error can occur is if the op kernel is not registered for the specific data type you are using: float, double, etc...

**Comment by formath** [comment]
@andydavis1 
Because the code is too much, I just put the core part here.

During training, the inputs to `embedding_lookup_sparse` are `tf.int64`. It works fine. After training, the node info of `emb_179/embedding_lookup_sparse/strided_slice` is 
```
node {
  name: "emb_179/embedding_lookup_sparse/strided_slice"
  op: "StridedSlice"
  input: "input/ParseExample/ParseExample:1"
  input: "emb_179/embedding_lookup_sparse/strided_slice/stack"
  input: "emb_179/embedding_lookup_sparse/strided_slice/stack_1"
  input: "emb_179/embedding_lookup_sparse/strided_slice/stack_2"
  attr {
    key: "Index"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "T"
    value {
      type: DT_INT64
    }
  }
  attr {
    key: "begin_mask"
    value {
      i: 1
    }
  }
  attr {
    key: "ellipsis_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "end_mask"
    value {
      i: 1
    }
  }
  attr {
    key: "new_axis_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "shrink_axis_mask"
    value {
      i: 2
    }
  }
}
```
python part. It works fine. Because too much code, just put the core part here.
```
with tf.variable_scope('input/sparse_field'):
    with tf.variable_scope('index'):
        sparse_index = tf.placeholder(tf.int64)
    with tf.variable_scope('id'):
        sparse_id = tf.placeholder(tf.int64)
    with tf.variable_scope('value'):
        sparse_val = tf.placeholder(tf.float32)
    with tf.variable_scope('shape'):
        sparse_shape = tf.placeholder(tf.int64)
with tf.variable_scope('label'):
    label = tf.placeholder(tf.float32)
sparse_ids.append(tf.SparseTensor(sparse_index, sparse_id, sparse_shape))
sparse_vals.append(tf.SparseTensor(sparse_index, sparse_val, sparse_shape))

input_size = 100
embedding_size = 50
with tf.variable_scope("emb_179"):
	embedding_variable = tf.Variable(tf.truncated_normal([input_size, embedding_size], stddev=0.05), name='emb' + str(field_id))
	embedding = tf.nn.embedding_lookup_sparse(embedding_variable, sparse_ids, sparse_vals, "mod", combiner="sum")
...
```

c++ prediction demo: It load the graph and checkpoint successfully, but give an error when `session.Run()` in node `emb_179/embedding_lookup_sparse/strided_slice`. The inputs shows here.
```
auto id_indice_tensor =
test::AsTensor<int64>(indice, {static_cast<int64>(indice.size()/2), 2});
inputs.push_back(std::pair<std::string, Tensor>("input/sparse_field/index/Placeholder", id_indice_tensor));
auto id_list_tensor = test::AsTensor<int64>(fid_list);
inputs.push_back(std::pair<std::string, Tensor>("input/sparse_field/id/Placeholder", id_list_tensor));
auto val_list_tensor = test::AsTensor<float>(fval_list);
inputs.push_back(std::pair<std::string, Tensor>("input/sparse_field/value/Placeholder", val_list_tensor));

std::vector<tensorflow::Tensor> outputs;
Status status = session->Run(inputs, {"predict/add"}, {}, &outputs);
```

I saw a attr of  `emb_179/embedding_lookup_sparse/strided_slice` is
```
attr {
    key: "Index"
    value {
      type: DT_INT32
    }
```
But in c++, I set `auto id_indice_tensor =
test::AsTensor<int64>(...)`. Is this the reason?

**Comment by andydavis1** [comment]
Yes, it looks like there is no kernel registered for this (perhaps there was issue int64 on GPU). But registering an int64 strided slice for CPU shouldn't be an issue. Marking as contributions welcome.

**Comment by formath** [comment]
@andydavis1 Because all `op` are implemented in c++ and python is just a wrapper. So, if python works right for `StridedSlice`, should it also ok in c++?

**Comment by facaiy** [comment]
@formath could you provide environment infomation? Say, tensorflow version etc.

```python
import tensorflow as tf
a = tf.constant([[[1, 1, 1], [2, 2, 2]],
                         [[3, 3, 3], [4, 4, 4]],
                         [[5, 5, 5], [6, 6, 6]]], dtype=tf.int64)

b = tf.strided_slice(a, [1, 0, 0], [2, 1, 3], [1, 1, 1])

with tf.Session() as sess:
    print(sess.run(b))        # [[[3 3 3]]]
```

I test the script above on tf 1.3, and it works well.

**Comment by facaiy** [comment]
It seems that `StridedSlice` has registered all types for cpu, see:

https://github.com/tensorflow/tensorflow/blob/513f7df42e4eadfcd241a3be695af6fd426b734e/tensorflow/core/kernels/strided_slice_op.cc#L388

**Comment by formath** [comment]
@facaiy commit 3537e663230ba2d694f6daebc2288f180c6db4ea
Yes. In python, it works right. Error occur in c++ prediction.

I use in this way:
* offline transform libfm data into tfrecord
* when training, read tfrecord and parse it into `SpsrseTensor` as the inputs of `embedding_lookup_sparse`.  The type of `SparseTensor` are int64. After training done, save the `graph.pb` and checkpoint.
* Because `graph.pb` use `tf.train.string_input_producer` as the first op. If load this graph, I can't feed `Tensor` as inputs in c++ api if using `session.Run(vector<pair<string,Tensor>> inputs, vector<Tensor> outputs ...)`. So I write another graph structure in python which is similar to the graph in training except the part of reading and parsing tfrecord replaced by three `Tensor` placeholder for contructing a `SparseTensor`. Then, I freeze this new graph with the checkpoint saved before and get a new `graph.pb` which contains all the parameter for prediction.
* Using c++ api, I load the new `graph.pb` and construct `Tensor` of type int64 for placeholder as inputs. Then, run `session.Run(vector<pair<string,Tensor>> inputs, vector<Tensor> outputs ...)`. Code is compiled ok bur run error.

Any suggestions?

**Comment by facaiy** [comment]
@formath I see, the exception is raised when predicting. If I understand correctly, `TF_CALL_ALL_TYPES` will register all numerical types, including `TF_CALL_int64`, so I believe it is correct here. Perhaps there exists some limitation for prediction, say, int64 may be not supported now, I don't know.

**Comment by formath** [comment]
Because I build source code using `tensorflow/contrib/makefile/build_all_ios.sh` on macOS, it maybe define a macro `IS_MOBILE_PLATFORM` as true. In this circumstance, it don't support int64. Please have a look. Thanks. @petewarden

**Comment by formath** [comment]
fixed

**Comment by facaiy** [comment]
Wonderful. Just a little curious, could you explain how to fix it?

**Comment by formath** [comment]
`build_all_ios.sh` is for mobile platform which has no support for int64. osx should use `build_all_linux.sh`.

**Comment by azilaazman** [comment]
@formath im getting the same error running the code from Android Studio. im not sure how to use build_all_linux.sh into my project in android studio. can u help me with this? 

> `build_all_ios.sh` is for mobile platform which has no support for int64. osx should use `build_all_linux.sh`.
