### ISSUE TITLE
Feature request: Prevent predict_scores() in tf.contrib.learn.estimators from reloading graph variables from checkpoint file everytime

### ISSUE THREAD

**Issue by rutadesai** [tensorflow/tensorflow#13788]
Hi there,

I am using tf.contrib.learn.DNNLinearCombinedRegressor with wide and deep feature columns in Tesnorflow 1.3. I use an input_fn to parse pandas dataframes to this regressor for training. I have both real and categorical features, and so my deep feature columns are made of sparse columns with embedding as well as real valued columns. After training, I want to use the trained model for prediction in another application. I can call estimator.predict_scores() function to do this, but it seems very slow. Mainly because, it seems to be reloading the graph variables from last checkpoint file created during training everytime it is called. Can we prevent this for faster predictions, so that it reloads the variables only the first time it is called ? My application is simple, and I would like to not use Tensorflow serving.

Thanks.

**Comment by facaiy** [comment]
Do you mean that you invoke the `predict_scores()` for multiple times? Yes, `predict_scores` always constructs graph every time. Hence, you can (1) collect all data and feed them all at once, or (2) use tf-serving.

**Comment by rutadesai** [comment]
@facaiy  Thanks for your reply. Yes, I call predict_scores() multiple times. I have an application where-in new samples (feature set) are generated one at a time, and I need to show their scores. So, I send each sample as it is generated to predict_scores() to get the predicted score, requiring multiple calls to predict_scores().  Tensorflow serving seems like an overkill for my simple local desktop application. So, I was trying to avoid it.

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by martinwicke** [comment]
This is a known issue. We've decided to keep Estimator free of state -- please use contrib/predictor to get that behavior.

For most cases, you can pass a generator as input. As long as the generator yields new input, the model is kept in memory.
