### ISSUE TITLE
Feature Request: C++ gradient for LRN (Local Response Normalization)

### ISSUE THREAD

**Issue by gdeer81** [tensorflow/tensorflow#13789]
Implement the gradient for LRN in c++ so that it is available for TF_AddGradients

This is the python code that I think would need to be ported:
https://github.com/tensorflow/tensorflow/blob/48be6a56d5c49d019ca049f8c48b2df597594343/tensorflow/python/ops/nn_grad.py#L516

I'm using this issue to call dibs on this gradient port per @bpiel's suggestion
I was also advised to mention @suharshs

**Comment by drpngx** [comment]
Thanks @gdeer81! feel free to also link to other discussions for context if they are online.

**Comment by gdeer81** [comment]
I think I am looking in the wrong place for the implementation for this because the code I mentioned above is just collecting some attributes and then calling out to `gen_nn_ops._lrn_grad` : https://github.com/tensorflow/tensorflow/blob/48be6a56d5c49d019ca049f8c48b2df597594343/tensorflow/python/ops/nn_grad.py#L522

this is allegedly imported from gen_nn_ops: `from tensorflow.python.ops import gen_nn_ops`

But I can't seem to find this anywhere.  

Can someone point me to the right place?

**Comment by bpiel** [comment]
@gdeer81 This is an example where the grad logic is already implemented as an op

**Comment by suharshs** [comment]
To add to @bpiel 's comment, see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/gradients/nn_grad.cc#L65

for an example of another op (Relu) which just calls its corresponding ReluGrad op as its gradients function. You can likely do something similar for LRN.

**Comment by gdeer81** [comment]
Awesome, thanks for the quick feedback. So I'm just going to name this LRNHelper and try to follow the conventions in both of those examples

**Comment by gdeer81** [comment]
@suharshs since this is my first one, would it be too much to ask to get someone to write a test for me?  I'd feel more confident in my implementation if I could make a test someone else wrote pass

**Comment by bpiel** [comment]
@gdeer81 I'll do it.

**Comment by bpiel** [comment]
For the record, here's @gdeer81's PR for this issue:
https://github.com/tensorflow/tensorflow/pull/13987
