### ISSUE TITLE
TypeError in freeze_graph tool while trying to freeze a graph in Tensorflow 1.3

### ISSUE THREAD

**Issue by rutadesai** [tensorflow/tensorflow#13785]
I train a tf.contrib.learn estimator (specifically, DNNLinearCombineRegressor) in Python and saved the model’s parameters and graph by specifying model_dir when defining the estimator. My estimator uses embedding and real valued feature columns, and a custom input_fn to parse the data. After training is done, I try to freeze the graph using the CLI as mentioned in this [post](https://stackoverflow.com/questions/46223252/error-while-freezing-the-model-freeze-graph), and get this error --` TypeError: names_to_saveables must be a dict mapping string names to Tensors/Variables. Not a variable: Tensor("dnn/hiddenlayer_0/biases:0", shape=(10,), dtype=float32)` in saver.py in the function _ValidateAndSliceInputs.  Is this because I am using an input_fn with pandas dataframe, or is it because of the tf.feature_columns that I am using? 

I want to freeze the graph so that predict_scores() doesnt reload the graph variables from checkpoint file everytime for prediction. I am using Tensorflow 1.3 with Anaconda Python 3.5 on Windows 10. 

Thanks in advance.

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by rutadesai** [comment]
I am not sure, if the freeze_graph works with input_fn, and estimators. So, it could be a bug. I have posted on StackOverflow before posting here. I also found other people facing similar problems on StackOverflow without any solution.

Thanks.

**Comment by satendrapratap** [comment]
Try following command to freeze the graph. We are able to create .pb file for text_classification.py (uses estimator and input function) example in tensorflow using the same command:

python /home/ck/venvs/enet/lib/python2.7/site-packages/tensorflow/python/tools/freeze_graph.py --input_graph ./log/graph.pbtxt --input_checkpoint ./log/model.ckpt-0 --output_graph ./log/frozen_model.pb --output_node_names=ENet/logits_to_softmax

**Comment by xia-sun** [comment]
I'm having exact same problem as @rutadesai "TypeError: names_to_saveables must be a dict mapping string names to Tensors/Variables. Not a variable: Tensor("dnn/hiddenlayer_0/bias:0", shape=(2,), dtype=float32)". @rutadesai Have you resolved your problem? Thanks!

**Comment by dkhmelenko** [comment]
@drpngx Thanks for your suggestion. However, on [StackOverflow ](https://stackoverflow.com/search?q=names_to_saveables+must+be+a+dict+) there are a lot of open issues without answers. 

I also have an issue, which @rutadesai and @xia-sun have. Would be nice to have any suggestions how can it be solved.

**Comment by dkhmelenko** [comment]
@rutadesai did you solve the issue? Was it because of pandas input function? or because of feature columns?

I'm using `input_fn = tf.estimator.inputs.pandas_input_fn(x=x_train, y=y_train, batch_size=100, num_epochs=None, shuffle=True)` as an input function for `LinearClassifier.train()`.

All my feature columns have type `tf.feature_column.categorical_column_with_vocabulary_list`

**Comment by spivotron** [comment]
+1

**Comment by vinay453** [comment]
Getting same issue. Stackoverflow does not have answer to it as of today.

**Comment by rutadesai** [comment]
@dkhmelenko, @xia-sun  sorry for late reply! I couldn't solve this issue :(

**Comment by charlescc9** [comment]
In the same boat using estimators...

**Comment by klaas3** [comment]
same

**Comment by drpngx** [comment]
Do we still have the same problem in the latest version?

**Comment by dkhmelenko** [comment]
@drpngx yes, the issue still exists in Tensorflow 1.8.0.

I created a separate ticket for it with the detailed description (https://github.com/tensorflow/tensorflow/issues/18523), but it was not processed so far.

**Comment by drpngx** [comment]
Thank you!

**Comment by dkhmelenko** [comment]
@drpngx do you know if there is a plan to fix this issue?

**Comment by drpngx** [comment]
In general, we want to fix all issues, once we find out what they are. Of course, a fix is always welcome if you get to it before we do.

**Comment by OzzieFZI** [comment]
same issue using v1.9

**Comment by drpngx** [comment]
@OzzieFZI please have further comments on #18523.
