### ISSUE TITLE
Feature Request: use S3 for checkpoint loading/saving

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#13796]
EFS is not available in most AWS regions. For distributed TensorFlow in those regions one would have to rely on S3 to save/restore checkpoints

**Comment by mrry** [comment]
Perhaps the code in here is relevant?

https://github.com/tensorflow/tensorflow/tree/51e5b692a5f8f6942cb43291ba9faab39e4b6104/tensorflow/contrib/s3

**Comment by yongtang** [comment]
@yaroslavvb The S3 support was added in #11089. I think it is supported in nightly build by default. Please let me know if there are any issues.

**Comment by yaroslavvb** [comment]
@yongtang thanks, that code is definitely relevant. Checkpoint support would need Python wrappers and perhaps some extra features to hide the fact that S3 is not a real filesystem

**Comment by yongtang** [comment]
Thanks @yaroslavvb. I am also working in this area though haven't touched checkpoint yet. Please keep me posted and let me know if I could be of any help.

**Comment by hackintoshrao** [comment]
Hello @yaroslavvb . I was one of the early engineers of Minio, we are keen on making this integration. The SageMaker-Python Tensorflow wrapper currently provides this support. If you could share your thoughts on the interface it would help us to get started.

**Comment by kgramm9026** [comment]
Hi Guys, Can anyone please let me know if I can use tf.train.latest_checkpoint or tf.train.load_checkpoint with an S3 url to load the model checkpoint? Whenever I use either of these to load a checkpoint file I get InvalidArgumentError: S3 path doesn't contain an object name: s3://url/

**Comment by seahrh** [comment]
@kgramm9026 
You can't load the checkpoint files directly from S3. Use the `boto` library to download the files from S3 to local storage on your target machine (in my case, it was AWS Lambda). Then I restore the model from the files (following example uses an old version of the tf api, there should be a better way to do it in newer versions)

```
ckpt_dir = os.path.join( ... )
ckpt_state = tf.train.get_checkpoint_state(ckpt_dir, latest_filename)
saver.restore(session, ckpt_state.model_checkpoint_path)

```

**Comment by yongtang** [comment]
@kgramm9026 It should be possible to use `s3://` directly though you have to use s3  `s3://bucket/object` format.

**Comment by RoelantStegmann** [comment]
For me this still gives errors however. 

`OSError: Unable to create file (unable to open file: name = 's3://bucket/key/20200120_102319968195_some_name/weights.01-0.4383.hdf5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)`

**Comment by byronyi** [comment]
> For me saving checkpoints still gives errors however.
> 
> `OSError: Unable to create file (unable to open file: name = 's3://bucket/key/20200120_102319968195_some_name/weights.01-0.4383.hdf5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)`

Use tf format instead of hdf5.

**Comment by zwarshavsky** [comment]
any updates here?

**Comment by Venkat6871** [comment]
Hi **@yaroslavvb** ,
- Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

- The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow version with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

- Please follow the release notes to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!
