### ISSUE TITLE
Tensorflow serving API does not support python3.5 

### ISSUE THREAD

**Issue by jieliuu** [tensorflow/tensorflow#13805]
Tensorflow serving API only supports python2.7.   It is not work for python3 .5

**Comment by drpngx** [comment]
/CC @sukritiramesh

Did you try with python3.5? What happens there?

**Comment by jieliuu** [comment]
@drpngx Yes, I try to install it in pip with python3.5 and fails. The command, **pip install tensorflow_serving_api** , does not work, but python2.7 can run this command and find this package.    There is no tensorflow serving api package for python3.5.

**Comment by drpngx** [comment]
How does it fail?

**Comment by Carmezim** [comment]
It may be silly but is perhaps your `pip` linked to Python 2.7 meaning, have you tried `pip3`?

**Comment by Carmezim** [comment]
Apparently TensorFlow Serving only supports Python 2.
https://github.com/tensorflow/serving/issues/581

**Comment by jieliuu** [comment]
@drpngx The error information 
  **Could not find a version that satisfies the requirement tensorflow-serving-api (from versions: )
No matching distribution found for tensorflow-serving-api**

**Comment by jieliuu** [comment]
@Carmezim  Thank you for your answer.

**Comment by sascha-monville** [comment]
Forced to use anaconda3 while working on a cluster with no sudo permission, i figured out that `pip install tensorflow-serving-api` only works for python 2.7.12 or higher python 2.7.9 fails.
@jieliuu you might check your version + good luck

**Comment by wt-huang** [comment]
Closing as this is resolved
