### ISSUE TITLE
Feature Request: Scripts for build tensorflow with FORTIFY

### ISSUE THREAD

**Issue by snnn** [tensorflow/tensorflow#13801]
FORTIFY is an important security feature that can help us discover hidden bugs. 
This is success story from Android:
https://android-developers.googleblog.com/2017/04/fortify-in-android.html

Please do the same thing for tensorflow, provide a checked build(with FORTIFY turned on) publicly.

**Comment by drpngx** [comment]
You mean build with `-DFORTIFY=1`? I think we do that by default.

/CC @gunan

**Comment by snnn** [comment]
You are right.
# hardening-check tools/proto_text/gen_proto_text_functions.runfiles/org_tensorflow/tensorflow/tools/proto_text/gen_proto_text_functions
tools/proto_text/gen_proto_text_functions.runfiles/org_tensorflow/tensorflow/tools/proto_text/gen_proto_text_functions:
 Position Independent Executable: no, normal executable!
 Stack protected: yes
 Fortify Source functions: yes (some protected functions found)
 Read-only relocations: yes
 Immediate binding: yes

Sorry for bothering you.

**Comment by drpngx** [comment]
Thanks for checking!
