### ISSUE TITLE
tensorflow-android library 1.4.0-rc0 seems to contain tensorflow 1.3.0-rc2

### ISSUE THREAD

**Issue by andreas-eberle** [tensorflow/tensorflow#13807]
For my work I require the new String Tensor feature introduced for the Java API in tensorflow 1.4. I tested my network with my Java code on my Desktop which works fine (using org.tensorflow:tensorflow:1.4.0-rc0). 

However, when I use the same code in an Android project (using org.tensorflow:tensorflow-android:1.4.0-rc0), I get the following error leading me to the guess that the wrong version was packaged:

```
10-18 16:33:33.987 21288-22070/test.android.fisheye W/System.err: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: non-scalar DataType.STRING tensors are not supported yet (version 1.3.0-rc2). Please file a feature request at https://github.com/tensorflow/tensorflow/issues/new
10-18 16:33:33.988 21288-22070/test.android.fisheye W/System.err:     at java.util.concurrent.FutureTask.report(FutureTask.java:94)
10-18 16:33:33.988 21288-22070/test.android.fisheye W/System.err:     at java.util.concurrent.FutureTask.get(FutureTask.java:164)
10-18 16:33:33.988 21288-22070/test.android.fisheye W/System.err:     at test.neuronalnetwork.service.TaskWorkerLoop$Loop.run(TaskWorkerLoop.java:71)
10-18 16:33:33.988 21288-22070/test.android.fisheye W/System.err:     at java.lang.Thread.run(Thread.java:762)
```

I also downloaded the org.tensorflow:tensorflow-android:1.4.0-rc0 from maven central and had a look at the class files. They look like the class files from the 1.3.0 version. 

Furthermore, when looking at the Tensor and Tensorflow classes, you can see that the version displayed in the error message above, is actually read from the native library. 

Do you agree, or did I miss something? If you do agree, can you please upload a real 1.4.0-rc0 to maven central?

**Comment by drpngx** [comment]
@av8ramit did we forget to change a string?

**Comment by av8ramit** [comment]
@case540 did we upload the Java maven packages for rc0?

**Comment by case540** [comment]
Yes, the Maven packages were uploaded for rc0 so that is not the issue at least.

**Comment by andreas-eberle** [comment]
As I tried to point out, I think you compiled an older version and uploaded that. Because it does not seem that only the string is wrong. Instead, the whole feature "string tensors" is missing in that version (but should be in there).

**Comment by andreas-eberle** [comment]
I just saw you released rc1 already. With rc1 my issue is fixed. Thanks guys and keep up the good work!
