### ISSUE TITLE
GRU cell implementation different from Reference paper "Cho 14"

### ISSUE THREAD

**Issue by Sanghoon94** [tensorflow/tensorflow#13825]
Hello, 

I've been looking through GRUCell implementation on Tensorflow at "tensorflow/tensorflow/python/ops/rnn_cell_impl.py", and got a bit confused.

The output of GRUCell is implemented as
`new_h = u * state + (1 - u) * c`

However, from the reference paper "Cho 14" at https://arxiv.org/pdf/1412.3555.pdf
I think it should be like
`new_h = (1 -  u) * state + u * c`

I am not sure if this is a bug or an intended variation from the reference.

Thank you

**Comment by drpngx** [comment]
To be clear we are looking at Eq 5 in the paper and the code [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn_cell_impl.py#L351).

@ebrevdo what do you think?

**Comment by Sanghoon94** [comment]
Any comments on the issue?

**Comment by hksonngan** [comment]
the code is right as eq 7 in the origin paper https://arxiv.org/pdf/1406.1078.pdf

**Comment by hksonngan** [comment]
code is right as detail explain in 2.3 of https://arxiv.org/pdf/1406.1078.pdf

**Comment by Sanghoon94** [comment]
@hksonngan 
Thanks! 
Wonder why the equations are the different in the papers though.
