### ISSUE TITLE
GPU Question: dtype supports 

### ISSUE THREAD

**Issue by suwangcompling** [tensorflow/tensorflow#13824]
According to https://github.com/tensorflow/tensorflow/issues/9506, gpu currently only supports floats. In NLP tasks however there's no way around looking up the embedding matrix with int-typed indices. 

So I wonder if it on your shortlist to extend to int support? If not, how to get around the index-lookup issue? Thanks.

**Comment by andydavis1** [comment]
Please ask this first on StackOverflow to see if you get some response to using TF with embedding integer index lookups.
