### ISSUE TITLE
feature request: more efficient tf.eye

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#13823]
tf.eye(n) creates a constant of size n*4
A better implementation would use `Fill` instead of constant

This is similar to issue https://github.com/tensorflow/tensorflow/issues/13221#issuecomment-333893186 , where zeros is getting refactored to use Fill instead of constant

**Comment by drpngx** [comment]
Seems reasonable.

@reedwm @alextp @zffchen78 @cwhipkey Any takers?

**Comment by drpngx** [comment]
@tfboyd for performance.

**Comment by drpngx** [comment]
Obviously, @yaroslavvb we accept contributions as well :-)

**Comment by facaiy** [comment]
Hi, do you mean to replace `array_ops.zeros` by `fill`?

https://github.com/tensorflow/tensorflow/blob/408fd454d7d2a16269576ea12bcd516e25a6b0c5/tensorflow/python/ops/linalg_ops.py#L134

**Comment by yaroslavvb** [comment]
Actually I just realized someone already has a PR to fix this: https://github.com/tensorflow/tensorflow/pull/13666

To see problem with current solution try
```
import tensorflow as tf
import numpy as np

tf.reset_default_graph()
sess = tf.Session()
run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE,output_partition_graphs=True)
run_metadata = tf.RunMetadata()
sess.run(tf.eye(10).op, options=run_options,run_metadata=run_metadata)
print(run_metadata)
```

You see a large const node being allocated on the GPU which is a problem because this memory will not be released at the end of `sess.run`

**Comment by drpngx** [comment]
OK, closing then.
