### ISSUE TITLE
Custom Reader Op : Undeclared Inclusions

### ISSUE THREAD

**Issue by dnel38** [tensorflow/tensorflow#13820]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
Custom Code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
Linux Ubuntu 16.04 
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
1.4.0
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
0.6.1

- **CUDA/cuDNN version**:
Laptop CPU
- **GPU model and memory**:
Laptop CPU
- **Exact command to reproduce**:
 bazel build -c opt //tensorflow/core/user_ops:rest_api.so --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"

### Describe the problem
I am getting undeclared inclusions for files in the //tensorflow/core/framework directory. I am not sure why this is happening since the user_ops_op_lib in the //tensorflow/core/BUILD has ":framework" as its dependency. Is there a missing dependency that needs to be added? 

### Source code / logs

BUILD File In /tensorflow/core/user_ops
```
load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

cc_library(
        name = "rest_api_dependencies",
        srcs = glob(["rest_api.cc", "*.c", "*.cpp"]),
        hdrs = glob(["rest_api.h", "*.h", "*.hpp", "dict.c"]),
	linkopts = ["-pthread", "-lev", "-fexceptions"],
)

tf_custom_op_library(
        name = "rest_api.so",
        srcs = ["rest_api.cc"],
        deps = [":rest_api_dependencies"],
)
```

undeclared inclusion(s) in rule '//tensorflow/core/user_ops:rest_api_dependencies':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/user_ops/rest_api.cc':
  'bazel-out/local-opt/genfiles/tensorflow/core/framework/op_def.pb.h'
  'bazel-out/local-opt/genfiles/tensorflow/core/framework/attr_value.pb.h'
  'bazel-out/local-opt/genfiles/tensorflow/core/framework/tensor.pb.h'
  'bazel-out/local-opt/genfiles/tensorflow/core/framework/resource_handle.pb.h'
  'bazel-out/local-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.h'
  'bazel-out/local-opt/genfiles/tensorflow/core/framework/types.pb.h'
  'bazel-out/local-opt/genfiles/tensorflow/core/lib/core/error_codes.pb.h'
  'bazel-out/local-opt/genfiles/tensorflow/core/framework/step_stats.pb.h'
  'bazel-out/local-opt/genfiles/tensorflow/core/framework/allocation_description.pb.h'
  'bazel-out/local-opt/genfiles/tensorflow/core/framework/tensor_description.pb.h'

**Comment by allenlavoie** [comment]
user_ops_op_lib will only apply the :framework dep to sources it collects. If you define your own cc_library rule you'll need to add the required deps explicitly. You should be able to just add `deps = ["//tensorflow/core:framework"]`.

**Comment by dnel38** [comment]
@allenlavoie Okay, everything is working now. Thank you! 
For anyone who stumbles upon this, I had to do one more step to get my custom op to successfully build with bazel. The dependencies I needed were disallowed in tensorflow.bzl. I removed these disallowed dependencies and  everything worked after that.

**Comment by allenlavoie** [comment]
Ah. Yes, I should reconsider whether that check is at all necessary (I think no at this point, after the RTLD_GLOBAL removal). What does bypass that check is using framework_headers_lib.

Are you interested in removing the :framework check in a pull request? You can mention me and I'll review. Not 100% certain it's safe, but it should be.
