### ISSUE TITLE
Attempting to use uninitialized value RNN/GRUCell/Gates/Linear/Bias

### ISSUE THREAD

**Issue by shiyemin** [tensorflow/tensorflow#1383]
### Environment info
Operating System:
Rocks OS (Centos 6.5)

I installed from sources, and here is my version:
https://github.com/shiyemin/tensorflow/
Nothing changed but to make it compile successfully on our server.

### ERROR
I use https://github.com/ethereon/caffe-tensorflow to convert caffe model to tensorflow and the GoogLeNet is selected to construct our network.

I add  a LSTM layer to this code as follows:

    @layer
    def lstm(self, input, lstm_type, n_steps, initial_state, num_units, name):
        #  with tf.variable_scope(name) as scope:
        input_shape = input.get_shape()
        dim = 1
        for d in input_shape[1:].as_list():
            dim *= d
        input = tf.reshape(input, [input_shape[0].value, -1])

        # select LSTM type, Define a lstm cell with tensorflow
        if lstm_type == 'basic':
            lstm_cell = rnn_cell.BasicLSTMCell(num_units, input_size=dim)
        elif lstm_type == 'lstm':
            lstm_cell = rnn_cell.LSTMCell(num_units, input_size=dim)
        elif lstm_type == 'GRU':
            lstm_cell = rnn_cell.GRUCell(num_units, input_size=dim)
        else:
            raise ValueError("LSTM type %s error."%lstm_type)

        # Split data because rnn cell needs a list of inputs for the RNN inner loop
        input = tf.split(0, n_steps, input) # n_steps * (batch_size, n_hidden)

        # Get lstm cell output
        outputs, states = rnn.rnn(lstm_cell, input, initial_state=initial_state) # , scope=scope)
        outputs = tf.concat(0, outputs)
        return outputs #, states

When i add this LSTM layer to GoogLeNet, "Failed precondition: Attempting to use uninitialized value  RNN/GRUCell/Gates/Linear/Bias" occurs. But when i using the code from https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/3%20-%20Neural%20Networks/recurrent_network.py, everything works well.

Anyone knows what happened? I don't know how to debug this error.

**Comment by vrv** [comment]
Unless you think this is a bug in TensorFlow, this question is better suited to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow)
