### ISSUE TITLE
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

### ISSUE THREAD

**Issue by melody-rain** [tensorflow/tensorflow#1385]
Why executing 
"bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package"

deletes grpc.git and repulls it If I execute "bazel clean" ?

**Comment by vrv** [comment]
This is probably more a question for the bazel team, but bazel clean is supposed to clean up all state to try to provide hermeticity in builds.
