### ISSUE TITLE
Should we provide parameters for 'data_dir' or 'untar' to cifar10.load_data?

### ISSUE THREAD

**Issue by uZeroJ** [tensorflow/tensorflow#13876]
https://github.com/tensorflow/tensorflow/blob/d7409d32bba5ffa89141ec5427780f68a3b6942d/tensorflow/python/keras/_impl/keras/datasets/cifar10.py#L30

This is maybe really a trivial issue for such a brilliant framework,
but it would be great more friendly to add this flexibility to load data from somewhere that I already have it and unpacked. Or it will fixed me to dig into the source to find where and in which format should this data be stored.

Hope that make sense.

Thanks a lot for you time.

**Comment by drpngx** [comment]
Sounds fine by me. This will need to go through an API review.

CC @martinwicke

**Comment by DjangoPeng** [comment]
@drpngx @uZeroJ I think it's reasonable. I'd like to make a PR to add the flexibility.

**Comment by uZeroJ** [comment]
@DjangoPeng Thanks!

**Comment by DjangoPeng** [comment]
I think @fchollet  has given a reasonable explaination in the PR. I agree on his point and suggest to close the issue, cause there is already a function for using local data files.  

@uZeroJ @drpngx  What do you think?

**Comment by uZeroJ** [comment]
@DjangoPeng , Got it. Anyway thanks again.
