### ISSUE TITLE
For poor guys without access to boringssl located in google's server

### ISSUE THREAD

**Issue by melody-rain** [tensorflow/tensorflow#1387]
When I cloned the latest tensorflow and compile it with bazel, bazel clones grpc.git from github.
However grpc.git need clone submodule boringssl which is located in google's server. Since I have no stable vpn to have access to boringssl, I forked grpc.git to my github and changed WORKSPACE of tensorflow (located in tensorflow's root path) as follows:
 git_repository(
     name = "grpc",
-    commit = "73979f4",
+    commit = "403cd6c",
     init_submodules = True,
-    remote = "https://github.com/grpc/grpc.git",
+    remote = "https://github.com/melody-rain/grpc.git",
 )

and also I changed the .gitmodule of grpc.git so that boringssl is downloaded from  

[submodule "third_party/boringssl"]
	path = third_party/boringssl
	url = https://github.com/doubler/boringssl.git

Thanks @doubler for his help. 

For those have access to google's service, just ignore this issue,

**Comment by yangyanli** [comment]
I was about to do the same thing, and found this issue. Many thanks!

Life is tough for Chinese mainland people...

**Comment by melody-rain** [comment]
@yangyanli  not easy to be a programmer...

**Comment by MisayaZ** [comment]
@	melody-rain I also meet the problem. I don't see git_repository name = "grpc" in my workspace. What I see is new_git_repository.

**Comment by melody-rain** [comment]
@MisayaZ  have a look at https://github.com/grpc/grpc/issues/5853. The code might be changed.

**Comment by mrry** [comment]
I think this is fixed thanks to the underlying fixes in gRPC.
