### ISSUE TITLE
ValueError raised when using AdamOptimizer, but not for GradientDescentOptimizer

### ISSUE THREAD

**Issue by rohan-varma** [tensorflow/tensorflow#13887]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sierra 10.12.1
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.2.0-rc2-21-g12f033d 1.2.0
- **Python version**: 3.5.0

### Source code / logs

Taken from this issue: https://github.com/tensorflow/tensorflow/issues/6220#issuecomment-314688444, the below code reproduces the error.

```
import tensorflow as tf
import numpy as np
class SimpleModel:
    def __init__(self):
        self.loss = self.calc_loss()
        self.train = self.train_model(self.loss)
    def calc_loss(self):
        W = tf.get_variable("w", [1])
        b = tf.Variable(tf.zeros([1]))
        y = W * x_data + b
        return tf.reduce_mean(tf.square(y - y_data))
    def train_model(self, loss):
        return tf.train.AdamOptimizer(0.5).minimize(loss)
        #return tf.train.GradientDescentOptimizer(0.5)
x_data = np.random.rand(100).astype(np.float32)
y_data = x_data * 0.1 + 0.3
s1 = SimpleModel()
tf.get_variable_scope().reuse_variables()
s2 = SimpleModel()
```

Running this gives the error `ValueError: Variable w/Adam_2/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?`, but when `train_model` is changed to return the `GradientDescentOptimizer`, the code compiles correctly.

I've tried following all the advice in the issue that relates to this (https://github.com/tensorflow/tensorflow/issues/6220), but haven't had any luck.

**Comment by kazemSafari** [comment]
I am having the same issue. I use tensorflow 1.3 and my operating system is ubuntu 16.4.

**Comment by drpngx** [comment]
Did you look at this?
https://stackoverflow.com/questions/44440900/cant-access-tensorflow-adam-optimizer-namespace

**Comment by kazemSafari** [comment]
I looked at it. It definitely explains exactly what  the problem is but does not give any solution at all.
I do not know how to create that subscope that he is talking about without tensorflow raising an error.

**Comment by kazemSafari** [comment]
Hi again!
Your comment helped a lot. Also the follow up here:
https://github.com/adeshpande3/Generative-Adversarial-Networks/issues/1
solves the problem.
Thank you.

**Comment by drpngx** [comment]
Woohoo! Thank you for following up and the link!

**Comment by rohan-varma** [comment]
So from what I understand, this issue seems to come from the fact that we can't actually set reuse = False for a variable scope? I was able to fix the problem by introducing a sub-scope like the above comments mentioned, but overall I'm still a bit confused about the underlying issue. The traceback given here: 
`ValueError: Variable w/Adam_2/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?`

Seems to imply that we can set the reuse flag to false/none, but the documentation [here](https://www.tensorflow.org/versions/r0.12/how_tos/variable_scope/#variable_scope_example) says "note that you cannot set the reuse flag to false". I may be interpreting this incorrectly, but could anything be done about maybe a better log message in this case? Thanks!

**Comment by michaelisard** [comment]
I believe the documentation is saying you can only change the reuse flag from false to true inside a scope (by calling `scope.reuse_variables()`); but you can't change the reuse flag from true to false inside a scope. The log message I think means 'did you mean be in a non-reusing VarScope', and I agree that it's not super clear.

@martinwicke do you think it's worth changing the message?

**Comment by martinwicke** [comment]
@lukaszkaiser @ebrevdo WDYT? 

I'd favor changing the message, but want to be sure I'm interpreting the situation correctly.

**Comment by lukaszkaiser** [comment]
It should certainly say "reuse=False" not "reuse=None" (that's been changed a long time ago). Nowadays (starting with TF 1.4) you can actually set "reuse=tf.AUTO_REUSE" and the error will go away in all circumstances (changing True/False can be tricky). Maybe it's worth mentioning that in the message and suggesting AUTO_REUSE?

**Comment by lukaszkaiser** [comment]
(As for setting reuse=False, you can do it but it'll be overridden if your parent scope has it set to True.)

**Comment by rohan-varma** [comment]
@lukaszkaiser @martinwicke I'd be happy to send in a PR to change the `reuse=None` message if we've decided to do that as my first contribution to Tensorflow!

**Comment by martinwicke** [comment]
Please do, thanks!

**Comment by rohan-varma** [comment]
@martinwicke https://github.com/tensorflow/tensorflow/pull/14015 is merged, so I'm closing this for now. Thanks for your help!
