### ISSUE TITLE
InvalidArgumentError: No OpKernel was registered to support Op 'Resampler' with these attrs. 

### ISSUE THREAD

**Issue by Sharath-girish** [tensorflow/tensorflow#13888]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: Python 3.6.2 
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: CUDA 8/ CUDNN 6
- **GPU model and memory**: GeForce 940MX
- **Exact command to reproduce**: tf.contrib.resampler.resampler(inp,warp)

### Describe the problem
No registered kernels for the resampler operation. The code is as follows
`import tensorflow as tf`
`inp = tf.ones([1,4,4,3],dtype=tf.float32)`
`warp = tf.zeros([1,4,4,2],dtype=tf.float32)`
`out = tf.contrib.resampler.resampler(inp,warp)`
`print(out)`
`sess = tf.Session()`
`print(sess.run(out))`

### Source code / logs
I get the following output and error, traceback

Tensor("resampler_1/Resampler:0", shape=(1, 4, 4, 3), dtype=float32)

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1326     try:
-> 1327       return fn(*args)
   1328     except errors.OpError as e:

F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1296       # Ensure any changes to the graph are reflected in the runtime.
-> 1297       self._extend_graph()
   1298       with errors.raise_exception_on_not_ok_status() as status:

F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py in _extend_graph(self)
   1357           tf_session.TF_ExtendGraph(
-> 1358               self._session, graph_def.SerializeToString(), status)
   1359         self._opened = True

F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\contextlib.py in __exit__(self, type, value, traceback)
     87             try:
---> 88                 next(self.gen)
     89             except StopIteration:

F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\errors_impl.py in raise_exception_on_not_ok_status()
    465           compat.as_text(pywrap_tensorflow.TF_Message(status)),
--> 466           pywrap_tensorflow.TF_GetCode(status))
    467   finally:

InvalidArgumentError: No OpKernel was registered to support Op 'Resampler' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
 &lt;no registered kernels&gt;

	 [[Node: resampler_1/Resampler = Resampler[T=DT_FLOAT](ones_2, zeros_2)]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-3-0ff9594126bf> in <module>()
      5 print(out)
      6 sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
----> 7 print(sess.run(out))

F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    893     try:
    894       result = self._run(None, fetches, feed_dict, options_ptr,
--> 895                          run_metadata_ptr)
    896       if run_metadata:
    897         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1122     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1123       results = self._do_run(handle, final_targets, final_fetches,
-> 1124                              feed_dict_tensor, options, run_metadata)
   1125     else:
   1126       results = []

F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1319     if handle is None:
   1320       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1321                            options, run_metadata)
   1322     else:
   1323       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1338         except KeyError:
   1339           pass
-> 1340       raise type(e)(node_def, op, message)
   1341 
   1342   def _extend_graph(self):

InvalidArgumentError: No OpKernel was registered to support Op 'Resampler' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
 &lt;no registered kernels&gt;

	 [[Node: resampler_1/Resampler = Resampler[T=DT_FLOAT](ones_2, zeros_2)]]

Caused by op 'resampler_1/Resampler', defined at:
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-0ff9594126bf>", line 4, in <module>
    out = tf.contrib.resampler.resampler(inp,warp)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\resampler\python\ops\resampler_ops.py", line 59, in resampler
    return gen_resampler_ops.resampler(data_tensor, warp_tensor)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\resampler\ops\gen_resampler_ops.py", line 28, in resampler
    result = _op_def_lib.apply_op("Resampler", data=data, warp=warp, name=name)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "F:\Sharath\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Resampler' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  &lt;no registered kernels&gt;

	 [[Node: resampler_1/Resampler = Resampler[T=DT_FLOAT](ones_2, zeros_2)]]

**Comment by liyzjj** [comment]
I cannot reproduce this error. Maybe this is related to the specific platform and setup of the user.

**Comment by skye** [comment]
@Sharath-girish do you see this error if you disable GPU? (You can disable your GPU by setting the env variable CUDA_VISIBLE_DEVICES='' and rerunning your script)

**Comment by Sharath-girish** [comment]
I disabled gpu by setting the variable to -1
`os.environ["CUDA_VISIBLE_DEVICES"]='-1'`

Alternatively, I also tried setting tf device to '/cpu:0'
I still get the error as
InvalidArgumentError: No OpKernel was registered to support Op 'Resampler' with these attrs.  Registered devices: [CPU], Registered kernels:
  &lt;no registered kernels&gt;

	 [[Node: resampler/Resampler = Resampler[T=DT_FLOAT](ones, zeros)]]

**Comment by skye** [comment]
Hm, I'm not able to repro either. I suspect the problem has something to do with the Windows binary... @gunan do you have a way to try to repro this? @Sharath-girish you could try building from source: https://github.com/tensorflow/tensorflow/tree/r0.12/tensorflow/contrib/cmake

**Comment by gunan** [comment]
It looks like resampler op kernels are excluded from the windows cmake build:
https://github.com/tensorflow/tensorflow/commit/a80c8b583fa3d619b358a91aefd05069227b8967
https://github.com/tensorflow/tensorflow/blame/r1.4/tensorflow/contrib/cmake/tf_core_kernels.cmake#L160

Also, resampler ops cuda kernels are not included in GPU kernels that need to be built:
https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/contrib/cmake/tf_core_kernels.cmake#L181

You can try editing the lines I linked above and rebuilding from sources, but the build may fail. It is contrib, so my knowledge about why the build failed in June and this was excluded ends here.

**Comment by cuevas1208** [comment]
I got a similar error when I build Tesorflow using GPU (using Cmake). I can successfully load and run the graph previously saved from my python model in Tensorflow 1.4 using CPU c++ with no problem; but when I tried to load the same graph using Tensorflow 1.4 using GPU c++ and I get the following error:
`- status {state_=unique_ptr {code=INVALID_ARGUMENT (3) msg="No OpKernel was registered to support Op 'OneHot' with these attrs. Registered devices: [CPU,GPU], Registered kernels:\n <no registered kernels>\n\n\t [[Node: one_hot = OneHot[T=DT_FLOAT, TI=DT_INT32, _... } } tensorflow::Status`

Any advice on this? 

My system:
OS Platform and Distribution = Windows 10 Pro 64-bit (build 15063)
TensorFlow installed from = https://github.com/tensorflow/tensorflow/archive/v1.4.0.zip
TensorFlow version = 1.4.0
Bazel version = N/A I am using cmake cmake-3.9.4-win64-x64
CUDA/cuDNN version = Cuda 8.0/Cudnn 6
GPU model and memory = NVIDIA Quadro M4000, VRAM 8152MB
Exact command to reproduce = N/A running it in visual studio 2015

**Comment by antoinecomp** [comment]
I got a similar error using 

My system:
OS Platform and Distribution = Linux 16.04 64-bit
TensorFlow installed from = ?
TensorFlow version = 1.6.0
Bazel version = ?
CUDA/cuDNN version = ??
GPU model and memory = ?
Exact command to reproduce = can be found here https://github.com/antoinecomp/Davidshah

**Comment by bharadwajdhornala** [comment]
Hi @Sharath-girish  @liyzjj  @skye  @gunan @cuevas1208  
Tensorflow=1.10.0
OS platform =Windows 10
CUDA/cuDNN version=9.0

I get this error while testing DISN code.
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Resampler' with these attrs. Registered devices: [CPU], Registered kernels:

[[Node: resampler/Resampler = Resampler[T=DT_FLOAT](ResizeBilinear_1, Minimum)]]
Please guide. Thanks!

**Comment by gunan** [comment]
Looks like this is about a very very old version of TF, which is not supported any more.
Please use 1.15 or 2.x
