### ISSUE TITLE
Build Error - Unable to clone jsoncpp repo, all others seem to be working

### ISSUE THREAD

**Issue by brycecf** [tensorflow/tensorflow#13896]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**:  Source from master branch
- **TensorFlow version (use command below)**:
- **Python version**: 3.6.2
- **Bazel version (if compiling from source)**:  cmake 3.9.4
- **CUDA/cuDNN version**: CUDA 9.0/cuDNN 7
- **GPU model and memory**:  GTX 1080
- **Exact command to reproduce**:  `MSBuild /filelogger /m:4 /p:Configuration=Release tf_python_build_pip_package.vcxproj`

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
I have been trying to build the TensorFlow pip package.  For some reason, while I have verified that the build is able to clone the other git repos, the `jsoncpp` one seems to be killing my build.

### Source code / logs
`    42>CustomBuild:
         Creating directories for 'jsoncpp'`
`    42>CustomBuild:
         Performing download step (git clone) for 'jsoncpp'`
`    42>CustomBuild:
         fatal: could not create work tree dir 'jsoncpp': Permission denied`
`    42>CustomBuild:
         fatal: could not create work tree dir 'jsoncpp': Permission denied`
`    42>CustomBuild:
         fatal: could not create work tree dir 'jsoncpp': Permission denied`
`    42>CustomBuild:
         -- Had to git clone more than once:
                   3 times.`
`    42>CustomBuild:
         CMake Error at C:/Users/Bryce/Documents/Programming/os_clones/tensorflow/tensorflow/contrib/cmake/build/jsoncpp/tmp/jsoncpp-gitclone.cmake:66 (message):
           Failed to clone repository:
           'https://github.com/open-source-parsers/jsoncpp.git'`

And later on,

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\Bryce\Documents\Programming\os_clones\tensorflow\tensorflow\contrib\cmake\build\jsoncpp.vcxproj]`

[msbuild.log](https://github.com/tensorflow/tensorflow/files/1404600/msbuild.log)

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it seems like a problem with your environment. There is also a larger community that reads questions there. Thanks!
