### ISSUE TITLE
Op type not registered 'GatherTree' in binary running on..

### ISSUE THREAD

**Issue by barak-hurwitz** [tensorflow/tensorflow#13902]
Hi,

I'm trying to use the GTT (Graph Transform Tool) on NMT model (From the NMT sample project),
https://github.com/tensorflow/nmt

I get the following error :
bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph=/tmp/NMT_frozenGraphPB.pb --out_graph=Quant_NMT.pb --inputs='' --outputs='attention' --transforms='add_default_attributes quantize weights quantize_nodes'

"Op type not registered 'GatherTree' in binary running on .... Make sure the Op and Kernel are registered in the binary running in this process."

Any idea how to solve this issue?

Thx
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No code change , using GTT tool example
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
From Source
- **TensorFlow version (use command below)**:
Latest
- **Python version**: 
3.5 , 3.6 and 2.7
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
None
- **GPU model and memory**:
Tried in several systems and installations 
- **Exact command to reproduce**:
bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph=/tmp/NMT_frozenGraphPB.pb --out_graph=Quant_NMT.pb --inputs='' --outputs='attention' --transforms='add_default_attributes quantize weights quantize_nodes'

**Comment by allenlavoie** [comment]
Sounds like the same issue as https://github.com/tensorflow/tensorflow/issues/12927. One workaround would be to add "from tensorflow.contrib.seq2seq.python.ops import beam_search_ops" to the graph transform tool so it picks up the kernel.

Not closing this immediately because there may be different solutions. Even if we don't load contrib eagerly we may want to import some contrib kernels in the graph transform tool.

**Comment by barak-hurwitz** [comment]
Thanks for your reply , 
since i'm using the C++ in transform_graph
solved it using small change in the BUILD file of graph transform.
...
Line 216:        "//tensorflow/contrib/seq2seq:beam_search_ops_op_lib",
...

*It will help to add a short guide or flag in the GTT tools for using ops from contrib  (not part of the default builds)
