### ISSUE TITLE
Feature request: make `smart_cond` public API

### ISSUE THREAD

**Issue by netheril96** [tensorflow/tensorflow#13903]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.3.0-24-g658866597
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**: None

### Describe the problem

Currently `tf.cond` does not work if predicate is a Python boolean. As a result, people frequently have to write conditional statements twice, one with `if` statement, and one with `tf.cond` call. There is a `smart_cond` in `tensorflow/python/layers/utils.py`, but it is not in the public API or searchable in documentation. Petition to make it public or just integrate the smartness in `tf.cond` altogether. It is not a big change and will not impact backwards compatibility.

**Comment by drpngx** [comment]
Here's the code: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/utils.py#L180

/CC @martinwicke

**Comment by Nickheythatsme** [comment]
## Overview
Sentiment analysis has been something I've been interested in for a long time. From my first python script pulling reddit comments to this program now, I've found it compelling and challenging, while also having a low barrier of entry (the first iterations of this compared each word to known "Bad" or "Good" words). I like making all of my own components for this as well. I could easily use vectors or map for much of this, but I like understanding and specializing my own data structures. The project will be split up into two major components: vectorization and word_frequency analysis (name pending)

## Vectorization
Vectorization is the process of parsing multi-word text into a frequency graph, where each word is related to another word by a certain frequency. For example, 

> I never sleep, ‘cause sleep is the cousin of death
Beyond the walls of intelligence, life is defined
I think of crime when I'm in a New York state of mind

The first thing we'll do is remove the most common words. Which might look like this:
> never sleep 'cause sleep cousin death

Then might parse this into several word-windows. A word window is a word, surrounded by its context. The context might be the 2-5 nearest words to the target word. The word window for the first *sleep* might be:
>"never, 'cause, sleep, cousin"

 Now that we have the window, we add this context to the already recorded contexts for the word sleep. Practically this looks like adding (or incrementing) edges on the graph vertex for the word sleep.

I like imagining data flow for projects so I will overview the what's happening on one thread, to one file of text.

1. File stream is started
2. Stream is parsed for non-ascii characters, all uppercase characters are lowered
3. Words are split up. "General" windows are made (word-windows with no target word)
4. Words and context are added to variable graph. This looks like a balanced tree of word-vertexes. We make word-vertexes if they do not exist yet, then pass the word window to the word-vertexes. 
5. Word-vertexes keep their edges in a balanced tree as well. We find the connected edge (or make it if we need), and adjust the edges appropriately
6. Once finished with parsing the file, we go through the graph and sort by word frequency. We remove the most frequently and *least* frequently used words (Can't fit a model to frequently used words and not frequently used words)
7. Output the word graph into a gephi friendly text file.

**Comment by asimshankar** [comment]
(From API review: It seems find to add it, contributions welcome :)

**Comment by GeorgyZhou** [comment]
I can work on it and send a PR later today.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.
