### ISSUE TITLE
tfdbg doesn't work with tensorflow GPU version?

### ISSUE THREAD

**Issue by mingyr** [tensorflow/tensorflow#13900]
Could the dear developers confirm that tfdbg works with tensorflow GPU version or not?
At least on my platform it doesn't work.
OS: Red Hat Enterprise Linux Workstation release 7.3 (Maipo)
Python: Python 2.7.5
tensorflow (1.4.0rc0) (compiled from source with CUDA enabled, CUDA 8.0.61, cuDNN8-7.0.1)
nVidia Quadro P5000

the code for reproducing the problem is as follows:

```
import numpy as np
import tensorflow as tf

from tensorflow.python import debug as tf_debug

t = tf.constant(np.ones((10, 16)), tf.float32)

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev = 0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0., shape = shape)
    return tf.Variable(initial)

lin1_output_size = 32
lin2_output_size = 1

with tf.name_scope("lin1"):
    weight_shape = t.get_shape().as_list()[1:] + [lin1_output_size]
    lin1_output = tf.matmul(t, weight_variable(weight_shape)) + bias_variable([lin1_output_size])

with tf.name_scope("lin2"):
    weight_shape = [lin1_output_size, lin2_output_size]
    lin2_output = tf.matmul(lin1_output, weight_variable(weight_shape)) + bias_variable([lin2_output_size])

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    sess = tf_debug.LocalCLIDebugWrapperSession(sess)

    print(sess.run(lin2_output))

``` 

The phenomenon is after invoking stepper and steps for several steps, it is reporting segmentation fault and exit.

I just wonder is it due to GPU issue?

**Comment by caisq** [comment]
The "run" mode of tfdbg should be compatible with tensorflow GPU. The "stepper" mode of tfdbg is being deprecated and it not guaranteed to work with GPUs.

**Comment by mingyr** [comment]
@caisq Hi, shanqing, what's the story behind this? I mean why stepping is gonna be deprecated? Sometimes it is quite useful for looking into under the hood. Any thread or discussion relates to this decision? Thanks.

**Comment by caisq** [comment]
@mingyr, the information you can get from stepping, with the exception from tensor value overriding, should all be available from the `tfdbg> run` mode. The `tfdbg> run` mode also provides visibility into intermediate graph/tensor states at runtime. It is the main topic of our guide at:
https://www.tensorflow.org/programmers_guide/debugger

Just to be abundantly clear, tfdbg is not deprecated; only its stepper part is. The stepping support is being moved to a TensorBoard feature based on tfdbg. The new TensorBoard feature will provide a more interactive and visual step-debugging experience. We are currently working on the new feature. Please see https://github.com/tensorflow/tensorflow/issues/10478 for more related discussion.

**Comment by mingyr** [comment]
@caisq Great, appreciating the detailed explanation.  Please feel free to close this thread (or give me an indication if shall I close it). Many thanks.
