### ISSUE TITLE
Attempting to use uninitialized value lstm/LSTMCell/W_0

### ISSUE THREAD

**Issue by shiyemin** [tensorflow/tensorflow#1390]
### Environment info
Operating System: Rocks OS (Centos 6.5)

I installed from sources, and here is my version:
https://github.com/shiyemin/tensorflow/
Nothing changed but to make it compile successfully on our server.

### Steps to reproduce
1. add a LSTM layer between local3 and local4 in cifar10.py

  ```
  # lstm
  with tf.variable_scope('lstm') as scope:
    lstm_cell = rnn_cell.LSTMCell(512, input_size=384)
    feed_in = tf.split(0, 16, local3)
    outputs, states = rnn.rnn(lstm_cell, feed_in, scope=scope, dtype=tf.float32)
    lstm1 = tf.concat(0, outputs)

  # local4
  with tf.variable_scope('local4') as scope:
    weights = _variable_with_weight_decay('weights', shape=[512, 192],
                                          stddev=0.04, wd=0.004)
    biases = _variable_on_cpu('biases', [192], tf.constant_initializer(0.1))
    local4 = tf.nn.relu(tf.matmul(lstm1, weights) + biases, name=scope.name)
    _activation_summary(local4)
```
2. run cifar10_multi_gpu_train.py
3. Error: Attempting to use uninitialized value lstm/LSTMCell/W_0

### What have you tried?
1. Run this network in Test mode, and everything is fine. 
2. Run this network in Train mode, error "Attempting to use uninitialized value lstm/LSTMCell/W_0" occurs.

### Logs or other output that would be helpful

I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:107] Allocating 10.60GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:118] GPU 0 memory begins at 0x23ee00000 extends to 0x4e573199a
W tensorflow/core/common_runtime/executor.cc:1221] 0xb26c6f0 Compute status: Failed precondition: Attempting to use uninitialized value lstm/LSTMCell/W_0
	 [[Node: lstm/LSTMCell/W_0/_9 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_292_lstm/LSTMCell/W_0", _device="/job:localhost/replica:0/task:0/gpu:0"](lstm/LSTMCell/W_0)]]
	 [[Node: Identity_7/_8 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_267_Identity_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
W tensorflow/core/common_runtime/executor.cc:1221] 0xb26c6f0 Compute status: Failed precondition: Attempting to use uninitialized value lstm/LSTMCell/W_0
	 [[Node: lstm/LSTMCell/W_0/_9 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_292_lstm/LSTMCell/W_0", _device="/job:localhost/replica:0/task:0/gpu:0"](lstm/LSTMCell/W_0)]]
	 [[Node: Identity_6/_16 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_295_Identity_6", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
W tensorflow/core/common_runtime/executor.cc:1221] 0xb255bf0 Compute status: Failed precondition: Attempting to use uninitialized value lstm/LSTMCell/W_0
	 [[Node: lstm/LSTMCell/W_0/_9 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_292_lstm/LSTMCell/W_0", _device="/job:localhost/replica:0/task:0/gpu:0"](lstm/LSTMCell/W_0)]]
	 [[Node: lstm/LSTMCell/B/Assign/_5 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_265_lstm/LSTMCell/B/Assign", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
W tensorflow/core/common_runtime/executor.cc:1221] 0xb255bf0 Compute status: Failed precondition: Attempting to use uninitialized value lstm/LSTMCell/W_0
	 [[Node: lstm/LSTMCell/W_0/_9 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_292_lstm/LSTMCell/W_0", _device="/job:localhost/replica:0/task:0/gpu:0"](lstm/LSTMCell/W_0)]]
	 [[Node: lstm/LSTMCell/W_0/Assign/_13 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_293_lstm/LSTMCell/W_0/Assign", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
W tensorflow/core/common_runtime/executor.cc:1221] 0xb255bf0 Compute status: Failed precondition: Attempting to use uninitialized value lstm/LSTMCell/W_0
	 [[Node: lstm/LSTMCell/W_0/_9 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_292_lstm/LSTMCell/W_0", _device="/job:localhost/replica:0/task:0/gpu:0"](lstm/LSTMCell/W_0)]]
	 [[Node: init/NoOp_1/_19 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_5848_init/NoOp_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
W tensorflow/core/common_runtime/executor.cc:1221] 0xb26c6f0 Compute status: Failed precondition: Attempting to use uninitialized value lstm/LSTMCell/W_0
	 [[Node: lstm/LSTMCell/W_0/_9 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_292_lstm/LSTMCell/W_0", _device="/job:localhost/replica:0/task:0/gpu:0"](lstm/LSTMCell/W_0)]]
	 [[Node: lstm/LSTMCell/B/Assign/_4 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_265_lstm/LSTMCell/B/Assign", _device="/job:localhost/replica:0/task:0/gpu:0"](lstm/LSTMCell/B/Assign/_3)]]
W tensorflow/core/common_runtime/executor.cc:1221] 0xb26c6f0 Compute status: Failed precondition: Attempting to use uninitialized value lstm/LSTMCell/W_0
	 [[Node: lstm/LSTMCell/W_0/_9 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_292_lstm/LSTMCell/W_0", _device="/job:localhost/replica:0/task:0/gpu:0"](lstm/LSTMCell/W_0)]]
	 [[Node: lstm/LSTMCell/W_0/Assign/_12 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_293_lstm/LSTMCell/W_0/Assign", _device="/job:localhost/replica:0/task:0/gpu:0"](lstm/LSTMCell/W_0/Assign/_11)]]
Traceback (most recent call last):
  File "cifar10_multi_gpu_train.py", line 282, in <module>
    tf.app.run()
  File "/home/shiyemin/code/tensorflow/_python_build/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "cifar10_multi_gpu_train.py", line 278, in main
    train()
  File "cifar10_multi_gpu_train.py", line 237, in train
    sess.run(init)
  File "/home/shiyemin/code/tensorflow/_python_build/tensorflow/python/client/session.py", line 315, in run
    return self._run(None, fetches, feed_dict)
  File "/home/shiyemin/code/tensorflow/_python_build/tensorflow/python/client/session.py", line 511, in _run
    feed_dict_string)
  File "/home/shiyemin/code/tensorflow/_python_build/tensorflow/python/client/session.py", line 564, in _do_run
    target_list)
  File "/home/shiyemin/code/tensorflow/_python_build/tensorflow/python/client/session.py", line 586, in _do_call
    e.code)
tensorflow.python.framework.errors.FailedPreconditionError: Attempting to use uninitialized value lstm/LSTMCell/W_0
	 [[Node: lstm/LSTMCell/W_0/_9 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_292_lstm/LSTMCell/W_0", _device="/job:localhost/replica:0/task:0/gpu:0"](lstm/LSTMCell/W_0)]]
	 [[Node: lstm/LSTMCell/B/Assign/_5 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_265_lstm/LSTMCell/B/Assign", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by lukaszkaiser** [comment]
It sounds like the variables were not initialized, but that's strange if tf.initialize_all_variables is being run. Can you check that you initialized the variables? Also - could you make a repo with just the problematic model and test it against the head TensorFlow?

**Comment by shiyemin** [comment]
@lukaszkaiser OK, give me a minute.

**Comment by shiyemin** [comment]
@lukaszkaiser There is no way for me to compile it without modifying some of configuration... Will you please test it for me? It's quite easy to test as what i said in issue.

**Comment by shiyemin** [comment]
@lukaszkaiser By the way, everything is fine wittout LSTM or single GPU with LSTM. This can be confirmed by run cifar10_train.py and cifar10_multi_gpu_train.py.

**Comment by lukaszkaiser** [comment]
I tried to replicate your problem, but I can't -- I don't have a multi-gpu machine and, even though I tried, I cannot replicate the problem in a single-gpu setting in any way. In fact I even managed to run "python cifar10_multi_gpu_train.py --num_gpus=2" with your change and it was all ok, but I guess it just soft-placed everything on GPU0. One problem I can think of is that in your code your LSTM variables will not be placed on CPU, like the other ones. Can you try to put the whole LSTM on cpu first, just for a test (using tf.device around it)? If that works, then you can use pin_variables_to_cpu in your tf.device to just put the variables there, I hope. (It did not work once, I guess that's why cifar10 has _variable_on_cpu, but I think it's ok now.)

**Comment by shiyemin** [comment]
@lukaszkaiser Yeah, you are right. It works well after put LSTM on CPU. I can not find this "pin_variables_to_cpu". But i will modify LSTM to add a parameter and let it have a option to put variables on CPU.

A suggestion for this problem is to **add this pin_variables_to_cpu kind of parameter to rnn.rnn function**.

Thanks for your help!

**Comment by shiyemin** [comment]
@lukaszkaiser After putting all LSTM variables on CPU,  the error "Attempting to use uninitialized value lstm/LSTMCell/W_0" is still there. I have to give up on this and use single GPU. But there may be bugs in LSTM in a multi GPU situation.

**Comment by lukaszkaiser** [comment]
I don't think there are any bugs in LSTM. Variable placement in a multi-device or multi-machine setting is hard, but it's solved by tf.device. We do not want to have parameters for this in LSTM or any other function, as we'd basically need to add the same code to every function we write. It is solved differently using tf.device -- you can use a tf.device context around anything you want, and it will put variables (or any other ops you wish) on any device you specify. Here is an example.
  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/graph_util_test.py#L57

**Comment by thewintersun** [comment]
I find the same problem

**Comment by thewintersun** [comment]
when I use multi layer lstm, 
if I put the lstm variables in gpu:0, it works well . 
but when I change the lstm variable to gpu:1 or gpu:2,  
error:
tensorflow.python.framework.errors.FailedPreconditionError: Attempting to use uninitialized value RNN/MultiRNNCell/Cell0/LSTMCell/W_0

**Comment by thewintersun** [comment]
there may be bugs in LSTM in a multi GPU situation.

**Comment by shiyemin** [comment]
@thewintersun In a multi GPUs situation, we should put all variables on CPU. However, the sample code will put them on GPU. You may try copying the code out and having a little modification.

**Comment by thewintersun** [comment]
@shiyemin but I want to use multi-gpu to accelerate my calculate. 
if I put the variables on CPU, then the calcelate is on CPU too. 
so  the calcelerate is slow, that is not my purpose.

**Comment by thewintersun** [comment]
your means is put variables define on CPU, the variables's operation on GPU? @shiyemin

**Comment by shiyemin** [comment]
Yeah, you may refer to the cifar10 multi-gpu sample code. Variables should be put on CPU and ops can be put on GPUs.

**Comment by thewintersun** [comment]
ok，it works,  thank you

**Comment by hashbangCoder** [comment]
@shiyemin @lukaszkaiser 
Hi, 
I have the same issue but with GRUCell using dynamic_rnn. I'm using them in a slightly modified seq-seq model. To be sure you're solution was something like this ? : 
```
gru_cell = rnn_cell.GRUCell(1000)
with tf.device('/cpu:0'):    
    output,final_state = rnn.dynamic_rnn(gru_cell,decoder_batch,initial_state = encoder_state,sequence_length = lens)
```
Its not working for me :/

Relevant error stack - 
```
tensorflow.python.framework.errors.FailedPreconditionError: Attempting to use uninitialized value seqToseq/RNN/GRUCell/Candidate/Linear/Matrix
         [[Node: seqToseq/RNN/GRUCell/Candidate/Linear/Matrix/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](seqT
oseq/RNN/GRUCell/Candidate/Linear/Matrix)]]
Caused by op u'seqToseq/RNN/GRUCell/Candidate/Linear/Matrix/read', defined at:

File "chatbot.py", line 85, in <module>
    output,final_state = rnn.dynamic_rnn(gru_cell,decoder_batch,initial_state = encoder_state,sequence_length = decoder_lens)

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 580, in dynamic_rnn
    swap_memory=swap_memory, sequence_length=sequence_length)

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 709, in _dynamic_rnn_loop
    swap_memory=swap_memory)

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1873, in while_loop
    result = context.BuildLoop(cond, body, loop_vars)

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1749, in BuildLoop
    body_result = body(*vars_for_body_with_tensor_arrays)

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 692, in _time_step
    skip_conditionals=True)

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 326, in _rnn_step
    new_output, new_state = call_cell()

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 680, in <lambda>
    call_cell = lambda: cell(input_t, state)

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell.py", line 266, in __call__
    self._num_units, True))

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell.py", line 910, in _linear
    matrix = vs.get_variable("Matrix", [total_arg_size, output_size])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 732, in get_variable
    partitioner=partitioner, validate_shape=validate_shape)

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 161, in get_variable
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 478, in _get_single_variable

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 211, in __init__
    dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 316, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 831, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()
```

**Comment by hashbangCoder** [comment]
Nevermind. I figured it out. I was running the init op before starting queue runner threads

**Comment by laurel2935** [comment]
I also met a similar error, but it was cause by my own fault.
for my case, I defined the LSTM within a function (within a class), say
---
def prediction(self):
  some codes..
  lstm_cell = tf.nn.rnn_cell.LSTMCell(self.size_inner_vector)
  lstm_cell = tf.nn.rnn_cell.DropoutWrapper(lstm_cell, output_keep_prob=self.dropout)
  lstm_stack = tf.nn.rnn_cell.MultiRNNCell([lstm_cell] * self.num_hiddden_layers)
  output, _ = tf.nn.dynamic_rnn(lstm_stack, batch_3D_input2lstm, dtype=tf.float32)
  some codes..

  return result
---

For my case, I initialised the class without calling this function.
When I fetch the value of a variable within this function, I got the above error.

Thus a possible reason is that: your expected graph has not been constructed, but you are fetching the value of a non-existing node. 'this is my stupid case>_<'

By sharing it here, I hope it can help someone else.

**Comment by menasria** [comment]
I have the same problem, could you help me to solve it 
my code is :
****
train_count = len(X_train)
N_HIDDEN_UNITS = 64

lstm_fw_cell = tf.contrib.rnn.BasicLSTMCell(N_HIDDEN_UNITS)
lstm_bw_cell = tf.contrib.rnn.BasicLSTMCell(N_HIDDEN_UNITS)

def shared_layer(input_data):
    print('i m in shared layer')
    print(input_data)
    (output_fw, output_bw), (output_state_fw, output_state_bw) = tf.nn.bidirectional_dynamic_rnn(
                lstm_fw_cell,
                lstm_bw_cell,
                input_data,
                sequence_length=None,
                initial_state_fw=None,
                initial_state_bw=None,
                dtype=tf.float32,
                parallel_iterations=None,
                swap_memory=False,
                time_major=False,
                scope=None
            )
    outputs = tf.concat(axis=2, values=[output_fw, output_bw])
    return outputs

tf.get_default_graph()
X = tf.placeholder(tf.float32, [BATCH_SIZE, N_TIME_STEPS,N_FEATURES],name="input")
#Initialize the variables
init = tf.global_variables_initializer()
# launch the graph
with tf.Session() as sess:
    sess.run(init)
    for start, end in zip(range(0, train_count, BATCH_SIZE),
                          range(BATCH_SIZE, train_count + 1,BATCH_SIZE)):
        sess.run(shared_layer(X), feed_dict={X: X_train[start:end]})
****
the shared layer function run for tensor(input:0) but it does not for the next tensor, it araise the folowing error : 
FailedPreconditionError (see above for traceback): Attempting to use uninitialized value bidirectional_rnn/bw/basic_lstm_cell/kernel
	 [[Node: bidirectional_rnn/bw/basic_lstm_cell/kernel/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_rnn/bw/basic_lstm_cell/kernel)]]
