### ISSUE TITLE
can't able to build android_tensorflow_inference_java file in tensorflow

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [tensorflow/tensorflow#13916]
iam not able to android_tensorflow_inference_java.jar file in tensorflow using bazel.when i build i got the following error how can i solve this:

**$ bazel build //tensorflow/contrib/android:android_tensorflow_inference_java**

____Loading package: @local_config_xcode//
____Loading complete.  Analyzing...
____Loading package: tensorflow/java
____Loading package: @bazel_tools//third_party/java/jarjar
____Loading package: @bazel_tools//third_party/py/six
____Loading package: @bazel_tools//src/main/native/windows
____Loading package: @androidsdk//
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:64:1: Traceback (most recent call last):
        File "C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel", line 64
                create_system_images_filegroups(system_image_dirs = ["system-ima..."])
        File "C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/bazel_tools/tools/android/android_sdk_repository_template.bzl", line 298, in create_system_images_filegroups
                int(apidir.split("-")[1])
invalid literal for int() with base 10: "N".
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:windows' contains an error and its package is in error and referenced by '@androidsdk//:sdk-26'.
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:windows_msvc' contains an error and its package is in error and referenced by '@androidsdk//:sdk-26'.
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:windows_msys' contains an error and its package is in error and referenced by '@androidsdk//:sdk-26'.
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:windows' contains an error and its package is in error and referenced by '@androidsdk//:sdk-26'.
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:windows_msvc' contains an error and its package is in error and referenced by '@androidsdk//:sdk-26'.
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:windows_msys' contains an error and its package is in error and referenced by '@androidsdk//:sdk-26'.
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:windows' contains an error and its package is in error and referenced by '@androidsdk//:sdk-26'.
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:windows_msvc' contains an error and its package is in error and referenced by '@androidsdk//:sdk-26'.
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:windows_msys' contains an error and its package is in error and referenced by '@androidsdk//:sdk-26'.
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:windows' contains an error and its package is in error and referenced by '@androidsdk//:sdk-26'.
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:windows_msvc' contains an error and its package is in error and referenced by '@androidsdk//:sdk-26'.
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:windows_msys' contains an error and its package is in error and referenced by '@androidsdk//:sdk-26'.
ERROR: C:/tools/msys64/tmp/_bazel_deemsys/28x4acs5/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:sdk-26' contains an error and its package is in error and referenced by '@androidsdk//:sdk'.
ERROR: E:/arisai1/tensor/tensorflow/WORKSPACE:20:1: Target '@androidsdk//:sdk' contains an error and its package is in error and referenced by '//external:android/sdk'.
ERROR: Analysis of target '//tensorflow/contrib/android:android_tensorflow_inference_java' failed; build aborted.
____Elapsed time: 25.324s

**Comment by skye** [comment]
Please include the information requested in the new issue template.

**Comment by andrewharp** [comment]
@ArigarasuthanRepo It appears you're attempting to build for Android on Windows, which is not expected to be supported until [1.0](https://bazel.build/roadmap.html). Until then please see https://github.com/tensorflow/tensorflow/issues/6385 for various workarounds, including building via Linux for Windows and the recommended AAR integration via gradle + Android Studio (also described in tensorflow/contrib/android/README.me).
