### ISSUE TITLE
build tensorflow for gpu faild 

### ISSUE THREAD

**Issue by haolidong** [tensorflow/tensorflow#13918]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:r1.3
- **Python version**: 3.5
- **Bazel version (if compiling from source)**:0.7.0
- **CUDA/cuDNN version**:CUDA9.0/cuDNN7
- **GPU model and memory**:GTX 660M / 2G memory

### Describe the problem
I'm building tensorflow for gpu from source according to the official guide https://www.tensorflow.org/install/install_sources , but alway faild, error message show in below:
`ERROR: /home/dangerous/.cache/bazel/_bazel_dangerous/821f9ca421a3e885f021819a154f9a6e/external/nccl_archive/BUILD:33:1: output 'external/nccl_archive/_objs/nccl/external/nccl_archive/src/broadcast.cu.pic.o' was not created
ERROR: /home/dangerous/.cache/bazel/_bazel_dangerous/821f9ca421a3e885f021819a154f9a6e/external/nccl_archive/BUILD:33:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.`

**Comment by caisq** [comment]
cc @gunan @yifeif @benoitsteiner @vrv 
 
I'm tackling this build failure (among other build issues) today. I expect the fix to be sync'ed to GitHub within 1-2 days.
