### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError

### ISSUE THREAD

**Issue by wjb123** [tensorflow/tensorflow#13919]
I have run a tensorflow code, which always give following errors:
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'div_1' has inputs from different frames. The input 'while/Mean_1' is in frame 'while/while/'. The input 'div_1/y' is in frame ''.

And I have searched for a long time, but find no proper solutions. I really wonder that anyone could give me some advice.

**Comment by drpngx** [comment]
This is likely better asked on stackoverflow.

Can you should the code?

**Comment by michaelisard** [comment]
Agreed, stackoverflow is the best place for this question. Without seeing any code, my best guess is that you have captured a Python Tensor object created within a tf.while_loop and are attempting to use it outside the loop. The error message in such a case is not very helpful, but the basic problem is that the value you are trying to use is not well-defined: which iteration should it pick? What if the loop doesn't execute at all (the condition is initially false)?
