### ISSUE TITLE
s390x Tensorflow CI build failure 

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#13914]
Hello, 
Tensorflow CI build fails with an error: 
```
java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer
	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:71)
	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)

```

**Comment by Nayana-ibm** [comment]
@gunan Continuing Tensorflow s390x CI discussion here. 
For VM-0, jnlp service is up and running. Not sure about the error mentioned above. 
Do we need to upgrade/install any package?

**Comment by Nayana-ibm** [comment]
For VM-0, http://ci.tensorflow.org/computer/ibm-contrib-s390x-0/
I have again started JNLP service still it shows 'Ping response time is too long or timed out.'.

**Comment by gunan** [comment]
Sent you an email to debug the issue with s390x-0.
on the other machine, could you try replacing jenkins slave.jar with this one:
http://ci.tensorflow.org/jnlpJars/slave.jar

**Comment by Nayana-ibm** [comment]
@gunan Issue resolved  after replacing jenkins slave.jar on s390x-1. Now builds are getting triggered on this node. About s390x-0, I have sent an email with details to you.

**Comment by Nayana-ibm** [comment]
s390x-0 is also now up. builds are getting triggered on this node also.

**Comment by gunan** [comment]
Looks like this specific issue was resolved?
Closing, please reopen if this specific issue still persists.
