### ISSUE TITLE
Examples of GANs using tensorflow estimator

### ISSUE THREAD

**Issue by hanfeisun** [tensorflow/tensorflow#13925]
I found all the estimator examples in the tutorial assumes there is `x`(features) and `y`(labels).

However, in the context of GANs-based method, there is no `y` in the dataset. Would there be any example of GANs using tensorflow estimator?

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by hanfeisun** [comment]
For anyone who is also curious about this question, I posted a thread on stackoverflow: https://stackoverflow.com/questions/46940837/how-to-implement-gans-by-tensorflow-estimator
