### ISSUE TITLE
Tensorflow import fails with Segmentation fault error

### ISSUE THREAD

**Issue by abraham221986** [tensorflow/tensorflow#13947]
Hello

I have pip3 installed tensorflow CPU only
Python version:  3.5.2
OS:LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.8 (Santiago)
Release:        6.8
Codename:       Santiago

Install command: pip3 install tensorflow

echo $LD_LIBRARY_PATH
:/usr/local/lib:/grapps/hadoop/instantclient/instantclient_11_2:/usr/local/lib:/opt/glibc-2.14/lib

Python 3.5.2 (default, Mar 23 2017, 07:51:35)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import tensorflow
Segmentation fault

Also tried to import scipy,numpy and matplotlib before importing tensorflow as per suggestion seens in some other cases https://github.com/tensorflow/tensorflow/issues/2034. 

But nothing solved the issue. 

Thanks for the advice 

Abraham

**Comment by michaelisard** [comment]
I'm sorry but we aren't able to provide support for Red Hat Linux. Tagging with community support.

**Comment by rthadur** [comment]
Please try to test with latest tested builds here https://www.tensorflow.org/install/source#tested_build_configurations, which will resolve the issue. Thank you
