### ISSUE TITLE
How can I use all of cpu cores in android 

### ISSUE THREAD

**Issue by xunkaixin** [tensorflow/tensorflow#13944]
Hi, 
     Thank your for your work.
     In my app, I use tensorflow to classify.  But CPU usage are lower, just about 30%. My device has 4 cores.  I want to use all CPUs to reduce cost time. I try to modify intra_op_parallelism_threads and  inter_op_parallelism_threads, when compile the libtensorflow_inference.so.  And use TF_SetConfig to set  TF_SessionOptions.　But it doesn't work. 
     Can you give me some advice?  thank you.

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by MohammadMoradi** [comment]
Hi @xunkaixin . Did you find any solution? I am facing the same problem.
