### ISSUE TITLE
Create Model file for Object (face) Recognition in C++

### ISSUE THREAD

**Issue by ashokbugude** [tensorflow/tensorflow#13946]
I am doing research on face Recognition using tensorflow.
Can I please know how how to use the code to create model file for face recognition.

**Task (required in C++)**
I have 5 folders, each folder has 4 images of a particular person.
I would like to train the images and generate a model file from scratch.
I would then like to use the model file for recognizing one of the 5 persons.

**Steps followed**
1. https://www.tensorflow.org/tutorials/image_retraining

**Issues**
> 1. Its in Python , but I wanted in C++
> 2. It is not training the model file from scratch
> 

2.https://github.com/tensorflow/models/tree/master/research/inception/inception

**Issue Resolved**
> Model can be trained from scratch. 
>
**Unresolved Issue**
> Its in Python , but I wanted in C++
> 

Please help me in creating the model file in C++

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ashokbugude** [comment]
I am sorry to say but haven't received any response in Stackoverflow yet - https://stackoverflow.com/questions/46909787/tensorflow-create-model-file-for-object-face-recognition-in-c
