### ISSUE TITLE
Doubt in definition of state returned by dynamic_rnn for LSTM cell in tensorflow

### ISSUE THREAD

**Issue by bhargav104** [tensorflow/tensorflow#13943]
### Describe the problem
Can someone tell me whether the state returned by the dynamic_rnn function for a LSTM cell is (h,c) or is (c,h)? c - cell state h - hidden state.

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
