### ISSUE TITLE
Support grayscale .bmp images

### ISSUE THREAD

**Issue by andreas-eberle** [tensorflow/tensorflow#13942]
The current implementation only supports 3 (RGB) or 4 (ARGB) channel BMP images. However, grayscale images are also often used for machine learning stuff. Therefore it would be great to be able to read 1 channel BMP images.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/decode_bmp_op.cc#L71

**Comment by skye** [comment]
@rmlarsen FYI (please feel free to cc anyone else who may be interested)

**Comment by andreas-eberle** [comment]
Any news?

**Comment by yongtang** [comment]
I think grayscale bmp is just 1 byte per pixel? Created a PR #14296 for the support.

**Comment by andreas-eberle** [comment]
Cool, thx.

**Comment by andreas-eberle** [comment]
Thanks @yongtang!
