### ISSUE TITLE
Tensorboard not displaying event files

### ISSUE THREAD

**Issue by droidben** [tensorflow/tensorflow#13953]
Hi all
First time posting, please forgive and correct me if i do anything wrong or stupid.

I have an issue where I am training a model, but tensorboard isn't displaying any data from the event files. I've done everything in my knowledge. Yes I read the tensorboard ReadMe FAQ. [https://github.com/tensorflow/tensorboard/blob/master/README.md#frequently-asked-questions](url)

I start the train process with the folowing command (cmd started in folder with the directories "tf_files" and "flower_photos" int it):
`python retrain.py --bottleneck_dir=tf_files/bottlenecks --model_dir=tf_files/models/"mobilenet_0.50_224" --summaries_dir=tf_files/training_summaries/"mobilenet_0.50_224" --output_graph=tf_files/retrained_graph.pb --output_labels=tf_files/retrained_labels.txt --architecture="mobilenet_0.50_224" --image_dir=flower_photos`

![retrain_start_1](https://user-images.githubusercontent.com/9570377/31962587-4074134c-b8fe-11e7-95ab-53b565cfa96e.png)
![retrain_start_2](https://user-images.githubusercontent.com/9570377/31962591-4317b784-b8fe-11e7-94f2-aebbd8bd11ef.png)
![retrain_finish](https://user-images.githubusercontent.com/9570377/31962594-459de2da-b8fe-11e7-8511-76a502fc7763.png)

The retraining finishes successfully.

Tensorboard i start with the command:
`tensorboard --logdir i:/temp/learningtf/tf_files/training_summaries`

![start_tensorboard](https://user-images.githubusercontent.com/9570377/31962693-8ddea9c6-b8fe-11e7-8876-b40bda7349b0.png)

The command above with `--inspect` give me the following output:

![tensorboard_inspect_1](https://user-images.githubusercontent.com/9570377/31962725-a472b268-b8fe-11e7-948b-75c0adb866b1.png)
![tensorboard_inspect_2](https://user-images.githubusercontent.com/9570377/31962727-a6f84458-b8fe-11e7-9b3a-0f4e41a8ebe0.png)

As you can see, tensorboard doesn't display anything. Im quite confused.
![tensorboard_webinterface](https://user-images.githubusercontent.com/9570377/31962837-faed81b8-b8fe-11e7-8f14-d7407a4b9130.png)

Here are the event files I'm talking about. If these are not the files you need, post a reply and tell my which files i need to upload, please.
[the_i_hope_right_files.zip](https://github.com/tensorflow/tensorflow/files/1412114/the_i_hope_right_files.zip)

If you need eny further Info on this case, please let me know.
Thanks for any help in advance.

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ybsave** [comment]
I do think this is a bug. After updating to Tensorflow 1.4, my tensorboard does not show anything, including previously working folders. Then I downgraded the Tensorboard version, it still does not work. Therefore, I believe that it is the Tensorflow 1.4's bug. @michaelisard . Would you please re-open this issue? 

My issue has been posted at https://github.com/tensorflow/tensorboard/issues/695

**Comment by juhui0419** [comment]
@ybsave You are genus!
