### ISSUE TITLE
tf.contrib.layers.flatten has neither "name" nor "reuse" parameter.

### ISSUE THREAD

**Issue by hanfeisun** [tensorflow/tensorflow#13956]
I think `tf.contrib.layers.flatten` is just a special case of `tf.reshape`. 

However, while `tf.reshape` has `name` parameter, `tf.contrib.layers.flatten` doesn't have one. Also neither of them has `reuse` parameter.  

Is `tf.contrib.layers.flatten` a deprecated API?

**Comment by hanfeisun** [comment]
Just found the flatten has been added to core layers `tf.layers` recently.

https://github.com/tensorflow/tensorflow/commit/80ed8afc02b16adb209bffeb551e7f0c435985f6

I was curious why reshape is not added into core layers as well.

**Comment by skye** [comment]
@fchollet can you comment or redirect? Thanks.

**Comment by fchollet** [comment]
There was an attempt to introduce `Reshape` in `tf.layers` at the same time as `Flatten`, but it was not approved; if I recall correctly this was to limit API surface.

You could use `tf.keras.layers.Reshape` instead.
