### ISSUE TITLE
Feature request: adding spectral functions for preserving phase information

### ISSUE THREAD

**Issue by doktorneergaard** [tensorflow/tensorflow#13977]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes (attempting to)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 3.5.4
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA v8.0.60, cuDNN 6.0
- **GPU model and memory**: GTX 1060 6 GB
- **Exact command to reproduce**: N/A

### Describe the problem
I am working on a data processing pipeline directly in my tensorflow graph. In that case, I would like to use continuous wavelet transforms (CWT) in order to transform time-series data into scalograms instead of spectrograms in order to increase time-frequency resolution. I can only find a single API for performing the CWT that is compatible directly with TF, but unfortunately, it is not 'enough' since the tf.conv2 operator does not work with inputs of different types (real, complex). I therefore am trying to fix my own op using TF's standard ops, but have hit a snag. The spectral ops rfft and irfft only return and accept positive frequency components, and for my purpose, I would have to apply phase transformations of the spectrum, resulting in non-Hermitian symmetry (in which case I cannot use the tf.spectral.irfft to inverse transform!). So what I request, are spectral ops that return and accept the full complex spectra of input signals. 

### Source code / logs
N/A

**Comment by michaelisard** [comment]
@rmlarsen are you the right person to look at this feature request?

**Comment by rryan** [comment]
Hi @doktorneergaard, 

I think [`tf.spectral.fft`](https://www.tensorflow.org/api_docs/python/tf/fft) and [`tf.spectral.ifft`](https://www.tensorflow.org/api_docs/python/tf/ifft) are what you're looking for. They return the full FFT, not the "real" FFT.

**Comment by rryan** [comment]
By the way, I think many people would love to have Continuous Wavelet Transforms available in TensorFlow (perhaps as part of `tf.spectral` or `tf.contrib.signal`), or at least as a library. Please do publish your code once you get it working!

**Comment by rryan** [comment]
@doktorneergaard great to hear, thanks!

**Comment by pachpandepriti** [comment]
@rryan How can I add a fix fft length to the function tf.spectral.ifft and tf.spectral.fft?

**Comment by rryan** [comment]
@pachpandepriti I'm afraid you'll have to slice the input to `fft`/`ifft` like so:
```python
fft_size = 256
# A [batch_size, num_frames, frame_length] signal. 
x = tf.random_normal([1, 24000, 512])
# Take the 1D DFT of the inner dimension with a 256-point FFT. 
# Without the slice, a 512-point FFT would be taken, since the inner dimension is 512.
s = tf.fft(x[:, :, :fft_size])
```

**Comment by pachpandepriti** [comment]
@rryan can u guide me how to implement fftshift(as in matlab) on a tensor? I need to shuffle the elements in a tensor and then reshuffle it

**Comment by pachpandepriti** [comment]
@rryan Hi I want to shuffle a tensor using lambda layer, but it is giving me an error :
order = range(len(l));
TypeError: object of type 'Tensor' has no len()

def shuffle_forward(l, axis=-1):
order = range(len(l));
random.shuffle(order)
return list(np.array(l)[order]), order

def shuffle_backward(l, order):
l_out = [0] * len(l)
for i, j in enumerate(order):
l_out[j] = l[i]
return l_out
can u guide me what am I doing wrong

**Comment by rryan** [comment]
Unfortunately Tensor objects can't be treated like NumPy arrays in the way you are using them.

Beyond the len issue that you are already seeing (you can use `tf.shape(l)[axis]` for that), Tensors also don't support advanced indexing that you are using in your example above.

It will not be most efficient but you can unstack on the desired axis, permute, then restack. Something like this (I haven't tested it):

```python
def shuffle_forward(l, axis=-1):
  order = range(l.shape[axis].value)
  random.shuffle(order)
  slices = tf.unstack(l, axis=axis)
  return tf.stack([slices[i] for i in order], axis=axis), order

def shuffle_backward(l, order, axis=-1):
  slices = tf.unstack(l, axis=axis)
  out = [None] * len(order)
  for i, j in enumerate(order):
    out[j] = slices[i]
  return tf.stack(out, axis=axis)
```

**Comment by pachpandepriti** [comment]
@rryan for tf.ifft function if I don't give the fft length will it take the batch_size as fft length when the function is used inside a model?

**Comment by rryan** [comment]
> @rryan for tf.ifft function if I don't give the fft length will it take the batch_size as fft length when the function is used inside a model?

It will use the inner-most dimension as the FFT length (not the batch size, which is usually the outer-most dimension).

**Comment by pachpandepriti** [comment]
@rryan Thanks for the help. Slicing the input  option worked for me.

**Comment by pachpandepriti** [comment]
@rryan When I  use the slicing option. I have a 2D tensor as input to the ifft function. I don't get the expected output as it treats both the incoming values as real. Is there any option where I can have first column as real and second as imaginary

**Comment by EliasHasle** [comment]
> Adding an `fft_length` parameter to `tf.spectral.fft` and `tf.spectral.ifft` has been on my TODO list for a while, though.

Any chance of getting an axis parameter, such as in numpy? (Maybe I should open a new issue for that feature request?)
