### ISSUE TITLE
begin_shift_axis not defined in tf.contrib.layers.layer_norm

### ISSUE THREAD

**Issue by techmatt** [tensorflow/tensorflow#13975]
The live version of tensorflow's api docs here:
https://www.tensorflow.org/api_docs/python/tf/contrib/layers/layer_norm

Refer to begin_shift_axis, which isn't defined.  I assume this is a typo and is meant to be begin_params_axis

Apologies if documentation bugs are supposed to be tracked elsewhere, it's not clear how those should be reported.

**Comment by yongtang** [comment]
Thanks @techmatt. Yes I think it should be `begin_params_axis`. Created a PR #13979 for the fix.

**Comment by michaelisard** [comment]
Marking contributions welcome while we wait for the PR: thanks!
