### ISSUE TITLE
Udacity examples should be improved (/tensorflow/examples/udacity)

### ISSUE THREAD

**Issue by mxrguspxrt** [tensorflow/tensorflow#1398]
https://www.udacity.com/course/viewer#!/c-ud730 is a really cool course in the context of Machine Learning and TensorFlow. After completing Coursera Andrew Ng course, they give valuable reasoning why and how something should be done in TensorFlow.

But, there is an issue.

Theory part in videos and implementing it in TensorFlow do not click together. Forum is full of questions in the format "how should it be done?", "am I doing it correctly?".

Yes, I can spend 2 days on a one assignment, search internet and take parts from manuals that are on the tensorflow.org page, but still I am not convinced that I am doing it correctly. 

Please improve https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/udacity so that best practice, how previous task would have been correctly solved, is included in the next task.

**Comment by OBorce** [comment]
+1

**Comment by pulinagrawal** [comment]
I agree.

**Comment by vincentvanhoucke** [comment]
There isn't going to be any updates to the course from the instructors beyond fixes at this point.
