### ISSUE TITLE
Error using tf.image.random._ : 'numpy.ndarray' object has no attribute 'get_shape'

### ISSUE THREAD

**Issue by julienroy13** [tensorflow/tensorflow#1399]
**Intro**

I am using a modified version of the Tensorflow tutorial "Deep MNIST for experts" with the Python API for a medical images classification project using convolutionnal networks.

I want to artificially increase the size of my training set by applying random modifications on the images of my training set.

**Problem**

When I run the line : 
    
`flipped_images = tf.image.random_flip_left_right(images)`

I get de following error :

> AttributeError: 'numpy.ndarray' object has no attribute 'get_shape'

My Tensor "images" is an ndarray (shape=[batch, im_size, im_size, channels]) of "batch" ndarrays (shape=[im_size, im_size, channels]).

Just to check if my input data was packed in the right shape and type, I have tried to apply this simple function in the (not modified) tutorial "Tensorflow Mechanics 101" and I get the same error.

Finally, I still get the same error trying to use the following functions :

 - tf.image.random_flip_up_down() 
 - tf.image.random_brightness()
 - tf.image.random_contrast()

**Questions**

As input data is usually carried in Tensorflow as ndarrays, I would like to know :   

 1. Is it a bug of Tensorflow Python API or is it my "fault" because
    of the type/shape of my input data?
 2. How could I get it to work and be able to apply    "tf.image.random_flip_left_right" to my training set?

**Comment by martinwicke** [comment]
The function requires its input to already be a tensor. You can call `convert_to_tensor` to make a tensor from a numpy array, or you can put the numpy data into a `tf.constant` first. 

Or you could fix `flip_left_to_right` to call `convert_to_tensor`, which would be the right thing to do.

**Comment by girving** [comment]
It looks like we could use a cleaning pass through some of the image ops.  A lot of them unnecessarily require known shape tensors as well.

**Comment by martinwicke** [comment]
On the `random_` ones now, which only work on a single image anyway. I think.

**Comment by fayeshine** [comment]
I'll work on this:  fix flip_left_to_right to call convert_to_tensor

**Comment by madisonmay** [comment]
I believe this can be closed now that PR #1428 has been merged?  I'm surprised this issue wasn't auto-closed on merge.

**Comment by girving** [comment]
PR #1428 didn't include something like "Fixes #1399" in the commit message, so it didn't autoclose.
