### ISSUE TITLE
g3doc format

### ISSUE THREAD

**Issue by kmatzen** [tensorflow/tensorflow#14]
Has the g3doc specification been publicly released?  Is an effort going to be made so that outside contributors know exactly how comments should be written in order to be correctly parsed?

**Comment by Hello1024** [comment]
The g3doc used in Tensorflow is, I believe, identical to [Markdown](https://daringfireball.net/projects/markdown/syntax).   If you find anything that doesn't meet the markdown specification, file an issue.

**Comment by kmatzen** [comment]
I mean the comments in the C++ that are used to generate the markdown files.

Example:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/public/env.h#L47
```
  /// \brief Returns a default environment suitable for the current operating
  /// system.
  ///
  /// Sophisticated users may wish to provide their own Env
  /// implementation instead of relying on this default environment.
  ///
  /// The result of Default() belongs to this library and must never be deleted.
  static Env* Default();
```
is used to generate
```
* [`static Env* tensorflow::Env::Default()`](#static_Env_tensorflow_Env_Default)
  * Returns a default environment suitable for the current operating system.
```
and
```
#### `static Env* tensorflow::Env::Default()` {#static_Env_tensorflow_Env_Default}

Returns a default environment suitable for the current operating system.

Sophisticated users may wish to provide their own Env implementation instead of relying on this default environment.

The result of Default() belongs to this library and must never be deleted.
```

My point is that the docs were pre-generated. I can't find another project where Google has open sourced the g3doc utility so that others may rerun it and update the documentation.

If the answer is "the syntax is just like doxygen", then that's an acceptable answer, although it would still be nice to be given the same tool to generate the markdown.

**Comment by martinwicke** [comment]
The syntax is, in fact, doxygen: part of our docs generation pipeline calls doxygen. We are working on making more of the doc generator publicly available, but it requires a decent amount of untangling.

**Comment by martinwicke** [comment]
Check out the documentation authoring guide: https://www.tensorflow.org/community/documentation

**Comment by martinwicke** [comment]
Everything from TensorFlow source code to markdown is open-source. It should be usable for other projects, although the code may have aspects specific to TensorFlow which may not trivial to extract. 

TensorFlow docs are not served using g3docs. I cannot speak to the specifics of that presentation.
