### ISSUE TITLE
Bazel build for CUDA failed on Ubuntu w/ lastest tip + CUDNN 6.0 + CUDA 8.0

### ISSUE THREAD

**Issue by rlegithub** [tensorflow/tensorflow#14002]
Hi,

I am trying to build latest TF with CUDNN 6.0 + CUDA 8.0 on Ubuntu 14 but it failed with the following error message. I found some similar issue (https://github.com/tensorflow/tensorflow/issues/469) reported in the past, not sure if the latest tip has fixed it?

Any suggestion would be appreciated.

Thanks

**Build Command**
- build command for CUDA that failed
`bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package `

- build for CPU works well
`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

**System Info**
- bazel version : Build label: 0.5.4
- CUDA: 8.0
- CUDNN 6.0
- TF origin/master latest sync as 10/26/17 (cb7cb40 Merge pull request #13972 from taehoonlee/fix_typos)

**Error message:**
`ERROR: $PROJECT_ROOT/tensorflow/tensorflow/stream_executor/BUILD:52:1: undeclared inclusion(s) in rule '//tensorflow/stream_executor:cuda_platform':
this rule is missing dependency declarations for the following files included by 'tensorflow/stream_executor/cuda/cuda_blas.cc':
  '/usr/local/cuda/include/cublas_api.h'
  '/usr/local/cuda/include/driver_types.h'
  '/usr/local/cuda/include/host_defines.h'
  '/usr/local/cuda/include/cuComplex.h'
  '/usr/local/cuda/include/vector_types.h'
  '/usr/local/cuda/include/builtin_types.h'
  '/usr/local/cuda/include/device_types.h'
  '/usr/local/cuda/include/surface_types.h'
  '/usr/local/cuda/include/texture_types.h'
  '/usr/local/cuda/include/cuda_fp16.h'
  '/usr/local/cuda/include/library_types.h'
tensorflow/stream_executor/cuda/cuda_blas.cc: In function 'cudaDataType_t perftools::gputools::cuda::{anonymous}::CUDAComputationType(perftools::gputools::blas::ComputationType)':
tensorflow/stream_executor/cuda/cuda_blas.cc:527:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
`

**Comment by skye** [comment]
@yifeif can you take a look or redirect? Thanks.

**Comment by gunan** [comment]
Just to make sure, could you share how you ran `configure` script?
I believe this is a duplicate of #10665

**Comment by rlegithub** [comment]
Thanks for reply @skye and @gunan . I found the root cause, it turn out there was a problem in the CUDNN header that I modified the path, which is not added to bazel header list properly.

Closing the issue now.

Thanks

**Comment by albenoit** [comment]
Hi, can you provide more details on the CUDNN header problem and the solution provided ?
Actually compiling Tensorflow from one version to the other on not officially supported distributions is always a mess. Sharing helps a lot.
Thanks in advance
