### ISSUE TITLE
tf.python.keras can't import np_utils

### ISSUE THREAD

**Issue by vkmenon** [tensorflow/tensorflow#14008]
Typically i'm able to replace any "from keras.X import Y" with "from tensorflow.python.keras.X import Y"

This works with most things, but it does not translates to keras.utils. I can run:
from keras.utils import np_utils

But the following fails:
from tensorflow.python.keras.utils import np_utils

The workaround is just to use: 
from tensorflow.python.keras._impl.keras.utils import np_utils

Unsure if this is intended or not. I guess I'd consider this either a bug fix or a feature request.

**Comment by skye** [comment]
@fchollet

**Comment by fchollet** [comment]
`np_utils` is not part of the public API. Please import symbols from `tensorflow.keras.utils` instead.

**Comment by DaniilStreletskiy** [comment]
for tf 1.3.1
`from tensorflow.contrib.keras.python.keras.utils    import np_utils`

for tf 1.4.1
`from tensorflow.python.keras          import utils`

**Comment by meetrainier** [comment]
in tensorflow 2.0.0 ?

**Comment by nohheamin** [comment]
In tensorflow 2.1.0
from tensorflow.keras import utils

**Comment by adarshm93** [comment]
in tensorflow 2.2.0?

**Comment by martianvenusian** [comment]
> in tensorflow 2.2.0?

`import tensorflow.keras.utils as utils`
or
`from tensorflow.keras import utils`

**Comment by pulakdas1999** [comment]
I have tensorflow 2.3.0 installed on my system !!
And it throws the following error : AttributeError: module 'tensorflow.keras.utils' has no attribute 'np_utils'
Can anyone help me solve this issue !!
Thanks in advance...........

**Comment by TsigabuTe** [comment]
from tensorflow.keras.utils import to_categorical

**Comment by GentleWine** [comment]
confused about where I can find the detailed announcement of this change. cuz I'm migrating from a very old version and "from keras.utils import np_utils" works but "from tf.keras.utils import np_utils" does not.
