### ISSUE TITLE
layers-based cuDNN RNN functionality not working

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#14001]
I'm trying to use the newly added layers-style cuDNN RNN functionality. I'm running TF 1.4.0-rc0 on Ubuntu with Pascal GPUs, compiled from source with CUDA 8 and cuDNN 7. When trying to import the relevant library:

`from tensorflow.contrib.cudnn_rnn.python.layers import cudnn_rnn`

I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/tensorflow-1.4.0-rc0/local/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py", line 33, in <module>
    resource_loader.get_path_to_datafile("_cudnn_rnn_ops.so"))
  File "/usr/local/tensorflow-1.4.0-rc0/local/lib/python2.7/site-packages/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "/usr/local/tensorflow-1.4.0-rc0/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/tensorflow-1.4.0-rc0/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/tensorflow-1.4.0-rc0/local/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/_cudnn_rnn_ops.so: cannot open shared object file: No such file or directory
```

Note that the non-layer based cuDNN RNN functionality works fine. I.e. I can run this:

`from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops`

and run cuDNN-based RNNs with no problem otherwise.

**Comment by printdhruv** [comment]
@alquraishi Did you try to set dynamic path to solve the error `cannot open shared object file: No such file or directory`?
Can you fill the ISSUE_TEMPLATE [here](https://github.com/printdhruv/tensorflow/blob/master/ISSUE_TEMPLATE.md)?

**Comment by alquraishi** [comment]
Not sure what you mean by "dynamic path", but if I create a symbolic link in `.../layers/_cudnn_rnn_ops.so` to `.../ops/_cudnn_rnn_ops.so` it solves the problem. I believe this is a bug. I think the path in `tensorflow/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py` pointing to `_cudnn_rnn_ops.so` is incorrect.

Here's the rest of information you requested
OS: Ubuntu 14.04
TensorFlow 1.4.0-rc0 installed from source
Python version: 2.6
Bazel version (if compiling from source): 0.7.0
CUDA/cuDNN version: 8/7
GPU model and memory: Titan X Pascal

**Comment by printdhruv** [comment]
@alquraishi Yes. By "dynamic path" I meant to play with the symbolic link! Can you tell what you changed/modified `tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py` 

for the lines 32-33 which worked for you ,

`_cudnn_rnn_ops_so = loader.load_op_library(
    resource_loader.get_path_to_datafile("_cudnn_rnn_ops.so"))`

**Comment by alquraishi** [comment]
I actually didn't much with the `.py` file. I just created a symbolic link in the system so that the `layers` directory effectively contains its own copy of `_cudnn_rnn_ops.so`. I was just saying that the bug is in `tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py`

**Comment by printdhruv** [comment]
I see! Can you try to play with the `cudnn_rnn.py` ? It would be great if you can find solution without adding symbolic link?

**Comment by alquraishi** [comment]
Hi, the symbolic link command was:

`ln -s ../ops/_cudnn_rnn_ops.so _cudnn_rnn_ops.so`

executed in `/usr/local/tensorflow-1.4.0-rc0/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/layers`

Also, modifying the `cudnn_rnn.py` file so that lines 32-33 read:

`_cudnn_rnn_ops_so = loader.load_op_library(
    resource_loader.get_path_to_datafile("../ops/_cudnn_rnn_ops.so"))`

fixes the problem as well.

**Comment by printdhruv** [comment]
In `_cudnn_rnn_ops_so = loader.load_op_library( resource_loader.get_path_to_datafile("../ops/_cudnn_rnn_ops.so"))` is the `../ops/_cudnn_rnn_ops.so` sufficient ?

**Comment by alquraishi** [comment]
Yes that's all that is necessary to make it work.

**Comment by printdhruv** [comment]
@alquraishi Thanks for sending out a reply. I am not sure will `../ops/_cudnn_rnn_ops.so` be enough for 
all OS-compatibility, as `load_op_library and get_path_to_datafile` are responsible for handling OS specific operations?

**Comment by alquraishi** [comment]
Yes you're right it would have to be platform-specific, presumably `os.path` should work.

**Comment by asimshankar** [comment]
Seems like the PR is in flight, so marking this as contributions welcome.

**Comment by asimshankar** [comment]
Addressed in https://github.com/tensorflow/tensorflow/commit/a6a61884396ef1d51b01f8e13df21becb23fd0c8
