### ISSUE TITLE
#tensorflow##PYNQ# Could I install tensorflow in my PYNQ-Z1 ? 

### ISSUE THREAD

**Issue by GEEK7COLSON** [tensorflow/tensorflow#14013]
I wanna build some Classifier with it. I'm used to build Classifiers with TensorFlow. 
So I want to know whether it is technically possible.THX!!
[http://www.pynq.io/](url)

**Comment by michaelisard** [comment]
I am not very familiar with pynq but [the only mention of pynq and TF together I could find](https://groups.google.com/forum/#!topic/pynq_project/kG8ZtRg4k_A) suggests that pynq is 32-bit. If that's the case I don't think it will work because TensorFlow is 64-bit only.

**Comment by gunan** [comment]
We have never tried this ourselves. You can try to adapt our raspberry pi or mobile build for your device. Those are the builds that has the most chance to work on a 32-bit system (but even they could fail).
But I suspect there will be compilation failures. You will need to work through them yourself, as we do not have this device ourselves and we wont be able to reproduce and fix these issues.

Once you have a working build, we would happily accept your fixes into our main repository, but we won't be able to provide support for you with this build.

**Comment by bzq2810** [comment]
From [this repository](https://github.com/hillhao/PYNQ-project) I found the following:

> The commands for installing TensorFlow in PYNQ board as follows:
> 
```
> # For Python 3.4
> wget https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/download/v1.1.0/tensorflow-1.1.0-cp34-cp34m-linux_armv7l.whl
> sudo pip3 install tensorflow-1.1.0-cp34-cp34m-linux_armv7l.whl
```

**Comment by shiniyou** [comment]
i try that command but not work on my pynq :(

**Comment by Quzard** [comment]
i try that command but not work on my pynq z2:(

 The directory '/home/xilinx/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/xilinx/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement 'tensorflow-1.1.0-cp34-cp34m-linux_armv7l.whl' looks like a filename, but the file does not exist

tensorflow-1.1.0-cp34-cp34m-linux_armv7l.whl is not a supported wheel on this platform.rm.

**Comment by JupyterLabs** [comment]
wget https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/download/v0.9.0/tensorflow-0.9.0-py3-none-any.whl 

/usr/bin/python3 -m pip install tensorflow-0.9.0-py3-none-any.whl

**Comment by hkhantang** [comment]
the latest tensorflow version in github is 0.11.0, but the tensorflow version older than 1.9.0 has the drawback: tf.session.close() can't release the memory of the gpu card，so the memory can exhaust, 
the version newer than or equal to 1.9.0 solves the problem;
so we need a tensorflow version newer than or equal to 1.9.0 that can run on pynq;
If there is a detailed introduction about how to cross-compile tensorflow running on pynq or Raspberry?

> wget https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/download/v0.9.0/tensorflow-0.9.0-py3-none-any.whl
> 
> /usr/bin/python3 -m pip install tensorflow-0.9.0-py3-none-any.whl

**Comment by alaauddin** [comment]
for a pynq - z1, it has armv71 which is 32 bits architecture, therefore if we install python with later version it e.g. 3.9 then you will not find a Tensorflow version which run in 32 bits latest version.

a solution can be by installing version 3.7 of python which has Tensorflow that can run in 32 bits system.

even though I tried this way but I am facing a problem in h5py, kindly help if you know a solution.
the error is failed to build a wheel for h5py

**Comment by akasharji** [comment]
I tried installing tensorflow in python -3.4,3.5,3.7 versions but it is not installing on PYNQ Z1 board
