### ISSUE TITLE
image_ops_test failing due to math_ops.sin() behaving differently

### ISSUE THREAD

**Issue by namrata-ibm** [tensorflow/tensorflow#14017]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: v1.2.1
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.4.5 
- **CUDA/cuDNN version**: No GPU
- **GPU model and memory**: No GPU
- **Exact command to reproduce**: bazel test -c opt //tensorflow/contrib/image:image_ops_test

### Describe the problem
The above test fails with the output array mismatch in [test_rotate_even](https://github.com/tensorflow/tensorflow/blob/v1.2.1/tensorflow/contrib/image/python/kernel_tests/image_ops_test.py#L48).

The exact cause of failure seems to be at [math_ops.sin(angles)](https://github.com/tensorflow/tensorflow/blob/v1.2.1/tensorflow/contrib/image/python/ops/image_ops.py#L115), which only fails for `angle=(np.pi / 4.0) = 0.78539819` (45 deg) and works fine for 0 and 90 deg.

The output of `math_ops.sin(0.78539819).eval()` differs on Intel and s390x as below:
1. Intel(test passes) : 0.70710**6769**
2.  s390x(test fails) : 0.70710**6829**

I verified `np.sin(0.78539819)` gives same output `0.7071067999` on both Intel and s390x.

Why is the difference seen in math_ops.sin()? Any pointers would be helpful.

### Source logs
----------------------------------------------------------------------
FAIL: test_rotate_even (__main__.ImageOpsTest)
----------------------------------------------------------------------
```
Traceback (most recent call last):
  File "/home/test/.cache/bazel/_bazel_test/24685d064c07f7346b48c2d13ec3ad69/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/image/image_ops_test.runfiles/org_tensorflow/tensorflow/contrib/image/python/kernel_tests/image_ops_test.py", line 75, in test_rotate_even
    [1, 7, 13, 19, 25, 31], [0, 6, 12, 18, 24, 30]]])
  File "/home/test/.cache/bazel/_bazel_test/24685d064c07f7346b48c2d13ec3ad69/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/image/image_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 699, in assertAllEqual
    np.testing.assert_array_equal(a, b)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 807, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 1.85185185185%)
 x: array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],...
 y: array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],...

not equal where =  (array([1, 1]), array([3, 4]), array([3, 4]))
not equal lhs =  [20 32]
not equal rhs =  [21 33]

```

**Comment by michaelisard** [comment]
I'm afraid we don't have the resources to support all platforms, and we don't have support for s390x. Tagging community support.

**Comment by namrata-ibm** [comment]
@mrry, any thoughts on the issue? 
Where can I refer the implementation for math_ops.sin/cos functions?

**Comment by mrry** [comment]
The implementations of these ops are thin wrappers around Eigen:

https://github.com/tensorflow/tensorflow/blob/0623993f08c5357302bf64a50a52120da323ed25/tensorflow/core/kernels/cwise_ops.h#L576-L592

**Comment by shahidhs-ibm** [comment]
After debugging more into issue which @namrata-ibm had found out, it turned out an issue with NumPy (similar to [12963](https://github.com/tensorflow/tensorflow/pull/12963)).

On Intel:
```
>>> np.sin(np.array([0.0, np.pi / 4.0, np.pi / 2.0], dtype=np.float32))
array([ 0.        ,  0.70710677,  1.        ], dtype=float32)
```
On zSystems:
```
>>> np.sin(np.array([0.0, np.pi / 4.0, np.pi / 2.0], dtype=np.float32))
array([ 0.        ,  0.70710683,  1.        ], dtype=float32)
```


If we do not specify the data type to the array, NumPy is giving same results on both the platforms.
On Intel:
```
>>> np.sin(np.array([0.0, np.pi / 4.0, np.pi / 2.0]))
array([ 0.        ,  0.70710678,  1.        ])
```

On zSystems:
```
>>> np.sin(np.array([0.0, np.pi / 4.0, np.pi / 2.0]))
array([ 0.        ,  0.70710678,  1.        ])
```

@mrry Please share your thoughts on this.

**Comment by mrry** [comment]
I assume it’s some difference between in the rounding behavior for `np.float32` and `np.float64` on zSystems. Not my area of experience, alas…

**Comment by shahidhs-ibm** [comment]
@mrry As you said correctly this is some rounding behavior difference on zSystems. Could you please share  why Tensorflow uses int32 and float32 over python/numpy's default int64 and float64? Will it be a major change if we go for 64 bit variant? Asking just out of curiosity :)

**Comment by mrry** [comment]
I don't think we can change that behavior without breaking backwards compatibility. I tracked down the original commit that added [this behavior](https://github.com/tensorflow/tensorflow/blame/4cdc52964ae24f2c2b863939b4dc9cbe9cd9d104/tensorflow/python/framework/tensor_util.py#L424), by @zffchen78. There's no documentation of the rationale, but perhaps ZF can comment.

(I suspect the reason is something like "Nobody wanted to use double precision to train their networks when we started, and choosing this default avoids the need for lots of explicit `tf.float32` casts." The trend towards lower-precision training seems to back this up.)

**Comment by zffchen78** [comment]
TensorFlow was largely motivated by our previous gen DL framework and applications at that time. Then, double was frowned upon by DL community for its slowness and the extra precision was not needed by those models. int64 & float64 on GPUs were also very slow and virtually nobody cared. So, int32 & float32 were more defacto data types.

**Comment by namrata-ibm** [comment]
Closing this as per discussion in #13638.
