### ISSUE TITLE
Raspberry example DecodeJpeg issue with Inception Retraining model 

### ISSUE THREAD

**Issue by turkeyB** [tensorflow/tensorflow#14026]
# **Environment info**

Operating System: raspbian

# **Steps to reproduce**

-   1.Follow the contrib/makefile/README to install the tensorflow raspbian core lib
-   2.Run the pi example, both successfully
-   3.Create inception model generally with the Tensorflow For Poets in Ubuntu 16.04 
-   4.Retrain the model and get 'retrained_graph.pb' and 'retrained_labels.txt'
-   5.Run the pi example with those two files by 

`tensorflow/contrib/pi_examples/label_image/gen/bin/label_image --image=xxx.jpg --graph=retrained_graph.pb --labels=retrained_labels.txt `
and get error log 
`Invalid argument: No OpKernel was registered to support Op 'DecodeJpeg' with these attrs. registered device:[CPU],registered kernels: <no registered kernels> 
[[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false](DecodeJpeg/contents)]]`

# **related**
#2883 And I have also read your blog ‘tensorflow for mobile poets’ ... Is raspberry pi a mobile device? cuz when I run the command `tensorflow/python/tools:optimize_for_inference ` in the file made by contrib/makefile/README , it suggested that no such file or dictionery..

**Any comment on what I do wrong.
many thanks**

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
