### ISSUE TITLE
tf.train.MonitoredTrainingSession does not have request_stop() method

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#14028]
```
with tf.train.MonitoredTrainingSession(checkpoint_dir="/tmp/train_logs",
                                       config=config,
                                       hooks=hooks) as mon_sess:
  while not mon_sess.should_stop():
    # Perform synchronous training.
    mon_sess.run(train_op)
```
I can not use mon_ses.request_stop().

**Comment by skye** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
