### ISSUE TITLE
Feature Request (API Design review) tf.get_shape(), tf.get_size(), tf.Tensor.size, tf.Tensor.get_size(), etc

### ISSUE THREAD

**Issue by ozabluda** [tensorflow/tensorflow#14047]
Below, everything with `get` in the name refers to dynamic (symbolic), everything without to static (integer).

1. Introduce `tf.get_shape(x)`. Then `tf.get_shape(x) <=> tf.shape(x)` will be analogous to existing `tf.Tensor.get_shape() <=> tf.Tensor.shape`
2. Introduce `tf.set_shape(x)`, matching `tf.get_shape(x)`
3. Introduce `tf.get_size(x)`. Then  `tf.get_size(x) <=> tf.size(x)`  will be analogous to `tf.get_shape(x) <=> tf.shape(x)`
4. Ditto for `tf.get_shape_n(x)`, see `tf.shape_n(x)`.
5. Introduce `tf.Tensor.size` for compatibility with `np.ndarray.size`. `tf.size(x) <=> x.size` will be analogous to `tf.shape(x) <=> x.shape`
6. Ditto for `tf.Tensor.get_size()`
7. Should there also be `tf.size_n(x)` and `tf.get_size_n(x)`?

**Comment by asimshankar** [comment]
Thanks very much for the suggestion.

Currently, I believe all the `tf.*` methods (like `tf.shape`, `tf.size` etc.) return symbolic tensors (unless [eager execution](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/README.md) is enabled), while the methods on the `tf.Tensor` object return values (well `TensorShape` objects for `tf.Tensor.shape`).

IMHO, having some `tf.*` methods return symbolic tensors and others return concrete values may be confusing, especially with the various aliases.

**Comment by ozabluda** [comment]
This is a good argument against introducing those methods into `tf.*`, but arguments for it are 

1.  `tf.*` methods have different signatures than eponymous `tf.Tensor.*` methods (like `dtype` parameters)
2. `tf.*` static methods could accept numpy arrays, python lists, etc

what about items 5 and 6?

**Comment by reedwm** [comment]
@martinwicke what do you think of this proposal?

**Comment by martinwicke** [comment]
We did not implement `x.size == tf.size(x)` because it would be similar to numpy. `tf.size(x)` returns a `Tensor`, while `ndarray.size` is an `int`. Almost no code that relies on the numpy behavior would work with `Tensor`s, so I'd rather not give the impression it would.

Even in Eager mode, the things returned from tf.shape will be TensorShape objects, not lists of integers. While these are mostly equivalent, we have seen problematic incompatibilies.

So we'd rather not add this.
