### ISSUE TITLE
Feature request: Exporting TensorBoard graphs to vector graphics formats

### ISSUE THREAD

**Issue by rasbt** [tensorflow/tensorflow#14049]
As recently discussed on the TensorFlow mailing list (https://groups.google.com/a/tensorflow.org/d/msg/discuss/GUW0KOmN7MM/2lRMD4JVAQAJ), it would be nice if TensorBoard would include an export function that supports exporting the graph in a vector graphics format (e.g., SVG or EPS, or both) in addition to the current PNG export function.

For instance, I recently bumped into a case where I wanted to include the TensorBoard graph as an example output of a tutorial section on TensorBoard in my book and found that the PNG version is "too low-res" and not very helpful so that I had to manually redraw it. Also, I like to include TensorBoard graphs in reports some times after applying some stylistic changes and recently stumbled upon a browser utility called "SVG crowbar" that can get the graph from TensorBoard in SVG format -- with some workarounds. This indicates that it may already be in SVG format, and it would be nice to allow to export it to disk for styling and generating high res figures.

**Comment by asimshankar** [comment]
I believe this is the same request as in the Tensorboard repository: https://github.com/tensorflow/tensorboard/issues/32 - so closing this as a duplicate.

**Comment by rasbt** [comment]
Sure, makes sense! I just realized that I should have searched & submitted this to the tensorboard repo anyways (for some reason, I thought tensorboard was included in the tensorflow main repo)
