### ISSUE TITLE
 Bug when using estimator with tf.data.Dataset.from_tensor_slices

### ISSUE THREAD

**Issue by traveller59** [tensorflow/tensorflow#14053]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 10
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.5.0-dev20171026
- **Python version**: 3.6.3

### Describe the problem
When I use tf.data and from_tensor_slices with estimator to build dataset from ndarray, tf.estimator will use much memory(peak 6900MB, final 4600MB with [simple mnist cnn](https://github.com/aymericdamien/TensorFlow-Examples/blob/master/notebooks/3_NeuralNetworks/convolutional_network.ipynb)) and create very huge event files：
events.out.tfevents 1.28GB
graph.pbtxt: 1.20GB
model.ckpt-1.meta: 370MB
Then I use cifar10 input pipeline from [resnet](https://github.com/tensorflow/models/blob/master/official/resnet/cifar10_main.py) as input_fn, everything back to normal.

### Source code / logs
replace code in [notebook](https://github.com/aymericdamien/TensorFlow-Examples/blob/master/notebooks/3_NeuralNetworks/convolutional_network.ipynb) cell 6 with code below.
```Python
def ndarray_iters(datas,
                batch_size):
    dataset = tf.data.Dataset.from_tensor_slices(tuple(datas))
    batched_dataset = dataset.batch(batch_size)
    iterator = batched_dataset.make_one_shot_iterator()
    next_iters = list(iterator.get_next())
    return next_iters
def train_input_fn():
    imgs, labels = ndarray_iters([mnist.train.images, mnist.train.labels], 128)
    return {'images': imgs}, labels
model.train(train_input_fn, steps=1000)
```

**Comment by asimshankar** [comment]
@jsimsa : Mind taking a look? Thanks.

**Comment by jsimsa** [comment]
@traveller59 the problem is rooted in the fact that `from_tensor_slices` will create a constant-value tensor that has the raw data, which will be recorded in GraphDef.

An alternative approach to achieve the behavior you are hoping for is to use `tf.data.from_generator`:

```
...
def make_generator(images, labels):

  def _generator():
    for image, label in zip(images, labels):
      yield image, label

  return _generator


def train_input_fn():
  mnist = input_data.read_data_sets('/tmp/data/', one_hot=False)
  dataset = tf.data.Dataset.from_generator(
      make_generator(mnist.train.images, mnist.train.labels),
      (tf.float32, tf.float32))
  batched_dataset = dataset.batch(batch_size)
  iterator = batched_dataset.make_one_shot_iterator()
  imgs, labels = list(iterator.get_next())
  return {'images': imgs}, labels
...
```

**Comment by traveller59** [comment]
Thanks, it seems that from_tensor_slices should be deprecated.
