### ISSUE TITLE
Shouldn't tensorboard warn you that not all summaries have loaded yet?

### ISSUE THREAD

**Issue by bernardopires** [tensorflow/tensorflow#1405]
Hi,

since I started using Tensorboard, I noticed some odd behavior that sometimes I'd open it and it seemed like a lot of the summary values were missing, i.e, even though it's already at 10k steps, the summary only shows 2k steps or so. Today I actually finally noticed that it simply meant that it was just still being loaded. I refreshed the page after a minute or so and all data was there. My PC is not bad (i5-2500k) so this was quite surprising. Any reason why the summaries sometimes take so long to load? Also can we get some sort of warning that not all summaries have been completely loaded yet?

**Comment by danmane** [comment]
That would be a really nice enhancement. We're planning to improve all the indications around when TensorBoard is loading, have it automatically refresh data, etc. I don't have a timeline, though.

**Comment by wchargin** [comment]
Hi there—I've just migrated this to our new repository at https://github.com/tensorflow/tensorboard/issues/65. Feel free to submit a PR there!
