### ISSUE TITLE
Feature request: Exporting TensorBoard graphs to graphviz DOT files

### ISSUE THREAD

**Issue by rasbt** [tensorflow/tensorflow#14050]
As recently discussed on the TensorFlow mailing list (https://groups.google.com/a/tensorflow.org/d/msg/discuss/GUW0KOmN7MM/2lRMD4JVAQAJ), it would be nice if TensorBoard would have an option to export a graph as graphviz DOT file. This would allow users and developers to create e.g., Python packages based on pygraphviz that can further modify the graph structure, such as simplifying or summarizing the graph ops into a publication-ready figure, etc.

For example, scikit-learn has such a function to export decision trees to DOT files; maybe the source code is useful as an example: https://github.com/scikit-learn/scikit-learn/blob/f3320a6f/sklearn/tree/export.py#L74

**Comment by diego898** [comment]
Hey @rasbt I've recently been using something simple like this: 

https://blog.jakuba.net/2017/05/30/tensorflow-visualization.html

It makes mention of the following:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/quantization/graph_to_dot.py

What do you think?

**Comment by rasbt** [comment]
That's an awesome post, Diego, thanks for sharing! It's really handy, and I didn't know that it was so easy to export graphs via graphviz's "Digraph" already! Of course, for the feature request, it would be even more convenient to have an "export" function in TensorBoard that does exactly this -- saving the graph as dot file for further manipulation.

Best,
Sebastian

**Comment by jart** [comment]
This is an excellent suggestion and it's something we're already in the process of thinking about. Please follow https://github.com/tensorflow/tensorboard/issues/570. I'm going to close this one out as a duplicate.
