### ISSUE TITLE
bug - when try train object detection in gcloud [ImportError: No module named 'tensorflow.python.eager']

### ISSUE THREAD

**Issue by ragulh26** [tensorflow/tensorflow#14069]
### System information
- **I tried to train the model using tensorflow objdet api**:
- **OS Platform and Distribution Linux Ubuntu 16.04 (gcloud VM)**:
- **TensorFlow installed from python pip**:
- **TensorFlow version 1.3.0**:
- **Python version 2.7**: 
- **Bazel version (if compiling from source)**:
- **CUDA 8.0 /cuDNN 6.0**:
- **The typical installation steps followed**:

### Describe the problem
when i trying to train the Mobilenet model the following error came up. I already trained using the same steps in my local PC without any errors. I couldn't find any solution related to this error.    

### Source code / logs
ragulh28@ubuntu1gpu:~/project/models/research/object_detection$ python train.py --logtostderr --train_dir=training/
 --pipeline_config_path=ssd_mobilenet_v1_lap.config
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from object_detection import trainer
  File "/home/ragulh28/project/models/research/object_detection/trainer.py", line 33, in <module>
    from deployment import model_deploy
  File "/home/ragulh28/project/models/research/slim/deployment/model_deploy.py", line 106, in <module>
    from tensorflow.python.eager import context
ImportError: No module named eager

**Comment by caisq** [comment]
@ragulh26 Can you update your tensorflow to the latest nightly version?
```
pip install --upgrade --force-reinstall tf-nightly
```
or
```
pip install --upgrade --force-reinstall tf-nightly-gpu
```

**Comment by hbfreedow** [comment]
I had the same problem

**Comment by caisq** [comment]
cc @derekjchow @martinwicke @gunan  for possible insight.

Looks like gcloud is using an old version of tensorflow, but is instructing users to run the model from a new version of the source code?

**Comment by martinwicke** [comment]
The error is in slim/model_deploy, so that must be new code. Is eager properly exposed in nightly?

**Comment by caisq** [comment]
@martinwicke Yes, eager is in nightly. How is tf installed on gcloud? I'm not familiar with that part.

**Comment by martinwicke** [comment]
If 1.3 is installed there it will simply not work.

**Comment by asimshankar** [comment]
It seems that this breakage was introduced in https://github.com/tensorflow/models/commit/cbb624791068590026f50f01d370d9328fe8ebf2 which made the `slim` code depend on the master branch of TensorFlow instead of the release version

@sguada : Is `models/research/slim` meant to depend on building TensorFlow from the HEAD of master branch? Or should the change mentioned above be rolled back to keep it compatible with the least official release (1.3.0)

**Comment by ragulh26** [comment]
After i installed tf-nightly-gpu version the [ImportError: No module named eager] is gone and new error [object_detection.protos.TFRecord InputReader" has no field named "data".] is popped up.

I don't know whether or not its related to this problem; Should i posted here or start a new thread?

**Comment by ragulh26** [comment]
After installing the tf-nightly version the problem got resolved. Thanks for the help.

**Comment by chensteven** [comment]
any status to this? I also have the same problem but installing tf-nightly did not fix the error.

**Comment by gunan** [comment]
@chensteven please see the latest comment by @ragulh26

**Comment by bhvyaismeduh21** [comment]
> @ragulh26 Can you update your tensorflow to the latest nightly version?
> 
> ```
> pip install --upgrade --force-reinstall tf-nightly
> ```
> 
> or
> 
> ```
> pip install --upgrade --force-reinstall tf-nightly-gpu
> ```

It tells me that 
`ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)
ERROR: No matching distribution found for tf-nightly
`
