### ISSUE TITLE
tf.train.MonitoredTrainingSession does not have request_stop() method

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#14071]
When i use tf.train.MonitoredTrainingSession class like below, I cannot use sess.request_stop() to stop the sess, because MonitoredTrainingSession does not have this method.

tensorflow version is 1.3

```
with tf.train.MonitoredTrainingSession(checkpoint_dir="/tmp/train_logs",
                                       config=config,
                                       hooks=hooks) as sess:
  while not mon_sess.should_stop():
      sess.run(train_op)
      sess.request_stop()
```

**Comment by asimshankar** [comment]
I'm sorry, I don't quite follow the issue here. Yes, `request_stop` is not a method on the `Session` or `MonitoredSession` classes. Perhaps you could add more detail on what you're trying to do.

**Comment by zh794390558** [comment]
I want to early stop the iteration over epoch, which maybe very time consume. So I have to use sess.request_stop() to stop the while loop like other Session, otherwise i have use `break` to stop the while loop.

**Comment by asimshankar** [comment]
I'm not quite following what you're referring to. Neither `Session` nor `MonitoredSession` have a `request_stop()` method, so I'm not sure what you mean by "like other Session".

**Comment by zh794390558** [comment]
@asimshankar Sorry, I mean coord has a request_stop() method , and coord is in MonitoredSession, so i think this method may exists. Now I think tf.train.StopAtStepHook  this maybe what I want.

**Comment by mattdornfeld** [comment]
@asimshankar I think the question is how do you manually stop a MonitoredTrainingSession? There should be a way to do this.

**Comment by jimmieliu** [comment]
Is there a way to manually stop a MonitoredTrainingSession? I have encountered an issue: my chief worker stops at an exception while non-chief workers keeps running
