### ISSUE TITLE
C++ documentation broken

### ISSUE THREAD

**Issue by ma2rten** [tensorflow/tensorflow#1407]
None of the links on this page work:

https://www.tensorflow.org/versions/r0.7/api_docs/cc/index.html

**Comment by girving** [comment]
@danmane: Do you know what the issue is here?

**Comment by IlseVerdiesen** [comment]
You are using a lower case after the final / , but that should be an upper case.

The link is: https://www.tensorflow.org/versions/r0.7/api_docs/cc/classEnv.html

But it should be: https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassEnv.html

**Comment by IlseVerdiesen** [comment]
It applies to all the links on the page. These are the correct ones:

tensorflow::Env
https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassEnv.html 

tensorflow::RandomAccessFile 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassRandomAccessFile.html 

tensorflow::WritableFile 
https://github.com/delftswa2016/tensorflow/blob/master/tensorflow/g3doc/api_docs/cc/ClassWritableFile.md 

tensorflow::EnvWrapper 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassEnvWrapper.html

tensorflow::Session 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassSession.html

tensorflow::SessionOptions 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/StructSessionOptions.html 

tensorflow::Status 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassStatus.html 

tensorflow::Status::State 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/StructState.html

tensorflow::Tensor 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassTensor.html

tensorflow::TensorShape 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassTensorShape.html 

tensorflow::TensorShapeDim 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/StructTensorShapeDim.html 

tensorflow::TensorShapeUtils 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassTensorShapeUtils.html 

tensorflow::PartialTensorShape 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassPartialTensorShape.html 

tensorflow::PartialTensorShapeUtils 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassPartialTensorShapeUtils.html 

TF_Buffer 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/structTF_Buffer.html

tensorflow::Thread 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassThread.html

tensorflow::ThreadOptions 
https://www.tensorflow.org/versions/r0.7/api_docs/cc/StructThreadOptions.html
