### ISSUE TITLE
How to get difference or square between two tensor？

### ISSUE THREAD

**Issue by shichengcn** [tensorflow/tensorflow#14079]
I define two subnets that output the tensor of the same dimension use functional model. I want get difference between them. for example：tensor1 [1,2,3,4,5], tensor2 [1,1,1,1,1], output=tensor1 -tensor2 =
Can you tell me how to get difference between two tensor，or square of one tensor？
Thank you very much.

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
