### ISSUE TITLE
Feature request: support convert python object to tensor automatical, and can back to object in py_func or other mechod.

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#14072]
I want to use python object as tensor in Tensorflow and can convert it back to object when useing tf.py_func method,  to  support using other python package.

**Comment by jart** [comment]
Have you considered [pickling](https://docs.python.org/2/library/pickle.html)? It should be possible to do this today. I am of course curious to learn more about how tf.py_func has been beneficial to your use case. I will also note that it is a feature that ought to be used judiciously. I'm going to close this one out, but if my suggestion doesn't offer solutions, let me know and I'll re-open.

**Comment by zh794390558** [comment]
@jart Now I use cPickle to do this, I want to embed FST in to tensorflow for beam search decoding.
