### ISSUE TITLE
Tensorflow hooks do not properly write events to HDFS

### ISSUE THREAD

**Issue by wochinge** [tensorflow/tensorflow#14084]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Alpine Linux 3.6.2 (running with Docker)
- **TensorFlow installed from (source or binary)**: Binary (conda-forge)
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**: - 
- **CUDA/cuDNN version**: -
- **GPU model and memory**: using CPU
- **Exact command to reproduce**: `CLASSPATH=$(${HADOOP_HOME}/bin/hadoop classpath --glob) jupyter notebook`

### Describe the problem
I am reading files from hdfs and also want to use hdfs as `model_dir` to store the tensorflow output. Reading and writing of the checkpoints works fine. However, the the events file just gets created, but it does not get updated with the evaluation events. 

When I kill the notebook then the output is written, but not in between. Changing the model directory to a local one solves this. Also adding an extra `SummarySaverHook` which points to a local directory did not help.

I am running my code using the instructions here: <https://www.tensorflow.org/deploy/hadoop>

### Source code / logs
I normally use an Estimator with a custom model function, but I reduced it to the following:

```python
import tensorflow as tf
import numpy

hdfs_namenode = 'hdfs://xx.xx.xx.xx:8020'
files = ['{}/data/part-00000-2a4cdbb2-f152-4503-9da8-cba63c7648fc-c000.csv'.format(hdfs_namenode)]

output_directory = '{}/tresults/'.format(hdfs_namenode)

feature_columns = [tf.feature_column.numeric_column("x", shape=[70])]

def input_function_training:
  ...
def input_function_evaluation:
  ...

def experiment_fn(run_config, hparams):
    estimator = tf.estimator.DNNClassifier(hidden_units=[4], 
        feature_columns=feature_columns,
        model_dir=output_directory, 
        n_classes=2,
        config=run_config)
    
    return tf.contrib.learn.Experiment(estimator=estimator, 
        train_input_fn=input_function_training, 
        eval_input_fn=input_function_evaluation)

tf.contrib.learn.learn_runner.run(experiment_fn,
    run_config=tf.contrib.learn.RunConfig(model_dir=output_directory,
        save_checkpoints_steps=10,
        save_checkpoints_secs=None,
        save_summary_steps=1))
```

The logs do not show any problems:

```
WARNING:tensorflow:RunConfig.uid (from tensorflow.contrib.learn.python.learn.estimators.run_config) is experimental and may change or be removed at any time, and without warning.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fb30e032780>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 1, '_save_checkpoints_secs': None, '_log_step_count_steps': 100, '_session_config': None, '_save_checkpoints_steps': 10, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': 'hdfs://xx.xx.xx.xx:8020/tresults/'}
WARNING:tensorflow:RunConfig.uid (from tensorflow.contrib.learn.python.learn.estimators.run_config) is experimental and may change or be removed at any time, and without warning.
WARNING:tensorflow:From /opt/conda/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:269: BaseMonitor.__init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into hdfs://xx.xx.xx.xx:8020/tresults/model.ckpt.
WARNING:tensorflow:Casting <dtype: 'float32'> labels to bool.
WARNING:tensorflow:Casting <dtype: 'float32'> labels to bool.
INFO:tensorflow:Starting evaluation at 2017-10-30-05:41:22
INFO:tensorflow:Restoring parameters fromhdfs://xx.xx.xx.xx:8020/tresults/model.ckpt-1
INFO:tensorflow:Evaluation [1/100]
...
INFO:tensorflow:Evaluation [100/100]
INFO:tensorflow:Finished evaluation at 2017-10-30-05:42:24
INFO:tensorflow:Saving dict for global step 1: accuracy = 0.46836, accuracy_baseline = 0.75205, auc = 0.697368, auc_precision_recall = 0.591545, average_loss = 0.692944, global_step = 1, label/mean = 0.24795, loss = 692.944, prediction/mean = 0.524391
INFO:tensorflow:Validation (step 1): accuracy = 0.46836, accuracy_baseline = 0.75205, auc = 0.697368, auc_precision_recall = 0.591545, average_loss = 0.692944, label/mean = 0.24795, loss = 692.944, prediction/mean = 0.524391, global_step = 1
INFO:tensorflow:loss = 42.1861, step = 1
INFO:tensorflow:Saving checkpoints for 11 into hdfs://xx.xx.xx.xx:8020/tresults/model.ckpt.
```

**Comment by jart** [comment]
@jhseu Would you be able to help out with the HDFS issue?

**Comment by wochinge** [comment]
I kind of fixed the error. My guess is that Hadoop only shows the initial file size as long as content is only appended to the event file and shows the "real" file size only when the training is stopped (ended or aborted). My problem further might have been related to the fact, that I have got Tensorflow running in a Docker container which was stopped immediately after Tensorflow was finished. I added some sleep at the end of my Python code, so that potential background operations have time to finish.

**Comment by jart** [comment]
Thank you for sharing that information for people who google this issue in the future. Sleep sounds like it would do the trick. If you end up discovering a way to do it without sleep in the future, please let us know. We're always interested in hearing about these things.

**Comment by kelly-tlz** [comment]
After reading this, how can I write tf events to hdfs?

**Comment by wochinge** [comment]
@kelly-tlz Just do it as described in https://www.tensorflow.org/deploy/hadoop. After the last evaluation is finished, wait a bit (should not be longer than 30min), then you should see the results on hdfs.

**Comment by kelly-tlz** [comment]
@wochinge can you share code of writing events to hdfs? Since I haven't use this, and I want to save my checkpoint file and events logs into hdfs directly. Now my code is like this:
`hdfs_path="hdfs://*"
local_path = "./"
with tf.Session(graph=tf.get_default_graph()) as sess:
    W = tf.Variable([[1,2,3],[3,4,5]], dtype=tf.float32, name='weights')
    b = tf.Variable([[1,2,3]], dtype=tf.float32, name='biases')
    inti_op = tf.group(tf.global_variables_initializer(),
                       tf.local_variables_initializer())  # local including FLAGS data
    saver = tf.train.Saver()
    sess.run(inti_op)
    summary_writer = tf.summary.FileWriter(local_path, graph_def=sess.graph_def)
    saver.save(sess, save_path=local_path+"save_net.ckpt")
`

**Comment by wochinge** [comment]
I am using `tf.estimator` (model_dir points to hadoop), but I think you simply need to set the directory of your `FileWriter` to a hdfs path, e.g.

```python
tf.summary.FileWriter('hdfs://namenode:8020/any_directory', graph_def=sess.graph_def)
```

Just be sure to follow all the stops from the documentation. Some hadoop names also may be reachable through port 9000.

**Comment by kelly-tlz** [comment]
this does not help when my version is 1.0, when I change the local_path to hdfs_path, it raise problem that "parent directory is not exists", the question I ask in https://stackoverflow.com/questions/47456415/file-test-hdfs-py-save-path-saver-savesess-hdfs-pathsave-net-ckpt-pa

**Comment by wochinge** [comment]
Did you properly format your hdfs url?
Since `hdfs_path+"save_net.ckpt` would give `"hdfs://*save_net.ckpt" `, which is wrong? I cannot comment on Stackoverflow since I have to less reputation there.

**Comment by kelly-tlz** [comment]
Maybe your version(mine is tf1.0) or environment of hadoop is different from me, I'm sure the hdfs path is exist and I can use subpreprocess.Popen to write and read hdfs file through python code.

**Comment by jimdowling** [comment]
We have this problem as well. The problem is most acute when using the Estimator APIs, where we don't have an explicit handle on the hdfs writer object. The problem is that hdfs only updates the file size written either at the end of block being fully written or when an explicit hflush is called on the file. When the file sizes are much smaller than the block size and they aren't closed, they just appear to hang - not available for reading.

**Comment by wochinge** [comment]
Hey,
so for me there a to options, which work:
- Just quit your TensorFlow services and wait for 1 to 2 hours. The files should then appear on HDFS
- you can use `hdfs debug recoverLease` on the files, which are not fully written yet (<https://hadoop.apache.org/docs/r2.7.1/hadoop-project-dist/hadoop-hdfs/HDFSCommands.html#recoverLease>)
