### ISSUE TITLE
Generalized matrix multiplication with semiring?

### ISSUE THREAD

**Issue by markusdr** [tensorflow/tensorflow#1408]
Would it be possible to support (generalized) matrix multiplication with non-standard semirings? 

In matrix multiplication, we have `A times B = C`, where `C(i,j) = sum_k A(i,k) times B(k,j)`

Using a different semiring practically means redefining the `plus` and `times` operations. 

For example, the log semiring assumes that all numbers in the matrices are log numbers and redefines `plus` as `logplus` (aka [logaddexp](http://docs.scipy.org/doc/numpy/reference/generated/numpy.logaddexp.html#numpy.logaddexp) or [logsumexp](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.misc.logsumexp.html)) and `times` as `plus`. This is useful for computing the log denominator in log-linear models, e.g., `log Z = log sum_y exp(f1(y)) times exp(f2(y))`.

The [max-plus semiring](https://en.wikipedia.org/wiki/Max-plus_algebra) (aka Viterbi or tropical semiring) redefines `plus` as `max` and `times` as `plus`. This is useful for finding the best path (assuming all matrix entries are log numbers).

**Comment by girving** [comment]
I think an optimized (blocked, etc.) implementation of semiring matmul is out of scope for tensorflow at the moment, since it would require either code generation or a massive amount of template instantiation.  Of course, for small sizes it can be implemented by writing down all the terms via broadcasting (producing a cubic size tensor) and then reducing, but that's not very interesting.

It's possible that TensorFlow may be better at this kind of flexibility at some point, so I'll leave this bug open.

**Comment by markusdr** [comment]
Templating `matmult` on a semiring (similar to OpenFst) might be too big of a change. But maybe one could just add a few new matrix multiplication functions for particular popular semirings, e.g., `matmult_log`, `matmult_maxplus`, etc.

**Comment by girving** [comment]
If a couple particular semirings capture most of the value, this seems quite reasonable.  @benoitsteiner: Can Eigen be convinced to give optimized semiring matrix multiply?

**Comment by yaroslavvb** [comment]
Computing log Z can be rewritten in terms of regular matrix multiplies, but Viterbi is an interesting example. You need efficient way to do compute matrix vector min-plus product r=Av as  r(i) = min_j A(i,j) v(j)

**Comment by markusdr** [comment]
@yaroslavvb Yes, rewriting the computation of log Z in terms of regular matrix multiplies is possible by explicitly exponentiating all entries in the matrices, but that can be expensive and also prone to underflow problems.

**Comment by girving** [comment]
Closing since I think this is out of reach of easy contributions.  A trivial implementation is trivial, but users are likely to want fast versions that are hard to write.
