### ISSUE TITLE
how can i get a specific version of tf

### ISSUE THREAD

**Issue by turkeyB** [tensorflow/tensorflow#14097]
## platform
raspbian 8.0

## problem
I need this specific release of tensorflow... and does anyone have the repository of that version?
it needs to be a source file.. because of some specific situation and some difficulties that hard to solve, I have to compile it from source and get a consequence similar to `git clone --recurse-submodules https://github.com/tensorflow/tensorflow.git` but in the version of 1.1.0

**related:**
https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md
after bazel build in this guidance, the contributor gave the command like this:
`sudo pip install /tmp/tensorflow_pkg/tensorflow-1.1.0-cp27-none-linux_armv7l.whl `
I don't know whether this command will have some influence.. but an release can adapt to this command will be ideal...

many thx!

**Comment by asimshankar** [comment]
You can switch to the release branch of the appropriate version. The release branches are named `r<version_number>`, see all branches at https://github.com/tensorflow/tensorflow/branches/all

For example:

```sh
git checkout r1.2
```

will take you to the version 1.2 branch.

**Comment by turkeyB** [comment]
thx !
