### ISSUE TITLE
There is a Error about: Too many include files

### ISSUE THREAD

**Issue by Rulen9987** [tensorflow/tensorflow#14092]
when i try to built example/label_image/main.cc . Visual studio will throw an error :c1014 too many include files . Click the message , this error point to a file of Tensor.  can anybody tell me how to fix this problem.thank you.
This is my first time to write English litter , and i am not good at english , wish you can understood what i said . lol

**Comment by jart** [comment]
I'd be interested in learning more about this. Please fill out the issue template. Also how exactly is Visual Studio happening? Are you importing all the code into the IDE? Running CMake? Running Makefile? Running Bazel? What version of Visual Studio? I must admit I haven't used it since 6.0 but when I did it was awesome.

**Comment by Rulen9987** [comment]
thanks for your reply ,

1.  i used visual studio 2015 to run the exampale
2.  i only add main.cc file into a new project as a soruce file 
3.   in the Option dialog , fill the head file Directory into the "VC++ Directories"
     E:\TensorFlow\tensorflow-master
     E:\TensorFlow\tensorflow-master\tensorflow
     E:\TensorFlow\tensorflow-master\third_party\eigen3
     E:\TensorFlow\tensorflow-master\tensorflow\core\framework

**Comment by Rulen9987** [comment]
Last night, i download the Negin3 soruce code form internet . replace  local Tensorflow\eigen3 file , then Error was dispeared , but still has a problem that i can not found .ph.h files . How can i get those ?

**Comment by jart** [comment]
I wish I could help but this question is probably better for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). There's a larger community there that provides support. This issue tracker is more for bugs and feature requests and very few members of the team has VS experience.

**Comment by Rulen9987** [comment]
OK,thanks for your suggestion .
