### ISSUE TITLE
tf.reshape() fails for shapes containing non-32 bit precision TF integer types

### ISSUE THREAD

**Issue by j-wilson** [tensorflow/tensorflow#14105]
**Environment**: TensorFlow v1.3.0-rc2-20-g0787eee 1.3.0 running on Mac OS X (v10.12.6)

**Issue**:
Function `tensorflow.reshape()` works when provided a list-based shape containing `tf.int32`; but, fails for, e.g., `tf.int16` and `tf.int64` with error message `TypeError: List of Tensors when single Tensor expected`.

**Example**:
```
import tensorflow as tf
src = tf.constant(list(range(32)))
for dtype in ['int32', 'int64', 'int16']:
	print("Calling tf.reshape using 'tf.{:s}'".format(dtype))
	tf.reshape(src, [tf.cast(16, dtype), 2])
```

**Comment by facaiy** [comment]
The behavior is expected, see API: [tf.reshape](https://www.tensorflow.org/versions/master/api_docs/python/tf/reshape)
> shape: A Tensor. Must be one of the following types: int32, int64. Defines the shape of the output tensor.

**Comment by j-wilson** [comment]
Not sure I fully understand. The API seems to suggest that it should work for both `int32` and `int64`. In the example provided above, the first iteration (using `int32`) succeeds but the remaining do not.

**Comment by facaiy** [comment]
Yes, you're right. The `shape` must be either int32 or int64, unfortunately, mixing them is not permitted. To be honest, it is not convenient. Perhaps you can open a feature request:-)

**Comment by facaiy** [comment]
By the way, cast `shape` to valid type might be useful for you.

```python
In [9]: tf.reshape(src, tf.cast([tf.cast(16, tf.int64), 2], dtype=tf.int64))
Out[9]: <tf.Tensor 'Reshape_1:0' shape=(16, 2) dtype=int32>
```

**Comment by j-wilson** [comment]
Thanks for helping to clarify this issue. Using what you've mentioned, the following work for both `int32` and `int64`: `tf.reshape(x, tf.cast([16, 2], dtype))`. This usage pattern suffices for my purposes; however, I would like to point out the following nuance (which still seems like a bug).

Of the following, the former works but the latter does not: 
```
tf.reshape(x, [tf.cast(16, 'float32'), tf.cast(2, 'float32')]) #works
tf.reshape(x, [tf.cast(16, 'float64'), tf.cast(2, 'float64')]) #fails
```
Presumably, support was added somewhere along the lines to allow for the first convention; otherwise, it should throw the same exception as the latter --- namely: `TypeError: List of Tensors when single Tensor expected`

**Comment by facaiy** [comment]
It's not perfect, I agree with you, @j-wilson .
However, note that `tf.cast([16, 2], dtype)` is a tensor, while `[tf.cast(16, 'int64'), tf.cast(2, 'int64')]` is a list of tensors. In fact, `tf.shape` expects a tensor for `shape`.

**Comment by jart** [comment]
Thank you for helping our friend @facaiy. The Python API makes a *best effort* to do type coercion, to make TensorFlow easier. It's highly nontrivial code and I'm not sure if collections with these sorts of mixed types was considered. While I'm sure it's something we'd like to support, I'm not sure if there would be performance ramifications to recursive type coercion. Therefore it might not be a feature we'd consider.

Also, one thing you might want to consider is to express these operations as TensorFlow operations, which could be verbose, but might help ensure that graph is fully defined and there isn't any performance bottlenecking magic that's happening.
