### ISSUE TITLE
How to print shape of tensors in tf.contrib.learn.Estimator

### ISSUE THREAD

**Issue by mudong0419** [tensorflow/tensorflow#14118]
tf.contrib.learn.Estimator and tf.contrib.learn.Experiment  are very convenience to build a model. But how to debug the user defined model? For example, in the [Abalone Age Predictor example,](https://www.tensorflow.org/extend/estimators) how to print shape of 'first_hidden_layer', 'second_hidden_layer' and 'predictions' in user defined 'model_fn' function? 

 It is easy to print  shape of tensors if we build a model with session, and an example is as follows:
`a = tf.Variable(tf.zeros(shape=(2, 3, 4)))
with tf.Session() as sess:
    print sess.run(tf.shape(a))`

By the way, I also tried to debug  [Abalone Age Predictor example,](https://www.tensorflow.org/extend/estimators) with tf.python.debug.LocalCLIDebugHook, but 'first_hidden_layer', 'second_hidden_layer' and 'predictions' are not in debug window.

Many thanks in advance.

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
