### ISSUE TITLE
[iOS] No OpKernel was registered to support Op 'Prod' with these attrs

### ISSUE THREAD

**Issue by tamias65** [tensorflow/tensorflow#14112]
I'm trying to load the faster_rcnn_resnet101_coco model from the [Tensorflow Object Detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) onto the iOS camera example.  Currently, I'm running in to the issue with 
```
No OpKernel was registered to support Op 'Prod' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>
```

The environment is as follows:

- python 3.6
- xcode 9.0.1
- mac os 10.12
- tensorflow built from source using r1.4
- bazel 0.5.4

I have done things as follow:

1. Following the iOS static library build [instructions](https://github.com/tensorflow/tensorflow/tree/r1.4/tensorflow/contrib/makefile),

2. Successfully ran 

`tensorflow/contrib/makefile/download_dependencies.sh
`
3. Successfully ran 

`tensorflow/contrib/makefile/compile_ios_protobuf.sh`

4. Successfully ran 

```
export HOST_NSYNC_LIB=`tensorflow/contrib/makefile/compile_nsync.sh`
export TARGET_NSYNC_LIB=`tensorflow/contrib/makefile/compile_nsync.sh -t ios`
```

5. Created faster-rcnn specific ops:
```
  bazel build tensorflow/python/tools:print_selective_registration_header 
  bazel-bin/tensorflow/python/tools/print_selective_registration_header \
    --graphs=frozen_inference_graph.pb > ops_to_register.h
```

6. Moved `ops_to_register.h` under `tensorflow/core/framework/`

7. Successfully built `libtensorflow-core.a` to account for additional types and custom ops
```
tensorflow/contrib/makefile/compile_ios_tensorflow.sh "-O3  -DANDROID_TYPES=ANDROID_TYPES_FULL -DSELECTIVE_REGISTRATION -DSUPPORT_SELECTIVE_REGISTRATION"
```

8. Verified the creation of 
```
tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a
tensorflow/contrib/makefile/gen/protobuf_ios/lib/libprotobuf.a
tensorflow/contrib/makefile/gen/protobuf_ios/lib/libprotobuf-lite.a
```

9. Check for `tf_op_files.txt`, and made sure `tensorflow/core/ops/math_ops.cc` exists (I think this is where "Prod" is covered since there's no such file as `cwise_op_prod.cc`?)

10. Updated iOS camera example with faster-rcnn model, imported "mscoco_label_map", and corresponding input/output layers.

When running, I can't get pass error 
```
2017-10-30 18:00:28.307769: E [path]/tensorflow_utils.mm:209] Could not create TensorFlow Graph: Invalid argument: No OpKernel was registered to support Op 'Prod' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: SecondStageBoxPredictor/Flatten/Prod = Prod[T=DT_INT32, Tidx=DT_INT32, keep_dims=false](SecondStageBoxPredictor/Flatten/Slice_1, SecondStageBoxPredictor/Flatten/Const)]]
2017-10-30 18:00:28.320101: F [path]CameraExampleViewController.mm:495] Couldn't load model: Invalid argument: No OpKernel was registered to support Op 'Prod' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: SecondStageBoxPredictor/Flatten/Prod = Prod[T=DT_INT32, Tidx=DT_INT32, keep_dims=false](SecondStageBoxPredictor/Flatten/Slice_1, SecondStageBoxPredictor/Flatten/Const)]]
```

If I try the same steps with the model `ssd_mobilenet_v1_coco` from the same model zoo, it works fine.  I've also tried the instructions from [JieHe96/iOS_Tensorflow_ObjectDetection_Example](https://github.com/JieHe96/iOS_Tensorflow_ObjectDetection_Example) but runs into the exact same problem.

Can anyone help?

**Comment by jart** [comment]
When modifying examples, you might need to tailor the build to make sure all the kernel libraries (which use a registration pattern) are being included. With that said, this question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is a larger community that reads questions there. You can also likely search for many similar issues.

**Comment by tamias65** [comment]
Thanks. On a more general question, I figured that it's missing the right kernel libraries as suggested.  What is a good way to identify which kernel library I'm missing since I'm using the default faster_rcnn_resnet101_coco model from the Tensorflow model zoo and there are quite a few "Prod" ops in the overall kernel libraries.

**Comment by tamias65** [comment]
Actually I figured it out after reproducing the "ops_to_register.h" file using "print_selective_registration.py".  The "Prod" op is associated with "reduction_prod_op.cc".

**Comment by nanhuo** [comment]
Hi, @tamias65 , Could you please give some more details on how you figure out which 'cc' file is associated with the "Prod" op?. 
 I'm running into a similar problem here, which says "No OpKernel was registered to support Op 'Equal'".

**Comment by AdamWP** [comment]
@nanhuo I think you need to register the math operator https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/equal
