### ISSUE TITLE
[feature request] Does android tensorflow make the without considering front-camera and landscape mode ?  

### ISSUE THREAD

**Issue by nanamare** [tensorflow/tensorflow#14125]
Fist bump.
I want to make a tensorflow application available in landscape also, facing-mode 

But, during the development- 
There was a problem that  coordinates were displayed wrong when the front camera and landscape mode was used to detect the object, after inference
Do you have  any reference code or other resources ?

Have a nice day  :)

**Comment by nanamare** [comment]
finally i solved landscape and facing mode.
If you need help, just contact me :)
![kakaotalk_20171102_142109456](https://user-images.githubusercontent.com/17498974/32311043-cb058284-bfd9-11e7-9f6c-b884460a6e5e.jpg)

**Comment by asimshankar** [comment]
Glad to hear you were able to figure things out.  If there is a pull request you'd like to contribute to improve the demo app, please feel encouraged to do so.

Thanks!

**Comment by eduqz** [comment]
@nanamare how did you change the orientation to landscape? I'll be grateful if you can help me

**Comment by Starlon87** [comment]
@nanamare how did you change the orientation to landscape? I'll be grateful  too, if you can help me.

**Comment by linlin860320** [comment]
I have a problem. When I use the front camera for detection, the bounding box is displayed in the wrong position. How do I flip the box position to the right position?

When I moved left to right, the bounding box moved right to left...

**Comment by jktruimp1** [comment]
> finally i solved landscape and facing mode.
> If you need help, just contact me :)
> ![kakaotalk_20171102_142109456](https://user-images.githubusercontent.com/17498974/32311043-cb058284-bfd9-11e7-9f6c-b884460a6e5e.jpg)

can you help me handle this problem?
I succeeded in detecting object, but I got opposite direction in tracking bounding box.

**Comment by linlin860320** [comment]
@jktruimp1  You can find a function "private RectF upscaleRect(final RectF downsampledFrameRect)" in ObjectTracker.java
You can try modify 
`return new RectF(
        downsampledFrameRect.left * DOWNSAMPLE_FACTOR,
        downsampledFrameRect.top * DOWNSAMPLE_FACTOR,
        downsampledFrameRect.right * DOWNSAMPLE_FACTOR,
        downsampledFrameRect.bottom * DOWNSAMPLE_FACTOR); `
to
   ` return new RectF(
            frameWidth - (downsampledFrameRect.right * DOWNSAMPLE_FACTOR),
            downsampledFrameRect.top * DOWNSAMPLE_FACTOR,
            frameWidth - (downsampledFrameRect.left * DOWNSAMPLE_FACTOR),
            downsampledFrameRect.bottom * DOWNSAMPLE_FACTOR);`

It's work for me when using front camera.

**Comment by jktruimp1** [comment]
@linlin860320 
Thanks you very much!
I have found the solution, I changed trackpos in multiboxtracker.java.
I will try your way on Monday :)

**Comment by linlin860320** [comment]
@jktruimp1 
Though my way can solve the problem, but I'm think my way is not really the right solution.
So could you share what you change in MutiBoxTracker?

**Comment by jktruimp1** [comment]
@linlin860320
variable trackpos or something named like it, I guess

**Comment by aaronhan92** [comment]
> finally i solved landscape and facing mode.
> If you need help, just contact me :)
> ![kakaotalk_20171102_142109456](https://user-images.githubusercontent.com/17498974/32311043-cb058284-bfd9-11e7-9f6c-b884460a6e5e.jpg)

Hi, do you mind to share how do you switch the camera to front view?

**Comment by aaronhan92** [comment]
I've tried with the front camera view. Only need to play with the rotation variables and matrixes function.

**Comment by taalaialmasova** [comment]
@jktruimp1, @Nanamare can you help me? I have the same problem
