### ISSUE TITLE
Access denied to download faster_rcnn_nas_17_10_2017.tar.gz trained on COCO from the network zoo found in object detection

### ISSUE THREAD

**Issue by sarim-zafar** [tensorflow/tensorflow#14122]
Following is link on which it says the network is available to download
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md
But when i click the link to download http://download.tensorflow.org/models/object_detection/faster_rcnn_nas_17_10_2017.tar.gz
it says access denied

**Comment by asimshankar** [comment]
Could you be looking at an older version of `detection_model_zoo.md`?
It seems the link was updated in https://github.com/tensorflow/models/commit/819de0e330b7026e21044b2bc3e96d8c1eed8820#diff-40f0678d6846e6efc7bd00fc93c826b8 to http://download.tensorflow.org/models/object_detection/faster_rcnn_nas_coco_24_10_2017.tar.gz
