### ISSUE TITLE
feature request for TensorFlow  Speech Recognizer .apk

### ISSUE THREAD

**Issue by Vysha** [tensorflow/tensorflow#14138]
the Android .apk file is a great way to test TensorFlow  Speech Recognizer.
It would be even more useful with the addition of these two features:
1. once any word is detected, specify the scores for all 10 words in the list.
2. specify silence detection

Thank you in advance to anyone who is able to add these features!

**Comment by asimshankar** [comment]
@Vysha : We (the TensorFlow maintainers) will probably not have cycles to implement this in the near future, but we'd welcome pull requests to do so.

Thanks!
