### ISSUE TITLE
Nameerror: could not find operator mpisize in dynamic library mpi_collectives.so

### ISSUE THREAD

**Issue by wangshuaizs** [tensorflow/tensorflow#14148]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:ubuntu 16.04 with 4.4 kernel
- **TensorFlow installed from (source or binary)**: source code
- **TensorFlow version (use command below)**: latest(git clone from github in 2017/10/30)
- **Python version**: 2.7 
- **Bazel version (if compiling from source) : 0.70(latest)
- **CUDA/cuDNN version**: 8.0/6.0
- **GPU model and memory**: tesla k40c
- **Exact command to reproduce**: python -c "import tensforflow.contrib.mpi_collectives"

**Comment by NEWPLAN** [comment]
Yep, it seem that, the dynamic lib didn't contain a MPISize. so i think it is caused by the dynamic lib.
but how to fix it ?

**Comment by jart** [comment]
MPI is a very new contrib package that we're not able to officially support yet. Please reach out to @jthestness. See also https://github.com/tensorflow/tensorflow/pull/12299.
