### ISSUE TITLE
generator_input_fn for tensorflow estimator?

### ISSUE THREAD

**Issue by hanfeisun** [tensorflow/tensorflow#14145]
I find there is `numpy_input_fn` and `pandas_input_fn` to construct the input_fn for tensorflow estimator. 

However, sometimes I need a more flexible constructor that can create the `input_fn` from a custom generator/iterator. It seems that Tensorflow doesn't have this feature currently. 

There is a [generator_input_fn](https://github.com/tensorflow/tensorflow/pull/7045/files#diff-58e32b22d643f3a61d9bbeee2bec89b6R27) for `tensorflow.contrib.learn` but I think that is not compatible with Tensorflow Estimator. 

Is there any plan to add `generator_input_fn` for tensorflow estimator?

**Comment by asimshankar** [comment]
@ispirmustafa would probably know.

**Comment by ispirmustafa** [comment]
You can use `Dataset.from_generator` in your input_fn.

**Comment by hanfeisun** [comment]
@ispirmustafa Thanks, but while `numpy_input_fn` supports "dict of numpy array object" for data source, it seems that `Dataset.from_generator` doesn't support dictionary structure.

**Comment by ispirmustafa** [comment]
@mrry could you please comment about Dataset.from_generator?

**Comment by mrry** [comment]
I believe `Dataset.from_generator()` *does* support yielding dictionaries (of NumPy arrays), as long as you specify a dictionary-based structure in the `output_types` argument. If this is not the case, please file a bug with a way to reproduce the problem!

**Comment by baoruxiao** [comment]
@mrry Hi Derek, does Dataset.from_generator() support multithreading like QueueRunner?

Thanks
