### ISSUE TITLE
[feature request] Adding c++ serving session api to c api 

### ISSUE THREAD

**Issue by hanabi1224** [tensorflow/tensorflow#14146]
Or is it recommended to just use TF_NewSession C API for session serving?  Is TF_Session.Run thread safe?  Thanks in advance!

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
