### ISSUE TITLE
Unable to use tf.multinomial in Android. No OpKernel was registered to support Op 'Multinomial'

### ISSUE THREAD

**Issue by matsui-k20xx** [tensorflow/tensorflow#14150]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sierra 10.12.6, Android APK 23
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.3
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:N/A
- **GPU model and memory**:N/A

### Describe the problem
I cannot use tf.multinomial in Android while it works in mac. The error message is in the next section. I'm using tensorflow from [TensorFlowSharp](https://github.com/migueldeicaza/TensorFlowSharp) and [ml-agents](https://github.com/Unity-Technologies/ml-agents) in Unity. Unity builds my game uisng tensorflow for Android.

### Source code / logs
TFException: No OpKernel was registered to support Op 'Multinomial' with these attrs.  Registered devices: [CPU], Registered kernels:\<no registered kernels\>
[[Node: multinomial/Multinomial = Multinomial[T=DT_FLOAT, seed=0, seed2=0](dense_2/MatMul, multinomial/Multinomial/num_samples)]]
  at TensorFlow.TFStatus.CheckMaybeRaise (TensorFlow.TFStatus incomingStatus, System.Boolean last) [0x0004a] in <252020d87a4e4581ad2cfe3f9cc7a0ac>:0

**Comment by jart** [comment]
Please check out [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) and Google for similar issues. It's a common issue with Android development to make sure the right kernels get included in a build. Please note they use the registration pattern.
