### ISSUE TITLE
The new version of the code about Wide and Deep model has not yet defined 'centered_bias'

### ISSUE THREAD

**Issue by Shicoder** [tensorflow/tensorflow#14151]
Hi,
I'm reading the new version tensorflow code about Wide and deep model. the model is in tf.estimator.DNNLinearCombinedClassifier. In the tf.contrib.learn.DNNLinearCombinedClassifier,we can find that the variable 'centered_bias' is defined in head.py,It;s the bias of model's output.However, in the new version code. eg. the implemention based on 'tf.feature_column' and 'tf.estimator', this variale has not been find.It's only add dnn_logits and linear_logits. Is it a bug? or I do not find it.
thanks.
Xiangfu Shi

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
