### ISSUE TITLE
List of functions could be improved with "const std::string&" or "std::string&" instead "std::string"

### ISSUE THREAD

**Issue by orpillar** [tensorflow/tensorflow#14170]
After a quick scan in the latest tensorflow "master" branch, here is the list of functions which could improve passing parameter by "std::string":

After a quick scan in the latest tensorflow "master" branch, here is the list of functions which could improve passing parameter by "std::string":

1. c/c_api_function.cc:  static string Normalize(string name);
   Suggestion: string& name;
2. c/c_api_function.cc:string NodeNameMapping::Normalize(string name) {
   Suggestion: string& name
#
3. compiler/jit/graph_to_functiondef.cc:  string NormalizeHelper(string name) const;
   Suggestion: string& name
4. compiler/jit/graph_to_functiondef.cc:  string UniquifyHelper(string name);
   Suggestion: const string&
5. compiler/jit/graph_to_functiondef.cc:string NodeNameMapping::NormalizeHelper(string name) const {
   Suggestion: string& name
6. compiler/jit/graph_to_functiondef.cc:string NodeNameMapping::UniquifyHelper(string name) {
   Suggestion: const string&
7. compiler/tf2xla/dump_graph.cc:string MakeUniquePath(string name) {
   Suggestion: string& name
8. compiler/xla/service/llvm_ir/llvm_util.cc:string IrName(string a) {
    Suggestion: string& a
9. compiler/xla/service/llvm_ir/llvm_util.cc:string SanitizeFunctionName(string function_name) {
    Suggestion: string& function_name
10. compiler/xla/service/llvm_ir/llvm_util.h:string IrName(string a);
    Suggestion: string& a
11. compiler/xla/service/llvm_ir/llvm_util.h:string SanitizeFunctionName(string function_name);
    Suggestion: string& function_name
12. compiler/xla/util.cc:string SanitizeFileName(string file_name) {
    Suggestion: string& file_name
13. compiler/xla/util.h:string SanitizeFileName(string file_name);
    Suggestion: string& file_name
#
14. contrib/verbs/rdma.cc:RdmaBuffer::RdmaBuffer(RdmaChannel* channel, string name)
    Suggestion: const string& name
15. contrib/verbs/rdma.cc:RdmaAckBuffer::RdmaAckBuffer(RdmaChannel* channel, string name)
    Suggestion: const string& name
16. contrib/verbs/rdma.cc:RdmaMessageBuffer::RdmaMessageBuffer(RdmaChannel* channel, string name)
    Suggestion: const string& name
17. contrib/verbs/rdma.cc:RdmaTensorBuffer::RdmaTensorBuffer(RdmaChannel* channel, string name)
    Suggestion: const string& name
18. contrib/verbs/rdma.h:  explicit RdmaBuffer(RdmaChannel* channel, string name);
    Suggestion: const string& name
19. contrib/verbs/rdma.h:  explicit RdmaAckBuffer(RdmaChannel* channel, string name);
    Suggestion: const string& name
20. contrib/verbs/rdma.h:  explicit RdmaMessageBuffer(RdmaChannel* channel, string name);
    Suggestion: const string& name
21. contrib/verbs/rdma.h:  explicit RdmaTensorBuffer(RdmaChannel* channel, string name);
    Suggestion: const string& name
#
22. core/common_runtime/step_stats_collector.cc:static int ExtractGpuWithStreamAll(string device_name) {
    Suggestion: string& device_name
23. core/common_runtime/step_stats_collector.cc:static int ExtractGpuWithoutStream(string device_name) {
    Suggestion: string& device_name
24. core/kernels/ops_util.cc:string SanitizeThreadSuffix(string suffix) {
    Suggestion: const string& suffix
25. core/kernels/ops_util.h:string SanitizeThreadSuffix(string suffix);
    Suggestion: const string& suffix
26. core/kernels/xsmm_conv2d.cc:static void chk_libxsmm_err(libxsmm_dnn_err_t status, string msg) {
    Suggestion: const string& msg
#
27. stream_executor/platform.cc:PlatformKind PlatformKindFromString(string kind) {
    Suggestion: const string& kind
28. stream_executor/platform.h:PlatformKind PlatformKindFromString(string platform_string);
    Suggestion: const string& platform_string

**Comment by jart** [comment]
@orpillar I'm a big fan of cleanup work. A lot of the stuff on this list checks out, like `for (string name : events) {` tracing.cc. I support refactoring those unidiomatic usages of the C++ language. However this list needs more curation. I looked at (1) which points to [NodeNameMapping::Normalize](https://github.com/tensorflow/tensorflow/blob/4f39566/tensorflow/c/c_api_function.cc#L75) and this function passes by value because it mutates the value. Could you help us narrow things down?

**Comment by orpillar** [comment]
@jart You are right. The first function **NodeNameMapping::Normalize** needs to have "**&**" added, there is no need to add "const". I updated the issue description, will list with more details soon.

**Comment by orpillar** [comment]
Updated the list

**Comment by jart** [comment]
@orpillar Passing a non-const reference would change the API and isn't allowed by the [Google C++ Style Guide](http://google.github.io/styleguide/cppguide.html#Reference_Arguments).

**Comment by orpillar** [comment]
Thanks for providing the Google C++ Style Guide. The guide does mention the rule. Please feel free to close the issue if not applicable.

**Comment by jart** [comment]
Well the issue is applicable, it's simply a question of curation. We appreciate that you took the time to suggest an improvement strategy. If you decide later that you want to take on this cleanup work, please send us a pull request, which I'd be happy to review.
