### ISSUE TITLE
Getting wrong value with placeholder

### ISSUE THREAD

**Issue by salihkaragoz** [tensorflow/tensorflow#14177]
### System information

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No, I have used code which is on the [link](https://www.tensorflow.org/get_started/get_started). 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04 LTS
- **TensorFlow installed from (source or binary)**:
Installing with native pip (tensorflow-gpu)
- **TensorFlow version (use command below)**:
'1.3.0'
- **Python version**: 
 Python 2.7.12
('v1.3.0-rc2-20-g0787eee', '1.3.0')
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
- **CUDA/cuDNN version**:
CUDA : release 8.0, V8.0.61
cuDNN: CUDNN_MAJOR      6
- **GPU model and memory**:
GeForce 940MX 
Memory: 2GB
Driver Version: 384.90

### Describe the problem
When I run at below code, I think i am getting the wrong result.

### Source code / logs
```
import tensorflow as tf
sess = tf.Session()
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a + b
print(sess.run(adder_node, {a: 3, b: 4.5}))
print(sess.run(adder_node, {a: [1, 3], b: [2, 4]}))
```

> **My Output :**
>  **3.0**
> **[ 1. 3.]**

> **I think the true result should be;**
> **7.5**
> **[ 3. 7.]**
> 

### Logs
Also, when i type `sess = tf.Session()` , i am getting that output
> 2017-11-02 12:09:04.184601: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-11-02 12:09:04.184689: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-11-02 12:09:04.184717: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
> 2017-11-02 12:09:04.184753: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-11-02 12:09:04.184805: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
> 2017-11-02 12:09:04.368504: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2017-11-02 12:09:04.368855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
> name: GeForce 940MX
> major: 5 minor: 0 memoryClockRate (GHz) 1.2415
> pciBusID 0000:01:00.0
> Total memory: 1.96GiB
> Free memory: 1.53GiB
> 2017-11-02 12:09:04.368870: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
> 2017-11-02 12:09:04.368874: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
> 2017-11-02 12:09:04.368882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0)

**Comment by asimshankar** [comment]
Hmm....I'm unable to reproduce the error using TensorFlow 1.3.0 (I see the correct outputs of `7.5` and `[3, 7]`. The outputs you see make sense if the line was `adder_node = a` instead of `adder_node = a + b`!

I don't have the same driver/GPU as you, though I doubt those would be to blame. But just to be extra sure, do you see the same errors when using just the CPU, say with:

```python
import tensorflow as tf

sess = tf.Session()
with tf.device('/cpu:0'):
  a = tf.placeholder(tf.float32)
  b = tf.placeholder(tf.float32)
  adder_node = a + b
print(sess.run(adder_node, {a: 3, b: 4.5}))
print(sess.run(adder_node, {a: [1, 3], b: [2, 4]}))
```

The log output you mentioned above is just informational logs. I didn't see any concerning notes in that.

**Comment by salihkaragoz** [comment]
@asimshankar Thank you for your interest. When i run over CPU with at above code, i got the true result. `7.5` and `[3, 7]`.

**Comment by asimshankar** [comment]
Hmm...that's weird.

Do you see the same problem with TensorFlow 1.4.0? Is it possible for you to try this on a different machine (specifically, one with a different driver/CUDA version/GPU or something)? Or, does upgrading CUDA/the NVIDIA driver make any difference?

**Comment by salihkaragoz** [comment]
@asimshankar  . I have also tried with Python 3.5.2 and Tensorflow '1.4.0' which is installed with pip3 tensorflow - gpu. I got same wrong results. I think the problem is related to GPU, it is old and has small memory. Thank you for your all effort.
