### ISSUE TITLE
memory leak with tf.image.encode_jpeg

### ISSUE THREAD

**Issue by c3l2** [tensorflow/tensorflow#14185]
I encountered an issue with tf.image.encode_jpeg. I got a lot of images to preprocess. The code that caused the problem is like this:

for imagefile in image_list:
  im = cv2.imread(imagefile)
  image_data = tf.image.encode_jpeg(im, format='rgb')

The memory usage kept increasing as image.encode_jpeg was called. Eventually the 256G mem server ran out of memory.

**Comment by mrry** [comment]
In regular TensorFlow, calling `tf.image.encode_jpeg()` (or any TensorFlow op function) in a loop will append it to a graph. Furthermore, each value of `im` will be embedded in the graph as a constant. There are a few options here:

* Try the recently announced [eager execution](https://research.googleblog.com/2017/10/eager-execution-imperative-define-by.html) mode, which makes code like this work the way you would expect, and prevents your code from leaking memory.

* Create a `tf.data` pipeline to do the conversion:

  ```python
  def generator():
    for imagefile in image_list:
      yield cv2.imread(imagefile)

  dataset = tf.data.Dataset.from_generator(generator, tf.uint8).map(tf.image.encode_jpeg)
  ```

* Create a single `tf.image.encode_jpeg()` op that takes its input from a `tf.placeholder()` and feed that placeholder with each image.

**Comment by c3l2** [comment]
@mrry Thanks a lot! I will try your suggestions.
