### ISSUE TITLE
Make CMake on TensorFlow Incrementally Compile on Windows

### ISSUE THREAD

**Issue by johnsrude** [tensorflow/tensorflow#14194]
I'm working with the tensorflow r1.4 branch on Windows 7 with Visual Studio 2015.   When I configure

```
cmake C:\Users\Kevin\dev\tensorflow-r1.4\tensorflow\contrib\cmake -A x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=C:/Users/Kevin/dev/swigwin-3.0.12/swig.exe -DPYTHON_EXECUTABLE=C:/ProgramData/Anaconda3/python.exe -DPYTHON_LIBRARIES=C:/ProgramData/Anaconda3/libs/python35.lib -DPYTHON_INCLUDE_DIR=C:\ProgramData\Anaconda3\include -DNUMPY_INCLUDE_DIR=C:\ProgramData\Anaconda3\Lib\site-packages\numpy\core\include -Dtensorflow_ENABLE_GPU=ON -DCUDNN_HOME="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0"
```
and run

```
powershell "MSBuild /m /p:Configuration=Release tf_python_build_pip_package.vcxproj | tee msbuild.txt"
```
the build always compiles all the projects, even the projects already compiled.

Looking at the first few lines of msbuild.txt I see

```
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 11/2/2017 4:35:58 PM.
     1>Project "C:\users\kevin\dev\tensorflow-r1.4\tensorflow\contrib\cmake\tf_python_build_pip_package.vcxproj" on node 1 (default targets).
     1>Project "C:\users\kevin\dev\tensorflow-r1.4\tensorflow\contrib\cmake\tf_python_build_pip_package.vcxproj" (1) is building "C:\Users\Kevin\dev\tensorflow-r1.4\tensorflow\contrib\cmake\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
     2>InitializeBuildStatus:
         Creating "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
       CustomBuild:
         Checking Build System
         CMake is re-running because C:/Users/Kevin/dev/tensorflow-r1.4/tensorflow/contrib/cmake/CMakeFiles/generate.stamp is out-of-date.
           the file 'C:/Users/Kevin/dev/tensorflow-r1.4/tensorflow/contrib/cmake/CMakeFiles/tf_core_gpu_kernels.dir/__/__/core/kernels/tf_core_gpu_kernels_generated_cwise_op_gpu_igammas.cu.cc.obj.depend'
           is newer than 'C:/Users/Kevin/dev/tensorflow-r1.4/tensorflow/contrib/cmake/CMakeFiles/generate.stamp.depend'
           result='-1'
         -- Configuring done
```
The issue isn't the multicore builds, I'm just using multicore builds to speed up the overall build, which takes 5 hours on one core.

The problem appears to be that the generate.stamp isn't what's expected.

**Comment by mrry** [comment]
This would definitely be a useful feature for anyone relying on the CMake build in regular development. However, since we only currently rely on CMake for CI builds on Windows, these are always from scratch, and we hope to shift that build to Bazel for Windows ASAP, it is unlikely that anyone on the TensorFlow team will spend time investigating the cause of the gratuitous rebuilds. Therefore I'm going to mark this issue as "Contributions Welcome", and I hope some member of the community heeds the call.

I'd be happy to respond to questions on this thread about how the build is structured with a view to making it incremental, and very happy to review pull requests that improve the situation. 

/cc @gunan FYI.

**Comment by johnsrude** [comment]
When will the Windows Bazel build be ready for prime-time?

The Nettles: Celtic. Eclectic. Folkadelic.
www.TheNettles.com <http://www.thenettles.com/>

**Comment by snnn** [comment]
Hi @johnsrude , now it lacks tf.load_library() support. All stuffs in tf.contrib are missing.   For the others, it's almost perfect.

**Comment by headupinclouds** [comment]
@johsrude The CMake build appears to be configured to generate an new version file `tensorflow/core/util/version_info.cc` for *every* build, which is included in the low level `tf_core_framework`.  This is at least partly responsible for the rebuild problems.

There is a custom command that creates the version file from python + git here:

https://github.com/tensorflow/tensorflow/blob/dcd820616d352d1e8844b1db504af4e859176cbf/tensorflow/contrib/cmake/tf_core_framework.cmake#L271-L283

I *think* what we want, is to only update this file if the git version has changed.  I've added an extra `add_custom_command` to copy the output from `gen_git_source.py --raw_generate` over`tensorflow/core/util/version_info.cc` only if it has changed using CMake's `copy_if_different`, and that seems to address the unwanted full rebuild.

```
# Tricky setup to force always rebuilding
# force_rebuild always runs forcing ${VERSION_INFO_CC} target to run
# ${VERSION_INFO_CC} would cache, but it depends on a phony never produced
# target.
set(gen_git_source ${tensorflow_source_dir}/tensorflow/tools/git/gen_git_source.py)
set(version_info_cc_tmp ${CMAKE_CURRENT_BINARY_DIR}/version_info.cc)
add_custom_target(force_rebuild_target ALL DEPENDS ${VERSION_INFO_CC})
set_property(TARGET force_rebuild_target PROPERTY FOLDER "custom")

add_custom_command(OUTPUT __force_rebuild COMMAND ${CMAKE_COMMAND} -E echo)
add_custom_command(OUTPUT
    ${version_info_cc_tmp}
    COMMAND ${PYTHON_EXECUTABLE} ${gen_git_source} --raw_generate ${version_info_cc_tmp}
    DEPENDS __force_rebuild)

set(VERSION_INFO_CC ${tensorflow_source_dir}/tensorflow/core/util/version_info.cc)
add_custom_command(OUTPUT
  "${VERSION_INFO_CC}"
  DEPENDS "${version_info_cc_tmp}"
  COMMAND ${CMAKE_COMMAND} -E copy_if_different "${version_info_cc_tmp}" "${VERSION_INFO_CC}"
  ) 
  
set(tf_version_srcs ${VERSION_INFO_CC})
```

I've tested this on OS X and it seems to be working.  Is there an active CMake author who can review this?

**Comment by mrry** [comment]
@headupinclouds I'd be happy to review a PR for this. Thanks!

**Comment by headupinclouds** [comment]
I've pushed the above changes in a PR (tested in another branch) for now:

https://github.com/headupinclouds/tensorflow/tree/pr.cmake.incremental.build

I'm running into some unrelated build issues after pulling the latest from master.  I'll hold off on submitting this until I sort those out.

**Comment by steven-hh-ding** [comment]
This seems very useful. Every time I compile a user_op on windows it needs to re-compile everything..

**Comment by snnn** [comment]
Hi @steven-hh-ding Forget cmake, Embrace bazel!

**Comment by steven-hh-ding** [comment]
@snnn Thanks! You mean I can build user_opr on windows with bazel? I will check it out!

**Comment by snnn** [comment]
Wait, for custom user_op, if you build it as a dll, then you can put it into a separated project, which is not part of the tensorflow.sln. So you don't have to use either cmake or bazel. All the issues described here are gone.  

If you put your custom user_op inside tensorflow source tree, it's another story. Yes. you can build it with bazel, and it's very fast.

**Comment by steven-hh-ding** [comment]
Thank you @snnn ! I managed to skip the rebuild with /p:BuildProjectReferences=false. Will switch to bazel later. Thanks!

**Comment by PROGrand** [comment]
with up-to-date sources (--source_dir and --git_tag_override):
```
# Tricky setup to force always rebuilding
# force_rebuild always runs forcing ${VERSION_INFO_CC} target to run
# ${VERSION_INFO_CC} would cache, but it depends on a phony never produced
# target.
set(gen_git_source ${tensorflow_source_dir}/tensorflow/tools/git/gen_git_source.py)
set(version_info_cc_tmp ${CMAKE_CURRENT_BINARY_DIR}/version_info.cc)
add_custom_target(force_rebuild_target ALL DEPENDS ${VERSION_INFO_CC})
set_property(TARGET force_rebuild_target PROPERTY FOLDER "custom")

add_custom_command(OUTPUT __force_rebuild COMMAND ${CMAKE_COMMAND} -E echo)
add_custom_command(OUTPUT
    ${version_info_cc_tmp}
    COMMAND ${PYTHON_EXECUTABLE} ${gen_git_source}
    ARGS --raw_generate ${version_info_cc_tmp} --source_dir ${tensorflow_source_dir} --git_tag_override=${GIT_TAG_OVERRIDE}
    DEPENDS __force_rebuild)

set(VERSION_INFO_CC ${tensorflow_source_dir}/tensorflow/core/util/version_info.cc)
add_custom_command(OUTPUT
  "${VERSION_INFO_CC}"
  COMMAND ${CMAKE_COMMAND}
  ARGS -E copy_if_different "${version_info_cc_tmp}" "${VERSION_INFO_CC}"
  DEPENDS "${version_info_cc_tmp}"
  ) 
  
set(tf_version_srcs ${VERSION_INFO_CC})
```

**Comment by snnn** [comment]
I would avoid to build tensorflow at home because my internet service provider(Xfinity) has a data cap.

**Comment by kumariko** [comment]
@johnsrude It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. Contrib has been depreciated in Tensorflow 2.x , also please refer this [link](https://www.tensorflow.org/guide/migrate) .
