### ISSUE TITLE
TF not compatible with AWS GPU instances?

### ISSUE THREAD

**Issue by nbenhaim** [tensorflow/tensorflow#142]
It seems like Google Compute Engine doesn't even have gpu instances, and AWS GPU instance isn't supported because it requires >= 3.5 cuda compute capability.  Is this correct?

**Comment by ebrevdo** [comment]
This is correct.  We currently do not support AWS GPU instances because of their 3.0 cuda compute capability.  You can try disabling that requirement in the source code and seeing if it works for you.

**Comment by anjishnu** [comment]
Is there any plan to support them, i.e. does the tensorflow source actually utilize the new features in cuda 3.5 capability?

**Comment by vrv** [comment]
zheng-xq is working on adding configurable support to it.

For every compute capability you add, the compile time and binary size increases significantly, so we're trying to find a solution.

In any case, thanks for the report -- de-duping with https://github.com/tensorflow/tensorflow/issues/25.
