### ISSUE TITLE
java.lang.UnsatisfiedLinkError: tensorflow_native_libraries-1509708652238-0/libtensorflow_jni.so: /lib64/libc.so.6: version `GLIBC_2.16' not found (required bytensorflow_native_libraries-1509708652238-0/libtensorflow_jni.so)

### ISSUE THREAD

**Issue by zjh-nudger** [tensorflow/tensorflow#14208]
The exception is caught when I run Tensorflow API in java. There is no GLIBC_2.16. The lowest version is 2.2.5. what should I do? Could I package the .so file by myself?

**Comment by asimshankar** [comment]
Please do try to fill in all the information asked for the in issue template (https://github.com/tensorflow/tensorflow/issues/new), without that it is somewhat hard to help.

In this particular case, what platform are you running on?  
Seems like you have a very old version of glibc (2.2.5 is from 2002 I believe - as per https://sourceware.org/glibc/wiki/Glibc%20Timeline)

If that is the case, and you're unable to use a more modern version of glibc, then you could try compiling from source - though I'm not sure that it will work.

To build from sources see https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java#building-from-source 

And once you have the native libraries (`libtensorflow_framework.so` and `libtensorflow_jni.so`) built, you could simply copy them to a directory an include that directory in the `java.library.path` property provided to the JVM.

Hope that helps.

**Comment by zjh-nudger** [comment]
Thanks. How can I specific the GLIBC version when I compile from source?  Is the GLIBC version same as GCC ?

**Comment by asimshankar** [comment]
Can you compile on the same machine you're deploying on (the one that has the old GLIBC version?).

That said, it is quite possible that TensorFlow will not compile with an older GLIBC version. Unfortunately, we don't have the bandwidth to support that, and will have to rely on community support.

**Comment by zjh-nudger** [comment]
unfortunately, I can not compile on the machine which I don't have the authority...

**Comment by zjh-nudger** [comment]
I have tried to compile on the machine with lower GLIBC version. Unfortunately, The compile tool (Bazel) need one higher GLIBC[bazel: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bazel)]. Consequently, there is no way to run the native tensorflow program on machine with lower GLIBC version（<2.14）...
