### ISSUE TITLE
Support for double precision complex numbers

### ISSUE THREAD

**Issue by ibab** [tensorflow/tensorflow#1420]
I'd like to use TensorFlow to write an application that would need `complex128` as a dtype.
But TensorFlow currently only supports `complex64`.
Are there any plans for supporting `complex128` as well in the future?

Seems that there is a TODO for this in  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/types.proto#L36.

**Comment by girving** [comment]
Yes, `complex128` would be good to have, but I don't think anyone's working on it at the moment.

**Comment by girving** [comment]
If someone wants to add it, I'm happy to answer questions.  It should mostly involve duplicating any mention of `complex64` into `complex64` and `complex128`.

**Comment by ibab** [comment]
When adding this to the [`types.proto`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/types.proto), should this be added to the enum as `DT_COMPLEX64 = 18;` to maintain backwards-compatibility?

**Comment by girving** [comment]
@ibab: Yep, it'd be `DT_COMPLEX128 =  18` and `DT_COMPLEX128_REF = 118`.
