### ISSUE TITLE
tf.contrib.learn.Experiment - train_monitors should be renamed

### ISSUE THREAD

**Issue by mpekalski** [tensorflow/tensorflow#14229]
Shouldn't **train_monitors** be renamed to **train_hooks**? As far as I understand hooks replaced monitors.

I look at TF v1.4.0-rc1.

tf.contrib.learn.Experiment(estimator, train_input_fn, eval_input_fn, eval_metrics=None, train_steps=None, eval_steps=100, **train_monitors**=None, **eval_hooks**=None, local_eval_frequency=None, eval_delay_secs=120, continuous_eval_throttle_secs=60, min_eval_frequency=None, delay_workers_by_global_step=False, export_strategies=None, train_steps_per_iteration=None, checkpoint_and_export=False)

**Comment by zhedongzheng** [comment]
There seems to be some difference between tf.estimator and tf.contrib.learn (though i think tf.estimator comes from tf.contrib.learn)
The similar issue is ```train()``` and ```fit```, it would be great if we can make two APIs compatible in these functions and arguments in the long term

**Comment by asimshankar** [comment]
FYI: As outlined in our [versioning guarantees policy](https://www.tensorflow.org/programmers_guide/version_compat#what_is_not_covered), things in the `tf.contrib` namespace are considered experimental and subject to change.

So we allow for differences between say `tf.estimator` and `tf.contrib.learn`, as a means of learning from feedback on functions and classes in `tf.contrib` before settling down on an API we will provide stability guarantees for going forward (`tf.estimator` in this case).

In the long term, the `tf.contrib` symbols will go away (as we either figure out that they are not worth pursuing or adapt them into ones that we will support in a non-`contrib` module).

Hope that makes sense.

Thanks!

(FYI @ispirmustafa for this particular case)
