### ISSUE TITLE
bayeslfow.hmc - provide option for skipping the MH step

### ISSUE THREAD

**Issue by botev** [tensorflow/tensorflow#14221]
Currently `tf.contrib.bayesflow.hmc.kernel` returns directly the update x and value of the potential after the Metropolis-Hasting steps. It would be useful to have an option to omitting the MH step. This, for instance, is required for implementing HVI [1], where we want to propagate gradients through the HMC step and not reject any samples:

[1] https://arxiv.org/pdf/1410.6460.pdf

**Comment by asimshankar** [comment]
@jvdillon : Any thoughts on this?

@botev : You may want to consider sending a pull request.

**Comment by tilakrayal** [comment]
@botev,
Respected PR was closed. Could you please check the [comment](https://github.com/tensorflow/tensorflow/pull/14237#issuecomment-370176051) from the developer and provide the required information. Thank you!
