### ISSUE TITLE
Feature request: an op that returns timestamp

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#14228]
This is useful for stats tracking in distributed TensorFlow (ie, measuring TF communication latency between workers and plotting it in TensorBoard). Perhaps it could be called `CurrentTimestamp`, `tf.current_timestamp()`

```
#include "tensorflow/core/platform/env.h"
static EnvTime* env_time = tensorflow::EnvTime::Default();
uint64 now_micros = env_time->NowMicros();
```

**Comment by bignamehyp** [comment]
If you would like to plot time stamp on tensorboard, you can use include it in tf.summary
For example,
summary_writer = tf.summary.FileWriter()

summary = tf.Summary()
summary.value.add(tag='xxx', simple_vale=yyy)
summary_writer.add_summary(summary, global_step)

**Comment by yaroslavvb** [comment]
How would you plot communication latency between workers using tf.summary?
You need something like CurrentTimestamp op to execute on one worker, and then compare it against timestamp on another worker to get the latency
