### ISSUE TITLE
Tensorflow just not working

### ISSUE THREAD

**Issue by manucarbonell** [tensorflow/tensorflow#1422]
I stopped using tensorflow for a while. Now i want to get back to it, but after installing, when I try to import tensorflow module on python i get this message:
```
Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there
```
Have tried uninstalling all previous existing versions and exiting any tensorflow folder, i'm running python from root folder, but I still get the error. Also if I download tensorflow from github and run from tensorflow version 6.0 I get same error
Any idea?
Thanks

**Comment by vrv** [comment]
- Can you include the stack of the entire error message?
- Have you tried installing in a virtualenv from scratch , using version 0.7.1 ?

**Comment by ushnish** [comment]
Check this out, i had this exact same trouble this weekend

https://github.com/tensorflow/tensorflow/issues/1402#event-580456750

**Comment by manucarbonell** [comment]
thanks @ushnish, but shouldn't it work only by following the steps explained on the installation guide?
I get the same error if I install using virtualenv.
@vrv here's the command's I do and the entire error message:
`sudo pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp27-none-any.whl`
```
Collecting tensorflow==0.7.1 from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp27-none-any.whl
  Downloading https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp27-none-any.whl (11.6MB)
```

...

```
Installing collected packages: tensorflow
Successfully installed tensorflow-0.7.1
```

...

```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Library/Python/2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named protobuf


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

```

**Comment by vrv** [comment]
https://www.tensorflow.org/versions/master/get_started/os_setup.html#pip-installation-issues might help :)

**Comment by manucarbonell** [comment]
Right! Didn't see I also had to uninstall protubuf. Thanks!

**Comment by danmane** [comment]
Sounds from the discussion like this issue can be closed - please re-open if you're still experiencing problems.

**Comment by MuhammadAsadJaved** [comment]
Please help me to solve this problem i am trying from several days. i get this error when i import tensorflow after installation , i am using windows OS

>>> import tensorflow as tf
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.umath failed to import
ImportError: numpy.core.umath failed to import
2018-10-18 18:24:15.573678: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr
