### ISSUE TITLE
64MB protobuf limit

### ISSUE THREAD

**Issue by drasmuss** [tensorflow/tensorflow#14220]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.4.0
- **Python version**: 3.5
- **Exact command to reproduce**:

```
import tensorflow as tf
import numpy as np

a = tf.constant(np.zeros(10000000))
profiler = tf.profiler.Profiler(tf.get_default_graph())
```

### Describe the problem
Running the above code results in the error message:
```
[libprotobuf ERROR C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\35\cmake_build\protobuf\src\protobuf\src\google\protobuf\io\coded_stream.cc:208] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf ERROR C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\35\cmake_build\protobuf\src\protobuf\src\google\protobuf\text_format.cc:298] Error parsing text-format tensorflow.GraphDef: 2:1: Interpreting non ascii codepoint 224.
[libprotobuf ERROR C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\35\cmake_build\protobuf\src\protobuf\src\google\protobuf\text_format.cc:298] Error parsing text-format tensorflow.GraphDef: 2:1: Expected identifier, got: à
Failed to parse graph
```

Reading #582 suggests that this problem should have been fixed in `protobuf 3.2.0`, but that doesn't seem to be the case in my system.  This may be a Windows-specific issue?

### Source code / logs
Here is the output of `pip freeze` showing the installed versions of tensorflow/protobuf (this is all starting from a fresh environment, and installed via `pip install tensorflow`).

```
bleach==1.5.0
certifi==2016.2.28
enum34==1.1.6
html5lib==0.9999999
Markdown==2.6.9
numpy==1.13.1
protobuf==3.4.0
six==1.11.0
tensorflow==1.4.0
tensorflow-tensorboard==0.4.0rc2
Werkzeug==0.12.2
wincertstore==0.2
```

**Comment by mrry** [comment]
Can you please try installing the nightly build of TensorFlow (`pip install tf-nightly`) and see if this is a problem? 

It looks like b927df57f0c09ea62a855795e340d6daf70553df upgrades TensorFlow on Windows to a newer version of protobuf, and that patch wasn't present in the 1.4 release.

**Comment by drasmuss** [comment]
That works!  So this should be fixed in the next release (or use `tf-nightly` in the meantime).  Thanks for the quick response.
