### ISSUE TITLE
Build from source documentation is incorrect

### ISSUE THREAD

**Issue by montanalow** [tensorflow/tensorflow#14230]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.4.0
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**: **4.5**
- **GCC/Compiler version (if compiling from source)**: 4.8
- **CUDA/cuDNN version**: 8/6
- **GPU model and memory**: nvidia
- **Exact command to reproduce**: bazel build --config=opt --config=cuda --verbose_failures //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
Documentation is incorrect: https://www.tensorflow.org/install/install_sources

"Tested source configurations" lists bazel 0.4.5 for tensorflow 1.4.0. Tensorflow 1.4.0 rejects this version of bazel with an error message:

Current Bazel version is 0.4.5, expected at least 0.5.4

### Source code / logs
```
$ bazel build --config=opt --config=cuda --verbose_failures //tensorflow/tools/pip_package:build_pip_package
 ---> Running in 547db5b015bf
WARNING: Config values are not defined in any .rc file: opt
ERROR: /tmp/tensorflow/WORKSPACE:41:1: Traceback (most recent call last):
File "/tmp/tensorflow/WORKSPACE", line 41
		tf_workspace()
	File "/tmp/tensorflow/tensorflow/workspace.bzl", line 146, in tf_workspace
		check_version("0.5.4")
	File "/tmp/tensorflow/tensorflow/workspace.bzl", line 56, in check_version
		fail("
Current Bazel version is {}, e...))

Current Bazel version is 0.4.5, expected at least 0.5.4
```

**Comment by asimshankar** [comment]
Thanks for pointing this out.

@jugglerix @gunan : Seems like the table needs to be updated?

**Comment by montanalow** [comment]
I was able to successfully build with 0.5.4, instead of 0.4.5

**Comment by gunan** [comment]
@av8ramit Could you check if we have the information correct in the table?

**Comment by erichiller** [comment]
& is 0.7.0 acceptable, because the Bazel installation guide the TensorFlow doc points to has only 0.7.0 in it's repo (unless installing from git) -- a list of acceptable releases might be good.

**Comment by av8ramit** [comment]
Yes, unfortunately the information in that table is out of date for 1.4.0. I'll update it accordingly.

**Comment by av8ramit** [comment]
https://github.com/tensorflow/tensorflow/pull/14298 thank you @jugglerix for pointing this out.

**Comment by av8ramit** [comment]
https://www.tensorflow.org/install/install_sources
