### ISSUE TITLE
Need force_gpu_if_available for tests

### ISSUE THREAD

**Issue by martinwicke** [tensorflow/tensorflow#1423]
For GPU tests, we have the `force_gpu` and `use_gpu` flags. `force_gpu=True` is good for manual testing during development, but if an op cannot be placed on a gpu because there isn't a GPU or because TensorFlow was built without GPU support, it will make the test fail. 

For tests, we really need a way to say "fail if a GPU is available, but it's not used". Could be as simple as providing the equivalent of `force_gpu=tf.compiled_with_GPU_support() and tf.get_GPU_devices()`. Both functions don't exist, but really should.

**Comment by girving** [comment]
`tf.test.is_built_with_cuda` may be useful.

**Comment by martinwicke** [comment]
We never merged the PR -- some test was still failing. So this issue is still not fixed.

**Comment by girving** [comment]
@martinwicke I'm not sure I understand.  You suggested that it might be as simple as `force_gpu=tf.test.is_built_with_cuda`, which already exists.  What is missing?

**Comment by martinwicke** [comment]
Do we have a function telling you (easily) whether there is a GPU?

**Comment by girving** [comment]
Ah, right.  Apologies for poor reading comprehension.  That other function doesn't exist as far as I know.

**Comment by girving** [comment]
Wrapping that up as `tf.test.is_gpu_available` would be great.

**Comment by gunan** [comment]
is_gpu_available is now ready.
Force gpu if available has been in the plans, but getting delayed deprioritized so far.

**Comment by girving** [comment]
@martinwicke says close.
