### ISSUE TITLE
graph_editor doesn't update graph_version

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#14233]
Symptom:
1. session.run
2. modify the graph with tf.contrib.graph_editor
3. session.run

Session.run in step 3 will use the same graph as in step 1 (pre-modification)

The reason is that session.py looks at [self._graph.version]( https://github.com/tensorflow/tensorflow/blob/4e75ae1f1e8c6479cfa86fde1a940453945e6671/tensorflow/python/client/session.py#L1345) when deciding whether to trigger TF_ExtendGraph. Since `graph_editor` doesn't update graph_version, it will reuse the previous graph.

Suggestion: every graph-modifying method in `graph_editor` should increment `version` attribute for the graph

@purpledog

**Comment by angersson** [comment]
@purpledog, can you take a look at this feature request?

**Comment by csuth86** [comment]
@yaroslavvb  Do you still see this as an issue? Looks like the code you're referring to has changed between r1.9 and r1.10.

Also, looking at the current document below, it seems if you are trying to edit graph in session it is not allowed.  https://www.tensorflow.org/api_guides/python/contrib.graph_editor

@purpledog  can we close this if thats the case?

**Comment by sachinprasadhs** [comment]
@yaroslavvb , As per the information provided [here](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md) graph editor has been deleted in the latest Tensorflow version. 
You can check [this](https://www.tensorflow.org/api_docs/python/tf/Graph) documentation for anything related to Tensorflow graph. 
Feel free to close the issue if you don't have any further question.
