### ISSUE TITLE
BUG: ImportError: No module named 'tensorflow.contrib.eager'

### ISSUE THREAD

**Issue by Instassa** [tensorflow/tensorflow#14247]
### Describe the problem
After I install the eager, i.e. `pip install tf-nightly-gpu` in my virtualenv activated I run
```
(tensorflow-gpu-3.5) marija@dhcp-90-160:~/DCGAN-tensorflow$ python
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import tensorflow.contrib.eager as tfe
```
and get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'tensorflow.contrib.eager'
```

**Comment by asimshankar** [comment]
That seems like it isn't using the latest nightly builds. Could you try the following to ensure that you're not using an old, cached nightly build:

```sh
pip install -U tf-nightly-gpu
```

If that still doesn't work, do add more detailed version information by running the following in a Python shell:

```python
import tensorflow as tf
print(tf.__version__)
print(tf.__git_version__)
```

Thanks

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by cswords** [comment]
The nightly built wheels are sometimes less than 30mb, which does not make sense to me. And I confirm that tf_nightly-1.5.0.dev20171216-cp35-cp35m-win_amd64.whl (29.46 MB) does not have eager mode.

**Comment by pinemosquito** [comment]
I run into this same error
ImportError                               Traceback (most recent call last)
<ipython-input-1-fb328cb2bd94> in <module>()
----> 1 import tensorflow.contrib.eager as tfe
      2 tfe.enable_eager_execution()
      3 import tensorflow as tf

ImportError: No module named 'tensorflow.contrib.eager'

**Comment by EricKani** [comment]
Have someone fixed this question?
>>> import tensorflow as tf
>>> print(tf.__version__)
1.4.0
>>> print(tf.__git_version__)
b'unknown'
>>>
Emmm, what the 'git' used for contrib.eager?
Thanks.

**Comment by asimshankar** [comment]
@pinemosquito @EricKani - `tensorflow.contrib.eager` was not included in TensorFlow 1.4. It is included in TensorFlow 1.5.

**Comment by pinemosquito** [comment]
Thank you!  My version was very old 0.12.1  
I updated with docker run -it gcr.io/tensorflow/tensorflow:latest-devel to 1.5 and it is working now

**Comment by EricKani** [comment]
Thank you！

**Comment by aksstar** [comment]
Upgrading TensorFlow solved the issue.
