### ISSUE TITLE
SpaceToDepthGrad and DepthToSpaceGrad are not aware of data_format

### ISSUE THREAD

**Issue by manipopopo** [tensorflow/tensorflow#14243]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.4.0-rc1-11-g130a514 1.4.0
- **Python version**: 3.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: CUDA 8.0 / cuDNN 6
- **GPU model and memory**:
- **Exact command to reproduce**:

`tf.depth_to_space` and `tf.space_to_depth` support `data_format='NCHW'` on GPU. However, [`_SpaceToDepthGrad`](https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/python/ops/array_grad.py#L626) and [`_DepthToSpaceGrad`](https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/python/ops/array_grad.py#L633) are not aware of `data_format`. Maybe they would need to propagate `op.get_attr('data_format')`.

### Source code / logs

``` python
import tensorflow as tf
x = tf.zeros([1, 4, 1, 1])
y = tf.depth_to_space(x, 2, data_format='NCHW')
# ValueError: Dimension size must be evenly divisible by 2 but is 1 for 'gradients ...
g = tf.gradients(y, x)
```

**Comment by asimshankar** [comment]
Thanks for the report, this indeed seems to be an oversight in https://github.com/tensorflow/tensorflow/commit/4d69d0408da946096163ee1d8ea068ae6698ae9d which introduced `data_format`.

@yzhwang @wujingyue : Could you take a look?
