### ISSUE TITLE
Issue with installing TensorFlow with pip

### ISSUE THREAD

**Issue by travek** [tensorflow/tensorflow#14249]
Hi!

I'm using Python 3.6.3
I'm trying to install TensorFlow using:
_pip3 install --upgrade tensorflow_

I get the following error:
_Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versi
ons: )
No matching distribution found for tensorflow_

Could someone help to fix this?

**Comment by asimshankar** [comment]
@av8ramit will have details on Python 3.6 support.

**Comment by travek** [comment]
Additionally I downloaded .whl file
tensorflow-1.4.0-cp36-cp36m-win_amd64.whl
and try to install it with 
_pip3 install tensorflow-1.4.0-cp36-cp36m-win_amd64.whl_
I had thefollowing error:
_tensorflow-1.4.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platf
orm._
I'm using Win7

**Comment by asimshankar** [comment]
Can you provide more details on the platform you're using? (e.g., are you using 32-bit Windows by any chance?)

**Comment by caisq** [comment]
TensorFlow has pip packages available for Python 3.6 on Linux, Mac and Win64.
https://pypi.python.org/pypi/tensorflow

**Comment by Emiller00** [comment]
Hmm I am trying to do this on macOS and I am also having issues.

**Comment by Emiller00** [comment]
I tried using a virtual environment that runs with both python 3.5 and 3.6 and pip did not work in both cases. What is going on.

**Comment by travek** [comment]
@asimshankar 
I'm using Win7 64 bit.
Python 3.6.3
The issue is still actual, can't install using pip

**Comment by travek** [comment]
@caisq 
I already tried to install from package:
Additionally I downloaded .whl file
tensorflow-1.4.0-cp36-cp36m-win_amd64.whl
and try to install it with
pip3 install tensorflow-1.4.0-cp36-cp36m-win_amd64.whl
I had thefollowing error:
tensorflow-1.4.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platf
orm.

**Comment by travek** [comment]
All,
closing the issue. I made a mistake and install 32 bit python. With 64 it's OK
