### ISSUE TITLE
'MultivariateNormalDiag' object has no attribute 'pdf' ERROR

### ISSUE THREAD

**Issue by psanch21** [tensorflow/tensorflow#14261]
Hi,

I am trying to use tf.contrib.distributions.MultivariateNormalDiag 
 as explained  in the API https://www.tensorflow.org/versions/r0.12/api_docs/python/contrib.distributions/multivariate_distributions 

- macOS High Sierra
- **TensorFlow version**: v1.3.0-rc2-20-g0787eee 1.3.0
- **Python version**:  Python 3.6.1

Here is the code that throws the error:

	mu1 = tf.to_float(tf.fill([batch_size, z_dim], 0))
	diag_stdev1 = tf.to_float(tf.fill([batch_size, z_dim], 1))

	dist1 = tf.contrib.distributions.MultivariateNormalDiag(mu1, diag_stdev1)

	mu2 = tf.to_float(tf.fill([batch_size, z_dim], -1))
	diag_stdev2 = tf.to_float(tf.fill([batch_size, z_dim], 1))

	dist2 = tf.contrib.distributions.MultivariateNormalDiag(mu2, diag_stdev2)

	z_gmm = dist1.pdf(z) + dist2.pdf(z)

And the error I get is: 
AttributeError: 'MultivariateNormalDiag' object has no attribute 'pdf'

Does anybody have the same problem?
Thank you for you time.

**Comment by asimshankar** [comment]
It seems you were looking at the documentation for release 0.12 but running 1.3.
Note that, as per [semantic versioning](http://semver.org/) followed [by TensorFlow](https://www.tensorflow.org/programmers_guide/version_compat) - there were no API stability guarantees for versions prior to 1.0

If you're using release 1.3, then please refer to the [documentation for that version](https://www.tensorflow.org/versions/r1.3/api_docs/python/tf/contrib/distributions/MultivariateNormalDiag), which mentions that there is no `pdf` field/function.

Hope that helps.
Please feel free to re-open if I'm mistaken.

Thanks.

**Comment by psanch21** [comment]
Thank you for your response. It helps me a lot!
