### ISSUE TITLE
Is CentOS 6.5 supported?

### ISSUE THREAD

**Issue by StevenHuang4321** [tensorflow/tensorflow#1426]
I have try each method in installation guide to install GPU-tensorflow in my centos 6.5 server?
However, the error below is still exists.
`ImportError: /lib64/libc.so.6: version GLIBC_2.14 not found (required by /usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so)`
Is there anyone who've successfully installed tensor flow in centos 6.5?

**Comment by thinxer** [comment]
You should build from the source code.
The pre-built binary may not work for older glibc. CentOS 6.5 has glibc 2.12 which IS too old for the pre-built binary.

**Comment by StevenHuang4321** [comment]
@thinxer Thanks for you reply.
I also try to build from source, but it failed again, it seems that it could be related to brazel, 
could you please elaborate the steps to build tensor flow including the version of brazel.

**Comment by thinxer** [comment]
I have no experience building TF on CentOS 6. I guess you need a compiler capable of C++11 features to begin with, such as GCC 4.8+.

**Comment by girving** [comment]
You'll need to provide more information if you want help.  If the build failed, what was the error message, and which compiler are you using?  You'll definitely need a C++11 capable compiler.

**Comment by StevenHuang4321** [comment]
@girving Below is the complete information
 `$ python
Python 2.7.11 (default, Mar  5 2016, 20:08:04)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 50, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/framework_lib.py", line 62, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 40, in <module>
    from tensorflow.python.framework import versions
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/versions.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: symbol memcpy, version GLIBC_2.14 not defined in file libc.so.6 with link time reference`

**Comment by StevenHuang4321** [comment]
@thinxer I am using gcc 4.9.2.

**Comment by thinxer** [comment]
This error seems to be from importing. Please paste your error on compiling from source.

**Comment by thinxer** [comment]
So you have compiled from source successfully but cannot load it from Python?

It seems that your Python is compiled from a lower version of GCC which uses GLIBC_2.12, but the built tensorflow binary uses GLIBC 2.14.

You may try LD_PRELOAD glibc 2.14, which should be found within your GCC 4.9 installation.

**Comment by rdipietro** [comment]
See https://github.com/bazelbuild/bazel/issues/760. Right now it requires customizing CROSSTOOL, but someone on the bazel team is trying to come up with a fix so that custom gcc envs are recognized and handled automatically.

**Comment by rdipietro** [comment]
Also the LD_PRELOAD option isn't so great because it'll mess with other things. For example I use IPython, and using a different glibc leads to a memory leak with quick infinite consumption.

**Comment by girving** [comment]
I'm going to close this since it appears to be a bazel issue.  Please reopen if you think there's a fix on the TensorFlow side.

**Comment by fbordignon** [comment]
I've compiled from source python 3.5 glibc 2.14 and gcc 6.2. Installed the glibc and gcc in my home directory with ./configure --prefix=~/libs. For python I did an altinstall, so now I have python 2.6 for centos to use and python 3.5 at the same time with different binaries i.e. python and python3.5 commands.
Now I have a script that puts my glibc and libstdc++ in the LD_LIBRARY_PATH before runing python3.5
Downloaded libcudnn 5.1 for cuda 7.5 from nvidia developers page and added to the ~/libs folder
I've installed cuda 7.5 from the cuda repo, hence I have nvidia driver version 352.99, cuda toolkit and everything related to cuda taken care by yum.

But when I run any tensorflow example or simple session to add 10+32 I get stuck at:

`I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0)`

with 0% of GPU utilization and python3.5 using almost all GPU memory

I'm using a GTX970
uname -a gives
Linux jigsaw 2.6.32-504.23.4.el6.x86_64 #1 SMP Tue Jun 9 20:57:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Anything you guys can do for me?

**Comment by zym1010** [comment]
I have succeeded in compiling a GPU, Python 3.5 version of TensorFlow 0.10.0 on a CentOS 6 Docker, and it ran well on our university's CentOS 6 cluster. Check <https://github.com/leelabcnbc/DevOps/tree/master/Docker>. Basically, it's replacing some hardcoded lines in CROSSTOOL-related items, and adding `-lm` to everything. I think Google can make compiling TensorFlow on CentOS less frustrating, if they make some hardcoded stuff link to correct locations.

**Comment by i3v** [comment]
I [was able](https://github.com/tensorflow/tensorflow/issues/110#issuecomment-265431453) to build tensorflow 0.12rc0 on CentOS6.5 without having root privileges, and it seem to work OK with glibc 2.12, without any `LD_LIBRARY_PATH` or `LD_PRELOAD` tricks. It looks like the key is to statically link necessary libraries, e.g. with `-lm`, like it was [just mentioned](https://github.com/tensorflow/tensorflow/issues/1426#issuecomment-250024253) by @zym1010  (I've also added `-lrt`).

**Comment by jimht011** [comment]
@i3v and @zym1010   When you compile the tensorflow, which version of bazel you installed in your box?
Very appreciate your answer

**Comment by i3v** [comment]
@jimht011
I've used bazel-0.4.1, just because it was the latest at that time. And bazel-0.4.0 few days before that (for just the same reason).
