### ISSUE TITLE
tf.layers generates an extra op when not specifying the name

### ISSUE THREAD

**Issue by wryoung412** [tensorflow/tensorflow#14265]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
pip install
- **TensorFlow version (use command below)**:
v1.4.0-rc1-11-g130a514 1.4.0
- **Python version**: 
3.5.2
- **Bazel version (if compiling from source)**:
NA
- **GCC/Compiler version (if compiling from source)**:
NA
- **CUDA/cuDNN version**:
8.0.61
- **GPU model and memory**:
GeForce GTX 1080 Ti, 11GB
- **Exact command to reproduce**:

### Describe the problem
When using tf.layers, I notice that an extra op is generated when not specifying the name. 

For example, here is an example using tf.layers.dense. "dense_1" is an extra op. Similar problem has been observed for tf.layers.conv2d also. 
```
x = tf.placeholder(tf.float32, [None, 16], name='x')
hidden = tf.layers.dense(x, 32)
hidden = tf.layers.dense(hidden, 32)
y = tf.layers.dense(hidden, 1, name='y')
```
The graph in tensorboard is as follows. 
![image](https://user-images.githubusercontent.com/13603534/32421364-b057853e-c24c-11e7-8aa7-865a42fc22ee.png)

If I add the name, 
```
x = tf.placeholder(tf.float32, [None, 16], name='x')
hidden = tf.layers.dense(x, 32, name='h1')
hidden = tf.layers.dense(hidden, 32, name='h2')
y = tf.layers.dense(hidden, 1, name='y')
```
then the graph looks as expected,
![image](https://user-images.githubusercontent.com/13603534/32421378-daedd956-c24c-11e7-9487-ecf9ed0d8027.png)

**Comment by angersson** [comment]
@fchollet Could you take a look at this?

**Comment by fchollet** [comment]
I believe this is the same issue as https://github.com/tensorflow/tensorflow/issues/13429

It sounds like a variable scope issue?

**Comment by facaiy** [comment]
I think @fchollet is right . The best solution is to specify name by yourself nowadays.

**Comment by wryoung412** [comment]
@facaiy thanks for confirming this. Not really a big issue. Just to make sure I am using it properly.

**Comment by angersson** [comment]
This appears to be resolved. I'm closing the issue to keep the tracker focused. Feel free to reopen if needed.
