### ISSUE TITLE
Tensorflow splitting?

### ISSUE THREAD

**Issue by abhigenie92** [tensorflow/tensorflow#14266]
I want to split tensor into two parts:   
 
    ipdb> mean_log_std
    <tf.Tensor 'pi/add_5:0' shape=(?, 2) dtype=float32>
  
Context: ? is for number of samples and the other dimension is 2. I want to split along the second dimension into two tensorflow of shape 1 along that dimension.

What I tried?(https://www.tensorflow.org/api_docs/python/tf/slice)
 
    ipdb> tf.slice(mean_log_std,[0,2],[0,1])
    <tf.Tensor 'pi/Slice_6:0' shape=(0, 1) dtype=float32>
    ipdb> tf.slice(mean_log_std,[0,1],[0,1])
    <tf.Tensor 'pi/Slice_7:0' shape=(0, 1) dtype=float32>
    ipdb>

I would expect the shape to be (?,1) and (?,1) for the above two splits.

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
