### ISSUE TITLE
opencv cannot read any image with tensorflow

### ISSUE THREAD

**Issue by stereomatchingkiss** [tensorflow/tensorflow#14267]
It is the same issue as #1924, since the bug is closed, I open a new one, because this bug haven't been solved yet.

From subashp

> I am using the TF 1.4 and linking against C++ code. Below code always says it failed to read the file. I have incorporated above suggestions and it doesnt make any difference. Thoughts/suggestions?

```
cv::String pathImg = argv[1];
cv::Mat img = cv::imread(pathImg, CV_LOAD_IMAGE_COLOR | CV_LOAD_IMAGE_ANYDEPTH);
if (img.empty()) {
error("Failed to read the file {}", argv[1]);
return -1;
}

```

From rmmal

> we cloned the latest version of tensorflow and still there is a problem of reading images using opencv , everytime i initiate a TENSOR object the opencv doesn't work.

From me, using tensor1.4, build from source

```
#include <opencv2/core.hpp>
#include <opencv2/highgui.hpp>

//unable to read any image if I include this header, no matter
//it before or after opencv
#include <tensorflow/cc/ops/const_op.h>

#include <iostream>

int main(int argc, char *argv[])
{
    cv::Mat input_mat = cv::imread(argv[1], cv::IMREAD_COLOR);
    std::cout<<argv[1]<<", size:"<<input_mat.size()<<std::endl;    
}

```

**Comment by allenlavoie** [comment]
This sounds like the same issue as https://github.com/tensorflow/tensorflow/issues/13278. Could you add a comment there describing how you're building (Bazel? Linking against libtensorflow_framework.so? Linking against the C++ API .so?)? TensorFlow needs to use image libraries, but it's possible we can hide the symbols in some cases.

**Comment by stereomatchingkiss** [comment]
@allenlavoie 

>how you're building (Bazel? Linking against libtensorflow_framework.so? Linking against the C++ API .so?)?

I build tensorflow libs by Bazel

1. Clone tensorflow from https://github.com/tensorflow
2. Install require dependencies
3. bazel build //tensorflow:libtensorflow.so
4. Link to cuda, -L/usr/local/cuda-8.0/lib64 -lcuda -lcudart -lcurand -lcublas -lcudnn -lcusolver -lcufft
5. Link to protof and tensorflow, -L/usr/local -lprotobuf -ltensorflow_framework -ltensorflow_cc
6. Link to opencv, -L/usr/local/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs -lopencv_video -lopencv_videoio
6. Compile and run, images always empty

> TensorFlow needs to use image libraries, but it's possible we can hide the symbols in some cases.

Could we separate images loading part as another module, make it as an independent lib? Let the users select they want to build it or not.

**Comment by allenlavoie** [comment]
If you're using the C++ API, you shouldn't need to link against libtensorflow_framework.so directly. Does it work if you take "-ltensorflow_framework" out?

**Comment by stereomatchingkiss** [comment]
@allenlavoie 

>Does it work if you take "-ltensorflow_framework" out?

It will pop out a lot of undefined symbol when compile

**Comment by allenlavoie** [comment]
@stereomatchingkiss which symbols? We'd like the C/C++ APIs (libtensorflow.so/libtensorflow_cc.so) to be usable on their own, and those have a linker script so that they don't expose extra symbols (preventing issues like the one you've reported).

**Comment by stereomatchingkiss** [comment]
@allenlavoie 

> Which symbols

Many of them(1270), I put the records at [pastebin](https://pastebin.com/jmLBncx8)

**Comment by allenlavoie** [comment]
This seems to be the main problem:
```usr/bin/ld: warning: libtensorflow_framework.so, needed by /home/ramsus/Qt/3rdLibs/tf_test/lib/libtensorflow_cc.so, not found (try using -rpath or -rpath-link)```

libtensorflow_framework.so should be accessible from libtensorflow_cc.so (in the same directory). As long as that's true and you stick to the C++ API it should work.

**Comment by stereomatchingkiss** [comment]
@allenlavoie 

I use rpath to specify the folder, this time all of the compile time error gone(if I do not call tensorflow::graph_def), but the images read by cv::imread remain empty.

However, create tensorflow::graph_def still got error

> /usr/bin/ld: tensorflow_obj_detect_example.o: undefined reference to symbol '_ZN10tensorflow8GraphDefD1Ev'
> /home/ramsus/Qt/3rdLibs/tf_test/lib/libtensorflow_framework.so: error adding symbols: DSO missing from command line

**Comment by allenlavoie** [comment]
@skye might know whether GraphDef should be in the C++ API.

But you could you verify that cv::imread works if you don't link in the TF C++ API, and doesn't work if you do link it in (making sure you're only linking to that and no other TF libraries)? This would be very surprising, since there's a linker script to control the symbols it exports. Basically we've already split the image reading part into an independent lib (libtensorflow_framework.so) that you don't need to link against.

**Comment by stereomatchingkiss** [comment]
@allenlavoie 

>But could you verify that cv::imread works if you don't link in the TF C++ API, and doesn't work if you do link it in (making sure you're only linking to that and no other TF libraries)? 

As long as I do not link to tensorflow library, cv::imread can read the image without any issue.
If I link to tensorflow library but do not include any tensorflow header, cv::imread still able to read the image.

**Comment by allenlavoie** [comment]
Ah, so it's not a symbol conflict (and splitting up our shared objects wouldn't help). Interesting. Maybe a ```#define```? I'd think the compiler would complain about most other header issues.

**Comment by stereomatchingkiss** [comment]
@allenlavoie 

I set the option -Wall, most of the worning are related to unused parameter. The header "#include <tensorflow/cc/ops/const_op.h>" will cause imread always return empty image

[Complete warning message](https://pastebin.com/r0arZUt8)

**Comment by allenlavoie** [comment]
Yeah, those warnings all look fine. The next step would be to narrow down and figure out which transitively included header from const_op.h is causing problems; any interest?

**Comment by stereomatchingkiss** [comment]
@allenlavoie  My tracking history

1. <tensorflow/cc/ops/const_op.h>
2. <tensorflow/cc/framework/ops.h>
3. <tensorflow/core/framework/tensor.h>
4. <tensorflow/core/lib/core/refcount.h>

As long as I include recount.h, the image return by imread will become empty. However, include <tensorflow/core/platform/logging.h> do not effect the resutls, this is weird. Do not looks like it is caused by #define.

**Comment by kikushah** [comment]
@allenlavoie 
Hi,

I have a similar problem as well, although its surprising. I am not using cv in my project. I just trained a network on python and am trying to load the graph on a C++ project. I am trying to link libtensorflow_cc to my c++ project (building with cmake). It fails during linking - undefined reference to symbol '_ZN10tensorflow8GraphDefD1Ev'
/usr/local/lib/libtensorflow_framework.so: error adding symbols: DSO missing from command line.



Any help would be highly appreciated.

**Comment by stereomatchingkiss** [comment]
Link with libtensorflow_framework.so should solve the issue

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-25 18:46 GMT+08:00 kikushah <notifications@github.com>:

**Comment by bitzy** [comment]
Encountered the same problem. Is there any solution? 
I am using tensorflow 1. & opencv 3.2.0 in Ubuntu 16.04.
The bazel version is 0.6.1,
and the tensorflow compile command is: ` bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --config=cuda tensorflow:libtensorflow_cc.so`

**Comment by kxhit** [comment]
Hi, I meet the same problem. Is there any solution?
I am using tensorflow r1.4 and opencv3.1 in ubuntu14.04.
As far as I include #include <tensorflow/core/public/session.h> or #include "tensorflow/cc/ops/standard_ops.h" I cannot read image. When I didn include these tensorflow files, I can read frame successfully. Anyone could help me? Thanks a lot!!!
my cpp file:
#include <tensorflow/core/platform/env.h>
//#include <tensorflow/core/public/session.h>
//#include "tensorflow/cc/ops/standard_ops.h"
#include <opencv2/opencv.hpp>
#include <iostream>
using namespace std;
using namespace tensorflow;

int main()
{
    cv::VideoCapture cap;
    if(!cap.open("/home/kx/project/RM-dataset/01.avi")){
        std::cout<<"cannot open video "<<std::endl;
    }
    cv::Mat frame;
    while(1){
        cap>>frame;
        if(frame.empty()){
            std::cout<<"no frame"<<std::endl;
            continue;
        }
        cv::imshow("frame",frame);
        cv::waitKey(0);
    }
    return 0;
} 

my cmake file:

 cmake_minimum_required (VERSION 2.8)
 project (tf_example)

 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -std=c++11 -W")
 find_package(OpenCV 3.1.0 REQUIRED)
 include_directories(
         /home/kx/something/tensorflow-r1.4
         /home/kx/something/tensorflow-r1.4/tensorflow/bazel-genfiles
         /home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/gen/protobuf/include
         /home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/gen/host_obj
         /home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/gen/proto
         /home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/downloads/nsync/public
         /home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/downloads/eigen
         /home/kx/something/tensorflow-r1.4/bazel-out/local-py3-opt/genfiles
         ${OPENCV_INCLUDE_DIRS}
         )

 add_executable(tf_test  tf_test.cpp)
 target_link_libraries(tf_test
         /home/kx/something/tensorflow-r1.4/bazel-bin/tensorflow/libtensorflow_cc.so
         /home/kx/something/tensorflow-r1.4/bazel-bin/tensorflow/libtensorflow_framework.so
         ${OpenCV_LIBS}
         )

**Comment by allenlavoie** [comment]
@stereomatchingkiss sorry, got a bit distracted. Is the claim that "#include <atomic>" is causing the issue? Everything else in that file is in a namespace, so I don't see how it could cause an issue.

**Comment by stereomatchingkiss** [comment]
@allenlavoie Me neither. Whatever, we prefer another tool for our jobs.

Tensorflow is the most popular deep learning library, got rich features, huge community, support by the most brilliant engineers hired by google, amazing tensorboard, tensorflow have a lot of pros, but it got obvious drawback too(no perfect library, just pick the one suit your need)

1. Very complicated dependencies and build system, I do not know why google prefer bazel but not cmake, cmake never break the build process of our projects, but bazel do

2. Api of tensroflow are far too complicated compared with keras and pytorch.Especially pytorch, it is much easier to debug and describe complicated network architectures by pytorch, everything are modularize and works just like numpy and python, you do not need to learn tons of new concepts when using pytorch, just some basic and you are good to go.

3. Deployment steps are non-trivial and not yet mature, like the bugs we encountered in this post

Almost everything in tensorflow need us spend lots of times to pick up new concepts, tons of times to study, tensorflow keep telling us "deep learning is super hard", while keras and pytorch show us how easy deep learning could be.

I do not what the other thinks, these are the major drawback I found in tensorflow.

**Comment by allenlavoie** [comment]
I'm guessing this is only an issue on later versions of OpenCV? I tried with 2.4 (since that was what the package manager had) and it seems to work fine including standard_ops.h.

Can someone check for me whether it's just `#include <atomic>` causing the issue in OpenCV 3.1/3.2? In which case this seems like it's an OpenCV issue rather than something TensorFlow can address.

**Comment by bitzy** [comment]
@allenlavoie 
It's wired!
I'm using opencv 2.4.13.2. I cann't use `imread` to load image if I add the tensorflow's include file path & link lib to the compile command. 

But when I using opencv 3.2.0. I can add the tensorflow's include path & link lib to the compile command and load file normally except define ` SessionOptions sessOptions;` variable.

**Comment by allenlavoie** [comment]
@bitzy Right, that's a symbol conflict. My original comments in this thread were incorrect; you do need libtensorflow_framework.so for protocol buffers right now, and that's the one with symbols which conflict with OpenCV. The eventual solution is going to be for us to split out a third shared object with just the protocol buffer symbols for use with the C++ API (which I believe @gunan is considering anyway).

In the meantime, as long as you're not using any custom ops you can build libtensorflow_cc.so with `bazel build --config=monolithic`, which will condense everything together into one shared object (no libtensorflow_framework dependence) and seal off non-TensorFlow symbols. That shared object will have protocol buffer symbols.

**Comment by bitzy** [comment]
@allenlavoie 

Now I can load image with opencv. Thanks!

**Comment by gunan** [comment]
Looks to be resolved?
I will close the issue now, but please reopen if there are still things to address.

**Comment by kxhit** [comment]
Hi! I meet the same problem.
I'm using opencv3.1 tensorflow1.4 in ubuntu14.04. When I included tensorflow headers like #include <tensorflow/core/public/session.h> or #include "tensorflow/cc/ops/standard_ops.h", cv::imread can not read images encoded by JPEG, but can read other encoding images like Uncompressed 8-bit RGB. When I commented TF headers, I can read any images by cv::imread. Is there any solution? Thanks a lot!!!  @allenlavoie @bitzy

**Comment by allenlavoie** [comment]
@kxhit 
Neat, so headers aren't causing issues on their own for you?

1. That's a reasonable guess; I've never tracked down exactly which image library in TF conflicts. 
2. Custom ops are the main limitation (since they need symbols which are sealed off from the C++ API; typically they'd link against libtensorflow_framework directly, but if that's not built then there's no good way to support them); you can use everything else in the C++ API. libtensorflow_framework does have lots of other undocumented/internal symbols which get sealed off from the C++ API, but most likely aren't super useful.
3. Yes, we'd like to split off our protocol buffers into another shared object. C++ API users could then link against libtensorflow_cc and e.g. libtensorflow_protobufs rather than relying on the metaphorical junk drawer which is libtensorflow_framework for protocol buffer symbols. I think this should be feasible, since we already have header-only protobuf rules (they need to live in exactly one .so, so we already need to exclude them from language bindings).

**Comment by kxhit** [comment]
@allenlavoie 
Yes! I can read any images with headers `#include <tensorflow/core/public/session.h>  #include "tensorflow/cc/ops/standard_ops.h"`. Thank you for your help!

**Comment by RoboEvangelist** [comment]
Hi, is this also a problem in tensorflow 1.5.0? upgrading takes a long time, so I don't want to do it if it also has the same problem :-(

**Comment by andpol5** [comment]
@RoboEvangelist I am having the same issue in tensorflow r1.5 as well.

**Comment by ashokbugude** [comment]
I have the same issue with tensorflow 1.7 . Has anyone found solution ?

**Comment by svetlov** [comment]
@allenlavoie is there any workaround to build custom ops, which using opencv? cv::resize seems to work, but cv::imread/cv::imdecode always return empty matrix, if it used inside custom op.

**Comment by allenlavoie** [comment]
@svetlov for sure, you can link your custom op .so against a second .so which does not link against libtensorflow_framework.so (and doesn't include TensorFlow headers, since the symbols won't be defined). There's [one contrib op doing basically this](https://github.com/tensorflow/tensorflow/blob/f610284f878b341423bde42afc90f917c337138c/tensorflow/contrib/tensor_forest/BUILD#L408). The second .so won't see any TensorFlow symbols and so won't have a problem calling OpenCV.

**Comment by ruanjiandong** [comment]
I hit the same issue. I can't use "monolithic" workaround since it breaks TensorRT integration. The conflicts are jpeg_CreateDecompress and jpeg_CreateCompress. libopencv_imgcodec expects to import from libjpect.so.8, but it somehow picked up from libtensorflow_framework. 

I solved it by compiling tensorflow jpeg with "-fvisibility" flag. The change is around line 41 in thirdparty/jpeg/jpeg.BUILD. "-fPIC" is needed as the result of "-fvisibility".
    "//conditions:default": [
        "-fvisibility=hidden -fPIC"
    ],  

There are some linking warnings for undefined dynamic symbol in tensorflow/contrib/lite/toco/toco, which I don't use.

**Comment by muyue1238** [comment]
Ran into the same problem while I'm trying to load a cv::Mat data to a tensor following this [page](https://stackoverflow.com/questions/39379747/import-opencv-mat-into-c-tensorflow-without-copying), imread() can not load any image. I even can't find out what caused the problem. It solved fine following @kxhit 's solution.

**Comment by esconda** [comment]
Same for me too, Unfortunately "Videcapture" function camera does not work with tensorflow libraries.I use Python for programming and using tegra k1 embedded Nvdia controller card.Tensor flow version is TF 0.8 and opencv version is 2.4.13 .These versions are correctly working on this embedded platform but unfortunately does not work together.Could you please help me about this problem.

**Comment by allenlavoie** [comment]
@zgsxwsdxg which platform, which OpenCV version, which TF commit hash, and are you linking to anything besides libtensorflow_cc.so? Those symbols should be locked down pretty well (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tf_exported_symbols.lds or https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tf_version_script.lds depending on the platform).

**Comment by zgsxwsdxg** [comment]
@allenlavoie  Thanks for your reply. 

platform: ubuntu16.04 LTS
opencv: 3.1
tensorflow: rc1.3
cuda：8.0
cudnn：6.0

I only link opencv’libs besides libtensorflow_cc.so for my project.

In addition when I build libtensorfow_cc.so with “--config=monolithic” option，one warning occurs as follow："WARNING: Config values are not defined in any .rc file: monolithic"

What should I do with the warning？

Does this have an impact on the question between tensorflow and opencv？

Look forward to your reply. Best wishes.

**Comment by WarmDay** [comment]
@allenlavoie use "-c opt --config=monolithic”

**Comment by chdzhen** [comment]
opencv3.4.6 tensorflow1.4 on MacOS is ok, the same libs on unbuntu16.04 is not ok . so I try this code "bazel build --config=monolithic :libtensorflow_cc.so"
