### ISSUE TITLE
changes in  ops_to_register.h file does not effect resulting compilation 

### ISSUE THREAD

**Issue by eli99999** [tensorflow/tensorflow#14275]
------------------------

### System information
- **Have I written custom code (https://github.com/tensorflow/tensorflow/issues/14215)**:
- **OS Platform and Distribution (Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source )**:
- **TensorFlow version (1.4)**:
- **Python version  2.7: 
- **Bazel version (0.7.0)**:

### Describe the problem
I have been running print_selective_registration_header to produce libtensorflow_inference.so
for android as described in : tensorflow/tensorflow/python/tools/print_selective_registration_header.py
i saw that ops_to_register.h was created correctly but the resulting    libtensorflow_inference.so did not work in android and there were always missing kernel ops errors,
i repeated the process with a few different graphs and i have noticed that the ops_to_register.h is being updated but there were no changes in the resulting libtensorflow_inference.so file.
i have tried all the possible bazel clean option and bazel dump thinking it is a bazel caching issue.
none helped ,
i opened this issue thinking it is an android bug :https://github.com/tensorflow/tensorflow/issues/14215
and closed it once i understood that the issue is that the result of the bazel build is worng

can anyone check this out?

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it looks like a configuration-related build issue. There is also a larger community that reads questions there. Thanks!
