### ISSUE TITLE
Cannot interpret feed_dict key as tensor: tensor tensor(import/input:0, shape=(1, 299, 299, 3), dtype=float32) is not an element of this graph.

### ISSUE THREAD

**Issue by indra215** [tensorflow/tensorflow#14276]
I'm running `label_image.py` given at [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/label_image.py](url) on `inception_resnet_v2` frozen graph. When I run this code it's giving me the following error
`cannot interpret feed_dict key as tensor: tensor tensor(import/input:0, shape=(1, 299, 299, 3), dtype=float32) is not an element of this graph.`

But when I print the tensors, there exists the above tensor in the graph. Could anyone please help me with this ? Thanks in advance.

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
