### ISSUE TITLE
Cannot interpret feed_dict key as tensor: tensor tensor(import/input:0, shape=(1, 299, 299, 3), dtype=float32) is not an element of this graph.

### ISSUE THREAD

**Issue by indra215** [tensorflow/tensorflow#14279]
I'm running `label_image.py` code given at [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/label_image.py](url) for inference on an image using InceptionV3 model trained on my own dataset. But it's giving the following error

> Cannot interpret feed_dict key as tensor: tensor tensor(import/input:0, shape=(1, 299, 299, 3), dtype=float32) is not an element of this graph.

Could anyone please help me with this issue ? Thanks in advance.

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
