### ISSUE TITLE
Estimator from Keras by model_to_estimator cannot export

### ISSUE THREAD

**Issue by yjmade** [tensorflow/tensorflow#14284]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.12
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.4 or Master 

### Describe the problem
when calling model_to_estimator, the model_fn create by _create_keras_model_fn didn't set ```export_outputs``` in the returned ```EstimatorSpec```, see [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/_impl/keras/estimator.py#L182). That make it unable to export to SavedModel, the following error raised when call ```estimator.export_savedmodel()```

```
packages/tensorflow/python/estimator/export/export.py", line 193, in build_all_signature_defs
    raise ValueError('export_outputs must be a dict.')
ValueError: export_outputs must be a dict.
```

I would like contrib a PR for fixing this if is OK

**Comment by bignamehyp** [comment]
@yifeif , can you please take a look at this issue? Thanks,

**Comment by yifeif** [comment]
Thanks @yjmade. A PR is more than welcomed! Feel free to request a review from me whenever you have it ready. cc: @fchollet.

**Comment by yjmade** [comment]
PR Merged, close now
