### ISSUE TITLE
Is something wrong about slim.learning.train?

### ISSUE THREAD

**Issue by gauss-clb** [tensorflow/tensorflow#14289]
[source code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/learning.py)

My code is so complex and very very long, so I just describe my code logic.

I add two parameters `run_tensor` and `run_placeholder` to `slim.learning.train`, the `run_tensor` is the tensor I want to run and the `run_placeholder` is placeholder I need to feed. And I also add two parameters `run_tensor` and `run_placeholder` to [`train_step`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/learning.py#L456), and `train_step` is passed to `slim.learning.train`'s `train_step_fn`. So every training step, I can run `run_tensor` in the  `train_step`  function, and I'm sure I have fed the `run_placeholder`, but when I run the program, it raise an error, like:

```
Invalid argument: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape
[...]
``` 

~~I debug for long time, and find it may be the [line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/learning.py#L779)~~ 

~~I have updated tensorflow to 1.4.0, but I  find my `slim.learning.train` only use `sv.stop(threads, close_summary_writer=True)`, without `ignore_live_threads=ignore_live_threads`.~~

I find what's wrong, it is `tf.summary.scalar`, slim doesn't run `summary` op with feed_dict.
Maybe I think slim need to support feed_dict on every training step.

**Comment by bignamehyp** [comment]
This is a question better suited for StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag.
