### ISSUE TITLE
Neural Net regression in Tensorflow

### ISSUE THREAD

**Issue by deepSalva** [tensorflow/tensorflow#14282]
### Describe the problem
Hi, I am trying to perform a Neural Network in tensorflow for The Bike-Sharing-Dataset with a regresion model. I checked out the tensorflow tutorials but I couldn't find  a solution. Something's wrong with the tf.matmul() and the input and  targets matrix. 

### Source code / logs
Here is my [repository](https://github.com/deepSalva/bikes_in_tensorflow.git) and the dataset.

Thanks so much!

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by deepSalva** [comment]
Thanks for your answer. Anyway I think there is a bug in there since I can' t train the model because of the tensor shapes. Also it will be interesting if someone in the tensorflow community can show me the way to make this regression model with a hidden layer in tensorflow. I already write in StackOverflow and I got no answer...
