### ISSUE TITLE
external symbol unresolved external symbol VS2015

### ISSUE THREAD

**Issue by cuevas1208** [tensorflow/tensorflow#14293]
I have one error while trying to build my program:

### System information
Windows 10 x64 bit
TensorFlow version 1.3
Python version 3.5
cmake
visual studio 2015

- **Additional Dependencies**:
zlib\install\lib\zlibstatic.lib
gif\install\lib\giflib.lib
png\install\lib\libpng12_static.lib
jpeg\install\lib\libjpeg.lib
lmdb\install\lib\lmdb.lib
jsoncpp\src\jsoncpp\src\lib_json\Release\jsoncpp.lib
farmhash\install\lib\farmhash.lib
fft2d\\src\lib\fft2d.lib
highwayhash\install\lib\highwayhash.lib
libprotobuf.lib
tf_protos_cc.lib
tf_cc.lib
tf_cc_ops.lib
tf_cc_framework.lib
tf_core_cpu.lib
tf_core_direct_session.lib
tf_core_framework.lib
tf_core_kernels.lib
tf_core_lib.lib
tf_core_ops.dir\Release\tf_core_ops.lib
nsync\src\nsync\Release\nsync.lib
sqlite\src\sqlite-build\Release\sqlite.lib
snappy\src\snappy\Release\snappy.lib

- **Error**:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "class tensorflow::Status __cdecl tensorflow::ops::BuildWhileLoop(class tensorflow::Scope const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > const &,class std::function<class tensorflow::Status __cdecl(class tensorflow::Scope const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > const &,class tensorflow::Output *)> const &,class std::function<class tensorflow::Status __cdecl(class tensorflow::Scope const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > *)> const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<class tensorflow::Output,class std::allocator<class tensorflow::Output> > *,bool,class tensorflow::Output *)" (?BuildWhileLoop@ops@tensorflow@@YA?AVStatus@2@AEBVScope@2@AEBV?$vector@VOutput@tensorflow@@V?$allocator@VOutput@tensorflow@@@std@@@std@@AEBV?$function@$$A6A?AVStatus@tensorflow@@AEBVScope@2@AEBV?$vector@VOutput@tensorflow@@V?$allocator@VOutput@tensorflow@@@std@@@std@@PEAVOutput@2@@Z@6@AEBV?$function@$$A6A?AVStatus@tensorflow@@AEBVScope@2@AEBV?$vector@VOutput@tensorflow@@V?$allocator@VOutput@tensorflow@@@std@@@std@@PEAV45@@Z@6@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@6@PEAV56@_NPEAVOutput@2@@Z) referenced in function "class tensorflow::Status __cdecl tensorflow::`anonymous namespace'::AddBackPropLoopCounter(class tensorflow::WhileContext *,class tensorflow::Output const &,class tensorflow::Scope const &,class tensorflow::Output *)" (?AddBackPropLoopCounter@?A0xb5093d1e@tensorflow@@YA?AVStatus@2@PEAVWhileContext@2@AEBVOutput@2@AEBVScope@2@PEAV52@@Z)	tensorflow_test2	C:\Users\mcuevas\Documents\Visual Studio 2015\Projects\tensorflow_test2\tensorflow_test2\tf_cc.lib(while_gradients.obj)	1	
`

**Comment by mrry** [comment]
That symbol is defined in `tf_cc_while_loop.lib`. Can you try linking that into your project?

**Comment by cuevas1208** [comment]
For some reason my tf_cc_while_loop.lib has not been build when I ran this command: 
`cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=C:\Users\mcuevas\bin\swigwin-3.0.12\swigwin-3.0.12\swig.exe -DPYTHON_EXECUTABLE=C:\Users\mcuevas\AppData\Local\Continuum\anaconda3\envs\acsis_cpu\python.exe -DPYTHON_LIBRARIES=C:\Users\mcuevas\AppData\Local\Continuum\anaconda3\pkgs\python-3.5.2-0\libs\python35.lib -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX2

and then:

MSBuild /m:4 /p:Configuration=Release tf_tutorials_example_trainer.vcxprojdir`

Then I tried building it separably:
