### ISSUE TITLE
node placement algorithm in the source code?

### ISSUE THREAD

**Issue by xiafei1009** [tensorflow/tensorflow#1430]
I have read the whitepaper and felt very excited about the **node placement** algorithm decribed in **section 3.2**, so I tried to figure out the details from the source code. However, I cannot find the files that implement this algorithm. 
I have read the tensorflow/core/common_runtime/**Simple_placer**.h (& Simple_placer.cc) and it seems it's too "simple" to cover the algorithm descibed in the whitepaper. Other files like tensorflow/core/graph/**Graph_partition**.h (& Graph_partition.cc) didn't have that algorithm neither. And the costmodel implemented in tensorflow/core/graph/**Costmodel**.h (& Costmodel.cc), I cannot find their caller in other place.
Someone please help me?

**Comment by girving** [comment]
Please ask non-issue questions on stackexchange or the discussion list, not as Github issues.
