### ISSUE TITLE
Install Error：SSLError: hostname 'storage.googleapis.com' doesn't match either of 'accounts.google.com', '*.partner.android.com'

### ISSUE THREAD

**Issue by amirkhango** [tensorflow/tensorflow#1431]
When I use command :
"sudo pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl" 
to install Iget this error, please tell me how can I solve?

**Comment by girving** [comment]
@martinwicke: Whose the right person for pip issues?

**Comment by martinwicke** [comment]
@amirkhango Is this still an issue with 0.7.1? Or are you deliberately trying to install 0.5.0?

**Comment by amirkhango** [comment]
@martinwicke  you mean I just change 0.5.0 to 0.7.1 in that command? Though this problem is still ! Can u tell me how do you find this solution?

**Comment by zishell** [comment]
@amirkhango have you solved this problem?

**Comment by zishell** [comment]
@amirkhango 
i got it, in this site: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#sslerror-ssl_verify_failed

you can download(http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_CONTAINER_TYPE=CPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.7.1-cp27-none-linux_x86_64.whl) and 
use `pip install xxx.whl`
