### ISSUE TITLE
Feature request: add tf.decode_libsvm op

### ISSUE THREAD

**Issue by facaiy** [tensorflow/tensorflow#14313]
Hi, since libsvm format is used widespreadly to store sparse data, and is supported by many main-stream frameworks:
+ spark: [LibSVMDataSource](https://spark.apache.org/docs/2.0.0/api/java/org/apache/spark/ml/source/libsvm/LibSVMDataSource.html)
+ sklearn: [load_svmlight_file](http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_svmlight_file.html)
+ xgboost: [LibSVM format](https://github.com/dmlc/xgboost/blob/master/demo/binary_classification/README.md)

Could tensorflow support to parse libsvm format like [`tf.decode_csv`](https://www.tensorflow.org/versions/master/api_docs/python/tf/decode_csv)?

**Comment by yongtang** [comment]
@facaiy I added a very rudimentary implementation of `decode_libsvm` in PR #14330. It is pretty rough as am not sure about the api. Please take a look and comment.

**Comment by angersson** [comment]
It looks like a few developers have written their own libsvm-format parser ops [based on previous issues](https://github.com/tensorflow/tensorflow/search?q=libsvm&type=Issues&utf8=%E2%9C%93), and a PR (above, #14330) has already been opened. Neat!

**Comment by facaiy** [comment]
Nice work, thank you, @yongtang! I'd like to take a look if time allows.
