### ISSUE TITLE
C++ model Saving(after training) not generating 'modelName.meta' file for Prediction

### ISSUE THREAD

**Issue by ashokbugude** [tensorflow/tensorflow#14316]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 17.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.5.1
- **GCC/Compiler version (if compiling from source)**: 6.0.3
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

`session->Run({{"save/Const:0", newModelFile}}, {}, {"save/control_dependency"}, nullptr)`

### Describe the problem
I am trying to train a model file in C++ and save the trained model file.

when I save the model file with below command in C++

`session->Run({{"save/Const:0", 'newModelFile'}}, {}, {"save/control_dependency"}, nullptr)`

Following files are generated
1. newModelFile.index
2. newModelFile.data-00000-of-00001

But when the training and saving is done in Python with below command 

```
with tf.Session() as sess:
    tf.train.Saver(tf.trainable_variables()).save(sess, 'newModelFile')

```
Following files are getting generated
1. newModelFile.index
2. newModelFile.data-00000-of-00001
3. newModelFile.meta

As we can see 'newModelFile.meta' is not getting generated in C++

**Requirement - To do prediction in C++ from trained model file (in C++)**   

I have found the code in C++ which meets the above requirement at https://stackoverflow.com/questions/35508866/tensorflow-different-ways-to-export-and-run-graph-in-c/43639305#43639305

BUT

the code makes use of 'newModelFile.meta' file which is not generated during training in C++

1. Can I please know how to generate 'newModelFile.meta' file in C++ to use it for prediction
2. Is there any other way to make predictions in c++ from the checkpoint files 
3. Is there a way to generate .pb in c++ after training instead of generating checkpoint files so that it can directly be loaded for prediction

Stackoverflow :  https://stackoverflow.com/questions/47154881/tensorflow-c-model-savingafter-training-not-generating-modelname-meta-file

**Comment by bignamehyp** [comment]
As far as I know, you can only save metagraph in python and load it in C++.
