### ISSUE TITLE
eager module has no attributes

### ISSUE THREAD

**Issue by hemp110** [tensorflow/tensorflow#14314]
My OS is Ubuntu 16.04
Python version is 3.5
Tensorflow version is 14.0
when I tried a simple code for TF Eager module

`import tensorflow as tf`
`import tensorflow.contrib.eager as tfe`
`tfe.enable_eager_execution()`
`x = [[2.]]`
`m = tf.matmul(x, x)`

I got a error
AttributeError: module 'tensorflow.contrib.eager' has no attribute 'enable_eager_execution'
So what's wrong?

**Comment by sunreef** [comment]
From Eager [user guide](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/python/g3doc/guide.md):

> Eager execution is not included in the latest release (version 1.4) of TensorFlow. To use it, you will need to build TensorFlow from source or install the nightly builds.

**Comment by hemp110** [comment]
@sunreef Thank you!

**Comment by terminsen** [comment]
This works for me:

import tensorflow as tf
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()

**Comment by Attyuttam** [comment]
you just need to include tensorflow as tf, since enable_eager_execution() is an attribute of tensorflow itself.
