### ISSUE TITLE
Issue while importing tensorflow

### ISSUE THREAD

**Issue by divya07srivastava** [tensorflow/tensorflow#14325]
I am trying to import tensorflow in Ubuntu 14.04 having cuda 7.5 installed. I am using tensorflow 1.4. There is issue related to
 importerror: libcudart.so.8.0: cannot open shared object file: no such file or directory.
Kindly help!!
![screenshot from 2017-11-07 17-31-46 1](https://user-images.githubusercontent.com/33459515/32506944-dd8f450e-c3dd-11e7-91b8-0870e086f137.png)

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
