### ISSUE TITLE
Cannot reload tensorflow with importlib

### ISSUE THREAD

**Issue by baluyotraf** [tensorflow/tensorflow#14322]
System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
I just tried reloading tensorflow using importlib
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
tensorflow-gpu from pip
- **TensorFlow version (use command below)**:
1.3.0
- **Python version**: 
3.6.2
- **CUDA/cuDNN version**:
CUDA 8, CuDNN 6
- **GPU model and memory**:
GeForce GTX 960M, 2GB
- **Exact command to reproduce**:
import tensorflow as tf
import importlib
importlib.reload(tf)

### Describe the problem
I won't really call it a problem. I was just trying to explore some part of tensorflow by checking out some stuffs. I just thought of reloading the module but it won't work. I don't know if this is something that should work or it's just a side effect of how tensorflow is implemented. Just adding it in in case it's something that should work.

### Source code / logs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\VirtualEnv\tensorflow\lib\importlib\__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 608, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "D:\VirtualEnv\tensorflow\lib\site-packages\tensorflow\__init__.py", line 40, in <module>
    del python
NameError: name 'python' is not defined

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
