### ISSUE TITLE
Mixed precision not enabled with TF1.4 on Tesla V100

### ISSUE THREAD

**Issue by furybubu** [tensorflow/tensorflow#14327]
Hi there,

I was interested in testing my neural net (an Autoencoder that serves as a generator + a CNN as a discriminator)  that uses 3dconv/deconv layers with the new Volta architecture and benefit from the Mixed-Precision training. I compiled the most recent source code of Tensorflow 1.4 with CUDA 9 and CudNN 7.0 and cast all the trainable variables used by my conv/deconv layers to tf.float16. Also, all my input and output tensors have sizes that are multiple of 8. 

I have two issues so far:
- I do not see any substantial speed improvement, the training time is roughly similar to when using tf.float32. My understanding is that with the Volta and cuDNN 7.0, Mixed Precision should be  automatically detected by TF and hence should use Tensor Core math. Am I wrong, or is there anything I should do to enable it? FYI, I also tried the TF1.5 nighlty build, and it seems that it is even slower than my custom 1.4.
- I also noticed that the Maxpool3D layers are not supporting TF.float16 yet and need a float32 input. Any plan to change that anytime soon ?

Thanks for your support!

**Comment by angersson** [comment]
For point 1, please ask a question on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow), which is better suited for questions that are not bugs or feature requests.

For point 2, can you split it (or reword this issue) into a separate feature request?

Thanks!

**Comment by furybubu** [comment]
Sure, I just wrote a separate issue.

**Comment by yaroslavvb** [comment]
@furybubu the way to troubleshoot this would be to isolate performance problem to individual ops.
There's probably a long road of improvements ahead in order to make TF make full use of Volta architectures.

For instance, here are some microbenchmarks on V100 using Amazon/Nvidia tensorflow images: https://medium.com/@yaroslavvb/peak-performance-of-amazon-p3-instances-f2bc48f9ef71

**Comment by furybubu** [comment]
@yaroslavvb Thanks for your reply. I tried the script you wrote for your benchmark and my results seem to be fairly different from what you have. In my case, both float32 and float exhibit the same plateau around 15 Tops/s, I do not see the peaks at 87ish Tops/s like yours.
My feeling is that my tensorflow build is probably not handling half precision correctly (Like I said, I compiled 1.4rc sources with CUDA 9/CudNN 7.0 support). Would you be kind enough to share the TF build that you used for your benchmarks?

**Comment by yaroslavvb** [comment]
@furybubu 
I've used Amazon Machine Learning for CUDA 9 image (ami-60df1418), and also NVidia's NGC container (`docker pull nvcr.io/nvidia/tensorflow:17.10`). I have not observed difference on the microbenchmark for those two images.

Verbally I've been told by NVidia that getting TF to utilize Volta in NGC container required significant amount of customization from the official version, and that eventually those changes will get merged back into main tensorflow.

**Comment by furybubu** [comment]
@yaroslavvb thanks for your insight. I am guessing now my best option is to call Nvidia!

**Comment by angersson** [comment]
This appears to be resolved, so I'm closing the issue to keep the tracker focused. Feel free to re-open if needed.
