### ISSUE TITLE
DataLossError (see above for traceback): corrupted record at 46064268          [[Node: parallel_read/ReaderReadV2_2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](parallel_read/TFRecordReaderV2_2, parallel_read/filenames)]]

### ISSUE THREAD

**Issue by wangwenqi1990** [tensorflow/tensorflow#14328]
I am trying to train AlexNet from scratch through slim (https://github.com/tensorflow/models/tree/master/research/slim). 
My setup is Python 2.7.12, Tensorflow 1.0.0, in a Linux16.04 system. Below is my error report after 3 hours training.
![screen shot 2017-11-07 at 12 57 15](https://user-images.githubusercontent.com/15274537/32509450-53bbcde2-c3bb-11e7-9dcb-e5fa2eab2783.png)
A similar problem also exists when I train vgg_16 using slim. May I know how to solve this?

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ZilongZhang** [comment]
Are you kidding me? How on earth this is not a bug??????
