### ISSUE TITLE
reduce mean for gpu is not registered

### ISSUE THREAD

**Issue by raingo** [tensorflow/tensorflow#1433]
The reduce_mean [GPU implementations](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/reduction_ops_gpu.cu.cc#L44-L60) are not registered [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/reduction_ops_mean.cc), so that the reduce_mean is still placed on CPU.

Wondering if it's a negligence or intended. If it's intended, please close this.

**Comment by girving** [comment]
"accidental" may be a better word than "negligence". :)

@benoitsteiner: Want to take a look at this?

**Comment by benoitsteiner** [comment]
That was indeed a mistake on my part. Somehow I didn't checkin the kernel registration part. We should merge pull request #1457 that fixes my oversight.
