### ISSUE TITLE
Float16 not supported by Maxpool3D

### ISSUE THREAD

**Issue by furybubu** [tensorflow/tensorflow#14334]
I was trying to switch the training of my neural net to Mixed-precision but while conv/deconv3d layers are supporting the float16 type,  Maxpool3D layers still require a float32 input. Can we expect these to support float16 precision soon?

Thanks!

**Comment by bignamehyp** [comment]
We currently don't have anybody working on this. It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thanks!
