### ISSUE TITLE
tf.nn.xw_plus_b not in API docs 

### ISSUE THREAD

**Issue by MrSaad** [tensorflow/tensorflow#1434]
The method tensorflow.nn.xw_plus_b() exists but is not documented in the [online API documentation](https://www.tensorflow.org/versions/master/api_docs/python/nn.html).

**Comment by girving** [comment]
I think this is intentional: it's better to use `tf.matmul(x, w) + b` directly.  We are working to lock down our symbol exports so that only documented symbols are exported, but we're a bit lax at the moment.

**Comment by dParadiz** [comment]
`tf.nn.xw_plus_b()`  has option to name the operation while` tf.matmul(x, w) + b` has not. Is there any way around that?

**Comment by ramnath-k** [comment]
@dParadiz you can just use tf.add(tf.matmul(x, w), b, name='<name>')
