### ISSUE TITLE
[Feature Request] Add payload only compression support for TFRecord files

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#14342]
This feature request is a follow up to PR #12369 and issue #12344.

Issue #12344 raised the feature request of supporting gzipped TFRecord files. However, the compression means the TFRecord file is gzipped as a whole and the header is compressed as well.

In certain situations, it might be desirable to expose the header and only compress the payload for better visibility and lookup performance.

This issue is a feature request to support payload only compression for TFRecord files.

**Comment by bignamehyp** [comment]
Thank you very much for adding gzip and zlib to TFRecords. For payload only compression the current option is to add compressed strings to the payload. 

We currently don't have anybody working on this. It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thanks!

**Comment by bignamehyp** [comment]
Thank you very much for adding gzip and zlib to TFRecords. For payload only compression the current option is to add compressed strings to the payload. 

We currently don't have anybody working on this. It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thanks!

**Comment by yongtang** [comment]
This issue is related to PR #14599 and related comment is https://github.com/tensorflow/tensorflow/pull/14599#issuecomment-352551762

Would like to get some feedback from @asimshankar before moving forward. Maybe this issue could be closed as well?

**Comment by asimshankar** [comment]
Yeah, I think that after https://github.com/tensorflow/tensorflow/pull/15132 - we have all the necessary building blocks for this without a feature specific to the TFRecord reader. Thanks!
