### ISSUE TITLE
Not found Op type not registered 'CountExtremelyRandomStats'

### ISSUE THREAD

**Issue by smsrikanthreddy** [tensorflow/tensorflow#14358]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS sierra 10.12.6
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**: 1.3
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: 0.5.4
- **GCC/Compiler version (if compiling from source)**: 
- **CUDA/cuDNN version**:NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: 
bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=rf_quora --model_base_path=/serving/rf_model &> rf_log &

You can collect some of this information using our environment capture script:
https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

== cat /etc/issue ===============================================
Darwin xxxxxxxxxx 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

== uname -a =====================================================
Darwin xxxxxxxxxx 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy (1.13.1)
protobuf (3.4.0)
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.8)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.3.0
tf.GIT_VERSION = v1.3.0-rc2-20-g0787eee
tf.COMPILER_VERSION = v1.3.0-rc2-20-g0787eee
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
abc.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

 I am getting the following error while running bazel command in the docker container.
command ran :- 
bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=rf_quora --model_base_path=/serving/rf_model &> rf_log &error:- Not found: Op type not registered 'CountExtremelyRandomStats' in binary running on 864822af1c6c. Make sure the Op and Kernel are registered in the binary running in this process.

I tried my search with the following link but in vain. https://github.com/tensorflow/tensorflow/issues/11847

I am trying to do inference using tensorflow tensorserving, but I am getting blocked by the above error. 
Using Tensorflow 1.3 and using tensor_forest api present in tf.contrib.tensor_forest_python.
Can anyone help me with this error as it is blocking my testing. Note:- I have successfully ran tensorserving inference for mnist and inception examples models.
-- | --

### Source code / logs
2017-11-08 07:27:45.038637: I tensorflow_serving/model_servers/main.cc:147] Building single TensorFlow model file config:  model_name: rf_quora model_base_path: /serving/rf_model
2017-11-08 07:27:45.038846: I tensorflow_serving/model_servers/server_core.cc:441] Adding/updating models.
2017-11-08 07:27:45.038879: I tensorflow_serving/model_servers/server_core.cc:492]  (Re-)adding model: rf_quora
2017-11-08 07:27:45.140519: I tensorflow_serving/core/basic_manager.cc:705] Successfully reserved resources to load servable {name: rf_quora version: 1}
2017-11-08 07:27:45.140575: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: rf_quora version: 1}
2017-11-08 07:27:45.140608: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: rf_quora version: 1}
2017-11-08 07:27:45.140647: I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:360] Attempting to load native SavedModelBundle in bundle-shim from: /serving/rf_model/1
2017-11-08 07:27:45.140685: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:236] Loading SavedModel from: /serving/rf_model/1
2017-11-08 07:27:45.159712: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-11-08 07:27:45.192628: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:284] Loading SavedModel: fail. Took 51931 microseconds.
2017-11-08 07:27:45.192711: E tensorflow_serving/util/retrier.cc:38] Loading servable: {name: rf_quora version: 1} failed: Not found: Op type not registered 'CountExtremelyRandomStats' in binary running on 864822af1c6c. Make sure the Op and Kernel are registered in the binary running in this process.

**Comment by bignamehyp** [comment]
I'm not familar with rf_quora but I think CountExtremelyRandomStats op is deprecated from tensor_forest.

**Comment by smsrikanthreddy** [comment]
Hi ,
rf_quora is a directory which contains the variabels folder and protobuf files (formed using savemodel builder).  
I am not using CountExtremelyRandomStats but I am not sure whether it is being referenced or not.
I have successfully ran training and inference but if I do inference using tensorserving, then I am facing the error.

**Comment by bignamehyp** [comment]
Please double check if you have referenced CountExtremelyRandomStats, which was deprecated already.

**Comment by smsrikanthreddy** [comment]
[train_file.txt](https://github.com/tensorflow/tensorflow/files/1470326/train_file.txt)
Hi,
Ya I indeed checked it more than once.
I am attaching the my training code.
Please let me know if I need to do anything or else for any code issues.

Ran the below command in docker container.
bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=rf_quora --model_base_path=/serving/output_new &> rf_log &
Error:-
Not found: Op type not registered 'CountExtremelyRandomStats' in binary running on 864822af1c6c. Make sure the Op and Kernel are registered in the binary running in this process.
root@864822af1c6

**Comment by InsZVA** [comment]
I met this error too. And I can't find the string "CountExtremelyRandomStats" in total sources.

**Comment by smsrikanthreddy** [comment]
@InsZVA , are running in the docker container. Did u get the error in docker or any other OS?

**Comment by smsrikanthreddy** [comment]
Hi @bignamehyp,
did u get time to look.

**Comment by InsZVA** [comment]
@smsrikanthreddy Did you find something in /tensorflow/BUILD file:
in `deps` segment of `cc_binary` whose `name=libtensorflow.so`, there's no deps about contrib.
However, in /tensorflow/tools/pip_package/BUILD, there exist something about `contrib`.
So we use python, can use `tf.contrib`; but cannot use `contrib.op` when use lib

**Comment by InsZVA** [comment]
@smsrikanthreddy You can try insert two line to /tensorflow/BUILD:
cc_binary(
    name = "libtensorflow.so",
    linkopts = select({
        "//tensorflow:darwin": [
            "-Wl,-exported_symbols_list",  # This line must be directly followed by the exported_symbols.lds file
            "//tensorflow/c:exported_symbols.lds",
        ],
        "//tensorflow:windows": [],
        "//tensorflow:windows_msvc": [],
        "//conditions:default": [
            "-z defs",
            "-s",
            "-Wl,--version-script",  #  This line must be directly followed by the version_script.lds file
            "//tensorflow/c:version_script.lds",
        ],
    }),
    linkshared = 1,
    deps = [
(+)	"//tensorflow/contrib:contrib_kernels",
(+)	"//tensorflow/contrib:contrib_ops_op_lib",
        "//tensorflow/c:c_api",
        "//tensorflow/c:exported_symbols.lds",
        "//tensorflow/c:version_script.lds",
        "//tensorflow/core:tensorflow",
    ],
)

**Comment by kemusa** [comment]
Hi. I'm having the same issue but on  Linux Ubuntu 16.04 in an AWS AMI using python version 2.7. I tried adding the lines you mentioned to the file in tensorflow/BUILD but got the same result.

**Comment by smsrikanthreddy** [comment]
Hi @InsZVA ,
I tried your suggestions and accordingly,  I have updated the /serving/tensorflow/tensorflow/BUILD file with the below lines,
tf_cc_shared_object(
    name = "libtensorflow.so",
    linkopts = select({
        "//tensorflow:darwin": [
            "-Wl,-exported_symbols_list",  # This line must be directly followed by the exported_symbols.lds file
            "//tensorflow/c:exported_symbols.lds",
            "-Wl,-install_name,@rpath/libtensorflow.so",
        ],
        "//tensorflow:windows": [],
        "//tensorflow:windows_msvc": [],
        "//conditions:default": [
            "-z defs",
            "-s",
            "-Wl,--version-script",  #  This line must be directly followed by the version_script.lds file
            "//tensorflow/c:version_script.lds",
        ],
    }),
    deps = [
	"//tensorflow/contrib:contrib_kernels",
	"//tensorflow/contrib:contrib_ops_op_lib",
        "//tensorflow/c:c_api",
        "//tensorflow/c:exported_symbols.lds",
        "//tensorflow/c:version_script.lds",
        "//tensorflow/c/eager:c_api",
        "//tensorflow/core:tensorflow",
    ],
)

I don't find the cc_binary in the BUILD file.
So updated the BUILD file with above code and even after adding the two lines I got the same error.

[versions used for serving]
/serving#  git branch --list -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/gh-pages
  remotes/origin/kirilg-patch-2
  remotes/origin/master
  remotes/origin/r0.5.1
  remotes/origin/r0.6
  remotes/origin/r1.0
  remotes/origin/r1.3

**Comment by kemusa** [comment]
Hi. I'm having the same issue but on Linux Ubuntu 16.04 in an AWS AMI using python version 2.7.

I tried adding the lines that @InsZVA mentioned to the tensorflow/BUILD file in the cc_binary section but got the same result.

**Comment by InsZVA** [comment]
Hi, @smsrikanthreddy , Your tf version in this issue is 1.3.0, so you should switch to r1.3 branch and build libtensorflow.so

**Comment by kemusa** [comment]
Hi I am having the same issue but on Ubuntu 16.04 and I am running it in a docker container. I did all of the above: 

- switched to branch r1.3 (because I am running TF v1.3.0)
- Added the two additional lines you mentioned
- built libtensorflow.so (using the instructions from here:    https://malmaud.github.io/TensorFlow.jl/latest/build_from_source.html)
- And then I copied libtensorflow.so to my usr/bin directory in attempt to follow the directions from the link above. 

I am still having the same error. Is there something that I've done wrong?

**Comment by InsZVA** [comment]
@kemusa I think you should put your libtensorflow.so to your library path(such as `/usr/local/lib`, and run `ldconfig`, refer: https://www.tensorflow.org/install/install_c

**Comment by InsZVA** [comment]
I faced this error when I tried to use Go load a savedmodel I trained with Python. And I found the library other language(c, c++, go etc) use is built by the rule in BUILD files. And I addethat two lines in file and succeed. So I think if you face a error like "Op type not registered XXX", you can check whether it was built into the library you use.

**Comment by smsrikanthreddy** [comment]
Hi @InsZVA,
Thanks for your reply.

Even I am also facing the same issue as @kemusa ,

- I switched to r1.3 and updated the BUID file with the two lines 
- then built libtensorflow.so and  copied the built file to /usr/local/lib file in my docker container 
-  then ran the bazel command to serve (the random forest code attached above) but again I got 
   the same error "Op type not registered XXX".

**Comment by kemusa** [comment]
@smsrikanthreddy following up on @InsZVA's point, it seems that we need to find the build rules that add CountExtremelyRandomStats. If you look at the link below we can see the rules associate with tensorForest:
https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/contrib/tensor_forest/BUILD

I attempted to add the following lines to cc_binary[name="libtensorflow.so"].
        "//tensorflow/contrib/tensor_forest:v2_ops",
        "//tensorflow/contrib/tensor_forest:tensor_forest_v4_kernels",
        "//tensorflow/contrib/tensor_forest:tensor_forest_v4_ops_op_lib"

And then copied to /usr/local/lib. But I got the same. issue. I'll try to see what I'm doing wrong over the weekend.

**Comment by drpngx** [comment]
@ThomasColthurst WDYT?

**Comment by ThomasColthurst** [comment]
@nataliaponomareva is the current maintainer of TensorForest.

My recommendation is to use TensorFlow 1.4, from which CountExtremelyRandomStats has been completely removed.

**Comment by smsrikanthreddy** [comment]
Thanks @ThomasColthurst and @drpngx ,
After upgrading tensorflow version from 1.3 to 1.4,  issue got resolved.

**Comment by liyue201** [comment]
i used v1.5.0 and met this.
  
Op type not registered 'FertileStatsResourceHandleOp' in binary running on 74b5282c732f.
