### ISSUE TITLE
tf.name_scope() is not propagated to variables created by Keras layers

### ISSUE THREAD

**Issue by humcasma** [tensorflow/tensorflow#14361]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: YES
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.12.6
- **TensorFlow installed from (source or binary)**: BINARY
- **TensorFlow version (use command below)**: v1.4.0-rc1-11-g130a514 1.4.0
- **Python version**: 3.5.4
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
When using Keras layers in combination with `tf.name_scope(a_name)`, `a_name` is added to the name of the layers. I would also expect it to be added to the name of the weights/variables that Keras creates internally. However, that is not the case. Having an automatic way of adding a name scope to the weights is highly desirable, though.

### Source code / logs
```
with tf.name_scope("test"):
     a = tf.keras.layers.Input(shape=(5,))
     b = tf.keras.layers.Dense(5)(a)
```

_Output_:

Executing `a.name` returns `test/input_1:0` as expected. 

`tf.trainable_variables()` returns:
`[<tf.Variable 'dense/kernel:0' shape=(5, 5) dtype=float32_ref>, <tf.Variable 'dense/bias:0' shape=(5,) dtype=float32_ref>]`

**Comment by angersson** [comment]
@martinwicke, can you take a look at this?

**Comment by facaiy** [comment]
How about using ˋwith tf.variable_scope("test")`?

**Comment by roytseng-tw** [comment]
`tf.name_scope` will NOT affect the name of Variable, use `tf.variable_scope` instead.
`tf.name_scope` will affect the name of Operation and thus Tensor.

**Comment by ppwwyyxx** [comment]
`tf.variable_scope` will NOT affect the name of Variables defined by Keras.

**Comment by facaiy** [comment]
@roytseng-tw is right.

```python
import tensorflow as tf

with tf.variable_scope("test"):
     a = tf.keras.layers.Input(shape=(5,))
     b = tf.keras.layers.Dense(5)(a)
     print(tf.trainable_variables())
# output
# [<tf.Variable 'test/dense/kernel:0' shape=(5, 5) dtype=float32_ref>, <tf.Variable 'test/dense/bias:0' shape=(5,) dtype=float32_ref>]
```

**Comment by humcasma** [comment]
That is true. `tf.variable_scope` does what I was expecting from `tf.name_scope`. I guess one can combine both to have both variables and operations named. 
A more correct name for `tf.name_scope` would probably be `tf.operation_scope`, though. But probably not realistic to change now.

**Comment by facaiy** [comment]
Hi, @humcasma. In fact, `tf.variable_scope` always creates an auxiliary name scope (for convenience) when used, so it is indeed what you desired. Moreover, you are also free to combine `tf.variable_scope` with `tf.name_scope` to custom them separately.

**Comment by angersson** [comment]
This appears to be resolved (and does not seem to indicate a bug), so I'm closing the issue to keep the issue tracker focused. Feel free to reopen if needed.

**Comment by alexandervandekleut** [comment]
> @roytseng-tw is right.
> 
> ```python
> import tensorflow as tf
> 
> with tf.variable_scope("test"):
>      a = tf.keras.layers.Input(shape=(5,))
>      b = tf.keras.layers.Dense(5)(a)
>      print(tf.trainable_variables())
> # output
> # [<tf.Variable 'test/dense/kernel:0' shape=(5, 5) dtype=float32_ref>, 
> # <tf.Variable 'test/dense/bias:0' shape=(5,) dtype=float32_ref>]
> ```

When I do this it comes up empty?

![image](https://user-images.githubusercontent.com/23745329/58649766-f5cf5d80-82da-11e9-9a74-519b32046626.png)

**Comment by martinwicke** [comment]
@alexandervandekleut your code has nothing to do with scopes. `tf.trainable_variables` is a global collection, which isn't used by Keras. It's also deprecated. 

To access the variables in layers, use their `.trainable_variables` property.

**Comment by alexandervandekleut** [comment]
> @alexandervandekleut your code has nothing to do with scopes. `tf.trainable_variables` is a global collection, which isn't used by Keras. It's also deprecated.
> 
> To access the variables in layers, use their `.trainable_variables` property.

Thanks for the fast reply!

I copy and pasted code from above in this thread, which worked for them but not for me - so something has changed between then and now. Thanks for letting me know about how that works though - all of the stackoverflow answers didn't mention that.
