### ISSUE TITLE
What is the instruction of checking which version of cuda and cudnn the tensorflow is running on?

### ISSUE THREAD

**Issue by chihyuwang** [tensorflow/tensorflow#14364]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:1.4
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:8.0/6.0
- **GPU model and memory**:Tesla P100-PCIE-16GB
- **Exact command to reproduce**:

### Describe the problem

What is the instruction of checking which version of cuda and cudnn the tensorflow is running on?
like the tensorflow version could be checked by the instruction tf.__version__ .
I want to check my tensorflow 1.4 running on the 8.0 cuda and 6.0 cudnn, not running on the 9.0 cuda and 7.0 cudnn.

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
