### ISSUE TITLE
pip3 syntax error

### ISSUE THREAD

**Issue by noahu1234** [tensorflow/tensorflow#14373]
I put in the code in python but it does not work i made sure that pip3 and python is updated and installed but it gives me this:
>>> pip3 install tensorflow
  File "<stdin>", line 1
    pip3 install tensorflow
               ^
SyntaxError: invalid syntax
>>> pip install tensorflow
  File "<stdin>", line 1
    pip install tensorflow
              ^
SyntaxError: invalid syntax
>>>
>>> pip3 install --upgrade tensorflow
  File "<stdin>", line 1
    pip3 install --upgrade tensorflow
               ^
SyntaxError: invalid syntax
>>> pip3 install --upgrade tensorflow
  File "<stdin>", line 1
    pip3 install --upgrade tensorflow
               ^
(I tryed multiple times)

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
