### ISSUE TITLE
Cannot make an input layer that takes scalars with the keras functional api

### ISSUE THREAD

**Issue by vishvananda** [tensorflow/tensorflow#14384]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source (branch 1.4)
- **TensorFlow version (use command below)**: 1.4.0-dev
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 8.0/6.0
- **GPU model and memory**: nVidia 1080Ti 11G
- **Exact command to reproduce**: run the script below

### Describe the problem

The following is an attempt to use the keras functional api to make a model that accepts scalars as input:
```
import tensorflow as tf
from tensorflow.contrib.keras.api.keras.models import Model
from tensorflow.contrib.keras.api.keras.layers import Input
i = Input(batch_shape=(None, ), dtype=tf.uint8, name="input")
m = Model(inputs=i, outputs=i)
```
which fails like so:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-54-dd00bec66757> in <module>()
----> 1 i = Input(batch_shape=(None, ), dtype=tf.uint8, name="input")
      2 m = Model(inputs=i, outputs=i)

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/topology.py in Input(shape, batch_size, name, dtype, sparse, tensor, **kwargs)
    611     dtype = K.floatx()
    612   if not shape and tensor is None:
--> 613     raise ValueError('Please provide to Input either a `shape`'
    614                      ' or a `tensor` argument. Note that '
    615                      '`shape` does not include the batch '

ValueError: Please provide to Input either a `shape` or a `tensor` argument. Note that `shape` does not include the batch dimension.
```
Using a sequential model instead works fine:
```
import tensorflow as tf
from tensorflow.contrib.keras.api.keras.models import Sequential
from tensorflow.contrib.keras.api.keras.layers import InputLayer
m = Sequential()
m.add(InputLayer(batch_input_shape=(None, ), dtype=tf.uint8, name="input"))
```
Additionally using the external keras works fine:
```
import tensorflow as tf
from keras.models import Model
from keras.layers import Input
i = Input(batch_shape=(None, ), dtype=tf.uint8, name="input")
m = Model(inputs=i, outputs=i)
```
It appears that this broke when the tensor and batch_size arguments were added to the internal version.
Here is one possible way to fix it which I can propose if people are ok with it:
```
diff --git a/tensorflow/python/keras/_impl/keras/engine/topology.py b/tensorflow/python/keras/_impl/keras/engine/topology.py
index f9be782..74df725 100644
--- a/tensorflow/python/keras/_impl/keras/engine/topology.py
+++ b/tensorflow/python/keras/_impl/keras/engine/topology.py
@@ -605,21 +605,20 @@ def Input(  # pylint: disable=invalid-name
       raise ValueError('Only provide the shape OR '
                        'batch_shape argument to '
                        'Input, not both at the same time.')
-    batch_size = batch_shape[0]
-    shape = batch_shape[1:]
+  else:
+    if not shape and tensor is None:
+      raise ValueError('Please provide to Input either a `shape`'
+                       ' or a `batch_shape` or a `tensor` argument.'
+                       ' Note that `shape` does not include the batch '
+                       'dimension.')
+    batch_shape = (batch_size,) + tuple(shape)
   if kwargs:
     raise ValueError('Unrecognized keyword arguments:', kwargs.keys())
 
   if dtype is None:
     dtype = K.floatx()
-  if not shape and tensor is None:
-    raise ValueError('Please provide to Input either a `shape`'
-                     ' or a `tensor` argument. Note that '
-                     '`shape` does not include the batch '
-                     'dimension.')
   input_layer = InputLayer(
-      input_shape=shape,
-      batch_size=batch_size,
+      batch_input_shape=batch_shape,
       name=name,
       dtype=dtype,
       sparse=sparse,
```

**Comment by vishvananda** [comment]
FYI, it is not possible to model.predict() at the moment with a scalar input_shape, even though it is totally valid to put scalars into a feed_dict using session.run(). In fact, some tensorflow operations like tf.images.decode_jpeg require scalar inputs. The missing scalar support is a separate keras issue that I have reported here: https://github.com/fchollet/keras/issues/8436

**Comment by bignamehyp** [comment]
@fchollet FYI, feel free to assign this issue to others.

**Comment by fchollet** [comment]
You are supposed to specify `shape` and `batch_size` as two separate arguments. We are deprecating the `batch_shape` argument from the public API.

**Comment by vishvananda** [comment]
@fchollet I understand the desire to deprecate batch_shape but that means there is no way to define an input that takes a scalar. Are you suggesting that accepting scalar input will not be supported at all? Or are you saying that the implementation needs to be different, perhaps with a new kwarg or a special sentinel value for shape? I personally think packing scalars into 1d vectors is pretty ugly, but if the decision is keras will not support scalars, I will abide by it.

**Comment by racinmat** [comment]
@fchollet  so what is the solution here? Is there a way to define a scalar keras variable, or are we supposed to have it as vector and slice it?

**Comment by shariq-audiofocus** [comment]
In case anyone else needs help with this - My solution was to use `shape=(1,)`. Equivalently, I think, you could do `batch_shape=(batch_size,1)`
