### ISSUE TITLE
The weights argument in Keras's Embedding does not work

### ISSUE THREAD

**Issue by hsm207** [tensorflow/tensorflow#14392]
I am using Tensorflow 1.4.0.

According to this [blog post](https://blog.keras.io/using-pre-trained-word-embeddings-in-a-keras-model.html), we can use the weights argument in the call to Embedding to specify some matrix that represents a pre-trained word embeddings (see the section titled Preparing the Embedding Layer).

However, this code does not work:

```
import tensorflow as tf
import numpy as np

from tensorflow.python.estimator.model_fn import EstimatorSpec
from tensorflow.contrib.keras.api.keras.layers import Embedding, Dense
from tensorflow.contrib.keras.api.keras.initializers import Constant


def model_fn(features, labels, mode):
    x = tf.constant([[1]])
    labels = tf.constant([[10.]])
    
    # Let m be our pre-trained word embeddings
    m = np.array([[1, 2], [3, 4]], np.float32)
    with tf.name_scope('Embedding_Layer'):
        # Create an embedding layer and load m into it
        n = Embedding(2, 2, weights=[m], input_length=1, name='embedding_matrix_1', trainable=False)

    lookup = n(x)
    lookup = tf.Print(lookup, [lookup])

    preds = Dense(1)(lookup)
    loss = tf.reduce_mean(labels - preds)
    train_op = tf.train.GradientDescentOptimizer(0.01).minimize(loss, tf.train.get_global_step())

    eval_metric_ops = {'accuracy': tf.metrics.accuracy(labels, preds)}
    return EstimatorSpec(mode=mode, loss=loss, train_op=train_op, eval_metric_ops=eval_metric_ops)


model = tf.estimator.Estimator(model_fn)
model.train(input_fn=lambda: None, steps=1)
```

`lookup` should print [[3 4]] but instead random numbers are printed.

The solution is to define `n` as follows:

```
n = Embedding(2, 2, embeddings_initializer=Constant(m), input_length=1, name='embedding_matrix_1',
                      trainable=False)
```

**Comment by bignamehyp** [comment]
I think the api has been changed.  Please visit
https://keras.io/layers/embeddings/ 
for more details on Embedding constructor.

**Comment by BoPengGit** [comment]
Hi,

So what is the new syntax to load pretrained word vectors now that the weights parameter is deprecated?

Do you know @bignamehyp ?

Thanks for the help!

**Comment by Huijun-Cui** [comment]
Recently I also noted that the weights parameter is deprecated,so what is new method to use pretrained weight in embedding?

**Comment by hsm207** [comment]
@BoPengGit @Huijun-Cui I think setting `embedding_initializer` to the pretrained word vectors and setting that embedding layer's `trainable` property to `false` is the way to go.

**Comment by farmeh** [comment]
@hsm207 but how? can you provide a working example? embedding_initializer can accept custom initializers, but I do not see a way to give weights ...

**Comment by hsm207** [comment]
@farmeh are you using tensorflow 2.0?

**Comment by farmeh** [comment]
@hsm207 no, keras 2.2.4 and tensorflow 1.14.0.

**Comment by Daanielvb** [comment]
To fix the issue you must do something like this 

  from keras.initializers import Constant
  embedding_layer = Embedding(input_len, input_size, 
                              embeddings_initializer=Constant(your_embedded_matrix), trainable=False)
