### ISSUE TITLE
TF Detect app doesnt work with my own weights

### ISSUE THREAD

**Issue by phongnhhn92** [tensorflow/tensorflow#14394]
Hello guys, I followed the instruction of object detection android app and successfully run the app using the pretrained tiny-yolo-voc. 

Now I have trained another model by myself with my own dataset(1class) using Darknet. Then I convert the weights file to pb type format using the Darkflow command
`./flow --model cfg/yolo-1class.cfg --load bin/yolo-marker_1class.weights --savepb --verbalise`

Using the summerize_graph tool, I checked the yolo-marker_1class.pb has the same 'input' and 'output' node.

After i manually copy this pb file into the asset folder and click Run button, I had this error which is not happened when I build when the pretrained tiny-yolo-voc.pb
Can anyone help me please ? 
![1](https://user-images.githubusercontent.com/11288381/32594925-38e2801c-c571-11e7-8992-4cd36675fb34.png)

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
