### ISSUE TITLE
Error:Execution failed for task ':buildNativeBazel'.

### ISSUE THREAD

**Issue by YudizPayal** [tensorflow/tensorflow#14393]
This problem occured with the android example in android studio.
 ->A problem occurred starting process 'command '/usr/local/bin/bazel''

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
