### ISSUE TITLE
tutorial GPU issue

### ISSUE THREAD

**Issue by AlexGruzdev** [tensorflow/tensorflow#144]
Hi guys,
I suppose that you've got an error in tutorial, section "Create the pip package and install" ([link]
(http://www.tensorflow.org/get_started/os_setup.md#installing_from_sources)):

1) this command should create pip package:
$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package 

In order to use GPU in training you need to specify --config=cuda:
$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Comment by falcon360** [comment]
+1 I faced a similar issue and it took me a long time to realize this. It would be helpful if the docs are updated.

**Comment by vrv** [comment]
Cool, will update our docs today if I can, thanks!

**Comment by vrv** [comment]
Fixed in a recent check-in, website will be updated soon.
