### ISSUE TITLE
Cuda 3.0 not working

### ISSUE THREAD

**Issue by alex-pardo** [tensorflow/tensorflow#1440]
When installing from pip tensorflow GPU version (Linux), minimum cuda version is 3.5.
Install instructions have been changed to:
"TensorFlow GPU support requires having a GPU card with NVidia Compute Capability >= 3.0"
However, gpu_device.cc is still requiring cuda 3.5:

```
// "configure" uses the specific name to substitute the following string.
// If you change it, make sure you modify "configure" as well.
std::vector<CudaVersion> supported_cuda_compute_capabilities = {
    CudaVersion("3.5"), CudaVersion("5.2")};

}  // namespace
```

**Comment by girving** [comment]
@zheng-xq: Should this be changed to 3.0?

**Comment by Mistobaan** [comment]
@alex-pardo did you `./configure` with `TF_UNOFFICIAL_SETTINGS=1` and specified `3.0` at the cuda compute capability step ?
