### ISSUE TITLE
Failed to connect to dl.google.com port 443: Operation timed out

### ISSUE THREAD

**Issue by hbfreedow** [tensorflow/tensorflow#14407]
when I run the simple project of ios, I just run "pod install", but I get the error message of the title, however, if I copy the url "https://dl.google.com/dl/cpdc/2cf20b661cbb3374/TensorFlow-experimental-1.1.1.tar.gz" to my safari, it download speed is fast, who can help me? By the way, my ruby/cocoapods all are newest, thx.

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
