### ISSUE TITLE
can eager mode make use of multi-thread automatically?

### ISSUE THREAD

**Issue by RayXu14** [tensorflow/tensorflow#14416]
just like session mode:

config = tf.ConfigProto(device_count={"CPU": 4},
                inter_op_parallelism_threads = 1,   
                intra_op_parallelism_threads = 4,  
                log_device_placement=True)  
with tf.Session(config = config) as sess:  
...

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
