### ISSUE TITLE
cuda 8.0 is not available now on NVIDIA's website

### ISSUE THREAD

**Issue by CodeMasterYi** [tensorflow/tensorflow#14417]
latest cuda version is 9.0.x, but what tf depends on is 8.0.x! and it seems that nvidia does not provide downloading site for 8.0 now~~~
how can i solve this problem?

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ShangYuming** [comment]
Please tell me how to find cuda8.0 and cudnn5.1?
