### ISSUE TITLE
Same model behaves different when restored in Linux vs OSX

### ISSUE THREAD

**Issue by jstaker7** [tensorflow/tensorflow#1442]
Using the recent TensorFlow pip install 0.7.0 I have encountered some frustrating behavior. It might be something I'm doing wrong on my end, but I've ruled out everything I can.

Here's what's happening:
I've trained a model on a linux system using a GPU. I then scp the checkpoint file to my mac, and restored the checkpoint file into exactly the same code-base. However, the results were much poorer. Thinking I might have a bug or a bad saved model, I went back to the linux and loaded the saved model there, reran the exact same evaluation procedure using identical data, code, etc. and the results were much better once again. I don't know anything about the purpose of the ckpt.meta file, but copying this into the same directory didn't help.

Does this sound familiar at all? Again, I can't rule out a bug on my end, but everything is identical as far as I can tell, apart from the running environment (Linux+GPU vs Mac). Any ideas?

**Comment by girving** [comment]
It's impossible for us to debug this without more information.  First, though, a wild guess: what happens if you restore and test on Linux but using only CPU?  That might at least isolate it to a GPU bug.  If it does turn out to be CPU vs. GPU, can you isolate which op is problematic?

**Comment by jstaker7** [comment]
I did try disabling the GPU and that didn't seem to help. Good suggestion on trying to isolate which op... let me spend some time doing that and I'll get back to you.

**Comment by jstaker7** [comment]
OK, I think I've worked it out. I still need to do a few more tests to be sure, but it looks like it is actually another 3rd-party package I'm using that is behaving differently on the two systems. Closing this issue since the problem is in another package and Tensorflow is working great.

**Comment by girving** [comment]
To satisfy my curiosity: what was the other package?

**Comment by jstaker7** [comment]
An organic chemistry toolkit called Indigo :)
http://lifescience.opensource.epam.com/indigo/

**Comment by shoc2005** [comment]
Hi, I have the same problem with loading trained model on GPU host and loaded on CPU host (both linux Ubuntu 14.04 LTS). There is example:
on GPU - Model accuracy: 0.79
on CPU - Model accuracy: 0.16
The code and model definition is same in Python.
Unfortunately on both machines Indigo package not installed... and model loads on both host without errors.

**Comment by girving** [comment]
@shoc2005: As with the other issue, we're going to need more information.  What version of tensorflow are you using?  Can you localize the differences to a particular op?

**Comment by shoc2005** [comment]
@girving: some minutes ago I achieved the same result as in GPU on CPU host - no difference. But now I retraining my model on GPU host with last code modifications. I think this problem may be caused by pyc (python file) files...
