### ISSUE TITLE
Hard-coded gcc path

### ISSUE THREAD

**Issue by rlrs** [tensorflow/tensorflow#1443]
When compiling with GPU support, the compiler path is set in the file
//third_party/gpus/crosstool/crosstool_wrapper_is_not_gcc on line 47 to 50:

```
CPU_COMPILER = ('/usr/bin/gcc')
etc
```

which can result in using an old version on e.g. clusters where several compilers might be installed under a path such as
`/appl/gcc/5.3.0/bin/gcc`

It would be nice to be able to configure the compiler path.

Edit: This overlaps with the hard coded paths in other parts of Bazel, see for example bazelbuild/bazel#760

**Comment by girving** [comment]
It'd be good to have this as part of `configure`, but I don't know how awkward it is.  @ebrevdo: Care to comment?

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/pull/1220 might be relevant

**Comment by rdipietro** [comment]
@damienmg any thoughts?

**Comment by damienmg** [comment]
I agree, for now it should probably be part of the ./configure script. With next Bazel realease the new auto-configuration mechanism could replace it.

**Comment by ebrevdo** [comment]
+1 if we can configure via bazelrc.  Alternatively it would be great if we could set up a symlink or something similar to the way we do python

**Comment by vrv** [comment]
So what's the status of this.  Should we accept #1220 since that's going the ./configure route, or wait for bazel auto config?

**Comment by damienmg** [comment]
I think you should accept #1220, bazel auto config is going to be in next bazel release but you probably don't want to stick to the latest bazel (and also have it a bit more tested before it goes live).

**Comment by girving** [comment]
@vrv: This is fixed by #1220, right?

**Comment by vrv** [comment]
Yes.
