### ISSUE TITLE
Some errors in docker tf notebooks

### ISSUE THREAD

**Issue by cinqs** [tensorflow/tensorflow#14430]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:CentOS 7
- **TensorFlow installed from (source or binary)**: docker images
- **TensorFlow version (use command below)**: latest

### Describe the problem

it is just a documentation problem.

in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/notebooks/2_getting_started.ipynb

in section **the code again**, in the comments:

```py
    # Perform gradient descent. 
    # This essentially just updates weights, like weights += grads * learning_rate
    # using the partial derivative of the loss with respect to the
    # weights. It's the direction we want to go to move toward lower error.
    update_weights = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)
```
I do think to update weights, you should use `weights := weights - grads * learning_rate`, I think using `+=` is not a right choice

And another one is also in this section, you should use `bias_with_x` instead of `x_with_bias`

That's all.

**Comment by bignamehyp** [comment]
Thank you very much for your feedback. Feel free to submit a pull request.
