### ISSUE TITLE
GPU support for sparse_dense_binary_op_shared.cc

### ISSUE THREAD

**Issue by pierrebaque** [tensorflow/tensorflow#14441]
Are you planning to add GPU support for the operations defined in 
tensorflow/tensorflow/core/kernels/sparse_dense_binary_op_shared.cc

I see that there is a GPU version for the sparse to dense Matrix-Multiplication version 
tensorflow/tensorflow/core/kernels/sparse_tensor_dense_matmul_op.cc 

but being able to use the GPU for Component-Wise operations would be very helpful.

Thank you.

Regards,
Pierre

**Comment by angersson** [comment]
@ebrevdo, can you comment on this?

**Comment by ebrevdo** [comment]
No current plans; will leave this as contributions welcome.

**Comment by facaiy** [comment]
Hi, the issue is interesting for me. I'd like to take a try.

**Comment by pierrebaque** [comment]
That would be really useful. Let me know if you try to do it and need some help.

**Comment by facaiy** [comment]
Yes, I'd like working on it. The issue seems not difficult, however it might still take a little long time (perhaps two weeks) for me, because I'm a novice in gpu programming. Is it OK? 

Anyway, I'll tell you if I get in trouble. Thanks.

**Comment by facaiy** [comment]
Hi, I'm a little busy this week. So if anyone is interesting, you can take over the issue  :-) 
If I start, I will post here. If someone else starts first, hopefully they'll post here.
