### ISSUE TITLE
[Feature request] Improve syntax for accessing Python objects in dataset pipelines

### ISSUE THREAD

**Issue by boeddeker** [tensorflow/tensorflow#14448]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary 
- **TensorFlow version (use command below)**: 1.4.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: 

### Describe the problem

Hey, I have a python database class
```python
class MyDatabase:
    def __len__(self): return ...
    def __getitem__(self, item): return ...  # slow code without gitlock, i.e. io and numpy
```
that supports indexing and returns a dict. The loading of the data is longer than a NN iteration, therefore it would be nice when tensorflow loads the data in parallel. When I use tf.data.Dataset.from_generator I have to convert my Database to a generator
```python
def generator():
    db = MyDatabase()
    yield from [db[i] for i in range(len(db))]
```
`from_generator` has no argument `num_parallel_calls`, therefore the loading is serial.
I am not sure how difficult it is to add such an argument. 
But in the case that `MyDatabase` has above structure it is possible to combine `tf.data.Dataset.range` with `tf.data.Dataset.map` and `tf.py_func` to get a parallel load. 
In my mind, it could be easier to implement a parallel load for an indexable object.

Further point the interface of `tf.py_func` has more constraints than `tf.data.Dataset.from_generator` (dict's are not allowed and it hat no output_shape argument).

Since I am new to tensorflow and have problems to understand the `tf.data.Dataset` code, here my feature request for a `num_parallel_calls` argument in `tf.data.Dataset.from_generator` or a new function `tf.data.Dataset.from_generator` with a `num_parallel_calls` argument.

### Source code / logs

Here a toy example, that demonstrate the non-parallel from_generator

```python
import time

start = time.perf_counter()
    
def body(i):
    global start
    if i == 0:
        start = time.perf_counter()
    time.sleep(0.2)
    return np.array([float(i), time.perf_counter() - start])

def gen():
    for i in range(5):
        yield body(i)
        
ds = tf.data.Dataset.from_generator(gen, tf.float64)
ds = ds.prefetch(5)
iterator = ds.make_one_shot_iterator()

entry = iterator.get_next()

with tf.Session() as sess:
    
    try:
        while True:
            print(sess.run(entry))
    except tf.errors.OutOfRangeError:
        pass
# Serial execution:  [index, time from start of first load to return of current load]
# [ 0.          0.20034038]
# [ 1.          0.40189139]
# [ 2.          0.60322792]
# [ 3.          0.80472201]
# [ 4.          1.00612245]
```
and here the parallel version (Less nice code and does not generalise so good as from_generator, e.g. no return dict support)
```python
ds = tf.data.Dataset.range(5)

def map_func(i):
    return tf.py_func(body, [i], tf.float64, stateful=False)

ds = ds.map(map_func, num_parallel_calls=4)
ds = ds.prefetch(1)
iterator = ds.make_one_shot_iterator()

entry = iterator.get_next()

with tf.Session() as sess:
    
    try:
        while True:
            print(sess.run(entry))
    except tf.errors.OutOfRangeError:
        pass

# Parallel execution:  [index, time from start of first load to return of current load]
# [ 0.          0.20026697]
# [ 1.          0.20084557]
# [ 2.          0.20095535]
# [ 3.          0.20048737]
# [ 4.          0.40154806]
```

**Comment by bignamehyp** [comment]
@vrv @mrry  Feature requests for datasets.

**Comment by mrry** [comment]
It sounds like `Dataset.map()` and `tf.py_func()` are almost adequate for your needs, so I'd be more in favor of improving `tf.py_func()` to the point where it has the same feature set as `Dataset.from_generator()`. Approximately speaking, it would need support for nested structures as inputs and outputs, and optional shape hints. There might be some delicacy in doing this without breaking backwards compatibility, but it should be possible. (If not, we could add a new API in `tf.contrib` at first with the new support.)

Marking this as contributions welcome.

**Comment by boeddeker** [comment]
Thanks for the suggestion to modify `py_func`. I looked in the code of `from_generator` and there is the generalization of my workaround with dicts.

I try to extract the code from `from_generator` and write a wrapper around `py_func`.

Current signature
`py_func(func, inp, Tout, stateful=True, name=None)`
Future signature
`py_func(func, inp, output_types, output_shapes=None, stateful=True, name=None)`

With that modification, I will be able to a `from_indexable` for my use cases.

But first I will write a bugfix for `nest.assert_shallow_structure` for dicts with different keys.

**Comment by boeddeker** [comment]
Now I have some working code, I extracted the code from 'tf.data.Dataset.from_generator' and modified it to have a similar signature as `py_func`.
Further, I added also a decorator (I prefer the decorator style.). For the decorator I allowed `output_type`/`output_shapes` to be callable to dynamic infer the `output_type`/`output_shapes`.

If there is an interest in a PR, I need some feedback on the code and some advise, where I place the code and tests.

```python
import tensorflow as tf
import traceback

from tensorflow.python.data.util import nest
from tensorflow.python.framework import tensor_shape
from tensorflow.python.ops import script_ops

def my_py_func(func, args=(), kwargs={}, output_types=None, output_shapes=None, stateful=True, name=None):
    # Low level function
    
    if isinstance(args, list):
        # Force tuple, nest.flatten interprets list as scalar
        args = tuple(args)
        
    if callable(output_types):
        # If callable, assume same signature and call with tensors and get the types
        output_types = output_types(*args, **kwargs)
    if callable(output_shapes):
        # If callable, assume same signature and call with tensors and get the shapes
        output_shapes = output_shapes(*args, **kwargs)
    
    flat_output_types = nest.flatten(output_types)
    
    args = (args, kwargs)
        
    flat_args = nest.flatten(args)

    def python_function_wrapper(*py_args):
        try:
            py_args, py_kwargs = nest.pack_sequence_as(args, py_args)
            ret = func(*py_args, **py_kwargs)
            nest.assert_shallow_structure(output_types, ret)
        except Exception:
            traceback.print_exc()
            raise
        return nest.flatten(ret)
    
    flat_values = script_ops.py_func(
      python_function_wrapper, flat_args, flat_output_types, stateful=stateful, name=name)

    if output_shapes is not None:
        # I am not sure if this is nessesary
        output_shapes = nest.map_structure_up_to(
            output_types, tensor_shape.as_shape, output_shapes)
        flattened_shapes = nest.flatten(output_shapes)
        for ret_t, shape in zip(flat_values, flattened_shapes):
            ret_t.set_shape(shape)

    return nest.pack_sequence_as(output_types, flat_values)
    
def py_func_decorator(output_types=None, output_shapes=None, stateful=True, name=None):
    def decorator(func):
        def call(*args, **kwargs):
            return my_py_func(
                func, 
                args, kwargs, 
                output_types=output_types, output_shapes=output_shapes, 
                stateful=stateful, name=name
            )
        return call
    return decorator
            
@py_func_decorator(
    output_types=lambda a, b: {
        'a': nest.map_structure(lambda x: x.dtype, a), 
        'b': nest.map_structure(lambda x: x.dtype, b),
    }, 
    output_shapes=lambda a, b: {
        'a': nest.map_structure(lambda x: x.shape, a), 
        'b': nest.map_structure(lambda x: x.shape, b),
    },
)
def foo(a, b):
    return {'a': a, 'b': b}
    
def bar(a, b):
    return {'a': a, 'b': b}
    
a = tf.constant([4., 5], name='a')
b = tf.constant([4., 5], name='b')
c = tf.constant([4., 5], name='c')
out0 = my_py_func(
    bar, [a, b], output_types={'a': a.dtype, 'b': b.dtype}, output_shapes={'a': a.shape, 'b': b.shape})
out1 = foo(a, b)
out2 = foo(a, b=b)
out3 = foo(a=a, b=b)
out4 = foo(a=dict(a=a, c=c), b=b)
print('out0', out0)
print('out1', out1)

from IPython.lib.pretty import pprint

with tf.Session() as sess:
    pprint(sess.run([out0]))
    pprint(sess.run([out1, out2, out3]))
    pprint(sess.run([out3]))

```

**Comment by boeddeker** [comment]
@mrry I started from `tf.data.from_generator` and wrote a wrapper around `pyfunc` to allow nested structures. Should I make a PR?

Further, I have now also a `tf.data.from_indexable` (Only some few lines with range and map) that support parallel loading with python code. Should I make a PR, else I will keep the code in my own code base?

**Comment by mrry** [comment]
We'd welcome a PR with any improvements to `tf.py_func()`. Ideally those could be in-place and backwards compatible, rather than adding a new API.

I'm less sure about `from_indexable()`, because I think it would amount to a one-line wrapper around `Dataset.map()` and `tf.py_func()` once the former changes go in. However, if it turns out to reduce the code complexity, perhaps we could find a place for it in `tf.contrib.data`.

**Comment by boeddeker** [comment]
Ok, I will make a PR for improving `tf.pyfunc`. I argee backward compatibility is important, but maybe rename some arguments would be better:

Current signature:
```python
def py_func(func, inp, Tout, stateful=True, name=None)
```
My prefared signature (similar to tf.data.Dataset.from_generator): (Note: output_types should not have a default argument.)
```python
def my_py_func(func, args=(), kwargs={}, output_types=None, output_shapes=None, stateful=True, name=None)
```
Suggestion for better backward compatibility:
```python
def my_py_func(func, inp=(), kwargs={}, Tout=None, Sout=None, stateful=True, name=None)
```

Note: An advantage of a decorator would be, that args and kwargs can be inferred (See example from_indexable).

You are right `from_indexable` takes only some few lines of code. For completeness here the code:

```python
def from_indexable(iterator, output_types, output_shapes=None, num_parallel_calls=None, stateful=True, name=None):
    length = 
    ds = tf.data.Dataset.range(len(iterator))
    @py_func_decorator(output_types, output_shapes, stateful=stateful, name=name)
    def index_to_entry(index):
        return iterator[index]
    return ds.map(index_to_entry, num_parallel_calls=num_parallel_calls)

```

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved by the PR #15121 (merged already), but please let me know if I'm mistaken.Thanks!

**Comment by Mushoz** [comment]
> Further, I have now also a `tf.data.from_indexable` (Only some few lines with range and map) that support parallel loading with python code. Should I make a PR, else I will keep the code in my own code base?

My apologies for replying on an old & closed ticket, but this was the easiest way to asks something about things said in this topic.

I tried your from_indexable code samples, but I did not experience any speed up with num_parallel_calls. From what I understand, code that is ran within py_func (or today, py_function/numpy_function) will obtain the GIL (Global Interpreter Lock), and therefor, while you can schedule more threads via `num_parallel_calls` only one can actually run at any point in time. How were you able to obtain speedups via your suggested from_indexable? Am I doing something wrong?

**Comment by Mushoz** [comment]
@boeddeker

**Comment by boeddeker** [comment]
Hey Mushoz, you can only observe a speedup, when you write "GIL friendly" code. So only a few python statements, with load (i.e. IO) operations and/or some "slow" code that releases the GIL (e.g. most numpy functions release the GIL).
When you have many loops and no function that releases the GIL, parallelization can have negative effects.
