### ISSUE TITLE
Session.run() hangs in child thread if something was executed in main thread first

### ISSUE THREAD

**Issue by JosPolfliet** [tensorflow/tensorflow#14442]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Confirmed on Mac OS X (10.12.6) + Ubuntu 16.04 on GCP
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.4.0-rc1-11-g130a514 1.4.0
- **Python version**: Anaconda Python 3.6.1 
- **GPU model and memory**: no gpu

### Describe the problem
`Session.run()` hangs in thread if it has executed something in the main thread. If we don't execute the first `calculate_something()` in the main thread- or execute it after we submitted to the pool, everything works. Only when first calculating something in the main thread, and then in the child thread does tensorflow hang. 

### Reproducing example
```python
from concurrent.futures import ProcessPoolExecutor as ProcessPool


def calculate_something():
    import tensorflow as tf

    with tf.Session() as sess:
        a = tf.constant(2)
        b = tf.constant(3)

        print("a=2, b=3")
        print("Addition with constants: %i" % sess.run(a+b))
        print("Multiplication with constants: %i" % sess.run(a*b))

calculate_something()

pool = ProcessPool(1)
pool.submit(calculate_something)
```

**Comment by mrry** [comment]
I assume `ProcessPoolExecutor` uses `fork()` internally, and forking after the TensorFlow runtime creates internal threads is unsafe. Fortunately, there are two workarounds:

1. Use `ThreadPoolExecutor` instead of `ProcessPoolExecutor`.
2. Use `tf.Session(config=tf.ConfigProto(use_per_session_threads=True))` instead of `tf.Session()`.

**Comment by JosPolfliet** [comment]
Thanks, that tip works!

**Comment by s0r2637** [comment]
Hi @JosPolfliet,

Which of the two workarounds mentioned by @mrry worked for you?  I am facing the same problem.

**Comment by krishnashankar** [comment]
FWIW I found that both 1 and 2 were necessary to prevent hang.
