### ISSUE TITLE
[Mac] Changes in fast-math-flags LLVM API cause XLA enabled build to fail

### ISSUE THREAD

**Issue by Carmezim** [tensorflow/tensorflow#14446]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.13 High Sierra
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: HEAD
- **Python version**: 3.6/2.7
- **Bazel version (if compiling from source)**: 0.7.0
- **GCC/Compiler version (if compiling from source)**: 9.0.0
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

Follow instructions in docs and build optimized for native architecture with XLA enabled (assumes fix in https://github.com/tensorflow/tensorflow/pull/14288).

### Describe the problem
LLVM latest release v5.0.0 does not include [recent fast-math-flags LLVM API changes](https://reviews.llvm.org/rL317488) already [updated](https://github.com/tensorflow/tensorflow/commit/4e69e02241067129379f73dd4fefe57f0a12bdc9#diff-866fd5845e79e513efd00ed931aa56f5L559) into TensorFlow codebase. 
Next LLVM release (v5.0.1) scheduled for the end of November, in the meanwhile besides building LLVM with CMake (?) there is no solution (?) but to wait.

Disclaimer: I'm new to LLVM and stuff so if I'm missing something I apologize and appreciate any insight.

```
tensorflow/compiler/xla/service/llvm_ir/llvm_util.cc:560:11: error: no member named 'setFast' in 'llvm::FastMathFlags'
    flags.setFast();
    ~~~~~ ^
```

**Comment by bignamehyp** [comment]
@tatatodd

**Comment by tatatodd** [comment]
@jlebar might know more about this.

**Comment by jlebar** [comment]
Hey there.

As you say, LLVM's APIs are not stable.  TF and XLA target LLVM built at head, not a particular LLVM release.  So if you want to build XLA, you also have to build LLVM.

This should happen automatically and transparently for you as part of the TF+XLA build.

The LLVM revision we check out is specified here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L570

Unfortunately it looks like we updated XLA to use the new fastmath API and pushed that change upstream without the corresponding change to workspace.bzl.  :(

Until we upstream our next set of changes, you can either roll back to before 82cd76bd36, or you can change that section in workspace.bzl to:

```
  temp_workaround_http_archive(
      name = "llvm",
      urls = [
          "https://mirror.bazel.build/github.com/llvm-mirror/llvm/archive/618cf290880ae9cd87b4bbf6c9b1759476f422eb.tar.gz",
          "https://github.com/llvm-mirror/llvm/archive/618cf290880ae9cd87b4bbf6c9b1759476f422eb.tar.gz",
      ],
      sha256 = "ec2e032e58372c614c41b539c0309baa91843c30d7a9c6dee647dcd24be02e3c",
      strip_prefix = "llvm-618cf290880ae9cd87b4bbf6c9b1759476f422eb",
      build_file = str(Label("//third_party/llvm:llvm.BUILD")),
      repository = tf_repo_name,
  )
```

I'm sorry about this.  :-/  I don't know enough about our OSS-releasing process to know if this is avoidable on our end in some way.

**Comment by Carmezim** [comment]
@jlebar Thank you for the thorough explanation and solution :) and no worries at all.
I've made the suggested changes and it compiled successfully 👍
