### ISSUE TITLE
tf.nn.sparse_softmax_cross_entropy_with_logits documentation error

### ISSUE THREAD

**Issue by dcunhas** [tensorflow/tensorflow#14450]
It looks like there may be a documentation error in [tf.nn.sparse_softmax_cross_entropy_with_logits](https://www.tensorflow.org/api_docs/python/tf/nn/sparse_softmax_cross_entropy_with_logits). 

It mentions "ValueError: If logits are scalars (need to have rank >= 1) or if the **rank of the labels is not equal to the rank of the labels minus one**." 

Based on the argument requirements above, I believe this should read "ValueError: If logits are scalars (need to have rank >= 1) or if the rank of the labels is not equal to the rank of the **logits** minus one."

**Comment by bignamehyp** [comment]
Thanks for catching this. Feel free to submit a pull request to fix it.

**Comment by dcunhas** [comment]
The error in this case is not in the in-file documentation in master (which is correct) but only on the website. It seems that master has the correct documentation, but 1.4 does not. If it is still valuable to pull request that change for 1.4, I can do so. However, I did notice a related error in master, which I did submit a pull request for.

**Comment by facaiy** [comment]
Yes, the typo of `sparse_softmax_cross_entropy_with_logits` is fixed in the master branch.
