### ISSUE TITLE
OpKernel errors after building tensorflow from sources

### ISSUE THREAD

**Issue by ShehabMMohamed** [tensorflow/tensorflow#14462]
Instead of using pip to install pre-built tensorflow library, I downloaded the sources and manually built the library to support using my machine's CPU SIMD instructions (SSE4.1, SSE4.2, AVX, AVX2, FMA).

I've installed tensorflow from sources using the official documentation (https://www.tensorflow.org/install/install_sources#PrepareMac)

But now I'm facing an array of OpKernel errors when I use tensorflow, here is a screenshot of my terminal...

<img width="1264" alt="screen shot 2017-11-10 at 9 39 24 pm" src="https://user-images.githubusercontent.com/11311073/32675491-bd1047cc-c65f-11e7-97a9-6f936f2cc7da.png">

Although I ran the following commands, 
`pip3 install --upgrade '/tmp/tensorflow_pkg/tensorflow-1.4.0-cp35-cp35m-macosx_10_6_intel.whl'`

`pip3 install --upgrade 'https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.1.0-cp35m-none-macosx_10_11_x86_64.whl'`

tensorflow still raises the same errors when being imported in a session. Any help?

**Operating System:** OS X El Captain 10.+

**Versions of installed libraries**
nltk (3.2.1)
numpy (1.13.3)
olefile (0.44)
pandas (0.20.0)
pigar (0.7.1)
Pillow (4.0.0)
pip (9.0.1)
pipreqs (0.4.9)
protobuf (3.4.0)
pyparsing (2.1.10)
python-dateutil (2.6.0)
python-xlib (0.18)
pytz (2016.10)
PyYAML (3.12)
requests (2.18.4)
scikit-learn (0.18.1)
scipy (0.18.1)
setuptools (36.7.0)
six (1.11.0)
sklearn (0.0)
tensorboard (1.0.0a5)
tensorflow (1.4.0)
tensorflow-tensorboard (0.4.0rc2)
Theano (0.8.2)
urllib3 (1.22)
Werkzeug (0.12.2)
wheel (0.30.0)
yarg (0.1.9)

**Comment by mrry** [comment]
This has been fixed in https://github.com/tensorflow/tensorflow/commit/f0b1e65b0ac9e587c117485a96a0eaf40675c518. If you pull the latest HEAD and build again, these warnings should not appear.
