### ISSUE TITLE
Apparent incorrect behavior from resize_to_range() in models/preprocessor.py

### ISSUE THREAD

**Issue by MisterMorden** [tensorflow/tensorflow#14460]
From the comments for resize_to_range():

  The output size can be described by two cases:
  1. If the image can be rescaled so its minimum dimension is equal to the
     provided value without the other dimension exceeding max_dimension,
     then do so.
  2. Otherwise, resize so the largest dimension is equal to max_dimension.

This logic would yield the wrong behavior for images with an aspect ratio near 1.  For instance, if we had a 1200x1200 image, and we had settings min_dimension = 600 and max_dimension = 1024, it seems that the desired behavior would be to rescale the image to 1024x1024.  Instead, following the logic above, the image would be rescaled to 600x600.

Am I missing something?

**Comment by bignamehyp** [comment]
@nealwu

**Comment by nealwu** [comment]
Hi @MisterMorden, it looks like your issue is for the object_detection model in the [models repository](https://github.com/tensorflow/models). Please open an issue there and tag the owners of the object_detection model.

**Comment by MisterMorden** [comment]
Thanks for the point in the right direction.
