### ISSUE TITLE
Wrong link in tensorflow-for-poets codelab

### ISSUE THREAD

**Issue by radeksimko** [tensorflow/tensorflow#14479]
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#3

There's a link for `Inception V3 model` pointing to https://github.com/tensorflow/models/tree/master/slim#pre-trained-models which 404's.

I assume it can point to https://arxiv.org/abs/1512.00567 instead.

<img width="375" alt="screen shot 2017-11-11 at 06 37 47" src="https://user-images.githubusercontent.com/287584/32687045-e22af624-c6aa-11e7-9773-a189f761a5ba.png">

I would've sent a PR fixing the link, but the codelab text doesn't seem to be available on anywhere Github. 😞

**Comment by drpngx** [comment]
@MarkDaoust could you take a look?

**Comment by MarkDaoust** [comment]
[Fixed](https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models)
