### ISSUE TITLE
error message show while compiling tensorflow from source

### ISSUE THREAD

**Issue by MyAusweis** [tensorflow/tensorflow#14477]
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasDgemm_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasCtrsv_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasIdamin_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasChpr2_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasSscal_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasSgemmBatched'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasSsyr2_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasDznrm2_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasDtpmv_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasCsymm_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasSspmv_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasZtbmv_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cudnnBatchNormalizationForwardTraining'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasCsyrk_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasSger_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasCgbmv_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasIdamax_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cufftSetStream'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasSasum_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cuDevicePrimaryCtxSetFlags'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cufftExecZ2D'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasSgbmv_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasZtrmm_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasCtpmv_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasCreate_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasZhpr_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cufftMakePlanMany'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasCher_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasDtrsv_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasZdotu_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasScasum_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasCscal_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasChemm_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `curandGenerateNormal'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasIcamax_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cudnnGetConvolutionBackwardDataAlgorithm'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasDtrmm_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasCtrmv_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasCgeru_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasZdrot_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cufftMakePlan3d'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasDsyr2_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasZtpsv_v2'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cudnnCreate'
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cgen_Umemory_Ustats_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `cublasSspr_v2'

**Comment by qmick** [comment]
It would be better if you post your system information as required. 

> ### System information
> - **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
> - **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
> - **TensorFlow installed from (source or binary)**:
> - **TensorFlow version (use command below)**:
> - **Python version**: 
> - **Bazel version (if compiling from source)**:
> - **GCC/Compiler version (if compiling from source)**:
> - **CUDA/cuDNN version**:
> - **GPU model and memory**:
> - **Exact command to reproduce**:

**Comment by MyAusweis** [comment]
- I tried to compile tensorflow from source in jetson tk1,
i use external sd card for booting (32 GB), ubuntu 14.04. already install cuda 7.0 with cudnn 4 (for dummy while compiling), python 2.7.6, gcc 4.8.5, bazel 0.5.4-dist, GPU Model K20A and memory of Jetson only 2 GB

The  steps are :
https://github.com/tensorflow/tensorflow
cd tensorflow
git checkout rv1.4.0
grep -Rl "lib64"| xargs sed -i 's/lib64/lib/g'  bec ause jetson tk1 only support 32 bit
./configure 
   chose cuda support,with cuda sdk 7.0 and cudnn 4
bazel build --config=opt --config=cuda --local_resources 2048,.5,1.0 //tensorflow/tools/pip_package:build_pip_package 

and the result shown above after compiling file around 3000 files

Thx

**Comment by drpngx** [comment]
It looks like it's not linking to cublas correctly. The way to debug this is to get the build command, and look at the .so or .a file in cublas using nm to see what symbols are defined.

**Comment by mpkuse** [comment]
I have same error.
```
$ nm /usr/local/cuda-9.1/lib64/libcudnn.so.7
nm: /usr/local/cuda-9.1/lib64/libcudnn.so.7: no symbols
```

**Comment by jmtatsch** [comment]
@mpkuse you can use `nm -D /usr/local/cuda-9.1/lib64/libcudnn.so.7`to see the stripped dynamic symbols.
For more information see https://unix.stackexchange.com/questions/282616/why-nm-shows-no-symbols-for-lib-i386-linux-gnu-libc-so-6

**Comment by ymodak** [comment]
Closing this issue due to staleness. Please use the latest version of TensorFlow and build again.
Feel free to report any issues you encounter with latest TensorFlow. Thanks!
