### ISSUE TITLE
bazel build failed 

### ISSUE THREAD

**Issue by WenchenLi** [tensorflow/tensorflow#1448]
Hi,
I'm running on ubuntu 14.04 with cuda 7.0, cudnn4 in system. 
I followed the instruction on  https://www.tensorflow.org/versions/r0.7/get_started/os_setup.html#optional-install-cuda-gpus-on-linux. But when build with bazel (0.2.0), I always get:

$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
INFO: Found 1 target...
ERROR: missing input file '//third_party/gpus/cuda:include/thrust/detail/config/exec_check_disable.h':/home/wenchen/frameworks/tensorflow/third_party/gpus/cuda/include/thrust/detail/config/exec_check_disable.h (Permission denied).
ERROR: /home/wenchen/frameworks/tensorflow/tensorflow/stream_executor/BUILD:5:1: //tensorflow/stream_executor:stream_executor: missing input file '//third_party/gpus/cuda:include/thrust/detail/config/exec_check_disable.h'.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/wenchen/frameworks/tensorflow/tensorflow/stream_executor/BUILD:5:1 1 input file(s) do not exist.
INFO: Elapsed time: 0.814s, Critical Path: 0.00s

please help. 

Thanks,
Wenchen

**Comment by girving** [comment]
The permission denied bit might mean that the permissions for that file are weird.

**Comment by girving** [comment]
Unfortunately no, it's a guess without knowledge of details.  What happens if you do `ls -ld` on that file and all the directories above it?

**Comment by WenchenLi** [comment]
I figured it out thanks to `ls -ld`, my exec_check_disable.h denies access for others.
Just `sudo chmod o=r /usr/local/cuda/include/thrust/detail/config/exec_check_disable.h` and it builds.

Thanks for pointing out girving.
