### ISSUE TITLE
My trained checkpoint doesn't work.

### ISSUE THREAD

**Issue by 7017227** [tensorflow/tensorflow#14484]
$ python3 tests/test_snapshot.py lsp out/lsp_alexnet_imagenet_small/checkpoint-370000.data-00000-of-00001

But it shows this error

Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator? Traceback (most recent call last):

DataLossError (see above for traceback): Unable to open table file out/lsp_alexnet_imagenet_small/checkpoint-370000.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
