### ISSUE TITLE
FATAL EXCEPTION on running the custom app after including libraries. java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by makarg1001** [tensorflow/tensorflow#14495]
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-support-annotations-25.0.1_ef28e13c9736d79b0dc9b87816fdb5d73ab6b4a6-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-org.tensorflow-tensorflow-android-1.4.0_d5862dbeef875a2fd03edd55b52916408a0fdae3-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-libandroid_tensorflow_inference_java_8b98de511efe4c9135a05cbc7896de53b57dba53-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-internal_impl-25.0.1_fe869e8b718f7d011b42911906bd8102f80b5a3e-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-internal_impl-25.0.1_e684d856bf1ea2afc0785de8b2275aa12611114e-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-internal_impl-25.0.1_aa673af4dcf22bcd43d00f80c8888302b9bc278f-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-internal_impl-25.0.1_73c7d1a62ae7807eb7fd020f01cc2e0e5fd6f9f0-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-internal_impl-25.0.1_2002db2ec303ce7ff6c3fba7cf2a064df60d63e4-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-com.android.support-support-vector-drawable-25.0.1_6f89a35e510cd2b99a51cac7fbf50945d73d2434-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-com.android.support-support-v4-25.0.1_7519131df48ff71670e81da58ca765ab77bce972-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-com.android.support-support-media-compat-25.0.1_d42d2937b0925301d8bc24c4d82fa264d601340d-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-com.android.support-support-fragment-25.0.1_130afa5cd91643b7e407f699e25e8953be2af0b8-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-com.android.support-support-core-utils-25.0.1_39638966b982d2402411d64d18981a4ce8677c1f-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-com.android.support-support-core-ui-25.0.1_a6406a5ff5aa24fae58de96cd3218c571f49607d-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-com.android.support-support-compat-25.0.1_5b463be571b727968d5b5d68f9c9b17d4dd40809-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-com.android.support-appcompat-v7-25.0.1_17a51234c0d6cd6e15ec23d8be2aa38790811b00-classes.dex", dex file "/data/data/com.example.iiti.earcheck/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-25.0.1_df8c5ec44495c7c6a687ebfe83e9e46b0bcc5d42-classes.dex"],nativeLibraryDirectories=[/data/app/com.example.iiti.earcheck

Help!

**Comment by cy89** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by makarg1001** [comment]
There was some issue with including the libraries manually. I fixed it just now. I will be posting the whole process after I finish up with my android application. Thanks a lot!

**Comment by dilipajm** [comment]
@makarg1001 I am facing same issue. Can you post the solution here? Thanks
