### ISSUE TITLE
unable to install -Inside the virtualenv, install TensorFlow:

### ISSUE THREAD

**Issue by hreganti** [tensorflow/tensorflow#145]
everytime i execute the line

(tensorflow)$ pip install --upgrade <$url_to_binary.whl>

I get below errors. Experts pls help. 

Hemanths-MBP:tensorflow hemanthreganti$ (tensorflow)$ pip install --upgrade <$url_to_binary.whl>
-bash: syntax error near unexpected token `$'
Hemanths-MBP:tensorflow hemanthreganti$  pip install --upgrade <$url_to_binary.whl>
-bash: syntax error near unexpected token `newline'
Hemanths-MBP:tensorflow hemanthreganti$ pip install --upgrade <$url_to_binary.whl>
-bash: syntax error near unexpected token `newline'
Hemanths-MBP:tensorflow hemanthreganti$  source bin/activate 
(tensorflow)Hemanths-MBP:tensorflow hemanthreganti$ pip install --upgrade <$url_to_binary.whl>
-bash: syntax error near unexpected token `newline'
(tensorflow)Hemanths-MBP:tensorflow hemanthreganti$ (tensorflow)$ pip install --upgrade <$url_to_binary.whl>
-bash: syntax error near unexpected token `$'
(tensorflow)Hemanths-MBP:tensorflow hemanthreganti$ (tensorflow)$ python tensorflow/models/image/mnist/convolutional.py
-bash: syntax error near unexpected token `$'
(tensorflow)Hemanths-MBP:tensorflow hemanthreganti$ python tensorflow/models/image/mnist/convolutional.py
python: can't open file 'tensorflow/models/image/mnist/convolutional.py': [Errno 2] No such file or directory
(tensorflow)Hemanths-MBP:tensorflow hemanthreganti$

**Comment by hreganti** [comment]
Hemanths-MBP:tensorflow hemanthreganti$ sudo pip install --upgrade virtualenv
Password:
The directory '/Users/hemanthreganti/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/hemanthreganti/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: virtualenv in /Library/Python/2.7/site-packages

**Comment by ebrevdo** [comment]
The string "<$url_to_binary.whl>" should be replaced with the correct URL; please see elsewhere in that document to see which version of the whl file is right for you.

For the second error, it looks like you already have virtualenv set up.

**Comment by hreganti** [comment]
Thanks ebrevdo. I am unable to find any link on the page http://tensorflow.org/get_started/os_setup.md .Would you be able to provide me with the right link.

**Comment by vrv** [comment]
That page lists it under OS X section:
https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
