### ISSUE TITLE
Error: CUDNN_STATUS_INTERNAL_ERROR Any help is appreciated. 

### ISSUE THREAD

**Issue by AlsubaieNajah** [tensorflow/tensorflow#14503]
Dears, I am struglling with tensorflow installation. 

I have GeForce GTX1080 , Ubuntu16.04 cuda 9 cudnn7 . nvidia driver 384.98. I try to run the mnist samle coud from cudd_samples v7 and I got this error: 
Error: CUDNN_STATUS_INTERNAL_ERROR
here is nvidia-smi
-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.98                 Driver Version: 384.98                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:03:00.0  On |                  N/A |
| 30%   47C    P8    13W / 250W |    581MiB / 11171MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:04:00.0 Off |                  N/A |
| 23%   36C    P8     9W / 250W |      2MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1390      G   /usr/lib/xorg/Xorg                           331MiB |
|    0      2158      G   compiz                                       196MiB |
|    0      2878      G   ...-token=04563B517E2C68A632F4C6B61B846229    51MiB |

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

Please help.

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
