### ISSUE TITLE
bazel build: can't install tensor flow

### ISSUE THREAD

**Issue by Titaniumtown** [tensorflow/tensorflow#14522]
I did "bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package"
and this is what I got:

"ERROR: /home/simon/Downloads/tensorflow/tensorflow/contrib/rnn/BUILD:259:1: Illegal ambiguous match on configurable attribute "copts" in //tensorflow/contrib/rnn:gen_gru_ops_py_wrappers_cc:
@local_config_cuda//cuda:using_clang
@local_config_cuda//cuda:using_nvcc
Multiple matches are not allowed unless one is unambiguously more specialized.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted:

/home/simon/Downloads/tensorflow/tensorflow/contrib/rnn/BUILD:259:1: Illegal ambiguous match on configurable attribute "copts" in //tensorflow/contrib/rnn:gen_gru_ops_py_wrappers_cc:
@local_config_cuda//cuda:using_clang
@local_config_cuda//cuda:using_nvcc
Multiple matches are not allowed unless one is unambiguously more specialized.
INFO: Elapsed time: 0.454s
FAILED: Build did NOT complete successfully (0 packages loaded)
currently loading: tensorflow/python"

What do I Do?

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
