### ISSUE TITLE
Multidimensional RNN

### ISSUE THREAD

**Issue by phvu** [tensorflow/tensorflow#1453]
Hi all,

This is a feature request for [Multidimensional LSTM](http://people.idsia.ch/~juergen/nips2009.pdf). Is there any plan to support this in tensorflow?

I might be able to help with implementation if there is such a plan.

Cheers,

**Comment by girving** [comment]
@ebrevdo: Want to comment on this?  Fancier variants of LSTMs would be great to have, the only question is whether they should go in core tensorflow, the contrib directory, or the models repo.  If you can make the interface similar to Eugene's existing RNN cell setup contrib might be the best place at first.

**Comment by ebrevdo** [comment]
Right now it's possible to implement various types of multidimensional RNNs by feeding in your data as time being one direction (say, x), taking the output of the RNN, transposing it, and feeding it into a second RNN.  etc.  Alternatively feed your data & its transpose into separate RNNs (possibly with tied weights) and depth-concatenate the results.  And maybe feed the result into another RNN.

This allows one to implement both separable and non-separable multidimensional RNNs.  Not sure we need the sugar until people show it's superior to convolutional networks for something, and there's lots of use cases.

**That said**, it would be really nice to implement GridLSTM (also by Alex Graves, and according to their paper showing a lot of promise with fewer parameters).  GridLSTM uses standard LSTM cells, so it would be a function that uses RNNCell objects.  It connects them in interesting, convolutional, ways.

GridLSTM would probably go well in contrib, until enough people use it and it shows to be a very successful technique.

**Comment by phvu** [comment]
Thanks, GridLSTM looks interesting. I will give it a shot. [This](https://github.com/coreylynch/grid-lstm) seems to be a good starting point.

I do have a use-case for this, but it is still in a pilot study. Will be nice to make it into contrib until there are more use-cases.

**Comment by selcouthlyBlue** [comment]
> Right now it's possible to implement various types of multidimensional RNNs by feeding in your data as time being one direction (say, x), taking the output of the RNN, transposing it, and feeding it into a second RNN. etc.

How exactly do I transpose the output? Say I have this code:

```
input = tf.placeholder(tf.float32, [batch_size, time_steps, num_features]
cell = rnn.BasicLSTMCell(num_units=1)
lstm1 = tf.nn.dynamic_rnn(cell, input, dtype=tf.float32)
tranposed_lstm_output = some_transpose_function(lstm1) # how does this work?
lstm2 = tf.nn.dynamic_rnn(cell, transposed_lstm_output, dtype=tf.float32)
```

As for the other one:

> Alternatively feed your data & its transpose into separate RNNs (possibly with tied weights) and depth-concatenate the results.

How do I "depth-concatenate" the results?

```
input = tf.placeholder(tf.float32, [batch_size, time_steps, num_features])
transposed_input = tf.placeholder(tf.float32, [batch_size, num_features, time_steps])
cell = rnn.BasicLSTMCell(num_units=1)
lstm1 = tf.nn.dynamic_rnn(cell, input, dtype=tf.float32)
lstm2 = tf.nn.dynamic_rnn(cell, transposed_input, dtype=tf.float32)
mdlstm1 = some_depth_concatenation_function([lstm1, lstm2]) # how does this work?
```

**Comment by selcouthlyBlue** [comment]
Is this the mdlstm implementation? https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/ndlstm/python/lstm2d.py
