### ISSUE TITLE
Failed to calculate FLOPs for Tensorflow Object Detection API (SSD_Mobilenet & SSD_Inception)

### ISSUE THREAD

**Issue by tankienleong** [tensorflow/tensorflow#14543]
System information

    Have I written custom code: No
    OS Platform and Distribution: Linux Ubuntu 14.04
    TensorFlow installed from: source
    TensorFlow version: ('v1.3.0-rc1-1951-g04c318b', '1.3.0')
    Python version: 2.7.12
    Bazel version (if compiling from source): 0.7.0
    CUDA/cuDNN version: 8.0/6.0
    GPU model and memory: Tesla K40 12Gb
    Exact command to reproduce: bazel-bin/tensorflow/tools/benchmark/benchmark_model --graph=ssd_inception.pb --input_layer="image_tensor" --input_layer_shape="1,224,224,3" --input_layer_type="uint8" --output_layer="detection_boxes,detection_scores,detection_classes,num_detections" --show_flops=true

Problem
The ssd_inception.pb is one of the model that trained from Tensorflow object detection API. When I tried the FLOPs calculation, it failed with  Invalid argument: Tried to fetch data for '^FeatureExtractor/Assert/Assert', which produces no output.  To run to a node but not fetch any data, pass '^FeatureExtractor/Assert/Assert' as an argument to the 'target_node_names' argument of the Session::Run API.

Logs
2017-11-14 19:01:29.405289: E tensorflow/tools/benchmark/benchmark_model.cc:593] FLOPs calculation failed with Invalid argument: Tried to fetch data for '^FeatureExtractor/Assert/Assert', which produces no output.  To run to a node but not fetch any data, pass '^FeatureExtractor/Assert/Assert' as an argument to the 'target_node_names' argument of the Session::Run API.

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
