### ISSUE TITLE
Links in tensorflow/tensorflow/contrib/lite/g3doc/models.md are not working

### ISSUE THREAD

**Issue by jasminezz** [tensorflow/tensorflow#14571]
The links in tensorflow/tensorflow/contrib/lite/g3doc/models.md are not working, please fix it?
When I click the Link, get the error "AccessDenied".
I try to modify the link from
https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_1.0_224_float_2017_11_08.zip
to
https://storage.googleapis.com/download.tensorflow.org/models/tflite/mobilenet_v1_1.0_224_float_2017_11_08.zip

it works.
But for inception model I don't know how to fix it , need your help?

**Comment by anitha-v** [comment]
Thank you for noticing this, the links are fixed now.

Anitha
