### ISSUE TITLE
modify tensorflow/core/protobuf/config.proto

### ISSUE THREAD

**Issue by rayjang** [tensorflow/tensorflow#14577]
I try to modify config.proto.
I want to change per_process_gpu_memory_fraction from 1 to 0.2.
I modified it and builded it.

After I modified it, I compiled by using bazel
```
. /configure
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_packag
```
But I got error and I cannot compile.

**Comment by qmick** [comment]
What is the error log and your system information?

**Comment by rayjang** [comment]
I changed per_process_gpu_memory_fraction from 1 to 0.5 in cofig.proto
![image](https://user-images.githubusercontent.com/9244296/32835622-1ef3b7ec-ca4a-11e7-8cbf-8838d4c7a86c.png)

**Comment by mrry** [comment]
From the error message I'm guessing that you edited this line:

https://github.com/tensorflow/tensorflow/blob/31b79e42b9e1643b3bcdc9df992eb3ce216804c5/tensorflow/core/protobuf/config.proto#L21

...to something like:

```protobuf
  double per_process_gpu_memory_fraction = 0.2;
```

The `1` in the original code is not a default value. Rather, it is a protobuf field number, which controls how the protocol buffer is serialized, and it must be a unique integer. (Moreover, for backwards compatibility, it must never change.)

The default value for a `double`-type protobuf field is `0.0`. The code for handling that is in the C++ runtime, here:

https://github.com/tensorflow/tensorflow/blob/31b79e42b9e1643b3bcdc9df992eb3ce216804c5/tensorflow/core/common_runtime/gpu/gpu_device.cc#L781
