### ISSUE TITLE
how to change the gpu_fraction_per_process from default 1 to 0.5 or 0.7?

### ISSUE THREAD

**Issue by rayjang** [tensorflow/tensorflow#14585]
I want to change the gpu_fraction_per_process from default 1 to 0.5 or 0.7.
Not by adding the below in my code
```
import tensorflow as tf
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.2)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
```
Is there other method to change it in the tensorflow source file??

In the case of Keras, I can change it by modifying keras.json file.
I spent a lot of time to find the way though, I cannot find the way ..
Is it impossible???

**Comment by yaroslavvb** [comment]
`K.set_session`?  (This kind of question is better for stackoverflow)

**Comment by rayjang** [comment]
@yaroslavvb  I run my model in spark with GPU machines. The problem is that tensorflow takes all memory, so there is no memory space for spark rdd. This is why I want to limit the fraction of memory.
`K.set_session` is  kinda not working for this case.  `K.set_session` works on only spark driver, not on workers.. So I want to set default  in Tensorflow itself. 
Is there any way to modify tensorflow source related to this and use it??

**Comment by yaroslavvb** [comment]
Some hacky workarounds are discussed here -- https://github.com/tensorflow/tensorflow/issues/8040

There was some discussion for a generic mechanism to do global settings here https://github.com/tensorflow/tensorflow/issues/8136 but it stalled
