### ISSUE TITLE
contrib.slim.conv2d doesn't check input dimension

### ISSUE THREAD

**Issue by Linusnie** [tensorflow/tensorflow#14583]
tensorflow version: v1.4.0-rc1-11-g130a514 (installed from pip)

contrib.slim.conv2d doesn't check for input dimensionality. So if you give it a 5D tensor it instead performs a 3D convolution.

Here is a quick way to see this:
```
sess = tf.InteractiveSession()

image_ph = tf.placeholder(tf.float32,
                          shape=(None, None, 10, 10),
                          name='image')
image = tf.expand_dims(image_ph, -1)
conv = tf.contrib.slim.conv2d(image, 3, 3, padding="VALID")

sess.run(tf.global_variables_initializer())
conv_out = conv.eval({image_ph: np.random.random((16, 20, 10, 10))})
```

conv_out will have shape `[16, 18, 8, 8, 3]`, meaning that the time dimension (dim 1) has decreased due to the VALID padding. 

As a side note I think it would be convenient if all conv2d implementations let you specify which dimensions to act on (or acted on the last 3 dims of the input by default). This is useful for example if you have sequential data and want to apply a 2d convolution to each frame independently.

**Comment by cy89** [comment]
@sguada would it be appropriate to mark this "contributions welcome", or do we have internal plans to fix it?

**Comment by sguada** [comment]
It should check it has the right rank.
Allowing other dimensions to run the conv2d on, that would be difficult since cuDNN doesn't support it.

**Comment by Linusnie** [comment]
in case anyone is interested I use the following code to get around the dimensionality requirements:

```
def frame_wise_op(inputs, operation, **kwargs):
    inputs_flat = tf.reshape(inputs, [-1] + inputs.shape[2:].as_list())

    outputs_flat = operation(inputs_flat, **kwargs)

    output_shape = tf.concat([tf.shape(inputs)[:2], tf.shape(outputs_flat)[1:]], 0)
    outputs = tf.reshape(outputs_flat, output_shape)

    return outputs
```

example use:
```
conv = frame_wise_op(inputs,
                     operation=tf.layers.conv2d,
                     filters=32,
                     kernel_size=[5, 5])
net = frame_wise_op(net,
                    operation=tf.layers.max_pooling2d,
                    pool_size=[2, 2],
                    strides=2)
```

**Comment by s4mpl3d** [comment]
+1

**Comment by gauravdesale** [comment]
where is the source code for this functionality to be found? sorry I am new and just curious as to how it works

**Comment by facaiy** [comment]
@gauravdesale I think the method is only an alias for `convolution`, that's why it doesn't check input size, see:

https://github.com/tensorflow/tensorflow/blob/0403762ced523c048914009b335c7626e10e5f2e/tensorflow/contrib/layers/python/layers/layers.py#L2945

https://github.com/tensorflow/tensorflow/blob/0403762ced523c048914009b335c7626e10e5f2e/tensorflow/contrib/layers/python/layers/layers.py#L1048

**Comment by facaiy** [comment]
Hi, @Linusnie . How about using ` tf.nn.conv2d` ?

**Comment by Linusnie** [comment]
Hey @facaiy, my problem is that I would like to use 2d convolution on multiple tensor dimensions. `tf.nn.conv2d` also requires a 4D input. Example:

```
>>> x = tf.placeholder(tf.float32, (5, 3, 9, 9, 1))
>>> y = tf.nn.conv2d(x)
```
yields 
```
ValueError: Shape must be rank 4 but is rank 5 for 'Conv2D_1' (op: 'Conv2D') with input shapes: [5,3,9,9,1], []
```

**Comment by wdhorton** [comment]
@Linusnie seems like this is the intended behavior:
https://github.com/tensorflow/tensorflow/blob/0403762ced523c048914009b335c7626e10e5f2e/tensorflow/contrib/layers/python/layers/layers.py#L1003

```
    if input_rank == 3:
      layer_class = convolutional_layers.Convolution1D
    elif input_rank == 4:
      layer_class = convolutional_layers.Convolution2D
    elif input_rank == 5:
      layer_class = convolutional_layers.Convolution3D
```

It chooses the kind of convolution to perform based on the rank of the input tensor.

**Comment by Linusnie** [comment]
@wdhorton yes, but my point is that a function called conv2d should never perform a 3d convolution, as it does right now when you use it on a 5d tensor.

**Comment by facaiy** [comment]
I agree with @Linusnie that `contrib.slim.conv2d` should check its input rank. However since it is under contrib module, I'm afraid that the issue might not be resolved quickly. So I prefer to use ` tf.layers.conv2d`.

About the second point, as @sguada said:
> Allowing other dimensions to run the conv2d on, that would be difficult since cuDNN doesn't support it.

I think the feature will be useful, however it seems difficult to implement currently. And to get around the problem, we can reshape our data before and after calculation like you do.  cc @fchollet who might be interested.

**Comment by sguada** [comment]
To clarify, both tf.layers.conv2d and slim.conv2d should check that the rank is 4D and raise an error otherwise.
Using conv2d in a 5D tensor is out of the current API, but it can be implemente with reshapes.

**Comment by yongtang** [comment]
Added a PR #18251 so that the shape could be checked for conv2d/conv3d.
