### ISSUE TITLE
CIFAR-10 Model has (almost) pointless ops in distorted_inputs

### ISSUE THREAD

**Issue by stefan-w** [tensorflow/tensorflow#1458]
While preparing an intro talk I noticed something odd happening in cifar10_input.py. 

In the following piece of code:
https://github.com/tensorflow/tensorflow/blob/a641ff6aca15b8e6e5ecf96a7a9188c0c1246c8e/tensorflow/models/image/cifar10/cifar10_input.py#L176

The sequence of ops is: random brightness, which adds a random constant to each pixel, then random contrast, which multiplies the difference from the mean by a random factor ... and then per_image_whitening, which transforms the image to zero mean and unit variance, effectively canceling the previous random operations out, if you don't cross the threshold the per_image_whitening has for low-variance images. That doesn't make sense to me - I would think you want either the data augmentation ops for brightness/contrast OR the whitening to deal with different lighting conditions, but not both. Am I mistaken there?

**Comment by girving** [comment]
@shlens: Want to comment here?

**Comment by shlens** [comment]
Agreed. The image preprocessing is confused and superfluous.

For the most part, the distortions provided by random_brightness combined with random_contrast would be largely removed by per_image_whitening performed in the subsequent operation. If you removed the per_image_whitening, I suspect that the model should train nearly identically.

Would you be able to perform a side-by-side comparison where you retain and then remove per_image_whitening? If the results are identical, we would remove per_image_whitening from the preprocessing of this network.

(In an earlier incarnation of this network we employed random_hue prior to per_image_whitening, however this operation we removed for other reasons.)

**Comment by stefan-w** [comment]
I actually tried a version without without the random brightness and random contrast and that trained identically (which I expected since the per_image_whitening is cancelling them out). I will try removing the whitening if there's an idle gpu sometime

**Comment by girving** [comment]
@stefan-w: Pull requests welcome!

**Comment by kingtaurus** [comment]
I believe that the whitening should be different on a per image basis (one because there is saturation effects that adjusting the contrast and brightness may cross, two the adjustments for data augmentation should be on a per 'image' basis). Take for example (using numpy):

```
X_batch_sample = X_train[0:256]
X_0 = (X_train[0:256] - np.mean(X_train[0:256], axis=0))/np.std(X_train[0:256],axis=0)
#X_0 is the whitened 'images'

shift_1 = 63 * np.random.normal(size=(256,1,1,1))
X_0_shift1 = (X_train[0:256] + shift_1 - np.mean(X_train[0:256] + shift_1, axis=0)) / np.std(X_train[0:256] + shift_1, axis=0)
#whitening the shifted case
shift_2 = np.random.uniform(low=0.2, high=1.8, size=(256,1,1,3))

#Let's look at only the first image:
print(np.mean(X_0[0] - X_0_shift1[0]))
#This should be non-zero shift (because its the difference of two independent Gaussian processes)
print(np.mean(X_0[0] - X_0_shift2[0]))
```
