### ISSUE TITLE
TF Lite C++ standalone Interpreter

### ISSUE THREAD

**Issue by JulianNeeleman** [tensorflow/tensorflow#14586]
**Feature request**

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.4
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.7.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**: None

I deploy TensorFlow models to environments with very limited memory, and was very excited to see how tiny the TF Lite kernel is (several hundred kilobytes). I know the project is young, but I was wondering if there are any plans to support a standalone C++ build for the Lite architecture, for deployment to (Linux) environments that do not have a TensorFlow runtime. 

For my purposes, this package should support the following:
- Loading a model configuration
- Loading input tensors
- Invoking the model with input tensors
- Storing the result in output tensors
- Some serialization method for the input- and output tensors

I would like to know:
- Is this a possible feature for TF Lite?
- What would the scope be of implementing this?
- Are there any plans to do so?

**Comment by aselle** [comment]
I'm not exactly sure what you mean by "standalone c++" build, but I assume independent of TensorFlow tooling is wha tyou mean.

There is already a makefile that builds basically just the interpreter that @petewarden made. You may need to modify the ops to be driven by the "reference ops" rather than the "optimized ops" to avoid using neon. But this should be definitely possible, and something we hope to support better in the future.

**Comment by charleys** [comment]
My goal is to use NDK to compile C++ static libraries that can be called by Android. I don't quite understand what you're saying "modify the ops to be driven by the "reference ops" rather than the "optimized ops" to avoid using neon. "  PS: I refer to /tensorflow/contrib/lite/makefile

**Comment by charleys** [comment]
hi, asslle:

My goal is to use NDK to compile C++ static libraries that can be called by Android. I don't quite understand what you're saying "modify the ops to be driven by the "reference ops" rather than the "optimized ops" to avoid using neon. " PS: I refer to /tensorflow/contrib/lite/makefile

**Comment by andrehentz** [comment]
aselle's point is that you can change the makefile to build a static library for Android, or any other system. However, a lot of the TF Lite operators depend on neon, which is available on Android but not on every other system. If you don't have neon (or a suitable replacement) you will have to manually edit the source code in kernels/*.cc. (On linux you may sometimes rely on sse as a neon replacement)

**Comment by WellDone2094** [comment]
where can i find the makefile made by @petewarden ?

**Comment by JulianNeeleman** [comment]
@WellDone2094 https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/Makefile

**Comment by WellDone2094** [comment]
i don't know how i missed that

**Comment by aselle** [comment]
@JulianNeeleman, is your question sufficiently answered?

**Comment by JulianNeeleman** [comment]
@aselle Yes, thank you.

**Comment by tataganesh95** [comment]
The link to the TF lite makefile posted by @JulianNeeleman is no longer available. Can someone update it with the new link? It is probably shifted here - https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/tools/make

**Comment by wantt** [comment]
you can find solution in my git

**Comment by tataganesh95** [comment]
@wantt Thanks! Will take a look.

**Comment by k-farrow** [comment]
Where can I find a version of the TensorFlow Lite makefile?

**Comment by milinddeore** [comment]
@wantt Thanks for git repo. On linux, I would able to compile it with `-no-pie` option. Could you please tell me how did you build `libtensorflow-lite.a` library? With `objdump` i can see that its for `arch=x86_64` did you compile it on `linux` or `macOS`? 

Has anyone tried on `macOS`?

**Comment by milinddeore** [comment]
I could able to run it on `macOS,` my working repo is here: https://github.com/milinddeore/TfLite-Standalone-build-Linux-MacOS
