### ISSUE TITLE
Unable to download  quantized Mobilenet TensorFlow Lite model 

### ISSUE THREAD

**Issue by yangcheng** [tensorflow/tensorflow#14594]
### Describe the problem
I am trying to build TensorFlow Lite Android app,  was following the [instruction](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite#building-in-android-studio-using-tensorflow-lite-aar-from-jcenter). 

> Download the quantized Mobilenet TensorFlow Lite model from [here](https://storage.googleapis.com/download.tensorflow.org/models/tflite/mobilenet_v1_224_android_quant_2017_11_08.zip)
> unzip and copy mobilenet_quant_v1_224.tflite to the assets directory: tensorflow/contrib/lite/java/demo/app/src/main/assets/

however, the link is not open to the public 

https://storage.googleapis.com/download.tensorflow.org/models/tflite/mobilenet_v1_224_android_quant_2017_11_08.zip

```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous users does not have storage.objects.get access to download.tensorflow.org/models/tflite/mobilenet_v1_224_android_quant_2017_11_08.zip.
</Details>
</Error>
```

**Comment by anitha-v** [comment]
Please try now, this has been fixed.

Anitha
