### ISSUE TITLE
partial_run segfault

### ISSUE THREAD

**Issue by zayd** [tensorflow/tensorflow#1459]
Running partial_run twice results in a segfault. By running twice I mean: setting up placeholder, ops and completing one run through the graph and then trying to do another run.

### Environment info
Operating System: Linux. 
Version: 0.7.1
Hash: 028d0b4

### Steps to reproduce
```
import tensorflow as tf
from tensorflow.python import array_ops
from tensorflow.python import math_ops
from tensorflow.python.framework import dtypes
sess = tf.Session()

a = array_ops.placeholder(dtypes.float32, shape=[])
b = array_ops.placeholder(dtypes.float32, shape=[])
r1 = math_ops.add(a, b)

h = sess.partial_run_setup([r1], [a, b])
res = sess.partial_run(h, r1, feed_dict={a: 1, b: 2})

h = sess.partial_run_setup([r1], [a, b])
res = sess.partial_run(h, r1, feed_dict={a: 1, b: 2})

> Segmentation fault (core dumped)
```

### What have you tried?
1. Changing execution target to CPU instead of GPU (same problem)
2. Reusing the same handle for the second run results in a ```StatusNotOK``` error because the input has already been fed

### Logs or other output that would be helpful
Core dump is 1.7 GB. Can attach if useful

**Comment by girving** [comment]
Checking with the main partial run person (I'm not sure I know his Github username).

**Comment by yuanbyu** [comment]
Just assign it to me.

**Comment by yuanbyu** [comment]
I don't seem to be able to reproduce the reported issue.  Here is the code I use:

```
import tensorflow as tf
sess = tf.Session()
a = tf.placeholder(tf.float32, shape=[])
b = tf.placeholder(tf.float32, shape=[])
r1 = tf.add(a, b)

h = sess.partial_run_setup([r1], [a, b])
res = sess.partial_run(h, r1, feed_dict={a: 1, b: 2})
print("111", res)

h = sess.partial_run_setup([r1], [a, b])
res = sess.partial_run(h, r1, feed_dict={a: 1, b: 2})
print("222", res)

h = sess.partial_run_setup([r1], [a, b])
res = sess.partial_run(h, r1, feed_dict={a: 1, b: 2})
print("333", res)
```

Running it produced:

```
('111', 3.0)
('222', 3.0)
('333', 3.0)
```

**Comment by zayd** [comment]
Same code results in segfault here:

```
...

res = sess.partial_run(h, r1, feed_dict={a: 1, b: 2})
Segmentation fault (core dumped)
```
Are you running 0.7.1 028d0b4 ? Will try another reinstall from scratch

**Comment by yuanbyu** [comment]
I am using HEAD. Could you try HEAD?

**Comment by zayd** [comment]
Trying it now

**Comment by zayd** [comment]
(ran into bazel issues) 
works!
```
('111', 3.0)
('222', 3.0)
('333', 3.0)
```
Seems the bug was fixed somewhere between last release and HEAD.

**Comment by girving** [comment]
Excellent!  Closing.  @yuanbyu: We should probably add a note to `RELEASE.md` saying some bugs were fixed in partial_run.
