### ISSUE TITLE
Linking error "Undefined symbols for architecture x86_64:   "nsync::nsync_mu_init(nsync::nsync_mu_s_*)"" on iOS

### ISSUE THREAD

**Issue by llyyun** [tensorflow/tensorflow#14605]
Hello,

I downloaded the latest release 1.4.0 and builded it for iOS with build_all_ios.sh, and can successfully build libtensorflow-core.a, libprotobuf-lite.a and libprotobuf.a

but error happened when link these libs to iOS project, the detail info as follows, can anybody know how to fix it? thanks

Undefined symbols for architecture x86_64:
  "nsync::nsync_mu_init(nsync::nsync_mu_s_*)", referenced from:
      tensorflow::Env::Env() in libtensorflow-core.a(env.o)
      __GLOBAL__sub_I_allocator.cc in libtensorflow-core.a(allocator.o)
      tensorflow::SessionFactory::Register(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tensorflow::SessionFactory*) in libtensorflow-core.a(session_factory.o)
      tensorflow::SessionFactory::GetFactory(tensorflow::SessionOptions const&, tensorflow::SessionFactory**) in libtensorflow-core.a(session_factory.o)
      tensorflow::TrackingAllocator::TrackingAllocator(tensorflow::Allocator*, bool) in libtensorflow-core.a(tracking_allocator.o)
      tensorflow::TrackingAllocator::TrackingAllocator(tensorflow::Allocator*, bool) in libtensorflow-core.a(tracking_allocator.o)
  "nsync::nsync_mu_lock(nsync::nsync_mu_s_*)", referenced from:
      tensorflow::FileSystemRegistryImpl::Register(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<tensorflow::FileSystem* ()>) in libtensorflow-core.a(env.o)
      tensorflow::FileSystemRegistryImpl::Lookup(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libtensorflow-core.a(env.o)
      tensorflow::FileSystemRegistryImpl::GetRegisteredFileSystemSchemes(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) in libtensorflow-core.a(env.o)
      tensorflow::CPUAllocator::AllocateRaw(unsigned long, unsigned long) in libtensorflow-core.a(allocator.o)
      tensorflow::CPUAllocator::DeallocateRaw(void*) in libtensorflow-core.a(allocator.o)
      tensorflow::CPUAllocator::GetStats(tensorflow::AllocatorStats*) in libtensorflow-core.a(allocator.o)
      tensorflow::SessionFactory::Register(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tensorflow::SessionFactory*) in libtensorflow-core.a(session_factory.o)
      ...
  "nsync::nsync_mu_unlock(nsync::nsync_mu_s_*)", referenced from:
      tensorflow::FileSystemRegistryImpl::Register(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<tensorflow::FileSystem* ()>) in libtensorflow-core.a(env.o)
      tensorflow::FileSystemRegistryImpl::Lookup(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libtensorflow-core.a(env.o)
      tensorflow::FileSystemRegistryImpl::GetRegisteredFileSystemSchemes(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) in libtensorflow-core.a(env.o)
      tensorflow::CPUAllocator::AllocateRaw(unsigned long, unsigned long) in libtensorflow-core.a(allocator.o)
      tensorflow::CPUAllocator::DeallocateRaw(void*) in libtensorflow-core.a(allocator.o)
      tensorflow::CPUAllocator::GetStats(tensorflow::AllocatorStats*) in libtensorflow-core.a(allocator.o)
      tensorflow::SessionFactory::Register(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tensorflow::SessionFactory*) in libtensorflow-core.a(session_factory.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by apollo-time** [comment]
try add ~/tensorflow/tensorflow/contrib/makefile/downloads/nsync/builds/lipo.ios.c++11/nsync.a into
other linker flags

**Comment by llyyun** [comment]
Yes, it works, thanks so much !!!

**Comment by sadlerjw** [comment]
@apollo-time @llyyun I'm having trouble too - I tried adding `-lnsync.a` (since I include `nsync.a` in the project), and also tried including it directly via `-l~/tensorflow/tensorflow/contrib/makefile/downloads/nsync/builds/lipo.ios.c++11/nsync.a` but I still get 
```
ld: library not found for -l~/tensorflow/tensorflow/contrib/makefile/downloads/nsync/builds/lipo.ios.c++11/nsync.a
```

Could you please be more specific about how to add this to the linker flags? (I'm not good with wrangling the compiler, sorry)

**Comment by bakercp** [comment]
Specifically 

```
make -f tensorflow/contrib/makefile/Makefile HOST_LDOPTS=tensorflow/contrib/makefile/downloads/nsync/builds/default.macos.c++11/nsync.a
```

**Comment by rribani** [comment]
I'm having the same issue. @apollo-time can you please be more specific? Thanks.
