### ISSUE TITLE
Why cannot use tf.Print() ?

### ISSUE THREAD

**Issue by MaeThird** [tensorflow/tensorflow#14609]
I just want to print out the executing data like this:
![t](https://user-images.githubusercontent.com/14851411/32872558-47be9c0c-ca7f-11e7-8e5d-6fa6796cb043.jpg)
But I got :"**Cannot assign a device for operation 'Print': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available**"
I'm sure this piece of code can work in python console with tf.device('/gpu:0') assigned:
Anyone help ?

**Comment by caisq** [comment]
@MaeThird Are you using TF eager mode by any chance?

**Comment by MaeThird** [comment]
@caisq no. This is just a test with my tedious codes.I thought there must be something wrong since it can print as excepted in console:
![t2](https://user-images.githubusercontent.com/14851411/32873268-feb1290e-ca82-11e7-8c91-187c4555a150.jpg)

**Comment by ppwwyyxx** [comment]
Putting `tf.Session()` under 'tf.device' has no effect at all. Putting `tf.Print` will probably give you the same error.
Enabling "allow_soft_placement" session option should avoid this error.

**Comment by MaeThird** [comment]
@ppwwyyxx  `allow_soft_placement=True` is ok! Thank U.
