### ISSUE TITLE
add Unspecified dimension to an existing tensor.

### ISSUE THREAD

**Issue by yupbank** [tensorflow/tensorflow#14603]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: osx
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:  ('v1.3.0-rc2-20-g0787eee', '1.3.0')
- **Python version**:   Python 2.7.11
- **Bazel version (if compiling from source)**: 0.7.0-homebrew
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

== cat /etc/issue ===============================================
Darwin Pengs-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== uname -a =====================================================
Darwin Pengs-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy (1.13.1)
protobuf (3.4.0)
tensorflow (1.3.0)
tensorflow-serving-api (1.3.0)
tensorflow-tensorboard (0.1.8)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.3.0
tf.GIT_VERSION = v1.3.0-rc2-20-g0787eee
tf.COMPILER_VERSION = v1.3.0-rc2-20-g0787eee
Sanity check: array([1], dtype=int32)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
ImportError: No module named platform

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tools/tf_env_collect.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
subgraph one have output:
```
state = Tensor(80, 80, 4)
```
subgraph two have input:
```
states = Tensor(None, 80, 80, 4)
```
right now `tf.expand_dims` can only make state a `Tensor(1, 80, 80, 4)` which can not being assigned to `states`. so that i have to do multiple sess execution and make two graph

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by cy89** [comment]
@yupbank can you please describe the specific error messages that you're getting? It seems like the static shape (1,80,80,4) ought to be OK to pass to a function that expects the dynamic shape (None,80,80,4).

**Comment by yupbank** [comment]
save i have a graph with two sub graph:
```
input_images = tf.placeholder(tf.float32, shape=[None, 1024, 2024, 3])
input_state = resize_and_folder_multi_image_into_one(input_images)
input_state.shape == (80, 80, 4)

input_states = tf.expand_dims(input_state, 0)

input_states.shape == (1, 80, 80, 4)

# i want to have a input_states acting both as middle node of graph but also can acting as input of ## a graph,  what operation can i do to make input_states.shape compatible with (None, 80, 80, 4)
 
action = q_function_accept_input_states_and_predict_actions(input_states)
```
this would work but will break when i pass multi `input_states`

this is my work around..  

but my case it's lucky that both function `resize_and_folder_multi_image_into_one` and  `q_function_accept_input_states_and_predict_actions`  are zero centered 
and  the walk around would fail if any of them are not zero centered.. 

https://github.com/yupbank/dqn-tf/blob/master/trainer/task.py#L59
https://github.com/yupbank/dqn-tf/blob/master/trainer/task.py#L64-L70

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
