### ISSUE TITLE
Which c++ source code Should I modify to allocate GPU memory dynamically?

### ISSUE THREAD

**Issue by rayjang** [tensorflow/tensorflow#14614]
I am using Spark with tensorflow. Spark make many tensorflow process, so I want tensorflow to allocate GPU memory dynamically. 
Adding the below code is **not workin**g for me
```
config = tf.ConfigProto() 
config.gpu_options.allow_growth=True 
sess = tf.Session(config=config)
```
Although I found  the way to set gpu memory fraction in 'tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc' ,
I want to set 'allow_growth' in c++ source.
Which part shoud I modify?

**Comment by rayjang** [comment]
solved it.

**Comment by rayjang** [comment]
solve it. 
change the source code manually and build it again by bazel.

**Comment by kerolos** [comment]
@rayjang could you please describe in more details how did you do this?
tensorflow::ConfigProto configProto;
 configProto.gpu_options();                   // ----> it gives to me one gpu_opention without any recieved arrguments.

thanks in advance.

**Comment by Ingerdev** [comment]
@kerolos:
tensorflow::ConfigProto config;
config.mutable_gpu_options()->set_allow_growth(...);
