### ISSUE TITLE
Undefined symbols "_cblas_sgemm" on iOS

### ISSUE THREAD

**Issue by llyyun** [tensorflow/tensorflow#14619]
Hello,

I downloaded the latest release 1.4.0 and builded it for iOS with build_all_ios.sh, and can successfully build libtensorflow-core.a, libprotobuf-lite.a and libprotobuf.a, and added the libtensorflow-core.a with -force_load

but error happened when link these libs to iOS project, the detail info as follows, can anybody know how to fix it? thanks
Undefined symbols for architecture arm64:
  "_cblas_sgemm", referenced from:
      tensorflow::Conv2DUsingGemmOp<float, tensorflow::(anonymous namespace)::Im2ColConvFunctor<float, float, float, FastGemmFunctor<float, float, float> > >::Compute(tensorflow::OpKernelContext*) in libtensorflow-core.a(conv_ops_using_gemm.o)
      tensorflow::FusedResizeConv2DUsingGemmOp<float, tensorflow::(anonymous namespace)::FusedResizeAndPadConvFunctor<float, float, float, FastGemmFunctor<float, float, float>, (tensorflow::(anonymous namespace)::SamplingMode)0>, true>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core.a(conv_ops_fused.o)
      tensorflow::FusedResizeConv2DUsingGemmOp<float, tensorflow::(anonymous namespace)::FusedResizeAndPadConvFunctor<float, float, float, FastGemmFunctor<float, float, float>, (tensorflow::(anonymous namespace)::SamplingMode)1>, false>::Compute(tensorflow::OpKernelContext*) in libtensorflow-core.a(conv_ops_fused.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by h8907283** [comment]
I don't think this is a lite issue. Maybe the iOS project is missing the Accelerate framework?

**Comment by llyyun** [comment]
Yes, it works after adding Accelerate framework
Thanks so much!!
