### ISSUE TITLE
Error in tf.image.extract_glimpse documentation

### ISSUE THREAD

**Issue by simo23** [tensorflow/tensorflow#14618]
Hi,
I think there is an error into the documentation of the **tf.image.extract_glimpse** into the **offsets** definition:

**offsets**: A Tensor of type float32. A 2-D integer tensor of shape [batch_size, 2] containing the **x, y** locations of the center of each window.

Are you sure it is not **y,x** instead? Also into the previous field:

**size**: A Tensor of type int32. A 1-D tensor of 2 elements containing the size of the glimpses to extract. **The glimpse height must be specified first, following by the glimpse width.**

So for **size** you place height (y) **before** width (x) which is the usual thing to do, but in **offsets** you require to have x (width) before y (height) which I think is wrong.

Thanks,
Andrea

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
