### ISSUE TITLE
Typo in How-To?

### ISSUE THREAD

**Issue by zplizzi** [tensorflow/tensorflow#1461]
I'm reading [this](https://www.tensorflow.org/versions/r0.7/how_tos/adding_an_op/index.html#implement-the-kernel-for-the-op) how-to page, and read the line:

`auto output = output_tensor->template flat<int32>();`

Is the `template flat` a typo, or some feature of C++ that I'm not familiar with? 

This line appears a few times in that section of the how-to.

**Comment by girving** [comment]
This is a Stackoverflow question, not a Github issue.  `template` is indeed a feature of C++.

**Comment by sesse** [comment]
More precisely: http://stackoverflow.com/questions/610245/where-and-why-do-i-have-to-put-the-template-and-typename-keywords

**Comment by zplizzi** [comment]
Apologies, I (wrongly) thought I knew more about C++ than I actually do, and assumed this was indeed a typo. Thanks for the link!
