### ISSUE TITLE
Tensorflow Lite Error: when convert frozen Graphdef  to flatbuffer format (.lite) 

### ISSUE THREAD

**Issue by charleys** [tensorflow/tensorflow#14621]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:master lastest
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:0.7

### Describe the problem
Tensorflow Lite Error: when convert frozen Graphdef  to flatbuffer format (.lite) 

ERROR：
2017-11-16 19:38:54.835542: F tensorflow/contrib/lite/toco/tflite/export.cc:294] Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If you have a custom implementation for them you can disable this error with --allow_custom_ops. Here is a list of operators for which you will need custom implementations: ArgMax.

Can anyone tell me how to solve this problem?

**Comment by andrehentz** [comment]
Unfortunately TF Lite doesn't support ArgMax yet. See [the list of supported ops](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/tf_ops_compatibility.md) 

Until it gets added, your best bet is to change your training script to avoid using ArgMax. You can also set --output_array in toco in a way that avoids the argmax node, but that might not be what you want anyway.

**Comment by andrehentz** [comment]
ArgMax is supported now. I'm closing this, but feel free to reopen if you still encounter problems.
