### ISSUE TITLE
Tensorflow Python 

### ISSUE THREAD

**Issue by Kingeng** [tensorflow/tensorflow#14636]
Hi This is my code for tensorflow_serve python client :

```
data = f.read()
data = base64.urlsafe_b64encode(data)
request = predict_pb2.PredictRequest()
request.model_spec.name = 'test'
request.model_spec.signature_name = 'serving_default'
data = tf.contrib.util.make_tensor_proto(data,shape=[1])

req=request.inputs['input'].CopyFrom(data)
```
could you please do me a favor and tell me how to convert(change) :
```

dtype: DT_STRING
tensor_shape {
dim {
size: 1
 }
}
string_val: "_9j_4AAQSkZJRgABAQEAYABgAAD_4QAWRXhpZgAASUk
```

to :
```

inputs: {
dtype: DT_STRING
tensor_shape {
dim {
size: 1
 }
}
string_val: "_9j_4AAQSkZJRgABAQEAYABgAAD_4QAWRXhpZgAASUk
```

**Comment by ttimasdf** [comment]
Feel sorry for maintainers overwhelmed by tons of issues like this. 🙊

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
