### ISSUE TITLE
Can I specify other gpu device not first one  in notebook?

### ISSUE THREAD

**Issue by brantbzhang** [tensorflow/tensorflow#1463]
Can I specify other gpu device not first one  in notebook?thanks!

**Comment by rdipietro** [comment]
I run this before creating a `Session`:

```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = gpu
```

`gpu` is a string. '0' for GPU 0, '0,2' for GPUs 0 and 2, etc.

Note if you do this then TensorFlow's '/gpu:0' will refer to the first in the list, not to the first GPU on the machine.

**Comment by girving** [comment]
This is a stackoverflow question, not a Github issue.
