### ISSUE TITLE
tf.bitwise.bitwise_and and friends have bad shape functions

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#14646]
The bitwise ops are componentwise and do normal broadcasting at the kernel level.  However, they claim unchanged shape during op registration:

    #define BINARY_BITWISE()                                                     \
      Input("x: T")                                                              \
          .Input("y: T")                                                         \
          .Output("z: T")                                                        \
          .SetIsCommutative()                                                    \
          .Attr("T: {int8, int16, int32, int64, uint8, uint16, uint32, uint64}") \
          .SetShapeFn(shape_inference::UnchangedShape)

To reproduce, do

    >>> import tensorflow as tf
    >>> tf.bitwise.bitwise_and(tf.zeros([3,1], dtype=tf.int32), tf.zeros([1,3], dtype=tf.int32))
    <tf.Tensor 'BitwiseAnd:0' shape=(3, 1) dtype=int32>

The result shape should be `(3, 3)`, not `(3, 1)`.

**Comment by yongtang** [comment]
@girving I think the shape function probably could be changed to `shape_inference::BroadcastBinaryOpShapeFn`? Added a PR #14678 for the fix.
