### ISSUE TITLE
Feature request: make TensorBoard side bar resizable?

### ISSUE THREAD

**Issue by rdipietro** [tensorflow/tensorflow#1464]
There's often a bunch of unused space on the right side of the TensorBoard interface, and if we have long directory names on the left (for example listing parameters during validation), they end up getting wrapped to multiple lines. Right now it's possible to adjust the sidebar width with Chrome's developer tools, but it seems natural for it to be resizable in the first place.

**Comment by girving** [comment]
@danmane: Want to comment?  I think we'd be happy to accept patches for this.

**Comment by danmane** [comment]
This is something I'd like to fix, but not super high priority. Patches would, indeed, be welcome.

**Comment by chihuahua** [comment]
I migrated this issue to tensorflow/tensorboard#62 because TensorBoard has moved into its own repo. Lets continue discussion there.

**Comment by michele-arrival** [comment]
> There's often a bunch of unused space on the right side of the TensorBoard interface, and if we have long directory names on the left (for example listing parameters during validation), they end up getting wrapped to multiple lines. Right now it's possible to adjust the sidebar width with Chrome's developer tools, but it seems natural for it to be resizable in the first place.

apologies for the obvious untimely reply in this thread. However, since this has not been implemented in tensorboard yet, I would like to try your method with Chrome's developer tools. Would you be so kind to share how that would be done plase?

thank you very much
