### ISSUE TITLE
tf.metrics.mean_relative error doesn't handle complex inputs

### ISSUE THREAD

**Issue by amir-mogh** [tensorflow/tensorflow#14658]
The offending line is here: 

https://github.com/tensorflow/tensorflow/blob/9c4bdb865452e418a1d69cd5f5cdccb51d6a0e1d/tensorflow/python/ops/metrics_impl.py#L1057

`array_ops.where` expects the second and third inputs to be of the same shape and **type**. Unfortunately, when the `labels` input is complex, `array_ops.zeros_like(labels)` returns an (unnecessarily) complex tensor, whereas the third input returns a float tensor. 

I haven't checked, but suspect similar problems might occur with other metrics (and perhaps elsewhere).

**Comment by amir-mogh** [comment]
Tagging my colleague @crjensen21.

**Comment by facaiy** [comment]
Hi, @amir-mogh . I open a PR to fix the issue, would you like to take a look?

**Comment by ymodak** [comment]
Closing this issue since a PR has been pushed. Please use the latest version of TensorFlow and feel free to reopen the issue if it still persists. Thanks!
