### ISSUE TITLE
Allow suppressing log output

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#1467]
Two recent requests recently to suppress logging on console [1](http://stackoverflow.com/questions/35911252/disable-tensorflow-debugging-information
), [2](http://stackoverflow.com/questions/35869137/avoid-tensorflow-print-on-standard-error)

Since TensorFlow uses Google logging library standard flags should work, ie "export GLOG_logtostderr=0" should turn off logging to console. However that doesn't work, I suspect these flags are explicitly overriden in code somewhere

**Comment by vrv** [comment]
We don't use the google logging library -- our python flags are just a wrapper over argparse, and we have no C++ flags at all.  There's an open issue already covering this, let me find it.

**Comment by vrv** [comment]
Duplicate of #1258
