### ISSUE TITLE
Couldn't find field google.protobuf.EnumDescriptorProto.EnumReservedRange.start

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#14689]
Im trying to run the following code 

```
import tensorflow as tf

print("Hello TensorFlow version", tf.__Version__)
```

It is firing the following error 

> Users/anaconda/envs/cnn/bin/python /Users/Downloads/rude-carnie/version.py
> Traceback (most recent call last):
>   File "/Users/Downloads/rude-carnie/version.py", line 1, in <module>
>     import tensorflow as tf
>   File "/Users/anaconda/envs/cnn/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import *
>   File "/Users/anaconda/envs/cnn/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52, in <module>
>     from tensorflow.core.framework.graph_pb2 import *
>   File "/Users/anaconda/envs/cnn/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
>     from google.protobuf import descriptor_pb2
>   File "/Users/anaconda/envs/cnn/lib/python3.6/site-packages/google/protobuf/descriptor_pb2.py", line 735, in <module>
>     options=None, file=DESCRIPTOR),
>   File "/Users/anaconda/envs/cnn/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 501, in __new__
>     return _message.default_pool.FindFieldByName(full_name)
> KeyError: "Couldn't find field google.protobuf.EnumDescriptorProto.EnumReservedRange.start"

**Comment by duynam1992** [comment]
14689

**Comment by andyjslee** [comment]
I'm having the same problem.

**Comment by carlthome** [comment]
Try reinstalling the protobuf version that TensorFlow 1.4 wants by running:

```
pip uninstall protobuf
pip install tensorflow
python -c "import tensorflow"
```

**Comment by TarrySingh** [comment]
No, your answer is incorrect. Tensorflow 1.4 uninstalls protobuf and reinstalls it so I think we need to dig deeper into this.

**Comment by carlthome** [comment]
Do you have multiple installs of protobuf (different versions) in the same Python environment?

**Comment by TarrySingh** [comment]
On my mac it all works like a charm including eager execution with nightly build update. It's just on my Ubuntu GPU box , its dying :/

I'll see if downgrading to 3.4.0 gives some positive results.

**Comment by TarrySingh** [comment]
OK, here is the solution -- funny but worked for me 👯‍♂️ 

I uninstalled protobuf 3.5.0.post1, which comes with TF 1.4.1 distro, installed 3.4.0 release and then installed 3.5.0.post1.

`
deeplearn@Ubuntu-1604-xenial-64-minimal:~$ pip install protobuf==3.4.0
Requirement already satisfied: protobuf==3.4.0 in ./anaconda3/lib/python3.6/site-packages
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from protobuf==3.4.0)
Requirement already satisfied: six>=1.9 in ./anaconda3/lib/python3.6/site-packages (from protobuf==3.4.0)
deeplearn@Ubuntu-1604-xenial-64-minimal:~$ pip install protobuf==3.5.0.post1
Collecting protobuf==3.5.0.post1
  Using cached protobuf-3.5.0.post1-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9 in ./anaconda3/lib/python3.6/site-packages (from protobuf==3.5.0.post1)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from protobuf==3.5.0.post1)
Installing collected packages: protobuf
  Found existing installation: protobuf 3.4.0
    Uninstalling protobuf-3.4.0:
      Successfully uninstalled protobuf-3.4.0
Successfully installed protobuf-3.5.0.post1
deeplearn@Ubuntu-1604-xenial-64-minimal:~$ 
`
as a result, this baby's working :)

`
![screen shot 2017-11-21 at 19 36 10](https://user-images.githubusercontent.com/7202199/33189935-02ec42ee-d0a8-11e7-8ad0-f12c2595c909.png)

**Comment by zeyu-h** [comment]
I run into the same problem, and your solution works for me.

**Comment by TarrySingh** [comment]
Glad to hear 😃

**Comment by wangzheqie** [comment]
check if your `protobuf` are installed  deplicately like: 

*  sudo apt-get install python3-protobuf  `or` python-protobuf 
*  pip install protobuf  `or`  pip3 install protobuf 

If both installed, uninstall one of them

**Comment by Zumbalamambo** [comment]
I tried all... i tried reinstalling protobuf, tensorflow but still the same issue :(

**Comment by evindj** [comment]
Thanks @TarrySingh Your solution worked for me

**Comment by xploiter-projects** [comment]
Thank you @TarrySingh. Your solution works like charm ^_^

**Comment by gokceneraslan** [comment]
In my case `protobuf` from `conda-forge` was the reason for the error. I removed it via `conda remove protobuf` and reinstalled protobuf via pip.

**Comment by TarrySingh** [comment]
Awesome to hear that 👌

@zumbalambo — you need to share your error.

**Comment by RakshakTalwar** [comment]
@TarrySingh your solution worked for me as well!

**Comment by hoangcuong2011** [comment]
Thanks @TarrySingh, pip install protobuf==3.4.0 solved the problem!

**Comment by danielfleischer** [comment]
@TarrySingh didn't immediately help but upgrading all pip packages did:

`pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U`

Hope it helps.

**Comment by lgrcyanny** [comment]
came with the same issue:
conda remove protobuf
pip install tensorflow=1.4.0
pip install protobuf==3.4.0
pip install protobuf==3.5.0.post1
python -c "import tensorflow"
thanks @gokceneraslan and @TarrySingh

**Comment by Kornel** [comment]
In my case tf 1.4.1 works only with protobuf 3.4.0:

```
python -c "import tensorflow as tf; print(tf.__version__); import google.protobuf as pb; print(pb.__version__)"
1.4.1
3.4.0
```

Upgrading protobuf to 3.5.x results in `KeyError: "Couldn't find field google.protobuf.EnumDescriptorProto.EnumReservedRange.start"`

**Comment by angshine** [comment]
I find this solution really helpful:
1. uninstall all the protobuf on your machine (both from anaconda and pip)
`pip uninstall protobuf`
`conda remove protobuf`
you may try them twice to make sure all the version of protobuf have been removed
2. install protobuf using pip:
`pip install protobuf==3.5.0.post1`

**Comment by yoyoalphax** [comment]
1、remove all the protobuf, by pip list, conda list and so on
2、install a new one

**Comment by Alexuan** [comment]
@TarrySingh thanks 大傻猫，你真棒👍
