### ISSUE TITLE
MemoryError from tensorflow.contrib.learning.datasets in Python3

### ISSUE THREAD

**Issue by quantitative-technologies** [tensorflow/tensorflow#14698]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 17.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.4.0-rc1-11-g130a514 1.4.0
- **Python version**: 3.5.3
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: python -c "import tensorflow as tf; tf.contrib.learn.datasets.load_dataset('dbpedia', size='full')"

### Describe the problem
The command results in an MemoryError, even though the dataset easily fits into my memory (64GB), and also works with Python 2. 

### Source code / logs
Here is the traceback:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/james/python3.5-ve/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/__init__.py", line 71, in load_dataset
    return DATASETS[name](size, test_with_fake_data)
  File "/home/james/python3.5-ve/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/text_datasets.py", line 65, in load_dbpedia
    train_path, target_dtype=np.int32, features_dtype=np.str, target_column=0)
  File "/home/james/python3.5-ve/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 72, in load_csv_without_header
    data = np.array(data)
MemoryError

**Comment by satendrapratap** [comment]
Any update on this?

**Comment by drpngx** [comment]
I think we'd need a bit more info about the code you're using.

**Comment by martinwicke** [comment]
I just tried with 1.4.0, I cannot reproduce this. I'll close, please reopen if you have more information.

**Comment by satendrapratap** [comment]
Please use the below files to recreate the issue. Use following command(copy rnn_tc.txt as rnn_tc.py first):

$python3 rnn_tc.py

We got following messages:

$ python3 rnn_tc.py > tc.log4
Traceback (most recent call last):
  File "rnn_tc.py", line 62, in <module>
    'dbpedia', size='big')
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/datasets/__init__.py", line 71, in load_dataset
    return DATASETS[name](size, test_with_fake_data)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/datasets/text_datasets.py", line 65, in load_dbpedia
    train_path, target_dtype=np.int32, features_dtype=np.str, target_column=0)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 72, in load_csv_without_header
    data = np.array(data)
**MemoryError**


[rnn_tc.txt](https://github.com/tensorflow/tensorflow/files/1535219/rnn_tc.txt)

**Comment by satendrapratap** [comment]
python3 tensorflow version:
1.3.0

**Comment by martinwicke** [comment]
Since you're running an old version of TensorFlow, this may be fixed in 1.4. Can you check whether this is fixed in 1.4? It works fine for me, but I am using Py2. That's the only difference I can think of. How much memory is in the machine you're using?

**Comment by martinwicke** [comment]
Oh wait, you said that. Sorry. I take that back. Let me test again with Py3.

**Comment by martinwicke** [comment]
I just tried with TF 1.4 and Py 3.6.3, and I don't see this failure.

**Comment by satendrapratap** [comment]
Did you get the error (using rnn_tc.txt)  with TF 1.3 and Py3 and did not get that error with TF 1.4 and Py 3.6.3 ?? Is this what you are saying?

**Comment by martinwicke** [comment]
I did not get the error (using your repro `python -c "import tensorflow as tf; tf.contrib.learn.datasets.load_dataset('dbpedia', size='full')"`) in TensorFlow 1.4, Python 3.6.3.

**Comment by quantitative-technologies** [comment]
I just did a fresh install of python 3.6.3 and tensorflow, and the issue is still present. For example:

(python-3.6.3-ve) ___$ python -V
Python 3.6.3
(python-3.6.3-ve) ___$ python -c 'import tensorflow as tf; print(tf.__version__)'
/home/james/.pyenv/versions/3.6.3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
1.4.1

Now, running python3 rnn_tc.py gives the error as above.

Please re-open this issue.

**Comment by martinwicke** [comment]
Does `python -c "import tensorflow as tf; tf.contrib.learn.datasets.load_dataset('dbpedia', size='full')"` trigger the problem for you?

**Comment by quantitative-technologies** [comment]
Yes, as before:

`(python-3.6.3-ve) ___$ python -c "import tensorflow as tf; tf.contrib.learn.datasets.load_dataset('dbpedia', size='full')"

/home/james/.pyenv/versions/3.6.3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/james/.pyenv/versions/3.6.3/envs/python-3.6.3-ve/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/__init__.py", line 71, in load_dataset
    return DATASETS[name](size, test_with_fake_data)
  File "/home/james/.pyenv/versions/3.6.3/envs/python-3.6.3-ve/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/text_datasets.py", line 65, in load_dbpedia
    train_path, target_dtype=np.int32, features_dtype=np.str, target_column=0)
  File "/home/james/.pyenv/versions/3.6.3/envs/python-3.6.3-ve/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 72, in load_csv_without_header
    data = np.array(data)
MemoryError
`

**Comment by martinwicke** [comment]
What sort of machine are you running this on? Can you check 

`time --verbose python -c "import tensorflow as tf; tf.contrib.learn.datasets.load_dataset('dbpedia', size='full')"`?

I'd like to understand why I cannot reproduce this.

**Comment by quantitative-technologies** [comment]
It is a System 76 laptop: 

`(python-3.6.3-ve) ___$ uname -a` 
gives
`Linux james-Bonobo-WS 4.10.0-42-generic #46-Ubuntu SMP Mon Dec 4 14:38:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

And: 

    (python-3.6.3-ve) ___$ /usr/bin/time --verbose python -c "import tensorflow as tf; tf.contrib.learn.datasets.load_dataset('dbpedia', size='full')" 
    /home/james/.pyenv/versions/3.6.3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
      return f(*args, **kwds)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/james/.pyenv/versions/3.6.3/envs/python-3.6.3-ve/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/__init__.py", line 71, in load_dataset
        return DATASETS[name](size, test_with_fake_data)
      File "/home/james/.pyenv/versions/3.6.3/envs/python-3.6.3-ve/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/text_datasets.py", line 65, in load_dbpedia
    train_path, target_dtype=np.int32, features_dtype=np.str, target_column=0)
      File "/home/james/.pyenv/versions/3.6.3/envs/python-3.6.3-ve/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 72, in load_csv_without_header
    data = np.array(data)
    MemoryError
    Command exited with non-zero status 1
	Command being timed: "python -c import tensorflow as tf; tf.contrib.learn.datasets.load_dataset('dbpedia', size='full')"
	User time (seconds): 9.28
	System time (seconds): 0.80
	Percent of CPU this job got: 103%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:09.71
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1554848
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 398832
	Voluntary context switches: 83
	Involuntary context switches: 106919
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1

**Comment by martinwicke** [comment]
I'm on a Mac, and I get "7516360704  maximum resident set size" (~7.5G), which is way more than your 1.5G. I agree that is a lot. There are probably a few unnecessary copies in there. 

We'll gladly take fixes that reduce the memory consumption.

**Comment by quantitative-technologies** [comment]
OK, but the 1.5G maximum resident set size still does not explain the `MemoryError` since this happens when there is > 10G of unused memory. Also the error only occurs with python3 and not python2.

Yes, the dataset should be way smaller than a G, but I haven't had a chance to look into fixing it.

**Comment by pkhlop** [comment]
If somebody sill have the issue
https://stackoverflow.com/a/49824034/604530
