### ISSUE TITLE
tf.train.Scaffold does't accept global_step, and therefore only one checkpoint (0) is saved

### ISSUE THREAD

**Issue by millskyle** [tensorflow/tensorflow#14697]
Disclaimer: Issue #10661 might be related. 

When I create a Scaffold object and attempt to use it in a MonitoredTrainingSession, there is no ability to specify the global step.  As a consequence (I think), only one checkpoint is created, labeled "model.ckpt-0". 

As I understand it, the code below (taken from a custom class I've written...hence the `self`s) should save a new checkpoint every 10 seconds, but only actually creates a single checkpoint at the start of training, and then never again.

    self.GLOBAL_STEP = tf.train.get_or_create_global_step()
    self.init_op = tf.global_variables_initializer()       
    self.Saver = tf.train.Saver()

    self.Scaffold = tf.train.Scaffold( init_op=self.init_op,
                                       saver=self.Saver
                                   #   global_step=self.GLOBAL_STEP  
                                           )

    self.sess = tf.train.MonitoredTrainingSession( master='',
                                                   is_chief=True,
                                                   scaffold = self.Scaffold,
                                                   checkpoint_dir='./chkpt/',
                                                   save_checkpoint_secs=10,
                                                       )

If I uncomment the `global_step=...` line above, I get an error (as expected) since `Scaffold.__init__()` doesn't take a global_step argument, however shouldn't it?

**Comment by tatatodd** [comment]
Yup, I think this is the same issue as #10661.  Closing this out, and pinging the other one.
