### ISSUE TITLE
add multiple-machine support

### ISSUE THREAD

**Issue by trevorboydsmith** [tensorflow/tensorflow#147]
Many projects require more resources than are available in a single machine. **Does the current opensource release of Tensorflow support processing that spans multiple-machines?**

I ask because the main webpage (says single machine) seems to conflict[1] with the Tensorflow whitepaper pdf (says multiple machines).

If the current opensource tensorflow does not support multiple-machine execution but the closed-sourced version does. **Is there any plan to release an opensource version that supports multiple machines? Is there an approximate timeframe?**

[1]
- The [tensorflow.org main webpage](http://tensorflow.org/) says "This open source release supports single machines". Also the [Resources/FAQ says "single computer"](http://tensorflow.org/resources/faq.md).
- But then when you [read the Tensorflow whitepaper](http://download.tensorflow.org/paper/whitepaper2015.pdf), the whitepaper indicates in many places that Tensorflow can run across multiple machines. See these quotes from the whitepaper:
 - "large-scale  distributed  systems  of  hundreds of machines" and "using
many  hundreds  of  machines"
 - " extends  it with  support  for  an environment where the client, the master, and the workers can all be in different processes on different machines"
 - "use remote communication mechanisms such as TCP or RDMA to move data across machine boundaries"

**Comment by danmane** [comment]
The current release doesn't support multiple machines, but we're working on it. Please see #23 for more details.
