### ISSUE TITLE
Android Demo Building Issue

### ISSUE THREAD

**Issue by islamoc** [tensorflow/tensorflow#1471]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Ubuntu 14.04

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

If installed from sources, provide the commit hash:

### Steps to reproduce
1. I have followed step by step the Android Demo installation

### What have you tried?
1. changing the ndk version

### Logs or other output that would be helpful
ERROR: /home/islamoc/tensorflow/tensorflow/examples/android/BUILD:65:1: Processing resources failed: resources_processor failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/android/resources_processor --buildToolsVersion 23.0.1 --aapt bazel-out/host/bin/external/androidsdk/aapt_binary --annotationJar ... (remaining 14 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Mar 12, 2016 4:13:36 AM com.google.devtools.build.android.AndroidResourceProcessingAction main
SEVERE: Error during merging resources
Error: Failed to run command:
        bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp4328338078871950922/tmp-deduplicated/tensorflow/examples/android/res/drawable-hdpi/ic_launcher.png -o /tmp/android_resources_tmp4328338078871950922/merged_resources/drawable-hdpi-v4/ic_launcher.png
Error Code:
        1
Output:
        bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory

        at com.android.ide.common.res2.MergeWriter.end(MergeWriter.java:54)
        at com.android.ide.common.res2.MergedResourceWriter.end(MergedResourceWriter.java:113)
        at com.android.ide.common.res2.DataMerger.mergeData(DataMerger.java:291)
        at com.android.ide.common.res2.ResourceMerger.mergeData(ResourceMerger.java:48)
        at com.google.devtools.build.android.AndroidResourceProcessor.mergeData(AndroidResourceProcessor.java:390)
        at com.google.devtools.build.android.AndroidResourceProcessingAction.main(AndroidResourceProcessingAction.java:321)
Caused by: com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp4328338078871950922/tmp-deduplicated/tensorflow/examples/android/res/drawable-hdpi/ic_launcher.png -o /tmp/android_resources_tmp4328338078871950922/merged_resources/drawable-hdpi-v4/ic_launcher.png
Error Code:
        1
Output:
        bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory

        at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:123)
        at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:96)
        at com.android.ide.common.internal.AaptCruncher.crunchPng(AaptCruncher.java:58)
        at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:188)
        at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:139)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 369.392s, Critical Path: 319.96s

**Comment by Muaazbinsaeed** [comment]
Does it not work on Ubuntu 15.10 ?

**Comment by islamoc** [comment]
No idea I could not build it on Ubuntu 14.04 I did not test it on 15.10
I think it is dependencies problem

**Comment by andrewharp** [comment]
You may need to run <sdk_path>/tools/android and ensure that you have the 23.0.1 Android build tools installed. Alternatively, if you already have a version >= 21, you can try changing the setting in WORKSPACE and point to that.

**Comment by islamoc** [comment]
Build tools 23.0.1 is installed normally
```
/home/islamoc/android-sdk-linux/build-tools# ls
23.0.1
```

**Comment by islamoc** [comment]
After updating the SDK I got this error

```
ERROR: /home/islamoc/tensorflow/tensorflow/core/BUILD:647:1: C++ compilation of rule '//tensorflow/core:android_tensorflow_lib' failed: arm-linux-androideabi-gcc failed: error executing command external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -fstack-protector-strong -fpic -ffunction-sections -funwind-tables ... (remaining 63 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
arm-linux-androideabi-gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://source.android.com/source/report-bugs.html> for instructions.
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by andrewharp** [comment]
What does it say if you try building with --verbose_failures?

**Comment by islamoc** [comment]
This

```
ERROR: /home/islamoc/tensorflow/tensorflow/examples/android/BUILD:65:1: Processing resources failed: resources_processor failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/android/resources_processor --buildToolsVersion 23.0.1 --aapt bazel-out/host/bin/external/androidsdk/aapt_binary --annotationJar external/androidsdk/tools/support/annotations.jar --androidJar external/androidsdk/platforms/android-23/android.jar --primaryData tensorflow/examples/android/res:tensorflow/examples/android/assets:tensorflow/examples/android/AndroidManifest.xml --srcJarOutput bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/tensorflow_demo.srcjar --proguardOutput bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/proguard/tensorflow_demo/_tensorflow_demo_proguard.cfg --packagePath bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/tensorflow_demo.ap_ --debug --packageForR org.tensorflow.demo): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: resources_processor failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/android/resources_processor --buildToolsVersion 23.0.1 --aapt bazel-out/host/bin/external/androidsdk/aapt_binary --annotationJar external/androidsdk/tools/support/annotations.jar --androidJar external/androidsdk/platforms/android-23/android.jar --primaryData tensorflow/examples/android/res:tensorflow/examples/android/assets:tensorflow/examples/android/AndroidManifest.xml --srcJarOutput bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/tensorflow_demo.srcjar --proguardOutput bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/proguard/tensorflow_demo/_tensorflow_demo_proguard.cfg --packagePath bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/tensorflow_demo.ap_ --debug --packageForR org.tensorflow.demo): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Mar 16, 2016 12:22:57 PM com.google.devtools.build.android.AndroidResourceProcessingAction main
SEVERE: Error during merging resources
Error: Failed to run command:
        bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp4150814921996220848/tmp-deduplicated/tensorflow/examples/android/res/drawable-mdpi/ic_launcher.png -o /tmp/android_resources_tmp4150814921996220848/merged_resources/drawable-mdpi-v4/ic_launcher.png
Error Code:
        1
Output:
        bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory

        at com.android.ide.common.res2.MergeWriter.end(MergeWriter.java:54)
        at com.android.ide.common.res2.MergedResourceWriter.end(MergedResourceWriter.java:113)
        at com.android.ide.common.res2.DataMerger.mergeData(DataMerger.java:291)
        at com.android.ide.common.res2.ResourceMerger.mergeData(ResourceMerger.java:48)
        at com.google.devtools.build.android.AndroidResourceProcessor.mergeData(AndroidResourceProcessor.java:390)
        at com.google.devtools.build.android.AndroidResourceProcessingAction.main(AndroidResourceProcessingAction.java:321)
Caused by: com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp4150814921996220848/tmp-deduplicated/tensorflow/examples/android/res/drawable-mdpi/ic_launcher.png -o /tmp/android_resources_tmp4150814921996220848/merged_resources/drawable-mdpi-v4/ic_launcher.png
Error Code:
        1
Output:
        bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory

        at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:123)
        at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:96)
        at com.android.ide.common.internal.AaptCruncher.crunchPng(AaptCruncher.java:58)
        at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:188)
        at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:139)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Slow read: a 376492-byte read from /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/_objs/protos_all_cc/tensorflow/core/framework/step_stats.pb.o took 7615ms.
Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 61.284s, Critical Path: 46.00s
```

**Comment by andrewharp** [comment]
Here's the contents of my aapt_binary script:
#!/bin/bash -eu
SDK=${0}.runfiles/external/androidsdk
exec ${SDK}/build-tools/23.0.1/aapt

I'm not sure exactly what's going on, but it appears that on your system, "${0}" (the path to the current bash executable) is defined to be: `/root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary`

You don't appear to be running as root given the path to your build file (`/home/islamoc/tensorflow/tensorflow/examples/android/BUILD`), so it's not surprising that the aapt file can't be found due to not existing or not having permissions. Are you running bazel with su/sudo, or have you given the bazel any special permissions or anything like that could cause such a mixup?

**Comment by islamoc** [comment]
The problem was in my system it is 64bit the aapt bin was 32bit I fixed the problem now I m getting this

```
ERROR: /home/islamoc/tensorflow/tensorflow/core/BUILD:647:1: C++ compilation of rule '//tensorflow/core:android_tensorflow_lib' failed: arm-linux-androideabi-gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -fstack-protector-strong -fpic -ffunction-sections -funwind-tables -no-canonical-prefixes -fno-canonical-system-headers '-march=armv7-a' '-mfpu=vfpv3-d16' '-mfloat-abi=softfp' -iquote . -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles -iquote external/re2 -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/re2 -iquote external/bazel_tools -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/eigen_archive -isystem external/re2 -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/re2 -isystem external/bazel_tools/tools/cpp/gcc3 -isystem google/protobuf/src -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/google/protobuf/src -isystem third_party/eigen3 -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-db7b61411772 -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/eigen_archive/eigen-eigen-db7b61411772 '-mfpu=neon' '-std=c++11' '-DMIN_LOG_LEVEL=0' -DTF_LEAN_BINARY -O2 '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm' -isystem external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9/include -isystem external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9/include-fixed -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward '-frandom-seed=bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/_objs/android_tensorflow_lib/tensorflow/core/kernels/cwise_op_sub.o' -MD -MF bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/_objs/android_tensorflow_lib/tensorflow/core/kernels/cwise_op_sub.d -c tensorflow/core/kernels/cwise_op_sub.cc -o bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/_objs/android_tensorflow_lib/tensorflow/core/kernels/cwise_op_sub.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4: arm-linux-androideabi-gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/a492118e4b53c9510c58595e273faae6/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -fstack-protector-strong -fpic -ffunction-sections -funwind-tables -no-canonical-prefixes -fno-canonical-system-headers '-march=armv7-a' '-mfpu=vfpv3-d16' '-mfloat-abi=softfp' -iquote . -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles -iquote external/re2 -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/re2 -iquote external/bazel_tools -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/eigen_archive -isystem external/re2 -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/re2 -isystem external/bazel_tools/tools/cpp/gcc3 -isystem google/protobuf/src -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/google/protobuf/src -isystem third_party/eigen3 -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-db7b61411772 -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/eigen_archive/eigen-eigen-db7b61411772 '-mfpu=neon' '-std=c++11' '-DMIN_LOG_LEVEL=0' -DTF_LEAN_BINARY -O2 '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm' -isystem external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9/include -isystem external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9/include-fixed -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward '-frandom-seed=bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/_objs/android_tensorflow_lib/tensorflow/core/kernels/cwise_op_sub.o' -MD -MF bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/_objs/android_tensorflow_lib/tensorflow/core/kernels/cwise_op_sub.d -c tensorflow/core/kernels/cwise_op_sub.cc -o bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/_objs/android_tensorflow_lib/tensorflow/core/kernels/cwise_op_sub.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
arm-linux-androideabi-gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://source.android.com/source/report-bugs.html> for instructions.
Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 208.522s, Critical Path: 206.77s
```

**Comment by andrewharp** [comment]
Status 4 is an OOM issue. Try increasing your swapspace, giving bazel more memory/decreasing memory usage, or running fewer simultaneous jobs.

See http://stackoverflow.com/questions/34382360/decrease-bazel-memory-usage?rq=1 for more info.

**Comment by islamoc** [comment]
I will try those recommendations and get back to you

**Comment by islamoc** [comment]
@andrewharp Thank you it worked :D with 2 jobs

**Comment by andrewharp** [comment]
Awesome! Glad that did the trick :)

**Comment by islamoc** [comment]
@andrewharp one more question please can we build the project for Android 4.4.2 ?

**Comment by andrewharp** [comment]
We use the camera2 API in the official repo, which requires API 21+.

However, @hamidb has a fork of TF using the old android.hardware.Camera that should run on devices api 15+. See https://github.com/hamidb/tensorflow/blob/api20/tensorflow/examples/android/src/org/tensorflow/demo/CameraConnectionFragment.java for the relevant changes.

**Comment by abhigoku10** [comment]
@islamoc  hi since you i have build android on ubuntu 14.04 it would be a great help if u you just give a brief steps on building it with its   the dependent versions . I have struggling from 1 week and no were near close to build the demo app
