### ISSUE TITLE
tensorflow/contrib/lite/download_dependencies.sh does not finish without error!

### ISSUE THREAD

**Issue by albushuang** [tensorflow/tensorflow#14718]
for tensorflow/contrib/lite/download_dependencies.sh, I can not run successfully with commit 049a34d692095b7e137bca27d2445415314ceaf7.
And I rollback to 4b4b51cdd9e8c3c748b76dd8649bcd5556e84d76, everything is good.

**Comment by miaout17** [comment]
Hi @albushuang , could you post the error message here?

**Comment by miaout17** [comment]
Thanks for reporting. I'm having #14631 to fix it.

**Comment by miaout17** [comment]
Fixed in #14734
