### ISSUE TITLE
Coverage for NMT

### ISSUE THREAD

**Issue by rajarsheem** [tensorflow/tensorflow#14717]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 14.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.3
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: 4.8.4
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: NVIDIA TITAN X (12GB)
- **Exact command to reproduce**:  NA

Modelling coverage is a very useful feature in NMT to reduce over-translations.

Ref.: 
https://www.aclweb.org/anthology/P/P16/P16-1008.pdf,
https://arxiv.org/pdf/1704.04368.pdf

Is this feature available right now or, if not, how can I hack the current attention mechanism (say, Bahadanau) to add this feature ?

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by hpulfc** [comment]
Coverage will fix the internal bias defect in beamsearchdecode and strongly recommends implementation

**Comment by rajarsheem** [comment]
@tatatodd this WAS a feature request.
