### ISSUE TITLE
NameError: global name 'xrange' is not defined in Python 3 - and solution proposal

### ISSUE THREAD

**Issue by guyko81** [tensorflow/tensorflow#14725]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04 Docker image
- **TensorFlow installed from (source or binary)**: pip install
- **TensorFlow version (use command below)**: 1.4.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/contrib/boosted_trees/examples/boston.py

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Running the example code under python 3.6 in Docker environment I got xrange error: NameError: global name 'xrange' is not defined in Python 3

I propose to change every xrange to range under the 3.x versions:
# patch for xrange
find /opt/conda/lib/python3.6/site-packages/tensorflow/contrib/boosted_trees -type f -print0 | xargs -0 sed -i 's/ xrange(/ range(/g'

### Source code / logs
NameError: global name 'xrange' is not defined in Python 3

**Comment by mrry** [comment]
I think we use `from six.moves import xrange` elsewhere in the codebase to handle this incompatibility, without the potential for a performance regression on Python 2.7. Any file that uses `xrange()` should have this import at the top.

**Comment by guyko81** [comment]
It didn't work for me, that's why I used this workaround.

**Comment by sshrdp** [comment]
This issue has already been fixed (cc2030dfd4842bb8ecdd1f84a7f18ae65734a90f) but unfortunately didn't make it to 1.4.

**Comment by guyko81** [comment]
oh, thank you then :)

**Comment by neel17** [comment]
You can try to change the code line 44 in 
`for i in xrange(self.num_pages):`
change it to 
`for i in list(range(self.num_pages)):`

I hope this should work and kindly restart your python before running the code.

**Comment by SUNILARAVA** [comment]
> I think we use `from six.moves import xrange` elsewhere in the codebase to handle this incompatibility, without the potential for a performance regression on Python 2.7. Any file that uses `xrange()` should have this import at the top.

Thanks it worked for Python 2.7

**Comment by ManuelNevado** [comment]
> I think we use `from six.moves import xrange` elsewhere in the codebase to handle this incompatibility, without the potential for a performance regression on Python 2.7. Any file that uses `xrange()` should have this import at the top.

Thanks it worked for me :)
