### ISSUE TITLE
Make a copy of a model

### ISSUE THREAD

**Issue by Erichliu00** [tensorflow/tensorflow#14726]
Hi,  is there a canonical method in Tensorflow for this? For example, in Keras, we can use keras.models.clone_model for this purpose.  I though that model's copy would be such a nice feature, since copy.deepcopy does not work for me in Tensorflow. 
I want to copy weights from this model to another model of identical structure,  and I do not want to save a model then restore it to another instance for this situation. Specifically, the situation at every iteration we train model1 then make model2 as a copy of current model1, adding noise to model1 parameters and sample from model2 and then use these samples to update model1.
```
Class Model1(object):
    def method1(self):
        ....
    def method2(self):
        ....
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Erichliu00** [comment]
just use `from copy import copy` and do `copy(model)` instead of deep copy.

**Comment by dennismckinnon** [comment]
@Erichliu00 I'm not sure using copy works to solve the problem fully. If we use copy then we can't change the weights of the one model without it affecting the weights of the other model. For example:

```
W = tf.Variable(tf.constant(0.2))
b= tf.Variable(tf.constant(0.5))
x = tf.placeholder(tf.float32)
y = W*x+b

train = tf.assign(W, A2)
y2 = copy(y)
```

the train here is just to mock what happens if we have the variable changed.

```
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run([y, y2], feed_dict={x:1}))
    sess.run(train)
    print(sess.run([y, y2], feed_dict={x:1}))
    y2 = copy(y)
    print(sess.run([y, y2], feed_dict={x:1}))
```

Prints out
```
[0.69999999, 0.69999999]
[1.0, 1.0]  -> This should be [1, 0.69999999] if a true copy was made
[1.0, 1.0]
```

So I don't know how to make a clone of a model I would love to know though... I currently have very awkward work arounds for it. If you do find out a way please let me know

**Comment by Erichliu00** [comment]
@dennismckinnon , 

```
import tensorflow as tf
from copy import copy

v1 = tf.Variable(2.0)
v_copy1 = tf.Variable(v1)
v_copy2 = tf.identity(v1)
v_copy3 = copy(v1)
v_copy4 = v1
init = tf.Variable(0.0)
v_copy5 = init.assign(v1)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
a, b, c, d, e= sess.run([v_copy1, v_copy2, v_copy3, v_copy4, v_copy5])
print(a, b, c, d, e) # 2.0 2.0 2.0 2.0 2.0

sess.run(tf.assign(v1, 3.0))
a, b, c, d, e= sess.run([v_copy1, v_copy2, v_copy3, v_copy4, v_copy5])
print(a, b, c, d, e) # 2.0 3.0 3.0 3.0 3.0
```
Thus, for copying variable, one way is `v_copy1 = tf.Variable(v1)`, for copying model, you can create two instances and inistialize the copy model's variable using such way.

**Comment by amina11** [comment]
@Erichliu00  Did you find the way to clone the model? or you stayed with the last solution you wrote up there, "ou can create two instances and initialize the copy model's variable using such way."?  I  have the same problem and I wanna know if there is a way to directly clone the model.

**Comment by KrantiK94** [comment]
I have tried it this way:

`variables = tf.trainable_variables()
		for var1 in variables:
			if "pred/" in var1.name:
				trained_var = [var2 for var2 in tf.global_variables() if var2.op.name in str.replace(var1.name, "pred/", "")][0]
				value =sess.run(trained_var)
				sess.run(tf.assign(var1, value))`

For this to work I put all varaibles of the target model in the scope "pred" and the source model was in the same wider scope. By getting the value of the source via sess.run() you get the hard copy of the values and no references which can then be assigned to your target.

**Comment by baregawi** [comment]
This seems unnecessarily difficult. Is the expectation that everyone creates their own Keras-like wrapper to try to separate sessions and make models easy to copy? Keras is the most reasonable API to Tensorflow I have seen but it seems barely supported.

In any case, Tensorflow has otherwise been great work and I realize that wasn't easy so thank you!
