### ISSUE TITLE
Unhelpful error for dynamic_rnn in version 1.4.0

### ISSUE THREAD

**Issue by parsa-saadatpanah** [tensorflow/tensorflow#14729]
This code:
```python
import tensorflow as tf

x = tf.constant([
		[[0,0],[5,0],[1,0],[1,0],[2,3],[4,0]],
		[[0,0],[0,0],[1,3],[2,0],[0,0],[0,0]]
	], dtype=tf.int32) #changing this to tf.float32 solves the problem


cell = tf.nn.rnn_cell.LSTMCell(num_units=15) 
initial_state = cell.zero_state(tf.shape(x)[0], dtype=tf.float32)
outputs, state = tf.nn.dynamic_rnn(cell, x, initial_state=initial_state, dtype=tf.float32)

init_op = tf.group(tf.global_variables_initializer(),
		tf.local_variables_initializer())

with tf.Session() as sess:
	sess.run(init_op)
	print(sess.run([outputs, state]))
```
Does not work, because the inputs to the LSTM are integers and they need to be float. However, in version 1.4.0 I get this error:
```
ValueError: Initializer for variable rnn/lstm_cell/kernel/ is from inside a control-flow construct, such as a loop or conditional. When creating a variable inside a loop or conditional, use a lambda as the initializer.
```
Which has nothing to do with what is wrong with the code. Version 1.2.0 however, generates this error which correctly refers to the problem:
```
TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [int32, float32] that don't all match.
```

**Comment by MikulasZelinka** [comment]
Thank you very much, I encountered the exact same issue and couldn't figure out what the problem was: [https://stackoverflow.com/questions/47393356/how-to-use-tensorflows-dataset-api-iterator-as-an-input-of-a-recurrent-neural/47409487](url).

(Python 3.6, tensorflow 1.4.0)

**Comment by tatatodd** [comment]
@parsa-saadatpanah Thanks for the clear problem description!

@ebrevdo can you suggest someone to look into a fix?

Contributions are definitely welcome!

**Comment by kwonmha** [comment]
thank you!
it helped a lot

**Comment by jayshah19949596** [comment]
hey... I have the same problem ... Any solution ??

**Comment by davisliang** [comment]
@jayshah19949596 as @parsa-saadatpanah mentioned, you probably have a placeholder of dtype=int32. Change this to float32.

**Comment by monk1337** [comment]
Suppose your input tensorflow looks like where you are accepting int values

input_x=tf.placeholder(name='input_',shape=[4,3,2],dtype=tf.int32)

now just use tf.cast method

input_x = tf.cast(input_x,tf.float32)

and feed it to rnn .

**Comment by Demetrio92** [comment]
Not that it is a very helpful advice, and not that I am proud of that fact that it is helpful to me. But: 
* Try restarting the console if you're developing using ipython 

Not sure what is it doing wrong, but after few runs with breaks via `ctrl+c` I encountered the issue. Clearing the scope does not help, but new instance does.

**Comment by Demetrio92** [comment]
Not that it is a very helpful advice, and not that I am proud of that fact that it is helpful to me. But: 
* Try restarting the console if you're developing using ipython 

Not sure what is it doing wrong, but after few runs with breaks via `ctrl+c` I encountered the issue. Clearing the scope does not help, but new instance does.

**Comment by mblouin02** [comment]
@Demetrio92 : Your answer worked for me! Restarting the console fixed it. Weird.

**Comment by Demetrio92** [comment]
@mblouin02 well, apparently, we just discovered an instantiating bug, should've thought of it...

**Comment by dynamicwebpaige** [comment]
Later versions of TensorFlow feature a much more informative error message for the code sample above:

```
ValueError: RNN cell only supports floating point inputs, but saw dtype: <dtype: 'int32'>
```

Closing out this issue - feel free to open, if mistaken. 🙂
