### ISSUE TITLE
ImageUtils.convertYUV420SPToARGB8888 resulting distorted image

### ISSUE THREAD

**Issue by lavinachitara** [tensorflow/tensorflow#14720]
Hi @andrewharp 

I did some modification in TF detect android app to detect person from loaded picture rather than clicking it by camera(Not using cameraActivity).

Everything is working fine except the function named ImageUtils.convertYUV420SPToARGB8888. This function returns distorted image (please find attachment)

actual image:
![actual_image](https://user-images.githubusercontent.com/2331214/33017067-f6c5dd42-ce16-11e7-9cb0-7827cf490c8b.png)

After converting image from YUV 4:2:0 to ARGB:
![converted_image](https://user-images.githubusercontent.com/2331214/33017069-f6f60e2c-ce16-11e7-9772-89d0a7d22612.png)

Sharing part of code below:

            newbitmap = Bitmap.createScaledBitmap(bitmap, 640, 480, false);
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            newbitmap.compress(Bitmap.CompressFormat.JPEG, 100, output);
            imgbytes = output.toByteArray();

            imageConverter =
                new Runnable() {
                    @Override
                    public void run() {
                        ImageUtils.convertYUV420SPToARGB8888(imgbytes, previewWidth, previewHeight, rgbBytes);
                    }
                };

**Comment by lavinachitara** [comment]
Resolved :)

**Comment by wadewangpower** [comment]
hello,@lavinachitara , i met similar problem now, how did you solve it ?

**Comment by Sanjay2802** [comment]
How did you resolve???
