### ISSUE TITLE
Tensorflow GPU version support with skflow

### ISSUE THREAD

**Issue by vnkmr7620** [tensorflow/tensorflow#1473]
![error](https://cloud.githubusercontent.com/assets/10511526/13720964/02b25a4c-e83e-11e5-9a03-f4250d7c8ab2.png)
![version](https://cloud.githubusercontent.com/assets/10511526/13720966/0807d9b8-e83e-11e5-83c8-26699934e698.png)

I have been trying to execute text_classification.py example of skflow but it is generating an error. Please see the attached document for an error as well as the version of tensorflow and the skflow.

**the error is tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'train/update_words/words_embeddings/Assign_1': Could not satisfy explicit device specification '' because the node was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/GPU:0'**

**Comment by vrv** [comment]
Try updating your version of TensorFlow: 0.5 was the original release and there have been a ton of bug fixes and improvements since then.

**Comment by vnkmr7620** [comment]
how to update gpu version of tensorflow

**Comment by vrv** [comment]
Try reading through: https://www.tensorflow.org/versions/r0.7/get_started/os_setup.html#download-and-setup

**Comment by vrv** [comment]
(Feel free to comment if, after upgrading, you still have the problem, and we can debug further!)
