### ISSUE TITLE
Does Tensorflow support Graphic for AMD (GPU also)  like NVIDIA (GPU)

### ISSUE THREAD

**Issue by MyAusweis** [tensorflow/tensorflow#14736]
Dear All

I have laptop lenovo G50-80 I7 5500 with AMD RADEON R5 M230-2GB for graphic (it is also gpu based on this link ( https://www.futuremark.com/hardware/gpu/AMD+Radeon+R5+M230/review ), does tensorflow support this amd for computing  the same like what tensorflow did with GPU from NVIDIA ?. if it has to be configured from the source, what is the setting of tensorflow that when i compile it it will run the gpu?

Thx

**Comment by abrad1212** [comment]
@MyAusweis I believe so (experimental though). Please see #22 for updates on AMD/OpenCL support

**Comment by drpngx** [comment]
Yes, it's not supported and OpenCL is not fully ready.

**Comment by charlie-ruan** [comment]
yes,   it supports newer version of AMD GPUs, such as GFX8 GPU's (Fiji & Polaris Family) and GFX9 (Vega).  I tried AMD RX 480 and works great !  See link below:

https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/README.ROCm.md

**Comment by TEJAPS** [comment]
@charlie-ruan do you have windows version of the GPU installation in amd.

**Comment by charlie-ruan** [comment]
@TEJAPS , according to AMD hiptensorflow documentation, hiptensorflow only supports Linux for now.

**Comment by denji** [comment]
AMD a great idea for modernization, NVIDIA proprietary vendor in which you can not implement your own layers

* https://github.com/ROCm-Developer-Tools/HIP
* https://github.com/ROCmSoftwarePlatform
* https://pro.radeon.com/en/solutions/vdi/
* https://pro.radeon.com/en/quality-of-service-amd-mxgpu/

**Comment by HackInvent** [comment]
You definitively need to support AMD's GPU natively asap in my opinion:
- they are leader on free remote GPU clustering
- there are thousands of crypto mining datacenters that will be converted to lowcost GPU farms in the next following years (they all use AMD's GPU)
Not supporting AMD's GPU is not strategic if your aim is massive adoption of tensorflow.

**Comment by HamzaElgarrab** [comment]
We need AMD GPUs support, 

- Their cards present amazing value for the money..
- They offer more VRam than GTX cards..
- HBM2 is way faster than DDR6. As u may know, memory bandwidth is the general bottleneck in DL tasks

**Comment by HackInvent** [comment]
Recently I heard the announcement of Stadia, the new Google Game platform.
It is supported by nVidia GPUs.
It think that Google is definitively focussing, and consequently Tensorflow, on nVidia GPUs support to reduce the integration effort in all its services that require GPUs.
Corporations strategies are not often fair for everyone...

**Comment by denji** [comment]
@HackInvent Google Stadia specifications:
* CPU: Custom 2.7GHz hyper-threaded x86 CPU with AVX2 SIMD and 9.5MB L2+L3 cache
* GPU: Custom **AMD GPU** with **HBM2** memory and **56** compute units, capable of 10.7 teraflops
* Memory: 16GB of RAM with up to 484GB/s of performance
* SSD cloud storage

**Comment by QuantumInformation** [comment]
How is support for the new macbooks, both for TF and TFJS?

https://www.apple.com/uk/shop/buy-mac/macbook-pro/15-inch-space-grey-2.3ghz-8-core-processor-with-turbo-boost-up-to-4.8ghz-512gb#


Radeon Pro 560X with 4GB of GDDR5 memory
- £225.00

Radeon Pro Vega 16 with 4GB of HBM2 memory

Radeon Pro Vega 20 with 4GB of HBM2 memory

**Comment by QuantumInformation** [comment]
Looks like OpenCI support is WIP by google atm.

TFJS abstracts this stuff away I think so since I use TFJS then these macs should be fine?

**Comment by vidyakabadi** [comment]
AMD radeon R 5 GPU is that ok if i install tensorflow on my laptop?? will it support or will it be compatible? I am new in this field pardon if my question didn't make any sense!!

**Comment by e-hamza** [comment]
Quite an old topic, but any good progress on this? The recent RX 6000 series really offer tremendous value compared to NVidia. I saw some good development happening on ROCm, anyone tried how that performs?
