### ISSUE TITLE
tf.contrib.ffmpeg.decode_audio console flood

### ISSUE THREAD

**Issue by georgesterpu** [tensorflow/tensorflow#14733]
When we evaluate the tensor returned by `tensorflow.contrib.ffmpeg.decode_audio()`, the ffmpeg log shows up in the terminal, leading to a flood of messages when decoding a large number of files.

Asked [here](https://stackoverflow.com/questions/47361507/tf-contrib-ffmpeg-decode-audio-verbosity) as well. I could not find an easy way such as an environment variable for ffmpeg to turn off the output log, there is only a command-line argument `loglevel` but TF's `decode_audio()` does not support it.

Currently using `ffmpeg 3.4 (gcc 7.2.0)` and `tensorflow 1.4.0` on linux.

Issue filed as instructed [here](https://github.com/tensorflow/tensorflow/issues/11339#issuecomment-345836714). @rryan @fredbertsch

**Comment by yongtang** [comment]
PR #14582 is pending review. I think the PR is the fix for this issue?

**Comment by georgesterpu** [comment]
Yes, indeed, the PR addresses the same problem I have. Now I see that I could not find it because it refers to `tf.contrib.ffmpeg.decode_*` instead of the complete function name. Unlucky
