### ISSUE TITLE
Build Tensorflow Lite C++ API into a dynamic library for Android

### ISSUE THREAD

**Issue by Calin-Mihnea** [tensorflow/tensorflow#14758]
Is there any way of building the Tensorflow Lite C++ API into a dynamic library for Android?
I have tried to build with bazel for armv7a but this only gives the corresponding static libraries:
`bazel build -c opt //tensorflow/contrib/lite:* --crosstool_top=//external:android/crosstool --cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11" --verbose_failures
`

**Comment by aselle** [comment]
You could try adding linkshared=1 to the framework rule in tensorflow/contrib/lite/BUILDhttps://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/BUILD#L64
(see bazel docs here https://docs.bazel.build/versions/master/be/c-cpp.html)

**Comment by Calin-Mihnea** [comment]
Approaching the problem without reading the bazel docs was really not a good idea.
Worked like a charm after, and also managed to use a LINKER_SCRIPT to expose only needed functions, thus reducing the size of the library.

**Comment by drpngx** [comment]
Closing as this seems to be resolved.
