### ISSUE TITLE
Downgrade to Bazel 0.4.2 for Tensorflow r1.0

### ISSUE THREAD

**Issue by Dagalaki** [tensorflow/tensorflow#14756]
Hello, 

I need to checkout to Tensorflow r1.0 and as suggested the Bazel version should be 0.4.2

I have already installed Bazel and after upgrade bazel version is 0.7.0

Do you know the steps so I can downgrade to Bazel 0.4.2? 

I have tried with apt-get install bazel=0.4.2 but this does not work, 

and I have also tried to uninstall by executing the command rm -fr ~/.bazel ~/.bazelrc and deleting relevant data in ~/.cache/bazel/ folder, but this did not also work.

Any suggestions ?

Thank you in advance

**Comment by shivaniag** [comment]
This issue is relevant for Bazel community, closing it here.
