### ISSUE TITLE
Udacity Example 1_notmnist failing to download

### ISSUE THREAD

**Issue by artgillespie** [tensorflow/tensorflow#1475]
### Environment info
Operating System: Mac OS X

### Steps to reproduce
1. `virtualenv venv`
2. `source venv/bin/activate`
3. `pip install ipython`
4. `pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp27-none-any.whl`
5. `git clone https://github.com/tensorflow/tensorflow.git`
6. `cd tensorflow/tensorflow/examples/udacity`
7. `ipython notebook`
8. In the browser (Chrome 48.0.2564.116) load `1_notmnist.ipynb`
9. Run cell 1 (imports)
10. Run cell 2

Cell 2 fails with `Exception: Failed to verify notMNIST_large.tar.gz. Can you get to it with a browser?`. Checked url (`http://yaroslavvb.com/upload/notMNIST/notMNIST_large.tar.gz`) with browser, downloads fine.

Checked working directory, found 422 byte `notMNIST_large.tar.gz`. Opened and found this;

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /upload/notMNIST/notMNIST_large.tar.gz
on this server.</p>
<p>Additionally, a 403 Forbidden
error was encountered while trying to use an ErrorDocument to handle the request.</p>
<hr>
<address>Apache Server at yaroslavvb.com Port 80</address>
</body></html>
```

Small thing, and easy to work around, but would improve our students' experience if they didn't have to debug this.

**Comment by yaroslavvb** [comment]
I don't understand, http://yaroslavvb.com/upload/notMNIST/notMNIST_large.tar.gz is there, where does "403 Forbidden" error come from?

**Comment by artgillespie** [comment]
It's what's downloaded in cell 2 here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/1_notmnist.ipynb

**Comment by yaroslavvb** [comment]
Thanks for the report, looks like my ISP is finicky about User-Agent strings, rehosting it on Google Cloud, should get upstreamed soon

**Comment by staffhorn** [comment]
I can't access the files on the either yarslavvb or google.

**Comment by yaroslavvb** [comment]
Just checked http://yaroslavvb.com/upload/notMNIST/notMNIST_small.tar.gz
and it works for me.
But future version will refer to alternative location at
http://commondatastorage.googleapis.com/books1000/notMNIST_small.tar.gz

**Comment by kstseng** [comment]
Hi, I only can access the small one, and large one failed.
Any suggestion?

Thanks

**Comment by yaroslavvb** [comment]
I just tried accessing http://commondatastorage.googleapis.com/books1000/notMNIST_large.tar.gz and it works for me

**Comment by kstseng** [comment]
But I tried to accessing by 1_notmnist.ipynb. It still give me the error.

`url = 'http://commondatastorage.googleapis.com/books1000/'

def maybe_download(filename, expected_bytes, force=False):
  """Download a file if not present, and make sure it's the right size."""
  if force or not os.path.exists(filename):
    filename, _ = urlretrieve(url + filename, filename)
  statinfo = os.stat(filename)
  if statinfo.st_size == expected_bytes:
    print('Found and verified', filename)
  else:
    raise Exception(
      'Failed to verify ' + filename + '. Can you get to it with a browser?')
  return filename

train_filename = maybe_download('notMNIST_large.tar.gz', 247336696)
test_filename = maybe_download('notMNIST_small.tar.gz', 8458043)`

**Comment by yaroslavvb** [comment]
What is the error?

**Comment by kstseng** [comment]
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-14-61c8ed837e56> in <module>()
     13   return filename
     14 
---> 15 train_filename = maybe_download('notMNIST_large.tar.gz', 247336696)
     16 test_filename = maybe_download('notMNIST_small.tar.gz', 8458043)

<ipython-input-14-61c8ed837e56> in maybe_download(filename, expected_bytes, force)
     10   else:
     11     raise Exception(
---> 12       'Failed to verify ' + filename + '. Can you get to it with a browser?')
     13   return filename
     14 

Exception: Failed to verify notMNIST_large.tar.gz. Can you get to it with a browser?

**Comment by yaroslavvb** [comment]
Looks like there's size mismatch. Can you see what size it is and also try
with force=true

**Comment by kstseng** [comment]
I just re-run the code without modifying with force = true, and it works right now!
I don't know why.

**Comment by yaroslavvb** [comment]
Are you in mainland China?

**Comment by kstseng** [comment]
No, I am in Taiwan.

**Comment by novemberkilo** [comment]
Also detected a size mismatch. With force=False the file size for notMNIST_large.tar.gz was coming in at 115793920. Setting force=True fixes the problem. 

I'm using the docker image per the instructions [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/README.md#running-the-docker-container-from-the-google-cloud-repository) - is there a file with this name already on the filesystem perhaps?

**Comment by sommeralex** [comment]
i keep getting 

[Errno socket error] [Errno -2] Name or service not known

altough I am forcing true.. any idea how to fix this?

**Comment by yaroslavvb** [comment]
Can you download it manually? I just clicked, and the download seems to be happening fine

**Comment by sommeralex** [comment]
thank you very much for your quick response. i tried

`docker run --net host -p 8888:8888 -it --rm b.gcr.io/tensorflow-udacity/assignments:0.5.0`

as mentioned https://discussions.udacity.com/t/assignment-1-ioerror-errno-socket-error-errno-2-name-or-service-not-known/46838/3

and it is working now

thx!

**Comment by subir0071** [comment]
May download it fromhere 
(http://yaroslavvb.com/upload/notMNIST/)

**Comment by Shaligram** [comment]
I could see its related to proxy.
in my case http_proxy was set on the shell.  unset that. and It worked like charm.

**Comment by WentaoZero** [comment]
@Shaligram Could you elaborate a bit?

**Comment by jubafourali** [comment]
downloading from this url  http://commondatastorage.googleapis.com/books1000/notMNIST_large.tar.gz 
works for me

**Comment by mstarodub** [comment]
https://www.kaggle.com/datasets/jwjohnson314/notmnist

you'll want to delete the following zero byte files:
A/RGVtb2NyYXRpY2FCb2xkT2xkc3R5bGUgQm9sZC50dGY=.png
F/Q3Jvc3NvdmVyIEJvbGRPYmxpcXVlLnR0Zg==.png
