### ISSUE TITLE
Type Serialization in as_graph_def function

### ISSUE THREAD

**Issue by tjingrant** [tensorflow/tensorflow#14769]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:  v1.3.0-rc2-20-g0787eee
- **Python version**: 2.7.14
- **Bazel version (if compiling from source)**: 0.7
- **GCC/Compiler version (if compiling from source)**: Apple LLVM version 8.1.0 (clang-802.0.42)
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Problem is that as_graph_def sometimes serialize the type information and sometimes doesn't.

### Source code / logs
```
import tensorflow as tf

# bool typed Op, no type serialized
x = tf.placeholder(tf.bool)
y = tf.placeholder(tf.bool)
op = tf.logical_or(x, y)
print op.graph.as_graph_def(add_shapes=True)

# float typed Op, type serialized
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
op = tf.add(x, y)
print op.graph.as_graph_def(add_shapes=True)
```

node for logical_or is, note no `T` in attr:
```
node {
  name: "LogicalOr"
  op: "LogicalOr"
  input: "Placeholder"
  input: "Placeholder_1"
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          unknown_rank: true
        }
      }
    }
  }
}
```

node for add is, note with `T` in attr:
```
node {
  name: "Add"
  op: "Add"
  input: "Placeholder_2"
  input: "Placeholder_3"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          unknown_rank: true
        }
      }
    }
  }
}
```
If you print out `print tf.logical_or(x, y)`, the output is 
```
Tensor("LogicalOr_1:0", dtype=bool)
```
So problem might be with the serialization?
This seems like a bug to me.

**Comment by tatatodd** [comment]
This is because `tf.logical_or` is only defined for the `bool` type, so there's no need to serialize extra type information into the GraphDef.

**Comment by arun-kumark** [comment]
Hi,
I am new to this issue. 
I want to serialize my Resnet101 based model.
I am using the script optimize_for_inference.py, I don't know how to edit this script for Resnet101 model.
When I run this script, I get the following errors: 

```
/home/arun/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "optimize_for_inference.py", line 146, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/arun/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "optimize_for_inference.py", line 90, in main
    FLAGS.output_names.split(","), FLAGS.placeholder_type_enum)
  File "/home/arun/anaconda3/lib/python3.6/site-packages/tensorflow/python/tools/optimize_for_inference_lib.py", line 109, in optimize_for_inference
    placeholder_type_enum)
  File "/home/arun/anaconda3/lib/python3.6/site-packages/tensorflow/python/tools/strip_unused_lib.py", line 83, in strip_unused
    raise KeyError("The following input nodes were not found: %s\n" % not_found)
KeyError: "The following input nodes were not found: {'input'}\n"
```
I want to make this script work to serialize my Resnet model. I need help, if someone can help me.

Kind Regards
Arun
