### ISSUE TITLE
Feature request: Control order of 'feature_column.input_layer'

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorflow#14768]
On master (80e7c9f45c).

It seems that the mapping of features to columns in dense the input matrix is always sorted by the alphabetical order of the feature names. It would be nice is this was customizable, perhaps by respecting the order of the feature columns in the second argument to `input_layer`. Mainly useful  for debugging and introspecting the network to know which columns correspond to which features.

eg:

```python
sess.run(tf.feature_column.input_layer({'a': [1], 'b': [2]}, [tf.feature_column.numeric_column('a'), tf.feature_column.numeric_column('b')]))
```

gives `[1, 2`],

as does switching the order of the feature columns:

```python
sess.run(tf.feature_column.input_layer({'a': [1], 'b': [2]}, [tf.feature_column.numeric_column('b'), tf.feature_column.numeric_column('a')]))
```

I also tried giving the features as an `OrderedDict`, but `input_layer` doesn't seem to care about the ordering in that  situation either.

**Comment by facaiy** [comment]
Yes, `feature_columns`'s order is rearranged:

https://github.com/tensorflow/tensorflow/blob/b5df90f91cde6eb12af9cbe818bd2cf4a9bcc687/tensorflow/python/feature_column/feature_column.py#L224

However, I think your request is reasonable.

**Comment by ispirmustafa** [comment]
We sort feature columns to make order of variables/ops deterministic. Each worker should create them in same order. we cannot know the given fc order is deterministic or not.

**Comment by facaiy** [comment]
Because feature_columns accepts an iterator, which can be either ordered (say,  list ) or unordered (say, set or map), so we always sorted the feature columns by name, right?

**Comment by ispirmustafa** [comment]
yes.

**Comment by malmaud** [comment]
I still think it would be nice to have some kind of interface for exposing the relationship between columns and features to users, even if it's not user-specifiable.

**Comment by ispirmustafa** [comment]
I think it's doable without changing order. Currently we're returning vars related to FCs via cols_to_vars. We can similarly add an argument such as cols_to_slices.

**Comment by facaiy** [comment]
I'm afraid that cols_to_slices is a little complicated. At least for tuple, it seems safe to respect its iterator's order.

**Comment by scut-salmon** [comment]
A design that doesn't return to the original order is so un-human. Do designers not use their products very much？
