### ISSUE TITLE
Bazel Compile tensorflow failure

### ISSUE THREAD

**Issue by Cfq0924** [tensorflow/tensorflow#14780]
System information
windows 10 64bit

bazel version
Build label: 0.7.0
Build target: bazel-out/msvc_x64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 18 14:25:56 2017 (1508336756)
Build timestamp: 1508336756
Build timestamp as int: 1508336756

i run ./configure:
configure
WARNING: Running Bazel server needs to be killed, because the startup options are different.
You have bazel 0.7.0 installed.
Please specify the location of python. [Default is F:\barzel\py2.7\python.exe]: D:/Anaconda3/python.exe
Found possible Python library paths:
  D:\Anaconda3\lib\site-packages
Please input the desired Python library path to use.  Default is [D:\Anaconda3\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with GDR support? [y/N]: n
No GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: n
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with MPI support? [y/N]: n
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:

Add "--config=mkl" to your bazel command to build with MKL support.
Please note that MKL on MacOS or windows is still not supported.
If you would like to use a local MKL instead of downloading, please set the environment variable "TF_MKL_ROOT" every time before build.

then i run:
bazel build --verbose_failures //tensorflow:libtensorflow_cc.so

ERROR: F:/barzel/tensorflow1/tensorflow-master/tensorflow/cc/BUILD:422:1: Linking of rule '//tensorflow/cc:ops/sparse_ops_gen_cc' failed (Exit 1181): link.exe failed: error executing command
  cd C:/users/cfenich/appdata/local/temp/_bazel_cfenich/ku2zcbwb/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\\shared;C:\Program Files (x86)\Windows Kits\8.1\include\\um;C:\Program Files (x86)\Windows Kits\8.1\include\\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET TEMP=C:\Users\CFenich\AppData\Local\Temp
    SET TMP=C:\Users\CFenich\AppData\Local\Temp
    SET USE_LINKER=1
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/link.exe /nologo /OUT:bazel-out/host/bin/tensorflow/cc/ops/sparse_ops_gen_cc.exe tensorflow_framework /SUBSYSTEM:CONSOLE -Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..,-rpath,$ORIGIN/../.. -pthread /MACHINE:X64 @bazel-out/host/bin/tensorflow/cc/ops/sparse_ops_gen_cc.exe-2.params /DEFAULTLIB:msvcrt.lib.
LINK : warning LNK4044: 无法识别的选项“/Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..,-rpath,$ORIGIN/../..”；已忽略
LINK : warning LNK4044: 无法识别的选项“/pthread”；已忽略
LINK : warning LNK4044: 无法识别的选项“/lm”；已忽略
LINK : warning LNK4044: 无法识别的选项“/lm”；已忽略
LINK : warning LNK4044: 无法识别的选项“/lm”；已忽略
LINK : fatal error LNK1181: 无法打开输入文件“tensorflow_framework.obj”

**Comment by Cfq0924** [comment]
@asimshankar

**Comment by arixlin** [comment]
same problem， you can try build on linux

**Comment by allenlavoie** [comment]
Does it work if you add `--config=monolithic` to the `bazel build` command? Unfortunately we don't have that shared object working on Windows yet (waiting on Bazel support AFAIK). The only downside is that custom ops won't work with libtensorflow_cc built this way.

**Comment by Cfq0924** [comment]
@allenlavoie thanks!but, it doesn't work. if i want to use tensorflow c++ on windows, could i build tensorflow by cmake?

**Comment by allenlavoie** [comment]
Oh right, our Bazel build is still not quite there on Windows. Is the issue that we don't have an exported symbol list for the C++ API? CMake would be good to try.

**Comment by drpngx** [comment]
Right, currently the supported path on windows is cmake.

**Comment by ymodak** [comment]
Closing this issue due to staleness. Please use the latest version of TensorFlow and build again.
Feel free to report any issues you encounter with latest TensorFlow. Thanks!
