### ISSUE TITLE
[feature request] custom GraphKeys QUEUE_RUNNERS for input pipeline

### ISSUE THREAD

**Issue by automateljw** [tensorflow/tensorflow#14793]
i find no perfect answer about using input pipeline to train and eval in same Session
===========
[switch input pipeline at stackoverflow](eg: https://stackoverflow.com/questions/41162955/tensorflow-queues-switching-between-train-and-validation-data)
===========
if we define different input pipeline for train and eval,  the following code will start both train and eval input pipeline, that is not we want
```
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(sess=sess, coord=coord)
```
if we can custom GraphKeys.QUEUE_RUNNERS  collection for different input pipeline , i think we can start input pipeline through parameter of collection.
`    tf.train.add_queue_runner(qr, collection=tf.GraphKeys.QUEUE_RUNNERS)`
`   eg: tf.train.add_queue_runner(qr, collection=tf.GraphKeys.TRAIN_QUEUE_RUNNERS)`
`   eg: tf.train.add_queue_runner(qr, collection=tf.GraphKeys.EVAL_QUEUE_RUNNERS)`
is it right ?  
@mrry  @all 
thanks

**Comment by tatatodd** [comment]
@automateljw The Dataset API is the recommended way to combine train and eval input pipelines in the same Session.  Read about it here:
https://www.tensorflow.org/programmers_guide/datasets

In particular, there is an example of exactly this usage here (search for `reinitializable iterator`):
https://www.tensorflow.org/programmers_guide/datasets#creating_an_iterator

Does this resolve your issue?

**Comment by automateljw** [comment]
@tatatodd  thank your reply firstly.  As i know, Dataset API will replace queue input pipeline,  but it does not support sparse tensor now, is it right ?  or can you show demo about SparseTensor using Dataset API, big thanks!

**Comment by mrry** [comment]
If you upgrade to a nightly build, you will find the `tf.data` now supports sparse tensors natively, thanks to @jsimsa's hard work!

**Comment by automateljw** [comment]
nice work， i will try it，
