### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'input_c'

### ISSUE THREAD

**Issue by dengyuning** [tensorflow/tensorflow#14795]
I am using `tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops.CudnnGRU` as cudnn_cell.
But when I call cudnn_cell as follows
`  	    hiddens, output_h, output_c = cudnn_cell(
   	        inputs,
   	        input_h=init_state,
   	        input_c=init_state,
   	        params=cudnn_params,
 	        is_training=True)
`, an error occurs saying that input_c was an unexpected keyword.
But I have checked the source code and I'am certain that there is a keyword argument 'input_c'.

**Comment by facaiy** [comment]
Could you paste your environment information?

**Comment by shivaniag** [comment]
https://www.tensorflow.org/api_docs/python/tf/contrib/cudnn_rnn/CudnnGRU, it seems that you have given wrong set of arguments.
