### ISSUE TITLE
Wrong link in the "common problems" docs

### ISSUE THREAD

**Issue by SkidanovAlex** [tensorflow/tensorflow#148]
On the "Getting started page" in the following part:

```
Common Problems
GPU-related issues

If you encounter the following when trying to run a TensorFlow program:

ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory

Make sure you followed the the GPU installation instructions.
```

The last word "instructions" leads to http://www.tensorflow.org/#install_cuda, however the main page it leads to does not have an anchor "install_cuda", so it just ends up leading to the top of main page.

Presumably, the correct link is http://www.tensorflow.org/get_started/os_setup.md#install_cuda

**Comment by vrv** [comment]
Thanks for the report -- our website generation is undergoing fixes / changes this week -- it is also quite behind our github documentation.  We'll close this bug once we've fixed these issues, thanks!
