### ISSUE TITLE
Renaming of input arguments for clarity

### ISSUE THREAD

**Issue by rdipietro** [tensorflow/tensorflow#1480]
Sorry in advance for being a bit pedantic... I bring this up because of lack of clarity when it comes to `gather`.

Right now there are many names for a generic input:
- `to_float` and others use `x` instead of `tensor`
- `shape`, `size`, `rank`, and others use `input` instead of `tensor`
- `reshape` and others use `tensor`
- `gather` uses `params` instead of `tensor`
- `dynamic_partition` uses `data` instead of `tensor`
- `pack` and `unpack` use `values` and `value` instead of `tensor_list` and `tensor`

`params` suggests that `gather` is special purpose, perhaps for efficiency or some other reason. Is it? If so, should we update the documentation? If not, can we change the name of `params`?

In addition, I think `value`(s) and `input` should be changed: a `Tensor` isn't a value and `input` is a Python built-in.

**Comment by mrry** [comment]
Unfortunately it's not trivial to change these names, because some code might have used them in explicit named arguments. I agree it would be nicer to have them consistent, so perhaps we could consider a breaking change at some point in the future.

**Comment by rdipietro** [comment]
Makes sense. Can you please comment on `gather`?
