### ISSUE TITLE
Potential memory leak from deleting array and closing file handler

### ISSUE THREAD

**Issue by orpillar** [tensorflow/tensorflow#14800]
Here are couple of minor memory leak for review.
1. https://github.com/tensorflow/tensorflow/blob/6c95675492aa8d25619f5e4ce1674582c051a7fe/tensorflow/c/c_api.cc#L569-L593 "delete []base;" looks missing.
   

2. https://github.com/tensorflow/tensorflow/blob/6c95675492aa8d25619f5e4ce1674582c051a7fe/tensorflow/core/lib/io/snappy/snappy_outputbuffer.cc#L164-L173  "delete []compressed_length_array;" looks missing when macro TF_RETURN_IF_ERROR() fails.

3. https://github.com/tensorflow/tensorflow/blob/6c95675492aa8d25619f5e4ce1674582c051a7fe/tensorflow/core/platform/profile_utils/android_armv7a_cpu_utils_helper.cc#L113-L123 Two potential problems:
    a. There is no "fclose()" being called after fscanf() fails
    b. "fclose()" could be called instead of "pclose()"

4. https://github.com/tensorflow/tensorflow/blob/6c95675492aa8d25619f5e4ce1674582c051a7fe/tensorflow/tools/proto_text/gen_proto_text_functions.cc#L132-L137 When "fwrite() fails", "fclose()" could be called before "return -1".

PS: I don't have handy working environment setup yet, currently browsing code may be better fit for me.

**Comment by carlthome** [comment]
Could you edit your post and wrap code in three backticks (Markdown code highlighting), please?

```cpp
int main() {
  // This is easier to read.
}
```

![image](https://user-images.githubusercontent.com/1595907/33139045-6ca77b38-cfac-11e7-8a29-233e0918a72d.png)

**Comment by carlthome** [comment]
Or better yet, paste links to the relevant lines and GitHub will insert code snippets for you:
https://github.com/tensorflow/tensorflow/blob/6c95675492aa8d25619f5e4ce1674582c051a7fe/tensorflow/c/c_api.cc#L580-L583

**Comment by orpillar** [comment]
@carlthome, thanks for the tip. Now I updated the description.

**Comment by yongtang** [comment]
@orpillar I think those issues are true.  In `snappy_outputbuffer.cc`, `unique_ptr` probably could be used.

Would you like to create a PR for that? Otherwise I could help create a PR for you.

**Comment by orpillar** [comment]
@yongtang, thanks for looking into the issues. You are right about snappy_outputbuffer.cc.
I am new to open source community, just want to see there is any easy things I could contribute.
Please feel free to help create a PR. Thanks,

**Comment by yongtang** [comment]
@orpillar Created PR #14816 for the fix. Thanks for your contribution to TensorFlow community! 👍

**Comment by orpillar** [comment]
@yongtang. Thanks for the PR. It looks the sanity build had time out.

**Comment by yongtang** [comment]
@orpillar bumped the build. Thanks!
