### ISSUE TITLE
segmentation fault due to pytorch and tensorflow conflictions

### ISSUE THREAD

**Issue by hantek** [tensorflow/tensorflow#14812]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 8 (jessie)
- **TensorFlow installed from (source or binary)**: from Anaconda, with command:
`pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp35-cp35m-linux_x86_64.whl`

- **TensorFlow version (use command below)**: v1.4.0-rc1-11-g130a514 1.4.0
- **Python version**: 3.5.4
- **Bazel version (if compiling from source)**: -
- **GCC/Compiler version (if compiling from source)**: -
- **CUDA/cuDNN version**: cuda 8.0
- **GPU model and memory**: TITAN Xp, 12G
- **Exact command to reproduce**:
This fails:
```python
>>> import torch
>>> import tensorflow as tf
Segmentation fault (core dumped)
```

### Describe the problem
I am using pytorch version 0.2.0_4, for python 3.5, with cuda support. I installed it from the following command:

`conda install pytorch torchvision cuda80 -c soumith`

When I use tensorflow alone, it works fine; i.e., doing an import like 
```python
>>> import tensorflow as tf
```
has no problem. Also, Importing tensorflow before torch seems fine as well.

However if I import pytorch before tensorflow, it fails and reported a segmentation error (as shown above).

**Comment by allenlavoie** [comment]
Sounds like this is another case of https://github.com/pytorch/pytorch/issues/3059. So unless this is a different stack trace than https://github.com/tensorflow/tensorflow/issues/13615, we're just waiting on the PyTorch folks.

**Comment by shivaniag** [comment]
Closing this, feel free to reopen if this is a different stack trace.
