### ISSUE TITLE
'output' does not exist in model 'file:///android_asset/retrained_graph.pb'

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [tensorflow/tensorflow#14824]
I was retrain a inception model with food images,i got the final test prediction and retrained_graph.pb ,retrained_labels.txt file.i check the prediction using command prompt in windows and its work.but i was put the retrained_graph.ph and retrained_labels.txt files into android studio asset folder for deploying mobile,i got the exception like:
output' does not exist in model 'file:///android_asset/retrained_graph.pb

Can anyone help me solve this issue.

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
