### ISSUE TITLE
third_party\eigen3\unsupported\Eigen\CXX11

### ISSUE THREAD

**Issue by luyuesheng** [tensorflow/tensorflow#14822]
when testing tensorflow.dll in vs2015. but  vs2015 can not recongnize "third_party\eigen3\unsupported\Eigen\CXX11\Tensor".

I succeeded in compiling tf1.4 on windows 10+vs2015+cuda8.0+cudnn5.1.  tensorflow.lib and tensorflow.dll  are there.

the error log:
E:\tensorflow2\third_party\eigen3\unsupported/Eigen/CXX11/Tensor(1): fatal error C1014: 包含文件太多: 深度 = 1024

My win32 console program does nothing ,only include some files .src code as follow:
#include <memory>
#include <string>
#include <vector>
#include "tensorflow/core/framework/tensor.h"
//#include "tensorflow/core/framework/graph.pb.h"
//#include "tensorflow/core/public/session.h"

**Comment by luyuesheng** [comment]
fatal error C1014: 包含文件太多: 深度 = 1024
fatal error C1014:too many files:depth =1024

**Comment by luyuesheng** [comment]
I found the error is caused by wrong path.  now  everything is ok.

**Comment by cocoakang** [comment]
How did you fix that?

**Comment by cocoakang** [comment]
@luyuesheng

**Comment by luyuesheng** [comment]
@cocoakang 
E:\tensorflow
E:\tensorflow\tensorflow\contrib\cmake\build\nsync\src\nsync\public
E:\tensorflow\tensorflow\contrib\cmake\build
E:\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen
E:\tensorflow\tensorflow\contrib\cmake\build\protobuf\src\protobuf\src

**Comment by laoyandujiang** [comment]
Sure, don't use this path: E:\tensorflow\third_party\eigen3
