### ISSUE TITLE
getting the dynamic shape of a Tensor as an integer

### ISSUE THREAD

**Issue by daksunt** [tensorflow/tensorflow#1482]
How can I get xshape as a int variable? Is this feature available?

Of course if I evaluate, I will get the value of xshape, but the input is dynamic and I don't want to use the get_sum function in for loop, because it would break the graph.

Problem: TypeError: range() integer end argument expected, got Tensor

```
import tensorflow as tf
import numpy as np


x = tf.placeholder(tf.float32, shape=[None])
xshape = tf.placeholder(tf.float32, shape=[])


def get_sum(x, xshape):
  sum = 0
  for i in range(xshape):
    sum += x[i]

init = tf.initialize_all_variables()
sum = get_sum(x, xshape)

with tf.Session() as sess:
  sess.run(init)
  for i in range(100):
    length = np.random.randint(0,10)
    a = np.random.randint(0, 10, length)
  print sess.run(sum,feed_dict={x:a, xshape:length})
```

**Comment by Shagas** [comment]
It's not clear to me why you want to get the value of xshape, which you are using as an input feed variable. Also why would you want to do a sum in a for loop like that?
What are you trying to achieve?

**Comment by daksunt** [comment]
I want to do process on variable length tensors. In other words I need to do a computation for each element in a tensor with different values. Getting the shape as an integer is a first step.

**Comment by mrry** [comment]
The only way to get the dynamic value of a tensor as a Python integer is to pass it to `sess.run()`. However, that doesn't really solve your problem, as you want to have data-dependent control flow in your graph. One way to do this is to upgrade to the latest nightly version of TensorFlow, and try the `tf.foldl()` or `tf.foldr()` functions, which operate like `scan()` in Theano to iterate over one dimension of a tensor.

**Comment by Shagas** [comment]
In my experience, if you need to do something 'iteratively' in tensorflow then you are most likely thinking about it wrong. Maybe you can formulate your task as a multiplication of matrices or something.

**Comment by mrry** [comment]
Indeed, for this case it would be more appropriate to use `tf.reduce_sum()`. However, if you need to define a recurrent network, where the input to an op depends on its output in a previous iteration in some non-trivial way, then the support for iteration will be useful.

**Comment by mrry** [comment]
Assigning @yuanbyu, who might have more information about the current status of the control flow ops.

**Comment by yuanbyu** [comment]
You could use fold to achieve what you wanted to do:

```
x = tf.placeholder(tf.float32, shape=[None])
init = tf.initialize_all_variables()
sum = tf.foldl(lambda a, e: a + e, x, initializer=0.0)
with tf.Session() as sess:
  sess.run(init)
  for i in range(100):
    length = np.random.randint(0,10)
    a = np.random.randint(0, 10, length)
  print sess.run(sum,feed_dict={x:a})
```

If you want to split/unpack on a tensor with dynamic shape and do some computation on each subtensor, the combination of TensorArray and While() is the way to go.

**Comment by mrry** [comment]
Closing this, since it looks like `tf.foldl()` is the way to go here.
