### ISSUE TITLE
Feature request: Tensorflow lite on memory constrained bare-metal systems

### ISSUE THREAD

**Issue by shaurya0** [tensorflow/tensorflow#14830]
I'm interested in running Tensorflow Lite on devices with limited memory resources and possibly no operating systems abstractions available. 

This means removing any dependencies on file systems, threads, synchronization primitives, etc. and keeping the binary size as small as possible. I don't know if you discuss your roadmap openly here, but I'm wondering whether this is something that is planned for TFLite? If not, I may go ahead and try to implement this myself.

**Comment by carlthome** [comment]
Considering how one of the frequently mentioned advantages of TensorFlow Lite (interpreter) over XLA (compiler) is that you can update models without changing app code, I assume the intention is to require a file system.

Raspberry Pi seems to be on the roadmap though: https://github.com/tensorflow/tensorflow/issues/14589

Perhaps you could try to compile a frozen GraphDef with tfcompile (LLVM based) for your target though?

**Comment by shaurya0** [comment]
Thanks for your comment.

I initially thought it would be possible for me to read the models from a region in memory reserved in the binary itself for storing models. I could then use flatbuffers to load the model from a pointer instead of a file path. 

Unfortunately, XLA backends are not available for the platforms I'm targetting.

**Comment by rajatmonga** [comment]
@shaurya0 The updating of model is independent of the core TF Lite interpreter and operations themselves. The core library and most kernels (op implementations) have very few dependencies and likely not the ones you list here. 

The goal is for the core to be very portable so keeping low dependencies is important.
 
Certain kernels do leverage multi-threading/synchronization, but we often have single threaded versions as well, or you could easily rewrite just those while taking advantage of the rest of the pieces.

Best thing to do is to try TF Lite out for your device and let us know what issues you run into. Do not hesitate to send across improvements to reduce/separate out dependencies where feasible - it will help many others as well.

**Comment by shaurya0** [comment]
Thanks for your comment.

**Comment by rongjiecomputer** [comment]
@shaurya0 I have upstreamed some changes to make it possible to build tfcompile on Windows via Bazel, tracking bug at #15213, instruction at https://github.com/rongjiecomputer/tensorflow-xla-aot-windows. Very hacky as I need to build LLVM with CMake then import the binaries to Tensorflow to build with Bazel

If you can port the Bazel build script of XLA/AOT to CMake, it will be possible to build LLVM and Tensorflow together. I can't do/test this as I cannot use CMake + MSBuild, and Tensorflow can't be built with CMake + Ninja.
