### ISSUE TITLE
tensorflow lite build for iOS

### ISSUE THREAD

**Issue by hutuyingxiong** [tensorflow/tensorflow#14852]
error ：./download_dependencies.sh: line 50: 1: Usage: download_and_extract URL DIR
how to do it？

**Comment by printdhruv** [comment]
Please fill and read [ISSUE_TEMPLATE](https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md) before raising an issue.

**Comment by derdav3** [comment]
do you have the newest version? [this](https://github.com/tensorflow/tensorflow/pull/14734) addresses some issues with download_dependencies

**Comment by derdav3** [comment]
I just tried it - the script fails when being outside of the root folder of tensorflow... when I cd into tensorflow - it all works out

**Comment by aselle** [comment]
Closing for now. Making a more user friendly error message here #14949.

-A
