### ISSUE TITLE
off-by-one bug in graph_editor get_forward_walk_ops

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#14858]
This [line](https://github.com/tensorflow/tensorflow/blob/c9de294d0a0980b1636f76757c175afbf4f58ea8/tensorflow/contrib/graph_editor/select.py#L414) converts Tensor to its corresponding op by replacing it with its consuming op

`seed_ops = util.get_consuming_ops(ts)
`

Instead it should replace it with its producing op

`seed_ops = [t.op for t in ts]
`

This would makes `get_forward_walk_ops(tensor` give same result as `get_forward_walk_ops(tensor.op` which was probably the intention of this function

I know `contrib` isn't really supported, but wanted to file this bug in order to reference it in work-arounds in my code

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yaroslavvb** [comment]
cc @purpledog

**Comment by purpledog** [comment]
Hi,

Consumer ops are not the same as t.op. Simply speaking, `t.op` is the op producing the tensor and consumer ops are the ops taking `t` as input.

So I think this is working as expected (correct me if I am wrong!).

**Comment by yaroslavvb** [comment]
Indeed they are not the same, and I think it should be `t.op` instead of consumer ops.
Consider how it works now

```
import tensorflow as tf
import tensorflow.contrib.graph_editor as ge

A0 = tf.ones((), name='A0')
A1 = tf.tanh(A0, name='A1')
print(ge.get_forward_walk_ops(A0))     # => [A1]
print(ge.get_forward_walk_ops(A0.op))  # => [A0, A1]

```

**Comment by yaroslavvb** [comment]
Actually after thinking a bit, I can see your logic -- using `A.op` instead of `A` may forward walks to include chains of computation that don't include `A` which would also be counter-intuitive.

I was too used to thinking of TensorFlow not having a concept of tensor (since the graph only contains ops, and you can't compute any tensor individually without computing all of the other tensors on the op).

**Comment by yaroslavvb** [comment]
The current counter-intuitive behavior is that there's no way to include the endpoints of your walks if you use a tensor

IE the following will not include `A0` in the forward walks returned

`print(ge.get_forward_walk_ops(A0, inclusive=True))`

**Comment by purpledog** [comment]
Yes, agreed. I think it's not possible to use the graph_editor without using both tensor and ops, which is indeed at odd with the rest of TensorFlow. I'd still call it a "feature" and not a bug but I do see where you are coming from.

**Comment by yaroslavvb** [comment]
@purpledog BTW, I hope you will graduate graph_editor out of contrib at some point, it's useful for running larger models in GPU budget. For instance, you can do imagenet resnet with 4x memory reduction at 1.2 compute cost by checkpointing intermediate values and using graph editor to rewire the graph.

Here's a recent neat example of using it -- do backprop on a chain of length n while using constant memory 
https://github.com/yaroslavvb/chain_constant_memory/blob/master/chain_constant_memory_test.py
