### ISSUE TITLE
tensorboard ImportError: cannot import name 'run_main'

### ISSUE THREAD

**Issue by XiaXuehai** [tensorflow/tensorflow#14855]
I install the tensorflow on Mac from source.
but when I run the tensorboard,and got a error like this

> Pro-2:Desktop xxh$ tensorboard
Traceback (most recent call last):
  File "/Users/xxh/anaconda3/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
ImportError: cannot import name 'run_main'`

How to fix it?

**Comment by printdhruv** [comment]
(1) You can't import it. Please go to [here](https://stackoverflow.com/) for support since it's not a bug.
(2) Please fill [ISSUE_TEMPLATE](https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md) before raising an issue.

**Comment by bigpalm82** [comment]
It could be helpful to run a script directly, e.g. "python /usr/local/lib/python2.7/dist-packages/tensorboard/main.py --logdir=~~~"

**Comment by tatatodd** [comment]
Please file TensorBoard issues under https://github.com/tensorflow/tensorboard/issues

**Comment by timmolter** [comment]
@XiaXuehai Did you ever figure out a fix? After building TF from source on a Mac running High Sierra, and running Tensorboard, I also get that same exact error.

**Comment by intrinsic-value** [comment]
i had the same problem after i build tensorflow from source. it turn out that tensorboard has not been installed accordingly.  Try to install tensorboard again, then the problem solved!

**Comment by andychat** [comment]
I ran into this after building tensorflow from source.

It worked for me after I built tensorboard separately from source: https://github.com/tensorflow/tensorboard.

**Comment by opeide** [comment]
I fixed this by changing the shebang at the top of the python file /usr/local/bin/tensorboard to #!/usr/bin/python3. (was just #!/usr/bin/python).
