### ISSUE TITLE
DocBug

### ISSUE THREAD

**Issue by aosterloh** [tensorflow/tensorflow#1486]
This tutorial **will how you **how to run the example script on your own images, and will explain some of the options you have to help control the training process.

found at
https://www.tensorflow.org/versions/master/how_tos/image_retraining/index.html

**Comment by chemelnucfin** [comment]
It looks like the issue has been fixed in the code, probably pending a website update.

**Comment by mrry** [comment]
Looks like this fix is now live, thanks!
