### ISSUE TITLE
If I import cv2, " tf.global_variables_initializer() " will be very slow.

### ISSUE THREAD

**Issue by YaoZhongtian** [tensorflow/tensorflow#14866]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04.3
- **TensorFlow installed from (source or binary)**:
Binary.
- **TensorFlow version (use command below)**:
1.3.0
- **Python version**: 
2.7.12
- **CUDA/cuDNN version**:
CUDA Version 8.0.61
- **GPU model and memory**:
NVIDIA GTX 1080Ti  12G

### Describe the problem
If I import cv2, " tf.global_variables_initializer() " will be very slow, about 143s. You can run my test code below, when " import cv2 " is commented out, the time is about 5s. The version of opencv is 2.4.13.4.

### Source code / logs
```Python
import tensorflow as tf
import time
import cv2

weight = tf.Variable(tf.truncated_normal([5,5,1,32], stddev=0.1))

ot = time.time()
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
nt = time.time()
print('time: {:.3f}'.format(nt-ot))
```

**Comment by ppwwyyxx** [comment]
#1197 #7755

**Comment by YaoZhongtian** [comment]
Thanks ！

**Comment by aselle** [comment]
Closing as a duplicate.
