### ISSUE TITLE
[Feature Request] Support for Flutter

### ISSUE THREAD

**Issue by nikhil-minz** [tensorflow/tensorflow#14873]
I recently moved from native development to Flutter seeing Google backing its development.
Since both TensorFlow and Flutter is by Google will there be a support for Flutter in Future?

**Comment by shivaniag** [comment]
@petewarden do you have any comments on this?

**Comment by asimshankar** [comment]
What kind of support were you thinking of?

At this time, there are no concrete plans for any Dart APIs for TensorFlow to be shipped as a flutter package. You may want to use something like https://flutter.io/platform-channels/ to integrate with TensorFlow/TensorFlowLite in your mobile application.

**Comment by a2en** [comment]
@asimshankar if we were to use platform channels, we need to code in both swift and kotlin. @nikhil-minz  is referring to plugin support like Flutterfire for firebase

**Comment by shaqian** [comment]
Hi, 
I created a Flutter plugin for TensorFlow Lite. It works on both iOS and Android. 
https://pub.dartlang.org/packages/tflite

**Comment by supermuka** [comment]
@asimshankar, any reconsideration for an official Dart implementation?

Two years after this issue was closed, Dart lang has had a real revolution and we can increasingly see applications developed on it with Flutter, AngularDart and server side. I think it would be great if we also had a Tensoflow implementation for Dart.

**Comment by bhack** [comment]
Check https://github.com/dart-lang/tflite_native/pull/22

**Comment by bhack** [comment]
For firebase instead https://github.com/FirebaseExtended/flutterfire/issues/788

**Comment by am15h** [comment]
TensorFlow Lite Flutter Plugin is now available [am15h/tflite_flutter_plugin](https://github.com/am15h/tflite_flutter_plugin/). It provides a Dart API similar to the TFLite Java API.

It is built on the top of the bindings from [dart-lang/tflite_native](https://github.com/dart-lang/tflite_native) under the guidance of TensorFlow Lite team.

**Comment by bhack** [comment]
@am15h Is https://github.com/dart-lang/tflite_native/issues/42 going to impact your GSOC proejct?

**Comment by am15h** [comment]
@bhack It won't,   [am15h/tflite_flutter_plugin](https://github.com/am15h/tflite_flutter_plugin/) is fully functional without any use of `dart:cli`.

**Comment by v7lin** [comment]
any news update?
