### ISSUE TITLE
What if we don't install tensorflow under a new environment?

### ISSUE THREAD

**Issue by yomoko** [tensorflow/tensorflow#14882]
How come we need to install tensorflow as a [separate](https://user-images.githubusercontent.com/33768560/33234120-05bba17a-d1ef-11e7-9f8a-0390d005aa6a.png) environment?

If we do it this way, many common libraries are not available when tensorflow is activated. 
![image](https://i.stack.imgur.com/zOslW.png)

Most of the common libraries such as matplotlib, panda, etc. are not within tensorflow environment. So we have to install again to use them.
![image](https://user-images.githubusercontent.com/33768560/33233620-c2242610-d1e6-11e7-9a23-44a20991daff.png)

So why not just install under root so we don't have to re-install all those libraries under the new environment?

Thanks.

**Comment by sl-matrix** [comment]
I did a system-wide install on Ubuntu (Linux Kernel) after going through similar troubles you mention. 
I am guessing the rational behind the preferred approach is to preserve the state of mission-critical machines by not altering the code base of dependencies. For recreational users like us, the native pip install allows more flexibility.

**Comment by facaiy** [comment]
I think new environment is optional choice. 
Since tensorflow has many dependencies, for example, numpy, pandas and so on, they might be upgraded when installing tensorflow. So it is safe to create a separate environment. If you don't care the case, feel free to install tensorflow in default environment.

**Comment by yomoko** [comment]
How come your tensorflow came with those dependencies?  Mine didn't. I have to reinstall pandas, matplotlib, pandas_datareader again under tensorflow environment.

**Comment by facaiy** [comment]
Hi, @yomoko. Since the issue is neither bug report or feature request, I think it could be better to post the question on [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow).
