### ISSUE TITLE
feature request - decode_compressed

### ISSUE THREAD

**Issue by YoelShoshan** [tensorflow/tensorflow#14887]
It will be great if you could add **tf.decode_compressed** to be used in **situations that tfrecords cannot be used**.

Currently, only **tf.decode_raw()** can be used in such situations, which becomes a big issue with massive amount/size of files.

**Comment by tatatodd** [comment]
@mrry might have some thoughts on this.

**Comment by mrry** [comment]
What the signature of such an op be?

**Comment by YoelShoshan** [comment]
same signature as decode_raw, I don't currently see any reason for additional arguments.
so basically

```python
decode_compressed(
    bytes,
    out_type,
    little_endian=True,
    name=None
)
```

**Comment by YoelShoshan** [comment]
[gzip](http://www.gzip.org/) which uses [deflate](http://www.gzip.org/algorithm.txt) sounds like a reasonable option.

Very standard nowadays, easy to generated/deflate using python/c++ (and probably other programming languages) by using zlib.

**Comment by yongtang** [comment]
I am wondering if it makes sense to just add an optional `compression` flag to `decode_raw`?

At the moment compression are supported in  some of the classes and there are some PRs pending,  like #14599, #12369, #14342. There is no dedicated `compressed format` process. Rather compression are treated as an optional layer on top of  `TFRecord`, `TextLineRecord`, etc.

Maybe we could just do the same so that we have
```
decode_raw(
    bytes,
    out_type,
    little_endian=True,
    name=None,
    compression="NONE"
)

```
with compression = `"NONE"`/`"ZLIB"`/`"GZIP"`/etc supported?

**Comment by YoelShoshan** [comment]
well, functionally it sounds good.
Function name wise it might be a bit misleading due to the "raw" in the function name.

**Comment by yongtang** [comment]
@YoelShoshan I created a PR #15132 for further discussion. After looking through decode_raw, I think it might make sense to have `decode_compressed` take a string Tensor input and generate a string Tensor output. In this way, it might potentially be used in many other places (not limited to decode_raw).

To apply `decode_compressed` to another op (e.g., decode_raw):
```
in_bytes = tf.placeholder(tf.string, shape=[None])
decompressed = tf.decode_compressed(in_bytes, compression_type="ZLIB")
decode = tf.decode_raw(decompressed, out_type=tf.int16)
```

Please take a look

**Comment by drpngx** [comment]
@martinwicke WDYT?

**Comment by martinwicke** [comment]
I like it. We can figure out details, if any, on the PR.

**Comment by YoelShoshan** [comment]
@yongtang I agree - good to have it for other possible usage as well.
Will continue discussion on  PR #15132 as you said.
