### ISSUE TITLE
A bug in tensorflow r1.4 when applying  MultiRNNCell

### ISSUE THREAD

**Issue by pangzhan27** [tensorflow/tensorflow#14897]
### System information
- **TensorFlow installed from source :
- **TensorFlow version: r1.4
- **Python version: 3.5.4
- **Bazel version: 0.5.4
- **GCC/Compiler version 5.4.0
- **CUDA/cuDNN version: 9.0 &5.0
- **GPU model and memory*: GeForce GTX 1080

### Describe the problem
when applying the MultiRNNCell as below, an error occurs. The code went well in tensorflow r1.3
# Source code
input_list is a list of tensor with shape[None, 8]
n_hidden = 32
lstm = tf.nn.rnn_cell.BasicLSTMCell(n_hidden)
stacked_lstm = tf.nn.rnn_cell.MultiRNNCell([lstm]*2)
outputs, states = tf.nn.static_rnn(stacked_lstm, input_list, dtype=tf.float32)
# error
ValueError: Dimensions must be equal, but are 64 and 40 for 'rnn/rnn/multi_rnn_cell/cell_0/cell_0/basic_lstm_cell/MatMul_1' (op: 'MatMul') with input shapes: [?,64], [40,128].

However when only applying one single lstm, i works well.

opinions:
when calculating, the basiclstmcell will be called, where a class named Linear will be initialized, as an example, in my case, the variable self.weight in this class will be initialized as [40,128]([32+8,32*4]). 
*** code from rnn_cell_impl.py***
if self._linear is None:
    self._linear = _Linear([inputs, h], 4 * self._num_units, True)

But, when MultiRNNCell is the case, for example,  a 2 layers lstm. in the second layer, the weight should be [64,128]('h' in last layer (32)+'o' in  last layer(32)). Disappointingly, the weight will only be initialized once and stay with the shape [40,128] due to the sentence "if self._linear is None:". So that the reason why such error occurs.

i try to comment out this sentence, but since share variable mechanism is related. it dosen't work, and induces other problem.

ValueError: Trying to share variable rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel, but specified shape (64, 128) and found shape (40, 128).

Any idea how to solve this problem efficiently?

**Comment by pangzhan27** [comment]
@arixlin  Thank you so much,  it works out

**Comment by fengfengxie** [comment]
@arixlin thank you!

**Comment by HelloSeeing** [comment]
It does not work for me, though. Because I add `tf.get_variable_scope().reuse_variables()` before it.

**Comment by sun2009ban** [comment]
@HelloSeeing tf.get_variable_scope().reuse_variables() works in version 1.0.0

**Comment by wangrui6** [comment]
@pangzhan27  Why does it work out? I am still confused and have the same problem with you.

**Comment by GuitarmonYz** [comment]
Anybody explain why it has to be modified in the form of @arixlin 's code?

**Comment by arixlin** [comment]
@GuitarmonYz  you can run tensorflow 1.1.0, the version has explanation.

**Comment by wizyoung** [comment]
@gaohuazuo Actually it's not a bug of TensorFlow but a feature of Python. `[lstm]*2` may not behave as you expect. The list it creates contains two elements refers to the **same** lstm cell instance instead of two separate ones. Here is an example:
```shell
>>> l = [{'a': 1}] * 4
>>> l
[{'a': 1}, {'a': 1}, {'a': 1}, {'a': 1}]
>>> l[0]['a'] = 2
>>> l
[{'a': 2}, {'a': 2}, {'a': 2}, {'a': 2}]
>>> ll = [{'a': 1} for _ in range(4)]
>>> ll
[{'a': 1}, {'a': 1}, {'a': 1}, {'a': 1}]
>>> ll[0]['a'] = 2
>>> ll
[{'a': 2}, {'a': 1}, {'a': 1}, {'a': 1}]
```
So using list comprehension or for loop is the correct way to create separate RNN instances in  `MultiRNNCell`.

**Comment by lihp11** [comment]
> ```
>  def get_a_cell(lstm_size, keep_prob):
>             lstm = tf.nn.rnn_cell.BasicLSTMCell(lstm_size)
>             drop = tf.nn.rnn_cell.DropoutWrapper(lstm, output_keep_prob=keep_prob)
>             return drop
>         
>  with tf.name_scope('lstm'):
>      cell = tf.nn.rnn_cell.MultiRNNCell(
>      [get_a_cell(self.lstm_size, self.keep_prob) for _ in range(self.num_layers)]
>      )
> ```
A genius answer!!!!

**Comment by azamatkhid** [comment]
really helpful!!!
