### ISSUE TITLE
Running label_wav.py from Simple Audio Recognition on Windows 7/64 is generating errors: CRITICAL:tensorflow:Audio file does not exist CRITICAL:tensorflow:Labels file does not exist CRITICAL:tensorflow:Graph file does not exist

### ISSUE THREAD

**Issue by rafalfirlejczyk** [tensorflow/tensorflow#14905]
Windows 7/64, GPU Nvidia M2000M, Python 3.5.4, tensorflow 1.5.0-dev20171120.

I was following the Simple Audio Tutorial. After retraining and freezing the model I was trying to run the script label_wav.py. The script produces an error: CRITICAL:tensorflow:Audio file does not exist CRITICAL:tensorflow:Labels file does not exist CRITICAL:tensorflow:Graph file does not exist:

C:\Users\bbb738>python tensorflow/tensorflow/examples/speech_commands/label_wav.py \--graph=/tmp/my_
frozen_graph.pb \--labels=/tmp/speech_commands_train/conv_labels.txt \--wav=/tmp/speech_dataset/left
/a5d485dc_nohash_0.wav
CRITICAL:tensorflow:Audio file does not exist
CRITICAL:tensorflow:Labels file does not exist
CRITICAL:tensorflow:Graph file does not exist
Traceback (most recent call last):
  File "tensorflow/tensorflow/examples/speech_commands/label_wav.py", line 135, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\bbb738\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\p
latform\app.py", line 129, in run
    _sys.exit(main(argv))
  File "tensorflow/tensorflow/examples/speech_commands/label_wav.py", line 107, in main
    FLAGS.output_name, FLAGS.how_many_labels)
  File "tensorflow/tensorflow/examples/speech_commands/label_wav.py", line 93, in label_wav
    labels_list = load_labels(labels)
  File "tensorflow/tensorflow/examples/speech_commands/label_wav.py", line 58, in load_labels
    return [line.rstrip() for line in tf.gfile.GFile(filename)]
  File "tensorflow/tensorflow/examples/speech_commands/label_wav.py", line 58, in <listcomp>
    return [line.rstrip() for line in tf.gfile.GFile(filename)]
  File "C:\Users\bbb738\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\l
ib\io\file_io.py", line 214, in __next__
    return self.next()
  File "C:\Users\bbb738\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\l
ib\io\file_io.py", line 208, in next
    retval = self.readline()
  File "C:\Users\bbb738\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\l
ib\io\file_io.py", line 177, in readline
    self._preread_check()
  File "C:\Users\bbb738\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\l
ib\io\file_io.py", line 79, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\bbb738\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\f
ramework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open:  :
 The system cannot find the path specified.
; No such process

**Comment by mrry** [comment]
Do those files exist? They don't look like Windows paths....

**Comment by rafalfirlejczyk** [comment]
Yes, they do exist according exactly as it is stated in the command bellow. So  the **my_frozen_graph.pb** in c:/tmp, **conv_labels.txt** is in c:/tmp/speech_commands_train/ and **a5d485dc_nohash_0.wav** is in c:/tmp/speech_dataset/left/.


According to the code in label_wav.py the program probably cannot find the tf.gfile...:

def label_wav(wav, labels, graph, input_name, output_name, how_many_labels):
  """Loads the model and labels, and runs the inference to print predictions."""
  if not wav or not tf.gfile.Exists(wav):
    tf.logging.fatal('Audio file does not exist %s', wav)

  if not labels or not tf.gfile.Exists(labels):
    tf.logging.fatal('Labels file does not exist %s', labels)

  if not graph or not tf.gfile.Exists(graph):
    tf.logging.fatal('Graph file does not exist %s', graph)


python tensorflow/examples/speech_commands/label_wav.py \
--graph=/tmp/my_frozen_graph.pb \
--labels=/tmp/speech_commands_train/conv_labels.txt \
--wav=/tmp/speech_dataset/left/a5d485dc_nohash_0.wav

**Comment by mrry** [comment]
Does it work if you explicitly include `C:/` at the beginning of the paths?

**Comment by rafalfirlejczyk** [comment]
No, adding c:/   does not.  Still the same  failure.
I even copied all these three files to the same folder where I am starting the script and I called the script like this:

_C:\Users\bbb738\tensorflow>python tensorflow/examples/speech_commands/label_wav.py \--graph=my_frozen_graph.pb \--labels=conv_labels.txt \--wav=a5d485dc_nohash_0.wav_

I still see the same failure:

_CRITICAL:tensorflow:Audio file does not exist
CRITICAL:tensorflow:Labels file does not exist
CRITICAL:tensorflow:Graph file does not exist__

**Comment by mrry** [comment]
Can you try running a small script that does the following?

```python
import tensorflow as tf
print(tf.gfile.Exists("/tmp/my_frozen_graph.pb"))
print(tf.gfile.Exists("/tmp/speech_commands_train/conv_labels.txt"))
print(tf.gfile.Exists("/tmp/speech_dataset/left/a5d485dc_nohash_0.wav"))
```

From the error message, it looks like the arguments `wav`, `labels`, and `graph` are empty strings. Notice that the filenames do not appear in those "CRITICAL" error messages. Perhaps something is going wrong in the command-line argument parsing...

**Comment by rafalfirlejczyk** [comment]
3x true

C:\Users\bbb738\tensorflow>python tensorflow/examples/speech_commands/test_rf.py
True
True
True

**Comment by rafalfirlejczyk** [comment]
Not sure if it helps, but I googled this issue 

https://github.com/tensorflow/tensorflow/issues/9027

**Comment by mrry** [comment]
I believe that that old issue has been fixed, and the problem seems to be in how `argparse.ArgumentParser()` is working in this code:

https://github.com/tensorflow/tensorflow/blob/7726333292b9e3d97a033617ee53099f6c4fedd5/tensorflow/examples/speech_commands/label_wav.py#L109-L130

Can you try modifying `label_wav.py` to print out both `FLAGS` and `unparsed` after it calls `parse_known_args()`?

**Comment by rafalfirlejczyk** [comment]
I added a few prints after definition of label_wav like this (arround line 85):

_def label_wav(wav, labels, graph, input_name, output_name, how_many_labels):
  """Loads the model and labels, and runs the inference to print predictions."""
  
  **print(FLAGS.wav)
  print(FLAGS.labels)
  print(FLAGS.graph)**

  
  if not wav or not tf.gfile.Exists(wav):
    tf.logging.fatal('Audio file does not exist %s', wav)_

and the result is:

   _**wav_data:0 labels_softmax:0 3**


CRITICAL:tensorflow:Audio file does not exist
CRITICAL:tensorflow:Labels file does not exist
CRITICAL:tensorflow:Graph file does not exist_

**Comment by mrry** [comment]
OK, it definitely looks like `parser.parse_known_args()` isn't doing the expected thing, because that looks like all the flags have their default values.

What print statement is printing "_wav_data:0 labels_softmax:0 3"?

**Comment by rafalfirlejczyk** [comment]
Q: What print statement is printing "_wav_data:0 labels_softmax:0 3"?
A: three prints - I added to the code yesterday. pls see my post above, however it is not important anymore

Today I  have change the code  to print **unparsed** and I got the following result:

**check unparsed=  ['\\--graph=/tmp/my_frozen_graph.pb', '\\--labels=/tmp/speech_commands_train/conv_l
abels.txt', '\\--wav=/tmp/speech_dataset/left/a5d485dc_nohash_0.wav']**

It means that the parser is wrong in interpreting the backslash in the command line ??

![image](https://user-images.githubusercontent.com/2536392/33306495-19c01c34-d413-11e7-8b63-420aa0f08035.png)




When I deleted the backslash and left only  **--**  then the problem was solved.
Now the command to run the **label_wav.py** for Windows looks like this:

**C:\Users\brm738\tensorflow>python tensorflow/examples/speech_commands/label_wav.py --graph=/tmp/my_frozen_graph.pb --labels=/tmp/speech_commands_train/conv_labels.txt --wav=/tmp/speech_dataset/left/a5d485dc_nohash_0.wav**

and I get my testing results as expected:
**left (score = 0.87401)
right (score = 0.07143)
_unknown_ (score = 0.03335)**

Thank you Derek for your help!

**Comment by mrry** [comment]
Argh, now that you mention it, `^` (rather than `\`) is the line continuation character in the Windows command prompt. 

Thanks for persevering with the example!
