### ISSUE TITLE
"and", "or", etc, should be overloaded if possible

### ISSUE THREAD

**Issue by lvilnis** [tensorflow/tensorflow#14914]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OS X 10.13.1
- **TensorFlow installed from (source or binary)**: Binary (anaconda)
- **TensorFlow version (use command below)**: 1.1.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**:  N/A
- **GPU model and memory**: Intel HD Graphics 630 1536 MB (not used)
- **Exact command to reproduce**: N/A

### Describe the problem
It would make code much cleaner if more of Python's binary boolean operations were overloaded for 
TF. I understand this can't be done for "==" because of hashmap key problems but "and", "or", "^", "not", really as many operations as possible, would be great.

### Source code / logs

Currently:
```
def cube_isect(x_m,x_M,y_m,y_M):
  return tf.logical_or(tf.logical_and(x_m >= y_m, x_m <= y_M), 
                                  tf.logical_and(y_m >= x_m, y_m <= x_M))
```
Proposed:
```
def cube_isect(x_m,x_M,y_m,y_M):
  return (x_m >= y_m and x_m <= y_M) or (y_m >= x_m and y_m <= x_M)
```

**Comment by lvilnis** [comment]
Not sure how I can assign or mark as a feature request but looping in @alextp

**Comment by alextp** [comment]
Looking at the details of python we're not allowed to override and and or since python has weird short-circuiting control flow based on those operators. What we can do is turn a tensor into a boolean if eager execution is enabled in which case and, or, not, etc all work as intended. We can override the bitwise operators to be elementwise but I think that is less attractive.

**Comment by lvilnis** [comment]
i would vote for overriding the bitwise operators to be elementwise because thats what python already does with "^" since it has no xor. You can write "True ^ False" etc

**Comment by lvilnis** [comment]
Also, you can think of an array of booleans as being an array of bits, so I don't see why overriding bitwise is a problem?

**Comment by alextp** [comment]
Numpy treats bitwise operators as elementwise operators on boolean arrays so I think we should too. Reopening.

**Comment by lvilnis** [comment]
Yeah as does regular python, for not just xor:

```
>>> True & True
True
>>> import numpy as np
>>> np.bool
<type 'bool'>
>>> a=np.asarray([True,False,False,True],dtype=np.bool)
>>> b=np.asarray([False,False,True,True],dtype=np.bool)
>>> a ^ b
array([ True, False,  True, False], dtype=bool)
>>> a & b
array([False, False, False,  True], dtype=bool)
>>> a | b
array([ True, False,  True,  True], dtype=bool)
>>> 
```

This is actually better than overriding "and" and "or" because these TF operators never shortcircuit AFAIK. This would be really nice to have in regular mode, not just immediate.

**Comment by facaiy** [comment]
I think bitwise operators have been supported, 

https://github.com/tensorflow/tensorflow/blob/3d1452c6a4a37c9f5d6f1da77d335cc43f9b7fc8/tensorflow/python/ops/math_ops.py#L1167-L1169
