### ISSUE TITLE
_LayerRNNCell __call__() method incompatible with tuple of tensors

### ISSUE THREAD

**Issue by RylanSchaeffer** [tensorflow/tensorflow#14923]
I'm trying to build a custom LSTM cell that should accept a tuple of tensors in the call method. However, as part of the `dynamic_rnn` loop, `_LayerRNNCell`'s `__call__()` method requires that `inputs` be a `2-D` tensor with shape `[batch_size, input_size]`, which is incompatible with a tuple of tensors. Is there a way around this, or can the `__call__()1 method be expanded to be more flexible?

The error that I receive:
`ValueError: Layer action_conditioned_lstm_cell_1 expects 1 inputs, but it received 2 input tensors.`

Linux Ubuntu 16.04
TensorFlow versions: ('v1.3.0-rc1-5211-gab0fcac', '1.5.0-dev20171127')

**Comment by RylanSchaeffer** [comment]
I just realised that the problem arises because my custom LSTM inherits from `BasicLSTMCell`, which requires that `Inputs must be 2-dimensional.` The above error thus arises because `self.input_spec` is set during initialisation and an error check on dimensionality is performed, so even though my custom `call` method handles the tuple of tensors, execution never reaches that code because it fails the dimensionality check. How do I get around this?

**Comment by RylanSchaeffer** [comment]
It seems like changing `call()` to `__call__()` allows me to bypass this problem. What is the difference?

**Comment by tatatodd** [comment]
@ebrevdo might have some thoughts on this.

**Comment by ebrevdo** [comment]
Don't subclass `BasicLSTMCell`.  You can copy/paste the bits you need for your class.
