### ISSUE TITLE
How to scale the weights at runtime in tensorflow?

### ISSUE THREAD

**Issue by zhangqianhui** [tensorflow/tensorflow#14935]
I have asked this questione in the stackoverflow.
https://stackoverflow.com/questions/47527384/how-to-scale-the-weights-at-runtime-in-tensorflow

Thanks for your help!

**Comment by tatatodd** [comment]
Since this is not a bug or feature request, you should follow-up on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). There is also a larger community that reads questions there. Thanks!
