### ISSUE TITLE
Support "causal" padding in tf.keras.layers.Conv1D by adding support to tf.layers.convolutional.Conv1D

### ISSUE THREAD

**Issue by szpssky** [tensorflow/tensorflow#14933]
TensorFlow version:1.4.0

In the API docs, tf.keras.layers.Conv1D supports "causal". However, if I use "causal" as the argument of 'padding', there will be an error like this: The 'padding' argument must be one of" valid "," same ". Received : causal.

I check the source code, the Conv1D uses the methods in tensorflow.python.layers.convolutional, but the default implementations of tensorflow do not support  "causal" as the padding.

(p.s., fchollet/keras uses the conv1d method in tensorflow_backend.py)

**Comment by tatatodd** [comment]
Thanks for filing the issue @szpssky!  I've dug through the code and agree with you; either the documentation is wrong (and should be fixed), or we need to add support for "causal" padding

@fchollet can you comment on this?

**Comment by fchollet** [comment]
I think support for causal padding should be added to the parent layer in `tf.layers`. Then it will also be supported in the Keras layer that subclasses it. Please open a PR, if your time allows.

**Comment by facaiy** [comment]
@fchollet The implementation of causal padding seems designed for NWC format only, does it make sense for NCW?

https://github.com/fchollet/keras/blob/b00ec66ba948077b61e25cf7dc004857c432b01a/keras/backend/tensorflow_backend.py#L3140

**Comment by fchollet** [comment]
@facaiy I've never seen this use case (it's used for timeseries only, which are in NTC format), but in theory it could be made more general.

**Comment by facaiy** [comment]
Thanks for explanation, @fchollet . #15000 is created to fix the issue, might you take a look?

**Comment by szpssky** [comment]
hi @facaiy
I use your convolutional.py file to replace the original file, I found error：

`   File "/Users/szp/Documents/github/check_tf/causal.py", line 63, in build_model
    model = tf.keras.models.Model(input_, net)
  File "/Users/szp/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 670, in __init__
    super(Network, self).__init__(inputs, outputs, name=name)
  File "/Users/szp/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 1554, in __init__
    '(thus holding past layer metadata). Found: ' + str(x))
ValueError: Output tensors to a Model must be the output of a TensorFlow `Layer` (thus holding past layer metadata). Found: Tensor("conv1d_8/Relu:0", shape=(?, ?, 1), dtype=float32)`

Does this modify still have some problem?

**Comment by facaiy** [comment]
@szpssky I only write test case for `tf.layers.Conv1D`, however it should work well for keras as well. I think that replacing file might not be a good idea, because the file might be quite different between 1.4 and master branch.

Could you replace only the modification to original 1.4 python file, and test whether it works? Thanks.

**Comment by szpssky** [comment]
@facaiy You are right, there are some difference between 1.4 and master branch. As you said I just replaced the modified part, It seems that the operation can only be "SAME" and "VALID", here will be an error:
https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/python/framework/op_def_library.py#L688
`ValueError: Attr 'padding' of 'Conv2D' Op passed string 'CAUSAL' not in: "SAME", "VALID".`

Currently, I haven't found a place to specify "SAME" and "VALID" in source code.

**Comment by facaiy** [comment]
OK, thank you for test, @szpssky .  I'll test it later after I get off work :-)

**Comment by facaiy** [comment]
Yes, hacking `__call__()` method might make mess because `tf.kears` and `tf.layers` share a complicate multiple inheritance. Thanks for feedback, @szpssky . I'll look out other solution to fix the problem.

**Comment by facaiy** [comment]
Hi, @szpssky. I reopened a PR with another solution. And both tests passed for keras and core. Perhaps you are interested on it.

**Comment by szpssky** [comment]
@facaiy 
It seems that this problem still exists:

`  File "/Users/szp/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 252, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/Users/szp/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/szp/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 167, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/Users/szp/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 835, in __call__
    return self.conv_op(inp, filter)
  File "/Users/szp/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 499, in __call__
    return self.call(inp, filter)
  File "/Users/szp/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 187, in __call__
    name=self.name)
  File "/Users/szp/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 177, in _conv1d
    data_format=data_format, name=name)
  File "/Users/szp/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2204, in conv1d
    data_format=data_format)
  File "/Users/szp/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 631, in conv2d
    data_format=data_format, name=name)
  File "/Users/szp/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 691, in _apply_op_helper
    attr_def.allowed_values.list.s))))
ValueError: Attr 'padding' of 'Conv2D' Op passed string 'CAUSAL' not in: "SAME", "VALID".`

It should be a variable declaring that only "SAME" and "VALID" are used.

Is the master branch correct? let me try test it on master branch version.

**Comment by facaiy** [comment]
Yes, at least for Linux CPU, both tests below passed on python 2.7 and python 3.6.

```bash
HEAD is now at 04a029d... TST: more test for invalid argument
INFO: Found 1 test target...
Target //tensorflow/python:layers_convolutional_test up-to-date:
  bazel-bin/tensorflow/python/layers_convolutional_test
INFO: Elapsed time: 303.626s, Critical Path: 78.83s
//tensorflow/python:layers_convolutional_test                            PASSED in 3.5s
Executed 1 out of 1 test: 1 test passes.

HEAD is now at 04a029d... TST: more test for invalid argument
INFO: Found 1 test target...
Target //tensorflow/python/keras:convolutional_test up-to-date:
  bazel-bin/tensorflow/python/keras/convolutional_test
INFO: Elapsed time: 23.051s, Critical Path: 22.28s
//tensorflow/python/keras:convolutional_test                             PASSED in 20.1s
Executed 1 out of 1 test: 1 test passes.
```

**Comment by facaiy** [comment]
Hi, @szpssky . I leave some comments on PR for you, and could you recheck your patch? It seems that `causal` leaks into its parent class, which is unexpected for me. Moreover, could you paste your environment information? Thanks.

**Comment by szpssky** [comment]
@facaiy 
I tested your PR on master branch, it looks work well. However, if input shape is (None,None,1) such as the first layer is LSTM, it will have an error:
`  File "/Users/szp/anaconda3/envs/tf-latest/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 358, in shape_fn
    input_list[1] += left_pad
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'`

But it doesn't seem to be your problem.  fchollet/keras LSTM layer output is a exact shape, such as (None, 30, 1), but the `tf.keras.layers.LSTM` output shape becomes (None, None, 1).

A simple test code:
https://gist.github.com/szpssky/3a54239a0044363abb53ef5c69a80056

**Comment by facaiy** [comment]
Good question! Yes, I forget unknown dimension. I'll fix the problem later. Thanks very much.

**Comment by facaiy** [comment]
By the way, if the two LSTM behaves differently, which might indicate a bug. I suggest to report the inconsistency: -)
