### ISSUE TITLE
Missing gradient for tf.argmax

### ISSUE THREAD

**Issue by pemywei** [tensorflow/tensorflow#14931]
LookupError: No gradient defined for operation 'Argmax' (op type: Argmax)

**Comment by tatatodd** [comment]
Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by boeddeker** [comment]
Afaik it is impossible to define a gradient for argmax.

**Comment by tatatodd** [comment]
Ah sorry, brain freeze.  Actually, we could create a practical implementation of gradient for argmax, but it just wouldn't be very useful for learning.

For details see:
Yaroslav's comment here: #2177
https://www.reddit.com/r/MachineLearning/comments/4e2get/argmax_differentiable/

**Comment by facaiy** [comment]
Yup, how about registering `argmax` by  `REGISTER_OP_NO_GRADIENT` or `ops.NotDifferentiable`?
