### ISSUE TITLE
Does the tensorflow support structured numpy array as inputs?

### ISSUE THREAD

**Issue by zhang8473** [tensorflow/tensorflow#1494]
data = np.array([(1,2.), (2,3.)],dtype=[('foo', 'i4'),('bar', 'f4')])

I want to feed this into
x = tf.placeholder("float", [None,2])

Will the tensorflow automatically convert they datatypes?

**Comment by mrry** [comment]
At present, TensorFlow only supports primitive NumPy datatypes. If you need to represent a tensor of a tuple of values, you can instead use a (Python) tuple of tensors (see e.g. the [`tf.QueueBase`](https://www.tensorflow.org/versions/r0.7/api_docs/python/io_ops.html#QueueBase) documentation for an example).
