### ISSUE TITLE
Document S3 `S3_REGION` constant

### ISSUE THREAD

**Issue by eggie5** [tensorflow/tensorflow#14951]
This gave me a lot of grief recently as the AWS Region for S3 is controlled by an undocumented constant `S3_REGION` which defaults to `us-east-1` unless defined on the system-level. Extra frustrating as it departs from the common naming practice: `AWS_REGION`:

https://github.com/tensorflow/tensorflow/blob/79422ab39b5fe0e1491abb8deabc7ecb5fd9f3a2/tensorflow/core/platform/s3/s3_file_system.cc#L52

If somebody could suggest where to document this, I'd be happy to contribute.

**Comment by aselle** [comment]
@jhseu, do you think we should support both and just fallback?

**Comment by jhseu** [comment]
Yeah, if there's a common practice here, we should use that and deprecate the other environment variable in TF 2.0.

**Comment by yongtang** [comment]
The S3_REGION was introduced in PR #11089. Sorry about the confusion on AWS_REGION vs. S3_REGION.  I will create a PR to add AWS_REGION support shortly.

**Comment by yongtang** [comment]
Added a PR #14984 for the fix. Please take a look.
