### ISSUE TITLE
Method of stabilizing prediction box

### ISSUE THREAD

**Issue by mameng1** [tensorflow/tensorflow#14960]
I found that when I used other methods to detect objects, the prediction box was not stable. However, in the demo you provided, I found that the detection box is very stable. Why, can you give me the code to stabilize the detection box?

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
