### ISSUE TITLE
why the size of filter is 3*3 in inceptionv1.py?

### ISSUE THREAD

**Issue by Bingohong** [tensorflow/tensorflow#14966]
https://github.com/tensorflow/tensorflow/blob/b5df90f91cde6eb12af9cbe818bd2cf4a9bcc687/tensorflow/contrib/slim/python/slim/nets/inception_v1.py#L103
according to the paper,  the size of filter in the scope of "InceptionV1/Mixed_3b/Branch_2"  should be 5*5.
why is 3*3 in the script?

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
