### ISSUE TITLE
Question about tf.contrib.image.rotate

### ISSUE THREAD

**Issue by VOCCTQ** [tensorflow/tensorflow#14968]
Good Morning :) -
is it possible to parse the result from `tf.contrib.image.rotate` to a tensor to use it in `t.cast` ?

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
