### ISSUE TITLE
Documentation of tf.nn.raw_rnn is confusing

### ISSUE THREAD

**Issue by akanimax** [tensorflow/tensorflow#14963]
The documentation for the tf.nn.raw_rnn displays the following line as the pseudocode for the function:
<br>
`(finished, next_input, initial_state, _, loop_state) = loop_fn(
    time=time, cell_output=None, cell_state=None, loop_state=None)`
<br>
This is the first time the loop_fn is called by the raw_rnn interface. Here, the '_' for the emit_output returned by the loop_fn is a **_do not care_** for the function. This misleads the user into believing that returning `None` for the first time as the `emit_output` is OK.

However, the actual code has the line:
<br>
`(elements_finished, next_input, initial_state, emit_structure,
     init_loop_state) = loop_fn(
         time, None, None, None)  # time, cell_output, cell_state, loop_state`
<br>
The code uses the `emit_structure` from the `emit_output` that then determines the shape of the emitted output to be aggregated in the `emit_ta` array. 
So, even for the first time the `loop_fn` needs to output a mock tensor for setting the shape of the output values.

The documentation needs to include this as going through the framework implementation for figuring this out is too tiresome. 

Cheers!

**Comment by tatatodd** [comment]
Thanks for filing the clear issue @akanimax!  Would you like to submit a PR to improve the documentation?

FYI @ebrevdo.

**Comment by akanimax** [comment]
Sure! It'd be a privilege.

**Comment by sachinprasadhs** [comment]
I see that the documentation and the the pseudo code has been updated here https://www.tensorflow.org/api_docs/python/tf/compat/v1/nn/raw_rnn.
