### ISSUE TITLE
Hey, I wanted to know where can i find the implementation of the tensorflow with respect to devices like GPU. Basically I want to understand from source code level what changes are done inside the tensor flow to make it comptabile to GPU when launched. How  does the CUDA compile/run come into play when a session is launched ? Appreciate the help/pointers.

### ISSUE THREAD

**Issue by MS0480** [tensorflow/tensorflow#1497]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

If installed from sources, provide the commit hash:

### Steps to reproduce
1.
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by vrv** [comment]
I would ask this question on StackOverflow, since this isn't a bug or feature request, thanks!
