### ISSUE TITLE
master branch: compilation of llvm_gpu_backend failed

### ISSUE THREAD

**Issue by marrowsuck** [tensorflow/tensorflow#14975]
### System information
- **OS Platform and Distribution**: slackware64-current
- **Python version**: 3.6.3
- **Bazel version**: 0.8.0
- **GCC/Compiler version**: 5.4.0
- **CUDA/cuDNN version**: 9 / 7
- **build environment**:
export PYTHON_BIN_PATH=/usr/bin/python3
export USE_DEFAULT_PYTHON_LIB_PATH=1
export CC_OPT_FLAGS="-march=native"
export TF_NEED_JEMALLOC=1
export TF_NEED_S3=1
export TF_NEED_GCP=0
export TF_NEED_HDFS=0
export TF_NEED_GDR=0
export TF_ENABLE_XLA=1
export TF_NEED_VERBS=0
export TF_NEED_OPENCL=0
export TF_NEED_MKL=1
export TF_NEED_MPI=0
export TF_NEED_CUDA=1
export GCC_HOST_COMPILER_PATH=/opt/gcc54/bin/gcc-5.4.0
export TF_CUDA_CLANG=0
export TF_NEED_OPENCL_SYCL=0
export CLANG_CUDA_COMPILER_PATH=/usr/bin/clang
export CUDA_TOOLKIT_PATH=/usr/share/cuda
export TF_CUDA_VERSION=$($CUDA_TOOLKIT_PATH/bin/nvcc --version | sed -n 's/^.*release \(.*\),.*/\1/p')
export CUDNN_INSTALL_PATH=/usr/share/cuda
export TF_CUDNN_VERSION=$(sed -n 's/^#define CUDNN_MAJOR\s*\(.*\).*/\1/p' $CUDNN_INSTALL_PATH/include/cudnn.h)
export TF_CUDA_COMPUTE_CAPABILITIES=3.0
sed -i 's|/lib"|/lib64"|g' third_party/mkl/build_defs.bzl
sed -i 's|"lib"|"lib64"|g' third_party/mkl/build_defs.bzl
sed -i 's|/lib|/lib64|g' tensorflow/c/generate-pc.sh
- **build command**:
./configure
bazel build --config=opt --config=cuda --config=mkl //tensorflow:libtensorflow.so //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package tmp`

### Building from master fails
ERROR: /tmp/SBo-VCS/tensorflow_cuda-VCS/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/BUILD:16:1: C++ compilation of rule '//tensorflow/compiler/xla/service/gpu/llvm_gpu_backend:llvm_gpu_backend' failed (Exit 1)
tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:37:41: fatal error: llvm/CodeGen/CommandFlags.def: No such file or directory
compilation terminated.
INFO: Elapsed time: 1828.121s, Critical Path: 131.49s
FAILED: Build did NOT complete successfully

**Comment by marrowsuck** [comment]
This commit https://github.com/tensorflow/tensorflow/commit/4e9fa6dcce4912a4797c48f4cb55d3564961bfca changed CommandFlags.h to CommandFlags.def which is missing.

**Comment by marrowsuck** [comment]
Tensorflow compiles successfully now.

**Comment by tatatodd** [comment]
Great, closing this out.

**Comment by ChaitanyaCixLive** [comment]
the error is still showing even after switching to 4e9fa6d
. what needs to be done .. m a nube.

**Comment by ChaitanyaCixLive** [comment]
ERROR: /home/chaitanya/GitLibs/tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/BUILD:16:1: C++ compilation of rule '//tensorflow/compiler/xla/service/gpu/llvm_gpu_backend:llvm_gpu_backend' failed (Exit 1).
tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:37:41: fatal error: llvm/CodeGen/CommandFlags.def: No such file or directory
compilation terminated.

**Comment by marrowsuck** [comment]
The cause of the issue is https://github.com/tensorflow/tensorflow/commit/4e9fa6dcce4912a4797c48f4cb55d3564961bfca. To successfully compile tf you have to change CommandFlags.def back to CommanFlags.h  in tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc.

I'll open another issue and address this.

**Comment by marrowsuck** [comment]
Never mind -- the issue seems to be fixed in master.

**Comment by ChaitanyaCixLive** [comment]
no its not .. but I did that & it compiled properly .. sorry for bothering

**Comment by marrowsuck** [comment]
The CommandFlags.def file referenced is created / downloaded via bazel. The softlink for the bazel cache where the file lives is bazel-$TENSORFLOWBUILDDIR/external/llvm/CodeGen/CommandFlags.def in the tensorflow build directory.

I'm a few minutes in the building process and CommandFlags.def shows up in the mentioned dir. Let's see if the whole program compiles.

Maybe you have to clean / rm your bazel-cache directory?

**Comment by marrowsuck** [comment]
Compilation successful. In the above specified environment.
