### ISSUE TITLE
bazel build nvcc: nvcc fatal : Unsupported gpu architecture 'compute_21'

### ISSUE THREAD

**Issue by rajarsheem** [tensorflow/tensorflow#1498]
After I executed the command
`bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer`

I get an error like 
`ERROR: /home/rajarshee/tensorflow/tensorflow/core/kernels/BUILD:517:1: error while parsing .d file: /home/rajarshee/.cache/bazel/_bazel_rajarshee/0d043bf46cad9f31127eb8d06453610d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/core/kernels/_objs/adjust_contrast_op_gpu/tensorflow/core/kernels/adjust_contrast_op_gpu.cu.d (No such file or directory).
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc fatal   : Unsupported gpu architecture 'compute_21'
Target //tensorflow/cc:tutorials_example_trainer failed to build`

I provided 2.1 gpu compute capability in ./configure earlier.

**Comment by mrry** [comment]
Thanks to @zheng-xq, we figured out that `compute_21` is not a valid architecture (instead it is a virtual architecture). We need to provide a way to pass a compute capability of **2.0** to `nvcc`. Currently our build scripts do not support that, but you can hack in support by editing the [crosstool wrapper](https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc). After you rung `./configure`, replace the loop on [L253--256](https://github.com/tensorflow/tensorflow/blob/e4add493f1020c0eb986aba21c266d9e6e6f4182/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc#L253) with the following:

```python
nvccopts += r'-gencode=arch=compute_20,\"code=sm_21,compute_20\" '
```

**Comment by rajarsheem** [comment]
While the previous is no more appearing, a new incompatibility with my gcc version has occured. please note that i have both 5.2 and 4.9 versions of gcc and my cuda located at /usr/local/cuda has the gcc already linked to /usr/bin/gcc-4.9

`error -- unsupported GNU version! gcc 4.5 and up are not supported!`

**Comment by rajarsheem** [comment]
And after I changed gcc to gcc-4.9 [here](https://github.com/tensorflow/tensorflow/blob/e4add493f1020c0eb986aba21c266d9e6e6f4182/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc#L47) the error was gone but this error came 

`9 errors detected in the compilation of "/tmp/tmpxft_00005b89_00000000-7_adjust_contrast_op_gpu.cu.cpp1.ii".
ERROR: /home/rajarshee/tensorflow/tensorflow/core/kernels/BUILD:517:1: output 'tensorflow/core/kernels/_objs/adjust_contrast_op_gpu/tensorflow/core/kernels/adjust_contrast_op_gpu.cu.o' was not created.
ERROR: /home/rajarshee/tensorflow/tensorflow/core/kernels/BUILD:517:1: not all outputs were created.
Target //tensorflow/cc:tutorials_example_trainer failed to build`

**Comment by zheng-xq** [comment]
@rajarsheem, you'll have to post the errors here. In general, TF is tested on compute_35. While compute_20 may work for now, which I am not sure, there is no guarantee that it will keep working in the long term.

**Comment by rajarsheem** [comment]
@zheng-xq 
`INFO: Found 1 target...
ERROR: /home/rajarshee/tensorflow/tensorflow/core/kernels/BUILD:212:1: error while parsing .d file: /home/rajarshee/.cache/bazel/_bazel_rajarshee/0d043bf46cad9f31127eb8d06453610d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/core/kernels/_objs/gather_op_gpu/tensorflow/core/kernels/gather_op_gpu.cu.d (No such file or directory).
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
In file included from third_party/gpus/cuda/include/cuda_runtime.h:76:0,
                 from <command-line>:0:
third_party/gpus/cuda/include/host_config.h:115:2: error: #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
 #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
  ^
Target //tensorflow/cc:tutorials_example_trainer failed to build
INFO: Elapsed time: 1.447s, Critical Path: 1.19s`

**Comment by zheng-xq** [comment]
>> unsupported GNU version! gcc versions later than 4.9 are not supported!

This problem is that your GCC and NVCC is not compatible. Which Cuda SDK
are you using? Could you try the latest Cuda 7.5 and GCC 4.8, which are
heavily tested.

Thanks.
-XQ

**Comment by rajarsheem** [comment]
I am using Cuda 7.5 and two gcc versions installled - 4.9 and 5.2. the cuda located in /usr/local/cuda has it's gcc _linked_ to gcc-4.9. (the gcc incompatibility issue earlier occured with theano and was solved after the linking)

**Comment by zheng-xq** [comment]
I don't think GCC 4.9 is officially supported by Cuda 7.5. Look at
include/host_config.h

#if defined(__GNUC__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ > 9)
#error -- unsupported GNU version! gcc versions later than 4.9 are not
supported!
#endif /* __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ > 9) */

You are better off with GCC 4.8 and use that instead.

Thanks.
-XQ

**Comment by rajarsheem** [comment]
@zheng-xq  upto 4.9 is supported.
`#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ > 9)

#error -- unsupported GNU version! gcc versions later than 4.9 are not supported!`

**Comment by zheng-xq** [comment]
I stand corrected. It is a good idea to check which version of your GCC was
actually used. A few things you can try:

* You can add "-s" to your bazel to print out the crosstools command line.
* Add "--copt=--cuda_log", which is passed to crosstools to print out the
nvcc command line.

That should be enough to see which version of the gcc was actually used.

**Comment by rajarsheem** [comment]
@zheng-xq  May this be of help. 

http://paste.ubuntu.com/15387128/
(note that default /usr/bin/gcc is actually the 5.2 one!)

**Comment by zheng-xq** [comment]
I think that might be the problem. The default gcc 5.2 is used instead. You
have a few options:

* Symlink your default /usr/bin/gcc to gcc 4.9.
* Modify
third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc to
point to your gcc-4.9 location.

**Comment by rajarsheem** [comment]
Sorry. A mistake! Default gcc version is 4.9.3

**Comment by rajarsheem** [comment]
@zheng-xq 
I changed all the variables below
CPU_COMPILER,GCC_HOST_COMPILER_PATH and LLVM_HOST_COMPILER_PATH by replacing gcc with gcc-4.9. While the gcc issue seems to be vanished, this came:
`5 errors detected in the compilation of "/tmp/tmpxft_00005de0_00000000-7_sparse_tensor_dense_matmul_op_gpu.cu.cpp1.ii".`
Full output:
http://paste.ubuntu.com/15387425/

**Comment by zheng-xq** [comment]
Unfortunately, Eigen starts to pick up warp shuffle capabilities recently,
which requires compute_30 support.

**Comment by rajarsheem** [comment]
all I can pray for is to officially add the support for compute_21 :'(

**Comment by zheng-xq** [comment]
@benoitsteiner to comment on the Eigen request.

@rajarsheem in this thread wants to support compute_20 device. However, since Eigen starts to use warp shuffling instructions, which is only available for compute_30 devices and later, it won't work.

Benoit can tell you whether Eigen will support older devices without the warp shuffling or not.

**Comment by rajarsheem** [comment]
Official support for compute_20 device will be highly appreciated. 
For now, let's count on @benoitsteiner ; may he throw some light.

**Comment by marcdumon** [comment]
I'm having the same problem. Did someone find a solution to make Tensorflow work with compute capability 2.1 GPU's ?

**Comment by benoitsteiner** [comment]
Eigen only supports compute 3.0 and above. Old GPUs tend to run slower than a decent CPU these days, so there is little incentive to remove this restriction at the moment.

@rajarsheem @marcdumon: What are your use cases for GPUs that only support compute capabilities 2.1 ?

**Comment by aselle** [comment]
Automatically closing because there was no response. Please reopen if it is still an issue.

**Comment by rajarsheem** [comment]
@benoitsteiner : Have witnessed that computations with my gpu (2.1) tend to be much faster than with just CPU when I used previously with Theano. Even that performance improvement can be highly beneficial.

**Comment by benoitsteiner** [comment]
@rajarsheem I have fixed the Eigen reduction to remove the dependency on warp shuffles. The next time we update TensorFlow to pick up the latest version of Eigen it should be possible to run with older gpus.

**Comment by AlexJoz** [comment]
hey! @benoitsteiner When it could happen? =)

**Comment by benoitsteiner** [comment]
@AlexJoz i checked that the code now compiles with architecture 2.0 and cuda 7.0.
