### ISSUE TITLE
tf.image.crop_and_resize

### ISSUE THREAD

**Issue by WKChung1028** [tensorflow/tensorflow#14988]
Anyone know how the 
tf.image.crop_and_resize(images, boxes, batch_inds,
                                         [pooled_height, pooled_width],
                                         method='bilinear',
                                         name='Crop')
work? i cannot find the " tf.image.crop_and_resize" in  tensorflow/python/ops/gen_image_ops.py. 
Thank you

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by WKChung1028** [comment]
N/A

**Comment by aselle** [comment]
It is written in C++ ... see e.g.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/image_ops.cc

**Comment by WKChung1028** [comment]
Can i have the "Exact command to reproduce" too?
 
 Tensorflow is new to me. I am trying to understand what happen in the function tf.image.crop_and_resize(images, boxes, batch_inds,
                                         [pooled_height, pooled_width],
                                         method='bilinear',
                                         name='Crop')"  .


If use 
return tf.image.crop_and_resize(images, boxes, batch_inds,
                                         [pooled_height, pooled_width],
                                         method='bilinear',
                                         name='Crop')"  .

How the input of this function is used in the function and what it with return?

**Comment by WKChung1028** [comment]
have the C++ code explains how the tf.image.crop_and_resize work?
I am not sure the .Input() in given link can explain the function.
