### ISSUE TITLE
fcn network to tensorflow lite ?

### ISSUE THREAD

**Issue by adeagle** [tensorflow/tensorflow#14990]
Input:
(u'input_image', (<tf.Tensor 'input_image:0' shape=<unknown> dtype=float32>,))
(u'image_width', (<tf.Tensor 'image_width:0' shape=<unknown> dtype=int32>,))
(u'image_height', (<tf.Tensor 'image_height:0' shape=<unknown> dtype=int32>,))

Output:
(u'Squeeze', (<tf.Tensor 'Squeeze:0' shape=(?, ?, 2) dtype=float32>,))
(u'Squeeze_1', (<tf.Tensor 'Squeeze_1:0' shape=(?, ?, 4) dtype=float32>,))
(u'Squeeze_2', (<tf.Tensor 'Squeeze_2:0' shape=(?, ?, 10) dtype=float32>,))

how to do?
 bazel-bin/tensorflow/contrib/lite/toco/toco \
  --input_file=PNet.pb \
  --input_format=TENSORFLOW_GRAPHDEF  --output_format=TFLITE \
  --output_file=PNet.float.lite --inference_type=FLOAT \
  --input_type=FLOAT --input_arrays=input_image,image_width,image_height \
  --output_arrays=Squeeze,Squeeze_1 --input_shapes=?

tensorflow/contrib/lite/toco/tooling_util.cc:1547] Check failed: array.final_data_type == array.data_type

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by adeagle** [comment]
i have fix it ,thanks

**Comment by wangbingcan1990** [comment]
How did you solve it? I have met the same issue, thanks!

> i have fix it ,thanks
