### ISSUE TITLE
Extend reshape with begin_axis and end_axis like in cntk

### ISSUE THREAD

**Issue by boeddeker** [tensorflow/tensorflow#14998]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.4.0-rc1-11-g130a514 1.4.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
CNTK has a generalized version of reshape and it would be nice to have such a version also in Tensorflow
(https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/ops/__init__.py#L1972).
```python
def reshape(x, shape, begin_axis=None, end_axis=None, name=''):
    ...
```

The difference is, that the user can provide `begin_axis` and `end_axis` and if they are specified reshape only operate on a subset of the shape.

I can make a PR, when somebody says me, where I have to write the code.

### Source code / logs
Here a working example:
```python
def reshape(tensor, shape, begin_axis=None, end_axis=None, name=None) -> tf.Tensor:
    if begin_axis is None and end_axis is None:
        return tf.reshape(tensor, shape, name=name)

    with tf.name_scope(name, 'reshape', [tensor]):
        tensor_shape = tf.shape(tensor)
        to_concat = [shape]
        if begin_axis is not None:
            bs = tensor_shape[:begin_axis]
            to_concat.insert(0, bs)
        if end_axis is not None:
            es = tensor_shape[end_axis:]
            to_concat.append(es)

        tensor_shape = tf.concat(to_concat, 0)

        return = tf.reshape(tensor, tensor_shape)
```

and an example doctest
```python
    """

    Inspired from cntk.reshape to allow begin_axis and end_axis

    Assume you call reshape
    >> out = reshape(in, shape, b, e)
    Than the following will hold
    (Note: If b or e is None, the are interpreted as 0 and/or include the last axis)
    >> in_shape = in.shape
    >> in_shape[b:e] = shape
    >> assert out.shape == in_shape

    First example normal reshape, where the input has unknown dimension
    >>> import numpy as np
    >>> _ = tf.InteractiveSession()
    >>> x = tf.placeholder(tf.float32)
    >>> y = reshape(x, [-1])
    >>> y
    <tf.Tensor 'Reshape:0' shape=(?,) dtype=float32>
    >>> y.eval({x: np.zeros([3, 4])}).shape
    (12,)

    Now keep first and last axis: (No shape inference expected, to difficult)
    >>> y = reshape(x, [-1], begin_axis=1, end_axis=-1)
    >>> y
    <tf.Tensor 'reshape/Reshape:0' shape=<unknown> dtype=float32>
    >>> y.eval({x: np.zeros([3, 4, 5, 6])}).shape
    (3, 20, 6)

    Now with ndim defined:
    >>> x = tf.placeholder(tf.float32, shape=[None, None, None, None])
    >>> y = reshape(x, [-1], begin_axis=1, end_axis=-1)
    >>> y
    <tf.Tensor 'reshape_1/Reshape:0' shape=(?, ?, ?) dtype=float32>
    >>> y.eval({x: np.zeros([3, 4, 5, 6])}).shape
    (3, 20, 6)

    Now with partial defined shape:
    >>> x = tf.placeholder(tf.float32, shape=[3, 4, None, 6])
    >>> y = reshape(x, [-1], begin_axis=1, end_axis=-1)
    >>> y
    <tf.Tensor 'reshape_2/Reshape:0' shape=(3, ?, 6) dtype=float32>
    >>> y.eval({x: np.zeros([3, 4, 5, 6])}).shape
    (3, 20, 6)

    Now with full defined shape:
    >>> x = tf.placeholder(tf.float32, shape=[3, 4, 5, 6])
    >>> y = reshape(x, [-1], begin_axis=1, end_axis=-1)
    >>> y
    <tf.Tensor 'reshape_3/Reshape:0' shape=(3, 20, 6) dtype=float32>
    >>> y.eval({x: np.zeros([3, 4, 5, 6])}).shape
    (3, 20, 6)

    :param tensor:
    :param shape:
    :param name:
    :return:
    """
```

**Comment by facaiy** [comment]
It seems that `tf.reshape` supports to merge its dimensions, for example:

```python
x = tf.placeholder(tf.float32, shape=[3, 4, 5, 6])
y = tf.reshape(x, (3, 20, 6))
# or
y = tf.reshape(x, (3, -1, 6))
```

**Comment by boeddeker** [comment]
Currently `tf.reshape` is powerful enough to solve all problems, but there are two reasons in my mind, why the further arguments are useful, not necessary.

First: Less "hidden bugs" on user side
Example: I modified your example (swapped 6 and 4), it is still executable, but the intent was to flatten the inner dims.
So the output shape is correct, but it hides a bug in user code.
```python
x = tf.placeholder(tf.float32, shape=[3, 6, 5, 4])
y = tf.reshape(x, (3, -1, 6))
```

Second: It is easier when there are unknown dimensions
For example the following does not work
```python
x = tf.placeholder(tf.float32, shape=[3, None, 5, None])
y = tf.reshape(x, (3, -1, -1))
```
For above example I had to learn the difference between `tensor.shape` and `tf.shape(tensor)` to make it possible
```python
x = tf.placeholder(tf.float32, shape=[3, None, 5, None])
shape = x.shape  # does not work, first shape[-1] is None, second shape[-1] can not be set to -1, because there is already a -1
shape = tf.shape(x)  # work
y = tf.reshape(x, (shape[0], -1, shape[-1]))
y = tf.reshape(x, (*shape[:1], -1, *shape[3:]))  # does not work, because the code `*tensor` is not allowed, but `*tensor.shape` work.
```
Further with the new arguments you can easily flatten the inner dims, while the tensor has a unkown shape.

**Comment by aselle** [comment]
@martinwicke, do you have any api thoughts. My thought is that I'd prefer this to be a separate call as this would keep it more similar to numpy (which doesn't have begin_axis and end_axis teither). You could call it partial_reshape() or something.

**Comment by martinwicke** [comment]
I agree. I'd prefer a separate function, `partial_reshape` seems like a good name. Added API review to figure this out before anyone writes any code.

**Comment by boeddeker** [comment]
The Code is already finished (see initial comment) and since the current reshape is powerful enough, only a small wrapper is necessary to extend the API. (The function is inside my code base and I thought that maybe also some other people find it useful.)

I agree that `partial_reshape` would highlight, what the function will do, but it is an extension of `reshape` and not a modification of `reshape`. So the default arguments of `partial_reshape` represent a wrapper around `reshape`. Then some people would not use `partial_reshape`, because they do not know it and other will make an alias and use only `partial_reshape`. (In the case somebody can imagine another extension of reshape that is incompatible with my suggestion, I agree that a separate function will be better.)

When you compare `tf.matmul` with `np.matmul` both have a common interface, but `tf` extends the base idea to be more powerful. So it is already done in tensorflow to add more keywords.

Another point is, that it is quite easy to calculate the desired shape in numpy, because in numpy the shape is a list of int, while in tensorflow it can happen that the shape is undefined or there are more than one undefined shapes.

**Comment by josh11b** [comment]
The API review consensus was not excited by modifying reshape's signature since it is already a widely used function and matches numpy. "partial_reshape" seemed more acceptable.

**Comment by boeddeker** [comment]
Ok, if there is an interest for `partial_reshape` (It sounds like nobody, except me, find such an extension useful.), I can make a PR.
But I need to know, where to place the code. Afaik it is common in tensorflow to initially place code under contrib.

**Comment by martinwicke** [comment]
You could add it contrib, in a new module, possibly called contrib/ops. I am skeptical that it's worthwhile, although you never know how many people silently want this as well.

**Comment by boeddeker** [comment]
@martinwicke When I make a new module, do you have a suggestion, which module I can use as a template? `partial_reshape` is only a thin wrapper around reshape, so I only need a single python file and I am not familiar with the structure of a tensorflow module.

**Comment by facaiy** [comment]
I suggest you to refer to [tf.contrib.lookup](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lookup), which is quite simple.

**Comment by boeddeker** [comment]
Where can I find what the `BUILD` file mean? 
It may be difficult to program it correctly because I use tensorflow binary and not from source.

**Comment by martinwicke** [comment]
You will have to use the source code. The binary distribution is missing
all the BUILD files and tests.

**Comment by boeddeker** [comment]
I know that I need the source code, else I can not use git.
The problem is, that I made the mistake to install tensorflow from source and hit weird bugs (Maybe I got a bad commit). Since then I use tensorflow binary and use a diff programme to sync the installed and the source code in the git repo because I only change python files. (As far as I know it is not possible to install tensorflow from binary (i.e. without bazel) as editable with the python files inside the git repo (i.e. `git clone ... && cd tensorflow && pip install -e .`).)


My question regarding the BUILD file is that I do not know what language it is or what style.
I know that it is not a Makefile, cmake, bash script and python.
Also, I do not know how to execute it (Likely something with bazel (problem) and not python).
So when I would write a BUILD file I would always guess.

Maybe I should keep the `partial_reshape` in my own code base until I understand how to add a new module and decided to build tensorflow. Or maybe someone has interest in `partial_reshape` and knows how to add a new module.

**Comment by facaiy** [comment]
@boeddeker, I understand that it might be not easy.
BUILD file is configured for [bazel](https://docs.bazel.build/versions/master/bazel-overview.html), which is an open-source build and test tool similar to Make, Maven, and Gradle. Those are some tutorials which perhaps are useful for you:
+ [Getting Started with Bazel](https://docs.bazel.build/versions/master/getting-started.html)
+ [Introduction to Bazel: Building a C++ Project](https://docs.bazel.build/versions/master/tutorial/cpp.html)
+ [Concepts and Terminology](https://docs.bazel.build/versions/master/build-ref.html#BUILD_files)

**Comment by boeddeker** [comment]
@facaiy Thanks for the links, when I find the time, I will read them and make a PR.
But it may take a while, so when someone is interested to add `partial_reshape` earlier, feel free to copy my example code.
