### ISSUE TITLE
Quantized ops?

### ISSUE THREAD

**Issue by jbondc** [tensorflow/tensorflow#15]
In the data types section, there are ```quantized ops```
http://tensorflow.org/resources/dims_types.md#data_types

Found a note here:
https://github.com/tensorflow/tensorflow/blob/d6357a5849db980df51d00d8a9ff874cda2faeb3/tensorflow/cc/ops/const_op.h#L65

Can you explain what these are?

**Comment by vrv** [comment]
We are working on support for operators and kernels that take quantized (fixed-point) data -- we're still working on the right APIs to expose them, and with that we'll have more documentation on why and how they are used.  Stay tuned!

**Comment by jbondc** [comment]
Awesome, this is great work :open_mouth:  
Please give my sincere thanks to :santa:

**Comment by martinwicke** [comment]
Closing for now. When the quantized ops come online, they'll come with documentation.

**Comment by dgschwend** [comment]
@vrv Any news on fixed-point / quantized data type support?
I am designing an FPGA-based accelerator for CNNs as my master thesis in the next few months. It would be awesome to be able to train the models with fixed-point weights and activations.
Do you have any roadmap for fixed-point support?

**Comment by hustqmk** [comment]
@dgschwend have you find the answer?

**Comment by amitport** [comment]
@vrv could you please repoen, point to the correct doc, or confirm that is still should be considered internal (though it is exposed in many place by now)
