### ISSUE TITLE
How can i read csv file by file name and line number in tensorflow?

### ISSUE THREAD

**Issue by xf4fresh** [tensorflow/tensorflow#15001]
I read some csv files using queue like [this](https://www.tensorflow.org/api_guides/python/reading_data#creating_threads_to_prefetch_using_queuerunner_objects).  Then, i get `key` and `value` when reading from file queues. The `key` contains file name and line number.

```
    filename_queue = tf.train.string_input_producer(["file0.csv", "file1.csv"]) 
    reader = tf.TextLineReader()
    key, value = reader.read(filename_queue)
```

I train model using Dynamic negative sampling like [IRGAN code](https://github.com/xf4fresh/irgan/blob/master/ltr-gan/ltr-gan-pointwise/ltr_dns_nn.py#L41). I need sample from large scale negative samples, so i want to save the example id such as filename:line rather than feature itself. 

However, i can not find a suitable function on document.
Thanks for your attention!

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
