### ISSUE TITLE
beam search in translation model

### ISSUE THREAD

**Issue by ybbaigo** [tensorflow/tensorflow#1500]
Do we have plan to support beam search in the decoding process of translation model, since the raw paper shows better result with beam search?

**Comment by mrry** [comment]
Does the [`tf.contrib.ctc.ctc_beam_search_decoder()`](https://github.com/tensorflow/tensorflow/blob/b9e9c9a12dbd2946d44c76abdd603eedf6eedb9a/tensorflow/contrib/ctc/ctc_ops.py#L183) help here?

**Comment by ybbaigo** [comment]
@mrry thanks for your quick response, I have no ideas about how to apply ctc_beam_search_decoder to the attention-based LSTM decoding process of the seq2seq model used in translation model in tutorial, since the interface looks different, @ebrevdo could you help double confirm?

**Comment by ebrevdo** [comment]
Nope - ctc_beam_search_decoer is only meant to be used with the ctc_loss and not more general seq2seq models.  Sorry!  You'll have to write your own beam search for now.

**Comment by ybbaigo** [comment]
@mrry @ebrevdo thanks for your help, I just found this feature had been discussed before #654 , I will close this issue.
