### ISSUE TITLE
Tutorial wrong code  cifar10_multi_gpu_train.py

### ISSUE THREAD

**Issue by hhxjzyr** [tensorflow/tensorflow#15027]
when I run 
`python cifar10_multi_gpu_train.py --num_gpus=2`
reported a error

```
usage: cifar10_multi_gpu_train.py [-h] [--batch_size BATCH_SIZE]
                                  [--data_dir DATA_DIR] [--use_fp16 USE_FP16]
cifar10_multi_gpu_train.py: error: unrecognized arguments: --num_gpus=2
```

So what is `[--use_fp16 USE_FP16]` ,it didn;a appear at anywhere in this code file

**Comment by qmick** [comment]
You can close this issue because this file has been moved to tensorflow/models(https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10) and a discuss about this problem can be found at tensorflow/models#2481.
