### ISSUE TITLE
build tensorflow Image Recognition with c++

### ISSUE THREAD

**Issue by scotthuang1989** [tensorflow/tensorflow#15029]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**: 0.6.1
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:8.0
- **GPU model and memory**:5.4.0
- **Exact command to reproduce**:

I follow this [tutorial](https://tensorflow.google.cn/tutorials/image_recognition#usage_with_the_c_api) try to build a a c++ tensorflow program.

Here is the steps:

1. build tensorflow from source. I am sure this step is right, because I can install python tensorflow with the whl file built by this step.
2. in the tensorflow source code directory, I run this command:

`bazel build tensorflow/examples/label_image/...`

the build failed with following logs(partial, because whole log is too big)

> WARNING: /home/scott/github/tensorflow/tensorflow/tensorflow/core/BUILD:1781:1: in includes attribute of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in /home/scott/github/tensorflow/tensorflow/tensorflow/tensorflow.bzl:1044:30
> INFO: Analysed 2 targets (0 packages loaded).
> INFO: Found 2 targets...
> INFO: From ProtoCompile tensorflow/core/example/example.pb.cc:
> bazel-out/local_linux-py3-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
> INFO: From ProtoCompile tensorflow/core/grappler/costs/op_performance_data.pb.cc:
> bazel-out/local_linux-py3-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
> bazel-out/local_linux-py3-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
> INFO: From ProtoCompile tensorflow/contrib/cloud/kernels/bigquery_table_partition.pb.cc:
> bazel-out/local_linux-py3-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
> INFO: From Executing genrule //tensorflow/cc:array_ops_genrule:
> 2017-12-01 15:02:52.546440: W tensorflow/core/framework/op_gen_lib.cc:372] Squeeze can't find input squeeze_dims to rename
> ERROR: /home/scott/github/tensorflow/tensorflow/tensorflow/examples/label_image/BUILD:14:1: Linking of rule '//tensorflow/examples/label_image:label_image' failed (Exit 1)
> /usr/bin/ld: warning: libcudnn.so.6, needed by bazel-out/local_linux-py3-opt/bin/_solib_local/_U_S_Stensorflow_Sexamples_Slabel_Uimage_Clabel_Uimage___Utensorflow/libtensorflow_framework.so, not found (try using -rpath or -rpath-link)
> bazel-out/local_linux-py3-opt/bin/_solib_local/_U_S_Stensorflow_Sexamples_Slabel_Uimage_Clabel_Uimage___Utensorflow/libtensorflow_framework.so: undefined reference to `cudnnGetConvolutionBackwardDataAlgorithm'

**Comment by scotthuang1989** [comment]
I found the cause. I need configure LPATH to include path of  libcudnn.so. Although I put the lib at the standard location. I am not familiar with bazel, so get confused at start.

**Comment by Furane** [comment]
Hello,

I have exactly the same problem, but I didn't get how you solved it. Can you give me more details, please? I tried to export the path to libcudnn.so, with export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64 , but it didn't work.
