### ISSUE TITLE
Error while implementing the feature requested in  #10767

### ISSUE THREAD

**Issue by rezwan16** [tensorflow/tensorflow#15032]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
RHEL 6.8 
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
'v1.3.0-rc1-5326-gcae852a', '1.4.0'
- **Python version**: 
2.7.14
- **Bazel version (if compiling from source)**:
Build label: 0.5.4- (@non-git)
- **GCC/Compiler version (if compiling from source)**:
4.8.5
- **CUDA/cuDNN version**:
Not installed
- **GPU model and memory**:
Using tensorflow for CPU
- **Exact command to reproduce**:
I want to implement _in_top_k_ operation with options to specify what to do when a tie occurs for [CIFAR-10](https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10) data-set. I came across this feature request in #10767, modified the 6-files as shown [here](https://github.com/nolanliou/tensorflow/commit/681724f94e025bbd8377c5406eec4047d58fc31b), and rebuilt from source. When I run _eval_CIFAR10.py_ which contains the _in_top_k_ op, I get the following error.

  File "eval_CIFAR10.py", line 146, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 129, in run
    _sys.exit(main(argv))
  File "eval_CIFAR10.py", line 141, in main
    evaluate()
  File "eval_CIFAR10.py", line 130, in evaluate
    eval_once(saver, summary_writer, top_k_op, summary_op)
  File "eval_CIFAR10.py", line 63, in eval_once
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1686, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Multiple OpKernel registrations match NodeDef 'in_top_k/InTopKV2 = InTopKV2[T=DT_INT32, handle_ties="SAMPLE"](softmax_linear/softmax_linear, Reshape_2, in_top_k/InTopKV2/k)': 'op: "InTopKV2" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } } host_memory_arg: "predictions" host_memory_arg: "targets" host_memory_arg: "k" host_memory_arg: "precision"' and 'op: "InTopKV2" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } } host_memory_arg: "predictions" host_memory_arg: "targets" host_memory_arg: "k" host_memory_arg: "precision"'
	 [[Node: in_top_k/InTopKV2 = InTopKV2[T=DT_INT32, handle_ties="SAMPLE"](softmax_linear/softmax_linear, Reshape_2, in_top_k/InTopKV2/k)]]

Caused by op u'in_top_k/InTopKV2', defined at:
  File "eval_CIFAR10.py", line 146, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 129, in run
    _sys.exit(main(argv))
  File "eval_CIFAR10.py", line 141, in main
    evaluate()
  File "eval_CIFAR10.py", line 116, in evaluate
    top_k_op = tf.nn.in_top_k(logits, labels, 1, handle_ties="SAMPLE")
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 2523, in in_top_k
    return gen_nn_ops._in_top_kv2(predictions, targets, k, handle_ties, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2536, in _in_top_kv2
    handle_ties=handle_ties, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3101, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1583, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Multiple OpKernel registrations match NodeDef 'in_top_k/InTopKV2 = InTopKV2[T=DT_INT32, handle_ties="SAMPLE"](softmax_linear/softmax_linear, Reshape_2, in_top_k/InTopKV2/k)': 'op: "InTopKV2" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } } host_memory_arg: "predictions" host_memory_arg: "targets" host_memory_arg: "k" host_memory_arg: "precision"' and 'op: "InTopKV2" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } } host_memory_arg: "predictions" host_memory_arg: "targets" host_memory_arg: "k" host_memory_arg: "precision"'
	 [[Node: in_top_k/InTopKV2 = InTopKV2[T=DT_INT32, handle_ties="SAMPLE"](softmax_linear/softmax_linear, Reshape_2, in_top_k/InTopKV2/k)]]

If you can kindly look into the matter I shall be much helped. Thank you.

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by rezwan16** [comment]
The issue is related to a new feature request (added option to deal with ties in _in_top_k_ op). Is the feature requested in  #10767  part of the latest tensorflow? I cloned the latest tensorflow version from github and could not find the change. Just wondering if anyone has implemented the [changes](https://github.com/nolanliou/tensorflow/commit/681724f94e025bbd8377c5406eec4047d58fc31b) done by @nolanliou and others and became successful to add _handle_ties_ argument to the _in_top_k_ op.

**Comment by drpngx** [comment]
Right, implementing a new feature is also a kind of usage question. It's best to share your experience so we can build the knowledge base on stackoverflow..

**Comment by rezwan16** [comment]
I have asked the question [here](https://stackoverflow.com/questions/47706810/dealing-with-ties-in-in-top-k-op-of-tensorflow) in StackOverflow.

**Comment by drpngx** [comment]
Thanks!
