### ISSUE TITLE
[Feature Request] Graph embedding (DeepWalk, LINE, ...)

### ISSUE THREAD

**Issue by gear** [tensorflow/tensorflow#1503]
Hello,

Recently algorithms such as DeepWalk or LINE, by applying word embedding techniques to graph, have opened a way to apply deep learning to graph analysis. I wonder if there is any future plan for Tensorflow to support graph / network analysis in general and graph embedding in specific?

**Comment by mrry** [comment]
I imagine we'd welcome contributions to https://github.com/tensorflow/models with graph embedding models. If there are any specific features missing from core TensorFlow that would enable these models to be expressed efficiently, please let us know!

**Comment by girving** [comment]
Adding contributions welcome in case someone feels like contributing a graph model to tensorflow/models.

**Comment by suiyuan2009** [comment]
I'd like to implement deepwalk since it's related to my study.

**Comment by vsuriya93** [comment]
Can I implement DeepWalk algorithm for tensorflow framework and ask for a pull request?

**Comment by girving** [comment]
@suiyuan2009 @vsuriya93 TensorFlow itself is the wrong place for such an algorithm, but https://github.com/tensorflow/models would work.

**Comment by suiyuan2009** [comment]
@vsuriya93 I'm not working on this currently, just go ahead!

**Comment by vsuriya93** [comment]
Thanks.. But @suiyuan2009 should I create a graph representation module then?

**Comment by suiyuan2009** [comment]
@vsuriya93 , yes, I suggest Forward Star (Reverse Star) since you can allocate a continuous memory space before adding edge, if you know the graph size first. You can define your own input pipelines to load data to your graph tensor. You may need a path generator op. Graph is hard to partition, which may limits input size.
