### ISSUE TITLE
rolling window batch operation for tf.data.Dataset

### ISSUE THREAD

**Issue by devinsaini** [tensorflow/tensorflow#15044]
_This is a feature request_

For Datasets that represent a sequence or time series, it can be useful to have a Dataset op that creates a rolling window batch over the given Dataset. For example, if I have a tf.data.Dataset whose elements represent a time series (line breaks separate elements):
```
1
2
3
4
5
6
7
8
9
```
The rolling window batch would create a dataset with the following elements (for window size 4 and stride 1):
```
1 2 3 4
2 3 4 5
3 4 5 6
4 5 6 7
5 6 7 8
6 7 8 9
```
This operation will be extremely useful for extracting sub sequences from a time series for training RNNs and Reinforcement Learning models.

**Comment by aselle** [comment]
@mrry, care to comment on this feature request?

**Comment by mrry** [comment]
This sounds like a reasonable thing to add as a custom transformation in `tf.contrib.data`. If each of the time series are small and can fit in memory, you can generate the windows using `Dataset.flat_map()` as I suggested [here](https://github.com/tensorflow/tensorflow/issues/14906#issuecomment-347396872). However, it might make sense to support a similar transformation of unbounded-length streams.

**Comment by Carter440** [comment]
I've got a solution running on my machine. I'll need to do more testing before I submit a pull req.

**Comment by Carter440** [comment]
How would we like to handle the event that the window + stride does not divide evenly into the length of the dataset?

eg: [0,1,2,3,4] window=3 stride=1 --> [[0,1,2],[1,2,3],[2,3,4]] OK
eg: [0,1,2,3,4] window=3 stride=3 --> [[0,1,2][3,4]] (size of last window is smaller) 
                                                                or just [[0,1,2]] (end early)

**Comment by devinsaini** [comment]
Ending early should definitely be an option. I think there can also be an option to pad shorter final sequence with a given value, or the last value. 
@mrry what do you think?

**Comment by Carter440** [comment]
just submitted a pull. This one just has the end early version. Looking into how to fill out the last bit.

Also don't try to use it with anything too big fit into RAM.

**Comment by carlthome** [comment]
Status?

I did something like this via `tf.contrib.signal` for flat_map but it would be nice to have sliding windows builtin in `tf.data`:
```python
def window(x, width=16, step=4, axis=-1):
    x = tf.contrib.signal.frame(x, width, step, axis=axis)
    frames = tf.shape(x, out_type=tf.int64)[axis]
    return tf.data.Dataset.range(frames).map(lambda i: tf.gather(x, i, axis=axis))
```

**Comment by facaiy** [comment]
I have written a C++ prototype, and I'd like to open a pull request for discussion next week.

**Comment by facaiy** [comment]
@mrry  Hi, I opened #16123 to resolve the issue. Because I'm not familiar with bazel, I get into trouble when I try to move c++ implementation from `core` to `contrib`. Could you take a look? And any help will be appreciated.

**Comment by jperl** [comment]
I don't know if this is performant but this solution has been working for me.

https://gist.github.com/jperl/954631259eda0f81be750b67e25f9bc4

**Comment by jperl** [comment]
Hmm seems like I have just reproduced tf.contrib.signal.frame. 🤦‍♂️
