### ISSUE TITLE
Running tensorflow-gpu in virtual env in remote Ubuntu system

### ISSUE THREAD

**Issue by preetivyas** [tensorflow/tensorflow#15059]
I was attempting to install tensorflow gpu version for my gpu system.
 - I don't have sudo access in the computer. 
 - Cuda version 7.5 (V7.5.17) is installed
After following all the steps and finding a suitable version of tensorflow suitable to cuda 7.5 I have installed everything. But after installing when I am trying to import tensorflow, these errors are coming. 
![image](https://user-images.githubusercontent.com/31855851/33518214-456db3ce-d75f-11e7-8d7e-a4f62f1c6dcc.png)

I don't know how to resolve it. Also, does this error affect the running of my code in gpu or can I ignore it and start coding?
The solutions I found on forum is related to reinstalling cuda but I cannot do that as I don't have sudo access. Can anyone please provide me some other solution to resolve this issue?
I really want to setup my environment soon for the project. 
Thank you!

Additional info

OS Platform and Distribution Ubuntu v 16.04
TensorFlow installed via creating virtualenv
TensorFlow version 0.12.0rc0
Bazel version - Not used
CUDA/cuDNN version - 7.5 
GPU model and memory - NA
Exact command to reproduce - NA

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by preetivyas** [comment]
Hello everyone the error is resolved. 
I followed this https://gist.github.com/digvijayky/e2f91af603b83396d6b3f2d281bb97a7
Linked the cuda directory to path using these and it works now.
![image](https://user-images.githubusercontent.com/31855851/33529532-1b021a4e-d840-11e7-9d0c-d15de6a77b1a.png)
![image](https://user-images.githubusercontent.com/31855851/33529535-28574e6c-d840-11e7-824b-481baf93200f.png)
