### ISSUE TITLE
ImportError: No module named tensorboard

### ISSUE THREAD

**Issue by wanji** [tensorflow/tensorflow#1506]
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorboard
```
I noticed that this issue is related to #1199 

It occurs after upgraded to v0.7.1 from v0.6. Seems `pip` did not overwrite `/usr/local/bin/tensorboard` when installing `tensorflow`. And the following `import` statement in the old script cause the error:

```python
from tensorflow.tensorboard.tensorboard import main
```

**Comment by vrv** [comment]
I don't think this is the same as #1199, and I'm not sure why pip upgrade doesn't overwrite /usr/local/bin/tensorboard -- it might be a permissions issue.  Uninstalling the pip, removing /usr/local/bin/tensorboard and then reinstalling should solve the problem.

**Comment by wanji** [comment]
Yes, removing the script and reinstalling can solve the problem. I installed the package with `sudo`, so it doesn't feel like a permission issue. Anyway, this might not be a `tensorflow` issue (:
