### ISSUE TITLE
Failing to retrieve AWS credentials running in ECS with the s3 provider

### ISSUE THREAD

**Issue by stefansedich** [tensorflow/tensorflow#15066]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master
- **Python version**: 3.6.0
- **Bazel version (if compiling from source)**: 0.5.4
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**: None

### Describe the problem
When using the S3 file system provider within an ECS container I am finding that even though my task has been assigned a task role that provides access to my S3 bucket it is unable to access it successfully.

Everything works fine if I supply the credentials manually using the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables.

After some extensive head-desking I have found that the version of aws-sdk-cpp that is used (1.0.90) appears to have been released before the ECS support was added to the sdk (https://github.com/aws/aws-sdk-cpp/commit/786666db02f5ac7918642c1ee056b822e37a6f30), at a minimum I think we would want 1.0.97 so that everything works as expected.

I had originally tried to bump the version but it appears that the bazel mirror has nothing but 1.0.90 available.

**Comment by yongtang** [comment]
Added a PR #15067 to update AWS C++ SDK to 1.3.15 for the fix.

**Comment by stefansedich** [comment]
Great thanks @yongtang I had originally intended the same fix but noticed that https://mirror.bazel.build/github.com/aws/aws-sdk-cpp/archive/1.3.15.tar.gz was not returning anything so was not sure how to make that bit happen.
