### ISSUE TITLE
Multil-model restore in tensorflow

### ISSUE THREAD

**Issue by CodesFarmer** [tensorflow/tensorflow#15070]
I have two model without scope name but they have same variable name, I want load them simultaneously, but it will crash and throw error, which is "Variable XXX already exists".
I notice the issue[https://github.com/tensorflow/tensorflow/issues/3270](url), but the problem is solved by re-training the model again and save them under different scope.
However, I do not want to re-train them again. So how can I load existing models and save them into two different scope?
Any advise or help will be appreciated!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by arixlin** [comment]
reuse=True

**Comment by CodesFarmer** [comment]
@arixlin I have tried setting reuse=True, but another error occurs.
The two models have both same and different named variables, so if set reuse=True, there are some variables does not pre-defined, and it seems that the followed variables will override the afore-restored variables.
Now I just want to add prefix for all variables within a model.
For examples, there are exist 'conv1/weight' in A model and 'conv1/weight' in B model,
I want to add prefix "model_A" and "model_B" for all variables in A and B separately
The previous variable now should be:
'model_A/conv1/weight' in model A
and
'model_B/conv1/weight' in model B

**Comment by arixlin** [comment]
@CodesFarmer  load all variables to memory，I think it’s feasible

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
