### ISSUE TITLE
When execute "bash tensorflow/contrib/lite/build_ios_universal_lib.sh", it gives the error: tensorflow/tensorflow/contrib/lite/ios_makefile.inc:2: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by voidguy** [tensorflow/tensorflow#15074]
### System information
- **Install problem**:
- **Darwin MacBook-Pro-2.local 16.7.0 Darwin Kernel Version 16.7.0, xnu-3789.71.6~1/RELEASE_X86_64 x86_64**:
- **TensorFlow installed from source**:
- **v1.0.0-rc2-15-g47bba63-dirty 1.0.0**:
- **Python 3.6.0 :: Anaconda custom (x86_64)**: 
- **Bazel version (None)**:
- **Apple LLVM version 9.0.0 (clang-900.0.37)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

**Comment by maziyang08** [comment]
I took a look at the contents of ios_makefile.inc, it's completely a mess. Hope tflite will fix this issue soon.

**Comment by voidguy** [comment]
I have corrected the file  and done it right locally.

**Comment by vinceyuan** [comment]
@voidguy Same problem here. How to fix it?

**Comment by vinceyuan** [comment]
@voidguy ok, i saw the solution: https://github.com/tensorflow/tensorflow/pull/15117

**Comment by aselle** [comment]
This appears to be fixed in #15191. Thanks for the report.
