### ISSUE TITLE
the source code to compile  about tensorflow1.1.0

### ISSUE THREAD

**Issue by zitengwm** [tensorflow/tensorflow#15076]
I am very distressed~~~
I need some help ~~~~

I refer to "TensorFlow Bindings for H2O.ai"
I execute " ./gradlew clean tensorflowCompile",but always has error,likes
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': Error downloading [http://bazel-mirror.storage.googleapis.com/github.com/bazelbuild/rules_closure/archive/5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz, https://github.com/bazelbuild/rules_closure/archive/5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz] to /root/.cache/bazel/_bazel_root/c0282f68c3c9fe7828209fa3ece89ea6/external/io_bazel_rules_closure/5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz: Checksum was 5afc2087ab53b160fb58fde30339a2c2826c1a171404b7b8ff7227d5ebc8225c but wanted 60fc6977908f999b23ca65698c2bb70213403824a84f7904310b6000d78be9ce. :deepwater-tensorflow:tensorflowCompile FAILED
errors with checksum
how can I do ,fix this problem
how can I checksum disabled

please ~~~~
thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gunan** [comment]
Please try again with a later version of TF.
This was due to github changing the compression method in their archives, and we did not go back to 1.1 to also fix this. 1.4 branch should work OK.

**Comment by zitengwm** [comment]
thank you very much ,I have result this issue,it's a network problem,our company's problem

**Comment by zitengwm** [comment]
thank you very much,I have resolved this issue,it's a network problem

**Comment by zitengwm** [comment]
thank you very much,I have resolved this issue,is't a network problem


ziteng


________________________________
发件人: Gunhan Gulsoy <notifications@github.com>
发送时间: 2017年12月14日 0:31:19
收件人: tensorflow/tensorflow
抄送: zitengwm; Author
主题: Re: [tensorflow/tensorflow] the source code to compile about tensorflow1.1.0 (#15076)


Please try again with a later version of TF.
This was due to github changing the compression method in their archives, and we did not go back to 1.1 to also fix this. 1.4 branch should work OK.

―
