### ISSUE TITLE
No GPU OpKernel for tf.exp() operation for Complex64

### ISSUE THREAD

**Issue by VinceMarron** [tensorflow/tensorflow#15103]
I am running tensorflow 1.4.0 from nightly build ('v1.3.0-rc1-5297-g4b7d79b6ea'  on ubuntu 16.04). I've had success working in eager mode (great job with this guys!) however I think I found a small bug:

It seems that there is no OpKernel on device='GPU'  for the tf.exp() operation applied to complex numbers in eager mode.  This can be reproduced with the below code:

```
import tensorflow as tf
import tensorflow.contrib.eager as tfe

tfe.enable_eager_execution()

with tf.device('/gpu:0'):
  g = tf.spectral.rfft(tf.ones(64))
  
  tf.exp(g)
```
which results in
```NotFoundError: No registered 'Exp' OpKernel for GPU devices compatible with node Exp = Exp[T=DT_COMPLEX64](dummy_input)
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
 [Op:Exp]
```

a more practical example that would lead to this same error:

```
import tensorflow as tf
import tensorflow.contrib.eager as tfe

tfe.enable_eager_execution(device_policy=tfe.DEVICE_PLACEMENT_SILENT)

frame_length=256
frame_step=64
n_mels = 64
sr=16000
filename = 'path/to/a.wav'

some_signal = tf.contrib.ffmpeg.decode_audio(tf.read_file(filename), 
                                     file_format='wav', 
                                     samples_per_second=16000, 
                                     channel_count=1)

with tf.device('/gpu:0'):
  stft = tf.contrib.signal.stft(tf.transpose(some_signal), frame_length=frame_length, 
                                  frame_step=frame_step, fft_length=frame_length)

  linear_to_mel_weight_matrix = tf.contrib.signal.linear_to_mel_weight_matrix(
      n_mels, 1+frame_length//2, sr)

  magnitude_spectrograms = tf.abs(stft)
  log_mel_spec = tf.log(1e-6+ tf.tensordot(magnitude_spectrograms,
                                           linear_to_mel_weight_matrix, 
                                           axes = [[2], [0]]))

  mfccs = tf.contrib.signal.mfccs_from_log_mel_spectrograms(log_mel_spec)
```

Keeping operations on CPU works just fine but I figured this would be easy to implement for GPU as well. Thanks

**Comment by asimshankar** [comment]
Thanks for the report @VinceMarron . This behavior isn't an artifact of eager execution, just that we don't have GPU kernels (in eager or graph) for Complex types for the Exp operation (see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_op_exp.cc)

I don't believe we have any immediate plans for GPU kernels for exp for complex types, but contributions are welcome.

Thanks!

**Comment by VinceMarron** [comment]
Gotcha. Thanks for looking into this @asimshankar . My error on assuming it was related to eager. 

I looked into contributing a general resolution but I don't think I have the know-how in terms of Tensorflow structure and C. What I can provide is a framework for implementing it in terms of real (tf.float32) operations that are implemented on gpu - [cwise_op_cos](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_op_cos.cc) and [cwise_op_exp](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_op_exp.cc)


```
import tensorflow as tf
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()

a=tf.random_normal([1], dtype=tf.float32)
b=tf.random_normal([1], dtype=tf.float32)

complex_num = tf.complex(a,b)
cpu_exp_complex_num = tf.exp(complex_num) #complex calc on cpu
gpu_exp_complex_num = tf.complex(tf.exp(a)*tf.cos(b), tf.exp(a)*tf.sin(b)) #complex calc on gpu

assert cpu_exp_complex_num.numpy() == gpu_exp_complex_num.numpy()
```

I'm not sure if that is helpful or already obvious but I'd be happy to assist an effort to implement this.

**Comment by rryan** [comment]
@VinceMarron in your STFT example, the Mel matrix is the only part that relies on Exp I believe. You can move the `linear_to_mel_weight_matrix` outside of the GPU device assignment block, or use soft device placement (which should automatically put the Exp on CPU): https://www.tensorflow.org/tutorials/using_gpu#using_a_single_gpu_on_a_multi-gpu_system

**Comment by VinceMarron** [comment]
@rryan  -- Agreed. I may be mistaken but I think the tf.gather() portion of tf.contrib.signal.stft() must run on cpu, and cpu is probably better suited for that operation, whereas having to copy a tensor to cpu to run tf.exp() on complex64 seemed silly. It appears @facaiy has implemented a gpu kernel that fixes this. Thanks.

**Comment by rryan** [comment]
@VinceMarron -- Gather does have a GPU kernel (I'm one of its authors :)). 

https://github.com/tensorflow/tensorflow/blob/70e33e0f77cb4f92ddd70a8dd601873b178124fc/tensorflow/core/kernels/gather_op.cc#L153

https://github.com/tensorflow/tensorflow/blob/70e33e0f77cb4f92ddd70a8dd601873b178124fc/tensorflow/core/kernels/gather_functor_gpu.cu.cc

**Comment by VinceMarron** [comment]
Ah.. Awesome work on this @rryan. Clearly I'm the rookie here (but trying to learn..)

I very well could be doing something else wrong but appears there is a glitch in 'gathering' from frame indices on gpu in eager mode. 

Example:

In standard graph mode this code runs just fine:

```
import tensorflow as tf

frame_length=256
frame_step=64


signal = tf.random_uniform((1,16000), minval=-1, maxval=1)

with tf.device('/gpu:0'):
  frames = tf.contrib.signal.frame(signal, frame_length=frame_length, 
                                  frame_step=frame_step)
  with tf.Session() as sess:
    frames_out = sess.run(frames)
    
print(frames_out[0, :2, :2], frames_out.shape)

```

> output:
>[[ 0.64405823 -0.69103551]
 >[-0.37752914  0.50947428]] (1, 247, 256)

The equivalent code in eager mode, however, produces an error:

```
import tensorflow as tf
import tensorflow.contrib.eager as tfe

tfe.enable_eager_execution()

frame_length=256
frame_step=64


signal = tf.constant(tf.random_uniform((1,16000), minval=-1, maxval=1))

with tf.device('/gpu:0'):
  frames = tf.contrib.signal.frame(signal, frame_length=frame_length, 
                                  frame_step=frame_step)
    
print(frames[0, :2, :2], frames.shape)

```

> ---------------------------------------------------------------------------
> InvalidArgumentError                      Traceback (most recent call last)
> <ipython-input-1-6254609ba767> in <module>()
>      12 with tf.device('/gpu:0'):
>      13   frames = tf.contrib.signal.frame(signal, frame_length=frame_length, 
> ---> 14                                   frame_step=frame_step)
>      15 
>      16 print(frames[0, :2, :2], frames.shape)
> 
> ~/anaconda3/envs/tf_source/lib/python3.5/site-packages/tensorflow/contrib/signal/python/ops/shape_ops.py in frame(signal, frame_length, frame_step, pad_end, pad_value, axis, name)
>     114     axis = math_ops.range(signal_rank)[axis]
>     115 
> --> 116     signal_shape = array_ops.shape(signal)
>     117     outer_dimensions, length_samples, inner_dimensions = array_ops.split(
>     118         signal_shape, [axis, 1, signal_rank - 1 - axis])
> 
> ~/anaconda3/envs/tf_source/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py in shape(input, name, out_type)
>     276     A `Tensor` of type `out_type`.
>     277   """
> --> 278   return shape_internal(input, name, optimize=True, out_type=out_type)
>     279 
>     280 
> 
> ~/anaconda3/envs/tf_source/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py in shape_internal(input, name, optimize, out_type)
>     304         if optimize and input_shape.is_fully_defined():
>     305           return constant(input_shape.as_list(), out_type, name=name)
> --> 306       return gen_array_ops.shape(input, name=name, out_type=out_type)
>     307 
>     308 
> 
> ~/anaconda3/envs/tf_source/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py in shape(input, out_type, name)
>    4479     _attrs = ("T", _attr_T, "out_type", out_type)
>    4480     _result = _execute.execute(b"Shape", 1, inputs=_inputs_flat, attrs=_attrs,
> -> 4481                                ctx=_ctx, name=name)
>    4482   _execute.record_gradient(
>    4483       "Shape", _inputs_flat, _attrs, _result, name)
> 
> ~/anaconda3/envs/tf_source/lib/python3.5/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
>      64     else:
>      65       message = e.message
> ---> 66     six.raise_from(core._status_to_exception(e.code, message), None)
>      67   # pylint: enable=protected-access
>      68   return tensors
> 
> ~/.local/lib/python3.5/site-packages/six.py in raise_from(value, from_value)
> 
> InvalidArgumentError: Tensors on conflicting devices: cannot compute Shape as input #0 was expected to be on /job:localhost/replica:0/task:0/device:GPU:0 but is actually on /job:localhost/replica:0/task:0/device:CPU:0 (operation running on /job:localhost/replica:0/task:0/device:GPU:0) Tensors can be copied explicitly using .gpu() or .cpu(), or transparently copied by using tfe.enable_eager_execution(tfe.DEVICE_PLACEMENT_SILENT). Copying tensors between devices may slow down your model [Op:Shape] name: frame/Shape/


Using  tfe.enable_eager_execution(tfe.DEVICE_PLACEMENT_SILENT) works just fine as a work around but I figure there is a small fix to be done to allow this to work entirely on gpu.

**Comment by rryan** [comment]
@VinceMarron huh, so I haven't used Eager mode with a GPU, but I think that error is saying your `signal` tensor is not located on the GPU, while the op `Shape` (which is part of the subgraph created by `tf.contrib.signal.frame`) expected that it was. 

Can you try the advice in the error of putting `.gpu()` on the end of your definition of signal to explicitly copy it to the GPU?  Or maybe define `signal` within the `with tf.device('/gpu:0'):` block.

**Comment by rryan** [comment]
@VinceMarron so sorry I didn't see your most recent post. I think whatever issue you're seeing might have been fixed, because I just ran your examples on TF 1.9.0 on a Colab w/ GPU and don't see the error.
