### ISSUE TITLE
Documentation required for SetIsStateful() method in OP registration

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#15102]
There are some examples with custom ops that use SetIsStateful() method during registration, e.g. https://www.tensorflow.org/extend/new_data_formats

But there is no documentation about that method.

**Comment by aselle** [comment]
This is documented  in the underlying op_def.proto that REGISTER generates...
https://github.com/tensorflow/tensorflow/blob/0b131503a04f1ebbe0967bebb2559dd1367baded/tensorflow/core/framework/op_def.proto#L125-L133

**Comment by shkarupa-alex** [comment]
Ok, "mooving between devices"...

But why string ops does not have such constraint https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/string_ops.cc

It's still not clear.

**Comment by drpngx** [comment]
@shkarupa-alex it looks like @aselle answered the question. Reading the doc, I think the doc is clear enough for a reasonably skilled tensorflow developer. That's a tradeoff for conciseness. Feel free to submit a PR if you find a better wording.
