### ISSUE TITLE
Using tfdbg with Monitored Session

### ISSUE THREAD

**Issue by karthik-hegde** [tensorflow/tensorflow#15105]
### System information
- I am using a modified version of  [CIFAR10 tutorial](https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10) TensorFlow.
- CentOS Linux release 7.3.1611
- TensrFlow from Source
- TensorFlow v1.3
-  Python 2.7

### Describe the problem
Hello,

I see that I can not use tfdbg with Monitored session. That is if I try to wrap `mon_sess = tf_debug.LocalCLIDebugWrapperSession(mon_sess)` where `mon_sess` is `tf.train.MonitoredTrainingSession(` I get the following error:

`TypeError: Expected type <class 'tensorflow.python.client.session.BaseSession'>; got type <class 'tensorflow.python.training.monitored_session.MonitoredSession'>`

Can there be a support from Debugger with Monitored Sessions?

**Comment by reedwm** [comment]
This has been fixed in dc58dcbea9beb30e0013f41e08786471ca4a6cb6. Try upgrading to TensorFlow 1.4.

**Comment by karthik-hegde** [comment]
Hello,

Thanks for the info, I updated to v1.4 and `tfdbg` works for me.

However, there seems to be some unsupported features. When I ran with `tfdbg> run -f has_inf_or_nan`, my model diverged with a NaN. 

However, I received the following error:

`tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
Exception ignored in: <bound method LocalCLIDebugWrapperSession.__del__ of <tensorflow.python.debug.wrappers.local_cli_wrapper.LocalCLIDebugWrapperSession object at 0x7ff95630a6a0>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/tensorflow/python/debug/wrappers/framework.py", line 705, in __del__
AttributeError: 'MonitoredSession' object has no attribute '__del__' `.

Can you please guide me through this?

**Comment by reedwm** [comment]
I can reprodce on master with the following program:

```python
import tensorflow as tf
from tensorflow.python import debug as tf_debug

with tf.train.MonitoredSession() as sess:
  sess = tf_debug.LocalCLIDebugWrapperSession(sess)
  del sess
```

@caisq, can you fix this?

**Comment by caisq** [comment]
Thanks for letting me know. Will fix it soon.
