### ISSUE TITLE
Compiling CPU version on windows X86

### ISSUE THREAD

**Issue by kaynon17** [tensorflow/tensorflow#15114]
System Information:
WIN 10
Visual studio 2015
Swigwin 3.0.12
Python 3.5.3
Cmake 3.10.0

Question description:

I am a new one about tensorflow, I used cmake command in cmd just like this:

cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=D:/swigwin-3.0.12/swig.exe -DPYTHON_EXECUTABLE=D:/Programs/Python/Python35/python.exe -DPYTHON_LIBRARIES=D:/Programs/Python/Python35/libs/python35.lib -Dtensorflow_ENABLE_GPU=OFF

and got the x64 vs project, but when I wanted to generate x86 version with similar commnd like:  

cmake .. -A x86 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=D:/swigwin-3.0.12/swig.exe -DPYTHON_EXECUTABLE=D:/Programs/Python/Python35/python.exe -DPYTHON_LIBRARIES=D:/Programs/Python/Python35/libs/python35.lib -Dtensorflow_ENABLE_GPU=OFF

then I got a error:

cmake .. -A x86 -DCMAKE_BUILD_TYPE=Debug -DSWIG_EXECUTABLE=D:/swigwin-3.0.12/swig.exe -DPYTHON_EXECUTABLE=D:/Programs/Python/Python35/python.exe -DPYTHON_LIBRARIES=D:/Programs/Python/Python35/libs/python35.lib -Dtensorflow_ENABLE_GPU=OFF
CMake Error at CMakeLists.txt:5 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe

  to get the value of VCTargetsPath:

Now I want to ask: does tensorflow support x86 windows? Did anyone build the x86 version once before?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by kaynon17** [comment]
I mistook the command. When I used the command: cmake .. -A Win32 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=D:/swigwin-3.0.12/swig.exe -DPYTHON_EXECUTABLE=D:/Programs/Python/Python35/python.exe -DPYTHON_LIBRARIES=D:/Programs/Python/Python35/libs/python35.lib -Dtensorflow_ENABLE_GPU=OFF, I got the right project.
