### ISSUE TITLE
XLA Reshape_test failing for 3rd party platforms

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#15124]
I have opened a discussion on the XLA dev mailing list, but I think that this counts as an issue since if it isn't fixed then potentially all XLA tests will migrate to being unusable for 3rd party devices.

https://groups.google.com/forum/#!topic/xla-dev/9cY21Hi0s_s

The issue is that the code in reshape_test.cc assumes that any devices which are not CPU/CPU_PARALLEL/GPU will use the bfloat16 format.  This isn't true for the Graphcore device.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by DavidNorman** [comment]
Hi,

No problem.

OS Platform and Distribution:
- all platforms and distrubutions

Tensorflow installed from:
- source

Tensorflow version:
- master branch of repo

Bazel version:
- unknown / not relevent

CUDA/cuDNN version:
- none

GPU model and memory:
- none

Exact command to reproduce:
- bazel test --test_env TF_CPP_MIN_VLOG_LEVEL=1  --verbose_failures --test_output=all --nocache_test_results --config=opt tensorflow/compiler/xla/tests:reshape_test_poplar

this only works if you have the Graphcore extensions which you will not.  see issue on the XLA dev board.

**Comment by ukoxyz** [comment]
Hi David, thanks for reporting this issue. We have committed a workaround to disable bfloat16 tests for unknown backends by default:
https://github.com/tensorflow/tensorflow/commit/557e0ce1ca949abb0ffdcccc6ab0480e65ea9fe1

**Comment by drpngx** [comment]
Thakns @ukoxyz . @DavidNorman I think that should solve your problem. Feel free to reopen if it doesn't.
