### ISSUE TITLE
Is their any java spark api available for using Tensor

### ISSUE THREAD

**Issue by AtulKumVerma** [tensorflow/tensorflow#15126]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by AtulKumVerma** [comment]
version is  not matter, i can configure as corresponding,
and plz give some deeplearnig example too with spark and tensorflow.

**Comment by av8ramit** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
