### ISSUE TITLE
Tensorflow broken by new Bazel versions

### ISSUE THREAD

**Issue by laurentlb** [tensorflow/tensorflow#15137]
Simplest way to reproduce the issue, run:
`$ bazel build --config=opt --incompatible_load_argument_is_label --nobuild //tensorflow/tools/pip_package:build_pip_package`

Suggested fix to `tensorflow/third_party/sycl/sycl/BUILD.tpl`:
```
-load("platform", "sycl_library_path")
+load(":platform.bzl", "sycl_library_path")

-load("platform", "readlink_command")
+load(":platform.bzl", "readlink_command")
```

This should address the immediate need.
There are other issues to fix (although not as pressing). You can see them by building using `--all_incompatible_changes`.

Let me know if you need any help.
Thanks!

**Comment by gunan** [comment]
Thanks for the report @laurentlb Could you file a bug internally for us to quickly triage this?

**Comment by angersson** [comment]
I've prepared a change that will fix this internally.

**Comment by angersson** [comment]
The fix has been applied to our internal branch. The next repository sync should bring the fix over to Github.

**Comment by laurentlb** [comment]
Thanks!
