### ISSUE TITLE
 model.fit crash ( keras example mnist) TensorFlow1.4

### ISSUE THREAD

**Issue by EVA-wu** [tensorflow/tensorflow#15151]
I run example : https://github.com/fchollet/keras/blob/master/examples/mnist_cnn.py
but it crashed when train, namely model.fit

The error is :
An error ocurred while starting the kernel
\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that thisTensorFlow binary was not compiled to use: AVX AVX2
\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties: 
\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) ‑> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
tensorflow\stream_executor\cuda\cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
tensorflow\stream_executor\cuda\cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
\tensorflow\core\kernels\conv_ops.cc:667] Check failed: stream‑>parent()‑>GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo(), &algorithms) 

And I run another example it crashed too when run at  model.fit, but the error is not the same:
An error ocurred while starting the kernel
\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) ‑> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
 \tensorflow\stream_executor\cuda\cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
tensorflow\stream_executor\cuda\cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
 \tensorflow\core\kernels\conv_ops.cc:667] Check failed: stream‑>parent()‑>GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo(), &algorithms) 
 

# My environment:
win7
tensorflow-gpu 1.4
cuda 8.0 
cudnn6.0 
GeForce GTX 1080 Ti 

I really appreciate your help！

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by reedwm** [comment]
This seems like the same issue as #6698. Try some of the advice there. In particular, try making sure no other processes are using the GPU by running `nvidia-smi`.

@mrry, any ideas what the problem could be?

**Comment by mrry** [comment]
No idea, sorry!

**Comment by EVA-wu** [comment]
Thank you for your replies so quickly ! It's OK when i restart the computer.

**Comment by EVA-wu** [comment]
After that i think i should introduce this solve in detail , 
if you  encounter 
"An error ocurred while starting the kernel
cc:366  failed to create cublas handle: CUBLAS_STATUS_NOT_INITALIZED
cc:4637 stream 000000000F5CB190 did not memcpy host-to-device; sorce:0000000204C00900
cc306 Error recording event in stream:error recording CUDA event on stream 0000000008C4220:
CUDA_ERROR_OUT_OF_MEMORY; not marking stream as bad,as the Event object may be at fault. Monitor for further errors. 
cc:49    Error polling for event status: failed to query event: CUDA_ERROR_OUT_OF_MEMORY
\tensorflow\core\common_runtime\gpu\gpu_event_mgr.cc
 Unexpected Event status:1"
maybe because cudnn is not match. 

 Then i  set a new environment install tensorflow1.4 which has keras without install，but after installing i did not check GPU, just as reedwm say “other processes are using the GPU ”. So i restart the computer.
Thank you!
