### ISSUE TITLE
Feature: MonitoredSession should have run() method with 'hooks_to_trigger' argument: run(..., hooks_to_trigger=[hooks[1], hooks[3], ...])

### ISSUE THREAD

**Issue by maxfiedler** [tensorflow/tensorflow#15158]
At the moment the session_run_hooks are passed to the constructor of MonitoredSession(..., hooks=[...]) 
and then they get executed for EVERY session.run() call within the MonitoredSession block.

This is inefficient and problematic.

E.g., if I define a LoggingTensorHook, I want the logging output to be evaluated and printed at most ONCE per global step and not after some auxiliary session.run() calls that only evaluate the size of some queue or whatever else.

If you use feedable iterators, the current MonitoredSession implementation actually crashes the program, see https://github.com/tensorflow/tensorflow/issues/12859#issuecomment-348290076

The best solution in my opinion would be, to be able to specify which run() calls should actually trigger the before_run and after_run methods of the hooks, e.g. via some flag-argument in MonitoredSession.run(..., execute_hooks=True)
or alternatively pass a list of specific hooks whose before_run and after_run methods should be triggered by a run call, via MonitoredSession.run(..., hooks_to_trigger=[...])

**Comment by maxfiedler** [comment]
Simple solution could be: (in _HookedSession) marked with **
```
def run(self, fetches, feed_dict=None, options=None, run_metadata=None, **hooks_to_trigger=[None]**):
    """See base class."""
    if self.should_stop():
      raise RuntimeError('Run called even after should_stop requested.')

    actual_fetches = {'caller': fetches}

    run_context = session_run_hook.SessionRunContext(
        original_args=session_run_hook.SessionRunArgs(fetches, feed_dict),
        session=self._sess)

    options = options or config_pb2.RunOptions()
    feed_dict = self._call_hook_before_run(run_context, actual_fetches,
                                           feed_dict, options, **hooks_to_trigger**)

    # Do session run.
    run_metadata = run_metadata or config_pb2.RunMetadata()
    outputs = _WrappedSession.run(self,
                                  fetches=actual_fetches,
                                  feed_dict=feed_dict,
                                  options=options,
                                  run_metadata=run_metadata)

    for hook in **list(set(self._hooks).intersection(hooks_to_trigger))**:
      hook.after_run(
          run_context,
          session_run_hook.SessionRunValues(
              results=outputs[hook] if hook in outputs else None,
              options=options,
              run_metadata=run_metadata))
    self._should_stop = self._should_stop or run_context.stop_requested

return outputs['caller']
```

**Comment by ispirmustafa** [comment]
We think allowing different hook sets to be used in each run complicates the usage. MonitoredSession.run_step_fn should be used instead.

**Comment by maxfiedler** [comment]
Okay.
Personally, I don't think that will offer enough flexibility. What if you need to implement Faster R-CNN style alternative training schedules, where you first train only the RPN and then the classifier Head. 
If you use e.g. a LoggingTensorHook in this setting and tell it to log Tensors both from RPN and the Head, then you will produce an error while training only RPN for the first time as Tensors in the Head cannot be evaluated yet. 
Wrapping all this in the run_step_fn would be super convoluted and ugly. 
I guess you can say, that for such more complex problems one just should not use hooks at all ...

**Comment by maxfiedler** [comment]
Why not at least implement a simple switch with which you can signal that a specific session.run should NOT trigger the hooks?
i.e. `MonitoredSession.run(..., trigger_hooks=False)` (default=True)

**Comment by isaprykin** [comment]
Hi!  

Would [after_create_session()](https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/python/training/session_run_hook.py#L115) work for something that you want to run only once?

What are those "auxiliary session.run() calls" that you are talking about?  [The relevant queues that I can think of are given](https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/python/training/monitored_session.py#L557) the raw session that doesn't run hooks.

**Comment by maxfiedler** [comment]
As an example, in our old input pipeline, we needed to evaluate the current size of the RandomShuffleQueues several times within the session block, in order to efficiently be able to switch between training and validation queues. For these evaluations we needed three separate session.run(rsq.size) calls, that evaluated nothing else and that always triggered all hooks, even though nothing in the weights had changed in the meantime. So for example LoggingTensorHook would log the same tensors with exactly the same values 4 times in the same global step. 
So, here it would have been nice to tell the hooks to just ignore the session.run(rsq.size) calls.

**Comment by maxfiedler** [comment]
As for the problem with creating the string_handles for the feedable iterator, after_create_session could be used to solve it, I guess but then I would have to create an extra hook just for that, that would also make the code much harder to read. 
I am not a great fan of hiding away simple logical algorithmic steps in convoluted constructs. I should be able to recognize all essential steps of the graph evaluation in the session block (so, except for logging and saving stuff, for this hooks are great).
So, I would still like to have this structure:
```
with MonitoredSession(hooks=hooks) as sess: 
  # everything that needs to be evaluated only once
  handles = session.run(handles)
  condition = session.run(some_structural_evaluation_of_the_graph )

  # everything that needs to be evaluated per global step
  while iter < iter_max and not sess.should_stop():
    session.run(opt)
    ...
```

**Comment by isaprykin** [comment]
If you run the calls to evaluate the size of the queue inside run_step_fn, then it won't trigger hooks.

In your code example, suppose the MonitoredSession instance handled a transient failure for you that resulted in a new underlying raw session.  The new session has restored from the last saved checkpoint, possibly undoing the updates that have been computed but haven't been checkpointed yet.  In such a scenario, would like for `session.run(handles)` and for `session.run(some_structural_evaluation_of_the_graph)` to be re-run for you when the session is re-recreated and variables are restored?

**Comment by pl-lee** [comment]
> Why not at least implement a simple switch with which you can signal that a specific session.run should NOT trigger the hooks?
> i.e. MonitoredSession.run(..., trigger_hooks=False) (default=True)
> or a separate wrapper MonitoredSession.run_without_hooks
> Seems way more straightforward than having to implement a step_fn with an if-statement that is executed only once and then never again (in the example you gave:
> def step_fn(step_context):
>   if handle_train is None:
>     handle_train, handle_val = sess.run([iter_train_handle, iter_val_handle])
>   return step_context.run_with_hooks(fetches=..., feed_dict=...)

Could you give a complete example by using this step_fn?Thanks!
