### ISSUE TITLE
Strange Dataset API behaviour

### ISSUE THREAD

**Issue by sofeikov** [tensorflow/tensorflow#15152]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
v1.4.0-rc1-11-g130a514 1.4.0
- **Python version**: 
sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)
- **Bazel version (if compiling from source)**:
n/a
- **GCC/Compiler version (if compiling from source)**:
n/a
- **CUDA/cuDNN version**:
Cuda 8.0 
- **GPU model and memory**:
Titan XP 12Gb
- **Exact command to reproduce**:

### Describe the problem
I get very strange behaviour of image read function. See attached screenshot from tensorboard. This is NOT a tensorboard problem as I get images as they are from Dataset object.
![kodak_messed](https://user-images.githubusercontent.com/6204851/33659749-37586c4e-da79-11e7-8977-7d8f6da31c2d.png)

Source images are fine, I have attached a zip archive with source images:
[Kodak.zip](https://github.com/tensorflow/tensorflow/files/1534996/Kodak.zip)

```
import glob
import tensorflow as tf

def simply_read_image(image_path):
    image_string = tf.read_file(image_path)
    image_source = tf.image.decode_png(image_string, channels=3)
    image_source = tf.image.convert_image_dtype(image_source, dtype=tf.float32)
    return image_source

validation_files = glob.glob(os.path.join(validation_folder, '*.png'))

dataset = tf.data.Dataset.from_tensor_slices(validation_files)
dataset = dataset.map(simply_read_image).batch(len(validation_files)).repeat(30)

next_element = iterator.get_next()

    with tf.Session() as s:
        for i in range(30):
            im = s.run(next_element)
            for j in range(25):
                current_image = im[j]
                pass

```
Any ` current_image` with portrait orientation seems to be read incorrectly. 
### Source code / logs
There are no logs that could help

**Comment by sofeikov** [comment]
Me and my colleague have made a small investigation of this behaviour. 
The reason of this happening is very surprising. All images in Kodak set are either 512x768 or 768x512 pixels. That said, it is just a pure luck that every time you precisely the same amount of pixels. 

Every time an image is read with a correct shape, which can be seen if we put 
`tf.Print(image_source, [tf.shape(image_source)], summarize=1000)` somewhere in `simply_read_image` function.

However, after Dataset object takes it place, it "memorises" the shape of the _first_ entry and then tries to fill image buffer _somehow_. There are two indicators of this: 

1. `dataset = dataset.map(lambda x: tf.Print(x, [tf.shape(x)], summarize=1000), num_parallel_calls=12)` This line will print the same shape for all image. This shape will of the first image met in file list

2. This can be easily checked by rescaling one of images so that is has different from 512x768 amount of pixels and try to do the same.

After this the code above will crush with an obvious error:
```
InternalError (see above for traceback): HandleElementToSlice Cannot copy slice: number of elements does not match.  Shapes are: [element]: [512,768,3], [parent slice]: [433,288,3]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?,?,3]], output_types=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
```

I think this is a wrong behaviour for `dataset` object, because:

1. I may want to use `Dataset` API for running my autoencoders on real world images of different sizes.
2. In image processing tasks you can't rescale image to standard size, because images will seen by humans after network does it's job

Taking these into account and that (to the best of my knowledge) there is no other way to use `Dataset` API for image reading images of different sizes, I think this poses a problem. 

Probably the resolution could be allow dispatching images of different sizes by `dataset` object, if batch size is equal to 1.

**Comment by mrry** [comment]
Hm, it looks like the problem is that `Dataset.batch()` doesn't validate that the shapes of all elements in the batch are the same. It merely checks that the number of elements matches, which allows you to silently batch together 512x768 and 768x512 images. I'm preparing a fix.
