### ISSUE TITLE
tf.data.Dataset.from_generator creates too many threads throwing "thread constructor failed"

### ISSUE THREAD

**Issue by mumas** [tensorflow/tensorflow#15162]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:Adapted an example from documentation
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Mac OS Siera (10.12.6)
- **TensorFlow installed from (source or binary)**:pip install tensorflow 
- **TensorFlow version (use command below)**: tensorflow-1.4.0-cp27-cp27m-macosx_10_11_x86_64.whl
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: CPU
- **GPU model and memory**: NA
- **Exact command to reproduce**:

```
import itertools
import tensorflow as tf

def gen():
  for i in itertools.count(1):
    yield (i, [1] * 5)

ds = tf.data.Dataset.from_generator(
    gen, (tf.int64, tf.int64), (tf.TensorShape([]), tf.TensorShape([None])))
ds = ds.make_one_shot_iterator()

with tf.Session() as sess:
    while True:
        sess.run(ds.get_next())  # (1, array([1, 1, 1, 1, 1]))...
```

### Describe the problem
If you run the code above, which is adapted from tf.data.Dataset.from_generator docstring, the program will crash with an error: `libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable`.

I see the number of threads increasing in the activity monitor of the mac OS and when it reaches ~3K threads the program crashes. It takes several seconds. 

Please let me know if this is not intended use of this API, it is OS releated issue or there is a bug involved.

**Comment by mrry** [comment]
The problem arises from  calling `Iterator.get_next()` *inside* the loop, which creates a new operation (and, in this case, a new background thread) in each iteration. The following code should not suffer from the same problem:

```python
import itertools
import tensorflow as tf

def gen():
  for i in itertools.count(1):
    yield (i, [1] * 5)

ds = tf.data.Dataset.from_generator(
    gen, (tf.int64, tf.int64), (tf.TensorShape([]), tf.TensorShape([None])))
ds = ds.make_one_shot_iterator()

next_element = ds.get_next()

with tf.Session() as sess:
    while True:
        sess.run(next_element)
```

**Comment by mumas** [comment]
Makes sense now!

--
Linas
