### ISSUE TITLE
Failure in LMDBReaderTest while reading testdata

### ISSUE THREAD

**Issue by namrata-ibm** [tensorflow/tensorflow#15179]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: s390x Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.4.0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.7.0
- **GCC/Compiler version (if compiling from source)**: gcc 5.4.0
- **CUDA/cuDNN version**: No GPU
- **GPU model and memory**: No GPU
- **Exact command to reproduce**: bazel test -c opt  //tensorflow/python/kernel_tests:reader_ops_test

### Describe the problem
While executing `reader_ops_test`, came across failure in `LMDBReaderTest`. 
Since I am running it on a big endian system, the failure could be because the testdata(data.mdb) is platform specific and hence gets interpreted wrongly. 
@bowang, @jhseu , Is my understanding correct? How can I generate the above testdata for s390x(big endian)?

### Source code / logs
```
F tensorflow/core/kernels/lmdb_reader_op.cc:49] Check failed: mdb_env_open(mdb_env_, current_work().c_str(), flags, 0664) == 0 (-30793 vs. 0)Invalid argument
012
234
012
234
012
234
012
234
012
234
012
234
Aborted (core dumped)
```

**Comment by reedwm** [comment]
/CC @rmlarsen do you know if you can fix this despite not having access to a big endian system?

/CC @sandipmgiri @Nayana-ibm can you help us fix this?

**Comment by bowang** [comment]
@namrata-ibm `data.mdb` is very simple and generated with LMDB's python interface.
It contains ten entries as below:
```
  '0' : 'a'
  '1' : 'b'
  ...
  '9' : 'j'
```

**Comment by sandipmgiri** [comment]
We had not observed this test failure on ppc64le.

```
$ bazel test -c opt //tensorflow/python/kernel_tests:reader_ops_test
..............
INFO: Found 1 test target...
Target //tensorflow/python/kernel_tests:reader_ops_test up-to-date:
  bazel-bin/tensorflow/python/kernel_tests/reader_ops_test
INFO: Elapsed time: 21.906s, Critical Path: 1.37s
//tensorflow/python/kernel_tests:reader_ops_test                (cached) PASSED in 3.1s

Executed 0 out of 1 test: 1 test passes.

```

Please note we had executed the test for Tensorflow v1.3.1.

**Comment by namrata-ibm** [comment]
@bowang , Thank you for your inputs. 
I generated the `data.mdb` for s390x(big endian) and the test is passing with it.

**Comment by namrata-ibm** [comment]
Closing this issue.
