### ISSUE TITLE
Extend existing ops to complex128

### ISSUE THREAD

**Issue by ibab** [tensorflow/tensorflow#1517]
This is a follow-up to #1420.
Now that `complex128` is supported in tensorflow, we should extend existing ops like `complex`, `real`, `imag`, … to support `complex128` as well.
I've already done some work on this, but I'm currently stuck on expressing dependencies between input and output types.
For example, the spec for the `Real` op is currently
```c++
REGISTER_OP("Real")
    .Input("in: complex64")
    .Output("out: float");
```
I've extended this to
```c++
REGISTER_OP("Real")
    .Input("in: T")
    .Output("out: Tout")
    .Attr("T: {complex64, complex128} = DT_COMPLEX64")
    .Attr("Tout: {float, double} = DT_FLOAT");
```
and specified corresponding `Tout` constraints when registering the kernels.

The problem is that the auto-generated Python op will default to `float32` for the output.
(It also turns `Tout` into an optional argument).
I'd like to express "If `T==complex128`, then `Tout==float64`" somehow.

The only way of doing it that I could come up with is by writing a Python wrapper that essentially does
```python
def real(in):
    if in.dtype == tf.complex64:
        Tout = tf.float32
    elif in.dtype == tf.complex128:
        Tout = tf.float64
    return generated_real(in, Tout=Tout)
```

Would that be an acceptable solution, or is there a better one?

**Comment by mrry** [comment]
This sounds like it might have consequences for backwards compatibility. @girving and @josh11b are our resident experts on that.

**Comment by girving** [comment]
Checking with Josh.  I think we may need an extra feature.

**Comment by girving** [comment]
@josh11b: In a perfect world the op spec would say you can't take the real part of a `complex128` and get a `float32`.  Reasonable to just ban that by not registering the kernels?

@ibab: If so, your solution is fine.  I'd change it to `Tout=in.dtype.real_dtype`, but otherwise good.  There will be no backwards compatibility issues since both defaults are the old values.

**Comment by sjperkins** [comment]
@ibab @girving I believe [numexpr](https://github.com/pydata/numexpr) has to consider similar issues when dealing with conversion between between float32, float64, complex64 and complex128. A contributor suggested the use of a casting table, https://github.com/pydata/numexpr/pull/181 may provide more insight.

**Comment by josh11b** [comment]
I recommend writing a Python wrapper that sets Tout based on the input type.  We don't have a better mechanism than that at the moment.

**Comment by girving** [comment]
+1 to @josh11b.  @sjperkins: Since this can easily be handled at the Python wrapper level as @ibab described, we'd like to avoid complicated the low level GraphDef structure.
