### ISSUE TITLE
Anyway to save the session as an object but not a file?

### ISSUE THREAD

**Issue by zhang8473** [tensorflow/tensorflow#1518]
Hi,

I know that the tensorflow can save all variables into a file as a checkpoint
Is there anyway to save the tensor flow session into an object? like
a=Queue()
a.put( sess.status({%variables%}) )  #or maybe a.put( tf.train.status({%variables%}) )

So when I want to restore a session status. I just do a.get()

Is that possible?

Thank you.

**Comment by mrry** [comment]
I'm not sure what semantics you're suggesting for `sess.status(...)` or `tf.train.status(...)`. If you're within the same Python process, you can treat a `tf.Session` like any other object.

A `tf.Session` is not serializable, but you can use the `tf.MetaGraphDef` protocol buffer, along with a checkpoint file, to represent an entire model.

**Comment by zhang8473** [comment]
I understand that tf.Session is as any other object. Maybe I did not explain my question clearly.

session_at_step1=tf.session().????
tf.session().run(...some feeds....)
session_at_step2=tf.session().????

In this case, the object will be changed. I mean, is there any way (a function at ????) to let session_at_step1 be different with session_at_step2?

**Comment by mrry** [comment]
I think the answer is "probably no," but I'm still unclear on what you want the behavior of `????` to be. If you describe a high-level use case, we would consider a feature request.

**Comment by zhang8473** [comment]
I've updated the question and made it clear. I mean, instead of having a handle(pointer) to the session, if there is anyway to copy the session.

**Comment by mrry** [comment]
Ah, ok. Right now there is no way to copy an entire session, and the best way to do what you're asking about is to use the `tf.train.Saver` to write out a `MetaGraphDef` proto, and import that into another session using `tf.train.import_meta_graph()`. This is still quite a new feature, but you can look at [the relevant tests](https://github.com/tensorflow/tensorflow/blob/df2ea2c8fb6fc2a653843ec521adb52305f1679f/tensorflow/python/training/saver_test.py#L762) to see an example of how it's used. It *does* give you the ability to restore an entire graph and resume training etc.

If there is any improved tooling you'd like to see around this format, please let us know in a feature request!
