### ISSUE TITLE
[XLA] OSX tfcompile compile failure in ../llvm_ir/kernel_support_library.cc 

### ISSUE THREAD

**Issue by powderluv** [tensorflow/tensorflow#15196]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.13.2 
- **TensorFlow installed from (source or binary)**: Source 
- **TensorFlow version (use command below)**: Top of Master (34bcd09c5fd4f6435517a499987b7e5044c8f2c0) 
- **Python version**: 
- **Bazel version (if compiling from source)**:   0.7.0
- **GCC/Compiler version (if compiling from source)**: Apple LLVM version 9.0.0 (clang-900.0.39.2)
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: 

bazel build tensorflow/compiler/aot/tfcompile

### Describe the problem
Compiler error when compiling tfcompile on OSX. This was introduced by @sanjoy  Commit:
https://github.com/tensorflow/tensorflow/commit/c572bc4fd7c73f4b8014ae43cdf9da5b99592f59

You will need this PR to be able to fix other compile issues on OSX. https://github.com/tensorflow/tensorflow/pull/14893

ERROR: /Users/tfninja/github/tensorflow/tensorflow/compiler/xla/service/llvm_ir/BUILD:171:1: C++ compilation of rule '//tensorflow/compiler/xla/service/llvm_ir:kernel_support_library' failed (Exit 1).
tensorflow/compiler/xla/service/llvm_ir/kernel_support_library.cc:99:5: error: no matching function for call to 'transform'
    std::transform(function->arg_begin(), function->arg_end(),
    ^~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:1922:1: note: candidate template ignored: couldn't infer template argument '_UnaryOperation'
transform(_InputIterator __first, _InputIterator __last, _OutputIterator __result, _UnaryOperation __op)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:1932:1: note: candidate function template not viable: requires 5 arguments, but 4 were provided
transform(_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2,
^
1 error generated.
Target //tensorflow/compiler/aot:tfcompile failed to build

### Source code / logs

The issue seems to be with this line of code in which works on Linux but fails on OSX/Clang tensorflow/compiler/xla/service/llvm_ir/kernel_support_library.cc

```
+    std::transform(function->arg_begin(), function->arg_end(),
+                   std::back_inserter(arg_values), std::addressof<llvm::Value>);
```

**Comment by darksipu** [comment]
Same issue here, when trying to compile the pip_build_package as a target

Trying to build from source on OS X Sierra 10.12.6, following the exact instructions on the Tensorflow website. Not trying to compile for GPU, only for CPU

**Comment by sanjoy** [comment]
Do you mind verifying that replacing the `std::transform` with a for loop works on OSX and send a PR?  Alternatively, let me know that it worked, and I'll fix it internally and the change will get upstreamed in the next sync.

**Comment by darksipu** [comment]
In the end it worked by just building with the normal:

`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

but during the `./configure`, I had to select **No** for the following (_Yes_ for the ones not mentioned):

Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)?
Do you wish to build TensorFlow with VERBS support?
Do you wish to build TensorFlow with OpenCL support?
Do you wish to build TensorFlow with CUDA support?
Do you wish to build TensorFlow with MPI support?

**Comment by powderluv** [comment]
@drpngx is there a fix committed ? @darsipu above just disabled XLA so it would compile

**Comment by powderluv** [comment]
@sanjoy as requested I have a PR up at https://github.com/tensorflow/tensorflow/pull/15229. I can't reopen this bug so will move discussion to the PR.
