### ISSUE TITLE
Feature request: automatically pick all defaults in ./configure

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#15207]
Everytime a new configuration option is added my CI halts on the ./configure step as it's prompted for input. Instead of setting each flag could we have some `USE_DEFAULTS=1 ./configure` flag instead?

I assume the intention is to slowly move away from the shell script to something better (hence configure.py, I wager) but for now, when testing projects with the master release it would be very useful to be able to just pick all default options for the WORKSPACE without knowing about them.

**Comment by facaiy** [comment]
If you use mac, try ˋyes "" | ./configure ˋ

**Comment by carlthome** [comment]
Haha, that's a sweet trick. Thanks!

**Comment by reedwm** [comment]
@yifeif although the `yes "" | ./configure` trick works, do you think its worth adding a USE_DEFAULTS flag/env var?

**Comment by yifeif** [comment]
I think it's easier to find out about the `yes "" | ./configure` trick than a new flag :). Closing this issue for now.

**Comment by bjarthur** [comment]
does it work on all platforms?
