### ISSUE TITLE
compile error with config sycl

### ISSUE THREAD

**Issue by huoyushi** [tensorflow/tensorflow#15204]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.4,the latest version I git from tensorflow
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**:0.8.1
- **GCC/Compiler version (if compiling from source)**:5.4.0
- **CUDA/cuDNN version**:no
- **GPU model and memory**:no
- **Exact command to reproduce**:bazel build -c opt --config=sycl //tensorflow/tools/pip_package:build_pip_package

##something else
OpenCl version:1.2
computecpp path:    /usr/local/computecpp  version 0.5.0

computecpp_info:
Device Info:
Discovered 1 devices matching:
  platform    : <any>
  device type : <any>
--------------------------------------------------------------------------------
Device 0:
  Device is supported                     : UNTESTED - Vendor not tested on this OS
  CL_DEVICE_NAME                          : Hainan
  CL_DEVICE_VENDOR                        : Advanced Micro Devices, Inc.
  CL_DRIVER_VERSION                       : 2482.3
  CL_DEVICE_TYPE                          : CL_DEVICE_TYPE_GPU 

clinfo:
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.0 AMD-APP (2482.3)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     Hainan
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 AMD-APP (2482.3)
  Driver Version                                  2482.3
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Board Name (AMD)                         AMD Radeon HD 8500M
  Device Topology (AMD)                           PCI-E, 04:00.0
  Max compute units                               4
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                16
  SIMD instruction width (AMD)                    1
  Max clock frequency                             850MHz
  Graphics IP (AMD)                               6.0
  Device Partition                                (core)
    Max number of sub-devices                     4
    Supported partition types                     none specified
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              64
  Wavefront width (AMD)                           64
  Preferred / native vector sizes                 
    char                                                 4 / 4       
    short                                                2 / 2       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    32, Little-Endian
  Global memory size                              2140311552 (1.993GiB)
  Global free memory (AMD)                        <printDeviceInfo:68: get number of CL_DEVICE_GLOBAL_FREE_MEMORY_AMD : error -33>
  Global memory channels (AMD)                    2
  Global memory banks per channel (AMD)           8
  Global memory bank width (AMD)                  256 bytes
  Error Correction support                        No
  Max memory allocation                           1591773593 (1.482GiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       2048 bits (256 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        16384
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   256 bytes
    Pitch alignment for 2D image buffers          256 bytes
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Local memory syze per CU (AMD)                  65536 (64KiB)
  Local memory banks (AMD)                        32
  Max constant buffer size                        65536 (64KiB)
  Max number of constant args                     8
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Profiling timer offset since Epoch (AMD)        1512650783761772748ns (Thu Dec  7 20:46:23 2017)
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Thread trace supported (AMD)                  No
    SPIR versions                                 1.2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  AMD Accelerated Parallel Processing
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [AMD]
  clCreateContext(NULL, ...) [default]            Success [AMD]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   Hainan
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   Hainan

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.8
  ICD loader Profile                              OpenCL 1.2
	NOTE:	your OpenCL library declares to support OpenCL 1.2,
		but it seems to support up to OpenCL 2.1 too.

### Describe the problem
I want Compile With sycl config  with the command 
bazel build -c opt --config=sycl //tensorflow/tools/pip_package:build_pip_package
 but  unfortunately get the error 

Illegal ambiguous match on configurable attribute "deps" in @local_config_sycl//sycl:sycl:
@local_config_sycl//sycl:using_sycl_ccpp
@local_config_sycl//sycl:using_sycl_trisycl
Multiple matches are not allowed unless one is unambiguously more specialized.

I did not know what casue this compile error. Please Help

**Comment by drpngx** [comment]
Sorry, opencl is not fully supported.

**Comment by mirh** [comment]
> Illegal ambiguous match on configurable attribute "deps"

That doesn't [seem](https://github.com/tensorflow/tensorflow/issues/11807) opencl \*specific\*

**Comment by huoyushi** [comment]
@mirh ,yeah, I am not familiar with bazel  tools ,But I guess that some Configuration may not be appropriate because I find that  in /third_party/sycl/sycl/BUILD.tpl  some configuration confuse me.
In that file
config_setting(
    name = "using_sycl_ccpp",
    define_values = {
        "using_sycl": "true",
        "using_trisycl": "false",
    },
)

config_setting(
    name = "using_sycl_trisycl",
    define_values = {
        "using_sycl": "true",
        "using_trisycl": "false",
    },
)
that the setting named "using_sycl_ccpp"  whosed define_values are same as "using_sycl_trisycl",,there must be some conflict in cuda's configruation cause the same error。but It's difficault for me to handle the problem . Just wait for someone is good at bazel to handle the problem.

**Comment by mirh** [comment]
The thing build fine for me with [this tree](https://github.com/lukeiwanski/tensorflow/tree/dev/amd_gpu)
Can you check ?

**Comment by huoyushi** [comment]
Thanks for your guide ,I will try this tree and reply the result.

发自贺敏琪

在 2017年12月19日，上午12:06，mirh <notifications@github.com<mailto:notifications@github.com>> 写道：


The thing build fine for me with this tree<https://github.com/lukeiwanski/tensorflow/tree/dev/amd_gpu>
Can you check ?

**Comment by lissyx** [comment]
I ran into a similar issue but I could get a successfull SYCL-based build once switching back to ComputeCpp 0.4.0 (building against TensorFlow ~r1.4). So you might want to give that a try as well, if that is something possible for you.

**Comment by huoyushi** [comment]
Thanks, I try the branch amd_gpu It can build. But I Have got another error about 

this rule is missing dependency declarations for the following files included by 'external/protobuf_archive/python/google/protobuf/internal/api_implementation.cc'

the command is 
bazel build --config=opt --config=sycl --verbose_failures //tensorflow/tools/pip_package:build_pip_package 2>&1 | tee ~/tfbuild.log

can you help me with  @this@mirh

**Comment by mirh** [comment]
For as much as I know, it might have been due to one of the plenty of updates they made in this last couple of days. 
Maybe.. Try [this](https://github.com/lukeiwanski/tensorflow/tree/6631d9c054c9b0531e8f9fd89031bb7f0c4612e1) revision for starters?

**Comment by devkicks** [comment]
I am getting this issue when compiling with Intel GPU. Is there a solution to this anywhere?

**Comment by mirh** [comment]
[This is the branch](https://github.com/lukeiwanski/tensorflow/tree/dev/amd_gpu).

**Comment by mirh** [comment]
[Found the actual cause](https://github.com/tensorflow/tensorflow/blob/d0a5d885d61b837018cb931a4d577289acc826fc/third_party/sycl/sycl/build_defs.bzl.tpl#L13)
Somebody screwed kinda hard. 

@huoyushi can you reopen?

**Comment by devkicks** [comment]
@mirh  were you able to fix this issue?

**Comment by mirh** [comment]
This specific one, yes. 
You just need to remove the trisycl line. 
OTOH normal tf is just rotten to the core for sycl. 

As I said 2 comments above, use Luke's branch.
