### ISSUE TITLE
stupid question but please help me to answer this

### ISSUE THREAD

**Issue by 32nguyen** [tensorflow/tensorflow#15218]
I have a problem with parallel computing. I know that CUDA or pyCUDA can do such thing like 3D convolution in parallel. 
I think about using tensorflow GPU by calling tf.nn.conv3d(input, filter), does it uses build in functions in CUDA to operate 3D convolution with parallel computing or there are somethings else? 
I am not familiar with C++ or even with pyCuda I am not sure how to implement 3D convolution with it.

Same question with all type of other implement with tensorflow GPU.

Bests,

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
