### ISSUE TITLE
ResidualWrapper and HighwayWrapper require rnn inputs' last dimension to be equal to num_units

### ISSUE THREAD

**Issue by MtDersvan** [tensorflow/tensorflow#15220]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: -
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:  v1.4.0-rc1-11-g130a514 1.4.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: -
- **GCC/Compiler version (if compiling from source)**: -
- **CUDA/cuDNN version**: - 
- **GPU model and memory**: - 
- **Exact command to reproduce**:
~~~python
from tensorflow.contrib import rnn as rnn_cell
from tensorflow.python.ops import rnn
import tensorflow as tf

rnn_inputs = tf.random_uniform([10, 10, 10])
cell = rnn_cell.LSTMCell(128)
cell = rnn_cell.HighwayWrapper(cell) # rnn_cell.ResidualWrapper(cell)
_, _ = rnn.dynamic_rnn(cell, rnn_inputs, dtype=tf.float32)
~~~

### Problem
`rnn_cell.ResidualWrapper` and `rnn_cell.HighwayWrapper` throw an exception when rnn inputs' last dimension is not equal to `num_units`. Without wrappers, the input tensor can be different from `num_units`.
What's the reason for the different behaviour? Is it intended?

### Full Traceback
https://pastebin.com/YvTb3WM3

**Comment by ebrevdo** [comment]
The ResidualWrapper adds the inputs to the outputs of the RNNCell it wraps.  How do you add if the input and output depths are different?

**Comment by MtDersvan** [comment]
Yeah, I guess there is not much that can be done without adding more parameters. I usually just add a linear transformation that converts depth into num_units. Sorry for bothering.
