### ISSUE TITLE
tensorflow-gpu on mac

### ISSUE THREAD

**Issue by pengyu** [tensorflow/tensorflow#15230]
I can use the following to install tensorflow on mac.

Python 2

~~~
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.4.0-py2-none-any.whl
~~~

Python 3

~~~
pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.4.0-py3-none-any.whl
~~~

But I don't find the correponding files for tensorflow-gpu. Can it be generated and posted over there? Thanks.

**Comment by asimshankar** [comment]
As per: https://www.tensorflow.org/install/install_mac - GPUs-on-Macs are not supported by the TensorFlow team (since after version 1.2).

Some more discussion is here: https://groups.google.com/a/tensorflow.org/d/msg/discuss/BbnxAK9Rc54/XeTIG7JsBQAJ
