### ISSUE TITLE
No gradient defined for op: Pow

### ISSUE THREAD

**Issue by cesarsouza** [tensorflow/tensorflow#15239]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 x64
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.4
- **Bazel version**: N/A
- **Python version**: None
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**: -

### Describe the problem
It seems there is no gradient defined for the Pow operation in the C++ API.

I am actually transferring this issue from https://github.com/migueldeicaza/TensorFlowSharp/issues/187. Similar to the case of Select (#14845), it seems there is also no gradient for the Pow operation in the C++ API.

**Comment by KingRando95** [comment]
TST: add test case
ENH: add pow grad

**Comment by facaiy** [comment]
@cesarsouza I have created a PR to resolve the issue.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version

**Comment by cesarsouza** [comment]
Huge thanks @facaiy! Also I've just noticed that I used the wrong title for the issue, probably it seemed confusing at first. Sorry about it, and thanks again for the extremely fast PR!

**Comment by basejn** [comment]
Is this issue fixed now. Because i get the same error with 1.9

**Comment by facaiy** [comment]
The PR has been merged, so I think the issue is fixed. Could you give an example?
