### ISSUE TITLE
Install new TensorFlow via anaconda, but failed

### ISSUE THREAD

**Issue by masa-matsu** [tensorflow/tensorflow#15232]
Hello,

When I tried to install TensorFlow via anaconda.
I`ve searched the suitable cite to submit the issue, but failed to find out it.
If this is not sorry for it and advice me.

The target os is 'windows 10', and via anaconda 5.0.1 For Windows (Python 3.6 version 64bit).
After intall anaconda, from my terminal 'cmd.exe',
$ conda create -n tensorflow python=3.6
but received an error message.

But from 'Anaconda Prompt' below 'Anaconda3' of 'start button',it works correctly.

Thus I recommend to include the following description,
start 'Anaconda Prompt' below 'Anaconda3' of 'start button' between the steps.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by quaeler** [comment]
The step failing here, as you write above, does not involve TensorFlow - so this issue should probably be closed.

**Comment by masa-matsu** [comment]
Sorry for bothering you. 
I understand the issue template, but my post is not suitable for here.
Thanks.
