### ISSUE TITLE
Add kappa coefficient as a new metric?

### ISSUE THREAD

**Issue by hanfeisun** [tensorflow/tensorflow#15285]
Currently tensorflow supports using accuracy as a metric for model's performance.

However, for unbalanced datasets, kappa coefficient (https://www.wikiwand.com/en/Cohen%27s_kappa#) is a commonly used metric. Would it be possible to add this one in the model.metrics?

**Comment by angersson** [comment]
@roumposg, what do you think about this?

**Comment by roumposg** [comment]
SG, but I don't think we have the cycles to do it soon. We welcome contributions, though! I would add it to tf.contrib.metrics.

**Comment by facaiy** [comment]
I'd like to work on it.

**Comment by facaiy** [comment]
@hanfeisun Hi, I added a very rudimentary implementation of `cohen_kappa` in PR #15443. It is pretty rough as am not sure about the api. Please take a look and comment. Thanks.
