### ISSUE TITLE
tensorflow multigpu with dataset api is not converging

### ISSUE THREAD

**Issue by creativesh** [tensorflow/tensorflow#15318]
I am trying to train a resNet50  on multi_gpus,
I have used 
[https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py)](url)

and I have added tensorflow Dataset input pipeline to the link code
But after some steps loss is some value and does not changes any more!(value =0.693147 always)

I have tested this network with dataset API on single gpu,and worked fine.
Im sure something is wrong with my data feeding,because when I feed a simple random nd_array,it converges!!!!!

I have tested my tfrecord file,it was OK .
but I dont know the problem.

I use
ubuntu 16.04,

tensorflow 1.4,

python 2.7.12,

gtx 1080 Gpus

this is all my train code:

[github.txt](https://github.com/tensorflow/tensorflow/files/1552082/github.txt)

**Comment by maxfiedler** [comment]
Quick hint. You need to set reuse to false for gpu:0 and to true for all others

**Comment by creativesh** [comment]
@maxfiedler
I didnt understand you,can you explain with code ?

**Comment by creativesh** [comment]
@maxfiedler
thanks-I did it,but didnt solve the problem

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
