### ISSUE TITLE
iOS build_all_ios_ssd.sh 'double-conversion/double-conversion.h' file not found

### ISSUE THREAD

**Issue by anonym24** [tensorflow/tensorflow#15312]
iOS `build_all_ios_ssd.sh` `'double-conversion/double-conversion.h' file not found`

```

export TF_ROOT=$(~/tensorflow-master)


cd ~/tensorflow_ios_detector/config
bash config.sh

export TF_ROOT=~/tensorflow-master
cd $TF_ROOT
tensorflow/contrib/makefile/build_all_ios_ssd.sh

gcc --std=c++11 -I. -I/Users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/ -I/Users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/eigen -I/Users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/gemmlowp -I/Users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/nsync/public -I/Users/admin/tensorflow-master/tensorflow/contrib/makefile/downloads/fft2d -I/Users/admin/tensorflow-master/tensorflow/contrib/makefile/gen/host_obj/ -I/Users/admin/tensorflow-master/tensorflow/contrib/makefile/gen/protobuf-host/include -I/usr/local/include -c tensorflow/core/lib/random/simple_philox.cc -o /Users/admin/tensorflow-master/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/lib/random/simple_philox.o
tensorflow/core/lib/strings/numbers.cc:26:10: fatal error: 
      'double-conversion/double-conversion.h' file not found
#include "double-conversion/double-conversion.h"
         ^
1 error generated.
make: *** [/Users/admin/tensorflow-master/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/lib/strings/numbers.o] Error 1
make: *** Waiting for unfinished jobs....
+ '[' 2 -ne 0 ']'
+ echo 'arm64 compilation failed.'
arm64 compilation failed.
+ exit 1
Mac-Admin:tensorflow-master admin$ 

```
but script downloaded `double-conversion` in `downloads` folder located at `tensorflow/contrib/makefile`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by anonym24** [comment]
OS Platform and Distribution - Mac OSX 10.11.6
TensorFlow installed from - native pip https://www.tensorflow.org/install/install_mac
TensorFlow version - 1.4.0
Bazel version - not used, not installed
CUDA/cuDNN version - not used, not installed
GPU model and memory - not used, 4gb
Exact command to reproduce - `tensorflow/contrib/makefile/build_all_ios_ssd.sh`

**Comment by anonym24** [comment]
forgot `tensorflow/contrib/makefile/download_dependencies.sh`
solved
