### ISSUE TITLE
why the tensorflow run slower on gpu than on cpu

### ISSUE THREAD

**Issue by MisayaZ** [tensorflow/tensorflow#1532]
The tensorflow should run faster on gpu than on cpu , however, I got the opposite result. The time cost when running on gpu is longer than on cpu.The code is as below:

```python
    with tf.device('/cpu:0'):
        local3_value = np.load("local3.npy")
    with tf.variable_scope('local4') as scope:
        weights4 = tf.get_variable('weights',[384,192])
        biases4 = tf.get_variable('biases',[192])
        local4 = tf.nn.relu(tf.matmul(local3_value, weights4)+biases4, name = scope.name)

    saver = tf.train.Saver()

    with tf.Session(config=tf.ConfigProto(log_device_placement=True))as sess:
        saver.restore(sess, "/tmp/cifar10_train/model.ckpt-27000")
        start_time  = time.time()
        predictions = sess.run(local4)
        duration = time.time() - start_time
        print(duration)
```

The variables such as weights4 and biases4 are restored from a trained model.

**Comment by mrry** [comment]
This looks like a very small layer, and you're only running it once. I suspect the cost is dominated by session setup costs and transferring the constant data to the GPU.

Try running `predictions = sess.run(local4)` in a loop to understand the average step time in the limit. This will give you a better understanding of whether some code is more efficient on CPU or GPU.

**Comment by MisayaZ** [comment]
@mrry  I think It makes sense, thank you.
I also got another problem, the first code is as below:
`with tf.device('/gpu:0'):
    local3_value = np.load("local3.npy")
    weights4 = np.load("weights4.npy")
    biases4 = np.load("biases4.npy")
    weights3 = np.load("weights4.npy")
    biases3 = np.load("biases4.npy")
    with tf.variable_scope('local3') as scope:
        local3 = tf.matmul(local3_value, weights3)
    with tf.variable_scope('local4') as scope:
        local4 = tf.nn.relu(tf.matmul(local3_value, weights4)+biases4, name = scope.name)

   
    with tf.Session(config=tf.ConfigProto(log_device_placement=True))as sess:
        sess.run(local3)
        start_time  = time.time()
        predictions = sess.run(local4)
        duration = time.time() - start_time
        print(duration)`
 The duration is 0.244572162628

The second code is as below:
`with tf.device('/gpu:0'):
    local3_value = np.load("local3.npy")
    weights4 = np.load("weights4.npy")
    biases4 = np.load("biases4.npy")
    weights3 = np.load("weights4.npy")
    biases3 = np.load("biases4.npy")
    with tf.variable_scope('local3') as scope:
        local3 = tf.nn.softplus(weights3)
    with tf.variable_scope('local4') as scope:
        local4 = tf.nn.relu(tf.matmul(local3_value, weights4)+biases4, name = scope.name)

   
    with tf.Session(config=tf.ConfigProto(log_device_placement=True))as sess:
        sess.run(local3)
        start_time  = time.time()
        predictions = sess.run(local4)
        duration = time.time() - start_time
        print(duration)`
The duration is 0.0679910182953

The only difference between these two codes is the local3 layer. Why the graph of local3 affects the cost of graph of loca4? These two graphs do not have any relationship.
