### ISSUE TITLE
Allow tf.Estimator.evaluate() to return summary protos / add tooling to produce useful eval image summaries

### ISSUE THREAD

**Issue by Rikorose** [tensorflow/tensorflow#15332]
Related to #14042.

`tf.Estimator.train()` writes a summary of all defined summaries (scalar, img) in the given `model_fn` when calling [MonitoredTrainingSession](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/estimator.py#L801) ([here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/monitored_session.py#L366)).

`tf.Estimator.evaluate()` does not write summaries defined somewhere in the `model_fn`. A workaround is defining `SummarySaverHook` inside the `model_fn`, which I think is not ideal since the Estimator has all the relevant information for saving summaries (steps, save directory, etc.).

A possible solution would be adding a `SummarySaverHook` during evaluation, (e.g. [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/evaluation.py#L206)) or create a new function `MonitoredEvaluationSession()` in [monitored_session.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/monitored_session.py) that creates such a hook.

cc @ispirmustafa @martinwicke

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Rikorose** [comment]
Thanks for answering. I specifically care about image summaries. I want to compare my results during training with the results of the evaluation dataset. Right now I create a `SummaryWriterHook` in my `model_fn`. Is this the supposed way?

**Comment by martinwicke** [comment]
If you were to simply summarize in the eval loop, you'll just get the image for the last batch. Is that what you want? I've heard from some people that "I just want some images, I don't care which". 

If you want just some random images from some batch, you can create an image summary, and return it in the eval_dict. It should then be summarized and available along with the other metrics (@xiejw I don't recall whether that fix is in, do you remember?). 

If you want all images, or a significant set of them, you should tile, say, the last n*n into a collage, and summarize that. We don't have tooling to do that, but I think it would be good to add such tooling, either as a custom plugin to TensorBoard (showing an "album" of images) or some TF summarization tooling allowing you to make a set of images into a tiled bugger image. A feature request for such tooling would be reasonable, though we'd rely on the community for implementation.

**Comment by xiejw** [comment]
for tf.estimator.Estimator, as far as i know, the fix is not in.

**Comment by martinwicke** [comment]
Then that should be added to the FR. @ispirmustafa unless you think otherwise.

I'll reopen this. @Rikorose I changed the title to reflect this. This FR should possibly be split in those two parts, but the summary fix is easy.

**Comment by iamtodor** [comment]
Here is the code that tested with TF 1.9
```
summary_hook = tf.train.SummarySaverHook(save_steps=save_steps,
                                                 output_dir='summary',
                                                 summary_op=tf.summary.merge_all)

eval_results = self._estimator.evaluate(input_fn=self.validation_dataset, hooks=[summary_hook])
```

**Comment by dumorgan** [comment]
Is it possible to do this inside model_fn which is passed to tf.estimator.train_and_evaluate and have the returned EstimatorSpec receive the SummarySaverHook?

**Comment by martinwicke** [comment]
Yes, set the evaluation_hooks field.

**Comment by martinwicke** [comment]
I will close this issue -- I believe @iamtodor's solution works well. Please reopen a new issue if there's a significant use case that is not covered.

**Comment by patzm** [comment]
I don't understand how @iamtodor's solution could work. I assume that the `summary_op` is only assigned a _function_ and not the actual merge operator of all summaries. If I try this locally, I in fact get an error for that:
```
TypeError: Fetch argument <function merge_all at 0x7fda81fb5158> has invalid
type <class 'function'>, must be a string or Tensor. (Can not convert a 
function into a Tensor or Operation.)
```
If I _call_ `tf.summary.merge_all()` when creating the `SummarySaverHook` before the call to `estimator.evaluate(...)`, then the Graph has not been built. `evaluate()` builds graph by calling the `model_fn`. So how is this supposed to work? 🤔
The only way I see is to implement a custom `SummarySaverHook`, that initializes the `summary_op` in the call to `begin()`, at which point the graph is already built. It could be as simple as
```python
class EvalSummarySaverHook(tf.train.SummarySaverHook):
    def __init__(self, output_dir=None, summary_writer=None):
        super(EvalSummarySaverHook, self).__init__(
            save_steps=1,
            output_dir=output_dir,
            summary_writer=summary_writer,
            summary_op=True)
        self._request_summary = None

    def begin(self):
        super(EvalSummarySaverHook, self).begin()
        self._summary_op = tf.summary.merge_all()
        self._request_summary = True

    def before_run(self, run_context):
        requests = {"global_step": self._global_step_tensor}
        if self._request_summary:
            if self._get_summary_op() is not None:
                requests["summary"] = self._get_summary_op()

        return tf.train.SessionRunArgs(requests)

    def after_run(self, run_context, run_values):
        super(EvalSummarySaverHook, self).after_run(run_context, run_values)
        self._request_summary = False
```
This Hook saves the very first batch of the eval run as a summary. Saving some aggregate over all batches in an eval session is somewhat tricky as already outlined earlier in this discussion.

**Comment by pwais** [comment]
*bump* @martinwicke  It seems people are surprised that evaluation mode does not save expected summaries, yet train mode does.  Could you please re-open this issue officially?  Or document the decision as to why evaluation neglected to record summaries?

**Comment by martinwicke** [comment]
Sorry, fell off my radar. It looks to me like @patzm is correct, you need the graph to make the merg_all. I can reopen.
