### ISSUE TITLE
opencv cannot read frame from video with tensorflow

### ISSUE THREAD

**Issue by kxhit** [tensorflow/tensorflow#15339]
I am using tensorflow r1.4 and opencv3.1 in ubuntu14.04.
When I include #include <tensorflow/core/public/session.h> or 
#include "tensorflow/cc/ops/standard_ops.h" I cannot read images from cv::VideoCapture adn I got empty mat. When I didn't include these tensorflow headers, I can read frame successfully. Anyone could help me? Thanks a lot!!!
I noticed other issues like [#1924](https://github.com/tensorflow/tensorflow/issues/1924?from=singlemessage) [#6496](https://github.com/tensorflow/tensorflow/issues/6496) but got no idea.

Here is my cpp file:
#include <tensorflow/core/platform/env.h>
#include <tensorflow/core/public/session.h>
#include "tensorflow/cc/ops/standard_ops.h"
#include <opencv2/opencv.hpp>
#include <iostream>
using namespace std;
using namespace tensorflow;

int main()
{
cv::VideoCapture cap;
if(!cap.open("/home/kx/project/RM-dataset/01.avi")){
std::cout<<"cannot open video "<<std::endl;
}
cv::Mat frame;
while(1){
cap>>frame;
if(frame.empty()){
std::cout<<"no frame"<<std::endl;
continue;
}
cv::imshow("frame",frame);
cv::waitKey(0);
}
return 0;
}

my cmake file:

cmake_minimum_required (VERSION 2.8)
project (tf_example)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -std=c++11 -W")
find_package(OpenCV 3.1.0 REQUIRED)
include_directories(
/home/kx/something/tensorflow-r1.4
/home/kx/something/tensorflow-r1.4/tensorflow/bazel-genfiles
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/gen/protobuf/include
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/gen/host_obj
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/gen/proto
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/downloads/nsync/public
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/downloads/eigen
/home/kx/something/tensorflow-r1.4/bazel-out/local-py3-opt/genfiles
${OPENCV_INCLUDE_DIRS}
)

add_executable(tf_test tf_test.cpp)
target_link_libraries(tf_test
/home/kx/something/tensorflow-r1.4/bazel-bin/tensorflow/libtensorflow_cc.so
/home/kx/something/tensorflow-r1.4/bazel-bin/tensorflow/libtensorflow_framework.so
${OpenCV_LIBS}
)

The results:
no frame

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by mrlzla** [comment]
I think this is a bug.
