### ISSUE TITLE
Using wrong location for x86_64 android build

### ISSUE THREAD

**Issue by sujitpoudel123** [tensorflow/tensorflow#15345]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
A: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
A: OSX 10.13.1
- **TensorFlow installed from (source or binary)**:
A: Source
- **TensorFlow version (use command below)**:
A: 1.4.1
- **Python version**: 
A: 2.7
- **Bazel version (if compiling from source)**:
A: 0.8
- **GCC/Compiler version (if compiling from source)**:
A:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:
`make -f tensorflow/contrib/makefile/Makefile TARGET=ANDROID ANDROID_ARCH=x86_64`

### Describe the problem
Android x86_64 build fails with Makefile using make -f tensorflow/contrib/makefile/Makefile TARGET=ANDROID ANDROID_ARCH=x86_64 because it cannot find the binary `x86-64-linux-android-g++`

It can be fixed by changing the `tensorflow/contrib/makefile/Makefile` at line 303 from 
`BIN_PREFIX := x86-64-linux-android` to
`BIN_PREFIX := x86_64-linux-android`

**Comment by angersson** [comment]
I've prepped a PR for this.

**Comment by angersson** [comment]
#15346 fixes this!
