### ISSUE TITLE
Windows Environment and TF 1.4.1 - Unavailable through PyPI

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#15342]
Hello dear Tensorflowers,

When running the following code `pip install tensorflow==1.4.1`, I obtain the following error:

```
Could not find a version that satisfies the requirement tensorflow==1.4.1 (from versions: 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0)
No matching distribution found for tensorflow==1.4.1
```

This error seem logical because the _wheel_ file does not exist for the windows distribution: 

- TF 1.4.1 - No Windows Compiled Library: https://pypi.python.org/pypi/tensorflow/1.4.1
- TF 1.4.0 - Windows Compiled Library is present: https://pypi.python.org/pypi/tensorflow/1.4.0

Is the support for the windows platform dropped ? Or maybe some compilation pipeline broke somewhere.

Thanks for your help,

Jonathan

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gunan** [comment]
We intentionally did not build 1.4.1 windows binaries, as the 1.4.1 only includes a fix for GCS and CloudML.
Our windows builds would have delayed the release, and we do not even include the GCS support on windows binaries anyway.
Is there a reason why you needed the 1.4.1 binary on windows?

**Comment by DEKHTIARJonathan** [comment]
Project dependencies are maintained for both platforms (Windows & Linux), 
I would prefer using the same version on both platform, I understand the reasons why it wasn't done.
I will wait for the next release, do you have any time frame for it in mind ?

**Comment by gunan** [comment]
Our goal is to push it before the end of this month, but we are blocked on some patches on other projects.

**Comment by DEKHTIARJonathan** [comment]
No problem, thanks for the answer.

**Comment by Fida1316** [comment]
same problem how can reslove it.? the project requirment is tensorflow 1.4.1
