### ISSUE TITLE
Automatic node placement (allocating graph nodes to multiple devices) feature  in distributed tensorflow

### ISSUE THREAD

**Issue by jyoungrok** [tensorflow/tensorflow#15365]
I read tensorflow white papaer and found node placement which allocates graph nodes to devices without manual configuration.

https://www.reddit.com/r/MachineLearning/comments/4n6a0e/distributed_tensorflow_resource_allocation/

This post says this feature was removed because it did not perform well.
However, it was posted a year ago and I think you are still developing this feature.

Is it included in the current version of tensorflow?
If so, what code do i need to see?
If inot, do you plan to add this feature?

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
