### ISSUE TITLE
cannot install with virtualenv python3.6

### ISSUE THREAD

**Issue by XinhaiWang** [tensorflow/tensorflow#15388]
Have I written custom code      No
OS Platform and Distribution .  MacOS 10.13.2
TensorFlow installed from        conda  URL of the TensorFlow Python package
TensorFlow version .                1.4
Bazel version                             N/A
CUDA/cuDNN version              N/A
GPU model and memory          N/A
Exact command to reproduce  I just follow Install with conda, My python was installed with conda, I think maybe that is the problem.

virtualenv --system-site-packages -p python3 ~/tensorflow
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/xinhai/tensorflow/bin/python3.6
Also creating executable in /Users/xinhai/tensorflow/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /Users/xinhai/tensorflow/bin/python3.6 - setuptools pip wheel:
  stringstringstringstringstringstringstringstring
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 5, in <module>
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 28, in <module>
    from string import Template
ImportError: cannot import name 'Template'

...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/xinhai/tensorflow/bin/python3.6 - setuptools pip wheel failed with error code 1

**Comment by quaeler** [comment]
I'm confused as to what here is TensorFlow related. Do you already have TF pip-installed into your system site packages?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by XinhaiWang** [comment]
Have I written custom code No
OS Platform and Distribution . MacOS 10.13.2
TensorFlow installed from conda URL of the TensorFlow Python package
TensorFlow version . 1.4
Bazel version N/A
CUDA/cuDNN version N/A
GPU model and memory N/A
Exact command to reproduce I just follow Install with conda, My python was installed with conda, I think maybe that is the problem.

**Comment by quaeler** [comment]
.... but...
This command you report using and having an issue with
```
virtualenv --system-site-packages -p python3 ~/tensorflow
```
has **nothing** to do with TensorFlow. Why are you reporting this issue here?
