### ISSUE TITLE
Feature request: tf.info to show docstrings in jupyter notebook

### ISSUE THREAD

**Issue by dataplayer12** [tensorflow/tensorflow#15398]
When working with jupyter notebooks, it is really helpful to see the documentation within the notebook. Numpy has a function called `np.info` which takes a numpy function as argument and prints its docstring. For example, np.info(np.mean) prints the docstring for `np.mean`. It would be really helpful to have an equivalent `tf.info` for those of us who work with jupyter notebooks (and who doesn't?).

**Comment by ppwwyyxx** [comment]
![1215-13 20 52](https://user-images.githubusercontent.com/1381301/34060943-ce5ca2fe-e19a-11e7-952e-dd2ed18d9152.png)

**Comment by andydavis1** [comment]
Thanks @ppwwyyxx @dataplayer12 Please reopen if that does not solve your problem.
