### ISSUE TITLE
OS X + GPU NVIDIA nccl dependency missing

### ISSUE THREAD

**Issue by headupinclouds** [tensorflow/tensorflow#15395]
[Comment](https://github.com/tensorflow/tensorflow/pull/14016#discussion_r156704387) migrated to a full issue here.

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OS X 10.12.2 (Any)
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: Master @HEAD
- **Python version**: N/A
- **Bazel version (if compiling from source)**: N/A (CMake)
- **GCC/Compiler version (if compiling from source)**: Xcode 8.3.3 (Any)
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: `cmake -GXcode ...`

### Describe the problem

I'm trying to extend [CMake-Linux support for GPU-build](https://github.com/tensorflow/tensorflow/pull/14016) to finish CMake + OSX testing w/ (NVIDIA) GPU.   I had started with CUDA 8.0 and cuDNN 6.0, but given recent activity here, it seems better to target a recent master branch w/ CUDA 9.0 + cuDNN 7.0.  The OS X CUDA installation does not come with `nccl` (see `find` output below for contents).  NVIDIA has a (login based) `nccl` download for v2.0, but it only has Linux libraries.  I see three other options to support OS X + GPU Builds:

1. https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/nccl (build from bundled source v1.3.5)
2. https://github.com/nvidia/nccl (build from source v1.?)
3. add `option(tensroflow_USE_NCCL "Use NCCL lib" ON)` to make it `nccl` optional (I'm not sure how complicated this is) and update the CMake and source code w/ preprocessor definitions as needed

Shall I add the bundled `nccl` (v1.3.5?) files to the CMake build?  I see notes about migrating to v2.0 in commit comments, which seems to be closed source.  If that's the case, then it may be best to try to make any internal tensorflow `nccl` operations optional in order to support single GPU configurations to start with. 

`find /Developer/NVIDIA/CUDA-9.0/lib -name "*.a"`
```
/Developer/NVIDIA/CUDA-9.0/lib/libcublas_device.a
/Developer/NVIDIA/CUDA-9.0/lib/libcublas_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libcudadevrt.a
/Developer/NVIDIA/CUDA-9.0/lib/libcudart_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libcufft_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libcufftw_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libculibos.a
/Developer/NVIDIA/CUDA-9.0/lib/libcurand_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libcusolver_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libcusparse_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libnppc_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libnppial_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libnppicc_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libnppicom_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libnppidei_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libnppif_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libnppig_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libnppim_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libnppist_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libnppisu_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libnppitc_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libnpps_static.a
/Developer/NVIDIA/CUDA-9.0/lib/libnvgraph_static.a
```

### Source code / logs

N/A

**Comment by angersson** [comment]
We don't officially support OSX + Nvidia, so I'm marking this as community support.

Please feel free to put together a PR!

**Comment by headupinclouds** [comment]
I will take a look.  Do you know which version of nccl is currently required for master?

**Comment by angersson** [comment]
I'm unfamiliar with the OSX build process myself, so I don't know, no.

**Comment by ymodak** [comment]
Closing this issue due to staleness. Please use the latest version of TensorFlow and build again.
Feel free to report any issues you encounter with latest TensorFlow. Thanks!
