### ISSUE TITLE
module 'tensorflow.contrib' has no attribute 'lite'

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [tensorflow/tensorflow#15401]
Hello folks.

Everytime I try to run the example fo TOCO:

```
import tensorflow as tf

img = tf.placeholder(name="img", dtype=tf.float32, shape=(1, 64, 64, 3))
val = img + tf.constant([1., 2., 3.]) + tf.constant([1., 4., 4.])
out = tf.identity(val, name="out")
with tf.Session() as sess:
  tflite_model = tf.contrib.lite.toco_convert(sess.graph_def, [img], [out])
  open("test.tflite", "wb").write(tflite_modeL)
``` 

I get the error: **module 'tensorflow.contrib' has no attribute 'lite'**

OS Platform and Distribution: Mac OS High Sierra
Tensorflow installed from pip version 1.4.1. 
Python version: 2.7.14 and 3.6.3 :: Anaconda custom (64-bit)

The informations about my system are those:

== cat /etc/issue ===============================================
Darwin Leandros-MacBook-Pro.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
Mac OS X 10.13.2

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== uname -a =====================================================
Darwin Leandros-MacBook-Pro.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy (1.13.3)
numpydoc (0.7.0)
protobuf (3.5.0.post1)
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.8)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.3.0
tf.GIT_VERSION = v1.3.0-rc2-20-g0787eee
tf.COMPILER_VERSION = v1.3.0-rc2-20-g0787eee
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 105: nvidia-smi: command not found

Seams like tensorflow lite is not available for reason =/

Sorry if this is not a bug and I am just being dumb about how to make TOCO works.

**Comment by aselle** [comment]
Tensorflow 1.4.1 doesn't contain TensorFlow lite. you need to download the nightly whl to get it.

**Comment by angersson** [comment]
You should be able to install the nightly with `pip install tf_nightly`.

**Comment by leandroBorgesFerreira** [comment]
Oh. So it's not a bug. Thanks for the help!

**Comment by SanthoshMKunthe** [comment]
I am getting TOCO_CONVERT ERROR. . .

    tflite_model=tf.contrib.lite.toco(sess.graph_def,[x],[mxc])

AttributeError: module 'tensorflow.contrib.lite.python.lite' has no attribute 'toco'

//=========================================
import tensorflow  as tf
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as lib

from tensorflow.python.tools import freeze_graph
from tensorflow.python.tools import optimize_for_inference_lib


print(tf.__version__)
data=pd.read_csv('C:\ml\irisInAndroid\iris.data',names=['f1','f2','f3','f4','f5'])

s=np.asarray([1,0,0])
ve=np.asarray([0,1,0])
vi=np.asarray([0,0,1])

data['f5']=data['f5'].map({'Iris-setosa':s,'Iris-versicolor':ve,'Iris-virginica':vi})

#print(data)

data=data.iloc[np.random.permutation(len(data))]

print(data)

data=data.reset_index(drop=True)

#training data
trainFeats=data.ix[0:105,['f1','f2','f3','f4']]
temp=data['f5']
trainlabels=temp[0:106]

y=tf.placeholder(tf.float32,shape=[None, 3])
#weight and bias
m=tf.Variable(tf.zeros([4,3]))
x=tf.placeholder(tf.float32,shape=[None,4],name="Input")
c=tf.Variable(tf.zeros([3]))

mxc = tf.nn.softmax((tf.matmul(x, m) + c) ,name="output")

loss = tf.reduce_mean(-tf.reduce_sum(y * tf.log(mxc), reduction_indices=[1]))

train_step = tf.train.AdamOptimizer(0.01).minimize(loss)

sess = tf.InteractiveSession()
init = tf.initialize_all_variables()
sess.run(init)


#_=tf.contrib.tflite.Convert(sess.graph_def,[x],[mxc])


#number of interations
epoch=2000
for step in range(epoch):
  print(sess.run([train_step,loss], feed_dict={x: trainFeats, y:[t for t in trainlabels.as_matrix()]}))

testData=data.ix[130,['f1','f2','f3','f4']]
testDataInFrormat=testData.reshape(1,4)
print(sess.run(tf.argmax(mxc),feed_dict={x:testDataInFrormat}))

tf.train.write_graph(sess.graph_def,'pbtxtFiles/','savegraph.pbtxt',as_text=True)

tf.train.Saver().save(sess,'pbtxtFiles/model.ckpt')

# jajkhbdcjabjcbdskjbkcjbsakjbckjasbckjasbckajcsbakjcbaksjcbakjbcbsabcasbc,asbcjabscjkabsckjabckjbcs

# Freeze the graph
MODEL_NAME = 'iris'
input_graph_path = 'pbtxtFiles/savegraph.pbtxt'
checkpoint_path = 'pbtxtFiles/model.ckpt'
input_saver_def_path = ""
input_binary = False
output_node_names = "output"
restore_op_name = "save/restore_all"
filename_tensor_name = "save/Const:0"
output_frozen_graph_name = 'pbtxtFiles/frozen_model_'+MODEL_NAME+'.pb'
output_optimized_graph_name = 'pbtxtFiles/optimized_inference_model_'+MODEL_NAME+'.pb'
clear_devices = True

freeze_graph.freeze_graph(input_graph_path, input_saver_def_path,
                          input_binary, checkpoint_path, output_node_names,
                          restore_op_name, filename_tensor_name,
                          output_frozen_graph_name, clear_devices, "")


output_graph_def = optimize_for_inference_lib.optimize_for_inference(
        sess.graph_def,
        ["Input"], # an array of the input node(s)
        ["output"], # an array of output nodes
        tf.float32.as_datatype_enum)

tflite_model=tf.contrib.lite.toco(sess.graph_def,[x],[mxc])
open("wow.tflite","w").write(tflite_model)
//= ================================================

**Comment by SanthoshMKunthe** [comment]
Am geetting TOCO_CONVERT error. . .Kindlyhelp. . .

**AttributeError: module 'tensorflow.contrib.lite.python.lite' has no attribute 'toco_convert'**
_see last two  lines for error causing code_
//=================================
import tensorflow  as tf
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as lib

from tensorflow.python.tools import freeze_graph
from tensorflow.python.tools import optimize_for_inference_lib


print(tf.__version__)
data=pd.read_csv('C:\ml\irisInAndroid\iris.data',names=['f1','f2','f3','f4','f5'])

s=np.asarray([1,0,0])
ve=np.asarray([0,1,0])
vi=np.asarray([0,0,1])

data['f5']=data['f5'].map({'Iris-setosa':s,'Iris-versicolor':ve,'Iris-virginica':vi})


data=data.iloc[np.random.permutation(len(data))]

print(data)

data=data.reset_index(drop=True)

trainFeats=data.ix[0:105,['f1','f2','f3','f4']]
temp=data['f5']
trainlabels=temp[0:106]

y=tf.placeholder(tf.float32,shape=[None, 3])

m=tf.Variable(tf.zeros([4,3]))
x=tf.placeholder(tf.float32,shape=[None,4],name="Input")
c=tf.Variable(tf.zeros([3]))

mxc = tf.nn.softmax((tf.matmul(x, m) + c) ,name="output")

loss = tf.reduce_mean(-tf.reduce_sum(y * tf.log(mxc), reduction_indices=[1]))

train_step = tf.train.AdamOptimizer(0.01).minimize(loss)

sess = tf.InteractiveSession()
init = tf.initialize_all_variables()
sess.run(init)




epoch=2000
for step in range(epoch):
  print(sess.run([train_step,loss], feed_dict={x: trainFeats, y:[t for t in trainlabels.as_matrix()]}))

testData=data.ix[130,['f1','f2','f3','f4']]
testDataInFrormat=testData.reshape(1,4)
print(sess.run(tf.argmax(mxc),feed_dict={x:testDataInFrormat}))

tf.train.write_graph(sess.graph_def,'pbtxtFiles/','savegraph.pbtxt',as_text=True)

tf.train.Saver().save(sess,'pbtxtFiles/model.ckpt')

MODEL_NAME = 'iris'
input_graph_path = 'pbtxtFiles/savegraph.pbtxt'
checkpoint_path = 'pbtxtFiles/model.ckpt'
input_saver_def_path = ""
input_binary = False
output_node_names = "output"
restore_op_name = "save/restore_all"
filename_tensor_name = "save/Const:0"
output_frozen_graph_name = 'pbtxtFiles/frozen_model_'+MODEL_NAME+'.pb'
output_optimized_graph_name = 'pbtxtFiles/optimized_inference_model_'+MODEL_NAME+'.pb'
clear_devices = True

freeze_graph.freeze_graph(input_graph_path, input_saver_def_path,
                          input_binary, checkpoint_path, output_node_names,
                          restore_op_name, filename_tensor_name,
                          output_frozen_graph_name, clear_devices, "")


output_graph_def = optimize_for_inference_lib.optimize_for_inference(
        sess.graph_def,
        ["Input"], # an array of the input node(s)
        ["output"], # an array of output nodes
        tf.float32.as_datatype_enum)

tflite_model=tf.contrib.lite.toco_convert(sess.graph_def,[x],[mxc])
open("wow.tflite","w").write(tflite_model)
@leandroBorgesFerreira @aselle @angersson @ry @jmhodges @a-dai @a-doumoulakis @a7744hsc @aam-at @b-3-n @b0noI @bafu @bakunyo @c0g @caisq @callofdutyops @calpa @cameronphchen 
am getting .pb abd .ckpt

**Comment by jizhidezhaojun** [comment]
my tensorflow version is 1.8.0,but still show this error ,
module 'tensorflow.contrib' has no attribute 'lite',
have no idea...

**Comment by naelabdeljawad** [comment]
@jizhidezhaojun same with me.
Did you handle the issue ?

**Comment by amanda321** [comment]
@jizhidezhaojun @naelabdeljawad doing a pip install of tensorflow-gpu-1.9.0rc1 worked for me! And following these [instructions](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/g3doc/python_api.md):

Example:
```
import tensorflow as tf
converter = tf.contrib.lite.TocoConverter.from_frozen_graph(...)
```

**Comment by nitheeshmuthuraj** [comment]
2018-07-30 07:22:46.477633: F tensorflow/contrib/lite/toco/import_tensorflow.cc:2020] Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'
Aborted (core dumped)

None

I have tensorflow version 1.9 and i do have tf_nightly installed . so when i convert keras model file to tflite i get this error !!.

**Comment by DmitrySolntsev** [comment]
I've got the same issue: AttributeError: module 'tensorflow.contrib' has no attribute 'lite'.
Tensorflow-gpu 1.10 installed from pip 18.0
Windows 10
Python 3.6.

**Comment by Lionellye97** [comment]
I am having the same issue as @DmitrySolntsev as well.

**Comment by aselle** [comment]
I believe this is fixed in master or 0.11 RC. Please give that a try.
-A

**Comment by manupillai308** [comment]
I also got the same issue, but got it fixed by installing tf_nightly using "pip install tf_nightly"
Please be sure that while installing, there shouldnt be any active python sessions or else the install will fail and the import of even the tensorflow will get u errors. 
close all active python sessions and install tf_nightly.

**Comment by user-ZJ** [comment]
“pip install --force-reinstall tf_nightly_gpu” to solve the problem

**Comment by clhne** [comment]
update TF.

**Comment by jennings1716** [comment]
TF version = 1.12
tfnightly = 1.13.0.dev20190104
python 3.5
Model [ ssd_mobilenet_v1_coco_2018_01_28](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz)

````
import tensorflow as tf
import sys
def convert(frozen):
	graph_def_file = frozen+"/frozen_inference_graph.pb"
	input_arrays = ["image_tensor"]
	output_arrays = ["detection_boxes","detection_scores","detection_classes","num_detections"]
	converter = tf.contrib.lite.TFLiteConverter.from_frozen_graph(graph_def_file,input_arrays,output_arrays)#,input_shapes={"image_tensor":[None,300,300,3]})
	tflite_model = converter.convert()
	open(frozen+"/model.tflite", "wb").write(tflite_model)

if __name__=='__main__':
	frozen_path = sys.argv[1]
	convert(frozen_path)
````

Error

> 2019-01-07 09:01:08.263004: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-07 09:01:08.268020: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300030000 Hz
2019-01-07 09:01:08.268185: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0x56b0400 executing computations on platform Host. Devices:
2019-01-07 09:01:08.268255: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): <undefined>, <undefined>
2019-01-07 09:01:09.412404: I tensorflow/core/grappler/devices.cc:53] Number of eligible GPUs (core count >= 8): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-01-07 09:01:09.412562: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-01-07 09:01:11.571194: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:584] Optimization results for grappler item: graph_to_optimize
2019-01-07 09:01:11.571245: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   model_pruner: Graph size after: 5957 nodes (-3), 10020 edges (-3), time = 68.272ms.
2019-01-07 09:01:11.571253: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   function_optimizer: Graph size after: 5957 nodes (0), 10020 edges (0), time = 13.564ms.
2019-01-07 09:01:11.571259: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   constant folding: Graph size after: 5958 nodes (1), 10022 edges (2), time = 539.625ms.
2019-01-07 09:01:11.571265: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   shape_optimizer: Graph size after: 5958 nodes (0), 10022 edges (0), time = 31.515ms.
2019-01-07 09:01:11.571271: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   arithmetic_optimizer: Graph size after: 4306 nodes (-1652), 8412 edges (-1610), time = 243.152ms.
2019-01-07 09:01:11.571280: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   loop_optimizer: Graph size after: 4289 nodes (-17), 8380 edges (-32), time = 43.908ms.
2019-01-07 09:01:11.571289: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   dependency_optimizer: Graph size after: 4272 nodes (-17), 8358 edges (-22), time = 103.724ms.
2019-01-07 09:01:11.571299: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   layout: Graph size after: 4272 nodes (0), 8358 edges (0), time = 15.684ms.
2019-01-07 09:01:11.571309: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   memory_optimizer: Graph size after: 4272 nodes (0), 8358 edges (0), time = 263.292ms.
2019-01-07 09:01:11.571319: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   model_pruner: Graph size after: 4258 nodes (-14), 8332 edges (-26), time = 43.246ms.
2019-01-07 09:01:11.571329: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   function_optimizer: Graph size after: 4258 nodes (0), 8332 edges (0), time = 11.187ms.
2019-01-07 09:01:11.571338: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   constant folding: Graph size after: 4258 nodes (0), 8332 edges (0), time = 305.64ms.
2019-01-07 09:01:11.571348: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   shape_optimizer: Graph size after: 4258 nodes (0), 8332 edges (0), time = 22.274ms.
2019-01-07 09:01:11.571358: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   arithmetic_optimizer: Graph size after: 4256 nodes (-2), 8328 edges (-4), time = 192.768ms.
2019-01-07 09:01:11.571367: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:586]   dependency_optimizer: Graph size after: 4256 nodes (0), 8328 edges (0), time = 100.01ms.
Traceback (most recent call last):
  File "export_graph.py", line 15, in <module>
    convert(frozen_path)
  File "export_graph.py", line 10, in convert
    tflite_model = converter.convert()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/lite/python/lite.py", line 499, in convert
    **converter_kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/lite/python/convert.py", line 445, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/lite/python/convert.py", line 208, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-01-07 09:01:12.809603: F tensorflow/core/framework/function.cc:1640] Check failed: GetOpGradFactory()->insert({op, func}).second Duplicated gradient for ReadVariableOp
Aborted (core dumped)

**Comment by umbrellalalalala** [comment]
I met the same problem when I used
`import tensorflow as tf` and 
`tf.contrib.TFLiteConverter.from_session(self.sess, [img], [out])`

then I tried
`from tensorflow.contrib import lite`  and 
`lite.TFLiteConverter.from_session(self.sess, [img], [out])`
and no longer get this problem. But I don't know why.

**Comment by jennings1716** [comment]
@umbrellalalalala  It is mainly version issue.. Check https://www.tensorflow.org/lite/convert/python_api for your tensorflow version and use the apt python api

**Comment by umbrellalalalala** [comment]
@jennings1716  Thank you. But my tensorflow version is already 1.12.0.

**Comment by mrgloom** [comment]
```
import tensorflow; print(tensorflow.__version__)
1.14.0

'lite' in dir(tf.contrib)
False
```
