### ISSUE TITLE
sparse_multiclass_hinge_loss() error

### ISSUE THREAD

**Issue by axelurbiz** [tensorflow/tensorflow#15415]
Hello, 

I'm getting the error below using `sparse_multiclass_hinge_loss()`. Any hints would be highly appreciated.

```python
import numpy as np
import tensorflow as tf

x = np.random.uniform(0, 1, size = (100, 5))
y = np.random.choice(3, 100) 
y = y.reshape(100, 1)

X = tf.placeholder("float32", [None, 5])
Y = tf.placeholder("int32", [None, 1])

weights = {'w': tf.Variable(tf.random_uniform([5, 3]))}
biases = {'b': tf.Variable(tf.zeros([3]))}

logits = tf.add(tf.matmul(X, weights['w']), biases['b'])

loss = tf.reduce_mean(tf.contrib.kernel_methods.sparse_multiclass_hinge_loss(logits=logits, labels=Y))

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    res = sess.run(loss, feed_dict={X: x, Y: y}) 


res
```
 make_tensor_proto(values, dtype, shape, verify_shape)
    369   else:
    370     if values is None:
--> 371       raise ValueError("None values not supported.")
    372     # if dtype is provided, forces numpy array to be the type
    373     # provided if possible.

ValueError: None values not supported.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by axelurbiz** [comment]
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
TensorFlow installed from (source or binary): N
TensorFlow version (use command below): 1.4
Python version: 2.7.12
Bazel version (if compiling from source): NA
GCC/Compiler version (if compiling from source): NA
CUDA/cuDNN version: NA
GPU model and memory: NA
Exact command to reproduce: See below.
