### ISSUE TITLE
[feature request] Switch to nvidia-docker v2?

### ISSUE THREAD

**Issue by snnn** [tensorflow/tensorflow#15432]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.4.1
- **Python version**: 
3.5.4
- **Bazel version (if compiling from source)**:
None
- **GCC/Compiler version (if compiling from source)**:
None
- **CUDA/cuDNN version**:
None
- **GPU model and memory**:
None
- **Exact command to reproduce**:
None

### Describe the problem
Now we are using nvidia-docker v1 for CI build. We should switch to v2 because v1 is now being deprecated. (https://github.com/NVIDIA/nvidia-docker/wiki/About-version-2.0)

**Comment by gunan** [comment]
The tensorflow CI uses nvidia-docker v2 for a while now.
Is there anything specific you saw that we missed?

**Comment by snnn** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/ci_build.sh#L83
It still depends on nvidia-docker command? Instead of that, it should use:

    docker run --runtime=nvidia ...

**Comment by gunan** [comment]
`nvidia-docker` command is still available for backwards compatility with nvidia-docker2.
This script gets installed on your system once you install nvidia docker v2
https://github.com/NVIDIA/nvidia-docker/blob/master/nvidia-docker
