### ISSUE TITLE
[cmake] CPU only build error in tf_stream_executor.cmake

### ISSUE THREAD

**Issue by SergeyBykov1** [tensorflow/tensorflow#15447]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master
- **Python version**: N/A, building with cmake
- **Bazel version (if compiling from source)**: N/A, building with cmake
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
cd tensorflow/contrib/cmake
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="../bin" ..

### Describe the problem
cmake build fails when 
option(tensorflow_ENABLE_GPU "Enable GPU support" OFF)
with following error:
.../tensorflow-master/tensorflow/stream_executor/dso_loader.h:32:30: fatal error: cuda/cuda_config.h: No such file or directory
compilation terminated.

### Source code / logs
Pretty sure that the issue lies in this commit:
https://github.com/tensorflow/tensorflow/commit/f1582cf82f06810900ee99870f5d5d3a7478d044#diff-1d799fa350437420218e5e5aa680c481

in CMakeLists.txt the line
"  include_directories(${tensorflow_source_dir}/third_party/gpus)"
is still under tensorflow_ENABLE_GPU

Which is why dso_loader cannot find cuda_config.h

On the other hand, I suppose it should not use this include at all in the CPU mode.

**Comment by jart** [comment]
@mrry Problems are being reported with some cmake cleanup that was done two weeks ago in https://github.com/tensorflow/tensorflow/pull/15099

**Comment by mrry** [comment]
Since we only continuously test the CMake build for Windows, it looks like #15099 has broken the Linux CPU build.

We'd accept a contribution to revert #15099 or fix it properly.

/cc @Androbin

**Comment by tilakrayal** [comment]
@SergeyBykov1,
Related #15099 PR was merged. Could you please check the same and update to latest stable v2.10 and let us know if the issue still persists. Thank you!
