### ISSUE TITLE
Tensorflow-gpu 1.4.1 windows binaries couldn't be found

### ISSUE THREAD

**Issue by eddr** [tensorflow/tensorflow#15449]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 1709
- **TensorFlow installed from (source or binary)**: looking for the binary
- **TensorFlow version (use command below)**: 1.4.1
- **Python version**: 3.6.3 64-bit
- **Exact command to reproduce**: "pip3 install --upgrade tensorflow-gpu"

### Describe the problem

Can't find the binaries for the 1.4.1 windows version

**Comment by snnn** [comment]
They didn't release TF 1.4.1 for Windows. I hope you've read the release note.
"NOTE: There is no Windows binary for 1.4.1. The only difference to 1.4.0 is the CloudML Engine fix, and since CloudML Engine only supports Linux, Windows is unaffected."

**Comment by eddr** [comment]
Apparently I haven't. Thx
