### ISSUE TITLE
Tensorflow installation error

### ISSUE THREAD

**Issue by gopi77** [tensorflow/tensorflow#15442]
Tensorflow installation error.

Method followed: https://www.tensorflow.org/install/install_linux#InstallingAnaconda

(Environment ubuntu 16.04, anaconda 4.3.29, Python 2.7.13, nvidia 1070 GPU)
Please help.

>>>>>
gopi@gp:~$ source activate tensorflow
(tensorflow) gopi@gp:~$ pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp27-none-linux_x86_64.whl
Collecting tensorflow-gpu==1.4.0 from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp27-none-linux_x86_64.whl
  Using cached https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp27-none-linux_x86_64.whl
Collecting enum34>=1.1.6 (from tensorflow-gpu==1.4.0)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting six>=1.10.0 (from tensorflow-gpu==1.4.0)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting protobuf>=3.3.0 (from tensorflow-gpu==1.4.0)
  Using cached protobuf-3.5.0.post1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting numpy>=1.12.1 (from tensorflow-gpu==1.4.0)
  Using cached numpy-1.13.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting wheel (from tensorflow-gpu==1.4.0)
  Using cached wheel-0.30.0-py2.py3-none-any.whl
Collecting backports.weakref>=1.0rc1 (from tensorflow-gpu==1.4.0)
  Using cached backports.weakref-1.0.post1-py2.py3-none-any.whl
Collecting tensorflow-tensorboard<0.5.0,>=0.4.0rc1 (from tensorflow-gpu==1.4.0)
  Using cached tensorflow_tensorboard-0.4.0rc3-py2-none-any.whl
Collecting mock>=2.0.0 (from tensorflow-gpu==1.4.0)
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf>=3.3.0->tensorflow-gpu==1.4.0)
  Downloading setuptools-38.2.4-py2.py3-none-any.whl (489kB)
    100% |████████████████████████████████| 491kB 30kB/s 
Collecting futures>=3.1.1; python_version < "3.2" (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
  Downloading futures-3.2.0-py2-none-any.whl
Collecting werkzeug>=0.11.10 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
  Downloading Werkzeug-0.13-py2.py3-none-any.whl (311kB)
    100% |████████████████████████████████| 317kB 31kB/s 
Collecting html5lib==0.9999999 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
Collecting markdown>=2.6.8 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
  Downloading Markdown-2.6.10.zip (414kB)
    100% |████████████████████████████████| 419kB 43kB/s 
Collecting bleach==1.5.0 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
  Using cached bleach-1.5.0-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->tensorflow-gpu==1.4.0)
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=2.0.0->tensorflow-gpu==1.4.0)
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Building wheels for collected packages: markdown
  Running setup.py bdist_wheel for markdown ... done
  Stored in directory: /home/gopi/.cache/pip/wheels/1e/5a/55/a80b200d12e234d575ad68c1528593d1ce488720b65b24e48c
Successfully built markdown
Installing collected packages: enum34, six, setuptools, protobuf, numpy, wheel, backports.weakref, futures, werkzeug, html5lib, markdown, bleach, tensorflow-tensorboard, funcsigs, pbr, mock, tensorflow-gpu
Exception:
Traceback (most recent call last):
  File "/home/gopi/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/gopi/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/gopi/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/gopi/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/gopi/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/gopi/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/gopi/.local/lib/python2.7/site-packages/pip/wheel.py", line 329, in clobber
    os.utime(destfile, (st.st_atime, st.st_mtime))
OSError: [Errno 1] Operation not permitted: '/home/gopi/anaconda2/lib/python2.7/site-packages/enum/README'
(tensorflow) gopi@gp:~$

**Comment by Carmezim** [comment]
Seems like an authorization issue rather TensorFlow's. Your user is probably not authorized to access a directory necessary for the installation. Using `sudo` will work but be sure you know what you're doing.

**Comment by gopi77** [comment]
Thanks for the reply.
Still error. Please check

(tensorflow) gopi@gp:~$ sudo pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp27-none-linux_x86_64.whl
The directory '/home/gopi/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/gopi/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
tensorflow_gpu-1.4.0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.

(tensorflow) gopi@gp:~$ sudo -H pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp27-none-linux_x86_64.whl
tensorflow_gpu-1.4.0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.

--------------------------

FYI:

gopi@gp:~/NVIDIA_CUDA-8.0_Samples/1_Utilities/deviceQuery$ ./deviceQuery 
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 1070"
  CUDA Driver Version / Runtime Version          9.0 / 8.0
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 8113 MBytes (8506769408 bytes)
  (15) Multiprocessors, (128) CUDA Cores/MP:     1920 CUDA Cores
  GPU Max Clock rate:                            1835 MHz (1.84 GHz)
  Memory Clock rate:                             4004 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 2097152 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = GeForce GTX 1070
Result = PASS

--------------------------

gopi@gp:~$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR      5
#define CUDNN_MINOR      1
#define CUDNN_PATCHLEVEL 10
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

**Comment by Carmezim** [comment]
Now it's a different error. Could you perhaps have created an environment for Python 3 rather 2?
This error occurs when the binary that doesn't correspond with the local environment, e.g. OS, Python version etc.

**Comment by Carmezim** [comment]
@tensorflowbutler hey

**Comment by gopi77** [comment]
Sorry for late response.
PYPI package meaning this one ? -> https://pypi.python.org/pypi/tensorflow 
GPU version of tensorflow for ubuntu 16.04 available here?

I also tried installing it using below conda command, but still the version shows older 1.2.1
>>>
gopi@gp:~$ conda install -c conda-forge tensorflow-gpu
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/gopi/anaconda2:
#
tensorflow-gpu            1.3.0                         0  
gopi@gp:~$ python
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow as tf
>>> print tf.VERSION
1.2.1
>>>

**Comment by Carmezim** [comment]
Yes, Linux packages are right there for TensorFlow v1.4.1. You can install as I mentioned before.
