### ISSUE TITLE
Tensorflow Installation Problem in Anaconda3-5.0.1Environment

### ISSUE THREAD

**Issue by bansalmk18jan** [tensorflow/tensorflow#15451]
After installing the Anaconda3-5.0.1 on Ubuntu 17.10, I have followed the following steps to install the Tesnorflow -

$ conda create -n tensorflow python=3.6
$ source activate tensorflow
(tensorflow)$ pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl
After installing the above pakages, I have verified the above installation in Anaconda environment, following issues are faced -
we6aisol@we6aisol-H170-Gaming-3:$ source activate tensorflow
(tensorflow) we6aisol@we6aisol-H170-Gaming-3:$ python
Python 3.6.3 |Anaconda, Inc.| (default, Nov 20 2017, 20:41:42)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

import tensorflow as tf
/home/we6aisol/anaconda3/envs/tensorflow/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
return f(*args, **kwds)
Please help me to resolve this issue.

Thanks & Regards
Manoj Bansal

**Comment by snnn** [comment]
Please use python 3.5

**Comment by bansalmk18jan** [comment]
I have already tried several times and observed that latest tensorflow will
require python3.6.
Pls. explain me the steps to follow to use python 3.5.
Thanks & Regards
Manoj Bansal

**Comment by jart** [comment]
Please follow #14182 for updates on this issue.
