### ISSUE TITLE
TensorFlow binary was not compiled to use: AVX AVX2 from Java 1.8

### ISSUE THREAD

**Issue by z589533** [tensorflow/tensorflow#15450]
![image](https://user-images.githubusercontent.com/12063612/34111971-2b81c42a-e446-11e7-8482-6e3f3867e8d6.png)

![image](https://user-images.githubusercontent.com/12063612/34112074-6ad1b824-e446-11e7-8541-02ae054aefa0.png)

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform from Windows 10
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version 1.4.0
- **Java version** : 1.8.0_144
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 
- **GPU model and memory**: GTX 1060 6G and Memory 8G
- **Exact command to reproduce**: javac

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
"C:\Program Files\Java\jdk1.8.0_144\bin\java" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:56173,suspend=y,server=n -javaagent:C:\Users\Administrator\.IntelliJIdea2017.3\system\captureAgent\debugger-agent.jar=C:\Users\Administrator\AppData\Local\Temp\capture.props -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_144\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\rt.jar;C:\gitspase\zczdemo\target\classes;E:\maven\Jars\org\tensorflow\tensorflow\1.4.0\tensorflow-1.4.0.jar;E:\maven\Jars\org\tensorflow\libtensorflow\1.4.0\libtensorflow-1.4.0.jar;E:\maven\Jars\org\tensorflow\libtensorflow_jni\1.4.0\libtensorflow_jni-1.4.0.jar;E:\maven\Jars\org\projectlombok\lombok\1.16.18\lombok-1.16.18.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.1\lib\idea_rt.jar" com.zcz.tensorflow.zczdemo.HelloTF
Connected to the target VM, address: '127.0.0.1:56173', transport: 'socket'
Hello from 1.4.0
Disconnected from the target VM, address: '127.0.0.1:56173', transport: 'socket'

**Comment by z589533** [comment]
2017-12-18 22:59:15.864242: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2

from java VM options Can you specify the GPU?

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/34112468-96bedb6e-e447-11e7-865b-5946f4accfdc.png)

**Comment by z589533** [comment]
[display]
Operating System: Windows 10 Pro, 64-bit
DirectX version: 12.0
GPU Processor: GeForce GTX 1060
Driver Version: 388.59
Direct3D API version: 12
Direct3D functional level: 12_1
CUDA core: 1280
Core clock: 1404 MHz
Memory data rate: 8008 MHz
Memory Interface: 192-bit
Memory Bandwidth: 192.19 GB / s
Total available graphics memory: 10180MB
Dedicated video memory: 6144 MB GDDR5
System video memory: 0MB
Shared system memory: 4036MB
Video BIOS version: 86.06.18.00.04
IRQ: Not used
Bus: PCI Express x16 Gen3
Device ID: 10DE 1C20 6A011558
Part Number: 2914 0030

[Component]

nvui.dll		8.17.13.8859		NVIDIA User Experience Driver Component
nvxdplcy.dll		8.17.13.8859		NVIDIA User Experience Driver Component
nvxdbat.dll		8.17.13.8859		NVIDIA User Experience Driver Component
nvxdapix.dll		8.17.13.8859		NVIDIA User Experience Driver Component
NVCPL.DLL		8.17.13.8859		NVIDIA User Experience Driver Component
nvCplUIR.dll		8.1.940.0		NVIDIA Control Panel
nvCplUI.exe		8.1.940.0		NVIDIA Control Panel
nvViTvSR.dll		23.21.13.8859		NVIDIA Video Server
nvViTvS.dll		23.21.13.8859		NVIDIA Video Server
NVSTVIEW.EXE		7.17.13.8859		NVIDIA 3D Vision Photo Viewer
NVSTTEST.EXE		7.17.13.8859		NVIDIA 3D Vision Test Application
NVSTRES.DLL		7.17.13.8859		NVIDIA 3D Vision Module
nvDispSR.dll		23.21.13.8859		NVIDIA Display Server
NVMCTRAY.DLL		23.21.13.8859		NVIDIA Media Center Library
nvDispS.dll		23.21.13.8859		NVIDIA Display Server
nvWSSR.dll		23.21.13.8859		NVIDIA Workstation Server
nvWSS.dll		23.21.13.8859		NVIDIA Workstation Server
PhysX		09.17.0524		NVIDIA PhysX
NVCUDA.DLL		23.21.13.8859		NVIDIA CUDA 9.1.104 driver
nvGameSR.dll		23.21.13.8859		NVIDIA 3D Settings Server
nvGameS.dll		23.21.13.8859		NVIDIA 3D Settings Server

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/34112625-2277d408-e448-11e7-9b99-92f3618b977f.png)

**Comment by z589533** [comment]
Trouble to help me locate the problem, thanks

**Comment by snnn** [comment]
It's a warning, not a bug.
If you need AVX support, compile libtensorflow by yourself.

**Comment by z589533** [comment]
https://storage.googleapis.com/tensorflow/  i find storage,not find  libtensorflow_jni-gpu-windows-x86_64-1.4.0.zip ,only libtensorflow-gpu-linux-x86_64-1.4.0.tar.gz

**Comment by z589533** [comment]
Have a tutorial, please send me, thank you

**Comment by snnn** [comment]
Np. Your suggestion is nice, I feel sad that I can't help you. My English is bad. You may seek help from the others.

**Comment by michaelisard** [comment]
This is a better question for stackoverflow. You can find some discussions about this by searching 'build tensorflow avx'. Essentially you need to [build from source](https://www.tensorflow.org/install/install_sources) specifying the right optimization flags for your platform in order to silence the warning.

**Comment by vishal-patel17** [comment]
Just lower the warning level:

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
