### ISSUE TITLE
 sparse_multiclass_hinge_loss() Error

### ISSUE THREAD

**Issue by axelurbiz** [tensorflow/tensorflow#15480]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows/MacOS
- **TensorFlow installed from (source or binary)**:N
- **TensorFlow version (use command below)**:1.4
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:N
- **GCC/Compiler version (if compiling from source)**:N
- **CUDA/cuDNN version**:NA
- **GPU model and memory**:NA
- **Exact command to reproduce**:See below

### Describe the problem
There seems to be a bug in sparse_multiclass_hinge_loss(), as per the example below.

### Source code / logs

```python
import numpy as np
import tensorflow as tf

x = np.random.uniform(0, 1, size = (100, 5))
y = np.random.choice(3, 100) 
y = y.reshape(100, 1)

X = tf.placeholder("float32", [None, 5])
Y = tf.placeholder("int32", [None, 1])

weights = {'w': tf.Variable(tf.random_uniform([5, 3]))}
biases = {'b': tf.Variable(tf.zeros([3]))}

logits = tf.add(tf.matmul(X, weights['w']), biases['b'])

loss = tf.reduce_mean(tf.contrib.kernel_methods.sparse_multiclass_hinge_loss(logits=logits, labels=Y))

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    res = sess.run(loss, feed_dict={X: x, Y: y}) 


res
```

 make_tensor_proto(values, dtype, shape, verify_shape)
    369   else:
    370     if values is None:
--> 371       raise ValueError("None values not supported.")
    372     # if dtype is provided, forces numpy array to be the type
    373     # provided if possible.

ValueError: None values not supported.

**Comment by printdhruv** [comment]
According to [docs](https://www.tensorflow.org/api_docs/python/tf/contrib/kernel_methods/sparse_multiclass_hinge_loss)

```
Raises:
ValueError: If logits, labels or weights have invalid or inconsistent shapes.
ValueError: If labels tensor has invalid dtype.
```

**Comment by axelurbiz** [comment]
This is not the case here.

The issue seems on passing tensors to the logits argument in the loss function. For instance if I pass a constant as below, the issue goes away.


```python
import tensorflow as tf
sess = tf.InteractiveSession()

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from tensorflow.contrib.kernel_methods.python import losses
from tensorflow.python.framework import constant_op
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import errors
from tensorflow.python.platform import test

x = np.random.uniform(0, 1, size = (3, 3))
y = np.random.choice(3, 3) 
y = y.reshape(3, 1)

X = tf.placeholder("float32", [None, 3])
Y = tf.placeholder("int32", [None, 1])

weights = {'w': tf.Variable(tf.random_uniform([3, 3]))}
biases = {'b': tf.Variable(tf.zeros([3]))}

#logits = tf.add(tf.matmul(X, weights['w']), biases['b'])

logits = constant_op.constant([[1.6, -0.4, 0.8], [1.5, 0.8, -1.0],
                                     [0.2, -1.8, 4.0]])
loss = tf.reduce_mean(tf.contrib.kernel_methods.sparse_multiclass_hinge_loss(logits=logits, labels=Y))

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    res = sess.run(loss, feed_dict={X: x, Y: y}) 


res
```

**Comment by facaiy** [comment]
Could you paste the whole exception stack?

**Comment by axelurbiz** [comment]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-b3ef74c071b2> in <module>()
     14 logits = tf.add(tf.matmul(X, weights['w']), biases['b'])
     15 
---> 16 loss = tf.reduce_mean(tf.contrib.kernel_methods.sparse_multiclass_hinge_loss(logits=logits, labels=Y))
     17 
     18 init = tf.global_variables_initializer()

/users/.local/lib/python2.7/site-packages/tensorflow/contrib/kernel_methods/python/losses.pyc in sparse_multiclass_hinge_loss(labels, logits, weights, scope, loss_collection, reduction)
    114     # Compute the logits tensor corresponding to the correct class per instance.
    115     example_indices = array_ops.reshape(
--> 116         math_ops.range(batch_size), shape=[batch_size, 1])
    117     indices = array_ops.concat(
    118         [

/users/.local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.pyc in range(start, limit, delta, dtype, name)
   1215   with ops.name_scope(name, "Range", [start, limit, delta]) as name:
   1216     start = ops.convert_to_tensor(start, dtype=dtype, name="start")
-> 1217     limit = ops.convert_to_tensor(limit, dtype=dtype, name="limit")
   1218     delta = ops.convert_to_tensor(delta, dtype=dtype, name="delta")
   1219 

/users/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc in convert_to_tensor(value, dtype, name, preferred_dtype)
    834       name=name,
    835       preferred_dtype=preferred_dtype,
--> 836       as_ref=False)
    837 
    838 

/users/q69hhtm/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx)
    924 
    925     if ret is None:
--> 926       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    927 
    928     if ret is NotImplemented:

/users/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.pyc in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    227                                          as_ref=False):
    228   _ = as_ref
--> 229   return constant(v, dtype=dtype, name=name)
    230 
    231 

/users/q69hhtm/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.pyc in constant(value, dtype, shape, name, verify_shape)
    206   tensor_value.tensor.CopyFrom(
    207       tensor_util.make_tensor_proto(
--> 208           value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    209   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    210   const_tensor = g.create_op(

/users/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.pyc in make_tensor_proto(values, dtype, shape, verify_shape)
    369   else:
    370     if values is None:
--> 371       raise ValueError("None values not supported.")
    372     # if dtype is provided, forces numpy array to be the type
    373     # provided if possible.

ValueError: None values not supported.

**Comment by petrosmol** [comment]
Thanks for reporting this. I will take a look today

Petros

**Comment by facaiy** [comment]
The exception is triggered when batch size is unknown, I added #15544 to fix it.

**Comment by petrosmol** [comment]
the issue has to do with dynamic vs static shape. The [change](https://github.com/tensorflow/tensorflow/pull/15544) by facaiy fixes it.
