### ISSUE TITLE
How to add run name to TensorBoard?

### ISSUE THREAD

**Issue by zhang8473** [tensorflow/tensorflow#1548]
On my TensorBoard, the run name always shows as "." The Board put all of my runs under the same log path into one plot. How do I separate them by setting a run name? I did not find it out from your documentary.

![image](https://cloud.githubusercontent.com/assets/5016962/13895427/48971808-ed30-11e5-9f94-8be43e00252c.png)

How did you achieve this in your documentary?
![image](https://cloud.githubusercontent.com/assets/5016962/13895456/9d7438ce-ed30-11e5-86bf-e94173e20d95.png)

I tried your https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py

The run name is also just a "."....

**Comment by ecobost** [comment]
You can get that by putting the event file in a folder called 'data' and running TensorBoard in the folder that contains data.
The idea is that you will create a folder called summary (or something like that) and store the summaries of different runs in different folders (so ./run1, ./run2, etc) and then when running TensorBoard in ./summary you can see results for different runs as 'run1', 'run2', etc.. 
You can also nest folders and get something like 'run1/part1', 'run1/part2', etc. if that's of any use.

**Comment by danmane** [comment]
thanks @ecobost for the correct info :)
i've added information on this to [the TensorBoard documentation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/README.md#runs-comparing-different-executions-of-your-model)

**Comment by ljstrnadiii** [comment]
@dandelionmane that link gives a 404.

**Comment by tuzhucheng** [comment]
@ljstrnadiii this is a working link: https://github.com/tensorflow/tensorboard#runs-comparing-different-executions-of-your-model

**Comment by stefan-falk** [comment]
It's possible to rename the directories as well:

```
tensorboard --logdir ExperimentA:path/to/dir,ExperimentB:another/path/to/somewhere
```

**Comment by gtinchev** [comment]
Just to mention that the above command no longer works with newer version of tensorboard. The argument should be `logdir_spec`. For example:

```
tensorboard --logdir_spec ExperimentA:path/to/dir,ExperimentB:another/path/to/somewhere
```
