### ISSUE TITLE
fatal error C1083: Cannot open include file: 'tensorflow/core/framework/device_attributes.pb_text.h'

### ISSUE THREAD

**Issue by cj741** [tensorflow/tensorflow#15517]
I am new to tensorflow, when I compile tensorfolw with VS2015 in Windows 7, I got the following error, could anyone help on this, thanks!
fatal error C1083: Cannot open include file: 'tensorflow/core/framework/device_attributes.pb_text.h'

**Comment by snnn** [comment]
1. Please fill the form. Especially, how did you run cmake
2. Apparently, you are using the wrong configuration.

**Comment by cj741** [comment]
I downloaded and installed Anaconda5, git, Swig 3.0.12, tensorflow source code and then generated VS sln file with cmake GUI(I didn't use command line tool). what should I do, if with the command line?
Thanks!

**Comment by snnn** [comment]
I suggest you run cmake from commandline. Please read the README.md file under tensorflow/contrib/cmake dir carefully, make sure you set all the options correctly

**Comment by cj741** [comment]
@snnn Thanks for your help,  I followed the readme file and made some progress, but I got new problem like following:

 "fatal: unable to access 'https://boringssl.googlesource.com/boringssl/': Fail
 ed to connect to boringssl.googlesource.com port 443: Timed out
 fatal: clone of 'https://boringssl.googlesource.com/boringssl' into submodule
  path 'D:/tensorflow/tensorflow/contrib/cmake/build/grpc/src/grpc/third_party
 /boringssl-with-bazel' failed"

I checked the google and fond the same Issue #6 in tensorflow/serving, but it looks not work for the last tensorflow, do you have  idea how to solve this problem?

**Comment by snnn** [comment]
Sorry, if it's a bug, I'll try to fix it. If it's not, here is not the right place to ask help.

**Comment by cj741** [comment]
@snnn It looks a connection problem with 'https://boringssl.googlesource.com/boringssl/', is it possible chage the URL to 'https://github.com/google/boringssl.git'?
Thanks!

**Comment by cj741** [comment]
I think the problem is the URL 'https://boringssl.googlesource.com/boringssl/' is not work for me, since I am not using tensorflow distributed currently, I set "option(tensorflow_ENABLE_GRPC_SUPPORT "Enable gRPC support" OFF)" in the file "tensorflow/tensorflow/contrib/cmake/CMakeLists.txt", and then CMake and build again. It is compiled success now.
thanks for your help! @snnn

**Comment by SURFZJY** [comment]
@cj741 I got the same error "fatal error C1083: Cannot open include file: 'tensorflow/core/framework/device_attributes.pb_text.h'", when I compile tensorfolw with VS2015 in Windows 10, can you tell me how you solve the problem? thanks.

**Comment by Mycheny** [comment]
@SURFZJY  If your source code is on disk C, try opening vs in admin mode

**Comment by xungeer29** [comment]
> @cj741 I got the same error "fatal error C1083: Cannot open include file: 'tensorflow/core/framework/device_attributes.pb_text.h'", when I compile tensorfolw with VS2015 in Windows 10, can you tell me how you solve the problem? thanks.

Have you solved the problem? How to solve it?

**Comment by SURFZJY** [comment]
> > @cj741 I got the same error "fatal error C1083: Cannot open include file: 'tensorflow/core/framework/device_attributes.pb_text.h'", when I compile tensorfolw with VS2015 in Windows 10, can you tell me how you solve the problem? thanks.
> 
> Have you solved the problem? How to solve it?

have not tried the method, because i gave up the project laterly.
