### ISSUE TITLE
tensorflow-0.7.1-cp35-none-linux_x86_64.whl

### ISSUE THREAD

**Issue by zkl99999** [tensorflow/tensorflow#1551]
sudo pip3 install --upgrade http://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp35-none-linux_x86_64.whl
tensorflow-0.7.1-cp35-none-linux_x86_64.whl is not a supported wheel on this platform.
Storing debug log for failure in /home/xxx/.pip/pip.log

**Comment by zkl99999** [comment]
http://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp34-none-linux_x86_64.whl

**Comment by zkl99999** [comment]
python 3.5.1   canot install    http://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp34-none-linux_x86_64.whl

**Comment by zkl99999** [comment]
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/numpy/random/mtrand/mtrand.o build/temp.linux-x86_64-3.4/numpy/random/mtrand/randomkit.o build/temp.linux-x86_64-3.4/numpy/random/mtrand/initarray.o build/temp.linux-x86_64-3.4/numpy/random/mtrand/distributions.o -Lbuild/temp.linux-x86_64-3.4 -o build/lib.linux-x86_64-3.4/numpy/random/mtrand.cpython-34m.so
    Creating build/scripts.linux-x86_64-3.4/f2py3
      adding 'build/scripts.linux-x86_64-3.4/f2py3' to scripts
    changing mode of build/scripts.linux-x86_64-3.4/f2py3 from 644 to 755
    
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    changing mode of /usr/local/bin/f2py3 to 755
    Running from numpy source directory.
    /tmp/pip_build_root/numpy/numpy/distutils/system_info.py:1651: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    /tmp/pip_build_root/numpy/numpy/distutils/system_info.py:1660: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      warnings.warn(BlasNotFoundError.__doc__)
    /tmp/pip_build_root/numpy/numpy/distutils/system_info.py:1663: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      warnings.warn(BlasSrcNotFoundError.__doc__)
    /tmp/pip_build_root/numpy/numpy/distutils/system_info.py:1552: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    /tmp/pip_build_root/numpy/numpy/distutils/system_info.py:1563: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.__doc__)
    /tmp/pip_build_root/numpy/numpy/distutils/system_info.py:1566: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.__doc__)
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
  Found existing installation: six 1.5.2
    Not uninstalling six at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: setuptools 3.3
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, owned by OS
Successfully installed tensorflow wheel numpy protobuf six setuptools
Cleaning up...

**Comment by zkl99999** [comment]
kl@dell:~$ sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 546, in unpack_http_url
    resp = session.get(target_url, stream=True)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/adapters.py", line 385, in send
    raise SSLError(e)
SSLError: hostname 'storage.googleapis.com' doesn't match either of '*.orkut.com', '*.a.orkut.gmodules.com', '*.demo.orkut.com', '*.orkut.co.in', '*.orkut.com.br', '*.orkut.gmodules.com', '*.staging.orkut.com', '*.www.orkut.com', 'orkut.co.in', 'orkut.com', 'orkut.com.br'

Storing debug log for failure in /home/zkl/.pip/pip.log

**Comment by RasmooL** [comment]
Your first error can be solved by making a virtualenv.

**Comment by zkl99999** [comment]
ubuntu14.04.4  python3.5 python2.7   
sudo pip3 install --upgrade http://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp35-none-linux_x86_64.whl

finally  success,  in terminal, input  python3.4   
>>> import tensorflow as tf
>>>

**Comment by sherrym** [comment]
Closing issue as it sounds like it has been resolved.
