### ISSUE TITLE
No PyPi package for Tensorflow 1.4 on Windows?

### ISSUE THREAD

**Issue by andydevs** [tensorflow/tensorflow#15540]
Running Windows 10 with Python 3.6.
Just wondering when that's gonna come out.

**Comment by andydevs** [comment]
If you can, could you point me to an older version or an alternate installation?

**Comment by Carmezim** [comment]
Thanks pointing that out. While TensorFlowers check this issue you could download the binary [here](https://github.com/tensorflow/tensorflow#installation) to get v1.4 running.

**Comment by michaelisard** [comment]
@gunan can you comment?

**Comment by gunan** [comment]
we have the 1.4.1 packages missing, because that patch release only affected features that are not enabled on windows. However, we do have 1.4.0 packages on pypi:
https://pypi.python.org/pypi/tensorflow/1.4.0
https://pypi.python.org/pypi/tensorflow-gpu/1.4.0
