### ISSUE TITLE
Maven Nightlies

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/tensorflow#15543]
@asimshankar Would it be possible to start releasing Maven nightlies for the Java API packages? I only depend on the org.tensorflow Proto package, but I guess it would be more consistent to do that for all the Java API packages.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment]
@eaplatanios : We just released [maven packages for 1.5.0-rc0](https://search.maven.org/#artifactdetails%7Corg.tensorflow%7Cproto%7C1.5.0-rc0%7Cjar), so I'm hoping your immediate need is met.

I'm tempted to defer setting up releases of Maven nightlies till there is a stronger, more consistent demand for them. Sound reasonable?

**Comment by asimshankar** [comment]
Closing this out for now. Please re-open if you disagree. Thanks.
