### ISSUE TITLE
DIGITS tensorflow distributed problem ：Graph is finalized and cannot be modified

### ISSUE THREAD

**Issue by shoneSolomon** [tensorflow/tensorflow#15546]
I am a DIGITS novice, and I want to change the TensorFlow single machine from DIGITS to distributed。The following is the code that I modified。

sv = tf.train.Supervisor(is_chief=(FLAGS.task_index == 0),
            logdir='/root/digits/digits/jobs/hello',
                        saver=saver,
                        init_op=init_op,
                        )

with sv.prepare_or_wait_for_session(server.target) as sess:
    inf_model.start_queue_runners(sess)
    val_model.start_queue_runners(sess)
    train_model.start_queue_runners(sess)
    try：
         while not train_model.queue_coord.should_stop():
            _, summary_str, step = sess.run                                 ([train_model.train,
                                                                                        train_model.summary,
                                                                                        train_model.global_step],
                                                                                        feed_dict=feed_dict,
                                                                                        options=run_options,
                                                                                        run_metadata=run_metadata)

and run it,but error:

2017-12-19 06:56:23.696588: I tensorflow/core/distributed_runtime/master_session.cc:999] S
tart master session ad6a96f02b5d215f with config: 
INFO:tensorflow:Starting standard services.
2017-12-19 06:56:23 [INFO] Starting standard services.
INFO:tensorflow:Starting queue runners.
INFO:tensorflow:Saving checkpoint to path /root/digits/digits/jobs/xwk/model.ckpt
2017-12-19 06:56:23 [INFO] Starting queue runners.
2017-12-19 06:56:23 [INFO] Saving checkpoint to path /root/digits/digits/jobs/xwk/model.ck
ptINFO:tensorflow:Errorreported to Coordinator: , exceptions.KeyError: 'pyfunc_1'     [[Node: val/data/data_reader = PyFuncTin=[DT_STRING], Tout=[DT_STRING, DT_INT32,DT_INT64,DT_INT32],token="pyfunc_1", _device="/job:ps/replica:0/task:0/cpu:0"]]2017-12-19 06:56:23 [INFO] Error reported to Coordinator: , exceptions.KeyError: 'pyfunc_1'  [[Node: val/data/data_reader = PyFuncTin=[DT_STRING], Tout=[DT_STRING, DT_INT32,DT_INT64, DT_INT32],token="pyfunc_1",_device="/job:ps/replica:0/task:0/cpu:0"]]INFO:tensorflow:/root/digits/digits/jobs/xwk/model.ckpt is not in all_model_checkpoint_pat
hs. Manually adding it.2017-12-19 06:56:24 [INFO] /root/digits/digits/jobs/xwk/model.ckpt is not in all_model_che
ckpoint_paths. Manually adding it.2017-12-19 06:56:24 [INFO] Starting queue runners (val)
Traceback (most recent call last):
  File "/root/digits/digits/tools/tensorflow/main.py", line 779, in 
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48
, in run    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/root/digits/digits/tools/tensorflow/main.py", line 629, in main
    val_model.start_queue_runners(sess)
  File "/root/digits/digits/tools/tensorflow/model.py", line 208, in start_queue_runners
    tf.add_to_collection(digits.GraphKeys.QUEUE_RUNNERS, qr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 4
248, in add_to_collection    get_default_graph().add_to_collection(name, value)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2
792, in add_to_collection    self._check_not_finalized()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2
181, in _check_not_finalized    raise RuntimeError("Graph is finalized and cannot be modified.")
RuntimeError: Graph is finalized and cannot be modified.

Do you know what is the cause of the final problem?
If you know, please tell me.
thx.

**Comment by snnn** [comment]
start queue runners before create the session

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by shoneSolomon** [comment]
@michaelisard OK

**Comment by shoneSolomon** [comment]
@snnn It is solved, in superviser() ，all the build Graph must be finished,the summery.
