### ISSUE TITLE
tensorflow::gtl::string_as_array crashes on Windows

### ISSUE THREAD

**Issue by snnn** [tensorflow/tensorflow#15557]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.4.1
- **Python version**: 
3.5.4
- **Bazel version (if compiling from source)**:
None
- **GCC/Compiler version (if compiling from source)**:
None
- **CUDA/cuDNN version**:
None
- **GPU model and memory**:
None
- **Exact command to reproduce**:
None

### Describe the problem
Compile and run the following code in VS 2017 in **Debug** Mode.
```c++
#include <iostream>
#include <stdint.h>
using namespace std;

inline char* string_as_array(string* str) { return &*str->begin(); }
int main()
{
	string str;
	char* p = string_as_array(&str);
	std::cout << (uint64_t)p << std::endl;
	return 0;
}
```

It will crash.

```
Debug Assertion Failed!

Program: C:\WINDOWS\SYSTEM32\MSVCP140D.dll
File: c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.12.25827\include\xstring
Line: 1219

Expression: cannot dereference string iterator because it is out of range (e.g. an end iterator)

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.
```

This function is extracted from  tensorflow\core\lib\gtl\stl_util.h

**Comment by snnn** [comment]
We have the same issue in  tensorflow\core\lib\strings\strcat.cc:94

**Comment by jart** [comment]
AFAIK we're going to be migrating these GTL containers to [ABSL](https://github.com/abseil/abseil-cpp) at some point in the future (hopefully soon) since that library is well very well staffed, and the two probably share overlapping code. Until then, we would welcome contributions helping to improve our MSVC story.

**Comment by gunan** [comment]
@guschmue @mrry FYI

**Comment by FlorinLozneanu** [comment]
Function string_as_array may be implemented as:

inline char* string_as_array(string* str) 
{
	return (!str || str->empty()) ? nullptr : &*str->begin();
}

**Comment by FlorinLozneanu** [comment]
Function string_as_array may be implemented as below:

inline char* string_as_array(string* str)
{
	return (!str || str->empty()) ? nullptr : &*str->begin();
}

**Comment by Muskaan4299** [comment]
Is this issue still open for contribution? I look forward to contributing to this issue as my first contribution to the Outreachy internship.
