### ISSUE TITLE
Little error in example how to read data

### ISSUE THREAD

**Issue by lucgiffon** [tensorflow/tensorflow#15556]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.3.0-rc2-20-g0787eee 1.3.0
- **Python version**: 3.5.4
- **Exact command to reproduce**: 

```
python tensorflow/tensorflow/examples/how_tos/reading_data/convert_to_record.py
python tensorflow/tensorflow/examples/how_tos/reading_data/fully_connected_reader.py
```

### Describe the problem

Error when doing the above second command: `AttributeError: module 'tensorflow' has no attribute 'data'` The data attribute is actually in the contrib module then you should change the line 108 of the file `tensorflow/tensorflow/examples/how_tos/reading_data/fully_connected_reader.py`:

`dataset = tf.data.TFRecordDataset(filename)`
to
`dataset = tf.contrib.data.TFRecordDataset(filename)`

Sorry, I don't know if I should have submitted a pull request for such a little change.

**Comment by mrry** [comment]
In fact, the docs are correct: these APIs moved from `tf.contrib.data` to `tf.data` in TensorFlow 1.4.

**Comment by lucgiffon** [comment]
Sorry but it is not the case on github: https://github.com/tensorflow/tensorflow/tree/r1.4/tensorflow . Or maybe I didn't understand what you said.

**Comment by mrry** [comment]
It's imported here: https://github.com/tensorflow/tensorflow/blob/438604fc885208ee05f9eef2d0f2c630e1360a83/tensorflow/python/__init__.py#L81

(From your **System Information**, it looks like you're using TensorFlow 1.3, which is an older version.)

**Comment by lucgiffon** [comment]
Ok, sorry. I got it thank you.
