### ISSUE TITLE
Dataset shuffle operation is not deterministic

### ISSUE THREAD

**Issue by ahmedanis03** [tensorflow/tensorflow#15569]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:elementary OS 0.4.1 Loki
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version**: v1.4.0-19-ga52c8d9 1.4.1
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: Not related
- **GPU model and memory**: Not related 
- **Exact command to reproduce**: mentioned below

### Describe the problem
Dataset Shuffle operation is not determenastic 

### Source code / logs
```python
import numpy as np
import tensorflow as tf

def test():
  np.random.seed(42)
  tf.set_random_seed(42)
  numbers = np.arange(1,100)

  def get_data():
    dataset = tf.data.Dataset.from_tensor_slices(numbers)  # some initial dataset
    dataset =  dataset.shuffle(100)
    x = dataset.make_one_shot_iterator().get_next()
    return x

  # execution 1
  x = get_data()
  with tf.Session() as sess:
    x_batch1 = sess.run(x)
    print(x_batch1)
  # clear out everything
  tf.reset_default_graph()

  # execution 2
  x = get_data()
  with tf.Session() as sess:
    x_batch2 = sess.run(x)
    print(x_batch2)
  # results should be equivalent
  assert np.allclose(x_batch1, x_batch2)
test()
```
test code sample taken from @dusenberrymw

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by mrry** [comment]
When you call `tf.reset_default_graph()`, it resets the seed. If you call `tf.set_random_seed(42` after `tf.reset_default_graph()` the result is deterministic as expected.
