### ISSUE TITLE
TensorFlow automatically modify variable scope name

### ISSUE THREAD

**Issue by FesianXu** [tensorflow/tensorflow#15575]
check the following code:

```python
with tf.variable_scope('test'):
      v1 = tf.placeholder(tf.float32, shape=(10,10), name='v1')

with tf.variable_scope('test'):
      v2 = tf.placeholder(tf.float32, shape=(5, 5), name='v2')

print(v1)
print(v2)
```

the code output:

 ```python
Tensor("test/v1:0", shape=(10, 10), dtype=float32)
Tensor("test_1/v2:0", shape=(5, 5), dtype=float32)
```

It looks ridiculous for TF modfiy variable scope name 'test' into 'test_1' while my new placeholder named 'v2' is different from 'v1'. However, if i add variables, everything is going to be normal. code like:

```python
    with tf.variable_scope('test'):
        v1 = tf.placeholder(tf.float32, shape=(10,10), name='v1')
        w1 = tf.get_variable('w1', shape=(2,2))

    with tf.variable_scope('test'):
        v2 = tf.placeholder(tf.float32, shape=(5, 5), name='v2')
        w2 = tf.get_variable('w2', shape=(3, 3))
    print(v1)
    print(v2)
    print(w1)
    print(w2)
```
outputs:
```python
Tensor("test/v1:0", shape=(10, 10), dtype=float32)
Tensor("test_1/v2:0", shape=(5, 5), dtype=float32)
<tf.Variable 'test/w1:0' shape=(2, 2) dtype=float32_ref>
<tf.Variable 'test/w2:0' shape=(3, 3) dtype=float32_ref>
```

I dont know why TF **just modify the variable scope name** while i try to add a new placeholder into the existed scope.Is it a BUG?

**Comment by facaiy** [comment]
If you want to reenter a variable scope, use 
```python
with tf.variable_scope('test') as scope:
    v1 = tf.placeholder(tf.float32, shape=(10,10), name='v1')
    w1 = tf.get_variable('w1', shape=(2,2))

with tf.variable_scope(scope) as scope2:
    with tf.name_scope(scope2.original_name_scope):
         v2 = tf.placeholder(tf.float32, shape=(5, 5), name='v2')
         w2 = tf.get_variable('w2', shape=(3, 3))
```

This posts below perhaps are useful for you:
+ [What's the difference of name scope and a variable scope in tensorflow?](https://stackoverflow.com/questions/35919020/whats-the-difference-of-name-scope-and-a-variable-scope-in-tensorflow)
+ [ Sharing Variables ](https://www.tensorflow.org/versions/r0.12/how_tos/variable_scope/)
+ [ TensorBoard: Graph Visualization ](https://www.tensorflow.org/get_started/graph_viz)

**Comment by FesianXu** [comment]
Well, it does work! Thanks for you help and answer

**Comment by shiv-gpt** [comment]
What if i need to do this in the case where i have a scope inside a scope? `Your method works for the outermost scope but TF still automatically renames the variables for the scopes inside.
