### ISSUE TITLE
Cyclic dependency error on build

### ISSUE THREAD

**Issue by chemelnucfin** [tensorflow/tensorflow#1558]
On my laptop, I get a cyclic dependency error

### Environment info
Operating System: Ubuntu 15.10

If installed from sources, provide the commit hash:
fd464caaa40cfa16c81712939e39bd14d88c6fd4 (most recent HEAD as of this submission)

google protobuf commit
fb714b3606bd663b823f6960a73d052f97283b74

bazel version 
Build label: 0.1.5
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Feb 9 19:15:13 2016 (1455045313)
Build timestamp: 1455045313
Build timestamp as int: 1455045313

### Steps to reproduce
1.  bazel test tensorflow/...  or bazel build -c opt //tensorflow/cc:tutorials_example_trainer

### What have you tried?
1.  trying to go through the chain of protobuf dependencies, but pointers would be appreciated.
2.  tried HEAD on protobuf

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
../../bin/bazel build //tensorflow/cc:tutorials_example_trainer
____Loading...
ERROR: /projects/tensorflow/google/protobuf/BUILD:272:1: in cc_binary rule //google/protobuf:protoc: cycle in dependency graph:
    //tensorflow/cc:tutorials_example_trainer
    //tensorflow/core:tensorflow
    //tensorflow/core:tensorflow_opensource
    //tensorflow/core:core
    //tensorflow/core:core_cpu
    //tensorflow/core:core_cpu_internal
    //tensorflow/core:framework_internal
    //tensorflow/core/kernels:bounds_check
    //tensorflow/core:lib
    //tensorflow/core:lib_internal
    //tensorflow/core:protos_all_cc
    //tensorflow/core:framework/function.pb.h
    //tensorflow/core:protos_all_cc_genproto
  * //google/protobuf:protoc
    //google/protobuf:protoc_lib
    //google/protobuf:protobuf
    //google/protobuf:src/google/protobuf/map_lite_unittest.pb.h
    //google/protobuf:cc_test_protos_genproto
  * //google/protobuf:protoc.
ERROR: Loading of target '//tensorflow/cc:tutorials_example_trainer' failed; build aborted.
ERROR: Loading failed; build aborted.

**Comment by cg31** [comment]
I got the same error today. It seems protobuf is messed up.

I fixed it by cleaning and updating it:

git submodule foreach git clean -dfx
git submodule update

**Comment by chemelnucfin** [comment]
Worked great!

**Comment by girving** [comment]
Closing, since @cg31 seems to have found the fix.  Thanks!
