### ISSUE TITLE
TfLiteCameraDemo only contains 32-bit libtensorflowlite_jni.so

### ISSUE THREAD

**Issue by benshi001** [tensorflow/tensorflow#15581]
I strictly followed the steps on https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/ to
build the TfLiteCameraDemo. But I found only 32-bit libtensorflowlite_jni.so was contained in the final APK.

I modified the source code of libneuralnetworks.so to test my employer's NN accelerator, which needed the 64-bit libtensorflowlite_jni.so.

even I configed bazel with
./configure --config=android_arm64

and built with 
bazel build --cxxopt=--std=c++11 --cpu=arm64-v8a //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo

could not work.

Where was my mistake? Or how can I pack the 64-bit  libtensorflowlite_jni.so into the final APK?

**Comment by benshi001** [comment]
BTW:
1. I made many changes in both java and c, and they run normally with the 32-bit libtensorlite_jni.so/libneuralnetworks.so
2. I did an extreme attempt,
cd /home/benshi001
grep armeabi-v7a * -r
then remove all lines with armeabi-v7a
but the bazel build still invoke armeabi-v7a build procedure

**Comment by bignamehyp** [comment]
@aselle

**Comment by aselle** [comment]
@angersson ,could you please take a look?

**Comment by angersson** [comment]
I confirmed this by building with `bazel --config=android_arm64`, unpacking the .APK, and using the `file` command (note the armeabi-v7a directory):

```
lib/armeabi-v7a/libtensorflowlite_jni.so: ELF 32-bit LSB  shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
```

The internal version of the build with the same commands contains `arm64-v8a/libtensorflowlite_jni.so`, a 64-bit ELF file.

I'll check to see if there's an easy fix.

**Comment by angersson** [comment]
From #9060, you can build the correct 64-bit library by setting the `--fat_apk_cpu=arm64-v8a` flag. 

```shell
bazel build --cxxopt=--std=c++11 //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo --config=android_arm64 --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
```

**Comment by angersson** [comment]
I've submitted an internal change that adds --fat_apk_cpu=... when using --config=android_arm{,64}. Once it gets synced, we shouldn't see this particular problem much any more.

**Comment by benshi001** [comment]
Thank you so much!
