### ISSUE TITLE
upgrade tensorflow 1.4 from 1.2，get undefined symbol:error

### ISSUE THREAD

**Issue by yogurfrul** [tensorflow/tensorflow#15582]
I import c++ api of concat op
and  add  "//tensorflow/core/kernels:concat_lib_hdrs", to the deps
my code work ok based on tf1.2 .
when I upgrade tf to 1.4 ,compile and install is ok.
when I run my model ,I got the error as :

Traceback (most recent call last):
  File "/home/my_work/.cache/bazel/_bazel_my_work/ce8941cb5767b65fdf1825ce866fc372/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/own_concat/own_concat_ops_test.runfiles/org_tensorflow/tensorflow/contrib/own_concat/python/ops/own_concat_ops_test.py", line 5, in <module>
    from tensorflow.contrib import own_concat
  File "/home/my_work/.cache/bazel/_bazel_my_work/ce8941cb5767b65fdf1825ce866fc372/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/own_concat/own_concat_ops_test.runfiles/org_tensorflow/tensorflow/contrib/own_concat/__init__.py", line 19, in <module>
    from tensorflow.contrib.own_concat.python.ops.own_concat_ops import *
  File "/home/my_work/.cache/bazel/_bazel_my_work/ce8941cb5767b65fdf1825ce866fc372/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/own_concat/own_concat_ops_test.runfiles/org_tensorflow/tensorflow/contrib/own_concat/python/ops/own_concat_ops.py", line 11, in <module>
    resource_loader.get_path_to_datafile('_own_concat_ops.so'))
  File "/home/my_work/.cache/bazel/_bazel_my_work/ce8941cb5767b65fdf1825ce866fc372/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/own_concat/own_concat_ops_test.runfiles/org_tensorflow/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/my_work/.cache/bazel/_bazel_my_work/ce8941cb5767b65fdf1825ce866fc372/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/own_concat/own_concat_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/my_work/.cache/bazel/_bazel_my_work/ce8941cb5767b65fdf1825ce866fc372/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/own_concat/own_concat_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/my_work/.cache/bazel/_bazel_my_work/ce8941cb5767b65fdf1825ce866fc372/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/own_concat/own_concat_ops_test.runfiles/org_tensorflow/tensorflow/contrib/own_concat/python/ops/_own_concat_ops.so: undefined symbol: _ZN10tensorflow9ConcatCPUIfEEvPNS_10DeviceBaseERKSt6vectorISt10unique_ptrINS_6TTypesIT_Li2ElE11ConstMatrixESt14default_deleteIS8_EESaISB_EEPNS7_6MatrixE

**Comment by allenlavoie** [comment]
Not totally clear to me what you're doing, but custom ops need to be linked again libtensorflow_framework.so in 1.4. See the [updated custom op instructions](https://www.tensorflow.org/versions/master/extend/adding_an_op#build_the_op_library). If you're building the custom op with Bazel, use tf_custom_op_library/tf_kernel_library/tf_cc_binary instead of the default Bazel rules (take a look at [contrib/boosted_trees](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/boosted_trees/BUILD) for example).

**Comment by yogurfrul** [comment]
thanks for your reply ,I build my custom op with Bazel
 here is my BUILD

tf_custom_op_library(
    name = "python/ops/_ddn_ops.so",
    srcs =  glob([
        "kernels/own_concat.cc",
        "ops/own_concat.cc",
        ],
        exclude = [
        "**/*test.cc",
        ],
    ),
    deps = [
        "//tensorflow/core:protos_all_cc",
        "//tensorflow/core/kernels:ops_util_hdrs",
        "//tensorflow/core/kernels:split_lib_hdrs",
        "//tensorflow/core/kernels:concat_lib_hdrs",
    ],
)
and I
`#include "tensorflow/core/kernels/concat_lib.h"
namespace tensorflow {
template <typename T>
void Concat(OpKernelContext* c, const gtl::ArraySlice<Tensor>& inputs, int32 concat_dim,Tensor* output) {
*******some preprocess code******
ConcatCPU<T>(c->device(), inputs_flat, &output_flat);
};
}`

it works based on tensorflow 1.2,and I can use own_concat op api rightlly
when I upgrade tenforflow version to 1.4 I get the error undefined symbol:error
something of tensorflow BUILD or custom op BUILD changed ?\
However I compare the source codes of two version,I don't find any clues

**Comment by yogurfrul** [comment]
ldd my _own_concat_ops.so output is different between 1.2 and 1.4:
1.4:
`ldd  bazel-out/local-opt/bin/tensorflow/contrib/own_concat/own_concat_ops_test.runfiles/org_tensorflow/tensorflow/contrib/own_concat/python/ops/_own_concat_ops.so
        linux-vdso.so.1 =>  (0x00007fffb29fe000)
        libachk.so => /lib/libachk.so (0x00007f6cfd1cf000)
        libtensorflow_framework.so => /home/yogur/new_TF/tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/own_concat/own_concat_ops_test.runfiles/org_tensorflow/tensorflow/contrib/own_concat/python/ops/../../../../../_solib_k8/_U_S_Stensorflow_Scontrib_Sown_concat_Cpython_Sops_S_Uown_concat_Uops.so___Utensorflow/libtensorflow_framework.so (0x00007f6cfc5d8000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6cfc2d2000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6cfbfce000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6cfbdb8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6cfb9f2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6cfd331000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6cfb7ee000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6cfb5d0000)`
+++++++++++++++++++++++++++++++++++++++
1.2:
`ldd bazel-out/local-opt/bin/tensorflow/contrib/own_concat/own_concat_ops_test.runfiles/org_tensorflow/tensorflow/contrib/own_concat/python/ops/_own_concat_ops.so
        linux-vdso.so.1 =>  (0x00007fff513fe000)
        libachk.so => /lib/libachk.so (0x00007f12a467f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f12a4379000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f12a415b000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f12a3e57000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f12a3c41000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f12a387b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f12a4d1a000)`

**Comment by allenlavoie** [comment]
Oh I see, you're relying on symbols which are now hidden from custom ops (we moved core kernels to the language bindings). You can build with --config=monolithic to get the old behavior. You could also explicitly link against _pywrap_tensorflow_internal.so for that symbol.

Or just copy the code you need from concat_lib_cpu.cc? It looks like there are only a few lines which call into other libraries. You'd just need to avoid the kernel registrations.

**Comment by yogurfrul** [comment]
:+1: 
When I get your latest reply ,I have tried copy the source code from concat_lib_cpu.cc to my own code，
it do works~
After I see your reply，I tried build with  --config=monolithic ，it also works~
I ended up choosing the copy code  method to prevent unknown changes of the dependent code

thank you very much！！

**Comment by allenlavoie** [comment]
Awesome, glad it worked.
