### ISSUE TITLE
lite model file size

### ISSUE THREAD

**Issue by xuelinchao** [tensorflow/tensorflow#15587]
how to reduce my model size(my own trained tensorflow model )
i want to use tensorflow lite converter get a smaller tflite file, but the tflite file has the same size with my trained model,
-------------------------------------------------------------------------

bazel-bin/tensorflow/contrib/lite/toco/toco \
  --allow_custom_ops \
  --input_file=/data/log/frozen_model.pb --input_format=TENSORFLOW_GRAPHDEF  --output_format=TFLITE \
  --output_file=/data/log//mobilenet.tflite --inference_type=FLOAT \
  --input_data_types=FLOAT --input_arrays=input \
  --output_arrays=output --input_shapes=1,224,224,3

--------------------------------------------------------------------------

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
