### ISSUE TITLE
Add name scopes (op_scopes) to tf.image ops so they look nice in TensorBoard

### ISSUE THREAD

**Issue by ecobost** [tensorflow/tensorflow#1560]
For instance, this:

```
image = tf.image.decode_png(tf.read_file("image.png"))
whitened_image = tf.image.per_image_whitening(image)
```

produces this:
![screenshot from 2016-03-19 19 33 06](https://cloud.githubusercontent.com/assets/9740006/13902377/f7b47c6a-ee0a-11e5-8ee4-06161b7ceaf1.png)
instead of something like this:
![screenshot from 2016-03-19 19 37 56](https://cloud.githubusercontent.com/assets/9740006/13902386/61696c38-ee0b-11e5-9230-9410c11a3fb1.png)

I know we can create the name scopes (that's how I generated the image) but it should probably be default behaviour.

**Comment by danmane** [comment]
Thanks for filing this with a clear example and description of the issue! :+1:  If you feel like taking this on yourself and submitting a pull request, that would be very welcome

**Comment by jameswex** [comment]
This issue is being worked on by Martin Wicke

**Comment by martinwicke** [comment]
Except, I never got to it. It is still contributions welcome. Since these ops do not create variables, the name_scopes can be safely inserted without concerns about backwards compatibility.

**Comment by martinwicke** [comment]
It's likely still valid. A PR adding name scopes consistently would be
welcome!
