### ISSUE TITLE
Cannot compute output tensor of tf.keras.layers.Lambda + tf.unstack

### ISSUE THREAD

**Issue by kzm4269** [tensorflow/tensorflow#15627]
### System information
- **Have I written custom code**: Yes
- **OS Platform and Distribution**: Ubuntu 16.04
- **TensorFlow installed from**: binary
- **TensorFlow version**: tf-nightly 1.5.0-dev20171224
- **Python version**: 3.5.4

### Source code

This is a tiny code that creates a model which stacks and unpacks input tensors.

```python
import tensorflow as tf
from tensorflow.python import keras

x = [keras.layers.Input([2]) for _ in range(3)]
h = keras.layers.Lambda(lambda inputs: tf.stack(inputs, axis=1))(x)
y = keras.layers.Lambda(lambda inputs: tf.unstack(inputs, axis=1))(h)

model = keras.models.Model(x, y)
model.compile('adam', 'mse')
```

This code raises a `AssertionError`.

```
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    model.compile('adam', 'mse')
  File ".../tf-nightly/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 681, in compile
    masks = self.compute_mask(self.inputs, mask=None)
  File ".../tf-nightly/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 787, in compute_mask
    _, output_masks = self._run_internal_graph(inputs, masks)
  File ".../tf-nightly/lib/python3.5/site-packages/tensorflow/python/layers/network.py", line 927, in _run_internal_graph
    assert str(id(x)) in tensor_map, 'Could not compute output ' + str(x)
AssertionError: Could not compute output Tensor("lambda_1/unstack:1", shape=(?, 2), dtype=float32)
```

**Comment by kzm4269** [comment]
I found that this is an error that occurs when the number of outputs of `Layer.output_masks()` does not match the number of outputs of `Layer.call()`.

**Comment by applenob** [comment]
Can you give some hint about how to debug with this error message: "assert str(id(x)) in tensor_map, 'Could not compute output ' + str(x)"? It troubles me too, and I can't find what's wrong.

**Comment by ningyanuta** [comment]
_run_internal_graph() forget to put all outputs in tensor_map. I encounter this in TF1.4, but looks like it is fixed in TF1.8.
