### ISSUE TITLE
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory with python 2.7

### ISSUE THREAD

**Issue by Gagazet** [tensorflow/tensorflow#15634]
Ubuntu 16.04
GPU: 1080 Ti
Cuda 9.0
CuDDN 7.0 v7
Using my PC, not a VM
Installed Intel MKL-DNN by this [guilde](https://github.com/mind/wheels#mkl), but looks like something wrong, because when trying to make a test for tensorflow, got error:

```
gagazet@woof:~/Desktop$` python 123.py 
Traceback (most recent call last):
  File "123.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

Recently someone created same problem and it was closed with reason: PR [#12975](https://github.com/tensorflow/tensorflow/pull/12975), but it was for a VM.
Can anyone explain, please, what i can be and how to fix it? Dont have any build_pip_package scrips at the TF folder. 
Its doesnt looks like same problem as PR [#12975](https://github.com/tensorflow/tensorflow/pull/12975)

**Comment by asimshankar** [comment]
Seems like the linker cannot find `libmklml_intel.so` so it's like some linker configuration or MKL installation issue.

FYI @tfboyd in case he has other suggestions.

**Comment by asimshankar** [comment]
The error message suggests a linker configuration or MKL installation issue. Does `libmkl_intel.so` exist on your filesystem and is it available to the linker? (You might get some clues from `ldd /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so`)

FYI @tfboyd in case he has other suggestions.

However, since the distribution (`.whl` file) you're using is not something maintained by the TensorFlow team, but rather maintained by TinyMind in their github project at https://github.com/mind/wheels - I'm going to suggest that you seek help there.
