### ISSUE TITLE
tf.name_scope does not work with tf.layers

### ISSUE THREAD

**Issue by aybberk** [tensorflow/tensorflow#15630]
When I define a layer with
```
with tf.name_scope("MY_SCOPE"):
    layer1 = tf.layers.dense(inputs = X,
                             units = 100,
                             kernel_initializer = he_init,
                             activation = tf.nn.elu,
                             name = "layer1")


```

and try to get its variables with

`tf.global_variables(scope="MY_SCOPE")`

it returns nothing because name scope did not apply to the layers from tf.layers

Shouldn't their name be

[<tf.Variable 'MY_SCOPE/layer1/kernel:0' shape=(784, 100) dtype=float32_ref>,
 <tf.Variable 'MY_SCOPE/layer1/bias:0' shape=(100,) dtype=float32_ref>]

instead of

[<tf.Variable 'layer1/kernel:0' shape=(784, 100) dtype=float32_ref>,
 <tf.Variable 'layer1/bias:0' shape=(100,) dtype=float32_ref>]

so that I can use my scope to reach my layers? This works with everything but tf.layers module.

**Comment by facaiy** [comment]
Hi, @aybberk . 
Because `name_sconpe` is only for operations, you should use `tf.variable_scope("MY_SCOPE") which is designed for variables. 

You might be interested on the post: [What's the difference of name scope and a variable scope in tensorflow?](https://stackoverflow.com/questions/35919020/whats-the-difference-of-name-scope-and-a-variable-scope-in-tensorflow)

**Comment by asimshankar** [comment]
Thanks for the response @facaiy

**Comment by facaiy** [comment]
@asimshankar Would it be a good idea if TensorFlow could explain the two scopes in the official site in details? This is not the first time when I found people confuse `tf.name_scope` with `tf.variable_scope`.

**Comment by PiotrCzapla** [comment]
@asimshankar  I'd like to second @facaiy here, I would love to see explanation in the docs, it would save me quite some time today.
