### ISSUE TITLE
[Solved, please close it] cuda 7.5 and tensorflow 0.7.1 error: cuda_gpu_executor.cc could not open file to read NUMA node

### ISSUE THREAD

**Issue by jialrs** [tensorflow/tensorflow#1563]
Hi, when test tensorflow after installation, I get the titled error.

>cuda_gpu_executor.cc  could not open file to read NUMA node: /sys/bus/pci/devices/0000:00:00.0/numa_node

In fact my cuda toolkit runs properly, and I can run all samples in it.
When run `import tensorflow as tf` and `hello = tf.constant('Hello, TensorFlow!')`, nothing is wrong and cuda libs can be found and loaded by tensorflow.

 BTW, my GPU is *GTX 980TI* and my os is *Slackware current 64*. Latest driver is installed.

Thanks.

**Comment by jialrs** [comment]
I find my kernel doesn't support NUMA. I solve this error after recompile.

**Comment by vrv** [comment]
I think this is a benign error, we'll try to maybe remove it.

@leary-google
