### ISSUE TITLE
Does  custom Op run slower than inner Op?

### ISSUE THREAD

**Issue by MisayaZ** [tensorflow/tensorflow#1564]
l want to incorporate an operation that isn't covered by the existing library, so I create a custom Op.
Howerver it run slowly. Does  custom Op run slower than inner Op? I have test on it by adding an new Op to do the same thing as matmul Op, the result is that the new op run slower than the exist matmul Op.

**Comment by sherrym** [comment]
The performance is completely dependent on the implementation of your custom op.

**Comment by MisayaZ** [comment]
@sherrym  the implementation of my custom op is exactly same as the matmul op, however the performance is different.

**Comment by TaoMiner** [comment]
I am confused with the same problem too. have you found a solution? 
I guess the only way is to adopt the second method to add a new op in the tutorial, that is, with the tensorflow source install via bazel, but the recompile process is too slow.
