### ISSUE TITLE
contrib/all_reduce not update to latest nccl

### ISSUE THREAD

**Issue by anpark** [tensorflow/tensorflow#15642]
send_op, dst_tensors = nccl.broadcast(level_2_output[w], dst_devices)

this line is out of date, hope update to latest

**Comment by anpark** [comment]
this file's op not support IndexedSlices Gradient,  such as flatten_tensor 
hope someone can help, thanks!

**Comment by anpark** [comment]
@jlebar @taehoonlee can you help? thanks

**Comment by skye** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by anpark** [comment]
@skye  thank you for the reply.
my question just relate to contrib/all_reduce  module, my version is tf-1.4 + tf_cnn_benchmark-nighty, i checked that it doesn't matter to build env which i use.

 i use tf_cnn_benchmark with distributed_all_reduce + nccl which depends contrib/all_reduce.  but contrib/all_reduce uses nccl version that is older than contrib/nccl, that's not updated to latest nccl

it's same as #15425 

thanks.
