### ISSUE TITLE
Tensorflow.org - master version is not updated

### ISSUE THREAD

**Issue by mtngld** [tensorflow/tensorflow#15647]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Not Relevant
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Not Relevant
- **TensorFlow installed from (source or binary)**: Not Relevant
- **TensorFlow version (use command below)**: Not Relevant
- **Python version**: Not Relevant
- **Bazel version (if compiling from source)**: Not Relevant
- **GCC/Compiler version (if compiling from source)**: Not Relevant
- **CUDA/cuDNN version**: Not Relevant
- **GPU model and memory**: Not Relevant
- **Exact command to reproduce**: Not Relevant

### Describe the problem
tensorflow.org master version should be updated to master, however it seems that it hasn't been regenerated for a while.

For example the latest addition of the performance guide for `tf.data` (https://github.com/tensorflow/tensorflow/commit/ba32ea1547af74d549f35a42e4de83c88652a636) hasn't yet made it to the website:

Doc source: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/performance/performance_guide.md

Generated web page in tensorflow.org (master version):
https://www.tensorflow.org/versions/master/performance/performance_guide

(Currently shows "Last updated November 14, 2017." in the bottom)

**Comment by bignamehyp** [comment]
@gunan

**Comment by gunan** [comment]
@av8ramit @MarkDaoust @wolffg

**Comment by MarkDaoust** [comment]
Fixed (manually).
