### ISSUE TITLE
CUDA 9.1 and TensorFlow

### ISSUE THREAD

**Issue by harimaruthachalam** [tensorflow/tensorflow#15656]
I am using NVIDIA GeForce GTX 1050 and installed NVIDIA 387.26. I installed cuDNN 7.0.5 and CUDA 9.1. As of my understanding, I know that, tensorflow is not supported in CUDA 9.1. My question is when I can expect the next build/release of TF to support CUDA 9.1. For the time being, shall I make a link from CUDA 9.0 to CUDA 9.1 and expect to work? Or is there any better way to solve the problem?

**Comment by asimshankar** [comment]
@gunan @av8ramit @case540 may have some information, especially relevant to the upcoming 1.5 release.

**Comment by gunan** [comment]
will be 1.6.
1.5 is building with 9.0

**Comment by av8ramit** [comment]
tf-nightly-gpu latest should also work with CUDA 9.0

**Comment by jonghyunc** [comment]
@av8ramit Is it a branch or tag name? I couldn't find it.

**Comment by av8ramit** [comment]
@jonghyunc r1.5 is the branch name. The tag hasn't been released yet as we are still creating rc0.

**Comment by jonghyunc** [comment]
@av8ramit Thank you! Will try r1.5 for running tf on cuda 9.1

**Comment by jonghyunc** [comment]
@av8ramit tf-nightly-gpu is built on cuda 9.0. Do you have a version that is built with cuda 9.1?

**Comment by av8ramit** [comment]
We are still working kinks out with cuda 9.1 Once that goes into master tf-nightly-gpu will automatically be built with 9.1 @gunan might have more information

**Comment by jonghyunc** [comment]
Thank you @av8ramit for the update! @gunan Do you have a rough idea when the version with cuda 9.1 is going to be ready?

**Comment by gunan** [comment]
It wont be ready until we release 1.5 final. That would be at least a month away.
But building from sources with cuda 9.1 should work just fine.

**Comment by jonghyunc** [comment]
@gunan Got it! Thanks!

**Comment by Gongfeng-LI** [comment]
Try this:  https://drive.google.com/open?id=1WdlN-NRlXQWIJrDAlw9aum7ooxI_-A4L
Cuda9.1 wheel with tensorflow v1.4.1

**Comment by samuelBB** [comment]
@jonghyunc @gunan Can confirm that building TF 1.5 from source with CUDA 9.1 and cuDNN 7.0.5 works fine on Ubuntu 16.04. Works fine for both python 2.7.12 and 3.5.2. Just built today from TF master (latest). A few weird warnings here and there during building and when I run a program, but runs fine. Haven't done any benchmarking yet.

**Comment by gunan** [comment]
I have not built myself but @reedwm or @tfboyd may be able to confirm.
Since 9.1 is a minor release, I would expect anything that works with 9.0 to work with 9.1.

**Comment by jonghyunc** [comment]
@samuelBB I've successfully built TF 1.5 from source (branch r1.5, a week ago, before they release the 1.5 in the master branch) with CUDA 9.1 and cuDNN 7.0.5 on Ubuntu 16.04; can train a network and performs inference. Tested on Titan V, Titan Xp, and Titan X and had no problem.

**Comment by samuelBB** [comment]
@gunan @jonghyunc Ah, I think I was unclear in my comment. I meant to say that *I can confirm...* as in I was able to successfully do the things described in my comment. I edited my above comment.

**Comment by zhang-yf** [comment]
Hi noob here, how would I build from source? is there a guide? I don't quite understand what it means to built from source and I've just spent entire day finding this post as I'm stuck on this specific issue. ... thanks 😄

**Comment by samuelBB** [comment]
I found this to be a very good guide when I was building from source: http://www.python36.com/install-tensorflow141-gpu/
The guide is for TF1.4 and CUDA9.1 but equally applies with TF1.5 or other combinations; just make sure to specify the correct files and version numbers. Cheers.

**Comment by av8ramit** [comment]
@zhang-yf maybe [this](https://www.tensorflow.org/install/install_sources) will also help?

**Comment by navneethc** [comment]
Could someone tell how to find the exact version of the dependencies used in the binaries? I assumed 9.1 was fine for 1.5 RC0, but it didn't work (in Windows; cf. #16014 ), so I had to spend a while un- and re-installing stuff.

**Comment by zhang-yf** [comment]
Thanks @samuelBB  and @av8ramit, I see now I just needed to specify the Cuda sdk version to be 9.1 while building from source. That seems straightforward. I was wondering would it be possible to write a script so that while installing through  pip it will just grab the 9.x version since it makes no difference the minor release version in this case. Also @navneethc  you have the same problem which lead me here, if you check the log when importing tensorflow it says it tries to find the 9.0 and it couldnt find the cudart64_90.dll because the cuda 9.1 have the cudart64_91.dll instead. Which is why im going to re install cuda 9.0 😆

**Comment by navneethc** [comment]
Yes, thankfully I’m past all that and running TF (that’s where the the uninstalls and reinstalls happened:) ). I’m now requesting a reference for the future. :D

**Comment by abntu** [comment]
couda older version(CUDA 9):
https://developer.nvidia.com/cuda-toolkit-archive

**Comment by gunan** [comment]
Just to update, after discussing with nvidia, and our team we decided to stay with cuda 9.0 for 1.6 release.

**Comment by farhanhubble** [comment]
Is there a way to print out all Cuda dependencies for Tensorflow, before building from source? I just built tensorflow master with Cuda 9.1 and now Tensorflow complains about **libcusolver.so.8** not being present, because I have  **libcusolver.so.9**. It must be that the version of **libcusolver.so** changed from 8 in Cuda 9.0 to 9 in Cuda 9.1.

**Comment by kreegah** [comment]
Will there be a cuda 9.1-compatible version?  :(

And why did you avoid cuda 9.1? Technical issues?

**Comment by gunan** [comment]
As indicated just one comment above, this is a decision after we discussed with NVIDIA.
The answer to why is driver issues in the ones required by 9.1, not many new features we need in cuda 9.1, and a few more minor issues. 1.7 is also building right now with CUDA 9.0

**Comment by kreegah** [comment]
Ok thanks for replying.

**Comment by josephnunn** [comment]
As far as I know Volta optimizations are only in 9.1, like CuBLAS for Volta etc, and the use of the tensor cores.  I guess nobody is using Tesla V100 or the Titan V with tensorflow so its not important...

**Comment by John1231983** [comment]
I am using cuda 6.1 and cudnn 7.0. Could we use tensorflow-1.6 build from pip? If not, how about build from source?

**Comment by zhzhao870303** [comment]
Followed the instructions in this link to build tensorflow with cuda 9.1 (cuDNN 7.1). Now everything works fine for me. http://www.python36.com/install-tensorflow-gpu-windows/

**Comment by michaelklachko** [comment]
Tensorflow 1.7RC1 is out, but the CUDA version is not specified. Is CUDA 9.1 now supported?

**Comment by rushatrai** [comment]
@michaelklachko have you tried installing with 9.1 yet? If so, could you please post the results?

**Comment by hitvoice** [comment]
Building from source with 9.1 works fine for me.

**Comment by erolrecep** [comment]
@hitvoice  Which version of tensorflow did you build from source? Also, which operating system do you use?

**Comment by hitvoice** [comment]
@erolrecep 1.7.0, on Ubuntu Server 16.04

**Comment by boyangwm** [comment]
@hitvoice @erolrecep Can you post the whl files?

**Comment by Oldpan** [comment]
@hitvoice Me too,can you give a download page for  the whl files?

**Comment by hitvoice** [comment]
@boyangwm @Oldpan @erolrecep Hope it helps.

- [tensorflow-1.7.0-cp36-cp36m-linux_x86_64.whl](https://drive.google.com/open?id=15iGFiagWcwTSzJMpOxYvRad-yKGjTB9J)
- [tensorflow-1.8.0rc0-cp36-cp36m-linux_x86_64.whl](https://drive.google.com/open?id=1xqHxMrsGQLsZhT0XMBfmJsccjFpJtXa5)

Environment:
- python 3.6
- Ubuntu Server 16.04
- CUDA 9.1, CUDNN 7.1, both in `usr/local/cuda`
- for tf1.8.0rc0, NCCL2.1 is in `/usr/local/nccl_2.1.15-1+cuda9.1_x86_64` (NCCL 2.1.15 O/S agnostic)

**Comment by Oldpan** [comment]
@hitvoice Thanks, man!

**Comment by Oldpan** [comment]
@hitvoice 
Dude,I try your whl file 'tensorflow-1.7.0-cp36-cp36m-linux_x86_64.whl' just now but I still get a wrong message: "libcublas.so.9.1: cannot open shared object file: No such file or directory".And I have no idea.
I built a same whl before and the build process is right and then I got a same problem.So I tried yours.But it still doesn't work.Maybe some configuration in my system doesn't fit?

My environment:
- Cuda compilation tools, release 9.1, V9.1.85
- cudnn:7.1.2
- nvidia-driver:390.48
- card:1080ti

**Comment by Oldpan** [comment]
@boyangwm I'll take a look at this repository,hope this will save my time.

**Comment by hitvoice** [comment]
@Oldpan Does the file `/usr/local/cuda/lib64/libcublas.so.9.1` exist on your machine?

**Comment by StevenGann** [comment]
Just wanted to remind you guys that it's been a while and CUDA 9.1 still isn't supported, even by the nightly build.

This means I still can't use TensorFlow because my system requires CUDA 9.1 for another purpose. I hope this can be fixed soon.

**Comment by bersbersbers** [comment]
@StevenGann I am running TensorFlow on a system that has CUDA 8, 9.0 and 9.1 installed, with TensorFlow using 9.0. It works. So you can have CUDA 9.1 installed "for another purpose" and still use TensorFlow.

**Comment by StevenGann** [comment]
@bersbersbers This doesn't seem to be the case. When I attempt to install CUDA 9.0, the installation runs but it only updates 9.1's installation. The Nvidia installer does not permit me to install 9.0 as long as 9.1 is installed.

Also, it seems fairly lazy to stick with an outdated library version and require people to uninstall and reinstall drivers, especially when the newer version was supposed to be supported months ago. Is there a technical reason why TensorFlow's developers can't figure out how to use 9.1?

**Comment by bersbersbers** [comment]
@StevenGann I am almost certain that I installed 9.0 after 9.1 (I think I did 9.1, 8.0, 9.0 until I got it working). That was in Windows 10. Anyway, uninstalling 9.1 and installing 9.0, followed by 9.1 looks like it should work?

**Comment by rushatrai** [comment]
@StevenGann if you build from sources, I believe you can use CUDA 9.1 as it asks for the CUDA version you want to build with.

**Comment by billti** [comment]
Just seconding what a pain this is. The CUDA link on the page at https://www.tensorflow.org/install/install_windows will end you up at https://developer.nvidia.com/cuda-downloads . This ONLY shows 9.1 now. You need to go into the "Legacy releases" area to get 9.0. I spent forever waiting for that GB install of 9.1 only to then hit this problem.

I resolved it by installing using the "network" install from https://developer.nvidia.com/cuda-90-download-archive , and doing a custom install of only the runtime libraries, then ensuring `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin` was on my path. That got me working in a few mins and is fine side-by-side with 9.1).

**Comment by faintedremix** [comment]
Are there plans for tensorflow to upgrade to CUDA v9.1?

**Comment by mikaelfs** [comment]
While waiting for the official release of TensorFlow with CUDA 9.1, [here is another attempt](http://tech.amikelive.com/node-746/guide-installing-tensor-flow-1-8-with-gpu-support-against-cuda-9-1-and-cudnn-7-1-on-ubuntu-16-04/) to describe how TensorFlow 1.8 can be built against CUDA 9.1.

The final system configuration will be:

- OS: Ubuntu 16.04
- CUDA version: 9.1
- cuDNN version: 7.1.3
- NCCL version: 2.1.15
- Python version: 2.7.12
- Python install method: virtualenv
- TensorFlow version: 1.8.0

Troubleshooting for common errors is also added in [the article content](http://tech.amikelive.com/node-746/guide-installing-tensor-flow-1-8-with-gpu-support-against-cuda-9-1-and-cudnn-7-1-on-ubuntu-16-04/). I found out that the build process was smooth like sailing a calm ocean (alternative meaning: it can be drowsy to wait for the build to complete).

**Comment by TengliEd** [comment]
Which cuda version can tf-nightly-1.9.0 work with? 
My system configuration:
- OS:Ubuntu 16.04
- Python version 3.6

**Comment by tarfeef101** [comment]
Still waiting on actual support because not everyone can build from sources. I, for example, need it in a conda environment which is created in Docker (and therefore can't be activated to build then switched back to the root environment for the rest of the build tasks). 

Given the feedback here in this comment chain, it shouldn't be a lot of work to ship a 9.1 compatible version. Hell give me a week with access to the relevant parts of your deployment chain and I'll do it! I just need this to be a thing.

**Comment by navneethc** [comment]
> Still waiting on actual support because not everyone can build from sources. I, for example, need it in a conda environment which is created in Docker (and therefore can't be activated to build then switched back to the root environment for the rest of the build tasks).
> 
> Given the feedback here in this comment chain, it shouldn't be a lot of work to ship a 9.1 compatible version. Hell give me a week with access to the relevant parts of your deployment chain and I'll do it! I just need this to be a thing.

If it helps, Anaconda offers its own packaged version of Tensorflow compiled with CUDA 9.2. And supposedly it's faster than pip-installed TF.

https://www.anaconda.com/tensorflow-in-anaconda/
