### ISSUE TITLE
MNIST dataset - gzip: train-images-idx3-ubyte.gz: not in gzip format

### ISSUE THREAD

**Issue by aselle** [tensorflow/tensorflow#15668]
initiated from tensorflow-discuss From: greina@eng.ucsd.edu 

> 
> 
> I'm trying to use:
> 
> from tensorflow.examples.tutorials.mnist import input_data
> mnist_data = input_data.read_data_sets('MNIST_data', one_hot=True)
> 
> but I am getting the error that the downloaded file is not in GZip format.
> 
> There are several bug reports on this, but none of them seem to solve the issue. 
> 
> I found train-images-idx3-ubyte.gz in the local directory MNIST_data, but even trying `gunzip` fails:
> 
> ```(tf) [bduser@param03 MNIST_data]$ gunzip
> gzip: compressed data not read from a terminal. Use -f to force decompression.
> For help, type: gzip -h
> (tf) [bduser@param03 MNIST_data]$ gunzip train-images-idx3-ubyte.gz
> 
> gzip: train-images-idx3-ubyte.gz: not in gzip format
> ```
> 
> I'm thinking that this is a problem with the original datafile. Maybe the GZip format has changed or is in conflict?? Or perhaps my OS' version of GZip can't understand the GZip file??
> 
> I am using TF 1.4 on CentOS Linux release 7.4.1708 (Core)
> 
> Thanks.
> -Tony
> 
> 
> 
> ```
> >>> from tensorflow.examples.tutorials.mnist import input_data
> >>> mnist_data = input_data.read_data_sets('MNIST_data', one_hot=True)
> Successfully downloaded train-images-idx3-ubyte.gz 727 bytes.
> Extracting MNIST_data/train-images-idx3-ubyte.gz
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/bduser/miniconda2/envs/tf/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 242, in read_data_sets
>     train_images = extract_images(f)
>   File "/home/bduser/miniconda2/envs/tf/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 56, in extract_images
>     magic = _read32(bytestream)
>   File "/home/bduser/miniconda2/envs/tf/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 38, in _read32
>     return numpy.frombuffer(bytestream.read(4), dtype=dt)[0]
>   File "/home/bduser/miniconda2/envs/tf/lib/python2.7/gzip.py", line 268, in read
>     self._read(readsize)
>   File "/home/bduser/miniconda2/envs/tf/lib/python2.7/gzip.py", line 303, in _read
>     self._read_gzip_header()
>   File "/home/bduser/miniconda2/envs/tf/lib/python2.7/gzip.py", line 197, in _read_gzip_header
>     raise IOError, 'Not a gzipped file'
> IOError: Not a gzipped file
> >>> exit()
> ```
>

**Comment by aselle** [comment]
It doesn't look like the downloaded file worked properly. Please cat the file and look what those 700bytes are. I'm sure they are a text error message saying why the download fails. See, my MNIST_data/train-images-idx3-ubyte.gz is *9912422 bytes* and yours is *727 bytes*. Catting the file will probably tell you why it wasn't downloaded properly...

```
>>> from tensorflow.examples.tutorials.mnist import input_data
>>> mnist_data = input_data.read_data_sets('MNIST_data', one_hot=True)
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
```

**Comment by mas-dse-greina** [comment]
Yes. It looks like my corporate firewall is preventing the service from downloading the file. 

I thought the proxy settings were correct on this machine, but apparently not.

Thanks for the help.

> (tf) [bduser@param03 MNIST_data]$ cat train-images-idx3-ubyte.gz
> <HTML><HEAD>
> <TITLE>Request Error</TITLE>
> </HEAD>
> <BODY>
> <FONT face="Helvetica">
> <big><strong></strong></big><BR>
> </FONT>
> <blockquote>
> <TABLE border=0 cellPadding=1 width="80%">
> <TR><TD>
> <FONT face="Helvetica">
> <big>Request Error (invalid_request)</big>
> <BR>
> <BR>
> </FONT>
> </TD></TR>
> <TR><TD>
> <FONT face="Helvetica">
> Your request could not be processed. Request could not be handled
> </FONT>
> </TD></TR>
> <TR><TD>
> <FONT face="Helvetica">
> This could be caused by a misconfiguration, or possibly a malformed request.
> </FONT>
> </TD></TR>
> <TR><TD>
> <FONT face="Helvetica" SIZE=2>
> <BR>
> For assistance, contact your network support team.
> </FONT>
> </TD></TR>
> </TABLE>
> </blockquote>
> </FONT>
> </BODY></HTML>

**Comment by aselle** [comment]
Glad you figured out the problem. Closing for now.
