### ISSUE TITLE
[Android] Dex cannot parse version 52 byte code

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [tensorflow/tensorflow#15699]
When including:

`compile 'org.tensorflow:tensorflow-lite:0.1.1'`

I get the error:

> [Android] Dex cannot parse version 52 byte code

If I use AGP 3.0.0+ the problem goes away since it has support for Java 8, but the problem exists if I try to use 2.3.3.

**Comment by asimshankar** [comment]
By AGP do you mean Android Studio? TensorFlow Lite requires Android Studio 3 (from [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite#building-in-android-studio-using-tensorflow-lite-aar-from-jcenter)).

FYI @aselle @andrehentz

**Comment by leandroBorgesFerreira** [comment]
Yes, that's what I was asking. Thanks for the help!
