### ISSUE TITLE
[master] User op example doesn't work

### ISSUE THREAD

**Issue by RasmooL** [tensorflow/tensorflow#1569]
A recent change to remove the static linking in user ops seems to have broken them.
From the example:
`g++ -std=c++11 -shared zero_out.cc -o zero_out.so -I $TF_INC`
you need -fPIC to compile it:
`/usr/bin/ld: /tmp/ccvknfY4.o: relocation R_X86_64_32 against '.text' can not be used when making a shared object; recompile with -fPIC`

It used to be:
```
g++ -std=c++11 -shared zero_out.cc -o zero_out.so \
-I $TF_INC -l tensorflow_framework -L $TF_LIB \
-fPIC -Wl,-rpath $TF_LIB
```
which no longer works since tensorflow_framework was removed.

However, it builds just by adding -fPIC, and you can try to load it:
`tf.load_op_library('zero_out.so')`
resulting in:
`undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev`

(and on a minor note, the doc link to load_op_library is broken, it's missing a '.html')

**Comment by RasmooL** [comment]
I'm curious whether you don't have the undefined symbol error, or if you just missed it? :) I can only get it to build with -fPIC, but it has missing symbols.

**Comment by vrv** [comment]
@keveman  to verify

**Comment by keveman** [comment]
Sorry about closing without a comment. I did verify before closing that I could successfully load the op, I don't see the undefined symbol error. I am on Ubuntu 14.04. What platform are you seeing this error?

**Comment by RasmooL** [comment]
I'm on Arch Linux, using a new binary install from http://ci.tensorflow.org/job/tensorflow-master-gpu_pip/. 
gcc 5.3.0 and Python 2.7.11

Does it matter where the compiled .so is located? To be clear:
```
> TF_INC=$(python2 -c 'import tensorflow as tf; print(tf.sysconfig.get_include())') 
/home/rasmus/.local/lib/python2.7/site-packages/tensorflow/include
> g++ -std=c++11 -shared zero_out.cc -o zero_out.so -I $TF_INC -fPIC
> python2 -c "import tensorflow as tf; tf.load_op_library('/home/rasmus/deep-rl/zero_out.so')"
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rasmus/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 71, in load_op_library
    raise errors._make_specific_exception(None, None, error_msg, error_code)
tensorflow.python.framework.errors.NotFoundError: /home/rasmus/deep-rl/zero_out.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev
```

**Comment by keveman** [comment]
I tried the following :

    $ pip install -U http://ci.tensorflow.org/job/tensorflow-master-gpu_pip/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.7.1-py2-none-any.whl
    $ python2
    Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
    [GCC 4.8.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import tensorflow as tf
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
    >>> tf.load_op_library('/home/keveman/zero_out.so')
    <module '18c058680842296ccc50a4eac3d8b763' (built-in)>

The one reason I can think of why the undefined symbol error could be happening for you is, pywrap_tensorflow.so is not dlopened with `RTLD_GLOBAL` for some reason. Look at `tensorflow/python/__init__.py` for these lines : 

    _default_dlopen_flags = sys.getdlopenflags()
    sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
    from tensorflow.python import pywrap_tensorflow
    sys.setdlopenflags(_default_dlopen_flags)

Try this on your machine : 

    $ python2 -c "import ctypes; print ctypes.RTLD_GLOBAL"
    256

Although I don't see why that would be different on ArchLinux.

**Comment by RasmooL** [comment]
Hmm, I can't say why it doesn't work. ctypes.RTLD_GLOBAL is indeed 256. 
Anyways, I tested on a Ubuntu 14.04 machine with Python 2.7.6 and gcc 4.8.4, where the custom op indeed loads just fine. It could be an issue with newer Python/gcc?

**Comment by RasmooL** [comment]
Indeed, on the Arch machine:
```
> $ g++-4.8 --version
g++-4.8 (GCC) 4.8.5

>g++-4.8 -std=c++11 -shared zero_out.cc -o zero_out.so -I $TF_INC -fPIC

> $ python2
Python 2.7.11 (default, Mar  3 2016, 11:00:04) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
>>> tf.load_op_library('/home/rasmus/deep-rl/zero_out.so')
<module '18c058680842296ccc50a4eac3d8b763' (built-in)>
```

**Comment by keveman** [comment]
Can you try building with gcc 5, but with `-D_GLIBCXX_USE_CXX11_ABI=0` , like so : 

    g++-4.8 -std=c++11 -shared zero_out.cc -o zero_out.so -I $TF_INC -fPIC -D_GLIBCXX_USE_CXX11_ABI=0

**Comment by RasmooL** [comment]
Yes, the ABI was the issue, it works with that flag on gcc 5. Good one :)

**Comment by keveman** [comment]
Glad it worked. Added a note to the documentation. #1584

**Comment by tobegit3hub** [comment]
Thanks @keveman and it works 👍
