### ISSUE TITLE
Very slow tf.transpose on CPU (compared to numpy)

### ISSUE THREAD

**Issue by Bihaqo** [tensorflow/tensorflow#15697]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Tested on Linux Ubuntu 16.04 and Mac OS
- **TensorFlow installed from (source or binary)**: Both affected
- **TensorFlow version (use command below)**: v1.4.0-19-ga52c8d9 1.4.1
- **Python version**:  3.6.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: 

### Describe the problem
Tensorflow transpose is 10000 slower than numpy transpose on my example.

### Source code / logs
```
import numpy as np
a = np.random.randn(*(10, 10, 10, 100, 10, 10, 10))
%timeit np.transpose(a, [3, 0, 1, 2, 4, 5, 6])
# 744 ns on my machine
b = tf.Variable(tf.random_normal((10, 10, 10, 100, 10, 10, 10))) # variable to avoid generating random numbers while measuring time
sess = tf.Session()
sess.run(tf.global_variables_initializer())
op = tf.transpose(b, [3, 0, 1, 2, 4, 5, 6]).op
%timeit sess.run(op)
# 7.94 s
```

**Comment by shoyer** [comment]
Numpy and TensorFlow use different memory models, so whereas transpose in NumPy does not require copying an array's data, a copy is always required by TensorFlow. So this behavior is entirely expected.

**Comment by bignamehyp** [comment]
Consider use static graph instead. 
b = tf.Variable(tf.random_normal((10, 10, 10, 100, 10, 10, 10))) # variable to avoid generating random numbers while measuring time
op = tf.transpose(b, [3, 0, 1, 2, 4, 5, 6]).op
sess = tf.Session()
sess.run(tf.global_variables_initializer())
%timeit sess.run(op)

**Comment by Bihaqo** [comment]
It still very slow with the static graph approach above as well. Also, copying memory doesn't explain the operation being _that_ slower (10000x!): e.g. tf.tile(b, [1, 2, 1, 1, 1, 1, 1]).op (which should be much slower if memory copying is the bottleneck) takes 261 ms while transpose takes 7.9 s.

My friend @mfigurnov suggests that the reason for this behavior may be here: https://github.com/tensorflow/tensorflow/blob/f284c708a8f3e2672d41dd3e7f6f03b9d26f0c80/tensorflow/core/kernels/transpose_functor_cpu.cc#L70

For <= 5 dimension tf uses efficient transpose, and in other cases, it uses some baseline code.
