### ISSUE TITLE
mkl_cpu_allocator.h is not compiled under windows anymoe

### ISSUE THREAD

**Issue by Ariel-Lieberman** [tensorflow/tensorflow#15690]
git branch v1.5/master

[mkl_cpu_allocator.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/mkl_cpu_allocator.h)

is not compiled on windows anymore since in includes unistd.h, which dosn't exist in windows.

**Comment by rongjiecomputer** [comment]
@Ariel-Lieberman Intel MKL optimization is only available on Linux for now, how did you get it to work on Windows in the past?

**Comment by Ariel-Lieberman** [comment]
Using the Cmake compilation I've managed (with no modifications to the source files themselves i.e. .cc, .h) to build the previous version (i.e. v1.3.0).  Now, MKL have added references to uint and other (like above, with no real reason) that breaks the compilation.  :-)

**Comment by asimshankar** [comment]
The dependency on `unistd.h` was introduced in #13674 by @jbobba , perhaps @jbobba has some thoughts on making this work for Windows.

FYI @rmlarsen 

@gunan may also want to comment on our ability to support Windows+MKL builds. 

Thanks!

**Comment by gunan** [comment]
We have nothing official on MKL build yet.
Even the build only works for only linux out of the box, so no guarantees for anything else.

However, contributions are certainly welcome.

**Comment by jbobba** [comment]
@Ariel-Lieberman unistd is used to get information about available system memory (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/mkl_cpu_allocator.h#L71). You can work around it by replacing with equivalent functionality on windows. https://stackoverflow.com/questions/2513505/how-to-get-available-memory-c-g provides one possible option.

**Comment by kumariko** [comment]
@Ariel-Lieberman Could you please let us know if this issue still persists ? If it is resolved then please feel free to move this issue to close status ?Thanks!

**Comment by Ariel-Lieberman** [comment]
fixed here - https://github.com/tensorflow/tensorflow/commit/dce9a49c19f406ba45919e8c94474e55dc5ccd54
