### ISSUE TITLE
tf.image.draw_bounding_boxes don't support boxes with different color

### ISSUE THREAD

**Issue by gauss-clb** [tensorflow/tensorflow#15692]
I want to draw boxes with different color for different classes, but it seems that  `tf.image.draw_bounding_boxes` don't support, could you add color paramters to `tf.image.draw_bounding_boxes`?

**Comment by asimshankar** [comment]
The operation [cycles between colors](https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/core/kernels/draw_bounding_box_op.cc#L68) when drawing multiple boxes.

That said, the set of colors isn't parameterized yet. 
Contributions for changing this are welcome.

FYI @shlens

**Comment by yongtang** [comment]
Added a PR #15778 for the fix. Please take a look.
