### ISSUE TITLE
Latency of simple tf.data.Dataset transformations is higher than raw Python

### ISSUE THREAD

**Issue by Anjum48** [tensorflow/tensorflow#15694]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip install tensorflow (CPU only)
- **TensorFlow version (use command below)**: v1.4.0-rc1-11-g130a514 1.4.0
- **Python version**: 3.5.2

### Describe the problem
I'm trying to improve performance by moving to `tf.data.Datasets` to manage epochs and minibatches (particularly I/O performance on a GPU when I come to scaling up). However I'm finding that this is much slower than just using nested `for` loops in Python.

### Source code / logs
Here's an example using a dataset with 10,000 numbers, 10 epochs and a minibatch size of 100:

```python
import tensorflow as tf
import numpy as np
from time import time

MINI_BATCH = 100
EPOCHS = 10

# Dataset consisting of 10000 random numbers
raw_data = np.random.randn(10000)

# Raw Python implementation
start = time()
split_data = np.split(raw_data, 10000 // MINI_BATCH)

for _ in range(EPOCHS):
    for i, batch in enumerate(split_data):
        # Do stuff with batch data
        x = batch * 2
print("Raw Python done in", time() - start)


# TensorFlow implementation
start = time()
dataset = tf.data.Dataset.from_tensor_slices(raw_data)
dataset = dataset.repeat(EPOCHS)
dataset = dataset.batch(MINI_BATCH)
iterator = dataset.make_one_shot_iterator()
next_chunk = iterator.get_next()

with tf.Session() as sess:
    while True:
        try:
            batch = sess.run(next_chunk)
            # Do stuff with batch data
            x = batch * 2
        except tf.errors.OutOfRangeError:
            break
print("TensorFlow done in", time() - start)

```
Output:
```
Raw Python done in 0.0011773109436035156
TensorFlow done in 0.14212393760681152
```

Does anyone know why this might be the case? 

I'm guessing that most of the overhead is in the evaluation of `iterator.get_next()` on every loop. If this is not supposed to be evaluated it would be useful to have some examples of how it should be used without using `sess.run` each time.

**Comment by mrry** [comment]
The short answer here is that building a single minibatch of 100 elements is too small an operation to benefit from TensorFlow as it's currently implemented. (You'll also find that multiplying two small matrices is faster in NumPy than loading it into TensorFlow.)

The `Dataset` implementation is designed to perform non-trivial amount of preprocessing (decoding images, parsing text, etc.); and the `Session` implementation is geared towards computations that take at least a few milliseconds to perform. In the intended use case, you would pass the output of `iterator.get_next()` to the input of a neural network, for inference or training.

Each of the TensorFlow operations in your example takes approximately 140 microseconds. Calling into TensorFlow from Python currently has an overhead of around 60 microseconds, a trivial step takes around 20 microseconds, and invoking an operation such as `Iterator.get_next()` incurs a few more microseconds of overhead, plus a context switch. 

There are a couple of things you could try:

* Try using a `tfe.Iterator` in Eager mode, which acts more like a Python iterator, and takes approximately 100us per batch in my tests.
* Creating a callable for the step, using `get_next_chunk = sess.make_callable(next_chunk)` and then using `get_next_chunk()` in place of `sess.run(next_chunk)` shaves about 65us off each invocation (to approximately 92us per batch) in my tests.
* Rewrite the pipeline to cache the processed data for an epoch:

    ```python
    dataset = tf.data.Dataset.from_tensor_slices(raw_data)
    dataset = dataset.batch(MINI_BATCH)
    dataset = dataset.cache()
    dataset = dataset.repeat(EPOCHS)
    iterator = dataset.make_one_shot_iterator()
    ```

  This change reduces the cost of each mini-batch to about 42us in my tests (and ~52us in Eager mode). 

Where does the rest of the time go? In the non-caching versions, the data are currently copied twice, out of the original array in `Dataset.from_tensor_slices()`, then into the batch in `Dataset.batch()`. We could potentially use `Tensor::Slice()` to avoid a deep copy in some cases, although that only works when the slices are aligned to 32-byte boundaries, which might not always be the case. (It isn't for a vector of shape `(10000,)` `int64` elements but it is if e.g. you reshape it to `(100, 100)`.) Alternatively, and at the cost of some memory inflation, `Dataset.from_tensor_slices()` could eagerly slice up its input ahead of time, where the up-front initialized cost would be amortized over multiple epochs... this is what the explicit `Dataset.cache()` does for you. There are more context switches than are strictly necessary, especially when running in Eager mode, where the work can happen on a donated Python thread. Finally, profiling suggests that there are some non-trivial overheads when dealing with tensors of a single element (shape calculations, in particular, weigh heavily in the profile when the cost of the actual copy is small). 

There are definitely some overheads worth paring down here, although they are likely to have only a small effect on headline performance numbers, so fixing them won't be top priority. I'll add some benchmarks to track the various versions, and invite contributions that improve things for all workloads.

**Comment by bhack** [comment]
@mrry What do you think?

**Comment by mrry** [comment]
@bhack `tf.py_func()` has to acquire the GIL in order to run `read_fn`, so unless there is a substantial amount of work in that function that happens while the GIL is released, it is unlikely that you will see much of a parallel speedup for that code.

**Comment by bhack** [comment]
@mrry We need to have a decent amount of computation to surpass the GIL overhead right?

**Comment by mrry** [comment]
Yes, plus that computation has to happen in a method that releases the GIL (e.g. many NumPy routines).

**Comment by bhack** [comment]
@mrry Do you think to add something about this in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/performance/datasets_performance.md? I think it could be useful.
