### ISSUE TITLE
AdaGradOptimizer on GPU (Making word2vec tutorial runnable on GPU)

### ISSUE THREAD

**Issue by alexeygrigorev** [tensorflow/tensorflow#1570]
When I try running the [word2vec tutorial](https://www.tensorflow.org/versions/r0.7/tutorials/word2vec/index.html) on GPU, I get the following error: 

```
Executor failed to create kernel. Invalid argument: AttrValue must not have reference type value of float_ref for attr 'tensor_type
```

It seems that the problem is with `AdaGradOptimizer`: when I replace it with `GradientDescentOptimizer`, I can run the code (see [here](https://gist.github.com/alexeygrigorev/ed884c433c495075f000))

Also see #86

**Comment by ma2rten** [comment]
I had the same problem with my own model. I was able to fix it by pinning the embedding lookup to the CPU.

**Comment by girving** [comment]
@zheng-xq: Any chance this is fixed?  If not, I'm going to mark this as contributions welcome in case someone else gets to it before we do.  PRs welcome!

**Comment by ChuyuHsu** [comment]
I bumped into this problem as well

**Comment by zheng-xq** [comment]
@alexeygrigorev, @ChuyuHsu, are you running the following example? 

https://github.com/tensorflow/tensorflow/blob/r0.9/tensorflow/examples/tutorials/word2vec/word2vec_basic.py

It seems that it was using GradientDescentOptimizer, not AdaGradOptimizer.

**Comment by alexeygrigorev** [comment]
As I wrote earlier, using gradient decent solves the issue

**Comment by ravyg** [comment]
Might be helpful:
ravyg@2a83490
Supports:

>     Multi-threaded Incremental word2vec
>     Mini-batched skip-gram model GPU support
>     Works with Tensorflow r0.12 with Checkpoints (New saver in TFr0.12)
>     Test Performance
>     Configurable Batch_size, epochs
>     etc.

[GPU support works with Tensorflow r0.12 with Checkpoints](https://github.com/ravyg/tensorflow/commit/2a83490455f0f02ea05fc447551cacea1c1b8cb6)

**Comment by tfboyd** [comment]
Closing, if you have a PR that would be great and please open a new issue or a PR.
