### ISSUE TITLE
Tensorflow Python3

### ISSUE THREAD

**Issue by BL4CKvGHOST** [tensorflow/tensorflow#15730]
i recently installed tensorflow in my linux machine with pip.

when i try to import tensorflow it show me this 
```
Python 3.6.4 (default, Dec 19 2017, 14:09:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
```

i installed tensorflow cpu version with this command `pip install tensorflow`

this warning don't affect the script but its annoying

can anyone explain to me what is this
**OS: Linux ubuntu**
**Python Version: 3.6.4**

**Comment by maxim5** [comment]
It's been discussed in #14182. You can find the solution [on StackOverflow](https://stackoverflow.com/q/47225210/712995).

**Comment by Aryal007** [comment]
If you are trying to install tensorflow-gpu on python 3.6 and Ubuntu version 16.04, you can follow the step-by-step process in this blog. It worked for me and doesn't give any warnings whatsoever.

http://www.python36.com/install-gpu-version-of-tensorflow/

**Comment by f00r** [comment]
The blog post recommends installing tensorflow 1.0.0

**Comment by Aryal007** [comment]
For tensorflow 1.4.1, check this out: http://www.python36.com/install-tensorflow141-gpu/
