### ISSUE TITLE
wrong output(extra symbol "b")

### ISSUE THREAD

**Issue by vodas3** [tensorflow/tensorflow#15738]
**System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows  Home
TensorFlow installed from (source or binary): binary (pip)
TensorFlow version (use command below): 1.4.0 (GPU)
Python version: 3.6**
GPU: GTX1050 Ti M (disabled Intel visualization)

Basically any output I try to write in console is with extra symbol : "b"
for example:
with cmmand:
```
C: python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
b'unknown' 1.4.0 //OUTPUT
```
I downloaded GPU verison form guide from official webiste(with:Anaconda):
[https://www.tensorflow.org/install/install_windows#installing_with_anaconda](url)

i have tried the validation example and same problem (extra symbol : "b")

**Comment by vodas3** [comment]
I just tried using custom code:
```
>>> node1 = tf.constant(3.0, dtype=tf.float32)
>>> node2 = tf.constant(4.0, dtype=tf.float32)
>>> print(node1,node2)
Tensor("Const:0", shape=(), dtype=float32) Tensor("Const_1:0", shape=(), dtype=float32)
```
and the oputput looks good 
I am bit scared something is not right 
thx for any help

**Comment by facaiy** [comment]
The b prefix indicates a byte string for python, see https://www.python.org/dev/peps/pep-3112/

**Comment by asimshankar** [comment]
Closing as this seems to not be an issue. Please let me know if I misunderstood
