### ISSUE TITLE
Importing submodules from tensorflow.keras fails with No module named 'tensorflow.keras'

### ISSUE THREAD

**Issue by rragundez** [tensorflow/tensorflow#15736]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary (pip)
- **TensorFlow version (use command below)**: v1.4.0-19-ga52c8d9 1.4.1
- **Python version**: 3.6
- **Exact command to reproduce**:
from tensorflow.keras import datasets # fails but should work
import tensorflow as tf #succeeds
tf.keras.datasets #succeeds
from tensorflow.python.keras import datasetst # succeeds

### Describe the problem
Importing submodules from tensorflow.keras fails with error: `ModuleNotFoundError: No module named 'tensorflow.keras'`. but `import tensorflow as tf` and then doing `tf.keras.datasets` works. This is a big inconsistency, also it means that every time an element from within the `tensforlow.keras` module you need to write the complete path (which is very annoying) this removes the simplicity and readability of the `keras` API. A work around is to import submodules from `tensorflow.python.keras`, which again is inconsistent. 

In my opinion, since the documentation states that `keras` is availabe at `tf.keras` that should be the access path to the submodules and not `tensorflow.python.keras`. I'll try to  make a pull request for this.

### Source code / logs

```python
# fails but should work
from tensorflow.keras import datasets
```
```python
# succeeds
import tensorflow as tf
tf.keras.datasets
```
```python
# succeeds
from tensorflow.python.keras import datasetst
```

**Comment by Hvass-Labs** [comment]
I can confirm this problem exists with my system settings that are similar.

@rragundez Thanks for reposting this issue here and taking care of it!

**Comment by rragundez** [comment]
Pull request submitted https://github.com/tensorflow/tensorflow/pull/15756
This only solves the import problem with `tensorflow.python.keras`, can be easily modified to do the same for any submodule inside the `tensorflow.python` module.

**Comment by drpngx** [comment]
Sorry, we only support `tf.keras.datasets`.

**Comment by Hvass-Labs** [comment]
@rragundez and @drpngx thanks for the quick fix and response, especially on New Years!

@drpngx Please explain the philosophy. Why have you made that decision and what do you propose is a good way of importing Keras from TensorFlow?

Perhaps @fchollet has a comment on the best way of importing Keras from TensorFlow?

Currently I am writing:

    from tensorflow.python.keras.models import Sequential
    from tensorflow.python.keras.layers import Dense
    model = Sequential()
    model.add(Dense(...))

But this is a bit clumsy compared to just writing the following, which unfortunately does not work:

    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import Dense
    model = Sequential()
    model.add(Dense(...))

It would be even more clumsy to write e.g.:

    import tensorflow as tf
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Dense(...))
    model.add(tf.keras.layers.Dense(...))
    model.add(tf.keras.layers.Dense(...))

One workaround would seem to be:

    import tensorflow as tf
    Sequential = tf.keras.models.Sequential
    Dense = tf.keras.layers.Dense
    model = Sequential()
    model.add(Dense(...))
    model.add(Dense(...))
    model.add(Dense(...))

But I am not really a Python expert so I don't know if this is considered bad style for some reason?

Happy New Years! :-)

**Comment by drpngx** [comment]
I see. We might decide to do something else for keras, but the last two are the ones supported by tensorflow.

The rationale behind this is that tensorflow is more like numpy. It's one big monolithic package that you import. We don't support importing piecemeal, because our code doesn't internally distinguish between private and exportable symbols. You might see `def foo` which really means `def _foo`, or `import sys` which really means `import sys as _sys`. So, if you import random modules in tensorflow, you will have access to private symbols. We don't want to support that, as it would be a large maintenance burden.

**Comment by fchollet** [comment]
> So, if you import random modules in tensorflow, you will have access to private symbols. 

Just a note to say that this isn't the case for imports in `tf.keras`, because the underlying files only contain public symbols (they're separate API-only files).

**Comment by drpngx** [comment]
Happy to have direct imports for keras, if you and @martinwicke agrees.

**Comment by rragundez** [comment]
@Hvass-Labs @drpngx @fchollet Adding to if it is a bad style in Python? it is, the bad style comes from the fact that you can access submodules from `tf` (`tf.keras.layers.Dense` for example) but you cannot import `Dense` from as `from tensorflow.keras.layers import Dense`. Normally when deep functionality want to be exposed in a higher module this is a direct exposure of objects (functions or classes normally) then you never have the problem at hand. In this case the functionality being exposed to the user is a module itself which causes this confusion. 

You can easily look at `pyspark` or `sklearn` for example, where the functionality taken to a higher level in the package are objects (a type of estimator for exapmle) but not modules themselves (as they will create the problem at hand).

So indeed the current approach is not pythonic and specially I would argue that removes the simplistic Keras API.

**Comment by Hvass-Labs** [comment]
I imagine most users of TensorFlow need to use a builder API. It has been a never-ending source of frustration for myself and the community that you have had numerous different and unfinished builder API's, instead of consolidating their best features into a single default API. You never even finished trivial features of the Layers API before you abandoned it.

To my knowledge Keras is the best builder API for TensorFlow. I would therefore encourage you to consider Keras to be the default builder API that many people will be using with TensorFlow. I think it would be wise to give it special treatment in the code-base if that is necessary.

Similarly goes for Keras' author @fchollet whose philosophy on API design is wonderfully user-centric so I think his opinion should weigh heavily in your discussions on the rest of TensorFlow's API as well.

**Comment by dnjake** [comment]
The standard python methods for importing modules and symbols from modules do not appear to work for parts of tensorflow that are described as modules.  That includes tensorflow.keras, tensorflow.keras.layers, and tensorflow.keras.models.  The result is that tensorflow comes across as a second class python package written by programmers who do not know what they are doing.  It also results in ugly code when the full path has to be written for every symbol in a tensorflow script that uses the keras object model.  If Google wants to project tensorflow as high quality software, this second class implementation needs to be fixed.

**Comment by Hvass-Labs** [comment]
@dnjake Hehehe! I'm glad to hear I'm not the only one who was frustrated by the TensorFlow API :-)

**Comment by dnjake** [comment]
I only have a modest experience with tensorflow.  So my opinion might change.
But my past does include two decades of experience developing computer system
software.  My view is that the big problem with tensorflow is mainly that it is
intrinsically hard.  No group is able to architect a complex UI in advance of
any experience with developing and using it.  On a realistic scale, I would give
tensorflow an high grade.  But, it is certainly a work in progress that is hard to
understand by those developing it, hard to understand how to use it, and even harder to use
productively after it is understood.  I think the base design did make a big
mistake with a configuration architecture that left major objects like the
session context and the default graph as implicit global variables.  I also am skeptical of
the value of eager mode.  Had the base design been better, perhaps only
one architecture would have emerged for models, graphs, and layers.  But, I
doubt that navigating the variations in the different object models that have
been built on top of the tensorflow python base will prove to be the limiting
factor for most people in working with tensorflow
________________________________

**Comment by Libardo1** [comment]
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import tensorflow.keras.backend as K

Works for me. Why?

**Comment by SwagatDas** [comment]
Can someone clearly explain this:

"Works"
import tensorflow 
from tensorflow.keras import _______


Doesnot work:
import tensorflow as tf
from tf.keras import ________

**Comment by ajeyaajeya** [comment]
Is there a solution to this?

For :
 from tensorflow.keras.layers.core import Reshape,Dense,Dropout,Activation,Flatten

I get:
ModuleNotFoundError: No module named 'tensorflow.keras.layers.core'

**Comment by dnjake** [comment]
I have not double checked this answer.  But I believe the reason for the problem is the way Tensorflow uses package __init__.py modules to restrict user access to the fixed Tensorflow API.  The way those modules are coded prevents the standard python techniques of mapping symbols to arbitrary module content from working.

**Comment by ajeyaajeya** [comment]
I can call keras.something when I installed keras on NVIDIA Jetson TX2 with `sudo apt-get install python3-keras`

**Comment by AGenchev** [comment]
I tried 
`sudo pip3 install keras`

**Comment by jkrathore** [comment]
> from tensorflow.keras.layers.core import Reshape,Dense,Dropout,Activation,Flatten

from tensorflow.python.keras.layers.core import Reshape,Dense,Dropout,Activation,Flatten

works for me

**Comment by clickfrank** [comment]
Had the same problem. None of the solutions above worked for me. Could not import tensorflow.keras.. or any variation of it, such as tensorflow.python.keras.  Frustrating.  Tested with Conda environment and python 3.7+ virtual env. Decided to pip install keras and import direct from that while tensorflow was conda install..ed. I am assuming that the conda install yields c based binaries for all languages while the pip is bringing back something python can understand. Anyway, not on to trying to get gpu working :-)

**Comment by dnjake** [comment]
Are you using tensorflow 2?  I have not tried it.  But, the talks I have heard over the web indicated that changes to tensorflow 2 make it possible to reference all of the module variables and functions.  In tensorflow 1, the __init__.py files for packages have been extensively manipulated to limit references to those specified in the api.  It is possible to go into the source code and modify the __init__.py files.  But, otherwise access to module internals is limited by the api.

________________________________

**Comment by knownstranger03** [comment]
> Can someone clearly explain this:
> 
> "Works"
> import tensorflow
> from tensorflow.keras import _______
> 
> Doesnot work:
> import tensorflow as tf
> from tf.keras import ________

when you import tensorflow as tf, you can use it to directly call functions into variable but not import sub-modles.

####Example####
import tensorflow as tf
model=tf.keras.models.sequential()

**Comment by Sreosha** [comment]
If you're getting this error in tensorflow==2.0.0, then do the following steps -

Step 1: Uninstall the keras by using '!python -m pip uninstall keras --yes' 
Step 2: Reinstall keras by using 'pip install keras'
Step 3: Now, install tensorflow 2.0.0 by using 'pip install tensorflow==2.0.0'

This should work, without downgrading the tensorflow version. Thank You!

**Comment by Vignesh142** [comment]
> from tensorflow.keras.models import Sequential from tensorflow.keras.layers import Dense from tensorflow.keras.optimizers import Adam import tensorflow.keras.backend as K
> 
> Works for me. Why?

But not for me. It runs in .ipynb but not in the .py file. I have tried multiple times but it dosen't work
