### ISSUE TITLE
build offline documentation, how to?

### ISSUE THREAD

**Issue by yaoli** [tensorflow/tensorflow#1574]
I've noticed the API doc in https://www.tensorflow.org/versions/master/api_docs/index.html is not complete. Is there a way to build a nice HTML based API *locally* that contains a complete documentation?

Basically the question is: how is this https://www.tensorflow.org/versions/master/api_docs/index.html being automatically generated? What's the magical command?

**Comment by girving** [comment]
The gen_docs_combined script should build markdown, but I'm not sure about HTML.  @martinwicke?

**Comment by martinwicke** [comment]
You cannot currently build html, but you can build the complete set of markdown, using [gen_docs.sh](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docs/gen_docs.sh).

**Comment by martinwicke** [comment]
Closing, please ping if you have trouble with gen_docs.sh.

**Comment by dmonopoly** [comment]
Seems like there's no more gen_docs.sh file. What's the proper way to build documentation?

**Comment by girving** [comment]
Cc @wolffg.

**Comment by martinwicke** [comment]
See here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/community/documentation.md

**Comment by dmonopoly** [comment]
Trying the "Generating docs and previewing links" section, I end up with this error:

```
INFO: Running command line: bazel-bin/tensorflow/tools/docs/generate '--src_dir=/Users/daze/PersonalGDrive/Hacks/ML/tensorflow/tensorflow/tensorflow/docs_src/' '--output_dir=/tmp/tfdocs/'
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
Writing docs for tf.abs (<function abs at 0x10b19fd08>).
Writing docs for tf.contrib.learn.monitors (<module 'tensorflow.contrib.learn.python.learn.monitors' from '/private/var/tmp/_bazel_daze/dbc852bfd1d7b33406bd81c3c9000a9d/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/tools/docs/generate.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/monitors.py'>).
Writing docs for tf.estimator.Estimator (<class 'tensorflow.python.estimator.estimator.Estimator'>).
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_daze/dbc852bfd1d7b33406bd81c3c9000a9d/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/tools/docs/generate.runfiles/org_tensorflow/tensorflow/tools/docs/generate.py", line 49, in <module>
    sys.exit(doc_generator.build(flags))
  File "/private/var/tmp/_bazel_daze/dbc852bfd1d7b33406bd81c3c9000a9d/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/tools/docs/generate.runfiles/org_tensorflow/tensorflow/tools/docs/generate_lib.py", line 473, in build
    write_docs(output_dir, parser_config, yaml_toc=self.yaml_toc)
  File "/private/var/tmp/_bazel_daze/dbc852bfd1d7b33406bd81c3c9000a9d/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/tools/docs/generate.runfiles/org_tensorflow/tensorflow/tools/docs/generate_lib.py", line 127, in write_docs
    f.write(pretty_docs.build_md_page(page_info))
  File "/private/var/tmp/_bazel_daze/dbc852bfd1d7b33406bd81c3c9000a9d/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/tools/docs/generate.runfiles/org_tensorflow/tensorflow/tools/docs/pretty_docs.py", line 39, in build_md_page
    return _build_class_page(page_info)
  File "/private/var/tmp/_bazel_daze/dbc852bfd1d7b33406bd81c3c9000a9d/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/tools/docs/generate.runfiles/org_tensorflow/tensorflow/tools/docs/pretty_docs.py", line 126, in _build_class_page
    parts.append(h3.format(**method_info.__dict__))
AttributeError: '_MethodInfo' object has no attribute '__dict__'
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

Is this still the official answer? Thanks in advance for the help.

**Comment by martinwicke** [comment]
It looks like you are running this in python 3. I have not converted the doc generator to be compatible with python3. Some of these issues would be easy to fix, but that would only lead to you finding more issues. Since inspect is seriously different and codegen is very old, it may be a bit of an endeavor. I'd welcome anyone who wants to take this on, but it's not a priority for us at the moment, we use py2 to generate the docs.

**Comment by dmonopoly** [comment]
Thanks, using Python 2 makes more progress.

Issue 1:
But the output still isn't error-free. [gist with errors](https://gist.github.com/dmonopoly/b67b5ba35748a25bdc02130a54ca18d6).

Issue 2:
If the above is fine output, and I can indeed look at the generated results, then...
Are we sure that this generator generates docs the same way as they appear on say https://www.tensorflow.org/api_docs/python/tf/contrib/learn/Evaluable ?

While looking into #9313, I generated the docs as described at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/community/documentation.md via

```
bazel run tools/docs:generate -- \
          --src_dir=`pwd`/tensorflow/docs_src/ \
          --output_dir=/tmp/tfdocs/
```

but the output markdown for this file does not have the same problem as featured on that site.

The [code in the master branch](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/evaluable.py#L88) and the [code in r1.1](https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/contrib/learn/python/learn/evaluable.py#L88) are also the same there, so it's not a versioning difference.

Thanks in advance - hope I just made a trivial oversight

**Comment by martinwicke** [comment]
@MarkDaoust for expertise on the doc generation scripts. 

It is surprising that so many doc references are not found. You appear to be giving the correct doc_src directory with guides. 

Mark, is there a problem with the documentation documentation?

**Comment by MarkDaoust** [comment]
It looks like you've got one too many `tensorflow` in your `src_dir` path.

It turns out that `os.walk` doesn't throw an error for a non-existant directory.

Fixes are in the pipeline for that example line of code, and adding clear error-messages. to the doc-generator.
