### ISSUE TITLE
Protobuf Compilation /object_detection/protos/anchor_generator_pb2.py: Permission denied issue

### ISSUE THREAD

**Issue by Dasun1991** [tensorflow/tensorflow#15754]
I need to implement object detection using Tensorflow but.
Im getting ,
**Protobuf Compilation /object_detection/protos/anchor_generator_pb2.py: Permission denied issue** when executing 
`protoc object_detection/protos/*.proto --python_out=.`  in Protobuf Compilation

this is the issue i already having.

![error](https://user-images.githubusercontent.com/34977438/34461460-ae4e5120-ee50-11e7-8d43-1ba5ecab2bc3.jpg)

Here is my link for Tensorflow model [https://github.com/tensorflow/models](url)
and i used **Protocol Buffers v3.4.0**
 So, can anyone knows how to solve and execute that command?﻿

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since this seems like an issue with your environment. There is also a larger community that reads questions there. Thanks!
