### ISSUE TITLE
tf.assert_equal raises incorrect traceback in Eager mode

### ISSUE THREAD

**Issue by matthew-z** [tensorflow/tensorflow#15766]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:  No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04.1 LTS
- **TensorFlow installed from (source or binary)**: pip binary
- **TensorFlow version (use command below)**: 1.5.0-dev20171227
- **Python version**: 3.5.0
- **Bazel version (if compiling from source)**: 
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**: python main.py

### Describe the problem

In eager mode, tf.assert_equal only shows `[]` in traceback message when two inputs are different. However, in graph mode, it does show different values in the message. 

### Source code / logs

```python
import tensorflow as tf
import tensorflow.contrib.eager as tfe

tfe.enable_eager_execution()

x = tf.constant([1,2,3])
y = tf.constant([3,2,1])

with tf.control_dependencies([tf.assert_equal(x, y)]):
    output = tf.reduce_sum(x)

```

Eager Mode Traceback:

```
Traceback (most recent call last):
  File "/Users/matt/PycharmProjects/scratch/main.py", line 9, in <module>
    with tf.control_dependencies([tf.assert_equal(x, y)]):
  File "/usr/local/var/pyenv/versions/anaconda3-4.1.1/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py", line 376, in assert_equal
    summary_msg)))
tensorflow.python.framework.errors_impl.InvalidArgumentError: 
Condition x == y did not hold.
Indices of first 0 different values:
[]
Corresponding x values:
[]
Corresponding y values:
[]
```

Graph Mode Traceback:
```
Traceback (most recent call last):
  File "/Users/matt/PycharmProjects/scratch/main.py", line 9, in <module>
    with tf.control_dependencies([tf.assert_equal(x, y)]):
  File "/usr/local/var/pyenv/versions/anaconda3-4.1.1/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py", line 391, in assert_equal
    _assert_static(condition_static, data)
  File "/usr/local/var/pyenv/versions/anaconda3-4.1.1/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py", line 104, in _assert_static
    message='\n'.join(data_static))
tensorflow.python.framework.errors_impl.InvalidArgumentError: 
Condition x == y did not hold element-wise:
x (Const:0) = 
[1 2 3]
y (Const_1:0) = 
[3 2 1]
```

**Comment by asimshankar** [comment]
Thanks for the report. @iganichev - could you take a look?

**Comment by iganichev** [comment]
The fix is in review. In the meantime, you can use `summarize=3` parameter to `assert_equals`.

**Comment by matthew-z** [comment]
Thank you very much!
