### ISSUE TITLE
How to define multiple loss function and train_op  in tf.estimator.EstimatorSpec

### ISSUE THREAD

**Issue by developer-mayuan** [tensorflow/tensorflow#15773]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.4.0
- **Python version**: 2.7.12
- **CUDA/cuDNN version**: 6.0
- **GPU model and memory**: 1080 Ti + 1080

### Describe the problem
I'm currently implementing a pose estimation system and I defined my network with 3 loss and train_op in each of degree, yaw, pitch and roll. And I'm current using your tf.estimator API which I think is pretty convenient to monitor the system, however I found that I may only be able to define one loss and train_op using this set of API. I would like to know if there is any solution to train and monitor the system with multiple loss and train_op at the same time. Thanks.

### Source code / logs
```
    return tf.estimator.EstimatorSpec(
        mode=mode,
        predictions=predictions,
        loss=[yaw_total_loss, pitch_total_loss, roll_total_loss],  # error
        train_op=[yaw_train_op, pitch_train_op, roll_train_op],  # error
        eval_metric_ops=None)
```

**Comment by unitive-jim** [comment]
I'm also struggling similar issues. I see that the Estimator framework includes experimental support for multiple "Heads" which will probably address this particular issue. There is paper on Arxiv that includes a section on Heads: https://arxiv.org/pdf/1708.02637.pdf. However, the document is just an outline, and the details are still unclear to me.

**Comment by shivaniag** [comment]
@ispirmustafa any comments on this?

**Comment by ispirmustafa** [comment]
for train op:
`EstimatorSpec(train_op = tf.group(yaw_train_op, pitch_train_op, roll_train_op), ...)`

for loss:
to see each of them separately on Tensorboard use: 
```
tf.summary.scalar('yaw_total_loss', yaw_total_loss)
tf.summary.scalar('pitch_total_loss', pitch_total_loss)
tf.summary.scalar('roll_total_loss', roll_total_loss)

EstimatorSpec(loss=yaw_total_loss + pitch_total_loss + roll_total_loss, ...)
```

**Comment by GHAIGIT** [comment]
@ispirmustafa 
Question on loss. I think your code makes the three train_op the same loss, the sum of three different losses. However, @developer-mayuan wants to run the three train_op with three separate losses I think.
@developer-mayuan Do you have any solution yet?

**Comment by developer-mayuan** [comment]
@GHAIGIT @ispirmustafa is correct. Here is my implementation:

```
            fc_yaw_train_op = fc_optimizer.minimize(yaw_total_loss,
                                                    var_list=fc_yaw_variables)
            fc_pitch_train_op = fc_optimizer.minimize(pitch_total_loss,
                                                      var_list=fc_pitch_variables)
            fc_roll_train_op = fc_optimizer.minimize(roll_total_loss,
                                                     var_list=fc_roll_variables)
```

**Comment by GHAIGIT** [comment]
@developer-mayuan @ispirmustafa 
Thanks for your answer!
I still don't understand the `loss` of `EstimatorSpec`, does not it join the back propagation process? What is the effect of `loss` of `EstimatorSpec`? only for summary?
I did not find any explanation in documentation, looking forward to your reply!

**Comment by developer-mayuan** [comment]
@GHAIGIT According to my understanding, the loss is an operation (a node in the computing graph), Tensorflow will automatically calculate the gradient starting from this loss , do the back propagation and update the weights in `var_list`.

The `+` in `EstimatorSpec(loss=yaw_total_loss + pitch_total_loss + roll_total_loss, ...)` is not the value addition but connect 3 different loss operation to the `loss` operation. It will be more clear if you visualize your graph in TensorBoard.

I believe `EstimatorSpec` will periodically evaluate the `loss` operator and get the loss value after certain steps.

**Comment by ispirmustafa** [comment]
@GHAIGIT @developer-mayuan 
yes, `loss` in `EstimatorSpec` is just for summary and tensorboard. it doesn't impact any training operation.

**Comment by developer-mayuan** [comment]
@mdfry I didn't do the optimization on the total loss for all variables, instead I doing the optimization separately for each loss.

```
# extract trainable variables
res_variables = tf.get_collection(
    tf.GraphKeys.GLOBAL_VARIABLESscope = 'resnet')
fc_yaw_variables = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES,
                                     scope='FC/yaw')
fc_pitch_variables = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES,
                                       scope='FC/pitch')
fc_roll_variables = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES,
                                      scope='FC/roll')

fc_optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate * 5)
res_optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)

# Batch norm requires update_ops to be added as a train_op dependency.
update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
with tf.control_dependencies(update_ops):
    fc_yaw_train_op = fc_optimizer.minimize(yaw_total_loss,
                                            var_list=fc_yaw_variables)
    fc_pitch_train_op = fc_optimizer.minimize(pitch_total_loss,
                                              var_list=fc_pitch_variables)
    fc_roll_train_op = fc_optimizer.minimize(roll_total_loss,
                                             var_list=fc_roll_variables)
    res_train_op = res_optimizer.minimize(total_loss, global_step,
                                          var_list=res_variables)
```

**Comment by OceanWong1991** [comment]
@developer-mayuan May I ask which dataset did you used to train your HPE model?

**Comment by developer-mayuan** [comment]
@OceanWong1991 300W-LP.

**Comment by tengerye** [comment]
Are you sure `tf.group()` won't create separate graphs? @ispirmustafa 
This [post](https://stackoverflow.com/questions/49953379/tensorflow-multiple-loss-functions-vs-multiple-training-ops) said `tf.group()` actually creates independent gradients.

**Comment by ispirmustafa** [comment]
Hi @tengerye ,
what do you mean by separate graphs?

**Comment by tengerye** [comment]
According to the [post](https://stackoverflow.com/questions/49953379/tensorflow-multiple-loss-functions-vs-multiple-training-ops) said, there are different sets of gradients, because the updates are performed at the same time @ispirmustafa . I don't know if my understanding is correct. The issue here looks the same as that post.

Thank you for your kind reply.

**Comment by ispirmustafa** [comment]
Hi @tengerye 
Now I see the confusion. The answer in that [post](https://stackoverflow.com/questions/49953379/tensorflow-multiple-loss-functions-vs-multiple-training-ops) is wrong. Ignore that please. I'll answer that post too.
Thanks for pointing out that.

**Comment by phongnhhn92** [comment]
`# optimization
  all_vars = tf.trainable_variables()
  gqn_var = [v for v in all_vars if 'GQN' in v.op.name]
  dis_var = [v for v in all_vars if 'Discriminator' in v.op.name]

  if mode == tf.estimator.ModeKeys.TRAIN:
    lr = _linear_lr_annealing(params['gqn_params'])
    optimizer = tf.train.AdamOptimizer(learning_rate=lr)
    optimizer_dis = tf.train.AdamOptimizer(learning_rate=lr*4)
    train_op_GQN = optimizer.minimize(
        loss=elbo+g_loss,
        global_step=tf.train.get_global_step(),
        var_list= gqn_var
    )
    train_op_dis = optimizer_dis.minimize(
        loss= d_loss,
        global_step= tf.train.get_global_step(),
        var_list=dis_var
    )
    train_op = tf.group(train_op_GQN, train_op_dis)
    estimator_spec = tf.estimator.EstimatorSpec(
        mode=mode,
        loss=elbo+g_loss+d_loss,
        train_op=train_op)
   return estimator_spec
`
Thanks @ispirmustafa I found my solution on my project but may I ask further ? In my case, I am working with a GAN architecture and I want to update the Generator part and Discriminator part using the two time-scale update rule (only Generator trains in the first two step, only Discriminator  trains in the 3rd step and so on) [.](https://arxiv.org/abs/1706.08500) Is that possible to do that using tf estimator ? Please help me since I am new to this tf Estimator.

**Comment by ispirmustafa** [comment]
hi,
for both of your quenstion, you can use tf.cond. it will be something like:
```
train_op: tf.cond(step mod 3, train_op_discriminator, train_op_generator)
```

**Comment by phongnhhn92** [comment]
@ispirmustafa Hello, thanks! But how did you define "step" variable in your answer. This is something I tried based on your suggestion but it didnt work 
```
step = tf.convert_to_tensor(tf.train.get_global_step())
number  = tf.cast(tf.convert_to_tensor(tf.constant(500)),tf.int64)
train_op = tf.cond(tf.greater(step,number),train_op_gen, train_op_dis)
```
This is the error:

> INFO:tensorflow:Calling model_fn.
> Traceback (most recent call last):
>   File "/home/storm/data/Work/code/tf-gqn-master/train_gqn_draw.py", line 185, in <module>
>     tf.app.run(argv=[sys.argv[0]] + UNPARSED_ARGV)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 126, in run
>     _sys.exit(main(argv))
>   File "/home/storm/data/Work/code/tf-gqn-master/train_gqn_draw.py", line 159, in main
>     hooks=[logging_hook],
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py", line 363, in train
>     loss = self._train_model(input_fn, hooks, saving_listeners)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
>     return self._train_model_default(input_fn, hooks, saving_listeners)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py", line 856, in _train_model_default
>     features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn
>     model_fn_results = self._model_fn(features=features, **kwargs)
>   File "/home/storm/data/Work/code/tf-gqn-master/gqn/gqn_model.py", line 218, in gqn_draw_model_fn
>     train_op_gen, train_op_dis)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2039, in cond
>     raise TypeError("true_fn must be callable.")
> TypeError: true_fn must be callable.

**Comment by fuji322** [comment]
> @GHAIGIT @ispirmustafa is correct. Here is my implementation which works well:
> 
> ```
> fc_yaw_train_op = fc_optimizer.minimize(yaw_total_loss, var_list=fc_yaw_variables)
> fc_pitch_train_op = fc_optimizer.minimize(pitch_total_loss, var_list=fc_pitch_variables)
> fc_roll_train_op = fc_optimizer.minimize(roll_total_loss, var_list=fc_roll_variables)
> 
> train_ops = tf.group(fc_yaw_train_op, fc_pitch_train_op, fc_roll_train_op)
> ```

I'm struggling with the multiple losses in an estimator, heres a question with the var_lists, how did you define? thanks

**Comment by Yangyx891121** [comment]
@ispirmustafa Hello! Is it possible to pass the "step" in the above example into model_fn as a placeholder? Thanks! I'm working on a problem that requires using an external switch to control the loss function, something like:

loss = a * loss_1 + (1 - a) * loss_2,

where "a" is defined outside of the estimator and can change during the training procedure.
