### ISSUE TITLE
TensorBoard: histogram charts sometimes duplicated

### ISSUE THREAD

**Issue by zhang8473** [tensorflow/tensorflow#1577]
I unclicked run1 and run2, but when I click on some variables, the run1 and run2 still show up. If I click on run1 and run2 again, five plots will be shown, with 2 of them repeated! By unclicking and clicking a run1, my board just messed up with more and more plots. This is a Google product? :-O

Screenshots:

![image](https://cloud.githubusercontent.com/assets/5016962/13942946/3a633a78-efb5-11e5-9dec-795b306778b3.png)

![image](https://cloud.githubusercontent.com/assets/5016962/13942974/8c51f4dc-efb5-11e5-9b14-3813f4110586.png)

**Comment by girving** [comment]
@danmane: Do you have enough information to look at this?

**Comment by danmane** [comment]
I'm planning to replace the histograms with entirely separate code soon(tm), so considering this obsolete/won't fix.
