### ISSUE TITLE
build&link tensorflow lite c++ library

### ISSUE THREAD

**Issue by acappemin** [tensorflow/tensorflow#15781]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.4.0-19-ga52c8d9 1.4.1
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.8.1
- **GCC/Compiler version (if compiling from source)**: g++ 5.4.0
- **CUDA/cuDNN version**: none
- **GPU model and memory**: none
- **Exact command to reproduce**: g++ -std=c++11 -I...tensorflow -L. -lframework demo.cpp

### Describe the problem
I run 'bazel build //tensorflow/contrib/lite:framework' and get libframework.so. Then I use libframework.so in my own code, but get undefined reference error when compile with g++:
/temp/ccYTZw2h.o: In function 'main':
demo.cpp:(.text+0x46): undefined reference to 'tflite::DefaultErrorReporter()'
demo.cpp:(.text+0x6a): undefined reference ro 'tflite::FlatBufferModel::BuildFromFile(char const*, tflite::ErrorReporter*)'
......

I get following lines by 'nm libframework.so | grep 'DefaultErrorReporter'':
000000000001b1b0 b _ZGVZN6tflite20DefaultErrorReporterEvE14error_reporter
0000000000007990 T _ZN6tflite20DefaultErrorReporterEv
000000000001b1a8 b _ZZN6tflite20DefaultErrorReporterEvE14error_reporter

I'm not familiar with how to use tensorflow lite. Where is the problem could be?

**Comment by ashokbugude** [comment]
@acappemin Can I know if you were able to use tensorflow lite for c++. Were you able to build libtensorflowlite_cc.so similar to libtensorflow_cc.so

**Comment by sosong** [comment]
@acappemin Have you solved the problem?

**Comment by ashishmagar600** [comment]
Why is this not resolved yet?

**Comment by ashishmagar600** [comment]
@ashokbugude  

> Can I know if you were able to use tensorflow lite for c++. Were you able to build libtensorflowlite_cc.so similar to libtensorflow_cc.so

Yes.  Here is my code:

 #include < cstdio >
  #include "tensorflow/lite/interpreter.h"
  #include "tensorflow/lite/kernels/register.h"
  #include "tensorflow/lite/model.h"
  #include "tensorflow/lite/tools/gen_op_registration.h"


  using namespace tflite;

  int main(int argc, char* argv[]) {
  if (argc != 2) {
  fprintf(stderr, "minimal \n");
  return 1;
  }
  const char* filename = argv[1];

  std::unique_ptr<tflite::FlatBufferModel> model =
  tflite::FlatBufferModel::BuildFromFile(filename);
  return 0;
  }

And This is the error:
/tmp/cc0JEa86.o: In function `main':
test.cpp:(.text+0x57): undefined reference to `tflite::DefaultErrorReporter()'
test.cpp:(.text+0x6d): undefined reference to `tflite::FlatBufferModel::BuildFromFile(char const*, tflite::ErrorReporter*)'
/tmp/cc0JEa86.o: In function `std::default_delete<tflite::FlatBufferModel>::operator()(tflite::FlatBufferModel*) const':
test.cpp:(.text._ZNKSt14default_deleteIN6tflite15FlatBufferModelEEclEPS1_[_ZNKSt14default_deleteIN6tflite15FlatBufferModelEEclEPS1_]+0x1e): undefined reference to `tflite::FlatBufferModel::~FlatBufferModel()'
collect2: error: ld returned 1 exit status
