### ISSUE TITLE
Release GPU memory after computation

### ISSUE THREAD

**Issue by shawnLeeZX** [tensorflow/tensorflow#1578]
Is it possible to release all resources after computation?

For example,

```python
import time
import tensorflow as tf

for i in range(0,10000000):
  t0 = time.clock()

  with tf.Graph().as_default():
    sess = tf.Session()

    a = tf.placeholder(tf.int16, name='a')
    y = tf.identity(a, name='y')

    sess.run(y, feed_dict={a: 3})
    sess.close()

  time.sleep(20)

print time.clock() - t0
```

When the program is sleeping, I type `nvidia-smi`, and the memory is always occupied.

```bash
| NVIDIA-SMI 352.79     Driver Version: 352.79         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:03:00.0      On |                  N/A |
| 29%   48C    P2    81W / 250W |   5843MiB /  6143MiB |      1%      Default |
```

The behavior I have observed is that only after the program exit, the memory is released. It makes using multiprocessing hard. Suppose one process is waited on a lock for another progress to finish, and all two processes need to join the main process. Then when process one release the lock, process two cannot get GPU memory, so it would fail.

Is there any way to release memory, so when the above program(not the two process example) is sleeping, it will release memory? 

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

If installed from binary pip package, provide:

1. Which pip package you installed.

```bash
sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
```

2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

```bash
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.7.1
```

**Comment by vrv** [comment]
Try passing "https://github.com/tensorflow/tensorflow/blob/30b52579f6d66071ac7cdc7179e2c4aae3c9cb88/tensorflow/core/protobuf/config.proto#L35" set to true as an argument to your Session's config arguments, it might help a little, though it won't release memory, it just allows growth at the cost of some memory efficiency.

Alternatively, you could delete your session objects (which should release the memory associated with them) when you don't need them.

**Comment by shawnLeeZX** [comment]
How could I delete a session object in python?

I tried

```python
import time
import tensorflow as tf

for i in range(0,10000000):
  t0 = time.clock()

  with tf.Graph().as_default():
    sess = tf.Session()

    a = tf.placeholder(tf.int16, name='a')
    y = tf.identity(a, name='y')

    sess.run(y, feed_dict={a: 3})
    sess.close()

  del sess

  time.sleep(20)

print time.clock() - t0
```

But when the program is sleeping, it still occupies memory.

Also, could you provide the line that configure session to use `allow_growth`?

I tried

```python
import time
import tensorflow as tf

for i in range(0,10000000):
  t0 = time.clock()

  with tf.Graph().as_default():
    sess = tf.Session(config=tf.GPUOptions(allow_growth=True))

    a = tf.placeholder(tf.int16, name='a')
    y = tf.identity(a, name='y')

    sess.run(y, feed_dict={a: 3})
    sess.close()

  del sess

  time.sleep(20)

print time.clock() - t0
```

and got this error report

```bash
TypeError: Expected config_pb2.ConfigProto, but got <class 'tensorflow.core.protobuf.config_pb2.GPUOptions'>
```

Note that this time I used a tensorflow compiled from source, since the 0.7.1 release does not have `allow_growth` option yet.

**Comment by vrv** [comment]
config = tf.ConfigProto()
    config.gpu_options.allow_growth=True
    sess = tf.Session(config=config)

**Comment by shawnLeeZX** [comment]
Oh, I thought GPUOptions is parallel to ConfigProto according to the protobuf message. Thanks!

What about the first problem? Normally deleting an object in python does not guarantee releasing memories, also the case here relates to GPU. It is up to tensorflow to decide what to do. Is that right? Or am I missing something?

**Comment by vrv** [comment]
Not sure, you could try invoking python's garbage collector?

**Comment by shawnLeeZX** [comment]
Already tried before.

gc.collect()

did not work.
​

**Comment by vrv** [comment]
Well, I'm out of ideas :(.  Hopefully allow_growth is good enough for you.

**Comment by shawnLeeZX** [comment]
Thanks anyway. I switched to use sub shell call instead of multi-processing.

Unfortunately, I cannot use allow_growth now. Version 0.7.1 and current master HEAD seem to have a serious performance problem in some ops, split, reshape or concat(about 20 times slower, I am sure I am using GPU). I fall back to 0.6.0 now. Do not have time to check where goes wrong yet.

**Comment by keskival** [comment]
TensorFlow preallocates all the memory in self-managed pools. nvidia-smi does not show the pool use percentage, because only TensorFlow know that. You could try tensorboard, not sure if it shows the memory status.

See this:
http://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory

**Comment by hadivafaei** [comment]
I was having the same problem, running tensorflow with CUDA 8.0 and cuDNN 6.0 on Ubuntu 17.10. This is what worked for me:

1.  Open activities and search for 'System Monitor'
2.  Sort by memory used and find a python process that's using the most memory (~2 GiB in my case)
3.  Click end process

Immediately after I ended that python process the memory was released as I verified using nvidia-smi

**Comment by AliceDinh** [comment]
@vrv Hi, where to put these lines?
```
config = tf.ConfigProto()
config.gpu_options.allow_growth=True
sess = tf.Session(config=config)
```

**Comment by hattajr** [comment]
In my case, i can not get keras.backend modul. so,

`from tensorflow.compat.v1 import ConfigProto`
`from tensorflow.compat.v1 import InteractiveSession`
`config = ConfigProto()`
`config.gpu_options.allow_growth = True`
`session = InteractiveSession(config=config)`

I don't have much experience with this, so let me know if I did it wrong.
