### ISSUE TITLE
configure.py environment variables

### ISSUE THREAD

**Issue by JasonAtNvidia** [tensorflow/tensorflow#15795]
Have I written custom code: No
OS Platform and Distribution: Linux (Any?)
TensorFlow installed from: Source
TensorFlow version: 1.4 (Master Branch)
Bazel version: 0.6
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

### System information
- Building from source
- Branch Master (currently d87a9fbbc5f49ec5ae8eb52c62628f0b1a0bf67f)

### Describe the problem
Line 1353 of configure.py needs to have int( ) wrapped around the function get_var, otherwise the string that is returned always flags positive and setting TF_SET_ANDROID_WORKSPACE=0 environment variable to avoid user interaction in building from source will never work.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by JasonAtNvidia** [comment]
It appears to have been fixed with update 136697ecdc64b5171522fb7f89cfe51a02f0f1c1.

Thank you
