### ISSUE TITLE
Can we install tensorflow with a package manager in Linux distro?

### ISSUE THREAD

**Issue by leemgs** [tensorflow/tensorflow#15806]
As we all know, Tensorflow is a major opensource deeplearning framework to the developers. 
BTW, How can we install tensorflow with a package manager such as apt-get (for *.deb), yum/zypper/dnf (for *.rpm)  in Linux distro?

* Reference - https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build/builds

I could not find related scripts from the abvloe web address. Does tensorflow support 1)  manual compilation with ./tools/ci_build/build/*.sh and 2) pre-built docker-based compilation only?

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7.0 and Ubuntu 16.04.3
- **TensorFlow installed from (source or binary)**: Latest version of Tensorflow (form github)
- **TensorFlow version (use command below)**: Latest version of Tensorflow (form github)
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: with Cmake (w/o Bazel)
- **GCC/Compiler version (if compiling from source)**: GCC 5.0
- **CUDA/cuDNN version**:  None (w/ CPU only)
- **GPU model and memory**: None , DRAM 16GB
- **Exact command to reproduce**:   Nonthing.

### Describe the problem
No support

### Source code / logs
Omission.

**Comment by tfboyd** [comment]
pip is the most popular way to install TensorFlow for Python. 
https://www.tensorflow.org/install/

There are no current plans to support install via apt-get, rpm, or other package manager.  The Anaconda team also has builds but I would stick with pip to get the best possible support as the Anaconda builds are done by a third-party.  I am not anti-Anaconda and finding the right wording is not easy.  At some point the Anaconda builds may be very good and maybe offer some additional options in the form of more CPU optimizations.
