### ISSUE TITLE
Calling variable property of DropoutWrapper gives Error: AttributeError: 'DropoutWrapper' object has no attribute 'trainable'

### ISSUE THREAD

**Issue by michaelkhan3** [tensorflow/tensorflow#15810]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Using docker container minimaxir/keras-cntk:cpu-compiled (https://hub.docker.com/r/minimaxir/keras-cntk/tags/)
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.2.1 also tested on 1.4
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: 
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
I was trying to access the weights and biases of an BasicLSTM cell I created. The BasicLSTM cell also has a DropoutWrapper and when trying to access the variables property the below error is thrown.
`AttributeError: 'DropoutWrapper' object has no attribute 'trainable'`

Someone tried to help me with the error on stackoverflow (second half of this [answer](https://stackoverflow.com/a/47643427/1169493)) and noticed that while variables is implemented in Layer. 

I will quote his very helpful response below:

> Although variables is documented for most (all?) RNN classes, it does break for DropoutWrapper. The property has been documented since r1.2, but accessing the property causes an exception in 1.2 and 1.4 (and looks like 1.3, but untested). Specifically,
> 
> from tensorflow.contrib import rnn
> ...
> lstm_cell = rnn.BasicLSTMCell(num_hidden, forget_bias=1.0)
> wrapped_cell = rnn.DropoutWrapper(lstm_cell)
> outputs, states = rnn.static_rnn(wrapped_cell, x, dtype=tf.float32)
> print("LSTM vars!", lstm_cell.variables)
> print("Wrapped vars!", wrapped_cell.variables)
> will throw AttributeError: 'DropoutWrapper' object has no attribute 'trainable'. From the traceback (or a long stare at the DropoutWrapper source), I noticed that variables is implemented in DropoutWrapper's super RNNCell's super Layer. Dizzy yet? Indeed, we find the documented variables property here. It returns the (documented) weights property. The weights property returns the (documented) self.trainable_weights + self.non_trainable_weights properties. And finally the root of the problem:

```
 @property
 def trainable_weights(self):
     return self._trainable_weights if self.trainable else []
 
 @property
 def non_trainable_weights(self):
     if self.trainable:
         return self._non_trainable_weights
     else:
        return self._trainable_weights + self._non_trainable_weights
```

> That is, variables does not work for a DropoutWrapper instance. Neither will trainable_weights or non_trainable_weights sinceself.trainable is not defined.
> 
> One step deeper, Layer.__init__ defaults self.trainable to True. Where that property gets removed, deled, unset, whatever from a DropoutWrapper object, I cannot tell.

**Comment by flauted** [comment]
I am that answerer, by the way. I'm curious why ``DropoutWrapper`` doesn't have a ``variables`` property, too.

**Comment by skye** [comment]
@ebrevdo can you comment? Thanks.

**Comment by ebrevdo** [comment]
DropoutWrapper does not have variables because it does not itself store any.  It wraps a cell that may have variables; but it's not clear what the semantics should be if you access the `DropoutWrapper.variables`.  For example, all keras layers only report back the variables that they **own**; and so only one layer ever **owns** any variable.  That said, this should probably return `[]`, and the reason it doesn't is that `DropoutWrapper` never calls `super().__init__` in its constructor.  That should be an easy fix; PRs welcome.

**Comment by michaelkhan3** [comment]
I have come up with a workaround while we wait for the permanent fix.
Instead of calling `one_kernel, one_bias = one_lstm_cell.variables` we can use `one_kernel, one_bias = one_lstm_cell._cell.variables`. This calls variables on the original RNNCell passed in. I know it's generally not a good idea to call protected properties but it works.

**Comment by ebrevdo** [comment]
It may make sense to add a @property "cell" or "wrapped_cell" to
DropoutWrapper, specifically for use cases like this.  Would you like to
send a PR?

**Comment by michaelkhan3** [comment]
@ebrevdo Sure.  I'll send one soon

**Comment by dmoham1476** [comment]
For me, even this is returning an empty list.  I have tf 1.5

lstm_cell = rnn.BasicLSTMCell(num_hidden, forget_bias=1.0)

print("LSTM vars!", lstm_cell.variables)

**Comment by ebrevdo** [comment]
Variables aren't created until after you call lstm_cell at least once.
This is because it doesn't know the input shape yet, so it can't create the
variables, which are shaped [*input_depth*, num_units].

**Comment by ebrevdo** [comment]
You can also call lstm_cell.build(input_shape)  to create the variables
without creating any computation ops.
