### ISSUE TITLE
TFGAN not compatible with eager execution mode

### ISSUE THREAD

**Issue by jppgks** [tensorflow/tensorflow#15821]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Colaboratory Google Compute Engine backend (not sure about OS here)
- **TensorFlow installed from (source or binary)**: binary (non-GPU version)
- **TensorFlow version (use command below)**: 1.5.0-dev20180102
- **Python version**: 3

### Describe the problem
When enabling eager execution mode
```python
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()
```
and running 
```python
noise_dims = 64
gan_model = tfgan.gan_model(
    generator_fn,
    discriminator_fn,
    real_data=images,
    generator_inputs=tf.random_normal([batch_size, noise_dims]))
```
from the [TFGAN tutorial](https://github.com/tensorflow/models/blob/master/research/gan/tutorial.ipynb) by @joel-shor, I get the following error:
```bash
ValueError: When Eager Execution is enabled, variable collections are not supported.
```
because of the following lines:
https://github.com/tensorflow/tensorflow/blob/8c2d6fc2b0202304885d5d6c3cba57eb2a1b3262/tensorflow/contrib/gan/python/train.py#L119-L121
.

Are there any plans to make TFGAN compatible with eager in the short term? Is there any help wanted in this regard? I'd be happy to contribute.

**Comment by asimshankar** [comment]
@iganichev should have an example of a GAN using eager execution shortly and may have more to add.

**Comment by jppgks** [comment]
Currently, I'm able to create a GAN using eager execution, without making use of TFGAN - _see [notebook on generating samples from 1-D Gaussian](https://github.com/jppgks/shenanigan/blob/master/1-generating-samples-from-1D-gaussian.ipynb) for context_:

1. Enable eager

```python
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()
```

2. Define the model

```python
class MLP(tfe.Network):
  def __init__(self):
    super(MLP, self).__init__()
    self.layer1 = self.track_layer(tf.layers.Dense(units=30, activation=tf.nn.tanh))
    self.layer2 = self.track_layer(tf.layers.Dense(units=1, activation=tf.nn.tanh))
    
  def call(self, input):
    """Actually runs the model."""
    result = self.layer1(input)
    result = self.layer2(result)
    return result
```

3. Create generator and discriminator

```python
with tf.variable_scope("G"):
  G = MLP()
with tf.variable_scope("D"):
  D = MLP()
```

4. Define optimizers, ...

```python
# For the generator
batch_g = tfe.Variable(0)
learning_rate = tf.train.exponential_decay(
  0.001,  # Base learning rate.
  batch_g,  # Current index into the dataset.
  TRAIN_ITERS // 4,  # Decay step - this decays 4 times throughout training process.
  0.95,  # Decay rate.
  staircase=True)
opt_g=tf.train.MomentumOptimizer(learning_rate, 0.6)

# For the discriminator
batch = tfe.Variable(0)
learning_rate = tf.train.exponential_decay(
  0.001,  # Base learning rate.
  batch,  # Current index into the dataset.
  TRAIN_ITERS // 4,  # Decay step - this decays 4 times throughout training process.
  0.95,  # Decay rate.
  staircase=True)
discriminator_optimizer=tf.train.MomentumOptimizer(learning_rate, 0.6)
```

5. ...and value functions

```python
# Used when taking tf.log(), so we don't end up doing tf.log(0)
TINY = tf.constant(1e-8, dtype=tf.float64)

def value_function(D, G, x, z):
  # D(x), x sampled from data distribution
  p_norm_data = D(x) # output likelihood of being normally distributed
  D1 = tf.maximum(tf.minimum(p_norm_data, .99), 0.01) # clamp as a probability

  # D(x), x sampled from model distribution as G(z)
  generated_samples = G(z)
  generated_samples = tf.multiply(5.0, generated_samples)
  p_norm_gen = D(generated_samples)
  D2 = tf.maximum(tf.minimum(p_norm_gen, .99), 0.01)
  
  # v(\theta^g, \theta^d)
  loss = tf.reduce_mean(tf.log(D1 + TINY) + tf.log(1 - D2 + TINY))
  return loss

def neg_value_function(D, G, x, z):
  '''Because our optimizers will minimize the loss function passed in,
  we define the _negative_ value function.
  
  Instead of maximizing the value function, 
  the discriminator will minimize this _negative_ value function.
  '''
  return -value_function(D, G, x, z)
```

6. Train

```python
# Algorithm 1 of Goodfellow et al. (2014)

# Number of discriminator updates per epoch
k = 5
# Setup log of loss throughout training
histd, histg = np.zeros(TRAIN_ITERS), np.zeros(TRAIN_ITERS)

for i in range(TRAIN_ITERS):
  # Train discriminator.
  for j in range(k):
    ## 1) Sample data,
    x = sample_data(batch_size=M)
    
    ## 2) Sample noise prior,
    z = sample_noise_prior(batch_size=M)

    ## 3) Compute all partial derivatives of the loss function,
    histd[i], grads_and_vars = tfe.implicit_value_and_gradients(neg_value_function)(D, G, x, z)
    
    ## 4) Optimize discriminator, and not generator (!).
    discriminator_grads_and_vars = [gv for gv in grads_and_vars if gv[1].name.startswith('D/')]
    discriminator_optimizer.apply_gradients(discriminator_grads_and_vars, global_step=batch)

  # Train generator.
  ## 1) Sample noise prior,
  z = sample_noise_prior(batch_size=M)
  
  ## 2) Compute all partial derivatives of the loss function
  histg[i], grads_and_vars = tfe.implicit_value_and_gradients(value_function)(D, G, x, z)
  
  ## 3) Optimize generator, and not discriminator (!)
  generator_grads_and_vars = [gv for gv in grads_and_vars if gv[1].name.startswith('G/')]
  opt_g.apply_gradients(generator_grads_and_vars, global_step=batch)
```

**Comment by iganichev** [comment]
As Asim mentioned, an example eager GAN should be up shortly. It is fairly similar to your code, but uses GradientTape and trains G and D at the same time. There are no concrete plans of making TFGAN eager friendly in the very near future that I am aware of. @joel-shor, do you have some bandwidth to discuss potential approaches to making TFGAN eager friendly? @jppgks is willing to contribute.

**Comment by jppgks** [comment]
@iganichev I didn't manage to get TFGAN loss functions to work with `tfe.implicit_value_and_gradients`. Do you have a minimal working example of this?

**Comment by iganichev** [comment]
@jppgks the eager GAN example was merged and should make it to github very soon. Though it does not use `implicit_value_and_gradients` because it wants to compute multiple gradients over the same computation.  What issue are you facing?

**Comment by jppgks** [comment]
@iganichev That’s great news! 

When I pass `tf.contrib.gan.losses.minimax_loss_discriminator` to `implicit_value_and_gradients` and then call it with discriminator output on real and generated samples, I get an error that there are no variables to compute the gradients on.

**Comment by iganichev** [comment]
@jppgks The reason this does not work is because the computation involving variables is done outside of the function passed to `implicit_value_and_gradients`. In your code you call `D` and `G` inside the `value_function`. You need to do the same when using GAN losses.

**Comment by jppgks** [comment]
@iganichev Thanks a lot for the help with debugging, I made it work using the suggestion in your last comment 💯

**Comment by joel-shor** [comment]
Apologies for the delay!

I do have plans to make TFGAN TF-Eager compatible. I'll discuss with @iganichev and update this thread ASAP.

**Comment by jppgks** [comment]
That’s good to hear! Let me know if I can help with anything.

**Comment by joel-shor** [comment]
TFGAN is fundamentally functional, and a number of TF-Eager paradigms are class-based. I think making TFGAN eager-compatible would require basically a re-write of the library, so we're not going to actively pursue this.

**Comment by jppgks** [comment]
I understand. I will be switching back to non-eager TensorFlow for now, so I can make use of TFGAN.
