### ISSUE TITLE
ci.tensorflow.org lacks a security certificate

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorflow#15827]
### The Problem
https://ci.tensorflow.org/ now lacks a security certificate (or it expired).
To repro, visit https://ci.tensorflow.org/. Chrome will note that the connection is not private.

This is breaking TensorBoard's tests that run on travis. The tests `pip install` nightly versions of TensorFlow from these URLs:

- https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-1.head-cp27-none-linux_x86_64.whl 
- https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=cpu-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-1.head-cp34-cp34m-linux_x86_64.whl

### Error Logs from a Failed Test Run

> Collecting tensorflow==1.head from https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-1.head-cp27-none-linux_x86_64.whl
> Exception:
> Traceback (most recent call last):
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
>     wb.build(autobuilding=True)
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
>     self.requirement_set.prepare_files(self.finder)
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
>     ignore_dependencies=self.ignore_dependencies))
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
>     session=self.session, hashes=hashes)
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
>     hashes=hashes
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
>     hashes)
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 853, in _download_http_url
>     stream=True,
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
>     return self.request('GET', url, **kwargs)
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 386, in request
>     return super(PipSession, self).request(method, url, *args, **kwargs)
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
>     resp = super(CacheControlAdapter, self).send(request, **kw)
>   File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 497, in send
>     raise SSLError(e, request=request)
> SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

**Comment by chihuahua** [comment]
This bug seems related to #12496.

**Comment by chihuahua** [comment]
We are going to try using `pip install tf-nightly` instead of pip installing the whl URL.

**Comment by gunan** [comment]
The current certificate expired, but we are looking into killing off ci.tensorflow.org in favor of kokoro, too.
In the meantime, would it be OK if we dropped SSL from ci.tensorflow.org and used `http://ci.tensorflow.org/` ?

**Comment by chihuahua** [comment]
Thank you @gunan! That is fine because we found that `pip install tf-nightly` works.

We are now grappling with a different issue.

**Comment by gunan** [comment]
The certificate is renewed and deployed.
