### ISSUE TITLE
Feature Request: saver.save mkdir if directory not exist

### ISSUE THREAD

**Issue by shitian-ni** [tensorflow/tensorflow#15832]
### Describe the problem
`saver.save(sess, 'my-model') `
returns error if directory not exist.
It would be nice if saver can automatically create the missing directory.
`Traceback (most recent call last):
  File "tf_voice_recognition.py", line 783, in <module>
    saver.save(sess, 'my-model')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1594, in save
    raise exc
ValueError: Parent directory of my-model doesn't exist, can't save.
`

**Comment by formath** [comment]
You can use absolute path.

**Comment by shitian-ni** [comment]
@formath Worked. Thanks. What about a feature to allow relative paths as well?

**Comment by formath** [comment]
It's not ok to use relative path in distributed training such as hdfs. So, absolute path is more general.

**Comment by shitian-ni** [comment]
@formath I see. Thank you.
