### ISSUE TITLE
*** Error in `python': double free or corruption (out): 0x00007fc5d674d9b0 ***

### ISSUE THREAD

**Issue by DavidBrayford** [tensorflow/tensorflow#15848]
I've built the latest version of TensorFlow from github repository with the following commands.

bazel build -s --config=mkl -c opt --copt=-msse4.1 --copt=-msse4.2 //tensorflow/tools/pip_package:build_pip_package

bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

pip install /tmp/tensorflow_pkg/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl

And get the following error after the import tensorflow command in python

Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 16 2017, 15:28:36) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> import tensorflow as tf
*** Error in `python': double free or corruption (out): 0x00007fc5d674d9b0 ***

Any suggestions on how to fix this issue?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by DavidBrayford** [comment]
Have I written custom code
> No, only built and ran the test program.
OS Platform and Distribution
> SLES12
TensorFlow installed from
> github repository
TensorFlow version
> release 1.5.0
Bazel version
> 0.9.0
CUDA/cuDNN version
> Not using CUDA
GPU model and memory
> Not using GPU
Exact command to reproduce
> import tensorflow as tf

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment]
Do you have a stack trace?

CC @gunan

**Comment by gunan** [comment]
@tfboyd to redirect the MKL issue to intel.

**Comment by DavidBrayford** [comment]
This issues can be closed. As after updating Python the error went away.
