### ISSUE TITLE
unable to install from source with undefined external dependency target error

### ISSUE THREAD

**Issue by tangdehong** [tensorflow/tensorflow#15850]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: r1.4.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.9.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: no
- **GPU model and memory**: no
- **Exact command to reproduce**:
`sudo bazel build --config=opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package`
### Describe the problem
 I'm trying to install r1.4.0 from source with CPU version and follow the install guidelines on the official website.  But some errors occur. (The errors are shown in "Source code / logs" )
(1) It seems that the undefined external dependency target "@local_config_sycl" is referred in some files (eg. //tensorflow-1.4.0/ third_party/eigen3/build ).
(2) I am sure the openCL suppurt is disabled when configure.
(3) I tried to install version r1.0.1 from source, but the same errors occur.
(4) I tried to install version r1.4.0 from binary, and success.

Why this happens and how can I fix it? Thank you!

### Source code / logs
`ERROR: /home/tangdehong/.cache/bazel/_bazel_root/4bf03e1269a0e4905c62fa69a980acb4/external/local_config_sycl/sycl/BUILD:4:1: First argument of 'load' must be a label and start with either '//', ':', or '@'. Use --incompatible_load_argument_is_label=false to temporarily disable this check.
ERROR: /home/tangdehong/.cache/bazel/_bazel_root/4bf03e1269a0e4905c62fa69a980acb4/external/local_config_sycl/sycl/BUILD:6:1: First argument of 'load' must be a label and start with either '//', ':', or '@'. Use --incompatible_load_argument_is_label=false to temporarily disable this check.
ERROR: /home/tangdehong/.cache/bazel/_bazel_root/4bf03e1269a0e4905c62fa69a980acb4/external/local_config_sycl/sycl/BUILD:30:9: Traceback (most recent call last):
	File "/home/tangdehong/.cache/bazel/_bazel_root/4bf03e1269a0e4905c62fa69a980acb4/external/local_config_sycl/sycl/BUILD", line 27
		cc_library(name = "syclrt", srcs = [sycl_libr...")], <3 more arguments>)
	File "/home/tangdehong/.cache/bazel/_bazel_root/4bf03e1269a0e4905c62fa69a980acb4/external/local_config_sycl/sycl/BUILD", line 30, in cc_library
		sycl_library_path
name 'sycl_library_path' is not defined
ERROR: /home/tangdehong/.cache/bazel/_bazel_root/4bf03e1269a0e4905c62fa69a980acb4/external/local_config_sycl/sycl/BUILD:39:1: Target '@local_config_sycl//sycl:using_sycl' contains an error and its package is in error and referenced by '@local_config_sycl//sycl:sycl'
ERROR: /home/tangdehong/OpenSourceCode/tensorflow-1.4.0/third_party/eigen3/BUILD:20:1: Target '@local_config_sycl//sycl:sycl' contains an error and its package is in error and referenced by '//third_party/eigen3:eigen3'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Loading failed
INFO: Elapsed time: 0.745s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/contrib/losses ... (17 packages)
`
Thank you!

**Comment by skye** [comment]
@yifeif @gunan any ideas?

**Comment by gunan** [comment]
I think there was a change in bazel that made our bazel files break.
If you need 1.4 release, you may need to roll back your bazel version to 0.5.4 or something close.
Otherwise, please try with 1.5 release.

Could you try one of the above ant let me know if it solves your problem?

**Comment by xav12358** [comment]
I get the same error : 

`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
........
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:96:1: First argument of 'load' must be a label and start with either '//', ':', or '@'. Use --incompatible_load_argument_is_label=false to temporarily disable this check.
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:98:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:100:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:102:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:104:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:106:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:108:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:110:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:112:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:114:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:116:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:118:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:120:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:122:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:124:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:126:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:131:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:136:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:141:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:146:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/com_googlesource_code_re2/BUILD:151:1: name 're2_test' is not defined (did you mean 'ios_test'?)
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/local_config_sycl/sycl/BUILD:4:1: First argument of 'load' must be a label and start with either '//', ':', or '@'. Use --incompatible_load_argument_is_label=false to temporarily disable this check.
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/local_config_sycl/sycl/BUILD:6:1: First argument of 'load' must be a label and start with either '//', ':', or '@'. Use --incompatible_load_argument_is_label=false to temporarily disable this check.
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/local_config_sycl/sycl/BUILD:41:9: Traceback (most recent call last):
	File "/home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/local_config_sycl/sycl/BUILD", line 38
		cc_library(name = "syclrt", srcs = [sycl_libr...")], <3 more arguments>)
	File "/home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/local_config_sycl/sycl/BUILD", line 41, in cc_library
		sycl_library_path
name 'sycl_library_path' is not defined
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/local_config_sycl/sycl/BUILD:50:1: Target '@local_config_sycl//sycl:using_sycl_ccpp' contains an error and its package is in error and referenced by '@local_config_sycl//sycl:sycl'
ERROR: /home/xavier/.cache/bazel/_bazel_xavier/ef54af8645dec4f38c438d8e1c779747/external/local_config_sycl/sycl/BUILD:50:1: Target '@local_config_sycl//sycl:using_sycl_trisycl' contains an error and its package is in error and referenced by '@local_config_sycl//sycl:sycl'
ERROR: /home/xavier/Bureau/developpement/NeuralNetwork/tensorflow/third_party/eigen3/BUILD:20:1: Target '@local_config_sycl//sycl:sycl' contains an error and its package is in error and referenced by '//third_party/eigen3:eigen3'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Loading failed
INFO: Elapsed time: 4.217s
FAILED: Build did NOT complete successfully (101 packages loaded)
    currently loading: tensorflow/core ... (2 packages)
`

I can't solve it. Can someone help me ?

**Comment by gunan** [comment]
@xav12358 Please see my comment right above your question

**Comment by tangdehong** [comment]
@gunan Thank you very much for your help. 
1. I try to build tensorflow-1.5.0rc0 with bazel 0.9.0, and success.Although there are still some warnings like comparison between signed int and unsigned int, breaking strict-aliasing rules.
2. The "Hello, tensorflow!" example runs well.

**Comment by tangdehong** [comment]
@xav12358 
I build tensorflow-1.5.0rc0 with bazel 0.9.0 following gunan's comment, and success. Maybe you can have a try.
