### ISSUE TITLE
tensorflow/go for Windows?

### ISSUE THREAD

**Issue by moorage** [tensorflow/tensorflow#15869]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: either
- **TensorFlow version (use command below)**: 1.4+
- **Python version**: n/a
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: MINGW64
- **CUDA/cuDNN version**: none
- **GPU model and memory**: none
- **Exact command to reproduce**: visit https://www.tensorflow.org/versions/master/install/install_go

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Feature request: https://www.tensorflow.org/versions/master/install/install_go doesn't have Windows 10 instructions.  I am curious if the tensorflow/go will be installable for windows

### Source code / logs
I currently get an error on the `ld.exe` phase of the go get . for github.com/tensorflow/tensorflow/tensorflow/go : `cannot find -ltensorflow`.  I'm not sure how to specify that the `tensorflow.dll` should be used.

**Comment by Mikerr1111** [comment]
Are you using the Fall Creators Update(Windows 10)?

**Comment by moorage** [comment]
@Mikerr1111 I'm on Windows 10 Pro

**Comment by asimshankar** [comment]
The C library (`tensorflow.dll`) that is required (and used via cgo) is available for Windows (see related https://github.com/tensorflow/tensorflow/issues/8773#issuecomment-349414677).

I'm not familiar enough with the use of cgo and dynamic libraries in Windows to provide a useful answer. However, if someone else can provide instructions then please share, or better yet, send in a pull request updating `tensorflow/go/README.md`.

**Comment by carusyte** [comment]
+1 waiting for update on this issue. Some of the bot automation programs in the business world do need to run on Windows, though I personally not so interested on Windows application development...

**Comment by lanybass** [comment]
2019.. still waiting..
Dose anybody using cgo with tensorflow.dll make a demo for windows?

**Comment by bdleitner** [comment]
Especially with TF2.0 out, it would be really nice to be able to use TF on windows with golang, and to be able to do so for both the training and use stages.

**Comment by Sakurasan** [comment]
9102.10-18
no update

**Comment by Kent-H** [comment]
After much frustration & hackery, I think I've got it working.

### Process:
1. Download the go bindings for windows.
https://www.tensorflow.org/install/lang_c#download
2. Convert the provided lib to one that's understood by the MinGW GCC using 
   1. `gendef tensorflow.dll`
(should generate a `tensorflow.def` file)
   2. `dlltool --kill-at --input-def tensorflow.def --ouput-lib tensorflow.a`
(should generate a tensorflow.a file)
3. Copy the generated files into the relevant places on the system.
   1. Copy the tensorflow.a file to `C:\TDM-GCC-64\lib\`, and _rename_ it to `tensorflow.dll`
(Be careful: at this point you will have a _new_ `tenstorflow.dll`, and an _original_ `tensorflow.dll`
   2. Copy the _original_ `tensorflow.dll` file into to `C:\Windows\System32\`.
(Or to the location that *.dlls should be installed to on your version of windows.)

That's it!  
You should now be able to compile go projects that depend on `github.com/tensorflow/tensorflow/tensorflow/go`

### Debugging note:
* If your program compiles OK, but immediately crashes with exit code `3221225781`/`0xc0000135 `, it's failing to find/load the _original_ *.dll file (or possibly some unrelated dll, this error code is used for dll loading errors).  
The _new_ *.dll file does not seem to load properly at runtime, you'll need the original.
* Be careful of versioning, the tensorflow version of both *.dlls, as well as the version of the golang binding should all match.

### Resources that were helpful to me:
* https://groups.google.com/d/msg/golang-nuts/i6UWSCPSRl4/Sul31sGH9yUJ
* https://mingw-w64-public.narkive.com/csdoiOTE/using-gendef-and-dlltool-reopening-the-pandora

### If you can't get it to work...
I have attached the generated *.def and *.a files, you can use these and skip to step 3 above.
You shouldn't use these unless you really trust me; generate your own as described above.

[libtensorflow-cpu-windows-x86_64-1.15.0-.def-and.a-files.zip](https://github.com/tensorflow/tensorflow/files/4333022/libtensorflow-cpu-windows-x86_64-1.15.0-.def-and.a-files.zip)

**Comment by qinjinze** [comment]
I hope there is a time plan to support windows
