### ISSUE TITLE
TensorFlow fails to build with MPI

### ISSUE THREAD

**Issue by bhavani-subramanian** [tensorflow/tensorflow#15866]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7.4
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: r1.5
- **Python version**: 2.7.5
- **Bazel version (if compiling from source)**: 0.9.0 & 0.7.0
- **GCC/Compiler version (if compiling from source)**: 6.3.0
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
bazel build --copt -mfma --copt -mavx2 --copt -O3 --verbose_failures -s -c opt //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
TensorFlow fails to build with MPI with the following error:
```
ERROR: /disk/public_tf/tensorflow/tensorflow/contrib/mpi_collectives/BUILD:40:1: undeclared inclusion(s) in rule '//tensorflow/contrib/mpi_collectives:python/ops/_mpi_ops.so':
this rule is missing dependency declarations for the following files included by 'tensorflow/contrib/mpi_collectives/kernels/mpi_ops.cc':
  '/disk/public_tf/tensorflow/tensorflow/stream_executor/lib/statusor.h'
  '/disk/public_tf/tensorflow/tensorflow/stream_executor/platform/port.h'
  '/disk/public_tf/tensorflow/tensorflow/stream_executor/lib/error.h'
  '/disk/public_tf/tensorflow/tensorflow/stream_executor/lib/status.h'
  '/disk/public_tf/tensorflow/tensorflow/stream_executor/lib/stringpiece.h'
  '/disk/public_tf/tensorflow/tensorflow/stream_executor/platform/logging.h'
tensorflow/contrib/mpi_collectives/kernels/mpi_ops.cc:128:6: warning: 'bool tensorflow::contrib::mpi_collectives::{anonymous}::IsGPUDevice() [with T = Eigen::GpuDevice]' defined but not used [-Wunused-function]
 bool IsGPUDevice<GPUDevice>() {
      ^~~~~~~~~~~~~~~~~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 379.332s, Critical Path: 76.80s
FAILED: Build did NOT complete successfully
```
This error persists even when Bazel 0.7.0 is used to build TensorFlow.

**Comment by Independent-Scientist** [comment]
Stumbled upon the same error.

**System information**

    Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
    TensorFlow installed from (source or binary): Source
    TensorFlow version (use command below): r1.4.1
    Python version: 2.7.14 Anaconda
    Bazel version (if compiling from source): 0.5.4
    GCC/Compiler version (if compiling from source): 4.8
    CUDA/cuDNN version: N/A
    GPU model and memory: N/A

    **Exact command to reproduce:**
    bazel build --verbose_failures --config=opt //tensorflow/tools/pip_package:build_pip_package

**Describe the problem**

TensorFlow fails to build with MPI with the following error:

ERROR: /home/singletron/source/tensorflow/tensorflow/contrib/mpi_collectives/BUILD:40:1: undeclared inclusion(s) in rule '//tensorflow/contrib/mpi_collectives:python/ops/_mpi_ops.so':
this rule is missing dependency declarations for the following files included by 'tensorflow/contrib/mpi_collectives/kernels/mpi_ops.cc':
  '/home/singletron/source/tensorflow/tensorflow/stream_executor/lib/statusor.h'
  '/home/singletron/source/tensorflow/tensorflow/stream_executor/platform/port.h'
  '/home/singletron/source/tensorflow/tensorflow/stream_executor/lib/error.h'
  '/home/singletron/source/tensorflow/tensorflow/stream_executor/lib/status.h'
  '/home/singletron/source/tensorflow/tensorflow/stream_executor/lib/stringpiece.h'
  '/home/singletron/source/tensorflow/tensorflow/stream_executor/platform/logging.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 871.316s, Critical Path: 50.18s
FAILED: Build did NOT complete successfully

**Comment by Independent-Scientist** [comment]
Managed to build r1.5 successfully with openmpi-3.0 and bazel 0.5.4!

**Comment by skye** [comment]
@gunan looks like we don't build with the latest version of bazel? (@Independent-Scientist correct me if I've misunderstood)

**Comment by Independent-Scientist** [comment]
@skye It seems so. I followed the chart on tested builds at the "Installing TensorFlow from Sources" page. Although there is no r1.5 hint the latest versions use bazel 0.5.4.

**Comment by gunan** [comment]
@av8ramit Could you check?
Also we should add the setup we use for all new releases to the tables in install from sources page during each release.

**Comment by av8ramit** [comment]
@gunan yes, I think that might not have been updated properly. I'll investigate and fix this for current and future releases.

**Comment by av8ramit** [comment]
https://www.tensorflow.org/versions/r1.5/install/install_sources
