### ISSUE TITLE
tfcompile with --config=monolithic and -fvisibility=hidden results in undefined reference __xla_cpu_runtime_EigenMatMulF32

### ISSUE THREAD

**Issue by lissyx** [tensorflow/tensorflow#15876]
Some background first. For DeepSpeech, I have been experimenting simplification of our set of dependencies, trying to do a `--config=monolithic` build. The root cause for that was being able to run a `SYCL`-enabled build on my system (Ubuntu 17.10). Using `OpenCL` on this would trigger dependency load-chain that in the end loads `libmirprotobuf`. This would clash with the `protobuf` symbols already built in our `libtensorflow_framework` / `libtensorflow_cc`. To avoid this, monolithic build and forcing `visibility=hidden` seemed to be the best solution.

This allows us to move from those libraries (non tfcompile build, tfcompile adds `libdeepspeech_model.so` and all the `XLA` dependencies):
 - `libdeepspeech.so`
 - `libdeepspeech_utils.so`
 - `libtensorflow_cc.so`
 - `libtensorflow_framework.so`

To just:
 - `libdeepspeech.so`
 - `libdeepspeech_utils.so`

This way, we have all needed TensorFlow bits within `libdeepspeech.so`, and those symbols are not re-exported thus avoiding any unwanted interaction. I could get `SYCL` build nearly working on Intel GPU.

Adding `tfcompile` in the equation, however, lead to linking issues. Symptom would be that build completes, but when one links binary against the model's `.so`, then it fails with:
```
undefined reference __xla_cpu_runtime_EigenMatMulF32
```

Checking with `objdump -t bazel-bin/tensorflow/compiler/xla/service/cpu/_objs/runtime_matmul/tensorflow/compiler/xla/service/cpu/runtime_matmul*.o | grep EigenMatMul` would show that the symbol is properly built into `runtime_matmul`, but that it is hidden.

I would be able to solve that by exposing `__xla_cpu_runtime_EigenMatMulF32` and `__xla_cpu_runtime_EigenMatMulF64` through `TF_EXPORT`.

**Comment by lissyx** [comment]
The patch itself is rather trivial, but I'm wondering if it's a supported use-case enough to justify sending it upstream.

**Comment by skye** [comment]
@tatatodd can you comment?

**Comment by tatatodd** [comment]
@sanjoy knows better than me.

**Comment by sanjoy** [comment]
How about statically linking tensorflow/compiler/xla/service/cpu:runtime_matmul etc. with the .o generated from tfcompile?  That seems a bit cleaner to me.

I'm also curious about how you're using tfcompile -- typically I've seen folks either use the XLA JIT with TF, or use tfcompile to build a small graph that gets linked into the binary that does not otherwise use TF directly.

**Comment by lissyx** [comment]
Thanks! @sanjoy About linking statically, I was not so sure this would be the best approach, this felt more hacky to me, but I'll give it another try if you recommend so.

Regarding how we use `tfcompile`, that might be hacky to you but basically we have `deepspeech` binary, and `libdeepspeech.so`, and `libdeepspeech_model.so`. The last one is generated by `tfcompile` through `tf_library()`. We then link `deepspeech` binary with `-ldeepspeech` and `-ldeepspeech_model`. In `libdeepspeech`, we have codepath that depends on `libdeepspeech_model.so`.

We naively compile the whole model using `tfcompile`, it used to work not too bad :)

**Comment by sanjoy** [comment]
> Thanks! @sanjoy About linking statically, I was not so sure this would be the best approach, this felt more hacky to me, but I'll give it another try if you recommend so.

Now that I think of it, I'm wondering if you'll run into issues with the Eigen thread pool -- for instance, if you create a Eigen thread pool device using one version of the thread pool and pass it into a `__xla_cpu_runtime_EigenMatMulF32` statically linked to another version of the thread pool.  If you start running into issues like this, I'd say adding `TF_EXPORT` instead is fine.

**Comment by lissyx** [comment]
@sanjoy Right, I tried in the past the static link, and I've just re-tried. The reason I stopped was because of:
```
/usr/bin/ld: deepspeech: hidden symbol `__xla_cpu_runtime_EigenMatMulF32' in ../../tensorflow//bazel-bin/tensorflow/compiler/xla/service/cpu/_objs/runtime_matmul/tensorflow/compiler/xla/service/cpu/runtime_matmul.pic.o is referenced by DSO
/usr/bin/ld: final link failed: Bad value
```

**Comment by sanjoy** [comment]
> But since the symbol __xla_cpu_runtime_EigenMatMulF32 is a callback and that it is hidden

This is a little surprising to me -- hidden symbols should still be visible from .o files, `-fvisibility=hidden` should only be blocking visibility at the DSO level.  I'm also not sure what you mean by "callback".

**Comment by lissyx** [comment]
@sanjoy 
```
../../tensorflow//bazel-bin/native_client/libdeepspeech_model.so: undefined reference to `__xla_cpu_runtime_EigenMatMulF32'
```

And `libdeepspeech_model.so` is being built with `tf_library`. And inside the definition of `tf_library`, it does refers to `runtime_matmul`: https://github.com/mozilla/tensorflow/blob/1390dc180e25b5821be80b407ddc5fad73d4ef6a/tensorflow/compiler/aot/tfcompile.bzl#L197

However,
```
$ grep -c runtime_matmul bazel-out/local-opt/bin/native_client/libdeepspeech*.so-2.params 
bazel-out/local-opt/bin/native_client/libdeepspeech_model.so-2.params:0
bazel-out/local-opt/bin/native_client/libdeepspeech.so-2.params:1
bazel-out/local-opt/bin/native_client/libdeepspeech_utils.so-2.params:0
```

And:
```
$ grep runtime_matmul bazel-out/local-opt/bin/native_client/libdeepspeech.so-2.params
bazel-out/local-opt/bin/tensorflow/compiler/xla/service/cpu/_objs/runtime_matmul/tensorflow/compiler/xla/service/cpu/runtime_matmul.pic.o
$ objdump -t bazel-out/local-opt/bin/tensorflow/compiler/xla/service/cpu/_objs/runtime_matmul/tensorflow/compiler/xla/service/cpu/runtime_matmul.pic.o | grep MatMul
0000000000000000 l    d  .text.__xla_cpu_runtime_EigenMatMulF32 0000000000000000 .text.__xla_cpu_runtime_EigenMatMulF32
0000000000000000 l    d  .gcc_except_table.__xla_cpu_runtime_EigenMatMulF32     0000000000000000 .gcc_except_table.__xla_cpu_runtime_EigenMatMulF32
0000000000000000 l    d  .text.__xla_cpu_runtime_EigenMatMulF64 0000000000000000 .text.__xla_cpu_runtime_EigenMatMulF64
0000000000000000 l    d  .gcc_except_table.__xla_cpu_runtime_EigenMatMulF64     0000000000000000 .gcc_except_table.__xla_cpu_runtime_EigenMatMulF64
0000000000000000 g     F .text.__xla_cpu_runtime_EigenMatMulF32 000000000000061e .hidden __xla_cpu_runtime_EigenMatMulF32
0000000000000000 g     F .text.__xla_cpu_runtime_EigenMatMulF64 000000000000061e .hidden __xla_cpu_runtime_EigenMatMulF64
```

So, for some reason, `runtime_matmul.pic.o` is not being fed into `libdeepspeech_model.so`, only in `libdeepspeech.so`. With the symbol being hidden, it does account for the visibility because we are at DSO level. Maybe this is the real issue here, and maybe we should see `runtime_matmul.pic.o` in `bazel-out/local-opt/bin/native_client/libdeepspeech_model.so-2.params`.

For reference, here is our definition of `libdeepspeech_model.so`:
```

tf_library(
    name = "deepspeech_model",
    cpp_class = "DeepSpeech::nativeModel",
    # We don't need tests or benchmark binaries
    gen_test=False, gen_benchmark=False,
    # graph and config will be generated at build time thanks to the matching
    # genrule.
    graph = "tfcompile.model.pb",
    config = "tfcompile.config.pbtxt",
    # This depends on //tensorflow:rpi3 condition defined in mozilla/tensorflow
    tfcompile_flags = select({
        "//tensorflow:rpi3": str('--target_triple="armv6-linux-gnueabihf" --target_cpu="cortex-a53" --target_features="+neon-fp-armv8"'),
        "//conditions:default": str('')
    }),
)
```

And `libdeepspeech.so`:
```
tf_cc_shared_object(
    name = "libdeepspeech.so",
    srcs = ["deepspeech.cc", "deepspeech.h", "deepspeech_utils.h", "alphabet.h", "beam_search.h", "trie_node.h"] +
           if_native_model(["deepspeech_model.h"]) +
           glob(["kenlm/lm/*.cc", "kenlm/util/*.cc", "kenlm/util/double-conversion/*.cc",
                 "kenlm/lm/*.hh", "kenlm/util/*.hh", "kenlm/util/double-conversion/*.h"],
                exclude = ["kenlm/*/*test.cc", "kenlm/*/*main.cc"]) +
           glob(["boost_locale/**/*.hpp"]),
    copts = ["-std=c++11", "-Wno-sign-compare"] + if_native_model([
        "-DDS_MODEL_TIMESTEPS=$(DS_MODEL_TIMESTEPS)",
        "-DDS_NATIVE_MODEL=1",
    ]),
    deps = [
        "//tensorflow/core:core_cpu",
        "//tensorflow/core:direct_session",
        "//tensorflow/core/kernels:constant_op",        # Const
        "//tensorflow/core/kernels:identity_op",        # Identity
        "//tensorflow/core/kernels:transpose_op",       # Transpose
        "//tensorflow/core/kernels:reshape_op",         # Reshape
        "//tensorflow/core/kernels:shape_ops",          # Shape
        "//tensorflow/core/kernels:strided_slice_op",   # StridedSlice
        "//tensorflow/core/kernels:pack_op",            # Pack
        "//tensorflow/core/kernels:reverse_op",         # ReverseV2
        "//tensorflow/core/kernels:concat_op",          # ConcatV2
        "//tensorflow/core/kernels:split_op",           # Split
        "//tensorflow/core/kernels:sparse_to_dense_op", # SparseToDense
        "//tensorflow/core/kernels:relu_op",            # Relu
        "//tensorflow/core/kernels:bias_op",            # BiasAdd
        "//tensorflow/core/kernels:math",               # Range, MatMul
        "//tensorflow/core/kernels:tensor_array_ops",   # Placeholder, TensorArrayV3
        "//tensorflow/core/kernels:control_flow_ops",   # Enter
        "//tensorflow/core/kernels:ctc_ops",            # CTCBeamSearchDecoder
        ### Needed by production model produced without "--use_seq_length False"
        "//tensorflow/core/kernels:logging_ops",         # Assert
        "//tensorflow/core/kernels:reverse_sequence_op", # ReverseSequence
        # Classic deps
        "//tensorflow/core/util/ctc",
        "//third_party/eigen3",
    ] + if_native_model([
        "//tensorflow/compiler/tf2xla:xla_compiled_cpu_function",
        "//tensorflow/compiler/xla/service/cpu:runtime_matmul",
    ])
      + if_cuda([
        "//tensorflow/core:core",
        "//tensorflow/core/kernels:slice_op_gpu",       # Slice GPU
    ]),
    includes = ["kenlm", "boost_locale"],
    defines = ["KENLM_MAX_ORDER=6"],
)
```

**Comment by sanjoy** [comment]
This is speculation -- I'm not very familiar with Bazel -- but I wonder if you need to have a tf_cc_shared_object for libdeepspeech_model.so, and the libdeepspeech_model.so you're loading right now is the one we build for testing and assumes all of its dependencies are built and loaded as SOs as well.

In other words, you can either statically link in libdeepspeech_model.o and its deps (which includes matmul) into libdeepspeech.so; or you can create a "self contained" libdeepspeech_model.so by tf_cc_shared_object.

**Comment by lissyx** [comment]
Thanks, so it means `tf_library` is for testing only ? And thus it's expected behavior so far ?

**Comment by sanjoy** [comment]
> Thanks, so it means tf_library is for testing only ? And thus it's expected behavior so far ?

No, I meant to say that (I think) the `libdeepspeech_model.so` file you're loading is built under the assumption that all of the dependencies of the `tf_library` (which includes `:runtime_matmul`) are also going to be loaded dynamically (this mode is useful for running tests since you don't have to wait for the link step).  The tf_library rule itself is not test-only -- it generates .o files that you can link into a normal binary or a .so depending on what you want.

**Comment by lissyx** [comment]
Okay, this would come from `tf_library` relying on `native.cc_library`, while `tf_cc_shared_object` should be producing linking all of that as expected?

**Comment by sanjoy** [comment]
Yes, I think that's what's going on.

**Comment by lissyx** [comment]
I do confirm that it seems to be doing the trick, I got lurred by the definition of `tf_library` and the way bazel handles deps and linking. Thanks!

I'm going to close this issue then.

**Comment by RoboEvangelist** [comment]
Dude...so many issues with the new tensorflow versions. I might have to consider switching to cafee or something! hahaha
