### ISSUE TITLE
Successful Local Build of Tensorflow r1.5 GPU for Python 3.6, CUDA Toolkit 9.0, and CUDNN 7.0 on Windows 7 X64 SP1 using CMake in VS 2015 Update 3

### ISSUE THREAD

**Issue by ahendry2688** [tensorflow/tensorflow#15886]
I have spent a week trying to compile Tensorflow from source using Bazel on Windows with no success. In 2 days, I was able to compile it using CMake following the command output from a successful build I saw on Jenkins on 02-Jan-2018.

I wanted to provide details to spare others the pain of development in the future. The whole build took 6 hours to compile on my system.

I have an older system, which is why I was doing this. You will need to path variables in the attached scripts to work with the path variables for your system. For the most part, however, the scripts replicate what is mentioned on github here:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:  Yes

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 7 x64 SP1
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: r1.5.0-rc0
- **Python version**: 3.6.4
- **CMake version (if compiling from source)**: CMake 3.10.1
- **GCC/Compiler version (if compiling from source)**: cl.exe (Visual Studio 2015 Update 3)
- **CUDA/cuDNN version**: 9.0.176 / 7.0.4
- **GPU model and memory**: NVIDIA Quadro K4000 P8, Driver 385.54, 3072 MiB
- **SWIG Version**: swigwin-3.0.12
- **Git Version**: Git for Windows 2.15.1 64-bit
- **MSBuild Version**: 14.0.25420.1
- **CPU**: Intel Xeon E5-2620 v2

- **Exact command to reproduce**:

After installing the above, I wrote a batch script to set and clean up system environment variables (please see attached script). Due to the 1024 character limit for PATH on windows, I manually edited the PATH in the registry editor to overcome this limitation.

I then wrote another script that set local variables, cloned tensorflow source and checked out version 1.5, then prepared the source with cmake and compiled with msbuild.

The final output was a python wheel, which I pip installed. I successfully ran the standard hello world script without error, i.e.

```
import tensorflow as tf
hello = tf.constant('Hello')
sess = tf.Session()
sess.run(hello)
```

as well as a small AlexNet network without issues.

I hope this helps future users and further emphasizes that it is possible to build Tensorflow 1.5 for GPU on Windows 7. I have not compiled this with AVX support, but that could be a next improvement (I'm not sure if this is possible. I only know MKL support is limited to Linux at the moment. However, Windows binaries for MKL and MPI can be downloaded from the Intel website).

[Scripts.zip](https://github.com/tensorflow/tensorflow/files/1607554/Scripts.zip)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version

**Comment by ahendry2688** [comment]
Of course. Bazel is N/A as I did not use it.

**Comment by arunmandal53** [comment]
Successfully built tensorflow 1.5-rc0 using bazel on windows 10 but it does not include most of package from contrib. Also built using cmake on windows 10 and seems like it has most of package included but not tested yet.

**Comment by arunmandal53** [comment]
Ok i have created a tutorial for them who want to build Tensorflow GPU1.5.0 for windows with cuda 9.1 and cudnn 7.0.5. Visit my blog for step by step instructions hope this will help lot of people and doesn't create an issue for build problems. Here is link of my blog  http://www.python36.com/install-tensorflow-gpu-windows

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment]
Thank you very much for contributing this! We are moving to having a working bazel implementation for Windows that will be supported. For now, the CMake version is the best option that we support on a best effort basis.

I'm going to close this issue for administrative purposes, but it is much appreciated.

@MarkDaoust is there something we could use from there?
CC @guschmue @mrry

**Comment by MarkDaoust** [comment]
cc ewilderj@

**Comment by ewilderj** [comment]
@ahendry2688 thanks for your hard work! The good news is that we also now have a forum where this would be really appropriate to share, and perhaps you might want to help out with the work of the group. Please check out https://groups.google.com/a/tensorflow.org/forum/#!forum/tf-distribute for more details!
