### ISSUE TITLE
tensorflow binary image for ARM architecture

### ISSUE THREAD

**Issue by vivekian** [tensorflow/tensorflow#159]
Any chance that an ARM compatible tensorflow whl binary image is available for Linux?

**Comment by vrv** [comment]
Not at the moment -- you might try building from source for arm.  We don't really have a test infrastructure yet to make sure we keep it working, which is why we don't build the binary package for it.

**Comment by girving** [comment]
@petewarden: What's the status of this now?

**Comment by petewarden** [comment]
I'm hoping to work on this over the next couple of weeks.

**Comment by petewarden** [comment]
I actually misread this - I didn't realize it was discussing an ARM binary for Linux. I'm not likely to be working on that, the closest I have is the makefile support for the Raspberry Pi. I'm going to close this since it's an enhancement and is unlikely to be worked on soon.
