### ISSUE TITLE
nightly installed TF is the new 1.5 TF?

### ISSUE THREAD

**Issue by chg0901** [tensorflow/tensorflow#15907]
today I heard that there are a new version 1.5 TF which is with good support dynamic graph.

And I also find there is a new nightly installed method.

So this nightly installing method is install the new Version TF?

```
chg0901@ubuntu:~$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2018-01-06 16:49:32.242801: I tensorflow/core/platform/s3/aws_logging.cc:53] Initializing Curl library
>>> print(tf.__version__)
1.6.0-dev20180105
>>> x = [[2.]]
>>> m = tf.matmul(x,x)
>>> print(m)
Tensor("MatMul:0", shape=(1, 1), dtype=float32)
>>> print(tf.Session().run(m))
2018-01-06 16:51:25.418750: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX FMA
[[ 4.]]

```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by chg0901** [comment]
I am sorry for I didn't add that template.

**Comment by chg0901** [comment]
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by chg0901** [comment]
I am sorry for that.

And I have got the answer from
[ **Stackoverflow**](https://stackoverflow.com/questions/48125424/nightly-installed-tf-is-the-new-1-5-tf )
