### ISSUE TITLE
How to see the implementation of softmax_cross_entropy

### ISSUE THREAD

**Issue by mokii** [tensorflow/tensorflow#15908]
In tf.nn_ops file ，it imports the file : tensorflow.python.ops import gen_nn_ops
but I can't find the file gen_nn_ops in the directory

**Comment by HelloSeeing** [comment]
`tensorflow/python/ops/nn_ops.py`

**Comment by toranome** [comment]
@mokii I was looking for this too. Eventually I found the answer [here](https://stackoverflow.com/questions/41147734/looking-for-source-code-of-from-gen-nn-ops-in-tensorflow).
