### ISSUE TITLE
Feature Request: MonitoredTrainingSession should accept checkpoint steps

### ISSUE THREAD

**Issue by wskinner** [tensorflow/tensorflow#15900]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: n/a
- **TensorFlow installed from (source or binary)**: n/a
- **TensorFlow version (use command below)**: n/a
- **Python version**: n/a
- **Bazel version (if compiling from source)**:n/a
- **GCC/Compiler version (if compiling from source)**:n/a
- **CUDA/cuDNN version**:n/a
- **GPU model and memory**:n/a
- **Exact command to reproduce**:n/a

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
As of 1.4, MonitoredTrainingSession conveniently offers constructor parameters for checkpoint_secs, summary_secs, and summary_steps. It does not offer a parameter for checkpoint_steps, so if I want to checkpoint by steps and not seconds, I have to register a custom CheckpointSaverHook. It would be nice if MonitoredTrainingSession encapsulated that, as it does for the similar summary_secs, summary_steps, and checkpoint_secs.

### Source code / logs
https://github.com/tensorflow/tensorflow/blob/cddf8d82dec9fff526f5c064add725b7f35f95fa/tensorflow/python/training/monitored_session.py#L272

**Comment by skye** [comment]
@ispirmustafa FYI

**Comment by twairball** [comment]
I agree! here's a PR:
https://github.com/tensorflow/tensorflow/pull/16154
