### ISSUE TITLE
Python Configuration Error

### ISSUE THREAD

**Issue by huoyushi** [tensorflow/tensorflow#15909]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**:  source 
- **TensorFlow version (use command below)**:the latest master branch
- **Python version**: 3.6.3 in anaconda ,python path is :C:/Users/huo_y/Anaconda3/python.exe
- **Bazel version (if compiling from source)**:0.9.0
- **GCC/Compiler version (if compiling from source)**:msvc 14
- **CUDA/cuDNN version**: no
- **GPU model and memory**: no
- **Exact command to reproduce**:
 bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
when I build tensorflow with bazel on windows by msys2 shell. I got this error
Python Configuration Error : --define PYTHON_BIN_PATH='C:/Users/huo_y/Anaconda3/python.exe' is not executable. Is it the python binary?

### Source code / logs
ERROR: C:/users/huo_y/tensorflow-master/util/python/BUILD:5:1: no such package '@local_config_python//': Traceback (most recent call last):
        File "C:/users/huo_y/tensorflow-master/third_party/py/python_configure.bzl", line 291
                _create_local_python_repository(repository_ctx)
        File "C:/users/huo_y/tensorflow-master/third_party/py/python_configure.bzl", line 251, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/huo_y/tensorflow-master/third_party/py/python_configure.bzl", line 204, in _check_python_bin
                _fail(("--define %s='%s' is not execut...)))
        File "C:/users/huo_y/tensorflow-master/third_party/py/python_configure.bzl", line 27, in _fail
                fail(("%sPython Configuration Error:%...)))
Python Configuration Error: --define PYTHON_BIN_PATH='C:/Users/huo_y/Anaconda3/python.exe' is not executable. Is it the python binary?
 and referenced by '//util/python:python_headers'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Loading failed
INFO: Elapsed time: 16.677s
FAILED: Build did NOT complete successfully (63 packages loaded)
    currently loading: tensorflow/core/kernels
    Fetching http://ufpr.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz; 32,768b 4s

It may cause by python_configure.bzl I think,But I don't know how to correct it.

here is on function about the error  in python_config.bzl 
```
def _check_python_bin(repository_ctx, python_bin):
  """Checks the python bin path."""
  cmd =  '[[ -x "%s" ]] && [[ ! -d "%s" ]]' % (python_bin, python_bin)
  result = repository_ctx.execute(["bash", "-c", cmd])
  if result.return_code == 1:
    _fail("--define %s='%s' is not executable. Is it the python binary?" % (
        _PYTHON_BIN_PATH, python_bin))
```
I find that when I run configure  the python path is windows format just like C:/Users/huo_y/Anaconda3/python.exe  but in msys2 the path may show /c/Users/huo_y/Anaconda3/python.exe .  I guess that when using bash -c ,it should need the path just like /c/Users/huo_y/Anaconda3/python.exe can get the correct return code, but it seems that the python_bin parameter is the windows path format .

can anyone help check it because I don't be farmiliar with bazel

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
