### ISSUE TITLE
Documentation does not explain the utility of -1 as value for the axis parameter of the tf.concat method

### ISSUE THREAD

**Issue by nbro** [tensorflow/tensorflow#15905]
### System information

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X, version 10.13.2
- **TensorFlow installed from (source or binary)**: Binary (pip)
- **TensorFlow version (use command below)**: v1.3.0-rc1-5211-gab0fcac 1.5.0-dev20171126
- **Python version**: Python 3.5.0
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**:  N/A
- **CUDA/cuDNN version**:  N/A
- **GPU model and memory**:  N/A
- **Exact command to reproduce**: Just run a Python script with the code I am sharing with you

### Describe the problem

It apparently concatenates along the last axis. See the following example:  

```
import tensorflow as tf

t1 = [[[1, 2], [2, 3]], [[4, 4], [5, 3]]]
t2 = [[[7, 4], [8, 4]], [[2, 10], [15, 11]]]

with tf.Session() as sess:
    result = sess.run(tf.concat([t1, t2], -1))
    print(result)
```

which produces

```
[[[ 1  2  7  4]
  [ 2  3  8  4]]

 [[ 4  4  2 10]
  [ 5  3 15 11]]]
``` 

The following documention does not seem to explain this use case:

- https://www.tensorflow.org/api_docs/python/tf/concat
- https://www.tensorflow.org/versions/r1.5/api_docs/python/tf/concat

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by nbro** [comment]
@tensorflowbutler Ok, updated the text of the issue. Anyway, you should really revise the documentation before putting a new version out of TF. And you should constantly try to improve the documentation, which, IMHO, is often unclear.

**Comment by yongtang** [comment]
Added PR #15917 to address the documentation.

**Comment by nbro** [comment]
@yongtang IMHO, you can give a clearer explanation than the one you added in the commit of the PR. Maybe just copy my explanation above with the code?

**Comment by yongtang** [comment]
@nbro The PR has been updated.
