### ISSUE TITLE
Tensorflow Optimize for Inference KeyError.

### ISSUE THREAD

**Issue by MauryaRitesh** [tensorflow/tensorflow#15924]
I got the following error when optimizing the graph for inference:
Traceback (most recent call last):
  File "C:\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\lib\site-packages\tensorflow\python\tools\optimize_for_
inference.py", line 146, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Python35\lib\site-packages\tensorflow\python\platform\app.py", l
ine 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:\Python35\lib\site-packages\tensorflow\python\tools\optimize_for_
inference.py", line 90, in main
    FLAGS.output_names.split(","), FLAGS.placeholder_type_enum)
  File "C:\Python35\lib\site-packages\tensorflow\python\tools\optimize_for_
inference_lib.py", line 109, in optimize_for_inference
    placeholder_type_enum)
  File "C:\Python35\lib\site-packages\tensorflow\python\tools\strip_unused_
lib.py", line 83, in strip_unused
    raise KeyError("The following input nodes were not found: %s\n" % not_f
ound)
KeyError: "The following input nodes were not found: {'input'}\n"

Please help me soon!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by MauryaRitesh** [comment]
Ok I got the error and now it is working.
It was due to wrong argument given while optimizing the model!

**Comment by murtaza1122** [comment]
Hi

Which argument was wrong. I am having same error.

**Comment by arun-kumark** [comment]
Hi Maurya Ritesh,
I am new to quantization scripts..

I need you help, I am facing the same issue while running the optimize_for_inference.py script.
My arguments are as below: 

`python optimize_for_inference.py   --input=res101_faster_rcnn_iter_5600.pb   --output=optimized_graph.pb   --input_names="input"   --output_names="final_result"`

My pb file is based on Resnet-101. I am sharing my res101_faster_rcnn_iter_5600.ckpt.custom file below to see it's contents:

`node {
  name: "Placeholder"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: -1
        }
        dim {
          size: -1
        }
        dim {
          size: 3
        }
      }
    }
  }
}
node {
  name: "Placeholder_1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 3
        }
      }
    }
  }
}
node {
  name: "Placeholder_2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: -1
        }
        dim {
          size: 5
        }
      }
    }
  }
}
node {
  name: "resnet_v1_101/Pad/paddings"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 4
          }
          dim {
            size: 2
          }
        }
        tensor_content: "\000\000\000\000\000\000\000\000\003\000\000\000\003\000\000\000\003\000\000\000\003\000\000\000\000\000\000\000\000\000\000\000"
      }
    }
  }
}
node {
  name: "resnet_v1_101/Pad"
  op: "Pad"
  input: "Placeholder"
  input: "resnet_v1_101/Pad/paddings"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tpaddings"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "resnet_v1_101/conv1/weights/Initializer/truncated_normal/shape"
  op: "Const"
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@resnet_v1_101/conv1/weights"
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 4
          }
        }
        tensor_content: "\007\000\000\000\007\000\000\000\003\000\000\000@\000\000\000"
      }
    }
  }
}
node {
  name: "resnet_v1_101/conv1/weights/Initializer/truncated_normal/mean"
  op: "Const"
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@resnet_v1_101/conv1/weights"
      }
    }
  }



I am getting tyhe below error :+1: 

`_result"
/home/arun/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/home/arun/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "optimize_for_inference.py", line 146, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/arun/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "optimize_for_inference.py", line 90, in main
    FLAGS.output_names.split(","), FLAGS.placeholder_type_enum)
  File "/home/arun/anaconda3/lib/python3.6/site-packages/tensorflow/python/tools/optimize_for_inference_lib.py", line 109, in optimize_for_inference
    placeholder_type_enum)
  File "/home/arun/anaconda3/lib/python3.6/site-packages/tensorflow/python/tools/strip_unused_lib.py", line 83, in strip_unused
    raise KeyError("The following input nodes were not found: %s\n" % not_found)
KeyError: "The following input nodes were not found: {'input'}\n"
`
Please help me identifying what arguments you passed to run the script.

Thank you.

Kind Regards
Arun

**Comment by arun-kumark** [comment]
python touch.py -m res101_faster_rcnn_iter_5600.ckpt.meta -o res101_faster_rcnn_iter_5600.pb -b

and my touch.py has following contents, which I took from some repository: 
```
#! /usr/bin/python3
#generate a pb file !
from __future__ import print_function
import tensorflow as tf
import argparse
import os

if __name__ == '__main__':


    parser = argparse.ArgumentParser()
    parser.add_argument('-m','--model',required=True, type=str, metavar='' ,help="model meta graph AKA .ckpt.meta file to start with")
    parser.add_argument('-o', '--output_file', type=str, required=True, metavar='',help="Where to save the output file ")
    parser.add_argument('-b','--bin',dest='binary_file',action='store_true', help="saves file as binary instead of default text file")
    parser.add_argument('-v','--verbose',dest='verbosity',action='store_true',help="trigger the verbose output (show tensorflow debug info)")
    args = parser.parse_args()
    #get output dir from output file name
    output_dir = os.path.dirname(args.output_file)
    if output_dir == "":
        output_dir="."
    output_file_name = os.path.basename(args.output_file)
    #setting verbosity    
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
    if args.verbosity:
        os.environ['TF_CPP_MIN_LOG_LEVEL'] = '0'
    print ("Welcome to tensorflow graph saver")
    print ("loading ",os.path.basename(args.model))
    #opening a new session
    with tf.Session() as sess:
        new_saver = tf.train.import_meta_graph(args.model)
        new_saver.restore(sess,args.model.replace(".meta","") )
        print ("model",os.path.basename(args.model),"loaded correctly... converting it to graph")
        tf.train.write_graph(sess.graph, output_dir ,output_file_name, as_text=not args.binary_file)
        print("conversion done, output file saved as",args.output_file)
```

**Comment by Sagarsharma4244** [comment]
Note: If you are getting an error KeyError: “The following input nodes were not found: {‘input’}\n” then change "input" to "Mul" 
If you have any doubt refer to this tutorial: [TensorFlow on Mobile: Tutorial](https://towardsdatascience.com/tensorflow-on-mobile-tutorial-1-744703297267)
