### ISSUE TITLE
iOS: Op type not registered 'DecodeWav'

### ISSUE THREAD

**Issue by anton6** [tensorflow/tensorflow#15921]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: I am trying to run graph model from Simple Audio Recognition example on iOS.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.13
- **TensorFlow installed from (source or binary)**: Branch r1.4
- **TensorFlow version (use command below)**: 1.4
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: Build label: 0.9.0-homebrew
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem

I am trying to run graph model from Simple Audio Recognition example on iOS. When I am calling `session->Create(tensorflow_graph)` with the graph I get the error: "Could not create TensorFlow Graph: Not found: Op type not registered 'DecodeWav'...".

My initial thought is that because I am using TensorFlow-experimental (1.1.1) from pods, it's possible that this Op type is not registered. So I tried building it myself, which builds without errors with command: `tensorflow/contrib/makefile/build_all_ios.sh`. I then remove TensorFlow-experimental (1.1.1) from the project and link my own build of tensorflow, but I get the same error. 

I also found the following PR - [[iOS] Add optional Selective Registration of Ops #14421](https://github.com/tensorflow/tensorflow/pull/14421)

I tried building from master with the above PR merged like so:
 
For iPhone 5:
`tensorflow/contrib/makefile/build_all_ios.sh -a armv7 -g /Users/anton/Development/tensorflow/tensorflow/examples/ios/simple/data/tensorflow_inception_graph_speech.pb`

For iPhone SE:
`tensorflow/contrib/makefile/build_all_ios.sh -a arm64 -g /Users/anton/Development/tensorflow/tensorflow/examples/ios/simple/data/tensorflow_inception_graph_speech.pb`

If I then go and check the file `/tensorflow/tensorflow/core/framework/ops_to_register.h` (auto-generated after above command) I can see that DecodeWav is listed among kernels and operations:

```
// This file was autogenerated by print_selective_registration_header.py
#ifndef OPS_TO_REGISTER
#define OPS_TO_REGISTER

    namespace {
      constexpr const char* skip(const char* x) {
        return (*x) ? (*x == ' ' ? skip(x + 1) : x) : x;
      }

      constexpr bool isequal(const char* x, const char* y) {
        return (*skip(x) && *skip(y))
                   ? (*skip(x) == *skip(y) && isequal(skip(x) + 1, skip(y) + 1))
                   : (!*skip(x) && !*skip(y));
      }

      template<int N>
      struct find_in {
        static constexpr bool f(const char* x, const char* const y[N]) {
          return isequal(x, y[0]) || find_in<N - 1>::f(x, y + 1);
        }
      };

      template<>
      struct find_in<0> {
        static constexpr bool f(const char* x, const char* const y[]) {
          return false;
        }
      };
    }  // end namespace
    constexpr const char* kNecessaryOpKernelClasses[] = {
"BinaryOp< CPUDevice, functor::add<float>>",
"AudioSpectrogramOp",
"ConstantOp",
"Conv2DOp<CPUDevice, float>",
"DecodeWavOp",
"IdentityOp",
"MatMulOp<CPUDevice, float, false >",
"MaxPoolingOp<CPUDevice, float>",
"MfccOp",
"NoOp",
"PlaceholderOp",
"ReluOp<CPUDevice, float>",
"ReshapeOp",
"SoftmaxOp<CPUDevice, float>",
"RecvOp",
"SendOp",
};
#define SHOULD_REGISTER_OP_KERNEL(clz) (find_in<sizeof(kNecessaryOpKernelClasses) / sizeof(*kNecessaryOpKernelClasses)>::f(clz, kNecessaryOpKernelClasses))

constexpr inline bool ShouldRegisterOp(const char op[]) {
  return false
     || isequal(op, "Add")
     || isequal(op, "AudioSpectrogram")
     || isequal(op, "Const")
     || isequal(op, "Conv2D")
     || isequal(op, "DecodeWav")
     || isequal(op, "Identity")
     || isequal(op, "MatMul")
     || isequal(op, "MaxPool")
     || isequal(op, "Mfcc")
     || isequal(op, "NoOp")
     || isequal(op, "Placeholder")
     || isequal(op, "Relu")
     || isequal(op, "Reshape")
     || isequal(op, "Softmax")
     || isequal(op, "_Recv")
     || isequal(op, "_Send")
  ;
}
#define SHOULD_REGISTER_OP(op) ShouldRegisterOp(op)

#define SHOULD_REGISTER_OP_GRADIENT false
#endif

```

But when I try to run the graph model I still get same error message. I have removed the pod version, and I am 100% sure I am running my own build version of tensorflow on iOS.

I can't tell if this is a bug or I am doing something wrong during the build process.

Has anyone tried running any graph that uses DecodeWav on iOS?

Thanks.

### Source code / logs

Error: Could not create TensorFlow Graph: Not found: Op type not registered 'DecodeWav' in binary running on Antons-iPhone. Make sure the Op and Kernel are registered in the binary running in this process.

**Comment by shivaniag** [comment]
@petewarden can you take a look?

**Comment by jeffxtang** [comment]
@anton6 any luck on this? I'm having the same problem, and I tried adding both `-DSELECTIVE_REGISTRATION` and `-DSUPPORT_SELECTIVE_REGISTRATION` in the Makefile, according to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/print_selective_registration_header.py, but to no avail..

**Comment by anton6** [comment]
@jeffxtang hi! No luck yet. I'm still trying things out, but same result. I'm hoping that someone at Tensorflow team can have a look.

**Comment by anton6** [comment]
If I go to `/tensorflow/tensorflow/contrib/makefile/gen/obj/ios_ARM64/tensorflow/core/kernels/` after running the build it's listed among ops: 

<img width="358" alt="screen shot 2018-01-23 at 14 13 10" src="https://user-images.githubusercontent.com/16119505/35280279-99d6dd30-0047-11e8-979e-a5da84b2d583.png">

So it looks like decode_wav gets built. Not sure why it's not working.

**Comment by jeffxtang** [comment]
Some progress: having realized the unregistered DecodeWav error is similar to the old familiar DecodeJpeg issue (https://github.com/tensorflow/tensorflow/issues/2883), I ran strip_unused on the pb as follows:
```
bazel-bin/tensorflow/python/tools/strip_unused \
  --input_graph=/tf_files/speech_commands_graph.pb \
  --output_graph=/tf_files/stripped_speech_commands_graph.pb \
  --input_node_names=wav_data,decoded_sample_data \
  --output_node_names=labels_softmax \
  --input_binary=true
```
It does get rid of the DecodeWav op in the resulting graph. But running the new stripped graph on iOS now gives me an `Op type not registered 'AudioSpectrogram'` error. 
Also there's no object file audio*.o generated after build_all_ios.sh is done, although `AudioSpectrogramOp` is specified in `tensorflow/core/framework/ops_to_register.h`:
```
Jeffs-MacBook-Pro:tensorflow-1.4.0 zero2one$ find  . -name decode*.o
./tensorflow/contrib/makefile/gen/obj/ios_ARM64/tensorflow/core/kernels/decode_bmp_op.o
./tensorflow/contrib/makefile/gen/obj/ios_ARM64/tensorflow/core/kernels/decode_wav_op.o
./tensorflow/contrib/makefile/gen/obj/ios_ARMV7/tensorflow/core/kernels/decode_bmp_op.o
./tensorflow/contrib/makefile/gen/obj/ios_ARMV7/tensorflow/core/kernels/decode_wav_op.o
./tensorflow/contrib/makefile/gen/obj/ios_ARMV7S/tensorflow/core/kernels/decode_bmp_op.o
./tensorflow/contrib/makefile/gen/obj/ios_ARMV7S/tensorflow/core/kernels/decode_wav_op.o
./tensorflow/contrib/makefile/gen/obj/ios_I386/tensorflow/core/kernels/decode_bmp_op.o
./tensorflow/contrib/makefile/gen/obj/ios_I386/tensorflow/core/kernels/decode_wav_op.o
./tensorflow/contrib/makefile/gen/obj/ios_X86_64/tensorflow/core/kernels/decode_bmp_op.o
./tensorflow/contrib/makefile/gen/obj/ios_X86_64/tensorflow/core/kernels/decode_wav_op.o
Jeffs-MacBook-Pro:tensorflow-1.4.0 zero2one$ find  . -name audio*_op.o
Jeffs-MacBook-Pro:tensorflow-1.4.0 zero2one$ 
```

**Comment by petewarden** [comment]
Sorry you're hitting problems! The issue here is that the *op* isn't being registered, not the *kernel*. The op is like the function signature of a TensorFlow operation, and in this case is defined in the following file:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/audio_ops.cc

I think to fix the error, you'll need to add this file to the manual list of objects that are compiled by the makefile:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/tf_op_files.txt#L285

Let me know if that helps with the issue, and if it does I'd love a PR!

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by jeffxtang** [comment]
Thanks @petewarden! That fixed the error. I need to use the original speech_commands_graph.pb. The stripped version fails to load with this error `Could not create TensorFlow Graph: Invalid argument: Node 'Mfcc': Connecting to invalid output 1 of source node decoded_sample_data which has 1 outputs`. 

Just like Pete said, op is different from kernel. The error with DecodeJpeg is `No OpKernel was registered to support Op 'DecodeJpeg'` but the error with DecodeWav is `Op type not registered 'DecodeWav'`, and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/audio_ops.cc has DecodeWav, AudioSpectrogram, etc registered.

**Comment by jeffxtang** [comment]
Hi @petewarden I just created a PR https://github.com/tensorflow/tensorflow/pull/16537 Thanks! Jeff

**Comment by petewarden** [comment]
Closing as fixed, thanks Jeff!
