### ISSUE TITLE
Android Camera Demo : Failed to build on Mac OS due to missing file ../darwin-x86/bin/arm-linux-androideabi-gcc

### ISSUE THREAD

**Issue by hassanabidpk** [tensorflow/tensorflow#1593]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
OS X EI Capitan version 10.11

If installed from sources, provide the commit hash:
[b3d862b](https://github.com/tensorflow/tensorflow/commit/b3d862b376656c0f58b729e1848ea6e0c5bebf2a)
### Steps to reproduce
1. Follow guidelines here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/README.md (Download Android NDK for MAC)
2. build android demo using `$bazel build //tensorflow/examples/android:tensorflow_demo --verbose_failures`
3. Error : `process-wrapper: execvp("external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86/bin/arm-linux-androideabi-gcc", ...): No such file or directory
Target //tensorflow/examples/android:tensorflow_demo failed to build`

### What have you tried?
1. Tried another way to build using `$bazel build //tensorflow/examples/android:tensorflow_demo --verbose_failures --config=android_arm`
2. Also tried Android NDK version `r10e`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
`ERROR: /Users/hassanabid/Documents/hassan/open_source/tensorflow/tensorflow_source/tensorflow/examples/android/BUILD:43:1: Linking of rule '//tensorflow/examples/android:libpthread.so' failed: arm-linux-androideabi-gcc failed: error executing command 
  (cd /private/var/tmp/_bazel_hassanabid/96ab15ac510a01a39eca351cb09446d8/tensorflow_source && \
  exec env - \
  external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86/bin/arm-linux-androideabi-gcc -o bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-py3-fastbuild/bin/tensorflow/examples/android/libpthread.so -Wl,-whole-archive -Wl,-no-whole-archive external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a -shared -static-libgcc -no-canonical-prefixes '-march=armv7-a' -Wl,--fix-cortex-a8 -Wl,-S '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: arm-linux-androideabi-gcc failed: error executing command 
  (cd /private/var/tmp/_bazel_hassanabid/96ab15ac510a01a39eca351cb09446d8/tensorflow_source && \
  exec env - \
  external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86/bin/arm-linux-androideabi-gcc -o bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-py3-fastbuild/bin/tensorflow/examples/android/libpthread.so -Wl,-whole-archive -Wl,-no-whole-archive external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a -shared -static-libgcc -no-canonical-prefixes '-march=armv7-a' -Wl,--fix-cortex-a8 -Wl,-S '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
process-wrapper: execvp("external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86/bin/arm-linux-androideabi-gcc", ...): No such file or directory
Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 0.438s, Critical Path: 0.04s`

**Comment by andrewharp** [comment]
@hassanabidpk What version of Bazel are you using?

**Comment by hassanabidpk** [comment]
After typing `bazel version` I see this : `0.2.0-homebrew`

**Comment by andrewharp** [comment]
Where did you get Bazel homebrew from? I'd suggest sticking with a vanilla default Bazel install if you're experiencing problems.

This is the complete output I see when I type bazel version:
`$ bazel version
Build label: 0.2.0
Build target: bazel-out/local_darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Feb 23 13:11:56 2016 (1456233116)
Build timestamp: 1456233116
Build timestamp as int: 1456233116
`

Also, what did you set your ndk path to in the WORKSPACE file?
When you run `ls -la $NDK_PATH/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc`, what do you see?

**Comment by hassanabidpk** [comment]
1. `Build label: 0.2.0-homebrew
Build target: bazel-out/local_darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Feb 23 14:12:29 2016 (1456236749)
Build timestamp: 1456236749
Build timestamp as int: 1456236749`

2. `-rwxr-xr-x@ 1 hassanabid  staff  747340 Mar 15 13:18 toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc`

Sorry for late reply - Got busy in GDE activities

**Comment by kmader** [comment]
I fixed this by simply making a link (or just copy) the folder ```($NDK_PATH)/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64``` to  ```($NDK_PATH)/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86``` and this fixed the problem

**Comment by andrewharp** [comment]
@hassanabidpk have you tried @kmader's solution?

@ahumesky Do you have any guess why it's trying to use the non-existent darwin-86 toolchain here? Any system running El Capitan should be 64bit from what I understand. I've not been able to reproduce on my macbook running OSX 10.11.4 -- it uses the darwin-x86_64 toolchain automatically.

**Comment by hassanabidpk** [comment]
Hi @andrewharp  I have tried the same solution posted by @kmader and it worked. However I am also wondering why it is not using `darwin-x86_64` toolchain automatically. Thanks

**Comment by ahumesky** [comment]
What version of the Android NDK are you using? We're working to update bazel to work with Android NDK r11, so for now you'll want to use r10e:
http://dl.google.com/android/repository/android-ndk-r10e-darwin-x86_64.zip

What is the content of `$NDK_PATH/RELEASE.TXT`?
Bazel uses that file to figure out if you have a 32-bit or 64-bit NDK.

**Comment by hassanabidpk** [comment]
@ahumesky Build worked fine with `ndk-r10e`
`RELEASE.TXT` contains `r10e (64-bit)`

**Comment by andrewharp** [comment]
Just noticed that you built with --config=android_arm. This should not be necessary (or do anything, but it's worth checking to see if it's what's causing the issue). It was included in some previous directions by mistake.

**Comment by andrewharp** [comment]
@ahumesky Did we ever figure out the root cause to this? If not, is this still relevant now that Bazel supports NDK 11?

**Comment by ahumesky** [comment]
Not sure of the root cause. If ndk r11 was being used before bazel supported it, it could have been detecting the wrong bit-ness of the ndk.

**Comment by andrewharp** [comment]
Seems likely, we can reinvestigate if it ever happens again.

**Comment by chuan9** [comment]
I build it tensorflow on ubunu 64  and referred this link:https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android#building-in-android-studio-using-the-tensorflow-aar-from-jcenter. This problem can also produced, can't find x86 clang. the log is as bellows:
src/main/tools/process-wrapper-legacy.cc:56: "execvp(external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86/bin/clang, ...)": No such file or directory
After I copy the linux-x86_64 to linux-x86, Another problem exist:
clang: error: unable to execute command: Executable "as" doesn't exist!
Can you help fix this?
