### ISSUE TITLE
Discontinuity at halfway point in graph output

### ISSUE THREAD

**Issue by ppfaff** [tensorflow/tensorflow#15930]
- **I have written custom code (as opposed to using a stock example script provided in TensorFlow)**:
to reproduce the error:
1) convert HnH_gate.txt to HnH_gate.py
2) Edit mypath in out() method at end of file for your system.  Save 
3) in python: run HnH_gate.py
4) run out() to create csv files for the good and bad output
            i) out("101", new_probka_good)
            ii) out("102", new_probka_bad)
5) Plot data from hh_101.csv and hh_102.csv and verify the discontinuity at half way point in hh_102.csv
6) Two additional tests can be run:
          i) Edit parameter timepoints in main() to show error remaps to half way point.
          ii) My temporary correction is to create 2x points and throw half away.  this is done in p_update() setting cut_in_half = True

7) This same error was found running the code in Tensorflow 1.4 on MacOS Sierra.  My system info is:

== cat /etc/issue ===============================================
Linux PAULP-XPS15 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.3 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux PAULP-XPS15 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.13.3)
numpydoc (0.7.0)
protobuf (3.4.1)
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.5)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.3.0
tf.GIT_VERSION = b'unknown'
tf.COMPILER_VERSION = b'unknown'
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

### Describe the problem
I am running a RNN for a Hodgkin and Huxley type gating of an ion channel protein
called HnH_gate.py.
The program takes a placeholder vmem and produces a timeseries output of the size
timepoints.
At the halfway point in the timeseries there is a discontinuity in the results
This only appears with some arrays fed to my tf.placeholder.  Others produce normal
results.  I can correct for the problem by doubling the number of timepoints requested
and throwing half away.

The array:
vmem_list_good = [[-100.0, -90.0, -80.0, -70.0, -60.0, -50.0, -41.0, -30.0, -20.0, -10.0, 0.0, 10.0, 20.0, 30.0, 40.0, 50.0],
                [-100.0, -90.0, -80.0, -70.0, -60.0, -50.0, -41.0, -30.0, -20.0, -10.0, 0.0, 10.0, 20.0, 30.0, 40.0, 50.0]]
appears to work perfectly
The array:
vmem_list_bad = [[80.0, 60.0, 40.0, 20.0, 00.0, -20.0, -41.0, -60.0, -80.0, -55.0, 0.0, 10.0, 20.0, 30.0, 40.0, 50.0],
            [70.0, 50.0, 30.0, 10.0, -10.0, -30.0, -50.0, -70.0, -90.0, -30.0, -10.0, 0.0, 10.0, 20.0, 30.0, 40.0]]

shows the error.

To see my temporary correction, edit the parameter in the HH.p_update() method
to: cut_in_half = True

I have written a short output routine to export the simulation to a csv file,
just edit the path and provide a string to make a unique filename:

out("101", new_probka_good)
out("102", new_probka_bad)

### Source code / logs
program file is: HnH_gate.py (provided as HnH_gate.txt)
HnH_gate.txt  (convert to HnH_gate.py)
[HnH_gate.txt](https://github.com/tensorflow/tensorflow/files/1610057/HnH_gate.txt)

System and Error Description: HnH_gate_bug_report.txt
[HnH_gate_bug_report.txt](https://github.com/tensorflow/tensorflow/files/1610056/HnH_gate_bug_report.txt)

Output example demonstrating problem: Artifact plotting new_probka_bad.py
[Artifact plotting new_probka_bad.pdf](https://github.com/tensorflow/tensorflow/files/1610058/Artifact.plotting.new_probka_bad.pdf)

Thanks for your help.
Paul

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ppfaff** [comment]
I have edited the file to show the info requested upfront.  The problem has also been seen reproduced on Tensorflow 1.4 on MacOS Sierra.

**Comment by ppfaff** [comment]
resolved as a tiling artifact.
