### ISSUE TITLE
An easy problem about tensorflow tf.reduce_mean op

### ISSUE THREAD

**Issue by Zxiaoma** [tensorflow/tensorflow#15938]
I know... there might not be a suitable palce to ask this question, but I really hope someone cloud help me.

i want to use the "tf.reduce_mean" to obtain the mean of an array (ignore the zeros element)
eg:
    data = [[1,2,3],[4,5,6],[0,0,0]]   
    i want to obtain mean= [2.5, 3.5, 4.5]  
    but  tf.reduce_mean op gets the mean=[1.6, 2.3, 3]

Thank you very much!

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
