### ISSUE TITLE
Install from sources: Error: can't copy 'tensorflow/python/pywrap_tensorflow.py': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by tamhd** [tensorflow/tensorflow#1594]
I recently tried to install Tensorflow on Ubuntu 14.10. I had cuda 7.0 and cudnn 3.0, so I had to install from sources following the instructions. I got "error: can't copy 'tensorflow/python/pywrap_tensorflow.py': doesn't exist or not a regular file" when building the pip package (with GPU support):

`$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
`
So far, I have set the configuration for cuda and cudnn correctly. What should I do? Thanks.

**Comment by mrry** [comment]
Just to check: have you installed `swig` on your machine? It has to be installed manually (via `apt-get`) and is reponsible for producing that file. (I would have expected a different error message though.)

**Comment by tamhd** [comment]
@mrry: It's what I forgot. problem fixed. Thanks.

**Comment by KendallWeihe** [comment]
I do have `swig` installed, but I'm still getting the same error. My process is outlined in [this](http://stackoverflow.com/questions/38773402/tensorflow-bazel-build-failing-not-generating-bazel-bin-directory/38773658#38773658) SO post (it was about a different question, but still explains everything).

**Comment by lemonzi** [comment]
Is `swig` still a requirement? It's not mentioned in the installation guide (https://www.tensorflow.org/install/install_sources). I got the same error with v1.0.0 and it was fixed installing swig (I have a different one now).

**Comment by asimonov** [comment]
I see the same error on latest 1.0 version. on MacOS ElCapitan

error: can't copy 'tensorflow/python/pywrap_tensorflow.py': doesn't exist or not a regular file

**Comment by asimonov** [comment]
here is full error message:

mymac:tensorflow myuser$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Fri 24 Feb 2017 22:41:56 GMT : === Using tmpdir: /var/folders/r5/njbm4bmx7x540l67m3zfp4lm0000gn/T/tmp.XXXXXXXXXX.hKT7gN4Z
~/dev/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles ~/dev/tensorflow
~/dev/tensorflow
/var/folders/r5/njbm4bmx7x540l67m3zfp4lm0000gn/T/tmp.XXXXXXXXXX.hKT7gN4Z ~/dev/tensorflow
Fri 24 Feb 2017 22:41:58 GMT : === Building wheel
error: can't copy 'tensorflow/python/pywrap_tensorflow.py': doesn't exist or not a regular file
mymac:tensorflow myuser$ 
mymac:tensorflow myuser$ sudo bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Password:
Fri 24 Feb 2017 22:42:16 GMT : === Using tmpdir: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.XXXXXXXXXX.KZWr2rvk
~/dev/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles ~/dev/tensorflow
~/dev/tensorflow
/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.XXXXXXXXXX.KZWr2rvk ~/dev/tensorflow
Fri 24 Feb 2017 22:42:18 GMT : === Building wheel
error: can't copy 'tensorflow/python/pywrap_tensorflow.py': doesn't exist or not a regular file

**Comment by IvyGongoogle** [comment]
@KendallWeihe @asimonov i got the same error. Do you have solved the problem?
@tamhd  @mrry do you have any else solution?

**Comment by asimonov** [comment]
I did, but had to turn off SIP and downgrade to bazel 0.4.3

_____________________________
Kind Regards,
Alexey Simonov

**Comment by IvyGongoogle** [comment]
@asimonov can you tell me how turn off SIP? I can not understand your mean. Thank you very much

**Comment by asimonov** [comment]
Google 'how to turn off SIP in El Capitain'

_____________________________
Kind Regards,
Alexey Simonov
