### ISSUE TITLE
TypeError: Input 'split_dim' of 'Split' Op has type float32 

### ISSUE THREAD

**Issue by Nassimmd** [tensorflow/tensorflow#15954]
Hi,

I use Tensorflow 1.5.0rc0  on windows (Python 3.5.2 )and I have this issue: 
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32. I have seen some answers for older versions of tensor flow but is there any fix for the new version?

**Comment by cy89** [comment]
Can you please tell us how to reproduce your problem? What did you run, and what does the entire error output look like?

Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by Nassimmd** [comment]
some information:
- **Windows 7**:
- **TensorFlow 1.4 installed with pip and then upgraded to 1.5.0-rc0 **:
- **TensorFlow version 1.5.0-rc0**:
- **Python version 3.5.2**: 

I am using the code for social LSTM (long short-term memory) which you can find here: https://github.com/vvanirudh/social-lstm-tf

when I want to train my model, no matter whether it is a normal or social LSTM I get an error. Here you can find the code for Training the model: 
### Source code / logs

import numpy as np
import tensorflow as tf
import argparse
import os
import time
import pickle
from model import Model
from utils import DataLoader

def main():
    parser = argparse.ArgumentParser()
    # RNN size parameter (dimension of the output/hidden state)
    parser.add_argument('--rnn_size', type=int, default=128,
                        help='size of RNN hidden state')
    # Number of layers parameter
    # TODO: (improve) Number of layers not used. Only a single layer implemented
    parser.add_argument('--num_layers', type=int, default=1,
                        help='number of layers in the RNN')
    # Type of recurrent unit parameter
    # Model currently not used. Only LSTM implemented
    parser.add_argument('--model', type=str, default='lstm',
                        help='rnn, gru, or lstm')
    # Size of each batch parameter
    parser.add_argument('--batch_size', type=int, default=50,
                        help='minibatch size')
    # Length of sequence to be considered parameter
    parser.add_argument('--seq_length', type=int, default=8,
                        help='RNN sequence length')
    # Number of epochs parameter
    parser.add_argument('--num_epochs', type=int, default=100,
                        help='number of epochs')
    # Frequency at which the model should be saved parameter
    parser.add_argument('--save_every', type=int, default=400,
                        help='save frequency')
    # Gradient value at which it should be clipped
    # TODO: (resolve) Clipping gradients for now. No idea whether we should
    parser.add_argument('--grad_clip', type=float, default=10.,
                        help='clip gradients at this value')
    # Learning rate parameter
    parser.add_argument('--learning_rate', type=float, default=0.003,
                        help='learning rate')
    # Decay rate for the learning rate parameter
    parser.add_argument('--decay_rate', type=float, default=0.95,
                        help='decay rate for rmsprop')
    # Dropout probability parameter
    # Dropout not implemented.
    parser.add_argument('--keep_prob', type=float, default=0.8,
                        help='dropout keep probability')
    # Dimension of the embeddings parameter
    parser.add_argument('--embedding_size', type=int, default=128,
                        help='Embedding dimension for the spatial coordinates')
    parser.add_argument('--leaveDataset', type=int, default=3,
                        help='The dataset index to be left out in training')
    # Lambda regularization parameter (L2)
    parser.add_argument('--lambda_param', type=float, default=0.05,
                        help='L2 regularization parameter')
    args = parser.parse_args()
    train(args)


def train(args):
    datasets = list(range(4))
    # Remove the leaveDataset from datasets
    datasets.remove(args.leaveDataset)

    # Create the data loader object. This object would preprocess the data in terms of
    # batches each of size args.batch_size, of length args.seq_length
    data_loader = DataLoader(args.batch_size, args.seq_length, datasets, forcePreProcess=True)

    # Save the arguments int the config file
    with open(os.path.join('save_lstm', 'config.pkl'), 'wb') as f:
        pickle.dump(args, f)

    # Create a Vanilla LSTM model with the arguments
    model = Model(args)

    # Initialize a TensorFlow session
    with tf.Session() as sess:
        # Initialize all the variables in the graph
        sess.run(tf.initialize_all_variables())
        # Add all the variables to the list of variables to be saved
        saver = tf.train.Saver(tf.all_variables())

        # For each epoch
        for e in range(args.num_epochs):
            # Assign the learning rate (decayed acc. to the epoch number)
            sess.run(tf.assign(model.lr, args.learning_rate * (args.decay_rate ** e)))
            # Reset the pointers in the data loader object
            data_loader.reset_batch_pointer()
            # Get the initial cell state of the LSTM
            state = sess.run(model.initial_state)

            # For each batch in this epoch
            for b in range(data_loader.num_batches):
                # Tic
                start = time.time()
                # Get the source and target data of the current batch
                # x has the source data, y has the target data
                x, y = data_loader.next_batch()

                # Feed the source, target data and the initial LSTM state to the model
                feed = {model.input_data: x, model.target_data: y, model.initial_state: state}
                # Fetch the loss of the model on this batch, the final LSTM state from the session
                train_loss, state, _ = sess.run([model.cost, model.final_state, model.train_op], feed)
                # Toc
                end = time.time()
                # Print epoch, batch, loss and time taken
                print(
                    "{}/{} (epoch {}), train_loss = {:.3f}, time/batch = {:.3f}"
                    .format(
                        e * data_loader.num_batches + b,
                        args.num_epochs * data_loader.num_batches,
                        e,
                        train_loss, end - start))

                # Save the model if the current epoch and batch number match the frequency
                if (e * data_loader.num_batches + b) % args.save_every == 0 and ((e * data_loader.num_batches + b) > 0):
                    checkpoint_path = os.path.join('save_lstm', 'model.ckpt')
                    saver.save(sess, checkpoint_path, global_step=e * data_loader.num_batches + b)
                    print("model saved to {}".format(checkpoint_path))

if __name__ == '__main__':
    main()


###and here is the error:

Traceback (most recent call last):
  File "C:\Users\ga67zod\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "C:\Users\ga67zod\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1013, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\ga67zod\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 857, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("Placeholder:0", shape=(?, 8, 2), dtype=float32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ga67zod\Desktop\social-lstm-tf\lstm\train.py", line 125, in <module>
    main()
  File "C:\Users\ga67zod\Desktop\social-lstm-tf\lstm\train.py", line 60, in main
    train(args)
  File "C:\Users\ga67zod\Desktop\social-lstm-tf\lstm\train.py", line 77, in train
    model = Model(args)
  File "C:\Users\ga67zod\Desktop\social-lstm-tf\lstm\model.py", line 80, in __init__
    inputs = tf.split(1, args.seq_length, self.input_data)
  File "C:\Users\ga67zod\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1330, in split
    axis=axis, num_split=num_or_size_splits, value=value, name=name)
  File "C:\Users\ga67zod\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 6922, in _split
    "Split", split_dim=axis, value=value, num_split=num_split, name=name)
  File "C:\Users\ga67zod\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 533, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.


Thank you in advance,
Nassim

**Comment by cy89** [comment]
Any chance that this update, in the 1.5.0 release notes, affected your code: 

tf.split now takes arguments in a reversed order and with different
keywords. In particular, we now match NumPy order as
tf.split(value, num_or_size_splits, axis).

**Comment by Nassimmd** [comment]
Thank you, that was it!
