### ISSUE TITLE
iOS Camera Example not able to fit to iphone 6 screen 

### ISSUE THREAD

**Issue by rlehman221** [tensorflow/tensorflow#15976]
### System information
- **OS Platform and Distribution macOS High Sierra **:
- **TensorFlow installed from source**:
- **TensorFlow version 1.4**:

### Describe the problem
When I run the tensorflow camera example on xcode it runs fine but only in dimensions that fit an iphone 4. I changed the build settings, have turned on autolayout, and even tried messing around with the constraints. It seems like no matter what I try the viewcontroller won't get any larger.

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
