### ISSUE TITLE
Estimator.predict always loads model checkpoint preventing partially loading checkpoints

### ISSUE THREAD

**Issue by andreas-eberle** [tensorflow/tensorflow#15974]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
pip
- **TensorFlow version (use command below)**:
1.4
- **Python version**: 
3.5

### Describe the problem
When using Tensorflow's Estimator to do predictions, the Estimator always loads the checkpoint in the model_dir. As this is done after the model_fn is called, there is no way to partially load a checkpoint for predictions. For training, I partially load the initial checkpoint in the model_fn which works fine.

I also tried not specifying the model_dir for the Estimator. As the [documentation states](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#__init__), this results in the Estimator using a temporary folder. However, as the temporary folder does not contain a checkpoint, I get the error `Could not find trained model in model_dir`.

It looks like there is no way to only partially load a checkpoint for prediction. If so, please provide a way to do this. For me, this is important, because I have a large model with several outputs. For different datasets, some of the outputs have different sizes. However, some of them are the same for all datasets. That's why I want to load them with the same code and only partially, because I don't need to load and run the whole network for this prediction.

**Comment by cy89** [comment]
@martinwicke @ispirmustafa is there a way for @andreas-eberle to do what they want, or is this a feature request?

**Comment by ispirmustafa** [comment]
Hi @andreas-eberle 
You can create your graph partially based on params. something like:
```
def model_fn(..., params):
  if params['model'] == 'all':
   create all graph
  elif params['model'] == 'small':
   create small graph

params = {'model': 'all'}
main_estimator = tf.estimator.Estimator(model_fn, params=params)
main_estimator.train(...)

params = {'model': 'small'}
small_estimator = tf.estimator.Estimator(model_fn, model_dir=main_estimator.model_dir, params=params)
small_estimator.predict(...)
```
Having said that, making your prediction graph different then the graph you trained looks error prone to me.
