### ISSUE TITLE
Is it possible to make IPython able to plot with matplotlib as default?

### ISSUE THREAD

**Issue by lekaha** [tensorflow/tensorflow#1597]
I am doing the assignment 1 of Deep learning course on Udacity. There is a problem to ask us to plot for checking the dataset.
I can not plot any figure with matplotlib initially (nothing happened). Then, looked for the solution on the internet. I found it should be with a line that will make IPython able to attach the figure:
`%matplotlib notebook` or `%matplotlib inline`

if we don't want to key the line above each time we can change the config of IPython. 
Is it possible to add the line as default in this repository? I guess for novice they would be stuck a while on this point.

**Comment by vincentvanhoucke** [comment]
My own setup doesn't require it, so I can't easily test it. Would you mind sending me a pull request with the change? I'll be happy to merge it.

**Comment by lekaha** [comment]
@vincentvanhoucke 
Please check it out
https://github.com/tensorflow/tensorflow/pull/1599

**Comment by yjmade** [comment]
@vincentvanhoucke 
also this one #1621 
Thank you
