### ISSUE TITLE
Documentation for placeholder does not explain when shape is (), [] or [None]

### ISSUE THREAD

**Issue by nbro** [tensorflow/tensorflow#15987]
### System information

Not necessary.

### Describe the problem

The documentation for `placeholder` does not explain the case when its shape is `()`, `[]` or `[None]`.

### Possible solution

Add the explanations in [this SO  answer](https://stackoverflow.com/a/46941087/3924118) to the documentation of `placeholder`, including the example !!

**Comment by shivaniag** [comment]
IMO this is well documented in Tensor rank, Shapes and Types. Closing this.

**Comment by nbro** [comment]
@shivaniag Can you please link me to a place where it is documented?
