### ISSUE TITLE
Feature Request: Dense to Sparse and Dense to Sparse Tensor Ops

### ISSUE THREAD

**Issue by selcouthlyBlue** [tensorflow/tensorflow#15985]
I think it would be helpful if there is a dense_to_sparse op in Tensorflow for ops like `ctc_loss` that requires sparse labels. I'm not really sure where else it can be used aside from that but in case only `ctc_loss` uses it, I think it would help if dense labels can be passed into `ctc_loss` and do the conversion within.

**Comment by shivaniag** [comment]
@mrry does this seems to you something we would want to add?

**Comment by mrry** [comment]
Perhaps, or perhaps it would make more sense for `tf.nn.ctc_loss()` to accept dense labels and do the conversion internally? I think @ebrevdo created that part of the code, so he'll know best.

**Comment by selcouthlyBlue** [comment]
One reason I would like this feature to exist is to be able to use Tensorflow’s Estimator.fit without having to covert the labels to a SparseTensor outside the fit function.

**Comment by ebrevdo** [comment]
+1 for having denaified versions of the CTC loss and decoders. You'll need
to pass an additional Sequence lengths for the labels.  PRs to
tf.contrib.layers welcome.

**Comment by selcouthlyBlue** [comment]
I’ll see if what I can do. I plan on basing this on the sparse_to_dense op.

**Comment by selcouthlyBlue** [comment]
How is the sequence_lengths required by ctc_loss right now different from that of the to-be-implenented-densified_ctc_loss?

**Comment by selcouthlyBlue** [comment]
I'm not sure if this is how it's done but I got so far: https://stackoverflow.com/questions/39838234/sparse-matrix-from-a-dense-one-tensorflow

```
# labels is a dense tensor
indices = tf.where(tf.not_equal(labels, 0))
values = tf.gather_nd(labels, indices)
shape = ???
sparse_labels = tf.SparseTensor(indices, values, dense_shape=shape)
```

I've tried the following:

1. If shape = labels.get_shape(), I get `ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, 33)`
2. If shape = (1, 33) or tf.shape(labels, out_type=tf.int64), I get `ValueError: Shape must be rank 1 but is rank 0 for 'CTCLoss' (op: 'CTCLoss') with input shapes: [?,?,80], [?,2], [?], [].`

**Comment by selcouthlyBlue** [comment]
Turns out, the conversion from dense to sparse is successful with this code:

```
#labels is a dense tensor
indices = tf.where(tf.not_equal(labels, 0))
values = tf.gather_nd(labels, indices)
shape = tf.shape(labels, out_type=tf.int64)
sparse_labels = tf.SparseTensor(indices, values, dense_shape=shape)
```

Now the only concern here is the ValueError thrown by ctc_loss:

`ValueError: Shape must be rank 1 but is rank 0 for 'CTCLoss' (op: 'CTCLoss') with input shapes: [?,?,80], [?,2], [?], [].`

**Comment by selcouthlyBlue** [comment]
I tried using this to function to create a sparse matrix from a dense one:

```
def convert_to_sparse(labels, dtype=np.int32):
    indices = []
    values = []

    for n, seq in enumerate(labels):
        indices.extend(zip([n] * len(seq), range(len(seq))))
        values.extend(seq)

    indices = np.asarray(indices, dtype=dtype)
    values = np.asarray(values, dtype=dtype)
    shape = np.asarray([len(labels), np.asarray(indices).max(0)[1] + 1], dtype=dtype)

    return indices, values, shape
```

When I placed the indices, values, and shape to create a `SparseTensor`:

```
print(tf.SparseTensor(
        indices=sparse_y_train[0],
        values=sparse_y_train[1],
        dense_shape=sparse_y_train
    ))
```

And compared it to a `SparseTensor` created from a `Tensor`:

```
indices = tf.where(tf.not_equal(labels, tf.constant(0, dtype=tf.int32)))
values = tf.gather_nd(labels, indices)
sparse_labels = tf.SparseTensor(indices, values, dense_shape=tf.shape(labels, out_type=tf.int64))
print(sparse_labels)
```

I got these respectively:

```
SparseTensor(indices=Tensor("SparseTensor/indices:0", shape=(33, 2), dtype=int64), values=Tensor("SparseTensor/values:0", shape=(33,), dtype=int32), dense_shape=Tensor("SparseTensor/dense_shape:0", shape=(2,), dtype=int64))

SparseTensor(indices=Tensor("Where:0", shape=(?, 2), dtype=int64), values=Tensor("GatherNd:0", shape=(?,), dtype=int32), dense_shape=Tensor("Shape:0", shape=(2,), dtype=int64))
```

I guess this is the case of ctc_loss not being able to handle dynamic shapes for indices, values, and dense_shape.

**Comment by Holded** [comment]
+1 for having densified versions of the ctc_loss and decoders.

**Comment by selcouthlyBlue** [comment]
I'm stuck right now D:

**Comment by selcouthlyBlue** [comment]
I already got it working! Turns out, the `sequence_length` parameter I was passing is a scalar but it should be a 1-d vector according to the [documentation](https://www.tensorflow.org/versions/r0.12/api_docs/python/nn/connectionist_temporal_classification__ctc_#ctc_loss):

> sequence_length: 1-D int32 vector, size [batch_size]. The sequence lengths. 

The code for converting a dense tensor into a sparse one is as follows:

```
def dense_to_sparse(dense_tensor, out_type):
    indices = tf.where(tf.not_equal(dense_tensor, tf.constant(0, dense_tensor.dtype)
    values = tf.gather_nd(dense_tensor, indices)
    shape = tf.shape(dense_tensor, out_type=out_type)
    return tf.SparseTensor(indices, values, shape)
```

Now the questions is whether to have this op exist or just put it inside `tf.nn.ctc_loss`. Thoughts, anyone?

**Comment by ebrevdo** [comment]
Your code makes the assumption that 0 signifies the EOS token, right?  I
suppose that's arbitrary, and would make that a required argument of the
function.  I'd put it in tf.contrib.layers as ctc_loss_dense_labels or
something.

**Comment by selcouthlyBlue** [comment]
What do you mean by EOS?

**Comment by ebrevdo** [comment]
End of sentence

**Comment by selcouthlyBlue** [comment]
Apparently, that number is not arbitrary according to this comment in this SO [post](https://stackoverflow.com/questions/39838234/sparse-matrix-from-a-dense-one-tensorflow/41676814?noredirect=1#comment83489373_41676814):

> A sparse tensor is defined through its nonzero values (in TensorFlow, but also in about any algebra package that defines sparse structures). A matrix or tensor is said to be sparse if most of its elements are zero, and so this representation is much more economical (although operating with it is generally more complex).

**Comment by ebrevdo** [comment]
Yes but when you start with a dense tensor, the zero value can mean
anything when it comes to CTC labels.  0 does not always mean end of
sentence or padding. For example, -1 is also a perfectly reasonable padding
label value.

**Comment by selcouthlyBlue** [comment]
Pull request made. https://github.com/tensorflow/tensorflow/issues/15985

**Comment by selcouthlyBlue** [comment]
Is EOS the blank label index for ctc?

**Comment by ebrevdo** [comment]
Nope; EOS is not the blank label index.  The blank label index is an index
emitted by logits to signify "skip emitting a character this time step".
It should never appear in the label tensor.  The EOS signifies the end of a
sentence.  Now that I think about it, EOS is usually part of the target
label; and padding should be some other value (not EOS, and obviously not
the blank label index).

**Comment by selcouthlyBlue** [comment]
Let's say I have a target label "apple". If I were to encode it, should it be like this:

`[0, 15, 15, 12, 5, 27, 26, 26, 26]` # 27 is the eos_token, 26 is the padding

Is it correct to say that there are 27 classes for ctc (the letters + the blank label) and the eos token should not be in those classes?

**Comment by ebrevdo** [comment]
"the eos token should not be in those classes"?  no.  the padding token
should not be in those classes.  the eos token should be in them.

valid label:

[0, 15, 15, 12, 5, 27, -1, -1, -1]  # 27 is EOS token, -1 is padding

29 classes for ctc logits outputs: 0, ..., 27 (eos), 28 (blank)

**Comment by selcouthlyBlue** [comment]
Oh, I see. Thank you for clearing it to me :D

**Comment by pozhijisi** [comment]
I am using the following code as a workaround. Haven't been tested though.

```
def dense_to_sparse(dense_tensor, sequence_length):
    indices = tf.where(tf.sequence_mask(sequence_length))
    values = tf.gather_nd(dense_tensor, indices)
    shape = tf.shape(dense_tensor, out_type=tf.int64)
    return tf.SparseTensor(indices, values, shape)
```

**Comment by selcouthlyBlue** [comment]
What does sequence_length mean here?

**Comment by pozhijisi** [comment]
sequence_length is the 1-D tensor containing the lengths of the labels in the batch.

sequence_length may be of shape [batch_size], and labels (dense_tensor) may be of shape [batch_size, max_length_of_the_labels].

The code has been tested now.

**Comment by selcouthlyBlue** [comment]
I have already implemented `dense_to_sparse` that passes an `eos_token`. What do you intend to gain from passing `sequence_length` instead of an `eos_token`?

**Comment by selcouthlyBlue** [comment]
@ebrevdo -1 is not really allowed as padding. ctc_loss throws this error: `All labels must be nonnegative integers`

**Comment by selcouthlyBlue** [comment]
Also, adding having an eos_token assumes that an eos_token should be appended to each label.

**Comment by shkarupa-alex** [comment]
Proposed implementations raises error with tensor of rank 0

**Comment by selcouthlyBlue** [comment]
Which proposed implementation?

**Comment by selcouthlyBlue** [comment]
I guess error handling can be applied such that scalars can't be accepted into `dense_to_sparse`.

**Comment by rightaditya** [comment]
@selcouthlyBlue I am using an implementation very much like @pozhijisi. I need this functionality for something unrelated to CTCs (namely, tf.edit_distance). I think it makes sense for the function to use either `eos_token` or `sequence_lengths` (or even a mask directly, as that is what I actually have).
