### ISSUE TITLE
Allow tensorflow/tensorflow/workspace.bzl to customize dependencies

### ISSUE THREAD

**Issue by tadeegan** [tensorflow/tensorflow#15997]
When including tensorflow as a dependency of a Bazel project, it requires you to take all the declared dependencies in  `tensorflow/tensorflow/workspace.bzl` or none of them. Some projects, like the closure_rules allow you to customize the dependencies:
https://github.com/bazelbuild/rules_closure/blob/master/closure/repositories.bzl#L21

This allows you to use whatever versions you want for specific dependencies that may be different from what tensorflow's workspace.bzl declares.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tadeegan** [comment]
Have I written custom code N/A
OS Platform and Distribution: Linux
TensorFlow installed from: Source
TensorFlow version: 1.4
Bazel version: Custom
CUDA/cuDNN version: 7
GPU model and memory: N/A

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by reedwm** [comment]
/CC @gunan what do you think of this idea?

**Comment by gunan** [comment]
Bazel should not download the unused stuff in your workspace anyway, so I do not see a big upside compared to the much longer workspace file.
You said you are trying to use a different version of one of the TF dependencies? Is that your motivation?

**Comment by tadeegan** [comment]
We use tensorflow as an external repository/dependency to our Bazel build.  In order to get all the dependencies in place we need to call tf_workspace() in our WORKSPACE file.  Sometimes though, for things like Eigen, we want to use our own version which corresponds to the rest of our project. So we want to exclude the eigen declaration in tf_workspace() and use our own.

**Comment by gunan** [comment]
For a limited set of dependencies, I can be OK with this.
Maybe not an exhaustive list like closure_rules, but maybe we can start with eigen.

**Comment by mohantym** [comment]
Hi @tadeegan !
We are checking to see whether you still need help in this issue . 
We can  update the tool chains for respective packages (llvm, flatbuffer etc.) in one of the workspace files mentioned here for 2.x versions .
Workspace [0](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace0.bzl), [1](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace1.bzl), [2](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace2.bzl), [3](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace3.bzl).

Attached relevant [commit history](https://github.com/tensorflow/tensorflow/commits/master/tensorflow/workspace0.bzl) for reference.

Thank you!
