### ISSUE TITLE
tensorflow input/output tensor reshape c++

### ISSUE THREAD

**Issue by GT123** [tensorflow/tensorflow#15998]
currently , I am working on loading and testing a tensorflow model on android using c++, and the trained model is a full convolutional model, so the input need to be dynamically reshaped according to input image size.

I can make this done easily using python. but when turn to c++ , I can hardly find much examples and experience on this.

the trained model is converted to *.pb file , and the input and output tensor shape has been specified before conversion in python. and now I want to reshape the input and output in c++ before using the model.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by GT123** [comment]
I have not figured it out, but instead I find a way around.  
the problem lies on the code how to generate the .pb file .   since , here my requirement is to make the input size flexible, I need to add two more input layer for width and height. after generation of .pb file, the model will support variable input sizes
