### ISSUE TITLE
doc for install from source of pip+gpu missing --config=cuda and --use_gpu

### ISSUE THREAD

**Issue by udibr** [tensorflow/tensorflow#160]
I was able to use GPU from python on AWS g2.2xlarge only after adding `--config=cuda` and `--use_gpu`
to the the instructions for creating a pip at http://tensorflow.org/get_started/os_setup.md#installing_from_sources

    $ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
    $ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg --use_gpu

**Comment by vrv** [comment]
--use_gpu seems unnecessary
--config=cuda is necessary: we've updated our git docs, our website hasn't been updated.  should be updated tomorrow though!
