### ISSUE TITLE
Java/JNI , Object Detection: Not big Difference with GPU or CPU? (Insignificant difference) ~300ms with and without GPU

### ISSUE THREAD

**Issue by anonym24** [tensorflow/tensorflow#16008]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: 

**binary** by instructions https://www.tensorflow.org/versions/master/install/install_java
> 
> Install on Linux
> 
> Take the following steps to install TensorFlow for Java on Linux or macOS:
> 
> 1 Download libtensorflow.jar, which is the TensorFlow Java Archive (JAR).
> 2 Decide whether you will run TensorFlow for Java on CPU(s) only or with the help of GPU(s). To help you decide, read the section entitled "Determine which TensorFlow to install" in one of the following guides:
>  - Installing TensorFlow on Linux
>
> 3 Download and extract the appropriate Java Native Interface (JNI) file for your operating system and processor support by running the following shell commands:
> 
>  TF_TYPE="gpu"
>  OS=$(uname -s | tr '[:upper:]' '[:lower:]')
>  mkdir -p ./jni
>  curl -L \
>    "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow_jni-${TF_TYPE}-${OS}-x86_64-1.4.0.tar.gz" |
>    tar -xz -C ./jni

- **TensorFlow version (use command below)**: 1.4.0
- **Python version**: n/a, not used here (Java instead)
- **Bazel version (if compiling from source)**: n/a, not used here
- **GCC/Compiler version (if compiling from source)**: n/a, not used here
- **CUDA/cuDNN version**: Cuda compilation tools, release 8.0, V8.0.61, cuDNN 6
- **GPU model and memory**: GeForce 940MX

### Source code / logs
```
Checking to see if TensorFlow native methods are already loaded
TensorFlow native methods not found, attempting to load via tensorflow_inference
Successfully loaded TensorFlow native methods (RunStats error may be ignored)
2018-01-10 15:51:41.115224: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-01-10 15:51:41.254497: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-01-10 15:51:41.255183: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce 940MX major: 5 minor: 0 memoryClockRate(GHz): 1.2415
pciBusID: 0000:01:00.0
totalMemory: 1,96GiB freeMemory: 1,51GiB
2018-01-10 15:51:41.255217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0, compute capability: 5.0)
Model load took 313ms, TensorFlow version: 1.4.0
```

**Comment by anonym24** [comment]
actually it seems it uses GPU (allocated all available memory) nvidia-smi, but I didn't notice any speed-up, it works I guess the as on CPU

```
------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 940MX       Off  | 0000:01:00.0     Off |                  N/A |
| N/A   55C    P0    N/A /  N/A |   1913MiB /  2002MiB |     82%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1002    G   /usr/lib/xorg/Xorg                             306MiB |
|    0      1400    G   compiz                                          61MiB |
|    0      2195    G   ...el-token=642304F43EA12C293DB722E17D520289   103MiB |
|    0      5257  C+G   ...lib/jvm/java-1.8.0-openjdk-amd64/bin/java  1440MiB |
+-----------------------------------------------------------------------------+
```

**Comment by anonym24** [comment]
I running Object Detection https://github.com/tensorflow/models/tree/master/research/object_detection

on **ssd_inception_v2_coco** model  https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

And it's insignificant difference when using GPU or only CPU

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

If you post to StackOverflow, you might want to share more information on how you're measuring time. A couple of things to think about:

- If you're measuring the time for the very first call to `inferenceInterface.run` in your process, then that includes some overhead of GPU initialization by the TensorFlow runtime. So, you might want to discard that.
- The exact numbers will depend on the specifications of the GPU. From a cursory look, the GeForce 940MX [can do 950GFLOPS](https://www.techpowerup.com/gpudb/2797/geforce-940mx), while the TitanX that was used to report the numbers in the [Object Detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) can do about 7x that ([~6700GFLOPS](https://www.techpowerup.com/gpudb/2632/geforce-gtx-titan-x)). So, you could expect almost 7x more time than reported there.
- Also, if you're measuring the time with a batch size of 1, then you may be benefitting less than you could from the parallelism that GPUs have to offer.

Long story short, it is possible that with the GPU you're using, you won't see much of a speedup.
Also, would be good to make sure that your measurement isn't biased by the first run.

For example, I tried the following (showing just the relevant snippet) on a 416x416 image:

```java
try (Tensor<UInt8> input = makeImageTensor(filename)) {
  for (int i = 0; i < 10; ++i) {
    final long start = System.currentTimeMillis();
    List<Tensor<?>> outputs =
            .session
            .runner()
            .feed("image_tensor", input)
            .fetch("detection_scores")
            .fetch("detection_classes")
            .fetch("detection_boxes")
            .run();
    final long end = System.currentTimeMillis();
    for (Tensor<?> t : outputs) {
      t.close();
    }
    System.out.printf("%3d - %d ms\n", i, (end - start));
  }
}  
```

Which is only measuring the time it takes to execute the graph, not any time spent in creating the input or other things. With that I see about 1/2 the time taken with GPU than CPU (50ms vs. 100ms). I'm using an Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz CPU and an NVIDIA TitanX GPU.

Hope that helps.

**Comment by anonym24** [comment]
@asimshankar  Thanks for the answer. I'll later upload sample java project on my github page which is used for tensorflow object detection with video (I ported some Android Sample Tensorflow Code https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/DetectorActivity.java to work it on Ubuntu/Windows Java PC). I'll ask question on Stackoverflow with link for a github sample and write a link for stackoverflow question here

I process every frame from a video, so there are many calls to run and only this call I measure:
```
long startTime = System.currentTimeMillis();
// call to run method
long stopTime = System.currentTimeMillis()  - startTime;
```

I just would like to know if **Tensorflow Object Detection** is faster than **Darknet Yolo 2 Object Detection**
I see that Tensorflow is very fast with CPU than Darknet
but Darknet with GPU is much better on the same Video Card (it's much faster than ~300ms, also with 416x416 input frames)

Also I didn't take attention at Tensorflow model accuracy (mAP):

![screenshot_2](https://user-images.githubusercontent.com/8851301/34837321-1acd62b8-f703-11e7-9e0d-4b80d95074d9.png)

So its accuracy is much worst than Darknet's? 

![screenshot_2](https://user-images.githubusercontent.com/8851301/34837341-277d9578-f703-11e7-95a5-d8e3d49c23c3.png)

So I'm not sure if I should try replace Darknet Yolo 2 with Tensorflow Object Detection in my projects

**Comment by asimshankar** [comment]
Sorry, those questions are beyond the scope of my expertise - or really beyond the scope of a TensorFlow bug/feature request :)

Though, aren't you comparing different models? TensorFlow Object Detection is using mobilenet or inceptionv2 or something, while you're comparing against a different Yolo model?

@jch1 @tombstone @derekjchow @jesu9 @dreamdragon may have some comments on the mAP numbers and model characteristics. But again, this would be beyond the scope of a TensorFlow bug/feature request.
