### ISSUE TITLE
TensorFlow Installation Error on SLES 11 SP Linux 

### ISSUE THREAD

**Issue by karthikpitchaimani** [tensorflow/tensorflow#16000]
I have been trying to install tensorflow (1.3.0/1.4/1.4.1) on SLES 11 Linux, I was getting GLIBC_2.14 not found an exception, currently, we have the **GLIBC_2.11.3 version in SLES 11 SP3T**. 

Please help me to install any of **tensorflow > 0.8** versions on SLES 11 Linux and let me know the tensorflow compatible version for SLES 11. OR SLES 11 SP3 Linux is not compatible with TensorFlow any of the versions.

Thanks in Advance.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by karthikpitchaimani** [comment]
Thanks for your quick response.
**Kindly find the below details.**
Have I written custom code - **Haven't written any custom code.**
OS Platform and Distribution - **SUSE Linux and CDH 5.11.0**
TensorFlow installed from: **pip install tensorflow-1.4.0-cp36-cp36m-manylinux1_x86_64.whl**
TensorFlow version: **Tried 1.3.0, 1.4.0 and 1.4.1**
Bazel version: Haven't Installed.
CUDA/cuDNN version: Haven't installed.
GPU model and memory: NA
Exact command to reproduce: **Attached error screenshot for more reference.**
![tensorflow import error](https://user-images.githubusercontent.com/7345716/34870949-b1be6f14-f7c6-11e7-8338-a471fb665275.JPG)

Kindly help me to import tensorflow successfully.
Thanks.

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment]
So, the `GLIBC` error means that your libc version is too old. At this point I can see only three options:
* Upgrade libc on your system
* Rebuild tensorflow
* Run tensorflow within a docker container
