### ISSUE TITLE
bazel build ask for ANDROID_NDK_HOME, ANDROID_SDK_HOME -- no way to disable it

### ISSUE THREAD

**Issue by PatWie** [tensorflow/tensorflow#16009]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
('v1.5.0-rc0-1-g793280a', '1.5.0-rc0')
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
```
Build label: 0.9.0
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 19 09:31:58 2017 (1513675918)
Build timestamp: 1513675918
Build timestamp as int: 1513675918
```
- **GCC/Compiler version (if compiling from source)**:
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
- **CUDA/cuDNN version**:
toolkit_9.0 and cudnn 7.0.5_for_9.0
- **GPU model and memory**:
different machines (irrelevant)
- **Exact command to reproduce**:
see [this gist](https://gist.github.com/PatWie/aef90e72dbeaf2f79fbcaa031d74baad) which is mainly

```bash
export TF_NEED_GCP=0
export TF_NEED_CUDA=1
export TF_CUDA_VERSION="$($CUDA_TOOLKIT_PATH/bin/nvcc --version | sed -n 's/^.*release \(.*\),.*/\1/p')"
export TF_CUDA_COMPUTE_CAPABILITIES=6.1,5.2,3.5
export TF_NEED_HDFS=0
export TF_NEED_OPENCL=0
export TF_NEED_JEMALLOC=1
export TF_ENABLE_XLA=0
export TF_NEED_VERBS=0
export TF_CUDA_CLANG=0
export TF_CUDNN_VERSION=7
export TF_NEED_MKL=0
export TF_DOWNLOAD_MKL=0
export TF_NEED_MPI=0
export TF_NEED_GDR=0
export TF_NEED_S3=0
export TF_NEED_OPENCL_SYCL=0
export TF_NEED_COMPUTECPP=0
export GCC_HOST_COMPILER_PATH=$(which gcc)
export CC_OPT_FLAGS="-march=native"

./configure

bazel build --config=opt --copt=-mfpmath=both --copt=-msse4.2 --copt=-O3 --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=1 ....
```
### Describe the problem
In the past, using exactly this scripted worked. However, there are now a few issues:
The build uses `AVX2` even I haven't specified it as `--copt` (which worked in the past)

### Source code / logs
depending on the machine it gives

```
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
2018-01-10 15:06:19.070740: F tensorflow/core/platform/cpu_feature_guard.cc:36] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.
zsh: abort      python
```
or
```
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
zsh: illegal hardware instruction  python
```

On machines with AVX2 everything is fine. Further, there is no way to skip to setup ANDROID_NDK_HOME, ANDROID_SDK_HOME (I manually uncommented this in `configure.py`).

*edit*
I am willing to provide a pull-request for `configure.py`, adding something like `TF_NEED_ANDROID`.

**Comment by shivaniag** [comment]
@gunan could you see if this is something we would want to have.

**Comment by gunan** [comment]
This is because you built with `--config=opt`,  it will try to build with whatever your machine arch seems to return. So I recommend trying with omitting `--config=opt`. Please note that `-c opt` and `--config=opt` are different.

For skipping android settings, cc @angersson

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by angersson** [comment]
You should be able to get around the prompt for SDK/NDK by also setting `TF_SET_ANDROID_WORKSPACE=0`.

**Comment by reedwm** [comment]
Closing since @gunan and @angersson have answered the questions.

**Comment by ivan-aksamentov** [comment]
@reedwm  @gunan @angersson 
Neither of two work for me. I should note that:
 - `--config=opt` has nothing to do with the problem, as the question prompt pops-up in `./configure` script, before the bazel build with this flag is launched
 - setting to `1` or `0` or unsettling the `TF_SET_ANDROID_WORKSPACE` has no visible effect

This is very annoying, because this interactive prompt breaks otherwise fully automated build on a headless server with no Android SDK/NDK. Could you please check if I do something wrong?

I am investigating the relevant code here: [configure.py#L1353](https://github.com/tensorflow/tensorflow/blob/v1.5.0/configure.py#L1353). Any help is appreciated.

My build script:

```
MKL_INSTALL_PATH=${MKL_ROOT} \
TF_MKL_ROOT==${MKL_ROOT} \
CC_OPT_FLAGS="-march=native -ftree-vectorize" \
GCC_HOST_COMPILER_PATH=$(which gcc) \
PYTHON_BIN_PATH=$(which python3) \
PYTHON_LIB_PATH=$(python3 -c "import site; print(site.getusersitepackages())") \
CUDA_TOOLKIT_PATH=${HOME}/opt/cuda \
CUDNN_INSTALL_PATH=${HOME}/opt/cuda \
TF_ENABLE_XLA=1 \
TF_NEED_MPI=0 \
TF_NEED_JEMALLOC=1 \
TF_NEED_HDFS=0 \
TF_NEED_GCP=0 \
TF_NEED_GDR=0 \
TF_NEED_OPENCL=0 \
TF_NEED_CUDA=1 \
TF_NEED_OPENCL_SYCL=0 \
TF_NEED_COMPUTECPP=0 \
TF_CUDA_CLANG=0 \
TF_CUDA_VERSION=9.1 \
TF_CUDNN_VERSION=7 \
TF_CUDA_COMPUTE_CAPABILITIES=${CUDA_COMPUTE_CAPABILITITY} \
TF_NEED_MKL=1 \
TF_DOWNLOAD_MKL=1 \
TF_NEED_VERBS=0 \
TF_NEED_S3=0 \
TF_SET_ANDROID_WORKSPACE=0 \
./configure

nice -15 bazel build \
--config=cuda \
--verbose_failures \
--config=mkl \
--copt="-DEIGEN_USE_VML" \
--action_env="LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" \
//tensorflow/tools/pip_package:build_pip_package
```
