### ISSUE TITLE
Tensorboard issue with the official docker image - 1.5.0-rc0-gpu-py3

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#16011]
Hello everyone,

I have the exact same issue as stated here: https://github.com/tensorflow/tensorflow/issues/14855
And on the official tensorboard repository: https://github.com/tensorflow/tensorboard/issues/812

The fact that I am using the official Docker Image and I didn't build anything from scratch.

`tensorflow/tensorflow   1.5.0-rc0-gpu-py3   9e770d59b136        6 days ago          2.85GB`

What I get when I try to launch Tensorboard as usual:

```
# tensorboard --logdir=log_directory
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
ImportError: cannot import name 'run_main'
```

**Resolution Idea:**
I noticed that by simply running the command: `pip install tensorboard` inside the container the problem is solved and I am able to normally launch Tensorboard.

Thanks a lot for the help,

All the best,

Jonathan

**Comment by shivaniag** [comment]
Please redirect your issue to https://github.com/tensorflow/tensorboard/issues.

**Comment by alanpurple** [comment]
@shivaniag this is not about tensorboard, just import tensorflow also cause same deprecated warning message from h5py

**Comment by DEKHTIARJonathan** [comment]
This is not a deprecation issue. This is real issue

**Comment by DEKHTIARJonathan** [comment]
This is not a deprecation issue. TensorBoard is not working at all

**Comment by DEKHTIARJonathan** [comment]
This is not a deprecation issue. TensorBoard is not working at all

**Comment by alanpurple** [comment]
@DEKHTIARJonathan sorry I haven't read it carefully
and this is the only issue the deprecation is referred

**Comment by yazabaza** [comment]
I observe the same problem with plain Tensorflow, not using Docker or Tensorboard. Appears to be in h5py.

**Comment by DEKHTIARJonathan** [comment]
@yazabaza this has nothing to do with the issue related here

**Comment by yazabaza** [comment]
Not clear to me how it has nothing to do with the issue if I am observing exactly the same error:
`/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters`

**Comment by DEKHTIARJonathan** [comment]
The warning in h5py is unrelated with this issue.

The import error (and not the warning) is generated by TensorBoard, not h5py.

So I repeat, the deprecation warning in h5py IS NOT an issue, and it has nothing to do with the issue in TensorBoard.

**Comment by neilpanchal** [comment]
@DEKHTIARJonathan I second, opened an new issue here: https://github.com/tensorflow/tensorboard/issues/877

**Comment by zh794390558** [comment]
the official docker image - 1.5.0-rc1-gpu has the same problem.

**Comment by caisq** [comment]
cc @jart @chizeng

**Comment by caisq** [comment]
cc @chihuahua

**Comment by DEKHTIARJonathan** [comment]
@daniellowell please read carefully the discussion, it's really anoying to repeat over and over the same thing: https://github.com/tensorflow/tensorflow/issues/16011#issuecomment-357527284

**Comment by aselle** [comment]
@jart, could your team PTAL?

**Comment by jart** [comment]
Also note the workaround [reported](https://github.com/tensorflow/tensorboard/issues/877#issuecomment-358801103) by @MikalaiDrabovich:

```sh
python3 /usr/local/lib/python3.5/dist-packages/tensorboard/main.py --logdir=/tmp/
```
