### ISSUE TITLE
Error While Importing Tensorflow 1.5 RC0 with CUDA 9.1

### ISSUE THREAD

**Issue by navneethc** [tensorflow/tensorflow#16014]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 64-bit
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.5 RC0
- **Python version**: 3.6.3 (via Anaconda)
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.1/7.0.5
- **GPU model and memory**: GTX 1050 4GB (notebook version)
- **Exact command to reproduce**: import tensorflow (from a Python shell)

### Describe the problem
The installation of the CUDA, cuDNN and Tensorflow went smoothly. When I import tensorflow I get the error pasted below. CUDA and CUDA_PATH_V9_1 were automatically set by the installer to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1`.

Installation instructions used:

CUDA: http://docs.nvidia.com/cuda/cuda-quick-start-guide/index.html#windows
(steps 7 to 10 ignored, because it involved downloading nearly 6 GB for a test. Is it required? I haven't installed TF in Windows before.)
cuDNN: http://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html
(step 5 ignored as I didn't have a Visual Studio project - is there a VS project in the context of Tensorflow?)
Tensorflow: https://www.tensorflow.org/install/install_windows
(`pip install --ignore-installed --upgrade tensorflow-gpu==1.5.0rc` inside a conda environment)

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
(tensorflow) C:\Users\Navneeth>python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\Navneeth\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Users\Navneeth\Miniconda3\envs\tensorflow\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Navneeth\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Navneeth\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Navneeth\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\Navneeth\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-toolkit
```

**Comment by aalexsmithh** [comment]
You likely have `cudart64_91.dll` instead of `cudart64_90.dll`. It seems as though tf doesn't yet have support for CUDA 9.1.

**Comment by navneethc** [comment]
Yes, that's true, I can see the dll for 9.1. 9.1 is the default download option at the CUDA website. Since the 1.5.0 rc page* didn't specify anything about minor versions, I assumed 9.1 was okay. 

* https://github.com/tensorflow/tensorflow/releases/tag/v1.5.0-rc0

**Comment by aalexsmithh** [comment]
The `tf-nightly` build might might have support for 9.1, although I havent looked into that. Also be sure to close this issue!

**Comment by navneethc** [comment]
Could someone tell me when 9.1 is likely to be supported? And for future reference: where can I find the exact versions of the dependencies? Thanks.

**Comment by ybsave** [comment]
This issue is still not solved yet? I encountered the same problem; I am also working on Windows 10. The most recent tensorflow-gpu version at https://pypi.python.org/pypi/tensorflow-gpu is still built on January 13. Any updated version for windows could support Cuda 9.1? Thanks.

**Comment by abhigoku10** [comment]
@navneethc @aalexsmithh @cy89  Hi could some one help me out , i have installed cuda 9.1 with cuddn 7.1 and all the dlls are present in the folder yet when i try to use tensorflow gpu it give me "ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-toolkit" but when i download the cuda 9.0 it again gives the same error saying cudart64_80.dll is not available . 

I have tired installing all the version of the tensorflow and cuda yet i get error i have checked the path variable to not sure why i am getting this error

**Comment by ybsave** [comment]
@abhigoku10 Until the 01/26/2018 nighty built version, the tensorflow still does NOT support cuda 9.1, but only cuda 9.0. Just see another nighty built version 02/15/2018; not know whether that supports.

If it doesn't work, just use cuda 9.0.

**Comment by navneethc** [comment]
> I have tired installing all the version of the tensorflow and cuda

@abhigoku10 Make sure that you are using CUDA 9.0/cuDNN 7 only with TF version 1.5 or higher.

**Comment by abhigoku10** [comment]
@ybsave  for me one time it worked then, due to other reasons i re-installed it and now its not working 

@navneethc  i have run it with cuda 9.0 yet i was not successful i shall give one last time again

**Comment by tlokeshkumar** [comment]
The problem I got was the mismatch between the CUDA version and CUDNN version. I initially installed CUDA 9 and CUDNN v7.0.5 (for CUDA 9.1) which caused these problems. Once the cudnn version is changed (the  version for CUDA 9) it solved the problem.

**Comment by hashamMunir** [comment]
I dont know what to do, I have tried all versions and everything found in two days on the internet. But this 
>>>ImportError: Could not find 'cudart64_90.dll'
is not leaving me alone. 
I am trying to install Tensorflow-gpu
on windows 10 64
tired: CUDA 9.0 , 9.1, 8.0
Tried cudNN: 7.2,7.1,7.0
Please someone help me out in it

**Comment by ybsave** [comment]
@hashamMunir It seems that you may not set your correct Windows environment path, leading to cannot find the dll. As discussed above, just use Cuda 9.0, cudnn 7, and make sure setting the "PATH" variable correctly in your system. Then it should work.

**Comment by hashamMunir** [comment]
@ybsave  Thank you for your reply. I think I did it I set the path in the system 
>CUDA_PATH_v9_0 : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0
>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\lib
is it ok, or I did it wrong??
Thanks again
