### ISSUE TITLE
NNAPI/libneuralnetwors.so does not work for other models than default mobilenet_quant_v1_224.tflite

### ISSUE THREAD

**Issue by benshi001** [tensorflow/tensorflow#16033]
I have made changes to tensorflowlite to force it use nnapi on my android 8.1 phone, and the nnapi only worked normally for the default default mobilenet_quant_v1_224.tflite.

The nnapi/libneuralnetworks.so did not work for the tensorflow_inception_graph.tflite inside the attached asserts.zip, which was built by toco, from tensorflow_inception_graph.pb of https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android

My steps,
1. generated tensorflow_inception_graph.tflite from tensorflow_inception_graph.pb by toco
2. add 7 extra lines to labels.txt "a\nb\nc\nd\ne\ng\ng"
3. copy new labels.txt and tensorflow_inception_graph.tflite to my bazel cache
4. apply the attached patch a.txt to tensorflow
5.  bazel build --cxxopt=--std=c++11 //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo --config=android_arm64 --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
6. adb install -r <apk_file>

If the nnapi is not forced to use, then the apk run normally, though the results are wrong. But if I forced it to use nnapi, then the apk crashed.

I guess the tensorflow_inception_graph.tflite contained some operators which were not supported by nnapi/libneuralnetwors.so. How can I confirm it?

Thank you.

[a.txt](https://github.com/tensorflow/tensorflow/files/1622153/a.txt)
[assets.zip](https://github.com/tensorflow/tensorflow/files/1622067/assets.zip)

**Comment by andrehentz** [comment]
Could you inspect the output of 'adb logcat' for errors from the demo app?

**Comment by benshi001** [comment]
The log

01-12 02:45:42.465  7030  7030 D TfLiteCameraDemo: Created a Tensorflow Lite Image Classifier.
01-12 02:45:42.763  7030  7047 D TfLiteCameraDemo: Timecost to put values into ByteBuffer: 20
01-12 02:45:42.764  7030  7047 I TfLiteCameraDemo: load function ANeuralNetworksModel_create successfully
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: load function ANeuralNetworksModel_addOperand successfully
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: load function ANeuralNetworksModel_setOperandValue successfully
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 142 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 146 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 155 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 164 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 176 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 184 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 206 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 211 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 216 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 234 3********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 236 3********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 259 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 343 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: load function ANeuralNetworksModel_addOperation successfully
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 349 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 142 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 146 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 155 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 164 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 176 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 184 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 206 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 211 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 216 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 234 17********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 236 17********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 249 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 343 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 349 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 142 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 146 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 155 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 164 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 176 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 184 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 206 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 211 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 216 ********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 234 13********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: ********** 236 13********
01-12 02:45:42.765  7030  7047 I TfLiteCameraDemo: Op code 13 is currently not delegated to NNAPI

**Comment by benshi001** [comment]
I saw the reason, because BuiltinOperator_LOCAL_RESPONSE_NORMALIZATION can not be delegated to NNAPI.

Thank you.
