### ISSUE TITLE
raise PiCameraMMALError(status, prefix) picamera.exc.PiCameraMMALError: Failed to enable connection: Out of resources

### ISSUE THREAD

**Issue by prabhundps** [tensorflow/tensorflow#16036]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by prabhundps** [comment]
Solved the issue, sir, thanks for your reply.

**Comment by nnguyen1602** [comment]
@prabhundps Hello, I am having the same issue. Could you please explain how you solved it?

**Comment by prabhundps** [comment]
@nnguyen1602, Will you please send me your code?

**Comment by jugs695369** [comment]
Same error help please
