### ISSUE TITLE
Link gives 404

### ISSUE THREAD

**Issue by unsalatasoy** [tensorflow/tensorflow#16038]
https://github.com/tensorflow/models/tree/master/syntaxnet#installation gives   404

**Comment by cy89** [comment]
@unsalatasoy where does the link come from?

**Comment by cy89** [comment]
@unsalatasoy it looks like it's back up again. I'll close, please reopen if you're still having problems.

**Comment by unsalatasoy** [comment]
https://github.com/tensorflow/models/tree/master/syntaxnet#installation 
this link still gives 404. I got this link from the following link. 
https://www.tensorflow.org/versions/r0.12/tutorials/syntaxnet/

I think the right link must be following. Could you please confirm me
https://github.com/tensorflow/models/tree/master/research/syntaxnet
