### ISSUE TITLE
Feature Request: clarify supported environments for official binaries.

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#16046]
As it stands now, binary release of TensorFlow 1.5 is set to drop compatibility with Ubuntu 14.04 ( https://github.com/tensorflow/tensorflow/issues/15777), and compatibility with Debian Linux distros, such as Amazon Linux AMI (`ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found`).

To avoid surprise, TensorFlow should either:
1. Follow other open-source projects like Ray/PyTorch and provide official binaries for these systems
or
2. Document that support is dropped, to encourage other players (ie, AWS) to take over the job of providing these binaries

@martinwicke

**Comment by martinwicke** [comment]
@gunan at the very least we must update the support matrix, which is public. 

However, there is a valid question as to whether we can continue to have our binaries work on 14.04 simply by building against an older GLIBC.

**Comment by yongtang** [comment]
@yaroslavvb Debian stretch uses `glibc 2.24`. This is new than Ubuntu 16.04's `glibc 2.23`. I think Debian stretch might still work (haven't tried yet).

**Comment by yaroslavvb** [comment]
PS: Amazon Linux uses glibc 2.18

**Comment by jart** [comment]
I'm surprised to hear that about Amazon. It seems that a few weeks ago [Amazon Linux 2](https://aws.amazon.com/amazon-linux-2/release-notes/) was released which has glibc 2.25.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by yaroslavvb** [comment]
@jart I guess it's still in the "candidate" stage, the images I launched recently still have previous version

**Comment by yaroslavvb** [comment]
IE, Deep Learning AMI's are still using Amazon Linux 1 -- https://aws.amazon.com/marketplace/pp/B01M0AXXQB

**Comment by yongtang** [comment]
I was playing with AWA Linux 2 and noticed there is a small build failure when compiling TensorFlow (missing `#include <functional>`). Added a PR #16470 for that fix.

**Comment by drpngx** [comment]
Closing since it seems that the PR was merged. Feel free to reopen if there's a remaining issue.

**Comment by yaroslavvb** [comment]
it's still not clear if Ubuntu 14.04 binaries will be supported. Someone mentioned Google possibly providing 14.04 binaries to allow compatibility with GCP dataflow containers which are on 14.04

**Comment by martinwicke** [comment]
The 1.5 final binaries should work on 14.04. If they don't we made some mistake and will patch.
