### ISSUE TITLE
Empty tensorflow/python/tools directory after build tf 1.5 from source

### ISSUE THREAD

**Issue by GustavZ** [tensorflow/tensorflow#16068]
I rebuild Tensorflow-GPU Version 1.5.0rc0 from source with Bazel Version 0.9.0 with CUDA 9 and cuDNN 7 to see changes from my previous version 1.4 also build from source with same prerequesites.

But now the tensorflow/python/tools directory is empty? Has anybody experienced the same?
Or Did these scripts get moved to another directory?

**Comment by cy89** [comment]
@GustavZ do you mean this directory: https://github.com/tensorflow/tensorflow/tree/r1.5/tensorflow/python/tools

**Comment by GustavZ** [comment]
yes exactly this one.
I am now switching back to 1.4 for multiple reasons.

**Comment by cy89** [comment]
@GustavZ seems reasonable. I'll close for now--it's not clear that this is widespread. Please reopen if you (or others) encounter this again.
