### ISSUE TITLE
Which CUDA/cuDNN version should I chose for tf-1.50

### ISSUE THREAD

**Issue by CangHaiQingYue** [tensorflow/tensorflow#16062]
![eo hqbj __vt _49a35ztc](https://user-images.githubusercontent.com/30284428/34855697-10dd4c5e-f77c-11e7-8174-3d1925170698.png)

**Comment by arunmandal53** [comment]
If installing using pip then cuda 9.0 and cudnn 7.0.

**Comment by CangHaiQingYue** [comment]
Did that means both cudnn 7.0.4 and 7.0.5 are ok?

**Comment by arunmandal53** [comment]
I have not used pip package but, i think both option should work.

**Comment by CangHaiQingYue** [comment]
OK！THANKS！
