### ISSUE TITLE
Feature request: (optionally) return all audio streams in tf.contrib.ffmpeg.decode_audio

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#16073]
I'm trying to read [musdb18](https://sigsep.github.io/musdb.html) with `tf.data` and it comes in the form of mp4 files with multiple audio streams so `ffmpeg -map` is needed.

`tf.contrib.ffmpeg.decode_audio` cannot be configured to choose the audio stream. I wonder if we could have a `tf.contrib.ffmpeg.decode_audios` that returns every audio stream in the file, or if we could have a new argument in `tf.contrib.ffmpeg.decode_audio` for choosing streams.

Being able to choose the audio stream is also important for getting the right language in a movie file's audio, and similarly `tf.contrib.ffmpeg.decode_video` could need the same extension (though multiple video streams is not as common AFAIK).

**Comment by carlthome** [comment]
Maybe @faroit has thoughts on this?

**Comment by shivaniag** [comment]
@vrv do you have any comments on this too or redirect to who would be the best person?

**Comment by vrv** [comment]
@fredbertsch I think knows most about ffmpeg ops

**Comment by yongtang** [comment]
Added a PR #16101 so that it is possible to provide an optional `stream="0"` for ffmpeg to select. Please take a look.

**Comment by faroit** [comment]
@carlthome this is great!

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.
