### ISSUE TITLE
Can't install tensorflow on OS X - problem with virtualenv

### ISSUE THREAD

**Issue by snailrowen** [tensorflow/tensorflow#161]
I try to install tensorflow, but run into this message, what should I do?

Johans-MacBook-Pro:~ johanbjorck$ pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Could not find an activated virtualenv (required).
Johans-MacBook-Pro:~ johanbjorck$

**Comment by yyttr3** [comment]
try running 
export PIP_REQUIRE_VIRTUALENV=false
from the terminal and reinstalling.

**Comment by snailrowen** [comment]
It worked, thanks a lot :D

2015-11-11 22:28 GMT-05:00 Christian Beasley <notifications@github.com>:

**Comment by yyttr3** [comment]
You're welcome :D

**Comment by vrv** [comment]
Thanks for the help @snailrowen!

**Comment by vrv** [comment]
Er, @yyttr3
