### ISSUE TITLE
No tf.metrics.true_negatives

### ISSUE THREAD

**Issue by mikevoets** [tensorflow/tensorflow#16108]
**TensorFlow version**: 1.4.1

Is there any particular reason for why there is no `tf.metrics.true_negatives` method? I know it's simple to calculate from other confusion metrics that are available, but I was wondering why the developers chose to let this one method out.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mikevoets** [comment]
Have I written custom code: N/A
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment]
Seems like a good addition. @ispirmustafa can decide if it's a welcome contribution.

**Comment by ispirmustafa** [comment]
There is [tf.metrics.true_negatives](https://www.tensorflow.org/versions/master/api_docs/python/tf/metrics/true_negatives)
