### ISSUE TITLE
How can I batch images of arbitrary sizes in tensorflow?

### ISSUE THREAD

**Issue by LvJC** [tensorflow/tensorflow#16124]
I want to realize arbitrary inputs that I can batch them in one batch.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by DEKHTIARJonathan** [comment]
Please go to stackoverflow, this is not the place to discuss about this.

**Comment by LvJC** [comment]
@DEKHTIARJonathan OK then

**Comment by DEKHTIARJonathan** [comment]
Please close the issue
