### ISSUE TITLE
Documentation for GridLSTMCell is lacking and does not match the paper

### ISSUE THREAD

**Issue by gcampax** [tensorflow/tensorflow#16146]
### Describe the problem

The documentation for tf.contrib.rnn.GridLSTMCell cites the paper "Grid Long Short-Term Memory", by Kalchbrenner et al.
The paper describes an architecture, called the 2D Grid LSTM, to replace a stack of LSTM cells. In a 2D Grid LSTM, 2 state components are passed from one layer to the next vertically.

In Tensorflow RNN parlance, one would expect both the state and the output of the cell to be an LSTMStateTuple, which would allow seamless integration with a MultiRNNCell.
In the current implementation, instead it appears that the vertical unrolling is done internally to the GridLSTMCell.
I say it appears, because I can't quite make sense of the arguments and their documentation: specifically, there is a required "num_frequency_block" argument whose meaning is quite obscure.
Looking at the implementation also did not help me understand what value is actually expected in that parameter, and the related parameters.
Note that the above mentioned paper does not talk about frequencies anywhere.

Would it be possible to expand on the documentation for the cell, as well as provide a code example on how to replicate the 2D Grid LSTM from the paper?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gcampax** [comment]
None of that is relevant, because this is a documentation issue, but sure:

Have I written custom code: n/a
OS Platform and Distribution: n/a
TensorFlow installed from: n/a
TensorFlow version: 1.4 (but master has the same problem)
Bazel version: n/a
CUDA/cuDNN version: n/a
GPU model and memory:  n/a
Exact command to reproduce: n/a

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment]
Sadly, we don't have an active maintainer for that code.

Maybe @MarkDaoust has a suggestion for documentation, but as it stands, this part of the code in contrib comes "as is".

**Comment by selcouthlyBlue** [comment]
I think I have an exampe use GridLSTMCell that belongs to contrib.grid_rnn.

```
class GridRNNTest(tf.test.TestCase):
    def setUp(self):
        self.num_features = 1
        self.time_steps = 1
        self.batch_size = 1
        tf.reset_default_graph()
        self.input_layer = tf.placeholder(tf.float32, [self.batch_size, self.time_steps, self.num_features])
        self.cell = grid_rnn_cell.Grid1LSTMCell(num_units=8)

    def test_simple_grid_rnn(self):
        self.input_layer = tf.unstack(self.input_layer, self.time_steps, 1)
        rnn.static_rnn(self.cell, self.input_layer, dtype=tf.float32)

class BidirectionalGridRNNTest(tf.test.TestCase):
    def setUp(self):
        self.num_features = 1
        self.time_steps = 1
        self.batch_size = 1
        tf.reset_default_graph()
        self.input_layer = tf.placeholder(tf.float32, [self.batch_size, self.time_steps, self.num_features])
        self.cell_fw = grid_rnn_cell.Grid1LSTMCell(num_units=8)
        self.cell_bw = grid_rnn_cell.Grid1LSTMCell(num_units=8)

    def test_simple_bidirectional_grid_rnn(self):
        self.input_layer = tf.unstack(self.input_layer, self.time_steps, 1)
        rnn.static_bidirectional_rnn(self.cell_fw, self.cell_bw, self.input_layer, dtype=tf.float32)
```

**Comment by JaeDukSeo** [comment]
Umm  so is anyone working on this? Can I work on it...?

**Comment by selcouthlyBlue** [comment]
I don’t think anyone is right now. You can take a shot at it.
