### ISSUE TITLE
Dataset from string generator raises Exception with python 2

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#16149]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS X 10.12.6
- **TensorFlow installed from (source or binary)**: binary cpu version from pypi
- **TensorFlow version (use command below)**: ('v1.5.0-rc0-9-gf9472619f6', '1.5.0-rc1')
- **Python version**: 2.7.14

### Describe the problem
I'm reading text data from file in generator. Encoding: UTF-8.
After some preprocessing i return it in generator manner.
Next, i'm trying to create Dataset from this generator.

Code below produce exception in both Python 2&3 for TensorFlow 1.4.
For TF 1.5.rc1 & Python 3 there is no errors.
For TF 1.5.rc1 & Python 2 error exist.

### Source code / logs
```python
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf


def generator():
    data = [
        [u'Простой', u'тест', u'юникода'],
        [u'никогда', u'не', u'бывает', u'простым']
    ]

    for seq in data:
        yield seq, [0, 1, 2, 3]


def dataset():
    dataset = tf.data.Dataset.from_generator(
        generator,
        (tf.string, tf.int32),
        (tf.TensorShape([None]), tf.TensorShape([None]))
    )
    dataset = dataset.padded_batch(2, padded_shapes=([None], [None]), padding_values=('', 0))

    return dataset


iterator = dataset().make_one_shot_iterator()
next_element = iterator.get_next()

with tf.Session() as sess:
    value = sess.run(next_element)
    print(value)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yongtang** [comment]
There might be some discrepancy between Python 2 and Python 3 with TensorFlow. In Python 3 the unicode is considered as UTF8 while in Python 2 a default (ascii) encoding is assumed.

Created a PR #16168 for a fix.
