### ISSUE TITLE
Accidentally cancelled inceptionV3 during install, now can't install at all

### ISSUE THREAD

**Issue by ryanboldi** [tensorflow/tensorflow#16164]
Hello,
i was setting up tensorflow for image classification, and after i ran : 

python -m scripts.retrain \
  --bottleneck_dir=tf_files/bottlenecks \
  --model_dir=tf_files/models/"${ARCHITECTURE}" \
  --summaries_dir=tf_files/training_summaries/"${ARCHITECTURE}" \
  --output_graph=tf_files/retrained_graph.pb \
  --output_labels=tf_files/retrained_labels.txt \
  --architecture="${ARCHITECTURE}" \
  --image_dir=tf_files/flower_photos

It automatically started installing inception, i realized that i needed to change some options so i cancelled the install of inception.
Now i believe that i have a half install that doesn't let me install the full package or use the half package.

I may be wrong, but any suggestions would be appreciated.
FYI: i've run :
pip install inception, to which i receive a "python setup.py egg_info" failed with error code 1 in {my local/temp dir}

I also just tried running the scripts.retrain again, to which i receive a "EOFError: compressed file ended before the end-of-stream marker was reached"

Running on Windows 7

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ryanboldi** [comment]
Have I written custom code
OS Platform and Distribution: Windows 7
TensorFlow installed from: github and pip install
TensorFlow version N/A
Bazel version N/A
CUDA/cuDNN version N/A
GPU model and memory: gtx 970 16gb
Exact command to reproduce: python -m scripts.retrain 
--bottleneck_dir=tf_files/bottlenecks 
--model_dir=tf_files/models/"${ARCHITECTURE}" 
--summaries_dir=tf_files/training_summaries/"${ARCHITECTURE}" 
--output_graph=tf_files/retrained_graph.pb 
--output_labels=tf_files/retrained_labels.txt 
--architecture="${ARCHITECTURE}" 
--image_dir=tf_files/flower_photos

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment]
@shlens any idea?

**Comment by petewarden** [comment]
You should be able to recover from this error by deleting model_dir, in your case `tf_files/models/"${ARCHITECTURE}"`. Closing this for now, please reopen if that doesn't work!

**Comment by rabbi2211** [comment]
facing the same issue. Can you help me, how have you resloved it?
