### ISSUE TITLE
Documentation Method Templates Improvement

### ISSUE THREAD

**Issue by aidangomez** [tensorflow/tensorflow#16167]
### System information
N/A

### Describe the problem
The method/class templates in documentation should include a full, functioning path to the method instead of just truncating to the method's name.

I.e. this is what we have at present (bad): 
<img width="399" alt="screen shot 2018-01-16 at 2 23 08 pm" src="https://user-images.githubusercontent.com/9597721/35007940-0511d55c-fac9-11e7-9d0c-4be2db021533.png">

This is a more practical and copy/paste-friendly version:
<img width="426" alt="screen shot 2018-01-16 at 2 22 49 pm" src="https://user-images.githubusercontent.com/9597721/35007976-2970cdc2-fac9-11e7-80b8-0ec1e2334734.png">

I'm constantly just grabbing method templates, pasting to my text editor and then coming back to docs to copy/paste the package path which is now the header of the page; which is an awful workflow.

### Source code / logs
N/A

**Comment by aselle** [comment]
@wolffg, could you consider this feature req. Thanks for the suggestion @aidangomez.

**Comment by MarkDaoust** [comment]
This is an easy fix, and clear win for regular functions.

It's probably better not to change this for methods. Adding the path to the class, on each method signature  seems like unnecessary noise, since you rarely do a direct lookup of the method:

get_collection(...)
tf.Graph.get_collection(...)

get_name_scope(...)
tf.Graph.get_name_scope(...)


WDYT?

**Comment by aidangomez** [comment]
Agreed. That's an important distinction.

**Comment by MarkDaoust** [comment]
Fix inflight.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.
