### ISSUE TITLE
Tensorboard is down after upgrading the tensorflow?

### ISSUE THREAD

**Issue by JohnnyY8** [tensorflow/tensorflow#16180]
Hello everyone:

I meet a issue about tensorboard after upgrading the tensorflow. It runs nicely before, but I want maintain some Python2.7 codes in Python3.4. That is why I install tensorflow .whl file of Python 3.4 and modify some grammer from Python2.7 to Python3.4. Then codes still run fine, but tensorboard is donw. The error message as following:

![image](https://user-images.githubusercontent.com/12611573/35029640-d1981942-fb96-11e7-9b89-c3c14ffaa54b.png)

OS Platform: Ubuntu 14.04
TensorFlow installed from: pip instll .whl file
TensorFlow version: tensorflow 1.2.1 for Python2, but can not check the version for Python 3

What should I do for this issue? degrade tensorflow or upgrade CUDA?
Can anybody give me any help? Thank you!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sleighsoft** [comment]
I noticed that when installing tensorflow-1.5.0rc1 it installs an old version of tensorboard `0.1.8` when install tensorflow with pip.

**Comment by JohnnyY8** [comment]
@sleighsoft I think the new version tensorboard needs CUDA 9. Is here any ways to degrade tensorboard for Python2?

**Comment by sleighsoft** [comment]
You can do `pip uninstall tensorflow-tensorboard` and then `pip install tensorflow-tensorboard==<your_version>`. At least this is what I do as long as pip installs the wrong tensorflow-tensorboard version.

**Comment by JohnnyY8** [comment]
@sleighsoft Thanks! I will give a try. But there is one more question? How can I check the tensorboard version?

**Comment by JohnnyY8** [comment]
@sleighsoft Here is problem. I can not uninstall tensorboard?
Do you have any methods for this?
![image](https://user-images.githubusercontent.com/12611573/35179615-e6831b88-fdd8-11e7-9634-86e58924e696.png)

**Comment by sleighsoft** [comment]
run `pip freeze` to see what you have installed first maybe.

**Comment by JohnnyY8** [comment]
@sleighsoft I have tried to run pip freeze, the details as following. There is only one about tf, nothing about tensorboard.

absl-py==0.1.8
alabaster==0.7.10
astor==0.6.2
Babel==2.5.1
bleach==1.5.0
certifi==2017.11.5
chardet==3.0.4
decorator==4.2.1
docutils==0.14
entrypoints==0.2.3
gast==0.2.0
html5lib==0.9999999
idna==2.6
imagesize==0.7.1
ipykernel==4.7.0
ipyparallel==6.0.2
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.0
jedi==0.11.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.1
jupyter-core==4.4.0
Markdown==2.6.11
MarkupSafe==1.0
mistune==0.8.3
nbconvert==5.3.1
nbformat==4.4.0
nose==1.3.7
notebook==5.2.2
numpy==1.14.0
pandocfilters==1.4.2
parso==0.1.1
pexpect==4.3.1
pickleshare==0.7.4
prompt-toolkit==1.0.15
protobuf==3.5.1
ptyprocess==0.5.2
Pygments==2.2.0
python-dateutil==2.6.1
pytz==2017.3
pyzmq==16.0.3
qtconsole==4.3.1
requests==2.18.4
simplegeneric==0.8.1
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.6.6
sphinxcontrib-websupport==1.0.1
tb-nightly==1.5.0a20180114
termcolor==1.1.0
terminado==0.8.1
testpath==0.3.1
tf-nightly-gpu==1.6.0.dev20180114
tornado==4.5.3
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.1.0

**Comment by sleighsoft** [comment]
So it is probably not installed or you already uninstalled it. Have you tried running `pip install tensorflow-tensorboard==<your_version>`. I think I cannot help you more from that point on.

**Comment by JohnnyY8** [comment]
@sleighsoft Truly thank you!
I have tried other solutions. But still did not work.
I think the point is my tensorboard always depends on python3.5. I do not know why.
My python2.7 still work on tensorflow.
![image](https://user-images.githubusercontent.com/12611573/35196071-35c5b64e-ff08-11e7-9419-ff534647b267.png)
I will keep checking other methods. Thanks again!

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment]
Is that still a problem?

**Comment by sleighsoft** [comment]
It seems that when installing tf15rc1 now it installs tensorflow-tensorboard1.5.0
This seems solved

**Comment by JohnnyY8** [comment]
@drpngx  Thanks, I reinstall the tensorflow. It seems solved.

**Comment by JohnnyY8** [comment]
@sleighsoft Thanks. I just reinstall tensorflow, because it is not convenient for other people to use it.
