### ISSUE TITLE
Implement reduceByKey or groupByKey?

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#1618]
Can we implement a Implement reduceByKey or groupByKey operation?

**Comment by sherrym** [comment]
Could you please elaborate on your usage model and expectations of these operations? Thanks.

Sherry

**Comment by fayeshine** [comment]
@sherrym for example, if we have reduceByKey operation then we can reduce the number of instance on every truth-prediction pair so that we can implement the confusion matrix in tensorflow api.
#1606 
what's more, there's many preprocessing procedure before training a model, if the data is big then we need to use spark or whatever to do the preprocessing distributedly. If tensorflow support map/reduce api, then we can just directly do it in tensorflow and don't need other toolchains.
Actually, the tensorflow graph architecture is quite similar to spark's DAG architecture, and I believe we could do similar things as what spark could do.

**Comment by girving** [comment]
@fayeshine: Since we have a confusion matrix op as of #1999, is this obsolete?

**Comment by fayeshine** [comment]
@girving thanks for adding confusion matrix, however we may still need groupByKey or reduceByKey for data preprocessing

**Comment by girving** [comment]
@fayeshine: Note that `confusion_matrix` was implemented on top of existing TensorFlow ops.  Does that mechanism suffices for your use cases?  If not, can you propose a specific semantics of what you want?

**Comment by aselle** [comment]
Automatically closing because there was no response. Please reopen if it is still an issue.
