### ISSUE TITLE
Any Roadmap Available?

### ISSUE THREAD

**Issue by stephenbaidu** [tensorflow/tensorflow#162]
As stated on http://tensorflow.org,
> TensorFlow is not complete; it is intended to be built upon and extended.

I would therefore like to know if a roadmap exists.

**Comment by bhack** [comment]
Yes something like [OpenCV weekly meetings](http://code.opencv.org/projects/opencv/wiki/2015), Torch roadmap at https://github.com/torch/torch7/issues/326 or [Gitlab direction](https://about.gitlab.com/2016/01/05/future-direction-gitlab/) could be really helpful for better planning PR activities by the community and to not overlap too much with Google Tensorflow team internal work.

**Comment by bhack** [comment]
See also https://about.gitlab.com/2016/01/11/being-a-good-open-source-steward/

**Comment by bhack** [comment]
@vrv Thank you. Can you add a section "we are on..."  where you can expose what is already in work by Google team. It seems that you don't use WIP PR for internals so could be useful to update a section like this to avoid contributors to start to works on things already allocated internally.

**Comment by martinwicke** [comment]
These are all things we are actively working on. We don't yet have a more aspirational longer term timeline yet, when we do, we will publish that as well. That may include things we know we want but are not yet working on. 

Where there are things that are useful for the community to take on, we have marked them with the [contributions welcome](https://github.com/tensorflow/tensorflow/labels/contributions%20welcome) tag. For instance, many issues relating to performance improvements are marked this way.

**Comment by bhack** [comment]
@martinwicke Ok thank you for the clarification. But e.g. https://github.com/tensorflow/tensorflow/issues/22 is tagged contributions welcome but it is also in the Roadmap. Is it tagged contributions welcome because is "long term" or do you have already started to design/code on it? I'm asking you this because the mean of my previous comment was to clarify, for a contributor, what make sense to start in his own fork to not conflict further with an emerging internal code developed on same target.

**Comment by martinwicke** [comment]
In case of #22, We are coordinating with the people on that thread (and
others). It hasn't gotten beyond initial planning yet. If you are
considering contributing for anything, do comment on the associated issue
to find out the current state of affairs and to avoid duplicating effort.
The issues will be updated with major developments, but usually the actual
development happens outside the issue thread.
