### ISSUE TITLE
Tensorflow doesn't delete previous checkpoints

### ISSUE THREAD

**Issue by XMabbX** [tensorflow/tensorflow#16215]
### System information
- Linux Ubuntu 16.04:
- Tensorflow version 1.4.1*:
- Python 3.5.2: 

### Describe the problem

A brief summary is that, if I run multiple times my training script tensorflow doesn't delete the checkpoints created in previous runs of the script.

I am preparing a automatic script that every X days runs and train with the new data collected. But I am facing a problem, even that I have configured the saver to keep the 2 last checkpoints, it doesn't work as I expected. 

Example:
I configure to run 100.000 iterations and each 10.000 to save the checkpoint. The system works and starts saving 10.000, 20.000, ... And when get to 30.000 starts deleting the firsts checkpoints. When the script ends I have the 2 last checkpoints(90.000 and 100.000). 

Then when I train again the system starts from the last checkpoint, in this example the 100.000, and do the same as the previous, 110.000, 120.000,.. and when gets to the 130.000 starts to delete the 100.000 and so on. But the 2 checkpoints from the previous run(90.000 and 100.000) remain there even that in the checkpoint txt are not listed there.

This will be repeated in every run of the script, creating files that I don't need anymore and growing during the time.

This is an intended behavior(expecting to the user to delete or manage manually) or it is really a problem?
It exist any workaround?

Thank you for your time and amazing work.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by aselle** [comment]
This is intended behavior. I suggest you create a wrapper script and use a separate directory for each new run.

**Comment by mishurov** [comment]
Take a look at the source code of tf.train.SessionManager. In order to restore all the checkpoints in the directory, and hence to delete the old ones during the next run, they use something like this:
```python
ckpt = tf.train.get_checkpoint_state(checkpoint_dir)
saver.restore(sess, ckpt.model_checkpoint_path)
saver.recover_last_checkpoints(ckpt.all_model_checkpoint_paths)
```
