### ISSUE TITLE
maxout lose the number of features in the shape of its output

### ISSUE THREAD

**Issue by carltonwang** [tensorflow/tensorflow#16225]
In tf.contrib.layers.maxout(), when the shape of "inputs" is not completely specified, the shape of its output will be completely unknown, such as [None, None, None] in the 3d case.
Since "num_units" has specified the final number of features in the maxout axis, the output should set its shape accordingly:
https://github.com/tensorflow/tensorflow/pull/16114

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by carltonwang** [comment]
leave them as N/A

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.
