### ISSUE TITLE
tf.contrib.rnn.LSTMCell()  dtype not defined. Error when creating initializer for bias variable. 

### ISSUE THREAD

**Issue by arbellea** [tensorflow/tensorflow#16228]
- **OS Platform and Distribution**: Mac OSX 10.10.5
- **TensorFlow installed from**: binary
- **TensorFlow version**: 1.5.0rc
- **Python version**:   3.6
- **Have I written custom code**: NA
- **Bazel version**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**:NA

- **Exact command to reproduce**:

import tensorflow as tf
lstm = tf.contrib.rnn.LSTMCell(10)
input_tensor = tf.ones([10,50])
lstm.build(input_tensor.get_shape())

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 719, in build
    initializer=init_ops.zeros_initializer(dtype=self.dtype))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py", line 88, in __init__
    self.dtype = dtypes.as_dtype(dtype)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py", line 627, in as_dtype
    "Cannot convert value %r to a TensorFlow DType." % type_value)
TypeError: Cannot convert value None to a TensorFlow DType.

### Describe the problem
It seems that LSTMCell does get the dtype in __init__ and does not pass to parent object. Then lstm._dtype is always None. 
A workearound is to add:
lstm._dtype = 'float32'
before:
lstm.build(input_tensor.get_shape())

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
Bazel version
CUDA/cuDNN version
GPU model and memory

**Comment by arbellea** [comment]
Done

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment]
@ebrevdo can correct me, but I think we should probably use the cell that's in core tensorflow instead: `tf.nn.rnn_cell.LSTMCell`.

**Comment by ebrevdo** [comment]
@drpngx the contrib cell is an alias.  this is indeed an issue.  we don't currently accept or propagate a dtype argument from the LSTM constructor.

**Comment by ebrevdo** [comment]
@arbellea PRs to add this are welcome.

**Comment by yongtang** [comment]
Added a PR #18178 for the fix.
