### ISSUE TITLE
//tensorflow/contrib/gan:losses_impl_test fails with AssertionError 

### ISSUE THREAD

**Issue by namrata-ibm** [tensorflow/tensorflow#16238]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04  s390x
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: v1.4.1
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.7.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: No GPU
- **GPU model and memory**: NA
- **Exact command to reproduce**: bazel test -c opt //tensorflow/contrib/gan:losses_impl_test

### Describe the problem
One of the sub-test `test_stable_global_norm_unchanged` fails on s390x with 
`AssertionError: 110.709068 != 110.709084 +/- 0.000010`

Seems like a minor difference, so I tried changing the tolerance slightly as below:
```
-        self.assertNear(gnorm_np, precond_gnorm_np, 1e-5)
+        self.assertNear(gnorm_np, precond_gnorm_np, 2e-5)
```
with this the test is passing.

Is it ok to create a PR with this change? Could you please share your thoughts on this.

### Source code / logs
```
.......................F..................................................................................
======================================================================
FAIL: test_stable_global_norm_unchanged (__main__.CombineAdversarialLossTest)
Test that preconditioning doesn't change global norm value.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/.cache/bazel/_bazel_test/774d974934abfb88e6e5d6a13042805c/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/gan/losses_impl_test.runfiles/org_tensorflow/tensorflow/contrib/gan/python/losses/python/losses_impl_test.py", line 602, in test_stable_global_norm_unchanged
    self.assertNear(gnorm_np, precond_gnorm_np, 1e-5)
  File "/home/test/.cache/bazel/_bazel_test/774d974934abfb88e6e5d6a13042805c/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/gan/losses_impl_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 879, in assertNear
    if msg is not None else ""))
AssertionError: 110.709068 != 110.709084 +/- 0.000010

----------------------------------------------------------------------
Ran 106 tests in 9.119s

FAILED (failures=1)
```

**Comment by poxvoculi** [comment]
@yifeif: any reason loosening this bound would not be acceptable?

**Comment by yifeif** [comment]
redirect to @joel-shor who owns tf.contrib.gan. Joel do you mind taking a look? Thanks!
