### ISSUE TITLE
Benchmarking GPU ops in Tensorflow Graphs

### ISSUE THREAD

**Issue by tvkpz** [tensorflow/tensorflow#16244]
I tried using the tool for benchmarking Tensorflow Graphs at
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/benchmark

Seems it only gives the memory profile for RAM per ops. How can I get the GPU memory and utilization profile per ops using this tool?

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
