### ISSUE TITLE
graph_metrics.py does not work well

### ISSUE THREAD

**Issue by FightForCS** [tensorflow/tensorflow#16240]
I want to use function in graph_metrics.py, I run corresponding test file graph_metrics_test.py, but I get the following assertion error for "weight_parameters" metric
```

line 32, in testGraphMetrics
    self.assertEqual(expected[statistic_type], current_stats.value)
AssertionError: 100 != None
```
has anyone encounter this problem?

**Comment by poxvoculi** [comment]
The only "graph_metrics_test.py" I see is here

https://github.com/petewarden/tensorflow_makefile/blob/master/tensorflow/python/tools/graph_metrics_test.py

which is not part of officially supported TensorFlow.  It also appears to be old.

**Comment by FightForCS** [comment]
That is right! I find another way to solve my problem! Thanks anyway, I will close this issue
