### ISSUE TITLE
[doc][feature request] Graphical representation of operations

### ISSUE THREAD

**Issue by Hoeze** [tensorflow/tensorflow#16247]
It would be cool if the documentation of TF operations would contain graphical examples.

E.g. the "tf.dynamic_partition" operation contains such a visualization:
![image](https://user-images.githubusercontent.com/1200058/35163918-880ec02e-fd48-11e7-944f-7d3aac7cadc5.png)

This would be especially helpful to understand the different slicing/joining operations.

**Comment by aselle** [comment]
I agree this would be really cool. Often it is hard to do for higher dimensional tensors. @wolffg, has anyone looked intothis?  It would be especially useful for things like conv as well (though there are sources of those).

**Comment by wolffg** [comment]
We are always on the hunt for contributions to the API docs!  If you have images you want to contribute, make a PR with the images, and we'll pull them into our image hosting system.

Agreed that many of these ops (such as space-to-depth and depth-to-space) could use more visuals, plus probably more code.  Restating it so the task has bounds, we'd say that all the ops in this section should have images:

https://www.tensorflow.org/api_guides/python/array_ops#Slicing_and_Joining

which is ~30 ops that don't have images.  I don't think I can close this with a quick change, so I'm setting this to "contributions welcome" and we'll track this suggestion internally as part of our ongoing API docs work.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.
