### ISSUE TITLE
Failed to build error: mismatched argument pack lenghts...

### ISSUE THREAD

**Issue by pfc** [tensorflow/tensorflow#16246]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 4.14.13-1-ARCH
- **TensorFlow installed from (source or binary)**: git
- **Python version**: 3.6.4
- **Bazel version (if compiling from source)**: 0.9.0-1
- **GCC/Compiler version (if compiling from source)**: 6.4.1
- **CUDA/cuDNN version**:  9.1.85-1 / 7.0.5-2
- **Exact command to reproduce**:
./configure
bazel build --config=opt --config=cuda --jobs 12 //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
failed to build

### Source code / logs

> /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/tuple:489:65: error: mismatched argument pack lengths while expanding 'std::is_convertible<_UElements&&, _Elements>'
>        return __and_<is_convertible<_UElements&&, _Elements>...>::value;
>                                                                  ^~~~~
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/tuple:490:1: error: body of constexpr function 'static constexpr bool std::_TC<<anonymous>, _Elements>::_ImplicitlyMoveConvertibleTuple() [with _UElements = {const std::tuple<tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece>}; bool <anonymous> = true; _Elements = {tensorflow::VariantBinaryOp, tensorflow::StringPiece, tensorflow::StringPiece}]' not a return-statement
>      }
>  ^
> ERROR: /home/user/dev/git/tensorflow/tensorflow/core/kernels/BUILD:1884:1: output 'tensorflow/core/kernels/_objs/list_kernels_gpu/tensorflow/core/kernels/list_kernels.cu.pic.o' was not created
> ERROR: /home/user/dev/git/tensorflow/tensorflow/core/kernels/BUILD:1884:1: not all outputs were created or valid
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 29.727s, Critical Path: 28.35s
> FAILED: Build did NOT complete successfully
>

**Comment by mortont** [comment]
Seeing the same failure with exactly the same system parameters. Attempted to roll back to commit d75c3474f93b87ccbfeb910550b5dcdb8913681b but still fails.

**Comment by naetherm** [comment]
Same behaviour with same system parameters.

**Comment by naetherm** [comment]
The same error was mentioned in #10220 .

**Comment by pfc** [comment]
nvidia will fix the gcc header bug but fix won't be available till next CUDA release, whenever that might be.
https://devtalk.nvidia.com/default/topic/1028112/cuda-setup-and-installation/nvcc-bug-related-to-gcc-6-lt-tuple-gt-header-/post/5234434/#5234434
Still need to find a workaround on arch.  Somehow downgrading gcc-6 might work but can't figure out what version to use.

**Comment by Celelibi** [comment]
As far as I could test, it doesn't compile with gcc 6.4.0. However, it compiles with gcc 6.3.0 (more specifically, the debian version 6.3.0-18).

**Comment by pfc** [comment]
I have just managed to compile tensorflow using gcc 6.4.1 with CUDA/CUDnn support (first said it couldn't find CUDnn but kept defaults a second time and then it found it) on Arch.
I guess someone has been fixing things?  I'll close for now as the original issue seems to be fixed.

NVIDIA: 387.34-21
CUDA: 9.1.85-1
CUDnn: 7.0.5-2
gcc6: 6.4.1-5

**Comment by drpngx** [comment]
Thanks @pfc!

Would you be able to provide a fix?

CC @gunan

**Comment by pfc** [comment]
I have not made any code changes to get it to compile.  I did update gcc from 6.4.1-4 to 6.4.1-5 and pulled latest code from repo.  One or a combination of theses must have fixed the problem.
