### ISSUE TITLE
tf.scatter_update Error 

### ISSUE THREAD

**Issue by oroojlooy** [tensorflow/tensorflow#16255]
Hi, 

I use tf.scatter_update to update non-trainable variables AS and AO in a code. As I found, when one uses scatter_update, the gradient misses, so that there is no gradient. 
Because of that I set both AL and AO as non-trainable variables (actually they are non-trainable), called the optimizer: tf.train.AdamOptimizer(config.actor_lr0,0.9,0.999,1e-8).minimize(actor_loss), and I thought everything should be fine. 
However, I am getting error:
LookupError: No gradient defined for operation 'actor/encoder/beer_game_flow_8/next_scat_j_2' (op type: ScatterUpdate). 
Here are the lines of the code that I update AO and AS that gives the error:

self.players[k-1].AS = tf.scatter_update(self.players[k-1].AS, 
                    self.curTime + leadTimeIn, 
                    tf.add(self.players[k-1].AS[self.curTime + leadTimeIn], possible_shipment), name='next_scat_j' )                   

self.players[k+1].AO = tf.scatter_update(self.players[k+1].AO, 
                    self.curTime + leadTime, tf.add(self.players[k+1].AO[self.curTime + leadTime], 
                    self.players[k].actionValue(self.curTime, self.playType))
                    , name='handle_scat_j')

Since both AS and AO are non-trainable, I do not need their gradient, and AS and AO are the only variable in this op. So, I was wondering why TensorFlow want to obtain the gradient, since there is no trainable variable here? 
Is it something that you can fix it, or is there any reason behind this behavior? 

BTW, I use python 2.7 with tf 1.4.0 on Debian 8.7 with a K80 with 12GB of memory. 

Thanks, 
Afshin

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by oroojlooy** [comment]
Hi, 
As I mentioned in my question, I use python 2.7 with tf 1.4.0 on Debian 8.7 with a K80 with 12GB of memory. I am using CUDA 8 and cuDNN 6. I installed it through pip and did not install bazel. 
The whole code is more than 1000 lines and it is not on a public git yet. 
If you could not check the error, I'll try to implement a small code to reproduce the error. 
Please let me know. 
Afshin

**Comment by tatatodd** [comment]
The error is telling you that ScatterUpdate does not have a gradient defined.  The rationale behind this is discussed in #2770

Closing this out.  As discussed in #2770, follow-ups should go to stackoverflow.  Thanks!
