### ISSUE TITLE
ImportError: cannot import name tf

### ISSUE THREAD

**Issue by rtamizh** [tensorflow/tensorflow#16265]
### System information
- **Os version**: Linux Ubuntu 14.04
- **TensorFlow installed from**: binary (sudo pip  install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.4.1-cp27-none-linux_x86_64.whl
)
- **TensorFlow version** :1.4.1
- **Python version**: 2.7

### Describe the problem
After Install when i run the following command it throws error;
`from tensorflow import tf`

It throws
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name tf
`

**Comment by ushnish** [comment]
I think you meant `import tensorflow as tf`
