### ISSUE TITLE
No module named tensorflow.python.platform

### ISSUE THREAD

**Issue by abratchik** [tensorflow/tensorflow#16264]
### System information
**OS**
Linux 4.4.0-109-generic 132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.3 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial
**Tensorflow**
Installed from source (git clone from this repository):
tf.VERSION = 1.5.0-rc1
tf.GIT_VERSION = v1.5.0-rc1-1379-g20f6af3
tf.COMPILER_VERSION = v1.5.0-rc1-1379-g20f6af3
Sanity check: array([1], dtype=int32)
**Python version**
Python 2.7.12
**Bazel version **
Build label: 0.9.0
**GCC/Compiler version**
gcc (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904
nvcc Cuda compilation tools, release 9.1, V9.1.85
**CUDA/cuDNN version**
CUDA Version 9.1.85
cuDNN Version 7.0.5
**GPU model and memory**
GeForce 1080 Ti 11Gb
Driver Version: 387.26 
**Exact command to reproduce**

1. git clone https://github.com/tensorflow/tensorflow 
2. ./configure

```
WARNING: Running Bazel server needs to be killed, because the startup options are different.
You have bazel 0.9.0 installed.
Please specify the location of python. [Default is /usr/bin/python]: 


Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]
/usr/lib/python2.7/dist-packages
Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: n
No jemalloc as malloc support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Google Cloud Platform support? [Y/n]: n
No Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [Y/n]: 
Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Amazon S3 File System support? [Y/n]: n
No Amazon S3 File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]: 
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with GDR support? [y/N]: 
No GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: 
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 9.0]: 9.1


Please specify the location where CUDA 9.1 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7.0]: 7.0.5


Please specify the location where cuDNN 7.0.5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:


Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 6.1]


Do you want to use clang as CUDA compiler? [y/N]: 
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 


Do you wish to build TensorFlow with MPI support? [y/N]: 
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: 
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
Configuration finished
```

3. bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --action_env="LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"

```

Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 1505.551s, Critical Path: 92.22s
INFO: Build completed successfully, 6091 total actions 
```

4. bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

`Sun Jan 21 09:39:44 +04 2018 : === Output wheel file is in: /tmp/tensorflow_pkg`

5. sudo pip install /tmp/tensorflow_pkg/tensorflow-1.5.0rc1-cp27-cp27mu-linux_x86_64.whl

```
Installing collected packages: tensorflow-tensorboard, tensorflow
Successfully installed tensorflow-1.5.0rc1 tensorflow-tensorboard-0.4.0
```
6.  start python & post 'import tensorflow as tf' command

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
ImportError: No module named platform
```

**Comment by abratchik** [comment]
I also found very old issue #374, which is closed now and the advice there was to define PYTHONPATH. in my case PYTHONPATH is defined and pointing to /usr/lib/python2.7/dist-packages.

the folder tensorflow/python/platform is also present in the root tensorflow folder but somehow it doesn't get packaged in the target wheel.

**Comment by wentian1hao** [comment]
I meet the same problem on mac, I find in the anaconda/python2.7/site-packages/tensorflow/python has the platform directory, but it seem it can find it, may be some path is not set correctly. Do you solve this bug? If so, can you help me? thanks!

**Comment by abratchik** [comment]
It is simple - just change the folder from the one where you run the configure/bazel and then try python import tensorflow as tf


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: wentian1hao <notifications@github.com> Date: 1/23/18  18:00  (GMT+04:00) To: tensorflow/tensorflow <tensorflow@noreply.github.com> Cc: Jcrist99 <abratchik@snap2cart.com>, State change <state_change@noreply.github.com> Subject: Re: [tensorflow/tensorflow] No module named tensorflow.python.platform (#16264) 
I meet the same problem on mac, I find in the anaconda/python2.7/site-packages/tensorflow/python has the platform directory, but it seem it can find it, may be some path is not set correctly. Do you solve this bug? If so, can you help me? thanks!

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tensorflow/tensorflow","title":"tensorflow/tensorflow","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tensorflow/tensorflow"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wentian1hao in #16264: I meet the same problem on mac, I find in the anaconda/python2.7/site-packages/tensorflow/python has the platform directory, but it seem it can find it, may be some path is not set correctly. Do you solve this bug? If so, can you help me? thanks!"}],"action":{"name":"View Issue","url":"https://github.com/tensorflow/tensorflow/issues/16264#issuecomment-359798263"}}}
-- 

------------------------------
The information transmitted herein is intended only for the person or 
entity to which it is addressed and may contain confidential, proprietary 
and/or privileged material. Any review, retransmission, dissemination or 
other use of, or taking of any action in reliance upon, this information by 
persons or entities other than the intended recipient is prohibited. If you 
received this in error, please contact the sender and delete the material 
from any computer.

**Comment by wentian1hao** [comment]
Thanks a lot! But I want to know why it does not work in the other directory? What's the point?

**Comment by abratchik** [comment]
no idea mate ) Basically it looks like you can use the tensorflow from any directlry except the one where you run the build scripts.

**Comment by wentian1hao** [comment]
OK，Thanks anyway！

**Comment by changwuxie** [comment]
@abratchik you are right

**Comment by Mubashshira** [comment]
I am trying from folder in which i used ./configure but same error
