### ISSUE TITLE
Cannot opened include file "tensorflow/contrib/tpu/proto/tpu_embedding_config.pb.h": no such file or directory

### ISSUE THREAD

**Issue by jackyko1991** [tensorflow/tensorflow#16262]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: source 
- **TensorFlow version (use command below)**: current git master branch, should be v1.4.1 or v1.5.0rc1?
- **Python version**: N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: MSVC2015
- **CUDA/cuDNN version**: CPU build only, gpu function is off
- **GPU model and memory**: N/A
- **Exact command to reproduce**: Trying a minimal build with cmake, with only snappy support and optimize for native arch turned on

### Describe the problem
Build failing due to missing header files "tensorflow/contrib/tpu/proto/tpu_embedding_config.pb.h".

Everything build succesful except for tpu project. I don't really know how to generate the pb.h file from protoc manually. I trying to fix the problem by chaning .cmake files, but not sure which one is for tpu.

### Source code / logs
133>D:\MSVC-source\tensorflow\tensorflow\contrib\tpu\ops\tpu_embedding_ops.cc(16): fatal error C1083: Cannot open include file: 'tensorflow/contrib/tpu/proto/tpu_embedding_config.pb.h': No such file or directory

**Comment by poxvoculi** [comment]
That file seems to be only 10 days old.  You can get it here
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/tpu/proto/tpu_embedding_config.proto
but maybe you've got an inconsistent or incomplete view of the master repository.

**Comment by omatai** [comment]
Yesterday I downloaded Tensorflow without a hitch as per the single line "pip install --upgrade tensorflow" instructions. Now I'm getting the exact same error.... and the distribution already includes that file you mention. The problem is: how is the ".h" file generated from this ".proto" file... if indeed that is what happens? Given that neither me nor the OP want any TPU support, how can we switch this off in the build? (my build has 240 successful projects, 2 failed projects, and the failures start with this error, then continue with roughly 570 LNK2005 errors from redefined functions)

**Comment by jackyko1991** [comment]
I get this file in my local git repository, the problem is that protoc does not generate the correct header file (pb.h) from the .proto file

**Comment by poxvoculi** [comment]
Thanks for the fix!

**Comment by Anguliachao** [comment]
@jackyko1991 hi, how did you find this pb.h file, in what directory of the local repository? could you please help me out? I face this problem as well

**Comment by jackyko1991** [comment]
The pb.h file is generated by protoc using the .cmake file. The issue is
fixed in recent update

2018年1月24日 17:12 於 "Anguliachao" <notifications@github.com> 寫道：

**Comment by aimhabo** [comment]
@jackyko1991 how did you fix it?
I generate files like "protoc --cpp_out=./ tensorflow/core/protobuf/*.proto"
after that I got lots of error like image shows.
how should I do?
![2018-07-03 13-34-24](https://user-images.githubusercontent.com/12708080/42200462-ee7205a2-7ec5-11e8-9ae6-f77cbca15e7d.png)
