### ISSUE TITLE
Linking against system-installed cuda and cudnn

### ISSUE THREAD

**Issue by Celelibi** [tensorflow/tensorflow#16276]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian sid
- **TensorFlow installed from (source or binary)**: source (trying)
- **TensorFlow version (use command below)**: git master (commit 9fb9ac66ce) or any version before.
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.9.0
- **GCC/Compiler version (if compiling from source)**: 7.2.0
- **CUDA/cuDNN version**: CUDA 9.0, cuDNN 6.0
- **GPU model and memory**: GeForce GTX 1070
- **Exact command to reproduce**:
`bazel build --config=opt --config=mkl --config=cuda //tensorflow/tools/pip_package:build_pip_package`

### Describe the problem
The build system currently require that all the libraries from the CUDA toolkit are stored in a specific directory called `cuda_toolkit_path`, both in the bazel scripts and in the `configure.py` script. However, some systems (like Debian) have a packaged version of CUDA which installs the libraries in the standard path which cannot be found by `configure.py`.

The compiler can find those libraries just right with nothing more than `-lcuda`. It would be nice if the build system could rely on the compiler's ability to find its libraries instead of relying on the knowledge of their full path.

### Source code / logs
As a feature-request / enhancement-request, this section seems irrelevant.

**Comment by drpngx** [comment]
/CC @gunan I think that'd be a great contribution if you're willing to send something.

**Comment by Celelibi** [comment]
For what it's worth, I have patched (hacked) the build scripts and a few lines of code to make it compile and link on my computer. Using the system-installed CUDA / cuDNN, of course.
https://github.com/Celelibi/tensorflow/tree/wip-system-cuda
(current latest commit Celelibi/tensorflow@c87884ddfbd419ff6663b9aef160fd45577280e0)

If you're interested, I can continue to work on it and make a pull request with a cleaner version. Or it might serve as a basis for a seasoned tensorflow developer to make the necessary modifications that follows tensorflow's guidelines much more quickly than I would.

**Comment by drpngx** [comment]
That looks reasonable. Feel free to send the PR!

**Comment by mohantym** [comment]
Hi @Celelibi ! In the current build from the source process , It asks locations of Cuda files while running the configure.py script for gpu support .Attached relevant [thread](https://www.tensorflow.org/install/source) for reference. Could we move this to closed status now. Thank you!
