### ISSUE TITLE
[bug?] Tensorflow accepts CUDA_VISIBLE_DEVICES but still allocates memory on multiple GPUs

### ISSUE THREAD

**Issue by e-ka** [tensorflow/tensorflow#16284]
### System information
- **I have written a custom script, but effect is also visible for just `import tensorflow as tf; sess = tf.Session()`**:
- **Windows 7 Professional**:
- **TensorFlow installed from binary (pip, in Anaconda environment)**:
- **TensorFlow version 1.4.0**:
- **Python version 3.5.4**: 
- **CUDA/cuDNN version 8.0/6.0**:
- **4 GeForce GTX 1080Ti, 11GB**:

### Problem description
I am facing the following issue:

If I set
`CUDA_VISIBLE_DEVICES=1`
and start my python script, everything works as expected, only GPU 1 is used/only memory from GPU 1 is allocated. GPU1 hosts the Desktop Window Manager.

If I set
`CUDA_VISIBLE_DEVICES=0 # or 2 or 3 `
before running my python script
`sess = tf.Session()`
faithfully reports only one available GPU (with the expected PCI bus id), see attached file ipython.txt.

However, nvidia_smi.exe shows that memory on all remaining GPUs except for GPU1 is allocated. GPU-Util shows that expected GPU is used for actual computation, see attached file nvidia_smi_output.txt.

I see this effect both for my actual tensorflow script as well for simple interactive python with

```
import tensorflow as tf
sess = tf.Session()
```

Unfortunately, the dual boot Ubuntu is not working at the moment, but once it is running again, I can try to check whether a similar effect presents itself there.
Could this be a bug, possibly related to Windows? Or a driver or hardware issue?

Attached files:
[ipython.txt](https://github.com/tensorflow/tensorflow/files/1651908/ipython.txt): ipython script and output.
[nvidia_smi_output.txt](https://github.com/tensorflow/tensorflow/files/1651905/nvidia_smi_output.txt): output of nvidia-smi.exe

**Comment by kbxu** [comment]
Are you using it exactly as 
`CUDA_VISIBLE_DEVICES=1 python oo.py`

**Comment by drpngx** [comment]
Maybe it's a windows thing? I'm not sure if Windows honors this flag. Could you try with more logging on?

CC @mrry @guschmue

**Comment by e-ka** [comment]
May very well be a Windows thing... 
With `tf.logging.set_verbosity` set to INFO or DEBUG, tensorflow does not print additional output for just `sess = tf.Session()`.

It seems to have some effect as it seems to differenciate between graphic card 1 and graphic cards [0, 2, 3]. If I do not set CUDA_VISIBLE_DEVICES at all, it allocates memory on all four cards.

**Comment by guschmue** [comment]
Just tried on tf-1.4/cuda8/windows10 and it is working as expected. 
But yes, the logs from @e-ka  show that the tensorflow process (pid 8040) has the device 0,2,3 open where it should have only seen 1 device. Kind of odd since tensorflow is reporting only 1 device.
The driver on my box is a little older 388.19 (vrs 390.65) and I have windows10 instead of windows7.
I can update my box to the latest driver to rule that out.

**Comment by e-ka** [comment]
Thanks for testing! 
I don't think it's necessarily the driver version by itself. IIRC, I updated the driver & tensorflow version along the way to test whether this already fixes it, but to no avail.

**Comment by drpngx** [comment]
Thank you @guschmue for testing!

@e-ka I think it's `TF_CPP_MIN_LOG_LEVEL`?

**Comment by e-ka** [comment]
@drpngx sorry for the late response, I did not have access to the machine for the last week. Setting the verbosity via the environment variable TF_CPP_MIN_LOG_LEVEL should generally do the same as tf.logging in python, should it not? I also do not see a difference in the output...

**Comment by drpngx** [comment]
`C++` logging and pthon logging are different. If you set it correctly, you should definitely see a lot more output.

**Comment by ed-alertedh** [comment]
Somewhat related to this: TF 1.4, Python 3.6.3 x64, Windows 10, CUDA 8, cuDNN 6, NVIDIA driver 385.69

I was trying to set CUDA_VISIBLE_DEVICES="" (as per #9201) to stop the GPU being grabbed at all and it goes ahead and open the device anyway. I only have one GPU on this laptop so I can't test what the behaviour is for multiple devices (the other machines I have access to are all running linux).

    >>> import os
    >>> os.environ["CUDA_VISIBLE_DEVICES"] = ''
    >>> import tensorflow as tf
    >>> sess=tf.Session()
    2018-02-12 16:22:11.752327: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
    2018-02-12 16:22:12.120254: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties:
    name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
    pciBusID: 0000:01:00.0
    totalMemory: 6.00GiB freeMemory: 4.96GiB
    2018-02-12 16:22:12.120473: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)

Confirmation that it is grabbing the GPU memory:

    >nvidia-smi
    Mon Feb 12 16:23:12 2018
    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 385.69                 Driver Version: 385.69                    |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |===============================+======================+======================|
    |   0  GeForce GTX 1060   WDDM  | 00000000:01:00.0  On |                  N/A |
    | N/A   57C    P2    27W /  N/A |   5763MiB /  6144MiB |      0%      Default |
    +-------------------------------+----------------------+----------------------+

Workaround for now is to set CUDA_VISIBLE_DEVICES="-1" which generates a seemingly benign error message as a side effect:

    2018-02-12 16:09:01.981599: E C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\cuda\cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE

**Comment by harshini-gadige** [comment]
I see TF version 1.4 was used when this issue was created. This may not exist with the latest version of Tensorflow. Please create a new issue if it still persists by giving all the information asked as per this template. Thanks !

**Comment by jameswan** [comment]
I have 2 X 1080Ti GPUs.
Each of the GPUs has 7.4GB or 8.2 GB out of the 11 GB being used when performing inferencing
Is this correct functioning of the code?

**Comment by policeme** [comment]
@e-ka Do you solve this problem? I have same too.

**Comment by yxlwfds** [comment]
> 我有 2 个 1080Ti GPU。每个 GPU 都有 7.4GB 或 8.2 GB，其中 11 GB 在执行推理时使用 这是代码的正确运行吗？

我在两个,只能用一个,也就是说当一个满时,另一个也无法启动.不知道有没有什么双gpu的最佳实践.
