### ISSUE TITLE
Saver restoring multiple sessions throws errors

### ISSUE THREAD

**Issue by kmitchner** [tensorflow/tensorflow#1628]
### Environment info
Operating System: Linux

### Steps to reproduce
1. Save two sessions independently from each other
2. Run a Saver.restore on the first session
3. Run a Saver.restore on the second session

### Logs or other output that would be helpful
W tensorflow/core/common_runtime/executor.cc:1161] 0x3437b20 Compute status: Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [6453,128] rhs shape= [1853,128]
	 [[Node: save/Assign_21 = Assign[T=DT_FLOAT, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding/W/Adam, save/restore_slice_21)]]
W tensorflow/core/common_runtime/executor.cc:1161] 0x3437b20 Compute status: Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [6453,128] rhs shape= [1853,128]
	 [[Node: save/Assign_22 = Assign[T=DT_FLOAT, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding/W/Adam_1, save/restore_slice_22)]]
W tensorflow/core/common_runtime/executor.cc:1161] 0x3437b20 Compute status: Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [6453,128] rhs shape= [1853,128]
	 [[Node: save/Assign_20 = Assign[T=DT_FLOAT, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding/W, save/restore_slice_20)]]

**Comment by sherrym** [comment]
How did you ensure that "Save two sessions independently from each other"?

Sherry

**Comment by kmitchner** [comment]
These are all managed through a class, I have separate training scripts that train models and save them into their own folders. I then had a classify script that I passed a file to, it instantiated 5 of the below classes attempting to load each of the sessions from their respective folders.  It throws the error above on all sessions but the first.  I tried changing the order of the sessions being loaded so it's definitely something being "shared" between the first and subsequent sessions.

Code below is truncated

```
imports...

class TextModel(object):

   def __init__(self, path, disable_gpu=False):
        self.path = path.rstrip('/')
        ...

    ...

    def save_session(self, folder, step=None):
        with self.graph.as_default():
            with self.session.as_default():
                try:
                    self.saver
                except:
                    self.saver = tf.train.Saver()

                if not os.path.exists(folder):
                    os.makedirs(folder)
                self.saver.save(self.session, folder+"/session", global_step=step)

  def save_model(self):
        with self.graph.as_default():
            with self.session.as_default():
                self.save_session(self.path)
                with open(self.path+"/saver_def.pkl", "wb") as f:
                    pickle.dump(self.saver.as_saver_def(),f)
                var_names = [v.name for v in tf.all_variables()]
                with open(self.path+"/var_names.json", "wb") as f:
                    json.dump(var_names, f)
                try:
                    os.rename(self.path+"/graph",self.path+"/graph_"+str(time.time()))
                    print("Existing graph folder renamed to "+self.path+"/graph"+time.time()+"\n", file=sys.stderr)
                except:
                    pass
                try:
                    tf.train.write_graph(self.session.graph_def, self.path+"/graph", "graph", as_text=False)
                except:
                    print("Graph folder not created\n", file=sys.stderr)

def load_model(self):
            with open(self.path+"/var_names.json", "r") as f:
                var_names = json.load(f)
            with open(self.path+"/saver_def.pkl", "r") as f:
                saver_def = pickle.load(f)
                self.session = tf.Session(config=self.tf_config)
                self.graph = self.session.graph
                with self.graph.as_default():
                    with open(self.path+"/graph/graph", 'rb') as f:
                        graph_def = tf.GraphDef.FromString(f.read())
                        self.graph_variables = tf.import_graph_def(graph_def, return_elements=var_names, name="")

                    self.saver = tf.train.Saver(saver_def=saver_def)
                    self.saver.restore(self.session, self.path+"/session")
                    with self.session.as_default():
                        tf.initialize_all_variables()
                        self.model_loaded = True
```

**Comment by kmitchner** [comment]
To add, "W" is a tensorflow variable I use, it's complaining about the shapes so I'd wager that the W variable is getting mixed up between the first graph_def or session and a subsequent one.

**Comment by sherrym** [comment]
When restoring, could you please create a new graph for each of your sessions instead of sharing the same one? Something like this:

self.graph = tf.Graph()  # Creates a new graph.
tf.Session(graph=self.graph, config=self.tf_config)


Sherry

**Comment by kmitchner** [comment]
Sorry for the long response time, what you suggested solved my issue, I didn't think using session.graph on different sessions was "sharing the same one" still not sure why this is the case but passing in empty graphs let me load multiple sessions via the saver
