### ISSUE TITLE
Adding go_package to proto definition files necessary for Tensorflow serving

### ISSUE THREAD

**Issue by orian** [tensorflow/tensorflow#16282]
I've went through guidelines about calling Tensorflow serving in Python.
Then I've decided to make it Go.

You can find my repo here:
https://github.com/datainq/go-mnist-client

Manually preparing files is unmaintainable. What about we add `go_package` to proto files?
e.g. for a `github.com/tensorflow/tensorflow/tensorflow/core/protobuf/saver.proto` it would be:
```
go_package = "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf";
```
I think keeping the generated files in go' subpath is a good idea.

Does it make sense? 
(@jhseu was the author of the initial Go code)

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: N/A
- **Python version**:  N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment]
Adding the `go_package` to protobuf files seems reasonable.
Marking as Contributions Welcome, we'd welcome a PR.

**Comment by yongtang** [comment]
Added a PR #17262 for the fix.
