### ISSUE TITLE
Tensorflow works in command prompt but not in Spyder

### ISSUE THREAD

**Issue by kubesji1** [tensorflow/tensorflow#16288]
Hello.
I'm new to Python so maybe I've missed something but anyway, here is my problem.
I've installed tensorflow in Anaconda prompt by using 
```
C:\WINDOWS\system32> conda create -n tensorflow python=3.6
C:\WINDOWS\system32> activate tensorflow
(tensorflow)C:\WINDOWS\system32> pip install --ignore-installed --upgrade tensorflow
```
Instalation was succesful, then I opened python and tried to import tensorflow to verify installation
```
(base) C:\WINDOWS\system32>python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
```

After activating tensorflow, it works.
```
(tensorflow) C:\WINDOWS\system32>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>>
```
But I cannot find a way to make it work in Spyder IDE. I always get error:
```ModuleNotFoundError: No module named 'tensorflow'```

**Comment by notsmartenough** [comment]
When I try `conda create -n tensorflow-gpu python=3.5.4`
it throws the error 'CondaValueError: prefix already exists: C:\Anaconda3\envs\tensorflow-gpu'
After, `activate tensorflow-gpu` , this ipython or spyder fails to import tensorflow while console does it similar to OP's issue. Any idea why? (decided to add this as an issue https://github.com/tensorflow/tensorflow/issues/16379)

**Comment by tatianashp** [comment]
@kubesji1 Did @quaeler advice help you?

**Comment by kubesji1** [comment]
Sorry, I thought I've responded but I don't see my answer here. Yes, it helped.

**Comment by tatianashp** [comment]
Great. I am closing the issue then.

**Comment by WalkerGoXQ** [comment]
activate tensorflow
conda install spyder
**activate tensorflow enviroment first and then start spyder each time.**

good luck, Walker

**Comment by vineeshvs** [comment]
In general, how do we ensure that a program which works in terminal also works in Spyder (say through os.system("terminal command")?
I am getting license enviroment error for some proprietary tools when I run in Spyder. It is not able to find the lincense. It works well in regular terminal.
