### ISSUE TITLE
Bug in session initialization?

### ISSUE THREAD

**Issue by Hoeze** [tensorflow/tensorflow#16290]
Initializing a variable depending on a placeholder does not work:

```python
import tensorflow as tf
import numpy as np

x = np.random.normal(loc=5, size=[10, 25])

sample_data = tf.placeholder(tf.float32)

mu = tf.Variable(tf.reduce_mean(sample_data, axis=0),
                 dtype=tf.float32,
                 validate_shape=False,
                 name="mu")

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer(), feed_dict={sample_data: x})
    print(sess.run(mu))

########################################### REPEAT:

x = np.random.normal(loc=5, size=[10, 25])

sample_data = tf.placeholder(tf.float32)

mu = tf.Variable(tf.reduce_mean(sample_data, axis=0),
                 dtype=tf.float32,
                 validate_shape=False,
                 name="mu")

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer(), feed_dict={sample_data: x})
    print(sess.run(mu))
```

### Error Message:
> tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float
> 	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

The interesting part about this is that the first initialization works, but the second one does not.
This is really annoying if you don't know that behaviour and you try to build some application with interactive python shells.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 17.10
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
v1.4.0-19-ga52c8d9 1.4.1
- **Python version**: 
3.6.3

**Comment by yaox12** [comment]
You should feed a placeholder when use it, not when initialize a session.
So the code should be
>  sess.run(tf.global_variables_initializer())
    print(sess.run(mu, feed_dict={sample_data: x}))

**Comment by Hoeze** [comment]
This will not work, if some variable (`mu` in this case) should be initialized depending on a placeholder.

I'd like to train `mu` further after initializing, so I either have to get `tf.reduce_mean` produce an optimizable variable or I have to create a new `tf.variable` and initialize it with `tf.reduce_mean` like in this example.

**Comment by Hoeze** [comment]
I just found out, that resetting the graph solves the problem of repeated call:
```
########################################### REPEAT:
tf.reset_default_graph()
...
```
However, this requires to re-build the whole graph.
Is there a better solution?

**Comment by netheril96** [comment]
It is not a bug. Most functions in tf including `placeholder` and `variable` mutates the current default graph by adding new operations to it. When you create `mu` for the second time, the first `mu` is still there, waiting to be initialized by the first `x`. That is why you encounter the error, for you do not feed the old `x`.

**Comment by Hoeze** [comment]
OK, thank you for clarifying.
Closing this now
