### ISSUE TITLE
ScipyOptimizer SLSQP supporting callback

### ISSUE THREAD

**Issue by mjwen** [tensorflow/tensorflow#16294]
The callback is deprecated when `SLSQP` method in scipy optimizer is selected (see [here](https://github.com/tensorflow/tensorflow/blob/04b5c75aae4bdbdac7c713714a369f9b360daf70/tensorflow/contrib/opt/python/training/external_optimizer.py#L400)). Actually, `SLSQP` does support callback, so 
```python 
if method == 'SLSQP':
  # SLSQP doesn't support step callbacks. Obviate associated warning
  # message.
  del minimize_kwargs['callback']
```
in the above linked file could be removed. 

The following example shows that `SLSQP` do support callback. 

```python 
from scipy.optimize import minimize, rosen, rosen_der

def callback(xk, step=[0]):
  print step[0], xk[0]
  step[0] += 1
  
x0 = [1.3, 0.7, 0.8, 1.9, 1.2]
res = minimize(rosen, x0, callback=callback, method='SLSQP',
    options={'ftol': 1e-6, 'disp': True})
 
print res.x[0]
```

**Comment by tatianashp** [comment]
@mjwen - thank you for reporting this issue.  Would you be interested in submitting a pull request that implements the change that you suggest?

**Comment by mjwen** [comment]
@tatianashp Sure. The pull request has been submitted at [#16312](https://github.com/tensorflow/tensorflow/pull/16312).

**Comment by tatianashp** [comment]
Great! 

Thank you.

**Comment by axil** [comment]
The documentation still says
"All methods except TNC, SLSQP, and COBYLA support a callable with the signature:"
