### ISSUE TITLE
Lack of clarity in tf.while_loop documentation

### ISSUE THREAD

**Issue by mholzel** [tensorflow/tensorflow#16316]
I believe that the documentation for tf.while_loop is lacking usage clarity, and actually provides contradictory statements. 

Specifically, it seems that many people are using the tf.while_loop as a "for loop" ([see stackoverflow](https://stackoverflow.com/questions/35330117/how-can-i-run-a-loop-with-a-tensor-as-its-range-in-tensorflow)). However, the [tf.while_loop](https://www.tensorflow.org/versions/r0.12/api_docs/python/control_flow_ops/control_flow_operations#while_loop) docs state:

> For correct programs, while_loop should return the same result for any parallel_iterations > 0.

A loop counter inside of the "while loop" body, seems to violate this constraint despite the fact that this is given as an example usage in the docs:

> python i = tf.constant(0) c = lambda i: tf.less(i, 10) b = lambda i: tf.add(i, 1) r = tf.while_loop(c, b, [i])

So it seems that there are two bad outcomes here:

1. If this is indeed the canonical way of creating a "for loop", then the example explicitly creates a dependency between iterations, meaning that the "while loop" iterations cannot be run in parallel. 

1. The example is incorrect? 

It seems like the while_loop docs should have an example which better illustrates how to use it as a "for loop", if such usage is indeed intended, or a warning on the implications of the provided example.

**Comment by dongsam** [comment]
test

**Comment by tatianashp** [comment]
Thank you for your report. As far as I can see, the loop that you show above is correct. In Python, parallel execution does not allow more than one thread run at a time. The execution of multiple threads might overlap, however. So, a code with reduction, such as the one shown above works just fine if executed in parallel.

Let me confirm with an expert, though. @michaelisard could you take a quick look?

**Comment by mholzel** [comment]
@tatianashp I found [this comment in issue 1984](https://github.com/tensorflow/tensorflow/issues/1984#issuecomment-211199897) that was incredibly helpful in understanding what is going on.  But even that comment is not complete [as I note here](https://github.com/tensorflow/tensorflow/issues/1984#issuecomment-359713984). It would be nice for somebody to have a look at these comments and incorporate them into the documentation. 

Finally, one more thing that is not explained in the docs is why [this phenomenon occurs (reported in issue 16333)](https://github.com/tensorflow/tensorflow/issues/16333). Specifically, it seems as though the while loop is doing some type of copy semantics instead of referencing the inputs. In my mind, that is not at all the behavior I expect.

**Comment by tatianashp** [comment]
The discussion of this issue has migrated to #16333.
