### ISSUE TITLE
how to set subtensor on Tensor objects

### ISSUE THREAD

**Issue by yaoli** [tensorflow/tensorflow#1632]
As a naive example, in numpy: 
```
x = numpy.zeros((2, 3, 4))
y = numpy.ones((2, 3, 4))
x[1:] = y[:-1]
array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])
```
How to achieve this in tensorflow? I've looked into tf.scatter_update(), but it only works on Variable objects, not on Tensors.

**Comment by girving** [comment]
I'd suggest `tf.pack` or `tf.concat`.  If you want more details, please ask questions like this on stackoverflow; issues are for bugs in tensorflow.
