### ISSUE TITLE
Compilation failure with gcc-6.4 (gcc-7.2 and clang-4) in ubuntu 17.10

### ISSUE THREAD

**Issue by samikama** [tensorflow/tensorflow#16331]
When compiling master in ubuntu 17.10, compilation fails due to 'too perfect forwarding' in variant_op_registry
`
std::unordered_map<std::tuple<VariantXOp, StringPiece, StringPiece>, 
                     VariantXOpFn, TupleHash>
`
A workaround, by replacing tuple with a struct, provided in PR #16309 for your review.

Thanks,
Sami

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by samikama** [comment]
Sorry, I forgot these 
OS Platform and Distribution: 17.10
TensorFlow installed from: N/A
TensorFlow version: master branch a93f40737d3a7
Bazel  0.9.0 & 0.8.0
CUDA/cuDNN: 9.0/7.0
GPU model & memory: compute 7.0
Exact command to reproduce: ./configure && bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

I added these for sake of completeness. PR #16309 merged and fixes the issue. Closing
