### ISSUE TITLE
KeyboardInterrupt make aws g2.2xlarge sys  no response 'cuda_gpu_executor.cc:624] Deallocating stream'

### ISSUE THREAD

**Issue by zdx3578** [tensorflow/tensorflow#1634]
### Environment info
Operating System:
aws 
https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#LaunchInstanceWizard:ami=ami-e191b38b

KeyboardInterrupt
E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:624] Deallocating stream with pending work
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C

If installed from sources, provide the commit hash:

### Steps to reproduce
1.
2.
3.

http://ramhiser.com/2016/01/05/installing-tensorflow-on-an-aws-ec2-instance-with-gpu-support/    
he installed

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by zdx3578** [comment]
/var/log/*   files no info about sys down

**Comment by girving** [comment]
This isn't enough information.  From what you've written so far, maybe you typed ^C to kill a process?

**Comment by aselle** [comment]
Automatically closing because there was no response. Please reopen if it is still an issue.
