### ISSUE TITLE
Change RELEASE.md to specify CUDA version

### ISSUE THREAD

**Issue by Anjum48** [tensorflow/tensorflow#16348]
The RELEASE.md states that "Prebuilt binaries are now built against CUDA 9 and cuDNN 7."

https://github.com/tensorflow/tensorflow/issues/15604 says that CUDA 9.1 is not supported.

Could we change the RELEASE.md so that it says "Prebuilt binaries are now built against CUDA 9.0 and cuDNN 7." until later versions are supported?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Anjum48** [comment]
Have I written custom code: N/A
OS Platform and Distribution: Linux
TensorFlow installed from: pip
TensorFlow version: tensorflow-gpu 1.5.0rc1
Bazel version: N/A
CUDA/cuDNN version: 9.1 & 7
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by tatianashp** [comment]
Thank you for noticing this imprecision in the documentation. Would you like to submit the requested change yourself as a pull request?
