### ISSUE TITLE
Request for updating keras/datasets files to r1.5

### ISSUE THREAD

**Issue by sakaia** [tensorflow/tensorflow#16358]
### System information
- **executes Keras sample code imdb_fasttext.py https://github.com/keras-team/keras/blob/master/examples/imdb_fasttext.py**:
- **Windows 7**:
- **TensorFlow installed from binary**:
- **TensorFlow version 1.5.0rc0**:
- **Python version 3.5.1**: 

### Describe the problem
Keras sample program does not work.
 There is a bug for numpy arange method wrong usage.
   (Need to fix from arrange to arange) 
This issue is already solved on master branch. (not in 1.5.0rc1)
Would you update these source codes?

### Source code / logs
Error messages are follows
===
C:\Users\sakaia\work\tensorflow\keras>python imdb_fasttext.py
Loading data...
Traceback (most recent call last):
  File "imdb_fasttext.py", line 75, in <module>
    (x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features
)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\keras\_imp
l\keras\datasets\imdb.py", line 77, in load_data
    indices = np.arrange(len(x_train))
AttributeError: module 'numpy' has no attribute 'arrange'
===

Following are just checking np.arrange (not np.arange)
>git branch r1.5
>grep -rn np.arrange *
tensorflow/python/keras/_impl/keras/datasets/boston_housing.py:51:  indices = np.arrange(len(x))
tensorflow/python/keras/_impl/keras/datasets/reuters.py:76:  indices = np.arrange(len(xs))
tensorflow/python/keras/_impl/keras/datasets/imdb.py:77:  indices = np.arrange(len(x_train))
tensorflow/python/keras/_impl/keras/datasets/imdb.py:82:  indices = np.arrange(len(x_test))
>git branch -
>grep -rn np.arrange *
(This line is intentionally blank)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sakaia** [comment]
Part of  parameters are already written, I add it

Bazel version                      NOT used (since it is binary)
CUDA/cuDNN version       NOT used
GPU model and memory   NOT used
Exact command to reproduce 

       get file from https://github.com/keras-team/keras/blob/master/examples/imdb_fasttext.py
       edit import path from keras to tensorflow.python.keras like follows
 ```python
from tensorflow.python.keras.preprocessing import sequence
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.layers import Embedding
from tensorflow.python.keras.layers import GlobalAveragePooling1D
from tensorflow.python.keras.datasets import imdb
```
       execute python imdb_fasttext.py

**Comment by tatianashp** [comment]
Thanks for letting us know about the typo. It will be fixed in 1.6 release once it comes out. Please work around it till then.

**Comment by esvhd** [comment]
+1 for this... had to hack my installed version to get this working...

**Comment by sakaia** [comment]
As for me, I am doing like follows as workaround
```Python
# Changed from keras to tensorflow.python.keras
from tensorflow.python.keras.preprocessing import sequence
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.layers import Embedding
from tensorflow.python.keras.layers import GlobalAveragePooling1D
from tensorflow.python.keras.callbacks import TensorBoard
# Followings are workaround for https://github.com/tensorflow/tensorflow/issues/16358
from keras.datasets import imdb
```
For this workaround, it needs to install original keras separately.
Ref.
  https://github.com/tensorflow/tensorflow/issues/16532

**Comment by ahmed-adly-ali** [comment]
here is how i got the same error:



```
from tensorflow.python import keras
from tensorflow.python.keras.datasets import imdb

(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)
```
ERROR: 

Traceback (most recent call last):
  File "/home/ahmed/Code/deep-learning-with-python/classifying-movie-reviews.py", line 5, in <module>
    (train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/datasets/imdb.py", line 77, in load_data
    indices = np.arrange(len(x_train))
AttributeError: module 'numpy' has no attribute 'arrange'

**Comment by sakaia** [comment]
you should change from
from tensorflow.python.keras.datasets import imdb
to
from keras.datasets import imdb

because of this issue in tensorflow/keras package.
original keras (not tensorflow/keras) works fine.
