### ISSUE TITLE
Include grpc_tensorflow_std_server in Docker image

### ISSUE THREAD

**Issue by jlewi** [tensorflow/tensorflow#16365]
It would be nice if the grpc_tensorflow_std_server was included in the Docker image.

This would prevent users from having to write code just to launch a parameter server because they could just run the stock binary.

Some context in: tensorflow/k8s#16

**Comment by aselle** [comment]
@angersson, could you please take a look.

**Comment by angersson** [comment]
This would be nice, but work on the Docker images is not currently high-priority for us, so we're not likely to have time to work on this. Please feel free to make a contribution.

**Comment by AK-ayush** [comment]
I would like to work on it. Could you please provide me some additional information related to it?
