### ISSUE TITLE
Python: Make an alias for "tf.variable" (with a lower "v") so the naming of it is consistent with "tf.placeholder"/"tf.constant"

### ISSUE THREAD

**Issue by olegserov** [tensorflow/tensorflow#16360]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: N/A
- **Python version**:  N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
Many developers learn the naming standards of the software so they can write code faster. It does not make any sense to have to things "tf.placeholder" and "tf.Variable" named using different schema. Constant, Placeholder and Variable are similar entities and can be used interchangeably. They should be named in same style even if tf.Variable is a class. 

https://www.tensorflow.org/api_docs/python/tf/placeholder
https://www.tensorflow.org/api_docs/python/tf/Variable
https://www.tensorflow.org/api_docs/python/tf/constant

### Source code / logs
N/A

**Comment by tatianashp** [comment]
@olegserov Thank you for your feedback. You can use tf.get_variable() instead of tf.Variable() to keep everything lower case.  Please see https://www.tensorflow.org/api_docs/python/tf/get_variable for details on the API.
