### ISSUE TITLE
I have an issue with http://projector.tensorflow.org/ always getting stuck

### ISSUE THREAD

**Issue by JustinMorsesTester** [tensorflow/tensorflow#16366]
Can anyone help me with this issue? I start up the _**Visualizing High-Dimensional Space**_ webstie and it loads until it says something about metadata and never does anything from there. Plese, help. I'm so confused?

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
