### ISSUE TITLE
java.lang.InternalError: Cannot find requested resource bundle for locale en_US

### ISSUE THREAD

**Issue by demidroid** [tensorflow/tensorflow#16388]
bazel version  0.9.0
java version "1.8.0_161"
os：Ubuntu 16
编译之后出现这个错误，
 Building tensorflow/examples/android/libtensorflow_demo.jar (24 source files) failed (Exit 1)
java.lang.InternalError: Cannot find requested resource bundle for locale en_US

应该如何修改呢，谢谢啦

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by demidroid** [comment]
CUDA/cuDNN  ，GPU model and memory在configure中选择的no
当我执行这个命令时bazel build -c opt //tensorflow/examples/android:tensorflow_demo，我同时也在mac os执行了这个命令，出现了类似的错误java.lang.InternalError: Cannot find requested resource bundle for locale zh_CN,,但是当我执行bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so ，是不是和多国语系相关，在代码中没有找到相关的部分,谢谢您

**Comment by demidroid** [comment]
CUDA/cuDNN ，GPU model and memory在configure中选择的no
当我执行这个命令时bazel build -c opt //tensorflow/examples/android:tensorflow_demo，我同时也在mac os执行了这个命令，出现了类似的错误java.lang.InternalError: Cannot find requested resource bundle for locale zh_CN,,但是当我执行bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so ，能够成功编译出so文件，所以是不是和多国语系相关，但是在代码中没有找到相关的部分,还不是不知道应该如何处理，谢谢您的回复

**Comment by demidroid** [comment]
我终于解决了这个问题，sudo apt-get upgrade bazel不要执行这一步，安装的java版本是1.8.0_151，系统必须只安装一个java，我把所有java版本都卸载之后，然后重新安装，就成功了
