### ISSUE TITLE
Tensorflow not using GPU

### ISSUE THREAD

**Issue by rajeev595** [tensorflow/tensorflow#16387]
I use windows in my laptop. Initially tensorflow worked well with GPU. I don't know why suddenly it's not detecting the GPU. I am using tensorflow-gpu 1.4 version (installed with pip install tensorflow-gpu) with CUDA 8.0 and cudnn 6.0. I also tried with other versions but the problem persists. Attached is the error message shown. I appreciate any help :)

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: just called a session
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **TensorFlow installed from (source or binary)**: pip install tensorflow-gpu
- **TensorFlow version (use command below)**: 1.4
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 8.0/6.0
- **GPU model and memory**: NVIDIA GeForce 1050 2GB
- **Exact command to reproduce**: sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

(https://user-images.githubusercont
![tferror](https://user-images.githubusercontent.com/19821962/35368823-48f11022-0153-11e8-87c3-41e41118a3fa.png)
ent.com/19821962/35368747-e2d4ba8c-0152-11e8-871a-a6a5aedf6663.png)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by rajeev595** [comment]
@tensorflowbutler Thanks for your response. I have edited the same :)

**Comment by ushnish** [comment]
Try uninstalling and reinstalling from source maybe? That way it's more configured and customized to your machine.

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). More people will see it there, and we don't have the bandwidth to debug installation issues here.
