### ISSUE TITLE
tensorflow object detection issue

### ISSUE THREAD

**Issue by usu008** [tensorflow/tensorflow#16393]
i developed the custom object detector with some 96 images (train 76 and test 20) after trained 200k steps my losses(1) goes down correctly....after that i create the interference graph all ok..........but my question is when i run my code to detect the object from video it not able to find the correct object ........ thanks in advance.....

actually i think we have a enough image for the dataset...because my dataset can able to detect the object from pre built video....so....it can detect the object from webcam also but not ...i dont kw the exact problem.....i think the resolution may b differ...thats y it not able to detect the object....﻿

use predefined "object detection" code with my own data set
ubuntu 16.04
tensorflow installed in anaconda environment
tensorflow 1.4.0
bazel 0.4.5
cpu version

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by usu008** [comment]
use predefined  "object detection" code with my own data set
ubuntu 16.04
tensorflow installed in anaconda environment
tensorflow 1.4.0
bazel 0.4.5
cpu version

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
