### ISSUE TITLE
Does TensorFlow 1.5 support CUDA 9.1?

### ISSUE THREAD

**Issue by playgithub** [tensorflow/tensorflow#16399]
My notebook has an MX150 display adapter, someone said that it's available with CUDA 9.1

**Comment by qmick** [comment]
Not officially support, but someone manage to build TF1.5 with CUDA9.1, see #15140

**Comment by Davidnet** [comment]
Yes, I been able to compile tf-1.5rc1 with CUDA 9.1 no problems

**Comment by tatatodd** [comment]
Thanks for the comments @qmick and @Davidnet!

Please follow-up on #15140 for CUDA 9.1 status.

I'll also mention for posterity that our official compatibility (for released versions) is described in our documentation:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/install/install_sources.md
https://www.tensorflow.org/install/install_sources

**Comment by JackLongKing** [comment]
I will tf r1.4 with cuda9.1 and cudnn7.0.5.
