### ISSUE TITLE
Direct Native Code / LLVM IR generation / JIT Compilation / Staging / Incremental Computing

### ISSUE THREAD

**Issue by sirinath** [tensorflow/tensorflow#164]
If it possible to have a feature to bypass C++ and go directly to Native / LLVM IR

**Comment by sirinath** [comment]
This can be useful when you have a defined DSL: https://github.com/tensorflow/tensorflow/issues/70

**Comment by jeffreyadean** [comment]
This is something we are actively working on, although it is in the early stages.  It is discussed briefly in the second-to-last paragraph of the Future Work section of the white paper at http://tensorflow.org/whitepaper2015.pdf:


"We also have a number of concrete directions to improve the performance of TensorFlow. One such direction is our initial work on a just-in-time compiler that can take a subgraph of a TensorFlow execution, perhaps with some runtime profiling information about the typical sizes and shapes of tensors, and can generate an optimized routine for this subgraph. This compiler will understand the semantics of perform a number of optimizations such as loop fusion, blocking and tiling for locality, specialization for particular shapes and sizes, etc."

**Comment by sirinath** [comment]
Sounds jolly good to me. Also how about having a high level language / DSL around this.

**Comment by sirinath** [comment]
I am not a fan of Python but an following: https://github.com/Maratyszcza/PeachPy is an interesting approach used in http://www.yeppp.info/

**Comment by bhack** [comment]
@jeffreyadean When you talk of Halide in the White paper you conclude with "In future work we are hoping to extend
TensorFlow with a similar cross-operation dynamic com-
pilation framework." Can you argument a little bit more on this?

**Comment by bhack** [comment]
@sirinath OpenCV is working on something similar with [Numl](http://code.opencv.org/projects/opencv/wiki/2015#2015-11-10)

**Comment by sirinath** [comment]
Some optimisations may not be apparent when static set up. Perhaps TensorFlow can do some staging and optimisation of the execution while running based on usage patterns, i.e., JIT compilation / Runtime Code Re Optimisation. This options need to be opt in where you have to option of full static optimisation and ability to specify a graph or sub graph for JIT / staging where this might help.

Perhaps you can borrow some ideas from projects related to: https://scala-lms.github.io/

**Comment by aselle** [comment]
This issue is more of a large scale road map item, and is already handled elsewhere. This issue is not individually actionable, so closing for now.

**Comment by sirinath** [comment]
Can you point me to the relevant project?

**Comment by aselle** [comment]
We are working on it, there's no separate project for this.
