### ISSUE TITLE
[doc] link to "How to Use t-SNE Effectively" from embeddings is broken

### ISSUE THREAD

**Issue by sakaia** [tensorflow/tensorflow#16400]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)  NO (since Web page problem)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04) Windows 7**:
- **TensorFlow installed from (source or binary) binary**:
- **TensorFlow version (use command below) 1.5.0rc0 **:
- **Python version  3.5.1**: 
- **Bazel version (if compiling from source) NOT USED**:
- **GCC/Compiler version (if compiling from source) NOT USED**:
- **CUDA/cuDNN version NOT USED**:
- **GPU model and memory NOT USED **:
- **Exact command to reproduce DOC Problem. Just look https://www.tensorflow.org/programmers_guide/distill.pub/2016/misread-tsne/**:

### Describe the problem
- Link to to "How to Use t-SNE Effectively" is broken.
- The page link is follows (before junmping)
  - https://www.tensorflow.org/programmers_guide/embedding
  - 404 page is following URL 
     - https://www.tensorflow.org/programmers_guide/distill.pub/2016/misread-tsne/
- Original page should be follows. (the URL in embedding.md should rewrite to follows)
  -   https://distill.pub/2016/misread-tsne/

### Source code / logs
- The problem code is follows.
  - https://github.com/tensorflow/tensorflow/blame/v1.5.0-rc1/tensorflow/docs_src/programmers_guide/embedding.md#L123

**Comment by yongtang** [comment]
@sakaia The linke seems to have been fixed in PR #16029. I will close this issue as it has been resolved. Thanks for your contribution!
