### ISSUE TITLE
embedding lookup table in tensorflow serving

### ISSUE THREAD

**Issue by mjason3** [tensorflow/tensorflow#16448]
Hi, I am trying to serve a NLP model in tensorflow serving. I am wondering how embedding matrix is being stored in tensorflow serving. If I deploy model to two servers, will the embedding matrix be a distributed table with sharding for looking up?

**Comment by anpark** [comment]
same question, how serving large embedding lookup?

**Comment by tatianashp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by poryfly** [comment]
> same question, how serving large embedding lookup?

hi, how do you solved this problem at last.
