### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by LokLu** [tensorflow/tensorflow#16444]
The mean squared error is described as following

mean_squared_error(
    labels,
    predictions,
    weights=1.0,
    scope=None,
    loss_collection=tf.GraphKeys.LOSSES,
    reduction=Reduction.SUM_BY_NONZERO_WEIGHTS
)

The default reduction method is MEAN in v1.4

**Comment by facaiy** [comment]
Do you mean `Reduction.MEAN`?

https://github.com/tensorflow/tensorflow/blob/c646af1957197a9be0feb5e928af46e29da688ea/tensorflow/python/ops/losses/losses_impl.py#L525-L528

**Comment by LokLu** [comment]
@facaiy Yes. In older versions, the default setting is SUM_BY_NONZERO_WEIGHTS. I don't when they update it to Reduction.Mean.

**Comment by facaiy** [comment]
Could you paste your system information?

  > You can collect some of this information using our environment capture script:
  > https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh
  > You can obtain the TensorFlow version with
  > python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

I have checked r1.4 branch and the latest master branch, the default reduction seems not changed to `Reduction.Mean`.

**Comment by LokLu** [comment]
The function behaviors like that on my PC. And it compute the sum only when I declare the reduction as SUM

### System information
OS Platform and Distribution:  (Ubuntu 14.04)
TensorFlow installed from: binary
TensorFlow version (use command below): 'v1.4.0-19-ga52c8d9', '1.4.1')
Python version:  2.7.13
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source)**:
CUDA/cuDNN version: V8.0.44/V6.0
GPU model and memory: Titan xp 12G

**Comment by facaiy** [comment]
If I understand you correctly, you mistake `Reduction.SUM_BY_NONZERO_WEIGHTS` as the sum of squared error, right? 

Although the name is a little confusing, in fact, `Reduction.SUM_BY_NONZERO_WEIGHTS` behaves like MSE (`Reduce.MEAS`) when `weight=1.0` by default. Unfortunately, it seems that tensorflow is lack of explanations in the document: https://www.tensorflow.org/versions/master/api_docs/python/tf/losses/Reduction

**Comment by LokLu** [comment]
Ya, I mistaken it as the summation of squared error. Thanks for your explanation.
