### ISSUE TITLE
Error on SummaryWriter creation

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#1645]
I'm loading a graph from a file and I'd like to see what the topology is. As there doesn't seem to be a way to do this in python (the best I can do is guess the tensor names and use ```graph.get_tensor_by_name```), I'm trying to produce a Summary which I can then view with TensorBoard. Unfortunately, instantiating the SummaryWriter object gives me an error:

```
AttributeError                            Traceback (most recent call last)
/home/vlad/Repos/vision/Hand/simple_imagenet.py in <module>()
      9 sess = tf.Session()
     10 
---> 11 writer = tf.train.SummaryWriter('./', sess.graph_def)
     12 
     13 #pool = sess.graph.get_tensor_by_name('pool_3:0')

/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/summary_io.py in __init__(self, logdir, graph_def, max_queue, flush_secs)
     95     if not gfile.IsDirectory(self._logdir):
     96       gfile.MakeDirs(self._logdir)
---> 97     self._event_queue = six.moves.queue.Queue(max_queue)
     98     self._ev_writer = pywrap_tensorflow.EventsWriter(
     99         compat.as_bytes(os.path.join(self._logdir, "events")))

AttributeError: 'module' object has no attribute 'Queue'
```

I'm using the pip3 install of tensorflow 7.1 on Ubuntu 15.10.

**Comment by mrry** [comment]
This sounds like a version error with the `six` library: can you please run the following code and reply with the result?

```python
import six
print(six.__version__)
```

**Comment by vladfi1** [comment]
My ```six``` version is ```1.9.0```.

**Comment by mrry** [comment]
Can you also try the following?

```python
print(dir(six.moves.queue))
print(six.moves.queue.__file__)
```

I have tried `six` versions `1.4.1`, `1.5.2` and `1.10.0` (in Python 2.7 and 3.4) and these all have `six.moves.queue.Queue`.

**Comment by vladfi1** [comment]
It looks like I've identified the problem:
```
> print(six.moves.queue.__file__)
/home/vlad/Repos/vision/Hand/queue.py
```

For some reason my local ```queue.py``` file is being picked up! Any idea why this is the case?

**Comment by mrry** [comment]
I believe this is related to Python's confusing import semantics, which make problems likely if a local module shadows the name of a standard library one. The easiest fix is probably to rename your local `queue.py`, or move it into a submodule (I can't tell from the path if your `queue` module would be imported as `queue` or `Hand.queue` in your program; if the former then I think you'll need to move it).

**Comment by mrry** [comment]
(Closing this since the issue seems to be related to local configuration.)

**Comment by moesy** [comment]
I get the same error with six v1.10.0 and Tensorflow v0.12.0rc1 .

**Comment by Riotpiaole** [comment]
Same Here we are six v1.10
