### ISSUE TITLE
Semantic Segmentation API

### ISSUE THREAD

**Issue by RomRoc** [tensorflow/tensorflow#16452]
Hello, is there any plan to include Semantic Segmentation API in future Tensorflow releases, similar to [Tensorflow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection#tensorflow-object-detection-api) ?

There are other semantic segmentation repositories in Github, an awesome list is [here](https://github.com/mrgloom/awesome-semantic-segmentation), but I would like to see the implementation from Tensorflow organization.
Thanks

**Comment by tatianashp** [comment]
@dreamdragon Would you like to comment on this request?

**Comment by bhack** [comment]
Check https://github.com/tensorflow/models/issues/2793 but we could use this issue to track the topic.

**Comment by RomRoc** [comment]
Hello, maybe @afathi3 or @tatianashp  has got an ETA for semantic segmentation Tensorflow release?
Last week [Detectron](https://github.com/facebookresearch/Detectron) Instance Segmentation was released, it could be interesting to compare these two software.
Thanks

**Comment by tatianashp** [comment]
@jch1 Can you comment?

**Comment by RomRoc** [comment]
I would like to inform that February 9 Tensorflow Api release now support instance segmentation.
Refer to [this section](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/instance_segmentation.md) for instructions.

**Comment by bhack** [comment]
@RomRoc What about the code mentioned in the DeepLabv3+ paper?

**Comment by RomRoc** [comment]
@bhack It's better to ask to Tensorflow team for forthcoming developments.

**Comment by bhack** [comment]
@YknZhu ping us here when you will have an update :wink:

**Comment by edgarriba** [comment]
@YknZhu any plan to release a Pytorch version for that ?

**Comment by YknZhu** [comment]
Haha no plans yet ;) But helping hands welcome!

**Comment by nom** [comment]
@YknZhu Keep me updated, can convert to pytorch.

**Comment by bhack** [comment]
https://github.com/tensorflow/models/pull/3551

**Comment by YknZhu** [comment]
Thanks for the patience. Deeplabv3+ is now released at https://github.com/tensorflow/models/tree/master/research/deeplab :)

**Comment by bhack** [comment]
@YknZhu Are you waiting also for https://github.com/tensorflow/models/pull/3244?

**Comment by YknZhu** [comment]
Yup mobilenet deeplab models will be released after they integrated into tensorflow/models.

**Comment by bhack** [comment]
I think that we can close thit. Mobilenet backbone is merge in https://github.com/tensorflow/models/pull/3709

**Comment by RomRoc** [comment]
Yes thanks.
