### ISSUE TITLE
Updated roadmap?

### ISSUE THREAD

**Issue by qtdaniel** [tensorflow/tensorflow#16453]
The [TensorFlow roadmap](https://www.tensorflow.org/about/roadmap) was last updated a year ago (January 2017); could there be an update from the team on where TensorFlow is going in 2018?

**Comment by tatatodd** [comment]
@qtdaniel Good point.

@wolffg @rajatmonga @mkacholia we should update the roadmap on tensorflow.org.

**Comment by facaiy** [comment]
Does tensorflow have plan to implement Unicode string Tensor?

**Comment by rajatmonga** [comment]
Yes, we are looking to update the roadmap soon, and will work to keep it more up to date.

@facaiy We do not have anything in the works to implement Unicode string Tensor. If this is something that is useful, may be worth opening it as a feature request, and share how you may do it.

**Comment by bhack** [comment]
It could be useful to explicitly know what is in the next release targets. Can you start to use a specific release label for ISSUE/PR?

**Comment by skye** [comment]
Unfortunately I don't think we can commit to including individual issues/PRs to a given release unless they're part of a larger roadmap item. @aselle @av8ramit correct me if I'm wrong.

**Comment by bhack** [comment]
@skye Why not? Many of your upstream updates comes from your internal branch that merge more or less regularly here on the public available repository. 
Tagging "community" issue/pr on a target release could be useful to have a tentative effort. I.e. this is working for Kubernetes as a general reference.

**Comment by av8ramit** [comment]
Yes, unfortunately that's true at the moment. Since we release on a regular cadence we don't commit to individual PRs/issues unless there is a special exception made.

**Comment by bhack** [comment]
@av8ramit But you target also review workload on user public PRs. So this could be useful for community PR and also to issue that are waiting for an internal upstream update. You can see many comment on issues that are not labeled as contribute welcome with comment like "we are working on this".

**Comment by bhack** [comment]
Just as an example we need to always make explicit requests [like this](https://github.com/tensorflow/tensorflow/issues/16468#issuecomment-364678210) in meanwhile TF team is releasing subsequent RC.

**Comment by gunan** [comment]
One reason for this is, when we tried to commit to certain features for releases, we saw our releases delayed by months (i.e. 1.5 release). When we move to modularizing tensorflow, and make more smaller component releases this will be feasible.
However, with the current monolithic structure of tensorflow, committing to features for releases just cause us to penalize all of TF if a feature is particularly messy, or problematic.

**Comment by bhack** [comment]
@gunan It is a good point but also on large repositories/communities like Kubernetes the release labels are just a desired target. When you are aware to skip the release target, best-effort, the label is re-target again.
So here we are not talking about managing release blocking labels.

**Comment by bhack** [comment]
For the pure Roadmap https://github.com/tensorflow/tensorflow/pull/16984 is merged.

**Comment by av8ramit** [comment]
@sandeepngupta has merged the new roadmap which will be populated to the site soon. Closing for now.
