### ISSUE TITLE
Parameter parsing error messages

### ISSUE THREAD

**Issue by MikalaiDrabovich** [tensorflow/tensorflow#16451]
Parameter parsing error messages probably can be improved, e.g. 

`bazel-bin/tensorflow/core/profiler/profiler --profile_path=/tmp/for_tfprof/profile_20`

runs ok, but if cd to bazel-bin/tensorflow/core/profiler/ and

`./profiler --profile_path /tmp/for_tfprof/profile_20`

results in 

> ./profiler
> --profile_path
> /tmp/for_tfprof/profile_20
> Reading Files...
> Try to use a single --profile_path instead of graph_path,op_log_path,run_meta_path
> 2018-01-26 01:43:29.458032: F tensorflow/core/profiler/profiler.cc:206] Non-OK-status: ReadProtoFile(Env::Default(), FLAGS_graph_path, graph.get(), false) status: Not found: ; No such file or directory
> Aborted (core dumped)

**Comment by yongtang** [comment]
I think the error message could be improved. Created a PR #16463 for the fix.
