### ISSUE TITLE
How to create a model checkpoint based on each step rather than time interval.? using TensorFlow-Slim api.

### ISSUE THREAD

**Issue by softmanu** [tensorflow/tensorflow#16462]
slim.learning.train(
    train_op,
    logdir,
    number_of_steps=1000,
    **save_summaries_secs=300**,
    **save_interval_secs=600**):

The above api only supports to capture model checpoints periodically, but I need to checkpoint based on each step. How do achieve this using TesorFlow-Slim API.?

I am looking for parameters like this:

save_summaries_steps = 10,
save_interval_steps=10
    where the value 10 is the number of steps and that should be configurable.

**Comment by tatianashp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by softmanu** [comment]
Thanks.. took your advice.  I've posted the same on stackoverflow, but can we take this as a feature request, as I did not find any way to achieve it in TF-Slim.? do I need to modify the content to make it a request.? I've recently joined so I may not have enough knowledge on github working process..

**Comment by tatianashp** [comment]
It is a feature request if it cannot be done with existing functionality.

@nsilberman Could you comment on @softmanu question/request?
