### ISSUE TITLE
Extend tf.unique_with_counts to multi-dimensional tensors

### ISSUE THREAD

**Issue by violetguos** [tensorflow/tensorflow#16499]
I'm trying to solve KNN using tensorflow. After I get the K neighbours for N vectors, I have a N by K tensor. Now, for each vector in N, I need to use [```tf.unique_with_counts```][1] to find the majority vote. However, I cannot iterate in a tensor and I cannot run [```tf.unique_with_counts```][1] with a multi-dimensional tensor. It keeps giving me ```InvalidArgumentError (see above for traceback): unique expects a 1D vector.```

Why can't tf support multi-demsional input?

Example:

    def knnVote():
    '''
    KNN using majority vote
    '''
    #nearest indices
    A = tf.constant([1, 1, 2, 4, 4, 4, 7, 8, 8])
    nearest_k_y, idx, votes = tf.unique_with_counts(A)
    print("y", nearest_k_y.eval())
    print("idx", idx.eval())
    print("votes", votes.eval())
    majority = tf.argmax(votes)
    predict_res = tf.gather(nearest_k_y, majority)
    
    
    print("majority", majority.eval())
    print("predict", predict_res.eval())
    return predict_res

Result:

    y [1 2 4 7 8]
    idx [0 0 1 2 2 2 3 4 4]
    votes [2 1 3 1 2]
    majority 2
    predict 4

But how can I extend this to N by D input A, such as the case when ```A = tf.constant([[1, 1, 2, 4, 4, 4, 7, 8, 8],
[2, 2, 3, 3, 3, 4, 4, 5, 6]])```

  [1]: https://www.tensorflow.org/api_docs/python/tf/unique_with_counts

**Comment by yongtang** [comment]
The multi-dimensional and axis support for unique_with_counts actually has already been implemented when UniqueV2 kernel was added in #12952. It is just not registered and exposed to python API.

Added a PR #16503 to address the issue.
