### ISSUE TITLE
in_top_k op does not work with int64 labels

### ISSUE THREAD

**Issue by poolio** [tensorflow/tensorflow#165]
The `tf.nn.in_top_k` op does not work with `int64` labels. This is problematic when computing accuracy from a one-hot encoding of labels as the output of `argmax` is `int64`:
```python
y = tf.placeholder("float")
yhat = tf.placeholder("float")
tf.nn.in_top_k(yhat, tf.argmax(y, 1), 1)
````
yields the error:
````
TypeError: Input 'targets' of 'InTopK' Op has type int64 that does not match expected type of int32.
```
The simple workaround is to cast the labels before calling the op:
```
tf.nn.in_top_k(y, tf.cast(tf.argmax(y_, 1), "int32"), 1)
```
but it'd be nice if `int64` labels were supported out of the box.

**Comment by vrv** [comment]
I added this some time last week to the source -- let me know if this still doesn't work at HEAD.  (will be in our next binary release)
