### ISSUE TITLE
TF1.5.0 not working with CUDA 8.0

### ISSUE THREAD

**Issue by Paula15** [tensorflow/tensorflow#16513]
After upgrading to TF 1.5.0, when I import tensorflow, it raises:

```
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
```

- System: Ubuntu 14.04.5 LTS (64 bit)
- Python: 2.7.6
- TensorFlow: tensorflow-gpu-1.5.0
- GPU: GeForce GTX TITAN
- CUDA: 8.0

**Comment by rootally** [comment]
Facing the exact same Issue!

**Comment by mtngld** [comment]
The prebuilt tensorflow binaries support CUDA 9.0 - https://github.com/tensorflow/tensorflow/releases/tag/v1.5.0

You have 3 options:

1. Compile from source and link against CUDA 8.0.
2. Upgrade your CUDA to 9.0
3. Continue to user TF 1.4.

**Comment by reedwm** [comment]
@mtngld is correct.
