### ISSUE TITLE
Feature Request: Make lstm2d.separable_lstm accept Dynamic Batch Sizes

### ISSUE THREAD

**Issue by selcouthlyBlue** [tensorflow/tensorflow#16510]
Apparently, lstm2d.separable_lstm doesn't accept dynamic batch sizes (number of images). Whenever I set the shape of a `placeholder` to `(None, height, width, depth)` to be fed into the network , I get this error:

```
Traceback (most recent call last):
  File "...\tensorflow\contrib\ndlstm\python\lstm2d.py", line 159, in separable_lstm
    hidden = horizontal_lstm(images, nhidden)
  File "...\tensorflow\contrib\ndlstm\python\lstm2d.py", line 82, in horizontal_lstm
    sequence = images_to_sequence(images)
  File "...\tensorflow\contrib\ndlstm\python\lstm2d.py", line 47, in images_to_sequence
    [width, num_image_batches * height, depth])
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

I guess it would be nice to have `separable_lstm` accept dynamic batch sizes so it can be used effectively.

**Comment by selcouthlyBlue** [comment]
Proposal: 

Modify the implementation of `images_to_sequence` and `sequence_to_images` such that they'll accept dynamic batch sizes. I have already pushed [it](https://github.com/selcouthlyBlue/tensorflow/commit/7fcc9393e0b9dbc1b70fe746dfabca424c320b38) into my forked copy of tensorflow. The gist of it is instead of multiplying the `height` of the images to the `batch_size`, I multiplied it to the `width` of the images.

**Comment by selcouthlyBlue** [comment]
I tried it for my own project and it's taking long to get to a step with a batch size greater than 1 in training. Any other ideas on how to make the batch size for ndlstm dynamic?

**Comment by facaiy** [comment]
How about using tf.shape to get dynamic shape? I mean to modify _shape function: 

s = array_ops.shape(input_)
return s[0], s[1],.... 

Does it work?

**Comment by selcouthlyBlue** [comment]
Applying tf.shape worked although I applied it in only one part of the lstm2d like so:

```
def images_to_sequence(tensor):
  _, _, width, depth = _shape(tensor)
  s = array_ops.shape(tensor)
  batch_size, height = s[0], s[1]
  transposed = array_ops.transpose(tensor, [2, 0, 1, 3])
  return array_ops.reshape(transposed,
                           [width, batch_size * height, depth])
```

With that, `sequence_to_images` was also modified to take in a known dimension (height) of the tensor:

```
def sequence_to_images(tensor, height):
  width, num_batches, depth = _shape(tensor)
  if num_batches is None:
    num_batches = -1
  else:
    num_batches = num_batches // height
  reshaped = array_ops.reshape(tensor,
                               [width, num_batches, height, depth])
  return array_ops.transpose(reshaped, [1, 2, 0, 3])
```

I already pushed these changes.
