### ISSUE TITLE
how to install ffmpeg in tensorflow 1.4 binary

### ISSUE THREAD

**Issue by zeynali** [tensorflow/tensorflow#16512]
hi
i want to install ffmpeg in tensorflow 1.4 binary , python 3.5 on ubuntu 16.04 , please help me how do i do ? 
the output type python -c "from tensorflow.contrib import ffmpeg" is ok dont have anly error , but i dont know why : 
from tensorflow.contrib import ffmpeg

i get error , 
>>>  from tensorflow.contrib import ffmpeg
  File "<stdin>", line 1
    from tensorflow.contrib import ffmpeg
    ^
IndentationError: unexpected indent

**Comment by jackyko1991** [comment]
ffmpeg is not officially supported by TF, you need to build from source and set this function on

**Comment by drpngx** [comment]
You have to use `tf.contrib.ffmpeg` to use functionality from there.
