### ISSUE TITLE
RNN Cell: different device placement for variables and ops

### ISSUE THREAD

**Issue by seominjoon** [tensorflow/tensorflow#1652]
I want to use RNN cell on multiple GPUs. For maximum performance, I want to place RNN cell variables on CPU and operations (matmul, tanh, etc) on GPU, just like in cifar10 multi gpu example. However, the current implementation of RNN cell seems to only allow same device placement for both variables and ops. Could you enable different device placement?

**Comment by keveman** [comment]
The existing implementation focuses equally on being readable/understandable/hackable, and being performant. Please see the documentation [here](https://www.tensorflow.org/versions/r0.7/api_docs/python/framework.html#Graph.device) for how to place variables/operations on specific devices. Closing this issue as the functionality to do what you want is already present in TensorFlow.

**Comment by seominjoon** [comment]
Thanks, I just want to confirm one thing: using the raw RNNCell as it is, I cannot place vars and ops in different devices, is this correct? I understand that I can easily make changes to it myself to give different placement.

**Comment by keveman** [comment]
That's correct.

**Comment by YiMX** [comment]
@seominjoon Hi, How did you seperate vars and ops in different devices for an RNN cell?

**Comment by andrebeu** [comment]
I am also having this issue where I want to place RNN vars on CPU but execute the cell ops on GPU. having to hack around source code is subprime.  it would be nice if vars and ops had a kwarg for soft device placement. then we could do:

to create a cell
`cell = tf.contrib.rnn.BasicRNNCell(celldim,device='/cpu:')`

to run the cell ops
`output,state = cell(x_batch[:,time_step,:], cell_state,device='/gpu:0')`
