### ISSUE TITLE
Feature request: tf.Print should either print (not log), or accept a log level

### ISSUE THREAD

**Issue by nikhilk** [tensorflow/tensorflow#16523]
### System information
- **Have I written custom code**: no
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from**: binary
- **TensorFlow version**: 1.4.1
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: n/a

### Feature Request
Currently tf.Print produces INFO logs.
If log level is set to get rid of INFO logs (given the noise level), it renders tf.Print as non-functional.

It would be nice to have tf.Print work either by making it actually work like print(), i.e. it is not a mechanism to generate logs, or if it should remain that way, then have it accept a log level optional parameter.

**Comment by reedwm** [comment]
/CC @mrry, what do you think of this proposal?

**Comment by mrry** [comment]
Seems reasonable. I'd lean towards the "making it actually work like `print()`" option, and consider adding a new API (perhaps in `tf.contrib`) that offers more options.

**Comment by reedwm** [comment]
Marking as contributions welcome for adding the contrib op.

**Comment by asimshankar** [comment]
I believe this is addressed in https://github.com/tensorflow/tensorflow/pull/15173 ?

**Comment by nikhilk** [comment]
From a quick read of the history on that bug, I don't think it does. I think from there print is still based on using the logging infrastructure and/or stderr, whereas `print()` by default writes unconditionally to stdout, which would be the desired behavior.

**Comment by mohantym** [comment]
Hi @nikhilk ! tf.print does not print logs anymore. To get logs printed , you can use [tf.compat.v1.loggin_set_verbosity](https://www.tensorflow.org/api_docs/python/tf/compat/v1/logging/set_verbosity) . Thank you!
