### ISSUE TITLE
How to use tensorflow library in c programs??

### ISSUE THREAD

**Issue by yunyin** [tensorflow/tensorflow#16539]
I build shared libraries in tensorflow-serving with bazel.
However, I can not build C programs with the shared libraries.

I build C programs like this:
g++ main.cc -L../../bazel-bin/tensorflow_serving/rnnlm -lrnnlm_client_run -ldata_generator

Details is shown below:

../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::serving::PredictionService::Stub::Predict(grpc::Cli
    entContext*, tensorflow::serving::PredictRequest const&, tensorflow::serving::PredictResponse*)'
 12 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
 13 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::Tensor::CheckTypeAndIsAligned(tensorflow::DataType)
     const'
 14 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::serving::PredictRequest::_slow_mutable_model_spec()
    '
 15 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::Tensor::FromProto(tensorflow::TensorProto const&)'
 16 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::serving::PredictResponse::PredictResponse()'
 17 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::TensorShape::CheckDimsEqual(int) const'
 18 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::Tensor::Tensor()'
 19 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::serving::PredictionService::NewStub(std::shared_ptr
    <grpc::ChannelInterface> const&, grpc::StubOptions const&)'
 20 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::TensorShapeProto_Dim::TensorShapeProto_Dim(google::
    protobuf::Arena*)'
 21 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::TensorProto::TensorProto(google::protobuf::Arena*)'
 22 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAligned(unsigned
     long)'
 23 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::dim_size(
    int) const'
 24 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::serving::PredictRequest::~PredictRequest()'
 25 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
 26 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::TensorShapeProto_Dim::TensorShapeProto_Dim()'
 27 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::serving::PredictRequest::PredictRequest()'
 28 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `google::protobuf::Arena::OnArenaAllocation(std::type_info const
    *, unsigned long) const'
 29 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::TensorProto::~TensorProto()'
 30 ../../bazel-bin/tensorflow_serving/rnnlm/librnnlm_client_run.so: undefined reference to `tensorflow::TensorProto::_slow_mutable_tensor_shape()'

**Comment by reedwm** [comment]
/CC @nfiedel.

Also, the TensorFlow Serving repo is [here](https://github.com/tensorflow/serving), so I think you should file issues there (@nfiedel can you confirm?)

**Comment by nfiedel** [comment]
Feel free to file as a bug/request at the TensorFlow Serving link from @reedwm. Note that this looks like more general compiler / bazel issue that the team will likely not have time to investigate. If you do find a resolution, please share it along with any PRs for documentation or build changes. Thanks!
