### ISSUE TITLE
deconv_output_length(input_length, filter_size, padding, stride)

### ISSUE THREAD

**Issue by gauss-clb** [tensorflow/tensorflow#16544]
deconv_output_length(input_length, filter_size, padding, stride) is defined [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/utils.py#L159)

When padding is valid, input_length += max(filter_size - stride, 0), why to use `max` function?
See more details on #2118

For conv2d:
```
output = (input - filter + stride) // stride  # VALID
output = (input + stride - 1) // stride  # SAME
```

For conv2d_transpose:
```
output = input * stride + filter - stride  # VALID
output = input * stride - stride + 1  # SAME 
```

Even when filter_size is less than stride, I think output is also `input * stride + filter - stride` rather `input * stride`, so why to use `max`?

**Comment by drpngx** [comment]
Could you comment on the original thread? If you're will to send a well-formed PR, maybe that's also another way. thanks!
