### ISSUE TITLE
AttributeError: module 'tensorflow.python.layers.layers' has no attribute 'conv_2d'

### ISSUE THREAD

**Issue by ziofil** [tensorflow/tensorflow#16548]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: see below
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.13.2
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.5.0
- **Python version**: 3.6.3
- **GPU model and memory**: no GPU
- **Exact command to reproduce**:

```python
class my_RNNCell(tf.nn.rnn_cell.RNNCell):
    def __init__(self):
        super(my_RNNCell, self).__init__()
        self._output_size = 2
        self._state_size = 2

    def __call__(self, tensor_in, state):

        output = tf.layers.conv_2d(tensor_in, 1, [1, 10])

        return output, output
    
    @property
    def output_size(self):
        return self._output_size
    @property
    def state_size(self):
        return self._state_size


tf.nn.dynamic_rnn(my_RNNCell(), inputs=tf.placeholder(shape=[None,2,100,3], dtype=tf.float32), initial_state= tf.placeholder(shape=[None,2], dtype=tf.float32))

>>>
AttributeError: module 'tensorflow.python.layers.layers' has no attribute 'conv_2d'
```

**Comment by drpngx** [comment]
Can you try `tf.layers.conv2d`?

**Comment by ziofil** [comment]
That seems to work:
```python
>>>tf.layers.conv2d(tf.placeholder(shape=[None,2,100,3], dtype=tf.float32), 1, [1, 10])
<tf.Tensor 'conv2d/BiasAdd:0' shape=(?, 2, 91, 1) dtype=float32>
```

**Comment by drpngx** [comment]
Great to see it's working for you!

**Comment by ziofil** [comment]
I'm sorry @drpngx , perhaps I wasn't clear: **my issue is still unsolved** (I can't initialize a `dynamic_rnn` using that `RNNCell` with a convolutional layer).
I thought you had asked me to verify that `tf.layers.con2d` could create an op.

**Comment by drpngx** [comment]
What is the error?

**Comment by ziofil** [comment]
The one on the title of this issue: ```AttributeError: module 'tensorflow.python.layers.layers' has no attribute 'conv_2d'```

**Comment by drpngx** [comment]
So you created that cell. Can you change it to `conv2d` instead of `conv_2d`?

**Comment by ziofil** [comment]
omg, I can't believe it was a typo... Ok, problem solved! 😅

**Comment by Cairang** [comment]
top = tf.layers.conv2d(inputs,
                               filters=filters,
                               kernel_size=3,
                               padding=padding,
                               activation=activation,
                               kernel_initializer=kernel_initializer,
                               bias_initializer=bias_initializer,
                               name=name)
   top = tf.layers.conv2d(inputs,

AttributeError: module 'tensorflow' has no attribute 'layers'
