### ISSUE TITLE
How to search similiar images?

### ISSUE THREAD

**Issue by itman85** [tensorflow/tensorflow#1655]
This is not an issue, but i don't know where to ask this. I just get started with tensor flow and it's interesting to me. I know tensorflow will help classifying images, but in my case, i need to search similiar images. I read that google using tensorflow for search image in photos app. So how to make tensorflow return similiar image?
Thank you very much

**Comment by vrv** [comment]
https://github.com/AKSHAYUBHAT/VisualSearchServer might be a good example to look for. (StackOverflow would be a better location for this question, in the future).
