### ISSUE TITLE
conv4d and higher dimension generalization

### ISSUE THREAD

**Issue by jerabaul29** [tensorflow/tensorflow#1661]
Are there some plans to include a 4D (and possibly higher dimension generalization) convolution op? Would be nice for doing 3D + time processing for example (for the 4D version).

Also, should something be done to offer the user the possibility to choose the shape of the kernel? For example allowing both the natural hyper cube kernel nodes location or a hyper thetrahedron location? Could have consequences on the computing power requested:

http://arxiv.org/pdf/1505.02890v2.pdf

**Comment by keveman** [comment]
@jerabaul29, generalizing convolutions to higher dimensions would be a great addition to TensorFlow, especially the GPU implementation. It will be great if someone in the community can take this up.

**Comment by bhack** [comment]
I think that this impact Eigen upstream

**Comment by akors** [comment]
I'm no expert, but I think that Eigen supports tensors with arbitrary dimensions (albeit compilation gets really slow when it's more than 8 or something), and judging by the cuDNN manual, it can also take 5D Tensors (as in 3D+1D-color+1D-batchsize) or maybe even higher-dimensional.

The code in tensorflow/core/kernels/conv_ops.cc looks fairly generic, and might even be extensible to include higher-dimensional and GPU-accelerated convolutions.

I'm afraid it would require a serious amount of digging, though.

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/commit/6a187ccddaebb741ea77fc3201c6e36625f0aadb for an example of adding 3d convolutions, which uses cudnn Nd tensor interface and eigen for CPU.  Something similar could be done for conv4d, conv1d, etc.

If someone wants to tackle this, please let us know (cc @rewonc), since we now have conv2d and conv3d to provide a template for generalization.  We may still be missing something though, so no guarantees it will be straightforward.

**Comment by rewonc** [comment]
@vrv Cool -- definitely seems like there's an opportunity to generalize a template. Will take a look and let you

**Comment by mhuen** [comment]
Are there any news on this?
A 4D operation would be a really nice feature. Especially now that more and more people from other fields, where 4D (3D + time)  is the common use case (i.e. physics), are jumping in on deep learning.
Even if the n-dimensional generalization is not easily implementable, I think a separate conv4d would be very helpful.

**Comment by mayank1123** [comment]
I know it hasn't been long but is there any news on this ? We are currently using Caffe for 4D light-fields convolutions but would love to shift to tensorflow.

**Comment by yaroslavvb** [comment]
@vincentvanhoucke know anyone at Google that likes 4D convolutions?

**Comment by vincentvanhoucke** [comment]
@yaroslavvb not that I know of. I think it would be a perfectly good feature for a motivated contributor to pick up. Note that in my experience, treating the time dimension convolutionally is not always a good idea. It makes you throw a lot of parameters at a dimension that comparatively has a lot less semantic content than the spatial dimensions. YMMV.

**Comment by KendallWeihe** [comment]
Any word on this? I am working with volumetric spectral scans, and a 4D convolution would make a great tool for what I need.

**Comment by mhuen** [comment]
I've plugged a conv4d equivalent together in python. It's just on python level, so most likely not the fastest, but if you want to start with that you can find it here:
https://github.com/mhuen/TFScripts
If you do decide to give it a try, let me know if you have any suggestions or if you come across any bugs as I haven't extensively tested it yet.

**Comment by yuryskaletskiy** [comment]
vote for the improvement too

**Comment by girving** [comment]
I think this is unlikely to happen in a way that makes anyone happy, so closing.  All applications of 4D convs that I know of will almost certainly be forced to use special factorizations for efficiency.

**Comment by funkey** [comment]
nD convolutions can be realized by summing a sequence of (n-1)D convolutions. See [here](https://github.com/funkey/conv4d) for an implementation of a 4D convolution layer using TensorFlow's `conv3d` layer. Details can be found in the [docstring](https://github.com/funkey/conv4d/blob/master/conv4d.py#L27).

**Comment by josuerocha** [comment]
Any news on this? I am working on human action recognition and I could greatly benefit from 4D convolutions since my representation is in the format (x,y,z,t).

**Comment by funkey** [comment]
@josuerocha, is there any reason the [4D convolution](https://github.com/funkey/conv4d) linked above would not work for your use case?

**Comment by ViaFerrata** [comment]
+1 to the need of Conv4D and higher dimensions.
Especially in fields other than traditional machine learning topics, like physics. 

Here, the time dimension can often be treated the same as the spatial dimensions such that a Conv4D would be very useful. I know several people in particle physics that have actually switched to other ML frameworks like CNTK just because of the lack of 4D Convs.

**Comment by shuyiii** [comment]
@vrv It might be late, may I ask if there is any plan recently to add n-d conv? We are working on a pure math problem, already get it worked under 3d, but really need to give evidence that this can work on arbitary dimensional data to finish the paper. Or anyone else is working on this can work together? If not a very huge task, we may try do it by our team people……

**Comment by jerabaul29** [comment]
Any news on this? If this is not available we will have to shift to another framework for one of our upcoming project, which would be a bit sad. If the 4D conv as a sum of 3D convs is the solution you want to keep for now, could this be added natively to tensorflow - nothing would prevent changes in the implementation later on anyways as long as the API choice is good?
