### ISSUE TITLE
How to get RunMetadata for tf.data.Dataset ops?

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorflow#16629]
Tensorflow version: 1.5 (pip)

I am interested in the runtime of ops when using the `tf.data.Dataset` api.
Information like how long shuffle, repeat or batch took.
When running the code below and visualizing it in tensoboard the intersting ops are marked as "unused substructure".

Is my approach the right one?
I find it a little confusing that they show up, but are not traceable.

Example code
```python
import numpy as np
import tensorflow as tf

tf.set_random_seed(0)

data = np.array([[10] * 10] * 3 + [[4] * 10]).astype(np.float32)

with tf.Graph().as_default():
  dataset = tf.data.Dataset.from_tensor_slices(data)
  sess = tf.Session()

  dataset = dataset.cache()
  dataset = dataset.shuffle(10, seed=0)
  dataset = dataset.repeat(5)
  dataset = dataset.batch(2)

  iterator = tf.data.Iterator.from_structure(
      output_types=tf.float32)
  batch = iterator.get_next()

  init1 = iterator.make_initializer(dataset)

  sess.run(init1)

  writer = tf.summary.FileWriter('tmp/datasettest/', sess.graph)
  run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)

  i = 0
  while True:
    try:
      run_metadata = tf.RunMetadata()
      sess.run(batch, options=run_options, run_metadata=run_metadata)
      writer.add_run_metadata(run_metadata, 'step{}'.format(i))
      i += 1
    except tf.errors.OutOfRangeError as ex:
      break
    except Exception as ex:
      raise ex
```
This will result in the following visualization in Tensorboard.

![image](https://user-images.githubusercontent.com/9438971/35647492-054aa5b0-06d3-11e8-8394-9b821fb79603.png)

**Comment by mrry** [comment]
There's no way to do that right now. The `tf.RunMetadata` interface isn't ideal for capturing this kind of information, because a `Dataset` transformation might contribute to 0, 1, or multiple different runs, and it may happen asynchronously with any of them. The transformations produce events for a tracing interface that captures fine-grained execution information, but this interface is [currently unimplemented](https://github.com/tensorflow/tensorflow/blob/995d836e9ba7cbee56948f73bdbd099d419e4511/tensorflow/core/platform/default/tracing_impl.h).

**Comment by reedwm** [comment]
Assigning to @mrry for implementing the tracing_impl.h interface.

**Comment by mrry** [comment]
I doubt I will work on this in the near future.

**Comment by sachinprasadhs** [comment]
You seem to be using older version(1.x) of Tensorflow which is not supported anymore. Please try the latest [Tensorflow version](https://www.tensorflow.org/install/pip) and let us know if the problem still persists. 
Also, refer the [tf.data](https://www.tensorflow.org/api_docs/python/tf/data) API in Tensorflow 2.x version. Thanks!
