### ISSUE TITLE
How to use model.summary() when using placeholder instead of Input(keras)

### ISSUE THREAD

**Issue by ymcasky** [tensorflow/tensorflow#16620]
Dear all, 
I follow  post in "https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html"
The little modified code I use is:
----------------------------------------------------------------------------------------------------------------------------------
import tensorflow as tf
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.backend import categorical_crossentropy
from tensorflow.examples.tutorials.mnist import input_data
from tensorflow.python.keras.models import Model

sess = tf.Session()
img = tf.placeholder(tf.float32, shape=(None, 784))
x = Dense(128, activation='relu')(img)  # fully-connected layer with 128 units and ReLU activation
x = Dense(128, activation='relu')(x)
preds = Dense(10, activation='softmax')(x)  # output layer with 10 units and a softmax activation

labels = tf.placeholder(tf.float32, shape=(None, 10))
loss = tf.reduce_mean(categorical_crossentropy(labels, preds))
mnist_data = input_data.read_data_sets('MNIST_data', one_hot=True)
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(loss)

init_op = tf.global_variables_initializer()
sess.run(init_op)
with sess.as_default():
    for i in range(100):
        batch = mnist_data.train.next_batch(50)
        train_step.run(feed_dict={img: batch[0],
                                  labels: batch[1]})

----------------------------------------------------------------------------------------------------------------------------------
It work fine until I use model.summary :  

model = Model(inputs=img, outputs=preds)

The error message show" Input tensors to a Model must come from `tf.layers.Input`"
I can use tf.layers.Input to solve this problem.
But I really want to use tf.placeholder so I can feed data as I like.
Can anyone help me?  Thanks!!

**Comment by ymcasky** [comment]
I solve my problem!!
Just use inputs = Input(tensor=img)
everything will be fine : )

**Comment by ymcasky** [comment]
I have one more question
---------------------------------------------------------------------------------------------------------------------------------------
import tensorflow as tf

from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.backend import categorical_crossentropy
from tensorflow.examples.tutorials.mnist import input_data
from tensorflow.python.keras.models import Model
from tensorflow.python.keras.layers import  Input

mnist_data = input_data.read_data_sets('MNIST_data', one_hot=True)
img_size_flat = 28*28

img = tf.placeholder(tf.float32, shape=(None, 784))
inputs = Input(tensor=img)   # tf_input
#inputs = Input(shape=(img_size_flat,))  #keras_input
x = Dense(128, activation='relu')(inputs)  # fully-connected layer with 128 units and ReLU activation
x = Dense(128, activation='relu')(x)
preds = Dense(10, activation='softmax')(x)  # output layer with 10 units and a softmax activation
model = Model(inputs=inputs, outputs=preds)
#%%
model.compile(optimizer='rmsprop',
               loss='categorical_crossentropy',
               metrics=['accuracy'])
model.fit(x=mnist_data.train.images,
           y=mnist_data.train.labels,
           epochs=1, batch_size=128)
------------------------------------------------------------------------------------------------------------------------------------
The error message shows 
ValueError: ('Error when checking model input: expected no data, but got:', array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32))
But when I commnet # tf_input and uncomment # keras_input
It work fine. How can I use #tf_input for this?

**Comment by brainnoise** [comment]
Input layer used without tensor arg ```inputs = Input(shape=(784,))``` creates a placeholder tensor internally. When you train a model using this input, you are always required to give a value for the placeholder tensor. In your code snippet, ```x=mnist_data.train.images``` is the value you give for that tensor. So, if you are looking to feed in input values you can use this approach and you will not need to use `tensor` argument.

The [tensor](https://keras.io/layers/core/#input) argument is used when there is an existing input tensor. When this is used, no placeholder will be created and no input value is expected. As you are passing input value ```x=mnist_data.train.images``` when using the tensor arg, you are seeing the error message `Error when checking model input: expected no data`. Example usage of tensor argument:
```
img = tf.convert_to_tensor(mnist_data.train.images, dtype=tf.float32)
inputs = Input(tensor=img)
x = Dense(128, activation='relu')(inputs)
x = Dense(128, activation='relu')(x)
preds = Dense(10, activation='softmax')(x)
model = Model(inputs=inputs, outputs=preds)
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(y=mnist_data.train.labels,epochs=1, batch_size=55000)
```

From what I understand it looks like the first method should be good for your use case. Hope this helps!

**Comment by ymcasky** [comment]
Thanks for your kindly reply.
It can train properly.
But even I change epochs from 1 to 100.
The acc still around 0.1...
I also want to feed batch by batch instead of whole 55000 data.
Do you have other suggestion? Thanks!

**Comment by brainnoise** [comment]
You can use fit_generator with Python data generators to train data in batches. Search for fit_generator [here](https://keras.io/models/sequential/). You can also refer this Keras [issue](https://github.com/keras-team/keras/issues/107).

```
inputs = Input(shape=(784,))
x = Dense(128, activation='relu', name='Boing')(inputs)
x = Dense(128, activation='relu', name='Achar')(x)
preds = Dense(10, activation='softmax', name='Paniyaram')(x)
model = Model(inputs=inputs, outputs=preds)
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit_generator(generator=training_generator, steps_per_epoch=steps_per_epoch, epochs=1000)
```

**Comment by ymcasky** [comment]
Thanks for your reply!!
Here is my code:

```
img_size_flat = 28*28
batch_size = 64

def gen(batch_size=32):
    while True:
        batch_data, batch_label = mnist_data.train.next_batch(batch_size)
        yield batch_data, batch_label   


inputs = Input(shape=(img_size_flat,))
x = Dense(128, activation='relu')(inputs)  # fully-connected layer with 128 units and ReLU activation
x = Dense(128, activation='relu')(x)
preds = Dense(10, activation='softmax')(x)  # output layer with 10 units and a softmax activation
model = Model(inputs=inputs, outputs=preds)
model.compile(optimizer='rmsprop',
               loss='categorical_crossentropy',
               metrics=['accuracy'])
model.fit_generator(gen(batch_size), steps_per_epoch=len(mnist_data.train.labels)//batch_size, epochs=2)

```

**Comment by ymcasky** [comment]
I have one more question in the following link:
https://github.com/tensorflow/tensorflow/issues/16721
I appreciate your help again!
