### ISSUE TITLE
Feature request: use padded_batch with tf.estimator.export.build_parsing_serving_input_receiver_fn

### ISSUE THREAD

**Issue by alltom** [tensorflow/tensorflow#16638]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.12.6
- **TensorFlow installed from (source or binary)**: I forget
- **TensorFlow version (use command below)**: 1.4
- **Python version**: 2.7.8
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
As far as I can tell, tf.estimator.export.build_parsing_serving_input_receiver_fn() doesn't allow you to control the way examples are batched. So if I have an Estimator that I've trained by using Dataset.padded_batch() in the input_fn, there doesn't seem to be a way for me to use that model with TensorFlow Serving.

### Source code / logs
N/A?

**Comment by alltom** [comment]
Whenever there's pre-processing work to be done like embedding variable-length features, is that usually done by pre-processing the data _before_ sending a predict request to TensorFlow Serving / Cloud ML Engine?

I filed this issue with the expectation that there should be some way to write a graph whose input is a batch of tf.strings (variable-length), but maybe that's not how it's meant to be done?

Also, I'm not sure what tensorflower is, but is it coming soon? :)

**Comment by martinwicke** [comment]
@sukritiramesh FYI

Serving will accept requests with any batch size and return results according to what the graph returns. Often, you will feed single examples, but there's no restriction on this.

`build_parsing_serving_input_receiver_fn` however is a utility for the most common case, and it does not give you control over batching. You'll have to write your own function returning a ServingInputReceiver to do that.

**Comment by alltom** [comment]
I accidentally came across more information that I'm including here for posterity:

tensorflow_model_server accepts a [BatchingParameters](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/servables/tensorflow/session_bundle_config.proto#L67) proto with a `bool pad_variable_length_inputs` parameter that might emulate Dataset.padded_batch() well enough. And if not, there's a `Int64Value max_batch_size` parameter that might disable batching if set to 1.

[Using SavedModel with Estimators](https://www.tensorflow.org/programmers_guide/saved_model#using_savedmodel_with_estimators) has more information about when/how to use build_parsing_serving_input_receiver_fn or write your own ServingInputReceiver.
