### ISSUE TITLE
Nightly debian CPU build fails during docker build 

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorflow#1663]
For example, see:
http://ci.tensorflow.org/view/Nightly/job/nightly-debian-cpu/28/console

The error happens during the step: RUN /install/install_deb_packages.sh

**Comment by mrry** [comment]
Is this still a problem? It looks like that particular nightly is passing now, so do we need to keep this issue open?

**Comment by jendap** [comment]
No, this is fixed.
