### ISSUE TITLE
Error while building Tensorflow model from bazel 

### ISSUE THREAD

**Issue by aditya478492** [tensorflow/tensorflow#16648]
INFO: From Linking tensorflow/libtensorflow_framework.so [for host]:
LINK : warning LNK4044: unrecognized option '/Wl,-soname,libtensorflow_framework.so'; ignored
LINK : warning LNK4044: unrecognized option '/pthread'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : warning LNK4044: unrecognized option '/lpthread'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : warning LNK4044: unrecognized option '/lpthread'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : warning LNK4044: unrecognized option '/ldl'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
   Creating library bazel-out/host/bin/tensorflow/libtensorflow_framework.ifso and object bazel-out/host/bin/tensorflow/libtensorflow_framework.exp
ERROR: C:/courses/tensorflow/tensorflow/cc/BUILD:422:1: Linking of rule '//tensorflow/cc:ops/array_ops_gen_cc' failed (Exit 1181)
LINK : warning LNK4044: unrecognized option '/pthread'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : fatal error LNK1181: cannot open input file 'tensorflow_framework.obj'
Target //tensorflow/contrib/android:libtensorflow_inference.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3434.951s, Critical Path: 365.14s
FAILED: Build did NOT complete successfully

Is LNK4044 warning related to c++ path, i've given VisualStudio.exe path while installing

**Comment by drpngx** [comment]
I'm not sure if this is supported just yet.

@gunan can we build the android contrib directory from Windows in bazel?

**Comment by gunan** [comment]
I am guessing probably not. I am sure the options for cross compilation on windows are different.
@meteorcloudy @andrewharp to confirm

**Comment by meteorcloudy** [comment]
@aditya478492 Can you provide more information?
Which target did you build? Can you build with `--verbose_failures` so that we can see what command failed exactly.

**Comment by aditya478492** [comment]
ERROR: C:/courses/tensorflow/tensorflow/cc/BUILD:422:1: Linking of rule '//tensorflow/cc:ops/array_ops_gen_cc' failed (Exit 1181): link.exe failed: error executing command
  cd C:/users/aditya/appdata/local/temp/_bazel_aditya/nmddefa1/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET TEMP=C:\Users\Aditya\AppData\Local\Temp
    SET TMP=C:\Users\Aditya\AppData\Local\Temp
    SET USE_LINKER=1
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/link.exe /nologo /OUT:bazel-out/host/bin/tensorflow/cc/ops/array_ops_gen_cc.exe tensorflow_framework /SUBSYSTEM:CONSOLE -pthread /MACHINE:X64 @bazel-out/host/bin/tensorflow/cc/ops/array_ops_gen_cc.exe-2.params /DEFAULTLIB:msvcrt.lib
LINK : warning LNK4044: unrecognized option '/pthread'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : fatal error LNK1181: cannot open input file 'tensorflow_framework.obj'
Target //tensorflow/contrib/android:libtensorflow_inference.so failed to build
INFO: Elapsed time: 398.641s, Critical Path: 150.53s
FAILED: Build did NOT complete successfully

i was building android:libtensorflow_interface

**Comment by meteorcloudy** [comment]
Hmm,, I don't think we are able to build android interface on Windows right now.

**Comment by andrewharp** [comment]
Windows builds of Android TF are not currently supported, but there are workarounds, e.g.: https://github.com/tensorflow/tensorflow/issues/6385#issuecomment-285208600

Otherwise I'd suggest just using the AAR as shown in the demo's build.gradle file, if possible.
