### ISSUE TITLE
can tf.estimator.Estimator's  parameters be modified by hand? 

### ISSUE THREAD

**Issue by buptzzl** [tensorflow/tensorflow#16646]
TF's  high level API  is very convenient to defined a new model. 
However, many DNN Machine Learning task has to reuse some old model's parameter to fill a new model and then  fine-tune it in new tasks. 
I have read the tf.estimator.Estimator'API  carefully, but cann't find any API to set It's parameters. Hope  TF developer  add this function to the high level API. 
Thank very much!

**Comment by drpngx** [comment]
Please describe into more details what you would like to do.

**Comment by buptzzl** [comment]
@drpngx  thanks for you attention!
I have use the tf.estimator.Estimator defined a group of models, and train a subset of them. 
After that, I want to use those trained model's Parameter to init the last un-trained model's parameter, and then start to train this last model. 
I find way's to get the older trained model's paramter by  tf.estimator.Estimator.get_variable_value(name),  but there is don't have a set var 's value's API to  init the last un-trainded model's Parameter Tensor by get_variable_value()'s Tensors.
 hope you can give me some advice about the  set var's value's API!

**Comment by drpngx** [comment]
You can use `tf.trainable_variables()` to get all the trainable variables in your graph, assuming that what you want. Then you can use `session.run` to retrieve their value if you want get the actual values.
You probably want to use `tf.variable_scope` to share variables.

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by martinwicke** [comment]
You should use init_from_checkpoint to set directly from the checkpoint. But as @drpngx said, the details are best resolved on StackOverflow.

**Comment by buptzzl** [comment]
@drpngx  When I used the lower level API for training,  tf.trainable_variables() is work.  But High level API's estimator use system defined Graph info and  tf.trainable_variables() doesn't work! 
For example, I have use the tf.estimator.Estimator defined a group of models,  and just test print the  tf.trainable_variables(), It just return empty list. The code is below: 
`    clf_ = tf.estimator.Estimator(model_fn=model_fn_wide2deep, params=param, model_dir=ckpt_dir)
    # try init parameters from other model.
    init_ops = [tf.global_variables_initializer(), tf.local_variables_initializer()]
    with tf.Session() as sess:
        sess.run(init_ops)
        print('traininig params: %r' % sess.run(tf.trainable_variables()))
        sys.exit(1)`

So, I think This way to change   tf.estimator.Estimator model's parameter doesn't work!  That why I supporse to add a Estimator.set_variable_value(name)  API. 
Hope you response! Thanks!

**Comment by buptzzl** [comment]
@martinwicke  Thanks for you advice. My problem is there are many diffent ckpt files to load for initial the last model's parameters, and what's more,   tf.estimator.Estimator trainable variables can get by hand recently! So, I think you advice doesn't work!  Hope you response! Thanks!

**Comment by kopas** [comment]
as I did not found full answer in other places (aka [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow)) and this issue appears first in search results 

If you want to update values on Estimator (high level API), you can use this code to do it

```python
# Restore, Update, Save
# tested only on tesorflow 1.4
import tensorflow as tf
tf.reset_default_graph()

CHECKPOINT_DIR = 'CHECKPOIN_DIR' # for example '/my_checkpoints' as in tf.estimator.LinearClassifier(model_dir='/my_checkpoints'...
checkpoint = tf.train.get_checkpoint_state(CHECKPOINT_DIR)

with tf.Session() as sess:
    saver = tf.train.import_meta_graph(checkpoint.model_checkpoint_path + '.meta')
    saver.restore(sess, checkpoint.model_checkpoint_path)

    # just to check all variables values
    # sess.run(tf.all_variables())

    # get your variable
    KEY = 'linear/linear_model/0/weights/part_0:0'# for tf.estimator.LinearClassifier first weight
    var_wights_0 = [v for v in tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES) if v.name == KEY][0]
    sess.run(var_wights_0)

    # your update operation
    var_wights_0_updated = var_wights_0.assign(var_wights_0 - 100)
    sess.run(var_wights_0_updated)

    # you can check that value is updated
    # sess.run(tf.all_variables())

    # this saves updated values to last checkpoint saved by estimator
    saver.save(sess, checkpoint.model_checkpoint_path)
```

**Comment by SumNeuron** [comment]
@kopas that looks promising. Wondering if you could take a look at this.

I have a model from `tf.estimator.BestExporter` and what I would like to do is read in the graph, update the weights, evaluate with different weights. If I can evaluate with the new weights saving isn't strictly required but would also be nice.

Currently I got some stuff like this

```python

def load_estimator_graph(export_dir:str)->None:
    '''Solves import issues when using tf.estimator.(Best)Exporter for saving
    models rather than using the last checkpoint.

    Arguments:
        export_dir (str): the full path to exported tf.estimator model
    Returns:
        None
    '''
    with tf.Session(graph=tf.Graph()) as sess:
        meta_graph   = tf.saved_model.loader.load(sess, ['serve'], export_dir)
    with tf.Session() as sess:
        loaded_graph = tf.train.import_meta_graph(meta_graph)

def lazy_fetch_variable_values(variable_names:list)->dict:
    '''
    Notes:
        "lazy" refers to:
            1. the use of `tf.initialize_all_variables()` to ensure
                variables have values
            2. the use of `tf.trainable_variables()` to search the likely
                releveant values

    Arguments:
        variable_names (list): list of variable names (str) to retrieve from the
            default tensorflow graph

    Returns:
        variables (dict): key:value of the variables and the values as pythonic
            data types.
    '''
    init_op = tf.initialize_all_variables()
    variables = {}
    with tf.Session() as sess:
        sess.run(init_op)

        tvars = tf.trainable_variables()
        tvars_vals = sess.run(tvars)

        for var, val in zip(tvars, tvars_vals):
            if var.name in variable_names:
                variables[var.name] = val
    return variables


def lazy_set_variable_values(variables_to_set:dict):
    '''
    Arguments:
        variables_to_set (dict): variable_name, variable_value pairs for which
            to be updated in the graph
    '''
    init_op = tf.initialize_all_variables()
    with tf.Session() as sess:
        sess.run(init_op)
        tf_global_vars = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES)

        for var_to_find, val_to_set in variables_to_set.items():
            var = [v for v in tf_global_vars if v.name == var_to_find][0]
            sess.run(var)

            var = var.assign(val_to_set)
            sess.run(var)
```

and then call something like this:

```python
load_estimator_graph(best_exported_model_dir)
weights = lazy_fetch_variable_values(['some_layer/kernel:0'])
new_weights = np.copy(weights)
new_weights = 0
lazy_set_varriable_values({'some_layer/kernel:0':new_weights})


with tf.Session() as session:
    sess.run(tf.initialize_all_variables())
    saver = tf.train.Saver()
    saver.save(sess, os.path.join(best_exported_model_dir, '..', 'best_updated'))
```

then 

```python
predict_fn = predictor.from_saved_model(best_exported_model_dir)
```

works but

```python
est = tf.estimator.Estimator(
    model_fn=model_fn,
    model_dir=os.path.join(best_exported_model_dir, '..', 'best_updated'),
    config=run_config, # same as when ran
    params = params, # same as when ran
)

eval_fn = lambda : input_fn(mode='eval')

est.evaluate(eval_fn)
```

yield the error

```
ValueError Input 0 of layer some_layer is incompatible with the layer: : expected min_ndim=2, found ndim=1. Full shape received: [an_integer]
```

where in the above code

```python
weights.shape[0] == new_weights.shape[0] == an_integer
```

Really bewildered and would appreciate help

**Comment by kopas** [comment]
@SumNeuron I did not verified your code, but error seems in this place
`
...
new_weights = 0
...
`
You assign single number, but your model expects vector (0,0)

**Comment by SumNeuron** [comment]
@kopas 

sorry for not clarifying with inline comments.

`new_weights` was a copy of the old weights (which `tf` interprets as a `np.ndarray`). So rather than copy-pasting a matrix or anything complex, `new_weights = 0`, just sets _element-wise_ the `np.ndarray` (tensor) to 0. 

Perhaps better pseudo code would have been:

```
weights = lazy_fetch_variable_values(['some_layer/kernel:0'])
new_weights = modify_weights(weights) # returns a tensor with same shape as weights, but may have different values per element
```

**Comment by SumNeuron** [comment]
@kopas for sanity I tried changing how I update to the following:

```python
export_dir = # directory from tf.estimator.(Best)Exporter
out_dir = # dir to save to

tf.reset_default_graph()
with tf.Session() as sess:
    meta_graph = tf.saved_model.loader.load(sess, ['serve'], export_dir)
    saver = tf.train.import_meta_graph(meta_graph)
#     saver.restore(sess, os.path.join(export_dir, 'saved_model.pb'))

    # just to check all variables values
#     sess.run(tf.all_variables())
    layer_weight_names = [
       'some_layer/kernel:0'
    ]
    weight_matrices_ref = [
        [v for v in tf.trainable_variables() if v.name == layer_weight_name][0]
        for layer_weight_name in layer_weight_names
    ]
    weight_matrices = [sess.run(wm) for wm in weight_matrices_ref]
    updated_weights  = update_weights(weight_matrices)
        
    # your update operation
    updated_weight_matrices = [weight_matrices_ref[i].assign(updated_weights[i]) for i in range(len(updated_weights))]
    for wm in updated_weight_matrices:
        sess.run(wm)

#     # you can check that value is updated
#     # sess.run(tf.all_variables())

    # this saves updated values to last checkpoint saved by estimator
    saver.save(sess, out_dir)

```

and this gives the same error.

Notes:
-  the `update_weights` returns a `np.ndarray` of the same shape as passed matrix. 
- this is reading in a model from `BestExporter` (which is different from a checkpoint) and then I would like to save it to the same format if possible, but that seems to be asking too much. So if I can export it as a checkpoint, that also works, as long as I can restore an estimator to use for eval.

**Comment by kopas** [comment]
@SumNeuron 
Maybe this issues is with this line:
`#     saver.restore(sess, os.path.join(export_dir, 'saved_model.pb'))`
You do not restore state from saved checkpoint, maybe this somehow interferes... my experience with high level api is limited. 
You need also check if '(Best)Exporter' supports same checkpoint system as 'LinearClassifier'.

Still,
can you provide some debug info?
```
# get your variable
KEY = 'linear/linear_model/0/weights/part_0:0'# for tf.estimator.LinearClassifier first weight
var_wights_0 = [v for v in tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES) if v.name == KEY][0]
# this should print result
sess.run(var_wights_0)
```

Print for your key 'some_layer/kernel:0' or for key that gives error. Print also variable that you are setting.
Can you do it?

The error says clearly, that on some update you try to set number, but vector expected. Maybe it's internal high level api error, then you can try opening new issue about it and I will not be able to help you.

**Comment by SumNeuron** [comment]
@kopas  I really appreciate you taking a look. Since estimators are on the way out (although technically around in 2.0) many are not so willing to help those stuck working with them.


# Digging in the Source Code
Some context about `BestExporter`. It just calls the estimator's `export_savedmodel`, which can be seen starting at [line 808](https://github.com/tensorflow/estimator/blob/33e13754b0deebe7cc5006c49c53d246b6ff1dec/tensorflow_estimator/python/estimator/estimator.py#L808) in the source code. It seems to use `saved_model_builder` and another function `_add_meta_graph_for_mode(...)` defined on [line 879](https://github.com/tensorflow/estimator/blob/33e13754b0deebe7cc5006c49c53d246b6ff1dec/tensorflow_estimator/python/estimator/estimator.py#L879). 

Looking at this  `_export_all_saved_models(...)` lines 815 to 826, we see that it looks for a `checkpoint`  to use as the model to export. However it is important to note that the exported model had a different structure than `checkpoints`. Namely, you have a directory like:

```
<timestamp>/
    - variables/
        - variables.data-00000-of-00001
        - variables.index
    - saved_model.pb
```

There is a class under `tf.contrib.predict` for loading this model  [`SavedModelPredictor`](https://github.com/tensorflow/tensorflow/blob/6c7c3bb0f3563e8a147935597617cf3d052c7852/tensorflow/contrib/predictor/saved_model_predictor.py). [Lines 149 to 164](https://github.com/tensorflow/tensorflow/blob/6c7c3bb0f3563e8a147935597617cf3d052c7852/tensorflow/contrib/predictor/saved_model_predictor.py#L149) uses something like `loader.load(self._session, tags.split(','), export_dir)` to get the model back.

# Requested Debug Info

```python
export_dir = # where my model is saved (not checkpoint, but BestExporter version)
out_dir =      # where I want to save my model

tf.reset_default_graph()
with tf.Session() as sess:
    meta_graph = tf.saved_model.loader.load(sess, ['serve'], export_dir)
    saver = tf.train.import_meta_graph(meta_graph)
#     saver.restore(sess, os.path.join(export_dir, 'saved_model.pb'))
#     # just to check all variables values
#     sess.run(tf.all_variables())
    layer_weight_names = [
        'input_layer/kernel:0', 
    ]
    weight_matrices_ref = [
        [v for v in tf.trainable_variables() if v.name == layer_weight_name][0]
        for layer_weight_name in layer_weight_names
    ]
    weight_matrices = [sess.run(wm) for wm in weight_matrices_ref]
    print(layer_weight_names[0], 'has shape', weight_matrices[0].shape, weight_matrices[0])
    updated_weights  = update_weights(weight_matrices)
    print(layer_weight_names[0], 'updated', 'has shape', updated_weights[0].shape, updated_weights[0])
    
#     # your update operation
    updated_weight_matrices = [weight_matrices_ref[i].assign(updated_weights[i]) for i in range(len(updated_weights))]
    for wm in updated_weight_matrices:
        sess.run(wm)

#     # you can check that value is updated
#     # sess.run(tf.all_variables())

#     # this saves updated values to last checkpoint saved by estimator
    saver.save(sess, out_dir)
```

prints out

```
INFO:tensorflow:Restoring parameters from <export_dir>/variables/variables
input_layer/kernel:0 has shape (784, 1000) [[ 0.02498415 -0.03715022  0.00038124 ... -0.01632504  0.01010246
  -0.0130309 ]
 [ 0.01805093  0.0504102   0.03946984 ... -0.01649825  0.0529456
   0.0090284 ]
 [-0.05145188 -0.00748302  0.02208934 ... -0.01180375 -0.05152242
   0.02814269]
 ...
 [ 0.02663752 -0.05750908 -0.05161621 ...  0.04808073 -0.03680649
  -0.02869198]
 [ 0.03978344  0.03805095  0.02332595 ...  0.04606824  0.01374551
   0.04582741]
 [ 0.0301908   0.04157476 -0.05609504 ...  0.00530757 -0.03418655
   0.02162087]]
input_layer/kernel:0 updated has shape (784, 1000) [[ 0.02498415  0.          0.00038124 ... -0.01632504  0.01010246
  -0.0130309 ]
 [ 0.01805093  0.0504102   0.03946984 ... -0.01649825  0.0529456
   0.0090284 ]
 [ 0.         -0.00748302  0.02208934 ... -0.01180375  0.
   0.02814269]
 ...
 [ 0.02663752  0.          0.         ...  0.04808073  0.
  -0.02869198]
 [ 0.03978344  0.03805095  0.02332595 ...  0.04606824  0.01374551
   0.04582741]
 [ 0.0301908   0.04157476  0.         ...  0.00530757 -0.03418655
   0.02162087]]

```

**Comment by SumNeuron** [comment]
@kopas  I have got a status update. Error seemed to be system dependent. uninstall / reinstall TF and now the code above lets me read and write models....

**however**,  what is being written (or possibly read / initialized) is incorrect!


```python
# helper function
def save_session(export_dir:str, model_name:str='estimator')->None:
    '''
    Saves the session to the desired directory

    Notes:
        Will produce the following directory and files:
            <export_dir>/
                checkpoint
                <model_name>.data-<ckpt-num>-of-<max-ckpt>
                <model_name>.index
                <model_name>.meta
    Arguments:
        export_dir (str): directory where model will be exported
        model_name (str): name of the model

    Returns:
        None
    '''
    if not os.path.isdir(export_dir): os.makedirs(export_dir)
    with tf.Session() as sess:
        sess.run(tf.initialize_all_variables())
        saver = tf.train.Saver()
        saver.save(sess, os.path.join(export_dir, model_name))
```

So now I can read an exported model,  save it as a checkpoint, and reload it with an estimator to use `estimator.evaluate(...)`. However,it seems my save function / pipeline is messed up.

Below I read in an exported model (using functions posted above) and then just save to a new directory. I then read in the "clone" and the weight matrix has changed! 

```python
import copy, os

final_model_dir = # estimator.export_finalmodel(...), acc > 90%
final_model_clone_dir = os.path.join(final_model_dir, '..', 'final_model_clone')

load_estimator_graph(final_model_dir)
weights = lazy_fetch_variable_values(['input_layer/kernel:0',])
weight_matrices = list(weights.values())

original_weight_matrices = copy.deepcopy(weight_matrices) # <--- keep this for later

# here I would, overwrite with the same value, but I will do you one better
# I will not alter the value at all!
# lazy_set_variable_values(dict(zip(list(weights.keys()), original_weight_matrices)))

# did nothing but load graph, extract values, but did NOT assign new values
save_session(final_model_clone_dir)

# load the clone and see what changed
load_estimator_graph(final_model_clone_dir)
weights = lazy_fetch_variable_values(['input_layer/kernel:0',])
weight_matrices = list(weights.values())

(weight_matrices[0] == original_weight_matrices[0]) 
# returns [[False, ..., False], ..., [False, ..., Flalse]
```

**Comment by SumNeuron** [comment]
@kopas  update

So I thought maybe all the use of:

```python
def foo(...):
    with tf.Session() as sess:
        # do something
```

helper functions might be the cause of the issue, so I managed together all those functions from above to this:

```python
model_dir = # <saved_final_model>
export_dir = # <new_model>
if not os.path.isdir(export_dir): os.makedirs(export_dir)

weight_matrices_names_to_update = ["input_layer/kernel:0",] # same gist as above


tf.reset_default_graph()
init_op = tf.initialize_all_variables()
with tf.Session(graph=tf.Graph()) as sess:

    # fetch graph
    meta_graph = tf.saved_model.loader.load(sess, ['serve'], model_dir)

    # load graph
    loaded_graph = tf.train.import_meta_graph(meta_graph)

    # sess.run(init_op) # <-- throws error

    # refs to variables to change
    weight_matrices_ref = [
        [v for v in tf.trainable_variables() if v.name == layer_weight_name][0]
        for layer_weight_name in weight_matrices_names_to_update
    ]

    # actual values of the variables
    weight_matrices = [sess.run(wm) for wm in weight_matrices_ref]

    # update weights
    updated_weights = update_weights(weight_matrices, percent, method)

    # update operations
    updated_weight_matrices = [
        weight_matrices_ref[i].assign(updated_weights[i])
        for i in range(len(updated_weights))
    ]

    # have session assign new values
    for wm in updated_weight_matrices:
        sess.run(wm)


    loaded_graph.save(sess, os.path.join(export_dir, 'estimator'))

```

Noteworthy, is that this this time:

- if `update_weights` returns identical matrices to what went in, I get the correct model exported
- if `update_weights` returns anything else, I seem to get just randomly initialized weight matrices

**Comment by SumNeuron** [comment]
@drpngx and @martinwicke  perhaps consider reopening the issue?

**Comment by martinwicke** [comment]
@SumNeuron, I think your code saves the graph, but not the variables. I do not think your graph needs saving, you are not modifying it. But the checkpoint must be saved -- it is what contains the variable values.

In fact, you shouldn't have to load the graph at all -- you only need the checkpoint, and you only need to write back the updated checkpoint.

**Comment by SumNeuron** [comment]
@martinwicke I am a bit confused by that response?

Not savlng the variables would explain why it appears upon making a new `tf.estimator.Estimator` instance (with `warm_start`), the weights appear to be random / just initialized (except in the case where I assign the weights to their current value).



From your own [answer](https://stackoverflow.com/a/43531616/5623899) on StackOverflow (`SavedModel` vs `Graph`) you note that `SavedModel`'s are more comprehensive and include a checkpoint. 

If one is using a `tf.estimator.BestExporter` in their `tf.estimator.Estimator`, then _which_ checkpoint (to my knowledge) is not immediately obvious from the `BestExporter` unless in the exported directory:

```
<timestamp>/
    - variables/
        - variables.data-<#####>-of-<#####>
        - variables.index
    - saved_model.pb
```

`<#####>-of-<#####>` corresponds to the `tf.estimator.Estimator`'s `model_dir`'s files `model.ckpt-<#####>-of-<#####>`

In addition, I am preferential to using or updating the `SavedModel` as:
1. to reuse the checkpoint in the future, the run-time parameters must be carried along side the `ckpt` so that a new instance of the `tf.estimator.Estimator` can be made (utilizing, `warm_start_from`)
2.  `tf.contrib.predictor` works well with the `SavedModel` and does not require knowing the run-time parameters.


So I guess then, how would I do what you suggest above? or alternatively, how can I just read in `variables.data-<#####>-of-<#####>` update the variables and then I can just clone the `SavedModel` directory with the new `variables.data-<#####>-of-<#####>` file?

**Comment by SumNeuron** [comment]
@kopas it seems your approach using `get_checkpoint_state` does not allow one to specify which checkpoint to use in the checkpoint directory (see [TensorFlow v1.10+: get_checkpoint_state what is the expected value for latest_filename for Estimator API to specify a particular checkpoint](https://stackoverflow.com/questions/56786829/tensorflow-v1-10-get-checkpoint-state-what-is-the-expected-value-for-latest-fi?noredirect=1#comment100128338_56786829) for more details / relevant source code)

**Comment by SumNeuron** [comment]
@martinwicke just for a "sanity" check, I copy-pasted @kopas 's solution from [above](https://github.com/tensorflow/tensorflow/issues/16646#issuecomment-384935839) (updating weights according to my previous [comments](https://github.com/tensorflow/tensorflow/issues/16646#issuecomment-504092705)) and it appears that the same issue persists

namely:
- if I set a weight matrix to the same value it originally had, things remain the same (same acc, etc)
- if I set a weight matrix to any other value (e.g. all 0, or just plus 0.0000000000001 to all values), then when inspecting the matrices from these exported, modified checkpoints, the values when reloaded are not the same.

Now to clarify, when I try to evaluate the re-exported checkpoint (in a new directory) I do so via:

```python
est = tf.estimator.Estimator(
        model_fn  = model_fn,
        model_dir = updated_dir, # <--- where I saved the model (not same location or same directory as originally used)
        config    = tf.estimator.RunConfig(**config['RunConfig']), # same as original run-time
        params    = config, # same as original run-time
        warm_start_from = updated_dir # <--- should start with updated values?
    )
    eval_fn = lambda : input_fn({**config, 'mode':'eval'})
```

**Comment by SumNeuron** [comment]
@martinwicke I really don't know how to precede on debugging this myself. I already went through the docs and source code as well as a series of trials / errors. So I would continue to appreciate your guidance, especially as the previously listed approach by @kopas does not seem to work any more, or at least in this context
