### ISSUE TITLE
Tensorflow on banana-pi m64

### ISSUE THREAD

**Issue by dntwrd** [tensorflow/tensorflow#16657]
How to install TF on banana m64? OS: Linux bpi-iot-ros-ai 3.10.105-BPI-M64-Kernel 

When i trying install i have an error

> tensorflow-1.5.0-cp34-none-any.whl is not a supported wheel on this platform.

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
