### ISSUE TITLE
Bazel version comparison fails with bazel 0.10.0

### ISSUE THREAD

**Issue by jendrikjoe** [tensorflow/tensorflow#16654]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, just commented 6 lines in the bzl files out
- **OS Platform and Distribution**: 16.04 on Jetson TX2
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.5
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.10.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: TX2 GPU, 5GB (not sure)
- **Exact command to reproduce**: bazel build -c opt --local_resources 3072,4.0,1.0 --verbose_failures --config=cuda //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
I cannot build tensorflow using bazel 0.10.0. It seems like the version checks in repositories.bzl and wokspace.bzl fail. Commenting them out solves the issue, even though I know that is no persistent solution. I think it is simply that bazel thinks that 0.10.0 is smaller 0.5.4 due to its string comparison, but I am no bazel expert.

### Source code / logs
ERROR: /home/nvidia/git/tensorflow/WORKSPACE:15:1: Traceback (most recent call last):
	File "/home/nvidia/git/tensorflow/WORKSPACE", line 15
		closure_repositories()
	File "/home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/external/io_bazel_rules_closure/closure/repositories.bzl", line 69, in closure_repositories
		_check_bazel_version("Closure Rules", "0.4.5")
	File "/home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/external/io_bazel_rules_closure/closure/repositories.bzl", line 172, in _check_bazel_version
		fail(("%s requires Bazel >=%s but was...)))
Closure Rules requires Bazel >=0.4.5 but was 0.10.0- (@non-git)
ERROR: Error evaluating WORKSPACE file
ERROR: /home/nvidia/git/tensorflow/WORKSPACE:41:1: Traceback (most recent call last):
	File "/home/nvidia/git/tensorflow/WORKSPACE", line 41
		tf_workspace()
	File "/home/nvidia/git/tensorflow/tensorflow/workspace.bzl", line 48, in tf_workspace
		check_version("0.5.4")
	File "/home/nvidia/git/tensorflow/tensorflow/workspace.bzl", line 38, in check_version
		fail("\nCurrent Bazel version is {}, ...))

Current Bazel version is 0.10.0- (@non-git), expected at least 0.5.4
ERROR: Error evaluating WORKSPACE file
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'external': Package 'external' contains errors
WARNING: Target pattern parsing failed.
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 3.145s
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by meteorcloudy** [comment]
Can you build TensorFlow from HEAD?
Or cherry-pick this commit to fix it: https://github.com/tensorflow/tensorflow/commit/3f57956725b553d196974c9ad31badeb3eabf8bb

**Comment by jendrikjoe** [comment]
Thanks for the speedy reply! :) I will try it on the other Jetson and will post it when I can confirm anything :)

**Comment by jendrikjoe** [comment]
Building HEAD works :+1:

**Comment by Dapid** [comment]
In r1.5 `check_version` from `tensorflow/workspace.bzl` still fails.

**Comment by RoboEvangelist** [comment]
This is a hilarious bug

**Comment by meteorcloudy** [comment]
@gunan Is there any chance to cherry-pick 3f57956 into r1.5?

**Comment by Dapid** [comment]
@meteorcloudy `git cherry-pick  3f57956`

I also had to change:

```
diff --git a/tensorflow/workspace.bzl b/tensorflow/workspace.bzl
index 94b1930db2..b550e9d3bb 100644
--- a/tensorflow/workspace.bzl
+++ b/tensorflow/workspace.bzl
@@ -19,7 +19,9 @@ def _parse_bazel_version(bazel_version):
   # Turn "release" into a tuple of strings
   version_tuple = ()
   for number in parts[0].split("."):
-    version_tuple += (str(number),)
+    n = str(number)
+    n = ''.join(('0' * (3 - len(n)), n)) #bzl doesn't support format?
+    version_tuple += (n,)
   return version_tuple
 
 # Check that a specific bazel version is being used.
```

**Comment by subzerofun** [comment]
Hope someone can help me out here – i'm bound to TF 1.4 since only that version works (for now) on macOS (I know macOS isn't officially supported anymore, but it works fine if you follow certain instructions).

I manually fixed the WORKSPACE file with the mentioned cherry-pick, but i still get this error:
```Current Bazel version is 0.10.0-homebrew, expected at least 0.5.4```

**Do i also have to change any other files?** Would love to switch to TF 1.5, but compiling still fails. Installed TF 1.4 a month ago (but just for python2, now i need it for python3 too) and everything works fine there.

**Comment by youpicontini** [comment]
I definitely dont know much about bazel but found an easy fix: 

open the.bzl files generating the error, repositories.bzl and workspace.bzl
change all the `check_version("...")` to `check_version("0.10.0")` then run

`bazel build --config=opt --incompatible_load_argument_is_label=false --incompatible_disallow_uncalled_set_constructor=false //tensorflow/tools/pip_package:build_pip_package`

worked for me, hope it helps

**Comment by hackbink** [comment]
`
# Parse the bazel version string from `native.bazel_version`.
def _parse_bazel_version(bazel_version):
  # Remove commit from version.
  version = bazel_version.split(" ", 1)[0]

  # Split into (release, date) parts and only return the release
  # as a tuple of integers.
  parts = version.split("-", 1)

  # Turn "release" into a tuple of strings
  version_tuple = ()
  for number in parts[0].split("."):
    version_tuple += (str(number),)
  return version_tuple


print ('{}'.format(_parse_bazel_version('0.5.4')))
print ('{}'.format(_parse_bazel_version('0.10.0')))

print (_parse_bazel_version('0.5.4') <= _parse_bazel_version('0.10.0'))
`

`
('0', '5', '4')
('0', '10', '0')
False
`

Maybe you want to remove str conversion and just return tuple of integers, from _parse_bazel_version().

**Comment by hackbink** [comment]
You may want to return tuple of integers from _parse_bazel_version(), instead of tuple of strings.

**Comment by YURIJTJ** [comment]
@jendrikjoe what does that mean "build TensorFlow from HEAD" ?what's the specific procedure?

**Comment by jendrikjoe** [comment]
@YURIJTJ instead of git checkout r1.5 you do git checkout HEAD and tehn follow the rest of the build instructions :)

**Comment by lifefeel** [comment]
I think it is version representation bug of bazel. (0.10.0-) It should be removed hypen.
```
nvidia@tegra-ubuntu:~$ bazel version
..............................................
Build label: 0.10.0- (@non-git)
Build target: bazel-out/arm-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Apr 26 21:36:52 +50060 (1517583937012)
Build timestamp: 1517583937012
Build timestamp as int: 1517583937012
```
I changed the version checking code of Tensorflow then compiled it successfully.

change this file,
`"/home/nvidia/.cache/bazel/_bazel_nvidia/01c445c7b00bca0241913a79fcd99718/external/io_bazel_rules_closure/closure/repositories.bzl", line 69, in closure_repositories`

```
_check_bazel_version("Closure Rules", "0.4.5")
```
to
```
_check_bazel_version("Closure Rules", "0.10.0-")
```

**Comment by YURIJTJ** [comment]
I just skip the 'git checkout' skip completely and that works.
Thx~

**Comment by fgallaire** [comment]
Same issue with Bazel 0.11.0
``Current Bazel version is 0.11.0, expected at least 0.5.4``

**Comment by fgallaire** [comment]
Brazel is a joke, why use this sh** ?

**Comment by ningxia** [comment]
@fgallaire 
I am building v1.5 against CUDA8.0, besides changing repositories.bzl file mentioned by @lifefeel    tensorflow/workspace.bzl, I also change tensorflow/workspace.bzl similarly to "0.11.0-". It's compiling.

**Comment by theyusufyildiz** [comment]
WTF ? IntelliJ throws following error:

```
Closure Rules requires Bazel >=0.4.5 but was 0.11.0-homebrew.
```

**Comment by ewilderj** [comment]
Please keep conversation civil in this issue, per our code of conduct. I've edited out the swearing: help us keep TensorFlow a welcoming environment.

**Comment by Tvde1** [comment]
So there is still no fix? I am unable to build any tensorflow version.

**Comment by ningxia** [comment]
@Tvde1 I manged to build TF 1.5 against CUDA8.0 and cuDNN 6.0.

**Comment by jendrikjoe** [comment]
@Tvde1 building HEAD should work, at least it did for me.
Otherwise ‘git cherry-pick 6fcfab770c2672e2250e0f5686b9545d99eb7b2b‘ should solve the issue 😊

**Comment by Tvde1** [comment]
It warns me that the commit is empty. And still after running `configure`, bazel can't load the `external` package.

**Comment by gunan** [comment]
after all the updates, could you make sure to run `bazel clean --expunge`
There may be some leftover files that are breaking your builds.

We are working on cherrypicking the fixes to 1.5 and some older releases.

**Comment by Tvde1** [comment]
I cleaned it with the `--expunge` flag and it's building right now!

**Comment by aaronpenne** [comment]
For those of us that are stuck using TensorFlow 1.4, the fix is simple. There are two files that need to be edited, both have lines that need to be changed from `version_tuple += (str(number),)` to `version_tuple += (int(number),)`. 

The change is needed here:

- line 184 of /private/.../closure/repositories.bzl
- line 39 of /Users/.../tensorflow/workspace.bzl

As others have said, the string comparison used in these lines fails with double digits. An integer comparison here would not fail. For example, `('0', '4', '5') > ('0', '11', '1')` will return `False`. However, `(0, 4, 5) > (0, 11, 1)` will return `True`. 

Works for me installing TensorFlow v1.4 on my MacBook Pro running macOS High Sierra v10.13.3 when following these instructions: http://paolino.me/tutorial/tensorflow/machine-learning/deep-learning/gpu/2017/11/18/installing-tensorflow-1.4.0-macos-cuda/

**Comment by ranka47** [comment]
Hi 
I changed the `str` to `int` as suggested above. However, it seems to be encountering another problem. 
**Tensorflow branch**: `r1.4`
**Bazel Version**: `0.12.0`

Following is the error I am facing: 
```
ERROR: /home/hadoop/.cache/bazel/_bazel_hadoop/c347cef6a9a3bcd6c02d65a5feb3f818/external/jpeg/BUILD:122:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:
@jpeg//:k8
@jpeg//:armeabi-v7a
Multiple matches are not allowed unless one is unambiguously more specialized.
ERROR: Analysis of target '//tensorflow:libtensorflow.so' failed; build aborted: 

/home/hadoop/.cache/bazel/_bazel_hadoop/c347cef6a9a3bcd6c02d65a5feb3f818/external/jpeg/BUILD:122:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:
@jpeg//:k8
@jpeg//:armeabi-v7a
Multiple matches are not allowed unless one is unambiguously more specialized.
INFO: Elapsed time: 0.209s
FAILED: Build did NOT complete successfully (7 packages loaded)
    currently loading: @protobuf_archive// ... (2 packages)
```

**Comment by gunan** [comment]
I think we did not fix this in older branches. Is there a reason for using 1.4, instead of master or 1.7 or 1.8?

**Comment by naji-s** [comment]
@gunan: Yes. On my cluster there is no cuda-9 which makes using 1.5+ impossible...

**Comment by Dapid** [comment]
@naji-s you can probably ask the administrators to install a more modern version of cuda. In my experience, they are usually accommodating.

**Comment by pauldelmusica** [comment]
> @YURIJTJ instead of git checkout r1.5 you do git checkout HEAD and tehn follow the rest of the build instructions :)

What is HEAD? Between SHOULDERS or between LEGS?
