### ISSUE TITLE
There is no log10 function in tensorflow, only the loge exist.

### ISSUE THREAD

**Issue by meanmee** [tensorflow/tensorflow#1666]

**Comment by keveman** [comment]
`log10` can be constructed by composing existing TensorFlow operations, as below : 

    def log10(x):
      numerator = tf.log(x)
      denominator = tf.log(tf.constant(10, dtype=numerator.dtype))
      return numerator / denominator

Closing this issue as we don't plan to support this natively.

**Comment by petered** [comment]
log10 and log2 are pretty common things to use, it'd be nice to have them (and would help to match the numpy api)

**Comment by carlthome** [comment]
```log(x, base)``` :+1:

**Comment by filipre** [comment]
Just out of curiosity: Would you lose a lot of performance if someone implements `base` as an optional attribute?

**Comment by ntakouris** [comment]
> Just out of curiosity: Would you lose a lot of performance if someone implements `base` as an optional attribute?

No. It would get compiled as a tf.function the first time it runs with said base.
