### ISSUE TITLE
Current Bazel version is 0.10.0, expected at least 0.5.4

### ISSUE THREAD

**Issue by jitoledo** [tensorflow/tensorflow#16662]
I get this error message when trying to build from source (r1.5) with the new bazel version published today.

Current Bazel version is 0.10.0, expected at least 0.5.4

I guess the version check is wrong.

**Comment by imsheridan** [comment]
@jitoledo Seems cannot repro this issue in Ubuntu from my side

**Comment by jitoledo** [comment]
I downloaded everything a couple of hours ago. Bazel 0.10.0 was published today. I am using ubuntu 14.04

`(venv) jitoledo@CVC203:~/install_tensorflow_sources/tensorflow$ bazel build
ERROR: /home/jitoledo/install_tensorflow_sources/tensorflow/WORKSPACE:15:1: Traceback (most recent call last):
        File "/home/jitoledo/install_tensorflow_sources/tensorflow/WORKSPACE", line 15
                closure_repositories()
        File "/home/jitoledo/.cache/bazel/_bazel_jitoledo/29f20a808e018d60d9e350b4366f4703/external/io_bazel_rules_closure/closure/repositories.bzl", line 69, in closure_repositories
                _check_bazel_version("Closure Rules", "0.4.5")
        File "/home/jitoledo/.cache/bazel/_bazel_jitoledo/29f20a808e018d60d9e350b4366f4703/external/io_bazel_rules_closure/closure/repositories.bzl", line 172, in _check_bazel_version
                fail(("%s requires Bazel >=%s but was...)))
Closure Rules requires Bazel >=0.4.5 but was 0.10.0
ERROR: Error evaluating WORKSPACE file
ERROR: /home/jitoledo/install_tensorflow_sources/tensorflow/WORKSPACE:41:1: Traceback (most recent call last):
        File "/home/jitoledo/install_tensorflow_sources/tensorflow/WORKSPACE", line 41
                tf_workspace()
        File "/home/jitoledo/install_tensorflow_sources/tensorflow/tensorflow/workspace.bzl", line 48, in tf_workspace
                check_version("0.5.4")
        File "/home/jitoledo/install_tensorflow_sources/tensorflow/tensorflow/workspace.bzl", line 38, in check_version
                fail("\nCurrent Bazel version is {}, ...))

Current Bazel version is 0.10.0, expected at least 0.5.4
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.127s
FAILED: Build did NOT complete successfully (0 packages loaded)
(venv) jitoledo@CVC203:~/install_tensorflow_sources/tensorflow$
`

**Comment by imsheridan** [comment]
@jitoledo It seems you're not using the latest master source branch right?

**Comment by jitoledo** [comment]
According to instructions on  https://www.tensorflow.org/install/install_sources
I did:
`git checkout Branch # where Branch is the desired branch`
For branch r1.5 (which I thought is the current release version). Isn't it?

**Comment by jitoledo** [comment]
I just switched to master branch and it  seems to work (still building). I just wanted to install an updated version of tensorflow.
I tried with pip and it downloaded a version 1.5 but required cuda 9 and  I didn't to update to cuda9.1 (which would require updating ubuntu version too).

**Comment by jitoledo** [comment]
It works.

**Comment by YURIJTJ** [comment]
@jitoledo  just:
git checkout r1.5 
is that ok?

**Comment by YURIJTJ** [comment]
I just switched to v1.5.0 but it doesn't work .Same bazel mistake as before.

**Comment by YURIJTJ** [comment]
@jitoledo  That works, thx.

**Comment by kevinashaw** [comment]
So by "skip the checkout step" I infer that we not checkout TF1.5 and instead work at HEAD?  I think that is TF1.6rc1.  We would prefer not to run on a release-candidate.  Or is that our only option so far.
