### ISSUE TITLE
Tensorflow 1.5: failed to use tf.keras.applications.MobileNet()

### ISSUE THREAD

**Issue by hgffly** [tensorflow/tensorflow#16683]
I updated my Tensorflow to 1.5, and I tried to run the codes as below:
`import tensorflow as tf`
`model = tf.keras.applications.MobileNet()`

But it raised an error  as below:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-14-2182e918e983> in <module>()
----> 1 model = tf.keras.applications.MobileNet()

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/applications/mobilenet.py in MobileNet(input_shape, alpha, depth_multiplier, dropout, include_top, weights, input_tensor, pooling, classes)
    538     K.set_image_data_format(old_data_format)
    539   elif weights is not None:
--> 540     model.load_weights(weights)
    541   return model
    542 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/topology.py in load_weights(self, filepath, by_name)
   1099     if h5py is None:
   1100       raise ImportError('`load_weights` requires h5py.')
-> 1101     f = h5py.File(filepath, mode='r')
   1102     if 'layer_names' not in f.attrs and 'model_weights' in f:
   1103       f = f['model_weights']

/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    267             with phil:
    268                 fapl = make_fapl(driver, libver, **kwds)
--> 269                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    270 
    271                 if swmr_support:

/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     97         if swmr and swmr_support:
     98             flags |= h5f.ACC_SWMR_READ
---> 99         fid = h5f.open(name, flags, fapl=fapl)
    100     elif mode == 'r+':
    101         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = 'imagenet', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

It seems like that something wrong with h5py
I try to upgrade h5py but it's still invalid
This works well in Tensorflow 1.4
How should I resolve it with Tensorflow 1.5, thanks

**Comment by reedwm** [comment]
/CC @fchollet, do you know what the issue is?

**Comment by fchollet** [comment]
> No such file or directory

This is a simple error: weight loading can't file the cached file for this model.

Your code snippet does work for me, so nothing wrong with the file location in tf.keras. I assume there was an issue when keras downloaded the file locally for you.

Try deleting `~/.keras/models/`. Maybe that will fix it.

**Comment by hgffly** [comment]
I tried to delete ~/.keras/models and rerun the codes
The process would download the model, but it raises the same error
Not only me but my colleagues have the same issues with Tensorflow 1.5 but it does work with Tensorflow 1.4
fchollet, do you try with Tensorflow 1.5 as well?

Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.6/mobilenet_1_0_224_tf.h5
17227776/17225924 [==============================]17227776/17225924 [==============================] - 8s 0us/step

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-2182e918e983> in <module>()
----> 1 model = tf.keras.applications.MobileNet()

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/applications/mobilenet.py in MobileNet(input_shape, alpha, depth_multiplier, dropout, include_top, weights, input_tensor, pooling, classes)
    538     K.set_image_data_format(old_data_format)
    539   elif weights is not None:
--> 540     model.load_weights(weights)
    541   return model
    542 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/topology.py in load_weights(self, filepath, by_name)
   1099     if h5py is None:
   1100       raise ImportError('`load_weights` requires h5py.')
-> 1101     f = h5py.File(filepath, mode='r')
   1102     if 'layer_names' not in f.attrs and 'model_weights' in f:
   1103       f = f['model_weights']

/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    267             with phil:
    268                 fapl = make_fapl(driver, libver, **kwds)
--> 269                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    270 
    271                 if swmr_support:

/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     97         if swmr and swmr_support:
     98             flags |= h5f.ACC_SWMR_READ
---> 99         fid = h5f.open(name, flags, fapl=fapl)
    100     elif mode == 'r+':
    101         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = 'imagenet', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by hgffly** [comment]
Hi fchollet, 
I add one line in /usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py to print the name of file the program expect to load

268                 fapl = make_fapl(driver, libver, **kwds)
269                 print(name, 'aaaaaaaaaabbbbbbbbbbccccccccccccc')  # the code I added to show the name
270                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)

I rerun the codes and it showed as below:

b'/home/wilson/.keras/models/mobilenet_1_0_224_tf.h5' aaaaaaaaaabbbbbbbbbbccccccccccccc
b'imagenet' aaaaaaaaaabbbbbbbbbbccccccccccccc
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-5-2182e918e983> in <module>()
----> 1 model = tf.keras.applications.MobileNet()

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/applications/mobilenet.py in MobileNet(input_shape, alpha, depth_multiplier, dropout, include_top, weights, input_tensor, pooling, classes)
    538     K.set_image_data_format(old_data_format)
    539   elif weights is not None:
--> 540     model.load_weights(weights)
    541   return model
... skip...

From the results, the program would run this snippet twice and with different names
May it be a clue to make my program can't work ?
How should resolve it? thanks

I also tried the codes as below

from keras import applications
model = applications.MobileNet()

It only show "b'/home/wilson/.keras/models/mobilenet_1_0_224_tf.h5' aaaaaaaaaabbbbbbbbbbccccccccccccc"  once

**Comment by fchollet** [comment]
I confirm this is a real issue. It was introduce in PR https://github.com/tensorflow/tensorflow/pull/15146/files and it applies to both Xception and MobileNet.

However, it has been fixed since. If you upgrade to TF 1.6, you will no longer see this issue. For instance, you can `pip install` the TF 1.6 release candidate `1.6.0rc0` as of now.
