### ISSUE TITLE
g3doc is not installed when using pip 

### ISSUE THREAD

**Issue by tingnan** [tensorflow/tensorflow#167]
Hi All,

At least under Mac OS X the following command:

pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl

will not install g3doc (and probably some other modules). 

Just a minor issue :)

**Comment by nbenhaim** [comment]
I'm seeing the same issue on ubuntu 14.04

**Comment by vrv** [comment]
How important is it to be installed for you? That documentation is more for our websites / github.  We could include it if it was important...

**Comment by ebrevdo** [comment]
In general we avoid installing g3doc as part of the package because it is not part of the core functionality.  Similarly with the tutorials; they're kept out so that people don't have to dig around in dist-packages & site-packages for the files.  They are instead made available in the git repo.

**Comment by vrv** [comment]
Sounds good, closing for now then.
