### ISSUE TITLE
tf.contrib.rnn.GLSTMCell is hilariously broken

### ISSUE THREAD

**Issue by akhti** [tensorflow/tensorflow#16703]
In 3f579020bab8f00e4621e9c7c740cbf13136a809 an "if" was added that caches linear transformation weights:
https://github.com/tensorflow/tensorflow/blob/r1.5/tensorflow/contrib/rnn/python/ops/rnn_cell.py#L2316

The problem is that this _linear is inside a loop. And so the change tied weights of all these linear transformations.

CC @okuchaiev

**Comment by reedwm** [comment]
/CC @panyx0718, can you take a look?

**Comment by panyx0718** [comment]
Right. this is a bug introduced during a refactoring. Perhaps we should cache one Linear for each group_id.

**Comment by asimshankar** [comment]
Doh! Thanks for pointing this out @akhti - will send out a fix.
(Though, not sure if this will result in an update to the 1.5 release since APIs in `tf.contrib` are experimental and bugs there aren't treated with the same urgency as the stable APIs).

**Comment by akhti** [comment]
No worries - the bug was here since October and nobody notices :)
Though it's a very nasty bug - nothing fails, but model quality is suboptimal. Is it possible to add some simple test, like for a number of parameters to avoid this in the future?

**Comment by okuchaiev** [comment]
Please have a look at this PR https://github.com/tensorflow/tensorflow/pull/16788
