### ISSUE TITLE
add an interface to check if a variable is initialized

### ISSUE THREAD

**Issue by youkaichao** [tensorflow/tensorflow#16718]
Currently, if we create an Adam optimizer and minimize some loss, Adam will create some new variables that need to be initialized. Howerver, this is only a part of variables and we donot want to use `tf.global_variables_initializer()`.

If there is an interface to check if a variable is initialized, then we can filter global variables and initialize only what needs to be initialized!

the interface should look like `Variable.is_initialized() -> bool`

**Comment by youkaichao** [comment]
Oh, I donot know that there is a function named` tf.is_variable_initialized(var)->bool`

sorry to bother!

closed.

**Comment by youkaichao** [comment]
Currently, I am using following code:

```
for x in tf.global_variables():
    if not sess.run(tf.is_variable_initialized(x)):
        sess.run(x.initializer)
```

but I found it extremely slow!

Can you consider maintain a flag to indicate whether a variable is initialized?

**Comment by michaelisard** [comment]
@alextp what do you think is the best way to do this?

**Comment by alextp** [comment]
tf.is_variable_initialized returns a tensor. If you want to initialize all uninitialized variables in a single session.run call you can build a graph which loops over the variables and assigns them to initialized_value (which is their current value or the value of their initializer). So something like `sess.run([x.assign(x.initialized_value()) for x in tf.global_variables()])` should do the trick.

**Comment by youkaichao** [comment]
@alextp  but is it efficient? I mean, this has the same amout of work as `sess.run(tf.global_variables_initializer())`

e.g, if I have a large matrix which is already initialized, this is going to be time-consuming.

**Comment by alextp** [comment]
You can look at the implementation of initialized_value to see how to write
tf.cond predicated on whether a variable is initialized.

I am suspicious of your initialization logic though as it's not safe on
distributed. Much better to keep track of the variables you want to
reinitialize.
