### ISSUE TITLE
Shape information is not preserved through sampling

### ISSUE THREAD

**Issue by bayerj** [tensorflow/tensorflow#1672]
When I create a sample from a normal based on the shape of another tensor, that shape information is not retained.

Using Tensorflow 0.7.1:

    >>> import tensorflow as tf
    >>> x = tf.placeholder(tf.float32, (None, 12))
    >>> y = tf.random_normal(tf.shape(x))
    >>> y.get_shape()
    TensorShape([Dimension(None), Dimension(None)])

I would have expected ``TensorShape([Dimension(None), Dimension(12)])`` instead.

**Comment by keveman** [comment]
This is intended behaviour. The shape input you are passing to `tf.random_normal`, namely, the output of `tf.shape` function, is only available at runtime. Hence the static analysis is unable to infer the shape. You can consider setting the shape of `y` explicitly using the [`set_shape`](https://www.tensorflow.org/versions/r0.7/api_docs/python/framework.html#Tensor.set_shape) function.

**Comment by bayerj** [comment]
Is there an easy way to find the size of the second dimension in the above example then?

**Comment by keveman** [comment]
`x.get_shape()[1]` ?

**Comment by bayerj** [comment]
Sorry, I was not clear enough. ``x`` is not available, only ``y``.
