### ISSUE TITLE
Discrepancies between GPU and CPU in floating-point operations

### ISSUE THREAD

**Issue by rdinse** [tensorflow/tensorflow#16737]
```
bs = 32
dim = 1024

tf.reset_default_graph()
with tf.device("/cpu:0"):
  probs = tf.where(tf.greater(tf.random_normal((bs, dim)), 0.), tf.ones((bs, dim)), tf.zeros((bs, dim)))
  print(probs)
  logits = tf.log(probs / (1e-10 + 1 - probs))
  s = tf.Session(config=tf.ConfigProto(log_device_placement=True))
  print(s.run([logits]))

tf.reset_default_graph()
with tf.device("/gpu:0"):
  probs = tf.where(tf.greater(tf.random_normal((bs, dim)), 0.), tf.ones((bs, dim)), tf.zeros((bs, dim)))
  print(probs)
  logits = tf.log(probs / (1e-10 + 1 - probs))
  s = tf.Session(config=tf.ConfigProto(log_device_placement=True))
  print(s.run([logits]))
```

Running this graph on GPU results in positive infinities, whereas on CPU these tensor entries evaluate to ~88.72284. I could not quite figure out which operation is responsible for the difference. In both cases TensorFlow reports `probs` as `float32`. The difference does not occur when replacing `probs` with a `tf.ones` tensor in `float32` format.

**Comment by ppwwyyxx** [comment]
Eigen's SSE implementation of log: https://bitbucket.org/eigen/eigen/src/2355b229ea4c2876f490e726526cdcd8a63c7f54/Eigen/src/Core/arch/SSE/MathFunctions.h?at=default&fileviewer=file-view-default#MathFunctions.h-11:13 
It comes from http://gruntthepeon.free.fr/ssemath/ which says log(inf)=88.7284 (i.e., log(inf) = log(max_float).
