### ISSUE TITLE
incorrect logging formatting used in tensorflow / examples / image_retraining / retrain.py, causes error

### ISSUE THREAD

**Issue by MicrocontrollersAndMore** [tensorflow/tensorflow#16735]
In tensorflow -> examples -> image_retraining -> retrain.py, currently lines 347 / 348 look like this:

```
tf.logging.info('Successfully downloaded', filename, statinfo.st_size,
                    'bytes.')
```

This understandably causes an error since this function accepts strings and it is being fed an instance of statinfo.st_size which does not seem to be a string.  On my machine at least (TensorFlow 1.5, Windows 10) this causes the following error in function maybe_download_and_extract:

`TypeError: not all arguments converted during string formatting`

Here is a screenshot if that helps:

![error](https://user-images.githubusercontent.com/5672876/35772391-74f4433c-08f2-11e8-83d2-084605c14844.png)

The line numbers are slightly different in my screenshot because I moved a few lines around, but I can assure you the line above is causing the logging error.

I would suggest changing this line to the following, or similar:

`tf.logging.info('Successfully downloaded ' + str(filename) + ', statinfo.st_size = ' + str(statinfo.st_size) + ' bytes')`

**Comment by yongtang** [comment]
Added #16738 for the fix.
