### ISSUE TITLE
install  mac os by pip3

### ISSUE THREAD

**Issue by Heipiao** [tensorflow/tensorflow#1674]
### Environment info
Operating System:
Mac OS 10.11.1
i try:
sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp35-none-any.whl

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
bogon:~ liu$ sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp35-none-any.whl
The directory '/Users/liu/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/liu/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
tensorflow-0.7.1-cp35-none-any.whl is not a supported wheel on this platform.
You are using pip version 7.1.2, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
bogon:~ liu$

**Comment by keveman** [comment]
There seems to be 2 issues, one is directory permissions, and the other is that the whl file is not compatible on your platform. Do you mind trying the pip install under a virtualenv?

    $ virtualenv -p `which python3` py3env
    $ source py3env/bin/activate
    # No sudo
    $ pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp35-none-any.whl

**Comment by kennmyers** [comment]
I'm also getting this issue but on Linux. I've tried installing tensorflow both on AWS EC2 and through herokus python buildpack but in both instances got the error ```tensorflow-0.7.1-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.``` Was able to get it on the EC2 using [this guys conda package](https://conda.anaconda.org/jjhelmus) but still can't get it on heroku.

**Comment by clsung** [comment]
What's your python3 version? also try upgrade your pip and setuptool?.

`% pip3 install --upgrade pip setuptools`

**Comment by kennmyers** [comment]
I ended up getting it working on the EC2 using a a conda install and on heroku by switching from python 3.5.1 to 3.4.0

**Comment by Heipiao** [comment]
i use python3.4.4 and upgrade pip to the newset,try virtulenviroment. but still not work...

**Comment by clsung** [comment]
Can you try execute and print python3 with the following command?

`import pip; print(pip.pep425tags.get_supported())`

Example:

> $ python3
> Python 3.5.1 (default, Dec  7 2015, 21:59:08)
> [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> import pip; print(pip.pep425tags.get_supported())
> [('cp35', 'cp35m', 'macosx_10_10_x86_64'), ('cp35', 'cp35m', 'macosx_10_10_intel'), ('cp35', 'cp35m', 'macosx_10_10_fat64'), ('cp35', 'cp35m', 'macosx_10_10_fat32'),.....
>

**Comment by clsung** [comment]
As an alternative, I'll suggest that you can download  tensorflow-0.7.1-py3-none-any.whl by via [Nightly Build](http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_CONTAINER_TYPE=CPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=mac-slave/)

**Comment by Heipiao** [comment]
thx,it finally work successfully!!!

2016-04-01 19:45 GMT+08:00 Cheng-Lung Sung <notifications@github.com>:

**Comment by raymondjplante** [comment]
I also had this same issue, .**..is not a supported wheel on this platform.**.  when trying to install with python 3.4.3 and pip 8.1

To fix issue:

- used pyenv to pull down upgraded to python 3.5.1, switched it to be my global python
- Created a virtual env via pyvenv (not virtualenv, but I think this is irrelevant) 
- Ran  `pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp35-none-any.whl`

Worked!!!
