### ISSUE TITLE
No documentation on the order of eigenvalues returned by tf.self_adjoint_eig 

### ISSUE THREAD

**Issue by thjashin** [tensorflow/tensorflow#16747]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:('v1.4.0-rc1-11-g130a514', '1.4.0')
- **Python version**: 2.7.14

### Describe the problem
From the documentation of `tf.self_adjoint_eig` I cannot see what the order of eigenvalues is. I tried with several examples and found they were sorted in ascending order. Does this always hold?

**Comment by qmick** [comment]
TensorFlow doc doesn't tell much about that. But TensorFlow use `Eigen` to calculate the eigenvalues:
https://github.com/tensorflow/tensorflow/blob/ba032db13627945e7cc772dbd3d85d257aef3ab9/tensorflow/core/kernels/self_adjoint_eig_op.cc#L58-L65

And document of `Eigen` says:

> The eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix. The eigenvalues are sorted in increasing order.
https://eigen.tuxfamily.org/dox/classEigen_1_1SelfAdjointEigenSolver.html#a3df8721abcc71132f7f02bf9dfe78e41

So the order is guranteed by `Eigen`.

**Comment by skye** [comment]
@rmlarsen could you update the docs? I think @annarev can help direct you to where they should be updated.

**Comment by annarev** [comment]
These seem to be relevant files for SelfAdjointEig documentation:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_SelfAdjointEig.pbtxt
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_SelfAdjointEigV2.pbtxt

**Comment by skye** [comment]
I think @rmlarsen has the flu, and @qmick seems to have discovered the answer, so I'm gonna mark contributions welcome for now. Please feel free to submit a PR!
