### ISSUE TITLE
CUDA Fail in Tensorflow Inference on Jetson TX2

### ISSUE THREAD

**Issue by pvaezi** [tensorflow/tensorflow#16751]
Hi,

I am getting CUDA fail error for model inference on Jetson TX2 aarch64. I have built the TF source (Version 1.3) for python 3.5 from this github repo:
https://github.com/jetsonhacks/installTensorFlowTX2

- Ubuntu 16.04
- Bazel 0.5.2
- CUDA 8 
- cuDNN 6. 

The relevant discussion on NVIDIA dev forum directed me to post this here:
https://devtalk.nvidia.com/default/topic/1029256/jetson-tx2/cuda-fail-when-running-tensorflow-inference/post/5236860/

TF does work for smaller sized models, but for larger sized models the inference fails. I appreciate if you can please take look at this.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by skye** [comment]
Hi, are you able to create a smaller repro script? We likely won't be able to debug this otherwise. Also, could you post the error message you receive and any other relevant information?

**Comment by skye** [comment]
Actually, this may be related to #15075. Regardless, we don't have the ability to support or debug Jetson TX2 issues, so I'm marking contributions welcome.

**Comment by LanYangXiXi** [comment]
hi pvaezi , I just met the same problem when I trying to use Inception v3 to classify image, which is a tutorial in TensorFlow repository, i flashed my TX2 with jetpack 3.1, and cuda 8.0, cudnn 6, I can train cifar10 so I think it is not the environment problem, so have you solve this problem? waiting for your response.

**Comment by mohantym** [comment]
Hi @pvaezi! Is this issue still valid ?
