### ISSUE TITLE
Feature request: Adding data_format argument to lstm2d.separable_lstm

### ISSUE THREAD

**Issue by selcouthlyBlue** [tensorflow/tensorflow#16760]
Since ndlstm is used for 2D data such as images, I think it would be nice to include a `data_format` argument in lstm2d.separable_lstm in case one decides to use the channels first format (NCHW) for their images (i.e. Using CNN having NCHW data format followed by NDLSTM).

**Comment by AK-ayush** [comment]
Is this still open?? But the ndlstm is removed from tensorflow:master.

**Comment by selcouthlyBlue** [comment]
Oh yeah, I forgot to close this one. Closing it.
