### ISSUE TITLE
TensorBoard: Fit domain to data in 1.5 under Windows cuts off max values

### ISSUE THREAD

**Issue by alenaschnurr** [tensorflow/tensorflow#16773]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Using TensorBoard in custom U-Net implementation
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 7
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.5
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 9.0, CuDNN 7
- **GPU model and memory**: GeForce GTX 1050 Ti (4 GB), 32 GB RAM
- **Exact command to reproduce**: tensorboard with tf.summary.scalar

### Describe the problem
After updating from 1.4 to 1.5 I have the problems that the y-scale for the scalar graphs in TensorBoard seems to be misscalculated. The maximum values are not included in the shown graph, they are cut off.

![image](https://user-images.githubusercontent.com/31246640/35806246-1efb92ee-0a7f-11e8-8441-17ebe97473b7.png)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
GPU model and memory

**Comment by alenaschnurr** [comment]
I updated the missing fields.

**Comment by jart** [comment]
TensorBoard has a new GitHub repo: https://github.com/tensorflow/tensorboard Would you be able to refile this issue over there?
