### ISSUE TITLE
Trying to allocate large output tensor in custom op leads to multiple evaluation of Compute method

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#16780]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS X 10.13.2
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.5.0
- **Python version**: 2.7.14
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: CPU-version of Tensorflow
- **GPU model and memory**:
- **Exact command to reproduce**: make

### Describe the problem
I wrote a custom op. During debugging i've noticed then Compute method from my op fired multiple times during single op.eval() call.
My quest lead me to row:
```c++
OP_REQUIRES_OK(ctx, ctx->allocate_output(0, TensorShape({output_size}), &values_tensor));
```
If output_size is small (e.g. 1000), my op works well and executes one time.
If output_size is big (e.g. 15000000), my op executes multiple times.

### Source code / logs
There are 3 files in archive:
- custom op source code
- demo eval script
- makefile config to build op and run eval

[issue.zip](https://github.com/tensorflow/tensorflow/files/1696503/issue.zip)

**Comment by michaelisard** [comment]
Do you get the same behavior with a simple type e.g. float or is it just string?

**Comment by shkarupa-alex** [comment]
Got same behavior with float

**Comment by michaelisard** [comment]
OK I will take a look when I get a chance but it may be a day or two sorry!

**Comment by michaelisard** [comment]
The first time your op is run is during a constant-folding optimization pass. When the output is sufficiently small the constant folding heuristic decides to replace the execution of the op by a constant, and when the 'real' step runs it doesn't need to execute your op again. When the output is larger, the heuristic decides it's better to keep re-running the op than fold it into a constant, so the 'real' step actually executes your op.

If you put SetIsStateful on your Op registration then the constant folder ignores it, and it will only execute once as you expect, regardless of the size of the output.

Closing for now but please reopen if that doesn't make sense!
