### ISSUE TITLE
Save a numpy params as tensorflow model!

### ISSUE THREAD

**Issue by yhl41001** [tensorflow/tensorflow#16790]
Hi, I have trained a model, and i save the params in a numpy file in dict type.
Now i construct the network manually, and set the params as my trained model.
i want to save the network as tensorflow model, but the session is empty, 
so how could i save the model?

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
