### ISSUE TITLE
Feature Request: Modification of lstm2d.horizontal_lstm implementation

### ISSUE THREAD

**Issue by selcouthlyBlue** [tensorflow/tensorflow#16794]
I noticed something in the documentation of `lstm2d.horizontal_lstm`. It says:

> Run an LSTM bidirectionally over all the rows of each image.

Kinda looks like a bidirectional_lstm to me. I propose to change the implentation such that it will use bidirectional_lstm within the function replacing this:

```
with variable_scope.variable_scope("lr"):
  hidden_sequence_lr = lstm1d.ndlstm_base(sequence, num_filters_out // 2)
with variable_scope.variable_scope("rl"):
  hidden_sequence_rl = (lstm1d.ndlstm_base(
      sequence, num_filters_out - num_filters_out // 2, reverse=1))
output_sequence = array_ops.concat([hidden_sequence_lr, hidden_sequence_rl],
                                       2)
```

With this:

```
cell_fw = rnn_cell.BasicLSTMCell(num_filters_out // 2)
cell_bw = rnn_cell.BasicLSTMCell(num_filters_out // 2)
output_sequence = rnn.bidirectional_dynamic_rnn(cell_fw, cell_bw, sequence, time_major=True, 
                                                                                 dtype=sequence.dtype)
```

**Comment by ebrevdo** [comment]
This code is considered legacy because the author is no longer maintaining it, and it doesn't have many users.  In fact, I hope to remove it for TF 1.7.  If you'd like to make these kinds of modifications, you may want to copy it under the Apache 2 license into your own repository and make them there?

**Comment by selcouthlyBlue** [comment]
If you really intend to remove it, mind at least keeping some of the functions in there (like move them to contrib.layers or something)? I think `images_to_sequence` and `sequence_to_images` are pretty useful.

**Comment by ebrevdo** [comment]
Would you like to send a PR to copy these + unit tests over?  I'll be
removing them in the next day or two.

**Comment by selcouthlyBlue** [comment]
Alright, I'll work on them.

**Comment by selcouthlyBlue** [comment]
Pull request made.
