### ISSUE TITLE
Tensorflow 1.5.0 Import Error on CUDA 9.0

### ISSUE THREAD

**Issue by ziruizhuang** [tensorflow/tensorflow#16791]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, I used the stock version.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: pip binary for windows with GPU support
- **TensorFlow version (use command below)**: 1.5.0
- **Python version**: Python 3.6.1 from Anaconda
- **CUDA/cuDNN version**: 9.0/7.0.5
- **GPU model and memory**:
- **Exact command to reproduce**: import tensorflow as tf

### Describe the problem
Installed CUDA/CUDNN 8.0/6, 9.0/7, 9.1/7
Used pip to install tensorflow_gpu 1.5.0

The installation process finished normally.

However, when import the module by "import tensorflow as tf", error messages raises and it says ImportError: Could not find 'cudart64_90.dll'.

I double checked the CUDA_PATH and PATH environmental variables to make sure that CUDA/CUDNN 9.0/7 are being used. Later I removed the 8.0/6 and 9.1/7, and the problem still exists.

### Source code / logs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-toolkit

**Comment by ziruizhuang** [comment]
A system reboot solved the issue.

However, since the tensorflow installation page still refers to CUDA/CUDNN 8.0/6, it would be better if the page states the CUDA requirement for different versions of prebuilt binaries.

**Comment by skye** [comment]
cc/ @MarkDaoust

**Comment by MarkDaoust** [comment]
The docs on the TensorFlow site have been updated. r1.5, r1.6, and master all include this commit now:

https://github.com/tensorflow/tensorflow/commit/f68404bdd10a4b6ef2a50439efac4614de024636

**Comment by JerryLife** [comment]
Thanks so much! I've tried dozens of ways for hours. **A system reboot finally solved everything.**
