### ISSUE TITLE
tensor flow does not support operator.__truediv__

### ISSUE THREAD

**Issue by Pakapark** [tensorflow/tensorflow#168]
tensorflow type does not support operation.__truediv__ as in the basic example in https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/g3doc/tutorials/word2vec/word2vec_basic.py
In line 153,  ' normalized_embeddings = embeddings / norm'  will cause the attribute error as followed

"AttributeError: type object 'Tensor' has no attribute '__truediv__"

To solve the problem, we can replace this line as 'normalized_embeddings = tf.div(embeddings, norm)'

**Comment by girving** [comment]
Fixed by 1d76583411038767f673a0c96174c80eaf9ff42f.  Also see #1 .

**Comment by xiangrongzeng** [comment]
Thankyou for your help
