### ISSUE TITLE
How to compile and use Opencv in tensorflow c++?

### ISSUE THREAD

**Issue by hxw111** [tensorflow/tensorflow#16800]
I want to implement a model inference in tensorflow c++ and have saved the model as .pb file. But I can't use opencv to process the image. I wonder how can I add the opencv lib to the bazel project? Are there any tricks to solve the problem? Thanks!

This is the code of the bazel BUILD file:

    package(
        default_visibility = ["//tensorflow:internal"],
    )

    licenses(["notice"])  # Apache 2.0

    exports_files(["LICENSE"])

    load("//tensorflow:tensorflow.bzl", "tf_cc_binary")

    tf_cc_binary(
        name = "mask_rcnn",
        srcs = [
            "main.cc",
        ],
        #prefix = "flower",
        linkopts = select({
            "//tensorflow:android": [
                "-pie",
                "-landroid",
                "-ljnigraphics",
                "-llog",
                "-lm",
                "-z defs",
                "-s",
                "-Wl,--exclude-libs,ALL",
            ],
            "//conditions:default": ["-lm"],
        }),
        deps = select({
            "//tensorflow:android": [
                # cc:cc_ops is used to include image ops (for label_image)
                # Jpg, gif, and png related code won't be included
                "//tensorflow/cc:cc_ops",
                "//tensorflow/core:android_tensorflow_lib",
                # cc:android_tensorflow_image_op is for including jpeg/gif/png
                # decoder to enable real-image evaluation on Android
                "//tensorflow/core/kernels:android_tensorflow_image_op",
            ],
            "//conditions:default": [
                "//tensorflow/cc:cc_ops",
                "//tensorflow/core:core_cpu",
                "//tensorflow/core:framework",
                "//tensorflow/core:framework_internal",
                "//tensorflow/core:lib",
                "//tensorflow/core:protos_all_cc",
                "//tensorflow/core:tensorflow",
            ],
        }),
    )

    filegroup(
        name = "all_files",
        srcs = glob(
            ["**/*"],
            exclude = [
                "**/METADATA",
                "**/OWNERS",
                "bin/**",
                "gen/**",
            ],
        ),
        visibility = ["//tensorflow:__subpackages__"],
    )

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by JuiYang** [comment]
hello, are you have solved this problem ?   why are you  want use opencv process image not ByteBuffer ?
