### ISSUE TITLE
Code size with XLA AOT

### ISSUE THREAD

**Issue by xcv9685** [tensorflow/tensorflow#16828]
I currently research about xla using AOT compilation and use Cifar10 as benchmark

After using AOT compilation, I got a binary file that size is 5.3MB, but the original tensorflow graph's size is about 4.2MB. Does it means a using AOT compilation can't promise always reduce code size efficiently?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sanjoy** [comment]
The AOT generated binary contains machine code for the CPU you're targeting (for instance x86) whereas the TF graph is a serialized representation of the TensorFlow graph (very different from machine code).  Everything else remaining equal, you can expect that a larger TF graph will generate a larger binary; but other than that there is no correlation between these two things.

**Comment by xcv9685** [comment]
@sanjoy  Thanks for your help.
So if I want to test whether AOT reduce code size, how should I test?
Does it means I should take final binary file's  size which generate from AOT compare with original TF graph + runtime size?

**Comment by xcv9685** [comment]
@sanjoy Thanks for your help very much.
According to speech at TensorFlow Dev Summit 2017(https://youtu.be/kAOanJczHA0?t=2831),
Code size can be evaluated by Original(Runtime + Graph) compare with Compiled(Code+Weigh).
As I know, Graph = TF graph, what does the rumtime means? Does it mean all libraries that graph need to use?
And does Code+Weight mean the binary file which compiled by AOT?

**Comment by sanjoy** [comment]
> what does the rumtime means? Does it mean all libraries that graph need to use?

Yes, it is everything that you need to actually execute the graph.

> And does Code+Weight mean the binary file which compiled by AOT?

It depends on the context, but most likely yes.

**Comment by michaelisard** [comment]
It probably makes sense to move any further discussion on this topic to stackoverflow, since it isn't a bug report or feature request. Thanks!
