### ISSUE TITLE
how to build and install cplusplus library and header file to /usr/local?

### ISSUE THREAD

**Issue by hxfxjun** [tensorflow/tensorflow#16827]
how to build and install cplusplus library and header file to /usr/local?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hxfxjun** [comment]
how to build and install cplusplus library and header file to /usr/local?

Have I written custom code
No

OS Platform and Distribution
Centos 7.0

TensorFlow installed from
Source

TensorFlow version
1.5

Bazel version
0.9.0

CUDA/cuDNN version
None

GPU model and memory
None

Exact command to reproduce

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
