### ISSUE TITLE
Feature request: Enable validate_args for all distributions based on a global parameter

### ISSUE THREAD

**Issue by lazypanda1** [tensorflow/tensorflow#16839]
The probability distributions in Tensorflow have a `validate_args` argument that is initially set to `False`. This is a request for a feature that initializes the value of `validate_args` to the value of a global flag (that can be set from the command line or the preferences).

Rationale: Currently, when the user sets up the model incorrectly e.g. wrong parameter values are provided for the distributions, or data values don't match the support for the distribution, the program silently fails and produces nans in the output (or worse, wrong values). The user has no way to debug this easily because `validate_args` is `False` by default, and manually adding `validate_args=True` while initializing each distribution can be tedious for the user.

I would be happy to contribute this feature to tensorflow if this seems reasonable. Do you have any suggestions on how to go forward?

**Comment by alextp** [comment]
Send a pull request and we'll discuss there.

**Comment by tilakrayal** [comment]
@lazypanda1,
The respective raised PR was closed. Could you please check the [comment](https://github.com/tensorflow/tensorflow/pull/16881#issuecomment-370161982) from the developer and provide the required information. Thank you!
