### ISSUE TITLE
TypeError when trying to import tensorflow 

### ISSUE THREAD

**Issue by TheGreenEvil** [tensorflow/tensorflow#16836]
Hello. I have install TF 1.6 from source and getting next error when trying to import it from python.
```
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 76, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 871, in <module>
    EagerTensor = c_api.TFE_Py_InitEagerTensor(_EagerTensorBase)
TypeError: Unable to create subclass EagerTensor from base class type. Need its size to be <= 32
>>>
```
------------------------

### System information
- **Linux Ubuntu 16.04**
- **Tensorflow 1.6.0-rc0 built from source**
- **Python 3.6**
- **Bazel version 0.10.0**
- **GCC version 5.4.0**
- **CUDA 9.1. cuDNN 7.0**
- **Nvidia 1050 Ti 4GB**

**Comment by TheGreenEvil** [comment]
Hello again, updates on my issue.
I recompiled tensorflow with the exact same settings but with python 3.5 from Ubuntu repositories and everything work fine. 
After some examination of source code, i find out that 
on python 3.5
`sys.getsizeof(type) == 400`
but on my python 3.6 
`sys.getsizeof(type) == 416`
and because of that `_EagerTensorBase` was bigger then expected.
And looks like this was the cause of issue

**Comment by chrisbyd** [comment]
hello. I have encountered the same problem when installing tensorflow from source in mac. When I import tensorflow in python, I had the same issue. But I tryed different python versions including "3.4.0,3.5.0 and 3.6.0" and none of them works.

**Comment by agarwal-ashish** [comment]
As per #17530 we need to increase kMaxEagerTensorParentSize to fix this error.
