### ISSUE TITLE
Point Tensorflow To My Local Protobuf Installation

### ISSUE THREAD

**Issue by RoboEvangelist** [tensorflow/tensorflow#16840]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: sorta
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.4.1
- **Python version**: 2.7 and 3.0
- **Bazel version (if compiling from source)**: 0.6.0
- **GCC/Compiler version (if compiling from source)**: 5
- **CUDA/cuDNN version**: 8 and 6
- **GPU model and memory**: GTX 1080
- **Exact command to reproduce**: make
-**PROTOBUF VERSION**: 3.4.1

Folks, I am using tensorflow C++, and I added it's path to my CMakeLists.txt.
Everything was working fine, but I had to change the protobuf installation to a different path because CAFFE needs a different version of protobuf other than 3.4.1
Now, Tensorflow libraries are complaining they cannot find common.h from protobuf:

/usr/local/include/google/tensorflow/tensorflow/core/framework/tensor.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory

I installed protobuf 3.4.1 here:
/usr/local/include/google

How do I make Tensorflow realize that protobuf is installed in a different path path?

**Comment by alextp** [comment]
See tensorflow/contrib/cmake/external/protobuf.cmake for how tf cmake imports the proto compiler
