### ISSUE TITLE
How to improve tensorflow model accuracy ?

### ISSUE THREAD

**Issue by VivekPowar** [tensorflow/tensorflow#16859]
I have created model for chair by using tensorflow. But that model detecting any object as chair, So how can i improve model to detect only chair. We have provided 300 images of chair for training, Total loss of chair model is less than 0.6.  [this is graph](https://i.stack.imgur.com/5yhW4.png) And also give me information about How to improve accuracy of model to detect only chair.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by VivekPowar** [comment]
@tensorflowbutler 

OS Platform and Distribution :- 16.04 
TensorFlow installed from :- https://www.tensorflow.org/install/install_linux
TensorFlow version :- tensorflow (1.4.1)
                                   tensorflow-tensorboard (0.4.0)
Bazel version :- blaze (0.11.3)
CUDA/cuDNN version :-  CUDA 8 and cuDNN 6
GPU model and memory :- GeForce GTX 1050 Ti mini, 4GB GDDR5

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
