### ISSUE TITLE
How to redirect tfdbg dumping directory

### ISSUE THREAD

**Issue by MrWanter** [tensorflow/tensorflow#16867]
By default, `tfdbg` dumps saved tensors to `/tmp`, but in my case, `/tmp` is mount in `/root `, `/root` has only several G's space, running the example debug is not a problem, but when debugging large network, for which in one run will generate tensors that exceeds 10 G's memory, it would prompts space not enough.

**Comment by caisq** [comment]
The constructors `LocalCLIDebugWrapperSession` and `LocalCLIDebugHook` both have a keyword argument called `dump_root`, which allows you to specify where to dump the debug data.

See:
https://www.tensorflow.org/api_docs/python/tfdbg/LocalCLIDebugWrapperSession#__init__
https://www.tensorflow.org/api_docs/python/tfdbg/LocalCLIDebugHook#__init__
