### ISSUE TITLE
Update Dockerfile to install Python 3.6

### ISSUE THREAD

**Issue by shoyer** [tensorflow/tensorflow#16875]
The Python 3 containers at gcr.io/tensorflow/tensorflow generated by [tensorflow/tools/docker](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker) are currently built using Python 3.5.

It would be nice to update them to Python 3.6 instead, which I think would be as simple as adding `sudo apt-get install python3.6`.

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: N/A
- **Python version**: N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gunan** [comment]
Unfortunately, it is not that simple.
We are staying with the earliest ubuntu version nvidia docker supports, which is ubuntu 16.04.
On ubuntu 16, python3.6 is not available.
Since we also had problems with 3rd party python distros before, until we upgrade the docker container to a newer version of ubuntu we will stay with python 3.5.

Just to check, is this breaking you by not having python3.6? I just would like to see if there is a specific usecase you had in mind?

**Comment by shoyer** [comment]
No, it was just "nice to have". Thanks for checking (and the explanation).

**Comment by riansanderson** [comment]
My specific use case for wanting Python 3.6 is because our codebase extensively uses [PEP 526 Variable Annotations](https://www.python.org/dev/peps/pep-0526) and Python 3.5.2 in the current docker images chokes on the syntax.  I'd like to be able to use the official TF docker images for running continuous integration tests..

**Comment by lzfxxx** [comment]
Hi, our codebase uses [PEP 498: Formatted string literals](https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals), which is only supported by py36 and newer.

**Comment by cgarciae** [comment]
+1

**Comment by gunan** [comment]
I think it may be time to reevaluate. Our builds have to use ubuntu 14 anyway, and nvidia does not provide such dockerfiles. We will need to split our docker images and CI setup anyway.

**Comment by SumNeuron** [comment]
@gunan I agree. This will only cause more grievance with time. With an unpleasant workaround being using virtualenv  inside a container... which defeats the point.

**Comment by ctrlbrett** [comment]
Is there any way the community can help move this along? Maybe an experimental release can be created? This feature would be very useful.

**Comment by harahu** [comment]
Joining the hype train. Would love to see the TensorFlow docker containers move to Python 3.6 or 3.7. Both carry performance improvements that I'd like to get the benefits from.

**Comment by nxphi47** [comment]
Hello, any update for this? I use the nvidia-docker provided for Nvidia GPU Cloud docker image. It also has python3.5

My codes lots of f"string {variable}" literals, which only work on python 3.6 or more. 
Is it possible to update the version of python without interfering existing packages like cuda or tensorflow-gpu?

Thanks

**Comment by harahu** [comment]
> I think it may be time to reevaluate. Our builds have to use ubuntu 14 anyway, and nvidia does not provide such dockerfiles. We will need to split our docker images and CI setup anyway.

@gunan in july you played with the idea of reevaluating the choice of sticking to 3.5. Any news on that process? Did you decide to keep Ubuntu 16.04, or is there movement in that regard?

**Comment by gunan** [comment]
After discussing with NVIDIA they agreed to reintroduce support for ubuntu 14.
As Debian stable and Centos 7 compatibility would be lost with newer ubuntu versions, our CI stayed with ubuntu 14.
I think our dockerfiles have been updated to ubuntu 16. Not sure about the python version on them.

**Comment by yuvval** [comment]
For anyone encountered the `f"string {variable}"` literals issue: A hacky workaround, that works on earlier versions of python is to change those expressions to `"string {variable}".format(**locals())`

**Comment by harahu** [comment]
@gunan Can confirm that tf dockerfiles are still python 3.5.2. Now that TF 1.13 is released with support for python 3.7, maybe it is worth it to look into this again? Python 3.5 will reach end of life on 2020-09-13, which isn't that far out. I'd like to move on sooner rather than later.
