### ISSUE TITLE
A small bug in tutorials/mnist/mnist_with_summaries.py

### ISSUE THREAD

**Issue by jialrs** [tensorflow/tensorflow#1688]
Please fix the bug in **Line 85** of file *tensorflow/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py*
the code 
`writer = tf.train.SummaryWriter(FLAGS.summaries_dir, sess.graph)` 
should be changed to 
`writer = tf.train.SummaryWriter(FLAGS.summaries_dir, sess.graph.as_graph_def())`,
otherwise there will be an error ` 'Graph' object has no attribute 'SerializeToString'`

**Comment by jialrs** [comment]
I look at the history of this file and find that the line 85 is changed to fit for the new API, which is somehow not consistent with the API in 0.7.1. Maybe some comments  here should add in this file as it is linked in the tutorial of the official website.

**Comment by vrv** [comment]
The link from the website actually points to the r0.7 version of the branch: https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py, so I'm not sure what else we can do here -- it is generally recommended (for all software), to match the binary install you are using with the branch that matches it.
