### ISSUE TITLE
Feauture Request: Multidimensional RNN

### ISSUE THREAD

**Issue by selcouthlyBlue** [tensorflow/tensorflow#16883]
I would like to contribute a Multidimensional RNN feature in the contrib directory based on the implementation mentioned [here](https://github.com/tensorflow/tensorflow/issues/1453#issuecomment-194976468). 

> Right now it's possible to implement various types of multidimensional RNNs by feeding in your data as time being one direction (say, x), taking the output of the RNN, transposing it, and feeding it into a second RNN. etc. Alternatively feed your data & its transpose into separate RNNs (possibly with tied weights) and depth-concatenate the results. And maybe feed the result into another RNN.

By any chance, is it related to the [main paper](https://arxiv.org/abs/0705.2011) for it?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by selcouthlyBlue** [comment]
Nome if them are relevant to in my case since this is a feature request.

Have I written custom code: I will be writing custom code.
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by drpngx** [comment]
There used to be `tf.contrib.ndlstm` (which did 2d) but you can still install this:
https://github.com/tmbarchive/tfndlstm.

**Comment by selcouthlyBlue** [comment]
Ohhh, I guess I can just make some improvements there instead. Closing this now.

**Comment by selcouthlyBlue** [comment]
I wonder if it is based on this paper: http://papers.nips.cc/paper/3449-offline-handwriting-recognition-with-multidimensional-recurrent-neural-networks.pdf
