### ISSUE TITLE
tfcompile fails with Executor failed to create kernel. Not found: No registered 'ResizeNearestNeighbor' 

### ISSUE THREAD

**Issue by thefiddler** [tensorflow/tensorflow#16888]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes, very simple CNN (attached)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.13.3
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 926fc13
- **Python version**: python 3.6.4
- **Bazel version (if compiling from source)**: 0.10
- **GCC/Compiler version (if compiling from source)**: Apple LLVM version 9.0.0 (clang-900.0.39.2
- **CUDA/cuDNN version**: none
- **GPU model and memory**: none
- **Exact command to reproduce**: ./bazel-bin/tensorflow/compiler/aot/tfcompile  --graph="/data/models/tensorflow/testmodel.pb" --config="/data/models/tensorflow/testmodel.pbtxt"

### Describe the problem
Trying to compile a trivial model, consisting of a single nearest-neighbour resize layer, I get an abort trap 6. The model graph and config can be [found here](https://github.com/tensorflow/tensorflow/files/1710673/testmodel.zip).

### Source code / logs
```bash
./bazel-bin/tensorflow/compiler/aot/tfcompile  --graph="/data/models/tensorflow/testmodel.pb" --
config="/data/models/tensorflow/testmodel.pbtxt"
2018-02-09 11:45:13.215728: E tensorflow/compiler/tf2xla/graph_compiler.cc:115] Executor failed to create kernel. Not found: No registered 'ResizeNearestNeighbor' OpKernel for XLA_CPU_JIT devices compatible with node out/ResizeNearestNeighbor = ResizeNearestNeighbor[T=DT_FLOAT, align_corners=false](aot_feed_0/in, out/mul)
        .  Registered:  <no registered kernels>

         [[Node: out/ResizeNearestNeighbor = ResizeNearestNeighbor[T=DT_FLOAT, align_corners=false](aot_feed_0/in, out/mul)]]
2018-02-09 11:45:13.216094: F tensorflow/compiler/aot/tfcompile_main.cc:148] Non-OK-status: status status: Not found: No registered 'ResizeNearestNeighbor' OpKernel for XLA_CPU_JIT devices compatible with node out/ResizeNearestNeighbor = ResizeNearestNeighbor[T=DT_FLOAT,
align_corners=false](aot_feed_0/in, out/mul)
        .  Registered:  <no registered kernels>

         [[Node: out/ResizeNearestNeighbor = ResizeNearestNeighbor[T=DT_FLOAT, align_corners=false](aot_feed_0/in, out/mul)]]
Abort trap: 6
```

**Comment by michaelisard** [comment]
@hawkinsp have you thought about how hard this would be to implement in XLA?

**Comment by hawkinsp** [comment]
This op would not be terribly hard to implement via XLA (although perhaps not performantly on CPU).

There's already a bilinear resize op (although I suspect it isn't fast on CPU) and one possible implementation strategy is to use almost the same code but with a different convolution kernel. This would at least fix the immediate error here, but I have no idea if it would meet any performance requirements.

Or if the resize here is an integer-multiple resize, then there are some special case implementations that would be easy to add.

**Comment by michaelisard** [comment]
For now I will leave it as contributions welcome in case anyone wants to try to generalize the existing bilinear resize op.

**Comment by meggamind** [comment]
@michaelisard  : I would love to work on this. Can you share some more info on this.
Thanks.
