### ISSUE TITLE
How show detecting image.

### ISSUE THREAD

**Issue by dersar00** [tensorflow/tensorflow#16891]
When I start a object_detection_tutorial script via ipython, it's didn't show me any image.  My console:
![image](https://user-images.githubusercontent.com/17855733/36030750-0f96f458-0db1-11e8-867c-7d545c6e3170.png)
But something is starting in process because starting some python program, but before it's  open, the program is closed.
![image](https://user-images.githubusercontent.com/17855733/36030857-713182fa-0db1-11e8-9b25-c208d0979d12.png)
code is here: https://pastebin.com/eh0SWjyU

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dersar00** [comment]
My issue is solved.
My mistake was that I tried to run it with command `ipython file.py` instead I had to start first `ipython` and then just start with the command `run file.py`
Hope it will help someone.
