### ISSUE TITLE
Small typo in Deep MNIST Tutorial

### ISSUE THREAD

**Issue by houstonlucas** [tensorflow/tensorflow#169]
There is a small typo on the [Deep MNIST for Experts](http://tensorflow.org/tutorials/mnist/pros/index.md) page. It's the first sentence of the second paragraph under the Start TensorFlow InteractiveSession header.
>Here we instead use the convenience InteractiveSession class, ...

should maybe  be
>Here we instead use the convenient InteractiveSession class,...

or maybe
>Here we instead use the convenience of the InteractiveSession class, ...

**Comment by vrv** [comment]
Pushed to git in https://github.com/tensorflow/tensorflow/commit/6b12d081d54b89869e26d9d99828f13de381761e  -- thanks!
