### ISSUE TITLE
python 3.6 + latest tf = infinity of "msgpack_numpy.py:142 PendingDeprecationWarning: encoding is deprecated." 

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#16906]
Symptom, trying to train resnet-50 imagenet @ppwwyyxx 's [imagenet-resnet.py](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py) script fails to start after 5 minutes, because of some thread being blocked trying to flush a gazillion of warning messages above

Since this problem is solved by downgrading from "tf-nightly-gpu" (`1.7.0-dev20180208`) to tensorflow-gpu 1.5, TensorFlow must be blame for introducing a new usage of this deprecated method. Unfortunately the warning messages are quite uninformative, with no indication of who is calling this :/

Note that Python 3.6 is the only Python 3 version supported on Amazon Deep Learning conda AMI images.

Warning messages look like this:

```
/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/msgpack_numpy.py:142: PendingDeprecationWarning: encoding is deprecated.
  use_bin_type=use_bin_type)
/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/msgpack_numpy.py:142: PendingDeprecationWarning: encoding is deprecated.
  use_bin_type=use_bin_type)
/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/msgpack_numpy.py:142: PendingDeprecationWarning: encoding is deprecated.
  use_bin_type=use_bin_type)

```

**Comment by ppwwyyxx** [comment]
Oops actually I think this one is on me. I did make calls to msgpack with use_bin_type. If you have pip installed pyarrow, it will not use msgpack then.
But not sure why downgrading tensorflow will help you.

**Comment by yaroslavvb** [comment]
hm, I may have done something else in addition to tensorflow downgrade, will close for now
