### ISSUE TITLE
Multi-GPU could not provide performance improve with dataset API

### ISSUE THREAD

**Issue by Lancerchiang** [tensorflow/tensorflow#16907]
I just wrote a small piece of code in tensorflow to test its multi-gpu performance, with dataset API.

```
import tensorflow as tf
import numpy as np
import time
import os

#dataset with 1000 vectors
dataset = tf.data.Dataset.from_tensor_slices(tf.random_uniform([1000,4], maxval=4, dtype=tf.int32))
          
print(dataset.output_types)
print(dataset.output_shapes)

iterator = dataset.make_initializable_iterator()
#next_element = iterator.get_next()

tensor_results = []


for i in range(500):
    for j in range(2):
        with tf.device("/gpu:%d" % j):
            with tf.name_scope("Tower_%d" % j) as scope:
                operand = iterator.get_next()
                tensor_result = tf.matmul(tf.reshape(operand,shape=[1,4]), tf.reshape(operand,shape=[4,1]))
                tensor_results.append(tensor_result)


tfconfig = tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)
tfconfig.gpu_options.allow_growth=True

sess = tf.Session(config=tfconfig)

sess.run(iterator.initializer)
t0 = time.time()

results = sess.run(tensor_results)

t1 = time.time()

elapsed_time = t1 - t0
print(elapsed_time)
results
```
I have 2 GPUs and this program takes 0.68 seconds to finish.
When I change to a single GPU execution mode:

```
import tensorflow as tf
import numpy as np
import time
import os

os.environ["CUDA_VISIBLE_DEVICES"]="0"

dataset = tf.data.Dataset.from_tensor_slices(tf.random_uniform([1000,4], maxval=4, dtype=tf.int32))
          
print(dataset.output_types)
print(dataset.output_shapes)

iterator = dataset.make_initializable_iterator()
#next_element = iterator.get_next()

tensor_results = []

with tf.device("/gpu:0"):
    for i in range(1000):
        operand = iterator.get_next()
        tensor_result = tf.matmul(tf.reshape(operand,shape=[1,4]), tf.reshape(operand,shape=[4,1]))
        tensor_results.append(tensor_result)


tfconfig = tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)
tfconfig.gpu_options.allow_growth=True

sess = tf.Session(config=tfconfig)

sess.run(iterator.initializer)
t0 = time.time()

results = sess.run(tensor_results)

t1 = time.time()

elapsed_time = t1 - t0
print(elapsed_time)
results
```

It takes the same time to finish (actually single GPU is even faster perhaps due to overhead reasons). Do anyone know where does the problem come from?

python version: Python 2.7.12
tensorflow version: 1.4.0
CUDA version: 8.0
Ubuntu version: Ubuntu 16.04 LTS

Thanks!

**Comment by Lancerchiang** [comment]
@mrry 
expert of distributed tensorflow

**Comment by huangwei2013** [comment]
You may check installed model of the tensorflow

**Comment by Lancerchiang** [comment]
@huangwei2013 Hi thanks for the reply! Do you mean the Cifar10 multi_gpu_train one? That's a queue based approach. I would like to try the dataset here

**Comment by bhack** [comment]
It could be interesting to understand also if the dataset api is ready to work on the shelf with `tf.keras.utils.multi_gpu_model` or we still have the same problem [already described on keras](https://medium.com/rossum/towards-efficient-multi-gpu-training-in-keras-with-tensorflow-8a0091074fb2).

**Comment by joeyearsley** [comment]
A few comments:
1) [Shard your dataset](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#shard)
2) Move the _i_ loop to around a sess.run; here you are expanding your graph to a huge size

**Comment by bhack** [comment]
There was also some recent update in models using dataset api but not strictly related to the multi gpu keras interface. See https://github.com/tensorflow/models/pull/3332.

**Comment by mrry** [comment]
@joeyearsley raises a good point about the loop structure here, which isn't representative of a real training job. In particular, it builds a huge graph that performs every iteration using a different `tf.matmul()` node, whereas it is more common to build a graph that works on a single mini-batch and then calls `sess.run()` multiple times in a loop. The `tf.matmul()` operations multiply two four-element vectors, which is a computation that is too small to benefit from GPU acceleration: the cost to copy the operands to the GPU would be much larger than the time to multiply them... which could potentially be achieved with a couple of SSE instructions. Finally, the code only measures the first time to execute the graph, which I expect will be dominated by the costs of building the large graph in both cases, and not substantially different based on how many GPUs you are using.

I'd recommend that you take a look at the [`tf_cnn_benchmarks.py`](https://github.com/tensorflow/benchmarks/blob/master/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py) code for an example of how to write a well-optimized multi-GPU trainer using `tf.data`. In addition, @karmel has just augmented the official MNIST example with support for [multi-GPU processing](https://github.com/tensorflow/models/blob/fd7b6887fb294e90356d5664724083d1f61671ef/official/mnist/mnist.py#L158), and that example shows some of the easier-to-use library support that has been added for multi-GPU processing. We're continuing to develop this to improve performance and usability together.

**Comment by bhack** [comment]
@mrry Is `tf.keras.utils.multi_gpu_model` working with estimators and dataset api?

**Comment by mrry** [comment]
@bhack I'm not sure: I haven't tried it. If not, we'd appreciate a feature request for that in a new issue!

**Comment by bhack** [comment]
@mrry Probably not cause I've got a segmentation fault with the exactly the same working code just adding `tf.keras.utils.multi_gpu_mode`

**Comment by bhack** [comment]
I don't know how model to estimator converter is in shape. See https://github.com/tensorflow/tensorflow/issues/16468

**Comment by bhack** [comment]
Seems also that the distributed version was not working with the converter. See https://github.com/tensorflow/tensorflow/issues/14504.
