### ISSUE TITLE
Eager: tf.linalg.inv(tf.transpose(mat)) has undefined shape in function with tfe.defun

### ISSUE THREAD

**Issue by traveller59** [tensorflow/tensorflow#16913]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Win10
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.6.0dev20180126(GPU)
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Source code / logs
* No problem in graph mode
```Python
import tensorflow as tf
import numpy as np
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()
@tfe.defun
def test(rect):
    rect_T = tf.transpose(rect)
    print(rect_T.shape)
    print(tf.linalg.inv(rect_T).shape)
    print(tf.linalg.inv(rect).shape)
    print(tf.linalg.inv(tf.transpose(rect)).shape)
rect_tf = tf.constant(np.random.uniform(size=[4, 4]))
test(rect_tf)
```
Output:
```
(4, 4)
(?, ?)
(4, 4)
(?, ?)
```

**Comment by asimshankar** [comment]
Thanks for the report. This is indeed a bug, will send out a fix.
