### ISSUE TITLE
TF fails to compile on Ubuntu 14.04: crosstool_wrapper_driver_is_not_gcc failed

### ISSUE THREAD

**Issue by elanmart** [tensorflow/tensorflow#1692]
Hello, 
I'm trying to build TF from source and I'm getting the error included below. 
I've seen similar issues but none of the fixes works for me.

What doesn't work:
- official "installation and setup" steps (duh...) with bazel 0.2.0
- updating bazel from 0.2.0 to master
- compiling with `--spawn_strategy=standalone`
- including `-fPIC` flag in `gpus/crosstools/CROSSTOOL`
- deleting `-fPIE` flag from the same file

The command I use is:
`bazel build -c opt --config=cuda --spawn_strategy=standalone --verbose_failures //tensorflow/cc:tutorials_example_trainer`

 
the error is:
```
ERROR: /home/marcin/Moje/Software/tensorflow/tensorflow/cc/BUILD:61:1: Linking of rule '//tensorflow/cc:tutorials_example_trainer' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/marcin/.cache/bazel/_bazel_marcin/259f71b95269c287fa42ef117628b45f/tensorflow && \
  exec env - \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc  ...
...
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.a(crc32.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```

the full error message is here:
[https://gist.github.com/elanmart/f462692553e1e53fc540](https://gist.github.com/elanmart/f462692553e1e53fc540)

**Comment by vincentvanhoucke** [comment]
Pretty old unattended bug. Was the issue resolved?

**Comment by zheng-xq** [comment]
I can confirm this is no longer an issue, so closing this issue. 

@elanmart, feel free to reopen if you still see the problem with the latest TensorFlow, Cuda SDK and Cudnn library.
