### ISSUE TITLE
tensorflow lite converter(toco) build error 

### ISSUE THREAD

**Issue by Mikun4619** [tensorflow/tensorflow#16946]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Windows 10(64bit)
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**: tensorflow 1.5.0
- **Python version**: Python 2.7/3.6
- **Bazel version (if compiling from source)**:  bazel 0.9.0
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: No GPU model

### Describe the problem
I try to build the toco that is tensorflow lite converter. 
But I can not success to build. please see below for the details.

### Source code / logs
`C:\tensorflow>bazel build //tensorflow/contrib/lite/toco:toco`
The following error message appears.
> ERROR: Skipping '//tensorflow/contrib/lite/toco:toco': error loading package 'tensorflow/contrib/lite/toco': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_archive//': Traceback (most recent call last):
        File "C:/tensorflow/third_party/repo.bzl", line 88
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/tensorflow/third_party/repo.bzl", line 59, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/tensorflow/third_party/repo.bzl", line 44, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(3) when executing 'C:\tools\msys64\usr\bin\bash.exe -c patch -p1 -d C:/users/r3pc/appdata/local/temp/_bazel_r3pc/x1e5egqw/external/protobuf_archive -i C:/tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout: patching file src/google/protobuf/compiler/cpp/cpp_file.cc
Stderr: Assertion failed: hunk, file ../patch-2.5.9-src/patch.c, line 354
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/contrib/lite/toco': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_archive//': Traceback (most recent call last):
        File "C:/tensorflow/third_party/repo.bzl", line 88
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/tensorflow/third_party/repo.bzl", line 59, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/tensorflow/third_party/repo.bzl", line 44, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(3) when executing 'C:\tools\msys64\usr\bin\bash.exe -c patch -p1 -d C:/users/r3pc/appdata/local/temp/_bazel_r3pc/x1e5egqw/external/protobuf_archive -i C:/tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout: patching file src/google/protobuf/compiler/cpp/cpp_file.cc
Stderr: Assertion failed: hunk, file ../patch-2.5.9-src/patch.c, line 354
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
INFO: Elapsed time: 27.852s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/contrib/lite/toco

- plus info.
The following message appears when I input like this in command line. (for test)
`patch -p1 -d C:/users/r3pc/appdata/local/temp/_bazel_r3pc/x1e5egqw/external/protobuf_archive -i C:/tensorflow/third_party/protobuf/add_noinlines.patch`
> patching file src/google/protobuf/compiler/cpp/cpp_file.cc
Assertion failed: hunk, file ../patch-2.5.9-src/patch.c, line 354
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

`patch -p1 -d C:/users/r3pc/appdata/local/temp/_bazel_r3pc/x1e5egqw/external/protobuf_archive -i C:/tensorflow/third_party/protobuf/add_noinlines.patch --binary`
> patching file src/google/protobuf/compiler/cpp/cpp_file.cc
Hunk #1 succeeded at 750 with fuzz 1 (offset 193 lines).
Hunk #2 succeeded at 825 (offset 169 lines).
Hunk #3 succeeded at 906 with fuzz 2 (offset 169 lines).

I don't know how to add --binary option to script...
ref. https://github.com/tensorflow/tensorflow/issues/10435

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Mikun4619** [comment]
I resolved this problem.
add "--binary" to  58 line in repo.bzl
like this, 
` ctx, ["patch", "-p1", "-d", ctx.path("."), "-i", ctx.path(patch_file) ,"--binary"])`
