### ISSUE TITLE
Tensorflow (0.11.0) returns error while running training and testing scripts. 

### ISSUE THREAD

**Issue by sainisanjay** [tensorflow/tensorflow#16944]
Due to some constraint i am using Tensorflow version 0.11.0, which i installed using bellow commands:
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl
pip install --ignore-installed --upgrade $TF_BINARY_URL

After installation i am successfully able to import Tensorflow in python:
```
cvsion@cvsion:~$ python -c 'import tensorflow as tf; print(tf.__version__)'
0.11.0

cvsion@cvsion:~/Deeplearning/DeepTensorFlow/tensorlayer$ python 
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> 
```

but when i am running my training script its giving error:

> Traceback (most recent call last):
>   File "./testing_nvidia.py", line 8, in <module>
>     import tensorlayer as tl
>   File "/home/cvsion/Deeplearning/DeepTensorFlow/tensorlayer/tensorlayer/__init__.py", line 23, in <module>
>     from . import distributed
>   File "/home/cvsion/Deeplearning/DeepTensorFlow/tensorlayer/tensorlayer/distributed.py", line 9, in <module>
>     from tensorflow.python.training import session_run_hook
> ImportError: cannot import name session_run_hook

Any idea to resolve above issue

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sainisanjay** [comment]
Have I written custom code = Yes
OS Platform and Distribution=  Ubuntu 16.04
TensorFlow installed from = export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl
pip install --ignore-installed --upgrade $TF_BINARY_URL
Bazel version= N/A
CUDA/cuDNN version = CUDA 8.0/cuDNN 6.1
GPU model and memory: 12GB
Exact command to reproduce: python ./testing_nvidia.py

**Comment by cy89** [comment]
I'm sorry, but 0.11.0 is past our support window.

**Comment by rthadur** [comment]
As we do not support 0.11.0 , will be closing this request. Please try latest versions. Thank you.
