### ISSUE TITLE
Android Bazel Build Error

### ISSUE THREAD

**Issue by MCoder1** [tensorflow/tensorflow#1695]
I'm at the step where I enter `bazel build //tensorflow/examples/android:tensorflow_demo` and I get the following output:
```
ERROR: /Users/mchong5/tensorflow/WORKSPACE:5:13: invalid character: '?'.
ERROR: /Users/mchong5/tensorflow/WORKSPACE:5:14: invalid character: '?'.
ERROR: /Users/mchong5/tensorflow/WORKSPACE:5:50: invalid character: '?'.
ERROR: /Users/mchong5/tensorflow/WORKSPACE:5:51: invalid character: '?'.
ERROR: /Users/mchong5/tensorflow/WORKSPACE:10:11: invalid character: '?'.
ERROR: /Users/mchong5/tensorflow/WORKSPACE:10:12: invalid character: '?'.
ERROR: /Users/mchong5/tensorflow/WORKSPACE:10:46: invalid character: '?'.
ERROR: /Users/mchong5/tensorflow/WORKSPACE:10:47: invalid character: '?'.
ERROR: /Users/mchong5/tensorflow/WORKSPACE:5:49: syntax error at '?': expected ,
ERROR: /Users/mchong5/tensorflow/WORKSPACE:6:1: non-keyword arg after keyword arg.
ERROR: no such package 'external': Error encountered while dealing with the WORKSPACE file: Failed to parse WORKSPACE file.
INFO: Elapsed time: 0.557s
```

My WORKSPACE is modified as follows... I'm not sure why it is telling me there are invalid characters
```
android_sdk_repository(
    name = "androidsdk",
    api_level = 23,
    build_tools_version = "23.0.2",
    path = “/Users/mchong5/Library/Android/sdk”,
)

android_ndk_repository(
    name="androidndk",
    path=“/Users/mchong5/android-ndk-r11b/”,
    api_level=21)
```

For reference, I am on OSX 10.11 using Bazel 0.2.0 built from source with tensorflow 0.7.1

**Comment by andrewharp** [comment]
It looks like you have non-ascii quotes around the paths. Did you use a rich text editor to make the edits?

**Comment by MCoder1** [comment]
It looks like that was it! I didn't even catch that the quotations looked different. Thanks

**Comment by pnt1614** [comment]
I am also at this step and I have a similar problem. When I entered "bazel build -c opt //tensorflow/examples/android:tensorflow_demo", I got an error message: "ERROR: Analysis of target '//tensorflow/examples/android:tensorflow_demo' failed; build aborted."

My WORKSPACE is:

# Uncomment and update the paths in these entries to build the Android demo.
android_sdk_repository(
    name = "androidsdk",
    api_level = 26,
    # Ensure that you have the build_tools_version below installed in the
    # SDK manager as it updates periodically.
    build_tools_version = "26.0.1",
    # Replace with path to Android SDK on your system
    path = "/Users/ST/AppData/Local/Android/Sdk/",
)

# Android NDK r12b is recommended (higher may cause issues with Bazel)
android_ndk_repository(
    name="androidndk",
    path="/Users/ST/AppData/Local/Android/Sdk/ndk-bundle/",
    # This needs to be 14 or higher to compile TensorFlow.
    # Please specify API level to >= 21 to build for 64-bit
    # archtectures or the Android NDK will automatically select biggest
    # API level that it supports without notice.
    # Note that the NDK version is not the API level.
    api_level=14)

I am using Windows 10. Is there anyone knowing how to solve this problem?
