### ISSUE TITLE
Row wise lookup table in Tensorflow

### ISSUE THREAD

**Issue by a-sehgal** [tensorflow/tensorflow#16955]
Currently I have a matrix in which each row is a lookup table. Corresponding to it I have a coded matrix with the same number of rows as the lookup table. e.g.

> LookupTable (matrix size 100, 32)

> CodedMatrix (matrix size 100, 1000)

So the lookup table values match to the corresponding row of the coded matrix. The code matrix contains numbers from 0 to 31 which have a corresponding value in the Lookup table for that specific row.

The final output of this should be 

> DecodedMatrix(matrix size 100, 1000)

In which each value of the row is replaced with it's corresponding lookup output.

Currently in numpy I use a for loop, because at the end I sum up the decoded matrix along the row axis for the final output. The code looks like this

       out = sum([C[L] for C,L in zip(CodedMatrix, LookupTable)])

which is a still inefficient. But in Tensorflow I use

     nRows = tf.constant(100, name="nRows")
     n     = tf.Variable(tf.constant(0))

     def cond(n, out):
         return n < nRows

     def body(n, out):  
         out = out + tf.gather(LookupTable[m,:], CodedMatrix[m,:])
         return n+1, out

     out = tf.while_loop(cond, body, [n, out])[1]

This execution takes a lot of time, because each time a new tensor is created and using the loop isn't very efficient.

Is there a way to do this without using while loop? Does tf.gather have any setup to do lookup like this?

Have I written custom code - Yes
OS Platform and Distribution - Mac OS X High Sierra
TensorFlow installed from - Source
TensorFlow version - 1.5.0-rc0
Bazel version - 0.5.4
CUDA/cuDNN version - N/A
GPU model and memory - N/A
Exact command to reproduce - Provided aboce

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by a-sehgal** [comment]
Updated

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
