### ISSUE TITLE
No package nasm

### ISSUE THREAD

**Issue by NguyenAnhTien** [tensorflow/tensorflow#16967]
On Release version v1.5.0.
In the file tensorflow/workspace.bzl.
At the line 208.

The link [http://pkgs.fedoraproject.org/repo/pkgs/nasm/nasm-2.12.02.tar.bz2/d15843c3fb7db39af80571ee27ec6fad/nasm-2.12.02.tar.bz2]() is not exist any more.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by NguyenAnhTien** [comment]
OS Platform and Distribution: Ubuntu 16.04
TensorFlow installed from: source
TensorFlow version: v1.5.0
Bazel version: 0.10.0
CUDA/cuDNN version: 9.1/7.0.5
GPU model and memory: GTX 1050 4Gbs

**Comment by bignamehyp** [comment]
Please use link at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L214 instead. Thanks
