### ISSUE TITLE
Go API - graph.get_tensor_by_name

### ISSUE THREAD

**Issue by jojo05** [tensorflow/tensorflow#16971]
What is the equivalent of the Python graph.get_tensor_by_name in Go?

thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jojo05** [comment]
Have I written custom code
- no

OS Platform and Distribution
- x86_64, Fedora Core 27 

TensorFlow installed from
- python
TensorFlow version
- 1.5.0
Bazel version
- n/a
CUDA/cuDNN version
- n/a
GPU model and memory
- n/a
Exact command to reproduce
- want to use equivalent of graph.get_tensor_by_name in Go

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by jojo05** [comment]
I thought about posting here first because in Python, get_tensor_by_name() is a method of the Graph type but in Golang the API seems to be quite different and the design doesn't seem to be documented anywhere. 
Any pointers that would also be useful (apart from godoc.org) ?

**Comment by asimshankar** [comment]
I'd still recommend posting on StackOverflow for a few reasons. (a) To keep this focused on bugs and feature requests, (b) To make such support questions more accessible to others.

Anyway, the short answer would be `Graph.Operation(<name>).Output(<index>)` in Go. 
For more details, again, I'd recommend StackOverflow.

Thanks!
