### ISSUE TITLE
Installation Tensorflow from source stuck at Downloading grpc 

### ISSUE THREAD

**Issue by josephgeorgek** [tensorflow/tensorflow#17007]
Installation Tensorflow 1.4.0-rc0 from source on RHEL 7.4 

Installation went fine with Python3.6, CUDA 9.1,  CUDNN 7.0.5

cd tensorflow-1.4.0-rc0
./configure
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

However, it is not moving from 
INFO: Downloading https://mirror.bazel.build/github.com/grpc/grpc/archive/781fd/6f6ea03645a520cd5c675da67ab61f87e4b.tar.gz

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by josephgeorgek** [comment]
Kindly find the details below

Have I written custom code - No/NA
OS Platform and Distribution - RHEL 7.4 Codename: Maipo 
TensorFlow installed from : https://github.com/tensorflow/tensorflow/archive/v1.4.0-rc0.zip
TensorFlow version - 1.4.0
Bazel version - https://github.com/bazelbuild/bazel/releases/download/0.5.4/bazel-0.5.4-installer-linux-x86_64.sh
CUDA/cuDNN version - cudnn-9.1-linux-x64-v7.tgz 
GPU model and memory - eForce GTX 1080 Ti, 11 GB
Exact command to reproduce  - cd tensorflow-1.4.0-rc0
./configure
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
