### ISSUE TITLE
Please add a working example for tf.contrib.factorization.KMeansClustering in tutorial example

### ISSUE THREAD

**Issue by sandeepkumar8713** [tensorflow/tensorflow#17002]
### Describe the problem
Hi, 

I have been trying to use tf.contrib.factorization.KMeansClustering for clustering. I got the documentation in [link](https://www.tensorflow.org/api_docs/python/tf/contrib/factorization/KMeansClustering). But it did not specify how to give input. There is no input argument here : 

__init__(
    num_clusters,
    model_dir=None,
    initial_clusters=RANDOM_INIT,
    distance_metric=SQUARED_EUCLIDEAN_DISTANCE,
    random_seed=0,
    use_mini_batch=True,
    mini_batch_steps_per_iteration=1,
    kmeans_plus_plus_num_retries=2,
    relative_tolerance=None,
    config=None
)

So I request you to please add a working example to train and predict using kmeansClustring in tutorial example.

Thank You

**Comment by byronyi** [comment]
I’d like to see a working example as well.

**Comment by cy89** [comment]
@sandeepkumar8713 do the score() or evaluate() methods not do what you want in some way?

**Comment by sandeepkumar8713** [comment]
@cy89 no they don't do that. First I have to train. For that i to have describe the feature. In init() there is no parameter to do so.

**Comment by ccolby** [comment]
@sandeepkumar8713 The error is because your input Tensor (X) was created outside the graph that the Estimator code creates during the kmeans.train() invocation. The solution is to delay the creation of that Tensor by putting it inside the input_fn lambda, which will be invoked within train().

Below is a complete example. Let me know if you encounter difficulties.

```
k = 5
n = 100
variables = 2
points = np.random.uniform(0, 1000, [n, variables])
input_fn=lambda: tf.train.limit_epochs(tf.convert_to_tensor(points, dtype=tf.float32), num_epochs=1)
kmeans=tf.contrib.factorization.KMeansClustering(num_clusters=k, use_mini_batch=False)
previous_centers = None
for _ in xrange(10):
  kmeans.train(input_fn)
  centers = kmeans.cluster_centers()
  if previous_centers is not None:
    print 'delta:', centers - previous_centers
  previous_centers = centers
  print 'score:', kmeans.score(input_fn)
print 'centers:', centers
cluster_indices = list(kmeans.predict_cluster_index(input_fn))
for i, point in enumerate(points):
  cluster_index = cluster_indices[i]
  print 'point:', point, 'is in cluster', cluster_index, 'centered at', centers[cluster_index]
```

**Comment by ccolby** [comment]
Also, you can see other examples in [kmeans_test.py](https://github.com/tensorflow/tensorflow/blob/r1.5/tensorflow/contrib/factorization/python/ops/kmeans_test.py).

**Comment by cy89** [comment]
@ccolby thanks for jumping in!

**Comment by sandeepkumar8713** [comment]
### System information
- **OS Platform and Distribution**: Open SUSE Leap 42.3
- **TensorFlow installed from**: python pip
- **TensorFlow version**: 1.5.0
- **Python version**: 2.7

### Problem Description
@ccolby Thank you very for explaining with code. Now I am facing a different problem while trying to save the above trained model. Can you please help me with that.

### Source code 
```
def serving_input_receiver_fn():
    feature_spec = {"x": tf.FixedLenFeature(dtype=tf.float32, shape=[2])}
    model_placeholder = tf.placeholder(dtype=tf.string,shape=[None],name='input')
    receiver_tensors = {"model_inputs": model_placeholder}
    features = tf.parse_example(model_placeholder, feature_spec)
    return tf.estimator.export.ServingInputReceiver(features, receiver_tensors)

def trainAndSaveModel():
    k = 5
    n = 1000
    variables = 2

    points = np.random.uniform(0, 1, [n, variables])
    input_fn = lambda: tf.train.limit_epochs(tf.convert_to_tensor(points, dtype=tf.float32), num_epochs=1)
    kmeans = tf.contrib.factorization.KMeansClustering(num_clusters=k, use_mini_batch=False)
    previous_centers = None
    for _ in xrange(10):
        kmeans.train(input_fn)
        centers = kmeans.cluster_centers()
        if previous_centers is not None:
          print 'delta:', centers - previous_centers
        previous_centers = centers
        print 'score:', kmeans.score(input_fn)

    modelPath = kmeans.export_savedmodel(export_dir_base="/path/",serving_input_receiver_fn=serving_input_receiver_fn)
    return modelPath
```
### Logs
`ValueError: export_outputs must be a dict and not<type 'NoneType'>`

I am getting this error while calling **serving_input_receiver_fn()** function. Same function is working for **tf.estimator.DNNClassifier** but not for **tf.contrib.factorization.KMeansClustering**.

**Comment by cy89** [comment]
@sandeepkumar8713 the stack trace ought to tell us a lot about what wasn't supplied and where. Can you add it, please?

**Comment by ccolby** [comment]
@sandeepkumar8713 Can you try r1.6 of kmeans.py? The current release (r1.5) did not set export_outputs in the EstimatorSpec. That was a bug.

**Comment by sandeepkumar8713** [comment]
@ccolby @cy89 Thank you for the suggestion. I upgraded my tensorflow to r1.6 version and the above code is working now.

Can you please suggest a way to import `cluster_centers()` of `tf.contrib.factorization.KMeansClustering` from the above saved model.
 
### Source Code

```
def restore(export_dir):
    sess = tf.Session()
    tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], export_dir)
    from tensorflow.contrib import predictor

    predict_fn = predictor.from_saved_model(export_dir)
    dataList = np.random.uniform(0, 1, [10, 2])

    inputList=[]
    for test_data in dataList:
        predictor_input_feature = {
            'x': tf.train.Feature(
                float_list=tf.train.FloatList(
                    value=test_data
                )
            )
        }

        input_for_predictor = tf.train.Example(
            features=tf.train.Features(
                feature=predictor_input_feature
            )
        )

        serialized_input = input_for_predictor.SerializeToString()
        inputList.append(serialized_input)

    results = predict_fn({"model_inputs": inputList})
    clusterIndices = results['output']

    for i, point in enumerate(dataList):
       clusterIndex = clusterIndices[i]
       print 'point:', point, 'is in cluster', clusterIndex
       #print 'point:', point, 'is in cluster', clusterIndex, 'centered at', centers[clusterIndex]

```
I would like to execute the last commented line.

**Comment by ccolby** [comment]
@sandeepkumar8713 I haven't worked with SavedModels, so I'd need to dig into the details. However, note that:
```
kmeans.cluster_centers()
```
is equivalent to
```
tf.train.load_variable(kmeans.model_dir, 'clusters')
```
Will that work for you? I am not sure if there is a way to get this variable out of the SavedModel.

**Comment by sandeepkumar8713** [comment]
@ccolby Even I think that currently there is no specify function to extract `cluster_centers` from the SavedModel. To use `tf.train.load_variable(kmeans.model_dir, 'clusters')` I will have to save checkpoints.

**Comment by ccolby** [comment]
@sandeepkumar8713 That is correct, but you don't need to do anything special to save the checkpoints. The `KMeansClustering.train` method will save the checkpoint for you. For example, the first code snippet that I posted above will work identically if you replace:
```
centers = kmeans.cluster_centers()
```
with
```
centers = tf.train.load_variable(kmeans.model_dir, 'clusters')
```
Please note that the variable name `'clusters'` should be considered an internal implementation detail that could change in future releases. Ideally, `tf.contrib.factorization` would include a public interface that hides that detail. But for now, this should work.

I'll clean up the working example in this thread and add it to the `KMeansClustering` documentation.

I believe exposing the cluster centers in the SavedModel would require a minor redesign of the `KMeansClustering` Estimator.

**Comment by sandeepkumar8713** [comment]
@ccolby Ok, looking forward to see a interface that extract cluster centers from SavedModel.  By the way, thank you for explaining all this. It is a great help.

**Comment by cy89** [comment]
@ccolby when you're happy with the KMeansClustering documentation, please close. 

@sandeepkumar8713 could you please open a separate issue for exposing clustering centers, tag @ccolby and this bug, and note that it's a feature request?

**Comment by avigyan1009** [comment]
@ccolby  i am KMeansClustering in distribute mode using TF_CONFIG but it got stuck after below warining
"WARNING:tensorflow:From /home/hdpuser/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/factorization/python/ops/clustering_ops.py:196: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead"
Code:
import pandas as pd
import tensorflow as tf
import numpy as np
from sklearn.metrics.pairwise import paired_distances
path_in = "/home/hdpuser/data/ml/sports_tfid_01.txt"
# Loading and reading data
print("testing tensorflow")
df = pd.read_csv(path_in).astype(np.float32)
relative_tolerance = 0.0001
features_ = list(df.columns)
# To extract usefull data
df_feature = df
x={"x": np.array(df_feature)}

train_input_fn=(lambda: [x, None])
# Define the test inputs
 
print("after train input fun")
kmeans = tf.contrib.factorization.KMeansClustering(num_clusters=4, model_dir="./iris_model",relative_tolerance=relative_tolerance)
print("after kmeans")
ret = kmeans.train(input_fn=train_input_fn)
print("after train")
print("score",kmeans.score(input_fn=train_input_fn))

**Comment by ccolby** [comment]
@avigyan1009 That warning shouldn't prevent anything from working.

**Comment by cy89** [comment]
@ccolby has an update on the internal side that should become visible through the normal merge process. 
I'll close this; please reopen if there is more to do.

**Comment by wileeam** [comment]
@cy89 Could you point to the revision of the merge process where the update you referred has happened on the r1.6 branch? I don't manage to find it (or maybe it hasn't happened yet?).

**Comment by ccolby** [comment]
It's not in r1.6, but it has been merged into the master. The content is essentially what is in this thread (a documented example). Essentially no change to the code.

**Comment by avigyan1009** [comment]
@ccolby @cy89 While training tf.contrib.factorization.kmeanclustering in r1.5 on 3 node cluster using cpu throwing error 'UTF-8' not encode, i had provided data in input function as df.asmatrix.

**Comment by wileeam** [comment]
Aha! Okay, awesome! I saw the documented example in the master as you said and was confused looking for something else.
Thanks! :)
