### ISSUE TITLE
Integration of "Tensor Comprehensions"?

### ISSUE THREAD

**Issue by PhilJd** [tensorflow/tensorflow#17017]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Not relevant
- **TensorFlow installed from (source or binary)**: Not relevant
- **TensorFlow version (use command below)**: Not relevant
- **Python version**: Not relevant
- **Bazel version (if compiling from source)**: Not relevant
- **GCC/Compiler version (if compiling from source)**: Not relevant
- **CUDA/cuDNN version**: Not relevant
- **GPU model and memory**: Not relevant
- **Exact command to reproduce**: Not relevant

### Describe the problem
FAIR just released an initial version of their [Tensor Comprehension Framework](https://research.fb.com/announcing-tensor-comprehensions/) which I think is a really clever concept. The Tensor comprehension library allows to define functions with a syntax similar to einstein-notation and then compiles these functions into fast GPU code via evolutionary search. Is this something you would consider including into the core or would you rather favor an integration as a separate framework?

Cheers,
Phil

**Comment by bignamehyp** [comment]
Thanks for your suggestion. Please check out XLA.

**Comment by neocxi** [comment]
@bignamehyp how is XLA a replacement of Tensor Comprehension?

**Comment by nicolasvasilache** [comment]
@neocxi it's not indeed. If we omit the user-facing and language-level aspects of TC, our positioning is strictly below the graph-level abstraction. TC gives a first reasonable answer to: "I have a subgraph, what is a good implementation of that subgraph on target hardware X". 
Our hope is that your favorite graph-level compiler/engine (XLA, NNVM, nGraph, TensorRT, Caffe2, ONNX, ...) starts providing HPC kernel synthesis. 
But I'm sure all these aforementioned solutions have something that fits the bill in the works.

**Comment by ff7250** [comment]
I alt for the auto-tuner and the polyhedral solution to maximize the NN implementation since it's already kind of canonicalized.

**Comment by cgarciae** [comment]
Why is this issue closed?
