### ISSUE TITLE
tfcompile tf.cond not dominated by switch nodes

### ISSUE THREAD

**Issue by jhunsaker** [tensorflow/tensorflow#17015]
Using the following example:

```
graph = tf.Graph()
with graph.as_default():
  x = tf.placeholder(name='x', shape=(2,), dtype=tf.float64)
  y = tf.cond(x[0] > x[1], partial(lambda x: x[0], x), partial(lambda x: x[1], x))
```

Compiling with:
`
tfcompile --graph=test_graph.pb --config=test_config.pb --entry_point=test_func --cpp_class=test --out_object=test.o --out_header=test.hpp --gen_program_shape=true --target_cpu=haswell
`

Gives the following error:
`
2018-02-13 16:32:27.484808: F tensorflow/compiler/aot/tfcompile_main.cc:140] Non-OK-status: status status: Failed precondition: Value {name:'cond/strided_slice_1' id:20 op device:{/device:XLA_CPU_JIT} def:{cond/strided_slice_1 = StridedSlice[Index=DT_INT32, T=DT_DOUBLE, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](cond/strided_slice_1/Switch, cond/strided_slice_1/stack, cond/strided_slice_1/stack_1, cond/strided_slice_1/stack_2)}} not dominated by switch nodes.
`

Would expect code to be generated similar to:
```
double test_func( double* x )
{
  if (x[0] > x[1] )
    return x[0];
  else
    return x[1];
}
```

tensorflow version 1.5.0
RHEL 7.3 64bit
tensorflow built from source 
python 2.7
bazel 0.7
gcc 4.8.5

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jhunsaker** [comment]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes, provided above
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: RHEL 7.3 64bit
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.5.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.7
- **GCC/Compiler version (if compiling from source)**: gcc 4.8.5
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: provided above

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by reuben** [comment]
@jhunsaker did you get around to asking about this on SO? I'm hitting the same problem.
