### ISSUE TITLE
Feature/PR Idea - mean IoU for vector of thresholds

### ISSUE THREAD

**Issue by petermetz** [tensorflow/tensorflow#17018]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: `False`
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sierra 10.12.6
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.0.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: `None`
- **GCC/Compiler version (if compiling from source)**: `None`
- **CUDA/cuDNN version**: `None`
- **GPU model and memory**: Radeon Pro 560 4096 MB - Intel HD Graphics 630 1536 MB
- **Exact command to reproduce**: `None`

### Summary
I'd love to have a convenient, clean API for expressing the calculation of mean IoU for a set of thresholds instead of a single value. 
Like the way it's described here: https://www.kaggle.com/c/data-science-bowl-2018#evaluation

I'm planning on submitting a PR with a solution unless I get told here that the idea is explicitly being opposed by the decision-makers. Please let me know if you'd consider merging something like this in and I'll move to the next phase.

I'm assuming that the implementation is possible without having to get knee deep in CUDA C/C++ given that there's already a mean IoU feature here and I would (hopefully) just need to extend that in a backward compatible way so that it takes some optional extra information in the form of a vector of thresholds =>
 https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/metrics_impl.py#L948:

Tips and guidance are most welcome, thank you in advance for any help and the verdict as well.

**Comment by cy89** [comment]
@drpngx looks like "mean_iou" is your code. How do you feel about @petermetz 's proposal?

**Comment by drpngx** [comment]
SGTM
CC @aquariusjay

**Comment by petermetz** [comment]
Thanks @drpngx @cy89 I'll move on to the next phase.
