### ISSUE TITLE
MLP prediction is 3~4x slower than theano/pytorch

### ISSUE THREAD

**Issue by JiaweiZhuang** [tensorflow/tensorflow#17028]
(Moving from keras-team/keras#9388)
For a simple 2-hidden-layer MLP, TF is 3~4x slower than pytorch and theano. This is only for **prediction**, not training, and it is only on **CPU**. Please see this [GitHub gist](https://gist.github.com/JiaweiZhuang/c3350f7a89db3d5a98c6a2c0228ceea9/eb4eec9056b02b1ac2e0e039f646347c02885309) for timing.

For reproducibility, the test was done on AWS EC2 c5.large. Two different builds were tested and showed similar results. One is the pre-built [AWS deep learning AMI](https://aws.amazon.com/machine-learning/amis/) (ami-e07e779a). Another is installing conda on a fresh Ubuntu machine and then installing TF with `pip`.

My questions are:
1. Is this performance difference expected? I assume that TF shouldn't be that slow. 
2. @fchollet suggested that the TF installation was broken. If so, what's the correct way to install TensorFlow to ensure good performance? I also tried [other installation methods on the official docs](https://www.tensorflow.org/install/install_linux), as such native Python and pip, but didn't get better performance.

### System information
- **Have I written custom code**: Almost all built-in functions
- **OS Platform and Distribution**: Linux Ubuntu 16.04 
Test env 1: AWS deep learning AMI Ubuntu Version (ami-e07e779a)
Test env 2: AWS base Ubuntu AMI (ami-66506c1c)
- **TensorFlow installed from**: 
Test env 1: TensorFlow/Keras/PyTorch are all provided by that AMI.
Test env 2: Installed from binary, i.e. `pip install tensorflow` and `pip install keras`. PyTorch was installed by `conda install pytorch`.
- **TensorFlow version**: 1.5.0
- **Python version**: 3.6
- **Bazel version**: N/A (from binary)
- **CUDA/cuDNN version**: CPU-only
- **GPU model and memory**: CPU-only
- **Exact command to reproduce**: Please follow this [GitHub gist](https://gist.github.com/JiaweiZhuang/c3350f7a89db3d5a98c6a2c0228ceea9/eb4eec9056b02b1ac2e0e039f646347c02885309).

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version

**Comment by rajatmonga** [comment]
For TF, the code you have is suboptimal. Modifying the following should help:

Replace:
X_tf = tf.placeholder(tf.float32, shape=(None, n_feature), name="X")
with:
X_tf = tf.Variable(X)

And change the next cell to:

with tf.Session() as sess:
    init.run()
    out.eval()  # Certain optimization passes are run on the first eval for a new graph
    %timeit out.eval()

**Comment by JiaweiZhuang** [comment]
> For TF, the code you have is suboptimal. Modifying the following should help:

Thanks, but this further slows down TF by 2x... Please see this [updated gist](https://gist.github.com/JiaweiZhuang/c3350f7a89db3d5a98c6a2c0228ceea9/05823858b19620a0367716459eb01f6e153ea27f)

**Comment by rajatmonga** [comment]
Looks like there's a fair bit of noise in how I have been trying this. One issue that does seem to hold:
- For TF 1.5 and before the default CPU binary isn't optimized e.g. isn't built with AVX etc.
- TF 1.6.0rc0 includes AVX (could still be better for the AMI you mention if built with the best options).

Created a [colab notebook](https://drive.google.com/file/d/1VTNncnaN0_4u6VT7hmiPd6WvjXohO_1H/view?usp=sharing) with some of your GIST  and running there (with TF 1.6rc) seems to give similar results. Note: It doesn't match your numbers for either PyTorch or TF, and there was some noise.

See [Optimizing for CPU](https://www.tensorflow.org/performance/performance_guide#optimizing_for_cpu) in the performance guide for more details.

**Comment by JiaweiZhuang** [comment]
Thanks for pointing out the AVX issue! 1.6rc1 does increase the performance by 40% (from 600 ms to 360 ms), but it is still 2~3x slower than PyTorch (130 ms) in my test environment (EC2 c5.large). Please see this [updated Gist](https://gist.github.com/JiaweiZhuang/c3350f7a89db3d5a98c6a2c0228ceea9/e5371704fa09be2f530a4e503a027fd82891f3a1) for details.

TensorFlow is installed by:
```
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.6.0rc1-cp36-cp36m-linux_x86_64.whl
```

**Comment by rajatmonga** [comment]
There doesn't seem to be an inherent performance difference even though we don't benchmark the specific case you mention. You may get better performance following the instructions in [Optimizing for CPU](https://www.tensorflow.org/performance/performance_guide#optimizing_for_cpu) or you can try installing the [TensorFlow binary from Intel](https://anaconda.org/intel/tensorflow) just to try it out (Note it is still on TF 1.4). 
Copying their instructions here:
`pip install -i https://pypi.anaconda.org/intel/simple tensorflow`
or
`conda install -c intel tensorflow` 

Please continue to look at the [performance guide](https://www.tensorflow.org/performance/performance_guide) to get the best performance for TensorFlow.

**Comment by JiaweiZhuang** [comment]
> you can try installing the TensorFlow binary from Intel just to try it out

Installing Intel's tensorflow binary does remove the performance difference. Now tensorflow is as fast as pytorch, although Keras still adds a significant overhead (3x slow down). The timing is available in the [updated Gist](https://gist.github.com/JiaweiZhuang/c3350f7a89db3d5a98c6a2c0228ceea9).

Thanks again for the help! Let me close this issue.
