### ISSUE TITLE
Print operation flattens the tensors

### ISSUE THREAD

**Issue by pronobis** [tensorflow/tensorflow#1702]
### Environment info

Operating System: Linux
Using: pip, 0.7.1 for Python 3
### Steps to reproduce

Run:

```
a=tf.constant([[1], [2]])
b=tf.Print(a, [a])
```
### Output

```
I tensorflow/core/kernels/logging_ops.cc:79] [1 2]
```

while the tensor evalutes to:

```
array([[1],
       [2]], dtype=int32)
```
### Expected output

```
I tensorflow/core/kernels/logging_ops.cc:79] [[1], [2]]
```

**Comment by keveman** [comment]
Thanks for filing this issue. `tf.Print` is primarily as a tool for debugging during graph execution. Making the output nicely formatted is not going to be high priority for us in the near future. But the code to print out the tensor is here [1]. I am marking this issue as 'Contributions welcome' :)

[1] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.cc#L628

**Comment by guotong1988** [comment]
If anyone haven't fix this issue , I want to working on it ! I have submitted the contribution license today.

**Comment by guotong1988** [comment]
@mrry @keveman 
My solution is , cut the total array into the format. 
For example, cut a tensor of shape (2,2) with the total-array data 1,2,3,4 to print [[1,2][3,4]]

Wondering if there exists a method that do the same?

**Comment by zffchen78** [comment]
This might be easier. tf.Print was created before we have convenient ways to calling python runtime:

`
def Print(inp, data):
  def np_print(*args):
    for x in args:
      print(x)
  return tf.with_dependencies([tf.py_func(np_print, data, [])], inp)

g = tf.Graph()
with g.as_default():
  x = tf.random_uniform([2, 2])
  y = tf.random_uniform([2, 2])
  z = tf.random_uniform([2, 2])
  x = Print(x, [x, y, z])

with tf.Session(graph=g) as sess:
  x.eval()
`

**Comment by Mistobaan** [comment]
Is this issue fixed?

**Comment by guotong1988** [comment]
@Mistobaan  Yes, fixed

**Comment by DomenicD** [comment]
So now I get this error when I try and print some gradients:
ValueError: Shapes must be equal rank, but are 3 and 2
	From merging shape 10 with other shapes. for 'Print/packed' (op: 'Pack') with input shapes: [2,1,2], [2,2], [2,1,2], [2,2], [2,2,2], [2,2], [2,2,2], [2,2], [2,2,1], [2,1], [2,2,1], [2,1].
