### ISSUE TITLE
Problem compiling on mac os x TF 1.6

### ISSUE THREAD

**Issue by fcacarminati** [tensorflow/tensorflow#17046]
Hello I am on Mac Os X

Darwin fcamacbook.dyndns.cern.ch 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

and I have the latest gcc

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Found CUDA installation: /usr/local/cuda, version 8.0

I have python 3.6.4 from homebrew

When I try to compile the master of TF from github with mkl support and -march=native I have

ERROR: /usr/local/tensorflow/tensorflow/core/BUILD:1574:1: C++ compilation of rule '//tensorflow/core:lib_hash_crc32c_accelerate_internal' failed (Exit 1)
clang: error: unsupported option '-fopenmp'
Target //tensorflow/tools/pip_package:build_pip_package failed to build

Thanks for help.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by fcacarminati** [comment]
Thanks for your message. I am sorry I was not clearer, but I thought all the info you are asking was in my posting:

OS platform and distribution:
-----------------------------
Darwin fcamacbook.dyndns.cern.ch 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

aka 

macOS High Sierra version 10.13.3 (17D47)

TensorFlow installed from & Version
------------------------------------

master from github

bazel version
-------------

Build label: 0.10.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 10 02:02:06 +50057 (1517480013726)
Build timestamp: 1517480013726
Build timestamp as int: 1517480013726

CUDA/cuDNN version & GPU model and memory
-------------------------------------------------

I am not using CUDA / GPU

Exact command to reproduce
------------------------------

Configure TF with mkl support & 

bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Comment by freedomtan** [comment]
As the message said you were using the clang from Xcode, which doesn’t support OpenMP. What you should do is either disabling OpenMP or using clang or gcc with OpenMP

**Comment by fcacarminati** [comment]
Hello,
  thanks for your answer. In fact support is there but a bit complex to get at. See this interesting article

https://iscinumpy.gitlab.io/post/omp-on-high-sierra/

Otherwise, any suggestion on how to tell bazel to change compiler? But then, should I compile the whole of python with the new compiler?

**Comment by fcacarminati** [comment]
Reply to myself... telling bazel to use a different complier seems to be a project in itself

https://github.com/bazelbuild/bazel/wiki/About-the-CROSSTOOL

**Comment by freedomtan** [comment]
change `$PATH` and/or `$CC` could help. E.g., the gcc I used is `/opt/local/bin/gcc-mp-6`, so I add `/opt/local/bin` to my `$PATH` and do something like
`
CC=gcc-mp-6 bazel build --config .....
`

**Comment by gunan** [comment]
MKL support for macos is still not available.
I am blocked on a few bazel bugs.
Please watch #10685 for updates.

**Comment by mjadczak** [comment]
Please let me know if this is the wrong place, but I'm also trying to compile TF on macOS and having trouble with changing the compiler (trying to use MKL, but also just to compile with openMP and native arch extensions). Setting CC and CXX doesn't work, because the CROSSTOOL in the project is configured to use `xcrun` which uses the system clang with no openMP support. I can only see the CROSSTOOL in the generated bazel files (after starting a build)—I can't work out where this all is configured.

**Comment by freedomtan** [comment]
if Xcode is installed, you need BAZEL_USE_CPP_ONLY_TOOLCHAIN=1, see this [stackoverflow entry](https://stackoverflow.com/questions/47624689/how-to-set-c-compiler-on-os-x-with-bazel)
