### ISSUE TITLE
Hello, I am interested in collaborating with your project, serving as a translator to Spanish since it is my native language. I can translate any document in .md

### ISSUE THREAD

**Issue by LuigiBaute** [tensorflow/tensorflow#17044]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by LuigiBaute** [comment]
Yes I can update it, and no I don't have experience in the field, I'm interested in contributing by translating over a thousand words texts... if interested let me know..

**Comment by drpngx** [comment]
Thank you for volunteering! I'm not sure what our multi-lingual plans are. @MarkDaoust ?

**Comment by LuigiBaute** [comment]
my intention is to translate the dc to spanish so it gets the attention of the spanish speaking people, let me know if you guys approve it so we can start working on it!, cheers!

**Comment by MarkDaoust** [comment]
We're seeing more and more people eager to contribute to translations (for example #16871).

But we don't have infrastructure to support this. We're looking into it.

+@ewilderj 
+@wolffg

**Comment by drpngx** [comment]
FYI we just released our [ML course](https://developers.google.com/machine-learning/crash-course/?hl=es-419).
