### ISSUE TITLE
Get variable mapping (dictionary) after checkpoint restore

### ISSUE THREAD

**Issue by Yagun** [tensorflow/tensorflow#17068]
It is a feature request.

Please provide a way to get the list of Tensorflow variables restored from a checkpoint and corresponding Python variables.

More info:

Consider that you have this code:

```
    matrix_1 = tf.Variable([[1, 2], [3, 4]], name="matrix1")
    matrix_2 = tf.Variable([[5, 6], [7, 8]], name="matrix2")
```

When a tensorflow checkpoint is created it has matrix1 and matrix2 variables saved. It is easy to understand that matrix1 (in TF namespace) corresponds to matrix_1 (in Python namespace).

Now consider that the code is:

```
    matrix_1 = tf.Variable([[1, 2], [3, 4]])
    matrix_2 = tf.Variable([[5, 6], [7, 8]])
```

A tensorflow checkpoint will have Variable_1:0 and Variable_2:0 variables saved. And it is not obvious at all that Variable_1:0 (in TF namespace) corresponds to matrix_1 (in Python namespace). Especially if there are dozens of variables.

There should be a way to get a list of corresponding variables. For example:
```
Variable_1 = matrix_1
Variable_2 = matrix_2
...
Variable_100 = relu_1_weights
```

**Comment by cy89** [comment]
@asimshankar is there already a way to do this; might it be a reasonable feature request, and/or should I mark "contributions welcome"?

**Comment by asimshankar** [comment]
@Yagun : The name of the variable as far as TensorFlow is concerned is available via the `.name` property. For example:

```python
matrix_1 = tf.Variable([[1, 2], [3, 4]])
matrix_2 = tf.Variable([[5, 6], [7, 8]])
print(matrix_1.name)  # Will print "Variable:0"
print(matrix_2.name) # Will print "Variable_1:0"
```

Is that sufficient? If not, could you provide some more detail on what you'd like?

Thanks.

**Comment by Yagun** [comment]
@asimshankar, thank you very much for your answer. It is definitely useful.

But, unfortunately, it is not enough. For example, I downloaded a project from GitHub. That project contains Python files and checkpoint files. Their author did not use tf.Variable() at all. But the checkpoint contains 48 variables (all of them are Variable_{number_here}). Is there a way to get a list of the variables and their corresponding Python names?

Thanks.

**Comment by asimshankar** [comment]
@Yagun : That is in general not possible. For example, consider the following Python code:

```python
def f(x):
  v = tf.Variable(1.)
  return v + 1

def g(x):
  v = tf.Variable(2.)
  return v + 1

y = f(g(tf.constant(2.))
```

In this, the Python variable is `v` for two distinct model parameters.

The checkpoint itself is written in a language independent manner, it has no association with Python, it corresponds to a TensorFlow graph, however that graph was created. Furthermore, the association between Python variables and TensorFlow variables is not well defined in general (as in the example above).

Your best bet would be to inspect the Python code you're using and annotate it if needed.

Hope that helps.
