### ISSUE TITLE
tf.cast() can't cast string to number

### ISSUE THREAD

**Issue by Nielsyang** [tensorflow/tensorflow#17069]
OS: Win10 64bit
Tensorflow version: 1.5.0

It looks like tf.cast() can't cast string to number,  but the documents doesn't explain it.
I found this problem when I migrated older versions of tensorflow code to a new version.

When I used tf.cast() to cast string to float, I got error "Unimplemented: Cast string to float is not supported". 
And when I used tf.string_to_number () instead of tf.cast (), the problem was solved.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
