### ISSUE TITLE
Compiling TensorFlow on Windows with NVIDIA 9.1 GPU?

### ISSUE THREAD

**Issue by apiszcz** [tensorflow/tensorflow#17075]
Does anyone have this working, prior to 1.3.0 the nightly builds at tensorflow had GPU builds, these no longer appear to be available.

I have the build running and makes it through all tests until the 'end', There are multiple errors shown below.  After reviewing other posts it appears that the GPU build with Windows is not working? 

cmake .. ^
-A x64 ^
-DCMAKE_BUILD_TYPE=Release ^
-DSWIG_EXECUTABLE=%SWIGEXE% ^
-DPYTHON_EXECUTABLE=%PYEXE% ^
-DPYTHON_LIBRARIES=%PYLIB% ^
-Dtensorflow_ENABLE_GPU=ON ^
-DCUDNN_HOME=%CUDNNH% ^
-Dtensorflow_BUILD_PYTHON_TESTS=OFF ^
-Dtensorflow_BUILD_CC_TESTS=OFF ^
-Dtensorflow_TF_NIGHTLY=OFF ^
-Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX2 ^
-Dtensorflow_CUDA_VERSION=9.1 ^
-Dtensorflow_ENABLE_GPU=ON

msbuild.exe ^
/p:Configuration=Release ^
/maxcpucount ^
/verbosity:minimal ^
/fileLogger ^
/fileloggerparameters:logfile=%TFDIR%\tf_msbuild.log ^
tf_python_build_pip_package.vcxproj

     3>Done building target "FinalizeBuildStatus" in project "pywrap_tensorflow_internal_static.vcxproj".
     3>Target "Build" in file "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.BuildSteps.Targets" from project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal_static.vcxproj" (entry point):
     3>Done building target "Build" in project "pywrap_tensorflow_internal_static.vcxproj".
     3>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal_static.vcxproj" (default targets).
     2>Done executing task "MSBuild" -- FAILED.
     2>Done building target "ResolveProjectReferences" in project "pywrap_tensorflow_internal.vcxproj" -- FAILED.
     2>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (default targets) -- FAILED.
   235>Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\_periodic_resample_op.vcxproj" (235) is building "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (2:2) on node 1 (default targets).
   2:2>Building with tools version "14.0".
       Target "_CheckForInvalidConfigurationAndPlatform" skipped. Previously built successfully.
       Target "Build" skipped. Previously built unsuccessfully.
   2:2>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (default targets) -- FAILED.
   234>Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\_nearest_neighbor_ops.vcxproj" (234) is building "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (2:3) on node 1 (default targets).
   2:3>Building with tools version "14.0".
       Target "_CheckForInvalidConfigurationAndPlatform" skipped. Previously built successfully.
       Target "Build" skipped. Previously built unsuccessfully.
   2:3>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (default targets) -- FAILED.
   233>Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\_lstm_ops.vcxproj" (233) is building "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (2:4) on node 1 (default targets).
   2:4>Building with tools version "14.0".
       Target "_CheckForInvalidConfigurationAndPlatform" skipped. Previously built successfully.
       Target "Build" skipped. Previously built unsuccessfully.
   2:4>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (default targets) -- FAILED.
   232>Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\_gru_ops.vcxproj" (232) is building "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (2:5) on node 1 (default targets).
   2:5>Building with tools version "14.0".
       Target "_CheckForInvalidConfigurationAndPlatform" skipped. Previously built successfully.
       Target "Build" skipped. Previously built unsuccessfully.
   2:5>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (default targets) -- FAILED.
     9>Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\_beam_search_ops.vcxproj" (9) is building "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (2:6) on node 1 (default targets).
   2:6>Building with tools version "14.0".
       Target "_CheckForInvalidConfigurationAndPlatform" skipped. Previously built successfully.
       Target "Build" skipped. Previously built unsuccessfully.
   2:6>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (default targets) -- FAILED.
   235>Done executing task "MSBuild" -- FAILED.
   235>Done building target "ResolveProjectReferences" in project "_periodic_resample_op.vcxproj" -- FAILED.
   235>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\_periodic_resample_op.vcxproj" (default targets) -- FAILED.
   234>Done executing task "MSBuild" -- FAILED.
   234>Done building target "ResolveProjectReferences" in project "_nearest_neighbor_ops.vcxproj" -- FAILED.
   234>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\_nearest_neighbor_ops.vcxproj" (default targets) -- FAILED.
   233>Done executing task "MSBuild" -- FAILED.
   233>Done building target "ResolveProjectReferences" in project "_lstm_ops.vcxproj" -- FAILED.
   233>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\_lstm_ops.vcxproj" (default targets) -- FAILED.
   232>Done executing task "MSBuild" -- FAILED.
   232>Done building target "ResolveProjectReferences" in project "_gru_ops.vcxproj" -- FAILED.
   232>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\_gru_ops.vcxproj" (default targets) -- FAILED.
     9>Done executing task "MSBuild" -- FAILED.
     9>Done building target "ResolveProjectReferences" in project "_beam_search_ops.vcxproj" -- FAILED.
     9>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\_beam_search_ops.vcxproj" (default targets) -- FAILED.
     7>Done executing task "MSBuild" -- FAILED.
     7>Done building target "ResolveProjectReferences" in project "tf_extension_ops.vcxproj" -- FAILED.
     7>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\tf_extension_ops.vcxproj" (default targets) -- FAILED.
     1>Done executing task "MSBuild" -- FAILED.
     1>Done building target "ResolveProjectReferences" in project "tf_python_build_pip_package.vcxproj" -- FAILED.
     1>Done Building Project "C:\g\tensorflow\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default targets) -- FAILED.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by apiszcz** [comment]
:: - MSVC Community 2015
:: - ANACONDA 4.4.4 (Python 3.5.5)
:: - CMake 3.10.2
:: - SWIG 3.0.12
:: - GIT 2.15.1.windows.2
:: - NVIDIA CUDA 9.1, CUDNN 7.05
:: No BAZEL
:: TensorFlow version (latest from GIT repository)

**Comment by wt-huang** [comment]
Closing as this is a duplicate
