### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by dbucci24** [tensorflow/tensorflow#17085]
Hello! I would like to translate the project into Spanish! is it already translated?

**Comment by facaiy** [comment]
Duplicate #17044?

**Comment by dbucci24** [comment]
@facaiy no, i dont know it

**Comment by dbucci24** [comment]
I really want to contribute here with the translation, I have experience in the field of translations

**Comment by facaiy** [comment]
Yes, the idea sounds great, at least for me. However, we don't hear any plan for multiple language support. Please be patient and wait for reply from official tensorflower.

**Comment by dbucci24** [comment]
Ok great! I'll wait for the answer!: :)

**Comment by bignamehyp** [comment]
We're seeing more and more people eager to contribute to translations (for example #16871).

But we don't have infrastructure to support this. We're looking into it.

**Comment by SoYoungCho** [comment]
I also wish this project's translated document in Korean. 
I hope multiple language be supported one day :)
Thanks for the issue by the way. I was also curious about this issue.
