### ISSUE TITLE
The method tf.graph_util.remove_training_nodes() is broken

### ISSUE THREAD

**Issue by VisuMap** [tensorflow/tensorflow#17080]
On Windows 7 + tensorflow 1.4 the following code:

tf.graph_util.remove_training_nodes(tf.get_default_graph())

throws out the following error message:

......
  File "C:\Program Files\Python3\lib\site-packages\tensorflow\python\framework\graph_util_impl.py", line 278, in remove_training_nodes
    input_nodes = input_graph.node
AttributeError: 'Graph' object has no attribute 'node'
.....

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by VisuMap** [comment]
Here are more details about test:

Have I written custom code: Yes
OS Platform and Distribution: Windows 7, 64bit AMD CPU, GTX1070 Graphics card
TensorFlow installed from: tensorflow_gpu-1.4.0-cp35-cp35m-win_amd64.whl
TensorFlow version: 1.4
Bazel version: N/A
CUDA/cuDNN version: 
GPU model and memory: 8 GB
Exact command to reproduce:  Custom code, but should be re-produceable with code in initial post, as it is static compilation error.

**Comment by VisuMap** [comment]
Problem solved: the method remove_training_nodes() expected a GraphDef object. So, the following code works:
tf.graph_util.remove_training_nodes(tf.get_default_graph().as_graph_def())
