### ISSUE TITLE
TF Lite example segmentation fault

### ISSUE THREAD

**Issue by mgkbeer** [tensorflow/tensorflow#17087]
### System information

OS Platform and Distribution - Ubuntu 16.04.2 LTS
TensorFlow installed from: https://github.com/tensorflow/tensorflow.git
TensorFlow version: last commit f66e9f92820804b7c2b4698147d07d5d2277c62f 
Bazel version: Build label: 0.8.1- (@non-git)
CUDA/cuDNN version N/A
GPU model and memory N/A
Exact command to reproduce: bazel build --verbose_failures --config opt --cxxopt=-std=c++11 --config monolithic //tensorflow/contrib/lite/examples/label_image:label_image 
./label_image

== compiler =====================================================
c++ (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
== uname -a =====================================================
Linux qds101 4.4.65 https://github.com/tensorflow/tensorflow/issues/1 SMP PREEMPT Mon Sep 18 13:34:00 CDT 2017 aarch64 aarch64 aarch64 GNU/Linux
== check pips ===================================================
numpy (1.13.3)
protobuf (3.4.0)
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.5)
== check for virtualenv =========================================
False
== tensorflow import ============================================
tf.VERSION = 1.3.0
tf.GIT_VERSION = v1.3.0-rc1-1607-gbe4e5ef
tf.COMPILER_VERSION = v1.3.0-rc1-1607-gbe4e5ef

### Describe the problem
I compile example/label_image nad when I run it I get segmentation fault.
Error comes from the following line in resize_bilinear.c (called from label_image.c resize<float>(interpreter->typed_tensor<float>(input), in, image_height,
                    image_width, image_channels, wanted_height, wanted_width,
                    wanted_channels, s);)
 

type::ResizeBilinear(GetTensorData<float>(input), GetTensorDims(input),   \
                       GetTensorData<int32>(size), GetTensorDims(size),     \
                       GetTensorData<float>(output), GetTensorDims(output), \
                       params->align_corners)

because params is NULL
I looked at code and i do not believe that this variable (builtin_data) ever initialized in this case because resize is called not within graph

### Source code / logs
user@qds101:~/ml/tf_lite/tensorflow/tensorflow/contrib/lite/examples/label_image/exec$ ./label_image -v 1
nnapi error: unable to open library libneuralnetworks.so
Loaded model ./vgg16_conv1_opt.tflite
resolved reporter
tensors size: 6
nodes size: 1
inputs: 1
input(0) name: Placeholder
0: Placeholder, 602112, 1, 0, 0
1: conv1_1, 12845056, 1, 0, 0
2: conv1_1/Conv2D_bias, 256, 1, 0, 0
3: conv1_1/weights, 6912, 1, 0, 0
len: 150666
width, height, channels: 224, 224, 3
input: 0
number of inputs: 1
number of outputs: 1
Interpreter has 6 tensors and 1 nodes
Inputs: 0
Outputs: 1

Tensor   0 kTfLiteFloat32  kTfLiteArenaRw     602112 bytes ( 0.6 MB)  1 224 224 3

Tensor   1 kTfLiteFloat32  kTfLiteArenaRw   12845056 bytes (12.2 MB)  1 224 224 64

Tensor   2 kTfLiteFloat32   kTfLiteMmapRo        256 bytes ( 0.0 MB)  64

Tensor   3 kTfLiteFloat32   kTfLiteMmapRo       6912 bytes ( 0.0 MB)  64 3 3 3

Tensor   4 kTfLiteFloat32  kTfLiteArenaRw    5419008 bytes ( 5.2 MB)  1 224 224 27

Tensor   5 kTfLiteFloat32  kTfLiteDynamic       6912 bytes ( 0.0 MB)  27 64

Node   0 Operator Builtin Code   3
  Inputs: 0 3 2
  Outputs: 1
params = (nil) //my print
Segmentation fault

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code

**Comment by freedomtan** [comment]
This should be fixed by https://github.com/tensorflow/tensorflow/commit/1a0b637df8d082301118dd0f85ec63704f862aeb

**Comment by jart** [comment]
In that case closing. Thank you for report.
