### ISSUE TITLE
enqueue inside while loop does not work as expected

### ISSUE THREAD

**Issue by gaohuazuo** [tensorflow/tensorflow#17093]
VERSION 1.5.0-rc0
GIT_VERSION v1.3.0-rc1-7323-g8d5741f
Compiled from source

```python
with tf.device('cpu:0'):
    x = tf.contrib.framework.local_variable(1024)
    q = tf.FIFOQueue(-1, tf.int32, shapes=[[]])

    def cond(_):
        remaining = tf.assign_sub(x, 1, use_locking=True)
        with tf.control_dependencies([q.enqueue(remaining)]):
            return remaining > 0

    def body(_):
        return _

    op = tf.while_loop(cond, body, [tf.constant([])], parallel_iterations=1, back_prop=False).op

x.initializer.run()
op.run()
q.dequeue_many(q.size()).eval()
# array([0, 0, 0, ..., 0, 0, 0], dtype=int32)
# expected: array([1023, 1022, 1021, ..., 2, 1, 0], dtype=int32)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gaohuazuo** [comment]
Have I written custom code: Yes
OS Platform and Distribution: Ubuntu 16.04
TensorFlow installed from: Source
TensorFlow version: 1.5.0
Bazel version: N/A
CUDA/cuDNN version: 8.0/6.0
GPU model and memory: 1080Ti
Exact command to reproduce: N/A

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by gaohuazuo** [comment]
I think this is a bug.

**Comment by nithya4** [comment]
@gaohuazuo Sorry for spamming this closed issue. Did you find a solution? I am facing similar issues using queue enqueue within a while loop.
