### ISSUE TITLE
Build Android on Windows failed

### ISSUE THREAD

**Issue by zeshaoaaa** [tensorflow/tensorflow#17091]
------------------------

### System information
- **Have I written custom code**: N/A
- **OS Platform**: Windows10
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.5
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: 6.3
- **CUDA/cuDNN version**: CUDA v9.1
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
I saw your instruction on [https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android](url) , but I want to replace the model in the demo to my retrained model. Is there anyone know how to do that? If my description is not clear enough, please tell me. Thanks in advance.

### Source code / logs
Error:Execution failed for task ':buildNativeMake'.
> A problem occurred starting process 'command 'tensorflow/contrib/makefile/build_all_android.sh''

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
OS Platform and Distribution

**Comment by zeshaoaaa** [comment]
@tensorflowbutler Thank your reply. I'm a little bit confused about N/A, is it mean not application? But actually, I do not install them. Is that still leave them as N/A? I saw other issues about building TensorFlow Android on Windows, but it seems nobody solved it, so I am wondering if anybody finds a new solution to this problem.

**Comment by andrewharp** [comment]
@zeshaoaaa We currently don't support building the TensorFlow library on Windows. 

However, we do provide a precompiled AAR download that should work in your case if you set the build type in build.gradel to `none`. This will remove the need to build native .so libraries locally.
