### ISSUE TITLE
Feature request: complex support in initializers

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#17097]
AFAIK no initializers work with tf.complex64 and tf.complex128 (is there a mathematical reason for this?).

My current workaround is to call them twice (once for the real part and once for the imaginary), as
```py
def complex_initializer(base_initializer):
    f = base_initializer()

    def initializer(*args, dtype=tf.complex64, **kwargs):
        real = f(*args, **kwargs)
        imag = f(*args, **kwargs)
        return tf.complex(real, imag)

    return initializer


tf.get_variable(
        name='my_complex_variable',
        shape=[1],
        dtype=tf.complex64,
        initializer=complex_initializer(tf.random_normal_initializer))
```
which seems to work fine so I'm wondering why this isn't built-in already?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by carlthome** [comment]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: any
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.6.0-rc1
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9/7.5
- **GPU model and memory**: Titan X
- **Exact command to reproduce**: `tf.get_variable('x', [1], tf.complex64, tf.random_normal_initializer)`

**Comment by bignamehyp** [comment]
What do you think about a complex number initializer? @mrry

**Comment by carlthome** [comment]
Having read up more, complex weight initialization is actually more subtle than I hoped, and somewhat uncharted territory, so if it were to be merged into TensorFlow it probably fits better into contrib somewhere at the moment.

Just doing the real and imaginary part separately like I proposed above might be too naive because in terms of polar coordinates we probably only want normal distributed magnitudes while the argument should be invariant for full rotations. [Here's the Keras implementation of Deep Complex Networks](https://github.com/ChihebTrabelsi/deep_complex_networks/blob/master/complexnn/init.py#L130-L191) that should correspond to `tf.orthogonal_initializer` with complex dtypes, for example.

**Comment by carlthome** [comment]
Ping @ChihebTrabelsi for input. 😃

**Comment by beniroquai** [comment]
May I ask you if there has been made any progress? I found out a weird behavior for initializing complex-valued tensors:

```
import numpy as np
import tensorflow as tf
import time as time

mysize = 256
mymat = np.ones((mysize,mysize,mysize))
mymat_cmplx = mymat+1j*mymat

# convertinig complex numpy to tensor
t1 = time.time()
TF_mymat_cmplx = tf.constant(mymat_cmplx)
t2 = time.time()
print('Time is: '+str(t2-t1))

# convertinig complex numpy to tensor
t1 = time.time()
TF_mymat_cmplx = tf.complex(np.real(mymat_cmplx), np.imag(mymat_cmplx))
t2 = time.time()
print('Time is: '+str(t2-t1))
```
which gives:
```
Time is: 20.639596700668335
Time is: 3.303292989730835
```
Both parts should do the same, but the latter one is approx. 6x faster. Any ideas? 
It was measured on Mac/Ubuntu/Windows with TF 1.13 GPU and CPU. 

Kind regards!

**Comment by LukeWood** [comment]
Are there any plans to implement this?
