### ISSUE TITLE
Tensorflow 1.5 issue on ipython notebook

### ISSUE THREAD

**Issue by arsalan993** [tensorflow/tensorflow#17103]
I recently upgrade tensorflow using the command " py -3.6 -m pip install --upgrade tensorflow " 

and after that why i run python on command prompt windows 10 tensorflow works like charm
but when i open ipython notebook for python3 and try to import tensorflow i get this error

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-64156d691fe5> in <module>()
----> 1 import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>()
     39 # pylint: disable=undefined-variable
     40 del python
---> 41 del core
     42 # pylint: enable=undefined-variable

NameError: name 'core' is not defined

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
