### ISSUE TITLE
Feature Request: Adamax optimizer

### ISSUE THREAD

**Issue by dchatterjee172** [tensorflow/tensorflow#17104]
It will be really nice to have a adamax implementation along with the regular adam optimization algorithm. Adamax superior than adam in certain cases, generally in models with word embedding.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dchatterjee172** [comment]
Hello As this is just a feature request i don't think those fields are necessary.

**Comment by asimshankar** [comment]
Sounds reasonable, though I don't think anyone on the TensorFlow team will be actively pursuing this right now, but contributions are welcome.

**Comment by kdhingra307** [comment]
Hey, 

I would like to work on this implementation

**Comment by facaiy** [comment]
@asimshankar Would you prefer to implement the optimizer in python side or c++ side?

**Comment by facaiy** [comment]
@kdhingra307 Hi, do you have start writing code? I'm watching the issue since it's opened, and a prototype is nearly complete (CPU test passed):  https://github.com/facaiy/tensorflow/tree/ENH/adamax_optimizer 
If you agree, I'd like to open a PR for future discussion. Thank you.

**Comment by kdhingra307** [comment]
@facaiy please go on, I will look into another issue

though can u help me with entry point

**Comment by facaiy** [comment]
@dchatterjee172 Not yet. I'll finish it in the weekend.

**Comment by dchatterjee172** [comment]
Thanks for your contribution. Sparse update is required in this case
because adamax is mainly used with word embeddings. Can you post a comment
here after implementing sparse update?

**Comment by dchatterjee172** [comment]
@facaiy 
Can you explain this operation?
https://github.com/facaiy/tensorflow/blob/006871750bb76dda4dfa65e0c707ca12e759d6f8/tensorflow/contrib/opt/python/training/adamax.py#L124
lr = (lr_t * math_ops.sqrt(1 - beta2_power) / (1 - beta1_power))
Is this required in adamax?

**Comment by facaiy** [comment]
Hi, I added a very rudimentary implementation of AdaMaxOptimizer in PR  #17395. It is pretty rough. Please take a look and comment.

@dchatterjee172 Thanks for feedback. Many codes are copied from AdmaOptimizer, and I forget to delete the line. I have added the corresponding tests, and welcome to review.
