### ISSUE TITLE
error import tensorflow

### ISSUE THREAD

**Issue by cheng6076** [tensorflow/tensorflow#1711]
I have installed the tensorflow and set the environment variables. However I got the following error when importing tensor flow:

ImportError: /myproject/lib/python2.7/sitepackages/tensorflow/python/_pywrap_tensorflow.so: invalid ELF header

Can anyone help me? Thanks

**Comment by cheng6076** [comment]
solved

**Comment by lingz** [comment]
@cheng6076 Could you share the solution.

**Comment by cheng6076** [comment]
I think I have installed the wrong version

2016-04-09 11:00 GMT+01:00 Lingliang Zhang <notifications@github.com>:

**Comment by saifrahmed** [comment]
I had the same problem when I mistakenly installed the OSX version on Linux.  When doing a pip install especially, ensure the $TF_BINARY_URL references the correct OS, Python Version, CPU/GPU architecture

https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#using-pip

**Comment by Srikanth-Kb** [comment]
> Can you run `uname -a` in your terminal and report what gets printed?

Linux raspberry 4.9.0-11-686 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) i686 GNU/Linux

I am facing this issue. I couldn't find the solution on how to choose the right .whl file for installation.

**Comment by AlexisLapeze** [comment]
same error here withh nvidia jetson. How can i fix it ?
