### ISSUE TITLE
Feature Request: Make beam_search_decoder use multiple CPU threads.

### ISSUE THREAD

**Issue by haotianteng** [tensorflow/tensorflow#17136]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:N.A.
- **GCC/Compiler version (if compiling from source)**:4.9.4
- **CUDA/cuDNN version**: 8.0/6.0
- **GPU model and memory**: GTX 1080Ti
- **Exact command to reproduce**: N.A.

### Describe the problem
Add multiple threads support for tf.nn.ctc_beam_search_decoder, for now the tf.nn.ctc_beam_search_decoder is using CPU and only run on 1 thread(although multiple threads has been provided), make it use several CPU threads to run would be very useful as the decoding process of the beam_search_decoder is now the bottleneck of the inference.
### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
I use the nvidia-smi and htop to observe the CPU and GPU usage when running a test CTC decoding process, only 1 CPU thread is used and 0 GPU-Utilitiy has been observed during decoding.

**Comment by asimshankar** [comment]
I don't believe we have anyone actively working on this, however, contributions are welcome. 
The change would likely involve updating the C++ implementation of the operation in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/ctc_decoder_ops.cc#L178 to utilize multiple threads.

**Comment by tamimaddari82** [comment]
@asimshankar , I would like to work on this issue. One thing I can see is that neither the ctc_decoder_ops.cc, nor ctc_ops.py have a test files associated with it. Would like me to write test files first for the ops?

**Comment by tamimaddari82** [comment]
@asimshankar Can you give me an example of an op which already use CPU multithreading so that I can follow the pattern? Thanks :)

**Comment by tamimaddari82** [comment]
@asimshankar ,Can you please check the PR and give feedback? If everything is okay, I will move to parallelize beam search and a GPU implementation of CTC. Thank you very much.

**Comment by kindernerd** [comment]
> @asimshankar ,Can you please check the PR and give feedback? If everything is okay, I will move to parallelize beam search and a GPU implementation of CTC. Thank you very much.

Thx! By the way, is there a parallel CTC beam search decoder?

**Comment by tilakrayal** [comment]
@haotianteng,
Respective PR's were merged and closed. Could you please take a look and let us know if the issue still persists. Thank you!
