### ISSUE TITLE
Windows installation page lists wrong cudnn version

### ISSUE THREAD

**Issue by mackiem** [tensorflow/tensorflow#17138]
The windows installation pages specifically asks to use cuDNN 6 - [link](https://www.tensorflow.org/install/install_windows). Then, when running tensorflow it looks specifically for cuDNN7.

    % (build_info.cudnn_dll_name, build_info.cudnn_version_number))
ImportError: Could not find 'cudnn64_7.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 7 from this URL: https://developer.nvidia.com/cudnn

Would be great if the page modified this to specifically ask for cuDNN 7.

**Comment by asimshankar** [comment]
Thanks for the note.

@gunan @av8ramit - does the Windows page need to be updated?

**Comment by gunan** [comment]
FYI @markdaoust
I thought we updated the website with the correct information, could you confirm?

**Comment by MarkDaoust** [comment]
Thanks for the reminder!

This is fixed now: https://www.tensorflow.org/install/install_windows
