### ISSUE TITLE
Wrong Bazel version check when building from source

### ISSUE THREAD

**Issue by christian-rauch** [tensorflow/tensorflow#17137]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.5
- **Python version**: Python 2.7.6
- **Bazel version (if compiling from source)**: 0.10.1
- **GCC/Compiler version (if compiling from source)**: 4.8.5
- **CUDA/cuDNN version**: 8.0 / 7.0
- **GPU model and memory**: GeForce GTX 970, 4GB VRAM
- **Exact command to reproduce**: `bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

### Describe the problem
I am trying to build TensorFLow 1.5 with Bazel 0.10.1 from the Google apt repo ([`http://storage.googleapis.com/bazel-apt`](http://storage.googleapis.com/bazel-apt)).
The build immediately fails with a misleading error message:
`Current Bazel version is 0.10.1, expected at least 0.5.4`
because the build script is comparing strings instead of integers of the version numbers.

Backtrace:
```
$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
ERROR: /home/christian/Development/tensorflow/WORKSPACE:15:1: Traceback (most recent call last):
	File "/home/christian/Development/tensorflow/WORKSPACE", line 15
		closure_repositories()
	File "/home/christian/.cache/bazel/_bazel_christian/d6e111ab803bbbeb04cac5fc3b321976/external/io_bazel_rules_closure/closure/repositories.bzl", line 69, in closure_repositories
		_check_bazel_version("Closure Rules", "0.4.5")
	File "/home/christian/.cache/bazel/_bazel_christian/d6e111ab803bbbeb04cac5fc3b321976/external/io_bazel_rules_closure/closure/repositories.bzl", line 172, in _check_bazel_version
		fail(("%s requires Bazel >=%s but was...)))
Closure Rules requires Bazel >=0.4.5 but was 0.10.1
ERROR: Error evaluating WORKSPACE file
ERROR: /home/christian/Development/tensorflow/WORKSPACE:41:1: Traceback (most recent call last):
	File "/home/christian/Development/tensorflow/WORKSPACE", line 41
		tf_workspace()
	File "/home/christian/Development/tensorflow/tensorflow/workspace.bzl", line 48, in tf_workspace
		check_version("0.5.4")
	File "/home/christian/Development/tensorflow/tensorflow/workspace.bzl", line 38, in check_version
		fail("\nCurrent Bazel version is {}, ...))

Current Bazel version is 0.10.1, expected at least 0.5.4
ERROR: Error evaluating WORKSPACE file

```

**Comment by facaiy** [comment]
Yes, version check uses alphabetical order wrongly before 1.6, and I believe the bug has been fixed in the master branch.

**Comment by flanaras** [comment]
Had the same problem, this fixed it. Thanks!

**Comment by christian-rauch** [comment]
Can this fix be backported to 1.5 so that people can build a stable version from source?

**Comment by facaiy** [comment]
@christian-rauch I rechecked the r1.5 branch, and found that 6fcfab77 patch, fortunately, has been merged since 13 days ago, see:

https://github.com/tensorflow/tensorflow/blob/5b10b3474bea72e29875264bb34be476e187039c/tensorflow/workspace.bzl#L45

So, could you pull the latest codes on r1.5 branch, and take a test again? Thank you.

**Comment by christian-rauch** [comment]
The `r1.5` branch works. I previously checked out the `v1.5.0` tag, in the assumptions that both point to the same commit.

**Comment by facaiy** [comment]
Good news! Could you close the issue since it has been fixed ?

**Comment by christian-rauch** [comment]
Yes. But maybe the current `r1.5` branch could be tagged, such that the next person that tries to build `v1.5.0` doesn't need to dig into the same issue.
