### ISSUE TITLE
error tf1.5 : tf.contrib.ffmpeg.decode_video

### ISSUE THREAD

**Issue by XuChunling** [tensorflow/tensorflow#17143]
I use tensorflow 1.5 on ubuntu and decodevideo.

`with tf.Session() as sess:
summary_writer = tf.summary.FileWriter('/home/xucl/app/tensorboard_log/keras_training')
movie_bin = tf.read_file('/home/xucl/app/data/bilibili/video/DongFangLieChe.mp4')
movie = tf.contrib.ffmpeg.decode_video(movie_bin)
movie_ev = movie.eval()`

the link of ffmpeg tensorflow
[https://github.com/tensorflow/tensorflow/tree/r1.5/tensorflow/contrib/ffmpeg](url)

but get an error

`F tensorflow/contrib/ffmpeg/default/ffmpeg_lib.cc:401] Non-OK-status: ReadInfoFile(stderr_filename, width, height, frames) status: Unknown: Not enough video info returned by FFmpeg [0, 0, 0, 3]Could not read FFmpeg stderr file: /tmp/tmp_file_tensorflow_3_Bi0OjG.err 已放弃 (核心已转储)`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by XuChunling** [comment]
more information about ffmpeg:

$ ffmpeg
ffmpeg version 2.4.3-1ubuntu1~trusty6 Copyright (c) 2000-2014 the FFmpeg developers
  built on Nov 22 2014 17:07:19 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
  configuration: --prefix=/usr --extra-version='1ubuntu1~trusty6' --build-suffix=-ffmpeg --toolchain=hardened --extra-cflags= --extra-cxxflags= --libdir=/usr/lib/x86_64-linux-gnu --shlibdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --enable-shared --disable-stripping --enable-avresample --enable-avisynth --enable-fontconfig --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-opengl --enable-x11grab --enable-libxvid --enable-libx265 --enable-libdc1394 --enable-libiec61883 --enable-libzvbi --enable-libzmq --enable-frei0r --enable-libx264 --enable-libsoxr --enable-openal --enable-libopencv
  libavutil      54.  7.100 / 54.  7.100
  libavcodec     56.  1.100 / 56.  1.100
  libavformat    56.  4.101 / 56.  4.101
  libavdevice    56.  0.100 / 56.  0.100
  libavfilter     5.  1.100 /  5.  1.100
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  0.100 /  3.  0.100
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  0.100 / 53.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**Comment by XuChunling** [comment]
I have get answer at issue pull request #13242
https://github.com/tensorflow/tensorflow/pull/13242

so, I will try ffmpeg.decode_video when tensorflow1.6 release.

**Comment by YongyiTang92** [comment]
> I have get answer at issue pull request #13242
> it is a bug in tf1.5, and the code was modified after tf1.5 release.
> so, I will try ffmpeg.decode_video when tensorflow1.6 release.

Any updates? I still run into this error with tf.1.12.0
