### ISSUE TITLE
tensorflow/contrib/lite/examples/label_image

### ISSUE THREAD

**Issue by ashishkej** [tensorflow/tensorflow#17146]
Build it for desktop machines (tested on Ubuntu and OS X)

bazel build --config opt --cxxopt=-std=c++11 //tensorflow/contrib/lite/examples/label_image:label_image

I am not able to build the this example on my Ubuntu 16.04 Intel Desktop using the command above.
Using TF 1.5 and the error is related to NEON. Can I run .tflite models on Desktop?

ERROR: /home/ashish/tensorflow_1.5/tensorflow/contrib/lite/examples/label_image/BUILD:15:1: Linking of rule '//tensorflow/contrib/lite/examples/label_image:label_image' failed (Exit 1)
bazel-out/k8-opt/bin/tensorflow/contrib/lite/kernels/internal/_objs/tensor_utils/tensorflow/contrib/lite/kernels/internal/tensor_utils.o:tensor_utils.cc:function tflite::tensor_utils::MatrixBatchVectorMultiplyAccumulate(float const*, int, int, float const*, int, float*, int): error: undefined reference to 'tflite::tensor_utils::NeonMatrixBatchVectorMultiplyAccumulate(float const*, int, int, float const*, int, float*, int)'
bazel-out/k8-opt/bin/tensorflow/contrib/lite/kernels/internal/_objs/tensor_utils/tensorflow/contrib/lite/kernels/internal/tensor_utils.o:tensor_utils.cc:function tflite::tensor_utils::VectorVectorCwiseProduct(float const*, float const*, int, float*): error: undefined reference to 'tflite::tensor_utils::NeonVectorVectorCwiseProduct(float const*, float const*, int, float*)'
bazel-out/k8-opt/bin/tensorflow/contrib/lite/kernels/internal/_objs/tensor_utils/tensorflow/contrib/lite/kernels/internal/tensor_utils.o:tensor_utils.cc:function tflite::tensor_utils::VectorVectorCwiseProductAccumulate(float const*, float const*, int, float*): error: undefined reference to 'tflite::tensor_utils::NeonVectorVectorCwiseProductAccumulate(float const*, float const*, int, float*)'
bazel-out/k8-opt/bin/tensorflow/contrib/lite/kernels/internal/_objs/tensor_utils/tensorflow/contrib/lite/kernels/internal/tensor_utils.o:tensor_utils.cc:function tflite::tensor_utils::VectorBatchVectorCwiseProductAccumulate(float const*, int, float const*, int, float*): error: undefined reference to 'tflite::tensor_utils::NeonVectorBatchVectorCwiseProductAccumulate(float const*, int, float const*, int, float*)'
bazel-out/k8-opt/bin/tensorflow/contrib/lite/kernels/internal/_objs/tensor_utils/tensorflow/contrib/lite/kernels/internal/tensor_utils.o:tensor_utils.cc:function tflite::tensor_utils::BatchVectorBatchVectorDotProduct(float const*, float const*, int, int, float*, int): error: undefined reference to 'tflite::tensor_utils::NeonBatchVectorBatchVectorDotProduct(float const*, float const*, int, int, float*, int)'
bazel-out/k8-opt/bin/tensorflow/contrib/lite/kernels/internal/_objs/tensor_utils/tensorflow/contrib/lite/kernels/internal/tensor_utils.o:tensor_utils.cc:function tflite::tensor_utils::Sub1Vector(float const*, int, float*): error: undefined reference to 'tflite::tensor_utils::NeonSub1Vector(float const*, int, float*)'
bazel-out/k8-opt/bin/tensorflow/contrib/lite/kernels/internal/_objs/tensor_utils/tensorflow/contrib/lite/kernels/internal/tensor_utils.o:tensor_utils.cc:function tflite::tensor_utils::ClipVector(float const*, int, float, float*): error: undefined reference to 'tflite::tensor_utils::NeonClipVector(float const*, int, float, float*)'
bazel-out/k8-opt/bin/tensorflow/contrib/lite/kernels/internal/_objs/tensor_utils/tensorflow/contrib/lite/kernels/internal/tensor_utils.o:tensor_utils.cc:function tflite::tensor_utils::VectorShiftLeft(float*, int, float): error: undefined reference to 'tflite::tensor_utils::NeonVectorShiftLeft(float*, int, float)'
bazel-out/k8-opt/bin/tensorflow/contrib/lite/kernels/internal/_objs/tensor_utils/tensorflow/contrib/lite/kernels/internal/tensor_utils.o:tensor_utils.cc:function tflite::tensor_utils::ReductionSumVector(float const*, float*, int, int): error: undefined reference to 'tflite::tensor_utils::NeonReductionSumVector(float const*, float*, int, int)'
collect2: error: ld returned 1 exit status
Target //tensorflow/contrib/lite/examples/label_image:label_image failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 194.676s, Critical Path: 14.43s
FAILED: Build did NOT complete successfully

**Comment by andrehentz** [comment]
My guess is that your platform does support NEON but is falling in the default category: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/kernels/internal/BUILD#L363

To test that hypothesis, could you force it to use ":neon_tensor_utils" there?

**Comment by ashishkej** [comment]
Thanks.... I am able to build with that trick.

**Comment by tataganesh95** [comment]
Is it possible to add this fix as a gist or something? Might be helpful for a lot of people.

**Comment by harshgrovr** [comment]
> Thanks.... I am able to build with that trick.

Hey How did we solve this issue?
