### ISSUE TITLE
Bazel doesn't use the optimization flag specified in configuration

### ISSUE THREAD

**Issue by eann** [tensorflow/tensorflow#17154]
Hi

I was compiling TensorFlow on a PowerPC machine and it kept failing with the error "unrecognized command line option -march=native" when compiling the file pcre_byte_order.c. This happened even though I specified the default flag -mcpu=native when running ./configure. I also used the --cxxopt=-mcpu=native flag to no avail, and the only way to solve the problem was to remove the --config=opt flag when invoking bazel.

**Comment by gunan** [comment]
@case540  is already working on the configuration scripts at the moment.
Could you look into this?

**Comment by case540** [comment]
hmm, could you give more specs about your machine. Specifically, what

python -c "import platform; print platform.machine()"

outputs. If the above outputs 'ppc64le', then --config=opt won't add -march=native flag and will instead add -mcpu=native.

**Comment by eann** [comment]
Tomorrow I'll run the command and post the output, but the architecture
should be ppc64le (I remember seeing it in the name of the whl file). The
configure script did specify -mcpu=native as the optimization flag for
--config=opt, but -march=native still popped up when compiling one of the
files (and consequently build failed). The problem disappeared when I built
without --config=opt.

Il mer 21 feb 2018, 00:10 Michael Case <notifications@github.com> ha
scritto:

**Comment by gunan** [comment]
We merged a potential fix. Could you test it out when you get the chance?

**Comment by eann** [comment]
I tried to compile from master and everything went smooth (just a few warnings)

**Comment by gunan** [comment]
@eann Thank you very much for verifying!
