### ISSUE TITLE
Catch / recover from CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by hko-gh** [tensorflow/tensorflow#17164]
Hi all,

* Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win7
* TensorFlow installed from (source or binary): source
* TensorFlow version (use command below): 1.3
* GCC/Compiler version (if compiling from source): VC14_64
* CUDA/cuDNN version: 8 / 6
* GPU model and memory: Quadro K2000M
* Bazel version (if compiling from source): N/A
* Exact command to reproduce: N/A

I am using the C++ API to load and execute trained models.
I sometimes experience a problem regarding the ensemble of CuDNN and tensorflow:
When I invoke Session::Run and the input tensor I am providing is too small for the network (which is fully convolutional and thus has no fixed input extents given), CuDNN crashes with CUDNN_STATUS_BAD_PARAM.
Is there any way to catch this as an exception or somehow recover from that failure? Or is there a way to determine whether the given tensor extent will lead to such an error before I actually throw it at the network?

Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Exact command to reproduce

**Comment by hko-gh** [comment]
@tensorflowbutler Thanks, I've updated the issue description

**Comment by hko-gh** [comment]
Any thoughts on this? Is more information required?
I think this is a valid issue as crashing is probably not the desired behavior

**Comment by reedwm** [comment]
@hko-gh can you provide a C++ code sample to reproduce the problem?

**Comment by hko-gh** [comment]
When I tried to arrange a minimal code sample, it surprisingly worked. I guess there was some issue with the self-compiled TF version we were using. Now I am getting an error message and status.ok() == false, which is the expected behavior. Thank you very much for asking for code :)

**Comment by reedwm** [comment]
Thank you for the update. I'll close the issue for now. Please reopen if you re-encounter the issue and are able to reproduce with a C++ code sample.
