### ISSUE TITLE
cifar 10 can not be downloaded

### ISSUE THREAD

**Issue by anbai106** [tensorflow/tensorflow#17165]
Hi, 

I am trying to follow the tutorial from the source code of tensor flow: /model/tutorials/cifar10/

In the cifar10.py, the link 

> DATA_URL = 'https://www.cs.toronto.edu/~kriz/cifar-10-binary.tar.gz'

does not work, I guess it is the problem from Canada.

Do you have a solution for this???

Thanks

**Comment by bignamehyp** [comment]
Can you please check the link again? It works for me.

**Comment by faizanahemad** [comment]
+1 not working for the last 12 hours. It seems that they have big outages
