### ISSUE TITLE
Feature request: Provide API to test whether a copy of TensorFlow has MKL support

### ISSUE THREAD

**Issue by frreiss** [tensorflow/tensorflow#17176]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: v1.5.0-9-gc959ec7
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: 0.10.0
- **GCC/Compiler version (if compiling from source)**: c++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: n/a

### Describe the problem
I have built a copy of TensorFlow with MKL-DNN support. The MKL convolution operators work much better with the "channels_first" (NCHW) data format. On non-MKL, non-GPU builds, the "channels_first" data format does not work for me, because a CPU version of average pooling is not implemented for that data format.

I would like to have my scripts test whether the current copy of TensorFlow has either MKL or GPU support, and if so, to use the "channels_first" data format. I can easily test for GPU support with `tf.test.is_built_with_cuda()`. However, there does not seem to be a corresponding API to test for MKL-DNN support. Would it be possible to add one?

**Comment by asimshankar** [comment]
CCing @tfboyd for comment.

**Comment by tatianashp** [comment]
I am adding the ability to test if the program has been built with MKL in the internal repo. It should propagate in a day or two.

**Comment by frreiss** [comment]
Yes, that works nicely, thanks!

**Comment by tatianashp** [comment]
You are welcome.
