### ISSUE TITLE
Question about freeze the graph

### ISSUE THREAD

**Issue by liuhantao9** [tensorflow/tensorflow#17179]
I found a model which has the checkpoint file inside .pd

```
## Saving the lastest checkpoint to protobuf file
flow --model cfg/yolo-new.cfg --load -1 --savepb
```
[https://github.com/thtrieu/darkflow](url)

So do I still have to freeze the graph?

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
