### ISSUE TITLE
Feature Request: Make sequence_length argument each of CTC function Optional

### ISSUE THREAD

**Issue by selcouthlyBlue** [tensorflow/tensorflow#17183]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 8.1
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
1.4
- **Python version**: 
3.6
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
N/A

### Describe the problem
Since the `sequence_length` parameter of CTC functions are each dependent on the input (specifically the number of time steps), why not let them determine the sequence lengths themselves? Or have a separate function that determines the sequence lengths.

### Source code / logs
I was thinking of adding something like this to ctc_loss (assuming inputs are batch major and of shape [None, num_time_steps, num_classes]):

```
batch_size = input.shape[0]
sequence_length = input.shape[1]
sequence_lengths = tf.fill([batch_size], sequence_length)  
```

Unfortunately, this throws an error.

`TypeError: Expected int32 passed to parameter 'dims' of op 'Fill', got [Dimension(None)] of type 'list' instead.`

**Comment by selcouthlyBlue** [comment]
Update: I figured out a way to do this. However, this assumes that the sequence_lengths of each example are all the same. 

Given an input tensor of shape `(None, num_time_steps, num_features)`:

```
sequence_length_dims = tf.stack([tf.shape(input)[0]])
sequence_lengths = tf.fill(sequence_length_dims, input.shape[1]) # to be passed to ctc
```

**Comment by bignamehyp** [comment]
@ebrevdo can you please take a look?

**Comment by ebrevdo** [comment]
Not sure I understand how to make it optional.  You can certainly identify, for each minibatch entry, the first location that contains some "padding" value, and make that index the sequence length.  However, this shouldn't be the job of e.g. ctc_loss: you can call this function, get the sequence lengths vector, and pass them to ctc_loss.  If ctc_loss did this for you, it'd now have an *additional* argument, the "padding value", and would have to check that you passed in *either* the sequence_lengths *or* the padding_value; and the API of ctc_loss would be more complicated.

**Comment by selcouthlyBlue** [comment]
I was thinking of creating something like this that assumes all sequence lengths are the same:

```
def static_ctc_loss(labels, inputs, preprocess_collapse_repeated=True,
             ctc_merge_repeated=True, time_major=True):
    sequence_length = None
    if time_major:
        sequence_length = tf.fill(tf.shape(inputs)[0:1], tf.shape(inputs)[1])
    else:
        sequence_length = tf.fill(tf.shape(inputs)[1:2], tf.shape(inputs)[0])
    return tf.nn.ctc_loss(sparse_labels, inputs, sequence_length,
                          preprocess_collapse_repeated=preprocess_collapse_repeated,
                          ctc_merge_repeated=ctc_merge_repeated,
                          time_major=time_major)
```
