### ISSUE TITLE
Error Creating Predictor from Core Estimator

### ISSUE THREAD

**Issue by jacky-liang** [tensorflow/tensorflow#17184]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.5.0
- **Python version**:  3.5.3
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: 9.0.176
- **GPU model and memory**: Titan V, 12288 MB
- **Exact command to reproduce**: See below

### Describe the problem
Creating a Predictor object by calling `from_estimator` results in the following error:

```python
----> 5 est_pred= predictor.from_estimator(est, serving_input_receiver_fn)

c:\libraries\python35\lib\site-packages\tensorflow\contrib\predictor\predictor_factories.py in from_estimator(estimator, serving_input_receiver_fn, output_key, graph)
     86       `Estimator`.
     87   """
---> 88   if isinstance(estimator, estimator.Estimator):
     89     raise TypeError('Espected estimator to be of type '
     90                     'tf.python.estimator.Estimator, but got type '

AttributeError: 'Estimator' object has no attribute 'Estimator'
```

### Source code / logs
To reproduce this error:
```python
import tensorflow as tf
from tensorflow.contrib import predictor

def model_fn(features, labels, mode):
    # this will trigger other errors once the type check is passed
    return None
est = tf.estimator.Estimator(model_fn=model_fn)

def serving_input_receiver_fn():
    inputs = {'X': tf.placeholder(shape=[None, 1], dtype=tf.float32)}
    return tf.estimator.export.ServingInputReceiver(inputs, inputs)

est_pred = predictor.from_estimator(est , serving_input_receiver_fn)
```

It appears the type check on predictor_factories.py's line 88 has a typo, since ```estimator``` is overridden by the function argument.

**Comment by asimshankar** [comment]
Thanks for the report.

I believe this was fixed in https://github.com/tensorflow/tensorflow/pull/15648 which is included in TensorFlow 1.6 (which is in release candidate form right now, a final release should be out soon).
