### ISSUE TITLE
Tensorflow 1.6 ALWAYS looking for libcublas.so.8.0 with Cuda 9.0, Cudnn 7.0 (and libcublas.so.9.0)

### ISSUE THREAD

**Issue by arch-rh1** [tensorflow/tensorflow#17185]
### System information
- **OS Platform and Distribution** -  Linux Ubuntu 16.04
- **TensorFlow installed from** - source 
- **TensorFlow version** - tensorflow-1.6.0rc0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**:  0.10.1
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: Cuda 9.0/ cuDNN 7.0
- **GPU model and memory**: Nvidia Quadro M1200 w/4GB GDDR5
- **Exact command to reproduce**: `import tensorflow as tf`
- **Have I written custom code**: No. Just trying to import tensorflow in python. The only line of code I wrote is  `import tensorflow as tf`

### Problem
Tensorflow is looking for **libcublas.so.8.0** although I linked the cuda path during configuration to /usr/local/cuda-9.0  (also tried linking /usr/local/cuda ). How do I run tensorflow with cuda 9.0 and cudnn 7.0? 

Outputs of: 
`ldconfig -v` :

> libcublas.so.9.0 -> libcublas.so.9.0.176
> libcudnn.so.7 -> libcudnn.so.7.0.5

`import tensorflow as tf`

> ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory
> Failed to load the native TensorFlow runtime.

## Complete Traceback
`import tensorflow as tf`

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/user/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import *
>   File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory
> 
> Failed to load the native TensorFlow runtime.
>

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code

**Comment by gunan** [comment]
If you build from source(as indicated by the information you provided) , the CUDA version TF will look for is what you picked during the build. Therefore, this is a misconfiguration during your build, rather than a bug in TF.

**Comment by adamdunlap** [comment]
I thought tensorflow was only supported on the 3 series of python?

**Comment by arch-rh1** [comment]
Nope. I built from **source** (also tried with **pip** [_uninstalled tf, cleared cache before each install attempt_] )on **another** machine that has **Cuda 8, Cudnn 7.05**. I specified the path to the cuda-8.0 (_used actual [to cuda-8.0 folder] and symbolic path [to cuda folder] on separate occasions, same error_) and performed TF 1.6 configuration. When I try to import tf, I got :

```
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
Failed to load the native TensorFlow runtime.
```

@gunan  This issue is **not closed.**

**Comment by gunan** [comment]
I am sorry that you are still running into issues.
However, I just verified on my test machine by building TF master on a machine cuda 8.0, cudnn 6.
tf.test.is_gpu_available() returns true, and I can run a very simple graph.

```
$ $ echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64:/usr/local/cuda-8.0/lib64
$ ldd /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
	linux-vdso.so.1 =>  (0x00007ffcc1ccd000)
	libtensorflow_framework.so => /usr/local/lib/python2.7/dist-packages/tensorflow/python/../libtensorflow_framework.so (0x00007f612d0d5000)
	libcublas.so.8.0 => /usr/local/cuda/lib64/libcublas.so.8.0 (0x00007f612a725000)
	libcusolver.so.8.0 => /usr/local/cuda/lib64/libcusolver.so.8.0 (0x00007f61271b5000)
	libcudart.so.8.0 => /usr/local/cuda/lib64/libcudart.so.8.0 (0x00007f6126f4f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6126d4b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6126b2e000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f612690c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6126704000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f61263fb000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6126079000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6125e63000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6125a99000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6137ab8000)
	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f6124e0b000)
	libcudnn.so.6 => /usr/local/cuda/lib64/libcudnn.so.6 (0x00007f611b8a9000)
	libcufft.so.8.0 => /usr/local/cuda/lib64/libcufft.so.8.0 (0x00007f6112a5b000)
	libcurand.so.8.0 => /usr/local/cuda/lib64/libcurand.so.8.0 (0x00007f610eaf2000)
	libnvidia-fatbinaryloader.so.387.34 => /usr/lib/nvidia-387/libnvidia-fatbinaryloader.so.387.34 (0x00007f610e8a0000)
$ python 
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'1.6.0-rc1'
>>> tf.test.is_gpu_available()
....
True
>>> tf.Session().run(tf.constant('Hello World'))
...
2018-02-24 07:35:59.621155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10747 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
'Hello World'
```

Please check your LD_LIBRARY_PATH actually points to your cuda and cudnn library directories, please make sure you follow CUDA installation instructions carefully to make sure you have correct version of cuda correctly installed.

As I have built the code from scratch and I was able to successfully run TF with cuda 8, I do not have a way to help you with this.

**Comment by NYcleaner** [comment]
I have find the reason is ldconf, ldconfig is a dynamic link library management command whose purpose is to allow the dynamic link library to be usedby the system.

The default ldconf only search /lib and /usr/lib, as well as the library file under the directory listed in the configuration file /etc/ld. so. conf.

so all of this is caused by the dynamic library of CUDA in the installed CUDA path such as : /path/cuda-9.0/lib64 or /path/cuda-9.0/lib. (for eample my CUDA is installed in /usr/local/cuda-9.0)

  1.if you install the CUDA manual, then after install, you should add the path of cuda/lib64 to /etc/ld.so.conf file
 ` sudo echo "/usr/local/cuda-9.0/lib64/" >> /etc/ld.so.conf`
  then
`  sudo ldconfig`

of course , you can add the path manual, like:
`vim /etc/ld.so.conf`
then add the path '/usr/local/cuda-9.0' at the end. 
then update it 
`sudo ldconfig` 
after the operation, reopen the ipython or pycharm ,
`import tensorflow as tf
wow, you will enjoy it!

if you install the CUDA by command such as 'dpkg -i cuda-repo-ubuntu1604_9.0.176-1_amd64.deb' or others, it may add the cuda lib path to the /etc/ld.so.conf automatically . but to be on the safe side, check the /etc/ld.so.conf and see if the path add to it .

**Comment by banbsyip** [comment]
> I have find the reason is ldconf, ldconfig is a dynamic link library management command whose purpose is to allow the dynamic link library to be usedby the system.
> 
> The default ldconf only search /lib and /usr/lib, as well as the library file under the directory listed in the configuration file /etc/ld. so. conf.
> 
> so all of this is caused by the dynamic library of CUDA in the installed CUDA path such as : /path/cuda-9.0/lib64 or /path/cuda-9.0/lib. (for eample my CUDA is installed in /usr/local/cuda-9.0)
> 
> 1.if you install the CUDA manual, then after install, you should add the path of cuda/lib64 to /etc/ld.so.conf file
> ` sudo echo "/usr/local/cuda-9.0/lib64/" >> /etc/ld.so.conf`
> then
> ` sudo ldconfig`
> 
> of course , you can add the path manual, like:
> `vim /etc/ld.so.conf`
> then add the path '/usr/local/cuda-9.0' at the end.
> then update it
> `sudo ldconfig`
> after the operation, reopen the ipython or pycharm ,
> `import tensorflow as tf
> wow, you will enjoy it!
> 
> if you install the CUDA by command such as 'dpkg -i cuda-repo-ubuntu1604_9.0.176-1_amd64.deb' or others, it may add the cuda lib path to the /etc/ld.so.conf automatically . but to be on the safe side, check the /etc/ld.so.conf and see if the path add to it .

i tried it,but still wrong
