### ISSUE TITLE
Log "Waiting for new checkpoint at" in tf.contrib.training.evaluate_repeatedly only after the checkpoint is found

### ISSUE THREAD

**Issue by sergii-bond** [tensorflow/tensorflow#17182]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.5.0-rc1
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.9.0

### Problem description
I use `tf.contrib.training.evaluate_repeatedly` function found here: https://github.com/tensorflow/tensorflow/blob/37aa430d84ced579342a4044c89c236664be7f68/tensorflow/contrib/training/python/training/evaluation.py#L345

The two parameters that are relevant here are:
`timeout=1, timeout_fn=my_timeout_fn`, where `my_timeout_fn` is a custom function and returns True or False. Basically I want to stop evaluation loop if some condition is met, in which case the function will return 1. I have to set timeout to some small value, in this case 1 sec, so that timeout_fn is triggered often. The issue with this is that I get the next log message very often:
```
Waiting for new checkpoint at /path/to/dir
```
I set timeout=10, but still I don't want to see that useless log message every 10 seconds.

The message comes from here:
https://github.com/tensorflow/tensorflow/blob/37aa430d84ced579342a4044c89c236664be7f68/tensorflow/contrib/training/python/training/evaluation.py#L192

One of the solutions would be to put this logging command inside the caller of `wait_for_new_checkpoint` function and execute it once before `while True` loop on  line 248, and then right after ` yield checkpoint_path` on line 264. This way we get this message only after a checkpoint is found.

**Comment by asimshankar** [comment]
If you'd like to make a change, please feel free to send a pull request :)
Alternatively, you could use [`tf.logging.set_verbosity(tf.logging.WARN)`](https://www.tensorflow.org/api_docs/python/tf/logging/set_verbosity) to avoid any `logging.info` messages from showing up.

Hope that helps.
