### ISSUE TITLE
ValueError: Unknown activation function:relu6  while converting MobileNet under Keras to estimator using model_to_estimator

### ISSUE THREAD

**Issue by SofaPotatos** [tensorflow/tensorflow#17191]
Hi, I try to convert a mobilenet model under `tf.keras.application` to estimator using model_to_estimator.
I get an error (`ValueError: Unknown activation function:relu6`) due to relu6 is a customized activation defined in mobilenet.

Thanks for help.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
1.6r
- **Python version**: 
3.5
- **Bazel version (if compiling from source)**:
0.10.1
- **GCC/Compiler version (if compiling from source)**:
GCC
- **CUDA/cuDNN version**:
9.0
- **GPU model and memory**:
GTX 1070
- **Have I written custom code**: 
No
- **Exact command to reproduce**:
```python
import tensorflow as tf
keras_mobilenet= tf.keras.applications.mobilenet.MobileNet(weights=None)
keras_mobilenet.compile(optimizer=tf.keras.optimizers.SGD(lr=0.0001, momentum=0.9),
                          loss='categorical_crossentropy',
                          metric='accuracy')
mobilenet_estimator = tf.keras.estimator.model_to_estimator(keras_model=keras_mobilenet)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Exact command to reproduce

**Comment by SofaPotatos** [comment]
Thanks for your reply. I have just updated the post based on the issue template.

**Comment by brainnoise** [comment]
Please take a look at this related [issue](https://github.com/keras-team/keras/issues/7431) in Keras.

**Comment by SofaPotatos** [comment]
@brainnoise Thanks for your help. The following code works for my case.
```
import tensorflow as tf
from tensorflow.python.keras.utils import CustomObjectScope
def relu6(x):
  return K.relu(x, max_value=6)
with CustomObjectScope({'relu6': relu6}):
    keras_mobilenet= tf.keras.applications.mobilenet.MobileNet(weights=None)
    keras_mobilenet.compile(optimizer=tf.keras.optimizers.SGD(lr=0.0001, momentum=0.9),
                          loss='categorical_crossentropy',
                          metric='accuracy')
    mobilenet_estimator = tf.keras.estimator.model_to_estimator(keras_model=keras_mobilenet)
```

**Comment by schliffen** [comment]
If none of them worked (like my case) use exactly Keras 2.1.6 version, import relu6 from "keras.applicatiions.mobilenet". then use CustomObjectScope to load the model.

**Comment by schliffen** [comment]
I think in this case using tensorflow stuff here makes problem! (at least I tried and got error).

**Comment by dvlee1024** [comment]
@SofaPotatos  Thx. Your code works for me.

**Comment by MarkDaoust** [comment]
Hi everyone, 

I think this is fixed now, old versions of keras.applications has a custom [activatiomn funciton there](https://github.com/keras-team/keras-applications/blob/1.0.1/keras_applications/mobilenet.py#L77).

But now [the code](https://github.com/keras-team/keras-applications/blob/master/keras_applications/mobilenet.py#L361) uses [layers.ReLU](https://www.tensorflow.org/api_docs/python/tf/keras/layers/ReLU) with a max-value argument.
