### ISSUE TITLE
C++ gradients for MaxPool3D, AvgPool, AvgPool3D

### ISSUE THREAD

**Issue by kbsriram** [tensorflow/tensorflow#17195]
Looks like these just need to connect the gradient to an existing core op. Anyone already working on it? Otherwise, I'll sign up for these three.

/cc @bpiel @suharshs

**Comment by bpiel** [comment]
@kbsriram I'm not. thanks

**Comment by suharshs** [comment]
Nor am I. Thanks!

**Comment by bignamehyp** [comment]
Can you please provide more details? AvgPoolingGradOp already exists.

**Comment by suharshs** [comment]
@bignamehyp This is referring to C++ gradients: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/cc/gradients
