### ISSUE TITLE
tf.contrib.quantize: layer not quantized in absence of activation

### ISSUE THREAD

**Issue by DominikAuras** [tensorflow/tensorflow#17190]
In absence of an activation function, e.g., `tf.layers.Conv2D(...,activation=None,...)`, the graph matcher using the `activation_pattern` at
https://github.com/tensorflow/tensorflow/blob/671baf080238025da9698ea980cd9504005f727c/tensorflow/contrib/quantize/python/quantize.py#L185-L192
won't match the layer that has no activation function, and consequently, that layer won't be quantized. 

Maybe previously, instead of no activation function, `tf.identity` was used? The package `tf.contrib.quantize` searches for the identity op.
https://github.com/tensorflow/tensorflow/blob/671baf080238025da9698ea980cd9504005f727c/tensorflow/contrib/quantize/python/quantize.py#L35

Note that if `activation = None`, then no operation is inserted:
https://github.com/tensorflow/tensorflow/blob/671baf080238025da9698ea980cd9504005f727c/tensorflow/python/layers/convolutional.py#L192-L193

Example: Box predictors in SSD from the TF Object Detection API.
https://github.com/tensorflow/models/blob/be9b80251af1bc798553c9e5135f8b0f19fa0a81/research/object_detection/core/box_predictor.py#L688-L689

@suharshs

**Comment by suharshs** [comment]
I submitted a fix for this a couple days ago :) It should work after the next sync.

Also, these rewrites are very new and only have been tried on a few models, but we plan to expand this to more models, so any information on models you are trying to quantize would be super helpful!

Thanks!

**Comment by DominikAuras** [comment]
Thanks for your great work.

I am trying to quantize MobileNet SSD for detection on a custom dataset, for later use in an FPGA implementation. As a workaround, I modified the code to look for the Reshape node after the box predictors as "activation node", and if found, quantize the BiasAdd.

I took a look on your PR, but didn't test it yet. I believe that your changes will match all BiasAdd patterns, even those ending in an activation. Won't that lead to double quantization, before and after the e.g. ReLU6, since a layer with activation would yield two matches? Again, not tested yet.

**Comment by suharshs** [comment]
The detail is that the function that finds matches only `yield`s them. So the final layer match (the one checking for BiasAdd with no activation) only runs after the FakeQuant nodes are added to the other matches. The FakeQuant nodes being added make the second pattern match not double match. Does that make sense?

**Comment by DominikAuras** [comment]
Ah okay, I see how it works. You modify the graph inbetween the matching steps, thus the inserted FakeQuant ops prevent the double matching. 

Btw, did you try to quantize MobileNet SSD by any chance?

**Comment by cjr0106** [comment]
@DominikAuras  
hi ,i also want to  quantize MobileNet SSD for detection on a custom dataset, for later use in an FPGA implementation , could you share how to do it?
