### ISSUE TITLE
Eigen version in cmake mismatch

### ISSUE THREAD

**Issue by phisiart** [tensorflow/tensorflow#1720]
In `tensorflow/contrib/cmake/external/eigen.cmake`, both `eigen_archive_hash` and `eigen_HASH` don't match those in `tensorflow/workspace.bzl` and the source (e.g. `third_party/eigen3/Eigen/Cholesky`). This leads to build failure when using cmake.

Could anyone update `tensorflow/contrib/cmake/external/eigen.cmake`?

**Comment by vrv** [comment]
Fixed, I believe.

**Comment by vrv** [comment]
(with 2c2f422a628d83a591fb5d20d46deecc47655ead)

**Comment by clsung** [comment]
Updated in #1738

**Comment by phisiart** [comment]
Brilliant! Now even [CLion](https://www.jetbrains.com/clion/)'s debugging seems to work.

**Comment by ccnankai** [comment]
@phisiart 
which version of tensorflow and clion you used, can teach me the configuration process import tensorflow source code . After installing the plugin, import the source directly? Still need to run other steps?
