### ISSUE TITLE
__init__() got an unexpected keyword argument 'dct_method'

### ISSUE THREAD

**Issue by zeshaoaaa** [tensorflow/tensorflow#17208]
### System information
- **What is the top-level directory of the model you are using**:
      C:\Users\Administrator\Documents\Projects\models
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
     Just changed the filename of 'train.py' to 'my_train.py'.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
     Windows 10
- **TensorFlow installed from (source or binary)**:
      Binary
- **TensorFlow version (use command below)**:
      1.5
- **CUDA/cuDNN version**:
     CUDA v9.0
- **GPU model and memory**:
      NVDIA GeForce GT 730

### Describe the problem
Is the new version have some bugs or my installation is incorrect? because I saw the source code of the 'Image' class of tf.example_decoder, it is no an argument named 'dec_method' in the 'init' method. If my description or log is not clear enough, please tell me. Thanks in advance!

### Source code / logs
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "C:/Users/Administrator/Documents/Projects/models/research/object_detection/my_train.py", line 120, in get_next
    dataset_builder.build(config)).get_next()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\builders\dataset_builder.py", line 138, in build
    label_map_proto_file=label_map_proto_file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\data_decoders\tf_example_decoder.py", line 110, in __init__
    dct_method=dct_method),
TypeError: __init__() got an unexpected keyword argument 'dct_method'

**Comment by RDaneelOlivav** [comment]
How did you fix this issue? I'm getting the exact same one

**Comment by zeshaoaaa** [comment]
@RDaneelOlivav I just clone the 'r1.5' branch of the 'models' repository and uninstall 'tensorflow-gpu' and install tensorflow 1.5, after that, the problem is disappeared. Seems it come from the 'gpu' version of tensorflow. I don't know, if my response doesn't solve your problem, I suggest you can open a new issue for that.

**Comment by jqcorreia** [comment]
Hey there,

Remove `dct_method=dct_method` in `object_detection/data_decoders/tf_example_decoder.py` around line 109. This fixed it for me. 

Using TensorFlow 1.5 and `4c0541482` of `tensorflow/models` without a problem

**Comment by valiok98** [comment]
Thanks a lot @jqcorreia
