### ISSUE TITLE
No clear documentation about how optimizer works through tf.tile() 

### ISSUE THREAD

**Issue by dchatterjee172** [tensorflow/tensorflow#17215]
If some one uses this type of code for batch learning,
`w1=tf.get_variable("W1", [300,300], dtype=tf.float32, initializer=init)
W1=tf.tile(tf.expand_dims(w1,axis=0), [batch_size,1,1], name="batch_W1")
x1=tf.placeholder(name="context",dtype=tf.float32,shape=[None,None,300]) ;
y=tf.matmul(x1,W1)`
how the optimizer will combine the gradients from `W1 [batch_size,300,300]` to `w1[300,300]`?
I asked this question in stackoverflow also but none replied.
https://stackoverflow.com/questions/48933564/is-this-the-appropriate-way-to-set-up-weights-in-batch-learning-in-tensorflow

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dchatterjee172** [comment]
I have included a custom code, rest are not required in this case

**Comment by netheril96** [comment]
When in doubt, check the [source code](https://github.com/tensorflow/tensorflow/blob/7c324811f10eaf049735ace7b6a228ccc931d8ff/tensorflow/python/ops/array_grad.py#L566).

So apparently, in your case, the gradient will be summed along axis 0 in back propagation.

**Comment by dchatterjee172** [comment]
Thank you very much, I'll remember that from next time.
You can close the issue.
