### ISSUE TITLE
Level 3 warnings in core headers

### ISSUE THREAD

**Issue by cnovel** [tensorflow/tensorflow#17213]
I found some level 3 warnings in core headers:

```
tensorflow/core/framework/node_def_util.h(118): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
tensorflow/core/lib/core/arena.h(46): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
tensorflow/core/graph/graph.h(475): warning C4244: 'return': conversion from 'const tensorflow::int64' to 'int', possible loss of data
tensorflow/core/graph/graph.h(480): warning C4244: 'return': conversion from 'tensorflow::int64' to 'int', possible loss of data
include\tensorflow/core/graph/graph.h(509): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
tensorflow/core/graph/graph.h(518): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
```

This issue can be fixed using static_cast<>. I'm using VS2017 15.5.6 on Windows 10.

**Comment by bignamehyp** [comment]
This warnings might be compiler specific.

**Comment by cnovel** [comment]
As far as I know, gcc will also raise warnings for conversion from 'size_t' to 'int' ([see here for example](https://stackoverflow.com/questions/27490762/how-can-i-convert-to-size-t-from-int-safely)). Beyond the warning issue, is there any reason to return an int instead of a size_t since these functions are returning sizes (so positive integer)?
