### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow-gpu (from versions: )

### ISSUE THREAD

**Issue by jcplus** [tensorflow/tensorflow#17217]
Can anyone help with this? I tried quite a few times even wiped the computer and started from scratch.

**Environment**
- CPU: Intel i7
- Memory: 16GB
- OS: Windows 10 64bit
- Nvidia GTX 1060 (latest driver installed: 390.77-desktop-win10-64bit-international-whql)
- Visual Studio Community
- CUDA 8.0 for Windows 10
- cuDNN 5.1 for CUDA 8.0
- Python 3.6.4

I have a few versions available on local hard drive but all of them are giving me the same error message.
- tensorflow-1.5.0-cp36-cp36m-win_amd64.whl
- tensorflow-1.6.0rc1-cp35-cp35m-win_amd64.whl
- tensorflow-1.6.0rc1-cp36-cp36m-win_amd64.whl

**By running `python -c "from pip import pep425tags;print(pep425tags.supported_tags)"`**:
`[('cp36', 'cp36m', 'win32'), ('cp36', 'none', 'win32'), ('py3', 'none', 'win32'), ('cp36', 'none', 'any'), ('cp3', 'none', 'any'), ('py36', 'none', 'any'), ('py3', 'none', 'any'), ('py35', 'none', 'any'), ('py34', 'none', 'any'), ('py33', 'none', 'any'), ('py32', 'none', 'any'), ('py31', 'none', 'any'), ('py30', 'none', 'any')]`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jcplus** [comment]
- Have I written custom code: N/A
- OS Platform and Distribution: Windows 10 64bit
- TensorFlow installed from: local files
- TensorFlow version: tensorflow-1.6.0rc1-cp35-cp35m-win_amd64.whl
- Bazel version: N/A
- CUDA/cuDNN version: 8.0/5.1
- GPU model and memory: GTX 1060 4GB
- Exact command to reproduce: `pip3 install tensorflow-1.6.0rc1-cp35-cp35m-win_amd64.whl`

Hope this helps.

**Comment by CarltonSemple** [comment]
You need CUDA 9.0 and cuDNN v7.0, and then make sure they're referenced in the Path environment variable.
See https://www.tensorflow.org/install/install_windows

**Comment by CarltonSemple** [comment]
Also, choose a command with `cp36` since you have Python 3.6.
For example
~~~~
pip3 install tensorflow-1.6.0rc1-cp35-cp35m-win_amd64.whl
~~~~

**Comment by jcplus** [comment]
Are there any x64 versions?

**Comment by jcplus** [comment]
I found the issue:
My windows 10 is 64 bit but I have a 32 bit python installed. After uninstalled the 32 bit python and reinstalled the 64 bit python, problem solved.
Thanks for everyone.

**Comment by CorruptedMonkey** [comment]
it still doesnt work for me

**Comment by chiu0602** [comment]
Currently TensorFlow released Python package up to 3.6, I have met the same problem and success after using Python 3.6 instead of 3.7, wish this help..

**Comment by haithink** [comment]
> Currently TensorFlow released Python package up to 3.6, I have met the same problem and success after using Python 3.6 instead of 3.7, wish this help..

yes, you are right!!!!

**Comment by Harsha-1729** [comment]
> I installed CUDA 9.1.85 and cudnn 7 for 9.1 and tried
> 
> ```shell
> pip3 install tensorflow-1.6.0rc1-cp36-cp36m-win_amd64.whl
> ```
> 
> but still having **tensorflow-1.6.0rc1-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.** issue.

Hey Hi
Can you please tell me how did you install CUDA 9.1.85?
If you have any hyperlinks to install please share, I will try them.

Thanks
