### ISSUE TITLE
NotFoundError: Op type not registered 'KafkaDataset' in binary.

### ISSUE THREAD

**Issue by MtDersvan** [tensorflow/tensorflow#17210]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: - 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: ('unknown', '1.6.0-rc1')
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.8.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: -
- **GPU model and memory**: -
- **Exact command to reproduce**:

~~~python
from tensorflow.contrib.kafka.python.ops import kafka_dataset_ops
from tensorflow.python.data.ops import iterator_ops
from tensorflow.python.framework import dtypes
from tensorflow.python.ops import array_ops

topics = array_ops.placeholder(dtypes.string, shape=[None])
num_epochs = array_ops.placeholder(dtypes.int64, shape=[])
batch_size = array_ops.placeholder(dtypes.int64, shape=[])

repeat_dataset = kafka_dataset_ops.KafkaDataset(
    topics, group="test", eof=True).repeat(num_epochs)
batch_dataset = repeat_dataset.batch(batch_size)

iterator = iterator_ops.Iterator.from_structure(batch_dataset.output_types)
init_op = iterator.make_initializer(repeat_dataset)
init_batch_op = iterator.make_initializer(batch_dataset)
get_next = iterator.get_next()
~~~

ENV: https://pastebin.com/89aihba7

### Describe the problem
Getting `NotFoundError` even with `TF_NEED_KAFKA=1` and `--define with_kafka_support=true`:
~~~
NotFoundError: Op type not registered 'KafkaDataset' in binary running on 68a9f992375e. Make sure the Op and Kernel are registered in the binary running in this process.
~~~
`KafkaDataset` was merged into master last month. Is there something missing that needs to be done in order to utilize the new op? 

### Source code / logs
https://pastebin.com/5Vy6b6kf

**Comment by asimshankar** [comment]
IIUC, the PR you're referring to is https://github.com/tensorflow/tensorflow/pull/14098

I might be missing something but it seems that the BUILD target for the kernels [`//tensorflow/contrib/kafka:kafka_kernels`](https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/contrib/kafka/BUILD#L15) isn't included as a dependency of any other target so the kernels are not being linked in. 

@yongtang @jhseu , could you take a look? Should there be a kernel library DSO that is created and loaded at build time? Or, if not, the kafka kernels library target needs to be linked in somewhere, right?

**Comment by yongtang** [comment]
@MtDersvan @asimshankar At the moment the Kafka Op could be optionally built with ./configure (specify `y`):
```
Do you wish to build TensorFlow with Apache Kafka Platform support? [y/N]: 
```

It is not part of the default configuration (only with customized build).

There were some issues with `.so` as the op requires linkage with core and bazel could not resolve the linkage.

That was the case a couple of months ago. I will take a look and see if it is possible to build a `.so` and load dynamically now.

**Comment by MtDersvan** [comment]
@yongtang If I understand correctly, `--define with_kafka_support=true` or `TF_NEED_KAFKA=1` is equivalent to specifying `y` in `Do you wish to build TensorFlow with Apache Kafka Platform support? [y/N]`, so it should be working.
I don't think tensorflow picks up the cpp kernel properly. I tried adding the [kernel](https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/contrib/kafka/BUILD#L15) itself  to the contrib [BUILD](https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/contrib/BUILD) but to no success.

**Comment by cfregly** [comment]
@yongtang same issue.  bazel 0.11.0, python3, cuda 9.0, cudnn 7.0, TF_NEED_KAFKA=1 

fresh build from a couple days ago:  4faee3942d9983e0c96091b32095cc0d9ff494e0

Note:  i didn't set `--with_kafka_support=true`

**Comment by yongtang** [comment]
@MtDersvan @cfregly Thanks for the info. Was on the road and had to do some other stuff so wasn't able to reply in time. But let me assign the issue to myself. I will take a look in the next several days.

**Comment by yongtang** [comment]
Added a PR #17418 for the fix.
