### ISSUE TITLE
Tensorflow-produced HLO graphs cannot be rendered by graphviz

### ISSUE THREAD

**Issue by Richard-Neill** [tensorflow/tensorflow#17220]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No, I'm using standard `mnist_softmax_xla.py` with unmodified tensorflow (cloned from master)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04: 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **TensorFlow installed from (source or binary)**:
Source, with XLA and CUDA
- **TensorFlow version (use command below)**:
tf.VERSION = 1.6.0-rc0
tf.GIT_VERSION = v1.5.0-2285-g4448430
tf.COMPILER_VERSION = v1.5.0-2285-g4448430
- **Python version**: 
Python 3.5.2
- **Bazel version (if compiling from source)**:
bazel release 0.10.0
- **GCC/Compiler version (if compiling from source)**:
gcc 5.4.0 20160609
- **CUDA/cuDNN version**:
== cuda libs  ===================================================
/usr/local/cuda-9.0/doc/man/man7/libcudart.7
/usr/local/cuda-9.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so.9.0.176
/usr/local/cuda-9.1/doc/man/man7/libcudart.7
/usr/local/cuda-9.1/doc/man/man7/libcudart.so.7
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudart.so.9.1.85
- **GPU model and memory**:
Nvidia Titan V Driver Version: 387.34, 12058MiB
- **Exact command to reproduce**:
    TF_XLA_FLAGS="--xla_hlo_graph_path=/home/user/test/hlo_graphs --xla_generate_hlo_graph=.*" python3 mnist_softmax_xla.py

### Describe the problem
I want to run XLA JIT on the `mnist_softmax_xla.py` example script, and then view the generated HLO to see what was compiled. To do this, I run:

    $> TF_XLA_FLAGS="--xla_hlo_graph_path=/home/user/test/hlo_graph --xla_generate_hlo_graph=.*" python3 mnist_softmax_xla.py

This produces a lot of text:

    **[omitted]**
    2018-02-23 12:42:22.413434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1016] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10979 MB memory) -> physical GPU (device: 0, name: Graphics Device, pci bus id: 0000:01:00.0, compute capability: 7.0)
    2018-02-23 12:42:22.743524: I tensorflow/compiler/xla/service/service.cc:158] XLA service 0x7fc63c001800 executing computations on platform CUDA. Devices:
    2018-02-23 12:42:22.743569: I tensorflow/compiler/xla/service/service.cc:166]   StreamExecutor device (0): Graphics Device, Compute Capability 7.0
    **[omitted]**
    2018-02-23 12:42:22.796890: I tensorflow/compiler/xla/service/hlo_graph_dumper.cc:1395] computation cluster_0__XlaCompiledKernel_true__XlaNumConstantArgs_0__XlaNumResourceArgs_0_.v83 [GPU-ir-emit-prepare: after copy-insertion, pipeline end]: /home/user/test/hlo_graph/hlo_graph_47.mcrbox-6dffc700-28862-565e07de51010.dot
    2018-02-23 12:42:22.973757: W tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:351] *** WARNING *** You are using ptxas 9.1.108, which is in range [9.0.0, 9.0.276) + [9.1.0, 9.1.121). These versions are known to miscompile XLA code, leading to incorrect results or invalid-address errors.
    2018-02-23 12:42:24.527632: I tensorflow/stream_executor/dso_loader.cc:147] successfully opened CUDA library libcupti.so.9.1 locally
    **[omitted]**

Apart from the warning for the ptxas version (which I believe there is no way for me to fix because I'm using the latest available version of CUDA that I can get from Nvidia), this appears to be successful and the compiled execution can be seen in the timeline.json. However, I want to view the HLO graph with `graphviz`, so using the above output, I try to load `hlo_graph/hlo_graph_47.mcrbox-6dffc700-28862-565e07de51010.dot`. However, I get an error:

    $> dot -Tpng hlo_graph/hlo_graph_47.mcrbox-6dffc700-28862-565e07de51010.dot -o graph.png
    Error: hlo_graph/hlo_graph_47.mcrbox-6dffc700-28862-565e07de51010.dot: syntax error in line 10 near ''

Line 10 is the large stylesheet definition in the `.dot` file. It's very long and I am not familiar with the syntax, but it 'seems' like there are no missing/supernumerary quotations anywhere. Is this a known problem or have I done something incorrectly? Is there another renderer (i.e. not `graphviz`) that I can target out-of-the-box?

I've attached the aforementioned `.dot` file as a `.txt`:
[hlo_graph_47.mcrbox-6dffc700-28862-565e07de51010.txt](https://github.com/tensorflow/tensorflow/files/1751694/hlo_graph_47.mcrbox-6dffc700-28862-565e07de51010.txt)

The graphviz version I'm using is:

    dot - graphviz version 2.38.0 (20140413.2041)

**Comment by Richard-Neill** [comment]
The rendering works with the 'spreadsheet' attribute entirely removed. 

Looking in a little more depth, we get an error when the spreadsheet is restricted to 312 lines. For example, if you remove lines 323:665 in the attached `.dot` file then no error is given. If you instead remove lines 324:665, i.e. 1 extra line, we get the error from before.

It does not seem like the syntax of lines 323 onwards is problematic, as we can move those CSS selectors earlier in the file and get no error, provided we don't go past 312 lines. 

This looks like it is therefore a `graphviz` issue, but I will keep this open if we are interested in some kind of workaround for Tensorflow.

**Comment by asimshankar** [comment]
@tatatodd in case he has any thoughts on what typically works for visualizing HLO graphs.

**Comment by tatatodd** [comment]
@jlebar might have some thoughts here, as he's worked on HLO visualization.

**Comment by jlebar** [comment]
Yeah, maybe try graphviz v2.40.1 or newer?  That seems to be what we're using internally.  (I say "seems to be because...it's complicated, and I can't just run `dot -v`.)  You may also need to pass `-Tsvg` given that we have the HTML selectors, I dunno.  I verified that `-Tsvg` doesn't work with v2.38.0.

FYI the graphs can get pretty big, and at some point graphviz will be unable to render even if it can parse.  Internally we have an interactive tool which can render subsets of the graph.  There's no fundamental reason this can't be open-sourced, and it probably should be.  But...no promises on when we'd be able to do that.

**Comment by Richard-Neill** [comment]
Using `dot - graphviz version 2.40.1 (20161225.0304)`, I get a more precise confirmation from graphviz about the problem:

     Error: hlo_graph_47.mcrbox-6dffc700-28862-565e07de51010.dot: syntax error in line 10 scanning a quoted string (missing endquote? *longer than 16384?*)
    String starting:"
      data:text/css,
      @import url(https://fonts.googleapis.com/css?family=Roboto:4

In graphviz, the buffer size is defined as 2^14:

    #define YY_BUF_SIZE 16384

I put it up to 2^20 and built graphviz from source, and I can now render the HLO as SVG. 

> Internally we have an interactive tool which can render subsets of the graph.

This sounds good and indeed necessary for ever-larger graphs, let us know if/when there is movement on releasing it.

**Comment by dmoham1476** [comment]
Hi Richard, this really helped, thanks

**Comment by goydex** [comment]
This also saved my bacon. Thanks!

**Comment by namizzz** [comment]
Hi @Richard-Neill , could you please tell me where is the "#define YY_BUF_SIZE 16384"?

**Comment by jlebar** [comment]
> This sounds good and indeed necessary for ever-larger graphs, let us know if/when there is movement on releasing it.

This is top of mind again, I'm hoping I can get something workable in the next few weeks.  If and when this happens, I'll announce it on the xla-dev mailing list, https://groups.google.com/forum/#!forum/xla-dev.

**Comment by jlebar** [comment]
The tool has landed!

https://github.com/tensorflow/tensorflow/commit/4817dabb5aba45547c6c1f5ef79d2b0c2040d51f

As a bonus it doesn't use `dot` on your local machine (it uses an asmjs version), so you shouldn't need to rebuild dot locally.

**Comment by Richard549** [comment]
Hi @jlebar, apologies for the lack of response. The solution looks good, thanks for putting it out there!
