### ISSUE TITLE
The nightly gpu builds for python 3 are failing consistently

### ISSUE THREAD

**Issue by Styrke** [tensorflow/tensorflow#1722]
The nightly gpu builds for python 3 are failing some tests consistently.

In the [most recent console output log](http://ci.tensorflow.org/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=gpu-working/50/consoleFull), the following 4 tests seem to fail: (each item links to the relevant test output log)

- [(66 / 224) Python test-on-install FAILED (): tensorflow/python/kernel_tests/bias_op_test.py](http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=gpu-working/ws/pip_test/tests/logs/tensorflow/python/kernel_tests/bias_op_test.py.log)
- [(75 / 224) Python test-on-install FAILED (): tensorflow/python/kernel_tests/conv_ops_test.py](http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=gpu-working/ws/pip_test/tests/logs/tensorflow/python/kernel_tests/conv_ops_test.py.log)
- [(93 / 224) Python test-on-install FAILED (): tensorflow/python/kernel_tests/fft_ops_test.py](http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=gpu-working/ws/pip_test/tests/logs/tensorflow/python/kernel_tests/fft_ops_test.py.log)
- [(120 / 224) Python test-on-install FAILED (): tensorflow/python/kernel_tests/pooling_ops_test.py](http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=gpu-working/ws/pip_test/tests/logs/tensorflow/python/kernel_tests/pooling_ops_test.py.log)

(Also: The link in the [readme file](https://github.com/tensorflow/tensorflow/blob/master/README.md) to the nightly gpu builds for python 3 seems to pointing to some old build that hasn't been updated for a week?)

**Comment by caisq** [comment]
@martinwicke @vrv Any plan to get this fixed soon?

**Comment by vrv** [comment]
To me, that's gating the next release, so probably :)

**Comment by martinwicke** [comment]
I filed bugs for these and assigned people, and some were fixed. It looks
like the failures are still the same though :(

**Comment by vrv** [comment]
I'm fixing some of them.
