### ISSUE TITLE
Cmake build doesn't work on ubuntu 16.04

### ISSUE THREAD

**Issue by achalshah20** [tensorflow/tensorflow#17232]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: Latest from master branch
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: 5.4
- **CUDA/cuDNN version**: Cuda 9.1, cuDNN 7.0.5
- **GPU model and memory**: GeForce GTX TITAN X, 12288 MB
- **Exact command to reproduce**:
git clone https://github.com/tensorflow/tensorflow
cd tensorflow/tensorflow/contrib/cmake/
mkdir build && cd build 
ccmake .. [correct cuda version and add nccl library, idk why that was mandatory though.]
make -j

### Describe the problem
I am trying to compile tensorflow with cmake on ubuntu 16.04. Some issues I have faced till now:

**1. cuda/extras/CUPTI/include/cupti.h no found (In cupti_wrapper.h)**
Temp fix: I saw "cuda/extras/CUPTI/include" is already included in the cmake. So, changed "cuda/extras/CUPTI/include/cupti.h" => "cupti.h" and it works.

**2. src/nccl.h not found (In nccl_manager.h and nccl_ops.cc)**
Temp fix: nccl v2 doesnt have src folder but nccl.h can be found in /usr/include/. So, changed
"src/nccl.h" => nccl.h and it works

**3. GRPC is not linked to libpywrap_tensorflow_internal.so (Not fixed yet)**
`[100%] Running SWIG to generate Python wrappers
[100%] Building CXX object CMakeFiles/pywrap_tensorflow_internal.dir/pywrap_tensorflow_internal.cc.o
[100%] Linking CXX shared library libpywrap_tensorflow_internal.so
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `on_txt_done_cb(void*, int, int, unsigned char*, int)':
grpc_ares_wrapper.cc:(.text+0x256): undefined reference to `ares_parse_txt_reply_ext'
grpc_ares_wrapper.cc:(.text+0x267): undefined reference to `ares_strerror'
grpc_ares_wrapper.cc:(.text+0x363): undefined reference to `ares_free_data'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `on_srv_query_done_cb(void*, int, int, unsigned char*, int)':
grpc_ares_wrapper.cc:(.text+0x65a): undefined reference to `ares_parse_srv_reply'
grpc_ares_wrapper.cc:(.text+0x677): undefined reference to `ares_free_data'
grpc_ares_wrapper.cc:(.text+0x683): undefined reference to `ares_strerror'
grpc_ares_wrapper.cc:(.text+0x7cf): undefined reference to `ares_gethostbyname'
grpc_ares_wrapper.cc:(.text+0x830): undefined reference to `ares_gethostbyname'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `on_hostbyname_done_cb(void*, int, int, hostent*)':
grpc_ares_wrapper.cc:(.text+0x964): undefined reference to `ares_strerror'
grpc_ares_wrapper.cc:(.text+0xb7d): undefined reference to `ares_inet_ntop'
grpc_ares_wrapper.cc:(.text+0xc62): undefined reference to `ares_inet_ntop'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `grpc_dns_lookup_ares_impl(char const*, char const*, char const*, grpc_pollset_set*, grpc_closure*, grpc_lb_addresses**, bool, char**)':
`
**4. Can't fix with GRPC OFF in ccmake (Not fixed yet)**

There are so many issues in CMake and I am not able to build directly on ubuntu 16.04. Can someone look into this? Thanks!

**Comment by gunan** [comment]
Currently, cmake build is only recommended for windows.
Bazel is the currently tested and officially supported build system on ubuntu.

**Comment by achalshah20** [comment]
I can surely take a look to make it work in linux environment. In so many of my projects I have to use cmake so I will fix and send PR. Other contributors are also welcome for speedup.

**Comment by tedhtchang** [comment]
@achalshah20 I saw similar grpc error on my Mac before so this PR #17005 may fix your grpc issue.

**Comment by mskwarek** [comment]
What do you think about using SCons as building script?

**Comment by achalshah20** [comment]
@mskwarek It may be good but most of the c++ projects like opencv, caffe,dlib are already using CMake. So, it's so convenient if tensorflow also officially support CMake, that way anyone can easily integrate tensorflow code to their product without using bazel build to create shared library and copy pasting some includes manually and etc. etc. .

**Comment by Skydes** [comment]
@achalshah20 Did you eventually manage to get the CMake build to work on Ubuntu ?

**Comment by yongtang** [comment]
I created a PR #18775 which should address the issue to build with CMAKE+GPU on Ubuntu. Please take a look if interested.

**Comment by achalshah20** [comment]
Thanks. I will test and let you know if it works for me!

**Comment by achalshah20** [comment]
Hey @yongtang , It actually builds successfully. But currently does tensorflow cmake have install rule?

**Comment by achalshah20** [comment]
So, If i want to use tensorflow c++ library, I don't need pip package but .so file and .h headers. So, I can't achieve that using current tensorflow cmake?
