### ISSUE TITLE
Getting ValueError: setting an array element with a sequence from tf.contrib.keras.preprocessing.image.ImageDatagenerator.flow

### ISSUE THREAD

**Issue by sadimanna** [tensorflow/tensorflow#17242]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution**:  Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.6.0-rc0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.10.0
- **GCC/Compiler version (if compiling from source)**: 5,4.0

I am trying to do Data Augmentation in Tensorflow. I have written this code.

    import numpy as np
    import tensorflow as tf
    import tensorflow.contrib.keras as keras
    import time, random
    
    def get_image_data_generator():
    	return keras.preprocessing.image.ImageDataGenerator(
        rotation_range=get_random_rotation_angle(),\
        width_shift_range=get_random_wh_shift(),\
        height_shift_range=get_random_wh_shift(),\
        shear_range=get_random_shear(),\
        zoom_range=get_random_zoom(),\
        horizontal_flip=get_random_flip(),\
        vertical_flip=get_random_flip(),\
        preprocessing_function=get_random_function())
        
    def augment_data(image_array,label_array):
    	print image_array.shape
    	images_array = image_array.copy()
    	labels_array = label_array.copy()
    	#Create a list of various datagenerators with different arguments
    	datagenerators = []
    	ndg = 10
        #Creating 10 different generators
    	for ndata in xrange(ndg):
    		datagenerators.append(get_image_data_generator())
        #Setting batch_size to be equal to no.of images
    	bsize = image_array.shape[0]
    	print bsize
        #Obtaining the augmented data
    	for dgen in datagenerators:
    		dgen.fit(image_array)
    		(aug_img,aug_label) = dgen.flow(image_array,label_array,batch_size=bsize,shuffle=True)
    		print aug_img.shape
            #Concatenating with the original data
    		images_array = np.concatenate([images_array,aug_img],axis=0)
    		labels_array = np.concatenate([labels_array,aug_label],axis=0)
    	return (images_array,labels_array)
   
When I run the code using

`augment_data(image_array,label_array)`

I get an error which says

    Traceback (most recent call last):
      File "cnn_model.py", line 40, in <module>
        images_array,labels_array = augment_data(image_array,label_array)
      File "/media/siladittya/d801fb13-809a-41b4-8f2e-d617ba103aba/ISI/code/2. known_object_detection/aug_data.py", line 47, in augment_data
        (aug_img,aug_label) = dgen.flow(image_array,label_array,batch_size=10000,shuffle=True)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/preprocessing/image.py", line 1018, in next
        return self._get_batches_of_transformed_samples(index_array)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/preprocessing/image.py", line 991, in _get_batches_of_transformed_samples
        batch_x[i] = x
    ValueError: setting an array element with a sequence.

Edit :: I am getting this error even if I pass a single image as argument.

What am I doing wrong here? I can't understand. Please help.

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
