### ISSUE TITLE
What defines the output tensor shape of tf.layers.conv2d_transpose?

### ISSUE THREAD

**Issue by miranthajayatilake** [tensorflow/tensorflow#17250]
When using `tf.layers.conv2d_transpose` what defines the output tensor shape?
For example: if the input was 4x4x512, for the output to be 8x8x256 the filters can be given, but how are is the height and width defined? Or else is it always two times the input height and width?

Thanks.

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
