### ISSUE TITLE
DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead 1.6rc0

### ISSUE THREAD

**Issue by JeromeDesseaux** [tensorflow/tensorflow#17254]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- Ubuntu 16.04
- Tensorflow installed from source, latest HEAD from master (CPU)
- 1.6rc0
- Python 3.5.2
- Bazel 0.10.1
- gcc-5

### Describe the problem
When using tensorflow, I got hundred of DeprecationWarnings: This message exactly 

> /home/jerome/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py:560: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  return np.fromstring(tensor.tensor_content, dtype=dtype).reshape(shape)

EDIT : fixed replacing line 560 in tensor_util.py by : 

`return np.frombuffer(tensor.tensor_content, dtype=dtype).reshape(shape)`

Thanks for any kind of help :)

**Comment by sadimanna** [comment]
```
import warnings
warnings.simplefilter("ignore", DeprecationWarning)
```

I used this at the start of my code which suppresses the warning.

**Comment by imsheridan** [comment]
I assume this is a duplicate issue of #17020, which was fixed already.

**Comment by yongtang** [comment]
Since the issue has been fixed in https://github.com/tensorflow/tensorflow/commit/f5c581f0f4649898ed00650fe98c7ef344e0f240. Let me close this one. Feel free to reopen if the issue persists. Thanks for the contribution!

**Comment by LionSR** [comment]
Which version of tensorflow should I to fix this?

**Comment by Chrisinger** [comment]
Follow the link by yongtang. There is says it is fixed since version v1.7.0-rc0.

**Comment by Rutuja-555** [comment]
> ```
> import warnings
> warnings.simplefilter("ignore", DeprecationWarning)
> ```
> 
> I used this at the start of my code which suppresses the warning.

where to use this particularly

**Comment by msameeruddin** [comment]
> > ```
> > import warnings
> > warnings.simplefilter("ignore", DeprecationWarning)
> > ```
> > 
> > 
> > I used this at the start of my code which suppresses the warning.
> 
> where to use this particularly

before all the imports in your script file.
