### ISSUE TITLE
tensorflow suddenly cannot detect my GPUs

### ISSUE THREAD

**Issue by Lancerchiang** [tensorflow/tensorflow#17255]
I was working with tensorflow-gpu, and it worked properly before. But just now, suddenly my Tensorflow cannot run on GPU anymore and when I query my devices with `list_local_devices()`, it shows that I don't have any GPU! But my nvidia-smi properly displayed the info of my 2 GPUs. It's very weird since I did't do anything.

**Comment by jerryshao4u** [comment]
Maybe you can check your CUDA is already installed, and with the correct version?
