### ISSUE TITLE
CI: TensorFlow build is failing on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [tensorflow/tensorflow#17268]
Before merging #16659, we should fix the TF build on Windows first.

Current failure:
```
subprocess.CalledProcessError: Command '['bazel', '--batch', 'version']' returned non-zero exit status 36
```
Culprit is https://github.com/tensorflow/tensorflow/commit/671baf080238025da9698ea980cd9504005f727c
because `f.write('import %s\n' % _TF_BAZELRC)` writes backslash into bazelrc file without escaping.
I'll send a fix.
FYI, @gunan @martinwicke @case540

**Comment by CarltonSemple** [comment]
By the way, is this related to https://github.com/tensorflow/tensorflow/issues/16138 ? Or are you referring to a build with VS 2015?

**Comment by meteorcloudy** [comment]
Sorry for the confusion, I meant the build on TF CI.
See http://ci.tensorflow.org/job/tf-master-win-bzl/2577/
