### ISSUE TITLE
'num' must be either a scalar or vector in tf.unstack?

### ISSUE THREAD

**Issue by Imorton-zd** [tensorflow/tensorflow#17266]
```
batch_size = tf.placeholder([],dtype=tf.int32) 
tf_x = tf.placeholder(tf.float32, [None,timestep_size,input_size])     
  
lstm_cell = rnn.BasicLSTMCell(num_units=hidden_size, forget_bias=1.0, state_is_tuple=True)
init_state = lstm_cell.zero_state(batch_size, dtype=tf.float32)

inputs = tf.unstack(tf_x,num=batch_size,axis=0)

ValueError: 'num' must be either a scalar or vector, but saw tensor
```

When training and test, I want to use the different batch size. But in `unstack` function, the `num` parameter doesn't support a tensor as input. However, in `zero_state` function, the first parameter can support a tensor as input. I think the new version should support this practical feature. Thanks!

**Comment by kdhingra307** [comment]
@angersson can I add a fix to this issue??

**Comment by angersson** [comment]
@kdhingra307 Please do! If you plan to contribute the code yourself, please have a look at [CONTRIBUTING.md](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md).

**Comment by kdhingra307** [comment]
@angersson i will, thanks

**Comment by jason9693** [comment]
@angersson  I finished this implementation. Please wait for just a little bit of time.

**Comment by facaiy** [comment]
@jason9693 Could you open a PR? I think it can be more convenient for review. By the way, perhaps we'd better let `gen_array_ops.unpack` supports `num` Tensor, rather than convert Tensor back to int :-)

**Comment by facaiy** [comment]
@jason9693 Yes, happy to see your pull request :-)  I agree that it's better to modify c++ code to support num Tensor.

**Comment by mohantym** [comment]
Hi @lmorton-zd! 1.x versions are not supported any more. Please create a new issue if it still persists in the 2.8 version. Thank you!
