### ISSUE TITLE
Bazel Build fails after updating

### ISSUE THREAD

**Issue by DavidBrayford** [tensorflow/tensorflow#17293]
After updating my local copy of TensorFlow from the github repository the Bazel build failed with the following error (see below). However, the same command successfully built version 1.5 of TensorFlow. 

OS: SLES12
Python version: 3.6
Bazel version: Build label: 0.7.0- (@non-git)
gcc version 7.2.0 (GCC)
No GPU
No CUDA

build command:
bazel build --config=mkl --copt="-DEIGEN_USE_VML" -s -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures

ERROR: /home/hpc/pr28fa/di72giz/TENSORFLOW/tensorflow/tensorflow/BUILD:399:12: Label '//tensorflow:tools/integration_tests/gcs_smoke_test/gcs_smoke.py' crosses boundary of subpackage 'tensorflow/tools/integration_tests/gcs_smoke_test' (perhaps you meant to put the colon here: '//tensorflow/tools/integration_tests/gcs_smoke_test:gcs_smoke.py'?).
ERROR: /home/hpc/pr28fa/di72giz/TENSORFLOW/tensorflow/tensorflow/BUILD:399:12: Label '//tensorflow:tools/integration_tests/gcs_smoke_test/setup.sh' crosses boundary of subpackage 'tensorflow/tools/integration_tests/gcs_smoke_test' (perhaps you meant to put the colon here: '//tensorflow/tools/integration_tests/gcs_smoke_test:setup.sh'?).
ERROR: /home/hpc/pr28fa/di72giz/TENSORFLOW/tensorflow/tensorflow/BUILD:399:12: Label '//tensorflow:tools/integration_tests/gcs_smoke_test/BUILD.bazel' crosses boundary of subpackage 'tensorflow/tools/integration_tests/gcs_smoke_test' (perhaps you meant to put the colon here: '//tensorflow/tools/integration_tests/gcs_smoke_test:BUILD.bazel'?).
ERROR: /home/hpc/pr28fa/di72giz/TENSORFLOW/tensorflow/tensorflow/BUILD:399:12: Label '//tensorflow:tools/integration_tests/gcs_smoke_test/teardown.sh' crosses boundary of subpackage 'tensorflow/tools/integration_tests/gcs_smoke_test' (perhaps you meant to put the colon here: '//tensorflow/tools/integration_tests/gcs_smoke_test:teardown.sh'?).
ERROR: /home/hpc/pr28fa/di72giz/TENSORFLOW/tensorflow/tensorflow/BUILD:399:12: Label '//tensorflow:tools/integration_tests/gcs_smoke_test/test_wrapper.sh' crosses boundary of subpackage 'tensorflow/tools/integration_tests/gcs_smoke_test' (perhaps you meant to put the colon here: '//tensorflow/tools/integration_tests/gcs_smoke_test:test_wrapper.sh'?).
ERROR: /home/hpc/pr28fa/di72giz/TENSORFLOW/tensorflow/tensorflow/tools/pip_package/BUILD:134:1: Target '//tensorflow:windows' contains an error and its package is in error and referenced by '//tensorflow/tools/pip_package:build_pip_package'.
ERROR: /home/hpc/pr28fa/di72giz/TENSORFLOW/tensorflow/tensorflow/tools/pip_package/BUILD:134:1: Target '//tensorflow:windows_msvc' contains an error and its package is in error and referenced by '//tensorflow/tools/pip_package:build_pip_package'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Loading failed.

**Comment by DerekKen** [comment]
I‘ve encountered the same problem.

OS: Windows 10, x64,
Bazel 0.5.4,
MSYS2, 
Python 2.7,
GPU-support enabled: CUDA 9.0 Toolkit, cuDNN 7.0,
Visual Studio 2017 community,

build command issued in MSYS2: 

`bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --copt=-march=native --config=mkl --config=win-cuda //tensorflow/tools/pip_package:build_pip_package`

**Comment by jbobba** [comment]
Can you try using a newer version of bazel (v0.11.0)?

**Comment by carlobertolli** [comment]
I had the same problem and it went away after updating to bazel 0.11.0

The configuration I had when I saw that error:

OS: Ubuntu 16.04.3 LTS
Python version: 2.7.12
Bazel version: Build label: 0.7.0- (@non-git)
gcc version 5.4.0 (GCC)
No GPU
No CUDA

The configuration that works is the same, except:

Bazel version: Build label: 0.11.0- (@non-git)

**Comment by berli** [comment]
I had the same problem
RROR: /media/berli/DataCenter/Test/tensorflow/tensorflow/BUILD:399:12: Label '//tensorflow:tools/integration_tests/gcs_smoke_test/gcs_smoke.py' crosses boundary of subpackage 'tensorflow/tools/integration_tests/gcs_smoke_test' (perhaps you meant to put the colon here: '//tensorflow/tools/integration_tests/gcs_smoke_test:gcs_smoke.py'?)
ERROR: /media/berli/DataCenter/Test/tensorflow/tensorflow/BUILD:399:12: Label '//tensorflow:tools/integration_tests/gcs_smoke_test/setup.sh' crosses boundary of subpackage 'tensorflow/tools/integration_tests/gcs_smoke_test' (perhaps you meant to put the colon here: '//tensorflow/tools/integration_tests/gcs_smoke_test:setup.sh'?)
ERROR: /media/berli/DataCenter/Test/tensorflow/tensorflow/BUILD:399:12: Label '//tensorflow:tools/integration_tests/gcs_smoke_test/BUILD.bazel' crosses boundary of subpackage 'tensorflow/tools/integration_tests/gcs_smoke_test' (perhaps you meant to put the colon here: '//tensorflow/tools/integration_tests/gcs_smoke_test:BUILD.bazel'?)
ERROR: /media/berli/DataCenter/Test/tensorflow/tensorflow/BUILD:399:12: Label '//tensorflow:tools/integration_tests/gcs_smoke_test/teardown.sh' crosses boundary of subpackage 'tensorflow/tools/integration_tests/gcs_smoke_test' (perhaps you meant to put the colon here: '//tensorflow/tools/integration_tests/gcs_smoke_test:teardown.sh'?)
ERROR: /media/berli/DataCenter/Test/tensorflow/tensorflow/BUILD:399:12: Label '//tensorflow:tools/integration_tests/gcs_smoke_test/test_wrapper.sh' crosses boundary of subpackage 'tensorflow/tools/integration_tests/gcs

**Comment by DavidBrayford** [comment]
After updating to bazel version 0.11 the errors went away and was able to successfully build TensorFlow.

**Comment by berli** [comment]
yes, updating to bazel version 0.11, the errors went away and build successfully

**Comment by JonnyHancox** [comment]
I had the same issue with version 0.11.0, having used the --user option at installation. Installing with sudo resolved the issue for me.

**Comment by dreamibor** [comment]
Great ! that solved my problem too, in any case that you cannot update through "sudo apt-get upgrade bazel", follow the installing instruction [here](https://docs.bazel.build/versions/master/install-ubuntu.html) again.

**Comment by tatianashp** [comment]
Great to see the problem solved.
