### ISSUE TITLE
FileWriter instance can not invoke close normally

### ISSUE THREAD

**Issue by Davidrjx** [tensorflow/tensorflow#17294]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
- **TensorFlow installed from (source or binary)**:
via pip3 for python3.5.3 
- **TensorFlow version (use command below)**:
v1.5.0-0-g37aa430d84 1.5.0
- **Python version**: 
3.5.3
- **Bazel version (if compiling from source)**: NO
- **GCC/Compiler version (if compiling from source)**: NO
- **CUDA/cuDNN version**: NO
- **GPU model and memory**: 256G RAM
- **Exact command to reproduce**:
python virtualenv and tensorboard

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

### Describe the problem
loggingMXNet summary data with tensorflow-tensorboard, but FileWriter close method can not execute successfully without any errors or warnings

### Source code / logs
in my case , without any extra info, but just i use minist dataset to training MXNet digits recongnition model and wrap tensorboard event writer into MXNet fit callback , by location, i found close method failed to exec.

IS there anyone faced with similar/same issue? if exists, please share your ideas.

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
