### ISSUE TITLE
Unable to restore trained models on the en-fr translate model:  tensorflow.python.framework.errors.NotFoundError: Tensor name "embedding_attention_seq2seq/RNN/MultiRNNCell/Cell2/GRUCell/Gates/Linear/Matrix" not found

### ISSUE THREAD

**Issue by viveksck** [tensorflow/tensorflow#173]
Hi, when I try the command:

Since ultimately I want to use a model similar to translate for POS tagging, I just copies translate.py to pos.py and trained a model.

``  /home/vvkulkarni/bazel/output/bazel run -- //tensorflow/models/rnn/translate:pos --data_dir /data/vivek/pos_tags/ --train_dir /data/vivek/pos_tags/models/ --decode 1 ``

I get the error:

``  File "/home/vvkulkarni/.cache/bazel/_bazel_vvkulkarni/4fc9a6787896f8b64890985f604431f2/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorfl
ow/models/rnn/translate/pos.runfiles/tensorflow/python/platform/default/_app.py", line 15, in run
    sys.exit(main(sys.argv))
  File "/home/vvkulkarni/.cache/bazel/_bazel_vvkulkarni/4fc9a6787896f8b64890985f604431f2/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorfl
ow/models/rnn/translate/pos.runfiles/tensorflow/models/rnn/translate/pos.py", line 262, in main
    decode()
  File "/home/vvkulkarni/.cache/bazel/_bazel_vvkulkarni/4fc9a6787896f8b64890985f604431f2/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorfl
ow/models/rnn/translate/pos.runfiles/tensorflow/models/rnn/translate/pos.py", line 196, in decode
    model = create_model(sess, True)
  File "/home/vvkulkarni/.cache/bazel/_bazel_vvkulkarni/4fc9a6787896f8b64890985f604431f2/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorfl
ow/models/rnn/translate/pos.runfiles/tensorflow/models/rnn/translate/pos.py", line 112, in create_model
    model.saver.restore(session, "/data/vivek/pos_tags/models/translate.ckpt-13450")
  File "/home/vvkulkarni/.cache/bazel/_bazel_vvkulkarni/4fc9a6787896f8b64890985f604431f2/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorfl
ow/models/rnn/translate/pos.runfiles/tensorflow/python/training/saver.py", line 867, in restore
    sess.run([self._restore_op_name], {self._filename_tensor_name: save_path})
  File "/home/vvkulkarni/.cache/bazel/_bazel_vvkulkarni/4fc9a6787896f8b64890985f604431f2/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorfl
ow/models/rnn/translate/pos.runfiles/tensorflow/python/client/session.py", line 349, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/home/vvkulkarni/.cache/bazel/_bazel_vvkulkarni/4fc9a6787896f8b64890985f604431f2/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorfl
ow/models/rnn/translate/pos.runfiles/tensorflow/python/client/session.py", line 423, in _do_run
    e.code)
tensorflow.python.framework.errors.NotFoundError: Tensor name "embedding_attention_seq2seq/RNN/MultiRNNCell/Cell2/GRUCell/Gates/Linear/Matrix" n
ot found in checkpoint files /data/vivek/pos_tags/models/translate.ckpt-13450
         [[Node: save/restore_slice_14 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_sa
ve/Const_0, save/restore_slice_14/tensor_name, save/restore_slice_14/shape_and_slice)]]
Caused by op u'save/restore_slice_14', defined at ``

**Comment by ebrevdo** [comment]
Can you upload the checkpoint file for inspection?

**Comment by viveksck** [comment]
Attaching the file. Because github does not allow attachments of certain filetypes, I had ro rename the file to .txt.

[translate.ckpt-12950.txt](https://github.com/tensorflow/tensorflow/files/33528/translate.ckpt-12950.txt)

**Comment by ebrevdo** [comment]
It is looking for:

embedding_attention_seq2seq/RNN/MultiRNNCell/Cell2/GRUCell/Gates/Linear/Matrix

but your checkpoint contains:

embedding_attention_seq2seq/RNN/MultiRNNCell/Cell0/GRUCell/Gates/Linear/Matrix
and
embedding_attention_seq2seq/RNN/MultiRNNCell/Cell1/GRUCell/Gates/Linear/Matrix

basically the graph you loaded from has 3 stacked RNNs (looking for Cell2) but the checkpoint file was created with a graph trained with only 2 stacked RNNs (it has Cell0 and Cell1).

**Comment by viveksck** [comment]
If it helps, this is the command used to train the model:
`` /home/vvkulkarni/bazel/output/bazel run -- //tensorflow/models/rnn/translate:pos --data_dir /data/vivek/pos_tags/ --train_dir /data/vivek/pos_tags/models_new/ --size=64 --num_layers=2 --steps_per_checkpoint=50 --fr_vocab_size 48 --batch_size 100``

and this is the command used to decode:
``/home/vvkulkarni/bazel/output/bazel run -- //tensorflow/models/rnn/translate:pos --data_dir /data/vivek/pos_tags/ --train_dir /data/vivek/pos_tags/models_new/ --decode 1 --fr_vocab_size 48``

**Comment by ebrevdo** [comment]
Try padding the flag "--num_layers=2" to the second call.  My guess is the default value is 3.

**Comment by viveksck** [comment]
I tried that, but that does not work. I get more errors: W tensorflow/core/common_runtime/executor.cc:1027] 0x8e51560 Compute status: Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1024] rhs shape= [64]


See below for details


INFO: Running command line: bazel-bin/tensorflow/models/rnn/translate/pos --data_dir /data/vivek/pos_tags/ --train_dir /data/vivek/pos_tags/models_new/ --decode 1 --fr_vocab_size 48 --num_layers 2

``I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 24
I tensorflow/core/common_runtime/direct_session.cc:45] Direct session inter op parallelism threads: 24
W tensorflow/core/common_runtime/executor.cc:1027] 0x8e51560 Compute status: Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1024] rhs shape= [64]
         [[Node: save/Assign_11 = Assign[T=DT_FLOAT, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/embedding_attention_decoder/attentio
n_decoder/Attention_0/Linear/Bias, save/restore_slice_11)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x8e51560 Compute status: Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,1024,1024] rhs shape= [1,1,64,64]
         [[Node: save/Assign_16 = Assign[T=DT_FLOAT, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/embedding_attention_decoder/attentio
n_decoder/AttnW_0, save/restore_slice_16)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x8e51560 Compute status: Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,1024] rhs shape= [128,64]
         [[Node: save/Assign_4 = Assign[T=DT_FLOAT, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/RNN/MultiRNNCell/Cell0/GRUCell/Candid
ate/Linear/Matrix, save/restore_slice_4)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x8e51560 Compute status: Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,1024] rhs shape= [128,64]
         [[Node: save/Assign_12 = Assign[T=DT_FLOAT, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/embedding_attention_decoder/attentio
n_decoder/Attention_0/Linear/Matrix, save/restore_slice_12)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x8e51560 Compute status: Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1024] rhs shape= [64]
         [[Node: save/Assign_23 = Assign[T=DT_FLOAT, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/embedding_attention_decoder/attentio
n_decoder/MultiRNNCell/Cell1/GRUCell/Candidate/Linear/Bias, save/restore_slice_23)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x8e51560 Compute status: Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1024] rhs shape= [64]
         [[Node: save/Assign_15 = Assign[T=DT_FLOAT, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/embedding_attention_decoder/attentio
n_decoder/AttnV_0, save/restore_slice_15)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x8e51560 Compute status: Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048] rhs shape= [128]
         [[Node: save/Assign_25 = Assign[T=DT_FLOAT, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/embedding_attention_decoder/attentio
n_decoder/MultiRNNCell/Cell1/GRUCell/Gates/Linear/Bias, save/restore_slice_25)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x8e51560 Compute status: Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,1024] rhs shape= [128,64]
         [[Node: save/Assign_18 = Assign[T=DT_FLOAT, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/embedding_attention_decoder/attentio
n_decoder/Linear/Matrix, save/restore_slice_18)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x8e51560 Compute status: Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [2048,2048] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/embedding_attention_decoder/attentio
n_decoder/MultiRNNCell/Cell0/GRUCell/Gates/Linear/Matrix, save/restore_slice_22)]]``

**Comment by ebrevdo** [comment]
When you run decoding, you basically have to have the same parameters as when you trained.  For example, you forgot to add --size=64 to the second command, and the number 64 is one of the incompatible dimensions.  I bet if you look at the code, you'll see that the default value for size is 1024.

**Comment by viveksck** [comment]
Yup :) Thanks that seems to work, although it seems counter-intuitive to me, that I need to restate all the parameters I used when I train the model. Ideally it should have picked up the parameters from the serialized model. 

Pasting what worked, so that others who may have hit the isseue may benefit,

 /home/vvkulkarni/bazel/output/bazel run -- //tensorflow/models/rnn/translate:pos --data_dir /data/vivek/pos_tags/ --train_dir /data/vivek/pos_tags/models_new/ --decode 1 --fr_vocab_size 48 --num_layers 2 --size 64

**Comment by vrv** [comment]
A program *could* try to pick up the parameters from the serialized model -- but for the tutorial we'll keep it as is for now.  Please re-open if there are any other issues here!

**Comment by srp1970** [comment]
Yes, I had the same problem, and when I gave the same params like "--size=256 --num_layers=2" while decode too, it worked. I think defaults are different during decode.

**Comment by ymakkapa** [comment]
Hello everyone,
I executed the code translate.py from sequence to sequence models tutorial of tensorflow for 20 hours 
![seqgoo](https://cloud.githubusercontent.com/assets/20130992/23177149/ca80dc96-f833-11e6-99c7-61b2150c7261.png)
and still waiting for the output.
Can anyone tell me how much more time will it take to display the output
System specifications:
I installed Ubuntu 16.04 on VMware with a disk space of 100
