### ISSUE TITLE
CudnnRNN TensorCore Support

### ISSUE THREAD

**Issue by samgd** [tensorflow/tensorflow#17306]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: N/A
- **Python version**: N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.1/7.0
- **GPU model and memory**: V100
- **Exact command to reproduce**: N/A

### Describe the problem

Feature/Status Request: Enable use of NVIDIA's TensorCores in CudnnRNN, CudnnLSTM. The requirements specified by NVIDIA are currently detailed at [1].

[1] http://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#tensor_ops

**Comment by yzhwang** [comment]
@protoget Do you have any timeline for adding TensorCore support for CudnnRNN?

**Comment by protoget** [comment]
The support for CudnnRNN is on our roadmap. We don't yet have a delivery date, but it's one of the high priority things we will do next.

**Comment by samgd** [comment]
@protoget What does `high priority` usually mean? i.e. week, weeks, months? I'll need to switch to another library if it's more the latter than the former :-(

**Comment by protoget** [comment]
It's now supported in TF. You should be able to use from the nightly build. 
Although we're trying to add more autotune logic s.t. TF would automatically choose between regular RNN and persistent RNN based on history. But without that you should still be able to use tensor_op.
