### ISSUE TITLE
ABI for `tensorflow::core::RefCounted` is error-prone

### ISSUE THREAD

**Issue by mrry** [tensorflow/tensorflow#17316]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: tf-nightly
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: (see above)

### Describe the problem

For performance, the implementation of `RefCounted` comprises a set of inline methods. Furthermore, it contains a cunning optimization that avoids updating the refcount when the caller to `Unref()` is the only owner:

https://github.com/tensorflow/tensorflow/blob/3ba1f72f8829c566372208062fcea04ab5695dc6/tensorflow/core/lib/core/refcount.h#L88-L89

It also includes some `DCHECK` macros to ensure that various invariants hold:

https://github.com/tensorflow/tensorflow/blob/3ba1f72f8829c566372208062fcea04ab5695dc6/tensorflow/core/lib/core/refcount.h#L79

https://github.com/tensorflow/tensorflow/blob/3ba1f72f8829c566372208062fcea04ab5695dc6/tensorflow/core/lib/core/refcount.h#L90-L92

Note that that second `DCHECK` performs a side-effect to make the first one succeed. 

The release build is built with `NDEBUG` defined, so the `DCHECK` code doesn't execute. However, the default flags you get when following the [Adding an New Op](https://www.tensorflow.org/versions/r1.6/extend/adding_an_op) tutorial to build an extension do not include `-DNDEBUG`. 

Recall that the methods are marked `inline`.  This means that some code in the release binary might call (an inlined version of) `Unref()` and the store to `ref_` will be elided, but some code in an extension (e.g. one that creates a custom `ResourceBase`, which inherits from `RefCounted`) might call `~RefCounted()` and the `DCHECK` will be performed, leading to a failure.

The workaround is to add `-DNDEBUG` to the compiler flags when adding a new op. Should we update the documentation, update the `tf.sysconfig.get_compile_flags()` implementation, or modify how `RefCounted` is implemented to avoid this problem altogether?

**Comment by angersson** [comment]
@josh11b Any thoughts on this?

**Comment by josh11b** [comment]
I think updating the documentation and tf.sysconfig.get_compile_flags() would be a quick fix that we should do. Not sure how performance critical the optimization is, measuring that would be the main effort behind really solving this problem.

**Comment by pavanky** [comment]
@mrry thanks for helping out with this!

**Comment by TimZaman** [comment]
Oh wow this was a subtle and nasty bug for me, thanks for the excellent bugreport.

**Comment by byshiue** [comment]
Hi, I encounter a similar problem in TF 1.15. 
I want to write a custom op and need to use the `mutable_input()`, but get the core dumped because "Check failed: input_is_ref(index)".

After tracing the source code, I find that the developer used `CHECK` in  [source code,](https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/core/framework/op_kernel.cc#L407) of TF 1.15 but not `DCHECK` in [source code](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/core/framework/op_kernel.cc#L410) of TF 1.14.

And the `CHECK` is not controlled by the `DNDEBUG` flag. 
Do you have any suggestion to handle this problem?

**Comment by kevint324** [comment]
such a nasty bug lived for 3 years and people are still struggling to workaround it.

**Comment by kumariko** [comment]
@mrry We are checking to see if you still need help on this issue. I can see [**`PR`**](https://github.com/capeprivacy/tf-trusted/pull/27) is merged . We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. Thanks!
