### ISSUE TITLE
Feature Request: Training on device

### ISSUE THREAD

**Issue by senthilki** [tensorflow/tensorflow#17328]
Hi Tensorflow,

I would like to know whether Tensorflow does support on-device training i.e creation of model on Android device. Right now Tensorflow provides Python script to generate model in the Native system and only inference we can execute on Android device. Obviously i cannot execute the Python to create the model in Android, does Tensorflow provides any Example/Feature in C++ to train the model on-device (Android)  ? 

Feature Request 

1. A Standalone C++ Application which can be cross compiled for Android to train the model from dataset. 

2. Training the model might be time consuming process if done on Android, but at least some minimal support for smaller data set would be helpful.

Regards,
Senthil

**Comment by angersson** [comment]
@aselle This seems TF Lite related, can you take a look?

**Comment by rajatmonga** [comment]
[TensorFlow mobile](https://www.tensorflow.org/mobile/mobile_intro) runs on Android and iOS and does support training as well. One way you could do this is to create the model using the Python libraries and then load and train it on Android, using the C++ APIs.

Here's [a blog](https://tebesu.github.io/posts/Training-a-TensorFlow-graph-in-C++-API) that does something similar (although not on mobile). 

In the future [TensorFlow Lite](https://www.tensorflow.org/mobile/tflite/) will also support training.

**Comment by milinddeore** [comment]
@rajatmonga Thanks for the inputs!
But, tensorflow still needs to be cross compiled for that device before being used. In case of Android, the libtensroflow_inference.so is just the inference only library, whereas for training we would need the complete library. Is there a ready build to cross compile tensorflow using NDK toolchain for complete library?

**Comment by saudet** [comment]
@milinddeore The builds with JavaCPP contain pretty much all that we can get working on Android. It's not the inference-only and/or lite version or anything:
https://github.com/bytedeco/javacpp-presets/tree/master/tensorflow
http://bytedeco.org/builds/
Please let me know if there's anything missing though!

**Comment by rajatmonga** [comment]
Adding @aselle and @petewarden who may have more pointers for building TensorFlow for Android for training your model.

**Comment by beniroquai** [comment]
Is there anybody who tried that on Android? I've seen this piece: https://tebesu.github.io/posts/Training-a-TensorFlow-graph-in-C++-API and here https://github.com/chelexa/tensorflow-on-android 

Is Androids Tensorflow Lite capable to do the training job and if so how? 

Help much appreciated!

**Comment by Aralox** [comment]
The tensorflow mobile link just redirects to tensorflow lite now, and it seems impossible to actually find any official page for tensorflow mobile anymore. This and the tf lite roadmap are the only places where training on device is mentioned. What gives? Where can we track work on this? Why is this issue closed, is there an equivalent tf lite issue?

**Comment by MHX792** [comment]
Is training on device already possible (iOS)?

**Comment by SunitRoy2703** [comment]
TensorFlow Lite now supports training your models on-device, in addition to running inference. On-device training enables interesting personalization use cases where models can be fine-tuned based on user needs

Check this: https://blog.tensorflow.org/2021/11/on-device-training-in-tensorflow-lite.html
