### ISSUE TITLE
Could some ops(assert,switch...) be removed in inference model ?

### ISSUE THREAD

**Issue by fengwuxuan** [tensorflow/tensorflow#17340]
I want to convert faster-rcnn model to tensorRT, but these ops can't be converted,because invalid dtype or non data value, so I want to know how to solve the question.

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
