### ISSUE TITLE
can't use all the CPU cores

### ISSUE THREAD

**Issue by fastalgo** [tensorflow/tensorflow#17342]
I'm running the [ptb](https://github.com/petewarden/tensorflow_makefile/blob/master/tensorflow/models/rnn/ptb/ptb_word_lm.py) example on my 48-core Intel Skylake CPUs (two sockets).

However, I found only 10 of the 48 cores are being used (I used the 'top' command). I want to use all the cores.

I tried the following setting, but it did not work

config_proto = tf.ConfigProto(allow_soft_placement=soft_placement, inter_op_parallelism_threads=4, intra_op_parallelism_threads=12)

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux 3.10.0-693.17.1.el7.x86_64 #1 SMP
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.5.0
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
5.4.0
- **CUDA/cuDNN version**:
Did not use GPU
- **GPU model and memory**:
Did not use GPU
- **Exact command to reproduce**:

**Comment by yaroslavvb** [comment]
Using more cores can decrease performance. It's not clear that ptb_word_lm.py example can make use of 48 cores

**Comment by angersson** [comment]
Thanks for the input, @yaroslavvb!

This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
