### ISSUE TITLE
Does the size of embedding have a huge influence on the training speed?

### ISSUE THREAD

**Issue by yananchen1989** [tensorflow/tensorflow#17344]
In my text classification task, I use vectors to represent the words. After I enlarge the size of vocabulary (word dimension is still 128), from 200000 to 1000000, the training step time arise from 0.1s to 0.4s. Here is the word embedding tensor creatation:

`tf.get_variable('embedding', shape, dtype=dtype, return tf.get_variable('embedding', shape, dtype=dtype, initializer=tf.random_normal_initializer(stddev=0.1), trainable=True)`

And the sentences are made of word ids and vectors will be looked up from the embedding tensor above.

`inputs_embedding = tf.contrib.layers.embedding_lookup_unique(embedding, inputs)`

So what confused me is that why the size of vocabulary has a significant impact on the training speed. Is that normal ?

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
