### ISSUE TITLE
Throw Exception instead of Crash when out of BFC memory allocation

### ISSUE THREAD

**Issue by ghostplant** [tensorflow/tensorflow#17354]
For huge application model, the memory is easy to overflow and the framework will quit after plenty of Out-of-memory logs. Is it possible to just quickly throw an Exception in python runtime instead of killing the whole program?

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ghostplant** [comment]
@angersson Hi. This is a bug of Tensorflow, not a question.

**Comment by ghostplant** [comment]
Can you reopen this issue?

**Comment by ghostplant** [comment]
Currently Tensorflow did a force quit when OOM which is not catchable by python runtime.

**Comment by angersson** [comment]
If you believe you've found a bug, file another issue that clearly indicates the problem and includes replicate-able code and the other required information from [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
