### ISSUE TITLE
[Suggestion]SVD GPU Op is not efficient than CPU.

### ISSUE THREAD

**Issue by sseung0703** [tensorflow/tensorflow#17352]
when I used TF 1.2 version, there is no problem with using SVD

but few days ago i updated my tensorflow version to 1.5 and my code get extremely slow.

so I tested all possibility and  checked issues

finally i found that someone commited SVD GPU op made by cudasolver. in june, 2017

he said that it contain memcopy and it cause bottleneck. it is true and it make svd GPU op extremely slow than former version.

so please remove that op. and if possible, please make proper SVD GPU op  and gradients, and solve problem that tf.svd return nan value.

i uploaded my naive solution to avoid nan value problem and code for compute svd's gradients.

https://github.com/InhaDeeplearningGroup/Academic_research/blob/master/LSH/tensorflow_slim/svdGradients.py

### System information
- Linux Ubuntu 16.04
- install by binary
- TF version : i tested in 1.2, 1.3, 1.4,1.5 
- python3.5
- CUDA : i tested in 7.5, 8.0, 9.0
- GPU : gtx1070

**Comment by angersson** [comment]
@rmlarsen  Can you comment on this?

**Comment by yaroslavvb** [comment]
It's a known issue. Doing SVD in numpy can be 20x faster than in TensorFlow
https://github.com/tensorflow/tensorflow/issues/13222#issuecomment-331642490

Similar with matrix inverses, it's faster to do it in numpy and feed the results back into tf using `feed_dict`

**Comment by yaroslavvb** [comment]
cc @shamanDevel

**Comment by sseung0703** [comment]
@yaroslavvb yes it's a known issue. so why still have to maintain this inefficient op. i think former version is better than this. i didn't check time but i think at least it is similar with numpy.

**Comment by yaroslavvb** [comment]
@sseung0703 they are both available, by default GPU is used if `tf.testing.is_gpu_available()`, but you can force CPU version by using `with tf.device('cpu:0'):` block. 

I agree that it's a regression, defaulting to such slow kernel for SVD gives another way for newcomers to shoot themselves in the foot.

**Comment by sseung0703** [comment]
@yaroslavvb it is not good solution. it still has bottleneck cause of communication, but former version is not.
test it in TF 1.2 and later version. tf.svd in TF 1.2 is much faster than later version. 
maybe i can change it by installing source. but you know "defaulting to such slow kernel for SVD gives another way for newcomers to shoot themselves in the foot".

**Comment by yaroslavvb** [comment]
@sseung0703 tf 1.2 didn't have GPU version of SVD, so it would have communication bottleneck as well.

**Comment by sseung0703** [comment]
@yaroslavvb oh, i didn't know that if there is no gpu op, it forcely use cpu.
Ok, so i use your way until tf.svd's gpu op work properly.
but i still don't know why TF maintain this op.

**Comment by angersson** [comment]
This issue seems to have been resolved, and has not had any extra discussion, so I'm closing it to keep the issue tracker focused.
