### ISSUE TITLE
Feature request: Make div operator that sets 0/0=0 instead of 0/0=NaN

### ISSUE THREAD

**Issue by aforslow** [tensorflow/tensorflow#17350]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
Yes, code provided below
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10 Pro, Version 1709
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
1.5.0
- **Python version**: 
3.6.4
- **Bazel version (if compiling from source)**:
&mdash;
- **GCC/Compiler version (if compiling from source)**:
&mdash;
- **CUDA/cuDNN version**:
Using processor, not GPU
- **GPU model and memory**:
Using processor, not GPU
- **Exact command to reproduce**:
Run code provided below

### Describe the problem
When I divide 0/0 elements in TensorFlow, I get 0/0=NaN values. However, I want a division operator that returns 0/0=0 for these elements. Currently, I am using a workaround for this with a where operator, as can be seen in the d variable below. However, this decreases readability, is tedious when writing code with many div operators, and is probably less efficient than coding this functionality into source.

### Source code / logs
```
import tensorflow as tf

a = tf.constant([0], dtype=tf.float32)
b = tf.constant([0], dtype=tf.float32)
c = tf.divide(a, b)
d = tf.where(tf.less(a, 1e-7), a, a/b)

with tf.Session() as sess:
    print(sess.run(c))
    print(sess.run(e))
```

**Comment by angersson** [comment]
@mrry Any thoughts on this?

**Comment by facaiy** [comment]
Yes, I agree that it is a problem indeed, and I proposed to add safe_div op in  #15706.

**Comment by mrry** [comment]
I have no objections, but I am not responsible for the math library, so we'd want to find another reviewer. Tentatively marking as "Contributions welcome" for now.

**Comment by RBerkheimer** [comment]
This is fundamentally false and shouldn't be added as a default. if this is a needed addition, there needs to be a config flag, cl flag, threshold for floats, or some other qualification. This is a breaking change. If truly necessary add a new operator or have the user implement a user function.
