### ISSUE TITLE
Interleaving multiple datasets together

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/tensorflow#17364]
@mrry The current interleave functionality is basically a interleaved flat-map taking as input a single dataset. Given the current API, what's the best way to interleave multiple datasets together? Say they have already been constructed and I have a list of them. I want to produce elements from them alternatively and I want to support lists with more than 2 datasets (i.e., stacked zips and interleaves would be pretty ugly).

Thanks! :)

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by eaplatanios** [comment]
I posted a question [here](https://stackoverflow.com/questions/49058913/interleaving-multiple-tensorflow-datasets-together) but I'm not sure how to mention @mrry there.

**Comment by FishermanZzhang** [comment]
```python
  # Preprocess 4 files concurrently.
  filenames = tf.data.Dataset.list_files("/path/to/data/train*.tfrecords")
  dataset = filenames.apply(
      tf.contrib.data.parallel_interleave(
          lambda filename: tf.data.TFRecordDataset(filename),
          cycle_length=4))
  ```
[parallel_interleave](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/data/python/ops/interleave_ops.py#L35)
[read_dataset](https://github.com/tensorflow/models/blob/master/research/object_detection/utils/dataset_util.py#L106)
