### ISSUE TITLE
Missing documentation for tf.train.Saver 

### ISSUE THREAD

**Issue by dreamflasher** [tensorflow/tensorflow#17362]
The documentation for tf.train.Saver (https://www.tensorflow.org/api_docs/python/tf/train/Saver) is not explaining how to actually use the saver. The crucial missing part:
* `saver = tf.train.Saver()` needs to be executed right before finalizing the graph

**Comment by lamberta** [comment]
Hi Marcel, can you clarify, please?

The code snippet on that page looks like:
```
...
# Create a saver.
saver = tf.train.Saver(...variables...)
# Launch the graph and train, saving the model every 1,000 steps.
sess = tf.Session()
for step in xrange(1000000):
    sess.run(..training_op..)
    if step % 1000 == 0:
        # Append the step number to the checkpoint name:
        saver.save(sess, 'my-model', global_step=step)
```

There's also the [Save and Restore guide](https://www.tensorflow.org/programmers_guide/saved_model#save_variables).

**Comment by DreamFlasher** [comment]
Code is not a replacement for documentation ;) It would be good to have a) a fully functional example, b) a textual description of what's structurally happening. Especially what I mentioned above, what you need to execute in which order.

**Comment by amishra791** [comment]
I'll work on updating the documentation.

**Comment by Ayush517** [comment]
@dreamflasher Is this what you were looking for? https://www.tensorflow.org/api_docs/python/tf/train/Saver

**Comment by dreamflasher** [comment]
@Ayush517 That's perfect! Thanks for adding the example.
