### ISSUE TITLE
C++ api: use of op::Attrs methods in gradients

### ISSUE THREAD

**Issue by kbsriram** [tensorflow/tensorflow#17360]
The generated op::Attrs struct returns new instances on its chainable methods, and doesn't change the original object.

https://github.com/tensorflow/tensorflow/blob/d7d7f4eea5f3a2e63e12c803d02f56726c0e0513/tensorflow/cc/framework/cc_op_gen.cc#L701

There are a few related issues e.g. https://github.com/tensorflow/tensorflow/blob/6fdb9ad1baf7686a75f9e660178f7ac595e7fc2e/tensorflow/cc/gradients/nn_grad.cc#L164 where the code assumes the underlying object is being mutated and the parameters don't actually pass through.

I guess there might be a couple of ways forward, depending on how Tensorflow prefers the C++ API:

1. Decide the Attrs chaining methods mutate the underlying object and fix the code generation.
2. Decide the Attrs chaining methods return new instances, and fix the uses.

Suggestions?

Fwiw if option 2, it might be nice to add TF_MUST_USE_RESULT to the generated API. (Unfortunately a [long-standing bug in gcc](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=38172) means this may be unreliable as an actual error across versions of gcc that contributors may use.)

/cc @suharshs @keveman

**Comment by keveman** [comment]
@kbsriram thanks for pointing out the bug. I am not a fan of mutable state, so my natural inclination is towards option 2. Adding `TF_MUST_USE_RESULT` to the generated API would simply point out the existing erroneous uses as compiler errors.

**Comment by kbsriram** [comment]
@keveman thanks for the note! Sgtm - don't have a strong opinion on this. But would like to make progress on fixes and (for option 2 as you note) add a bit of a compile-time safety net for new code.

Tentatively predicated on option 2, suggestions on next steps? If someone is already on it, awesome - otherwise, I can sign up for a pull request on this.
