### ISSUE TITLE
Potential resource leaks caused by unclear Java examples

### ISSUE THREAD

**Issue by mixalturek** [tensorflow/tensorflow#17374]
### System information

Java examples at https://www.tensorflow.org/ for tensorflow 1.6.0.

### Describe the problem

`org.tensorflow.Session.Runner.run()` returns list of closables, Javadoc clearly states that the caller is responsible to free all of them. None of the Java examples I found at https://www.tensorflow.org/ highlights that, I realized it by happy accident during in-depth reading implementation in Session.java quite long time after I wrote my code that uses TensorFlow.

```
    /**
     * Execute the graph fragments necessary to compute all requested fetches.
     *
     * <p><b>WARNING:</b> The caller assumes ownership of all returned {@link Tensor}s, i.e., the
     * caller must call {@link Tensor#close()} on all elements of the returned list to free up
     * resources.
     *
     * ...
     */
    public List<Tensor<?>> run() {
      return runHelper(false).outputs;
    }
```

I'm not sure if the examples them-self contain any resource leak or not, they free only the first element of the list, but there may be more of them (in general). I would expect an explicit loop properly freeing all the returned resources there.

Such examples for beginners should be as explicit as possible, 100% clear and understandable for anyone. A lot of people (like me) base core of their code on them which may easily introduce significant resource leak bugs to their applications.

- https://www.tensorflow.org/install/install_java, HelloTF example
- https://www.tensorflow.org/install/install_java, referenced advanced example LabelImage
- https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/java/src/main/java/org/tensorflow/examples/LabelImage.java

### Source code / logs

None.

**Comment by angersson** [comment]
@asimshankar Can you take a look at this?

**Comment by asimshankar** [comment]
@mixalturek : Thanks for the note and yes we'd like to make documentation and examples as clear as possible.

The examples referenced only fetch a single tensor, hence the list returned necessarily has a single element (and since that is referenced in the try-with-resources blocks, there is no leak). When the example is explicitly requesting a single tensor, the loop seems unnecessary.

Happy to hear any suggestions for improvement though.

**Comment by mixalturek** [comment]
Yes, I guessed there is only a single one so the code is correct. So what about to add a comment with an explicit info.

```
      // Execute the "MyConst" operation in a Session.
      try (Session s = new Session(g);
           // Generally, there may be multiple output tensors, all of them must be closed to prevent resource leaks.
           Tensor output = s.runner().fetch("MyConst").run().get(0)) {
        System.out.println(new String(output.bytesValue(), "UTF-8"));
      }
```

**Comment by asimshankar** [comment]
Sure. A PR would be welcome :)

**Comment by MarkDaoust** [comment]
The fix PR is merged, so I think we can close this.
