### ISSUE TITLE
Inconsistent OMPI_SKIP_MPICXX define

### ISSUE THREAD

**Issue by llchan** [tensorflow/tensorflow#17388]
Looks like we `#define OMPI_SKIP_MPICXX` before `#include third_party/mpi/mpi.h` in two places:

https://github.com/tensorflow/tensorflow/blob/b79ce0029dce3264266ced739590bc238b17096c/tensorflow/contrib/mpi_collectives/kernels/ring.h#L32-L34
https://github.com/tensorflow/tensorflow/blob/b79ce0029dce3264266ced739590bc238b17096c/tensorflow/contrib/mpi_collectives/kernels/mpi_ops.cc#L36-L37

But it is not defined here:
https://github.com/tensorflow/tensorflow/blob/b79ce0029dce3264266ced739590bc238b17096c/tensorflow/contrib/mpi/mpi_utils.h#L27

Because the first two are defined without an `#ifndef`, I can't define it in a compiler flag. We should probably add it to the last one, or at least make the first two no-ops if it's already set.

**Comment by angersson** [comment]
This seems like a pretty small / low-impact change, so I'll mark it as contributions welcome. Please feel free to prepare a PR.

**Comment by yongtang** [comment]
Added a PR #17414 for the fix.
