### ISSUE TITLE
https://www.tensorflow.org/versions/r1.6/ Dead link on versions page

### ISSUE THREAD

**Issue by Mandrewoid** [tensorflow/tensorflow#17382]
On https://www.tensorflow.org/versions, there's a link to 
https://www.tensorflow.org/versions/r1.6/
This link is 404

**Comment by angersson** [comment]
@wolffg Can you look at this?

**Comment by angersson** [comment]
Also @gunan, just in case.

**Comment by MarkDaoust** [comment]
FIxed: https://www.tensorflow.org/versions/
