### ISSUE TITLE
Documentation links for version 1.5 silently redirect to 1.6

### ISSUE THREAD

**Issue by recolgan** [tensorflow/tensorflow#17389]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.5
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: NVIDIA Titan X
- **Exact command to reproduce**: Go to https://www.tensorflow.org/versions/r1.5/api_docs/python

### Describe the problem
The Python and C++ API Documentation links at https://www.tensorflow.org/versions/r1.5/api_docs/ silently redirect you to documentation for version 1.6. The links are (I assume) correct, but the URLs https://www.tensorflow.org/versions/r1.5/api_docs/python and https://www.tensorflow.org/versions/r1.5/api_docs/cc redirect to https://www.tensorflow.org/api_docs/python/ and https://www.tensorflow.org/api_docs/cc/ respectively.

I spent a while trying to diagnose a problem based on the documentation for 1.6, without realizing I was looking at 1.6 rather than 1.5. Turns out the problem was caused by an API change between 1.5 and 1.6. 

### Source code / logs
N/A

**Comment by MarkDaoust** [comment]
Thanks for the report, this is fixed now.
