### ISSUE TITLE
Tensorflow 1.6.0 cpu fails on import on Windows 10

### ISSUE THREAD

**Issue by epivbg** [tensorflow/tensorflow#17386]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, problem appears on import (import tensorflow as tf).
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 x64
- **TensorFlow installed from (source or binary)**: binary (pip --no-cache-dir) install --upgrade tensorflow
- **TensorFlow version (use command below)**: 1.6.0 (install says tensorflow-1.6.0-cp36-cp36m-win_amd64.whl)
- **Python version**: 3.6.4 x64
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: import tensorflow as tf

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
When installing tensorflow 1.6.0 the import reports problems. See log below. Tried uninstalled r1.6 and reinstalled 1.5.0 to see if something else might be the problem. 1.5.0 works like a charm. Tried a clean install of 1.6.0 without any luck.

Ran the 'tensorflow_self_check.py' script. See log below.

### Source code / logs

```
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.



------------------------

When running 'tensorflow_self_check.py' this is what is reported. Supposed to have installed the CPU version so cuda is not installed.

ERROR: Failed to import the TensorFlow module.

- Python version is 3.6.

- TensorFlow is installed at: C:\Users\Jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow

- Could not load 'cudart64_80.dll'. The GPU version of TensorFlow
  requires that this DLL be installed in a directory that is named in
  your %PATH% environment variable. Download and install CUDA 8.0 from
  this URL: https://developer.nvidia.com/cuda-toolkit

- Could not load 'cudnn64_5.dll'. The GPU version of TensorFlow
  requires that this DLL be installed in a directory that is named in
  your %PATH% environment variable. Note that installing cuDNN is a
  separate step from installing CUDA, and it is often found in a
  different directory from the CUDA DLLs. You may install the
  necessary DLL by downloading cuDNN 5.1 from this URL:
  https://developer.nvidia.com/cudnn

- Could not find cuDNN.
```

**Comment by angersson** [comment]
@gunan Can you take a look at this?

**Comment by gunan** [comment]
This is interesting. Could you retry installing with "--ignore_installed" plus everything you had, just in case.

**Comment by bradezard131** [comment]
I also have this problem, exact same errors and outputs (except obviously my username instead of OPs). Installing with --ignore-installed doesn't change anything

**Comment by epivbg** [comment]
No positive result on installing with --ignore-installed.

**Comment by fo40225** [comment]
The CPU lack AVX instruction can cause this error.

I have built tensorflow wheel without AVX.

https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.6.0/py36/CPU/sse2

I wish this .whl may help you.

**Comment by gunan** [comment]
@mrry any ideas?
CPU incompatibility makes sense to me.
@epivbg @bradezard131 what is the CPU make/model on your machine?

**Comment by bradezard131** [comment]
AMD Phenom II x4 955BE for me, which does indeed lack AVX support. These unlisted requirements (AVX support, VC++2015, etc.) are rather frustrating...

@fo40225's wheel does fix the issue though!

**Comment by epivbg** [comment]
CPU Identification utility v2.14                 (c) 1997-2017 Jan Steunebrink
 ------------------------------------------------------------------------------
 CPU Vendor and Model: Intel Core i5 Dual M i5-430M/520E/520M/540M C2-step
 Internal CPU speed  : 2260.9 MHz
 System CPU count    : 1 Physical CPU(s), 2 Core(s) per CPU, 4 Thread(s)
 CPU-ID Vendor string: GenuineIntel
 CPU-ID Name string  : Intel(R) Core(TM) i5 CPU       M 430  @ 2.27GHz
 CPU-ID Signature    : 020652
 CPU Features        : Floating-Point Unit on chip  : Yes
                       Time Stamp Counter           : Yes
                       Enhanced SpeedStep Technology: Yes
                       Hyper-Threading Technology   : Yes
                       Execute Disable protection   : Yes
                       64-bit support               : Yes
                       Virtualization Technology    : Yes
 Instr set extensions: MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2
 Size of L1 cache    : 2 x 64 KB
 Integrated L2 cache : 2 x 256 KB
 Integrated L3 cache : 3072 KB

**Comment by epivbg** [comment]
So I guess it's about the AVX support.

Thanks @fo40225.

**Comment by andre-schmidt-42** [comment]
@fo40225's wheel does fix the issue for me too. Many thanks!

I fully agree with  bradezard131: Why arent these requirements listed on the official project website?

CPU Identification utility v2.14                 (c) 1997-2017 Jan Steunebrink
 ------------------------------------------------------------------------------
 CPU Vendor and Model: Intel -Unknown model-
 Internal CPU speed  : 1439.9 MHz
 System CPU count    : 1 Physical CPU(s), 4 Core(s) per CPU, 4 Thread(s)
 CPU-ID Vendor string: GenuineIntel
 CPU-ID Name string  : Intel(R) Atom(TM) x5-Z8550  CPU @ 1.44GHz
 CPU-ID Signature    : 0406C4
 CPU Features        : Floating-Point Unit on chip  : Yes
                       Time Stamp Counter           : Yes
                       Enhanced SpeedStep Technology: Yes
                       Hyper-Threading Technology   : No
                       Execute Disable protection   : Yes
                       64-bit support               : Yes
                       Virtualization Technology    : Yes
 Instr set extensions: MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2,
                       AES
 Size of L1 cache    : 4 x 56 KB
 Integrated L2 cache : 4 x 1024 KB
 Integrated L3 cache : None

**Comment by funkysandman** [comment]
I am having this issue too on Windows 10.  No luck installing the CPU-only version on 2 different laptops.  No clue as to what requirements I'm missing.  I've tried Python 3.5 and 3.6.  I have the VC runtime

 **CPU Identification utility v2.14                 (c) 1997-2017 Jan Steunebrink**
 ------------------------------------------------------------------------------
 CPU Vendor and Model: Intel Core i7 Quad i7-860S/860/870S/870/875K/880 B1-step
 Internal CPU speed  : 1728.9 MHz
 System CPU count    : 1 Physical CPU(s), 4 Core(s) per CPU, 8 Thread(s)
 CPU-ID Vendor string: GenuineIntel
 CPU-ID Name string  : Intel(R) Core(TM) i7 CPU       Q 740  @ 1.73GHz
 CPU-ID Signature    : 0106E5
 CPU Features        : Floating-Point Unit on chip  : Yes
                       Time Stamp Counter           : Yes
                       Enhanced SpeedStep Technology: Yes
                       Hyper-Threading Technology   : Yes
                       Execute Disable protection   : Yes
                       64-bit support               : Yes
                       Virtualization Technology    : Yes
 Instr set extensions: MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2
 Size of L1 cache    : 4 x 64 KB
 Integrated L2 cache : 4 x 256 KB
 Integrated L3 cache : 6144 KB

**Comment by MrEmanuel** [comment]
The .whl file provided by @fo40225 solved this issue for me. 

OS Name	Microsoft Windows 10 Pro
Processor	Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 4 Logical Processor(s)
System Type	x64-based PC

**Comment by funkysandman** [comment]
I've tried installing that whl a couple of times with no luck - ( I'm a python newbie just trying to do the hello  world tensorflow example).  I'm using the --ignore-installed flag.  I will uninstall it and try again, give it few more goes and post the results

**Comment by funkysandman** [comment]
ok, success!  I uninstalled and re-installed the .whl by @fo40225  using the --upgrade flag and it worked!  Thanks

**Comment by shawon100** [comment]
Thanks a lot  @fo40225 . Fixed it

**Comment by MilkTeaD** [comment]
and yet another guy reported this **UNDOCUMENTED** problem
And the whl-solution doe snot work : is not a supported wheel on this platform

**Comment by cpfy** [comment]
Thanks to @fo40225 !

**Comment by Freakysoft13** [comment]
downgraded tensorflow to version 1.4 and everything works like a charm)

**Comment by rosariosanto** [comment]
I have the same issue with version 1.6. Downgrading to version 1.4 fixed the problem. I'm using the CPU version only.

**Comment by rameshvarun** [comment]
Had the same issue using the CPU version while testing on an older computer - downgrading to 1.4 worked for me. This should probably fixed or at least the error message could be improved.

**Comment by hasantanvir79** [comment]
.whl fixed the issue finally! Thanks a lot @fo40225

**Comment by norderk** [comment]
@fo40225 !
Thank you so much! I have been trying to figure out this for a couple of days now. Your solution solved all of my problems!

**Comment by tuanhm2911** [comment]
@fo40225 
Thank you ! Your solution fixed my problems.

**Comment by vijaysaimutyala** [comment]
@fo40225 Thanks for the wheel. But it seems like TFLite is missing from the contrib !

**Comment by MarlonJhow** [comment]
So thanks @fo40225 ! It's really work for me.

**Comment by wandesky** [comment]
Thanks @fo40225  Installing the tensorflow-1.6.0-cp36-cp36m-win_amd64.whl helped fixed the issue for me. I really appreciate.

**Comment by Curious-Nikhil** [comment]
**System Specs -**
**CPU - AMD Athlon X2 250**
Is it not supported?
Also, how exactly I use the **.whl file** to install and what are the limitations of doing so.
Thanks! @fo40225 
Just need a little help over here.

**Comment by fifothekid** [comment]
Your 1.8 with AVX2 worked on my machine
But my compiled 1.9RC2 with AVX2 doesn't
Any idea?

**Comment by ibrcic** [comment]
.whl file fixed it for me.

@Curious-Nikhil just run it using pip install <path-to-file/filename>

**Comment by laitooo** [comment]
hi i had same problem trying to install tensorflow cpu
when i installed tensorflow it got the error
"no modile named pywrap_tensorflow"

so i downgraded to tensorflow 1.5 
this time it gave me another error 
"dll load failed coulnt find procedure " 
can some one help me with this

**Comment by antodasns** [comment]
I used the .whl file that @fo40225 said and it works like a charm..
Thanks to @fo40225

**Comment by fifothekid** [comment]
Building with Bazel works on Windows

**Comment by santoshgurujula** [comment]
I used the .whl file(TF 1.10.0) downloaded from @fo40225's Github repository said and it works without any issue..
Thanks to @fo40225

**Comment by Jolium** [comment]
After almost one week trying everything I solve the problem.
First I had to unistall tensorflow and than just run pip install!

@fo40225 you are the one!

**Comment by reefman001** [comment]
Attempt restoring spyder to default settings before going down the rabbit hole. This may save you days of sifting through the thousand different solutions out there.

**Comment by darkmanAmazigh** [comment]
i have the same problem,
i use AVX like @fo40225 say, but not working !

**Comment by hanhtd2** [comment]
I fixed this issue with the newest version of tensorflow-gpu==1.13.1, python 3.6.8: 
1. Download CUDA 10.1 (the newest)
2. Download cuDNN 7.5.0 (the newest)
3. Install CUDA
4. Extract cuDNN and copy to installed folder of CUDA
5. Enjoin:
![image](https://user-images.githubusercontent.com/40728496/54088644-d63b2f80-4392-11e9-8d4c-6e8527167550.png)

**Comment by bradezard131** [comment]
@hanhtd2 That has nothing to do with any of this. This entire issue stems from a time where AVX was required for the binary available on Pip, but was not listed in the system requirements. So if you used a CPU that did not support AVX (i.e. an older one) it would not work. Your output shows that your CPU supports AVX...

**Comment by eneszv** [comment]
I had a similar problem and this worked for me

1. Install anaconda
2. Open anaconda prompt
3.  `conda create -n tfp python=3.6`
4. `activate tfp`
5. `conda install tensorflow`
6. `python`
7. `import tensorflow`

If it works and you are using PyCharm go to File -> Settings ->Project Interpreter
Click on top right button ->Add (Project Interpreter) -> Conda Environment ->Existing environment
Choose ~path~\Anaconda3\envs\tfp\python.exe

**Comment by GuoshengCui** [comment]
run this code "import tensorflow as tf" and it report below errors:

ImportError                               Traceback (most recent call last)
D:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

D:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
     34         return _mod
---> 35     _pywrap_tensorflow_internal = swig_import_helper()
     36     del swig_import_helper

D:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     29         try:
---> 30             _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     31         finally:

D:\Anaconda3\lib\imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

D:\Anaconda3\lib\imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-6-8c0c2a0e5106> in <module>
----> 1 import tensorflow as tf
      2 # https://www.lfd.uci.edu/~gohlke/pythonlibs/#xgboost

D:\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     20 
     21 # pylint: disable=g-bad-import-order
---> 22 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     23 from . import app
     24 from . import bitwise

D:\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

D:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 35, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 30, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

my python is Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

my computer is Intel(R) Core(TM) i3 CPU 64bit with win7 Service Pack 1

i have tried many different solutions but they still won't work. Anybody has met the same problem?

**Comment by RehamAboelyazied7** [comment]
ERROR: tensorflow-1.6.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
what should i do to solve this

**Comment by Atulin** [comment]
I have AMD Ryzen 1600 CPU which supports both AVX and AVX2, and I cannot use the CPU version of Tensorflow either.

Stacktrace:
```
Using TensorFlow backend.
Usage: python -m flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "C:\Users\Angius\PycharmProjects\LNNameGen\app.py", line 2, in <module>
    from textgenrnn import textgenrnn
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\textgenrnn\__init__.py", line 1, in <module>
    from .textgenrnn import textgenrnn
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\textgenrnn\textgenrnn.py", line 1, in <module>
    from keras.callbacks import LearningRateScheduler, Callback
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Angius\PycharmProjects\LNNameGen\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
Can't install the provided alternative wheel either, because
```
tensorflow-1.6.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
```

**Comment by pgavda** [comment]
Same
>Can't install the provided alternative wheel either, because
tensorflow-1.6.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

Plz help

**Comment by raibove** [comment]
After the installation I am able to import tensorflow thanks @fo40225 
@pgavda just try to download the wheel from [link](https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.6.0/py36/CPU/sse2/tensorflow-1.6.0-cp36-cp36m-win_amd64.whl) and then run "pip install --user tensorflow" 
Then run " import tensorflow as tf "  
It worked for me.

**Comment by jmtc7** [comment]
I am using **Python 3.6.0** with an i5-6300U (which should have **AVX2 support**, according to [intel](https://ark.intel.com/content/www/us/en/ark/products/88190/intel-core-i5-6300u-processor-3m-cache-up-to-3-00-ghz.html)). I have tried installing **TensorFlow 1.7, 1.6 and 1.4** but nothing worked. The **wheel file** did **not work** either. Any idea of what can be the cause of my issue? I get this message when trying to include the module: 

![image](https://user-images.githubusercontent.com/36297047/72887277-ab886a00-3d0b-11ea-9608-8900c37eb271.png)

**Comment by saurabhsbb** [comment]
> The CPU lack AVX instruction can cause this error.
> 
> I have built tensorflow wheel without AVX.
> 
> https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.6.0/py36/CPU/sse2
> 
> I wish this .whl may help you
I had installed tensorflow 2.2 and facing the same error. Can you please elaborate on what should I do (step by step procedure would be more helpful)
