### ISSUE TITLE
Eager: Allowing GPU memory growth

### ISSUE THREAD

**Issue by nostringattached** [tensorflow/tensorflow#17400]
Since we don't have session in eager mode, how can we allocate only as much GPU memory as needed in our program?

Or can we set the fraction of the overall amount of memory that each visible GPU should be allocated?

When will this feature be supported?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
