### ISSUE TITLE
embed_sequence and embedding_lookup behave differently on CPU vs. GPU

### ISSUE THREAD

**Issue by eisenjulian** [tensorflow/tensorflow#17417]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.6
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
When using `tf.nn.embedding_lookup` or `tf.contrib.layers.embed_sequence` with -1 in the indexes the corresponding embeddings should be 0 vectors, in the same way that `tf.feature_column.categorical_column_with_identity` ignores negative values. This works correctly when trying on Colaboratory but fails on my Windows installation using the same Tensorflow version v1.6.

### Source code / logs
Both ways of initializing the embeddings produce the same error, only on Windows, may it be related to the version of the `gather` function being used from `python\ops\array_ops.py`?
```python
tf.reset_default_graph()
a = tf.constant(np.array([[0, 1, 2, -1, 4]]))
# b = tf.contrib.layers.embed_sequence(a, 5, 3, initializer=tf.random_uniform_initializer(-1.0, 1.0))
b = tf.nn.embedding_lookup(tf.get_variable('embeddings', [5, 3], initializer=tf.random_uniform_initializer(-1.0, 1.0)), a)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(b))
```

The error goes like this
> InvalidArgumentError: indices[..] = -1 is not in [0, ..)

**Comment by bignamehyp** [comment]
@ilblackdragon can you please take a look?

**Comment by eisenjulian** [comment]
Actually, I have some more insight to add, since by trying something else I have discovered that the issue is not with the OS, but it has to do with whether you are using a GPU or not. Running the same code on Linux (for instance in Colaboratory) will throw the same error about -1 values if you disable GPU support. 

Hope this further helps to nail down the issue.

**Comment by ispirmustafa** [comment]
embedding_lookup doesn't support invalid ids. InvalidArgumentError is the right behavior.  FeatureColumns are handling them. We implemented _safe_embedding_lookup_sparse. Making those functions public make sense. I added contributions welcome to make them public.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by ispirmustafa** [comment]
the difference seems related to tf.gather. @alextp do you know who can give us some background info here?

**Comment by alextp** [comment]
Is this related to GPU gather setting out-of-range indices to zero ( https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/gather_functor_gpu.cu.h#L58 ) ?

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by mohantym** [comment]
Hi @eisenjulian ! 
It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. Could you confirm whether issue is replicating after [migrating](https://www.tensorflow.org/guide/migrate/migrate_tf2) to 2.8 or not ? Thanks!

**Comment by harshavardhan-b20** [comment]
Hello,

I'm excited about contributing to this issue and believe it aligns well with my skills and interests. Could you please assign me to work on this? I'm ready to dive in, discuss the details, and start contributing.

Thank you!
Harshavardhan Bellamkonda

**Comment by MarkDaoust** [comment]
Hi, thanks for offering to help out. 

This is an **ancient** issue. It you want to help with it the first step would be to check the current behavior. But given @mohantym 's comment above this is likely still the case. 

It looks like the `safe` function never made it to TF2.

It also looks like the underlying gather OP's docs now mention the difference between CPU and GPU behavior, in a red warning box:

https://www.tensorflow.org/api_docs/python/tf/gather_nd

 Since it's too late in the game to change the behavior of these functions, if you want to help out you could copy that the nodice to the embedding_lookup docs to close this as fixed.

**Comment by harshavardhan-b20** [comment]
Hi there! I'm trying to locate the documentation file for the `tf.nn.embedding_lookup` function. Can anyone point me in the right direction? Thanks!

**Comment by Venkat6871** [comment]
Hi **@eisenjulian** ,
- Could you go through this [documentation](https://www.tensorflow.org/api_docs/python/tf/gather_nd) once. It is clearly showing in red box like this "  On CPU, if an out of bound index is found, an error is returned. On GPU, if an out of bound index is found, a 0 is stored in the corresponding output value". If it is not resolved for you please let us know.

Thank you!
