### ISSUE TITLE
Polygamma and zeta function for tensorflow

### ISSUE THREAD

**Issue by tillahoffmann** [tensorflow/tensorflow#1741]
The polygamma function is necessary to evaluate the derivative of the digamma function which is already supported by tensorflow. As suggested by @ebrevdo in #291, I have ported the code for the two-parameter zeta function from cephes which allows us to evaluate the polygamma function. A pull request for eigen is [here](https://bitbucket.org/eigen/eigen/pull-requests/173/added-zeta-function-of-two-arguments-and). 

What is the best way to proceed integrating the new functionality into tensorflow? I'm happy to contribute the code with a bit of input regarding the right procedure. In particular, how do you update the eigen sources within the tensorflow repo?

**Comment by ebrevdo** [comment]
Let's get that code through review on bitbucket, then we can update the references and I'll push my changes adding igamma/igammac to TensorFlow.  You'll be able to use those as reference for the TF implementations of polygamma/zeta.

**Comment by tillahoffmann** [comment]
The zeta and polygamma functions are now in eigen. Happy to have a look at implementing them in tensorflow whenever you have time to update the references.

**Comment by ebrevdo** [comment]
Great!  I need a couple of days to import your changes on our end.  In the meantime look at my recent push of igamma/igammac as a reference for wrapping zeta/polygamma.

**Comment by ebrevdo** [comment]
(note the unit tests I added: they require scipy and cause a soft failure if it's not found.  this is fine - just make sure you have scipy installed when testing locally)

**Comment by tillahoffmann** [comment]
That sounds good. I have implemented the wrappers locally. Just let me know when you've integrated the changes and I'll submit a PR.

**Comment by benoitsteiner** [comment]
The Eigen implementations of the polygamma and zeta functions are now available in TensorFlow

**Comment by akashgit** [comment]
@benoitsteiner is the build containing these functions already available ? thanks

**Comment by tillahoffmann** [comment]
@akashgit, the eigen code in TensorFlow supports the functions but they won't be available from python until the PR above is merged. You can have a look there if you need them urgently.
