### ISSUE TITLE
Feature Request: Train Using Multiple GPUs with Tensorflow in a Tower-like Fashion for tensorflow 1.4

### ISSUE THREAD

**Issue by selcouthlyBlue** [tensorflow/tensorflow#17427]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 8.1
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
1.4
- **Python version**: 
3.6
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
8.0
- **GPU model and memory**:
2 NVIDIA GeForce GTX 1070 (8 GB each)
-**Exact command to reproduce**:
N/A

### Describe the problem
I tried training my model with a large batch size that is supposed to be enough just for two GPUs but I encounter out of memory errors. I'm using the Estimator API and I was wondering if it handles multi-gpu training like in this [example](https://www.tensorflow.org/tutorials/deep_cnn#training_a_model_using_multiple_gpu_cards) using the cifar_10 dataset. If it doesn't, it would be nice to have the Estimator API handle multi-gpu training such that we can use larger batch sizes.

### Source code / logs
Here's the architecture of the model I trained.

```
{
  "network":[
    {"layer_type": "input_layer", "name": "inputs", "shape": [-1, 168, 168, 1]},
    {"layer_type": "l2_normalize", "axis": [1, 2]},
    {"layer_type": "conv2d", "num_filters": 16, "kernel_size": [3, 3]},
    {"layer_type": "max_pool2d", "pool_size": [2, 2]},
    {"layer_type": "l2_normalize", "axis": [1, 2]},
    {"layer_type": "conv2d", "num_filters": 32, "kernel_size": [3, 3]},
    {"layer_type": "max_pool2d", "pool_size": [2, 2]},
    {"layer_type": "l2_normalize", "axis": [1, 2]},
    {"layer_type": "dropout", "keep_prob": 0.5},
    {"layer_type": "conv2d", "num_filters": 64, "kernel_size": [3, 3]},
    {"layer_type": "max_pool2d", "pool_size": [2, 2]},
    {"layer_type": "l2_normalize", "axis": [1, 2]},
    {"layer_type": "dropout", "keep_prob": 0.5},
    {"layer_type": "collapse_to_rnn_dims"},
    {"layer_type": "birnn", "num_hidden": 128, "cell_type": "LSTM"},
    {"layer_type": "dropout", "keep_prob": 0.5}
  ],
  "output_layer": "ctc_decoder",
  "loss": "ctc",
  "metrics": ["label_error_rate"],
  "learning_rate": 0.001,
  "optimizer": "adam"
}
```

The image dimensions are 168x168 px and the working batch size is 240 which I would like to double.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by selcouthlyBlue** [comment]
It’s not really relevant to the issue since this is a feature request.

**Comment by carlthome** [comment]
It's actually super easy to get data parallel, single-machine, multi-GPU training going with a `tf.estimator` by using the [replicate_model_fn](https://www.tensorflow.org/versions/master/api_docs/python/tf/contrib/estimator/replicate_model_fn) and [TowerOptimizer](https://www.tensorflow.org/versions/master/api_docs/python/tf/contrib/estimator/TowerOptimizer) decorators. Just make sure your batch size is divisible by the number of GPUs.

**Comment by selcouthlyBlue** [comment]
Is there an example that uses those things? I guess it would be nice to have an example in the “Using Multiple GPUs” section that uses tf.Estimator.

**Comment by selcouthlyBlue** [comment]
Can this be supported in tensorflow 1.4 as well?

**Comment by selcouthlyBlue** [comment]
I created this pull request for that. https://github.com/tensorflow/tensorflow/pull/17462

**Comment by drpngx** [comment]
@selcouthlyBlue did you send a PR against master?

**Comment by selcouthlyBlue** [comment]
I did send a PR against master. https://github.com/tensorflow/tensorflow/pull/17478 But it's not related to this request.

**Comment by drpngx** [comment]
Ok how about sending one for this request?

**Comment by selcouthlyBlue** [comment]
This feature apparently exists in master already. I just want it to be supported in tensorflow 1.4 as well. Here's the pull request I made against r1.4 https://github.com/tensorflow/tensorflow/pull/17462

**Comment by drpngx** [comment]
Thanks for checking! Ok, we can close this then

**Comment by selcouthlyBlue** [comment]
So will the said feature be added to tensorflow 1.4? I did notice that my pull request for that branch was closed for the following reason:

> TensorFlow development is on master rather than any of the release branches, and once there is a release branch, we only accept bugfixes for that branch, so we can't accept this right now.

**Comment by drpngx** [comment]
You need to send PRs directly against master. The release branches are for
our use only. They contain the release bits. The release branches are cut
from the master branch periodically, do if you get something into master,
it will become part of the next release

**Comment by selcouthlyBlue** [comment]
So every feature that gets added into master are periodically added into the release branches including the older ones?

**Comment by drpngx** [comment]
No, we only cherry pick important bug fixes to the older releases

**Comment by drpngx** [comment]
Also when we cherry pick these but sizes, we pick them from master.

**Comment by selcouthlyBlue** [comment]
In that case, I'm closing this issue now.
