### ISSUE TITLE
CTC: Add support for dense label matrix

### ISSUE THREAD

**Issue by mbhenry** [tensorflow/tensorflow#1742]
I'm working on integrating the new CTC operation into Keras and the SparseTensor used to pass the labels is causing a lot challenges due internal Keras requirements about the shape of the data going into the layers. What would be make integration trivial is an alternative dense label input format:

```python
def ctc_loss_dense(inputs, labels, sequence_length, label_length,
             preprocess_collapse_repeated=False, ctc_merge_repeated=True):
  """Computes the CTC (Connectionist Temporal Classification) Loss.
  Requires:
       max_label_length <= sequence_length
  If ctc_merge_repeated is set False, then *during* CTC calculation
  repeated non-blank labels will not be merged and are interpreted
  as individual labels.  This is a simplified version of CTC.
  Args:
    inputs: 3-D `float` `Tensor` sized
      `[max_time x batch_size x num_classes]`.  The logits.
    labels: 2-D `int` `Tensor` sized
       `[max_label_length x batch_size]
    sequence_length: 1-D `int32` vector, size `[batch_size]`.
      The sequence lengths.
    label_length: 1-D `int32` vector, size `[batch_size]`.
      The label lengths.
    preprocess_collapse_repeated: Boolean.  Default: False.
      If True, repeated labels are collapsed prior to the CTC calculation.
    ctc_merge_repeated: Boolean.  Default: True.
  Returns:
    A 1-D `float` `Tensor`, size `[batch]`, containing logits.
  Raises:
    TypeError: if labels is not a `SparseTensor`.
  """
```
This dense input format would also be consistent with Baidu's Warp-CTC and various Theano CTC implementations, so projects using cross-library platforms like Keras would be a lot cleaner.  Also, for common CTC uses like OCR and speech processing, the sequence lengths are often a lot smaller than the input lengths, so I don't think the increased bandwidth from not having a spare tensor would be too noticeable.

**Comment by ebrevdo** [comment]
This is method is simple to write using the sparse_tensor_to_dense op.  Contributions are welcome.

**Comment by mbhenry** [comment]
I was thinking it would need the reverse of that (Dense to sparse) which doesn't seem to exist.

**Comment by ebrevdo** [comment]
Sorry right. I added gather_nd which does what you need.

**Comment by mbhenry** [comment]
Thanks for pointing me to gather_nd.  It did take a bit more effort to generate the index list from the label_length arrays, but I got it working.  Below is the code.

```python
def ctc_label_dense_to_sparse( labels, label_lengths ):
    label_shape = tf.shape( labels )
    num_batches_tns = tf.pack( [label_shape[0]] )
    max_num_labels_tns = tf.pack( [label_shape[1]] )
    def range_less_than(previous_state, current_input):
        return tf.expand_dims( tf.range( label_shape[1] ), 0 ) < current_input

    init = tf.cast( tf.fill( max_num_labels_tns, 0 ), tf.bool )
    dense_mask = functional_ops.scan(range_less_than, label_lengths , initializer=init, 
         parallel_iterations=1)
    dense_mask = dense_mask[ :, 0, : ]

    label_array = tf.reshape( tf.tile( tf.range( 0, label_shape[1] ), num_batches_tns ),
          label_shape )
    label_ind = tf.boolean_mask( label_array, dense_mask )

    batch_array = tf.transpose( tf.reshape( tf.tile( tf.range( 0,  label_shape[0] ), max_num_labels_tns ),
          tf.reverse( label_shape,[True]) ) )
    batch_ind = tf.boolean_mask( batch_array, dense_mask )

    indices = tf.transpose( tf.reshape( tf.concat( 0, [batch_ind, label_ind] ), [2,-1] ) )
    vals_sparse = tf.gather_nd( labels, indices )
    return tf.SparseTensor( tf.to_int64(indices), vals_sparse, tf.to_int64( label_shape ) )
```
For now I may put this in a Keras PR, unless you think it has a place in the TensorFlow API.

**Comment by wangyongliang** [comment]
@ebrevdo 

Hi ebrevdo ,
recently I am trying to use ctc in a OCR project, but I found that the "label" parameter in ctc_loss function is sparse tensor, but it seams that I can't feed a sparse tensor to placeholder. Is there any way to work around it?

**Comment by ebrevdo** [comment]
Create 3 tensors (indices, values, shape), wrap them in a SparseTensor
object, and feed the 3 tensors together.

**Comment by raindeer** [comment]
Maybe a stupid question, but why use a SparseTensor at all since it is never sparse? You have a label for each timestep right?

**Comment by ebrevdo** [comment]
No, for CTC you have a different number of output time steps than input
time steps.  That's the point.

**Comment by raindeer** [comment]
Yes of course, the target/output sequence is shorter than the input sequence. But for every "target timestep" you have a label, right?
Im probably misunderstanding what `labels` represent.  In the docs it says:
`labels.indices[i, :] == [b, t]` means `labels.values[i]` stores the id for (batch b, time t). 
Is not t here in the output time scale?

**Comment by raindeer** [comment]
Ah, now i get it, you want to use a SparseTensor since the target sequences might have different length?

**Comment by ebrevdo** [comment]
Yes - the target sequences almost always have different length, from one
batch entry to the next.

**Comment by girving** [comment]
@ebrevdo @raindeer What's the status of this issue?

**Comment by ebrevdo** [comment]
Marked as resolved.  It's easy to create a SparseTensor if you have fixed length target sequences.

**Comment by selcouthlyBlue** [comment]
PR https://github.com/tensorflow/tensorflow/pull/16119 addresses this issue.
