### ISSUE TITLE
docker image for 1.6.0 is missing CUPTI libraries

### ISSUE THREAD

**Issue by voegtlel** [tensorflow/tensorflow#17431]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04, 4.4.0-104-generic
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version**: v1.6.0-0-gd2e24b6 1.6.0
- **Bazel version**: N/A
- **CUDA/cuDNN version**: 9.0.176 (from docker image)
- **GPU model and memory**: GeForce GTX TITAN X
- **Exact command to reproduce**: (see below)

### Describe the Error

CUPTI library is missing in docker image `tensorflow/tensorflow:1.6.0-gpu-py3`. This is required when using `trace_level=tf.RunOptions.FULL_TRACE` and `run_metadata` in session.run.

### Source code / logs
To reproduce:

    # run.py
    import tensorflow as tf

    with tf.Session().as_default() as sess:
        test_op = tf.no_op()

        run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
        run_metadata = tf.RunMetadata()
        sess.run(test_op, options=run_options, run_metadata=run_metadata)

And run:
`> nvidia-docker run --volume /path/to/run.py:/run.py --rm -it tensorflow/tensorflow:1.6.0-gpu-py3 python /run.py`

The error message is:

    2018-03-05 00:00:00.000000: I tensorflow/stream_executor/dso_loader.cc:141] Couldn't open CUDA library libcupti.so.9.0. LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
    2018-03-05 00:00:00.000000: F ./tensorflow/stream_executor/lib/statusor.h:212] Non-OK-status: status_ status: Failed precondition: could not dlopen DSO: libcupti.so.9.0; dlerror: libcupti.so.9.0: cannot open shared object file: No such file or directory

Additional information from within the docker image:

    > echo $LD_LIBRARY_PATH
    /usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
    > ll /usr/local/cuda/extras/CUPTI/lib64
    ls: cannot access '/usr/local/cuda/extras/CUPTI/lib64': No such file or directory
    > find / -name libcupti*
    (not found)

The library seems to be missing in this build. Worked with tensorflow/tensorflow:1.4.0-gpu-py3.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by voegtlel** [comment]
@tensorflowbutler: Updated accordingly. They are all not relevant, still filled them in.

**Comment by voegtlel** [comment]
In case anyone needs a workaround: Go to https://developer.nvidia.com/cuda-90-download-archive, Select: Linux, x86_64, Ubuntu, 16.04, deb (local). Download base installer and all patches.

Build a new docker image with Dockerfile:
```Dockerfile
FROM tensorflow/tensorflow:1.6.0-gpu-py3
ADD cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64.deb /tmp
ADD cuda-repo-ubuntu1604-9-0-local-cublas-performance-update_1.0-1_amd64.deb /tmp
ADD cuda-repo-ubuntu1604-9-0-local-cublas-performance-update-2_1.0-1_amd64.deb /tmp
# Does not require any internet connection
RUN dpkg -i /tmp/cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64.deb && \
 dpkg -i /tmp/cuda-repo-ubuntu1604-9-0-local-cublas-performance-update_1.0-1_amd64.deb && \
 dpkg -i /tmp/cuda-repo-ubuntu1604-9-0-local-cublas-performance-update-2_1.0-1_amd64.deb && \
 apt-key add /var/cuda-repo-9-0-local/7fa2af80.pub && \
 apt-get update -o Dir::Etc::sourcelist="sources.list.d/cuda-9-0-local.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" && \
 apt-get update -o Dir::Etc::sourcelist="sources.list.d/cuda-9-0-local-cublas-performance-update.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" && \
 apt-get update -o Dir::Etc::sourcelist="sources.list.d/cuda-9-0-local-cublas-performance-update-2.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" && \
 apt-get install -y cuda-libraries-9-0 cuda-command-line-tools-9-0 cuda-cublas-9-0
```

**Comment by flx42** [comment]
cupti is present in `tensorflow/tensorflow:1.6.0-devel-gpu-py3`. I think it makes sense.

In addition, in CUDA 9.0, CUPTI is not in its own package, so we would have to pull ~100MB of dependencies just to get CUPTI in the non-devel image.
I suggest that we either keep CUPTI out of the non-devel image, or we wait until cuda 9.1+ to add it back since it finally has a dedicated package (`cuda-cupti-9-1`).

@gunan

**Comment by voegtlel** [comment]
Thanks for your response. I see that cupti does not have a dedicated package für cuda 8.0 for Ubuntu 16.04 (https://packages.ubuntu.com/search?keywords=libcupti) and is not included in the main package. Still one might wish not to build tensorflow (thats what devel is for, right?), but still want to get run_metadata. libcupti.so is ~5.7MB, thus I see no issue to put it in the nondevel image.

**Comment by gunan** [comment]
Unfortunately, CUPTI is a runtime dependency for certain modules in TF, so it may be best to pull in the extra 100MBs. We try to provide the non-devel images to be as a quickstart to TF, so it is better to make sure they have as little issues as possible.
But once cupti has its own package it looks like this will be much better, thanks for the information @flx42

**Comment by flx42** [comment]
I could bundle this fix with the change I suggested here: https://github.com/tensorflow/tensorflow/issues/17566#issuecomment-372851697
