### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by karthickn210** [tensorflow/tensorflow#17441]
karthick@karthick-Aspire-4739Z:~$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
**Illegal instruction (core dumped)**
karthick@karthick-Aspire-4739Z:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  **File "<stdin>", line 1, in <module>
ImportError: No module named tensorflow**
>>> exit()

how can i solve this problem but i install tensorflow using native pip on both pip3 and pip on ubuntu 16.04

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sbean0** [comment]
https://github.com/tensorflow/tensorflow/issues/17411 

shows installing tensoflow 1.5 (vs 1.6) fixed this issue.
resolved issue for me also
