### ISSUE TITLE
install fails on ubuntu 

### ISSUE THREAD

**Issue by Sandy4321** [tensorflow/tensorflow#1745]
install per recomendatoin from github fails on ubuntu 

sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl

sandy@sandy-laptop:~$ sudo apt-get install python-pip python-dev
[sudo] password for sandy: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version.
python-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 268 not upgraded.
sandy@sandy-laptop:~$ sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
  Downloading tensorflow-0.7.1-cp27-none-linux_x86_64.whl (13.8Mb): 13.8Mb downloaded
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-8L3Eho-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-8L3Eho-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /home/sandy/.pip/pip.log
sandy@sandy-laptop:~$ 

GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

If installed from sources, provide the commit hash:

### Steps to reproduce
1.
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by vrv** [comment]
Try https://www.tensorflow.org/versions/r0.7/get_started/os_setup.html#pip-installation-issues
