### ISSUE TITLE
Support OpenMP and SIMD?

### ISSUE THREAD

**Issue by linkerlin** [tensorflow/tensorflow#1747]
char foo(char *A, int n){
int i;
char x = 0;
#pragma omp parallel for simd
for(i = 0; i < n; i++)
x = x + A[i];
return 0;
}

$ icc test.c -c -vec-report2 -c -openmp-report2 -openmp
test.c(4): (col. 1) remark: OpenMP DEFINED LOOP WAS PARALLELIZED
test.c(5): (col. 1) remark: OpenMP SIMD LOOP WAS VECTORIZED

**Comment by martinwicke** [comment]
Most of our in-op parallel currently comes through Eigen, which includes SIMD optimizations. We're not planning on using OpenMP right now, see also a discussion at #22. 

I'll close this issue for now. We may revisit it depending on how the OpenCL work goes.
