### ISSUE TITLE
The "multiply" operator of type Dimension has a bug.

### ISSUE THREAD

**Issue by George-Gate** [tensorflow/tensorflow#17482]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Custom code
- **OS**: Win10 64bit 
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.5.0
- **Python version**: 3.6.2
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: GTX 1080Ti
- **Exact command to reproduce**: See codes below

### Describe the problem
Suppose `A` is a tensor, `L = A.shape[0]`. I found that `L*3` works while `3*L` lead to a **TypeError**. Can someone fix this?

### Source code / logs
```
import tensorflow as tf
A = tf.placeholder( tf.float32, shape = [3, 4, 5] )
L = A.shape[0]
print( type(L) )
print( L*3 )
print( 3*L )
```
Output is:
![image](https://user-images.githubusercontent.com/8580553/37040371-a1b8e12e-2194-11e8-8d23-b317458b2382.png)

**Comment by George-Gate** [comment]
It seems that this problem exists for all operators like `//`, `-`, `+`, `%` etc...

**Comment by shoyer** [comment]
It appears that Dimension needs special methods defined for reflexive methods, e.g., `__rmul__`.

**Comment by facaiy** [comment]
5fd341d has fixed the problem, I think we can close the issue now.

**Comment by George-Gate** [comment]
Thanks a lot!
