### ISSUE TITLE
Request: Better documentation on TFRecords and their use

### ISSUE THREAD

**Issue by robwell** [tensorflow/tensorflow#1749]
I am using TFRecords to use the sharding/queuing machinery. For simple problems for which the examples can be cloned, it is easy to use. But recently I tried to do something more complex: train examples where there are multiple labels. I posted a question on Stackoverflow about the specific issue I have: http://stackoverflow.com/questions/36365118/how-do-you-write-and-retrieve-tfrecord-features-that-are-lists

It would be nice to have clearer guidance on the use of TFRecords. I've looked through the code, have a pretty good understanding of Protocol Buffers, etc. In spite of this it is difficult to understand how the machinery works.

**Comment by alextp** [comment]
@robwell I saw your stackoverflow question was resolved. Is this still relevant? Thanks!

**Comment by TimZaman** [comment]
@alextp The issue here is not a question on SO. It's more a request for better documentation for TFRecords. This Issue here is the _4th hit_ on Google Search if you look for 'TFRecords'. 
https://www.tensorflow.org/versions/r0.11/how_tos/reading_data/index.html has a exact grand total of **8  sentences** on the topic of TFRecords.
It literally states it is The [Tensorflow] Standard Data Format, it would make sense to me to elaborate more on this topic with examples and good usage practices. And sure, the well documented API itself provides the tools, but does not touch upon the actual usage and power of TFRecords.

**Comment by zorancupic** [comment]
it would also be awesome if there would be some function which easily writes examples in the given tfrecords file. A function you give a tensor of the for example a image and the label tensor for this image (one or multidim label) and it writes this to the tfrecord file.

**Comment by drpngx** [comment]
We revamped our docs. Feel free to open a new issue if this is still missing from our new docs.

**Comment by ajschumacher** [comment]
I've tried to explain the basics of TFRecords in this post: [TFRecords for Humans](http://planspace.org/20170323-tfrecords_for_humans/). Maybe it's helpful for at least some aspects?

I'm thinking of continuing to write, specifically on working with images, and perhaps also on reading in-graph.

**Comment by drpngx** [comment]
Thanks @ajschumacher, that's really neat!

**Comment by ajschumacher** [comment]
I've written a bit more about working with images specifically: [Images and TFRecords](http://planspace.org/20170403-images_and_tfrecords/). Also includes a bit of background on how image formats work. Hope it's helpful!

**Comment by TimZaman** [comment]
Ideally we don't have to scrape people's blogs for documentation but have it in the documentation. @drpngx closed the issue saying the docs are revamped. But really, on the topic of TFRecords usage there is still exactly that same single one: paragraph.https://www.tensorflow.org/programmers_guide/reading_data#reading_from_files.
The paragraph includes 9 sentences.
One sentence reads`The recommended format for TensorFlow is a TFRecords file (..) `; that's pretty weird considering the 9 sentences about the format.

**Comment by drcrook1** [comment]
As well as including information on how to create inference programs with a model that was trained using queue runners and tfrecords.

**Comment by notsmartenough** [comment]
Exactly, this is not about one question or doubt or a blog post. Tensorflow, in general, has very vague documentation. It seems totally confusing for beginners like me. For eg. https://www.tensorflow.org/api_docs/python/tf/train/Features

**Comment by evictor** [comment]
This needs more attention... All we're left to do is peruse source code or random blogs. Official docs are greatly needed!
