### ISSUE TITLE
use tf.concat, get error about ExpandDims, Prod, Slice not supported when use toco to convert the model to .tflite format

### ISSUE THREAD

**Issue by BKZero** [tensorflow/tensorflow#17497]
detail is describe in:
https://github.com/tensorflow/tensorflow/issues/17461

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by andydavis1** [comment]
@aselle Looks TFLite related

**Comment by BKZero** [comment]
@tensorflowbutler 

**System information**

Have I written custom code: yes, the model definition in the attach files: 
[models.zip](https://github.com/tensorflow/tensorflow/files/1791589/models.zip)
OS Platform and Distribution (Linux Ubuntu 14.04):
TensorFlow installed from (build from source):
TensorFlow version (r1.5):
Bazel version(0.8.1)
GPU model and memory: CPU only

**Exact command to reproduce**
i train the model with tf.slim, then freeze with the python script : 
[python-script.zip](https://github.com/tensorflow/tensorflow/files/1791587/python-script.zip)
then i got a pb file and converting it to the .tflite format:
```
./bazel-bin/tensorflow/contrib/lite/toco/toco --input_file=../test.pb --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --output_file=litev1.tflite --inference_type=FLOAT --input_type=FLOAT --input_arrays=lite_v1/InputPlaceholder --output_arrays=lite_v1/Output --input_shapes=1,35,35,1
```

**Comment by BKZero** [comment]
@andydavis1 
yes, it is about the TFLite. but i do not know the problem is toco tools or the definition of the original network.
seems tf.concat is ok in other cases, i mean, when tf.concat appear in other position, the model converting is successful, but when i use tf.concat after slim.flatten, there is an error.

**Comment by andrehentz** [comment]
I'll close this one. Will use #17461 to track.
