### ISSUE TITLE
einsum-like function?

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#175]
Numpy has einsum which is very useful for formulating and computing tensor operations efficiently. Any plans to include an equivalent in tensorflow?

**Comment by vrv** [comment]
We are not working on it right now -- would be happy to have contributions though!

**Comment by goodfeli** [comment]
any updates on this issue?

**Comment by tscohen** [comment]
Would also like to see this. One tensor op to rule them all.

If anyone wants to have a go at this, note that the gradient of einsum can be implemented neatly as another einsum with swapped arguments / indices. See the autograd implementation make_grad_einsum: https://github.com/HIPS/autograd/blob/master/autograd/numpy/numpy_grads.py#L447

**Comment by jluttine** [comment]
Just a minor comment: NumPy einsum supports arbitrary number of input arrays, but I guess it would suffice to support only two input tensors in TensorFlow.

**Comment by yaroslavvb** [comment]
einsum would subsume tensordot which is tracked in https://github.com/tensorflow/tensorflow/issues/216

**Comment by zakizhou** [comment]
@yaroslavvb thanks Bulatov, It did work for high dimentional tensors inner product!
