### ISSUE TITLE
Tensorflow failed when build with MSVC + /permissive-

### ISSUE THREAD

**Issue by PhoebeHui** [tensorflow/tensorflow#17502]
System information
•	Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
N/A 
•	OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows server 2016
•	TensorFlow installed from (source or binary):
Source
•	TensorFlow version (use command below):
Master branch latest revison
•	Python version:
Anaconda 4.1.1 (Python 3.5 64-bit) 
•	Bazel version (if compiling from source):
N/A
•	GCC/Compiler version (if compiling from source):
VS2017 15.5.7
•	CUDA/cuDNN version:
NVidia CUDA Toolkit 8.0
NVidia CUDNN 5.1
•	GPU model and memory:
N/A
•	Exact command to reproduce:
N/A

Describe the problem
Tensorflow failed when build with /permissive- by using msvc on windows. This should be tensorflow source issue, could you help fix it?

The failures like:
D:\Tensorflow\src\tensorflow/core/util/memmapped_file_system.h(61): error C2440: 'initializing': cannot convert from 'const char [21]' to 'char *const '
D:\Tensorflow\src\tensorflow/core/util/memmapped_file_system.h(61): note: Conversion from string literal loses const qualifier (see /Zc:strictStrings)
D:\Tensorflow\src\tensorflow/core/util/memmapped_file_system.h(69): error C2440: 'initializing': cannot convert from 'const char [22]' to 'char *const '
D:\Tensorflow\src\tensorflow/core/util/memmapped_file_system.h(69): note: Conversion from string literal loses const qualifier (see /Zc:strictStrings)
D:\Tensorflow\src\tensorflow\core\util\memmapped_file_system.cc(182): error C2737: 'tensorflow::MemmappedFileSystem::kMemmappedPackagePrefix': 'constexpr' object must be initialized
D:\Tensorflow\src\tensorflow\core\util\memmapped_file_system.cc(182): error C2734: 'tensorflow::MemmappedFileSystem::kMemmappedPackagePrefix': 'const' object must be initialized if not 'extern'
D:\Tensorflow\src\tensorflow\core\util\memmapped_file_system.cc(183): error C2737: 'tensorflow::MemmappedFileSystem::kMemmappedPackageDefaultGraphDef': 'constexpr' object must be initialized
D:\Tensorflow\src\tensorflow\core\util\memmapped_file_system.cc(183): error C2734: 'tensorflow::MemmappedFileSystem::kMemmappedPackageDefaultGraphDef': 'const' object must be initialized if not 'extern'

Repro steps:
1.	git clone  https://github.com/tensorflow/tensorflow D:\Tensorflow\src
2.	pushd D:\Tensorflow
3.	set PreferredToolArchitecture=x64
4.	set rel=Release
5.	set CUDNN_HOME="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\cuda"
6.	set PY=C:\ProgramData\Anaconda3
7.	set _CL_=/FS /permissive-
8.	cmake D:\Tensorflow\src\tensorflow\contrib\cmake -A x64 -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=C:\ProgramData\Anaconda3\python.exe -DPYTHON_LIBRARIES=C:\ProgramData\Anaconda3\libs\python36.lib -DSWIG_EXECUTABLE=D:\Tensorflow\swigwin-3.0.12\swig.exe -Dtensorflow_BUILD_PYTHON_TESTS=ON -Dtensorflow_BUILD_SHARED_LIB=ON
9. MSBuild /m /p:Configuration=Release;Platform=x64 /p:WindowsTargetPlatformVersion=10.0.16299.0 tensorflow.sln /t:Rebuild

**Comment by Blackh0leZ** [comment]
/Zc:strictStrings and along other /Zc: C++ standard conformance behaviors are turned on by default under the /permissive- mode in MSVC. Starting with VS2017 15.5 update release, /permissive- is turned on for new Visual C++ Console applications and Windows SDK headers with Redstone 3 release (Nov 2017) are clean with this mode. MSVC's plan is in not-so-distant future to turn on the /permissive- switch by default in the compiler. Making these source changes in Tensorflow will better align with more conformance MSVC compiler as well as be compatible with other C++ compilers GCC/Clang.
Thank you,

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Blackh0leZ** [comment]
My post was supplemental information for the previous bug report from Phoebe Ma.

Thanks,
Bat-Ulzii Лувсанбат
Cell: +1 (425) 551-9551<tel:%2B1%20%28425%29%20551-9551>

**Comment by cy89** [comment]
@mrry @gunan PTAL: seems like a reasonable request, which isn't breaking the build yet but will do so in once /permissive becomes the default.

**Comment by mrry** [comment]
Seems reasonable, but not a priority for me, so I'm marking it "Contributions Welcome".

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by mohantym** [comment]
Hi @PhoebeHui ! 1.x versions are not supported any more. Please check out the[ build from source ](https://www.tensorflow.org/install/source)documentation from the 2.9 version and  let us know . Thank you!

**Comment by QuellaZhang** [comment]
@Blackh0leZ Thanks for the reminder, we switched to the master branch a long time ago. :)

**Comment by PhoebeHui** [comment]
Thanks @mohantym for your reply!
