### ISSUE TITLE
android Semantic segmentation  

### ISSUE THREAD

**Issue by shadow111** [tensorflow/tensorflow#17511]
Hello,

can tensorflow for android be used for semantic segmentation?
Thank you

Lafi

**Comment by shadydiaa** [comment]
i want to ask the same question ?
@tensorflowbutler 
### System information
- **Have I written custom code : No
- **OS Platform and Distribution : windows 10 
- **TensorFlow installed from binary
- **TensorFlow version :1.6
- **Python version**: 3
- **Bazel version *:N/A
- **CUDA/cuDNN version**: cuda 9 - cudnn 7
- **GPU model and memory**: geforce gtx 960 - 4 GB 
- **Exact command to reproduce**: N/A

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
