### ISSUE TITLE
master branch building problem

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#1751]
when using bazel (0.20 or 0.21 or master) to build tensorflow master branch, the process get stalled on Analyzing....

**Comment by martinwicke** [comment]
It seems to work in our tests. Can you provide more information? Is this still an issue?

**Comment by martinwicke** [comment]
Closing for now, please comment with more information if it's still an issue.

**Comment by trinity77** [comment]
Trigger last updated
