### ISSUE TITLE
Feature request:  Increase kMaxEagerParentSize or make it python version dependent

### ISSUE THREAD

**Issue by RichDubielzig** [tensorflow/tensorflow#17530]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
N/A (problem occurs on startup)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
tip of tree
- **Python version**: 
3.6 (from source)
- **Bazel version (if compiling from source)**:
0.10.1
- **GCC/Compiler version (if compiling from source)**:
4.8.4
- **CUDA/cuDNN version**:
unused
- **GPU model and memory**:
n/a
- **Exact command to reproduce**:
import tensorflow

### Describe the problem
We wanted to evaluate our patches in Valgrind, so we made a custom build of python 3.6 from source (it's more valgrind-friendly), then compiled TensorFlow against that.

When this done, 'import tensorflow' fails on a python exception because the size of the base class of EagerTensor in Python 3.6 is greater than kMaxEagerParentSize.

Issue #16836 was opened on this a month ago, but closed by its creator.  When we encountered this problem, we found that we could simply set the value of kMaxEagerParentSize to 48 and everything would run with no obvious issues.

Is there a reason that kMaxEagerParentSize must always equal 32, or can it be increased, or possibly even adjusted depending on which version of python TensorFlow is being compiled for?

### Source code / logs
```
diff --git a/tensorflow/python/eager/pywrap_tensor.cc b/tensorflow/python/eager/pywrap_tensor.cc
index 3ec2109..cc1c0f7 100644
--- a/tensorflow/python/eager/pywrap_tensor.cc
+++ b/tensorflow/python/eager/pywrap_tensor.cc
@@ -163,7 +163,7 @@ PyObject* PyIntFromDataType(TF_DataType l) {
 
 extern "C" {
 
-static const int kMaxEagerTensorParentSize = 32;
+static const int kMaxEagerTensorParentSize = 48;
 
 // TODO(agarwal): store context handle in EagerTensor.
 typedef struct EagerTensor {
```

**Comment by aselle** [comment]
You are compiling TensorFlow 1.6? or do you really mean Python 1.6? If the latter, we do not support less like python 2.x.

As far as I can tell, the underlying tensor implementation must be able to fit in the kMaxEagerParentSize. So in principal it can be increased with impunity. Somehow in your compile the base class tensor size is larger (probably alignment differences between compilers?)

@alextp, do you have any insights?

**Comment by RichDubielzig** [comment]
I meant Python version 3.6, sorry.  I got mixed up between TensorFlow and Python versions.  I've updated the ticket to correct my mistake.

**Comment by alextp** [comment]
@agarwal-ashish I think it should be fine to increase the size, right?

**Comment by agarwal-ashish** [comment]
Yes, it should be ok to increase the size.  @RichDubielzig, do you want to submit your change ?

**Comment by mirh** [comment]
The same problem also happens when I try to compile python with `--with-pydebug`
For some reason, that alone increase type size from 400 to 416

**Comment by agarwal-ashish** [comment]
kMaxEagerParentSize is now 64 bytes and should be available in nightly builds soon. Please reopen if this value still doesn't work.

**Comment by RichDubielzig** [comment]
Thanks.  I was looking into ways to try and autodetect whether pydebug was on and got nowhere.
