### ISSUE TITLE
AVX512F is not compiled when running "hello world" test using Tensorflow 1.6 on Intel KNL

### ISSUE THREAD

**Issue by melodylail** [tensorflow/tensorflow#17537]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No custom code

- **TensorFlow installed from (source or binary)**:
binary, follow the instructions from intel,
https://software.intel.com/en-us/articles/intel-optimized-tensorflow-wheel-now-available#comment-1919528

Linux KNL101-04 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="17.10 (Artful Aardvark)"
VERSION_ID="17.10"
VERSION_CODENAME=artful

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux KNL101-04 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.13.3)
protobuf (3.5.2)
tensorflow (1.6.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.6.0
tf.GIT_VERSION = b'unknown'
tf.COMPILER_VERSION = b'unknown'
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

### Describe the problem

It seems that AVX512F is not compiled into released tensorflow 1.6. (but other KNL specific AVX512 instructions are compiled!!!)

I run simple "hello world" test on KNL after install the tensorflow 1.6 by following the steps mentioned here!!

it give me the message as follows:

2018-03-08 13:08:26.924344: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX512F

BTW, i try to compile the tensorflow 1.6 from source code, and adding all of avxxxxx as -copt to bazel build cmd, after build tensorflow 1.6 package correctly, re-run above test program, it seems the "AVX512F" is compiled!!!!

### Source code / logs
Source code
simple program, just print "hello tensorflow" using tensorflow.

logs:
2018-03-08 13:08:26.924344: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX512F

**Comment by gunan** [comment]
These are binaries built,  distributed and maintained by Intel.
You should reach out to intel with questions about those.
