### ISSUE TITLE
Setting up CI jobs for Windows Bazel build

### ISSUE THREAD

**Issue by meteorcloudy** [tensorflow/tensorflow#17549]
Now tensorflow/contrib is enabled in the Bazel Windows build. (https://github.com/tensorflow/tensorflow/pull/16659)

We can start working on setting up kokoro jobs for Bazel Windows build.

- [ ] Github presubmit
- [ ] Github postsubmit
- [ ] Internal presubmit
- [ ] Internal postsubmit

**Comment by meteorcloudy** [comment]
@gunan @yifeif

**Comment by gunan** [comment]
this is all internal work. Let's create an internal bug for this.
