### ISSUE TITLE
tf.python_io.TFRecordWriter() results in "UnknownError: Failed to create a NewWriteableFile"

### ISSUE THREAD

**Issue by sethun** [tensorflow/tensorflow#17553]
### System information

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):**No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 7, 64 Bit**
- TensorFlow installed from (source or binary): **TensorFlow installed from Conda**
- TensorFlow version (use command below): **1.6.0**
- Python version: **Python 3.6.3**
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: **9.1.85**
- GPU model and memory: **NVIDIA GeForce 820M**
- Exact command to reproduce: 
import tensorflow as tf
tf.python_io.TFRecordWriter('C:\\Users\\user_name\\Documents')

import tensorflow as tf
tf.python_io.TFRecordWriter('Any_path')

### Problem
tf.python_io.TFRecordWriter('path') doesn't create output file and returns following error:
_UnknownError: Failed to create a NewWriteableFile: 'path' : Access is denied.
; Input/output error._

### Troubleshooting
Tried with different folders and drives as "path". But error is consistent 

### Source code / logs

import tensorflow as tf
C:\Users\Sethu\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

tf.python_io.TFRecordWriter('C:\\Users\\Sethu\\Documents')
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-2-1fe0cde88225> in <module>()
----> 1 tf.python_io.TFRecordWriter('C:\\Users\\Sethu\\Documents')

~\Anaconda3\lib\site-packages\tensorflow\python\lib\io\tf_record.py in __init__(self, path, options)
    109     with errors.raise_exception_on_not_ok_status() as status:
    110       self._writer = pywrap_tensorflow.PyRecordWriter_New(
--> 111           compat.as_bytes(path), compat.as_bytes(compression_type), status)
    112 
    113   def __enter__(self):

~\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    514             None, None,
    515             compat.as_text(c_api.TF_Message(self.status.status)),
--> 516             c_api.TF_GetCode(self.status.status))
    517     # Delete the underlying status object from memory otherwise it stays alive
    518     # as there is a reference to status from this from the traceback due to

UnknownError: Failed to create a NewWriteableFile: C:\Users\Sethu\Documents : Access is denied.
; Input/output error

**Comment by mrry** [comment]
Is `"C:\Users\Sethu\Documents"` the name of an existing directory on your computer?

**Comment by sethun** [comment]
Yes, it is an existing folder in my computer.

**Comment by mrry** [comment]
That explains the "Access is denied" error. The `path` argument to [`tf.python_io.TFRecordWriter()`](https://www.tensorflow.org/api_docs/python/tf/python_io/TFRecordWriter#__init__) must be a *file* name (typically the name of a file that does not exist) and not a directory name.

**Comment by kazemSafari** [comment]
Thanks you so much mrry. I guess your answer has helped me multiple times. I really hate tensorflow. I will move on to pytorch soon. But thanks again.

**Comment by x007007007** [comment]
I have a same problem , very weird

**Comment by x007007007** [comment]
> 
> 
> That explains the "Access is denied" error. The `path` argument to [`tf.python_io.TFRecordWriter()`](https://www.tensorflow.org/api_docs/python/tf/python_io/TFRecordWriter#__init__) must be a _file_ name (typically the name of a file that does not exist) and not a directory name.

This link could be helpful
https://stackoverflow.com/questions/45893235/tensorflow-tfrecordwriter-access-is-denied

**Comment by orenNelson** [comment]
mrry, thanks as well! Now I see 'c.	[PATH_TO_ANNOTATIONS_FOLDER]/train.record' what this means!  And now it seems so obvious. I'm glad it was a much easier fix than it looked.
