### ISSUE TITLE
tf.train.Saver() protocol buffer saving issue

### ISSUE THREAD

**Issue by Burton2000** [tensorflow/tensorflow#17554]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.4.1 gpu
- **Python version**: 3.5.4
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: Cuda 8.0/Cudnn 6.0
- **GPU model and memory**: Titan xp
- **Exact command to reproduce**: tf.train.Saver()

### Describe the problem
When using tf.train.Saver() if you set max_to_keep=None to keep all checkpoint files created then the protocol buffer saved at 'checkpoint' will only save the name of the latest checkpoint created and not all created checkpoints. 

When you set max_to_keep=N to be any other value then it will save the latest N checkpoint names as intended.

**Comment by michaelisard** [comment]
@rjpower assigning you because I saw you worked on this code recently but please reassign if you know of a better owner.

**Comment by kr-ish** [comment]
Is this not the defined behavior (though perhaps it is not a desired behavior)? From https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/saver.py#L737:

      max_to_keep: Maximum number of checkpoints to keep.  As new checkpoints
        are created, old ones are deleted.  If None or 0, no checkpoints are
        deleted from the filesystem but only the last one is kept in the
        `checkpoint` file.  Presently the number is only roughly enforced.  For
        example in case of restarts more than max_to_keep checkpoints may be
        kept.

So no checkpoint data files should be deleted but only the last one should be in the checkpoint file. Is that not what is happening?

**Comment by Burton2000** [comment]
Yeah that is what is happening. Probably just needs a mention in the documentation then that this happens if it is desired behavior as I didn't find it there, didn't think to look at the source code apologies.

**Comment by kr-ish** [comment]
Agreed, I'll create a pull request shortly to update the docs. However I do wonder if this should be the desired behavior going forward and what the rationale for not keeping all the checkpoints in the checkpoint file is.

**Comment by kr-ish** [comment]
added PR #17712
