### ISSUE TITLE
train on new dataset

### ISSUE THREAD

**Issue by misstong** [tensorflow/tensorflow#17552]
i want to detect people wearing a hat.can i directly label those people wearing hats as a class  and train on this dataset?can cnn distinguish people wearing hats from those who don't?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by misstong** [comment]
thank you for your reply .In my case the fields in the issue template are irrelevant.
Have I written custom code            N/A
OS Platform and Distribution          N/A
TensorFlow installed from               N/A
TensorFlow version                          N/A
Bazel version                                   N/A
CUDA/cuDNN version                    N/A
GPU model and memory                N/A
Exact command to reproduce         N/A

**Comment by soloice** [comment]
@misstong Yes, CNNs can do that.
Btw, this issue is not about TF bugs/feature requests. Please ask it on StackOverflow or other websites.

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
