### ISSUE TITLE
sess.run() returns invisible string for a tf.summary.merge_all() op. 

### ISSUE THREAD

**Issue by anbai106** [tensorflow/tensorflow#17560]
HI, 

I have a problem to read the outpur of sess.run:
here is the code:
`        tf.summary.scalar('Loss', loss)
        tf.summary.scalar('Accuracy', accuracy)
        write_op = tf.summary.merge_all()
       summary_train = sess.run(write_op, feed_dict=feed_dict_train)`
where, write_op is a op from tf.summary.merge_all().

The output **summary_train** is something like: **\n\nLoss??\n\nAccuracy?????** 

Do you have any idea how I can get the numbers for the loss and accuracy from **summary_train**

Look forward to your response

Hao

**Comment by mrry** [comment]
That string is a binary-encoded protocol buffer. If you want to render something more human readable, you'll need to parse it as a `tf.summary.Summary` object:

```python
summary_train = sess.run(write_op, feed_dict=feed_dict_train)

summary_pb = tf.summary.Summary()
summary_pb.ParseFromString(summary_train)
print(summary_pb)
```
