### ISSUE TITLE
sparse variable request or any alternate?

### ISSUE THREAD

**Issue by warisha** [tensorflow/tensorflow#17582]
In tensor flow (TF) , to compute gradients we have to pass some variable. Sparse tensors cannot be used as variables. Can you please tell me is there any solution for sparse matrix gradient ?
N/A
Tensorflow version 1.4

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
