### ISSUE TITLE
s390x build fails with boringssl error

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#17587]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: master
- **Bazel version (if compiling from source)**: 0.11.1
- **CUDA/cuDNN version**: Not used
- **Exact command to reproduce**: bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

TensorFlow master build is failing with below error: 
```
ERROR: /data/TF_tmp/_bazel_root/be3f47674f2731fd84874c35a2feb28b/external/kafka/BUILD:8:1: C++ compilation of rule '@kafka//:kafka' failed (Exit 1)
In file included from external/boringssl/src/include/openssl/ssl.h:145:0,
                 from external/kafka/src/rdkafka_int.h:53,
                 from external/kafka/src/rdkafka_conf.c:29:
external/boringssl/src/include/openssl/base.h:114:2: error: #error "Unknown target CPU"
 #error "Unknown target CPU"
```
We have disabled support for Apache Kafka Platform support through `./configure`.

**Comment by Nayana-ibm** [comment]
@gunan Looks like Apache Kafka support also depends on boringssl. 
Looks similar to  [this](https://github.com/tensorflow/tensorflow/issues/14039#issuecomment-355439575) issue.

**Comment by gunan** [comment]
Thanks for catching this!
The recurrence of this problem just makes me think, is there an alternative SSL library we can substitute for boringSSL on s390x?
Maybe that will be a better fix?

**Comment by yongtang** [comment]
@Nayana-ibm @gunan I updated the PR #17565 so that kafka (and boringSSL dependency) build could be skipped with `with_kafka_support=False`. Please take a look.

**Comment by Nayana-ibm** [comment]
@rohan100jain Now build is successful on s390x. 
Configured with export TF_NEED_KAFKA=0

**Comment by Nayana-ibm** [comment]
Closing the issue 
Thanks,
