### ISSUE TITLE
Split a tensor with Tensor 0-D int32 as num_split argument

### ISSUE THREAD

**Issue by ndohuu** [tensorflow/tensorflow#176]
Hi,

According to the doc, th.split takes a 0-D int32 Tensor as num_split argument but executing :

x = tf.placeholder(tf.float32, [5, None])
numsplit = tf.shape(x)[1]
splits = tf.split(1, numsplit, x)

returns :

"Expected int for argument 'num_split' not  < tensorflow.python.framework.ops.Tensor object at 0x7fcad834f810>"

If the dimension is defined split also returns the same error :

x = tf.placeholder(tf.float32, [5, 30])
numsplit = tf.shape(x)[1]
splits = tf.split(1, numsplit, x)

Same thing with a constant as argument:

x = tf.placeholder(tf.float32, [5, 30])
numsplit = tf.constant(30)
splits = tf.split(1, numsplit, x)

Any ideas ?

**Comment by ndohuu** [comment]
Thinking about this twice, I can't imagine how split could populate the resulting list without having a "hard" number.

**Comment by girving** [comment]
Thanks, that's a documentation bug.  I'll fix it now.  As you point out, the number has to be known at graph construction time since it determines the topology.

**Comment by girving** [comment]
Fixed, will be pushed out in the next repo sync.  Thanks again for the catch!

**Comment by bluemonk482** [comment]
Is this fixed? I have just tested the code provided by the author and it gives an error:

`TypeError: Expected int for argument 'num_split' not <tf.Tensor 'Squeeze_1:0' shape=() dtype=int32>`

tf version: `0.10.0rc0`
