### ISSUE TITLE
TensorBoard tutorial links to the wrong MNIST tutorial and example code

### ISSUE THREAD

**Issue by recolgan** [tensorflow/tensorflow#17600]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: 1.6
- **Python version**: N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

Sorry if this is better suited as an issue for TensorBoard, but since it's about documentation on tensorflow.org I thought it should go here.

The TensorBoard guide at https://www.tensorflow.org/programmers_guide/summaries_and_tensorboard contains example code that it says "is a modification of the [simple MNIST tutorial](https://www.tensorflow.org/tutorials/layers), in which we have added some summary ops." But the tutorial it links to, https://www.tensorflow.org/tutorials/layers, is very different from the example code it gives -- that tutorial uses the tf.layers module to create a CNN, while the example code manually defines a one-hidden-layer fully-connected network. I'm not even sure what the example code is based on, since it doesn't seem that similar to https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/examples/tutorials/mnist/mnist.py. 

At the very least the link should be fixed to point to the correct original example code, but even better would be if the tutorial could be updated to show how to use TensorBoard with a network created with tf.layers.

**Comment by imsheridan** [comment]
Created a PR #17640 to fix this to point to [mnist.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist.py)
