### ISSUE TITLE
Raspberry Pi 3 C++ compiling issue

### ISSUE THREAD

**Issue by 01000001-086** [tensorflow/tensorflow#17618]
### System information
Raspberry Pi 3 running a clean install of latest Raspbian (version November 2017)

Have I written custom code: No
OS Platform and Distribution : Raspbian (version November 2017)
TensorFlow installed from : git cloned the latest version
TensorFlow version: git cloned the latest version
Bazel version: N/A
CUDA/cuDNN version : N/A
GPU model and memory: N/A
Exact command to reproduce: [Tensorflow Makefile for Raspberry Pi](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#raspberry-pi)

### Problem
I am having a problem building the C++ library of Tensorflow.

First I use a USB as a swap by follwing the instructions here:
https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md#2-install-a-memory-drive-as-swap-for-compiling

Then continued on building tensorflow with the instructions below:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#raspberry-pi

I followed all the steps and believed that everything went successfull, 
until I build the library and example using the command below:
```
make -f tensorflow/contrib/makefile/Makefile HOST_OS=PI TARGET=PI \
 OPTFLAGS="-Os -mfpu=neon-vfpv4 -funsafe-math-optimizations -ftree-vectorize" CXX=g++-4.8
```

### Logs
It will ran for quite few hours until it stops and outputs the error below:
```
collect2: error: ld returned 1 exit status
tensorflow/contrib/makefile/Makefile:730: recipe for target '/home/pi/tensorflow/tensorflow/contrib/makefile/gen/bin/benchmark' failed
make: *** [/home/pi/tensorflow/tensorflow/contrib/makefile/gen/bin/benchmark] Error 1
```

The rest of the log can be seen here:
[output_log.txt](https://github.com/tensorflow/tensorflow/files/1799928/output_log.txt)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by kecsap** [comment]
I just completed my project on Github to run C++ inference on Ubuntu and Raspberry Pi. Feel free to grab the prebuilt Debian package and run your inference following my instructions:

https://github.com/kecsap/tensorflow_cpp_packaging

**Comment by 01000001-086** [comment]
@kecsap Thank you. I will try your project. Its a little bit off-topic, would I be able to run the [pi_example](https://github.com/tensorflow/tensorflow/tree/de1334da2c6e074c427d283898450de6e50a605d/tensorflow/contrib/pi_examples) using your project?

**Comment by kecsap** [comment]
@01000001-086 Yes!

I have just added the Raspberry Pi examples from the Tensorflow repo and adapted the README file:

https://github.com/kecsap/tensorflow_cpp_packaging/tree/master/rpi_examples

**Comment by 01000001-086** [comment]
@kecsap I was able to build and make the [example](https://github.com/kecsap/tensorflow_cpp_packaging/tree/master/rpi_examples)
However, I had to ran the command first because it could not the find the needed file. 
```
sudo apt-get install libv4l-dev
```
Anyways, Thanks for your support.

One more thing, I was trying to run my test cpp file but every time I ran the command below to compile.
```
g++ -I/usr/include/tensorflow-cpp -L/usr/lib/tensorflow-cpp  tfCpp1.cpp
```

I get an error.
```
/usr/include/tensorflow-cpp/tensorflow/core/platform/default/mutex.h:25:22: fatal error: nsync_cv.h: No such file or directory
 #include "nsync_cv.h"
```

I believe I am missing something.

**Comment by kecsap** [comment]
Yes because there are more include directories, you can check them in:

/usr/lib/cmake/tensorflow-cpp/TensorFlowCppConfig.cmake

or by building the Rpi example by "make VERBOSE=1".

**Comment by 01000001-086** [comment]
@kecsap Thank you. I was able to compile my test cpp using the command below.
```
 g++ -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public  -L/usr/lib/tensorflow-cpp tfCpp1.cpp
```

Now, I am trying to compile it using cmake.
```
CMAKE_MINIMUM_REQUIRED(VERSION 3.0)

PROJECT(TEST_TF)

SET(CMAKE_CXX_STANDARD 11)

# Find tensorflow-cpp
FIND_PACKAGE(TensorFlowCpp REQUIRED PATHS /usr/lib/cmake/tensorflow-cpp)

# Add the tensorflow-cpp paths to the include directories
INCLUDE_DIRECTORIES(${TENSORFLOWCPP_INCLUDE_DIRS})

# Add a target with your inference codes
ADD_EXECUTABLE(tfCpp1 tfCpp1.cpp)

# Link your application against the shared Tensorflow C++ library
TARGET_LINK_LIBRARIES(tfCpp1 ${TENSORFLOWCPP_LIBRARIES})
```

However, I keep getting an error.
```
/usr/lib/tensorflow-cpp/libprotobuf-tf.so: undefined reference to `deflate'
/usr/lib/tensorflow-cpp/libprotobuf-tf.so: undefined reference to `deflateEnd'
/usr/lib/tensorflow-cpp/libprotobuf-tf.so: undefined reference to `inflateInit2_'
/usr/lib/tensorflow-cpp/libprotobuf-tf.so: undefined reference to `inflate'
/usr/lib/tensorflow-cpp/libprotobuf-tf.so: undefined reference to `deflateInit2_'
/usr/lib/tensorflow-cpp/libprotobuf-tf.so: undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
CMakeFiles/tfCpp1.dir/build.make:95: recipe for target 'tfCpp1' failed
make[2]: *** [tfCpp1] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tfCpp1.dir/all' failed
make[1]: *** [CMakeFiles/tfCpp1.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Can you point out where I missed?

**Comment by kecsap** [comment]
@01000001-086: You can see in the RPi example CMake file the additional "-lz" to the TARGET_LINK_LIBRARIES() what is necessary on the Pi.

**Comment by 01000001-086** [comment]
@kecsap Thanks! I totally missed that. Your project really helped me.

**Comment by tatianashp** [comment]
@kescap Thank you for your help!
