### ISSUE TITLE
Tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory

### ISSUE THREAD

**Issue by jongwun** [tensorflow/tensorflow#17615]
Hi I try to use tensorflow object_detection API

My computer is Mac book pro(version Sierra 10.12.6 )

I follow this youtube :'https://www.youtube.com/watch?v=JR8CmWyh2E8'

and final step, error show up

MacBook-Pro-de-Jongwun:object_detection jongwuni$ python3 train.py --logtostderr --train_dir="/Users/jongwuni/Documents/Jongwunibang/Neural_network/models/object_detection/training" --pipline_config_path="/Users/jongwuni/Documents/Jongwunibang/Neural_network/models/object_detection/training/faster_rcnn_inception_resnet_v2_atrous_coco.config"
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    tf.app.run()
  File "/anaconda/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 106, in main
    overwrite=True)
  File "/anaconda/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 385, in copy
    compat.as_bytes(oldpath), compat.as_bytes(newpath), overwrite, status)
  File "/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
