### ISSUE TITLE
Does TensorFlow 1.1 support CUDA 9.1?  

### ISSUE THREAD

**Issue by LANRRI** [tensorflow/tensorflow#17621]
Does TensorFlow 1.5 support CUDA 9.1? if not , shoud i degrade my cuda or upgrade tensorflow?

**Comment by LANRRI** [comment]
TensorFlow-gpu 1.1

**Comment by agdownes** [comment]
How are you installing tensorflow? The current prebuilt binaries 1.5 and 1.6 are built against CUDA 9.0 so you will need this version of CUDA installed. You can use CUDA 9.1 if you compile tensorflow from source and specify that version during the configuration step.

**Comment by xysmlx** [comment]
No, tensorflow-gpu supports CUDA 9 since 1.5. Tensorflow < 1.5 is unable to be compiled with CUDA 9. I have tried to compile 1.4 with CUDA9, but I failed.
See the tested source configurations in the following site.
https://www.tensorflow.org/install/install_sources#tested_source_configurations

**Comment by LANRRI** [comment]
@xysmlx thanks a lot . here i met a new problem  . i've installed tensorflow-gpu with cuda 8.0 and i write a simple program, but it's freezed when running session = tf.session(). when use keras to train data. it's also freezed like this. 
![image](https://user-images.githubusercontent.com/16147268/37582552-883f12e2-2b88-11e8-816d-534b8cc018ee.png)

**Comment by xysmlx** [comment]
@LANRRI These information say that tensorflow can get a higher performance when compiled with these instructions but tensorflow can also run normally without them. These information do not affect your programs. If there are problems, please check your codes.

**Comment by LANRRI** [comment]
@xysmlx i mean when the code run to session = tf.session()  the thread is freezed with no error or exception in 1 hour . the program is no longer processing.

simply, just run one line code "import tensorflow as tf ; session = tf.session()"  the problem is still there.

**Comment by xysmlx** [comment]
@LANRRI If you cannot run the validation code, there must be errors in your installation. I recommend you to reinstall the tensorflow in this case.

[https://www.tensorflow.org/install/install_linux#validate_your_installation](https://www.tensorflow.org/install/install_linux#validate_your_installation)

```
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))
```

**Comment by LANRRI** [comment]
@xysmlx  thank you
