### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory

### ISSUE THREAD

**Issue by jongwun** [tensorflow/tensorflow#17620]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
 Mac OS Sierra 10.12.6
- **TensorFlow installed from (source or binary)**:
 source
- **TensorFlow version (use command below)**:
1.4.0
- **Python version**: 
python3
- **Bazel version (if compiling from source)**:
sorry, I don't know
- **GCC/Compiler version (if compiling from source)**:
sorry, I don't know
- **CUDA/cuDNN version**:
sorry, I don't know
- **GPU model and memory**:
radeon pro 560 4G

### Describe the problem
I try to use object detection using tensorflow API 
I follow this youtube
https://www.youtube.com/watch?v=JR8CmWyh2E8
but there is a error

### Source code / logs
MacBook-Pro-de-Jongwun:~ jongwuni$ cd /Users/jongwuni/Documents/Jongwunibang/Neural_network/models
MacBook-Pro-de-Jongwun:models jongwuni$ cd object_detection
MacBook-Pro-de-Jongwun:object_detection jongwuni$ python3 train.py --logtostderr --train_dir="/Users/jongwuni/Documents/Jongwunibang/Neural_network/models/object_detection/training" --pipline_config_path="/Users/jongwuni/Documents/Jongwunibang/Neural_network/models/object_detection/training/faster_rcnn_inception_resnet_v2_atrous_coco.config"

Traceback (most recent call last):
  File "train.py", line 163, in <module>
    tf.app.run()
  File "/anaconda/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 106, in main
    overwrite=True)
  File "/anaconda/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 385, in copy
    compat.as_bytes(oldpath), compat.as_bytes(newpath), overwrite, status)
  File "/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by isrugeek** [comment]
@jongwun  did you fix the issue?
Thanks

**Comment by thanhtu19392** [comment]
I met the same issue. Has anyone fixed this yet? Thanks

**Comment by isrugeek** [comment]
@thanhtu19392  are you using external HDD as a path or storage?

**Comment by thanhtu19392** [comment]
I fixed the error. It's an error from my side. Thanks anw

**Comment by ProjectDent** [comment]
@thanhtu19392 I'm having this error - how did you fix it?
