### ISSUE TITLE
The value changes incorrectly after assignment using tf.assign

### ISSUE THREAD

**Issue by whaoer** [tensorflow/tensorflow#17644]
**System information**
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
TensorFlow installed from (source or binary): Binary
TensorFlow version (use command below): 1.4.0
Python version: Python 2.7.12
Bazel version (if compiling from source): N/A
GCC/Compiler version (if compiling from source): N/A
CUDA/cuDNN version: 8.0/6.0
GPU model and memory: GTX 960, 2G
Exact command to reproduce: N/A

**ISSUE**
data = load("new.mat")
print data
tf.assign(old, data)
print old

But：    old!=data
Ex. 0.081345705——>0.081345707

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by soloice** [comment]
I guess this is a float precision problem.
Because you name the file "new.mat", I suppose it is dumped by MATLAB and is of 64-bit precision.
While you load it, you may convert it to 32-bit precision, thus you get an approximation.

Actually, you can verify this with the C programming language:

```
#include <iostream>
#include <iomanip>
using namespace std;

int main() {
double x = 0.081345705;
float y = (float) x;
cout << setprecision(8) << x << " " << y << endl;
}
```
You will see that `x=0.081345705` and `y=0.081345707`.
