### ISSUE TITLE
Feature request: tf.as_dtype(float) should work just as tf.as_dtype('float')

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#17641]
In NumPy, `np.dtype(float)` works just the same as `np.dtype("float")`.

In TensorFlow `tf.as_dtype("float")` works but `tf.as_dtype(float)` crashes with `TypeError: Cannot convert value <class 'float'> to a TensorFlow DType.`.

Is there a particular reason for this behaviour or was it just overlooked?

(same error for other builtins such as `int` and `complex`)

**Comment by yongtang** [comment]
I added  #17652 as an effort to support built-in types for `tf.as_dtype`.

I think one potential issue is that python's `float` is implemented as C `double`, so there are some discrepancies here.

Not sure if this is the way to go, but will let tensorflower's to make a call.

**Comment by carlthome** [comment]
Wow, you're one fast potato @yongtang! 😃

>I think one potential issue is that python's float is implemented as C double, so there are some discrepancies here.

Yeah, and I guess it can be a little confusing to have `tf.as_dtype("float")` be 32-bit while `tf.as_dtype(float)` would give doubles. I'd probably stick with tf.float32 [here](https://github.com/tensorflow/tensorflow/pull/17652/files#diff-85e323da48079f7831b7e9f6ec24cda2R655) for consistency, despite not matching NumPy (too late for that anyway), especially considering that the vast majority of TensorFlow users assume single precision floats (e.g. for GPU model training).
