### ISSUE TITLE
How can I gdb tfcompile by using bazel build?

### ISSUE THREAD

**Issue by xcv9685** [tensorflow/tensorflow#17647]
tfcompile is a binary file to compile an inference graph into executable code for tensorflow XLA which created by bazel build.
If I want to gdb tfcompile file on ubuntu 16.04,  it will return message 

    Reading symbols from /PWD/tfcompile...(no debugging symbols found)...done.

It seem that should make bazel compile with something flag like -g?
I have tried to use 
   
    bazel build XXX --compilation_mode=dbg

but there seems not change anything.

How can I resolve this question?

by the way , I'm working on Ubuntu 16.04, bazel version 0.8.1 tensorflow r1.0

Thanks for any help!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by neohemstar** [comment]
@xcv9685
Is this problem solved? I have met the similar issue,.though I have compiled the tensorflow/examples/label_image as follows

`bazel build --compilation_mode=dbg //tensorflow/examples/label_image/..
`

but the the final produced binary label_image has no debug symbols .

> Reading symbols from ./label_image...(no debugging symbols found)...done.
> (gdb) b main
> Breakpoint 1 at 0x8b39ab
> (gdb) r
> Starting program: /home/neo/.cache/bazel/_bazel_neo/b79e78d41078616f7b591dd11d552dc0/execroot/org_tensorflow/bazel-out/k8-dbg/bin/tensorflow/examples/label_image/label_image

**Comment by neohemstar** [comment]
@xcv9685 
with --strip=never flag ,the  binary was build with debug symbol.
appreciate for your help
