### ISSUE TITLE
Multi-dimensional argmax and one-hot

### ISSUE THREAD

**Issue by RasmooL** [tensorflow/tensorflow#1766]
This is a feature request, unless someone can show me how the following might be done with the current API.

Say I have a tensor WxHxD, and I want to keep only the largest element in each WxH slice, setting the rest to zero. These indices could be obtained in numpy by doing something like
`(row,col) = np.unravel_index(A.argmax(), A.shape)`
on each slice WxH slice A.
Collecting the D row and column indices, I could create a boolean mask using advanced indexing
`mask[rows,cols, range(D)] = 1`
Then, an elementwise multiplication between the WxHxD tensor and the mask gives the desired tensor.

**Comment by martinwicke** [comment]
This should be possible using reshape, argmax, one_hot, reshape, cwise_mul. If you need help with the exact invocation, stackoverflow is probably a better place.

**Comment by petered** [comment]
For those searching for this, here is the place: 

```
def tf_argmax_nd(tensor):
    """ Given an D-dimensional tesnsor, find the indices of the argmax (a length-D integer vector) """
    return tf.unravel_index(tf.argmax(tf.reshape(tensor, (-1, ))), dims=tensor.shape)


def tf_argmax_onehot(tensor):
    """ Given a tensor, return a boolean tensor of the same shape with only the argmax element true """
    ixs = tf_argmax_nd(tensor)
    return tf.tensor_scatter_nd_update(tf.zeros_like(tensor, dtype=bool), indices=ixs[None, :], updates=tf.ones((1, ), dtype=bool))

```
