### ISSUE TITLE
tf.matrix_solve_ls: Documentation corrupt?

### ISSUE THREAD

**Issue by Hoeze** [tensorflow/tensorflow#17663]
Hi,
I just found tf.matrix_solve_ls and read its documentation at https://www.tensorflow.org/api_docs/python/tf/matrix_solve_ls :
![grafik](https://user-images.githubusercontent.com/1200058/37315800-cbf13e16-265b-11e8-9ead-727fd6d95c7d.png)
Seems like there are some markdown errors...

Have I written custom code: No
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by skye** [comment]
@MarkDaoust

**Comment by imsheridan** [comment]
Created a PR #18022 to fix this math equation format issue
