### ISSUE TITLE
Logging frequency hardcoded in tf.estimator

### ISSUE THREAD

**Issue by martius-lab** [tensorflow/tensorflow#17676]
### Describe the problem

The logging frequency of the default LoggingTensorHook of tf.Estimator is hardcoded to 100 steps (see lines 828-837 in [https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/python/estimator/estimator.py]). It would really help me to unclutter my logs if I had access to this value (my training is fast).

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by facaiy** [comment]
How about creating your own [`tf.train.LoggingTensorHook`](https://www.tensorflow.org/versions/master/api_docs/python/tf/train/LoggingTensorHook) and passing them to `Estimator.train(hooks=your_log_hook)`?

**Comment by facaiy** [comment]
Sounds like a problem, cc @ispirmustafa

**Comment by ispirmustafa** [comment]
https://github.com/tensorflow/tensorflow/pull/17157 is addressing it.
