### ISSUE TITLE
graph_def.ParseFromString>google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by AlexDag** [tensorflow/tensorflow#17683]
I have the model fine tuned Inception model with my images set data by tensorflow/examples/image_retraining/retrain.py. Then, running python tensorflow/examples/label_image/label_image.py  for classification the custom image I get error:        `graph_def.ParseFromString(f.read())`
`google.protobuf.message.DecodeError:` Error parsing message.
Tensorflow version 1.6.0 , GPU build. 
I have other fine tuned Inception model  that running without this error:
` 95781819 Mar 12 19:37 carvajal_model.pb`  * this run with Parser error
` 87458742 Mar  1 14:33 flow_model.pb`
` 87622663 Mar  2 17:58 grocery_model.pb`
There is not a  big difference  the size of the model files , the problem model file has size 95m and well running models have  87m.

Trace >
`Traceback (most recent call last):
  File "./label_image.py", line 117, in <module>
    graph = load_graph(model_file)
  File "./label_image.py", line 30, in load_graph
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message`

Are some advices about ?

**Comment by gmaggess** [comment]
@AlexDag, were you able to find a solution. I'm facing the same issue.

**Comment by AlexDag** [comment]
@gmaggess , the my case was easy> by error, it was used the model from tensorflow train.py message:"INFO:tensorflow:SavedModel written to: b'/tmp/saved_models/1/**saved_model.pb'"**. The fine tuned model  is **/tmp/output_graph.pb**

**Comment by Jason-xin** [comment]
Sorry, I don't understand, can you tell me how you solve this problem in detail? thanks

**Comment by AlexDag** [comment]
@Jason-xin,  for the inferencing(object classification)  we need fine tuning model, the binary file. It was made by train.py on folder /tmp/***(as my train process config) . I had error by using /tmp/saved_models/1/saved_model.pb. The tuned model for object classification is /tmp/output_graph.pb.

**Comment by nimaid** [comment]
For me, I was trying to use `saved_model/saved_model.pb`, which gives that protobuf error. I had to use `frozen_inference_graph.pb`, and then I was able to load it. (I'm using the UFF conversion library, it also calls something similar to `graph_def.ParseFromString(f.read())`)

**Comment by seongkyun** [comment]
is anyone solved this problem??
I have exactly same problem.

in my case,
I have my pytorch model and converted to onnx model.
Nextly, it is converted to tf2.3.1 saved_model.pb (including variables folder with data files) type model and I checked it ran perfectly.

Now, I converted it to frozen.pb type model following here: https://stackoverflow.com/questions/59657166/convert-frozen-model-pb-to-savedmodel
and finally got the frozen_model.pb file.

Now, I am trying to run frozen_model.pb on my tensorflow 2.3.1 but got same error.

<pre><code>
...
graph_def = tf.compat.v1.GraphDef()
loaded = graph_def.ParseFromString(open('path/to/frozen/pb/file/frozen_model.pb','rb').read())
...
</code></pre>

and got following error

<pre><code>
Traceback (most recent call last):
  File "run_frozen.py", line 392, in <module>
    loaded = graph_def.ParseFromString(open(PB_MODEL_PATH,'rb').read())
google.protobuf.message.DecodeError: Error parsing message
</code></pre>

is anyone solved this problem?

**Comment by eirikaso** [comment]
@seongkyun 
Did you solve this issue?
