### ISSUE TITLE
How to convert .pb file to .ckpt file

### ISSUE THREAD

**Issue by dinglong1020** [tensorflow/tensorflow#17699]
How to convert .pb file to .ckpt file??
   as following code raise error:  ValueError: No variables to save

#!/usr/bin/env python
#coding: utf-8

import tensorflow as tf
import argparse 

# Pass the filename as an argument
parser = argparse.ArgumentParser()
parser.add_argument("--frozen_model_filename", default="frozen_inference_graph.pb", type=str, help="Pb model file to import")
args = parser.parse_args()

# We load the protobuf file from the disk and parse it to retrieve the 
# unserialized graph_def
with tf.gfile.GFile(args.frozen_model_filename, "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

    #saver=tf.train.Saver()
    with tf.Graph().as_default() as graph:

        tf.import_graph_def(
            graph_def,
            input_map=None,
            return_elements=None,
            name="prefix",
            op_dict=None,
            producer_op_list=None
        )
        sess = tf.Session(graph=graph)
        saver = tf.train.Saver()
        save_path = saver.save(sess, "model.ckpt")
        print("Model saved to chkp format")

**Comment by dinglong1020** [comment]
I have save the model to protobuf  (pb and pbtxt,  as Protobuf.pb and Text_Protobuf.pbtxt)

**Comment by facaiy** [comment]
As far as I known, pb file contains only graph information, while ckpt file needs both graph and variable. So I don't think it sounds feasible.

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Giorat** [comment]
@angersson I posted it to StackOverflow, could you help out posting there the code to convert pb to ckpt ?

**Comment by Cruisetang** [comment]
@dinglong1020 have you got it done?I also want to convert pb into ckpt file,but failed finnally. If you kown how to fix it now,please tell me,thanks!

**Comment by jycccccccc** [comment]
Has anyone known how to do it? I also want to convert .pb to a ckpt file.

**Comment by xiaoyuan129** [comment]
Does anyone know how to solve this problem?

**Comment by smartcatdog** [comment]
Has anyone known how to do it? I also want to convert .pb to a ckpt file.thx

**Comment by suke27** [comment]
is it resolved, i also want to know how to convert pb to ckpt

**Comment by sanghyeonp** [comment]
Has this been solved yet?

**Comment by MrRights** [comment]
Has anyone known how to do it? I also want to convert .pb to a ckpt file.
