### ISSUE TITLE
Suggestion:Tensor add the finalize method to close tensor object after GC

### ISSUE THREAD

**Issue by raintung** [tensorflow/tensorflow#17708]
System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): Master
Python version: 3.6
Bazel version (if compiling from source): N/A
GCC/Compiler version (if compiling from source): N/A
CUDA/cuDNN version: None
GPU model and memory: None
Exact command to reproduce: Run the snippet below.

Describe the problem
Tensor object should initiative call close method to release native memory, but the document don't have any reference to mention this important function.
To avoid some guy to forget call this method, suggest invoke close method in the finalize method that let GC try compensate it at last.
`Public void finalize(){
close()
}`

**Comment by tatianashp** [comment]
I apologize but I am having a hard time understanding what the problem is. Could you please clarify what feature you are suggesting?

**Comment by raintung** [comment]
Tensor object should be initiative invoked the closed method if you don't want use the tensor. You can n't expect the GC to collect this object otherwise will occur the memory leak.
But I  don't see any reference to mention this important behave in the document, it is very dangerous. In my product environment, the developer forget trigger the close function, the product meet OOM and crash last.
To compensate this, I suggest in the finalize method (tensor.java) to close the tensor object,  to avoid the developer forget closing the tensor object. At last, GC will trigger the finalize the method to close the tensor object.

**Comment by tatianashp** [comment]
@asimshankar Do you agree with this proposal?

**Comment by asimshankar** [comment]
I'm tempted to avoid a finalizer (see ["Effective Java", Item 7](http://www.informit.com/articles/article.aspx?p=1216151&seqNum=7) for various reasons).

The `Tensor` class [implements the `AutoCloseable` interface](https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/java/src/main/java/org/tensorflow/Tensor.java#L45), which is one indication (often picked up by IDEs) that `close()` should be invoked. We [mention this in the javadoc as well](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/Tensor.java#L35).

So, I'd not like to introduce a finalizer. However, I'm very open to suggestions on how to make this easier to discover/harder to mess up.

Thanks!
