### ISSUE TITLE
Error:  Executor failed to create kernel. No registered 'Snapshot' OpKernel for GPU devices,while running image label example

### ISSUE THREAD

**Issue by GilesCJ** [tensorflow/tensorflow#17752]
### System information
- OS Platform: Windows10
- TensorFlow installed from source  (GPU support)
- Python version: 3.5
- Compiler version : Microsoft Visual Studio 2015 x64
- CUDA/cuDNN version:CUDA9.0/cuDNN7.0
- GPU: GTX 1070 8G
-CMake settings:  
![image](https://user-images.githubusercontent.com/13750472/37500096-84403974-2902-11e8-8e1d-2a540d3a03b5.png)

### Problem
  I successfully built tensorflow.lib and tensorflow.dll, then I linked these to my visual studio project.Everything goes well when I run the example code which does matrix multiplication (the example code on:https://joe-antognini.github.io/machine-learning/windows-tf-project)
  But when I tried to run the Label_Image example code(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/main.cc), I got the error:
![image](https://user-images.githubusercontent.com/13750472/37500237-47decb84-2903-11e8-8bcd-670f4976fb66.png)
`E C:\tensorflow_gpu\tensorflow\tensorflow\core\common_runtime\executor.cc:644] Executor failed to create kernel. Not found: No registered 'Snapshot' OpKernel for GPU devices compatible with node Subtract = Snapshot[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ResizeBilinear)
    .  Registered:  device='CPU'; T in [DT_INT64]device='CPU'; T in [DT_INT32]
device='CPU'; T in [DT_UINT16]
device='CPU'; T in [DT_INT16]
device='CPU'; T in [DT_UINT8]
device='CPU'; T in [DT_INT8]
device='CPU'; T in [DT_HALF]
device='CPU'; T in [DT_BFLOAT16]
device='CPU'; T in [DT_FLOAT]
device='CPU'; T in [DT_DOUBLE]
device='CPU'; T in [DT_COMPLEX64]
device='CPU'; T in [DT_COMPLEX128]
device='CPU'; T in [DT_BOOL]
     [[Node: Subtract = Snapshot[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ResizeBilinear)]]
2018-03-14 17:13:05.408206: E Image_Label.cpp:385] Not found: No registered 'Snapshot' OpKernel for GPU devices compatible with node Subtract = Snapshot[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ResizeBilinear)
    .  Registered:  device='CPU'; T in [DT_INT64]
device='CPU'; T in [DT_INT32]
device='CPU'; T in [DT_UINT16]
device='CPU'; T in [DT_INT16]
device='CPU'; T in [DT_UINT8]
device='CPU'; T in [DT_INT8]
device='CPU'; T in [DT_HALF]
device='CPU'; T in [DT_BFLOAT16]
device='CPU'; T in [DT_FLOAT]
device='CPU'; T in [DT_DOUBLE]
device='CPU'; T in [DT_COMPLEX64]
device='CPU'; T in [DT_COMPLEX128]
device='CPU'; T in [DT_BOOL]
     [[Node: Subtract = Snapshot[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ResizeBilinear)]]`

I found out the code stopped at:
`TF_RETURN_IF_ERROR(session->Run({ inputs }, { output_name }, {}, out_tensors));`
in
`Status ReadTensorFromImageFile(const string& file_name, const int input_height,
    const int input_width, const float input_mean,
    const float input_std,
    std::vector<Tensor>* out_tensors)`

Does anyone know how to fix this problem??

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow version
Bazel version
GPU model and memory
Exact command to reproduce

**Comment by GilesCJ** [comment]
@tensorflowbutler 
Have I written custom code: no, using example code only
OS Platform and Distribution: Windows10
TensorFlow version: v1.7
Bazel version: N/A
GPU model and memory:  nvidia geforce 1070 8G
Exact command to reproduce: N/A, the error code is from visual studio project after build and run the example code

Thanks!

**Comment by poxvoculi** [comment]
The error says that the SnapshotOp kernel is not available for GPU.  It's a relatively new kernel.  You said you compiled from source, so I believe this kernel should have compiled for GPU.  @rmlarsen do you see anything wrong with the application of this kernel?

**Comment by rancheng** [comment]
Same problem with Win10 and tf-nightly-gpu installed.

**Comment by btud** [comment]
Same problem here. I'm on Win10 and I've compiled this yesterday (19MAR) using latest sources from https://github.com/tensorflow/tensorflow.git. Built using cmake following instructions from 
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake.

The full error is:
2018-03-20 17:34:41.133280: I D:\temp\tensorflow\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6522 MB memory) -> physical GPU (device: 0, name: GeForce GTX 880M, pci bus id: 0000:01:00.0, compute capability: 3.0)
2018-03-20 17:34:53.281846: E D:\temp\tensorflow\tensorflow\tensorflow\core\common_runtime\executor.cc:644] Executor failed to create kernel. Not found: No registered 'Snapshot' OpKernel for GPU devices compatible with node conv1/truncated_normal = Snapshot[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1/truncated_normal/mul)

**Comment by poxvoculi** [comment]
@btud did you try the uninstall/reinstall suggested by @rancheng ?

**Comment by GilesCJ** [comment]
Is this problem only related to the tensorflow branch:master?
How can I get the lastest tensorflow-gpu packages besides cloning from https://github.com/tensorflow/tensorflow.git and build it with cmake and MCVS 2015 ?
@rancheng Did you get the source code else where?

**Comment by btud** [comment]
@poxvoculi , I tried installing the prebuilt package (hope I understood correctly what @rancheng was suggesting) using "pip3 install --upgrade tensorflow-gpu". It seems the default tensorflow-gpu requires the exact 9.0 version of CUDA. I have 9.1 installed - this is what I built against.  So with prebuilt package It fails even for a hello world program - the error is: ImportError: Could not find 'cudart64_90.dll. Not sure if multiple cuda versions can coexist on windows, so I may have to downgrade to 9.0 and then try again.

**Comment by GilesCJ** [comment]
What if I'm trying to build C++ dynamic library?

**Comment by mrry** [comment]
@GilesCJ What version of TensorFlow (exact git commit) are you trying to build? @jhseu recently fixed this for the Windows build in d392b1c9ebf131b9ac64ff289d26e43afea21c10, which as far as I can tell is only on the r1.7 branch.

@yifeif @jhseu Does this fix need to be backported to the master branch?

**Comment by jhseu** [comment]
Yeah, we usually merge the r1.7 branch back into master sometime near the final release.

**Comment by GilesCJ** [comment]
@mrry  I've rebuild master three days ago, and the problem remains. I'll try to build r1.7 today and see how it goes. Is this problem possible related to static library or dynamic library??

**Comment by mrry** [comment]
As far as I understand, the problem affects all versions of the GPU build using Windows/CMake since the snapshot op was added.

**Comment by GilesCJ** [comment]
@mrry The problem is solved when I build the library with r1.7 branch!! Thank you guys very much!
Will r1.7 merge to the master?? Or I'll have to use r1.7 from now on?
