### ISSUE TITLE
How to update columns in tf.Values

### ISSUE THREAD

**Issue by qwesdfok** [tensorflow/tensorflow#17768]
I use tf.scatter_nd_update() method to update lines, but I not find any method to update columns. So I was wondering whether has a convenient way to update columns? 

For example, data=tf.Values(tf.zeros([10,100])), and I want to update data with "data[:,0]=tf.ones([10])" or other methods like tf.scatter_nd_update.

I will appreciate it if anyone can help me!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by qwesdfok** [comment]
@angersson 

Thank you for your response. I think it may become a feature, because the numpy lib support columns opertaions and there is lines opertaions in tensorflow. It might be confused that tf is not support columns operations and we have to use while_loop to update data. I think it might be not convenient.

So, if you ( or your team) have a plan to update operations, it might be a good attempt to add columns operations.
