### ISSUE TITLE
Should this error message be a bracket instead of parentheses ?

### ISSUE THREAD

**Issue by arthurbarros** [tensorflow/tensorflow#17777]
> Received a label value of 1 which is outside the valid range of [0, 1).

Am I reading it wrong? or it should be `[0, 1]` insteado fo `[0, 1)` ?

https://github.com/tensorflow/tensorflow/blob/982549ea3423df4270ff154e5c764beb43d472da/tensorflow/core/kernels/sparse_xent_op.cc#L45

**Comment by mrry** [comment]
`[0, 1)` is the interval `0 <= x < 1`, which 1 is outside. `[0, 1]` is the interval `0 <= x <= 1`, which 1 is inside, and so changing it would not be correct.
