### ISSUE TITLE
TensorFlowInferenceInterface.feed() fails to accept multi-dimensional input

### ISSUE THREAD

**Issue by hoonkai** [tensorflow/tensorflow#17791]
### Describe the problem

My understanding is that `TensorFlowInferenceInterface.feed()` takes a 1D float array `float[]` as input. But what happens if the `.pb` model/graph needs a multi-dimensional array, which is fairly common? For instance, if the model was trained using Keras, the input dimension would be 4. If an image was flattened to become a 1D array, it'd raise an error. Must the dimensionality of the input of the graph be 1?

### Source code / logs

```java
float[] floatValues;
TensorFlowInferenceInterface inferenceInterface;
int inputSize;
String inputName;
...
inferenceInterface.feed(inputName, floatValues, 1, inputSize, inputSize, 3);
```

Gives the error:

`java.lang.IllegalArgumentException: input must be 4-dimensional`

**Comment by glenkalarikkal** [comment]
could you tell us the solution, please?
