### ISSUE TITLE
Request: dynamic RNN in bidirectional_rnn()

### ISSUE THREAD

**Issue by zhangjiajie** [tensorflow/tensorflow#1779]
The bidirectional_rnn() is not taking the advantages of dynamic_rnn(), it runs into memory issues for even moderate length of time steps. I guess this should be really easy to implement, but a really big help for people using the bidirectional version.

Thanks!

Jiajie

**Comment by zhangjiajie** [comment]
I see why this is not implemented yet, reverse the inputs is nasty with current code ....

**Comment by Smerity** [comment]
Until this request is implemented, anyone who is interested and impatient can roll their own bidirectional dynamic RNN relatively simply. It still has the nasty reverse input aspect but it works and can likely be swapped out for future implementations relatively simply. `dynamic_rnn` is a life saver when your RNN sequence is many hundreds of steps long.

For [fwd + bwd] concatenated vectors:
```
fwd_outputs, _ = rnn.dynamic_rnn(cell, embeddings, sequence_length=self.input_lengths, dtype=tf.float32, time_major=False)
bwd_embeddings = tf.reverse_sequence(embeddings, seq_lengths=self.input_lengths, seq_dim=1)
with tf.variable_scope('Bwd'):
    bwd_outputs, _ = rnn.dynamic_rnn(cell, bwd_embeddings, sequence_length=self.input_lengths, dtype=tf.float32, time_major=False)
rnn_outputs = fwd_outputs + bwd_outputs
```

**Comment by jihunchoi** [comment]
It seems that `tf.reverse_sequence` now works with partly unknown shape.
Is anybody working on this?

**Comment by girving** [comment]
@ebrevdo: Should I leave this one assigned to you?

**Comment by ebrevdo** [comment]
Sure, I'll review the PR.

**Comment by ebrevdo** [comment]
This has been submitted.
