### ISSUE TITLE
Raspbian 9 (Stretch): Failed to load native TensorFlow runtime

### ISSUE THREAD

**Issue by Lexicographical** [tensorflow/tensorflow#17790]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No. Simply calling "import tensorflow" already crashes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Raspbian GNU/Linux 9 (Stretch)
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: TensorFlow 1.6.0
- **Python version**: Python 3.5.3
- **Bazel version (if compiling from source)**: Bazel 0.11.1
- **GCC/Compiler version (if compiling from source)**: GCC 6.3.0 20170124
- **CUDA/cuDNN version**: I didn't install with CUDA support
- **GPU model and memory**: n/a
- **Exact command to reproduce**: "import tensorflow" in the Python environment

### Describe the problem
I built TensorFlow on Raspbian Linux for the Raspberry Pi 3 Model B. The problem is that when I try to import it in Python, the program instantly crashes, saying: "Failed to load native TensorFlow runtime." The full traceback is below.

### Source code / logs
Only need to call "import tensorflow" on Python3 to reproduce the traceback below:

```
Traceback (most recent call last): File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in from tensorflow.python.pywrap_tensorflow_internal import * File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in _pywrap_tensorflow_internal = swig_import_helper() File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description) File "/usr/lib/python3.5/imp.py", line 242, in load_module return load_dynamic(name, filename, file) File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic return _load(spec) ImportError: /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow9ConcatCPUINS_8bfloat16EEEvPNS_10DeviceBaseERKSt6vectorISt10unique_ptrINS_6TTypesIT_Li2EiE11ConstMatrixESt14default_deleteIS9_EESaISC_EEPNS8_6MatrixE
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last): File "idex.py", line 1, in import gui File "/home/pi/Desktop/IDEX/scripts/gui.py", line 10, in import fun_util File "signlang/fun_util.py", line 3, in import tensorflow as tf File "/usr/local/lib/python3.5/dist-packages/tensorflow/init.py", line 24, in from tensorflow.python import * # pylint: disable=redefined-builtin File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/init.py", line 49, in from tensorflow.python import pywrap_tensorflow File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in raise ImportError(msg) ImportError: Traceback (most recent call last): File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in from tensorflow.python.pywrap_tensorflow_internal import * File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in _pywrap_tensorflow_internal = swig_import_helper() File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description) File "/usr/lib/python3.5/imp.py", line 242, in load_module return load_dynamic(name, filename, file) File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic return _load(spec) ImportError: /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow9ConcatCPUINS_8bfloat16EEEvPNS_10DeviceBaseERKSt6vectorISt10unique_ptrINS_6TTypesIT_Li2EiE11ConstMatrixESt14default_deleteIS9_EESaISC_EEPNS8_6MatrixE

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions. Include the entire stack trace above this error message when asking for help.
```

**Comment by Lexicographical** [comment]
Hello :) May I ask if there's any progress on this issue? Thanks.

**Comment by drpngx** [comment]
The error is that you're missing the following symbol:
```
void tensorflow::ConcatCPU<tensorflow::bfloat16>(tensorflow::DeviceBase*, std::vector<std::unique_ptr<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix, std::default_delete<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix> >, std::allocator<std::unique_ptr<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix, std::default_delete<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix> > > > const&, tensorflow::TTypes<tensorflow::bfloat16, 2, int>::Matrix*)
```
It was probably built incorrectly. How did you build?

**Comment by Lexicographical** [comment]
I built using this command:

bazel build -c opt --copt="-mfpu=neon-vfpv4" --copt="-funsafe-math-optimizations" --copt="-ftree-vectorize" --copt="-fomit-frame-pointer" --local_resources 1024,1.0,1.0 --verbose_failures tensorflow/tools/pip_package:build_pip_package

Specifically, I followed the tutorial here:

https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md

**Comment by Lexicographical** [comment]
Hello. I tried building and installing again following the instructions on the tensorflow website for building from source and I'm getting the same error.

First I cloned the repo
`git clone https://github.com/tensorflow/tensorflow `

Then I configured it using
`./configure`
I selected
`/usr/bin/python3`
and its respective default dist-packages location. For the other options, I said yes to using jemalloc and then no to all the others. I left the -march=native part as default.

I then built using:
`bazel build --config=opt --local_resources 1024,1.0,1.0 //tensorflow/tools/pip_package:build_pip_package`

Then, I built the pip package using
`bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg`

Then, I installed the pip package via:
`sudo pip3 install /tmp/tensorflow_pkg/tensorflow-1.7.0rc1-cp35-cp35m-linux_armv7l.whl`

Afterwards, when I opened the python terminal in a separate directory and tried to import tensorflow, I got the same error.

**Comment by drpngx** [comment]
Can you try with `alwayslink = 1` [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/BUILD#L155)?

**Comment by Lexicographical** [comment]
I tried building it again but it fails with the following error (I added the --verbose_failures option):
`ERROR: /home/pi/Desktop/tensorflow/tensorflow/contrib/lite/toco/BUILD:391:1: Linking of rule '//tensorflow/contrib/lite/toco:toco' failed (Exit 1): gcc failed: error executing command
  (cd /home/pi/.cache/bazel/_bazel_pi/0a9cb2a29ff2847422358ab74afe8d8d/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/local/lib/python3.5/dist-packages \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
  /usr/bin/gcc -o bazel-out/arm-py3-opt/bin/tensorflow/contrib/lite/toco/toco '-Wl,-rpath,$ORIGIN/../../../../_solib_arm/_U_S_Stensorflow_Scontrib_Slite_Stoco_Ctoco___Utensorflow' -Lbazel-out/arm-py3-opt/bin/_solib_arm/_U_S_Stensorflow_Scontrib_Slite_Stoco_Ctoco___Utensorflow '-Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..,-rpath,$ORIGIN/../..,-rpath,$ORIGIN/../../..' -Wl,-z,notext -Wl,-z,notext -Wl,-z,notext -Wl,-z,notext -Wl,-z,notext -Wl,-z,notext -Wl,-z,notext -Wl,-z,notext -Wl,-z,notext -Wl,-z,notext -Wl,-z,notext -Wl,-z,notext -Wl,-z,notext -Wl,-z,notext -Wl,-z,notext -pthread '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,@bazel-out/arm-py3-opt/bin/tensorflow/contrib/lite/toco/toco-2.params)
bazel-out/arm-py3-opt/bin/tensorflow/core/kernels/_objs/list_kernels/tensorflow/core/kernels/list_kernels.o:list_kernels.cc:function tensorflow::TensorListStack<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'void tensorflow::ConcatCPU<tensorflow::bfloat16>(tensorflow::DeviceBase*, std::vector<std::unique_ptr<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix, std::default_delete<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix> >, std::allocator<std::unique_ptr<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix, std::default_delete<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix> > > > const&, tensorflow::TTypes<tensorflow::bfloat16, 2, int>::Matrix*)'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1766.182s, Critical Path: 275.26s
FAILED: Build did NOT complete successfully`

**Comment by drpngx** [comment]
Oh, that's good, thank you. It means that the definition is actually missing, which is the root cause. Now we need to find out why.

**Comment by drpngx** [comment]
So, there are two options: 1) you don't actually want the definition in raspbian, or 2) you want it, so you need to define it.

For 1), then you can try to track down the usage in `list_kernels.cc` and figure out how to pull it out, or why it is inconsistent. For 2), you need to read the templates and macro definitions carefully (the lazy way out is to build it on a platform where it works, then define it in other file. The linker should tell you where the duplicate definition is)

**Comment by Lexicographical** [comment]
I'm having trouble finding where it's actually being used. I tried searching the file itself and there are no results for "ConcatCPU". I thought it might have something to do with `#include "tensorflow/core/kernels/concat_lib.h"` but that's gonna affect a lot of other things if I change it. To clarify, I'm looking at `tensorflow/core/kernels/list_kernels.cc`

**Comment by Lexicographical** [comment]
After recompiling, with the include statement commented out, it still throws the same error saying there's an undefined refernce to the ConcatCPU function. Nowhere in the file is there a mention of the said function though.

**Comment by Lexicographical** [comment]
Ok it now compiles fine and I can run tensorflow now. Thank you!
To clarify, what I did was comment out the function call of `ConcatCPU` in `tensorflow/core/kernels/list_kernels.h`

**Comment by drpngx** [comment]
Glad it worked for you!

**Comment by Lexicographical** [comment]
Hello! I'm not really sure but I was able to run Tensorflow applications normally despite commenting out that line so it doesn't seem to be a problem.

**Comment by mbahaa** [comment]
Hello, I've been fiddling around this for a while, there's actually a clean method without commenting code lines or any ad-hoc solutions, for native building on ARM, I checked out to the [revision with latest successful nightly build](http://ci.tensorflow.org/view/Nightly/job/nightly-pi/238/), then you should pass one of the following macros while building (**ARM_NON_MOBILE** or **RASPBERRY_PI**), so bazel building command becomes as follows:
`git checkout -f d82b2f71b60d5fff48884c20c7b85e517330e91f`
`bazel build -c opt --copt=-DARM_NON_MOBILE --copt=-mfpu=neon-vfpv4 --copt=-std=gnu11 --copt=-DS_IREAD=S_IRUSR --copt=-DS_IWRITE=S_IWUSR --copt=-O3 --config=monolithic --copt=-funsafe-math-optimizations --copt=-ftree-vectorize --copt=-fomit-frame-pointer --local_resources 400,2.0,1.0 --verbose_failures tensorflow/tools/pip_package:build_pip_package 2>&1 | tee ~/tf_nativebuild.log`
I found the hint about the macros in this file `tensorflow/core/platform/platform.h`
> // Require an outside macro to tell us if we're building for Raspberry Pi or
// another ARM device that's not a mobile platform.

Another very convenient alternative is to use the cross-building script that tensorflow maintainers use for nightly ci builds, it's easier and also much faster, it creates a docker container, installs all required dependencies inside it, then cross-builds tensorflow for arm, you also need to checkout to the stable revision
`git checkout -f d82b2f71b60d5fff48884c20c7b85e517330e91f`
`tensorflow/tools/ci_build/ci_build.sh PI tensorflow/tools/ci_build/pi/build_raspberry_pi.sh 2>&1 | tee ~/tf_crossbuild.log`

**Comment by flyhorseli** [comment]
I used the same command, as mbahaa.
What I found is that --copt=IS_RASPBERRY is not passed into build, so IS_MOBILE_PLATFORM is defined in the build.
