### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mikeconnors909** [tensorflow/tensorflow#178]
While running the `sudo bazel build -c opt //tensorflow/tools/pip_package:build_pip_package`, I get the following error:

```
./tensorflow/python/client/tf_session_helper.h:6:10: fatal error: 'numpy/arrayobject.h' file not found
#include "numpy/arrayobject.h"
         ^
1 error generated.

```

However, I installed numpy from the source listed and it worked perfectly. Any suggestions?

**Comment by mikeconnors909** [comment]
I forgot to add I am on Mac OS X Mavericks

**Comment by mikeconnors909** [comment]
Edit:

By updating the file `./tensorflow/python/client/tf_session_helper.h` to include the actual path of the numpy include directory of the computer, I have managed to get a new error,
```
bazel-out/local_darwin-opt/bin/tensorflow/python/pywrap_tensorflow.cc:3609:10: fatal error: 'numpy/arrayobject.h' file not found
#include "numpy/arrayobject.h"
         ^
1 warning and 1 error generated.
```

I have tried to edit this file the same way, but I cannot because it is just a symlink to a tmp direcotry, so it is regenerated each time.

Any ideas?

**Comment by vrv** [comment]
Possibly dumb question: is there a need to sudo bazel build?  what if you remove the sudo ?

**Comment by mikeconnors909** [comment]
I removed the directory, reinstalled everything from scratch, then got the 1st error:
```
INFO: From Compiling tensorflow/python/client/tf_session_helper.cc:
In file included from tensorflow/python/client/tf_session_helper.cc:1:
./tensorflow/python/client/tf_session_helper.h:6:10: fatal error: 'numpy/arrayobject.h' file not found
#include "numpy/arrayobject.h"
         ^
1 error generated.
```

What next?

**Comment by vrv** [comment]
Any chance this is related to https://github.com/tensorflow/tensorflow/issues/187 ? (are you using anaconda python?

**Comment by mikeconnors909** [comment]
No, I installed numpy directly from source, and it is located in the right directory. The directory tree to the file the installer can't find is as follows:

```
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h

```

**Comment by vrv** [comment]
Hm, I'm not entirely sure what the answer is here.  https://github.com/BVLC/caffe/issues/1284 seems to suggest a similar problem, but the solution to 'reinstall numpy' doesn't really apply here.  Hopefully someone from the community can chime in and help.

**Comment by ebrevdo** [comment]
We look for the numpy headers here:

/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include

which is different from your setup.  Try changing [this line](https://github.com/tensorflow/tensorflow/blob/72a5a60dd4664a7caa4611344364ac7851464a60/tensorflow/python/BUILD#L23) accordingly.

**Comment by mikeconnors909** [comment]
Works great for first step. Waiting for next two to execute. Thanks ebrevdo!

**Comment by mikeconnors909** [comment]
Installation completely worked. Thanks!

**Comment by prateekm33** [comment]
hey @ebrevdo, getting this issue from the `master` branch right now

is there an analogous fix for it there or should I compile a different release?

**Comment by prateekm33** [comment]
having the following issue on release branches 1.8 - 1.10
```
/tensorflow/third_party/python_runtime/BUILD:5:1: no such package '@local_config_python//': 
```

and having `numpy` import errors on 1.11 and 1.12 and master
