### ISSUE TITLE
Feature request: batch image input for exported model (image retraining)

### ISSUE THREAD

**Issue by chunkya** [tensorflow/tensorflow#17817]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **TensorFlow installed from (source or binary)**:  binary
- **TensorFlow version (use command below)**: 1.4.1
- **Python version**: 3.6.1
- **Bazel version (if compiling from source)**: - 
- **GCC/Compiler version (if compiling from source)**: -
- **CUDA/cuDNN version**: 7.5/6
- **GPU model and memory**: -
- **Exact command to reproduce**: 

### Describe the problem
Feature request:
I want to use the image retraining on my own image classes and then use the exported model as part of my data pipeline. But I noticed that the exported model only accepts input tensors of size (1, 299, 299, 3). It would be really great if it could accept batch images for example (32, 299, 299, 3) tensors. If you could advise me on how best to modify the code to do this that would be great too.

### Source code / logs
How I trained my model:
```
python3 tensorflow/examples/image_retraining/retrain.py --image_dir $DATA_DIR
```
Here I tried feeding (2, 299, 299, 3) tensor as input to the model
```
Traceback (most recent call last):
  File "tensorflow/examples/label_image/label_image.py", line 133, in <module>
    input_operation.outputs[0]: t
  File "/home/beo/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/beo/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1113, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (2, 299, 299, 3) for Tensor u'import/Mul:0', which has shape '(1, 299, 299, 3)'
```

**Comment by dthkao** [comment]
How are you saving/loading your saved model? What tags are you using?

Do you have a code snippet?

**Comment by chunkya** [comment]
I am using the model generated by the retrain.py code. 
```
python tensorflow/examples/label_image/label_image.py --graph=/tmp/output_graph.pb --labels=/tmp/output_labels.txt --input_layer=Mul --output_layer=final_result --input_mean=128 --input_std=128
```
And i replaced the input in label_image.py to use a (2, 299, 299, 3) shape array.
```
graph = load_graph(model_file)
# t = read_tensor_from_image_file(
#     file_name,
#     input_height=input_height,
#     input_width=input_width,
#     input_mean=input_mean,
#     input_std=input_std)

t = np.zeros((2, 299, 299, 3))

input_name = "import/" + input_layer
output_name = "import/" + output_layer
input_operation = graph.get_operation_by_name(input_name)
output_operation = graph.get_operation_by_name(output_name)

with tf.Session(graph=graph) as sess:
  results = sess.run(output_operation.outputs[0], {
      input_operation.outputs[0]: t
  })
```

**Comment by michaelisard** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
