### ISSUE TITLE
Tensorflow lite c++ shared library build steps.

### ISSUE THREAD

**Issue by dimitryn** [tensorflow/tensorflow#17826]
Hi , 
I like to know steps to build shared/static  c++ tensorflow lite library+ headers **WITHOUT JNI** for Android armeabi-v7a/arm64-v8a.
I search for this problem through all issues here , found couple relevant topics but all of them without complete answer. 

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
Master
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
0.10.1
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
None
- **GPU model and memory**:
None

Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by dimitryn** [comment]
updated

**Comment by brancooo1** [comment]
@dimitryn any news on this?

**Comment by dimitryn** [comment]
1. add this to BUILD file in contrib/lite
cc_binary(
    name = "libtensorflowLite.so",
 
linkopts=["-shared", "-Wl"],
linkshared=1,


    copts = tflite_copts(),
    deps = [
        ":framework",
    ],
)

2. bazel build  //tensorflow/contrib/lite:libtensorflowLite.so --crosstool_top=//external:android/crosstool --cpu=arm64-v8a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11"

**Comment by SimoLoca** [comment]
Is this still functional for Tensorflow 2.2.0?
