### ISSUE TITLE
[Doc] Clarification on tf.contrib.lookup.MutableHashTable insert operation

### ISSUE THREAD

**Issue by Fnjn** [tensorflow/tensorflow#17835]
Document on [MutableHashTable](https://www.tensorflow.org/api_docs/python/tf/contrib/lookup/MutableDenseHashTable) is confusing, especially in this line:
`table.insert(keys, values)`
This code is unexecutable and misleading, it suggests insert is done inplace rather than an operation that need to be executed afterwards.

I think it shall be replaced by:
`sess.run(table.insert(keys, values))`

Reference: [tensorflow-mutablehashtable-not-updating](https://stackoverflow.com/questions/43373170/tensorflow-mutablehashtable-not-updating)

**Comment by imsheridan** [comment]
Created PR #17836 to fix this.

**Comment by Fnjn** [comment]
Create PR #17838 to fix related doc problem in tf.contrib.lookup.MutableDenseHashTable
