### ISSUE TITLE
Very Large Dataset

### ISSUE THREAD

**Issue by rizplate** [tensorflow/tensorflow#17834]
I have very large dataset of 500GB csv single file. is there a way to batch or chunk process it?

**Comment by Fnjn** [comment]
This [Input Pipeline Performance Guide] (https://www.tensorflow.org/versions/master/performance/datasets_performance) may helps. I think this kind of questions should be asked in [stackoverflow](stackoverflow.com).

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
