### ISSUE TITLE
feature request: complex64 support in diag op

### ISSUE THREAD

**Issue by corcra** [tensorflow/tensorflow#1783]
[`tf.diag`](https://www.tensorflow.org/versions/r0.7/api_docs/python/math_ops.html#diag) only supports `float32`, `float64`, `int32`, `int64` right now; is it possible to also include `complex64`? 

I may get around to extending the op to do this for my own purposes, but perhaps someone else is better positioned to add this functionality. Or is there some deeper reason it's not supported?

**Comment by suiyuan2009** [comment]
I'll work on it

**Comment by suiyuan2009** [comment]
InvalidArgumentError: No OpKernel was registered to support Op 'Diag' with these attrs
	 [[Node: Diag = Diag[T=DT_COMPLEX64, _device="/device:CPU:0"](Const)]]
does this mean I should use gpu?
