### ISSUE TITLE
Beam search terminology

### ISSUE THREAD

**Issue by MattShannon** [tensorflow/tensorflow#17839]
(This issue is with terminology used in documentation and code. System information not applicable.)

The documentation and code in tf.contrib.seq2seq.BeamSearchDecoder and friends seems to use "beam" to mean "search state", whereas beam conventionally means "a collection of search states". This non-standard usage makes for confusing documentation!

Examples in documentation at https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/BeamSearchDecoder:

"The BeamSearchDecoder shuffles its beams" 
"beam_width: Python integer, the number of beams" 

Or in code:

https://github.com/tensorflow/tensorflow/blob/838a8f54f92452a15e3bb62a23ad5cd67e86933f/tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py#L144

The conventional search algorithm terminology as I understand it, and attested by wikipedia (https://en.wikipedia.org/wiki/Beam_search) and recent academic usage (http://www.ijcai.org/Proceedings/05/Papers/0596.pdf), is that beam search is called beam search because it keeps a beam of search states in memory. The beam refers to the collection of search states, not the individual search states (I presume by the analogy that a beam of light illuminates certain objects but not others that fall outside the beam).

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by MattShannon** [comment]
As I mentioned, I'm looking at documentation and source code, so system information is not applicable. The TensorFlow version I'm looking at the documentation for is r1.6.

**Comment by ebrevdo** [comment]
PRs improving the documentation are welcome!

**Comment by imsheridan** [comment]
Created a PR #18235 to fix this issue.

**Comment by harshini-gadige** [comment]
Closing this issue as a PR is created for the same.

**Comment by MattShannon** [comment]
That PR doesn't fix the issue. It's just a straight-up replace of "beam" for "search state" which leaves the documentation ungrammatical or nonsensical in many places. (I'm afraid I don't have bandwidth at the moment to make the docs better though.)

**Comment by harshini-gadige** [comment]
Reopening the issue. Can refer the PR number if one is created for the same.

**Comment by MarkDaoust** [comment]
Contrib seq2seq has moved to tensorflow addons. If this is still an issue, please send a new Issue to that repository.
