### ISSUE TITLE
Add support for stochastic depth networks

### ISSUE THREAD

**Issue by aman-tiwari** [tensorflow/tensorflow#1784]
This issue is a feature request to add support to tensorflow to implement networks with stochastic depth (http://arxiv.org/abs/1603.09382).

**Comment by alexatknit** [comment]
tf.cond should be enough to make this work

**Comment by vrv** [comment]
Agreed with @alexatknit, seems like we have the primitives to implement this already -- though if you have a more concrete feature request, we'll take a look.
