### ISSUE TITLE
feature request: support for cudnn v5 rc

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#1786]
Anyone can help this?
https://developer.nvidia.com/rdp/cudnn-download

**Comment by fayeshine** [comment]
FYI, https://github.com/Theano/Theano/issues/4342#

**Comment by vrv** [comment]
I looked into this just now briefly -- there are a lot of API changes that are somewhat annoying to #ifdef around but I made progress.  The biggest changes have to do with convolution APIs: they exposed the convolution algorithms as required parameters, and from the Theano example, it seems they decided to plumb the algo as an option through their API, which seems kind of ugly.

There seems to be a "FindConvolution*Algorithm" function in the API which might be able to choose the best one automatically but there's no documentation so I have no idea if this is what we should be calling (and why the cudnn APIs don't call this automatically underneath the hood).

If anybody has any ideas about what we should do here, please let us know.

**Comment by vrv** [comment]
https://github.com/vrv/tensorflow/commit/a76449737fed046b7e9f9871dd2d1d5c2f51ead0

Built for me with R5, I was able to run a few benchmarks, though not a huge difference, presumably because I'm not choosing the 'optimal algorithms'.

**Comment by alquraishi** [comment]
They claim to be getting rather [substantial speed improvements](https://pbs.twimg.com/media/CfTGrS9XIAENPCv.jpg) on RNNs and LSTMs.

**Comment by vrv** [comment]
#1794 added basic support for v5 RC, so you can at least install the library on your system and it will work.  We haven't performance optimized it or added the RNN/LSTM API yet.

**Comment by esd100** [comment]
I'm not sure why but I am unable to do a Bazel PIP build past cuDNN.

I'm using the instructions and forked TF from here.
https://gist.github.com/ageitgey/819a51afa4613649bd18

TF_UNOFFICIAL_SETTING=1 ./configure
bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer

[TF_BazelPIPBuild_TerminalOutput.txt](https://github.com/tensorflow/tensorflow/files/211039/TF_BazelPIPBuild_TerminalOutput.txt)

**Comment by vrv** [comment]
I'm not sure stream executor works for OS X yet (hence #664).  I did test cudnn v5 on my local machine and it seemed to work, so I'm not entirely sure why it's still failing for you -- might double check that the symlinks and cudnn header file and ./configure options have been set properly.

**Comment by wchan** [comment]
will TF integrate the cuDNN LSTM API? Did anyone run benchmarks on how much faster it is? The nasty thing I can see from the cuDNN API is in the backward pass, we need to pass a temp scratch pointer from the forward pass -- not too sure how to impl that.

**Comment by benbarsdell** [comment]
I think there is a small bug here: the 'format' argument to cudnnSetFilter4dDescriptor should be based on the filter layout not the data layout.

Also, CUDNN_ACTIVATION_CLIPPED_RELU can be used for Relu6 and ReluX.

**Comment by vrv** [comment]
Thanks @benbarsdell: want to send a PR to fix either one?  Also when I wrote that up, it wasn't clear to me how a 'filter' could have a format of NCHW, which is why I used the data layout.  Filters don't talk about batch, just input and output channel / height / width, so I wasn't really sure what to do there.

**Comment by vrv** [comment]
@benbarsdell okay I think with the commit above and dfcad66c5ecc6e49aff0fa379832982809b2b447 we addressed your issues -- let me know if there's still something left there.

Will leave this open until we figure out what we're doing about the LSTM/RNN API.

**Comment by vrv** [comment]
We're sort of working on this now.

**Comment by phiber1** [comment]
Was about to ask about the RNN and LSTM support in cuDNN v5, and found this thread. While we're on the subject, what about support for tensor descriptors? Also new in v5.

**Comment by girving** [comment]
@vrv: Assigning to you for now.

**Comment by zpardos** [comment]
@vrv So, what did you all decide you're doing about CuDNN v5's RNN/LSTM API?

**Comment by vrv** [comment]
We're still trying to integrate it -- it's pretty hard :(

**Comment by kfinla** [comment]
Is cuDNN v5.1 compatible with theano 0.8.2? (minus LSTM, RNN optimizations)  I had cuDNN 5005 and cuda 7.5  working with an older kepler card. I THINK i need cuda 8.0 to work with my gxt 1060. Should I update to win10? I am on 8.1 atm.

**Comment by tatatodd** [comment]
@vrv Friendly ping, is this still being worked on?

**Comment by vrv** [comment]
The LSTM components are, yes.

**Comment by kfinla** [comment]
So I have cuda 8.0 RC (cudnn 5.0 (5005)) working with my gtx 1060 , keras 1.0.6 and theano 0.9.0 dev2.
I am still curious to know the state of support for cuDNN 5.1, if it works with theano yet? 0.8.2 or 0.9.0 dev2.

**Comment by vrv** [comment]
Cudnn RNN ops were added here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cudnn_rnn

Closing this bug since that's probably the major thing desired from cudnn v5.

And I'm sure v6 is around the corner...
