### ISSUE TITLE
CUDNN_STATUS_BAD_PARAM with included cifar10 model

### ISSUE THREAD

**Issue by cmcneil** [tensorflow/tensorflow#1787]
### Environment info
Operating System:
Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
Python 2.7

If installed from binary pip package, provide:

1. Which pip package you installed.
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.7.1

### Steps to reproduce
1. Go to /usr/local/lib/python2.7/dist-packages/tensorflow/models/image/cifar10
2. Run python cifar10_train.py as root
3. Observe output 
F tensorflow/stream_executor/cuda/cuda_dnn.cc:383] could not set cudnn filter descriptor: CUDNN_STATUS_BAD_PARAM
Aborted

### What have you tried?
1. Messing with LD_LIBRARY_PATH and making sure all cuda packages are updated to 7.5 (and CudNN 5.0). Training the simple softmax models on GPU is possible.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
root@leviathan:/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/cifar10# python cifar10_train.py 
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
... Loads other CUDA libraries as above ...
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:01:00.0
Total memory: 11.25GiB
Free memory: 11.15GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:717] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40c, pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 1.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 2.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 4.0KiB
... and so on up to 16.00 GB:
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 16.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:73] Allocating 10.60GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:83] GPU 0 memory begins at 0x5047a0000 extends to 0x7aaa4019a
F tensorflow/stream_executor/cuda/cuda_dnn.cc:383] could not set cudnn filter descriptor: CUDNN_STATUS_BAD_PARAM
Aborted

**Comment by vrv** [comment]
If you are installing the pip package for 0.7.1, check that you are using cudnn r4 (make sure the libraries being loaded are the correct version).

**Comment by cmcneil** [comment]
Ah, I am using cudnn r5. Is it not backwards compatible? Another error was preventing me from using r4. Thank you, and I will open another bug if r4 continues to give me trouble!

**Comment by vrv** [comment]
No, it's not backwards compatible from the pip installation, the APIs are often different.

https://github.com/tensorflow/tensorflow/pull/1794 is a change to allow compiling from source to support cudnn r5.  Since it's RC, we're unlikely to package it in our official PIPs until it is officially released (as they work out bugs), but that commit should add basic support for it.

**Comment by cmcneil** [comment]
Alright thanks!

**Comment by ushnish** [comment]
Hello can you tell me what is the right cuda and cudnn version to use? Should I be using cuda 7.0 and cudnn v3 then?

**Comment by vrv** [comment]
for 0.8.0 pips, cuda 7.5 and cudnn v4.

If you build from sources, you can use anything from cuda 6.5-cuda 7.5 and cudnn v2 - cudnn v5

**Comment by philipperemy** [comment]
If you have the error `CUDNN_STATUS_BAD_PARAM`, make sure that the problem does not come from your code.
For example if you give an empty array as an input. It happened to me and this was the reason.
I'm running v5 with TF built from the sources.

**Comment by Soltius63** [comment]
Just to weigh in on @philipperemy  's answer, CUDNN_STATUS_BAD_PARAM can indeed be sort of unrelated to cuda, and hide a "simple" code error. In my case, I was trying to convolute an input with a kernel bigger than the actual input. Code to reproduce : 


```
class _network(nn.Module):
    def __init__(self):
        super(_network, self).__init__()

        self.test_module = nn.Sequential(
            nn.Conv2d(1, int(64 / 2), 4, 2, 1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),
        )

    def forward(self, input):
        output=self.test_module(input)
        return output

input=Variable(torch.zeros(64,1,1,1).cuda())

network=_network()
network=network.cuda()
output=network(input)
```

This gives the CUDNN_STATUS_BAD_PARAM error with Pytorch 0.3.1 and Python 3.6. Removing the "cuda" from the network and the input yields a much more informative error on what is actually happening : 

> RuntimeError: Calculated input size: (3 x 3). Kernel size: (4 x 4). Kernel size can't greater than actual input size at /pytorch/torch/lib/THNN/generic/SpatialConvolutionMM.c:46

**Comment by philipperemy** [comment]
@Soltius63 thanks for the explanation :)
