### ISSUE TITLE
How to force Tensorflow app to use Android framework's NNAPI?

### ISSUE THREAD

**Issue by deval1491** [tensorflow/tensorflow#17880]
### Describe the problem
I am using x86 (intel platform) android device to check if tensorflow apk is calling Android's NNAPI. It seems its not calling the APIs.
How can i force tensorflow apk to forcefully use Android framework's NNAPI?

Android studio project location: <src>/tensorflow/contrib/lite/java/demo/app/
Android version: 8.1

**Comment by freedomtan** [comment]
I have a PR for this, see https://github.com/tensorflow/tensorflow/pull/16065

**Comment by aselle** [comment]
This seems to be resolved with another PR see:
https://github.com/tensorflow/tensorflow/blob/049dfd5e070cfa84c82eea71c6c746a70cba4a3f/tensorflow/contrib/lite/java/src/main/java/org/tensorflow/lite/Interpreter.java#L207

Please close if this is done to your satisfaction. Thanks!

**Comment by andrehentz** [comment]
I'll close this for now. Let us know if this still doesn't work for you.

**Comment by deval1491** [comment]
This is solved... Please close this
