### ISSUE TITLE
pip install TensorFlow wheel fails due to BoringSSL

### ISSUE THREAD

**Issue by namrata-ibm** [tensorflow/tensorflow#17882]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: s390x Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.6.0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.7.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: pip install tensorflow-1.6.0-cp27-cp27mu-linux_s390x.whl

### Describe the problem
TensorFlow v1.6.0 wheel installation fails on s390x since it installs `grpcio` which fails due to BoringSSL. 
@gunan, this is similar to earlier issues related to BoringSSL on s390x. 

### Source code / logs
``` 
sudo pip install /tmp/tensorflow_wheel/tensorflow-1.6.0-cp27-cp27mu-linux_s390x.whl
.
.
.
  Running setup.py install for gast ... done
  Running setup.py install for termcolor ... done
  Running setup.py install for absl-py ... done
  Running setup.py install for grpcio ... error
.
.
.
Werror=format-security -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) void -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -I/usr/include/python2.7 -c src/core/lib/security/credentials/google_default/google_default_credentials.cc -o python_build/temp.linux-s390x-2.7/src/core/lib/security/credentials/google_default/google_default_credentials.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    In file included from third_party/boringssl/include/openssl/rsa.h:60:0,
                     from ./src/core/lib/security/credentials/jwt/json_token.h:23,
                     from ./src/core/lib/security/credentials/jwt/jwt_credentials.h:23,
                     from src/core/lib/security/credentials/google_default/google_default_credentials.cc:34:
    third_party/boringssl/include/openssl/base.h:114:2: error: #error "Unknown target CPU"
     #error "Unknown target CPU"
      ^
```

**Comment by gunan** [comment]
@caisq @jart @chihuahua 
Looks like this was added with https://github.com/tensorflow/tensorflow/commit/549581f635a439ddcc6fdabf05f972c8ced1738d

Do you remember why we made this change?
Can we remove the dependency on grpcio?

**Comment by jart** [comment]
Is the IBM Z mainframe "zEC12" CPU in our support matrix?

```
// Note BoringSSL only supports standard 32-bit and 64-bit two's-complement,
// little-endian architectures. Functions will not produce the correct answer
// on other systems. Run the crypto_test binary, notably
// crypto/compiler_test.cc, before adding a new architecture.
#error "Unknown target CPU"
```

Maybe this issue should be sent upstream as contributions welcome?

**Comment by gunan** [comment]
It is not in our support matrix, but grpc makes even contributed support impossible.
IBM has been maintaining support for us.

On the upstream feature request side, boringSSL owners reported that they will not support big endian systems. Therefore our option now is to enable building TF without SSL.

**Comment by jart** [comment]
It seems this started in https://github.com/tensorflow/tensorflow/pull/6681. That's a big commitment on our part. I'm not sure TensorFlow stored data would be portable between such systems. Can't these CPUs simulate little endian?

Would it be possible for grpcio to update their setup.py so, if the system is big endian, it favors linking OpenSSL from the system, rather than compiling BoringSSL from scratch?

**Comment by gunan** [comment]
@martinwicke to loop him in.
I guess that is one bug we can file to grpc team, but until that is done, our dependence on grpcio will completely block the big endian systems.

**Comment by martinwicke** [comment]
Since TF has to be build from source on big endian anyway, can we do this: If building build_pip_package for a BE system, remove the grpcio dependency from the generated setup.py. 

This will break things that actually depend on grpcio, so we'd have to make those failures soft(er), for instance, the debugger may just error out on big endian systems, but TF import shouldn't be affected.

@namrata-ibm do you think that would be workable?

**Comment by caisq** [comment]
+1 what @martinwicke said. If that plan sounds good to everyone, I'll be happy to modify setup.py to make the grpcio pip dependency conditional on little endian.

**Comment by gunan** [comment]
This plan sounds good to me.
Please add @yifeif as a reviewer as she has experience with conditional pip dependencies.

**Comment by jart** [comment]
+1 @martinwicke again. We can make grpcio an optional but important dependency for folks who need it. Please note I also support the BoringSSL decision to not support big endian, which was done for reasons that likely don't apply here.
