### ISSUE TITLE
How does the line of code ensure that total_loss are computed after finishing update_ops?

### ISSUE THREAD

**Issue by tianzhi0549** [tensorflow/tensorflow#17887]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: ('v1.7.0-rc0-11-g8fded78', '1.7.0-rc1') 
- **Python version**: Python 2.7.12
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

Hi, there may be a bug in create_train_op().

In the newest tensorflow code, the line (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/training/python/training/training.py#L428) intends to make sure that total_loss is computed after finishing update_ops.

I think it wants to make sure that the total_loss is computed with up-to-date values of variables after update_ops.

However, my question is that the total_loss is defined elsewhere. There is just a reference to total_loss, which should not make the control_dependencies effective. So how does it work? **Is it possible the total_loss is computed with stale values of variables before update_ops?**

Thank you very much:-).

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tianzhi0549** [comment]
@tensorflowbutler The information has been added. Thank you very much.

**Comment by aselle** [comment]
This seems to be a misunderstanding of how TensorFlow graphs work. The reference to total_loss is a reference to the operation that has not yet been executed. The python calls are not executing things, they are building a graph which is later executed. A control dependency alters the graph to represent that one node has to run before another.

**Comment by tianzhi0549** [comment]
@aselle Thank you for your reply. I know the python code just define the operations. However, a control dependency does not work for an operation defined elsewhere. So this control dependency does not make sure the total_loss is computed with up-to-date variables. I mean there is a race condition.

The question has been answered on StackOverflow (https://stackoverflow.com/questions/49421529/how-does-tf-control-dependencies-work-for-operations-defined-elsewhere/49455352?noredirect=1#comment85995693_49455352). Thank you very much.
