### ISSUE TITLE
Inconsistency in the accepted shape/data_format of Input Tensor to Conv2D in documentation.

### ISSUE THREAD

**Issue by YashalShakti** [tensorflow/tensorflow#17892]
### Problem
The Tensorflow Layers Guide at https://www.tensorflow.org/tutorials/layers specifies:

> The methods in the layers module for creating convolutional and pooling layers for two-dimensional image data expect input tensors to have a shape of [batch_size, image_width, image_height, channels]

While, the inline documentation specified for conv2D (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/convolutional.py#L444) mentions the following valid data_formats:

> data_format: A string, one of `channels_last` (default) or `channels_first`.
      The ordering of the dimensions in the inputs.
      `channels_last` corresponds to inputs with shape
      `(batch, height, width, channels)` while `channels_first` corresponds to
      inputs with shape `(batch, channels, height, width)`

Moreover, nn.bias_add, avg_pool2d (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/layers.py#L99) etc. also accept [...,height, width...] but using different strings/methodology.

> inputs: A 4-D tensor of shape `[batch_size, height, width, channels]` if
      `data_format` is `NHWC`, and `[batch_size, channels, height, width]` if
      `data_format` is `NCHW`.

Thus; shouldn't https://www.tensorflow.org/tutorials/layers be updated and the valid data_format values for Convolutional Layers be changed?

**Comment by imsheridan** [comment]
Created #17893 to fix the inconsistency mentioned above.

**Comment by YashalShakti** [comment]
Hi,

There are several other instance where the inconsistency needs to be fixed. Moreover, for data_format=channels_first the shape should be NCHW while it is specified as CNWH. I have created #17920 to cover all the instances where the shape should be changed.

Thanks!
