### ISSUE TITLE
Failed compilation of build_all_android.sh on Ubuntu 17

### ISSUE THREAD

**Issue by dimitryn** [tensorflow/tensorflow#17895]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 17
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
Master
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
0.10
- **GCC/Compiler version (if compiling from source)**:
4.9
- **CUDA/cuDNN version**:
No
- **GPU model and memory**:
No
- **Exact command to reproduce**:
./tensorflow/contrib/makefile/samples/build_and_run_inception_hexagon.sh

### Describe the problem
1. NDK version 16
2.after build_all_android.sh download successfully  dependencies it start  building protocol buffer from sources.
3.Compilation error:
### Source code / logs
```
libtool: compile:  aarch64-linux-android-g++ --sysroot /home//Android/Sdk/ndk-bundle/platforms/android-27/arch-arm64 -std=c++11 -DHAVE_CONFIG_H -I. -I.. -Wall -Wno-sign-compare -frtti -fexceptions -I/home/dnozik/Android/Sdk/ndk-bundle/sources/android/support/include -I/home/dnozik/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -I/home/dnozik/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include -MT google/protobuf/stubs/atomicops_internals_x86_gcc.lo -MD -MP -MF google/protobuf/stubs/.deps/atomicops_internals_x86_gcc.Tpo -c google/protobuf/stubs/atomicops_internals_x86_gcc.cc -o google/protobuf/stubs/atomicops_internals_x86_gcc.o
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:34:0:
/home//Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/cstring:42:20: fatal error: string.h: No such file or directory
 #include <string.h>
                    ^
compilation terminated.
Makefile:4123: recipe for target 'google/protobuf/stubs/atomicops_internals_x86_gcc.lo' failed
make[3]: *** [google/protobuf/stubs/atomicops_internals_x86_gcc.lo] Error 1
make[3]: Leaving directory '/home//Code/Tensorflow_Hexagon/tensorflow-master/tensorflow/contrib/makefile/downloads/protobuf/src'
Makefile:2109: recipe for target 'all' failed

```

Thanks for help

**Comment by dimitryn** [comment]
install latest bazel version 14.0 , it support NDK 16.

**Comment by Chucky109** [comment]
I'm trying to build via makefile because I hit this issue too: https://github.com/tensorflow/tensorflow/issues/11777 and wanted to try the solution
