### ISSUE TITLE
Typo in TensorBoard: Visualizing Learning docs

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#179]
I believe there is a typo. In the code snippet in that section, currently it states:

`summary_writer = tf.train.SummaryWriter('/tmp/mnist_logs', sess.graph)`

But `sess.graph` is a `Graph` object and `SummaryWriter` expects a `GraphDef` object instead, so something like:

`summary_writer = tf.train.SummaryWriter('/tmp/mnist_logs', tf.Graph.as_graph_def(sess.graph))`

**Comment by vrv** [comment]
Yup, you are right -- should be sess.graph_def.  We'll try to fix this soon, thanks for the report!

**Comment by vrv** [comment]
Fixed some time ago.
