### ISSUE TITLE
ImportError: No module named 'tensorflow.tensorboard.tensorboard'

### ISSUE THREAD

**Issue by neotheicebird** [tensorflow/tensorflow#1790]
When I try:

```
tensorboard --logdir=/path/to/eventlogs
```

I get

```
ImportError: No module named 'tensorflow.tensorboard.tensorboard'
```

Packages
-------------
I use Ubuntu 14.04, Python 3.4.3 and I installed tensorflow using:

```
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp34-none-linux_x86_64.whl
```

**Comment by neotheicebird** [comment]
The reason for the error is that `tensorboard.py` resides inside `tensorboard\backend\` instead of `tensorboard\` as expected by it

**Comment by neotheicebird** [comment]
If I run:

```shell
~/tensorflow$

**Comment by vrv** [comment]
Check your bin path to see if there's a stale / old tensorboard.py ?

**Comment by neotheicebird** [comment]
Thanks. I did check and found I posted some wrong information.

`tensorboard` in `/bin` of `Python 3.4 virtualenv` works, its the `tensorboard` installed along with Anaconda (Python 3.5.1) that doesn't. 

what I did:

```
pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp34-none-linux_x86_64.whl
```
Probably this `.whl` installation is not meant for Anaconda.

**Comment by vrv** [comment]
Yes, we don't release anaconda wheels (yet) :(.  You might want to try building from sources.

**Comment by neotheicebird** [comment]
oh, cool. No problem, thanks. I am happy it works with Py3.4 now. :) :+1:

**Comment by Sidney2408** [comment]
One workaround I did was to navigate to the directory of tensorboard.py and edit the import statement.

if __name__ == '__main__':
    import sys
    #import tensorflow.tensorboard.tensorboard
    import tensorboard.main
    #sys.exit(tensorflow.tensorboard.tensorboard.main())
    sys.exit(tensorboard.main.main())

Not sure if this is good practice though

**Comment by AmritbaniKaur** [comment]
My PyCharm is not getting tensorboard, when i use: tensorboard --logdir="logs\" . It gives: 
error: 'tensorboard' is not recognized as an internal or external command, operable program or batch file.
^-- the env set in Pycharm setting has tensorboard packages located at: envs\tensorflow\Lib\site-packages\tensorflow\contrib\tensorboard
and
envs\tensorflow\Lib\site-packages\tensorboard

but, as stated in the comments above, I cannot find tensorboard.py, even in the backend package
there is: import_pb_to_tensorboard.py; but i don't think that's what is needed

----------------------------------------------------------------------------------------------------------------

If I try to: python -m tensorboard --logdir="logs\"; then it says:
C:\Users\<name>\AppData\Local\Programs\Python\Python36-32\python.exe: No module named tensorboard
^-- this location does not have tensorflow / tensorboard

-----------------------------------------------------------------------------------------------------------------
Any suggestions to resolve this would be highly appreciated
Thanks!

P.S.: Using it on Windows 10, through anaconda
