### ISSUE TITLE
Missing gradient for tf.nn.max_pool_with_argmax

### ISSUE THREAD

**Issue by Thrasi** [tensorflow/tensorflow#1793]
I swapped out the first max_pool operation in [convolutional.py](https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/models/image/mnist/convolutional.py) tutorial for a max_pool_with_argmax operation and there doesn't seem to exist a gradient for that op:

`(virtenv)$ python convolutional.py`
`Extracting data/train-images-idx3-ubyte.gz`
`Extracting data/train-labels-idx1-ubyte.gz`
`Extracting data/t10k-images-idx3-ubyte.gz`
`Extracting data/t10k-labels-idx1-ubyte.gz`
`Traceback (most recent call last):`
`File "convolutional.py", line 316, in <module>`
`tf.app.run()`
`File "/home/name/virtenv/local/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run`
`sys.exit(main(sys.argv))`
`File "convolutional.py", line 244, in main`
`global_step=batch)`
`File "/home/name/virtenv/local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 190, in minimize`
`colocate_gradients_with_ops=colocate_gradients_with_ops)`
`File "/home/name/virtenv/local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 241, in compute_gradients`
`colocate_gradients_with_ops=colocate_gradients_with_ops)`
`File "/home/name/virtenv/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients.py", line 453, in gradients`
`(op.name, op.type))`
`LookupError: No gradient defined for operation 'MaxPoolWithArgmax' (op type: MaxPoolWithArgmax)`
### Environment info

Operating System: Ubuntu 14.04.1 LTS

If installed from binary pip package, provide:

(virtenv)$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
(virtenv)$ python -c "import tensorflow; print(tensorflow.**version**)"
0.7.1
### Steps to reproduce
1. Change line 192-5 of [convolutional.py](https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/models/image/mnist/convolutional.py) from:
   
   `pool = tf.nn.max_pool(relu, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')`
   
   to:
   
   `pool, pos = tf.nn.max_pool_with_argmax(relu, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')`
2. Run:
   
   `(virtenv)$ python convolutional.py`
### What have you tried?

1.
### Logs or other output that would be helpful

(If logs are large, please upload as attachment).

**Comment by xiongkun** [comment]
I had the same issue when I was trying to get the max indices.

**Comment by mwalton** [comment]
this is a bit of a hack, but copying the gradient for maxpool and registering it for max_pool_with_argmax works. The function signature has an additional arg (presumably this has to do with the argmax). Also the op doesn't have a data_format, so that is left default (NHWC).

```python
from tensorflow.python.framework import ops
from tensorflow.python.ops import gen_nn_ops
@ops.RegisterGradient("MaxPoolWithArgmax")
def _MaxPoolWithArgmaxGrad(op, grad, some_other_arg):
  return gen_nn_ops._max_pool_grad(op.inputs[0],
                                   op.outputs[0],
                                   grad,
                                   op.get_attr("ksize"),
                                   op.get_attr("strides"),
                                   padding=op.get_attr("padding"),
                                   data_format='NHWC')
```

**Comment by girving** [comment]
@mwalton: `some_other_arg` should be called `unused_argmax_grad`, but otherwise that's basically it.  Would you be interesting it submitting your change as a PR?  We'd have to add tests if so (mirroring those for the gradient of the normal max_pool.

**Comment by mwalton** [comment]
@girving  Sure! Should I go ahead and put in the PR; or implement the tests first?

**Comment by girving** [comment]
@mwalton: The tests should go in the same PR.

**Comment by bcaine** [comment]
@mwalton Not sure if you've made any progress on this, but I believe the correct change would be the following:

```python
@ops.RegisterGradient("MaxPoolWithArgmax")
def _MaxPoolGradWithArgmax(op, grad, unused_argmax_grad):
  return gen_nn_ops._max_pool_grad_with_argmax(op.inputs[0],
                                               grad,
                                               op.outputs[1],
                                               op.get_attr("ksize"),
                                               op.get_attr("strides"),
                                               padding=op.get_attr("padding"))
````

Seems to be working on a model I'm training. Haven't had time to write tests for it yet, nor do I know how/what tests are needed for registering an existing op (that appears to have **some** test coverage, see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/pooling_ops_test.py#L521). 

@girving If you can provide some direction on what tests I'd need to add for this change, I can try to pull together a PR.

**Comment by girving** [comment]
@bcaine Awesome!  Tests for gradients are pretty easy: just use `tf.test.compute_gradient_error` and verify that the error is small (1e-4 or 1e-3, typically, due to numerical differences).  You can look at other `compute_gradient_error` examples and mimic.

**Comment by Enet4** [comment]
Are there any updates on this issue? It seems that adding this gradient was attempted in #4014, but not taken place due to commit conflicts. Should I cherry-pick commit dc3d4782cbdf2d98b into a PR?

**Comment by girving** [comment]
@Enet4 Definitely looks stagnated, so feel free to take over.

**Comment by eflavio** [comment]
Hi. I trained a network with @bcaine register ops solution in python. Now I exported my graph using freeze_graph.py to use my network in C++. But there, this gradient is not registered.
Can anyone help how this can be for C++/ source?

**Comment by williamh97** [comment]
Hey, is anyone doing anything about the lack of gradient?
