### ISSUE TITLE
Formatting issue in tf debugger documentation

### ISSUE THREAD

**Issue by Conceptron** [tensorflow/tensorflow#17946]
![image](https://user-images.githubusercontent.com/35289454/37821263-29a87d1c-2ea9-11e8-90b5-7f3bb5f42d49.png)
In the [FAQ section](https://www.tensorflow.org/programmers_guide/debugger#frequently_asked_questions), there seem to be some markdown formatting problems.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by cy89** [comment]
@caisq I don't understand the markup details, but it looks like the source has a "```python" that's indented rather than flush-left around the place where things go wrong. PTAL.

**Comment by caisq** [comment]
@Conceptron  @cy89 thanks for reporting this issue. I believe this has to do with some subtle differences among the two markdown renderers that we have:
1. The one on GitHub
2. The one on the tensorflow.org website.

This file renders correctly on GitHub:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/programmers_guide/debugger.md

cc @MarkDaoust for any possible insight.
