### ISSUE TITLE
Feature request: in tf.train.MonitoredSession(), add operator that makes it possible to skip certain hooks

### ISSUE THREAD

**Issue by aforslow** [tensorflow/tensorflow#17952]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10 Pro 64-bit (10.0, Build 16299)
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
1.6.0
- **Python version**: 
3.6.4
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
I would like an operator that makes it possible to skip a certain/multiple hooks whilst running a tf.train.MonitoredSession(). An example of how this could look is provided below.

The reason why I want this functionality, is that I sometimes want to permit a certain hook(s) from running when calling `mon_sess.run()`. One reason for this can be that the hook generates unnecessary errors when doing this particular `mon_sess.run()` call. Another one can be that I simply don't want the hook's functionality on this particular `mon_sess.run()` call.

### Source code / logs
Example code of how this operator could look:

```
with tf.train.MonitoredTrainingSession(
  hooks=[hook1, hook2, hook3, hook4]
) as mon_sess:
  mon_sess.partial_run(fetches=..., feed_dict=..., skip_hooks=[hook1, hook3])
```

Is this possible?

**Comment by ispirmustafa** [comment]
We decided not to support partial hook run since it will complicate the usage. 
You may find `MonitoredSession.run_step_fn` useful. It let's you run with or without hooks since you access the raw session.
