### ISSUE TITLE
No way to re-enter previous name/variable-scoped context

### ISSUE THREAD

**Issue by meereeum** [tensorflow/tensorflow#1797]
As far as I can tell, there is no way to re-enter the same name_scope or variable_scope (once closed) without the name being "unique-ified."

The [example in the docs](https://www.tensorflow.org/versions/r0.7/api_docs/python/framework.html#Graph.name_scope) shows how to re-enter the original scope from within a nested scope - but not when context is closed.

Perhaps this could be solved by enabling access to the scope reference as ```tf.Variable.scope``` ?

Current hack-y workaround is to manually specify variable name as ```"{}/name".format(previous_scope_name)```

**Comment by gaohuazuo** [comment]
It is actually possible to re-enter a closed variable scope, as in the example below.

```python
with tf.variable_scope('test') as vscope: pass
with tf.variable_scope(vs) as vscope_:
     assert vscope.name == vscope_.name
```

However, the re-entered variable scope does not copy the reuse status of the original one.

**Comment by meereeum** [comment]
@gaohuazuo hmmm that assert statement returns True (as long as you are consistent about ```vscope``` vs ```vs```); however...

```
with tf.variable_scope('foo') as vs:
    x = tf.Variable([1])
with tf.variable_scope(vs) as vs_:
    assert vs.name == vs_.name
    y = tf.Variable([1])
x.name
>>> u'foo/Variable:0'
y.name
>>> u'foo_1/Variable:0'
```

with corresponding non-overlapping name-scopes in tensorboard. This is not changed by passing ```reuse = True```.

**Comment by meereeum** [comment]
Anyway, if possible I think it would be useful to be able to access name-scope of a given variable....without writing a (simple but) hacky regex. The current approach I am using to build layers in a more functional manner does not lend itself to the workflow described above.

**Comment by girving** [comment]
@ebrevdo: @meereeum's example with `y.name == 'foo_1/Variable:0'` looks like a bug.  Could you take a look?

**Comment by ebrevdo** [comment]
Have you tried saving the scope object and reopening it later?

with tf.variable_scope(...) as vs:
  ...

Later:

with tf.variable_scope(vs):
  ...

**Comment by lukaszkaiser** [comment]
I'm working on a CL/PR that at least adds the name scope to variable scope. Will report back here once that's in.

**Comment by lukaszkaiser** [comment]
A recent CL correcting this is now live on master. It includes a unit test that re-enters a variable scope and the original name scope this variable scope was created in (by using the new .original_name_scope property). See here: [variable_scope_test](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/variable_scope_test.py#L297). Closing this now, please re-open or make a new issue if you find more problems!
