### ISSUE TITLE
graph.pb.h missing in cc tutorial

### ISSUE THREAD

**Issue by dl002** [tensorflow/tensorflow#17987]
In tensorflow > cc > tutorials >>graph.pb.h , the code includes the header file `graph.pb.h` . However in the path it specifies (`tensorflow/core/framework/)` there is no such file.

Where is this header file located? I could not find it inside the tensorflow master branch.

**Comment by bignamehyp** [comment]
It's auto generated by the grah.proto file.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/graph.proto
