### ISSUE TITLE
Tensorflow 1.6.0 on ARMv7 import error

### ISSUE THREAD

**Issue by rezaxdi** [tensorflow/tensorflow#17986]
Hi there,

I compiled Bazel and Tensorflow 1.6.0 on an ARMv7 board (OrangePI Zero 512MB) successfully without any error and built the python wheel, Here are related info : 

### System information
- Have I written custom code : no
- OS Platform and Distribution : Armbian 5.41 (Ubuntu 16.04.3 LTS - Kernel 4.14.18-sunxi)
- TensorFlow installed from : source
- TensorFlow version : 1.6.0
- Bazel version : 0.11.1
- CUDA/cuDNN version : N/A
- GPU model and memory : N/A
- Exact command to reproduce : import tensorflow as tf
- Build command : 
`bazel build -c opt --copt="-mfpu=neon-vfpv4" --copt="-funsafe-math-optimizations" --copt="-ftree-vectorize" --copt="-fomit-frame-pointer" --local_resources 512,1.0,1.0 --verbose_failures tensorflow/tools/pip_package:build_pip_package`

In python when I import tensorflow I get this error : 
`
ImportError: /home/user/.local/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow9ConcatCPUINS_8bfloat16EEEvPNS_10DeviceBaseERKSt6vectorISt10unique_ptrINS_6TTypesIT_Li2EiE11ConstMatrixESt14default_deleteIS9_EESaISC_EEPNS8_6MatrixE
`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by rezaxdi** [comment]
Updated the first post

**Comment by Lexicographical** [comment]
Hi! I encountered a similar error and I was able to solve it. Check it out here: [https://github.com/tensorflow/tensorflow/issues/17790](url)

**Comment by rezaxdi** [comment]
Ok, thanks for the tip I removed concat functions from that file and currently building tensorflow again which on my board will take 2 days :) lets hope this time it works !

**Comment by rezaxdi** [comment]
It worked ! actually it didn't take 2 days because it only compiled changed files. thanks a lot !

**Comment by cy89** [comment]
@Lexicographical thanks very much!
@rezaxdi closing, thanks to @Lexicographical 's help.
