### ISSUE TITLE
android demo? mask_rcnn_inception_v2_coco?

### ISSUE THREAD

**Issue by mengxiabing** [tensorflow/tensorflow#17998]
在android demo中，使用mask_rcnn_inception_v2_coco获取到的detection_masks并不是[num_masks, mask_height, mask_width]，请问如何在android中添加mask?
Have I written custom code: YES
OS Platform and Distribution: Android
TensorFlow installed from: 1.7
TensorFlow version: 1.7
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by angersson** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by hoangtubatu123** [comment]
Please provide the code get output detection_masks with mask rcnn on mobile. Thanks
