### ISSUE TITLE
'state' is not defined 

### ISSUE THREAD

**Issue by shikhar1sharma** [tensorflow/tensorflow#180]
When I was trying to run the samples I got an error while running -> new_value = tf.add(state,one)

Error : Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'state' is not defined

>>> import tensorflow as tf
>>> var = tf.Variable(0, name= "counter")
>>> one = tf.constant(1)
>>> new_value = tf.add(state,one)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'state' is not defined

**Comment by vrv** [comment]
Our website has some incorrect code at the moment that we've already fixed in the repo -- if you can look at the corresponding docs in the git repository, it should be fixed.

**Comment by Foorack** [comment]
@shikhar1sharma The fix to this is just more or less renaming the variable 'var' to 'state'. You can find the updated code here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/basic_usage.md#variables-

**Comment by shikhar1sharma** [comment]
Thanks a lot. It worked
