### ISSUE TITLE
TensorFlow 1.5.1 binaries use AVX instructions like 1.6.0 but unlike 1.5.0

### ISSUE THREAD

**Issue by jonasrauber** [tensorflow/tensorflow#18013]
### System information
Linux, Python 3.6

### Describe the problem
For TensorFlow 1.6.0 and later it was announced that the official binaries on PyPI will use AVX instructions and therefore it doesn't run on old GPUs. TensorFlow 1.5.0 did not need AVX instruction support. Unfortunately, the bug fix release 1.5.1 was built with AVX instructions.

The 1.5.1 binary should be rebuild without AVX instructions such that upgrading from 1.5.0 to 1.5.1 is always possible.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jonasrauber** [comment]
- **Have I written custom code**: N/A
- **OS Platform and Distribution**: Linux
- **TensorFlow installed from**: binary
- **TensorFlow version**: 1.5.1
- **Python version**: 3.6
- **Bazel version**: N/A
- **GCC/Compiler version**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

**Comment by asimshankar** [comment]
@av8ramit : Seems like we built 1.5.1 with AVX?

**Comment by av8ramit** [comment]
Yes, @jonasrauber we made a mistake. I'm not sure we can delete images off of pypi, but I'll rebuild without AVX and get those binaries on GCS ASAP. Thanks for filing this issue.

**Comment by av8ramit** [comment]
Can you give these [CPU](https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.5.1-cp36-cp36m-linux_x86_64.whl) or [GPU](https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-1.5.1-cp36-cp36m-linux_x86_64.whl) binaries a try?

**Comment by jonasrauber** [comment]
Checked the CPU version and it works.
The link to the GPU binary is broken.

**Comment by av8ramit** [comment]
Sorry, fixed!

**Comment by av8ramit** [comment]
Updated the release notes. Closing this for now.
