### ISSUE TITLE
what is the correct format of python command?

### ISSUE THREAD

**Issue by ccs1605** [tensorflow/tensorflow#18050]
Hi guys,
i am running tensorflow-gpu in windows environment of anaconda. the backslash \ doesnt work in anaconda prompt eg:
`python train_model.py \
    --training_data=rnn_tutorial_data/training.tfrecord-?????-of-????? \
    --eval_data=rnn_tutorial_data/eval.tfrecord-?????-of-????? \
    --classes_file=rnn_tutorial_data/training.tfrecord.classes`
it works in my ubuntu terminal. i dont want to mess with ubuntu cuz the cuda is 9.1 which doesnt support tensorflow1.6 yet.  what is the correct format command in windows of \ backslash?

Hope to hear your suggestions.

**Comment by mrry** [comment]
The eqiuvalent character in the Windows command prompt is `^`.

https://stackoverflow.com/q/69068/3574081

**Comment by ccs1605** [comment]
thank you @mrry! you are the best.
