### ISSUE TITLE
Tensorflow lite c++ shared library include headers file

### ISSUE THREAD

**Issue by dimitryn** [tensorflow/tensorflow#18060]
Hi ,
1.I build tensorflowlite.so library as describe in https://github.com/tensorflow/tensorflow/issues/16219
2.I added lib to my Android studio project.
3.In C++ class header I added 
#include "tensorflow/contrib/lite/kernels/register.h"
#include "tensorflow/contrib/lite/model.h"
#include "tensorflow/contrib/lite/string_util.h"
#include "tensorflow/contrib/lite/tools/mutable_op_resolver.h"

4.Error compilation :
```
  ../../../../../../../3rdparty/tensorflow/tf_lite/tensorflow/contrib/lite/schema/schema_generated.h:21:37: fatal error: flatbuffers/flatbuffers.h: No such file or directory
   #include "flatbuffers/flatbuffers.h"
                                       ^
  compilation terminated.
  ninja: build stopped: subcommand failed.
```
Please advise how to resolve it,
Thanks.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu
- **TensorFlow installed from (source or binary)**:
Sources
- **TensorFlow version (use command below)**:
Master
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
0.11
- **GCC/Compiler version (if compiling from source)**:
NDK 14
- **CUDA/cuDNN version**:
n/A
- **GPU model and memory**:
n/A
- **Exact command to reproduce**:
bazel build  //tensorflow/contrib/lite:libtensorflowLite.so --crosstool_top=//external:android/crosstool --cpu=arm64-v8a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11"

**Comment by fengye88** [comment]
@dimitryn how did you solve this? I have the same problem (flatbuffers.h)

**Comment by dimitryn** [comment]
1.this is my include in app
#include <tensorflow/contrib/lite/context.h>
#include "tensorflow/contrib/lite/builtin_op_data.h"
#include "tensorflow/contrib/lite/kernels/internal/tensor.h"
#include "tensorflow/contrib/lite/kernels/kernel_util.h"
#include "tensorflow/contrib/lite/kernels/op_macros.h"

2.in  lite BUILD file
cc_binary(
    name = "libtensorflowLite.so",
    linkshared=1,
deps = [
    ":framework",
    "//tensorflow/contrib/lite/kernels:builtin_ops",
],

)

**Comment by fengye88** [comment]
I was trying to compile the minimal.cc, or something similar that can load a model and execute. Do you have that kind of example?

**Comment by conser12** [comment]
@dimitryn I have the same problem, have you solved this by using these includes?
#include "tensorflow/contrib/lite/kernels/register.h"
#include "tensorflow/contrib/lite/model.h"
#include "tensorflow/contrib/lite/string_util.h"
#include "tensorflow/contrib/lite/tools/mutable_op_resolver.h".

I find "flatbuffers/flatbuffers.h" is a third-party library, do we need to install it additionally?

**Comment by dimitryn** [comment]
@conser12  we using this include
in h file
#include "tensorflow/contrib/lite/string_util.h"
#include "tensorflow/contrib/lite/model.h"
#include "tensorflow/contrib/lite/context.h"
#include "tensorflow/contrib/lite/interpreter.h"
#include "tensorflow/contrib/lite/kernels/register.h"
#include "tensorflow/contrib/lite/kernels/internal/tensor.h"
in cpp
#include <tensorflow/contrib/lite/context.h>
#include "tensorflow/contrib/lite/builtin_op_data.h"
#include "tensorflow/contrib/lite/kernels/internal/tensor.h"
#include "tensorflow/contrib/lite/kernels/kernel_util.h"
#include "tensorflow/contrib/lite/kernels/op_macros.h"
