### ISSUE TITLE
KeyError: u'PlaceholderWithDefault' while running transfer learning model through Python

### ISSUE THREAD

**Issue by eldor4do** [tensorflow/tensorflow#1807]
I followed the transfer learning example, and trained on my own image to create my model file. Then in the classify_image.py file, in place of the original 'classify_image_graph_def.pb' file, I replaced it with my model. However, while running I get the following error:

```
Traceback (most recent call last):
  File "classify_image.py", line 214, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "classify_image.py", line 210, in main
    run_inference_on_image(image)
  File "classify_image.py", line 158, in run_inference_on_image
    create_graph()
  File "classify_image.py", line 141, in create_graph
    _ = tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 227, in import_graph_def
    op_def = op_dict[node.op]
KeyError: u'PlaceholderWithDefault'

```

I can run my model fine through the terminal using bazel. Only through Python it is crashing. I'm using version 0.7.1.
Do I need to make any more changes in code before running?

**Comment by vrv** [comment]
It sounds like you're using github sources from HEAD, rather than from r0.7 branch.  Try installing one of our pip nightlies if you want to use source code from HEAD.

**Comment by eldor4do** [comment]
@vrv I checked out to branc r0.7, and tried doing the same with my previously created model, but I still get the same error?

**Comment by vrv** [comment]
If you created the model with HEAD, it's going to have ops have been added since r0.7, so that's not going to work :(.

**Comment by eldor4do** [comment]
But the image retraining thing mentioned [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/image_retraining/index.md). How do I run such model?

**Comment by eldor4do** [comment]
I reinstalled tensorflow with this [release](http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-slave/lastStableBuild/), now I am getting a different error.

>  Traceback (most recent call last):
>   File "classify_image.py", line 214, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
>     sys.exit(main(sys.argv))
>   File "classify_image.py", line 210, in main
>     run_inference_on_image(image)
>   File "classify_image.py", line 169, in run_inference_on_image
>     softmax_tensor = sess.graph.get_tensor_by_name('softmax:0')
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2305, in get_tensor_by_name
>     return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2202, in as_graph_element
>     "graph." % (repr(name), repr(op_name)))
> KeyError: "The name 'softmax:0' refers to a Tensor which does not exist. The operation, 'softmax', does not exist in the graph."

**Comment by eldor4do** [comment]
@vrv Sorry to make this seem like a progress report, but I fixed all the above issues, the code is running now, but for whatever input image I seem to give as input, it's giving me the same output. Same prediction values. I am not able to get the output I got from running it via bazel. What could be the problem here?

**Comment by janislejins** [comment]
> @vrv Sorry to make this seem like a progress report, but I fixed all the above issues, the code is running now, but for whatever input image I seem to give as input, it's giving me the same output. Same prediction values. I am not able to get the output I got from running it via bazel. What could be the problem  here?<
How'd you fix it?

**Comment by eldor4do** [comment]
@janislejins Updating tensorflow should do the trick.
