### ISSUE TITLE
Android speech recognition sample averaging wrong values

### ISSUE THREAD

**Issue by NearLinHere** [tensorflow/tensorflow#18082]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: none
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  not related to this question
- **TensorFlow installed from (source or binary)**: not related to this question
- **TensorFlow version (use command below)**: not related to this question
- **Python version**: not related to this question
- **Bazel version (if compiling from source)**: not related to this question
- **GCC/Compiler version (if compiling from source)**: not related to this question
- **CUDA/cuDNN version**: not related to this question
- **GPU model and memory**: not related to this question
- **Exact command to reproduce**: not related to this question

### Describe the problem &  Source code / logs
Please refer to this question and comments on stackoverflow: https://stackoverflow.com/questions/49269555/logging-and-deque-operation-problems-in-tensorflow-android-speech-recognition-sa

In brief, previousResults.addLast should be revised. Otherwise, it will take wrong values to average.

**Comment by skye** [comment]
I'm sorry, but we can't answer stackoverflow q's here. If you there's a bug, please file a new issue filling out the template.
