### ISSUE TITLE
Python 3.5 Wheel

### ISSUE THREAD

**Issue by JLCCI** [tensorflow/tensorflow#1808]
Thanks for all your work so far.

Is there any chance of providing a wheel for Python 3.5? I have been having a rough time trying to install it from scratch and a wheel would be very helpful!

**Comment by gustavla** [comment]
This is most certainly not a recommended approach, but I downloaded the py34 wheel and simply renamed the file to py35 and tried installing it. It has been working so far.

**Comment by martinwicke** [comment]
It should work, we don't do anything special for 3.5 -- the only difference would be the name (in fact, our Mac wheels are built with 3.5 without any changes).

We may in future provide more binaries, ideally directly in pypi, but I will close this issue for now.

**Comment by caisq** [comment]
With PR #2585, we now have Linux Python 3.5 whl files built and tested nightly. The links to the whl files and build history can be found in the main README.md: 
https://github.com/tensorflow/tensorflow/

**Comment by JLCCI** [comment]
Fantastic, many thanks for preparing the 3.5 wheel, it is much appreciated.
