### ISSUE TITLE
Distributed TensorFlow got error message with the MPI collective Ops units test

### ISSUE THREAD

**Issue by jianyinglang** [tensorflow/tensorflow#18092]
Have I written custom code:  None
OS Platform and Distribution: Linux Ubuntu 16.04
Open MPI version: 3.0.0
TensorFlow installed from: b'v1.7.0-rc1-816-g1712002ad0' 1.7.0-rc1
Bazel version: 0.11.1 
Python version: 3.5.2
GCC version: 6.3.0
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: `mpirun -np 1 python mpi_allreduce_test.py` under directory `tensorflow/tensorflow/contrib/mpi_collectives`

I ran the unit test under directory `tensorflow/tensorflow/contrib/mpi_collectives` and the run command is `mpirun -np 1 python mpi_allreduce_test.py` . I got the following error message:
Could someone please help me take a look at this? Thanks!

```
WARNING:tensorflow:From /ec/fm/disks/nrv_algo_home01/langjian/.tf_17/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):
  File "mpi_allreduce_test.py", line 23, in <module>
    import tensorflow.contrib.mpi_collectives as mpi
  File "$HOME/.tf_17/lib/python3.5/site-packages/tensorflow/contrib/mpi_collectives/__init__.py", line 128, in <module>
    from tensorflow.contrib.mpi_collectives.python.ops.mpi_ops import init
  File "$HOME/.tf_17/lib/python3.5/site-packages/tensorflow/contrib/mpi_collectives/python/ops/mpi_ops.py", line 29, in <module>
    resource_loader.get_path_to_datafile('_mpi_ops.so'))
  File "$HOME/.tf_17/lib/python3.5/site-packages/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "$HOME/.tf_17/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "$HOME/.tf_17/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: $HOME/.tf_17/lib/python3.5/site-packages/tensorflow/contrib/mpi_collectives/python/ops/_mpi_ops.so: undefined symbol: _ZN10tensorflow7contrib15mpi_collectives7MPITypeIiEEP15ompi_datatype_tv
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[18657,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jianyinglang** [comment]
@tensorflowbutler Thanks a lot for the quick response! See the updated issue template below:
Have I written custom code:  None
OS Platform and Distribution: Linux Ubuntu 16.04
Open MPI version: 3.0.0
TensorFlow installed from: b'v1.7.0-rc1-816-g1712002ad0' 1.7.0-rc1
Bazel version: 0.11.1 
Python version: 3.5.2
GCC version: 6.3.0
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: `mpirun -np 1 python mpi_allreduce_test.py`

**Comment by asimshankar** [comment]
@jthestness @poxvoculi : Any suggestions here? 

It seems to be complaining about not finding `ompi_datatype_t* tensorflow::contrib::mpi_collectives::MPIType<int>()`, which should be defined in `ring.cc`.

Just to be clear: You did build from sources using the instructions in [`contrib/mpi/README.md`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/mpi/README.md), right?

**Comment by jianyinglang** [comment]
@asimshankar I did build the code using the instructions in `contrib/mpi/README.md`. And then run the unit test `mpirun -np 1 python mpi_allreduce_test.py` under directory `tensorflow/tensorflow/contrib/mpi_collectives`. I did not set `server = tf.train.Server(cluster, job_name="local", task_index=0, protocol='grpc+mpi')`.

**Comment by jthestness** [comment]
We've tested TF mpi_collectives using OpenMPI 2.0.x, but we haven't thoroughly tested with OpenMPI 3.0.x. OpenMPI 2.0.x defines `MPI_Datatype` as `ompi_datatype_t` in `include/mpi.h`, so the symbol exists and is detected correctly. I see the same declarations in 3.0.x, so it should work the same if OpenMPI is built the same way. I would recommend checking the symbol table in your MPI libraries to see if the symbol is defined. If not, you might need to reconfigure and rebuild OpenMPI.

**Comment by jianyinglang** [comment]
@jthestness We checked the mpi.h header file and did see that it defines `MPI_Datatype` as `ompi_datatype_t` in OpenMPI3.0.0.
Which gcc compiler version do you use for the test? Thanks!

**Comment by jthestness** [comment]
@jianyinglang: We're using GCC 4.8.4. I would be very surprised if the GCC version is causing the problem. Did you check whether the symbol is defined in your MPI libraries (e.g., `objdump -t <lib> | grep ompi_datatype_t`)?

**Comment by jianyinglang** [comment]
@jthestness Yes, I did see it in the lib folder.
```
00000000002e0b40 g     O .data  0000000000000040              ompi_datatype_t_class
00000000002ffe70 g     O .bss   0000000000000008              ompi_datatype_t_type_force_inclusion
00000000002e0b40 g     O .data  0000000000000040              ompi_datatype_t_class
00000000002ffe70 g     O .bss   0000000000000008              ompi_datatype_t_type_force_inclusion
00000000002e0b40 g     O .data  0000000000000040              ompi_datatype_t_class
00000000002ffe70 g     O .bss   0000000000000008              ompi_datatype_t_type_force_inclusion
```

**Comment by jthestness** [comment]
Ok, you're going to need to step through the chain of defining symbols across the libraries to see where there is a missing link. Check that the Tensorflow library you built points to the correct MPI library with `ldd <path_to_tf_build>/python/_pywrap_tensorflow_internal.so`. If that's correct, then check the mpi_collectives library: `ldd <path_to_tf_build>/contrib/mpi_collectives/python/ops/_mpi_ops.so` and then `objdump -t <path_to_tf_build>/contrib/mpi_collectives/python/ops/_mpi_ops.so | grep ompi_datatype_t`. The latter should show something like this (note "F" means the function is defined, you probably have a "U" or the functions are missing):

```
00000000000265f0 g     F .text	0000000000000008              _ZN10tensorflow7contrib15mpi_collectives7MPITypeIxEEP15ompi_datatype_tv
00000000000265e0 g     F .text	0000000000000008              _ZN10tensorflow7contrib15mpi_collectives7MPITypeIiEEP15ompi_datatype_tv
00000000000265d0 g     F .text	0000000000000008              _ZN10tensorflow7contrib15mpi_collectives7MPITypeIfEEP15ompi_datatype_tv
```

If the function is not defined ("U" or missing), then something went wrong with the TF build. Be sure that you either opt 'yes' when prompted to configure the build with MPI or set the environment variable `TF_NEED_MPI=1` before configuring.

Another thing you could try is to roll back to TF 1.5.0, which we have working internally. (We haven't tested 1.7.0-rc1, and unfortunately, the regressions architecture for TF doesn't permit us to run MPI tests, so changes to TF can break the mpi_collectives code).

**Comment by chengdianxuezi** [comment]
mpirun -np 1 python mpi_allreduce_test.py

**Comment by chengdianxuezi** [comment]
I run mpirun -np 1 python mpi_allreduce_test.py,the test pass;
but when run mpirun -np 3 python mpi_allreduce_test.py 
I got error 
```
1: iter 0
rank 2: My output is 330772870.0
rank 2: Our output is 170543409.0
rank 0: My output is 11908270.0
rank 0: Our output is 170543409.0
2: iter 0
0: iter 0
[e92e09614.em21:08680] Read -1, expected 2362084, errno = 38
[e92e09614.em21:08681] Read -1, expected 2362080, errno = 38
[e92e09614.em21:08679] Read -1, expected 2362080, errno = 38
[e92e09614.em21:08680] Read -1, expected 2362080, errno = 38
[e92e09614.em21:08681] Read -1, expected 2362084, errno = 38
[e92e09614.em21:08679] Read -1, expected 2362080, errno = 38
[e92e09614.em21:08680] Read -1, expected 2362080, errno = 38

```

**Comment by chengdianxuezi** [comment]
I run mpirun -np 1 python mpi_allreduce_test.py ;the test pass.
but when I run mpirun -np 3 python mpi_allreduce_test.py, the test failed
```
1: iter 0
rank 2: My output is 330772870.0
rank 2: Our output is 170543409.0
rank 0: My output is 11908270.0
rank 0: Our output is 170543409.0
2: iter 0
0: iter 0
[e92e09614.em21:08680] Read -1, expected 2362084, errno = 38
[e92e09614.em21:08681] Read -1, expected 2362080, errno = 38
[e92e09614.em21:08679] Read -1, expected 2362080, errno = 38
[e92e09614.em21:08680] Read -1, expected 2362080, errno = 38
[e92e09614.em21:08681] Read -1, expected 2362084, errno = 38
[e92e09614.em21:08679] Read -1, expected 2362080, errno = 38
[e92e09614.em21:08680] Read -1, expected 2362080, errno = 38
```

**Comment by jthestness** [comment]
Hi @chengdianxuezi: Your issue looks different from the issue in this thread. Can you please create a new TF Github issue and follow TF's issue creation process (i.e., include information about the version of TF and other software that you are using. See here: https://github.com/tensorflow/tensorflow/issues/new)?

**Comment by ahmet-uyar** [comment]
I have the same problem. 
-------------------------------------------------------------------
tensorflow/contrib/mpi_collectives$ mpirun -np 1 python mpi_allreduce_test.py
Traceback (most recent call last):
  File "mpi_allreduce_test.py", line 23, in <module>
    import tensorflow.contrib.mpi_collectives as mpi
  File "/home/research/virtualenvs/tfenv/lib/python3.5/site-packages/tensorflow/contrib/mpi_collectives/__init__.py", line 128, in <module>
    from tensorflow.contrib.mpi_collectives.python.ops.mpi_ops import init
  File "/home/research/virtualenvs/tfenv/lib/python3.5/site-packages/tensorflow/contrib/mpi_collectives/python/ops/mpi_ops.py", line 29, in <module>
    resource_loader.get_path_to_datafile('_mpi_ops.so'))
  File "$HOME/virtualenvs/tfenv/lib/python3.5/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "$HOME/virtualenvs/tfenv/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: $HOME/virtualenvs/tfenv/lib/python3.5/site-packages/tensorflow/contrib/mpi_collectives/python/ops/_mpi_ops.so: undefined symbol: _ZN10tensorflow7contrib15mpi_collectives7MPITypeIiEEP15ompi_datatype_tv
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[35887,1],0]
  Exit code:    1
--------------------------------------------------------------------------

when I check ompi_datatype_t in _mpi_ops.so, I got following output:
$ objdump -t $HOME/virtualenvs/tfenv/lib/python3.5/site-packages/tensorflow/contrib/mpi_collectives/python/ops/_mpi_ops.so | grep ompi_datatype_t
0000000000000000         *UND*	0000000000000000              _ZN10tensorflow7contrib15mpi_collectives7MPITypeIiEEP15ompi_datatype_tv
0000000000000000         *UND*	0000000000000000              _ZN10tensorflow7contrib15mpi_collectives7MPITypeIxEEP15ompi_datatype_tv
0000000000000000         *UND*	0000000000000000              _ZN10tensorflow7contrib15mpi_collectives7MPITypeIfEEP15ompi_datatype_tv

--------------------------------------------------------------------------

I have ubuntu 16.04, 
tensorflow branch r1.13, (only mpi is enabled, all other options are disabled on build)
python 3.5,
gcc (Ubuntu 4.8.5-4ubuntu2) 4.8.5, 
tested with both bazel 0.19 and 0.21.
tested with OpenMPI 2.1.6, 3.1.2, 4.0.1

not sure how to proceed. Any help would be really appreciated.

**Comment by tilakrayal** [comment]
@jianyinglang ,
We see that you are using older version of tensorflow (1.x) which is not actively supported. We recommend that you upgrade to latest stable version of tensorflow 2.6.0 and let us know if the issue still persists in newer versions .Thanks!
