### ISSUE TITLE
can I use tracker(used android example) from opencv tracking lib?

### ISSUE THREAD

**Issue by c13proto** [tensorflow/tensorflow#18119]
The performance of tracker used android example is very nice.
I really want to use it via opencv tracking library.
is it possible in the future? anyone send pull request to opencv library?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by andrewharp** [comment]
The object tracker is open sourced, so you are welcome to reproduce it as you wish within the Apache 2.0 guidelines.

Questions regarding making PRs to the opencv repo in particular are probably best asked at https://github.com/opencv/opencv
