### ISSUE TITLE
importing tensorflow.contrib produces a warning

### ISSUE THREAD

**Issue by yaohualibin** [tensorflow/tensorflow#18111]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows and Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.7
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0/7
- **GPU model and memory**:
- **Exact command to reproduce**:
python
import tensorflow.contrib

### Describe the problem
Using tensorflow.contrib produces a warning in 1.7. The warning is

WARNING:tensorflow:From ...\envs\tf-1.7\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.

**Comment by chiachunfu** [comment]
Encounter the same warning with python 2.7, TF1.7.0-rc1 from source, ubuntu 16.04, Cuda 9.0, Cudnn 7.0.5

**Comment by annarev** [comment]
Thank you for the report!
I cherrypicked relevant fix in 1.7: https://github.com/tensorflow/tensorflow/pull/18130
So, this will be fixed in 1.7.1.

**Comment by angersson** [comment]
Thanks @annarev!

**Comment by stefanievonk** [comment]
When will 1.7.1 be released? Is there a temporary solution to mute this output?

**Comment by erickrf** [comment]
@stefanievonk you can create a logging filter. A bit cumbersome but it gets the job done:

```
import logging

class WarningFilter(logging.Filter):
    def filter(self, record):
        msg = record.getMessage()
        tf_warning = 'retry (from tensorflow.contrib.learn.python.learn.datasets.base)' in msg
        return not tf_warning
            
logger = logging.getLogger('tensorflow')
logger.addFilter(WarningFilter())
```

**Comment by annarev** [comment]
Sorry for delay in response.
We decided to include the fix in 1.8.0rc0 instead of releasing 1.7.1.
1.8.0rc0 should (most likely) be out later today.

**Comment by Nasnl** [comment]
I used 1.8.0rc0 just now and still see the same error:

WARNING:tensorflow:From C:\Users\Gebruiker\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.

Python 3.6.4, Windows10

**Comment by annarev** [comment]
@Nasnl do you see it when importing tensorflow.contrib?

**Comment by Nasnl** [comment]
Hi @annarev 
Thanks for checking this out. Sorry for not mentioning this right away.

No, I get the message when I gave the command "python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config" (creating a recognition engine for neighborhood parking issues to support the neighborhood detecting the amount of parked cars in the streets in a smarter way than manually counting them).

**Comment by kirk86** [comment]
I still see this message with tf 1.8 when following the tensorflow example of loading mnist dataset:
```
from tensorflow.examples.tutorials.mnist import input_data
mnist = nput_data.read_data_sets("MNIST_data/", one_hot=True) 
```

**Comment by annarev** [comment]
@Nasnl, sorry, forgot to reply back then. If the code uses "retry" from tensorflow.contrib.learn.python.learn.datasets.base then the error is expected. Original issue reported here happened when just importing "tensorflow.conrib" causes this warning to be printed.

@kirk86, the warning gets printed because tensorflow.examples.tutorials.mnist.input_data depends on 
from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/input_data.py
which depends on deprecated "maybe_download" function:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/datasets/base.py
This issue is different from the one originally reported here. A fix would require updating the example so that it doesn't depend on this deprecated function. Can you open a separate issue for that?

**Comment by sachinprabhu007** [comment]
Warning still persists in tf 1.8 

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data')

**Comment by Sunil1997** [comment]
Yes,still it's come

**Comment by boukicher** [comment]
Did you resolve this issue ?
