### ISSUE TITLE
[feature request] port benchmarks to google benchmark

### ISSUE THREAD

**Issue by dominichamon** [tensorflow/tensorflow#1813]
you have a simple benchmark framework in tensorflow/tensorflow/core/platform/test_benchmark.h but i was curious if you'd be interested in integrating with github.com/google/benchmark instead.

i'm happy to help with the integration if you are.

**Comment by martinwicke** [comment]
We're working on a benchmarking framework and some infrastructure. I'll let @ebrevdo comment.

**Comment by ebrevdo** [comment]
Gchat me and we can discuss.

**Comment by girving** [comment]
@dominichamon, @ebrevdo: What was the result of the offline discussion?

**Comment by ebrevdo** [comment]
No concrete plans to merge code, but backward compatible commits are welcome.

**Comment by aselle** [comment]
Since no action has been taking in a while and it appears that there isn't compelling motivation to use the google framework, closing for now. @annarev, reopen if you feel this is likely to be a priority.
