### ISSUE TITLE
Tensorflow model save using c++

### ISSUE THREAD

**Issue by modkzs** [tensorflow/tensorflow#18141]
I can't find any c++ api to save a tensorflow model. Is there any way to implement this?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
