### ISSUE TITLE
Implementing a Siamese Network

### ISSUE THREAD

**Issue by johnrowlay** [tensorflow/tensorflow#1814]
I want to implement a Siamese Convolutional Neural Network, where two images share weights in the convolutional layers, and are then concatenated before being passed through the fully-connected layers. I have tried an implementation, but it seems rather a "hacked" solution. In particular, I have defined an operation on tensors as simply a Python function, and I'm not sure whether this is allowed.

Here is the code I have tried:

```
images = tf.placeholder(tf.float32, shape=[None, 64 * 64])
# Convolutional layers
# ...
# ...
# Results in pool3_flat, which is the flattened output of the third convolutional layer
pool3_flat = tf.reshape(pool3, [-1, 8 * 8 * 128])

# Now, merge the image pairs, where each pair is composed of adjacent images in the batch, with a stride of 2
def merge_pairs():
  # Create a tensor to store the merged image pairs
  # The batch size is 128, therefore there will be 64 pairs (64 in the first dimension of this tensor)
  merged_pairs = tf.Variable(tf.zeros([64, 8 * 8 * 128]))
  # Split the images into 64 pairs
  pairs = tf.split(0, 64, pool3_flat)
  # For each pair, concatenate the two images across dimension 1, and set this tensor in the appropriate row of merged_pairs
  for pair_num, pair in enumerate(pairs):
    merged_pair = tf.concat(1, pair)
    merged_pairs[pair_num] = merged_pair

# Proceed with operations on the merged_pair tensor, as if the batch size is 64
fc4 = tf.matmul(merge_pairs, weights4)
# ...
# ...
```

When running this, I get the following error message:

```TypeError: Expected binary or unicode string, got <function merge_pairs at 0x7f006edbed70>```

So it seems that I cannot simple replace a TensorFlow operation with a Python function. Is there a way to implement a Siamese network using built-in operations in TensorFlow?

**Comment by martinwicke** [comment]
You should make merge_pairs return its result, and call it in the call to matmul.

This type of question is generally better answered on StackOverflow. I will close this issue, we're trying to keep issues for bug reports.
