### ISSUE TITLE
Why tensorflow.org is not reachable from Iran? 

### ISSUE THREAD

**Issue by pbashivan** [tensorflow/tensorflow#18169]
When I try to access [tensorflow.org](tensorflow.org) from my computer in Iran I get the error "403: Your client does not have permission to get URL / from this server. That’s all we know."

I didn't know any other (reachable) location to post it. Would appreciate it if someone would respond/act on this.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by martinwicke** [comment]
tensorflow.org is hosted on GCP. You appear to be seeing this issue: https://stackoverflow.com/questions/35150576/any-suggestion-about-accessing-google-cloud-hosted-website-from-iran

We won't be able to do much about that, since we rely on GCP for hosting.
