### ISSUE TITLE
tf.layers.Input missing on 1.7

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/tensorflow#18179]
Recently updated to 1.7 and a script is now crashing because tf.layers.Input is missing. I just check the docs and it appears until 1.6 but it wasn't deprecated.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by facaiy** [comment]
@fchollet `tf.layers.Input` seem removed in 32ccc6a0. Is this a mistake?

**Comment by facaiy** [comment]
@cgarciae Would you replace it by `tf.keras.layers.Input`? I think it should work for you as well.

**Comment by fchollet** [comment]
Sorry for the inconvenience, it was not possible to keep it in the namespace after relocating the code. This is deliberate.

You can now import it as `tf.keras.Input`.

**Comment by facaiy** [comment]
@fchollet I think the change should have been explained in [1.7 release notes](https://github.com/tensorflow/tensorflow/releases/tag/v1.7.0)
