### ISSUE TITLE
how to debug lite jni so in android 

### ISSUE THREAD

**Issue by skyson** [tensorflow/tensorflow#18173]
after building the so of lite, some how i need to debug in the android mobile; how can i debug the native c++ code using android studio?  appriciated

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by kang-lee** [comment]
Here is the guideline to debug code in android studio: https://developer.android.com/studio/debug/.

You can use LLDB to debug your native code. If you want to debug the whole flow: java --> jni --> native, I would recommend you to use logs for debugging.
