### ISSUE TITLE
400 Bad Request caused by https://github.com/google/boringssl.git:

### ISSUE THREAD

**Issue by Yunlong-He** [tensorflow/tensorflow#1817]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Ubuntu 14.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
yunlong@dl-y9:~/github/tensorflow$ ls -l /usr/local/cuda/lib/libcud*
-rw-r--r-- 1 root root 189170 Mar 19 15:48 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Mar 19 15:48 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Mar 19 15:48 /usr/local/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Mar 19 15:48 /usr/local/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Mar 19 15:48 /usr/local/cuda/lib/libcudart_static.a

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

If installed from sources, provide the commit hash:
commit 51f5f6be3ede7242b01c4bdf136de938fd00839f

### Steps to reproduce
yunlong@dl-y9:~/github/tensorflow$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
ERROR: /home/yunlong/github/tensorflow/tensorflow/core/distributed_runtime/rpc/BUILD:207:1: no such package '@grpc//': Error cloning repository: https://github.com/google/boringssl.git: 400 Bad Request caused by https://github.com/google/boringssl.git: 400 Bad Request and referenced by '//tensorflow/core/distributed_runtime/rpc:grpc_server_lib'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.189s

### What have you tried?
yunlong@dl-y9:~/tmp$ git clone https://github.com/google/boringssl.git
Cloning into 'boringssl'...
remote: Counting objects: 24195, done.
remote: Compressing objects: 100% (117/117), done.
Receiving objects:  12% (3019/24195), 2.64 MiB | 256.00 KiB/s     

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by Yunlong-He** [comment]
Note that v0.7.1 can be built successfully.

**Comment by girving** [comment]
Unfortunately it looks like this fell through the cracks.  @Yunlong-He: Do you know if it's still an issue?  @martinwicke: Is this a known problem?

**Comment by martinwicke** [comment]
If the connectivity to github is patchy, these things happen. Those are
usually transient issues though, sadly, bazel does not retry anything.

**Comment by capers** [comment]
FWIW I'm getting the same error, and doesn't seem to be intermittent. I can repeatedly clone https://github.com/google/boringssl.git but always get the error:
```
Error cloning repository: https://github.com/google/boringssl.git: 400 Bad Request caused by https://github.com/google/boringssl.git: 400 Bad Request and referenced by '//tensorflow/core/distributed_runtime/rpc:grpc_server_lib'.
```
when running
`bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`
