### ISSUE TITLE
python cifar10_eval.py hang forever sometimes

### ISSUE THREAD

**Issue by zhanglix** [tensorflow/tensorflow#1819]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Linux ubuntu 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
james@ubuntu:~/practice$ ls -l /usr/local/cuda*
lrwxrwxrwx 1 root root    8 Mar 29 13:21 /usr/local/cuda -> cuda-7.5

/usr/local/cuda-7.5:
total 32
drwxr-xr-x  3 root root 4096 Mar 29 14:48 bin
drwxr-xr-x  2 root root 4096 Mar 29 12:16 doc
lrwxrwxrwx  1 root root   28 Aug 16  2015 include -> targets/x86_64-linux/include
lrwxrwxrwx  1 root root   24 Aug 16  2015 lib64 -> targets/x86_64-linux/lib
-rw-r--r--  1 root root  365 Aug 16  2015 LICENSE
drwxr-xr-x  7 root root 4096 Mar 29 12:16 nvvm
-rw-r--r--  1 root root  365 Aug 16  2015 README
drwxr-xr-x 11 root root 4096 Mar 29 14:48 samples
drwxr-xr-x  3 root root 4096 Feb  3 18:04 targets
-rw-r--r--  1 root root   20 Aug 15  2015 version.txt

installed from docker.
tag   "b.gcr.io/tensorflow/tensorflow:latest-devel-gpu"
(id:7f61540f94b2951574fd313b5980b850c7326933fc5a857779a36a94443c64cb)

### Steps to reproduce
1. pull images from docker
2.docker run -it -v /lib/modules/4.2.0-22-generic:/lib/modules/4.2.0-22-generic -v /lib/modules/4.2.0-23-generic:/lib/modules/4.2.0-23-generic -v /lib/modules/4.2.0-25-generic:/lib/modules/4.2.0-25-generic -v /lib/modules/4.2.0-27-generic:/lib/modules/4.2.0-27-generic -v /usr/lib/x86_64-linux-gnu/libcuda.so:/usr/lib/x86_64-linux-gnu/libcuda.so -v /usr/lib/x86_64-linux-gnu/libcuda.so.1:/usr/lib/x86_64-linux-gnu/libcuda.so.1 -v /usr/lib/x86_64-linux-gnu/libcuda.so.352.79:/usr/lib/x86_64-linux-gnu/libcuda.so.352.79 --device /dev/nvidia0:/dev/nvidia0 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-uvm:/dev/nvidia-uvm -v /home/james:/home/james -P tensor-james
3. python /usr/local/lib/python2.7/dist-packages/tensorflow/models/image/cifar10/cifar10_train.py 
4. stop train after some checkpoint file been written to disk
5. python /usr/local/lib/python2.7/dist-packages/tensorflow/models/image/cifar10/cifar10_eval.py  --run_once true
6. the last step hanging forever some times. 

### What have you tried?
1.I add some logs to the cifar10_eval.py and it comes out that all threads of queue runner is active, and  it is hanging at the first call to   `predictions = sess.run([top_k_op])`

print([t.isAlive() for t in threads]);
      while step < num_iter and not coord.should_stop():
        print("begin step %d;" %(step))
        predictions = sess.run([top_k_op])
        print("step %d: %d;" %(step, true_count))

[train_checkpoints.zip](https://github.com/tensorflow/tensorflow/files/209762/train_checkpoints.zip)

### Logs or other output that would be helpful

I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
...
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning N
UMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: GeForce GTX 980 Ti
major: 5 minor: 2 memoryClockRate (GHz) 1.291
pciBusID 0000:01:00.0
Total memory: 5.99GiB
Free memory: 5.43GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:717] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 1.0KiB
... 
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:73] Allocating 5.14GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:83] GPU 0 memory begins at 0x706400000 extends to 0x84ef38000

**Comment by sherrym** [comment]
Did you pass in --checkpoint_dir=your-checkpoint-dir?

Sherry

**Comment by sherrym** [comment]
No user response. Closing as not reproducible. Please open a new bug if the issue persists.
