### ISSUE TITLE
How to implement fine-tune training in blstm?

### ISSUE THREAD

**Issue by SPY-Ming** [tensorflow/tensorflow#18190]
I just want a cnn network,blstm network,word embedding and implement them separately
Save their params and use into a new network.
I have tried tf.saver\restore and tf.collection,it dosen't work.
How and I do that?
thank u very much

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
