### ISSUE TITLE
As per documentation Tensorflow 1.5 with Cuda -8 

### ISSUE THREAD

**Issue by Shehz** [tensorflow/tensorflow#18203]
Hi,

As per documentation in the below link:

[https://www.tensorflow.org/versions/r1.5/install/install_linux#InstallingVirtualenv](url)

Requirement for tensorflow 1.5 is Cuda 8. I installed tensorflow using the following tf binary url https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.5.0rc1-cp27-none-linux_x86_64.whl

However, still it is asking for cuda 9. Is there any .whl, which supports cuda 8 ( tensorflow 1.5).

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Shehz** [comment]
Have I written custom code - NA
OS Platform and Distribution - Ubuntu 16.04
TensorFlow installed from - Followed the instructions from https://www.tensorflow.org/versions/r1.5/install/install_linux#InstallingVirtualenv
TensorFlow version - 1.5
Bazel version - NA
CUDA/cuDNN version - Cuda-8
GPU model and memory - Nvidia Geforce GTX 1070
Exact command to reproduce
Followed the tensorflow installation instructions in virtual env from the following link:
https://www.tensorflow.org/versions/r1.5/install/install_linux

Used the following tf binary url to install:
 https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.5.0rc1-cp27-none-linux_x86_64.whl

After, installing while importing tensorflow  I'm getting the following error:

ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

However, in the link  it requires only cuda-8.0.

**Comment by JSLBen** [comment]
I have the same problem. I believe while TF devs upgraded to 1.7, they also added cuda 9.0 support for some of the prev versions, which lead to a backward compatibility issue. This problem should be solved easily, and quickly.

**Comment by gunan** [comment]
@av8ramit Do you know how this may have happened?
Or do we simply have a documentation issue?

**Comment by MarkDaoust** [comment]
Fixed.

https://www.tensorflow.org/versions/r1.5/install/

**Comment by fpgdubost** [comment]
@MarkDaoust The link is dead.

**Comment by MarkDaoust** [comment]
This info has moved: look for the v1.5 line in the gpu table:

 https://www.tensorflow.org/install/source#linux
