### ISSUE TITLE
TensorFlow verbose logging is too verbose even at level 1

### ISSUE THREAD

**Issue by samikama** [tensorflow/tensorflow#18243]
Hello,

This is more of a feature request than an issue. Currently there is no convention on verbose logging of TensorFlow with VLOG() levels. This is making it pretty useless for development purposes. For example at  TF_CPP_MIN_VLOG_LEVEL=1, tensorflow/core/framework/log_memory.cc is printing all allocations and de-allocations which are spamming the log with hundreds of messages if not thousands per second. on the other hand tensorflow/core/common_runtime/graph_execution_state.cc is dumping nodedefs to the log file which sometimes contain the input data, creating hundreds of megabytes of strings as outputs . Similarly extremely verbose output is printed even at the verbosity level 1 making levels useless and logs unusable other than a few tiny example cases probably. 

It would be nice to establish some conventions for logging levels on number of messages per second or amount of data printed to the log. Something in the lines of
0 < level 1 <= 0.1 msg/s
0.1 msg/s <= level 2 <= ~1-2 msg/s
1-2msg/s <= level 3 <= ~5-10 msg/s
.... and similarly for amount of information printed in the logs.

But the best solution would be to have a more advanced logging structure that would allow users to selectively enable or disable different logging levels for each module but I don't know how hard would it be to implement. 

I am creating this issue to bring this feature/improvement request into attention.

Thanks,
Sami

**Comment by yaroslavvb** [comment]
Internally to Google there's a `vmodule` feature that lets you do per-level customization

IE, `--vmodule=gpu_util=2,executor=2` will allow vlog=2 messages originating from gpu_util.cc and executor.cc

I think it would be nice to bring this feature in open-source version

**Comment by samikama** [comment]
@yaroslavvb Yes that would be great and greatly simplifies issue pinpointing.

**Comment by yaroslavvb** [comment]
cc @martinwicke in case he knows a good person to tackle this

**Comment by yaroslavvb** [comment]
to recap: without vmodule, running beyond v=1 is not practical, last time I ran with vlog=2 my emacs shell buffer gets stuck before getting to interesting stuff, probably GBs of text

**Comment by michaelisard** [comment]
@asimshankar do you want to assign this to someone or leave as community support?

**Comment by asimshankar** [comment]
I believe [glog](https://github.com/google/glog) does support `vmodule`.
That said, I don't think we'll be working on switching the logging implementation/adding a vmodule feature in the near future, so marking this as "Contributions Welcome".

We'll be happy to see pull requests bumping up the log level of existing lines.

Deferring to @martinwicke about whether switching to glog is an option.

**Comment by martinwicke** [comment]
Forgive my ignorance -- what's the relationship between glog and absl logging? Ideally we wouldn't have both.

Independently, making TF more conservative about logs is a fine thing to do. I agree high volume logging levels are currently useless.

**Comment by asimshankar** [comment]
@martinwicke : Haven't looked in detail enough to be sure. Let's chat with the absl/glog folks off this thread.

**Comment by samikama** [comment]
vmodule is implemented now
