### ISSUE TITLE
Tensorflow assume the pointer size is 64bit cause problem on 32bit platform

### ISSUE THREAD

**Issue by fo40225** [tensorflow/tensorflow#18241]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 1709 x64
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 3.6.4
- **Bazel version (if compiling from source)**: cmake 3.9.6
- **GCC/Compiler version (if compiling from source)**: msvc 1911 (vs 2017 15.4)
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

VS2017 x64_x86 Cross Tools Command Prompt

    cmake .. -G "Visual Studio 15 2017" -T host=x64 ^
    -DCMAKE_BUILD_TYPE=Release ^
    -Dtensorflow_BUILD_PYTHON_BINDINGS=OFF ^
    -Dtensorflow_BUILD_SHARED_LIB=ON ^
    
    cmake --build . --target tensorflow --config Release -- /fileLogger

### Describe the problem

Tensorflow should use proper pointer type instead of hardcode int64.

### Source code / logs
    "C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tensorflow.vcxproj" (預設目標) (1) ->
    "C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj" (預設目標) (13) ->
    (ClCompile 目標) -> 
      C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\batch_kernels.cc(160): error C2398: 項目 '1': 從 'tensorflow::int64' 到 'Eigen::DenseIndex' 的轉換必須是縮小轉換 [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\batch_kernels.cc(161): error C2398: 項目 '1': 從 'const tensorflow::int64' 到 'Eigen::DenseIndex' 的轉換必須是縮小轉換 [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\batch_kernels.cc(161): error C2398: 項目 '2': 從 'tensorflow::int64' 到 'Eigen::DenseIndex' 的轉換必須是縮小轉換 [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\conv_grad_ops_3d.cc(296): error C2398: 項目 '2': 從 'initializer list' 到 'Eigen::IndexPair<int>' 的轉換必須是縮小轉換 [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\conv_grad_ops_3d.cc(296): error C2398: 項目 '3': 從 'initializer list' 到 'Eigen::IndexPair<int>' 的轉換必須是縮小轉換 [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\conv_grad_ops_3d.cc(296): error C2398: 項目 '4': 從 'initializer list' 到 'Eigen::IndexPair<int>' 的轉換必須是縮小轉換 [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\conv_grad_ops_3d.cc(296): error C2398: 項目 '1': 從 'const tensorflow::int64' 到 'int' 的轉換必須是縮小轉換 [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\conv_grad_ops_3d.cc(296): error C2398: 項目 '2': 從 'const tensorflow::int64' 到 'int' 的轉換必須是縮小轉換 [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\conv_grad_ops_3d.cc(320): error C2398: 項目 '2': 從 'const tensorflow::int64' 到 'Eigen::DenseIndex' 的轉換必須是縮小轉換 [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(242): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\draw_bounding_box_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(242): error C2398: 項目 '4': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\draw_bounding_box_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(245): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\draw_bounding_box_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(245): error C2398: 項目 '4': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\draw_bounding_box_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(242): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\matrix_band_part_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(245): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\matrix_band_part_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorDimensions.h(289): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\matrix_band_part_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(242): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\matrix_set_diag_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(245): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\matrix_set_diag_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(242): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\matrix_diag_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(245): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\matrix_diag_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(242): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\resize_bilinear_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(242): error C2398: 項目 '4': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\resize_bilinear_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(245): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\resize_bilinear_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(245): error C2398: 項目 '4': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\resize_bilinear_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(242): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\resize_bicubic_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(242): error C2398: 項目 '4': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\resize_bicubic_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(245): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\resize_bicubic_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(245): error C2398: 項目 '4': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\resize_bicubic_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(242): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\resize_nearest_neighbor_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(245): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\resize_nearest_neighbor_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\tensor_array_ops.cc(1286): error C2398: 項目 '2': 從 'tensorflow::int64' 到 'int' 的轉換必須是縮小轉換 [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\tensor_array_ops.cc(1288): error C2398: 項目 '2': 從 'const __int64' 到 'int' 的轉換必須是縮小轉換 [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(242): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\unique_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
      c:\users\user\source\repos\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(245): error C2398: 項目 '3': 從 'tensorflow::int64' 到 'ptrdiff_t' 的轉換必須是縮小轉換 (正在編譯原始程式檔 C:\Users\User\Source\Repos\tensorflow\tensorflow\core\kernels\unique_op.cc) [C:\Users\User\Source\Repos\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]

**Comment by reedwm** [comment]
I'm assuming the issue is that TensorFlow does not compile on a 32-bit platform. Correct me if I'm wrong.

/CC @gunan, do we support 32-bit platforms?

**Comment by gunan** [comment]
No, we do not support 32 bit desktop operating systems.
