### ISSUE TITLE
Feature Request: Porting tensorflow to onion omega 2+

### ISSUE THREAD

**Issue by loser2509** [tensorflow/tensorflow#18258]
I have been working with onion omega 2+ an iot computer with following specifications :
Operating system-OpenWrt
System-on-chip used MediaTek MT7688
CPU-580 MHz 32-bit computing Single-core MIPS 24KEc
Memory-128 MB for Omega2 Plus
Storage-32 MB and a MicroSDHC slot
Graphics-No graphic
Power-0.6 Watts

I would like to run inception V3 model but I am unable to install tensorflow on omega 2+. Is it possible to run tensorflow or tensorflow lite on omega 2+????

**Comment by loser2509** [comment]
Update 1
No I have not written any custom code 
I am now using OnionOS on onion omega 2+
Tensorflow installed : Unable to install tensorflow
Tensorflow version : N/A
Bazel version : N/A
CUDA/cuDNN version : N/A
GPU model and memory : N/A
Exact command to reproduce : N/A

**Comment by aselle** [comment]
Since you haven't given any indictation of what problem you have and what you have tried. I am closing this issue for now. This is certainly  currently an unsupported platform, but we are willing to help you if you provide enough information to provide suggestions. Thanks!
