### ISSUE TITLE
Various matrix triangular functions. 

### ISSUE THREAD

**Issue by alexggmatthews** [tensorflow/tensorflow#1825]
A feature request.

At the moment as far as I'm aware TensorFlow doesn't have equivalents of the following numpy functionality:

1) np.tril: http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.tril.html and similarly
np.triu: http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.triu.html

2) np.tril_indeces http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.tril_indices.html and the upper triangular equivalent and the ability to assign to a tensor using them.

3) The ability to convert a vector to a lower or upper triangular square matrix which blas has. 

This sort of thing is useful for instance in linear algebra usages of TensorFlow. 

I am unaware of an easy work around for these but I would be happy to be wrong.

**Comment by rmlarsen** [comment]
Hi Alex,

I'm actually working on adding the equivalent of np.tril and np.triu, or rather an op that can copy a specified set of diagonals from a given matrix or batch of matrices. I expect it to be done sometime next week. 

The other pack/unpack of triangular to/from vector are probably lower priority. Feel free to submit a PR :-)

Rasmus

**Comment by rmlarsen** [comment]
Actually, regarding the packing/unpacking, you might want to look at the code in tensorflow/core/kernels/batch_matrix_diag_op.h which should get pushed to OSS shortly. It could be extended to extract multiple diagonals or you could at least use it as a template for a packing/unpacking op.

**Comment by alexggmatthews** [comment]
Hi Rasmus, Thanks for your reply. I think what you are working on sounds good and will have a look when it gets merged.

**Comment by eriophora** [comment]
Any progress on this? Looking to be able to extract the upper (or lower!) triags.

**Comment by alexggmatthews** [comment]
1) is done . have a look at batch_matrix_band_part

**Comment by rmlarsen** [comment]
Some of the functionality of 2) and 3) is covered by the SparseTensor class and the functions
tf.sparse_merge, and tf.sparse_to_dense. 

The op pair tf.diag / tf.diag_part  (and batch_ extensions) do perform the unpacking/packing similar to what you suggest in 3), but here the potential space savings are much larger. I suppose batch_matrix_band_part could have been written that way (with a companion unpacking op), but I thought the current form, which simply zeros out the remaining part of the matrix, more convenient and much faster than having to write a packing followed by an unpacking op to achieve the same.

As always, feel free to send a PR if you think it would be useful.

**Comment by eriophora** [comment]
@alexggmatthews Great, thanks so much alexggmatthews! `tf.batch_matrix_band_part` is not a part of the official 0.8 release correct? I see documentation [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/math_ops.md) but not [here in the official documentation](https://www.tensorflow.org/versions/r0.8/api_docs/python/math_ops.html). Nevertheless this looks like exactly what I need. Wonderful!

**Comment by alexggmatthews** [comment]
You're most welcome @eriophora but it was @rmlarsen who did the hard bit - I guess he will know more about the release plans too. You're correct that it hasn't been in a release yet.

**Comment by girving** [comment]
@rmlarsen What's left to do in this issue?

**Comment by rmlarsen** [comment]
tf.batch_matrix_band_part is in the 0.9 release, and as discussed above there are reasonable equivalents for the other use cases. Feel free to open specific issue for them if you disagree. I'll close this issue.

**Comment by markvdw** [comment]
@rmlarsen Is it correct that the issue of unpacking a vector to a triangular matrix (similar to BLAS (d|s|c)tpttf) is not addressed yet? I have some code that does this, which I'm happy to contribute.

**Comment by danmackinlay** [comment]
@markvdw I think it would be useful if such code were in tensorflow; various projects, especially ones that do Gaussian process inference, really need to work with vectors of triangular matrices, e.g. [GPflow](https://github.com/GPflow/GPflow/blob/master/gpflow/tf_wraps.py) and [AutoGP](https://github.com/ebonilla/AutoGP/blob/master/autogp/util/tf_ops/tri_to_vec.cc)

**Comment by jvdillon** [comment]
Sorry for just jumping in here. But the `tf.contrib.distributions.fill_triangular` utility function might be useful.  It reshapes a length-`d*(d+1)/2` vector into a lower (or upper) triangular matrix (with zeros on the flip-side).

(Note: Im just now making this function public in tf.contrib.distributions. This should be live by tomorrow.)
