### ISSUE TITLE
Empty tensorflow r1.7 api after virtualenv install of tensorflow r1.7 

### ISSUE THREAD

**Issue by mgyong** [tensorflow/tensorflow#18252]
Ubuntu 16.10 using below commands for tensorflow r1.7
########
virtualenv --system-site-packages -p python3 tensorflow
pip3 install tensorflow
########
pip3 install --upgrade tensorflow
Collecting tensorflow
  Using cached tensorflow-1.7.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting tensorboard<1.8.0,>=1.7.0 (from tensorflow)
  Using cached tensorboard-1.7.0-py3-none-any.whl
Requirement not upgraded as not directly required: six>=1.10.0 in /usr/local/lib/python3.6/site-packages (from tensorflow) (1.11.0)
Requirement not upgraded as not directly required: wheel>=0.26 in ./tensorflow/lib/python3.6/site-packages (from tensorflow) (0.31.0)
Collecting gast>=0.2.0 (from tensorflow)
Collecting grpcio>=1.8.6 (from tensorflow)
  Using cached grpcio-1.10.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting astor>=0.6.0 (from tensorflow)
  Using cached astor-0.6.2-py2.py3-none-any.whl
Requirement not upgraded as not directly required: absl-py>=0.1.6 in /usr/local/lib/python3.6/site-packages (from tensorflow) (0.1.10)
Requirement not upgraded as not directly required: numpy>=1.13.3 in /usr/local/lib/python3.6/site-packages (from tensorflow) (1.14.0)
Requirement not upgraded as not directly required: protobuf>=3.4.0 in /usr/local/lib/python3.6/site-packages (from tensorflow) (3.5.1)
Collecting termcolor>=1.1.0 (from tensorflow)
Requirement not upgraded as not directly required: html5lib==0.9999999 in /usr/local/lib/python3.6/site-packages (from tensorboard<1.8.0,>=1.7.0->tensorflow) (0.9999999)
Requirement not upgraded as not directly required: werkzeug>=0.11.10 in /usr/local/lib/python3.6/site-packages (from tensorboard<1.8.0,>=1.7.0->tensorflow) (0.14.1)
Requirement not upgraded as not directly required: bleach==1.5.0 in /usr/local/lib/python3.6/site-packages (from tensorboard<1.8.0,>=1.7.0->tensorflow) (1.5.0)
Requirement not upgraded as not directly required: markdown>=2.6.8 in /usr/local/lib/python3.6/site-packages (from tensorboard<1.8.0,>=1.7.0->tensorflow) (2.6.11)
Requirement not upgraded as not directly required: setuptools in ./tensorflow/lib/python3.6/site-packages (from protobuf>=3.4.0->tensorflow) (39.0.1)
tensorboard 1.7.0 requires bleach==1.5.0, which is not installed.
tensorboard 1.7.0 requires html5lib==0.9999999, which is not installed.
tensorboard 1.7.0 requires markdown>=2.6.8, which is not installed.
tensorboard 1.7.0 requires numpy>=1.12.0, which is not installed.
tensorboard 1.7.0 requires protobuf>=3.4.0, which is not installed.
tensorboard 1.7.0 requires six>=1.10.0, which is not installed.
tensorboard 1.7.0 requires werkzeug>=0.11.10, which is not installed.
grpcio 1.10.0 requires protobuf>=3.5.0.post1, which is not installed.
grpcio 1.10.0 requires six>=1.5.2, which is not installed.
tensorflow 1.7.0 requires absl-py>=0.1.6, which is not installed.
tensorflow 1.7.0 requires numpy>=1.13.3, which is not installed.
tensorflow 1.7.0 requires protobuf>=3.4.0, which is not installed.
tensorflow 1.7.0 requires six>=1.10.0, which is not installed.
Installing collected packages: tensorboard, gast, grpcio, astor, termcolor, tensorflow
Successfully installed astor-0.6.2 gast-0.2.0 grpcio-1.10.0 tensorboard-1.7.0 tensorflow-1.7.0 termcolor-1.1.0

##########
When i tried to verify tensorflow r1.7 installed properly, i got an empty api
Python 3.6.4 (default, Jan 28 2018, 16:44:18) 
[GCC 6.2.0 20161005] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'constant'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by kingeasternsun** [comment]
I encounter the same question
```
tensorflow 1.7.0 requires six>=1.10.0, which is not installed.
tensorboard 1.7.0 requires six>=1.10.0, which is not installed.
protobuf 3.5.2.post1 requires six>=1.9, which is not installed.
html5lib 0.9999999 requires six, which is not installed.
grpcio 1.10.1 requires six>=1.5.2, which is not installed.
bleach 1.5.0 requires six, which is not installed.
absl-py 0.1.13 requires six, which is not installed.
keras 2.1.5 requires pyyaml, which is not installed.
keras 2.1.5 requires six>=1.9.0, which is not installed.
```

**Comment by skye** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
