### ISSUE TITLE
why the kfac in tensorflow is not working suddenly?

### ISSUE THREAD

**Issue by Luanming** [tensorflow/tensorflow#18270]
Hi,

I wrote a simple code using tf.contrib.kfac for regression. It worked fine in the last two weeks. However, when I tried to run the code again the day before yesterday, there was an error: 

**AttributeError: module 'tensorflow.contrib' has no attribute 'kfac'**

![image](https://user-images.githubusercontent.com/38111150/38382416-c53529aa-38be-11e8-9220-d6f9102f61e8.png)

I just don't know why suddenly this goes wrong. Can anyone help me?

Thanks so much.

**Comment by yaroslavvb** [comment]
cc @duckworthd

**Comment by duckworthd** [comment]
Thank you, @yaroslavvb!

Hi @Luanming. I had some difficulty getting `kfac` knit into `tf.contrib` near the beginning, though hopefully all is well in the latest version of TensorFlow. Could you print out which version of TensorFlow you're using, so I could inspect the source code?

```python
$ python -c "import tensorflow; print tensorflow.__version__"
```

**Comment by Luanming** [comment]
Oh, that's where things went wrong. My version was 1.2.1. After updating, it is working now.
@duckworthd  Thank you  so much for your answer!
@yaroslavvb Thank you, too

**Comment by duckworthd** [comment]
That was easy :)

![image](https://user-images.githubusercontent.com/626236/38401640-c84cff9e-390b-11e8-9ee3-527463062598.png)
