### ISSUE TITLE
Document for `tf.TextLine.Dataset.shuffle` is confusing.

### ISSUE THREAD

**Issue by shiquanwang** [tensorflow/tensorflow#18283]
In the [doc](https://www.tensorflow.org/api_docs/python/tf/data/TextLineDataset#shuffle) for V1.7.

The signature is:
```
shuffle(
    buffer_size,
    seed=None,
    reshuffle_each_iteration=None
)
```

and in below description:
`reshuffle_each_iteration: (Optional.) A boolean, which if true indicates that the dataset should be pseudorandomly reshuffled each time it is iterated over. (Defaults to True.)`

I can't tell what is default value for `reshuffle_each_iteration` and so I can't tell the default behaviour.

**Comment by mrry** [comment]
From the docstring as quoted:

>  (Defaults to True.)

**Comment by shiquanwang** [comment]
The docstring is `True` but the signature shows `None`.
