### ISSUE TITLE
SparseTensor: common unary ops

### ISSUE THREAD

**Issue by concretevitamin** [tensorflow/tensorflow#1828]
Currently, we have a slew of common unary ops that work on Tensors, but not SparseTensors ([ref](https://www.tensorflow.org/versions/r0.7/api_docs/python/math_ops.html#basic-math-functions)):

```
tf.pow()
tf.exp()
tf.log()

# lower priority?
tf.abs()
tf.neg()
tf.sign()
tf.inv()
tf.square()
tf.round()
tf.sqrt()
tf.ceil()
tf.floor()
```
and so on.

We'd like these ops to work on SparseTensor. These do not change the indices nor shape of `SparseTensor`s, so all that's needed is transform the `.values` field on Python side in O(1) line.

**Comment by mrry** [comment]
Are `log()` and `inv()` well-defined for sparse tensors? Also, doesn't `exp()` make the whole tensor dense? (Or do other frameworks deal with the implicitly-zero elements differently in those cases?)

**Comment by concretevitamin** [comment]
As a first cut, I think having these ops transform only the non-empty entries makes sense and is simple to start with.  (This is what Theano calls "structured", as opposed to "regular" where the implicitly-zero elements are worked on as well.)  

So, `log(), inv(), exp()` should all work on the provided elements and thus will not make the tensor dense.
.

**Comment by siddharth-agrawal** [comment]
@concretevitamin @ebrevdo Added PR for `tf.log()`, let me know whether I'm on the right track.

**Comment by maniteja123** [comment]
Hi everyone, I am new to tensorflow but have been working on it recently and was hoping to contribute. This task might help me understand the basic functionalities like adding ops. Would it be fine if I try implementing these. I suppose @siddharth-agarwal has already worked on some of these. Please let me know whether I can work on this. Thanks.

**Comment by siddharth-agrawal** [comment]
@maniteja123 I would suggest looking at how to implement `tf.pow()` as it is a binary operator. I have already figured out how the unitary operator code and tests need to look like, so I will be putting them out one by one.

**Comment by ebrevdo** [comment]
pow(0, x) is undefined for x == 0, so that requires subtle work.

exp(0) == 1, so that densifies the SparseTensor (therefore it's not very useful)
log(0) = -inf, and i see you just pushed that; we will have to revert it because it densifies the sparse tensor.
inv(0) is not defined, and so is not implementable.

**Comment by ebrevdo** [comment]
@vrv have to assign you for now, to revert the log() change.  feel free to unassign yourself after.

**Comment by siddharth-agrawal** [comment]
@ebrevdo The implementations were based on @concretevitamin's comment [here](https://github.com/tensorflow/tensorflow/issues/1828#issuecomment-225325574), which was a reply to @mrry's comment just before that (which raised the same issues you raised). I think an option should be added later for the operators to make the result tensor dense, if and when applicable.

**Comment by ebrevdo** [comment]
No sparse matrix library I know of supports these operations, and SparseTensor was definitely not designed to support structured unary operations like this. It's meant to represent tensors with lots of zeros. Any functions that modify the sparsity structure of a dense version of the matrix have to be implemented similarly. One can always call tf.exp(st.values) themselves. Then it's very clear what's going on.

**Comment by ebrevdo** [comment]
Binary operations like tf.pow are even more tricky. See the various implementations of sparse_add.

**Comment by siddharth-agrawal** [comment]
Could you point me towards some library where I can see what the expected outputs of each of these operations should be? Also, could you mention which of these operations should be implemented? (since you mentioned exp won't be useful and inv is not implementable)

**Comment by ebrevdo** [comment]
There are no sparse libraries that implement log or exp or inv.  Unary operations that preserve the sparsity pattern are reasonable and easy to implement... Think sign, neg, square, round, floor.

**Comment by ebrevdo** [comment]
Basically, any injective function for which f(0)=0 is OK.  floor and ceil require care because they move values near 0 to 0, so those are probably also not great candidates here.

**Comment by concretevitamin** [comment]
After more thoughts, I agree with @ebrevdo about leaving out the tricky ones for now.  Biggest reason being the purposed semantics is indeed weird, and if users do want to do something like that, it'd be easy for them to make a new SparseTensor with transformed values.  

Apologies for my earlier comment in this thread.  This issue probably still should exist for other unary ops that are well-behaved.

**Comment by maniteja123** [comment]
Hi, sorry for the noise but in scipy sparse matrices, functions like log(1+X) [log1p](http://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.sparse.csr_matrix.log1p.html) and exp(X)-1 [expm1](http://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.sparse.csr_matrix.expm1.html) are implemented which satisfy f(0)=0. Though I am not sure if these operations are too specific to be implemented here. Cheers.

**Comment by siddharth-agrawal** [comment]
@concretevitamin @ebrevdo Making a list of all the ops that cannot be made to work for `SparseTensor`s, let me know if there are any mistakes.
`
tf.inv()
tf.rsqrt()
tf.exp()
tf.log()
tf.sigmoid()
tf.sin()
tf.cos()
tf.lgamma()
tf.erfc()
tf.tan()
tf.asin()
tf.acos()
tf.atan()
`

**Comment by siddharth-agrawal** [comment]
Assuming the above list is correct, only `tf.erf()` remains to be done.

**Comment by concretevitamin** [comment]
@siddharth-agrawal I noticed that many of the ops are now in the same following form:

```python
 +  with ops.op_scope([x], name, "Erf") as name:
 +    if isinstance(x, ops.SparseTensor):
 +      x_erf = gen_math_ops.erf(x.values, name=name)
 +      return ops.SparseTensor(indices=x.indices, values=x_erf, shape=x.shape)
 +    else:
 +      return gen_math_ops.erf(x, name=name)
```

Is it possible that we use some registration wrapper / decorator to factor out this form?

**Comment by siddharth-agrawal** [comment]
@concretevitamin Yes, this should be possible. But there are exceptions, for example `tf.abs()`. I'm not very familiar with registration wrappers / decorators. Could you provide some example in the TF code where they are used?

**Comment by concretevitamin** [comment]
Not directly applicable, but search for `ops.Tensor._override_operator` in `math_ops.py`.

Now that I think about it more - what we wanted was more like a macro, not registration.  I don't see a good solution immediately, so fine to drop it for now.

**Comment by siddharth-agrawal** [comment]
@concretevitamin If we are dropping this, then this issue has been resolved. Unless, of course, there is some problem with the list I provided above.

**Comment by concretevitamin** [comment]
@siddharth-agrawal I am closing this issue.  Thanks again for your awesome series of work on this!

**Comment by siddharth-agrawal** [comment]
@concretevitamin Thanks! If there are any other `SparseTensor` ops I can help with, do let me know.
