### ISSUE TITLE
Issue using/importing unsorted_segment_mean

### ISSUE THREAD

**Issue by roya0045** [tensorflow/tensorflow#18294]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Win 10
- **TensorFlow installed from (source or binary)**: pip install ( and reinstalled after the first errors)
- **TensorFlow version (use command below)**: 1.7
- **Python version**: 3.5.4
- **Bazel version (if compiling from source)**:N/A
- **GCC/Compiler version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:N/A
- **GPU model and memory**:N/A
- **Exact command to reproduce**: test = tensorflow.unsorted_segment_mean

### Describe the problem

I cannot import the or use the function unsorted_segment_mean despite it being present in python/ops/math_ops and exported with tf_export, but I am able to use unsorted_segment_sum.
My IDE shows me the function but when trying to call it I get AttributeError.
I have tried to import it directly using
import tensorflow.unsorted_segment_mean
And this failed too.
I have tried to import permutations of the path (ops, math_ops, ops.math_ops, etc) to try to access is directly and I got error that tensorflow did not have those modules (despite my IDE stating the opposite). And I could not access it that way either.

### Source code / logs
Code
```python
import tensorflow as tf
try:
    test=tf.unsorted_segment_mean
except:
    from tensorflow import unsorted_segment_mean
    test=unsorted_segment_mean()
```
Error:
`
Traceback (most recent call last):
  File "[redacted]", line 25, in <module>
    test=tf.unsorted_segment_mean
AttributeError: module 'tensorflow' has no attribute 'unsorted_segment_mean'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[redacted]", line 27, in <module>
    from tensorflow import unsorted_segment_mean
ImportError: cannot import name 'unsorted_segment_mean'
`

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by Jax29** [comment]
File "/home/lixuchang/anaconda3/envs/pcdet/lib/python3.6/site-packages/waymo_open_dataset/utils/frame_utils.py", line 25, in <module>
    from waymo_open_dataset.utils import range_image_utils
  File "/home/lixuchang/anaconda3/envs/pcdet/lib/python3.6/site-packages/waymo_open_dataset/utils/range_image_utils.py", line 59, in <module>
    pool_method=tf.unsorted_segment_max):
AttributeError: module 'tensorflow' has no attribute 'unsorted_segment_max'
