### ISSUE TITLE
does tensorboard allow for building/editing models?

### ISSUE THREAD

**Issue by nbenhaim** [tensorflow/tensorflow#183]
I was under the impression that tensorboard was an interactive UI that allows you to build/edit models.  Is this not the case?

**Comment by danmane** [comment]
Nope - at the moment TensorBoard only allows you to visualize and inspect existing models that were created with the Python API. Enabling the TensorBoard graph inspector to modify models would be extremely cool, and we've discussed the idea a bit, but it would also be extremely complicated to get it right, so we're not likely to prioritize it any time soon.
