### ISSUE TITLE
WinML or DirectML support planned?

### ISSUE THREAD

**Issue by oscarbg** [tensorflow/tensorflow#18307]
Windows only, but this should support AMD and Intel GPUs using D3D12 backend or even DirectML which with custom metacommands seems even able to use tensor cores on Volta GPUs..
Hope to hear news at least by Build conference in May

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by oscarbg** [comment]
It’s a request such details aren’t needed..

**Comment by skye** [comment]
I do not believe there are any plans to support thisWinML or DirectlyML at this time.

**Comment by deepseek** [comment]
@skye What about this time?

**Comment by skye** [comment]
Hi, I don't work on TF anymore, so I still don't know of any plans! Maybe someone else can comment... @mhong ?

**Comment by martinwicke** [comment]
We currently have no plans to integrate WinML or DirectML. We are hoping that support for AMD and Intel can be added natively and cross-platform.

**Comment by deepseek** [comment]
@pfultz2

**Comment by oscarbg** [comment]
Hi @martinwicke,
curious with Intel Win support will be with OneAPI Level Zero API?
also for AMD are you expecting Windows support for MIOpen and/or ROCM coming soon from AMD?
thanks..

**Comment by martinwicke** [comment]
@penpornk knows best. We're working with both Intel and AMD, but I don't know strict timelines.

**Comment by penpornk** [comment]
@oscarbg I believe it will be through oneDNN. 
@TensorFlow-MKL and @agramesh1: Please correct me if I'm wrong.

**Comment by penpornk** [comment]
@chsigg Do you know about AMD Windows support?

**Comment by chsigg** [comment]
I do not know whether AMD is planning to support Windows. As far as I know MIOpen is not supported on Windows. You might want to ask them directly at https://github.com/ROCmSoftwarePlatform/tensorflow-upstream.
