### ISSUE TITLE
tf.enable_eager_execution must be called at program startup.

### ISSUE THREAD

**Issue by LandSurveyorK** [tensorflow/tensorflow#18304]
```
from __future__ import absolute_import, division, print_function
import os
import matplotlib.pyplot as plt

import tensorflow as tf
print(tf.VERSION)   #  => 1.7.0
import tensorflow.contrib.eager as tfe

tf.enable_eager_execution()
```

```
ValueError                                Traceback (most recent call last)
<ipython-input-59-0c62cac7517d> in <module>()
      7 import tensorflow.contrib.eager as tfe
      8 
----> 9 tf.enable_eager_execution()

D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py in enable_eager_execution(config, device_policy)
   5242     if graph_mode_has_been_used:
   5243       raise ValueError(
-> 5244           "tf.enable_eager_execution must be called at program startup.")
   5245   context._default_mode = context.EAGER_MODE
   5246   if context._context is None:

ValueError: tf.enable_eager_execution must be called at program startup.
```

**Comment by asimshankar** [comment]
`tf.enable_eager_execution()` is intended to be called once in a program, typically the first thing in a program. Libraries should not be calling `tf.enable_eager_execution()` and instead should in general work for both graph construction and eager execution (or `assert tf.executing_eagerly()` if they work only with eager execution).

That said, I can't reproduce the error you're seeing using the snippet provided. Is there more to reproducing the problem? Thanks.

**Comment by LandSurveyorK** [comment]
Thank you for your quick response. 

I tried the same codes in Windows terminal, it works. 
But it doesn't work in Jupyter (Version 5.4.1, latest version).

**Comment by asimshankar** [comment]
Sounds like the Jupyter kernel needs to be restarted.

**Comment by LandSurveyorK** [comment]
Cool, it works, thank you for  your time.

**Comment by vincent-pli** [comment]
Thanks a lot, also fix my issue

**Comment by cy576013581** [comment]
Cool, solved my problem.

**Comment by mymusise** [comment]
Met this problem again when I run the example of **Neural Machine Translation with Attention** in [colab](https://github.com/tensorflow/tensorflow/blob/r1.10/tensorflow/contrib/eager/python/examples/notebooks/eager_basics.ipynb).  What should I do to make this notebook work.

**Comment by asimshankar** [comment]
For now, you can restart the colab runtime ("Runtime -> Restart Runtime...").
In future releases, I think the error will go away (thanks to e2c6ec9e86dd86e0dd56e0f11302a5bf5d9ed440)

**Comment by mymusise** [comment]
@asimshankar  Thanks guy,  but restarting the runtime does not work for me, even I change the notebook environment to python2 without GPU.

**Comment by t-ubukata** [comment]
I have the same issue with the notebook below.
Restart runtime, Reset all runtimes neither do not solve, but I could run it once before.

https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/python/examples/pix2pix/pix2pix_eager.ipynb

**Comment by stefan-falk** [comment]
Same issue here:

```python
import os
import logging.config
import tensorflow as tf
from tensor2tensor import problems
from tensor2tensor.data_generators.translate_ende import TranslateEndeWmtBpe32k

from asr.util import is_debug_mode

if __name__ == '__main__':

    logging.config.fileConfig('../logging.conf')
    logger = logging.getLogger(__name__)
    logger.setLevel(level=logging.DEBUG)

    tfe = tf.contrib.eager

    if is_debug_mode():
        logger.info('Debug mode. Enabling tensorflow eager excetion.')
        if not tf.executing_eagerly():
            # Enable tensorflow Eager execution
            tfe.enable_eager_execution()
```

Throws

```
19-09-2018:10:37:35,546 INFO     [example_transformer_ende.py:41] Debug mode. Enabling tensorflow eager excetion.
Traceback (most recent call last):
  File "/home/everest11/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/everest11/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/everest11/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/everest11/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/everest11/tmp/pycharm_project_254/asr/example_transformer_ende.py", line 44, in <module>
    tfe.enable_eager_execution()
  File "/home/everest11/miniconda3/envs/t2t-asr/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5187, in enable_eager_execution
    config, device_policy, execution_mode, None)
  File "/home/everest11/miniconda3/envs/t2t-asr/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5255, in enable_eager_execution_internal
    "tf.enable_eager_execution must be called at program startup.")
ValueError: tf.enable_eager_execution must be called at program startup.
```

**Comment by yiboyang** [comment]
I had the same problem. My code looks something like
```
import utils
import tensorflow as tf
tf.enable_eager_execution()
```
Turns out `utils` already imports tensorflow. The exception goes away if I run `tf.enable_eager_execution` immediately after tensorflow is imported **for the very first time** (i.e., in `utils`).

**Comment by naf140230** [comment]
I have a similar problem with this code:
`import tensorflow as tf
tf.enable_eager_execution()`

This is right at the top of the code. However, even `tf.enable_eager_execution()` is right after `import tensorflow as tf` and these are the first two lines of code, I still get the error.

**Comment by sandipto-sanyal** [comment]
Restart Kernel and clear output and run the code block again from start. Issue will be resolved

**Comment by CA4GitHub** [comment]
As a tip, at least in tensorflow version 1.13.1, you can't even check if eager execution is enabled before you try to enable eager execution.

That is the following will not work:

    import tensorflow as tf
    tf.executing_eagerly()
    tf.enable_eager_execution()

However, with a new python kernel, the following works:
        
    import tensorflow as tf
    tf.enable_eager_execution()
    tf.executing_eagerly()
