### ISSUE TITLE
Feature Request: Allow extending Estimator

### ISSUE THREAD

**Issue by jperl** [tensorflow/tensorflow#18314]
Our model is time based and we are doing continuous training and eval on the same machine. The model is very large and takes 1+ minutes to load, so we don't want the overhead of reloading the graph and weights every time we switch from training to eval https://github.com/tensorflow/tensorflow/issues/13895#issuecomment-375990484.

I tried to subclass Estimator to override the `_train_model fn` but it is not allowed due to this [white-list](https://github.com/tensorflow/tensorflow/blob/e7f158858479400f17a1b6351e9827e3aa83e7ff/tensorflow/python/estimator/estimator.py#L524-L528). Can you remove this restriction and let people override methods at their own peril?

`Subclasses of Estimator cannot override members of Estimator. <class ... does override ['_train_model']` (relates to https://github.com/tensorflow/tensorflow/issues/12908).

**Comment by jperl** [comment]
Hacked around this with a noop `Estimator._assert_members_are_not_overridden = lambda _: None`

**Comment by djovanoski** [comment]
Hey @jperl , im trying to skip creating the model_fn ( creating the graph) each time, can you please advice me how can i skip that using above snippet where i need to modify my model ?

Thanks

**Comment by jperl** [comment]
@djovanoski I decided to not use or overload estimators by rather build my own "Estimator" like class that wraps `MonitoredSession`.
