### ISSUE TITLE
saving model under different directory if specified one is already taken

### ISSUE THREAD

**Issue by xxiane** [tensorflow/tensorflow#18328]
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/builder_impl.py](url)
Line 87

If the specified directory name is already taken, is there a reason why the model saving has to fail instead of saving to some alternate directory? I was wondering if we could add a while loop that says that while the directory name is taken, we'll try again and save it in `export_dir + "_" + incr`?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by xxiane** [comment]
Have I written custom code: no, but i can, unless there's a reason why the model should fail to save
OS Platform and Distribution: ubuntu 17.10
TensorFlow installed from / TensorFlow version: cloned from this repo
Bazel version: idk what this is
CUDA/cuDNN version: n/a?
GPU model and memory: n/a
Exact command to reproduce: n/a

**Comment by asimshankar** [comment]
The reason is primarily that the directory was specified by the caller, so we should respect that :)

I don't think we want to change behavior since it breaking it would be backward incompatible.

Thanks for the suggestion though.
