### ISSUE TITLE
Tensorflow 1.7.0 - Illegal instruction

### ISSUE THREAD

**Issue by Gnefi** [tensorflow/tensorflow#18322]
Hy everyone!

I have Illegal instruction with tensorflow (v. 1.7) when I just type the import command:

Python 2.7.14 |Anaconda, Inc.| (default, Mar 27 2018, 17:29:31) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Illegal instruction ( core dumped creato )

Surface the internet for the solution, I found that I can downgrade at 1.5 but I cannot downgrade at 1.5 because I need new attribute that are located in 1.6 and 1.7. (the attribute is tf.contrib.data.shuffle_and_repeat).

How can I fix the problem?

This is my CPU: AMD A4-3300M APU with Radeon(tm) HD Graphics
It's to old to run tensorflow? Is tensorflow works with new CPU and GPU? My PC is 6-7 years old.

**Comment by xysmlx** [comment]
This CPU does not support the AVX instructions. The prebuilt binaries require it. Please install from source.

**Comment by asimshankar** [comment]
Yup, as @xysmlx said : TensorFlow release binaries are now compiled with AVX support. If your CPU does not support that, you'll have to build from source for now. (see ["Release Notes"](https://github.com/tensorflow/tensorflow/releases/tag/v1.6.0) for 1.6)
