### ISSUE TITLE
iOS Demo can't run

### ISSUE THREAD

**Issue by moluwentu** [tensorflow/tensorflow#18343]
iOS Demo run crash in interpreter.h line 221 if (tensor_ptr->type == typeToTfLiteType<T>()) ,How can I solve this problem?

Have I written custom code : NO
OS Platform and Distribution: High Sierra 10.13.4,  iOS 11.3 on iPhoneX,iOS11.0.3 on iPhone6
TensorFlow installed from : https://github.com/tensorflow/tensorflow
TensorFlow version : 1.7.0
Exact command to reproduce  : Followed instructions at https://www.tensorflow.org/mobile/tflite/demo_ios

**Comment by glenn-jocher** [comment]
Same issue. Followed all directions on https://www.tensorflow.org/mobile/tflite/demo_ios, build succeeds in Xcode but error at runtime as shown below. iPhone screen remains black, or with camera (no classifications) and unresponsive 'Freeze Frame' below camera.

- Xcode 9.3
- MacOS High Sierra 10.13.4
- iPhone 6s with iOS 11.3

<img width="1418" alt="screen shot 2018-04-09 at 3 35 51 pm" src="https://user-images.githubusercontent.com/26833433/38515947-2c6d6218-3c0c-11e8-9107-da45cca249af.png">

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by glenn-jocher** [comment]
Have I written custom code - No
OS Platform and Distribution - MacOS High Sierra 10.13.4, iOS 11.3 on iPhone
TensorFlow installed from - git clone https://github.com/tensorflow/tensorflow
TensorFlow version - 1.7.0
Bazel version - NA
CUDA/cuDNN version - NA
GPU model and memory - NA
Exact command to reproduce - Followed instructions at  https://www.tensorflow.org/mobile/tflite/demo_ios

**Comment by VictorQi** [comment]
Same issue.

Have I written custom code - No
OS Platform and Distribution - MacOS High Sierra 10.13.0, iOS 11.0.1 on iPhone 6s
TensorFlow installed from - git clone https://github.com/tensorflow/tensorflow
TensorFlow version - 1.7.0
Bazel version - NA
CUDA/cuDNN version - NA
GPU model and memory - NA
Exact command to reproduce - Followed instructions at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/mobile/tflite/demo_ios.md

**Comment by andaas4** [comment]
Same issue here. 
Have I written custom code - No
OS Platform and Distribution - MacOS High Sierra 10.13.4, iOS 11.3.0 on iPhone X
TensorFlow installed from - git clone https://github.com/tensorflow/tensorflow
TensorFlow version - 1.7.0
Bazel version - NA
CUDA/cuDNN version - NA
GPU model and memory - NA
Exact command to reproduce - Followed instructions at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/mobile/tflite/demo_ios.md

**Comment by miaout17** [comment]
The fix was already merged

**Comment by japer21** [comment]
Same issue, but it does not load my own model:

```
nnapi error: unable to open library libneuralnetworks.so
Model provided has model identifier 'Plac', should be 'TFL3'

2018-07-02 12:03:14.951547+0200 Proba[8638:68521] Failed to mmap model model_tflite_graph.
```
When I run your demo tflite simple, it does work perfectly.
