### ISSUE TITLE
Tensorflow import error for tf.contrib.data.python.ops.threadpool(used for benchmark script)

### ISSUE THREAD

**Issue by nushrathumaira** [tensorflow/tensorflow#18359]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, I am trying to run tf_cnn_benchmarks provided by tensorflow
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Redhat linux 7.4
- **TensorFlow version (use command below)**: v1.5.0-0-g37aa430d84 1.5.0
- **GCC/Compiler version (if compiling from source)**:c++ (GCC) 5.3.0
- **CUDA/cuDNN version**:cuda-toolkit/9.0.176 nccl/2.1.2-1 anaconda cuDNN/9.0v7
- **GPU model and memory**: Tesla k40, memory 55gb
- **Exact command to reproduce**:  python tf_cnn_benchmarks.py 

### Describe the problem
I am trying to run the benchmark provided in this link([https://github.com/tensorflow/benchmarks/blob/master/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py])
It says it can not import threadpool. Threadpool is inside tf.contrib.data API which may be deprecated. 

### Source code / logs
I am including the trace below:

```
>>> import tensorflow
>>> from tensorflow.contrib.data.python.ops import threadpool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name threadpool
```

**Comment by mrry** [comment]
The `tensorflow.contrib.data.python.ops.threadpool` module was added after TensorFlow 1.5 (in ee40d87af8e6c24e6e84ff64e4932c38d6ccfcf7), so you'll need to upgrade to TensorFlow 1.7 or later to use that particular version of the benchmarking script.
