### ISSUE TITLE
pdf version of the TF document

### ISSUE THREAD

**Issue by baoblackcoal** [tensorflow/tensorflow#1835]
Recently we often can't access https://www.tensorflow.org, could you provide a pdf version of the TF document, It will be very convenient for us

.

**Comment by liyi193328** [comment]
Or What is the way to lanuch doc

**Comment by martinwicke** [comment]
Almost all of the content on tensorflow.org is also on github. Can you see it here? Also, if you check our the source, it is in the g3doc folder locally.

**Comment by baoblackcoal** [comment]
g3doc folder is enough for me, thanks @martinwicke

**Comment by miku** [comment]
Quick-and-dirty solution. Convert all Markdown files to PDF, then join. Order maybe broken, but you get a single PDF (2856 pages, some documents missing, without images).

```
$ cd tensorflow/g3doc
$ for i in $(find . -name "*md"); do pandoc -s -o $i.zzzz.pdf $i; done
$ pdfjoin -o tfdocs.pdf $(find . -name "*zzzz.pdf" -printf "%p ")
```

**Comment by MGarvinNYC** [comment]
@miku:  If you're still listening, your command line works for some files (thanks). But other files give an error message: "! You can't use `macro parameter character #' in math mode"
Any idea what's up?

**Comment by O-KAYgorodov** [comment]
I have a python script to do this https://github.com/O-KAYgorodov/TF2pdf

**Comment by byronyi** [comment]
For those of you who is in mainland China and has frequently met connection problems accessing [](tensorflow.com), you could try [](tensorflow.google.cn).
