### ISSUE TITLE
LookupError: No gradient defined for operation DepthwiseConv2dNativeBackpropFilter

### ISSUE THREAD

**Issue by tsoernes** [tensorflow/tensorflow#18354]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Fedora 27
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: b'v1.3.0-rc1-3011-gd86448938' 1.3.0
- **Python version**: Python 3.6.4 
-Bazel version: N/A
-CUDA/cuDNN version: N/A
-GPU model and memory: N/A
- **Exact command to reproduce**:

```
import tensorflow as tf

inp = tf.ones((1, 2, 2, 5))
shape = (3, 3, 5, 1)
filters = tf.Variable(tf.zeros_initializer()(shape))
conv = tf.nn.depthwise_conv2d(inp, filters, strides=[1, 1, 1, 1], padding="SAME")
value_layer = tf.layers.Dense(
    units=1, kernel_initializer=tf.zeros_initializer(), use_bias=False, activation=None)
val = value_layer.apply(conv)

trainer = tf.train.GradientDescentOptimizer(1e-4)
v_grads, _ = zip(*trainer.compute_gradients(val))
v_gradsf = tf.concat([tf.reshape(e, [-1, 1]) for e in v_grads], axis=0)
vweights = tf.random_uniform((50, 1))
dot = tf.matmul(tf.transpose(v_gradsf), vweights)
v_hess, _ = zip(*trainer.compute_gradients(dot))

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run((v_grads, dot, v_hess)))
```
```
LookupError: No gradient defined for operation 'gradients/depthwise_grad/DepthwiseConv2dNativeBackpropFilter' (op type: DepthwiseConv2dNativeBackpropFilter)
```
I'm not sure if this is a bug or feature request.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory

**Comment by reedwm** [comment]
This is a feature request to implement second order gradients `tf.nn.depthwise_conv2d`.

/CC @zhangyaobit, do you know if there are any plans for this or how difficult this would be?

**Comment by namhoonlee** [comment]
@reedwm I am also looking forward to this feature - second order gradients `tf.nn.depthwise_conv2d`. Any updates on this?

**Comment by reedwm** [comment]
Unfortunately, no one is currently available to work on this, so marking as contributions welcome to implement second order gradients to `tf.nn.depthwise_conv2d`.

**Comment by gmichel-netatmo** [comment]
@reedwm I am also looking forward for this feature. It would be nice for this op to support float16 precision.

**Comment by jony0917** [comment]
i am working on it.

**Comment by jony0917** [comment]
i have created a pl https://github.com/tensorflow/tensorflow/pull/20782

**Comment by veqtor** [comment]
Although a fix for this was merged in https://github.com/tensorflow/tensorflow/commit/6d96cc4d05fd09e5663853a795bcd9a5b01f1732

It seems as if this issue has returned at some point since I'm getting it with the exact same repro-steps as in this ticket.
See this colab for quick proof:
https://colab.research.google.com/drive/1s-0Co367Os762TzId5L2_kT1miLWaiMd

**Comment by reedwm** [comment]
See [this comment](https://github.com/tensorflow/tensorflow/pull/20782#issuecomment-479999811). This will be in the next stable release.

**Comment by reedwm** [comment]
Closing this issue since this is fixed in the master branch.
