### ISSUE TITLE
Android: Not a valid TensorFlow Graph serialization: Invalid GraphDef

### ISSUE THREAD

**Issue by dkhmelenko** [tensorflow/tensorflow#18361]
I have an issue with loading custom model into Android app. 
I'm using `LinearClassifier` and the function `export_savedmodel()` for saving the model.
It looks like this
```
model_path = model.export_savedmodel(export_dir_base="model", serving_input_receiver_fn=serving_input_fn)
```

Then from the path, I'm getting the file `saved_model.pb` and put it into the `assets` folder of the Android app. Then I try to load the model
```
val inferenceInterface = TensorFlowInferenceInterface(assets, "saved_model.pb")
```
However, at runtime IOException is thrown:
```
Failed to load model from 'saved_model.pb'
...
Android: Not a valid TensorFlow Graph serialization: Invalid GraphDef
```

Does anybody know what can be the issue? Seems like either the model is exported wrong or the issue with the implementation of `TensorFlowInferenceInterface`. Did somebody have experience loading models in Android app?

Model export is located [here](https://github.com/dkhmelenko/fitness-ml/blob/master/simple/Fitness%20Classification.ipynb)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dkhmelenko** [comment]
Sure, sorry for incomplete data. Here they are:
OS Platform and Distribution: Windows 10
TensorFlow installed from Anaconda
TensorFlow version: 1.4.0
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: Described in the first comment

**Comment by asimshankar** [comment]
The TensorFlow Mobile API only supports "frozen graphs" (where all model parameters are "frozen" as constants in the graph) and not the [SavedModel](https://www.tensorflow.org/programmers_guide/saved_model#build_and_load_a_savedmodel) format at this time.

See https://www.tensorflow.org/mobile/prepare_models for details on creating frozen models suitable for TensorFlow mobile. I believe changes are in progress to make it easier to created frozen models as well as models in a format usable by [TFLite](https://www.tensorflow.org/mobile/) directly from the SavedModel format.

Hope that helps.

**Comment by dkhmelenko** [comment]
@asimshankar Thank you for your help! 

I'm trying to freeze my model and I'm getting the error 
```
TypeError: names_to_saveables must be a dict mapping string names to Tensors/Variables. Not a variable: Tensor("linear/linear_model/bias_weights:0", shape=(18,), dtype=float32)
```

I looked on  [StackOverflow](https://stackoverflow.com/search?q=names_to_saveables+must+be+a+dict+) and seems this issue happens to many people and there is no answer to that.

Do you know what can be the reason? 

The code for creating the model is very simple
```python
gender = tf.feature_column.categorical_column_with_vocabulary_list("gender", ["f", "m"])
goal = tf.feature_column.categorical_column_with_vocabulary_list("goal", ["fit", "lose", "muscle"])
level = tf.feature_column.categorical_column_with_vocabulary_list("level", ["begin", "middle", "advance"])

feature_columns = [gender,goal,level]
input_fn = tf.estimator.inputs.pandas_input_fn(x=x_train, y=y_train, batch_size=100, num_epochs=None, shuffle=True)
model = tf.estimator.LinearClassifier(feature_columns=feature_columns, n_classes=18, model_dir="export")

model.train(input_fn=input_fn, steps=100)
```
