### ISSUE TITLE
CI nightly libtensorflow stuck

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/tensorflow#18373]
@asimshankar @alextp the nightly libtensorflow build on the CI server seems to have been stuck for a few days now due to the Mac build. Is there a way to resolve this in order to have the binaries built for the recent changes to the eager C API? I'm currently cross-compiling on my machine but that is very expensive and so this would really help! Thanks a lot! :)

[http://ci.tensorflow.org/job/nightly-libtensorflow/](http://ci.tensorflow.org/job/nightly-libtensorflow/)

**Comment by asimshankar** [comment]
I restarted that job, but I believe the nightly jobs are in the process of being migrated away from this Jenkins instance? I could be wrong (there seem to be no online Mac slaves).

@av8ramit @case540 would know better.

**Comment by av8ramit** [comment]
Thanks for filing @eaplatanios. I'm working right now to take care of this.

**Comment by eaplatanios** [comment]
@av8ramit Thanks! It seems it'll all good now! :)

@asimshankar Thanks for helping with this! If indeed you migrate those jobs away, do you plan to provide a way to obtain nightly builds for the dynamic libraries (i.e., `libtensorflow.so` and `libtensorflow_framework.so`)?

**Comment by av8ramit** [comment]
@eaplatanios yes we will definitely provide a way for access to those in a cleaner way as well.

**Comment by eaplatanios** [comment]
That's great! Thanks @av8ramit! :)

**Comment by av8ramit** [comment]
https://github.com/tensorflow/tensorflow#continuous-build-status
