### ISSUE TITLE
compile tf-lite error

### ISSUE THREAD

**Issue by MaeThird** [tensorflow/tensorflow#18371]
I want to **cross compile** some components of **tf-lite**.So I do these:
```
bazel build tensorflow/contrib/lite/arm_build:test_only \
      --crosstool_top=@local_config_arm_compiler//:toolchain \
      --cpu=armeabi\
      --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
      --verbose_failures
```
in my **arm_build** folder the **BUILD** file is:
```
package(default_visibility = ["//visibility:public"])
load("//tensorflow/contrib/lite:build_def.bzl", "tflite_copts")
licenses(["notice"])  # Apache 2.0
cc_binary(
    name = "test_only",
    srcs = [
        "test.cc",
    ],
    copts = [ "-O3",],
    linkopts = [
    ],
    deps = [
        "//tensorflow/contrib/lite:context",
        "//tensorflow/contrib/lite:framework",
        "//tensorflow/contrib/lite:schema_fbs_version",
    ],
    linkstatic=1,
)
```
the **test.cc** is:
```
#include <stdio.h>
int main(){
  printf("---");
  return 0;
}
```
Actually I just want to compile the "context,framework and schema_fbs_version" components.
I got like this "**error: '_Float128' does not name a type**"
![a](https://user-images.githubusercontent.com/14851411/38535744-98ca9ada-3c74-11e8-8ad3-e4e3ef9d7c40.png)
If compiled with native gcc ,it is okay.
**gcc version 7.3.1 20180312 (GCC)**
cross-toolchain **4.9.3 raspberry pi** which was downloaded by the **Bazel(version 0.11.1**)automatically.
OS:  4.15.15-1-ARCH
Can anyone help?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by MaeThird** [comment]
I managed to bypass this issue by replaced a higher toolchain version than 4.9.3 . Thanks.
