### ISSUE TITLE
tf.decode_csv New Feature Request option to remove leading/trailing whitespace on text fields

### ISSUE THREAD

**Issue by jrbrearley** [tensorflow/tensorflow#18384]
tf.decode_csv currently allows leading and trailing spaces with int or float fields and quietly strips the whitespace off, see: https://www.tensorflow.org/api_docs/python/tf/decode_csv
 
It would be really nice if the text fields could also have the leading/trailing whitespace stripped off. The embedded whitespace in a text field or sentence does need to be left intact, although it might be useful to compress it down to a single space between words. 
 
Pandas.read_csv has an option skipinitialspace to strip leading/trailing whitespace, which defaults to False. I would suggest a similar option for tf.decode_csv for text fields. If you wanted to aggressively deploy the option, you could default it to True.

Currently I remove whitespaces via a call to tf.py_func and a small rexexp function. There is also tf_regex_replace which works.
 
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Win 7
- **TensorFlow installed from (source or binary)**: pip install tensorflow-gpu
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 3.6.4
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0 / cudnn64_7
- **GPU model and memory**: Nvidia GeForce GTX660, 2GB RAM
- **Exact command to reproduce**: N/A

**Comment by yongtang** [comment]
Instead of an option in decode_csv, maybe we could add an 'string_strip' op so that it could be used in some other places as well?

**Comment by jrbrearley** [comment]
Sounds good. Another place that this would apply is: tf.data.TextLineDataset

**Comment by michaelisard** [comment]
@mrry would you reassign to someone as appropriate?

**Comment by mrry** [comment]
Reassigning to "contributions welcome" (for the `tf.string_strip()` op).

**Comment by yongtang** [comment]
Added a PR #18418 for `tf.string_strip`
