### ISSUE TITLE
where can I find people to help with tensorflow for windows? 

### ISSUE THREAD

**Issue by hydrogenpi** [tensorflow/tensorflow#18382]
I'm on server 2016, Windows 10 LTSB

I cannot get tensorflow to work with a tf/python open source project I have interested in.

Is there somewhere I can find help like someone good at tensorflow on Windows to remote in or use teamviewer to walk me through step by step to show me how to do a net2net and start a training (supervised training, not reinforced training) just in order to show me how to get the process started? 

I would like to convert using Net2Net an existing 15 block 192 filter to 40 block 256 filters and then start trainging it for many steps using raw training data that is also open source/public domain for it to get strong.

I'm willing to compensate them for said time and effort

**Comment by Carmezim** [comment]
Hi @hydrogenpi, for instructions on how to install TF on Windows please follow the [installation docs](https://www.tensorflow.org/install/install_windows), you will find all the information necessary to successfully install it.

**Comment by av8ramit** [comment]
@hydrogenpi, @Carmezim said it best. You can also refer to our [tested source configurations](https://www.tensorflow.org/install/install_sources#tested_source_configurations) table if you want to install from source with certain packages as well. Good luck!
