### ISSUE TITLE
Unable to write an event file for TF-TRT model

### ISSUE THREAD

**Issue by chiachunfu** [tensorflow/tensorflow#18408]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.11.1
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.0/7.0.5
- **GPU model and memory**: 1080 Ti 8GB
- **Exact command to reproduce**:
```
import tensorflow as tf
from tensorflow.python.platform import gfile
with tf.Session() as sess:
    model_filename ='test_TFTRT.pb'
    with gfile.FastGFile(model_filename, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        g_in = tf.import_graph_def(graph_def)
LOGDIR="/check_graph"
train_writer = tf.summary.FileWriter(LOGDIR)
train_writer.add_graph(sess.graph)
```
### Describe the problem
I was trying to write an event file for a TF-TRT model so I can visualize it after the graph was optimized by TensorRT. When running the snippet above, I got error message:

### Source code / logs
g_in = tf.import_graph_def(graph_def)
  File "/home/user/.virtualenvs/BuildTF_1.7/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/user/.virtualenvs/BuildTF_1.7/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 570, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named TRTEngineOp in defined operations.

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation. Thanks!

**Comment by chiachunfu** [comment]
Thanks for the reply! This seems to be a common problem for ops in tf.contrib. I was wondering if this could be solved by registering the TRTEngineOp (generated by TensorRT) to the Op dict and if someone can fix that for future release. Just want to make sure that people who work on TF-TRT are aware of this issue.

**Comment by wincle** [comment]
I also met the problem,could you please tell me how did you solve it?
My tensorflow was build 1.7.0 from source

**Comment by adavoudi** [comment]
Just add this to your python script:

```
import tensorflow.contrib.tensorrt
```
