### ISSUE TITLE
sneaky re-release of TF 1.7.0?

### ISSUE THREAD

**Issue by boegel** [tensorflow/tensorflow#18424]
Someone informed us that the checksum of the source tarball from https://github.com/tensorflow/tensorflow/archive/v1.7.0.tar.gz changed according to what we had in place (was `2df5e308357356c9ffb7e9a7816dfa9947bd8928f9d406cf7e851b82853931ea`, now is `c676a96fc8700722816b2b98c85578b2f99fac7a7b2484c9c7f0641484f8d50d`).

After some investigation, it seems there was indeed a "re-release" without changing the version number, see https://github.com/easybuilders/easybuild-easyconfigs/issues/6146 for more details.

Can someone confirm this, and share some more information on why this was done?
This sort of practice should really be avoided at all costs...

I guess @annarev could probably shed some light on this, since the most recent `1.7.0` tag done by @annarev.

**Comment by tgamblin** [comment]
This is covered in [section I of Kenneth's talk](https://www.youtube.com/watch?v=NSemlYagjIU#t=4m10s) 😄

**Comment by annarev** [comment]
We re-created the release because we had a last-minute cherrypick (after the release page in Github was created but before we built our pip packages). So, we included the cherrypick in our pip packages and updated release page for consistency.

Sorry for the trouble, I will make sure to avoid it in the future.

**Comment by boegel** [comment]
Thanks for confirming my suspicion @annarev. Do you have any idea how much time passed between the initial 1.7.0 release on GitHub and the current one?

+1 on @tgamblin's remarks. I know it can be very tempting to just quickly include another minor change and replacing the tag (probably assuming that nobody will notice), but it's really bad practice, especially for a popular project like TensorFlow (where you can be damned sure *somebody* will suffer from doing this).
Note that PyPI hard prevents you from doing this, if you would have pushed any `pip` packages there for the initial release, you would have been forced to do another point release (and rightfully so).

**Comment by mboisson** [comment]
Did the tag v1.7.0 change too ?

**Comment by annarev** [comment]
I don't remember exactly how much time passed in between, but I think it was ~1 day.
That's right, v1.7.0 tag was re-created.

The points you bring up make sense. Sorry for the trouble!

**Comment by martinwicke** [comment]
This was a mistake and we are taking steps to prevent it in future. No tags should ever change (and definitely no releases).

I'm sorry about the additional work (and confusion) this has caused.
