### ISSUE TITLE
Implement an efficient AssignMatMul() for general BLAS GEMM pattern

### ISSUE THREAD

**Issue by fritzo** [tensorflow/tensorflow#1843]
TensorFlow currently lacks efficient in-place matrix updates such as rank-1 update `A += U V'`. @rmlarsen recommends supporting these in-place updates through a single new `AssignMatMul()` method that wraps the underlying GEMM kernels in Eigen or cuBlas etc.

**Comment by girving** [comment]
This hasn't gotten much attention, but I like it so I'm going to leave it open in the forlorn hope that someone will eventually do it.

**Comment by harshini-gadige** [comment]
We are going to close this issue. Feel free to reopen it if you want to contribute and link the PR to it.
