### ISSUE TITLE
Op type not registered 'GatherV2' error when using libtensorflow maven artifacts

### ISSUE THREAD

**Issue by eric-czech** [tensorflow/tensorflow#18463]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: maven
- **TensorFlow version (use command below)**: 1.7.0-rc1
- **Java version**: 1.8.0_162
- **GPU model and memory**: Tesla K80

### Describe the problem
When attempting to use the **libtensorflow** maven artifacts mentioned in the [GPU Support for Java](https://www.tensorflow.org/versions/master/install/install_java#gpu_support) page to load an exported graph, I received the error:

```
Exception in thread "main" org.tensorflow.TensorFlowException: Op type not registered 'GatherV2'
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:39)
	at net.imagej.ops.experiments.filter.deconvolve.FlowdecGraph.load(FlowdecGraph.java:38)
```

Please let me know if any other information would help, but the error seems pretty informative so I just wanted to check and see if support for newer operations like "GatherV2" were likely to make it into the java artifacts in the near future.

It may also help to note that the same code I was running works just fine when using either python or the non-gpu-enabled java artifact like this:

```
<dependency>
         <groupId>org.tensorflow</groupId>
         <artifactId>tensorflow</artifactId>
         <version>1.7.0-rc1</version>
</dependency>
```

But switching that to these dependencies results in the error (with no other changes):

```
<dependency>
	<groupId>org.tensorflow</groupId>
	<artifactId>libtensorflow</artifactId>
	<version>1.7.0-rc1</version>
</dependency>
<dependency>
	<groupId>org.tensorflow</groupId>
	<artifactId>libtensorflow_jni_gpu</artifactId>
	<version>1.7.0-rc1</version>
</dependency>
```

Thanks for the help!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
Exact command to reproduce

**Comment by eric-czech** [comment]
**Bazel version**: N/A
**CUDA/cuDNN version**: N/A (This error occurs with and without a GPU and I see no way that CUDA lib versions apply -- I think it's solely related to missing ops in the java API)
**Exact command to reproduce**:

```python

# Generate and export a graph with a "GatherV2" op in it

import tempfile
import numpy as np
import tensorflow as tf

tmp = tempfile.mkdtemp()
!rm -rf $tmp
builder = tf.saved_model.builder.SavedModelBuilder(tmp)

g = tf.Graph()
with g.as_default():
    x = tf.placeholder(tf.float32, shape=[5, 5])
    y = tf.gather(x, tf.range(0, 5), axis=0)

   # Running this a second time is what puts GatherV2 into the graph (does not happen w/o this line)
    y = tf.gather(y, tf.range(0, 5), axis=1)
    
with tf.Session(graph=g) as sess:
    signature = tf.saved_model.signature_def_utils.build_signature_def(
        inputs={'x': tf.saved_model.utils.build_tensor_info(x)},
        outputs = {'y': tf.saved_model.utils.build_tensor_info(y)}
    )

    builder.add_meta_graph_and_variables(
        sess, [tf.saved_model.tag_constants.SERVING],
        signature_def_map={tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY: signature}
    )
    
    xv = np.arange(25).reshape(5, 5)
    yv = sess.run(y, {x: xv})
        
builder.save(as_text=True)

> INFO:tensorflow:SavedModel written to: b'/var/folders/vc/j01b02990c7g90mw6v_dqpsw0000gn/T/tmpx0od_epb/saved_model.pbtxt'
```

Then when importing this into java with the following maven dependencies:

```xml
<dependency>
	<groupId>org.tensorflow</groupId>
	<artifactId>libtensorflow</artifactId>
	<version>1.7.0</version>
</dependency>
<dependency>
	<groupId>org.tensorflow</groupId>
	<artifactId>libtensorflow_jni_gpu</artifactId>
	<version>1.7.0</version>
</dependency> 
<dependency>
	<groupId>org.tensorflow</groupId>
	<artifactId>proto</artifactId>
	<version>1.7.0</version>
</dependency>
```

```java
public class TFDebug {
	public static void main(String[] args) throws InvalidProtocolBufferException {
		String path = "/var/folders/vc/j01b02990c7g90mw6v_dqpsw0000gn/T/tmpx0od_epb/";
		SavedModelBundle model = SavedModelBundle.load(path, "serve");
		MetaGraphDef metaGraph = MetaGraphDef.parseFrom(model.metaGraphDef());
	}
}
// Running this results in:
Exception in thread "main" org.tensorflow.TensorFlowException: Op type not registered 'GatherV2'
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:39)
	at net.imagej.ops.experiments.filter.deconvolve.TFDebug.main(TFDebug.java:12)
```

**Comment by eric-czech** [comment]
Hi @asimshankar ,

Sorry to have wasted your time on this but just knowing that it was working for you forced me to go back and consider other possibilities which ultimately led me to find that through a transitive dependency, an older version of the tensorflow artifacts was getting pulled into my maven build.  I excluded those and it works just as it did for you.

Thanks for the help though!  And apologies again for the false positive issue.
