### ISSUE TITLE
tensorflow version not updating to 0.7.1 using pip

### ISSUE THREAD

**Issue by vignesh10** [tensorflow/tensorflow#1848]
Hi,

I recently updated to tensorflow version 0.7.1 using the command:

`pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl`

If I run `pip show tensorflow`, then it gives me that version of tensorflow as `0.6.0`. However, `tf.__version__` in python gives me `0.7.1` 

I am using pip to install a few other dependencies(like prettytensor), it looks for the latest  version of tensorflow. Since it fails to find the latest version using pip, it isnt updating my other dependencies.

Please let me know if there is a workaround for this. Thanks in advance!

**Comment by vrv** [comment]
Is it possible to uninstall tensorflow and then reinstall?
