### ISSUE TITLE
Can device run tensorflow lite be used as a work task when performing distribute training?

### ISSUE THREAD

**Issue by fengpingbaustem** [tensorflow/tensorflow#18489]
Tensorflow lite is designed for mobile device, so can the lite version be used to do some training work. Like using the standard version tensorflow as parameter server, and the edge mobile device do some edge computing and work with the ps?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by fengpingbaustem** [comment]
the tensorflow version and platform are neither associate with this issue, it's just a common question, if there is a way or any plan to support it, please kindly share the info. Thanks.

**Comment by andrehentz** [comment]
Training using TF Lite is not currently supported. There are no short-term plans to support it.
