### ISSUE TITLE
UnimplementedError: Cast uint8 to uint32 is not supported

### ISSUE THREAD

**Issue by elbaro** [tensorflow/tensorflow#18529]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.7.0-0-g024aecf414
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.1/7.1.1
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
UnimplementedError: Cast uint8 to uint32 is not supported

It is unintuitive that tf.cast from uint8 to float32 works, but uint8 to uint32 does not.
Please document or implement unsupported pairs of numerical dtypes for tf.cast.

### Source code / logs
```
x = tf.cast(uint8_tensor, dtype=tf.uint32)
```
```
   return [tf.reduce_sum(tf.cast(orig, dtype=tf.uint32))]
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 782, in cast
    return gen_math_ops.cast(x, base_type, name=name)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1524, in cast
    "Cast", x=x, DstT=DstT, name=name)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): Cast uint8 to uint32 is not supported
	 [[Node: Cast_1 = Cast[DstT=DT_UINT32, SrcT=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_img_0_0)]]
```

**Comment by yongtang** [comment]
In TensorFlow, the following integer types are supported:
`uint8`, `int8`, `uint16`, `int16`, `int32`, `int64`. 

`uint32` and `uint64` are not supported so the `UnimplementedError` is the expected error.

There might be some enhancement that could be done in the docs. Added a PR #18561 for docs update.

**Comment by LucaCappelletti94** [comment]
It seems that in newer versions of TensorFlow, the uint32 has been added. Do you know which is the version when this happened?
