### ISSUE TITLE
[r1.7][TensorRT] The passing parameter "max_batch_size" within function "trt.create_inference_graph()" is fixed to 1

### ISSUE THREAD

**Issue by oscarriddle** [tensorflow/tensorflow#18548]
What do I intended to do:
I've already trained a model by TensorFlow, and then try to use the integrated TensorRT to import the frozen model and optimize it, then output the optimized graph_def and session run it by TensorFlow.

Script:                                                 
```
      with tf.Graph().as_default():
         with tf.device("/device:GPU:0"):                                                                                 
            output_graph_def = tf.GraphDef()
            with open("./"+frozen_model_name, "rb") as f:
               output_graph_def.ParseFromString(f.read())
               print (len(output_graph_def.node))
               _ = tf.import_graph_def(output_graph_def, name="")
                                                                                   
        f32_graph = trt.create_inference_graph(
            input_graph_def=output_graph_def,                                                                                       
            outputs=['InceptionV3/Logits/SpatialSqueeze'],
            max_batch_size = 16,  #<<<<<<<<<<<<<<<HERE
            max_workspace_size_bytes=1 << 20,
            precision_mode="FP32",  # TRT Engine precision "FP32","FP16" or "INT8"                                        
            minimum_segment_size=2  # minimum number of nodes in an engine                                                
        )
```
Log:
```
host/replica:0/task:0/device:GPU:0 with 4757 MB memory) -> physical GPU (device: 0, name: Tesla P4, pci bus id: 0000:00:08.0, compute capability: 6.1)
Traceback (most recent call last):
  File "extract_model_tf_trt_frozen.py", line 118, in <module>
    _main()
  File "extract_model_tf_trt_frozen.py", line 91, in _main
    val = sess.run(out, {inp: batch_input})
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1116, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (16, 299, 299, 3) for Tensor u'import/Placeholder:0', which has shape '(1, 299, 299, 3)'
```

Observation:
Seems like even though I set the passing parameter "max_batch_size" to 16, the generated new graph still only has batch_size == 1. I can't locate the source file of trt_convert(), which is relevant actually, probably it's a binary .o file so I can only post a new issue here for help.

Has anyone encountered the same issue?
Any idea will be welcome.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by oscarriddle** [comment]
Hi tensorflowbutler,

Sorry for ignoring the required information.

- Have I written custom code: No
- OS Platform and Distribution:  Red Hat 4.8.5-16, Linux version 3.10.0-693.5.2.el7.x86_64
- TensorFlow installed from: pip (python 2.7)
- TensorFlow version: tensorflow-gpu==1.7.0
- Bazel version: N/A
- CUDA/cuDNN version: CUDA9.0, cuDNN7.0.5
- GPU model and memory: Tesla P4, 8GB
- Exact command to reproduce: 
My own script is coded based on the official test "tensorflow/tensorflow/contrib/tensorrt/test/test_tftrt.py", so I think you can reproduce this problem with this test. The point is "max_batch_size" within trt.create_inference_graph().

Thanks,

**Comment by oscarriddle** [comment]
I figured out the root-cause.
It's because the dimension of Placeholder of the frozen model is (1, 299, 299, 3) and it can' be modified once been generated.
The solution is to regenerate a binary graph.pbtxt of the model with input placeholder(?, 299, 299, 3), then freeze it and use tensorrt to optimize it.

**Comment by aaroey** [comment]
@oscarriddle Good to hear that, and thanks for the information!

**Comment by Isaamarod** [comment]
@oscarriddle  @tensorflowbutler  I'm trying to execute tfrt.py but y have this problems:
  File "test_tftrt.py", line 27, in <module>
    from tensorflow.contrib import tensorrt as trt
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tensorrt/__init__.py", line 25, in <module>
    from tensorflow.contrib.tensorrt.python import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tensorrt/python/__init__.py", line 22, in <module>
    from tensorflow.contrib.tensorrt.python.ops import trt_engine_op
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tensorrt/python/ops/trt_engine_op.py", line 25, in <module>
    from tensorflow.contrib.tensorrt.ops.gen_trt_engine_op import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tensorrt/ops/gen_trt_engine_op.py", line 11, in <module>
    from tensorflow.python.eager import context as _context
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/context.py", line 50, in <module>
    DEVICE_PLACEMENT_EXPLICIT = pywrap_tensorflow.TFE_DEVICE_PLACEMENT_EXPLICIT
AttributeError: module 'tensorflow.python.pywrap_tensorflow' has no attribute 'TFE_DEVICE_PLACEMENT_EXPLICIT'


Do you know ?

Thanks
