### ISSUE TITLE
Incremental builds are very slow

### ISSUE THREAD

**Issue by ry** [tensorflow/tensorflow#1856]
I'm following the instructions from "Setting up TensorFlow for Development" in `tensorflow/g3doc/get_started/os_setup.md`

If I make a small change to `core/kernels/eigen_spatial_convolutions.h` and rebuild the pip package (`bazel build --config=cuda //tensorflow/tools/pip_package:build_pip_package`) the process takes **204 seconds**.

**Comment by martinwicke** [comment]
You picked the worst file to modify. It's included a lot and building it is pretty hard on the compiler. There's not all that much we can do about this, sorry. I would guess that those 204s do not include any unnecessary steps.

**Comment by andrei-pokrovsky** [comment]
Seems like build_pip_package can take a very long time by itself especially for debug builds. The amount of data generated is substantial but it's not bound by disk bandwidth. The python build is running on a single thread for 3-4 minutes suggesting the wheel generation process is CPU bound and could benefit from parallelization over multiple threads.
