### ISSUE TITLE
Help with C++API configuration

### ISSUE THREAD

**Issue by JusakNowWorldLater** [tensorflow/tensorflow#18566]
What do I need to choose at `./configure` ?If I just want to start learn tensorflow by C++API , when I choose nothing and run bazel( `bazel build :libtensorflow_cc.so` ) I get 
`ERROR: Skipping ':libtensorflow_cc.so': no such target '//:libtensorflow_cc.so': target 'libtensorflow_cc.so' not declared in package '' defined by /home/vjusak/Tensorflow/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//:libtensorflow_cc.so': target 'libtensorflow_cc.so' not declared in package '' defined by /home/vjusak/Tensorflow/BUILD
INFO: Elapsed time: 0.393s
FAILED: Build did NOT complete successfully (0 packages loaded)
`
Ubuntu 16.10 

> bazel version
`Build label: 0.12.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Aug 4 01:22:27 +50246 (1523462001747)
Build timestamp: 1523462001747
Build timestamp as int: 1523462001747
`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
