### ISSUE TITLE
Feeding variable length list data (from csv) to an 'indicator_column' feature

### ISSUE THREAD

**Issue by imanirajian** [tensorflow/tensorflow#18572]
I have a feature as follows:
`tf.feature_column.indicator_column(tf.feature_column.categorical_column_with_vocabulary_file(...))`

Corresponding 'vocabulary_file' contains integer values as follows:

10
20
32
44
5
1212
...

Consider such training examples:
Jack, M, 22, **"[10, 20]"**, 2.33, 1
Sara, F, 24, **"[32, 44, 5, 1212]"**, 5.6, -1

Each training example has a variable length list data like [10, 20] or [32, 44, 5, 1212]
Now, I want to capture this data from csv file into the 'indicator_column' feature and then feed the multi-hot representation (result) to a deep model. 
The `decode_csv` function only support `float32`, `float64`, `int32`, `int64`, `string` and I have issue for **'list'** type data in csv. 

------------------------

### System information
- **OS Platform**: Win8
- **TensorFlow installed from**: binary
- **TensorFlow version**: 1.5
- **Python version**: 3.6
- **Bazel version**: None
- **CUDA/cuDNN version**: None
- **GPU model and memory**: GPU> None | CPU> AMD(Phenom II x4)
Exact command to reproduce is clear.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by imanirajian** [comment]
@skye

**Comment by skye** [comment]
@mrry do you know if there are any plans to implement something like this?

**Comment by mrry** [comment]
This is already possible: simply apply `tf.string_split(list_column, ',')` to the field with list data to get a `tf.SparseTensor` representing the variable-length list. (You may also need to use `tf.regex_replace()` to remove the `'['` and `']'` characters from the list, if you can't remove them when the data is being produced; and `tf.cast()` to convert the string elements to integers.)

**Comment by imanirajian** [comment]
@skye , @mrry 

1. I've removed `'['` and `']'` during data generation process. Therefore the values of `list_column` is now something like these:
**"10, 20"
"32, 44, 5, 1212"**

2. I've implemented the mentioned solution as follows:

`list_column = tf.string_split(list_column, ',')`

but that caused this error:

> ValueError: Shape must be rank 1 but is rank 0 for 'StringSplit' (op: 'StringSplit') with input shapes: [], [].

**Comment by imanirajian** [comment]
@mrry @skye @tensorflowbutler 

Converting tensor of string of ints to tensor of list of ints done successfully. But I get an error when passing this resulted tensor to the `indicator_column` or `embedding_column` as follows:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot batch tensors with different shapes in component 4. First element had shape [5] and element 1 had shape [4].`

`	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?], [?], [?], [?], [?,?], ..., [?], [?], [?], [?], [?]], output_types=[DT_INT32, DT_FLOAT, DT_STRING, DT_STRING, DT_INT32, ..., DT_STRING, DT_STRING, DT_STRING, DT_FLOAT, DT_BOOL], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
`

**Comment by mrry** [comment]
Judging from the error, you are attempting to use `Dataset.batch()` on a dataset of elements with different shapes. If the elements have different shapes, you must either (i) transform them to all have the same shape (e.g. using `Dataset.map()`) or (ii) use `Dataset.padded_batch()` to add padding to some of the components.

**Comment by imanirajian** [comment]
@mrry 
Some of my features have different length values, But I already defined `embedding_column`s for them in my model. An `embedding_column` has a constant `dimension` so why shapes various when I parse and map my dataset and then pass them to the model?

**Comment by imanirajian** [comment]
@mrry 
Consider you have an `embedding_column` named `ec`. `ec` is defined in estimator model for accepting a sparse column. Further consider the column's values are different length integer list. How you parse and pass the column to `ec` then to the estimator?

**Comment by GoingMyWay** [comment]
@imanirajian 

Have you figured out how to input variable length feature data to get embedding columns?

**Comment by wannibar** [comment]
# coding: utf-8
import collections
import os
import sys
import time
import re
import math
import random

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow.python.feature_column.feature_column import _CategoricalColumn
from tensorflow.python.framework import dtypes, tensor_shape
from tensorflow.python.ops import parsing_ops, array_ops, string_ops
from tensorflow.python.framework import sparse_tensor as sparse_tensor_lib
from tensorflow.python.util import deprecation

plt.rcParams['font.sans-serif'] = ['Arial Unicode MS']  # plt中文显示
pd.set_option('display.max_columns', None)  # pandas显示所有列
pd.set_option('display.max_rows', None)  # pandas显示所有行
pd.set_option('max_colwidth', 1000)
pd.set_option('display.width', 1000 * 10)
np.set_printoptions(threshold=sys.maxsize)


class SparseVarLenCategoricalColumnWithHashBucket(_CategoricalColumn,
                                                  collections.namedtuple('SparseVarLenCategoricalColumnWithHashBucket',
                                                                         ['key', 'hash_bucket_size', 'delimiter'])):
    """
    输入为 X1&X2&X3 形式, &为delimiter
    """

    @property
    def name(self):
        return self.key

    @property
    def parse_example_spec(self):
        return {self.key: parsing_ops.VarLenFeature(dtypes.string)}

    _FEATURE_COLUMN_DEPRECATION_DATE = None
    _FEATURE_COLUMN_DEPRECATION = ('The old _FeatureColumn APIs are being '
                                   'deprecated. Please use the new FeatureColumn '
                                   'APIs instead.')

    @property
    @deprecation.deprecated(_FEATURE_COLUMN_DEPRECATION_DATE,
                            _FEATURE_COLUMN_DEPRECATION)
    def _parse_example_spec(self):
        return self.parse_example_spec

    def _transform_feature(self, inputs):

        input_tensor = inputs.get(self.key)
        print("DEBUG", input_tensor)
        flat_input = array_ops.reshape(input_tensor, (-1,))
        input_tensor = tf.string_split(flat_input, self.delimiter)

        if not isinstance(input_tensor, sparse_tensor_lib.SparseTensor):
            raise ValueError('key={key} must be sparse tensor'.format(key=self.key))

        sparse_values = input_tensor.values
        sparse_id_values = string_ops.string_to_hash_bucket_fast(sparse_values, self.hash_bucket_size, name='lookup')
        return sparse_tensor_lib.SparseTensor(input_tensor.indices, sparse_id_values, input_tensor.dense_shape)

    @property
    def _variable_shape(self):
        if not hasattr(self, '_shape'):
            self._shape = tensor_shape.vector(self.hash_bucket_size)
        return self._shape

    @property
    def _num_buckets(self):
        return self.hash_bucket_size

    def _get_sparse_tensors(self, inputs, weight_collections=None, trainable=None):
        return _CategoricalColumn.IdWeightPair(inputs.get(self), None)


def categorical_column_with_var_len_hash_bucket(key, hash_bucket_size, delimiter=","):
    return ValueError('invalid hash_bucket_size {} !'.format(hash_bucket_size)) if (hash_bucket_size is None) or (hash_bucket_size < 1) \
        else SparseVarLenCategoricalColumnWithHashBucket(key, hash_bucket_size, delimiter)


custom_cat_col = categorical_column_with_var_len_hash_bucket("seq", hash_bucket_size=10, delimiter="&")
custom_cat_emd_col = tf.feature_column.embedding_column(categorical_column=custom_cat_col, dimension=5, combiner='sum')
print(custom_cat_emd_col)

features = {
    'seq': [[""], ['A'], ['B'], ['C'], ['A&B'], ['A&B&B'], ["A&B&C"]],
}

tensor = tf.feature_column.input_layer(features, [custom_cat_emd_col])

with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    session.run(tf.tables_initializer())
    print(session.run([tensor]))
=========
这是我的实现，可以支持pb导出，直接传 “1&2”，不用padding。
