### ISSUE TITLE
tf.train.batch does not work with tf.uint32 and tf.uint64 data types

### ISSUE THREAD

**Issue by jml6757** [tensorflow/tensorflow#18586]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

```
import tensorflow as tf

values = tf.constant([0, 1, 2, 3, 4], dtype=tf.uint64)
batch = tf.train.batch(
    [values],
    batch_size=2,
    num_threads=1,
    enqueue_many=True,
)

with tf.Session() as sess:
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(sess=sess, coord=coord)

    print(sess.run(batch))

    coord.request_stop()
    coord.join(threads)
```

### Describe the problem
`tf.train.batch` does not work on tensors with types `uint32` or `uint64`. It works with all other primitive types. The source of this issue can be traced back to `CopyElementToSlice` which calls `TF_CALL_ALL_TYPES`

https://github.com/tensorflow/tensorflow/blob/3128b43eb0bf37ac3c49cb22a6e1789d8ea346e8/tensorflow/core/kernels/batch_util.cc#L94

This `TF_CALL_ALL_TYPES` macro eventually calls into `TF_CALL_INTEGRAL_TYPES` 

https://github.com/tensorflow/tensorflow/blob/3128b43eb0bf37ac3c49cb22a6e1789d8ea346e8/tensorflow/core/framework/register_types.h#L154

This macro includes `int8`, `uint8`, `int16`, `uint16`, `int32`, and `int64` but **does not** include `uint32` or `uint64`

The change to support these types appears to be simple, but since `TF_CALL_ALL_TYPES` is a high-level macro, I did not know if these data types were purposefully excluded.

**Comment by poxvoculi** [comment]
@alextp Do you know why these types are excluded?

**Comment by kr-ish** [comment]
I wonder if the issue in this SO question is related to this one? https://stackoverflow.com/questions/49437216/tf-data-dataset-from-generator-not-supporting-uint16-uint32

**Comment by alextp** [comment]
Can you try changing the definition of tf_call_all_types and send a pull request? A lot of our dtype handling decisions aren't very principled..
