### ISSUE TITLE
Python 2 linux GPU nightly link in readme is wrong

### ISSUE THREAD

**Issue by lahwran** [tensorflow/tensorflow#1859]
Hey! I wanted to try out the scan op, so I installed the latest. however, on doing so, I discovered that no nightly build has been attempted in jenkins for about 20 days. if this is simply because one has not been run, could someone at google hit build and then take a look at why it hasn't run?

Note: I don't mean it's failed; I mean there are no builds in the list newer than that, failed or otherwise.

In the meantime, I'll install from source.

### Environment info
Operating System: Linux; Ubuntu/14.04

Installed version of CUDA and cuDNN: irrelevant

installed from binary pip package: http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.7.1-cp27-none-linux_x86_64.whl

### What are you about to try?

1. building from source.

**Comment by vrv** [comment]
Does http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-working/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.7.1-cp27-none-linux_x86_64.whl work? 

(difference seems to be gpu-working vs. gpu-slave)

**Comment by lahwran** [comment]
oh huh! it's not that it isn't building, it's that the wrong one is linked from the readme.

**Comment by lahwran** [comment]
this is silly trivial. I'll make a pr.

**Comment by vrv** [comment]
I think we keep moving the URL as we add more jenkins instances and forgetting to change the README :(  sorry about that
