### ISSUE TITLE
No documentation for Saver class

### ISSUE THREAD

**Issue by cemkod** [tensorflow/tensorflow#186]
There are multiple references to **Saver** class in *api_docs/python/train.md* and *tutorials/mnist/tf/index.md*, yet the documentation for the Saver class does not exist. 

Is there any way I can help with the documentation?

**Comment by vrv** [comment]
Hm, our doc links are sort of broken on the tensorflow.org website.  We'll fix it, but in the meantime: 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/state_ops.md#Saver

**Comment by vrv** [comment]
new website update fixes this: http://www.tensorflow.org/api_docs/python/state_ops.html#Saver
