### ISSUE TITLE
Strange result of float division

### ISSUE THREAD

**Issue by weichiche** [tensorflow/tensorflow#18635]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.5.0
- **Python version**: 
3.5.2
- **CUDA/cuDNN version**:
9.0
- **GPU model and memory**:
GTX 1080Ti

### Describe the problem

The below Numpy and TensorFlow codelets produce different results, while I suppose they should be the same.

```python
import numpy as np
import tensorflow as tf

x = np.array([247.], dtype=np.float32)
y = x / 255.
print('{:12.10f}'.format(y[0]))
# 0.9686274529

a = tf.placeholder(tf.float32)
b = a / 255.
with tf.Session() as sess:
    _b = sess.run(b, feed_dict={a: x})
print('{:12.10f}'.format(_b[0]))
# 0.9686275125
```

Running on CPU gives the same issue.

However, if I use `a = tf.constant(x, dtype=tf.float32)` instead of `tf.placeholder`, the result seems correct.

Is this an issue about `tf.placeholder` or something else? Does this affect other operations?

**Comment by Benyuel** [comment]
@weichiche: I'm not a tensorflow expert, but I suspect you're seeing a difference in the behavior in your example is because of casting between types and precision handled inside tensorflow vs inside numpy. 

Python's standard float type is a C double.  Numpy's standard `np.float` is a reference to python's float.  Therefore your divisor in `y`, 255., is actually np.float64.  You've specifically declared x as `np.float32`.  So because of numpy's casting logic, your resulting y is `np.float32 / np.float64 = np.float32`.  

In tensorflow, it looks like your `a` is declared as `tf.float32` but when tf runs `tf.convert_to_tensor` on 255., the type is inferred according to tensorflow and `255.` is treated as a `Constant tf.float32`.  So your op is `tf.float32 / tf.float32 = tf.float32`

 If I do the following in float64, the tf result matches numpy:
```
import numpy as np
import tensorflow as tf

x = np.array([247.], dtype=np.float64)
y = x / 255.
print('{:12.10f}'.format(y[0]))
# 0.9686274510

a = tf.placeholder(tf.float64)
b = a / 255.
with tf.Session() as sess:
    _b = sess.run(b, feed_dict={a: x})
print('{:12.10f}'.format(_b[0]))
# 0.9686274510
```

For `tf.placeholder` and using `feed_dict`, If the feed_dict key is a tf.Tensor, the value may be a Python scalar, string, list, or numpy ndarray that can be converted to the same dtype as that tensor.

**Comment by weichiche** [comment]
@Benyuel: I tried explicitly making the divisor `float32`, and the discrepancy still exists. Though if I test with `float64`, I get identical results just as you did.

**Comment by Benyuel** [comment]
@weichiche:    I suspect that tensorflow core is doing the division or casting dtypes differently, and if so, the question then becomes if tf operations using `tf.placeholder` should mirror numpy logic or not?   
With a constant, the value is a part of the computation graph itself, specified when the constant is created. With a placeholder, every time you run the computation graph, you can feed in a different value in your feed_dict, and tf core has to do some checking/casting.

```
import numpy as np
np.can_cast(np.float32, np.float64)
# True
np.can_cast(np.float64, np.float32)
# False
```
Internal numpy casting logic: `np.float64` cannot be automatically cast to `np.float32`
```
# Returns the data type with the smallest size and smallest scalar kind to which both type1 and type2 may be safely cast. The returned data type is always in native byte order.
# Per my previous comment, x = np.float32, y = np.float64
np.promote_types(np.float32, np.float64)
# dtype('float64')
```
Therefore, numpy core is actually performing `np.float64 / np.float64` and then casting to `np.float32`.

Also, you're printing 10 digits, so you're likely within the rounding error (Single precision (float32) ~= 7 decimal digits, Double precision(float64) ~= 16 decimal digits).  Instead of printing and checking equality for floating point, you probably just check `np.allclose`.

**Comment by weichiche** [comment]
@Benyuel: I said that _I tried explicitly making the divisor `float32`_. Let's make it more clear. For Numpy,

```python
np_dtype = np.float32

x = np.array(247., dtype=np_dtype)
z = np.array(255., dtype=np_dtype)
y = x / z

print(x.dtype, x)
print(z.dtype, z)
print(y.dtype, list(struct.pack('!f', y)))
```

prints

```
float32 247.0
float32 255.0
float32 [63, 119, 247, 248]
```

For TensorFlow,

```python
tf_dtype = tf.float32

a = tf.placeholder(tf_dtype)
c = tf.constant(255., dtype=tf_dtype)
b = a / c

with tf.Session() as sess:
    _a, _b, _c = sess.run([a, b, c], feed_dict={a: x})
    
print(a.dtype.name, _a)
print(c.dtype.name, _c)
print(b.dtype.name, list(struct.pack('!f', _b)))
```

prints

```
float32 247.0
float32 255.0
float32 [63, 119, 247, 249]
```

The number of printed digits may be inappropriate. But both `y` and `_b` are Numpy data, thus they should be represented in the same way. Anyhow, I turn to print the bytes which should reflect the true difference.

As to your question

> ... and if so, the question then becomes if tf operations using `tf.placeholder` should mirror numpy logic or not?

I hope so. It'll make less confusion, at least for former Numpy users.

**Comment by Benyuel** [comment]
@weichiche: Had a random idea and it seems to work with placeholders.  It may help in figuring this out

```
import tensorflow as tf
import numpy as np

x = np.array([247.], dtype=np.float32)
y = x / 255.

with tf.device('/device:CPU:0'):
  a = tf.placeholder(tf.float32)
  b = tf.placeholder(tf.float32)
  c = a / b

config = tf.ConfigProto(log_device_placement=True)
with tf.Session(config=config) as sess:
  _c = sess.run(c, feed_dict={a:x, b:255.})

print('TF:     {:12.10f}'.format(_c[0]))
print('NUMPY: {:12.10f}'.format(y[0]))
```

**Comment by weichiche** [comment]
@Benyuel: Do you suggest that the device matters?

I've found that using `tf.placeholder` for both divident and divisor results in quotient consistent with Numpy. How ever, if you declare the divisor by `tf.constant`, on CPU, the output is inconsistent again.

**Comment by Benyuel** [comment]
Correct, I'm not saying that device matters.

I think I've narrowed it down to one of 2 or both possible causes, not 100% certain though:
1.  How type conversion is handled
2.  How a constant tensor is embedded into the graph def which means it is stored in the client and in the runtime.  Placeholders values are as you would expect not stored in the graph def. 

Sorry for all of these snippets, but here's another one.
```
a = 247.
b = 255.
x = np.array([247.], dtype=np.float32)
y = x / b
# x.dtype = float32
# x.tobytes() = b'\x00\x00wC'
# np.array(b).dtype = float64
# np.array(b).tobytes() = b'\x00\x00\x00\x00\x00\xe0o@'
# y = 0.9686274529
```

```
a_placeholder_32 = tf.placeholder(tf.float32)
c = a_placeholder_32 / b
# b is treated as a tf.constant by default
sess = tf.Session()
_c  = sess.run(c,  feed_dict={a_placeholder_32:x})
# numerator = float32
# denominator = float64
print(sess.graph_def.node[0].attr['dtype'])
print(sess.graph_def.node[1].attr['dtype'])
# numerator & denominator in graph_def = DT_FLOAT
 np.array(b).tobytes() = b'\x00\x00\x00\x00\x00\xe0o@'
_c =  0.9686275125
```

```
a_placeholder_32 = tf.placeholder(tf.float32)
b_placeholder_32 = tf.placeholder(tf.float32)
c = a_placeholder_32 / b_placeholder_32
sess = tf.Session()
_b_placeholder_32 = sess.run(b_placeholder_32, feed_dict={b_placeholder_32:b})
_c  = sess.run(c,  feed_dict={a_placeholder_32:x, b_placeholder_32:b})
# numerator = float32
# denominator = float32
print(sess.graph_def.node[0].attr['dtype'])
print(sess.graph_def.node[1].attr['dtype'])
# numerator & denominator in graph_def = DT_FLOAT
print(_b_placeholder_32.tobytes())
# b'\x00\x00\x7fc'
_c =  0.9686274529
```

Note the difference in bytes in the denominators.
Note the difference in denominator dtypes.

**Comment by weichiche** [comment]
@Benyuel: I've made a misleading example in my first comment. Please allow me to rephrase my questions.

Consider two _float32-by-float32_ divisions:

* (**_TF_**) dividing a `tf.float32` `Tensor` created by `tf.placeholder()` by a `float32` `Tensor` created by `tf.constant()` ,
* (**_NP_**) dividing an `np.float32` (or `np.float32` `ndarray` created by `np.array()`) by another `np.float32` (or `np.float32` `ndarray` created by `np.array()`).

and a statement:

* (**_S_**) (_TF_) produces, numerically, the same quotient as (_NP_),

Here're the questions:

1. Can we expect (_S_)?
2. Should we expect (_S_)?

---

As to our long-discussed example (i.e. dividing 247 by 255).

In Numpy, if the dividend is a scalar (created by `np.float32(247.)`) or a 0-dimensional array (created by `np.array(247., dtype=np.float32)`), the division by a Python `float` (which is actually a 64-bit float as you mentioned before) will be lifted to a _float64-by-float64_ division. However, if the dividend is an array with one or more dimensions (e.g. created  by `np.array([247.], dtype=np.float32)`), then the divisor is converted to a 32-bit float, and the result is the same as _float32-by-float32_ division. So the first snippet in your last comment, whether the divisor is 32-bit or 64-bit, gives exact result of (_NP_).

Your second snippet is an example of (_TF_). Though the divisor is 64-bit, it is converted to a `DT_FLOAT`, which I think is 32-bit. This division should also be a _float32-by-float32_ division. But somehow the result is slightly different from that of (_NP_), even if the divisor is explicitly created as 32-bit using `tf.constant(255., dtype=tf.float32)`. This is where my concern comes from.

I've tried the same example in TensorFlow 1.1.0, and the result is consistent with (_NP_). It looks like this issue is introduced during TensorFlow upgrading. 

The third snippet is out of my consideration, as it gives expected result.

**Comment by tensorflowbutler** [comment]
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by sachinprasadhs** [comment]
`tf.placeholder` is not compatible with eager execution(which is default in Tensorflow 2) and in `tf.function` and there is no plan to modify that, upgrade your Tensorflow version to recent version and report a new issue for any errors/challenges. Thanks!
