### ISSUE TITLE
TensorFlow 1.8.0-rc1 fails on aarch64 platforms

### ISSUE THREAD

**Issue by psyhtest** [tensorflow/tensorflow#18643]
Building TensorFlow 1.8.0-rc0 from source fails on aarch64 platforms (NVIDIA TX1 and Linaro HiKey960) with a linking error for some Neon function:
```
Linking of rule '//tensorflow/cc:ops/remote_fused_graph_ops_gen_cc' failed (Exit 1)
bazel-out/host/bin/_solib_arm/_U_S_Stensorflow_Scc_Cops_Sremote_Ufused_Ugraph_Uops_Ugen_Ucc___Utensorflow/libtensorflow_framework.so: error: undefined reference to 'png_init_filter_functions_neon'
```

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A (a build problem)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 (JetPack 3.1)
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.8.0-rc0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.12.0
- **GCC/Compiler version (if compiling from source)**: 5.4.1
- **CUDA/cuDNN version**: N/A (CPU ony)
- **GPU model and memory**: N/A (CPU only)
- **Exact command to reproduce**: Install dependencies and build via [CK-TensorFlow](github.com/ctuning/ck-tensorflow):
```
$ sudo apt install liblapack-dev libatlas-dev
$ sudo pip install enum34 mock pillow wheel absl-py scipy ck
$ ck pull repo:ck-tensorflow
$ ck install ck-env:package:tool-bazel-0.12.0-linux
$ ck install package:lib-tensorflow-1.8.0-src-cpu --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1
```
**NB:** Restricting the number of building processes to 1 is necessary to prevent running out of memory on the NVIDIA TX1 platform (4 GB and no swap enabled) or similar.

### Describe the problem

Building TensorFlow 1.8.0-rc0 fails on aarch64 platforms (NVIDIA TX1 and Linaro HiKey960). Similar instructions for TensorFlow 1.7.0 with Bazel 0.11.1 worked well (both with and without XLA support):
```
$ ck install package:lib-tensorflow-1.7.0-src-cpu --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1
$ ck install package:lib-tensorflow-1.7.0-src-cpu-xla --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1

$ ck show env --tags=tensorflow,v1.7
Env UID:         Target OS: Bits: Name:                                       Version: Tags:

ed191cc45dda7ee4   linux-64    64 TensorFlow library (from sources, cpu, xla) 1.7      64bits,bazel,channel-stable,host-os-linux-64,lib,needs-bazel,needs-bazel-0.11.1,target-os-linux-64,tensorflow,tensorflow-cpu,v1,v1.7,v1.7.0,vcpu,vsrc,vxla
ed191cc45dda7ee3   linux-64    64 TensorFlow library (from sources, cpu)      1.7      64bits,bazel,channel-stable,host-os-linux-64,lib,needs-bazel,needs-bazel-0.11.1,target-os-linux-64,tensorflow,tensorflow-cpu,v1,v1.7,v1.7.0,vcpu,vsrc
```

### Source code / logs
```
ERROR: /home/anton/CK_TOOLS/lib-tensorflow-src-cpu-1.8-linux-64/src/tensorflow/cc/BUILD:510:1: Linking of rule '//tensorflow/cc:ops/remote_fused_graph_ops_gen_cc' failed (Exit 1)
bazel-out/host/bin/_solib_arm/_U_S_Stensorflow_Scc_Cops_Sremote_Ufused_Ugraph_Uops_Ugen_Ucc___Utensorflow/libtensorflow_framework.so: error: undefined reference to 'png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 15373.402s, Critical Path: 153.22s
FAILED: Build did NOT complete successfully
```

**Comment by Amrsaeed** [comment]
Getting same error when building Tensorflow 1.7.0 with the same system information and Bazel 0.12.0

**Comment by psyhtest** [comment]
FWIW, I've got a different error building TensorFlow 1.7.0 using Bazel 0.12.0 on Linaro HiKey960:
```
$ ck install package:lib-tensorflow-1.7.0-src-cpu --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=2
...
ERROR: /home/anton/.cache/bazel/_bazel_anton/19f8e08691d47ead673afa362fc193f9/external/jpeg/BUILD:269:1: C++ compilation of rule '@jpeg//:simd_armv7a' failed (Exit 1)                                                                                                   
gcc: error: unrecognized command line option '-mfloat-abi=softfp'                                                       
Target //tensorflow/tools/pip_package:build_pip_package failed to build                                                                                                                                                                                                  
Use --verbose_failures to see the command lines of failed build steps.                                            
INFO: Elapsed time: 668.059s, Critical Path: 63.27s                                                                                                                                                                                                                      
FAILED: Build did NOT complete successfully
```
Smells like a Bazel 0.12.0 problem separate from the issue reported here.

**Comment by shivaniag** [comment]
@gunan could you please take a look?

**Comment by psyhtest** [comment]
@gunan You can simply follow Collective Knowledge based instructions above. They encapsulate a couple of patches our community found necessary on aarch64 systems (including TX1).

**Comment by gunan** [comment]
@psyhtest Thanks for the pointer. However I am reaching out to my teammates who I know has looked into running and building TF on NVIDIA Tegra TX1 before, to check if we have any official instructions somewhere. Sorry for the ambiguous question I posted above.

**Comment by psyhtest** [comment]
@gunan No problem at all. Just wanted to help you reduce the drudgery to the minimum and accelerate time-to-solution :).

**Comment by Davidnet** [comment]
I confirm I have found the same error on Jetson TX2 with r1.8 and bazel 0.12

**Comment by Davidnet** [comment]
More concretely:
```
ERROR: /home/nvidia/Documents/tensorflow/tensorflow/python/BUILD:1569:1: Linking of rule '//tensorflow/python:gen_set_ops_py_wrappers_cc' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/nvidia/.cache/bazel/_bazel_nvidia/38f510ce87073e6e7989e37d45036c24/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64/: \
    PATH=/usr/local/cuda/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/host/bin/tensorflow/python/gen_set_ops_py_wrappers_cc '-Wl,-rpath,$ORIGIN/../../_solib_local/_U_S_Stensorflow_Spython_Cgen_Uset_Uops_Upy_Uwrappers_Ucc___Utensorflow' '-Wl,-rpath,$ORIGIN/../../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' -Lbazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Uset_Uops_Upy_Uwrappers_Ucc___Utensorflow -Lbazel-out/host/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib '-Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..' -Wl,-z,notext -Wl,-z,notext -Wl,-rpath,../local_config_cuda/cuda/lib64 -Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64 -pthread -Wl,-no-as-needed -B/usr/bin/ -pie -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,--gc-sections -Wl,-S -Wl,@bazel-out/host/bin/tensorflow/python/gen_set_ops_py_wrappers_cc-2.params)
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Uset_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 4073.346s, Critical Path: 358.03s
```

**Comment by psyhtest** [comment]
1.8.0-rc1 fails too; also on Firefly-RK3399.

**Comment by WilliamJuel** [comment]
I can confirm (as stated above) that  TensorFlow 1.7.0 with Bazel 0.11.1 works. But i have to change the hardcoded x86 paths to aarch64 in tensorflow....

**Comment by psyhtest** [comment]
@WilliamJuel Interesting. Could you please provide a couple of examples what you need to do? I don't think we need to change anything with our automatic Collective Knowledge workflow. By the way, feel free to give it a try to see if it's easier than what you have to do currently.

**Comment by jessebenson** [comment]
Potentially the same/related issue - the nightly Raspberry Pi builds are hitting this (and have been failing for several weeks now):
http://ci.tensorflow.org/view/Nightly/job/nightly-pi/245/console

**Comment by gunan** [comment]
I think on our end, our bazel build did not work on tegra tx1 yet. As far as I can learn internally our makefile build was working on tx1 last we experimented.
I will keep on looking to see if we have docs or instructions.

**Comment by psyhtest** [comment]
@gunan I believe one does need to patch Bazel on TX1 but the Collective Knowledge package takes care of that. So you can install Bazel using one CK command, and then TensorFlow using another one. (Just copy and paste the instructions from the top of the issue, and give it 10 hours )

This will allow you to reproduce the issue in the least painful way. As you can see from other reports, it's not specific to using CK for TensorFlow installation.

**Comment by gunan** [comment]
What I am trying to say is, we never officially made it working. It may or may not work, but we got the makefile build working.
I will mark this issue contributions welcome. I will add our official status later when I have it.

**Comment by psyhtest** [comment]
@gunan What I mean is that we've been able to build TensorFlow on TX1 since 1.4.0. 1.8.0-rc0 was the first to break.

If TX1 is not officially supported, then surely Raspberry Pi is (if it's part of the nightlies)? I agree with @jessebenson - it looks like the same issue. Would it be easier for you to investigate it there? I could help you then test across other aarch64 platforms I have access to (TX1, HiKey960, RK3399)?

**Comment by psyhtest** [comment]
If you google (sorry) for the name of the function (`png_init_filter_functions_neon`), you may find similar issues e.g. https://github.com/opencv/opencv/issues/7600.

**Comment by gunan** [comment]
Nightlies mean we are working on it. If it is released as an artifact during releases, or announced during releases that means we have official support for it.
We definitely want tensorflow to build and work properly on both TX1 and Raspberry Pi.
However, we want to make sure we have proper infrastructure to continuously build and test it before we announce our official support.

**Comment by jessebenson** [comment]
@psyhtest - yeah I looked into this yesterday, and found the same link you pointed out.  I was able to get the Raspberry Pi nightlies to build by adding `--copt=-DPNG_ARM_NEON_OPT=0` - see (https://github.com/jessebenson/tensorflow/commit/b135e2d9a234e23cebc7b6d63043b40b07e76a1a).  I didn't include this in my pull request (https://github.com/tensorflow/tensorflow/pull/18892), as I'm not sure if that's the desired fix.

**Comment by psyhtest** [comment]
@jessebenson @peterlee0127 Thanks for the update! We'll give it a go.

**Comment by psyhtest** [comment]
@peterlee0127 I've incorporated your patch into [ck-tensorflow:package:lib-tensorflow-1.8.0-src-cpu](https://github.com/ctuning/ck-tensorflow/tree/master/package/lib-tensorflow-1.8.0-src-cpu), and tested the latest TensorFlow v1.8.0 can be built with the latest Bazel v0.13.0:
```
$ sudo apt install liblapack-dev libatlas-dev
$ sudo pip install enum34 mock pillow wheel absl-py scipy ck
$ ck pull repo:ck-tensorflow
$ ck install ck-env:package:tool-bazel-0.13.0-linux
$ ck install package:lib-tensorflow-1.8.0-src-cpu [--env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1]
```
Specifically, here's how I built on Firefly RK3399 (4 GB RAM, with swap):
```
$ ck install package:lib-tensorflow-1.8.0-src-cpu --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=3
...
Installation time: 24036.3912299 sec.
```
and on Jetson TX1 (4 GB RAM, without swap):
```
$ ck install package:lib-tensorflow-1.8.0-src-cpu --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1
...
Installation time: 51031.3029599 sec.
```
(In other words, it took less than 7 hours on RK3399, and more than 14 hours on TX1.)

Look forward to a more elegant solution to appear in TensorFlow v1.9.0, so this workaround is no longer needed.

**Comment by peterlee0127** [comment]
In TX2, it still need about 3 hours. We should use cross compiler for building whl file in the future.

**Comment by psyhtest** [comment]
[firefly-accuracy_top1-500-tf-complete.pdf](https://github.com/tensorflow/tensorflow/files/1972867/firefly-accuracy_top1-500-tf-complete.pdf)

**Comment by psyhtest** [comment]
@peterlee0127 Agree but it sounds a bit scary given all the dependencies.

**Comment by psyhtest** [comment]
![firefly-accuracy_top1-500-tf-complete](https://user-images.githubusercontent.com/6597818/39606680-80ac2e1a-4f2e-11e8-922b-1d6f884b3315.png)

**Comment by jessebenson** [comment]
@gunan - can you take a look at this PR as well?  https://github.com/tensorflow/tensorflow/pull/18892  I want to get the official binaries built so I can extend Tensorflow for C# (https://github.com/migueldeicaza/TensorFlowSharp) to use ARM natively.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by gunan** [comment]
This issue is fixed at head.
As 1.8 did not have official support for this platform, we will not patch the previous release.
