### ISSUE TITLE
Feature request: tf.layers.Layer.{trainable_variables,updates,...} should return values from all sublayers

### ISSUE THREAD

**Issue by olesalscheider** [tensorflow/tensorflow#18665]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: 0.12.0
- **GCC/Compiler version (if compiling from source)**: 7.2
- **CUDA/cuDNN version**: 7.1
- **GPU model and memory**: Nvidia Titan Xp (12 GB)

### Describe the problem
The properties trainable_variables, updates, and so on of tf.layers.Layer currently only returns the corresponding objects from the layer itself. This is different from Keras where it adds the corresponding objects from all child layers.
Please consider to make the behaviour of tf.layers.Layer the same as Keras. In it's current form, these properties are not really helpful.

**Comment by allenlavoie** [comment]
Could you go into a bit more detail on your use-case? The expectation is that Layers which have sub-Layers will inherit from `tf.keras.Model`. Most built-in Layers don't have any sub-Layers to return variables/updates from.

**Comment by olesalscheider** [comment]
Ok, I was not aware that `tf.layers.Layer` is only supposed to be used for built-in layers. My understanding was that `tf.layers` sits beside Keras and could be used on it's own. And since there was no `Network` or `Model` in `tf.layers` I used `Layer`.

But if the expectation is that everyone uses `tf.keras.Model` that's ok.

**Comment by allenlavoie** [comment]
Yes, we're trying to keep the number of symbols down, sorry for the confusion. Using Layers from `tf.keras.layers` is good too (there shouldn't be much difference and they'll both work with `tf.keras.Model`, but we're slowly migrating toward the `tf.keras.layers` versions).
