### ISSUE TITLE
Documentation mistake?

### ISSUE THREAD

**Issue by Sentient07** [tensorflow/tensorflow#18692]
Hi,

The documentation [page](https://www.tensorflow.org/api_docs/python/tf/unstack) of `tf.unstack` says the equivalent is np.unstack. But np doesn't have an unstack method? (Should have been np.split ? ) 

Cheers,

**Comment by yongtang** [comment]
The tf.unstack is not truly compatible with numpy.split. There is an op of tf.split but this is also different with numpy.split in that the second arg `num_or_size_splits` vs `indices_or_sections` are also different. I created a PR #18694 to simply remove the mentioning of numpy equivalent for tf.unstack for now.
