### ISSUE TITLE
Make Python/Numpy include paths configurable

### ISSUE THREAD

**Issue by hannes-brt** [tensorflow/tensorflow#187]
The Mac OS X Numpy and Python include paths are hard-coded to `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include` and `/usr/include/python2.7`. I am on OS X 10.11 and I use the Anaconda Python distribution (installed to `/Users/<user>/anaconda`).

Currently, Bazel doesn't find my headers:

```
./tensorflow/python/client/tf_session_helper.h:4:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^
1 error generated.
```

It would be great if Python include paths could be configured in `configure` along with the cuDNN and CUDA paths.

**Comment by tscheepers** [comment]
I just ran into the same problem. A configuration would be great. Just for now I solved this by editing https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/BUILD#L23 and add your Python / Numpy include paths, e.g. for OS X `"-I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7"`

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/commit/bf6b536bde7d8060c489b51fedb58968b8cbfd7c added the ability to configure the python paths -- as a consequence, we require users to now run ./configure before invoking bazel so they can specify the paths.

Let us know if this works for you!
