### ISSUE TITLE
tf.count_nonzero should support string tensors

### ISSUE THREAD

**Issue by adamcrume** [tensorflow/tensorflow#18712]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: 1.8
- **Python version**: N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: tf.count_nonzero(tf.constant(["test"]))

### Describe the problem
tf.count_nonzero should support string tensors, since tf.zeros and tf.zeros_like work with string tensors.

### Source code / logs
tf.count_nonzero(tf.constant(["test"]))

**Comment by yongtang** [comment]
Added a PR #18715 to support `tf.string` with `tf.count_nonzero`.

**Comment by adamcrume** [comment]
Thanks for the quick fix!
