### ISSUE TITLE
tensorflow problem

### ISSUE THREAD

**Issue by tbousole** [tensorflow/tensorflow#18738]
how to solve the following error? ImportError: No module named '_pywrap_tensorflow_internal'
I have python  3.5 installed, Jupyter Notebook along with Ananconda also installed.

**Comment by cchan** [comment]
Hi @tbousole, can you provide more information? At minimum, tensorflow version and a piece of code that reproduces the error would be needed.

**Comment by tbousole** [comment]
import tensorflow as tf

reset_graph()

x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x*x*y + y + 2

i am using tensorflow version 1.5

**Comment by vijaysaimutyala** [comment]
@tboousele, if you're using the CPU version on Windows, can you please try installing version 1.4. This turned out to be a good workaround for a friend of mine.

**Comment by cchan** [comment]
@tbousole what is `reset_graph()`? The following code works fine for me:
```
import tensorflow as tf

tf.reset_default_graph()

x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x * y + y + 2
```

**Comment by cchan** [comment]
Perhaps also take a look at #11571.

**Comment by angersson** [comment]
This is a duplicate of #11571 (thanks for the link, @cchan). Please move discussion over there so that advice is not spread across the tracker. Thanks!
