### ISSUE TITLE
Tensorflow_lite Android Demo compiled failed on Windows

### ISSUE THREAD

**Issue by 1icas** [tensorflow/tensorflow#18751]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**: 
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:

### Describe the problem

I download the tensorflow , use the git clone today.
And when i open the android studio, and open the tensorflow_lite demo(contrib/lite/java/demo).
some errors occur.

### Source code / logs

some errors occured on my android studio console:  Error:Could not find tensorflow-lite.jar (org.tensorflow:tensorflow-lite:0.1.8-rc1).
Searched in the following locations:
    https://jcenter.bintray.com/org/tensorflow/tensorflow-lite/0.1.8-rc1/tensorflow-lite-0.1.8-rc1.jar

Consult IDE log for more details (Help | Show Log)

**Comment by ZZANZU** [comment]
I have same error.... it worked well few days ago...weird!

**Comment by sokunmin** [comment]
+1

**Comment by juanluisrto** [comment]
Same. Please fix this

**Comment by zhonghuabao1** [comment]
the same to me

**Comment by aselle** [comment]
@sokunmin, do you have insight in what that does? Should we do this for all platforms and not just on Windows?

**Comment by isaisachen** [comment]
Hi @1icas, could you try again? Sorry that we had a bad push last Friday (mismatched artifact name) and this error was expected. But we immediately fixed the repo during the weekend.

**Comment by sokunmin** [comment]
@aselle I used it on Mac OS X, and encountered the same problem. I was happened to find .aar in https://jcenter.bintray.com/org/tensorflow/tensorflow-lite/0.1.7/, and it worked for me since I changed to aar. Yes, it should work for all platforms. 

@isaisachen I tried and it's still not working. 

Thanks.

**Comment by isaisachen** [comment]
@sokunmin Did you try on Mac for the first time today or you tried last Friday as well?

The demo app configured below
    compile 'org.tensorflow:tensorflow-lite:+'
1st step Android Studio does is downloading 
https://google.bintray.com/tensorflow/org/tensorflow/tensorflow-lite/maven-metadata.xml
which tells you what's the latest version.

And we once had a broken 0.1.8-rc1 published. 

If you don't clear the project / gradle local cache, it will stick with 0.1.8-rc1 without re-consulting maven-metadata.xml (which is fixed now w/ all 0.1.8-rc* removed).

You can try deleting ~/.gradle/caches on Mac OS and clean / rebuild your Android project.

**Comment by sokunmin** [comment]
@isaisachen Hey, it works like a charm now since I deleted the caches folder using `org.tensorflow:tensorflow-lite:+`. I did try today and last week. Thanks for your great help!

**Comment by 1icas** [comment]
I'm very sorry reply so late. I solve this problem use another method. I download the tensorflow-lite.aar and add this aar to this demo.

**Comment by 1icas** [comment]
Sovled

**Comment by Elites2017** [comment]
> 
> 
> I'm very sorry reply so late. I solve this problem use another method. I download the tensorflow-lite.aar and add this aar to this demo(also need modified the build.gradle).

@1icas I have the same problem, the other solutions proposed above don't work for me.

What line did you edit in the build.gradle? and after downloading the tensorflow-lite.aar, where did you add it in the project?

**Comment by wqw547243068** [comment]
> @sokunmin Did you try on Mac for the first time today or you tried last Friday as well?
> 
> The demo app configured below
> compile 'org.tensorflow:tensorflow-lite:+'
> 1st step Android Studio does is downloading
> https://google.bintray.com/tensorflow/org/tensorflow/tensorflow-lite/maven-metadata.xml
> which tells you what's the latest version.
> 
> And we once had a broken 0.1.8-rc1 published.
> 
> If you don't clear the project / gradle local cache, it will stick with 0.1.8-rc1 without re-consulting maven-metadata.xml (which is fixed now w/ all 0.1.8-rc* removed).
> 
> You can try deleting ~/.gradle/caches on Mac OS and clean / rebuild your Android project.

I am wondering where should I palce the new xml file ?
