### ISSUE TITLE
Documentation issues regarding installing on ubuntu

### ISSUE THREAD

**Issue by hedenface** [tensorflow/tensorflow#18767]
While I was perusing the documentation for install_linux, I got to the section *Determine which TensorFlow to install*, and then I continued on.

I was at *Determine how to install TensorFlow* and I settled on *Virtualenv*. So I went to that section, and I followed the steps. But when I got to the sub-section (2) stating

> where `targetDirectory` specifies the top of the Virtualenv tree. Our instructions assume that `targetDirectory` is `~/tensorflow`, but you may choose any directory.

I was caught off guard a bit. I didn't know if I had missed something, so I spent a bit of time back-tracking the documentation to see if that was the case. I finally decided to `mkdir ~/tensorflow` and give it a go.

It would be nice if there was a (sub-)section stating this. I don't want to write it, so I'm making it as an issue instead. I did do this amazing thing though: #18766

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hedenface** [comment]
> Have I written custom code

No

> OS Platform and Distribution

Linux Mint

> TensorFlow installed from

My issue is regarding the documentation before installation, so I'll say this is N/A.

> TensorFlow version

N/A

> Bazel version

N/A

> CUDA/cuDNN version

N/A

> GPU model and memory

N/A

> Exact command to reproduce

N/A

My issue is simply regarding some confusion I faced during reading the installation documentation.

**Comment by poxvoculi** [comment]
thanks for the PR.

**Comment by martinwicke** [comment]
@lamberta maybe see if this can be clarified. But the branching install is going to be some cognitive burden no matter how much we describe the steps.

**Comment by hedenface** [comment]
I don't disagree that it will be a cognitive burden. (I like that phrase). I mean more in the sense of "did I miss something?" and then having to re-read to identify that I did not in fact miss anything.

Or even something like "read all the way through before doing anything." If I were better with words I would probably be able to come up with something better than that. No words, only code.

Thanks!

**Comment by lamberta** [comment]
Thanks for reporting.
The entire page could use a scrubbing, but I went through the pip install instructions using virtualenv and system install and clarified some steps (and cut out some cruft).
