### ISSUE TITLE
tf-nightly-gpu wheels are no more deployed for python 3.6 since 2018/03/30

### ISSUE THREAD

**Issue by nicoulaj** [tensorflow/tensorflow#18791]
The tensorflow GPU wheels (https://pypi.org/project/tf-nightly-gpu) for python 3.6 are no more deployed since 2018/30/30, as shown by:

```
pip3.6 install tf-nightly-gpu==
```

Have I written custom code: N/A
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sleighsoft** [comment]
Same goes for windows builds. They are not available for 1.9 and some 1.8 builds.

**Comment by sleighsoft** [comment]
Is this a jenkins issue or why are the windows build not there anymore?

**Comment by carlthome** [comment]
I just ran into the same issue. Very confusing.

**Comment by sleighsoft** [comment]
This is important for me. Is there any news on this Tensorflow Team?

**Comment by bhack** [comment]
There is a problem also with the py3 related docker images:
https://hub.docker.com/r/tensorflow/tensorflow/tags/

**Comment by av8ramit** [comment]
Thanks for filing. I've fixed the python 3.6 build for tf-nightly-gpu.

**Comment by av8ramit** [comment]
I believe the nightly docker py3 images are fixed as well.

**Comment by bhack** [comment]
Can we close this?

**Comment by av8ramit** [comment]
Windows build fix is in flight. Closing this issue for now.
