### ISSUE TITLE
tf.image.extract_glimpse not work as expected

### ISSUE THREAD

**Issue by YantianZha** [tensorflow/tensorflow#18815]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: r1.8
- **Python version**: 2.7.14
- **GCC/Compiler version (if compiling from source)**: 5.4
- **CUDA/cuDNN version**: 8.0/7.0
- **GPU model and memory**: GTX1080, 8G
- **Bazel version**: N/A
- **Exact command to reproduce**: python test_script.py

### Describe the problem
The output for the code below, is not correct. To me, the correct output should be: [0.   1.    2.    3.   4.  ]. The offset is [0, 0], and the centered is false, so the starting point is at the most upper left pixel (with the value 0). And the glimpse height is 1 and width is 5, so the glimpse should be the first row. 

### Source code / logs
import tensorflow as tf
import numpy as np

input_img = np.float32(np.arange(25).reshape((5, 5)))
print input_img

input_img = tf.expand_dims(input_img, 0)
input_img = tf.expand_dims(input_img, -1)

offset_ = tf.expand_dims([0.0, 0.0], 0)
first_glimpse = tf.image.extract_glimpse(input_img, [1, 5], offset_,
                                    centered=False, normalized=False, uniform_noise=False)
first_glimpse = tf.squeeze(first_glimpse)
sess = tf.Session()
print first_glimpse.eval(session=sess)

Output:
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
[16.995655 12.920303  0.        1.        2.      ]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Exact command to reproduce

**Comment by YantianZha** [comment]
Updated. Thanks.

**Comment by facaiy** [comment]
@YantianZha Hi, perhaps you mistake the `offset`, which is the center of each window. See its [API](https://www.tensorflow.org/versions/master/api_docs/python/tf/image/extract_glimpse):

> A 2-D integer tensor of shape [batch_size, 2] containing the y, x locations of the **center** of each window.

**Comment by YantianZha** [comment]
@facaiy Hi, thanks for your help. I set up centered argument to false in my code. According to the centered argument usage in API: "If false, the (0,0) offset corresponds to the upper left corner of the input images."

**Comment by shivaniag** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
