### ISSUE TITLE
Using out-of-graph Reward in Reinforcement Learning with Iterator in tf.data

### ISSUE THREAD

**Issue by gsh199449** [tensorflow/tensorflow#18818]
When the reward value is generated from a script that is not computed in Tensorflow graph, like ROUGE score in text summarization or BLEU score in machine translation.
We first use the graph to generate a prediction result, then calculate the reward value out of the graph, and then feed the value into the graph to update the parameters of our model by policy gradients.
If we use session.run, this will cause recomputation that is mentioned in #672.  
Although recomputation does not cost very much, when we use the `tf.dataset` with `Iterator`, the dataset pointer will move to the next sample when calling `session.run` function.
In #672, they suggest to use `partitial_run` instead of `session.run`. But `partitial_run` can only fetch the tensor, but it can not execute the operation. 

So can you add a feature that can move the pointer of `Iterator` backward? or fix the pointer when calling the `session.run` function?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gsh199449** [comment]
Have I written custom code : N/A
OS Platform and Distribution : all platform
TensorFlow installed from : pip
TensorFlow version : all version
Bazel version : N/A
CUDA/cuDNN version: N/A
GPU model and memory : N/A
Exact command to reproduce : N/A

**Comment by jart** [comment]
Feature request relating to `tf.data` backwards iterators for @mrry.

**Comment by mrry** [comment]
Thanks for the suggestion. We do not plan to add this feature to `tf.data`, because it would complicate—and completely change—the implementation and make it more difficult to add optimizations in the future. For this kind of workflow, I'd suggest using the recently added Eager Execution mode, and storing any iterator values that you need to reuse in a local variable in your Python code.
