### ISSUE TITLE
Update website with correct Cuda info

### ISSUE THREAD

**Issue by petewarden** [tensorflow/tensorflow#1881]
I received this on twitter:
"Can you please help update TF website to state TF-GPU needs nvidia compute cap. >= 3.5 and to install cudNN v4 (not 5). Thanks"
https://twitter.com/AlliseeSolution/status/719789250082766848

I'm not using Cuda myself, so I'm not sure of the details here, but wanted to get it logged so somebody more knowledgeable can take a look.

**Comment by alliseesolutions** [comment]
Thanks Pete!  I twittered that.  I'm new to github community.  Here is a screenshot. I have a GTX 780 with Nvidia compute capability 3.5 and it works great!

https://www.dropbox.com/s/b9dhbz46iqhfer7/tf.jpg?dl=0

**Comment by vrv** [comment]
@alliseesolutions: which documentation was incorrect?  https://www.tensorflow.org/versions/r0.7/get_started/os_setup.html#optional-install-cuda-gpus-on-linux appears accurate but we may have stale docs somewhere.

**Comment by vrv** [comment]
Oh, our pip install for 0.7.1 was only built for cuda 3.5, but I believe our installs for 0.8.0+ will probably support 3.0 natively.

**Comment by alliseesolutions** [comment]
P.s.  I just remembered that screenshot was when I installed cudnn v5  which I later found causes an error in tensorflow.  

At that time I also installed too recent of Nvidia drivers I had 364.15 installed when Tensorflow requires 352.79 I beleive.  Things I learned troubleshooting the 780 card!

For community sake I would be willing to test my gtx 770 with cudnn v4 and proper drivers to see if it works.

Ubuntu 14.04 LTS

**Comment by alliseesolutions** [comment]
@vrv see above post I think I should test this out before making assumptions but I beleive what may need to be updated is that tensorflow website says minimum required cuda compute is 3.0 when the screenshot shows 3.5.  But there is a possibility the error was because I was using v5 of cudnn.

**Comment by vrv** [comment]
If you build from sources you can use both cudnnv5 and cuda compute 3.0.  We only build pips for the latest official cudnn (v4), and the nightly pip packages now are built with 3.0 support.

**Comment by alliseesolutions** [comment]
Ok so far I have tried my GTX 770 (Nvidia compute capability 3.0) using the pip install and cudnn v4 and no dice same error as above.  Will try building from sources later and see what happens.

**Comment by alliseesolutions** [comment]
Compiled from source everything worked fine with my Cuda Compute Cap. 3.0 card.

**Comment by alliseesolutions** [comment]
Also tested that latest 0.8 pip release with cudnn v4 and it works fine with the card as well.

**Comment by vrv** [comment]
I believe our docs https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html are currently accurate.
