### ISSUE TITLE
does tensorflow take all resource from GPU, making other CUDA code slow ?

### ISSUE THREAD

**Issue by ChiFang** [tensorflow/tensorflow#18822]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
I have a custom CUDA code but not register into Tensorflow OP
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary: by "pip3 install --upgrade tensorflow-gpu"
- **TensorFlow version (use command below)**:
tensorflow-gpu (1.7.0)
- **Python version**: 
Python 3.5.2
- **Bazel version (if compiling from source)**: 0.11.0
- **GCC/Compiler version (if compiling from source)**:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- **CUDA/cuDNN version**: CUDA 9.0 cuDNN 7
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
I have a cuda lib build from C++ for post-processing after predict result by tensorflow model.
I use following way to make python able to use cuda code from C++
`lib = ctypes.cdll.LoadLibrary(my.so)`

If I test the cuda code alone without tensorflow. it work fine.
But when tensorflow is used in my project, my cuda code become 10 times slower....

My  time log is in cuda .so lib, so it's no way that the gap come from python to .so  wrap.

I have try to set the fraction of GPU memory to be allocated in tensorflow by:
`# Assume that you have 12GB of GPU memory and want to allocate ~4GB:`
`gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)`
`sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))`

but useless....
so I wonder does tensorflow take all resource from GPU, making other CUDA code slow ?
the only solution is make my cuda code as a tensorflow OP by register?

Any suggestion? Thanks~~~

----------------------Update----------------------
I have tested following way to set gpu_options, but still useless....
`config = tf.ConfigProto()`
`config.gpu_options.allow_growth = True`
`sess = tf.Session(config=config)`

**Comment by sleighsoft** [comment]
Maybe your GPU is just busy doing tensorflow calculations.

**Comment by ChiFang** [comment]
Hi @sleighsoft
my program flow is:
tensorflow calculations >> post-processing cuda code 
It won't calculate at same time.
I just wonder if tensorflow force every code in same project or scope share same resource from GPU.
I have 2 GeForce GTX 1080, I have tested that make tensorflow only see the first one.
But it make my C++ cuda code only see the same one in the available GPU device list....

Any idea to workaround? Thanks.....

**Comment by sleighsoft** [comment]
You could try allowing your process to see both GPUs then move your tensorflow calculations to e.g. GPU 1 with `tf.device` and your post-processing to GPU 0.

**Comment by sleighsoft** [comment]
You could try allowing your process to see both GPUs then move your tensorflow calculations to e.g. GPU 1 with `tf.device` and your post-processing to GPU 0.

**Comment by jart** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by ChiFang** [comment]
hi @jart 
I think it might be a bug.  Because once tensorflow be active. it will make every cuda code crash even I use "sess.close()"...
The case mentioned above is run on specific NVIDIA driver to make it don't crash.

The following code it a simple example cuda code run by [pycuda](https://documen.tician.de/pycuda/).
once I add `sess = tf.Session()` .  My cuda code crash. It work fine without `sess = tf.Session()`.

`import tensorflow as tf`
`import pycuda.autoinit`
`import pycuda.driver as drv`
`import numpy`
`from pycuda.compiler import SourceModule`
`mod = SourceModule("""`
`__global__ void multiply_them(float *dest, float *a, float *b)`
`{`
  `const int i = threadIdx.x;`
 ` dest[i] = a[i] * b[i];`
`}`
`""")`
`## tensorflow will make any other cuda code crash................................`
`sess = tf.Session()`
`sess.close()`
`multiply_them = mod.get_function("multiply_them")`
`a = numpy.random.randn(400).astype(numpy.float32)`
`b = numpy.random.randn(400).astype(numpy.float32)`
`dest = numpy.zeros_like(a)`
`multiply_them(drv.Out(dest), drv.In(a), drv.In(b), block=(400,1,1), grid=(1,1))`
`print (dest-a*b)`
`print("finish")`



It would be wonderful if tensorflow could allow other cuda code

**Comment by brucechou1983** [comment]
@ChiFang  Do you find any solution for this? I ran into the same issue. Tried allow_growth option but no luck.
