### ISSUE TITLE
Distortions in Retrain.py (Transfer learning w/ inception model) take exceedingly long

### ISSUE THREAD

**Issue by oweingrod** [tensorflow/tensorflow#1882]
### Environment info

Operating System:
Ubuntu 14.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
CUDA: 7.5
cuDNN: 6.5 (v2)
Using nVidia Quadro K2200

If installed from sources, provide the commit hash:
fe9dafd1583da5ccc205eab776f86afcb00411d2
### Steps to reproduce

Retrain.py runs fine without any distortions. Not massively faster than CPU, but faster.
NVIDIA-SMI shows that the GPU has 3824mb used during training.

If any distortions are used, training becomes very, very, long. It takes almost ten minutes for ten images to be trained.

Is this very slow speed intended?

Best

Oren

**Comment by felixmaximilian** [comment]
Hi @oweingrod,

you probably find the explanation for the slow training [here](https://github.com/tensorflow/tensorflow/blob/d4bf5e072478c92cae2bd71b96e10e77e229dfba/tensorflow/examples/image_retraining/retrain.py#L497).
It's said that bottleneck caching cannot be applied if distortions are enabled. That means the bottlenecks are calculated by the inception model for each image and each step.

Even it makes sense that the randomized distortion is applied ad-hoc when an images is processed, I wonder if would be possible to apply the distortions before the training is executed to create more training examples. Then we are able to precompute and cache the bottlenecks again. I see one tricky problem arising: The handling of train and validation splits will be trickier.

Cheers,
Max

**Comment by girving** [comment]
@petewarden: Assigning you since it's about retraining.

**Comment by petewarden** [comment]
I'm moving this one to contributions welcome, since I'm unlikely to have a chance to work on this.

**Comment by aselle** [comment]
@nealwu, could you consider this bug in your creation of garden models.

**Comment by nealwu** [comment]
Yep, we'll keep retraining in mind. We shouldn't run into this issue in the garden though, at least not with our current set of models.

**Comment by rola93** [comment]
I had the same issue. How about adding some noise to precalculated bottlenecks?

I'm not sure if this would work, but adding a random vector to each precalculated bottleneck before training with them is cheap enougth. Since those bottlenecks are in the end a feature vector over which there is a linear classifier, it makes sense for me... doesn't it?

**Comment by alextp** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
