### ISSUE TITLE
No module named tensorflow.python.platform

### ISSUE THREAD

**Issue by dinglong1020** [tensorflow/tensorflow#18856]
environment: ubuntu 1604, python 2.7

```
sudo pip install -i https://pypi.tuna.tsinghua.edu.cn/simple/   https://mirrors.tuna.tsinghua.edu.cn/tensorflow/linux/cpu/tensorflow-1.7.0-cp27-none-linux_x86_64.whl
```
there is error, but why???
```
ubuntu@vm:~/code/tensorflow$ python tensorflow/python/tools/freeze_graph.py --input_graph=/tmp/mobilenet_v1_1.0_224.pb --input_binary=true --output_graph=/tmp/frozen_mobilenet_v1_224.pb --output_node_names=MobilenetV1/Predictions/Reshape_1
Traceback (most recent call last):
  File "tensorflow/python/tools/freeze_graph.py", line 45, in <module>
    from tensorflow.core.framework import graph_pb2
  File "/home/ubuntu/code/tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/ubuntu/code/tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/ubuntu/code/tensorflow/tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
ImportError: No module named platform
```

**Comment by dinglong1020** [comment]
thanks, I found the solution, that I need to run command at the $(source_code_root)/tensorflow/tensorflow folder

**Comment by dinglong1020** [comment]
and my command need to modified as:
python -m tensorflow.python.tools.freeze_graph \
--input_graph=/tmp/mobilenet_v1_1.0_224.pb \
--input_checkpoint=/tmp/checkpoints/mobilenet_v1_1.0_224.ckpt \
--input_binary=true \
--output_graph=/tmp/mobilenet_v1_1.0_224_frozen.pb \
--output_node_names=MobilenetV1/Predictions/Reshape_1

**Comment by drpngx** [comment]
Glad you figured it out!

**Comment by Mubashshira** [comment]
@drpngx i m doing in same folder but still giving error

mubashshira_farooqui2000@tensorflow-2-vm:~/tensorflow_build/tensorflow$ python
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
ImportError: No module named platform
