### ISSUE TITLE
use freeze_graph and report TypeError: main() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by dinglong1020** [tensorflow/tensorflow#18865]
ubuntu@vm:~/code/tensorflow/tensorflow$ freeze_graph \
> --input_graph=/tmp/mobilenet_v1_1.0_224.pb \
> --input_meta_graph=/tmp/mobilenet_v1_1.0_224.ckpt.meta \
> --input_binary=true \
> --input_checkpoint=/tmp/checkpoints/mobilenet_v1_1.0_224.ckpt \
> --output_node_names=MobileNetV1/Predictions/Reshape_1 \
> --output_graph=/tmp/mobilenet_v1_1.0_224_frozen.pb
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/local/bin/freeze_graph", line 11, in <module>
    sys.exit(main())
TypeError: main() takes exactly 1 argument (0 given)

**Comment by Swordancer** [comment]
Try input_meta_graph=/tmp/mobilenet_v1_1.0_224.ckpt instead of .meta

**Comment by dinglong1020** [comment]
I found solution:

python -m tensorflow.python.tools.freeze_graph \
--input_graph=/tmp/mobilenet_v1_1.0_224.pb \
--input_checkpoint=/tmp/checkpoints/mobilenet_v1_1.0_224.ckpt \
--input_binary=true \
--output_graph=/tmp/mobilenet_v1_1.0_224_frozen.pb \
--output_node_names=MobilenetV1/Predictions/Reshape_1
