### ISSUE TITLE
[Windows custom ops] Compiled c++ and imported dll successfully, but custom ops are not visible from python?

### ISSUE THREAD

**Issue by cooltopics** [tensorflow/tensorflow#18879]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Win 7 64
- **TensorFlow installed from (source or binary)**: sources
- **TensorFlow version (use command below)**: 1.3.1
- **Python version**: 2.7.13
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: Visual Studio 15
- **CUDA/cuDNN version**: 8.0/7.5
- **GPU model and memory**: NA
- **Exact command to reproduce**: Please see below.

### Describe the problem
Trying to build a library available at https://github.com/optas/latent_3d_points.

It has custom ops implemented in c++.
I have successfully built the package therein specifically `structural_losses` from https://github.com/optas/latent_3d_points/tree/master/external/structural_losses with changes for compiling with Visual Studio 2015.

In python, I am also able to load the ops dlls e.g. using 
`approxmatch_module = tf.load_op_library(osp.join(base_dir, '_approxmatch.pyd')).
`

However, I don't see the operators approxmatch_module.approx_match,approxmatch_module.match_cost, etc. from the c++ getting exposed to the python tensorflow.

I am getting the following error:
`AttributeError: 'module' object has no attribute 'approx_match'
`

When I do the following
```
from structural_losses import approxmatch
dir(approxmatch.approxmatch_module)
```
it lists only the following items
`['LIB_HANDLE', 'OP_LIST', '_InitOpDefLibrary', '__builtins__', '__doc__', '__name__', '__package__', '_collections', '_common_shapes', '_op_def_lib', '_op_def_library', '_op_def_pb2', '_op_def_registry', '_ops']
`
where the actual operations from c++ are missing.

What am I missing from proper compilation?

Or is it that in windows custom ops is `unavailable/not implemented`?

**Comment by tatatodd** [comment]
@mrry might know more about Windows status.

**Comment by mrry** [comment]
@cooltopics Are you certain that the custom library was built and linked correctly? One potential cause for this problem is if the static initializers for Op and Kernel registration are "optimized" out of the final DLL. The [`/WHOLEARCHIVE` option to `link.exe`](https://stackoverflow.com/a/39715978/3574081) might be useful here.

**Comment by cooltopics** [comment]
@mrry Losing hope, I have downloaded Tensorflow version 1.7.1 sources and built anew for Python 3.6 win64. Using this versions combination, it is working. I propose to close this issue as I no longer have the builds for the particular combination mentioned in this issue.

**Comment by VVingerfly** [comment]
Hi, @cooltopics 

Have you solved the problem?

I try to build a tensorflow user op under Window 10. Following the [Official Docs](https://www.tensorflow.org/extend/adding_an_op), I successfully generate a `zero_out.dll` using VS2017, But when I try to load and use it in python, 
```
import tensorflow as tf
zero_out_module = tf.load_op_library('./kernel/zero_out.dll')


use_cpu = True
device_count = {"GPU": 0} if use_cpu else {"GPU": 1}
with tf.Session(config=tf.ConfigProto(device_count=device_count)):
  zero_out_module.zero_out([[1, 2], [3, 4]]).eval()
```
it produces an error with 
```
AttributeError: module 'f21c708d1ddc75dcce283dd13fe531f7' has no attribute 'zero_out'
```

Do I miss something or make any mistakes? Do you have any suggestion?

Thanks a lot.

**Comment by martiningram** [comment]
Hi all,

I just wanted to write that I had the same problem under Mac OS X, and after a lot of dead ends (including building tensorflow from source...!) I realised that I hadn't copied part of the example to my file. In particular, I was missing the `REGISTER_OP` part right at the top of the file. The following file works for me:

`#include "tensorflow/core/framework/op_kernel.h"

#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/shape_inference.h"

using namespace tensorflow;

REGISTER_OP("ZeroOut")
    .Input("to_zero: int32")
    .Output("zeroed: int32")
    .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
      c->set_output(0, c->input(0));
      return Status::OK();
    });

class ZeroOutOp : public OpKernel {
 public:
  explicit ZeroOutOp(OpKernelConstruction* context) : OpKernel(context) {}

  void Compute(OpKernelContext* context) override {
    // Grab the input tensor
    const Tensor& input_tensor = context->input(0);
    auto input = input_tensor.flat<int32>();

    // Create an output tensor
    Tensor* output_tensor = NULL;
    OP_REQUIRES_OK(context, context->allocate_output(0, input_tensor.shape(),
                                                     &output_tensor));
    auto output_flat = output_tensor->flat<int32>();

    // Set all but the first element of the output tensor to 0.
    const int N = input.size();
    for (int i = 1; i < N; i++) {
      output_flat(i) = 0;
    }

    // Preserve the first input value if possible.
    if (N > 0) output_flat(0) = input(0);
  }
};

REGISTER_KERNEL_BUILDER(Name("ZeroOut").Device(DEVICE_CPU), ZeroOutOp);
`

You guys may have a Windows-specific problem, but I thought I'd pass this on anyway.

**Comment by sunglowzhang** [comment]
> @mrry Losing hope, I have downloaded Tensorflow version 1.7.1 sources and built anew for Python 3.6 win64. Using this versions combination, it is working. I propose to close this issue as I no longer have the builds for the particular combination mentioned in this issue.

Hi @cooltopics  Could  you share some information how you solved the problem? To build the user defined op in Windows, do you need to install the tensorflow from source and put the defined c++ in the tensorflow/core/.. ?  Looking forward to your comments!

**Comment by sc1991327** [comment]
> Hi, @cooltopics
> 
> Have you solved the problem?
> 
> I try to build a tensorflow user op under Window 10. Following the [Official Docs](https://www.tensorflow.org/extend/adding_an_op), I successfully generate a `zero_out.dll` using VS2017, But when I try to load and use it in python,
> 
> ```
> import tensorflow as tf
> zero_out_module = tf.load_op_library('./kernel/zero_out.dll')
> 
> 
> use_cpu = True
> device_count = {"GPU": 0} if use_cpu else {"GPU": 1}
> with tf.Session(config=tf.ConfigProto(device_count=device_count)):
>   zero_out_module.zero_out([[1, 2], [3, 4]]).eval()
> ```
> 
> it produces an error with
> 
> ```
> AttributeError: module 'f21c708d1ddc75dcce283dd13fe531f7' has no attribute 'zero_out'
> ```
> 
> Do I miss something or make any mistakes? Do you have any suggestion?
> 
> Thanks a lot.

Hello, 

> Hi, @cooltopics
> 
> Have you solved the problem?
> 
> I try to build a tensorflow user op under Window 10. Following the [Official Docs](https://www.tensorflow.org/extend/adding_an_op), I successfully generate a `zero_out.dll` using VS2017, But when I try to load and use it in python,
> 
> ```
> import tensorflow as tf
> zero_out_module = tf.load_op_library('./kernel/zero_out.dll')
> 
> 
> use_cpu = True
> device_count = {"GPU": 0} if use_cpu else {"GPU": 1}
> with tf.Session(config=tf.ConfigProto(device_count=device_count)):
>   zero_out_module.zero_out([[1, 2], [3, 4]]).eval()
> ```
> 
> it produces an error with
> 
> ```
> AttributeError: module 'f21c708d1ddc75dcce283dd13fe531f7' has no attribute 'zero_out'
> ```
> 
> Do I miss something or make any mistakes? Do you have any suggestion?
> 
> Thanks a lot.

Hello, could you solved this problem?

**Comment by sc1991327** [comment]
> Hi, @cooltopics
> 
> Have you solved the problem?
> 
> I try to build a tensorflow user op under Window 10. Following the [Official Docs](https://www.tensorflow.org/extend/adding_an_op), I successfully generate a `zero_out.dll` using VS2017, But when I try to load and use it in python,
> 
> ```
> import tensorflow as tf
> zero_out_module = tf.load_op_library('./kernel/zero_out.dll')
> 
> 
> use_cpu = True
> device_count = {"GPU": 0} if use_cpu else {"GPU": 1}
> with tf.Session(config=tf.ConfigProto(device_count=device_count)):
>   zero_out_module.zero_out([[1, 2], [3, 4]]).eval()
> ```
> 
> it produces an error with
> 
> ```
> AttributeError: module 'f21c708d1ddc75dcce283dd13fe531f7' has no attribute 'zero_out'
> ```
> 
> Do I miss something or make any mistakes? Do you have any suggestion?
> 
> Thanks a lot.

Hi~

Could you solved this problem?

I have the same problem.

**Comment by ZhuXinyan** [comment]
> Hi all,
> 
> I just wanted to write that I had the same problem under Mac OS X, and after a lot of dead ends (including building tensorflow from source...!) I realised that I hadn't copied part of the example to my file. In particular, I was missing the `REGISTER_OP` part right at the top of the file. The following file works for me:
> 
> ```
> #include "tensorflow/core/framework/op_kernel.h"
> 
> #include "tensorflow/core/framework/op.h"
> #include "tensorflow/core/framework/shape_inference.h"
> 
> using namespace tensorflow;
> 
> REGISTER_OP("ZeroOut")
>     .Input("to_zero: int32")
>     .Output("zeroed: int32")
>     .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
>       c->set_output(0, c->input(0));
>       return Status::OK();
>     });
> 
> class ZeroOutOp : public OpKernel {
>  public:
>   explicit ZeroOutOp(OpKernelConstruction* context) : OpKernel(context) {}
> 
>   void Compute(OpKernelContext* context) override {
>     // Grab the input tensor
>     const Tensor& input_tensor = context->input(0);
>     auto input = input_tensor.flat<int32>();
> 
>     // Create an output tensor
>     Tensor* output_tensor = NULL;
>     OP_REQUIRES_OK(context, context->allocate_output(0, input_tensor.shape(),
>                                                      &output_tensor));
>     auto output_flat = output_tensor->flat<int32>();
> 
>     // Set all but the first element of the output tensor to 0.
>     const int N = input.size();
>     for (int i = 1; i < N; i++) {
>       output_flat(i) = 0;
>     }
> 
>     // Preserve the first input value if possible.
>     if (N > 0) output_flat(0) = input(0);
>   }
> };
> 
> REGISTER_KERNEL_BUILDER(Name("ZeroOut").Device(DEVICE_CPU), ZeroOutOp);
> ```
> 
> You guys may have a Windows-specific problem, but I thought I'd pass this on anyway.

Hi ~,I have met the same question on ubuntu. But the library complied by g++ works well. 
How did you solve this problem?

**Comment by leimao** [comment]
@ZhuXinyan @sc1991327 @sunglowzhang @VVingerfly
It is likely that the building of the shared library did not include the header file correctly.
If this [particular line](https://github.com/tensorflow/custom-op/blob/master/Makefile#L5) is incorrect, the custom op interface will not find the method or attribute correctly.
