### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Exporter'

### ISSUE THREAD

**Issue by sriram-ramanathan** [tensorflow/tensorflow#18889]
When I try to import tensorflow hub in python 2, I get the following error saying that 'module' object has no attribute 'Exporter'.

AttributeErrorTraceback (most recent call last)
<ipython-input-1-31fb71834c8c> in <module>()
      1 # Install TF-Hub.
      2 import tensorflow as tf
----> 3 import tensorflow_hub as hub
      4 import matplotlib.pyplot as plt
      5 import numpy as np

/usr/local/lib/python2.7/dist-packages/tensorflow_hub/__init__.py in <module>()
     24 import tensorflow as tf
     25 
---> 26 from tensorflow_hub.estimator import LatestModuleExporter
     27 from tensorflow_hub.estimator import register_module_for_export
     28 from tensorflow_hub.feature_column import image_embedding_column

/usr/local/lib/python2.7/dist-packages/tensorflow_hub/estimator.py in <module>()
     59 
     60 
---> 61 class LatestModuleExporter(tf.estimator.Exporter):
     62   """Regularly exports registered modules into timestamped directories.
     63 

AttributeError: 'module' object has no attribute 'Exporter'`

**Comment by karmel** [comment]
@agasparovic , can you advise? Looks like there might be some pathing issue here.

**Comment by vbardiovskyg** [comment]
Hi,

I cannot reproduce this. Could you please run:
pip uninstall tensorflow tensorflow_hub
pip install tensorflow==1.8 tensorflow_hub==0.1.0

and confirm that you are still getting the error?

**Comment by maksym33** [comment]
Hello,
I did what you said, and I am still getting the error:
python2 retrain.py 

Traceback (most recent call last):
  File "retrain.py", line 133, in <module>
    import tensorflow_hub as hub
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_hub/__init__.py", line 26, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_hub/estimator.py", line 61, in <module>
    class LatestModuleExporter(tf.estimator.Exporter):
AttributeError: 'module' object has no attribute 'Exporter'

**Comment by vbardiovskyg** [comment]
Ok, so another idea:

1) Create a file test.py with:
```
import tensorflow as tf

print(tf.__version__)
print(tf.estimator.Exporter)
```

2) run `python2 test.py`

**Comment by maksym33** [comment]
python2 test.py 
1.3.0
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(tf.estimator.Exporter)
AttributeError: 'module' object has no attribute 'Exporter'

**Comment by vbardiovskyg** [comment]
So it seems that your python2 has tensorflow 1.3.0 installed. That hints to a problem with pip.

A likely reason is that when you do `pip install tensorflow==1.8`, the `pip` is actually `pip3`.

You can therefore try:
`pip2 show tensorflow tensorflow-gpu tf-nightly tensorflow-hub`
`pip3 show tensorflow tensorflow-gpu tf-nightly tensorflow-hub`

If indeed your `pip` is actually `pip3` (you can check also with `which pip`), you'll have to call `pip2 install tensorflow==1.8 tensorflow_hub==0.1.0`.

**Comment by vbardiovskyg** [comment]
Sorry I missed your last sentence. Yes, that could very well be the issue.

**Comment by maksym33** [comment]
Hi,
So this is the pip2 output:
`pip2 show tensorflow tensorflow-gpu tf-nightly tensorflow-h
ub
Name: tensorflow
Version: 1.8.0
Summary: TensorFlow helps the tensors flow
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: astor, protobuf, gast, tensorboard, six, wheel, absl-py, backports.weakref, termcolor, enum34, numpy, grpcio, mock
Required-by: 
---
Name: tensorflow-gpu
Version: 1.3.0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/maks/.local/lib/python2.7/site-packages
Requires: protobuf, six, tensorflow-tensorboard, wheel, backports.weakref, numpy, mock
Required-by: 
---
Name: tensorflow-hub
Version: 0.1.0
Summary: TensorFlow Hub is a library to foster the publication, discovery, and consumption of reusable parts of machine learning models.
Home-page: https://github.com/tensorflow/hub
Author: Google LLC
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: protobuf, numpy, six
Required-by:`
and pip3 output:
`pip3 show tensorflow tensorflow-gpu tf-nightly tensorflow-hub
---
Metadata-Version: 2.0
Name: tensorflow
Version: 1.8.0
Summary: TensorFlow helps the tensors flow
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
Installer: pip
License: Apache 2.0
Location: /home/maks/.local/lib/python3.5/site-packages
Requires: termcolor, grpcio, absl-py, wheel, gast, astor, numpy, six, protobuf, tensorboard
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  Intended Audience :: Education
  Intended Audience :: Science/Research
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
  Topic :: Scientific/Engineering
  Topic :: Scientific/Engineering :: Mathematics
  Topic :: Scientific/Engineering :: Artificial Intelligence
  Topic :: Software Development
  Topic :: Software Development :: Libraries
  Topic :: Software Development :: Libraries :: Python Modules
Entry-points:
  [console_scripts]
  freeze_graph = tensorflow.python.tools.freeze_graph:run_main
  saved_model_cli = tensorflow.python.tools.saved_model_cli:main
  tensorboard = tensorboard.main:run_main
  toco = tensorflow.contrib.lite.toco.python.toco_wrapper:main
  toco_from_protos = tensorflow.contrib.lite.toco.python.toco_from_protos:main
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`
From that I understand that for python 2 everything should be correctly installed, shouldn't it?

**Comment by maksym33** [comment]
Hi,
So this is the pip2 output:
```
pip2 show tensorflow tensorflow-gpu tf-nightly tensorflow-h
ub
Name: tensorflow
Version: 1.8.0
Summary: TensorFlow helps the tensors flow
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: astor, protobuf, gast, tensorboard, six, wheel, absl-py, backports.weakref, termcolor, enum34, numpy, grpcio, mock
Required-by: 
---
Name: tensorflow-gpu
Version: 1.3.0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/maks/.local/lib/python2.7/site-packages
Requires: protobuf, six, tensorflow-tensorboard, wheel, backports.weakref, numpy, mock
Required-by: 
---
Name: tensorflow-hub
Version: 0.1.0
Summary: TensorFlow Hub is a library to foster the publication, discovery, and consumption of reusable parts of machine learning models.
Home-page: https://github.com/tensorflow/hub
Author: Google LLC
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: protobuf, numpy, six
Required-by:`
```
and pip3 output:
```
`pip3 show tensorflow tensorflow-gpu tf-nightly tensorflow-hub
---
Metadata-Version: 2.0
Name: tensorflow
Version: 1.8.0
Summary: TensorFlow helps the tensors flow
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
Installer: pip
License: Apache 2.0
Location: /home/maks/.local/lib/python3.5/site-packages
Requires: termcolor, grpcio, absl-py, wheel, gast, astor, numpy, six, protobuf, tensorboard
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  Intended Audience :: Education
  Intended Audience :: Science/Research
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
  Topic :: Scientific/Engineering
  Topic :: Scientific/Engineering :: Mathematics
  Topic :: Scientific/Engineering :: Artificial Intelligence
  Topic :: Software Development
  Topic :: Software Development :: Libraries
  Topic :: Software Development :: Libraries :: Python Modules
Entry-points:
  [console_scripts]
  freeze_graph = tensorflow.python.tools.freeze_graph:run_main
  saved_model_cli = tensorflow.python.tools.saved_model_cli:main
  tensorboard = tensorboard.main:run_main
  toco = tensorflow.contrib.lite.toco.python.toco_wrapper:main
  toco_from_protos = tensorflow.contrib.lite.toco.python.toco_from_protos:main
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
From that I understand that for python 2 everything should be correctly installed, shouldn't it?

**Comment by vbardiovskyg** [comment]
The problem is that `import tensorflow` is importing tensorflow_gpu. If you have both tensorflow and tensorflow_gpu pip packages, which one will be imported by `import tensorflow` is undefined.

The correct way to fix it would be:
1) decide whether to keep tensorflow or tensorflow_gpu, so for example tensorflow_gpu
2) `pip2 uninstall tensorflow`
3) `pip2 install tensorflow_gpu`

**Comment by maksym33** [comment]
Ok, but I still get the 
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(tf.estimator.Exporter)
AttributeError: 'module' object has no attribute 'Exporter'
```
error, after I have uninstalled the tensorflow. Is there any way to make it run with the gpu accelerated version?

**Comment by sriram-ramanathan** [comment]
Latest version solved the issue.
