### ISSUE TITLE
graph.pb.h missing

### ISSUE THREAD

**Issue by SanderDalm** [tensorflow/tensorflow#1890]
The issue is quite simple: I downloaded and built TF from source, but the include files like tensorflow/core/public/session.h reference non-existing files. One culprit is tensorflow/core/framework/graph.pb.h. Attempted compilation produces the following error:

22:31:27 **** Build of configuration Debug for project hello_world ****
make all 
make: Warning: File `objects.mk' has modification time 1,8e+02 s in the future
Building file: ../src/hello_world.cpp
Invoking: GCC C++ Compiler
g++ -I/home/sander/tensorflow -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/hello_world.d" -MT"src/hello_world.d" -o "src/hello_world.o" "../src/hello_world.cpp"
In file included from ../src/hello_world.cpp:8:0:
/home/sander/tensorflow/tensorflow/core/public/session.h:22:48: fatal error: tensorflow/core/framework/graph.pb.h: No such file or directory
 #include "tensorflow/core/framework/graph.pb.h"
                                                ^
compilation terminated.

I cannot rule out a mistake on my part, but I've tried a bunch of things to no avail. Either a file is missing or there may be a linking issue. Any help would be greatly appreciated.

### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 
None

If installed from binary pip package, provide:

1. Which pip package you installed.
I followed these steps:

1 git clone --recurse-submodules https://github.com/tensorflow/tensorflow

2 run ./configure

3 bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

4 bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

5 pip install /tmp/tensorflow_pkg/tensorflow-0.7.1-py2-none-linux_x86_64.whl

2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.7.1

If installed from sources, provide the commit hash:
not sure, retrieved on 11 april from terminal:
$ git clone --recurse-submodules https://github.com/tensorflow/tensorflow

### Steps to reproduce
1. The error occurs simply when any file from TF is included in c++
example:
#include "tensorflow/core/public/session.h"

### What have you tried?
1. Reinstall/upgrade: pip, bazel, tensorflow, gcc/g++, add additional include paths

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by mrry** [comment]
`tensorflow/core/framework/graph.pb.h` is a generated file: it should be produced in the `bazel-genfiles/tensorflow/core/framework` directory when you build TensorFlow using Bazel.

Building from source without using Bazel is not fully supported right now, but you could try adding `-I/home/sander/tensorflow/bazel-genfiles` to your `g++` arguments (assuming you have previously build TF from source).

**Comment by SanderDalm** [comment]
Thank you for your answer. In genfiles I finally found the missing file. Should I add genfiles to my include paths?

**Comment by mrry** [comment]
That should work, although the recommend workflow is still to use Bazel for building C++ targets (since it takes care of these issues).

**Comment by SanderDalm** [comment]
Ah, but the thing is, I did use bazel to build it. I used the bazel commands as shown on the TF installation page. I wonder if something else is wrong...

**Comment by mrry** [comment]
I mean that it would be easier to build your own program `hello_world.cpp` using Bazel as well. From your error message it looks like you are using `make all` to build it, which is unsupported, but you might be able to set up your include path appropriately.

**Comment by SanderDalm** [comment]
Wow, I finally get my mistake. I built TF using bazel, but then tried to build my program in Eclipse. Thanks a lot! 

As a last little question, do you know any link/tutorial on building your own project in bazel?

**Comment by mrry** [comment]
Ah, that makes sense! The [Bazel C++ tutorial](http://bazel.io/docs/cpp.html) covers all of the concepts that you need to know, although for simple projects you might get just as far by copying the rule for one of the TensorFlow C++ binaries ([e.g.](https://github.com/tensorflow/tensorflow/blob/cf1659d1c233f8ddbee13fd298464d76e58bdccb/tensorflow/cc/BUILD#L61)).

**Comment by HossamAmer12** [comment]
@SanderDalm After you created the bazel-gen files, what did you do for your application to build? Did you add the bazel-gen files in your include path? Did it work after that?

I have a C++ project that contains several subfolders of *.h and *.cpp files. I think that creating a BUILD file for such a project will not be the fastest way to solve the issue.
@mrry

**Comment by YorksonChang** [comment]
@SanderDalm @HossamAmer12 
I have the same question ,too.
I use Bazel build to create a libtensorflow.so
then I add it in the lib path
but it dose not work.

**Comment by HossamAmer12** [comment]
This is a simple Neural Network I created using C++ Tensorflow. I also created a makefile for compiling the source code via (g++); I think that this makefile will be helpful for you to understand how to build the code.
[simpleNetwork.zip](https://github.com/tensorflow/tensorflow/files/943262/simpleNetwork.zip)

Best of luck and let me know if you have more questions!

PS: I extended the following tutorial: [[https://medium.com/jim-fleming/loading-a-tensorflow-graph-with-the-c-api-4caaff88463f]]

**Comment by lababidi** [comment]
@HossamAmer12 Thank you for sharing your project. There's a key step I'm failing to accomplish. When I run your code (or my code) the header files are not found. How do you resolve this?

**Comment by lababidi** [comment]
Thanks to @HossamAmer12 for providing a zip of his work, deriving from the Medium article example, I have the follow:

First, after installing `protobuf` and `eigen`:
```
./configure
bazel build  //tensorflow:libtensorflow_cc.so
```

Then Copy the following include headers and dynamic shared library to `/usr/local/lib` and `/usr/local/include`:
```
mkdir /usr/local/include/tf
cp -r bazel-genfiles/ /usr/local/include/tf/
cp -r tensorflow /usr/local/include/tf/
cp -r third_party /usr/local/include/tf/
cp -r bazel-bin/libtensorflow_cc.so /usr/local/lib/
```

Lastly, compile using an example:
```
g++ -std=c++11 -o tLoader -I/usr/local/include/tf -I/usr/local/include/eigen3 -g -Wall -D_DEBUG -Wshadow -Wno-sign-compare -w  -L/usr/local/lib/libtensorflow_cc `pkg-config --cflags --libs protobuf`  -ltensorflow_cc loader.cpp
```

**Comment by HossamAmer12** [comment]
@lababidi Is the issue still open?

**Comment by freesouls** [comment]
@lababidi thanks for your tips, after some efforts, I can run successfully in your way.

**Comment by haiy** [comment]
@lababidi @freesouls  I've followed @lababidi method,but  got the error below.Any suggestion?

```
Undefined symbols for architecture x86_64:
  "tensorflow::internal::CheckOpMessageBuilder::NewString[abi:cxx11]()", referenced from:
      std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* tensorflow::internal::MakeCheckOpString<int, int>(int const&, int const&, char const*) in cc918f4y.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

**Comment by integeruser** [comment]
@haiy I had your same issue trying to compile some examples using `g++-7` from Homebrew. I solved it by using instead the compiler shipped with macOS (i.e. `/usr/bin/g++`) (which was likely used by Bazel for compiling tensorflow).

**Comment by jkravanja** [comment]
@lababidi Hi, thanks for you description of how to use standalone shared library. For me, libtensorflow_so compiled without a problem using bazel, but I have problems with includes, when i try to use it in a separate eclipse project, specifically with eigen3. I tried 2 options. 
1) Add tensorflow's _third_party/eigen3_ to the include path. This causes cyclic include, since _unsupported/Eigen/CXX11/Tensor_ bacisally includes itself in the first line:
` #include "unsupported/Eigen/CXX11/Tensor". `
So this approach does not work.

2) Using system installed /usr/include/eigen3, but in this case the error is:

`tensorflow/core/framework/type_traits.h:69:52: error: ‘half’ is not a member of ‘Eigen’`

I guess there is probably a trivial solution of just correctly configuring the include paths, but so far i have spent a lot of time on this with no luck. Does anybody have any ideas for how to do this correctly?

**Comment by jkravanja** [comment]
@lababidi Hi, thanks for you description of how to use standalone shared library. For me, libtensorflow_so compiled without a problem using bazel, but I have problems with includes, when i try to use it in a separate eclipse project, specifically with eigen3. I tried 2 options. 
1) Add tensorflow's _third_party/eigen3_ to the include path. This causes cyclic include, since _unsupported/Eigen/CXX11/Tensor_ bacisally includes itself in the first line:
` #include "unsupported/Eigen/CXX11/Tensor". `
So this approach does not work.

2) Using system installed /usr/include/eigen3, but in this case the error is:

`tensorflow/core/framework/type_traits.h:69:52: error: ‘half’ is not a member of ‘Eigen’`

I guess there is probably a trivial solution of just correctly configuring the include paths, but so far i have spent a lot of time on this with no luck. Does anybody have any ideas for how to do this correctly?

**Comment by integeruser** [comment]
@jkravanja This is some `bash` code I use to copy the necessary files for compiling a separate project (after having built tensorflow):
```
cp -r $TENSORFLOW_DIR/tensorflow include/third_party
cp -r $TENSORFLOW_DIR/bazel-genfiles/tensorflow include/third_party
cp -r $TENSORFLOW_DIR/bazel-tensorflow/../../external/protobuf/src/google include/third_party
cp -r $TENSORFLOW_DIR/third_party/eigen3 include/third_party
cp -r $TENSORFLOW_DIR/bazel-tensorflow/../../external/eigen_archive/. include/third_party/eigen3
cp -r include/third_party/eigen3/Eigen include/third_party
```
where `TENSORFLOW_DIR` is the directory where you cloned the tensorflow repository (for example `/opt/tensorflow`), and `include/third_party` is the directory to include when compiling your project (`-I include/third_party`). This script probably copies a lot more files than the strictly necessary, but it works for me.

**Comment by jkravanja** [comment]
Thanks that works, but i have to add both include paths, include/third_party and also include/, since some headers include from "third_party/..."

**Comment by 9thDimension** [comment]
@integeruser @jkravanja 

I am having the same problem `tensorflow/core/framework/type_traits.h:69:52: error: ‘half’ is not a member of ‘Eigen’`.

I tried running all those copy commands, but it gets stuck at:

`$TENSORFLOW_DIR/bazel-tensorflow/../../external/protobuf/src/google': No such file or directory`.

**Comment by jkravanja** [comment]
Probably you can try copying 
`cp -r $TENSORFLOW_DIR/bazel-tensorflow/external/protobuf/src/google include/third_party`

**Comment by bobeo** [comment]
@9thDimension @jkravanja I have a lot of undefined errors. Any idea? I did compile libtensorflow_cc.so successfully.

**Comment by jkravanja** [comment]
@bobeo undefined errors or undefined rference erros? Probably it is a linker error, you are missing some libraries. Can you copy paste it here?

**Comment by bobeo** [comment]
@jkravanja undefined reference errors:
```

/tmp/ccEdGM3i.o: In function `LoadGraph(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unique_ptr<tensorflow::Session, std::default_delete<tensorflow::Session> >*)':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:44: undefined reference to `tensorflow::GraphDef::GraphDef()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:46: undefined reference to `tensorflow::Env::Default()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:46: undefined reference to `tensorflow::ReadBinaryProto(tensorflow::Env*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::MessageLite*)'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:51: undefined reference to `tensorflow::SessionOptions::SessionOptions()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:51: undefined reference to `tensorflow::NewSession(tensorflow::SessionOptions const&)'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:44: undefined reference to `tensorflow::GraphDef::~GraphDef()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:44: undefined reference to `tensorflow::GraphDef::~GraphDef()'
/tmp/ccEdGM3i.o: In function `main':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:71: undefined reference to `tensorflow::SessionOptions::SessionOptions()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:71: undefined reference to `tensorflow::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**)'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:73: undefined reference to `tensorflow::Status::ToString[abi:cxx11]() const'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:81: undefined reference to `tensorflow::GraphDef::GraphDef()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:84: undefined reference to `tensorflow::Env::Default()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:84: undefined reference to `tensorflow::ReadBinaryProto(tensorflow::Env*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::MessageLite*)'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:86: undefined reference to `tensorflow::Status::ToString[abi:cxx11]() const'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:93: undefined reference to `tensorflow::Status::ToString[abi:cxx11]() const'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:105: undefined reference to `tensorflow::Tensor::Tensor(tensorflow::DataType, tensorflow::TensorShape const&)'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:144: undefined reference to `tensorflow::Status::ToString[abi:cxx11]() const'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:156: undefined reference to `tensorflow::Tensor::DebugString[abi:cxx11]() const'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:127: undefined reference to `tensorflow::Tensor::~Tensor()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:81: undefined reference to `tensorflow::GraphDef::~GraphDef()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:105: undefined reference to `tensorflow::Tensor::~Tensor()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/loader.cpp:81: undefined reference to `tensorflow::GraphDef::~GraphDef()'
/tmp/ccEdGM3i.o: In function `tensorflow::Status::operator=(tensorflow::Status const&)':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/lib/core/status.h:106: undefined reference to `tensorflow::Status::SlowCopyFrom(tensorflow::Status::State const*)'
/tmp/ccEdGM3i.o: In function `tensorflow::TensorShapeRep::TensorShapeRep(tensorflow::TensorShapeRep const&)':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/framework/tensor_shape.h:477: undefined reference to `tensorflow::TensorShapeRep::SlowCopyFrom(tensorflow::TensorShapeRep const&)'
/tmp/ccEdGM3i.o: In function `tensorflow::TensorShapeRep::~TensorShapeRep()':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/framework/tensor_shape.h:492: undefined reference to `tensorflow::TensorShapeRep::DestructorOutOfLine()'
/tmp/ccEdGM3i.o: In function `tensorflow::core::RefCounted::~RefCounted()':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/lib/core/refcount.h:79: undefined reference to `tensorflow::internal::LogMessageFatal::LogMessageFatal(char const*, int)'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/lib/core/refcount.h:79: undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
/tmp/ccEdGM3i.o: In function `tensorflow::core::RefCounted::Ref() const':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/lib/core/refcount.h:82: undefined reference to `tensorflow::internal::LogMessageFatal::LogMessageFatal(char const*, int)'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/lib/core/refcount.h:82: undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/lib/core/refcount.h:82: undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
/tmp/ccEdGM3i.o: In function `tensorflow::TensorShape::TensorShape(std::initializer_list<long long>)':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/framework/tensor_shape.h:273: undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase(std::initializer_list<long long>)'
/tmp/ccEdGM3i.o: In function `tensorflow::SessionOptions::~SessionOptions()':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/public/session_options.h:28: undefined reference to `tensorflow::ConfigProto::~ConfigProto()'
/tmp/ccEdGM3i.o: In function `std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tensorflow::Tensor>::~pair()':
/usr/include/c++/5/bits/stl_pair.h:96: undefined reference to `tensorflow::Tensor::~Tensor()'
/tmp/ccEdGM3i.o: In function `tensorflow::Status tensorflow::errors::NotFound<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*>(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*)':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/lib/core/errors.h:73: undefined reference to `tensorflow::strings::StrCat[abi:cxx11](tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&)'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/lib/core/errors.h:73: undefined reference to `tensorflow::Status::Status(tensorflow::error::Code, tensorflow::StringPiece)'
/tmp/ccEdGM3i.o: In function `tensorflow::TTypes<float, 2ul, long>::Tensor tensorflow::Tensor::tensor<float, 2ul>()':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/framework/tensor.h:535: undefined reference to `tensorflow::Tensor::CheckTypeAndIsAligned(tensorflow::DataType) const'
/tmp/ccEdGM3i.o: In function `tensorflow::TTypes<float, 1, long>::Scalar tensorflow::Tensor::scalar<float>()':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/framework/tensor.h:643: undefined reference to `tensorflow::Tensor::CheckIsAlignedAndSingleElement() const'
/tmp/ccEdGM3i.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* tensorflow::internal::MakeCheckOpString<long, int>(long const&, int const&, char const*)':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/platform/default/logging.h:184: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::CheckOpMessageBuilder(char const*)'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/platform/default/logging.h:186: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::ForVar2()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/platform/default/logging.h:187: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::NewString[abi:cxx11]()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/platform/default/logging.h:184: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/platform/default/logging.h:184: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
/tmp/ccEdGM3i.o: In function `Eigen::DSizes<long, 2> tensorflow::TensorShape::AsEigenDSizes<2>() const':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/framework/tensor_shape.h:445: undefined reference to `tensorflow::TensorShape::CheckDimsEqual(int) const'
/tmp/ccEdGM3i.o: In function `Eigen::DSizes<long, 2> tensorflow::TensorShape::AsEigenDSizesWithPadding<2>() const':
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/framework/tensor_shape.h:452: undefined reference to `tensorflow::TensorShape::CheckDimsAtLeast(int) const'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/framework/tensor_shape.h:455: undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::dims() const'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/framework/tensor_shape.h:456: undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::dim_size(int) const'
/home/sensen/Downloads/simpleNetwork/simpleNetwork/include/third_party/tensorflow/core/framework/tensor_shape.h:458: undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::dims() const'
/tmp/ccEdGM3i.o: In function `void std::_Destroy<tensorflow::Tensor>(tensorflow::Tensor*)':
/usr/include/c++/5/bits/stl_construct.h:93: undefined reference to `tensorflow::Tensor::~Tensor()'
collect2: error: ld returned 1 exit status
```

**Comment by jkravanja** [comment]
Do you link against libtensorflow_cc.so? You should use a linkflag when you compile your program, -ltensorflow_cc

**Comment by bobeo** [comment]
@jkravanja yes i did

`g++ -std=c++11 -o tLoader -Iinclude/third_party -Iinclude -g -Wall -D_DEBUG -Wshadow -Wno-sign-compare -w  -L/home/sensen/workspace/nhatvo/tensorflow/bazel-bin/tensorflow/ `pkg-config --cflags --libs protobuf` -ltensorflow_cc loader.cpp`

**Comment by bobeo** [comment]
@jkravanja all good now when I run this instead : 

g++ -std=c++11 -o tLoader loader.cpp -Iinclude/third_party -Iinclude -g -Wall -D_DEBUG -Wshadow -Wno-sign-compare -w  -L/home/sensen/workspace/nhatvo/tensorflow/bazel-bin/tensorflow/ -ltensorflow_cc `pkg-config --cflags --libs protobuf`

**Comment by sidhunileshwar13894** [comment]
Sir i created a trained model using Tensorflow Inception. I use the Flower data set.
But i cant find .pb file anywhere....

The codes are specified below...


FLOWERS_DATA_DIR=/tmp/flowers-data/

cd tensorflow-models/inception
bazel build //inception:download_and_preprocess_flowers

bazel-bin/inception/download_and_preprocess_flowers "${FLOWERS_DATA_DIR}"



Now the .tfr file created sucessfully.

INCEPTION_MODEL_DIR=$HOME/inception-v3-model
mkdir -p ${INCEPTION_MODEL_DIR}
cd ${INCEPTION_MODEL_DIR}

curl -O http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz
tar xzf inception-v3-2016-03-01.tar.gz


# this will create a directory called inception-v3 which contains the following files.
> ls inception-v3
README.txt
checkpoint
model.ckpt-157585



cd tensorflow-models/inception
bazel build //inception:flowers_train

# Path to the downloaded Inception-v3 model.
MODEL_PATH="${INCEPTION_MODEL_DIR}/inception-v3/model.ckpt-157585"

# Directory where the flowers data resides.


FLOWERS_DATA_DIR=/tmp/flowers-data/

# Directory where to save the checkpoint and events files.


TRAIN_DIR=/tmp/flowers_train/

# Run the fine-tuning on the flowers data set starting from the pre-trained
# Imagenet-v3 model.


bazel-bin/inception/flowers_train \
  --train_dir="${TRAIN_DIR}" \
  --data_dir="${FLOWERS_DATA_DIR}" \
  --pretrained_model_checkpoint_path="${MODEL_PATH}" \
  --fine_tune=True \
  --initial_learning_rate=0.001 \
  --input_queue_memory_factor=1








Please help me..

**Comment by drabaioli** [comment]
The comments in here are precious!!!
After all of this effort, isn't it possible to have an official tensorflow_cc-dev package? isn't it possible to have a more official way of compiling tensorflow based c++ project out of the source tree? It feels like a very important feature to me!

**Comment by carol-hsu** [comment]
This instruction also save my time
http://www.blitzblit.com/2017/06/11/creating-tensorflow-c-headers-and-libraries/

**Comment by xiupingmath** [comment]
@lababidi Hi, I did the following according to you tips,
mkdir /usr/local/include/tf
cp -r bazel-genfiles/ /usr/local/include/tf/
cp -r tensorflow /usr/local/include/tf/
cp -r third_party /usr/local/include/tf/
cp -r bazel-bin/libtensorflow_cc.so /usr/local/lib/

and make

g++ -std=c++11 -o tLoader -I/usr/local/include/tf -I/usr/local/include/eigen3 -g -Wall -D_DEBUG -Wshadow -Wno-sign-compare -w  -L/usr/local/lib/libtensorflow_cc `pkg-config --cflags --libs protobuf`  -ltensorflow_cc loader.cpp

however, I met an error,

/usr/local/include/tf/tensorflow/core/framework/numeric_types.h:60:34: error: ‘log’ is not a template function 
/usr/local/include/tf/tensorflow/core/framework/numeric_types.h:66:34: error: ‘exp’ is not a template function    
/usr/local/include/tf/tensorflow/core/framework/numeric_types.h:72:34: error: ‘abs’ is not a template function

any suggestions?Thanks
