### ISSUE TITLE
About newlly added eager_operation.h

### ISSUE THREAD

**Issue by jackyko1991** [tensorflow/tensorflow#18925]
In the latest Eager core update, I see that eager_operation is moved to [tensorflow/core/common_runtime/eager](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/common_runtime/eager). However this file require c_api as one of the dependency.

The c_api is suppose to be built after cpu_core_lib is generated, I am now a bit confuse as I am trying to rewrite the CMake files in order to fit the new eager structure.

Any hel?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Skydes** [comment]
I face this issue as well (Ubuntu 14, latest master head). My current workaround is to disable the build of `transform_graph`, `summarize_graph`, `compare_graphs` and `benchmark_model` (see [here](https://github.com/Skydes/tensorflow_catkin/blob/updated-build/patches/fix_eager_link.patch)).

**Comment by drpngx** [comment]
@akshaym could you look into this and if our dependency graph is healthy?
