### ISSUE TITLE
Problem with shape inference with diag_part operator. 

### ISSUE THREAD

**Issue by alexggmatthews** [tensorflow/tensorflow#1893]
Running` from master the following small code snippet gives an error.

```
import tensorflow as tf
import numpy as np

W = tf.constant(3., tf.float64)
X = tf.placeholder(tf.float64, [5,3])
Y = tf.scalar_mul( W , tf.ones(tf.pack([tf.shape(X)[0], tf.shape(X)[0]]), tf.float64) )
Z = tf.diag_part(Y)

init = tf.initialize_all_variables()

sess = tf.Session()
sess.run(init)
print(sess.run(Z, feed_dict={X: np.ones((5,3))}))
```

The relevant part of the error is 

> /tensorflow/python/ops/array_ops.py", line 960, in _DiagPartShape
>     " do not match ")
> ValueError: Invalid shape, shape[:mid] \(?,\) and shape[mid:] \(?,\) do not match 
> 

I think it is reasonable to be able to get the diagonal of this matrix. Therefore I think this is a bug with the shape inference. 

Thanks,
Alex

**Comment by yaroslavvb** [comment]
Simpler example

shape = tf.placeholder(tf.int32, shape=(2))
a = tf.ones(shape)
sess = tf.Session()
sess.run(tf.diag_part(a+1), feed_dict={shape:(1,1)})

ValueError: Invalid shape, shape[:mid] (?,) and shape[mid:] (?,) do not match

**Comment by alexggmatthews** [comment]
@yaroslavvb That looks like a bug then. I'd be interested in a work around if anyone finds one.

**Comment by rmlarsen** [comment]
A fix has been submitted.
