### ISSUE TITLE
Missing types in C++ API

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#1894]
It looks like there are some missing types in tensorflow/core/framework/types.h, such as uint32 and uint64. This means I can't make tensors of these types in C++.

**Comment by aakashpatel25** [comment]
Hi, I can work on this. Starting with the open source for the first time. Can I get more details regarding the issue. Thanks.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
