### ISSUE TITLE
Please clarify the documentation on eager execution and available host language functionalities

### ISSUE THREAD

**Issue by micdestefano** [tensorflow/tensorflow#18960]
The documentation on eager execution [here](https://www.tensorflow.org/programmers_guide/eager), particularly for the "fizzbuzz" example, does not reflect what tensorflow does. Specifically, all the comparisons num % x == y  do not work as the reader is expecting them to. According to me, it is not true that "all the functionality of the host language is available" because in order to make that code work I need to convert all the comparisons into num.numpy() % x == y (I have enabled eager execution).

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by maisamwasti** [comment]
This is true. I have observed the similar pattern. Apparently it needs to be x.numpy().

**Comment by micdestefano** [comment]
Answering to "tensorflowbutler".

Actually, because this is an issue with tensorflow documentation, if tensorflow developers had taken the time to run the "fizzbuzz" code as it is reported into the tensorflow documentation, at the link I have provided, which points to tensorflow web site, the issue would have come out.

Trying to fill out the relevant information:
Have I written custom code: No. I cut and pasted the code on the tensorflow documentation.
OS Platform and Distribution: It happens both on Windows 10 (tensorflow 1.8, downloaded with pip) and on Linux (built from sources).
TensorFlow installed from: on Windows, through pip. On Linux, from source.
TensorFlow version 1.7 and 1.8
Bazel version: NA
CUDA/cuDNN version: No CUDA. I am not using GPU.
GPU model and memory: Not using GPU
Exact command to reproduce: try to run the code you report on your documentation (see above).

**Comment by jsnowacki** [comment]
+1 Also you can just cast it to e.g. int: `int(num % x) == y`. Though, the bare FizzBuzz doesn't work as given in the example. BTW same behavior on GPU version, so it is unrelated (as expected really).

**Comment by alextp** [comment]
When I ran the fizzbuzz example in the programmer's guide on tf 1.7.0 as `fizzbuzz(10)` it worked; it only failed when run as `fizzbuzz(tf.constant(10))`. I'm updating the docs to make it work in both cases, thanks for the heads up.
