### ISSUE TITLE
Is the expected_shape argument of tf.Variable still useable/useful?

### ISSUE THREAD

**Issue by yunhailuo** [tensorflow/tensorflow#18990]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
Installed with Anaconda
- **TensorFlow version (use command below)**:
b'v1.8.0-0-g93bc2e2072' 1.8.0
- **Python version**: 
3.6.5

I know this might be a small docs fix which doesn't fit the issue policy. But I'm not sure and I don't really know how to fix it. I'm sorry. But it seems that the `expected_shape` argument of `tf.Variable` has been deprecated for a long time (since v1.0.0). Is it still useable/useful? Is there a reason [it is still in the documentation](https://www.tensorflow.org/api_docs/python/tf/Variable#__init__)?

https://github.com/tensorflow/tensorflow/blob/8753e2ebde6c58b56675cc19ab7ff83072824a62/tensorflow/python/ops/variables.py#L284

**Comment by yaroslavvb** [comment]
It's not yet deprecated in the latest released version, which is what docs point to
https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/python/ops/variables.py

The code you point to is from master, so this change will make its way to official docs once it's part of a release

**Comment by yunhailuo** [comment]
@yaroslavvb Thank you for confirming the deprecation. It's really helpful in clarifying a few confusing problems.

If I understand the code correctly, the constructor of `tf.Variable` pretty much passes everything, including `expected_shape`, to the protected method `_init_from_args`, which has deprecated `expected_shape` in the code (line 298 of your link) as well as documenting it as deprecated (line 284 of your link). I do understand it is better to use `tf.get_variable` whenever it's possible. However, it can be confusing when people actually use `tf.Variable`, as reported both here, #18653, and on [stackoverflow](https://stackoverflow.com/questions/50103262/tensorflow-tf-variable-initialize-shape-bug). I just want to kindly point it out in case you guys forget about it since this has been the case (doc'ed in `tf.Variable` while actually deprecated in `_init_from_args`) since v1.0.0.

Thank you all again for building and opening this great tool!

**Comment by yunhailuo** [comment]
@yaroslavvb Thanks. I'll close this issue now. 

Just to clarify, it's not yet documented as deprecated in master (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/variables.py#L187-L188) as for now.
