### ISSUE TITLE
[Feature Request] Reuse curl handle in CurlHttpRequest class

### ISSUE THREAD

**Issue by damienpontifex** [tensorflow/tensorflow#19013]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.7.0-3-g024aecf414 1.7.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: 0.12.0-homebrew
- **GCC/Compiler version (if compiling from source)**: Apple LLVM version 9.1.0 (clang-902.0.39.1)
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
In the [libcurl programming tutorial](https://curl.haxx.se/libcurl/c/libcurl-tutorial.html) under the section "Persistence Is The Way to Happiness" it notes that re-cycling the same easy handle can give several benefits. This could lead to performance improvements when using remote filesystems that utilise this class (e.g. gcs file system and I've been working on azure blob storage). Currently it seems that a single instance of the `CurlHttpRequest` and hence curl handle can only be used once and must be instantiated per request.

Is this worth investigating to integrate some sort of 'reset' method to this class along with [curl_easy_reset](https://curl.haxx.se/libcurl/c/curl_easy_reset.html) plus extract defaults set in the constructor into a 'setup defaults' method? Plus some profiling to ensure the change is better?

**Comment by aselle** [comment]
@mrry, could yoou PTAL?

**Comment by mrry** [comment]
I'm no curl expert, but this sounds like a contribution we'd welcome.

**Comment by mskwarek** [comment]
Hi, imho I could handle this issue but im not sure what needs to be done here. It's about make CurlHttpRequest class as singleton?

**Comment by damienpontifex** [comment]
@mskwarek wouldn't need to be a singleton, but a way to reset the state so a subsequent request could be made with the same `tensorflow::CurlHttpRequest` instance (or really curl handle under that instance)

**Comment by egolearner** [comment]
`tensorflow::HttpRequest`, parent class of `CurlHttpRequest` stats that it's not designed to be reused.
```
  /// \brief Sends the formed request.
  ///
  /// If the result buffer was defined, the response will be written there.
  /// The object is not designed to be re-used after Send() is executed.
  virtual Status Send() = 0;

```
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/cloud/http_request.h#L171

**Comment by damienpontifex** [comment]
With most of the io modules that would probably use this moving to tensorflow/io I'll close this here
