### ISSUE TITLE
how many steps that are required to train the model>

### ISSUE THREAD

**Issue by muhammadzulfanazhari** [tensorflow/tensorflow#19012]
I've trained the model for more than 12 hours and it is still training. How many steps that machine needs to complete the process?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by muhammadzulfanazhari** [comment]
Ubuntu 16.04
Tensorflow installed from Virtualenv
Tensorflow 1.7
Bazel 0.12
CUDA/cuDNN 9.0
GPU 1080 Ti

bazel-bin/$examples_dir/cifar10/cifar10_train --pruning_hparams=name=cifar10_pruning,begin_pruning_step=10000,end_pruning_step=100000,target_sparsity=0.9,sparsity_function_begin_step=10000,sparsity_function_end_step=100000

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there. Thanks!
