### ISSUE TITLE
Doesn`t work with Golang version until 1.7

### ISSUE THREAD

**Issue by prostoiChelovek** [tensorflow/tensorflow#19023]
### System information
- OS Platform and Distribution: `Linux Ubuntu 16.04` 
- TensorFlow version: `1.7.0` 
- TensorFlow installed from `binary`
- Have I written custom code: `not`, thats because i can`t install the library
- Bazel version: bazel is `not installed`
- CUDA/cuDNN version: `i have not` CUDA/cuDNN
- GPU model and memory: GPU - `AMD MULLINS (DRM 2.50.0 / 4.13.0-37-generic, LLVM 5.0.0)`, RAM - `6.8 gb`
- Exact command to reproduce: `go get github.com/tensorflow/tensorflow/tensorflow/go`

### Tthe problem
I installed TensorFlow as shown in the [instruction](https://www.tensorflow.org/install/install_go), but with `go get github.com/tensorflow/tensorflow/tensorflow/go` failed:
```
# github.com/tensorflow/tensorflow/tensorflow/go
could not determine kind of name for C. CBytes
```
but it was only in Golang version below 1.7, BUT to use it I can't because I need another library gocv (and other binding OpenCV for Golang) work only in version 1.6. 
### Question
Is there any possibility to use TensorFlow with Golang 1.6?
P.S. [env collect](https://www.dropbox.com/s/vawhuyh1d58a3k6/tf_env.txt?dl=0)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment]
Unfortunately, nope, we don't have the bandwidth to support very old versions of Go.
Currently, we're trying to keep in sync with [the supported releases of Go](https://golang.org/doc/devel/release.html#policy), which at this time corresponds to 1.10 and 1.9. 

If a simple code change makes things work with older versions of Go, without sacrificing compatibility and performance with the supported Go releases, then we'd be happy to accept a pull request. If not, will have to rely on community support.

Thanks! Sorry that I didn't give the answer you were probably hoping for!

**Comment by fardok** [comment]
Its very funny but  Tensorflow libs dont work also with golang 1.10 1.11 1.12 

7 months ago...
Omg
