### ISSUE TITLE
Documentation format mistake

### ISSUE THREAD

**Issue by the0demiurge** [tensorflow/tensorflow#19022]
### Describe the problem

here, the `exeption_mode` ought to be an arg, while Markdown recognizes it as a list member
![image](https://user-images.githubusercontent.com/11363529/39514973-4726e0bc-4e2b-11e8-9cb3-dc70f6273e5e.png)

![image](https://user-images.githubusercontent.com/11363529/39514893-0d7b9ee8-4e2b-11e8-98d6-40acb1171315.png)

api doc address: 
https://www.tensorflow.org/api_docs/python/tf/enable_eager_execution

the problem source code:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L5426

### System information
v1.8.0-0-g93bc2e2072 1.8.0

It's not a problem of my environment, it's a problem of the official api doc

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yongtang** [comment]
Added a PR #19116 as an attempt to fix the doc format issue.
