### ISSUE TITLE
Tensorboard is down after upgrading to the tensorflow 1.8.0

### ISSUE THREAD

**Issue by willSapgreen** [tensorflow/tensorflow#19074]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04

- **TensorFlow installed from (source or binary)**:
binary

- **TensorFlow version (use command below)**:
1.8.0

- **Python version**: 
2.7.12

- **Bazel version (if compiling from source)**:
No

- **GCC/Compiler version (if compiling from source)**:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

- **CUDA/cuDNN version**:
CUDA 9.0
cuDNN 7.0

- **GPU model and memory**:
Nvidia Geforece GTX 1080

- **Exact command to reproduce**:
type 

> sudo pip install tensorboard

and then get

> tensorflow 1.4.1 requires tensorflow-tensorboard<0.5.0,>=0.4.0rc1, which is not installed.

But my tensorflow or tensorflow object detection api works.

### Describe the problem
Cannot install tensorboard from pip.

### Source code / logs
N/A

**Comment by asimshankar** [comment]
Something seems amiss with your installation, since the error message says `tensorflow 1.4.1`, but it seems you're installing 1.8.0?

Can you try upgrading both with:

```sh
pip install --upgrade tensorflow tensorboard
```

**Comment by willSapgreen** [comment]
Hello @asimshankar ,

Sorry for the late response.

when I type `pip install --upgrade tensorflow tensorboard`,

I got the following messages and the same error message:

> Requirement already up-to-date: tensorflow-gpu in /usr/local/lib/python2.7/dist-packages (1.8.0)
Requirement already up-to-date: tensorboard in /usr/local/lib/python2.7/dist-packages (1.8.0)
Requirement not upgraded as not directly required: mock>=2.0.0 in /home/garmin/.local/lib/python2.7/site-packages (from tensorflow-gpu) (2.0.0)
Requirement not upgraded as not directly required: grpcio>=1.8.6 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (1.11.0)
Requirement not upgraded as not directly required: enum34>=1.1.6 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (1.1.6)
Requirement not upgraded as not directly required: numpy>=1.13.3 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (1.14.3)
Requirement not upgraded as not directly required: termcolor>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (1.1.0)
Requirement not upgraded as not directly required: backports.weakref>=1.0rc1 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (1.0.post1)
Requirement not upgraded as not directly required: absl-py>=0.1.6 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (0.2.0)
Requirement not upgraded as not directly required: wheel in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (0.31.0)
Requirement not upgraded as not directly required: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (1.11.0)
Requirement not upgraded as not directly required: gast>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (0.2.0)
Requirement not upgraded as not directly required: protobuf>=3.4.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (3.5.2.post1)
Requirement not upgraded as not directly required: astor>=0.6.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (0.6.2)
Requirement not upgraded as not directly required: bleach==1.5.0 in /usr/local/lib/python2.7/dist-packages (from tensorboard) (1.5.0)
Requirement not upgraded as not directly required: futures>=3.1.1; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from tensorboard) (3.2.0)
Requirement not upgraded as not directly required: html5lib==0.9999999 in /usr/local/lib/python2.7/dist-packages (from tensorboard) (0.9999999)
Requirement not upgraded as not directly required: markdown>=2.6.8 in /usr/local/lib/python2.7/dist-packages (from tensorboard) (2.6.11)
Requirement not upgraded as not directly required: werkzeug>=0.11.10 in /usr/local/lib/python2.7/dist-packages (from tensorboard) (0.14.1)
Requirement not upgraded as not directly required: funcsigs>=1; python_version < "3.3" in /home/garmin/.local/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow-gpu) (1.0.2)
Requirement not upgraded as not directly required: pbr>=0.11 in /usr/local/lib/python2.7/dist-packages (from mock>=2.0.0->tensorflow-gpu) (4.0.2)
Requirement not upgraded as not directly required: setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf>=3.4.0->tensorflow-gpu) (39.1.0)
tensorflow 1.4.1 requires tensorflow-tensorboard<0.5.0,>=0.4.0rc1, which is not installed.

when typing `python -c 'import tensorflow as tf; print(tf.__version__)'`
it shows 1.8.0

Please let me know if any other information you need. Thank you.

**Comment by asimshankar** [comment]
I'm confused about why the error message talks about TensorFlow 1.4.1.
Perhaps you have conflicting installs for tensorflow and tensorflow-gpu?
Could you try `pip list` to see what all you have installed and remove all TensorFlow packages and then reinstall?

**Comment by willSapgreen** [comment]
Hello @asimshankar ,

The 1.4.1 error is because I have tensorflow-gpu 1.8.0 and tensorflow 1.4.1 installed.

After uninstalling tensorflow 1.4.1, the error is gone.

And here is the output after `pip install --upgrade tensorflow-gpu tensorboard`

> Requirement already up-to-date: tensorflow-gpu in /usr/local/lib/python2.7/dist-packages (1.8.0)
Requirement already up-to-date: tensorboard in /usr/local/lib/python2.7/dist-packages (1.8.0)
Requirement not upgraded as not directly required: mock>=2.0.0 in /home/garmin/.local/lib/python2.7/site-packages (from tensorflow-gpu) (2.0.0)
Requirement not upgraded as not directly required: grpcio>=1.8.6 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (1.11.0)
Requirement not upgraded as not directly required: enum34>=1.1.6 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (1.1.6)
Requirement not upgraded as not directly required: numpy>=1.13.3 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (1.14.3)
Requirement not upgraded as not directly required: termcolor>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (1.1.0)
Requirement not upgraded as not directly required: backports.weakref>=1.0rc1 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (1.0.post1)
Requirement not upgraded as not directly required: absl-py>=0.1.6 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (0.2.0)
Requirement not upgraded as not directly required: wheel in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (0.31.0)
Requirement not upgraded as not directly required: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (1.11.0)
Requirement not upgraded as not directly required: gast>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (0.2.0)
Requirement not upgraded as not directly required: protobuf>=3.4.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (3.5.2.post1)
Requirement not upgraded as not directly required: astor>=0.6.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow-gpu) (0.6.2)
Requirement not upgraded as not directly required: bleach==1.5.0 in /usr/local/lib/python2.7/dist-packages (from tensorboard) (1.5.0)
Requirement not upgraded as not directly required: futures>=3.1.1; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from tensorboard) (3.2.0)
Requirement not upgraded as not directly required: html5lib==0.9999999 in /usr/local/lib/python2.7/dist-packages (from tensorboard) (0.9999999)
Requirement not upgraded as not directly required: markdown>=2.6.8 in /usr/local/lib/python2.7/dist-packages (from tensorboard) (2.6.11)
Requirement not upgraded as not directly required: werkzeug>=0.11.10 in /usr/local/lib/python2.7/dist-packages (from tensorboard) (0.14.1)
Requirement not upgraded as not directly required: funcsigs>=1; python_version < "3.3" in /home/garmin/.local/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow-gpu) (1.0.2)
Requirement not upgraded as not directly required: pbr>=0.11 in /usr/local/lib/python2.7/dist-packages (from mock>=2.0.0->tensorflow-gpu) (4.0.2)
Requirement not upgraded as not directly required: setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf>=3.4.0->tensorflow-gpu) (39.1.0)

However,

when trying to use tensorboard, I got 

> tensorboard: command not found

In /usr/local/lib/python2.7/dist-packages

I have 

> tensorboard
tensorboard-1.8.0.dist-info
tensorflow
tensorflow_gpu-1.8.0.dist-info

And I cannot find main.py in tensorboard, like this [discussion feed](https://stackoverflow.com/questions/45095820/tensorboard-command-not-found?rq=1&utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).

Any suggestion?

Thank you for helping!

**Comment by willSapgreen** [comment]
Hello @asimshankar 

After

1. 

> sudo pip uninstall tensorflow-gpu

2. 

> pip install tensorflow-gpu

Both tensorflow and tensorboard work.

Thank you for helping.
