### ISSUE TITLE
[Feature request] SavedModelBuilder collection export

### ISSUE THREAD

**Issue by KineticCookie** [tensorflow/tensorflow#19086]
Hello!
As far as I'm concerned, there is no way to export custom collection with `SavedModelBuilder`.
Current implementation uses `tf_saver.Saver.export_meta_graph ` method with empty `collection_list` parameter.

My suggestion is to add the `collection_list` parameter to the  `SavedModelBuilder.add_meta_graph_and_variables` and `SavedModelBuilder.add_meta_graph` methods. In this way, user can specify custom collections, that could be useful after model import.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by KineticCookie** [comment]
Hmm. So it defaults to all collections. It's weird, because I ran this snipped of code
``` python
a = tf.placeholder(dtype=tf.float32)
b = tf.placeholder(dtype=tf.float32)
s = a + b
sess.graph.add_to_collection("TEAM_AB", a)
sess.graph.add_to_collection("TEAM_AB", b)
builder = tf.saved_model.builder.SavedModelBuilder("./model_other")
builder.add_meta_graph_and_variables(sess, ...)
builder.save(as_text=True)
```
and I couldn't find any of the `collection_def` fields. 

But now I checked it again but in other environment, and it works pretty good! 
```
collection_def {
    key: "TEAM_AB"
    value {
      node_list {
        value: "Placeholder:0"
        value: "Placeholder_1:0"
      }
    }
}
```

Well, that's awkward. I think we could close this FR. Thanks @allenlavoie !
