### ISSUE TITLE
Unrecognized option: --data_dir

### ISSUE THREAD

**Issue by mikeconnors909** [tensorflow/tensorflow#191]
When I try to run the command 
```
bazel run -c opt <...>/models/rnn/translate/translate.py
  --data_dir [your_data_directory]
```
I get the error: 
`Unrecognized option: --data_dir`

Is my syntax wrong?

**Comment by SWu** [comment]
you need to add a '--' after translate.py to distinguish options passed to the python script vs options passed to bazel:
```
bazel run -c opt <...>/models/rnn/translate/translate.py --
  --data_dir [your_data_directory]
```

**Comment by vrv** [comment]
Yeah, bazel run syntax requires `--` to separate.

**Comment by mikeconnors909** [comment]
When I try to run this command:

`bazel run -c opt tensorflow/models/rnn/translate/translate.py -- --   data_dir ../data/translate/`
I get the following error:

```
...................
ERROR: Cannot run target //tensorflow/models/rnn/translate:translate.py: Not   executable.
INFO: Elapsed time: 1.537s
ERROR: Build failed. Not running target.
```

Any ideas how to resolve?

**Comment by ebrevdo** [comment]
Drop the .py from the end of the bazel run command.
