### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Yogiraj-Patil** [tensorflow/tensorflow#19104]
I have install Tensorflow via using this commands:
sudo apt-get install python3-pip python3-dev  :->  this for the 'pip' installation
pip3 install tensorflow   :-> this for a tensorflow installation

I am using ubantu 16.04 64 bit version Configuration as below :-
![screenshot from 2018-05-05 10-30-59](https://user-images.githubusercontent.com/30696388/39659867-076002a2-5050-11e8-8ee3-361881b92e3b.png)

still when as importing the tensorflow in python3 it gives "Illegal instruction (core dumped)" error
as :-1: 
![screenshot from 2018-05-05 10-37-31](https://user-images.githubusercontent.com/30696388/39659879-55f635da-5050-11e8-8fb4-03b0fce0571b.png)

**Comment by ppwwyyxx** [comment]
"Starting from 1.6 release, our prebuilt binaries will use AVX instructions.
This may break TF on older CPUs."
-- from https://github.com/tensorflow/tensorflow/releases?after=v1.6.0

**Comment by AdamMiltonBarker** [comment]
Is there anyway to get around this ? I trained a model on 1.7.0 due to it crashing on my 750ti from memory, but need to run this model on 1.4.0, should of thought about it earlier but any way to avoid an additional 3 days training ?

**Comment by Yogiraj-Patil** [comment]
So is there any other option is available for my CPU for tensorflow

**Comment by ppwwyyxx** [comment]
The options are:
1. Build TF yourself
2. Download third-party binaries built by others, e.g. https://github.com/mind/wheels/releases
3. Use old version TF

**Comment by jart** [comment]
What @ppwwyyxx mentioned is almost certainly the case. If you have an older CPU that doesn't have AVX you can install either an older TensorFlow binary, or you can build TensorFlow from source.
