### ISSUE TITLE
Build Tensorflow C++ Windows with MSVC2013

### ISSUE THREAD

**Issue by Wang-Guanyu** [tensorflow/tensorflow#19126]
I have successfully built Tensorflow C++ Windows with MSVC2015, but currently I am interested in building Tensorflow C++ Windows with MSVC2013. May I know has anybody done this before, or does it doable?

Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jart** [comment]
It's most likely undoable. TensorFlow is written in C++11 and MSVC2013 has [limited support](https://msdn.microsoft.com/en-us/library/hh567368.aspx) for that.
