### ISSUE TITLE
Error converting from tflite to PB

### ISSUE THREAD

**Issue by samsun639** [tensorflow/tensorflow#19123]
bazel run --config=opt   //tensorflow/contrib/lite/toco:toco --   --input_file=/root/tensorflow/tensorflow/mobilenet_v1_1.0_224.tflite   --output_file=/root/tensorflow/tensorflow/tflite_2_pb.pb   --input_format=TFLITE   --output_format=TENSORFLOW_GRAPHDEF   --input_shape=1,224,224,3   --input_array=input   --output_array=MobilenetV1/Predictions/Reshape_1

**It shows below error:** 

INFO: Analysed target //tensorflow/contrib/lite/toco:toco (0 packages loaded).
INFO: Found 1 target...
Target //tensorflow/contrib/lite/toco:toco up-to-date:
  bazel-bin/tensorflow/contrib/lite/toco/toco
INFO: Elapsed time: 0.198s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/tensorflow/contrib/lite/toco/toco '--input_file=/root/tensorflow/tensorflow/mobilenet_v1_1.0_224.tflite' '--output_file=/root/tensorflow/tensorflow/tflite_2_pb.pb' '--input_format=TFLITE' '--output_format=TENSORFLOW_GRAPHDEF' '--input_shape=1,224,224,3' '--input_array=input' '--output_array=MobilenetV1/Predictions/Reshape_1'
2018-05-07 16:07:38.775341: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 31 operators, 89 arrays (0 quantized)
2018-05-07 16:07:38.775647: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 31 operators, 89 arrays (0 quantized)
2018-05-07 16:07:38.775663: F tensorflow/contrib/lite/toco/graph_transformations/propagate_fixed_sizes.cc:48] Check failed: dilation_width_factor >= 1 (0 vs. 1)

**Comment by fengye88** [comment]
@samsun639 I wonder why you closed this issue? I wonder if there's a way to convert from tflite flat buffer model back to pb model.

**Comment by oscarriddle** [comment]
This issue is meaningful.
Developers need to find a way to convert the tflite model to frozen model.

**Comment by milinddeore** [comment]
I too would like to know the same, converting .tflite to frozen model.

**Comment by jithu12** [comment]
Anyone?

**Comment by milinddeore** [comment]
You can analyse TFlite, like operations and subgraph using this nice [tool](https://github.com/PeteBlackerThe3rd/tflite_analyser).

**Comment by leavittx** [comment]
I have more specific question: how do I get .pb for this particular .tflite model? 
https://www.tensorflow.org/lite/models/segmentation/overview
I want to use the same training set as in the pre-trained .tflite model

**Comment by leavittx** [comment]
Regarding the general solution, toco seems not to be working (see [this](https://stackoverflow.com/questions/59924882/using-toco-command-converting-tflite-to-pb-throwing-error-tensorflow-graphdef), the only custom converting script I've found is [this](https://gist.github.com/tworuler/bd7bd4c6cd9a8fbbeb060e7b64cfa008). I think it should be possible to adapt it to other models as well.
