### ISSUE TITLE
build with python3 binary uses wrong path to find Python.h (fix inside)

### ISSUE THREAD

**Issue by akorzh** [tensorflow/tensorflow#19128]
I spent few days fighting issue with building tensorflow where it was unable to find Python.h, and seen number of similar issues.
Python.h was installed as a part of python3-devel, but build system wasnt unable to find it.
Finally i figured out that in tensorflow/third_party/py/python_configure.bzl function _get_python_bin was looking for binary by name python, even once i did configure i told it to use /usr/bin/python3

so i did a workaround by changing python_bin_path=repository_ctx.which("python") to look for python3 instead.

but i guess configure should do that for me.

i had unsupported fedora28 but its not the only distro having both python and python3 binaries

**Comment by yongtang** [comment]
@akorzh I tried building with python3 on Ubuntu 16.04 and the build finished correctly. I have to link `/usr/bin/python3` to `/usr/bin/python` but other than that the build works fine. Could you list the detailed steps and environment (as was suggested in the pull request template) so that the issue could be reproduced?

**Comment by akorzh** [comment]
problem is that python is a python 2.7 binary i dont want to use. python3 is a python 3.6 binary i want to use so when doing configure i answer /usr/bin/python3 is the one i want to use, but aforementioned .bzl function is still using python binary no matter what which leads to build fail

**Comment by akorzh** [comment]
steps are easy : start with default fedora 27 or 28 installation where python is python2 binary and python3 is a python 3.6 binary. This issue is non-relevant to Ubuntu i guess then

**Comment by michaelisard** [comment]
Since Fedora is unsupported I will leave this as community support.

**Comment by tensorflowbutler** [comment]
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by tensorflowbutler** [comment]
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by tensorflowbutler** [comment]
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by mohantym** [comment]
Hi @akorzh ! Python 3.7 is minimum version now. Please check out instructions on [build from source](https://www.tensorflow.org/install/source) document from 2.8/2.9 version  and let us know . Thank you!
