### ISSUE TITLE
Linalg.LinearOperators do not give any performance improvement

### ISSUE THREAD

**Issue by sanket-kamthe** [tensorflow/tensorflow#19145]
### Describe the problem

The performance gaurantees are not visible for the Linalg.LinearOperators (e.g., [DiagOperator](https://www.tensorflow.org/api_docs/python/tf/linalg/LinearOperatorDiag))   I have implemented a basic case below as per the documentation. Is there any reason why the performance of `diag` operator is same as full matrix ? 

Cuda and other versions not included as the issue is reproducible across GPU and CPU modes.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:

Yes, but using only preliminary Linalg operations. 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux xxxx-xxxop 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.4 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

- **TensorFlow installed from (source or binary)**:
Binary

- **TensorFlow version (use command below)**:
== tensorflow import ============================================
tf.VERSION = 1.8.0
tf.GIT_VERSION = v1.8.0-0-g93bc2e2072
tf.COMPILER_VERSION = v1.8.0-0-g93bc2e2072
Sanity check: array([1], dtype=int32)

- **Python version**: 
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 

- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:
Check the source code.

### Source code / logs

```python
import numpy as np
import tensorflow as tf
rng = np.random.RandomState(1)
```
```python
class Data:
    num_data = 10
    num_ind = 50
    D_in = 100
    D_out = 2

    Xmu = rng.randn(num_data, D_in)
    Xcov = rng.randn(num_data, D_in, D_in)
    Xcov = Xcov @ np.transpose(Xcov, (0, 2, 1))
    Z = rng.randn(num_ind, D_in)
```

```python
N = Data.num_data
Xmu = tf.convert_to_tensor(Data.Xmu)
Xcov = tf.convert_to_tensor(Data.Xcov)
```
```python
C = tf.cholesky(Xcov)

Z_tiled = tf.tile(tf.expand_dims(tf.transpose(Data.Z), 0), [N, 1, 1])
```
```python
C_operator = tf.linalg.LinearOperatorLowerTriangular(C)
C_diag_operator = tf.linalg.LinearOperatorDiag(tf.matrix_diag_part(C))
```

```python
def compute_matrix_solve(C, Z_tiled):
#     return tf.matrix_triangular_solve(C, Z_tiled, lower=True)  # NxDxM
    return tf.matrix_solve(C, Z_tiled)  # NxDxM

def compute_matrix_matmul(C, Z_tiled):
    mat = tf.matmul(C, Z_tiled)
    return mat 

def compute_operator_solve(C_operator, Z_tiled):
    operator_value = C_operator.solve(Z_tiled)
    return operator_value

def compute_operator_matmul(C_operator, Z_tiled):
    operator_value = C_operator.matmul(Z_tiled)
    return operator_value
```

```python
with tf.Session() as sess:
    mat_solve = sess.run(compute_matrix_solve(C, Z_tiled))
    op_solve = sess.run(compute_operator_solve(C_operator, Z_tiled))
    
    tf_mat_mul = sess.run(compute_matrix_matmul(C, Z_tiled))
    op_matmul = sess.run(compute_operator_matmul(C_operator, Z_tiled))

np.testing.assert_allclose(mat_solve, op_solve)
np.testing.assert_allclose(tf_mat_mul, op_matmul)
```

```python
with tf.Session() as sess:
    %timeit sess.run(compute_matrix_solve(C, Z_tiled))
    %timeit sess.run(compute_operator_solve(C_operator, Z_tiled))
    %timeit sess.run(compute_operator_solve(C_diag_operator, Z_tiled))
```

    69.1 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
    69.4 ms ± 515 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
    73.7 ms ± 1.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

```python
with tf.Session() as sess:
    %timeit sess.run(compute_matrix_matmul(C, Z_tiled))
    %timeit sess.run(compute_operator_matmul(C_operator, Z_tiled))
    %timeit sess.run(compute_operator_matmul(C_diag_operator, Z_tiled))
    
```

    58.5 ms ± 447 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
    60.8 ms ± 808 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
    63.8 ms ± 1.78 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

**Comment by srvasude** [comment]
Hi,
  One reason for slowness is compute_* adds nodes to the graph. Generally for benchmarking, one should create the graph up front, and then benchmark the sess.runs. The sess.run(...) should also be timed for the underlying op since eval'ing the tensor can include time from the CPU / GPU copies.

What you want in the end is something like:

with tf.Session() as sess:
  msolve = compute_matrix_solve(C, Z_tiled).op
  ....
  def sess_run_msolve():
    return sess.run(msolve)
  print(timeit.timeit(sess_run_msolve, number=100))

Doing the aforementioned changes (and changing D_in to 500 to see the difference for larger matrices), I get on CPU (in seconds):

Matrix Solve 3.94200801849
Operator Solve 2.10899114609
Diag Solve 1.88388705254
Matrix Mul 2.18344807625
Operator Mul 2.28254699707
Diag Mul 1.86973500252

Using https://www.tensorflow.org/api_docs/python/tf/test/Benchmark is also an alternative, which would also do some burn in cycles.

**Comment by sanket-kamthe** [comment]
Thank for your reply. I can confirm that with your suggestions I do see the improvements.
Unfortunately, I have to do this over much lower dimensions and may the gain that case is very marginal.

However, I do like this feature. I will close this issue with results confirming @srvasude  suggestions. 

``` python
with tf.Session(graph=tf.get_default_graph()) as sess:
    msolve = compute_matrix_solve(C, Z_tiled).op
    opsolve = compute_operator_solve(C_operator, Z_tiled)
    diagsolve=compute_operator_solve(C_diag_operator, Z_tiled)
    def sess_run_msolve():
        return sess.run(msolve)
    def sess_run_opsolve():
        return sess.run(opsolve)
    def sess_run_diagsolve():
        return sess.run(diagsolve)
    def burn_in(msolve, opsolve, diagsolve, cycles=100):
        for _ in range(cycles):
            sess.run([msolve, opsolve, diagsolve])
            
            
    burn_in(msolve, opsolve, diagsolve)
    print(timeit.timeit(sess_run_msolve, number=500))
    print(timeit.timeit(sess_run_opsolve, number=500))
    print(timeit.timeit(sess_run_diagsolve, number=500))
```

``` shell
28.759427453987882
15.111607366998214
10.926930371992057

```
