### ISSUE TITLE
Windows 10 GPU JNI Compile Error

### ISSUE THREAD

**Issue by wangxm345566462** [tensorflow/tensorflow#19167]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:Only modified path variables
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 10
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.8 or master ( tried both)
- **Python version**: 3.6.4
- **Bazel version (if compiling from source)**: 0.10.0
- **GCC/Compiler version (if compiling from source)**: 3.6.3
- **CUDA/cuDNN version**: V9.0 / 7.0
- **GPU model and memory**: GTX 1070 6G (Notebook)
- **Exact command to reproduce**:  
msys64 :swigwin-3.0.10
tensorflow/tools/ci_build/windows/libtensorflow_gpu.sh
 

### Describe the problem
I need a GPU version of tensorflow_jni.dll but I did not find that trying to compile with an error.
Compilation is perfectly normal in cpu mode, but errors occur in gpu mode, and every time changes error * .o file

### Source code / logs
ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: not all outputs were created or valid
ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: output 'external/protobuf_archive/_objs/protoc_lib/external/protobuf_archive/src/google/protobuf/compiler/javanano/javanano_enum.o' was not created
ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: output 'external/protobuf_archive/_objs/protoc_lib/external/protobuf_archive/src/google/protobuf/compiler/php/php_generator.o' was not created
ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: output 'external/protobuf_archive/_objs/protoc_lib/external/protobuf_archive/src/google/protobuf/compiler/java/java_message_field_lite.o' was not created
ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: output 'external/protobuf_archive/_objs/protoc_lib/external/protobuf_archive/src/google/protobuf/compiler/javanano/javanano_primitive_field.o' was not created
ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: output 'external/protobuf_archive/_objs/protoc_lib/external/protobuf_archive/src/google/protobuf/compiler/java/java_lazy_message_field.o' was not created
ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: output 'external/protobuf_archive/_objs/protoc_lib/external/protobuf_archive/src/google/protobuf/compiler/cpp/cpp_string_field.o' was not created

### Source code / logs (ALL)
wangxiaoming@MSI MINGW64 /d/projects/tensorflow
$ /d/projects/tensorflow/tensorflow/tools/ci_build/windows/libtensorflow_gpu.sh
+++ dirname /d/projects/tensorflow/tensorflow/tools/ci_build/windows/libtensorflow_gpu.sh
++ cd /d/projects/tensorflow/tensorflow/tools/ci_build/windows
++ pwd
+ SCRIPT_DIR=/d/projects/tensorflow/tensorflow/tools/ci_build/windows
+ source /d/projects/tensorflow/tensorflow/tools/ci_build/windows/bazel/common_env.sh
++ export TMPDIR=C:/tmp
++ TMPDIR=C:/tmp
++ mkdir -p C:/tmp
++ export BAZEL_SH=C:/tools/msys64/usr/bin/bash
++ BAZEL_SH=C:/tools/msys64/usr/bin/bash
++ export PYTHON_BASE_PATH=ProgramData/Anaconda3
++ PYTHON_BASE_PATH=ProgramData/Anaconda3
++ export PYTHON_BIN_PATH=C:/ProgramData/Anaconda3/python.exe
++ PYTHON_BIN_PATH=C:/ProgramData/Anaconda3/python.exe
++ export PYTHON_LIB_PATH=C:/ProgramData/Anaconda3/lib/site-packages
++ PYTHON_LIB_PATH=C:/ProgramData/Anaconda3/lib/site-packages
++ export PATH=/c/ProgramData/Anaconda3:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin
++ PATH=/c/ProgramData/Anaconda3:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin
++ export PATH=/c/ProgramData/Anaconda3/Scripts:/c/ProgramData/Anaconda3:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin
++ PATH=/c/ProgramData/Anaconda3/Scripts:/c/ProgramData/Anaconda3:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin
++ export 'PATH=/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/bin:/c/ProgramData/Anaconda3/Scripts:/c/ProgramData/Anaconda3:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin'
++ PATH='/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/bin:/c/ProgramData/Anaconda3/Scripts:/c/ProgramData/Anaconda3:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin'
++ export 'PATH=/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/extras/CUPTI/libx64:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/bin:/c/ProgramData/Anaconda3/Scripts:/c/ProgramData/Anaconda3:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin'
++ PATH='/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/extras/CUPTI/libx64:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/bin:/c/ProgramData/Anaconda3/Scripts:/c/ProgramData/Anaconda3:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin:/c/ProgramData/chocolatey/bin'
+ source /d/projects/tensorflow/tensorflow/tools/ci_build/windows/bazel/bazel_test_lib.sh
++ failing_cpu_cc_tests='    //tensorflow/core/kernels:control_flow_ops_test +     //tensorflow/core:example_example_parser_configuration_test +     //tensorflow/core:lib_core_status_test +     //tensorflow/core:lib_monitoring_collection_registry_test +     //tensorflow/core:lib_strings_numbers_test +     //tensorflow/core/platform/hadoop:hadoop_file_system_test +     //tensorflow/core:platform_file_system_test +     //tensorflow/core:platform_logging_test +     //tensorflow/core:util_sparse_sparse_tensor_test +     //tensorflow/cc:framework_gradient_checker_test +     //tensorflow/cc:framework_gradients_test +     //tensorflow/cc:gradients_array_grad_test +     //tensorflow/cc:gradients_math_grad_test +     //tensorflow/cc:gradients_nn_grad_test +     //tensorflow/cc/saved_model:loader_test '
++ broken_cpu_cc_tests='    //tensorflow/cc:framework_cc_ops_test +     //tensorflow/core/platform/cloud:time_util_test +     //tensorflow/core/platform/cloud:oauth_client_test +     //tensorflow/core/platform/cloud:http_request_test +     //tensorflow/core/platform/cloud:google_auth_provider_test +     //tensorflow/core/platform/cloud:gcs_file_system_test +     //tensorflow/core/kernels/cloud:bigquery_table_accessor_test +     //tensorflow/core/kernels/hexagon:graph_transferer_test +     //tensorflow/core/kernels:remote_fused_graph_execute_utils_test +     //tensorflow/core/kernels:requantize_op_test +     //tensorflow/core/kernels:requantization_range_op_test +     //tensorflow/core/kernels:quantized_reshape_op_test +     //tensorflow/core/kernels:quantized_pooling_ops_test +     //tensorflow/core/kernels:quantized_matmul_op_test +     //tensorflow/core/kernels:quantized_conv_ops_test +     //tensorflow/core/kernels:quantized_concat_op_test +     //tensorflow/core/kernels:quantized_bias_add_op_test +     //tensorflow/core/kernels:quantized_batch_norm_op_test +     //tensorflow/core/kernels:quantized_activation_ops_test +     //tensorflow/core/kernels:quantize_op_test +     //tensorflow/core/kernels:quantize_down_and_shrink_range_op_test +     //tensorflow/core/kernels:quantize_and_dequantize_op_test_gpu +     //tensorflow/core/kernels:quantize_and_dequantize_op_test +     //tensorflow/core/kernels:quantization_utils_test +     //tensorflow/core/kernels:debug_ops_test +     //tensorflow/core/distributed_runtime/rpc:rpc_rendezvous_mgr_test_gpu +     //tensorflow/core/distributed_runtime/rpc:rpc_rendezvous_mgr_test +     //tensorflow/core/distributed_runtime/rpc:grpc_tensor_coding_test +     //tensorflow/core/distributed_runtime/rpc:grpc_session_test_gpu +     //tensorflow/core/distributed_runtime/rpc:grpc_session_test +     //tensorflow/core/distributed_runtime/rpc:grpc_channel_test_gpu +     //tensorflow/core/distributed_runtime/rpc:grpc_channel_test +     //tensorflow/core/distributed_runtime:remote_device_test_gpu +     //tensorflow/core/distributed_runtime:remote_device_test +     //tensorflow/core/distributed_runtime:executor_test_gpu +     //tensorflow/core/distributed_runtime:executor_test +     //tensorflow/core/debug:debug_gateway_test +     //tensorflow/core/debug:debug_grpc_io_utils_test +     //tensorflow/core:util_reporter_test +     //tensorflow/core:util_memmapped_file_system_test +     //tensorflow/core:platform_subprocess_test +     //tensorflow/core:platform_profile_utils_cpu_utils_test +     //tensorflow/core:lib_jpeg_jpeg_mem_unittest +     //tensorflow/core/debug:debug_io_utils_test '
++ extra_failing_gpu_cc_tests='    //tensorflow/core:lib_core_threadpool_test +     //tensorflow/core:cuda_libdevice_path_test +     //tensorflow/core:common_runtime_direct_session_test +     //tensorflow/core:common_runtime_direct_session_with_tracking_alloc_test +     //tensorflow/core:device_tracer_test +     //tensorflow/core:ops_math_grad_test '
++ exclude_cpu_cc_tests='    //tensorflow/core/kernels:control_flow_ops_test +     //tensorflow/core:example_example_parser_configuration_test +     //tensorflow/core:lib_core_status_test +     //tensorflow/core:lib_monitoring_collection_registry_test +     //tensorflow/core:lib_strings_numbers_test +     //tensorflow/core/platform/hadoop:hadoop_file_system_test +     //tensorflow/core:platform_file_system_test +     //tensorflow/core:platform_logging_test +     //tensorflow/core:util_sparse_sparse_tensor_test +     //tensorflow/cc:framework_gradient_checker_test +     //tensorflow/cc:framework_gradients_test +     //tensorflow/cc:gradients_array_grad_test +     //tensorflow/cc:gradients_math_grad_test +     //tensorflow/cc:gradients_nn_grad_test +     //tensorflow/cc/saved_model:loader_test  +     //tensorflow/cc:framework_cc_ops_test +     //tensorflow/core/platform/cloud:time_util_test +     //tensorflow/core/platform/cloud:oauth_client_test +     //tensorflow/core/platform/cloud:http_request_test +     //tensorflow/core/platform/cloud:google_auth_provider_test +     //tensorflow/core/platform/cloud:gcs_file_system_test +     //tensorflow/core/kernels/cloud:bigquery_table_accessor_test +     //tensorflow/core/kernels/hexagon:graph_transferer_test +     //tensorflow/core/kernels:remote_fused_graph_execute_utils_test +     //tensorflow/core/kernels:requantize_op_test +     //tensorflow/core/kernels:requantization_range_op_test +     //tensorflow/core/kernels:quantized_reshape_op_test +     //tensorflow/core/kernels:quantized_pooling_ops_test +     //tensorflow/core/kernels:quantized_matmul_op_test +     //tensorflow/core/kernels:quantized_conv_ops_test +     //tensorflow/core/kernels:quantized_concat_op_test +     //tensorflow/core/kernels:quantized_bias_add_op_test +     //tensorflow/core/kernels:quantized_batch_norm_op_test +     //tensorflow/core/kernels:quantized_activation_ops_test +     //tensorflow/core/kernels:quantize_op_test +     //tensorflow/core/kernels:quantize_down_and_shrink_range_op_test +     //tensorflow/core/kernels:quantize_and_dequantize_op_test_gpu +     //tensorflow/core/kernels:quantize_and_dequantize_op_test +     //tensorflow/core/kernels:quantization_utils_test +     //tensorflow/core/kernels:debug_ops_test +     //tensorflow/core/distributed_runtime/rpc:rpc_rendezvous_mgr_test_gpu +     //tensorflow/core/distributed_runtime/rpc:rpc_rendezvous_mgr_test +     //tensorflow/core/distributed_runtime/rpc:grpc_tensor_coding_test +     //tensorflow/core/distributed_runtime/rpc:grpc_session_test_gpu +     //tensorflow/core/distributed_runtime/rpc:grpc_session_test +     //tensorflow/core/distributed_runtime/rpc:grpc_channel_test_gpu +     //tensorflow/core/distributed_runtime/rpc:grpc_channel_test +     //tensorflow/core/distributed_runtime:remote_device_test_gpu +     //tensorflow/core/distributed_runtime:remote_device_test +     //tensorflow/core/distributed_runtime:executor_test_gpu +     //tensorflow/core/distributed_runtime:executor_test +     //tensorflow/core/debug:debug_gateway_test +     //tensorflow/core/debug:debug_grpc_io_utils_test +     //tensorflow/core:util_reporter_test +     //tensorflow/core:util_memmapped_file_system_test +     //tensorflow/core:platform_subprocess_test +     //tensorflow/core:platform_profile_utils_cpu_utils_test +     //tensorflow/core:lib_jpeg_jpeg_mem_unittest +     //tensorflow/core/debug:debug_io_utils_test '
++ exclude_gpu_cc_tests='    //tensorflow/core:lib_core_threadpool_test +     //tensorflow/core:cuda_libdevice_path_test +     //tensorflow/core:common_runtime_direct_session_test +     //tensorflow/core:common_runtime_direct_session_with_tracking_alloc_test +     //tensorflow/core:device_tracer_test +     //tensorflow/core:ops_math_grad_test  +     //tensorflow/core/kernels:control_flow_ops_test +     //tensorflow/core:example_example_parser_configuration_test +     //tensorflow/core:lib_core_status_test +     //tensorflow/core:lib_monitoring_collection_registry_test +     //tensorflow/core:lib_strings_numbers_test +     //tensorflow/core/platform/hadoop:hadoop_file_system_test +     //tensorflow/core:platform_file_system_test +     //tensorflow/core:platform_logging_test +     //tensorflow/core:util_sparse_sparse_tensor_test +     //tensorflow/cc:framework_gradient_checker_test +     //tensorflow/cc:framework_gradients_test +     //tensorflow/cc:gradients_array_grad_test +     //tensorflow/cc:gradients_math_grad_test +     //tensorflow/cc:gradients_nn_grad_test +     //tensorflow/cc/saved_model:loader_test  +     //tensorflow/cc:framework_cc_ops_test +     //tensorflow/core/platform/cloud:time_util_test +     //tensorflow/core/platform/cloud:oauth_client_test +     //tensorflow/core/platform/cloud:http_request_test +     //tensorflow/core/platform/cloud:google_auth_provider_test +     //tensorflow/core/platform/cloud:gcs_file_system_test +     //tensorflow/core/kernels/cloud:bigquery_table_accessor_test +     //tensorflow/core/kernels/hexagon:graph_transferer_test +     //tensorflow/core/kernels:remote_fused_graph_execute_utils_test +     //tensorflow/core/kernels:requantize_op_test +     //tensorflow/core/kernels:requantization_range_op_test +     //tensorflow/core/kernels:quantized_reshape_op_test +     //tensorflow/core/kernels:quantized_pooling_ops_test +     //tensorflow/core/kernels:quantized_matmul_op_test +     //tensorflow/core/kernels:quantized_conv_ops_test +     //tensorflow/core/kernels:quantized_concat_op_test +     //tensorflow/core/kernels:quantized_bias_add_op_test +     //tensorflow/core/kernels:quantized_batch_norm_op_test +     //tensorflow/core/kernels:quantized_activation_ops_test +     //tensorflow/core/kernels:quantize_op_test +     //tensorflow/core/kernels:quantize_down_and_shrink_range_op_test +     //tensorflow/core/kernels:quantize_and_dequantize_op_test_gpu +     //tensorflow/core/kernels:quantize_and_dequantize_op_test +     //tensorflow/core/kernels:quantization_utils_test +     //tensorflow/core/kernels:debug_ops_test +     //tensorflow/core/distributed_runtime/rpc:rpc_rendezvous_mgr_test_gpu +     //tensorflow/core/distributed_runtime/rpc:rpc_rendezvous_mgr_test +     //tensorflow/core/distributed_runtime/rpc:grpc_tensor_coding_test +     //tensorflow/core/distributed_runtime/rpc:grpc_session_test_gpu +     //tensorflow/core/distributed_runtime/rpc:grpc_session_test +     //tensorflow/core/distributed_runtime/rpc:grpc_channel_test_gpu +     //tensorflow/core/distributed_runtime/rpc:grpc_channel_test +     //tensorflow/core/distributed_runtime:remote_device_test_gpu +     //tensorflow/core/distributed_runtime:remote_device_test +     //tensorflow/core/distributed_runtime:executor_test_gpu +     //tensorflow/core/distributed_runtime:executor_test +     //tensorflow/core/debug:debug_gateway_test +     //tensorflow/core/debug:debug_grpc_io_utils_test +     //tensorflow/core:util_reporter_test +     //tensorflow/core:util_memmapped_file_system_test +     //tensorflow/core:platform_subprocess_test +     //tensorflow/core:platform_profile_utils_cpu_utils_test +     //tensorflow/core:lib_jpeg_jpeg_mem_unittest +     //tensorflow/core/debug:debug_io_utils_test '
+ cd /d/projects/tensorflow/tensorflow/tools/ci_build/windows/../../../..
+ '[' '!' -e WORKSPACE ']'
+ export TF_BAZEL_TARGETS=//tensorflow:libtensorflow.so
+ TF_BAZEL_TARGETS=//tensorflow:libtensorflow.so
+ export 'TF_BAZEL_TARGETS=//tensorflow:libtensorflow.so //tensorflow/tools/lib_package:clicenses_generate'
+ TF_BAZEL_TARGETS='//tensorflow:libtensorflow.so //tensorflow/tools/lib_package:clicenses_generate'
+ export 'TF_BAZEL_TARGETS=//tensorflow:libtensorflow.so //tensorflow/tools/lib_package:clicenses_generate //tensorflow/java:libtensorflow_jni.so'
+ TF_BAZEL_TARGETS='//tensorflow:libtensorflow.so //tensorflow/tools/lib_package:clicenses_generate //tensorflow/java:libtensorflow_jni.so'
+ export 'TF_BAZEL_TARGETS=//tensorflow:libtensorflow.so //tensorflow/tools/lib_package:clicenses_generate //tensorflow/java:libtensorflow_jni.so //tensorflow/tools/lib_package:jnilicenses_generate'
+ TF_BAZEL_TARGETS='//tensorflow:libtensorflow.so //tensorflow/tools/lib_package:clicenses_generate //tensorflow/java:libtensorflow_jni.so //tensorflow/tools/lib_package:jnilicenses_generate'
+ run_configure_for_gpu_build
+ export TF_NEED_CUDA=1
+ TF_NEED_CUDA=1
+ export TF_CUDA_VERSION=9.0
+ TF_CUDA_VERSION=9.0
+ export 'CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0'
+ CUDA_TOOLKIT_PATH='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0'
+ export TF_CUDNN_VERSION=7.0
+ TF_CUDNN_VERSION=7.0
+ export 'CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0'
+ CUDNN_INSTALL_PATH='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0'
+ export TF_CUDA_COMPUTE_CAPABILITIES=6.1
+ TF_CUDA_COMPUTE_CAPABILITIES=6.1
+ '[' -z '' ']'
+ export TF_ENABLE_XLA=0
+ TF_ENABLE_XLA=0
+ export TF_NEED_VERBS=0
+ TF_NEED_VERBS=0
+ export TF_NEED_MKL=0
+ TF_NEED_MKL=0
+ export TF_NEED_GCP=0
+ TF_NEED_GCP=0
+ export TF_NEED_HDFS=0
+ TF_NEED_HDFS=0
+ export TF_NEED_OPENCL_SYCL=0
+ TF_NEED_OPENCL_SYCL=0
+ export USE_MSVC_WRAPPER=1
+ USE_MSVC_WRAPPER=1
+ echo ''
+ ./configure
WARNING: Running Bazel server needs to be killed, because the startup options are different.
You have bazel 0.10.0 installed.
Invalid python path: C:/ProgramData/Anaconda3/python cannot be found.
Please specify the location of python. [Default is C:\ProgramData\Anaconda3\python.exe]:

Do you wish to build TensorFlow with GDR support? [y/N]: No GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with MPI support? [y/N]: No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
Configuration finished
+ bazel build -c opt --copt=/arch:AVX tensorflow:libtensorflow.so tensorflow/tools/lib_package:clicenses_generate tensorflow/java:libtensorflow_jni.so tensorflow/tools/lib_package:jnilicenses_generate
...................
Loading:
Loading: 0 packages loaded
WARNING: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/WORKSPACE:1: Workspace name in C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions
DEBUG: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:197:9: @//tensorflow/tools/lib_package:libtensorflow_jni: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:197:9: @//tensorflow/tools/lib_package:common_deps: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:197:9: @//tensorflow/tools/lib_package:cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:197:9: @//tensorflow/tools/lib_package:clib: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:197:9: @//tensorflow/tools/lib_package:clicenses: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
Analyzing: 4 targets (6 packages loaded)
Analyzing: 4 targets (42 packages loaded)
Analyzing: 4 targets (55 packages loaded)
Analyzing: 4 targets (59 packages loaded)
Analyzing: 4 targets (66 packages loaded)
WARNING: D:/projects/tensorflow/tensorflow/core/BUILD:1895:1: in includes attribute of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in D:/projects/tensorflow/tensorflow/tensorflow.bzl:1181:30
WARNING: D:/projects/tensorflow/tensorflow/core/BUILD:1895:1: in includes attribute of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in D:/projects/tensorflow/tensorflow/tensorflow.bzl:1181:30
INFO: Analysed 4 targets (70 packages loaded).
INFO: Found 4 targets...
Building: no action
[0 / 24] [-----] BazelWorkspaceStatusAction stable-status.txt
INFO: From Compiling external/protobuf_archive/src/google/protobuf/compiler/java/java_doc_comment.cc [for host]:
▒÷▒: cl [ ѡ▒▒... ] ▒ļ▒▒▒... [ /link ▒▒▒▒ѡ▒▒... ]
▒▒▒▒ x64 ▒▒ Microsoft (R) C/C++ ▒Ż▒▒▒▒▒▒▒ 19.00.24215.1 ▒▒
▒▒Ȩ▒▒▒▒(C) Microsoft Corporation▒▒▒▒▒▒▒▒▒▒Ȩ▒▒▒▒

INFO: From Compiling external/protobuf_archive/src/google/protobuf/compiler/javanano/javanano_enum.cc [for host]:
▒÷▒: cl [ ѡ▒▒... ] ▒ļ▒▒▒... [ /link ▒▒▒▒ѡ▒▒... ]
▒▒▒▒ x64 ▒▒ Microsoft (R) C/C++ ▒Ż▒▒▒▒▒▒▒ 19.00.24215.1 ▒▒
▒▒Ȩ▒▒▒▒(C) Microsoft Corporation▒▒▒▒▒▒▒▒▒▒Ȩ▒▒▒▒

ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: output 'external/protobuf_archive/_objs/protoc_lib/external/protobuf_archive/src/google/protobuf/compiler/java/java_doc_comment.o' was not created
INFO: From Compiling external/protobuf_archive/src/google/protobuf/compiler/java/java_message_field_lite.cc [for host]:
▒÷▒: cl [ ѡ▒▒... ] ▒ļ▒▒▒... [ /link ▒▒▒▒ѡ▒▒... ]
▒▒▒▒ x64 ▒▒ Microsoft (R) C/C++ ▒Ż▒▒▒▒▒▒▒ 19.00.24215.1 ▒▒
▒▒Ȩ▒▒▒▒(C) Microsoft Corporation▒▒▒▒▒▒▒▒▒▒Ȩ▒▒▒▒

ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: not all outputs were created or valid
ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: output 'external/protobuf_archive/_objs/protoc_lib/external/protobuf_archive/src/google/protobuf/compiler/javanano/javanano_enum.o' was not created
ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: output 'external/protobuf_archive/_objs/protoc_lib/external/protobuf_archive/src/google/protobuf/compiler/php/php_generator.o' was not created
ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: output 'external/protobuf_archive/_objs/protoc_lib/external/protobuf_archive/src/google/protobuf/compiler/java/java_message_field_lite.o' was not created
ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: output 'external/protobuf_archive/_objs/protoc_lib/external/protobuf_archive/src/google/protobuf/compiler/javanano/javanano_primitive_field.o' was not created
ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: output 'external/protobuf_archive/_objs/protoc_lib/external/protobuf_archive/src/google/protobuf/compiler/java/java_lazy_message_field.o' was not created
ERROR: C:/tmp/_bazel_wangxiaoming/g7crfchu/external/protobuf_archive/BUILD:277:1: output 'external/protobuf_archive/_objs/protoc_lib/external/protobuf_archive/src/google/protobuf/compiler/cpp/cpp_string_field.o' was not created
INFO: Elapsed time: 11.237s, Critical Path: 0.46s
FAILED: Build did NOT complete successfully

**Comment by wangxm345566462** [comment]
Clean up the build file and restart the build successfully

**Comment by Neiko2002** [comment]
@wangxm345566462 Can you share the compiled jni files?
