### ISSUE TITLE
pandas_input_fn taking a DataFrame or dict of Series for y

### ISSUE THREAD

**Issue by nrstott** [tensorflow/tensorflow#19182]
# Pandas Input Function for Multilabel Inputs

`tf.estimator.inputs.pandas_input_fn` should be able to take a DataFarme or a dict with key to Series for y. This would allow multi-label inputs. This is similar to the numpy_input_fn behavior implemented in issue #12610.

I'd be happy to give the implementation a shot.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by nrstott** [comment]
This is a feature request.

**Comment by asimshankar** [comment]
CC @mrry 
@rachellim - Do you want to take a look at this? Should we be providing a `tf.data.Dataset` path instead/as-well?

**Comment by nrstott** [comment]
Thanks @mrry, will get started on it this evening and see if I can make some progress.

**Comment by nrstott** [comment]
@mrry I opened a pull request. Will a reviewer be automatically assigned? Is there any further action I need to take?

**Comment by mrry** [comment]
@nrstott Thanks for the PR! I've requested a review from someone who's most familiar with that part of the code (and Pandas).

**Comment by wt-huang** [comment]
Closing as this is resolved
