### ISSUE TITLE
tf.image.crop_and_resize() return a wrong  values on the Jetson TX2

### ISSUE THREAD

**Issue by Yightwing** [tensorflow/tensorflow#19184]
same as https://github.com/tensorflow/tensorflow/issues/13890
And I have tried tensorflow 1.4.0 , tensorflow 1.4.1 ,tensorflow 1.7 , all of them got a wrong value,and when I use cpu to calculate it ，it returns a right value .

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
