### ISSUE TITLE
Arrow format for Tensor import/export for cross-platform usage

### ISSUE THREAD

**Issue by rpatra** [tensorflow/tensorflow#19181]
This is regarding a feature request in Tensorflow.
Is there any support currently (or will be in the future) for Tensor porting using [Apache Arrow](https://arrow.apache.org/) for cross-platform usage (e.g., Spark-Tensorflow) in python/java?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by robieta** [comment]
Hi. I would suggest asking this question on [tensorflow/ecosystem](https://github.com/tensorflow/ecosystem). Thanks for your interest.
