### ISSUE TITLE
Support for "Prod" on GPU

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#1919]
As brought up on [so](http://stackoverflow.com/questions/35724469/where-can-i-have-a-look-at-tensorflow-gradient-descent-main-loop/35728022#35728022), Prod on GPU is only registered for float/double but not int inputs

This happens when computing gradient of network with tf.mean() because tf.gradients inserts a "Prod" node with integer inputs.

We already have support on GPU for Prod for float/double, could it be as simple as adding an extra registration clause to [reduction_ops_prod.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/reduction_ops_prod.cc#L37)?

**Comment by yaroslavvb** [comment]
Nope, that one-liner doesn't work....need someone who knows Eigen?

void tensorflow::functor::ReduceFunctor<Eigen::GpuDevice, Eigen::internal::ProdReducer<int> >::Reduce<Eigen::TensorMap<Eigen::Tensor<int, 0ul, 1, long>, 1>, Eigen::TensorMap<Eigen::Tensor<int const, 1ul, 1, long>, 1>, Eigen::array<long, 1ul> >(Eigen::GpuDevice const&, Eigen::TensorMap<Eigen::Tensor<int, 0ul, 1, long>, 1>, Eigen::TensorMap<Eigen::Tensor<int const, 1ul, 1, long>, 1>, Eigen::array<long, 1ul> const&, Eigen::internal::ProdReducer<int> const&)

**Comment by yaroslavvb** [comment]
Nope, just adding "REGISTER_GPU_KERNELS(int32);" gives unknown symbol error below. Benoit, any ideas?

void tensorflow::functor::ReduceFunctor<Eigen::GpuDevice, Eigen::internal::ProdReducer<int> >::Reduce<Eigen::TensorMap<Eigen::Tensor<int, 0ul, 1, long>, 1>, Eigen::TensorMap<Eigen::Tensor<int const, 1ul, 1, long>, 1>, Eigen::array<long, 1ul> >(Eigen::GpuDevice const&, Eigen::TensorMap<Eigen::Tensor<int, 0ul, 1, long>, 1>, Eigen::TensorMap<Eigen::Tensor<int const, 1ul, 1, long>, 1>, Eigen::array<long, 1ul> const&, Eigen::internal::ProdReducer<int> const&)

**Comment by yaroslavvb** [comment]
OK, also needed to add a line to core/kernels/reduction_ops_gpu.cu.cc
DEFINE_FOR_ALL_REDUCERS(int32);

should be fixed once Martin/Vijay merges internal changes

**Comment by vrv** [comment]
@yaroslavvb: feel free to do this yourself
