### ISSUE TITLE
rnn_cell not Checkpointable

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorflow#19208]
tf-nightly: 1.8.0.dev20180329 (latest Windows 10 build)

Sample Code:
```python
import tensorflow as tf
import tensorflow.contrib.eager as tfe
from tensorflow.python.training import checkpointable


class MyModel(checkpointable.Checkpointable):

  def __init__(self):
    self.cell = tf.nn.rnn_cell.DropoutWrapper(
        tf.nn.rnn_cell.BasicLSTMCell(10), 0.5)
    self.cell2 = tf.nn.rnn_cell.BasicLSTMCell(10)


model = MyModel()
state = tf.nn.rnn_cell.LSTMStateTuple(
    c=tf.constant([[10] * 10] * 10, dtype=tf.float32),
    h=tf.constant([[10] * 10] * 10, dtype=tf.float32))
model.cell(tf.constant([[10]] * 10, dtype=tf.float32), state)
model.cell2(tf.constant([[10]] * 10, dtype=tf.float32), state)

checkpoint_path = 'modeldir/test/'
checkpoint = tfe.Checkpoint(model=model)
saver = tfe.CheckpointableSaver(checkpoint)

from tensorflow.contrib.eager.python import checkpointable_utils
print(checkpointable_utils._serialize_object_graph(saver._root_checkpointable))

```

Prints:
```
({'model/cell2/kernel/.ATTRIBUTES/VARIABLE_VALUE': <tf.Variable 'basic_lstm_cell_1/kernel:0' shape=(11, 40) dtype=float32_ref>, 'model/cell2/bias/.ATTRIBUTES/VARIABLE_VALUE': <tf.Variable 'basic_lstm_cell_1/bias:0' shape=(40,) dtype=float32_ref>}, nodes {
  children {
    node_id: 1
    local_name: "model"
  }
}
nodes {
  children {
    node_id: 2
    local_name: "cell"
  }
  children {
    node_id: 3
    local_name: "cell2"
  }
}
nodes {
}
nodes {
  children {
    node_id: 4
    local_name: "kernel"
  }
  children {
    node_id: 5
    local_name: "bias"
  }
}
nodes {
  attributes {
    name: "VARIABLE_VALUE"
    full_name: "basic_lstm_cell_1/kernel"
    checkpoint_key: "model/cell2/kernel/.ATTRIBUTES/VARIABLE_VALUE"
  }
}
nodes {
  attributes {
    name: "VARIABLE_VALUE"
    full_name: "basic_lstm_cell_1/bias"
    checkpoint_key: "model/cell2/bias/.ATTRIBUTES/VARIABLE_VALUE"
  }
}
)
```

Expected to contain `bias` and `kernel` for both `cell` and `cell2` but only contains them for the cell without `DropoutWrapper`.

**Comment by sleighsoft** [comment]
@allenlavoie Maybe that is something for you. I am not sure.

**Comment by allenlavoie** [comment]
Thank you for the report! I've sent a fix out for review (and then it'll sync to github and mark this as closed).

For now I'll just have wrappers depend on their cells. It would be nice to have them inherit their cell's dependencies too, so that adding a wrapper around a cell doesn't break an existing checkpoint [contributions welcome :)]. But when adding a wrapper you can add a skip dependency on the cell to get the same effect (or going the other way can add a random Checkpointable object in place of the wrapper).

**Comment by sleighsoft** [comment]
Great to here, can't wait to use it.

**Comment by sleighsoft** [comment]
Now, when trying to print the checkpoint graph with `checkpointable_utils._serialize_object_graph(ckpt, None)` it will throw:
```
/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 196, in name
    return self._name
AttributeError: 'DropoutWrapper' object has no attribute '_name'
```

**Comment by allenlavoie** [comment]
Oh I see, DropoutWrapper isn't calling its parent constructor so get_config() fails. Easy enough to fix. Thank you for the reports!

**Comment by sleighsoft** [comment]
Would this be a valid approach to support lists of variables for checkpointing?
```python
class MyModel(checkpointable.Checkpointable):

  def __init__(self):
    self.variables = [tf.get_variable('var{}'.format(i), []) for i in range(10)]
    for var in self.variables:
      setattr(self, var.name, var)
```

**Comment by allenlavoie** [comment]
Yeah, this is what several of the eager examples do: e.g. https://github.com/tensorflow/tensorflow/blob/d8f9538ab48e3c677aaf532769d29bc29a05b76e/tensorflow/contrib/eager/python/examples/rnn_colorbot/rnn_colorbot.py#L211

It's fine, but we should add checkpointable data structures (which also forward Layers). I'm almost done with an append-only list datastructure. Whether we support regular Python lists is another interesting question (somewhat tricky semantics with restore-on-create, but doable...).

**Comment by sleighsoft** [comment]
Btw. the `checkpoint.save()` also throws the dropout name error.

**Comment by allenlavoie** [comment]
Yep, will add some end-to-end tests for saving wrappers this time.

I'd note on the setattr() issue that using "var.name" as a dependency name is rather fragile. If you make another instance of the object in the same Graph, the name will be different, which means the objects will be checkpoint incompatible (and changes elsewhere in the program that change "var.name" might break checkpoints for this object).

**Comment by sleighsoft** [comment]
Good point, I will change that in my code.

**Comment by sleighsoft** [comment]
Do you have a date for the name fix? I would really like to use checkpoint and this bug puts me on hold.

**Comment by allenlavoie** [comment]
Should be whenever the next push is. In the meantime, the fix is just to add `super(DropoutWrapper, self).__init__()` as the [first line of `DropoutWrapper`'s `__init__`](https://github.com/tensorflow/tensorflow/blob/a9761960e282cdcf0822951dec86372181f0e88e/tensorflow/python/ops/rnn_cell_impl.py#L981). Once it syncs, the change will add that to a few other wrappers and add some unit tests.

**Comment by sleighsoft** [comment]
How can this error occur?
```
load_status.initialize_or_restore(self.session)
  File "/home/lib/python3.5/site-packages/tensorflow/python/training/checkpointable_utils.py", line 677, in initialize_or_restore
    checkpointable_objects = list_objects(self._root_checkpointable)
  File "/home/lib/python3.5/site-packages/tensorflow/python/training/checkpointable_utils.py", line 472, in list_objects
    object_names=object_names)
  File "/home/lib/python3.5/site-packages/tensorflow/python/training/checkpointable_utils.py", line 291, in _serialize_slot_variables
    "A slot variable was re-used as a dependency of a "
NotImplementedError: A slot variable was re-used as a dependency of a Checkpointable object. This is not currently allowed. File a feature request if this limitation bothers you.
```

**Comment by sleighsoft** [comment]
@allenlavoie I have some remarks to the current solution.
When using e.g. `DropoutWrapper` then it is no longer possible to switch between not using it e.g. during `inference` while using it during `training`. There are a lot of implementations currently that are programmed like this that do not work anymore. Same goes for `DeviceWrapper`. There either has to be an updated documentation stating that is important to keep these object wrappers when using checkpointing or a different solution is necessary that skips the wrapper in the dependency tree.

```python
if training:
   cell = DropoutWrapper(cell, prob)
else:
   # leave cell as is
```
This code does not work when doing checkpointing!

**Comment by allenlavoie** [comment]
[Totally agree](https://github.com/tensorflow/tensorflow/issues/19208#issuecomment-388218570), we should do dependency forwarding so that removing a wrapper doesn't break the checkpoint. It's on my list.

Isn't that a bit of an unusual use-case, though? My expectation is that the model is created in an __init__ before training/not training is known, then `training` is passed through to DropoutWrapper's call(). Creating the object conditionally (in call?) seems a bit wasteful, although I guess it doesn't matter so much unless eager execution is enabled.

**Comment by sleighsoft** [comment]
This issue also stemmed from the problem mentioned in one of my previous issues where overriding e.g. an LSTM cell caused checkpointing errors. The problem I see with the wrappers is that sometimes people implement somethings like a wrapper function to apply all kinds of wrappers to a cell and then get that cell from that function. (e.g. https://github.com/tensorflow/nmt/blob/365e7386e6659526f00fa4ad17eefb13d52e3706/nmt/model_helper.py#L427).
They probably did not have the checkpointing API in mind when they programmed this but for me it shows that some misunderstanding can happen when using both APIs (wrapper & checkpointing)

**Comment by allenlavoie** [comment]
In the NMT example, it's still only an issue if the wrappers are changed, right? I guess ideally MultiRNNCell would have the dependencies forwarded from its first child (so you could add a second cell, causing it to wrap in a MultiRNNCell, and still load the first cell from an existing checkpoint).

**Comment by sleighsoft** [comment]
Yes, If you would run inference where training is false it would probably fail to restore because they did not add the DropoutWrapper in that case. I myself would also not want to add the overhead of another wrapper I don‘t even use in the inference training just to make sure checkpointing works. Only objects (BasicLSTMCell) that add something that is worth restoring e.g. Variables should be considered during restoration. All other dependencies (here Wrapper) should not be mandatory during restoration
