### ISSUE TITLE
import tensorflow as tf error

### ISSUE THREAD

**Issue by loboere** [tensorflow/tensorflow#19216]
installed from anaconda using
`pip  install  tensorflow`

OS Platform:
Windows 7 64bit
intel processor
intel hd graphic graphic card
python version 3.6.4

Have I written custom code: No
Bazel version : I don't have
CUDA/cuDNN version : I don't have
GPU model and memory :N\A
Exact command to reproduce : import tensorflow as tf using jupyter

```
(base) C:\Users\david>pip install tensorflow
Collecting tensorflow
  Downloading https://files.pythonhosted.org/packages/f4/88/980d7032b7408fcca5b0
b8d420fcd97919197a9e7acf280ab74fc7db6993/tensorflow-1.8.0-cp36-cp36m-win_amd64.w
hl (34.4MB)
    100% |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 34.4MB 13kB/s
Collecting astor>=0.6.0 (from tensorflow)
  Downloading https://files.pythonhosted.org/packages/b2/91/cc9805f1ff7b49f62013
6b3a7ca26f6a1be2ed424606804b0fbcf499f712/astor-0.6.2-py2.py3-none-any.whl
Collecting gast>=0.2.0 (from tensorflow)
  Downloading https://files.pythonhosted.org/packages/5c/78/ff794fcae2ce8aa6323e
789d1f8b3b7765f601e7702726f430e814822b96/gast-0.2.0.tar.gz
Requirement already satisfied: six>=1.10.0 in c:\programdata\anaconda3\lib\site-
packages (from tensorflow)
Collecting tensorboard<1.9.0,>=1.8.0 (from tensorflow)
  Downloading https://files.pythonhosted.org/packages/59/a6/0ae6092b7542cfedba6b
2a1c9b8dceaf278238c39484f3ba03b03f07803c/tensorboard-1.8.0-py3-none-any.whl (3.1
MB)
    100% |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 3.1MB 682kB/s
Requirement already satisfied: numpy>=1.13.3 in c:\programdata\anaconda3\lib\sit
e-packages (from tensorflow)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2
a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Requirement already satisfied: wheel>=0.26 in c:\programdata\anaconda3\lib\site-
packages (from tensorflow)
Collecting grpcio>=1.8.6 (from tensorflow)
  Downloading https://files.pythonhosted.org/packages/80/7e/d5ee3ef92822b01e3a27
4230200baf2454faae64e3d7f436b093ff771a17/grpcio-1.11.0-cp36-cp36m-win_amd64.whl
(1.4MB)
    100% |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 1.4MB 787kB/s
Collecting protobuf>=3.4.0 (from tensorflow)
  Downloading https://files.pythonhosted.org/packages/32/cf/6945106da76db9b62d11
b429aa4e062817523bb587018374c77f4b63200e/protobuf-3.5.2.post1-cp36-cp36m-win_amd
64.whl (958kB)
    100% |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 962kB 787kB/s
Collecting absl-py>=0.1.6 (from tensorflow)
  Downloading https://files.pythonhosted.org/packages/90/6b/ba04a9fe6aefa56adafa
6b9e0557b959e423c49950527139cb8651b0480b/absl-py-0.2.0.tar.gz (82kB)
    100% |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 92kB 708kB/s
Collecting bleach==1.5.0 (from tensorboard<1.9.0,>=1.8.0->tensorflow)
  Downloading https://files.pythonhosted.org/packages/33/70/86c5fec937ea4964184d
4d6c4f0b9551564f821e1c3575907639036d9b90/bleach-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: werkzeug>=0.11.10 in c:\programdata\anaconda3\lib
\site-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow)
Collecting markdown>=2.6.8 (from tensorboard<1.9.0,>=1.8.0->tensorflow)
  Downloading https://files.pythonhosted.org/packages/6d/7d/488b90f470b96531a3f5
788cf12a93332f543dbab13c423a5e7ce96a0493/Markdown-2.6.11-py2.py3-none-any.whl (7
8kB)
    100% |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 81kB 682kB/s
Collecting html5lib==0.9999999 (from tensorboard<1.9.0,>=1.8.0->tensorflow)
  Downloading https://files.pythonhosted.org/packages/ae/ae/bcb60402c60932b32dfa
f19bb53870b29eda2cd17551ba5639219fb5ebf9/html5lib-0.9999999.tar.gz (889kB)
    100% |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 890kB 787kB/s
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-p
ackages (from protobuf>=3.4.0->tensorflow)
Building wheels for collected packages: gast, termcolor, absl-py, html5lib
  Running setup.py bdist_wheel for gast ... done
  Stored in directory: C:\Users\david\AppData\Local\pip\Cache\wheels\9a\1f\0e\3c
de98113222b853e98fc0a8e9924480a3e25f1b4008cedb4f
  Running setup.py bdist_wheel for termcolor ... done
  Stored in directory: C:\Users\david\AppData\Local\pip\Cache\wheels\7c\06\54\bc
84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6
  Running setup.py bdist_wheel for absl-py ... done
  Stored in directory: C:\Users\david\AppData\Local\pip\Cache\wheels\23\35\1d\48
c0a173ca38690dd8dfccfa47ffc750db48f8989ed898455c
  Running setup.py bdist_wheel for html5lib ... done
  Stored in directory: C:\Users\david\AppData\Local\pip\Cache\wheels\50\ae\f9\d2
b189788efcf61d1ee0e36045476735c838898eef1cad6e29
Successfully built gast termcolor absl-py html5lib
Installing collected packages: astor, gast, html5lib, bleach, markdown, protobuf
, tensorboard, termcolor, grpcio, absl-py, tensorflow
  Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Found existing installation: bleach 2.1.2
    Uninstalling bleach-2.1.2:
      Successfully uninstalled bleach-2.1.2
Successfully installed absl-py-0.2.0 astor-0.6.2 bleach-1.5.0 gast-0.2.0 grpcio-
1.11.0 html5lib-0.9999999 markdown-2.6.11 protobuf-3.5.2.post1 tensorboard-1.8.0
 tensorflow-1.8.0 termcolor-1.1.0
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.
```

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     13         try:
---> 14             return importlib.import_module(mname)
     15         except ImportError:

C:\ProgramData\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py in module_from_spec(spec)

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap_external.py in create_module(self, spec)

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>()
     16             return importlib.import_module('_pywrap_tensorflow_internal')
---> 17     _pywrap_tensorflow_internal = swig_import_helper()
     18     del swig_import_helper

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     15         except ImportError:
---> 16             return importlib.import_module('_pywrap_tensorflow_internal')
     17     _pywrap_tensorflow_internal = swig_import_helper()

C:\ProgramData\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-306-64156d691fe5> in <module>()
----> 1 import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>()
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 # pylint: disable=wildcard-import
     26 from tensorflow.tools.api.generator.api import *  # pylint: disable=redefined-builtin

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
OS Platform and Distribution
TensorFlow installed from
TensorFlow version

**Comment by jart** [comment]
It's most likely the case that you purchased your Intel CPU before 2012. You have the following options on your existing hardware:

1. Build TF from source.
2. Use a slightly older TF release binary (when we supported k8-sse3+)
3. Install an unofficial binary release created a community member: https://github.com/tensorflow/tensorflow/issues/17386#issuecomment-370129452

**Comment by loboere** [comment]
solve it with this

`pip install tensorflow == 1.5.0`

Thank

**Comment by jubafourali** [comment]
yes, install old version solved this. Thanks @loboere .

**Comment by isahhin** [comment]
Hi, I solved the problem as.

First, I created the conda environment as following:
**_conda create -n myenv  python=3.6
conda activate myenv_** 
Then I installed the keras-gpu=2.2.2 this 
**_conda install keras-gpu=2.2.2_** #this comment also installed the tensorflow

**Comment by karthikcode1** [comment]
I have faced these type of  problems ,
-Like Tensorflow =2.0.0 (latest version )  incompatible   with 3.7 python .
-Like in python 3.7 version tensorflow doesn't work properly so install python 3.6 version or before version.
And working windows 7 version laptops and desktops (manufactured before 2012 or 2013)
Solution  for It.
### command in anacoda prompt
**$ _conda create -n tensorflow_cpu pip python=3.6_**  (to to make a virtual environment in same place with version)
$ **_activate tensorflow_cpu_**   (these command is used to activate the enviroment)
### installation of tensorlflow
pip install --ignore-installed --upgrade tensorflow==1.5.0
.. 

"THESE WILL WORK PROBABLY"  if yes or no comment ..

**Comment by mayurgabhane4** [comment]
> I have faced these type of problems ,
> -Like Tensorflow =2.0.0 (latest version ) incompatible with 3.7 python .
> -Like in python 3.7 version tensorflow doesn't work properly so install python 3.6 version or before version.
> And working windows 7 version laptops and desktops (manufactured before 2012 or 2013)
> Solution for It.
> 
> ### command in anacoda prompt
> **$ _conda create -n tensorflow_cpu pip python=3.6_** (to to make a virtual environment in same place with version)
> $ **_activate tensorflow_cpu_** (these command is used to activate the enviroment)
> 
> ### installation of tensorlflow
> pip install --ignore-installed --upgrade tensorflow==1.5.0
> ..
> 
> "THESE WILL WORK PROBABLY" if yes or no comment ..

this works for me

**Comment by AtilanoBurgos** [comment]
buen día tengo el siguiente error, su ayuda sería de mucha ayuda.
ImportError                               Traceback (most recent call last)
<ipython-input-3-29f498619f5c> in <module>
      4 import keras
      5 import matplotlib.pyplot as plt
----> 6 import tensorflow as tf
      7 from keras import applications
      8 from keras.utils import to_categorical

~\anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     26 
     27 # pylint: disable=g-bad-import-order
---> 28 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     29 from tensorflow.python.tools import module_util as _module_util
     30 

~\anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     81 from tensorflow.python import data
     82 from tensorflow.python import distribute
---> 83 from tensorflow.python import keras
     84 from tensorflow.python.feature_column import feature_column_lib as feature_column
     85 from tensorflow.python.layers import layers

~\anaconda3\lib\site-packages\tensorflow\python\keras\__init__.py in <module>
     25 
     26 from tensorflow.python.keras import activations
---> 27 from tensorflow.python.keras import applications
     28 from tensorflow.python.keras import backend
     29 from tensorflow.python.keras import callbacks

~\anaconda3\lib\site-packages\tensorflow\python\keras\applications\__init__.py in <module>
     24 from tensorflow.python.keras import backend
     25 from tensorflow.python.keras import engine
---> 26 from tensorflow.python.keras import layers
     27 from tensorflow.python.keras import models
     28 from tensorflow.python.keras import utils

~\anaconda3\lib\site-packages\tensorflow\python\keras\layers\__init__.py in <module>
     27 
     28 # Advanced activations.
---> 29 from tensorflow.python.keras.layers.advanced_activations import LeakyReLU
     30 from tensorflow.python.keras.layers.advanced_activations import PReLU
     31 from tensorflow.python.keras.layers.advanced_activations import ELU

~\anaconda3\lib\site-packages\tensorflow\python\keras\layers\advanced_activations.py in <module>
     25 from tensorflow.python.keras.engine.base_layer import Layer
     26 from tensorflow.python.keras.engine.input_spec import InputSpec
---> 27 from tensorflow.python.keras.utils import tf_utils
     28 from tensorflow.python.ops import math_ops
     29 from tensorflow.python.util.tf_export import keras_export

~\anaconda3\lib\site-packages\tensorflow\python\keras\utils\__init__.py in <module>
     37 from tensorflow.python.keras.utils.layer_utils import print_summary
     38 from tensorflow.python.keras.utils.losses_utils import squeeze_or_expand_dimensions
---> 39 from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model
     40 from tensorflow.python.keras.utils.np_utils import normalize
     41 from tensorflow.python.keras.utils.np_utils import to_categorical

~\anaconda3\lib\site-packages\tensorflow\python\keras\utils\multi_gpu_utils.py in <module>
     20 from tensorflow.python.framework import ops
     21 from tensorflow.python.keras import backend as K
---> 22 from tensorflow.python.keras.engine.training import Model
     23 from tensorflow.python.ops import array_ops
     24 from tensorflow.python.util.tf_export import keras_export

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in <module>
     38 from tensorflow.python.keras import optimizers
     39 from tensorflow.python.keras.distribute import distributed_training_utils
---> 40 from tensorflow.python.keras.engine import network
     41 from tensorflow.python.keras.engine import training_arrays
     42 from tensorflow.python.keras.engine import training_distributed

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py in <module>
     37 from tensorflow.python.keras import backend
     38 from tensorflow.python.keras import callbacks
---> 39 from tensorflow.python.keras import saving
     40 from tensorflow.python.keras.engine import base_layer
     41 from tensorflow.python.keras.engine import base_layer_utils

~\anaconda3\lib\site-packages\tensorflow\python\keras\saving\__init__.py in <module>
     31 from tensorflow.python.keras.saving.save import load_model
     32 from tensorflow.python.keras.saving.save import save_model
---> 33 from tensorflow.python.keras.saving.saved_model import export_saved_model
     34 from tensorflow.python.keras.saving.saved_model import load_from_saved_model
     35 from tensorflow.python.keras.saving.saving_utils import trace_model_call

ImportError: cannot import name 'export_saved_model' from 'tensorflow.python.keras.saving.saved_model' (C:\Users\DANTE\anaconda3\lib\site-packages\tensorflow\python\keras\saving\saved_model\__init__.py)
