### ISSUE TITLE
Misleading "cupti.h" error message

### ISSUE THREAD

**Issue by grindhold** [tensorflow/tensorflow#19223]
i am trying to build tensorflow 1.7.1 with cuda support on debian.
While doing so, i received the error message
```
Cuda Configuration Error: Cannot find cupti.h under /usr/lib/cuda
```
i symlinked cupti.h to the written location, even copied it there but nothing happened. after reading the buildscript ```third_party/gpus/cuda_configure.bzl```, it became clear that the script did actually not search for cupti.h in ```/usr/lib/cuda/``` but in two subfolders below that one. This error message is disleading and should display the actual path that bazel uses to look up the files.

**Comment by yongtang** [comment]
Added PR #19224 for the fix.

**Comment by grindhold** [comment]
wow that was quick :) very much appreciated. thx
