### ISSUE TITLE
TensorBoard issue on Mac (0.8.0rc0)

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorflow#1923]
### Environment info
Operating System: Mac OS X
Using virtualenv

Installed version of CUDA and cuDNN: None
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
sudo pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.8.0rc0-py2-none-any.whl

2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.8.0rc0

If installed from sources, provide the commit hash:

### Steps to reproduce
1. git clone --recurse-submodule https://github.com/tensorflow/tensorflow.git
2. cd tensorflow
3. git checkout r0.8
4. python tensorflow/examples/tutorials/mnist/mnist_with_summaries.py --summaries_dir=/tmp/summaries_1
5. tensorboard --logdir /tmp/summaries_1
6. Open http://127.0.0.1:6006 in Chrome

Notice that the CSS don't load properly. The graphs and charts don't show either. 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
If accessed from non-localhost, tensorboard prints messages like the following in console:

WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/Users/cais/venv1/lib/python2.7/site-packages/tensorflow/tensorboard/___rPc_sWiTcH___' on path /Users/cais/venv1/lib/python2.7/site-packages/tensorflow/tensorboard/___rPc_sWiTcH___
10.1.2.3 - - [13/Apr/2016 12:28:20] code 404, message Not Found

**Comment by cavedweller** [comment]
I can confirm the issue. This was very confusing, I was sure I was logging incorrectly. I downgraded to 0.7 and Tensorboard functioned beautifully.

4.2.5-1-ARCH
0.8.0rc0
tried in Firefox
Installed using pip

**Comment by danmane** [comment]
Should be fixed by https://github.com/tensorflow/tensorflow/pull/1926 (ty for confirmation from cavedweller)
