### ISSUE TITLE
opencv imported after tensorflow can't read jpeg

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#1924]
### Environment info
Operating System: Ubuntu 14.04. 

If installed from sources, provide the commit hash: f952246b17562

### Steps to reproduce
```bash
$ python2 -c "import tensorflow; import cv2; print cv2.imread('cat.jpg')"
None
```

### What have you tried?
import cv2 before tensorflow works.

This problem also exists on CentOS 7. It doesn't happen on a latest ArchLinux.
It's likely due to that tensorflow has it's own libjpeg that conflicts with opencv on some platforms.

**Comment by mrry** [comment]
@keveman: Could this be related to the build configuration or the `dlopen()` flags that we're using to support `tf.load_op_library()` and friends? Perhaps there's some way we could structure the libraries so that `import cv2` doesn't link against TensorFlow's internal `libjpeg` or `libpng`?

**Comment by beniz** [comment]
It is much more than just jpeg. I've been hit by this problem for weeks now, and investigating a bit further, I have a snippet of C++ code below that helps reproducing the weird behavior:

```C++
#include <iostream>
//#include "tensorflow/core/public/session.h"                                                                   
#include "tensorflow/core/platform/env.h"
//#include "tensorflow/core/framework/tensor.h"                                                                 
#include <fstream>

#include <opencv2/opencv.hpp>
#include <opencv2/imgproc/imgproc.hpp>

int main(int argc, char** argv)
{
  // Loading the file path provided in the arg into a mat objects                                               
  std::string path = argv[1];
  cv::Mat readImage = cv::imread(path);
  std::cerr << "read image size" << readImage.size() << std::endl;
}
```
Compile and execute
```
./opencv_tensor grace_hopper.jpg
```
yields
```
read image size[517 x 606]
```

Now uncomment either `tensorflow/core/public/session.h` or `tensorflow/core/framework/tensor.h`, compile and execute:
```
read image size[0 x 0]
```

A few notes:
- this uses OpenCV 2.x
- this also occurs with some but not all `png` images
- I've tried to trace the problem back, and one of my current leading hypotheses is related to the `allocator.h` header of TF, as I see a possibility that the `Allocate` functions may be interfering with OpenCV allocator.

@keveman I'm open to any lead I could help testing, typically if you know how I could investigate the `dlopen` lead you are mentioning, I'm your jack of all trade on this one!

**Comment by keveman** [comment]
@beniz, thanks for offering to help. What is the command line you are using for compiling your opencv_tensor binary? I doubt that the problem involving `dlopen` and the one you are facing are the same, but you never know.

**Comment by beniz** [comment]
@keveman thanks for the quick answer, see below, adapted to reflect any custom path:

```
/usr/bin/c++   -g -Wall -Wextra -fopenmp -fPIC -I/path/to/include \
-I/path/to/tensorflow/dbuild/external/eigen_archive/eigen-eigen-4c94692de3e5 \
-I/path/to/tensorflow/dbuild/external/eigen_archive -I/path/to/tensorflow/dbuild/tensorflow \
-I/path/to/tensorflow/bazel-out/local_linux-fastbuild/genfiles/ -std=c++11 -O2 opencv_tensor.cc  \
-o opencv_tensor  -L/path/to/lib -L/path/to/tensorflow/dbuild/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow \
-rdynamic -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lboost_system \
-lcrypto -lssl -ltensorflow \
-Wl,-rpath,/path/to/tensorflow/dbuild/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow
```

`opencv_tensor.cc` is the code shared in previous message. I'm pretty puzzled by this one.

**Comment by keveman** [comment]
Do you mind switching around the order of the libraries? i.e., have the -ltensorflow at the beginning as follows : 

    /usr/bin/c++   -g -Wall -Wextra -fopenmp -fPIC -I/path/to/include \
    -I/path/to/tensorflow/dbuild/external/eigen_archive/eigen-eigen-4c94692de3e5 \
    -I/path/to/tensorflow/dbuild/external/eigen_archive -I/path/to/tensorflow/dbuild/tensorflow \
    -I/path/to/tensorflow/bazel-out/local_linux-fastbuild/genfiles/ -std=c++11 -O2 opencv_tensor.cc  \
    -o opencv_tensor  \
    -ltensorflow \
    -Wl,-rpath,/path/to/tensorflow/dbuild/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow \
    -L/path/to/lib -L/path/to/tensorflow/dbuild/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow \
    -rdynamic -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lboost_system \
    -lcrypto -lssl

**Comment by beniz** [comment]
I had try something related, and tried yours (copied, pasted & fixed), tried several variations, but it doesn't work on my side. Am I right to infer that this is working for you ?

**Comment by MasazI** [comment]
I have same problem. 
Environment: 
Ubuntu14.04
Tensorflow0.8
Opencv3.0, 2.4.11

**Comment by mmuneebs** [comment]
Having same problem on recent nightly build of Tensorflow with GPU:
```
...
    img = skimage.io.imread(path)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_io.py", line 100, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_plugins/pil_plugin.py", line 52, in imread
    raise ValueError('Could not load "%s"\nPlease see documentation at: %s' % (fname, site))
ValueError: Could not load "cat.jpg"
Please see documentation at: http://pillow.readthedocs.org/en/latest/installation.html#external-libraries
```
The weird thing here is that this same code works on my Python IDE 'Spyder', but not from the bash command-line.
Alternatively, reversing the import order of tf/skimage solves the issue.
Additionally, Spyder has trouble finding skimage.io and skimage.transform unless I explicitly import them instead of just `import skimage`; whereas the command-line has no problem finding the submodules from `skimage`. This is not a problem but might explain a part of the differences between CL and IDE. Note: In Spyder I use a regular python interpreter, not IPython.

**Comment by dong-matroid** [comment]
@beniz not sure @keveman's patch fix the c++ issue you and @MasazI had. I just met the same issue while adding cv2 to tensorflow serving. Basically cv::imdecode always return empty image. Have you figured out a way to solve it?

**Comment by beniz** [comment]
@dong-matroid we couldn't solve it, but it's been worked around into our `tf` branch by using the built-in image reading routines, see https://github.com/beniz/deepdetect/blob/tf/src/tfinputconns.h#L239

**Comment by dong-matroid** [comment]
@beniz Thanks for the workaround, make sense for images. I am also adding video clip decoding as a second step, will try ffmpeg library to see if the conflict with tensorflow goes away.

**Comment by ilaripih** [comment]
Has anyone managed to solve the C++ issue, or work around it so that OpenCV's `cv::imdecode` could still be used? Is dynamic linking to `libtensorflow.so` the way to go? I'd even be happy with a solution that completely removed JPEG and PNG reading abilities from TensorFlow as I don't need them.

**Comment by ilaripih** [comment]
Turns out that the C++ conflict between OpenCV and Tensorflow can be solved by using the same `tf_version_script.lds` with `libtensorflow.so` that was added in this commit: https://github.com/qbx2/tensorflow/commit/f2f9322db34d0d500bff2d7ac812c2daf53d4d79

I'm happy now.

**Comment by beniz** [comment]
@ilaripih good to know, can you give more details on what the script does and how to use this properly ?

**Comment by ilaripih** [comment]
@beniz the linker script defines what symbols in `libtensorflow.so` will be exported: in this case it exports symbols that match the pattern `*tensorflow*` and keeps everything else (eg. everything from `libpng` and `libjpeg`) internal.

I think all you need to do is add this to the `libtensorflow.so` Bazel rule:
`linkopts = [ "-Wl,--version-script=tensorflow/tf_version_script.lds" ],`
Then rebuild `libtensorflow.so`.

**Comment by hit-suit** [comment]
put "import pylab"  before "import tensorflow as tf" and it may help
so, the code likes this

`
import pylab
import tensorflow as tf

blabla....
`

**Comment by Ape** [comment]
@ilaripih If I use that `linkopts` and rebuild, it seems that the produced `libtensorflow.so` doens't contain the C API functions. I get "undefined reference" for `TF_NewSession`, `TF_ExtendGraph` etc. Is there a way to include the C API to the library, but still filter out `libjpeg` etc.?

**Comment by ilaripih** [comment]
@Ape If you need to export symbols not covered by `*tensorflow*`, you can add them to the version script's `global` section, eg.: `*tensorflow*; *TF_*;`

**Comment by chenbiaolong** [comment]
@ilaripih It seems that the latest [tensorflow.bzl](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl) is the same as the [qbx2@f2f9322 ](https://github.com/qbx2/tensorflow/commit/f2f9322db34d0d500bff2d7ac812c2daf53d4d79) you just comment. But I still can't use the opencv(c++) read images. 
Here is my BUILD:
```
cc_binary(
name = 'opencv_test',
srcs = ["loader.cc"],
linkopts = ["-lopencv_core","-lopencv_imgproc", "-lopencv_highgui"],
copts = ["-I/usr/include/"],
deps = [
  "//tensorflow/cc:cc_ops",
  "//tensorflow/core:framework_internal",
  "//tensorflow/core:tensorflow",
]
)
```
Did I miss something?Can you give an example of using the `opencv` and `tensorflow` simultaneous? Any advice would be grateful.

**Comment by ilaripih** [comment]
@chenbiaolong My solution was to to build `libtensorflow.so` with the version script that only exports the `*tensorflow*` symbols, and link to it dynamically from my project. You seem to be using static linkage to some tensorflow modules, which won't work.

I only used Bazel to build `libtensorflow.so`, but for building my own project I found that it was a lot easier to just use a traditional Makefile.

**Comment by chenbiaolong** [comment]
@ilaripih Thank you for your reply.I try to use your solution to build my project.But when I try to compile the project, a lot of include errors occur.I had include the `.../tensorflow` and `.../bazel-genfiles/tensorflow`,but some errors like`atal error: eigen-eigenb4fa9622b809/unsupported/Eigen/CXX11/Tensor: No such file or directory` occur.what headers should I include when compile the projects?Thinks.

**Comment by ilaripih** [comment]
@chenbiaolong  Ah yes, the headers are all over the place. I made a shell script that can copy all the needed headers into a single location: https://gist.github.com/ilaripih/928ec17298859f168eee8d12cf796ee8

The script assumes that you have cloned and built tensorflow at `/tensorflow`, and can be run like this to copy the headers to `/tf_headers`:

`sh bundle_tf_headers.sh /tf_headers`

Then you can simply add `/tf_headers/` and `/tf_headers/third_party/eigen3/` as include paths to the linker.

The script probably only works with tensorflow 0.9

**Comment by chenbiaolong** [comment]
@ilaripih great useful script. I am able to build the project.But I still can't use opencv read image... Maybe I made some mistakes I did't find out yet.It seems that if I include some `tensorflow` header and link the `libtensorflow_cc.so`, `cv::imread` will fail to read images(just return an empty `Mat`).The `opencv` 's other functions seem work well.For now, I use `tensorflow` decode the image, and convert the `Tensor` to `cv::Mat` and then use `opencv`.

**Comment by ilaripih** [comment]
@chenbiaolong What does your `cc_binary` section for `libtensorflow_cc.so` look like? Did you add the version script to the linkopts?

**Comment by chenbiaolong** [comment]
@ilaripih 
```
# -------------------------------------------
# New rules should be added above this target.
# -------------------------------------------
cc_binary(
    name = "libtensorflow.so",
    linkshared = 1,
    copts = ["-Wl, --version-script=tensorflow/tf_version_script.lds"],
    deps = [
        "//tensorflow/core:tensorflow",
    ],
)

cc_binary(
    name = "libtensorflow_cc.so",
    linkshared = 1,
    copts = ["-Wl, --version-script=tensorflow/tf_version_script.lds"],
    deps = [
        "//tensorflow/cc:cc_ops",
        "//tensorflow/core:tensorflow",
    ],
)
```
I use `copts ` instead of `linkopts` because when I use `linkopts` I got an error `gcc: error: unrecognized command line option '--version-script=tensorflow/tf_version_script.lds'`
I `bazal clean` before build the `tensorflow.so`,but still no make any different.

**Comment by ilaripih** [comment]
@chenbiaolong `copts` is only used when compiling; you need to use the linker script with the linker so it really needs to be in `linkopts`. Maybe you can't have a space between `-Wl,` and `--version-script...`

**Comment by chenbiaolong** [comment]
@ilaripih wow,finally solve my problem! you are right, I should delete the space between `Wl` and `--version-script` .A stupid mistake... Thank you for your patience.

**Comment by Ape** [comment]
I no longer need this workaround with TensorFlow 1.0.0-rc0 and OpenCV 3.1.0. So the bug has finally been fixed.

**Comment by RoboEvangelist** [comment]
Where is the entire code? How did you include the OpenCV libraries to your code? Thanks,

**Comment by Thomas-Kim** [comment]
The resolution to this issue only fixes libtensorflow.so, the same issue is still present in libtensorflow_cc.so

The fix is a single line, the diff is below:
```
diff --git a/tensorflow/BUILD b/tensorflow/BUILD
index a162bcf..b2f9474 100644
--- a/tensorflow/BUILD
+++ b/tensorflow/BUILD
@@ -466,6 +466,7 @@ cc_binary(

 cc_binary(
     name = "libtensorflow_cc.so",
+    linkopts = [ "-Wl,--version-script=tensorflow/tf_version_script.lds" ],
     linkshared = 1,
     deps = [
         "//tensorflow/c:c_api",
```

**Comment by dave-andersen** [comment]
@Thomas-Kim @meldron - I've pushed a fix to this that should be going out within 24 hours.  LMK.  (Also, as a side note, next time go ahead and open a new bug or re-open it;  I only noticed this because Thomas pinged me about it.)

**Comment by ssriramana93** [comment]
Hi I am a newbie and I'm using tensorflow 1.0 , and I am facing this error. Is this issue fixed in latest version 1.3? If I upgrade to 1.3 will everything work? Thanks

**Comment by Thomas-Kim** [comment]
I am not sure whether upgrading to 1.3 will fix the issue, but upgrading to the tip of master should fix the issue.

**Comment by meldron** [comment]
@ssriramana93 with 1.3 you still got the problem, but you can easily fix the problem.

Just add https://github.com/tensorflow/tensorflow/blob/master/tensorflow/BUILD#L641 this line and the next to the build rule.

**Comment by Thomas-Kim** [comment]
This fix supposedly breaks compilation on OSX, it is better to use the fix that dave-andersen submitted unless you don't care about OSX.

**Comment by meldron** [comment]
@Thomas-Kim yeah you are right he probably should just copy the whole build target

```tf_cc_shared_object(
    name = "libtensorflow_cc.so",
    linkopts = select({
        "//tensorflow:darwin": [
            "-Wl,-exported_symbols_list",  # This line must be directly followed by the exported_symbols.lds file
            "//tensorflow:tf_exported_symbols.lds",
        ],
        "//tensorflow:windows": [],
        "//tensorflow:windows_msvc": [],
        "//conditions:default": [
            "-z defs",
            "-s",
            "-Wl,--version-script",  #  This line must be directly followed by the version_script.lds file
            "//tensorflow:tf_version_script.lds",
        ],
    }),
    deps = [
        "//tensorflow:tf_exported_symbols.lds",
        "//tensorflow:tf_version_script.lds",
        "//tensorflow/c:c_api",
        "//tensorflow/c/eager:c_api",
        "//tensorflow/cc:cc_ops",
        "//tensorflow/cc:client_session",
        "//tensorflow/cc:scope",
        "//tensorflow/core:tensorflow",
    ],
)```

**Comment by Thomas-Kim** [comment]
If my memory serves correctly, @dave-andrsen mentioned that macOS doesn't like the tf_version_script.lds

**Comment by ssriramana93** [comment]
Thank you very much for the replies. I ran "pip3 install tensorflow==1.4.0rc0". When I import it, it says compiled version python3.5 is different from runtime version python3.6. Do I have to downgrade python3.6 to 3.5?

**Comment by subashp** [comment]
I am using the TF 1.4 and linking against C++ code. Below code always says it failed to read the file. I have incorporated above suggestions and it doesnt make any difference. Thoughts/suggestions?
  // ...
  cv::String pathImg = argv[1];
  cv::Mat img = cv::imread(pathImg, CV_LOAD_IMAGE_COLOR | CV_LOAD_IMAGE_ANYDEPTH);
  if (img.empty()) {
    error("Failed to read the file {}", argv[1]);
    return -1;
  }
// ...

**Comment by rmmal** [comment]
@Thomas-Kim , we cloned the latest version of tensorflow and still there is a  problem of reading images using opencv , everytime i initiate a TENSOR object  the opencv doesn't work.

so any suggestions please

**Comment by stereomatchingkiss** [comment]
Have the same issue with tensorflow1.4 and opencv3.3.1

**Comment by bobetocalo** [comment]
I have the same problem using v1.4.0 and opencv 3.3.1 #14267

**Comment by meldron** [comment]
The problem still exists in 1.4.1. The fix for version 1.3 mentioned above no longer works.

**Comment by kxhit** [comment]
I have the same problem using tensorflow r1.4 and opencv3.1 in ubuntu14.04. Anyone could help me?

**Comment by tuanphuc** [comment]
I use tensorflow 1.4.0 and opencv 3.2.0 in ubuntu 16.04. I built libtensorflow_cc.so with bazel. I took the code from @beniz 
```cpp
#include <iostream>
//#include "tensorflow/core/public/session.h"                                                                   
#include "tensorflow/core/platform/env.h"
//#include "tensorflow/core/framework/tensor.h"                                                                 

#include <opencv2/opencv.hpp>
#include <opencv2/imgproc/imgproc.hpp>

int main(int argc, char** argv)
{
  // Loading the file path provided in the arg into a mat objects                                               
  std::string path = argv[1];
  cv::Mat readImage = cv::imread(path);
  std::cerr << "read image size" << readImage.size() << std::endl;
}
```
and then compile it with gcc.

I saw that it can read the image fine with `tensorflow/core/public/session.h` or `tensorflow/core/framework/tensor.h` commented or uncommented. However if I want to show the image with `cv::imshow`, the seg fault error comes again. Is there anyone has the same problem ?

**Comment by beniz** [comment]
This is the current fix to the OpenCV jpeg reading problem: https://github.com/tensorflow/tensorflow/issues/14267#issuecomment-351780041

Build with `bazel --config=monolithic`

**Comment by drpngx** [comment]
Continuing discussion from PR to here. @allenlavoie it looks like the [remove RTLD global](https://github.com/tensorflow/tensorflow/commit/5c7f9e316d8c7735308a217310350d416d7498cc) might have broken this.

**Comment by allenlavoie** [comment]
@msarett @drpngx if you need to link against libtensorflow_framework.so and use OpenCV, please use the workaround in https://github.com/tensorflow/tensorflow/issues/14267#issuecomment-351780041. Eventually we'll split out protocol buffers so you won't need to link against libtensorflow_framework.so for protocol buffer symbols.

**Comment by lordadamson** [comment]
Same issue. OpenCV 2.4. Haaalp!

**Comment by lordadamson** [comment]
A workaround I've done is that I loaded the image with an external library (stb_image) and then fed the data to the `cv::Mat` like so:

```c++
#include <opencv2/opencv.hpp>
#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>

std::map<int, int> channels_map = {
	{1, CV_8UC1},
	{3, CV_8UC3},
	{4, CV_8UC4}
};

int width, height, channels;
std::uint8_t* image_data = stbi_load(file_name.c_str(), &width, &height, &channels, 0);
cv::Mat img(height, width, channels_map[channels], image_data); // You must free the image_data yourself
```

Hope that helps.

**Comment by sumit7** [comment]
Is this issue fixed for cmake build root too. Because I would like to use c++ api of tensorflow and include tensorflow as a standalone library in my project?

**Comment by stereomatchingkiss** [comment]
If it haven't fixed, maybe cpp-package of mxnet can ease your pain, you
could use mmdnn to convert models of tensorflow to mxnet.

Sumit Kshirsagar <notifications@github.com> 於 2018年10月12日 週五 下午12:23寫道：

**Comment by allenlavoie** [comment]
The C++ API + OpenCV jpeg issue was fixed by https://github.com/tensorflow/tensorflow/commit/e6570147c4699518af50d2b08190290003d33aa8#diff-a45ad39a8349c3896b6decf56bcbe304 . Is anyone still seeing the issue with a version which includes that change?
