### ISSUE TITLE
In eager model, tfe.Checkpoint does not restore Variables that are not instance properties of tf.keras.Model instance

### ISSUE THREAD

**Issue by hujunxianligong** [tensorflow/tensorflow#19250]
## System information

+ Have I written custom code : Yes
+ OS Platform and Distribution: Win7 X64
+ TensorFlow installed from (source or binary): binary
+ TensorFlow version (use command below): 1.8.0.dev20180329
+ Python version: 3.5
+ Bazel version (if compiling from source): N/A
+ GCC/Compiler version (if compiling from source):N/A
+ CUDA/cuDNN version: N/A
+ GPU model and memory: N/A
+ Exact command to reproduce: N/A 

## Problem

I wrote a Text CNN in eager model:
```python
class TextCnn(tf.keras.Model):
    def __init__(self):
        ......
        self.conv_funcs = [tf.layers.Conv2D(filter_num,
                                            [filter_size, embedding_size],
                                            activation=tf.nn.relu,
                                            name='conv_{}'.format(filter_size))
                           for filter_size, filter_num in filter_size_num_list]

```
I set the list of Conv2D layers as an instance property(self.conv_funcs), and when I restore the model by tfe.Checkpoint, the weights of the Conv2D layers are not restored.

However, I add the following code and the tfe.Checkpoint successfully restore the weights of the Conv2D layers:
```python
        self.conv_2 = self.conv_funcs[0]
        self.conv_3 = self.conv_funcs[1] 
```

Is it a bug that tfe.Checkpoint only restore the weights of instance properties of tf.keras.Model?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hujunxianligong** [comment]
I have updated the post.

**Comment by sleighsoft** [comment]
Checkpoint does not save/restore lists. You have to assign the Convolutions individually to self for now I think. @allenlavoie correct me if I am wrong.

**Comment by asimshankar** [comment]
Yeah, for now we [don't recurse into lists/dictionary members of a `tf.keras.Model`](https://github.com/tensorflow/tensorflow/blob/f8b74d642420dcf2f5cab763b41884a05777ea45/tensorflow/python/keras/_impl/keras/engine/network.py#L344), so you'll have to explicitly assign member variables. Figuring out the right public API is on our [TODO list](https://github.com/tensorflow/tensorflow/blob/f27033fb1212d7031a359c913d0f59e976b14c14/tensorflow/contrib/eager/python/examples/rnn_ptb/rnn_ptb.py#L77)

**Comment by allenlavoie** [comment]
Mutable built-in data structures (lists, dicts) are going to be tricky to support, since we'd need to hook mutations for restore-on-create (monkey patching?). I'm fine with supporting tuples, though, and I will add checkpointable lists and dictionaries to `tf.contrib.checkpoint`.
