### ISSUE TITLE
tf windows dll could you help me

### ISSUE THREAD

**Issue by craigtao** [tensorflow/tensorflow#19261]
I want to use tensorflow on the windows platform. Why is it so hard?

According to the official website's instructions, cmake came out of the vc project, but compiled a bunch of errors

i use tf r1.2 ！ please help me

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by henrysky** [comment]
If you need Tensorflow on windows, someone compiled a bunch of Tensorflow wheels for Windows and they are available here: https://github.com/fo40225/tensorflow-windows-wheel

**Comment by craigtao** [comment]
My development environment：
Have I written custom code     NO
OS Platform and Distribution  Win7
TensorFlow installed from       github
TensorFlow version                 r1.2
Bazel version                           ？
CUDA/cuDNN version             NO   just for cpu   
GPU model and memory         NO
Exact command to reproduce  NO

MSBuild /p:Configuration=Release ALL_BUILD.vcxproj


I follow README.md in \tensorflow-r1.2\tensorflow\contrib\cmake, 
I follow exactly the instructions README.md

Every time the error is different, 
This morning was such an error “-- The Fortran compiler identification is unknown”
The compiler does not continue to run down

yesterday，error is  ftt2d complied failed、sometime，zlib  complied faile，
Sometimes more than one hundred errors
Sometimes more than two hundred errors

**Comment by craigtao** [comment]
@henrysky   thank you so much, I just need tf r1.2, and just for cpp,

**Comment by henrysky** [comment]
He did talk about compiling C++ standalone shared-lib on Windows and he did uploaded one for TF1.8

The discussion: https://github.com/fo40225/tensorflow-windows-wheel/issues/6
The TF1.8 C++ standalone shared-lib: https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.8.0/cpp

**Comment by craigtao** [comment]
@henrysky  
thank you! i just need TF1.2

**Comment by craigtao** [comment]
cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=D:/all_lib/swigwin-3.0.12/swig.exe -DPYTHON_EXECUTABLE=D:/all_lib/Python36/python.exe -DPYTHON_LIBRARIES=D:/all_lib/Python36/libs/python36.lib -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX -Dtensorflow_BUILD_ALL_KERNELS=ON -Dtensorflow_BUILD_CC_EXAMPLE=ON -Dtensorflow_BUILD_PYTHON_BINDINGS=OFF -Dtensorflow_BUILD_PYTHON_TESTS=OFF -Dtensorflow_ENABLE_GRPC_SUPPORT=ON -Dtensorflow_ENABLE_SSL_SUPPORT=OFF -Dtensorflow_ENABLE_GPU=OFF -Dtensorflow_BUILD_CC_TESTS=OFF -Dtensorflow_BUILD_SHARED_LIB=ON


MSBuild /p:Configuration=Release ALL_BUILD.vcxproj




“D:\all_lib\tensorflow-r1.2\tensorflow\contrib\cmake\build\_beam_search_ops.vcxproj”(默认目标) (1) ->
“D:\all_lib\tensorflow-r1.2\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj”(默认目标) (3) ->
(Link 目标) ->
  tf_session_helper.obj : error LNK2019: 无法解析的外部符号 __imp_PyBytes_FromStringAndSize，该符号在函数 "class tensorflow::Status __cdecl tensorflow::`anonymous namespace'::CopyStringToPyArrayElement
(struct tagPyAr
rayObject *,void *,struct TF_Tensor *,__int64,__int64)" (?CopyStringToPyArrayElement@?A0x10c2f664@tensorflow@@YA?AVStatus@2@PEAUtagPyArrayObject@@PEAXPEAUTF_Tensor@@_J3@Z) 中被引用 [D:\all_lib\tensorfl
ow-
r1.2\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
  py_func.obj : error LNK2001: 无法解析的外部符号 __imp_PyBytes_FromStringAndSize [D:\all_lib\tensorflow-r1.2\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
  pywrap_tensorflow_internal.obj : error LNK2001: 无法解析的外部符号 __imp_PyBytes_FromStringAndSize [D:\all_lib\tensorflow-r1.2\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
  tf_session_helper.obj : error LNK2019: 无法解析的外部符号 __imp_PyBytes_AsString，该符号在函数 "class tensorflow::Status __cdecl tensorflow::`anonymous namespace'::PyArrayDescr_to_TF_DataType(struct
_PyArray_Descr
*,enum TF_DataType *)" (?PyArrayDescr_to_TF_DataType@?A0x10c2f664@tensorflow@@YA?AVStatus@2@PEAU_PyArray_Descr@@PEAW4TF_DataType@@@Z) 中被引用 [D:\all_lib\tensorflow-r1.2\tensorflow\contrib\cmake\build
\py
wrap_tensorflow_internal.vcxproj]
  pywrap_tensorflow_internal.obj : error LNK2001: 无法解析的外部符号 __imp_PyBytes_AsString [D:\all_lib\tensorflow-r1.2\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
  tf_session_helper.obj : error LNK2019: 无法解析的外部符号 __imp_PyBytes_AsStringAndSize，该符号在函数 "class tensorflow::Status __cdecl tensorflow::`anonymous namespace'::PyBytesArrayMap<class <lambd
a_4d99011b9cff9
377914df5087ee03b23> >(struct tagPyArrayObject *,class <lambda_4d99011b9cff9377914df5087ee03b23>)" (??$PyBytesArrayMap@V<lambda_4d99011b9cff9377914df5087ee03b23>@@@?A0x10c2f664@tensorflow@@YA?AVStatus
@1@PEAUtagPyArrayObject@@V<lambda_4d99011b9cff9377914df5087ee03b23>@@@Z) 中被引用 [D:\all_lib\tensorflow-r1.2\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
  py_func.obj : error LNK2001: 无法解析的外部符号 __imp_PyBytes_AsStringAndSize [D:\all_lib\tensorflow-r1.2\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
  pywrap_tensorflow_internal.obj : error LNK2001: 无法解析的外部符号 __imp_PyBytes_AsStringAndSize [D:\all_lib\tensorflow-r1.2\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
  tf_session_helper.obj : error LNK2019: 无法解析的外部符号 __imp_PyUnicode_FromString，该符号在函数 "class tensorflow::Status __cdecl tensorflow::`anonymous namespace'::GetPyArrayDescrForTensor(struct
 TF_Tensor cons
t *,struct _PyArray_Descr * *)" (?GetPyArrayDescrForTensor@?A0x10c2f664@tensorflow@@YA?AVStatus@2@PEBUTF_Tensor@@PEAPEAU_PyArray_Descr@@@Z) 中被引用 [D:\all_lib\tensorflow-r1.2\tensorflow\contrib\cmake
\bu
ild\pywrap_tensorflow_internal.vcxproj]
  pywrap_tensorflow_internal.obj : error LNK2001: 无法解析的外部符号 __imp_PyUnicode_FromString [D:\all_lib\tensorflow-r1.2\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
  tf_session_helper.obj : error LNK2019: 无法解析的外部符号 __imp_PyUnicode_AsUTF8AndSize，该符号在函数 "class tensorflow::Status __cdecl tensorflow::`anonymous namespace'::PyBytesArrayMap<class <lambd
a_4d99011b9cff9
377914df5087ee03b23> >(struct tagPyArrayObject *,class <lambda_4d99011b9cff9377914df5087ee03b23>)" (??$PyBytesArrayMap@V<lambda_4d99011b9cff9377914df5087ee03b23>@@@?A0x10c2f664@tensorflow@@YA?AVStatus
@1@PEAUtagPyArrayObject@@V<lambda_4d99011b9cff9377914df5087ee03b23>@@@Z) 中被引用 [D:\all_lib\tensorflow-r1.2\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
  tf_session_helper.obj : error LNK2019: 无法解析的外部符号 __imp_PyUnicode_AsASCIIString，该符号在函数 "class tensorflow::Status __cdecl tensorflow::`anonymous namespace'::PyArrayDescr_to_TF_DataType(
struct _PyArray

**Comment by craigtao** [comment]
example_trainer.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl google::protobuf::internal::LogFinisher::operator=(class google::protobuf::internal::LogMessage &)" (??4LogFinisher@internal@protobuf@google@@QEAAXAEAVLogMessage@123@@Z)
1>example_trainer.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
1>example_trainer.obj : error LNK2001: 无法解析的外部符号 "public: class google::protobuf::internal::LogMessage & __cdecl google::protobuf::internal::LogMessage::operator<<(char const *)" (??6LogMessage@internal@protobuf@google@@QEAAAEAV0123@PEBD@Z)
1>example_trainer.obj : error LNK2001: 无法解析的外部符号 "public: __cdecl google::protobuf::internal::LogMessage::~LogMessage(void)" (??1LogMessage@internal@protobuf@google@@QEAA@XZ)
1>example_trainer.obj : error LNK2001: 无法解析的外部符号 "public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z)
1>example_trainer.obj : error LNK2001: 无法解析的外部符号 "private: void __cdecl google::protobuf::Arena::AddListNode(void *,void (__cdecl*)(void *))" (?AddListNode@Arena@protobuf@google@@AEAAXPEAXP6AX0@Z@Z)
1>example_trainer.obj : error LNK2001: 无法解析的外部符号 "private: void * __cdecl google::protobuf::Arena::AllocateAligned(class type_info const *,unsigned __int64)" (?AllocateAligned@Arena@protobuf@google@@AEAAPEAXPEBVtype_info@@_K@Z)
1>..\..\bin\win_trainer.exe : fatal error LNK1120: 7 个无法解析的外部命令



this sample  example_trainer.cc from \tensorflow-r1.2\tensorflow\cc\tutorials

The link library is also compiled using this source code. tensorflow-r1.2

Why did this link error occur?

thank you！

**Comment by reedwm** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
