### ISSUE TITLE
TfLiteCameraDemo performance with and without NNAPI

### ISSUE THREAD

**Issue by dimitryn** [tensorflow/tensorflow#19317]
Hi , 
I running TfLiteCameraDemo.apk on Google Pixel 2 8.1 Android.
when NNAPI = false apk display 90-80 ms per frame 
when NNAPI = true apk display 170- 200 ms per frame.

Is that NNAPI current performance ? match slower than Tflite path !?

Thanks.

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
SetUSENNAPI(true);
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
ubuntu 16
- **TensorFlow installed from (source or binary)**:
sources
- **TensorFlow version (use command below)**:
master
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
0.10
- **GCC/Compiler version (if compiling from source)**:
gcc
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
bazel build --cxxopt=--std=c++11 //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo --config=android_arm64 --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a

Thanks.

**Comment by dimitryn** [comment]
Thanks.

**Comment by haoyan01** [comment]
Does Android 8.1 provide an libneuralnetworks.so (even there is no GPU/DSP support) ? If so, how is it implemented ? or such *.so is empty.  Any related docs?

**Comment by freedomtan** [comment]
There should be libneuralnetworks.so that handles CPU fallback mentioned in NNAPI [doc](https://developer.android.com/ndk/guides/neuralnetworks/)
