### ISSUE TITLE
Alternative to image_tensor_mapped in Tensoreflow-Lite

### ISSUE THREAD

**Issue by simonfernandes7389** [tensorflow/tensorflow#19325]
Hi there, For my iOS app using Tensorflow the pre-processing was done by using image_tensor_mapped. i.e.

```
auto image_tensor_mapped = image_tensor.tensor<float, 4>();

uint32_t *pixels = (uint32_t *) calloc(width * height, sizeof(uint32_t));

uint8_t *bufptr = (uint8_t *)pixels;
for (i = 0; i < height; i++){
   for (j = 0; j < width; j++){
        blue = bufptr[1] / 255.0;
        green = bufptr[2] / 255.0;
        red = bufptr[3] / 255.0;
            
        image_tensor_mapped(0, i, j, 0) = blue;
        image_tensor_mapped(0, i, j, 1) = green;
        image_tensor_mapped(0, i, j, 2) = red;
            
        bufptr += 4;
    }
}
```
What will be the alternative for image_tensor_mapped in Tensorflow-lite(tflite)

Have I written custom code - No
OS Platform and Distribution - MacOS
TensorFlow installed from Pod
TensorFlow version - r1.8
TensorFlowLite version - 0.1.7
Bazel version - 0.11.0
CUDA/cuDNN version  - N/A
GPU model and memory - N/A
Exact command to reproduce - N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by simonfernandes7389** [comment]
Have I written custom code - No
OS Platform and Distribution - MacOS
TensorFlow installed from Pod
TensorFlow version - r1.8
TensorFlowLite version - 0.1.7
Bazel version - 0.11.0
CUDA/cuDNN version - N/A
GPU model and memory - N/A
Exact command to reproduce - N/A
