### ISSUE TITLE
When I install tensorflow for gpu mode, I got a error! hellp!

### ISSUE THREAD

**Issue by forfish** [tensorflow/tensorflow#1932]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:Ubuntu 15.10

Installed version of CUDA and cuDNN: both are 7.5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

Before I install tensorflow of GPU,I installed tensorflow of CPU and It work. And I want to install tensorflow of GPU. I get this error:
### Order:bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
Error info:

`bazel-out/local_linux-opt/bin/tensorflow/core/libcore_cpu_internal.lo(device.o): In function `tensorflow::Device::BuildDeviceAttributes(std::string const&, tensorflow::DeviceType, tensorflow::gtl::IntType<tensorflow::Bytes_tag_, long long>, tensorflow::BusAdjacency, std::string const&)':
device.cc:(.text._ZN10tensorflow6Device21BuildDeviceAttributesERKSsNS_10DeviceTypeENS_3gtl7IntTypeINS_10Bytes_tag_ExEENS_12BusAdjacencyES2_+0x2d): undefined reference to `google::protobuf::internal::empty_string_'
bazel-out/local_linux-opt/bin/tensorflow/core/libcore_cpu_internal.lo(device.o): In function `tensorflow::Device::Device(tensorflow::Env*, tensorflow::DeviceAttributes const&, tensorflow::Allocator*)':
device.cc:(.text._ZN10tensorflow6DeviceC2EPNS_3EnvERKNS_16DeviceAttributesEPNS_9AllocatorE+0xe0): undefined reference to `tensorflow::ResourceMgr::ResourceMgr(std::string const&)'
bazel-out/local_linux-opt/bin/tensorflow/core/libcore_cpu_internal.lo(threadpool_device.o): In function `tensorflow::ThreadPoolDevice::MakeTensorFromProto(tensorflow::TensorProto const&, tensorflow::AllocatorAttributes, tensorflow::Tensor*)':
threadpool_device.cc:(.text._ZN10tensorflow16ThreadPoolDevice19MakeTensorFromProtoERKNS_11TensorProtoENS_19AllocatorAttributesEPNS_6TensorE+0x69): undefined reference to `google::protobuf::Message::DebugString() const'
bazel-out/local_linux-opt/bin/tensorflow/core/libframework_internal.lo(types.o): In function `tensorflow::DataTypeString[abi:cxx11](tensorflow::DataType)':
types.cc:(.text._ZN10tensorflow14DataTypeStringB5cxx11ENS_8DataTypeE+0xa5): undefined reference to `tensorflow::strings::StrCat[abi:cxx11](tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&)'
bazel-out/local_linux-opt/bin/tensorflow/core/libframework_internal.lo(types.o): In function `tensorflow::DataTypeSliceString[abi:cxx11](tensorflow::gtl::ArraySlice<tensorflow::DataType>)':
types.cc:(.text._ZN10tensorflow19DataTypeSliceStringB5cxx11ENS_3gtl10ArraySliceINS_8DataTypeEEE+0xda): undefined reference to `tensorflow::strings::StrAppend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&)'
bazel-out/local_linux-opt/bin/tensorflow/core/libframework_internal.lo(mirror_pad_mode.o): In function `tensorflow::GetNodeAttr(tensorflow::NodeDef const&, tensorflow::StringPiece, tensorflow::MirrorPadMode*)':
mirror_pad_mode.cc:(.text._ZN10tensorflow11GetNodeAttrERKNS_7NodeDefENS_11StringPieceEPNS_13MirrorPadModeE+0x1fd): undefined reference to `tensorflow::strings::StrCat[abi:cxx11](tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&)'
bazel-out/local_linux-opt/bin/tensorflow/core/libframework_internal.lo(padding.o): In function `tensorflow::GetNodeAttr(tensorflow::NodeDef const&, tensorflow::StringPiece, tensorflow::Padding*)':
padding.cc:(.text._ZN10tensorflow11GetNodeAttrERKNS_7NodeDefENS_11StringPieceEPNS_7PaddingE+0x1fd): undefined reference to `tensorflow::strings::StrCat[abi:cxx11](tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&)'
collect2: error: ld returned 1 exit status
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.377s, Critical Path: 3.16s`

Another:
### bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
Error info:
python_op_gen.cc:(.text._ZN10tensorflow12_GLOBAL__N_1L11GetPythonOpERKNS_5OpDefEbSs+0x2117): undefined reference to `tensorflow::strings::Appendf(std::string*, char const*, ...)'
python_op_gen.cc:(.text._ZN10tensorflow12_GLOBAL__N_1L11GetPythonOpERKNS_5OpDefEbSs+0x2140): undefined reference to `tensorflow::strings::Appendf(std::string*, char const*, ...)'
python_op_gen.cc:(.text._ZN10tensorflow12_GLOBAL__N_1L11GetPythonOpERKNS_5OpDefEbSs+0x2549): undefined reference to `tensorflow::strings::Appendf(std::string*, char const*, ...)'
python_op_gen.cc:(.text._ZN10tensorflow12_GLOBAL__N_1L11GetPythonOpERKNS_5OpDefEbSs+0x262a): undefined reference to `tensorflow::strings::Appendf(std::string*, char const*, ...)'
python_op_gen.cc:(.text._ZN10tensorflow12_GLOBAL__N_1L11GetPythonOpERKNS_5OpDefEbSs+0x2726): undefined reference to `tensorflow::strings::Appendf(std::string*, char const*, ...)'
python_op_gen.cc:(.text._ZN10tensorflow12_GLOBAL__N_1L11GetPythonOpERKNS_5OpDefEbSs+0x30db): undefined reference to `tensorflow::strings::StrCat(tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&)'
python_op_gen.cc:(.text._ZN10tensorflow12_GLOBAL__N_1L11GetPythonOpERKNS_5OpDefEbSs+0x31b3): undefined reference to `tensorflow::strings::StrCat(tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&)'
bazel-out/host/bin/tensorflow/python/libpython_op_gen.lo(python_op_gen.o): In function `tensorflow::GetPythonOps(tensorflow::OpList const&, std::string const&, bool)':
python_op_gen.cc:(.text._ZN10tensorflow12GetPythonOpsERKNS_6OpListERKSsb+0x4e): undefined reference to `tensorflow::strings::Appendf(std::string*, char const*, ...)'
python_op_gen.cc:(.text._ZN10tensorflow12GetPythonOpsERKNS_6OpListERKSsb+0x37b): undefined reference to `tensorflow::strings::StrAppend(std::string*, tensorflow::strings::AlphaNum const&)'
python_op_gen.cc:(.text._ZN10tensorflow12GetPythonOpsERKNS_6OpListERKSsb+0x3d7): undefined reference to `tensorflow::strings::Appendf(std::string*, char const*, ...)'
python_op_gen.cc:(.text._ZN10tensorflow12GetPythonOpsERKNS_6OpListERKSsb+0x494): undefined reference to `google::protobuf::Message::DebugString() const'
python_op_gen.cc:(.text._ZN10tensorflow12GetPythonOpsERKNS_6OpListERKSsb+0x4b0): undefined reference to `tensorflow::strings::Appendf(std::string*, char const*, ...)'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.646s, Critical Path: 0.42s

nvidia info:
forfish1@Mercury:~/forfish1/workplace/gpu/tensorflow$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
forfish1@Mercury:~/forfish1/workplace/gpu/tensorflow$ nvcc
nvcc fatal   : No input files specified; use option --help for more information
forfish1@Mercury:~/forfish1/workplace/gpu/tensorflow$ 

Help!!!!!

**Comment by forfish** [comment]
@vrv  help! and anybody help!

**Comment by alliseesolutions** [comment]
Are you installing from source or using the pip install?

**Comment by alliseesolutions** [comment]
https://youtu.be/cVWVRA8XXxs

Maybe this could help?

**Comment by jayricco** [comment]
I got this same error. For me, it seemed to me an issue with the master branch and my system. I ended up pulling the vrv-patch-1 branch just now and that compiled fine using the same commands. Maybe try that?

**Comment by keveman** [comment]
@forfish Do you still have problems compiling example_trainer?

**Comment by forfish** [comment]
3Q for your attention，I updated to 0.8 and it work. Can you tell me how can I make a app with the example in tensorflow?

**Comment by forfish** [comment]
3Q for your attention，I updated to 0.8 and it work.

**Comment by forfish** [comment]
@keveman 3Q for your attention，I updated to 0.8 and it work.
