### ISSUE TITLE
use seq2seq to output context vector

### ISSUE THREAD

**Issue by NightKight** [tensorflow/tensorflow#1933]
When I use tensorflow seq2seq library, how can i get the context vector of input sequence?
Thanks a lot.

**Comment by lukaszkaiser** [comment]
I think by context vector you mean just the state after the encoder. For example, in [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/seq2seq_test.py#L34](this test) it would be the `enc_state` tensor.
