### ISSUE TITLE
Eager: Variable collection for training specific varibles

### ISSUE THREAD

**Issue by Harry-Up** [tensorflow/tensorflow#19341]
### System information
- **TensorFlow version (use command below)**: 1.6.0v GPU
- **Python version**: 3.6.4

### Describe the problem
When exploring the eager execution mode, I built neural network model with `tf.layers.Dense` API under the `tf.variable_scope("MLP")`. 

Once I would like to get variables with `tf.get_collection` to train specific variables, a ValueError was raised. 

> ValueError: When Eager Execution is enabled, variable collections are not supported.

It means that the `var_list` could not be collected to train specific variables, although fine-tune is quite common in the application of neural network model. Is there any solution?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by muaz-git** [comment]
@Harry-Up could you find solution to this problem?
