### ISSUE TITLE
Is there a way improve memory strategy with in-place & broadcasting & bsxfun?

### ISSUE THREAD

**Issue by myme5261314** [tensorflow/tensorflow#1934]
Suppose I have 4GB gpu memory, see the following code.

```python
A = tf.Variable(tf.zeros([5000, 5000, 25]))  # 5000*5000*25*4byte=2.5GB
B = tf.Variable(tf.zeros([5000, 25])  # 5000*25*4byte=500KB
sub_op = A.assign(A - B)
```
So, if you run sub_op, apparently, it will lead to OOM error, since A-B will need 5GB peak memory because of the broadcasting repetition.

Question 1: Is there a way to use functions like `bsxfun` in matlab which will not extend two object into the same big size and then calculate? i.e.
```python
sub_op = A.assign(tf.bsxfun(@minus, A, B))
```

Question 2: So, there's another problem about in-place assignment. Since sub_op related to in-place assignment, if the tensorflow haven't implemented it reasonable, it will lead to OOM error two, since there's no 5GB gpu memory to handle two 2.5GB objects.

Any ideas?

**Comment by myme5261314** [comment]
refer to [bsxfun memory](http://stackoverflow.com/questions/28722723/matlab-bsxfun-no-longer-faster-than-repmat) and [bsxfun](http://www.mathworks.com/help/matlab/ref/bsxfun.html)

I doubt that whether `bsxfun` is lead in with "not repetition" version in Matlab R2007, and after a few years, it's improved to the "repetition except the free memory is not enough" version. Matlab uses lazy allocation memory strategies.

**Comment by zffchen78** [comment]
On q1. 

Because A - B is an automatic broadcasting binary operation. A - B does not require B to be expanded to use 2.5GB. Only the result needs to be allocated (2.5GB). So, the peak memory usage in your code snippet should be 2.5GB + 500KB + 2.5GB. 

On q2.

It's been worked on. There can be multiple approaches to this issue: a) extend assign_sub() to support broadcasting; b) support inplace operationos like -=, +=, etc.

**Comment by rmlarsen** [comment]
If you replace write

sub_op = tf.assign_sub(A, B)

then the broadcasting happens implicitly in the underlying Eigen
expression, and the memory overhead should be minimal.

(Low level code is here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/dense_update_ops.h#L43
)

Rasmus

**Comment by myme5261314** [comment]
I have one more complex question other than just subtract.

Say, still maximum 4GB gpu memory, I need the operation like below, **I've confirmed this will lead to OOM error**:

```python
    A = tf.Variable(tf.zeros([5000, 25])) # 500KB
    temp1 = tf.tile(A, [1, 5000]) # 2.5GB
    temp2 = tf.reshape(temp1, [5000, 5000, 25])
    _temp2 = temp2 = tf.reshape(temp1, [5000, 5000, 25]) - A # OOM error.
    temp3 = temp2 - A
    temp4 = tf.square(temp2)
    temp5 = tf.reduce_sum(temp2, 2)
    temp6 = tf.reshape(temp5, [5000, 5000])

    sess = tf.Session()
    sess.run(tf.initialize_all_variables())
    sess.run(temp1) # run successfully
    print "temp1"
    sess.run(temp2) #  run successfully
    print "temp2"
    sess.run(temp3) # OOM error
    print "temp3"
    sess.run(temp4) # OOM error
    print "temp4"
    sess.run(temp5) # OOM error
    print "temp5"
    sess.run(temp6) # not execute.
    print "temp6"
```

So, I don't know why you all @zffchen78 @rmlarsen say that it won't expand intermediately.
Or, is my code wrong?

**Comment by zffchen78** [comment]
Both Rasmus and I meant your code do need > 2.5GB * 2 memory. I was trying to correct your understanding that A - B would expand B to 2.5GB first. If your understand was that way, the peak memory would be 2.5GB * 3.

Rasmus was saying, if your original code is changed to sub_op = tf.assign_sub(A, B) _and_ extend the code he points out, the peak memory usage in your program would be 2.5GB * 1.

**Comment by myme5261314** [comment]
Ok, so the issue is the one input as 2.5GB while the result requires another 2.5GB memory. Got that.
But, I'm a little confused why the following code still gives OOM error.
```python
temp2 = tf.reshape(temp1, [5000, 5000, 25])
temp2 -= A # if remove this line, sess.run(temp2) execute successfully, otherwise fails.
sess.run(temp2)
```

**Comment by zffchen78** [comment]
temp2 -= A is not doing any inplace update.

**Comment by yaroslavvb** [comment]
temp2 -= A tries to call "__isub__", if that's not defined (it's not defined for TF tensors), Python interpreter rewrites it into temp2 = temp2 - A and calls "__sub__"

**Comment by rmlarsen** [comment]
@myme5261314 : Did this answer your questions?

**Comment by myme5261314** [comment]
Yes, I see what's happening. Just for suggestion.
If I wrote the code
```python
temp2 = tf.reshape(temp1, [5000, 5000, 25])
# temp2_ = temp2
temp2 -= A
```
which temp2 is a tensor, that means whatever the temp2 tensor value is before this operation, I'm discarding it after this operation unless I have another `temp2_` which refer to the `temp2 before`, right?
So, if just like the code above, that line is commented, is it possible to make the `temp2 -= A` inplace? Since the `temp2 before` is just a transition tensor, the `temp2 after` is the actual tensor that might be `eval()` by the user.
I'm not familiar with tensorflow core, I don't know whether this could be implemented.
