### ISSUE TITLE
AttributeError: module 'tensorflow.contrib' has no attribute 'distribute'

### ISSUE THREAD

**Issue by sangeetsaurabh** [tensorflow/tensorflow#19343]
When I include mirroring strategy using following code -

# Build the Estimator
distribution = tf.contrib.distribute.MirroredStrategy()
config = tf.estimator.RunConfig(train_distribute=distribution)
model = tf.estimator.Estimator(model_fn,config=config)

I get the error - AttributeError: module 'tensorflow.contrib' has no attribute 'distribute'

I tried this with both Tensorflow 1.7 and 1.8 - I get the same issue. I am using Python 3.6 https://colab.research.google.com/ .

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by achalshah20** [comment]
Colab reasearch has v1.7. It has no module called distribute, so you should use that code with 1.8 and it works(tested).

https://github.com/tensorflow/tensorflow/tree/r1.7/tensorflow/contrib/distribute

**Comment by sangeetsaurabh** [comment]
Thank you for your comments! This was the issue happening only on Colab server. When I moved to my P2.8xlarge instance on AWS, it works fine there. Thank you for all your help and comments!
