### ISSUE TITLE
Improve java documentation by explaining "magic" constants like ""save/control_dependency""

### ISSUE THREAD

**Issue by apischan** [tensorflow/tensorflow#19348]
In your examples [here](https://github.com/tensorflow/models/blob/master/samples/languages/java/training/src/main/java/Train.java) there is a statement:
```
sess.runner()
     .feed("save/Const", checkpointPrefix)
     .addTarget("save/control_dependency")
     .run();
```
Can you explain somewhere in documentation what is the "magic" constants used there and list all the variants of them somewhere?

**Comment by asimshankar** [comment]
These aren't special constants, these are names printed by the script that generates the graph (see [code](https://github.com/tensorflow/models/blob/493d7a2e233fa874415062061fe0ce1aa62f2d3e/samples/languages/java/training/model/create_graph.py#L24)).

Sent https://github.com/tensorflow/models/pull/4297, hopefully that helps.
