### ISSUE TITLE
ArgumentError: argument --self_test: conflicting option string(s): --self_test

### ISSUE THREAD

**Issue by shiuan5566** [tensorflow/tensorflow#1935]
I just installed tensorflow and no problem when I enter **python -m tensorflow.models.image.mnist.convolutional** in console  
But when I open convolutional.py on spyder, it appears that
```
File "/usr/lib/python2.7/argparse.py", line 1467, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
ArgumentError: argument --self_test: conflicting option string(s): --self_test
```
and other example have the same problem such as
```
 File "/usr/lib/python2.7/argparse.py", line 1467, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
ArgumentError: argument --batch_size: conflicting option string(s): --batch_size
```
anyone can solve it??

**Comment by girving** [comment]
@keveman: Did you get a chance to look at this?

**Comment by keveman** [comment]
@shiuan5566 What platform are you trying this on?

**Comment by shiuan5566** [comment]
@keveman  I use Kubuntu 15.10

**Comment by keveman** [comment]
I am not the best person to debug this. Throwing it over to @martinwicke so he can find someone with access to different platforms.

**Comment by martinwicke** [comment]
I don't know what spyder is, and the fact that it runs ok in plain python makes me think this is not actually our error.

These types of errors are caused by the flag initialization code such as flags.DEFINE_string('batch_size', ...) running twice, or two different parts of the program defining flags with the same name (for self_test that would be a pretty likely candidate, batch_size not so much.

**Comment by aselle** [comment]
Automatically closing because there was no response and this is an unsupported configuration. Please reopen if it is still an issue and you verify it is not caused by Spyder's execution environment running initialization code twice. Thank you.

**Comment by eeveeta** [comment]
I ran into the same problem. I'm running word2vec.py from https://github.com/tensorflow/models/tree/master/tutorials/embedding

I'm running it on a google datalab notebook, on debian.
