### ISSUE TITLE
python3: Relink issue

### ISSUE THREAD

**Issue by lbiemans** [tensorflow/tensorflow#19375]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 78.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: 9.2
- **GPU model and memory**:  GeForce GTX 980 Ti - 6GB
- **Exact command to reproduce**:
python3 
import tensorflow as tf

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

== cat /etc/issue ===============================================
Linux blue 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="18.04 LTS (Bionic Beaver)"
VERSION_ID="18.04"
VERSION_CODENAME=bionic

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux blue 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.14.3)
protobuf (3.5.2.post1)
tensorflow-gpu (1.8.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcufft.so.9.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Fri May 18 09:03:01 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti  Off  | 00000000:05:00.0 Off |                  N/A |
| 22%   60C    P0    71W / 250W |      0MiB /  6080MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 980 Ti  Off  | 00000000:06:00.0 Off |                  N/A |
| 22%   57C    P0    67W / 250W |      0MiB /  6083MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 980 Ti  Off  | 00000000:09:00.0 Off |                  N/A |
|  0%   50C    P0    59W / 250W |      0MiB /  6083MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-9.2/doc/man/man7/libcudart.7
/usr/local/cuda-9.2/doc/man/man7/libcudart.so.7
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudart.so.9.2.88
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudart_static.a

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem

Can't run tensorflow because of this error:

python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by Squadrick** [comment]
Having the same issue.

**Comment by wangfys** [comment]
I have the same problem when I tried to preprocess pictures before training, maybe it's nothing wrong with tensorflow.
I'm using:
+ Windows Subsystem for Linux (Ubuntu 18.04)
+ python 3.6.5
+ opencv-python 3.4.1.15

```
Python 3.6.5 (default, Apr  1 2018, 05:46:30)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)
```
I'm confused now. I'm not sure whether it's the problem of WSL or opencv-python. My codes work fine on Ubuntu16.04 .

**Comment by Squadrick** [comment]
My problem was that the Nvidia drivers weren't installed properly. Now it's fine.

**Comment by lbiemans** [comment]
My solution seems installing np_utils.

**Comment by betachat** [comment]
I fixed it by following:
```bash
export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```

**Comment by wieberinsma** [comment]
I have the same issue on Ubuntu 18.10 (Cosmic Cuttlefish), none of the above worked for me. I'm running IntelliJ with a Python 3.6 interpreter that is inside virtualenv. Cuda 7.1.2, nvidia-cuda-toolkit 9.1.85-4.

`/home/<username>/virtual/tensorflow/bin/python3.6: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'`

**Comment by betachat** [comment]
@wieberinsma try to use CUDA 9.0.
The official site says that it needs CUDA 9.0.

**Comment by wieberinsma** [comment]
Which official site do you mean? I'm pretty sure the pre-installed nvidia packages (nvida-cuda-dev, etc.) should be in sync with the toolkit, which is all v9.1.85. Toolkit 9.2 is apparently not yet supported for Ubuntu 18.10.

**Comment by betachat** [comment]
Tensorflow's website.
Try to install CUDA 9.0 by deb.
You can download it from Nvidia (just search CUDA 9.0) and copy cudnn files into /.../CUDA
Then set environment path.
I think it would work.

Sorry for bad English :(

**Comment by betachat** [comment]
I think your problem is caused by cudnn.
Download this.
https://imgur.com/a/Zlp30No

**Comment by wieberinsma** [comment]
I wil ltry, but I am a bit confused. cuDNN is not the same as the CUDA toolkit. Also, if you are referring to this CUDA toolkit https://developer.nvidia.com/cuda-90-download-archive, that one is not compatible with Ubuntu 18.04 (I have tried).

**Comment by betachat** [comment]
You can install cuda-9-0 via aptitude command, it will fix something automatically.

**Comment by lbiemans** [comment]
You could also do something like:

wget https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda_9.0.176_384.81_linux-run
chmod 755 cuda_9.0.176_384.81_linux-run
./cuda_9.0.176_384.81_linux-run --override

echo /usr/local/cuda-9.0/lib64 >   /etc/ld.so.conf.d/cuda-9-0.conf

**Comment by wieberinsma** [comment]
Thanks for the suggestions guys, will try to see if this fixes it soon.

**Comment by jcarreira** [comment]
Have the same issue when importing tensorflow (only fails with tensorflow-gpu):

```
tf_gpu) [---@---:/home/...]% python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
zsh: segmentation fault (core dumped)  python3

```

Some info about my setup:
1. CUDA toolkit 9.0
2. set the PATH and LD_LIBRARY_PATH environment variables as suggested
3. Installed nvidia drivers using ```ubuntu-drivers autoinstall```
4. Installed ```opencv-python``` and ```np_utils``` as suggested

**Comment by darrellenns** [comment]
I have also tried everything solution listed here, and the same issue persists

- cuda 9.0 using "local install"
- set PATH and LD_LIBRARY_PATH
- library path in ld.so.conf.d and ran ldconfig
- nvidia driver 390.87
- installed opencv-python and np_utils

**Comment by 995270418L** [comment]
same with upstairs.

**Comment by 995270418L** [comment]
cuda 9.0 using "nvidia deb file "
ubuntu 18.04
nividia driver 390.87
installed opencv-python and np_utils
had config LD_LIBRARY_PATH and PATH
cuDNN 7.3

**Comment by soulmachine** [comment]
I tried all ways mentioned above but none worked, this is very upsetting

**Comment by deblauwetom** [comment]
For me what worked on linux mint 19 tara:
- I have a 6GB GTX 1060 card
- install 390 driver just with `apt install nvidia-driver-390`
- install cuda-9.0 from the nvidia website + all these 4 patches on top
- .... here i got this error....
- So fix was to really sign up for the nvidia developer program, and download cudnn 7.3.1 for linux for cuda 9.0

Now "import tensorflow" works in my python3. 👍 
Cheerio!

**Comment by FazalAAli** [comment]
Here's how I fixed this issue for me:
**Things that didn't fix the issue**
1. Installed all the dependencies for the thing I was working on (hypergan in this case). 
2. Installed latest linux nvidia drivers (390 in my case)
3. Download and install Cuda 9.0

**Thing that worked**
Installing Cudnn from Nvidia using the .deb pacakge.(The package was meant for ubuntu 16.04 but it worked fine for me on 18.04)

**Comment by TimZaman** [comment]
I am on a Titan Volta with Ubuntu 18.04, cuda10, nvidia driver 410. Installing cudnn (7.4) fixed it for me.

**Comment by max0x7ba** [comment]
March 2019 update. 

`tensorflow-gpu` is built against `cuda-10.0`. Ubunty 18.04 has `cuda-10.1` and that is incompatible with `tensorflow-gpu`.

One has to go to NVidia developer website to install CUDA from CUDA Toolkit 10.0 Archive **along** with corresponding `cuDNN` because the latter is not packaged with `cuda` meta-package. 

If you don't install `cuDNN` you get that `python: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'` error.

`tensorflow-gpu` should work in Ubuntu 18.04 out of the box.

**Comment by lolitsgab** [comment]
@betachat Addint to my paths like you mentioned fixed my problem! Thank you!

**Comment by gaurav16gupta** [comment]
I got the same problem.  
python3: Relink /lib/x86_64-linux-gnu/libudev.so.1' with /lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)
even after correct CUDA and CUDNN installation.  
Finally **installing opencv  (apt install python3-opencv) worked!** 
Strange...?

**Comment by mammadjv** [comment]
Solved my problem with replacing cudnn-9.1 by cudnn-9.0 .
check [this](https://medium.com/@lookfwd/install-tensorflow-1-12-gpu-on-g3-aws-ubuntu-18-04-instances-4cd884f06ec2) out  for a perfect installation guide.

**Comment by cryoff** [comment]
I had the same issue and it was resolved by "installing" cuDNN

**Comment by bhattacharya586** [comment]
> I have the same problem when I tried to preprocess pictures before training, maybe it's nothing wrong with tensorflow.
> I'm using:
> 
> * Windows Subsystem for Linux (Ubuntu 18.04)
> * python 3.6.5
> * opencv-python 3.4.1.15
> 
> ```
> Python 3.6.5 (default, Apr  1 2018, 05:46:30)
> [GCC 7.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import cv2
> python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
> Segmentation fault (core dumped)
> ```
> 
> I'm confused now. I'm not sure whether it's the problem of WSL or opencv-python. My codes work fine on Ubuntu16.04 .

Does your problem solved??

**Comment by ray1422** [comment]
Does your CPU support AVX ?

**Comment by bhattacharya586** [comment]
Thanks for your reply it worked... But the problem I am facing is the
problem that our cloud instance doesn't connect it with the webcam... Aws
cloud with hardware connection problem I am facing now

**Comment by asadkhilji** [comment]
> Now I find the solution from [here](https://unix.stackexchange.com/questions/444697/cannot-run-python-file-asks-to-relink-libraries). Just need to install opencv-python correctly.

This worked for me. Thanks

**Comment by AndreasLuckert** [comment]
So far nothing of the above-mentioned steps resolved my problem.

As for my issue:

```
user:~/$ jupyter qtconsole
/home/linuxbrew/.linuxbrew/opt/python@3.8/bin/python3.8:
Relink `/usr/lib/x86_64-linux-gnu/libQtCore.so.4' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)
```

**Comment by justinkterry** [comment]
No suggested fixes in this thread worked for me, but i tried importing cv2 alone based on the comments and it threw and error. Googling that error turned up this: https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo

Which did in fact fix the issue for me.

**Comment by max0x7ba** [comment]
I still use Ubuntu 18.04. Things have got better.

The working solution as of the time of this post is:

1. Uninstall all NVidia packages which were installed from Ubuntu repos. 
2. Follow https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#ubuntu-installation instructions to install NVidia repo.
3. Install required CUDA version, along with NVidia kernel and xorg driver from a tool of your choice. I used Muon Package Manager.

That solved it for me.

**Comment by VoNhatVinh** [comment]
I fix this issue by activate virutal environment in this topic https://stackoverflow.com/questions/53070868/how-to-install-python3-7-and-create-a-virtualenv-with-pip-on-ubuntu-18-04
