### ISSUE TITLE
Build from source fail : web_animations_js

### ISSUE THREAD

**Issue by ballaslee** [tensorflow/tensorflow#1937]
### Environment info
Ubuntu 14.04
hardware - NVidia DIGITS DevBox

Installed version of CUDA and cuDNN: CUDA 7.5, cuDNN 5

### Issue

Issue: trying to install TensorFlow from source and have run into a number of issues. 
1. Resolved: Issue reported elsewhere with pulling eigen. Resolved by downloading eigen manually and modifying workspace.bzl to point to local eigen repository.
2. Unresolved: Error with getting web-animations for bower:

##### Output 

xxx@yyy:~/tensorflow⟫ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
ERROR: /home/liam/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@web_animations_js//': Error cloning repository: https://github.com/web-animations/web-animations-js.git: cannot open git-upload-pack caused by https://github.com/web-animations/web-animations-js.git: cannot open git-upload-pack caused by https://github.com/web-animations/web-animations-js.git: cannot open git-upload-pack and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: Loading failed; build aborted.

I'm not sure how to fix this - any help at all would be appreciated.

**Comment by ballaslee** [comment]
I managed to resolve this by getting my proxy issues sorted out.

**Comment by jiapei100** [comment]
Got exactly the same issue as yours. Can you please be more specific?  What is your proxy issue?
