### ISSUE TITLE
Memory leak in Eager execution

### ISSUE THREAD

**Issue by henriquem87** [tensorflow/tensorflow#19385]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Xubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 'v1.8.0-1451-g6ba9573' 1.8.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: 0.11.1
- **GCC/Compiler version (if compiling from source)**: 5.4.0 20160609
- **CUDA/cuDNN version**: 9.1 / 7.1
- **GPU model and memory**: GeForce GTX 960M - 2GB
- **Exact command to reproduce**: Just run the following code:

```python
import tensorflow as tf

tf.enable_eager_execution()

class Net(tf.keras.Model):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = tf.keras.layers.Conv2D(32, 3)

    def call(self, x):
        y = self.conv1(x)
        return y

inputs = tf.zeros([1, 10, 10, 3], tf.float32)
net = Net()
for _ in range(1000000):
    net(inputs)
```

### Describe the problem
I am observing a memory leak when I run the code above at my machine. The RAM usage increase indefinitely over time (but GPU memory remains constant). Profiling the code with memory_profiler produces the following plot:
![memory_plot_conv2d](https://user-images.githubusercontent.com/24420973/40237678-828c29ec-5a87-11e8-9a96-a15d7b1b3ca6.png)

### Source code / logs

This problem might be related to the usage of tensors of rank higher than two. For example, if I use a rank 2 tensor as input to a dense layer, then there is no leak:
```python
import tensorflow as tf

tf.enable_eager_execution()

class Net(tf.keras.Model):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = tf.keras.layers.Dense(32)

    def call(self, x):
        y = self.fc1(x)
        return y

inputs = tf.zeros([1, 100], tf.float32)
net = Net()
for _ in range(1000000):
    net(inputs)
```
![memory_plot_fc](https://user-images.githubusercontent.com/24420973/40238436-951a3570-5a89-11e8-8d80-b75a423e2f3f.png)

However, if I input a rank 3 tensor to the same net, there is a leak again:
```python
import tensorflow as tf

tf.enable_eager_execution()

class Net(tf.keras.Model):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = tf.keras.layers.Dense(32)

    def call(self, x):
        y = self.fc1(x)
        return y

inputs = tf.zeros([1, 10, 10], tf.float32)
net = Net()
for _ in range(1000000):
    net(inputs)
```
![memory_plot_fc_rank3](https://user-images.githubusercontent.com/24420973/40238473-a8f22ea4-5a89-11e8-9ab7-0b9fc6eab18b.png)

Please let me know if there is anything else I can do to help.

**Comment by akshaym** [comment]
Thanks for the report @henriquem87, and for helping track it down @allenlavoie!

I have a fix which should get committed in the next couple days.

**Comment by henriquem87** [comment]
Thank you for the fix @akshaym and @allenlavoie ! It did solve that problem. However, now I am observing another leak when I use tfe.GradientTape(). The code to reproduce the problem, and the memory plot are below:

```python
import tensorflow as tf

tf.enable_eager_execution()
tfe = tf.contrib.eager

class Net(tf.keras.Model):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = tf.keras.layers.Dense(5)

    def call(self, x):
        y = self.fc1(x)
        return y

inputs = tf.zeros([32, 100], tf.float32)
net = Net()
for i in range(1000000):
    with tfe.GradientTape() as tape:
        net(inputs)
```
![tape](https://user-images.githubusercontent.com/24420973/40581921-16b78f98-613c-11e8-887b-47a3ea3d3061.png)

Should I open a new issue for this?

**Comment by allenlavoie** [comment]
@alextp want to take a look (at the GradientTape issue; the original leak has been plugged)?

FWIW it doesn't look like a PyObject leak (or at least the test decorators don't see one), and I can reproduce it without a Model (nightly builds, Python 2.7 and 3.6 rather than just 3 this time):

```
import tensorflow as tf
tf.enable_eager_execution()

layer = tf.keras.layers.Dense(5)
inputs = tf.zeros([32, 100], tf.float32)

for i in range(1000000):
  with tf.GradientTape() as tape:
    layer(inputs)
```

**Comment by allenlavoie** [comment]
https://github.com/tensorflow/tensorflow/commit/bf6644f9d274f549707d3f2a80c77e5eda163ebb was for the original issue; re-opening to keep tracking the GradientTape issue.
