### ISSUE TITLE
Tensorflow setup on clound9

### ISSUE THREAD

**Issue by ngoduyvu** [tensorflow/tensorflow#1939]
I am doing the project using Tensorflow. I set up it on Clound9 since It run on Ubuntu. I chose python 2.7. However, It kept showing an error: enter image description here . Does anyone have any idea why it keep happening? By the way, I clone tensorflow github in my repository. Thanks

(tensorenv)ngoduyvu:~/workspace (master) $ pip install --upgrade https://storage.googleapis
.com/tensorflow/linux/cpu/tensorflow-0.8.0rc0-cp27-none-linux_x86_64.whl
Collecting tensorflow==0.8.0rc0 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0rc0-cp27-none-linux_x86_64.whl
  Downloading https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0rc0-cp27-none-linux_x86_64.whl (22.2MB)
    100% |████████████████████████████████| 22.2MB 40kB/s 
Collecting six>=1.10.0 (from tensorflow==0.8.0rc0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b2 (from tensorflow==0.8.0rc0)
  Downloading protobuf-3.0.0b2-py2.py3-none-any.whl (326kB)
    100% |████████████████████████████████| 327kB 1.8MB/s 
Requirement already up-to-date: wheel in ./miniconda/envs/tensorenv/lib/python2.7/site-packages (from tensorflow==0.8.0rc0)
Collecting numpy>=1.8.2 (from tensorflow==0.8.0rc0)
  Downloading numpy-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl (15.3MB)
    100% |████████████████████████████████| 15.3MB 60kB/s 
Collecting setuptools (from protobuf==3.0.0b2->tensorflow==0.8.0rc0)
  Downloading setuptools-20.7.0-py2.py3-none-any.whl (508kB)
    100% |████████████████████████████████| 512kB 1.8MB/s 
Installing collected packages: six, setuptools, protobuf, numpy, tensorflow
  Found existing installation: setuptools 20.6.7
Cannot remove entries from nonexistent file /home/ubuntu/workspace/miniconda/envs/tensorenv/lib/python2.7/site-packages/easy-install.pth

**Comment by martinwicke** [comment]
Can you try the pip with with `--ignore-installed`?

**Comment by ngoduyvu** [comment]
Thanks, I find out what is the problem. I already install tensorflow, but what I did were install again so It collapsed.
