### ISSUE TITLE
g3doc tutorial mnist.py tf.range missing argument

### ISSUE THREAD

**Issue by colinfang** [tensorflow/tensorflow#194]
` indices = tf.expand_dims(tf.range(batch_size), 1)`
in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/tutorials/mnist/mnist.py#L94

which should be `indices = tf.expand_dims(tf.range(0, batch_size, 1), 1)`

The [tutorial doc](http://www.tensorflow.org/tutorials/mnist/tf/index.md) shows the correct code.

**Comment by girving** [comment]
Apologies for the inconsistency.  We fixed the code to allow one-argument range, but the release hasn't changed and that's probably what you're using.  Good to know about the synchronization issue; we'll keep it in mind in future.

**Comment by girving** [comment]
I'm going to fix this in git to be compatible back to 0.5.0.

**Comment by girving** [comment]
Fixed, will be part of the next git commit.
