### ISSUE TITLE
convolution on dimension variable inputs 

### ISSUE THREAD

**Issue by ahmed-touati** [tensorflow/tensorflow#1940]
I would like to perform a convolution on dimension variable inputs. 
The only solution I find and I think that it would work is to perform a convolution on each input and perform a scan on batch_size. I think this is not optimal.
Is there another function or method to do this differently in TensorFlow?

Thanks in advance.

**Comment by zffchen78** [comment]
Can you clarify on what "dimension variable inputs" means?

**Comment by ahmed-touati** [comment]
@zffchen78 I would like perform a convolution 1d on sentences with not fixed length. 
My mini batch contains sentences with different lengths.

**Comment by black-puppydog** [comment]
so in vision this would correspond to input images of varying size within a batch? If so I would be muchmuch interested in that, too, but suspect it's not going to happen any time soon :P

**Comment by ahmed-touati** [comment]
@black-puppydog yes it corresponds to input images of varying size in computer vision
I am trying to implement this paper http://research.microsoft.com/pubs/226585/cikm2014_cdssm_final.pdf and I would like to avoid making a for loop over mini batch examples.

**Comment by zffchen78** [comment]
I am not aware of anyone doing exactly what you are trying. Maybe the following. Say your batch has N sentences, each sentence has up to M words, each word's embedding dimensions is K. For sentence shorter than M, pads it with a special word with a fixed embedding vector of 0s. Then, you can do batch 1D convolution on [N, M*K] (per-row). Multiple the result w/ a mask of [ [1,..., 1, 1, ...0, ..., 0, 0], ...[...]], the total number of 1s and 0s on each row can be computed for each batch.

**Comment by girving** [comment]
I'm going to close, since I don't think this is feasible in TensorFlow in a performant manner.  Everything down to cuDNN assumes rectangular tensors, and uses this assumption to arrange for high arithmetic intensity.  Fancy approaches which do manual tiling of irregularly sizes images are possible, but those would be a layer on top of tensorflow (or possibly something in `tf.contrib`).

**Comment by ayushchd** [comment]
Is there a way to achieve this even by using a batch of size 1? Each batch would contain 1 sentence, however, the ksize in max pooling needs to be set dynamically since it would depend on the length of the input. Any ideas?

**Comment by abieler** [comment]
The solution to this issue would be interesting indeed :)

**Comment by utkrist** [comment]
Yes. I need this too.

**Comment by dandarm** [comment]
Me too :-)

**Comment by ltt00** [comment]
Me too!

**Comment by XuanHeIIIS** [comment]
Me too :)

**Comment by gauravkoradiya** [comment]
me too :)
