### ISSUE TITLE
Error trying on GPU 

### ISSUE THREAD

**Issue by shahinsh** [tensorflow/tensorflow#1943]
Hi Everyone 

I'm new in TensorFlow , I'm running some tests . I tried the Convolutional.py on my local machine and it ran perfectly and everything was ok .On my local pc I don't have a Nvidia GPU , so I tried to connect to a server computer which has Nvidia M4000, I installed Cudnn 7.5 the last version from their website and my CUDA toolkit  is the last version of CUDA (7.5) .

When I run the " import tensorflow as tf " everything is ok and it recognize all the libraries and Cudnn .
I manually downloaded the mnist data and I put it in the directory ,when I run the Convolutional.py ,the extracting and everything goes ok when it wants to initialize I receive this error 

ConvolutionalBackwardFilter_V2 cudnn DSO dlerror 

I looked at the cudnn library and searched in it , there is ConvolutionalBackwardFilter in it but there isn't ConvolutionalBackwardFilter_V2. 

I changed the cudnn 7.5 to cudnn 6.5 but still the same story .
At this point I don't know what to do and how can I fix this issue ? I would be grateful if someone could help me 

P.S :My operating system is Linux Ubunto and the server operating system is CentOs

**Comment by vrv** [comment]
If you are installing from pip packages, try installing cudnn v4 -- our pip packages require cudnn4.
