### ISSUE TITLE
My tensorflow model doesn't work on c++ iOS

### ISSUE THREAD

**Issue by cagrigider** [tensorflow/tensorflow#19437]
I am trying to do character recognition mobile app with CNN. My model predict with %99,6 accuracy on python. But when I m trying to use same model with c++ in iOS app it can't predict any value. 

I am getting pixelBuffer values from images for my cnn model with this:

        pixelBuffer(width: width, height: height,
                           pixelFormatType: kCVPixelFormatType_32BGRA,
                           colorSpace: CGColorSpaceCreateDeviceRGB(),
                           alphaInfo: .noneSkipFirst)

    func pixelBuffer(width: Int, height: Int, pixelFormatType: OSType,
                     colorSpace: CGColorSpace, alphaInfo: CGImageAlphaInfo) -> CVPixelBuffer? {
        var maybePixelBuffer: CVPixelBuffer?
        let attrs = [kCVPixelBufferCGImageCompatibilityKey: kCFBooleanTrue,
                     kCVPixelBufferCGBitmapContextCompatibilityKey: kCFBooleanTrue]
        let status = CVPixelBufferCreate(kCFAllocatorDefault,
                                         width,
                                         height,
                                         pixelFormatType,
                                         attrs as CFDictionary,
                                         &maybePixelBuffer)
        
        guard status == kCVReturnSuccess, let pixelBuffer = maybePixelBuffer else {
            return nil
        }
        
        CVPixelBufferLockBaseAddress(pixelBuffer, CVPixelBufferLockFlags(rawValue: 0))
        let pixelData = CVPixelBufferGetBaseAddress(pixelBuffer)
        
        guard let context = CGContext(data: pixelData,
                                      width: width,
                                      height: height,
                                      bitsPerComponent: 8,
                                      bytesPerRow: CVPixelBufferGetBytesPerRow(pixelBuffer),
                                      space: colorSpace,
                                      bitmapInfo: alphaInfo.rawValue)
            else {
                return nil
        }
        
        UIGraphicsPushContext(context)
        context.translateBy(x: 0, y: CGFloat(height))
        context.scaleBy(x: 1, y: -1)
        self.draw(in: CGRect(x: 0, y: 0, width: width, height: height))
        UIGraphicsPopContext()
        
        CVPixelBufferUnlockBaseAddress(pixelBuffer, CVPixelBufferLockFlags(rawValue: 0))
        return pixelBuffer}

and then I m creating my model with this settings:

        static NSString* model_file_name = @"inference_1_1_0";
        static NSString* model_file_type = @"pb";
        static NSString* labels_file_name = @"labels";
        static NSString* labels_file_type = @"txt";
        std::unique_ptr<tensorflow::Session> tf_session;
        std::vector<std::string> labels;

        const int wanted_input_width = 38;
        const int wanted_input_height = 45;
        const int wanted_input_channels = 3;
        const float input_mean = 117.0f;
        const float input_std = 1.0f;
        const std::string input_layer_name = "input_input";
        const std::string output_layer_name = "output_node0";

but I have no idea what should I use for `input_mean` and `input_std` . Maybe they can be problem. 
I got runCNN method default from [Tensorflow Example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/ios/camera/CameraExampleViewController.mm)

I really have no idea my image is wrong or should I change any default settings from tensorflow

Thanks.

- Have I written custom code: Yes
- OS Platform and Distribution: Mac OS 10.13.3 High Sierra
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.1.0 on Mac (Tensorflow-Experimental on iOS)
- Python version: 3
- Bazel version: 0.13.0
- CUDA/cuDNN: N/A
- GPU model and Memory: N/A
- Exact command to reproduce: When I am trying to predict with my model it's always predict wrong.(Prediction)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
CUDA/cuDNN version
GPU model and memory

**Comment by cagrigider** [comment]
CUDA/cuDNN: N/A
GPU model and Memory: N/A

**Comment by cagrigider** [comment]
const float input_mean = 117.0f;
    const float input_std = 1.0f;
always works well ? or should I find special values for my model.(And how can I find ? )

**Comment by michaelisard** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
