### ISSUE TITLE
In TF Stylize demo,I replace the camera captured bitmap with a predefined one,but not work

### ISSUE THREAD

**Issue by GL1920** [tensorflow/tensorflow#19448]
I replace the camera captured bitmap with a predefined one,but not work.
The code changes as follows:
`@TargetApi(Build.VERSION_CODES.LOLLIPOP)
public class StylizeActivity  extends Activity  {

  private static final Logger LOGGER = new Logger();

  private static final String MODEL_FILE = "file:///android_asset/stylize_quantized.pb";
  private static final String INPUT_NODE = "input";
  private static final String STYLE_NODE = "style_num";
  private static final String OUTPUT_NODE = "transformer/expand/conv3/conv/Sigmoid";
  private static final int NUM_STYLES = 26;

  private static final boolean SAVE_PREVIEW_BITMAP = false;
  private static final boolean NORMALIZE_SLIDERS = true;

  private static final float TEXT_SIZE_DIP = 12;

  private static final boolean DEBUG_MODEL = false;
  private Handler handler;
  private HandlerThread handlerThread;
  private int desiredSize = 256;
  private long lastProcessingTimeMs;
  private final float[] styleVals = new float[NUM_STYLES];
  private int[] intValues;
  private float[] floatValues;

  private int frameNum = 0;
  private ImageView imageView;

  private Bitmap textureCopyBitmap;
  private Bitmap bitmap;
  private Bitmap newbm;
  private Bitmap test;

  private TensorFlowInferenceInterface inferenceInterface;

  private int lastOtherStyle = 1;

  private boolean allZero = false;

  private ImageGridAdapter adapter;
  private GridView grid;
  private int[] rgbBytes = null;
  private Runnable imageConverter;
  // which image
  int position_now;
  // image url
  String url = null;
  private Boolean debug=false;

  private final OnTouchListener gridTouchAdapter =
          new OnTouchListener() {
            ImageSlider slider = null;

            @Override
            public boolean onTouch(final View v, final MotionEvent event) {
              switch (event.getActionMasked()) {
                case MotionEvent.ACTION_DOWN:
                  for (int i = 0; i < NUM_STYLES; ++i) {
                    final ImageSlider child = adapter.items[i];
                    final Rect rect = new Rect();
                    child.getHitRect(rect);
                    if (rect.contains((int) event.getX(), (int) event.getY())) {
                      slider = child;
                      slider.setHilighted(true);
                    }
                  }
                  **chuli();**
                  break;

                case MotionEvent.ACTION_MOVE:
                  if (slider != null) {
                    final Rect rect = new Rect();
                    slider.getHitRect(rect);

                    final float newSliderVal =
                            (float)
                                    Math.min(
                                            1.0,
                                            Math.max(
                                                    0.0, 1.0 - (event.getY() - slider.getTop()) / slider.getHeight()));

                    setStyle(slider, newSliderVal);
                  }
                  **chuli();**
                  break;

                case MotionEvent.ACTION_UP:
                  if (slider != null) {
                    slider.setHilighted(false);
                    slider = null;
                  }
                  **chuli();**
                  break;

                default: // fall out

              }
              return true;
            }
          };
  private int previewWidth;
  private int previewHeight;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.camera_connection_fragment_stylize);
    // get intent information
    getMessage();
    initView();

  }

private void initView(){
  adapter = new ImageGridAdapter();
  grid = (GridView) findViewById(R.id.grid_layout);
  grid.setAdapter(adapter);
  grid.setOnTouchListener(gridTouchAdapter);
  imageView=(ImageView)findViewById(R.id.ivs);
  inferenceInterface = new TensorFlowInferenceInterface(getAssets(), MODEL_FILE);

  intValues = new int[desiredSize * desiredSize];
  floatValues = new float[desiredSize * desiredSize * 3];
  BitmapFactory.Options options = new BitmapFactory.Options();
  options.inPreferredConfig = Config.ARGB_8888;
  bitmap = BitmapFactory.decodeFile(url, options);
  previewWidth=bitmap.getWidth();
  previewHeight=bitmap.getHeight();

  **newbm=Bitmap.createScaledBitmap(bitmap,desiredSize,desiredSize,true);**
  **imageView.setImageBitmap(bitmap);

  if(textureCopyBitmap!=null){
    test=big(textureCopyBitmap);
    imageView.setImageBitmap(test);
  }**

}
  private  Bitmap big(Bitmap bitmap) {
    Matrix matrix = new Matrix();
    matrix.postScale(2.f,2.f); //长和宽放大缩小的比例
    Bitmap resizeBmp = Bitmap.createBitmap(bitmap,0,0,bitmap.getWidth(),bitmap.getHeight(),matrix,true);
    return resizeBmp;
  }
private void chuli(){
  runInBackground(
          new Runnable() {
            @Override
            public void run() {
              final long startTime = SystemClock.uptimeMillis();
              stylizeImage(newbm);
              lastProcessingTimeMs = SystemClock.uptimeMillis() - startTime;
              textureCopyBitmap = Bitmap.createBitmap(newbm);
              requestRender();
          
            }
          });
}
  protected void getMessage() {
    Intent intent = getIntent();
    try {
      position_now = intent.getIntExtra("position", -1);
      url  = intent.getStringExtra("url");
    } catch (Exception e) {
      Log.d("ERROR: ", "" + e);
    }
    Log.d("Info: ", "" + position_now + " " + url);
  }

  private static Bitmap getBitmapFromAsset(final Context context, final String filePath) {
    final AssetManager assetManager = context.getAssets();

    Bitmap bitmap = null;
    try {
      final InputStream inputStream = assetManager.open(filePath);
      bitmap = BitmapFactory.decodeStream(inputStream);
    } catch (final IOException e) {
      LOGGER.e("Error opening bitmap!", e);
    }

    return bitmap;
  }

  @Override
  public synchronized void onStart() {
    LOGGER.d("onStart " + this);
    super.onStart();
  }

  @Override
  public synchronized void onResume() {
    LOGGER.d("onResume " + this);
    super.onResume();

    handlerThread = new HandlerThread("inference");
    handlerThread.start();
    handler = new Handler(handlerThread.getLooper());
  }

  @Override
  public synchronized void onPause() {
    LOGGER.d("onPause " + this);

    if (!isFinishing()) {
      LOGGER.d("Requesting finish");
      finish();
    }

    handlerThread.quitSafely();
    try {
      handlerThread.join();
      handlerThread = null;
      handler = null;
    } catch (final InterruptedException e) {
      LOGGER.e(e, "Exception!");
    }

    super.onPause();
  }

  @Override
  public synchronized void onStop() {
    LOGGER.d("onStop " + this);
    super.onStop();
  }

  @Override
  public synchronized void onDestroy() {
    LOGGER.d("onDestroy " + this);
    super.onDestroy();
  }

  protected synchronized void runInBackground(final Runnable r) {
    if (handler != null) {
      handler.post(r);
    }
  }

//gridview imagestyle
  private class ImageSlider extends android.support.v7.widget.AppCompatImageView {
    private float value = 0.0f;
    private boolean hilighted = false;

    private final Paint boxPaint;
    private final Paint linePaint;

    public ImageSlider(final Context context) {
      super(context);
      value = 0.0f;

      boxPaint = new Paint();
      boxPaint.setColor(Color.BLACK);
      boxPaint.setAlpha(128);

      linePaint = new Paint();
      linePaint.setColor(Color.WHITE);
      linePaint.setStrokeWidth(10.0f);
      linePaint.setStyle(Style.STROKE);
    }

    @Override
    public void onDraw(final Canvas canvas) {
      super.onDraw(canvas);
      final float y = (1.0f - value) * canvas.getHeight();

      // If all sliders are zero, don't bother shading anything.
      if (!allZero) {
        canvas.drawRect(0, 0, canvas.getWidth(), y, boxPaint);
      }

      if (value > 0.0f) {
        canvas.drawLine(0, y, canvas.getWidth(), y, linePaint);
      }

      if (hilighted) {
        canvas.drawRect(0, 0, getWidth(), getHeight(), linePaint);
      }
    }

    @Override
    protected void onMeasure(final int widthMeasureSpec, final int heightMeasureSpec) {
      super.onMeasure(widthMeasureSpec, heightMeasureSpec);
      setMeasuredDimension(getMeasuredWidth(), getMeasuredWidth());
    }

    public void setValue(final float value) {
      this.value = value;
      postInvalidate();
    }

    public void setHilighted(final boolean highlighted) {
      this.hilighted = highlighted;
      this.postInvalidate();
    }
  }

  public void requestRender() {
    final OverlayView overlay = (OverlayView) findViewById(R.id.debug_overlay);
    if (overlay != null) {
      overlay.postInvalidate();
    }
  }

  public void addCallback(final OverlayView.DrawCallback callback) {
    final OverlayView overlay = (OverlayView) findViewById(R.id.debug_overlay);
    if (overlay != null) {
      overlay.addCallback(callback);
    }
  }
  
  private class ImageGridAdapter extends BaseAdapter {
    final ImageSlider[] items = new ImageSlider[NUM_STYLES];
    final ArrayList<Button> buttons = new ArrayList<>();

    {
      final Button saveButton =
          new android.support.v7.widget.AppCompatButton(StylizeActivity.this) {
            @Override
            protected void onMeasure(final int widthMeasureSpec, final int heightMeasureSpec) {
              super.onMeasure(widthMeasureSpec, heightMeasureSpec);
              setMeasuredDimension(getMeasuredWidth(), getMeasuredWidth());
            }
          };
      saveButton.setText("save");
      saveButton.setTextSize(12);

      saveButton.setOnClickListener(
          new OnClickListener() {
            @Override
            public void onClick(final View v) {
              if ( test != null) {
                // TODO(andrewharp): Save as jpeg with guaranteed unique filename.
                ImageUtils.saveBitmap(test, "stylized" + url + ".png");
                Toast.makeText(
                        StylizeActivity.this,
                        "Saved image to: /sdcard/tensorflow/" + "stylized" + url + ".png",
                        Toast.LENGTH_LONG)
                    .show();
              }
            }
          });

      buttons.add(saveButton);

      for (int i = 0; i < NUM_STYLES; ++i) {
        LOGGER.v("Creating item %d", i);

        if (items[i] == null) {
          final ImageSlider slider = new ImageSlider(StylizeActivity.this);
          final Bitmap bm =
              getBitmapFromAsset(StylizeActivity.this, "thumbnails/style" + i + ".jpg");
          slider.setImageBitmap(bm);

          items[i] = slider;
        }
      }
    }

    @Override
    public int getCount() {
      return buttons.size() + NUM_STYLES;
    }

    @Override
    public Object getItem(final int position) {
      if (position < buttons.size()) {
        return buttons.get(position);
      } else {
        return items[position - buttons.size()];
      }
    }

    @Override
    public long getItemId(final int position) {
      return getItem(position).hashCode();
    }

    @Override
    public View getView(final int position, final View convertView, final ViewGroup parent) {
      if (convertView != null) {
        return convertView;
      }
      return (View) getItem(position);
    }
  }

  private void setStyle(final ImageSlider slider, final float value) {
    slider.setValue(value);

    if (NORMALIZE_SLIDERS) {
      // Slider vals correspond directly to the input tensor vals, and normalization is visually
      // maintained by remanipulating non-selected sliders.
      float otherSum = 0.0f;

      for (int i = 0; i < NUM_STYLES; ++i) {
        if (adapter.items[i] != slider) {
          otherSum += adapter.items[i].value;
        }
      }

      if (otherSum > 0.0) {
        float highestOtherVal = 0;
        final float factor = otherSum > 0.0f ? (1.0f - value) / otherSum : 0.0f;
        for (int i = 0; i < NUM_STYLES; ++i) {
          final ImageSlider child = adapter.items[i];
          if (child == slider) {
            continue;
          }
          final float newVal = child.value * factor;
          child.setValue(newVal > 0.01f ? newVal : 0.0f);

          if (child.value > highestOtherVal) {
            lastOtherStyle = i;
            highestOtherVal = child.value;
          }
        }
      } else {
        // Everything else is 0, so just pick a suitable slider to push up when the
        // selected one goes down.
        if (adapter.items[lastOtherStyle] == slider) {
          lastOtherStyle = (lastOtherStyle + 1) % NUM_STYLES;
        }
        adapter.items[lastOtherStyle].setValue(1.0f - value);
      }
    }

    final boolean lastAllZero = allZero;
    float sum = 0.0f;
    for (int i = 0; i < NUM_STYLES; ++i) {
      sum += adapter.items[i].value;
    }
    allZero = sum == 0.0f;

    // Now update the values used for the input tensor. If nothing is set, mix in everything
    // equally. Otherwise everything is normalized to sum to 1.0.
    for (int i = 0; i < NUM_STYLES; ++i) {
      styleVals[i] = allZero ? 1.0f / NUM_STYLES : adapter.items[i].value / sum;

      if (lastAllZero != allZero) {
        adapter.items[i].postInvalidate();
      }
    }
  }

public boolean isDebug() {
  return debug;
}

  private void stylizeImage(final Bitmap bitmap) {
    ++frameNum;
    bitmap.getPixels(intValues, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());

    if (DEBUG_MODEL) {
      // Create a white square that steps through a black background 1 pixel per frame.
      final int centerX = (frameNum + bitmap.getWidth() / 2) % bitmap.getWidth();
      final int centerY = bitmap.getHeight() / 2;
      final int squareSize = 10;
      for (int i = 0; i < intValues.length; ++i) {
        final int x = i % bitmap.getWidth();
        final int y = i / bitmap.getHeight();
        final float val =
            Math.abs(x - centerX) < squareSize && Math.abs(y - centerY) < squareSize ? 1.0f : 0.0f;
        floatValues[i * 3] = val;
        floatValues[i * 3 + 1] = val;
        floatValues[i * 3 + 2] = val;
      }
    } else {
      for (int i = 0; i < intValues.length; ++i) {
        final int val = intValues[i];
        floatValues[i * 3] = ((val >> 16) & 0xFF) / 255.0f;
        floatValues[i * 3 + 1] = ((val >> 8) & 0xFF) / 255.0f;
        floatValues[i * 3 + 2] = (val & 0xFF) / 255.0f;
      }
    }

    // Copy the input data into TensorFlow.
    LOGGER.i("Width: %s , Height: %s", bitmap.getWidth(), bitmap.getHeight());
    inferenceInterface.feed(
        INPUT_NODE, floatValues, 1, bitmap.getWidth(), bitmap.getHeight(), 3);
    inferenceInterface.feed(STYLE_NODE, styleVals, NUM_STYLES);
    inferenceInterface.run(new String[] {OUTPUT_NODE}, isDebug());
    inferenceInterface.fetch(OUTPUT_NODE, floatValues);
    for (int i = 0; i < intValues.length; ++i) {
      intValues[i] =
          0xFF000000
              | (((int) (floatValues[i * 3] * 255)) << 16)
              | (((int) (floatValues[i * 3 + 1] * 255)) << 8)
              | ((int) (floatValues[i * 3 + 2] * 255));
    }

    bitmap.setPixels(intValues, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());
  }

public void onSetDebug(final boolean debug) {}
  @Override
  public boolean onKeyDown(int keyCode, KeyEvent event) {
    int moveOffset = 0;
    switch (keyCode) {
      case KeyEvent.KEYCODE_DPAD_LEFT:
        moveOffset = -1;
        break;
      case KeyEvent.KEYCODE_DPAD_RIGHT:
        moveOffset = 1;
        break;
      case KeyEvent.KEYCODE_DPAD_UP:
        moveOffset = -1 * grid.getNumColumns();
        break;
      case KeyEvent.KEYCODE_DPAD_DOWN:
        moveOffset = grid.getNumColumns();
        break;
      default:
        **if (keyCode == KeyEvent.KEYCODE_VOLUME_DOWN || keyCode == KeyEvent.KEYCODE_VOLUME_UP
                || keyCode == KeyEvent.KEYCODE_BUTTON_L1 || keyCode == KeyEvent.KEYCODE_DPAD_CENTER) {
          debug = !debug;
          requestRender();
          onSetDebug(debug);
          return true;
        }**
        return super.onKeyDown(keyCode, event);
    }

    // get the highest selected style
    int currentSelect = 0;
    float highestValue = 0;
    for (int i = 0; i < adapter.getCount(); i++) {
      if (adapter.items[i].value > highestValue) {
        currentSelect = i;
        highestValue = adapter.items[i].value;
      }
    }
    setStyle(adapter.items[(currentSelect + moveOffset + adapter.getCount()) % adapter.getCount()], 1);

    return true;
  }

}
`
I preprocessed the bitmap and resized it to(256,256).But when I touch the grideview ,nothing happend. So I want to know how should I modify it so that it can achieve stylize??

**Comment by GL1920** [comment]
when DEBUG_MODEL = false，it throw this problem [https://github.com/tensorflow/tensorflow/issues/8550](url),but when DEBUG_MODEL = true,it not work.

**Comment by skye** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new). Please provide all the information it asks. Thank you.
