### ISSUE TITLE
Feature Request: Checkpointable slot_variables for AdamOptimizer

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorflow#19442]
When using `tf.train.Checkpoint()` in combination with the `AdamOptimizer` the following error is thrown.

```
load_status.initialize_or_restore(self.session)
  File "/home/lib/python3.5/site-packages/tensorflow/python/training/checkpointable_utils.py", line 677, in initialize_or_restore
    checkpointable_objects = list_objects(self._root_checkpointable)
  File "/home/lib/python3.5/site-packages/tensorflow/python/training/checkpointable_utils.py", line 472, in list_objects
    object_names=object_names)
  File "/home/lib/python3.5/site-packages/tensorflow/python/training/checkpointable_utils.py", line 291, in _serialize_slot_variables
    "A slot variable was re-used as a dependency of a "
NotImplementedError: A slot variable was re-used as a dependency of a Checkpointable object. This is not currently allowed. File a feature request if this limitation bothers you
```

See also: https://github.com/tensorflow/tensorflow/issues/19208

**Comment by allenlavoie** [comment]
Adam works fine in general (there are a bunch of unit tests). Do you have a snipped which reproduces this error?

**Comment by sleighsoft** [comment]
I'll see what I can come up with. It is a lot of code I have

**Comment by allenlavoie** [comment]
Well, from the error something is adding a dependency on one of Adam's slot variables; do you use the output of `optimizer.variables()` somewhere? Or `tf.global_variables()`? Assigning one of those to an attribute could add the dependency.

**Comment by sleighsoft** [comment]
Why could a `slot_variable` be in `node_ids`?

**Comment by allenlavoie** [comment]
To clarify, it works if you take out this bit?

```
    for var in self.optimizer.variables():
      print('Adding {}'.format(var.name))
      setattr(self, var.name, var)
```

I don't see the purpose of that. There's already a dependency on the optimizer, right? Is this so they'll show up in `model.variables`?

**Comment by sleighsoft** [comment]
I think I just hacked around the problem of not having lists of checkpointables be supported. I wanted to build a solution that did not require me to change model code. But I now see, that my shot at it backfired.

**Comment by allenlavoie** [comment]
Checkpointable data structures are coming. We're just ~~arguing over~~ working on a few final details.
