### ISSUE TITLE
TF failing to build on Bazel CI

### ISSUE THREAD

**Issue by katre** [tensorflow/tensorflow#19464]
See logs at https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/246#a2654e2b-dbaf-4c4b-909f-1dfd16b7fe7a

The underlying error is:
```
ERROR: /usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/30de07a0c21303385c48fed63725bc15/external/grpc/BUILD:1300:1: C++ compilation of rule '@grpc//:grpc_resolver_dns_ares' failed (Exit 1)
external/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc:30:10: fatal error: ares.h: No such file or directory
 #include <ares.h>
          ^~~~~~~~
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

I can't determine why ares.h cannot be found. The generated .tf_configure.bazelrc contains the line:
```
build --define grpc_no_ares=true
```

**Comment by katre** [comment]
Apparently this was a bug in the Bazel CI system. My apologies.

**Comment by daniziz** [comment]
How did you solved it?

**Comment by katre** [comment]
The problem I had was a flake in our CI system. If you are seeing something similar I am afraid I don't have any advice.

**Comment by daniziz** [comment]
I had same issue, solved it by:

apt-get install libc-ares-dev

**Comment by psn9** [comment]
@NorwayLobster whats the error message thats being thrown ?

**Comment by NorwayLobster** [comment]
> @NorwayLobster whats the error message thats being thrown ?
it has been a too long time, honestly, i forgot.

**Comment by NorwayLobster** [comment]
sorry, it has been a too long time, honestly, I forgot. @psn9

**Comment by haslo** [comment]
I had this problem here, fixed it by installing `libc-ares-dev`, then ran into #23402 which was fixable with https://github.com/tensorflow/tensorflow/issues/23402#issuecomment-436932197. Thanks to everybody involved for fixing things when they break!

**Comment by jiakai0419** [comment]
> i use mac,when i use commad brew install libc-ares-dev,the error message is Error: No available formula with the name "libc-ares-dev",how to solve it ?3q

brew install c-ares

**Comment by drscotthawley** [comment]
@jiakai0419 
> brew install c-ares

This had no effect.  Error persists on Mac. 

"Warning: c-ares 1.15.0 is already installed and up-to-date"
