### ISSUE TITLE
NHWC convolution sometimes incorrectly considered NCHW

### ISSUE THREAD

**Issue by tdanyluk** [tensorflow/tensorflow#19497]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**:  3.5.2
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:  9.0.176 / 7.0.5
- **GPU model and memory**: GeForce GTX 1050 Ti/PCIe/SSE2 4GB
- **Exact command to reproduce**: custom script

### Describe the problem
When using dilated conv2d and bias_add, the conv2d is incorrectly considered NCHW, so the normal dilation format is not accepted. Strangely when there is no bias_add, the problem does not happen.

### Source code / logs
This gives ERROR:
```
import tensorflow as tf 
import numpy as np

def test_add_conv_transform1():
    input_ = tf.placeholder(tf.float32, shape=[1, 64, 64, 3], name="input")
    filter_ = tf.get_variable(dtype=tf.float32, shape=[4, 4, 3, 16], name="filter")
    
    conv = tf.nn.conv2d(input_, filter_, strides=[1, 1, 1, 1], padding='VALID', dilations=[1, 4, 4, 1])

    bias1 = tf.get_variable(name='bias', shape=[16], dtype=tf.float32)
    return tf.nn.bias_add(conv, bias1)
        
o = test_add_conv_transform1()
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    sess.run(o, {"input:0": np.random.random([1, 64, 64, 3])})
```

tensorflow.python.framework.errors_impl.InvalidArgumentError: Current implementation does not yet support dilations in the batch and depth dimensions.
         [[Node: Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 4, 4, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, filter/read)]]

Interestingly this works as intended:
```
import tensorflow as tf 
import numpy as np

def test_add_conv_transform1():
    input_ = tf.placeholder(tf.float32, shape=[1, 64, 64, 3], name="input")
    filter_ = tf.get_variable(dtype=tf.float32, shape=[4, 4, 3, 16], name="filter")

    return tf.nn.conv2d(input_, filter_, strides=[1, 1, 1, 1], padding='VALID', dilations=[1, 4, 4, 1])
        
o = test_add_conv_transform1()
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    sess.run(o, {"input:0": np.random.random([1, 64, 64, 3])})
```

**Comment by yongtang** [comment]
I tried with v1.8.0 and it works fine. Maybe the issue has been resolved?

**Comment by tdanyluk** [comment]
Hi! Thanks for trying! I'll check out the 1.8 version tomorrow at work, and then confirm the results to you. Cheers

**Comment by tdanyluk** [comment]
It is fixed in 1.8. Thank you.

**Comment by tdanyluk** [comment]
It was good only in tf 1.8 CPU version, but in the GPU version it is till erroneous. 
@yongtang  please confirm

**Comment by tatianashp** [comment]
@zheng-xq Can you take a look?

**Comment by zheng-xq** [comment]
This seems to be a layout optimizer issue. Adding Yao.

**Comment by zhangyaobit** [comment]
Thanks for reporting the bug. I have submitted a fix, which will be pushed to TensorFlow github and reflected in nightly build in a day or two; it will also be part of the next release.

More info on nightly build: https://github.com/tensorflow/tensorflow/

**Comment by samzoozi** [comment]
Hi, I am also using 1.7 version and facing the same issue. Is there any fix for it?
