### ISSUE TITLE
Segfault with rpc ops in eager mode

### ISSUE THREAD

**Issue by arogozhnikov** [tensorflow/tensorflow#19496]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary, pip
- **TensorFlow version (use command below)**: 1.8
- **Python version**:  3.6
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: see below

### Describe the problem

Rpc ops (`rpc`, `try_rpc`)  are not working in eager mode. See minimal examples below.

### Source code / logs

Non-eager version works

```python
import tensorflow as tf
from tensorflow.contrib.rpc.python.ops.gen_rpc_op import try_rpc

with tf.Graph().as_default():
    response = try_rpc('localhost:80', '/Test', 'some simple message', protocol='grpc')
    session = tf.InteractiveSession()
    print( session.run([response], feed_dict={}) )
```
Eager version does not (results in segfault):
```python
import tensorflow as tf
from tensorflow.contrib.rpc.python.ops.gen_rpc_op import try_rpc
tf.enable_eager_execution()
response = try_rpc('localhost:80', '/Test', 'some simple message', protocol='grpc')
```

**Comment by asimshankar** [comment]
@jsimsa : Mind taking a look?

**Comment by jsimsa** [comment]
will do

**Comment by jsimsa** [comment]
This was just fixed internally and will be push to github in the next sync.
