### ISSUE TITLE
tf.data.Dataset iterators are not cleaned when the loop ends with a break

### ISSUE THREAD

**Issue by LionelCons** [tensorflow/tensorflow#19499]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:CentOS7
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.8.0
- **Python version**: 2.7.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
tf.data.Dataset iterators are not cleaned when the loop ends with a `break`.

The code below opens one file per epoch. This eventually hits a system limit (maximum number of open files).

Replacing the `break` by a `continue` works better since the files are closed. However, this is inefficient if we only need to iterate over a small fraction of the data

### Source code / logs
```
dataset = tf.data.TextLineDataset(fp)
...
for epoch in xrange(epochs):
    ...
    batches = 0
    for (x, y) in dataset:
        batches += 1
        if batches > MAX_BATCHES:
            break
        ...
```

**Comment by mrry** [comment]
@allenlavoie It looks like you've done something related to Eager resource garbage collection in 309e340619ab922f1ecb51b8f142283e09bda07d, and this is still used in the current `iterator_ops.EagerIterator`:

https://github.com/tensorflow/tensorflow/blob/2c9d129cb8f6e3f6a27d074664033e4fccd83a63/tensorflow/python/data/ops/iterator_ops.py#L480-L482

Can you please take a look and see if there's a reference leak here?

**Comment by allenlavoie** [comment]
There is a reference leak, but I don't think it's in Python. DestroyResourceOp gets run and Unrefs the resource, but it looks like IteratorHandleOp is [keeping a reference to the resource in its OpKernel](https://github.com/tensorflow/tensorflow/blob/f8b74d642420dcf2f5cab763b41884a05777ea45/tensorflow/core/kernels/data/iterator_ops.cc#L510). AFAIK kernels are never deleted when executing eagerly, they just sit around in the kernel cache.

I've verified that removing the reference from IteratorHandleOp fixes the "files not closed" issue (they get closed when DestroyResourceOp runs). I can think of horrible hacks to get this to happen only when executing eagerly, but maybe we should discuss tomorrow.

**Comment by mrry** [comment]
Ugh, yes, whatever we do to that kernel implementation, the current version will still leak the `OpKernel` object and related guff for each iterator. As a strawman, we could solve it with (i) a new version of `IteratorHandleOp` that creates the handle doesn't retain a resource, and (ii) some API for creating-and-running-but-not-caching a kernel in eager mode. (CCing @asimshankar since kernel lifetimes in eager is something we've talked about in the past.)

@LionelCons In the meantime, here's a workaround that should alleviate the file handle leak:

```python
dataset = tf.data.TextLineDataset(fp)
# ...
for epoch in xrange(epochs):
  # ...
  for (x, y) in dataset.take(MAX_BATCHES):
    # ...
```
