### ISSUE TITLE
How to get the output of a layer when making predictions?

### ISSUE THREAD

**Issue by universewill** [tensorflow/tensorflow#19493]
My code is something like this:
```
        from tensorflow.contrib.layers import fully_connected

        hidden1 = fully_connected(train_inputs, hidden[0], scope="hidden1") 
        hidden2 = fully_connected(hidden1, hidden[1], scope="hidden2")
        u = fully_connected(hidden2, hidden[2], scope="u")

        loss = tf.reduce_mean(
            tf.nn.sampled_softmax_loss(
                weights=nce_weights,
                biases=nce_biases,
                labels=train_labels,
                inputs=u,
                num_sampled=sample_num,
                num_classes=class_num,
                remove_accidental_hits=True),
            name='loss')
```

After training, i loaded the model and make predictions for my data. I want to get the 'u' scope layer output in the net as output. How can i achieve that?
Notice that 'u' is a scope define, so i can not just use sess.run(['u:0'])

I load the model as follows:
```
    sess = tf.Session()
    saver = tf.train.import_meta_graph(meta_path)
    saver.restore(sess, model_path)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
