### ISSUE TITLE
Tensorflow Lite Python Interpreter Crashes

### ISSUE THREAD

**Issue by nimatter** [tensorflow/tensorflow#19505]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: b'v1.8.0-2191-gc36266e' 1.8.0
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: 0.13
- **GCC/Compiler version (if compiling from source)**: c++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
mkvirtualenv tf -p /usr/bin/python3
git clone https://github.com/tensorflow/tensorflow
cd tensorflow
git checkout 4dbaa65
./configure
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
cd ~
pip install /tmp/tensorflow_pkg/tensorflow-1.8.0-cp35-cp35m-linux_x86_64.whl
wget http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz
tar -zxf mobilenet_v1_1.0_224.tgz
python
> import tensorflow as tf
> a = tf.contrib.lite.Interpreter('mobilenet_v1_1.0_224.tflite')
> a.allocate_tensors()
> a.get_input_details()
Segmentation fault (core dumped)

### Describe the problem
Segmentation fault when running the tflite python interpreter.  The Interpreter initializes and allocate_tensors() runs, but other commands result in segfault.

Is the python tflite interface only intended for ARM systems, or should it run on x64 as well?  (I'm running on x64).

**Comment by parvizp** [comment]
I'm not sure of a proper fix but adding a call to `tensorflow::ImportNumpy();` in this function https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L111 seems to work.

**Comment by gargn** [comment]
The fix noted by @parvizp is correct. It has been fixed internally and should be fixed externally next week.

**Comment by nimatter** [comment]
Great, fixed it for me!
Thanks!
