### ISSUE TITLE
tf.gather doesn't support SparseTensors as an input

### ISSUE THREAD

**Issue by Remper** [tensorflow/tensorflow#1950]
As the code in ```tf.nn.embedding_lookup``` suggests, there were attempts in 0.8 to make it accept SparseTensors, but then everything funnels into ```tf.gather``` that tries to convert SparseTensor to Tensor and fails.

Is it a correct behaviour or is it a bug? If not, is there any workaround to achieve the same effect (get some of the rows of a SparseTensor based on a index list)? Otherwise, SparseTensors are close to being completely unusable.

### Environment info
Operating System: OS X 10.10.5
TensorFlow version: 0.8.0rc0

### Log:
```
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 566, in gather
    validate_indices=validate_indices, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 411, in apply_op
    as_ref=input_arg.is_ref)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 390, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/util/compat.py", line 44, in as_bytes
    raise TypeError('Expected binary or unicode string, got %r' % bytes_or_text)
TypeError: Expected binary or unicode string, got <tensorflow.python.framework.ops.SparseTensor object at 0x103dbc350>
```

**Comment by concretevitamin** [comment]
Thanks for reporting this @Remper.  Could you clarify a bit on your use cases:

1) Do you want to gather based on indices to the *first* dimension only?  Or do you want to gather by all coordinates (i.e., similar to `gather_nd()`)?

2) How do you intend to use the gathered results?  Do you want them to form a new dense Tensor, or remain a SparseTensor with the original shape?

**Comment by Remper** [comment]
@concretevitamin 

1) For my usecase I only need to gather by the first dimension
2) If ```tf.boolean_mask``` would support SparseTensor as well, then it is much better to have SparseTensor as a result, but a new dense Tensor is fine too, since I don't need to select many rows at once.
Basically, the idea is that I have a huge square matrix (5m by 5m) of booleans and I want to select a batch of rows at every iteration, which then are used as masks. Each row contains at most 400 values and SparseTensor is exactly what I need. I can do it on python side and feed it along with other input, but this solution is much cleaner.

Thank you for the quick response!

**Comment by girving** [comment]
@Remper: What would the implementation look like?  I'm having trouble seeing how to make this not terrifyingly slow.  I suppose you could do binary search to find the matching sparse indices?

**Comment by Remper** [comment]
@girving ideally I would expect an explicit (via the separate op) or an implicit (when the SparseTensor is populated with data at runtime) way to build an index across the first dimension (or any given dimension). Then ```tf.gather``` would be just a search on that index.

Going back to my original use case: originally I've needed to represent a dictionary that contained arrays of elements of varying size. I ended up using ```tf.py_func```, but the performance isn't good this way. But for sure traversing all possible values in the SparseTensor of my size and filtering matches without any index would be even slower.

**Comment by girving** [comment]
@ysuematsu This seems hashtable related.  Can we do this with existing int -> int hashtable ops?

**Comment by girving** [comment]
@michaelisard I don't think we know a way to do this that isn't very slow, but it's hard to know since @ysuematsu apparently didn't notice my question.  If it's possible to do this in a clean and fast fashion we could mark it contributions welcome, but otherwise it should be closed.

**Comment by ysuematsu** [comment]
Right now, The current hashtable op does a mapping of id to single value, it could be extended to support id -> tensor, but the restriction will be that all tensors should have the same shape.

**Comment by ysuematsu** [comment]
About the original question related to embedding_lookup. It expects to pass a tensor of ids. If you have a SparseTensor that contains ids in the value part, you can just use embedding_lookup with my_sparse_tensor.values

There is a embedding_lookup_sparse that expects sparse tensors, but it will aggregate the embedding for the same 1st-dimension of the indices, and possibly this is not what you want.

**Comment by girving** [comment]
Thanks @ysuematsu for commenting.  Let's close this for now, since I think efficient gather on sparse tensors is infeasible without quite a lot of work.

**Comment by zacwellmer** [comment]
Is there still no plans for this? Having a way to use gather_nd or gather on SparseTensors would be awesome

**Comment by nicktasios** [comment]
Yes, I also have an application for this. Basically I use `tf.where` to get a list of coordinates of filled voxels and thenI ravel_multi_index the result and use a sparse matrix as a dictionary to index the filled voxels using the coordinates.
