### ISSUE TITLE
TOCO Quantized InceptionV3 Error: "tensorflow/contrib/lite/kernels/pooling.cc:116 input->params.scale != output->params.scale"

### ISSUE THREAD

**Issue by parvizp** [tensorflow/tensorflow#19503]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Minor custom code for quantization but using provided InceptionV3 checkpoints and models/research/slim scripts.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.10
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: ('v1.8.0-2169-gb84878e63e', '1.8.0')
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.12.0
- **GCC/Compiler version (if compiling from source)**: gcc version 7.2.0
- **CUDA/cuDNN version**: 9.1/7.1.3
- **GPU model and memory**: NVIDIA P40 (24 GB)
- **Exact command to reproduce**: I link to my script on GitHub below.

### Describe the problem
I've been trying to produce a quantized InceptionV3 model since one is not provided (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/models.md) but it currently fails in the `label_image` demo application due to a MaxPool that has different input/output quantization ranges.

In this TensorFlow Lite announcement video, quantized InceptionV3 is shown to be ~3x faster than floating point (https://youtu.be/FAMfy7izB6A?t=8m40s), so I thought it might work "out of the box".
Additionally, in this Google quantization paper the accuracy is shown to be fairly high (https://arxiv.org/abs/1712.05877), which is pretty motivating. 

### Source code / logs
I have a branch of `tensorflow/models` with very minor changes to support quantization: https://github.com/parvizp/models/tree/quantize
You can run the whole script to see the training, TOCO call and call to `label_image`: https://github.com/parvizp/models/blob/279e458ac99da67e405ac74bc5e4583d5111c1bb/research/slim/scripts/quantize_inception_v3_on_imagenet.sh
```
INFO: Running command line: bazel-bin/tensorflow/contrib/lite/examples/label_image/label_image '--tflite_model=/tmp/imagenet-models/inception_v3/inception_v3.quantized.tflite' '--image=/tmp/tensorflow/tensorflow/contrib/lite/examples/label_image/testdata/grace_hopper.bmp' '--labels=/tmp/imagenet/labels.txt'
nnapi error: unable to open library libneuralnetworks.so
Loaded model /tmp/imagenet-models/inception_v3/inception_v3.quantized.tflite
resolved reporter
tensorflow/contrib/lite/kernels/pooling.cc:116 input->params.scale != output->params.scale (-1454358704 != 734155808)
Failed to allocate tensors!
```
The error seems to stem from this MaxPool in the center of:
<img width="850" alt="inception_v3 quantized maxpool-issue" src="https://user-images.githubusercontent.com/926261/40436998-d7f6ff38-5e79-11e8-9b1e-6e65f2f20ec9.png">
To reach the accuracy reported in (https://arxiv.org/abs/1712.05877) should we:
- Add support for TF-Lite MaxPool kernel so it can perform requantization as needed (i.e. for this case)?
- Make TOCO nudge the ranges so all things forking from the cancat and joining have the same range? Could also make the graph re-writer emulate this with shared ranges? 

Seems to preserve more precision and easier to do the first option. I'm happy to provide a patch if you can provide some insight into which direction to pursue.

**Comment by parvizp** [comment]
@suharshs Should the current version of TOCO/TF-Lite be able to quantize vanilla InceptionV3?

**Comment by suharshs** [comment]
Hi @parvizp ,

This was a recent issue we found and fixed. The issue has to do with TOCO trying to guarantee that the input and output scales of Concatentation operations match, which stomps on other guarantees TOCO tries to make. This should be resolved by providing `--change_concat_input_ranges=false` to your commandline TOCO invocation.

We plan to make this default to false soon, but were worried about breaking users that may rely on that feature.

Thanks!
-Suharsh

**Comment by parvizp** [comment]
Thanks @suharshs !
