### ISSUE TITLE
Eager metrics not saving as summaries

### ISSUE THREAD

**Issue by Threynaud** [tensorflow/tensorflow#19507]
I am writing a piece of tf.eager code on the Iris dataset and I'm facing issues when trying to save `Mean` and `Accuracy` as summaries. Here is the piece of code I am using:
```
def evaluate(model, iterator, logdir=None):
    avg_loss = tfe.metrics.Mean('loss')
    accuracy = tfe.metrics.Accuracy('accuracy')

    for inputs, labels in iterator:
        avg_loss(sce(model, inputs, labels))
        accuracy(tf.argmax(model(inputs), axis=1, output_type=tf.int64),
                 tf.argmax(labels, axis=1))
    print(f"Dev set: Average loss: {avg_loss.result()},\
    Accuracy: {100 * accuracy.result()}\n")
    with tf.contrib.summary.always_record_summaries():
        tf.contrib.summary.scalar('loss', avg_loss.result())
        tf.contrib.summary.scalar('accuracy', accuracy.result())
```

This is almost a copy from the MNIST Eager tutorial (line 82).
The print statement is working great but when it gets into the `with` block I get:
```
File "./iris.py", line 131, in train_iris_model
    logdir=logdir, summary_freq=summary_freq)
  File "./iris.py", line 98, in fit
    evaluate(model, dev_iterator, logdir=logdir)
  File "./iris.py", line 61, in evaluate
    Accuracy: {100 * accuracy.result()}\n")
  File "/Users/thms/.virtualenvs/unbabel3/lib/python3.6/site-packages/tensorflow/contrib/eager/python/metrics_impl.py", line 341, in result
    t = self.numer / self.denom
AttributeError: 'Mean' object has no attribute 'numer'
```

If I understand correctly it means that is is trying to call `.result()` on an unitialized `Mean` object but I don't get why. Is this normal behaviour?

Full code can be found [here](https://github.com/Threynaud/tf-deep-learning/blob/master/tensorflow/tf-eager/iris/iris.py) and run with `./iris.py`

------------------------
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS High Sierra
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.8
- **Python version**: 3.6.5

**Comment by mikeyrayvon** [comment]
@Threynaud did you find a solution for this? I'm experiencing the same error.

**Comment by p3jgr** [comment]
I am experiencing the same error too. Was it closed with no solution?

**Comment by Threynaud** [comment]
Hi! I completely forgot to share the solution, very sorry for that. It seems like you need to use `tf.contrib.metrics` instead of `tf.metrics` which doesn't support eager execution correctly for some reason... It worked for me at least, tell me if it solves your problem as well!

**Comment by p3jgr** [comment]
No, it did not help. I got the following error:

AttributeError: module 'tensorflow.contrib.metrics' has no attribute 'Mean'

**Comment by Moxank6277** [comment]
> Hi! I completely forgot to share the solution, very sorry for that. It seems like you need to use `tf.contrib.metrics` instead of `tf.metrics` which doesn't support eager execution correctly for some reason... It worked for me at least, tell me if it solves your problem as well!

I had the same problem.
SOLUTION:
Check the iterator in for loop,
it may not be initialized and no value would be appended to metrics,
causing error.
