### ISSUE TITLE
Running graph in C++

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#1951]
After reading #615 and the related StackOverflow [question](http://stackoverflow.com/questions/35508866/tensorflow-different-ways-to-export-and-run-graph-in-c) (which only has one, unsatisfactory answer) I'd like to know what the right way to do this is. Writing a ```MetaGraphDef``` proto seems like it would be more convenient than running the freeze_graph python script, but I'm not sure how to read the ```MetaGraphDef``` with the C++ Session API.

**Comment by vladfi1** [comment]
I've figured out a nice solution: call ```tensorflow.python.client.graph_util.convert_variables_to_constants``` to create a ```graph_def``` containing only the subgraph necessary for execution and with the relevant variables replaced by constants, and then pass this to ```tensorflow.train.write_graph``` instead of [the current session's] ```sess.graph_def```.

This should probably be documented somewhere! I searched pretty hard, and it was only when I read the source code of ```python/tools/freeze_graph.py``` (which itself was not in any documentation) that I found out that this function existed.

**Comment by peci1** [comment]
I got it working quite nicely today: http://stackoverflow.com/a/43639305/1076564
