### ISSUE TITLE
Bug: About tf.Variable and tf.get_variable

### ISSUE THREAD

**Issue by geweihgg** [tensorflow/tensorflow#19514]
Hi,
    I have a question about tf.Variable and tf.get_variable, it seems that the tf.get_variable cannot share the variables defined by tf.Variable.
    My test code is like this:

```
#! /usr/bin/python
import tensorflow as tf
def main():
	with tf.variable_scope("scope_1"):
		v1 = tf.Variable([1], name="v1", dtype=tf.float32)
	print v1
	with tf.variable_scope("scope_1", reuse=True):
		v2 = tf.get_variable("v1", [1])
        print v2
if __name__ == "__main__":
	main()
```

    The output:

![2018-05-24 10 18 55](https://user-images.githubusercontent.com/18585014/40461001-e46e7094-5f3b-11e8-952b-1656c40ddf03.png)
    Um..., from the first terminal output line, we can see that there exists a variable named "scope_1/v1:0", but tf.get_variable still can't find the variable? So, I'm confused about this.
    Can you help me?
    Thank you very much.
    GeWei

**Comment by achalshah20** [comment]
Just execute below code and you will understand that both of the below lines create variables under different name. v1:0, v1_1:0.

v1 = tf.Variable([1], name="v1", dtype=tf.float32)
v2 = tf.get_variable("v1", [1], dtype=tf.float32)

**Comment by geweihgg** [comment]
Hi, @achalshah20,
    Thank you for your reply.
    I've tested something like this:
```
v1 = tf.get_variable("v1", [1], dtype=tf.float32)
```
    Then I got v1 as "v1:0", and I opened a new terminal, input some code:
```
v1 = tf.Variable([1], name="v1", dtype=tf.float32)
```
    I got the same output "v1:0". So I think, when you input the two lines of codes below, v2  really knows that "v1:0" exists, so v2 renames itself as "v1_1:0".
```
v1 = tf.Variable([1], name="v1", dtype=tf.float32)
v2 = tf.get_variable("v1", [1], dtype=tf.float32)
```
    If I input these two lines of codes, I will get the "v1 already exists" Error.
```
v1 = tf.get_variable("v1", [1], dtype=tf.float32)
v2 = tf.get_variable("v1", [1], dtype=tf.float32)
```
    Um...it confuses me.
GeWei

**Comment by facaiy** [comment]
@geweihgg Could you explain why you need to mix them? I think it's always recommend to use `tf.get_variable` only, and official document [Sharing variables](https://www.tensorflow.org/programmers_guide/variables#sharing_variables) might be useful for you.

**Comment by geweihgg** [comment]
Hi, @facaiy ,
    I have no need to mix them, but just feel puzzled at this phenomenon~
    Thank you for your recommendation, I'll learn this document further~
GeWei

**Comment by achalshah20** [comment]
https://stackoverflow.com/questions/45074049/tensorflow-how-does-tf-get-variable-work

> The variables created with tf.Variable can't be shared,

**Comment by geweihgg** [comment]
Hi, @achalshah20 ,
    Thank you very much!
    So the tf.Variable is designed just for creating new variables, which brings benefits to writing the libraries. Then we users can recreate as much layers as we can, just using one line of code like this:
```
net = fully_connected(input_tensor, shape)
```
    Ok, thank you again~
GeWei

**Comment by aselle** [comment]
As was discussed, this is working as intended. Further discussion is recommended to be done on stackoverflow.
