### ISSUE TITLE
Windows can't build toco library by bazel (bazel build //tensorflow/contrib/lite/toco:toco)

### ISSUE THREAD

**Issue by az507929Jason** [tensorflow/tensorflow#19516]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: I user command (pip install tensorflow)
- **TensorFlow version (use command below)**: Version: 1.7.1
- **Python version**:  Python 3.6.4 :: Anaconda
- **Bazel version (if compiling from source)**:  Build label: 0.13.0
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:  bazel build //tensorflow/contrib/lite/toco:toco

### Describe the problem
I am trying to run the command "toco --help" for tensorflow lite. 
but I get the error ModuleNotFoundError: No module named 'tensorflow.contrib.lite.toco.python'.
so I'm going to build the toco library , when I run the command "bazel build tensorflow/contrib/lite/toco:toco" I get the error "**ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package** ".

### Source code / logs
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': Error downloading 
[https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/dbb96841cc0a5fb2664c37822803b06dab20c7d1.tar.gz,
https://github.com/bazelbuild/rules_closure/archive/dbb96841cc0a5fb2664c37822803b06dab20c7d1.tar.gz] to C:/users/XXXX/_bazel_XXXX/pqfcltl7/external/io_bazel_rules_closure/dbb96841cc0a5fb2664c37822803b06dab20c7d1.tar.gz: All mirrors are down: []
INFO: Elapsed time: 57.492s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by gunan** [comment]
This just looks like a download error. Did you retry downloading?
Closing because the mirrors are live, and this issue is a connection issue.

**Comment by az507929Jason** [comment]
@gunan  thanks your response. I retried downloading but it's same problem :(

**Comment by az507929Jason** [comment]
@gunan thanks your response :) . I have downloaded the two files, and then I merge and move them to [C:/users/XXXX/_bazel_XXXX/pqfcltl7/external/io_bazel_rules_closure]  finally I execute [bazel build //tensorflow/contrib/lite/toco:toco]  instruction, but it also show same error.

do you have facebook or other social account?, could I make friend with you? :)
