### ISSUE TITLE
How to use grap_transfroms tools?

### ISSUE THREAD

**Issue by GustavZ** [tensorflow/tensorflow#19525]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes and No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04)
- **TensorFlow installed from (source or binary)**: Source 
- **TensorFlow version (use command below)**: 1.7
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: 0.13.0
- **GCC/Compiler version (if compiling from source)**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- **CUDA/cuDNN version**: 9 / 7
- **GPU model and memory**: 4GB GTX 1050
- **Exact command to reproduce**:

I want to use the graph_transforms tools but i dont know how to use them correctly:

As far as i know you have to run the commands like
```
bazel build tensorflow/tools/graph_transforms:summarize_graph
bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=tensorflow_inception_graph.pb
```
from inside the cloned tensorflow repo from which you successfull build tf from source.

But then i see errors like:
```
ERROR: /home/gustav/.cache/bazel/_bazel_gustav/0efb90387e9af20adf0714a85702521f/external/jpeg/BUILD:126:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:
@jpeg//:k8
@jpeg//:armeabi-v7a
Multiple matches are not allowed unless one is unambiguously more specialized.
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'PACKAGE:tensorflow/core/kernels' (requested by nodes '//tensorflow:libtensorflow_framework.so com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@fedf386b false (700629378)', '//tensorflow/core:framework_internal_headers_lib_gather com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@fedf386b false (744921750)')

```
and
```
FAILED: Build did NOT complete successfully (33 packages loaded)
    currently loading: tensorflow/core/kernels ... (3 packages)
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:tensorflow/core/kernels' (requested by nodes '//tensorflow:libtensorflow_framework.so com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@fedf386b false (700629378)', '//tensorflow/core:framework_internal_headers_lib_gather com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@fedf386b false (744921750)')

```

**Comment by GustavZ** [comment]
Pulling tensorflow v1.8.0 seems to solve this problem (i previously had v.1.7.0)

**Comment by sungwonida** [comment]
In my case, the bazel version was the problem. 
With bazel `0.25.2` and `0.24.1`, lots of `FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false` has been introduced.
Thus I downgraded the bazel once more, to `0.21.0`, and graph_transfroms began to build.

Summary: 
TensorFlow: `1.13.1`
Bazel: `0.21.0`
