### ISSUE TITLE
[TFlite] unable to bazel build tensorflow/contrib/lite/toco:toco

### ISSUE THREAD

**Issue by GustavZ** [tensorflow/tensorflow#19521]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes and No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04)
- **TensorFlow installed from (source or binary)**: Source 
- **TensorFlow version (use command below)**: 1.7
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: 0.13.0
- **GCC/Compiler version (if compiling from source)**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- **CUDA/cuDNN version**: 9 / 7
- **GPU model and memory**: 4GB GTX 1050
- **Exact command to reproduce**:

i trained a mask r-cnn model with mobilenet as backbone and i try to quantize it according to this guide: https://www.tensorflow.org/performance/quantization 

My code looks like this:
```
MODEL_NAME="mask_rcnn_mobilenet_v1_400_coco_117k"

INPUT_FILE="models/${MODEL_NAME}/frozen_inference_graph.pb"
OUTPUT_FILE="models/${MODEL_NAME}/frozen_inference_graph.tflite"
INPUT_SHAPE="1,400,400,3"
INPUT_ARRAY=['image_tensor']
OUTPUT_ARRAY=['num_detections','detection_boxes','detection_scores','detection_classes','detection_masks']
STD_VALUE=127.5
MEAN_VALUE=127.5


bazel build tensorflow/contrib/lite/toco:toco && \
  ./bazel-bin/third_party/tensorflow/contrib/lite/toco/toco \
  --input_file=${INPUT_FILE} \
  --output_file=${OUTPU_FILE} \
  --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE \
  --inference_type=QUANTIZED_UINT8 \
  --input_shape=${INPUT_SHAPE} \
  --input_array=${INPUT_ARRAY} \
  --output_array=${OUTPUT_ARRAY} \
  --std_value=${STD_VALUE} --mean_value=${MEAN_VALUE}
```
and this error i get:
```
ERROR: Skipping 'tensorflow/contrib/lite/toco:toco': no such package 'tensorflow/contrib/lite/toco': BUILD file not found on package path
WARNING: Target pattern parsing failed.
ERROR: no such package 'tensorflow/contrib/lite/toco': BUILD file not found on package path
INFO: Elapsed time: 1.132s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Another thing i don't understand is that when i try to run this code in my custom model folder i see this error:
`ERROR: The 'build' command is only supported from within a workspace.`

What is this supposed to mean?

So i tried it in the tensorflow/models

**Comment by GustavZ** [comment]
https://github.com/tensorflow/tensorflow/issues/19525

**Comment by rorlich** [comment]
i'm using 1.8.0 and having same issue

**Comment by duyanfang123** [comment]
> 
> 
> Perhaps add 'exports_files(["toco"])' to tensorflow/contrib/lite/BUILD

why add this ? I have got a same probilem such as GuatavZ ,what should I do ?

**Comment by defaultUser3214** [comment]
No, it appears in the current master version as well if you execute (from https://github.com/tensorflow/tensorflow/issues/15633 )

# Strip out problematic nodes before even letting TOCO see the graphdef
bazel run -c opt tensorflow/python/tools/optimize_for_inference -- \
--input=$DETECT_PB  --output=$STRIPPED_PB --frozen_graph=True \
--input_names=Preprocessor/sub --output_names=concat,concat_1 \
--alsologtostderr

# Run TOCO conversion.
bazel run tensorflow/contrib/lite/toco:toco -- \
--input_file=$STRIPPED_PB --output_file=$DETECT_FB \
--input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE \
--input_shapes=1,300,300,3 --input_arrays=Preprocessor/sub \
--output_arrays=concat,concat_1 --inference_type=FLOAT --logtostderr

**Comment by KapoorHitesh** [comment]
The toco target has been moved from //tensorflow/contrib/lite/toco to //tensorflow/lite/toco

**Comment by yixunzhou** [comment]
> The toco target has been moved from //tensorflow/contrib/lite/toco to //tensorflow/lite/toco

useful comment. thank you
