### ISSUE TITLE
TensorRT: Invalid graph after calibration -> inference graph transformation

### ISSUE THREAD

**Issue by yegord** [tensorflow/tensorflow#19535]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
Source.
- **TensorFlow version (use command below)**:
1.8
- **Python version**: 
2.7.12
- **Bazel version (if compiling from source)**:
0.13.0
- **GCC/Compiler version (if compiling from source)**:
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
- **CUDA/cuDNN version**:
9.0.176/7.0.5.15
- **GPU model and memory**:
1080 Ti
- **Exact command to reproduce**:

### Describe the problem

It seems that `tf.contrib.tensorrt` may incorrectly redirect edges when transforming an INT8 calibration node into an engine node. The current implementation, for each output node, searches the first edge from this output node [1] and redirects only this edge to point from the newly created engine node [2]. If the output node has multiple outgoing edges, then only the first one is redirected, and the remaining edges still use the output node as the source. As a result, after the output node is deleted, the graph becomes invalid and the graphdef generated by `tf.contrib.tensorrt.calib_graph_to_infer_graph` cannot be loaded (e.g., using `TF_GraphImportGraphDef`) due to errors like this: `Node 'Shape_4': Unknown input node 'group1/block1/Relu'`. (In this case, `group1/block1/Relu` had two edges in the original graph: to some convolution node and to `Shape_4`; the first edge was updated, the second one was not and caused the error.)

[1] https://github.com/tensorflow/tensorflow/blob/717aa746e7e915cba9ce36df424d05642fbe8cd7/tensorflow/contrib/tensorrt/convert/convert_nodes.cc#L2191
[2] https://github.com/tensorflow/tensorflow/blob/717aa746e7e915cba9ce36df424d05642fbe8cd7/tensorflow/contrib/tensorrt/convert/convert_nodes.cc#L2258

**Comment by jjsjann123** [comment]
We have found this problem in our unit tests. We'll be working on it and push fix to master.
Would update this thread as well.

Thanks,
J

**Comment by samikama** [comment]
PR #19652 should fix this
