### ISSUE TITLE
Export GRPC symbols along with the C API

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/tensorflow#19549]
Hi,

Given the recent changes to the eager API, that requires GRPC, the eager API cannot be used by external libraries, because it cannot link to the GRPC symbols in TensorFlow. A possible solution is to add `*grpc*` to the C API version script. @asimshankar @alextp is it ok if I make a PR to add that?

Thanks,
Anthony

**Comment by asimshankar** [comment]
@eaplatanios : Could you elaborate a bit? What cannot be used by external library (the eager C API?).

If possible, I'd rather work out a scheme were we don't have to export more symbols instead of exporting `*grpc*` from the C API.

@akshaym would know more about how to hide those symbols.

**Comment by eaplatanios** [comment]
@asimshankar Sorry I was actually being too vague. I looked into it more and the main issue appears to be [this line](https://github.com/eaplatanios/tensorflow_scala/blob/67f125c40b3ef7f2ef23486f72793071b1d8e9f6/jni/src/main/native/checkpoint_reader.cc#L62). Creating a TFE_TensorHandle from a Tensor is not part of the public API. This forces me to include `eager/c_api_internal.h`, which includes dependencies on GRPC. In this case, maybe those symbols should not be exported in `libtensorflow.so`, but rather in `libtensorflow_framework.so`. This can be done by adding `"//tensorflow/c/eager:c_api"` as a dependency [here](https://github.com/tensorflow/tensorflow/blob/fe3f9dddb39171dd7cd9fbb9e044a40e08072c50/tensorflow/BUILD#L452). Do you think this is an acceptable solution? If not, how do you suggest I create the TFE_TensorHandle? Thanks! :)

**Comment by eaplatanios** [comment]
By the way, my current temporary solution is to add this instead of including `eager/c_api_internal.h`:
```
#include "tensorflow/core/common_runtime/eager/tensor_handle.h"

struct TFE_TensorHandle {
  TFE_TensorHandle(const tensorflow::Tensor& t)
      : handle(new tensorflow::TensorHandle(t, nullptr, nullptr, nullptr)) {}

  tensorflow::TensorHandle* handle;
};
```
However, I believe that I shouldn't need to replicate code here. If you think this is ok for now, feel free to close this issue. :)

**Comment by asimshankar** [comment]
Ah, thanks for the additional information. You're using APIs that we've explicitly marked "internal" so I'm not surprised you're seeing some friction :). I'd rather not add dependencies/symbols to export things we want to hide from the public API as that will only make it harder down the road.

I think the workaround you have is okay for now. The situation will change as the eager C API matures, but for now I feel it's okay to have some hacks in code that uses APIs we don't want to commit to :)

Thanks for your understanding.

**Comment by eaplatanios** [comment]
No problem. Yes, I am aware I'm using internal APIs that might change and totally understand that. I guess pointing out such issues related to how I am using those APIs might help with evolving the public API.

On another note, what happened to the `nightly-libtensorflow` CI builds? They seem to have been removed. Is there some alternative I could use? I was using them to obtain cross-compiled binaries to package with my Scala library.

**Comment by asimshankar** [comment]
Yup, definitely do point these out. Thanks.
Regarding nightly-libtensorflow: @av8ramit @case540 might know more.

**Comment by case540** [comment]
Sorry about the disruption. We recently shuffled around our CI builds. Just took a look and Windows libtensorflow seems to be having some build issues. Will look to fix next week sometime. Also, if you were downloading the builds from TensorFlow Jenkins, that will no longer be where the build artifacts will live. Will post their new location once everything gets settled.

**Comment by av8ramit** [comment]
Yes, we are doing a huge reshuffle of our nightly build process. Please bear with us until we have it all resolved. Thanks!

**Comment by eaplatanios** [comment]
@av8ramit @case540  Is there any update on when a new way to access the precompiled binaries might become available?
