### ISSUE TITLE
Why rnn final state shape[0] is uncertain when has sequence_length?

### ISSUE THREAD

**Issue by indiejoseph** [tensorflow/tensorflow#1956]
inputs = [tf.placeholder(tf.float32, [batch_size])] * 12
initial_state = cell.zero_state(batch_size, tf.float32)
outputs, final_state = rnn.rnn(cell, inputs, initial_state=initial_state, sequence_length=early_stop)

Why the final_state shape is Tensor(... shape=(?, 256)), instead of batch number?

**Comment by ebrevdo** [comment]
batch_size may be a dynamic tensor, and we don't check to see if it's a constant of the graph when performing static shape inference.

**Comment by vincentvanhoucke** [comment]
Closing assuming there is no real action item here.
