### ISSUE TITLE
'infiniband/verbs.h' file not found

### ISSUE THREAD

**Issue by quadrixm** [tensorflow/tensorflow#19566]
**ERROR**: /Users/abc/tensorflow/tensorflow/contrib/verbs/BUILD:90:1: C++ compilation of rule '//tensorflow/contrib/verbs:rdma_rendezvous_mgr' failed (Exit 1)
In file included from tensorflow/contrib/verbs/rdma_rendezvous_mgr.cc:18:
In file included from ./tensorflow/contrib/verbs/rdma_rendezvous_mgr.h:21:
In file included from ./tensorflow/contrib/verbs/rdma_mgr.h:24:
**./tensorflow/contrib/verbs/rdma.h:21:10: fatal error: 'infiniband/verbs.h' file not found**
#include <infiniband/verbs.h>

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by quadrixm** [comment]
Have I written custom code: No
OS Platform and Distribution: Mac OS 10.13.2 
TensorFlow installed from: Github
TensorFlow version: r1.8
Bazel version: 0.13.1-homebrew
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: are following

`$ cd tensorflow  # cd to the top-level directory created`
`$ ./configure`

Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]Y
Do you wish to build TensorFlow with Hadoop File System support? [y/N]
Do you wish to build TensorFlow with the XLA just-in-time compiler? [y/N]Y
**Do you wish to build TensorFlow with VERBS support? [y/N]Y**
Do you wish to build TensorFlow with OpenCL support? [y/N]
Do you wish to build TensorFlow with CUDA support? [y/N] N

`$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

**Comment by quadrixm** [comment]
When configuring with all default option that is all No it worked. Its only occurs when in configuration I select for **VERBS support** I guess
I have checked the code of the file /tensorflow/contrib/verbs/rdma.h and its including infiniband/verbs.h
`#include <infiniband/verbs.h>`
But there is no such file anywhere.

**Comment by cliffwoolley** [comment]
If you want verbs support, you need to have installed the necessary OFED components, which would provide this header file among other things.  If you don't have InfiniBand (or RoCE), then you don't need IB verbs.

**Comment by karmel** [comment]
Thanks, @cliffwoolley . @quadrixm - does installing the necessary components resolve your issue?
