### ISSUE TITLE
Getting wrong values from slice of a variable array

### ISSUE THREAD

**Issue by cemysf** [tensorflow/tensorflow#19565]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.4 LTS
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.7.0-3-g024aecf414 1.7.0
- **Python version**: 3.6.5
- **CUDA/cuDNN version**: CUDA Driver Version / Runtime Version:  9.1 / 9.0;  cuDNN: 7.1.3.16-1+cuda9.0
- **GPU model and memory**: GeForce 940MX 
- **Have I written custom code**: N/A
- **Bazel version**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
Bug: I am getting wrong values when I try to run/evaluate slice of a variable array with rank 3. 
Wrong values are all zeros, no matter how I initialize the array. Problem occurs for some dimension values (see screenshots below).

### Source code / logs
Trying to run this code with different k and d values. For instance there is no problem for k=3 and d=4, but k=3 and d=4 replicates the problem.

```
import tensorflow as tf
import numpy as np


k = 4
d = 3
sigma_init = np.repeat([np.eye(d, dtype=np.float32)], k, axis=0)

sigma = tf.get_variable("sigma",
                      shape=(k,d,d),
                      dtype=tf.float32,
                      initializer=tf.constant_initializer(sigma_init),
                      trainable=False)


sess = tf.Session()

sess.run([sigma.initializer])
#sess.run(tf.global_variables_initializer())
print("whole:")
print(sigma.eval(session=sess))


print("slices:")
print(sigma[0].eval(session=sess))

with sess.as_default():
    print(sigma[0].eval())
    
print(sess.run(sigma[0]))
```

![kd34](https://user-images.githubusercontent.com/9108649/40570982-228658b4-6091-11e8-83d6-aa59d15900e0.png)

![kd43](https://user-images.githubusercontent.com/9108649/40570984-264f6d00-6091-11e8-8b19-224ef3d5045d.png)

Some additional info about system:
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/2041188/tf_env.txt)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version
Exact command to reproduce

**Comment by cemysf** [comment]
I have updated the post

Re-installing/updating tensorflow did not help. Also: I cannot reproduce the error when I force tf to use the cpu

**Comment by cemysf** [comment]
Turned out to be driver specific problem, reinstalling driver, cuda and cudnn resolved it
