### ISSUE TITLE
AddSymbolicGradients cannot compute the partial derivative for merged node

### ISSUE THREAD

**Issue by tho15** [tensorflow/tensorflow#19561]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
1.8.0
- **Python version**: 
3.5.0
- **Bazel version (if compiling from source)**:
0.13.0
- **GCC/Compiler version (if compiling from source)**:
5.4.0
- **CUDA/cuDNN version**:
No CUDA
- **GPU model and memory**:
No GPU
- **Exact command to reproduce**:

### Describe the problem
Create a graph in C++ as following

      input
       /    \
      |      |
      x     y
       \    / 
         + (or concat)
         |
     output 

getting following error:

Non-OK-status: AddSymbolicGradients(root, {loss}, vars, &grads) status: Invalid argument: Cannot compute the partial derivative for node 'Variable_1' as it's unreachable from the output node(s).

The 'Variable_1' is the weight of x op. It should be reachable from output, but it looks the C++ library is not able to handle branch merge or adding.

**Comment by skye** [comment]
Can you provide a C++ script to the reproduce this problem?

**Comment by tho15** [comment]
Hi, I found an bug in my own code, and it works now. I'll close this issue. Thanks for your attention.
