### ISSUE TITLE
Latest NonMaxSuppression breaks backward compatiblity

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#19578]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: N/A
- **Python version**:  N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

The latest changes https://github.com/tensorflow/tensorflow/commit/1a300437cecfae36f7584694dac523851f1cd931 to the NonMaxSuppression op have two issues:

1. It breaks backward compatibility. It removes all boxes whose scores are below a threshold, and the threshold is default to 0. However, the old API does not require that the scores have to be >= 0. Boxes with negative scores will be removed by default after this change.
On [my implementation of Mask RCNN](https://github.com/ppwwyyxx/tensorpack/tree/master/examples/FasterRCNN) this decreases mAP by 0.2.

2. It has a potential bug. This loop:
https://github.com/tensorflow/tensorflow/blob/1a300437cecfae36f7584694dac523851f1cd931/tensorflow/core/kernels/non_max_suppression_op.cc#L137-L142

triggers an integer underflow when `selected` is empty, because `size()` is unsigned. It happens to cause no bugs in this case, but should better be fixed. If the loop order is reversed like `for (int j = 0; j <= selected.size() - 1; ++j)`, this would become a bug immediately.

EDIT: From https://en.cppreference.com/w/cpp/language/implicit_conversion:

> If the destination type is signed, the value does not change if the source integer can be represented in the destination type. Otherwise the result is implementation-defined. (Note that this is different from signed integer arithmetic overflow, which is undefined).

So the above code relies on implementation-defined behavior.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ppwwyyxx** [comment]
leave them as N/A

**Comment by ppwwyyxx** [comment]
1. was fixed in https://github.com/tensorflow/tensorflow/commit/d5a71ef8355ebb8d983c5e7f5b1e840cf2d00c17
