### ISSUE TITLE
[Feature] tf.reduce_dims() to reduce dimension as opposite to tf.expand_dims()

### ISSUE THREAD

**Issue by walkerlala** [tensorflow/tensorflow#19572]
### Describe the problem
It seems that there is no `tf.reduce_dims()` (the opposite of `tf.expand_dims()`). This functionality will be useful in the following scenario:

```python
# I want to reduce the last dimension 
[[1,2,3], [4,5,6], [7,8,9]]
# such that it becomes
[1,2,3,4,5,6,7,8,9]
```

I know this can be done with `tf.reshape()` but
 1. that requires extra `tf.shape()` for dynamic dimensions
 2. `tf.expand_dims()` can also be implemented with `tf.reshape()` but we have `tf.expand_dims()`

Would it be a bad idea to implement `tf.reduce_dims()`?

**Comment by ppwwyyxx** [comment]
1. Your example makes shape [3, 3] become shape [9, 1]. This is NOT the opposite of `expand_dims`. As said in the API document, `expand_dims` "__Inserts__ a dimension of 1 into a tensor's shape.".

2. `tf.squeeze` is an opposite of `expand_dims`. As mentioned in the API document.
https://www.tensorflow.org/api_docs/python/tf/expand_dims

**Comment by walkerlala** [comment]
@ppwwyyxx My example make `(3,3)` become `(9, )`, not `(9, 1)`.

**Comment by ppwwyyxx** [comment]
Sorry that was a mistake and I've edited my comment 5 hours ago.

**Comment by walkerlala** [comment]
@ppwwyyxx  Though not the opposite, would `tf.reduce_dims()` be useful?

**Comment by ppwwyyxx** [comment]
If not the opposite, you need to define what it is then, before others could possibly comment whether it's useful.
An example alone does not define an operation.

**Comment by robieta** [comment]
I took a look at the `tf.expand_dims()` implementation, and is seems that it is more than just a thin wrapper around `tf.reshape`. I think barring a very compelling reason it's simply not worth the additional API glut and maintenance cost of adding `reduce_dims`. As @walkerlala points out, for most cases `tf.squeeze()` is sufficient, which also makes the addition of another similar op less attractive.

Thanks for putting forward the idea though.
