### ISSUE TITLE
Using 1.7's TF_C_API_GRAPH_CONSTRUCTION=0 in 1.8.

### ISSUE THREAD

**Issue by szymonmaszke** [tensorflow/tensorflow#19594]
After your 1.8 change I am unable to programatically obtain architecture of loaded neural network (neural network saved by SavedModel functionality, custom tf.Estimator [or any tf.Estimator for that matter]). 

In 1.7 I could get all of the operations by ```graph.get_operations()```. Those were ordered (exactly the same as network layout, e.g. input operations first, followed by dense/convolutional/other layers up to network/graph output). Furthermore I could infer architecture by their names like conv2d etc. Right now (version 1.8) operations are **unordered** and their placement does not make much sense.

My question is: Is it possible to do now? Should I use some script from your repository to get those names in order (other than environment variable provided right now)?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
