### ISSUE TITLE
[Feature Request] Named Dimensions

### ISSUE THREAD

**Issue by Hoeze** [tensorflow/tensorflow#19602]
Having named dimensions would be a nice improvement to dynamic shapes.
I'm thinking about a similar system like [xarray's](http://xarray.pydata.org/en/stable/data-structures.html#dataset).

Example of current code:
```
images = tf.placeholder(tf.float32, shape=(None, None, None, 3))
images_shape = tf.shape(images)
ones = tf.ones(images_shape, dtype=images.dtype)
images_plus1 = images + ones 
print(images_plus1)
```
> <tf.Tensor 'add:0' shape=(?, ?, ?, 3) dtype=float32>

Due to the "None" - Dimensions it's hard to distinguish them, especially when using reshaping ops.
In my opinion some type of "tf.Dimension" would be better:
```
image_dim_0 = tf.Dimension(size=None, name="image_dim_0")
image_dim_1 = tf.Dimension(size=None, name="image_dim_1")
image_dim_2 = tf.Dimension(size=None, name="image_dim_2")

images = tf.placeholder(tf.float32, shape=(image_dim_0, image_dim_1, image_dim_2, 3))
images_shape = tf.shape(images)
ones = tf.ones(images_shape, dtype=images.dtype)
images_plus1 = images + ones 
print(images_plus1)
```
> <tf.Tensor 'add:0' shape=(**image_dim_0:** ?, **image_dim_1:** ?, **image_dim_2:** ?, 3) dtype=float32>

Also, this maybe helps to do some shape inference?

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: none
- **GCC/Compiler version (if compiling from source)**: none
- **CUDA/cuDNN version**: none
- **GPU model and memory**: none
- **Exact command to reproduce**: none

**Comment by martinwicke** [comment]
We actually have an attempt at this: [contrib/labeled_tensor](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/labeled_tensor).

I will close this issue. Contributions to labeled_tensor are welcome, although at this point, I believe it is abandoned (?).

**Comment by Hoeze** [comment]
Thanks for the hint, this fits my request very well.
It's a pity that these tensor labels are not natively supported by every tensor.

**Comment by danijar** [comment]
I think supporting named dimensions would still be a very useful feature. The link above is dead now because contrib is gone. JAX also supports this as *axes names*. Are there still ideas for adding this idea to TensorFlow?

**Comment by danijar** [comment]
I've opened a new issue with a more detailed proposal: https://github.com/tensorflow/tensorflow/issues/38228. @martinwicke, could you please take a look at it?

**Comment by martinwicke** [comment]
We are evaluating this project in the context of implementing a stronger
type system.

@agarwal-ashish FYI

**Comment by danijar** [comment]
Good to know, thanks.
