### ISSUE TITLE
'ClusterSpec' object has no attribute '_cluster_spec'

### ISSUE THREAD

**Issue by dsindex** [tensorflow/tensorflow#1961]
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
    sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0rc0-cp27-none-linux_x86_64.whl
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
    0.8.0rc0

### Steps to reproduce
1. https://github.com/dsindex/tensorflow/blob/master/mlp_mnist_dist.py
2. python mlp_mnist_dist.py --ps_hosts=localhost:2222,localhost:2223 --worker_hosts=localhost:2224,localhost:2225 --job_name=ps --task_index=0

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

{'ps': ['localhost:2222', 'localhost:2223'], 'worker': ['localhost:2224', 'localhost:2225']}
Traceback (most recent call last):
  File "mlp_mnist_dist.py", line 90, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "mlp_mnist_dist.py", line 35, in main
    server = tf.train.Server(cluster, job_name=FLAGS.job_name, task_index=FLAGS.task_index)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/server_lib.py", line 135, in __init__
    job_name, task_index, protocol)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/server_lib.py", line 65, in _make_server_def
    cluster_spec = ClusterSpec(server_or_cluster_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/server_lib.py", line 242, in __init__
    self._cluster_spec[job_def.name] = [t for t in job_def.tasks.values()]
AttributeError: 'ClusterSpec' object has no attribute '_cluster_spec'

**Comment by mrry** [comment]
Oops, this is an embarrassing bug - thanks for catching it! I've got a fix in the pipeline. For now, you can make it work by changing line 35 of your `mlp_mnist_dist.py` to:

```python
server = tf.train.Server(cluster.as_cluster_def(), job_name=FLAGS.job_name, task_index=FLAGS.task_index)
```

**Comment by dsindex** [comment]
@mrry thanks~ it works now :)

**Comment by caisq** [comment]
@mrry Let's put the fix into 0.8.0 final release.

**Comment by mrry** [comment]
@caisq: Agreed! Shall I send an individual PR with the cherrypicked commit?

**Comment by caisq** [comment]
@mrry: Yes, please send the PR to branch r0.8 and we'll merge it back to master.
