### ISSUE TITLE
Tensorflow custom Ops on AWS P3 instances exit with CUDA_ERROR_ILLEGAL_ADDRESS

### ISSUE THREAD

**Issue by badreddine1758** [tensorflow/tensorflow#19618]
I am trying to build my own Tensorflow Op on a AWS P3 instance (using NVIDIA's GPU Cloud and nvidia-docker) and I get the following error message:

```
2018-05-29 10:47:38.377439: E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
2018-05-29 10:47:38.377513: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:203] Unexpected Event status: 1
```

To build the Op, I had to create a coda_config.h, under /usr/local/cuda/, with the following content
```
#ifndef CUDA_CUDA_CONFIG_H_
#define CUDA_CUDA_CONFIG_H_

#define TF_CUDA_CAPABILITIES CudaVersion("3.0")

#define TF_CUDA_VERSION "9.0"
#define TF_CUDNN_VERSION "7.0.5"

#define TF_CUDA_TOOLKIT_PATH "/usr/local/cuda-9.0"

#endif  // CUDA_CUDA_CONFIG_H_
```
I also had to make these changes to /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/platform/default/mutex.h

```
#include "/usr/local/lib/python2.7/dist-packages/tensorflow/include/external/nsync/public/nsync_cv.h" // <- "nsync_cv.h"
#include "/usr/local/lib/python2.7/dist-packages/tensorflow/include/external/nsync/public/nsync_mu.h" // <- "nsync_mu.h"
```
I compile my source code files as follows
```
nvcc -std=c++11 -c -o my_op_gpu.cu.o my_op_gpu.cu.cc -I $TF_INC -I /usr/local/ -I /usr/local/lib/python2.7/dist-packages/tensorflow/include/external/nsync/public -I /usr/local/cuda/include/ -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC --expt-relaxed-constexpr

g++ -std=c++11 -shared -D_GLIBCXX_USE_CXX_ABI=0 -o my_op.so my_op.cc my_op_gpu.cu.o -I $TF_INC -I /usr/local/lib/python2.7/dist-packages/tensorflow/include/external/nsync/public -D GOOGLE_CUDA=1 -L$TF_LIB -ltensorflow_framework -fPIC
```

where
```
TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')
```

Please help.

**Comment by cliffwoolley** [comment]
CUDA_ERROR_ILLEGAL_ADDRESS indicates that some GPU kernel issued an out-of-bounds memory access.  You can run TF through `cuda-memcheck --binary-patching no` to determine which kernel it was.

**Comment by angersson** [comment]
Thanks for the help, @cliffwoolley!

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
