### ISSUE TITLE
Model_Average_optimizer Use Problems in got multiple values for keyword argument 'dtype'

### ISSUE THREAD

**Issue by yunyin** [tensorflow/tensorflow#19617]
I used `Model_Average_optimizer` and some problems occured:<br>
the code is used more likely as `model_average_optimizer_test.py`.<br>
I find this error is occured in `init ModelAverageOptimizer` to create local_step. And this problem is more likely some problems with device_setter.<br>
But I don't know why. Could someone help me?<br>

Have I written custom code: Yes
OS Platform and Distribution: Linux n10-044-067 4.4.0-33.bm.1-amd64 #1 SMP Thu, 22 Jun 2017 11:19:55 +0800 x86_64 GNU/Linux
TensorFlow installed from: Anaconda2.5, pip install tensorflow_gpu
TensorFlow version: 1.8.0
Bazel version: N/A
CUDA/cuDNN version: CUDA-9.0, cuDNN-7.1.2(installed in anaconda2.5 also)
GPU model and memory: GeForce GTX 1080
Exact command to reproduce:

    ~/anaconda2/bin/python test.py --server_hosts=localhost:12222 --worker_hosts=localhost:12223,localhost:12224 --job_name=worker --task_id=0
    ~/anaconda2/bin/python test.py --server_hosts=localhost:12222 --worker_hosts=localhost:12223,localhost:12224 --job_name=worker --task_id=1
    ~/anaconda2/bin/python test.py --server_hosts=localhost:12222 --worker_hosts=localhost:12223,localhost:12224 --job_name=server --task_id=0

You may notice the errors below is occured when one worker init class `ModelAverageOptimizer`

Traceback (most recent call last):

    File "/data00/home/wupeihao/ma_test/src/rnnlm.py", line 112, in tf.app.run()
    File "/data00/home/wupeihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
    File "/data00/home/wupeihao/ma_test/src/rnnlm.py", line 109, in main
    test()
    File "/data00/home/wupeihao/ma_test/src/rnnlm.py", line 84, in test
    interval_steps=3)
    File "/data00/home/wupeihao/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/opt/python/training/model_average_optimizer.py", line 139, in init name="local_step")
    File "/data00/home/wupeihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1317, in get_variable
    constraint=constraint)
    File "/data00/home/wupeihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1079, in get_variable
    constraint=constraint)
    File "/data00/home/wupeihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 417, in get_variable
    return custom_getter(**custom_getter_kwargs)
    File "/data00/home/wupeihao/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/opt/python/training/model_average_optimizer.py", line 92, in call
    return getter(name, trainable, collections, *args, **kwargs)
    TypeError: _true_getter() got multiple values for keyword argument 'dtype'

The code is below:
    
    import os
    import time
    import json
    import copy
    import numpy as np
    import tensorflow as tf
    from tensorflow.python.framework import ops
    from tensorflow.python.framework import constant_op
    from tensorflow.contrib.opt.python.training import model_average_optimizer
     
    flags = tf.flags
    flags.DEFINE_string("server_hosts", "", "Comma-separated list of hostname:port pairs")
    flags.DEFINE_string("worker_hosts", "", "Comma-separated list of hostname:port pairs")
    flags.DEFINE_string("job_name", "", "Either 'server' of 'worker'")
    flags.DEFINE_integer("task_id", 0, "Task Id for Each workers")
     
    FLAGS = flags.FLAGS
    tf.logging.set_verbosity(tf.logging.INFO)
     
    def workers_ps_creator(args):
        ps_hosts = args.server_hosts.split(",")
        worker_hosts = args.worker_hosts.split(",")
        num_workers = len(worker_hosts)
     
        cluster = tf.train.ClusterSpec({"ps": ps_hosts,"worker": worker_hosts})
        gpu_options = tf.GPUOptions(allocator_type='BFC', allow_growth=True)
        if args.job_name == "server":
            server_def = tf.train.ServerDef(cluster=cluster.as_cluster_def(),
                job_name='ps',
                task_index=args.task_id,
                default_session_config=tf.ConfigProto(gpu_options=gpu_options, device_count={"GPU":0}),
                protocol="grpc")
        elif args.job_name == "worker":
            server_def = tf.train.ServerDef(cluster=cluster.as_cluster_def(),
                    job_name="worker",
                    task_index=args.task_id,
                    default_session_config = tf.ConfigProto(gpu_options=gpu_options),
                    protocol="grpc")
        server = tf.train.Server(server_def)
        return server, cluster, num_workers, gpu_options
     
    def Model(opt):
        if FLAGS.task_id == 0:
            var_0 = tf.get_variable(initializer = 0.0, name = 'v0')
            var_1 = tf.get_variable(initializer = 1.0, name = 'v1')
            grads_0 = constant_op.constant(-1.0)
            grads_1 = constant_op.constant(-1.0)
        else:
            var_0 = tf.get_variable(initializer = 7.0, name = 'v0')
            var_1 = tf.get_variable(initializer = 8.0, name = 'v1')
            grads_0 = constant_op.constant(-2.0)
            grads_1 = constant_op.constant(-2.0)
        train_op = opt.apply_gradients([[grads_0, var_0], [grads_1, var_1]],
                global_step = tf.train.get_or_create_global_step())
        return train_op
     
    def test():
        server, cluster, num_workers, gpu_options = workers_ps_creator(FLAGS)
        if FLAGS.job_name == "server":
            server.join()
        elif FLAGS.job_name == "worker":
            is_chief = (FLAGS.task_id == 0)
            #Between-graph replication
            worker_device = "/job:worker/task:%d" % (FLAGS.task_id)
            ma_custom = model_average_optimizer.ModelAverageCustomGetter(worker_device=worker_device)
            from tensorflow.python.training import device_setter
            with tf.device(
                device_setter.replica_device_setter(
                    cluster=cluster,
                    worker_device=worker_device,
                    ps_device="/job:ps")), \
                tf.variable_scope("", custom_getter=ma_custom):
                #create model
                lr = tf.Variable(1, trainable=False)
                opt = tf.train.GradientDescentOptimizer(lr)
                sync_opt = model_average_optimizer.ModelAverageOptimizer(
                            opt=opt,
                            num_worker=num_workers,
                            ma_custom_getter=ma_custom,
                            is_chief=is_chief,
                            interval_steps=3)
                tf.logging.info('model start')
                train_model = Model(sync_opt)
                tf.logging.info('model end')
                ma_hook = sync_opt.make_session_run_hook()
            sess_config = tf.ConfigProto(gpu_options=gpu_options)
            sess_config.log_device_placement = False
            sess_config.allow_soft_placement = True
      
            all_hooks = [ma_hook]
     
            tf.logging.info('Start Sess')
            with tf.train.MonitoredTrainingSession(master=server.target,
                    is_chief=is_chief,
                    hooks=all_hooks) as sess:
                tf.logging.info("is chief: %s, len: %s", is_chief, num_workers)
                for i in range(4):
                    sess.run(train_op)
                    pp1 = sess.run(tf.get_default_graph().get_tensor_by_name('v0:0'))
                    pp2 = sess.run(tf.get_default_graph().get_tensor_by_name('v1:0'))
                    tf.logging.info("%d %.2f %.2f" % (FLAGS.task_id, pp1, pp2))
            sv.stop()
            tf.logging.info("done")

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yunyin** [comment]
Sorry for delay, details are updated.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yunyin** [comment]
I've updated this questions yesterday.
I've no idea if there are any problems for solving this problem.

**Comment by jinxin0924** [comment]
Hi @yunyin, I am the author of ModelAverageOptimizer. Sorry for the bug. Did you solve the problem? There are two ways to solve it: 
1. place opt out of the ma_custom scope
2.  modify model_average_optimizer.py line 91 like this:
```
    else:
      kwargs['trainable'] = trainable
      kwargs['collections'] = collections
      return getter(name, *args, **kwargs)
```
I will make a pull request to fix this. Thanks for trying this opt!

**Comment by asimshankar** [comment]
Thanks for responding @jinxin0924 - marking as "Contributions welcome" since it seems you have PR out for this.

**Comment by yunyin** [comment]
@jinxin0924 Thank you for your reply. I solve this problems with your second suggestion.
It's a nice work. But I still have some problems about `local_step` in `model_average_optimizer.py`. 
I found that it seems different workers share the same `local_step`.

detail logs are shown below,
It seems that model average is triggered in `(0,0),(4,2),(6,4),(9,9)`, it doesn't make any sense.

worker0 log:

	INFO:tensorflow:is chief: True, len: 2
	INFO:tensorflow:0 0 8.00 9.00
	INFO:tensorflow:0 1 9.00 10.00
	INFO:tensorflow:0 2 10.00 11.00
	INFO:tensorflow:0 3 11.00 12.00
	INFO:tensorflow:0 4 18.00 19.00
	INFO:tensorflow:0 5 19.00 20.00
	INFO:tensorflow:0 6 27.00 28.00
	INFO:tensorflow:0 7 28.00 29.00
	INFO:tensorflow:0 8 29.00 30.00
	INFO:tensorflow:0 9 48.50 49.50

worker1 log:

	INFO:tensorflow:is chief: False, len: 2
	INFO:tensorflow:1 0 8.00 9.00
	INFO:tensorflow:1 1 16.00 17.00
	INFO:tensorflow:1 2 18.00 19.00
    INFO:tensorflow:1 3 26.00 27.00
    INFO:tensorflow:1 4 27.00 28.00
    INFO:tensorflow:1 5 35.00 36.00
    INFO:tensorflow:1 6 43.00 44.00
    INFO:tensorflow:1 7 51.00 52.00
    INFO:tensorflow:1 8 59.00 60.00
    INFO:tensorflow:1 9 48.50 49.50

**Comment by jinxin0924** [comment]
@yunyin, yes, different workers share the same local_step. It is a bug. You can modify model_average_optimizer.py line 91 like this:
```
    else:
      kwargs['trainable'] = trainable
      kwargs['collections'] = collections
      if ops.GraphKeys.LOCAL_VARIABLES in collections:
        with ops.device(self._worker_device):
          return getter(name, *args, **kwargs)
      else:
        return getter(name, *args, **kwargs)
```
In my experiments, I always create model average optimizer out of the ma_custom scope, so I did not find these bugs. Again, thanks a lot!

**Comment by yunyin** [comment]
@jinxin0924 Thank you for reply soon.

**Comment by jinxin0924** [comment]
@yunyin , clould you debug at model_average_optimizer.py line 94 `if ops.GraphKeys.LOCAL_VARIABLES in collections:` and take a look what will happen when the name is local_step?

**Comment by yunyin** [comment]
@jinxin0924 I've solved this problem.
You should put opt in ma_custom scope, so that local_step could be LOCAL_VARIABLES.
Thanks again for your work and support.
