### ISSUE TITLE
Cannot create initializer for non-floating point type

### ISSUE THREAD

**Issue by nairouz** [tensorflow/tensorflow#19613]
I m using tensorflow.contrib.slim for creating my model and google Colaboratory for running my code.
My code was working like a charm with tensorflow 1.7 but when the new version 1.8 was installed in the cloud, I got the following error:

`TypeError                                 Traceback (most recent call last)
/content/drive/Colab/baby_training_model_estimators/train_model.py in <module>()
    100     import logging
    101     logging.getLogger('tensorflow').propagate = False
--> 102     run_train()

/content/drive/Colab/baby_training_model_estimators/train_model.py in run_train(args)
     94                                       run_config=run_config,
     95                                       schedule="train_and_evaluate",
---> 96                                       hparams=params)
     97 
     98 if __name__ == '__main__':

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    248               'in a future version' if date is None else ('after %s' % date),
    249               instructions)
--> 250       return func(*args, **kwargs)
    251     return tf_decorator.make_decorator(
    252         func, new_func, 'deprecated',

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py in run(experiment_fn, output_dir, schedule, run_config, hparams)
    223   schedule = schedule or _get_default_schedule(run_config)
    224 
--> 225   return _execute_schedule(experiment, schedule)
    226 
    227 

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py in _execute_schedule(experiment, schedule)
     50     logging.error('Allowed values for this experiment are: %s', valid_tasks)
     51     raise TypeError('Schedule references non-callable member %s' % schedule)
---> 52   return task()
     53 
     54 

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py in train_and_evaluate(self)
    664                   hooks=self._eval_hooks)
    665           ]
--> 666       self.train(delay_secs=0)
    667 
    668     # If the checkpoint_and_export flag and appropriate estimator configuration

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py in train(self, delay_secs)
    387         max_steps=self._train_steps,
    388         hooks=self._train_monitors + extra_hooks,
--> 389         saving_listeners=self._saving_listeners)
    390 
    391   def evaluate(self, delay_secs=None, name=None):

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py in _call_train(self, _sentinel, input_fn, steps, hooks, max_steps, saving_listeners)
    874           max_steps=max_steps,
    875           hooks=hooks,
--> 876           saving_listeners=saving_listeners)
    877     else:
    878       return self._estimator.fit(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    361 
    362     saving_listeners = _check_listeners_type(saving_listeners)
--> 363     loss = self._train_model(input_fn, hooks, saving_listeners)
    364     logging.info('Loss for final step: %s.', loss)
    365     return self

/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py in _train_model(self, input_fn, hooks, saving_listeners)
    841       return self._train_model_distributed(input_fn, hooks, saving_listeners)
    842     else:
--> 843       return self._train_model_default(input_fn, hooks, saving_listeners)
    844 
    845   def _train_model_default(self, input_fn, hooks, saving_listeners):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py in _train_model_default(self, input_fn, hooks, saving_listeners)
    854       worker_hooks.extend(input_hooks)
    855       estimator_spec = self._call_model_fn(
--> 856           features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
    857       return self._train_with_estimator_spec(estimator_spec, worker_hooks,
    858                                              hooks, global_step_tensor,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py in _call_model_fn(self, features, labels, mode, config)
    829 
    830     logging.info('Calling model_fn.')
--> 831     model_fn_results = self._model_fn(features=features, **kwargs)
    832     logging.info('Done calling model_fn.')
    833 

/content/drive/Colab/baby_training_model_estimators/tf_autoencoder/estimator.py in _model_fn(features, labels, mode)
     92                                                  dropout=dropout,
     93                                                  weight_decay=weight_decay,
---> 94                                                  mode=mode)
     95             return _create_estimator_spec_from_logits(labels=labels,
     96                                                       logits=logits,

/content/drive/Colab/baby_training_model_estimators/tf_autoencoder/layers.py in fully_connected_autoencoder(network_type, model_id, sparse_coding, inputs, hidden_units, activation_fn, dropout, weight_decay, mode)
     90         with tf.variable_scope(scope, 'FCAutoencoder', [inputs]):
     91                 with slim.arg_scope(autoencoder_arg_scope(activation_fn, dropout, weight_decay, None, mode)):
---> 92                         net = fc_encoder(inputs, hidden_units, network_type, model_id, dropout, sparse_coding)
     93                         n_features = inputs.shape[1].value
     94                         decoder_units = hidden_units[:-1][::-1] + [n_features]

/content/drive/Colab/baby_training_model_estimators/tf_autoencoder/layers.py in fc_encoder(inputs, hidden_units, network_type, model_id, dropout, sparse_coding)
     15                         with tf.variable_scope('layer_{}'.format(layer_id), values=(net,)) as layer_scope:
     16                                 print(num_hidden_units)
---> 17                                 net = slim.fully_connected(net, num_outputs= num_hidden_units, scope=layer_scope)
     18                                 if sparse_coding is not None:
     19                                         tf.losses.mean_squared_error(net, tf.zeros_like(net), weights=sparse_coding, scope=layer_scope)

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py in func_with_args(*args, **kwargs)
    181       current_args = current_scope[key_func].copy()
    182       current_args.update(kwargs)
--> 183     return func(*args, **current_args)
    184 
    185   _add_op(func)

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/layers/python/layers/layers.py in fully_connected(inputs, num_outputs, activation_fn, normalizer_fn, normalizer_params, weights_initializer, weights_regularizer, biases_initializer, biases_regularizer, reuse, variables_collections, outputs_collections, trainable, scope)
   1714         _scope=sc,
   1715         _reuse=reuse)
-> 1716     outputs = layer.apply(inputs)
   1717 
   1718     # Add variables to collections.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/base.py in apply(self, inputs, *args, **kwargs)
    826       Output tensor(s).
    827     """
--> 828     return self.__call__(inputs, *args, **kwargs)
    829 
    830   def _add_inbound_node(self,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/base.py in __call__(self, inputs, *args, **kwargs)
    697           if all(hasattr(x, 'get_shape') for x in input_list):
    698             input_shapes = nest.map_structure(lambda x: x.get_shape(), inputs)
--> 699           self.build(input_shapes)
    700         try:
    701           # Note: not all sub-classes of Layer call Layer.__init__ (especially

/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/core.py in build(self, input_shape)
    136                                     constraint=self.kernel_constraint,
    137                                     dtype=self.dtype,
--> 138                                     trainable=True)
    139     if self.use_bias:
    140       self.bias = self.add_variable('bias',

/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/base.py in add_variable(self, name, shape, dtype, initializer, regularizer, trainable, constraint, partitioner)
    544             constraint=constraint,
    545             trainable=trainable and self.trainable,
--> 546             partitioner=partitioner)
    547 
    548         if init_graph is not None:  # pylint: disable=protected-access

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpointable.py in _add_variable_with_custom_getter(self, name, shape, dtype, initializer, getter, overwrite, **kwargs_for_getter)
    434     new_variable = getter(
    435         name=name, shape=shape, dtype=dtype, initializer=initializer,
--> 436         **kwargs_for_getter)
    437 
    438     # If we set an initializer and the variable processed it, tracking will not

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in get_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
   1315       partitioner=partitioner, validate_shape=validate_shape,
   1316       use_resource=use_resource, custom_getter=custom_getter,
-> 1317       constraint=constraint)
   1318 get_variable_or_local_docstring = (
   1319     """%s

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in get_variable(self, var_store, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
   1077           partitioner=partitioner, validate_shape=validate_shape,
   1078           use_resource=use_resource, custom_getter=custom_getter,
-> 1079           constraint=constraint)
   1080 
   1081   def _get_partitioned_variable(self,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in get_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
    415       if "constraint" in estimator_util.fn_args(custom_getter):
    416         custom_getter_kwargs["constraint"] = constraint
--> 417       return custom_getter(**custom_getter_kwargs)
    418     else:
    419       return _true_getter(

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/layers/python/layers/layers.py in layer_variable_getter(getter, *args, **kwargs)
   1609   def layer_variable_getter(getter, *args, **kwargs):
   1610     kwargs['rename'] = rename
-> 1611     return _model_variable_getter(getter, *args, **kwargs)
   1612 
   1613   return layer_variable_getter

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/layers/python/layers/layers.py in _model_variable_getter(getter, name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, rename, use_resource, **_)
   1600       partitioner=partitioner,
   1601       custom_getter=getter,
-> 1602       use_resource=use_resource)
   1603 
   1604 

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py in func_with_args(*args, **kwargs)
    181       current_args = current_scope[key_func].copy()
    182       current_args.update(kwargs)
--> 183     return func(*args, **current_args)
    184 
    185   _add_op(func)

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/variables.py in model_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, device, partitioner, custom_getter, use_resource)
    289                  caching_device=caching_device, device=device,
    290                  partitioner=partitioner, custom_getter=custom_getter,
--> 291                  use_resource=use_resource)
    292   return var
    293 

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py in func_with_args(*args, **kwargs)
    181       current_args = current_scope[key_func].copy()
    182       current_args.update(kwargs)
--> 183     return func(*args, **current_args)
    184 
    185   _add_op(func)

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/variables.py in variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, device, partitioner, custom_getter, use_resource)
    244                   caching_device=caching_device,
    245                   partitioner=partitioner,
--> 246                   use_resource=use_resource)
    247 
    248 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, constraint)
    392           trainable=trainable, collections=collections,
    393           caching_device=caching_device, validate_shape=validate_shape,
--> 394           use_resource=use_resource, constraint=constraint)
    395 
    396     if custom_getter is not None:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint)
    784         validate_shape=validate_shape,
    785         constraint=constraint,
--> 786         use_resource=use_resource)
    787     if not context.executing_eagerly() or self._store_eager_variables:
    788       # In eager mode we do not want to keep default references to Variable

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in variable(initial_value, trainable, collections, validate_shape, caching_device, name, dtype, constraint, use_resource)
   2218                          name=name, dtype=dtype,
   2219                          constraint=constraint,
-> 2220                          use_resource=use_resource)
   2221 
   2222 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in <lambda>(**kwargs)
   2208              constraint=None,
   2209              use_resource=None):
-> 2210   previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
   2211   for getter in ops.get_default_graph()._variable_creator_stack:  # pylint: disable=protected-access
   2212     previous_getter = _make_getter(getter, previous_getter)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in default_variable_creator(next_creator, **kwargs)
   2191         collections=collections, validate_shape=validate_shape,
   2192         caching_device=caching_device, name=name, dtype=dtype,
-> 2193         constraint=constraint)
   2194 
   2195 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py in __init__(self, initial_value, trainable, collections, validate_shape, caching_device, name, variable_def, dtype, expected_shape, import_scope, constraint)
    233           dtype=dtype,
    234           expected_shape=expected_shape,
--> 235           constraint=constraint)
    236 
    237   def __repr__(self):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py in _init_from_args(self, initial_value, trainable, collections, validate_shape, caching_device, name, dtype, expected_shape, constraint)
    341             with ops.name_scope("Initializer"), ops.device(None):
    342               self._initial_value = ops.convert_to_tensor(
--> 343                   initial_value(), name="initial_value", dtype=dtype)
    344               shape = (self._initial_value.get_shape()
    345                        if validate_shape else tensor_shape.unknown_shape())

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in <lambda>()
    768           initializer = initializer(dtype=dtype)
    769         init_val = lambda: initializer(  # pylint: disable=g-long-lambda
--> 770             shape.as_list(), dtype=dtype, partition_info=partition_info)
    771         variable_dtype = dtype.base_dtype
    772 

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/layers/python/layers/initializers.py in _initializer(shape, dtype, partition_info)
    118     """Initializer function."""
    119     if not dtype.is_floating:
--> 120       raise TypeError('Cannot create initializer for non-floating point type.')
    121     # Estimating fan_in and fan_out is not possible to do perfectly, but we try.
    122     # This is the right thing for matrix multiply and convolutions.

TypeError: Cannot create initializer for non-floating point type.

`

I think it is related to a previous bug: [#6342](https://github.com/tensorflow/tensorflow/issues/6342)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by nairouz** [comment]
Sorry, it seems that I have deleted a line that converts the integer tensors into floating tensors.
So there is no bug.
