### ISSUE TITLE
Feature Request: Add normalizer_fn to sequence_numeric_column.

### ISSUE THREAD

**Issue by jojiasako** [tensorflow/tensorflow#19628]
### System information
- **Have I written custom code**: no
- **OS Platform and Distribution**: macOS Sierra 10.12.6
- **TensorFlow installed from**: binary
- **TensorFlow version**: 1.8.0
- **Python version**: 3.6.5
- **Bazel version**: N/A
- **GCC/Compiler version**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
Currently, `sequence_numeric_column` does not support a `normalizer_fn`, wondering if this could be added in like in `numeric_column`.

**Comment by yongtang** [comment]
Added a PR #19649 for the support.
