### ISSUE TITLE
[Bug] AdamOptimizer: No Exception on invalid input

### ISSUE THREAD

**Issue by mBHyuC** [tensorflow/tensorflow#19621]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.8.0-0-g93bc2e2072
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0/7.0
- **GPU model and memory**: 4G/Quadro M1000M
- **Exact command to reproduce**: -

### Describe the problem
The graph can be executed with AdamOptimizer, thus the graph input is invalid. In the example an out-of-bound embedding  index is passed. Other tested optimizer (RMSP,Ada) yield: InvalidArgumentError: indices[0,0] = 10 is not in [0, 10)

### Source code / logs
```python
import tensorflow as tf
import numpy as np

def embed_helper(inputs, size, dim, name=None):
    std = np.square(2. / dim)
    test_emb = tf.Variable(tf.random_uniform([size, dim], -std, std), name=name)
    return tf.nn.embedding_lookup(test_emb, inputs)

num_factors = 16
num_embed = 10

graph = tf.Graph()
with graph.as_default():
    x = tf.placeholder(tf.int32, shape=(None, 1))
    x_emb = embed_helper(x, num_embed, num_factors, name=None)
    very_complicated_net = tf.square(tf.subtract(x_emb, tf.constant(3.)))

    # RMSP and the other tested optimizer yield InvalidArgumentError - AdamOptimizer does not
    # -> InvalidArgumentError (see above for traceback): indices[0,0] = 10 is not in [0, 10)
    #opt = tf.train.RMSPropOptimizer(learning_rate=0.01)
    opt = tf.train.AdamOptimizer(learning_rate=0.01)

    graph_step = opt.minimize(very_complicated_net)
    init = tf.global_variables_initializer()

session = tf.Session(config=None, graph=graph)
session.run(init)

# 10 is not in [0,1,..,9]
index_batch_out_of_bound = np.array([10]).reshape(-1, 1)

x_feed_dict = {
    x: index_batch_out_of_bound
}

session.run(graph_step, x_feed_dict)
```

**Comment by drpngx** [comment]
Consistency would be good. Feel free to send a fix. Thanks!

**Comment by ShreyasSingh** [comment]
I would like to work on this.

**Comment by HannH** [comment]
I am working on this bug, found it happend after adding RMS optimizer: "RMSProp/update_Variable/SparseApplyRMSProp/xx"
in the graph, the embedding operator then was bound to CPU though it has been bound to GPU.
before add rms:
embedding_lookup: (Gather): /job:localhost/replica:0/task:0/device:GPU:0
after add rms:
embedding_lookup: (Gather): /job:localhost/replica:0/task:0/device:CPU:0
According to the official [document](https://www.tensorflow.org/api_docs/python/tf/nn/embedding_lookup), it will **definitely** raise out of boundary error when you run it on CPU rather than GPU.
It is a weird problem, but bind the operation into GPU compulsive may solve the problem. Any idea how to do this? @drpngx 
Code place :python/framework/ops.py line 3210:"self._add_op(op)"

**Comment by drpngx** [comment]
So there is code to colocate gradients and variables, is that causing the problem?

Anyway, the way I would do this is to try and compare the working optimizer vs the non-working ones and see what the difference is. I'm not sure right now what exactly that is. Even if it's bound on another device it shouldn't return different results.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by transcendentsky** [comment]
Emmm, the code is not right i think, 
```
# 10 is not in [0,1,..,9]
index_batch_out_of_bound = np.array([10]).reshape(-1, 1)
```
maybe the following is right
```
index_batch_out_of_bound = np.arange(10).reshape(-1,1)
```

**Comment by sachinprasadhs** [comment]
Could you please upgrade your Tensorflow version to 2.x and your code to version compatibility and check for the error message again. 
Refer [tf.keras.optimizers.Adam](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam) for more details.Thanks!
