### ISSUE TITLE
Killed during checkpoint save (v0.8)

### ISSUE THREAD

**Issue by Jinxit** [tensorflow/tensorflow#1962]
### Environment info
Operating System: Ubuntu 15.10

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

`-rw-r--r-- 1 root root   322936 aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 61453024 mar  6 15:08 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 61453024 mar  6 15:08 /usr/local/cuda/lib64/libcudnn.so.4
-rwxr-xr-x 1 root root 61453024 mar  6 15:08 /usr/local/cuda/lib64/libcudnn.so.4.0.7
-rwxr-xr-x 1 root root 11172416 feb 29 22:12 /usr/local/cuda/lib64/libcudnn.so.6.5
-rwxr-xr-x 1 root root 11172416 feb 29 22:12 /usr/local/cuda/lib64/libcudnn.so.6.5.48
-rw-r--r-- 1 root root 62025862 mar  6 15:08 /usr/local/cuda/lib64/libcudnn_static.a`

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

`0.8.0rc0`

### Relevant code:

Unfortunately I can't upload everything, but the code is based on your CIFAR-10 example. Here is the structure of my network:
http://pastebin.com/5QEJWqtm

After running for some time, I save a checkpoint:

`saver.save(sess, checkpoint_path, global_step=step)`

Which *sometimes* allocates all memory on my system and gets killed. I have 8gb RAM and 8gb swap. For the first few checkpoints it seems fine, it allocates 2gb RAM (equal to checkpoint file size), but after some time it locks up my entire system and gets killed automatically.

Didn't have any issues in 0.7.

**Comment by sherrym** [comment]
Could you please try calling save with this option:

saver.save(sess, checkpoint_path, global_step=step, write_meta_graph=False)

Sherry

**Comment by jmugan** [comment]
Adding `write_meta_graph=False` fixed the error for me where saver.save would result in `MemoryError` on an Amazon GPU. But now I randomly get `terminate called after throwing an instance of std::bad_alloc what(): std::bad_alloc Aborted (core dumped)`.

**Comment by Jinxit** [comment]
Sorry for the delay @sherrym, finally got to try this out. `write_meta_graph=False` seems to have solved the issue for me. I don't get @jmugan's error either.

**Comment by pkmital** [comment]
This is happening for me while saving a checkpoint with or without `write_meta_graph=False` on tf.0.8.0rc0 on Ubuntu 14.04.  The checkpoint appears to be in a temporary state just before the crash occurs.

```
-rw-rw-r-- 1 ubuntu ubuntu 590993388 May 11 07:51 gan.ckpt-1400
-rw-rw-r-- 1 ubuntu ubuntu 67731865 May 11 07:59 gan.ckpt-1500.tempstate5056164176772455283
```

**Comment by pkmital** [comment]
On further inspection, this occurs once the system has run out of memory.  In my particular application, it seems the process grows from using ~ 1 GB to using the entire system memory ~16 GB (no swap) over the course of 8 hours, and then crashes with the above message.   I can at least continue training by using a swap space, but it seems there is another issue here causing a memory leak.

**Comment by sherrym** [comment]
@jmugan, I agree with you that the model is probably too big for your system.

@pkmital, could you please file a bug if you believe the memory leak is in TensorFlow, and not in the way your model is constructed?

Closing this bug as the fundamental issue is memory, not the saver itself.

**Comment by deeptigp** [comment]
Hi @sherrym  : has this issue been resolved?  I am running into the same problem where the program crashes while trying to save the checkpoint file.

**Comment by innovationchef** [comment]
I am facing the same error and write_meta_graph=False doesn't seem to work in my case. I have a RAM of about 5.5 GB. The training is aborted at the first step only. Can anyone suggest what could be the issue?

**Comment by Syndrome777** [comment]
I have this error, too.
And I have a RAM of 60GB. I get this error after some save operators. It seems that the save operator don't release the memory rightly. My version is '0.12.0'.

**Comment by alexattia** [comment]
Same error with 1.0

**Comment by Immortalt** [comment]
Same error with 1.0

**Comment by HenriMir** [comment]
same error (with 1.01) has anyone figured a solution out?

**Comment by gmhafiz** [comment]
I found out that I do not have a swap partition. Creating one solves this problem. Verify with `sudo free -h`

To create, (guide from https://linuxize.com/post/create-a-linux-swap-file/)
`sudo fallocate -l 32G /swapfile
sudo dd if=/dev/zero of=/swapfile bs=1024 count=33554432
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
`
