### ISSUE TITLE
Possible Error in "TensorFlow For Poets" Guide

### ISSUE THREAD

**Issue by silpian** [tensorflow/tensorflow#19630]
Small, possible error found in https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#4:
"The first figure shows accuracy (x-axis) as a function of training progress (y-axis):"

Should be corrected to:
"The first figure shows accuracy (y-axis) as a function of training progress (x-axis):"

Or you can change the "accuracy_1" graph below it.

**Comment by dubey** [comment]
Thanks, assigning to Wolff who added the codelab.

**Comment by MarkDaoust** [comment]
Fixed.Thanks.

**Comment by silpian** [comment]
Cool, np. There are also some minor spelling errors on   https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#5   (in the yellow box):
  

  
"WIf you chose a mobilenet that takes a smaller input size, then be shure to set the   --input_size   flag using the shell variable you set earlier."
  
  
  
should probably be:
  

  
"**If**   you chose a mobilenet that takes a smaller input size, then be to **sure** set the   --input_size   flag using the shell variable you set earlier."
  

  
But people can probably understand it regardless. Thank you.
  
  

  
>

**Comment by MarkDaoust** [comment]
Right. Fixed. Thanks Again.
