### ISSUE TITLE
Disable tensors with unknown rank

### ISSUE THREAD

**Issue by GSPP** [tensorflow/tensorflow#19632]
I am a Tensorflow novice. I found that a lot of headache was caused by tensors of unknown rank. This sometimes caused runtime errors and sometimes errors at graph building time. I now understand why all of this happened but at the time it caused a lot of grief. I have seen the Tensorflow developers speak about tensors of unknown rank as something to be avoided.

I propose adding a feature to Tensorflow to disable tensors with unknown rank. Often, when that happens it signals a coding error. That way I would immediately notice when this happens with some intermediate computation.

This feature could be either to immediately throw when this happens or it could be a linter that can be run on a graph to warn about suspicious patterns.

------------------------

### System information
- **Experiences from custom code**
- **Windows TF 1.8**
- **Python 3.5**

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by GSPP** [comment]
These fields do not appear relevant to my feature request so I left them out. The TF version was included in my post as 1.8.

**Comment by bignamehyp** [comment]
There are many highly dynamic custom code that requires tensors with unknown rank.
For example you can create one with tf.placeholder(tf.float32).  

Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by GSPP** [comment]
I was proposing to enable a sanitizing mode that rejects tensors with unknown ranks. Of course the framework must continue to allow dynamic use. This is important for some use cases and for compatibility. This should be opt-in. Of course I'm fine with closing this issue if you think such a feature would not be of merit. But I'm not sure you noticed that this was meant as an opt-in mode (e.g. `myGraph.setAllowDynamicRank(False)`).
