### ISSUE TITLE
kernel_constraint=maxnorm(3) raises error with eager execution

### ISSUE THREAD

**Issue by doriang102** [tensorflow/tensorflow#19648]
I posted this already on Stackoverflow and it was suggested this is indeed a bug:
https://stackoverflow.com/questions/50594025/how-to-include-kernel-constraints-in-tensorflow-eager-conv2d

I'm having trouble using `kernel_constraint=maxnorm(3)` within keras when using Tensorflow eager execution. This works fine when not using the standard `Sequential` method outside of eager execution, but seems to fail with an error here (it seems to be because of a multiplication step `*=` which I don't know if there is a substitute for in this context). 

**Question:** Is there a workaround to incorporate the maximum $L^2$ norm functionality within the Eager Tensorflow execution framework? Below are more details.

Here is how I activate `tensorflow` eager. 

    from __future__ import absolute_import, division, print_function
    import tensorflow as tf
    import tensorflow.contrib.eager as tfe
    from keras.datasets import cifar10
    tf.enable_eager_execution()

The following code works fine

**Works:**

    class ObjectDet(tf.keras.Model):
        def __init__(self):
            super(ObjectDet,self).__init__()
            self.layer1= tf.keras.layers.Conv2D(32, (3, 3), input_shape=(32,32,3), padding='same', activation='relu')
            self.layer2=tf.keras.layers.Dropout(0.2)
            self.layer3=tf.keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same')
            self.layer4=tf.keras.layers.MaxPooling2D(pool_size=(2,2))
            self.layer5=tf.keras.layers.Flatten()
            self.layer6=tf.keras.layers.Dense(512, activation='relu')
            self.layer7=tf.keras.layers.Dropout(0.1)
            self.layer8=tf.keras.layers.Dense(10, activation='softmax')

        def call(self, input):
            """Run the model."""
            result = self.layer1(input)
            result = self.layer2(result)
            result = self.layer3(result)
            result = self.layer4(result)
            result = self.layer5(result)
            result = self.layer6(result)
            result = self.layer7(result)
            result = self.layer8(result)
        
            return result

    def loss(model, x, y):
      prediction = model(x)
      return cross_entropy(prediction,y)
    
    def grad(model, inputs, targets):
      with tf.GradientTape() as tape:
        loss_value = loss(model, inputs, targets)
      return tape.gradient(loss_value, model.variables)
    
    
    x, y = iter(train_ds).next()
    print("Initial loss: {:.3f}".format(loss(model, x, y)))
    
    # Training loop
    for (i, (x, y)) in enumerate(train_ds):
      # Calculate derivatives of the input function with respect to its parameters.
      grads = grad(model, x, y)
      # Apply the gradient to the model
      
      optimizer.apply_gradients(zip(grads, model.variables),
                                global_step=tf.train.get_or_create_global_step())
      if i % 200 == 0:
        pass
        print("Loss at step {:04d}: {:.3f}".format(i, loss(model, x, y)))

**Does not work:**

If I replace 

    self.layer1= tf.keras.layers.Conv2D(32, (3, 3), input_shape=(32,32,3), padding='same', activation='relu')

with

    self.layer1= tf.keras.layers.Conv2D(32, (3, 3), input_shape=(32,32,3), padding='same', activation='relu',kernel_constraint=maxnorm(3))

I obtain the error:

    RuntimeErrorTraceback (most recent call last)
    <ipython-input-74-629273c4a534> in <module>()
         19 
         20   optimizer.apply_gradients(zip(grads, model.variables),
    ---> 21                             global_step=tf.train.get_or_create_global_step())
         22   if i % 200 == 0:
         23     pass
    
    /home/dgoldma1/.local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.pyc in apply_gradients(self, grads_and_vars, global_step, name)
        615           scope_name = var.op.name
        616         with ops.name_scope("update_" + scope_name), ops.colocate_with(var):
    --> 617           update_ops.append(processor.update_op(self, grad))
        618       if global_step is None:
        619         apply_updates = self._finish(update_ops, name)
    
    /home/dgoldma1/.local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.pyc in update_op(self, optimizer, g)
        166     if self._v.constraint is not None:
        167       with ops.control_dependencies([update_op]):
    --> 168         return self._v.assign(self._v.constraint(self._v))
        169     else:
        170       return update_op
    
    /home/dgoldma1/.local/lib/python2.7/site-packages/keras/constraints.pyc in __call__(self, w)
         51         norms = K.sqrt(K.sum(K.square(w), axis=self.axis, keepdims=True))
         52         desired = K.clip(norms, 0, self.max_value)
    ---> 53         w *= (desired / (K.epsilon() + norms))
         54         return w
         55 
    
    /home/dgoldma1/.local/lib/python2.7/site-packages/tensorflow/python/ops/resource_variable_ops.pyc in __imul__(self, unused_other)
        931 
        932   def __imul__(self, unused_other):
    --> 933     raise RuntimeError("Variable *= value not supported. Use "
        934                        "variable.assign_mul(value) to modify the variable "
        935                        "value and variable = variable * value to get a new "
    
    RuntimeError: Variable *= value not supported. Use variable.assign_mul(value) to modify the variable value and variable = variable * value to get a new Tensor object.

Thanks!

**Comment by asimshankar** [comment]
Thanks for the report!

Which version of TensorFlow are you using? I suspect 1.7.
This should have been fixed in 1.8 via [this commit](https://github.com/tensorflow/tensorflow/commit/255712a4544a404177d75d492713c0267f874f60#diff-4a7c925d693473a6751c940335523e14).

Let us know if that is not the case. Thanks!

**Comment by asimshankar** [comment]
Oh wait, from the stack trace I see you're using `keras.max_norm` instead of `tf.keras.max_norm`. Is that accurate? Could you switch to `tf.keras.max_norm` instead?

Note that the Keras implementation in `tf.keras` includes features (such as compatibility with eager execution) that are not part of the `keras` package.

**Comment by doriang102** [comment]
Thanks! I changed my code to

```
self.layer3=tf.keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same',kernel_constraint=tf.keras.constraints.max_norm(3))
```

And now this works. I'm closing the issue.
