### ISSUE TITLE
macOS build fail on __shared__ variable

### ISSUE THREAD

**Issue by yarrseni** [tensorflow/tensorflow#19646]
- **Code changes**:
Fixes from https://github.com/tensorflow/tensorflow/issues/17067#issuecomment-366544970 .
Fix from https://github.com/tensorflow/tensorflow/issues/18564#issue-314731167
Fix from https://github.com/tensorflow/tensorflow/issues/14174#issuecomment-342163130

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
macOS High Sierra 10.13.4 (17E202)
XCode 7.2.1, XCode 8.2

- **TensorFlow installed from (source or binary)**:
During compilation from sources

- **TensorFlow version (use command below)**:
1.6.0, 1.7.1

- **Python version**: 
3.6.5

- **Bazel version (if compiling from source)**:
Build label: 0.13.1-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed May 23 16:57:59 2018 (1527094679)
Build timestamp: 1527094679
Build timestamp as int: 1527094679

- **GCC/Compiler version (if compiling from source)**:
XCode 7.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin17.5.0
Thread model: posix

- **CUDA/cuDNN version**:
CUDA 9.2
cudNN 7.1.4

- **GPU model and memory**:
GeForce 1080Ti 11Gb

- **Exact command to reproduce**:
`bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

### Describe the problem
During compilation from sources, an errorr occurs about __shared__ variable expression used. 

### Source code / logs
`INFO: From Compiling tensorflow/core/kernels/reduction_ops_gpu_complex64.cu.cc:
./tensorflow/core/lib/core/status.h(32): warning: attribute "warn_unused_result" does not apply here

external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/Meta.h(187): warning: missing return statement at end of non-void function "Eigen::internal::device::numeric_limits<T>::quiet_NaN [with T=std::__1::complex<float>]"
          detected during:
            instantiation of "T Eigen::internal::device::numeric_limits<T>::quiet_NaN() [with T=std::__1::complex<float>]" 
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/NumTraits.h(180): here
            instantiation of "T Eigen::GenericNumTraits<T>::quiet_NaN() [with T=std::__1::complex<float>]" 
./tensorflow/core/kernels/reduction_ops.h(59): here

external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/NumTraits.h(180): warning: calling a __host__ function from a __host__ __device__ function is not allowed
          detected during instantiation of "T Eigen::GenericNumTraits<T>::quiet_NaN() [with T=std::__1::complex<float>]" 
./tensorflow/core/kernels/reduction_ops.h(59): here

external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/Meta.h(187): warning: missing return statement at end of non-void function "Eigen::internal::device::numeric_limits<T>::quiet_NaN [with T=std::__1::complex<double>]"
          detected during:
            instantiation of "T Eigen::internal::device::numeric_limits<T>::quiet_NaN() [with T=std::__1::complex<double>]" 
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/NumTraits.h(180): here
            instantiation of "T Eigen::GenericNumTraits<T>::quiet_NaN() [with T=std::__1::complex<double>]" 
./tensorflow/core/kernels/reduction_ops.h(60): here

external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/NumTraits.h(180): warning: calling a __host__ function from a __host__ __device__ function is not allowed
          detected during instantiation of "T Eigen::GenericNumTraits<T>::quiet_NaN() [with T=std::__1::complex<double>]" 
./tensorflow/core/kernels/reduction_ops.h(60): here

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(271): error: initializer not allowed for __shared__ variable 

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(319): error: initializer not allowed for __shared__ variable 

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(271): error: initializer not allowed for __shared__ variable 

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(319): error: initializer not allowed for __shared__ variable 

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(271): error: initializer not allowed for __shared__ variable 

./tensorflow/core/kernels/reduction_gpu_kernels.cu.h(319): error: initializer not allowed for __shared__ variable 

external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/NumTraits.h(180): warning: calling a __host__ function("Eigen::internal::device::numeric_limits< ::std::__1::complex<float> > ::quiet_NaN") from a __host__ __device__ function("Eigen::GenericNumTraits< ::std::__1::complex<float> > ::quiet_NaN") is not allowed

6 errors detected in the compilation of "/var/folders/by/bnpbnnbj2m180m_vjq9l97n40000gn/T//tmpxft_00009e05_00000000-6_reduction_ops_gpu_complex64.cu.cpp1.ii".
ERROR: tensorflow/tensorflow/core/kernels/BUILD:2796:1: output 'tensorflow/core/kernels/_objs/reduction_ops_gpu/tensorflow/core/kernels/reduction_ops_gpu_complex64.cu.pic.o' was not created
ERROR: tensorflow/tensorflow/core/kernels/BUILD:2796:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 486.544s, Critical Path: 212.55s
INFO: 595 processes, local.
FAILED: Build did NOT complete successfully`

**Comment by luizzanlorensi** [comment]
I also have this exact problem, but I'm trying to run on ubuntu 16.04.
Please, if you fix it, let me know!

**Comment by yarrseni** [comment]
@luizzanlorensi I managed to compile v1.7.1 by downgrading to CUDA9.1+cudnn7, so I think this is CUDA-wide issue so far.

**Comment by luizzanlorensi** [comment]
@yarrseni Thanks!
I downgrading to cuda 9.0, then installed tensorflow 1.8 via pip, now everything is working!

**Comment by fqx** [comment]
@yarrseni How did you downgrade to CUDA9.1? I thought only CUDA 9.2 supports macOS High Sierra 10.13.4 (17E202). What is your macOS / nVidia display driver / CUDA driver combination?

**Comment by yarrseni** [comment]
@fqx I just installed the cuda from here [https://developer.nvidia.com/cuda-91-download-archive?target_os=MacOSX&target_arch=x86_64&target_version=1013](CUDA9.1 for mac). I think the support for CUDAs is for second (10.**13**) part of version, so 10.13.3 or 10.13.4 does not matter (and it works).

To downgrade, follow the instructions to uninstall CUDA9.2 (it should be somewhere in the docs, it involves running a perl script that is created during installation basically).

**Comment by fqx** [comment]
@yarrseni Thank you for your reply! I could finally use wheels from this site https://j74th.com/tensorflow/
macOS tensorflow with eGPU users were usually overlooked by official communities, solutions are hard to find. I encourage you share your compiled wheels on GitHub.

**Comment by karmel** [comment]
Closing as this issue seems resolved. Please reopen if there is still a problem.

**Comment by Tayseer-bme** [comment]
I have the same problem but I have not the permission to downgrade CUDA because I'm working on the Cluster from the university and they have their own version of cuda
Python 3.6.8 Anaconda
CUDA/cuDNN version:
CUDA 10
cudNN 7
Any solution please ?

**Comment by cailun01** [comment]
> I have the same problem but I have not the permission to downgrade CUDA because I'm working on the Cluster from the university and they have their own version of cuda
> Python 3.6.8 Anaconda
> CUDA/cuDNN version:
> CUDA 10
> cudNN 7
> Any solution please ?

In reduction_gpu_kernels.cu.h(271) and reduction_gpu_kernels.cu.h(319), change 
```c++
__shared__ value_type partial_sums[32 * 33];
```
to
```c++
  __shared__ __align__(alignof(value_type)) char
      partial_sums_raw[32 * (32 + 1) *
                       sizeof(value_type)];
  value_type* partial_sums = reinterpret_cast<value_type*>(partial_sums_raw);
```
