### ISSUE TITLE
Crash when saving model: "tensorflow.GraphDef was modified concurrently during serialization"

### ISSUE THREAD

**Issue by samsamoa** [tensorflow/tensorflow#19657]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.13.4 (also Linux Ubuntu)
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A 
- **GPU model and memory**: N/A (problem on CPU and GPU)
- **Exact command to reproduce**: saver.save(sess,fname)

### Describe the problem
TF consistently crashes when saving a model after loading datasets of a certain size into memory and creating iterators for them.  This occurs both on macOS and on Linux.

Some additional information:
- If I make the iterators initializable instead of one-shot, there is no crash.
- If I only make one iterator (not two), there is no crash
- If I reduce the size of the dataset, there is no crash

### Source code / logs
The most minimal example I could come up with:
```
import numpy as np
import tensorflow as tf

### The following two lines are necsesary to cause the crash
### Also, reduce the size to eliminate the crash
data1 = tf.data.Dataset.from_tensor_slices(np.ones([20000000,2,2]))
iter1 = data1.make_one_shot_iterator()

data2 = tf.data.Dataset.from_tensor_slices(np.ones([20000000,2,2]))
iter2 = data2.make_one_shot_iterator()
feat2 = iter2.get_next()
out = tf.layers.dense(inputs=feat2, units=10)

saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Crash here
    saver.save(sess=sess,save_path='/tmp/crash-example')
```

This causes the following crash:
```
[libprotobuf FATAL external/protobuf_archive/src/google/protobuf/message_lite.cc:68] CHECK failed: (byte_size_before_serialization) == (byte_size_after_serialization): tensorflow.GraphDef was modified concurrently during serialization.
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (byte_size_before_serialization) == (byte_size_after_serialization): tensorflow.GraphDef was modified concurrently during serialization.
Aborted (core dumped)
```

**Comment by samsamoa** [comment]
Some additional information: if I make the iterators initializable instead of one-shot, there is no crash.   Also, the crash happens when I load SVHN, but not MNIST, so maybe it has something to do with the size of the dataset?

**Comment by girving** [comment]
If the size matters, it's possible this is related to some `2**32` size limit for protobuf.

**Comment by fogelton** [comment]
When I used feed for input data, no problem occured, now when using tf.data, the input is part of the graph resulting in this problem. Can I somehow save all variables except the input data? Respectively, can we save all trainable variables only?

**Comment by fogelton** [comment]
tf.saved_model.simple_save seems to work, I tried this example with a sufficiently large dataset, so large, I got the memory error
http://vict0rsch.github.io/2018/05/17/restore-tf-model-dataset/

**Comment by fogelton** [comment]
the same error rises when using SavedModelBuilder and this tutorial http://stackabuse.com/tensorflow-save-and-restore-models/

**Comment by samsamoa** [comment]
I now understand that this bug was caused because tf.data.Dataset.from_tensor_slices stores the entire dataset in the TF graph.  There is a comment on [the datasets guide](https://www.tensorflow.org/programmers_guide/datasets) about this, though if it's a new addition.

**Comment by asimshankar** [comment]
Apologies for the delayed response. Yup, `tf.data.Dataset.from_tensor_slices(x)` will embed `x` as a constant tensor inside the graph. With the dataset size you're describing, using an initializable iterator (as you suggested) with a placeholder would be more appropriate. Something like this:

```python
import tensorflow as tf
import numpy as np

data = tf.placeholder(tf.float32)
ds = tf.data.Dataset.from_tensor_slices(data)
itr = ds.make_initializable_iterator()
next = itr.get_next()

with tf.Session() as sess:
  # Feed the data when initializing the iterator
  sess.run(itr.initializer, feed_dict={data: np.random.rand(100, 100)})
  for _ in range(10):
    print(sess.run(next))
```

Without the placeholder, the tensor content ends up in the graph def. With `one_shot_iterator`, it ends up in the graph def twice.

@mrry @jsimsa : Perhaps the documentation could be enhanced to make this more obvious?

@samsamoa @fogelton : Does this sound reasonable?

**Comment by samsamoa** [comment]
Yes, this works well.  It is described well on the datasets guide, though not in the tf.Dataset documentation.

**Comment by fogelton** [comment]
ok, thanks

**Comment by amirnetflix** [comment]
Hi,

I have ` tf.data.Dataset.from_generator` in my code, and I get the exact same error while saving. 
Does the graph become too big even by using generators? 

Thanks

**Comment by asimshankar** [comment]
@amirmazaheri1990 : No, that shouldn't be the case, so you might want to file a separate issue, including more details on what you're doing. Perhaps some other aspect of your program results in large constants embedded in the graph?

**Comment by freshforlife** [comment]
@asimshankar  I'm running into the same issue while trying to train a dataset with 80,000 rows and 3800 columns ( i.e. 3800 covariates) using a LinearRegressor estimator( `tf.estimator.LinearRegressor`)  Your solution regarding using an initializable iterator doesn't work with the Estimator api easily (https://www.tensorflow.org/guide/datasets) Do you have an example where an estimator api for prediction works with an initializable iterator ?

**Comment by asimshankar** [comment]
@freshforlife : could you file a new issue with all the details (version etc) and ideally a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve). The original issue here seemed to be about reaching the 2GB limit on protobufs, so (without knowing all the details), your problem sounds different

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by zhanglirong1999** [comment]
> 

I use MonitoredTrainingSession not Session, and no initialization operations can be performed after MonitoredTrainingSession , So I used scaffold to initialize the data. But an error is reported: 'GetNext() failed because the iterator has not been initialized. Ensure that you have run the initializer operation for this iterator before getting the next element.'
How to use feed_dict in MonitoredTrainingSession and initialize the data correctly? Can you give me some examples? Thanks!
```python
import tensorflow as tf
import numpy as np
import pandas as pd
import time
import collections
import random
datas = np.random.rand(16000000)
features = tf.placeholder(tf.float32)
feed_dict = {features:datas}
dataset = tf.data.Dataset.from_tensor_slices(features)
dataset = dataset.batch(100)
dataset = dataset.prefetch(2)
iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()
global_step = tf.train.get_or_create_global_step()
sess_config = tf.ConfigProto()
scaffold = tf.train.Scaffold(
        init_op=iterator.initializer,
        local_init_op=tf.local_variables_initializer(),
        init_feed_dict=feed_dict,
       )
stop_hook = tf.train.StopAtStepHook(last_step=1000)
hooks = []
hooks.append(stop_hook)
tm = time.time()
with tf.train.MonitoredTrainingSession(
            scaffold=scaffold,
            hooks=hooks,
            checkpoint_dir = './result/ddd',
            save_checkpoint_steps=1000,
            summary_dir= None,
            save_summaries_steps=1000,
            config=sess_config) as sess:
    print(f'cost session create:{time.time() - tm:.8f}s')
    t2 = time.time()
    # sess.run(iterator.initializer,feed_dict={data: tuple([datas]*40)})
    for i in range(1,100):
        sess.run(next_element)
    print(f'cost run time:{time.time() - t2:.8f}s')
    print('done')
```
