### ISSUE TITLE
tf.layers.conv2d_transpose does not accept output_shape

### ISSUE THREAD

**Issue by boocheck** [tensorflow/tensorflow#19668]
I believe there is no reason why using layer interface user should not be able to specify this. Output shape is not obvious for some cases (as stated here: https://github.com/tensorflow/tensorflow/issues/2118) and without accepting output_shape argument one cannot match desired output. Potential use case is trying to build autoencoder for 2d images in form of (conv1->conv2->conv3->deconv1->deconv2->deconv3). With stride >1 there is no way for doing this with layers interface right now.

**Comment by facaiy** [comment]
duplication of #19236?

**Comment by drpngx** [comment]
So, I am going to close this since we are now recommending using the keras layers. Thank you for your understanding.
