### ISSUE TITLE
how could tf.nn.max_pool work with dynamic kernel size?

### ISSUE THREAD

**Issue by ahmed-touati** [tensorflow/tensorflow#1967]

**Comment by zheng-xq** [comment]
Not with the current op interface. You would have to write a new op that takes the kernel size as an input tensor. The kernel implementation can be refactored to use most of the current max_pool implementation.

**Comment by vincentvanhoucke** [comment]
Closing. Feel free to reopen if this is a feature request worth tracking.

**Comment by apple2373** [comment]
+1
I would like to request that feature.
