### ISSUE TITLE
incompatible with eager and graph when output of tf.keras.Model is a dictionary

### ISSUE THREAD

**Issue by zakizhou** [tensorflow/tensorflow#19687]
env: ubuntu18.04 python2.7 tensorflow1.8
```   
 import tensorflow as tf
 tf.enable_eager_execution()
 class Model(tf.keras.Model):
        def __init__(self):
            super(Model, self).__init__()

        def call(self, inputs):
            return {"inputs": inputs}
 m = Model()
 m(tf.random_uniform((2, 2)))
```
the code runs smoothly, but when I comment ` tf.enable_eager_execution()`, it raises error,  the compatibility between eager and graph is quite important, please have a see and fix it

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment]
@fchollet @brainnoise - Mind taking a look?

**Comment by brainnoise** [comment]
Hello @zakizhou, I believe this issue has been fixed by https://github.com/tensorflow/tensorflow/commit/693b339ab2f062ec5bbb29f976c5d1fd94fbffa5 . Can you please try this in tf-nightly?

**Comment by brainnoise** [comment]
Yes, it will be in 1.9 which will be available in the next few days.
