### ISSUE TITLE
What version of cuda and cudnn does TF 0.8 support?

### ISSUE THREAD

**Issue by ushnish** [tensorflow/tensorflow#1969]
Hi, I have installed Cuda 7.5 and Cudnn v5 for use with TensorFlow 0.8 and am getting the following error when trying to run /tensorflow/models/image/mnist/convolutional.py

F tensorflow/stream_executor/cuda/cuda_dnn.cc:427] could not set cudnn filter descriptor: CUDNN_STATUS_BAD_PARAM
Aborted (core dumped)

Should I be using an older version of Cuda and/or Cudnn? Thank you

**Comment by vrv** [comment]
See https://github.com/tensorflow/tensorflow/issues/1787#issuecomment-210560825

**Comment by petamem** [comment]
same here
