### ISSUE TITLE
Small typo in Beginners MNIST Tutorial

### ISSUE THREAD

**Issue by stanton119** [tensorflow/tensorflow#197]
There is an extra 'as' in the following sentence, in the "The MNIST Data" section:

>For the purposes of this tutorial, we're going to want our labels as as "one-hot vectors".

http://tensorflow.org/tutorials/mnist/beginners/index.md

**Comment by stanton119** [comment]
There's another one under the "Training" section as well:
>Because TensorFlow know the entire graph of your computations...

Should be:
>Because TensorFlow knows the entire graph of your computations...

**Comment by vrv** [comment]
Both of these are fixed in git, pending a push to the website, hopefully soon!
