### ISSUE TITLE
build tensorflow-lite example label_image to .so 

### ISSUE THREAD

**Issue by raninbowlalala** [tensorflow/tensorflow#19709]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.8.0 gpu
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:0.12.0
- **GCC/Compiler version (if compiling from source)**: c++11  
- **CUDA/cuDNN version**:7.5.18
- **GPU model and memory**:TITAN,12GB
- **Exact command to reproduce**:N/A

### Describe the problem
I want to use bazel to build label_image to .so file. I modified the BUILD in /tensorflow/contrib/lite/examples/label_image/BUILD like below:

```
package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

load("//tensorflow:tensorflow.bzl", "tf_cc_binary", "tf_copts", "if_android")
load("//tensorflow/contrib/lite:build_def.bzl", "tflite_linkopts")

exports_files([
    "version_script.lds",
])

filegroup(
    name = "label_image_src",
    srcs = glob([
        "label_image.cc",
        "bitmap_helpers.cc",
        "label_image.h",
        "bitmap_helpers.h",
    ]),
    visibility = ["//visibility:public"],
)

LINKER_SCRIPT = "//tensorflow/contrib/lite/examples/label_image:version_script.lds"

cc_binary(
    name = "libtflite_label_image.so",
    srcs = [],
    copts = tf_copts() + [
        "-ffunction-sections",
        "-fdata-sections",
    ],
    linkopts = if_android([
        "-landroid",
        "-latomic",
        "-ldl",
        "-llog",
        "-lm",
        "-z defs",
        "-s",
        "-Wl,--gc-sections",
        "-Wl,--version-script",  # This line must be directly followed by LINKER_SCRIPT.
        LINKER_SCRIPT,
    ]),
    linkshared = 1,
    linkstatic = 1,
    tags = [
        "manual",
        "notap",
    ],
    deps = [
        ":label_image",
        "//tensorflow/contrib/lite:framework",
        "//tensorflow/contrib/lite:string_util",
        "//tensorflow/contrib/lite/kernels:builtin_ops",
        "//tensorflow/core:android_tensorflow_lib",
        LINKER_SCRIPT,
    ],
)
cc_library(
    name = "label_image",
    srcs = if_android([":label_image_src"]),
    copts = tf_copts(),
    visibility = ["//visibility:public"],
    deps = [
        "//tensorflow/contrib/lite:framework",
        "//tensorflow/contrib/lite:string_util",
        "//tensorflow/contrib/lite/kernels:builtin_ops",
        "//tensorflow/core:android_tensorflow_lib_lite",
    ],
    alwayslink = 1,
)
```

I can generated libtflite_label_image.so successfully by using  command
`"bazel build --config monolithic --cxxopt=-std=c++11   --crosstool_top=//external:android/crosstool   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain   --cpu=arm64-v8a   //tensorflow/contrib/lite/examples/label_image:libtflite_label_image.so --verbose_failures"`
but when I test the libtflite_label_image.so by using Cmake file, I got the error ` undefined reference to `tflite::label_image::label_image`
I think maybe the .so file is generated uncorrectly, some one can help me?
Thank you!

**Comment by andrehentz** [comment]
Try removing "-Wl,--version-script" and LINKER_SCRIPT (those options might be hiding the symbols you care about)
