### ISSUE TITLE
Scikit Flow Readme file

### ISSUE THREAD

**Issue by Vlsarro** [tensorflow/tensorflow#1970]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/README.md

Seems to me that README file extension should be rst. But instead it is a markdown and now all links are broken etc.

If this is true then first row should be changed to `|License| |Join the chat at https://gitter.im/tensorflow/skflow|` and everything is alright.

**Comment by ilblackdragon** [comment]
@Vlsarro You are right, it was Rst (to put it in pip easily). Though now after move inside tensorflow, to easily display on website it should be Markdown. I'll address links to actually be markdown this weekend.

**Comment by Vlsarro** [comment]
@ilblackdragon Don't waste your time, I already fixed most of it yesterday. Just wanted to be sure that it should be markdown. Check pull request
