### ISSUE TITLE
ppc64le: //tensorflow/python:nn_test test fails

### ISSUE THREAD

**Issue by wdirons** [tensorflow/tensorflow#19700]
Please assign this issue to me and add the tag: stat:community support

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes, Have written a Dockerfile.gpu.ppc64le file and modified ci_parameterized_build.sh to allow for build/test runs on ppc64le. (Will submit as a PR)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ppc64le Ubuntu 16.04.4 
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master from may 30th
- **Python version**:  2.7.12
- **Bazel version (if compiling from source)**: 0.11.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.2.88, 7
- **GPU model and memory**: 2 P100 GPUs with 16 GB of memory each

- **Exact command to reproduce**:
bazel test --config=cuda -c opt --local_test_jobs=2 --cache_test_results=no --run_under=//tensorflow/tools/ci_build/gpu_build:parallel_gpu_execute //tensorflow/python:nn_test

### Describe the problem
```
======================================================================
FAIL: testNaNs (__main__.ReluTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/nn_test.runfiles/org_tensorflow/tensorflow/python/ops/nn_test.py", line 934, in testNaNs
    self.assertTrue(np.isnan(z).all())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 79 tests in 12.600s

FAILED (failures=1)
0.0208333333333
0.00566666666667
0.0075
0.0208333333333
0.00566666666667
0.0075
0.0208333333333
0.00566666666667
0.0075
0.0208333333333
0.00566666666667
0.0075
L2Loss gradient err = 9.6958e-12
L2Normalize gradient err = 4.2424e-08
L2Normalize gradient err = 5.45829e-07
L2Normalize gradient err = 7.61142e-05
================================================================================
```

### Source code / logs
[nn_test.log](https://github.com/tensorflow/tensorflow/files/2063777/nn_test.log)

**Comment by reedwm** [comment]
/CC @gunan, can you comment? I do not know the state of PowerPC support.

**Comment by gunan** [comment]
Triaged as requested by @wdirons

**Comment by wdirons** [comment]
@smatzek shared some information on this defect with me. There is an issue in Eigen opened for this http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1494 dealing with minmax nan propagation. Sam provided a patch that fixed this problem: http://eigen.tuxfamily.org/bz_attachmentbase/attachment.cgi?id=831, but the patch that was integrated into eigen added #ifdef __VSX__, that doesn't appear defined in Power as it is not following that code path.

I tried in my own environment patching https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L110 with the commit containing the patch for 1494 and it did not resolve the issue.

**Comment by wdirons** [comment]
With the latest code in the master branch, this test is now passing on ppc64le. My guess is this commit: https://github.com/tensorflow/tensorflow/commit/4bc01f8f63074337c846a1b60a4a2b88d420bd56 to update Eigen resolved the issue.
