### ISSUE TITLE
TF Lite wants help on Andorid Between ImageClassifier and ObjectDetection

### ISSUE THREAD

**Issue by cableyang** [tensorflow/tensorflow#19716]
Dear Sir/Madam:
       (1)I run tf-lite to recognize things ok according to 
 `https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#0`
     (2)But When I want to detect Objects on camera,Only `https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android`
     the first one use  `private Interpreter tflite` to run .lite for result,while the second one use `TensorFlowInferenceInterface` to build graph and feed inputs,this need to using bazel compile the whole project,a lot time need to spend
   So my Question is: Can Examples like the first one for Object Detection using lighweight interpreter?
    Plus tensorflow-lite is valued very import in many areas,Hope for talents helping,Thank you.
Plus 
OS Platform and Distribution:Ubuntu16.04LTS
TensorFlow installed from:PIP install
TensorFlow version:tensorflow-gpu:1.6
Bazel version:0.11.1
CUDA/cuDNN version
GPU model and memory:nvidia 1080TI 12G
Exact command to reproduce:N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by cableyang** [comment]
Dear Sir:
   I have learned the newest video on Tensorflow Lite by engineer Renming Gu,Shanghai ,China,R&D develop of Google.
   May I contact with him to give me some suggestions on Tensorflow Lite Examples.

**Comment by renminio** [comment]
@cableyang, 

I'm here. I notice you are in CN region, we have active forum here.
https://www.tensorflowers.cn/

As for knowledge discussion, I would prefer you go to forum or mail list. Github issues are more for tracking feature requests, issues etc.
