### ISSUE TITLE
Getting empty tensorflow installation

### ISSUE THREAD

**Issue by Diyago** [tensorflow/tensorflow#19729]
### System information

== cat /etc/issue ===============================================
Linux analyst-PC 4.4.0-124-generic #148~14.04.1-Ubuntu SMP Thu May 3 07:26:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="14.04.5 LTS, Trusty Tahr"
VERSION_ID="14.04"

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux analyst-PC 4.4.0-124-generic #148~14.04.1-Ubuntu SMP Thu May 3 07:26:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy                              1.14.3            
numpydoc                           0.7.0             
protobuf                           3.5.2.post1       
tensorflow-gpu                     1.5.1             
tensorflow-tensorboard             1.5.1             

== check for virtualenv =========================================
False

== tensorflow import ============================================

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda-9.0/lib64:/usr/local/cuda-9.0/lib64
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Sun Jun  3 23:29:37 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 660     Off  | 00000000:01:00.0 N/A |                  N/A |
| 30%   35C    P8    N/A /  N/A |    266MiB /  1998MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so.9.0.176
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-9.0/doc/man/man7/libcudart.7
/usr/local/cuda-9.0/doc/man/man7/libcudart.so.7
 
You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
#running from console says about unsupported operation.
#in jupyter notebook:
AttributeError: module 'tensorflow' has no attribute 'GIT_VERSION'

### Describe the problem
Then tried to import tensorflow, I get no error However tf.set_random_seed(random_state) - returns AttributeError: module 'tensorflow' has no attribute 'set_random_seed'

Then in the jupyter notebook with shit-tab get library help:
Type:        module
String form: <module 'tensorflow' (namespace)>
Docstring:   <no docstring>

Seems to isnt righ. However :

 ~ $ pip show tensorflow-gpu
Name: tensorflow-gpu
Version: 1.5.1
Summary: TensorFlow helps the tensors flow
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/analyst/anaconda3/lib/python3.6/site-packages
Requires: absl-py, wheel, six, tensorflow-tensorboard, numpy, protobuf
Required-by: 

$ pip show tensorflow  #Returns nothing
What might be wrong?

I have 2 active namaspaces: how to fix that:

    > tf.__path__
    
    _NamespacePath(['/home/aa/tensorflow', '/home/aa/anaconda3/lib/python3.6/site-packages/tensorflow'])

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by JaeDukSeo** [comment]
I used to get this problem as well. for me simply reinstalling did the trick. I know this is an obvious answer question but did you tried to reinstall it as well?

**Comment by Diyago** [comment]
I have tried to reinstall couple of times, different versions, even by trying manually deleting folders.

**Comment by JaeDukSeo** [comment]
@Diyago one method that worked for me was using the precomplied version
https://www.lfd.uci.edu/~gohlke/pythonlibs/#tensorflow

Maybe give this a try and for precomplied GPU version: https://github.com/mind/wheels

Let me know how it goes I wanna help

**Comment by michaelisard** [comment]
Was this helpful?

**Comment by JaeDukSeo** [comment]
haha I want to know as well

**Comment by Diyago** [comment]
Installing precomputed version leads me to another error, problems with intel libraries. Trying to solve such problem I found the solution
`
conda install -c anaconda tensorflow-gpu 
`

You can specify here version you want to install as well

**Comment by JaeDukSeo** [comment]
Great so lets close issue??

**Comment by michaelisard** [comment]
OK, closing, thanks very much @JaeDukSeo for solving the problem.
