### ISSUE TITLE
Faild clone libFuzzer when compiling tensorflow on win10

### ISSUE THREAD

**Issue by lzkmylz** [tensorflow/tensorflow#19722]
When compiling tensorflow on windows 10 with vs2017, follow error occor:

  Cloning into 'third_party/libFuzzer'...
  fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Failed to connect to chromium.googlesource.com port 443: Timed out
  fatal: clone of 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer' into submodule path 'third_party/libFuzzer' failed
  Failed to recurse into submodule path 'third_party/bloaty'
  CMake Error at D:/program/tfMake/tensorflow-master/tensorflow/contrib/cmake/build/grpc/tmp/grpc-gitclone.cmake:93 (message):
    Failed to update submodules in:
    'D:/program/tfMake/tensorflow-master/tensorflow/contrib/cmake/build/grpc/src/grpc'

However, open https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/  I see:
024d10d [libFuzzer] Delete llvm/lib/Fuzzer by vitalybuka · 8 months ago master 

The libFuzzer is already deleted. I think this is a bug need to fix.

Have I written custom code: No
OS Platform and Distribution: Windows 10
TensorFlow installed from: git clone
TensorFlow version: latest
Bazel version: 
CUDA/cuDNN version: CUDA9.0, cuDNN 7.0 for win10
GPU model and memory: GPU GTX970M, 3G
Exact command to reproduce:

code for CMake:
cmake .. -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe" -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe" -T v140 -A x64 -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=C:/Users/hasee/Anaconda3/python.exe -Dtensorflow_ENABLE_GPU=ON -DCUDNN_HOME="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0" -Dtensorflow_BUILD_SHARED_LIB=ON -Dtensorflow_ENABLE_GRPC_SUPPORT=ON -DCUDA_HOST_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe" -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX -Dtensorflow_BUILD_CC_EXAMPLE=OFF -Dtensorflow_BUILD_PYTHON_BINDINGS=OFF

code for MSBuild:
& "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" ALL_BUILD.vcxproj /m:1 /p:CL_MPCount=1 /p:Configuration=Release /p:Platform=x64 /p:PreferredToolArchitecture=x64 /filelogger

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by 7oud** [comment]
I meet the same situation, and compile tensorflow failed

**Comment by asimshankar** [comment]
Could you please provide all the details asked for in the issue template? For example, which version of the codebase is being built, what commands are being executed etc.

Thanks!

**Comment by 7oud** [comment]
## Objective
To inference my trained model in Windows using executable program without python, so I try to build tf follow [cmake](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md) instructions.
## Enviroment
Have I written custom code
**No**
OS Platform and Distribution
**Win10 Pro, VS2015**
TensorFlow installed from
**Source code**
TensorFlow version
**I git pull tf yesterday(08, Aug) and use master branch**
Bazel version
**Using cmake 3.10**
CUDA/cuDNN version
**Do not use GPU, tensorflow_GPU_ENABLE=OFF, but my PC has CUDA 9.0, cuDNN 7**
GPU model and memory
**N/A**
## Problem: 
### Build failed with gRPC supported
**Git clone grpc/third_party/libFuzzer failed**
Cloning into 'third_party/libFuzzer'...
fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Failed to connect to chromium.googlesource.com port 443: Timed out
### Build failed without gRPC supported
**tensorflow_ENABLE_GRPC_SUPPORT = OFF, cannot find "grpc++“ header file, why still need grpc related file?**
Error	C1083	Cannot open include file: 'grpc++/grpc++.h': No such file or directory (compiling source file D:\Workspace\Github\tensorflow\tensorflow\tensorflow\core\common_runtime\eager\context.cc)	tf_core_cpu	D:\Workspace\Github\tensorflow\tensorflow\tensorflow\core\distributed_runtime\rpc\grpc_server_lib.h	21

**Comment by lzkmylz** [comment]
@tensorflowbutler 
This issue has been solved and can be closed.

**Comment by kingbackyang** [comment]
@lzkmylz GRPC_URL https://github.com/lzkmylz/grpc 404，not a valid address?
