### ISSUE TITLE
Incorrect Download URL

### ISSUE THREAD

**Issue by cavedweller** [tensorflow/tensorflow#1975]
It appears the location has been changed and not updated in the tutorial.

```
sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl

Collecting tensorflow==0.8.0 from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
  HTTP error 404 while getting https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
  Could not install requirement tensorflow==0.8.0 from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl because of error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
Could not install requirement tensorflow==0.8.0 from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl for URL https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
```

**Comment by SirSpunky** [comment]
Getting the same error.

**Comment by leekkww** [comment]
Same.

**Comment by arainhyy** [comment]
Same!!!

**Comment by wkadwaikar** [comment]
Same!! :(

**Comment by vrv** [comment]
It's still 0.8.0rc0, we changed the install instructions before we uploaded the new packages.  Sigh.

Example:
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0rc0-cp27-none-linux_x86_64.whl

**Comment by wkadwaikar** [comment]
Not sure if this one is the new?
[https://pypi.python.org/packages/2.7/r/requests/requests-2.0.0-py2.py3-none-any.whl#md5=6af9c16dbddd2fc751ae4f1606d041e8](https://pypi.python.org/packages/2.7/r/requests/requests-2.0.0-py2.py3-none-any.whl#md5=6af9c16dbddd2fc751ae4f1606d041e8)

**Comment by wkadwaikar** [comment]
This works for mac:
`sudo pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.8.0rc0-py2-none-any.whl`

**Comment by vrv** [comment]
Fixed in github, pushed to website.

**Comment by Yaffa1607** [comment]
I'm stil getting the same error

**Comment by bhattad2** [comment]
I still get the same error

**Comment by twhetzel** [comment]
Following the installation instructions [here](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#virtualenv-installation) when I run this it works
```
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc1-py3-none-any.whl
```

BUT on the next step of 
```
pip3 install --upgrade $TF_BINARY_URL
```
I get the error `HTTP error 404 while getting https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc1-py3-none-any.whl`
```

**Comment by ckirksey3** [comment]
Same here 😭

**Comment by bhattad2** [comment]
I install tensorflow in conda environment and it worked. Maybe you should give a try. 

After installing anaconda make sure to set your path. Or else it would conda: command not available.

**Comment by Rampage89** [comment]
Use this URL: https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc0-cp27-none-linux_x86_64.whl

It works (replace rc1 for rc0)

**Comment by lemuriandezapada** [comment]
it works to install but doesn't work to run because it wants cuda 7.5 and the latest is 8 :P

**Comment by Rampage89** [comment]
create a simlink on the cuda 7.5 file to cuda 8.0 file with a same name and it works :P

**Comment by GoingMyWay** [comment]
Maybe you can just 

cpu
`pip install tensorflow`

gpu
`pip install tensorflow-gpu`
