### ISSUE TITLE
 auto load_file_system_library

### ISSUE THREAD

**Issue by u2takey** [tensorflow/tensorflow#19764]
From https://www.tensorflow.org/extend/add_filesys we can build a custom filesystem plugin, and explictily load it like this :

```
from tensorflow.python.framework import load_library
load_library.load_file_system_library("xxxx.so")
```
But this is hard to use, and user who want to use xxxx.so `must change his code`.
Is there a way to call `load_library.load_file_system_library` automatically when a environment variable such as `FILE_SYSTEM_LIBRARY` is set.

To sum up with a user story:
1. user set environment variable  FILE_SYSTEM_LIBRARY=xxxx.so
2. user use xxxx.so related method in his script directly without explictily loading  xxxx.so.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
