### ISSUE TITLE
tflitecamerademo error

### ISSUE THREAD

**Issue by bigbao9494** [tensorflow/tensorflow#19760]
hi,
    I test tflitecamerademo in tensorflow\contrib\lite\java\demo

Prompt me to download the file every day, and then compile it after downloading. Do these library files need to be updated every day? :
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve org.tensorflow:tensorflow-lite:+.
     Required by:
         project :app
      > Could not resolve org.tensorflow:tensorflow-lite:+.
         > Failed to list versions for org.tensorflow:tensorflow-lite.
            > Unable to load Maven meta-data from https://jcenter.bintray.com/org/tensorflow/tensorflow-lite/maven-metadata.xml.
               > Could not GET 'https://jcenter.bintray.com/org/tensorflow/tensorflow-lite/maven-metadata.xml'.
                  > jcenter.bintray.com
      > Could not resolve org.tensorflow:tensorflow-lite:+.
         > Failed to list versions for org.tensorflow:tensorflow-lite.
            > Unable to load Maven meta-data from https://google.bintray.com/tensorflow/org/tensorflow/tensorflow-lite/maven-metadata.xml.
               > Could not GET 'https://google.bintray.com/tensorflow/org/tensorflow/tensorflow-lite/maven-metadata.xml'.
                  > google.bintray.com

------------------------------------------------------------------------------------------------------
Another question, how to compile tflite.so by yourself instead of using downloaded tflite.so

thanks.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by shashishekhar** [comment]
@bigbao9494 I would suggest to use: 'org.tensorflow:tensorflow-lite:0.1.7'. instead of  'org.tensorflow:tensorflow-lite:+'
which pins the tensorflow lite version to use. This should not attempt to download a new version.

**Comment by Havelet** [comment]
Is there a clear way to solve this problem?
