### ISSUE TITLE
einsum contraction order (is undocumented)

### ISSUE THREAD

**Issue by mrader1248** [tensorflow/tensorflow#19776]
### Describe the problem
The documentation for `tf.einsum` does not specify the order of the contraction. However, for contractions with three and more tensors, the contraction order is crucial as it determines the runtime complexity. The only thing one finds in the documentation is the following:

> This function behaves like `numpy.einsum` [...]

The `numpy.einsum` function has an additional parameter `optimize` and is able to peform a greedy optimisation for the contraction order. As far as I understood the tensorflow code, `tf.einsum` simply contracts tensors from left to right.
Would it be possible to adopt the optimisation code from numpy for tensorflow? If not, at least the documentation should indicate the contraction order. Thank you!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mrader1248** [comment]
Dear @tensorflowbutler, the issue template is not relevant for this issue as this is a documentation issue.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by mrader1248** [comment]
Is there a formal dependence of tensorflow on numpy (and if yes, which version)? If I could use numpy 1.14, the numpy function `einsum_path` [1] could be used to implement this.

[1] https://docs.scipy.org/doc/numpy/reference/generated/numpy.einsum_path.html

**Comment by rthadur** [comment]
Closing this issue , Please refer this link for update https://github.com/tensorflow/tensorflow/pull/23921#issuecomment-518861095 . Thank you.
