### ISSUE TITLE
Tensorflow logs everything twice while training

### ISSUE THREAD

**Issue by achraf-boussaada** [tensorflow/tensorflow#19795]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
macOS Sierra version 10.12.6
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
1.8.0
- **Python version**: 
3.6.5
- **Bazel version (if compiling from source)**:
0.13.0
- **GCC/Compiler version (if compiling from source)**:
GCC 4.2.1

### Describe the problem
I'm training an object detection model using the new `ssdlite_mobilenet_v2_coco_2018_05_09` and it's configuration file `ssdlite_mobilenet_v2_coco.config` and tensorflow installed from source. When I launch the training tensorflow starts printing the same info twice. 

This problem didn't happen while training the same network I'm trying to get, with a different model (checkpoint)  `ssd_mobilenet_v1_coco_2017_11_17` and the configuration file `ssd_mobilenet_v1_pets.config` and with tensorflow installed from pip (I tested with version 1.6.0 and 1.8.0) 

NOTE : I didn't change the code in both cases and I wonder what's the cause of this.

### Source code / logs

```
INFO:tensorflow:global step 3292: loss = 3.2832 (2.960 sec/step)
INFO:tensorflow:global step 3292: loss = 3.2832 (2.960 sec/step)
INFO:tensorflow:global step 3293: loss = 3.5285 (3.675 sec/step)
INFO:tensorflow:global step 3293: loss = 3.5285 (3.675 sec/step)
INFO:tensorflow:global step 3294: loss = 2.3972 (3.564 sec/step)
INFO:tensorflow:global step 3294: loss = 2.3972 (3.564 sec/step)
INFO:tensorflow:Recording summary at step 3294.
INFO:tensorflow:Recording summary at step 3294.
INFO:tensorflow:global_step/sec: 0.294019
INFO:tensorflow:global_step/sec: 0.294019
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by achraf-boussaada** [comment]
I'm using CPU only and the command to execute the training is (for both cases) : 

    python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/name_of_config_file.config

**Comment by xuyithu** [comment]
I got the same problem.

**Comment by xuyithu** [comment]
I got the same problem while training detectors using tools from the "models" repo, under models/research/object_detection. I am using tensorflow-gpu version.

**Comment by robieta** [comment]
Could you reopen this issue in the `tensorflow/models` repo issues?

**Comment by achraf-boussaada** [comment]
@robieta done [#4517](https://github.com/tensorflow/models/issues/4517)
