### ISSUE TITLE
tflite toco build failed in version of 3daa07aa2dde379388beb2a557a78bc5dd1b86ba

### ISSUE THREAD

**Issue by wenhui7909** [tensorflow/tensorflow#19798]
### System information
- Have I written custom code : No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: tensorflow 1.8
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.13.0
- **GCC/Compiler version (if compiling from source)**: 6.4
- **CUDA/cuDNN version**: None
- **GPU model and memory**: GeForce GTX 750
- **Exact command to reproduce**: tensorflow code :
 commit 3daa07aa2dde379388beb2a557a78bc5dd1b86ba
Author: Courtial Florian <floriancourtial@gmail.com>
Date:   Wed Jun 6 01:02:07 2018 +0200
    Add C++ no gradient for Floor operation. (#19662)

### Describe the problem
Use cmd below: 
bazel build --config android_arm --cxxopt=-std=c++11  //tensorflow/contrib/lite/toco:toco   --config monolithic

My WORKSPACE as below:
WORKSPACE

android_sdk_repository(
    name = "androidsdk",
    api_level = 22,
    # Ensure that you have the build_tools_version below installed in the
    # SDK manager as it updates periodically.
    build_tools_version = "27.0.3",
    # Replace with path to Android SDK on your system
    path = "/home/hwh/Android/Sdk",
)

android_ndk_repository(
    name="androidndk",
    path="/home/hwh/Android/Ndk/android-ndk-r14b",
    # This needs to be 14 or higher to compile TensorFlow.
    # Please specify API level >= 21 to build for 64-bit architecture
    # otherwise the Android NDK will automatically select the latest
    # API level it does support without notice.
    # Note that the NDK version is not the API level.
    api_level=14)

build failed as below:
INFO: Found 1 target...
ERROR: /home/hwh/.cache/bazel/_bazel_hwh/a5d93fc2a8e4cfbb4b042a3b705d2c38/external/gif_archive/BUILD.bazel:8:1: C++ compilation of rule '@gif_archive//:gif' failed (Exit 1)
external/gif_archive/lib/openbsd-reallocarray.c:33:19: error: use of undeclared identifier 'SIZE_MAX'
            nmemb > 0 && SIZE_MAX / nmemb < size) {
                         ^
1 error generated.
Target //tensorflow/contrib/lite/toco:toco failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 167.962s, Critical Path: 29.34s
INFO: 374 processes, local.
FAILED: Build did NOT complete successfully

**Comment by wenhui7909** [comment]
Now I can build toco by the command below:
bazel build tensorflow/contrib/lite/toco:toco

**Comment by asimshankar** [comment]
I don't believe that the `toco` binary is meant to be compiled with `--config=android_arm`, so I think this is working as intended.

CC @suharshs @aselle

**Comment by wenhui7909** [comment]
Yes, I found I needn't set to arm platform as you figured out this.
And I had a mistake to used this opt of  --config=android_arm because the
comment below:

commit 320d8056af7799ab20e339757cf379963148425a
Author: freedom" Koan-Sin Tan <koansin.tan@gmail.com>
Date:   Mon Jun 4 12:49:17 2018 +0800

    make toco build for android (#17885)

    * make toco build for android



2018-06-07 17:35 GMT+08:00 Asim Shankar <notifications@github.com>:

**Comment by asimshankar** [comment]
Great, so if I understand correctly, there is no issue now?

**Comment by wenhui7909** [comment]
Yes, No issue for me, thanks a lot.

2018-06-09 0:41 GMT+08:00 Asim Shankar <notifications@github.com>:
