### ISSUE TITLE
cumulative longer epochs

### ISSUE THREAD

**Issue by graphific** [tensorflow/tensorflow#198]
A simple logistic regression (or any other function for that matter), incurs a hefty penalty over time. Code [gist here](https://gist.github.com/graphific/7f0a214350fd763275b8). 
Each training epoch takes increasingly longer, from 1.7s for th first epoch and already at 2.7 at 20 epochs:

	Epoch: 0001 cost= 29.860479714
	time this epoch= 1.749361
	Epoch: 0002 cost= 22.108508758
	time this epoch= 1.873362
	Epoch: 0003 cost= 21.061937475
	time this epoch= 2.053877
	Epoch: 0004 cost= 20.553687506
	time this epoch= 2.401098
	Epoch: 0005 cost= 20.262585952
	time this epoch= 2.563413
	Epoch: 0006 cost= 19.878952036
	time this epoch= 2.675142
	Epoch: 0007 cost= 19.573502880
	time this epoch= 2.638027
	Epoch: 0008 cost= 19.433302383
	time this epoch= 2.632813
	Epoch: 0009 cost= 19.428594169
	time this epoch= 2.616152
	Epoch: 0010 cost= 19.276754012
	time this epoch= 2.553015
	Epoch: 0011 cost= 19.082279745
	time this epoch= 2.571626
	Epoch: 0012 cost= 19.017995413
	time this epoch= 2.657914
	Epoch: 0013 cost= 18.981637795
	time this epoch= 2.684047
	Epoch: 0014 cost= 18.957392608
	time this epoch= 2.626817
	Epoch: 0015 cost= 18.679365802
	time this epoch= 2.629546
	Epoch: 0016 cost= 18.732087401
	time this epoch= 2.633352
	Epoch: 0017 cost= 18.655737654
	time this epoch= 2.662984
	Epoch: 0018 cost= 18.450943058
	time this epoch= 2.765998
	Epoch: 0019 cost= 18.539302767
	time this epoch= 2.774611
	Epoch: 0020 cost= 18.555477153
	time this epoch= 2.79623
	Epoch: 0021 cost= 18.401914994
	time this epoch= 2.81699
	Epoch: 0022 cost= 18.408855550
	time this epoch= 2.864744
	Epoch: 0023 cost= 18.456620145
	time this epoch= 2.852341
	Epoch: 0024 cost= 18.365951549
	time this epoch= 2.787942
	Epoch: 0025 cost= 18.230793715
	time this epoch= 2.748816

it might be something wrong in the code, or things to be fixed with tensorflow, any ideas?

**Comment by vrv** [comment]
I am not able to reproduce this unfortunately:

```
Epoch: 0001 cost= 29.860476766
time this epoch= 6.674506
Epoch: 0002 cost= 22.030540740
time this epoch= 3.98675
Epoch: 0003 cost= 21.065916606
...

time this epoch= 6.122648
Epoch: 0023 cost= 18.377196394
time this epoch= 6.448846
Epoch: 0024 cost= 18.326277539
time this epoch= 6.469679
Epoch: 0025 cost= 18.222360275
time this epoch= 6.436373

```
It's a bit noisy, but it doesn't look like it's consistently increasing.

**Comment by graphific** [comment]
@vrv k tnx for testing, ill run it over a few different machines as well, and see if I can narrow it down.

**Comment by vrv** [comment]
(Clearing out our open issues list: feel free to reopen if you still think there's a problem)
