### ISSUE TITLE
Illegal Instruction Error when Importing TensorFlow Module

### ISSUE THREAD

**Issue by bvanfleet** [tensorflow/tensorflow#19809]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: binary (native pip and Anaconda), also attempted compiling source and received same error
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: Tried 2.7 and 3.6.5
- **Bazel version (if compiling from source)**: 0.14.0
- **GCC/Compiler version (if compiling from source)**: 7.3.0
- **GPU model and memory**: CPU install only with 4GB memory
- **Exact command to reproduce**:

```python
import tensorflow as tf
```

### Describe the problem

When attempting to import the TensorFlow module into python the error `illegal instruction (core dumped)` is thrown.

I am installing TensorFlow as part of university research on a home lab rack server (HP Proliant DL380 G7 with Intel Xeon 5675 processors) with a Ubuntu 18.04 VM on a Hyper V host. When I complete the installation instructions and attempt to validate the instruction, I receive the above error message.

I've attempted in a local workstation virtual environment with VMware, and it worked fine (albeit with instruction warnings that did not impede expected results).

### Troubleshooting steps taken

* Reviewed StackOverflow community, wasn't able to find a resolution
  * We are required to use r1.8 so we're not able to downgrade to r1.5 at this time.
* Attempted both binary and compiled installation.
* Attempted installation via Anaconda and native pip for Python 2.7.n and Pyhon 3.6.5
* Tried a separate VM (using a local workstation).

**Comment by bvanfleet** [comment]
If it helps, while I was trying to troubleshoot, I ran the validation script below through python3.6-dbg:

```python
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))
```

During execution I saw the same few errors thrown a couple of times :

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "~/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tf-fail.py", line 1, in <module>
    import tensorflow as tf
  File "~/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 47, in <module>
    import numpy as np
  File "~/.local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "~/.local/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "~/.local/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "~/.local/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "~/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray'
```

I've uninstalled and reinstalled numpy a couple of times on my machine and went through numpy's basic troubleshooting steps to verify that the expected version is being pulled.

Are there any known version limits with numpy? I'm assuming not, but I want to check. I'm using v1.14.3

**Comment by bvanfleet** [comment]
I figured it out, it's my processor. From what I recall, TensorFlow started compiling versions after r1.5 to use AVX support. However, my server's processor (Intel X5675) doesn't have AVX support.

I was looking to perform some upgrades to my server anyway, guess the processors need to be first for this project. I'll go ahead with closing this out as this is a hardware issue, and not software.

**Comment by Yumin-Sun-00** [comment]
I got the same problem.

`import tensorflow as ts`

it returns `illegal instruction`.

```
tensorflow 2.1.0
cuda 10.2
gcc 7.4
ubuntu 1804
python 3.6.9
```
