### ISSUE TITLE
./configure failed on mac with GPU support

### ISSUE THREAD

**Issue by hlzz** [tensorflow/tensorflow#1983]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: mac os 10.11

Installed version of CUDA and cuDNN: 7.5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
-rwxr-xr-x  1 root  wheel  8280 Oct 29 09:50 /usr/local/cuda/lib/libcuda.dylib
lrwxr-xr-x@ 1 root  wheel    45 Sep 25  2015 /usr/local/cuda/lib/libcudadevrt.a -> /Developer/NVIDIA/CUDA-7.5/lib/libcudadevrt.a
lrwxr-xr-x@ 1 root  wheel    50 Sep 25  2015 /usr/local/cuda/lib/libcudart.7.5.dylib -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart.7.5.dylib
lrwxr-xr-x@ 1 root  wheel    46 Sep 25  2015 /usr/local/cuda/lib/libcudart.dylib -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart.dylib
lrwxr-xr-x@ 1 root  wheel    49 Sep 25  2015 /usr/local/cuda/lib/libcudart_static.a -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart_static.a

If installed from binary pip package, provide:

1. Which pip package you installed.
alembic (0.8.5)
appnope (0.1.0)
Babel (2.2.0)
cffi (1.5.2)
click (6.4)
colorama (0.3.7)
cryptography (1.3.1)
cvxopt (1.1.8)
Cython (0.23.4)
decorator (4.0.9)
enum34 (1.1.2)
Flask (0.10.1)
Flask-AppBuilder (1.6.0)
Flask-BabelPkg (0.9.6)
Flask-Cache (0.13.1)
Flask-Login (0.2.11)
Flask-Migrate (1.8.0)
Flask-OpenID (1.2.5)
Flask-Script (2.0.5)
Flask-SQLAlchemy (2.0)
Flask-Testing (0.4.2)
Flask-WTF (0.12)
gnureadline (6.3.3)
gunicorn (19.4.5)
h5py (2.5.0)
humanize (0.5.1)
idna (2.1)
ipaddress (1.0.16)
ipython (4.1.2)
ipython-genutils (0.1.0)
itsdangerous (0.24)
Jinja2 (2.8)
Mako (1.0.4)
Markdown (2.6.6)
MarkupSafe (0.23)
numpy (1.11.0)
pathlib2 (2.1.0)
pexpect (4.0.1)
pickleshare (0.7.2)
pip (8.1.1)
ptyprocess (0.5.1)
pyasn1 (0.1.9)
pycparser (2.14)
python-editor (0.5)
python-openid (2.2.5)
setuptools (20.9.0)
simplegeneric (0.8.1)
six (1.10.0)
speaklater (1.3)
SQLAlchemy (1.0.12)
traitlets (4.2.1)
vboxapi (1.0)
Werkzeug (0.11.5)
wheel (0.26.0)
WTForms (2.1)

2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

If installed from sources, provide the commit hash:

### Steps to reproduce
I tried to build tensorflow from source on macbook pro. It only looks for .so cuda library but on mac the shared libraries end with .dylib. Also it only looks for lib64 sub-directory, which is not present for cuda 7.5 on mac, in which the libraries are in /usr/local/cuda/lib folder. Does the configure script support mac with gpu now?

Tianweis-Macbook:tensorflow STW$ ./configure 
Please specify the location of python. [Default is /usr/local/bin/python]: 
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc nvcc should use as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Invalid path to CUDA  toolkit. /usr/local/cuda/lib64/libcudart.so cannot be found
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 

### What have you tried?
I tried to build tensorflow on mac with GPU support. It seems that tensorflow only supports gpu build on linux?

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by vrv** [comment]
Yes, we don't yet support GPU on Mac.

**Comment by vrv** [comment]
Closing as dup of #491
