### ISSUE TITLE
XLA Compile error: Operation has no attr named '_XlaCompile'

### ISSUE THREAD

**Issue by prasadwork** [tensorflow/tensorflow#19849]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from**: pip (Command: pip install tensorflow-gpu)
- **TensorFlow version**: v1.8.0-0-g93bc2e2072  1.8.0
- **Python version**: Python 3.6.4 :: Anaconda, Inc.
- **CUDA/cuDNN version**: CUDA Version 9.0.176 / cuDNN: 7.0.5.15
- **Bazel version**: N/A
- **GPU model and memory**: GeForce GTX 1080 / 8 GB
- **Exact command to reproduce**: python filename.py
- **Have I written custom code**: No

### Describe the problem
I am running the below code. I am getting the XLA Compiler error as mentioned below. I am having Tensorflow GPU version, but I did try with CPU version and I was getting the error. But when I downgraded Tensorflow (CPU) to 1.3 I was not getting any error. 
Please can somebody help me in this.

### Source code / logs
```
import tensorflow as tf
input_tensor = tf.placeholder(dtype=tf.float32, shape=[None, 16, 16, 3])
print(input_tensor.shape)

conv_filter = tf.get_variable('conv_filter', shape=[2, 2, 3, 6], dtype=tf.float32)
conv1 = tf.nn.conv2d(input_tensor, conv_filter, strides=[1, 2, 2, 1], padding='SAME')
print(conv1.shape)

deconv_filter = tf.get_variable('deconv_filter', shape=[2, 2, 6, 3], dtype=tf.float32)

deconv = tf.nn.conv2d_transpose(input_tensor, filter=deconv_filter,
    output_shape=tf.shape(input_tensor),
    strides=[1, 2, 2, 1],
    padding='SAME')
print(deconv.shape)

t = tf.reduce_mean(deconv)
g = tf.train.AdamOptimizer(0.01).minimize(t)
```

Error:
```
(?, 16, 16, 3)
(?, 8, 8, 6)
(?, 16, 16, 3)     # <<<<< This should have printed (?, ?, ?, ?)

Traceback (most recent call last):
  File "/my/path/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'conv2d_transpose' has no attr named '_XlaCompile'.

Traceback (most recent call last):
  File "/my/path/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 380, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "/my/path/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2331, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'conv2d_transpose' has no attr named '_XlaCompile'.
```

The error is coming in the line `g = tf.train.AdamOptimizer(0.01).minimize(t)`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version
GPU model and memory
Exact command to reproduce

**Comment by drpngx** [comment]
@tatatodd could you take a look?

**Comment by prasadwork** [comment]
I am really sorry. The problem is happening because of mismatch in the shape of filter and strides associated with it to produce the required output shape. I should have set deconvolution filter shape of [1, 1, 3, 3] and strides at [1, 1, 1, 1]. Then the above example would work.

My sincere apologies in wasting the time of developers.
