### ISSUE TITLE
Protobuff file in Android example - "TF Detect" app

### ISSUE THREAD

**Issue by IvanAntunovic** [tensorflow/tensorflow#19851]
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**
Linux Ubuntu 16.04
**TensorFlow installed from (source or binary):**
Source.
**TensorFlow version (use command below):**
1.8.0
**Python version:**
2.7.12
**Bazel version (if compiling from source):**
0.13.0
**GCC/Compiler version (if compiling from source):**
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

Sorry if this is wrong place to ask, since my question is not related to any bug/error. 
I have already asked on StackOverflow and nobody has given me an answer, so I decided to ask it here. 

In android example https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android , there is "ssd_mobilenet_v1_android_export.pb" that gets stored in assets folderT once gradle is run. The model seems to be trained using COCO dataset.

I would like to know where I can find original .cfg and .weights files of the CNN in order to do my own training. I could not find anything online.

Thank you in advance.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by michaelisard** [comment]
Closing this: I think stackoverflow is still your best bet for this kind of support, sorry!
