### ISSUE TITLE
Tensorflow Backend error on Pycharm

### ISSUE THREAD

**Issue by MohammadUmer526** [tensorflow/tensorflow#19857]
**Using Tensorflow backend** 
I have set anaconda environment on pycharm and also installed keras and tensorflow packages but it shows error **Using Tensorflow Backend**

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by MohammadUmer526** [comment]
@tensorflowbutler I switched from Pycharm to JupyterNotebook and it works fine on it. I am going to close this issue. Thanks for your co-operation!!!
