### ISSUE TITLE
Wrong calculation for conv2d_transpose outpu shape with stride != 1

### ISSUE THREAD

**Issue by 2649** [tensorflow/tensorflow#19863]
I work on convolutional auto encoder and recognized that the calculation of the conv2d_transpose output shape for a stride > 1 is wrong.  

Considering an input shape of [2, 74, 74, 16], a kernel of [3, 3], a stride of (2,2) and the 24 output filter the following code for a minimal AE would be this:

``conv_input = tf.placeholder("float32", [2, 74, 74, 16])``
``print(conv_input)``
``conv = tf.layers.conv2d(conv_input, 24, [3,3],strides=(2,2))``
``print(conv)``
``deconv = tf.layers.conv2d_transpose(conv, 16, [3, 3], strides=(2,2))``
``print(deconv)``

The output is:

![grafik](https://user-images.githubusercontent.com/17809849/41171901-62425888-6b52-11e8-8117-5ec0df63b859.png)

Should not the transpose operation restore the original shape or does this only appy on stride =1?
I also calculated the output shape by hand and get the same result. So not 100% sure if this is a bug.

**Comment by kr-ish** [comment]
see #2118 to understand why the shape of the output of conv2d_transpose is ambiguous with stride > 1
