### ISSUE TITLE
Tensorflow Testing Problem

### ISSUE THREAD

**Issue by mohsinali722** [tensorflow/tensorflow#19873]
Hi,
I am working on Tensorflow with Python. I have a new idea about the pooling method. Currently there are two pooling methods  (max-pooling, avg-pooling). I want to do some experiment by some new idea about pooling method. 
But for that i need to find the current pooling functions. But unfortunately i could not find that. Can anyone please help me to do this experiment and help me to find the exact flow of pooling because i am not so much fluent to Python.

 Thanks.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mohsinali722** [comment]
@poxvoculi Hi
I am working on Tensorflow with Python. I have a new idea about the pooling method. Currently there are two pooling methods  (max-pooling, avg-pooling). I want to do some experiment by some new idea about pooling method. 
But for that i need to find the current pooling functions. But unfortunately i could not find that. Can anyone please help me to do this experiment and help me to find the exact flow of pooling because i am not so much fluent to Python.

 Thanks.

**Comment by mohsinali722** [comment]
@tensorflowbutler ,  I don't know where to fill the fields you asked. So I am providing you information about these fields here:
Have I written custom code:    yes
OS Platform and Distribution:   Windows 10
TensorFlow installed from:      using pip
TensorFlow version:    1.7.0
Bazel version:   N/A
CUDA/cuDNN version:   8.0
GPU model and memory:     memory 24 GB
Exact command to reproduce  N/A

**Comment by mohsinali722** [comment]
@tensorflowbutler 
Please help to implement my idea about pooling.
Regards

**Comment by poxvoculi** [comment]
The pooling op source is in 
[pooling_ops_common.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/pooling_ops_common.cc)

and several similar files.  Look in core/kernels/* for anything with "pooling" in the name.

In the future, this sort of question is better asked on StackOverflow.  This forum is primarily for bug reports.
