### ISSUE TITLE
tensorflow/tensorflow/core/framework directory  not found BUILD file .

### ISSUE THREAD

**Issue by xxxx001** [tensorflow/tensorflow#19888]
why ， tensorflow/tensorflow/core/framework directory  not found BUILD file . ？

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by xxxx001** [comment]
System information
TensorFlow installed from (source or binary): source
TensorFlow version (use command below):  current master
