### ISSUE TITLE
tf.Print not printing

### ISSUE THREAD

**Issue by Cactucs** [tensorflow/tensorflow#1988]
### Environment info
Operating System: Ubuntu 14.04 LST
Tensorflow v0.7.1 (no CUDA)
Python 2.7.6

### Steps to reproduce
``` python
import tensorflow as tf
sess = tf.InteractiveSession()
x = tf.placeholder(tf.float32, shape=[None, 2, 2])
x = tf.Print(x, [x], message="P1")
i = tf.reshape(x, [-1, 4])
i = tf.Print(i, [i], message="P2")
i.eval(feed_dict={x: [[[1,2], [3,4]], [[5,6], [7,8]]]})
```
prints
``` 
I tensorflow/core/kernels/logging_ops.cc:79] P2[1 2 3...]
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.]], dtype=float32)
```

Where is the first print with P1 message?

**Comment by vrv** [comment]
You replaced x with Print(x,...), and then you fed x in your eval, replacing the result of Print and going directly into reshape.

Try:
    x = tf.placeholder(...)
    x_print = tf.Print(x, [x], ...)
    i = tf.reshape(x_print)

So that when you feed 'x', x_print is still run.

**Comment by eastonYi** [comment]
![5](https://user-images.githubusercontent.com/17430186/37584863-08164f9a-2b92-11e8-9e6e-8953a36f4398.PNG)

**Comment by YasserTahaSW** [comment]
I have the same problem but I dont have the same mistake mentioned above
```
x = tf.placeholder(tf.float32, shape=(None,image_height, image_width,channel))
xp = tf.Print(x,[x],"x")
kernel = tf.constant([[-2, -2, -2], [-2, 17, -2],[-2, -2, -2]])
kernel = tf.expand_dims(kernel, 0)
kernel = tf.expand_dims(kernel, 0)
kernel = tf.cast(kernel, tf.float32)
sharpened = tf.nn.conv2d(xp,kernel, strides=[1, 1, 1, 1], padding='SAME')
with tf.Session() as sess:
    results = sess.run(sharpened,feed_dict={x: dataset})
```
Nothing is being displayed.. any help is appreciated
