### ISSUE TITLE
a Makefile would be supremely helpful

### ISSUE THREAD

**Issue by tutufan** [tensorflow/tensorflow#199]
It'd be really useful to have a Makefile to build the tree.  Bazel (or it is blaze?) isn't working for us out of the gate, and it's rather non-obvious what it will try to do given its config files.

If someone could provide a transcript of a full build (preferably with GPU), showing external commands run and simulated (e.g., if bazel does 'cp' itself, for example), I'll try to work on this.

For the record, here's the initial fail I see when trying to build, without GPU to keep things simple.  No doubt I'm making some novice error.  Nonetheless, this diagnostic is rather opaque compared to what one might expect from 'make'.  (Maybe something is missing?  The tree was grabbed with 'git clone --recurse-submodules' though.) 

$ bazel build --logging=6 -c opt //tensorflow/cc:tutorials_example_trainer                                                                                                      
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: Loading of target '//tools/cpp:toolchain' failed; build aborted: no such package 'tools/cpp': BUILD file not found on package path.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.877s

**Comment by ebrevdo** [comment]
What version of bazel are you using?  Is it the one suggested in the getting started guide?  Do you have gcc/g++ installed on your machine?  If none of these help, try running the build with --verbose-failures and report back.

**Comment by tutufan** [comment]
The bazel version and g++ presence were fine.  The problem turned out to be a quirk in our environment.  We use environment modules and apparently that doesn't fit seamlessly with bazel's assumptions about its environment, necessitating a special bazelrc on every run, which I had left out.  That is, the error message was not about tensorflow, but rather bazel complaining that it couldn't find all of its parts.  (which didn't occur to me as 'make' simply cannot fail this way)

This got me farther, but unfortunately there are still showstopping build issues.  (We need to add our own include flag for a numpy header, and bazel fights hard to prevent this.)

I'm sure bazel has advantages inside of Google, but for the purposes of just downloading and playing with this externally, it's all stick, unfortunately.  As before, a Makefile would be really helpful.

P.S.  That's how that flag *should* be spelled, but bazel cleverly invents its own novel option syntax as well (--verbose_failures).

**Comment by ebrevdo** [comment]
We're working on a way to automatically infer the location of the numpy headers.  The current locations are [here](https://github.com/tensorflow/tensorflow/blob/72a5a60dd4664a7caa4611344364ac7851464a60/tensorflow/python/BUILD#L698).

**Comment by ebrevdo** [comment]
I'm closing this for now unless you have any other issues we can help with.  I know the title is about having a Makefile, but the question seemed to be more related to bazel issues.  I don't think we have Makefile/CMakeFile creation on the horizon but feel free to reopen a new issue limiting the description to just that fact and we'll keep it in mind in future planning.

**Comment by tutufan** [comment]
It's your call, but to me the lack of a Makefile or some similar understandable and easy-to-adapt substitute is an issue.  I provided some supporting information just to illustrate that this isn't mere bikeshedding, but I hope that doesn't distract from the big picture.  I can't think of any open source project I've had as much trouble trying to build from scratch.  Cheers.

**Comment by davidzchen** [comment]
> P.S. That's how that flag should be spelled, but bazel cleverly invents its own novel option syntax as well (--verbose_failures).

FWIW, that is the syntax used by [gflags](https://gflags.github.io/gflags/).
