### ISSUE TITLE
"Address already in use" occurs in Distributed Estimator.train_and_evaluator when loop training

### ISSUE THREAD

**Issue by cklsoft** [tensorflow/tensorflow#19900]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.18.0
- **Python version**:  2.7.13
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem

In Distributed ResNet, it need train the model many times, but when train in the second iteration, it fail for below:
```
{"created":"@1528701271.960402221","description":"No address added out of total 1 resolved","file":"external/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1528701271.960399817","description":"Failed to add any wildcard listeners","file":"external/grpc/src/core/lib/iomgr/tcp_server_posix.cc","file_line":345,"referenced_errors":[{"created":"@1528701271.960371584","description":"OS Error","errno":97,"file":"external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":259,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:50992"},{"created":"@1528701271.960399232","description":"Unable to configure socket","fd":74,"file":"external/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":203,"referenced_errors":[{"created":"@1528701271.960393654","description":"OS Error","errno":98,"file":"external/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":176,"os_error":"Address already in use","syscall":"bind"}]}]}]}
```

It means that, the worker port 50992 not release when a new iteration start. The train iteration code show as fllow:

--------------------code begin----------------------------------------
```

train_spec=tf.estimator.TrainSpec(input_fn=input_fn_train,max_steps=1000)

eval_spec=tf.estimator.EvalSpec(input_fn=input_fn_eval,steps=1,throttle_secs=1,start_delay_secs=1)

for cycle_index in range(total_training_cycle):

    print("start a train")

    tf.logging.info('Starting a training cycle: %d/%d',cycle_index, total_training_cycle)

    tf.logging.info('Starting to evaluate.')

    tf.estimator.train_and_evaluate(classifier,train_spec,eval_spec)

    print("end a train")

```
--------------------code end----------------------------------------

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
