### ISSUE TITLE
TensorFlow MNIST dataset is throwing 403

### ISSUE THREAD

**Issue by alsrgv** [tensorflow/tensorflow#19914]
[TensorFlow official MNIST model](https://github.com/tensorflow/models/blob/master/official/mnist/dataset.py) and [TFLearn Model](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/datasets/mnist.py) use https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz as a data store for MNIST dataset.

This URL is returning 403 errors:
```
<Error>
  <Code>UserProjectAccountProblem</Code>
  <Message>User project billing account not in good standing.</Message>
  <Details>
    The billing account for project 81,941,577,218 is disabled in state delinquent
  </Details>
</Error>
```

Any ETA for the fix?

cc @reedwm @martinwicke

**Comment by martinwicke** [comment]
Yeah, ironically, we're having trouble with billing. 

PR #19905 would fix it and can be used as a workaround until we figure out how to pay ourselves (hopefully not long, otherwise we'll accept the PR).

**Comment by njmote** [comment]
Just noticed this error. Good luck :)

**Comment by alsrgv** [comment]
Would be better if the Google URL is fixed, then users can use both for a foreseeable future and don't have to hard migrate.

**Comment by martinwicke** [comment]
This should now be fixed. Sorry about this.
