### ISSUE TITLE
tf dataset iterators producing Key error when used with tf.keras.Model fit method

### ISSUE THREAD

**Issue by sibyjackgrove** [tensorflow/tensorflow#19912]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.9.0-rc0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: model.fit(dataset_iterator,steps_per_epoch=2,batch_size=2,epochs=2,shuffle =True,verbose=1)

### Describe the problem
 In the tf 1.9 rc0 release notes, it was mentioned that dataset iterator can work with Keras training and eval methods. However, the fit method is throwing the following error when used with an iterator.

> No data provided for "InputLayer". Need data for each key in: ['InputLayer']

### Source code / logs

```
X_dataset = tf.contrib.data.make_csv_dataset(file_names[0],4,select_columns=['Load_residential_multi_0','Load_residential_multi_1'],shuffle=False)
Y_dataset = tf.contrib.data.make_csv_dataset(file_names[0],4,select_columns=['Load_residential_multi_2'],shuffle=False)
dataset = tf.data.Dataset.zip((X_dataset,Y_dataset))
dataset = dataset.batch(2)
dataset_iterator = dataset.make_one_shot_iterator()

model = Sequential() 
#Input Layer
model.add(InputLayer(input_shape=(1,),name='InputLayer'))#,input_tensor =dataset
#Layer1 
model.add(Dense(units=5,activation='relu',name='FeedForward1'))  #Add a feed forward layer
#Layer2 
model.add(Dense(units=5,activation='relu',name='FeedForward2'))  #Add a feed forward layer
#Output layer 
model.add(Dense(units=2,name='OutputLayer'))
#Specify loss function and optimizer
model.compile(loss='mse',optimizer='adam',metrics=['mae'])
#Summarize model
model.summary()
#Train model
model.fit(dataset_iterator,steps_per_epoch=2,batch_size=2,epochs=2,shuffle =True,verbose=1)
```
The error trace is given below:

> KeyError                                  Traceback (most recent call last)
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
>     125           if data[x].__class__.__name__ == 'DataFrame' else data[x]
> --> 126           for x in names
>     127       ]
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_utils.py in <listcomp>(.0)
>     125           if data[x].__class__.__name__ == 'DataFrame' else data[x]
> --> 126           for x in names
>     127       ]
> 
> KeyError: 'InputLayer'
> 
> During handling of the above exception, another exception occurred:
> 
> ValueError                                Traceback (most recent call last)
> <ipython-input-90-cd138934ce6f> in <module>()
> ----> 1 model.fit(dataset_iterator,steps_per_epoch=2,batch_size=2,epochs=2,shuffle =True,verbose=1)
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
>    1256         steps_name='steps_per_epoch',
>    1257         steps=steps_per_epoch,
> -> 1258         validation_split=validation_split)
>    1259 
>    1260     # Prepare validation data.
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, check_steps, steps_name, steps, validation_split)
>     867         feed_input_shapes,
>     868         check_batch_axis=False,  # Don't enforce the batch size.
> --> 869         exception_prefix='input')
>     870 
>     871     if y is not None:
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
>     128     except KeyError as e:
>     129       raise ValueError('No data provided for "' + e.args[0] + '". Need data '
> --> 130                        'for each key in: ' + str(names))
>     131   elif isinstance(data, list):
>     132     if isinstance(data[0], list):
> 
> ValueError: No data provided for "InputLayer". Need data for each key in: ['InputLayer']

**Comment by pavithrasv** [comment]
@sibyjackgrove You are seeing this issue because the model is not compatible with the input provided by the csv dataset iterator. Model expects input to be a tensor or a list or a dict with key as layer name of the layer that has placeholder. In your case {'InputLayer': Tensor(...)}.

However, iterator from make_csv_dataset provided a dictionary where key is csv column header and value is row value. This is not compatible with the model. We do not have a way of knowing whether the dictionary is from csv or if user has generated the layer name and value pairs. The not very elegant workaround you can try is to match the name of input layer with csv column name. Sorry about that.

We will make sure to add this information to our documentation and in the future see if we can improve support for this. Thank you!

**Comment by sibyjackgrove** [comment]
@pavithrasv thanks for pointing out why it is not working. But I think the underlying problem is being ignored. If  `make_csv_dataset ` is producing a different kind of dataset that cannot be used in places where other dataset iterators are used, why is it called a dataset in the first place.

**Comment by bensteUEM** [comment]
@sibyjackgrove i ran into the same problem - kinda confusing ...
leaving out the input shape definition i even get a 
> ValueError: Please do not pass a dictionary as model inputs.

The workaround with renaming woun't work for multiple inputs.
How can i feed any DataSet into a Sequential Keras model if it doesn't accept dicts but prefers datasets ...
