### ISSUE TITLE
Hi, how can I fix HTTP error 403? mnist input_data

### ISSUE THREAD

**Issue by bandheart** [tensorflow/tensorflow#19918]
Hi!
It is my first time to use this data set!
I got HTTP error 403 when I use the following code.

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("./mnist/data/", one_hot=True)

So.. I tried several things such as turning off firewall.
But, I can't solve it and need to fix it for homework.
Can you help me?

**Comment by martinwicke** [comment]
There was a problem with that bucket, which should now be fixed.
