### ISSUE TITLE
Could tensorboard add search function

### ISSUE THREAD

**Issue by chengmengli06** [tensorflow/tensorflow#19926]
Tensorboard visualization is great, but for big graphs, it is hard to locate certain ops. There are two many components in the graph. So I want two new functions:
1. It is possible to hide some nodes, such as reshape, relu, and soon, which does not affects the graph structure.
2. Is it possible to search some ops by name keywords, such as RPNLoss? The search result could be displayed on a search board.

**Comment by alexbeloi** [comment]
I think you will have better luck searching for or posting your request to the Tensorboard issues here https://github.com/tensorflow/tensorboard/issues

**Comment by angersson** [comment]
Yes, please file this against the tensorboard repository: https://github.com/tensorflow/tensorboard/issues. Thanks!
