### ISSUE TITLE
Bazel Build transform_graph failing to find inputs/outputs 

### ISSUE THREAD

**Issue by ashermancinelli** [tensorflow/tensorflow#19951]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX HS 10.13.4
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8
- **Python version**: 3.65
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: Tesla V100 16g x2

### Describe The Problem
Using retrained Inception V3 model.
I have used the exact scripts from the docs to fold the graph and optimize for mobile, yet it keeps failing. I ran `./configure` and built the `transform_graph` function as specified. Running the function with:
```
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=/path/frozen.pb \
--out_graph=/path/optimized.pb \
--inputs=“input” \
--outputs=“new_output_layer/probability” \
--transforms='
  strip_unused_nodes(type=float, shape="1,299,299,3")
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms'
```
gives the error: `Input node ‘new_output_layer/probability’ not found in graph` (full trace below) even though I know I specified the tensor names correctly. For some reason it seems to be looking for an input node under my output node's name even though the output node's name is rightly under `--outputs`. Inspecting the graph with `bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=/path/frozen.pb` gives:
```
Found 1 possible inputs: (name=input, type=float(1), shape=[?,299,299,3]) 
No variables spotted.
Found 1 possible outputs: (name=new_output_layer/probability, op=Softmax) 
Found 21826166 (21.83M) const parameters, 0 (0) variable parameters, and 191 control_edges
```
confirming that my names are correct. 

### Full Logs/Code
Inspect_graph:
`$ bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=/Users/manc568/Documents/projects/tf-threeclass/pbdir/frozen.pb`
```
Found 1 possible inputs: (name=input, type=float(1), shape=[?,299,299,3]) 
No variables spotted.
Found 1 possible outputs: (name=new_output_layer/probability, op=Softmax) 
Found 21826166 (21.83M) const parameters, 0 (0) variable parameters, and 191 control_edges
Op types used: 849 Switch, 679 Const, 569 Identity, 188 FusedBatchNorm, 95 Merge, 94 Conv2D, 94 Relu, 15 ConcatV2, 10 AvgPool, 4 MaxPool, 2 Add, 2 Mul, 1 BiasAdd, 1 Placeholder, 1 MatMul, 1 RandomUniform, 1 RealDiv, 1 Floor, 1 Shape, 1 Softmax, 1 Squeeze, 1 Sub, 1 PlaceholderWithDefault
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=/Users/manc568/Documents/projects/tf-threeclass/pbdir/frozen.pb --show_flops --input_layer=input --input_layer_type=float --input_layer_shape=-1,299,299,3 --output_layer=new_output_layer/probability
```
Transform_graph:
```
$ bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=/Users/manc568/Documents/projects/tf-threeclass/pbdir/frozen.pb \
--out_graph=/Users/manc568/Documents/projects/tf-threeclass/pbdir/optimized_inception_graph.pb \
--inputs=“input” \
--outputs=“new_output_layer/probability” \
--transforms='
  strip_unused_nodes(type=float, shape="1,299,299,3")
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights' 
```
```
2018-06-12 11:38:14.293873: I tensorflow/tools/graph_transforms/transform_graph.cc:318] Applying strip_unused_nodes
2018-06-12 11:38:14.297407: E tensorflow/tools/graph_transforms/transform_graph.cc:264] Input node “new_output_layer/probability” not found in graph
```

**Comment by ashermancinelli** [comment]
Fixed by removing the quotes around the tensor/op names.

**Comment by chaine09** [comment]
@ashermancinelli  what do you mean by tensor/op names? Can you specify?
