### ISSUE TITLE
Install OSError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by aureosun** [tensorflow/tensorflow#19970]
I'm trying to install tensorflow on my ubuntu os. The configuration of my machine is ubuntu14.04LTS ,NVIDIA K40*8 gpu,cuda8.0 with cudnn6.0.First,I install with Virtualenv,I follow the instructions on **https://www.tensorflow.org/install/install_linux#installing_with_virtualenv** step by step,
but after the last step,I got the error:
_

> Exception:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 324, in run
>     requirement_set.prepare_files(finder)
>   File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
>     ignore_dependencies=self.ignore_dependencies))
>   File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
>     require_hashes
>   File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 281, in populate_link
>     self.link = self._wheel_cache.cached_wheel(self.link, self.name)
>   File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 68, in cached_wheel
>     self._cache_dir, link, self._format_control, package_name)
>   File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 129, in cached_wheel
>     wheel_names = os.listdir(root)
> OSError: [Errno 13] Permission denied: '/home/cs/.cache/pip/wheels/7c/06/54/bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6'

_
What's the matter?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by aureosun** [comment]
Well,I install tensorflow with virtualenv,just follow the instructions in https://www.tensorflow.org/install/install_linux#installing_with_virtualenv.The step5 and step6 fails with the same error code:OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/numpy/distutils/tests/gen_ext/__init__.pyc'
My OS is ubuntu14.04 ,the details are Linux node4 3.16.0-33-generic #44~14.04.1-Ubuntu SMP Fri Mar 13 10:33:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux,
CUDA Version 8.0.44
and cuDNN is
#define CUDNN_MAJOR      6
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 21
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
#include "driver_types.h"
GPU:Tesla K80 ,with NVIDIA-SMI 390.48  
and the error occurs when
Successfully installed absl-py-0.2.2 astor-0.6.2 backports.weakref-1.0.post1 bleach-1.5.0 enum34-1.1.6 funcsigs-1.0.2 futures-3.2.0 gast-0.2.0 grpcio-1.12.1 html5lib-0.9999999 markdown-2.6.11 mock-2.0.0 numpy-1.14.3 pbr-4.0.2 protobuf-3.5.2.post1 setuptools-39.1.0 six-1.11.0 tensorboard-1.8.0 tensorflow-gpu-1.8.0 termcolor-1.1.0 werkzeug-0.14.1 wheel-0.31.0
Exception:
Traceback (most recent call last):
  File "/home/cs/TF-Workspace/local/lib/python2.7/site-packages/pip-10.0.1-py2.7.egg/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/cs/TF-Workspace/local/lib/python2.7/site-packages/pip-10.0.1-py2.7.egg/pip/_internal/commands/install.py", line 381, in run
    options.target_dir, target_temp_dir, options.upgrade
  File "/home/cs/TF-Workspace/local/lib/python2.7/site-packages/pip-10.0.1-py2.7.egg/pip/_internal/commands/install.py", line 432, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/numpy/distutils/tests/gen_ext/__init__.pyc'

**Comment by bignamehyp** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
