### ISSUE TITLE
profiler op view: how to interpret the two numbers of (xx%, xx%) in the output

### ISSUE THREAD

**Issue by MrWanter** [tensorflow/tensorflow#19974]
Hi! I'm using the tf profiler, a typical output for the `op` view with the code:
```
profiler.profile(
    tf.get_default_graph(),
    run_meta=run_metadata,
    cmd='op',
    options=opts)
```
would be 
```
Profile:
node name | # float_ops
MatMul                   81.40m float_ops (100.00%, 96.29%)
Mean                     795.12k float_ops (3.71%, 0.94%)
Mul                      648.40k float_ops (2.77%, 0.77%)
Add                      548.00k float_ops (2.00%, 0.65%)
Sub                      397.51k float_ops (1.36%, 0.47%)
Square                   397.51k float_ops (0.89%, 0.47%)
RealDiv                  200.00k float_ops (0.42%, 0.24%)
Sum                      100.79k float_ops (0.18%, 0.12%)
Neg                      50.00k float_ops (0.06%, 0.06%)
ArgMax                     900 float_ops (0.00%, 0.00%)
Equal                      102 float_ops (0.00%, 0.00%)
Greater                      1 float_ops (0.00%, 0.00%)

======================End of Report==========================
```
but I really cannot figure out what the two percent numbers in the output means, I googled it a while, no lucky, when I tried to read the source code of profiler, I find it wrapped too heavy...

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
