### ISSUE TITLE
Feature Request: erosion and dilation such as scipy.ndimage.grey_erosion and scipy.ndimage.grey_dilation

### ISSUE THREAD

**Issue by KeyKy** [tensorflow/tensorflow#19981]
tf.image.erosion and tf.image.dilation. I find tf.nn.dilation2d is too slow when the kernel size is [20,20,1].

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by KeyKy** [comment]
I solved the problem using other ways. For now, it works well. Thanks!

**Comment by pribadihcr** [comment]
@KeyKy,

Can you share your code? thanks
