### ISSUE TITLE
Feature Request: untruncated normal in variance scaling initializer

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#19996]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: N/A
- **Python version**: N/A
- **Bazel version (if compiling from source)**:N/A
- **GCC/Compiler version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:N/A
- **GPU model and memory**:N/A
- **Exact command to reproduce**:N/A

Currently the "normal" mode of `variance_scaling_initializer` actually produces truncated normal distribution. 
Despite that I saw Google suggest in several places that a truncated normal might be better than a true normal distribution, truncated normal is NOT what is used in the initialization literature such as:

[1] Glorot, Xavier, and Yoshua Bengio. "Understanding the difficulty of training deep feedforward neural networks." In Proceedings of the thirteenth international conference on artificial intelligence and statistics, pp. 249-256. 2010.
[2] He, Kaiming, Xiangyu Zhang, Shaoqing Ren, and Jian Sun. "Delving deep into rectifiers: Surpassing human-level performance on imagenet classification." In Proceedings of the IEEE international conference on computer vision, pp. 1026-1034. 2015.

I found that this difference is affecting some of my experiments. To be more consistent with literature, I would request a new mode in variance_scaling_initializer that produces untruncated normal distribution. I'm OK to implement it If someone can give it a good name.

**Comment by josh11b** [comment]
(For API review.) We agree this should be fixed. I think the best path forward is:

* We change the legal values in https://github.com/tensorflow/tensorflow/blob/23c218785eac5bfe737eec4f8081fd0ef8e0684d/tensorflow/python/ops/init_ops.py#L443
 if distribution not in {"normal", "uniform"}:
to "normal", "uniform", "truncated_normal", "untruncated_normal"

* We change the default here: https://github.com/tensorflow/tensorflow/blob/23c218785eac5bfe737eec4f8081fd0ef8e0684d/tensorflow/python/ops/init_ops.py#L435
from "normal" to "truncated_normal" (matching current behavior, but clearer)

* We change the implementation here:
https://github.com/tensorflow/tensorflow/blob/23c218785eac5bfe737eec4f8081fd0ef8e0684d/tensorflow/python/ops/init_ops.py#L465
to treat "normal" & "truncated_normal" as the same (required for backwards-compatibility) and add a new implementation for "untruncated_normal"

* In the documentation here:
https://github.com/tensorflow/tensorflow/blob/23c218785eac5bfe737eec4f8081fd0ef8e0684d/tensorflow/python/ops/init_ops.py#L421
update the text to document the options as "truncated_normal", "untruncated_normal", and "uniform", and that "normal" is a deprecated alias for "truncated_normal"

* I will make a note that at 2.0, when we can break backwards compatibility, we should change "normal" to be an alias for "untruncated_normal".

**Comment by martinwicke** [comment]
Ok. We cannot change the behavior right now, but how about the following:

* We add a "

**Comment by martinwicke** [comment]
Would that solve your problem? If so, please send a PR and reference this issue. Thank you!

**Comment by ppwwyyxx** [comment]
That's exactly the solution I was hoping for.
