### ISSUE TITLE
Install Tensorflow x86 with pip

### ISSUE THREAD

**Issue by Fabioluxx** [tensorflow/tensorflow#19998]
Can i install tensorflow for python x86 with pip?

**Comment by marshalhayes** [comment]
Hi @Fabioluxx. By x86, do you mean Python running on Windows? 

TensorFlow can be downloaded from pip in general. If you have pip installed, you should be able to download TensorFlow just fine by running `pip install tensorflow` regardless of platform. 

Hope this helps.

**Comment by marshalhayes** [comment]
By the way, if pip isn't added to your path you can run it instead with `python -m pip install tensorflow`.

**Comment by Fabioluxx** [comment]
But it worked only when i uninstalled python x86 and installed python x64, otherwise a erro occurs like no version of tensorflow found and if i try to use install `pip3 install tensorflow== ` to see what versions are available, is empty

**Comment by marshalhayes** [comment]
According to the documentation, it appears that TensorFlow should work on almost any Windows system. They only support and test on 64-bit, x86 systems that are Windows 7 or later however. 

I'm unsure of why it didn't work for you.  Did you read the documentation here?: [Install TensorFlow on Windows](https://www.tensorflow.org/install/install_windows)

**Comment by Fabioluxx** [comment]
Yes, i am using windows 10 x64

**Comment by Fabioluxx** [comment]
Conclusion: It only supports x64

After some search, here is the repository: https://pypi.org/project/tensorflow/#files
that only have x64 builds

**Comment by marshalhayes** [comment]
Yes, you are correct @Fabioluxx. TensorFlow only support 64-bit Python. See [TensorFlow not found using pip](https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip).
