### ISSUE TITLE
Broken link on beginner's tutorial page

### ISSUE THREAD

**Issue by shirriff** [tensorflow/tensorflow#200]
At the bottom of http://www.tensorflow.org/tutorials/mnist/beginners/index.md is a link to "the next tutorial": http://www.tensorflow.org/tutorials/index.md

For some reason, that link redirects to the home page. Removing index.md from the end of the URL works.

**Comment by mrry** [comment]
Thanks for the report! Indeed, it should point to http://tensorflow.org/tutorials/mnist/pros/index.md

We'll check in that fix, and it will appear on the website when it's next updated.
