### ISSUE TITLE
tf.get_variable(reuse=tf.AUTO_REUSE) is not working in the eager execution mode.

### ISSUE THREAD

**Issue by David-Mao** [tensorflow/tensorflow#20009]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Darwin localhost 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
Mac OS X 10.13.4
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.7
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: See below

### Describe the problem

When calling get_variable() function in tensorflow, the behavior of the "reuse" flag is defined in the [tensorflow api doc](https://www.tensorflow.org/api_docs/python/tf/variable_scope) to be AUTO_REUSE:

> reuse: True, None, or tf.AUTO_REUSE; ... **When eager execution is enabled, this argument is always forced to be tf.AUTO_REUSE**.

However when I run the demo code as suggested in the api doc:

```
tf.enable_eager_execution()
def foo():
  with tf.variable_scope("foo", reuse=tf.AUTO_REUSE):
    v = tf.get_variable("v", [1])
  return v
v1 = foo()  # Creates v.
v2 = foo()  # Gets the same, existing v.
assert v1 == v2
```

It fails. (It passes if the first line is removed, as expected.)

Not sure whether it is a bug or expected behavior, but at least the api doc seems kind of misleading. If it's expected, then what's the correct way to reuse a variable in eager mode? (and can this be included in the api doc?)

**Comment by alextp** [comment]
This is sadly working as intended and we need to update the documentation. We don't support variable reuse in eager other than inside templates.
