### ISSUE TITLE
Feature request: Length normalisation  in ctc_beam_search_decoder

### ISSUE THREAD

**Issue by dbanka** [tensorflow/tensorflow#20015]
I  read that length normalisation improves the result of beam search. So, is there any plan of adding length normalisation in ctc_beam_search_decoder? 

Have I written custom code: No
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version:N/A
Bazel version:N/A
CUDA/cuDNN version: N/A
GPU model and memory:N/A
Exact command to reproduce:N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by githubharald** [comment]
I think length normalization only makes sense when using a language model (LM).
In case a character-level LM is used, a labeling with say L characters gets scored L times. Each scoring is done with a value between p=0..1. Therefore, the LM-score for a long text is usually too low and length normalization makes sense in this case.
