### ISSUE TITLE
feature request: improve the training speed of GPU

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#2001]
tensorflow seems to have a good performance on CPU compared to other frameworks, however relatively poor on GPU according to third-party benchmark
![image](https://cloud.githubusercontent.com/assets/11470826/14587474/6e4106ae-04e6-11e6-9102-0a4e63b2b82f.png)
![image](https://cloud.githubusercontent.com/assets/11470826/14587481/862ef96a-04e6-11e6-8e43-1bc4ebff7e22.png)
Could I ask the reason why this happen? I belive Tensorflow is the hottest Deep Learning Framework on github. If we could make the performance of Tensorflow better, it will help a lot of people.

Anyone can help or contribute to this issue?

**Comment by vrv** [comment]
All of those benchmark numbers are quite stale -- things should be much faster, though there's still room for improvement.  If you have a specific benchmark with up to date numbers, we can definitely take a look!
