### ISSUE TITLE
tf.keras.layers.DepthwiseConv2D fail when bias is enabled

### ISSUE THREAD

**Issue by laurent-george** [tensorflow/tensorflow#20023]
It seems that a little mistake is present in tf.keras.layers.DepthwiseConv2D, in the call procedure:

https://github.com/tensorflow/tensorflow/blob/17d6639b550cdcedf31ee01bd6eb26c592aeac42/tensorflow/python/keras/layers/convolutional.py#L1727

In my understanding self.bias should be replaced by self.use_bias on this line, as self.bias is a tensor, wheras self.use_bias is a boolean value.

After replacing it, the DepthwiseConv2D seems to works fine here.
@fchollet what do you think ?

Have I written custom code N/A
OS Platform and Distribution N/A
TensorFlow installed from N/A
TensorFlow version N/A
Bazel version N/A
CUDA/cuDNN version N/A
GPU model and memory N/A
Exact command to reproduce N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
