### ISSUE TITLE
[BUG] tf.train.Saver in non-local filesystem

### ISSUE THREAD

**Issue by candyzone** [tensorflow/tensorflow#20043]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux CentOS 7
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.4.0 release
- **Python version**: python2.7
- **Bazel version (if compiling from source)**: 0.9.0
- **GCC/Compiler version (if compiling from source)**: gcc4.8.5
- **CUDA/cuDNN version**: -
- **GPU model and memory**: -
- **Exact command to reproduce**: -

In Tensorflow source code tensorflow/python/training/saver.py, there are some function call like "os.path.isabs()". If saving to non-local filesystem such as "hdfs://" and using save_relative_paths=True, the behavior is not expected. The checkpoint file still save "hdfs://.../.../..." instead of relative_path

source code: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/saver.py#L982

It doesn't have any "IsAbs()" Interface in tensorflow::FileSystem, I think some solution:
1. Add IsAbs() Interface in tensorflow::FileSystem
2. add IsAbs() Interface in tensorflow::FileStatistics, we can call tensorflow::FileSystem::Stat() to get this info.

Thanks

**Comment by YongCHN** [comment]
i met the same issue. the root cause is the wrong file io used. should change to the tf.file_io apis.

**Comment by jony0917** [comment]
i am working on it

**Comment by jony0917** [comment]
i have created a PR, it is my first time, could someone tell me what should i do next. 

https://github.com/tensorflow/tensorflow/pull/20406

**Comment by tilakrayal** [comment]
Hi,
[tf.compat.v1.train.Saver](https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/Saver) is not supported for saving and restoring checkpoints in TF2. Please switch to [tf.train.Checkpoint](https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint) or [tf.keras.Model.save_weights](https://www.tensorflow.org/api_docs/python/tf/keras/Model#save_weights), which perform a more robust [object-based saving](https://www.tensorflow.org/guide/checkpoint#loading_mechanics).

https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint

Thank you!
