### ISSUE TITLE
error : tf.nn.ctc_beam_search_decoder

### ISSUE THREAD

**Issue by JanzZhu** [tensorflow/tensorflow#20053]
if classes size is small ，tf.nn.ctc_beam_search_decoder can run normally.

if classes size is big (example: 3800), tf.nn.ctc_beam_search_decoder Will not end

cpu: 8
memory: 32
gpu: 1080ti

Please anyone help me

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by githubharald** [comment]
running time of beam search is O(T * BW * C * log(BW * C)), with BW=beam width, C=number of characters, T=input sequence length. Increasing the number of characters C increases the running time more than linearly. So, maybe you just have to wait a little longer?
