### ISSUE TITLE
Wide Deep model erased all my files?

### ISSUE THREAD

**Issue by mklebanamc** [tensorflow/tensorflow#20061]
I downloaded the models-master folder to my harddrive and ran the wide-deep.py script.  Next thing I know, all the files on my harddrive are wiped out.  Is there a script that deletes the directory?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by BEARTRAPTHERAPPER** [comment]
U need to run a custom ROM drive id if you wanna have any luck with that... And evwrytime it will wipe ur drive .. With a ROM its secluded away on the drive to be left alone use backe partition code 17.773.76... It works nice if you run a version 7.1 or above..

**Comment by k-w-w** [comment]
Hi @mklebanamc, we are really sorry to hear that. The wide deep model used to clear out the directory set by the `--model_dir` flag, to allow training to start from a blank slate. We recently pushed out a change to clear the directory when the user has specified a `--clean` flag. In general, Estimator expects free reign over the model directory. Again, sincere apologies that this happened.
