### ISSUE TITLE
Python double free or corruption

### ISSUE THREAD

**Issue by anhnt1** [tensorflow/tensorflow#20087]
Hi, 

I try tensorflow-gpu 1.9.0rc1, but got the following error. I use ubuntu 16.04 (fresh install last night), numpy=1.13.3 (as required by 1.9.0rc1). Anyone tell me what the reason for this error? Thanks in advance.

Tuan 

`*** Error in `python': double free or corruption (out): 0x00007ff8980021b0 ***
*** Error in `python': double free or corruption (out): 0x00007ff898001d20 ***
======= Backtrace: =========
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ff9781137e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7ff97811c37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7ff97812053c]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow8EventMgr10PollEventsEbPNS_3gtl13InlinedVectorINS0_5InUseELi4EEE+0x6fb)[0x7ff943fcb14b]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(_ZN10tensorflow7GPUUtil18CopyGPUTensorToCPUEPNS_6DeviceEPKNS_13DeviceContextEPKNS_6TensorEPS6_St8functionIFvRKNS_6StatusEEE+0x3ff)[0x7ff93e95241f]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(_ZN10tensorflow16GPUDeviceContext21CopyDeviceTensorToCPUEPKNS_6TensorENS_11StringPieceEPNS_6DeviceEPS1_St8functionIFvRKNS_6StatusEEE+0x82)[0x7ff93e953a72]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(+0x5f59ef)[0x7ff93e97e9ef]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(_ZN10tensorflow10CopyTensor6ViaDMAENS_11StringPieceEPNS_13DeviceContextES3_PNS_6DeviceES5_NS_19AllocatorAttributesES6_PKNS_6TensorEPS7_St8functionIFvRKNS_6StatusEEE+0x67a)[0x7ff93e97f53a]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(_ZN10tensorflow22IntraProcessRendezvous18SameWorkerRecvDoneERKNS_10Rendezvous9ParsedKeyERKNS1_4ArgsES7_RKNS_6TensorEPS8_St8functionIFvRKNS_6StatusEEE+0x4cc)[0x7ff93e9c7cac]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(+0x63f2bd)[0x7ff93e9c82bd]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(_ZN10tensorflow19LocalRendezvousImpl9RecvAsyncERKNS_10Rendezvous9ParsedKeyERKNS1_4ArgsESt8functionIFvRKNS_6StatusES7_S7_RKNS_6TensorEbEE+0x961)[0x7ff93e7ebaf1]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(_ZN10tensorflow22IntraProcessRendezvous9RecvAsyncERKNS_10Rendezvous9ParsedKeyERKNS1_4ArgsESt8functionIFvRKNS_6StatusES7_S7_RKNS_6TensorEbEE+0x473)[0x7ff93e9c8903]
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ff9781137e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7ff97811c37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7ff97812053c]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(+0x6036b9)[0x7ff93e98c6b9]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(+0x606ba8)[0x7ff93e98fba8]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(+0x60c8c3)[0x7ff93e9958c3]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(+0x60ca2a)[0x7ff93e995a2a]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(_ZN5Eigen26NonBlockingThreadPoolTemplIN10tensorflow6thread16EigenEnvironmentEE10WorkerLoopEi+0x21a)[0x7ff93e9f3fba]
/home/anhnt/tf-190/venv/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(_ZNSt17_Function_handlerIFvvEZN10tensorflow6thread16EigenEnvironment12CreateThreadESt8functionIS0_EEUlvE_E9_M_invokeERKSt9_Any_data+0x32)[0x7ff93e9f3062]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80)[0x7ff921537c80]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7ff97846d6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7ff9781a341d]`

**Comment by anhnt1** [comment]
Hi again,

This is the full stack trace.

Tuan
[error-1.9.0rc1.txt](https://github.com/tensorflow/tensorflow/files/2109750/error-1.9.0rc1.txt)

**Comment by asimshankar** [comment]
@anhnt1 - thanks for the report. Is it possible for you to create a [reproducible example](https://stackoverflow.com/help/mcve)?

Thanks

**Comment by anhnt1** [comment]
@asimshankar - I got the error twice yesterday. But the work-around is here https://github.com/tensorflow/tensorflow/issues/6968, compile numpy from source.
But I still got segfault, another issue :)
Tuan

**Comment by asimshankar** [comment]
@anhnt1 : Not sure I followed - do you have some code to share that can reproduce the problem?

**Comment by anhnt1** [comment]
@asimshankar 
Hi, 
The code is attached, but data is quite big. I do not know how I can share it with you.
Tuan

**Comment by anhnt1** [comment]
@asimshankar Change the bug.txt to bug.py. I will zip data files later.
Tuan

**Comment by anhnt1** [comment]
@asimshankar 
Data files (zip version) is still too big (125M). Not sure how I can share it with you.
Tuan

**Comment by asimshankar** [comment]
@anhnt1 : I was hoping for a much smaller, [minimal, verifiable, complete example](https://stackoverflow.com/help/mcve). Is there something you could do to isolate the issue further?
