### ISSUE TITLE
Feature request: add Tensorflow.js

### ISSUE THREAD

**Issue by stopsatgreen** [tensorflow/tensorflow#20093]
Thanks for this tutorial, found it super-useful and helped me understand a lot. It would be great to see a version that uses Tensorflow.js / for Node, and how this works differently.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment]
@nkreeger would know about such documentation in the pipeline.

**Comment by nkreeger** [comment]
Hi @stopsatgreen which tutorial are you referencing?

We have a variety of docs up on http://js.tensorflow.org and our examples repo has some node-specific demos as well: https://github.com/tensorflow/tfjs-examples

**Comment by stopsatgreen** [comment]
@nkreeger Sorry, it was *Tensorflow for Poets*. I went through the Python demo, which was great, would love to see the same for JS.

**Comment by lamberta** [comment]
Glad you found it helpful. There are no plans to port that specific tutorial to TensorFlow.js, but there are others available here: https://js.tensorflow.org/tutorials/
But will keep *TensorFlow for Poets* in mind for the future. Thanks.
