### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.keras'

### ISSUE THREAD

**Issue by alanhdu** [tensorflow/tensorflow#20096]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary (CPU linux wheel)
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: 3.6.5

### Describe the problem

Using Tensorflow 1.8.0, running:
```python
from tensorflow.keras.utils import Progbar
```

raises an error:
```
ModuleNotFoundError: No module named 'tensorflow.keras'
```

Of course, `from tensorflow import keras` works fine.

This is a minor nit since there's an obvious workaround, but IMO this is pretty unintuitive behavior for how modules work in Python. I'm not sure what kind of sorcery is going on to end up with this result :laughing:.

**Comment by brge17** [comment]
```
from tensorflow.python.keras.utils import Progbar
```

**Comment by asimshankar** [comment]
As @brge17 pointed out, the package organization is a bit nuanced. You could use aliases instead as well:

```python
import tensorflow as tf

Progbar = tf.keras.utils.Progbar
```

Closing this since we are unlikely to change package organization in the near future.

**Comment by abbasabaei** [comment]
> ```python
> from tensorflow.python.keras.utils import Progbar
> ```

I had the same problem but your solution was useful.
thanks
