### ISSUE TITLE
How To doc for tensor indexing and assigning ops

### ISSUE THREAD

**Issue by domluna** [tensorflow/tensorflow#201]
If you're coming from numpy you're used to be able to index and assign into arrays in the usual way.

**Comment by girving** [comment]
Thanks for the note!  We're working on improving our suite of indexing / assignment ops, and we'll definitely want a good tutorial once they're in place.  There's a tracking bug for the necessary functionality here: https://github.com/tensorflow/tensorflow/issues/206

**Comment by ebrevdo** [comment]
Closing as duplicate of #206.
