### ISSUE TITLE
Negative Axis Support for tf.manip.roll and other ops

### ISSUE THREAD

**Issue by bbartoldson** [tensorflow/tensorflow#20106]
tf.manip.roll does not support a negative axis argument. Some ops have had support for negative axes added (e.g. see #6022 regarding argmin), so perhaps tf.manip.roll should be modified, or maybe it should warn the user that the axis argument must not be negative. 

In general, is there a guideline for knowing when a negative axis is supported by a TensorFlow op? 

### System information
I am using TensorFlow 1.8 installed from binary, Python 3.6, and macOS 10.13.4.

### The problem

I expected tf.manip.roll to behave the same as numpy.roll when given a negative axis argument. As shown in the following code, this is not the case.

```python
x = tf.placeholder(tf.float32, [None, 5])
y = tf.manip.roll(x,1,1)
z = tf.manip.roll(x,1,-1)

with tf.Session() as sess:
    print(sess.run([y,z], feed_dict={x:[range(5)]}))
```

[array([[4., 0., 1., 2., 3.]], dtype=float32), array([[0., 1., 2., 3., 4.]], dtype=float32)]

```python
x= np.array([range(5)])
y = np.roll(x,1, axis=1)
z = np.roll(x,1, axis=-1)

print(y, z)
```
[[4 0 1 2 3]] [[4 0 1 2 3]]

Thank you!

**Comment by yongtang** [comment]
@bbartoldson I think PR #18409 added the negative axis support for tf.manip.roll. It will be available in the next version I believe.

**Comment by bbartoldson** [comment]
Awesome. I tried searching the open issues for this, but I didn't think about checking pull requests. Thanks!
