### ISSUE TITLE
Question:How does Tensorflow deal with numpy.nan values?

### ISSUE THREAD

**Issue by zhang8473** [tensorflow/tensorflow#2013]
1. raise error
2. treat them as empty: I would say this is the proper way but the developers have to some math works to let the codes work
3. treat them as zero

**Comment by yaroslavvb** [comment]
Different parts of TensorFlow treat them differently. Computations usually
propagate them. Python parts of TensorFlow often raise an error on "NaN",
ie, trying to add a NaN summary to histogram will fail with Python
exception.

a=tf.constant(1.0)
b = tf.constant(0.0)
c = a/b * 0          # nan
d = c+1             # nan+1 = nan
e = tf.to_int32(d)  # int(nan) = 0 (???)
f = c - c           # nan - nan = nan
sess = create_session()
print sess.run(c)
print sess.run(d)
print sess.run(e)
print sess.run(f)
