### ISSUE TITLE
Tf lite: EXC_BAD_ACCESS when invoking the interpreter in iOS

### ISSUE THREAD

**Issue by mjuvilla** [tensorflow/tensorflow#20145]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS X High Sierra
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.9.0
- **Python version**: 3.5

### Describe the problem
I created a feedforward neural network in Python and then exported the tflite model using:

```
bazel run --config=opt \
  //tensorflow/contrib/lite/toco:toco -- \
  --input_file=frozen_graphdef.pb \
  --output_file=model.tflite \
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --inference_type=FLOAT \
  --input_shape=1,200 \
  --input_array=inputs \
  --output_array=prediction  
```

I'm now trying to use it in iOS following the guidelines of your examples. This is my code:

```

  float* _fInput;
  std::unique_ptr<tflite::Interpreter> _interpreter;

  std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile(sModel_path.c_str());
  
  if (!model) {
    std::cout << "Failed to map model " << sModel_path << std::endl;
    exit(-1);
  }
  std::cout << "Loaded model " << sModel_path << std::endl;
  
  tflite::ops::builtin::BuiltinOpResolver resolver;
  
  tflite::InterpreterBuilder(*model, resolver)(&_interpreter);
  
  if (!_interpreter) {
    std::cout << "Failed to construct interpreter." << std::endl;
    exit(-1);
  }
  
  int input_idx = _interpreter->inputs()[0];
  
  std::vector<int> sizes = {1, NUM_FEAT};
  std::string input_layer_type = "float";
  
  if (input_layer_type != "string") {
    _interpreter->ResizeInputTensor(input_idx, sizes);
  }

  if (_interpreter->AllocateTensors() != kTfLiteOk) {
    printf("Failed to allocate tensors!\n");
  }
  
  _fInput = _interpreter->typed_tensor<float>(input_idx);

  // receive vFeatures, an std::vector<float> of size NUM_FEAT

  for(int i = 0; i < NUM_FEAT; ++i)
    _fInput[i] = vFeatures[i];
  
  if (_interpreter->Invoke() != kTfLiteOk) {
    std::cout << "Failed to invoke!" << std::endl;
    exit(-1);
  }

```

For some reason, the execution fails on the line _interpreter->Invoke(), I get an "EXC_BAD_ACCESS" error. 

On a sidenote, do I need the ResizeInputTensor and AllocateTensors lines? It seems to me that the resizing is not necessary since I already stated the input size when exporting the tflite model, and I've seen some examples in which these lines were not present.

**Comment by andresteves** [comment]
what was the solution?

**Comment by mjuvilla** [comment]
It was a long time ago so I don't remember but probably "move to pytorch"
