### ISSUE TITLE
Tensorboard not showing anything 

### ISSUE THREAD

**Issue by jcyk** [tensorflow/tensorflow#2014]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Mac OS
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
None installed.
If installed from binary pip package, provide:

1. Which pip package you installed.
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.8.0rc0-py2-none-any.whl
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.8.0rc0

### Steps to reproduce
1. tensorboard --logdir=board 

### What have you tried?
1. checked things according to the instructions in ready.md

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/Users/jcyk/tensorflow/lib/python2.7/site-packages/tensorflow/tensorboard/TAG' on path /Users/jcyk/tensorflow/lib/python2.7/site-packages/tensorflow/tensorboard/TAG
WARNING:tensorflow:Unable to read TensorBoard tag
Starting TensorBoard  on port 6006
(You can navigate to http://0.0.0.0:6006)

[board.zip](https://github.com/tensorflow/tensorflow/files/225193/board.zip)

**Comment by arlejeun** [comment]
+1. I have similar issue. 
I checked the logdir and the events file Test and Train are in the directory.

`(tensorflow)[ arnaudlejeune /tmp/mnist_logs ] find /tmp/mnist_logs/ | grep events | xargs ls -lh
-rw-r--r--  1 arnaudlejeune  wheel   2,6M 20 avr 11:40 /tmp/mnist_logs/test/events.out.tfevents.1461170332.MacBook-Pro-de-ARNAUD.local
-rw-r--r--  1 arnaudlejeune  wheel    19M 20 avr 11:40 /tmp/mnist_logs/train/events.out.tfevents.1461170331.MacBook-Pro-de-ARNAUD.local`

**Comment by jacobsn** [comment]
I was seeing the same issue.  I updated to a [nightly build](http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_CONTAINER_TYPE=CPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/lastBuild/) and the problem is gone.

**Comment by mrry** [comment]
@jcyk, @arlejeun: Does updating to a more recent version fix this for you?

**Comment by kadrach** [comment]
Have a similar issue with a recent build of tensorflow - the .runfiles paths are not correct, e.g. tensorboard is looking for ```/home/ubuntu/tensorflow-py2.7/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/org_tensorflow/external/paper_item/paper-item.html```,
which is actually located in ```/home/ubuntu/tensorflow-py2.7/bazel-bin/tensorflow/tensorboard/tensorboard.runfiles/paper_item/paper-item.html```

Symlinking directories into the right places fixes the issue.

**Comment by girving** [comment]
@kadrach: I'm going to close since the original problem seems to have been fixed, but please open a separate issue if you have a different extant problem.
