### ISSUE TITLE
Find a bug in tensorflow

### ISSUE THREAD

**Issue by zyj183247166** [tensorflow/tensorflow#20140]
write the code below, and save it to  a ,ckpt as a model
```
import tensorflow as tf`
v1 = tf.Variable(tf.constant(1.0, shape=[1]), name = "v1")
v2 = tf.Variable(tf.constant(2.0, shape=[1]), name = "v2")
v3 = tf.Variable(tf.constant(3.0, shape=[1]), name = "v3")
result=v1+v2
result2= result + v3

init_op = tf.global_variables_initializer()
saver = tf.train.Saver()

with tf.Session() as sess:
    sess.run(init_op)
    writer = tf.summary.FileWriter('./graphs/const_add', sess.graph)
    saver.save(sess, "Saved_model/model.ckpt")`
```
then in another .py， we restore the model from the model.ckpt file
```
import tensorflow as tf
saver = tf.train.import_meta_graph("Saved_model/model.ckpt.meta")
with tf.Session() as sess:
    saver.restore(sess, "Saved_model/model.ckpt")
    print (sess.run(tf.get_default_graph().get_tensor_by_name("add:0")))
    #sess.run(tf.assign(v1,[10])) #直接这样使用v1，会提示v1没有定义
    
    #with tf.variable_scope("",reuse=tf.AUTO_REUSE):
    with tf.variable_scope("",reuse=False):
        v1=tf.get_variable(name="v1",shape=[1])
        print(v1.name)
    sess.run(tf.assign(v1,[10]))
    """④输出所有可训练的变量名称，也就是神经网络的参数"""
    trainable_variables=tf.trainable_variables()
    variable_list_name = [c.name for c in tf.trainable_variables()]
    variable_list = sess.run(variable_list_name)
    for k,v in zip(variable_list_name,variable_list):
        print("variable name:",k)
        print("shape:",v.shape)
            #print(v) 
    """④输出所有可训练的变量名称，也就是神经网络的参数"""
    print (sess.run(tf.get_default_graph().get_tensor_by_name("v1:0")))
    print (sess.run(tf.get_default_graph().get_tensor_by_name("add:0")))
    print (sess.run(tf.get_default_graph().get_tensor_by_name("add_1:0")))
    print (sess.run(tf.get_default_graph().get_tensor_by_name("v1_1:0")))
```
the results will be as below:
![image](https://user-images.githubusercontent.com/7501074/41644510-d1957e98-74a0-11e8-9327-7e2cd5ccd438.png)
we will find that:
if we restore some variables from the already existed model file ""Saved_model/model.ckpt.meta")",
such as v1,v2,v3 in this example.
it will influence the process of calling get_variable. Because of these two causes as below:
1. the variables restored from the model file such as v1,v2 and v3 will not exist in the scope of get_variable, it means you can only use
```
with tf.variable_scope("",reuse=False):
        v1=tf.get_variable(name="v1",shape=[1])
```
and create a new variable.  you can not  reuse the restored variable v1 from the model file unless you define a v1 , before you restore from the model file. like below
```
v1=tf.get_variable(name="v1",shape=[1])
saver = tf.train.Saver()
with tf.Session() as sess:
    saver.restore(sess, "Saved_model/model.ckpt")
    print (sess.run(result))
```
that is , you can not reuse the restored variable v1 which is from restoring the model file unless you define it befor you restore.
2.  although tensorflow doesnot allow reusing the restored variable v1 which is from restoring the model file if you don't define v1 before you restore the model file.
But if you call get_varialbe after you restore the model file, it will create a variable whose name is "v1_1" but not as name='v1' which you specify.
    in my opinion, it should be corrected because it is so confusing.  how to correct it?
i think get_variable should also reuse the variables which is loaded by restoring some model file.
the last sentence is what i finally want to say. 
My english is to bad, you can run the code i offer and will find what i want to convey. 
Thanks.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by zyj183247166** [comment]
OS Platform and Distribution：windows10
TensorFlow installed from：using anacond3 and pip to install tensorflow1.8.0 version.
cuda version 9.0 cudnn.

reproducing my code is very easy. just run it.

**Comment by reedwm** [comment]
If I'm understanding correctly, you're asking that when you create a variable and save the metagraph, then later load the metagraph, calling `tf.get_variable` again does not seem to know about the restored variable, and will not reuse it.

/CC @lukaszkaiser, can you comment?

**Comment by lukaszkaiser** [comment]
I'm not really familiar with metagraphs, are we not serializing the variable store? It can be, I'm sorry I cannot help more.

**Comment by reedwm** [comment]
/CC @allenlavoie, do you know if the variable store is serialized, and if it should be?

**Comment by reedwm** [comment]
> To be clear, the workaround of getting the variable's Tensor from the metagraph by name works, right?

Yes and the variable object is in `tf.trainable_variables()`. The issue is just that the info `tf.get_variable()` to see if the variable has already been created with a previous call to `tf.get_variable` is not stored in the metagraph. I'm not sure if we would want to add such functionality.

**Comment by allenlavoie** [comment]
So maybe "contributions welcome"? It is indeed odd behavior, but unless there's a compelling use-case I don't know of anyone who would prioritize it.

**Comment by zyj183247166** [comment]
@reedwm what you have conveyed is just what i meant. in tensorflow, now we can use get_tensor_by_name to reuse the restored variable v1, but can not use get_variable function to reuse it.
@allenlavoie i think the  MetaGraph imports and newly constructed graphs should be grouped together.
i give one use case.
If someone want to reuse v1 in MetaGraph by get_variable, he will find some error. and v1 is collected to v1_1 in actual. I think, this is confusing.
If no improvement is made, it should also be explained in the tutorial.
