### ISSUE TITLE
Improper attribution for GPLv3 in non-existent directory

### ISSUE THREAD

**Issue by jamesiri** [tensorflow/tensorflow#20162]
### Describe the problem
You are declaring GPLv3 attribution at https://github.com/tensorflow/tensorflow/blob/v1.8.0/third_party/eigen3/LICENSE#L1011 for a directory that you have removed. The license attributed is also improperly identified as GPLv3 but instead should be GPLv2 as per Eigen's own repo, https://github.com/eigenteam/eigen-git-mirror/blob/master/bench/btl/COPYING.
The later isn't of much concern since you already removed the directory, but the former shows that you need to update your attribution to correctly reflect what is in the package. Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jamesiri** [comment]
Have I written custom code - no
OS Platform and Distribution - N/A
TensorFlow installed from - N/A
TensorFlow version - 1.8.0
Bazel version - N/A
CUDA/cuDNN version - N/A
GPU model and memory - N/A
Exact command to reproduce - N/A. I found this issue while I was digging through the repo.

**Comment by gunan** [comment]
I think you are looking at the btl subset of eigen.
From eigen website, I see that they also have GPLv3 license for the general package:
https://github.com/eigenteam/eigen-git-mirror/blob/master/COPYING.GPL
https://bitbucket.org/eigen/eigen/src/36d65672189a71a100340c1f675f763fd50d9e37/COPYING.GPL?at=default&fileviewer=file-view-default

but it looks like later versions of eigen changed to MPLv2. 
@rmalrsen @benoitsteiner , do the code under eigen3 we have come from head of eigen, or the files we have under eigen3 are a subset of eigen that have a different license?
