### ISSUE TITLE
TF Debug Session Wrapper has no attribute '_make_callable_from_options'

### ISSUE THREAD

**Issue by dillondaudert** [tensorflow/tensorflow#20160]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 18
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
v1.8.0-3410-g79d7e11f3e, 1.10.0-dev20180616
- **Python version**: 
3.6
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
CUDA 9.0, cuDNN 7.0
- **GPU model and memory**:
NVIDIA GeForce 1080
- **Exact command to reproduce**:
Running the provided script should produce the error. The attached file shows the output.

### Describe the problem
It's not possible to debug Keras models since `BaseDebugWrapperSession` in `tensorflow/python/debug/wrappers/framework.py` does not implement the `_make_callable_from_options` method.

### Source code / logs
- **Script**:
```python
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.python import debug as tf_debug


inputs = np.zeros((10, 3))
targets = np.zeros((10, 4))
dataset = tf.data.Dataset.from_tensor_slices((inputs, targets))
dataset = dataset.repeat(100)
dataset = dataset.batch(5)

with tf_debug.LocalCLIDebugWrapperSession(tf.Session()) as sess:
    keras.backend.set_session(sess)

    x = keras.layers.Input(shape=(3,), name='input')
    flat = keras.layers.Flatten()(x)
    y = keras.layers.Dense(4, name='dense')(flat)

    model = keras.Model(x, y)
    model.compile(loss='mse', optimizer='rmsprop')

    model.fit(dataset, epochs=1, steps_per_epoch=2, verbose=1)
```
- **Output**:
[tfdbg_output.txt](https://github.com/tensorflow/tensorflow/files/2120950/tfdbg_output.txt)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by asimshankar** [comment]
Thanks for the report. Indeed, seems like a little bit of work may be helpful here.

@caisq : Would you have the cycles to take this on? If not, let's discuss options.

FYI @fchollet @mrry

**Comment by caisq** [comment]
@dillondaudert Thank you for reporting this issue.
@asimshankar Thanks for cc'ing me on this issue. I will look into it.
