### ISSUE TITLE
Importing error with tensorflow1.8.0 and protobuf 3.6.0

### ISSUE THREAD

**Issue by marctuscher** [tensorflow/tensorflow#20173]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:binary pip
- **TensorFlow version (use command below)**:1.8
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:9.0 / 7.0
- **GPU model and memory**: GeForce GTX 1080Ti 11GB
- **Exact command to reproduce**: import tensorflow as tf

### Problem description
Importing tensorflow gives me following error. This error is only reproducible in a file where a computational graph is defined.
```
KeyError: "Couldn't find field google.protobuf.FileOptions.php_metadata_namespace"
```

### Solution
I already found a solution to this problem. It is related to the pip package protobuf 3.6.0. I solved this problem by issuing following commands:
```
pip3 uninstall protobuf
pip3 install protobuf==3.5.2
```

**Comment by gunan** [comment]
This is due to backwards incompatible changes in protobuf 3.6
This should be largely triaged in 1.9.

**Comment by agronskiy** [comment]
Worked in 1.9.0, thanks!

**Comment by qinhuangdaoStation** [comment]
thanks
