### ISSUE TITLE
Tensor Forest regression

### ISSUE THREAD

**Issue by JSSotola** [tensorflow/tensorflow#2017]
I was not able to find any documentation for Tensor Forest, however from the comment on line 90 in [tensor_forest.py](https://github.com/tensorflow/tensorflow/edit/master/tensorflow/contrib/tensor_forest/python/tensor_forest.py) it seems to follow that it is intended for regression as well as classification. However it does not accept floats as labels.

The following code:
`params = tensor_forest.ForestHParams(num_classes=1, num_features=features, num_trees=10, max_nodes=1000).fill()`
`graph_builder = tensor_forest.RandomForestGraphs(params)`
`graph = graph_builder.training_graph(X, y)`

Returns a value error:
`TypeError:  Input 'input_labels' of 'CountExtremelyRandomStats' Op has type float32 that does not match expected type of int32.`

**Comment by caisq** [comment]
@gilberthendry

**Comment by gilberthendry** [comment]
The released version of Tensor Forest doesn't support regression yet, apologies for the lack of a good error message or documentation.  But sit tight, it's implemented and just hasn't made its way to github yet.
