### ISSUE TITLE
SetNumThreads() with float models has no observable effect in TFLite

### ISSUE THREAD

**Issue by sfanxiang** [tensorflow/tensorflow#20187]
### Describe the problem
When running (a slightly tweaked version of) the example code in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/apis.md, I noticed that no matter what `interpreter->SetNumThreads()` is called with, it __only__ creates (and uses) 4 threads. The only exception is when I set it to 1, in which case the main thread is used. CPU usage is never at or near 100%.

Here's the code I'm running:
```c++
#include <tensorflow/contrib/lite/kernels/register.h>
#include <tensorflow/contrib/lite/model.h>
#include <memory>

int main()
{
	std::unique_ptr<tflite::FlatBufferModel> model =
		tflite::FlatBufferModel::BuildFromFile("model.tflite");

	tflite::ops::builtin::BuiltinOpResolver resolver;
	std::unique_ptr<tflite::Interpreter> interpreter;
	tflite::InterpreterBuilder(*model, resolver)(&interpreter);

	interpreter->SetNumThreads(8);
	interpreter->AllocateTensors();

	while (true)
		interpreter->Invoke();
}
```

Tensorflow Lite is built with `make -f tensorflow/contrib/lite/Makefile`, from branch r1.9.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch Linux
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.9.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: 0.14.1
- **GCC/Compiler version (if compiling from source)**: 8.1.1
- **CUDA/cuDNN version**: CPU only
- **GPU model and memory**: CPU only
- **Exact command to reproduce**: (Build the C++ example in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/apis.md)

**Comment by freedomtan** [comment]
Are you using floating point number model? If yes, that's expected behavior.

**Comment by sfanxiang** [comment]
> Are you using floating point number model?

Yes.

> If yes, that's expected behavior.

Good to know. However, I cannot find any docs or think of why there's a limitation on floating point numbers. Could you point out the technical reason behind this?

Thanks!

**Comment by freedomtan** [comment]
The reason is that the number of threads is hard-coded in the source code, see [1]. In case you don't know it, TF Lite relies on [Eigen](http://eigen.tuxfamily.org/) and [gemmlowp](https://github.com/google/gemmlowp) for floating point and integer convolutions respectively. 

[1] https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/contrib/lite/kernels/internal/optimized/multithreaded_conv.h#L58

**Comment by sfanxiang** [comment]
[multithreaded_conv.h#L55](https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/contrib/lite/kernels/internal/optimized/multithreaded_conv.h#L55) says:
> since the underlying resource of CPU cores should be consumed by the operations anyway, it shouldn't affect overall performance.

Is this understanding correct:
- There's little performance gain in increasing the number of threads for a single invocation, i.e. by changing `thread_count` at [L58](https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/contrib/lite/kernels/internal/optimized/multithreaded_conv.h#L58).
- There is, however, some performance gain if several invocations are run in parallel (e.g. by using one thread for each).

---------

Hypothetically, apart from the implementation difference between Eigen and gemmlowp, what differs floating point and integer so much that we can't (or shouldn't) even run floating point convolutions from more than 4 threads? IMO not all models are suitable for quantization.

Thank you!

**Comment by freedomtan** [comment]
@sfanxiang Whether increasing the number of threads can get performance gain is actually system and workload dependent. E.g., for large amount of convolution on modern x86 Xeon platform, number of threads > 4 could be useful. I guess 4 is there just as a convenient hack. On most modern cell phones, 4 should work pretty well, except some big.LITTLE systems, such as one with 2xbig + 4xLITTE.

**Comment by freedomtan** [comment]
@sfanxiang set number of threads should work for after 2bfc7957dad
