### ISSUE TITLE
tensorflow lite with ndk 17 compilatoin failed

### ISSUE THREAD

**Issue by dimitryn** [tensorflow/tensorflow#20192]
Hi ,  I took latest tensorflow sources from github and try to build tensorflow lite.
There was error compilation.

We upgraded our NDK version from 16 to 17 couple weeks ago and tensorflow lite compiled **without any error**. But latest sources from today failed to compile.

```
INFO: Found 1 target...
ERROR: XXX/tensorflow/contrib/lite/kernels/BUILD:57:1: C++ compilation of rule '//tensorflow/contrib/lite/kernels:gemm_support' failed (Exit 1)
In file included from tensorflow/contrib/lite/kernels/gemm_support.cc:15:
In file included from ./tensorflow/contrib/lite/kernels/gemm_support.h:18:
In file included from external/gemmlowp/public/gemmlowp.h:19:
In file included from external/gemmlowp/public/../internal/dispatch_gemm_shape.h:20:
In file included from external/gemmlowp/public/../internal/../internal/kernel_default.h:22:
In file included from external/gemmlowp/public/../internal/common.h:26:
In file included from external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/cmath:305:
In file included from external/androidndk/ndk/sources/android/support/include/math.h:32:
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/math.h:1302:93: error: no member named 'log2f' in the global namespace
inline _LIBCPP_INLINE_VISIBILITY float       log2(float __lcpp_x) _NOEXCEPT       {return ::log2f(__lcpp_x);}
                                                                                          ~~^
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/math.h:1303:93: error: no member named 'log2l' in the global namespace
inline _LIBCPP_INLINE_VISIBILITY long double log2(long double __lcpp_x) _NOEXCEPT {return ::log2l(__lcpp_x);}
                                                                                          ~~^
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/math.h:1308:38: error: call to 'log2' is ambiguous
log2(_A1 __lcpp_x) _NOEXCEPT {return ::log2((double)__lcpp_x);}
                                     ^~~~~~
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/math.h:1302:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY float       log2(float __lcpp_x) _NOEXCEPT       {return ::log2f(__lcpp_x);}
                                             ^
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/math.h:1303:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long double log2(long double __lcpp_x) _NOEXCEPT {return ::log2l(__lcpp_x);}
                                             ^
3 errors generated.
Target //tensorflow/contrib/lite:libtensorflowLite.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 60.727s, Critical Path: 13.01s
INFO: 19 processes, local.
FAILED: Build did NOT complete successfully
```

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu
- **TensorFlow installed from (source or binary)**:
sources 
- **TensorFlow version (use command below)**:
master
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
0.14
- **GCC/Compiler version (if compiling from source)**:
NDK 17
- **CUDA/cuDNN version**:
No
- **GPU model and memory**:
No
- **Exact command to reproduce**:
bazel build //tensorflow/contrib/lite:framework --crosstool_top=//external:android/crosstool --cpu=arm64-v8a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++14"

Thanks for help

**Comment by kismeter** [comment]
I met the same issue. I always using NDK 17 without any error, but today pull the latest source, the issue happen.

**Comment by sunshinemyson** [comment]
I met same issue while building Android Demo under $TF_Root/tensorflow/example/android. NDK 17 installed.
build command: bazel build -c opt tensorflow/examples/android:tensorflow_demo

**Comment by shashishekhar** [comment]
Looks like this is due to Android API level, which causes this error. With recent versions of NDK these errors happen if one is compiling with NDK API level below < 21. 

I can fix the error if I change tensorflow/.tf_configure.bazelrc to

build --action_env ANDROID_NDK_API_LEVEL=21

It also seems that NDK API level parsing logic is incorrect in configure.py:
https://github.com/tensorflow/tensorflow/blob/master/configure.py#L674

Right now it parses the NDK version in sources.properties.
Instead it should get the API level lists from:
using something like:
ls $ANDROID_NDK_PATH/platforms | cut -d '-' -f 2 | sort -n | tail -1
@case540 , @angersson  this logic needs to be updated.

@dimitryn , @kismeter : To get you unblocked, can you try to update ANDROID_NDK_API_LEVEL in .tf_configure.bazelrc to set to 21.

**Comment by dimitryn** [comment]
thanks

**Comment by Fa1c0nSec** [comment]
No, just like @shashishekhar said, you need to add one line in tensorflow/.tf_configure.bazelrc:
build --action_env ANDROID_NDK_API_LEVEL=21
if that doesn't work, you need to change your workspace file which in tensorflow/WORKSPACE, and modify your ndk repository settings with:

android_ndk_repository(
    name = "androidndk",
    path = "/Users/kyoushouu/Library/Android/sdk/ndk-bundle",
    api_level = 21,
)

and rebuild tensorflow lite will be best solution for this issue.
