### ISSUE TITLE
`tf.contrib.data.sliding_window_batch` cannot slide further than the window size

### ISSUE THREAD

**Issue by danielwatson6** [tensorflow/tensorflow#20191]
### System information
- **Have I written custom code: yes**:
- **OS Platform and Distribution: macOS High Sierra 10.13.4**:
- **TensorFlow installed from: binary**:
- **TensorFlow version: 1.8.0**:
- **Python version: 3.6.5**: 
- **CUDA/cuDNN version, GPU info: N/A; not using GPU support**:
- **Exact command to reproduce**:

### Problem
`tf.contrib.data.sliding_window_batch` requires that the `stride` argument lie in the range `[1, window_size)`. This limits potential uses for this function. For example; consider the following scenario where the model is fed an element and must predict the previous and next element. Here is the description of the task more precisely:

We have data elements `(e0, e1, e2, ...)`. The model has to learn to predict `e_{i-1}, e_{i+1}` given `e_i`. To give the model triples of batches from the original sequence `(e0, e1, e2, ...)`, we could use `tf.contrib.data.sliding_window_batch` as follows, assuming `dataset` yields `(e0, e1, e_2, ...)`:

```python
dataset = dataset.apply(window_size=batch_size, stride=1)
# yields ([e_0, ..., e_{b-1}], [e_1, ..., e_b], [e_2, ..., e_{b+1}], ...)

dataset = dataset.apply(window_size=3, stride=batch_size)
# yields:
# [[e_0, ..., e_{b-1}],     [[  e_b  , ..., e_{2b-1}],
#  [e_1, ...,   e_b  ],  ;   [e_{b+1}, ...,   e_2b  ],  ;  ...
#  [e_2, ..., e_{b+1}]]      [e_{b+2}, ..., e_{2b+1}]]
```

Notice how the training inputs would be the middle row, and if the stride size were smaller, we would feed the same input-labels triples to the model twice. So the stride size in this case needs to be larger than the window size, but the existing implementation does not allow that.

### Source code / logs
As soon as one attempts to run the iterator within a session, one gets an error log with this relevant line:
```
...
tensorflow.python.framework.errors_impl.InvalidArgumentError: Stride must be in [1, window_size).
```

**Comment by mrry** [comment]
Seems reasonable to allow this. IIRC this op was a contribution from @facaiy, and we'd welcome contributions to improve it and fix this bug.

**Comment by facaiy** [comment]
Thanks for ping me, @mrry.

The restriction is designed for safety at first, since it means lost data if `stride > batch_size`. I think if people really need it, they should use `filter` explicitly with `batch` instead . 

Take the case of @danielwatson6 , I think there are at least two solutions:

1. 
```python
dataset.apply(sliding_window_batch(window_size=batch_size, stride=1))
        .filter()   # drop the data you don't need
        .batch(batch_size)
```

2.
```python
dataset.apply(sliding_window_batch(window_size=3, stride=1))
        .batch(batch_size)
        .map(lambda x: tf.transpose(x))
```

**Comment by danielwatson6** [comment]
@facaiy Thanks for the reply! Do you think it would be possible to set it as a warning instead? It's a more direct solution compared to passing lambdas. Surely the user understands that they are skipping items in the generator if the stride size exceeds the window size.

**Comment by facaiy** [comment]
@danielwatson6 Hi, what do you think of the second solution I wrote above?

**Comment by facaiy** [comment]
I create PR #20223 to solve the issue. Could you take a look? Thanks. cc @mrry.
