### ISSUE TITLE
Better error message for tf.assign

### ISSUE THREAD

**Issue by domluna** [tensorflow/tensorflow#202]
When I try to use tf.assign I'm always running into the error message

TypeError: Input 'ref' of 'Assign' Op requires l-value input

I have no idea what this means. It's a pretty unhelpful error message.

Some context ...

```
a = tf.random_normal([4,4]) # I tried this with tf.constant and tf.Variable and got the same result

tf.assign(tf.slice(a, [1, 0], [-1, -1]), tf.slice(a, [0, 0], [3, -1]))

tf.assign(a, 5)

tf.assign(a, a)
```

All three give the same error message.

**Comment by vrv** [comment]
http://tensorflow.org/get_started/basic_usage.md#variables  -- you might find that useful.

You can only assign to a tf.Variable -- that is the only mutable state you can use the assign ops with.

We'll see if we can come up with a better error message in the meantime.  Thanks for the report!

**Comment by girving** [comment]
@michaelisard: Assigning to you since presumably this will change as part of upcoming work.

**Comment by girving** [comment]
Switching to @prb12: Should we mark this as contributions welcome or is something more elaborate than an error message change warranted?

**Comment by prb12** [comment]
It makes no sense to assign this to me?

**Comment by aselle** [comment]
This is pretty much the exact error that gcc gives when you try to write 
f(){ 3 = f; }
OTOH, since we are embedded in another programming language the subtlety between a tensorflow variable and a python variable that is a handle to partial tensorflow graph is not obvious to the uninitiated.  Leaving open in case someone wants to update the error message.

**Comment by codeisnotcode** [comment]
FWIW, I think vrv's explanation would make a very clear error message:
"TypeError: You can only tf.assign to a tf.Variable"
and the actual error message of 
"TypeError: Input 'ref' of 'Assign' Op requires l-value input" 
makes no sense unless one knows what an "I-value input" is (which I don't, even after reading this thread).

**Comment by iRapha** [comment]
I can work on this but I wanted to clarify something:

This error message [0] is only raised when the ref input needs to be of type `tf.Variable`, right? I can't find another example of it being raised. If so, this change is really just a matter of updating [0] and I can have a PR in no time :)

[0] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/op_def_library.py#L621

**Comment by girving** [comment]
@iRapha That sounds right.
