### ISSUE TITLE
[FEATURE REQUEST] tf.scatter_nd doesn't support half types

### ISSUE THREAD

**Issue by x10000year** [tensorflow/tensorflow#20219]
I try to use tf.scatter_nd and tf.scatter_max for tf.float16 input, but it reports that it doesn't support half types. Can tf.scatter_nd  and tf.scatter_max add support for half types? Thanks.

@kosklain @dantkz

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by drpngx** [comment]
I don't see why not.

**Comment by drpngx** [comment]
That would be a good contribution if you feel up to it. Thanks!

**Comment by facaiy** [comment]
I'm afraid that [tf.scatter_add](https://www.tensorflow.org/versions/master/api_docs/python/tf/scatter_add) indeed supports half type in the latest version.

**Comment by x10000year** [comment]
@facaiy scatter_xxx supports half type only for cpu kernel. No gpu kernel is registered for half type.

**Comment by facaiy** [comment]
Yes, you're right. I checked the source code and found that float16 is not registered for GPU kernel to avoid compile failure.

https://github.com/tensorflow/tensorflow/blob/c1d223de41838e9d387a48137c76ea39d3b38f3f/tensorflow/core/kernels/scatter_functor_gpu.cu.cc#L43-L49

Perhaps we can uncomment the last code and let's see what happens :-)

**Comment by facaiy** [comment]
I register the float16 gpu kernel for scatter function in PR #20244, and then I run those related tests. All seems passed.

**Comment by x10000year** [comment]
@facaiy 
In scatter_nd_op.cc there are several TF_CALL_GPU_NUMBER_TYPES_NO_HALF.  Do they need to be fixed?

**Comment by facaiy** [comment]
@x10000year Would you like to create a pull request and make the contribution? Take a try to fix it. 

The test file of `scatter_nd` is [here](https://github.com/tensorflow/tensorflow/blob/cb401f09be5b816e704a70babc0facad63e84636/tensorflow/python/kernel_tests/scatter_nd_ops_test.py#L146). If I'm not wrong, we could fix `scatter_nd` by the similar way as we do in PR #20244.

**Comment by x10000year** [comment]
@facaiy sorry I know almost nothing about c++. I will appreciate if you can create a PR :)

**Comment by facaiy** [comment]
@x10000year Sure, I have registered float16 gpu kernel for scatter_nd in
e369dbb .

**Comment by chunduriv** [comment]
@x10000year, Sorry for the late response. 

`tf.scatter_nd ` supports half type. For more details please refer to this commit 5e28f0c5c83afc3ede7758b2b541777e719cb146. Thanks!
