### ISSUE TITLE
tf.flags not compatible with old versions

### ISSUE THREAD

**Issue by xueeinstein** [tensorflow/tensorflow#20214]
The new `tf.flags` APIs (>1.4.1) perform badly, not compatible with old ones, even raise weird exception like: 

```
absl.flags._exceptions.IllegalFlagValueError: flag --env_worker_samples=100000.0: Expect argument to be a string or int, found <class 'float'>
```

In fact, I use '--env_worker_samples 100000' in command line.

Why does the official not provide any instruction on migrating `tf.flags` to new version TF?

**Comment by xueeinstein** [comment]
Some related, unsolved but closed issues including #17132

**Comment by facaiy** [comment]
I think @asimshankar answered the similar question in #17734.

**Comment by xueeinstein** [comment]
@facaiy I see that since TensorFlow 1.5, __absl-py__ is used as arguments parser. I have fixed this exception. Thanks.
