### ISSUE TITLE
bazel not respecting PYTHONPATH

### ISSUE THREAD

**Issue by chemelnucfin** [tensorflow/tensorflow#2021]
### Environment info
Operating System: Fedora 23

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
Built without GPU

If installed from sources, provide the commit hash:
c303ff7

### Steps to reproduce
1.  bazel --output_base=/projects/.cache test //tensorflow/...

### What have you tried?
1.  starting python from command line and import tensorflow is ok.
2.  the above command line produces tests shown below in the pastebin in the log section
3.  echo $PYTHONPATH
/usr/local/lib/python3.4/site-packages:/projects/.cache/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/tools/pip_package/build_pip_package.runfiles
4.  I think there is an imports function recently added for bazel, would like some pointers to see if this is the best way to solve this problem and change all the bazel files (and not commit them to pull requests), or if there are better ways.
http://bazel.io/docs/be/python.html
5. (EDIT) #1704 following comments did not work.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
http://pastebin.com/hTw53y2X

**Comment by vrv** [comment]
@davidzchen in case he knows what's going on here (or knows someone who might)

**Comment by davidzchen** [comment]
Sorry for the delay.

I have also seen this issue appear in the same setup -- building a target with Python protobuf while at the same time having Python protobuf installed locally on the machine. This seems to be the case even with the `imports` attribute set.

I have opened bazelbuild/bazel#1193 to track this.

**Comment by davidzchen** [comment]
This turned out to be a problem in the protobuf Bazel build setup. google/protobuf#1586 has been merged to fix this problem. Once tensorflow/tensorflow#1289 is merged to bump TensorFlow's dependency to the protobuf version that contains the fix, this problem will be fixed on the TensorFlow side as well.

**Comment by trinity77** [comment]
Trigger last updated
