### ISSUE TITLE
Use shallow clones from git repos in CMake build

### ISSUE THREAD

**Issue by KOLANICH** [tensorflow/tensorflow#20222]
Please add

```cmake
GIT_SHALLOW 1
GIT_PROGRESS 1
```

to all cmake files cloning git repos in ``contrib/cmake/external`

**Comment by meggamind** [comment]
https://github.com/tensorflow/tensorflow/pull/20525

**Comment by KOLANICH** [comment]
@meggamind,  these should be arguments to https://cmake.org/cmake/help/v3.6/module/ExternalProject.html

**Comment by meggamind** [comment]
@KOLANICH Got it, will makes the changes

**Comment by meggamind** [comment]
@KOLANICH I updated the PR, Please let me know if any changes needs to be done

**Comment by KOLANICH** [comment]
1 these arguments should only be added to the files using git, for files downloading zips and tars they are useless.

you can find the files using git by usage of the variables GIT_REPOSITORY

2 when using shallow clones with GIT_TAG fetches will likely fail

3 So we need a cache bool variable controlling if 
GIT_TAG should be used or GIT_SHALLOW. GIT_PROGRESS should be added unconditionally since it just showes the progress.

**Comment by KOLANICH** [comment]
Sorry for the late answer, I have just noticed your message.

**Comment by KOLANICH** [comment]
If I remember right, it was not me who was fetching the repos, but the build scripts. Anyway, building TensorFlow is unbearable for me, so I have to resort on the prebuilt one, but I still think that optimizing (speeding up and making it consume and waste less resources) building process is always beneficial, if not for me directly, then for other people and then for me indirectly (through increasing possible amoint of third-party builds and reducing number of changes to be done to make the process bearable for me).

**Comment by tilakrayal** [comment]
@KOLANICH,
CMake is away with TF 1.11. Please have a look at https://github.com/tensorflow/tensorflow/releases/tag/v1.10.0. Also apologies for the experience on building the tensorflow. 
The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
