### ISSUE TITLE
Build fails while creating Python API: "TypeError: argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by cjmayo** [tensorflow/tensorflow#20233]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Gentoo Linux
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.9.0-rc1
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: 0.14.1
- **GCC/Compiler version (if compiling from source)**:  7.3.0
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: None
- **Exact command to reproduce**: building using Gentoo ebuild

### Describe the problem
Build fails while creating Python API.

### Source code / logs
```
"/var/tmp/portage/sci-libs/tensorflow-1.9.0_rc1/work/bazel-base-python3_6/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/tools/api/generator/create_python_api.py", line 182, in get_api_init_text
    package not in module.__name__):
TypeError: argument of type 'NoneType' is not iterable
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3202.457s, Critical Path: 83.98s
INFO: 4901 processes, local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

Fixed for me with:
```
--- tensorflow-1.9.0-rc1.orig/tensorflow/tools/api/generator/create_python_api.py
+++ tensorflow-1.9.0-rc1/tensorflow/tools/api/generator/create_python_api.py
@@ -179,7 +179,7 @@
   for module in list(sys.modules.values()):
     # Only look at tensorflow modules.
     if (not module or not hasattr(module, '__name__') or
-        package not in module.__name__):
+        module.__name__ is None or package not in module.__name__):
       continue
     # Do not generate __init__.py files for contrib modules for now.
     if '.contrib.' in module.__name__ or module.__name__.endswith('.contrib'):
```

because `module.__name__` can be None.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
CUDA/cuDNN version
GPU model and memory

**Comment by yongtang** [comment]
@cjmayo Maybe you can submit the pull request of your patch?

**Comment by cjmayo** [comment]
Creating a pull request is not a problem but the CLA put me off, not expecting to create any more patches.

I think this one is trivial, and in any case I'm happy if anyone wants to use it.

**Comment by yongtang** [comment]
@cjmayo I created a PR #20250 with your patch.

**Comment by cjmayo** [comment]
Great, thanks.
