### ISSUE TITLE
Batched tf.linspace; documentaton says its possible, but returns error

### ISSUE THREAD

**Issue by MarkGreeny** [tensorflow/tensorflow#20258]
Following documentation [here](https://www.tensorflow.org/api_docs/python/tf/lin_space) it says that in `tf.linspace(start=A,stop=B, n)`, `A` and `B` are to be Tensors. But

    A=tf.constant(np.array([1.,2.,3.]))

    B=tf.constant(np.array([3.,4.,5.]))

    tf.linspace(A,B,3)

returns an error, that A should have shape 0, which contradicts the documentation. Is there some other way to achieve this? The desired output is

`array([[1,2,3],[2,3,4],[3,4,5]])`

**Comment by MarkGreeny** [comment]
@facaiy  Not at all. Thank you!

**Comment by yongtang** [comment]
I created a PR #20264 to update the docstring.

**Comment by MarkGreeny** [comment]
@facaiy Could you please show me an example how to use it? I do not know how to employ it. How do I get a tensor from it? Thank you kindly.

@yongtang Great!

**Comment by ZigaSajovic** [comment]
@MarkGreeny 

To make your example complete, you need to specify the `num` parameter, as the `tf.linspace` requires it. With that in mind, your request is fulfilled by

`A=tf.constant(np.array([1.,2.,3.]))

B=tf.constant(np.array([3.,4.,5.]))

N=3#or any integer you'd like

AB=tf.stack([A,B],axis=1)

batched_linspace=tf.map_fn(lambda ab: tf.linspace(ab[0],ab[1],N), AB)

sess.run(batched_linspace)`

which promptly returns

> array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.]])

as requested.

**Comment by facaiy** [comment]
@MarkDaoust Perhaps the tutorial [ Importing Data ](https://www.tensorflow.org/versions/master/programmers_guide/datasets) would be helpful for you.

```python
import tensorflow as tf

dataset = (tf.data.Dataset.range(1, 6)
                          .apply(tf.contrib.data.sliding_window_batch(3, 1))
                          .batch(3))
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

with tf.Session() as sess:
  res = sess.run(next_element)
  print(res)
# [[1 2 3]
#  [2 3 4]
#  [3 4 5]]
```
