### ISSUE TITLE
Constraint optimization?

### ISSUE THREAD

**Issue by ataber** [tensorflow/tensorflow#2025]
Hello! Are there any plans for adding constraints to trainable variables? If not, I'd like to request it. Thanks!

**Comment by yaroslavvb** [comment]
You can do equality constraints by adding up gradients from 2 variables.
IE, initialize them the same and do a+=(agrad+bgrad); b+=(agrad+bgrad)

**Comment by yaroslavvb** [comment]
Closing due to lack of details/activity

**Comment by IreneZihuiLi** [comment]
So it is like to use Lagrange Multipliers, just combine with new alphas.

**Comment by samuela** [comment]
Is there a way to do proper constrained optimization? Besides using a Lagrangian relaxation?

**Comment by IreneZihuiLi** [comment]
Maybe you would try KKT? (But I think it is also from Lagrangian....)

**Comment by zakizhou** [comment]
any beautiful solution?
