### ISSUE TITLE
PIP user-op tests-on-install FAILED

### ISSUE THREAD

**Issue by nbcsm** [tensorflow/tensorflow#20269]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
1.9, cpu
- **Python version**: 
Python 3.5
- **Bazel version (if compiling from source)**:
0.11.0
- **GCC/Compiler version (if compiling from source)**:
gcc version 5.4.0 20160609
- **CUDA/cuDNN version**:
NA
- **GPU model and memory**:
NA
- **Exact command to reproduce**:
ci_parameterized_build.sh with TF_BUILD_IS_PIP=PIP

### Describe the problem
I am using ci_parameterized_build.sh to build tensorflow whl in our CI system.
After https://github.com/tensorflow/tensorflow/commit/fdbb80f217d3a153b4eda66c766df921b3f73ab4, i found do_test_user_ops kept failing due the the following error.

Just let you guys know, @case540 as well.
Thanks.

[1m=== PIP test step 4 of 7: do_test_user_ops (User ops test) ===[0m

=== Testing user ops ===
PYTHON_BIN_PATH: /workspace/pip_test/venv/bin/python
/tmp/tmp.o7UMG4on4E /workspace
TensorFlow compile flags: -I/workspace/pip_test/venv/lib/python3.5/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1
TensorFlow link flags: -L/workspace/pip_test/venv/lib/python3.5/site-packages/tensorflow -ltensorflow_framework

g++ version:
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
lib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 

Extra GPP flag: 
Testing user ops in CPU environment
ero_out_op_kernel_1.cc
In file included from /workspace/pip_test/venv/lib/python3.5/site-packages/tensorflow/include/tensorflow/core/framework/numeric_types.h:20:0,
			  from /workspace/pip_test/venv/lib/python3.5/site-packages/tensorflow/include/tensorflow/core/framework/allocator.h:23,
			  from /workspace/pip_test/venv/lib/python3.5/site-packages/tensorflow/include/tensorflow/core/framework/op_kernel.h:23,
ero_out_op_kernel_1.cc:17:
/workspace/pip_test/venv/lib/python3.5/site-packages/tensorflow/include/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
compilation terminated.
ero_out_op_kernel_1.cc FAILED
PIP user-op tests-on-install FAILED

**Comment by gunan** [comment]
@case540 just fixed this at head.

However, ci_parameterized_build.sh is going away. You should write your own test script or use another one under `tensorflow/tools/ci_build/linux`
