### ISSUE TITLE
dataset.map function needs better documentation

### ISSUE THREAD

**Issue by MalcolmSlaney** [tensorflow/tensorflow#20265]
Can the documentation for dataset.map be fleshed out a bit? Most importantly, what are the input and output arguments for the mapping function? The current documentation implies there is only one return, but all the code examples show (input,output).  What is the meaning of the input and output args?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by facaiy** [comment]
cc @mrry
