### ISSUE TITLE
Could the site refer change?

### ISSUE THREAD

**Issue by zfk513** [tensorflow/tensorflow#20270]
Hi ,in https://www.tensorflow.org/mobile/tflite/demo_android 
the demo site (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/java/demo/app)
actually is direct,but i found i could not successful build it cuz various problem
And  occasionally i found this site:https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/java/demo
it is much better and i can easily deploy on my phone without any change,Great!

**Comment by marshalhayes** [comment]
Hi @zfk513. If I understand correctly, it appears that the [Android Demo App](https://www.tensorflow.org/mobile/tflite/demo_android) example application link brings you inside the `app` directory within [tensorflow/tensorflow/contrib/lite/java/demo/](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/java/demo). 

You are proposing that this link be changed from [https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/java/demo/app](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/java/demo/app) to [https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/java/demo/](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/java/demo)

Is that correct?

**Comment by zfk513** [comment]
@marshalhayes 
yeah,thx for translating

**Comment by asimshankar** [comment]
Sounds fair enough, will send out a change.

**Comment by zfk513** [comment]
@asimshankar thank you
