### ISSUE TITLE
tflite_convert raises TypeError: object of type 'zip' has no len()

### ISSUE THREAD

**Issue by GPhilo** [tensorflow/tensorflow#20276]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: docker image tensorflow/tensorflow:nightly-py3
- **TensorFlow installed from (source or binary)**: -
- **TensorFlow version (use command below)**: latest (1.9.0 rc1)
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: -
- **GCC/Compiler version (if compiling from source)**: -
- **CUDA/cuDNN version**: -
- **GPU model and memory**: -
- **Exact command to reproduce**: `tflite_convert --output_file=out.tflite --saved_model_dir=1529923978/ --inference_type=QUANTIZED_UINT8 --mean_values=128 --std_dev_values=127 --input_array=input`

### Describe the problem
Trying to run the script above in Python 3 raises a `TypeError: object of type 'zip' has no len()`.
This is caused by [line 107 of the `tflite_converter` script](https://github.com/tensorflow/tensorflow/blob/f202958ee2d5177a474e3d107fdbf0c83174d099/tensorflow/contrib/lite/python/tflite_convert.py#L107), more specifically by `len(quant_stats)`. `quant stats` is defined in [line 105](https://github.com/tensorflow/tensorflow/blob/f202958ee2d5177a474e3d107fdbf0c83174d099/tensorflow/contrib/lite/python/tflite_convert.py#L105) as `zip(mean_values, std_dev_values)`.

**Comment by yongtang** [comment]
I think the issue could be resolved with `list(zip(...)`. Added a PR #20278 for the fix.
