### ISSUE TITLE
Why does tf.placeholder() change the random state?

### ISSUE THREAD

**Issue by SCP-173-cool** [tensorflow/tensorflow#20297]
![image](https://user-images.githubusercontent.com/22118890/41892870-4e437440-794c-11e8-9267-31f600c34181.png)

**Comment by llan-ml** [comment]
You need to quite the current ipython console, and reopen a new one.

**Comment by facaiy** [comment]
see #14675: Small change to graph changes initial values of variables

**Comment by SCP-173-cool** [comment]
@facaiy Thx!
