### ISSUE TITLE
python  trap divide error

### ISSUE THREAD

**Issue by zc129** [tensorflow/tensorflow#2031]
# Environment info
Operating System:CentOS 7
GCC version:4.8.5
Cuda Toolkit:7.5
Cuda compiler driver:6.5
Built with GPU

# What have you tried?
## I run /usr/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py will print:Floating point exception

I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: Tesla K40m
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:04:00.0
Total memory: 11.25GiB
Free memory: 3.08GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:04:00.0)
Failed to get the number of CUDA devices: CUDA driver version is insufficient for CUDA runtime version
Floating point exception

## I view the system message:
Apr 20 10:53:43 milan kernel: traps: python[66624] trap divide error ip:7fc0113304d2 sp:7fbf74ff0170 error:0 in _pywrap_tensorflow.so[7fc00f573000+a38a000]

**Comment by vrv** [comment]
"Failed to get the number of CUDA devices: CUDA driver version is insufficient for CUDA runtime version" from your logs sounds like a problem -- try to upgrade your cuda driver?

**Comment by vrv** [comment]
(Or consider compiling from sources if you want to use an earlier CUDA runtime)
