### ISSUE TITLE
warning: no files found matching '*.dll' under directory '*'

### ISSUE THREAD

**Issue by zdlmgrzm9900** [tensorflow/tensorflow#20327]
Hi all, this problem has troubled me for a long time and I have not found a suitable solution.

My system informations:
- **Have I written custom code**: No, I just try to make a building wheel by Bazel.
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from**: source
- **TensorFlow version**: latest
- **Python version**: 3.5 
- **Bazel version**: 0.14.1
- **GCC/Compiler version**: 5.0+
- **CUDA/cuDNN version**: 8.0, 7.0.5
- **GPU model and memory**: GeForce GTX 1050 Ti (4GB)
- **Exact command to reproduce**:`bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg`

When I make a building wheel:

`bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg`

 I get some warnings like these:

```
2018年 06月 26日 星期二 14:22:53 CST : === Preparing sources in dir: /tmp/tmp.DJDLaJRILD
~/tensorflow ~/tensorflow
~/tensorflow
2018年 06月 26日 星期二 14:24:22 CST : === Building wheel
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
warning: no files found matching '*.h' under directory 'tensorflow/include/tensorflow'
warning: no files found matching '*' under directory 'tensorflow/include/Eigen'
warning: no files found matching '*.h' under directory 'tensorflow/include/google'
warning: no files found matching '*' under directory 'tensorflow/include/third_party'
warning: no files found matching '*' under directory 'tensorflow/include/unsupported'
2018年 06月 26日 星期二 14:26:01 CST : === Output wheel file is in: /tmp/tensorflow_pkg
```

Then, I check the **Output wheel files**, **but I did not find any tmp/tensorflow folder or .whl file.** 
I think many people are also facing the same confusion, anyone can help me?

Thanks in advance!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
GPU model and memory
Exact command to reproduce

**Comment by zdlmgrzm9900** [comment]
Thank you for the reminder, and  I have updated the issue

**Comment by gunan** [comment]
Those are just warning messages. Not error messages. Everything seems to be working as expected.
You can try creating a different folder and creating your pip package there.
Or you can simply try running
```
bazel-bin/tensorflow/tools/pip_package/build_pip_package .
```
Which should create the whl file in the folder you are running the command in.
