### ISSUE TITLE
Bug on  create a Dataset from a DataFrame when  index its not ordered

### ISSUE THREAD

**Issue by marcelino-m** [tensorflow/tensorflow#20347]
This code generate a  **segmentation fault**

```python
import pandas     as pd
import tensorflow as tf
import tensorflow.contrib.eager as tfe
tf.enable_eager_execution()

train = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=[2, 1, 4])
label = pd.Series([7, 8, 9], index=[2, 1, 4])

ds = tf.data.Dataset.from_tensor_slices((dict(train), label))
```

But this not,  (only index  it's changed) from **[2, 1, 4]** to **[0, 1, 4]**:
```python
import pandas     as pd
import tensorflow as tf
import tensorflow.contrib.eager as tfe
tf.enable_eager_execution()


train = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=[0, 1, 4])
label = pd.Series([7, 8, 9], index=[0, 1, 4])

ds = tf.data.Dataset.from_tensor_slices((dict(train), label))
```

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Kubuntu 17.10 (Artful Aardvark), Kernel 4.13.0-21-generic
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**:  3.6.3
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by marcelino-m** [comment]
I updated the missing information.

**Comment by asimshankar** [comment]
Thanks for the report @marcelino-m - it surely shouldn't crash, so I'll look into that.

In the mean time, a workaround would be to explicitly convert to tensors before creating the dataset, with something like this:

```
import tensorflow as tf
import pandas as pd
import numpy as np
tf.enable_eager_execution()

train = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=[2, 1, 4])
label = pd.Series([7, 8, 9], index=[2, 1, 4])

np_train  = {k: np.array(v) for k, v in dict(train).items()}
np_label = np.array(label)
ds = tf.data.Dataset.from_tensor_slices((np_train, np_label))
```

**Comment by marcelino-m** [comment]
thanks for the tips. I did something like that.
