### ISSUE TITLE
reg. tensorflow-gpu in amd windows

### ISSUE THREAD

**Issue by ironside007** [tensorflow/tensorflow#20340]
**I have Win 10/ AMD Raedon R5 M335
I am using Python 3.5 and tensorflow 1.0.0
I am also, working through Spyder as using Python Console would make handling the code very difficult**

Please guide me how should i use my gpu in the training of deep learning model i am working on. Currently it uses my CPU.

**PS: No solutions to previously made issues worked for me.**

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ironside007** [comment]
OS Platform and Distribution-Win 10
TensorFlow installed from-pip
TensorFlow version-1.0.0
Bazel version-Don't have
CUDA/cuDNN version-for Nvidia so didn't install
GPU model and memory-AMD Raedon R5 M335
Exact command to reproduce-deep learning model , training the data set on qns ans basis, for a chatbot

**Comment by gunan** [comment]
No official binaries for tf on AMD GPUs are available yet.
You can check out [tensorflow with SYCL](https://www.codeplay.com/portal/tensorflow%E2%84%A2-for-opencl%E2%84%A2-using-sycl%E2%84%A2) or [tensorflow with ROCM](https://github.com/ROCmSoftwarePlatform/tensorflow)
