### ISSUE TITLE
No instructions for NDK setup

### ISSUE THREAD

**Issue by nnegrey** [tensorflow/tensorflow#20354]
The setup steps for the NDK don't include how to install from an older version

Step 2 on https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android#bazel

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by nnegrey** [comment]
Have I written custom code: NA
OS Platform and Distribution: NA
TensorFlow installed from: NA
TensorFlow version: NA
Bazel version: NA
CUDA/cuDNN version: NA
GPU model and memory: NA
Exact command to reproduce: NA

**Comment by achowdhery** [comment]
Hi
Android Studio:
https://developer.android.com/ndk/guides/

**Comment by achowdhery** [comment]
or download directly https://developer.android.com/ndk/downloads/

**Comment by nnegrey** [comment]
Android Studio installs a version that is incompatible with Bazel (according to the guide. 

You can download it directly, but the guide doesn't provide steps to the reader on how they should then install the locally downloaded NDK. Providing those steps for the reader or a link to those steps make it easier for them to complete the task.

**Comment by achowdhery** [comment]
http://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip

**Comment by achowdhery** [comment]
This Dockerfile should also help
https://github.com/tensorflow/models/blob/master/research/object_detection/dockerfiles/android/Dockerfile
or use Android Studio
