### ISSUE TITLE
keras model to estimator in eager mode gives ValueError

### ISSUE THREAD

**Issue by kashif** [tensorflow/tensorflow#20377]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.13.4
- **TensorFlow installed from (source or binary)**: binary 
- **TensorFlow version (use command below)**:  1.9.0-rc1
- **Python version**:  3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
After enabling eager mode with `tf.enable_eager_execution()` if I convert my `tf.keras.Model` to an estimator via: `tf.keras.estimator.model_to_estimator(model)` I get:

```
INFO:tensorflow:Using the Keras model provided.
INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /var/folders/yg/t3pf0vds6c14zlhmq1jwwvtnsz8fsr/T/tmp197t8ju4
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/yg/t3pf0vds6c14zlhmq1jwwvtnsz8fsr/T/tmp197t8ju4', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1227bcdd8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-6cc0c716ca8a> in <module>()
----> 1 estimator = tf.keras.estimator.model_to_estimator(model)

/usr/local/lib/python3.6/site-packages/tensorflow/python/estimator/keras.py in model_to_estimator(keras_model, keras_model_path, custom_objects, model_dir, config)
    512 
    513   # Check if we need to call get_weights:
--> 514   if _any_variable_initialized():
    515     keras_weights = keras_model.get_weights()
    516     # Warn if config passed to estimator tries to update GPUOptions. If a

/usr/local/lib/python3.6/site-packages/tensorflow/python/estimator/keras.py in _any_variable_initialized()
     77     boolean, True if at least one variable has been initialized, else False.
     78   """
---> 79   variables = variables_module.global_variables()
     80   for v in variables:
     81     if getattr(v, '_keras_initialized', False):

/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/variables.py in global_variables(scope)
   1442     A list of `Variable` objects.
   1443   """
-> 1444   return ops.get_collection(ops.GraphKeys.GLOBAL_VARIABLES, scope)
   1445 
   1446 

/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in get_collection(key, scope)
   5905   @end_compatibility
   5906   """
-> 5907   return get_default_graph().get_collection(key, scope)
   5908 
   5909 

/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in get_collection(self, name, scope)
   3961       collected.
   3962     """  # pylint: disable=g-doc-exception
-> 3963     _assert_collection_is_ok(name)
   3964     with self._lock:
   3965       collection = self._collections.get(name, None)

/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in _assert_collection_is_ok(collection_name)
   6146     if collection_name in GraphKeys._VARIABLE_COLLECTIONS:  # pylint: disable=protected-access
   6147       raise ValueError(
-> 6148           "variable collections are not supported when eager execution is enabled."
   6149       )
   6150 

ValueError: variable collections are not supported when eager execution is enabled.
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment]
@anj-s @tanzhenyu : Mind taking a look?

(CC @fchollet )

**Comment by tanzhenyu** [comment]
Currently the tf.global_variables() function is not supported for eager execution.

**Comment by asimshankar** [comment]
@tanzhenyu : Global collections in general aren't used with eager execution and that won't change going forward.

That said, why do we need to use them at all? Can we use `Model.variables` to get all the variables instead of using the collection?

**Comment by tanzhenyu** [comment]
@asimshankar yes that's what I have in mind as well -- I have made one code change that takes in the keras model to search its own variables instead of searching global variables. (In the end there's no guarantee how many models exist in the graph by the way model_to_estimator works, so asking for global variables does not make sense here)

**Comment by tanzhenyu** [comment]
@karmel add feature supporting eager execution in model_to_estimator?

**Comment by karmel** [comment]
If that's the only delta, it seems pretty straightforward to resolve and make this compatible, which would be great.

**Comment by tanzhenyu** [comment]
@karmel  probably more than that, one example I can think of is the optimizers compiled by Keras is not compatible with eager -- Currently keras is utilizing its own optimizer instead TF 'native' optimizers, that will likely cause a problem in the conversion. On the other hand, the metrics compiled by Keras (and losses) might not support eager as well as of today.

**Comment by anj-s** [comment]
Stateless metrics are supported in Eager but not stateful metrics. Sample weight mode and weighted metrics are also not supported. I believe loss functions are eager compatible.

**Comment by karmel** [comment]
Got it. @tanzhenyu , care to add to the list of blocked features for now? We can readdress after some of the other issues are handled (ie, optimizers, stateful metrics in eager).

**Comment by bhack** [comment]
@tanzhenyu It seems not only that metrics compiled by Keras might not support eager mode. 
But seems that there is a general incompatibility between tf.keras and pure tf metrics. See https://github.com/tensorflow/tensorflow/issues/17168. As generally the metrics portfolio is not the same between tf.keras and tf (low level) users don't undertand why the need to select what API to use (high level/low level) based on the metrics that they need inside the same framework (tensorflow).

**Comment by pavithrasv** [comment]
@bhack Regarding the existence of multiple metrics modules - we are working towards integrating them. After that you will be able to use any metric with any API.

@tanzhenyu Stateful metrics are not supported in eager mode - this means irrespective of whether we convert keras model to estimator or not, this scenario is not supported today. This will be fixed as well when we integrate the metric modules. Having said that, this should not affect (and is independent) adding support for model_to_estimator in eager mode => should not cause a problem in conversion.

**Comment by bhack** [comment]
@pavithrasv This is the only plausible route. I hope it can land soon in master.

**Comment by tanzhenyu** [comment]
code shipped. Should be merged soon.

**Comment by tanzhenyu** [comment]
@kashif it's already live. can you try it before we close the ticket?

**Comment by kashif** [comment]
@tanzhenyu sure i'll compile up master and try it out asap!

**Comment by kashif** [comment]
works! thanks! See: https://github.com/kashif/tf-keras-tutorial/blob/master/7-estimators-multi-gpus.ipynb
