### ISSUE TITLE
tensorboard doesn't work well on Windows

### ISSUE THREAD

**Issue by iwmq** [tensorflow/tensorflow#20376]
Hey guys,
I use TensorFlow on Windows. When I invoked this command:
`tensorboard --logdir=output`
The **tensorboard** program didn't visualize my trained model as expected. Instead, it simply executed my model's python file.
Anyway, I tried this fully-qualified version:
`C:\Python36\Scripts\tensorboard --logdir=output`
It did work, and I got my model visualized successfully.
This is very strange. Invoking the same program **tensorboard** in different ways produce totally different results.
Can this be fixed in future releases?
Thank you so much.

**Comment by marshalhayes** [comment]
Hi @iwmq. I'm not too familiar with Python or TensorFlow on Windows. However, by looking at the location you executed `tensorboard`, I would assume you do not have `C:\Python36\Scripts\` added to your path. 

Please ensure that the directory where you installed Python is added to your path environment variable. You can do this from My Computer > Properties > Advanced System Settings > Environment Variables. In your case, just add `C:\Python36\` and `C:\Python36\Scripts\`. Close and relaunch your terminal and TensorBoard should work well now.

**Comment by iwmq** [comment]
Hi @marshalhayes , thank you. I resolved this glitch of my code. 
It's me to blame. I named the python program file as _tensorboard.py_, so the program I invoked is my own model script.
