### ISSUE TITLE
Keras Tensorboard callback fails with tf.eager

### ISSUE THREAD

**Issue by EKami** [tensorflow/tensorflow#20372]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: Via pip
- **TensorFlow version (use command below)**: 1.9.0-rc1
- **Python version**:  3.6.5
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 9.0/7.0
- **GPU model and memory**: GTX 1080Ti/11GB
- **Exact command to reproduce**: Code given below

### Describe the problem
I'm using tf.eager, Keras model subclassing and tf.Dataset on TF 1.9.0-rc1. When I try to add the Tensorboard callback to the Keras `.fit` method I get the following error:
```
  File "/home/ekami/workspace/src/main.py", line 112, in <module>
    main(args)
  File "/home/ekami/workspace/src/main.py", line 63, in main
    validation_steps=3)
  File "/home/ekami/workspace/src/models/base_model.py", line 75, in fit
    sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
  File "/home/ekami/Programs/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1328, in fit
    validation_steps=validation_steps)
  File "/home/ekami/Programs/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_eager.py", line 979, in fit_loop
    callbacks.set_model(callback_model)
  File "/home/ekami/Programs/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 70, in set_model
    callback.set_model(model)
  File "/home/ekami/Programs/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 763, in set_model
    self.merged = tf_summary.merge_all()
  File "/home/ekami/Programs/anaconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/summary/summary.py", line 311, in merge_all
    'Merging tf.summary.* ops is not compatible with eager execution. '
RuntimeError: Merging tf.summary.* ops is not compatible with eager execution. Use tf.contrib.summary instead.
```

Here is a pseudo code to reproduce the error:
```
train_ds, train_slides, val_ds, val_slides, lookup_table = Dataset(logger, input_dir, output_dir, crop_size,
                                           cache_slide_size=cache_slide_size).get_dataset() # Returns a tf.Dataset object

patches_len = len(train_slides[0].patches)
model = SimpleCNNModel(num_classes=len(lookup_table))
model.compile(optimizer=tf.train.AdamOptimizer(),
                          loss='categorical_crossentropy',
                          metrics=['accuracy'])
model.fit(train_ds, epochs=args.epochs,
                callbacks=[tf.keras.callbacks.TensorBoard()],  # Will fail with the above error
                batch_size=batch_size,
                steps_per_epoch=patches_len // batch_size,
                shuffle=True,
                validation_data=val_ds,
                validation_steps=3)
model.save_weights(weights_pth)
logger.info("Done training!")
```

### Source code / logs

Given above

**Comment by pavithrasv** [comment]
Assigning to @anj-s as she has a fix ready.

**Comment by omalleyt12** [comment]
The code provided should now work

**Comment by EKami** [comment]
Perfect, thank you :)

**Comment by malikaltakrori** [comment]
> The code provided should now work

so should we just update ?

**Comment by omalleyt12** [comment]
@malikaltakrori yep

**Comment by malikaltakrori** [comment]
Thanks for the reply @omalleyt12 .
Note that I am working on Windows, not Linux. 
I did. Using Tensorflow version 1.10.0 and my callback is: 

`callbacks = [
        # Write TensorBoard logs to `./logs` directory
        tf.keras.callbacks.TensorBoard(),
        # tf.keras.callbacks.ModelCheckpoint("./checkpoints", monitor='val_loss', verbose=1, save_best_only=True,
        #                                 save_weights_only=False, mode='auto', period=1)
        hist

    ]

    history = model.fit([X_train_seqs, masked_X_train_seqs], y=tf.keras.utils.to_categorical(YDocLevel_train, 13),
              validation_data=([X_valid_seqs, masked_X_valid_seqs], tf.keras.utils.to_categorical(YDocLevel_valid, 13)),
              batch_size=16, epochs=100, shuffle=True, callbacks= callbacks)`
still got the same error:
File "D:\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\keras\callbacks.py", line 71, in set_model
    callback.set_model(model)
  File "D:\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\keras\callbacks.py", line 782, in set_model
    self.merged = tf_summary.merge_all()
  File "D:\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\summary\summary.py", line 311, in merge_all
    'Merging tf.summary.* ops is not compatible with eager execution. '
RuntimeError: Merging tf.summary.* ops is not compatible with eager execution. Use tf.contrib.summary instead.

**Comment by omalleyt12** [comment]
@malikaltakrori 1.10 is too early, please try 1.11 or nightly

**Comment by EKami** [comment]
I confirm it's now working on TF >= 1.11.0

**Comment by malikaltakrori** [comment]
I see. 
Maybe there is something going on with my installation. I did I try to upgrade (with pip install --upgrade tensorflow)  I get: 
`Requirement already up-to-date: tensorflow in d:\anaconda2\envs\tensorflow\lib\site-packages (1.11.0rc2)`
When I print tf.__version__ I get 1.10
and when I print tf.__file__ i get the correct location: 
`D:\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\__init__.py`

**Comment by MonsieurWave** [comment]
Recently updated to `TensorFlow version:  2.0.0-beta1`
I now get `ValueError: Session keyword arguments are not support during eager execution. You passed: {'callbacks': [<tensorflow.python.keras.callbacks.TensorBoard object at 0x1a473117f0>]}`

**Comment by dorian821** [comment]
I'm also experiencing this with TF 2.0.0-beta1

ValueError: Session keyword arguments are not support during eager execution. You passed: {'callbacks': [<tensorflow.python.keras.callbacks.EarlyStopping object at 0x00000000498CB940>, <tensorflow.python.keras.callbacks.EarlyStopping object at 0x00000000498CB9E8>]}

**Comment by omalleyt12** [comment]
@MonsieurWave could you share a code snippet to repro?

**Comment by fabioiuri** [comment]
Make sure that the callbacks argument is inside the `fit` call, and not inside the `compile`.
