### ISSUE TITLE
latest-gpu Docker image has broken cudnn

### ISSUE THREAD

**Issue by klopyrev** [tensorflow/tensorflow#2039]
Running import tensorflow:

>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:99] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:
I tensorflow/stream_executor/cuda/cuda_dnn.cc:1562] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally

Note that this seems to work with the latest-devel-gpu image. As far as I can tell the problem is caused by a missing symlink from /usr/lib/x86_64-linux-gnu/libcudnn.so to /usr/lib/x86_64-linux-gnu/libcudnn.so.4

**Comment by flx42** [comment]
See https://github.com/tensorflow/tensorflow/issues/808#issuecomment-187931361
And: https://github.com/tensorflow/tensorflow/issues/970#issuecomment-202999836

**Comment by girving** [comment]
@jendap: Do you know if this is still an issue?

**Comment by chan1** [comment]
@girving In case it's helpful, this is still an issue as of this week when using gcr.io/tensorflow/tensorflow:latest-gpu. As klopyrev mentioned, ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so.4 /usr/lib/x86_64-linux-gnu/libcudnn.so , fixes the issue.

**Comment by girving** [comment]
@chan1 Thanks.  Switching assignment to @caisq who knows more about the docker setup.

**Comment by alextp** [comment]
@klopyrev does the workaround help you, or do you still have an issue?

**Comment by klopyrev** [comment]
Well, it's still an issue. I'm not really using Tensorflow at the moment.

**Comment by flx42** [comment]
@alextp it's actually a bit more complicated, the image `gcr.io/tensorflow/tensorflow:latest-gpu` doesn't work because it's still version `0.8` (very old!). You should use the images on the DockerHub to get `0.9`, `0.10rc` or even nightly builds. I reported this issue here:
https://github.com/tensorflow/tensorflow/issues/3669

But recently, the `Dockerfile.gpu` was changed to inherit from the `devel` CUDA image instead of the `runtime` image, so the symlink workaround is not needed because the symlink already exists.
https://github.com/tensorflow/tensorflow/pull/2527
But this is not ideal since it's pulling extra dependencies in the `gpu` Docker image.

**Comment by asimshankar** [comment]
This seems to have been fixed in more recent docker images, sorry we didn't respond on this issue thread earlier.

For example:
```sh
nvidia-docker run -it gcr.io/tensorflow/tensorflow:latest-gpu python -c "import tensorflow; print tensorflow.__version__"
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
0.11.0rc0
```

So I'm going to close this issue for now. Please feel free to reopen or file a new one if there is any contention on this being fixed :)
