### ISSUE TITLE
Feature Request: tf.data.Dataset.truncated_batch()

### ISSUE THREAD

**Issue by rongou** [tensorflow/tensorflow#20391]
The `Dataset` api currently provides a `padded_batch` transformation, but for dense sequential data (audio, video) it might be better to drop a few frames to make the batched examples even. Can we have a new function to `Dataset` like this?
```python
truncated_batch(
    batch_size,
    truncating_shapes
)
```

The semantic would be very similar to `padded_batch` but in reverse. The `truncating_shapes` argument determines the resulting shape for each dimension of each component in an output element:
* If the dimension is a constant (e.g. `tf.Dimension(37)`), the component will be truncated to that length in that dimension.
* If the dimension is unknown (e.g. `tf.Dimension(None)`), the component will be truncated to the minimum length of all elements in that dimension.

Thoughts? @mrry

**Comment by rongou** [comment]
Cool, that'll be great. Is there a tracking issue for that work?

**Comment by jsimsa** [comment]
Hello @rongou, the initial implementation of the API alluded to by @mrry has been merged to master (https://github.com/tensorflow/tensorflow/commit/a6471888cc9dfe9c18d121149bc0516a3f423fbb). It contains implementations for batching and padded batching of both dense and sparse tensors which can serve as an example of how to write custom batching transformation (such as your "truncated" batch).
