### ISSUE TITLE
building pip package issue

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#2040]
```
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
2016年 04月 21日 星期四 07:34:12 CST : === Using tmpdir: /tmp/tmp.cMsLMGw3bz
cp: cannot stat ‘bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/tensorflow’: No such file or directory
cp: cannot stat ‘bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/external’: No such file or directory
```

**Comment by caisq** [comment]
Did you following the steps listed here? https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#create-the-pip-package-and-install

**Comment by sloscal1** [comment]
I ran into this problem today using the master branch of bazel, but after rebuilding bazel from the 0.2.0 tag everything went smoothly in the tensorflow build.

**Comment by vrv** [comment]
We are unable to reproduce this -- can you send us instructions about how to reproduce this from a fresh build / source tree?  We'll reopen if this is still a problem.

**Comment by ZhuFengdaaa** [comment]
It maybe caused by directory: the master branch make a `__main__` folder under the `bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles`, thus many files cannot be found.

**Comment by akors** [comment]
Hi! I have this issue to.

I am using Ubuntu 16.04, with Python 3.5.1, TensorFlow master (currently at  4a4f2461533847dde239851ecebe5056088a828c) and Bazel master (`Build label: 0.2.2b-2016-05-09 (@7222943)`).

Here are my steps to reproduce:
1. Install gcc-4.9 and g++-4.9
2. export CXX=/usr/bin/g++-4.9 and export CC=/usr/bin/gcc-4.9
3. Change to bazel directory, run ./compile
4. Copy  bazel/output/bazel to ~/.bazel/bazel, symlink ~/bin/bazel -> ~/.bazel/bazel
5. Add `cxx_flag: "-D_FORCE_INLINES"` to tensorflow/third_party/gpus/crosstool/CROSSTOOL at line 52
6. Run `bazel build -c opt --config=cuda --genrule_strategy=standalone --local_resources 4096,4.0,1.0 -j 4 //tensorflow/cc:tutorials_example_trainer`
7. Run `bazel build -c opt --config=cuda --genrule_strategy=standalone --local_resources 4096,4.0,1.0 -j 4 //tensorflow/tools/pip_package:build_pip_package`
8. Observe that the `__main__` directory contains directories that should probably be somewhere else.

Running `cp -r bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/__main__/* bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/`
works around this issue. (Thanks to @ZhuFengdaaa for this!)

Please don't hesitate to ask for more information.

**Comment by ZhuFengdaaa** [comment]
Actually I use `cp -r * ../`, the same.

**Comment by SpicyBroseph** [comment]
Same issue, compiling in CentOS 6.7 for our HPC cluster with latest master branch of both tensorflow and bazel, python 2.7.6, and using the devtoolset-2 install of gcc/g++ 4.8.2.

My steps are identical to kors, who has them two comments above mine (though I am not using the gpu build).  Same fix solves the issue.

@vrv I am also happy to provide more info.  My guess it's also due to bazel.

**Comment by vrv** [comment]
@damienmg @kchodorow will you help us move towards the new runfiles location before you decide to release the next version of bazel officially?

**Comment by kchodorow** [comment]
Happy to work with you on this.  TensorFlow probably needs to:

* Define a workspace name (`workspace(name = "org_tensorflow")` in the WORKSPACE file).
* Fix any scripts you have that reference runfiles to look for them under `x.runfiles/org_tensorflow` (or whatever you choose for a name), instead of `x.runfiles`. 

I'll take a look and see if I can reproduce/fix it myself.

**Comment by kchodorow** [comment]
Oh, yeah:

```
$ grep -r '\.runfiles' *
tensorflow/tools/pip_package/build_pip_package.sh:    bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/{tensorflow,external} \
tensorflow/tools/pip_package/build_pip_package.sh:    bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/google \
tensorflow/tools/pip_package/build_pip_package.sh:    bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/third_party/eigen3 \
tensorflow/stream_executor/dso_loader.cc:  rpaths->push_back("driver/driver_sh.runfiles/third_party/gpus/cuda/lib");
tensorflow/stream_executor/dso_loader.cc:  rpaths->push_back("driver/driver_sh.runfiles/third_party/gpus/cuda/lib64");
tensorflow/g3doc/get_started/os_setup.md:ln -s ../bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/* .
```

All of these just need to be changed to .runfiles/_some_name_.

**Comment by zplizzi** [comment]
I'm also having this issue. I'm on the current master branch of tensorflow (7d9ab3e), bazel 0.2.3, and gcc 5.3.1 on Ubuntu 16.04. My build steps were very similar to @akors. The fix mentioned above works. I'd be happy to provide more specific information if that's helpful.

**Comment by pszoldan** [comment]
Just did a fresh install on new ssd: Ubuntu 15.10, bazel 0.2.3.1463494873, tensorflow [60f6812](https://github.com/tensorflow/tensorflow/commit/60f68124494ef2aaff371e13e5f8b267b4043e6e), CUDA 7.5, cudnn v5, gcc 4.9. Same thing happens, same workaround works.

**Comment by damienmg** [comment]
/cc @kchodorow

What is the exact workaround you are applying?

The build_pip_package shell script seems incorrect because it tries to copy external

**Comment by zplizzi** [comment]
@damienmg 
I ran 

    cp -r bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/__main__/* bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/

to get it working.

**Comment by damienmg** [comment]
Oh yes makes sense. The corresponding PR is not yet merged. I guess @vrv will merge it soon, I think this bug should be reopen until then.

**Comment by kadrach** [comment]
Had a related (I presume) issue with current tensorflow@d42facc3 and bazel@c728a631, just adding this here for reference:
```
~/tensorflow$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Sat Jun 4 07:22:15 UTC 2016 : === Using tmpdir: /tmp/tmp.wBMcP4UriY
rsync: change_dir "/home/ubuntu/tensorflow//bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/external" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
```

Fixed by symlinking the path referenced in the error to `~/tensorflow/bazel-bin/external`.

**Comment by damienmg** [comment]
ping @kchodorow: @kadrach issue happens with latest Bazel. Maybe we should extends the coverage of what we test of Tensorflow on ci.bazel.io

**Comment by jiapei100** [comment]
I'm using bazel 0.2.3 as well, Ubuntu 16.04 + GCC 5.3.1, Cuda 7.5 + cudnn 5.0.5 .
I strictly followed https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#installation-for-linux, but run into the same error 
"$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Wed Jun 8 17:48:44 PDT 2016 : === Using tmpdir: /tmp/tmp.67PiK9GeAe
rsync: change_dir "/home/jiapei/Downloads/machinelearning/deeplearning/tensorflow//bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/external" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]"

I noticed that I do **NOT** have the subfolder **external**, but only a folder **tensorflow**. In addition, I do **NOT** have a folder **__main__** .

> .../pip_package/build_pip_package.runfiles$ ls 
> d3                             iron_collapse               iron_range_behavior        paper_dropdown_menu  paper_styles
> dagre                          iron_dropdown               iron_resizable_behavior    paper_header_panel   paper_tabs
> eigen_archive                  iron_fit_behavior           iron_selector              paper_icon_button    paper_toggle_button
> es6_promise                    iron_flex_layout            iron_validatable_behavior  paper_input          paper_toolbar
> font_roboto                    iron_form_element_behavior  lodash                     paper_item           plottable
> graphlib                       iron_icon                   MANIFEST                   paper_material       polymer
> __init__.py                    iron_icons                  neon_animation             paper_menu           promise_polyfill
> iron_a11y_announcer            iron_iconset_svg            org_tensorflow             paper_menu_button    protobuf
> iron_a11y_keys_behavior        iron_input                  paper_behaviors            paper_progress       six_archive
> iron_ajax                      iron_list                   paper_button               paper_radio_button   web_animations_js
> iron_autogrow_textarea         iron_menu_behavior          paper_checkbox             paper_radio_group    webcomponentsjs
> iron_behaviors                 iron_meta                   paper_dialog               paper_ripple
> iron_checked_element_behavior  iron_overlay_behavior       paper_dialog_behavior      paper_slider



Can anybody help please?

Cheers
Pei

**Comment by AnishShah** [comment]
I'm using Bazel 0.3 and facing this problem

**Comment by jellysquider** [comment]
I am using Bazel 0.4.0, python 2.7 and Mac 10.11.6. I have the same issue with running `bazel build -c opt  --local_resources 2048,.5,1.0 //tensorflow/tools/pip_package:build_pip_package`

> ERROR: no such package 'tensorflow/tools/pip_package': BUILD file not found on package path.

**Comment by sivi29y** [comment]
i had this problem when trying to run the command: 
     ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
outside of the tensorflow installation dir when back there it did work without any problem
