### ISSUE TITLE
power activation function

### ISSUE THREAD

**Issue by binxuan** [tensorflow/tensorflow#2041]
Hi, I am a newbie with Tensorflow. I just found there is no power activation function existing in Tensorflow? How can I implement a new activation function in TF?

**Comment by vrv** [comment]
https://www.tensorflow.org/versions/r0.8/api_docs/python/math_ops.html#pow ?  Comment if you think this isn't sufficient

**Comment by binxuan** [comment]
Ignore me. I have found the right solution. Tensor flow is fantastic. Thank you!
