### ISSUE TITLE
add sticky version flag to https://www.tensorflow.org/

### ISSUE THREAD

**Issue by jetojedno** [tensorflow/tensorflow#20456]
The https://www.tensorflow.org/ site would be greatly improved by a sticky flag (stored in a cookie in the browser) for the version you're using.  This would be used (as a default) for the landing page and search results.  People could choose to set it, or use have some such value as 'stable' for the latest stable release.

I waste a lot of time repeatedly navigating from 1.8 to the right version for the environment I'm working in.  When reading the docs, I prefer to read them for the right version of the API ...

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jetojedno** [comment]
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: 1.7
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce:  https://www.tensorflow.org/api_docs/python/ then search (e.g. tf.layers.dense).  The version I require (1.7) isn't on the first or second pages, so the quickest route is to click on the link for any of the prior versions (e.g. first is for v1.1) and edit the URL to change /1.1/ to /1.7/.

Nasty, and not recommended as a standard practice.

**Comment by lamberta** [comment]
Thanks for the feedback, but there are no plans to add this feature at this time.
However, you can bookmark an older version: https://www.tensorflow.org/versions/r1.7/api_docs/python/
And we are planning to add a /stable/ directory that points to the latest release.

**Comment by jetojedno** [comment]
If you could make search aware of and respect this base version, that would be very helpful.

**Comment by lamberta** [comment]
Good idea and will keep it in mind, thanks
