### ISSUE TITLE
C++ Code

### ISSUE THREAD

**Issue by EdwardVincentMa** [tensorflow/tensorflow#20463]
Hello, thank you very much for answer me !

This is the question:

There are 2 tensors, tensor A and tensor  B with same shape and data-type,  how can I put B into A with C++ code. I know in Python, I can use "append()" function. In C++, which function is same  with "append()"?

Python's code for example :
```
TrainImageDataArray = []
ImageData = mpl.image.imread(strImageInfoArray[i][0])
ImageData = ImageData.reshape(-1)
TrainImageDataArray.append(ImageData)
```
And how can I put "ImageData" into "TrainImageDataArray" in C++.

**Comment by JohnMiz** [comment]
Suppose you are using std::vector for that, you can do that:

`TrainImageDataArray.insert(TrainImageDataArray.end(), ImageData .begin(), ImageData .end());`
