### ISSUE TITLE
[Feature Request] Exponential Integral function Ei

### ISSUE THREAD

**Issue by robertmaxton42** [tensorflow/tensorflow#20462]
No form because it's not a bug. -- Well, I assume it isn't a bug. As it happens, while Tensorflow does implement the log-gamma and regularized incomplete gamma functions, as far as I know no combination of provided functions can be used to obtain the exponential integral function Ei (it's a 0/0 problem for the most part). As far as I know, my only recourse at this point is writing a custom op and gradient with SciPy's expi function. It'd be cool if that were addressed in the next version.

Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by robertmaxton42** [comment]
I suppose, Mr. Bot?

Have I written custom code - N/A
OS Platform and Distribution - N/A
TensorFlow installed from - 1.9
TensorFlow version - 1.9
Bazel version - 0.15
CUDA/cuDNN version - 9.0/7.1
GPU model and memory - N/A
Exact command to reproduce - N/A

**Comment by josh11b** [comment]
Approval for API reviewl

**Comment by reedwm** [comment]
Marking as contributions welcome if anyone wants to work on this

**Comment by GeorgyZhou** [comment]
I can work on this.

**Comment by robertmaxton42** [comment]
... It's a bit _late_, though I suppose the function was added "only" a year or two after the original request, but ... yes, as far as I can tell. I have thoroughly moved on from that project, however, so I'm just assuming it works the way it says.

**Comment by mohantym** [comment]
Thanks @robertmaxton42 for the confirmation. Closing this issue for now.

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
