### ISSUE TITLE
total_float_ops is 0 by tf.profiler.profile

### ISSUE THREAD

**Issue by ChiFang** [tensorflow/tensorflow#20469]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: None
- **GCC/Compiler version (if compiling from source)**: 5.4
- **CUDA/cuDNN version**: CUDA 9 / cuDNN 7
- **GPU model and memory**: GeForce GTX 1080Ti
- **Exact command to reproduce**:
```
import cv2
import time
import tensorflow as tf
from tensorflow.python.framework import graph_util

ModelFile = "OX_Predict_frozen.pb"

def load_pb(pb):
    with tf.gfile.GFile(pb, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(graph_def, name='')
        return graph
        
import math
M = math.pow( 10, 6 )
print(M)

def log_FLOP():
    # ***** (3) Load frozen graph *****
    g2 = load_pb(ModelFile)
    with g2.as_default():
        flops = tf.profiler.profile(g2, options = tf.profiler.ProfileOptionBuilder.float_operation())
        print('FLOP after freezing(M): ', flops.total_float_ops/ M)

def main():
    log_FLOP()

if __name__ == "__main__":
    main()
```

### Describe the problem
I'm trying to log the number of multiply-add operations (MAC) in my network by "tf.profiler.profile".

here is the [model](https://drive.google.com/file/d/12-7TI7EGLuN8JgcafGPJKeugp263gVYD/view?usp=sharing)(.pb)

the model work perfect when predict, but it always return 0 flops with "tf.profiler.profile"

any suggestion ?

### Source code / logs
the sample code to get .pb is following:
https://github.com/ChiFang/TensorFlow_XO_example

it takes only few sec~~~~

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by hari-dori** [comment]
I am also getting the same error , any update
