### ISSUE TITLE
InternalError (see above for traceback): CUB segmented reduce errorinvalid device function

### ISSUE THREAD

**Issue by l2yao** [tensorflow/tensorflow#20466]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: running training step from [here](https://github.com/lengstrom/fast-style-transfer)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 64 bit
- **TensorFlow installed from (source or binary)**: installed using conda
- **TensorFlow version (use command below)**: b'unknown' 1.8.0
- **Python version**: 3.6.2
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**:  CUDA 9.0 cuDNN 7.1.4
- **GPU model and memory**: name: GeForce GTX 650 Ti major: 3 minor: 0 memoryClockRate(GHz): 0.928
- **Exact command to reproduce**: python style.py --style examples\poem.jpg --checkpoint-dir checkpoint

### Describe the problem
Running a CNN training on fast style transfer, and using tensorflow-gpu. training crushed at moments/mean, is this a bug in tensorflow?

### Source code / logs

> Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: CUB segmented reduce errorinvalid device function
         [[Node: moments/mean = Mean[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Conv2D_16, moments/mean-1-LayoutOptimizer)]]

**Comment by karmel** [comment]
The linked code runs on TensorFlow 0.11.0, and you are using 1.8.0. I would not expect consistency over a major version change like that. I would suggest finding a more recent version of the CNN you want to run, or checking out an older version of TensorFlow. Thanks.
