### ISSUE TITLE
I want to build tensorflow-gpu 1.4.0

### ISSUE THREAD

**Issue by nagata-tensor** [tensorflow/tensorflow#20473]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04.4 LTS
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:tensorflow-gpu 1.4.0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**:0.5.4
- **GCC/Compiler version (if compiling from source)**:5.4.0
- **CUDA/cuDNN version**:8.0/6.0.21
- **GPU model and memory**:GeForce GTX 980 4GB
- **Exact command to reproduce**:

### Describe the problem

I am trying to install TensorFlow from Sources. I did it with reference to https://www.tensorflow.org/install/install_sources.But I accidentally built a CPU version.

I want to build tensorflow-gpu 1.4.0 from source. But I cannot find the GPU version of tensorflow.

Any suggestions would help. Thanks.

**Comment by karmel** [comment]
Hi @nagata-tensor -- please make sure you have the [NIVIDIA prerequisites](https://www.tensorflow.org/install/install_linux#NVIDIARequirements) installed on your system before installing from source. Then you can proceed with the [install from source instructions](https://www.tensorflow.org/install/install_sources).

**Comment by nagata-tensor** [comment]
Hi @karmel I have the NVIDIA prerequisites installed on my system. I could proceed with the install from source instructions.
