### ISSUE TITLE
Not found: Could not find session factory for DIRECT_SESSION

### ISSUE THREAD

**Issue by tiny-app** [tensorflow/tensorflow#2047]
Operating System:  Android

because my android system is below Android 5.0, so I rebuild the tensorflow librarys for android with NDK android-11.  the building is success.   

then,  with these librarys, I write a android demo.  But when I run, it output the message ...

      **Not found: Could not find session factory for DIRECT_SESSION**

I don't know, what's wrong with my works.

**Comment by andrewharp** [comment]
There are problems with Bazel and NDK 11 currently; it's suggested that you use NDK r10e until this is resolved. See #1468 for details and links to relevant r10e downloads.

If the problem persists after trying r10e please let me know the bazel version and command you're using to build.

**Comment by tiny-app** [comment]
@andrewharp 

thanks for your replay.

"Not found: Could not find session factory for DIRECT_SESSION"

my ndk is always the NDK r10e, and i rebuild it,  the build is ok, but the problem still persists.

> libandroid_tensorflow_lib.a
> libprotobuf.a
> libprotobuf_lite.a
> libprotos_all_cc.a
> libre2.a

I extract these static librarys, and write my jni code, just like 'android:tensorflow_demo'.

	tensorflow::SessionOptions options;
	tensorflow::ConfigProto& config = options.config;
	LOG(INFO) << "Got config, " << config.device_count_size() << " devices";
	tensorflow::Session* tempSession = tensorflow::NewSession(options);

here, config.device_count_size() is 0,  and tempSession is nullptr, internal it print

        "Not found: Could not find session factory for DIRECT_SESSION"

the device count is importance, but it's zero.

------------------------------------------------------------------------------------------------------
android-ndk-r10e-linux-x86_64.bin
bazel-0.2.1-installer-linux-x86_64.sh

git clone --recurse-submodules https://github.com/tensorflow/tensorflow -b r0.7

android_sdk_repository(
    name = "androidsdk",
    api_level = 23,
    build_tools_version = "23.0.1",
    path = "/home/gzzhang/android-sdk",
)

android_ndk_repository(
    name="androidndk",
    path="/opt/android-ndk",
    api_level=11,                                        <<==  this is diff, i want to down the api_level.
)

bazel build //tensorflow/examples/android:tensorflow_demo --verbose_failures

Target //tensorflow/examples/android:tensorflow_demo up-to-date:
  bazel-bin/tensorflow/examples/android/tensorflow_demo_deploy.jar
  bazel-bin/tensorflow/examples/android/tensorflow_demo_unsigned.apk
  bazel-bin/tensorflow/examples/android/tensorflow_demo.apk
INFO: Elapsed time: 2363.175s, Critical Path: 2126.57s

**Comment by andrewharp** [comment]
I just tried with api_level=11, but was unable to reproduce the issue.

If you update tensorflow/examples/android:libtensorflow_demo.so to have the following linkopts:
```
    linkopts = [
        "-landroid",
        "-ljnigraphics",
        "-llog",
        "-lm",
        "-z defs",
    ],
```

And then run:
```
bazel build //tensorflow/examples/android:tensorflow_demo --verbose_failures
unzip bazel-bin/tensorflow/examples/android/tensorflow_demo.apk -d apk
nm --radix=d --print-size -C --size-sort apk/lib/armeabi-v7a/libtensorflow_demo.so  | grep DirectSession
```
Do you see anything?

As a potential workaround, you can try adding alwayslink=1 to tensorflow/core:android_tensorflow_lib and see if that does anything.

How are you installing it on your device?

**Comment by tiny-app** [comment]
@andrewharp 

"Not found: Could not find session factory for DIRECT_SESSION"

It seems that the DirectSessionFactory is not been regist.

So I browse the codes, and in the end of direct_session.cc, i find:

//////////
class DirectSessionFactory : public SessionFactory {
 public:
  DirectSessionFactory() {}

  Session* NewSession(const SessionOptions& options) override {
    std::vector<Device*> devices;
    DeviceFactory::AddDevices(options, "/job:localhost/replica:0/task:0",
                              &devices);
    return new DirectSession(options, new DeviceMgr(devices));
  }
};

class DirectSessionRegistrar {
 public:
  DirectSessionRegistrar() {
    SessionFactory::Register("DIRECT_SESSION", new DirectSessionFactory());
  }
};
static DirectSessionRegistrar registrar;
//////////

today, i rebuild it with ndk api_level=9 and api_level=21

libandroid_tensorflow_lib.a
direct_session.o

nm libandroid_tensorflow_lib.a | grep DirectSessionFactory    OK
nm libandroid_tensorflow_lib.a | grep DirectSessionRegistrar  Found Nothing
nm libandroid_tensorflow_lib.a | grep registrar  Found Nothing

direct_session.o is same.  api_level=9 and api_level=21 is some.

so, you know, DIRECT_SESSION is not registed.

and then, "Not found: Could not find session factory for DIRECT_SESSION"

================================================

It really occur.  very very strange.

**Comment by tiny-app** [comment]
@andrewharp

It my fault, now it's ok.

I develop under Windows, and I use Android.mk to build.

I must use LOCAL_WHOLE_STATIC_LIBRARIES instead of LOCAL_STATIC_LIBRARIES to link these libraries. And it also depend on android-ndk-r10e, just like bazel build.

LOCAL_WHOLE_STATIC_LIBRARIES := \
                                android_tensorflow_lib \
                                protobuf re2 \
                                protobuf_lite \
                                protos_all_cc

Now I can develop APP under Windows with Eclipse and Android.mk.

thanks.
