### ISSUE TITLE
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):

### ISSUE THREAD

**Issue by nagata-tensor** [tensorflow/tensorflow#20471]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04.4 LTS
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.4.0
- **Python version**: Python 2.7.12
- **Bazel version (if compiling from source)**:0.5.4
- **GCC/Compiler version (if compiling from source)**:5.4.0
- **CUDA/cuDNN version**:8.0/6.0.21
- **GPU model and memory**:GeForce GTX 980 4GB
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
I am trying to install  TensorFlow from Sources. I did it with reference to https://www.tensorflow.org/install/install_sources.

To build a pip package for TensorFlow with GPU support, I invoke the following command:

bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

But getting following error.(My log is shown at the bottom)

Any suggestions would help. Thanks.

### Source code / logs
root@nakadake:/mnt/fs4/nagata/tensorflow-1.4.0# ./configure 
WARNING: Running Bazel server needs to be killed, because the startup options are different.
You have bazel 0.5.4 installed.
Traceback (most recent call last):
  File "configure.py", line 1039, in <module>
    main()
  File "configure.py", line 973, in main
    reset_tf_configure_bazelrc()
  File "configure.py", line 249, in reset_tf_configure_bazelrc
    open(_TF_BAZELRC, 'w').close()
IOError: [Errno 13] Permission denied: '/mnt/fs4/nagata/tensorflow-1.4.0/.tf_configure.bazelrc'

**Comment by xingjinglu** [comment]
@nagata-tensor have you resolved the problem?
