### ISSUE TITLE
Input to reshape is a tensor with 4889 values, but the requested shape has 4800

### ISSUE THREAD

**Issue by neverPick** [tensorflow/tensorflow#2048]
Operating System:Ubuntu 14.04
1.I fixed my images to 200*200 .jpg,and stored into TFRecord file
2.I read TFR file and try to train in cifar10 model,it raised error:
Input to reshape is a tensor with 4889 values, but the requested shape has 4800
on :`depth_major = tf.reshape(image,[result.depth, result.height, result.width])`
It seems cause of diffrent of images' buffer size?
Should I  fix the sizes before put into TFR file?

**Comment by sherrym** [comment]
@neverPick, the size of the "image" needs to be the same as what you are reshaping it to.

**Comment by vrv** [comment]
(in other words, "reshape" is not "resize".  There are operations for resizing available in TensorFlow though.)

**Comment by AshviniVJain** [comment]
How did you solve the issue? Iam facing the same issue and not able to find what and where to make a correction.

**Comment by freedom9393** [comment]
In my case, `an image size` and my `model's input shape` were different. Please check your image size again and again. Cuz, I've spent pretty long time on fixing this problem
