### ISSUE TITLE
Trouble replicating results using capi

### ISSUE THREAD

**Issue by nickblock** [tensorflow/tensorflow#20482]
I have written minimal code in both python and using the capi. This code loads a premade graph and runs a test image through it. I cannot seem to get the same results using the capi as I get running through python.
Linux Ubuntu 16.04
I have both installed tf and built the library using bazel.
I haqve tried various versions but for this experiment am fixing on 1.9.
Python 3.5.2
bazel 0.13.0
gcc 5.4
no cuda

I am trying to run the graph "ssd_mobilenet_v1_android_export.pb" given with the android mobile examples.

I am using this test image https://github.com/pjreddie/darknet/raw/master/data/dog.jpg

I have simple python code (code below), that loads the graph, feeds the image to it and reads back various tensors. This graph has an op at the end called "num_detections", I am reading the tensor at this point to check for success.
With the dog.jpg I get a "3.0" result. Other test images give appropriate results. 

I am repeating this experiment with the capi (code below), but the only result I ever get is zero. 
The first obvious place I looked is my image input. The second graph op is a "ToFloat" operation. I have been using that to check the values of the pixel data going into the feed. They are identical. I checked the image is not flipped and the color channels are in the same order after decoding. I then started looking further up the graph, sampling values of the tensors at each op. I find they are mostly the same until they get to a long list of convolution ops where it seems the values slowly diverge - like they are the same the first couple of ops then start to show differences getting further and further apart.

Not working capi code:

````

#include <png.hpp>
#include <stdlib.h>
#include <stdio.h>
#include <tensorflow/c/c_api.h>

typedef unsigned char byte; 

const int num_channels = 3;

struct Image {
  byte* data;
  int width, height;
  int dataSize() {
    return width * height * num_channels;
  }
};

Image open_image(const char* filename) {

  Image image;
  int dataSize = image.width * image.height * num_channels;

  png::image< png::rgb_pixel > png_import(filename);
  image.width = png_import.get_width();
  image.height = png_import.get_height();
  image.data = (byte*)malloc(image.dataSize());
  for(int y=0; y<image.height; y++) {
    for(int x=0; x<image.width; x++) {
      png::rgb_pixel pixel = png_import.get_pixel(x,y);
      byte* data = &image.data[(y*image.width+x)*num_channels];
      *data++ = pixel.red;
      *data++ = pixel.green;
      *data++ = pixel.blue;
    }
  }

  printf("%s loaded, %dx%d\n", filename, image.width, image.height);
  return image;
}

TF_Graph* open_graph(const char* filename, TF_Status* status) {

  TF_Graph* graph = TF_NewGraph();

  TF_ImportGraphDefOptions* opts = TF_NewImportGraphDefOptions();

  FILE* fp = fopen(filename, "r");

  fseek(fp, 0L, SEEK_END);
  int file_size = ftell(fp);
  rewind(fp);

  char* graph_content = (char*)malloc(file_size);

  fread(graph_content, file_size, 1, fp);
  fclose(fp);

  TF_Buffer tfBuffer;
  tfBuffer.data = graph_content;
  tfBuffer.length = file_size;
  
  TF_GraphImportGraphDef(graph, &tfBuffer, opts, status);

  free(graph_content);

  if(TF_GetCode(status) != TF_OK) {

    printf("%s\n", TF_Message(status));
    return 0;
  }

  printf("Successfully loaded graph\n");

  return graph;
}
void TensorDeallocator(void* data, size_t len, void* arg)
{

}


int main(int argi, char** argc) {

  printf("TensorFlow C library version %s\n", TF_Version());

  TF_Status* status = TF_NewStatus();
  TF_Graph* graph = open_graph(argc[1], status);

  Image image = open_image(argc[2]);

  int64_t dims[] = {1, image.width, image.height, num_channels};
  
  TF_Tensor* image_tensor = TF_NewTensor(
    TF_UINT8, dims, 4, 
    image.data, image.dataSize(), 
    TensorDeallocator, 0
  );

  TF_Operation* input_image_op = TF_GraphOperationByName(graph, "image_tensor");
  if(!input_image_op) {
    printf("Failed to find Op '%s'", "image_tensor");
    return 1;
  }

  TF_Output image_input;
  image_input.oper = input_image_op;
  image_input.index = 0;
  TF_Output inputs[1] = {image_input};

  TF_Operation* num_detection_op = TF_GraphOperationByName(graph, "num_detections");
  if(!num_detection_op) {
    printf("Failed to find Op '%s'", "num_detections");
    return 1;
  }
  TF_Output num_detection_output;
  num_detection_output.oper = num_detection_op;
  num_detection_output.index = 0;

  TF_Output outputs[1] = {num_detection_output};
  TF_Tensor* output_tensors[1];

  TF_SessionOptions * options = TF_NewSessionOptions();
  TF_Session* session = TF_NewSession( graph, options, status );

  TF_SessionRun(session, 0, 
                &image_input, &image_tensor, 1,
                outputs, output_tensors, 1,
                0, 0,
                0, status
                );

  if(TF_GetCode(status) != TF_OK) {

    printf("%s\n", TF_Message(status));
  }
  else {
      
    printf("Ran successfully\n");

    float* f = (float*)TF_TensorData(output_tensors[0]);

    printf("TF data %f\n", f[0]);

  }
  
  free(image.data);

  return 0;
}


```


Working python code:


```
import data_helpers
import sys
import tensorflow as tf
import numpy as np


from tensorflow.python.platform import gfile
from tensorflow.python.util import compat
from tensorflow.core.protobuf import saved_model_pb2

def read_graph(model_filename):

    with gfile.FastGFile(model_filename, 'rb') as f:

        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        g_in = tf.import_graph_def(graph_def)

        return g_in


def printOps():

    for op in tf.get_default_graph().get_operations():

        print(op.name)

if __name__ == "__main__":
    
    if len(sys.argv) < 3:
        print("Usage: run_image_on_graph.py [input graph filepath] [output image filepath]")
        exit(1)

    graph_file = sys.argv[1]
    image_file = sys.argv[2]

    image = data_helpers.import_image(image_file)

    with tf.Session() as sess:

        read_graph(graph_file)

        graph = tf.get_default_graph()

        image_tensor = graph.get_tensor_by_name("import/image_tensor:0")
        num_detections = graph.get_tensor_by_name("import/num_detections:0")
        detection_scores = graph.get_tensor_by_name("import/detection_scores:0")
        detection_boxes = graph.get_tensor_by_name("import/detection_boxes:0")
        debug = graph.get_tensor_by_name("import/ToFloat:0")

        image = np.array([data_helpers.import_image(image_file)])

        print("sess = " + str(sess.run([num_detections], feed_dict={
            image_tensor: image})
        ))
      
```
   

Is there anything obviously wrong with my approach?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by nickblock** [comment]
System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes, shown
OS Platform and Distribution: Ubuntu 16.04.4 LTS
TensorFlow installed from (source or binary):source
TensorFlow version (use command below):1.9
Python version: 3.5.2
Bazel version (if compiling from source):0.13.0
GCC/Compiler version (if compiling from source):5.4.0
CUDA/cuDNN version:N/A
GPU model and memory:N/A
Exact command to reproduce: 

tf_test ssd_mobilenet_v1_android_export.pb dog.png

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by nickblock** [comment]
Hi, thanks for taking a look. It might be a bug. I'm just asking whether you are of the opinion that running the same graph with the same data should produce identical results between python and the capi. And if that is true is there something about the code above that is the reason that is not happening?.
