### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [tensorflow/tensorflow#205]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [TensorSliceReaderCacheWrapper](https://github.com/tensorflow/tensorflow/blob/d6357a5849db980df51d00d8a9ff874cda2faeb3/tensorflow/core/util/tensor_slice_reader_cache.cc#L11 "Destructor for TensorSliceReaderCacheWrapper")
* [Uncompress](https://github.com/tensorflow/tensorflow/blob/d6357a5849db980df51d00d8a9ff874cda2faeb3/tensorflow/core/lib/jpeg/jpeg_mem.cc#L323 "Uncompress function")

**Comment by girving** [comment]
Thanks for noticing!  Will fix.

**Comment by girving** [comment]
Fixed the `TensorSliceReaderCache` one.  The other one is necessary; the code is

    if (!result) delete[] buffer;

`delete[]` is not smart enough to not delete `buffer` if the distinct variable `result` happens to be nonnull.

**Comment by elfring** [comment]
Further update candidates:
- [EdgeSetTest::MakeEdgeSet()](https://github.com/tensorflow/tensorflow/blob/0f8f062e89f1b915d953c3c5eda57ef77d5fbd93/tensorflow/core/graph/edgeset_test.cc#L29 "EdgeSetTest::MakeEdgeSet function")
- [LocalShapedBufferTuple](https://github.com/tensorflow/tensorflow/blob/39587aaeb7760c6c963d8668bd6f614360e914f8/tensorflow/compiler/xla/python/local_computation_builder.cc#L145 "Destructor for LocalShapedBufferTuple")
