### ISSUE TITLE
No OpKernel was registered to support Op 'QuantizedReluX' with these attrs

### ISSUE THREAD

**Issue by cs-tf** [tensorflow/tensorflow#20514]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary using conda
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: 3.5.2
- **CUDA/cuDNN version**: 8.0/7.0
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **GPU model and memory**: Quadro M2000M/ 4GB
- **Exact command to reproduce**:
Tried to use quantized_relu_x and it doesn't work
I have already used quantized_conv2d and quantized_max_pool, both of them works fine, but have only problem when I use quantized_relu_x

### Describe the problem
Other two quantized kernels QuantizedRelu and QuantizedRelu6 seem to have defined but QuantizedReluX appears to be missing, although three of them are registered together in core/ops/nn_ops.cc file

### Source code / logs
Error message that I am getting is as follows:
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'QuantizedReluX' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  >no registered kernels

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version

**Comment by cs-tf** [comment]
I have already added it 3 days ago.. Please try to have a look at it

**Comment by yongtang** [comment]
Added a PR #20700 for QuantizedReluX kernel.
