### ISSUE TITLE
libpthread.so was not created => can't build Android example

### ISSUE THREAD

**Issue by codingyourlife** [tensorflow/tensorflow#2055]
I don't know if it is a tensorflow bug, a bazel bug or a misconfiguration on my side (maybe with SDK/NDK) but could you guys just have a short look at my stackoverflow issue: http://stackoverflow.com/q/36731061/828184

Here the errors (also can be seen on stackoverflow):
> ERROR: /home/administrator/TensorFlow_Git/tensorflow/examples/android/BUILD:41:1: output 'tensorflow/examples/android/libpthread.so' was not created.
> 
> ERROR: /home/administrator/TensorFlow_Git/tensorflow/examples/android/BUILD:41:1: not all outputs were created.

Sorry for cross-posting but I waited a while, would really need this and don't even know if stackoverflow is the right address at this point.

**Comment by andrewharp** [comment]
What bazel version do you have installed, and what command line are you using to build?

libpthread is actually not needed on Android, and the demo only depends on it to make the protobuf dependency happy at link time. Once Tensorflow upgrades to the newer version of protobuf, this hack will no longer be necessary. As a temporary workaround you can you try removing "-lpthread" from LINK_OPTS in google/protobuf/BUILD, and similarly removing all references to it from tensorflow/examples/android/BUILD.

It's possible you might have a more systematic installation issue, though, and this is just the first error the build process encounters.

**Comment by codingyourlife** [comment]
I digged around in the Pull Requests and noticed that there is some moving around and wanting it gone :-)

GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
bazel version 0.2.1

Changed it to `LINK_OPTS = []` and same result

**Comment by andrewharp** [comment]
Did you also delete the references from tensorflow/examples/android/BUILD?

**Comment by codingyourlife** [comment]
I tried but got an error. Did it again to write down the error but it doesn't say much:
/home/administrator/TensorFlow/tensorflow/tensorflow/examples/android/BUILD:12:1: output 'tensorflow/examples/android/libtensorflow_demo.so' was not created.

tensorflow/examples/android/BUILD file:
```
# Description:
#   Tensorflow camera demo app for Android.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

load("//tensorflow:tensorflow.bzl", "tf_copts")

exports_files(["LICENSE"])

cc_binary(
    name = "libtensorflow_demo.so",
    srcs = glob([
        "jni/**/*.cc",
        "jni/**/*.h",
    ]),# + [":libpthread.so"],
    copts = tf_copts(),
    linkopts = [
        "-landroid",
        "-ljnigraphics",
        "-llog",
        "-lm",
        "-z defs",
        "-s",
        "-Wl,--icf=all",  # Identical Code Folding
        "-Wl,--exclude-libs,ALL",  # Exclude syms in all libs from auto export
    ],
    linkshared = 1,
    linkstatic = 1,
    tags = [
        "manual",
        "notap",
    ],
    deps = ["//tensorflow/core:android_tensorflow_lib"],
)

# This library only exists as a workaround to satisfy dependencies
# that declare -lpthread in their linkopts. Although Android supports
# pthreads, it does not provide it as a separate library.
#cc_binary(
#    name = "libpthread.so",
#    srcs = [],
#    linkopts = ["-shared"],
#    tags = [
#        "manual",
#        "notap",
#    ],
#)

cc_library(
    name = "tensorflow_native_libs",
    srcs = [
        #":libpthread.so",
        ":libtensorflow_demo.so",
    ],
    tags = [
        "manual",
        "notap",
    ],
)

android_binary(
    name = "tensorflow_demo",
    srcs = glob([
        "src/**/*.java",
    ]),
    assets = glob(["assets/**"]),
    assets_dir = "assets",
    custom_package = "org.tensorflow.demo",
    inline_constants = 1,
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
    tags = [
        "manual",
        "notap",
    ],
    deps = [
        ":tensorflow_native_libs",
    ],
)

filegroup(
    name = "all_files",
    srcs = glob(
        ["**/*"],
        exclude = [
            "**/METADATA",
            "**/OWNERS",
            "bin/**",
            "gen/**",
        ],
    ),
    visibility = ["//tensorflow:__subpackages__"],
)

filegroup(
    name = "java_files",
    srcs = glob(["src/**/*.java"]),
)

filegroup(
    name = "jni_files",
    srcs = glob([
        "jni/**/*.cc",
        "jni/**/*.h",
    ]),
)

filegroup(
    name = "resource_files",
    srcs = glob(["res/**"]),
)

exports_files(["AndroidManifest.xml"])
```

**Comment by andrewharp** [comment]
That looks like it should work. What command are you using to build?

**Comment by codingyourlife** [comment]
`bazel build //tensorflow/examples/android:tensorflow_demo`

**Comment by andrewharp** [comment]
Strange, are you sure there are no error messages before that? If you run `bazel clean` and then build with `bazel build -s //tensorflow/examples/android:tensorflow_demo`, do you see anything that stands out?

**Comment by andrewharp** [comment]
You could also try building with `--verbose_failures` to see if it outputs any additional error messages.

**Comment by codingyourlife** [comment]
I watched it now compiling and didn't see any error. I wanted to be sure and write the output to a file but I'm not a linux expert and this doesn't seem to work:
` sudo bazel build -s //tensorflow/examples/android:tensorflow_demo --verbose_failures > output.txt`

**Comment by andrewharp** [comment]
You can try `bazel build -s //tensorflow/examples/android:tensorflow_demo --verbose_failures 2>&1 output.txt` which will redirect all output to the file.

You shouldn't need to use sudo for building if your Bazel is installed properly -- have you been using it the entire time?

**Comment by codingyourlife** [comment]
I now did again from scratch. I mean I git pulled freshly, edited WORKSPACE file, added the submodule and said submodule  update, changed BUILD file so no libpthread.so files are present (as above), made the LINK_OPTS an empty array in the protobuf BUILD file, made whole tensorflow folder chmod 777, and executed it with your last written command without sudo. I still ran into this issue. Attached my output.txt.
[output.txt](https://github.com/tensorflow/tensorflow/files/232888/output.txt)

**Comment by andrewharp** [comment]
It looks like the libpthread.so issue was only a symptom of a more general issue as your build environment can't find libtensorflow_demo.so either.

If you look in your bazel-* dirs for libtensorflow_demo.so, what do you find?

For reference, this is what I see:

```
$ find bazel-*/ | grep libtensorflow_demo.so$
bazel-bin/tensorflow/examples/android/_dx/tensorflow_demo/native_symlinks/armeabi-v7a/libtensorflow_demo.so
bazel-out/local_linux-opt/bin/tensorflow/examples/android/_dx/tensorflow_demo/native_symlinks/armeabi-v7a/libtensorflow_demo.so
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/tensorflow/examples/android/libtensorflow_demo.so
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/_solib_armeabi-v7a/_U_S_Stensorflow_Sexamples_Sandroid_Ctensorflow_Unative_Ulibs___Utensorflow_Sexamples_Sandroid/libtensorflow_demo.so
bazel-tensorflow/bazel-out/local_linux-opt/bin/tensorflow/examples/android/_dx/tensorflow_demo/native_symlinks/armeabi-v7a/libtensorflow_demo.so
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/tensorflow/examples/android/libtensorflow_demo.so
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/_solib_armeabi-v7a/_U_S_Stensorflow_Sexamples_Sandroid_Ctensorflow_Unative_Ulibs___Utensorflow_Sexamples_Sandroid/libtensorflow_demo.so

```

**Comment by codingyourlife** [comment]
`bazel-bin/tensorflow/examples/android/_dx/tensorflow_demo/native_symlinks/armeabi-v7a/libtensorflow_demo.so
bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/_dx/tensorflow_demo/native_symlinks/armeabi-v7a/libtensorflow_demo.so
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/imageutils_jni.d
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/imageutils_jni.o
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/tensorflow_jni.d
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/yuv2rgb.o
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/tensorflow_jni.o
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/rgb2yuv.d
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/jni_utils.o
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/jni_utils.d
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/rgb2yuv.o
bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/yuv2rgb.d
bazel-tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/examples/android/_dx/tensorflow_demo/native_symlinks/armeabi-v7a/libtensorflow_demo.so
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/imageutils_jni.d
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/imageutils_jni.o
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/tensorflow_jni.d
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/yuv2rgb.o
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/tensorflow_jni.o
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/rgb2yuv.d
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/jni_utils.o
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/jni_utils.d
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/rgb2yuv.o
bazel-tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/yuv2rgb.d`

I also noticed that if I type which bazel it gives me, don't know if that's normal
![whichbazel](https://cloud.githubusercontent.com/assets/10122382/14871069/414885a4-0cdf-11e6-908a-1e37c38dc265.JPG)

**Comment by andrewharp** [comment]
Odd, obviously it's creating the files, it's just not finding them for some reason. Can you check for permission issues, e.g.:
`find bazel-*/ | grep libtensorflow_demo.so$ | xargs ls -la` ?

The only command you should run with sudo is the one to install bazel, that should put it in /usr/bin. e.g. `sudo ./bazel-0.2.1-installer-linux-x86_64.sh`. I'd try installing it that way and see if it gets you anywhere.

**Comment by codingyourlife** [comment]
[permission.txt](https://github.com/tensorflow/tensorflow/files/239554/permission.txt)

**Comment by andrewharp** [comment]
What about `ls -la ~/.cache/bazel/_bazel_administrator` or `ls -la /home/administrator/.cache/bazel/_bazel_administrator/d80406fadc9e2685aed9bed686923250/tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/libtensorflow_demo.so` ?

**Comment by codingyourlife** [comment]
It's not in `/home/administrator/.cache/bazel/_bazel_administrator/d80406fadc9e2685aed9bed686923250/tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/libtensorflow_demo.so`

![res](https://cloud.githubusercontent.com/assets/10122382/14871691/0cb15c2a-0ce5-11e6-8acc-ccbf86280d7a.JPG)

But I have something new now. I uninstalled bazel with `rm -fr ~/.bazel ~/.bazelrc ~/.cache/bazel` copied the `bazel-0.2.1-installer-linux-x86_64.sh` file to the tensorflow directory and executed it with sudo. Am I now a step further or back? ^^

**Comment by codingyourlife** [comment]
Update: I did chmod 777 on the whole tensorflow directory and I am now step 613 but OS seems to be frozen now

**Comment by codingyourlife** [comment]
Same error on step 671

**Comment by codingyourlife** [comment]
Ok the problem with the EOF seems to be because of too less memory and gets fixed with --jobs 4 parameter but I then run into a c++ error. Anyway all that looks like topics for another thread in case I can't find existing ones.

What seemed to have helped now was executing `-fr ~/.bazel ~/.bazelrc ~/.cache/bazel` and calling `bazel-0.2.1-installer-linux-x86_64.sh` INSIDE the tensorflow directory.

Thanks for your help.

**Comment by codingyourlife** [comment]
Okay sorry but after increasing my swap partition with gparted to fix another error and running the command with --jobs 4 I get this `libtensorflow_demo.so` was not created error again.

Logs: [output1.txt](https://github.com/tensorflow/tensorflow/files/243192/output1.txt)

**Comment by andrewharp** [comment]
You really should not be running bazel build with sudo. If you have to do that something is broken with your install. What happens when you run without the sudo?

The only time bazel and sudo should mix is when you're running the installer, so that it can install itself in /usr/bin

**Comment by codingyourlife** [comment]
Tried it without too. Or is the output "dirty" than?

**Comment by andrewharp** [comment]
Can you search for the libtensorflow_demo.so file using the find command referenced earlier, and follow the links to check all the permissions? Earlier you said that it wasn't there, does that mean that the symlink existed but pointed to a non-existent file?

Also, you've attached output1.txt but your command should have written to output2.txt. Are the output logs the same?

**Comment by codingyourlife** [comment]
Yesterday I've spent the whole day trying out different tensorflow github releases and bazel releases and combinations of those and I kept running into this libpthread.so error. If I remove dependency to libpthread.so (seems this dependency was in the BUILD file before it wen't into the WORKSPACE file) it's usally a C++ compilation of rule error that gets fixed with --jobs 2 (sometimes 4 work but 2 allways works) but then it stops at this libtensorflow_demo.so not created error.
I searched for all libtensorflow_demo.so files on the drive and made them chmod 777  and also the whole tensorflow folder and .cache/bazel folder and it just doesn't work.

You are right that I wrote ouput1.txt and ouput2.txt but just because I edited the post afterwards to add the command but it wasn't the original command but a few tries later. The output1.txt is/was correct and error also came without writing to file.

Because I now tried many different versions I suspect the NDK or SDK to be honest. The ndk doesn't work with r11c (because it doesn't find a README file) and I somewhere got the android-ndk-r10e and placed it in my Downloads folder. Not sure if it matters where its located. Also installed it via SDK manager but that doesn't tell me where its located. The SDK is installed normally via SDK Manager but I added the 23.0.1 folder manually which I also found somewhere on the internet. Also tried the 23.03 with same result a few times (and just now).

Any more ideas? I would even create a new VM with OS, bazel, tensorflow, Android SDK and NDK versions of your choice etc. if you think that helps. The error isn't really that useful, that's the problem.

Again current command:
`bazel build //tensorflow/examples/android:tensorflow_demo --verbose_failures --jobs 2 >output.txt 2>&1`

Current output (used bazel clean before): [output.txt](https://github.com/tensorflow/tensorflow/files/244363/output.txt)

But I currently tried it with the older TensorFlow v0.7.1, bazel v0.2.0 on Ubuntu 14.04 LTS

**Comment by andrewharp** [comment]
A few notes first:
- libpthread.so itself is not the problem, just a symptom here, as it seems you have a general issue with your bazel install
- There's currently a Bazel/NDK 11 incompatibility, so you should be using r10e
- Bazel 0.2.0 or 0.2.1 should work, and "which bazel" should tell you /usr/bin/bazel after install

You said before that:
`/home/administrator/.cache/bazel/_bazel_administrator/d80406fadc9e2685aed9bed686923250/tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/examples/android/libtensorflow_demo.so`
"wasn't there". So that means the link exists (since you provided the "find" output that showed it), but the target of the link doesn't? Can you check your current set of links produced by bazel in the [workspace]/bazel-* folder, and see if they point to nothing as well?

How much free disk space/memory do you have?

**Comment by codingyourlife** [comment]
FINALLY I GOT IT! I have no idea what and where something went wrong but you are right and there were broken link files pointing to a non existing directory with libtensorflow_demo.so.
The solution for me was to start all over with a fresh VM with enough diskspace (20GB is clearly not enough), enough memory (default is pretty low) and all cores assigned (default is 1) with the current Ubuntu 16.04 LTS and Android Studio. Also tensorflow v8.0 which came out meanwhile seems to be a bit less troublesome.

I described everything in my blog. It's in German but you'll only need the console commands anyway.
[http://blog.codingyourlife.at/?page_id=1315](url)
