### ISSUE TITLE
Word2Vec model crashes with unicode train data

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#2057]
### Environment info
Operating System: OS X 10.11.3

Installed version of CUDA and cuDNN: CUDA-7.5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
Developer/NVIDIA/CUDA-7.5/lib/libcudadevrt.a
/Developer/NVIDIA/CUDA-7.5/lib/libcudart.dylib
/Developer/NVIDIA/CUDA-7.5/lib/libcudart.7.5.dylib
/Developer/NVIDIA/CUDA-7.5/lib/libcudart_static.a

If installed from binary pip package, provide: 0.8.0rc0

### Steps to reproduce
1. Clone folder https://github.com/tensorflow/tensorflow/blob/r0.8/tensorflow/models/embedding/
2. Run successful python word2vec_optimized.py --train_data=questions-words.txt --eval_data=questions-words.txt --save_path=model/
3. Run failed if i add some unicode text in train data (e.g. russian word "тест")

### Logs or other output that would be helpful
Traceback (most recent call last):
  File "../lib/word2vec/word2vec_optimized.py", line 431, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "../lib/word2vec/word2vec_optimized.py", line 416, in main
    model = Word2Vec(opts, session)
  File "../lib/word2vec/word2vec_optimized.py", line 146, in __init__
    self.save_vocab()
  File "../lib/word2vec/word2vec_optimized.py", line 242, in save_vocab
    opts.vocab_counts[i]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

**Comment by kaiix** [comment]
temporary workaround
```python
  def save_vocab(self):
    """Save the vocabulary to a file so the model can be reloaded."""
    opts = self._options
    with open(os.path.join(opts.save_path, "vocab.txt"), "w") as f:
      for i in xrange(opts.vocab_size):
        f.write(u"{} {}\n".format(tf.compat.as_text(opts.vocab_words[i]),
                             opts.vocab_counts[i]).encode('utf8'))

```

**Comment by shkarupa-alex** [comment]
Solution works fine

**Comment by alextp** [comment]
Closing since the workaround works.

**Comment by alekseyl1992** [comment]
This workaround produces the following lines in vocab.txt:
`b'\xd0\xb8' 3185432`

Is there any way to load these sequences as utf8 strings (str) besides using `eval()`?

I think it would be better to store utf8-strings in the vocab as utf8-encoded file.
For now it seems to be weird for me:
it is `bytes` object representation saved in file
