### ISSUE TITLE
TF-hub command line cannot download module

### ISSUE THREAD

**Issue by bright1125** [tensorflow/tensorflow#20582]
When I try retrain my dataset as said in https://www.tensorflow.org/tutorials/image_retraining,
no matter which model I choose to fill in the --tfhub_module option from
https://www.tensorflow.org/hub/modules/image#mobilenet

I always stucked in "INFO:tensorflow:Downloading TF-Hub Module 'https://tfhub.dev/google/imagenet/mobilenet_v1_100_128/feature_vector/1'."

I have tried to change tfhub.dev/ into tensorflow.google.cn/hub/modules/ ,but fail too.

I am using tensorflow version1.7
Do I missed something?How can I fix it?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tatianashp** [comment]
Please post this question to [TensorFlow Hub issues](https://github.com/tensorflow/hub/issues).
