### ISSUE TITLE
grpc_master_service method names backward-incompatible

### ISSUE THREAD

**Issue by naurril** [tensorflow/tensorflow#20594]
After grpc updated(#20513 ), the master service method names are:
```
//generated automatically

static const char* MasterService_method_names[] = {
  "/tensorflow.grpc.MasterService/CreateSession",
  "/tensorflow.grpc.MasterService/ExtendSession",
  "/tensorflow.grpc.MasterService/PartialRunSetup",
  "/tensorflow.grpc.MasterService/RunStep",
  "/tensorflow.grpc.MasterService/CloseSession",
  "/tensorflow.grpc.MasterService/ListDevices",
  "/tensorflow.grpc.MasterService/Reset",
  "/tensorflow.grpc.MasterService/MakeCallable",
  "/tensorflow.grpc.MasterService/RunCallable",
  "/tensorflow.grpc.MasterService/ReleaseCallable",
};
```
but the old version is 
[v1.8 grpc_master_service_impl.cc](https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/core/distributed_runtime/rpc/grpc_master_service_impl.cc)
```
static const char* grpcMasterService_method_names[] = {
    "/tensorflow.MasterService/CreateSession",
    "/tensorflow.MasterService/ExtendSession",
    "/tensorflow.MasterService/PartialRunSetup",
    "/tensorflow.MasterService/RunStep",
    "/tensorflow.MasterService/CloseSession",
    "/tensorflow.MasterService/ListDevices",
    "/tensorflow.MasterService/Reset",
    "/tensorflow.MasterService/MakeCallable",
    "/tensorflow.MasterService/RunCallable",
    "/tensorflow.MasterService/ReleaseCallable",
};
```

So older version (e.g. 1.8) clients cannot talk to new version server and vice versa,  as I have tested. Should this be fixed?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by naurril** [comment]
Have I written custom code: yes
OS Platform and Distribution: Linux fedora28
TensorFlow installed from: source & bin both tested
TensorFlow version: 1.8 & newest
Bazel version: 1.4
CUDA/cuDNN version: 9.1
GPU model and memory: 11G
Exact command to reproduce: use v1.8 as client, and newest version from source as server, call session.list_devices() or session.run()

I believe all above info are irrelevant for this issue.

**Comment by drpngx** [comment]
@naurril thanks for reporting, that's indeed a problem. It's probably too late for this version to change back. I'm closing this.

@gunan to keep in mind for releases.
