### ISSUE TITLE
Profiler: Check Failed tf_start

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorflow#20590]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Archlinux
- **TensorFlow installed from (source or binary)**: pip tf-nightly
- **TensorFlow version (use command below)**: v1.8.0-3463-g39ea5a7044 1.10.0-dev20180620
- **Python version**: 3.6.5

### Describe the problem
I am trying do some profiling as described here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/profiler/g3doc/python_api.md

Session setup code
```python
run_meta = tf.RunMetadata()
builder = tf.profiler.ProfileOptionBuilder
    opts = builder(builder.time_and_memory()).order_by('micros').build()
    opts2 = tf.profiler.ProfileOptionBuilder.trainable_variables_parameter()
    with tf.contrib.tfprof.ProfileContext('.tmp/trace',
                                      trace_steps=range(0, 2),
                                      dump_steps=[2]) as pctx:
      pctx.add_auto_profiling('op', opts, [0, 1])
      pctx.add_auto_profiling('scope', opts2, [0, 1])
      self._session = tf.Session(
          target='', graph=self._graph,
          config=session_util.config_proto(
              session_settings['config_proto'],
              session_settings['gpu_options']))
    self.pctx = pctx
```

Then at a different point in my code I do
```python
loss = self._session.run(fetches, ..., run_meta)
```

This works for the first step, but at the second step it throws `F tensorflow/core/profiler/internal/print_model_analysis.cc:125] Check failed: tf_stat`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by sleighsoft** [comment]
So what does this error tell me to do?
