### ISSUE TITLE
TensorFlow failing on Bazel CI with Ubuntu 14.04

### ISSUE THREAD

**Issue by meteorcloudy** [tensorflow/tensorflow#20592]
https://buildkite.com/bazel/tensorflow/builds/863

Full log: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/330#f4d9112b-3525-45b1-a2c7-09bc95905c6d

Error message:
```
external/com_github_googlecloudplatform_google_cloud_cpp/google/cloud/bigtable/internal/rowreaderiterator.h:57:44: error: ambiguous overload for 'operator*' (operand type is 'std::remove_reference<const google::cloud::v0::internal::optional<google::cloud::bigtable::v0::Row>&>::type {aka const google::cloud::v0::internal::optional<google::cloud::bigtable::v0::Row>}')
```

Because it's only failing on 14.04, I suspect it's caused by compiling with an old gcc version.

culprit: https://github.com/tensorflow/tensorflow/commit/2e764644d6

Do we care about building TF on Ubuntu 14.04? If so we might need to fix code from https://github.com/GoogleCloudPlatform/google-cloud-cpp

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jiangcore** [comment]
+1. Any help?

**Comment by tommiezzz** [comment]
@jiangcore 
i comment out line 126,127,128 in external/com_github_googlecloudplatform_google_cloud_cpp/google/cloud/internal/optional.h and line 57 in external/com_github_googlecloudplatform_google_cloud_cpp/google/cloud/bigtable/internal/rowreaderiterator.h

**Comment by tatianashp** [comment]
This issue is better submitted to [Google Cloud Platform issues] since it is not a TensorFlow bug or feature request.

**Comment by ClaudioCimarelli** [comment]
@tommiebupt  I am experiencing the same problem with TF 1.12 and compiling with GCC 4.9
Where are the files to edit? The only ones I could find are under the folder "bazel-tensorflow", but I cannot modify those without creating a problem with the cache of bazel.

Moreover, there is a comment on line #59  of `rowreaderiterator.h`, which says that line #60 should be commented out with GCC 4.8. Should be the same with 4.9? Maybe this is the reason.

There is a way to exclude Google cloud from the beginning? Thanks a lot in advance, and sorry for so many questions.
