### ISSUE TITLE
no variable name in repr() of variables from tf.trainable_variables()

### ISSUE THREAD

**Issue by DSLituiev** [tensorflow/tensorflow#2061]
`repr()` does not show names of variables obtained from `tf.trainable_variables()`

### Environment info
Operating System:
MacOSX Yosemite, Python3.5

If installed from sources, provide the commit hash:
nightly build a week ago from wheel

### Steps to reproduce

           scope = "myscope"
           trainables = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, scope)
           "OR"
           trainables = tf.trainable_variables()
           print("trainable variables in scope '%s':\t%s" % (scope, ["%s" % repr(x) for x in trainables] ) )
           "trainable variables in scope 'model/states':	['<tensorflow.python.ops.variables.Variable object at 0x10bb3a518>', '<tensorflow.python.ops.variables.Variable object at 0x10bb3aa20>']"
           print("trainable variables in scope '%s':\t%s" % (scope, ["%s" % repr(x.name) for x in trainables] ) )
           "scope/name ..."

**Comment by poxvoculi** [comment]
It seems to have been a deliberate stylistic choice not to define __repr__ within tensorflow.  Not being a python enthusiast myself, I can't comment on the virtues of that decision.  If you feel differently, perhaps the tensorflow discussion group would be a good place to raise the issue.  [https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!forum/discuss]

**Comment by wookayin** [comment]
I am a little bit curious on that decision, and therefore opened a thread in the discussion group: https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!topic/discuss/u8eIulwX_OY
