### ISSUE TITLE
InMemoryEvaluatorHook failed to control printing freq with every_n_iter 

### ISSUE THREAD

**Issue by matthew-z** [tensorflow/tensorflow#20622]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:  v1.9.0-rc2-202-g6d5b8b7cae 1.10.0-dev20180707
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**:  https://gist.github.com/matthew-z/aec927462416969b9b4e9c39a15eabca
 
### Describe the problem

InMemoryEvaluatorHook prints the evaluation result after every training iteration even every_n_iter is set to 10.
 
### Source code / logs

Source code: [https://gist.github.com/matthew-z/aec927462416969b9b4e9c39a15eabca](https://gist.github.com/matthew-z/aec927462416969b9b4e9c39a15eabca)

Log: https://gist.github.com/matthew-z/921990af6957a1d9292759c933a1c16a

**Comment by jperl** [comment]
Here is a PR w/ test to fix this https://github.com/tensorflow/tensorflow/pull/20822

**Comment by cy89** [comment]
@matthew-z does that fix your problem?

**Comment by matthew-z** [comment]
Yes. I will close it
