### ISSUE TITLE
Unexpected result when load new model versions

### ISSUE THREAD

**Issue by weberxie** [tensorflow/tensorflow#20635]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 7.0
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.4
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: 0.7.0
- **GCC/Compiler version (if compiling from source)**:  4.8.5
- **CUDA/cuDNN version**: 5.1.10
- **GPU model and memory**: p40 etc
- **Exact command to reproduce**: 

### Describe the problem
Using tensorflow serving with hdfs and serving automatic loading new versions based on 1 second interval. Due to the load of hdfs, variables.index file may appeared later than saved_model.pb.

So, the unexpected things appeard, you can see the log in the next few lines.

### Source code / logs

when predict serving returns :

Attempting to use uninitialized value conv1d_1_1/kernel
       [[Node: conv1d_1_1/kernel/read = Identity[T=DT_FLOAT, _class=["loc:@conv1d_1_1/kernel"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1d_1_1/kernel)]]
       [[Node: dense_1_1/BiasAdd/_31 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_178_dense_1_1/BiasAdd", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

when load new version, serving print :

2018-06-25 16:56:40.483957: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:165] The specified SavedModel has no variables; no checkpoints were restored.

### Some thoughts

It's hard to say who is wrong, but should tensorflow consider and prevent this inconsistency?

**Comment by michaelisard** [comment]
@nfiedel I can't assign this to you (could you join the TF org?) but what do you think?

**Comment by nfiedel** [comment]
Based on the problem description, it sounds like you are writing the model directly to the directory that TensorFlow Serving is polling for new model versions. Instead, please export (or copy/upload if that is your workflow) to a temporary directory, and then use one of the atomic file operations such as move, to move the saved model directory into place.

**Comment by weberxie** [comment]
@nfiedel yes, thanks for your reply, your suggestions can avoid this problem. But should we prevent this problem from the code? Or should we make obvious instructions for the user to see?

**Comment by nfiedel** [comment]
@weberxie preventing this in code is particularly challenging across many distributed/inconsistent filesystems. Making this more obvious in the instructions is a great idea – I'll see if we can do this either now or in coming doc refreshes. Thanks!

**Comment by michaelisard** [comment]
I'll close this for now, thanks @nfiedel.
