### ISSUE TITLE
tf-trt converting. support for FC.

### ISSUE THREAD

**Issue by VictorBebnev** [tensorflow/tensorflow#20647]
Hello.
tensorflow.contrib.tensorrt.convert will support the fully connected layer?
Thx.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by drpngx** [comment]
@aaroey do you have any comment on this?

**Comment by aaroey** [comment]
@jjsjann123 any comments?

**Comment by aaroey** [comment]
This should be fixed by #21075, closing.
