### ISSUE TITLE
sess = tf.Session() get stuck!

### ISSUE THREAD

**Issue by wangbm** [tensorflow/tensorflow#2064]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-85-generic x86_64)

Installed version of CUDA and cuDNN: 
-rw-r--r-- 1 root root   322936 Apr 22 10:12 /usr/local/cuda-7.5/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Apr 22 10:12 /usr/local/cuda-7.5/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Apr 22 10:12 /usr/local/cuda-7.5/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Apr 22 10:12 /usr/local/cuda-7.5/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Apr 22 10:12 /usr/local/cuda-7.5/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 61453024 Apr 22 10:57 /usr/local/cuda-7.5/lib64/libcudnn.so
-rwxr-xr-x 1 root root 61453024 Apr 22 10:57 /usr/local/cuda-7.5/lib64/libcudnn.so.4
-rwxr-xr-x 1 root root 61453024 Apr 22 10:57 /usr/local/cuda-7.5/lib64/libcudnn.so.4.0.7
-rw-r--r-- 1 root root 62025862 Apr 22 10:57 /usr/local/cuda-7.5/lib64/libcudnn_static.a

My cudnn package: cudnn-7.0-linux-x64-v4.0-prod
If installed from binary pip package, provide:

1. Which pip package you installed.
sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.8.0rc0

### What have you tried?
1.I ran 'python -m tensorflow.models.image.mnist.convolutional', and for the first time the model can print 'initialization' and train, but got stuck at the end. The second time I want to run it, it got stuck at the beginning after extracting from data. When I debug it, I find it's tf.Session() that making it get stuck.  When I tried '>>> hello = tf.constant('Hello, TensorFlow!')  >>> sess = tf.Session()', it got stuck here.
2.I have run the NVIDIA_CUDA-7.5_Samples/1_Utilities/deviceQuery, and the result is PASS. I have even reinstall the cuda, but the result remain the same.
3.I have tried the CPU model, and it went just fine.
4.I tried to install from the source, the result remain the same.

Where is wrong? It seemed that the cuda and cudnn went wrong, but how to fix it?
Please help me!

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by prb12** [comment]
I am unable to reproduce this on my installation...

Could you please provide more information. e.g. did you have a previous version of TensorFlow installed, and if so did you remove it before installing 0.8?   (see note on https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#pip-installation)

What is your LD_LIBRARY_PATH?

Thanks, Paul

**Comment by wangbm** [comment]
I installed the tensorflow 0.8 on a brand new ubuntu server, and I'm sure I was following the steps on the tensorflow website. 
LD_LIBRARY_PATH = /usr/local/cuda-7.5/lib64
CUDA_HOME = /usr/local/cuda-7.5
I'm thinking if the cuda test can pass, and the CPU model went well. Can it be cuDNN that caused the bug?

**Comment by poxvoculi** [comment]
Are you still having a problem?  When you say it "gets stuck", what do you mean?  What are the symptoms?  Have you identified exactly where it gets stuck?

**Comment by wangbm** [comment]
The most obvious symptom is whenever I want to use tf.Session() in GPU model, it would show nothing including the command prompt and I can't input anything. Like this in IPYTHON,
_In [1]: import tensorflow as tf   
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally

In [2]: hello =  tf.constant('Hello')

In [3]: sess = tf.Session()_
It stuck here and stop showing anything, but it went just well in CPU model.
What should I do? Thank you very much!!
@poxvoculi

**Comment by ktrnka** [comment]
I ran into the same issue trying to setup an EC2 machine. Although deviceQuery ran fine, nvidia-smi would run halfway then crash the first time then hang on subsequent tries. I also tried running the [Theano test](http://deeplearning.net/software/theano/tutorial/using_gpu.html) which hung the same way as TensorFlow.

Ultimately I stumbled on https://devtalk.nvidia.com/default/topic/880246/cuda-7-5-unstable-on-ec2-/ which points to CUDA 7.5 as the issue. When I switched to CUDA 7.0 at least Theano would work. That nvidia forum thread has some directions at the end that might get 7.5 working.

**Comment by wangbm** [comment]
WOW! It works with CUDA 7.0! 
I've been trying to solve this problem for one week. You save me! Thanks! @ktrnka

**Comment by ktrnka** [comment]
You're welcome. Yesterday I followed the script on the nvidia forum thread
and got 7.5 working so now I can use pip tensor flow without problems.
On Apr 29, 2016 1:31 AM, "wangbm" <notifications@github.com> wrote:

WOW! It works with CUDA 7.0!
I've been trying to solve this problem for one week. You save me! Thanks!
@ktrnka <https://github.com/ktrnka>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/tensorflow/tensorflow/issues/2064#issuecomment-215657771>

**Comment by minakhan01** [comment]
I am having this problem with CUDA 8.0. I am following this guide here: https://gist.github.com/jganzabal/8e59e3b0f59642dd0b5f2e4de03c7687
