### ISSUE TITLE
Attempting to use uninitialized value Variable

### ISSUE THREAD

**Issue by qianlnk** [tensorflow/tensorflow#20660]
Hi all,

I had Import a graph with go:

```go
			bmodel := res.GetBytes(0)

			graph := tf.NewGraph()
			if err := graph.Import(bmodel, ""); err != nil {
				log.Error(err)
				continue
			}

			sess, err := tf.NewSession(graph, nil)
			if err != nil {
				log.Error(err)
				continue
			}

			p.model = &tf.SavedModel{
				Graph:   graph,
				Session: sess,
			}
```

use the model:

```go
	output := tf.Output{
		Op:    p.model.Graph.Operation("input"),
		Index: 0,
	}
	target, err := tf.NewTensor([][]float32{})

	if err != nil {
		log.Error(err)
		return "accept", err
	}

	tensor, err := tf.NewTensor([][]float32{preData})
	if err != nil {
		log.Error(err)
		return "accept", err
	}

	feeds := map[tf.Output]*tf.Tensor{
		output: tensor,
		p.model.Graph.Operation("target").Output(0): target,
	}

	fetches := []tf.Output{
		{
			Op:    p.model.Graph.Operation("infer"),
			Index: 0,
		},
	}

	result, err := p.model.Session.Run(
		feeds,
		fetches,
		nil,
	)
```

but get error: 

```sh
2018-07-10 14:36:41 ERROR (shield-ai-engine/predict.go:188):20187 Attempting to use uninitialized value Variable_3
	 [[Node: Variable_3/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable_3)]]
```
It haven't init in NewSession? how to initialize variable?

env:

OS: mac 10.11.6
python version: python2.7
tensorflow install base on https://www.tensorflow.org/install/install_go
tensorflow-go version: v1.9.0-rc2
go version: go1.9.2 darwin/amd64

**Comment by qianlnk** [comment]
save model with python:

```py
        builder = tf.saved_model.builder.SavedModelBuilder('shield')
        builder.add_meta_graph_and_variables(self.sess, ['login3'])
        builder.save()
```

here has all code:

[https://github.com/tensorflow/tensorflow/issues/20511](https://github.com/tensorflow/tensorflow/issues/20511)

**Comment by asimshankar** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
