### ISSUE TITLE
how can I use mkl with tbb in tensorflow 

### ISSUE THREAD

**Issue by suhang1994** [tensorflow/tensorflow#20681]
I found that tbb is fast than openMp
https://software.intel.com/en-us/articles/using-intel-mkl-and-intel-tbb-in-the-same-application

But in tensorflow, I cant use mkl with tbb, Is there a better solution？

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by suhang1994** [comment]
@tatianashp 

Thanks, I found another way to speed up my multithreading by setting MKL_NUM_THREADS.

And I have a question, tensorflow use mkl-dnn, if I use mkl, Is there any different?

**Comment by tatianashp** [comment]
In my experience, the performance is similar when using MKL or MKL-DNN. Setting the environment variables for MKL might have a bigger effect. Please take a look at [CPU optimizations](https://www.tensorflow.org/performance/performance_guide#optimizing_for_cpu ) guide for more information.
