### ISSUE TITLE
confused by device placement on Amazon AWS

### ISSUE THREAD

**Issue by timshephard** [tensorflow/tensorflow#207]
First - loving tensorflow.  The tutorials were really great fun to read.   Tensorflow API architecture is clear and amazing.   Hope to do pull requests once I get up to speed.

However, I'm trying to do device placement to do some basic benchmarks to see if it's worth using Amazon at all versus my own computers.  So far, not so promising, but maybe I'm doing something wrong.

From the example here:  http://tensorflow.org/how_tos/using_gpu/index.md

I get the following results.
<pre>

>>> with tf.device('/cpu:0'):
...   a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
...   b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
...   sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
...   print sess.run(c)
...
I tensorflow/core/common_runtime/gpu/gpu_device.cc:644] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GRID K520, pci bus\
 id: 0000:00:03.0)
Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GRID K520, pci bus id: 0000:00:03.0
I tensorflow/core/common_runtime/direct_session.cc:111] Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GRID K520, pci bus id: 0000:00:03.0

b: /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:289] b: /job:localhost/replica:0/task:0/cpu:0
a: /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:289] a: /job:localhost/replica:0/task:0/cpu:0
MatMul_1: /job:localhost/replica:0/task:0/gpu:0
I tensorflow/core/common_runtime/simple_placer.cc:289] MatMul_1: /job:localhost/replica:0/task:0/gpu:0
[[ 22.  28.]
 [ 49.  64.]]
</pre>
Looking at that, it looks like it's placing the matmul on the gpu.   I want it on the cpu.  Is that possible?  

Also, is matrix_inverse or matmul of say a 5000x5000 matrix a good (but very rough!) benchmark to help evaluate the value of Amazon GPU/CPU large instances?

Thanks again

**Comment by vrv** [comment]
In your code, it doesn't look like you wrapped the declaration of 'c' within the 'with tf.device()' block, so it doesn't have a device assigned to it.  Because we have an implementation of matmul on GPU, we automatically place the op on GPU.

I bet if you moved  c = tf.matmul(a, b) into the `with` block,it would probably do wht you expect.

As for the benchmark: GPUs are generally good for large matrix multiplies, so it's not a bad benchmark, but it depends on what you intend to use TensorFlow for.  The best benchmark is a real application :)

**Comment by timshephard** [comment]
Great stuff, vrv.  That was the issue.  

So, following that matmul only works for matricies up to 3000x3000 size or so.  I guess that's fine.  However, it doesn't seem to work at all for Matrix Inverse.  Is this just not supported yet?  https://developer.nvidia.com/sites/default/files/akamai/cuda/files/Misc/mygpu.pdf

tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'MatrixInverse_9': Could not satisfy explicit device specification '/gpu:0'

**Comment by vrv** [comment]
Yeah, matrix inverse has not yet been implemented for GPU, so when you say 'run this on GPU', we can't find an implementation for it and we return that error.

**Comment by timshephard** [comment]
Ok, awesome!   Thanks.   I assume I just need to look at ~/tensorflow/tensorflow/core/kernels/*gpu* for a list of the gpu supported operations.   I'll work with that.  List looks really exciting.  :D

**Comment by timshephard** [comment]
Ok, I think this is the list.  

$ ls *gpu* | grep -v cwise
adjust_contrast_op_gpu.cu.cc
aggregate_ops_gpu.cu.cc
argmax_op_gpu.cu.cc
avgpooling_op_gpu.cu.cc
batch_norm_op_gpu.cu.cc
bias_op_gpu.cu.cc
cast_op_gpu.cu.cc
check_numerics_op_gpu.cu.cc
concat_op_gpu.cu.cc
constant_op_gpu.cu.cc
conv_ops_gpu.cu.cc
conv_ops_gpu_2.cu.cc
conv_ops_gpu_3.cu.cc
conv_ops_gpu_matmul.cu.cc
dense_update_ops_gpu.cu.cc
l2loss_op_gpu.cu.cc
matmul_op_gpu.cu.cc
maxpooling_op_gpu.cu.cc
maxpooling_op_gpu.h
pad_op_gpu.cu.cc
pooling_ops_common_gpu.h
random_op_gpu.cu.cc
reduction_ops_gpu.cu.cc
relu_op_gpu.cu.cc
reverse_op_gpu.cu.cc
reverse_sequence_op_gpu.cu.cc
slice_op_gpu.cu.cc
softmax_op_gpu.cu.cc
softplus_op_gpu.cu.cc
split_op_gpu.cu.cc
tile_ops_gpu.cu.cc
training_ops_gpu.cu.cc
transpose_op_gpu.cu.cc
xent_op_gpu.cu.cc


Let me know if you want some assist with the docs.  Happy to do a pull request in whatever format you'd like.  Cheers

**Comment by vrv** [comment]
Those are the list of the files, but some of those files have multiple op implementations in them.

I would love to be able to automatically generate the list of implemented ops for each platform so they don't go out of date.  Maybe one day soon I'll get to doing this :)

**Comment by vrv** [comment]
(should have a separate feature request for this)
