### ISSUE TITLE
Guide Tensorflow for JAVA EE

### ISSUE THREAD

**Issue by JohnnyLe** [tensorflow/tensorflow#2070]
Hello all,

Do we have any guideline or document to help get started with JAVA EE? In case we want to build with Java server application.

Best regards
Johnny

**Comment by poxvoculi** [comment]
I'm not aware that this issue has been raised before.  Could you clarify what you think the problems are?

**Comment by JohnnyLe** [comment]
Thanks @poxvoculi for the response.
I've just start for researching solution for integration Tensorflow with Java web app, so I wondering if there is any document available for that.

**Comment by mrry** [comment]
There is no supported Java API for TensorFlow at present, but you could look at the source of the [Android JNI wrapper](https://github.com/tensorflow/tensorflow/tree/e39d8feebb9666a331345cd8d960f5ade4652bba/tensorflow/examples/android/jni) for guidance in how to build your own interface.

**Comment by JohnnyLe** [comment]
Thank you @mrry 
Ok, I will check with that.
