### ISSUE TITLE
Seq2seq tutorial dissapeared

### ISSUE THREAD

**Issue by melkonyan** [tensorflow/tensorflow#20714]
Hi, 

[https://www.tensorflow.org/tutorials/seq2seq](https://www.tensorflow.org/tutorials/seq2seq) tutorial returns 404 not found. This is where an extensive tutorial by Luong et al was located until several days ago, I assume it was deleted or moved by mistake.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by melkonyan** [comment]
Have I written custom code: NA
OS Platform and Distribution: NA
TensorFlow installed from: NA
TensorFlow version: NA
Bazel version: NA
CUDA/cuDNN version: NA
GPU model and memory: NA
Exact command to reproduce: NA

**Comment by ayush2991** [comment]
The tensorflow tutorials page has been evolving drastically of late. If this is what you were looking for, please close this issue.
https://www.tensorflow.org/versions/r1.0/tutorials/seq2seq
New tutorials page:
https://www.tensorflow.org/tutorials/
Thanks!

**Comment by ayush2991** [comment]
Actually the tutorials page (https://www.tensorflow.org/tutorials/) does have a link to the NMT page (https://github.com/tensorflow/nmt) under the "Sequences" tab. You will notice that the tutorials page has also changed quite a bit - tutorials are now clubbed under collapsed sections on the left.

**Comment by lamberta** [comment]
Aayush is correct, we've updated the tutorials page and are cleaning up some old examples.
That NMT tutorial is linked under 'Sequences' (there's another [NMT w/ attention](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb) using eager listed under 'Research and experimentation').

I added a redirect for '/tutorials/seq2seq' to fix the 404. It redirects back to the main tutorials page.
