### ISSUE TITLE
TFSA-2018-001 commit link is invalid

### ISSUE THREAD

**Issue by attritionorg** [tensorflow/tensorflow#20722]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2018-001.md

Links to:
https://github.com/tensorflow/tensorflow/commit/49f73c55d56edffebde4bca4a407ad69c1cae4333c55

Which is 404. Can you please update this with the correct commit? Thanks!

**Comment by yongtang** [comment]
Created the PR #20725 for the link fix.

**Comment by attritionorg** [comment]
Thank you for the really quick response!
