### ISSUE TITLE
TF 1.3 with AMD ROCm build error on ARM64 Ubuntu 16.04

### ISSUE THREAD

**Issue by wormwang** [tensorflow/tensorflow#20724]
I meet error at ARM64 ubuntu 16.04 with AMD ROCm and TF 1.3 https://github.com/ROCmSoftwarePlatform/tensorflow

root@:~/tensorflow# bazel build --config=opt --config=rocm //tensorflow/tools/pip_package:build_pip_package --verbose_failures
ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/io_bazel_rules_closure/closure/filegroup_external.bzl:23:16: name 'set' is not defined
ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/io_bazel_rules_closure/closure/webfiles/web_library.bzl:43:14: name 'set' is not defined
ERROR: error loading package '': Extension 'closure/filegroup_external.bzl' has errors
ERROR: error loading package '': Extension 'closure/filegroup_external.bzl' has errors
INFO: Elapsed time: 4.595s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by wormwang** [comment]
To build Tensorflow 1.3.0? There's an old version of TF that can only be built with Bazel 0.5.1, according to the tutorial. You have Bazel 0.15, which doesn't support the keyword set in the build scripts

download bazel 0.51
Download bazel-<version>-dist.zip from the release page.

Note: There is a single, architecture-independent distribution archive. There are no architecture-specific or OS-specific distribution archives.
 
On Unix-like systems such as Ubuntu Linux or macOS, do the following:

Open a shell or Terminal window.

Change into the directory where you unpacked the distribution archive.

Arm64 patch bazel
https://collaborate.linaro.org/display/BDTS/Building+and+Installing+Tensorflow+on+AArch64

https://github.com/bazelbuild/bazel/commit/cc8e7166e29fee39d44e578cf98a06486084a6bd

Run the compilation script: 
$bash ./compile.sh

**Comment by gunan** [comment]
This is a very old branch well out of our support window.
Also support for ROCm is just being merged into our repository.
I am pretty certain that TF 1.3 wont build successfully for ROCm.
You should reach out to ROCm or the author of the above instructions for this.
