### ISSUE TITLE
tf.contrib.seq2seq.AttentionWrapperState TypeError: __new__() missing 4 required positional arguments: 'time', 'alignments', 'alignment_history', and 'attention_state'

### ISSUE THREAD

**Issue by lvjiujin** [tensorflow/tensorflow#20727]
in the tensorflow r1.8:
```
 tf.contrib.seq2seq.AttentionWrapperState(cell_state, attention, time, alignments, alignment_history,attention_state)
```
in the tensorflow r1.2 
```
 tf.contrib.seq2seq.AttentionWrapperState(cell_state, attention, time, alignments, alignment_history,attention_state)
```

my code is r1.2, but now i want to run it in the r1.8.
```
 initial_state = tf.contrib.seq2seq.AttentionWrapperState(enc_state[0],
                                                             _zero_state_tensors(rnn_size, 
                                                                                 batch_size, 
                                                                                 tf.float32)) 
 with tf.variable_scope("decode"):
        training_logits = training_decoding_layer(dec_embed_input, 
                                                  summary_length, 
                                                  dec_cell, 
                                                  initial_state,
                                                  output_layer,
                                                  vocab_size, 
                                                  max_summary_length)
    with tf.variable_scope("decode", reuse=True):
        inference_logits = inference_decoding_layer(embeddings,  
                                                    vocab_to_int['<GO>'], 
                                                    vocab_to_int['<EOS>'],
                                                    dec_cell, 
                                                    initial_state, 
                                                    output_layer,
                                                    max_summary_length,
                                                    batch_size)
```
who can help me ?
because the number of the argument of the AttentionWrapperState in the r1.2 is the same to the r1.8 , why it occurs error in the r1.8 , but well in the r1.2?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by drpngx** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by jinfagang** [comment]
Same issue here

**Comment by betty35** [comment]
Had the same issue when I moved the old-versioned codes to new environment, but found a workaround, kinda.... 
Simply give up initiating it with AttentionWrapperState, and do this:
```
initial_state = decoder_cell.zero_state(dtype=tf.float32, batch_size=batch_size)
initial_state = initial_state.clone(cell_state=encoder_state[0])
```
And it worked ヽ(｀Д´)ﾉ︵ ┻━┻ ┻━┻

(Tensorflow version: 1.13.1)
