### ISSUE TITLE
Getting KeyError: u'LSTMBlockCell while loading graph

### ISSUE THREAD

**Issue by akanyaani** [tensorflow/tensorflow#20732]
I have trained an LSTM model using tf.contrib.cudnn_rnn.CudnnCompatibleLSTMCell when I tried to load that model I got KeyError: u'LSTMBlockCell' and it was working fine when I was using Basic LSTM cell.
Tensorflow-gpu - 1.8.0

Error Log

File "<stdin>", line 1, in <module>
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1955, in import_meta_graph
    **kwargs)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 743, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 460, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/home/abhay/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 227, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: u'LSTMBlockCell'

**Comment by CaoManhDat** [comment]
I got the same issue when tried to load a trained model of [PTB Rnn](https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb)

Tensorflow-gpu - 1.8.0
The code used for loading model
```
with tf.Session() as sess:
  new_saver = tf.train.import_meta_graph('./trained_model/model.ckpt-24672.meta')
  new_saver.restore(sess, tf.train.latest_checkpoint('./trained_model'))
```

Error log
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-63da410a664c> in <module>()
      1 with tf.Session() as sess:
----> 2   new_saver = tf.train.import_meta_graph('./trained_model/model.ckpt-24672.meta')
      3   new_saver.restore(sess, tf.train.latest_checkpoint('./trained_model'))

/home/caomanhdat/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.pyc in import_meta_graph(meta_graph_or_file, clear_devices, import_scope, **kwargs)
   1953       clear_devices=clear_devices,
   1954       import_scope=import_scope,
-> 1955       **kwargs)
   1956 
   1957   if meta_graph_def.HasField("saver_def"):

/home/caomanhdat/.local/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.pyc in import_scoped_meta_graph(meta_graph_or_file, clear_devices, graph, import_scope, input_map, unbound_inputs_col_name, restore_collections_predicate)
    741         name=(import_scope or scope_to_prepend_to_names),
    742         input_map=input_map,
--> 743         producer_op_list=producer_op_list)
    744 
    745     # Restores all the other collections.

/home/caomanhdat/.local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.pyc in new_func(*args, **kwargs)
    430                 'in a future version' if date is None else ('after %s' % date),
    431                 instructions)
--> 432       return func(*args, **kwargs)
    433     return tf_decorator.make_decorator(func, new_func, 'deprecated',
    434                                        _add_deprecated_arg_notice_to_docstring(

/home/caomanhdat/.local/lib/python2.7/site-packages/tensorflow/python/framework/importer.pyc in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    458   if producer_op_list is not None:
    459     # TODO(skyewm): make a copy of graph_def so we're not mutating the argument?
--> 460     _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
    461 
    462   graph = ops.get_default_graph()

/home/caomanhdat/.local/lib/python2.7/site-packages/tensorflow/python/framework/importer.pyc in _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
    225     # Remove any default attr values that aren't in op_def.
    226     if node.op in producer_op_dict:
--> 227       op_def = op_dict[node.op]
    228       producer_op_def = producer_op_dict[node.op]
    229       # We make a copy of node.attr to iterate through since we may modify

KeyError: u'LSTMBlockCell'
```

**Comment by akanyaani** [comment]
Hi Anderson,

I am waiting for your reply, I tried to resolve this problem but I am not able to solve please help.

**Comment by akanyaani** [comment]
Hi all,
I have resolved this issue, earlier i used to load model using this 

tf.reset_default_graph()
saver = tf.train.import_meta_graph("{}.meta".format(checkpoint_file))
saver.restore(sess, checkpoint_file)

But sometimes I was getting an LSTMBLOACKcell error sometimes some variable is not initialized.
Now While training, I am storing these variable to graph only.

var_list = (tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope) + tf.get_collection(tf.GraphKeys.SAVEABLE_OBJECTS, scope))

And the time of loading the graph I am loading the list of variables 

saver = tf.train.Saver(var_list)
saver.restore(sess, checkpoint_file)

Now its working fine, I am able to resume the training or making servable file.

Thanks

**Comment by angersson** [comment]
Looks like this issue has been resolved, so I am closing the issue. Thanks!

**Comment by AbdelsalamHaa** [comment]
Hi @akanyaani 
you mean I have to start the training from beginning,
I'm trying to change the model to be in one .pd file so I got the same error but I'm doing this after the training is done and the ckpt files are saved

**Comment by amirmgh1375** [comment]
you just need to add *.so compiled file generated by model implementation.
as follows add this line before session and import meta graph.
`tf.load_op_library('<compiled_filename>.so')`
for example. i compiled a model that contains a `RoiPooling` layer and generated `roi_pooling.so` file. so that i added this line to my code
`tf.load_op_library('op/roi_pooling.so')`

and finally it works : )
