### ISSUE TITLE
tensorflow uses recomputer technology

### ISSUE THREAD

**Issue by jerryli1119** [tensorflow/tensorflow#20730]
System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary):source
TensorFlow version (use command below):1.8.0
Python version: 3.5
Bazel version (if compiling from source):0.10.0
GCC/Compiler version (if compiling from source): c++11
CUDA/cuDNN version: 9/7
GPU model and memory: gtx 1080ti, 11G
Exact command to reproduce:N/A
Describe the problem:

In order to understand how much gpu memory resources tensorflow can economize, I did some experiments.
My network is vgg-16 and dataset is mnist, batch size is 128. i estimate my gpu memory usage is 2.8GB.
I close  all the RewriterConfig like:
  rewrite_options.memory_optimization = rewriter_config_pb2.RewriterConfig.NO_MEM_OPT
  rewrite_options.layout_optimizer = rewriter_config_pb2.RewriterConfig.OFF
  rewrite_options.function_optimization = rewriter_config_pb2.RewriterConfig.OFF
  rewrite_options.constant_folding = rewriter_config_pb2.RewriterConfig.OFF
  rewrite_options.arithmetic_optimization = rewriter_config_pb2.RewriterConfig.OFF
  rewrite_options.loop_optimization = rewriter_config_pb2.RewriterConfig.OFF
  rewrite_options.dependency_optimization = rewriter_config_pb2.RewriterConfig.OFF
And i gradually reduce the amount of gpu memory usage :

GPU   memory usage | 2.883 | 2.5 | 2 | 1.5 | 1.307
-- | -- | -- | -- | -- | --
average(iter   5000) | 337.161 | 336.968 | 339.018 | 338.409 | 412.119
average(iter   50000) | 3350.804 | 3352.093 | 3358.742 | 3373.366 | 4116.673

I observed that the method used by tensorflow is recomputer. Why use recomputer technology instead of swapping technology? Is recompute faster than swapping? or ?
In the memory_optimizer.cc:1226, it has RecomputationRewritingPass function. After I close the function to test, i find that tensorflow has other block do same event.
Why tensorflow has two block to do same event ?

Thanks.

**Comment by skye** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
