### ISSUE TITLE
Tensorflow C++ GPU support

### ISSUE THREAD

**Issue by gulingfengze** [tensorflow/tensorflow#20743]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Window 10 64Bit
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.7.0-rc1
- **Python version**: 3.5
- **Bazel version (if compiling from source)**:N/A
- **GCC/Compiler version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:9.0/7.0
- **GPU model and memory**:GTX960
- **Exact command to reproduce**:N/A

### Describe the problem
I have successfully compiled the tensorflow1.7C++ version on windows10.In the prediction, I found that GPU is not used in the program. Is the GPU not supported by the tensorflowC++ interface?I am very anxious and hope to get help. Thank you very much.

**Comment by aimhabo** [comment]
You are not using bazel. how did you "./configure" and make it?

**Comment by gulingfengze** [comment]
@aimhabo I compile using CMake,as follows:
1. Go to the tensorflow/tensorflow/contrib/cmake path, create the build folder, and CMD enters the build folder to execute the command:

> cmake .. -G "Visual Studio 14 2015" -A x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=C:/tools/swigwin-3.0.12/swig.exe -DPYTHON_EXECUTABLE=C:/ProgramData/Anaconda3/envs/tfbuild/python.exe -DPYTHON_LIBRARIES=C:/ProgramData/Anaconda3/envs/tfbuild/libs/python35.lib -Dtensorflow_ENABLE_GPU=ON -Dtensorflow_ENABLE_GRPC_SUPPORT=OFF -Dtensorflow_BUILD_PYTHON_BINDINGS=OFF -Dtensorflow_BUILD_SHARED_LIB=ON

2.Enter the build folder, use VS2015 to open tensorflow.sln, and then ALL build.

**Comment by aimhabo** [comment]
@gulingfengze I got this in Cmake
> CMake Error at CMakeLists.txt:422 (message):
>   NCCL is required for GPU-build
