### ISSUE TITLE
Miss a '.support'

### ISSUE THREAD

**Issue by ruihou** [tensorflow/tensorflow#20748]
https://github.com/tensorflow/tensorflow/blob/365d2fc4d62540b2c6524500a7a58e7edab0dfa9/tensorflow/contrib/lite/java/demo/app/build.gradle#L47

It should be com.android.support.test instead of com.androidx.test. Otherwise, gradle will report an error

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by shashishekhar** [comment]
Fix is merged.
