### ISSUE TITLE
Gradient of TensorArray updated during while loop yields error

### ISSUE THREAD

**Issue by ofirnachum** [tensorflow/tensorflow#2077]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Mac OS X 10.11.4

Installed version of CUDA and cuDNN: none
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed: Installed from source
2. The output from python -c "import tensorflow; print(tensorflow.__version__)": 0.8.0rc0

If installed from sources, provide the commit hash:
commit 504e8a6ac678f83f88862b3826d54bb9b484cc33

### Steps to reproduce
1. See http://stackoverflow.com/questions/36807107/strange-error-when-taking-gradient-of-tensorarray

### What have you tried?
1. I've tried removing the while loop (just writing out one iteration) and it works.  Introducing the while loop back in yields error.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
See http://stackoverflow.com/questions/36807107/strange-error-when-taking-gradient-of-tensorarray

**Comment by yaroslavvb** [comment]
@yuanbyu Could that be related to the recent gradients code in while/loop?

**Comment by yuanbyu** [comment]
I will have to take a look.  My guess is that the gradient code for one of the TensorArray ops missed a dependency, resulting in reading an unwritten slot.

**Comment by ebrevdo** [comment]
I see you are performing an unpack to write into one of the TensorArrays.  Though I haven't taken a careful look at the code, make sure all the elements you unpack have a corresponding read or you have a pack(); otherwise there may be no gradient written to the corresponding slot at runtime.

It's also easier to debug if you can write a very simple failing case.

**Comment by yuanbyu** [comment]
When reading an unwritten slot from a gradient TensorArray, could we return zeros instead of an error?

**Comment by ofirnachum** [comment]
Is it actually reading an unwritten slot?  At least in the forward stage, all read slots should be previously written to.

**Comment by ebrevdo** [comment]
They should all be read from also.

**Comment by ofirnachum** [comment]
This should also be the case.  In fact, when I replace the 'while' loop with a written out single iteration (equivalent in the case that I test), the code works fine forwards and backwards.  So I would assume there is something to do with using the TensorArray's inside the while loop that is causing issues.

**Comment by ebrevdo** [comment]
Are you using a separate tensor array inside each while loop iteration?

**Comment by ofirnachum** [comment]
The inner handle of the tensor array should be the same through all iterations.  The style is similar to _dynamic_rnn_loop in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn.py
(the TensorArray is written-to to yield a new TensorArray which is passed to the next iteration - the difference in my code is that the array is also read from).

**Comment by ebrevdo** [comment]
We haven't tested your use case very carefully.  I'll have to review your
code.. May be a few weeks unless Yuan has time to do it before I get to it.

**Comment by girving** [comment]
@ebrevdo, @yuanbyu: What's the status of this?

**Comment by yuanbyu** [comment]
We have a bug in gradient support for unpack and split of dynamic TensorArray. I have a pending CL fixing this problem.
