### ISSUE TITLE
CUDA 9.2 + cuDNN 7.1.4 Support for Windows

### ISSUE THREAD

**Issue by subha26** [tensorflow/tensorflow#20770]
I installed CUDA 9.2 and cuDNN 7xx on windows 10. when I import tensorflow in python, it says that tensorflow works only with CUDA 9.0, so when wil the support for CUDA 9.2 come.

**Comment by gunan** [comment]
As @alanpurple mentioned, and as documented at https://www.tensorflow.org/install/install_windows
Our prebuilt binaries are built for cuda 9.0.
The sources can run on cuda 9.2, but you just need to build from sources tourself.
According to our discussions, we will probably jump straight to cuda 10.
