### ISSUE TITLE
tf1.2 windows dll error

### ISSUE THREAD

**Issue by craigtao** [tensorflow/tensorflow#20775]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2001	无法解析的外部符号 "public: void __cdecl google::protobuf::internal::LogFinisher::operator=(class google::protobuf::internal::LogMessage &)" (??4LogFinisher@internal@protobuf@google@@QEAAXAEAVLogMessage@123@@Z)	win_trainer	H:\2018\001_TFopencv\002_demo\TF1.2\DemoTF1.2\win_trainer\example_trainer.obj	1

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tatianashp** [comment]
@craigtao  Thank you for reporting the error. Please try using a more recent version of TensorFlow and see if it helps.

**Comment by VanitarNordic** [comment]
if you use Anaconda, you can use  `conda install -c hesi_m tensorflow ` to install tensorflow 1.9.0 for CPU 

if you specifically use Keras also, you can use  `conda install -c hesi_m keras` which installs Keras 2.2.0 in accompany with everything including tensorflow 1.9.0

It is better to make a fresh anaconda environment for your experiments

**Comment by craigtao** [comment]
my project just need tf1.2 ， its enough,

**Comment by tatianashp** [comment]
1.2 is an old version and might have bugs that have been fixed since then. If you see erroneous behavior in the latest version please let us know and reopen the issue. Please also provide full details about your system  using the standard template.
