### ISSUE TITLE
Tensorflow 1.8.0 and 1.9.0 behavioural difference for tf.layers.Layer API 

### ISSUE THREAD

**Issue by n3011** [tensorflow/tensorflow#20789]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8.0 and 1.9.0
- **Python version**: 3.5.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: cpu
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

      import tensorflow as tf

      class LayersBaseTest(tf.test.TestCase):

        def test_create_variable(self):
  
          class MyLayer(tf.layers.Layer):

             def build(self, _):
               # Do not mark the layer as built.
                pass

              def call(self, inputs):
                self.my_var = self.add_variable('my_var', [2, 2])
                if self.built:
                  self.add_variable('this_will_break_on_second_call', [2, 2])
                return inputs + tf.square(self.my_var)

          layer = MyLayer(name='my_layer')
          inputs = tf.random_uniform((2,), seed=1)
          outputs = layer.apply(inputs)
          self.assertEqual(layer.built, True)
          self.assertEqual(outputs.op.name, 'my_layer/add')
          self.assertListEqual([v.name for v in layer.variables], ['my_layer/my_var:0'])
          with self.assertRaisesRegex(ValueError, 'my_layer/this_will_break_on_second_call'):
            layer.apply(inputs)
          # The list of variables hasn't changed.
          self.assertListEqual([v.name for v in layer.variables], ['my_layer/my_var:0'])

      if __name__ == '__main__':
        tf.test.main()

### Describe the problem
the above tests passed with tensorflow version `1.8.0`

Throws the following errors with tensorflow version `1.9.0`. The `tf.layers.Layer` shouldn't create another variable with the same name even after throwing the `ValueError` on the second call to `layer.apply`. This behaviours s unexpected. 
###  logs
>FAIL: test_create_variable (__main__.LayersBaseTest)
 >----------------------------------------------------------------------
 >Traceback (most recent call last):
  >File "test_layer_base_tf1.9.py", line 29, in test_create_variable
   >self.assertListEqual([v.name for v in layer.variables], ['my_layer/my_var:0'])
  >AssertionError: Lists differ: ['my_layer/my_var:0', 'my_layer/my_var:0'] != ['my_layer/my_var:0']
   >First list contains 1 additional elements.
   >First extra element 1:  
    >'my_layer/my_var:0'
    > - ['my_layer/my_var:0', 'my_layer/my_var:0']
    > + ['my_layer/my_var:0']

**Comment by facaiy** [comment]
I think you should call `add_variable` in `build` method, rather than `call` method.

**Comment by n3011** [comment]
@cy89 any updates on this?

**Comment by cy89** [comment]
@n3011 could you try @facaiy 's suggestion? Or explain why it is that you need to build the variables at call time, not at build time?

**Comment by n3011** [comment]
@cy89 I think my issue relates to behavioural difference . can you replay on that?

**Comment by facaiy** [comment]
I'm afraid this is intended behavior going forward. By the way, perhaps the issue is related to #20842.
