### ISSUE TITLE
tensorflow-1.9.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by SHikumo** [tensorflow/tensorflow#20787]
From my Cmd:  I have downloaded it from here: https://pypi.org/project/tensorflow/#files

F:\Python\Scripts>pip3 install tensorflow-1.9.0-cp36-cp36m-win_amd64.whl
tensorflow-1.9.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

F:\Python\Scripts>python --version
Python 3.6.5

I tried upgrade Pip, Wheel but they're all up-to-date.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by VanitarNordic** [comment]
if you use Anaconda, you can use  `conda install -c hesi_m tensorflow ` to install tensorflow 1.9.0 for CPU 

if you specifically use Keras also, you can use  `conda install -c hesi_m keras` which installs Keras 2.2.0 in accompany with everything including tensorflow 1.9.0

It is better to make a fresh anaconda package for your experiments
