### ISSUE TITLE
Can not convet .pb to .tflite format using tflite_convert

### ISSUE THREAD

**Issue by MohammadMoradi** [tensorflow/tensorflow#20798]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.9
- **Python version**: 3.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0/7.0
- **GPU model and memory**: GTX 1060/6G
- **Exact command to reproduce**: 
tflite_convert   --output_file=/tmp/net.tflite --saved_model_dir=models/ssd_mobilenet_v1_plate_0.004_set2_150\*150/saved_model

### Describe the problem
Hi, I want to covert a .pb model to .tflite one. The model is train with tensorflow object detection API. The input tensor shape is (None, None, None, 3) but it seems that tflite_convert doesn't support this kind of input.

### Source code / logs
ValueError: None is only supported in the 1st dimension. Tensor 'image_tensor:0' has invalid shape '[None, None, None, 3]'.

**Comment by inakaaay** [comment]
I have the same problem. please update if you have other option

**Comment by SanggunLee** [comment]
I have the same issue.

Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 320, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 316, in run_main
    _convert_model(tflite_flags)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 121, in _convert_model
    output_data = converter.convert()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/lite.py", line 273, in convert
    "invalid shape '{1}'.".format(tensor.name, shape))
ValueError: None is only supported in the 1st dimension. Tensor 'pnet/input:0' has invalid shape '[None, None, None, 3]'.

**Comment by achowdhery** [comment]
Please follow steps on this blog post and let us know if you still fail to convert SSD Mobilenet V1
https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193

**Comment by MohammadMoradi** [comment]
Thanks for your reply. The problem was that I used old version of tensorflow object detectjon API. The new one seems to have complete solution for tensorflow lite. Maybe I should close the issue.

**Comment by Elites2017** [comment]
@MohammadMoradi How did you figure this out?

**Comment by Elites2017** [comment]
@MohammadMoradi I have the same problem, I don't know how to solve it. Any help is welcomed !

**Comment by zishanahmed08** [comment]
@Elites2017 David.Where you able to solve it?

**Comment by abhijayghildyal** [comment]
Hi I am facing the same issue.


	model.inputs----------> [<tf.Tensor 'conv2d_1_input:0' shape=(?, 32, 32, 3) dtype=float32>]
	Traceback (most recent call last):
	  File "training.py", line 199, in <module>
	    tflite_model = tf.contrib.lite.toco_convert( frozen_graph, model.inputs, [out.op.name for out in model.outputs])
	  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/convert.py", line 243, in toco_convert
	    *args, **kwargs)
	  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/convert.py", line 212, in build_toco_convert_protos
	    input_array.shape.dims.extend(map(int, input_tensor.get_shape()))
	TypeError: __int__ returned non-int (type NoneType)

**Comment by abhijayghildyal** [comment]
> @MohammadMoradi I have the same problem, I don't know how to solve it. Any help is welcomed !

Were you able to solve this?

**Comment by Elites2017** [comment]
> 
> ### System information
> 
>     * **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
> 
>     * **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
> 
>     * **TensorFlow installed from (source or binary)**: binary
> 
>     * **TensorFlow version (use command below)**: 1.9
> 
>     * **Python version**: 3.5
> 
>     * **Bazel version (if compiling from source)**:
> 
>     * **GCC/Compiler version (if compiling from source)**:
> 
>     * **CUDA/cuDNN version**: 9.0/7.0
> 
>     * **GPU model and memory**: GTX 1060/6G
> 
>     * **Exact command to reproduce**:
>       tflite_convert   --output_file=/tmp/net.tflite --saved_model_dir=models/ssd_mobilenet_v1_plate_0.004_set2_150*150/saved_model
> 
> 
> ### Describe the problem
> 
> Hi, I want to covert a .pb model to .tflite one. The model is train with tensorflow object detection API. The input tensor shape is (None, None, None, 3) but it seems that tflite_convert doesn't support this kind of input.
> ### Source code / logs
> 
> ValueError: None is only supported in the 1st dimension. Tensor 'image_tensor:0' has invalid shape '[None, None, None, 3]'.


@pkulzc Do you think this error is caused because we don't specify the input shape in the file **export_inference_graph.py** if so, should we edit this file by putting the dimension of our images?

**Comment by Elites2017** [comment]
> 
> 
> Thanks for your reply. The problem was that I used old version of tensorflow object detectjon API. The new one seems to have complete solution for tensorflow lite. Maybe I should close the issue.

@inakaaay @MohammadMoradi How did you Guys figure this out ?

**Comment by kismeter** [comment]
> I use the command to convert .pb to .tflite
> `tflite_convert --output_file=/home/wang/Downloads/deeplabv3_mnv2_pascal_train_aug/optimized_graph.tflite --graph_def_file=/home/wang/Downloads/deeplabv3_mnv2_pascal_train_aug/frozen_inference_graph.pb --inference_type=FLOAT --inference_input_type=QUANTIZED_UINT8 --input_arrays=ImageTensor --input_shapes=1,513,513,3 --output_arrays=SemanticPredictions –allow_custom_ops`
> and it works
> I use the pretrained model downloaded from [https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md](url)

@wwwecho do you try to inference using coverted tflite? I met runtime error ```Failed to run on the given Interpreter: tensorflow/contrib/lite/kernels/depthwise_conv.cc:99 params->depth_multiplier * SizeOfDimension(input, 3) != SizeOfDimension(filter, 3) (0 != 32)Node number 30 (DEPTHWISE_CONV_2D) failed to prepare.```

**Comment by zhewang95** [comment]
> > I use the command to convert .pb to .tflite
> > `tflite_convert --output_file=/home/wang/Downloads/deeplabv3_mnv2_pascal_train_aug/optimized_graph.tflite --graph_def_file=/home/wang/Downloads/deeplabv3_mnv2_pascal_train_aug/frozen_inference_graph.pb --inference_type=FLOAT --inference_input_type=QUANTIZED_UINT8 --input_arrays=ImageTensor --input_shapes=1,513,513,3 --output_arrays=SemanticPredictions –allow_custom_ops`
> > and it works
> > I use the pretrained model downloaded from [https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md](url)
> 
> @wwwecho do you try to inference using coverted tflite? I met runtime error `Failed to run on the given Interpreter: tensorflow/contrib/lite/kernels/depthwise_conv.cc:99 params->depth_multiplier * SizeOfDimension(input, 3) != SizeOfDimension(filter, 3) (0 != 32)Node number 30 (DEPTHWISE_CONV_2D) failed to prepare.`

same problem.

**Comment by jayzhou215** [comment]
Share my problem and the solution.
problem:  I don't know what is the accutally input_arrays and output_arrays. It gives errors like`Invalid tensors 'convolution2d_input_1:0' were found`
fix: add `print(list(tensor_name_to_tensor))` to contrib/lite/python/convert_saved_model.py line 176 in function get_tensors_from_tensor_names()

after execute the tflite_convert command again, it print all the tensor name. 
my finally command which execute success
`tflite_convert \
  --output_file=tf.tflite \
  --graph_def_file=tf.pb \
  --input_arrays=convolution2d_1_input \
  --output_arrays=dense_3/BiasAdd \
  --input_shape=1,3,448,448`

**Comment by SanthoshRajendiran** [comment]
> > I use the command to convert .pb to .tflite
> > `tflite_convert --output_file=/home/wang/Downloads/deeplabv3_mnv2_pascal_train_aug/optimized_graph.tflite --graph_def_file=/home/wang/Downloads/deeplabv3_mnv2_pascal_train_aug/frozen_inference_graph.pb --inference_type=FLOAT --inference_input_type=QUANTIZED_UINT8 --input_arrays=ImageTensor --input_shapes=1,513,513,3 --output_arrays=SemanticPredictions –allow_custom_ops`
> > and it works
> > I use the pretrained model downloaded from [https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md](url)
> 
> @wwwecho do you try to inference using coverted tflite? I met runtime error `Failed to run on the given Interpreter: tensorflow/contrib/lite/kernels/depthwise_conv.cc:99 params->depth_multiplier * SizeOfDimension(input, 3) != SizeOfDimension(filter, 3) (0 != 32)Node number 30 (DEPTHWISE_CONV_2D) failed to prepare.`

Facing the same issue in Tensorflow 1.12.0

**Comment by SanthoshRajendiran** [comment]
This issue is closed. Please open this issue up

**Comment by pygosceles** [comment]
Support really needs to be added to tflite_convert for fully convolutional models (those having multiple **None**s in the input shape).

**Comment by pavanjava** [comment]
I have the same problem with tflite_convert while converting. so i checked with tflite_convert --help which is giving me the below problem i have tensorflow version 1.12. please see the log below.


(tensorflow) C:\Users\H156759>python
Python 3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'1.12.0'
>>> exit()

(tensorflow) C:\Users\H156759>tflite_convert --help
Traceback (most recent call last):
  File "C:\Pavans\Anaconda3\envs\tensorflow\Scripts\tflite_convert-script.py", line 6, in <module>
    from tensorflow.contrib.lite.python.tflite_convert import main
ModuleNotFoundError: No module named 'tensorflow.contrib.lite.python.tflite_convert'

**Comment by corlov** [comment]
Hi all!
I use tensorflow 1.11.0 and Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux.
I have trained a neural network and I want to use it on a mobile device (Android OS).
My main issue is that of I can't create tflite-file.
I have tried to change input parameters of tflite_convert. 
Sometimes I receive error messages at the moment of creating tflite-file:

```
#1 ValueError: Invalid tensors 'input' were found.

                tflite_convert \
                  --graph_def_file=/storage/src/basic_detector/veh_models_frozen_inference_graph.pb \
                  --output_file=veh_models.lite \
                  --input_format=TENSORFLOW_GRAPHDEF \
                  --output_format=TFLITE \
                  --input_shape=1,289,204,3 \
                  --input_array=input \
                  --output_array=final_result \
                  --inference_type=FLOAT \
                  --input_data_type=FLOAT
```
```
#2 ValueError: Invalid tensors 'ImageTensor' were found.

                tflite_convert \
                    --graph_def_file=/storage/src/basic_detector/veh_models_frozen_inference_graph.pb \
                    --output_file=veh_models.lite \
                    --inference_type=FLOAT \
                    --inference_input_type=QUANTIZED_UINT8 \
                    --input_array=normalized_input_image_tensor \
                    --input_shapes=1,289,204,3 \
                    --output_array=SemanticPredictions \
                    --allow_custom_ops
```


```
#3 ValueError: Invalid tensors 'ImageTensor' were found.

                tflite_convert \
                   --graph_def_file=/storage/src/tflite_files/poets_graph.pb \
                   --output_file=veh_models.lite \
                   --input_format=TENSORFLOW_GRAPHDEF \
                   --output_format=TFLITE \
                   --input_shape=1,224,224,3 \
                   --input_array=input \
                   --output_array=final_result \
                   --inference_type=FLOAT \
                   --input_data_type=FLOAT

```


Sometimes tflite-file is created but then a runtime error occurs on a mobile phone:

```
                tflite_convert \
                  --graph_def_file=/storage/src/basic_detector/veh_models_frozen_inference_graph.pb \
                  --output_file=veh_models.lite \
                  --input_format=TENSORFLOW_GRAPHDEF \
                  --output_format=TFLITE \
                  --input_shape=1,289,204,3 \
                  --input_arrays=Preprocessor\/sub \
                  --output_arrays=concat,concat_1 \
                  --inference_type=FLOAT \
                  --input_data_type=FLOAT

```

A tflite-file is created successfully but I receive runtime error:

```
W/System.err: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 1335, 11] and a Java object with shape [1, 10].
                                      at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:240)
                                      at org.tensorflow.lite.Tensor.copyTo(Tensor.java:116)
                                      at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:152)
                                      at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:216)
                                      at org.tensorflow.lite.Interpreter.run(Interpreter.java:195)
                                      at com.example.root.neuralnetworks01.MainActivity.classifyFrame(MainActivity.java:239)
                                      at com.example.root.neuralnetworks01.MainActivity$2.onClick(MainActivity.java:169)
                                      at android.view.View.performClick(View.java:4757)
                                      at android.view.View$PerformClick.run(View.java:19757)
                                      at android.os.Handler.handleCallback(Handler.java:739)
                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                      at android.os.Looper.loop(Looper.java:135)
                                      at android.app.ActivityThread.main(ActivityThread.java:5219)
                                      at java.lang.reflect.Method.invoke(Native Method)
                    W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

I don't understand meaning of input parameters for tflite_convert:
  --input_array
  --output_array
  --inference_type
  --input_data_type

I tried to repeat the example that is described in the article (https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2-tflite/#1) but it didn't work out.

I attached my config file used for training the network.
Maybe I need to consider and get some parameters from there to use them when I'm going to run tflite_convert.
Can you help me? Thanks.


[ssd_vehicle_model_config.txt](https://github.com/tensorflow/tensorflow/files/2855716/ssd_vehicle_model_config.txt)

**Comment by achowdhery** [comment]
SSD MobileNet model is for detection, where the conversion instructions are different as detailed in [blog](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193).
For classification, you would use MobileNet model as given in the codelab you referenced.
The meaning of the following can be found [here](https://www.tensorflow.org/lite/convert/cmdline_reference): 
--input_array
--output_array
--inference_type
--input_data_type

**Comment by JWSunny** [comment]
@Elites2017 hello, when i convert the mobilenet-ssd .pb file to tflite file, i get the same error about [None,None,None,3], what can i do to solve the problem? can i ues the export_tflite_ssd_graph to convert? thanks

**Comment by corlov** [comment]
> SSD MobileNet model is for detection, where the conversion instructions are different as detailed in [blog](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193).
> For classification, you would use MobileNet model as given in the codelab you referenced.
> The meaning of the following can be found [here](https://www.tensorflow.org/lite/convert/cmdline_reference):
> --input_array
> --output_array
> --inference_type
> --input_data_type

I have read the manual, but it seems there is not enough information about a list of possible values that could be set for input_arrays and output_arrays.
How can I understand what values for input_arrays and output_arrays I need to put there so those can correspond to my config file that was used for NN training?
In the manual, it says there should be names of activation tensors. To be honest  I don't understand what is it either.
What can I use for understanding what values need put there? Can you please point me somewhere for further reading? Thank you.

**Comment by corlov** [comment]
I have read this article (https://heartbeat.fritz.ai/neural-networks-on-mobile-devices-with-tensorflow-lite-a-tutorial-85b41f53230c) and it helped me.

I have reproduced exactly what was written there. It was my first step.
After this, I have tried to take my own dataset of pictures (14 classes of cars of different brands), repeated instructions, and got good results. It was strong impressive results for about 97% accuracy. I couldn't hope to see such results. 

This seems as incidental success more than logical, because before I had consumed a lot of time applied anoter way. I talk about the way discribed there https://github.com/tensorflow/models.

Now I'm confused a little bit. I had trained my own model for desktop computers and servers and it had worked and works. But it doesn't work for mobile. My issues occur with tflite_convert and some runtime errors I have described a little bit earlier pop up. Maybe my trained model is incompatible with mobile devices. I don't know. 

Why another way of creating pb-file is successful and gives positive results?
Can anybody help me understand the issue?

**Comment by mrgloom** [comment]
So it isn't possible to use fully convolutional models with input like `[None, None, None, 3]`?

**Comment by roymiles** [comment]
@mrgloom No, you must specify the spatial dimensions. The batch dimension gets reduced to 1 in tflite export.

Has anyone fixed this error:

> tensorflow/contrib/lite/kernels/depthwise_conv.cc:99 params->depth_multiplier * SizeOfDimension(input, 3) != SizeOfDimension(filter, 3) (0 != 6)Node number 23 (DEPTHWISE_CONV_2D) failed to prepare.

Any updates would be great. Tensorflow r1.12, training/testing works fine but tflite model fails.

Why is params->depth_multiplier * SizeOfDimension(input, 3) = 0 ??

**Comment by farmaker47** [comment]
Solved it with extra parameters inside code:

    import tensorflow as tf

    graph_def_file = "mask_rcnn_resnet50_atrous_coco_2018_01_28/frozen_inference_graph.pb"
    input_arrays = ["image_tensor"]
    output_arrays = ["detection_scores","detection_boxes","detection_classes","detection_masks"]

    converter = tf.lite.TFLiteConverter.from_frozen_graph(
            graph_def_file, input_arrays, output_arrays,input_shapes={"image_tensor":[1,600,600,3]})
    tflite_model = converter.convert()
    open("converted_model.tflite", "wb").write(tflite_model)

Although it cannot produce .tflite because it raises kmerge error "OperatorType::kMerge Found Sub as non-selected output from Switch, but only Merge supported"

**Comment by Davari393** [comment]
hi.
i dont now what should i put in my output and input array .
my code is:

import tensorflow as tf

graph_def_file = "./ssdlite_mobilenet_v2_coco_2018_05_09/frozen_inference_graph.pb"
input_arrays = ["image_tensor"]
output_arrays = ["MobilenetV2/Predictions/Reshape_2"]

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)


and my error is:

ValueError: Invalid tensors 'MobilenetV2/Predictions/Reshape_2' were found.


i have:
python = 3.7
tensorflow =1.15
protobuf=3.7

please help

**Comment by farmaker47** [comment]
@Davari393  check the .pb file with Tensorboard to see input and output array names

**Comment by Davari393** [comment]
> @Davari393 check the .pb file with Tensorboard to see input and output array names

can you tell me how?

**Comment by farmaker47** [comment]
@Davari393  check this link 
https://www.tensorflow.org/tensorboard/r1/overview

**Comment by Davari393** [comment]
thanks so much

**Comment by mrgloom** [comment]
It's better to use summarize_graph, it will print input and output nodes:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms#inspecting-graphs
https://stackoverflow.com/a/52029732/1179925

**Comment by akinpelu746** [comment]
hi.
my code is:

from tensorflow.contrib import lite
converter = lite.TFLiteConverter.from_keras_model_file( r'/content/drive/My Drive/inceptionv3-transfer-learning__fine_tune.model' ) # Your model's name
model = converter.convert()
file = open( 'model.tflite' , 'wb' ) 
file.write( model )

ValueError: None is only supported in the 1st dimension. Tensor 'input_1' has invalid shape '[None, None, None, 3]'.

what will my input array be?

**Comment by akinpelu746** [comment]
hi.
my code is:

from tensorflow.contrib import lite
converter = lite.TFLiteConverter.from_keras_model_file( r'/content/drive/My Drive/inceptionv3-transfer-learning__fine_tune.model' ) # Your model's name
model = converter.convert()
file = open( 'model.tflite' , 'wb' )
file.write( model )

ValueError: None is only supported in the 1st dimension. Tensor 'input_1' has invalid shape '[None, None, None, 3]'.

what will my input_array,input_shape and output_array be?

**Comment by hzqqqqq** [comment]
> > @wwwecho do you try to inference using coverted tflite? I met runtime error `Failed to run on the given Interpreter: tensorflow/contrib/lite/kernels/depthwise_conv.cc:99 params->depth_multiplier * SizeOfDimension(input, 3) != SizeOfDimension(filter, 3) (0 != 32)Node number 30 (DEPTHWISE_CONV_2D) failed to prepare.`
> 
> Facing the same issue in Tensorflow 1.12.0
@SanthoshRajendiran  @wwwecho   sorry for my bad English. 
When I convert the mobilenetv2+deeplabv3+ model to  a tflite file and then deploy it to Andriod, I face the same issue:
Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/depthwise_conv.cc:108 params->depth_multiplier * SizeOfDimension(input, 3) != SizeOfDimension(filter, 3) (0 != 32)Node number 16 (DEPTHWISE_CONV_2D) failed to prepare.

Can you give me some suggestions? Thanks.

**Comment by erolgerceker** [comment]
> tflite_convert --output_file=/home/wang/Downloads/deeplabv3_mnv2_pascal_train_aug/optimized_graph.tflite --graph_def_file=/home/wang/Downloads/deeplabv3_mnv2_pascal_train_aug/frozen_inference_graph.pb --inference_type=FLOAT --inference_input_type=QUANTIZED_UINT8 --input_arrays=ImageTensor --input_shapes=1,513,513,3 --output_arrays=SemanticPredictions –allow_custom_ops

i got this error.

ValueError: Invalid tensors 'ImageTensor' were found.
