### ISSUE TITLE
Initialize variable from TF Hub/MobilNet checkpoint fails for "expanded_conv_15/expand/weights" with Container localhost does not exist. 

### ISSUE THREAD

**Issue by dchichkov** [tensorflow/tensorflow#20803]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Collab
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.9_rc2
- **Python version**:  N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:   https://colab.research.google.com/drive/1X2TqjiK3ctRWCGEmJ3Id2VbbL64MWuzT

### Describe the problem
Initialize variable from TF Hub/MobilNet checkpoint fails for "expanded_conv_15/expand/weights" with Container localhost does not exist. 

### Source code / logs
Can be executed at https://colab.research.google.com/drive/1X2TqjiK3ctRWCGEmJ3Id2VbbL64MWuzT
Logs: [tflog.txt](https://github.com/tensorflow/tensorflow/files/2195060/tflog.txt)

```
!wget https://www.tensorflow.org/images/daisies.jpg
import tensorflow as tf, tensorflow_hub as hub

def read_tensor_from_image_file(file_name, height, width, mean=0, std=128):  
  file_reader = tf.read_file(file_name, name="file_reader")
  image_reader = tf.image.decode_jpeg(file_reader, channels=3, name="jpeg_reader")
  float_caster = tf.cast(image_reader, tf.float32)
  dims_expander = tf.expand_dims(float_caster, 0)
  resized = tf.image.resize_bilinear(dims_expander, [height, width])
  normalized = tf.divide(tf.subtract(resized, [mean]), [std])
  return normalized

module = hub.Module("https://tfhub.dev/google/imagenet/mobilenet_v2_140_224/feature_vector/2")
height, width = hub.get_expected_image_size(module)
image = read_tensor_from_image_file("daisies.jpg", height, width)
features = module(image)

sess = tf.Session()
result = sess.run(features)
print(result)

```

FailedPreconditionError: Error while reading resource variable module_4/MobilenetV2/expanded_conv_15/expand/weights from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/module_4/MobilenetV2/expanded_conv_15/expand/weights)
	 [[Node: module_4_apply_default/MobilenetV2/expanded_conv_15/expand/Conv2D/ReadVariableOp = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](module_4/MobilenetV2/expanded_conv_15/expand/weights)]]

**Comment by dchichkov** [comment]
Ah, I see. It needs sess.run(tf.global_variables_initializer()). The following code seem to work:

```
!wget https://www.tensorflow.org/images/daisies.jpg
import tensorflow as tf, tensorflow_hub as hub, numpy as np

def read_tensor_from_image_file(file_name, height, width, mean=0, std=128):  
  file_reader = tf.read_file(file_name, name="file_reader")
  image_reader = tf.image.decode_jpeg(file_reader, channels=3, name="jpeg_reader")
  float_caster = tf.cast(image_reader, tf.float32)
  dims_expander = tf.expand_dims(float_caster, 0)
  resized = tf.image.resize_bilinear(dims_expander, [height, width])
  normalized = tf.divide(tf.subtract(resized, [mean]), [std])
  return normalized


module = hub.Module("https://tfhub.dev/google/imagenet/mobilenet_v2_140_224/feature_vector/2")
height, width = hub.get_expected_image_size(module)
image = read_tensor_from_image_file("daisies.jpg", 224, 224)
features = module(image)

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  sess.run(tf.tables_initializer())

  result = sess.run(features)
  print(np.squeeze(result))
```

Still, seem like a bug to me, as the:
 * requirement to run tf.global_variables_initializer is not documented
 * error message is very poor
 * no minimalistic sample code is available

**Comment by tatianashp** [comment]
@dchichkov Glad to see that you found that issue in your code yourself. The example on the TFHub Overview [page](https://www.tensorflow.org/hub/) shows minimalistic sample code including the call to tf.global_variables_intializer(). 

We welcome contributions that help us to improve TensorFlow. If you feel that additional documentation  would be helpful please feel free to submit a PR.

**Comment by advahad** [comment]
Having the same issue, any ideas?

**Comment by tatianashp** [comment]
Have you tried adding  sess.run(tf.global_variables_initializer())?

**Comment by ingramator** [comment]
This is completely broken, you can't even load a TF hub model it will load with sess.run(tf.global_variables_initializer())? and then produce completely random results
