### ISSUE TITLE
install from source fails on Mac

### ISSUE THREAD

**Issue by apcode** [tensorflow/tensorflow#2081]
The installation of tensorflow from source fails on Mac.

The step it fails on is ./configure. The configure script looks like it has never been written to work on the Mac, even though the install guide suggests running ./configure in the section for Mac installation.

The script contains these lines which is where the failure happens:

  if [ -e $CUDA_TOOLKIT_PATH/lib64/libcudart.so$TF_CUDA_EXT ]; then
    break
  fi
  echo "Invalid path to CUDA $TF_CUDA_VERSION toolkit. $CUDA_TOOLKIT_PATH/lib64/libcudart.so$TF_CUDA_EXT cannot be found"

--
Of course the Mac doesn't have .so libs, or a lib64 dir. For example, my Cuda installation is at /usr/local/cuda, with /usr/local/cuda/lib/ containing *.dylib files including libcudart.dylib.

**Comment by vrv** [comment]
Thanks for the report: we do not yet support GPUs on OS X, but https://github.com/tensorflow/tensorflow/pull/664 is adding support for it, stay tuned.  Follow on that thread, will close for now!
