### ISSUE TITLE
Java SavedModelBundle.load do not support long path in windows

### ISSUE THREAD

**Issue by iron9light** [tensorflow/tensorflow#20817]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10 64bit.
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:
### Describe the problem
Java SavedModelBundle.load do not support long path in windows.
It will throw something like:
```
org.tensorflow.TensorFlowException: NewRandomAccessFile failed to Create/Open: C:\Projects\veryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryverylongpath/variables/variables.data-00000-of-00001 : The system cannot find the path specified.
; No such process
	 [[Node: save_1/RestoreV2 = RestoreV2[_output_shapes=[<unknown>, <unknown>, <unknown>, <unknown>, <unknown>, ..., <unknown>, <unknown>, <unknown>, <unknown>, <unknown>], dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]
	at org.tensorflow.SavedModelBundle.load(Native Method)
```
I shorten the model path, everything works fine.
I enabled long path based on this [doc](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file). It still has this issue.

I know it's a limit of Windows OS. I just wandering is there any way to let the C++ part bypass this limit?

**Comment by asimshankar** [comment]
Thanks for the report @iron9light , I'm guessing you're talking about the path size limitations described in https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation ?

The TensorFlow maintainers are unlikely to have the cycles to investigate a fix for this in the short term, so I'm marking this as "Contributions Welcome" in case anyone else in the community would like to give it a shot.

Thanks!

**Comment by iron9light** [comment]
Fine!

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
