### ISSUE TITLE
Grappler warning and segfault

### ISSUE THREAD

**Issue by megagosha** [tensorflow/tensorflow#20823]
### System information
- **Have I written custom code**: I used this TensorFlow [patch](https://gist.github.com/Willian-Zhang/a3bd10da2d8b343875f3862b2a62eb3b).
- **OS Platform and Distribution**: macOS 10.13.6 and 10.13.5 before
- **TensorFlow installed from**: Source
- **TensorFlow version**: ('v1.8.0-0-g93bc2e2072', '1.8.0')
- **Python**: 2.7
- **Bazel version**: 0.13.1
- **GCC/Compiler**: from Xcode 9.2
- **CUDA/cuDNN**: 9.1/7.0.5
- **GPU model and memory**: NVIDIA 1080 8.00GiB
- **Exact command to reproduce**: Cifar 10 training from examples

Hardware: 
MacBook Pro 13,3 eGPU 1080
NVIDIA Web Driver 387.10.10.10.40.105 
CUDA Driver 396.148 
CUDA 9.1 Toolkit 
cuDNN 7.0.5 
Python 2.7 
NCCL 2.1.15 
Xcode 9.2

import tensorflow as tf
tf.test.is_gpu_available():
`tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:859] OS X does not support NUMA - returning NUMA node zero
tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:46:00.0
totalMemory: 8.00GiB freeMemory: 2.32GiB
tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/device:GPU:0 with 2025 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:46:00.0, compute capability: 6.1)
True`

When I try to run something I get this error messages with segfault in the end:

`Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:859] OS X does not support NUMA - returning NUMA node zero
tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:46:00.0
totalMemory: 8.00GiB freeMemory: 3.39GiB
tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3118 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:46:00.0, compute capability: 6.1)
E tensorflow/core/grappler/clusters/utils.cc:127] Not found: TF GPU device with id 0 was not registered
Segmentation fault: 11`

In other program I tried to reduce per_process_gpu_memory_fraction and batch size so it crashed after first batch with the same error code. I have seen people encounter same grappler warning without segfault. 

Any idea how to resolve this? Any help appreciated!! Thank you!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
OS Platform and Distribution
CUDA/cuDNN version

**Comment by megagosha** [comment]
Any ideas?

**Comment by smoothdvd** [comment]
same error with CUDA 9.2 and cuDNN 7.1

**Comment by megagosha** [comment]
@smoothdvd Could you share your hardware and software info?

**Comment by smoothdvd** [comment]
@megagosha 
```
NVIDIA driver                                                                                                            [387.10.10.10.40.105] CUDA drivers                                                                                                            [396.148]
CUDA developer drivers                                                                                           [396.148]
CUDA toolkit                                                                                                              [9.2.148]
CUDA samples                                                                                                           [9.2.148]

macOS version                                                                                                           [10.13.6]
macOS build                                                                                                               [17G65]

eGPU  GTX 1080

python 3.6.x

iMac (Retina 5K, 27-inch, Late 2014)
```

**Comment by rohan100jain** [comment]
We don't support GPU's on MacOS as of now.  This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
