### ISSUE TITLE
build doc enhancements

### ISSUE THREAD

**Issue by crusaderky** [tensorflow/tensorflow#2083]
The installation guide https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html could use the following improvements:

1. In the "pip installation" and "virtualenv installation" section, should specify that the wheel package is *specifically* for Python 3.4. 
As a side note, a wheel package for Python 3.5 would be greatly appreciated.

2. In build from sources -> install other dependencies:
Replace:
    $ sudo apt-get install python-numpy swig python-dev
With:
    For Python 2.7:
    $ sudo apt-get install python-numpy swig python-dev python-wheel
    For Python 3.x:
    $ sudo apt-get install python3-numpy swig python3-dev python3-wheel

3. In the build from sources section: specify that the compilation is VERY memory hungry (it won't fit on 8GB RAM), and suggest to add --local_resources 2048,.5,1.0 to the bazel build command as a workaround.
Alternatively, change the bazel script to detect the available RAM and scale down automatically.

**Comment by vrv** [comment]
Thanks for the suggestions!

Our documentation is open source too, so feel free to send us a PR for these!

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md is the file to edit.

**Comment by martinwicke** [comment]
For 3., it would be best to note that you can use -j X to throttle bazel. It's easier than local_resources and gets the job done.

**Comment by omtcyfz** [comment]
I believe this should be closed now. Addressed comment 2 in #4410, and as for the first one: I believe there are wheel packages for 3.5 now, too.
