### ISSUE TITLE
[Feature request] Allow `tf.estimator.train_and_evaluate` to support chief and evaluator working with different `model_dir`

### ISSUE THREAD

**Issue by fanshiqing** [tensorflow/tensorflow#20831]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Cent OS
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.4
- **Python version**: 2.7.5
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: NA

### Describe the problem
Currently `tf.estimator.train_and_evaluate` makes it easy to use an Estimator to perform both training and evaluation, possibly in a distributed environment. 

 In my case, `evaluator` have to 

  (1) read from chief worker's  `model_dir`,
  (2) do some extra processing,
  (3) generate **new model_dir** , 
  (4) finally concrete evaluation is based on the **new model_dir**. 

However, `train_and_evaluate` only supports one estimator **with single `model_dir`**,  i.e. `chief worker` and `evaluator` shares the same `checkpoint path`, which makes above requirements imcompatible. It would be ideal if we could perhaps pass more than one `model_dir` to train_and_evaluate to handle the above scenes.

Or maybe there are some workarounds to deal with this problem?

**Comment by wangsiyu** [comment]
The train_and_evaluate interface does not seems to be flexible. Sometimes the configuration of training and evaluation must be different. Currently we construct two different estimators to do these. Does this interface will be changed to support more complex situations ? @xiejw @ispirmustafa

**Comment by xiejw** [comment]
This is not part of the design goal of train_and_evaluate. My suggestion would writing your own loop to do that.
