### ISSUE TITLE
 Check failed: message->ParseFromZeroCopyStream(&adaptor) 

### ISSUE THREAD

**Issue by neverPick** [tensorflow/tensorflow#2084]
I replaced the pb&labels.txt files in asset in android demo with what I retrained in examples/image_retraining . I built the demo successfully,but when running ,it shut down,and toast the error message: 
` Check failed: message->ParseFromZeroCopyStream(&adaptor) `
`Fatal signal 6 (SIGABRT), code -6 in tid 14617 (ImageListener)`
I have no idea about this,please give some advice.

**Comment by neverPick** [comment]
what is the difference between inceptionv3 and inception5h? why I canot use it in android demo?

**Comment by neverPick** [comment]
close it,they are some models,but different of output_layer name.

**Comment by l4chong** [comment]
@neverPick just wondering, what did you end up doing?

**Comment by andrewharp** [comment]
@l4chong You can edit [TensorflowImageListener.java](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/examples/android/src/org/tensorflow/demo/TensorflowImageListener.java?q=tensorflow/examples/android+inception&sq=package:piper+file://depot/google3+-file:google3/(experimental%7Cobsolete)&l=45) according to the comment there to adapt it to handle Inception v3.

**Comment by hongyehenry** [comment]
@andrewharp what parameters need to change to adapt the retrained data t work on Android Demo?

**Comment by barantes** [comment]
I believe the params to be modified are:
  private static final int NUM_CLASSES = 256;
  private static final int INPUT_SIZE = 224;
  private static final int IMAGE_MEAN = 117;

But I'm not sure what values to use (though I suspect that NUM_CLASSES should correspond to the number of lines in the labels file). I'm also having the same error message (Check failed: message->ParseFromZeroCopyStream(&adaptor)) when trying to use my own model in the demo.

**Comment by hongyehenry** [comment]
@barantes I opened a new issue here https://github.com/tensorflow/tensorflow/issues/3599
to declare my problem. Let me know if you find any solutions.

**Comment by l4chong** [comment]
It's working for me, with a retrained model. 

  private static final int NUM_CLASSES = 7;
  private static final int INPUT_SIZE = 299;
  private static final int IMAGE_MEAN = 128;
  private static final float IMAGE_STD = 128;
  private static final String INPUT_NAME = "Mul:0";
  private static final String OUTPUT_NAME = "final_result:0";

you have to change the NUM_CLASSES with the number of labels you have
