### ISSUE TITLE
BUG: tf.keras.layers and tf.REUSE.AUTO fail to share parameters in 1.9.0

### ISSUE THREAD

**Issue by Schnabbel** [tensorflow/tensorflow#20842]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
v1.9.0-0-g25c197e023 1.9.0
- **Python version**: 
3.6
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
run MWE under 1.9.0, which works fine for 1.8.0

### Describe the problem
I think a bug was introduced, where `tf.keras.layers.Conv3D` in context of `tf.REUSE.AUTO` no longer works as intended (.e.g no parameter-sharing is performed).
This might be caused by the bugfix mentioned in the [release notes](https://github.com/tensorflow/tensorflow/releases/tag/v1.9.0) (Using tf.keras.layers with custom variable scopes).

This bug seemingly does not affect the `tf.keras.layers.Lambda` layer, as outlined by the MWE, where `tf.contrib.layers.instance_norm` and `tf.layers.conv3d` share paramters as intended.

### Source code / logs
MWE which runs fine under 1.8.0 but fails to yield complete parameter sharing under 1.9.0.

```
import tensorflow as tf

Conv3D = tf.keras.layers.Conv3D
Lambda = tf.keras.layers.Lambda
Activation = tf.keras.layers.Activation
tf_instance_norm = tf.contrib.layers.instance_norm    

def Conv_block_keras(input_layer, n_filters, kernel=(3, 3, 3), 
               padding='same', strides=(1, 1, 1)):

    with tf.variable_scope('conv_block'):
        #layer = Conv3D(n_filters, kernel, padding=padding, strides=strides)(input_layer) # does not work
        #layer = Lambda(lambda x: Conv3D(n_filters, kernel, padding=padding, strides=strides)(x))(input_layer) # does not work
        layer = Lambda(lambda x: tf.layers.conv3d(inputs=x, filters=n_filters, padding=padding, strides=strides, kernel_size=kernel))(input_layer)
        layer = Lambda(lambda x: tf_instance_norm(inputs=x, data_format='NCHW'))(layer)
        return Activation('relu')(layer)

with tf.variable_scope('reuse', reuse=tf.AUTO_REUSE):
    conv_1 = Conv_block_keras(tf.zeros(shape=[1,1]+[128]*3), 3)
    vars_conv_1 = [x.name for x in tf.global_variables(scope='reuse')]
    conv_2 = Conv_block_keras(tf.zeros(shape=[1,1]+[128]*3), 3)
    vars_conv_2 = [x.name for x in tf.global_variables(scope='reuse')]
    print(vars_conv_1 == vars_conv_2)
```

**Comment by omalleyt12** [comment]
Thanks for the code, I'm getting the same behavior on my end. It looks like `tf.keras` is incrementing the name of the layer unconditionally every time a layer of the same type is created. As per the release note you mentioned, this might be intended behavior, I'll check with other members of the team and get back. 

In the meantime, one way to have variable sharing with `tf.keras` is to create the layer once and then call it multiple times:

```python
conv = tf.keras.Conv3D(32, (3, 3, 3))

out = conv(x)
out_2 = conv(y) # this will share variables with the first call
```

**Comment by omalleyt12** [comment]
Confirmed that this is intended behavior going forward. Preferred way to reuse variables in `tf.keras` is to construct the object once and then call it multiple times

**Comment by Schnabbel** [comment]
Okay, but then shouldn't the name of the `Lambda` be incremented unconditionally as well?
It does not do so in the above MWE, and this then is ambiguous behavior to me, as `Lambda` should inherit from `tf.keras.layers.Layer` just the same as `Conv3D`

**Comment by omalleyt12** [comment]
The *name* of the ```Lambda``` layer is getting updated unconditionally, but ```Lambda``` layers are completely unaware of any variables you create inside of them, so the variable creation defaults to using ```variable_scope``` and thus gets reused. This is one of the reasons Keras recommends not creating variables of performing any stateful operations inside of ```Lambda``` layers. The best way to do that is to create your own ```Layer``` subclass

**Comment by Schnabbel** [comment]
Got it thanks :)

**Comment by Schnabbel** [comment]
Okay, so I am still a bit confused of what the expected behavior is for `tf.keras.layers`, `tf.layers` and `variable_scopes` and `tf.get_variable` with regard to the future.

As of 1.9.0, the `tf.keras.layers.Layer` and all subclasses no longer allow for [variable reusing, but instead use a "pared-down"](https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/python/training/checkpointable/util.py#L193) version of `tf.get_variable`. Furthermore, the `tf.layers` as well as `tf.contrib.layers` still allow for reusing with `tf.variable_scopes` and perform all required checks.

However, according to #14703, `tf.layers` is set to be removed in the future. 

I would be very delighted, if you could give a roadmap on what's the future of a `high-level layers API` for tensorflow (as additionally requested here #16182, where use of tf.layers.api together with estimators are suggested as best practice).

**Comment by omalleyt12** [comment]
```tf.keras.layers``` is the preferred high-level layers API for Tensorflow going forward. You're right, for historical reasons ```tf.layers``` still allows for reuse with ```tf.variable_scopes```, but Keras layers don't as of 1.9.0 and I don't expect they will going forward.

Some roadmap decisions are still being made, most of the updates for these types of things are sent through our [developer mailing lists](https://www.tensorflow.org/community/lists), you can check out the link to subscribe

Hope that helps!

**Comment by Schnabbel** [comment]
Okay, one last thing:
Is there a way to intermingle `tf.layers` and `tf.contrib.layers` with `tf.keras.layers` and get the expected `tf.keras.Model` behavior? Because i think this was broken upon in 1.9.0. I tried wrapping the above MWE as a `tf.keras.Model()` by subclassing `tf.keras.Model()`. Code is attached, but expected behavior of `tf.keras`, which is parameter-sharing by sharing the `Model` object is not achieved.

In 1.8.0, it was possible to do this simply by wrapping `tf.layers` and `tf.contrib.layers` inside a `Lambda` layer, as I did in the initial comment. If this is the case, I would like to add a Feature Request for this.

```
import tensorflow as tf

Conv3D = tf.keras.layers.Conv3D
Lambda = tf.keras.layers.Lambda
Activation = tf.keras.layers.Activation
tf_instance_norm = tf.contrib.layers.instance_norm    

class MyModel(tf.keras.Model):

  def __init__(self, n_filters=1, kernel=3, padding='same', strides=1):
    super(MyModel, self).__init__(name='my_model')
    self.conv = Conv3D(n_filters, kernel, padding=padding, strides=strides, data_format='channels_first')
    self.instance_norm = Lambda(lambda x: tf_instance_norm(inputs=x, data_format='NCHW'))

  def call(self, inputs):
    x = self.conv(inputs)
    x = self.instance_norm(x)
    x = self.conv(x)
    x = self.instance_norm(x)
    return x

with tf.variable_scope('reuse', reuse=tf.AUTO_REUSE) as scope:

    model = MyModel()
    
    outputs_1 = model(tf.zeros(shape=[1,1]+[128]*3))
    vars_conv_1 = [x.name for x in tf.global_variables(scope='reuse')]
    outputs_2 = model(tf.zeros(shape=[1,1]+[128]*3))
    vars_conv_2 = [x.name for x in tf.global_variables(scope='reuse')]
    print(vars_conv_1)
    print(vars_conv_2)
```

**Comment by vvekic** [comment]
So the new practice is to define layers and then call them with the inputs. All further calls to the same instance of a layer results in underlying variables being reused.
But I'd like to use predefined tf.keras models (e.g. `tf.keras.applications.resnet50`) and define them multiple times (using different devices, for multi-GPU). This simply doesn't work now as the predefined models themselves define new instances of each layer each time they are created.

Is there a way out of this?
