### ISSUE TITLE
Will cycle-gan have a Estimator implementation like tf.contrib.gan.estimator.GANEstimator?

### ISSUE THREAD

**Issue by joneepenk** [tensorflow/tensorflow#20868]
or can GanEstimator be used on cycle-gan for training/predicting?

Thanks.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by joel-shor** [comment]
We don't have immediate plans to add a CycleGAN estimator, but we're going to add a StarGAN estimator within the week.

It should be straightforward to extend CycleGAN to CycleGANEstimator by following how GANEstimator is made; feel free to send me a pull request and I'll approve it.

**Comment by joneepenk** [comment]
@joel-shor Thanks for information. Surely I will send a pull request while i finish it.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by joel-shor** [comment]
Expect a StarGANEstimator in the next week.

Also, any progress on the GANEstimator, @joneepenk ?

**Comment by joneepenk** [comment]
sorry, the work on CycleGANEstimator is suspended for now, I am trapped in something else and will back to it asap.

**Comment by Saduf2019** [comment]
Please refer to the updated [link](https://www.tensorflow.org/tutorials/generative/cyclegan), moving this to closed status.
