### ISSUE TITLE
NCCL not detected on Arch Linux

### ISSUE THREAD

**Issue by Mukundan314** [tensorflow/tensorflow#20879]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch Linux
- **TensorFlow installed from (source or binary)**: source (r1.9)
- **TensorFlow version (use command below)**: 1.9
- **Python version**: 3.7.0
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**: 8.1.1
- **CUDA/cuDNN version**: 9.2/7.1.4
- **NCCL version**: 2.2.13
- **GPU model and memory**: Nvidia GTX 1060 3GB
- **Exact command to reproduce**: ./configure

### Problem
`./configure` does not detect my `libnccl.so.2` located at `/opt/cuda/lib64`.

#### Output of `./configure`
```
Please specify the location of python. [Default is /home/mukundan/.pyenv/versions/machine_learning/bin/python]: 


Found possible Python library paths:
  /home/mukundan/.pyenv/versions/machine_learning/lib/python3.7/site-packages
Please input the desired Python library path to use.
Default is [/home/mukundan/.pyenv/versions/machine_learning/lib/python3.7/site-packages]

Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: 
jemalloc as malloc support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Google Cloud Platform support? [Y/n]: 
Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [Y/n]: 
Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Amazon S3 File System support? [Y/n]: 
Amazon S3 File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Apache Kafka Platform support? [Y/n]: 
Apache Kafka Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]: 
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with GDR support? [y/N]: 
No GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: 
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 9.0]: 9.2


Please specify the location where CUDA 9.2 toolkit is installed. Refer to README.md for more details. [Default is /opt/cuda]: 


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7.0]: 7.1.4


Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is /opt/cuda]:


Do you wish to build TensorFlow with TensorRT support? [y/N]: 
No TensorRT support will be enabled for TensorFlow.

Please specify the NCCL version you want to use. [Leave empty to default to NCCL 1.3]: 2.2.13


Please specify the location where NCCL 2 library is installed. Refer to README.md for more details. [Default is /opt/cuda]:


Invalid path to NCCL 2 toolkit, /opt/cuda/lib/libnccl.so.2 or /opt/cuda/include/nccl.h not found. Please use the O/S agnostic package of NCCL 2
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
CUDA/cuDNN version

**Comment by MaeThird** [comment]
modify the code ` nccl_lib_path = 'lib/libnccl.so.%s' % tf_nccl_version` round line 1135 of **configure.py**  or put your so into `/opt/cuda/lib` What's more **Don't forget the license file**!

**Comment by Mukundan314** [comment]
Thanks

**Comment by carusyte** [comment]
or add this line in the ~/.profile to set the environment variable, in Ubuntu, other OS varied accordingly. Actual nccl installation path is also varied
`export NCCL_INSTALL_PATH="$CUDA_HOME/targets/x86_64-linux"`

**Comment by lilei461536135** [comment]
Edit configure.py line 1136 nccl_lib_path = 'lib/libnccl.so.%s' % tf_nccl_version to nccl_lib_path = 'lib64/libnccl.so.%s' % tf_nccl_version. (I installed nccl in /usr/local/cuda-9.2/lib64/)
