### ISSUE TITLE
load_op_library fails with undefined symbol in 1.7, but not 1.1

### ISSUE THREAD

**Issue by iandreariley** [tensorflow/tensorflow#20899]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux SLES 12.1
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 3.5.4 (as Anaconda environment)
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: 4.8.5 (for custom Op)
- **CUDA/cuDNN version**: 7.1.2
- **GPU model and memory**: Nvidia Tesla M40 11443MiB
- **Exact command to reproduce**: `tf.load_op_library('zero_out.so')`

### Describe the problem
When I follow the instructions on the [adding a new op page](https://www.tensorflow.org/extend/adding_an_op#top_of_page), loading the example `zero_out.so` fails with `tensorflow.python.framework.errors_impl.NotFoundError: zero_out.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv` in tensorflow 1.7. However, the same procedure succeeds with tensorflow 1.1, python 3.5.2.   
I have seen similar issues (e.g. #9137), however adding `-D_GLIBCXX_USE_CXX11_ABI=0` doesn't help (and probably shouldn't, as GCC < 5). The closest issue is seemingly #17619 since the problem seems to be with the linker being unable to find the correct library at run time.

### Source code / logs
Zero-out source code is available on the [adding a new op page](https://www.tensorflow.org/extend/adding_an_op#top_of_page).

**Full Traceback**

```sh
>>> import tensorflow as tf
>>> tf.load_op_library('zero_out.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/TF17/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/anaconda3/envs/TF17/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: zero_out.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
```

**Comment by iandreariley** [comment]
Moving to a different system with a single conda environment solved the issue - so the issue is unrelated to tensorflow and is perhaps an issue with having multiple tensorflow versions in the same machine. Closing issue.

I still haven't figured out how to point tensorflow at the right libraries in the system with multiple environments, but if I figure out a solution, I will post it here.

**Comment by iandreariley** [comment]
**update**: This appears not due to having multiple environments, but that tensorflow binaries that I installed via conda were built with GCC 5.x using the C++11 ABI

User defined op libraries (in this case, zero_out.so) are linked against `/path/to/tf/libtensorflow_framework.so`. If I check the symbol table of that library in the failing conda env (tf17) for `_ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv`, nothing shows up. However, if I remove the “Ev: at the end, I get this:

```sh
iriley@iriley_cpu> nm libtensorflow_framework.so | grep _ZN10tensorflow8internal21CheckOpMessageBuilder9NewString
000000000055e75c T _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev
```

Note the `cxx11` towards the end of the symbol name. If you have GCC 5.x, setting -`D_GLIBCXX_USE_CXX11_ABI=1` should fix the problem.

**Comment by iandreariley** [comment]
Per ContinuumIO/anaconda-issues/issues/9826, all anaconda packages are built with the C++11 ABI. A solution that worked for me (again, per the mentioned issue) is to use the anaconda `gxx_linux-64` compiler to compile the op.

**Comment by debapriyamaji** [comment]
I faced a similar situation while using the conda distribution. Installing tensorflow from pip solved the problem. That is probably built with gcc4.8.

**Comment by amirmgh1375** [comment]
you just need to add *.so compiled file generated by model implementation.
as follows add this line before session and import meta graph.
tf.load_op_library('<compiled_filename>.so')
this function add a new op in tensorflow runtime.
for example. i compiled a model that contains a RoiPooling layer and generated roi_pooling.so file. so that i added this line to my code
tf.load_op_library('op/roi_pooling.so')

and finally it works : )
