### ISSUE TITLE
Add support for reading HDF5

### ISSUE THREAD

**Issue by ilblackdragon** [tensorflow/tensorflow#2089]
HDF5 is a popular format to store complicated datasets (alternative to proto files).
Also has different random seeking functionality and is widely used in scientific community.

This is FR for:
* Adding HDF5 reader.
* Support of HDF5 in tf.learn.

(originally from https://github.com/tensorflow/skflow/issues/52)

**Comment by sun9700** [comment]
May be the hdf5 reader prefer to read from a single huge hdf5 file, instead of a file-name queue.
The bioinformatics data often stores in one mat/gtcx/hdf5 file.
However, open it with h5py.File as numpy array and feed the tf.placeholder is OK for now.

**Comment by jreadey** [comment]
I'll be happy to help with any questions regarding the best way to utilize HDF5.

**Comment by pydevhacker** [comment]
I would like to work on this issue. I am new here and looking for help to get started.

**Comment by terrytangyuan** [comment]
This can be closed. See an example in examples/skflow.

**Comment by ilblackdragon** [comment]
Thanks @terrytangyuan!

**Comment by sun9700** [comment]
The skflow is not suitable for out-of-core hdf5 data, some hdf5 or matlabv7.3 data are the same size as ImageNet

**Comment by sun9700** [comment]
@ilblackdragon The skflow is not suitable for out-of-core hdf5 data, some hdf5 or matlabv7.3 data are the same size as ImageNet. Maybe a reader randomly acesss hdf5 data and feed the model with reasonbale memory is still necessary.

**Comment by ilblackdragon** [comment]
@sun9700 Yes, the out-of-core doesn't work yet. Feel free to file a separate Feature Request about it (support streaming from hdf5) - and of cause PR will be highly welcome :)
