### ISSUE TITLE
Yann LeCun's web page is not available - cannot download data from there is there a mirror?

### ISSUE THREAD

**Issue by damiand** [tensorflow/tensorflow#209]
Yan Lecun''s web page is not available - cannot download data from there is there a mirror?

python tensorflow/models/image/mnist/convolutional.py attempts to download from http://yann.lecun.com/exdb/mnist/

For the past hour or so yann.lecun.com is not responding...

**Comment by Foorack** [comment]
The port on the address 'yann.lecun.com' is not listening. Either someone stopped the webserver (unlikely) or it died because of overload (much more likely). After more research I have found that no known port is responding and it might very well have been the whole server machine which have gone down. The domain is owned by 'PERFECT PRIVACY LLC' and reverse IP domain check reports that only one domain is hosted at the same location.

Personally, to me this sounds like it is some ones private server and I think that the data located there related should be copied or transferred over to a more public mirror

**Comment by damiand** [comment]
Thanks!

- Damian

**Comment by Foorack** [comment]
@damiand I have uploaded the training data to a Github repository which can be used as a mirror until the old website comes back up or a TensorFlow official announces a new location.

The **temporary** mirror can be found (with hash file checksums) here:
https://github.com/Foorack/tensorflow-trainingdata

Kind Regards,
~Foorack

**Comment by damiand** [comment]
Cool. Thanks!

- Damian

@DamianDanowski
(703) 716-7474

**Comment by ebrevdo** [comment]
Page looks to be back up, so I'm closing this for now.

**Comment by jeremija** [comment]
The page seems to be down again from here...

**Comment by Foorack** [comment]
@jeremija I have unfortunately deleted my mirror as the problem was solved. Please tell me if you want me to upload it again.

**Comment by Foorack** [comment]
@jeremija Actually wayback-machine should work! Tell me how it went if you decide to try it. :)

**Comment by jeremija** [comment]
@Foorack wayback-machine [doesn't seem to be working](https://web.archive.org/web/*/https://github.com/Foorack/tensorflow-trainingdata), but thanks anyway! You don't have to reupload for me, I just wanted to raise the issue.

**Comment by davebiagioni** [comment]
Like @jeremija, I am also unable to access the data set from either http://yann.lecun.com/exdb/mnist/ or wayback-machine.  Just FYI!

**Comment by jeremija** [comment]
There are actually snapshots on the wayback machine available [here](https://web.archive.org/web/20160117040036/http://yann.lecun.com/exdb/mnist/). I was looking at Foorack's repository only at first...

**Comment by davebiagioni** [comment]
Great, yes that link seems to work.  Thanks!

**Comment by Foorack** [comment]
OK @jeremija davebiagioni, great that you got it working :+1:

**Comment by hudvin** [comment]
Same for me.

**Comment by RuiZhang1993** [comment]
It seems that the page is not available again...

**Comment by alwint3r** [comment]
@RuiZhang1993 It's still not available now. But [this link](https://web.archive.org/web/20160117040036/http://yann.lecun.com/exdb/mnist/) is still available, and you can download the data from there. Thanks a lot @jeremija!

**Comment by daochou** [comment]
just remove the s , use http , hava a try http://yann.lecun.com/exdb/mnist/
