### ISSUE TITLE
Preinstalled tensorflow on ubuntu image 

### ISSUE THREAD

**Issue by anaskoara** [tensorflow/tensorflow#20903]
Hi 
Is There any Ubuntu image that comes with Tensorflow preinstalled,it will be more easier to start learning Tensorflow more quickly for beginners 
I actually I have troubles with installing Tensorflow-gpu

Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by wdirons** [comment]
The dockerhub tensorflow image can be used to try tensorflow:

https://hub.docker.com/r/tensorflow/tensorflow/

**Comment by angersson** [comment]
Thanks @wdirons! This question has been answered, so I'm closing the issue.
