### ISSUE TITLE
[Tensorflow lite] iOS build for any archs fails : error: no matching member function for call to 'Verify'

### ISSUE THREAD

**Issue by wiseosho** [tensorflow/tensorflow#20900]
-----------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.13.3
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.9.0
- **Python version**: 2.7 / 3.6
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: 4.2.1
== compiler =====================================================
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: tensorflow/contrib/lite/build_ios_universal_lib.sh

### Describe the problem
iOS build for any architecture will fail.
I checked 'verifier' exist and defined in tensorflow/contrib/lite/tools/ and Verify is in there.
If i am right I guess it is related to the feature 'template deduction' which is c++11 or gcc version 
I am not sure if this failure comes from the bug of the code or my environmental setups but I think I throughly read the build documentation and followed the guidelines.

Here is my practice.

1. I installed xcode from the app store, (success)
 - run xcode-select --install
2. install homebrew (success)
3. brew install automake libtool (success)
4. git cloned tensorflow, (no issue)
5. download_install_dependencies (success)

### Source code / logs
...
clang++ -fPIC -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK -pthread  -std=c++11 -fPIC -O3 -DNDEBUG -miphoneos-version-min=9.0 -DGEMMLOWP_ALLOW
_SLOW_SCALAR_FALLBACK -DTFLITE_USE_APPLE_ACCELERATE_FOR_CONV -fembed-bitcode -Wno-c++11-narrowing -mno-thumb -fno-exceptions -isysroot 
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk -arch arm64 -O3 -I. -I/Users/con
tinuumai/tensorflow/tensorflow/contrib/lite/../../../ -I/Users/june/tensorflow/tensorflow/contrib/lite/downloads/ -I/Users/conti
nuumai/tensorflow/tensorflow/contrib/lite/downloads/eigen -I/Users/june/tensorflow/tensorflow/contrib/lite/downloads/gemmlowp -I
/Users/june/tensorflow/tensorflow/contrib/lite/downloads/neon_2_sse -I/Users/june/tensorflow/tensorflow/contrib/lite/down
loads/farmhash/src -I/Users/june/tensorflow/tensorflow/contrib/lite/downloads/flatbuffers/include -I/Users/june/tensorflo
w/tensorflow/contrib/lite/gen/obj/ -I/usr/local/include -c tensorflow/contrib/lite/kernels/lsh_projection.cc -o /Users/june/tens
orflow/tensorflow/contrib/lite/gen/obj/ios_arm64/tensorflow/contrib/lite/kernels/lsh_projection.o                                      clang: warning: argument unused during compilation: '-mno-thumb' [-Wunused-command-line-argument]                                      5 warnings generated.                                                                                                                  In file ```
**included from tensorflow/contrib/lite/interpreter.cc:33:                                                                       
**./tensorflow/contrib/lite/schema/schema_generated.h:1730:21: error: no matching member function for call to 'Verify'                   
           verifier.Verify(min()) &&                                                                                                   
           ~~~~~~~~~^~~~~~** **                                                                                                             
/Users/june/tensorflow/tensorflow/contrib/lite/downloads/flatbuffers/include/flatbuffers/flatbuffers.h:1775:29: note: candidate 
      template ignored: couldn't infer template argument 'T'                                                                           
  template<typename T> bool Verify(uoffset_t elem) const {                                                                             
                            ^                                                                                                          /Users/june/tensorflow/tensorflow/contrib/lite/downloads/flatbuffers/include/flatbuffers/flatbuffers.h:1784:29: note: candidate 
      function template not viable: requires 2 arguments, but 1 was provided                                                           
  template<typename T> bool Verify(const uint8_t *base, voffset_t elem_off)
                            ^
/Users/june/tensorflow/tensorflow/contrib/lite/downloads/flatbuffers/include/flatbuffers/flatbuffers.h:1763:8: note: candidate
      function not viable: requires 2 arguments, but 1 was provided
  bool Verify(uoffset_t elem, size_t elem_len) const {
       ^
/Users/june/tensorflow/tensorflow/contrib/lite/downloads/flatbuffers/include/flatbuffers/flatbuffers.h:1780:8: note: candidate
      function not viable: requires 3 arguments, but 1 was provided
  bool Verify(const uint8_t *base, voffset_t elem_off, size_t elem_len) const {
       ^
In file included from tensorflow/contrib/lite/interpreter.cc:33:
./tensorflow/contrib/lite/schema/schema_generated.h:1732:21: error: no matching member function for call to 'Verify'
           verifier.Verify(max()) &&
           ~~~~~~~~~^~~~~~
/Users/june/tensorflow/tensorflow/contrib/lite/downloads/flatbuffers/include/flatbuffers/flatbuffers.h:1775:29: note: candidate
      template ignored: couldn't infer template argument 'T'
  template<typename T> bool Verify(uoffset_t elem) const {
                            ^
/Users/june/tensorflow/tensorflow/contrib/lite/downloads/flatbuffers/include/flatbuffers/flatbuffers.h:1784:29: note: candidate
      function template not viable: requires 2 arguments, but 1 was provided
  template<typename T> bool Verify(const uint8_t *base, voffset_t elem_off)
                            ^
/Users/june/tensorflow/tensorflow/contrib/lite/downloads/flatbuffers/include/flatbuffers/flatbuffers.h:1763:8: note: candidate
      function not viable: requires 2 arguments, but 1 was provided

```
[log.txt](https://github.com/tensorflow/tensorflow/files/2203945/log.txt)

**Comment by EleanWei** [comment]
I had the same problem！！！！！

**Comment by zhengnianqing** [comment]
I have the same problem.!

**Comment by davlhd** [comment]
Try replacing the downloaded version of flatbuffers with an older one.

**Comment by cokekoala** [comment]
Are flatbuffers the only one needed to be replaced? I have tried doing this, but it did not work.

**Comment by davlhd** [comment]
I am stuck at a later point but this particular issues is fixed for me.

**Comment by cokekoala** [comment]
I find that it will still download the latest version of flatbuffers if I simply checkout to r1.8 branch of the tensorflow repository. To download the 1.8 version of flatbuffers, I should go to [https://github.com/google/flatbuffers/tree/v1.8.0](the flatbuffers repository). Then, I can build without error. Thanks @davlhd .

**Comment by shashishekhar** [comment]
@wiseosho : Thank you for the report, looks like a lot of people are hitting this, I am looking into it. @davlhd what other error are you seeing after replacing flatbuffers?

**Comment by davlhd** [comment]
I get `error: invalid argument '--std=c++11' not allowed with 'C'`
 because of `CCFLAGS := ${CXXFLAGS}` inside _tensorflow/contrib/lite/Makefile_. I need to change it to 
```
CCFLAGS := ${CXXFLAGS} -O3 -DNDEBUG
CXXFLAGS += --std=c++11 -O3 -DNDEBUG
```
to make sure the c++11 argument is only put into CCFLAGS. After that I got 

```
tensorflow/contrib/lite/downloads/eigen/unsupported/Eigen/CXX11/src/ThreadPool/NonBlockingThreadPool.h:326:5: error: thread-local storage is not supported for the current
      target
    EIGEN_THREAD_LOCAL PerThread per_thread_;
    ^
tensorflow/contrib/lite/downloads/eigen/unsupported/Eigen/CXX11/src/ThreadPool/ThreadLocal.h:15:35: note: expanded from macro 'EIGEN_THREAD_LOCAL'
#define EIGEN_THREAD_LOCAL static __thread
```
and thats where I left it for the moment.

But all of this could be due to some setup error on my side.

**Comment by wiseosho** [comment]
@davlhd Thankyou! I changed the flatbuffers version from master.zip to v1.8.0.zip and it works.
I can compile arm64 architecture only with this fallback, but I get the same error as @davlhd reported.
It seems this error pop up for x86_64 architecture( i386 I didn't try) . If I build only for arm64 architecture (which I need). It builds with no more issues.

**Comment by shashishekhar** [comment]
Looks like this is a problem with Xcode 9.3, it make take a few days to fix it. I will suggest to use Xcode 9.2 for now, while we fix it.

**Comment by wiseosho** [comment]
@shashishekhar Do you mean Xcode 9.3 or later, including Xcode 9.4.1?

**Comment by shashishekhar** [comment]
I have a fix, currently under review should be merged by end of tomorrow.
essentially: change MIN_SDK_VERSION := 10.0 which has C++ thread_local support and pass 
-D__thread=thread_local

**Comment by dyf102** [comment]
Change from 
```bash
FLATBUFFERS_URL="https://github.com/google/flatbuffers/archive/master.zip"
to 
FLATBUFFERS_URL="https://github.com/google/flatbuffers/archive/v1.8.0.zip"
```
indownload_dependencies.sh

**Comment by eavy** [comment]
I think we should also add the concrete revisions for each dependency in the `download_dependecies.sh` rather depend on `master` for example. Otherwise this issue can happen in the future when any "dependency" updates its `master`.

For example, I also see that `NEON_2_SSE_URL` has also the dependency on `master` rather than on concrete revision.

**Comment by wiseosho** [comment]
I git pulled the repository and checked all architectures build. 
Thanks for @shashishekhar, @davlhd and others for the support.

**Comment by shashishekhar** [comment]
Patch: https://github.com/tensorflow/tensorflow/commit/474b40bc7cb33d25f9bdc187d021e94a807bf1bd is merged, closing.

**Comment by KingBo0259** [comment]
I have the Same issue 。。。。 I have user master branch

**Comment by toby5box** [comment]
Against tensorflow v1.10.0: flatbuffers 1.9.0 also worked for me. 1.10.0 did not work.
