### ISSUE TITLE
android how to get time consuming ,node type and other information

### ISSUE THREAD

**Issue by 298068845** [tensorflow/tensorflow#20912]
![20170623201903623](https://user-images.githubusercontent.com/11265867/42868674-7c9973c0-8aa5-11e8-9558-4ae018dd96bd.png)
 I find a tensorflow lite app‘s screenshot ，how to do it like that?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by 298068845** [comment]
Have I written custom code N/A
OS Platform and Distribution N/A
TensorFlow installed from N/A
TensorFlow version N/A
Bazel version N/A
CUDA/cuDNN version N/A
GPU model and memory N/A
Exact command to reproduce N/A

**Comment by tatianashp** [comment]
@298068845 I apologize but I have hard time understanding what kind of help you need. Could you please clarify?

**Comment by shashishekhar** [comment]
@298068845 : You can try using https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/tools/benchmark for per node statistics. We don't expose this in the Java API yet, if the original image is using TFLite example, it maybe generated by making changes to the example code.

**Comment by shashishekhar** [comment]
@298068845 : Please reopen if you still need help.
