### ISSUE TITLE
Not able to build tensorflow lite iOS library

### ISSUE THREAD

**Issue by darcwader** [tensorflow/tensorflow#20924]
### System information

Trying to follow steps from this https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/ios.md

OS: Mac 10.13.4
XCode: 9.4.1
Command Line Tools: 9.4.1
Branch: master
SHA: ff791a7fde3605493bef70de8a9c9779541daf66

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh (Throws error)

### Describe the problem

error: invalid argument '--std=c++11' not allowed with 'C'

I get this when i try to build. if i change CC in makefile to 'g++' then other errors pop up. i think this script is broken. 

### Source code / logs
[build_ios_universal_lib.log](https://github.com/tensorflow/tensorflow/files/2206029/build_ios_universal_lib.log)

**Comment by shashishekhar** [comment]
This is tracked by issue #20900 , closing this updates will be on the other issue.
