### ISSUE TITLE
'ClusterSpec' object has no attribute '_cluster_spec'

### ISSUE THREAD

**Issue by chengdianxuezi** [tensorflow/tensorflow#2092]
I want to test tensorflow cluster,According tothe website https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/distributed/index.md
ERROR 'ClusterSpec' object has no attribute '_cluster_spec'  happend
>>> import numpy
>>> import matplotlib
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
>>> cluster = tf.train.ClusterSpec({"local": ["localhost:2222", "localhost:2223"]})
>>> server = tf.train.Server(cluster, job_name="local", task_index=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/server_lib.py", line 135, in __init__
    job_name, task_index, protocol)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/server_lib.py", line 65, in _make_server_def
    cluster_spec = ClusterSpec(server_or_cluster_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/server_lib.py", line 242, in __init__
    self._cluster_spec[job_def.name] = [t for t in job_def.tasks.values()]
AttributeError: 'ClusterSpec' object has no attribute '_cluster_spec'
>>>

**Comment by caisq** [comment]
See: https://github.com/tensorflow/tensorflow/issues/1961

**Comment by mrry** [comment]
This bug (#1961) has been fixed at HEAD and in the 0.8 release.
