### ISSUE TITLE
C++: Add gradient for Fill operator

### ISSUE THREAD

**Issue by kbsriram** [tensorflow/tensorflow#20926]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
v1.4.0-19-ga52c8d9 1.4.1
- **Python version**:
3.5.2 (default, Nov 23 2017, 16:37:01) 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
Feature request: Add gradient support for the Fill operator in the C++ API.

**Comment by bignamehyp** [comment]
We currently don't have anybody working on this. It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thanks!

**Comment by kbsriram** [comment]
Thanks Yanping! PR https://github.com/tensorflow/tensorflow/pull/20928 is currently approved - if you can help with the process, can close this issue when it gets merged.

**Comment by bignamehyp** [comment]
Thank you very much for your contributions!

**Comment by kbsriram** [comment]
Thanks all for the help getting the PR merged, fixed via https://github.com/tensorflow/tensorflow/commit/b462815ccc279c79a5592a0a2d4492718da02c5d
