### ISSUE TITLE
Use InlinedVector for ShapeIndex breaks tensorflow build from source using bazel 0.14.0 inside docker 

### ISSUE THREAD

**Issue by trathpai** [tensorflow/tensorflow#20925]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: latest
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:0.14.0
- **GCC/Compiler version (if compiling from source)**:gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

- **CUDA/cuDNN version**:9.0/7.1
- **GPU model and memory**:Nvidia GeForce 1080 Ti
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
While building the tensorflow from source inside docker  using above configuration i encountered following errors.

### Source code / logs
ERROR: /root/tensorflow/tensorflow/compiler/xla/BUILD:216:1: C++ compilation of rule '//tensorflow/compiler/xla:shape_util' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-9.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 \
    NCCL_INSTALL_PATH=/usr/local/cuda-9.0 \
    PATH=/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/opt/conda/bin/python3.6 \
    PYTHON_LIB_PATH=/opt/conda/lib/python3.6 \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=6.1 \
    TF_CUDA_VERSION=9.0 \
    TF_CUDNN_VERSION=7 \
    TF_NCCL_VERSION=2 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL_SYCL=0 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/compiler/xla/_objs/shape_util/tensorflow/compiler/xla/index_util.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/compiler/xla/_objs/shape_util/tensorflow/compiler/xla/index_util.o' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' -DTENSORFLOW_USE_JEMALLOC -DTENSORFLOW_USE_ABSL -DTF_USE_SNAPPY -iquote . -iquote bazel-out/k8-opt/genfiles -iquote external/com_google_absl -iquote bazel-out/k8-opt/genfiles/external/com_google_absl -iquote external/bazel_tools -iquote bazel-out/k8-opt/genfiles/external/bazel_tools -iquote external/nsync -iquote bazel-out/k8-opt/genfiles/external/nsync -iquote external/jemalloc -iquote bazel-out/k8-opt/genfiles/external/jemalloc -iquote external/eigen_archive -iquote bazel-out/k8-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/k8-opt/genfiles/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/k8-opt/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/k8-opt/genfiles/external/jpeg -iquote external/protobuf_archive -iquote bazel-out/k8-opt/genfiles/external/protobuf_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/k8-opt/genfiles/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/genfiles/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/genfiles/external/highwayhash -iquote external/zlib_archive -iquote bazel-out/k8-opt/genfiles/external/zlib_archive -iquote external/local_config_cuda -iquote bazel-out/k8-opt/genfiles/external/local_config_cuda -isystem external/nsync/public -isystem bazel-out/k8-opt/genfiles/external/nsync/public -isystem bazel-out/k8-opt/bin/external/nsync/public -isystem external/jemalloc/include -isystem bazel-out/k8-opt/genfiles/external/jemalloc/include -isystem bazel-out/k8-opt/bin/external/jemalloc/include -isystem external/eigen_archive -isystem bazel-out/k8-opt/genfiles/external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/k8-opt/genfiles/external/gif_archive/lib -isystem bazel-out/k8-opt/bin/external/gif_archive/lib -isystem external/protobuf_archive/src -isystem bazel-out/k8-opt/genfiles/external/protobuf_archive/src -isystem bazel-out/k8-opt/bin/external/protobuf_archive/src -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/genfiles/external/farmhash_archive/src -isystem bazel-out/k8-opt/bin/external/farmhash_archive/src -isystem external/zlib_archive -isystem bazel-out/k8-opt/genfiles/external/zlib_archive -isystem bazel-out/k8-opt/bin/external/zlib_archive -isystem external/local_config_cuda/cuda -isystem bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda -isystem bazel-out/k8-opt/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/include -isystem bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include -isystem external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/crt '-std=c++11' -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIE -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections '-D_GLIBCXX_USE_CXX11_ABI=0' -c tensorflow/compiler/xla/index_util.cc -o bazel-out/k8-opt/bin/tensorflow/compiler/xla/_objs/shape_util/tensorflow/compiler/xla/index_util.o)
In file included from tensorflow/compiler/xla/index_util.cc:21:0:
./tensorflow/compiler/xla/shape_util.h:77:26: error: 'gtl' does not name a type
   using container_type = gtl::InlinedVector<int64, 2>;
                          ^
./tensorflow/compiler/xla/shape_util.h:79:3: error: 'container_type' does not name a type
   container_type::const_iterator begin() const { return indices_.begin(); }
   ^
./tensorflow/compiler/xla/shape_util.h:80:3: error: 'container_type' does not name a type
   container_type::const_iterator end() const { return indices_.end(); }
   ^
./tensorflow/compiler/xla/shape_util.h:81:3: error: 'container_type' does not name a type
   container_type::iterator begin() { return indices_.begin(); }
   ^
./tensorflow/compiler/xla/shape_util.h:82:3: error: 'container_type' does not name a type
   container_type::iterator end() { return indices_.end(); }
   ^
./tensorflow/compiler/xla/shape_util.h:103:3: error: 'container_type' does not name a type
   container_type indices_;
   ^
./tensorflow/compiler/xla/shape_util.h: In constructor 'xla::ShapeIndex::ShapeIndex(std::initializer_list<long long int>)':
./tensorflow/compiler/xla/shape_util.h:65:51: error: class 'xla::ShapeIndex' does not have any field named 'indices_'
   ShapeIndex(std::initializer_list<int64> init) : indices_(init) {}
                                                   ^
./tensorflow/compiler/xla/shape_util.h: In constructor 'xla::ShapeIndex::ShapeIndex(InputIt, InputIt)':
./tensorflow/compiler/xla/shape_util.h:67:44: error: class 'xla::ShapeIndex' does not have any field named 'indices_'
   ShapeIndex(InputIt start, InputIt end) : indices_(start, end) {}
                                            ^
./tensorflow/compiler/xla/shape_util.h: In member function 'bool xla::ShapeIndex::empty() const':
./tensorflow/compiler/xla/shape_util.h:69:31: error: 'indices_' was not declared in this scope
   bool empty() const { return indices_.empty(); }
                               ^
./tensorflow/compiler/xla/shape_util.h: In member function 'size_t xla::ShapeIndex::size() const':
./tensorflow/compiler/xla/shape_util.h:70:32: error: 'indices_' was not declared in this scope
   size_t size() const { return indices_.size(); }
                                ^
./tensorflow/compiler/xla/shape_util.h: In member function 'void xla::ShapeIndex::push_back(tensorflow::int64)':
./tensorflow/compiler/xla/shape_util.h:71:33: error: 'indices_' was not declared in this scope
   void push_back(int64 value) { indices_.push_back(value); }
                                 ^
./tensorflow/compiler/xla/shape_util.h: In member function 'void xla::ShapeIndex::pop_back()':
./tensorflow/compiler/xla/shape_util.h:72:21: error: 'indices_' was not declared in this scope
   void pop_back() { indices_.pop_back(); }
                     ^
./tensorflow/compiler/xla/shape_util.h: In member function 'void xla::ShapeIndex::push_front(tensorflow::int64)':
./tensorflow/compiler/xla/shape_util.h:75:34: error: 'indices_' was not declared in this scope
   void push_front(int64 value) { indices_.insert(indices_.begin(), value); }
                                  ^
./tensorflow/compiler/xla/shape_util.h: In member function 'const int64* xla::ShapeIndex::data() const':
./tensorflow/compiler/xla/shape_util.h:84:38: error: 'indices_' was not declared in this scope
   const int64* data() const { return indices_.data(); }
                                      ^
./tensorflow/compiler/xla/shape_util.h: In member function 'tensorflow::int64 xla::ShapeIndex::back() const':
./tensorflow/compiler/xla/shape_util.h:86:31: error: 'indices_' was not declared in this scope
   int64 back() const { return indices_.back(); }
                               ^
./tensorflow/compiler/xla/shape_util.h: In member function 'tensorflow::int64& xla::ShapeIndex::back()':
./tensorflow/compiler/xla/shape_util.h:87:26: error: 'indices_' was not declared in this scope
   int64& back() { return indices_.back(); }
                          ^
./tensorflow/compiler/xla/shape_util.h: In member function 'const int64& xla::ShapeIndex::operator[](size_t) const':
./tensorflow/compiler/xla/shape_util.h:89:52: error: 'indices_' was not declared in this scope
   const int64& operator[](size_t i) const { return indices_[i]; }
                                                    ^
./tensorflow/compiler/xla/shape_util.h: In member function 'tensorflow::int64& xla::ShapeIndex::operator[](size_t)':
./tensorflow/compiler/xla/shape_util.h:90:40: error: 'indices_' was not declared in this scope
   int64& operator[](size_t i) { return indices_[i]; }
                                        ^
./tensorflow/compiler/xla/shape_util.h: In member function 'bool xla::ShapeIndex::operator==(const xla::ShapeIndex&) const':
./tensorflow/compiler/xla/shape_util.h:93:12: error: 'indices_' was not declared in this scope
     return indices_ == other.indices_;
            ^
./tensorflow/compiler/xla/shape_util.h:93:30: error: 'const class xla::ShapeIndex' has no member named 'indices_'
     return indices_ == other.indices_;
                              ^
./tensorflow/compiler/xla/shape_util.h: In member function 'bool xla::ShapeIndex::operator<(const xla::ShapeIndex&) const':
./tensorflow/compiler/xla/shape_util.h:97:12: error: 'indices_' was not declared in this scope
     return indices_ < other.indices_;
            ^
./tensorflow/compiler/xla/shape_util.h:97:29: error: 'const class xla::ShapeIndex' has no member named 'indices_'
     return indices_ < other.indices_;
                             ^
tensorflow/compiler/xla/index_util.cc: In static member function 'static bool xla::IndexUtil::IndexInBounds(const xla::Shape&, tensorflow::gtl::ArraySlice<long long int>)':
tensorflow/compiler/xla/index_util.cc:155:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (rank != index.size()) {
            ^
In file included from ./tensorflow/core/platform/default/logging.h:24:0,
                 from ./tensorflow/core/platform/logging.h:25,
                 from ./tensorflow/core/lib/gtl/array_slice_internal.h:32,
                 from ./tensorflow/core/lib/gtl/array_slice.h:101,
                 from ./tensorflow/compiler/xla/index_util.h:25,
                 from tensorflow/compiler/xla/index_util.cc:16:
./tensorflow/core/platform/default/logging.h: In instantiation of 'std::string* tensorflow::internal::Check_LEImpl(const T1&, const T2&, const char*) [with T1 = long long int; T2 = long unsigned int; std::string = std::basic_string<char>]':
./tensorflow/compiler/xla/shape_util.h:117:5:   required from here
./tensorflow/core/platform/default/logging.h:232:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 TF_DEFINE_CHECK_OP_IMPL(Check_LE, <=)
                                   ^
./tensorflow/core/platform/macros.h:88:49: note: in definition of macro 'TF_PREDICT_TRUE'
 #define TF_PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                 ^
./tensorflow/core/platform/default/logging.h:232:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_LE, <=)
 ^
./tensorflow/core/platform/default/logging.h: In instantiation of 'std::string* tensorflow::internal::Check_EQImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = long long int; std::string = std::basic_string<char>]':
tensorflow/compiler/xla/index_util.cc:170:3:   required from here
./tensorflow/core/platform/default/logging.h:230:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                         ==)  // Compilation error with CHECK_EQ(NULL, x)?
                         ^
./tensorflow/core/platform/macros.h:88:49: note: in definition of macro 'TF_PREDICT_TRUE'
 #define TF_PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                 ^
./tensorflow/core/platform/default/logging.h:229:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_EQ,

**Comment by dibyendudas0708** [comment]
I have faced the same issue for the latest TF1.9 build.

**Comment by dibyendudas0708** [comment]
Looks like the namespace tensorflow is missing in ./tensorflow/compiler/xla/shape_util.h:77 for gtl::InlinedVector<> usage. We need to change this line to tensorflow::gtl::InlinedVector<>

**Comment by d0k** [comment]
02725138f41befb78573e6abc177baed06cc1b3f fixed this
