### ISSUE TITLE
How to add/print logs from TFLite JNI.cc (native code) files?

### ISSUE THREAD

**Issue by madhu-sudhan** [tensorflow/tensorflow#20949]
Hello, I'm trying to put prints in the [native code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/java/src/main/native/nativeinterpreterwrapper_jni.cc) files of TFLite files in the repository to get good understanding of TFlite and Android ecosystem. I have tried including <stdio.h> and printing with printf/fprintf/cout. Noting seems to be coming in the adb logcat.

Can anyone help me how to get the prints from the native code?

Thanks

**Comment by shashishekhar** [comment]
@madhu-sudhan : You need to use Android native logging macros: https://developer.android.com/ndk/reference/group/logging#__android_log_print

**Comment by madhu-sudhan** [comment]
Hi @shashishekhar , good to see quick response on the issue. 

Yes, as you have mentioned I have just tried including the file <android/log.h> and I have put a sample print at [Java_org_tensorflow_lite_NativeInterpreterWrapper_run](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/java/src/main/native/nativeinterpreterwrapper_jni.cc#L349):

__android_log_print(ANDROID_LOG_ERROR, "MyLog","=========================");

But it seems it is not turning up in the logcat. I'm pretty sure that the control in going through this function (I have verified that by putting a dummy return instead of print statement). Can you please tell if I could have missed something? Or is it that no debug prints comes from this particular file?

Thanks !!

**Comment by freedomtan** [comment]
@madhu-sudhan you probably want add `-llog` when building your jni .so (if you are building .so or say .aar with .so inside)

**Comment by madhu-sudhan** [comment]
Hi @freedomtan , I'm trying to build with bazel command like mentioned below.

bazel build --cxxopt=--std=c++11 -c opt --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a tensorflow/contrib/lite/java:libtensorflowlite_jni.so

I have specified -llog with an option (--linkopt=-llog) to bazel command like shown below, but still am not able to see any prints in logcat.

bazel build --linkopt=-llog --cxxopt=--std=c++11 -c opt --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a tensorflow/contrib/lite/java:libtensorflowlite_jni.so

Can you please suggest some workarounds?

Thanks

**Comment by shashishekhar** [comment]
@madhu-sudhan :  this should work and is well test unless you are missing a step or apk is not updated.

**Comment by madhu-sudhan** [comment]
Hi @shashishekhar , yeah I dont know what i have missed. But the above mentioned steps are not helping to get prints in android logcat. Can you please help me identify if something I have missed?

Thanks
Madhu

**Comment by shashishekhar** [comment]
@madhu-sudhan : You can try __android_log_assert and see if you get a fatal crash, then at least your log is getting triggered.

If that works then try "adb logcat -P ''" and relaunch the app, if you still don't see the log, I will suggest first writing a simple Android app with JNI and using that to do Android logging, there are plenty of examples on the web. This will make you familiar with how JNI works on Android. Unfortunately can't help you anymore, without knowing how you are using the code.
