### ISSUE TITLE
Build tensorflow-model-server for gpu - Cannot find cuda library libcudnn.so.6

### ISSUE THREAD

**Issue by nadavb** [tensorflow/tensorflow#20959]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux ip-172-30-1-83 4.4.0-1062-aws #71-Ubuntu SMP Fri Jun 15 10:07:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.5.0
- **Python version**: Python 2.7.12
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**: c++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

- **CUDA/cuDNN version**:

== cuda libs  ===================================================
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so.9.0.176
/usr/local/cuda-9.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-9.0/doc/man/man7/libcudart.7

But I also have these files:
/usr/lib/x86_64-linux-gnu/libcudnn.so -> /etc/alternatives/libcudnn_so
/usr/lib/x86_64-linux-gnu/libcudnn.so.6 -> libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7 -> libcudnn.so.7.0.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5

- **GPU model and memory**: Tesla K80

### Describe the problem

I try to build tensorflow-model-server with gpu support, as I saw that the apt-get version is only for CPU.

I did:
1. git clone --recurse-submodules https://github.com/tensorflow/serving
2. bazel clean --expunge && export TF_NEED_CUDA=1
3. bazel query 'kind(rule, @local_config_cuda//...)'

And got:

Cuda Configuration Error: Cannot find cuda library libcudnn.so.6

When I do: bazel build -c opt --config=cuda tensorflow_serving/model_servers:tensorflow_model_server
I get the same error.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi. Try to set the env variable to `LD_LIBRARY_PATH`:

```
export D_LIBRARY_PATH="/usr/local/cuda-9.0/"

```
Hope it helps :)

**Comment by nadavb** [comment]
You meant `export D_LIBRARY_PATH="/usr/local/cuda-9.0/"`

Nope... Still same error message:

`Cuda Configuration Error: Cannot find cuda library libcudnn.so.6`

The file libcudnn.so.6 is found on my server at `/usr/lib/x86_64-linux-gnu/libcudnn.so.6`
But it can't find it...

**Comment by FrancescoSaverioZuppichini** [comment]
Sorry  I meant,
```
export LD_LIBRARY_PATH="/usr/local/cuda-9.0/"
```
I am not an expert I was just trying to help since I had a similar issue on ubuntu 18.04 with `tensorflow-gpu`. So, did you have the `/usr/local/cuda-9.0/` folder? Just in case, try to echo your environment variables and see if there is LD_LIBRARY_PATH. 

I hope maybe it will help

**Comment by reedwm** [comment]
This should be filed with the [tensorflow/serving repo](https://github.com/tensorflow/serving/issues). So I'll close this issue.

Not sure why Tensorflow Serving needs cudnn 6. In TensorFlow, currently by default we use cudnn 7.

**Comment by nadavb** [comment]
I will file it in the other repo.
