### ISSUE TITLE
Entry point not found error reported when calling tf.contrib.rnn.BasicRNNCell

### ISSUE THREAD

**Issue by solarbear123** [tensorflow/tensorflow#20954]
Python version = 3.5.0

- Have I written custom code --> No
- OS Platform and Distribution  --> Windows 10
- TensorFlow installed from --> pip install --ignore-installed --upgrade tensorflow-gpu 
- TensorFlow version --> 1.8.0-gpu
- Bazel version --> NA
- CUDA/cuDNN version --> 9.0
- GPU model and memory --> GeForce GTX 960M, 3GB
- Exact command to reproduce --> See below

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)  # Errs out here

Error message:

"The procedure entry point
?AddCleanup@Arenalmpl@internal@protobuf@google@@QEAAXXEPEAXP6AX0@Z@Z could not be located in the dynamic link library C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\data\_dataset_ops.so"

![image](https://user-images.githubusercontent.com/8305769/42923931-d0e91e26-8adc-11e8-802c-29ff0a065301.png)

**Comment by Tonoyama** [comment]
I'm having the same problem!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by solarbear123** [comment]
Requested info added to original post.

**Comment by bignamehyp** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by solarbear123** [comment]
OK. But did you observe the same phenomenon? How did you come to the conclusion that it is not an issue with the file data_dataset_ops.so?

**Comment by sbhola** [comment]
I came across this same issue today, can anyone suggest what's the workaround @solarbear123 @bignamehyp. Thanks.

**Comment by Anurag-cod4fun** [comment]
I am facing the same issue, how can I fix this ? @solarbear123  @bignamehyp  @sbhola
