### ISSUE TITLE
Miss-leading explanation of 'export_tflite_ssd_graph.py' 

### ISSUE THREAD

**Issue by MaeThird** [tensorflow/tensorflow#20962]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: PC
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: newest from master branch
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.14
- **GCC/Compiler version (if compiling from source)**: gcc-7.1
- **CUDA/cuDNN version**: cuda-9.2,cudnn-7.1
- **GPU model and memory**: 16G
- **Exact command to reproduce**:

The function explanation of **export_tflite_ssd_graph.py** said 
`
Outputs:
If add_postprocessing_op is true: frozen graph adds a
  TFLite_Detection_PostProcess custom op node has four outputs:
  detection_boxes: a float32 tensor of shape [1, num_boxes, 4] with box
  locations
  detection_scores: a float32 tensor of shape [1, num_boxes]
  with class scores
  detection_classes: a float32 tensor of shape [1, num_boxes]
  with class indices
  num_boxes: a float32 tensor of size 1 containing the number of detected boxes
`

But according to my test the output sequence is  **boxes, indice, scores ,num** not **boxes,scores,indice,num**. (in `detection_postprocess.cc` seq is also **boxes, indice, scores ,num** )
And in **export_tflite_ssd_graph_lib.py** 
the `def get_const_center_size_encoded_anchors(anchors)` 's return shape is obviously 
**[num_anchors,4]** not **[4,num_anchors]**.

**Comment by achowdhery** [comment]
Thanks for correction on the comment

**Comment by achowdhery** [comment]
https://github.com/tensorflow/models/pull/4851
Thanks. This should merge soon.
