### ISSUE TITLE
switch for nccl

### ISSUE THREAD

**Issue by aimhabo** [tensorflow/tensorflow#20966]
in configure.py(r1.10):

> line 1132 to 1141

```
    if is_windows():
      nccl_lib_path = 'lib/x64/nccl.lib'
    elif is_linux():
      nccl_lib_path = '/usr/lib/x86_64-linux-gnu/libnccl.so.%s' % tf_nccl_version
      #nccl_lib_path = 'lib64/libnccl.so.%s' % tf_nccl_version
    elif is_macos():
      nccl_lib_path = 'lib/libnccl.%s.dylib' % tf_nccl_version

    nccl_lib_path = os.path.join(nccl_install_path, nccl_lib_path)
    nccl_hdr_path = os.path.join(nccl_install_path, '/usr/include/nccl.h')#'include/nccl.h')
```
in case of install nccl by `sudo apt install libnccl2=2.2.13-1+cuda9.0 libnccl-dev=2.2.13-1+cuda9.0
`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by aimhabo** [comment]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:  no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.8
- **Python version**:  2.7.12
- **Bazel version (if compiling from source)**: 0.14.1
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.0/7.1.2
- **GPU model and memory**: GTX850M 2GB
