### ISSUE TITLE
Undefined symbol in GPU user op

### ISSUE THREAD

**Issue by c0g** [tensorflow/tensorflow#2097]
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 7.5, 5 (see bottom for ls output)
If installed from sources, provide the commit hash: 55068f32c87c73c8de7a417d8be735306e5307a1

### Steps to reproduce
1. Get BUILD, get_diag.cc, get_diag.cu.cc from [my fork](https://github.com/c0g/tensorflow/tree/master/tensorflow/core/user_ops)
2. Build the get_diag op with `bazel build -c opt --config cuda //tensorflow/core/user_ops:get_diag.so`
3. Try to run it on the GPU.

Error messages is: 
`
tensorflow.python.framework.errors.NotFoundError: /home/tron/Source/tensorflow/bazel-bin/tensorflow/core/user_ops/get_diag.so: undefined symbol: _Z21GetDiagKernelLauncherIdEvPKT_iiPS0_
`

however, running `nm -an get_diag.so | grep _Z21GetDiagKernelLauncherIdEvPKT_iiPS0_` shows `                 U _Z21GetDiagKernelLauncherIdEvPKT_iiPS0_` , so it appears the symbol is present.

This works fine with the CPU version of the op - is there something I'm missing to make Bazel link things properly?

### Logs or other output that would be helpful
-rw-r--r-- 1 root root   322936 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart_static.a
lrwxrwxrwx 1 tron tron       13 Mar 22 07:44 /usr/local/cuda-7.5/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 tron tron       17 Mar 22 07:44 /usr/local/cuda-7.5/lib64/libcudnn.so.5 -> libcudnn.so.5.0.4
-rwxrwxr-x 1 tron tron 59823168 Mar 22 01:37 /usr/local/cuda-7.5/lib64/libcudnn.so.5.0.4
-rw-rw-r-- 1 tron tron 58734618 Mar 22 01:37 /usr/local/cuda-7.5/lib64/libcudnn_static.a

**Comment by c0g** [comment]
Closing: user error.

**Comment by zhengwy888** [comment]
can you briefly explain what your user error is? I think i am hitting the same issue and not able to get around this.
