### ISSUE TITLE
object detection api tflite export_tflite_ssd_graph  error 

### ISSUE THREAD

**Issue by rickragv** [tensorflow/tensorflow#20974]
when i ran above SSD model

xport CONFIG_FILE=~/**ssd_mobilenet_v1_0.75_depth_quantized_300x300_coco14_sync_2018_07_03**/pipeline.config
export CHECKPOINT_PATH=~/ssd_mobilenet_v1_0.75_depth_quantized_300x300_coco14_sync_2018_07_03/model.ckpt

python object_detection/export_tflite_ssd_graph.py \

> — pipeline_config_path=$CONFIG_FILE \

> — trained_checkpoint_prefix=$CHECKPOINT_PATH \

> — output_directory=$OUTPUT_DIR \

> — add_postprocessing_op=true

/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.

from ._conv import register_converters as _register_converters

OMP: Warning #181: OMP_PROC_BIND: ignored because KMP_AFFINITY has been defined

2018–07–19 15:44:19.888752: I tensorflow/core/common_runtime/process_util.cc:63] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.

2018–07–19 15:44:22.853028: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint

Traceback (most recent call last):

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py”, line 1322, in _do_call

return fn(*args)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py”, line 1307, in _run_fn

options, feed_dict, fetch_list, target_list, run_metadata)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py”, line 1409, in _call_tf_sessionrun

run_metadata)

tensorflow.python.framework.errors_impl.NotFoundError: Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint

[[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, …, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device=”/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File “object_detection/export_tflite_ssd_graph.py”, line 137, in <module>

tf.app.run(main)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/platform/app.py”, line 126, in run

_sys.exit(main(argv))

File “object_detection/export_tflite_ssd_graph.py”, line 133, in main

FLAGS.max_classes_per_detection)

File “/home/ubuntu/models/research/object_detection/export_tflite_ssd_graph_lib.py”, line 261, in export_tflite_graph

initializer_nodes=’’)

File “/home/ubuntu/models/research/object_detection/exporter.py”, line 72, in freeze_graph_with_def_protos

saver.restore(sess, input_checkpoint)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py”, line 1802, in restore

{self.saver_def.filename_tensor_name: save_path})

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py”, line 900, in run

run_metadata_ptr)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py”, line 1135, in _run

feed_dict_tensor, options, run_metadata)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py”, line 1316, in _do_run

run_metadata)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py”, line 1335, in _do_call

raise type(e)(node_def, op, message)

tensorflow.python.framework.errors_impl.NotFoundError: Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint

[[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, …, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device=”/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op ‘save/RestoreV2’, defined at:

File “object_detection/export_tflite_ssd_graph.py”, line 137, in <module>

tf.app.run(main)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/platform/app.py”, line 126, in run

_sys.exit(main(argv))

File “object_detection/export_tflite_ssd_graph.py”, line 133, in main

FLAGS.max_classes_per_detection)

File “/home/ubuntu/models/research/object_detection/export_tflite_ssd_graph_lib.py”, line 261, in export_tflite_graph

initializer_nodes=’’)

File “/home/ubuntu/models/research/object_detection/exporter.py”, line 67, in freeze_graph_with_def_protos

tf.import_graph_def(input_graph_def, name=’’)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py”, line 432, in new_func

return func(*args, **kwargs)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/importer.py”, line 513, in import_graph_def

_ProcessNewOps(graph)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/importer.py”, line 303, in _ProcessNewOps

for new_op in graph._add_new_tf_operations(compute_devices=False): # pylint: disable=protected-access

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py”, line 3540, in _add_new_tf_operations

for c_op in c_api_util.new_tf_operations(self)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py”, line 3540, in <listcomp>

for c_op in c_api_util.new_tf_operations(self)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py”, line 3428, in _create_op_from_tf_operation

ret = Operation(c_op, self)

File “/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py”, line 1718, in __init__

self._traceback = self._graph._extract_stack() # pylint: disable=protected-access

NotFoundError (see above for traceback): Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint

[[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, …, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device=”/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by achowdhery** [comment]
Thanks. This checkpoint link will be updated today.
Please start with this checkpoint meanwhile:
https://storage.googleapis.com/download.tensorflow.org/models/tflite/ssd_mobilenet_v1_0.75_depth_300x300_quant_pets_2018_06_29.zip

**Comment by achowdhery** [comment]
The checkpoints have been updated in the detection model zoo.
