### ISSUE TITLE
TFLITE object detection api  SSD model export issue toco

### ISSUE THREAD

**Issue by rickragv** [tensorflow/tensorflow#20973]
Hi, while running

export CONFIG_FILE=~/ssdlite_mobilenet_v2_coco_2018_05_09/pipeline.config
export CHECKPOINT_PATH=~/ssdlite_mobilenet_v2_coco_2018_05_09/model.ckpt

bazel run -c opt tensorflow/contrib/lite/toco:toco — — input_file=$OUTPUT_DIR/tflite_graph.pb — output_file=$OUTPUT_DIR/detect.tflite — input_shapes=1,300,300,3 — input_arrays=normalized_input_image_tensor — output_arrays=’TFLite_Detection_PostProcess’,’TFLite_Detection_PostProcess:1',’TFLite_Detection_PostProcess:2',’TFLite_Detection_PostProcess:3' — inference_type=QUANTIZED_UINT8 — mean_values=128 — std_values=128 — change_concat_input_ranges=false — allow_custom_ops

INFO: Analysed target //tensorflow/contrib/lite/toco:toco (0 packages loaded).

INFO: Found 1 target…

Target //tensorflow/contrib/lite/toco:toco up-to-date:

bazel-bin/tensorflow/contrib/lite/toco/toco

INFO: Elapsed time: 0.392s, Critical Path: 0.01s

INFO: 0 processes.

INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/tensorflow/contrib/lite/toco/toco ‘ — input_file=/home/ubuntu/tflite/tflite_graph.pb’ ‘ — output_file=/home/ubuntu/tflite/detect.tflite’ ‘ — input_shapes=1,300,300,3’ ‘ — input_arrays=normalized_input_image_tensor’ ‘ — output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3’ ‘INFO: Build completed successfully, 1 total action

2018–07–19 15:32:40.725811: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1048] Converting unsupported operation: TFLite_Detection_PostProcess

2018–07–19 15:32:40.742690: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1070 operators, 1570 arrays (0 quantized)

2018–07–19 15:32:40.791000: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1070 operators, 1570 arrays (0 quantized)

2018–07–19 15:32:40.849051: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 116 operators, 310 arrays (1 quantized)

2018–07–19 15:32:40.852027: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 116 operators, 310 arrays (1 quantized)

2018–07–19 15:32:40.853807: F tensorflow/contrib/lite/toco/tooling_util.cc:1621] Array FeatureExtractor/MobilenetV2/Conv/Relu6, which is an input to the DepthwiseConv operator producing the output array FeatureExtractor/MobilenetV2/expanded_conv/depthwise/Relu6, is lacking min/max data, which is necessary for quantization. Either target a non-quantized output format, or change the input graph to contain min/max information, or pass — default_ranges_min= and — default_ranges_max= if you do not care about the accuracy of results.

**Comment by achowdhery** [comment]
Please start with Mobilenet v1 SSD to make sure the pipeline works.
https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193
For the above model you are passing, it seems it is a float model, not a quantized model.
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md

**Comment by patrick-ucr** [comment]
I am having a similar issue with ssdlite_mobilenet_v2
