### ISSUE TITLE
High loss of accuracy when using TFLite on Android

### ISSUE THREAD

**Issue by jbuisson1** [tensorflow/tensorflow#20980]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Only on Android (modified the TFLiteClassifier.java class to output the results in a more convenient manner and commented the call to applyFilter() so the model doesn't base its detection on other images than the one I am giving to it)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.13.3
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: Samsung Galaxy S6
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.8.0-0-g93bc2e2072 1.8.0
- **Python version**: Python 3.6.0 :: Anaconda 4.3.1 (x86_64)
- **Bazel version (if compiling from source)**: Build label: 0.14.1-homebrew
- **GCC/Compiler version (if compiling from source)**: Apple LLVM version 9.1.0 (clang-902.0.39.2)
- **CUDA/cuDNN version**: NA
- **GPU model and memory**:  NVIDIA GeForce GT 650M 1 GB
- **Exact command to reproduce**: 
```
cd ../tensorflow-for-poets-2/
python -m scripts.retrain --bottleneck_dir=bottlenecks --how_many_training_steps=$STEPS --model_dir=/Users/jean-baptistebuisson/new_training_dir/model/ --summaries_dir=/Users/jean-baptistebuisson/new_training_dir/training_summaries/mobilenet_1.0_224 --output_graph=/Users/jean-baptistebuisson/new_training_dir/$NAME.pb --output_labels=/Users/jean-baptistebuisson/new_training_dir/retrained_labels.txt --architecture=mobilenet_1.0_224 --image_dir=/Users/jean-baptistebuisson/tf_files/tw --tfhub_module https://tfhub.dev/google/imagenet/mobilenet_v1_100_224/feature_vector/1
cd ../new_training_dir/
cd ../tensorflow/
bazel-bin/tensorflow/contrib/lite/toco/toco --input_file=../new_training_dir/$NAME.pb --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --output_file=$NAME.tflite --inference_type=FLOAT --inference_input_type=FLOAT --input_arrays=input --output_array=final_result --input_shapes=1,224,224,3
cd ../new_training_dir/
```

### Describe the problem

The above commands let me retrain a Mobilenet model with 2 categories (positive and negative) and outputs a .pb and a .tflite model that both work fine when tested with label_image with the same data (100 positive images and 100 negative):
For the .pb model:
`True positive: 97; true negative: 98; false positive: 2; false negative: 3`
For the .tflite model:
`True positive: 100; true negative: 100; false positive: 0; false negative: 0`

Then I import the model on Android and run on the same images I get the following result:
`True Positive: 100; True Negative: 0; False Positive: 100; False Negative: 0`

I don't know what is messing with the detection but on Android everything is detected as positive.
Here are the .pb and .tflite models I am using:
[retrainedMNetV1_7_8000.pb.zip](https://github.com/tensorflow/tensorflow/files/2211815/retrainedMNetV1_7_8000.pb.zip)
[retrainedMNetV1_7_8000.tflite.zip](https://github.com/tensorflow/tensorflow/files/2211816/retrainedMNetV1_7_8000.tflite.zip)

And here is my modified TFLiteClassifier.java class:
[TFLiteClassifier.java.zip](https://github.com/tensorflow/tensorflow/files/2211823/TFLiteClassifier.java.zip)

**Comment by shashishekhar** [comment]
@jbuisson1 : How are you feeding images to the classifier?

**Comment by jbuisson1** [comment]
Here is the code where I feed an image to the classifier (f is the File of the current image to be fed)

```
BitmapFactory.Options options = new BitmapFactory.Options()
options.inSampleSize = 8;
final Bitmap b = BitmapFactory.decodeFile(f.getAbsolutePath(), options);
ArrayList<TFLiteRecognition> res = new ArrayList<>();
try {
    res = Globals.lightClassifier.classifyFrame(b);
} catch (IllegalStateException e) {
    Log.d(TAG, "testImage: " + e.getMessage());
}
```

**Comment by shashishekhar** [comment]
@jbuisson1 : My suspicion without looking at the images will be that images fed to classifier are not correct or not in the same format as during the training. You can try doing a sanity check of images that you are feeding to the classifier.
Try dumping the images to sdcard after you do 
bitmap.getPixels(...) in convertBitmapToByteBuffer.  Check if they match with the images during the training phase after pre-processing.
Let me know if that helps. You can also try running the non-TFLite model on Android and check if there is an accuracy loss. I suspect you will see a loss there as well, which would mean an error in the pre-processing phase.

**Comment by naris96** [comment]
Hi @jbuisson1. I face the same problem right now and I'm not sure what I'm supposed to do. In your case, do you mean you change the image size in the Android or the model training? Desperate for help...Thanks in advance.

**Comment by DoritoDog** [comment]
In case anyone has the same problem in the future, the solution for me was to make sure that all dimensions were the same - width, height, IMAGE_MEAN, and IMAGE_STD. 
If you are using one of the tensorflow examples, you need to update all these values accordingly. Also make sure the image's size also matches the hardcoded width and height values.

**Comment by getsanjeev** [comment]
@DoritoDog I see that codelab example (flower classification) shows moblenetv2 training with 0-1 based pre-processing, but in android after tflite conversion in floating point model, they use -1, 1 based preprocessing.
Could you please help by justifying or confirming that its wrong there.
