### ISSUE TITLE
Misleading error message when using "empty" variables

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#2099]
The code below fails with "Attempting to use uninitialized value Variable". This came up [here](http://stackoverflow.com/questions/36763913/tensorflow-failedpreconditionerror-but-all-variables-have-been-initialized) and makes debugging harder. Maybe instead it should fail during Variable creation or Shape inference with "Variable must have non-zero size"

sess = tf.InteractiveSession()
empty = np.zeros(shape=(0, 0) )
a = tf.Variable(empty)
sess.run(tf.initialize_all_variables())
sess.run(tf.reduce_sum(a))

**Comment by girving** [comment]
There's no reason to restrict variables to have nonzero size.  I'll fix.
