### ISSUE TITLE
CheckpointSaverListener before_save

### ISSUE THREAD

**Issue by DLFaker** [tensorflow/tensorflow#20992]
code:
```
--->listener

 listeners = [
            EvalListener(estimator,
                         lambda: input.input_fn(mode=tf.estimator.ModeKeys.EVAL, params=params,
                                                data_path=params.eval_dir))
        ]

--->train 
        estimator.train(input_fn=train_input_fn, max_steps=FLAGS.max_steps, saving_listeners=listeners)

class EvalListener(CheckpointSaverListener):
    def __init__(self, parent, input_fn, name='eval_data'):

        self.parent = parent
        self.input_fn = input_fn
        self.name = name
        self.history = {}
---> before save
    def before_save(self, session, global_step_value):
        accuracy_spec = self.parent.evaluate(input_fn=self.input_fn, name=self.name)
        for k, v in sorted(six.iteritems(accuracy_spec)):
            if k == ACCU_HEAD:
                if v >= self.history[k][1]:
                    #   TODO
                    #   if this time is better than last time, the model will be save
                    print()
```
i'd wonder whether i can save the model when the accuracy score is better than last, if not the model will not be saved!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by DLFaker** [comment]
sorry, 
ubuntu OS
tensorflow gpu 1.8
i wonder know whether i can stop the model to be saved if current accuracy is not better than last time, what i can do in the CheckpointSaverListener's before_save function.

**Comment by drpngx** [comment]
AFAIK you can't use the hook to save. You could probably override the Saver object, but probably what you want to do is to modify the outer scope calling the saving.

**Comment by drpngx** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
