### ISSUE TITLE
Cannot set random_seed for DNNClassifier

### ISSUE THREAD

**Issue by AdamPWhite** [tensorflow/tensorflow#20995]
### System information
My own code 
Windows 10
Python 3.6.5
Tensorflow 1.9 (problem also occurs with 1.8)
NVIDIA GeForce GTX 1050 (approx total memory 6011MB)
CUDA version 9.0 v9.0.176

Problem Description
Each time I run the code below, I get a different 'Loss for final step' when training my model. I have checked that the input data from train_test_split is constant. I have set the value of tf.random_seed, turned off shuffling and set the value of num_threads.  
Looking at INFO, I can see that when training my model, the config file has _tf_random_seed set to 'None'.  There does not appear to be a way of setting this  for tf.estimator.DNNClassifier. The only solution I have found is to 'hack' run_config.py and set random_seed there. Is this a serious flaw with tf.estimator.DNNClassifier or am I missing something?

from __future__ import print_function
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split

np.random.seed(1)
tf.set_random_seed(50)

df = pd.read_csv('diabetes.csv')
X = df.iloc[:,0:8]
y = df['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                   stratify=None, random_state=1)

def create_feature_cols():
  return [
    tf.feature_column.numeric_column('Pregnancies'),
    tf.feature_column.numeric_column('Glucose'),
    tf.feature_column.numeric_column('BloodPressure'),
    tf.feature_column.numeric_column('SkinThickness'),
    tf.feature_column.numeric_column('Insulin'),
    tf.feature_column.numeric_column('BMI'),
    tf.feature_column.numeric_column('DiabetesPedigreeFunction'),
    tf.feature_column.numeric_column('Age')
  ]

input_func = tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,
             batch_size=10,num_epochs=1000,shuffle=False,num_threads=1)
model  =  tf.estimator.DNNClassifier(hidden_units=[20,20],
          feature_columns=create_feature_cols(),n_classes=2)
model.config._tf_random_seed=1
tf.set_random_seed(1)
model.train(input_fn=input_func,steps=1000)

eval_input_func = tf.estimator.inputs.pandas_input_fn(
      x=X_test,
      y=y_test,
      batch_size=10,
      num_epochs=1,
      shuffle=False,
      num_threads=1)
results = model.evaluate(eval_input_func)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by AdamPWhite** [comment]
OS Platform and Distribution : **Windows 10**
TensorFlow installed from: **Anaconda installation**
TensorFlow **version 1.9 (problem also occurs with 1.8) running with Python 3.6.5**
Bazel version: **N\A**
CUDA/cuDNN version: **CUDA version 9.0 v9.0.176**
GPU model and memory: **NVIDIA GeForce GTX 1050 (approx total memory 6011MB)**
Exact command to reproduce: **N\A**
Mobile device: **N\A**

**Comment by tanzhenyu** [comment]
I thought estimator random seed is set through RunConfig, not through tf.set_random_seed().
So the thing you could do here is initialize your constructor in this way:
config = tf.RunConfig(tf_random_seed=???)
clf = DNNClassifier(hidden_units=[20,20],
feature_columns=create_feature_cols(),n_classes=2, config=config)

Can you try this and let us know if it works?

**Comment by AdamPWhite** [comment]
Hi
I tried the above code but got the message:

"AttributeError: module 'tensorflow' has no attribute 'RunConfig'"

I then tried:

 config = tf.estimator.RunConfig(tf_random_seed=234)

but this also failed. Finally I tried:

config = tf.contrib.learn.RunConfig(tf_random_seed=234)

This works! Is using contrib.learn the best way to set the random seed?

Thanks

**Comment by tanzhenyu** [comment]
when you run 'config = tf.estimator.RunConfig(tf_random_seed=234)', what failed?

**Comment by AdamPWhite** [comment]
ValueError: config must be an instance of RunConfig, but provided <tensorflow.python.estimator.run_config.RunConfig object at 0x000002179AEF3A20>.

**Comment by tanzhenyu** [comment]
@AdamPWhite I don't have your dataset so I can't test for you. But below please find my code snippet which works fine:

import tensorflow as tf
tf.reset_default_graph()
config = tf.estimator.RunConfig(tf_random_seed=234)

input1_col = tf.feature_column.numeric_column('input1')
input2_col = tf.feature_column.numeric_column('input2')
model = tf.estimator.DNNClassifier(hidden_units=[20,20],
feature_columns=[input1_col, input2_col],n_classes=2,config=config)

import numpy as np
input1 = np.random.random(size=(100, 1))
input2 = np.random.random(size=(100, 1))
target = np.where(np.sum(input1 + input2, axis = 1) > 0, 1, 0)
def train_input_fn():
  return ({'input1': input1, 'input2': input2}, target)

model.train(input_fn=train_input_fn, steps = 10)

# result:
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmp70021xj7/model.ckpt.
INFO:tensorflow:loss = 61.109077, step = 1
INFO:tensorflow:Saving checkpoints for 10 into /tmp/tmp70021xj7/model.ckpt.
INFO:tensorflow:Loss for final step: 1.6393224.
<tensorflow.python.estimator.canned.dnn.DNNClassifier at 0x7f0fb18c6ef0>

**Comment by AdamPWhite** [comment]
Hi
I guess there must be some difference as to how our systems are configured as I have to use  tf.contrib.learn.RunConfig(tf_random_seed=234). However, this is good enough for me, so let's close the case. Many thanks for your help.

**Comment by tanzhenyu** [comment]
The only difference I see is tf version. I'm using 1.10.
