### ISSUE TITLE
GPU_Base dockerfile image not found

### ISSUE THREAD

**Issue by sibleyd** [tensorflow/tensorflow#21]
I'm attempting to use the GPU dockerfile to build an image with gpu support, however it points at b.gcr.io/tensorflow-testing/tensorflow-full which doesn't appear to be accessible. The image at b.gcr.io/tensorflow/tensorflow-full doesn't have CUDA in it, is there a different image I need to point the script at?

**Comment by craigcitro** [comment]
hey @sibleyd -- yes, that Dockerfile was still undergoing a little churn. An updated version will come along shortly, and I'll update this issue as soon as it's ready.

The image is already up: b.gcr.io/tensorflow/tensorflow-full-gpu ... you'll need to follow [these instructions](http://tensorflow.org/get_started/os_setup.md#install_cuda) to pick up the CUDA libraries. The Dockerfile will assume those files are available locally (which is the missing `cuda/` path you spotted).

**Comment by craigcitro** [comment]
hey @sibleyd -- this should be cleaned up now:

* Back to a [single Dockerfile](../blob/master/tensorflow/tools/docker/Dockerfile.gpu_base)
* Complete instructions (well, with pointers) in [the README](../blob/master/tensorflow/tools/docker/README.md)

**Comment by craigcitro** [comment]
Closing for now, but reopen if you hit issues.
