### ISSUE TITLE
Error during tf.evaluate when running on TPU: RuntimeError: All tensors outfed from TPU should preserve batch size dimension, but got scalar 

### ISSUE THREAD

**Issue by mrezak** [tensorflow/tensorflow#21001]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Cloud Platform (Linux Debian)
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:Binary
- **TensorFlow version (use command below)**:1.9
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: NA (TPU)
- **GPU model and memory**: NA (TPU)
- **Exact command to reproduce**:

### Describe the problem
I am using TPU on GCP to train my model. My model is fully TPU compatible and the training on TPU works as expected when I run `model.train(train_input, steps=num_steps)`. However, when I want to evaluate the model using `train_costs = lfads.evaluate(train_input, name='train_data', steps=100)` I get the following error:

`RuntimeError: All tensors outfed from TPU should preserve batch size dimension, but got scalar Tensor("OutfeedDequeueTuple:0", shape=(), dtype=float32, device=/job:worker/task:0/device:TPU:0)`

I constructed the `eval_metrics` in `TPUEstimatorSpec` as described in the MNIST example passing a tuple of (metric_fn, [tensors]) as
```
def m_fn(input):
       return {'test':tf.metrics.mean(input)}
tpu_eval_metrics = (m_fn, [rec_costs])
```

I used the same `input_fn` both for train and evaluate. I also used the same `TPUEstimatorSpec` line in my `model_fn` for training/evaluation. I cannot figure out what is causing this error and didn't have any luck searching online. 

**Note:** I tested the same code but for CPU/GPU and did not run into any errors during evaluation

### Source code / logs
`RuntimeError: All tensors outfed from TPU should preserve batch size dimension, but got scalar Tensor("OutfeedDequeueTuple:0", shape=(), dtype=float32, device=/job:worker/task:0/device:TPU:0)`

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by xaviergonzalez** [comment]
@mrezak did you ever figure out what was going on? I am having the same problem

**Comment by pxxgogo** [comment]
I met the same problem before. I think you should make sure that the parameters of the metrics_fn should be the tensors with the same shape of labels (i.e. the first dimension of these tensors should be the batch size).

**Comment by RobRomijnders** [comment]
For anyone reaching this issue later: I had the same problem as @pxxgogo. My metrics_fn output a scalar instead of a tensor. Thanks @pxxgogo for making the suggestion.
