### ISSUE TITLE
C++: Add gradient for image operators

### ISSUE THREAD

**Issue by kbsriram** [tensorflow/tensorflow#21019]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
N/A
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
v1.4.0-19-ga52c8d9 1.4.1
- **Python version**:
3.5.2 (default, Nov 23 2017, 16:37:01) 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
Feature request: Add gradient support for the image operators in the C++ API.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Mobile device

**Comment by kbsriram** [comment]
Updated

**Comment by michaelisard** [comment]
As I understand it this issue is here just so it can be referred to by the PR, and no action is needed while that PR is in flight. If that's wrong, please let me know!

**Comment by kbsriram** [comment]
Thanks Michael, yes - that's pretty much it. There is one more image op (`CropAndResize`) that's not covered by the in-flight PR. So if you think it makes sense, could keep the issue open till someone contributes a PR for this last op in the image group.

**Comment by michaelisard** [comment]
Sounds good to me.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by a6802739** [comment]
@tensorflowbutler, Could I have a try for my first contribution? Thanks.

**Comment by rmothukuru** [comment]
@kbsriram,
Can you please confirm if we can close this issue as the [in-flight PR](https://github.com/tensorflow/tensorflow/pull/21021) and the [PR corresponding to Image OP](https://github.com/tensorflow/tensorflow/pull/25467) has been merged? Thanks!

**Comment by kbsriram** [comment]
@rmothukuru - great! Thanks for checking, I'll go ahead and close it.
