### ISSUE TITLE
keras model to estimator in eager mode does not support the use of nested subclassed models

### ISSUE THREAD

**Issue by bosmart** [tensorflow/tensorflow#21016]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes, code attached below.

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 18.04

- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
N/A

- **TensorFlow installed from (source or binary)**:
From source

- **TensorFlow version (use command below)**:
b'v1.9.0-rc2-999-g78909bf81e' 1.9.0

- **Python version**:
3.6.6

- **Bazel version (if compiling from source)**:
0.16.0rc3

- **GCC/Compiler version (if compiling from source)**:
6

- **CUDA/cuDNN version**:
9.1 / 7.1

- **GPU model and memory**:
Titan X, 12GB

- **Exact command to reproduce**:
Run the attached code.

### Describe the problem
This is more of a feature request to add support for the use of nested subclassed models within keras model to estimator eager mode. There is a comment in the relevant section of the code (estimator/keras.py) which says:

    # This will not work for nested subclassed models used as layers.
    # This would be theoretically possible to support, but would add complexity.
    # Only do it if users complain.

### Source code / logs
```
import copy
import tensorflow as tf

tf.enable_eager_execution()
tf.logging.set_verbosity(tf.logging.INFO)

class BaseModel(tf.keras.Model):
    def __init__(self):
        super(BaseModel, self).__init__()
        self.dense1 = tf.keras.layers.Dense(units=10)
        self.dense2 = tf.keras.layers.Dense(units=1)
    def call(self, input):
        """Run the model."""
        result = self.dense1(input)
        result = self.dense2(result)
        return result
    def get_config(self):
        config = []
        for layer in self.layers:
            config.append({
                'class_name': layer.__class__.__name__,
                'config': layer.get_config()
            })
        return copy.deepcopy(config)

class NestedModel(tf.keras.Model):
    def __init__(self):
        super(NestedModel, self).__init__()
        self.base_model = BaseModel()
        self.dense = tf.keras.layers.Dense(units=1)
    def call(self, input):
        result = self.base_model(input)
        result = self.dense(result)
        return result
    def get_config(self):
        config = []
        for layer in self.layers:
            config.append({
                'class_name': layer.__class__.__name__,
                'config': layer.get_config()
            })
        return copy.deepcopy(config)

model = NestedModel()
model.compile(optimizer=tf.train.AdamOptimizer(learning_rate=0.0001), loss='mean_squared_error', metrics=['accuracy'])
estimator = tf.keras.estimator.model_to_estimator(keras_model=model)
estimator.train(input_fn=lambda: tf.data.Dataset.from_tensor_slices((tf.random_uniform([100, 10]), tf.random_uniform([100, ]))).batch(2).repeat(10))
```

**Comment by tanzhenyu** [comment]
This is already done in latest version. Please compile up to master version. Thanks.

**Comment by bosmart** [comment]
Still not working - the exceptions comes from `tensorflow/python/estimator/keras.py`, I think you were referring to commit `d2f3441c0c` ("Added support for build on subclass models"), which doesn't fix it for the Estimator API.

**Comment by tanzhenyu** [comment]
No I am referring to this #20377

**Comment by tanzhenyu** [comment]
Or this commit:
https://github.com/tensorflow/tensorflow/commit/f83a382e87ca09e8f688515a9549c81d0f46554a

I changed it to use _any_weight_initialized, not sure why it's still seeing _any_variable_initialized here.

**Comment by bosmart** [comment]
Yeah, had this problem too, but this one is different.

**Comment by bosmart** [comment]
Either way, I built master a few hours ago and it still throws the exception.

**Comment by tanzhenyu** [comment]
It should be updated in master branch:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/keras.py

Can you run tf.__version__ and print the output?

**Comment by bosmart** [comment]
b'v1.9.0-rc2-1241-g3f454e4060' 1.9.0

**Comment by tanzhenyu** [comment]
should be 1.10 that fixes the issue.

**Comment by nishprabhu** [comment]
tf.keras.estimator.model_to_estimator doesn't seem to support nested subclassed models even without eager execution enables in 1.12

**Comment by nishprabhu** [comment]
Any update on this?
