### ISSUE TITLE
Waste lots of time to redownload grpc when building with CMake

### ISSUE THREAD

**Issue by imistyrain** [tensorflow/tensorflow#21018]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 7 64 bit.
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:No.
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.9
- **Python version**:3.5
- **Bazel version (if compiling from source)**:No.
- **GCC/Compiler version (if compiling from source)**:VS2015
- **CUDA/cuDNN version**:CUDA 8.0 and cuDnn 7.0.
- **GPU model and memory**:No.
- **Exact command to reproduce**:
```
cd $TENDORFLOW_DIR/tensorflow/contrib/cmake
cmake .
make -j20
```

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

I want to build tensorflow from source with CMake in Windows, but it fails with the error caused by the fail of gprc. I wonder if there is a way to avoid the redownload gprc when rebuilding form source.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

29>  Creating directories for 'grpc'
29>  Cloning into 'grpc'...
29>  Performing download step (git clone) for 'grpc'
29>  fatal: unable to access 'https://boringssl.googlesource.com/boringssl/': Failed to connect to boringssl.googlesource.com port 443: Timed out
29>  fatal: clone of 'https://boringssl.googlesource.com/boringssl' into submodule path 'D:/CNN/tensorflow/BUILD/grpc/src/grpc/third_party/boringssl-with-bazel' failed
29>  Failed to clone 'third_party/boringssl-with-bazel'. Retry scheduled
29>  Failed to clone 'third_party/boringssl-with-bazel' a second time, aborting
29>  CMake Error at D:/CNN/tensorflow/BUILD/grpc/tmp/grpc-gitclone.cmake:93 (message):
29>  Failed to update submodules in: 'D:/CNN/tensorflow/build/grpc/src/grpc'

**Comment by michaelisard** [comment]
I think that package is required. I don't know why you were having trouble downloading but I hope that the connection is working now. I will close for now assuming you were able to build, but please reopen if I have misunderstood.

**Comment by imistyrain** [comment]
Yes, I know grpc is required. But what we need is incremential downloading, not redownload the whole package when failed to build the project. As you known, the grpc is more than 200M! My network is not good and every time in rebuilding it takes serval hours to download the grpc package.
The url of [boringssl](https://boringssl.googlesource.com/boringssl) is not accesible under the Great Firewall of China.

**Comment by michaelisard** [comment]
I see I'm sorry thanks for clarifying. @mrry do you think this is something that would be feasible without heroic effort?

**Comment by mrry** [comment]
It sounds like it should be possible, but we'll need someone with more CMake expertise to suggest a fix, so I'll mark this as "contributions welcome".

As a potential lead, the `UPDATE_DISCONNECTED` option seems relevant:

* https://github.com/Kitware/CMake/blob/5bbcf76399e107bbb1712ba8aeee27c160413d2d/Modules/ExternalProject.cmake#L320-L338
* https://stackoverflow.com/q/36254658/3574081

**Comment by michaelisard** [comment]
A couple of days ago the Windows build was switched over to use bazel instead of cmake. That doesn't solve your problem, but it means the best solution now is going to be a feature request to the bazel team I think. Sorry not to be more help.
