### ISSUE TITLE
Building TensorFlow failed

### ISSUE THREAD

**Issue by timur-st94** [tensorflow/tensorflow#21045]
### Issue
I'm trying to build the .so file using bazel
`bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a`  
Getting an error:

```
tensorflow/core/BUILD:2306:1: C++ compilation of rule '//tensorflow/core:protos_all_proto_cc_impl' failed (Exit 1)
In file included from bazel-out/armeabi-v7a-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.cc:4:
In file included from bazel-out/armeabi-v7a-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.h:9:
In file included from external/protobuf_archive/src/google/protobuf/stubs/common.h:52:
In file included from external/protobuf_archive/src/google/protobuf/stubs/mutex.h:33:
In file included from external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/mutex:35:
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/c++0x_warning.h:32:2: error: This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
#error This file requires compiler and library support for the \
 ^
In file included from bazel-out/armeabi-v7a-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.cc:4:
In file included from bazel-out/armeabi-v7a-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.h:9:
In file included from external/protobuf_archive/src/google/protobuf/stubs/common.h:52:
external/protobuf_archive/src/google/protobuf/stubs/mutex.h:58:8: error: no type named 'mutex' in namespace 'std'
  std::mutex mu_;

In file included from bazel-out/armeabi-v7a-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.cc:4:
In file included from bazel-out/armeabi-v7a-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.h:9:
In file included from external/protobuf_archive/src/google/protobuf/stubs/common.h:53:
external/protobuf_archive/src/google/protobuf/stubs/callback.h:346:25: error: no type named 'remove_reference' in namespace 'std'
  typedef typename std::remove_reference<T>::type base_type;
 
external/protobuf_archive/src/google/protobuf/stubs/callback.h:346:41: error: expected member name or ';' after declaration specifiers
  typedef typename std::remove_reference<T>::type base_type;

external/protobuf_archive/src/google/protobuf/stubs/callback.h:347:17: error: unknown type name 'base_type'
  typedef const base_type& type;
                
external/protobuf_archive/src/google/protobuf/stubs/callback.h:401:17: error: no type named 'remove_reference' in namespace 'std'
  typename std::remove_reference<P1>::type p1_;

external/protobuf_archive/src/google/protobuf/stubs/callback.h:401:33: error: expected member name or ';' after declaration specifiers
  typename std::remove_reference<P1>::type p1_;

external/protobuf_archive/src/google/protobuf/stubs/callback.h:402:17: error: no type named 'remove_reference' in namespace 'std'
  typename std::remove_reference<P2>::type p2_;

external/protobuf_archive/src/google/protobuf/stubs/callback.h:402:33: error: expected member name or ';' after declaration specifiers
  typename std::remove_reference<P2>::type p2_;

external/protobuf_archive/src/google/protobuf/stubs/callback.h:403:17: error: no type named 'remove_reference' in namespace 'std'
  typename std::remove_reference<P3>::type p3_;

external/protobuf_archive/src/google/protobuf/stubs/callback.h:403:33: error: expected member name or ';' after declaration specifiers
  typename std::remove_reference<P3>::type p3_;

external/protobuf_archive/src/google/protobuf/stubs/callback.h:404:17: error: no type named 'remove_reference' in namespace 'std'
  typename std::remove_reference<P4>::type p4_;

external/protobuf_archive/src/google/protobuf/stubs/callback.h:404:33: error: expected member name or ';' after declaration specifiers
  typename std::remove_reference<P4>::type p4_;

external/protobuf_archive/src/google/protobuf/stubs/callback.h:405:17: error: no type named 'remove_reference' in namespace 'std'
  typename std::remove_reference<P5>::type p5_;

external/protobuf_archive/src/google/protobuf/stubs/callback.h:405:33: error: expected member name or ';' after declaration specifiers
  typename std::remove_reference<P5>::type p5_;

external/protobuf_archive/src/google/protobuf/stubs/callback.h:383:9: error: member initializer 'p1_' does not name a non-static data member or base class
        p1_(p1),

external/protobuf_archive/src/google/protobuf/stubs/callback.h:384:9: error: member initializer 'p2_' does not name a non-static data member or base class
        p2_(p2),

external/protobuf_archive/src/google/protobuf/stubs/callback.h:385:9: error: member initializer 'p3_' does not name a non-static data member or base class
        p3_(p3),

external/protobuf_archive/src/google/protobuf/stubs/callback.h:386:9: error: member initializer 'p4_' does not name a non-static data member or base class
        p4_(p4)
```

### System information
OS:
 macOS High Sierra 10.13.3

bazel: 
`Build label: 0.15.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 26 12:42:27 2018 (1530016947)
Build timestamp: 1530016947
Build timestamp as int: 1530016947`

ndk:
android-ndk-r16b

I looked similar problems, like [#3924](https://github.com/bazelbuild/bazel/issues/3924) or [#17046](https://github.com/tensorflow/tensorflow/issues/17046), but unfortunately did not find a solution for himself. 

Thank you in advance.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by timur-st94** [comment]
### Have I written custom code
N/A

### OS Platform and Distribution
macOS High Sierra 10.13.3 (17D47)

### TensorFlow installed from
I used "native" pip command for install TensorFlow

### TensorFlow version
1.5.0

### Bazel version
Build label: 0.15.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 26 12:42:27 2018 (1530016947)
Build timestamp: 1530016947
Build timestamp as int: 1530016947

### CUDA/cuDNN version
I am not using CUDA/cuDNN

### GPU model and memory
ATI Radeon HD 4670 256 МБ

### Exact command to reproduce
`bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a`

### Mobile device
N/A

**Comment by fdchiu** [comment]
I was trying to make the same build as OP. I got the same errors. I was using ndk14b though.

**Comment by timur-st94** [comment]
Have any solutions about my issue?

**Comment by kjancke** [comment]
+1

**Comment by kjancke** [comment]
I am on Linux though, using ndk14b. Also tried with ndk17

**Comment by kjancke** [comment]
not sure if it helps, but this is the executed commandline: /home/karsten/tensorflow/tensorflow/core/BUILD:2306:1: C++ compilation of rule '//tensorflow/core:protos_all_proto_cc_impl' failed (Exit 1): clang failed: error executing command 
  (cd /home/karsten/.cache/bazel/_bazel_karsten/c3148022e5394457e9b87b7ac08211f4/execroot/org_tensorflow && \
  exec env - \
    ANDROID_BUILD_TOOLS_VERSION=27.0.3 \
    ANDROID_NDK_API_LEVEL=14 \
    ANDROID_NDK_HOME=/home/karsten/Android/android-ndk-r14b \
    ANDROID_SDK_API_LEVEL=24 \
    ANDROID_SDK_HOME=/home/karsten/Android/Sdk \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/armeabi-v7a-opt/bin/tensorflow/core/_objs/protos_all_proto_cc_impl/tensorflow/core/framework/allocation_description.pb.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/tensorflow/core/_objs/protos_all_proto_cc_impl/tensorflow/core/framework/allocation_description.pb.o' -iquote . -iquote bazel-out/armeabi-v7a-opt/genfiles -iquote external/protobuf_archive -iquote bazel-out/armeabi-v7a-opt/genfiles/external/protobuf_archive -iquote external/bazel_tools -iquote bazel-out/armeabi-v7a-opt/genfiles/external/bazel_tools -isystem external/protobuf_archive/src -isystem bazel-out/armeabi-v7a-opt/genfiles/external/protobuf_archive/src -isystem bazel-out/armeabi-v7a-opt/bin/external/protobuf_archive/src -Wno-unknown-warning-option -Wno-unused-but-set-variable -Wno-sign-compare '--sysroot=external/androidndk/ndk/platforms/android-24/arch-arm' -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -c bazel-out/armeabi-v7a-opt/genfiles/tensorflow/core/framework/allocation_description.pb.cc -o bazel-out/armeabi-v7a-opt/bin/tensorflow/core/_objs/protos_all_proto_cc_impl/tensorflow/core/framework/allocation_description.pb.o)

**Comment by timur-st94** [comment]
Issue solved, just building with the --cxxopt=-std=c++11 flag

**Comment by kjancke** [comment]
Is this fix upstream, or do I have to set it somewhere myself. If so, where do I set this parameter?

**Comment by timur-st94** [comment]
Example 
`bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a --cxxopt=-std=c++11`

**Comment by kjancke** [comment]
That works, thanks a lot. Should be updated here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/android ?

**Comment by cusitkhan** [comment]
my issue could not solve with this ....

**Comment by cusitkhan** [comment]
pleas help mee

**Comment by pranavj7Z** [comment]
I am still getting error.

**Comment by sodiumLights** [comment]
Still getting the error

Command: `bazel build -c opt --cxxopt=-std=c++11 --copt=-D__ANDROID_TYPES_FULL__ //tensorflow/contrib/android:libtensorflow_inference.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a  --verbose_failures`

Error:
`ERROR: /private/var/tmp/_bazel_ivlab/23994111945cccf7235ecf4d9dc9fbce/external/com_google_absl/absl/numeric/BUILD.bazel:26:1: C++ compilation of rule '@com_google_absl//absl/numeric:int128' failed (Exit 1): clang failed: error executing command 
  (cd /private/var/tmp/_bazel_ivlab/23994111945cccf7235ecf4d9dc9fbce/execroot/org_tensorflow && \
  exec env - \
    ANDROID_BUILD_TOOLS_VERSION=28.0.3 \
    ANDROID_NDK_API_LEVEL=21 \
    ANDROID_NDK_HOME=/Users/ivlab/Downloads/android-ndk-r14b/ \
    ANDROID_SDK_API_LEVEL=28 \
    ANDROID_SDK_HOME=/Users/ivlab/library/Android/Sdk \
    PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ivlab/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 \
    PYTHON_LIB_PATH=/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages \
    TF_CONFIGURE_IOS=0 \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=0 \
  external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/armeabi-v7a-opt/bin/external/com_google_absl/absl/numeric/_objs/int128/int128.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/external/com_google_absl/absl/numeric/_objs/int128/int128.o' -iquote external/com_google_absl -iquote bazel-out/armeabi-v7a-opt/genfiles/external/com_google_absl -iquote bazel-out/armeabi-v7a-opt/bin/external/com_google_absl -D__ANDROID_TYPES_FULL__ '-std=c++11' -Wall -Wextra -Wcast-qual -Wconversion-null -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wunused-local-typedefs -Wunused-result -Wvarargs -Wvla -Wwrite-strings -Wno-missing-field-initializers -Wno-sign-compare '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm' -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -c external/com_google_absl/absl/numeric/int128.cc -o bazel-out/armeabi-v7a-opt/bin/external/com_google_absl/absl/numeric/_objs/int128/int128.o)
Execution platform: @bazel_tools//platforms:host_platform
external/com_google_absl/absl/numeric/int128.cc:139:59: error: no member named 'trunc' in namespace 'std'; did you mean simply 'trunc'?
  uint64_t w0 = static_cast<uint64_t>(static_cast<double>(std::trunc(v)));
                                                          ^~~~~~~~~~
                                                          trunc
external/androidndk/ndk/platforms/android-21/arch-arm/usr/include/math.h:278:8: note: 'trunc' declared here
double  trunc(double);
        ^
external/com_google_absl/absl/numeric/int128.cc:141:59: error: no member named 'trunc' in namespace 'std'; did you mean simply 'trunc'?
  uint64_t w1 = static_cast<uint64_t>(static_cast<double>(std::trunc(v)));
                                                          ^~~~~~~~~~
                                                          trunc
external/androidndk/ndk/platforms/android-21/arch-arm/usr/include/math.h:278:8: note: 'trunc' declared here
double  trunc(double);
        ^
external/com_google_absl/absl/numeric/int128.cc:143:59: error: no member named 'trunc' in namespace 'std'; did you mean simply 'trunc'?
  uint64_t w2 = static_cast<uint64_t>(static_cast<double>(std::trunc(v)));
                                                          ^~~~~~~~~~
                                                          trunc
external/androidndk/ndk/platforms/android-21/arch-arm/usr/include/math.h:278:8: note: 'trunc' declared here
double  trunc(double);
        ^
3 errors generated.
Target //tensorflow/contrib/android:libtensorflow_inference.so failed to build`

**Comment by cusitkhan** [comment]
dear this is insoloble still we also face this....
