### ISSUE TITLE
Faile to run tensorflow 

### ISSUE THREAD

**Issue by liumilan** [tensorflow/tensorflow#2105]
I just want to install the tensorflow using pip.
$ sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
and it succeed.

And I run python -c "import tensorflow;it will report
ImportError: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /usr/local/python2710/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so)

And I tried to upgrade GLIBC_2.15,and then now it reported that
ImportError: /opt/glibc-2.15/lib/libc.so.6: version `GLIBC_2.17' not found (required by /usr/local/python2710/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.s

And then tried to upgrade to GLIBC_2.17,and then type ls ,the error as below:
ls: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument

My machine is 
Linux sjs_88_78 2.6.32-504.23.4.el6.x86_64 #1 SMP Fri May 29 10:16:43 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by poxvoculi** [comment]
Sorry you're having trouble.  Did you previously install another version of tensorflow?  If so, you must use pip uninstall to remove the first installation before trying to upgrade.  If you have an unusual linux distribution it may be necessary to install from sources by configuring and compiling on your machine.

**Comment by liumilan** [comment]
It is the first time I tried to install the tensorflow
I just also tried to install from sources,but it still failed when install bazel

**Comment by EdwardHux** [comment]
I have the same problem too! Have you solved this problem?

**Comment by girving** [comment]
@liumilan: It does sound like you'll need to install from source.  I'm going to close this bug for now: if you still have issues please reopen a separate bug about the problems installing from source.
