### ISSUE TITLE
there is still an isue with cuda 9.1

### ISSUE THREAD

**Issue by fenix7** [tensorflow/tensorflow#21059]
the problem in isue CUDA 9.1 Support #18961 is still unsolved is the any good workaround

**Comment by fenix7** [comment]
i Think tat my iissu is the same like #21074

**Comment by reedwm** [comment]
It looks like eventually TensorFlow will use Cuda 9.2, and 9.1 will be skipped. See #18906. If you want to use Cuda 9.1, you have to compile from source.
