### ISSUE TITLE
writing tfrecord with multithreading is not fast as expected

### ISSUE THREAD

**Issue by hbi-tianyi** [tensorflow/tensorflow#21069]
System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 16.04 and MacOS High Sierra 10.13.4
TensorFlow installed from (source or binary): docker and virtualenv
TensorFlow version (use command below): v1.8.0-0-g93bc2e2072
Python version: 2.7.12
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
Exact command to reproduce: N/A

### Describe the problem
Tried to write tfrecord w/ and w/o multithreading, and found the speed difference is not much (w/ 4 threads: 434 seconds; w/o multithread 590 seconds).  Not sure if I used it correctly. Is there any better way to write tfrecord faster?

### Source code / logs

```
import tensorflow as tf 
import numpy as np 
import threading 
import time 


def generate_data(shape=[15,28,60,1]):
	return np.random.uniform(size=shape)


def _bytes_feature(value):
	return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))


def _int64_feature(value):
	return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))


def write_instances_to_tfrecord(tfrecord_file, filenames):
	tfrecord_writer = tf.python_io.TFRecordWriter(tfrecord_file)
	for i, filename in enumerate(filenames):
		curr_MFCC = generate_data()
		curr_MFCC_raw = curr_MFCC.tostring()
		curr_filename_raw = str(filename)+'-'+str(i)
		example = tf.train.Example(features=tf.train.Features(
			feature={
			'MFCC': _bytes_feature(curr_MFCC_raw),
			'filename': _bytes_feature(curr_filename_raw)
			})
		)
		tfrecord_writer.write(example.SerializeToString())
	tfrecord_writer.close()


def test():
	threading_start = time.time()
	coord = tf.train.Coordinator()
	threads = []
	for thread_index in xrange(4):
		args = (str(thread_index), range(200000))
		t = threading.Thread(target=write_instances_to_tfrecord, args=args)
		t.start()
		threads.append(t)
	coord.join(threads)
	print 'w/ threading takes', time.time()-threading_start

	start = time.time()
	write_instances_to_tfrecord('5', range(800000))
	print 'w/o threading takes', time.time()-start

if __name__ == '__main__':
	test()
```

**Comment by karmel** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
