### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wmcnally** [tensorflow/tensorflow#21074]
I have tensorflow-gpu 1.9 installed for python3.5 system environment. I have cuda 9.0 installed. I do not have any other versions of cuda installed. I verified that libcublas.so.9.0 is located in /usr/local/cuda-9.0/lib64. I added the following to my ~/.bashrc file, as per the NVIDIA docs:
```
export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64\
                         ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```
I still get this error. Please help. Thank you.

ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

**Comment by dhgokul** [comment]
You can set cuda library using below command for this issue
export LD_LIBRARY_PATH="/usr/local/cuda-8.0/lib64"
export LD_LIBRARY_PATH="/usr/local/cuda-8.0/lib64"

**Comment by wmcnally** [comment]
@dhgokul that did not work. I am using cuda-9.0, so why would that command work? Why did you write the command twice?

**Comment by wmcnally** [comment]
Fixed. I think it was because I was using PyCharm in the system environment. I had to set the variables in my system environment, not in ~/.bashrc: 

sudo gedit /etc/environment

PATH="**/usr/local/cuda-9.0/bin:**/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

LD_LIBRARY_PATH="/usr/local/cuda-9.0/lib64"
