### ISSUE TITLE
[Building Error] No rule to make target

### ISSUE THREAD

**Issue by daben218** [tensorflow/tensorflow#21089]
+ set -e
+++ dirname tensorflow/contrib/lite/build_ios_universal_lib.sh
++ cd tensorflow/contrib/lite
++ pwd
+ SCRIPT_DIR=/Users/ctr-daben/desktop/tensorflow-master/tensorflow/contrib/lite
+ cd /Users/ctr-daben/desktop/tensorflow-master/tensorflow/contrib/lite/../../..
+ make_library libtensorflow-lite.a
+ for arch in x86_64 armv7 armv7s arm64
+ make -f tensorflow/contrib/lite/Makefile TARGET=IOS IOS_ARCH=x86_64 -j 8 /Users/ctr-daben/desktop/tensorflow-master/tensorflow/contrib/lite/gen/lib/ios_x86_64/libtensorflow-lite.a
/Users/ctr-daben/Desktop/tensorflow-master/tensorflow/contrib/lite/gen/bin/ios_x86_64/benchmark_model
make: *** No rule to make target `/Users/ctr-daben/desktop/tensorflow-master/tensorflow/contrib/lite/gen/lib/ios_x86_64/libtensorflow-lite.a'.  Stop.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by daben218** [comment]
Have I written custom code    N
OS Platform and Distribution   macOS High Sierra 10.13.4 (17E202)
TensorFlow installed from   github
TensorFlow version   tensorflow-master
Bazel version   0.15.2
CUDA/cuDNN version    N
GPU model and memory N
Exact command to reproduce  tensorflow/contrib/lite/build_ios_universal_lib.sh
Mobile device  iOS

**Comment by daben218** [comment]
Have I written custom code N
OS Platform and Distribution macOS High Sierra 10.13.4 (17E202)
TensorFlow installed from github
TensorFlow version tensorflow-master
Bazel version 0.15.2
CUDA/cuDNN version N
GPU model and memory N
Exact command to reproduce tensorflow/contrib/lite/build_ios_universal_lib.sh
Mobile device iOS

[说明: http://www.ctrchina.cn/ctrwebsite/ctr/signature/logocn1.png]

任江彬
数字业务研究部
+ 86 10 8201 5388*8437 - renjb@ctrchina.cn<mailto:xiahc@ctrchina.cn>

央视市场研究股份有限公司 / CTR Market Research Co., Ltd.
中国北京西城区德外大街5号 邮编100088 / No.5 Dewai Avenue, Xicheng District, Beijing, China
www.ctrchina.cn<http://www.ctrchina.cn/>  / 官方微信WeChat @CTR洞察 / @德外5号 / 新浪微博Weibo @CTR洞察中国

[说明: http://www.ctrchina.cn/ctrwebsite/ctr/signature/logocn2.jpg]
www.ctrchina.cn/disclaimer.html<http://www.ctrchina.cn/disclaimer.html>



 原始邮件
发件人: Alfred Sorten Wolf<notifications@github.com>
收件人: tensorflow/tensorflow<tensorflow@noreply.github.com>
抄送: 任江彬<renjb@CTRCHINA.CN>; Author<author@noreply.github.com>
发送时间: 2018年7月25日(周三) 03:10
主题: Re: [tensorflow/tensorflow] [Building Error] No rule to make target (#21089)


Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by miaout17** [comment]
I tried this in master branch and it worked with no problem. (commit 81d927bfc)
Could you provide more information? (The full console log, git commit hash)
Thanks!

**Comment by IvyGongoogle** [comment]
meet the same error.
