### ISSUE TITLE
3*cycle_length readers are created when using tf.data.Dataset? 

### ISSUE THREAD

**Issue by Jar7** [tensorflow/tensorflow#21088]
Hello, I am creating a tensorflow dataset using the following code.
```
files = 'hdfs://default/testset/*'
ds = tf.data.Dataset.list_files(files)
ds = ds.apply(interleave_ops.parallel_interleave(tf.data.TextLineDataset, cycle_length=1))
ds = ds.shuffle(buffer_size=10000)
ds = ds.map(parse_line)
ds = ds.repeat()
ds = ds.batch(128)
ds = ds.prefetch(1)
iterator = ds.make_one_shot_iterator()
next_element = iterator.get_next()
```
Since the first line of each file is an empty line, I can notice it read 3*cycle_length(here cycle_length=1) files at the beginning from the the following output. After that, it still read files in order(not recurrently).
```
18/07/24 11:07:44 WARN hdfs.DFSClient: zero
18/07/24 11:07:44 WARN hdfs.DFSClient: zero
18/07/24 11:07:44 WARN hdfs.DFSClient: zero
```
I could not find a argument whose default value is 3. Does anyone know why it is 3? Thank you.

**Comment by mrry** [comment]
The default value of `parallel_interleave()`'s `prefetch_input_elements` argument is 2. Thus when the `cycle_length` is 1, there will be 1 + 2 = 3 files opened at the start of execution. I suspect it is not 3 * `cycle_length` for other values of `cycle_length`.

If you want to avoid this behavior, set `prefetch_input_elements` to 0.

**Comment by Jar7** [comment]
Hi, @mrry, thank you for your response. 
You are right that `prefetch_input_elements` is the key. But for the default setting, it did read  3*`cycle_length`, and if I give a value to `prefetch_input_elements`, it reads `prefetch_input_elements+cycle_length` files.
