### ISSUE TITLE
Cannot compile toco on windows

### ISSUE THREAD

**Issue by inakaaay** [tensorflow/tensorflow#21085]
### Error Message
Target //tensorflow/contrib/lite/toco:toco failed to build saying Cannot open include file: 'sys/time.h'

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: none
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows 10
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.9
- **Python version**:  3.5.1-32 bit
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: nothing since i have AMD radeon
- **GPU model and memory**:  Intel(R) HD Graphics 620
- **Exact command to reproduce**:

`bazel run -c opt tensorflow/contrib/lite/toco:toco -- \ --input_file=maonani/tflite_graph.pb \ --output_file=maonani/detect.tflite \ --input_shapes=1,300,300,3 \ --input_arrays=normalized_input_image_tensor \ --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \ --inference_type=QUANTIZED_UINT8 \ --mean_values=128 \ --std_values=128 \ --change_concat_input_ranges=false \ --allow_custom_ops`

### Describe the problem
i have been trying for weeks to convert custom object detection api models to tflite and i have found this article [https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193](url) but i just skip to the part where it converts the resulting frozen graph (tflite_graph.pb) to the TensorFlow Lite flatbuffer format (detect.tflite) and when i run the command that i specified above i get an error saying

```
ERROR: C:/users/lenovo-pc/tensorflow/tensorflow/contrib/lite/profiling/BUILD:37:1: C++ compilation of rule '//tensorflow/contrib/lite/profiling:time' failed (Exit 2)
tensorflow/contrib/lite/profiling/time.cc(17): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
Target //tensorflow/contrib/lite/toco:toco failed to build
```

### Source code / logs

C:\Users\LENOVO-PC\tensorflow> bazel run -c opt tensorflow/contrib/lite/toco:toco -- \ --input_file=maonani/tflite_graph.pb \ --output_file=maonani/detect.tflite \ --input_shapes=1,300,300,3 \ --input_arrays=normalized_input_image_tensor \ --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \ --inference_type=QUANTIZED_UINT8 \ --mean_values=128 \ --std_values=128 \ --change_concat_input_ranges=false \ --allow_custom_ops
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //tensorflow/contrib/lite/toco:toco (60 packages loaded).
INFO: Found 1 target...
INFO: From Compiling external/protobuf_archive/src/google/protobuf/generated_message_reflection.cc [for host]:
external/protobuf_archive/src/google/protobuf/generated_message_reflection.cc(2429): warning C4506: no definition for inline function 'google::protobuf::Message *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::NewFromPrototype(const GenericType *,google::protobuf::Arena *)'
        with
        [
            GenericType=google::protobuf::Message
        ]
external/protobuf_archive/src/google/protobuf/generated_message_reflection.cc(2429): warning C4506: no definition for inline function 'google::protobuf::Arena *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::GetArena(GenericType *)'
        with
        [
            GenericType=google::protobuf::Message
        ]
external/protobuf_archive/src/google/protobuf/generated_message_reflection.cc(2429): warning C4506: no definition for inline function 'void *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::GetMaybeArenaPointer(GenericType *)'
        with
        [
            GenericType=google::protobuf::Message
        ]
INFO: From Compiling external/protobuf_archive/src/google/protobuf/map_field.cc [for host]:
external/protobuf_archive/src/google/protobuf/map_field.cc(465): warning C4506: no definition for inline function 'google::protobuf::Message *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::NewFromPrototype(const GenericType *,google::protobuf::Arena *)'
        with
        [
            GenericType=google::protobuf::Message
        ]
external/protobuf_archive/src/google/protobuf/map_field.cc(465): warning C4506: no definition for inline function 'google::protobuf::Arena *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::GetArena(GenericType *)'
        with
        [
            GenericType=google::protobuf::Message
        ]
external/protobuf_archive/src/google/protobuf/map_field.cc(465): warning C4506: no definition for inline function 'void *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::GetMaybeArenaPointer(GenericType *)'
        with
        [
            GenericType=google::protobuf::Message
        ]
INFO: From Compiling tensorflow/core/platform/default/logging.cc [for host]:
c:\users\lenovo-pc\_bazel_lenovo-pc\buizwhxs\execroot\org_tensorflow\tensorflow\core\platform\default\logging.cc(147) : warning C4722: 'tensorflow::internal::LogMessageFatal::~LogMessageFatal': destructor never returns, potential memory leak
INFO: From Compiling tensorflow/core/platform/default/logging.cc:
c:\users\lenovo-pc\_bazel_lenovo-pc\buizwhxs\execroot\org_tensorflow\tensorflow\core\platform\default\logging.cc(147) : warning C4722: 'tensorflow::internal::LogMessageFatal::~LogMessageFatal': destructor never returns, potential memory leak
INFO: From Compiling external/protobuf_archive/src/google/protobuf/generated_message_reflection.cc:
external/protobuf_archive/src/google/protobuf/generated_message_reflection.cc(2429): warning C4506: no definition for inline function 'google::protobuf::Message *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::NewFromPrototype(const GenericType *,google::protobuf::Arena *)'
        with
        [
            GenericType=google::protobuf::Message
        ]
external/protobuf_archive/src/google/protobuf/generated_message_reflection.cc(2429): warning C4506: no definition for inline function 'google::protobuf::Arena *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::GetArena(GenericType *)'
        with
        [
            GenericType=google::protobuf::Message
        ]
external/protobuf_archive/src/google/protobuf/generated_message_reflection.cc(2429): warning C4506: no definition for inline function 'void *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::GetMaybeArenaPointer(GenericType *)'
        with
        [
            GenericType=google::protobuf::Message
        ]
INFO: From Compiling external/protobuf_archive/src/google/protobuf/map_field.cc:
external/protobuf_archive/src/google/protobuf/map_field.cc(465): warning C4506: no definition for inline function 'google::protobuf::Message *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::NewFromPrototype(const GenericType *,google::protobuf::Arena *)'
        with
        [
            GenericType=google::protobuf::Message
        ]
external/protobuf_archive/src/google/protobuf/map_field.cc(465): warning C4506: no definition for inline function 'google::protobuf::Arena *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::GetArena(GenericType *)'
        with
        [
            GenericType=google::protobuf::Message
        ]
external/protobuf_archive/src/google/protobuf/map_field.cc(465): warning C4506: no definition for inline function 'void *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::GetMaybeArenaPointer(GenericType *)'
        with
        [
            GenericType=google::protobuf::Message
        ]
INFO: From Compiling external/flatbuffers/src/util.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/reflection.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/flatc.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/idl_parser.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/idl_gen_fbs.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/code_generators.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/grpc/src/compiler/go_generator.cc [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/idl_gen_python.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/idl_gen_php.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/idl_gen_js.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/idl_gen_cpp.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/grpc/src/compiler/cpp_generator.cc [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/idl_gen_go.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/idl_gen_json_schema.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/flatc_main.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/idl_gen_text.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/grpc/src/compiler/java_generator.cc [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
INFO: From Compiling external/flatbuffers/src/idl_gen_grpc.cpp [for host]:
cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
ERROR: C:/users/lenovo-pc/tensorflow/tensorflow/contrib/lite/profiling/BUILD:37:1: C++ compilation of rule '//tensorflow/contrib/lite/profiling:time' failed (Exit 2)
tensorflow/contrib/lite/profiling/time.cc(17): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
Target //tensorflow/contrib/lite/toco:toco failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 287.186s, Critical Path: 15.02s
INFO: 295 processes: 295 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Mobile device

**Comment by inakaaay** [comment]
thank you for reminding. it's been updated

**Comment by aselle** [comment]
Thanks for the issue. We are in the progress of fixing compilation on Windows. TensorFlow is now building  Bazel on Windows which is making this much easier. Please stay tuned.

**Comment by jdduke** [comment]
The toco conversion utility should now run on Windows. It hasn't been put through exhaustive testing, though, due to some limitations with our testing infrastructure, so feel free to file bugs for any issues you encounter.
