### ISSUE TITLE
How to recognize a jpg from sdcard

### ISSUE THREAD

**Issue by onexuan** [tensorflow/tensorflow#2108]
I try to use tensorflow to recognize a jpg from sdcard, Is it right?
Bitmap bitmap = BitmapFactory.decodeFile("/storage/8A38-1900/1/1.jpg");
		if (bitmap != null && !bitmap.isRecycled()) {
			List<Recognition> recogns = tensorflow.recognizeImage(bitmap);
			if(recogns!=null){
				for (Recognition recognition:recogns) {
					Log.e("recognition", "recognition="+recognition.toString());
				}
			}
		}

**Comment by mrry** [comment]
Assuming you are using the Android demo code [here](https://github.com/tensorflow/tensorflow/tree/e39d8feebb9666a331345cd8d960f5ade4652bba/tensorflow/examples/android/src/org/tensorflow/demo), yes, that looks approximately right.
