### ISSUE TITLE
libnccl-dev is not installed in Dockerfile.gpu

### ISSUE THREAD

**Issue by nbcsm** [tensorflow/tensorflow#21094]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master branch
- **Python version**: not related
- **Bazel version (if compiling from source)**: 0.14.1
- **GCC/Compiler version (if compiling from source)**: not related
- **CUDA/cuDNN version**: CUDA9, cuDNN7
- **GPU model and memory**: not related
- **Exact command to reproduce**:
tensorflow/tools/ci_build/ci_build.sh GPU bazel test //tensorflow/...

### Describe the problem
when build from source inside docker container, configure.py will fail with error message below due to nccl.h is missing.

```
Please specify the location where NCCL 2 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:

Invalid path to NCCL 2 toolkit, /usr/local/cuda-9.0/lib/libnccl.so.2 or /usr/local/cuda-9.0/include/nccl.h not found. Please use the O/S agnostic package of NCCL 2
Traceback (most recent call last):
  File "configure.py", line 1586, in <module>
    main()
  File "configure.py", line 1525, in main
    set_tf_nccl_install_path(environ_cp)
  File "configure.py", line 1156, in set_tf_nccl_install_path
    _DEFAULT_PROMPT_ASK_ATTEMPTS)
__main__.UserInputError: Invalid TF_NCCL setting was provided 10 times in a row. Assuming to be a scripting mistake.
```

### Source code / logs
https://github.com/tensorflow/tensorflow/blob/226831aab92a395a26824a08caa9d43f0c3d604e/tensorflow/tools/ci_build/Dockerfile.gpu#L18-L20
libnccl-dev is not installed, so nccl.h is missing.

**Comment by nbcsm** [comment]
it is strange that recent GPU related CI checks on master branch can still pass without libnccl-dev installed. 
e.g. https://source.cloud.google.com/results/invocations/ae1f1de9-f91b-4138-b89d-d56b3dfebb80

@gunan, does current CI check still use ci_build.sh to build inside a docker container?

**Comment by gunan** [comment]
No, current CI runs outside docker, because we still try to support ubuntu 14, and there is no nvidia docker containers for ubuntu 14.
We will also soon remove all docker containers under `tools/ci_build`
Could you try using the devel-gpu container here?
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker

**Comment by nbcsm** [comment]
@gunan, thanks for the response.
 
To confirm, `We will also soon remove all docker containers under tools/ci_build`, do you mean stop official support for build inside docker container? 
when will this happen?

I believe this is a useful feature to build inside docker. 
For example, our CI build machines are shared with other team, so we prefer to build inside docker for isolation. 
Maybe we should still keep it, and leave the maintenance work to the community?



`tools/docker` is not quite friendly for ci build and release scenario. 
Also, it lacks of support for multiple python versions, e.g. build whl for python 3.5, python 3.6.

**Comment by gunan** [comment]
Multiple python versions was something we have not considered, I will take that into account when moving forward. In our dockerfiles, we certainly want to default to latest python versions moving forward.
However, I think we can parameterize python versions on the dockerfiles so it is possible to run our CI in them.
Having the community maintain these dockerfiles is also another viable option.

**Comment by nbcsm** [comment]
Just submitted a PR https://github.com/tensorflow/tensorflow/pull/21127
@gunan could you or someone help to take a look please?
Thanks

**Comment by nbcsm** [comment]
I saw @tfboyd already submitted a fix https://github.com/tensorflow/tensorflow/commit/402bb7353289013520fa99a38559319bc7b3d845, so I closed my previous PR.

Then when I pull latest cuda image, I realized ci_build.sh needs an option to allow something like `docker build --pull`, so I opened another PR https://github.com/tensorflow/tensorflow/pull/21147
Thanks.
