### ISSUE TITLE
Add gpu support for LRN

### ISSUE THREAD

**Issue by alexatknit** [tensorflow/tensorflow#211]
When I launch a network that uses local response normalization, it works perfectly on a CPU, but it appears to not have a gpu implementation and results in the following error when I switch to a gpu device:

```tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'LRN': Could not satisfy explicit device specification '/gpu:0'
	 [[Node: LRN = LRN[alpha=0.0005, beta=0.75, bias=2, depth_radius=5, _device="/gpu:0"](conv1/conv1)]]```

I could probably explicitly deploy this operation on the cpu, but it since this is a sliding window algorithm I'm surprised it doesn't have a gpu implementation.

**Comment by mrry** [comment]
Thanks for this feature request! In the meantime, if you want to test your model without explicitly specifying the device for each op, you can do:

```python
sess = tf.Session(tf.ConfigProto(allow_soft_placement=True))
```

...when constructing your session. This allows you to request a GPU device for any of your ops, and it will fall back to running on a CPU if there is no GPU kernel available.

**Comment by alexatknit** [comment]
Just in case anyone is using this code, theres a typo. It should be:

```
sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))
```

**Comment by jtoy** [comment]
just ran into this, anyone working on it?

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/dnn.h#L822 does exist, if someone wants to plumb that call through, I think we'd have LRN support for GPU :)

**Comment by apkuhar** [comment]
Any updates on this? not having this on GPU really slows things down.

**Comment by rryan** [comment]
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/dnn.h#L822 does exist, if someone wants to plumb that call through, I think we'd have LRN support for GPU :)

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/cuda/cuda_dnn.cc#L1422 

;)

**Comment by vrv** [comment]
Right, cudnn has an LRN implementation, so the point is to have it use that one.

**Comment by rryan** [comment]
FYI to anyone looking at contributing a fix for this -- there is some movement internally.

**Comment by vrv** [comment]
Thanks, removing the contributions welcome tag, since this is being worked on.

**Comment by girving** [comment]
@vrv: Does the person working on it have a Github username?

**Comment by vrv** [comment]
I don't know, @rryan do you know?

**Comment by rryan** [comment]
Once Stream Executor support is finished I was planning to work on it -- so you can assign me if you'd like :).

**Comment by girving** [comment]
@rryan: Assigned, thanks!

**Comment by alvisememo** [comment]
Is there any news on this bug? Should I better compute it with different operations?

**Comment by rryan** [comment]
Sorry for the delay, I carved out some time to work on it this weekend and will be sending it out for review as soon as the GPU tests pass.

**Comment by alvisememo** [comment]
Thanks @rryan , looking forward!

**Comment by rryan** [comment]
Added in 35df3ed43edabbc4ad1b2439bbc7de8917026d6e.

**Comment by vrv** [comment]
Yay!
