### ISSUE TITLE
Two versions of Grid LSTM cells

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#2111]
I noticed that there are two distinct versions of Grid RNN and LSTM cells in contrib:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/grid_rnn/python/ops/grid_rnn_cell.py
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/python/ops/rnn_cell.py

I realize that the RNN interface is still in flux, but I was wondering if these will be harmonized at some point?

**Comment by poxvoculi** [comment]
This might be a good issue to take up on the discussion board:

https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!forum/discuss
