### ISSUE TITLE
No contrib directory after installation via virtualenv

### ISSUE THREAD

**Issue by kate-kate** [tensorflow/tensorflow#21128]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra 10.13.4
- **TensorFlow installed from (source or binary)**: https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.9.0-py3-none-any.whl
- **TensorFlow version (use command below)**: 1.9.0 (v1.9.0-0-g25c197e023)
- **Python version**: 3.6.4
- **CUDA/cuDNN version**: -
- **GPU model and memory**: Intel Iris Graphics 6100 / 1536 MB
- **Exact command to reproduce**: bazel build tensorflow/contrib/lite/toco:toco

### Describe the problem
Hi, I've successfully installed the latest version of tensorflow with virtualenv and even created the frozen graph of my model with help of it, but then I needed the .tflite file and I found that ```bazel run -c opt tensorflow/contrib/lite/toco:toco``` returns ```no such package 'tensorflow/contrib/lite/toco'``` error (at first run there was ```The 'run' command is only supported from within a workspace.``` and I've created WORKSPACE file, because I saw some issue with such an advice, but problem was not in this file).
Then I've admitted that directory structure differs from one from the github. I had only include, bin and lib directories and pip-selfcheck.json
I've reinstalled tensorflow few times, I've deleted environment in Anaconda, when I had another build of tensorflow and reinstalled it again. Nothing changes. Also I haven't found any issues with this problem in github or stackoverflow. Maybe I've missed something (despite I followed the docs very precisely)? Any help would be very appreciated

### Source code / logs
I've installed When I'm trying to run 
```
bazel run -c opt tensorflow/contrib/lite/toco:toco -- \
--input_file=/Users/kate/python/codes2/tflite_res/tflite_graph.pb \
--output_file=/Users/kate/python/codes2/tflite_res/detect.tflite \
--input_shapes=1,300,300,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 \
--std_values=128 \
--change_concat_input_ranges=false \
--allow_custom_ops
```
I get 
```
ERROR: Skipping 'tensorflow/contrib/lite/toco:toco': no such package 'tensorflow/contrib/lite/toco': BUILD file not found on package path
WARNING: Target pattern parsing failed.
ERROR: no such package 'tensorflow/contrib/lite/toco': BUILD file not found on package path
INFO: Elapsed time: 0.370s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Bazel was installed with homebrew. Build command returns the same. 
Also here is the info I've collected with the help of your script
```
== cat /etc/issue ===============================================
Darwin MacBook-Pro-Ekaterina.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
Mac OS X 10.13.4

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

== uname -a =====================================================
Darwin MacBook-Pro-Ekaterina.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy                              1.15.0
numpydoc                           0.7.0
protobuf                           3.6.0
tensorflow                         1.9.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.9.0
tf.GIT_VERSION = v1.9.0-0-g25c197e023
tf.COMPILER_VERSION = v1.9.0-0-g25c197e023
Sanity check: array([1], dtype=int32)
/Users/kate/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/kate/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/Users/kate/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/kate/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
tf_env_collect.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================
```

There are some warnings about deprecation in python libs but them seem to be harmless. Also I don't understand why check for virtualenv is false (I've tried to run the command with both activated and deactivated tensorflow environment but it is always false).

Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Mobile device

**Comment by asimshankar** [comment]
@kate-kate - The `bazel` commands are intended to build TensorFlow binaries (like `toco`) from source. So I'm confused a bit by your setup since it seems you're installing TensorFlow from `pip` and not building from source.

Could you elaborate on your setup?

**Comment by kate-kate** [comment]
@asimshankar aah, so that's ok for install from ```pip```? 
You're right, I've installed from ```pip```, but I haven't found any info, that I can't use ```bazel``` or other ```contrib``` utils then. Even on ```contrib``` docs section. Thanks for claryfying, I'll try to make build from source

**Comment by asimshankar** [comment]
@kate-kate - It's okay to install from `pip` which will make all the Python `contrib` APIs (e.g., `tf.contrib.*` symbols in Python) available.

However, it seems you're trying to build the `toco` tool, which is built from source.

Is there some documentation that you're following that led to this confusion? If so, we'd be happy to update that to make it clearer. But yeah, to build the `toco` tool (and in general to use `bazel` which is a tool to build sources), you need the source code.

Hope that helps.

**Comment by kate-kate** [comment]
@asimshankar Thanks for help!
I think, first reason that led to this confusion is that neither in virtualenv installation guide nor in python API overview for ```contrib``` module  or even for ```toco``` (https://www.tensorflow.org/api_docs/python/tf/contrib/lite/TocoConverter) wasn't anynotr  that it should be installed from source and won't be available from ```pip``` build.
Actually there were some hint in ```toco``` [README](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/g3doc/python_api.md) "Additional instructions" section, that in order to get the latest version, you should build it from source. But I misunderstood, that it is necessary only for latest version.
