### ISSUE TITLE
Unexpected behavior of tf.hessians on graphs with tf.reduce_prod

### ISSUE THREAD

**Issue by lballes** [tensorflow/tensorflow#21130]
### System information

TensorFlow 1.9 CPU version installed via pip on Linux. Replicated the error on both Python 2.7.13 and 3.5.3 on Linux. Did not try with GPU version.

Details:
Have I written custom code: no
OS Platform and Distribution: Ubuntu 18.04
TensorFlow installed from: pip
TensorFlow version: 1.9 CPU version
Bazel version: n/a
CUDA/cuDNN version: n/a
GPU model and memory: n/a
Exact command to reproduce: see code below
Mobile device: no

### Describe the problem
``tf.hessians`` fails on a very simple function that uses ``tf.reduce_prod``. The error only occurs at the minimum of the function, where the Hessian is zero. Here's a minimal example:

    import numpy as np
    import tensorflow as tf
    
    x = tf.placeholder(tf.float32, shape=[3,])
    y = tf.reduce_prod(x**2)
    H = tf.hessians(y, x)[0]
    
    with tf.Session() as sess:
      print(sess.run(H, feed_dict={x: np.ones(3)}))
      print(sess.run(H, feed_dict={x: np.zeros(3)}))
      
    # Produces
    # [[2. 4. 4.]
    #  [4. 2. 4.]
    #  [4. 4. 2.]]
    # [[nan nan nan]
    #  [nan nan nan]
    #  [nan nan nan]]

The Hessian at ``x=[0, 0, 0]`` is well-defined and should evaluate to a zero-matrix. This behavior is unexpected. If ``tf.hessians`` can't handle ``tf.reduce_prod`` it should raise an exception.

### Source code / logs
See above for minimal example.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by lballes** [comment]
Updated issue with missing information.

**Comment by poxvoculi** [comment]
Looks like the last several changes to hessians have been from github.   Maybe this is community contributions welcome.  @drpngx: any opinion?

**Comment by drpngx** [comment]
Yes, that sounds like a really good idea.

**Comment by matthewfeickert** [comment]
Just pining this Issue to see if there has been any development on this, as it looks like this is [affecting our project as well](https://github.com/diana-hep/pyhf/issues/332).

**Comment by tilakrayal** [comment]
@lballes,
Is this still an issue?
Could you please update TensorFlow to the latest stable version v.2.10 and let us know if you are facing the same error. Thanks!
