### ISSUE TITLE
tf.Print() print wrong value

### ISSUE THREAD

**Issue by ztwe** [tensorflow/tensorflow#21154]
environment
ubuntu 16.04
tf-gpu 1.8

`tf_print = tf.Print(labels_0_new, [labels_0_new])`

The shape of labels_0_new is [16, 64]
But the output of tf_print is [[0 1 0]...]. The shape is [16?, 3]

What's the problem?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ppwwyyxx** [comment]
https://www.tensorflow.org/api_docs/python/tf/Print

> summarize: Only print this many entries of each tensor. If None, then a maximum of 3 elements are printed per input tensor.
