### ISSUE TITLE
Default floating point values in single_image_random_dot_stereograms_ops.cc cause syntax error

### ISSUE THREAD

**Issue by theHamsta** [tensorflow/tensorflow#21164]
Have I written custom code: yes
OS Platform and Distribution: Ubuntu 18.04
TensorFlow installed from: origin master
TensorFlow version: 1.9
Bazel version 0.15.2
CUDA/cuDNN version: 9.1/7.1
GPU model and memory:  NVIDIA-SMI 390.48
Exact command to reproduce: use code below in python3 script 
Mobile device: N/A
     
     import tensorflow as tf
      vol = tf.contrib.util.make_tensor_proto([256, 256])

Import of /localhome/local/projects/lme_custom_ops/tensorflow/contrib/image/__init__.py causes syntax error on my system (see issue https://github.com/tensorflow/serving/issues/421).

    Traceback (most recent call last):
    File "main.py", line 6, in <module>
        import geometry as geometry
    File "/localhome/local/projects/deep-iterative-reco/geometry.py", line 20, in <module>
        volume_origin = tf.contrib.util.make_tensor_proto([-((_volume_xy-1)/2 * _volume_spacing),-((_volume_xy-1)/2 * _volume_spacing)], tf.float32 )
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
        module = self._load()
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
        module = importlib.import_module(self.__name__)
    File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/__init__.py", line 48, in <module>
        from tensorflow.contrib import image
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/image/__init__.py", line 70, in <module>
        from tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms import single_image_random_dot_stereograms
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/image/python/ops/single_image_random_dot_stereograms.py", line 27, in <module>
        "_single_image_random_dot_stereograms.so"))
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
        ret = load_library.load_op_library(path)
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py", line 73, in load_op_library
        exec(wrappers, module.__dict__)
    File "<string>", line 28
        def single_image_random_dot_stereograms(depth_values, hidden_surface_removal=True, convergence_dots_size=8, dots_per_inch=72, eye_separation=3, mu=0,333299994, normalize=True, normalize_max=-100, normalize_min=100, border_level=0, number_colors=256, output_image_shape=[1024, 768, 1], output_data_window=[1022, 757], name=None):
                                                                                                                                                                    ^
    SyntaxError: invalid syntax

Works again if I change the default kwargs float arguments to integer values. Reason maybe localization option (I am from Germany which uses , to indicate decimal point. E.g. 1.2 == 1,2 in Germany). Though I think I am using the US standard.

Using this code in /tensorflow/contrib/image/ops/single_image_random_dot_stereograms_ops.cc solves the problem (not using floating values).

    REGISTER_OP( "SingleImageRandomDotStereograms" )
        .Attr( "T: {double,float,int64,int32}" )
        .Input( "depth_values: T" )
        .Output( "image: uint8" )
        .Attr( "hidden_surface_removal: bool = true" )
        .Attr( "convergence_dots_size: int = 8" )
        .Attr( "dots_per_inch: int = 72" )
        .Attr( "eye_separation: float = 3" )
        .Attr( "mu: float = 3333" )
        .Attr( "normalize: bool = true" )
        .Attr( "normalize_max: float = -100.0" )
        .Attr( "normalize_min: float = 100.0" )
        .Attr( "border_level: float = 0.0" )
        .Attr( "number_colors: int = 256" )

On python2 executing the following...  

      Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
      [GCC 7.3.0] on linux2
      Type "help", "copyright", "credits" or "license" for more information.
      >>> import locale
      >>> locale.setlocale(locale.LC_ALL, '')
            'LC_CTYPE=en_US.UTF-8;LC_NUMERIC=de_DE.UTF-8;LC_TIME=de_DE.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=de_DE.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=de_DE.UTF-8;LC_NAME=de_DE.UTF-8;LC_ADDRESS=de_DE.UTF-8;LC_TELEPHONE=de_DE.UTF-8;LC_MEASUREMENT=de_DE.UTF-8;LC_IDENTIFICATION=de_DE.UTF-8'

Though I compiled for python3:

    Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
    Type "copyright", "credits" or "license" for more information.

    IPython 5.5.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    In [1]: 
    ...: 
    ...: import locale

    In [2]: locale.localeconv()
    Out[2]: 
    {'currency_symbol': '',
    'decimal_point': '.',
    'frac_digits': 127,
    'grouping': [],
    'int_curr_symbol': '',
    'int_frac_digits': 127,
    'mon_decimal_point': '',
    'mon_grouping': [],
    'mon_thousands_sep': '',
    'n_cs_precedes': 127,
    'n_sep_by_space': 127,
    'n_sign_posn': 127,
    'negative_sign': '',
    'p_cs_precedes': 127,
    'p_sep_by_space': 127,
    'p_sign_posn': 127,
    'positive_sign': '',
    'thousands_sep': ''}

I am using tensorflow revision 6d71d3fc659b317a38586f71ae94410ad3261f55 on Ubuntu 18.08. cuDNN 7.1, CUDA 9.1

This seems to be related: https://github.com/tensorflow/tensorflow/issues/2974

**Comment by skye** [comment]
I'm gonna mark this as contributions welcome in case anyone wants to submit a PR addressing this.

@gunan do you know anything about localization or who would?

**Comment by gunan** [comment]
No idea, as we all use US settings, I think this is best handled by the community, who has a high chance of reproducing the problem.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by hofingermarkus** [comment]
Seems to be also related to #10370

Anyway, I only have this problem with tensorflow versions >= 1.9  (1.9, 1.10)
I never had troubles with tensorflow from v1.0 - v1.8
So the following code sinppet, that reproduces the error, works in my old tensorflow environments but fails in the new one.

``` python
import tensorflow as tf
import locale
locale.setlocale(locale.LC_ALL, locale="de_AT.UTF-8") 
dataset = tf.data.Dataset.from_tensor_slices([ ["a","b","c","e"]])
dataset = dataset.apply(tf.contrib.data.assert_element_shape( tf.TensorShape(4) ) )
```

It yields the same error as above (in tf >=1.9) when tf tries to import single_image_random_dot_stereograms and does so with the wrong floating point conversion style.

When I ran the debugger in tf 1.10 to the [load_library.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/load_library.py) file, it generates the wrong floating point style in [line 61](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/load_library.py#L61-L73) when it calls "wrappers = py_tf.GetPythonWrappers(op_list_str)" which calls this [C++ function.](https://github.com/tensorflow/tensorflow/blob/c4ccab7a95835ec12af16938ba0c17cc7c1f17e0/tensorflow/python/framework/python_op_gen.cc#L1029)
Setting the locale setting of LC_NUMERIC to US style before this function call and back to the original style fixes this error for me.
However, I don't have experience with i18n, so I don't know about side effects. (I guess US style needs to be intsalled?). But a warning/ exception would be nice if the code is called with the wrong locale setting.

``` python
  import locale
  bak = locale.getlocale(locale.LC_NUMERIC)
  locale.setlocale(locale.LC_NUMERIC,"en_US.UTF-8")
  wrappers = py_tf.GetPythonWrappers(op_list_str)
  locale.setlocale(locale.LC_NUMERIC,bak)
```

**Comment by yongtang** [comment]
Added a PR #22044 for the fix.

**Comment by grzegorz700** [comment]
After this solution, I have still the same issue in the last version of tensorflow (1.11). Why does that happen?

**Comment by yongtang** [comment]
@grzegorz700 the PR was only merged recently and may not be part of 1.11. Can you try with the nightly build if possible?

**Comment by DeepakVellampalli** [comment]
I'm using TensorFlow 1.12.0 and still facing the same error. Any suggestions please?


`File "/home/deepakvellampalli/carla_9_3_rllib/models.py", line 7, in <module>
    import tensorflow.contrib.slim as slim
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 57, in <module>
    from tensorflow.contrib import image
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/tensorflow/contrib/image/__init__.py", line 70, in <module>
    from tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms import single_image_random_dot_stereograms
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/tensorflow/contrib/image/python/ops/single_image_random_dot_stereograms.py", line 27, in <module>
    "_single_image_random_dot_stereograms.so"))
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/deepakvellampalli/.local/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 77, in load_op_library
    exec(wrappers, module.__dict__)
  File "<string>", line 28
    def single_image_random_dot_stereograms(depth_values, hidden_surface_removal=True, convergence_dots_size=8, dots_per_inch=72, eye_separation=, mu=, normalize=True, normalize_max=, normalize_min=, border_level=, number_colors=256, output_image_shape=[1024, 768, 1], output_data_window=[1022, 757], name=None):
                                                                                                                                                 ^
SyntaxError: invalid syntax
`


Thanks in advance!

**Comment by varunjammula** [comment]
Same here!

**Comment by medard0** [comment]
did someone solve this?

**Comment by varunjammula** [comment]
It happens when you also have an incompatible import statement.

**Comment by yongtang** [comment]
@varunjammula @medard0 the PR for the fix should have been in the latest version of TensorFlow. If the issue persist (or different but similar issue), can you open a new issue with the exact steps to reproduce?

**Comment by Ajk4** [comment]
> It happens when you also have an incompatible import statement.

Hi @varunjammula 

Could elaborate what do you mean by 'incompatible import statement' ? I have similar issue now and I would like to understand it more.

**Comment by sfikas** [comment]
What worked for me:

Instead of the call
```
import tensorflow.contrib.slim as slim
```
use
```
bak = locale.getlocale(locale.LC_NUMERIC)
locale.setlocale(locale.LC_NUMERIC,"en_US.UTF-8")
import tensorflow.contrib.slim as slim
locale.setlocale(locale.LC_NUMERIC,bak)
```
following the rationale set in comment https://github.com/tensorflow/tensorflow/issues/21164#issuecomment-417274023
