### ISSUE TITLE
request wrapper tutorial

### ISSUE THREAD

**Issue by andrebeu** [tensorflow/tensorflow#21172]
hi all,

it would be really great to have a tutorial on how to use the many awesome wrappers like dropoutwrapper, attentionwrapper, etc.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by MarkDaoust** [comment]
Yes. This is a good idea. 

The RNN tutorials need an update. We should make this a part of that update.

#18405 

I'm going to close this as duplicate and, make this part of that bug.
