### ISSUE TITLE
ValueError: No op named QuantizedAdd in defined operations.

### ISSUE THREAD

**Issue by kiritozzl** [tensorflow/tensorflow#21184]
python version:2.7.5 tensorflow version:1.2.0 bazel version:

i want to use tensorflow bazel to quantize my trained model,the quantize code is follow:

`bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
  --in_graph=/home/oup/zzl/zzl/AdversarialJPEG/JPEGFinalXu/Discriminative145000.pb \
  --out_graph=/home/oup/zzl/zzl/AdversarialJPEG/JPEGFinalXu/quantized8_Discriminative145000.pb \
  --outputs=Group_22/y_ \
   --transforms='
  strip_unused_nodes(type=float, shape="1,253,253,1")
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_nodes
  quantize_weights(minimum_size=0)'`

but when i try to get my trained model to test it accuracy, i get the error:

`tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:04:00.0)
2018-07-27 14:01:15.643854: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla P100-PCIE-16GB, pci bus id: 0000:05:00.0)
2018-07-27 14:01:15.643863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:2) -> (device: 2, name: Tesla P100-PCIE-16GB, pci bus id: 0000:8a:00.0)
Traceback (most recent call last):
  File "testpb2.py", line 82, in <module>
    _ = tf.import_graph_def(graph_def,name="")
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 283, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named QuantizedAdd in defined operations.`

and the code snippet to lead the error:

`with tf.Session(config=config) as sess:
    #load the quantity model
     with open(path+'quantized64_noDCT_retrained5000_Pruned_Discriminative145000.pb', 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        **_ = tf.import_graph_def(graph_def,name="")**
     y_ = sess.graph.get_tensor_by_name('Group_22/y_:0')
     correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
     accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

     init = tf.global_variables_initializer()
     sess.run(init)`

i don't konw why i delete the params 'quantize_nodes' in the quantize code it work normal,but add 'quantize_nodes' will raise the error above,is't my tensorflow version is too low lead this error?i have google that error but i can't found any solution,please give me some suggestion for that error,thank you very much!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by kiritozzl** [comment]
@tensorflowbutler thank you for your reply,but i know the reason is that my tensorflow version is too low,i use version 1.7,it's work.
