### ISSUE TITLE
TypeError: Cannot interpret feed_dict key as Tensor: Can not convert a NoneType into a Tensor.

### ISSUE THREAD

**Issue by ECE-Engineer** [tensorflow/tensorflow#21188]
Error:
/usr/lib64/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-07-27 08:35:51.967246: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: FMA
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1075, in _run
    subfeed, allow_tensor=True, allow_operation=False)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3590, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3679, in _as_graph_element_locked
    types_str))
TypeError: Can not convert a NoneType into a Tensor.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "--------------.py", line 397, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "---------------------.py", line 88, in main
    print(prediction(e))
  File "---------------------.py", line 361, in prediction
    model_prediction = sess.run(pred_label, feed_dict={x: subject_npy, y: y_const_npy, keep_prob: 1.0})
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1078, in _run
    'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Can not convert a NoneType into a Tensor.

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

I've tried what some stackoverflow posts recommended, e.g. keeping the feed_dict placeholder names as x and y, when either saving & restoring the graph or just making new placeholders.

My objective: I'm trying to restore and run an lstm.

My code:
"""setup for training-------(no issue with training)"""
  out_weights = tf.Variable(tf.random_normal([num_units,n_classes]), name = "out_weights")
  out_bias = tf.Variable(tf.random_normal([n_classes]), name = "out_bias")
  x = tf.placeholder("float",[None,time_steps,n_input])
  y = tf.placeholder("float",[None,n_classes])
  keep_prob = tf.placeholder("float", shape=())
input = tf.unstack(x ,time_steps,1, name = "inputs")
lstm_layer = rnn.BasicLSTMCell(num_units,forget_bias=1)
outputs, _ = rnn.static_rnn(lstm_layer,input,dtype="float32")
  loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=prediction,labels=y))
  tf.summary.scalar('cross_entrophy', loss)
  opt = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss)
  pred_label = tf.argmax(prediction,1)
  actual_label = tf.argmax(y,1)
  correct_prediction = tf.equal(pred_label, actual_label)
  accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver = tf.train.Saver()
    for i in range(N):
        sess.run(, feed_dict = {x: batch[0], y: batch[1], keep_prob: 0.5})
        if i%100==0:
                    saver.save(sess, "path/model.ckpt")
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
"""LOADING  lstm"""
  with tf.Session() as sess:
    from_saver = tf.train.import_meta_graph('path/model.ckpt.meta')
    from_saver.restore(sess, tf.train.latest_checkpoint('path_to_summaries_dir'))
   lstm_graph = tf.get_default_graph()
    out_weights = lstm_graph.get_tensor_by_name("out_weights:0")
    out_bias = lstm_graph.get_tensor_by_name("out_bias:0")
    x = tf.placeholder("float",[time_steps,n_input])
    y = tf.placeholder("float",[n_classes])
    keep_prob = keep_prob = tf.placeholder("float", shape=())
    inputs = lstm_graph.get_tensor_by_name("inputs:0")
    prediction = lstm_graph.get_tensor_by_name("prediction:0") + out_bias
    pred_label = tf.argmax(prediction,1)

"""RUNNING MODEL"""
  with tf.Session(graph=lstm_graph) as sess:
    sess.run(tf.global_variables_initializer())
    model_prediction = sess.run(pred_label, feed_dict={x: subject_npy, y: y_const_npy, keep_prob: 1.0})

------------------------

Have I written custom code:   yes
OS Platform and Distribution:    centos 6
TensorFlow installed from:    pip3
TensorFlow version:    v1.9
Bazel version:    N/A
CUDA/cuDNN version:    N/A
GPU model and memory:    N/A
Exact command to reproduce:    N/A
Mobile device:    N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device
