### ISSUE TITLE
Documentation issue 

### ISSUE THREAD

**Issue by abdurrehman1998** [tensorflow/tensorflow#21199]
![screenshot 25 _li](https://user-images.githubusercontent.com/25861787/43352882-816db4d2-9244-11e8-8f0a-3af1eef9b29f.jpg)
It's a Fashion MNIST dataset Tesorflow tutorial.What are digits doing here?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by drpngx** [comment]
I think we're talking about the classification of images of numeric arabic digits.

**Comment by MarkDaoust** [comment]
Hi @abdurrehman1998 

Yes, this tutorial is using fashion-mnist, this comment is left-over from an earlier version.

The source file for this tutorial is here: https://github.com/tensorflow/models/blob/master/samples/core/tutorials/keras/basic_classification.ipynb

Can you send me a PR with a fix?
The easiest way to do it is to edit in Colab and use the "save a copy to github" option. 

Thanks!

**Comment by HughKu** [comment]
Hey guys, I sent a PR to fix this [#5032](https://github.com/tensorflow/models/pull/5032).

**Comment by MarkDaoust** [comment]
Merged. Thanks!
