### ISSUE TITLE
toco convert quantized mobilenet_v1_ppn failed

### ISSUE THREAD

**Issue by MaeThird** [tensorflow/tensorflow#21221]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:Y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:None of them
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.9.0-rc2-623-geb04124bb7' 1.9.0-rc0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.15
- **GCC/Compiler version (if compiling from source)**: gcc-7.1
- **CUDA/cuDNN version**: cuda-9.2,cudnn-0.71
- **GPU model and memory**: 16G
- **Exact command to reproduce**:

I trained model by  `models/research/object_detection/model_main.py` with backbone `samples/configs/ssd_mobilenet_v1_ppn_shared_box_predictor_300x300_coco14_sync.config`.The difference from official is that I added quantization code in this config file like 
`
graph_rewriter {
  quantization {
    delay: 48000
    activation_bits: 8
    weight_bits: 8
  }
}
` 
**Everything works fine on PC(both train and eval)**  then I tried to export it to tf-lite.
1) `export_tflite_ssd_graph.py` seems ok for I **got tflite_graph.pb and tflite_graph.pbtxt**.
2) `bazel run -c opt tensorflow/contrib/lite/toco:toco -- \
--input_file=$OUTPUT_DIR/tflite_graph.pb \
--output_file=$OUTPUT_DIR/detect.tflite \
--input_shapes=1,300,300,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 \
--std_values=128 \
--change_concat_input_ranges=false \
--allow_custom_ops
`
**failed with "tensorflow/contrib/lite/toco/graph_transformations/propagate_fixed_sizes.cc:116] Check failed: dim_x == dim_y (512 vs. 24)Dimensions must match"**

Any idea?

**Comment by achowdhery** [comment]
@MaeThird  The PPN model is in float and not quantized.
You will need to follow the instructions here for conversion:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md

**Comment by MaeThird** [comment]
@achowdhery you mean it's not enough to add 
`graph_rewriter { quantization { delay: 48000 activation_bits: 8 weight_bits: 8 } }` in config file and retrain the  PPN model ?

**Comment by achowdhery** [comment]
@MaeThird Thanks. The quantized model config is correct. The transformation step in toco needs debugging. We will note this and address it based on our priorities. Is there a specific reason you need PPN over SSD? It has similar accuracy and higher latency in float version we released.

**Comment by MaeThird** [comment]
Hi,@achowdhery. I tried to use quantized PPN on SSD,because I want the running time is as short as possible on my low frequency embedded arm board. Anyway,waiting for your good news.

**Comment by achowdhery** [comment]
@MaeThird SSD with Mobilenet head is fastest in our benchmarks on Android phones.

**Comment by MaeThird** [comment]
@achowdhery  By printf the shape,I found some clues.
when import tensorflow model the **tensorflow::Status ConvertCOnvOperator** function will ReorderAxes from AxesOrder::**kHWIO** to AxesOrder::**kOHWI**. In my case :
`BoxPredictor/weights/read with shape: [ 1, 1, 512, 24 ] reorder to shape: [ 24, 1, 1, 512 ] `
At this moment `BoxPredictor/weights_quant/FakeQuantWithMinMaxVars ` **has no shape**
After some passes  the `BoxPredictor/weights_quant/FakeQuantWithMinMaxVars ` **has shape: [ 24, 1, 1, 512 ]** This shape is calculated correctly but **the appending reorder changed** it to [512,24,1,1].
**I mean the later-happened reorder ops  overrode  the previously calculated shape on** `BoxPredictor/weights_quant/FakeQuantWithMinMaxVars ` 
I skipped the reorder on `BoxPredictor/weights_quant/FakeQuantWithMinMaxVars ` and strode out.

**Comment by achowdhery** [comment]
@MaeThird Thanks. Is there a specific bug ? Can you attach the frozen graph in pbtxt format?

**Comment by MaeThird** [comment]
@achowdhery  
[tflite_pb.tar.gz](https://github.com/tensorflow/tensorflow/files/2264630/tflite_pb.tar.gz) Thanks.

**Comment by achowdhery** [comment]
@MaeThird : Thanks

**Comment by holyhao** [comment]
@achowdhery  Hi, I use mobilenetv1_ppn, the train and eval is right. I convert it to frozen_inference_graph.pb, it can work well on pc and the results are right. When i convert it to tflite_graph.pb, then convert it to detect.tflite. No warning and errors occur. But when it runs on the mobile, it shows totally wrong results. By the way, before this，I used mobilenetV2_ssd, all thing works fine. Could you please help me find it out?

**Comment by kchylee** [comment]
I encountered the same problem while trying to convert MobileNet PPN (quantize-aware training) from `.pb` to `.tflite`. @achowdhery is there an update on this issue? @MaeThird how did you skip the reorder?
