### ISSUE TITLE
Default model signatures of Estimator can not be used by TensorFlow Serving RESTful APIs

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#21234]
### System information

== cat /etc/issue ===============================================
Darwin mbp-2.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
Mac OS X 10.13.4

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== uname -a =====================================================
Darwin mbp-2.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy                              1.14.2
protobuf                           3.5.2.post1
tensorflow                         1.8.0
tensorflow-hub                     0.1.0
tensorflow-model-analysis          0.6.0
tensorflow-serving-api             1.8.0
tensorflow-tensorboard             1.5.0
tensorflow-transform               0.6.0
tensorflowjs                       0.1.0
tensorflowonspark                  1.0.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.8.0
tf.GIT_VERSION = v1.8.0-0-g93bc2e2072
tf.COMPILER_VERSION = v1.8.0-0-g93bc2e2072
Sanity check: array([1], dtype=int32)
/usr/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
tf_env_collect.sh: line 106: nvidia-smi: command not found

== cuda libs  ===================================================

== cat /etc/issue ===============================================
Darwin mbp-2.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
Mac OS X 10.13.4

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== uname -a =====================================================
Darwin mbp-2.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy                              1.14.2
protobuf                           3.5.2.post1
tensorflow                         1.8.0
tensorflow-hub                     0.1.0
tensorflow-model-analysis          0.6.0
tensorflow-serving-api             1.8.0
tensorflow-tensorboard             1.5.0
tensorflow-transform               0.6.0
tensorflowjs                       0.1.0
tensorflowonspark                  1.0.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.8.0
tf.GIT_VERSION = v1.8.0-0-g93bc2e2072
tf.COMPILER_VERSION = v1.8.0-0-g93bc2e2072
Sanity check: array([1], dtype=int32)
/usr/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 106: nvidia-smi: command not found

== cuda libs  ===================================================

### Describe the problem

Now we can use `TensorFlow Estimator` to train and export the `SavedModel` which can be loaded by `TensorFlow Serving`. However, the default model signature of Estimators only accept an byte array of input Tensor. These byte arrays can be encoded in `UTF-8` or other formats.

Therefore, if we use `TensorFlow Serving` to serve Estimator models, the gRPC APIs works but the RESTful APIs doesn't. We have fixed that by modifying the model signature of the graph to accept base64 string which can be encoded in `UTF-8` and send to the RESTful servers.

### Source code / logs

It is easy to re-produce the issue. We can export the SavedModel by this [estimator example](https://github.com/tobegit3hub/tensorflow_examples/blob/master/estimator_example/export_estimator_savedmodel.py). Then start the TensorFlow Serving and try to send the RESTful requests.

We have this [script](https://github.com/tobegit3hub/simple_tensorflow_serving/blob/master/tools/tensorflow_estimator_tool/generate_estimator_string.py) to generated the byte array of requested Tensor.

**Comment by tobegit3hub** [comment]
Is it possible to add another helper function just like `build_parsing_serving_input_fn` but requires base64 string as input?

If so, we could send the pull-request so that everyone can use it.

```
def input_fn():
    """An input_fn that expects a serialized tf.Example."""
    serialized_tf_example = array_ops.placeholder(dtype=dtypes.string,
                                                  shape=[default_batch_size],
                                                  name='input_example_tensor')

    # Add base64 decoding here

    inputs = {'examples': serialized_tf_example}
    features = parsing_ops.parse_example(serialized_tf_example, feature_spec)
    labels = None  # these are not known in serving!
    return InputFnOps(features, labels, inputs)
```

**Comment by karmel** [comment]
Please do send a PR with a helper function, and I can take a look. Thanks!

**Comment by netfs** [comment]
if your input a n-dimensional tensor of some numeric type (say DT_UINT8 for byte values), you can represent them as JSON arrays. see the examples here:

https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/api_rest.md#request-format-1

if your input is a serialized byte stream/blob, you need to encode it in base64. see:

https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/api_rest.md#encoding-binary-values

**Comment by karmel** [comment]
From a discussion with @netfs -- the REST processing logic will convert base64 -> string bytes. 
so if the input is "string" (to represent serialized blob), all you need to do is encode that blob as base64 in the REST request, and the REST api processor will decode that and feed a "string" during inferencing. So, the model graph itself, and hence the serving input receiver, should only ever see a string. Is that not what you are experiencing, @tobegit3hub ?

**Comment by tobegit3hub** [comment]
Thanks @netfs and @karmel . It seems that it works if TensorFlow Serving will convert the base64 string to byte array if it meets the special key "b64". But the logic is not part of TensorFlow Graph and since we have another RESTful service like TensorFlow Serving, we need to make the convention like this.
I can close the issue and pull-request if we don't make it in TensorFlow Graph. Still not sure if it is an good idea.

**Comment by karmel** [comment]
Since having a separate restful service will not be a requirement for most users, I would say, let's close the issue and PR for now. If you want to deserialize the base64 string in the graph, you can still write a custom serving_input_receiver_fn that does just that, but we will hold off on making it a general utility given that this is a specialized need.

Thanks, @tobegit3hub !

**Comment by tobegit3hub** [comment]
Okay, thanks @karmel and @netfs 😃
