### ISSUE TITLE
DecodeBase64 is not supported for Android TensorFlowInferenceInterface

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#21238]
### System information

== cat /etc/issue ===============================================
Darwin mbp-2.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
Mac OS X 10.13.4

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== uname -a =====================================================
Darwin mbp-2.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy                              1.14.2
protobuf                           3.5.2.post1
tensorflow                         1.8.0
tensorflow-hub                     0.1.0
tensorflow-model-analysis          0.6.0
tensorflow-serving-api             1.8.0
tensorflow-tensorboard             1.5.0
tensorflow-transform               0.6.0
tensorflowjs                       0.1.0
tensorflowonspark                  1.0.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.8.0
tf.GIT_VERSION = v1.8.0-0-g93bc2e2072
tf.COMPILER_VERSION = v1.8.0-0-g93bc2e2072
Sanity check: array([1], dtype=int32)
/usr/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
tf_env_collect.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

Have I written custom code:
No

OS Platform and Distribution:
MacOS

TensorFlow installed from:
`pip install tensorflow`

TensorFlow version:
1.8.0

Bazel version:
0.5.4

CUDA/cuDNN version
N/A

GPU model and memory:
N/A

Exact command to reproduce:
Follow the official and deploy the model with DecodeBase64 operator.

Mobile device:
Xiaomi MIX 2

### Describe the problem

We have the problem to deploy the image model to Android platform. It throws `No OpKernel was registered to support Op 'DecodeBase64' with these attrs`. And we have tried feeding string or byte array like these.

```
image_string = "foo"

byte[] image_bytes = image_string.getBytes();

String inputName = "model_input_b64_images";
 
inferenceInterface.feedString(inputName, image_bytes);

inferenceInterface.feed(inputName, image_bytes, 1, 4860);
```

Is it possible to implement and registry the kernel for `DecodeBase64` which is really important for image models? Or we have another way to feed the data for this Operator.

### Source code / logs

It is easy to re-produce the issue. Try exporting the model which has the `DecodeBase64` operator and use the `freeze_graph.py` to generated the Android model file.

Here is the complete log when trying to run the inference in Android.

```

07-30 16:58:35.943 14616-14616/com.tobe.androidclient E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.tobe.androidclient, PID: 14616
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tobe.androidclient/com.tobe.androidclient.MainActivity}: java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'DecodeBase64' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: DecodeBase64 = DecodeBase64[](model_input_b64_images)]]
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2855)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2930)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1619)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:171)
    at android.app.ActivityThread.main(ActivityThread.java:6684)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
 Caused by: java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'DecodeBase64' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: DecodeBase64 = DecodeBase64[](model_input_b64_images)]]
    at org.tensorflow.Session.run(Native Method)
    at org.tensorflow.Session.access$100(Session.java:48)
    at org.tensorflow.Session$Runner.runHelper(Session.java:298)
    at org.tensorflow.Session$Runner.runAndFetchMetadata(Session.java:260)
    at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:220)
    at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:197)
    at com.tobe.androidclient.MainActivity.onCreate(MainActivity.java:98)
    at android.app.Activity.performCreate(Activity.java:7057)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
    at android.app.ActivityThread.performLaun
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tobegit3hub** [comment]
Thanks for your reply. I have updated the basic information of this issue.

**Comment by angersson** [comment]
@aselle Can you have a look at this?

**Comment by tobegit3hub** [comment]
Thanks @aselle . It is reasonable and we can the base64 op from exported model.

But we want to train the model once and deploy to Serving/Android/iOS. It would be great if all the running devices can load the same model signature without any modification.
