### ISSUE TITLE
InvalidArgumentError: assertion failed: [predictions must be in [0, 1]] [Condition x >= y did not hold element-wise:x (linear/head/predictions/logistic:0) = ]

### ISSUE THREAD

**Issue by opokualbert** [tensorflow/tensorflow#21254]
### Describe the problem
I am using TF 1.9. My model trains successfully but when I try to evaluate I get the error below. I was even thinking my create_test_input_fn() could be the problem so I tried to evaluate on the training data set but I got the same error.

### Source code / logs

def create_train_input_fn(): 
    return tf.estimator.inputs.pandas_input_fn(
        x=X_train.drop('indiv_key',axis=1),
        y=y_train, 
        batch_size=32,
        num_epochs=None, # Repeat forever
        shuffle=True)

def create_test_input_fn():
    return tf.estimator.inputs.pandas_input_fn(
        x=X_test.drop('indiv_key',axis=1),
        y=y_test, 
        num_epochs=1, # Just one epoch
        shuffle=False) # Don't shuffle so we can compare to census_test_labels later

outdir = 'graphs/linear'
shutil.rmtree(outdir, ignore_errors = True) # start fresh each time
myopt = tf.train.AdamOptimizer(1e-4)

train_input_fn = create_train_input_fn()
estimator = tf.estimator.LinearClassifier(feature_columns ,
            optimizer=myopt, 
            model_dir=outdir, 
            n_classes=2)
estimator.train(train_input_fn, steps=5000)

test_input_fn = create_test_input_fn()
estimator.evaluate(test_input_fn)

=============
ERROR
=============
InvalidArgumentError: assertion failed: [predictions must be in [0, 1]] [Condition x >= y did not hold element-wise:x (linear/head/predictions/logistic:0) = ] [[0.0246640872][0.0240472779][0.0353220813]...] [y (linear/metrics/auc_precision_recall/Cast/x:0) = ] [0]
	 [[Node: linear/metrics/auc_precision_recall/assert_greater_equal/Assert/AssertGuard/Assert = Assert[T=[DT_STRING, DT_STRING, DT_FLOAT, DT_STRING, DT_FLOAT], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](linear/metrics/auc_precision_recall/assert_greater_equal/Assert/AssertGuard/Assert/Switch, linear/metrics/auc/assert_greater_equal/Assert/AssertGuard/Assert/data_0, linear/metrics/auc/assert_greater_equal/Assert/AssertGuard/Assert/data_1, linear/metrics/auc/assert_greater_equal/Assert/AssertGuard/Assert/Switch_1, linear/metrics/auc_precision_recall/assert_greater_equal/Assert/AssertGuard/Assert/data_3, linear/metrics/auc_precision_recall/assert_greater_equal/Assert/AssertGuard/Assert/Switch_2)]]

During handling of the above exception, another exception occurred:

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by michaelisard** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
