### ISSUE TITLE
tf.constant should support dynamic shape

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#21267]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOSX 10.13.5
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: pip binary
- **TensorFlow version (use command below)**: v1.9.0-0-g25c197e023 1.9.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: -
- **GCC/Compiler version (if compiling from source)**: -
- **CUDA/cuDNN version**: -
- **GPU model and memory**: -
- **Exact command to reproduce**: see below

### Source code / logs

Example code:

`tf.constant(3, shape=(3, 1, tf.constant(3) * 5))`

Will throw an error (very unrelated / confusing: `ValueError: setting an array element with a sequence.`).

Corresponding `tf.zeros` or `tf.ones` works, so it is a counter-intuitive that `tf.constant` does not.

(Workaround for me, but this seems a bit ugly: `tf.tile(tf.constant(value, shape=[1] * len(shape)), shape)`)

**Comment by yongtang** [comment]
Added a PR #21296 to support tensor type of shape (constant value only).

**Comment by albertz** [comment]
Ok, well, my example was maybe badly chosen. I explicitly need this for non-constant (dynamic) shapes. I edited the question description.

**Comment by asimshankar** [comment]
`tf.constant` is intended to produce values that are fully known at graph construction time. Perhaps I'm misunderstanding, but what does a "constant with dynamic shape" mean?

Perhaps what you're looking for is [`tf.fill`](https://www.tensorflow.org/api_docs/python/tf/fill)?

**Comment by albertz** [comment]
Thanks, `tf.fill` is actually what I wanted. But from the users perspective, why make this a difference? E.g. check inside `tf.constant` if the shape is constant, then make it a `Const`, otherwise use a `Fill`, i.e. basically merge `tf.constant` and `tf.fill`. I would have expected that `tf.constant` supports the same kind of shapes as `tf.zeros` or `tf.ones`. But maybe just because I did somehow miss `tf.fill`. If you don't like this suggestion, then maybe at least `tf.fill` should be mentioned in the documentation of `tf.constant`. Also, currently it is not totally clear to me from the documentation that `shape` must be constant.

**Comment by asimshankar** [comment]
I don't think we want to make `tf.constant` produce a tensor that isn't a constant (i.e., one whose value might be determined only at graph execution time).

However, updating the documentation for `tf.constant` to make it more understandable seems perfectly reasonable. I'd encourage you to create a pull request updateing https://github.com/tensorflow/tensorflow/blob/25c197e02393bd44f50079945409009dd4d434f8/tensorflow/python/framework/constant_op.py#L117

Thanks!
