### ISSUE TITLE
Using a tuple of Numpy arrays as validation_data fails when fitting a tf.keras model with a tf.data.Dataset

### ISSUE THREAD

**Issue by olix20** [tensorflow/tensorflow#21274]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.9.0
- **Python version**: 3.6.6
- **CUDA/cuDNN version**:9.2
- **GPU model and memory**: NA
- **Exact command to reproduce**:
```
model.fit(train_dataset,
          steps_per_epoch=100,
          validation_data=(val_samples, valid_targets),
          epochs=10)
```
### Describe the problem
Usecase: train a tf.keras.Model using the `fit` method. I for training data I have a `tf.data.Dataset` but for  `validation_data` I'd like to have a prefetched tuple `(x_val, y_val)` of Numpy arrays. At the end of the epoch it fails with the error `TypeError: float() argument must be a string or a number, not 'NoneType'. `

It seems it's trying to calculate `validation_steps` but it fails. Passing `validation_steps` will avoid the exception but it's unnecessary and i'm not sure what the `fit` model does with it.

### Source code / logs

```

#### train Dataset

with tf.device('/cpu:0'):
    dataset = tf.data.Dataset.from_tensor_slices(
    (train_df.file.values, train_targets))
    dataset = dataset.apply(
        tf.contrib.data.shuffle_and_repeat(len(train_df)))
    dataset = dataset.apply(tf.contrib.data.map_and_batch(
    map_func=proces_audio, batch_size=batch_size,
        num_parallel_calls=64))

#### model definition
x_logml = tf.keras.Input(shape=(timesteps,input_dim))
x = get_conv_layers(x_logml)  # returns a stack of conv/batch_norm/max_pool layers
x = tf.keras.layers.Dense(128, activation = 'relu')(x) 
x = tf.keras.layers.Dense(len(classes), activation = 'softmax')(x)
model = tf.keras.Model(inputs = x_logml, outputs = x)
model.compile(optimizer=tf.train.AdamOptimizer(learning_rate=0.001), 
              loss=['categorical_crossentropy'],
              metrics=['accuracy'])

model.fit(dataset,
          steps_per_epoch=100,
          validation_data=(val_samples,valid_targets),
#               validation_steps=10,  #including this line will avoid the exception, but not sure what's the point
         epochs=10)
```

as a smoke test, I used `val_samples` and `valid_targets` as training data (`x` and `y`) and it runs fine. So the problem seems to be when using a `tf.data.Dataset` and `(x_val, y_val)`. Using a `tf.data.Dataset` as `validation_data` (with `validation_steps`) also works fine.

error log at the end of epoch:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-b8d33816aaa6> in <module>()
      9               validation_data=(val_samples,valid_targets),#val_dataset,
     10 #               validation_steps=len(valid_df)//16,
---> 11              epochs=100)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1346           initial_epoch=initial_epoch,
   1347           steps_per_epoch=steps_per_epoch,
-> 1348           validation_steps=validation_steps)
   1349 
   1350   def evaluate(self,

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py in fit_loop(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
    218             batch_size=batch_size,
    219             steps=validation_steps,
--> 220             verbose=0)
    221         if not isinstance(val_outs, list):
    222           val_outs = [val_outs]

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py in test_loop(model, inputs, targets, sample_weights, batch_size, verbose, steps)
    459         outs[i] /= steps
    460   else:
--> 461     batches = make_batches(num_samples, batch_size)
    462     index_array = np.arange(num_samples)
    463     for batch_index, (batch_start, batch_end) in enumerate(batches):

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py in make_batches(size, batch_size)
    465       A list of tuples of array indices.
    466   """
--> 467   num_batches = int(np.ceil(size / float(batch_size)))
    468   return [(i * batch_size, min(size, (i + 1) * batch_size))
    469           for i in range(0, num_batches)]

TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by yashk2810** [comment]
You are getting this error because the batch_size of validation_data is None. Since you are passing a dataset for training you don't need to specify a batch_size for that. As you don't specify the batch_size and pass arrays as input for validation data, it fails. 

I would suggest using tf.data.Dataset for both training and validation. I hope this will unblock you.

**Comment by bignamehyp** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by olix20** [comment]
@yashk2810 thanks, it feels like a broken experience though specially since the docstring for `fit` says:
```
            batch_size: Integer or `None`.
                Number of samples per gradient update.
                If unspecified, `batch_size` will default to 32.
```
following your suggestion, is there a right value to set for `validation_steps` or is everything worked out based on `steps = val_set_size / batch_size` relationship?

**Comment by yashk2810** [comment]
@olix20  The docsting also specifies that if you use tf.data dataset, then the batch_size parameter won't be taken into consideration. 

`batch_size: Integer or `None`.
            Number of samples per gradient update.
            If unspecified, `batch_size` will default to 32.
            Do not specify the `batch_size` if your data is in the
            form of symbolic tensors, datasets, or dataset iterators
            (since they generate batches).
`
If you are creating a tf.data dataset for training, a tf.data dataset for testing and validation makes the most sense(as it is only 1-2 lines of code), as everything is consistent and makes it easy to understand the flow. If you are using validation steps then it will be calculated according to the formula you mentioned above.
