### ISSUE TITLE
Time_Distributed Keras vs TF Keras 

### ISSUE THREAD

**Issue by lysecret2** [tensorflow/tensorflow#21304]
Hi, 
there is a Bug when using the Time_Distributed Layer from tf Keras:

```
from tensorflow.python.keras.layers import TimeDistributed,Input,Embedding,LSTM
inu=Input(shape=(None,None))
emb=Embedding(input_dim=100,output_dim=100)(inu)
rnn=TimeDistributed(LSTM(100))(emb)

```
you get the error: 

`as_list() is not defined on an unknown TensorShape.`
If I use the Time_Distributed from Keras directly like this, there is no error: 

```
from keras.layers import TimeDistributed,Input,Embedding,LSTM
inu=Input(shape=(None,None))
emb=Embedding(input_dim=100,output_dim=100)(inu)
rnn=TimeDistributed(LSTM(100))(emb)
```
We can see the difference in how the Time_Distributed gets its shape, which is defined in line 163 in the keras definition [Keras](https://github.com/keras-team/keras/blob/master/keras/layers/wrappers.py#L114) they define a "get_shape_tuple" function and use that to not have to call the "as_list" as in TF Keras in line 164 [TF Keras](https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/python/keras/layers/wrappers.py)

Have I written custom code NO
OS Platform and Distribution Ubuntu 
TensorFlow installed from Source
TensorFlow version 1.9 
Bazel version NA 
CUDA/cuDNN version 9, 7.1
GPU model and memory p100 
Exact command to reproduce See above
Mobile device NA

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by omalleyt12** [comment]
@lysecret2 could you try a newer version of TF? ```pip install tf-nightly```. I'm not getting an error when running:

```python
from tensorflow.keras.layers import TimeDistributed,Input,Embedding,LSTM
inu=Input(shape=(None,None))
emb=Embedding(input_dim=100,output_dim=100)(inu)
rnn=TimeDistributed(LSTM(100))(emb)
```

(Note Keras is now under `tensorflow.keras` rather than `tensorflow.python.keras`)

**Comment by lysecret2** [comment]
You are right. The problem does not exist using tf nightly. Thanks!
