### ISSUE TITLE
After TensorFlow 1.1.0, libtensorflow_inference.so error: undefined reference to 'TF_NewGraph'

### ISSUE THREAD

**Issue by kevinan1** [tensorflow/tensorflow#21301]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by drpngx** [comment]
Could you fill out the rest of the form? In particular I'm wonder how you obtained the so file, did you build it yourself and how, or did you get it from a release?
