### ISSUE TITLE
Cannot benchmark mobilenet_v2_1.0_224.tflite

### ISSUE THREAD

**Issue by sf-wind** [tensorflow/tensorflow#21327]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Mac high sierra
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
Galaxy S7, Huawei Mate 10 etc.
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
1dc4c5b6f5829c4b8ef7d67f41735e8a0ce9d59a
- **Python version**:
2.7.10
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:
```
bazel build -c opt \
  --config=android_arm \
  --cxxopt='--std=c++11' \
  tensorflow/contrib/lite/tools/benchmark:benchmark_model
<copy benchmark file and model to phone>
adb shell /data/local/tmp//tflite_benchmark --graph=/data/local/tmp///mobilenet_v2_1.0_224.tflite --warmup_runs=1 --num_runs=50 --input_layer=input --input_layer_shape=1,244,244,3 --num_threads=4
```

### Describe the problem
Cannot run benchmark on mobilenet_v2_1.0_224.tflite model. Other models seem to be fine. Tried 0.35_96 and 1.4_224. Both are fine.

### Source code / logs
```
Num runs: [50]
Inter-run delay (seconds): [-1]
Num threads: [4]
Benchmark name: []
Output prefix: []
Warmup runs: [1]
Graph: [/data/local/tmp///mobilenet_v2_1.0_224.tflite]
Input layers: [input]
Input shapes: [1,244,244,3]
Use nnapi : [0]
nnapi error: unable to open library libneuralnetworks.so
Loaded model /data/local/tmp///mobilenet_v2_1.0_224.tflite
resolved reporter
tensorflow/contrib/lite/kernels/reshape.cc:58 num_input_elements != num_output_elements (4004 != 1001)
Node number 64 (RESHAPE) failed to prepare.

Failed to allocate tensors!
Aborted
```

**Comment by freedomtan** [comment]
apparently, you have typos. Please use ` --input_layer_shape=1,224,224,3` instead of ` --input_layer_shape=1,244,244,3`

**Comment by andrehentz** [comment]
Thanks @freedomtan 

Just to be extra clear, the proper size is 224, not 244. And you can also run the benchmark tool without specifying those parameters:

```
$ bazel run //tensorflow/contrib/lite/tools/benchmark:benchmark_model -- \
    --graph=`realpath ~/Downloads/mobilenet_v2*.tflite`
...
Average inference timings in us: Warmup: 46891, Init: 5050, no stats: 33320.6
...
```
