### ISSUE TITLE
tf.fold{r,l} no longer works on sequence of tensors

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#21340]
### System information
- **Have I written custom code**: Yes
- **OS Platform and Distribution**: Ubuntu 16.04
- **Mobile device**: N/A
- **TensorFlow installed from**: binary
- **TensorFlow version (use command below)**: `v1.9.0-0-g25c197e023`
- **Python version**: 3.5.2
- **Bazel version**: N/A
- **GCC/Compiler version**: N/A
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: GTX 1060 (6GB)
- **Exact command to reproduce**: see below

### Describe the problem

Starting from TensorFlow 1.9, it appears that `tf.fold{r,l}` functions no longer work on a list of tensors. The code snippet provided below works fine in 1.8 but not in 1.9 or 1.10-rc1. Do you confirm the bug? Thanks. 

### Source code / logs

```python
import tensorflow as tf

a = tf.constant([1, 2])
b = tf.constant([3, 4])
c = tf.foldl(lambda a, x: a * x, [a, b])

with tf.Session() as sess:
    print(sess.run(c))
```

should print `[3, 8]` but fails with:

```text
Traceback (most recent call last):
  File "test/foldl.py", line 5, in <module>
    c = tf.foldl(lambda a, x: a * x, [a, b])
  File "<python>/envpy3/lib/python3.5/site-packages/tensorflow/python/ops/functional_ops.py", line 145, in foldl
    swap_memory=swap_memory)
  File "<python>/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3209, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "<python>/envpy3/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2941, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "<python>/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2878, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "<python>/lib/python3.5/site-packages/tensorflow/python/ops/functional_ops.py", line 138, in compute
    a = fn(a, elem_i)
  File "test/foldl.py", line 5, in <lambda>
    c = tf.foldl(lambda a, x: a * x, [a, b])
TypeError: can't multiply sequence by non-int of type 'list'
```

**Comment by karmel** [comment]
Thanks for the report @guillaumekln -- it doesn't appear that those particular functions have changed recently, at least not since ~April when support for nested structures was added, but it's easy to imagine that changes in while loops or similar had an unexpected effect. @guptapriya , could this be related to changes you made on 07/03 [here](https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/python/ops/control_flow_ops.py#L3209)?

**Comment by guptapriya** [comment]
Hey @karmel, you're referring to this change right: https://github.com/tensorflow/tensorflow/commit/bbde9a6c47fedc35a03c90b85b9f301d643f6680#diff-76ab9dafbe12c20ddc3769c6b108986c

This change doesn't exist in 1.9 from what I can tell (the file you linked to is the 1.9 version right?). It doesn't have the changes from that commit. Also, that change should actually have no effect unless the new `return_same_structure` argument was used. So even if this change were in 1.9, it shouldn't change existing behavior.

**Comment by karmel** [comment]
@ebrevdo , @lukaszkaiser -- looks like that was someone working with you on adding support for nested tensors? Do you have context here, or know who would?

**Comment by ebrevdo** [comment]
We found the associated internal change & author, will loop back.  Will see if this is a backwards breaking change.

**Comment by ebrevdo** [comment]
OK; this isn't quite a backwards breaking change because you're relying on tf auto-magic to perform a tf.stack() for you.

The [version 1.8 documentation](https://www.tensorflow.org/versions/r1.8/api_docs/python/tf/foldl) explicitly states that it expects a tensor or tensor-like object, and a list is not one of these.  A tensor or a numpy array is.  Now that we've added support for nested structures, `[a, b]` is treated as a list of 2 tensors; and the foldl body sees a list of 2 tensors at each iteration.

What you want to do is pass a single tensor:
```
c = tf.foldl(lambda a, x: a * x, tf.stack([a, b]))
```

**Comment by guillaumekln** [comment]
Thanks @ebrevdo. After re-reading the documentation, I can accept that my input was not covered by the API. However, the `fold{l,r}` examples from the documentation are no longer working on 1.9 because of this change:

```python
import tensorflow as tf

elems = [1, 2, 3, 4, 5, 6]
s = tf.foldl(lambda a, x: a + x, elems)

with tf.Session() as sess:
    print(sess.run(s))
```

prints `21` on 1.8 but fails on 1.9 with:

```text
Traceback (most recent call last):
  File "test/foldl.py", line 4, in <module>
    s = tf.foldl(lambda a, x: a + x, elems)
  File "<python>/lib/python3.5/site-packages/tensorflow/python/ops/functional_ops.py", line 125, in foldl
    n = elems_flat[0].shape[0].value or array_ops.shape(elems_flat[0])[0]
  File "<python>/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 615, in __getitem__
    return self._dims[key]
IndexError: list index out of range
```

They should either be updated or this change be considered as breaking.
