### ISSUE TITLE
Fail to print Global Step as specified in documentation

### ISSUE THREAD

**Issue by nschejtman** [tensorflow/tensorflow#21344]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra version 10.13.6
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: v1.8.0-0-g93bc2e2072 1.8.0
- **Python version**: 3.6.5
- **Bazel version**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Mobile device**: N/A
- **Exact command to reproduce**:

```
global_step_tensor = tf.Variable(10, trainable=False, name='global_step')
sess = tf.Session()
print('global_step: %s' % tf.train.global_step(sess, global_step_tensor))
```

As found in: [https://www.tensorflow.org/api_docs/python/tf/train/global_step](https://www.tensorflow.org/api_docs/python/tf/train/global_step)

### Describe the problem
I am testing the command to print the global_step and fails 

### Source code / logs

> 2018-08-02 13:14:17.524910: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> Traceback (most recent call last):
>   File "/*my project*/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
>     return fn(*args)
>   File "/*my project*/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "/*my project*/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value global_step
> 	 [[Node: _retval_global_step_0_0 = _Retval[T=DT_INT32, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](global_step)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/*my project*/", line *, in <module>
>     print('global_step: %s' % tf.train.global_step(sess, global_step_tensor))
>   File "/*my project*/venv/lib/python3.6/site-packages/tensorflow/python/training/training_util.py", line 67, in global_step
>     return int(sess.run(global_step_tensor))
>   File "/*my project*/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
>     run_metadata_ptr)
>   File "/*my project*/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/*my project*/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
>     run_metadata)
>   File "/*my project*/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value global_step
> 	 [[Node: _retval_global_step_0_0 = _Retval[T=DT_INT32, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](global_step)]]

**Comment by asimshankar** [comment]
Thanks for the notice, will update the docs. It should read something like:

```python
global_step_tensor = tf.Variable(10, trainable=False, name='global_step')
sess = tf.Session()
# Initialize the variable
sess.run(global_step_tensor.initializer)
print('global_step: %s' % tf.train.global_step(sess, global_step_tensor))
```
