### ISSUE TITLE
import_graph_def ERROR when NodeDef contains NameAttrList (func) message defined in attr_value.proto - makes the graph unusable / unloadable in TF 1.8 or 1.9 (works in 1.7). ValueError: NodeDef mentions attr '<my_attr>' not in Op<>

### ISSUE THREAD

**Issue by sjain-stanford** [tensorflow/tensorflow#21345]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: n/a
- **TensorFlow installed from (source or binary)**: binary 
- **TensorFlow version (use command below)**: v1.9.0-0-g25c197e023 1.9.0
- **Python version**: Python 3.5.2
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: See below.

### Describe the problem
Our simplified code `modify.py` below does the following: 

- Loads an existing TF graph from `graph1.pb` into `graph_def = tf.GraphDef()`
- To each node within the `graph_def`, adds user-defined attributes using `NameAttrList func` protobuf message in [attr_value.proto](https://github.com/tensorflow/tensorflow/blob/25c197e02393bd44f50079945409009dd4d434f8/tensorflow/core/framework/attr_value.proto#L40-L44).
- Saves out the modified `graph_def` to `graph2.pb`
- Loads this new `graph2.pb` and imports to default graph --> Works in TF 1.7, fails in TF 1.8/1.9

This flow works fine in TF 1.7. However due to an added constraint in TF 1.8 or 1.9, when importing a graph containing nodes with user-defined attributes, it fails as follows (full error log included below):
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'my_attr' not in Op<name=VariableV2; signature= -> ref:Ref(dtype); attr=shape:shape; attr=dtype:type; attr=container:string,default=""; attr=shared_name:string,default=""; is_stateful=true>; 
NodeDef: import/loss3_classifier/biases = VariableV2[_class=["loc:@import/loss3_classifier/biases"], _output_shapes=[[1000]], container="", dtype=DT_FLOAT, my_attr=attr_name[data1=8, data2=2], shape=[1000], shared_name=""](). 
(Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
```

This is not an issue with the GraphDef interpreting binary mismatching with GraphDef-generating binary, since the same binary is used to generate and interpret. I believe this is failing because the check to ensure all attrs within the NodeDef are valid doesn't account for user-defined attributes given using `NameAttrList func` message in [attr_value.proto](https://github.com/tensorflow/tensorflow/blob/25c197e02393bd44f50079945409009dd4d434f8/tensorflow/core/framework/attr_value.proto#L40-L44). 

This is breaking some of our production code written in TF1.7, when migrating to TF1.9, since the graph is no longer loadable.

### Attachments
[graphs_attachment.zip](https://github.com/tensorflow/tensorflow/files/2254600/graphs_attachment.zip)
Contains:
- graph1.pb
- graph2.pb
- tensorboard events file for graph1.pb
- tensorboard events file for graph2.pb (can only generate using TF1.7, fails with TF1.8/1.9)
- modify.py script

#### modify.py
```python
import tensorflow as tf

def add_attr_to_tf_node(node, key, name, data):
  """ Add a dictionary 'data' to a TF graph node,
  with optional label 'name'. Key is 'key'.
  Each element of 'data' should be a tf.AttrValue() instance
  e.g.  a1 = tf.AttrValue(i=8)
        a2 = tf.AttrValue(i=2)
        attrs = {"data1": a1, "data2": a2}
  """
  if name is None:
    node.attr[key].CopyFrom(tf.AttrValue(func={"attr": data}))
  else:
    node.attr[key].CopyFrom(tf.AttrValue(func={"name": name, "attr": data}))

# Create empty graph_def
graph_def = tf.GraphDef()

# Parse/Load from graph1.pb
with tf.gfile.GFile('graph1.pb', 'rb') as f:
  graph_def.ParseFromString(f.read())

# Add user attributes to each node in graph_def
for node in graph_def.node:
  a1 = tf.AttrValue(i=8)
  a2 = tf.AttrValue(i=2)
  attrs = {"data1": a1, "data2": a2}
  add_attr_to_tf_node(node, 'my_attr', 'attr_name', attrs)

# Serialize/Save modified graph_def to graph2.pb
with tf.gfile.GFile('graph2.pb', 'wb') as f:
  f.write(graph_def.SerializeToString())

# Parse/Load from graph2.pb
with tf.gfile.GFile('graph2.pb', 'rb') as f:
  graph_def.ParseFromString(f.read())

# Import graph_def to defalt graph --> WORKS IN TF-1.7, ERROR WITH TF-1.8/1.9
tf.import_graph_def(graph_def)
```
#### TensorFlow 1.7:
No issues. 

#### TensorFlow 1.8/1.9 (ERROR LOG):
```
Traceback (most recent call last):
  File "/scratch/tensorflow_1p8/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 489, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'my_attr' not in Op<name=VariableV2; signature= -> ref:Ref(dtype); attr=shape:shape; attr=dtype:type; attr=container:string,default=""; attr=shared_name:string,default=""; is_stateful=true>; NodeDef: import/loss3_classifier/biases = VariableV2[_class=["loc:@import/loss3_classifier/biases"], _output_shapes=[[1000]], container="", dtype=DT_FLOAT, my_attr=attr_name[data1=8, data2=2], shape=[1000], shared_name=""](). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "modify.py", line 37, in <module>
    tf.import_graph_def(graph_def)
  File "/scratch/tensorflow_1p8/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/scratch/tensorflow_1p8/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 493, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef mentions attr 'my_attr' not in Op<name=VariableV2; signature= -> ref:Ref(dtype); attr=shape:shape; attr=dtype:type; attr=container:string,default=""; attr=shared_name:string,default=""; is_stateful=true>; NodeDef: import/loss3_classifier/biases = VariableV2[_class=["loc:@import/loss3_classifier/biases"], _output_shapes=[[1000]], container="", dtype=DT_FLOAT, my_attr=attr_name[data1=8, data2=2], shape=[1000], shared_name=""](). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
```

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by sjain-stanford** [comment]
Thanks @angersson for checking on this. I think this can be classified as a bug, since it is breaking the code that is supposed to otherwise run, and does run normally on an earlier version (1.7). The details from the issue template are all populated. Please try to re-create it at your end to see how this actually affects the forward compatibility of the codebase written for 1.7. 

As long as the code in `modify.py` looks reasonable to do (allowed by TF design), the fact that it breaks importing the graph in TF1.9 and not in TF1.7 speaks to the nature of this issue.

The real issue is this: 
In earlier versions, importing a graph def had no checks for the node attributes and if they're valid. It was added in TF1.8 onwards, I believe to ensure no invalid attributes are present when importing the graph def. However it should indeed allow room for a user-attribute, which can be added through the `NameAttrList func` in the [attr_value.proto](https://github.com/tensorflow/tensorflow/blob/25c197e02393bd44f50079945409009dd4d434f8/tensorflow/core/framework/attr_value.proto#L40-L44), which is a valid TF definition for a node attribute. 

Please let me know if you need help re-creating the issue at your end.
