### ISSUE TITLE
tf.clip_by_global_norm() returns zero tensors if the norm is infinity

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#21363]
I think this should return NaN tensors instead of zero tensors to signal an error. Users expect `tf.clip_by_global_norm()` to return tensors unaltered or with global norm matching the threshold passed into the function. This invariant is violated by returning zero tensors.

This is caused by `1.0 / use_norm` which is zero for an infinite norm in [clip_ops.py](https://github.com/tensorflow/tensorflow/blob/25c197e02393bd44f50079945409009dd4d434f8/tensorflow/python/ops/clip_ops.py#L257):

```python
scale = clip_norm * math_ops.minimum(
        1.0 / use_norm,
        constant_op.constant(1.0, dtype=use_norm.dtype) / clip_norm)
```

Boilerplate:

- Have I written custom code: No
- OS Platform and Distribution: N/A
- TensorFlow installed from: N/A
- TensorFlow version: master
- Bazel version: N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A
- Exact command to reproduce: N/A
- Mobile device: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by danijar** [comment]
Done

**Comment by facaiy** [comment]
Hi, which norm do you mean the infinity is in, use_norm or clip_norm?

**Comment by danijar** [comment]
The infinity is in `use_norm`, which is computed internally if not provided by the user.

**Comment by facaiy** [comment]
Thanks. Sounds reasonable to me. I create the PR #21428 to fix it.

**Comment by angersson** [comment]
Thanks @facaiy! I'll mark you as the assignee while we wait for #21428 to go in.
