### ISSUE TITLE
[tf.keras] Fit Generator & TensorBoard Callback with Stateful Metrics

### ISSUE THREAD

**Issue by brge17** [tensorflow/tensorflow#21361]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04/OSX
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: n/a
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.9.0/1.10.0rc1
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: n/a

### Describe the problem
When using ``fit_generator`` with ``TensorBoard`` callback and a ``StatefulMetric`` inside ``tf.keras``:

```
  File "/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 841, in on_epoch_end
    summary_value.simple_value = value.item()
AttributeError: 'float' object has no attribute 'item'
```
**This issue was fixed in regular Keras** (https://github.com/keras-team/keras/pull/10673), but has not been reviewed (https://github.com/tensorflow/tensorflow/pull/21071) yet in TensorFlow

### Source code / logs

Heres a dummy example of fit_generator with a dummy stateful metric that demonstrates the error:

```python
import tensorflow as tf
from tensorflow.python.keras.layers import Input, Dense
from tensorflow.python.keras.models import Model
from tensorflow.python.ops import state_ops

import numpy as np

class BatchCounter(tf.keras.layers.Layer):

        def __init__(self, name="batch_counter", **kwargs):
            super(BatchCounter, self).__init__(name=name, **kwargs)
            self.stateful = True
            self.batches = tf.keras.backend.variable(value=0, dtype="int32")

        def reset_states(self):
            tf.keras.backend.set_value(self.batches, 0)

        def __call__(self, y_true, y_pred):
            current_batches = self.batches * 1
            self.add_update(
              state_ops.assign_add(self.batches,
                                   tf.keras.backend.variable(value=1, dtype="int32")))
            return current_batches + 1

class DummyGenerator(object):
    """ Dummy data generator. """

    def run(self):
        while True:
            yield np.ones((10, 1)), np.zeros((10, 1))

train_gen = DummyGenerator()
val_gen = DummyGenerator()

# Dummy model
inputs = Input(shape=(1,))
outputs = Dense(1)(inputs)
model = Model(inputs=inputs, outputs=outputs)
model.compile(loss="mse", optimizer="adam", metrics=[BatchCounter()])

model.fit_generator(
    train_gen.run(),
    steps_per_epoch=5,
    epochs=200,
    validation_data=val_gen.run(),
    validation_steps=5,
    callbacks=[tf.keras.callbacks.TensorBoard()])
```

**Comment by brge17** [comment]
@fchollet

**Comment by brge17** [comment]
Looks like this was fixed in this commit:
https://github.com/tensorflow/tensorflow/commit/306dc604991c7f5fa45622a8c8236f59039d2c6a

**Comment by Aparajit-Garg** [comment]
Hi,
I am trying the below command but it is giving the mentioned error. Please help me out.

Code : history = model.fit_generator(train_generator, steps_per_epoch = 8,
                             epochs = 15, verbose = 1, callback = [tensorboard])

Error: fit_generator() got an unexpected keyword argument 'callback'
