### ISSUE TITLE
@tf.custom_gradient fails in eager execution mode

### ISSUE THREAD

**Issue by RamNathaniel** [tensorflow/tensorflow#21364]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX High Sierra 10.13.2
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.9.0-0-g25c197e023 1.9.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: Running on CPU
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
@tf.custom_gradient does not work in eager execution mode although the documentation states it does.

### Source code / logs
Providing a minimal example to reproduce:
```python
import tensorflow as tf

tfe = tf.contrib.eager
tf.enable_eager_execution()

@tf.custom_gradient
def log1pexp(x):
    e = tf.exp(x)

    def grad(dy):
        return dy * (1 - 1 / (1 + e))
    return tf.log(1 + e), grad

with tf.GradientTape() as tape:
    x = tf.constant(100.)
    y = log1pexp(x)

print(tape.gradient(y, [x]))
# prints None as default derivative is undefined
# not working properly - it did not use the custom gradient func (and print 1.0)

# Graph mode is working OK!
# x = tf.constant(100.)
# y = log1pexp(x)
# dy = tf.gradients(y, x)
#
# with tf.Session() as sess:
#     print(sess.run(dy))
# # prints 1.0 - the custom derivative
```

**Comment by asimshankar** [comment]
Short answer: Adding a [`tape.watch(x)`](https://www.tensorflow.org/api_docs/python/tf/GradientTape#watch) will make this work, so:

```python
with tf.GradientTape() as tape:
    x = tf.constant(100.)
    tape.watch(x)
    y = log1pexp(x)

print(tape.gradient(y, [x]))
```

As per the [documentation for `GradientTape`](https://www.tensorflow.org/api_docs/python/tf/GradientTape), trainable `Variable` objects are watched automatically, but tensors aren't.

@RamNathaniel : While we figure out how to make it harder to trip over this quirk, I hope you can continue to make progress (and it's fine to call `tape.watch(x)` in graph as well, so the same code will work).

**Comment by RamNathaniel** [comment]
Thank you for the very quick response - much appreciated!

**Comment by malikaltakrori** [comment]
Ok, I'll get to my question directly: So, If I have a model with a gradient reversal layer, i.e. a custom layer with no trainable variables, that calculates tf.identity(x) in the forward pass, but should return tf.negative(grad) in the backward pass, what should I monitor in this case? the layer itself?
