### ISSUE TITLE
Tensorflow Lite Don't supoort squared_difference?

### ISSUE THREAD

**Issue by aifollower** [tensorflow/tensorflow#21376]
I have made a model trained using tensorflow. 
When I transfer it to tensorflow lite, it has not supported squared difference operation!
How can I solve this problem?
Thanks very much!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by aifollower** [comment]
When I convert Tensorflow object detection api model to tensroflow lite, I have get this problem.
I tensorflow/contrib/lite/toco/import_tensorflow.cc:1053] Converting unsupported operation: SquaredDifference

**Comment by suharshs** [comment]
What model are you trying to convert? Are you sure its an eval model? Often squared difference comes in the loss function of a training model and right now you should only be trying to convert a frozen eval graph. Or does your eval graph have a squared difference operation?

**Comment by suharshs** [comment]
Will track this in the above tracking issue, please feel free to add more info about what model you are trying convert and if the graph is training or eval, in this issue. Thanks!

**Comment by dlml** [comment]
I got a bug when using toco to transform model

ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node batch_normalization_55/cond/batchnorm/add/y}} = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [] values: 1.1e-05>](batch_normalization_55/cond/Switch)
