### ISSUE TITLE
Is it possible to pass a PyObject into tf.py_func?

### ISSUE THREAD

**Issue by draplater** [tensorflow/tensorflow#21381]
Some times we need to use some information inside tf.pyfunc, and its unnecessary to convert these information into basic types that can feed into tensorflow.

For example, I don't know how to pass a pyObject into  tf.py_func, so I must write like this:
```python
import pickle
from typing import List
import tensorflow as tf
import numpy as np

data: List[int] = [1, 2, 3]
extra_info: List[object] = [{1: "Some python object that cannot be easily converted into basic types"},
                            {2: "Some python object that cannot be easily converted into basic types"},
                            {3: "Some python object that cannot be easily converted into basic types"}
                            ]


def some_func(one_data: int, one_info_serialized: str):
    one_extra_info = pickle.loads(one_info_serialized)
    # just imagine I will use the object
    print(one_extra_info)
    return np.int32(0)


data_pl = tf.placeholder(dtype=tf.int32, shape=())
info_pl = tf.placeholder(dtype=tf.string)
op = tf.py_func(some_func, [data_pl, info_pl], tf.int32)
session = tf.Session()

for one_data, one_info in zip(data, extra_info):
    session.run(op, feed_dict={data_pl: one_data,
                               # How can I pass this PyObject directly?
                               info_pl: pickle.dumps(one_info)})
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by sabhiram** [comment]
@draplater If you want to pass non-tensor arguments to a `py_func` you can do so quite easily by wrapping your `py_func` definition in a wrapper where the desired variable is within scope.

For example something like this will work:

```
def mk_some_func(extra_info):
    def some_func(tensor0, tensor1, ...):
        # Use `extra_info` as a py object here
        return np.int32(0)
    return some_func
```

Then when you want to create your py_func:
```
op = tf.py_func(mk_some_func(extra_info), [data_pl, info_pl], tf.int32)
```

Remember that if `extra_info` is a graph-time tensor, this method will not work. Also if the info you wish to pass is redefined with each session, you will need to get cute with how you modify the `extra_info` dictionary (etc). However if the data will not change for the given session, the above method should work out.

**Comment by angersson** [comment]
@sabhiram Thanks for the help!

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there (and it also supports helpful members of the community a bit better than we can here).

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
