### ISSUE TITLE
import_meta_graph + load model, then fail to model_export with signature

### ISSUE THREAD

**Issue by baobao7766** [tensorflow/tensorflow#21395]
I was fail to export model for tf-serving, and this is my error message, but i hava no idea about it:
```
TypeError: Can't convert Operation 'in_table' to Tensor (target dtype=None, name=None, as_ref=True)
```
And those are part of my code:
```
        self.symbol2index = tf.contrib.lookup.MutableHashTable(
            key_dtype=tf.string,
            value_dtype=tf.int64,
            default_value=self.UNK_ID,
            shared_name="in_table_share",
            name="in_table",
            checkpoint=True)

        self.index2symbol = tf.contrib.lookup.MutableHashTable(
            key_dtype=tf.int64,
            value_dtype=tf.string,
            default_value=self.UNK,
            shared_name="out_table_share",
            name="out_table",
            checkpoint=True)
```
Save model with:
```
self.saver.save(sess, "%s/model.ckpt" % ckpt_dir, global_step=global_step)
```
Load with:
```
ckpt = tf.train.latest_checkpoint(checkpoint_dir=tfFLAGS.train_dir)
graph_from_meta=ckpt + ".meta"
self.saver = tf.train.import_meta_graph(graph_from_meta)
self.saver.restore(sess, tf.train.latest_checkpoint(ckpt_dir))
```
model export with:
```
        prediction_signature = tf.saved_model.signature_def_utils.build_signature_def(
            inputs={
                'question': question_placeholder,
                'answer': answer_placeholder,
                'question_len': qes_len_placeholder,
                'answer_len': ans_len_placeholder,
            },
            outputs={'output': out_infers},
            method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME)

        # legacy_init_op = tf.group(tf.tables_initializer(), name='legacy_init_op')
        builder.add_meta_graph_and_variables(
            sess,
            tags=[tf.saved_model.tag_constants.SERVING],
            signature_def_map={'prediction': prediction_signature},
        )
        builder.save()

```

I have try to rebuild graph with the same parameters instead load them with `import_meta_graph`, it works, but it not convenient. 

Hope anyone can help me, thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by baobao7766** [comment]
@tensorflowbutler Thanks for your reply, i have run the code on two environments: PC and Platform:
PC:
  Have I written custom code: No
  OS Platform: Mac OS 10.11.6, no distribution
  TensorFlow installed with conda4.5.4, version is 1.2.0, without Bazel

Platform:
  ubuntu16.04, cuda8, cudnn5,
  python2.7, tensorflow 1.2.1, Bazel 0.15.0
  tensorflow install by docker, 

That's all i know about environment. And both of them can not work. And i use the rebuild graph for now.

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
