### ISSUE TITLE
conditional rbm 

### ISSUE THREAD

**Issue by rpagliarix** [tensorflow/tensorflow#2139]
Will conditional rbm ever be available in tensor flow library?

[Here](http://www.machinelearning.org/proceedings/icml2007/papers/407.pdf) is the original paper

**Comment by poxvoculi** [comment]
This question is better asked in the discussion forum.   This context is for bug-like issues, thanks!


https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!forum/discuss
