### ISSUE TITLE
Error with tf 1.10.0rc1

### ISSUE THREAD

**Issue by anhnt1** [tensorflow/tensorflow#21406]
Hi,

After upgrading to 1.10.0rc1, I got an error: E tensorflow/core/common_runtime/gpu/gpu_device.cc:228] Illegal GPUOptions.experimental.num_dev_to_dev_copy_streams=0 set to 1 instead. However, the program is still running. Is it still ok with this error?

Thanks,
Tuan

**Comment by asimshankar** [comment]
Yes, that is a benign message that you can ignore.
We'll look into make that message less ominous! :)

**Comment by av8ramit** [comment]
Thanks @asimshankar .

**Comment by asimshankar** [comment]
(Actually, this was fixed in commit bb52a6663a0141de53ddaf844f6c7087c0ddf7f7, but that isn't included in 1.10 so there will be spurious messages in 1.10.

@av8ramit : Should we cherry pick that fix?)
