### ISSUE TITLE
Feature request: support symbolic links for tensorboard

### ISSUE THREAD

**Issue by Russell91** [tensorflow/tensorflow#2140]
It would be nice if one could use symbolic links to organize groups of training files. Tensorboard does not search over symbolic links for event files because the following line 178 of python/summary/event_multiplexer.py:

```python
subdirs = [
        subdir
        for (subdir, files) in io_wrapper.ListRecursively(path)
        if list(filter(event_accumulator.IsTensorFlowEventsFile, files))
]
```

does not walk across symbolic links. This would be easy to fix by adding a symlink option to ListRecursively().

Current difficulties: 
1) Over time, the number of distinct training runs in a directory can grow to over 10, at which point tensorboard becomes slow and too information rich. Reorganizing a subset with symbolic links would be quite nice.

2) Sometimes it would be nice to compare a small subset of training runs that exist in different directories. Copying these files with `cp -r` is quite slow.

**Comment by danmane** [comment]
Hi @Russell91. This request sounds quite reasonable to me. If you send in a pull request that enables this, I would happily accept it. I think the best thing to do would be to have gfile.Walk https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/default/_gfile.py#L400 follow symlinks by default (we can just pass follow_links=True to the os.walk call)
