### ISSUE TITLE
[Feature Request] Main improvements for the c++-API

### ISSUE THREAD

**Issue by PinkySan** [tensorflow/tensorflow#21409]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: a bit, but this is not the problem
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 64 Bit
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: every version
- **Python version**: no python bindings
- **Bazel version (if compiling from source)**: using cmake
- **GCC/Compiler version (if compiling from source)**: MSVC 1910
- **CUDA/cuDNN version**: no
- **GPU model and memory**: no
- **Exact command to reproduce**: not necessary

## Main improvements for the c++-API.
I am really having a lot of trouble using the tensorflow api with c++. Building from sources took some time, but i fixed it. At the moment i am able to train a basic model, but not really further. I would really appreciate, if you take a look at these points 

### Very Important
- Official support for c++
- Offer downloading the c++ built binaries for Windows and Linux, CPU and GPU, 64bit
- Way more examples for c++ (tried some [here](https://github.com/PinkySan/TensorflowHandlingTests))
- Exporting the models must be supported (e.g. simple Save) (tried it [here](https://github.com/PinkySan/TensorflowSimpleSaver))

### Important
- Focussing the error is out of heap space building-problem
- Building the static library without the shared library (both in the same cmake file)

### Nice to have
- Conanize the build (externals should be conan packages)
- Conanize tensorflow itself

If anyone else got other ideas or problems, feel free to add these

**Comment by s4mpl3d** [comment]
Sounds cool :+1:

**Comment by PinkySan** [comment]
spread the word!

**Comment by josh11b** [comment]
I don't know of anyone explicitly working on the C++ API at this time, so I'm going to mark this as "contributions welcome". I believe there are some issues with providing C++ libraries as binaries, though, because in general it is hard to make stable C++ ABI.

**Comment by PinkySan** [comment]
I totally understand that it is pretty hard to make a stable C++  ABI and API. 
What about clearly announcing, that the C++ binaries are not a stable C++ ABI. But at least providing the binaries would help.

Even after building a tensorflow application in C++ (which takes a lot of effort due to lack of c++ examples and tutorials), it is not possible to save the model and its variables into a SavedModel, which can be loaded and used within python. (I know WriteBinaryProto, WriteTextProto and the SaveV2-Ops). But the inner connection between variable-nodes and saved variables (by SaveV2) is missing.

**Comment by mietzen** [comment]
@PinkySan Sound like a good solution

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.
