### ISSUE TITLE
Request: Be able to tell if tensorflow is making use of tensor cores on V100

### ISSUE THREAD

**Issue by ChrisBellew** [tensorflow/tensorflow#21401]
It would be really great if you could tell if the model you were training was successfully making use of the tensor cores on the Nvidia Tesla V100.

This would help in deciding whether spending the extra money on the V100 would be worth it, which it would be if the model is making good use of the tensor cores.

I've tried to find the information using Nvidia's `nvidia-smi` tool, but it doesn't seem to how utilization by type of core.

Thanks
Chris

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by cy89** [comment]
@ChrisBellew my understanding of V100 architecture is that the TensorCores aren't separated out--they use the same registers and reuse the ALUs of the main SM. So it may not be meaningful to ask for the utilization of the TC versus the normal SIMD cores. 

I would think that what you actually want to know is the performance benefits from using the TensorCores. Is your problem that you don't have a V100 and want to know if your model is likely to benefit from running on it? If you have a V100 sample, can't you do end-to-end timing measurements on it versus the alternatives?

**Comment by ChrisBellew** [comment]
Thanks Cliff.

My situation is that I am using V100 GPUs on AWS using keras/tensorflow.
There are some rules that you must use to ensure the calculations are half
precision floating point such as:

* Setting float X to float 16
* Ensuring input arrays are float 16

If you don't abide by these, the GPU will just use the standard single
precision cores and you won't get the significant speed up. My problem is
that I don't know if I have successfully moved some calculations onto the
tensor cores or if I have made a mistake. I suppose I could ensure all my
types are float 32 and then compare to the float 16 times, and they should
be very different, but i wanted to know if there was a way tensorflow could
give me some feedback.

Thanks

**Comment by cy89** [comment]
@zheng-xq can you offer hints, please?

**Comment by reedwm** [comment]
Tensor cores are used on V100s for various ops, such as matrix multiplications and convolutions, if the op inputs are float16. So this question is equivalent to checking if float16 is used in the model.

As @cy89 mentioned, one way is to measure the performance. Another way is to check the graph in TensorBoard to see the dtype ops are done in. A third option is to print `layer.input` and `layer.output` for each layer to verify the inputs and outputs are float16.

A mixed precision API is being worked on, which when released, will make it easy to build a model in float16. Once released, it will be clear models that use the API will be done in float16, and therefore tensor cores are being used.
