### ISSUE TITLE
tensorflow-1.0.0rc0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by harshita-kaushal** [tensorflow/tensorflow#21413]
I've activated tensorflow in terminal, and I'm trying to set up tensorflow fold. When I try doing this, the above error pops up
`tensorflow-1.0.0rc0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.`

I searched other forums and tried to resolve the issue by trying the solutions suggested, but I wasn't able to solve the problem. 
Thanks!

**Comment by av8ramit** [comment]
Hi @harshita-kaushal can you please provide more information? What commands are you running? Are you running in a virtual environment? I'm guessing you're running python2. Are you directly installing a whl file or just running a pip install. If you provide more information I may be able to help.

**Comment by av8ramit** [comment]
You're getting a specific link which for whatever reason may not be compatible. Can you try this?

```sudo -H pip install ** proxy specific part to intel that i cannot provide** -U tensorflow==1.10.0rc0```

**Comment by harshita-kaushal** [comment]
```
(tensorflow) hkaushal-mac01:~ hkaushal$ python -c 'import tensorflow_fold'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow_fold
```
This is the error generated.

**Comment by av8ramit** [comment]
Now after tensorflow is installed try the install tensorflow_fold line again:

```
pip install https://storage.googleapis.com/tensorflow_fold/tensorflow_fold-0.0.1-cp27-none-linux_x86_64.whl
```

**Comment by harshita-kaushal** [comment]
The same error is generated when I run the install tensorflow_fold command:
`tensorflow_fold-0.0.1-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.`

**Comment by av8ramit** [comment]
So now the error is different. Earlier the error was "tensorflow-1.0.0rc0" is not a supported. Unfortunately I cannot help you with tensorflow_fold issues. I suggest you file the issue an issue [here](https://github.com/tensorflow/fold/issues). 

My unofficial advice would be to try this:
```
wget https://storage.googleapis.com/tensorflow_fold/tensorflow_fold-0.0.1-cp27-none-linux_x86_64.whl
mv tensorflow_fold-0.0.1-cp27-none-linux_x86_64.whl tensorflow_fold-0.0.1-cp27-cp27mu-manylinux1_x86_64.whl 
pip install tensorflow_fold-0.0.1-cp27-cp27mu-manylinux1_x86_64.whl 
``` 

My theory is that your virtualenv does not like the whl file extension.

**Comment by xurongqiang** [comment]
> I've activated tensorflow in terminal, and I'm trying to set up tensorflow fold. When I try doing this, the above error pops up `tensorflow-1.0.0rc0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.`
> 
> I searched other forums and tried to resolve the issue by trying the solutions suggested, but I wasn't able to solve the problem. Thanks!

you may use the error tensorflow package name, I got the same error and solved by use the correct install package name.
