### ISSUE TITLE
Resnet50.py apply pooling at last layer regardless pooling parameter.

### ISSUE THREAD

**Issue by weishi258** [tensorflow/tensorflow#21438]
### Describe the problem
Resnet50.py apply pooling at last layer regardless pooling parameter.
The issue has been fixed in keras 2.2.0
### Source code / logs
Current:
```python  
  x = AveragePooling2D((7, 7), name='avg_pool')(x)
  if include_top:
    x = Flatten()(x)
    x = Dense(classes, activation='softmax', name='fc1000')(x)
  else:
    if pooling == 'avg':
      x = GlobalAveragePooling2D()(x)
    elif pooling == 'max':
      x = GlobalMaxPooling2D()(x)
```
Fix:
```python
  if include_top:
    x = AveragePooling2D((7, 7), name='avg_pool')(x)
    x = Flatten()(x)
    x = Dense(classes, activation='softmax', name='fc1000')(x)
  else:
    if pooling == 'avg':
      x = GlobalAveragePooling2D()(x)
    elif pooling == 'max':
      x = GlobalMaxPooling2D()(x)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by omalleyt12** [comment]
@weishi258 thanks for the issue! `keras_applications` has now been separated into its own module that both external Keras and tf.keras import, so this issue should be fixed if you install the nightly version
