### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by pumpkinband** [tensorflow/tensorflow#21449]
While running this code on CYGWIN 

`$ python -m scripts.label_image \
>   --graph=tf_files/retrained_graph.pb  \
>   --image=tf_files/flower_photos/daisy/3475870145_685a19116d.jpg`

this error showed up

` Traceback (most recent call last):
 File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/Admin/tensorflow-for-poets-2/scripts/label_image.py", line 24, in <module>
    import numpy as np
ImportError: No module named numpy
`

**Comment by av8ramit** [comment]
@pumpkinband it looks like you have no installed numpy. Please run the following in your terminal.

```
pip install numpy==1.14.5
```

**Comment by pumpkinband** [comment]
@av8ramit  actually i tried but every time this error keeps going
`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-i                                                                                                                                  nstall-LkomBi/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f                                                                                                                                  .read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" i                                                                                                                                  nstall --record /tmp/pip-record-bAHGSs/install-record.txt --single-version-exter                                                                                                                                  nally-managed --compile" failed with error code 1 in /tmp/pip-install-LkomBi/num                                                                                                                                  py/
`

**Comment by av8ramit** [comment]
I'd recommend trying in a virtual environment with the latest corresponding python version. If that doesn't work maybe update your setuptools version as well.

```
pip install --upgrade setuptools==39.1.0
```

**Comment by pumpkinband** [comment]
Tried both the things but 'numpy' isn't installing.

**Comment by av8ramit** [comment]
I recommend filing this issue on the [numpy](https://github.com/numpy/numpy/issues) repository as they will have a better idea of how to help you. After you get that working please comment or open a new issue if there is any issue with the TensorFlow portion.

**Comment by pumpkinband** [comment]
Thanks a lot brother.
