### ISSUE TITLE
the error of freeze model

### ISSUE THREAD

**Issue by ztwe** [tensorflow/tensorflow#21446]
- OS Platform:  Ubuntu 16.04
- TensorFlow installed from:  anaconda
- TensorFlow version: GPU-1.8
- Python version: 3.6.6
- CUDA/cuDNN version: 9.0 / 7.1.2
- GPU model and memory:16G

The model is mobilenetV2 + LSTM + attention.
MobilenetV2 is restored from the model zoo in [https://github.com/tensorflow/models/tree/master/research/slim](https://github.com/tensorflow/models/tree/master/research/slim). It is not trained during the training of the whole model.
LSTM and attention is trained.

The code about model is shown as following.
```
    def mobilenet_v2_rnn_attention(self, X, num_classes, dropout_keep_prob=0.8, is_train=False):
        rnn_size = 4096
        num_layers = 8
        attention_size = 1024
        arg_scope = training_scope()
        with slim.arg_scope(arg_scope):
            net_vis, end_points = mobilenet_base(X, num_classes=num_classes)
        with slim.arg_scope([slim.conv2d, slim.max_pool2d, slim.avg_pool2d], stride=1, padding='SAME'):
            with tf.variable_scope('Logits_out'):
                orig_shape = net_vis.get_shape().as_list()
                net = tf.reshape(net_vis, [-1, orig_shape[1] * orig_shape[2], orig_shape[3]])

                def lstm_cell():
                    return tf.contrib.rnn.LSTMCell(rnn_size)

                stack = tf.contrib.rnn.MultiRNNCell([lstm_cell() for _ in range(0, num_layers)], state_is_tuple=True)
                net, _ = tf.nn.dynamic_rnn(stack, net, dtype=tf.float32)
                # (B, T, D) => (T, B, D)
                net = tf.transpose(net, (1, 0, 2))
                net = attention(net, attention_size, True)
                net = slim.fully_connected(net, num_classes, activation_fn=None, scope='Logits_out1')
        return net, net_vis
```

At the first, I export the graph as following.
```
    X = tf.placeholder(tf.float32, [None, height, width, 3], name="inputs_placeholder")
    net, net_vis = build_model(X, num_classes, 1.0, False, arch_model)
    net = tf.nn.sigmoid(net)
    predict = tf.reshape(net, [-1, num_classes], name='predictions')

    graph_def = graph.as_graph_def()

    with gfile.GFile(FLAGS.output_file, 'wb') as f:
      f.write(graph_def.SerializeToString())
```

Then, freeze the model using the api

```
python /root/anaconda3/pkgs/tensorflow-base-1.8.0-py36hc1a7637_0/lib/python3.6/site- 
    packages/tensorflow/python/tools/freeze_graph.py \
      --input_graph=${INFERENCE_GRAPH_PATH}/${TMP_GRAPH} \
      --input_checkpoint=${CHECKPOINT_PATH}/model.ckpt-3800 \
      --input_binary=true \
      --output_graph=${CHECKPOINT_PATH}/${EXPORT_INF_GRAPH} \
      --output_node_names=${OUTPUT_NODE_NAME}
```

The error is shown as following.

`[libprotobuf FATAL google/protobuf/wire_format.cc:830] CHECK failed: (output->ByteCount()) == (expected_endpoint): : Protocol message serialized to a size different from what was originally expected.  Perhaps it was modified by another thread during serialization?`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
Bazel version
Exact command to reproduce
Mobile device
