### ISSUE TITLE
RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7

### ISSUE THREAD

**Issue by suraneti** [tensorflow/tensorflow#21472]
**Environment:**
-  MacOS (High Sierra)
-  Python 3.7
-  Tensorflow 1.9.0

After I've imported tensorflow, I've got warning message link this
`RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7`

And I've tried to run demo.py from this repo https://github.com/mystic123/tensorflow-yolo-v3
still got error message
 `SystemError: <built-in function AppendFloat32ArrayToTensorProto> returned NULL without setting an error`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by suraneti** [comment]
**OS Platform**

- MacOS (High Sierra) Version 10.13.4

**TensorFlow installed from**

- this tensorflow build repo https://github.com/lakshayg/tensorflow-build via pip

> 1.8.0 | CPU | macOS High Sierra | clang-902.0.39.1 | 3.6.5 | SSE4.1, SSE4.2, AVX, AVX2, FMA

link : https://github.com/lakshayg/tensorflow-build/releases/download/v1.8.0-macos-py27-py36-avx-avx2-fma-sse41-sse42/tensorflow-1.8.0-cp36-cp36m-macosx_10_13_x86_64.whl

**TensorFlow version**

- 1.8.0

**Bazel version**

- N/A (I don't know how to check this).

**CUDA/cuDNN version**

- Not installed because I use CPU version

**GPU model and memory**

- GPU Intel Iris Plus Graphics 640 1536 MB
- Memory 8 GB 2133 MHz LPDDR3
- *Additional CPU 2.3 GHz Intel Core i5

**Exact command to reproduce**

- I don't understand this question, but I just install via pip and run python script and fail
(following demo test in tensorflow website is fine).

**Mobile device**

- No

**Comment by skye** [comment]
Can you try installing a non-custom build of TF from our repo and see if you still get the problem? I suspect it's a problem in the build provided by https://github.com/lakshayg/tensorflow-build.

**Comment by suraneti** [comment]
Sorry for my mistake info, I've installed via pip.

**Comment by skye** [comment]
Can you try the latest release, 1.10?

**Comment by aminzabardast** [comment]
I have tried in 1.10 and yet I have this issue:
`RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7`

**Comment by skye** [comment]
@av8ramit this looks to be the same problem as #14182

**Comment by av8ramit** [comment]
We do not have a native binary for python3.7 yet. My recommendation until we have python3.7 support is that you [build from sources](https://www.tensorflow.org/install/install_sources) or use python3.5 or 3.6.
