### ISSUE TITLE
Question:  Example on how can TensorFlow be used for Text classification?

### ISSUE THREAD

**Issue by sumitchawla** [tensorflow/tensorflow#215]

**Comment by vrv** [comment]
Hi, this is probably a better question for either the discussion mailing list or StackOverflow -- can you please repost at one of those [venues](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/resources/index.md#community-)?

**Comment by sumitchawla** [comment]
Got a redirect back on that 
http://stackoverflow.com/questions/33705284/tensorflow-text-classification-using-neural-networks?noredirect=1#

I think it will be helpful to have a tutorial as community is just getting started on this.

**Comment by vrv** [comment]
(Discuss mailing list is probably the best for this)
