### ISSUE TITLE
tf.train.Saver() will save both the checkpoint and meta-graph

### ISSUE THREAD

**Issue by xu-song** [tensorflow/tensorflow#21502]
I found that, `tf.train.Saver()` will save both the `checkpoint` and `meta-graph`.
However in many tensorflow tutorial, it adopt the following usage:
```py
saver = tf.train.Saver()
saver.save(sess, 'my-save-dir/my-model-10000')    # will generate my-model-10000.meta
saver.export_meta_graph('my-save-dir/my-model-10000.meta')  # not need
```

# the following case

https://www.tensorflow.org/api_guides/python/meta_graph#Import_a_MetaGraph

```py
import tensorflow as tf
import math
# Creates an inference graph.
# Hidden 1
images = tf.constant(1.2, tf.float32, shape=[100, 28])
with tf.name_scope("hidden1"):
  weights = tf.Variable(
      tf.truncated_normal([28, 128],
                          stddev=1.0 / math.sqrt(float(28))),
      name="weights")
  biases = tf.Variable(tf.zeros([128]),
                       name="biases")
  hidden1 = tf.nn.relu(tf.matmul(images, weights) + biases)
# Hidden 2
with tf.name_scope("hidden2"):
  weights = tf.Variable(
      tf.truncated_normal([128, 32],
                          stddev=1.0 / math.sqrt(float(128))),
      name="weights")
  biases = tf.Variable(tf.zeros([32]),
                       name="biases")
  hidden2 = tf.nn.relu(tf.matmul(hidden1, weights) + biases)
# Linear
with tf.name_scope("softmax_linear"):
  weights = tf.Variable(
      tf.truncated_normal([32, 10],
                          stddev=1.0 / math.sqrt(float(32))),
      name="weights")
  biases = tf.Variable(tf.zeros([10]),
                       name="biases")
  logits = tf.matmul(hidden2, weights) + biases
  tf.add_to_collection("logits", logits)

init_all_op = tf.global_variables_initializer()

with tf.Session() as sess:
  # Initializes all the variables.
  sess.run(init_all_op)
  # Runs to logit.
  sess.run(logits)
  # Creates a saver.
  saver0 = tf.train.Saver()
  saver0.save(sess, 'my-save-dir/my-model-10000')            # it save both checkpoints and meta-graph
  # Generates MetaGraphDef.
  saver0.export_meta_graph('my-save-dir/my-model-10000.meta')  # you can comment this line
```

# env
```yml
tensorflow=1.8.0
```

# background

I read the tensorflow docs, and search in stackoverflow.
I just find similar question, but no proper answer, like this one

https://stackoverflow.com/questions/45208587/relationship-between-tensorflow-saver-exporter-and-

**Comment by facaiy** [comment]
You're right. For save method, its argument `write_meta_graph` is True by default, see API [ tf.train.Saver](https://www.tensorflow.org/api_docs/python/tf/train/Saver#save):

```python
save(
    sess,
    save_path,
    global_step=None,
    latest_filename=None,
    meta_graph_suffix='meta',
    write_meta_graph=True,
    write_state=True,
    strip_default_attrs=False
)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by xu-song** [comment]
what is the difference between `my-model-10000.meta` and `graph.pb`?
I export both `my-model-10000.meta` and `graph.pb` in txt format, I found they are similar.
Both contains `MetaInfoDef`、`GraphDef`、`SaverDef`、`CollectionDef`

**Comment by facaiy** [comment]
I think this question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow).

If I understand correctly, [GraphDef](https://github.com/tensorflow/tensorflow/blob/r1.10/tensorflow/core/framework/graph.proto) is a member of [MetaGraphDef](https://github.com/tensorflow/tensorflow/blob/r1.10/tensorflow/core/protobuf/meta_graph.proto).
