### ISSUE TITLE
How to encrypt the tflite file？

### ISSUE THREAD

**Issue by zchfaq** [tensorflow/tensorflow#21501]
Now  I have my own tflite file，and I am worried that others will copy my file. I want to encrypt my tflite file，so even if others have my file，they cannot use it. 
Is there a way to encrypt the file?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by cy89** [comment]
@aselle @andrehentz @petewarden this seems like a feature request, unless it's something that Lite already does, or it's something that's naturally handled elsewhere.

**Comment by aselle** [comment]
This is something that is available in most host operating systems. Look for AES encryption. Maybe https://stackoverflow.com/questions/6788018/android-encryption-decryption-with-aes
Of course encryption is not a panacea as you need to store your key somewhere. You might look at say https://developer.android.com/training/articles/security-key-attestation

**Comment by zchfaq** [comment]
@aselle  Thank you for the answer. I'll colse it

**Comment by mabdullahrafique** [comment]
But when I try to open the tflite model in bytes array the tflite interpreter can not read it.

**Comment by JeetSA** [comment]
@mabdullahrafique I am facing the same problem. Did you find any solution for the same? Please help me with that.

Thanks in advance.

**Comment by piyushag21** [comment]
The tflite file in the assets folder is visible to any third party and anybody can extract the proprietary tflite model, this creates a problem in creating a commercial application esp. when the option to host the model on a server is not available.
