### ISSUE TITLE
How to take weight from file checkpoint ckpt ?

### ISSUE THREAD

**Issue by ThorPham** [tensorflow/tensorflow#21532]
i want to take weight parameter from model object detection api ? how to do that ?

**Comment by allenlavoie** [comment]
[tf.train.load_variable](https://www.tensorflow.org/api_docs/python/tf/train/load_variable), and [tf.train.list_variables](https://www.tensorflow.org/api_docs/python/tf/train/list_variables) if you don't know the name. Probably a better question for StackOverflow.
