### ISSUE TITLE
Build from source with python3.7 failed(prototype changed)

### ISSUE THREAD

**Issue by MaeThird** [tensorflow/tensorflow#21531]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:N
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:arch
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:1.10.0
- **Python version**:python-3.7
- **Bazel version (if compiling from source)**: 0.15.2
- **GCC/Compiler version (if compiling from source)**: gcc-7
- **CUDA/cuDNN version**:cuda-9.2,cudnn-7.1
- **GPU model and memory**:24G
- **Exact command to reproduce**:

build from newest source with Python3.7 failed at 
`external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc:69:42: error: invalid conversion from 'const char*' to 'char*'`
As the https://docs.python.org/3.7/c-api/unicode.html#c.PyUnicode_AsUTF8AndSize said 
`Changed in version 3.7: The return type is now const char * rather of char *` for `PyUnicode_AsUTF8AndSize() prototype` 
Maybe you should update it accordingly.

**Comment by MaeThird** [comment]
https://github.com/tensorflow/tensorflow/issues/20690

**Comment by andrbmgi** [comment]
As this is the first hit on google, the solution is here: https://github.com/protocolbuffers/protobuf/pull/4862/files
