### ISSUE TITLE
Optimisations do not seem to be active during building

### ISSUE THREAD

**Issue by Dapid** [tensorflow/tensorflow#2153]
When building Tensorflow with Bazel master following the instructions in #2109 , I get many warnings like:

```
In file included from third_party/gpus/cuda/include/host_config.h:161:0,
                 from third_party/gpus/cuda/include/cuda_runtime.h:76,
                 from <command-line>:0:
/usr/include/features.h:328:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
```

In fact, running a simple network on TF built by me and linked against Cudnn 5  is10% slower than the wheel built by Google against the default Cudnn.

**Comment by vrv** [comment]
Did you build with -c opt ?

**Comment by Dapid** [comment]
Yes.

```
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

**Comment by vrv** [comment]
Hm, not entirely sure :(

1) Did you build the pip package additionally with  --copt=-mavx ?  I think our pip wheels do that.
2) Is there a previous commit where this didn't happen, or has this always been happening for you?

@damienmg for help

**Comment by Dapid** [comment]
1) No, but I am running out on the GPU, so AVX wouldn't affect it, right?
Anyway, the warning seems to indicate that the O2 flag is missing somewhere.

2) Today I managed to build TF for the first time, so I can't tell, but I
can try an earlier version. Any suggestions? (It is not completely trivial,
as I have to tweak with the include paths in the configuration).

**Comment by vrv** [comment]
AVX can still help since not all operations are on GPU, and some code can still be accelerated by avx.  Worth a shot anyway :)

I think if you have to tweak include paths and all of that jazz, something is really wrong -- most of our users don't have to do that.  Did the instructions to add --spawn-strategy and genrule-strategy=standalone not help?

**Comment by damienmg** [comment]
https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/CROSSTOOL#L225 according to the crosstool it should have -O2

What does the command line looks like with -s ?

**Comment by girving** [comment]
Closing for now due to lack of response to @damienmg's question.  @Dapid: Please comment if you have more information and I'm happy to reopen.

**Comment by vladfi1** [comment]
I too am getting these warnings.

**Comment by wichtounet** [comment]
Building the branch r1.0 from source gives me the same warning. I'm working on Gentoo with GCC 4.9.4. 

The command is: 

`$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package `

Thanks

**Comment by maomaocode** [comment]
I have the same issue
I am using CentOS 7, python3.5, TensorFlow 1.1.0-rc1

in the prompt of ./configure:

```
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3.5
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] Y
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
```
to compile I used:

`bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

I tried as early as tensorflow version 1.0.0 and I always get the "warning _FORTIFY_SOURCE requires compiling with optimization (-O)". Tensorflow version 0.12.1 doesn't seem to have this problem for me.

**Comment by reverendbedford** [comment]
I also have this issue on CentOS 7, python2.7.5, and TensorFlow r1.1.  If I run with -s I can see the compiler wrapper is getting passed -O2 -march=native, so maybe this is spurious?

**Comment by yaohuaxin** [comment]
The warning seems to come out when compile CUDA code. How to pass in NVCC flags?

**Comment by XapaJIaMnu** [comment]
Any updates on this?

**Comment by girving** [comment]
According to @reverendbedford TensorFlow is actually getting optimized, so it seems like a CentOS toolchain but that I don't think we have control over (and CentOS is not an officially supported TensorFlow platform).

**Comment by XapaJIaMnu** [comment]
@girving , I'm actually running Arch and I see the same problem, even when I build it myself.
Here's my build process:
```bash
  export PYTHON_BIN_PATH=/usr/bin/python
  export USE_DEFAULT_PYTHON_LIB_PATH=1
  export CC_OPT_FLAGS="-march=native -O3"
  export TF_NEED_JEMALLOC=1
  export TF_NEED_GCP=0
  export TF_NEED_HDFS=0
  export TF_ENABLE_XLA=1
  export TF_NEED_VERBS=0
  export TF_NEED_OPENCL=0
  export TF_NEED_CUDA=1
  export GCC_HOST_COMPILER_PATH=/usr/bin/gcc-5
  export CUDA_TOOLKIT_PATH=/opt/cuda
  export TF_CUDA_VERSION=$($CUDA_TOOLKIT_PATH/bin/nvcc --version | sed -n 's/^.*release \(.*\),.*/\1/p')
  export CUDNN_INSTALL_PATH=/opt/cuda
  export TF_CUDNN_VERSION=$(sed -n 's/^#define CUDNN_MAJOR\s*\(.*\).*/\1/p' $CUDNN_INSTALL_PATH/include/cudnn.h)
  export TF_CUDA_COMPUTE_CAPABILITIES=5.2
  
./configure
  bazel build --config=opt --config=cuda //tensorflow:libtensorflow.so //tensorflow/tools/pip_package:build_pip_package
  bazel-bin/tensorflow/tools/pip_package/build_pip_package ${srcdir}/tmp
```
Could you tell me what flag am I missing?
Cheers,

Nick

**Comment by girving** [comment]
@XapaJIaMnu Can you add `-s` and see if it actually is getting optimized?

**Comment by XapaJIaMnu** [comment]
@girving, nvm, my bad. I had wrongly installed the wrong packages. The warnings are gone if I use my locally compiled once with "-march=native -O3"

Thanks,

Nick
