### ISSUE TITLE
fatal: not a git repository: 'E:/tensorflow/tensorflow/contrib/cmake/build/nsync/src/nsync/.git'

### ISSUE THREAD

**Issue by cvJie** [tensorflow/tensorflow#21542]
i want to use cmake+VS2015+win10 to compile tensorflow-CPU,to get tensorflow.dll and tensorflow.lib，in total 6 errors , 
but always happen :
Creating directories for 'zlib'
  Building Custom Rule E:/tensorflow/tensorflow/contrib/cmake/CMakeLists.txt
  CMake does not need to re-run because E:/tensorflow/tensorflow/contrib/cmake/build/CMakeFiles/generate.stamp is up-to
  -date.
  Performing download step (git clone) for 'zlib'
  Cloning into 'zlib'...
  fatal: Out of memory, malloc failed (tried to allocate 947912704 bytes)
  Cloning into 'zlib'...
  fatal: Out of memory, malloc failed (tried to allocate 947912704 bytes)
  Cloning into 'zlib'...
  fatal: Out of memory, malloc failed (tried to allocate 947912704 bytes)
  -- Had to git clone more than once:
  CMake Error at E:/tensorflow/tensorflow/contrib/cmake/build/zlib/tmp/zlib-gitclone.cmake:66 (message):
    Failed to clone repository: 'https://github.com/madler/zlib'
 3 times.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”已退 出，
代码为 1。 [E:\tensorflow\tensorflow\contrib\cmake\build\zlib.vcxproj]

how to solve it??thanks,please

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by skye** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
