### ISSUE TITLE
tf.image.decode_image cannot decode b64-encoded string in Python3.6

### ISSUE THREAD

**Issue by FortiLeiZhang** [tensorflow/tensorflow#21547]
```python
import tensorflow as tf
import base64

with open('~/001.jpg', 'r') as img:
	encoded_string = base64.b64encode(img.read())
	image_tensor = tf.image.decode_image(encoded_string, channels=3)
	print(image_tensor)
```

When run above code with Python 2, it is ok, the result is:
Tensor("decode_image/cond_jpeg/Merge:0", dtype=uint8)

However, when run with Python 3, it shows:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by facaiy** [comment]
It seems that [API](https://www.tensorflow.org/api_docs/python/tf/image/decode_image) declare its contents must be byte string:

> contents: 0-D string. The encoded image bytes.

**Comment by ppwwyyxx** [comment]
This issue has completely nothing to do with tensorflow. This is a python usage issue.

https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in/42340744

**Comment by FortiLeiZhang** [comment]
Hi, @ppwwyyxx  and @facaiy 

Thanks for your reply. Solved it by explicitly adding the mode 'b' when open the image file:
```python
with open('/home/lzhang/tmp/0000045/001.jpg', 'rb') as img:
```
