### ISSUE TITLE
How to query the amount of memory needed for a model?

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#2155]

**Comment by yaroslavvb** [comment]
No good way really, besides running and seeing if you run out of memory.
You may get more help on stackoverflow, we are trying to keep issues for bugs:

related SO questions
http://stackoverflow.com/questions/36514994/how-to-estimate-the-amount-of-memory-needed-for-rnn
http://stackoverflow.com/questions/36331419/tensorflow-how-to-measure-how-much-gpu-memory-each-tensor-takes

**Comment by danijar** [comment]
Thanks for your reply. I think this would be a useful feature. Maybe keep this open as a feature request?

**Comment by vrv** [comment]
have you seen https://github.com/tensorflow/tensorflow/blob/fe454464681b036ff7fed3e42c6bb541fa52dd7c/tensorflow/python/tools/graph_metrics.py ?  It might not provide everything you want, and 'how much memory is needed' is a little hard to quantify, because you can trade off speed for memory.

**Comment by yaroslavvb** [comment]
Oh, didn't know about graph_metrics....from first glance that seems to only calculate memory needed for parameters and not activations

**Comment by danijar** [comment]
@vrv Thank you, this is what I was looking for.

**Comment by carlthome** [comment]
What superseded `graph_metrics.py`?

**Comment by kaczmarj** [comment]
@carlthome - https://github.com/tensorflow/tensorflow/issues/6983#issuecomment-274165889 says `tfprof` has superseded `graph_metrics.py`.

**Comment by carlthome** [comment]
Thanks @kaczmarj!
