### ISSUE TITLE
Horrible

### ISSUE THREAD

**Issue by mha-py** [tensorflow/tensorflow#21550]
Really a waste of time. Installing all kind of s**t, winpython, anaconda, then, finally, checking that tensorflow doesnt work with 32bit systems. Why cant tensorflow write:
"Only 64 bit supported!!"

**Comment by asimshankar** [comment]
This is mentioned on both https://www.tensorflow.org/install/install_windows and https://www.tensorflow.org/install/install_sources

If you have a suggestion to make that more prominent, we'd be happy to hear.
