### ISSUE TITLE
contrib/quantize vs Graph Transform Tool

### ISSUE THREAD

**Issue by jonkoi** [tensorflow/tensorflow#21558]
Hi,

I am wondering if the quantize_weights and quantize_nodes transforms in Graph Transform Tool use the same method as contrib/quantizei in this paper: https://arxiv.org/abs/1712.05877

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by suharshs** [comment]
Hi @jonkoi 

The contrib/quantize tool instruments the graph with FakeQuant operations and is the exact technique described in the paper you have attached. You can then convert the model to TensorFlow Lite to run full quantized inference.

The instructions to do this are here: https://www.tensorflow.org/performance/quantization and at the contrib/quantize docs (https://github.com/tensorflow/tensorflow/tree/r1.10/tensorflow/contrib/quantize)

The Graph Transform Tool doesn't support this. Further, quantization efforts are being spent more on TensorFlow Lite right now so we recommend using TFLite quantization tools (we will be releasing more as well).

Thanks!
