### ISSUE TITLE
Tensorflow code is not running on GPU

### ISSUE THREAD

**Issue by harishkool** [tensorflow/tensorflow#21564]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.0/7.1.4
- **GPU model and memory**: K80
- **Exact command to reproduce**: 
```
import tensorflow as tf
with tf.device('/GPU:0'):
  w = tf.constant(2.0,shape=[3,3,3,3,1])
  inpt = tf.constant(2.0,shape=[1,5,5,5,3])
  conv = tf.nn.conv3d(inpt,w,[1,1,1,1,1],'SAME')
  init_op = tf.global_variables_initializer()
  with tf.Session() as sess:
    sess.run(init_op)
    print('Convolution Output')
    print( sess.run(conv))
```

I have installed tensorflow from sources and modified(just some print statements in both CPU kernel and GPU kernel) inside '**conv_ops_3d.cc**'. And built from sources, but when I am running on GPU it is always calling CPU code.
Similarly I checked for backprop using '**tf.test.compute_gradient_error**', by keeping some print statements in '**conv_grad_ops_3d.cc**' in CPU kernels and GPU kernels. But this time, it is calling GPU code only (from 'conv_grad_ops_3d.cc' to 'conv_ops_3d.cc'). May be I am missing something small when I am installing from sources..! From the attached file, you can see the yellow colored lines which I changed which are just print statements.
[Conv_ops_3d.pdf](https://github.com/tensorflow/tensorflow/files/2281807/Conv_ops_3d.pdf)

**Comment by reedwm** [comment]
Try replacing all constants with `tf.Variable`s. TensorFlow does constant propagation on the CPU even if your ops are GPU ops. Using `tf.Variable`s instead of constants prevents constant propagation from occurring.

**Comment by harishkool** [comment]
Thank you...Got it...!!
