### ISSUE TITLE
the tensorflow-CPU version can support X86 in window??

### ISSUE THREAD

**Issue by cvJie** [tensorflow/tensorflow#21575]
Now i want to compile tensorflow-CPU by cmake+vs2015 ,which is to get tensorflow.dll and tensorflow.lib，but now I can't sure tensorf-CPU can support X86 in window platform？
thanks

**Comment by harishkool** [comment]
I am guessing what you want to do 
is to compile tensorflow from sources in Windows....Follow the below links:
https://joe-antognini.github.io/machine-learning/build-windows-tf
https://github.com/cjweeks/tensorflow-cmake
https://medium.com/@shiweili/building-tensorflow-c-shared-library-on-windows-e79c90e23e6e

If I am guessing wrong, please correct me..!!

**Comment by iteachmachines** [comment]
Yes it does support in x86 platform in windows.

**Comment by cvJie** [comment]
thanks.
if compile tensorflow from sources in windows , and it can support  win-x86??  No 64

**Comment by iteachmachines** [comment]
Yes it might support on x64-win too.Altough not much sure about it.

**Comment by cvJie** [comment]
thanks

**Comment by AlanNewImage** [comment]
> Now i want to compile tensorflow-CPU by cmake+vs2015 ,which is to get tensorflow.dll and tensorflow.lib，but now I can't sure tensorf-CPU can support X86 in window platform？
> thanks

didyou  got the x86 dll?
