### ISSUE TITLE
[TensorFlow Android Camera Demo] NOTHING DETECTED with SSD FPN model

### ISSUE THREAD

**Issue by AliceDinh** [tensorflow/tensorflow#21570]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Window 10 64bit
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: Samsung Galaxy S7 Edge, RAM 4GB
- **TensorFlow installed from (source or binary)**: binary with pip: pip install tensorflow
- **TensorFlow version (use command below)**: 1.9.0
- **Python version**: Python 3.6.4 |Anaconda custom (64-bit)
- **Bazel version (if compiling from source)**: None
- **GCC/Compiler version (if compiling from source)**: None
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**: None

### Describe the problem
I retrained the model using [SSD FPN](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync.config). The training process was ok, total loss was acceptable at 0.5 after 1.7K steps.
The problem: I imported to [TensorFlow Android Camera Demo](https://github.com/tensorflow/tensorflow/tree/r1.10/tensorflow/examples/android), at DetectorActivity, I modified:
```
private static final String TF_OD_API_MODEL_FILE = "file:///android_asset/frozen_inference_graph.pb"; private static final String TF_OD_API_LABELS_FILE = "file:///android_asset/my_list.txt";
NOTHING DETECTED. 
```
Just to confirm that, the app was working with [SSD Mobilenet V1](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_coco.config) model (re-trained with my own data)

I also changed:
`private static final int TF_OD_API_INPUT_SIZE = 640; ` at DetectorActivity.java because SSD FPN uses input-size 640x640, but not working

**Comment by karmel** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
