### ISSUE TITLE
Custom CUDA op kernel launch dimensions

### ISSUE THREAD

**Issue by Valentin4869** [tensorflow/tensorflow#21571]
Are there any kind of restrictions on the grid dimensions for custom op CUDA kernels?

Thanks

**Comment by PatWie** [comment]
These are standard CUDA kernels, hence normal CUDA restrictions apply:
https://developer.download.nvidia.com/compute/cuda/CUDA_Occupancy_calculator.xls

And Table H.1
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#features-and-technical-specifications

> Maximum ... of a grid of threadblocks
