### ISSUE TITLE
Freezing a graph from a .pb file

### ISSUE THREAD

**Issue by NylaWorker** [tensorflow/tensorflow#21585]
Hello!
This is not a bug or a feature request but I cannot find answers on stackoverflow and have tried multiple ways of fixing this. This is my stack-overflow question: https://stackoverflow.com/questions/51826706/tensorflow-load-a-pb-file-and-then-save-it-as-a-frozen-graph-issues
I went to the discussion forums and after finding some bugs in that code got redirected here. 
This is the code that I have tried:
```
import tensorflow as tf
import sys
from tensorflow.python.platform import gfile

from tensorflow.core.protobuf import saved_model_pb2
from tensorflow.python.util import compat
constant_values = {}

with tf.Session() as sess:
    model_filename ='saved_model.pb'
    with gfile.FastGFile(model_filename, 'rb') as f:

      	data = compat.as_bytes(f.read())# reads binary
      	sm = saved_model_pb2.SavedModel()
        print(sm)
      	sm.ParseFromString(data)# parses through file. 
      	print(sm)
      	if 1 != len(sm.meta_graphs):
      		print('More than one graph found. Not sure which to write')
      		sys.exit(1)
            
        # Attempt at initializing the variables here 
        g_in = tf.import_graph_def(sm.meta_graphs[0].graph_def)
        constant_ops = [op for op in sess.graph.get_operations() if op.type == "Const"]
        for constant_op in constant_ops:
            constant_values[constant_op.name] = sess.run(constant_op.outputs[0])
            
        # Creating frozen graph.
        output_graph = "frozen_grapha.pb"
        output_nodes = [n.name for n in tf.get_default_graph().as_graph_def().node]
        output_graph_def = tf.graph_util.convert_variables_to_constants(
           sess, # The session is used to retrieve the weights
           sess.graph_def,
           output_nodes# The output node names are used to select the usefull nodes
        ) 

        # Finally we serialize and dump the output graph to the filesystem
        with tf.gfile.GFile(output_graph, "wb") as f:
            f.write(output_graph_def.SerializeToString())
        print("%d ops in the final graph." % len(output_graph_def.node))
        print(g_in)
LOGDIR='.'
train_writer = tf.summary.FileWriter(LOGDIR)
train_writer.add_graph(sess.graph)

```

The error I get:
```

tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value NAME_OF_NODE_IN_GRAPH
```

Thank you for your time!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by NylaWorker** [comment]
Sorry, here is all missing info! 

Have I written custom code: No
OS Platform and Distribution: ubuntu 16.04
TensorFlow installed from: pip 
TensorFlow version: tensorflow 1.8 (but I have tried 1.9 and 1.10)
Bazel version: NA
CUDA/cuDNN version: 9.2 (but I don't think it matters in this case)
GPU model and memory: 7gb . (but it doesn't matter) 
Exact command to reproduce
`tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value NAME_OF_NODE_IN_GRAPH
`
Mobile device: NA

**Comment by NylaWorker** [comment]
Hello! 
I figured it out:

```
def frozen_graph_maker(export_dir,output_graph):
        with tf.Session(graph=tf.Graph()) as sess:
        tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], export_dir)
        output_nodes = [n.name for n in tf.get_default_graph().as_graph_def().node]
        output_graph_def = tf.graph_util.convert_variables_to_constants(
                sess, # The session is used to retrieve the weights
                sess.graph_def,
                output_nodes# The output node names are used to select the usefull nodes
        )       
        # Finally we serialize and dump the output graph to the filesystem
        with tf.gfile.GFile(output_graph, "wb") as f:
                f.write(output_graph_def.SerializeToString())
def main():
        export_dir='/dir/of/pb/and/variables'
        output_graph = "frozen_graph.pb"
        frozen_graph_maker(export_dir,output_graph)
```
I realized that I was just loading the meta graph. I would love if you could confirm my understanding of what was failing. With `compat.as_bytes` I was just loading it as a meta graph. Is there a way of integrating variables after doing that kind of loading or should I stick with `tf.saved_model.loader.load()` ? 
My attempt of loading was completely wrong as it wasn't even calling the folder of variables. 

Another question:  with `[n.name for n in tf.get_default_graph().as_graph_def().node]` I am putting all nodes into the output_nodes, should I just put the last node? It works with just the last node. What is the difference? I will close this and post this follow up questions in stackoverflow. Here:https://stackoverflow.com/questions/51826706/tensorflow-load-a-pb-file-and-then-save-it-as-a-frozen-graph-issues/51865645#51865645 

Thank you!

**Comment by Shubham3101** [comment]
@NylaWorker thank you so much for this post.
