### ISSUE TITLE
Division by num_steps when calculating language model perplexity

### ISSUE THREAD

**Issue by giancds** [tensorflow/tensorflow#2158]
Hi all,

I think I found something on the language modeling example that might be a bug: 

As pointed in the tutorial, the perplexity can obtained from the averaged cross entropy. The code show [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/ptb_word_lm.py#L260) and [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/ptb_word_lm.py#L263) the division of the costs by `num_iters`.

Nevertheless, the seq2seq.sequence_loss_by_example is averaging losses across timesteps [(here)](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/seq2seq.py#L871). As no value is passed to the parameter `average_across_timesteps` I'm assuming it is using the default value `True`.

After that, the model is further averaging the losses by the batch size [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/ptb_word_lm.py#L133).

If I'm not wrong (and please correct me if I am), there is no need to divide the costs by `num_iters` as we already averaged over timesteps and the batch. There is no reference in the tutorial regarding why one should do that. If it is something that we should do it would be nice to include an instruction in the tutorial or a comment in the code. In addition, the Seq2seq tutorial is also showing the perplexity calculation and does not have any further division by the number of steps representing the length of the sequence, but by the number of steps between two verbosity points. 

Also, imo, if the intention is averaging, the `step` parameter [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/ptb_word_lm.py#L249)  is the one that should be added to `iters`.

**Comment by rafaljozefowicz** [comment]
in `seq2seq.sequence_loss_by_example` the averaging happens across timesteps but only if the timesteps are specified as a list of elements.

In PTB case we concatenate all the steps before calling that function and `log_perps` ([batch_size * num_steps]) is divided by tf.ones([batch_size * num_steps]) which is esentially a no-op.

Instead of calling sequence_loss_by_example we could directly call sparse_cross_entropy_with_logits because that's the only thing of interest here. In the past, that function was more complicated and we didn't want to copy its logic into ptb_word_lm.py. Feel free to send a PR.

Hope that makes sense!

**Comment by giancds** [comment]
Hi @rafaljozefowicz, thanks for the reply.

Indeed it makes sense, since I have not realized the weights are passed as one big vector and not as in the seq2seq examples.

I'm also glad in contributing with a pull request although I have a question that might either my job easier or not:

should we just include a parameters pass `average_across_timesteps=True` to the function or change it to compute the ` sparse_cross_entropy_with_logits ` directly?

I think the second option would make it more clear for the reader used to cross entropy and perplexities but would also create the need to change the tutorial.

**Comment by girving** [comment]
@giancds: Sorry for the delay; Rafal just left Google.  @ludimagister: Could you answer @giancds's question?

**Comment by ludimagister** [comment]
Hi @giancds,

while your proposed change probably would make sense in a perfect world, possibly just this thread is as informative to understand what's going on? If you want you can send a PR but I am honestly not sure it is worth it given the info in this thread...

**Comment by giancds** [comment]
Hey @ludimagister, thanks for the reply and sorry for the delay. 

Some things came up and I was away of all this discussions. I think you are right, does not worth the effort given what we have in this thread. Sorry for the delay but I think we can close the the issue OK for you.

Thanks again.
