### ISSUE TITLE
unchanging minibatches from skflow DataFeeder for unsupervised tasks

### ISSUE THREAD

**Issue by mheilman** [tensorflow/tensorflow#2159]
I'm pretty sure there's a bug [here](https://github.com/tensorflow/tensorflow/blob/ec0552f1bc0e7c6ec6bd84ea1c3c92ff046d6d3c/tensorflow/contrib/learn/python/learn/io/data_feeder.py#L272) in the DataFeeder class for skflow (tf.contrib.learn).  If there are no labels, then the mapping of input placeholders to inputs is returned without updating the minibatch offsets.  [The code for updating offsets and shuffling](https://github.com/tensorflow/tensorflow/blob/ec0552f1bc0e7c6ec6bd84ea1c3c92ff046d6d3c/tensorflow/contrib/learn/python/learn/io/data_feeder.py#L289) won't be reached.

**Comment by cssndrx** [comment]
Agreed that this looks like a bug. Thanks for the find! 

Feel free to submit a pull request (I can also submit a fix :)

**Comment by mheilman** [comment]
You're welcome.  I just happened to come across it when looking at how the data feeders work.  I don't think I'll have bandwidth for a PR in the near future, but I thought it'd be helpful to make note of it here.

**Comment by cssndrx** [comment]
Thanks again! I'll submit the fix :)

**Comment by mrry** [comment]
@cssndrx: Did this fix make it into the master branch?

**Comment by terrytangyuan** [comment]
@mrry I think so. Looks like you are adding that commit internally. https://github.com/vrv/tensorflow/commit/2c3c49bb6a1a2f3a9ebcf0b9f48cf8988197f718

**Comment by mrry** [comment]
Great, thanks!
