### ISSUE TITLE
TFLite：How to generate partial quantized model

### ISSUE THREAD

**Issue by huangxuwei** [tensorflow/tensorflow#21596]
I only found the way to generate fully quantized model.
https://www.tensorflow.org/performance/quantization

But for high accuracy, maybe we should retrain the network by adding fake quantization for the front part and keeping the last part unchanged. Finally we'd like to generate such partial quantized TFLITE model for mobile application.
Is there any tool to implement except merging two separately generated models manually ?

Thanks

**Comment by suharshs** [comment]
Currently the TFLite converter doesn't support partially quantizing a model. We understand the need for this and plan to add support as we ramp up on other methods of quantization techniques.

So there isn't yet a tool for what you ask, but tools for better quantization options are on our roadmap.

Thanks!

**Comment by suharshs** [comment]
Since we are actively working on new tooling and this is on our roadmap I will close this issue, feel free to reopen if you have a specific related question about this. Thank you!
