### ISSUE TITLE
memory_layer bug

### ISSUE THREAD

**Issue by jiarenyf** [tensorflow/tensorflow#21594]
In Tensorflow 1.10, the following lines conflict, since `None` has no attribute `dtype`.

https://github.com/tensorflow/tensorflow/blob/5326a7fb028d6a66286e9e929dc9454c12e81522/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py#L176

https://github.com/tensorflow/tensorflow/blob/5326a7fb028d6a66286e9e929dc9454c12e81522/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py#L198

https://github.com/tensorflow/tensorflow/blob/5326a7fb028d6a66286e9e929dc9454c12e81522/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py#L204

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by sabhiram** [comment]
The documentation for the function calls out that if the `memory_layer` is None, the memory should assume the shape of the `query_layer` and vice-versa.  However the code ever evaluates what happens when both memory and query layers are not specified.

**Comment by sabhiram** [comment]
Here is a maybe patch:
```
diff --git a/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py b/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py
index 1c9d179e3c..d1d191691a 100644
--- a/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py
+++ b/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py
@@ -185,6 +185,9 @@ class _BaseAttentionMechanism(AttentionMechanism):
         `memory_sequence_length` is not None.
       name: Name to use when creating ops.
     """
+    if (query_layer is None and memory_layer is None):
+      raise TypeError(
+        "either \"query_layer\" or \"memory_layer\" should be specified")
     if (query_layer is not None
         and not isinstance(query_layer, layers_base.Layer)):
       raise TypeError(
@@ -195,13 +198,12 @@ class _BaseAttentionMechanism(AttentionMechanism):
           "memory_layer is not a Layer: %s" % type(memory_layer).__name__)
     self._query_layer = query_layer
     self._memory_layer = memory_layer
-    self.dtype = memory_layer.dtype
+    self.dtype = memory_layer.dtype if memory_layer else query_layer.dtype
     if not callable(probability_fn):
       raise TypeError("probability_fn must be callable, saw type: %s" %
                       type(probability_fn).__name__)
     if score_mask_value is None:
-      score_mask_value = dtypes.as_dtype(
-          self._memory_layer.dtype).as_numpy_dtype(-np.inf)
+      score_mask_value = dtypes.as_dtype(self.dtype).as_numpy_dtype(-np.inf)
     self._probability_fn = lambda score, prev: (  # pylint:disable=g-long-lambda
         probability_fn(
             _maybe_mask_score(score, memory_sequence_length, score_mask_value),
```

**Comment by jiarenyf** [comment]
@tensorflowbutler Could you please remove the label:"stat:awaiting response", since I have closed this issue.

**Comment by sabhiram** [comment]
@jiarenyf : Has this been resolved in latest? Do you guys not elaborate why an issue gets closed?
