### ISSUE TITLE
how to automatically restart worker/master after occasional crash

### ISSUE THREAD

**Issue by MrWanter** [tensorflow/tensorflow#21604]
HI! I'm running distributed training of tensorflow, I have a very simple question, does TF provide some feature for monitor and automatically restart crashed worker/master all all training process, as currently I can only manually restart failed worker.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by cy89** [comment]
@mrry do we have any such facility?

**Comment by mrry** [comment]
No, we rely on a cluster manager such as Kubernetes to restart crashed processes. See the KubeFlow project for a high-level example of using Kubernetes to manage a set of TensorFlow jobs:

https://github.com/kubeflow/kubeflow
