### ISSUE TITLE
The return value of _has_variables() in freeze_graph.py is not consistent with what its name imply

### ISSUE THREAD

**Issue by stonexjr** [tensorflow/tensorflow#21627]
https://github.com/tensorflow/tensorflow/blob/3109a8fb2c966ea5ce198c8906a703ee48af75fb/tensorflow/python/tools/freeze_graph.py#L71-L74

I'm a bit of surprised to notice this. Shouldn't the helper function `_has_variables` simply returns `False` (line 74) when no `Variable` has been found in the operations? Shall we change the function name to `_has_no_variables` or reverse the true/false logic?

Furthermore, 
https://github.com/tensorflow/tensorflow/blob/3109a8fb2c966ea5ce198c8906a703ee48af75fb/tensorflow/python/tools/freeze_graph.py#L171-L173

if `_has_variables` returns true, why it prints out "no variable were found...."? 

Bad naming.

Have I written custom code: no
OS Platform and Distribution: ubuntu 14.04
TensorFlow installed from: tensorflow-gpu
TensorFlow version: 1.9
Bazel version: N/A
CUDA/cuDNN version: 9.0/7.0
GPU model and memory: TITAN Xp 12GB
Exact command to reproduce: N/A (just read the source code I pointed out)
Mobile device: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by stonexjr** [comment]
Just updated the description. Thanks.

**Comment by allenlavoie** [comment]
@gargn any thoughts on the function naming?

**Comment by gargn** [comment]
Thanks for reporting this issue. It has been fixed [here](https://github.com/tensorflow/tensorflow/commit/09e272a6a5c3359b671a068f4dac2bca8b312358).

**Comment by stonexjr** [comment]
💯
