### ISSUE TITLE
Compilation Error: suffix or operands invalid for `vpaddd'

### ISSUE THREAD

**Issue by soporteCluster** [tensorflow/tensorflow#21634]
Hi,
i'm trying to install tensorflow with CUDA support and I have the following issue whe i execute 
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures

ERROR: 
/home/user/.cache/bazel/_bazel_user/95b102d38f4be088a2028c5510fdf1c2/external/boringssl/BUILD:130:1: C++ compilation of rule '@boringssl//:crypto' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
cd /home/user/.cache/bazel/_bazel_user/95b102d38f4be088a2028c5510fdf1c2/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/share/apps/libxc-3.0.1/lib/:/share/apps/libgpuarray/lib/:/opt/python/lib/:/share/apps/gcc-6.3.0/lib64:/opt/gridengine/lib/linux-x64 \
    PATH=/share/apps/python/python2.7/bin/:/opt/python/bin/:/share/apps/cmake-3.9.1/bin:/share/apps/gcc-6.3.0/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bio/ncbi/bin:/opt/bio/mpiblast/bin:/opt/bio/EMBOSS/bin:/opt/bio/clustalw/bin:/opt/bio/tcoffee/bin:/opt/bio/hmmer/bin:/opt/bio/phylip/exe:/opt/bio/mrbayes:/opt/bio/fasta:/opt/bio/glimmer/bin:/opt/bio/glimmer/scripts:/opt/bio/gromacs/bin:/opt/bio/gmap/bin:/opt/bio/tigr/bin:/opt/bio/autodocksuite/bin:/opt/bio/wgs/bin:/opt/eclipse:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/java/latest/bin:/opt/rocks/bin:/opt/rocks/sbin:/opt/gridengine/bin/linux-x64:/share/apps/local/bin:/home/user/bin \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/host/bin/external/boringssl/_objs/crypto/chacha20_poly1305_x86_64.pic.d -iquote external/boringssl -iquote bazel-out/host/genfiles/external/boringssl -iquote bazel-out/host/bin/external/boringssl -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -isystem external/boringssl/src/include -isystem bazel-out/host/genfiles/external/boringssl/src/include -isystem bazel-out/host/bin/external/boringssl/src/include -g0 '-march=native' -Wa,--noexecstack '-D_XOPEN_SOURCE=700' -Wall -Werror '-Wformat=2' -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -Wshadow -fno-common '-std=c11' -Wmissing-prototypes -Wold-style-definition -Wstrict-prototypes -c external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S -o bazel-out/host/bin/external/boringssl/_objs/crypto/chacha20_poly1305_x86_64.pic.o)
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S: Assembler messages:
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4104: Error: no such instruction: `vbroadcasti128 0(%r9),%ymm4'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4105: Error: no such instruction: `vbroadcasti128 16(%r9),%ymm8'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4106: Error: no such instruction: `vbroadcasti128 32(%r9),%ymm12'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4107: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4118: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4119: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4120: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4121: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4122: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4123: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4124: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4125: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4126: Error: suffix or operands invalid for `vpaddd'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by d0ntbeshy** [comment]
I got the similar error when i install tensorflow without CUDA

ERROR: /home/user/.cache/bazel/_bazel_user/539629cca61901b68a2179672fed247c/external/boringssl/BUILD:115:1: C++ compilation of rule '@boringssl//:crypto' failed (Exit 1)
external/boringssl/linux-x86_64/crypto/fipsmodule/p256-x86_64-asm.S: Assembler messages:
external/boringssl/linux-x86_64/crypto/fipsmodule/p256-x86_64-asm.S:638: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/fipsmodule/p256-x86_64-asm.S:639: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/fipsmodule/p256-x86_64-asm.S:640: Error: suffix or operands invalid for `vpxor'
...

OS:Alibaba Group Enterprise Linux Server release 6.2 (DogTag)
Tensorflow installed from source.
Tensorflow version: 1.10
Python version: 3.6
Bazel version: 0.15.2
GCC version: 7.2.0
Command:
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

Thanks!

**Comment by soporteCluster** [comment]
Hi,
I resolved the issue by adding "binutils 2.29" to the environment variables PATH and LD_LIBRARY_PATH:
PATH=/share/apps/binutils/binutils-2.29.1/bin/:$PATH
LD_LIBRARY_PATH=/share/apps/binutils/binutils-2.29.1/lib/:$LD_LIBRARY_PATH
