### ISSUE TITLE
ReadSavedModel & related operations should follow symlinks

### ISSUE THREAD

**Issue by masonk** [tensorflow/tensorflow#21648]
https://github.com/tensorflow/tensorflow/blob/98010279f40e4963512ba2f2f39c3d732aef7b93/tensorflow/cc/saved_model/reader.cc#L34

Consider that line, and now consider what happens if `export_dir` is the pathname of a symlink to a directory.

The way I'm reading this, the naive file join will fail to find the kSavedModelFilenamePb file that the op is looking for, since it will be looking at `<symlink>/saved_model.pb` instead of `<link_target>/saved_model.pb` as (I think) would be logical.

This came up for me recently. I have one process that's continually training and occasionally promoting a new version of the model to a SavedModel for inference in a second process. The second process runs concurrently and occasionally loads the latest SavedModel from disk.

Atomically swapping a directory for another directory is either not possible on POSIX or, if it is possible, I couldn't find out a way from searching. However, it's easy to atomically swap the referent of a symlink. My naive hope was to maintain a symlink to the "current best SavedModel" which the second process would be able to use. The second process is Rust, and it's binding to the C API, which I traced all the way back to the linked line above.

Admittedly this isn't extremely easy to fix (or maybe it's not possible to fix - not sure if holding a directory fd preserves the directory's contents from removal by another process). In order to be useful for my use case, doing the easy thing of resolving the symlink in one operation and then doing file joins wouldn't work, because the symlink is subject to swap to a new referent at any point of time, and that could happen between the resolution of the symlink and ops on the referents. 

Anyway, there is a workaround for this use case (some sort of file locking should do the trick). But, I wanted to point this out.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by poxvoculi** [comment]
@nfiedel: Can you take a look at this, or recommend someone else?

**Comment by Philipp91** [comment]
Sorry, I don't know the answer to this. I have refactored the code at two separate occasions: when I moved it from loader.cc to reader.cc, and when I changed the error reporting (the latter might not even be submitted yet?).
The `io::JoinPath()` call has been there before and in the same way.

My personal uninformed opinion about this:
Symlinks are an artifact of the underlying filesystem, everything should work fine if the TensorFlow code doesn't deal with them. Yes, it does look at `<symlink>/saved_model.pb`, and that's just as logical as the other version. I don't see why this would cause it to "fail to find the kSavedModelFilenamePb", that's still a valid file path even if it goes through the symlink.

The standard solution for continuous training and serving is to have the training create epoch directories with numerically/alphabetically increasing names. Then the serving process can `ls` the directory (or even a symlink) periodically and pick the latest one to load.

If you absolutely want to keep pointing a symlink to the latest version, but need the path to be fixed to the resolved target when the model is loaded, couldn't you do the symlink resolution in your own code, and then pass the resolved path to the `export_dir` parameter?

**Comment by masonk** [comment]
I just tried it again in an isolated test, and you're right. Core _was_ able to resolve `<symlink>/saved_model.pb` to the target. It must have been something in my code that was choking the symlink.

This code is fine as-is, sorry for the bother.
