### ISSUE TITLE
Convolution for 1D

### ISSUE THREAD

**Issue by RobRomijnders** [tensorflow/tensorflow#2165]
Dear community,

Do you know of any implementation for 1 dimensional convolution in TensorFlow?

For the moment, I circumvented this by using conv2d with a filter of 5x1. This works good and I was able to surpass state-of-the-art performances on some datasets. However, this short-term 'hack' doesn't allow for longer strides. With a 5x1 filter, I cannot make strides of 2. Tensorflow will raise error that 'stride must be less than or equal to filter size'

Do you know of any 1D implementation for tf.nn.conv2d?
If not, how can I recommend this to the developing team of TensorFlow? A 1D conv would make TensorFlow useful to the world of time-series classification, which is a plus for TensorFlow as well

Thank you in advance!

Rob

**Comment by vrv** [comment]
@ry recently added support for strides > filter, so if you use our nightly pip binaries or build from sources you should be able to do what you want!  It will be part of our next official release if you want to just wait.

**Comment by ry** [comment]
@RobRomijnders can i ask what you're using 1d conv for?

**Comment by RobRomijnders** [comment]
Thanks @vrv 

@ry I'm working on CNN for time series. Therefore i use 1d conv

Like these three projects
  * [Music genre classification with CNN](http://robromijnders.github.io/cnn_music/)
  * [Time-series classification with LSTM's in Tensorflow](http://robromijnders.github.io/LSTM_tsc/)
  * [Time-series classification with CNN's](http://robromijnders.github.io/CNN_tsc/)

**Comment by renesax14** [comment]
are there any docs explaining how to actually use the 1D conv/CNN?
