### ISSUE TITLE
Build failed due to missing "tensorflow/contrib/constrained_optimization"

### ISSUE THREAD

**Issue by LvanderGoten** [tensorflow/tensorflow#21652]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS High Sierra 10.13.6
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: Not applicable
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: r1.10
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**: 0.15.2-homebrew
- **Clang version**: 
```
clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
- **CUDA/cuDNN version**: CPU only
- **GPU model and memory**: CPU only
- **Exact command to reproduce**: 
```bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package```

### Describe the problem
Following the help page that describes how to install TensorFlow from source, I first ran `./configure`(I declined each question and used valid paths for Python) followed by `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

### Source code / logs
```
Starting local Bazel server and connecting to it...
..........................................
ERROR: /Users/.../Build/tensorflow/tensorflow/tools/pip_package/BUILD:180:1: no such package 'tensorflow/contrib/constrained_optimization': BUILD file not found on package path and referenced by '//tensorflow/tools/pip_package:build_pip_package'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package 'tensorflow/contrib/constrained_optimization': BUILD file not found on package path
INFO: Elapsed time: 55.970s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (6 packages loaded)
```
Dots in the first path are used to conceal the real path.

**Comment by gunan** [comment]
Could you share the output of the command `git describe --tags --long` in the branch you are trying to build?
In our CI, everything seems to be green.

**Comment by LvanderGoten** [comment]
I cloned the repository again yesterday and don't have this problem any more. Thanks for you effort!
