### ISSUE TITLE
Feature Request:  API for the Julia Language.

### ISSUE THREAD

**Issue by as1ndu** [tensorflow/tensorflow#2168]

**Comment by ViralBShah** [comment]
There is this package that wraps the TensorFlow Python APIs using Julia's PyCall.

https://github.com/benmoran/TensorFlow.jl

Another approach could be to wrap the C++ APIs (using Julia's Cxx.jl, which is very easy). I have not looked inside TensorFlow but talking to those who have, I understand that a substantial part of TensorFlow is in Python, and if one were to use the C++ APIs, a bunch of the other stuff in the python part of the codebase would need to be recreated. 

Cc: @benmoran @ninjin

**Comment by as1ndu** [comment]
wow thanx!!!

**Comment by ViralBShah** [comment]
There is now a reasonably sophisticated TensorFlow Julia package by @malmaud 

https://github.com/malmaud/TensorFlow.jl

Can this be featured on the TensorFlow website?
