### ISSUE TITLE
Bazel build for llvm fails in sandboxed mode

### ISSUE THREAD

**Issue by guoshimin** [tensorflow/tensorflow#21685]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.9.0, 1.10.0, master
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.15.2
- **GCC/Compiler version (if compiling from source)**: 6.3
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**:
- **Exact command to reproduce**:
```
$ bazel build @llvm//:orc_jit --spawn_strategy=sandboxed
INFO: Analysed target @llvm//:orc_jit (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/sguo/.cache/bazel/_bazel_sguo/312e4bfd87ddc7075e69d12d6c5f1e44/external/llvm/BUILD.bazel:1641:1: C++ compilation of rule '@llvm//:orc_jit' failed (Exit 1)
external/llvm/lib/ExecutionEngine/Orc/CompileOnDemandLayer.cpp:12:40: fatal error: llvm/Bitcode/BitcodeWriter.h: No such file or directory
 #include "llvm/Bitcode/BitcodeWriter.h"
                                        ^
compilation terminated.
Target @llvm//:orc_jit failed to build
Use --verbose_failures to see the command lines of failed build steps.
```
```
$ bazel build @llvm//:analysis --spawn_strategy=sandboxed
INFO: Analysed target @llvm//:analysis (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/sguo/.cache/bazel/_bazel_sguo/312e4bfd87ddc7075e69d12d6c5f1e44/external/llvm/BUILD.bazel:598:1: C++ compilation of rule '@llvm//:analysis' failed (Exit 1)
external/llvm/lib/Analysis/MemoryBuiltins.cpp:24:39: fatal error: llvm/Analysis/Utils/Local.h: No such file or directory
 #include "llvm/Analysis/Utils/Local.h"
                                       ^
compilation terminated.
Target @llvm//:analysis failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

### Describe the problem

The bazel build targets for llvm are missing header file declarations. They only build when Bazel doesn't enforce a sandboxed environment. When sandboxing in enabled, the builds fail.

**Comment by cy89** [comment]
@jart @gunan @martinwicke would you PTAL?

**Comment by martinwicke** [comment]
This would be a problem for the XLA build on remote workers. @tatatodd could you take a look?

**Comment by guoshimin** [comment]
any update?

**Comment by gunan** [comment]
@klimek recently fixed this and got XLA+TF build on remote workers.

**Comment by guoshimin** [comment]
:+1:
