### ISSUE TITLE
INT TFLITE very much slower than FLOAT TFLITE

### ISSUE THREAD

**Issue by abhi-rf** [tensorflow/tensorflow#21698]
Hi Guys. I am using Mobilenet 0.25,128. I used the pretrained models provided in the repo for obtaining the int tflite and float tflite models for the same [found here](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md). I am trying to infer some images. Using the imagenet images and some other test images as well, the FLOAT TFLITE is faster than the INT TFLITE (FLOAT TFLITE takes roughly 3-4 milliseconds while INT one takes 8-9 ms). Any suggestions as to why this is happening ?I am running the inferences using the tflite interpreter following the documentation [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/g3doc/python_api.md#interpreter). This issue happens with the tf-nightly builds as well as the normal tensorflow. Tried on both, and also on both python 2 as well as 3.
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:Binary
- **TensorFlow version (use command below)**:1.10 (tf-nightly) 
- **Python version**:2
- **Bazel version (if compiling from source)**
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: No
- **GPU model and memory**: No

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs

# ####INT TFLITE CODE####

```
#Load TFLite model and allocate tensors. Select the appropriate model and give its path
interpreter = tf.contrib.lite.Interpreter(model_path='mobilenet_v1_0.25_128_quant.tflite')



#For allocating the model tensors
interpreter.allocate_tensors()

#Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
#print(input_details)
#print(output_details)

k=1
for image_path in TEST_IMAGE_PATHS:
	#Loading the image and resizing into the correct shape
	#Change the .astype(np.uint8) (used when using int tflite) to .astype(np.float32) if using float tflite
	img = np.array(PIL.Image.open(image_path).resize((128, 128))).astype(np.uint8)

	img = img.reshape(1,128,128,3)
	#print(input_details)
	#print (img.shape)
	
	#Setting the input image to the input tensor
	interpreter.set_tensor(input_details[0]['index'], img)

	#Running inference and timing it
	start = time.time()
	interpreter.invoke()
	end = time.time()

	#Getting the output information
	output_data = interpreter.get_tensor(output_details[0]['index'])

	#Converting the prediction into human readable form
	#label_map = imagenet.create_readable_names_for_imagenet_labels()  
	print("Top 1 Prediction: ", output_data.argmax()-1, output_data.max(), k+1,labels[output_data.argmax()-1])
	
	total_infer_time+=(end-start)
	k+=1

#printing average inference time along with the accuracy
print("Total infer time avg (in seconds) == ",total_infer_time/no_images)



```
# ####FLOAT TFLITE CODE####
```
#Load TFLite model and allocate tensors. Select the appropriate model and give its path
interpreter = tf.contrib.lite.Interpreter(model_path='mobilenet_v1_0.25_128.tflite')


#For allocating the model tensors
interpreter.allocate_tensors()

#Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
#print(input_details)
#print(output_details)
k = 1           
for image_path in TEST_IMAGE_PATHS:
	print image_path
	#Loading the image and resizing into the correct shape
	#Change the .astype(np.uint8) (used when using int tflite) to .astype(np.float32) if using float tflite
	img = np.array(PIL.Image.open(image_path).resize((128, 128))).astype(np.float32) / 128 - 1

	img = img.reshape(1,128,128,3)
	#print (img.shape)
	
	#Setting the input image to the input tensor
	interpreter.set_tensor(input_details[0]['index'], img)

	#Running inference and timing it
	start = time.time()
	interpreter.invoke()
	end = time.time()

	#Getting the output information
	output_data = interpreter.get_tensor(output_details[0]['index'])

	#Converting the prediction into human readable form
	#label_map = imagenet.create_readable_names_for_imagenet_labels()  
	#print("Top 1 Prediction: ", output_data.argmax()-1, output_data.max(), k+1,labels[output_data.argmax()-1])
	
	#detect_dog(output_data)


	'''
	#For accuracy
	number = []
	number = int(mobilenet_labels[k])
	        

	if(number==output_data.argmax()):
	    accuracy+=1

	'''
	total_infer_time+=(end-start)
	print total_infer_time/(k+1)
	k+=1

#printing average inference time along with the accuracy
print("Total infer time avg (in seconds) == ",total_infer_time/no_images)

``````

```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by aselle** [comment]
This is likely because quantized int requires an arm neon to be faster than float. On a PC (which is what I assume you are running on, float is likely better). This is because quantized int relies on special instructions that have not been emphasized on intel x86_64.

**Comment by abhi-rf** [comment]
It makes sense. Thanks. That means that it should give good time improvement when I run it on raspberry pi or some other arm device. Thanks a ton. I'll reopen the issue if there's further issue.

**Comment by arun-kumark** [comment]
Dear all,
I am testing the performance/throughput of fp32 and quantized models on my platform x86. My configuration is as follows:

tflite-runtime==2.5.0.post1
tensorflow==1.14.0


**Hardware**
```
-INFO- CPU Name             : GenuineIntel Intel(R) Core(TM) i5-6442EQ CPU @ 1.90GHz
-INFO- Total Memory (MiB)   : 15938
-INFO- # of Logical CPUs    : 4
-INFO- Instruction Set      : x86_64
```

**FP32 on CPU**

```
-INFO- Running prediction...
-INFO- Acquired 1 file(s) for model 'MobileNet v1.0'
-INFO- Task runtime: 0:00:28.796083
-INFO- Throughput: 35.8 fps
-INFO- Latency: 29.5 ms
-INFO- Target          Workload        H/W   Prec  Batch Conc. Metric       Score    Units
-INFO- -----------------------------------------------------------------------------------
-INFO- tensorflow_lite mobilenet       cpu   fp32      1     1 throughput    35.8      fps
-INFO- tensorflow_lite mobilenet       cpu   fp32      1     1 latency       29.5       ms
-INFO- Total runtime: 0:00:28.830364
-INFO- Done

```

**INT8 on CPU**
```
google@localhost:~/mlmark$ harness/mlmark.py -c config/tflite-cpu-mobilenet-int8-throughput.json 
-INFO- Running prediction...
-INFO- Acquired 1 file(s) for model 'MobileNet v1.0'
-INFO- Task runtime: 0:01:00.933346
-INFO- Throughput: 16.9 fps
-INFO- Latency: 65. ms
-INFO- Target          Workload        H/W   Prec  Batch Conc. Metric       Score    Units
-INFO- -----------------------------------------------------------------------------------
-INFO- tensorflow_lite mobilenet       cpu   int8      1     1 throughput    16.9      fps
-INFO- tensorflow_lite mobilenet       cpu   int8      1     1 latency       65.        ms
-INFO- Total runtime: 0:01:00.960828
-INFO- Done
```

Observations: The performance of FP32 model is almost double than INT8 models on CPU, but Google TensorFlow lite benchmarking mentions the opposite:
[https://www.tensorflow.org/lite/guide/hosted_models#quantized_models](url)

I also tried the models present in above Hosted location, but the harness gives the similar results.

Could you let me know, where it's going wrong?

Thanks
Kind Regards
Arun

**Comment by huzq85** [comment]
> This is likely because quantized int requires an arm neon to be faster than float. On a PC (which is what I assume you are running on, float is likely better). This is because quantized int relies on special instructions that have not been emphasized on intel x86_64.

hello, @aselle , thank you for your comments! I think it makes sense but I ran the quantized tflited model on my (Android) phone and the inference speed is still slow. I tried both on Tensorflow 2.8.1 and 2.9.1, the results of the quantized version is slower than the one without quantization. My question is, how could I enable ARM NEON intrinsic when I ran the tflite model? Any comments are appreciated!

**Comment by mikel-brostrom** [comment]
You won't see INT8 boosts on Intel CPUs under 10th gen. This is because CPUs < 10th gen don't gave Intel DLBoost which is explicitly meant for INT8 calculations.
