### ISSUE TITLE
Is pep8 compatibility necessary right now for tensorflow?

### ISSUE THREAD

**Issue by taranjeet** [tensorflow/tensorflow#217]
On running the pep8 test, I found out around 18k warnings. I think we should strict to some guideline, so that as the project grows, a proper standard is maintained. We can use flake8 for this.

I can work on this and submit a PR, if pep8 compatibility is required.

**Comment by vrv** [comment]
Thanks for the report -- we'll look into this at some point!  Hopefully our code is at least internally consistent :)

**Comment by staranjeet** [comment]
ok, then i work on this later on.

**Comment by girving** [comment]
@martinwicke: Do we have a plan in terms of linting and/or pep8 compliance?  Should this be closed?

**Comment by martinwicke** [comment]
Plans, yes, time to do it, no. I would like to make much more of the pylint
we're already running, and ideally add cpplint as well.

**Comment by girving** [comment]
@martinwicke: I'll leave it assigned to you for now, and you can reassign to other testing folk as appropriate.

**Comment by staranjeet** [comment]
I can work on this.

**Comment by girving** [comment]
@staranjeet: I think we may need to figure out a policy of just how pep8 compliant we want to be first.  For example, I'd hate to give up our 2 space indent paradise.

**Comment by martinwicke** [comment]
Definitely not while we still maintain a 80-character hard limit.

**Comment by martinwicke** [comment]
@staranjeet We'd like to ignore some thing (in particular, the 4 space indent), but otherwise, proper linting would be great. We already run pylint as part of the build, but we disabled all but the most terrible errors (syntax errors, unknown names) in order to make it blocking without damaging productivity.

It would be nice to have a stricter pylintrc that we can use for informational purposes. Especially if we can generate statistics on how many lint issues were added (and make that a blocking error). 

I haven't used flake8 miself, if it supports both python 2 and python 3 and is sufficiently flexible we could use that as well.

**Comment by martinwicke** [comment]
Closing this -- if there are specific violations, or a nicer linter for our tests, I'd love more concrete issues or PRs.

**Comment by staranjeet** [comment]
I ran a pep8 test and found that most of the warnings were for spaces as 2
and 80 char limit. As for the spaces, I think that as per the above
conversation we are going with 2 spaces convention. Char limit can be
discussed.

Also let me know if there are any other linters. I was a little busy, will
also look myself today.

**Comment by martinwicke** [comment]
We currently use pylint: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/ci_sanity.sh

We can talk about changing options to make it more powerful -- it will need some experimentation to get the right balance between false positives (which we have to whitelist) and enforcing the rules.

**Comment by staranjeet** [comment]
Ok I will look this into today and update accordingly.

**Comment by staranjeet** [comment]
The errors which we are planning to ignore


| Error |                Error meaning                    |
|------ |-------------------------------------------------|
| E501  | line too long                                   |
| E111  | indentation is not a multiple of four           |
| E114  | indentation is not a multiple of four(comment)  |
| E701  | multiple statements on one line (colon)         |

Now the stats while running pep8(ignoring the above mentioned erros) tests are as follows:

| Error|                Error meaning                                          |  Count  |
|------|-----------------------------------------------------------------------|---------|
| E101 | indentation contains mixed spaces and tabs                            |    2    |
| E115 | expected an indented block (comment)                                  |    4    |
| E116 | unexpected indentation (comment)                                      |    1    |
| E121 | continuation line under-indented for hanging indent                   |    27   |
| E123 | closing bracket does not match indentation of opening bracket's line  |    18   |
| E124 | closing bracket does not match visual indentation                     |    15   |
| E125 | continuation line with same indent as next logical line               |    195  |
| E126 | continuation line over-indented for hanging indent                    |    22   |
| E127 | continuation line over-indented for visual indent                     |    102  |
| E128 | continuation line under-indented for visual indent                    |    145  |
| E129 | visually indented line with same indent as next logical line          |    106  |
| E131 | continuation line unaligned for hanging indent                        |    7    |
| E201 | whitespace after '['                                                  |    14   |
| E202 | whitespace before ']'                                                 |    1    |
| E203 | whitespace before ':'                                                 |    3    |
| E222 | multiple spaces after operator                                        |    1    |
| E225 | missing whitespace around operator                                    |    21   |
| E226 | missing whitespace around arithmetic operator                         |    300  |
| E227 | missing whitespace around bitwise or shift operator                   |    2    |
| E231 | missing whitespace after ','                                          |    58   |
| E241 | multiple spaces after ','                                             |    1    |
| E251 | unexpected spaces around keyword / parameter equals                   |    15   |
| E261 | at least two spaces before inline comment                             |    6    |
| E262 | inline comment should start with '# '                                 |    1    |
| E265 | block comment should start with '# '                                  |    57   |
| E266 | too many leading '#' for block comment                                |    78   |
| E271 | multiple spaces after keyword                                         |    5    |
| E272 | multiple spaces before keyword                                        |    2    |
| E301 | expected 1 blank line, found 0                                        |    98   |
| E302 | expected 2 blank lines, found 1                                       |    55   |
| E303 | too many blank lines (2)                                              |    7    |
| E304 | blank lines found after function decorator                            |    1    |
| E402 | module level import not at top of file                                |    43   |
| E502 | the backslash is redundant between brackets                           |    3    |
| E704 | multiple statements on one line (def)                                 |    1    |
| E711 | comparison to None should be 'if cond is None:'                       |    4    |
| E731 | do not assign a lambda expression, use a def                          |    155  |
| W191 | indentation contains tabs                                             |    2    |
| W291 | trailing whitespace                                                   |    43   |
| W293 | blank line contains whitespace                                        |    15   |
| W391 | blank line at end of file                                             |    15   |
| W503 | line break before binary operator                                     |    58   |


I think that these should be removed. Let me know your opinion

**Comment by martinwicke** [comment]
E402 has valid uses (conditional imports to avoid breaking on missing soft
dependencies) and we should probably ignore those if they are used for such
a purpose.

E129 is a bit iffy, i have to check how these look.

I'd like to find a way to enforce these going forward (=add a stricter
linter test), but we have to make sure that we don't conflict with our
internal tools. Otherwise I agree, these should be fixed.

**Comment by martinwicke** [comment]
Actually, we want to enforce line-too-long, but with some exceptions
(import statements for instance can make unavoidably long lines)

**Comment by staranjeet** [comment]
So I should start fixing pep8 warning or add clauses first in existing pylintrc?

**Comment by martinwicke** [comment]
We can't really add the clauses until the code is clean, as currently set
up, pylint errors are a test failure blocking a commit.

**Comment by ohmystack** [comment]
@staranjeet I don't think we should ignore any pep8 errors, `E501,E111,E114,E701`.

Every developer should config his/her Python editor with a full PEP8 checker.

Like the [coding style](http://docs.openstack.org/developer/hacking/) of OpenStack, the largest open source project in Python, says,

> * Step 1: Read pep8
> * Step 2: Read pep8 again
> * Step 3: Read on

I know that TensorFlow has made some declaration about `E111` in [Coding Guide](https://www.tensorflow.org/versions/r0.9/how_tos/style_guide.html), but, do you want every developer to change his/her Python editor configuration to ignore the PEP8 E111?

TensorFlow's coding style should be corrected, not everyone's PEP8 rules.

**Comment by ohmystack** [comment]
You can use a tool [autopep8](https://pypi.python.org/pypi/autopep8) to fix all of the PEP8 things. Though this may effect the `git blame` now, it will take a good effect to the future.

**Comment by staranjeet** [comment]
So I can start working on this?. What should be the line length that we are following for E501?

**Comment by staranjeet** [comment]
@ohmystack @martinwicke : any comments?

**Comment by aselle** [comment]
@martinwicke any direction here for @TroJan who is excited to work on this.

**Comment by martinwicke** [comment]
E501 should be 80 characters. I encourage you to do this, I'm not terribly concerned about git blame per se, it's the nature of things.

**Comment by martinwicke** [comment]
Any news on this? We have autopep8 set up now, but it's doing fairly minimal things so far (and @yifeif hacked a version to do 2 space indent).

**Comment by ohmystack** [comment]
@martinwicke @yifeif 

Though I don't understand why TensorFlow team insists on 2 space indent, which is invalid in both PEP8 and Google Python Style Guide, hacking the `autopep8` for 2 space indent is a bad idea.

If the TF uses 2 space indent, which is a special case for most of the Python developers, please add a comment line at the beginning of all the files.

Like this,

```python
#!/usr/bin/env python
# vim: tabstop=2 shiftwidth=2 softtabstop=2
```

> Why? Please see: https://wiki.python.org/moin/Vim

Indentaion is very important for Python scripts as we all known.
Try not to hack the PEP8. Tell it explicitly in code.

**Comment by martinwicke** [comment]
Yes, 2 space indent is a bit of an accident, but here we are, and changing it is not a priority (and would invalidate 100% of our git blame, which is too valuable to lose). 

I would also prefer an annotation for each file, but I don't believe that linter tools will respect vim comments, and vim will likely not respect pylint directives (which we'd be more likely to use).

**Comment by esc** [comment]
I'd like to see this addressed too, my vim goes all red when I open TF code. Either adding a decent flake8 config (like in https://github.com/tensorflow/tensorflow/pull/4511#event-804342012) and vim header or fixing the 2 space thing would be fine with me.

For the time being, I'm just putting a `.flake8` file in my local tree, that solves everything being red and I still have some descent linting. Not sure about the vim-config, anyone know how to configure vim to have project based overrides? For example to use the config suggested above, but only when starting vim in a specific directory or set of files?

Also, you should check out: https://www.youtube.com/watch?v=wf-BqAjZb8M (just auto-pepping the entire code-base is not a solution)

**Comment by martinwicke** [comment]
@yifeif is working on this. I'll reassign.

**Comment by mortada** [comment]
I'd like to +1 migrating to the standard 4-space indentation. I've seen quite a few places in the tensorflow codebase with a mix of 2-space and 4-space indentations in the same file. This is really not great.

Also like to +1 the comment above to extend the 80char limit

**Comment by mortada** [comment]
also on the point about `git blame`, we can always just use `git blame -w` which will ignore whitespace only changes. So we can still get the desired information fairly easily

```
-w
           Ignore whitespace when comparing the parent's version and the child's to find where the lines came from.
```

**Comment by gunan** [comment]
In some of these checks, we are bound by google's style. Therefore, I think the amount of enforcement for pep8 we have in place right now will stay.
Closing this issue, please reopen if you think there needs to be more discussion on this.
