### ISSUE TITLE
Numpy 15.0 support

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/tensorflow#21700]
It seems numpy newest version has comes out for a long time, but as far as tensorflow 1.10, it not support numpy 15.0 yet.
While pytorch using numpy 15.0 above, this is really awkward... I have to using 2 versions numpy

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wookayin** [comment]
How does precisely numpy 1.15 break TF?

**Comment by jinfagang** [comment]
@wookayin You can not be installed tensorflow newest version under numpy < 15.0

**Comment by av8ramit** [comment]
This will be fixed in 1.11.
