### ISSUE TITLE
Index into tensor

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#2170]
I'd like to have a `tf.index` function that works like this:

```python
import tensorflow as tf

weights = tf.constant([[0, 0], [1, 1], [2, 2]])
indices = tf.constant([0, 2, 1, 2])

indexed = tf.index(weights, indices)
#indexed = [[0, 0], [2, 2], [1, 1], [2, 2]]
```

That is, `indexed[i] = weights[indices[i]]`. Of the existing functions, `tf.slice` comes close, but it doesn't seem to allow for multiple slices. A less efficient way of doing this is to use `tf.one_hot` and a matrix multiply, but this should be straightforward to do.

**Comment by mrry** [comment]
`tf.gather()` works for exactly the case you describe (it's not perfect, but it handles indexing on the 0th dimension):

```python
>>> import tensorflow as tf
>>> 
>>> weights = tf.constant([[0, 0], [1, 1], [2, 2]])
>>> indices = tf.constant([0, 2, 1, 2])
>>> indexed = tf.gather(weights, indices)
>>> sess = tf.Session()
>>> sess.run(indexed)
array([[0, 0],
       [2, 2],
       [1, 1],
       [2, 2]], dtype=int32)
```

**Comment by sicongliu92** [comment]
I have a solution: please see https://github.com/sicongliu92/DL-code/blob/master/unpool(1).py
