### ISSUE TITLE
parallel_for's jacobian and batch_jacobian fail when inputs are disjoint in the comp. graph

### ISSUE THREAD

**Issue by artsobolev** [tensorflow/tensorflow#21717]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: reproducible on macOS High Sierra 10.13.4 and Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: reproducible on both source and binary
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.15.2-homebrew
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Mobile device**: N/A
- **Exact command to reproduce**:

```python
import tensorflow as tf
from tensorflow.python.ops.parallel_for import gradients

x = tf.placeholder(tf.float32, (None,))
y = tf.placeholder(tf.float32, (None,))
print(gradients.jacobian(x, y))
```

### Describe the problem
When the example script is run, the following exception is thrown

```
Traceback (most recent call last):
  File "test-2.py", line 5, in <module>
    print(gradients.jacobian(x, 5))
  File "/Users/asobolev/dev/tensorflow/pfor_test/venv/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/gradients.py", line 58, in jacobian
    pfor_outputs = control_flow_ops.pfor(loop_fn, output_size)
  File "/Users/asobolev/dev/tensorflow/pfor_test/venv/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 122, in pfor
    outputs.append(converter.convert(loop_fn_output))
  File "/Users/asobolev/dev/tensorflow/pfor_test/venv/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 1075, in convert
    output = self._convert_helper(y)
  File "/Users/asobolev/dev/tensorflow/pfor_test/venv/lib/python3.6/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 1108, in _convert_helper
    assert isinstance(y, ops.Tensor), y
AssertionError: None
```

This is due to the `tf.gradients(y, x)` (which sits under to hood of `jacobian`) returning `None` when `y` is independent of `x` in terms of computational graph, that is, when `y` is not achievable from `x` by any computation path, and `parallel_for` does not like working with `None`s.

This is not affecting me as I have found workarounds, but it's still a bug that needs fixing.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
CUDA/cuDNN version
GPU model and memory
Mobile device

**Comment by artsobolev** [comment]
Done
(originally removed them since the problem is reproducible on macOS)

**Comment by agarwal-ashish** [comment]
A fix has been submitted and should sync out soon. Thanks for reporting.
