### ISSUE TITLE
I got a keras_applications ModuleNotFoundError when I compile my tensorflow 1.10

### ISSUE THREAD

**Issue by KazuhiraDZ** [tensorflow/tensorflow#21723]
hi, I want compile my tensorflow 1.10 to update. But I got an error when I compile it:
ModuleNotFoundError: No module named 'keras_applications'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines failed build steps.
Anyone has the same error?

**Comment by hsgkim** [comment]
Solution in https://github.com/tensorflow/tensorflow/issues/21518#issuecomment-411875069
