### ISSUE TITLE
tflite-nnapi sometimes returns error result on same image.

### ISSUE THREAD

**Issue by jiarenyf** [tensorflow/tensorflow#21752]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu14.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: Xiaomi 8, OnePlus 5T, Oppo.
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0 / 7.1

### Describe the problem

I use tflite in android phone and it return right result. But when setting `tflite.useNNAPI(true)`, the result sometimes is error, while sometimes is right on the same images. See the source code below for details.

### Source code / logs

    private boolean NNAPI = true; # when set to `false` everything is ok, but when set to `true`, sometimes returns error result on the same images.

    private String getResult(final Bitmap bitmap) {
        tflite.setUseNNAPI(NNAPI );

        startTime = System.currentTimeMillis();

        int width = bitmap.getWidth();
        int height = bitmap.getHeight();
        float scale = (float)IMG_HEIGHT / height;
        int nWidth = (int) Math.floor(width * scale);
        int nHeight = (int) Math.floor(height * scale);
        int IMG_WIDTH =  (int) Math.ceil((float)nWidth/BLOCK)*BLOCK;

        Bitmap nBitmap = Bitmap.createScaledBitmap(bitmap, nWidth, nHeight, true);

        int intValues[] = new int[nWidth * nHeight];
        nBitmap.getPixels(intValues, 0, nWidth, 0, 0, nWidth, nHeight);

        ByteBuffer imgData = ByteBuffer.allocateDirect(IMG_WIDTH*IMG_HEIGHT);
        imgData.order(ByteOrder.nativeOrder());

        for (int i = 0; i < IMG_HEIGHT; ++i) {
            for (int k = 0; k < IMG_WIDTH; ++k) {
                if(i >= nHeight || k >= nWidth) {
                    imgData.put((byte)0);
                    continue;
                }

                int val = intValues[i*nWidth+k];
                int b = val & 0xFF;
                int g = (val >> 8) & 0xFF;
                int r = (val >> 16) & 0xFF;

                float gray = (float) (r * 0.30 + g * 0.59 + b * 0.11);
                imgData.put((byte) gray);
            }
        }

        endTime1 = System.currentTimeMillis();

        int MAX_LENGTH = IMG_WIDTH / BLOCK;
        int dims[] = { 1, IMG_HEIGHT, IMG_WIDTH, 1 };
        byte outputs[][] = new byte[MAX_LENGTH][KIND];

        tflite.resizeInput(0, dims);
        tflite.run(imgData, outputs);

        endTime2 = System.currentTimeMillis();

        int indices[] = new int[MAX_LENGTH];
        for(int i=0; i < MAX_LENGTH; ++i) {
            float prob = Byte.MIN_VALUE;
            int index = KIND-1;
            for (int k = 0; k < KIND; ++k) {
                if (outputs[i][k] > prob) {
                    index = k;
                    prob = outputs[i][k];
                }
            }
            indices[i] = index;
        }

        int blank = KIND - 1;
        StringBuilder sb = new StringBuilder();
        for(int i=0; i < MAX_LENGTH; ++i) {
            if(indices[i] == blank) { continue; }

            if(i==0 || indices[i] != indices[i-1]) {
                sb.append(CHARS[indices[i]]);
            }
        }

        endTime3 = System.currentTimeMillis();
        return sb.toString();
    }

**Comment by jiarenyf** [comment]
@suharshs Could you please take a look ?

**Comment by poxvoculi** [comment]
@aselle: Are you the right person to look at this?

**Comment by suharshs** [comment]
What is the error that occurs sometimes?

**Comment by jiarenyf** [comment]
@suharshs @aselle 

Actually I use tflite to perform cnn+ctc in android, and the greedy decoder is written in java while the cnn part is done by tflite. When `tflite.setUseNNAPI(false)` the features return by tflite (that is the line: `byte outputs[][] = new byte[MAX_LENGTH][KIND];`
`) can be decoded to the right prediction. However, when `tflite.setUseNNAPI(true)`, in the line `byte outputs[][] = new byte[MAX_LENGTH][KIND];` the values in the `outputs` sometimes changes, and the decoded result is error.

I wonder why the values return by line `byte outputs[][] = new byte[MAX_LENGTH][KIND];` which is done by tflite with NNAPI will sometimes return different results ?

Thanks.

**Comment by jiarenyf** [comment]
@jdduke 

I use XiaoMi 8, which is Android 8.1.

In fact, the model I use is CNN+CTC on the OCR task. But we need the input images to have variable widths, so each before feeding, I call `tflite.resize`.

If setting `tflite.setUseNNAPI(false)`, the result is always right.

However, **when setting `tflite.setUseNNAPI(true)`, if the width of the first image is larger than the second image, then the result of the second image is always wrong**. Then I set `tflite.setUseNNAPI(false)` and run the same (the second) image and set `tflite.setUseNNAPI(true)` and run again, the result is right.

**Comment by jdduke** [comment]
Thanks for the details, @jiarenyf.

Unfortunately, this is an existing (and undocumented) limitation of current NNAPI functionality. Once enabled, it does not properly handle resizes. This should be reported as an error (we'll fix that directly), though longer term we do plan on allowing dynamic resizes.

The best way to work around this at the moment is just as you mentioned; when you have to resize an input tensor, first disable NNAPI, then perform the resize, then re-enable NNAPI. This operation is non-trivial, however, so it should be done as infrequently as possible.

**Comment by jiarenyf** [comment]
@jdduke Thank you.
