### ISSUE TITLE
tf.placeholder changes random number sequence generated by a seed

### ISSUE THREAD

**Issue by pratham16** [tensorflow/tensorflow#21759]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow):**
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**
Debian Buster (Debian 10)
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:**
N/A
- **TensorFlow installed from (source or binary):**
N/A
- **TensorFlow version (use command below):**
1.8.0
- **Python version:**
2.7.14
- **Bazel version (if compiling from source):**
N/A
- **GCC/Compiler version (if compiling from source):**
7.3.0
- **CUDA/cuDNN version:**
N/A
- **GPU model and memory:**
N/A
- **Exact command to reproduce:**
N/A

Here's the code to test. Inserting a placeholder changes the sequence of `a` and `b`.
``` python
tf.set_random_seed(1234)
#c = tf.placeholder(dtype=tf.float32, shape=[10,10])
a = tf.random_uniform([1])
b = tf.random_normal([1])

print("Session 1")
with tf.Session() as sess1:
  print(sess1.run(a))  # generates 'A1'
  print(sess1.run(a))  # generates 'A2'
  print(sess1.run(b))  # generates 'B1'
  print(sess1.run(b))  # generates 'B2'

print("Session 2")
with tf.Session() as sess2:
  print(sess2.run(a))  # generates 'A1'
  print(sess2.run(a))  # generates 'A2'
  print(sess2.run(b))  # generates 'B1'
  print(sess2.run(b))  # generates 'B2'
```
Few Observations - 
1. I tried adding the line `c = tf.placeholder(dtype=tf.float32, shape=[10,10])` before and after `tf.set_random_seed(1234)`. The issue persists.
2. Insertion of placeholder does not affect the outcome when op level seed is set.

Does the placeholder affect the sequence in which random numbers are generated by graph level seed?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by pratham16** [comment]
The issue template is updated now.

**Comment by facaiy** [comment]
duplication of #14675.

**Comment by rohan100jain** [comment]
Closing issue as its a duplicate.
