### ISSUE TITLE
Libtensorflow bazel build link error LNK2019 on debug mode on Windows 

### ISSUE THREAD

**Issue by AnnieYim** [tensorflow/tensorflow#21758]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
     Yes, made change of bazel command in
     tensorflow\tensorflow\tools\ci_build\windows\libtensorflow_cpu.sh
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
     Windows 10 64bit 
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
      N/A
- **TensorFlow installed from (source or binary)**:
     source
- **TensorFlow version (use command below)**:
     Tensorflow version 1.10
- **Python version**:
     Python 3.5
- **Bazel version (if compiling from source)**:
     Bazel 0.15.2
- **GCC/Compiler version (if compiling from source)**:
     VS2015(Microsoft Visual Studio 14.0\VC)
- **CUDA/cuDNN version**:
     N/A
- **GPU model and memory**:
     N/A
- **Exact command to reproduce**:
     Code path: tensorflow\tensorflow\tools\ci_build\windows\libtensorflow_cpu.sh
     Bazel command(my code change): 
     bazel --output_user_root=${TMPDIR} build --distinct_host_configuration=false -c **dbg** -- 
     copt=/arch:AVX -s --strip=never --verbose_failures tensorflow:libtensorflow.so 
     tensorflow/tools/lib_package:clicenses_generate 
### Describe the problem
I want to **build libtensorflow on debug mode with bazel on Windows**, and change the corresponding  bazel command from '-c opt' to '-c dbg', but when build process 'action Linking tensorflow:libtensorflow.so', encountered the following link error:
depth_space_ops.lo.lib(spacetodepth_op.obj) : error LNK2019: unresolved external symbol
depth_space_ops.lo.lib(depthtospace_op.obj) : error LNK2019: unresolved external symbol 

### Source code / logs
Here comes the specific error log:
[libtensorflow_dbg_error_log.txt](https://github.com/tensorflow/tensorflow/files/2305961/libtensorflow_dbg_error_log.txt)

ERROR: D:/tensorflow/libtensorflow/tensorflow/tensorflow/BUILD:520:1: Linking of rule '//tensorflow:libtensorflow.so' failed (Exit 1120): link.exe failed: error executing command
  cd C:/tmp/k6dssnhw/execroot/org_tensorflow
C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/link.exe /nologo /DLL /SUBSYSTEM:CONSOLE -DEFAULTLIB:advapi32.lib /MACHINE:X64 /DEBUG:FULL @bazel-out/x64_windows-dbg/bin/tensorflow/libtensorflow.so-2.params /DEBUG:FULL /INCREMENTAL:NO
depth_space_ops.lo.lib(spacetodepth_op.obj) : error LNK2019: unresolved external symbol "public: void __cdecl tensorflow::functor::SpaceToDepthOpFunctor<struct Eigen::GpuDevice,int,1>::operator()(struct Eigen::GpuDevice const &,class Eigen::TensorMap<class Eigen::Tensor<int const ,4,1,__int64>,16,struct Eigen::MakePointer>,int,class Eigen::TensorMap<class Eigen::Tensor<int,4,1,__int64>,16,struct Eigen::MakePointer>)" (??R?$SpaceToDepthOpFunctor@UGpuDevice@Eigen@@H$00@functor@tensorflow@@QEAAXAEBUGpuDevice@Eigen@@V?$TensorMap@V?$Tensor@$$CBH$03$00_J@Eigen@@$0BA@UMakePointer@2@@4@HV?$TensorMap@V?$Tensor@H$03$00_J@Eigen@@$0BA@UMakePointer@2@@4@@Z) referenced in function "public: virtual void __cdecl tensorflow::SpaceToDepthOp<struct Eigen::ThreadPoolDevice,signed char>::Compute(class tensorflow::OpKernelContext *)" (?Compute@?$SpaceToDepthOp@UThreadPoolDevice@Eigen@@C@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
depth_space_ops.lo.lib(depthtospace_op.obj) : error LNK2019: unresolved external symbol "public: void __cdecl tensorflow::functor::DepthToSpaceOpFunctor<struct Eigen::GpuDevice,int,1>::operator()(struct Eigen::GpuDevice const &,class Eigen::TensorMap<class Eigen::Tensor<int const ,4,1,__int64>,16,struct Eigen::MakePointer>,int,class Eigen::TensorMap<class Eigen::Tensor<int,4,1,__int64>,16,struct Eigen::MakePointer>)" (??R?$DepthToSpaceOpFunctor@UGpuDevice@Eigen@@H$00@functor@tensorflow@@QEAAXAEBUGpuDevice@Eigen@@V?$TensorMap@V?$Tensor@$$CBH$03$00_J@Eigen@@$0BA@UMakePointer@2@@4@HV?$TensorMap@V?$Tensor@H$03$00_J@Eigen@@$0BA@UMakePointer@2@@4@@Z) referenced in function "public: virtual void __cdecl tensorflow::DepthToSpaceOp<struct Eigen::ThreadPoolDevice,signed char>::Compute(class tensorflow::OpKernelContext *)" (?Compute@?$DepthToSpaceOp@UThreadPoolDevice@Eigen@@C@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
bazel-out/x64_windows-dbg/bin/tensorflow/libtensorflow.so : fatal error LNK1120: 32 unresolved externals
INFO: Elapsed time: 1609.057s, Critical Path: 741.15s

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Mobile device

**Comment by AnnieYim** [comment]
I have updated the issue following the template.

**Comment by bignamehyp** [comment]
Similar to issue #17647.

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by AnnieYim** [comment]
I have not investigated this issue further, thanks!
