### ISSUE TITLE
"not all arguments converted during string formatting" in rnn_cell_impl

### ISSUE THREAD

**Issue by melkonyan** [tensorflow/tensorflow#21762]
I believe there's a mistake in the ```BasicLSTMCell.build``` method:

```python
raise ValueError("Expected inputs.shape[-1] to be known, saw shape: %s"
                       % inputs_shape)
```
will be called with inputs_shape being a tuple and % formatting will interpret this tuple as multiple formatting arguments. Can we change it to

```python
raise ValueError("Expected inputs.shape[-1] to be known, saw shape: %s"
                       % (inputs_shape,))
```
?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by yongtang** [comment]
@melkonyan Would you mind to create a PR for the proposed fix?

**Comment by tatianashp** [comment]
@melkonyan Your contribution would be very welcome.

**Comment by melkonyan** [comment]
Ok, I'll create a PR
