### ISSUE TITLE
setting allocated memory of gpu

### ISSUE THREAD

**Issue by mrphoenix13** [tensorflow/tensorflow#2176]
By using options like `gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)` , it gives  the process this fraction of **free** gpu's memory. it means when you want to give a process an exact value of memory you must change the fractions due to running sequence of processes. For example if you want to run 2 process simultaneously with half of the memory you have to run the first one with 0.5 fraction and the second one with 1.0 fraction.
Is there any way to allocate an exact  size for each process (for example 2gb)?

**Comment by zheng-xq** [comment]
The current logic is implemented as a fraction of the remaining free memory. 

Adding @vrv to decide whether it is okay to switch to a fraction of total memory. 

You are also welcome to make a contribution. The logic is here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/gpu/gpu_device.cc#L599

**Comment by vrv** [comment]
Seems fine to switch to fraction of total memory.  Please send a PR!

**Comment by mrphoenix13** [comment]
thanks @vrv. The related PR has been sent.
