### ISSUE TITLE
bazel run error

### ISSUE THREAD

**Issue by mikeconnors909** [tensorflow/tensorflow#218]
I am trying to run the code from this tutorial: http://tensorflow.org/tutorials/seq2seq/index.md

When I try to run this command:

`bazel run -c opt tensorflow/models/rnn/translate/translate.py -- -- data_dir ../data/translate/`
I get the following error:

```
...................
ERROR: Cannot run target //tensorflow/models/rnn/translate:translate.py: Not   executable.
INFO: Elapsed time: 1.537s
ERROR: Build failed. Not running target.
```
Any ideas how to resolve?

**Comment by vrv** [comment]
`bazel run -c opt tensorflow/models/rnn/translate:translate`

in bazel you have to build / run the target as defined in the BUILD file, rather than the source file.

**Comment by mikeconnors909** [comment]
Maybe update the tutorial with the right command then?

**Comment by vrv** [comment]
Good call -- sent out the fix internally and we'll push the change out soon.  Thanks!

**Comment by mikeconnors909** [comment]
Great thanks!
