### ISSUE TITLE
SparseTensor   transpose

### ISSUE THREAD

**Issue by nationalflag** [tensorflow/tensorflow#2180]
Is  there a way to transpose a SparseTensor without converting it to dense?

**Comment by mrry** [comment]
There's no built-in op for doing this, but you could do something like the following:

```python
input_st = ...  # object of type `tf.SparseTensor`, with 2-D indices

indices = input_st.indices
# Reverse the columns of `indices`
transposed_indices = tf.concat(1, [indices[:, 1:2], indices[:, 0:1]])

dense_shape = input_st.dense_shape
# Reverse the elements of `dense_shape`
transposed_dense_shape = tf.pack([dense_shape[1], dense_shape[0]])

transposed_st = tf.SparseTensor(transposed_indices, input_st.values, transposed_dense_shape)
```

**Comment by mrry** [comment]
(Assigning this to @concretevitamin, since he is looking at the sparse ops right now.)

**Comment by ebrevdo** [comment]
Don't forget to call Reorder Sparse on the result of Derek's code.

**Comment by girving** [comment]
@concretevitamin: Are you planning to work on this?  If not, we should mark it as contributions welcome.

@mrry: `tf.reverse` is a better way to reverse a Tensor that extracting each component and manually reassembling them in the opposite order.

**Comment by concretevitamin** [comment]
I see Eugene has marked it as contributions welcome.  I am happy to review any PRs!

**Comment by maniteja123** [comment]
Hi, I would like working on this. Please let me know if it would be fine to proceed. Thanks.

**Comment by concretevitamin** [comment]
@maniteja123 please feel free to take it.  Besides all of the above suggestions, I'd imagine adding an additional bool flag (`reorder`?) to the Python function can be useful, with default to True.

**Comment by maniteja123** [comment]
Thanks for the response. Could you please clarify some questions ? Would adding a wrapper suffice ? I was thinking ``sparse_ops.py`` where similar functions are there ? Or should it be added to the core code ?

Also the implementation AFAICU would be something like 

```
transposed_indices  = tf.reverse(sp_input.indices), [False, True])
transposed_values = sp_input.values
transposed_shape = tf.reverse(sp_input.shape), [True])
sp_output = tf.SparseTensor(transosed_indices, transposed_values, transposed_shape)
sp_output = tf.sparse_reorder(sp_output)
```

Please let me know if this is  the right approach here ? Thanks.

**Comment by concretevitamin** [comment]
AFAICT, adding a wrapper function to sparse_ops.py sounds good.

**Comment by maniteja123** [comment]
Thank you. Will try working on it and send a PR as soon as possible.

**Comment by maniteja123** [comment]
Hi @concretevitamin , sorry for the delay. I have tried adding a wrapper to the function in ``sparse_ops.py``. What is the general procedure to register it in case it is only a python op and doesn't have a corresponding kernel op ? I couldn't find something similar done before. Could you please help me here ? Thanks and sorry for many questions. It is my first attempt to contribute here.

**Comment by concretevitamin** [comment]
In case of a Python wrapper function, it really is not an Op, but just an ordinary Python function that introduces Ops to the graph by composing other Op wrappers.

In other words, there's no need to register anything (gradient function, shape function, kernel) in this case.

There are many PRs that does exactly this for Issues #1968 and #1828.   Could you take a look at those?

**Comment by maniteja123** [comment]
Thnaks for the response. I did follow those PRs. If I understand it correctly, I just add the wrapper function and build again. This should show the function in the ``tf`` namespace ? Right now, I am using the instructions [here](https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#installing-from-sources) and using ``python setup.py develop``. Please do let me know if I am doing it correctly ? Thanks.

**Comment by concretevitamin** [comment]
The instructions should work.  To explicitly expose the documentation,
you'll need to add `@@sparse_transpose()` near the top of the file.  Are
you seeing some errors?  It'd be better if we are talking about concrete
issues.

**Comment by maniteja123** [comment]
Apologies for the trivial doubts. I did add ``@@sparse_transpose`` to top of the file but was getting the following error in the bazel build. I was using the current master to build it.

```
ERROR: /root/FOSS/tensorflow/tensorflow/contrib/session_bundle/example/BUILD:38:1:
 Executing genrule //tensorflow/contrib/session_bundle/example:half_plus_two faile
d: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s)
skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exit
ed with status 1.
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/5b738bf9edce520d5df62c48e6337528/tensorflow
/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two
.runfiles/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plu
s_two.py", line 115, in <module>
    tf.app.run()
  File "/root/FOSS/tensorflow/_python_build/tensorflow/python/platform/app.py", li
ne 30, in run
    sys.exit(main(sys.argv))
  File "/root/.cache/bazel/_bazel_root/5b738bf9edce520d5df62c48e6337528/tensorflow
/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two
.runfiles/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plu
s_two.py", line 111, in main
    Export()
  File "/root/.cache/bazel/_bazel_root/5b738bf9edce520d5df62c48e6337528/tensorflow
/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two
.runfiles/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plu
s_two.py", line 106, in Export
    assets_callback=CopyAssets)
  File "/root/FOSS/tensorflow/_python_build/tensorflow/contrib/session_bundle/expo
rter.py", line 200, in init
    graph_any_buf.Pack(copy)
AttributeError: 'Any' object has no attribute 'Pack'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

Sorry if I am missing something trivial but I couldn't find any issue related to this. Thanks.

**Comment by maniteja123** [comment]
Sorry I got that solved by updating protobuf.

**Comment by maniteja123** [comment]
Hi, I have tried to use the following implementation for transpose as suggested above

```
transposed_indices  = tf.reverse(sp_input.indices), [False, True])
transposed_values = sp_input.values
transposed_shape = tf.reverse(sp_input.shape), [True])
sp_output = tf.SparseTensor(transosed_indices, transposed_values, transposed_shape)
sp_output = tf.sparse_reorder(sp_output)
```

But it seems that ``tf.reverse`` doesn't support ``int64`` and raises an error

```
 File "<stdin>", line 1, in <module>
  File "tensorflow/python/ops/gen_array_ops.py", line 1598, in reverse
  File "tensorflow/python/framework/op_def_library.py", line 529, in apply_op
  File "tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesType
Constraint
TypeError: DataType int64 for attr 'T' not in list of allowed values: uint8, int8,
 int32, bool, float16, float32, float64
```

Is there any workaround for this ? Since this is used only for ``indices`` and ``shape`` would it be okay to downcast to ``int32`` ? Thanks.

**Comment by maniteja123** [comment]
Hi, I have opened a PR at #3031. Please do have a look and give your suggestions. Thanks.
