### ISSUE TITLE
Custom tensorflow op with output shape determined by the input tensor

### ISSUE THREAD

**Issue by mzgsxs** [tensorflow/tensorflow#21800]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: YES
- Linux Ubuntu 16.04
- PC
- Binary
- 1.10
- 3.5
- 9.0/7.0
- V100 
- **Exact command to reproduce**:
```
REGISTER_OP("GroupPoint")
    .Input("points: float32")
    .Input("idx: int32")
    .Input("length: int32")
    .Output("out: float32")
    .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
        ::tensorflow::shape_inference::ShapeHandle dims1; **// shape N x C**
        c->WithRank(c->input(0), 2, &dims1);
        ::tensorflow::shape_inference::ShapeHandle dims2; **// shape L**
        c->WithRank(c->input(1), 1, &dims2);
        ::tensorflow::shape_inference::ShapeHandle dims3; **// scalar, shape 0**
        c->WithRank(c->input(2), 0, &dims3);
        ::tensorflow::shape_inference::ShapeHandle output = c->MakeShape({c->Dim(dims2, 2), L});
        **// L should have the value of input(2)**
        c->set_output(0, output); **// shape input(2) x C**
        return Status::OK();
    });
```

### Describe the problem
Basically I want to write a customized op to output a tensor with shape which is determined by the value of input(2), i.e the third input. 
More specifically, I want to get 'length' number of 'idx' (i.e. idx[0:length] ) then to gather those indices from 'points'. ( i.e. tf.gather(points, idx[0:length]))
The stock tensor-flow apis such as tf.slice and tf.gather would not allow me to do this because my op (also an customised op) to get input 'idx' has to be run on GPU. Error Message as:

**Tensor("strided_slice:0", shape=(128, 16), dtype=float32, device=/device:GPU:0)
Tensor("strided_slice_1:0", shape=(32,), dtype=int32, device=/device:GPU:0) Tensor("strided_slice_2:0", shape=(), dtype=i
nt32, device=/device:GPU:0)
2018-08-22 13:28:55.108318: E tensorflow/core/common_runtime/executor.cc:696] Executor failed to create kernel. Not found
: No registered 'QueryBallPoint' OpKernel for CPU devices compatible with node QueryBallPoint = QueryBallPoint[nsample=32
, radius=1, _device="/device:GPU:0"](Const_1, Const_2)
        .  Registered:  device='GPU'
[[Node: QueryBallPoint = QueryBallPoint[nsample=32, radius=1, _device="/device:GPU:0"](Const_1, Const_2)]]
Tensor("GatherV2:0", shape=(?,), dtype=int32, device=/device:GPU:0)**

I have tried to digging from the source code of class ::tensorflow::shape_inference::InferenceContext*, but failed, I have no idea how to do this, any kind of suggestions would be greatly helpful, thanks

**Comment by asimshankar** [comment]
The shape functions run during graph construction, not execution - as a means to catch shape errors as early as possible. The value of input tensors is not available (because it hasn't been computed), and thus the shape functions cannot always infer a fully-specified shape.

You'll see this for example in [ops like `Unique`](https://github.com/tensorflow/tensorflow/blob/abd64d680b9afa37e8c0a7ce5504c1f7c1a81fbc/tensorflow/core/ops/array_ops.cc#L1362), where the operation would have to be computed in order to get the fully-specified shape.

If I understand your operation correctly, you'd have to do something like:

```c++
output = c->MakeShape({c->Dim(dims2, 2), InferenceContext::kUnknownDim});
```

Hope that helps.

**Comment by mzgsxs** [comment]
Thank you so much for the help asimshankar, I've change my code based on your suggestion. (btw I've made a mistake in my question, it should be **c->MakeShape({L, c->Dim(dims1, 2)})** instead of original line **c->MakeShape({c->Dim(dims2, 2), L})** )

Now my code looks like this:
::tensorflow::shape_inference::ShapeHandle output = c->MakeShape({c->kUnknownDim, c->Dim(dims1, 2)});

Another error occured:
**Tensor("strided_slice_1:0", shape=(32,), dtype=int32, device=/device:GPU:0) Tensor("strided_slice_2:0", shape=(), dtype=int32, device=/device:GPU:0)
2018-08-23 06:58:18.876048: F /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/shape_inference.h:803] Check failed: dim.IsSet() Internal error: Got nullptr for Dimension.
Aborted (core dumped)**

My guess is maybe because this is an GPU op?

**Comment by mzgsxs** [comment]
UPDATE:
c->set_output(0, c->Matrix(c->UnknownDim(), c->UnknownDim()));
this actually worked but with out put tensor dimension as:
Tensor("GroupPoint:0", shape=(?, ?), dtype=float32, device=/device:GPU:0)
which is not optimal

**Comment by mzgsxs** [comment]
@asimshankar thanks for reply, I have tried this method, but I have no idea why it's not working.
Here is my coplete code:

**op.cpp**

REGISTER_OP("GroupPoint")
    .Input("points: float32") // N x C
    .Input("idx: int32") // M
    .Input("length: int32") // L
    .Output("out: float32") // L x C
    .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
        ::tensorflow::shape_inference::ShapeHandle dims1; 
        c->WithRank(c->input(0), 2, &dims1);
        //::tensorflow::shape_inference::ShapeHandle output = c->MakeShape(c->kUnknownDim);
        //c->set_output(0, output);
        c->set_output(0, c->Matrix(c->UnknownDim(), c->Dim(dims1, 2)));
        return Status::OK();
    });
void groupPointLauncher(int n, int l, int c, int nsample, const float *points, const int *idx, float *out);
class GroupPointGpuOp: public OpKernel{
    public:
        explicit GroupPointGpuOp(OpKernelConstruction * context):OpKernel(context){}

        void Compute(OpKernelContext * context) override {
            const Tensor& points_tensor=context->input(0);
            OP_REQUIRES(context, points_tensor.dims()==2, errors::InvalidArgument("GroupPoint expects (num_points, channel) points shape"));
            int n = points_tensor.shape().dim_size(0);
            int c = points_tensor.shape().dim_size(1);

            const Tensor& idx_tensor=context->input(1);
            OP_REQUIRES(context,idx_tensor.dims()==1, errors::InvalidArgument("GroupPoint expects (nsample) idx shape"));
            int nsample = idx_tensor.shape().dim_size(0);

            const Tensor& length_tensor=context->input(2);
            auto length_flat = length_tensor.flat<int>();
            const int *length = &(length_flat(0));
            int l = length[0];
            printf("%d",l);

            Tensor * out_tensor = nullptr;
            OP_REQUIRES_OK(context, context->allocate_output(0,TensorShape{l,c}, &out_tensor));

            auto points_flat = points_tensor.flat<float>();
            const float *points = &(points_flat(0));
            auto idx_flat = idx_tensor.flat<int>();
            const int *idx = &(idx_flat(0));
            auto out_flat = out_tensor->flat<float>();
            float *out = &(out_flat(0));
            //printf("GroupPointGpuOp Start \n");
            groupPointLauncher(n,l,c,nsample,points,idx,out);
            //printf("GroupPointGpuOp Pass \n");
        }
};
REGISTER_KERNEL_BUILDER(Name("GroupPoint").Device(DEVICE_GPU).HostMemory("out"),GroupPointGpuOp);

**With op.cn**
// input: points (n,c), idx (nsample)
// output: out (nsample,c)
__global__ void group_point_gpu(int n, int l, int c, int nsample, const float *points, const int *idx, float *out) {
    int s_idx = blockIdx.x;
    // get single batch 
    idx += s_idx;
    out += s_idx*c;

    int index = threadIdx.x;
    int stride = blockDim.x;

    //// shared memory for points
    //__shared__ const float temp[n*c];
    //// fetch per block data into shared memory
    //for (int i=0;i<n*c;i++){
    //    temp[i] = points[i] 
    //}
    //// make sure data has been getched
    //__syncthreads();

    int ii = idx[0];
    for (int i=index;i<c;i+=stride) {
        out[i] = points[ii*c+i];
    }
}
void groupPointLauncher(int n, int l, int c, int nsample, const float *points, const int *idx, float *out){
    group_point_gpu<<<l,512>>>(n,l,c,nsample,points,idx,out);
}

**Compile command:**
#/bin/bash
/usr/local/cuda-9.0/bin/nvcc op.cu -o op.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC

# TF1.2
#g++ -std=c++11 tf_grouping.cpp tf_grouping_g.cu.o -o tf_grouping_so.so -shared -fPIC -I /usr/local/lib/python2.7/dist-packages/tensorflow/include -I /usr/local/cuda-8.0/include -lcudart -L /usr/local/cuda-8.0/lib64/ -O2 -D_GLIBCXX_USE_CXX11_ABI=0

# TF>1.4
g++ -std=c++11 op.cpp op.cu.o -o op_so.so -shared -fPIC -I /usr/local/lib/python3.5/dist-packages/tensorflow/include -I /usr/local/cuda-9.0/include -I /usr/local/lib/python3.5/dist-packages/tensorflow/include/external/nsync/public -lcudart -L /usr/local/cuda-9.0/lib64/ -L/usr/local/lib/python3.5/dist-packages/tensorflow -ltensorflow_framework -O2 -D_GLIBCXX_USE_CXX11_ABI=0
~                                             

**Python example, op.py**
import tensorflow as tf
from tensorflow.python.framework import ops
import sys
import os
import numpy as np

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(BASE_DIR)
grouping_module=tf.load_op_library(os.path.join(BASE_DIR, 'op_so.so'))

def group_point(points, idx, length):
    '''
    Input:
        points: (batch_size, ndataset, channel) float32 array, points to sample from
        idx: (batch_size, npoint, nsample) int32 array, indices to points
    Output:
        out: (batch_size, npoint, nsample, channel) float32 array, values sampled from points
    '''
    return grouping_module.group_point(points, idx, length)
@tf.RegisterGradient('GroupPoint')

if __name__=='__main__':
#  tf.test.main() 
  with tf.device('/gpu:0'):
    n = 128
    c = 16
    nsample = 32
    points = tf.constant(np.random.random((n,c)).astype('float32'))
    idx = tf.constant(np.random.randint(0,n,(nsample)).astype('int32'))
    length = tf.constant(np.random.randint(0,n,(1)).astype("int32"))
    print(points, idx, length)
    local_feature = group_point(points, idx, length)
    print(local_feature)

**Comment by mzgsxs** [comment]
Thanks for the help, @asimshankar
https://github.com/tensorflow/tensorflow/blob/5306e10929e8b5aa05c49d32d4a147ca9786ddfa/tensorflow/core/framework/shape_inference.h#L459
I think it might due to this 
  ShapeHandle MakeShape(const std::vector<DimensionHandle>& dims);
  ShapeHandle MakeShape(std::initializer_list<DimensionOrConstant> dims);

which in my case, shape1 c->kUnknownDim is a DimensionOrConstant or int64 obj, which shape2 c->Dim(dims1, 2) is a DimensionHandle obj. thus the error.
that's my guess tho, is there any way to avoid this?

**Comment by marsupialtail** [comment]
Would anybody happen to know how to do this for the python interface of adding a custom op?
