### ISSUE TITLE
Please provide cmake-based build files

### ISSUE THREAD

**Issue by yurivict** [tensorflow/tensorflow#21815]
Currently tensorflow fails to build due to this problem: https://github.com/bazelbuild/bazel/issues/5763
Bazel project doesn't appear to be willing to fix the problem.

Could you please provide cmake-based build? cmake is known to work much better than bazel, and many projects are using it without problems.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by yurivict** [comment]
OS: FreeBSD 11.2
Installed from: GitHub
bazel-0.15.0
No CUDA.

**Comment by asimshankar** [comment]
Unfortunately, the TensorFlow maintainers don't have the resources to maintain multiple build systems or more operating systems at this time and we rely on community support for CMake.

See [this thread](https://groups.google.com/a/tensorflow.org/d/msg/build/9vKi3ceP2ZI/fQxWQFHsDgAJ) and FreeBSD related issues [like this](https://github.com/tensorflow/tensorflow/issues/20421#issuecomment-401449378).

Thanks for your understanding.

(CC @ewilderj @jakline @gunan )
