### ISSUE TITLE
TensorBoard build failure on Jenkins

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorflow#2186]
TensorBoard build has failed for quite a while in Jenkins now. The failure seems to have to do with gulp config, for example:

> [16:46:28] Using gulpfile /workspace/tensorflow/tensorboard/gulpfile.js
> [16:46:28] Task 'compile.all' is not in your gulpfile
> [16:46:28] Please check the documentation for proper gulpfile formatting

For full build log, see example: http://ci.tensorflow.org/job/tensorflow-master-tensorboard/161/console

### Environment info
Operating System: Linux + Docker

Installed version of CUDA and cuDNN: Not applicable.
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide: N/A

To reproduce locally:
`tensorflow/tools/ci_build/ci_build.sh TENSORBOARD tensorflow/tools/ci_build/builds/tensorboard.sh
`

**Comment by caisq** [comment]
@danmane Can you take a look?

**Comment by danmane** [comment]
Ah, I know what the problem is. Will fix.

**Comment by caisq** [comment]
@danmane Gentle ping. Any ETA to fix?

**Comment by girving** [comment]
@danmane says he's still working on the fix.

**Comment by danmane** [comment]
I believe this was fixed.
