### ISSUE TITLE
tensorflow 1.10.1 requires numpy 1.14.5?

### ISSUE THREAD

**Issue by beew** [tensorflow/tensorflow#21866]
I have successfully built tensorflow  1.10.1 from source but when  I installed the whl with pip3 it downloaded and installed numpy-1.14.5 and removed numpy-1.15.1. 

After tensorflow was installed I manually uninstalled numpy-1.14.5 and reinstalled numpy-1.15.1, pip gave a warning that tensorflow-1.10.1 requires numpy <= 1.14.5 but went ahead anyway. Afterwards I ran some tests on tensorflow and it works just fine with numpy 1.15.1 so this requirement appears to be unnecessary. **Edited:** there is no complaint about incompatibility with numpy-1.15.1 for tensorflow-1.9

Is there a file I can edit to get rid of this requirement? I am ok with compiling again.

OS Ubuntu 16.04.5 LTS 64 bits , python3.5 (cuda-9.2)

**Comment by facaiy** [comment]
@av8ramit The restriction seems introduced in f9410ac2, could you explain why we need it?

@beew I think you can modify the line below and take a try, good luck:

https://github.com/tensorflow/tensorflow/blob/90209afabc187da3ef7157352eea3b901c84e03d/tensorflow/tools/pip_package/setup.py#L56

**Comment by facaiy** [comment]
Link to #21700

**Comment by av8ramit** [comment]
I've removed the restriction in https://github.com/tensorflow/tensorflow/commit/6729cd7d1c07e547298fa2a02d1e36390dc62f0a#diff-5228adef057db60d6aa080e4074ab93c and 1.11 should support the latest numpy. cc: @angersson

**Comment by facaiy** [comment]
@av8ramit Good news! Could you close all those related issue?

**Comment by av8ramit** [comment]
I believe I did, did I miss any?
