### ISSUE TITLE
Windows docker documentation

### ISSUE THREAD

**Issue by chuhanuman** [tensorflow/tensorflow#21874]
### System information
- Win 10
- Latest version of docker
- docker run -p 8888:8888 --name tensorflow-udacity -it gcr.io/tensorflow/udacity-assignments:1.0.0

### Describe the problem
At https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/udacity. It does not say what command to use for windows.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by gunan** [comment]
We do not have docker images/containers for windows.
That's why they are not there.

That may be an interesting community contribution though.

**Comment by shafi-dayatar** [comment]
I can take a look at this!

**Comment by shafi-dayatar** [comment]
@chuhanuman, 
Could you please mention your Windows edition. Docker has different implementation for Windows Home and (Pro, enterprise, and education) edition.

**Comment by shafi-dayatar** [comment]
Have updated the document and mentioned the command for Windows. Have submitted PR 22944 for it.

**Comment by shafi-dayatar** [comment]
This issue has been resolved.
