### ISSUE TITLE
Missing support for Ubuntu 16.04 with Python 3.5

### ISSUE THREAD

**Issue by fcole90** [tensorflow/tensorflow#2188]
### Environment info
Operating System:
Ubuntu 16.04 Xenial Xerus

Installed version of CUDA and cuDNN: 
none (using CPU version)

If installed from binary pip package, provide:

https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl

### What have you tried?
I tried to install

```
https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl
```

but it failed with the following message:

```
tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl is not a supported wheel on this platform.
```

This is probably because the python3 version in Xenial is Python 3.5.x

I managed to install tensorflow using instead:

```
linux/cpu/tensorflow-0.7.0-py3-none-linux_x86_64.whl
```

but there's not anything like that neither for the protobuf nor for the tensorflow-0.8.0 packages.

**Comment by pyephyomaung** [comment]
+1

**Comment by zjj2008se** [comment]
i have download it and rename to tensorflow-0.8.0-cp35-cp35m-linux_x86_64.whl to install it

**Comment by girving** [comment]
@caisq: Can you take a look as someone more familiar with pip-land?

**Comment by crunchiness** [comment]
+1

**Comment by caisq** [comment]
We are in the process of getting python3.5 build to work for linux. Stay tuned. Renaming is the temporary solution.

**Comment by Spacefish** [comment]
+1

**Comment by caisq** [comment]
With PR #2585, we now have Linux Python 3.5 whl files built and tested nightly. The links to the whl files and build history can be found in the main README.md: 
https://github.com/tensorflow/tensorflow/

Linux Python 3.5 whl files will also be included in future releases.
