### ISSUE TITLE
ImportError:No module named setuptools after exectued the step for bazel-bin

### ISSUE THREAD

**Issue by xinshouke** [tensorflow/tensorflow#219]
I setup tensorflow according to http://tensorflow.org/tutorials/seq2seq/index.md. When I do the step as below:
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg,but the below error was throw:
Sat XXXXXXXXXXXXX CST 2015: ===Building wheel
Traceback(most recent call last):
  File “setup.py”,line 3,in <module>
    from setuptools import find_packages,setup,Extension
ImportError:No module named setuptools
BTW, I had no do the step for (Optional) Enable GPU Support

**Comment by ebrevdo** [comment]
Are you able to install the binary wheel via the getting started guide,
without going through the pip build process?

**Comment by keveman** [comment]
You need [python setuptools](https://pypi.python.org/pypi/setuptools) installed. Either `sudo apt-get install python-setuptools` or `sudo pip install setuptools` should install that on a Ubuntu machine.

**Comment by vrv** [comment]
Let us know if that isn't sufficient.  Thanks!

**Comment by xinshouke** [comment]
After I execute the command 'sudo apt-get install python-setuptools', I get the blow error:
error: invalid command 'bdist_wheel'. Would you like indicate me once again please?
As you known, we couldn't use installer from google site for many years... So I had to use source build.

**Comment by xinshouke** [comment]
@vrv it worked as the above suggesion. What's more I apt-get install python-pip,the step was executed successfully
