### ISSUE TITLE
Error: Can not allocate memory for the given inputs: external/tensorflow/tensorflow/contrib/lite/kernels/sub.cc:48 NumDimensions(input1) != NumDimensions(input2) (4 != 0)

### ISSUE THREAD

**Issue by seayqrain** [tensorflow/tensorflow#21919]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
I only replace the model we retained refer to tensorflow-for-poets.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 14.04.3 LTS
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
LG G4
- **TensorFlow installed from (source or binary):binary
- **TensorFlow version (use command below):1.7.1
- **Python version:2.7.6
- **Bazel version (if compiling from source): NA
- **GCC/Compiler version (if compiling from source): NA
- **CUDA/cuDNN version: NA
- **GPU model and memory: NA
- **Exact command to reproduce:

### Describe the problem
Hi,
I retrained a model refer to tensorflow-for-poets, the retrain command is:

> python -m scripts.retrain \
  --bottleneck_dir=tf_files/bottlenecks \
  --model_dir=tf_files/models/ \
  --summaries_dir=tf_files/training_summaries/mobilenet_v2_140_224 \
  --output_graph=tf_files/retrained_graph.pb \
  --output_labels=tf_files/retrained_labels.txt \
  --tfhub_module=https://tfhub.dev/google/imagenet/mobilenet_v2_140_224/feature_vector/2 \
  --how_many_training_steps=8000 \
  --learning_rate=0.005 \
  --flip_left_right True \
  --random_crop=10 \
  --random_scale=10 \
  --random_brightness=10 \
  --image_dir=tf_files/tf_Images

retrained_graph.pb works fine in our Android APP.
Then I converted ".pb" to ".lite" with this command:

> toco \
  --input_file=tf_files/retrained_graph.pb \
  --output_file=tf_files/retrained_graph.lite \
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --input_shape=1,224,224,3 \
  --input_array=Placeholder \
  --output_array=final_result \
  --inference_type=FLOAT \
  --input_data_type=FLOAT

But retrained_graph.lite **can not** work in our Android APP(refer to tensorflow-for-poets-2\android\tflite), the error is:

> 08-23 18:15:33.202  2457  2475 E AndroidRuntime: java.lang.NullPointerException: Can not allocate memory for the given inputs: external/tensorflow/tensorflow/contrib/lite/kernels/sub.cc:48 NumDimensions(input1) != NumDimensions(input2) (4 != 0)
08-23 18:15:33.202  2457  2475 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
08-23 18:15:33.202  2457  2475 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:95)
08-23 18:15:33.202  2457  2475 E AndroidRuntime: 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:113)
08-23 18:15:33.202  2457  2475 E AndroidRuntime: 	at org.tensorflow.lite.Interpreter.run(Interpreter.java:94)

**Please help to analyze that why this error occurs? Thanks!**

**Comment by mikemaksymowych** [comment]
having the same issue; what was the solution?
