### ISSUE TITLE
Row distances Tensorflow for models like K-Means, SOM and RBFN

### ISSUE THREAD

**Issue by RobRomijnders** [tensorflow/tensorflow#2192]
I am wondering if Tensorflow has some op for fast calculation of distances. For example like Matlab's [pdist](http://nl.mathworks.com/help/stats/pdist.html) or [pdist2](http://nl.mathworks.com/help/stats/pdist2.html)

Or do you know of any way to optimize this piece of code?
```python
with tf.name_scope("Hidden_layer") as scope:
  centroids = tf.Variable(tf.random_uniform([num_centr,D],dtype=tf.float32),name='centroids')
  var = tf.Variable(tf.truncated_normal([num_centr],mean=225,stddev=1,dtype=tf.float32))
  exp_list = []

  for i in xrange(num_centr):
        exp_list.append(tf.exp((-1*tf.reduce_sum(tf.square(tf.sub(x,centroids[i,:])),1))/(2*var[i])))
        phi = tf.transpose(tf.pack(exp_list))
```

For now my code works and the results beautifully surpass my expectations. My prof deemed this impossible. With Tensorflow, I was able to prototype within two hours. 
For future, I am curious if TensorFlow can improve this for-loop for calculating distances with a function like matlab's pdist()

Thanks for your help!

Rob

**Comment by zheng-xq** [comment]
This code looks reasonable for the prototype. In general, a few ways to make it faster when you get serious about performance: 

1. Use Tensor form and avoid the loop as much as possible. Give each node more things to compute tend to improve performance. 
2. Look at the timeline / profile of the nodes, and see which one is more expensive that it should. And optimize the implementation of that one. 
3. Write a custom op or kernel and manually fuse together the operations. There are research efforts on how to automatically facilitate that. But before that becomes main stream, manual fusing is the way to go.

**Comment by yaroslavvb** [comment]
You could also compare your speed against @dave-andersen 's K-means implementation here https://gist.github.com/dave-andersen/265e68a5e879b5540ebc

**Comment by RobRomijnders** [comment]
Thank you @zheng-xq @yaroslavvb 
For now, I'm happy with the implementation. I look forward to a distance implementation in Tensorflow.

Thanks again for responding
