### ISSUE TITLE
[feature request] tensor type `boundaries` in `bucketize` op

### ISSUE THREAD

**Issue by guolinke** [tensorflow/tensorflow#21934]
ping @yongtang and refer to https://github.com/tensorflow/tensorflow/pull/14774#issuecomment-416726581 

Currently, `boundaries` has to be `list` type. It is not convenience for the dynamic `boundaries` .
It would be great if`boundaries` could be `tensor` type.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device
