### ISSUE TITLE
TF logging should support "exception()"

### ISSUE THREAD

**Issue by cyfra** [tensorflow/tensorflow#21930]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: np
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: all
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:1.8
- **Python version**:2.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:N/A
- **GPU model and memory**:N/A
- **Exact command to reproduce**:N/A

### Describe the problem
Feature request:
Tensorflow logging library should support "exception()" function  - and forward it to the underlying logger.

**Comment by martinwicke** [comment]
Maybe hijacking this for a slightly bigger discussion: Should tf expose logging at all? Clearly we need something for TF itself to use, but is there an actual use case for tf.logging being part of the public API? Or should we simply remove it, and users who also want logging facilities should simply use python's logging module. A wrapper makes little sense if it doesn't add useful features.

**Comment by martinwicke** [comment]
Yes. Let's remove tf.logging from the public API (in 2.0). Users should switch to Python's logging module (or any logging facility of their choice).

I will close this issue.
