### ISSUE TITLE
Where can i find tensorflow 0,12 version?

### ISSUE THREAD

**Issue by Paulekna** [tensorflow/tensorflow#21947]
It seems that i can't find tensorflow versio 0,12.. Can anyone help me to find it?

**Comment by hsgkim** [comment]
If you mean the source code, it's under branch `r0.12`: https://github.com/tensorflow/tensorflow/tree/r0.12

**Comment by matthew-z** [comment]
https://github.com/tensorflow/tensorflow/releases/tag/v0.12.0

**Comment by av8ramit** [comment]
We do not support documentation for that version on the site, but those are the best resources if you must use it.
