### ISSUE TITLE
Feature request: partial_run_reset()

### ISSUE THREAD

**Issue by slerman12** [tensorflow/tensorflow#21953]
Experimental partial_run feature leaks memory. The problem is demonstrated below (with explanatory comments). A simple solution might look like `session.partial_run_reset()` at the end of the while loop. 

Thanks if this can be added!

```
import tensorflow as tf

# Define graph
some_placeholder_value = tf.placeholder(tf.float32, shape=[])
long_list_of_ones = tf.ones(10000)
some_operation = long_list_of_ones + 1
a_second_operation = some_operation + some_placeholder_value

# Initialize
initialize = tf.global_variables_initializer()
session = tf.Session()
session.run(initialize)

# Using partial run in a loop causes a memory leak if not all fetches are fetched. 
# For increased dynamism please allow resetting the partial run graph so that one 
# does not have to know for sure which fetches will be used ahead of time.

while True:
    # Watch as application memory steadily increases... 
    handle = session.partial_run_setup([some_operation, a_second_operation], 
                                       [some_placeholder_value])
    run = session.partial_run(handle, some_operation)
```

Memory usage grows really fast! Since a great advantage of this feature is that it affords greater dynamism and modularity, the option to reset at the end of each iteration would help since it would allow one to use this feature without knowing the full list of fetches a priori.

Alternatively, allowing the same graph components to be re-fetched would also do the trick (by putting handle outside the while loop) and would afford even more dynamism and modularity... but is probably harder to implement.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by reedwm** [comment]
/CC @vrv, can you take a look?

**Comment by vrv** [comment]
The two authors / maintainers of this experimental feature no longer work on TensorFlow, as far as I know, and partial_run functionality is probably better solved by using Eager Execution.

I'd love to leave this open for community contributions to fix this, but my guess is that no one will ever get to this, and everyone is better off moving to Eager, which is supposed to be the default mode in TF 2.0 anyway and will be supported much better.
