### ISSUE TITLE
Building Windows Tensorflow C++ Debug version failed

### ISSUE THREAD

**Issue by Wang-Guanyu** [tensorflow/tensorflow#21963]
**System information:**

- Windows 10 Home
- TensorFlow version: r1.4
- Visual studio version: vs2015 Community x64
- CUDA version: 8.0
- CUDNN version: 6.0
- GPU: NVIDIA GeForce 1080ti
- Cmake version: 3.9.0
- Swig version: 3.0.10

**Problem Description:**

- I followed some online guide to build tensorflow, firstly I used ALL_BUILD, but had compiler is out of heap space problem;
- I set compiler to x64 and build tf_core_kernels -> tensroflow_static->tensorflow project only, it said cannot open file "Debug\tf_core_gpu_kernels.lib";
- I built tf_core_gpu_kernels only, the error message is: Severity	Code Description Project File Line Suppression State Error calling a __host__ function("std::_Debug_message") from a __device__ function("std::_Debug_lt<const int &, const int &> ") is not allowed	tf_core_gpu_kernels	D:\Programs\Microsoft Visual Studio 14.0\VC\INCLUDE\xutility	911

May I know how should I deal with this problem? Or anybody has successfully built tensorflow c++ windows debug version? If yes, may I know your configurations?

Thank you very much!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by karmel** [comment]
It looks like you are using a fairly out of date version of TensorFlow. Can you try upgrading your version of TensorFlow, and resubmit if the issue continues? Thanks.
