### ISSUE TITLE
While loop no gradients provided for any variable

### ISSUE THREAD

**Issue by lizaigaoge550** [tensorflow/tensorflow#21985]
After i used while_loop, ValueError: no gradients provided for any variable , it seems like RefvariableProcessor wraps tf.variable.

![default](https://user-images.githubusercontent.com/12975526/44889979-d9ca6b80-ad0a-11e8-967b-0f31a2467c68.PNG)

# while_loop
def dynamic_pointing_decoder(self, U, mask):
        def _HMN(ut, h, us, ue):
            h_us_ue = tf.concat([h, us, ue], axis=1) #batch,5*d
            WD = tf.get_variable(name="WD", shape=(5 * self._config.hidden_dim, self._config.hidden_dim), dtype=tf.float32,initializer=xavier_initializer())
            r = tf.nn.tanh(tf.matmul(h_us_ue, WD)) #batch, d
            ut_r = tf.concat([ut, r], axis=1) #batch,3d
            W1 = tf.get_variable(name="W1", shape=(3 * self._config.hidden_dim, self._config.hidden_dim, self._config.pool_size), dtype='float32', initializer=xavier_initializer())
            b1 = tf.get_variable(name="b1_Bias", shape=(self._config.hidden_dim, self._config.pool_size), dtype=tf.float32, initializer=tf.zeros_initializer())
            mt1 = tf.einsum('bt,top->bop', ut_r, W1) + b1
            mt1 = tf.reduce_max(mt1, axis=2) #batch * d
            W2 = tf.get_variable(name="W2", shape=(self._config.hidden_dim, self._config.hidden_dim, self._config.pool_size), dtype=tf.float32, initializer=xavier_initializer())
            b2 = tf.get_variable(name="b2_Bias", shape=(self._config.hidden_dim,self._config.pool_size), dtype=tf.float32, initializer=tf.zeros_initializer())
            mt2 = tf.einsum('bi,ijp->bjp', mt1, W2) + b2
            mt2 = tf.reduce_max(mt2, axis=2) #batch * d
            mt12 = tf.concat([mt1, mt2], axis=1) # batch * 2d
            W3 = tf.get_variable(name="W3", shape=(2 * self._config.hidden_dim, 1, self._config.pool_size), dtype=tf.float32, initializer=xavier_initializer())
            b3 = tf.get_variable(name="b3_Bias", shape=(1, self._config.pool_size), dtype='float32', initializer=tf.zeros_initializer())
            hmn = tf.einsum('bi,ijp->bjp', mt12, W3) + b3
            hmn = tf.reduce_max(hmn, axis=2) #batch 1
            hmn = tf.reshape(hmn, [-1]) #batch
            return hmn

        def body(time_step, p1s, p2s, alphas, betas, us, ue, state):
            us_ue = tf.concat([us, ue], axis=1)  # batch 4d
            h, state = cell(inputs=us_ue, state=state)  # batch * d

            with tf.variable_scope('alpha_HMN', reuse=tf.AUTO_REUSE):
                alpha = tf.map_fn(lambda ut: _HMN(ut, h, us, ue), U_transpose, dtype=tf.float32)
                alpha = tf.transpose(alpha, [1, 0]) * tf.cast(mask, dtype=tf.float32)  # batch article_len
            i_start = tf.argmax(alpha, axis=1)  # batch
            i_start = tf.cast(i_start, tf.int32)
            s_idx = tf.stack([idx, i_start], axis=1)
            us = tf.gather_nd(U, s_idx)  # batch 2d

            with tf.variable_scope('betas_HMN', reuse=tf.AUTO_REUSE):
                beta = tf.map_fn(lambda ut: _HMN(ut, h, us, ue), U_transpose, dtype=tf.float32)
                beta = tf.transpose(beta, [1, 0]) * tf.cast(mask, dtype=tf.float32)  # batch article_len
            i_end = tf.argmax(beta, axis=1)  # batch
            i_end = tf.cast(i_end, tf.int32)
            e_idx = tf.stack([idx, i_end], axis=1)
            ue = tf.gather_nd(U, e_idx)  # batch 2d

            p1s.write(time_step, i_start)
            p2s.write(time_step, i_end)
            alphas.write(time_step, alpha)
            betas.write(time_step, beta)
            return (time_step+1, p1s, p2s, alphas, betas, us, ue, state)

        def condition(time_step, p1s, p2s,alphas, betas, us, ue, state):
            return tf.less(time_step, 4)

        with tf.variable_scope('dynamic_pointing_decoder'):
            cell = CudnnCompatibleLSTMCell(self._config.hidden_dim)
            i_start = tf.zeros(shape=(tf.shape(U)[0],), dtype=tf.int32)
            i_end = tf.zeros(shape=(tf.shape(U)[0],), dtype=tf.int32)
            idx = tf.range(0, tf.shape(U)[0], 1)
            s_idx = tf.stack([idx, i_start], axis=1)
            e_idx = tf.stack([idx, i_end], axis=1)
            us = tf.gather_nd(U, s_idx) #batch 2d
            ue = tf.gather_nd(U, e_idx) #batch 2d
            p1s = tf.TensorArray(tf.int32, size=4)
            p2s = tf.TensorArray(tf.int32, size=4)
            alphas = tf.TensorArray(tf.float32, size=4)
            betas = tf.TensorArray(tf.float32, size=4)
            state = tf.nn.rnn_cell.LSTMStateTuple(tf.zeros(shape=(tf.shape(U)[0], self._config.hidden_dim),dtype=tf.float32),
                                              tf.zeros(shape=(tf.shape(U)[0], self._config.hidden_dim),dtype=tf.float32))  # initial hidden state of RNN
            U_transpose = tf.transpose(U, [1, 0, 2]) #a batch 2d
            #time_step, p1s, p2s, us, ue, state
            time_step = 0
            time_step, p1s, p2s, alphas, betas, us, ue, state = tf.while_loop(cond=condition, body=body,
                                                                              loop_vars=(time_step, p1s, p2s, alphas, betas, us, ue, state),
                                                                              maximum_iterations=4)
            self.p1s = tf.transpose(p1s.stack()) #batch*4
            self.p2s = tf.transpose(p2s.stack())
            print(
                "p1s  shape : {0}".format(np.shape(self.p1s))
            )
            self.p1 = tf.unstack(self.p1s,axis=0)[-1]
            print("p1 shape : {0}".format(np.shape(self.p1)))
            self.p2 = tf.unstack(self.p2s, axis=0)[-1]
            alphas = tf.unstack(alphas.stack(), axis=0)
            betas = tf.unstack(betas.stack(), axis=0)
            print('alphas 0 shape :{0}'.format(np.shape(alphas[0])))
            return alphas, betas

#no while loop
def dynamic_pointing_decoder(self, U, mask):
        def _HMN(ut, h, us, ue):
            h_us_ue = tf.concat([h, us, ue], axis=1) #batch,5*d
            WD = tf.get_variable(name="WD", shape=(5 * self._config.hidden_dim, self._config.hidden_dim), dtype=tf.float32,initializer=xavier_initializer())
            r = tf.nn.tanh(tf.matmul(h_us_ue, WD)) #batch, d
            ut_r = tf.concat([ut, r], axis=1) #batch,3d
            W1 = tf.get_variable(name="W1", shape=(3 * self._config.hidden_dim, self._config.hidden_dim, self._config.pool_size), dtype='float32', initializer=xavier_initializer())
            b1 = tf.get_variable(name="b1_Bias", shape=(self._config.hidden_dim, self._config.pool_size), dtype=tf.float32, initializer=tf.zeros_initializer())
            mt1 = tf.einsum('bt,top->bop', ut_r, W1) + b1
            mt1 = tf.reduce_max(mt1, axis=2) #batch * d
            W2 = tf.get_variable(name="W2", shape=(self._config.hidden_dim, self._config.hidden_dim, self._config.pool_size), dtype=tf.float32, initializer=xavier_initializer())
            b2 = tf.get_variable(name="b2_Bias", shape=(self._config.hidden_dim,self._config.pool_size), dtype=tf.float32, initializer=tf.zeros_initializer())
            mt2 = tf.einsum('bi,ijp->bjp', mt1, W2) + b2
            mt2 = tf.reduce_max(mt2, axis=2) #batch * d
            mt12 = tf.concat([mt1, mt2], axis=1) # batch * 2d
            W3 = tf.get_variable(name="W3", shape=(2 * self._config.hidden_dim, 1, self._config.pool_size), dtype=tf.float32, initializer=xavier_initializer())
            b3 = tf.get_variable(name="b3_Bias", shape=(1, self._config.pool_size), dtype='float32', initializer=tf.zeros_initializer())
            hmn = tf.einsum('bi,ijp->bjp', mt12, W3) + b3
            hmn = tf.reduce_max(hmn, axis=2) #batch 1
            hmn = tf.reshape(hmn, [-1]) #batch
            return hmn
        with tf.variable_scope('dynamic_pointing_decoder'):
            #single_cell = lambda: CudnnCompatibleLSTMCell(self._config.hidden_dim)
            #cell = tf.nn.rnn_cell.MultiRNNCell([single_cell() for _ in range(1)])
            #cell = tf.nn.rnn_cell.LSTMCell(self._config.hidden_dim)
            cell = CudnnCompatibleLSTMCell(self._config.hidden_dim)
            i_start = tf.zeros(shape=(tf.shape(U)[0],), dtype=tf.int32)
            i_end = tf.zeros(shape=(tf.shape(U)[0],), dtype=tf.int32)
            #pre_start = tf.zeros(shape=(tf.shape(U)[0],), dtype=tf.int32)
            #pre_start = tf.zeros(shape=(tf.shape(U)[0],), dtype=tf.int32)
            idx = tf.range(0, tf.shape(U)[0], 1)
            s_idx = tf.stack([idx, i_start], axis=1)
            e_idx = tf.stack([idx, i_end], axis=1)
            us = tf.gather_nd(U, s_idx) #batch 2d
            ue = tf.gather_nd(U, e_idx) #batch 2d
            alphas, betas = [], []
            state = tf.nn.rnn_cell.LSTMStateTuple(tf.zeros(shape=(tf.shape(U)[0], self._config.hidden_dim),dtype=tf.float32),
                                              tf.zeros(shape=(tf.shape(U)[0], self._config.hidden_dim),dtype=tf.float32))  # initial hidden state of RNN
            U_transpose = tf.transpose(U, [1, 0, 2]) #a batch 2d
            for time_step in range(4):
                if time_step >= 1:
                    tf.get_variable_scope().reuse_variables()
                us_ue = tf.concat([us,ue], axis=1) #batch 4d
                h, state = cell(inputs=us_ue, state=state) #batch * d

                with tf.variable_scope('alpha_HMN'):
                    if time_step >= 1:
                        tf.get_variable_scope().reuse_variables()
                    alpha = tf.map_fn(lambda ut:_HMN(ut, h, us, ue), U_transpose, dtype=tf.float32)
                    alpha = tf.transpose(alpha, [1,0]) * tf.cast(mask,dtype=tf.float32) # batch article_len
                i_start = tf.argmax(alpha, axis=1) #batch
                i_start = tf.cast(i_start, tf.int32)
                s_idx = tf.stack([idx, i_start], axis=1)
                us = tf.gather_nd(U, s_idx) #batch 2d

                with tf.variable_scope('betas_HMN'):
                    if time_step >= 1:
                        tf.get_variable_scope().reuse_variables()
                    beta = tf.map_fn(lambda ut:_HMN(ut, h, us, ue), U_transpose, dtype=tf.float32)
                    beta = tf.transpose(beta, [1,0]) * tf.cast(mask,dtype=tf.float32) # batch article_len
                i_end = tf.argmax(alpha, axis=1) #batch
                i_end = tf.cast(i_end, tf.int32)
                e_idx = tf.stack([idx, i_end], axis=1)
                ue = tf.gather_nd(U, e_idx) #batch 2d

                alphas.append(alpha)
                betas.append(beta)
                #if tf.equal(pre_start, i_end) and tf.equal(pre_end, i_end):
                #    break
                #else:
                #    pre_start = i_start
                #    pre_end = i_end
            return alpha, beta

anyone can help me? Thank you very much

**Comment by lizaigaoge550** [comment]
i found the gradients are None, why and how to solve it. anyone give me some advices?

**Comment by lizaigaoge550** [comment]
In my program. i found a map_fn operation in body,  Is it right?

**Comment by lizaigaoge550** [comment]
i have solved it, but i found the speed of while_loop is slower than for, Is it reasonable? what are the tips to speed up training when using while_loop?

**Comment by cy89** [comment]
Glad you're up and running. #9527 has tips about the work in the body of the loop versus the control overheads.
