### ISSUE TITLE
Feature request for tf.test.TestCase.assertNotAllClose: do not log the differences

### ISSUE THREAD

**Issue by jnd77** [tensorflow/tensorflow#21988]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOs
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
When running this test, it logs the failure of `assertAllClose` which is not necessary.

### Source code / logs

    import tensorflow as tf
    test_case = tf.test.TestCase()
    test_case.assertNotAllClose([1, 2, 3], [2, 3, 4])

The logs are (I would expect no log):

    not close where =  (array([0, 1, 2]),)
    not close lhs =  [1 2 3]
    not close rhs =  [2 3 4]
    not close dif =  [1 1 1]
    not close tol =  [3.e-06 4.e-06 5.e-06]
    dtype = int64, shape = (3,)

**Comment by facaiy** [comment]
Hi, I create PR #22006 to fix the issue.

**Comment by jnd77** [comment]
Thanks a lot @facaiy. Looks perfect ...
Will check it out once it has been merged (which seems to take a while).
