### ISSUE TITLE
ValueError: None is only supported in the 1st dimension.

### ISSUE THREAD

**Issue by dlml** [tensorflow/tensorflow#21986]
Using TensorFlow backend.
2018-08-30 20:26:09.136414: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
(?, 32, 280, 1)
(?, 35, 5990)
(?, 32, 280, 1)
(?, 35, 5990)
WARNING:tensorflow:From /home/huangwei/.local/lib/python3.5/site-packages/tensorflow/python/ops/init_ops.py:86: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with distribution=normal is deprecated and will be removed in a future version.
Instructions for updating:
`normal` is a deprecated alias for `truncated_normal`
WARNING:tensorflow:No training configuration found in save file: the model was *not* compiled. Compile it manually.
Traceback (most recent call last):
  File "1.py", line 15, in <module>
    tflite_model = converter.convert()
  File "/home/huangwei/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/lite.py", line 394, in convert
    "invalid shape '{1}'.".format(_tensor_name(tensor), shape))
ValueError: None is only supported in the 1st dimension. Tensor 'the_input' has invalid shape '[None, 32, None, 1]'.

**Comment by dlml** [comment]
tf.__verion
'1.11.0-dev20180830'
python3.5
ubuntu

**Comment by dlml** [comment]
now, i have sovled this problem,but when i quantized my model got a bug(no quantized no bug)

b"2018-09-04 17:43:07.631853: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.632044: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.632181: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.632298: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.632415: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.632566: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.632683: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.632920: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.633044: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.633390: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.633573: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.633686: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.633807: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.633943: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.634092: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.634256: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.634413: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.634594: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.634825: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.635026: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.635212: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.635350: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.635546: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.635691: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.635836: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.636058: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.636231: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1055] Converting unsupported operation: SquaredDifference\n2018-09-04 17:43:07.674613: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1157 operators, 1673 arrays (0 quantized)\n2018-09-04 17:43:07.703190: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 1099 operators, 1586 arrays (0 quantized)\n2018-09-04 17:43:07.738731: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1099 operators, 1586 arrays (0 quantized)\n2018-09-04 17:43:07.791890: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 822 operators, 1281 arrays (1 quantized)\n2018-09-04 17:43:07.833745: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 820 operators, 1278 arrays (1 quantized)\n2018-09-04 17:43:07.866853: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 820 operators, 1278 arrays (1 quantized)\n2018-09-04 17:43:07.879104: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before default min-max range propagation graph transformations: 820 operators, 1278 arrays (1 quantized)\n2018-09-04 17:43:07.891322: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After default min-max range propagation graph transformations pass 1: 820 operators, 1278 arrays (1 quantized)\n2018-09-04 17:43:07.909161: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before quantization graph transformations: 820 operators, 1278 arrays (1 quantized)\n2018-09-04 17:43:07.909290: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:100] Constant array conv2d_55/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.\n2018-09-04 17:43:07.909526: F tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:474] Unimplemented: this graph contains an operator of type (Unsupported TensorFlow op: SquaredDifference) for which the quantized form is not yet implemented. Sorry, and patches welcome (that's a relatively fun patch to write, mostly providing the actual quantized arithmetic code for this op).\nAborted (core dumped)\n"

**Comment by dlml** [comment]
when i quantized  my model,got an Unsupported TensorFlow op: SquaredDifference, if no use quantized form, i can get a tflite form(use_custom_op)

**Comment by dlml** [comment]
ValueError: Didn't find custom op for name 'Merge' with version 1
Didn't find custom op for name 'Switch' with version 1
Didn't find custom op for name 'SquaredDifference' with version 1
Registration failed.

**Comment by jdduke** [comment]
Hi @dlml, were you able to use the workaround you mentioned in #22022 ?

**Comment by gargn** [comment]
The list of supported ops are available [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/tf_ops_compatibility.md). The two recommended solutions are:
1. Add a custom op as described [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/custom_operators.md).
2. Only use the ops that are currently supported by TFLite in your model.

Quantized `SquaredDifference` hasn't been prioritized yet, contributions are welcome, but we are also tracking these operations requests here: https://github.com/tensorflow/tensorflow/issues/21526 to help with prioritizing. I have added your request there.

Additionally, as @jdduke  mentioned, `Merge` and `Switch` are not prioritized and are not in our immediate roadmap due to complexity. For that reason, we will close this issue, please reopen if you have more info on the specific model you are trying to convert. Thanks!

**Comment by farmaker47** [comment]
Solved it with extra parameters inside code:

    import tensorflow as tf

    graph_def_file = "mask_rcnn_resnet50_atrous_coco_2018_01_28/frozen_inference_graph.pb"
    input_arrays = ["image_tensor"]
    output_arrays = ["detection_scores","detection_boxes","detection_classes","detection_masks"]

    converter = tf.lite.TFLiteConverter.from_frozen_graph(
            graph_def_file, input_arrays, output_arrays,input_shapes={"image_tensor":[1,600,600,3]})
    tflite_model = converter.convert()
    open("converted_model.tflite", "wb").write(tflite_model)

Although it cannot produce .tflite because it raises kmerge error "OperatorType::kMerge Found Sub as non-selected output from Switch, but only Merge supported"
