### ISSUE TITLE
how can I export android-tensorflow into my android stuido

### ISSUE THREAD

**Issue by fhowen** [tensorflow/tensorflow#220]
Is it possible for me to import the android example into android studio? I am confused because I haven't found the libtensorflowdemo.so lib (in the code ,this lib is loaded) about tensorflow in the folders

**Comment by Yangqing** [comment]
Currently, the android demo is built with Bazel - one way to go is to put your android app under bazel, and follow a similar build rule as highlighted by the Android example.

If that is not possible, you can manually copy the header files and the pre-built .so file to your Android Studio project. The libtensorflow_demo.so can be found in the bazel cache. If you use Linux, it is usually located at ~/.cache/bazel. Find it with:

```shell
find ~/.cache/bazel -name "libtensorflow_demo.so"
```

(Another way is to rename the *.apk to *.apk.zip and unzip it. The resulting .so file is the same as the one found above.)

**Comment by Yangqing** [comment]
Assuming the above addresses your problem, I will close this issue - feel free to reopen if you encounter problems further.

**Comment by renats** [comment]
Hello @Yangqing ! About building Tensorflow with Gradle, which header files should be included manually in the app? Are the header files from all dependencies needed? There are also some files that are generated with photobuf, right? How would that be possible in Gradle?

**Comment by flawless2011** [comment]
@Yangqing do you guys happen to have example WORKSPACE and BUILD files for using TensorFlow in an Android app that is separately managed (i.e. the Android project is not located inside the TensorFlow project like your example is)?  bazel has a huge learning curve to incorporate a large dependency like TensorFlow and I'm not crazy about manually copying over the .h and .so files.

**Comment by GayatriSN** [comment]
@Yangqing I had been facing the same problem so I located the .so file as you mentioned. After this, where do we have to place the file?

**Comment by CalmWaves** [comment]
You can find a project android demo done using Android studio here:
[https://github.com/miyosuda/TensorFlowAndroidDemo](url) 

but it only works with armebi v7 only. If any one can tell me how to convert this to run on x86 and x86_64 devices it would be a great help.

**Comment by renats** [comment]
@CalmWaves Check this out https://github.com/tensorflow/tensorflow/issues/1019

**Comment by CalmWaves** [comment]
Hi renats, 
                 Thank you for your reply. I already checked your post, but I want to know the **commands that you used to build the project using bazel**.

 And the other thing is you have used bazel to build the project, But I need to **use gradle in Android Studio.**

Please help me on this

**Comment by andrewharp** [comment]
Instructions for building the Android demo APK with Android Studio (Bazel still required for native libs): https://github.com/tensorflow/tensorflow/issues/3444

**Comment by cesardelgadof** [comment]
@CalmWaves check this out https://github.com/cesardelgadof/TensorFlowAndroidMNIST

**Comment by CalmWaves** [comment]
Thanks @cesardelgadof  I will check it out.
