### ISSUE TITLE
bug in string_input_producer

### ISSUE THREAD

**Issue by andyhujinzhao** [tensorflow/tensorflow#22011]
https://github.com/tensorflow/tensorflow/blob/r1.10/tensorflow/python/training/input.py

line169:
element_shape = input_tensor.shape[1:].merge_with(element_shape)
 input_tensor.shape[1:] must be compatable with element_shape

line252:
element_shape = []

so, no matter what kind of shape you defined in input_tensor.shape[1:], it will raise an error!

import tensorflow as tf

test_list_1 = ['andy', 'jerry', 'lala', 'coco', 'mimi']
test_list_2 = ['andy', 'jerry', 'lala', 'coco', 'mimi']
test_tensor_1 = tf.convert_to_tensor(test_list_1)
test_tensor_2 = tf.convert_to_tensor(test_list_2)

res = tf.train.string_input_producer([test_tensor_1, test_tensor_2])

sess = tf.Session()

tf.train.start_queue_runners(sess = sess)

print(sess.run(res))

#ValueError: Shapes (5,) and () are not compatible

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by yongtang** [comment]
@andyhujinzhao The docstring:
https://github.com/tensorflow/tensorflow/blob/r1.10/tensorflow/python/training/input.py#L208

specifies that the input is `A 1-D string tensor`.

**Comment by mrry** [comment]
As @yongtang pointed out, this is working as intended.

(Note that this API is now deprecated, and will be removed in TensorFlow 2.0. We recommend that new code uses `tf.data`.)
