### ISSUE TITLE
ubuntu image with tensorflow preinstalled 

### ISSUE THREAD

**Issue by anaskoara** [tensorflow/tensorflow#22034]
Hi every one
I tried install tensorflow-gpu on my pc I failed i tried all possible ways I failed to build it from source I failed to run it from docker image
can on you share ubuntu image with tensorflow-gpu installed on it i iam despaired really need to run tensorlow-gpu
and I will be very thankful

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by gunan** [comment]
Did you try using out docker containers?
https://www.tensorflow.org/install/install_linux#InstallingDocker

Unfortunately, outside docker we cannot provide full ubuntu system images with tensorflow, due to licensing restrictions.
