### ISSUE TITLE
Keras Save / Load with Eager

### ISSUE THREAD

**Issue by lc0** [tensorflow/tensorflow#22038]
https://github.com/tensorflow/tensorflow/blob/ec357afc00c8fb0e9c99754afd78d47fc0ab2116/tensorflow/python/keras/engine/network.py#L1357-L1361

Since TensorFlow uses more and more of Eager execution. 
Would it make sense to add a bit more verbose mention on how to save a non-graph model?

Just mentioning more explicitly the reason and linking `tfe.Checkpoint` docs would be already of great help.

Any objections?

**Comment by zerocurve** [comment]
agree, actually, why we limit to graph network at the beginning?

**Comment by lc0** [comment]
cc @fchollet and @alextp

**Comment by alextp** [comment]
@allenlavoie , assigning to you

**Comment by lc0** [comment]
I am not sure, if we need to adapt save method for Eager, but I would at least add an explicit reference to `tfe.Checkpoint` and docs, so once a person sees it she or he can figure out what to do next.

Please let me know if I can help

**Comment by allenlavoie** [comment]
There is an effort to make `Model.save` work with TensorFlow formats (SavedModel). Right now it requires `get_config()` and `from_config()` to be implemented for subclassed Models, but that could change (@k-w-w has been iterating on `tf.contrib.saved_model.save_keras_model`). 

On the doc issue, maybe we should reference `save_weights`/`load_weights` from `save` for now? Those work fine with subclassed `Model`s (+eager). It won't save the `Model`, but neither does `tf.train.Checkpoint`. Happy to review a PR for that @lc0 , or I can get to it (but not super soon).

**Comment by lc0** [comment]
@allenlavoie just added a small reference. 

Any better way to do it?

**Comment by lc0** [comment]
Since the fix is merged, I am closing the issue. Looking forward to the second stage. Thanks @allenlavoie for support!
