### ISSUE TITLE
eager mode using tf.train.Checkpoint not support setting max models to keep

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#22036]
tensorflow 1.10.1
It looks tf.train.Checkpoint not support setting max models to keep.
In tensorflow/python/training/checkpointable/util.py
line 1123   def save(self, file_prefix, checkpoint_number=None, session=None):
line 1178 self._last_save_saver = saver_lib.Saver(var_list=named_variables)
looks like we need saver_lib.Saver(var_list=named_variables, max_to_keep=...)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by chenghuige** [comment]
@allenlavoie  Thanks, this works, I need to update tf code, closing this issue.
