### ISSUE TITLE
Can't Import Keras from Tensorflow library

### ISSUE THREAD

**Issue by gergoh** [tensorflow/tensorflow#22041]
I've been trying to import keras from tensorflow using the following statement (using Python in PyCharm):
```
import tensorflow as tf
from tensorflow import keras
```

It should work as far as I know but I still get the following message for some reason:
```
from tensorflow import keras
ImportError: cannot import name 'keras' from 'tensorflow'(/Users/gabork/PycharmProjects/Tester/venv/lib/python3.7/site-packages/tensorflow/__init__.py)
```

**EDIT:** As I'm using PyCharm with Tensorflow version 0.12.0 and Python 3.7, I'm suspecting version issues. I tried updating to Tensorflow 1.10.1 through PyCharm (venv) but got the following message:
```
Collecting tensorflow==1.10.1

 Could not find a version that satisfies the requirement tensorflow==1.10.1 (from versions: )
No matching distribution found for tensorflow==1.10.1
```

**EDIT2:** Downgrading to Python 2.7 seems to fix the issue. But I would still prefer someone more knowledgable to maybe give me a reason why it worked like this.

Have I written custom code: 
> No, only code written is shown above

OS Platform and Distribution: 
> OSX 10.13.6

TensorFlow version
> 0.12.0

GPU model and memory
> Intel HD Graphics 6000 1536 MB graphics
> 8 GB 1600 MHz DDR3 Memory

Exact command to reproduce
> Shown Above

Mobile device
> N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by successar** [comment]
Tensorflow still doesn't support python 3.7 . See #20517

**Comment by omalleyt12** [comment]
@gergoh You'll have to update your version of Tensorflow, tf.keras didn't exist in 0.12. You can use Python 2.7 or Python 3.6
