### ISSUE TITLE
Tensorflow failed to build on x64 when build with MSVC

### ISSUE THREAD

**Issue by spacelg** [tensorflow/tensorflow#22047]
System information:
*Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
NA
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows server 2016
*TensorFlow installed from (source or binary):
Source
*TensorFlow version (use command below):
https://github.com/tensorflow/tensorflow/commit/24787842adfefe35f5a520313d775b14c29f143a#diff-47cae0cad6802731af5c3d2c42011880
*Python version:
Anaconda 4.1.1 (Python 3.5 64-bit)
*Bazel version (if compiling from source):
N/A
*GCC/Compiler version (if compiling from source):
VS2017 15.7.2
*CUDA/cuDNN version:
NVidia CUDA Toolkit 8.0
NVidia CUDNN 5.1
*GPU model and memory:
N/A
*Exact command to reproduce:
N/A

Describe the problem:
Tensorflow failed to build on x64. This issue can be reproduced from the master revision commit/24787842adfefe35f5a520313d775b14c29f143a#diff-47cae0cad6802731af5c3d2c42011880. This should be tensorflow source issue, could you please help take a look at this? Thanks!

The failures like:
The whole log file please see attachment.
[log_x64_build.log](https://github.com/tensorflow/tensorflow/files/2347551/log_x64_build.log)

Repro steps:

1.git clone https://github.com/tensorflow/tensorflow D:\Tensorflow\src
2.pushd D:\Tensorflow
3.set PreferredToolArchitecture=x64
4.set rel=Release
5.set CUDNN_HOME="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\cuda"
6.set PY=C:\ProgramData\Anaconda3
7.set CL=/FS /permissive-
8.cmake D:\Tensorflow\src\tensorflow\contrib\cmake -A x64 -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=C:\ProgramData\Anaconda3\python.exe -DPYTHON_LIBRARIES=C:\ProgramData\Anaconda3\libs\python36.lib -DSWIG_EXECUTABLE=D:\Tensorflow\swigwin-3.0.12\swig.exe -Dtensorflow_BUILD_PYTHON_TESTS=ON -Dtensorflow_BUILD_SHARED_LIB=ON
9.MSBuild /m /p:Configuration=Release;Platform=x64 /p:WindowsTargetPlatformVersion=10.0.17134.0 tensorflow.sln /t:Rebuild

Build Message:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX64\x64\CL.exe /c /ID:\Tensorflow\src /ID:\Tensorflow\build_x64 /ID:\Tensorflow\build_x64\external\zlib_archive /I"D:\Tensorflow\build_x64\external\gif_archive\giflib-5.1.4" /ID:\Tensorflow\build_x64\external\png_archive /ID:\Tensorflow\build_x64\external\jpeg_archive /ID:\Tensorflow\build_x64\external\lmdb /ID:\Tensorflow\build_x64\external\eigen_archive /ID:\Tensorflow\src\third_party\eigen3 /ID:\Tensorflow\build_x64\gemmlowp\src\gemmlowp /ID:\Tensorflow\build_x64\jsoncpp\src\jsoncpp /ID:\Tensorflow\build_x64\external\farmhash_archive /ID:\Tensorflow\build_x64\external\farmhash_archive\util /ID:\Tensorflow\build_x64\external\highwayhash /ID:\Tensorflow\build_x64\cub\src\cub /ID:\Tensorflow\build_x64\external\nsync\public /ID:\Tensorflow\build_x64\protobuf\src\protobuf\src /ID:\Tensorflow\build_x64\re2\install\include /ID:\Tensorflow\build_x64\external\sqlite /ID:\Tensorflow\build_x64\double_conversion\src\double_conversion /ID:\Tensorflow\build_x64\grpc\src\grpc\include /ID:\Tensorflow\build_x64\snappy\src\snappy /nologo /W3 /WX- /diagnostics:caret /MP /O2 /Ob2 /D WIN32 /D _WINDOWS /D NDEBUG /D _ITERATOR_DEBUG_LEVEL=0 /D SQLITE_OMIT_LOAD_EXTENSION /D EIGEN_AVOID_STL_ARRAY /D WIN64 /D NOMINMAX /D _WIN32_WINNT=0x0A00 /D WIN32_LEAN_AND_MEAN /D NOGDI /D PLATFORM_WINDOWS /D TENSORFLOW_USE_EIGEN_THREADPOOL /D EIGEN_HAS_C99_MATH /D TF_COMPILE_LIBRARY /D _HAS_EXCEPTIONS=0 /D GRPC_ARES=0 /D TF_USE_SNAPPY /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /GF /Gm- /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /openmp /std:c++14 /Fo"tf_core_lib.dir\Release\\" /Fd"tf_core_lib.dir\Release\tf_core_lib.pdb" /Gd /TP /wd4267 /wd4244 /wd4800 /wd4503 /wd4554 /wd4996 /wd4348 /wd4018 /wd4099 /wd4146 /wd4305 /wd4307 /wd4715 /wd4722 /wd4723 /wd4838 /wd4309 /wd4334 /wd4003 /wd4506 /wd4577 /FC /errorReport:queue  /EHs-c- /bigobj D:\Tensorflow\src\tensorflow\core\lib\bfloat16\bfloat16.cc D:\Tensorflow\src\tensorflow\core\lib\core\arena.cc D:\Tensorflow\src\tensorflow\core\lib\core\bitmap.cc D:\Tensorflow\src\tensorflow\core\lib\core\coding.cc D:\Tensorflow\src\tensorflow\core\lib\core\status.cc D:\Tensorflow\src\tensorflow\core\lib\core\threadpool.cc D:\Tensorflow\src\tensorflow\core\lib\db\snapfn.cc D:\Tensorflow\src\tensorflow\core\lib\db\sqlite.cc D:\Tensorflow\src\tensorflow\core\lib\gif\gif_io.cc D:\Tensorflow\src\tensorflow\core\lib\hash\crc32c.cc D:\Tensorflow\src\tensorflow\core\lib\hash\crc32c_accelerate.cc D:\Tensorflow\src\tensorflow\core\lib\hash\hash.cc D:\Tensorflow\src\tensorflow\core\lib\histogram\histogram.cc D:\Tensorflow\src\tensorflow\core\lib\io\block.cc D:\Tensorflow\src\tensorflow\core\lib\io\block_builder.cc D:\Tensorflow\src\tensorflow\core\lib\io\buffered_inputstream.cc D:\Tensorflow\src\tensorflow\core\lib\io\compression.cc D:\Tensorflow\src\tensorflow\core\lib\io\format.cc D:\Tensorflow\src\tensorflow\core\lib\io\inputbuffer.cc D:\Tensorflow\src\tensorflow\core\lib\io\inputstream_interface.cc D:\Tensorflow\src\tensorflow\core\lib\io\iterator.cc D:\Tensorflow\src\tensorflow\core\lib\io\path.cc D:\Tensorflow\src\tensorflow\core\lib\io\random_inputstream.cc D:\Tensorflow\src\tensorflow\core\lib\io\record_reader.cc D:\Tensorflow\src\tensorflow\core\lib\io\record_writer.cc D:\Tensorflow\src\tensorflow\core\lib\io\snappy\snappy_inputbuffer.cc D:\Tensorflow\src\tensorflow\core\lib\io\snappy\snappy_outputbuffer.cc D:\Tensorflow\src\tensorflow\core\lib\io\table.cc D:\Tensorflow\src\tensorflow\core\lib\io\table_builder.cc D:\Tensorflow\src\tensorflow\core\lib\io\two_level_iterator.cc D:\Tensorflow\src\tensorflow\core\lib\io\zlib_compression_options.cc D:\Tensorflow\src\tensorflow\core\lib\io\zlib_inputstream.cc D:\Tensorflow\src\tensorflow\core\lib\io\zlib_outputbuffer.cc D:\Tensorflow\src\tensorflow\core\lib\jpeg\jpeg_handle.cc D:\Tensorflow\src\tensorflow\core\lib\jpeg\jpeg_mem.cc D:\Tensorflow\src\tensorflow\core\lib\monitoring\collection_registry.cc D:\Tensorflow\src\tensorflow\core\lib\monitoring\sampler.cc D:\Tensorflow\src\tensorflow\core\lib\png\png_io.cc D:\Tensorflow\src\tensorflow\core\lib\random\distribution_sampler.cc D:\Tensorflow\src\tensorflow\core\lib\random\random.cc D:\Tensorflow\src\tensorflow\core\lib\random\random_distributions.cc D:\Tensorflow\src\tensorflow\core\lib\random\simple_philox.cc D:\Tensorflow\src\tensorflow\core\lib\random\weighted_picker.cc D:\Tensorflow\src\tensorflow\core\lib\strings\base64.cc D:\Tensorflow\src\tensorflow\core\lib\strings\numbers.cc D:\Tensorflow\src\tensorflow\core\lib\strings\ordered_code.cc D:\Tensorflow\src\tensorflow\core\lib\strings\proto_serialization.cc D:\Tensorflow\src\tensorflow\core\lib\strings\proto_text_util.cc D:\Tensorflow\src\tensorflow\core\lib\strings\scanner.cc D:\Tensorflow\src\tensorflow\core\lib\strings\str_util.cc D:\Tensorflow\src\tensorflow\core\lib\strings\strcat.cc D:\Tensorflow\src\tensorflow\core\lib\strings\stringprintf.cc D:\Tensorflow\src\tensorflow\core\lib\wav\wav_io.cc D:\Tensorflow\src\tensorflow\core\platform\abi.cc D:\Tensorflow\src\tensorflow\core\platform\cpu_feature_guard.cc D:\Tensorflow\src\tensorflow\core\platform\cpu_info.cc D:\Tensorflow\src\tensorflow\core\platform\denormal.cc D:\Tensorflow\src\tensorflow\core\platform\file_system.cc D:\Tensorflow\src\tensorflow\core\platform\file_system_helper.cc D:\Tensorflow\src\tensorflow\core\platform\protobuf_util.cc D:\Tensorflow\src\tensorflow\core\platform\setround.cc D:\Tensorflow\src\tensorflow\core\platform\stacktrace_handler.cc D:\Tensorflow\src\tensorflow\core\platform\tensor_coding.cc D:\Tensorflow\src\tensorflow\core\platform\default\device_tracer.cc D:\Tensorflow\src\tensorflow\core\platform\default\human_readable_json.cc D:\Tensorflow\src\tensorflow\core\platform\default\logging.cc D:\Tensorflow\src\tensorflow\core\platform\default\mutex.cc D:\Tensorflow\src\tensorflow\core\platform\default\protobuf.cc D:\Tensorflow\src\tensorflow\core\platform\default\string_coding.cc D:\Tensorflow\src\tensorflow\core\framework\resource_handle.cc D:\Tensorflow\src\tensorflow\core\platform\windows\net.cc D:\Tensorflow\src\tensorflow\core\platform\windows\port.cc D:\Tensorflow\src\tensorflow\core\platform\windows\windows_file_system.cc
bfloat16.cc
         arena.cc
         bitmap.cc
         coding.cc
         status.cc
         threadpool.cc
         snapfn.cc
         sqlite.cc
         gif_io.cc
         crc32c.cc
         crc32c_accelerate.cc
         hash.cc
         histogram.cc
         block.cc
         block_builder.cc
         buffered_inputstream.cc
         compression.cc
         format.cc
         inputbuffer.cc
         inputstream_interface.cc
         iterator.cc
         path.cc
         random_inputstream.cc
         record_reader.cc
         record_writer.cc
         snappy_inputbuffer.cc
   297>D:\Tensorflow\src\tensorflow\core\lib\core\stringpiece.h(34,10): error C1083:  Cannot open include file: 'absl/strings/string_view.h': No such file or directory (d:\agent\_work\3\s\src\vctools\compiler\cxxfe\sl\p1\c\p0prepro.c:1711) [D:\Tensorflow\build_x64\tf_core_lib.vcxproj]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Mobile device

**Comment by skye** [comment]
I believe the preferred way to build TF on windows is to use bazel now. @gunan can comment further.

**Comment by gunan** [comment]
Yes. New install guide is here:
https://github.com/tensorflow/docs/blob/master/site/en/install/install_sources_windows.md
Looks like it did not make it to the website yet. @MarkDaoust can we push this page to the 1.10 docs, or do we need to wait until 1.11?

**Comment by MarkDaoust** [comment]
Fixed:

https://www.tensorflow.org/install/install_sources_windows

**Comment by PinkySan** [comment]
not working for me at the moment. See [here](https://github.com/tensorflow/tensorflow/issues/21880#issuecomment-420782866)

It is a bit confusing to build the target **libtensorflow_cc.so** on a windows machine. (shared object on windows?!?! CMake is much more accurate and clearer in this case, but unfortunatly you dropped the CMake support in 1.10)

**Comment by gunan** [comment]
You should not be building libtensorflow_cc.so on windows.
Maybe you are looking at the wrong documentation?

**Comment by PinkySan** [comment]
But what is the main target for the c++ library?

**Comment by gittyupagain** [comment]
@PinkySan I was able to successfully build the TensorFlow C++ library by building `//tensorflow:libtensorflow_cc.so` from the `v1.11.0-rc0` tag. Without any changes, this built a version of `libtensorflow_cc.so` that only had the `TF_*` and `TFE_*` symbols in it. After closer examination, those are the only explicitly exported symbols, so it was expected. In order to get the necessary C++ symbols, I modified `tensorflow/BUILD` as follows:
```
--- a/tensorflow/BUILD
+++ b/tensorflow/BUILD
@@ -562,7 +562,10 @@ tf_cc_shared_object(
             "-Wl,-exported_symbols_list",  # This line must be directly followed by the exported_symbols.lds file
             "$(location //tensorflow:tf_exported_symbols.lds)",
         ],
-        "//tensorflow:windows": [],
+        "//tensorflow:windows": [
+           "-def:" +  # This line must be directly followed by the exported_symbols_msvc.lds file
+            "$(location //tensorflow:tf_exported_symbols_msvc.lds)",
+       ],
         "//conditions:default": [
             "-z defs",
             "-Wl,--version-script",  #  This line must be directly followed by the version_script.lds file
@@ -571,6 +574,7 @@ tf_cc_shared_object(
     }),
     deps = [
         "//tensorflow:tf_exported_symbols.lds",
+        "//tensorflow:tf_exported_symbols_msvc.lds",
         "//tensorflow:tf_version_script.lds",
         "//tensorflow/c:c_api",
         "//tensorflow/c/eager:c_api",
@@ -586,6 +590,7 @@ exports_files(
     [
         "tf_version_script.lds",
         "tf_exported_symbols.lds",
+        "tf_exported_symbols_msvc.lds",
     ],
 )

```
I then had to provide a DEF file that contained the symbols. I called it `tf_exported_symbols_msvc.lds`, but that was really just an arbitrary decision. Luckily there is already a script for extracting the symbols that may be found in the `tensorflow/contrib/cmake/tools` directory called `create_def_file.py`. The trick was finding the .lib files to include as inputs to the script. Due to the limitations of number of symbols (65535) that may be exported in a DLL, I had to pare down the symbols. It took some trial and error to find a suitable list that fell under the limit. It is nice that `create_def_file.py` shows the number of symbols as the second output value, making iteration of the list easier.

As for parameters to that script, you need a semicolon separated list of the files for the inputs, the `--output` parameter should be `tensorflow/tf_exported_symbols_msvc.lds`, the `--bitness` should be `64` or `32` (based one whether you are building for x64 or x86), and the `--target` should be either `tensorflow` or `tensorflow_cc` (use the former to match the name from the cmake builds). After running the script, the appropriate `tf_exported_symbols_msvc.lds` file should be created. You can now build the C++ target. If all is successful, you will need to rename `libtensorflow_cc.so` to `tensorflow.dll` (or `tensorflow_cc.dll` if you specified that when creating the DEF file). Likewise, rename `libtensorflow_cc.so.if.lib` to `tensorflow.lib` (or `tensorflow_cc.lib`). You may not know for sure if you have all of the symbols you need until you link against your own executable.

I could provide the list of libraries that I ended up using, but you may have other required symbols an my list is probably not the best. The libraries come from the `c`, `cc`, and `core` directories. You could also probably get the list of .lib file names by running through the cmake process, then seeing which .lib files it uses. Ideally someone with more knowledge of TensorFlow could automate this process.

**Comment by Steroes** [comment]
> @PinkySan I was able to successfully build the TensorFlow C++ library by building `//tensorflow:libtensorflow_cc.so` from the `v1.11.0-rc0` tag. Without any changes, this built a version of `libtensorflow_cc.so` that only had the `TF_*` and `TFE_*` symbols in it. After closer examination, those are the only explicitly exported symbols, so it was expected. In order to get the necessary C++ symbols, I modified `tensorflow/BUILD` as follows:
> 
> ```
> --- a/tensorflow/BUILD
> +++ b/tensorflow/BUILD
> @@ -562,7 +562,10 @@ tf_cc_shared_object(
>              "-Wl,-exported_symbols_list",  # This line must be directly followed by the exported_symbols.lds file
>              "$(location //tensorflow:tf_exported_symbols.lds)",
>          ],
> -        "//tensorflow:windows": [],
> +        "//tensorflow:windows": [
> +           "-def:" +  # This line must be directly followed by the exported_symbols_msvc.lds file
> +            "$(location //tensorflow:tf_exported_symbols_msvc.lds)",
> +       ],
>          "//conditions:default": [
>              "-z defs",
>              "-Wl,--version-script",  #  This line must be directly followed by the version_script.lds file
> @@ -571,6 +574,7 @@ tf_cc_shared_object(
>      }),
>      deps = [
>          "//tensorflow:tf_exported_symbols.lds",
> +        "//tensorflow:tf_exported_symbols_msvc.lds",
>          "//tensorflow:tf_version_script.lds",
>          "//tensorflow/c:c_api",
>          "//tensorflow/c/eager:c_api",
> @@ -586,6 +590,7 @@ exports_files(
>      [
>          "tf_version_script.lds",
>          "tf_exported_symbols.lds",
> +        "tf_exported_symbols_msvc.lds",
>      ],
>  )
> ```
> I then had to provide a DEF file that contained the symbols. I called it `tf_exported_symbols_msvc.lds`, but that was really just an arbitrary decision. Luckily there is already a script for extracting the symbols that may be found in the `tensorflow/contrib/cmake/tools` directory called `create_def_file.py`. The trick was finding the .lib files to include as inputs to the script. Due to the limitations of number of symbols (65535) that may be exported in a DLL, I had to pare down the symbols. It took some trial and error to find a suitable list that fell under the limit. It is nice that `create_def_file.py` shows the number of symbols as the second output value, making iteration of the list easier.
> 
> As for parameters to that script, you need a semicolon separated list of the files for the inputs, the `--output` parameter should be `tensorflow/tf_exported_symbols_msvc.lds`, the `--bitness` should be `64` or `32` (based one whether you are building for x64 or x86), and the `--target` should be either `tensorflow` or `tensorflow_cc` (use the former to match the name from the cmake builds). After running the script, the appropriate `tf_exported_symbols_msvc.lds` file should be created. You can now build the C++ target. If all is successful, you will need to rename `libtensorflow_cc.so` to `tensorflow.dll` (or `tensorflow_cc.dll` if you specified that when creating the DEF file). Likewise, rename `libtensorflow_cc.so.if.lib` to `tensorflow.lib` (or `tensorflow_cc.lib`). You may not know for sure if you have all of the symbols you need until you link against your own executable.
> 
> I could provide the list of libraries that I ended up using, but you may have other required symbols an my list is probably not the best. The libraries come from the `c`, `cc`, and `core` directories. You could also probably get the list of .lib file names by running through the cmake process, then seeing which .lib files it uses. Ideally someone with more knowledge of TensorFlow could automate this process.

Do you have a list of the libraries available for me? I think I try to add too many of them. Thanks beforehand.

**Comment by PinkySan** [comment]
Unfortunatly I do not have a list of the libraries

**Comment by HackersSpirit** [comment]
> @PinkySan I was able to successfully build the TensorFlow C++ library by building `//tensorflow:libtensorflow_cc.so` from the `v1.11.0-rc0` tag. Without any changes, this built a version of `libtensorflow_cc.so` that only had the `TF_*` and `TFE_*` symbols in it. After closer examination, those are the only explicitly exported symbols, so it was expected. In order to get the necessary C++ symbols, I modified `tensorflow/BUILD` as follows:
> 
> ```
> --- a/tensorflow/BUILD
> +++ b/tensorflow/BUILD
> @@ -562,7 +562,10 @@ tf_cc_shared_object(
>              "-Wl,-exported_symbols_list",  # This line must be directly followed by the exported_symbols.lds file
>              "$(location //tensorflow:tf_exported_symbols.lds)",
>          ],
> -        "//tensorflow:windows": [],
> +        "//tensorflow:windows": [
> +           "-def:" +  # This line must be directly followed by the exported_symbols_msvc.lds file
> +            "$(location //tensorflow:tf_exported_symbols_msvc.lds)",
> +       ],
>          "//conditions:default": [
>              "-z defs",
>              "-Wl,--version-script",  #  This line must be directly followed by the version_script.lds file
> @@ -571,6 +574,7 @@ tf_cc_shared_object(
>      }),
>      deps = [
>          "//tensorflow:tf_exported_symbols.lds",
> +        "//tensorflow:tf_exported_symbols_msvc.lds",
>          "//tensorflow:tf_version_script.lds",
>          "//tensorflow/c:c_api",
>          "//tensorflow/c/eager:c_api",
> @@ -586,6 +590,7 @@ exports_files(
>      [
>          "tf_version_script.lds",
>          "tf_exported_symbols.lds",
> +        "tf_exported_symbols_msvc.lds",
>      ],
>  )
> ```
> I then had to provide a DEF file that contained the symbols. I called it `tf_exported_symbols_msvc.lds`, but that was really just an arbitrary decision. Luckily there is already a script for extracting the symbols that may be found in the `tensorflow/contrib/cmake/tools` directory called `create_def_file.py`. The trick was finding the .lib files to include as inputs to the script. Due to the limitations of number of symbols (65535) that may be exported in a DLL, I had to pare down the symbols. It took some trial and error to find a suitable list that fell under the limit. It is nice that `create_def_file.py` shows the number of symbols as the second output value, making iteration of the list easier.
> 
> As for parameters to that script, you need a semicolon separated list of the files for the inputs, the `--output` parameter should be `tensorflow/tf_exported_symbols_msvc.lds`, the `--bitness` should be `64` or `32` (based one whether you are building for x64 or x86), and the `--target` should be either `tensorflow` or `tensorflow_cc` (use the former to match the name from the cmake builds). After running the script, the appropriate `tf_exported_symbols_msvc.lds` file should be created. You can now build the C++ target. If all is successful, you will need to rename `libtensorflow_cc.so` to `tensorflow.dll` (or `tensorflow_cc.dll` if you specified that when creating the DEF file). Likewise, rename `libtensorflow_cc.so.if.lib` to `tensorflow.lib` (or `tensorflow_cc.lib`). You may not know for sure if you have all of the symbols you need until you link against your own executable.
> 
> I could provide the list of libraries that I ended up using, but you may have other required symbols an my list is probably not the best. The libraries come from the `c`, `cc`, and `core` directories. You could also probably get the list of .lib file names by running through the cmake process, then seeing which .lib files it uses. Ideally someone with more knowledge of TensorFlow could automate this process.

@gittyupagain : Can you please sample syntax of how to create_def_file.py. Your explanation is very clear but getting error of file cannot be found

**Comment by HackersSpirit** [comment]
Hello @gittyupagain : I tried to build the tensorflow as per the instructions and i am getting the following error:
ERROR: C:/tensorflow-r1.8/tensorflow/BUILD:502:1: Linking of rule '//tensorflow:libtensorflow_cc.so' failed (Exit 1107)
LINK : warning LNK4044: unrecognized option '/pthread'; ignored
LINK : warning LNK4044: unrecognized option '/ldl'; ignored
LINK : warning LNK4044: unrecognized option '/lpthread'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : warning LNK4044: unrecognized option '/ldl'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
**tensorflow/tf_exported_symbols_msvc.lds : fatal error LNK1107: invalid or corrupt file: cannot read at 0x2B015
Target //tensorflow:libtensorflow_cc.so failed to build
Use --verbose_failures to see the command lines of failed build steps.**
INFO: Elapsed time: 2124.002s, Critical Path: 1350.81s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 859 processes: 859 local.
FAILED: Build did NOT complete successfully.
I also got error when i tried to add the below highlighted line:
 "//tensorflow:windows": [],
       "//tensorflow:windows": [
           **"-def:" +  # This line must be directly followed by the exported_symbols_msvc.lds file**
            "$(location //tensorflow:tf_exported_symbols_msvc.lds)",
       ],
So i removed the line and tried to run the program

**Comment by HackersSpirit** [comment]
@gittyupagain @Steroes : 
I have tried to implement the solution as mentioned by you.
But still getting an error message.
**For Ex: Consider one of the error messages**
main.obj:-1: error: LNK2019: unresolved external symbol "public: __cdecl tensorflow::ops::MatMul::MatMul(class tensorflow::Scope const &,class tensorflow::Input,class tensorflow::Input,struct tensorflow::ops::MatMul::Attrs const &)" (??0MatMul@ops@tensorflow@@QEAA@AEBVScope@2@VInput@2@1AEBUAttrs@012@@Z) referenced in function main

But using approach mentioned i have linked the symbols to tensorflow_cc.so file:
Please have a look on the exported symbols of tensorflow_cc.so file:

 346  159 001E4270 ?TransposeA@Attrs@MatMul@ops@tensorflow@@QEAA?AU1234@_N@Z
 347  15A 001EECC0 ?TransposeA@MatMul@ops@tensorflow@@SA?AUAttrs@123@_N@Z
 348  15B 001E4280 ?TransposeB@Attrs@MatMul@ops@tensorflow@@QEAA?AU1234@_N@Z

I think the following link is present in the file still its giving an error message

**Comment by HackersSpirit** [comment]
@guikarist : Currently i am working with qt creator. I will have to look into building the libray using visual studio

**Comment by guikarist** [comment]
@HackersSpirit It is what I have to do, too.
I have asked a [question](https://stackoverflow.com/questions/53809398/how-to-program-with-c-api-library-on-windows) on stackoverflow, and I hope people with similar problems can work together to solve it.

**Comment by Steroes** [comment]
Well, to summarize my TensorFlow journey: Here is the build script I use to compile it with bazel. 
Directory structure:
tensorflow/
   bin
   build (build.ps1)
   source (tensorflow v.1.11.0)

- Place build.ps1 in build dir.
- Patch for symbols based on earlier post.
- Use FindTensorFlow.CMake file to find the TensorFlow package.
See zip file for contents. This is how I got it to work for the inference example from https://github.com/PatWie/tensorflow-cmake/tree/master/inference/cc.
[tf_changes_msvc.zip](https://github.com/tensorflow/tensorflow/files/2687763/tf_changes_msvc.zip)

**Comment by guikarist** [comment]
> Well, to summarize my TensorFlow journey: Here is the build script I use to compile it with bazel.
> Directory structure:
> tensorflow/
> bin
> build (build.ps1)
> source (tensorflow v.1.11.0)
> 
> * Place build.ps1 in build dir.
> * Patch for symbols based on earlier post.
> * Use FindTensorFlow.CMake file to find the TensorFlow package.
>   See [tf_changes_msvc.zip](https://github.com/tensorflow/tensorflow/files/2687763/tf_changes_msvc.zip)
>   for contents. This is how I got it to work for the inference example from https://github.com/PatWie/tensorflow-cmake/tree/master/inference/cc.

It is extremely wonderful! But I haven't tested the script. Where does the zip file come from?

**Comment by Steroes** [comment]
@guikarist I created the zip/scripts myself. Gathered from all kinds of sources like github and StackOverflow. It took me 5 weeks fulltime to get it working on windows, Ubuntu 14 and 16 and an old CentOs linux machine. Also have the bash Linux build script if someone is in need.

**Comment by guikarist** [comment]
@Steroes What a big job! I have read the whole script, now I have some questions:

1. Visual Studio is one of the requirements of your script, right?
1. I found that your script does not add support for CUDA. So I just need to add some other environment variables if I need CUDA? If so, where do you find the exact name of these variable? I tried but found no official ones.

Thank you!

**Comment by Steroes** [comment]
@guikarist 
1. Indeed, I use VS Community 2015 Update 3
2. I don't need CUDA indeed, so I disabled it. If you look into the configure.py script located in the tensorflow source code, then you can find the TF_** variables, which can be set as environment variables. There are also TF_ variables about CUDA. You can set them in the script to the needed value.

**Comment by guikarist** [comment]
@gittyupagain Is there any to overcome it and export all the symbols into the DLL? (e.g. by dividing the DLL file to several smaller ones)

**Comment by mnboos** [comment]
> You should not be building libtensorflow_cc.so on windows.

@gunan Could you please explain that a little further? Why should we not build that and:

> But what is the main target for the c++ library?

Thanks.

**Comment by Steroes** [comment]
> @mnboos I think I may be wrong about not building libtensorflow_cc.so on windows.
> 
> @meteorcloudy could you provide a summary of how to build libtensorflow_cc.dll on windows?
> Maybe a short script, or a list of commands and finally where the dll gets generated?

See: https://github.com/guikarist/tensorflow-windows-build-script

**Comment by meteorcloudy** [comment]
@Steroes 's solution looks good to me

**Comment by jackyko1991** [comment]
@gittyupagain it is nice to find your export C++ symbol method here. However as tf evolves to 2.0, the old cc API fadeout and I am trying to keep that up-to-date with this PR https://github.com/tensorflow/tensorflow/pull/26152

In the past necessary exported symbols can be found with the cmake contrib python file, at current status all tf library are built via bazel, and C++ symbols are exported with this [file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tf_exported_symbols.lds)

from your description an extra MSVC symbol is needed, could you provide the previous one that you are using as a reference?

At present stage most of the core symbols are not exported, my current solution is to copy all compiled libs and linking them all to the executable but still get quite a lot of problem for C++ API to be fully functional. Any help will be appreciated.

**Comment by ttdd11** [comment]
@Steroes I'm using your script to build tensorflow_cc.dll.

I get link errors when testing in my app. I added the symbols to tf_exported_symbols_msvc and place that file in source->tensorflow along with tf_exported_symbols and other files. After recompiling I get the same link errors. Is this the correct file location? Doesn't look like my changes to this file are sticking or something.

**Comment by guikarist** [comment]
@ttdd11 You didn't apply the patch my script applied automatically. (e.g. [for Tensorflow 1.12.0](https://github.com/guikarist/tensorflow-windows-build-script/blob/master/patches/cpp_symbol.1.12.0.patch))

**Comment by ttdd11** [comment]
@guikarist very correct thanks!

**Comment by JasonzhouCV** [comment]
@gittyupagain hi ,  it seems the BUILD file is version-specific ， could u explain how to find that build file  and how to modify?  i found the build file under tensorflow is quite different compared with yours. thx a lot!
