### ISSUE TITLE
GPU: tf.Session() needs 1-3 minutes at first start

### ISSUE THREAD

**Issue by Tockra** [tensorflow/tensorflow#22043]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux powerai 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 20:00:40 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux

- **TensorFlow installed from (source or binary)**:
source (R1.10)
- **TensorFlow version (use command below)**:
R1.10
- **Python version**:
3.5.2
- **Bazel version (if compiling from source)**:
1.15.2
- **GCC/Compiler version (if compiling from source)**:
5.4.0 20160609 
- **CUDA/cuDNN version**:
CUDA 9.0, cuDNN 7.1
- **GPU model and memory**:
4 x  Tesla P100-SXM2-16GB
- **Exact command to reproduce**:
import tensorflow as tf
sess = tf.Session()

### Describe the problem

Every first time I start a tensorflow session, it needs 1-3 minutes to finish. 
It freezes at the point "2018-09-04 08:32:04.920181: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0, 1, 2, 3"

After waiting and restarting the python script it works in 1-5 seconds.

### Source code / logs
There is no additional source code or loginformation.

**Comment by sjperkins** [comment]
Its likely jit compiling the binary PTX up to your device's compute capacity. See for e.g. https://devtalk.nvidia.com/default/topic/810047/ptx-compute-2-0-not-forward-compatible-with-gtx-970-/

**Comment by Tockra** [comment]
I don't know how this link should solve the issue ?

**Comment by sjperkins** [comment]
Tensorflow binaries are compiled against specific compute capabilities (3.5 and 5.2 IIRC). If you your device is a different compute capability, the PTX is jit-compiled to your device's compute capability. Since there is a great deal of CUDA code, this initially takes some time, but I believe its a once off thing.

**Comment by Tockra** [comment]
It's 6.0

**Comment by toddpi314** [comment]
Seeing the 970 cause the JIT rebuild in cycles, as if the delay is something that get's GC'd. Kind of adds some lame delays waiting for the GPUs to be accessible.
