### ISSUE TITLE
Wheel not supported Python3.5 

### ISSUE THREAD

**Issue by GrandathePanda** [tensorflow/tensorflow#2205]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: ArchLinux x64 Anaconda Environment

Installed version of CUDA and cuDNN: CPU Only Version
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
pip 8.1.1 from /opt/conda/envs/AI_Playground/lib/python3.5/site-packages (python 3.5)

2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
Tensorflow is not yet Installed
If installed from sources, provide the commit hash:

### Steps to reproduce
1. Install anaconda
2. Create Python3.5 environment
3. Follow tensorflow install guide for Anaconda

### What have you tried?
1. The command the tutorial provides to create the env : 

$ conda create -n tensorflow python=3.5

and then the command:

 pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl

reference different c python versions 3.5 and c python 3.4 respectively.

I tried tweaking the version in the link to cp35 in both instances which resulted in a 404 error from the pip script. Which I kind of expected. 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by Froskekongen** [comment]
I suspect that this has to do with the wheel you are specifying is for python3.4. However, it's fairly easy to build from source, if no wheel for python3.5 exists on the storage server.

**Comment by GrandathePanda** [comment]
Yeah that's exactly what I figured, I was more concerned that the tutorial specified anaconda with python3.5 and the wheel they tell you to use is their 3.4 build. Since it doesn't seem they have a 3.5 version for the wheel file I figured I'd bring it to their attention. A small oversight, but I imagine it'll cause issues for a number of people who use the tutorial.

**Comment by vladfi1** [comment]
This just bit me today. I would definitely appreciate a python 3.5 wheel, as I'm working on a system with only python 3.5.

**Comment by aam-at** [comment]
You can install provided wheel for python 3.5.
First, you download locally whl for python 3.4.
After that, you rename tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl to smth like tensorflow-0.8.0-cp35-none-linux_x86_64.whl

I hope this helps!

**Comment by roryhr** [comment]
Part of the problem is the Conda installation instructions are incorrect. It says to create a new virtual environment with Python 3.5 but the wheel is for 3.4.

**Comment by akors** [comment]
Manually downloading and renaming works for me, so thanks @aam-at !
However, could the the TensorFlow team create wheels for Python3.5 as well? That would be very nice :)

**Comment by xksteven** [comment]
Manually renaming it did not work for me.

sudo pip3 install ./tensorflow-0.8.0-cp35-none-linux_x86_64.whl

Gave me the same error:
tensorflow-0.8.0-cp35-none-linux_x86_64.whl is not a supported wheel on this platform.

On Ubuntu 16.04

Anything else that you did?

**Comment by akors** [comment]
@xksteven 
You can try renaming it to: `tensorflow-0.8.0-py3-none-any.whl`. This worked for me.

**Comment by xksteven** [comment]
@akors 
Thank you! That did the trick.

**Comment by caisq** [comment]
With PR https://github.com/tensorflow/tensorflow/pull/2585, we now have whl files built and tested nightly. The links to the whl files and build history can be found in the main README.md: 
https://github.com/tensorflow/tensorflow/

**Comment by NicoBuntu** [comment]
Merci @akors il m'a fallu 2 jours pour trouver cette solution j'ai juste renommé la version 0.8.0 en 1.2.0 donc ça m'a fait
`tensorflow-1.2.0-py3-none-any.whl`
