### ISSUE TITLE
Build Tensorflow on RHEL 7 with GPU CUDA support

### ISSUE THREAD

**Issue by zacharymostowsky** [tensorflow/tensorflow#22053]
Was searching high and wide for a guide that included all the steps to install TF on Rhel. Posting the solution that worked for me.

**Comment by zacharymostowsky** [comment]
First Install actions for CUDA 9.2, cuDNN 7.2
Mostly followed from: http://kehang.github.io/tools/2017/03/31/install-CUDA-cuDNN-on-Red-Hat/


Need wget to download drivers and git, etc.
`sudo yum -y install wget git nano python-devel patch numpy python-pip`

Pre-install actions
```
sudo yum -y install pciutils
sudo yum -y install gcc
sudo yum -y install kernel-devel-$(uname -r) kernel-headers-$(uname -r)
```

Python packages
`sudo pip install enum34 keras`

# CUDA 9.2

Get the drivers and install
`wget https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers/cuda-repo-rhel7-9-2-local-9.2.148-1.x86_64`



Rename to .rpm
`mv cuda-repo-rhel7-9-2-local-9.2.148-1.x86_64 cuda-repo-rhel7-9-2-local-9.2.148-1.x86_64.rpm`

```
sudo rpm -i cuda-repo-rhel7-9-2-local-9.2.148-1.x86_64.rpm
sudo yum clean all
sudo yum -y install cuda
```



Install cuDNN
Need an Nvidia developer account to download from Nvidia website
Untar
`tar -zxf cudnn-9.2-linux-x64-v7.2.1.38.tgz`

```
cd cuda

sudo cp -av lib64/* /usr/local/cuda/lib64/
sudo cp -av include/* /usr/local/cuda/include/
```

```
export LD_LIBRARY_PATH=/usr/local/cuda/lib64/:$LD_LIBRARY_PATH
export LIBRARY_PATH=/usr/local/cuda/lib64/:$LIBRARY_PATH
```

Install bazel, followed from: https://gist.github.com/gentaiscool/a628fab5cd98953af7f46b69463394b3

Add repo
```
cd /etc/yum.repos.d/
sudo wget https://copr.fedorainfracloud.org/coprs/vbatts/bazel/repo/epel-7/vbatts-bazel-epel-7.repo
```

```
cd
sudo yum -y install bazel
```

Install TF from source

First, lets just install TF from python standard lib so we can get all the dependencies.
`sudo pip install tensorflow-gpu`

Now uninstall so we can build from source
`sudo pip uninstall tensorflow-gpu`

# Clone repo
`git clone https://github.com/tensorflow/tensorflow`

# Configure
```
cd tensorflow
./configure
```
Answer these for the prompts. May need to change. A couple of 'gotchas' listed below.
# PYTHON_INCLUDE_PATH - location of Python.h - https://github.com/tensorflow/tensorflow/issues/327
# Fill in these answers to the prompts:
# Only enter what is inside quotes
# To accept a default press enter
*1. Python Path: DO NOT ACCEPT DEFAULT, input: "/usr/bin/python2.7"
2. Python Library Path: Default: "/usr/lib/python2.7/site-packages"
3. jemalloc: no (n)
4. GCS Support: Yes (y) - not needed right now but perhaps in future
5. HDFS Support: No
6. AWS Support: No
7. Kafka Support: No
8. XLA JIT Support: No
9. GDR Support: No
10. VERBS Support: No
11. OpenCL SYCL Support: No
*12. CUDA Support: Yes
*13. CUDA Version: "9.2"
14. CUDA Lib Location: Accept Default: "/usr/local/cuda"
*15. cuDNN Version: "7.2"
16. cuDNN Lib Path: Accept Default: "usr/local/cuda"
17. TensorRT Support: No
18. NCCL Version: "1.3"
19. Accept Default
20. clang CUDA compiler: No
21. Default: "/usr/bin/gcc"
22. Tensor MPI: No
23. Optimization Flafs: Default
24. Interactively configure WORKSPACE: No

# Build with GPUs
`bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

# Without GPUs
`bazel build -c opt //tensorflow/tools/pip_package:build_pip_package`

Build whl file
`bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg`

Install - look in tmp/tensorflow_pkg/ directory to find <your whl file>
`sudo pip install --upgrade /tmp/tensorflow_pkg/<your whl file>.whl`

Mine is
`sudo pip install --upgrade /tmp/tensorflow_pkg/tensorflow-1.10.0-cp27-cp27mu-linux_x86_64.whl`

May need to upgrade protobuf, although I did not have to !!! - https://gist.github.com/jorgemf/d2f3d85fadeb6e9d88ab00a06fbca0a2


Lets check Tensorflow can use GPU. Copy python code at link into python session.
https://www.tensorflow.org/guide/using_gpu

Check pytorch can see GPU
```
python2

> import torch
> torch.cuda.is_available()
```

The above should return true

# NOTES
# Do not start python and import tensorflow from inside the tensorflow folder cloned from github - won't be able to find some modules - https://github.com/tensorflow/tensorflow/issues/374
# Speed up build time for bazel by leveraging multiple CPU cores. Can use --jobs flag to specify num jobs - https://github.com/tensorflow/models/issues/195

Other Links:
https://github.com/tensorflow/tensorflow/issues/327 - python.h missing help link

**Comment by gauravkaila** [comment]
Thanks @zacharymostowsky for the solution. I found it quite helpful while installing cuda/cudnn/TensorFlow on RHEL7. 

One additional step that I had to do was to install third-party repository. 

`yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`

I followed this guide to get around a few errors

https://developer.download.nvidia.com/compute/cuda/9.2/Prod2/docs/sidebar/CUDA_Installation_Guide_Linux.pdf 

Again, thanks for your answer.
