### ISSUE TITLE
Integrating this framework into swift causing syntax errors

### ISSUE THREAD

**Issue by suneelkumargavara** [tensorflow/tensorflow#22051]
I am using this framework in a swift project and used a bridging header to implement some functionalities. I was included this framework with CocoaPods into my swift project. But while trying to build the project, there are so many syntax errors like #include not found, #include not found etc. I have been banging my head around this issue from past two days but no luck. The Xcode compiler is able to build if i am using an Objective C Project. Somebody please guide me to resolve the issue with swift project

Thanks in Advance

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by suneelkumargavara** [comment]
- i haven't written any custom code. I have created swift project and integrated tensor flow framework using CocoaPods. i have imported the objective C classes as well which you provided in examples section in GitHub project. After that i created one bridging header to imported the camera class into that.Then i tried to build the project and getting errors in header files of tensorflow framework.
- iOS platform, 
- iPhone device

**Comment by suneelkumargavara** [comment]
Removing the declared c++ variables on header file has done the trick.
