### ISSUE TITLE
Feature request: Implement SVD

### ISSUE THREAD

**Issue by quilby** [tensorflow/tensorflow#2207]
Feature request: Implement SVD

Like for example in Torch:
https://github.com/torch/torch7/blob/master/doc/maths.md#torchsvdresu-ress-resv-a--s-or-a

**Comment by mrry** [comment]
@rmlarsen, I'm assigning this to you because you mentioned there was a plan to add SVD this quarter. Feel free to reassign if someone else is doing the work....

**Comment by rmlarsen** [comment]
Hi, Just saw this after returning from vacation: Yes, I do intend to add this.

**Comment by sergulaydore** [comment]
I am working on this, too. What algorithm are you planning to use?

**Comment by rmlarsen** [comment]
I plan to add an op for dense, since-machine SVD using the divide-and-conquer in Eigen. For sparse it would be nice to implement something like the Lanczos algorithm in PROPACK (which I'm the author of), but I have no immediate plans to work on that.

**Comment by whitewhim2718** [comment]
This is a feature I would like to see, which would be necessary for implementing tensor networks as in http://arxiv.org/abs/1605.05775 in Tensorflow.

**Comment by rmlarsen** [comment]
Ops for computing the SVD of dense matrices or batches of matrices have been added: 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/linalg_ops.py#L479
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/linalg_ops.py#L522
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/svd_op.cc

**Comment by sergulaydore** [comment]
I am having trouble calling this function. I saved the new version as
linalg_ops_new. I am attaching the error I got. Can you please tell me what
I am doing wrong? What is the best way to call new ops in tensorflow?

Thanks,
Sergul

**Comment by sergulaydore** [comment]
I am comparing this with PCA implementation from scikit learn and the results don't seem to be consistent. Here is the results and code for a toy example. Can you please comment why the results might be different?

`# USING TENSORFLOW
import tensorflow as tf
sess = tf.InteractiveSession()
x_tf = tf.Variable([[0.0, 1.0, 0.0, 7.0, 0.0], [2.0, 0.0, 3.0, 4.0, 5.0], [4.0, 0.0, 0.0, 6.0, 7.0]])
x_tf.initializer.run()
s, u, v = tf.svd(x_tf, full_matrices = False)
u.eval()
# output: array([[-0.38829127, -0.91980982, -0.05638742],
#       [-0.53017205,  0.27301854, -0.80273181],
#       [-0.75375545,  0.28179872,  0.5936681 ]], dtype=float32)

# USING SCIKIT LEARN
import numpy as np
from sklearn.decomposition import PCA
pca = PCA(n_components=3, whiten = False)
x = np.array([[0.0, 1.0, 0.0, 7.0, 0.0], 
			  [2.0, 0.0, 3.0, 4.0, 5.0],
			  [4.0, 0.0, 0.0, 6.0, 7.0]])
pca.fit(x)
print pca.components_.transpose()
# output: [[ 0.44859172  0.28423808 -0.706726  ]
#          [-0.13301986  0.05621156 -0.34735227]
#          [ 0.12523156 -0.76362648 -0.44948593]
#          [-0.21650757  0.56529588 -0.281509  ]
#          [ 0.84765129  0.11560341  0.31400611]]`
