### ISSUE TITLE
Provide wheels for multiple versions of CUDA officially

### ISSUE THREAD

**Issue by tats-u** [tensorflow/tensorflow#22087]
Ubuntu 18.04, the latest LTS version, only supports CUDA 9.2, but there is no wheel available for that combination of CUDA and Linux.  This prevents servers where Ubuntu 16.04 are installed from upgrading to 18.04.

On the other hand, PyTorch and CuPy officially provides wheels multiple versions of CUDA.  TF may be the only deep learning framework that is available in PyPI and confines the version of CUDA to specific one.

Let Ubuntu 18.04 use TF without building from source and Ubuntu 16.04 upgrade to 18.04!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tats-u** [comment]
OS: Ubuntu 16.04/18.04
TF installed from: wheel (via pip)
CUDA: 9.0/9.2
cuDNN: 7.2

**Comment by martinwicke** [comment]
I agree that would be fantastic. However, changing CUDA versions often means changing drivers and code. We strongly believe that we should only release official builds that are thoroughly tested, and I we cannot properly test and release several CUDA/cuDNN versions. 

Note that while 18.04 switched the default CUDA version, you can simply request a different version of CUDA when installing with apt-get. Please see our installation instructions.
