### ISSUE TITLE
Word2vec overflows int32 corpus_size_

### ISSUE THREAD

**Issue by snakecharmer1024** [tensorflow/tensorflow#2209]
Hello, I'm trying to build a big word model, and I'm getting overflows in the corpus_size_ declared here
https://github.com/tensorflow/tensorflow/blob/e39d8feebb9666a331345cd8d960f5ade4652bba/tensorflow/models/embedding/word2vec_kernels.cc#L119

The error is being thrown here:

https://github.com/tensorflow/tensorflow/blob/e39d8feebb9666a331345cd8d960f5ade4652bba/tensorflow/models/embedding/word2vec_kernels.cc#L191

Because negative numbers are less than positive numbers. I'm going to change them to uint64 in my own build, if it doesn't cause problems should I make a PR?

**Comment by zheng-xq** [comment]
@snakecharmer1024, int64 is better than uint64 for size. 

Adding @zffchen78 to comment whether it is okay to int64. It is possible that you need to change several places to make this work.

**Comment by snakecharmer1024** [comment]
@zheng-xq I don't understand these things that well, why would you prefer signed to unsigned?

**Comment by zheng-xq** [comment]
In general, TensorFlow prefers int64 when large indices or size are needed. One reason is that the following code would work naturally. 

for (auto i = v_size - 1; i>=0; i--) {...}

**Comment by aselle** [comment]
Thank you for offering to create a pr. Unfortunately, changing from signed to unsigned often creates lots of subtle bugs (especially in the case @zheng-xq suggest). So for now I am closing this bug. Hopefully using int64 when you have more than 2^31 positive is a workable solution for you.
