### ISSUE TITLE
CTCLoss does not support half precision (float16/fp16)

### ISSUE THREAD

**Issue by npow** [tensorflow/tensorflow#22096]
I was trying to use `CTCLoss` with float16, and encountered a type exception in `python.framework.op_def_library._apply_op_helper `. In the [op definition](https://github.com/tensorflow/tensorflow/blob/294442996b2aeff00b1bfdc7e7169f7cb35bbf3d/tensorflow/core/ops/ops.pbtxt#L3568), it only lists `DT_FLOAT`.  Is there a particular reason that this op wasn't updated to support half precision in #1300?

```
  File "/nix/store/rnfj7g778synyrkr7qa8nx67sdmsr4xg-python3.6-tensorflow-1.7.0/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 533, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'inputs' of 'CTCLoss' Op has type float16 that does not match expected type of float32.
```

Have I written custom code: No
OS Platform and Distribution: Ubuntu 16.04
TensorFlow installed from: pip
TensorFlow version: 1.7
Bazel version: 0.10.1
CUDA/cuDNN version: 9.1
GPU model and memory: Tesla V100
Exact command to reproduce: N/A
Mobile device: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by npow** [comment]
@tensorflowbutler 

Have I written custom code: No
OS Platform and Distribution: Ubuntu 16.04
TensorFlow installed from: pip
TensorFlow version: 1.7
Bazel version: 0.10.1
CUDA/cuDNN version: 9.1
GPU model and memory: Tesla V100
Exact command to reproduce: N/A
Mobile device: N/A

**Comment by ebrevdo** [comment]
CTC loss calculation can be numerically unstable.  So it's better to keep it at least 32 bits.  Since it's only implemented on CPU, there's essentially no benefit to having a float16 version.
