### ISSUE TITLE
TensorFlow profiler timeline range

### ISSUE THREAD

**Issue by georgesterpu** [tensorflow/tensorflow#22103]
Hello,

I'm following the tf.profiler.Profiler guide to profile my code.
When generating the timelines, all of them except the first one are scaled in hundreds of years, rather than seconds.

There is something happening at year 0, then something going on after 583 years.
No, my DNN code is not that slow. 
![screenshot_2018-09-05_23-19-38](https://user-images.githubusercontent.com/6018251/45128332-5c24b680-b175-11e8-96f6-c5cc9abee2d4.png)
Running the latest stable version of everything.

Could you please recommend me a fix?
Thank you

**Comment by ppwwyyxx** [comment]
Looks like a duplicate of #20750.

**Comment by georgesterpu** [comment]
Indeed, apologies. I will close this one.

**Comment by ppwwyyxx** [comment]
The repro in #20750 only works on 2 GPUs somehow. Are you only using 1 GPU? If you can give a small repro with 1 GPU maybe that'll be easier to debug.

**Comment by georgesterpu** [comment]
There are two physical GPUs in my machine, but the launch script sets the `CUDA_VISIBLE_DEVICES` environment variable to use only one of them. Will post the code to reproduce the issue later this week.

**Comment by georgesterpu** [comment]
Hi @ppwwyyxx, the code is here: https://github.com/georgesterpu/Sigmedia-AVSR
You only have to set the `profiling` flag to True when instantiating the AVSR class.
