### ISSUE TITLE
Sharing a GPU between tensorflow and another cuda code.

### ISSUE THREAD

**Issue by mrvahdat** [tensorflow/tensorflow#2210]
Hello,

I am trying to run tensorflow and another cuda code in the same python script. My script is coded such that it iteratively uses the other cuda code to generate bunch of samples and then it uses tensorflow to process them. The tensoflow session is always open while doing these iterations.

The problem is that in tensorflow 0.7, I get the following error when the session is closing (exiting python):

F tensorflow/stream_executor/cuda/cuda_driver.cc:302] current context was not created by the StreamExecutor cuda_driver API: 0x2eb5c50; a CUDA runtime call was likely performed without using a StreamExecutor context

And, in tensorflow 0.8, I get another error in middle of run:

*** Error in `python': munmap_chunk(): invalid pointer: 0x00007ffea63b7380 ***
Aborted (core dumped)

I have modified my other cuda code to use cuda's Stream Executor context but this did not solve any of these issues. I'm also pretty sure my cuda code does not have any memory leak. If I replace my cuda code with its cpu version or the tensorflow operations with numpy counterparts every thing works perfectly. I have also limited gpu memory for TF using: 

tf.GPUOptions(per_process_gpu_memory_fraction=0.5)

I am wondering if we actually can share a single GPU between tenorflow and another cuda code in the same script? If so, is there any particular protocol that I should follow.

**Comment by sjperkins** [comment]
Off the top of my head, you may need to explicitly create, push and pop a CUDA context for your own code. Otherwise, you may end up using Tensorflow's context with it's own streams etc.

**Comment by girving** [comment]
Adding @zheng-xq.  As noted in https://github.com/tensorflow/tensorflow/issues/916, sharing a GPU between TensorFlow and other code is not generally supported.  However, you mentioned that you modified your other code to use stream executor, which seems like it has a chance.  Are you saying you got the same error after switching to stream executor, or did the error change?

**Comment by zheng-xq** [comment]
@sjperkins is correct. If you want to share the same GPU between TensorFlow and other Cuda library, you have to be very careful. No Cuda Runtime API is safe. Either you call stream-executor, or call Cuda Driver API, and manage the context yourself. Every time when you are done with your Cuda work, restore the context back to the previous state, because that is what stream-executor implicitly expects.

**Comment by aselle** [comment]
Closing this issue as it is as supporting shared use of GPU is not currently or planned to be supported.

**Comment by sstirlin** [comment]
I know this is closed, but just in case anybody needs a tip:

One possible workaround is to launch the Tensorflow code in a separate worker thread.  This isolates Tensorflow's CUDA context and allows it to coexist peacefully with Caffe (and other CUDA-enabled libraries).  

I'm using python's `threading` and `Queue` libraries for this, and no complaints (although they're still battling for memory, but that's a different story).
