### ISSUE TITLE
tf.add_check_numerics_ops() adds ops to while_loop frame

### ISSUE THREAD

**Issue by hexahedria** [tensorflow/tensorflow#2211]
When I construct a graph that contains a tf.while_loop, and then try to call tf.add_check_numerics_ops(), I get an InvalidArgumentError.

Given the code

``` python
import tensorflow as tf

def test():
    i = tf.constant(0, tf.float32)
    c = lambda i: tf.less(i, 10)
    b = lambda i: tf.add(i, 1)
    r = tf.while_loop(c, b, [i])

    check = tf.add_check_numerics_ops()

    with tf.Session() as sess:
        print sess.run([r,check])
```

I get the error

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "minimal_bug_example.py", line 12, in test
    print sess.run([r,check])
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: All inputs to node CheckNumerics_1 must be from the same frame.
```

I'm running Tensorflow installed from pip, version 0.8.0. As far as I can tell, this is caused by the while_loop creating a new control flow context, but the check numerics op living outside that context.

**Comment by hexahedria** [comment]
One potential dirty fix I figured out is to change [this line](https://github.com/tensorflow/tensorflow/blob/e39d8feebb9666a331345cd8d960f5ade4652bba/tensorflow/python/ops/numerics.py#L65) to
```python
if output.dtype in [dtypes.float32, dtypes.float64] and output.op._get_control_flow_context() == ops.get_default_graph()._get_control_flow_context():
```
which makes sure to only add check_numerics ops on ops in the outermost context. There are probably better ways to do it, and I haven't looked to closely at the code, but this worked as a temporary workaround for me.

**Comment by zheng-xq** [comment]
I would not use tf.add_check_numerics_ops in this case, since it doesn't know what are the hidden nodes that shouldn't be checked. 

Add tf.check_numerics to the node that you want to check it yourself.

**Comment by hexahedria** [comment]
I was attempting to use add_check_numerics_ops for debugging purposes. One of the models I was building was spitting out NaNs and I wanted to figure out where they were coming from. Ideally I'd like it to check within the while loop too, but that doesn't seem to work.

**Comment by zheng-xq** [comment]
You should be able to use tf.check_numerics within the loop. It is like an
identity op.

**Comment by akshaybetala** [comment]
I am also getting an error message similar to this. But I am not able to understand exactly what does it mean

**Comment by girving** [comment]
@yuanbyu: Should I mark this contributions welcome?  It seems like it would be nice if `tf.add_check_numerics_ops` just did the right thing in this case.

**Comment by yuanbyu** [comment]
Yes, sounds like a good idea.

**Comment by alquraishi** [comment]
I'm getting this error as well, and I'm not explicitly using a while_loop, although my model does have an RNN in it which may explain this.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by albertz** [comment]
I think this should be reopened. `tf.add_check_numerics_ops()` currently is useless when there is a loop or other custom context in the computation graph.
