### ISSUE TITLE
[Bug] tf.nn.depthwise_conv2d fails with AttributeError

### ISSUE THREAD

**Issue by manu291** [tensorflow/tensorflow#22110]
### System information
- **Have I written custom code**: yes
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from**: binary
- **TensorFlow version**: v1.10.1-0-g4dcfddc5d1
- **Python version**: 2.7.12
- **CUDA/cuDNN version**: 9.0/7.1.4
- **GPU model and memory**: GTX 1070

### Describe the problem
`tf.nn.depthwise_conv2d` fails when the shape of the input is not known statically and the data format is 'NCHW' and the dilation rate is larger than 1.

### Source code / logs
Reproducible test case:
```
import tensorflow as tf
sh = tf.placeholder(dtype=tf.int32, shape=[4])
img = tf.ones(sh)
k = tf.ones([1, 1, 1, 1])
t = tf.nn.depthwise_conv2d(img, k, [1, 1, 1, 1], 'VALID', rate=[2, 1], data_format='NCHW')
```
Traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/manu/.local/lib/python2.7/site-packages/tensorflow/python/ops/nn_impl.py", line 461, in depthwise_conv2d
    op=op)
  File "/home/manu/.local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 364, in with_space_to_batch
    return new_op(input, None)
  File "/home/manu/.local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 520, in __call__
    return self.call(inp, filter)
  File "/home/manu/.local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 514, in _with_space_to_batch_call
    output_shape[1] = filter.shape[-1]
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by yongtang** [comment]
Added a PR #22139 for the fix.

**Comment by manu291** [comment]
As requested, system information with all fields filled out.

### System information
- **Have I written custom code**: yes
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **Mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version**: v1.10.1-0-g4dcfddc5d1
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0/7.1.4
- **GPU model and memory**: GTX 1070
- **Exact command to reproduce**: N/A
