### ISSUE TITLE
DirectSessionRegistrar not found in libraries

### ISSUE THREAD

**Issue by tiny-app** [tensorflow/tensorflow#2216]
tensorflow branch r0.7    android-ndk-r10e    bazel-0.2.1

I build the android:tensorflow_demo with the command below:

=> bazel build //tensorflow/examples/android:tensorflow_demo --verbose_failures

The build is successful, and it generate some files:
	
=> ??????????????.apk
=> tensorflow_demo.so
=> libandroid_tensorflow_lib.a
=> libre2.a and so on
	
I want to use Windows Android SDK/NDK to develop Android APP with these static libraries.

When I initialize the tensorflow session, it prompt that direct session not found.

Then I browse the code tensorflow\core\common_runtime\direct_session.cc.
At the tail, I find:

"""
class DirectSessionFactory : public SessionFactory {
 public:
  DirectSessionFactory() {}

  Session* NewSession(const SessionOptions& options) override {
    std::vector<Device*> devices;
    DeviceFactory::AddDevices(options, "/job:localhost/replica:0/task:0",
                              &devices);
    return new DirectSession(options, new DeviceMgr(devices));
  }
};

class DirectSessionRegistrar {
 public:
  DirectSessionRegistrar() {
    SessionFactory::Register("DIRECT_SESSION", new DirectSessionFactory());
  }
};
static DirectSessionRegistrar registrar;
"""

nm libandroid_tensorflow_lib.a | grep "???"
nm direct_session.o | grep "???"

I can grep DirectSessionFactory from libandroid_tensorflow_lib.a/direct_session.o, but not DirectSessionRegistrar.

It seems that libandroid_tensorflow_lib.a/direct_session.o does not contain DirectSessionRegistrar.

What can i do?

**Comment by zheng-xq** [comment]
@mrry, any idea here?

**Comment by andrewharp** [comment]
Hi, did you try the alwayslinks=1 and linkopt workarounds suggested in https://github.com/tensorflow/tensorflow/issues/2047?

Another potential solution is to add an explicit reference to DirectSession in the code to make sure it's not getting stripped out.

It'd be nice to know the root cause of why this is happening to people occasionally, of course, but I've never been able to reproduce.

**Comment by andrewharp** [comment]
Another thing worth checking: how much free disk space and memory does your system have? I've seen cases where Bazel "forgets" that it has successfully built entire .so libraries when running low on resources -- I wouldn't be terribly surprised if the same thing happened for .o files.

Can you do a blaze clean, then try building with `--jobs=1 -s` and attach the entire build log here please?

**Comment by mrry** [comment]
I'm not a linker expert, but it looks like the problem might be discussed in this SO question: [Static initialization and destruction of a static library's globals not happening with g++](http://stackoverflow.com/q/1804606/3574081). Perhaps there are some linker options that you need (e.g. `-Wl,--whole-archive` as suggested in [this comment](http://stackoverflow.com/questions/1804606/static-initialization-and-destruction-of-a-static-librarys-globals-not-happenin#comment1692937_1804618))?

**Comment by mrry** [comment]
A colleague suggests adding the following option to your build command for the code that uses `libandroid_tensorflow_lib.a`: `linkopts=["-Wl,-no-as-needed"]`.

**Comment by tiny-app** [comment]
@zheng-xq @andrewharp @mrry 

It my fault, now it's ok.

I develop under Windows, and I use Android.mk to build.

I must use LOCAL_WHOLE_STATIC_LIBRARIES instead of LOCAL_STATIC_LIBRARIES to link these libraries. And it also depend on android-ndk-r10e, just like bazel build.

LOCAL_WHOLE_STATIC_LIBRARIES := \
                                android_tensorflow_lib \
                                protobuf re2 \
                                protobuf_lite \
                                protos_all_cc

Now I can develop APP under Windows with Eclipse and Android.mk.

thanks.
