### ISSUE TITLE
Wrap cuSOLVER in stream

### ISSUE THREAD

**Issue by c0g** [tensorflow/tensorflow#2217]
I have started to wrap NVIDIA's cusolver library (LAPACK-like) for my work on #367. Is this something the TF team would consider supporting/helping with? I have so far only wrapped potrf, but adding more functions should be fairly easy now that I have done the long-winded bit.

[Its in my fork](https://github.com/c0g/tensorflow).

**Comment by zheng-xq** [comment]
A good way to start with tf.contrib. Once it matures enough the TF team would move it to the core.

**Comment by c0g** [comment]
Okay, sounds good. Is there an easy way to tell Bazel to build with a contrib/ masking files in Tensorflow proper? Apologies if this is documented somewhere obvious!

**Comment by zheng-xq** [comment]
Here are a few examples in tf.contrib.

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/README.md

Once you created your own directory, you need to create your own BUILD file to set up your target and dependencies. Then bazel can build it like any other target.

**Comment by girving** [comment]
@c0g: Thanks, we look forward to PRs!  @rmlarsen: Do you have any comments?

**Comment by c0g** [comment]
Hi, sorry my silence in this - I've been ill. I have not been able to puzzle out how to integrate my changes inside of tf.contrib - they're changes to fairly key things like stream.h, the cuda stuff in third party, etc. It seems like most of the other projects inside of contrib are more modular and are mainly python ops.

What I have been trying to do is make a BUILD file such that I could write:

`bazel build -c opt --config=cuda //tensorflow/contrib/solver_stream:build_pip_package` 

and have that build the pip package in exactly the same way as a normal build, but with the files I have in the directory structure masking the original tensorflow files. Unfortunately I have got nowhere. 

I can't think of a way to make my changes part of contrib without some mechanism like this - for example, how can I test and install my work without building a pip package?

**Comment by zheng-xq** [comment]
@c0g, all the stream_executor has to directly go to the stream_executor source. And we will ask the owners from stream_executor to review them. 

In general, once you set up your ops and BUILD file, any project that wants to use your op can depends on it directly, in addition to normal TensorFlow dependency. 

If you want really your op to be available in the default TensorFlow pip_package, once it is mature enough, you can do it to here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/BUILD#L24

**Comment by alexggmatthews** [comment]
@girving @rmlarsen do the developers at Google have any plans in this specific direction or for GPU linear algebra solvers in general? Having spoken to @c0g  it looks like he will be unable to spend more time on this thread.

**Comment by rmlarsen** [comment]
I think this would be a great addition to TF of somebody would have the cycles to work on it. I'm not sure the TF team has cycles to work on this in the short term, but would be happy to advice and review PRs.

**Comment by zheng-xq** [comment]
Adding stream-executor owner henline@ here. 

One more thing, we are in the process of stream-executor of getting rid of our forked version of stream-executor. Stream-executor will be officially released as LLVM subproject: parallel-libs. And TensorFlow will eventually switch to that. We don't have a specific timeline yet. But if this development takes a while, it is helpful to pay attention to that transition. 

See this announcement for more details: 

http://lists.llvm.org/pipermail/llvm-dev/2016-June/101028.html

**Comment by alexggmatthews** [comment]
@henline @zheng-xq .Great. Keen to here of any developments.

**Comment by alextp** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
