### ISSUE TITLE
keras.layers.Conv3DTranspose error when reused

### ISSUE THREAD

**Issue by kor01** [tensorflow/tensorflow#22187]
Version 1.10

file: tensorflow/python/keras/layers/ convolution.py

line: 1000

problem: 

input_spec is modified every time the module is called; 
input_spec uses dynamic shape causes error in shape checker when the layer is reused

**Comment by kor01** [comment]
solution: delete line 1000, input_spec should only be modified in constructor or build function

**Comment by tatianashp** [comment]
@kor01 Thank you for your suggestion. Would you be interested in submitting a PR?
/cc @fchollet

**Comment by kor01** [comment]
> @kor01 Thank you for your suggestion. Would you be interested in submitting a PR?
> /cc @fchollet

OK, I'll submit a PR.

**Comment by tatianashp** [comment]
Great. Thank you! Please post here once you do.

**Comment by harshini-gadige** [comment]
@kor01 Hi, any update on the PR ?

**Comment by SushanthIkshwaku** [comment]
@harshini-gadige This issue seems to be fixed. Can you update the status?
Version: r1.10 :
https://github.com/tensorflow/tensorflow/blob/4dcfddc5d12018a5a0fdca652b9221ed95e9eb23/tensorflow/python/keras/layers/convolutional.py#L997

Version master:
https://github.com/tensorflow/tensorflow/blob/7bcbcc1392516a2b2d7a7abae2ccce7091c8dae3/tensorflow/python/keras/layers/convolutional.py#L1070

**Comment by harshini-gadige** [comment]
> @harshini-gadige This issue seems to be fixed. Can you update the status?
> Version: r1.10 :
> [tensorflow/tensorflow/python/keras/layers/convolutional.py](https://github.com/tensorflow/tensorflow/blob/4dcfddc5d12018a5a0fdca652b9221ed95e9eb23/tensorflow/python/keras/layers/convolutional.py#L997)
> 
> Line 997 in [4dcfddc](/tensorflow/tensorflow/commit/4dcfddc5d12018a5a0fdca652b9221ed95e9eb23)
> 
>  self.input_spec = InputSpec(ndim=5, axes={c_axis: inputs_shape[c_axis]}) 
> Version master:
> [tensorflow/tensorflow/python/keras/layers/convolutional.py](https://github.com/tensorflow/tensorflow/blob/7bcbcc1392516a2b2d7a7abae2ccce7091c8dae3/tensorflow/python/keras/layers/convolutional.py#L1070)
> 
> Line 1070 in [7bcbcc1](/tensorflow/tensorflow/commit/7bcbcc1392516a2b2d7a7abae2ccce7091c8dae3)
> 
>  def call(self, inputs):

Sure. Closing the issue.
