### ISSUE TITLE
Add HDFS support

### ISSUE THREAD

**Issue by liumilan** [tensorflow/tensorflow#2218]
Becase of massive data,data is stored in hdfs
Can tensorflow support to read from hdfs directly?

**Comment by alexatknit** [comment]
use pyspark and run tensorflow in a reduce operation?

**Comment by liumilan** [comment]
I'd like to use the second way.
iterate over the resulting query ,
Can it possbile read minibatch from data files,like caffe,What API should I use?

**Comment by alexatknit** [comment]
I believe that spark has a to_iterable operation: 
http://spark.apache.org/docs/latest/api/python/pyspark.html#pyspark.RDD.toLocalIterator

pyspark has the tools available to preprocess the data in an RDD before returning it to the current python process, use this command to return a random subset of the current RDD:
http://spark.apache.org/docs/latest/api/python/pyspark.html#pyspark.RDD.sample

**Comment by liumilan** [comment]
Can it possbile to use other ways?No using the spark.
Becasue i am not familar with spark

**Comment by phvu** [comment]
I think we can write a custom data reader, that reads data from HDFS, which seems doable: https://www.tensorflow.org/versions/r0.8/how_tos/new_data_formats/index.html

Any plan for this? I might be able to help with implementation.

**Comment by itsmeolivia** [comment]
I'm working on this.  The testing is a little tricky to integrate but it should be done soon :)

**Comment by ajayjain** [comment]
Are there any updates on this? Thanks!

**Comment by tobegit3hub** [comment]
@itsmeolivia Are you still working on this?  We're looking forward to this feature as well.

**Comment by sergulaydore** [comment]
@alexatknit When you say to use Spark, do you mean to input batches of rdd's as a placeholder?

**Comment by llhe** [comment]
@itsmeolivia Will Kerberos be supported for the HDFS integration?

**Comment by bhack** [comment]
See also https://github.com/tensorflow/tensorflow/issues/2655#issuecomment-238602661

**Comment by jhseu** [comment]
HDFS support is in master and will be in the 0.11 release. There'll be a how to on the website that's live with 0.11, but I've copied and pasted it below. If you run into any bugs, file an issue and assign it to me.

I haven't tested Kerberos support. Patches are welcome if any code is needed for that:

> To use HDFS with TensorFlow, change the file paths you use to read and write
> data to an HDFS path. For example:
> 
> ```python
> filename_queue = tf.train.string_input_producer([
>     "hdfs://namenode:8020/path/to/file1.csv",
>     "hdfs://namonode:8020/path/to/file2.csv",
> ])
> ```
> 
> If you want to use the namenode specified in your HDFS configuration files, then
> change the file prefix to `hdfs://default/`.
> 
> When launching your TensorFlow program, the following environment variables must
> be set:
> 
> *   **JAVA_HOME**: The location of your Java installation.
> *   **HADOOP_HDFS_HOME**: The location of your HDFS installation. You can also
>     set this environment variable by running:
> 
> ```shell
> source $HADOOP_HOME/libexec/hadoop-config.sh
> ```
> 
> *   **LD_LIBRARY_PATH**: To include the path to libjvm.so. On Linux:
> 
> ```shell
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JAVA_HOME/jre/lib/amd64/server
> ```
> 
> *   **CLASSPATH**: The Hadoop jars must be added prior to running your
>     TensorFlow program. The CLASSPATH set by
>     `$HADOOP_HOME/libexec/hadoop-config.sh` is insufficient. Globs must be
>     expanded as described in the libhdfs documentation:
> 
> ```shell
> CLASSPATH=$($HADOOP_HDFS_HOME/bin/hdfs classpath --glob) python your_script.py
> ```
>

**Comment by PhoenixDai** [comment]
If I want to access data in HDFS (remote cluster) that's outside my GPU machine (local), do I still need to install and configure HDFS locally before I can point the file path like:
```
filename_queue = tf.train.string_input_producer([
    "hdfs://namenode:8020/path/to/file1.csv",
    "hdfs://namonode:8020/path/to/file2.csv",
])
```

**Comment by jhseu** [comment]
You need to install Hadoop locally, but you don't need to configure it. You can just download a binary Hadoop release or use a standard distribution (e.g., Cloudera).

**Comment by PhoenixDai** [comment]
Got you. Thanks a lot! I will try it out.

**Comment by agggaurav** [comment]
How to use hive in distributed tensorflow?Please post any example if available.

**Comment by kelly-tlz** [comment]
@jhseu Hi, I use tensorflow 1.0, and I don't know how to write checkpoint files and event logs files directly to hdfs directory. My current code is like this:
`hdfs_path="hdfs://*" 
local_path = "./" 
with tf.Session(graph=tf.get_default_graph()) as sess: 
    W = tf.Variable([[1,2,3],[3,4,5]], dtype=tf.float32, name='weights') 
    b = tf.Variable([[1,2,3]], dtype=tf.float32, name='biases') 
    init = tf.group(tf.global_variables_initializer(),tf.local_variables_initializer()) 
    saver = tf.train.Saver() 
    sess.run(init) 
    summary_writer = tf.summary.FileWriter(hdfs_path,graph_def=sess.graph_def) 
    saver.save(sess,save_path=hdfs_path+"save_net.ckpt") `
