### ISSUE TITLE
" error: no member named 'stoi' in namespace 'std' " when bazel build //tensorflow/contrib/lite/tools/accuracy/ilsvrc:imagenet_accuracy_eval

### ISSUE THREAD

**Issue by PennySHE** [tensorflow/tensorflow#22183]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
Linux Ubuntu 14.04.4
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
snapdragon SDM845
- **TensorFlow installed from (source or binary)**:
Install from binary
- **TensorFlow version (use command below)**: 
1.9.0 , CPU only
- **Python version**: 
Python 2.7.6
- **Bazel version (if compiling from source)**:
Build label: 0.16.1
- **GCC/Compiler version (if compiling from source)**: gcc version 4.8.4 
- **CUDA/cuDNN version**: 
- **GPU model and memory**:
- **Exact command to reproduce**:

**### Describe the problem**
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/tools/accuracy  
bazel build -c opt \
  --config=android_arm \
  --config=monolithic \
  --cxxopt='--std=c++11' \
  --copt=-D__ANDROID_TYPES_FULL__ \
  --copt=-DSUPPORT_SELECTIVE_REGISTRATION \
  //tensorflow/contrib/lite/tools/accuracy/ilsvrc:imagenet_accuracy_eval 

NFO: Analysed target //tensorflow/contrib/lite/tools/accuracy/ilsvrc:imagenet_accuracy_eval (71 packages loaded).
INFO: Found 1 target...
ERROR: /local/mnt/workspace/ruipan/tf_source/tensorflow/tensorflow/contrib/lite/tools/accuracy/ilsvrc/BUILD:122:1: C++ compilation of rule '//tensorflow/contrib/lite/tools/accuracy/ilsvrc:imagenet_model_evaluator' failed (Exit 1): clang failed: error executing command
  (cd /local/mnt/workspace/ruipan/tmp/cache_bazel/_bazel_ruipan/9f5b27aadc11adc5a986b0783cdd6b20/execroot/org_tensorflow && \
  exec env - \
    ANDROID_BUILD_TOOLS_VERSION=28.0.0 \
    ANDROID_NDK_API_LEVEL=16 \
    ANDROID_NDK_HOME=/local/mnt/workspace/ruipan/android/android-ndk-r16b \
    ANDROID_SDK_API_LEVEL=28 \
    ANDROID_SDK_HOME=/local/mnt/workspace/ruipan/android/sdk \
    PATH=/local/mnt/workspace/ruipan/android/android-ndk-r16b:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/local/mnt/workspace/ruipan/android/sdk/tools:/local/mnt/workspace/ruipan/android/sdk/platform-tools \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/local \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang '-D__ANDROID_API__=16' -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/armeabi-v7a-opt/bin/tensorflow/contrib/lite/tools/accuracy/ilsvrc/_objs/imagenet_model_evaluator/imagenet_model_evaluator.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/tensorflow/contrib/lite/tools/accuracy/ilsvrc/_objs/imagenet_model_evaluator/imagenet_model_evaluator.o' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DS_IREAD=S_IRUSR' '-DS_IWRITE=S_IWUSR' '-DS_IEXEC=S_IXUSR' -iquote . -iquote bazel-out/armeabi-v7a-opt/genfiles -iquote bazel-out/armeabi-v7a-opt/bin -iquote external/com_google_absl -iquote bazel-out/armeabi-v7a-opt/genfiles/external/com_google_absl -iquote bazel-out/armeabi-v7a-opt/bin/external/com_google_absl -iquote external/bazel_tools -iquote bazel-out/armeabi-v7a-opt/genfiles/external/bazel_tools -iquote bazel-out/armeabi-v7a-opt/bin/external/bazel_tools -iquote external/nsync -iquote bazel-out/armeabi-v7a-opt/genfiles/external/nsync -iquote bazel-out/armeabi-v7a-opt/bin/external/nsync -iquote external/protobuf_archive -iquote bazel-out/armeabi-v7a-opt/genfiles/external/protobuf_archive -iquote bazel-out/armeabi-v7a-opt/bin/external/protobuf_archive -iquote external/eigen_archive -iquote bazel-out/armeabi-v7a-opt/genfiles/external/eigen_archive -iquote bazel-out/armeabi-v7a-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/armeabi-v7a-opt/genfiles/external/local_config_sycl -iquote bazel-out/armeabi-v7a-opt/bin/external/local_config_sycl -iquote external/double_conversion -iquote bazel-out/armeabi-v7a-opt/genfiles/external/double_conversion -iquote bazel-out/armeabi-v7a-opt/bin/external/double_conversion -iquote external/fft2d -iquote bazel-out/armeabi-v7a-opt/genfiles/external/fft2d -iquote bazel-out/armeabi-v7a-opt/bin/external/fft2d -iquote external/gemmlowp -iquote bazel-out/armeabi-v7a-opt/genfiles/external/gemmlowp -iquote bazel-out/armeabi-v7a-opt/bin/external/gemmlowp -iquote external/gif_archive -iquote bazel-out/armeabi-v7a-opt/genfiles/external/gif_archive -iquote bazel-out/armeabi-v7a-opt/bin/external/gif_archive -iquote external/jpeg -iquote bazel-out/armeabi-v7a-opt/genfiles/external/jpeg -iquote bazel-out/armeabi-v7a-opt/bin/external/jpeg -iquote external/png_archive -iquote bazel-out/armeabi-v7a-opt/genfiles/external/png_archive -iquote bazel-out/armeabi-v7a-opt/bin/external/png_archive -iquote external/zlib_archive -iquote bazel-out/armeabi-v7a-opt/genfiles/external/zlib_archive -iquote bazel-out/armeabi-v7a-opt/bin/external/zlib_archive -iquote external/flatbuffers -iquote bazel-out/armeabi-v7a-opt/genfiles/external/flatbuffers -iquote bazel-out/armeabi-v7a-opt/bin/external/flatbuffers -iquote external/arm_neon_2_x86_sse -iquote bazel-out/armeabi-v7a-opt/genfiles/external/arm_neon_2_x86_sse -iquote bazel-out/armeabi-v7a-opt/bin/external/arm_neon_2_x86_sse -iquote external/androidndk -iquote bazel-out/armeabi-v7a-opt/genfiles/external/androidndk -iquote bazel-out/armeabi-v7a-opt/bin/external/androidndk -iquote external/farmhash_archive -iquote bazel-out/armeabi-v7a-opt/genfiles/external/farmhash_archive -iquote bazel-out/armeabi-v7a-opt/bin/external/farmhash_archive -isystem external/nsync/public -isystem bazel-out/armeabi-v7a-opt/genfiles/external/nsync/public -isystem bazel-out/armeabi-v7a-opt/bin/external/nsync/public -isystem external/protobuf_archive/src -isystem bazel-out/armeabi-v7a-opt/genfiles/external/protobuf_archive/src -isystem bazel-out/armeabi-v7a-opt/bin/external/protobuf_archive/src -isystem external/eigen_archive -isystem bazel-out/armeabi-v7a-opt/genfiles/external/eigen_archive -isystem bazel-out/armeabi-v7a-opt/bin/external/eigen_archive -isystem external/double_conversion -isystem bazel-out/armeabi-v7a-opt/genfiles/external/double_conversion -isystem bazel-out/armeabi-v7a-opt/bin/external/double_conversion -isystem external/gif_archive/lib -isystem bazel-out/armeabi-v7a-opt/genfiles/external/gif_archive/lib -isystem bazel-out/armeabi-v7a-opt/bin/external/gif_archive/lib -isystem external/png_archive -isystem bazel-out/armeabi-v7a-opt/genfiles/external/png_archive -isystem bazel-out/armeabi-v7a-opt/bin/external/png_archive -isystem external/zlib_archive -isystem bazel-out/armeabi-v7a-opt/genfiles/external/zlib_archive -isystem bazel-out/armeabi-v7a-opt/bin/external/zlib_archive -isystem tensorflow/contrib/lite/schema -isystem bazel-out/armeabi-v7a-opt/genfiles/tensorflow/contrib/lite/schema -isystem bazel-out/armeabi-v7a-opt/bin/tensorflow/contrib/lite/schema -isystem external/flatbuffers/include -isystem bazel-out/armeabi-v7a-opt/genfiles/external/flatbuffers/include -isystem bazel-out/armeabi-v7a-opt/bin/external/flatbuffers/include -isystem external/farmhash_archive/src -isystem bazel-out/armeabi-v7a-opt/genfiles/external/farmhash_archive/src -isystem bazel-out/armeabi-v7a-opt/bin/external/farmhash_archive/src -D__ANDROID_TYPES_FULL__ -DSUPPORT_SELECTIVE_REGISTRATION '--std=c++11' -DFARMHASH_NO_CXX_STRING '-mfpu=neon' '-mfloat-abi=softfp' '-std=c++11' -O3 -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK '--sysroot=external/androidndk/ndk/platforms/android-16/arch-arm' -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystemexternal/androidndk/ndk/sysroot/usr/include -c tensorflow/contrib/lite/tools/accuracy/ilsvrc/imagenet_model_evaluator.cc -o bazel-out/armeabi-v7a-opt/bin/tensorflow/contrib/lite/tools/accuracy/ilsvrc/_objs/imagenet_model_evaluator/imagenet_model_evaluator.o)
tensorflow/contrib/lite/tools/accuracy/ilsvrc/imagenet_model_evaluator.cc:240:56: error: no member named 'stoi' in namespace 'std'
                   [](const string& val) { return std::stoi(val) - 1; });
                                                  ~~~~~^
1 error generated.
Target //tensorflow/contrib/lite/tools/accuracy/ilsvrc:imagenet_accuracy_eval failed to build
INFO: Elapsed time: 18.066s, Critical Path: 2.62s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by shashishekhar** [comment]
@PennySHE : Can you use a newer version of NDK, this should not be an issue with the newer versions of NDK.

**Comment by PennySHE** [comment]
@shashishekhar  _SUPPORTED_ANDROID_NDK_VERSIONS = [10, 11, 12, 13, 14, 15, 16]

I'm using NDK 16 which is the most stable version right now.

**Comment by shashishekhar** [comment]
@PennySHE : Ah! correct the parsing code for NDK support seems incorrect. Please see my comment [here](https://github.com/tensorflow/tensorflow/issues/20192#issuecomment-404971539) for using a higher version of NDK. Sorry for the trouble, we are going to fix this soon.

**Comment by tofulawrence** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by lee-bin** [comment]
You may try this in `.tf_configure.bazelrc`
```bazel
build --action_env ANDROID_NDK_HOME="/path/to/android-ndk-r17b"
build --action_env ANDROID_NDK_API_LEVEL="21"
```
