### ISSUE TITLE
Error in api_docs/images/Gather.png 

### ISSUE THREAD

**Issue by ry** [tensorflow/tensorflow#222]
The last arrow should originate from p_5. I'd photoshop it, but I imagine there's an source illustrator file somewhere which would be better to change.

http://www.tensorflow.org/api_docs/python/array_ops.md#gather
https://github.com/tensorflow/tensorflow/blob/a9ca5173b2252b0de5dd754147b275e85298e522/tensorflow/g3doc/api_docs/images/Gather.png

**Comment by keveman** [comment]
Thanks for pointing it out. We will fix it at the source.

**Comment by vrv** [comment]
@colah, can you take a look at this?

**Comment by vrv** [comment]
was fixed ages ago
