### ISSUE TITLE
LookupError: No gradient defined for operation type: ResizeNearestNeighborGrad or ResizeBilinearGrad

### ISSUE THREAD

**Issue by GPrathap** [tensorflow/tensorflow#22208]
### System information:
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version**:1.10.0
- **Python version**:2.7.x
- **CUDA/cuDNN version**:9.0.x
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:Nope
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:N/
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**:N/A
- **GPU model and memory**: Geforce 940mx
- **Exact command to reproduce**: N/A

### Describe the problem
I want to the gradient of any of [these image resizing operations](https://www.tensorflow.org/api_docs/python/tf/image/ResizeMethod) inside the neural network. But seems to be any of these does not define the gradient ops for them. I see there is a [similar issue ](https://github.com/tensorflow/tensorflow/issues/7641) which has not been answered yet. I also asked in the [SO](https://stackoverflow.com/questions/52264891/lookuperror-no-gradient-defined-for-operation-type-resizenearestneighborgrad) but still, I did not get an answer for this. 

### Source code / logs

      
		differences = tf.subtract(images_fake, images_real)
		alpha_shape = [params.batch_size] + [1] * (differences.shape.ndims - 1)
		alpha = tf.random_uniform(shape=alpha_shape, minval=0., maxval=1.)
		interpolates = images_real + (alpha * differences)
		d_model = Model(params, args.mode, interpolates, reuse_variables, images_fake, 1)
		gradients = tf.gradients(d_model.logistic_linear, [interpolates])[0]
		slopes = tf.sqrt(tf.reduce_sum(tf.square(gradients), reduction_indices=[1]))
		gradient_penalty = tf.reduce_mean((slopes - 1.) ** 2)
		_gradient_penalty = 10 * gradient_penalty

Inside my model, it uses [ tf.image.resize_bicubic()](https://www.tensorflow.org/api_docs/python/tf/image/resize_bicubic). But I see there are some [exisiting implementation](https://github.com/tensorflow/tensorflow/commit/3331c574bcfd85787d7a4f3d1b1b139239a6595b) for this. But not sure how those things get it them working. Please let me know how this can be achieved. These image resizing cannot be done as preprocessing it needs to be done inside a model. Any help would be really appreciated.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by GPrathap** [comment]
Any update on this

**Comment by facaiy** [comment]
I think the patch 3331c574b will be released with r1.11. Would you mind taking a try on 
+ 1.11-rc: `pip install tensorflow==1.11.0rc0`
+ or nightly version: `pip install tf-nightly`

**Comment by GPrathap** [comment]
yeap, I will try and let you know. Thanks

**Comment by harshini-gadige** [comment]
@GPrathap Hi, any update if you tried ?

**Comment by GPrathap** [comment]
Sorry for the late reply, I was on my vacation.

Still I am getting this error. 

`LookupError: No gradient defined for operation 'discriminator/gradients/discriminator/decoder/ResizeBilinear_grad/ResizeBilinearGrad' (op type: ResizeBilinearGrad)`

I installed `pip install tensorflow-gpu==1.11.0rc0`

**Comment by facaiy** [comment]
Could you provide a minimal example?

**Comment by GPrathap** [comment]
As I explained in the above, to find the total loss I calculate the gradient of the model. When the model is going through backpropagation stage it is trying to calculate the gradient of gradient where this error comes from. I guess in the tensorflow gradient of the gradient is not defined for these image resizing operations. That is why I am getting this error. I guess you can close this issue because I might try to calculate the loss in a different way where it is not required to calculate the gradient of  gradient.

Thanks

**Comment by facaiy** [comment]
Yes, `ResizeBilinearGradGrad` is missing, unfortunately. I think contribution is welcome if you'd like to implement it.

**Comment by Oktai15** [comment]
@GPrathap how did you fix it?

**Comment by GPrathap** [comment]
Nope, I haven't fixed it, I changed the loss function

**Comment by Oktai15** [comment]
@GPrathap can you provide the loss function that you did? I want to implement WGAN-GP loss and I have the same problem

**Comment by GPrathap** [comment]
You may find it here, I am not sure which will help you or not. 

https://github.com/GPrathap/monodepth/blob/master/monodepth_main_new_loss.py#L222 
https://github.com/GPrathap/monodepth/blob/master/monodepth_model_gan.py#L381

Just have a look :)

**Comment by tanzhenyu** [comment]
Contributions welcome!

**Comment by SNMS95** [comment]
Has there been any progress in this issue? If someone has implemented or knows how to implement this, can you post it here please?

**Comment by gtanzi** [comment]
Hi, I may be wrong but I'm quite confident that second derivative of a linear op should be zero (None).
I checked this numerically by looking at the output of the gradient of tf.image.resize (or keras UpSampling2D ) vs changing its input and I found out (as expected) that the output depends only on resize factor. So as a quick fix I used:
`
@tf.RegisterGradient("ResizeBilinearGrad")
def _ResizeBilinearGrad_grad(unused_op, grad):
    return None,None
`
Can someone confirm my thoughts?

**Comment by SNMS95** [comment]
@gtanzi . I too think that the second gradient is zero So you can return None w.r.t the original image. But is it correct to return None for the second argument as well?

**Comment by gtanzi** [comment]
@SNMS95 I'm not sure becasue I'm still confused about what exactly needs a definition (i.e. the second order gradient of op Vs the "the first order gradient of grad_fn with respect to dy " [here](https://www.tensorflow.org/api_docs/python/tf/custom_gradient)) If I understood correctly from [here](https://www.tensorflow.org/api_docs/python/tf/RegisterGradient) , for an op with m inputs and n outputs, the gradient function should return m objects. The first derivative of op defined [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_grad.py) returns [something,None] so I guess op takes two imputs but only use one? I've never dealt with custom gradient before

**Comment by SNMS95** [comment]
@gtanzi 
I found that the gradient function for the ‘ResizeBilinearGrad’ op is not implemented in Tensorflow and that this is causing the said error. Also,custom gradients for nonexistant ops can be registered using @tf.RegisterGradient(“ResizeBilinearGrad”), but I don’t know what exactly it should return. The required gradient function should have the form as given below:

@tf.RegisterGradient(“ResizeBilinearGrad”)
def _ResizeBilinearGradGrad(op, grad):
    return (A,B)

Where,
grad - gradients w.r.t to the outputs of ResizeBilinearGrad op
op - ‘ResizeBilinearGrad’
A - gradients w.r.t first input to the op
B - gradients w.r.t input image

The inputs to the ‘ResizeBilinearGrad’ op are:
A - gradients calculated till that point (Not sure!!)
B - the original input image

**Comment by gtanzi** [comment]
@SNMS95 
After some thoughts on your comments I now think my first naive answer was completely wrong. The main reason being that tf is not asking the second derivative of ResizeBilinear, but rather the first derivative of ResizeBilinearGrad with respect to its inputs ( from which it can later perform second order derivative with chain rule). 
The upscaling op should take an image X with shape <img src="https://render.githubusercontent.com/render/math?math=(%5Calpha%20x%20%5Cbeta)%0A">  and return a scaled image Y with shape (i x j) like:
<img src="https://render.githubusercontent.com/render/math?math=Y_%7Bij%7D%20%3D%20c_%7Bij%7D%5E%7B%5Calpha%5Cbeta%7DX_%7B%5Calpha%5Cbeta%7D%0A">
where the c coefficients (in bilinear interp) do not depend on X but only on the scaling factors.

Now, as you suggest,  ResizeBilinearGrad inputs are indeed:

> G1 - gradients calculated till that point of shape (ixj) (-> I too think it's right looking at the code)
> X - the original input image  
> 

i.e.

ResizeBilinearGrad( <img src="https://render.githubusercontent.com/render/math?math=G1%5E%7Bij%7D">,X): 
&nbsp;&nbsp; return:<img src="https://render.githubusercontent.com/render/math?math=G1%5E%7Bij%7Dc_%7Bij%7D%5E%7B%5Calpha%5Cbeta%7D">  

and ResizeBilinearGradGrad ( op= ResizeBilinearGrad , grad=G2): 
&nbsp;&nbsp; return:[A,B]


I believe ResizeBilinearGrad uses X only to determine the output shape (? I'm not sure why ResizeBilinearGrad needs X), I assume the second outputs of _ResizeBilinearGradGrad must be None.
However this is not true for the first output (as I wrongly suggest before) and should be (including the backprop of grad G2):
&nbsp;&nbsp;<img src="https://render.githubusercontent.com/render/math?math=c_%7Bij%7D%5E%7B%5Calpha%5Cbeta%7D%20G2_%7B%5Calpha%5Cbeta%7D">
Which is just the upscaling of G2.
Sooo my second guess is:

```
@tf.RegisterGradient("ResizeBilinearGrad")
def _ResizeBilinearGrad_grad(op, grad):
    up = tf.image.resize(grad,tf.shape(op.inputs[0])[1:-1])
    return up,None

```

I did perform a simple test:
```
import tensorflow as tf
import numpy as np
@tf.RegisterGradient("ResizeBilinearGrad")
def _ResizeBilinearGrad_grad(op, grad):
    up = tf.image.resize(grad,tf.shape(op.inputs[0])[1:-1])
    return up,None

a = np.zeros((1, 2, 2, 1), dtype=np.float32)
a[0, 0, 0, 0] = 2.0

x = tf.constant(a)
up=  tf.keras.layers.UpSampling2D((2,2), data_format='channels_last', interpolation='bilinear')
with tf.GradientTape() as g_tape:
    g_tape.watch(x)
    with tf.GradientTape(persistent=True) as g_tape2:
        g_tape2.watch(x)
        y = x
        y = up(y) 
        t = (y**2)   
        
    up1 = g_tape2.gradient(y,x) 
    g1 = g_tape2.gradient(t,x) 
g2 = g_tape.gradient(g1,x) 


print('######################')
print('x',x[0, :, :, 0])
print('up(x)',y[0, :, :, 0])
print("up'(x)",up1[0, :, :, 0])
print('g1',g1[0, :, :, 0])
print('g2',g2[0, :, :, 0])
```
And checked these with Wolphram Mathematica. It may be useful to perform more checks.
what you think?

**Comment by SNMS95** [comment]
@gtanzi  I am not really an expert in this but if the calculated gradients are the same in Mathematica as well, I do hope that this might be correct.

**Comment by ershang2** [comment]
> @SNMS95 After some thoughts on your comments I now think my first naive answer was completely wrong. The main reason being that tf is not asking the second derivative of ResizeBilinear, but rather the first derivative of ResizeBilinearGrad with respect to its inputs ( from which it can later perform second order derivative with chain rule). The upscaling op should take an image X with shape ![](https://render.githubusercontent.com/render/math?math=(%5Calpha%20x%20%5Cbeta)%0A) and return a scaled image Y with shape (i x j) like: ![](https://render.githubusercontent.com/render/math?math=Y_%7Bij%7D%20%3D%20c_%7Bij%7D%5E%7B%5Calpha%5Cbeta%7DX_%7B%5Calpha%5Cbeta%7D%0A) where the c coefficients (in bilinear interp) do not depend on X but only on the scaling factors.
> 
> Now, as you suggest, ResizeBilinearGrad inputs are indeed:
> 
> > G1 - gradients calculated till that point of shape (ixj) (-> I too think it's right looking at the code)
> > X - the original input image
> 
> i.e.
> 
> ResizeBilinearGrad( ![](https://render.githubusercontent.com/render/math?math=G1%5E%7Bij%7D),X):    return:![](https://render.githubusercontent.com/render/math?math=G1%5E%7Bij%7Dc_%7Bij%7D%5E%7B%5Calpha%5Cbeta%7D)
> 
> and ResizeBilinearGradGrad ( op= ResizeBilinearGrad , grad=G2):    return:[A,B]
> 
> I believe ResizeBilinearGrad uses X only to determine the output shape (? I'm not sure why ResizeBilinearGrad needs X), I assume the second outputs of _ResizeBilinearGradGrad must be None. However this is not true for the first output (as I wrongly suggest before) and should be (including the backprop of grad G2):   ![](https://render.githubusercontent.com/render/math?math=c_%7Bij%7D%5E%7B%5Calpha%5Cbeta%7D%20G2_%7B%5Calpha%5Cbeta%7D) Which is just the upscaling of G2. Sooo my second guess is:
> 
> ```
> @tf.RegisterGradient("ResizeBilinearGrad")
> def _ResizeBilinearGrad_grad(op, grad):
>     up = tf.image.resize(grad,tf.shape(op.inputs[0])[1:-1])
>     return up,None
> ```
> 
> I did perform a simple test:
> 
> ```
> import tensorflow as tf
> import numpy as np
> @tf.RegisterGradient("ResizeBilinearGrad")
> def _ResizeBilinearGrad_grad(op, grad):
>     up = tf.image.resize(grad,tf.shape(op.inputs[0])[1:-1])
>     return up,None
> 
> a = np.zeros((1, 2, 2, 1), dtype=np.float32)
> a[0, 0, 0, 0] = 2.0
> 
> x = tf.constant(a)
> up=  tf.keras.layers.UpSampling2D((2,2), data_format='channels_last', interpolation='bilinear')
> with tf.GradientTape() as g_tape:
>     g_tape.watch(x)
>     with tf.GradientTape(persistent=True) as g_tape2:
>         g_tape2.watch(x)
>         y = x
>         y = up(y) 
>         t = (y**2)   
>         
>     up1 = g_tape2.gradient(y,x) 
>     g1 = g_tape2.gradient(t,x) 
> g2 = g_tape.gradient(g1,x) 
> 
> 
> print('######################')
> print('x',x[0, :, :, 0])
> print('up(x)',y[0, :, :, 0])
> print("up'(x)",up1[0, :, :, 0])
> print('g1',g1[0, :, :, 0])
> print('g2',g2[0, :, :, 0])
> ```
> 
> And checked these with Wolphram Mathematica. It may be useful to perform more checks. what you think?

Thanks，This is very helpful to me
