### ISSUE TITLE
How to get max and min x and y of bounding boxes from Object_detection_image.py?

### ISSUE THREAD

**Issue by rokij6698** [tensorflow/tensorflow#22215]
this is the link of the image:
https://ibb.co/nbLjc9

After I print the "boxes" variable, it gives an array of numbers.

When I change the values inside, the bounding box changes too.

So, I am pretty sure those are the values will give different size and location of bounding boxes.

However, how can I get the max and min bounding box from this array?

like max y = 1920, max x = 1080, min y = 0, min x = 0.

Thank you.

**Comment by wt-huang** [comment]
If you are trying to get the min/max x and y from the array in your output, simply read the output into ndarray using numpy then find the min and max.
