### ISSUE TITLE
The latest process of building tensorflow serving for windows

### ISSUE THREAD

**Issue by taotaolin** [tensorflow/tensorflow#22222]
**Have I written custom code**  in /tensorflow/contrib/cmake/CMakeLists.txt
```
if（tensorflow_OPTIMIZE_FOR_NATIVE_ARCH）
  include（CheckCXXCompilerFlag）
  CHECK_CXX_COMPILER_FLAG（“ - march = native” COMPILER_OPT_ARCH_NATIVE_SUPPORTED）
  if（COMPILER_OPT_ARCH_NATIVE_SUPPORTED）
    set（CMAKE_CXX_FLAGS “ $ {CMAKE_CXX_FLAGS} -march = native”）
  endif（）
endif（）
```

changed to

```
if (tensorflow_OPTIMIZE_FOR_NATIVE_ARCH)
  include(CheckCXXCompilerFlag)
  CHECK_CXX_COMPILER_FLAG("-march=native" COMPILER_OPT_ARCH_NATIVE_SUPPORTED)
  if (COMPILER_OPT_ARCH_NATIVE_SUPPORTED)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
  else()
    CHECK_CXX_COMPILER_FLAG("/arch:AVX" COMPILER_OPT_ARCH_AVX_SUPPORTED)
    if(COMPILER_OPT_ARCH_AVX_SUPPORTED)
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX")
    endif()
  endif()
endif()
```

**OS Platform and Distribution**    windows7 x64
**TensorFlow installed from**    sourse
**TensorFlow version**  r1.10
**Bazel version** N/A
**CUDA/cuDNN** version 9.0/Cudnn 7.0
**GPU model and memory** 1080Ti / 11G
**Exact command to reproduce**

**1. Cmake build:**
```
cmake .. -A x64 -DCMAKE_BUILD_TYPE=Debug
-T host=x64
-DSWIG_EXECUTABLE=D:/lib/swigwin-3.0.12/swig.exe
-DPYTHON_EXECUTABLE=C:/Users/tao/AppData/Local/Programs/Python/Python35-32/python.exe 
-DPYTHON_LIBRARIES=C:/Users/tao/AppData/Local/Programs/Python/Python35-32/libs/python35.lib 
-Dtensorflow_ENABLE_GPU=ON 
-Dtensorflow_ENABLE_GRPC_SUPPORT=OFF
-Dtensorflow_BUILD_SHARED_LIB=ON  
```

**2. Visual studio 2015:**

`MSBuild /p:Configuration=Debug /p:Platform=x64 ALL_BUILD.vcxproj
`
### Describe the problem

I want to use Tensorflow in my Windows C++ application. Therefore I'm trying to build in Visual studio on a Windows system.

Whether to support compiling DEBUG version.
### logs
```
fatal error C1083: Cannot open include file: 'tensorflow/core/framework/device_attributes.pb_text.h': No such file or directory (compiling source file C:\tensorflow\tensorflow\core\kernels\captured_function.cc)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
CUDA/cuDNN version
Mobile device

**Comment by taotaolin** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> CUDA/cuDNN version
> Mobile device

**CUDA/cuDNN version**   CUDA 9.0/Cudnn 7.0

Now I have new problems. if `-Dtensorflow_ENABLE_GRPC_SUPPORT=OFF`  Tips：fatal error C1083: Cannot open include file: 'grpcpp/grpcpp.h': No such file or directory 

if `-Dtensorflow_ENABLE_GRPC_SUPPORT=ON`  Tips：C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”已退出，代码为 1。 [D:\tensorflow-master\tensorflow\contrib\cmake\build\grpc.vcxproj]

I hope to get help. Thx
