### ISSUE TITLE
feed_previous argument for basic_rnn_seq2seq

### ISSUE THREAD

**Issue by ghyun** [tensorflow/tensorflow#2223]
Feature request: can the `basic_rnn_seq2seq` function in the seq2seq module implement a `feed_previous` argument, just like the `embedding_rnn_seq2seq` function?

**Comment by girving** [comment]
@lukaszkaiser: Can you comment?  Should we mark this contributions welcome?

**Comment by lukaszkaiser** [comment]
Yes!

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by aaxwaz** [comment]
Can we reopen the issue for implementing the 'feed_previous' feature in basic_rnn_seq2seq? This is useful for time series predictions. Otherwise we will need to implement our own seq2seq using lstm from scratch which may not be as optimised I think
