### ISSUE TITLE
 encrypt the tflite model

### ISSUE THREAD

**Issue by dlml** [tensorflow/tensorflow#22232]
I want to encrypt the tflite model, what should I do?

**Comment by w3x10e8** [comment]
Someone already asked this earlier [here](https://github.com/tensorflow/tensorflow/issues/21501)

**Comment by wt-huang** [comment]
Closing this issue since this is a duplicate

**Comment by zw232618** [comment]
emmm

**Comment by wt-huang** [comment]
Any questions or concerns you have about this issue, just let me know.
