### ISSUE TITLE
Feature Request: Permit Changes to LSTMStateTuple to be compatible with autodiff

### ISSUE THREAD

**Issue by RylanSchaeffer** [tensorflow/tensorflow#22254]
I would like to make changes to an LSTMStateTuple that (in theory) should be compatible with auto differentiation (I'm taking a vector output by one LSTM and adding it to the cell state `c` of another LSTM at each "time step"). However, as far as I can tell, LSTMStateTuple is a named tupled, so making a change to `c` requires creating a new LSTMStateTuple, preventing autodiff from working. I confirmed with Tensorboard summaries that no gradients are flowing through the kernels or biases of my second LSTM. Does a work-around exist or is this capability missing?

**Comment by ebrevdo** [comment]
Autodiff needs to learn about namedtuples, perhaps?

**Comment by ebrevdo** [comment]
Autodiff needs to learn about namedtuples, perhaps?

**Comment by ebrevdo** [comment]
Tuples are immutable, so you can't modify them in place

**Comment by RylanSchaeffer** [comment]
@ebrevdo , I'm not sure I understand. Yes, tuple are immutable, so they cannot be modified in place. A friend told me that he had no problems creating new `LSTMStateTuple`s, so I'll spend today checking if there's some other problem with my code.

**Comment by RylanSchaeffer** [comment]
I think my code actually works as intended. Sorry to bother you.
