### ISSUE TITLE
Docs/tutorial link to 'Eager execution', item 1 of 'Research and experimentation' 404 err.

### ISSUE THREAD

**Issue by jmsinusa** [tensorflow/tensorflow#22267]
Documentation; tutorials.
Link to Eager execution tutorial (item 1 of 'Research and experimentation') give a 404 error.

The link is currently pointing to:
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/python/examples/notebooks/eager_intro.ipynb](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/python/examples/notebooks/eager_intro.ipynb)

I believe that it should be pointing to:
[https://github.com/tensorflow/docs/blob/master/site/en/tutorials/eager/eager_basics.ipynb](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/eager/eager_basics.ipynb)

**Comment by ymodak** [comment]
@jmsinusa Thank you for the post. Yes you are right about the pointing of eager_basics.ipynb link, we have moved the notebooks to the tensorflow/docs repository. We have mentioned this update in the Readme file as well. I am closing this issue as you can access the notebooks from the tensorflow/docs repository.
