### ISSUE TITLE
failed to build tensorflow wheel file on jetson TX2 board 

### ISSUE THREAD

**Issue by amoghkashyap** [tensorflow/tensorflow#22272]
ERROR: /home/nvidia/Desktop/tensorflow/tensorflow/cc/BUILD:422:1: Linking of rule '//tensorflow/cc:ops/math_ops_gen_cc' failed (Exit 1)
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Scc_Cops_Smath_Uops_Ugen_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1648.891s, Critical Path: 115.03s
FAILED: Build did NOT complete successfully

Bazel version: 10.0
CUDA: 9.0
CUDNN:7.0

Request you to kindly help me find a solution to the problem.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by amoghkashyap** [comment]
Hi I was able to fix the issue thank you!

**Comment by anhtu812** [comment]
@amoghkashyap  how to fix this issue? Thanks.

**Comment by Roython** [comment]
now i meet the same problem, how to fix it?

**Comment by amoghkashyap** [comment]
you have to build tensorflow from source using bazel. Also, if you don't have the jetpack, you can install the dependencies with the following instructions:


#Add base Jetpack URL to ENV
export URL=https://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/3.2.1/m8u2ki/JetPackL4T_321_b23

#update and add few usefull packages 
sudo apt-get update && apt-get install -y apt-utils bzip2 curl sudo unp && apt-get clean && rm -rf /var/cache/apt

#install drivers
curl -sL http://developer.nvidia.com/embedded/dlc/l4t-jetson-tx2-driver-package-28-2 3 | tar xvfj -
chown root /etc/passwd /etc/sudoers /usr/lib/sudo/sudoers.so /etc/sudoers.d/README
/tmp/Linux_for_Tegra/apply_binaries.sh -r / && rm -fr /tmp/*

#Download the JETPACK libraries for ARM architecture
curl $URL/cuda-repo-l4t-9-0-local_9.0.252-1_arm64.deb -so /tmp/cuda-repo-l4t_arm64.deb
curl $URL/libcudnn7_7.0.5.15-1+cuda9.0_arm64.deb -so /tmp/libcudnn_arm64.deb
curl $URL/libcudnn7-dev_7.0.5.15-1+cuda9.0_arm64.deb -so /tmp/libcudnn-dev_arm64.deb

#Install L4T, CUDA, cuDNN libraries
sudo dpkg -i /tmp/cuda-repo-l4t_arm64.deb
sudo apt-key add /var/cuda-repo-9-0-local/7fa2af80.pub
sudo apt-get update && apt-get install -y cuda-toolkit-9.0 (default installation dir: /usr/local/cuda)
sudo dpkg -i /tmp/libcudnn_arm64.deb
sudo dpkg -i /tmp/libcudnn-dev_arm64.deb

#Add LD_LIBRAARY_PATH to ENV
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/aarch64-linux-gnu/tegra

#Re-link libs in /usr/lib/tegra
ln -s /usr/lib/aarch64-linux-gnu/tegra/libnvidia-ptxjitcompiler.so.28.2.0 /usr/lib/aarch64-linux-gnu/tegra/libnvidia-ptxjitcompiler.so
ln -s /usr/lib/aarch64-linux-gnu/tegra/libnvidia-ptxjitcompiler.so.28.2.0 /usr/lib/aarch64-linux-gnu/tegra/libnvidia-ptxjitcompiler.so.1
ln -sf /usr/lib/aarch64-linux-gnu/tegra/libGL.so /usr/lib/aarch64-linux-gnu/libGL.so
ln -s /usr/lib/aarch64-linux-gnu/libcuda.so /usr/lib/aarch64-linux-gnu/libcuda.so.1

#Clone OpenCV Github repo
git clone https://github.com/jetsonhacks/buildOpenCVTX2.git

#Run the shell script to build OpenCV
./buildOpenCV.sh -s <file directory>
(This will build OpenCV in the given file directory and install OpenCV in the /usr/local directory.)

#Remove the source files
./removeOpenCVSources.sh -d <file directory>
where the <file directory> contains the OpenCV source.

#Clean the board 
sudo apt-get -y autoremove && apt-get -y autoclean
sudo rm -rf /var/cache/apt
