### ISSUE TITLE
How to compile the tensorflow-lite to get a smaller and faster library?

### ISSUE THREAD

**Issue by wzzju** [tensorflow/tensorflow#22277]
### System information
- **Mobile device**: 
    * HUAWEI Mate 9
    * Xiaomi Mi 6

### Describe the problem
During Arm AI Developer Global Summit, the Google engineer said that TensorFlow-Lite can be compiled into an about 400KB library. However, when I compile the latest TensorFlow-Lite, I can only get a  1.2MB dynamic link library. The following script is my compiled command:
```bash
bazel build -c opt --cxxopt='--std=c++11' --cxxopt='-O3' --cxxopt='-march=armv7-a' --cxxopt='-mfpu=neon' --cxxopt='-mfloat-abi=softfp' //tensorflow/contrib/lite/java:tensorflowlite --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a
```
What's wrong with this compiled command?

Besides,  in order to test the performance of tensorflow-lite, I also compiled its benchmarks according to [this official doc](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/tools/benchmark) .The following script is my compiled command (offered by the official doc):
```
bazel build -c opt \
  --config=android_arm \
  --cxxopt='--std=c++11' \
  tensorflow/contrib/lite/tools/benchmark:benchmark_model
```
When running MobileNet_v1_1.0_224, its result is shown as follow:
![image](https://user-images.githubusercontent.com/17102274/45552548-d9ca7f80-b863-11e8-8bd1-db14bf5c354f.png)
I want to know how to get a faster result?

**Comment by wzzju** [comment]
@shashishekhar, thanks. I want to compile the tf-lite to get a smaller size of jni dynamic link library（.so file）, not a java library. How can I achieve this goal？

**Comment by zhyj3038** [comment]
can U get a static library ? ie. libtensorflow-lite.a.  I can only get one works on pc, not on armeabi-v7

**Comment by shashishekhar** [comment]
@wzzju: You can use our experimental [C library](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/experimental/c/BUILD#L56) and corresponding [shared library](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/experimental/c/BUILD#L20) but be warned a lot of the API is still experimental and subject to change.

**Comment by shashishekhar** [comment]
@wzzju : Please reopen if this doesn't handle your case.
