### ISSUE TITLE
Check failed

### ISSUE THREAD

**Issue by nationalflag** [tensorflow/tensorflow#2229]
F tensorflow/core/framework/tensor_shape.cc:211] Check failed: num_elements_ <= kMaxElements (9291474468864 vs. 1099511627776)
I can't figure out why the above error happens. What's wrong ?

**Comment by yaroslavvb** [comment]
There's a hard bound on the number of elements in a Tensor (about a trillion), do you really need to use a 9 trillion element tensor?

**Comment by nationalflag** [comment]
I found I have created a big SparseTensor
