### ISSUE TITLE
Golang: could not determine kind of name for C.TF_UINT64

### ISSUE THREAD

**Issue by donutloop** [tensorflow/tensorflow#22294]
I do have a issue with building my golang app. I'm getting this error while compiling my application. 

github.com/donutloop/imagedetection/vendor/github.com/tensorflow/tensorflow/tensorflow/go
vendor/github.com/tensorflow/tensorflow/tensorflow/go/tensor.go:42:24: could not determine kind of name for C.TF_UINT32
vendor/github.com/tensorflow/tensorflow/tensorflow/go/tensor.go:50:24: could not determine kind of name for C.TF_UINT64

go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build290707876=/tmp/go-build -gno-record-gcc-switches"

golang dep
[[constraint]]
  name = "github.com/tensorflow/tensorflow"
  version = "1.10.1"

**Comment by donutloop** [comment]
Fixed it

**Comment by princesegzy01** [comment]
@donutloop How did you fix it, I am having same issue

**Comment by donutloop** [comment]
i didn't use the right version of "tensorflow/tensorflow/tensorflow/go" for the tensorflow engine, that means binding and engine wasn't compatible with each other. Please check if you are using a correct binding version for your installed tensorflow c library

**Comment by zmajew** [comment]
> 

princesegzy01 did not ask you what was the problem, but hot to fix it.

**Comment by donutloop** [comment]
@zmajew version mismatch between client library and Tensorflow engine. Check that both version are compatible with each other.
