### ISSUE TITLE
shared_embedding_columns  with partitioner  is  ERROR

### ISSUE THREAD

**Issue by qiang2008** [tensorflow/tensorflow#22297]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: 
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:1.10.1
- **Python version**:3.5.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:NO
- **GPU model and memory**:NO
- **Exact command to reproduce**:

### Describe the problem
When use shared_embedding_columns without partitioner  to save model ,then import_meta_graph from check_point is success. But use shared_embedding_columns with partitioner, then import_meta_graph from check_point is failed.   
Report error: KeyError: 
The name 'run_2/input_from_feature_columns/a1_shared_embedding/a1_a1_shared_embedding' refers to an Operation not in the graph

### Source code / logs

code for model
first, mkdir mypath/model
````
from tensorflow.contrib.layers.python.layers import feature_column as fc
from tensorflow.python.ops import variable_scope
from tensorflow.python.framework import sparse_tensor as sparse_tensor_lib
from tensorflow.contrib.layers.python.layers import feature_column_ops
from tensorflow.python.training import saver
import tensorflow as tf

def mySharedEmbeddingColumn():
    a1 = fc.sparse_column_with_keys("a1", ["marlo", "omar", "stringer"])
    b = fc.shared_embedding_columns([a1, a1], dimension=4, combiner="mean")
    c = fc.embedding_column(a1, dimension=4, combiner="mean")
    input_tensor_c1 = sparse_tensor_lib.SparseTensor(
        indices=[[0, 0], [1, 1], [2, 2]], values=[0, 1, 2], dense_shape=[3, 3])
    dnn_partitioner = (
        tf.min_max_variable_partitioner(
        max_partitions=1))
    with variable_scope.variable_scope("run_2",partitioner=dnn_partitioner):
      b2 = feature_column_ops.input_from_feature_columns({
          b[1]: input_tensor_c1
      }, [b[1]])
    with variable_scope.variable_scope("run_3", partitioner=dnn_partitioner):
      c1 = feature_column_ops.input_from_feature_columns({
          c: input_tensor_c1
      }, [c])
    saver = tf.train.Saver()
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        variable_names = [v.name for v in tf.trainable_variables()]
        values = sess.run(variable_names)
        for k,v in zip(variable_names, values):
            print("Variable: ", k)
            print("Shape: ", v.shape)
            print(v)
        saver.save(sess,'model/model-ckt')

mySharedEmbeddingColumn()
````
code for restore
````
import tensorflow as tf

graph = tf.Graph()
sess = tf.Session(graph=graph)
with graph.as_default():
    del tf.get_collection_ref(tf.GraphKeys.TRAIN_OP)[:]
    check_point_path = 'model' 
    saver = tf.train.import_meta_graph('model/model-ckt.meta')
    print(graph.get_operations())

````

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by qiang2008** [comment]
updated, please help me to solve this problerm ,thank u.

**Comment by allenlavoie** [comment]
Yeah this comes up if there's a PartitionedVariable in a collection without a read op. There was a fix in https://github.com/tensorflow/tensorflow/commit/b23df6e50255991b06cc8d6596b1075c3bd3f7e9. Looks like it'll be in 1.11.
