### ISSUE TITLE
extra cpus not recognized when using docker on windows 10

### ISSUE THREAD

**Issue by timshephard** [tensorflow/tensorflow#223]
Not sure if this is a windows 10 specific issue, a virtual box issue, a docker issue or a tensorflow/docker integration issue, but I'm getting 

"tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'random_normal/stddev': Could not satisfy explicit device specification '/cpu:1'"

For the following code:

with tf.device("/cpu:1"):
    sess = tf.Session()
    op = tf.matrix_inverse(tf.random_normal([100,100]))
    sess.run(op)

Note that /proc/cpuinfo is reporting that I have cpu cores       : 8

Also, when I do run  tf.matrix_inverse(tf.random_normal([3000,3000])) my CPUs are barely used. 

Another thing I tried was  

"cat cifar10_multi_gpu_train.py | sed -e 's:gpu:cpu:g' > cifar10_multi_cpu_train.py"
python cifar10_multi_cpu_train.py --num_cpus=7

That didn't seem to work at all.

**Comment by vrv** [comment]
We should probably clear this up somewhere, but at the moment there is only one 'CPU device' per process.  So cpu:0 has access to all 8 of your cores via threading.

(We thought it would be useful to have the ability to specify multiple CPUs in the future if it turns out that NUMA-aware assignment was helpful)

**Comment by craigcitro** [comment]
@vrv -- presumably the fix here is to just document this?

**Comment by vrv** [comment]
https://www.tensorflow.org/versions/r0.7/how_tos/using_gpu/index.html description of devices is reasonable but could be better.  Happy to accept a PR to make this even more clear.  Closing to reduce the size of our enormous open issues list.

**Comment by zkl99999** [comment]
C:\Users\\Desktop>docker run -it b.gcr.io/tensorflow/tensorflow

Unable to find image 'b.gcr.io/tensorflow/tensorflow:latest' locally

docker: Error response from daemon: unable to ping registry endpoint https://b.g
cr.io/v0/
v2 ping attempt failed with error: Get https://b.gcr.io/v2/: dial tcp 64.233.188
.82:443: i/o timeout

**Comment by craigcitro** [comment]
@zkl99999 this sounds like a connectivity problem; are you still seeing this?

**Comment by zkl99999** [comment]
@craigcitro  thank you, in China,you  know  break wall  haha

**Comment by zkl99999** [comment]
@craigcitro  i install TF ok  in docker,thank you
