### ISSUE TITLE
Tflite label_image resize bug

### ISSUE THREAD

**Issue by tataganesh95** [tensorflow/tensorflow#22310]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
NA
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
1.10
- **Python version**:
3.5
- **Bazel version (if compiling from source)**:
0.15
- **GCC/Compiler version (if compiling from source)**:
NA
- **CUDA/cuDNN version**:
NA
- **GPU model and memory**:
NA
- **Exact command to reproduce**:
NA

### Describe the problem
In the `label_image.cc` example of TFlite, a resize function present in `bitmap_helpers_impl.h` is being called in line [171](https://github.com/tensorflow/tensorflow/blob/4dcfddc5d12018a5a0fdca652b9221ed95e9eb23/tensorflow/contrib/lite/examples/label_image/label_image.cc#L171) - 
`   resize<float>(interpreter->typed_tensor<float>(input), in.data(),`

In the implementation of the function in `bitmap_helpers_impl.h`, the following [line](https://github.com/tensorflow/tensorflow/blob/4dcfddc5d12018a5a0fdca652b9221ed95e9eb23/tensorflow/contrib/lite/examples/label_image/bitmap_helpers_impl.h#L90) 
```
  auto output_number_of_pixels =
      wanted_height * wanted_height * wanted_channels;
```
assumes that for the input image, the height and width must be the same. And this works for the mobilenet example since the input size is 224 x 224. But, this would cause issues for any network where the expected input size does not have the same width and height. It should instead be - 
```
   auto output_number_of_pixels =
      wanted_width * wanted_height * wanted_channels;
```

### Source code / logs
NA

**Comment by shahid14** [comment]
https://github.com/tensorflow/tensorflow/issues/22377#issuecomment-444550814
