### ISSUE TITLE
add R-CNN support with ROI pooling ?

### ISSUE THREAD

**Issue by Irtza** [tensorflow/tensorflow#2231]
Hi, 
I'm interested in implementing a R-CNN or similar object detection/recognition model. there is a theano [port](https://github.com/ddtm/theano-roi-pooling) of Ross. Girshick's implementation in Caffe. 
please let me know if there is a plan to implement R-CNN / release the ROI pooling layer in Tensorflow?

please see.
[Faster RCNN on caffe.](https://github.com/rbgirshick/py-faster-rcnn)

**Comment by wookayin** [comment]
Please see #739 and https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/hnbRY-L4RBg

**Comment by girving** [comment]
Closing since the conversation is happening over in #739.
