### ISSUE TITLE
Links for API broken

### ISSUE THREAD

**Issue by Arafatk** [tensorflow/tensorflow#2232]
On tensorflow website the links for API are broken on [this](https://www.tensorflow.org/versions/r0.7/api_docs/cc/index.html) page.

**Comment by hunkim** [comment]
@Arafatk I think that is fixed in 0.8. [https://www.tensorflow.org/versions/r0.8/api_docs/cc/index.html](https://www.tensorflow.org/versions/r0.8/api_docs/cc/index.html)

**Comment by Arafatk** [comment]
@hunkim  Thanks.
