### ISSUE TITLE
bazel build tensorflow on windows 10 getting cudnn.h- system cannot find the file specified

### ISSUE THREAD

**Issue by rcorvus** [tensorflow/tensorflow#22325]
From stackoverflow:

https://stackoverflow.com/questions/52335703/bazel-build-tensorflow-on-windows-10-getting-cudnn-h-system-cannot-find-the-fil

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: 1.11.0
- **TensorFlow version (use command below)**:  
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: 0.16.0
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:  9.2/7.2.1
- **GPU model and memory**: Nvidia M1000M
- **Exact command to reproduce**:

Additional information:
I've added these to my path (and rebooted):
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\libnvvp
C:\tools\msys64
C:\tools\bazel
C:\tools\bazel\bazel.exe
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\extras\CUPTI\libx64

These are the system variables I've set:
BAZEL_SH  C:\tools\msys64\usr\bin\bash.exe
BAZEL_VC  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
BAZEL_VS  C:\Program Files (x86)\Microsoft Visual Studio 14.0

### Describe the problem
I keep getting this error when trying to build the tensorflow-gpu using bazel and python in Windows 10:

Cuda Configuration Error: Error reading C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/cuda/include/cudnn.h: ja
va.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(239): CreateProcessW("grep" --color=never -A1 -E "#de
fine CUDNN_MAJOR" "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/cuda/include/cudnn.h"): The system cannot fin
d the file specified.
This is the command I'm trying to run:
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

I've confirmed the C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/cuda/include/cudnn.h is there.

I've tried running it from VS2015 x64 Native Tools Command Prompt, cmd, and powershell and get the same error.

I'm using bazel 0.16.1, CUDA 9.2, Anaconda3 (Python 3.6.5), and CUDNN 7.2.1. I "installed" the CUDDNN files by unzipping its cuda folder into my C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2 folder (i.e. the whole "cuda" folder). I specified the C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\cuda path in the cudnn path question when I ran the configure.py. The configure.py completes without error.

I also tried putting the CUDNN files directly in the C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2 folder (instead of a cuda folder in there) and specified the default location and still get basically the same error: "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/include/cudnn.h": The system cannot find the file specified.

This is the full error:

ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package'
: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Trac
eback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1458
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1185, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 909, in _get_cuda_config
                _cudnn_version(repository_ctx, cudnn_install_base..., ...)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 584, in _cudnn_version
                find_cuda_define(repository_ctx, cudnn_header_dir, "c...", ...)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 534, in find_cuda_define
                auto_configure_fail(("Error reading %s: %s" % (str(h...)))
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 315, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Error reading C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/cuda/include/cudnn.h: ja
va.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(239): CreateProcessW("grep" --color=never -A1 -E "#de
fine CUDNN_MAJOR" "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/cuda/include/cudnn.h"): The system cannot fin
d the file specified.

WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_
defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1458
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1185, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 909, in _get_cuda_config
                _cudnn_version(repository_ctx, cudnn_install_base..., ...)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 584, in _cudnn_version
                find_cuda_define(repository_ctx, cudnn_header_dir, "c...", ...)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 534, in find_cuda_define
                auto_configure_fail(("Error reading %s: %s" % (str(h...)))
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 315, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Error reading C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/cuda/include/cudnn.h: ja
va.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(239): CreateProcessW("grep" --color=never -A1 -E "#de
fine CUDNN_MAJOR" "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/cuda/include/cudnn.h"): The system cannot fin
d the file specified.

### Source code / logs
Solution/workaround is:

The problem is a bug in cuda_configure.bzl: it uses ctx.execute instead of ctx.action.run_shell.
To work around it: add c:\tools\msys64\usr\bin to your PATH. That's where grep.exe is so ctx.execute can find grep on the PATH.

**Comment by gunan** [comment]
Thanks for debugging the problem.
Would you like to contribute a fix to cuda_configure.bzl ?

**Comment by rcorvus** [comment]
Definitely, I'll see what I can do.

**Comment by zacharymostowsky** [comment]
Hi @rcorvus I am in the exact same position as you. I did as you said and added msys64\usr\bin to my path but am still not seeing success. Any update on this issue?

Thanks,
Zach

**Comment by joseortiz3** [comment]
I don't know why this fix only works with Bazel 0.16.1. 
With Bazel 17.x, manually changing this line fixed my [`repository_ctx.execute`](https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html#execute) not finding grep:

In line 531 of cuda_configure.bzl:

```python
    result = repository_ctx.execute(
        # Grep one more lines as some #defines are splitted into two lines.
        ["grep", "--color=never", "-A1", "-E", define, str(h_path)],
        quiet=False
    )
```

Changing it to

```python
    result = repository_ctx.execute(
        # Grep one more lines as some #defines are splitted into two lines.
        ["C:/msys64/usr/bin/grep", "--color=never", "-A1", "-E", define, str(h_path)],
        quiet=False
    )
```

Meanwhile, changing the environment variable did not work, as @rcorvus pointed out.

Please fix this, I spent two hours on this. Obviously my "fix" is not universal, and I don't know of one that would be.

 Doesn't help that Bazel's error message seems to imply that `cuddn.h` couldn't be found, when in reality grep couldn't be found...

**Comment by alanpurple** [comment]
same problem, tensorflow bazel build is not ready for asian locale windows

this might be path-related

**Comment by dweekly** [comment]
Also had this issue building TF master from source with Bazel 0.19.2, and joseortiz3's suggested fix of manually specifying the path to the grep binary in cuda_configure.bzl (though now on line 562) unblocked my build.

**Comment by GPhilo** [comment]
The problem is still there in bazel 0.21 (the fix is also the same).

**Comment by jey07** [comment]
The problem still exist .

**Comment by mohantym** [comment]
Hi @rcorvus!
We are checking to see if you still need help on this issue. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. Thanks!
