### ISSUE TITLE
TensorFlowlite  加载模型报 it is probably compressed

### ISSUE THREAD

**Issue by sss0636** [tensorflow/tensorflow#22333]
android版本5.1
系统版本Windows
软件版本androidstudio3.0.1
模型 yolo_v2_7_448.tflite
程序调试到AssetFileDescriptor fileDescriptor = assets.openFd(modelFilename)时报错，”This file can not be opened as a file descriptor; it is probably compressed”

**Comment by adityakamble49** [comment]
I am facing the same issue
I referred [TFLite Poets 2](https://github.com/googlecodelabs/tensorflow-for-poets-2) example and [TFLite using Keras](https://www.youtube.com/watch?v=MZx1fhbL2q4)

I have _**linear.tflite**_ file in **android assets** directory
I am able to generate linear.tflite model but while accessing it from loadModel() method I am getting
```
java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
```

at line

```
AssetFileDescriptor fileDescriptor = activity.getAssets().openFd("linear.tflite"); // <- This Line
```

```
private MappedByteBuffer loadModelFile(Activity activity) throws IOException {
        AssetFileDescriptor fileDescriptor = activity.getAssets().openFd("linear.tflite"); // <- This Line
        FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
        FileChannel fileChannel = inputStream.getChannel();
        long startOffset = fileDescriptor.getStartOffset();
        long declaredLength = fileDescriptor.getDeclaredLength();
        return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
    }
```

Is there any other way to load **_tflite_** model to run prediction ?

**Comment by harshini-gadige** [comment]
#21245

**Comment by harshini-gadige** [comment]
@adityakamble49 Hi, can you try loading your model using tf.contrib.lite.Interpreter.

**Comment by wt-huang** [comment]
@sss0636 try adding the following in build.gradle in Android Studio then sync gradle:
android{
    aaptOptions {
        noCompress "tflite"
        noCompress "lite"
}

**Comment by shashishekhar** [comment]
@adityakamble49 : Try wt-huang's suggestion, I don't think this is related to #21245

**Comment by sss0636** [comment]
> @ sss0636尝试在Android Studio中的build.gradle中添加以下内容然后同步gradle：
> android { 
> aaptOptions { 
> noCompress“tflite” 
> noCompress“lite” 
> }

问题已解决

**Comment by adityakamble49** [comment]
Thanks @wt-huang , @shashishekhar. It worked. able to load model now
```
android{
aaptOptions {
noCompress "tflite"
noCompress "lite"
}
```
