### ISSUE TITLE
Feature Request: Add quadratic weighted kappa

### ISSUE THREAD

**Issue by fclof** [tensorflow/tensorflow#22341]
### System information
- **Have I written custom code**: No
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **Mobile device if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: GTX 1070 8G
- **Exact command to reproduce**: N/A

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem

Quadratic weighted kappa (qwk) is a frequently used evaluation criteria, and is used in many competitions, such as the Kaggle Diabetic Retinopathy Detection, Prudential Life Insurance Assessment, and Crowdflower Search Results Relevance, etc. 

It would be very helpful for those who actively take part in those competitions if a quadratic_weighted_kappa function can be added into tf.contrib.metrics.

Also, we already have cohen's kappa (tf.contrib.metrics.cohen_kappa) and confusion matrix (tf.contrib.metrics.confusion_matrix -> tf.confusion_matrix) . Adding qwk is consistent with the existing codes. 

Again, please add quadratic weighted kappa into tensorflow.

**Comment by ymodak** [comment]
@fclof  This will be an interesting feature addition to tf.contrib.metrics. Workaround will be to refer [quadratic_weighted_kappa](https://github.com/benhamner/Metrics/blob/master/Python/ml_metrics/quadratic_weighted_kappa.py)
Feel free to contribute PR for this feature, we will be glad to review it.

**Comment by bravenoob** [comment]
Any changes with this feature?
