### ISSUE TITLE
Bazel build fails for r1.11

### ISSUE THREAD

**Issue by kate-kate** [tensorflow/tensorflow#22355]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra 10.13.4
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.11
- **Python version**: 3.6.4
- **Bazel version (if compiling from source)**: 0.15.2-homebrew\
- **CUDA/cuDNN version**:  I use CPU-only tensorflow version
- **GPU model and memory**: Intel Iris Graphics 6100 / 1536 MB
- **Exact command to reproduce**: bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

Hello everyone!
I've updated tensorflow today, run ```./configure``` command succesfully, but then ```bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package``` command and it failed with error
```
ERROR: /private/var/tmp/_bazel_kate/8be913d8cdea6dd8174f0dac0a48c277/external/double_conversion/BUILD.bazel:12:1: undeclared inclusion(s) in rule '@double_conversion//:double-conversion':
this rule is missing dependency declarations for the following files included by 'external/double_conversion/double-conversion/fast-dtoa.cc':
  '/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stdint.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3.297s, Critical Path: 1.92s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```
This text was rendered after this command with ```--verbose_failures```  option

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Mobile device

**Comment by kate-kate** [comment]
**Mobile device** N/A
Also can't get, why error is pointing at the clang files, because I set "use clang: no" while configuring
I have updated python dependencies that were mentioned in installation guide. I have installed other versions of tensorflow successfully before. Now I've tried also to build it for 1.9 version, but I had another error:
```
ERROR: /Users/kate/tensorflow/tensorflow/core/BUILD:309:1: undeclared inclusion(s) in rule '//tensorflow/core:platform_base':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/platform/posix/env_time.cc':
  '/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stdint.h'
  '/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stddef.h'
  '/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/__stddef_max_align_t.h'
  '/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stdarg.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 17.712s, Critical Path: 2.16s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```
pointing some clang files as well

**Comment by wt-huang** [comment]
@kate-kate it looks like you are using XCode 10 beta. Have you tried OSX-10.13.5?

**Comment by kate-kate** [comment]
@wt-huang actually I'm not using XCode (it is not installed on my OS at all), that is why I configured tensorflow not to use clang. But anyway I have Xcode Command Line Tools installed and recently updated and here is the info about them 
```
MacBook-Pro-Ekaterina:~ kate$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Also sorry for misinformation, my OS version is 10.13.6 now

**Comment by kate-kate** [comment]
@wt-huang I have following files in my ```/private/var/tmp/_bazel_kate/8be913d8cdea6dd8174f0dac0a48c277/external/double_conversion``` directory:
```
MacBook-Pro-Ekaterina:~ kate$ ls /private/var/tmp/_bazel_kate/8be913d8cdea6dd8174f0dac0a48c277/external/double_conversion
3992066a95b823efc8ccc1baf82a1cfc73f6e9b8.zip	Makefile
AUTHORS						README.md
BUILD						SConstruct
BUILD.bazel					WORKSPACE
CMakeLists.txt					cmake
COPYING						double-conversion
Changelog					msvc
LICENSE						test
```

**Comment by kate-kate** [comment]
Finally solved by total reinstall of bazel. Thank you for help
