### ISSUE TITLE
[Feature Request] Making gradient boosted trees available outside tf.Estimator

### ISSUE THREAD

**Issue by calledbymountains** [tensorflow/tensorflow#22353]
**Feature Request**

Is there any ongoing discussion on making gradient boosted trees available outside of `tf.estimators` ?

Doing this will allow a wider range of experimentation than what is possible with `tf.estimators`.

**Comment by martinwicke** [comment]
@nataliaponomareva not sure whether you have plans to expose the underlying ops?

**Comment by nataliaponomareva** [comment]
boosted_trees_ops_op_lib has public visibility, so you can potentially use the ops as you wish in your graph. 
What's ur use case? what kind of experiments you can't do with an estimator?

**Comment by calledbymountains** [comment]
@nataliaponomareva  I specifically would like to jointly train a CNN/LSTM based pipeline with gradient boosted trees.  I could not find a concrete example of how to do this with an estimator.  That is the source of this feature request. If however it is possible to do it via tf.estimator, an example would be much welcome.

**Comment by nataliaponomareva** [comment]
You would have to write your own estimator (eg. model fn where you will call the ops from lstm and gbdts). An example of something like this is https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/boosted_trees/estimator_batch/dnn_tree_combined_estimator.py - you can get an idea on how to do it out of it (eg using hooks etc)
