### ISSUE TITLE
'module' object has no attribute 'conv3d' but only in Jupyter Notebook

### ISSUE THREAD

**Issue by akors** [tensorflow/tensorflow#2235]
Hi! This isn't really a bug, but more a support request.

I tried to use the new conv3d operations from 6a187ccddaebb741ea77fc3201c6e36625f0aadb, so I built a pip wheel from the latest sources, created a virtualenv called "tensorflow-dev" and instlled the wheel there.

Now I am running into weirdness that I cannot explain...

Python works:

```
$ python3
Python 3.5.1 (default, Mar  7 2016, 18:39:06) 
[GCC 5.3.1 20151207 (Red Hat 5.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
>>> tf.nn.conv3d
<function conv3d at 0x7fb58acc3400>
>>> 
```

Ipython works:

```
$ ipython3
Python 3.5.1 (default, Mar  7 2016, 18:39:06) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally

In [2]: tf.nn.conv3d
Out[2]: <function tensorflow.python.ops.gen_nn_ops.conv3d>
```

But the Jupyter notebook does not!!

```
In [1]: import tensorflow as tf
In [2]: tf.nn.conv3d
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-9e3b7db30b11> in <module>()
----> 1 tf.nn.conv3d

AttributeError: 'module' object has no attribute 'conv3d'
```

All three were started form the same shell, after activating the same virtualenv. I really can't explain this. Does anyone have any ideas what's wrong with my install?

**Comment by mrry** [comment]
Can you check the output of `which ipython3` to see if it is running the version inside your virtualenv? You may need to install it inside your virtualenv (e.g. using `pip install`) to get it to work.

**Comment by akors** [comment]
@mrry 

```
$ which ipython3
~/.virtualenvs/tensorflow-dev/bin/ipython3

$ which jupyter
~/.virtualenvs/tensorflow-dev/bin/jupyter

$ which python3
~/.virtualenvs/tensorflow-dev/bin/python3
```
the latter being a link to python3.5

I think I am having troubles with my jupyter install... Ipython and python3.5 use Python 3.5, but from within the Jupyter notebook:
```
>>> import sys
>>> print(sys.version)
3.4.3 (default, Mar 31 2016, 20:42:37) 
[GCC 5.3.1 20151207 (Red Hat 5.3.1-2)]
```

This is very strange. I will investigate further.

**Comment by akors** [comment]
So here is what happened: somehow, something installed a kernelspec for Jupyter in /usr/local/share/jupyter/kernels for my old python3.4 installation. I deleted the Kernelspec there, and Jupyter and the import of tf.nn.conv3d started working.

Sorry for the inconvenience.

**Comment by power9694** [comment]
Can i ask you something? 

In my case, There was a same error, 'module' object has no attribute 'conv3d'.
I used jupyter notebook and shell to run tf.nn.conv3d, but coudn't run it.
I typed this code " print(sys.version) ".
The result is 2.7.6 (default, Jun 22 2015, 17:58:13) 
Should i install another version of python in my computer to run tf.nn.conv3d??

**Comment by akors** [comment]
@power9694 

No, python 2.7 should definitely work with TensorFlow. What is your TensorFlow version?
conv3d should be present from version 0.9 on.

Could you run the following code:

```
import tensorflow
print(tensorflow.__version__)
print(tensorflow.__path__)
```

**Comment by power9694** [comment]
@akors 

I actually runned the code, print(tensorflow.__version__), and found that version of the tensorflow in my computer was 0.8.0. 
After i updated the version, i can run tf.nn.conv3d well.
Very thank you for your advice. :)

**Comment by Wason1** [comment]
@akors 

could you please go in to a little more detail about how to delete this kernel spec thing?
I'm new to tf. Thanks!

**Comment by Wason1** [comment]
Actually ignore that. I solved it by removing tensorflow and then reinstalling! I think it's because I installed the gpu and cpu versions then removed the cpu version to be left with a non-functional gpu version.

Or maybe it's just magic.
