### ISSUE TITLE
Can't separate by sentences when running word2vec model?

### ISSUE THREAD

**Issue by michelleowen** [tensorflow/tensorflow#2236]
In gensim word2vec, the input can be a list of sentences. However, in tensorflow word2vec, the input is a list of words (concatenate sentences together). Can you add the feature to separate by sentences to word2vec?
 I am using the following code: https://github.com/tensorflow/tensorflow/blob/r0.8/tensorflow/models/embedding/word2vec.py

**Comment by zheng-xq** [comment]
Adding @a-dai to comment.

**Comment by girving** [comment]
@a-dai can confirm, but I don't think anyone is working on this at the moment.  PRs are welcome, though!

**Comment by girving** [comment]
However, since this is about tensorflow/models, not tensorflow/tensorflow, it should be refiled at the right repo.
