### ISSUE TITLE
Example problem in tf.reduce_sum function documentation

### ISSUE THREAD

**Issue by dyanos** [tensorflow/tensorflow#22366]
I'm not sure about registering an issue for an documentation error here, I found that the name of argument "keep_dims" on example of tf.reduce_sum is wrong.

ref: https://www.tensorflow.org/versions/r1.11/api_docs/python/tf/reduce_sum

x = tf.constant([[1, 1, 1], [1, 1, 1]])
tf.reduce_sum(x)  # 6
tf.reduce_sum(x, 0)  # [2, 2, 2]
tf.reduce_sum(x, 1)  # [3, 3]
tf.reduce_sum(x, 1, **keepdims**=True)  # [[3], [3]]
tf.reduce_sum(x, [0, 1])  # 6

==>

x = tf.constant([[1, 1, 1], [1, 1, 1]])
tf.reduce_sum(x)  # 6
tf.reduce_sum(x, 0)  # [2, 2, 2]
tf.reduce_sum(x, 1)  # [3, 3]
tf.reduce_sum(x, 1, **keep_dims**=True)  # [[3], [3]]
tf.reduce_sum(x, [0, 1])  # 6

**Comment by ymodak** [comment]
@dyanos Thank you for your post. The arg: keep_dims in tf.reduce_sum() is deprecated and will be removed from future versions of TensorFlow. Please use arg: **keepdims** instead.
