### ISSUE TITLE
*** stack smashing detected ***: <unknown> terminated 已放弃 (核心已转储)

### ISSUE THREAD

**Issue by Yangxiu123321** [tensorflow/tensorflow#22374]
## describe problems：
1. ubuntu 18.04 cmake
2. c++ with libtensorflow_cc.so
3. I can compile my code,but when I run it,the error is "*** stack smashing detected ***: <unknown> terminated 已放弃 (核心已转储)"

## code
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/platform/env.h"

using namespace std;
using namespace chrono;
using namespace tensorflow;
int main(int argc, char* argv[]) {
  // SessionOptions options;
  // std::unique_ptr<tensorflow::Session> session(tensorflow::NewSession(options));
  Session *session = NewSession(SessionOptions());
  if(session == nullptr)
  {
    throw runtime_error("Could not create tensorflow session");
  }
  session->Close();
  return 0;
}
## So, what should I do?Thank you!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by Yangxiu123321** [comment]
### OS platform:ubuntu:16.04
### ensorflow install from source code
### tensorflow version:1.11(master branch)
### Bazel version:0.17.1
### CPU
## 1、comand:
bazel build --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --config=monolithic //tensorflow:libtensorflow_cc.so
bazel build --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --config=monolithic //tensorflow:libtensorflow_framework.so

sudo mkdir /usr/local/include/tf
sudo mkdir /usr/local/include/tf/tensorflow
sudo cp -r bazel-genfiles/ /usr/include/tf
sudo cp -r tensorflow/cc /usr/include/tf/tensorflow
sudo cp -r tensorflow/core /usr/include/tf/tensorflow
sudo cp -r third_party /usr/include/tf
sudo cp -r bazel-bin/tensorflow/libtensorflow_cc.so /usr/local/lib
sudo cp -r bazel-bin/tensorflow/libtensorflow_framework.so /usr/local/lib
## 2、code:
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/platform/env.h"

using namespace std;
using namespace chrono;
using namespace tensorflow;
int main(int argc, char* argv[]) {
// SessionOptions options;
// std::unique_ptrtensorflow::Session session(tensorflow::NewSession(options));
Session *session = NewSession(SessionOptions());
if(session == nullptr)
{
throw runtime_error("Could not create tensorflow session");
}
Status status = session->Close();
return 0;
}
## 3、the status is status.ok() is right,but the error is "*** stack smashing detected ***: terminated 已放弃 (核心已转储)"

**Comment by ymodak** [comment]
Closing this issue as new issue #22411 is opened with updated information.

**Comment by dawgster** [comment]
I'm facing the same issue with tensorflow 1.12. I'm trying to compile my project using our own build system and linking against the tensorflow_cc.so. Is that possible or will I have to find a way to build my code using bazel?
