### ISSUE TITLE
ERROR: /home/developer/tensorflow/tensorflow/BUILD:652

### ISSUE THREAD

**Issue by phalexo** [tensorflow/tensorflow#22393]
:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/developer/.cache/bazel/_bazel_developer/6acbce31a4e8077fc84a239074e8eda3/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/developer/.cache/bazel/_bazel_developer/6acbce31a4e8077fc84a239074e8eda3/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 70, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/developer/.cache/bazel/_bazel_developer/6acbce31a4e8077fc84a239074e8eda3/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/home/developer/.cache/bazel/_bazel_developer/6acbce31a4e8077fc84a239074e8eda3/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 27, in <module>
    from tensorflow.python.framework import function
  File "/home/developer/.cache/bazel/_bazel_developer/6acbce31a4e8077fc84a239074e8eda3/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 36, in <module>
    from tensorflow.python.ops import resource_variable_ops
  File "/home/developer/.cache/bazel/_bazel_developer/6acbce31a4e8077fc84a239074e8eda3/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/ops/resource_variable_ops.py", line 38, in <module>
    from tensorflow.python.ops import variables
  File "/home/developer/.cache/bazel/_bazel_developer/6acbce31a4e8077fc84a239074e8eda3/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/ops/variables.py", line 20, in <module>
    import enum  # pylint: disable=g-bad-import-order
ImportError: No module named enum
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1418.730s, Critical Path: 243.25s
INFO: 9922 processes: 9922 local.
FAILED: Build did NOT complete successfully

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by harshini-gadige** [comment]
@phalexo Can you please describe the problem clearly.

**Comment by phalexo** [comment]
Ubuntu 16.04, building TF from source with CUDA, MPI, NCCL 2.2 support. I modified the code with ToString proposed fix (not sure it has been committed into the master yet). So after that error was no more I ran into this build error. I've tried bazel 0.15, 0.16

INFO: From Compiling external/llvm/lib/Transforms/Scalar/JumpThreading.cpp:
external/llvm/lib/Transforms/Scalar/JumpThreading.cpp: In member function 'void llvm::JumpThreadingPass::UpdateBlockFreqAndEdgeWeight(llvm::BasicBlock*, llvm::BasicBlock*, llvm::BasicBlock*, llvm::BasicBlock*)':
external/llvm/lib/Transforms/Scalar/JumpThreading.cpp:2165:61: warning: '*((void*)& BBSuccFreq +16)' may be used uninitialized in this function [-Wmaybe-uninitialized]
       *std::max_element(BBSuccFreq.begin(), BBSuccFreq.end());
                                                             ^
ERROR: /home/developer/tensorflow/tensorflow/BUILD:652:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)

**Comment by phalexo** [comment]
bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --verbose_failures //tensorflow/tools/pip_package:build_pip_package

is the command line that was run.

**Comment by phalexo** [comment]
INFO: From Compiling tensorflow/compiler/xla/service/cpu/parallel_task_assignment.cc:
In file included from ./tensorflow/compiler/xla/service/hlo_computation.h:35:0,
                 from ./tensorflow/compiler/xla/service/hlo_cost_analysis.h:21,
                 from ./tensorflow/compiler/xla/service/cpu/parallel_task_assignment.h:20,
                 from tensorflow/compiler/xla/service/cpu/parallel_task_assignment.cc:16:
./tensorflow/compiler/xla/service/hlo_instruction.h: In member function 'void xla::HloInstruction::ReplaceCalledComputations(std::function<xla::HloComputation*(xla::HloComputation*)>)':
./tensorflow/compiler/xla/service/hlo_instruction.h:1119:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int64 i = 0; i < called_computations_.size(); ++i) {
                       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./tensorflow/core/platform/default/logging.h:24:0,
                 from ./tensorflow/core/platform/logging.h:25,
                 from ./tensorflow/core/lib/gtl/flatmap.h:26,
                 from ./tensorflow/compiler/xla/service/cpu/target_machine_features.h:22,
                 from ./tensorflow/compiler/xla/service/cpu/parallel_task_assignment.h:19,
                 from tensorflow/compiler/xla/service/cpu/parallel_task_assignment.cc:16:
./tensorflow/core/platform/default/logging.h: In instantiation of 'std::string* tensorflow::internal::Check_LEImpl(const T1&, const T2&, const char*) [with T1 = long long int; T2 = long unsigned int; std::string = std::basic_string<char>]':
./tensorflow/compiler/xla/shape_util.h:118:5:   required from here
./tensorflow/core/platform/default/logging.h:232:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 TF_DEFINE_CHECK_OP_IMPL(Check_LE, <=)
./tensorflow/core/platform/macros.h:88:49: note: in definition of macro 'TF_PREDICT_TRUE'
 #define TF_PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                 ^
./tensorflow/core/platform/default/logging.h:232:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_LE, <=)
 ^
In file included from ./tensorflow/compiler/xla/array2d.h:29:0,
                 from ./tensorflow/compiler/xla/literal.h:31,
                 from ./tensorflow/compiler/xla/service/dfs_hlo_visitor.h:24,
                 from ./tensorflow/compiler/xla/service/hlo_cost_analysis.h:20,
                 from ./tensorflow/compiler/xla/service/cpu/parallel_task_assignment.h:20,
                 from tensorflow/compiler/xla/service/cpu/parallel_task_assignment.cc:16:
./tensorflow/compiler/xla/array.h: In instantiation of 'bool xla::Array<T>::operator==(const xla::Array<T>&) const [with T = long long int]':
./tensorflow/compiler/xla/service/hlo_sharding.h:189:38:   required from here
./tensorflow/compiler/xla/array.h:421:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int64 i = 0; i < sizes_.size(); ++i) {
                       ~~^~~~~~~~~~~~~~~
ERROR: /home/developer/tensorflow/tensorflow/BUILD:652:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash failed: error executing command
  (cd /home/developer/.cache/bazel/_bazel_developer/6acbce31a4e8077fc84a239074e8eda3/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib: \
    PATH=/home/developer/anaconda3/envs/AI/bin:/home/developer/anaconda3/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1 --root_init_template=tensorflow/api_template.__init__.py --apidir=bazel-out/host/genfiles/tensorflow_api/v1/ --apiname=tensorflow --apiversion=1 --package=tensorflow.python --output_package=tensorflow._api.v1 bazel-out/host/genfiles/tensorflow/_api/v1/__init__.py bazel-out/host/genfiles/tensorflow/_a

**Comment by woshishui201020** [comment]
The problem has been solved. I have encountered this problem. I can’t solve it.

**Comment by woshishui201020** [comment]
Has the problem been solved? I also encountered this problem, how can I not solve it?

**Comment by BitRift** [comment]
Same here, Ubuntu 18.04, very latest CUDA, NCCL etc.

**Comment by gunan** [comment]
The failure is right in your logs:
```
ImportError: No module named enum
```
In the failing python distro, you may need to install enum.
