### ISSUE TITLE
tensorflow error in a docker container 

### ISSUE THREAD

**Issue by gnujimmik** [tensorflow/tensorflow#2239]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: ubuntu 14.04

Installed version of CUDA and cuDNN: 7.5 and 4 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide: 

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

If installed from sources, provide the commit hash:

### Steps to reproduce
1. Install tensorflow-gpu-devel
2. docker run the image
3. python and import tensorflow

### What have you tried?
1. Tried the example from tensorflow website: https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#test-the-tensorflow-installation

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so.4 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so.7.5 locally
>>> sess = tf.Session()
E tensorflow/stream_executor/cuda/cuda_driver.cc:481] failed call to cuInit: CUresult(-1)
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:114] retrieving CUDA diagnostic information for host: 18a61c37a941
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:121] hostname: 18a61c37a941
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:146] libcuda reported version is: Invalid argument: expected %d.%d form for driver version; got "1"
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:257] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.93  Tue Apr  5 18:18:24 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel reported version is: 352.93
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.

**Comment by gnujimmik** [comment]
Why do I have this error?

**Comment by zheng-xq** [comment]
The error says no GPU can be found on this machine. 

Could you run "nvidia-smi" and post the log?

**Comment by gnujimmik** [comment]
Host machine:

Fri May  6 08:34:30 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.93     Driver Version: 352.93         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:03:00.0     Off |                  N/A |
| 22%   35C    P8    15W / 250W |    135MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:04:00.0     Off |                  N/A |
| 22%   36C    P8    15W / 250W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 0000:81:00.0     Off |                  N/A |
| 22%   36C    P8    14W / 250W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 0000:82:00.0     Off |                  N/A |
| 22%   33C    P8    15W / 250W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1184    C   /usr/bin/python                                110MiB |
+-----------------------------------------------------------------------------+

and in the docker container, I can't run nvidia-smi. it says command not found.

**Comment by PatWie** [comment]
This is an Docker-Issue.

Docker does not support GPUs by the default settings. You can test:
https://github.com/NVIDIA/nvidia-docker

or add 

```
--device /dev/nvidia0:/dev/nvidia0 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-uvm:/dev/nvidia-uvm
```

**Comment by gnujimmik** [comment]
I already tried the both way. But still have the same message and tensor doesn't work with gpus.

**Comment by girving** [comment]
@martinwicke: It looks like our docker instructions are out of sync.  One of these says to use nvidia-docker; the other does not.

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker#running-the-container
https://www.tensorflow.org/versions/master/get_started/os_setup.html#docker-installation

Should they be synchronized?

**Comment by martinwicke** [comment]
caisq@, which one are the "correct" ones? There should definitely only be one version.

**Comment by girving** [comment]
Cc @jendap who said he was planning to synchronize the two places.

**Comment by alextp** [comment]
@jendap are you still working on this?

**Comment by aselle** [comment]
@caisq could you take a look at resolving this issue?

**Comment by aselle** [comment]
This appears to be fixed. Both recommend using nvidia-docker now.

**Comment by wangchuan** [comment]
Due some reasons, I am allowed to use official `docker` instead of `nvidia-docker` in my program. But I still need gpu access with Tensorflow, and I encountered the same problem as @gnujimmik posted. Do you have any ideas about it?
