### ISSUE TITLE
ValueError: Cannot set tensor: Got tensor of type 4 but expected type 2 for input 25

### ISSUE THREAD

**Issue by theavgguy** [tensorflow/tensorflow#22409]
I am trying to run a tensorflow model on device, using tensorflow lite. I was able to convert my .pb graph to a .lite graph. Using python interpreter as below

`interpreter = interpreter_wrapper.Interpreter(model_path=model_file)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
interpreter.set_tensor(input_details[0]['index'], candidates)`

the above code throws following error : ValueError: Cannot set tensor: Got tensor of type 4 but expected type 2 for input 25

I have no clue what tensor of type 4 and tensor of type 2 are, I am not sure if they are same as tensor ranks, in my case, the tensor ranks and types mentioned above don't seem to be the same.

**Comment by theavgguy** [comment]
I am trying to run a tensorflow model on device, using tensorflow lite. I was able to convert my .pb graph to a .lite graph. Using python interpreter as below

`interpreter = interpreter_wrapper.Interpreter(model_path=model_file)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details() 
interpreter.set_tensor(input_details[0]['index'], candidates)`

the above code throws following error : ValueError: Cannot set tensor: Got tensor of type 4 but expected type 2 for input 25

I have no clue what tensor of type 4 and tensor of type 2 are, I am not sure if they are same as tensor ranks, in my case, the tensor ranks and types mentioned above don't seem to be the same.

**Comment by wt-huang** [comment]
@theavgguy Just executed above code snippet with a simple model without running into any error. Type 2 or 4 is internal TFLite type casted from C++ type.  You would need to check your converted graph, or post your graph here.

**Comment by wt-huang** [comment]
Closing this now, feel free to open a new issue if encountering any errors.

**Comment by oneTaken** [comment]
@theavgguy 
Hello, I got this problem too.  
And I debug and find that type 2 or 4 in your case is the data type of the internal encoding which you can find clearly [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L142~L166). So you just need to cast your tensor with the same data type of your input.  

Hope that help you.

**Comment by theavgguy** [comment]
@oneTaken Yes I forgot to share my findings here. Been a busy month at work.
I found out that the problem was not with the tensor , but with numpy encoding. For each array I was creating I specified the data type to int32 and I was able to debug the issue. It would have been better though if tensorflow documented this error better as the error statement is of no help, it required a lot of reading of the code and hit and trial to debug and finally find the issue.
Thanks for your help.

**Comment by toby5box** [comment]
@theavgguy It is a remarkably bad error message. I'm fighting a similar one right now.

**Comment by SystemErrorWang** [comment]
got similar problem here, the error message is "ValueError: Cannot set tensor: Got tensor of type 2 but expected type 1 for input 0 ", i checked the input dtype by "print(interpreter.get_input_details())",  the output is "[{'name': 'Placeholder', 'index': 0, 'shape': array([  1, 160, 160,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]",  but i still got this error when i set the input dtype to be either int32 or float32

**Comment by wolterlw** [comment]
same error with float32 
```ValueError: Cannot set tensor: Got tensor of type 5 but expected type 1 for input 0```
strangely when I set a non-converted numpy array it only starts to bark when I invoke the interpreter
