### ISSUE TITLE
CUDA 10.0 and python 3.7 support

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#22401]
this is not an issue

more of a question, request

can tensorflowers give roadmap for CUDA 10.0(and of course, cuDNN 7.3 for CUDA 10.0) and python 3.7 support? and of course Ubuntu 18.04

CUDA 10.0 and python 3.7 already support Ubuntu 18.04

thank you always

**Comment by facaiy** [comment]
Linked to #20517 : Python 3.7 compatibility

**Comment by EwoutH** [comment]
In addition, [TensorRT 5](https://developer.nvidia.com/tensorrt#tensorrt-whats-new)

> **What's New in TensorRT 5 and TensorRT inference server**
> TensorRT 5 delivers up to 40x faster inference over CPU-only platforms through support for Turing GPUs, new INT8 APIs and optimizations. It uses multi-precision compute to dramatically speed up recommenders, neural machine translation, speech and natural language processing. With TensorRT 5, you can:
> - Speed up inference by 40x over CPUs for models such as translation using mixed precision on Turing Tensor Cores
> - Optimize inference models with new INT8 APIs and optimizations
> - Deploy applications to Xavier-based NVIDIA Drive platforms and the NVIDIA DLA accelerator (FP16 only)
> 
> In addition, TensorRT 5 supports Windows and the CentOS Operating System. TensorRT 5 RC is available for download now to members of the NVIDIA Developer Program.

**Comment by alanpurple** [comment]
@EwoutH 

good

TensorRT 5.0.0.10 RC for Ubuntu 1804 and CUDA 10.0

**Comment by beew** [comment]
Tensorflow 1.10.1 works with cuda 10.0 and tensorRT5.0.0, Just compiled on Ubuntu 16.04 (python 3.5) and did some tests. But no cudnn7.3 at this point from Nvidia's download site so have to use cudnn7.2 .

Tensorflow 1.11.0RC1 didn't build but it might have nothing to do with cuda 10

**Comment by harshini-gadige** [comment]
@alanpurple Hi, if you are looking for compatibility information, please find the links below.
For [Linux and Mac OS](https://www.tensorflow.org/install/source#tested_build_configurations)
[For Windows ](https://www.tensorflow.org/install/source_windows#tested_build_configurations)

**Comment by homieseven** [comment]
Just built 1.11.0rc1 with CUDA 10, cuDNN 7.3 on Ubuntu 18.04.

**Comment by vyse8** [comment]
I've been attempting to find a compatible Tensorflow version with the new RTX cards. Does anyone know if this exists yet? I tried building 1.11.0rc2 on Windows but it throws "Failed to load the native TensorFlow Runtime" message.

**Comment by gunan** [comment]
looks like CUDA 10 is GA.
It is too close to our 1.12 release cut. But we will have 1.13 with CUDA 10.

For python 3.7 support, we are ready to move, but we are waiting on our dependencies to cut releases that have python 3.7 compatibility.

**Comment by alanpurple** [comment]
@gunan 

thank you for precise and complete answer, maybe you can close this issue
