### ISSUE TITLE
Will it conflict installing by soucecode ,with installing by pip

### ISSUE THREAD

**Issue by liumilan** [tensorflow/tensorflow#2240]
I have install tensorflow by pip.
And Because I have to add some code in tensorflow ,so I need to build tensorflow by sourcecode.
And when run bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
it will report 
configure: error: zlib not installed
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.743s, Critical Path: 2.24s
But in fact ,I have install zlib.

INFO: Elapsed time: 2.743s, Critical Path: 2.24s
[@sjs_88_31 tensorflow]# yum install zlib
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * epel: mirrors.neusoft.edu.cn
_Package zlib-1.2.7-13.el7.x86_64 already installed and latest version
_Nothing to do
So how can I fixed it?
My Os is cenos7.1.

And how can i add souce files if just only using pip install?

**Comment by zheng-xq** [comment]
Please run with --verbose_failures and post the results. 

I am not sure whether Centos 7.1 is supported by bazel. You can also file a bazel bug to get more help on bazel issues.

**Comment by girving** [comment]
Closing for now due to insufficient information.  @liumilan: I am happy to reopen if there are more details.
