### ISSUE TITLE
[tensorflow ppc64le] Building tensorflow from source fails on power8 architecture machine

### ISSUE THREAD

**Issue by ghltshubh** [tensorflow/tensorflow#22400]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Red Hat Enterprise Linux Server 7.4 (Maipo)
- **Mobile devices**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 
- **Python version**: 3.5.6
- **Bazel version (if compiling from source)**: 0.14.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0 (tried with 4.8.x as well)
- **CUDA/cuDNN version**: 8.0/ 7.1.4
- **GPU model and memory**: NVIDIA P100
- **Exact command to reproduce**: bazel build //tensorflow/tools/pip_package:build_pip_package

**Output of the tf_collect_env.sh**

== cat /etc/issue ===============================================
Linux summitdev-login1 3.10.0-693.21.1.el7.ppc64le #1 SMP Fri Feb 23 14:02:56 EST 2018 ppc64le ppc64le ppc64le GNU/Linux
VERSION="7.4 (Maipo)"
VERSION_ID="7.4"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

== are we in docker =============================================
No

== compiler =====================================================
c++ (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux summitdev-login1 3.10.0-693.21.1.el7.ppc64le #1 SMP Fri Feb 23 14:02:56 EST 2018 ppc64le ppc64le ppc64le GNU/Linux

== check pips ===================================================
numpy      1.15.1   

== check for virtualenv =========================================
False    **(this is not true I created an environment and ran this script from inside that env)**

== tensorflow import ============================================

== env ==========================================================
LD_LIBRARY_PATH /autofs/nccs-svm1_sw/summitdev/.swci/1-compute/opt/spack/20180406/linux-rhel7-ppc64le/gcc-5.4.0/spectrum-mpi-10.2.0.0-20180110-6keaqyzn74d6t7ilr5wcmd4ovxjkxue7/lib:/sw/summitdev/gcc/5.4.0new/lib64:/sw/summitdev/cuda/8.0.61-1/lib64:/autofs/nccs-svm1_home/shubhankar/magma_install/lib:/autofs/nccs-svm1_home1/shubhankar/magma_install/lib:/autofs/nccs-svm1_home/shubhankar/magma_install/lib:/autofs/nccs-svm1_home1/shubhankar/magma_install/lib:/opt/ibm/spectrumcomputing/lsf/10.1/linux3.10-glibc2.17-ppc64le-csm/lib:/autofs/nccs-svm1_home1/shubhankar/miniconda3/envs/pytorch/lib:/autofs/nccs-svm1_home/shubhankar/miniconda3/envs/pytorch/lib:/autofs/nccs-svm1_home/shubhankar/pytorch/build/lib:/autofs/nccs-svm1_home1/shubhankar/pytorch/build/lib:/autofs/nccs-svm1_home/shubhankar/libcudnn7_7.0.3.11-1+cuda8.0_ppc64el/lib/powerpc64le-linux-gnu:/sw/summitdev/cuda/8.0.61-1/extras/CUPTI/lib64:/autofs/nccs-svm1_home1/shubhankar/miniconda3/envs/pytorch/lib:/autofs/nccs-svm1_home/shubhankar/miniconda3/envs/pytorch/lib:/autofs/nccs-svm1_home/shubhankar/pytorch/build/lib:/autofs/nccs-svm1_home1/shubhankar/pytorch/build/lib:/sw/summitdev/cuda/9.0.69/extras/CUPTI/lib64
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Wed Sep 19 23:25:19 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.46                 Driver Version: 390.46                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  Off  | 00000002:01:00.0 Off |                    0 |
| N/A   32C    P0    29W / 300W |     18MiB / 16280MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-SXM2...  Off  | 00000003:01:00.0 Off |                    0 |
| N/A   28C    P0    30W / 300W |     18MiB / 16280MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-SXM2...  Off  | 00000006:01:00.0 Off |                    0 |
| N/A   32C    P0    28W / 300W |     18MiB / 16280MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-SXM2...  Off  | 00000007:01:00.0 Off |                    0 |
| N/A   29C    P0    30W / 300W |     18MiB / 16280MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================

### Describe the problem
Building tensorflow from source fails on power architecture machine. I am following the instructions given [here](https://developer.ibm.com/tutorials/install-tensorflow-on-power/)

### Source code / logs
```
WARNING: Output base '/autofs/nccs-svm1_home1/shubhankar/.cache/bazel/_bazel_shubhankar/e74c0b81a4afde0b86e7c039eda6fc5e' is on NFS. This may lead to surprising failures and undetermined behavior.
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
    File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 1166
        _create_local_cuda_repository(repository_ctx)
    File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 995, in _create_local_cuda_repository
        _get_cuda_config(repository_ctx)
    File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 750, in _get_cuda_config
        _cudnn_version(repository_ctx, cudnn_install_base..., ...)
    File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 464, in _cudnn_version
        _find_cudnn_header_dir(repository_ctx, cudnn_install_base...)
    File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 707, in _find_cudnn_header_dir
        auto_configure_fail(("Cannot find cudnn.h under %s" ...))
    File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 210, in auto_configure_fail
        fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find cudnn.h under /autofs/nccs-svm1_home1/shubhankar/libcudnn7_7.0.3.11-1+cuda8.0_ppc64el/lib/powerpc64le-linux-gnu
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
    File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 1166
        _create_local_cuda_repository(repository_ctx)
    File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 995, in _create_local_cuda_repository
        _get_cuda_config(repository_ctx)
    File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 750, in _get_cuda_config
        _cudnn_version(repository_ctx, cudnn_install_base..., ...)
    File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 464, in _cudnn_version
        _find_cudnn_header_dir(repository_ctx, cudnn_install_base...)
    File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 707, in _find_cudnn_header_dir
        auto_configure_fail(("Cannot find cudnn.h under %s" ...))
    File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 210, in auto_configure_fail
        fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find cudnn.h under /autofs/nccs-svm1_home1/shubhankar/libcudnn7_7.0.3.11-1+cuda8.0_ppc64el/lib/powerpc64le-linux-gnu
INFO: Elapsed time: 0.197s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

**NOTE:** Don't have sudo access and can't modify /usr/local/* but have all dependencies installed.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Mobile device

**Comment by ghltshubh** [comment]
@gunan Nope I did.

**Comment by gunan** [comment]
the main problem is this 
```
Cuda Configuration Error: Cannot find cudnn.h under /autofs/nccs-svm1_home1/shubhankar/libcudnn7_7.0.3.11-1+cuda8.0_ppc64el/lib/powerpc64le-linux-gnu
```
It is looking for the cudnn headers in the wrong place.

**Comment by ghltshubh** [comment]
I guess cudnn.h usually lives inside /usr/local/cuda/ but I have cuda installed separately but I didn't find that file there either.

**Comment by wdirons** [comment]
Hi @ghltshubh , I can help you get TensorFlow compiled on Power (or perhaps point you to a whl file where it is already compiled.)

Some questions:

Do you want to use CUDA 8.0 and cuDNN 7.0 as those versions are old, or are you just using those levels because that is what is documented at that website? 

Can you share the contents of .tf_configure.bazelrc (in the root of your tensorflow directory) which will show me the paths you provided with the ./configure script.

**Comment by ghltshubh** [comment]
I am using CUDA 8.0 and cuDNN 7.0 just because those are mentioned on the website. I have CUDA 9.0 and cuDNN 7.0 as well. Contents of the .tf_configure.bazelrc

```
build --action_env PYTHON_BIN_PATH="/ccs/home/shubhankar/miniconda3/envs/tensorflow/bin/python"
build --action_env PYTHON_LIB_PATH="/ccs/home/shubhankar/miniconda3/envs/tensorflow/lib/python3.5/site-packages"
build --python_path="/ccs/home/shubhankar/miniconda3/envs/tensorflow/bin/python"
build --define with_jemalloc=true
build:gcp --define with_gcp_support=true
build:hdfs --define with_hdfs_support=true
build:s3 --define with_s3_support=true
build:kafka --define with_kafka_support=true
build:xla --define with_xla_support=true
build:gdr --define with_gdr_support=true
build:verbs --define with_verbs_support=true
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_CUDA="1"
build --action_env CUDA_TOOLKIT_PATH="/ccs/home/shubhankar/8.0.61-1/"
build --action_env TF_CUDA_VERSION="8.0"
build --action_env CUDNN_INSTALL_PATH="/autofs/nccs-svm1_home1/shubhankar/libcudnn7_7.0.3.11-1+cuda8.0_ppc64el/lib/powerpc64le-linux-gnu"
build --action_env TF_CUDNN_VERSION="7"
build --action_env TF_NCCL_VERSION="1"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="3.5,5.2"
build --action_env LD_LIBRARY_PATH="/autofs/nccs-svm1_sw/summitdev/.swci/1-compute/opt/spack/20180406/linux-rhel7-ppc64le/gcc-4.8.5/spectrum-mpi-10.2.0.0-20180110-kfmznqmxgfqvpxzgtkuhlaggidefbkjw/lib:/sw/summitdev/cuda/8.0.61-1/lib64:/autofs/nccs-svm1_home/shubhankar/magma_install/lib:/autofs/nccs-svm1_home1/shubhankar/magma_install/lib:/opt/ibm/spectrumcomputing/lsf/10.1/linux3.10-glibc2.17-ppc64le-csm/lib:/autofs/nccs-svm1_home1/shubhankar/miniconda3/envs/pytorch/lib:/autofs/nccs-svm1_home/shubhankar/miniconda3/envs/pytorch/lib:/autofs/nccs-svm1_home/shubhankar/pytorch/build/lib:/autofs/nccs-svm1_home1/shubhankar/pytorch/build/lib:/autofs/nccs-svm1_home/shubhankar/libcudnn7_7.0.3.11-1+cuda8.0_ppc64el/lib/powerpc64le-linux-gnu:/sw/summitdev/cuda/8.0.61-1/extras/CUPTI/lib64"
build --action_env TF_CUDA_CLANG="0"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/gcc"
build --config=cuda
test --config=cuda
build --define grpc_no_ares=true
build:opt --copt=-mcpu=power8
build:opt --copt=-mtune=power8
build:opt --define with_default_optimizations=true
build --strip=always

```

**Comment by wdirons** [comment]
I myself have never built with anything below CUDA 9.0, but it should be fine to build with either version.

Make sure /autofs/nccs-svm1_home1/shubhankar/libcudnn7_7.0.3.11-1+cuda8.0_ppc64el/lib/powerpc64le-linux-gnu/include/cudnn.h and /autofs/nccs-svm1_home1/shubhankar/libcudnn7_7.0.3.11-1+cuda8.0_ppc64el/lib/powerpc64le-linux-gnu/lib64/libcudnn.so* exists on your system. 

The build looks for the files in CUDNN_INSTALL_PATH/include and CUDNN_INSTALL_PATH/lib64. If CUDNN_INSTALL_PATH is not correct, correct it and try the build again.

**Comment by ghltshubh** [comment]
These are the only contents of my libcudnn7_7.0.3.11-1+cuda8.0_ppc64el
drwxr-xr-x  0 root   root        0 Sep 16  2017 ./
drwxr-xr-x  0 root   root        0 Sep 16  2017 ./usr/
drwxr-xr-x  0 root   root        0 Sep 16  2017 ./usr/share/
drwxr-xr-x  0 root   root        0 Sep 16  2017 ./usr/share/doc/
drwxr-xr-x  0 root   root        0 Sep 16  2017 ./usr/share/doc/libcudnn7/
-rw-r--r--  0 root   root        0 Aug 31  2017 ./usr/share/doc/libcudnn7/copyright
-rw-r--r--  0 root   root      158 Sep 16  2017 ./usr/share/doc/libcudnn7/changelog.Debian.gz
drwxr-xr-x  0 root   root        0 Sep 16  2017 ./usr/share/lintian/
drwxr-xr-x  0 root   root        0 Sep 16  2017 ./usr/share/lintian/overrides/
-rw-r--r--  0 root   root       45 Sep 16  2017 ./usr/share/lintian/overrides/libcudnn7
drwxr-xr-x  0 root   root        0 Sep 16  2017 ./usr/lib/
drwxr-xr-x  0 root   root        0 Sep 16  2017 ./usr/lib/powerpc64le-linux-gnu/
-rw-r--r--  0 root   root 217439272 Sep 16  2017 ./usr/lib/powerpc64le-linux-gnu/libcudnn.so.7.0.3
lrwxrwxrwx  0 root   root         0 Sep 16  2017 ./usr/lib/powerpc64le-linux-gnu/libcudnn.so.7 -> libcudnn.so.7.0.3


**NOTE:** I don't have dpkg installed on my system and I don't have permissions to install it either. So I downloaded libcudnn7_7.0.3.11-1+cuda8.0_ppc64el from [nvidia repo](https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/ppc64el/) on my macbook, extracted .deb file and converted it to tar.gz which I then sent to my install machine.

**Comment by ghltshubh** [comment]
No I can't build on docker as there is no root access. I will try these solutions and let you know.

**Comment by wdirons** [comment]
@ghltshubh , Any luck with your build?

**Comment by wdirons** [comment]
I renamed the build on Friday to include GPU in the name :) The URL is now:

 https://powerci.osuosl.org/job/TensorFlow_Ubuntu_16.04_PPC64LE_GPU_Release_Build/

**Comment by ghltshubh** [comment]
I don't get it why am I getting this error. I even created a symlink `ln -s /autofs/nccs-svm1_home1/shubhankar/cuda/targets/ppc64le-linux/include/cudnn.h /autofs/nccs-svm1_home1/shubhankar/cuda/targets/ppc64le-linux/lib/cudnn.h`
```
WARNING: Output base '/autofs/nccs-svm1_home1/shubhankar/.cache/bazel/_bazel_shubhankar/e74c0b81a4afde0b86e7c039eda6fc5e' is on NFS. This may lead to surprising failures and undetermined behavior.
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 1166
		_create_local_cuda_repository(repository_ctx)
	File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 995, in _create_local_cuda_repository
		_get_cuda_config(repository_ctx)
	File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 750, in _get_cuda_config
		_cudnn_version(repository_ctx, cudnn_install_base..., ...)
	File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 464, in _cudnn_version
		_find_cudnn_header_dir(repository_ctx, cudnn_install_base...)
	File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 707, in _find_cudnn_header_dir
		auto_configure_fail(("Cannot find cudnn.h under %s" ...))
	File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 210, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find cudnn.h under /autofs/nccs-svm1_home1/shubhankar/cuda/targets/ppc64le-linux/lib
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 1166
		_create_local_cuda_repository(repository_ctx)
	File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 995, in _create_local_cuda_repository
		_get_cuda_config(repository_ctx)
	File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 750, in _get_cuda_config
		_cudnn_version(repository_ctx, cudnn_install_base..., ...)
	File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 464, in _cudnn_version
		_find_cudnn_header_dir(repository_ctx, cudnn_install_base...)
	File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 707, in _find_cudnn_header_dir
		auto_configure_fail(("Cannot find cudnn.h under %s" ...))
	File "/autofs/nccs-svm1_home1/shubhankar/tensorflow/third_party/gpus/cuda_configure.bzl", line 210, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find cudnn.h under /autofs/nccs-svm1_home1/shubhankar/cuda/targets/ppc64le-linux/lib
INFO: Elapsed time: 0.258s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

**Comment by wdirons** [comment]
In .tf_configure.bazelrc
build --action_env CUDNN_INSTALL_PATH="/autofs/nccs-svm1_home1/shubhankar/cuda/targets/ppc64le-linux/lib"

need to drop the /lib at the end and change to:
build --action_env CUDNN_INSTALL_PATH="/autofs/nccs-svm1_home1/shubhankar/cuda/targets/ppc64le-linux"

It looks for CUDNN_INSTALL_PATH/include/cudnn,h

**Comment by ghltshubh** [comment]
I even copied cudnn.h to /autofs/nccs-svm1_home1/shubhankar/cuda/targets/ppc64le-linux/lib directory but it still can't find it.

**Comment by wdirons** [comment]
The whl file was compiled on an Ubuntu 16.04 system with glibc 2.22. I'm asking around if there is a way to compile it for an older version of glibc. 

For the message:
```
Invalid path to cuDNN 7 toolkit. None of the following files can be found:
/autofs/nccs-svm1_home1/shubhankar/cuda/targets/ppc64le-linux/lib64/libcudnn.so.7
```
it is looking for a lib64 (and not the lib directory) for libcudnn.so.7. Maybe symlink lib64 to lib?

**Comment by gunan** [comment]
Based on our experience with x86, there is no straightforward way to do it.
You can statically link glibc and libstdcxx into your binary, but that can cause other problems.

**Comment by wdirons** [comment]
Thanks @gunan for the comment about building on ububtu 14, I'll see if i'm able to switch our build process to use an ubuntu 14 container.

**Comment by wdirons** [comment]
@ghltshubh, that comment references compiling with a different level of glibc, the issue you have when using the whl file is at runtime.

From my stand point it will probably be easier to me to compile with an ubuntu 14.04 container then use those instructions. Thanks.

**Comment by ghltshubh** [comment]
@wdirons Tried various permutations and combinations of bazel, tf, gcc, cuda and this is the least error I could achieve. Similar error showed up using different versions as well.. The following is using bazel 0.13.1, tf 1.8.0 and gcc 4.8.5 and cuda 9.0

```
ERROR: /autofs/nccs-svm1_home1/shubhankar/tensorflow/tensorflow/contrib/framework/BUILD:101:1: output 'tensorflow/contrib/framework/_objs/python/ops/_variable_ops_gpu/tensorflow/contrib/framework/kernels/zero_initializer_op_gpu.cu.pic.o' was not created
ERROR: /autofs/nccs-svm1_home1/shubhankar/tensorflow/tensorflow/contrib/framework/BUILD:101:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 232.502s, Critical Path: 97.67s
INFO: 3268 processes, local.
FAILED: Build did NOT complete successfully
```

**Comment by ghltshubh** [comment]
Was able to build tf v1.8 https://developer.ibm.com/tutorials/install-tensorflow-on-power/ had to downgrade bazel to 0.11.0.

**Comment by ghltshubh** [comment]
@wdirons How did you build the tf wheel? Is their any recipe that I could follow to safely build it so that I can distribute it. Thanks.

**Comment by ghltshubh** [comment]
oh ok got it. Btw which NCCL version does it use. Can I build it using NCCL 2.x?

**Comment by wdirons** [comment]
From the contents of .tf_configure.bazelrc posted above, I see you answered nccl 1 in ./configure

NCCL2 will work, just download the os/agnostic package from: https://developer.nvidia.com/nccl/nccl-download and extract the file and use .configure to point at the directory containing the include and lib (or lib64) directory.

**Comment by ghltshubh** [comment]
I tried linking nccl-2.2.13 but it failed I am not sure if it's path issue or legacy bazel version.

```
ERROR: /autofs/nccs-svm1_home1/shubhankar/tensorflow/tensorflow/contrib/nccl/BUILD:23:1: Linking of rule '//tensorflow/contrib/nccl:python/ops/_nccl_ops.so' failed (Exit 1)
/usr/bin/ld: skipping incompatible bazel-out/ppc-opt/bin/_solib_local/_U@local_Uconfig_Unccl_S_S_Cnccl___Uexternal_Slocal_Uconfig_Unccl_Snccl_Slib/libnccl.so.2 when searching for -l:libnccl.so.2
/usr/bin/ld: skipping incompatible bazel-out/ppc-opt/bin/_solib_local/_U@local_Uconfig_Unccl_S_S_Cnccl___Uexternal_Slocal_Uconfig_Unccl_Snccl_Slib/libnccl.so.2 when searching for -l:libnccl.so.2
/usr/bin/ld: cannot find -l:libnccl.so.2
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 988.531s, Critical Path: 771.31s
FAILED: Build did NOT complete successfully
```

**Comment by gunan** [comment]
We just upgraded the master to NCCL 2.3, which is opensource.
Could you retry?

**Comment by ghltshubh** [comment]
I tried installing tf 1.8 NCCL 2.3 built from source but got the following error:

`ERROR: /autofs/nccs-svm1_home1/shubhankar/tensorflow/tensorflow/BUILD:541:1: Executing genrule //tensorflow:python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/shubhankar/.cache/bazel/_bazel_shubhankar/e74c0b81a4afde0b86e7c039eda6fc5e/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/autofs/nccs-svm1_home1/shubhankar/.cache/bazel/_bazel_shubhankar/e74c0b81a4afde0b86e7c039eda6fc5e/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/autofs/nccs-svm1_home1/shubhankar/.cache/bazel/_bazel_shubhankar/e74c0b81a4afde0b86e7c039eda6fc5e/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/ccs/home/shubhankar/miniconda3/envs/tf_p3.5/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/ccs/home/shubhankar/miniconda3/envs/tf_p3.5/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /autofs/nccs-svm1_home1/shubhankar/.cache/bazel/_bazel_shubhankar/e74c0b81a4afde0b86e7c039eda6fc5e/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: LLVMInitializePowerPCTargetMC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/shubhankar/.cache/bazel/_bazel_shubhankar/e74c0b81a4afde0b86e7c039eda6fc5e/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.util import tf_decorator
  File "/autofs/nccs-svm1_home1/shubhankar/.cache/bazel/_bazel_shubhankar/e74c0b81a4afde0b86e7c039eda6fc5e/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/autofs/nccs-svm1_home1/shubhankar/.cache/bazel/_bazel_shubhankar/e74c0b81a4afde0b86e7c039eda6fc5e/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/shubhankar/.cache/bazel/_bazel_shubhankar/e74c0b81a4afde0b86e7c039eda6fc5e/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/autofs/nccs-svm1_home1/shubhankar/.cache/bazel/_bazel_shubhankar/e74c0b81a4afde0b86e7c039eda6fc5e/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/autofs/nccs-svm1_home1/shubhankar/.cache/bazel/_bazel_shubhankar/e74c0b81a4afde0b86e7c039eda6fc5e/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/ccs/home/shubhankar/miniconda3/envs/tf_p3.5/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/ccs/home/shubhankar/miniconda3/envs/tf_p3.5/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /autofs/nccs-svm1_home1/shubhankar/.cache/bazel/_bazel_shubhankar/e74c0b81a4afde0b86e7c039eda6fc5e/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: LLVMInitializePowerPCTargetMC


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 324.978s, Critical Path: 159.69s
FAILED: Build did NOT complete successfully`

**Comment by ghltshubh** [comment]
I was able to build tf 1.8 with os agnostic NCCL 2.3 build from source with minor changes to NCCL.
Symlink LICENSE.txt in nccl dir to NCCL-SLA.txt
