### ISSUE TITLE
Core dumped error for specific example codes (virtualenv related?)

### ISSUE THREAD

**Issue by kglore** [tensorflow/tensorflow#2241]
Hi there,

I have installed TensorFlow on my system, and was able to run some examples just fine on the gpu: (e.g. 0_multiply.py, 1_linear_regression.py, 4_modern_net.py, etc). However, when I try to run some CNN-related codes, I am getting a core-dumped error.

### Environment info
Operating System: Ubuntu 14.04, TensorFlow installed in virtualenv

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

> -rw-r--r-- 1 root root   322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
> lrwxrwxrwx 1 root root       16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
> lrwxrwxrwx 1 root root       19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
> -rwxr-xr-x 1 root root   383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
> -rw-r--r-- 1 root root   720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
> lrwxrwxrwx 1 root root       13 May  5 12:48 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
> lrwxrwxrwx 1 root root       17 May  5 12:48 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.0.4
> -rwxrwxr-x 1 root root 59823168 Mar 21 20:37 /usr/local/cuda/lib64/libcudnn.so.5.0.4
> -rwxr-xr-x 1 root root 19340472 Apr 19 09:43 /usr/local/cuda/lib64/libcudnn.so.6.5
> -rwxr-xr-x 1 root root 19340472 Apr 19 09:43 /usr/local/cuda/lib64/libcudnn.so.6.5.18
> -rw-rw-r-- 1 root root 58734618 Mar 21 20:37 /usr/local/cuda/lib64/libcudnn_static.a

I installed TF using this page: https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#virtualenv-installation
via virtualenv. I needed virtualenv because I don't want it to screw with my python/Theano.

### Steps to reproduce
1. Running 5_convolutional_net.py will produce the log file.

### What have you tried?
I'm using CUDA 7.5, so I tried reinstalling CUDA 7.0 and CUDA 6.5

### Logs or other output that would be helpful

> I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0)
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX TITAN Black, pci bus id: 0000:03:00.0)
> Building graph...
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0)
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX TITAN Black, pci bus id: 0000:03:00.0)
> Exception AssertionError: AssertionError() in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x7f4bf7816390>> ignored
> F tensorflow/stream_executor/cuda/cuda_dnn.cc:204] could not find cudnnCreateTensorDescriptor in cudnn DSO; dlerror: /usr/local/lib/libcudnn.so: undefined symbol: cudnnCreateTensorDescriptor
> Aborted (core dumped)

Thanks for your help! It was able to use my GPU fine for other codes, not particularly the ones involving CNNs.

**Comment by EelcovdW** [comment]
I was experiencing this error too, redownloading and reinstalling cudnn (4.0.7) worked for me.

**Comment by Retoro** [comment]
I used
cudnn-6.5-linux-x64-v2.tgz of 
Download cuDNN v2 (March 17,2015), for CUDA 6.5 and later.

**Comment by EelcovdW** [comment]
That might be the problem. as written [here]https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#requirements), prebuilt GPU version works with cuda 7.5 + cuDNN v4. Try it with 4.0.7, and see if it works.

**Comment by girving** [comment]
@martinwicke: Is there a convenient way to report error message in this case instead of crashing?

**Comment by martinwicke** [comment]
I don't know. @zheng-xq? 

This is almost certainly due to the version conflict. Our binaries are built against cudnn4, Cuda 7.5. Any other version will have some problem like this.
