### ISSUE TITLE
CUDNN_STATUS_ALLOC_FAILED

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#22414]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no, it's on examples/tutorial/mnist,  mnist_deep.py
- **Bazel version**: N/A
- **Mobile device**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows 10 x64 latest build
- **TensorFlow installed from (source or binary)**: binary prebuilt 
- **TensorFlow version (use command below)**: 1.11.0rc1
- **Python version**: 3.6.6
- **CUDA/cuDNN version**: 9.0/7.2.1
- **GPU model and memory**: GTX1050Ti GDDR5 4GB
- **Exact command to reproduce**: 
1. python mnist_deep.py
E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED

2. other codes are fine-working as before

3. no problem with my laptop, which has geforce mx150 GDDR5 2GB

all this happens after I installed geforce driver 411.63

### Source code / logs
PS D:\VSWorkspace\tensorflow\tensorflow\examples\tutorials\mnist> python .\mnist_deep.py
WARNING:tensorflow:From .\mnist_deep.py:130: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From C:\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future versi
on.
Instructions for updating:
Please write your own downloading logic.
WARNING:tensorflow:From C:\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future vers
ion.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/tensorflow/mnist/input_data\train-images-idx3-ubyte.gz
WARNING:tensorflow:From C:\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future vers
ion.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/tensorflow/mnist/input_data\train-labels-idx1-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data\t10k-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data\t10k-labels-idx1-ubyte.gz
WARNING:tensorflow:From C:\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future ve
rsion.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Saving graph to: C:\Users\alanp\AppData\Local\Temp\tmpxpinc32v
2018-09-20 22:10:32.455130: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-09-20 22:10:32.641187: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.4175
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2018-09-20 22:10:32.659090: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-09-20 22:10:33.556406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-20 22:10:33.565294: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2018-09-20 22:10:33.571150: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2018-09-20 22:10:33.578487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3013 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus
id: 0000:01:00.0, compute capability: 6.1)
2018-09-20 22:10:36.376573: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Mobile device

**Comment by alanpurple** [comment]
@tensorflowbutler  updated

**Comment by facaiy** [comment]
@zheng-xq @zhangyaobit @alextp Could you comment or reassign?

**Comment by alextp** [comment]
@azaks2 do you know if there is a known issue with this driver version?

**Comment by tfboyd** [comment]
I would upgrade to cuDNN 7.3 (7.2 is no longer supported on the NVIDIA site and we are going to downgrade to 7.1.4 for our builds but anything over 7.1 will work).  The 411 driver is really new and likely more aligned with CUDA 10 but I have no data points even on Linux at this time as to combinations I know work.  

My advice (with no data points I am sorry):
-  Upgrade to cuDNN 7.3
-  Consider downgrading to an older Device Driver like 396 but I realized that is really hard on windows as it tries to keep you on the latest possible version.  I would likely do this as a last resort.

**Comment by alanpurple** [comment]
@tfboyd 
with cudnn 7.3, same

but thank you anyway, I'd rather stick with ubuntu this moment and leave this pc for a while

**Comment by mjohenneken** [comment]
For people searching the keyword CUDNN_STATUS_ALLOC_FAILED
 and finding this issue. You may check if there is another process allocating the gpu. In my case i got this error on terminal after previously running tensorflow from a jupyter notebook
