### ISSUE TITLE
Tensor2Tensor Intro tensorflow.python.framework.errors_impl.OutOfRangeError: Read fewer bytes than requested

### ISSUE THREAD

**Issue by davypepe** [tensorflow/tensorflow#22412]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
windows 10, x64
- **TensorFlow installed from (source or binary)**:
 pip (pip install --upgrade tensorflow)
- **TensorFlow version (use command below)**:
1.10.0
- **Python version**:
3.6
- **GPU model and memory**:
not using GPU, 12GB memory
Mobile device: N/A
Bazel version : N/A
CUDA/cuDNN version : N/A

### Describe the problem 
I'm trying to make the Tensor2Tensor intro: English to German translation with a pre-trained model work locally. I have downloaded the checkpoints to the right directory, however it's returning this error:
tensorflow.python.framework.errors_impl.OutOfRangeError: Read fewer bytes than requested

As you can see the checkpoints are in the proper directory:
![image](https://user-images.githubusercontent.com/24248699/45819470-ac0e8c00-bce4-11e8-85bf-fccc4e2e7c22.png)

I have tried redownloading the checkpoints many times, I can't seem to get the English to German translation working with the provided checkpoints.
@lukaszkaiser 

- **Exact command to reproduce**:

```
# Imports we need.
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import os
import collections

from tensor2tensor import models
from tensor2tensor import problems
from tensor2tensor.layers import common_layers
from tensor2tensor.utils import trainer_lib
from tensor2tensor.utils import t2t_model
from tensor2tensor.utils import registry
from tensor2tensor.utils import metrics

# Enable TF Eager execution
tfe = tf.contrib.eager
tfe.enable_eager_execution()

# Other setup
Modes = tf.estimator.ModeKeys

# Setup some directories
data_dir = os.path.expanduser("~/t2t-ende/data")
tmp_dir = os.path.expanduser("~/t2t-ende/tmp")
train_dir = os.path.expanduser("~/t2t-ende/train")
checkpoint_dir = os.path.expanduser("~/t2t-ende/checkpoints")
tf.gfile.MakeDirs(data_dir)
tf.gfile.MakeDirs(tmp_dir)
tf.gfile.MakeDirs(train_dir)
tf.gfile.MakeDirs(checkpoint_dir)
gs_data_dir = "gs://tensor2tensor-data"
gs_ckpt_dir = "gs://tensor2tensor-checkpoints/"

# Fetch the problem
ende_problem = problems.problem("translate_ende_wmt32k")

# Copy the vocab file locally so we can encode inputs and decode model outputs
# All vocabs are stored on GCS
vocab_name = "vocab.translate_ende_wmt32k.32768.subwords"
vocab_file = os.path.join(gs_data_dir, vocab_name)

# Get the encoders from the problem
encoders = ende_problem.feature_encoders(data_dir)

# Setup helper functions for encoding and decoding


def encode(input_str, output_str=None):
    """Input str to features dict, ready for inference"""
    inputs = encoders["inputs"].encode(input_str) + [1]  # add EOS id
    batch_inputs = tf.reshape(inputs, [1, -1, 1])  # Make it 3D.
    return {"inputs": batch_inputs}


def decode(integers):
    """List of ints to str"""
    integers = list(np.squeeze(integers))
    if 1 in integers:
        integers = integers[:integers.index(1)]
    return encoders["inputs"].decode(np.squeeze(integers))

# Generate and view the data
# This cell is commented out because WMT data generation can take hours


ende_problem.generate_data(data_dir, tmp_dir)
example = tfe.Iterator(ende_problem.dataset(Modes.TRAIN, data_dir)).next()
inputs = [int(x) for x in example["inputs"].numpy()]  # Cast to ints.
targets = [int(x) for x in example["targets"].numpy()]  # Cast to ints.

# Example inputs as int-tensor.
print("Inputs, encoded:")
print(inputs)
print("Inputs, decoded:")
# Example inputs as a sentence.
print(decode(inputs))
# Example targets as int-tensor.
print("Targets, encoded:")
print(targets)
# Example targets as a sentence.
print("Targets, decoded:")
print(decode(targets))

# Create hparams and the model
model_name = "transformer"
hparams_set = "transformer_base"

hparams = trainer_lib.create_hparams(
    hparams_set, data_dir=data_dir, problem_name="translate_ende_wmt32k")

# NOTE: Only create the model once when restoring from a checkpoint; it's a
# Layer and so subsequent instantiations will have different variable scopes
# that will not match the checkpoint.
translate_model = registry.model(model_name)(hparams, Modes.EVAL)

# Copy the pretrained checkpoint locally
ckpt_name = "transformer_ende_test"
gs_ckpt = os.path.join(gs_ckpt_dir, ckpt_name)
ckpt_path = tf.train.latest_checkpoint(os.path.join(checkpoint_dir, ckpt_name))

# Restore and translate!
def translate(inputs):
    encoded_inputs = encode(inputs)
    print(encoded_inputs)
    with tfe.restore_variables_on_create(ckpt_path):
        model_output = translate_model.infer(encoded_inputs)["outputs"]
        print(model_output)
    return decode(model_output)


inputs = "The animal didn't cross the street because it was too tired"
outputs = translate(inputs)

print("Inputs: %s" % inputs)
print("Outputs: %s" % outputs)`
```

### Source code / logs
>>> def translate(inputs):
...     encoded_inputs = encode(inputs)
...     print(encoded_inputs)
...     with tfe.restore_variables_on_create(ckpt_path):
...         model_output = translate_model.infer(encoded_inputs)["outputs"]
...         print(model_output)
...     return decode(model_output)
...
>>> inputs = "The animal didn't cross the street because it was too tired"
>>> outputs = translate(inputs)
{'inputs': <tf.Tensor: id=202, shape=(1, 15, 1), dtype=int32, numpy=
array([[[   28],
        [ 4705],
        [ 6253],
        [   83],
        [   62],
        [ 3444],
        [    4],
        [ 3825],
        [  244],
        [   40],
        [   53],
        [  362],
        [19285],
        [   85],
        [    1]]])>}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in translate
  File "C:\Users\david.salsbach\AppData\Local\Programs\Python\Python36\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\david.salsbach\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\eager\python\saver.py", line 91, in restore_variables_on_create
    ckpt_var_cache[k] = reader.get_tensor(k)
  File "C:\Users\david.salsbach\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 348, in get_tensor
    status)
  File "C:\Users\david.salsbach\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.OutOfRangeError: Read fewer bytes than requested
>>> print("Inputs: %s" % inputs)
Inputs: The animal didn't cross the street because it was too tired
>>> print("Outputs: %s" % outputs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'outputs' is not defined

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Mobile device

**Comment by wt-huang** [comment]
@davypepe From your screenshot it appears that at least some of the files were not downloaded completely. You may consider switching to GPU or use [Git LFS](https://git-lfs.github.com/).

**Comment by davypepe** [comment]
@wt-huang Thanks! I'll try that out and close the issue for now! 😎
