### ISSUE TITLE
Native compilation of Tensorflow on ARMv8 platforms fail

### ISSUE THREAD

**Issue by xiaomin05** [tensorflow/tensorflow#22424]
------------------------

### System information
== cat /etc/issue ===============================================
Linux ad96b38fdef35570b0c421cb8b68608f.lsdk.generic.ls1046ardb.nxp 4.14.47 #1 SMP PREEMPT Sat Jun 23 08:17:00 CST 2018 aarch64 aarch64 aarch64 GNU/Linux
VERSION="18.04 LTS (Bionic Beaver)"                                                                                                                     
VERSION_ID="18.04"                                                                                                                                      
VERSION_CODENAME=bionic                                                                                                                                 
== are we in docker =============================================
No                                                               

== compiler =====================================================
c++ (Ubuntu/Linaro 7.3.0-16ubuntu3) 7.3.0                        
Copyright (C) 2017 Free Software Foundation, Inc.                
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux ad96b38fdef35570b0c421cb8b68608f.lsdk.generic.ls1046ardb.nxp 4.14.47 #1 SMP PREEMPT Sat Jun 23 08:17:00 CST 2018 aarch64 aarch64 aarch64 GNU/Linux

== check pips ===================================================
numpy (1.13.3)
protobuf (3.6.0)
tensorflow (1.10.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.10.0
tf.GIT_VERSION = v1.10.0-0-g656e7a2b34
tf.COMPILER_VERSION = v1.10.0-0-g656e7a2b34
Sanity check: array([1], dtype=int32)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
ImportError: No module named platform

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tools/tf_env_collect.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

### Describe the problem
Native compilation on ARMv8 platform fails, due to tensorflow-lite 
Patch is copied below. Please incorporate them in the next release. thanks.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Patch file is copied below
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
diff --git a/tensorflow/contrib/lite/build_def.bzl b/tensorflow/contrib/lite/build_def.bzl
index b735d08b4b..4f333f079d 100644                                                       
--- a/tensorflow/contrib/lite/build_def.bzl                                               
+++ b/tensorflow/contrib/lite/build_def.bzl                                               
@@ -14,8 +14,8 @@ def tflite_copts():                                                     
               "-O3",                                                                     
           ],                                                                             
           str(Label("//tensorflow:android_arm")): [
-              "-mfpu=neon",
-              "-mfloat-abi=softfp",
+              #"-mfpu=neon",
+              #"-mfloat-abi=softfp",
               "-std=c++11",
               "-O3",
           ],
diff --git a/tensorflow/contrib/lite/kernels/internal/BUILD b/tensorflow/contrib/lite/kernels/internal/BUILD
index 3a855fe3dd..c013313512 100644
--- a/tensorflow/contrib/lite/kernels/internal/BUILD
+++ b/tensorflow/contrib/lite/kernels/internal/BUILD
@@ -21,7 +21,7 @@ HARD_FP_FLAGS_IF_APPLICABLE = select({
 NEON_FLAGS_IF_APPLICABLE = select({
     ":arm": [
         "-O3",
-        "-mfpu=neon",
+        #"-mfpu=neon",
     ],
     ":armeabi-v7a": [
         "-O3",
diff --git a/third_party/png.BUILD b/third_party/png.BUILD
index 17c5449cc0..7b095cbc36 100644
--- a/third_party/png.BUILD
+++ b/third_party/png.BUILD
@@ -42,6 +42,7 @@ cc_library(
     ],
     includes = ["."],
     linkopts = ["-lm"],
+    copts = ["-DPNG_ARM_NEON_OPT=0"],
     visibility = ["//visibility:public"],
     deps = ["@zlib_archive//:zlib"],
 )

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment]
@xiaomin05 Thanks for catching this. Please submit PR and we will gladly review.

**Comment by freedomtan** [comment]
With bazel >= 0.16, which comes with better support for ARMv8, and my patch (https://github.com/tensorflow/tensorflow/pull/16175), TF Lite related stuff should work.

**Comment by xiaomin05** [comment]
Here is the requested info:
=================================
Have I written custom code
Ans: No
 OS Platform and Distribution
Ans: Ubuntu userland 16.04
 TensorFlow installed from
Ans: https://github.com/tensorflow/tensorflow, tag: v1.10.0
 TensorFlow version
Ans: v1.10.0
 Bazel version
Ans: v0.15.2
 CUDA/cuDNN version
Ans: not used
 GPU model and memory
Ans: not used
 Exact command to reproduce
Ans: bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
 Mobile device
Ans: Not used

**Comment by wt-huang** [comment]
@freedomtan Thanks for the patch. @xiaomin05 Feel free to submit PR or patch for older Bazel versions.
