### ISSUE TITLE
TensorFlow installs open source Keras

### ISSUE THREAD

**Issue by TimZaman** [tensorflow/tensorflow#22426]
Installing TensorFlow (1.11.rc1) installs open source Keras. I don't think that's intentional, and things might get confusing.

In my bazel build system, that's a problem as there's a circular dependency as my keras depends on tensorflow, and tensorflow now depends on keras. (although it's true that open source keras does not explicitly list TF as a dependency)

This happens because of the new dependncy on keras-applications and keras-preprocessing that both depend on `keras` (open source version).

pip dependency tree of `tensorflow-gpu==1.11.0rc1`:

```
tensorflow-gpu==1.11.0rc1
  (...)
  - keras-applications [required: >=1.0.5, installed: 1.0.5]
    (...)
    - keras [required: >=2.1.6, installed: 2.2.0]
  (...)
  - keras-preprocessing [required: >=1.0.3, installed: 1.0.3]
    - keras [required: >=2.1.6, installed: 2.2.0]
  (...)
(...)
```

**Comment by gunan** [comment]
@fchollet @martinwicke Is this dependency intentional?

**Comment by martinwicke** [comment]
@fchollet has removed the Keras dependency from applications and preprocessing. Thanks for reporting this.
