### ISSUE TITLE
pip official package compiled differently with package in docker image?

### ISSUE THREAD

**Issue by u2takey** [tensorflow/tensorflow#22431]
I am working on filesystem plugin, a .so file, which works fine with official tensorflow pip package, but with tensorflow in tensorflow/tensorflow:1.7.0, i got error  `_ZN10tensorflow10FileSystem10FilesExistERKSt6vectorISsSaISsEEPS1_INS_6StatusESaIS6_EE`

Seems tensorflow from pypi package is different from package in docker image?
I checked docker hub image history `tensorflow/tensorflow:1.7.0` with docker history
```
/bin/sh -c pip --no-cache-dir install /tensorflow-1.7.0-cp27-cp27mu-manylinux1_x86_64.whl
``` 
seems tensorflow is install from local wal, and tensorflow size is `16533200` and symbol i want to find missing

```
-rwxr-xr-x  1 root staff 16533200 Mar 29 17:04 libtensorflow_framework.so*

nm libtensorflow_framework.so|grep _ZN10tensorflow10FileSystem10FilesExistERKSt6vectorISsSaISsEEPS1_INS_6StatusESaIS6_EE
```
But if i uninstall tensorflow an reinstall in again
```
pip uninstall -y tensorflow
pip install tensorflow==1.7.0
```

i get different tensorflow library with size `16337456`, and symbol i want to find  appears
````
16337456 Sep 20 02:45 libtensorflow_framework.so*

 nm libtensorflow_framework.so|grep _ZN10tensorflow10FileSystem10FilesExistERKSt6vectorISsSaISsEEPS1_INS_6StatusESaIS6_EE
0000000000553240 T _ZN10tensorflow10FileSystem10FilesExistERKSt6vectorISsSaISsEEPS1_INS_6StatusESaIS6_EE
```

So why and how to solve this? How can i compile a filesystem plugin compatible to tensorflow/tensorflow:1.7.0

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment]
@u2takey Could you try TensorFlow 1.10? Also make sure you completely uninstall TensorFlow before reinstalling. Please provide more information by filling out the above template .

**Comment by u2takey** [comment]
duplicate: https://github.com/tensorflow/tensorflow/issues/22339, closed
