### ISSUE TITLE
TensorFlow C++ API on ARM processor issue

### ISSUE THREAD

**Issue by RothLuo** [tensorflow/tensorflow#22430]
System information
***Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
   No
***OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   Linux Kernel 4.4.103, Linaro 5.4.0
***TensorFlow installed from (source or binary):
   Cross compilation in Ubuntu 16.04 and install the C++ library (libtensorflow.so + protobuf + nsync) in 
   the ARM development board
***TensorFlow version (use command below):
   1.10.1
***Python version:
  3.5
***CUDA/cuDNN version:
  Only CPU no GPU
***Exact command to reproduce:
  Session->Run(feed_dict, {"num_detections:0", "detection_boxes:0", 
              "detection_scores:0", "detection_classes:0"}, {}, &outputs)

Describe the problem
   Trained Detection API mobileNetSSD model and saved as a 'pb' file.  Cross compiled the TensorFlow on the PC and installed the binary  (libtensorflow.so + protobuf + nsync) to the ARM board.  The code can be successfully built on the ARM side.  The pb file can be successfully read and loaded into a graph in a session.  However, when trying to run the session by feeding a tensor, the following error message came up:

2018-09-20 18:28:38.852657: F tensorflow/core/framework/tensor.cc:657] Check failed: in_size != 0 (0 vs. 0)

It refers to Tensor::UnsafeCopyFromInternal function Line 3:  CHECK_NE(in_size, 0), and in_size =DataTypeSize(other.dtype()), which is unlikely to be zero.  

BTW, these message also came up when loading the 'pb' file:
2018-09-20 18:28:37.864057: E tensorflow/core/framework/op_kernel.cc:1197] OpKernel ('op: "DecodeProtoV2" device_type: "CPU"') for unknown op: DecodeProtoV2
2018-09-20 18:28:37.865515: E tensorflow/core/framework/op_kernel.cc:1197] OpKernel ('op: "EncodeProto" device_type: "CPU"') for unknown op: EncodeProto

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
GPU model and memory
Mobile device

**Comment by wt-huang** [comment]
@RothLuo  sounds like there is data conversion issue related to precision when feeding a tensor. You may want to check floating point precision on your ARM, which may not be compatible with TensorFlow. 

The error messages that came up when loading the 'pb' file can be ignored.

**Comment by wt-huang** [comment]
Closing this for now, feel free to open a new issue if encountering any errors.
