### ISSUE TITLE
get error run simple_estimator_example.py

### ISSUE THREAD

**Issue by AmberCheng** [tensorflow/tensorflow#22442]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Just example from tensorflow.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:macOS High Sierra 10.13.6
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:None
- **TensorFlow installed from (source or binary)**:Ananconda3
- **TensorFlow version (use command below)**:Tensorflow 1.10
- **Python version**: Python 3.65
- **Bazel version (if compiling from source)**:NaN
- **GCC/Compiler version (if compiling from source)**:NaN
- **CUDA/cuDNN version**:NaN
- **GPU model and memory**:NaN
- **Exact command to reproduce**:  config = tf.estimator.RunConfig(train_distribute=distribution,
 eval_distribute=distribution)

### Describe the problem
I just download the official example-"simple_estimator_example.py" and run it in my own computer. But I just get this error `  config = tf.estimator.RunConfig(train_distribute=distribution,eval_distribute=distribution)`. 
### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by harshini-gadige** [comment]
@AmberCheng Hi, Could you please post the source code/logs which you are getting.

**Comment by AmberCheng** [comment]
> @AmberCheng Hi, Could you please post the source code/logs which you are getting.

The logs are like that:

/Users/amber/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/Users/amber/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense (Dense)                (None, 16)                176       
_________________________________________________________________
dense_1 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 17        
=================================================================
Total params: 465
Trainable params: 465
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):
  File "/Users/amber/Documents/dstf/test_1.11.py", line 74, in <module>
    tf.app.run(argv=sys.argv)
  File "/Users/amber/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Users/amber/Documents/dstf/test_1.11.py", line 62, in main
    train_distribute=strategy, eval_distribute=strategy)
TypeError: __init__() got an unexpected keyword argument 'eval_distribute'
[Finished in 5.8s with exit code 1]

**Comment by AmberCheng** [comment]
This problem is finished in tensorflow 1.11. So I close it .
