### ISSUE TITLE
[Request] Please make version-compatible table among them: "python/tensorflow/tensorflow-gpu/tflearn/cuDNN/CUDA"

### ISSUE THREAD

**Issue by Dentrax** [tensorflow/tensorflow#22441]
Request: Version-Compatible Table

There are a lot of people using Tensorflow, and I'm sure that those people at least have tried to use tflearn, tensorflow-gpu, cuDNN CUDA, etc. And again, I'm very sure we have had the problem of version incompatibility many many many... times. We've done a lot of research to resolve this incompatibility. We tried all kinds of version combinations. And something came to mind:
"Why there wasn't a Version-Compatible table?"

Like: https://www.tensorflow.org/install/source_windows (Tested build configurations)

Example:

Which version tensorflow-gpu (X version) want at least (also MAX.) Python version?
Which version tensorflow-gpu (X version) want at least (also MAX.) cuDNN version?
Which version tensorflow-gpu (X version) want at least (also MAX.) CUDA version?

Which tflearn versions are compatible with which tensorflow (X) versions?
Which tflearn versions are compatible with which tensorflow-gpu (X) versions?

Which CUDA versions are compatible (at least and MAX) with which tensorflow-gpu versions?

etc... It could be an Exel table that clears all of these questions from our minds. Wouldn't that be good? You need to enter individual wiki pages and investigate version compatible each time. (I mean that waste of time)

Thanks in advance...

**Comment by EwoutH** [comment]
I tried installing the newest Tensorflow (1.11.0-rc1) with the newest Python (3.7.0), newest CUDA (9.2) and the newest cuDNN (7.2). It failed miserably.

Now with CUDA 10.0 and cuDNN 7.3 it will be an even bigger mess. A compatibility table would help very much!

**Comment by harshini-gadige** [comment]
@Dentrax Please find "Tested build configurations" table in this [link.](https://www.tensorflow.org/install/source#tested_build_configurations)

**Comment by EwoutH** [comment]
@harshini-gadige Nice! Could a table for Windows be added and minor CUDA revisions? CUDA 9.2 didn't work for me on 1.10, only 9.0 did.

**Comment by harshini-gadige** [comment]
@EwoutH  Here is the link for [Windows](https://www.tensorflow.org/install/source_windows#tested_build_configurations)
