### ISSUE TITLE
tf.keras.utils.multi_gpu_model  just ingore loaded weights from template model

### ISSUE THREAD

**Issue by jasstionzyf** [tensorflow/tensorflow#22447]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: no
- **TensorFlow installed from (source or binary)**: binary prebuilt
- **TensorFlow version (use command below)**: 1.9.0
- **Python version**: 3.6.4
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0/7.2.1
- **GPU model and memory**: Tesla K80 12GB
- **Exact command to reproduce**:

actually, when i call tf.keras.utils.multi_gpu_model on a template model that load_weights,  but result show that the multi_gpu_model just ingore the loaded weights on the template model.

**Comment by harshini-gadige** [comment]
@jasstionzyf Hi, Could you please describe the issue clearly. Also request you to provide a sample code snippet to reproduce the issue.

**Comment by jasstionzyf** [comment]
@harshini-gadige 
currently i can not reproduce the  issues, so will close it !
