### ISSUE TITLE
Import tensorflow ,Kernel died,restarting 

### ISSUE THREAD

**Issue by yaskh** [tensorflow/tensorflow#22440]
### System information
- **OS Platform and Distribution (Windows 10)**:
- **TensorFlow installed from :pip3
- **TensorFlow version :1.5
- **Python version: 2.7.14
- **GPU model and memory: Nvidia GT540M 1GB

### Describe the problem
On importing tensorflow i get this error. Downgraded to 1.5 still the same error as on the lastest version.
1) Spyder and Jupyter both result in the same error

**Comment by adshnaik** [comment]
Install a lower version of tensorflow, It works for me.

**Comment by yaskh** [comment]
Got this error when i run the command: 
Collecting ipykernal
  Could not find a version that satisfies the requirement ipykernal (from versions: )
No matching distribution found for ipykernal

**Comment by harshini-gadige** [comment]
@yaskh Have you tried with a lower version of tensorflow ?

**Comment by harshini-gadige** [comment]
@yaskh There is also a possibility that the firewall/internet security is blocking the kernel to start. So can you stop the firewall and try it again. Please post your observation once done. Thank you !

**Comment by harshini-gadige** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by AnitAggarwal** [comment]
I have a version 1.5 of tensorflow(have downgraded it) and 3.3.1 of spyder. 
I have tried updating the wait time to more than 60 seconds and also installed ipykernel and still the problem persists.
I am running anaconda on a 16GB DDR4 ram with i7-7500u processor machine

**Comment by yongDataScince** [comment]
apple m1, when import tensorflow: dead kernel

**Comment by keshaavlalsseth** [comment]
same issue not able to solve it after 3 dayss
