### ISSUE TITLE
tflite interpreter get different output for same input

### ISSUE THREAD

**Issue by lcxywfe** [tensorflow/tensorflow#22444]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian 4.5.5
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:  v1.10.1
- **Python version**: 3.5.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
give data to a tflite model
data shape = (2, 28, 28, 1) and data[0] == data[1]
use tf.contrib.lite.Interpreter to run the model
get the output, but output[0] != output[1]

### Source code / [logs](url)
```
import tensorflow as tf
import numpy as np

def test_same():
    data = np.random.random((1,28,28,1)).astype(np.float32)
    data = np.concatenate([data, data])
    print('input[0] == input[1]: ', equal(data[0], data[1]))
    model = tf.contrib.lite.Interpreter(
        model_path='resnet18_finetuned_batch2.tflite')
    model.allocate_tensors()
    model.set_tensor(0, data)
    model.invoke()
    output = model.get_tensor(model.get_output_details()[0]['index'])
    print('output[0] == output[1]: ', equal(output[0], output[1]))

def equal(tensor1, tensor2):
    for i, j in zip(tensor1.reshape(-1), tensor2.reshape(-1)):
        if abs(i - j) > 0.001:
            return False
    return True

if __name__ == "__main__":
    test_same()
```
OUTPUT:
```
input[0] == input[1]:  True
output[0] == output[1]:  False
```

**Comment by wt-huang** [comment]
@lcxywfe I compared tflite outputs from identical inputs using a simple model without getting any error. Make sure your model.set_tensor has the correct index and tensor from input details.

**Comment by wt-huang** [comment]
@lcxywfe You can post a link to your model.

**Comment by lcxywfe** [comment]
@wt-huang https://github.com/lcxywfe/model-zoom/raw/master/resnet18_finetuned_batch2.tflite

**Comment by wt-huang** [comment]
@lcxywfe Thanks for sharing the model. The reason that you didn't get identical results for the same input is because the tensor shape for input and output needs to be identical. You can feed `data` separately into model, i.e. `model.set_tensor(input_details[0]['index'], data[0])` and `model.set_tensor(input_details[0]['index'], data[1])`, then you will get identical results.

**Comment by wt-huang** [comment]
@lcxywfe The tensor shape for model input and output should be identical. To avoid `Dimension mismatch` error, you would need to convert `data[0]` and `data[1]` to np.array, Below is an example to get input from your model then do the same and feed `data[1]` to a separate tflite model, then you will see identical outputs.

```
    model = tf.contrib.lite.Interpreter(model_path="resnet18_finetuned_batch2.tflite")
    model.allocate_tensors()

    input_details = model.get_input_details()
    output_details = model.get_output_details()

    data = np.array(np.random.random_sample(input_details[0]['shape']), dtype=np.float32)
    model.set_tensor(input_details[0]['index'], data)

    model.invoke()
    output = model.get_tensor(output_details[0]['index'])
```

**Comment by lcxywfe** [comment]
@wt-huang I'm sorry, but why the input and output shape should be identical? If this is a classification model, then it can not work?

**Comment by wt-huang** [comment]
@lcxywfe Yes, it works on classification or most models for that matter. What I meant was the input and output to the model conversion and their shapes should be the same.

**Comment by lcxywfe** [comment]
Hi, what the 'the input and output to the model conversion' means?, i used "Flatbuffers" to create the tflite model instread of "toco".

**Comment by jia-kai** [comment]
@lcxywfe I guess tflite does not support changing input shape, so the original TF model used to create the tflite model must have identical shapes with tensors loaded at runtime in tflite.

**Comment by wt-huang** [comment]
Closing this now, feel free to ask any additional questions.
