### ISSUE TITLE
 Intel  GPU Support 

### ISSUE THREAD

**Issue by abdelrahmanmohamed** [tensorflow/tensorflow#22450]
Support Intel GPU alongside with NVIDIA, not sure if that is possible but it may help achieve better performance
check intel deep leaning kit
https://software.intel.com/en-us/openvino-toolkit/

**Comment by harshini-gadige** [comment]
@abdelrahmanmohamed Fyi. Please check [this](https://www.tensorflow.org/performance/performance_guide#tensorflow_with_intel%C2%AE_mkl_dnn).

**Comment by harshini-gadige** [comment]
You may also check the following github rep 
[Intel-TF](https://github.com/Intel-tensorflow)
[Intel/MKL-DNN](https://github.com/intel/mkl-dnn)
[OpenCL support](https://github.com/tensorflow/tensorflow/issues/22)

**Comment by gunan** [comment]
I do not think there are promising project which demonstrate good performance on Intel GPUs.
I know that OpenCL can work on these GPUs, but I am not sure about the performance.
This will  definitely need to be a community contribution, as we have no plans for this.

@claynerobison any resources on Intel GPUs you can point us to?

**Comment by claynerobison** [comment]
Hi @abdelrahmanmohamed. There are a couple of community supported OpenCL efforts, but nothing officially supported:

- https://jonnoftw.github.io/2018/04/04/building-tensorflow-with-opencl-support-on-ubuntu-1604

- https://github.com/hughperkins/tf-coriander

- https://www.codeplay.com/portal/tensorflow%E2%84%A2-for-opencl%E2%84%A2-using-sycl%E2%84%A2

**Comment by Hari-MathWorks** [comment]
Does TensorFlow support Intel GPUs in its latest releases?
