### ISSUE TITLE
Tensorflow mystique bug with MirroredStrategy freeze on particular local GPU combo

### ISSUE THREAD

**Issue by rr4rr** [tensorflow/tensorflow#22463]
https://stackoverflow.com/questions/52425485/tensorflow-mirroredstrategy-freeze-on-particular-gpu-combo

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04 host Linux Ubuntu 16.04 inside Docker container
- **TensorFlow installed from (source or binary)**: source and binary
- **TensorFlow version (use command below)**: 1.10.1 - 1.11.rc1
- **Python version**: 3.5 - 3.6
- **Bazel version (if compiling from source)**: 0.17.1
- **GCC/Compiler version (if compiling from source)**: 5
- **CUDA/cuDNN version**: 9.0, 9,2/7.2
- **GPU model and memory**: 
    (0) Nvidia Titan x 980 12gb
    (1) Nvidia Titan x 980 12gb (same)
    (2) Nvidia 1080ti 11gb
    (3) Nvidia 1080ti 11gb (same)
- **Exact command to reproduce**: example source below

### Describe the problem
Four GPUs on the same desktop:

(0) Nvidia Titan x 980 12gb
(1) Nvidia Titan x 980 12gb (same)
(2) Nvidia 1080ti 11gb
(3) Nvidia 1080ti 11gb (same)

MirroredStrategy (say from the obvious example code below) goes ok in combinations of the above (1,2), (1,3) but freezes on (2,3), (1,2,3). 
(0 - not used at distribution as causes another sort of CUDA_WAIT_TIMEOUT error due to guessed kernel timeouts for being used to render display)

Have no idea where to go further. Checked with original binary docker images both latest and nightly. Checked with compiled from source TensorFlow r1.10-r1.11 within original nvidia/cuda binary docker image. All the same behaviour.

### Source code / logs
```
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ['CUDA_VISIBLE_DEVICES']="2,3"

import tensorflow as tf 

def model_fn(features, labels, mode):
  layer = tf.layers.Dense(1)
  logits = layer(features)

  if mode == tf.estimator.ModeKeys.PREDICT:
    predictions = {"logits": logits}
    return tf.estimator.EstimatorSpec(mode, predictions=predictions)

  loss = tf.losses.mean_squared_error(
               labels=labels, predictions=tf.reshape(logits, []))

  if mode == tf.estimator.ModeKeys.EVAL:
    return tf.estimator.EstimatorSpec(mode, loss=loss)

  if mode == tf.estimator.ModeKeys.TRAIN:
    train_op = tf.train.GradientDescentOptimizer(0.2).minimize(loss)
    return tf.estimator.EstimatorSpec(mode, loss=loss, train_op=train_op)

def input_fn():
  features = tf.data.Dataset.from_tensors([[1.]]).repeat(100)
  labels = tf.data.Dataset.from_tensors(1.).repeat(100)
  return tf.data.Dataset.zip((features, labels))

distribution = tf.contrib.distribute.MirroredStrategy()
config = tf.estimator.RunConfig(train_distribute=distribution)
classifier = tf.estimator.Estimator(model_fn=model_fn, config=config)

classifier.train(input_fn=input_fn)

classifier.evaluate(input_fn=input_fn)
```

[freeze_output_r1.10.txt](https://github.com/tensorflow/tensorflow/files/2407611/freeze_output_r1.10.txt)
[freeze_output_r1.11.txt](https://github.com/tensorflow/tensorflow/files/2407612/freeze_output_r1.11.txt)
[normal_completion_output_r1.10.1.txt](https://github.com/tensorflow/tensorflow/files/2407613/normal_completion_output_r1.10.1.txt)
[normal_completion_output_r1.11.txt](https://github.com/tensorflow/tensorflow/files/2407614/normal_completion_output_r1.11.txt)
[tf_env_r1.10.1.txt](https://github.com/tensorflow/tensorflow/files/2407615/tf_env_r1.10.1.txt)
[tf_env_r1.11.txt](https://github.com/tensorflow/tensorflow/files/2407616/tf_env_r1.11.txt)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Mobile device

**Comment by rr4rr** [comment]
There was mentioned a lot [...:](https://devtalk.nvidia.com/default/topic/994904/linux/peer-to-peer-dma-transfers-bug-under-intel-vt-d-iommu-virtualization-/), [...:](https://bbs.archlinux.org/viewtopic.php?id=230362), [...:](https://stackoverflow.com/questions/42767187/why-does-this-tensorflow-code-crash)
 ASUS plx chip and bios related issue.
Kernel parameter pci=nommconf has fixed everything.
iommu off - should as well but as a last measure.
