### ISSUE TITLE
The tensorflow tested builds advices wrong bazel version for tensorflow-gpu r1.8

### ISSUE THREAD

**Issue by Kaju-Bubanja** [tensorflow/tensorflow#22475]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
No
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
r1.8
- **Python version**:
2.7
- **Bazel version (if compiling from source)**:
0.9.0
- **GCC/Compiler version (if compiling from source)**:
4.8.5
- **CUDA/cuDNN version**:
9.0/7.1
- **GPU model and memory**:
GeForce GTX 960M
- **Exact command to reproduce**:
./configure 
The output is:
You have bazel 0.9.0 installed.
Please upgrade your bazel installation to version 0.10.0 or higher to build TensorFlow!
Configuration finished

### Describe the problem
I tried to build tf r1.8 with gpu with bazel 0.17 but got errors then I checked [here](https://www.tensorflow.org/install/source) to make sure I got the right version, but saw that I need bazel 0.9.0. When trying it with bazel 0.9.0 I get the error above.
I did not find where I could edit the tf website itself to make a PR, so I just opened this issue. 

### Source code / logs
None

**Comment by gunan** [comment]
I think 0.17 was a typo.
@lamberta the problem is for Linux, tensorflow-gpu, version 1.8.0, we have bazel 0.9.0.
But it needs to be bazel 0.10.
Where do we update that?
