### ISSUE TITLE
How to use runStats() and view more detail of debug information in the android image classify demo?

### ISSUE THREAD

**Issue by jamesdeep** [tensorflow/tensorflow#22471]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
android and Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
Xiaomi Max2
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
the latest
- **Python version**:
3.5
- **Bazel version**:
N/A
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
N/A

### Describe the problem
I am doing a research of tensorflow on mobile devices and I get started in the android image classify demo.
I want to fetch the detail debug information while running pre-trianed model on android devices, and I notice the debug indormation can be fetched through pressing volume button while running the demo as the following:
![20180923190653](https://user-images.githubusercontent.com/14329360/45927296-e46fcd80-bf63-11e8-922c-9c6d2d9695a1.jpg)

However I can not find where to fetch the original debug data listed in the figure. Can someone tell me where to fetch these debug datas? Also the meaning of some of the datas are vague, for example [start], [first], what does these parameters mean? It is important of my research and hope someone could explain these, thx!

### Source code / logs
  private void renderDebug(final Canvas canvas) {
    if (!isDebug()) {
      return;
    }
    final Bitmap copy = cropCopyBitmap;
    if (copy != null) {
      final Matrix matrix = new Matrix();
      final float scaleFactor = 2;
      matrix.postScale(scaleFactor, scaleFactor);
      matrix.postTranslate(
          canvas.getWidth() - copy.getWidth() * scaleFactor,
          canvas.getHeight() - copy.getHeight() * scaleFactor);
      canvas.drawBitmap(copy, matrix, new Paint());

      final Vector<String> lines = new Vector<String>();
      if (classifier != null) {
        String statString = classifier.getStatString();// Here is where the core debug information come from, 
                                                                             //but I can not get more information!
        String[] statLines = statString.split("\n");
        for (String line : statLines) {
          lines.add(line);
        }
      }

      lines.add("Frame: " + previewWidth + "x" + previewHeight);
      lines.add("Crop: " + copy.getWidth() + "x" + copy.getHeight());
      lines.add("View: " + canvas.getWidth() + "x" + canvas.getHeight());
      lines.add("Rotation: " + sensorOrientation);
      lines.add("Inference time: " + lastProcessingTimeMs + "ms");

      borderedText.drawLines(canvas, 10, canvas.getHeight() - 10, lines);
    }
  }

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by wt-huang** [comment]
@jamesdeep  You can set up debugging on your device following the steps [here](https://developer.android.com/training/basics/firstapp/running-app#RealDevice) The on-screen data are for  model profiling where you can find the execution time of each operator for to benchmarking purposes. Count is the total number of nodes executed, Start is the time stamp for each node and First is the duration.

**Comment by wt-huang** [comment]
Closing this for now, feel free to open a new issue for any additional questions.
