### ISSUE TITLE
Why my tensorflow-gpu runs only on cpu?

### ISSUE THREAD

**Issue by noticeable** [tensorflow/tensorflow#22472]
OS Platform and Distribution: windows10
**TensorFlow installed from **: pip install tensorflow-gpu
TensorFlow version: (tensorflow-gpu            1.10.0）
Python version: Python 3.6.5
CUDA/cuDNN version: Cuda compilation tools, release 9.0/cudnn-9.0-windows10-x64-v7.3.0.29.zip

when I run nvidia-smi and nvcc-V,
The output is following:
(python36) C:\Windows\System32>nvidia-smi
Sun Sep 23 20:26:38 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 398.82                 Driver Version: 398.82                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080   WDDM  | 00000000:01:00.0  On |                  N/A |
| 42%   30C    P8    11W / 200W |    488MiB /  8192MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1176    C+G   Insufficient Permissions                   N/A      |
|    0      2388    C+G   ...oftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe N/A      |
|    0      6712    C+G   ...tEdge_8wekyb3d8bbwe\MicrosoftEdgeCP.exe N/A      |
|    0      7036    C+G   ...t_cw5n1h2txyewy\ShellExperienceHost.exe N/A      |
|    0      7220    C+G   ...dows.Cortana_cw5n1h2txyewy\SearchUI.exe N/A      |
|    0      7656    C+G   ...tEdge_8wekyb3d8bbwe\MicrosoftEdgeCP.exe N/A      |
|    0      8260    C+G   ...hell.Experiences.TextInput.InputApp.exe N/A      |
|    0      9852    C+G   ...tEdge_8wekyb3d8bbwe\MicrosoftEdgeCP.exe N/A      |
|    0     10308    C+G   ...tEdge_8wekyb3d8bbwe\MicrosoftEdgeCP.exe N/A      |
|    0     13544    C+G   ...Chrome\Chrome\Application\360chrome.exe N/A      |
|    0     16656    C+G   ...es (x86)\Internet Explorer\iexplore.exe N/A      |
+-----------------------------------------------------------------------------+

(python36) C:\Windows\System32>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:32_Central_Daylight_Time_2017
Cuda compilation tools, release 9.0, V9.0.176

When I use import tensorflow as tf,it's work well 
Then I tried to use this code:
>>> sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
The output is following:
Device mapping: no known devices.
2018-09-23 20:12:06.377265: I T:\src\github\tensorflow\tensorflow\core\common_runtime\direct_session.cc:288] Device mapping:

there is nothing show in the map.Why is this happening? How can I fix it?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by noticeable** [comment]
Thank you for your answer.I'll fill up it at following:
> Have I written custom code:No,I haven't written custom code.
> Bazel version:No,i'm not compiling the source code .
> GPU model and memory:GeForce GTX 1080 WDDM.Memory is 8192MiB 
> Exact command to reproduce:My command have been clearly displayed.
>>activate python3.6（a python3.6 enviroment I created on anaconda  ）
>>conda list 
(python36) C:\Windows\system32>conda list
# packages in environment at D:\software\anaconda\envs\python36:
#
# Name                    Version                   Build  Channel
_tflow_190_select         0.0.1                       gpu
absl-py                   0.4.1                    py36_0
alabaster                 0.7.10                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
astor                     0.7.1                    py36_0
astroid                   1.5.3                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
babel                     2.5.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
backcall                  0.1.0                     <pip>
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bleach                    1.5.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
certifi                   2018.8.24                 <pip>
certifi                   2016.2.28                py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
chardet                   3.0.4                     <pip>
chardet                   3.0.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cloudpickle               0.4.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
colorama                  0.3.9                     <pip>
colorama                  0.3.9                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cudatoolkit               9.0                           1
cudnn                     7.1.4                 cuda9.0_0
decorator                 4.3.0                     <pip>
decorator                 4.1.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
docutils                  0.14                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
entrypoints               0.2.3                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gast                      0.2.0                    py36_0
grpcio                    1.12.1           py36h1a1b453_0
html5lib                  0.9999999                py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
icc_rt                    2017.0.4             h97af966_0
icu                       57.1                     vc14_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
idna                      2.7                       <pip>
imagesize                 0.7.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ipykernel                 4.6.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ipykernel                 4.9.0                     <pip>
ipython                   6.5.0                     <pip>
ipython                   6.1.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ipython-genutils          0.2.0                     <pip>
ipython_genutils          0.2.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
isort                     4.2.15                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jedi                      0.10.2                   py36_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jedi                      0.12.1                    <pip>
jinja2                    2.9.6                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jpeg                      9b                       vc14_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jsonschema                2.6.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jupyter-client            5.2.3                     <pip>
jupyter-core              4.4.0                     <pip>
jupyter_client            5.1.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jupyter_core              4.3.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
keyring                   9.3.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
lazy-object-proxy         1.3.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libpng                    1.6.30                   vc14_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libprotobuf               3.6.0                h1a1b453_0
markdown                  2.6.9                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
markupsafe                1.0                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mistune                   0.7.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mkl                       2017.0.3                      0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
nbconvert                 5.2.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
nbformat                  4.4.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
numpy                     1.14.2           py36h5c71026_0
numpy                     1.14.5                    <pip>
numpydoc                  0.7.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
openssl                   1.0.2l                   vc14_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pandocfilters             1.4.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
parso                     0.3.1                     <pip>
path.py                   10.3.1                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pickleshare               0.7.4                     <pip>
pickleshare               0.7.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pip                       9.0.1                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pip                       18.0                      <pip>
prompt-toolkit            1.0.15                    <pip>
prompt_toolkit            1.0.15                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
protobuf                  3.6.0            py36he025d50_0
protobuf                  3.6.1                     <pip>
psutil                    5.2.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pycodestyle               2.3.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyflakes                  1.6.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
Pygments                  2.2.0                     <pip>
pygments                  2.2.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pylint                    1.7.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyqt                      5.6.0                    py36_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python                    3.6.2                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python-dateutil           2.6.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python-dateutil           2.7.3                     <pip>
pytz                      2017.2                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyzmq                     17.1.2                    <pip>
pyzmq                     16.0.2                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qt                        5.6.2                    vc14_6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qtawesome                 0.4.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qtconsole                 4.3.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qtpy                      1.3.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
requests                  2.14.2                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
requests                  2.19.1                    <pip>
rope                      0.9.4                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
setuptools                36.4.0                   py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
simplegeneric             0.8.1                     <pip>
simplegeneric             0.8.1                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
singledispatch            3.4.0.3                  py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sip                       4.18                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
six                       1.11.0                    <pip>
six                       1.10.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
snowballstemmer           1.2.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sphinx                    1.6.3                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sphinxcontrib             1.0                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sphinxcontrib-websupport  1.0.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
spyder                    3.3.1                    py36_1
spyder-kernels            0.2.4                    py36_0
tensorboard               1.9.0            py36he025d50_0
tensorboard               1.10.0                    <pip>
tensorflow                1.9.0           gpu_py36hfdee9c2_1
tensorflow-base           1.9.0           gpu_py36h6e53903_0
tensorflow-gpu            1.9.0                hf154084_0
tensorflow-gpu            1.10.0                    <pip>
tensorflow-gpu-base       1.8.0            py36h376609f_0
termcolor                 1.1.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
testpath                  0.3.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tornado                   4.5.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tornado                   5.1.1                     <pip>
traitlets                 4.3.2                     <pip>
traitlets                 4.3.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
typing                    3.6.6                     <pip>
urllib3                   1.23                      <pip>
vc                        14                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
vs2015_runtime            14.0.25420                    0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wcwidth                   0.1.7                     <pip>
wcwidth                   0.1.7                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
Werkzeug                  0.14.1                    <pip>
werkzeug                  0.12.2                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wheel                     0.29.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wincertstore              0.2                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wrapt                     1.10.11                  py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zlib                      1.2.11                   vc14_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

(python36) C:\Windows\System32>python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
2018-09-24 10:51:55.917673: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Device mapping: no known devices.
2018-09-24 10:51:55.926033: I T:\src\github\tensorflow\tensorflow\core\common_runtime\direct_session.cc:288] Device mapping:
(This Step I can't find my GPU)
> Mobile device:No,It's not works on mobile device

**Comment by noticeable** [comment]
> Could you copy-paste the full output of this python command:
> `tf.test.is_gpu_available()`

Yes，I have run the command ,the result is as following
>>> tf.test.is_gpu_available()
2018-09-24 14:39:47.660250: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
False

**Comment by gunan** [comment]
I am quite certain that the output you shared comes from non-gpu version of TF.
Are you sure you installed GPU version of TF?

**Comment by noticeable** [comment]
> I am quite certain that the output you shared comes from non-gpu version of TF.
> Are you sure you installed GPU version of TF?

yes ,I can found it in my conda list .it's  shown as following 
(python36) C:\Windows\system32>conda list
# packages in environment at D:\software\anaconda\envs\tensorflow-gpu:
#
# Name                    Version                   Build  Channel
_tflow_1100_select        0.0.1                       gpu
_tflow_190_select         0.0.1                       gpu
absl-py                   0.5.0                     <pip>
absl-py                   0.4.1                    py36_0
astor                     0.7.1                    py36_0
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
certifi                   2018.8.24                py36_1
cudatoolkit               9.0                           1
cudnn                     7.1.4                 cuda9.0_0
gast                      0.2.0                    py36_0
grpcio                    1.12.1           py36h1a1b453_0
h5py                      2.7.0               np113py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
hdf5                      1.8.15.1                 vc14_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
icc_rt                    2017.0.4             h97af966_0
keras-applications        1.0.4                    py36_1
keras-base                2.2.2                    py36_0
keras-gpu                 2.2.2                         0
keras-preprocessing       1.0.2                    py36_1
libprotobuf               3.6.0                h1a1b453_0
markdown                  2.6.9                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
Markdown                  3.0                       <pip>
mkl                       2017.0.3                      0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
numpy                     1.13.3           py36hb69e940_3
numpy                     1.14.5                    <pip>
pip                       18.0                      <pip>
pip                       9.0.1                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
protobuf                  3.6.1                     <pip>
protobuf                  3.6.0            py36he025d50_0
python                    3.6.5                h0c2934d_0
pyyaml                    3.12                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
scipy                     0.19.1              np113py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
setuptools                40.2.0                   py36_0
setuptools                39.1.0                    <pip>
six                       1.11.0                   py36_1
six                       1.11.0                    <pip>
tensorboard               1.10.0           py36he025d50_0
tensorflow                1.10.0          gpu_py36h3514669_0
tensorflow-base           1.10.0          gpu_py36h6e53903_0
tensorflow-gpu            1.10.0               hf154084_0
termcolor                 1.1.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
vc                        14                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
vs2015_runtime            14.15.26706          h3a45250_0
Werkzeug                  0.14.1                    <pip>
werkzeug                  0.12.2                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wheel                     0.31.1                    <pip>
wheel                     0.29.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wincertstore              0.2                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zlib                      1.2.11                   vc14_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

**Comment by noticeable** [comment]
OK,I found there is a tensorflow1.9.0 in my packages ,when I uninstall It, Everything works well. THX  for your answer. I'm appreciate of that .and I will close this issue

**Comment by namitmohale** [comment]
@noticeable how do I check if a previous version is present in my packages or not?

**Comment by noticeable** [comment]
> @noticeable how do I check if a previous version is present in my packages or not?
i'm using conda  ,in conda ,you can use conda list to see your packages installed

**Comment by noticeable** [comment]
> @noticeable how do I check if a previous version is present in my packages or not?

to solved this problem,you may use pip uninstall tensorflow,if there is a chonse shown. uninstall previous packages may be OK.

**Comment by shelendravashishtha2** [comment]
I have installed tensorflow v2.0.0 and tensorflow-gpu v2.0.0 both and keras also, but my tensorflow is still using CPU instead of GPU I don't know how to fix it can somebody help me out

**Comment by CGreen4u** [comment]
I'm having a similar issue. The GPU seems to run when running predictions but not when training the model instead it uses CPU.

**Comment by shelendravashishtha2** [comment]
May be the size of your predictions is small that's why you're thinking that in predictions, your system is using GPU. Make sure that you have installed tensorflow-gpu. Also if you've installed keras then sometimes system automatically uses Theano backend for the solution you can set backend from the prompt by simply writing the following code
    set "KERAS_BACKEND=tensorflow"
