### ISSUE TITLE
Installing Kerras on R/Windows

### ISSUE THREAD

**Issue by CarstenLange** [tensorflow/tensorflow#22487]
Hi All,

I hope somebody can help.

I had a well running Keras version running on R, which took me 30 minutes to install. Then I needed to reinstall after more than 20 hours and several workarounds I got everything running except the install_keras() command. See below:

> install_keras()
Using r-tensorflow conda environment for TensorFlow installation
Determining latest release of TensorFlow...done
Installing TensorFlow...
Collecting tensorflow==1.10.1 from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl
  HTTP error 404 while getting https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl
  Could not install requirement tensorflow==1.10.1 from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl because of error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl
Could not install requirement tensorflow==1.10.1 from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl because of HTTP error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl for URL https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Error: Error 1 occurred installing packages into conda environment r-tensorflow
In addition: Warning message:
running command '"C:/MINICO~1/Scripts/activate" r-tensorflow && pip install --upgrade --ignore-installed "https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl"' had status 1 

It seems that version 10.10.1 is not available for windows (I use Windows 10), while it is for all other platforms. The file tensorflow-1.10.1-cp36-cp36m-win_amd64.whl seems not to be available anywhere on the Internet (same seems to be true for the 86 version)

I tested  in a browser "https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl" does not work.
Older version 1.10.0: "https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.0-cp36-cp36m-win_amd64.whl" downloads file.

Also: 

install_keras(tensorflow="1.10.1)  gives an HTTP error 404 error

install_keras(tensorflow="1.10.0) installs fine, but does not work. 
E.g. (below first command works, while second one does not; Flags were set correctly, code used to work in my old installation, I also downgraded numpy and setup tools as requested => no success)
modelNn <- keras_model_sequential() 
modelNn %>% 
  layer_dense(units = FLAGS$dense1Neurons , activation = 'relu', input_shape = c(numInputs)) %>% 
  layer_dropout(rate = FLAGS$dense1Dropout)%>%
  layer_dense(units = 1, activation = 'linear')

I really rely on R tensorflow/keras in my research. Please help!

Thanks

Carsten

**Comment by ymodak** [comment]
@CarstenLange Just want to make sure. 
Did you load keras library with library(keras) before modelNn <- keras_model_sequential()?
 Also was that successful for tensorflow version 1.10.0?

**Comment by CarstenLange** [comment]
@ymodak . Thanks for the fast reply.  Yes, Ioaded Keras with library(keras) and the first command executed well. However, only keras_model_sequential() worked other commands did not. E.g.., the second one I mentioned and also "use_session_with_seed(2018)" did not work. I was not surprised, because Keras seems to require tensorflow="1.10.1" and I used  tensorflow="1.10.0" instead, which was kind of a hack.

**Comment by ymodak** [comment]
@CarstenLange You are welcome.Okay. Did you load the libraries such as dplyr or magrittr for the piping operator (%>%) to function? Also can you please paste the error message?

**Comment by CarstenLange** [comment]
Yes, dplyr was loaded via tidyverse. I also loaded library(magrittr).  
Here is the error message (this time from the MNIST example from the Tensorflow R webpage: 
model %>% 
+   layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>% 
+   layer_dropout(rate = 0.4) %>% 
+   layer_dense(units = 128, activation = 'relu') %>%
+   layer_dropout(rate = 0.3) %>%
+   layer_dense(units = 10, activation = 'softmax')
 Show Traceback
 
 Rerun with Debug
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Layer dense_1 was called with an input that isn't a symbolic tensor. Received type: <class 'keras.engine.se

However, this was tensorflow 1.10.0 since 1.10.1 does not install (see error at beginning of post).
Thanks.

**Comment by wt-huang** [comment]
@CarstenLange Which Keras version did you use? Please also provide the information below so we can better help you.

System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version (use command below): 1.10.1
Python version: python 3.6
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
Exact command to reproduce:

**Comment by wt-huang** [comment]
I have installed Keras/R on Windows without any errors.

**Comment by CarstenLange** [comment]
Hi Wt-Huang,

I had the same experience. I installed first Anaconda (5.0.1) and then MRO some month ago and all worked fine. Then when I tried to update R nothing worked anymore. I deinstalled everything and started from scratch.
The latest version of Anconda does not install correctly on Windows. I found a link and an advice to install Minconda instead. However when installing R I ran into new problems. I gave up and now run the Kerras part of my research on Ubunto.

However, it would be interesting which versions of Anaconda, Python, TensorFlow and Keras work well in your case and when you installed.

Thank you
Carsten

…………………………………………………..
Carsten Lange, Ph.D.
Professor of Economics and Graduate Coordinator
California State University
3801 west Temple Ave.
Pomona, CA 91768
Phone: +1 (909) 869 3843
Email: clange@cpp.edu

**Comment by wt-huang** [comment]
@CarstenLange 
Hi Carten, the previous Anaconda seemingly have less installation issues, however Ubuntu can work just as well if not better. Miniconda is compact but you could miss the benefit of some handy and useful packages. FWIW the versions I have used was Anaconda 3.7.0, Python 3.6, TensorFlow 1.10.0, Keras 2.2.0.

**Comment by CarstenLange** [comment]
Hi Wt-Huang,

Thanks for the email. I had TensorFlow 1.10.0 installed too when everything still worked. Then when I reinstalled TensorFlow 1.10.0 was not available on the Internet anymore.

I just recently saw that Anaconda 5.3.0 is out. I will wait for a while until it is at least updated ones and then try to install from scratch.

Best

Carsten

**Comment by wt-huang** [comment]
@CarstenLange 
Hi Carsten, glad that everything works for you now. Any further issues you may have when using TensorFlow, feel free to let us know.
