### ISSUE TITLE
Tensorflow r0.8 doesn't work with scikit-learn and scikit-Image

### ISSUE THREAD

**Issue by fivejjs** [tensorflow/tensorflow#2248]
I tried two installation method. Without scikit-Learn and scikit-Image, tensorflow works fine and I can run the deepdream ipynb. 

1. cuda 7.5 + cudnn v5 with source code compiled
2. cuda 7.5 + cudnn v4 pip GPU install

All according to https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html

After I installed scikit-learn, the segmentation fault (core dumped) following the Tensorflow loading message even though I import numpy before tesorflow. I will post more info here later.

**Comment by zheng-xq** [comment]
A small code segment to reproduce the error and an error message log will be very helpful.

**Comment by ilblackdragon** [comment]
This seems similar to #2034. Can you try nightly build with the fix, if it still has this issue?

**Comment by fivejjs** [comment]
Thanks, let me try.

**Comment by bhack** [comment]
This can be closed https://github.com/tensorflow/tensorflow/issues/2034#issuecomment-217632558
