### ISSUE TITLE
I have two nvidia GPU,but run ours finalAlg.so，and GPU don't work. 

### ISSUE THREAD

**Issue by cvJie** [tensorflow/tensorflow#22495]
first,i cmake tensorflow-GPU,and get tensorflow_cc.so；
then ,cmake tensorflow__cc.so and another alg codes have got finalAlg.so;
last,run finalAlg.so by tensorflow C++ API.

    string model_path = "finalAlg.pb";
    GraphDef graph_def;
    status = ReadBinaryProto(Env::Default(), model_path, &graph_def);
    status = session->Create(graph_def); 
    graph::SetDefaultDevice("/gpu:0", &graphdef);
    sess_options.config.mutable_gpu_options()->set_allow_growth(true); 
    Tensor phase_train(DT_BOOL, TensorShape());
    phase_train.scalar<bool>()() = false;   	
    std::vector<std::pair<std::string, tensorflow::Tensor>> inputs = {
    { "input", input_tensor },{"phase_train",phase_train }};
    std::vector<tensorflow::Tensor> outputs;
    status = session->Run(inputs, { "dsts"}, {}, &outputs);
    runtime appear:
    I tensorflow/core/common_runtime/gpu/gpu_device.cc:972]      0 1
    I tensorflow/core/common_runtime/gpu/gpu_device.cc:985] 0:   N N
    I tensorflow/core/common_runtime/gpu/gpu_device.cc:985] 1:   N N

 
Although i have two nvidia GPUs,but ours finalAlg.so cant't run in GPU,just always run in CPU.
Give me some suggesstion.thanks.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by harshini-gadige** [comment]
@cvJie Hi, can you try using this "with tf.device("/gpu:0"):"  Something like as shown below :

import tensorflow as tf
with tf.device("/gpu:0"):
- - -
- - -(your code)

**Comment by harshini-gadige** [comment]
@cvJie Is this issue resolved ?

**Comment by cvJie** [comment]
> @cvJie Is this issue resolved ?

It has resolved.thanks
