### ISSUE TITLE
I met the error:__init__() missing 2 required positional arguments: 'message' and 'code' when I tried to run the exact same code on image_captioning_with_attention 

### ISSUE THREAD

**Issue by LongForCMU** [tensorflow/tensorflow#22496]
The details are as follows:
code:
for img, path in image_dataset:
    batch_features = image_features_extract_model(img)
    batch_features = tf.reshape(batch_features, 
                              (batch_features.shape[0], -1, batch_features.shape[3]))

    for bf, p in zip(batch_features, path):
        path_of_feature = p.numpy().decode("utf-8")
        np.save(path_of_feature, bf.numpy())
error:
_FallbackException                        Traceback (most recent call last)
E:\anaconda\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py in iterator_get_next_sync(iterator, output_types, output_shapes, name)
   1600         "IteratorGetNextSync", name, _ctx._post_execution_callbacks, iterator,
-> 1601         "output_types", output_types, "output_shapes", output_shapes)
   1602       return _result

_FallbackException: Expecting int64_t value for attr output_shapes, got NoneType

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-17-266d7ad17ef7> in <module>()
----> 1 for img, path in image_dataset:
      2     batch_features = image_features_extract_model(img)
      3     batch_features = tf.reshape(batch_features, 
      4                               (batch_features.shape[0], -1, batch_features.shape[3]))
      5 

E:\anaconda\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py in __next__(self)
    484 
    485   def __next__(self):  # For Python 3 compatibility
--> 486     return self.next()
    487 
    488   def _next_internal(self):

E:\anaconda\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py in next(self)
    515     """
    516     try:
--> 517       return self._next_internal()
    518     except errors.OutOfRangeError:
    519       raise StopIteration

E:\anaconda\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py in _next_internal(self)
    505             self._resource,
    506             output_types=self._flat_output_types,
--> 507             output_shapes=self._flat_output_shapes)
    508 
    509       return sparse.deserialize_sparse_tensors(

E:\anaconda\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py in iterator_get_next_sync(iterator, output_types, output_shapes, name)
   1604       return iterator_get_next_sync_eager_fallback(
   1605           iterator, output_types=output_types, output_shapes=output_shapes,
-> 1606           name=name, ctx=_ctx)
   1607     except _core._NotOkStatusException as e:
   1608       if name is not None:

E:\anaconda\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py in iterator_get_next_sync_eager_fallback(iterator, output_types, output_shapes, name, ctx)
   1633   _result = _execute.execute(b"IteratorGetNextSync", len(output_types),
   1634                              inputs=_inputs_flat, attrs=_attrs, ctx=_ctx,
-> 1635                              name=name)
   1636   _execute.record_gradient(
   1637       "IteratorGetNextSync", _inputs_flat, _attrs, _result, name)

E:\anaconda\lib\site-packages\tensorflow\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     tensors = pywrap_tensorflow.TFE_Py_Execute(ctx._handle, device_name,
     59                                                op_name, inputs, attrs,
---> 60                                                num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

TypeError: __init__() missing 2 required positional arguments: 'message' and 'code

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by LongForCMU** [comment]
@wt-huang Thank you for your reply. I have changed the batch size but it didn't work. Here are some details: Win10+tensorflow 1.10.0+CUDA 9.0.
I found that there was someone else who met just the same error as me: https://stackoverflow.com/questions/51811510/typeerror-init-missing-2-required-positional-arguments-message-and-co

**Comment by wt-huang** [comment]
@LongForCMU It did work on my end. You can find compatibility chart [here](https://www.tensorflow.org/install/source_windows)

**Comment by wt-huang** [comment]
Closing this for now, feel free to reopen if any errors come up.
