### ISSUE TITLE
Can not run benchmark on android using "tensorflow/tensorflow/tools/benchmark"

### ISSUE THREAD

**Issue by jamesdeep** [tensorflow/tensorflow#22499]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
android and Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
Xiaomi Max2
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.14
- **Python version**:
3.5
- **Bazel version**:
1.7
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
N/A

### Describe the problem
I am trying to run benchmark on android phone following the instructions here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/benchmark/

I have succeffully build the benchmark and everything is right until step (4) Run the benchmark.
When I run the command below, I got no response:
adb shell "/data/local/tmp/benchmark_model \
  --graph=/data/local/tmp/tensorflow_inception_graph.pb \
  --input_layer="input:0" \
  --input_layer_shape="1,224,224,3" \
  --input_layer_type="float" \
  --output_layer="output:0"

There is only blinking arrow:
![_20180925202142](https://user-images.githubusercontent.com/14329360/46014065-acea5800-c100-11e8-8975-db7b06c88d10.png)

So can someone tell me what's wrong?

**Comment by freedomtan** [comment]
unbalance delimiter `"`. Use something like
```
adb shell "/data/local/tmp/benchmark_model \
  --graph=/data/local/tmp/tensorflow_inception_graph.pb \
  --input_layer="input:0" \
  --input_layer_shape="1,224,224,3" \
  --input_layer_type="float" \
  --output_layer="output:0""
```
or 
```
adb shell /data/local/tmp/benchmark_model \
  --graph=/data/local/tmp/tensorflow_inception_graph.pb \
  --input_layer="input:0" \
  --input_layer_shape="1,224,224,3" \
  --input_layer_type="float" \
  --output_layer="output:0"
```
instead. I'll send a PR to update the doc later.
