### ISSUE TITLE
I get "Session was not created with a graph before Run()" while running official TFLite Model Benchmark Tool on Android!

### ISSUE THREAD

**Issue by jamesdeep** [tensorflow/tensorflow#22500]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
android and Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
Xiaomi Max2
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.14
- **Python version**:
3.5
- **Bazel version**:
1.7
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
N/A

### Describe the problem
I am doing the "build/install/run" steps on Android phone following https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/tools/benchmark

However, when I run the benchmark using the following command I got error"Session was not created with a graph before Run()":

adb shell /data/local/tmp/benchmark_model \
  --graph=/data/local/tmp/mobilenet_quant_v1_224.tflite \
  --num_threads=4

I did not modify the source code and just follow the official document. Does anyone encounter the same problem?

![_20180925211348](https://user-images.githubusercontent.com/14329360/46016662-f12d2680-c107-11e8-8d8e-1e1f47b895cb.jpg)

**Comment by freedomtan** [comment]
It seems the one you ran is the TF benchmark_model rather than the TF Lite one. Please check it.
