### ISSUE TITLE
LookupError when computing tf.gradients of DepthwiseConv2dNativeBackpropInput

### ISSUE THREAD

**Issue by SimKuanGOH** [tensorflow/tensorflow#22502]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Anaconda
- **TensorFlow version:  v1.10.0-rc0-0-g586a7f1d2c 1.10.0-rc0
- **Python version : 3.6
- **CUDA/cuDNN version**: 9.0 / 7.3
- **GPU model and memory**: Titan X

### Describe the problem
I got a LookupError when computing tf.gradients()

LookupError: No gradient defined for operation 'gradients/discriminator_3/separable_conv2d/depthwise_grad/DepthwiseConv2dNativeBackpropInput' (op type: DepthwiseConv2dNativeBackpropInput)

Because DepthwiseConv2dNativeBackpropInput does not have a registered gradient function.

### Source code / logs
tf.gradients(d_hat, x_hat)[0] where tf.nn.separable_conv2d is used in the intermediate layers.

**Comment by harshini-gadige** [comment]
@reedwm Can this be added to "Contributions Welcome" as a feature request ?

**Comment by SimKuanGOH** [comment]
This is a quick fix by @rdinse:

https://github.com/tensorflow/tensorflow/issues/9917#issuecomment-322012032

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by veqtor** [comment]
Any updates on this?

**Comment by astropeak** [comment]
Hey, I'd like to work on this. Looks it still hasn't been done. Is that alright?

**Comment by astropeak** [comment]
@reedwm @SimKuanGOH, I just verified that the issue already be fixed in the latest version of tensorflow. Please consider close this issue.
The gradient is defined in tensorflow/tensorflow/python/ops/nn_grad.py.

**Comment by facaiy** [comment]
@astropeak Thank you :-)
