### ISSUE TITLE
Weird behaviour of back propagation in a while_loop in Tensorflow

### ISSUE THREAD

**Issue by dblueeye** [tensorflow/tensorflow#22504]
- **Have I written custom code: Yes
- **OS Platform and Distribution: Windows 10 (primary), Ubunto 16.04.3 LTS (secondary)
- **TensorFlow installed from (source or binary): Binary
- **TensorFlow version (use command below): b'v1.10.0-rc1-19-g656e7a2b34' 1.10.0
- **Python version: Python 3.6.6 :: Anaconda, Inc.
- **CUDA/cuDNN version**: N/A (not relevant)
- **GPU model and memory**: N/A (not relevant) 
- **Exact command to reproduce**:

### Describe the problem

I am trying to see if Tensorflow can backpropagate through a while_loop without a pre-defined number of loops. Something weird caught my attention: the following script results in the error 

> InvalidArgumentError: Retval[0] does not have value

However, when I replaced `tf.add(X,X)` by `tf.multiply(X,2)`, the code can be executed and return the correct answer graVal=64. 

Could anyone help me to understand where the error came from when I was using `tf.add(X,X)`? Thanks in advance!

### Source code / logs
```
import tensorflow as tf
from numpy import *

tf.reset_default_graph()

X = tf.Variable(5.0, dtype = float32)
Y = tf.Variable(4.0, dtype = float32)

def cond(iterN, Y):
    return iterN<6

def body(iterN, X):
    return iterN+1, tf.add(X,X)
    # return iterN+1, tf.multiply(X,2)

finalOutX = tf.while_loop(cond, body, [0,X], parallel_iterations=1, back_prop=True, swap_memory=True)

gra = tf.gradients(finalOutX, X)

init = tf.global_variables_initializer()

with tf.Session() as sess:

    init.run()
    X_val, graVal, = sess.run([finalOutX, gra])    

print(X_val)
print(graVal)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Mobile device

**Comment by ymodak** [comment]
@dblueeye A quick debugging tells me that error arises when the code triggers following line:
X_val, graVal, = sess.run([finalOutX, gra]) in your script.

**Comment by dblueeye** [comment]
@ymodak. That was not the real source, IMHO.  You'll see if you change the tf.add(X,X) to tf.multiply(2.0, X).

**Comment by dblueeye** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> Bazel version
> Mobile device

They are not relevant. I installed from the binary and not from the source, and I have not tried on a mobile device (I don't think I'll ever be trying:)).

**Comment by wt-huang** [comment]
@dblueeye `tf.add` works if you set the second parameter constant, i.e., `tf.add(X, 5.0)` would not encounter any error. @aselle Is this expected behavior?

**Comment by wt-huang** [comment]
Closing this, feel free to reopen if problem persists.
