### ISSUE TITLE
Quantization Error:   Converting unsupported operation: Elu

### ISSUE THREAD

**Issue by NikishinRoman** [tensorflow/tensorflow#22501]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)** : pip install
- **TensorFlow version (use command below)**: 1.10.1
- **Python version**:3.6
- **GPU model and memory**:NVIDIA 1080
- **Exact command to reproduce**:N/A
- **Bazel version**: N/A
- **CUDA/cuDNN version**: use CPU
- **Mobile device**:N/A

```
import tensorflow as tf
print(tf.__version__)
tf.enable_eager_execution()
converter = tf.contrib.lite.TocoConverter.from_saved_model("/media/user/60EA4260EA423298/Nikishyn/model")
#converter.post_training_quantize = True
tflite_quantized_model = converter.convert()
```

I'm trying to quantify my model, but I get an error.
console logs:

RuntimeError: TOCO failed see console for info.
b'2018-09-25 08:17:37.600466: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Elu\n2018-09-25 08:17:37.600610: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Elu\n2018-09-25 08:17:37.600833: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Elu\n2018-09-25 08:17:37.601051: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Elu\n2018-09-25 08:17:37.601221: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Elu\n2018-09-25 08:17:37.601441: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Elu\n2018-09-25 08:17:37.601664: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Elu\n2018-09-25 08:17:37.601835: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Elu\n2018-09-25 08:17:37.602063: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Elu\n2018-09-25 08:17:37.602291: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Elu\n2018-09-25 08:17:37.603091: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Elu\n2018-09-25 08:17:37.603218: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Elu\n2018-09-25 08:17:37.603283: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Elu\n2018-09-25 08:17:37.606771: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 373 operators, 615 arrays (0 quantized)\n2018-09-25 08:17:37.610480: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 347 operators, 576 arrays (0 quantized)\n2018-09-25 08:17:37.615480: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 347 operators, 576 arrays (0 quantized)\n2018-09-25 08:17:37.615675: F tensorflow/contrib/lite/toco/graph_transformations/resolve_batch_normalization.cc:42] Check failed: IsConstantParameterArray(*model, bn_op->inputs[1]) && IsConstantParameterArray(*model, bn_op->inputs[2]) && IsConstantParameterArray(*model, bn_op->inputs[3]) Batch normalization resolution requires that mean, multiplier and offset arrays be constant.\nAborted (core dumped)\n'
None

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
Mobile device

**Comment by NikishinRoman** [comment]
updated  fields

**Comment by harshini-gadige** [comment]
@NikishinRoman Hi, thanks for your post. Please note that tflite does not support the operation Elu and due to which you are running into this error.

**Comment by harshini-gadige** [comment]
@NikishinRoman For more information about TFLite supported operations, please find [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/tf_ops_compatibility.md).

**Comment by tofulawrence** [comment]
@suharshs Is this an op that we should add to your issue?

**Comment by NikishinRoman** [comment]
@harshini-gadige , Is it expected to support this(Elu) operation in the future?

**Comment by harshini-gadige** [comment]
@NikishinRoman You can track the operations that are added to tensorflow Lite in the future here #21526.
Thank you!
