### ISSUE TITLE
Lookup Error : Gradient Registry has no entry for  StatefulPartitionedCall

### ISSUE THREAD

**Issue by vibss2397** [tensorflow/tensorflow#22505]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.10.1
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: v9.0 (Cuda)
- **GPU model and memory**: gtx 930m, 2GB
- **Exact command to reproduce**:

### Describe the problem
I was implementing the gradient penalty for improved stability for wgan in tensorflow eager

### Source code / logs
``` python
with tf.GradientTape() as critic_tape:
    generated_images = generator(tf.random_normal([16, 100]), training=True)
    a = tf.convert_to_tensor(images)
    real_output = critic(a, training=True)
    generated_output = critic(generated_images, training=True)               
    with tf.GradientTape() as gtape:
        epsilon = tf.random_uniform([], 0, 1)
        xhat = epsilon*a + (1-epsilon)*generated_images
        dhat = critic(xhat, training=True)
        gtape.watch(xhat)
    dhat2 = gtape.gradient(dhat, xhat)
    slopes = tf.sqrt(tf.reduce_sum(tf.square(dhat2), reduction_indices=[1]))
    gradient_penalty = 10*tf.reduce_mean((slopes-1.0)**2)
    critic_loss = get_critic_loss(real_output, generated_output)
    critic_loss+= gradient_penalty                
gradients_of_critic = critic_tape.gradient(critic_loss, critic.variables)
print(gradients_of_critic) 
```

and the error stack i recieve is 
```--------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
<ipython-input-512-cbc8ebf905ac> in <module>()
     16     critic_loss = get_critic_loss(real_output, generated_output)
     17     critic_loss+= gradient_penalty
---> 18 gradients_of_critic = critic_tape.gradient(critic_loss, critic.variables)
     19 print(gradients_of_critic)

c:\users\vibhu\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\eager\backprop.py in gradient(self, target, sources, output_gradients)
    856     flat_grad = imperative_grad.imperative_grad(
    857         _default_vspace, self._tape, nest.flatten(target), flat_sources,
--> 858         output_gradients=output_gradients)
    859 
    860     if not self._persistent:

c:\users\vibhu\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\eager\imperative_grad.py in imperative_grad(vspace, tape, target, sources, output_gradients)
     61   """
     62   return pywrap_tensorflow.TFE_Py_TapeGradient(
---> 63       tape._tape, vspace, target, sources, output_gradients)  # pylint: disable=protected-access

c:\users\vibhu\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\eager\backprop.py in _gradient_function(op_name, attr_tuple, num_inputs, inputs, outputs, out_grads)
    110   """
    111   mock_op = _MockOp(attr_tuple, inputs, outputs, op_name)
--> 112   grad_fn = ops._gradient_registry.lookup(op_name)  # pylint: disable=protected-access
    113   if grad_fn is None:
    114     return [None] * num_inputs

c:\users\vibhu\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\registry.py in lookup(self, name)
     91     else:
     92       raise LookupError(
---> 93           "%s registry has no entry for: %s" % (self._name, name))

LookupError: gradient registry has no entry for: StatefulPartitionedCall

**Comment by vibss2397** [comment]
Hey, @wt-huang i checked all the tensors and they are fine, and both the gradient terms are calculated separately are proper but only when  the gradient penalty added to the critic loss function doed it throw the error. Can i calculate gradients of output of a model wrt input using``tfe.gradients_function() ``

**Comment by vibss2397** [comment]
@wt-huang did you get a chance to look at it?

**Comment by vibss2397** [comment]
@wt-huang it started working now, basically the line `` gtape.watch(xhat) ``, i had to write that before calculating `` dhat `` , thanks anyways

**Comment by wt-huang** [comment]
@vibss2397 Glad it worked, yes you would need to have that line before computing `dhat`.

**Comment by pengzhou93** [comment]
> @wt-huang it started working now, basically the line `gtape.watch(xhat)`, i had to write that before calculating `dhat` , thanks anyways

I did like this, but still get that error. My environment is tf_1.11 and in eager mode. Could you please detail the solution for this error? Thanks very much.

**Comment by vibss2397** [comment]
Hey @pengzhou93, i tried that, it just worked because ``dhat `` got assigned a value which didnt update and it just used that value, i started getting the same error even after correcting it  but forgot to reopen the issue, reopening, my bad 😅

**Comment by mvacaporale** [comment]
I'm having the same issue (also trying to implement a wgan-gp using tensorflow eager).
@vibss2397 Were you able to get it to work?

**Comment by vibss2397** [comment]
@mvacaporale yess. A workaround would be Disabling `tf.contrib.eager.defun` for the critic, but then again you won't get the speedup offered by `defun`

**Comment by alextp** [comment]
Does this error still reproduce at tf nightly?

**Comment by vibss2397** [comment]
@alextp wow, no, it does not, why might that be.

**Comment by alextp** [comment]
@vibss2397 it's been fixed since. Closing.
