### ISSUE TITLE
Support for NVIDIA Video Loader (nvvl)

### ISSUE THREAD

**Issue by fengyang0317** [tensorflow/tensorflow#22518]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: GTX 980M 4G
- **Exact command to reproduce**: N/A

Could you add the support for [NVIDIA Video Loader](https://github.com/NVIDIA/nvvl)?

**Comment by samikama** [comment]
@fengyang0317 keep an eye on DALI, https://github.com/NVIDIA/DALI

**Comment by bhack** [comment]
@fengyang0317 Why you are forwarding over DALI? Is DALI support video readers like NVVL? I don't think that features overlaps between the two projects or tha DALI supersedes NVVL.

**Comment by bhack** [comment]
@samikama Why you are forwarding over DALI? Is DALI support video readers like NVVL? I don't think that features overlaps between the two projects or tha DALI supersedes NVVL.

**Comment by bhack** [comment]
@samikama Why you are forwarding over DALI? Is DALI support video readers like NVVL? I don't think that features overlaps between the two projects or tha DALI supersedes NVVL.

**Comment by bhack** [comment]
Something is moving in https://github.com/NVIDIA/DALI/pull/240
