### ISSUE TITLE
get error when slice tensor

### ISSUE THREAD

**Issue by 333caowei** [tensorflow/tensorflow#2251]
I want to slice tensor to get specific tensor by list of index, for example:
```
word_weight   = tf.get_variable("word_weight", [20])
a= word_weight[ [1,6,5] ]
```
(I want to get word_weight[1],  word_weight[6],  word_weight[5])

------------------------------------------------------------------

But I get error when I run above code.
```
raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (16491,) must have rank 3

```

**Comment by mrry** [comment]
That syntax (which might be valid in NumPy - I'm not sure) doesn't work for TensorFlow slicing. To get rows 1, 6, and 5 from a tensor or variable, you use [`tf.gather()`](https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#gather):

```python
a = tf.gather(word_weight, [1, 6, 5])
```
