### ISSUE TITLE
Tensorflow lite aborts due to "pure virtual method called" on Raspberry Pi

### ISSUE THREAD

**Issue by vvigilante** [tensorflow/tensorflow#22510]
Hello.
I compiled the library as described in
https://www.tensorflow.org/lite/rpi

When running
`./benchmark_model --graph=mobilenet_v1_1.0_224.tflite`
or
`./minimal mobilenet_v1_1.0_224.tflite`

it crashes with the following output:
```

STARTING!
Num runs: [50]
Inter-run delay (seconds): [-1]
Num threads: [1]
Benchmark name: []
Output prefix: []
Warmup runs: [1]
Graph: [mobilenet_v1_1.0_224.tflite]
Input layers: []
Input shapes: []
Use nnapi : [0]
Loaded model mobilenet_v1_1.0_224.tflite
resolved reporter
pure virtual method called
terminate called without an active exception


```

I tried to debug the problem myself: it occurs in a secondary thread.
Some function that is called from 
`EigenForTFLite::NonBlockingThreadPoolTempl<EigenForTFLite::StlThreadEnvironment>::WorkerLoop(int)
` 
gets the this parameter equal to NULL.

The host is a raspberry pi 3B+, with raspbian.
I tried both to cross-compile the code and to compile natively.
I tried more versions: one is r1.11
Gcc version: 4.9.2

Does anyone else have the same problem or is it just me?
Thank you.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by vvigilante** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.

Hello. Here is the form:

> Have I written custom code
No
> OS Platform and Distribution
Raspbian 8 Jessie
> TensorFlow installed from
Source
> TensorFlow version
r1.11
> Bazel version
No
> CUDA/cuDNN version
No
> GPU model and memory
No
> Exact command to reproduce
./benchmark_model --graph=mobilenet_v1_1.0_224.tflite
> Mobile device
Raspberry Pi 3B+

**Comment by wt-huang** [comment]
@vvigilante It appears that you are using cmake which is deprecated. Could you try using Bazel?

**Comment by vvigilante** [comment]
I did not use cmake. I used the steps described in https://www.tensorflow.org/lite/rpi

**Comment by vvigilante** [comment]
I got it running. **Compile flag _-march=armv7-a_ seems to break things**.
Just removing that flag worked for me.
I don't know if it is related to gcc version (mine is 4.9.2). I'm doing other tests.
