### ISSUE TITLE
[Compile Error] Compiling tf r1.8 from source in cuda9.0_cudnn7.0 container failed.

### ISSUE THREAD

**Issue by ChengduoZhao** [tensorflow/tensorflow#22527]
When I compile tf r1.8 from source in cuda9.0_cudnn7.0 container following this [doc](https://www.tensorflow.org/install/source), I encountered error, the error is:
```
./tensorflow/core/util/tensor_format.h:355:3: note: in expansion of macro 'CHECK'
   CHECK(index >= 0 && index < dimension_attribute.size())
   ^
ERROR: 
/tf_compile/tensorflow_cuda9.0_cudnn7.0/tensorflow/contrib/lite/toco/python/BUILD:22:1: Linking of rule '//tensorflow/contrib/lite/toco/python:_tensorflow_wrap_toco.so' failed (Exit 1)
gcc: error: tensorflow_wrap_toco_versionscript.lds: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1417.439s, Critical Path: 262.20s
INFO: 7170 processes: 7170 local.
FAILED: Build did NOT complete successfully
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ChengduoZhao** [comment]
@harshini-gadige tf r1.9 and tf r1.10 is ok.

**Comment by manishkm** [comment]
Hi, I am also getting same error, I am compiling tf r1.7 on ubuntu 16.04 with cuda support & using cuda-9.0 and cudnn7.0

ERROR: /data3/tensorflow_git/tensorflow/tensorflow/contrib/lite/toco/python/BUILD:22:1: Linking of rule '//tensorflow/contrib/lite/toco/python:_tensorflow_wrap_toco.so' failed (Exit 1)
gcc: error: tensorflow_wrap_toco_versionscript.lds: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1173.957s, Critical Path: 170.61s
INFO: 5492 processes: 5492 local.
FAILED: Build did NOT complete successfully

I am trying to build from source because I get "Illegal instruction" error on importing tensorflow with tf1. installation.  Probably because my in xeon cpu does not support avx instruction.

**Comment by dreambear1234** [comment]
@manishkm , @ChengduoZhao 
    Hi, I got the same error lately too, bug error info cannot be searched except this new page.
I guess it's the problem of new version for some dependency packages.

    I compared several packages(gcc, cuda, cudnn, bazel and...) with other tensorflow  installation position, I doubt it the bug of bazel(latest version: 0.17.2). So...

1. rm -fr ~/.bazel ~/.bazelrc
2. install bazel (version: 0.11.1, maybe others)
3. bazel build ...

It's okay!

**Comment by harshini-gadige** [comment]
@ChengduoZhao Hi, have you tried the workaround suggested by @dreambear1234  ?

**Comment by kochkov92** [comment]
I ran into the same problem while building TF 1.8 with cuda support (toolkit 9.2, cudnn 7.1).

Building with older version of bazel (0.16.1) solved the problem.

**Comment by harshini-gadige** [comment]
@ChengduoZhao @kochkov92   Hi, you can find the compatible Bazel versions [here](https://www.tensorflow.org/install/source#tested_build_configurations). Please make sure you are using the correct combination of these with respect to the OS. Thank you!

**Comment by yelojakit** [comment]
I am still having this issue using Bazel 0.17.2 building TensorFlow 1.7 with CUDA support (toolkit 9.0, cudnn 7.0.5).

Note that I had to also had to add a linker flag for it to find my nvidia libraries (specifically the libnvidia-fatbinaryloader.so) in my CROSSTOOL file (as referenced here: https://github.com/tensorflow/tensorflow/issues/3261#issuecomment-234147379)

**Comment by yelojakit** [comment]
I had the same problem with TF 1.7 (toolkit 9.0, cudnn 7.0) and was able to fix the problem using Bazel 0.16.1 as well

**Comment by vslyu** [comment]
@dreambear1234 @yelojakit  Thanks! I meet the problem about contrib which is  same with you !And  What I sloved  the problem is uninstalling Bazel 0.17.2  and return to  use Bazel 0.16.1 as well.

**Comment by harshini-gadige** [comment]
> @ChengduoZhao @kochkov92 Hi, you can find the compatible Bazel versions [here](https://www.tensorflow.org/install/source#tested_build_configurations). Please make sure you are using the correct combination of these with respect to the OS. Thank you!
> 
> @ChengduoZhao Could you please confirm if this issue still persist after trying the correct and compatible Bazel version ?

Closing this issue as there is no response from the user. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
