### ISSUE TITLE
Feature request: Make contrib.receptive_field extensible

### ISSUE THREAD

**Issue by jvlmdr** [tensorflow/tensorflow#22529]
### System information
- **TensorFlow version (use command below)**: 1.8.0

### Describe the problem

For the problem I am working on, I need to compute a cross-correlation where the filters are a function of some inputs, i.e. `c_i = conv2d(f(a_i), g(b_i))` for the `i`-th example `(a_i, b_i)` in the batch. After doing this, the receptive field of `c` with respect to `a` is still well-defined.

I can think of several ways to implement this, but none of them are compatible with `receptive_field`!

For example, I usually use `reshape`-`depthwise_conv2d`-`reshape`-`sum` to transform a batch of `B` convolutions with `C` channels into a batch of `1` depthwise-convolution with `B*C` channels, then sum over the `C` channels at the end. Another way to do it would be using `tf.map_fn`. However, neither of these will work with `compute_receptive_field_from_graph_def`.

I understand that it would be very difficult to support edge cases like this. However, it breaks the workflow a bit to keep track of every place where the graph is incompatible with `receptive_field` and perform the composition manually here.

Perhaps it would be possible to add a manual override parameter to `compute_receptive_field_from_graph_def` that allows a user to manually specify the receptive field from one node to another, instead of using the graph?

Another way could be to support custom layers, either by checking if the custom layer has a receptive field method, or allowing users to register custom layers with the `receptive_field` module. However, this would require me to write my own layer for the "dynamic" convolution described above, which is not currently necessary.

I'm open to suggestions!

**Comment by jvlmdr** [comment]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: n/a
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: n/a
- **TensorFlow installed from (source or binary)**: binary
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: n/a

**Comment by wt-huang** [comment]
@jvlmdr Thanks for sharing the use case. Customizing your own layer would be a quicker route but adding knobs to `compute_receptive_field_from_graph_def` is a viable approach especially when your use case may change frequently in the future. You can modify TensorFlow graph in place using [Graph Editor via tf.contrib.graph_editor](https://www.tensorflow.org/api_guides/python/contrib.graph_editor)

**Comment by wt-huang** [comment]
Glad to help :)
