### ISSUE TITLE
After post-training quantization -- Internal error: Cannot allocate memory for the interpreter

### ISSUE THREAD

**Issue by minizon** [tensorflow/tensorflow#22535]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: tf-nightly-1.12.0.dev20180926
- **TensorFlow version (use command below)**: tf-nightly-1.12.0.dev20180926
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: no
- **GCC/Compiler version (if compiling from source)**: no
- **CUDA/cuDNN version**: no
- **GPU model and memory**: no
- **Exact command to reproduce**: see follows

### Describe the problem
When I tried to use the quantized model for the example [TensorFlow for Poets 2: TFLite Android](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2-tflite/#0), I encountered the following problem.
beginning of crash
09-26 13:08:10.249 31824-31824/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: android.example.com.tflitecamerademo, PID: 31824
    java.lang.RuntimeException: Unable to start activity ComponentInfo{android.example.com.tflitecamerademo/com.example.android.tflitecamerademo.CameraActivity}: **java.lang.NullPointerException: Internal error: Cannot allocate memory for the interpreter: tensorflow/contrib/lite/kernels/conv.cc:201 filter->type != data_type (3 != 1)Node 4 failed to prepare.**
    
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.NullPointerException: Internal error: Cannot allocate memory for the interpreter: tensorflow/contrib/lite/kernels/conv.cc:201 filter->type != data_type (3 != 1)Node 4 failed to prepare.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:75)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:54)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:114)
        at com.example.android.tflitecamerademo.ImageClassifier.<init>(ImageClassifier.java:97)
        at com.example.android.tflitecamerademo.Camera2BasicFragment.onActivityCreated(Camera2BasicFragment.java:299)
        at android.app.Fragment.performActivityCreated(Fragment.java:2362)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1014)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
        at android.app.BackStackRecord.run(BackStackRecord.java:816)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
        at android.app.FragmentController.execPendingActions(FragmentController.java:371)
        at android.app.Activity.performStart(Activity.java:6695)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

The cmds were as follows:
```
import tensorflow as tf
graph_def_file='retrained_graph.pb'
input_arrays = ["input"]
output_arrays = ["final_result"]
converter = tf.contrib.lite.TocoConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
converter.post_training_quantize = True
tflite_quantized_model = converter.convert()
open("quantized_graph.tflite", "wb").write(tflite_quantized_model)
```
But if post-training quantization is not enabled, the app works.

The quantized model could work in python env (though the result is not accurate).
```
interpreter = tf.contrib.lite.Interpreter(model_path="quantized_graph.tflite")
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
from label_image import read_tensor_from_image_file
input_data = read_tensor_from_image_file('1.jpg',input_height=224,input_width=224, input_mean=128, input_std=128)
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)
```

### Source code / logs
Models are attached.
[tf_files.zip](https://github.com/tensorflow/tensorflow/files/2419845/tf_files.zip)

**Comment by freedomtan** [comment]
After the post-training quantization, the type of input tensors are changed from floating point into quantized uint8. You need to change your code accordingly.

**Comment by minizon** [comment]
> After the post-training quantization, the type of input tensors are changed from floating point into quantized uint8. You need to change your code accordingly.

But in the python env, I found the dtype of input was still float
>>>input_details
[{'name': 'input', 'index': 89, 'shape': array([  1, 224, 224,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
>>> output_details
[{'name': 'final_result', 'index': 85, 'shape': array([1, 5], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
Whether additional setting params are required for the post-training quantization? Could you give any detailed tutorials?

**Comment by freedomtan** [comment]
@minizon sorry about confusion. What I wanted to say is that for post-training quantization, the type of input tensors remains floating point. For real quantized model, the type of input tensors is expected to be quantized uint8 (type 3). To put it simply, a post-training model should be treated as a floating point model rather than a quantized one. That's why it doesn't work in the demo app (which, if not modified, expects a quantized one, see tflitecamera source [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/Camera2BasicFragment.java#L334)

**Comment by minizon** [comment]
@freedomtan What I did before is that I just simply replaced the retrained_graph.lite by the quantized_graph.lite in the assets folder ([here](https://github.com/googlecodelabs/tensorflow-for-poets-2/tree/master/android/tflite/app/src/main/assets)), the classifier for the tf interpreter was not changed ([here](https://github.com/googlecodelabs/tensorflow-for-poets-2/blob/master/android/tflite/app/src/main/java/com/example/android/tflitecamerademo/ImageClassifier.java#L97)). I think this demo is still for the floating point model, but the error ( **Internal error: Cannot allocate memory for the interpreter: tensorflow/contrib/lite/kernels/conv.cc:201 filter->type != data_type (3 != 1)Node 4 failed to prepare**) did happen. Or do you mean only after post-training quantization, the model is still not proper for android deployment?

Any way, I couldn't find clear guides for how to change the floating point model into a real quantized one. The official model zoo provides some pre-converted models ([here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/models.md#image-classification-quantized-models)) with no details for the conversion process.

**Comment by freedomtan** [comment]
@minizon I finally figured out what your environment/setting is. Put it simply, **the TF Lite runtime used by the TensorFlow for Poets 2: TFLite Android example at this time doesn't support post-training quantization**. Quick solution, build your own tensorflow-lite aar with more recent source code.

More details:
1. yes, the app you used uses floating-point model, not quantized uint8. I thought you were trying the tflitecamera demo in the TF source code rather than the one in the TensorFlow for Poets 2.
2. post-training quantization is to quantize weights of convolutions, that is, it's weights only quantization. Weights are quantized from float32 to uint8. But computation is still in floating point, that is, dequantization should be done before computing. Code related to this dequantization was added relative late. So it's not in AAR you used.
3. for full quantization / quantization-aware training see [this doc]( https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/quantize/README.md)
4. Since TensorFlow 1.11.0 was released. Maybe there will be updated AAR soon. Maybe @wt-huang can help?

**Comment by minizon** [comment]
@freedomtan Thank you very much!

**Comment by GQYYY** [comment]
@minizon  Hello, I met the same problem with you. After reading your communication contents with  listed above, I saw a promising solution. But when I tried in practice, there still existed problems, which confused me long. Therefore, I wonder whether you could share your experience in fixing the problem?  And, how on earth to conduct the quantization using the command tool TOCO? Could you give me some detailed tips? Thank you very much! 

My conversion is as follows,and the conversion process failed:

IMAGE_SIZE=28
toco \
  --graph_def_file=./lenet5.pb \
  --output_file=./lenet5_qt_uint8.lite \
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --input_shape=1,${IMAGE_SIZE},${IMAGE_SIZE},1 \
  --input_array=conv2d_1_input \
  --output_array=output_node0 \
  --inference_type=QUANTIZED_UINT8 \
  --inference_input_type=QUANTIZED_UINT8 \
  --post_training_quantize

Also thanks to @freedomtan for your instructions! I would appreciate it if you gave me some detailed tips fixing this bug.

**Comment by minizon** [comment]
@GQYYY I didn't use the CLI toco. Please follow [the python tutorial](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/tutorials/post_training_quant.ipynb)  to make it. You can use tf.contrib.lite.TocoConverter.from_frozen_graph for the pb file. **Please make sure that you've installed a recent tf release version**.  And be aware that after this kind of conversion, the model is still muck like a floating model, so maybe better set the inference_type and inference_input_type to float. What I understood is that once you had quantization-aware training, you could set them to uint8.

**Comment by jazzystring1** [comment]
@minizon Have you already solved your problem? If so, can you share it with us? Because I also encountered this error. I used tensorflow 11.0 in converting my pb model to tflite format. I can't run the post-quantized model in my phone. Thanks

**Comment by jazzystring1** [comment]
Fixed! Use the tflite 0.0.0-nightly in android.

**Comment by minizon** [comment]
@brucechou1983 See this [reference](https://heartbeat.fritz.ai/compiling-a-tensorflow-lite-build-with-custom-operations-cf6330ee30e2)

**Comment by brucechou1983** [comment]
@minizon seems to be helpful! Thank you~

**Comment by damhurmuller** [comment]
@minizon @brucechou1983 did you guys find the solution for this issue? I have the same issue and I'm using the last version of nightly.

**Comment by jazzystring1** [comment]
@brucechou1983

Can you share your newly Tensorflow Lite AAR build?  Thanks

**Comment by SreehariRamMohan** [comment]
@ jazzystring1 using tf nightly didn't solve my issue. Also @brucechou1983 your advice seems helpful. I have a tflite quantized model right now, could you tell me the terminal command to covert that into a post-training quantization model? Thanks!

**Comment by chenlh14** [comment]
@minizon Hello! I wonder whether your model  after the post-training quantization can have correct results. My post-training quantized model just can't. Could you plz share your experience?

**Comment by chenlh14** [comment]
@brucechou1983 @jazzystring1 @freedomtan @GQYYY did your post-training quantization models get correct inference results?

**Comment by minizon** [comment]
@chenlh14 After quantization the model's performance will degenerate. If you want to minimize the disparity, you should use quantization-aware training first. For other situations, you should check the whole conversion process.

**Comment by chenlh14** [comment]
@minizon Thank you for your advice.
Codes are simple, as follows.
`import tensorflow as tf
tf.enable_eager_execution()
converter = tf.contrib.lite.TocoConverter.from_frozen_graph('resnet_v1_frozen.pb', ['input'], ['output'])
tflite_model = converter.convert()
open("converted_resnet.tflite", "wb").write(tflite_model)
converter.post_training_quantize = True
tflite_model = converter.convert()
open("quantized_resnet.tflite", "wb").write(tflite_model)`
My model is based on ResNet V1, but without BN layers.
.pb model can reach an accuracy of 88%, while .tflite nearly none.
Am I wrong in the conversion process or has it something to do with my model?
Any advice will be appreciated.

**Comment by brucechou1983** [comment]
Did you check the performance of the non-quatized tflite model?

**Comment by GustavZ** [comment]
i have the same error with a normal trained tensorflow model (so no quantization aware training) and porting it to tflite and running it on android works, but fails for the quantized version.
I tried both:
```
tflite_convert \
--output_file=model_quantized_uint8.tflite \
--graph_def_file=model.pb \
--inference_type=QUANTIZED_UINT8 \
--input_shapes=1,224,224,3 \
--input_arrays=inputs \
--output_arrays=outputs \
--default_ranges_min=0 \
--default_ranges_max=6 \
--mean_values=128 \
--std_dev_values=127
```
and
```
tflite_convert \
--output_file=model_quantized_float.tflite \
--graph_def_file=model.pb \
--inference_type=FLOAT \
--inference_input_type=FLOAT \
--input_shapes=1,224,224,3 \
--input_arrays=inputs \
--output_arrays=outputs \
--post_training_quantize
```
