### ISSUE TITLE
tfe.Saver only stores last 5 checkpoints

### ISSUE THREAD

**Issue by gokul-uf** [tensorflow/tensorflow#22538]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.1
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: CUDA 9.0
- **GPU model and memory**: 940 MX
- **Exact command to reproduce**:
```
import numpy as np
import os

import tensorflow as tf
import tensorflow.contrib.eager as tfe


 '''The following should be irrelevant, but nevertheless'''
class CNNClassifier(tf.keras.Model):

    def __init__(self):
        super(CNNClassifier, self).__init__()
        xav_init = tf.contrib.layers.xavier_initializer

        self.layer_1 = tf.layers.Conv2D(
            filters=32,
            kernel_size=[3, 3],
            padding="same",
            activation=tf.nn.relu,
            kernel_initializer=xav_init())
        self.layer_2 = tf.layers.Conv2D(
            filters=64,
            kernel_size=[3, 3],
            padding="same",
            activation=tf.nn.relu,
            kernel_initializer=xav_init())
        self.layer_3 = tf.layers.Conv2D(
            filters=128,
            kernel_size=[3, 3],
            padding="same",
            activation=tf.nn.relu,
            kernel_initializer=xav_init())
        self.layer_4 = tf.layers.Conv2D(
            filters=256,
            kernel_size=[3, 3],
            padding="same",
            activation=tf.nn.relu,
            kernel_initializer=xav_init())
        self.layer_5 = tf.layers.Conv2D(
            filters=512,
            kernel_size=[3, 3],
            padding="same",
            activation=tf.nn.relu,
            kernel_initializer=xav_init())
        self.dense = tf.layers.Dense(units=10)

    def call(self, inputs):
        inputs = tf.convert_to_tensor(inputs)
        x = tf.layers.max_pooling2d(
            self.layer_1(inputs), pool_size=[2, 2], strides=[2, 2])
        x = tf.layers.max_pooling2d(
            self.layer_2(x), pool_size=[2, 2], strides=[2, 2])
        x = tf.layers.max_pooling2d(
            self.layer_3(x), pool_size=[2, 2], strides=[2, 2])
        x = tf.layers.max_pooling2d(
            self.layer_4(x), pool_size=[2, 2], strides=[2, 2])
        x = tf.layers.max_pooling2d(
            self.layer_5(x), pool_size=[2, 2], strides=[2, 2])
        x = tf.layers.flatten(x)
        x = self.dense(x)
        return x

if __name__ == "__main__":
	os.mkdir("saved_models")
    tfe.enable_eager_execution()

    c = CNNClassifier()
    c(np.random.randn(1, 32, 32, 3))

    saver = tfe.Saver(c.variables)

    for i in range(100):
        print(i)
        saver.save(f"saved_models/step_{i}.ckpt")

```

### Problem Description
I am using eager execution and the `tfe.Saver` class to save my model's weights. However, if I am saving many checkpoints, only last five checkpoints are saved. This is very similar to issues with `tf.train.Saver` where the `max_to_keep` argument defaults to `5`. Since `tfe.Saver` doesn't have a corresponding argument, it seems to me that it is impossible to store more than the 5 most recent checkpoints.

I am happy to submit PRs if there's any guidance on how to fix this issue.

**Comment by gokul-uf** [comment]
Quick check of the codebase reveals the following
[`tfe.Saver`](https://github.com/tensorflow/tensorflow/blob/4dcfddc5d12018a5a0fdca652b9221ed95e9eb23/tensorflow/contrib/eager/python/saver.py#L116) uses [`tf.train.saver.Saver`](https://github.com/tensorflow/tensorflow/blob/4dcfddc5d12018a5a0fdca652b9221ed95e9eb23/tensorflow/python/training/saver.py#L1072) internally. A "simple fix" would be to bubble up the agrument of the the constructor of the latter to the former, thereby allowing the users to modify these args themselves instead of just using the defaults

**Comment by gokul-uf** [comment]
Thanks for the suggestion.

I think it should work, though I would much prefer if `Checkpoint.restore` didn't do its own numbering and allowed the user to customize it (via a `global_step` arg) :)

Nevertheless, it seems good enough for me.
Quick question, do we still need to do a dummy pass to initialize the variables berfore restoring the saved weights?


Thanks again, upto the devs to decide whether to close this issue because the bug still remains in `tfe.Saver`

**Comment by allenlavoie** [comment]
Custom numbering will work with `CheckpointManager.save(checkpoint_number=...)`, and you can set `max_to_keep=None` to keep everything if you don't want it cleaning up checkpoints.

There's also [`tf.train.Checkpoint.write`](https://www.tensorflow.org/versions/r1.11/api_docs/python/tf/train/Checkpoint#write), which `CheckpointManager` calls, if you want to do string formatting/checkpoint management yourself.

Will close since `tfe.Saver` is going away (deprecating it is on my list).

**Comment by allenlavoie** [comment]
Oh, and for initialization, there's `tf.train.Checkpoint.restore(...).initialize_or_restore()` for initializing variables which won't get restored while graph building. When executing eagerly, variables are initialized eagerly, so it's optional there.
