### ISSUE TITLE
Number of intra_op_parallelism_threads Issue with TF 1.10

### ISSUE THREAD

**Issue by priyankjain** [tensorflow/tensorflow#22546]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra version 10.13.6
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 2.7.10
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: None (It's a CPU build)
- **GPU model and memory**: N/A
- **Exact command to reproduce**: Please see sections below

### Describe the problem

In tensorflow 1.7.0, getting the number of threads in the intra_op pool was possible with the following line of code in C++:
`context->device()->tensorflow_cpu_worker_threads()->num_threads`
where context is an object of type OpKernelContext. (because of https://github.com/tensorflow/tensorflow/blob/7bccde15ce0dd29dce62092a5e9d48ffdc772963/tensorflow/core/common_runtime/local_device.cc#L43).

If the corresponding ConfigProto was set using the following python code:
```
import tensorflow as tf 
conf = tf.ConfigProto(inter_op_parallelism_threads=5, intra_op_parallelism_threads=4) 
sess = tf.Session(config=conf)
```

TF 1.7 would output the value of `context->device()->tensorflow_cpu_worker_threads()->num_threads` as `4`.

TF 1.10 outputs the value of `context->device()->tensorflow_cpu_worker_threads()->num_threads` as `1`, irrespective of the intra_op_parallelism_threads value specified in the ConfigProto.

I was wondering if something changed in the TF upgrade from 1.7.0 to 1.10.0 to cause this piece of code to give a different value or is the number of threads in the threadpool truly 1?

Other relevant information:

- macOS High Sierra version `10.13.6`

- Working TF version: `1.7.0`

- Breaking TF version: `1.10.0`

- Python information: Python 2.7.10 (default, Oct 6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin

- Detailed debugging information from tensorflow (by setting `TF_CPP_MIN_VLOG_LEVEL=3` before running the python program) says that TF 1.10 is indeed planning to create a thread pool of size 4 on this line of C++ code. The C++ piece of code at the start of this post however outputs value 1.

- This is the first and only session being created in the program.

**Comment by azaks2** [comment]
I have tried a small test with direct session and it worked. Note there are a few places where this parameter is not used or being overridden. For example, whenever we run the graph via GraphRunner.  If you have an op and the context in which it was called I can try to find a more precise explanation.

**Comment by harshini-gadige** [comment]
@priyankjain Hi, can you provide some code snippet relevant to the context.

**Comment by priyankjain** [comment]
Here is the C++ OP code
```cpp
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/framework/op_kernel.h"
#include "tensorflow/core/framework/common_shape_fns.h"

using namespace tensorflow;

REGISTER_OP("NumIntraOpThreads")
.Output("num_intra_op_threads: int32")
.SetShapeFn(tensorflow::shape_inference::ScalarShape)
.Doc(R"doc(
A tensorflow OP that returns the number of threads in the intra_op_parallelism pool
)doc");

class NumIntraOpThreads : public OpKernel {
 public:
  explicit NumIntraOpThreads(OpKernelConstruction* context)
      : OpKernel(context) {}

  void Compute(OpKernelContext* context) override {
    int num_intra_op_threads = context->device()->tensorflow_cpu_worker_threads()->num_threads;
    Tensor* output_tensor = NULL;
    OP_REQUIRES_OK(context, context->allocate_output(0, TensorShape({}), &output_tensor));
    auto output_flat = output_tensor->flat<int32>();
    output_flat(0) = num_intra_op_threads;
    }
};

REGISTER_KERNEL_BUILDER(Name("NumIntraOpThreads").Device(DEVICE_CPU), NumIntraOpThreads);
```

Here are the flags I am using to compile the OP
```bash
TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )
g++ -std=c++11 -shared -undefined dynamic_lookup num_intra_op_threads.cc -o num_intra_op_threads.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2
```

The python code to test the output of the OP:
```python
import tensorflow as tf
print('Tensorflow version is ', tf.__version__)
n_module = tf.load_op_library('./num_intra_op_threads.so')
print(tf.__version__)
with tf.Session(config=tf.ConfigProto(intra_op_parallelism_threads=10, inter_op_parallelism_threads=10)):
  print(n_module.num_intra_op_threads().eval())
```

Output of the above python script with TF 1.7:
```bash
('Tensorflow version is ', '1.7.0')
1.7.0
2018-10-02 12:25:36.949725: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
10
```

Output with TF 1.10:
```bash
('Tensorflow version is ', '1.10.0')
1.10.0
2018-10-02 12:24:26.858385: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
1
```

Output with TF 1.11:
```bash
('Tensorflow version is ', '1.11.0')
1.11.0
2018-10-02 12:27:45.802153: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
1
```

I am recompiling the OP with different TF versions, before running the python script.

**Comment by azaks2** [comment]
Will try your example to confirm but the best guess so far is that your kernel is run as part of constant folding which does use 1 thread. Adding input should help to see the 10 inter threads.

**Comment by priyankjain** [comment]
Indeed, that works for all tf versions until 1.9. Unfortunately, not for 1.10.
Here is the modified C++ code
```cpp
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/framework/op_kernel.h"
#include "tensorflow/core/framework/common_shape_fns.h"

using namespace tensorflow;

REGISTER_OP("NumIntraOpThreads")
.Input("placeholder: float32")
.Output("num_intra_op_threads: int32")
.SetShapeFn(tensorflow::shape_inference::ScalarShape)
.Doc(R"doc(
A tensorflow OP that returns the number of threads in the intra_op_parallelism pool
)doc");

class NumIntraOpThreads : public OpKernel {
 public:
  explicit NumIntraOpThreads(OpKernelConstruction* context)
      : OpKernel(context) {}

  void Compute(OpKernelContext* context) override {
    int num_intra_op_threads = context->device()->tensorflow_cpu_worker_threads()->num_threads;
    Tensor* output_tensor = NULL;
    OP_REQUIRES_OK(context, context->allocate_output(0, TensorShape({}), &output_tensor));
    auto output_flat = output_tensor->flat<int32>();
    output_flat(0) = num_intra_op_threads;
    }
};

REGISTER_KERNEL_BUILDER(Name("NumIntraOpThreads").Device(DEVICE_CPU), NumIntraOpThreads);
```

The OP compilation code remains the same.
Here is the updated python code:
```python
import tensorflow as tf
print('Tensorflow version is ', tf.__version__)
n_module = tf.load_op_library('./num_intra_op_threads.so')
print(tf.__version__)
with tf.Session(config=tf.ConfigProto(intra_op_parallelism_threads=10, inter_op_parallelism_threads=10)):
  print(n_module.num_intra_op_threads(tf.constant(2.0)).eval())
```
Output with TF 1.9:
```bash
('Tensorflow version is ', '1.9.0')
1.9.0
2018-10-02 15:10:56.503960: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
10
```

Output with TF 1.10:
```bash
('Tensorflow version is ', '1.10.0')
1.10.0
2018-10-02 15:11:47.141032: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
1
```

**Comment by priyankjain** [comment]
@azaks2 Checking in to see whether you got a chance to run my code and confirm? Happy to provide more information if needed, thanks!

**Comment by priyankjain** [comment]
Bump, wondering whether you got a chance to look into this.
