### ISSUE TITLE
Misleading full description on Tensorflow's Docker Hub public repository

### ISSUE THREAD

**Issue by chrish42** [tensorflow/tensorflow#22542]
The instructions on https://hub.docker.com/r/tensorflow/tensorflow/ still refer to the old `nvidia-docker`, when new images support nvidia-docker2, which works a bit differently.. The full description from Docker Hub doesn't seem to be under version control, so I can't submit a diff, but the following changes are needed, under the "Start GPU (CUDA) container" section:

* In "Install nvidia-docker and run", change "nvidia-docker" for "nvidia-docker2" instead. (The link stays the same).
* Instead of  "nvidia-docker run -it -p 8888:8888 tensorflow/tensorflow:latest-gpu", now the command is `docker run --runtime=nvidia -it -p 8888:8888 tensorflow/tensorflow:latest-gpu`.

This was the best place I could find where to submit this bug report. If there's a better place, please let me know. Thanks!

**Comment by av8ramit** [comment]
Thanks for pointing this out @chrish42 I'll take a look.

**Comment by av8ramit** [comment]
@tfboyd if you can sign off on this I can update dockerhub.

**Comment by tfboyd** [comment]
+1

**Comment by av8ramit** [comment]
Done. https://hub.docker.com/r/tensorflow/tensorflow/
