### ISSUE TITLE
conflicting shape of tflite conv2d weight tensor shape vs conv2d documentation

### ISSUE THREAD

**Issue by jnorwood** [tensorflow/tensorflow#22540]
https://www.tensorflow.org/api_docs/python/tf/nn/conv2d
shows that conv2d expects kernel tensor of shape [filter_height, filter_width, in_channels, out_channels]
The mobilenet_v1_1.0_224/mobilenet_v1_1.0_224.tflite from the following link contains shape for the first conv2d of [32,3,3,3]
while the mobilenet_v1_1.0_224/mobilenet_v1_1.0_223_frozen.pb has conv2d tensor shape of [3,3,3,32]
https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md

So, since these are conflicting shapes, both going into the first conv2d, then one of them does not match the documentation kernel tensor shape.  It appears to me the .pb file matches the documentation, since HWCN is 3,3,3,32 for the first conv2d

Is the .tflite format going to persist the weight tensors in a different shape than in the .pb?   If so, I don't see that documented.

You can see this by downloading the netron viewer from 
https://github.com/lutzroeder/netron
and clicking on the weight tab in the first conv2d, and look at the shape in the weights node properties.
I'm using tensorflow 1.10 on ubuntu 18.04, and using netron viewer 2.1.8

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by freedomtan** [comment]
I think you are right that the order of conv2d weights is OHWI, I didn't see any related doc, but it's all in source code, see e.g., [1](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/model.h#L162-L172), [2](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/import_tensorflow.cc#L550-L557) and [3](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/kernels/conv.cc#L252-L258)

**Comment by jnorwood** [comment]
The compatibility list  comment  is a bit cryptic, but perhaps it is acknowledging that the conv2d filter /weight order is incompatible.   So, is there some plan to resolve the incompatibilities between tflite and tf operations (incuding these persisted filter/weight shape differences)?    

https://www.tensorflow.org/lite/tf_ops_compatibility
"The following TensorFlow operations are usually mapped to their TensorFlow Lite counterparts:"
"tf.nn.conv2d - as long as the filter is constant"

**Comment by jnorwood** [comment]
Thanks for the links.   "TensorFlow vs Our" differences, with "Our" meaning tflite, could be important documentation for anyone trying to use tflite.   I guess we can close this, since the differences are obviously known.
  kOHWI,     // Our standard for conv weights
  kHWIO,     // TensorFlow conv weights
  k1HWO,     // Our standard for DepthwiseConv weights
  kHWIM,     // TensorFlow DepthwiseConv weights
