### ISSUE TITLE
@fft2d//:fft2d bazel 

### ISSUE THREAD

**Issue by dingshaoran** [tensorflow/tensorflow#22558]
fisrt build 
ERROR: /private/var/tmp/_bazel_dsr/f1e96f4f92f1092791bdd5610d5595fa/external/com_google_absl/absl/strings/BUILD.bazel:84:1: C++ compilation of rule '@com_google_absl//absl/strings:internal' failed (Exit 1)

after build
ERROR: /private/var/tmp/_bazel_dsr/f1e96f4f92f1092791bdd5610d5595fa/external/fft2d/BUILD.bazel:26:1: C++ compilation of rule '@fft2d//:fft2d' failed (Exit 1)

macos 10.13.6
ndk 16.0.4442984

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment]
@dingshaoran It appears that something is off in the tool chain. Please fill out the issue template so we can better help you.

**Comment by wt-huang** [comment]
Closing this for now, please open a new issue if any error comes up.
