### ISSUE TITLE
Adding custom op instructions lacking the GPU building instructions

### ISSUE THREAD

**Issue by panfengli** [tensorflow/tensorflow#22554]
Tensorflow [Add a new op tutorial](https://www.tensorflow.org/extend/adding_an_op) never mention the building instructions for GPU ops. 

I find one [here](https://gist.github.com/Sergio0694/fc94fb14388ee4b7b92be6e33704e5b9), but it met the similar issue with [Building custom op instructions out of date ](https://github.com/tensorflow/tensorflow/issues/13607).
`
tensorflow.python.framework.errors_impl.NotFoundError: ./libcuda_op.so: undefined symbol: _ZTIN10tensorflow8OpKernelE`

Tensorflow really needs to give some suggestions on how to build GPU ops.

**Comment by panfengli** [comment]
The one from the above link:

cmake_minimum_required(VERSION 3.5)

set(CMAKE_C_COMPILER /opt/cuda/bin/gcc)
set(CMAKE_CXX_COMPILER /opt/cuda/bin/g++)

# get tensorflow include dirs, see https://www.tensorflow.org/how_tos/adding_an_op/
execute_process(COMMAND python3 -c "import tensorflow; print(tensorflow.sysconfig.get_include())" OUTPUT_VARIABLE Tensorflow_INCLUDE_DIRS)

```
find_package(CUDA)

# C++11 required for tensorflow
set(CMAKE_CXX_FLAGS "-std=c++11 -O2 ${CMAKE_CXX_FLAGS}")

# if GCC > 5
if (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 5.0 OR CMAKE_CXX_COMPILER_VERSION VERSION_EQUAL 5.0)
  set(CMAKE_CXX_FLAGS "-D_GLIBCXX_USE_CXX11_ABI=0 ${CMAKE_CXX_FLAGS}")
endif()

#pass flags to c++ compiler
SET(CUDA_PROPAGATE_HOST_FLAGS ON)

# build the actual operation which can be used directory
include_directories(${Tensorflow_INCLUDE_DIRS})

#create library
cuda_add_library(
    add_one SHARED
    cuda_op_kernel.cu
add_one.cc)
```

Currently Tensorflow only provides instructions for CPU ops as:

TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )
g++ -std=c++11 -shared zero_out.cc -o zero_out.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2

**Comment by ppwwyyxx** [comment]
The tutorial does mention the build instructions for GPU ops: https://www.tensorflow.org/extend/adding_an_op#gpu_support

**Comment by panfengli** [comment]
Thanks! @ppwwyyxx
