### ISSUE TITLE
missing build_pip_package runfiles tensorflow external

### ISSUE THREAD

**Issue by edi-bice** [tensorflow/tensorflow#2256]
-bash-4.1$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Fri May 6 18:41:53 UTC 2016 : === Using tmpdir: /tmp/tmp.HLtyx30grJ
cp: cannot stat `bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/tensorflow': No such file or directory
cp: cannot stat `bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/external': No such file or directory

### Environment info
Operating System:

redhat-release-server-6Server-6.7.0.3.el6.x86_64
epel-release-6-8.noarch
scl python27 devtoolset-2 enable
numpy 1.11.0

Installed version of CUDA and cuDNN: 

No CUDA -- configured without GPU

If installed from sources, provide the commit hash:

f8eb1d70a7ea7dc2cd5e1eddde389395f88a6be9

### Steps to reproduce
git clone https://github.com/bazelbuild/bazel.git
cd bazel/
./compile.sh

--git 1.7.1
git clone --recursive https://github.com/tensorflow/tensorflow
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

### What have you tried?
1. With previously installed protobuf from source 3.0.0b2- thought that was the problem so
2. Tried on another box with no previously installed protobuf

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /home/ebice/.cache/bazel/_bazel_ebice/e10106cd0aa7dd3e05f3af5f70558af6/external/grpc/WORKSPACE:1: Workspace name in /home/ebice/.cache/bazel/_bazel_ebice/e10106cd0aa7dd3e05f3af5f70558af6/external/grpc/WORKSPACE (@__main__) does not match the name given in the repository's definition (@grpc); this will cause a build error in future versions.
WARNING: /home/ebice/.cache/bazel/_bazel_ebice/e10106cd0aa7dd3e05f3af5f70558af6/external/re2/WORKSPACE:1: Workspace name in /home/ebice/.cache/bazel/_bazel_ebice/e10106cd0aa7dd3e05f3af5f70558af6/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
INFO: Loading complete.  Analyzing...

**Comment by vals** [comment]
I'm having the same issue, performing the same steps as above.

## Environment Info

Red Hat Enterprise Linux Server release 6.6 (Santiago)
Python 3.5

No CUDA

If installed from sources, provide the commit hash:

85f494e7e2354dd674a7831deb38cc9c1acdee1a

## What have you tried

Different GCC compilers, different versions of Bazel.

**Comment by nsuke** [comment]
Looks like the bazel is too new.
Missing directories are now placed in `.runfiles/__main__/` instead of `.runfiles/`.

https://github.com/bazelbuild/bazel/wiki/Updating-the-runfiles-tree-structure
bazelbuild/bazel@857cda2

**Comment by martinwicke** [comment]
Which versions of bazel are you using?

**Comment by vals** [comment]
I used 2.2b, this is the top one which is present in the release page https://github.com/bazelbuild/bazel/releases which is linked to from the setup instructions: https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#installation-for-linux

What is the recommended version?

**Comment by vals** [comment]
Ah sorry, actually I was using HEAD of master of the basel github repository. I had to build it from source.

**Comment by martinwicke** [comment]
I hope that 2.2 would work. We'll have to make changes to make 2.3 work
when it comes out.

**Comment by vals** [comment]
I rolled back to 0.2.2 by `git checkout 759bbfe` in the bazel repository, then rebuilt. After this I could successfully build tenssorflow!

**Comment by martinwicke** [comment]
Thanks, it's good to know we'll have to fix TensorFlow for the next bazel
release.

**Comment by edi-bice** [comment]
I rolled back to 0.2.2 - thanks @vals - but ran into a different issue

ERROR: /home/ebice/.cache/bazel/_bazel_ebice/87c284e4831886db3eb74a03d0a82dcb/external/grpc/BUILD:1597:1: Linking of rule '@grpc//:grpc_cpp_plugin' failed: gcc failed: error executing command /opt/rh/devtoolset-2/root/usr/bin/gcc -o bazel-out/host/bin/external/grpc/grpc_cpp_plugin -no-canonical-prefixes -B/opt/rh/devtoolset-2/root/usr/bin -pass-exit-codes '-Wl,--build-id=md5' ... (remaining 12 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/opt/rh/devtoolset-2/root/usr/bin/ld: /opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/libstdc++_nonshared.a(hashtable_c++0x44.o): undefined reference to symbol 'ceil@@GLIBC_2.2.5'
/opt/rh/devtoolset-2/root/usr/bin/ld: note: 'ceil@@GLIBC_2.2.5' is defined in DSO /lib64/libm.so.6 so try adding it to the linker command line
/lib64/libm.so.6: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by edi-bice** [comment]
Seems the above is a known Bazel CentOS issue [https://github.com/bazelbuild/bazel/issues/1190](url). Will close this issue and chase this elsewhere.
