### ISSUE TITLE
Confusing information in the tf.data Op kernel files

### ISSUE THREAD

**Issue by feihugis** [tensorflow/tensorflow#22576]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: 0.16.0
- **GCC/Compiler version (if compiling from source)**: 4.2.1
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
A bunch of files for tf.data Ops under the directory `tensorflow/core/kernels/data/` has the following doc:

```
// See documentation in ../ops/dataset_ops.cc for a high-level
// description of the following op.
```
However, I could not find this file at the referred location (`../ops/dataset_ops.cc`). Does it mean the file `tensorflow/core/ops/dataset_ops.cc`? If yes, I would like to submit a PR to update them.

**Comment by mrry** [comment]
Yes, we moved the kernel files down one directory, and forgot to update those comments. A contribution would be welcome, thanks!
