### ISSUE TITLE
1.11.0 is missing the package for Python 3.6 on macOS

### ISSUE THREAD

**Issue by daniel-ziegler** [tensorflow/tensorflow#22574]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra (10.13.6)
- **TensorFlow installed from (source or binary)**: binary (attempted)
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: 3.6.4 (Anaconda)
- **Exact command to reproduce**: `pip install tensorflow==1.11.0`

### Describe the problem

1.11.0 is missing the package for Python 3.6 on macOS. See https://pypi.org/project/tensorflow/1.11.0/#files -- it has many combinations of {Windows, Linux, macOS} and Python {2.7, 3.3, 3.4, 3.5, 3.6}, but it's missing macOS + Python 3.6. (It's also missing Windows + older Python versions, but that's been that way for a while.)

### Source code / log
Here's what https://pypi.org/project/tensorflow/1.11.0/#files currently lists:

Filename, size & hash SHA256 hash help | File type | Python version | Upload date
-- | -- | -- | --
tensorflow-1.11.0-cp27-cp27m-macosx_10_11_x86_64.whl (59.4 MB)  Copy SHA256 hashSHA256 | Wheel | cp27 | Sep 27, 2018
tensorflow-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl (63.0 MB)  Copy SHA256 hashSHA256 | Wheel | cp27 | Sep 27, 2018
tensorflow-1.11.0-cp33-cp33m-macosx_10_11_x86_64.whl (59.9 MB)  Copy SHA256 hashSHA256 | Wheel | cp33 | Sep 27, 2018
tensorflow-1.11.0-cp33-cp33m-manylinux1_x86_64.whl (63.5 MB)  Copy SHA256 hashSHA256 | Wheel | cp33 | Sep 27, 2018
tensorflow-1.11.0-cp34-cp34m-macosx_10_11_x86_64.whl (59.9 MB)  Copy SHA256 hashSHA256 | Wheel | cp34 | Sep 27, 2018
tensorflow-1.11.0-cp34-cp34m-manylinux1_x86_64.whl (63.5 MB)  Copy SHA256 hashSHA256 | Wheel | cp34 | Sep 27, 2018
tensorflow-1.11.0-cp35-cp35m-macosx_10_11_x86_64.whl (59.3 MB)  Copy SHA256 hashSHA256 | Wheel | cp35 | Sep 27, 2018
tensorflow-1.11.0-cp35-cp35m-manylinux1_x86_64.whl (63.0 MB)  Copy SHA256 hashSHA256 | Wheel | cp35 | Sep 27, 2018
tensorflow-1.11.0-cp35-cp35m-win_amd64.whl (46.9 MB)  Copy SHA256 hashSHA256 | Wheel | cp35 | Sep 27, 2018
tensorflow-1.11.0-cp36-cp36m-manylinux1_x86_64.whl (63.0 MB)  Copy SHA256 hashSHA256 | Wheel | cp36 | Sep 27, 2018
tensorflow-1.11.0-cp36-cp36m-win_amd64.whl (46.9 MB)  Copy SHA256 hashSHA256 | Wheel | cp36 | Sep 27, 2018

**Comment by av8ramit** [comment]
Taking a look now.

**Comment by av8ramit** [comment]
@angersson any ideas?

**Comment by av8ramit** [comment]
This should be fixed now. Thanks @daniel-ziegler for bringing this to our attention. 

[Link](https://files.pythonhosted.org/packages/70/78/cd74769027b6249e45807637c1aa3ef212b9492349cca4b87e5de1a10548/tensorflow-1.11.0-cp36-cp36m-macosx_10_11_x86_64.whl)

**Comment by daniel-ziegler** [comment]
Works, thanks!
