### ISSUE TITLE
TFGAN support in tensorflow 2.0

### ISSUE THREAD

**Issue by galeone** [tensorflow/tensorflow#22596]
Hi everyone,

as written in the [roadmap](https://www.tensorflow.org/community/roadmap) `tf.contrib` will be deprecated/removed and some parts of it will be merged inside tensorflow core or moved to a separate repository and some removed.

Since in my team we're currently using tensorflow and TFGAN (and we like it a lot, we even hold a tutorial at EuroSciPy 2018 about GANs in Tensorflow [[1]]) we're looking closely at the Tensorflow 2.0 release and we would like to move our stack to this new version in the fastest and smoothest possible way.

In order to do this, a couple of questions (that I can't ask on StackOverflow, since you're the only one that knows what will happen on Tensorflow 2.0 and the community, outside of the maintainers, can't help a lot in this phase):

- Will TFGAN be moved to a separate project? If so, will the repo be available at the day-one?
- Since `tf.layer` will be removed in favor of `tf.keras.layers`: the implementation of our models into TFGAN, that are currently defined using `tf.layers` will work just switching to `tf.keras.layers` or have we to refactor all the existing codebase?

Thank you

[1]: https://github.com/zurutech/gans-from-theory-to-production

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by facaiy** [comment]
@galeone Hi, you can find more details and ask question at https://github.com/tensorflow/community/pull/18/files#diff-eef567fcebc6a5988c0fa92c7bb38526R192 

I'll close the issue, please feel free to reopen it if needed.
