### ISSUE TITLE
TensorFlow 1.11.0 with GPU support now requires CUDA Compute Capability 3.7?

### ISSUE THREAD

**Issue by skydreamer888** [tensorflow/tensorflow#22594]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, [cifar10_train.py](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_train.py)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Version 1803 OS Build 17134.320
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: b'v1.11.0-rc2-4-gc19e29306c' 1.11.0
- **Python version**: Python 3.6.6 :: Anaconda, Inc.
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 9.0/cuDNN v7.3.0
- **GPU model and memory**: GeForce GTX 780 Ti 3GB
- **Exact command to reproduce**: `python cifar10_train.py`

### Describe the problem
TensorFlow 1.11.0 now requires CUDA Compute Capability 3.7. But this was not mentioned in [
GPU support](https://www.tensorflow.org/install/gpu) or [Release Notes](https://github.com/tensorflow/tensorflow/releases/tag/v1.11.0). I want to ask whether this is intentional.

### Source code / logs

```
2018-09-28 18:31:27.274915: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.0715
pciBusID: 0000:01:00.0
totalMemory: 3.00GiB freeMemory: 2.45GiB
2018-09-28 18:31:27.278399: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1461] Ignoring visible gpu device (device: 0, name: GeForce GTX 780 Ti, pci bus id: 0000:01:00.0, compute capability: 3.5) with Cuda compute capability 3.5. The minimum required Cuda capability is 3.7.
```

**Comment by smitshilu** [comment]
Yes, They changed minimum CUDA Compute Capability to 3.7 from 3.0.

**Comment by av8ramit** [comment]
Yes this was intentional as part of our transition from cmake to bazel. @angersson maybe add this to the release notes?

**Comment by byronyi** [comment]
I guess you could always use customized-build for your GPU. After all, it’s still supported by CUDA and NV drivers.

**Comment by nimning** [comment]
I have a Tesla 63C K40C. The highest compute capability is 3.5. So, do you mean I have to buy a new GPU or install the older version tensorflow? Is there any setting I can use to make the current tensorflow also support GPU with capacity 3.5?

**Comment by byronyi** [comment]
@nimning AFAIK 3.5 or K40 series is always supported.

**Comment by smitshilu** [comment]
@nimning You can always build from source. If you don't want to do that then unfortunately you have to install older versions
