### ISSUE TITLE
`from tensorflow.g3doc...` is Broken

### ISSUE THREAD

**Issue by MarkDaoust** [tensorflow/tensorflow#226]
There are a dozen places in `g3doc/how_tos` and `g3doc/tutorials` where things are imported from the `g3doc` directory. 

The `g3doc` directory isn't included in the installation, and `tensorflow`, intentionally, can't be imported from the source directory, so those are likely all broken.

**Comment by mrdrozdov** [comment]
Any workarounds in the meantime?

**Comment by arieltci** [comment]
Yes, just remove the path name before the import. Change:
from tensorflow.g3doc.tutorials.mnist import input_data
from tensorflow.g3doc.tutorials.mnist import mnist
to :
import input_data
import mnist

**Comment by vrv** [comment]
Should be fixed in 0.6.0
