### ISSUE TITLE
Tensorflow 1.11.0 incompatible with keras2.2.2?

### ISSUE THREAD

**Issue by beew** [tensorflow/tensorflow#22601]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
No
- **TensorFlow installed from (source or binary)**:
Source

- **TensorFlow version (use command below)**:
1.11.0

- **Python version**:
3.5

- **Bazel version (if compiling from source)**:
0.17.2

- **GCC/Compiler version (if compiling from source)**:
5.4.0

- **CUDA/cuDNN version**:
CUDA 10
cuDNN 7.3

- **GPU model and memory**:
GTX1070

- **Exact command to reproduce**:
```
pip3 --no-cache-dir install ./tensorflow-1.11.0-cp35-cp35m-linux_x86_64.whl --user
```

Then  pip complains that
```
keras 2.2.2 has requirement keras-applications==1.0.4, but you'll have keras-applications 1.0.5 which is incompatible.
keras 2.2.2 has requirement keras-preprocessing==1.0.2, but you'll have keras-preprocessing 1.0.3 which is incompatible
```
But keras 2.2.2 is already the newest and it requires  keras-applications 1.0.4 and  keras-preprocessing 1.0.2.

Why does tensorflow require incompatible versions of keras-applications and keras-preprocessing? 

I reinstalled keras and it removed keras-applications 1.0.5 and and keras-processing 1.0.3 and installed 
 keras-applications 1.0.4 and keras-preprocessing 1.0.2 instead . I did a few tests with tensorflow  and it worked without problem.

If In tensorflow/tools/pip_package/setup.py change line 54 and 55 to

```
'keras_applications >= 1.0.4',
'keras_preprocessing >= 1.0.2',
```
before bazel build pip package then I think pip3 install would happily go along without complaint.   Are these incompatible requirements really necessary??

**Comment by canthonyscott** [comment]
Running this on Windows and I have this same notification as well when installing these versions of keras and tensorflow

**Comment by atul2427** [comment]
tensorflow 1.11.0 has requirement keras-applications>=1.0.5, but you'll have keras-applications 1.0.4 which is incompatible.
but when i install 1.0.5 it required for 1.0.4

**Comment by wt-huang** [comment]
Is this still an issue?
