### ISSUE TITLE
Is official 1.11.0 pip package for windows build by bazel or cmake?

### ISSUE THREAD

**Issue by fo40225** [tensorflow/tensorflow#22613]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**: vs2017 15.8 / msvc 19.15.26726
- **CUDA/cuDNN version**: 10.0.130_411.31/7.3.0.29
- **GPU model and memory**: 1080ti 11GB
- **Exact command to reproduce**: pip install tensorflow-gpu

### Describe the problem

In 1.10 release notes, you say `Starting from TensorFlow 1.11, Windows builds will use Bazel. Therefore, we will drop official support for cmake.`, but table from https://www.tensorflow.org/install/source_windows indicate that 1.11 is build by cmake.

The cuDNN version described in the table from https://www.tensorflow.org/install/source_windows or https://www.tensorflow.org/install/source still 7, not 7.2 or 7.x.x. Which version of cudnn do you used to build pip package?

Nvidia's website didn't provide cudnn 7.2 for cuda 9.0 download, please provide more clarify documentation.

Thanks

### Source code / logs

```
pip install tensorflow-gpu==1.11.0
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
b'v1.11.0-rc2-4-gc19e29306c' 1.11.0
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Mobile device

**Comment by fo40225** [comment]
@tensorflowbutler 

- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A

**Comment by av8ramit** [comment]
We have switched over to using bazel rather than cmake for Windows. The cmake build will still be supported by the community. 

I have updated the [release notes](https://github.com/tensorflow/tensorflow/releases/tag/v1.11.0) We had mentioned this in the 1.10 release, but forgot to mention it now. Thanks @fo40225 for bringing this to our attention.
