### ISSUE TITLE
compiler/tests/stateless_random_ops_test.py:testRandomNormalIsFinite doesn't

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#22611]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: n/a
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: n/a
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: n/a
- **TensorFlow installed from (source or binary)**: n/a
- **TensorFlow version (use command below)**: n/a
- **Python version**: n/a
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: n/a

### Describe the problem

@hawkinsp wrote a test called [`testRandomNormalIsFinite`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tests/stateless_random_ops_test.py#L94), but it uses `stateless_random_uniform` instead of `stateless_random_normal`.

### Source code / logs

N/A.

**Comment by hawkinsp** [comment]
Oops! Good catch. I'll fix the test.
