### ISSUE TITLE
Here is a list of operators for which  you will need custom implementations: ListDiff

### ISSUE THREAD

**Issue by dlml** [tensorflow/tensorflow#22610]
i use tf.keras to save my h5 model, and convert to tflite, this op can't be supported

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by dlml** [comment]
i have solved this bug， i will close this issue

**Comment by sadknight0001** [comment]
> i have solved this bug， i will close this issue

Could you tell me how you solved the problem? I've got the same but i cant locate where Listdiff had been used
