### ISSUE TITLE
cannot make learning rate as variable when using keras model to estimator

### ISSUE THREAD

**Issue by vbvg2008** [tensorflow/tensorflow#22618]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: pip install
- **TensorFlow version (use command below)**: 1.11.0-cpu-py3
- **Python version**:3.6.5
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA 
- **GPU model and memory**: NA
- **Exact command to reproduce**: run the code provided below 

### Describe the problem
I was trying to make learning rate a variable and control it using hook during training, however, it gives me the following error <Tensor("Variable/read:0", shape=(), dtype=float32) must be from the same graph as Tensor("dense/kernel:0", shape=(), dtype=resource).>

PS: when I define the estimator through the generic "model_fn" instead of keras, variable learning rate can work.  Therefore, I believe the issue comes from tf.keras.estimator.model_to_estimator

### Source code / logs
```
import tensorflow as tf
import numpy as np

def estimator_fn():
    x_in = tf.keras.layers.Input(shape=[10])
    x = tf.keras.layers.Dense(16, activation='relu')(x_in)
    x_out = tf.keras.layers.Dense(1, activation='sigmoid')(x)
    model = tf.keras.models.Model(x_in, x_out)
    lr = tf.Variable(0.1, trainable=False, dtype=tf.float32)
    optimizer = tf.train.GradientDescentOptimizer(lr)
    model.compile(loss='binary_crossentropy', optimizer= optimizer)
    estimator = tf.keras.estimator.model_to_estimator(keras_model = model)
    return estimator

def input_fn():
    np.random.seed(100)
    x = np.random.random((1024, 10))
    y = np.random.randint(2, size=(1024, 1))
    x = tf.cast(x, tf.float32)
    dataset = tf.data.Dataset.from_tensor_slices((x, y))
    dataset = dataset.repeat()
    dataset = dataset.batch(1024)
    return dataset
  
model_estimator = estimator_fn()
model_estimator.train(input_fn=input_fn, steps=1000)
```

**Comment by wt-huang** [comment]
@vbvg2008 You can make learning rate a variable, try using `keras.optimizers` instead. Just modified your code as below and executed it without running into error.

```
import tensorflow as tf
import numpy as np
from keras import optimizers

def estimator_fn():
    x_in = tf.keras.layers.Input(shape=[10])
    x = tf.keras.layers.Dense(16, activation='relu')(x_in)
    x_out = tf.keras.layers.Dense(1, activation='sigmoid')(x)
    model = tf.keras.models.Model(x_in, x_out)
    lr = tf.Variable(0.1, trainable=False, dtype=tf.float32)
    optimizer = keras.optimizers.SGD(lr, momentum=0.0, decay=0.0, nesterov=False)
    model.compile(loss='binary_crossentropy', optimizer= optimizer)
    estimator = tf.keras.estimator.model_to_estimator(keras_model = model)
    return estimator

def input_fn():
    np.random.seed(100)
    x = np.random.random((1024, 10))
    y = np.random.randint(2, size=(1024, 1))
    x = tf.cast(x, tf.float32)
    dataset = tf.data.Dataset.from_tensor_slices((x, y))
    dataset = dataset.repeat()
    dataset = dataset.batch(1024)
    return dataset
  
model_estimator = estimator_fn()
model_estimator.train(input_fn=input_fn, steps=1000)
```

**Comment by vbvg2008** [comment]
@wt-huang Thanks for your reply.  But the thing is: I am trying to use mirrored strategy to do multi-gpu training. Only optimizers from tf.train are supported.  

If there can be some fix on the model_to_estimator side, it would be greatly appreciated.

**Comment by wt-huang** [comment]
@vbvg2008 For multi-gpu training you can add the following to the code:
```
import tensorflow as tf
import numpy as np
import keras
from keras import optimizers

def estimator_fn():
    x_in = tf.keras.layers.Input(shape=[10])
    x = tf.keras.layers.Dense(16, activation='relu')(x_in)
    x_out = tf.keras.layers.Dense(1, activation='sigmoid')(x)
    model = tf.keras.models.Model(x_in, x_out)
    lr = tf.Variable(0.1, trainable=True, dtype=tf.float32)
    optimizer = keras.optimizers.SGD(0.01, momentum=0.0, decay=0.0, nesterov=False)
    model.compile(loss='binary_crossentropy', optimizer= optimizer)
    num_gpu = 2
    dist = tf.contrib.distribute.MirroredStrategy(num_gpus=num_gpu)
    conf = tf.estimator.RunConfig(train_distribute=dist)
    estimator = tf.keras.estimator.model_to_estimator(keras_model = model, config=conf)
    return estimator

def input_fn():
    np.random.seed(100)
    x = np.random.random((1024, 10))
    y = np.random.randint(2, size=(1024, 1))
    x = tf.cast(x, tf.float32)
    dataset = tf.data.Dataset.from_tensor_slices((x, y))
    dataset = dataset.repeat()
    dataset = dataset.batch(1024)
    return dataset
  
model_estimator = estimator_fn()
model_estimator.train(input_fn=input_fn, steps=1000)
```

**Comment by vbvg2008** [comment]
@wt-huang Hi, thanks again for the reply. However, I don't think your solution works.

Executing your fixed code gives me error message saying <ValueError: ('Could not interpret optimizer identifier:', <keras.optimizers.SGD object at 0x7fb12460f310>)>. I believe it is bad practice to mix the usage of keras and tf.keras.

Also, even I use tf.keras.optimizers.SGD instead, it gives me the error message saying <alueError: Only TensorFlow native optimizers are supported with DistributionStrategy.>.  I believe only Only optimizers from tf.train are supported. 

The current tensorflow 's model_to_estimator is not compatible with  tf.train optimizers with variable learning rate.  I believe the right direction should be focusing on the model_to_estimator code.

**Comment by wt-huang** [comment]
@vbvg2008 thought I could trust copy/paste. Edited the above code, which you can use as a guideline. Essentially `tf.keras.utils.multi_gpu_model` could get what you need, refer to this [page](https://www.tensorflow.org/api_docs/python/tf/keras/utils/multi_gpu_model) for more details.

**Comment by CorbanSwain** [comment]
I'm having this same issue. It seems like there needs to be a way to retrieve a global_step tensor in a compatible manner. I think there are some advantages to the TensorFlor distributed estimator method that the keras multi_gpu_model doesn't capture (i.e. distributing the entire model over multiple GPUs [estimator]rather than running computations in parallel over multiple GPUs [multi_gpu_model]), so it would still be relevant to find a compatible method.

**Comment by jacobsn** [comment]
I am having the same issue.  I would like to be able to use Keras to define a model, convert to TPUEstimator, and use an adaptive learning rate policy.  So far, I can't figure out a good solution and it all seems to point back to this issue.

Any good workarounds?

**Comment by Jasonnor** [comment]
+1 multi_gpu_model is not a substitute for estimator (it's slow and not fully support multi-gpu), this issue should be reopen.

**Comment by jacobbentolila** [comment]
Hi, 

Did anyone found a workaround ?
