### ISSUE TITLE
tensors_flowing.gif

### ISSUE THREAD

**Issue by sunbozhang** [tensorflow/tensorflow#2262]
who knows how to make this gif? https://www.tensorflow.org/images/tensors_flowing.gif

**Comment by martinwicke** [comment]
@colah did you make this one?

**Comment by petewarden** [comment]
From previous discussions, I believe this was manually created with After Effects, so there isn't an easy way to do something similar without using motion graphics tools.

**Comment by martinwicke** [comment]
I've made great animations using Keynote. This one would actually be pretty easy, just tedious.

**Comment by bhack** [comment]
Or D3 with an SVG/JS ninja  :smile: http://bl.ocks.org/nitaku/6354551

**Comment by bhack** [comment]
http://bl.ocks.org/mbostock/5649592

**Comment by girving** [comment]
Closing, since this is a question not an issue.

**Comment by sahaskarkera** [comment]
Is it possible to train GIF and TIFF images in tensor-flow image classification?
