### ISSUE TITLE
FailedPreconditionError in of tf.keras TF1.11 but not TF1.10

### ISSUE THREAD

**Issue by henrysky** [tensorflow/tensorflow#22621]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 RS4 x64
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.11
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 10/7.3
- **GPU model and memory**: GTX1060 6GB
- **Exact command to reproduce**:

```
import tensorflow as tf
get_session = tf.keras.backend.get_session
a = tf.Variable([[0.5, 0., 1.], [2., 0., -1.]])
tf.add(a, a).eval(session=get_session())
```

### Describe the problem
A code that run with TF1.10 but not TF1.11

### Source code / logs
```
FailedPreconditionError (see above for traceback): Attempting to use uninitialized value Variable_1
	 [[{{node Variable_1/read}} = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable_1)]]
```

**Comment by ymodak** [comment]
You can initialize the variables using function [global_variables_initializer()](://www.tensorflow.org/api_docs/python/tf/Variable)
Also refer [this](https://www.tensorflow.org/api_docs/python/tf/initializers/global_variables)
This should pass:
import tensorflow as tf
get_session = tf.keras.backend.get_session
a = tf.Variable([[0.5, 0., 1.], [2., 0., -1.]])
with tf.Session() as sess: 
    sess.run(tf.global_variables_initializer())
    print(tf.add(a, a).eval(session=get_session()))

**Comment by henrysky** [comment]
thank you this is a solution but in the past  (tf 1.10=<) we don't have to do that with tf.keras get_session. Should I adapt this new way to do things or this is a bug?

**Comment by henrysky** [comment]
Thanks

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
