### ISSUE TITLE
Building tensorflow on Aarch64 (bazel newer than 0.16.0) has no default_toolchain provided.

### ISSUE THREAD

**Issue by n-west** [tensorflow/tensorflow#22629]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04 on NVIDIA Jetson AGX Xavier (Aarch64)
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
N/A
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
1.10.1
- **Python version**:
- **Bazel version (if compiling from source)**:
0.17.2
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
NVIDIA Jetson Xavier
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

Compiling on a Jetson AGX Xavier board yields an error `ERROR: No default_toolchain found for cpu 'aarch64'. Valid cpus are`...

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

### Commentary

It looks like the problem is that recent (newer than 0.16.0) versions of bazel provide a named cpu for aarch64 rather than wrapping it in to ARM. The relevent bazel commit is https://github.com/bazelbuild/bazel/commit/886d01c89fca32e46f5841081eb3288e5b4f313b#diff-1ec7b345acf6aff694c52be93dc2f3d1. Using bazel 0.15.2 on aarch64 works (although needs the patch https://github.com/JasonAtNvidia/JetsonTFBuild/blob/master/jetson.patch)

**Comment by n-west** [comment]
Perfect. That looks like the same issue. I don't really know bazel all that well-- would tensorflow/BUILD be the file to make a similar change to to get the full build running? My interest is actually in tensorflow_cc.so

**Comment by ymodak** [comment]
@n-west  Is this still an issue?

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
