### ISSUE TITLE
Why using Camera2 API for Android Tensorflow Lite Demo?

### ISSUE THREAD

**Issue by anonym24** [tensorflow/tensorflow#22620]
Many manufactures didn't implemented Camera2 that well https://github.com/googlesamples/android-Camera2Basic/issues/123

So it's better to use legacy Camera API even for Android API >= 25

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by aselle** [comment]
@shashishekhar  so you have any insight on this? I suspect we just used the new API arbitrarily.

**Comment by shashishekhar** [comment]
@anonym24 : Which manufacturers are you talking about? Do you have an example where the API is correctly implemented by one manufacturer and not implemented by another manufacturer.  

@aselle: Camera2 API is the official API, Camera 1 API is deprecated.

**Comment by anonym24** [comment]
The main issue with Camera2 API that I can't set Full HD resolution for preview (1920x1080), though it can be done with Legacy Camera API

Proofs:

https://github.com/googlesamples/android-Camera2Basic/issues/123
https://stackoverflow.com/questions/31362202/android-camera2-output-sizes
https://stackoverflow.com/questions/52374888/camera2-1440x1080-is-maximum

I tried some Xiaomi devices, some users reported this problem on Samsung devices (see stackoverflow links)

Seems many phone manufactures didn't care about Camera2 that much

**Comment by shashishekhar** [comment]
@anonym24 : Thank you for the links. This seems like a bad implementation on some particular manufacturers. I hope in future the manufacturers will fix these bugs. Most of our samples are forward looking so we want to support Camera 2 API, rather than Camera 1. This is certainly not a problem with AOSP.

I agree for production use cases, you may have to do workarounds against bugs and may need to use Camera 1 API for your use case.
