### ISSUE TITLE
[BUG] tf.batch_gather error when feeding int64 indices

### ISSUE THREAD

**Issue by wwt17** [tensorflow/tensorflow#22638]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: using CPU
- **GPU model and memory**: using CPU
- **Exact command to reproduce**:
```
import tensorflow as tf
x = [[0, 1, 2], [3, 4, 5]]
y = tf.convert_to_tensor([[1, 2, 0], [2, 0, 1]], dtype=tf.int64)
tf.batch_gather(x, y)
```
### Describe the problem
When feeding an int64 Tensor as `indices` to `tf.batch_gather`, an error occurs.

### Source code / logs
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1144, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 981, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int64 for Tensor with dtype int32: 'Tensor("Reshape:0", shape=(2, 1), dtype=int32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 4, in <module>
    tf.batch_gather(x, y)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 2726, in batch_gather
    batch_indices += reshape(dim_indices, dim_shape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 862, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 301, in add
    "Add", x=x, y=y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 546, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Add' Op has type int32 that does not match type int64 of argument 'x'.
```

The error occurs [here](https://github.com/tensorflow/tensorflow/blob/5fa4e1ac928b0512b28e955c588c5a7eab2ea046/tensorflow/python/ops/array_ops.py#L2726) at the first `for` iteration. I found `batch_indices` is an int64 Tensor, while `dim_indices` is an int32 Tensor.
Obviously, a simple fix is to cast `dim_indices` to the dtype of the input `indices`. I wonder if I can directly send a pull request.

**Comment by harshini-gadige** [comment]
@wwt17 Hi, can you try using tf.to_int64() for the conversion and see if it works

**Comment by harshini-gadige** [comment]
@ebrevdo Hi, could you please look into this one. The datatype of y is int64 but it says as "Input 'y' of 'Add' Op has type int32" in the error message.

**Comment by ebrevdo** [comment]
Unfortunately I don't have cycles to look at this.

**Comment by alextp** [comment]
I'd love to approve a pull request with the cast you suggest (and a unit test which fails without it)!

**Comment by wwt17** [comment]
I found this issue has been solved in [this commit](https://github.com/tensorflow/tensorflow/commit/6cc738da1748e819b9c8ee92dc2f1a7bdb291b50).
