### ISSUE TITLE
Cmake can't handle deprecated files (assert_next_dataset_op.cc...)

### ISSUE THREAD

**Issue by theVmagnificient** [tensorflow/tensorflow#22634]
Have I written custom code - No

OS Platform and Distribution - Windows 10

Cmake cannot find deprecated files 

CMake Error at tf_core_kernels.cmake:221 (add_library):
  Cannot find source file:

    C:/tensorflow/tensorflow/contrib/data/kernels/assert_next_dataset_op.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:525 (include)

CMake Error at tf_core_ops.cmake:73 (add_library):
  Cannot find source file:

    C:/tensorflow/tensorflow/contrib/data/ops/dataset_ops.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  tf_core_ops.cmake:92 (GENERATE_CONTRIB_OP_LIBRARY)
  CMakeLists.txt:523 (include)

CMake Error at tf_core_ops.cmake:73 (add_library):
  No SOURCES given to target: tf_contrib_data_dataset_ops
Call Stack (most recent call first):
  tf_core_ops.cmake:92 (GENERATE_CONTRIB_OP_LIBRARY)
  CMakeLists.txt:523 (include)

CMake Error at tf_core_kernels.cmake:221 (add_library):
  No SOURCES given to target: tf_core_kernels
Call Stack (most recent call first):
  CMakeLists.txt:525 (include)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by theVmagnificient** [comment]
Have I written custom code - No
OS Platform and Distribution - Windows 10
TensorFlow installed from - Git
TensorFlow version - Last
Bazel version - Last
CUDA/cuDNN version NA
GPU model and memory NA
Exact command to reproduce NA
Mobile device NA

**Comment by azaks2** [comment]
The files have been recently moved around that broke cmake. Since the latter is no longer supported you should switch to bazel.

**Comment by harshini-gadige** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by yoobright** [comment]
still can not find C:/tensorflow/tensorflow/contrib/data/ops/dataset_ops.cc on master branch.

**Comment by s091704** [comment]
The weird part in all of this is that when you use Bazel on windows to build tensorflow libs, it keeps failing.
When you search for  those errors you only find people telling you NOT to use bazel because there is no support on windows so far.
Then when we use Cmake you guys tell us to use bazel because you broke Cmake...

**Comment by Arritmic** [comment]
Hi, 
A similar error here:
````
(base) C:\projects\External\OLD\tensorflow\tensorflow\contrib\cmake\build>cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=C:\Users\Tino\bin\swigwin-3.0.12\swig.exe -DPYTHON_EXECUTABLE=C:\Users\Tino\Anaconda3\python.exe -DPYTHON_LIBRARIES=C:\Users\Tino\Anaconda3\libs\python37.lib -Dtensorflow_BUILD_PYTHON_BINDINGS=OFF
CMake Warning at CMakeLists.txt:9 (message):
  Your current cmake generator is set to use 32 bit toolset architecture.
  This may cause "compiler out of heap space" errors when building.  Consider
  using the flag -Thost=x64 when running cmake.


-- Configuring done
CMake Error at tf_core_framework.cmake:328 (add_library):
  Cannot find source file:

    C:/projects/External/OLD/tensorflow/tensorflow/core/util/version_info.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:518 (include)


CMake Error at tf_core_ops.cmake:73 (add_library):
  Cannot find source file:

    C:/projects/External/OLD/tensorflow/tensorflow/contrib/data/ops/dataset_ops.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  tf_core_ops.cmake:92 (GENERATE_CONTRIB_OP_LIBRARY)
  CMakeLists.txt:524 (include)


CMake Error at tf_core_kernels.cmake:218 (add_library):
  Cannot find source file:

    C:/projects/External/OLD/tensorflow/tensorflow/contrib/data/kernels/assert_next_dataset_op.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:526 (include)


CMake Error: CMake can not determine linker language for target: tf_core_framework
CMake Error: CMake can not determine linker language for target: tf_contrib_data_dataset_ops
CMake Error: CMake can not determine linker language for target: tf_core_kernels
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    SWIG_EXECUTABLE


-- Build files have been written to: C:/projects/External/OLD/tensorflow/tensorflow/contrib/cmake/build
```
I have Windows 10 x64
Anaconda 3
Swig

**Comment by Steroes** [comment]
@Arritmic Using release v1.12.0, some contrib/data/kernels files moved to core/kernels/data/experimental. You can search for the filenames that are missing and change the filepaths in the tf_core_framework.cmake and tf_core_kernels.cmake files.

**Comment by Arritmic** [comment]
Thank you so much. :)

**Comment by Oceania2018** [comment]
Still can't find `tensorflow\contrib\data\ops\dataset_ops.cc`, after I copied that file to `contrib\data\ops`, it works. starting compiling...

**Comment by Hema414** [comment]
@Steroes Thank you, it helped.

**Comment by Steroes** [comment]
@Hema414 You can also build tensorflow using bazelon windows or linux using this [guide](https://github.com/guikarist/tensorflow-windows-build-script).

**Comment by rikichou** [comment]
@Steroes，it is work,thanks

**Comment by shoutOutYangJie** [comment]
> @Hema414 You can also build tensorflow using bazelon windows or linux using this [guide](https://github.com/guikarist/tensorflow-windows-build-script).

How could I use libtensorflow_cc.so in Windows system?

**Comment by Steroes** [comment]
@shoutOutYangJie libtensorflow_cc.so is actually a dll file. When you follow the guide in the link i provided earlier, then it will eventually provide you with a ddl (just a rename of the .so file) and a .lib file. With CMake you can link to the dll by linking to the .lib file. If you then include the header files that are required (see also the guide) then you can link it to you example code.

**Comment by shoutOutYangJie** [comment]
you means i can use cmake to transfer .so file to .dll file ?


 
---Original---

**Comment by Arritmic** [comment]
Hi,
CMake is an open-source, cross-platform family of tools designed to build, test and package software. That means if you are working on Windows, you can compile tensorflow for Windows, and it will be something like libtensorflow_cc.dll (dynamic lib) or libtensorflow_cc.lib (static lib). Then, you will be able to link it in your cmake project, qt project or whatever other build system.

Also, if you may compile tensorflow library inside of your cmake project. It would be something like this:

```
if(NOT TARGET tensorflow) 
        get_filename_component(tf_build_DIR ${CMAKE_BINARY_DIR}/intermediates/tensorflow REALPATH)
        file(MAKE_DIRECTORY ${tf_build_DIR})
        add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/../../path/to/tensorflow/ ${tf_build_DIR})
endif()
```

And finally if you are on Windows:
```

if(CMAKE_SYSTEM_NAME STREQUAL Windows)
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MD")
    set_property(TARGET tensorflow-lite PROPERTY CXX_STANDARD 17)
    set_property(TARGET tensorflow-lite PROPERTY CXX_STANDARD_REQUIRED ON)
    target_link_libraries(MyProject  tensorflow)
endif()
```
