### ISSUE TITLE
Query regarding 1.11.0 release

### ISSUE THREAD

**Issue by nehaljwani** [tensorflow/tensorflow#22636]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: Binary
- **Python version**: N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
Two questions:
- Are the wheels uploaded on PyPI for Windows made using bazel or cmake?
- The wheels uploaded on PyPI for macOS claim that they target 10.11, however, the function at https://github.com/tensorflow/tensorflow/blob/v1.11.0/tensorflow/core/platform/posix/env_time.cc#L31 uses `clock_gettime`, which wasn't available till 10.12 was released. So, how was it built? 🤔

**Comment by wt-huang** [comment]
@nehaljwani 1.11.0 for Windows uses bazel, cmake is deprecated. You are correct that `clock_gettime` was not built prior to 10.12, it requires custom implementation in `libzmq`. The wheels targeting 10.11 use custom implementation.

**Comment by nehaljwani** [comment]
How is the custom implementation for `clock_gettime` being used? I don't see it in the source code anywhere. I am asking that because the build failed for me and I had to apply this patch:
```patch
diff --git a/tensorflow/core/platform/posix/env_time.cc b/tensorflow/core/platform/posix/env_time.cc
index 59a67b1..88f8a6c 100644
--- a/tensorflow/core/platform/posix/env_time.cc
+++ b/tensorflow/core/platform/posix/env_time.cc
@@ -18,6 +18,23 @@ limitations under the License.

 #include "tensorflow/core/platform/env_time.h"

+// Slightly pruned version of https://gist.github.com/alfwatt/3588c5aa1f7a1ef7a3bb
+// Copyright (c) 2015-2018 Alf Watt - Open Source - https://opensource.org/licenses/MIT
+#if defined __APPLE__
+#include <mach/clock.h>
+#include <mach/mach.h>
+int alt_clock_gettime (int clock_id, timespec *ts) {
+  clock_serv_t cclock;
+  mach_timespec_t mts;
+  host_get_clock_service (mach_host_self (), clock_id, &cclock);
+  clock_get_time (cclock, &mts);
+  mach_port_deallocate (mach_task_self (), cclock);
+  ts->tv_sec = mts.tv_sec;
+  ts->tv_nsec = mts.tv_nsec;
+  return 0;
+}
+#endif
+
 namespace tensorflow {

 namespace {
@@ -28,7 +45,11 @@ class PosixEnvTime : public EnvTime {

   uint64 NowNanos() override {
     struct timespec ts;
+#if defined __APPLE__ && __MAC_OS_X_VERSION_MIN_REQUIRED < 101200 // less than macOS 10.12
+    alt_clock_gettime(CALENDAR_CLOCK, &ts);
+#else
     clock_gettime(CLOCK_REALTIME, &ts);
+#endif
     return (static_cast<uint64>(ts.tv_sec) * kSecondsToNanos +
             static_cast<uint64>(ts.tv_nsec));
   }
--
2.5.4 (Apple Git-61)
```

**Comment by gunan** [comment]
All of our wheels are not using bazel to be built, including windows.
For macos, @av8ramit @yifeif what is our build infra using?
I am thinking we use el capitan to build for macos?

And the final question, no. even at head, that PR is partially rolled back.

**Comment by yifeif** [comment]
I think we have 10.12.6  sierra?
