### ISSUE TITLE
[Feature request] Refactor gFile out into separate library?

### ISSUE THREAD

**Issue by brilee** [tensorflow/tensorflow#22637]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.8.0-0-g93bc2e2072 1.8.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
I really love gfile's API/ abstraction layer for wrapping GCS, and it's my primary method of scripting file manipulations (as opposed to, say, using a subprocessed gsutil and scraping stdout). However, TensorFlow's long import time imposes a high overhead on these scripts because `from tensorflow import gfile` will import all of TensorFlow. It'd be nice if gfile were refactored into a separate python module.

**Comment by harshini-gadige** [comment]
@mrry Hi, can this be added as a new feature request ?

**Comment by mrry** [comment]
@martinwicke Is this something you'd be interested in having done? Or is it something we might eventually get from Abseil?

**Comment by martinwicke** [comment]
We have no plans to refactor it in this manner. However, opensource is awesome! If you're willing to do the work, you could certainly move the code out and maintain it separately. I think a filesystem abstraction library would be a great addition to the Python ecosystem, and if a well maintained option emerges, we would consider depending on it as well.

**Comment by martinwicke** [comment]
I'll close this issue as we have no plans on working on this.

**Comment by shoyer** [comment]
It might be worth taking a look at [GCSFS](https://gcsfs.readthedocs.io/)/[S3Fs](https://s3fs.readthedocs.io/en/latest/) or [PyFilesystem](https://www.pyfilesystem.org/).
