### ISSUE TITLE
TensorFlow 1st Test: “could not open file to read NUMA node” - what's wrong?

### ISSUE THREAD

**Issue by petamem** [tensorflow/tensorflow#2264]
I went to StackOverflow with this and was pointed back to Github. ;-)
see [http://stackoverflow.com/questions/37067297]

### Environment info
Operating System: Gentoo Linux on Lenovo P50

Installed version of CUDA and cuDNN: 
I installed dev-util/nvidia-cuda-toolkit package, version 7.5.18-r2

```
# ll /opt/cuda/lib/libcud*
-rw-r--r-- 1 root root 189082 May  6 10:42 /opt/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Sep 19  2015 /opt/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Sep 19  2015 /opt/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Sep 19  2015 /opt/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 557240 May  6 10:42 /opt/cuda/lib/libcudart_static.a
```
Plus I installed cuDNN 5 downloaded from Nvidia
```
# ll libcud*
lrwxrwxrwx 1 rj rj       13 Mar 22 08:44 libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 rj rj       17 Mar 22 08:44 libcudnn.so.5 -> libcudnn.so.5.0.4
-rwxrwxr-x 1 rj rj 59823168 Mar 22 02:37 libcudnn.so.5.0.4
-rw-rw-r-- 1 rj rj 58734618 Mar 22 02:37 libcudnn_static.a
```
If installed from binary pip package, provide:

Which pip package you installed.
```
# pip3 -V
pip 8.1.1 from /usr/lib64/python3.4/site-packages (python 3.4)
```
The output from python -c "import tensorflow; print(tensorflow.__version__)".
```
# python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.8.0
```

### Steps to reproduce
1. import tensorflow as tf
2. hello = tf.constant('Hello, TensorFlow!')
3. sess = tf.Session()

### What have you tried?
1. stackoverflow ;-)

**Comment by petewarden** [comment]
For reference, here's the error output from StackOverflow:
```
E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Quadro M2000M
major: 5 minor: 0 memoryClockRate (GHz) 1.137
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.96GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro M2000M, pci bus id: 0000:01:00.0)
F tensorflow/core/common_runtime/gpu/process_state.cc:155] Check failed: numa_node >= 0 (-1 vs. 0)
Aborted
```

Assigning to @poxvoculi

**Comment by yaroslavvb** [comment]
For reference, cuda_gpu_executor [here](https://github.com/tensorflow/tensorflow/blob/7b4d733593842361d066d7e33a03a07da5dca465/tensorflow/stream_executor/cuda/cuda_gpu_executor.cc#L905) should've convereted all -1 to 0 (I've gotten -1 Numa node on machines with 1 or 2 nodes, but it turns into 0 in the end

**Comment by poxvoculi** [comment]
Thanks @yaroslavvb, looks like it's failing to get the numa node on one of the other logic paths through TryToReadNumaNode.  @petamem: Fix coming.  Meanwhile, it's probably safe for you to hack common_runtime/gpu/gpu_device to set the num_node parameter to 0, where it is used.  This value is only important if you have multiple GPUs on different PCI buses.  If that's your case, then we need to fix the stream executor to find the numa node correctly.

**Comment by petamem** [comment]
If there's anything I can do to help searching for the culprit (enabling some debug switches, using other (combinations of) versions), let me know.

**Comment by petamem** [comment]
Ok. In order to test the hypothesis that I could mitigate the error by disabling the Intel P530 GPU, I disabled it in the BIOS. lspci henceforth does not list it, so for the OS it should look like there is only one GPU - the M2000M - present.

Unfortunately, the error remains the same (GPU just uses slightly more memory because the frame buffer):

```
>>> sess = tf.Session()
E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Quadro M2000M
major: 5 minor: 0 memoryClockRate (GHz) 1.137
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.68GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro M2000M, pci bus id: 0000:01:00.0)
F tensorflow/core/common_runtime/gpu/process_state.cc:155] Check failed: numa_node >= 0 (-1 vs. 0)
```
Which leads me to the conclusion, that there must be some own OS-independent GPU detection routine present. Not sure if this is a good thing.

Any ETA for the fix? I could try hacking common_runtime/gpu/gpu_device as suggested, but if there's soon a fix, that'd be probably moot.

**Comment by poxvoculi** [comment]
Unfortunately, the fix is not in the latest (pending) merge up from Google: https://github.com/tensorflow/tensorflow/pull/2299
It should be in the next one.  The testing process makes the code pushes slow.

If you'd like to help debug the underlying problem, look at tensorflow/stream_executor/cuda/cuda_gpu_executor.cc
In there is a function TryToReadNumaNode() which examines the /sys/ directory to try to find the socket/bus affinity of a GPU device.  Evidently this doesn't work on your system.  It would be nice to know why: is the data not present, or stored somewhere else?

If you just want to get on with your other task, override the kUnknownNumaNode value (-1) being returned with 0, and the rest of the system should work ok...assuming that TF is actually accessing the correct GPU.  (Notice that for OS/X that's exactly what happens in TryToReadNumaNode().)

**Comment by petamem** [comment]
Hm. I'm afraid the path template "/sys/bus/pci/devices/%s/numa_node" cannot be found on my system as /sys/bus/pci/devices looks like that:

    # ll /sys/bus/pci/devices/0000\:*
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:00.0 -> ../../../devices/pci0000:00/0000:00:00.0
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:01.0 -> ../../../devices/pci0000:00/0000:00:01.0
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:14.0 -> ../../../devices/pci0000:00/0000:00:14.0
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:14.2 -> ../../../devices/pci0000:00/0000:00:14.2
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:16.0 -> ../../../devices/pci0000:00/0000:00:16.0
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:16.3 -> ../../../devices/pci0000:00/0000:00:16.3
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:17.0 -> ../../../devices/pci0000:00/0000:00:17.0
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:1c.0 -> ../../../devices/pci0000:00/0000:00:1c.0
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:1c.2 -> ../../../devices/pci0000:00/0000:00:1c.2
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:1c.4 -> ../../../devices/pci0000:00/0000:00:1c.4
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:1d.0 -> ../../../devices/pci0000:00/0000:00:1d.0
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:1d.4 -> ../../../devices/pci0000:00/0000:00:1d.4
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:1f.0 -> ../../../devices/pci0000:00/0000:00:1f.0
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:1f.2 -> ../../../devices/pci0000:00/0000:00:1f.2
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:1f.3 -> ../../../devices/pci0000:00/0000:00:1f.3
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:1f.4 -> ../../../devices/pci0000:00/0000:00:1f.4
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:00:1f.6 -> ../../../devices/pci0000:00/0000:00:1f.6
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:01:00.0 -> ../../../devices/pci0000:00/0000:00:01.0/0000:01:00.0
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:01:00.1 -> ../../../devices/pci0000:00/0000:00:01.0/0000:01:00.1
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:04:00.0 -> ../../../devices/pci0000:00/0000:00:1c.2/0000:04:00.0
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:3e:00.0 -> ../../../devices/pci0000:00/0000:00:1d.0/0000:3e:00.0
    lrwxrwxrwx 1 root root 0 May 11 15:06 /sys/bus/pci/devices/0000:3f:00.0 -> ../../../devices/pci0000:00/0000:00:1d.4/0000:3f:00.0

    ls /sys/bus/pci/devices/*/numa_node
   no such file or directory

Which it does - of course, because the kernel has no NUMA support. :-)
So I compiled a new 4.5.3 kernel with NUMA support and ... 

    >>> sess = tf.Session()
    I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
    I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
    name: Quadro M2000M
    major: 5 minor: 0 memoryClockRate (GHz) 1.137
    pciBusID 0000:01:00.0
    Total memory: 4.00GiB
    Free memory: 3.47GiB
    I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
    I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
    I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro M2000M, pci bus id: 0000:01:00.0)

So it seems my problem was simply due to the fact, that the kernel had no NUMA support.
I will now switch back to Hybrid mode (activate the Intel GPU) and test if that works with NUMA enabled.

**Comment by poxvoculi** [comment]
Thanks, glad you found a solution.  I'll look into the error messages.

**Comment by abhijayghildyal** [comment]
When I ran 

    bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu

it gave me the following error:

    I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
	I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
	I tensorflow/core/common_runtime/gpu/gpu_init.cc:118] Found device 0 with properties: 
	name: GeForce GT 640
	major: 3 minor: 0 memoryClockRate (GHz) 0.9015
	pciBusID 0000:05:00.0
	Total memory: 2.00GiB
	Free memory: 1.98GiB
	I tensorflow/core/common_runtime/gpu/gpu_init.cc:138] DMA: 0 
	I tensorflow/core/common_runtime/gpu/gpu_init.cc:148] 0:   Y 
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:843] Ignoring gpu device (device: 0, name: GeForce GT 640, pci bus id: 0000:05:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:843] Ignoring gpu device (device: 0, name: GeForce GT 640, pci bus id: 0000:05:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:843] Ignoring gpu device (device: 0, name: GeForce GT 640, pci bus id: 0000:05:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:843] Ignoring gpu device (device: 0, name: GeForce GT 640, pci bus id: 0000:05:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:843] Ignoring gpu device (device: 0, name: GeForce GT 640, pci bus id: 0000:05:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:843] Ignoring gpu device (device: 0, name: GeForce GT 640, pci bus id: 0000:05:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:843] Ignoring gpu device (device: 0, name: GeForce GT 640, pci bus id: 0000:05:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:843] Ignoring gpu device (device: 0, name: GeForce GT 640, pci bus id: 0000:05:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:843] Ignoring gpu device (device: 0, name: GeForce GT 640, pci bus id: 0000:05:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:843] Ignoring gpu device (device: 0, name: GeForce GT 640, pci bus id: 0000:05:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
	F tensorflow/cc/tutorials/example_trainer.cc:128] Check failed: ::tensorflow::Status::OK() == (session->Run({{"x", x}}, {"y:0", "y_normalized:0"}, {}, &outputs)) (OK vs. Invalid argument: Cannot assign a device to node 'Cast': Could not satisfy explicit device specification '/gpu:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
		 [[Node: Cast = Cast[DstT=DT_FLOAT, SrcT=DT_INT32, _device="/gpu:0"](Const)]])
	F tensorflow/cc/tutorials/example_trainer.cc:128] Check failed: ::tensorflow::Status::OK() == (session->Run({{"x", x}}, {"y:0", "y_normalized:0"}, {}, &outputs)) (OK vs. Invalid argument: Cannot assign a device to node 'Cast': Could not satisfy explicit device specification '/gpu:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
		 [[Node: Cast = Cast[DstT=DT_FLOAT, SrcT=DT_INT32, _device="/gpu:0"](Const)]])
	F tensorflow/cc/tutorials/example_trainer.cc:128] Check failed: ::tensorflow::Status::OK() == (session->Run({{"x", x}}, {"y:0", "y_normalized:0"}, {}, &outputs)) (OK vs. Invalid argument: Cannot assign a device to node 'Cast': Could not satisfy explicit device specification '/gpu:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
		 [[Node: Cast = Cast[DstT=DT_FLOAT, SrcT=DT_INT32, _device="/gpu:0"](Const)]])
	F tensorflow/cc/tutorials/example_trainer.cc:128] Check failed: ::tensorflow::Status::OK() == (session->Run({{"x", x}}, {"y:0", "y_normalized:0"}, {}, &outputs)) (OK vs. Invalid argument: Cannot assign a device to node 'Cast': Could not satisfy explicit device specification '/gpu:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
		 [[Node: Cast = Cast[DstT=DT_FLOAT, SrcT=DT_INT32, _device="/gpu:0"](Const)]])
	Aborted (core dumped)

Will I need a different gpu to run this?

**Comment by poxvoculi** [comment]
Officially you need a GPU with compute level >= 3.5, but see
https://github.com/tensorflow/tensorflow/issues/25

**Comment by YerongLi** [comment]
@petamem Hi, I am trying to fix a similar issue here. Could you help me figure out how to "a new 4.5.3 kernel with NUMA support"? (T_T)

I am runing tensorflow on Jetson TX1 and **sess=tf.Session()** gives me **NUMA** error on both python 2.7 and python 3.5.
```
>>> import tensorflow as tf
>>> sess = tf.Session()
2017-12-30 01:13:41.421430: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:857] ARM64 does not support NUMA - returning NUMA node zero
2017-12-30 01:13:41.421551: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: NVIDIA Tegra X1
major: 5 minor: 3 memoryClockRate (GHz) 0.9984
pciBusID 0000:00:00.0
Total memory: 3.89GiB
Free memory: 365.80MiB
2017-12-30 01:13:41.421603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-12-30 01:13:41.421631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-12-30 01:13:41.421671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0)
```
I followed build on this repo: [https://github.com/jetsonhacks/installTensorFlowTX1](https://github.com/jetsonhacks/installTensorFlowTX1).

**Comment by Kongsea** [comment]
@petamem Could you please share with us how to do this? Thank you.
- `I will now switch back to Hybrid mode (activate the Intel GPU) and test if that works with NUMA enabled.`

**Comment by bubbelMCU** [comment]
When I run into the numa=-1 error, installing this package helped me.

 ```sudo apt install numactl ```

Ubuntu 18.04

**Comment by Pizzanomicon** [comment]
@petamem - I'm afraid I don't quite understand.  Suffering the same problem with a Titan GTX/Tensorflow 1.14 (Compute capability 3.5) - I'd compiled this myself rather painstakingly.  How did you do:

> So I compiled a new 4.5.3 kernel with NUMA support and ...
4.5.3 kernel of what, and how?  Thank you!

**Comment by goog** [comment]
tensorflow 1.9 will return 0, do not fail

**Comment by engrmz** [comment]
Hi all,
I am stuck in the same error. I am working with tensorflow. If you found any solution, kindly share. Thanks

`successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`

**Comment by 17-Jarvis** [comment]
> Hi all, I am stuck in the same error. I am working with tensorflow. If you found any solution, kindly share. Thanks
> 
> `successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`

refer this link https://gist.github.com/zrruziev/b93e1292bf2ee39284f834ec7397ee9f
