### ISSUE TITLE
Unable to build Tensorflow on Windows 8

### ISSUE THREAD

**Issue by imrsayyed29** [tensorflow/tensorflow#22647]
I am not able to build Tensorflow on windows 8 using the following command.

bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

Tensorflow 1.7 
Cuda 9.0

1 error detected in the compilation of "C:/Users/imrans/AppData/Local/Temp/nvcc_inter_files_tmp_dir/gru_ops_gpu.cu.compute_70.cpp1.ii".
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 985.757s, Critical Path: 177.12s
INFO: 466 processes: 466 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment]
@imrsayyed29 Please complete the template so we can better help you.

**Comment by wt-huang** [comment]
@imrsayyed29 Please find build configurations for TensorFlow [here](https://www.tensorflow.org/install/source_windows). Please upgrade to Windows 10 and use the latest TensorFlow version 1.11.0.

**Comment by wt-huang** [comment]
This should work on Windows 10, feel free to reopen if any issue comes up.
