### ISSUE TITLE
Problem with CUDA 10 and Tensorflow 1.11

### ISSUE THREAD

**Issue by Serge9744** [tensorflow/tensorflow#22645]
Hello,

I have Windows 10 , a Geforce 1060 6GB and I have installed CUDA 10. What I would like is to use tensorflow gpu for deep learning purposes. I have installed tensorflow-gpu 1.11

I installed some C++ compilers in Microsoft Visual basic 2017 prior to CUDA 10 installation.
I tried CUDA which was compatible with the graphic card but not CUDA 9. 
Then , I copied the cudnn 7.3.1 (latest) .dll into the bin located in CUDA/bin.

Problem is..tensorflow doesn't still recognize my GPU (recognize only the CPU but printed "CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2").

Version of keras 2.2 are still not compatible with tensorflow 1.11.

I checked te version of CUDA and it worked ,it is the 10 version printed out.

However I tried the C++ compiling tests (I tried to compile the bandwidth project in Microsoft Visual Studio loacted in CUDA Samples ) but it seemed to fail.

Can someone help me please , I am a bit desperate !

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by Serge9744** [comment]
Hello,

Here is the filled template:

OS Platform and Distribution : Windows 10

TensorFlow installed from : Conda

TensorFlow version :    1.11

Bazel version: NA

CUDA/cuDNN version : v10

GPU model and memory : Geforce 1060 6B Max-Q

Exact command to reproduce : 
-Microsoft Visual studio 2017 installation : C++ complier box checked
-CUDA 10 installation : all ok , version is good
-CUDNN version for CUDA 10 . .dll placed in the bin of NVIDIA Toolkits/CUDA/v10/bin
-pip install tensorflow-gpu
And it still doesn't see my GPU
I clicked on "repair" in Microsoft Visual Studio 2017 to try but it still doesn't see it.
When i do nvidia-smi in the Windows command , it says either it doesn't work or my GPU isn't in WDDM mode. I don't understand that...

I also tried to install cuda and cudnn via     "conda -c install tensorflow-gpu"   in the conda prompt , it installed  automatically cuda toolkit v9 directly and cudnn version accordingly (so , without installing manually CUDA) in the python libraries but not in C:\Program... and not in the environment variable  . But it still doesn't work.

I tried to install CUDA v9 manually but the installation said that my system is incompatible as my gpu muight be newer than the version of CUDA (which is surprising) , and therefore I could not use CUDA fully.

Mobile device: NA

**Comment by adampl** [comment]
TensorFlow requires CUDA 9.0 according to: https://www.tensorflow.org/install/gpu

**Comment by gunan** [comment]
Just like @adampl shared, prebuilt binaries for TF on pypi use CUDA 9.0
the binaries you installed from conda are supported by the anaconda community, we have no documentation on those.

For using TF with cuda 10, you have to build it from sources yourself. Here is the documentation for that:
https://www.tensorflow.org/install/source_windows
