### ISSUE TITLE
Is there some way to decode bytes string back to unicode which is decoded using string.encode('utf-8') in tensorflow pipline.

### ISSUE THREAD

**Issue by lifeisshubh** [tensorflow/tensorflow#22644]
I am using tfRecord for storing my data. I have a Hindi text which is basically Unicode text and to convert it into bytes I have encoded into using string.encode('utf-8').
At the time of taking out data using tensorflow dataset API, I am facing trouble in getting my data in original form, Since I did not find any working method that could convert my byte string back to Unicode string.
I have Tried 
`tf.compat.as_text(
    byte_tensor,
    encoding='utf-8'
)`
also, raw_decode which should not work and it definitely not worked. Though I can convert my text back to original using string.decode('utf-8') by taking data out of the graph. But definitely, I don't want to do that since it will defeat the whole purpose and make my operation slow.
Can anyone suggest any functionality that could help in this matter?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by Ceceu** [comment]
@lifeisshubh did you find a solution? I have this same need.

**Comment by lifeisshubh** [comment]
In my case i have encode the data i have in alphanumeric form.
