### ISSUE TITLE
CentOS 6.7 Compilation Issue at HEAD

### ISSUE THREAD

**Issue by rdipietro** [tensorflow/tensorflow#2266]
CentOS 6.7
Cuda 7.0
cuDNN 6.5

I previously got TensorFlow 7.x to compile with an older version of Bazel (1.x), but this fails with HEAD, and it also fails if I use Bazel 0.2.0 as suggested in other issues.

Bazel 0.2.0 builds fine.

Keeping with what worked before, I run
```
export EXTRA_BAZEL_ARGS='-s --verbose_failures --ignore_unsupported_sandboxing --genrule_strategy=standalone --spawn_strategy=standalone --jobs 8'

bazel build -c opt --config=cuda --linkopt '-lrt' --copt="-DGPR_BACKWARDS_COMPATIBILITY_MODE" --conlyopt="-std=c99" //tensorflow/tools/pip_package:build_pip_package
```

Here is the error I now get. Any ideas? Please note that python2.7 is in my path, and /usr/bin/env python2.7 opens an interpreter with no problem.

Thanks.

```
ERROR: /home-4/rdipiet2@jhu.edu/install/tensorflow/google/protobuf/BUILD:520:1: Linking of rule '//google/protobuf:internal/_api_implementation.so' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home-4/rdipiet2@jhu.edu/.cache/bazel/_bazel_rdipiet2@jhu.edu/549db212089e33b4d213773753834e47/tensorflow && \
  exec env - \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -shared -o bazel-out/local_linux-opt/bin/google/protobuf/internal/_api_implementation.so -Wl,-whole-archive bazel-out/local_linux-opt/bin/google/protobuf/_objs/internal/_api_implementation.so/google/protobuf/python/google/protobuf/internal/api_implementation.pic.o -Wl,-no-whole-archive -Wl,-R/cm/shared/apps/gcc/4.8.2/lib64 -lstdc++ -B/usr/bin/ -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,--gc-sections -lrt): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home-4/rdipiet2@jhu.edu/.cache/bazel/_bazel_rdipiet2@jhu.edu/549db212089e33b4d213773753834e47/tensorflow && \
  exec env - \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -shared -o bazel-out/local_linux-opt/bin/google/protobuf/internal/_api_implementation.so -Wl,-whole-archive bazel-out/local_linux-opt/bin/google/protobuf/_objs/internal/_api_implementation.so/google/protobuf/python/google/protobuf/internal/api_implementation.pic.o -Wl,-no-whole-archive -Wl,-R/cm/shared/apps/gcc/4.8.2/lib64 -lstdc++ -B/usr/bin/ -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,--gc-sections -lrt): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127.
/usr/bin/env: python2.7: No such file or directory
```

**Comment by zheng-xq** [comment]
Could you pass the absolute path to your python, such as? 

/usr/bin/python

**Comment by rdipietro** [comment]
Thanks for the quick response. It's `/cm/shared/apps/anaconda/2.7.10/bin/python`.

**Comment by rdipietro** [comment]
Any ideas about why this wouldn't be picked up?

**Comment by zheng-xq** [comment]
The error message is from the first line here: 

#!/usr/bin/env python2.7
https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc

Could you confirm that you are running bash? And if you start from your bash shell, if you run the displayed command line from "bazel", you would pass the first line? 

If so, it could be possible that the new bazel is running a more restricted bash and however you put python2.7 on env didn't get picked up. If that is indeed the case, it would be better solved if you file a bazel issue directly. 

https://github.com/bazelbuild/bazel

**Comment by rdipietro** [comment]
I think you're right. I'll file a bazel issue along with other lost dependencies after I get it to successfully compile.
