### ISSUE TITLE
Build Fail : Build using MSbuild to create whl file (pip package)

### ISSUE THREAD

**Issue by imrsayyed29** [tensorflow/tensorflow#22667]
I am trying to build Tenserflow following these steps:

https://www.python36.com/install-tensorflow-gpu-windows/

I am on Step 10

Build using MSbuild to create whl file (pip package) using the following command:

**MSBuild /p:Configuration=Release /verbosity:detailed tf_python_build_pip_package.vcxproj**

I am getting following error and build is failing can anyone help?

----------------------------------------------------------------------------------
Done executing task "Touch".
Done building target "FinalizeBuildStatus" in project "tf_python_copy_scripts_to_destination.vcxproj".
Target "Build" in file "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.BuildSteps.Targets" from project "C:\tensorflow\tensorflow\c
ontrib\cmake\build\tf_python_copy_scripts_to_destination.vcxproj" (entry point):
Done building target "Build" in project "tf_python_copy_scripts_to_destination.vcxproj".
Done Building Project "C:\tensorflow\tensorflow\contrib\cmake\build\tf_python_copy_scripts_to_destination.vcxproj" (default targets).

Done executing task "MSBuild" -- FAILED.
Done building target "ResolveProjectReferences" in project "tf_python_build_pip_package.vcxproj" -- FAILED.
Done Building Project "c:\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default targets) -- FAILED.

Build FAILED.

"c:\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (default target) (3) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal_static.vcxproj" (default target) (4) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\tf_c.vcxproj" (default target) (5) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\tf_cc_framework.vcxproj" (default target) (6) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\tf_core_framework.vcxproj" (default target) (7) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\proto_text.vcxproj" (default target) (8) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\grpc.vcxproj" (default target) (9) ->
(CustomBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\tensorf
low\tensorflow\contrib\cmake\build\grpc.vcxproj]

    0 Warning(s)
    1 Error(s)
----------------------------------------------------------------------------------

### System information
- **OS Platform and Distribution**: **Windows 8**
- **TensorFlow installed from (source or binary)**: **Source**
- **TensorFlow version (use command below)**: **1.5**
- **Python version**: **3.6**
- **Bazel version (if compiling from source)**: **N/A**
- **GCC/Compiler version (if compiling from source)**:**N/A**
- **CUDA/cuDNN version**: **9.1/7**
- **GPU model and memory**:**N/A**
- **Mobile Device**:**N/A**
- **Exact command to reproduce**: **MSBuild /p:Configuration=Release /verbosity:detailed tf_python_build_pip_package.vcxproj**

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Mobile device

**Comment by imrsayyed29** [comment]
Hello,

Follwing are the details:

System information
OS Platform and Distribution: **Windows 8**
TensorFlow installed from (source or binary): **Source**
TensorFlow version (use command below): **1.5**
Python version: **3.6**
Bazel version (if compiling from source): **N/A**
GCC/Compiler version (if compiling from source): **N/A**
CUDA/cuDNN version: **9.1/7**
GPU model and memory: **N/A**
Mobile device: **N/A**
Exact command to reproduce: **MSBuild /p:Configuration=Release /verbosity:detailed tf_python_build_pip_package.vcxproj**

Thanks

**Comment by harshini-gadige** [comment]
@imrsayyed29 Hi, can you provide information for this field.

GPU model and memory:

**Comment by gunan** [comment]
CMake support is dropped, please see the bazel instructions here:
https://www.tensorflow.org/install/source_windows

Moreover, for support with such 3rd party resources, please contact their authors.
