### ISSUE TITLE
Toco outdated in docker build

### ISSUE THREAD

**Issue by redbeard-the-coder** [tensorflow/tensorflow#22673]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: docker
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: n/a
- **TensorFlow installed from (source or binary)**: docker
- **TensorFlow version (use command below)**: latest-gpu-py3
- **Python version**: python3
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: 
- **GPU model and memory**:
- **Exact command to reproduce**: toco

### Describe the problem
Attempting to convert TF graph to TF-lite using the latest stable GPU Python3 docker image. Commands (shown below) differ from those shown in documentation [here](https://www.tensorflow.org/lite/devguide). Additionally, toco conversion of graph throws errors about unsupported operations Fill, Unpack, and MeanSquaredDifference. 

Downloading the latest bazel in the docker container and rebuilding toco from source gives a clearly different version.

### Source code / logs

```
usage: toco [-h] --output_file OUTPUT_FILE
            (--graph_def_file GRAPH_DEF_FILE | --saved_model_dir SAVED_MODEL_DIR | --keras_model_file KERAS_MODEL_FILE)
            [--output_format {TFLITE,GRAPHVIZ_DOT}] [--inference_type {FLOAT,QUANTIZED_UINT8}]
            [--inference_input_type {FLOAT,QUANTIZED_UINT8}] [--input_arrays INPUT_ARRAYS] [--input_shapes INPUT_SHAPES]
            [--output_arrays OUTPUT_ARRAYS] [--saved_model_tag_set SAVED_MODEL_TAG_SET]
            [--saved_model_signature_key SAVED_MODEL_SIGNATURE_KEY] [--std_dev_values STD_DEV_VALUES]
            [--mean_values MEAN_VALUES] [--default_ranges_min DEFAULT_RANGES_MIN]
            [--default_ranges_max DEFAULT_RANGES_MAX] [--quantize_weights QUANTIZE_WEIGHTS] [--drop_control_dependency]
            [--reorder_across_fake_quant] [--change_concat_input_ranges] [--allow_custom_ops]
            [--dump_graphviz_dir DUMP_GRAPHVIZ_DIR] [--dump_graphviz_video]
```

**Comment by wt-huang** [comment]
@redbeard-the-coder Thanks for catching and reporting this.

**Comment by MarkDaoust** [comment]
The dock seems to contain the newer version.

When I check the toco help in the various docker containers I get the new help on all of them.

I think maybe you just forgot to do a docker pull. Try that and re-open if it doesn't work.
