### ISSUE TITLE
tensorflow.python.data.ops.dataset_ops.DatasetSource

### ISSUE THREAD

**Issue by feihugis** [tensorflow/tensorflow#22681]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source 
- **TensorFlow version (use command below)**: 1.11
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.16
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
The abstract class [DatasetSource](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/dataset_ops.py#L1496) is defined for representing a dataset with no inputs. The datasets (e.g. [CsvDataset](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/experimental/ops/readers.py#L513)) defined under `tensorflow/python/data/experimental/ops/readers.py` are inherited from `DatasetSource`, but these three [FixedLengthRecordDataset](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/readers.py#L250), [TextLineDataset](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/readers.py#L35), and [TFRecordDataset](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/readers.py#L80) in `tensorflow/python/data/ops/readers.py` are herited from [Dataset](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/dataset_ops.py#L53). In my understanding, they also need to be inherited from `DatasetSource`. If my understanding is right, I would like to submit a PR to update them.

**Comment by feihugis** [comment]
@jsimsa Could you have a look at this issue?

**Comment by jsimsa** [comment]
SGTM

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.
