### ISSUE TITLE
r1.11 failed to build on debian

### ISSUE THREAD

**Issue by theedge456** [tensorflow/tensorflow#22694]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:debian stretch
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:r1.11
- **Python version**:2.7.13
- **Bazel version (if compiling from source)**:0.17.2
- **GCC/Compiler version (if compiling from source)**:6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
- **CUDA/cuDNN version**:N/A
- **GPU model and memory**: radeon RV370 256Mo
- CPU : Ryzen 5-1600 with 8Gb
- **Exact command to reproduce**: bazel build //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
compilation fails.
Is there a specific version of protobuf to use  ?

### Source code / logs
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded).
INFO: Found 1 target...
ERROR: /media/travail/tensorflow/tensorflow/contrib/tensorrt/BUILD:124:1: Executing genrule //tensorflow/contrib/tensorrt:trt_engine_op_pygenrule failed (Exit 127)
bazel-out/host/bin/tensorflow/contrib/tensorrt/gen_trt_engine_op_py_wrappers_cc: symbol lookup error: bazel-out/host/bin/tensorflow/contrib/tensorrt/gen_trt_engine_op_py_wrappers_cc: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 231.846s, Critical Path: 52.14s
INFO: 38 processes: 38 local.
FAILED: Build did NOT complete successfully

**Comment by SummerLife** [comment]
Hi, did you solve this problem? And would you like to tell me the way you solve it?

**Comment by theedge456** [comment]
No. Fortunately, I have an r1.8 as a rescue.

**Comment by freedomtan** [comment]
install keras_applications  and other pip wheels should help, see https://github.com/tensorflow/tensorflow/issues/21518

**Comment by gunan** [comment]
When building from sources, it will download and build its own protobuf.
Are you trying to build with GPU support?

**Comment by theedge456** [comment]
I installed protobuf from sources. I'll try without it to see how it goes.
I enabled OpenCL with trisyscl support.

**Comment by gunan** [comment]
We have not looked into building with trisycl at all. That is a configuration supported purely by the community.
I am guessing the issue is isolated to that build configuration.

**Comment by mohantym** [comment]
Hi @theedge456 !We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!
