### ISSUE TITLE
Compute capability < 3.5

### ISSUE THREAD

**Issue by marker68** [tensorflow/tensorflow#227]
I have a little bit old GPU card with compute capability 2.0 (GeForce GTX 560).
Is there a way to get TensorFlow work with this card?

**Comment by vrv** [comment]
If you're comfortable building from source, https://github.com/tensorflow/tensorflow/issues/25#issuecomment-156234658 should have an answer for you, though we haven't tested it on anything below 3.0.

Will de-dupe this bug with that one, thanks!

**Comment by Huxwell** [comment]
@marker68 I know 2 years have passed, but did you finally managed to get it running?
I just got myself 5x Tesla m2075 6GB VRAM and wonder if I can do anything productive with it in terms of deep learning.

**Comment by abysmalocean** [comment]
I also have the same card, 2.0 computational capacity, looking for a solution.

**Comment by abdelouahabb** [comment]
I have 2.1 , it is only after downloading everything that  I go this :( I hope there will be a build for this (Windows)

**Comment by artus9033** [comment]
You can have a look at [this](https://github.com/tensorflow/models/issues/1695), but what I got were errors  during attempt to obtain memory buffer size, which ended in an InternalError
