### ISSUE TITLE
[Cloud TPU] `dot` with non-standard layout operands produces incorrect output

### ISSUE THREAD

**Issue by Keno** [tensorflow/tensorflow#22709]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: r1.11
- **Python version**: N/A
- **Bazel version (if compiling from source)**: 0.16.1
- **GCC/Compiler version (if compiling from source)**: 7.2.0
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem

We are seeing incorrect answers from VGG19 from Cloud TPUs using the Julia frontend (VGG19 source here: https://github.com/FluxML/Metalhead.jl/blob/master/src/vgg19.jl). The Julia frontend generates XLA and submits it to the Cloud TPU using xrt. Reducing the test case, we find that there seems to be a problem with the `dot` operation when operating on arrays of non-standard data layout (julia is column major by default so tends to encounter this more, although the Julia->XLA compiler pass heuristically changes the layout of inputs/outputs when targeting TPUs to avoid padding if profitable). Example output showing the problem:

```
julia> W′′ = XRTArray(sess, W′)
10×10 XRTArray{Float32,(10, 10),2}:
  0.0117621   -0.0111235    0.0105805   -0.00403011   -0.00355716  -0.00718089  -0.0134884    -0.00459831    0.0197616    -0.00417151
 -0.00695795  -0.00393374   0.0090458   -0.00566363    0.0121302    0.00420088  -0.00750095    0.000967382   0.0220296     0.00428639
 -0.00687687  -0.00229628  -0.007712    -0.00997357   -0.00680831   0.00262956   0.000473469  -0.00876678   -0.011446     -0.00720634
  0.00530032   0.00782367  -0.00427682   0.00691867   -0.00343559   0.00912634  -0.0111816    -0.00729117    0.00522226   -0.00822838
 -0.00600947  -0.00683288  -0.0122932    0.000471149  -0.00142788   0.0201943    0.000141306   0.0052818     0.00387177   -0.00254829
  0.00345886   0.0106005   -3.07181e-5   0.0217212     0.00135223  -0.00411474   0.00345068   -0.00515104    0.00140949   -0.0132586
 -0.00233608  -0.0117845   -0.00938103   0.0190475    -0.00731929  -0.00104086  -0.0144478     0.00959422    0.00774611   -0.00810476
 -0.00620138  -0.00673539  -0.00782188   0.00821768    0.00439068   0.00334791  -0.00190924   -0.00682392   -0.00805664    0.0150204
 -0.00116647  -0.00305227   0.00475127   9.85245e-7    0.0024828    0.013036     0.00340338   -0.00387893    0.000677002   0.00680005
 -0.00499851   0.0115887   -0.00762315   0.0148181     0.0112692    0.00543651   0.0137934    -0.00666574    0.00736139    0.00202298

julia> x′′ = XRTArray(sess, x′)
10×1 XRTArray{Float32,(10, 1),2}:
 0.0
 6.706906
 0.0
 0.0
 2.0117874
 0.0
 0.0
 0.0
 0.0
 0.0

julia> W′′ * x′′
10×1 XRTArray{Float32,(10, 1),2}:
 -0.081760176
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
```

The first value is correct, the rest of them are not (however I do believe I've seen cases where the first value was incorrect but non-zero also) - for python folks remember that `*` is matrix multiply in Julia. Dumping the XLA generated during the above session, we get:

```
ENTRY comp {
  comp0_parameter0 = f32[10,10]{0,1} parameter(0)
  comp0_parameter1 = f32[10,1]{0,1} parameter(1)
  ROOT comp0_dot3 = f32[10,1]{0,1} dot(comp0_parameter0, comp0_parameter1), lhs_contracting_dims={1}, rhs_contracting_dims={0}
}
```

Notice in particular the layout being `{0,1}` rather than the standard `{1,0}`. If I change the above mentioned layout heuristic to prefer the XLA standard layout, the issue disappears. The issue also disappears if the RHS is a plain vector, i.e. `f32[10]{0}` rather than `f32[10,1]{0,1}`. Further note that this issue was reduced from a case where the `dot` was not the final operation, but the zeros it generated nonetheless propagated. To me that would indicate that the output values are being written to the wrong place by the `dot` operation (as opposed to being a problem with the way that xrt retrieves the data from the device for example).

@michaelisard remarked that this sounded like a padding issue.
cc @eliben

**Comment by Keno** [comment]
Yes, as I mentioned, things work fine with the standard layout. However, we are using non-standard layout for memory efficiency to avoid excessive padding on the TPU, so changing all layout is not feasible.

**Comment by Keno** [comment]
However, if you have an internal reproducer already, maybe you can share that with @meheffernan and @michaelisard who were planning to look into this.

**Comment by michaelisard** [comment]
This is now verified fixed at the current version though not pushed to a public release yet, so closing.
