### ISSUE TITLE
tf.while_loop 

### ISSUE THREAD

**Issue by nairouz** [tensorflow/tensorflow#22701]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Colab
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: Colab
- **TensorFlow installed from (source or binary)**: Colab
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: Colab
- **GCC/Compiler version (if compiling from source)**: Colab
- **CUDA/cuDNN version**: Colab
- **GPU model and memory**: Colab
- **Exact command to reproduce**: Colab

### Describe the problem
The `tf.while_loop` no longer works. I have also checked the code from the official [documentation](https://www.tensorflow.org/api_docs/python/tf/while_loop).
I ran away from the eager mode issues and I found myself writing nonsense code:
`tf.cond`
`tf.while_loop`
`tf.Print`
`tf.gather`
`tf.scatter_update`

At the end of the day, nothing works properly neither the graph mode nor the eager one.

### Source code
```
import tensorflow as tf

n = 10000
x = tf.constant(list(range(n)))
c = lambda i, x: i < n
b = lambda i, x: (tf.Print(i + 1, [i]), tf.Print(x + 1, [i], "x:"))
i, out = tf.while_loop(c, b, (0, x))
with tf.Session() as sess:
    print(sess.run(i))  # prints [0] ... [9999]

    # The following line may increment the counter and x in parallel.
    # The counter thread may get ahead of the other thread, but not the
    # other way around. So you may see things like
    # [9996] x:[9987]
    # meaning that the counter thread is on iteration 9996,
    # while the other thread is on iteration 9987
    print(sess.run(out).shape)
```

### logs
InvalidArgumentErrorTraceback (most recent call last)
<ipython-input-21-a546eb31055a> in <module>()
      7 i, out = tf.while_loop(c, b, (0, x))
      8 with tf.Session() as sess:
----> 9     print(sess.run(i))  # prints [0] ... [9999]
     10 
     11     # The following line may increment the counter and x in parallel.

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    885     try:
    886       result = self._run(None, fetches, feed_dict, options_ptr,
--> 887                          run_metadata_ptr)
    888       if run_metadata:
    889         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1108     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1109       results = self._do_run(handle, final_targets, final_fetches,
-> 1110                              feed_dict_tensor, options, run_metadata)
   1111     else:
   1112       results = []

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1284     if handle is None:
   1285       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1286                            run_metadata)
   1287     else:
   1288       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1306           self._config.experimental.client_handles_error_formatting):
   1307         message = error_interpolation.interpolate(message, self._graph)
-> 1308       raise type(e)(node_def, op, message)
   1309 
   1310   def _extend_graph(self):

InvalidArgumentError: Input 1 of node while/Merge_3 was passed float from while/NextIteration_3:0 incompatible with expected int32.

**Comment by nairouz** [comment]
@martinwicke are you sure that the version 1.11 is a stable one?

**Comment by nairouz** [comment]
I am really disappointed. Lots and lots of bugs.

**Comment by ppwwyyxx** [comment]
![1003-15 04 34](https://user-images.githubusercontent.com/1381301/46442207-ade14200-c71d-11e8-914a-e51e6263ab5a.png)

Opened a colab and runs your code. It works just fine.

**Comment by nairouz** [comment]
How come?
![image](https://user-images.githubusercontent.com/10966954/46442736-f70bb300-c76a-11e8-92c8-538e2b14647b.png)
