### ISSUE TITLE
Sudden slowdowns due to the TLB shootdowns

### ISSUE THREAD

**Issue by ivankreso** [tensorflow/tensorflow#2271]
### Environment info
Operating System: Arch Linux

Installed version of CUDA and cuDNN: CUDA 7.5, CUDNN v4
If installed from binary pip package, provide:

1. Which pip package you installed: https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl
2. The output from python -c "import tensorflow; print(tensorflow.__version__)": 0.8.0

### Steps to reproduce
I am experiencing slowdowns due to some problem with memory caching. My system has 32GB of RAM. I am training a CNN on one large image dataset. During training at some point almost 100% of memory is cached which is expected when working with a large dataset. But then soon after TF starts to experience slowdowns (3-5x slower execution per batch). I used netdata and observed that the slowdowns are accompanied by a sudden huge spikes in TLB shootdowns. I found a way how to fix a problem from outside, the slowdowns disappear for quite some time if I just clear all the cached memory like this:
```
$ free && sync && echo 3 > /proc/sys/vm/drop_caches && free
              total        used        free      shared  buff/cache   available
Mem:       32825492     3454324      209124      638072    29162044    28463116
              total        used        free      shared  buff/cache   available
Mem:       32825492     3455692    28603760      637636      766040    28476376

```
Then later when memory is fully cached again they reappear. First row is the state at which the slowdown is happening. You can see that most memory is cached and I am actually using only around 10% of RAM.
Does anyone have an idea what could cause these TLB shootdowns or what can I do to find out more about what is going on?

**Comment by kadrach** [comment]
Facing the same issue here, dropping caches via sysctl fixes it temporarily.

This is with current tensorflow@9078909131d5e91e8bd1878eac54136885656043 on a ec2 g2.2xlarge running Xenial.

**Comment by girving** [comment]
@rmlarsen: Any guesses as to what's going on?

**Comment by ivankreso** [comment]
I forgot to mention that I am using tf.train.batch for data fetching, defined like this:
```
  with tf.name_scope('input'), tf.device('/cpu:0'):
    filename_queue = tf.train.string_input_producer(dataset.get_filenames(),
        num_epochs=num_epochs, shuffle=shuffle, capacity=dataset.num_examples())
    
    image, labels, weights, num_labels, img_name = read_and_decode(filename_queue)

    image, labels, weights, num_labels, img_name = tf.train.batch(
        [image, labels, weights, num_labels, img_name], batch_size=FLAGS.batch_size, num_threads=2,
        capacity=64)
```

**Comment by dvyukov** [comment]
Is it TLB misses or page faults? Page cache should cause page faults.
What process does trigger the faults?
You can check it with `perf record -a -g -e faults`, then ctrl+C after 10 seconds, then `perf report`.
Does the tf program read any files? Is it possible that some other process constantly reads something from the disk?

**Comment by rmlarsen** [comment]
@ivankreso Did you make any progress on investigating this further?

**Comment by ivankreso** [comment]
@rmlarsen No, I am currently running experiments on a smaller dataset which fits into memory. I will have free time on my machine over the weekend or during next week and then I can try to reproduce the problem again on the newest TF version. I will then post any new observations and the report from perf record logs here.
@dvyukov Thanks for good suggestion!

**Comment by ivankreso** [comment]
I build the newest TF version from master and the problem doesn't appear anymore.
Closing the issue. If it reappears i will post the new info here.

**Comment by chenchao666** [comment]
> I build the newest TF version from master and the problem doesn't appear anymore.
> Closing the issue. If it reappears i will post the new info here.

I came across the same problem as you, do you know how to solve it now. I use tf 1.9.0
