### ISSUE TITLE
How should we use the script tf_upgrade?

### ISSUE THREAD

**Issue by nbro** [tensorflow/tensorflow#22724]
I would like to use the [tf_upgrade](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/compatibility/tf_upgrade.py) script. However, of course, I cannot simply copy it to the directory which contains the file whose code I want to upgrade, because that script contains an import `from tensorflow.tools.compatibility import ast_edits` and, if I execute that script using `python tf_upgrade.py --infile main.py --outfile main-upgraded.py`, I get the error

```
Traceback (most recent call last):
  File "tf_upgrade.py", line 23, in <module>
    from tensorflow.tools.compatibility import ast_edits
ImportError: No module named compatibility
````

In fact, `compatibility` is not a module of `tools`. So, how exactly are we supposed to use the `tf_upgrade` script? The documentation or README me of https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility should be updated so that this info is present.

In a few posts on the web, it's written that we are simply supposed to copy that script, but this is not true (at least, not anymore).

I'm using Python 2.7 and TensorFlow 1.11.0 on a Mac OS X 10.13.6 (High Sierra).

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment]
Closing this, feel free to reopen if any additional questions.

**Comment by nbro** [comment]
@wt-huang So, do we need to download the whole directory? Or do we need to go to the `compatibility` folder under my TF installation directory? It's not clear. There should be a step-by-step clear an unambiguous explanation on how to use that script.

**Comment by wt-huang** [comment]
@nbro You can follow the steps I described above to use `tf_upgrade.py`, assuming you already have TensorFlow installed on your system.

**Comment by nbro** [comment]
@wt-huang Your steps above are ambigous, that's why I complained above. What do you mean by "go to directory tree then replace"? Do you mean in my TF installation? Or do I need to download that `compatibility` folder only and do what you suggested there?

Btw, why would we need to modify any import? Why the guys that created that script made it in such a way that the script is just runnable?

**Comment by wt-huang** [comment]
@nbro The `compatibility` folder should already be in your system if TensorFlow is installed properly. Follow the [installation guide](https://www.tensorflow.org/install/) if haven't done so. I don't see issue template filled out so no idea which system you are using. Regardless you should be able to issue the command I mentioned above without getting any error.

**Comment by nbro** [comment]
@wt-huang Anyway, maybe should have suggested a more mnemonic command instead of `python tf_upgrade.py --infile renames_v2.py --outfile foo-upgraded.py`; you could have suggested e.g. `python tf_upgrade.py --infile path_to_your_file_to_upgrade.py --outfile path_to_upgraded_file_produced_by_script.py`. 

Also, I haven't tried yet your suggestion, but why would we need to change any import? Is this script supposed to be used in any other way than from the command line? If yes, then maybe two scripts could have been used to solve this problem of needing to change imports.
