### ISSUE TITLE
Enable USE_CBLAS_GEMM for Conv ops in C++ API

### ISSUE THREAD

**Issue by hagerrady13** [tensorflow/tensorflow#22721]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from**: using bazel
- **TensorFlow version**: 1.10
- **Bazel version**: 0.17.2
- **Have I written custom code**: No
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: bazel run -c opt //tensorflow/example/example:example --define USE_CBLAS_GEMM=true
- **Mobile device**: N/A

### Describe the problem:
TF is not built from source, I am just configuring a specific example. So I am doing inference on TF C++ convolution layers, using bazel. I added 'USE_CBLAS_GEMM' and 'USE_GEMM_FOR_CONV' into the config setting of the build file.

```
config_setting(
    name = "cblas",
    values = {
        "define": "USE_CBLAS_GEMM=1",
    },
)
```
For running, 
```
bazel run -c opt //tensorflow/example/example:conv2d --define USE_CBLAS_GEMM=true
```

But the flag is not enabled and I cannot find a way to make sure whether CBLAS is running or not.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment]
@hagerrady13 It is stated in System Information that TensorFlow is installed from source, but in Description it is stated otherwise. Which one is correct? If installing TensorFlow with bazel, you can add `-DEIGEN_USE_BLAS ` to `bazel build` command.

To check whether CBLAS_GEMM is applied you can use:

```
np.__config__.show()
```

**Comment by hagerrady13** [comment]
@wt-huang TF is is installed with Bazel, I edited the description. I tried to add ``` -DEIGEN_USE_BLAS ``` to the build command as you suggested but it gives the following:
``` ERROR: Invalid options syntax: -DEIGEN_USE_BLAS ```

Any help?

**Comment by wt-huang** [comment]
@hagerrady13 If you already have TensorFlow installed with Bazel, no need to use `-DEIGEN_USE_BLAS.` Just type `np.__config__.show()` in jupyter notebook, your will get an output containing `cblas` in the list of libraries.

**Comment by wt-huang** [comment]
Closing, feel free to reopen if problem persists.
