### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.engine.base_layer' has no attribute 'Layer'

### ISSUE THREAD

**Issue by bleedingfight** [tensorflow/tensorflow#22739]
# I just update my keras so my tensorflow update from 1.7 update 1.9
but I found that tensorflow can't work,I just run `from tensorflow as tf`,the error show as title.My system just following with:
- ubuntu16.0.4 64bit
- gtx980m 8G
- intel i7 6820hk
- cuDNN7
- CUDA 9.0
I just tried that conda create a new environment and reinstall tensorflow with conda or pip,but the result is same.Use conda install from tsinghua's mirror,tensorflow's version is tensorflow1.10,pip install's tensorflow is tensorflow1.11,Had sameone happened the same question? 
```
~/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in <module>()
     38 from tensorflow.python.keras.engine import training_generator
     39 from tensorflow.python.keras.engine import training_utils
---> 40 from tensorflow.python.keras.engine.network import Network
     41 from tensorflow.python.keras.utils.generic_utils import slice_arrays
     42 from tensorflow.python.ops import array_ops

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py in <module>()
     64 
     65 
---> 66 class Network(base_layer.Layer):
     67   """A `Network` is a composition of layers.
     68 

AttributeError: module 'tensorflow.python.keras.engine.base_layer' has no attribute 'Layer'

```

**Comment by harshini-gadige** [comment]
@bleedingfight Hi, thanks for the post. You have to use cuDNN 7 with CUDA 9 for any tensorflow-gpu version from 1.5 to 1.11. I understand from your post that you are using cuDNN5.1 with CUDA 9 which is not a correct combination inorder to use tensorflow on Ubuntu. 
For more information on the version compatibility, please find Tested build configurations in [this link.](https://www.tensorflow.org/install/source#tested_build_configurations)

**Comment by bleedingfight** [comment]
@harshini-gadige Sorry,I don't understand your means.I post error info in the title,My GPU's computer capacity is 5.1,I found the libcudnn.so.7.0.5 in my cuda folder.Thanks for your help.

**Comment by gunan** [comment]
as our internals change, sometimes we saw things like this happen as pypi does not properly clean things up. Could you Try the following:
```
pip uninstall tensorflow
rm -rf ~/anaconda3/lib/python3.6/site-packages/tensorflow
pip install tensorflow
```

**Comment by bleedingfight** [comment]
@gunan thanks for your help,it workd now.

**Comment by gunan** [comment]
Awesome, thanks for the update.
I will close this issue. But we are looking into finding a workaround for the bug in pip that causes this problem.

**Comment by harshini-gadige** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
