### ISSUE TITLE
tf.test.is_gpu_available() blocking indefinitely, using 100% CPU

### ISSUE THREAD

**Issue by epicvrvs** [tensorflow/tensorflow#22730]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Barely. See below.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10, Version 10.0.17134.285.
- **TensorFlow installed from (source or binary)**: Binary.
- **TensorFlow version (use command below)**: b'v1.11.0-rc2-4-gc19e29306c' 1.11.0.
- **Python version**: Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32.
- **CUDA/cuDNN version**: CUDA V9.0.176, cuDNN v7.3.1.
- **GPU model and memory**: Nvidia GTX 970 4 GB.

### Reproduction
```
import tensorflow as tf
print(tf.test.is_gpu_available())
```

### Expected behaviour
Test prints `True`.

### Actual behaviour
The test script prints the following text and then hangs indefinitely, using 100% of one CPU core:
```
>>> tf.test.is_gpu_available()

2018-10-03 23:08:26.805592: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

2018-10-03 23:08:27.171992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:

name: GeForce GTX 970 major: 5 minor: 2 memoryClockRate(GHz): 1.253

pciBusID: 0000:01:00.0

totalMemory: 4.00GiB freeMemory: 3.31GiB

2018-10-03 23:08:27.184134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
```

**Comment by epicvrvs** [comment]
A user on Reddit pointed out that it might be a duplicate of the following open issue:
https://github.com/tensorflow/tensorflow/issues/21836

**Comment by harshini-gadige** [comment]
@epicvrvs Hi, have you installed gpu version of tensorflow ? i.e pip install tensorflow-gpu. 
Just wanted to get confirmation on this first :)

**Comment by epicvrvs** [comment]
Yes, I have installed the GPU version of TensorFlow. Not the CPU version.

```
>pip list | grep tensor
tensorboard         1.11.0
tensorflow-gpu      1.11.0
```

**Comment by epicvrvs** [comment]
I just realized that the same happens when just running `tf.Session()` so it's actually worse than I thought.
