### ISSUE TITLE
Layer Normalization : Choice of the correct axes where to apply mean and variance in case of LSTM Input

### ISSUE THREAD

**Issue by AzizCode92** [tensorflow/tensorflow#22731]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: VERSION="16.04.4 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
   No

- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.9.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.11.1
- **GCC/Compiler version (if compiling from source)**: c++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

- **CUDA/cuDNN version**: 9.1
- **GPU model and memory**:  Tesla K80

- **Exact command to reproduce**: no command to reproduce

### Describe the problem
I'm implementing layer_normalization in an LSTM cell. My input has the following shape                           
**[batch,time,features]**.
In tensorflow, we have the [LayerNormBasicLsmtCell](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/LayerNormBasicLSTMCell).
Reading the code of this class, and in line [1417](https://github.com/tensorflow/tensorflow/blob/c19e29306ce1777456b2dbb3a14f511edf7883a8/tensorflow/contrib/rnn/python/ops/rnn_cell.py#L1417), the authors used the layer_norm function to apply the shift/scale of the inputs. 
Going to the implementation of the layer_norm and in line [2311](https://github.com/tensorflow/tensorflow/blob/c19e29306ce1777456b2dbb3a14f511edf7883a8/tensorflow/contrib/layers/python/layers/layers.py#L2311), tensorflow specified the axes where to compute the mean/variance. Knowing that `begin_param_axis=1` and the `inputs_rank=3` in my case.
The `norm_axes = list(range(1,3)) = [1,2]` so the mean/variance will be calculated on both axis time and features.
**My question is** : 
why do we need to compute the mean and variance of both axis=time and axis=Features?
Isn't okay to just do the nn.moments of the feature axis only? 
How can we set up the axes correctly in case of LSTM cells?

**Comment by AzizCode92** [comment]
Done

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
