### ISSUE TITLE
Batch Jacobian seems to have troubles to pass through `tf.nn.elu` and `tf.nn softplus`

### ISSUE THREAD

**Issue by ricvo** [tensorflow/tensorflow#22737]
### System information
- Linux Ubuntu 16.04
- tensorflow 1.11.0
- python3.5.2

### The problem
Batch Jacobian seems to have troubles to pass through `tf.nn.elu` and `tf.nn softplus`

### Source code
```
import tensorflow as tf
from tensorflow.python.ops.parallel_for.gradients import batch_jacobian
tf.set_random_seed(1000)
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]='1'
import argparse


parser = argparse.ArgumentParser(description='test jacobian', formatter_class=argparse.ArgumentDefaultsHelpFormatter)

parser.add_argument('--activation', '-a', default=None)

args = parser.parse_args()

print("using tensorflow"+tf.__version__)
act1=None
if args.activation:
    act1 = getattr(tf.nn, args.activation)

print("activation = "+str(act1))

x = tf.placeholder(tf.float32, shape=[None, 784], name='input')
my_layer = tf.layers.dense(inputs=x,
                           units=10,
                           activation=act1
                           )

jac = batch_jacobian(my_layer,x)
```

 ### Error
```
$ python test-jacobian-simple.py -a softplus
using tensorflow1.11.0
activation = <function softplus at 0x7f345a279840>
Traceback (most recent call last):
  File "test-jacobian-simple.py", line 29, in <module>
    jac = batch_jacobian(my_layer,x)
  File "/data1/env/tf1.11.0/lib/python3.5/site-packages/tensorflow/python/ops/parallel_for/gradients.py", line 119, in batch_jacobian
    pfor_output = control_flow_ops.pfor(loop_fn, output_row_size)
  File "/data1/env/tf1.11.0/lib/python3.5/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 129, in pfor
    outputs.append(converter.convert(loop_fn_output))
  File "/data1/env/tf1.11.0/lib/python3.5/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 1077, in convert
    output = self._convert_helper(y)
  File "/data1/env/tf1.11.0/lib/python3.5/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 1216, in _convert_helper
    if flags.FLAGS.op_conversion_fallback_to_while_loop:
  File "/data1/env/tf1.11.0/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 490, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --op_conversion_fallback_to_while_loop before flags were parsed.
```

Same error with:
`python test-jacobian-simple.py -a elu`

If I run with rel;u or leaky_relu instead it works fine:
`python test-jacobian-simple.py -a relu`
`python test-jacobian-simple.py -a leaky_relu`

Any ideas on how to fix this or how to workaround?

**Comment by ricvo** [comment]
All relevant info are already specified, if you think something relevant is missing I'd be happy to provide the extra info.
Have I written custom code: Yes and I put it up.
OS Platform and Distribution: I already specified, Ubuntu 16.04
TensorFlow installed from: `pip install --upgrade tensorflow-gpu`
TensorFlow version:  1.11.0
Bazel version: N/A
CUDA/cuDNN version: 9.0 / 7.3
GPU model and memory: geforce gtx 1080 ti
Exact command to reproduce: `python test-jacobian-simple.py -a elu`
Mobile device: Laptop or computer

**Comment by wt-huang** [comment]
@ricvo The nonlinear gradients in Jacobian computation used in `elu ` is usually much slower and the performance is not as good as `relu `most of the time. If you want to use `elu`, try to convert the input shape in your example and reduce the number of units to a much smaller number.

**Comment by ricvo** [comment]
I would be happy it it would be just slower...
NB the problem is in the creation of the graph, not even in the computation!
Try the code i sent, is a very small piece of code, and it does not even initialize a session.
It is a problem with flags
**absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --op_conversion_fallback_to_while_loop before flags were parsed.**

**Comment by wt-huang** [comment]
@ricvo This issue is fixed in TensorFlow nightly build. You should be able to pass elu, softplus, relu and leaky_relu now.

**Comment by ricvo** [comment]
@wt-huang I just tried the nightly build and it seems to work, thank you very much!

**Comment by wt-huang** [comment]
Are all your questions answered?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
