### ISSUE TITLE
why does tf.norm return a complex tensor?

### ISSUE THREAD

**Issue by ziofil** [tensorflow/tensorflow#22740]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
MacOS 10.14
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
N/A
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
v1.11.0-rc2-4-gc19e29306c 1.11.0
- **Python version**:
Python 3.6.5 :: Anaconda custom (64-bit)
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
`tf.norm(tf.Variable(0.0, dtype=tf.complex64)) `

### Describe the problem
The norm is always positive, why does it return a tensor of type tf.complex64?

**Comment by ziofil** [comment]
Perhaps I was too succinct. I think this is more of a bug: a norm (mathematically speaking) always returns a number that is either zero or positive. A real number in any case, certainly never having an imaginary component.
I would expect `tf.norm` to cast the returned tensor to a float.

**Comment by alextp** [comment]
I think it is a convenience issue: if your computation is already expressed in the complex dtype getting a norm you cannot pass to the same ops as your complex number is likely to lead to more bugs than not, and getting the real part of a complex tensor is easy if you do want to do it.
