### ISSUE TITLE
TensorFlow build error possibly caused by renamed zlib license file

### ISSUE THREAD

**Issue by cmessenger99** [tensorflow/tensorflow#22741]
I get a build failure building tensorflow using bazel, due to the fact that the following file apparently no longer exists: https://docs.python.org/2.7/_sources/license.txt

This file is specified in workspace.bzl (master):

  filegroup_external(
      name = "org_python_license",
      licenses = ["notice"],  # Python 2.0
      sha256_urls = {
          "b5556e921715ddb9242c076cae3963f483aa47266c5e37ea4c187f77cc79501c": [
              "https://mirror.bazel.build/docs.python.org/2.7/_sources/license.txt",
              "https://docs.python.org/2.7/_sources/license.txt",
          ],
      },
  )

It appears that the file has been replaced by one named license.rst.txt.

There is a second file which bazel can't download, for no obvious reason: zlib-1.2.11.tar.gz. I am able to manually download the file from the file's URLs in workspace.bzl.

Bazel successfully downloaded all other files.

As a workaround, I have acquired the two problematical files, and manually placed them in the bazel cache, verifying that they have the expected file hashes. However, when I run "bazel fetch //tensorflow/tools/pip_package:build_pip_packages", I get the following errors:

   ERROR: /home/cmesse02/.cache/bazel/_bazel_cmesse02/f4cce9ac06677e7da5b9b027126f0db6/external/org_python_pypi_backports_weakref/BUILD:17:1: no such package '@org_python_license//': java.io.IOException: Error downloading [https://mirror.bazel.build/docs.python.org/2.7/_sources/license.txt, https://docs.python.org/2.7/_sources/license.txt] to /home/cmesse02/.cache/bazel/_bazel_cmesse02/f4cce9ac06677e7da5b9b027126f0db6/external/org_python_license/license.txt: All mirrors are down: [GET returned 404 Not Found, sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target] and referenced by '@org_python_pypi_backports_weakref//:license'
   ERROR: /home/cmesse02/.cache/bazel/_bazel_cmesse02/f4cce9ac06677e7da5b9b027126f0db6/external/org_python_pypi_backports_weakref/BUILD:17:1: no such package '@org_python_license//': java.io.IOException: Error downloading [https://mirror.bazel.build/docs.python.org/2.7/_sources/license.txt, https://docs.python.org/2.7/_sources/license.txt] to /home/cmesse02/.cache/bazel/_bazel_cmesse02/f4cce9ac06677e7da5b9b027126f0db6/external/org_python_license/license.txt: All mirrors are down: [GET returned 404 Not Found, sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target] and referenced by '@org_python_pypi_backports_weakref//:license'
   ERROR: /home/cmesse02/local/tensorflow/tensorflow/tools/pip_package/BUILD:106:1: no such package '@zlib_archive//': java.io.IOException: Error downloading [https://mirror.bazel.build/zlib.net/zlib-1.2.11.tar.gz, https://zlib.net/zlib-1.2.11.tar.gz] to /home/cmesse02/.cache/bazel/_bazel_cmesse02/f4cce9ac06677e7da5b9b027126f0db6/external/zlib_archive/zlib-1.2.11.tar.gz: All mirrors are down: [sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target] and referenced by '//tensorflow/tools/pip_package:licenses'
   ERROR: Evaluation of query "deps(//tensorflow/tools/pip_package:build_pip_package)" failed: errors were encountered while computing transitive closure
   Building: no action

During the command, bazel removes the two files from its cache.

The argument could be made that this is a bazel issue. However, I think it might also be a tensorflow issue, at least for the license.txt file, because that file name is apparently wrong (it should be license.rst.txt).

**Comment by gunan** [comment]
This is interesting. Our CI does not run into this problem.
Could you fill in the issue template to help us see what is different in your setup?

**Comment by gunan** [comment]
How about this theory?
Our builds currently rely on `mirrors.bazel.build` hosting a mirror for each and every external dependency we have. This site is hosted on GCP.
If your corporate firewall blocked or limited access to GCP, you will fall back to the original URL. That, combined with the underlying change that happened in the license files can explain this problem.

Can you confirm if your access to GCP is blocked by running:
```
curl https://mirror.bazel.build/docs.python.org/2.7/_sources/license.txt
```

Regardless, we should update this license dependency, maybe even use a version from git for the original license to avoid such disruptions.

**Comment by cmessenger99** [comment]
Results with curl. First, for reference, I test a file which works, on 3 different machines (machines A, B, C):

  curl http://ftp.exim.org/pub/pcre/pcre-8.39.tar.gz | sha256sum

File hash checks out on all machines. Next, on the Python 2.7 license file, from the bazel mirror:

  curl https://mirror.bazel.build/docs.python.org/2.7/_sources/license.txt | sha256sum

On machines A and B, this fails with:

  curl: (60) SSL certificate problem: unable to get local issuer certificate

On machine C, this works. Machine C did not have any problems building Tensorflow - no workaround was needed.

On all 3 machines, I was able to download this file using wget:

  wget https://mirror.bazel.build/docs.python.org/2.7/_sources/license.txt

So, it would seem that curl is more discriminating than wget, somehow, when it comes to checking certificates. That explains part of what has been puzzling me: why is it that I can download the problematical files with no problem, while bazel can't.  It seems it is because I use wget, while bazel uses curl.

**Comment by gunan** [comment]
the python license issue should be resolved.
I think the zlib issue is due to access to the resources.

**Comment by joybit** [comment]
I have the same issue with bazel **0.11.0** (`Error downloading [https://mirror.bazel.build/docs.python.org/2.7/_sources/license.rst.txt)`
I tried creating a manual-download folder and this command: `bazel fetch --experimental_distdir manual-download //tensorflow/tools/pip_package:build_pip_package`, but --experimental_distdir option is not recognized. 
do you know if --experimental_repository_cache is the replacement?

Is there a known solution for this issue?
