### ISSUE TITLE
Trying to install tensorflow 1.11.0 on python 3.4.2

### ISSUE THREAD

**Issue by ishandutta2007** [tensorflow/tensorflow#22745]
Have I written custom code: No
OS Platform and Distribution: Mac Sierra
TensorFlow installed from: running on pyenv, currently on local pyenv of python 3.4.2, installed via `pip`
TensorFlow version: 1.11.0
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: `pip install tensorflow`
Mobile device: N/A

This is the error I get,

> tensorflow 1.11.0 has requirement setuptools<=39.1.0, but you'll have setuptools 40.4.3 which is incompatible.

uninstllling and reinstalling setuptools to required version fixes it but ideally it should work with the default verision that comes with python 3.4.2

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ishandutta2007** [comment]
updated

**Comment by ymodak** [comment]
What is the pip version you are using?

**Comment by Juanlu001** [comment]
I guess this is related to https://github.com/tensorflow/tensorflow/issues/22567?

**Comment by ymodak** [comment]
Yes this issue is related to #22567. As mentioned in that thread, This issue can be resolved once 1.12 rc0 builds.
