### ISSUE TITLE
Cannot compile with C++17 because std::random_shuffle is removed

### ISSUE THREAD

**Issue by FelixDuvalletKodiak** [tensorflow/tensorflow#22746]
std::random_shuffle has been deprecated since C++14 and [removed](https://meetingcpp.com/blog/items/stdrandom_shuffle-is-deprecated.html) from C++17. Unfortunately this means it's not possible to compile tensorflow with C++17.

Fortunately, there are not many [usages](https://github.com/tensorflow/tensorflow/search?l=C%2B%2B&q=random_shuffle
) present, and the [suggested replacement](https://meetingcpp.com/blog/items/stdrandom_shuffle-is-deprecated.html) is not very complicated.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by FelixDuvalletKodiak** [comment]
Have I written custom code: no
OS Platform and Distribution: all
TensorFlow installed from: n/a
TensorFlow version: master
Bazel version: 16
CUDA/cuDNN version: n/a
GPU model and memory: n/a
Exact command to reproduce: n/a
Mobile device: no
