### ISSUE TITLE
Feature request for tf.contrib.image.translate

### ISSUE THREAD

**Issue by gautamsreekumar** [tensorflow/tensorflow#22760]
### System information

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04.4
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: Not applicable
- **TensorFlow installed from (source or binary)**: Don't know
- **TensorFlow version (use command below)**: 1.18.0
- **Python version**: 2.7.15
- **Bazel version (if compiling from source)**: Don't know
- **GCC/Compiler version (if compiling from source)**: Don't know
- **CUDA/cuDNN version**: CUDA 7.5.17
- **GPU model and memory**: GeForce GTX 1080 Ti, 11GB
- **Exact command to reproduce**: tf.contrib.image.translate(img, output_of_network)

Hi, is there a way that the feature for computing gradients through the translation in `tf.contrib.image.translate` could be added? It does not involve any interpolation like in `tf.contrib.image.transform` or `tf.contrib.image.rotate` as in issue  #18649

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
OS Platform and Distribution
TensorFlow installed from
Bazel version
Exact command to reproduce
Mobile device

**Comment by gautamsreekumar** [comment]
Hi @tensorflowbutler, I have updated the details, Please look into it.

**Comment by wt-huang** [comment]
@gautamsreekumar `tf.contrib.image.translate` has the same issue as `tf.contrib.image.transform` since the gradient for bilinear interpolation can't be calculated from the existing projective transformation. OpenCV or MATLAB would be a better option.

**Comment by rickyim** [comment]
> @gautamsreekumar `tf.contrib.image.translate` has the same issue as `tf.contrib.image.transform` since the gradient for bilinear interpolation can't be calculated from the existing projective transformation. OpenCV or MATLAB would be a better option.

@wt-huang  Do you mean we can implement gradient through image translation/rotation by OpenCV/MATLAB? If so, can you briefly explain how? As I am facing similar issue. Thank you!

**Comment by skosch** [comment]
I needed this as well, so for posterity: if all you care about is translation, this can be accomplished with some effort using padding and slicing via `map_fn`. That keeps the operation differentiable. ([Code example](https://gist.github.com/skosch/e43260f3ae65ddb319b43ce880349175), [SO question](https://stackoverflow.com/questions/55767069))

**Comment by gautamsreekumar** [comment]
I asked this question on StackOverflow and I got an answer which showed how I could use `tf.gradients` to manually calculate the gradients. The answer can be found [here](https://stackoverflow.com/a/52779070/6211109)
