### ISSUE TITLE
Error building on Windows, patch command failing

### ISSUE THREAD

**Issue by madsdk** [tensorflow/tensorflow#22761]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 3.6.6
- **Bazel version (if compiling from source)**: 0.17.2
- **GCC/Compiler version (if compiling from source)**: Visual C++ Build Tools 2015
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: Follow build instructions on https://www.tensorflow.org/install/source_windows

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

When following the build instructions on https://www.tensorflow.org/install/source_windows I am unable to build tensorflow from source. I'm running on a clean Windows 10 install (nothing else installed but the requirements listed on the homepage). 

When running the bazel build step (CPU) with the command: $ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package I get two different errors, both when the build script tries to patch some files. The commands that fail are:

`C:\msys64\usr\bin\bash.exe -l -c patch -p1 -d C:/users/cm/_bazel_cm/xv6zejqw/external/kafka -i C:/tensorflow/third_party/kafka/config.patch
C:\msys64\usr\bin\bash.exe -l -c patch -p1 -d C:/users/cm/_bazel_cm/xv6zejqw/external/png_archive -i C:/tensorflow/third_party/png_fix_rpi.patch`

Copying the patch commands into the cmd.exe prompt makes the patch command "hang" until I manually terminate it. If I add ' ' around the command part of the bash invocation (e.g. bash -c 'patch ...') it works just fine. 

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

`$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
DEBUG: C:/users/cm/_bazel_cm/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/cm/_bazel_cm/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/cm/_bazel_cm/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@kafka//': Traceback (most recent call last):
        File "C:/tensorflow/third_party/repo.bzl", line 99
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/tensorflow/third_party/repo.bzl", line 67, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(256) when executing 'C:\msys64\usr\bin\bash.exe -l -c patch -p1 -d C:/users/cm/_bazel_cm/xv6zejqw/external/kafka -i C:/tensorflow/third_party/kafka/config.patch':
Stdout:
Stderr: Timed out
INFO: Elapsed time: 93,541s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (242 packages loaded)

cm@tbuilder  /c/tensorflow
$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
DEBUG: C:/users/cm/_bazel_cm/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/cm/_bazel_cm/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/cm/_bazel_cm/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@png_archive//': Traceback (most recent call last):
        File "C:/tensorflow/third_party/repo.bzl", line 99
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/tensorflow/third_party/repo.bzl", line 67, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(256) when executing 'C:\msys64\usr\bin\bash.exe -l -c patch -p1 -d C:/users/cm/_bazel_cm/xv6zejqw/external/png_archive -i C:/tensorflow/third_party/png_fix_rpi.patch':
Stdout:
Stderr: Timed out
INFO: Elapsed time: 33,880s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)`

**Comment by gunan** [comment]
@meteorcloudy

**Comment by tonygrue** [comment]
@madsdk I also just ran into this. In another similar bug (lost track of which one and can't find it now) it was suggested that you rerun `pacman -S patch` under msys2 (as opposed to cmd.exe).  Doing that got me unblocked.  (fwiw, seems like there is some issue here with the instructions, but I'm too unfamiliar with msys to say exactly what. just sharing this workaround in case it may prove of use.)

**Comment by madsdk** [comment]
> 
> 
> @madsdk I also just ran into this. In another similar bug (lost track of which one and can't find it now) it was suggested that you rerun `pacman -S patch` under msys2 (as opposed to cmd.exe). Doing that got me unblocked. (fwiw, seems like there is some issue here with the instructions, but I'm too unfamiliar with msys to say exactly what. just sharing this workaround in case it may prove of use.)

Thank you for your suggestion. I tried this (running bash from the cmd.exe and then removing and re-installing patch), but unfortunately it doesn't seem to work for me. Did you run the bazel build command from msys2 bash also?

**Comment by meteorcloudy** [comment]
@madsdk Can you try to run `bazel clean --expunge` command then retry the build? See if it helps.
It's not the first I see this issue, but I couldn't reproduce it,

**Comment by madsdk** [comment]
> 
> 
> @madsdk Can you try to run `bazel clean --expunge` command then retry the build? See if it helps.
> It's not the first I see this issue, but I couldn't reproduce it,

Thank you for your answer. I've tried calling clean before, but I just tried it again and got the following result:
`c:\tensorflow>bazel clean --expunge
Starting local Bazel server and connecting to it...
INFO: Starting clean.

c:\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
DEBUG: C:/users/cm/_bazel_cm/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/cm/_bazel_cm/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/cm/_bazel_cm/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@kafka//': Traceback (most recent call last):
        File "C:/tensorflow/third_party/repo.bzl", line 99
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/tensorflow/third_party/repo.bzl", line 67, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(256) when executing 'C:\msys64\usr\bin\bash.exe -l -c patch -p1 -d C:/users/cm/_bazel_cm/xv6zejqw/external/kafka -i C:/tensorflow/third_party/kafka/config.patch':
Stdout:
Stderr: Timed out
INFO: Elapsed time: 98,260s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (243 packages loaded)`

**Comment by meteorcloudy** [comment]
Can you show me your `PATH` environment variable and where is `patch` installed?

Should be the output of `echo %PATH%` and `which patch`

**Comment by ivopivo** [comment]
I am also having the same issue. Have exact the same setting like the original post except I am using Python 3.5.2 (Downgraded from 3.6.6 as I read somewhere tensorflow wasn't supporting 3.6. But probably outdated claim)

**Comment by deepKratos** [comment]
Having the same issue. 
Same/exact configuration as @madsdk

**Comment by bjepson** [comment]
I'm seeing the same behavior, but if the error message is correct, and the -c argument to bash.exe isn't being quoted, the behavior is what I'd expect. That's because bash would be running patch without arguments, so would be hanging waiting for STDIN, which leads to the timeout that kills the job:

```
Non-zero return code(256) when executing 'C:\msys64\usr\bin\bash.exe -l -c patch -p1 -d C:/users/bjeps/_bazel_bjeps/jcnpsgii/external/png_archive -i C:/users/bjeps/desktop/src/tensorflow/third_party/png_fix_rpi.patch':
Stdout:
Stderr: Timed out
INFO: Elapsed time: 153.569s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (242 packages loaded)
```

**Comment by madsdk** [comment]
I just added the suggested changes to repo.bzl (thanks @twilightdema) but I still get an error with either the kafka or the png_archive package.

`
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@kafka//': Traceback (most recent call last):
        File "C:/tensorflow/third_party/repo.bzl", line 99
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/tensorflow/third_party/repo.bzl", line 67, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch -p1 -d C:/users/cm/_bazel_cm/xv6zejqw/external/kafka -i C:/tensorflow/third_party/kafka/config.patch"':
Stdout:
Stderr: /usr/bin/bash: patch -p1 -d C:/users/cm/_bazel_cm/xv6zejqw/external/kafka -i C:/tensorflow/third_party/kafka/config.patch: No such file or directory
INFO: Elapsed time: 111,261s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (264 packages loaded)
`

**Comment by madsdk** [comment]
Copying the command line that it says fails, works perfectly now that the patch command has been put within ' ':

c:\tensorflow>C:\msys64\usr\bin\bash.exe -l -c 'patch -p1 -d C:/users/cm/_bazel_cm/xv6zejqw/external/kafka -i C:/tensorflow/third_party/kafka/config.patch'
patching file config.h

**Comment by twilightdema** [comment]
@madsdk - Seeing from you log:
`
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch -p1 -d C:/users/cm/_bazel_cm/xv6zejqw/external/kafka -i C:/tensorflow/third_party/kafka/config.patch"'
`
Please make sure that you don't add single quote or double quote to "repo.bzl ".
**The only necessary change seems to be Timeout value.**
Adding quote/double quote will generate 'No such file or directory' error.
From what I found, the original line below is correct:
`
cmd = [bazel_sh, "-l", "-c", " ".join(cmd)]
`

**Comment by madsdk** [comment]
@twilightdema thank you for your message. You are indeed right, if I remove the added quotes the build process actually starts now! :) Only problem is that it breaks down a few minutes later now... I'll try some things and perhaps post a new log soon. Thank you 👍

**Comment by deepKratos** [comment]
@twilightdema Thank you for the propsed solution.  Problem solved when changing the timeout value !

**Comment by bjepson** [comment]
> Please make sure that you don't add single quote or double quote to "repo.bzl ".
> **The only necessary change seems to be Timeout value.**
> Adding quote/double quote will generate 'No such file or directory' error.
> From what I found, the original line below is correct:
> `cmd = [bazel_sh, "-l", "-c", " ".join(cmd)]`

@twilightdema Thank you! I just tried on a faster computer than the one I was building on, and it works, so that confirms what you said. 

The arguments to bazel_sh are quoted fine, contrary to what I had thought before. It seems that building on a slower computer can lead to this error. I had compiled it on the same slow computer under the Windows Subsystem for Linux, and hadn't encountered this error, but when running using Visual C and MSYS, I received the timeout error.

**Comment by meteorcloudy** [comment]
@twilightdema Thanks for the solution! I'll send a PR to increase the timeout!

**Comment by arunmandal53** [comment]
Still having timeout after setting up the time out. Adding double quotes or simply running patch instead of bash patch works. I fixed it by commenting then line where cmd is wraped with bash to run patch directly from msys2.

**Comment by twilightdema** [comment]
> Still having timeout after setting up the time out. Adding double quotes or simply running patch instead of bash patch works. I fixed it by commenting then line where cmd is wraped with bash to run patch directly from msys2.

@arunmandal53 - Can you try adding more timeout? I saw in patch that timeout was increased to be 60.. Anyway, I built tensorflow on Surface 3 (Non-Pro) (CPU ATOM), I have to use like 200 in order to not getting Timeout.

**Comment by arunmandal53** [comment]
When i ran bash -c patch -v it will take too much time so need to stop forcefully. But when i just use patch -v it works instantly. Also bash -c "patch -v" works instantly.

**Comment by Miptipop** [comment]
> When i ran bash -c patch -v it will take too much time so need to stop forcefully. But when i just use patch -v it works instantly. Also bash -c "patch -v" works instantly.



> Still having timeout after setting up the time out. Adding double quotes or simply running patch instead of bash patch works. I fixed it by commenting then line where cmd is wraped with bash to run patch directly from msys2.

can you explain more clearly?

**Comment by GPhilo** [comment]
Just adding a comment for who lands here because of error 127 ( @madsdk ): after plenty of <s>swearing</s> researching, I finally figured it out: Error 127 is raised by bash when the program run is not found **or one of its dependencies is missing**. Turns out, my **MSYS2 installation was not complete**.

Following Bazel's website, I chose the Chocolately installation, which also installs dependencies (msys2 and python2), however, it seems that the setup script does NOT update the msys2 setup after the installation completes. Following the instructions on mysy2's homepage, I ran `pacman -Syu`, closed and reopened the shell, ran again `pacman -Su` and now it stopped raising the error on `patch`.
