### ISSUE TITLE
Keras cannot get gradient for using only one output from multi-outputs in another model

### ISSUE THREAD

**Issue by ybsave** [tensorflow/tensorflow#22775]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**:  binary
- **TensorFlow version (use command below)**: 1.11.0-dev20180823
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0 / 7
- **GPU model and memory**: Quadro M4000
- **Exact command to reproduce**: N/A

### Describe the problem
I build one keras model with two outputs. I want to build another model that is exactly just a part of the existing model by using only one output. However, it shows the error message as

    ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

### Source code / logs
Example codes are shown below

	def get_test0_net():
	  data_input = keras.Input(shape=(4, 4, 3))
	  x0 = Conv2D(3, 3, padding='same')(data_input)
	  x1 = Conv2D(3, 3, padding='same')(data_input)
	  return keras.Model(inputs=data_input, outputs=[x0, x1])
	  
	def test0():
	  model = get_test0_net()

	  batch_in = np.ones((1,4,4,3))
	  batch_out = [np.zeros((1,4,4,3)), np.zeros((1,4,4,3))]

        # the original model can train without problem
	#  model.compile(loss='mse', optimizer='adam')
	#  model.train_on_batch(batch_in, batch_out)
	  
	  data_input = keras.Input(shape=(4, 4, 3))
	  out = model(data_input)[0]
	  new_model = keras.Model(data_input, out)
	  new_model.compile(loss='mse', optimizer='adam')
	  new_model.train_on_batch(batch_in, batch_out[0])

**Comment by fchollet** [comment]
You are asking `new_model` to compute the gradients of some weights (specifically the weights of the second `Conv2D` layer) that are not involved in the forward pass of the model. Naturally, these weights have None gradients, which is an error.

Make sure that all layers you are including in your model are used.
