### ISSUE TITLE
tf.keras.layers.SeparableConv2D fails on Cloud TPU

### ISSUE THREAD

**Issue by choongng** [tensorflow/tensorflow#22772]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes: Convnet for MNIST, hand-written
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colaboratory, default versions of Python & all libraries
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: n/a
- **TensorFlow installed from (source or binary)**: n/a
- **TensorFlow version (use command below)**: n/a
- **Python version**: n/a
- **Bazel version (if compiling from source)**: n/a 
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: TPU
- **Exact command to reproduce**: n/a, see below

### Description
tf.keras.layers.SeparableConv2D fails on Cloud TPU. Colaboratory notebook with small example linked, works with GPU runtime but not TPU runtime.

https://colab.research.google.com/drive/1TyYSeA6bq2YBT7Ngo7thHfrcrAR30aXa

Expected result is successful training to >99% accuracy, this works on GPU but on TPU model.fit throws (full stack trace in notebook):

```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in __init__(self, fetches, contraction_fn)
    289       except ValueError as e:
    290         raise ValueError('Fetch argument %r cannot be interpreted as a '
--> 291                          'Tensor. (%s)' % (fetch, str(e)))
    292       except KeyError as e:
    293         raise ValueError('Fetch argument %r cannot be interpreted as a '

ValueError: Fetch argument <tf.Variable 'separable_conv2d_6/depthwise_kernel:0' shape=(5, 5, 1, 1) dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("separable_conv2d_6/depthwise_kernel/Read/ReadVariableOp:0", shape=(5, 5, 1, 1), dtype=float32) is not an element of this graph.)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by choongng** [comment]
Updated.

**Comment by wt-huang** [comment]
@choongng I ran the above code snippet on TPU without running into any errors. There is a warning `WARNING:tensorflow:tpu_model (from tensorflow.contrib.tpu.python.tpu.keras_support) is experimental and may change or be removed at any time, and without warning.` which you can ignore.

**Comment by choongng** [comment]
Verified it's working, thanks! (cc @fchollet)

**Comment by wt-huang** [comment]
Are all your questions answered?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
