### ISSUE TITLE
System freezes after decreasing batch size when using CuDNNLSTM

### ISSUE THREAD

**Issue by twolodzko** [tensorflow/tensorflow#22795]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: Yes (conda)
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 3.6.6
- **Bazel version (if compiling from source)**: 
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.0, V10.0.130
- **GPU model and memory**: GeForce GTX 1070 
- **Exact command to reproduce**:

### Describe the problem
While executing rather simple model in Keras/TensorFlow with three `keras.layers.CuDNNLSTM` layers, some skip connections, `Embedding` and `Dense` layers with <10 GB data read from numpy arrays, my system has frozen after using smaller batch size. When using batches of size 512 or larger everything was fine, when decreasing it to 256 system freezes (still screen, mouse and keyboard non responsive) after just a few dozen of iterations (not epochs). This happened several times in a row, with no single success, so I stopped experimenting further. Once I waited for 10 minutes to see if anything changes, but with no success. Everything went fine when using smaller batches and regular `keras.layers.LSTM` layers. Additionally, I used `nvidia-smi` and `top` monitoring tools and didn't notice anything strange before the crashes, but I might have missed something because of screen freezes. RAM and GPU usage in seconds before crushes was fine, far from limits.

**Comment by wt-huang** [comment]
@twolodzko This is likely triggered by the memory limitation since your data size is significant (<10 GB) and you are reading from numpy arrays. Try to stay with batch size of 512 or increase RAM, also optimize how you feed the data.

**Comment by twolodzko** [comment]
@wt-huang thanks, but how using smaller batches needs more RAM?

**Comment by wt-huang** [comment]
@twolodzko When the batch size is smaller, dataset becomes bigger causing GPU resource hungry hence more RAM is needed.

**Comment by twolodzko** [comment]
@wt-huang thanks, nice to learn something new. Nevertheless, the fact that system freezes (rather then app dies) seems to be a kind of bug, isn't it?

**Comment by wt-huang** [comment]
@twolodzko gladly. System freeze or lockup doesn't necessary contitute a bug as there may be other cofounding factors in the mix. However, if a problem is observed consistently in systems across the board then it is a bug.

**Comment by wt-huang** [comment]
Closing this, feel free to reopen if problem persists.
