### ISSUE TITLE
Could TensorFlow read data from MySQL? If not, what's the right way to add the feature?

### ISSUE THREAD

**Issue by wangkuiyi** [tensorflow/tensorflow#22798]
I wanted to write a training program that read data from MySQL.

I found [tf.contrib.data.SqlDataset](https://www.tensorflow.org/api_docs/python/tf/contrib/data/SqlDataset), which seems reads from SQLite, but not other SQL DBMSes.

I tried to see how if I can extend it to support MySQL. It seems that (please correct me if I am wrong): [`tf.contrib.data.SqlDataset`](https://github.com/tensorflow/tensorflow/blob/b72265dc002e712fc3d0f33434f13c7a36a484b2/tensorflow/contrib/data/python/ops/readers.py#L363) uses `class SqlDatasetOp`, which uses [SQL drivers in the directory](https://github.com/tensorflow/tensorflow/tree/ad5c0c4d091c93ef65e91c55cb4df065d0c7a989/tensorflow/core/kernels/data/sql), and it seems that I can extend `SqlDatasetOp` by adding the MySQL connection driver as `mysql_query_connection.{h,cc}` in the directory.  However, this would require me to add MySQL libraries as TensorFlow dependencies in [`tensorflow/core/lib/db/BUILD`](https://github.com/tensorflow/tensorflow/blob/ad5c0c4d091c93ef65e91c55cb4df065d0c7a989/tensorflow/core/lib/db/BUILD); thus makes the TensorFlow binary depends on too many external staff. Is such kind of contributions welcome by the community?

I also noticed that the [Hadoop sequence file dataset](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/hadoop) is in the `contrib` directory. Is this the recommended way to adding datasets?

Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
