### ISSUE TITLE
Unable to download Android prebuilt binaries

### ISSUE THREAD

**Issue by marcominerva** [tensorflow/tensorflow#22802]
Hi all!

On the README.md file at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/android#android-tensorflow-support it is said that we can download prebuilt binaries for Android via https://ci.tensorflow.org/view/Nightly/job/nightly-android, but unfortunately this link is broken. 

Is there another way to get prebuilt binaries for Android?

Kindest regards.

**Comment by wt-huang** [comment]
@marcominerva This link is deprecated. There is an ongoing effort to get the Android builds back. You can refer to [20771](https://github.com/tensorflow/tensorflow/issues/20771). In the meantime, you can build your own Android project following this [tutorial](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/android/README.md).

**Comment by lef-fan** [comment]
you could use the aar package from here:
https://bintray.com/google/tensorflow/tensorflow/1.13.0-rc0
