### ISSUE TITLE
Variance Inflation Factor estimate for each layer as guidance for dropout

### ISSUE THREAD

**Issue by soodoku** [tensorflow/tensorflow#22800]
Dear All,

The [arXiv paper](https://arxiv.org/pdf/1806.06850.pdf) makes the following useful suggestion:

"We thus believe it would be helpful for NN software to include layer-by-layer checks for multicollinearity. If a layer is found to output a higher degree of multicollinearity, one might consider reducing the number of units in it, or even eliminating it entirely. Applying dropout to such layers is another possible action. One related implication is that later NN layers possibly should have fewer units than the earlier ones"

(Please see Table 2 of the paper.)

Concrete guidance on how to implement dropout remains a bit of a dark art. I don't think it needs to be. If we can produce VIF estimates for each layer, we can very possibly implement dropout with greater confidence.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by soodoku** [comment]
Sure thing. 

Have I written custom code -- N/A
OS Platform and Distribution -- N/A
TensorFlow installed from -- N/A
TensorFlow version-- N/A
Bazel version-- N/A
CUDA/cuDNN version-- N/A
GPU model and memory-- N/A
Exact command to reproduce-- N/A
Mobile device-- N/A

**Comment by karmel** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by soodoku** [comment]
I see it as a feature request: provide VIF for each layer so that people can decide on the optimal number of hidden units in the previous layer or the dropout. But ok.
