### ISSUE TITLE
centos6 compile source code error

### ISSUE THREAD

**Issue by zdx** [tensorflow/tensorflow#22811]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  centos6.4
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: r1.9
- **TensorFlow version (use command below)**:
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.16.1
- **GCC/Compiler version (if compiling from source)**: 2.12
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: 

### Describe the problem
Compile tensorflow with source code, but get some erros.
command : 
bazel build --config=opt --conlyopt=-std=c99  --verbose_failures //tensorflow/tools/pip_package:build_pip_package

### Source code / logs
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
... still trying to connect to local Bazel server after 20 seconds ...
WARNING: /home/rcdev/.cache/bazel/_bazel_rcdev/0bbd005cd428560db8b92113dbd10a39/external/grpc/BUILD:1960:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_common.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/rcdev/.cache/bazel/_bazel_rcdev/0bbd005cd428560db8b92113dbd10a39/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: /home/rcdev/.cache/bazel/_bazel_rcdev/0bbd005cd428560db8b92113dbd10a39/external/grpc/BUILD:1960:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_decode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/rcdev/.cache/bazel/_bazel_rcdev/0bbd005cd428560db8b92113dbd10a39/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: /home/rcdev/.cache/bazel/_bazel_rcdev/0bbd005cd428560db8b92113dbd10a39/external/grpc/BUILD:1960:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_encode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/rcdev/.cache/bazel/_bazel_rcdev/0bbd005cd428560db8b92113dbd10a39/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: /home/rcdev/soft/tensorflow/tensorflow/contrib/learn/BUILD:17:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
WARNING: /home/rcdev/soft/tensorflow/tensorflow/contrib/learn/BUILD:17:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately.
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package (287 packages loaded).
INFO: Found 1 target...
INFO: From Compiling external/nsync/internal/counter.c:
cc1plus: warning: command line option '-std=c99' is valid for C/ObjC but not for C++
INFO: From Compiling tensorflow/contrib/lite/kernels/internal/tensor_utils.cc:
In file included from ./tensorflow/contrib/lite/kernels/internal/common.h:42:0,
                 from tensorflow/contrib/lite/kernels/internal/tensor_utils.cc:16:
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'void vst1q_lane_f32(float32_t*, float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:9673:31: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(ptr) =  *((float*)&ilane);
                               ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'float32_t vgetq_lane_f32(float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:11912:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     return *(float*)&ilane;
                      ^
ERROR: /home/rcdev/.cache/bazel/_bazel_rcdev/0bbd005cd428560db8b92113dbd10a39/external/gif_archive/BUILD.bazel:8:1: C++ compilation of rule '@gif_archive//:gif' failed (Exit 1): gcc failed: error executing command 
  (cd /home/rcdev/.cache/bazel/_bazel_rcdev/0bbd005cd428560db8b92113dbd10a39/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/home/rcdev/soft/binutils/lib/:/home/rcdev/soft/gcc-4.9/lib/:/home/rcdev/soft/gcc-4.9/lib64/:/usr/local/CDH5/hadoop/lib/native/:/usr/local/lib: \
    PATH=/home/rcdev/soft/python3/bin:/home/rcdev/soft/bazel-0.16.1/output:/usr/local/java/jdk1.8.0/bin:/home/rcdev/soft/binutils/bin:/home/rcdev/soft/python2.7/bin:/home/rcdev/soft/gcc-4.9/bin:/home/rcdev/soft/python3/bin:/usr/local/CDH5/hadoop/bin:/usr/local/ruby/bin:/usr/local/CDH5/hive/bin:/usr/local/jdk1.7.0/bin:/usr/local/jdk1.7.0/jre/bin:/bin:/usr/local/jdk1.7.0/bin:/usr/local/apache-maven-3.0.4/bin:/usr/local/mysql/bin:/usr/local/jdk1.7.0/bin:/usr/local/jdk1.7.0/jre/bin:/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/apache-flume/bin:/bin:/usr/local/R-3.1/bin:/usr/local/apache-flume/bin:/usr/local/CDH5/hadoop/bin:/usr/local/apache-maven-3.0.4/bin:/usr/local/CDH5/hbase/bin:/usr/local/CDH5/pig/bin:/usr/local/CDH5/zookeeper-3.4.5-cdh5.0.1/bin:/usr/local/scala-2.10.3/bin:/home/rcdev/bin:/home/rcdev/storm/bin:/home/rcdev/.local/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/home/rcdev/soft/python2.7/bin/python \
    PYTHON_LIB_PATH=/home/rcdev/soft/python2.7/lib/python2.7/site-packages \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
  /home/rcdev/soft/gcc-4.9/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/home/rcdev/soft/gcc-4.9/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/k8-opt/bin/external/gif_archive/_objs/gif/egif_lib.pic.d -fPIC -iquote external/gif_archive -iquote bazel-out/k8-opt/genfiles/external/gif_archive -iquote bazel-out/k8-opt/bin/external/gif_archive -iquote external/bazel_tools -iquote bazel-out/k8-opt/genfiles/external/bazel_tools -iquote bazel-out/k8-opt/bin/external/bazel_tools -isystem external/gif_archive/lib -isystem bazel-out/k8-opt/genfiles/external/gif_archive/lib -isystem bazel-out/k8-opt/bin/external/gif_archive/lib '-march=native' '-std=c99' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/gif_archive/lib/egif_lib.c -o bazel-out/k8-opt/bin/external/gif_archive/_objs/gif/egif_lib.pic.o)
external/gif_archive/lib/egif_lib.c: In function 'EGifOpenFileName':
external/gif_archive/lib/egif_lib.c:62:6: error: 'S_IREAD' undeclared (first use in this function)
      S_IREAD | S_IWRITE);
      ^
external/gif_archive/lib/egif_lib.c:62:6: note: each undeclared identifier is reported only once for each function it appears in
external/gif_archive/lib/egif_lib.c:62:16: error: 'S_IWRITE' undeclared (first use in this function)
      S_IREAD | S_IWRITE);
                ^
external/gif_archive/lib/egif_lib.c: In function 'EGifOpenFileHandle':
external/gif_archive/lib/egif_lib.c:119:5: warning: implicit declaration of function 'fdopen' [-Wimplicit-function-declaration]
     f = fdopen(FileHandle, "wb");    /* Make it into a stream: */
     ^
external/gif_archive/lib/egif_lib.c:119:7: warning: assignment makes pointer from integer without a cast
     f = fdopen(FileHandle, "wb");    /* Make it into a stream: */
       ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 46.012s, Critical Path: 14.30s
INFO: 327 processes: 327 local.
FAILED: Build did NOT complete successfully
You have mail in /var/spool/mail/rcdev

**Comment by ymodak** [comment]
The error likely due to your GCC/Compiler version. Please take a look at this link [Building TensorFlow for CentOS 6.](https://blog.abysm.org/2016/06/building-tensorflow-centos-6/). It mentions about the modifications that are necessary to build.

**Comment by ymodak** [comment]
@zdx Were you able to solve your issue?

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
