### ISSUE TITLE
Windows 10 c++, bazel build successfully， where is the .lib file？

### ISSUE THREAD

**Issue by EdwardVincentMa** [tensorflow/tensorflow#22812]
I have build both TensorFlow1.11 and 1.10 's libtensorflow_cc.so file successfully, but where is the .lib file for Visual Studio ?

**Comment by sumit7** [comment]
Hi Did you get the answer?
I have built tensorflow for c++ with bazel on windows and need .lib and .dll. Can you share what you did to include tensorflow in visual studio project?
