### ISSUE TITLE
Unable to disable build of AWS, HDFS, Kafka and GCP

### ISSUE THREAD

**Issue by lissyx** [tensorflow/tensorflow#22819]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: any
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: any
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master
- **Python version**: N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: ./configure

### Describe the problem
When building TensorFlow as a library (and in our case using `--config=monolithic`), we used to remove as much as possible of the not used features. Recently, this was removed from master in https://github.com/tensorflow/tensorflow/commit/d56c298f1ef14b5a738e1e0b7bbc66fcd736be3e for AWS, HDFS, Kafka and GCP.

I understand that that having to deal with multiple optionnally-disabled features can be a huge burden for the future, but is it possible to have some way around ?

**Comment by gunan** [comment]
Discussed offline.
I will need to reintroduce a way to disable building these into our build system.
I am thinking having these default on, but having `--config` options such as `noaws`, `nogcp`, `nohdfs` and `nokafka`
What do you think?

**Comment by lissyx** [comment]
I think that any solution that is okay for you in term of complexity and allows us to disable should be good :)

**Comment by lissyx** [comment]
Thanks for that!

**Comment by lissyx** [comment]
@gunan Hello, I'm testing that on current master, my build command line does include `--config=noaws --config=nogcp --config=nohdfs --config=nokafka --config=noignite` and yet, checking out the `bazel-out/` subdirectories, I find `.o` and `.d` files that have been rebuilt, under `aws-cpp-sdk-core`, `aws-cpp-sdk-kinesis` and `aws-cpp-sdk-s3`, am I missing something ?
