### ISSUE TITLE
Is Latest Tensorflow not compatible with latest cuda release  i.e CUDA 10??

### ISSUE THREAD

**Issue by artificial-mind** [tensorflow/tensorflow#22818]
Hi Team,
I have new  RTX 2080 Graphics card with cuda 10.0 and cudnn 7.3.1. But tensor flow-gpu doesn't works. Can you please tell whether  tensor flow is compatible with it or not. Because as per tensorflow.org installation it is only compatible with cuda 9. I there any way out for this??
Or you guys are planning to release tensorflow with cuda 10 compatibility.??

**Have I written custom code : NO
- **OS : Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: Using pip
- **TensorFlow version (use command below)**: TensorFlow 1.11
- **Python version**: 3.6
- **CUDA/cuDNN version**: CUDA 10.0/ cuDNN 7.3
- **GPU model and memory**: RTX 2080/ 8GB
- **Exact command to reproduce**: import tensorflow

**Comment by jrabary** [comment]
I managed to build and use Tensorflow 1.11 with cuda 10 and cudnn 7.2

**Comment by artificial-mind** [comment]
Hi @jrabary,

Please guide me through the same. I am not able to use it

**Comment by ymodak** [comment]
TensorFlow officially supports CUDA 9.0. However it is compatible with CUDA 10.0 but not supported currently. For using TF with cuda 10, you have to build it from sources yourself. You can also take a look at [installations](https://medium.com/@vitali.usau/install-cuda-10-0-cudnn-7-3-and-build-tensorflow-gpu-from-source-on-ubuntu-18-04-3daf720b83fe) done by another users to make it work.

**Comment by weiji14** [comment]
See also #22664 if you're having problems compiling Tensorflow 1.11.0 with CUDA 10.0

**Comment by artificial-mind** [comment]
Hi @ymodak ,

Thankyou so much. It worked.

**Comment by ymodak** [comment]
Happy to help :-)

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
