### ISSUE TITLE
Second order derivative not supported for LRN (tf.nn.lrn)

### ISSUE THREAD

**Issue by vipinpillai** [tensorflow/tensorflow#22825]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: binary 
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:  CUDA 9.0, cuDNN - 7
- **GPU model and memory**: Titan X
- **Exact command to reproduce**:

### Describe the problem
I have a network architecture which has a LRN layer (tf.nn.lrn). I am using the same network definition from the CIFAR 10 tutorial: https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10.py .
I have a loss term which involves the gradient of the cross entropy loss with respect to the input. This throws an error during graph construction:
LookupError: No gradient defined for operation 'gradients/norm1_grad/LRNGrad' (op type: LRNGrad)

### Source code
I have reused the same code from the CIFAR10 tutorial with minimal change to the loss function.
I have modified the loss function to have an additional term which penalizes the L2 norm of the gradient of the cross entropy loss with respect to the input.
Following is the change to the loss function made to the cifar10.py from the tutorial.
```python
def loss(images, logits, labels):
  """Please note that the caller needs to feed the input images as well.
  Args:
    images: Input images to be used for gradient computation
    logits: Logits from inference().
    labels: Labels from distorted_inputs or inputs(). 1-D tensor
            of shape [batch_size]
  Returns:
    Loss tensor of type float.
  """
  labels_onehot = tf.one_hot(labels, depth=10, off_value=0.0, on_value=1.0, dtype=tf.float32)
  cross_entropy = tf.nn.softmax_cross_entropy_with_logits(
      labels=labels_onehot, logits=logits, name='cross_entropy_per_example')
  cross_entropy_mean = tf.reduce_mean(cross_entropy, name='cross_entropy')
  
  cross_entropy_grads, = tf.gradients(cross_entropy_mean, images)
  xent_grad_norm = tf.nn.l2_loss(cross_entropy_grads)

  tf.add_to_collection('losses', cross_entropy_mean)
  tf.add_to_collection('losses', xent_grad_norm)

  return tf.add_n(tf.get_collection('losses'), name='total_loss')
```
### Logs:
```
Traceback (most recent call last):
  File "/home/vipin/anaconda3/envs/py36-tf1.11.0-test/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 730, in _GradientsHelper
    grad_fn = ops.get_gradient_function(op)
  File "/home/vipin/anaconda3/envs/py36-tf1.11.0-test/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2460, in get_gradient_function
    return _gradient_registry.lookup(op_type)
  File "/home/vipin/anaconda3/envs/py36-tf1.11.0-test/lib/python3.6/site-packages/tensorflow/python/framework/registry.py", line 93, in lookup
    "%s registry has no entry for: %s" % (self._name, name))
LookupError: gradient registry has no entry for: LRNGrad

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
..............................................
..............................................
  File "/home/vipin/anaconda3/envs/py36-tf1.11.0-test/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 596, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/home/vipin/anaconda3/envs/py36-tf1.11.0-test/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 734, in _GradientsHelper
    (op.name, op.type))
LookupError: No gradient defined for operation 'gradients/norm1_grad/LRNGrad' (op type: LRNGrad)
```

**Comment by wt-huang** [comment]
@vipinpillai Second order derivative should be supported for LRN (tf.nn.lrn). I ran the above code snippet without running into any errors.

**Comment by vipinpillai** [comment]
@wt-huang Could you please share the full code snippet that you had used? 
I have verified this on multiple versions of tensorflow including 1.11.0 and it gave the error that I has posted. Which TF version did you use to check this issue?

**Comment by wt-huang** [comment]
@vipinpillai The code I used is the same as above with modification to cross entropy. I used TensorFlow nightly and 1.12.0-rc0, both worked.

**Comment by vipinpillai** [comment]
@wt-huang I was able to reproduce the bug on tf-nightly and python 3.6.
I have attached the 2 files which contain the minimal changes to reproduce the issue. 
To summarize the changes, I have edited the function loss in cifar10_lrn.py to take an argument for input images and added an additional loss term which is the L2 norm of the gradients of the cross entropy with respect to the input images. 
Could you please use the attached code to reproduce the issue at your end?

[cifar10_lrn_bug.zip](https://github.com/tensorflow/tensorflow/files/2480487/cifar10_lrn_bug.zip)

**Comment by wt-huang** [comment]
@vipinpillai The issue lies in `tf.gradients(cross_entropy_mean, images)`. Images used here is a 4D tensor that needs to be preprocessed before feeding into `tf.gradients`. You can probably leverage tf.image.image_gradients(image) to some extent.

**Comment by vipinpillai** [comment]
@wt-huang I don't think you have quite understood the issue here. `tf.image.image_gradients(image)` will merely give gradients for the image itself, whereas I am trying to compute the gradient of the cross entropy loss with respect to the image.
Could you please clarify how you were able to execute the code snippet previously without errors since the snippet included `tf.gradients(cross_entropy_mean, images)`. Images used here is 4D tensor as is the standard practice and I have used the same preprocessing which is used in the CIFAR10 tutorial. I have made extremely minimal changes in the loss function to just add an additional term for L2 norm of the gradients of the cross entropy loss with respect to the input image.

**Comment by wt-huang** [comment]
@vipinpillai Yes, understood the issue, which is why I said to leverage  `tf.image.image_gradients` only to get some implementation ideas. There are other alternatives as well. Previously executed the code you provided inside the issue without running into error, which is different from the zip file. 
Absolutely, images used as 4D tensor is standard practice, but feeding into tf.gradients directly is a different story. Please refer to [`tf.gradients`.](https://www.tensorflow.org/api_docs/python/tf/gradients).

**Comment by vipinpillai** [comment]
@wt-huang `tf.gradients` only mentions that the xs should be a tensor. I was expecting the `tf.gradients` to be working across any nodes in the graph as long as they were tensors and were connected. 
Could you please clarify as to why `tf.nn.lrn` is not working as expected since automatic differentiation should allow computation of higher order gradients?

**Comment by wt-huang** [comment]
@vipinpillai `tf.gradients(cross_entropy_mean, arg1)` returns the gradient of cross_entropy_mean with respect to each tensor in arg1. You would need to define the shape for arg1 such that its elements are included in `cross_entropy_mean`. Also, the LHS should match with the arg1 shape as well.

After fixing `tf.gradients(cross_entropy_mean, arg1)`, you should be able to use `tf.nn.lrn` to get the gradient for lrn as per PR [13987](https://github.com/tensorflow/tensorflow/pull/13987).

**Comment by vipinpillai** [comment]
@wt-huang In the API `tf.gradients(cross_entropy_mean, arg1)` , arg1 can be a list of tensors or simply a tensor. There is no restriction on the dimensionality of the _arg1_ tensor as long as the tensor is connected to _cross_entropy_mean_ in the graph. Could you please clarify as to what exactly do you mean by:
> You would need to define the shape for arg1 such that its elements are included in cross_entropy_mean.

There is no restriction anywhere in the `tf.gradients` method as to the LHS shape to match with arg1. 

Also, I don't exactly understand as to what you mean by 
> After  fixing `tf.gradients(cross_entropy_mean, arg1)`.

What should be fixed here? Is it not possible to take a simple gradient of the loss with respect to the input? The important point to note here is that there is no error if we don't use `tf.nn.lrn` suggesting that the problem lies in the underlying implementation of `tf.nn.lrn` itself.

**Comment by vipinpillai** [comment]
@skye @aselle Could you please take a quick look at this issue?

**Comment by skye** [comment]
I'm not very familiar with tf.nn.lrn, but it appears that the LRN op has a custom kernel for its gradient computation, LRNGrad. The LRNGrad op doesn't have a gradient defined, which is why you can't take the second derivative.

I'm gonna mark this contributions welcome for now, since someone needs to implement the LRNGrad gradient function to address this. @ebrevdo @martinwicke do you know if anyone on the TF team owns/knows about LRN + LRNGrad?

**Comment by ebrevdo** [comment]
@rryan might.

**Comment by vipinpillai** [comment]
Thanks @skye . 
I would be happy to contribute if given some hints to proceed with the required changes.
Do I need to add an additional GradGrad op?

**Comment by skye** [comment]
Yes exactly. You would register an LRNGradGrad op here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/nn_ops.cc#L684

And then implement the kernel here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/lrn_op.cc

And then register a Python gradient function here: http://go/gh/tensorflow/tensorflow/blob/master/tensorflow/python/ops/nn_grad.py#L579

I'm not familiar with the specifics of LRN, so I can't really give more context than that. It looks like the current LRN kernels are pretty fancy so this might be tricky, although it's possible you can make a simpler GradGrad kernel that's not as performant but still works.

Alternatively, you can possibly implement the gradient entirely in the Python gradient function using lower-level ops (i.e. create the grad grad computation using the standard TF API). This would have the advantage that it could in turn be differentiated (assuming you use ops that have gradients defined), and might be easier to implement.

Please let me know if you have any questions!

**Comment by ashutosh96** [comment]
I've run into the same problem. @vipinpillai Can you please share if you were able to solve the issue?

**Comment by vipinpillai** [comment]
@ashutosh96 No, I moved to PyTorch more than a year ago and higher order gradients are fully supported in PyTorch.
