### ISSUE TITLE
Win10 C++ TF1.9, error LNK2001, build by bazel  !

### ISSUE THREAD

**Issue by EdwardVincentMa** [tensorflow/tensorflow#22826]
I have generated the TensorFlowV1.9's .so and .lib file successfully on Win10,  but when I use this in VS2017, it has errors as bellow :

MFCTestTF1.9.obj : error LNK2001: 无法解析的外部符号 "char const * __cdecl tensorflow::core::GetVarint32PtrFallback(char const *,char const *,unsigned int *)" (?GetVarint32PtrFallback@core@tensorflow@@YAPBDPBD0PAI@Z)
1>D:\ProgramData\VS2017 Project\MFCTestTF1.9\Release\MFCTestTF1.9.exe : fatal error LNK1120: 1 个无法解析的外部命令
1>已完成生成项目“MFCTestTF1.9.vcxproj”的操作 - 失败。

And I also build TensorFlowV1.8 with CMAKE, it work OK without LNK error.  But V1.9 can not build by CMAKE.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment]
@EdwardVincentMa Try to use VS2015 as shown in the [installation document](https://www.tensorflow.org/install/source_windows). Please let us know if you run into any errors. You should be able to install TensorFlow 1.10 with Cmake.

**Comment by wt-huang** [comment]
Closing this now, feel free to reopen if problem persists.

**Comment by ttdd11** [comment]
@EdwardVincentMa How did you fix this link error?
