### ISSUE TITLE
aws: tensorflow_model_server: /lib64/libm.so.6: version `GLIBC_2.23' not found

### ISSUE THREAD

**Issue by xianqian1** [tensorflow/tensorflow#22828]
Hi team, 

I am trying to build tensorflow_model_server from source, I follow https://www.tensorflow.org/serving/setup and finish the building step. 

But when I run it, I get the error message:

```
bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server

bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server)
```

The platform is Amazon Linux 14, 
gcc (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)

I am trying to build glibc 2.23 to get libm.so, but can not configure

```
loading cache ./config.cache
checking host system type... x86_64-unknown-linux-gnu
checking sysdep dirs... configure: error: The x86_64 is not supported.
```

Any idea? Thanks!

**Comment by xianqian1** [comment]
self addressed:

There are two versions of libm.so.6 in my aws ec2 instance. Since ec2 is a virtual machine, so the binary is built within the virtual environment using glibc 2.23 version and when running outside the virtual environment, it can not find that version. 

What i do is to find that version:

```
sudo find / -name "libm.so.6"

/var/lib/docker/overlay2/422e54cc5ac5921a6d8f8db67f40162ea497cdcd0e6ebd22bd86ec39e55b8397/diff/lib/x86_64-linux-gnu/libm.so.6
/var/lib/docker/overlay2/fe4ce1d185e5ea59f770f70daf2d13bdbc78d26f5e48e541c3338dcea4ae835a/diff/lib/x86_64-linux-gnu/libm.so.6
/lib64/libm.so.6
/home/ec2-user/anaconda3/pkgs/gcc_impl_linux-64-7.3.0-habb00fd_1/x86_64-conda_cos6-linux-gnu/sysroot/lib/libm.so.6
/home/ec2-user/anaconda3/pkgs/gcc_impl_linux-64-7.2.0-habb00fd_3/x86_64-conda_cos6-linux-gnu/sysroot/lib/libm.so.6
/home/ec2-user/anaconda3/envs/tensorflow_p36/x86_64-conda_cos6-linux-gnu/sysroot/lib/libm.so.6
/home/ec2-user/anaconda3/envs/theano_p36/x86_64-conda_cos6-linux-gnu/sysroot/lib/libm.so.6
/home/ec2-user/anaconda3/envs/theano_p27/x86_64-conda_cos6-linux-gnu/sysroot/lib/libm.so.6
/home/ec2-user/anaconda3/envs/tensorflow_p27/x86_64-conda_cos6-linux-gnu/sysroot/lib/libm.so.6
```

then check version for each libm:

```
strings /var/lib/docker/overlay2/422e54cc5ac5921a6d8f8db67f40162ea497cdcd0e6ebd22bd86ec39e55b8397/diff/lib/x86_64-linux-gnu/libm.so.6  | grep GLIBC_

GLIBC_2.2.5
GLIBC_2.4
GLIBC_2.15
GLIBC_2.18
GLIBC_2.23
GLIBC_PRIVATE
```

this is the version i need, and then add it to an existing ld_library_path:

```
sudo cp /var/lib/docker/overlay2/422e54cc5ac5921a6d8f8db67f40162ea497cdcd0e6ebd22bd86ec39e55b8397/diff/lib/x86_64-linux-gnu/libm.so.6 /lib/
```

Then tensorflow_server works

**Comment by KeremTurgutlu** [comment]
In my case for swift for tensorflow, GLIBC_2.27 is needed. I've checked every single libm.so.6 file but none of seem to have GLIBC_2.27. What can be done in this case?

**Comment by MiroFurtado** [comment]
+1 on the above issue - I can't find GLIBC_2.27

**Comment by bhavints** [comment]
Any updates?

**Comment by weishengchong** [comment]
Hi @KeremTurgutlu, @MiroFurtado , @bhavints,
I have the same issue. Would you please share your solution/update if any? Thanks!

My system infor
ubuntu16.04
tf1.9
rk3399 board

`
./label_image: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./label_image)
(tf1.13) root@firefly:/usb/tf/rk_tf1.9_label_image# strings /usr/lib/aarch64-linux-gnu/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBC_2.17
GLIBC_2.18
GLIBCXX_DEBUG_MESSAGE_LENGTH
`

**Comment by imrankh46** [comment]
Hi, I'm trying to deploy model with tf serving in colab but they give me this error.

tensorflow_model_server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by tensorflow_model_server)

tensorflow_model_server: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by tensorflow_model_server)

tensorflow_model_server: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by tensorflow_model_server)

Any suggestions!!!
