### ISSUE TITLE
Can GANEstimator execute a forward pass in the discriminator after training?

### ISSUE THREAD

**Issue by alain-sam** [tensorflow/tensorflow#22832]
Hi, 

I am looking at GANEstimator and am trying to pass a new data point `X` to `discriminator_fn`. I have a class `GAN` that has an attribute `self.model = tfgan.estimator.GANEstimator(...)`. Is there a way to do this? It looks like for now, there is a session problem (in order to have something like `sess.run([self.discriminator_fn(X)])`).

Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by alain-sam** [comment]
Hi,
Yes, I have custom code, TensorFlow 1.11 from Anaconda, GPU: Tesla V100.

**Comment by wt-huang** [comment]
@alain-sam It is much easier to use TFGAN than GANEstimator as the latter is canned estimator. You can write your own model_fn and feed new data. Please refer to [TFGAN](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/gan) for details.

**Comment by wt-huang** [comment]
Closing this, feel free to reopen if running into any errors.
