### ISSUE TITLE
conv.cc:260 real_multiplier < 1.0 was not true.Node 0 failed to prepare.

### ISSUE THREAD

**Issue by Heetmadhu** [tensorflow/tensorflow#22831]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 14.0.4
- **Mobile device if the issue happens on mobile device**: MI 3s Prime
- **TensorFlow installed from (source or binary)**: pip install
- **TensorFlow version (use command below)**: 1.9.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.16
- **CUDA/cuDNN version**: 8
- **GPU**: Nvidia GeForce GTX 1080 Ti
- **Exact command to reproduce**:
bazel-bin/tensorflow/contrib/lite/toco/toco --input_file=tflite_graph.pb --output_file=detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --inference_type=QUANTIZED_UINT8  --mean_values=128 --std_dev_values=128 --allow_custom_ops

### Problem
App gets crashed while loading model with following error.

### logs
Caused by: java.lang.NullPointerException: Internal error: Cannot allocate memory for the interpreter: tensorflow/contrib/lite/kernels/conv.cc:260 real_multiplier < 1.0 was not true.Node 0 failed to prepare.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
CUDA/cuDNN version
GPU model and memory

**Comment by Heetmadhu** [comment]
Updated

**Comment by shashishekhar** [comment]
@Heetmadhu : Can you attach the model that you are trying to convert.
