### ISSUE TITLE
Compiling tensorflow 1.10.0 in mingw-w64(msys2 32bit)

### ISSUE THREAD

**Issue by smalltalkman** [tensorflow/tensorflow#22840]
After patching some code(mostly in cmake), I have compiled successfully tensorflow 1.10.0 in mingw-w64(msys2 32bit). Although some unit test not passed, I think some code should be commit to master. So now what should i do?
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: win7 32bit
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 2.7.15
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: gcc with mingw-w64(msys2 32bit)
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
### Describe the problem
For some reasons, i need to using tensorflow in mingw-w64. 
After patching some code(mostly in cmake and little in header files), I have compiled successfully tensorflow source 1.10.0 in win7 mingw-w64(msys2 32bit) with cmake. 
Although some unit test not passed, I think some code should be commit to master to check. 
I think this patchs could make a mingw-w64 port.
Because i never use github to commit code, so i want to know how should i commit this patchs to master to check?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by smalltalkman** [comment]
Has been solved by stackoverflow

**Comment by ymodak** [comment]
Can you please ppst the link of stackoverflow for this issue? It will help us to guide users who may run into similar issue. Thanks!

**Comment by smalltalkman** [comment]
[compiling-tensorflow-1-10-0-in-mingw-w64msys2-32bit](https://stackoverflow.com/questions/52714317/compiling-tensorflow-1-10-0-in-mingw-w64msys2-32bit)

The patch for mingw-w64-tensorflow is at [mingw-w64-tensorflow](https://github.com/smalltalkman/mingw-w64-tensorflow). PKGBUILD shows all my compile steps.

**Comment by mammaiap** [comment]
@smalltalkman , i am trying to build the tensorflow using mingw-w64 on  windows 10 ...  i need the tensorflow c++ lib which i wanted to use it in mingw-w64 based projects... can you please help me , how to do the cmake with mingw-w64 to get compile successfully.

**Comment by smalltalkman** [comment]
@mammaiap 
> @smalltalkman , i am trying to build the tensorflow using mingw-w64 on windows 10 ... i need the tensorflow c++ lib which i wanted to use it in mingw-w64 based projects... can you please help me , how to do the cmake with mingw-w64 to get compile successfully.

Sorry, replied very late.
If you need `tensorflow c++ lib`, you can refer to the patch in [mingw-w64-tensorflow] (https://github.com/smalltalkman/mingw-w64-tensorflow).
Alternatively, reference may be made to [mingw-w64-tensorflow-1.10.0-cmake] (https://github.com/smalltalkman/mingw-w64-tensorflow-1.10.0-cmake).
`mingw-w64-tensorflow-1.10.0-cmake` is mainly used to build `python` applications， currently no perfect `C++` lib.

**Comment by Haffon** [comment]
@smalltalkman the stackoverflow link page not found. should we run PKGBUILD in msys2 shell?
