### ISSUE TITLE
Is Tensorflow Distributed Model supporting NCCL 2.0 inter-node AllReduce features?

### ISSUE THREAD

**Issue by ghostplant** [tensorflow/tensorflow#22842]
Hi, allow me to ask for a question about Tensorflow feature:

Firstly, I uses the nearly-latest Tensorflow version v1.10 and the system has NCCL 2.0 installed.

As is known that NCCL 2.0 has already supported Cross-Node multiple GPU training with fully NCCL management, but I found that Tensorflow benchmark script doesn't support NCCL in Tensorflow distributed mode, and it said NCCL mode is only allowed and designed for in single-node mode, so I don't know whether it is not supported by Tensorflow engine, or just not supported by the Tensorflow benchmark script? If it is just not implemented by the Tensorflow benchmark script, is there documentation or example to enable Distributed Tensorflow to use NCCL 2.0 to manage cross-node Multi GPUs? Thanks.

The official Tensorflow benchmark:
https://github.com/tensorflow/benchmarks

**Comment by byronyi** [comment]
I will suggest you to use uber/horovod, which uses NCCL and MPI for inter-node all reduce.

AFAIK, the TF team resists from using NCCL for inter-node GPU training, and perhaps the reason is simply because that we need to support non-NVidia GPU (ROCm was recently supported) for inter-node training as well.

**Comment by ppwwyyxx** [comment]
Duplicate question of #20447

**Comment by ymodak** [comment]
Please refer to the discussion on another thread as mentioned below.
> Duplicate question of #20447

**Comment by ghostplant** [comment]
@ymodak So is it not a plan for Tensorflow to support this just as byronyi said?

**Comment by byronyi** [comment]
To be more constructive, please submitting PR to support new features, not duplicated issues.
