### ISSUE TITLE
tensorflow `resize_image_with_crop_or_pad` for whole batch

### ISSUE THREAD

**Issue by ziky90** [tensorflow/tensorflow#2284]
Currently there exists `tensorflow.image.resize_image_with_crop_or_pad()` that works well, but for me it would be very beneficial to have also something that would be able to perform crop on whole batch of images or even conv2d or conv2d_transpose outputs.

In other words it should work on Tensor of shape `[batch, height, width, channels]`.

So far I have found this mentioned here http://stackoverflow.com/questions/33944683/tensorflow-map-operation-for-tensor

And for now I'd probably go with the `tf.while_loop`, but general built in function in tensorflow would be helpful.

**Comment by mrry** [comment]
If you have a batch of images in a `[batch, height, width, channels]`, can't you just use `tf.slice()` to crop the whole batch?

**Comment by girving** [comment]
Closing for now, since slice does seem to be a good solution.  @ziky90: Please comment if slice doesn't fit your use case.

**Comment by cancan101** [comment]
@mrry How would you use slice to accomplish this?

**Comment by mrry** [comment]
@cancan101 Assuming the crop region should be at the same location in each image, you would just take `images[:, y_start:y_end, x_start:x_end, :]` where `x_start`, `x_end`, `y_start`, and `y_end` define the corners of the crop region.

**Comment by cancan101** [comment]
okay, but then need to copy over logic like:
```python
  width_diff = target_width - width
  offset_crop_width = max_(-width_diff // 2, 0)
  offset_pad_width = max_(width_diff // 2, 0)

  height_diff = target_height - height
  offset_crop_height = max_(-height_diff // 2, 0)
  offset_pad_height = max_(height_diff // 2, 0)
...
```
to get those values.

**Comment by mrry** [comment]
Sure, but you don't need to use a `tf.while_loop()`, which was suggested in the original issue.

I don't feel strongly either way adding such a function in `image_ops.py`... feel free to open a new issue with the proposed interface if you'd like!
