### ISSUE TITLE
tf.keras.Model overrides 'self' behaviour with lists

### ISSUE THREAD

**Issue by jpatts** [tensorflow/tensorflow#22853]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04.1 LTS
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
N/A
- **TensorFlow installed from (source or binary)**:
pip3 install tensorflow-gpu
- **TensorFlow version (use command below)**:
v1.11.0-0-gc19e29306c 1.11.0
- **Python version**:
Python 3.6.5
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
V9.0.176
- **GPU model and memory**:
GTX 1070, 6GB VRAM
- **Exact command to reproduce**:
python3 codebelow.py

### Describe the problem
I am not familiar with ListWrapper(), but it is being applied to all list variables created with self when my class inherits from tf.keras.Model. This is bad because it is causing an IndexError when I use it in certain functions, or even by just passing it through my Tensorflow model (I am using eager execution). I don't know whether this is a bug or if it is intended, but if this is supposed to happen, I think documentation should be added to explain this at https://www.tensorflow.org/api_docs/python/tf/keras/models/Model. I have included a smallest working example below.

### Source code / logs
Code:

```
import tensorflow as tf

class my_class(tf.keras.Model):

    def __init__(self):
        super(my_class, self).__init__()

        self.x = [0]
        print(self.x)

model = my_class()
```

Output:
`ListWrapper([0])`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Mobile device

**Comment by allenlavoie** [comment]
Could you be more specific about the issue it's causing? List wrappers are used to support restore on create for variables.

**Comment by jpatts** [comment]
With more investigation, `tf.enable_eager_execution` appears to be involved as well. I believe this to be a compatibility issue with `tf.keras.Model` and `tf.enable_eager_execution`. I am unable to pass data contained within a ListWrapper() into my model, as well as in other functions, while both of those are present.
The following code runs without issue:
```
import tensorflow as tf

class my_class(object):

    def __init__(self):
        super(my_class, self).__init__()

        self.model = tf.keras.layers.Dense(3)
        # Specify input size
        self.model.build((32, 32, 1))
    
    def forward(self):
        image = tf.zeros((32, 32, 1))
        self.images = []
        self.images.append(image)
        self.model(self.images)

model = my_class()
model.forward()
```
Adding tf.enable_eager_execution() OR tf.keras.Model does not break this program.
However, adding tf.enable_eager_execution() AND tf.keras.Model causes an ugly error:
```
import tensorflow as tf

tf.enable_eager_execution()

class my_class(tf.keras.Model):

    def __init__(self):
        super(my_class, self).__init__()

        self.model = tf.keras.layers.Dense(3)
        # Specify input size
        self.model.build((32, 32, 1))
    
    def forward(self):
        image = tf.zeros((32, 32, 1))
        self.images = []
        self.images.append(image)
        self.model(self.images)

model = my_class()
model.forward()
```
```
2018-10-12 18:17:23.199858: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-12 18:17:23.394365: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 5.87GiB
2018-10-12 18:17:23.394407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-10-12 18:17:23.630373: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-12 18:17:23.630403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2018-10-12 18:17:23.630410: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2018-10-12 18:17:23.630591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5641 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    model.forward()
  File "test.py", line 18, in forward
    self.model(self.images)
  File "/home/jpatts/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 769, in __call__
    outputs = self.call(inputs, *args, **kwargs)  File "/home/jpatts/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 936, in call
    inputs = ops.convert_to_tensor(inputs, dtype=self.dtype)
  File "/home/jpatts/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1048, in convert_to_tensor
    as_ref=False)
  File "/home/jpatts/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1144, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/jpatts/.local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 971, in _autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "/home/jpatts/.local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 893, in _autopacking_helper
    return gen_array_ops.pack(list_or_tuple, name=name)
  File "/home/jpatts/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4713, in pack
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: OpKernel 'Pack' has constraint on attr 'T' not in NodeDef '{{node Pack}} = Pack[N=0, axis=0]()', KernelDef: 'op: "Pack" device_type: "GPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } } host_memory_arg: "values" host_memory_arg: "output"' [Op:Pack] name: packed
```

**Comment by allenlavoie** [comment]
Makes sense, presumably we have a PyList_CheckExact or equivalent somewhere in TFE_Py_Execute. I can reproduce and will see about a fix.

**Comment by allenlavoie** [comment]
Thank you for the report. The pack error should be fixed now, but please let me know if there are other issues around tracking/ListWrapper.

**Comment by allenlavoie** [comment]
@2649 to be clear, the existence of ListWrappers is intended behavior. Them causing problems is a bug. Are they causing issues?

**Comment by Danmou** [comment]
@allenlavoie I ran into the problem that adding a `ListWrapper` and `TensorShape` results in the error `TypeError: 'TensorShape' object does not support item assignment`. Explicitly converting either of the two objects to a list works fine, but it's a bit confusing behavior. Not sure why `ListWrapper` would try to modify the object you're adding with it.

**Comment by allenlavoie** [comment]
@Danmou thanks for the report. I've sent a fix for review; I think we can just be more lazy about re-wrapping the result of operators in ListWrapper.

**Comment by n4ndoz** [comment]
Just reporting: as of 2021, using TF version 2.4.1 (stable) and ran into the same issue. My code, while different, uses the same dynamic of feeding options as a list (of dicts, actually). And the code won't recognize. My setting and settings are:
OS: Ubuntu 20.04
TF_version: 2.4.1
Eager_Mode: activated by default (i'm using it to debug my custom layers)
IDE: (docker)Jupyter Notebook
Container: tensorflow/tensorflow:2.4.1-gpu-jupyter

I was able to model the layer without the options as list, but it was a tedious process, the code became unreadable but works. I need this possibility to configure my layer with a list since I will be feeding all those layers and stuff to a Genetic Algorithm to optimize my topology. Would love a solution.

**Comment by allenlavoie** [comment]
@n4ndoz eager execution doesn't change the `self.foo = list(...)` behavior. I'd file another bug with a reproduction.

**Comment by n4ndoz** [comment]
@allenlavoie I actually ended up solving this issue refactoring my code, is it good to delete the comment? (I'm actually pretty noob on the GitHub etiquette)

**Comment by janmarxen** [comment]
> @2649 to be clear, the existence of ListWrappers is intended behavior. Them causing problems is a bug. Are they causing issues?

When I use dask and my custom models (when subclassing) are being serialized/deserialized, the error Exception: TypeError("can not serialize '_DictWrapper' object") is thrown. Are these wrappers not serializable?
