### ISSUE TITLE
Tensorflow C API: SessionRun batch size (how to properly set)

### ISSUE THREAD

**Issue by EnricoGiordano1992** [tensorflow/tensorflow#22869]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: no
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.16.1
- **GCC/Compiler version (if compiling from source)**: 7.3.0
- **CUDA/cuDNN version**: 9.2 / 7.3
- **GPU model and memory**: Nvidia GTX 1070ti

Dear sirs,
I am struggling to find the correct way to properly set the batch size for a SessionRun call in the C API. 
What I am trying to do is passing multiple images in a single SessionRun to a CNN (VGG16).
I am wondering which is the correct way to do so and to retrieve the appropriate correlated output values.
I have also come to believe that a single SessionRun call can only accept a single image as an input, so a proper batched input could only be achieved by having multiple SessionRun calls (for an example inside a "for" loop) with a single image each. Am I correct? Is there not a way to batch multiple images inside a single SessionRun call for a single-input CNN?

I have searched thoroughly your documentation but I could not find any evidence of a proper indication on how to do it.

Best regards

**Comment by sabhiram** [comment]
The `session.run` executes a graph. A graph may have any number of input images as part of it's input pipeline.  Typically you will use the `tf.data.Dataset`API to define your data input layer as well as decide on appropriate batch sizes for your model.

Folks will probably ask you to post this on something like stackoverflow as this is probably not best asked here :)

**Comment by EnricoGiordano1992** [comment]
I really need help with this question, because it is blocking for my work (and I did not find any advice in the documentation).

I have tried these pseudo-code: (calling these code SISO = Single Input Single Output, and MIMO = Multiple Input Multiple Output, the input is batch_size * 50 * 50 * 3, in SISO batch_size = 1, in MIMO batch_size = 3; remember that I am using VGG16 graph)

SISO:
```
loadGraph()
TF_NewSession()
TF_AllocateTensor( 1 * 50 * 50 * 3)
// copy data into tensor
num_bytes = rows() * cols() * channels() * sizeof(float);
memcpy(tensor_data, img_data, num_bytes)
TF_SessionRun()
data = static_cast<float*>(TF_TensorData(output_tensor));
// data[0] = frame number
// data[1] = probabily of prediction
out = (data[1] > 0.5f) ? true : false;
```

for SISO, I have always the right output.

MIMO:
```
loadGraph()
TF_NewSession()
TF_AllocateTensor( 3 * 50 * 50 * 3)
// copy data into tensor
num_bytes = rows() * cols() * channels() * sizeof(float);
offset = 0;
for(size_t i = 0; i < 3; ++i)
{
   memcpy(tensor_data + offset, imgs_data[i], num_bytes);
   offset += num_bytes;
}
TF_SessionRun()
data = static_cast<float*>(TF_TensorData(output_tensor));
offset = 0;
num_bytes = 2 * sizeof(float);
// data[i] = frame number
// data[i+1] = probabily of prediction
for(size_t i = 0; i < 3; ++i)
    {
        out[i] = (*(data + offset + 1) > 0.5f) ? true : false;
        offset += num_bytes;
    }
```

for MIMO, only the first classification output value is right, the other ones are random numbers.

what is wrong with this code?

**Comment by wt-huang** [comment]
@EnricoGiordano1992 shouldn't you use `data[i+1]` in this line:
```
out[i] = (*(data + offset + 1) > 0.5f) ? true : false;
```

**Comment by EnricoGiordano1992** [comment]
@wt-huang it seems that something changed, but I have wrong outputs.

What about input tensor setting? What is wrong?

```
    uint8_t * tensor_data = static_cast<uint8_t *>(TF_TensorData(input_tensor));
    const size_t num_bytes = rows() * cols() * channels() * sizeof(float); // 50 * 50 * 3 * 4
    size_t offset = 0;
    for(size_t i = 0; i < batch_sz; ++i)
    {
        std::memcpy((tensor_data + offset), actual_in.at(i).data, num_bytes);
        offset += num_bytes;
    }
```

**Comment by EnricoGiordano1992** [comment]
any suggestions?

**Comment by soumilchugh** [comment]
any update on this?

**Comment by serop96** [comment]
any update on this? it is also pending for my work

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
