### ISSUE TITLE
Tf keras functional model with tf dataset input

### ISSUE THREAD

**Issue by xinyu-Naturali** [tensorflow/tensorflow#22862]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
no
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.11
- **Python version**:
3.5.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
I'm new to tensorflow keras and dataset. Can anyone help me understand why the following code doesn't work?

    import tensorflow as tf
    import tensorflow.keras as keras
    import numpy as np
    from tensorflow.python.data.ops import dataset_ops
    from tensorflow.python.data.ops import iterator_ops
    from tensorflow.python.keras.utils import multi_gpu_model
    from tensorflow.python.keras import backend as K

    data = np.random.random((1000,32))
    labels = np.random.random((1000,10))
    dataset = tf.data.Dataset.from_tensor_slices((data,labels))
    print( dataset)
    print( dataset.output_types)
    print( dataset.output_shapes)
    dataset.batch(10)
    dataset.repeat(100)

    inputs = keras.Input(shape=(32,))  # Returns a placeholder tensor

    # A layer instance is callable on a tensor, and returns a tensor.
    x = keras.layers.Dense(64, activation='relu')(inputs)
    x = keras.layers.Dense(64, activation='relu')(x)
    predictions = keras.layers.Dense(10, activation='softmax')(x)

    # Instantiate the model given inputs and outputs.
    model = keras.Model(inputs=inputs, outputs=predictions)

    # The compile step specifies the training configuration.
    model.compile(optimizer=tf.train.RMSPropOptimizer(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

    # Trains for 5 epochs
    model.fit(dataset, epochs=5, steps_per_epoch=100)

It failed with the following error:

    model.fit(x=dataset, y=None, epochs=5, steps_per_epoch=100)
    File "/home/wuxinyu/pyEnv/lib/python3.5/site-packages/tensorflow/python/keras/engine/training.py", line 1510, in fit
    validation_split=validation_split)
    File "/home/wuxinyu/pyEnv/lib/python3.5/site-packages/tensorflow/python/keras/engine/training.py", line 994, in _standardize_user_data
    class_weight, batch_size)
    File "/home/wuxinyu/pyEnv/lib/python3.5/site-packages/tensorflow/python/keras/engine/training.py", line 1113, in _standardize_weights
    exception_prefix='input')
    File "/home/wuxinyu/pyEnv/lib/python3.5/site-packages/tensorflow/python/keras/engine/training_utils.py", line 325, in standardize_input_data
    'with shape ' + str(data_shape))
    ValueError: Error when checking input: expected input_1 to have 2 dimensions, but got array with shape (32,)

According to tf.keras guide, I should be able to directly pass the dataset to model.fit, as this example shows:

> # Input tf.data datasets

> Use the Datasets API to scale to large datasets or multi-device training. Pass a tf.data.Dataset instance to the fit method:

    # Instantiates a toy dataset instance:
    dataset = tf.data.Dataset.from_tensor_slices((data, labels))
    dataset = dataset.batch(32)
    dataset = dataset.repeat()

> # Don't forget to specify `steps_per_epoch` when calling `fit` on a dataset.
> model.fit(dataset, epochs=10, steps_per_epoch=30)
Here, the fit method uses the steps_per_epoch argument—this is the number of training steps the model runs before it moves to the next epoch. Since the Dataset yields batches of data, this snippet does not require a batch_size.

> Datasets can also be used for validation:

    dataset = tf.data.Dataset.from_tensor_slices((data, labels))
    dataset = dataset.batch(32).repeat()

    val_dataset = tf.data.Dataset.from_tensor_slices((val_data, val_labels))
    val_dataset = val_dataset.batch(32).repeat()

    model.fit(dataset, epochs=10, steps_per_epoch=30,
          validation_data=val_dataset,
          validation_steps=3)

What's the problem with my code, and what's the correct way of doing it?

**Comment by clck** [comment]
Hello!

Think you are missing one assignment step in your setup.
It is a subtle issue and has to do with how tf approaches data pipelines.
In your case it has to do with the way transforms are chained together.

For example in these lines of your code:

```
dataset.batch(10)
dataset.repeat(100)
```

You call the batch and repeat operations yet never assign them.
This creates a new Dataset object, and then just throws it away.
It also why you see that dimension error since the dataset that is passed to `fit()` only yields single examples with no batch dimension.


You want to do the same as the examples and assign the new dataset. 
There are a couple of options:

```
dataset = dataset.batch(10)
dataset = dataset.repeat(100)
```

or 

```
dataset = dataset.batch(10).repeat(100)
```

Hope this helps!

**Comment by xinyu-Naturali** [comment]
It works.  Thank you very much.
