### ISSUE TITLE
Why resize_image_with_crop_or_pad require fully defined image?

### ISSUE THREAD

**Issue by ziky90** [tensorflow/tensorflow#2286]
I would like to ask, why `tensorflow.image.resize_image_with_crop_or_pad` require fully defined image? Wouldn't it be better to have some function that is more general and that can handle dynamically created tensor?

I am currently playing with this function and I would like to use it for not fully defined Tensors.

Is there some plan to implement some more complex `crop_tensor` function that would work with dynamic tensors? And that would possibly be able to handle https://github.com/tensorflow/tensorflow/issues/2284

**Comment by girving** [comment]
I'm going to merge this thread into the extremely related #1029.  We'd be happy to accept PRs for either one.
