### ISSUE TITLE
Dataset.shuffle gives same order with any seed if reshuffle_each_iteration=False

### ISSUE THREAD

**Issue by SiLiKhon** [tensorflow/tensorflow#22871]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OS X 10.11.6
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary (anaconda)
- **TensorFlow version (use command below)**: b'unknown' 1.10.0
- **Python version**:
Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:07:29) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
in python interactive session

```
>>> op1 = tf.data.Dataset.from_tensor_slices(list(range(100))).shuffle(100, seed=0, reshuffle_each_iteration=False).repeat().make_one_shot_iterator().get_next()
>>> op2 = tf.data.Dataset.from_tensor_slices(list(range(100))).shuffle(100, seed=1, reshuffle_each_iteration=False).repeat().make_one_shot_iterator().get_next()
>>> sess = tf.InteractiveSession()
2018-10-10 18:56:24.996286: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
>>> sess.run([op1, op2])
[85, 85]
>>> sess.run([op1, op2])
[1, 1]
>>> sess.run([op1, op2])
[54, 54]
```

One can see that op1 and op2 fetch elements in same order. If reshuffle_each_iteration is set to True, the element order is different as expected. I believe different seed values should result in different element order for op1 and op2, no matter what the value of reshuffle_each_iteration is.

**Comment by mrry** [comment]
Thanks for reporting this. We just noticed this bug in the last few days, and the fix is in 4ff7b81514ea1b86295bc74b620e3c1d3e127e6f.
