### ISSUE TITLE
[TensorRT] use op_name as op_type_name.

### ISSUE THREAD

**Issue by qiaohaijun** [tensorflow/tensorflow#22887]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: None
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: centos 7.2
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: None
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:  0.16.1
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: cudnn 7.0.4
- **GPU model and memory**: p40 & 20GB
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem

1. run tensorflow 1.11.0 with tensorrt 4.0.6.
2. TRTEngineOp is registered. 
3. I find the tf  use `op_name` as `op_type_name`.

```
Not found: Op type not registered 'TitleLSTM/my_trt_op_2_native_segment' in binary
```
I think  'TitleLSTM/my_trt_op_2_native_segment' is a op_name, this op's type is 'TRTEngineOp'

### Source code / logs
2018-09-30 17:23:37.482200: I external/org_tensorflow/tensorflow/core/framework/op.cc:103] Not found: Op type not registered 'TitleLSTM/my_trt_op_2_native_segment' in binary running on jshd_40_73. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Comment by samikama** [comment]
@qiaohaijun step 3 is not clear to me. Can you describe what are you trying to do in a bit more detail?

**Comment by qiaohaijun** [comment]
@samikama ok
1. freeze `saved_model` to `freezed_model`
2. use `create_inference_graph` to covert `freezed_model` to `freezed_trt_model`
3. convert `freezed_trt_model` to `trt_saved_model` for tensorflow_serving
4. tf serving load the `trt_saved_model`

When the tensorflow serving is executed, an error occurs.
```
Not found: Op type not registered 'TitleLSTM/my_trt_op_2_native_segment' in binary
```

**Comment by qiaohaijun** [comment]
@samikama is it a bug or not?

**Comment by samikama** [comment]
@qiaohaijun this is not a bug in TFTRT, it is a bug in your script that converts TFTRT model to serving model. As error mentions 'TitleLSTM/my_trt_op_2_native_segment' is not an OP but it is a function. It looks like your serving conversion script can't handle functions.

**Comment by samikama** [comment]
@qiaohaijun , logs above seem correct to me. TRT optimization pass should not be run on function objects in the graph but current infrastructure runs all configured optimizers on all graph components thus TRT optimization pass is printing a warning about it. I don' t think problem is related with TFTRT or specific to conversion of a TRT optimized graph. It is more likely to be due to you conversion scripts ability to handle function objects in the graph. I expect it to fail similarly when more functional ops introduced in to the graphs. Perhaps you can try asking in TFServing forums, or you can take a look at https://github.com/NVIDIA/dl-inference-server which is similar and support TRT optimized graphs.

**Comment by qiaohaijun** [comment]
@samikama ok, thank you very much.
