### ISSUE TITLE
Error building on Windows // no such package '@flatbuffers

### ISSUE THREAD

**Issue by ivopivo** [tensorflow/tensorflow#22898]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: from source
- **TensorFlow version (use command below)**: 1.11
- **Python version**: 3.6.6
- **Bazel version (if compiling from source)**: 0.17.2
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
I followed the instructions from https://www.tensorflow.org/install/source_windows 
When I tried to make a cpu only build with the command
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

I get the error:

C:\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@flatbuffers//': C:/users/xxxx/_bazel_xxxx/xv6zejqw/external/flatbuffers/tests (Directory not empty)
INFO: Elapsed time: 106.904s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (246 packages loaded)

**Comment by arnaldog12** [comment]
Did you find a solution, @ivopivo? I'm facing the same issue.

**Comment by CalebGreer** [comment]
I am also having this error. Did you find a solution too @arnaldog12?
