### ISSUE TITLE
from __future__ import division gives error in word2vec_basic when dividing tensors.Just comment out "from __future__...."

### ISSUE THREAD

**Issue by arieltci** [tensorflow/tensorflow#229]

**Comment by girving** [comment]
Are you running a version of the tutorials from HEAD against tensorflow installed via pip or similar?  We just added `__truediv__` support as part of #1.

**Comment by arieltci** [comment]
Was running python 2.7......

**Comment by girving** [comment]
Yep, you're running 2.7, but how did you install tensorflow and where did you get the tutorial?  I think you might be running a newer version of the tutorial than tensorflow itself.

**Comment by arieltci** [comment]
I pip installed it but I run the tutorial from the repository after git fetched
it.


Sent with Mixmax

On Sun, Nov 15, 2015 at 7:44 PM, Geoffrey Irving < notifications@github.com > wrote:
Yep, you're running 2.7, but how did you install tensorflow and where did you
get the tutorial? I think you might be running a newer version of the tutorial
than tensorflow itself.

**Comment by girving** [comment]
@arieltci: For now, deleting that import is the right thing for you to do.  @vrv: Not sure if should close or remove that division from the tutorial so that it's more backwards compatible.

**Comment by girving** [comment]
I'm going to fix the tutorial in git to be compatible back to 0.5.0.

**Comment by girving** [comment]
Fixed, will be part of the next git commit.  Thanks for reporting!
