### ISSUE TITLE
We have removed this restriction. Please check out the code at head, or in the upcoming 1.4 RC. Please reopen if there are issues with it.

### ISSUE THREAD

**Issue by jg577** [tensorflow/tensorflow#22901]
_Originally posted by @martinwicke in https://github.com/tensorflow/tensorflow/issues/12367#issuecomment-335320352_

**Comment by wt-huang** [comment]
@jg577 You can use `SignatureDefs` to get around the restriction, refer to [`SignatureDefs` in SaveModel for TensorFlow Serving](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/signature_defs.md for more details.

**Comment by wt-huang** [comment]
Closing, feel free to reopen if problem persists.
