### ISSUE TITLE
why does sess.run()so slow on android?

### ISSUE THREAD

**Issue by neverPick** [tensorflow/tensorflow#2290]
I used retrain.py to retrain inception_v3 with my own images.It works will on pc with label_image.cc.It costs about 2-4s on android demo(just change the graph.pb) once sess.run().In original demo,it costs only 400ms?whats wase,the result always get wrong.I have no idea,why it works so slow?why the accuracy so low on android device?

**Comment by petewarden** [comment]
Sorry you're hitting problems! There are various changes you need to make to successfully run the Inception v3 model in the Android demo, including altering the mean and std values that the input images are scaled by. We don't have an example of this yet, but we'll track it in this bug.

**Comment by neverPick** [comment]
trying to build label_image:main.cc on Android...
