### ISSUE TITLE
RTX 2080 issue with Tensorflow

### ISSUE THREAD

**Issue by tejavoo** [tensorflow/tensorflow#22900]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NaN
- **TensorFlow installed from (source or binary)**: Both 
- **TensorFlow version (use command below)**: 1.12.0-rc0-devel-gpu-py3 
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: Latest
- **GCC/Compiler version (if compiling from source)**: 5.x
- **CUDA/cuDNN version**: 9.0 / 10.0 (Tried Both)    | cuDNN : 7.2.x / 7.3.1
- **GPU model and memory**: RTX Geforce 2080
- **Exact command to reproduce**:  Running the most basic mnist dataset using keras with Tf backend

When I try running the code it starts and ends with a segmentation fault even without start of single epoch. The command nvidia-smi shows maximum usage of its volatile memory. I also restricted the gpu usage by a fraction of 0.5 still the problem persists.  I tried building the source files with cuda 9.0 / cudnn 7.2.1 in the docker environment yet the installed whl package produces the same error.

**Comment by samikama** [comment]
@tejavoo, Just to let you know, since 2080 is rather new, cuda 9.0 doesn't know anything about it. So try with cuda 10 installation and driver.

**Comment by ymodak** [comment]
@tejavoo Is this still an issue?

**Comment by tejavoo** [comment]
@ymodak No its been solved and the link to how it was solved is [here](https://medium.com/@saitejadommeti/building-tensorflow-gpu-from-source-for-rtx-2080-96fed102fcca) in a medium article. Thanks to one and all

**Comment by ketil-malde** [comment]
Possibly related?  I have a system set up using Keras, TensorFlow, CUDA 9.0 on Ubuntu 18.0.  When running on 2080 Ti, I either get a validation score that is constant 5.0, or if I tweak a bit, inf.  Running the exact same code on a different machine with P100 works correctly (but slower, dammit).  The setup on the second machine is different, though, so could be a software version problem.
