### ISSUE TITLE
r1.5 tf_version_script.lds not found

### ISSUE THREAD

**Issue by amcphail** [tensorflow/tensorflow#22908]
### System information
== cat /etc/issue ===============================================
Linux sc-phy-370909L 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.5 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux sc-phy-370909L 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.15.1)
numpydoc (0.6.0)
protobuf (3.6.0)
tensorflow (1.10.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
ImportError: No module named platform

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tools/tf_env_collect.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

### Describe the problem
A stock tensorflow r1.5 build fails with "tf_version_script.lds not found."

### Source code / logs
ERROR: /home/amcp011/Documents/tensorflow/tensorflow/python/BUILD:3059:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed (Exit 1): gcc failed: error executing command 
  (cd /home/amcp011/.cache/bazel/_bazel_amcp011/39f5672abd825ffe3e88afa17f90eb9e/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/amcp011/local/bin:/home/amcp011/bin:/home/amcp011/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/amcp011/anaconda3/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/local/lib/python3.5/dist-packages \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
  /usr/bin/gcc -shared -o bazel-out/k8-py3-opt/bin/tensorflow/python/_pywrap_tensorflow_internal.so '-Wl,-rpath,$ORIGIN/../../_solib_k8/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow' -Lbazel-out/k8-py3-opt/bin/_solib_k8/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow -Wl,--version-script //tensorflow:tf_version_script.lds '-Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..' -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,@bazel-out/k8-py3-opt/bin/tensorflow/python/_pywrap_tensorflow_internal.so-2.params)
gcc: error: //tensorflow:tf_version_script.lds: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 97.480s, Critical Path: 10.96s
INFO: 2 processes: 2 local.
FAILED: Build did NOT complete successfully

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by amcphail** [comment]
No: Have I written custom code
Ubuntu 16.04: OS Platform and Distribution
github r1.5: TensorFlow installed from
r1.5: TensorFlow version
?: Bazel version
N/A: CUDA/cuDNN version
N/A: GPU model and memory
Provided above: Exact command to reproduce
N/A: Mobile device

**Comment by gunan** [comment]
with tensorflow 1.5, you need a very old version of bazel to build.
I would recommend checking workspace file, and using the minimum allowed version of bazel.

As this is a more than 1 year old branch, I will close this issue, we do not provide active support for old branches.

**Comment by amcphail** [comment]
I have been trying to compile tensorflow from github.  I thought r1.5 was the latest stable release.  Is this not so?  What tag should I use?  I need to be able to use kera.
