### ISSUE TITLE
Documentation update: virtualenv should not be run from ~

### ISSUE THREAD

**Issue by sesse** [tensorflow/tensorflow#2293]
Hi,

The documentation suggests that you make a virtualenv essentially by “cd ~; mkdir tensorflow; virtualenv ~/tensorflow”. Unfortunately, for some reason I cannot comprehend, this makes virtualenv try to scan every HTML file (possibly also others) in ~; in my case, this hit a 22 MB file I had lying around, causing virtualenv to use 5+ minutes (I eventually aborted it) and 4.5 GB of RAM without really saying why.

A better workaround is “cd ~; mkdir tensorflow; cd tensorflow; virtualenv .”, since seemingly the scanning is of the current directory. The documentation should probably be updated.

**Comment by aselle** [comment]
Is it possible that you had . in your $PATH or $path (in csh)? That's not advised for security reasons, and it might confuse virtualenv which is using your system versions of software (which is probably found by using $PATH).

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
