### ISSUE TITLE
[tf.keras] Ominous Load Warning

### ISSUE THREAD

**Issue by brge17** [tensorflow/tensorflow#22947]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: na
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: na
- **GCC/Compiler version (if compiling from source)**: na
- **CUDA/cuDNN version**: na
- **GPU model and memory**:na 
- **Exact command to reproduce**:na

### Describe the problem
Calling 
```tf.keras.models.model.save(...)```
```model.load_weights(...)```

Produces an ominous warning:

```
Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
```

### Source code / logs
```python
import numpy as np
import tensorflow as tf

def create_model():
    inputs = tf.keras.layers.Input(shape=(1,))
    outputs = tf.keras.layers.Dense(1)(inputs)
    model = tf.keras.models.Model(inputs=inputs, outputs=outputs)
    return model

X = np.array([[1]])

model = create_model()
model.compile("Adam", loss="mse")
model.save("test.hdf5")
print (model.predict(X))
del model

model = create_model()
model.load_weights("test.hdf5")
print (model.predict(X))
```

```
[[-1.1461306]]
2018-10-12 13:05:33.052964: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./test.hdf5: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
[[-1.1461306]]
```

The predictions match, the warning isn't actually an issue.

**Comment by brge17** [comment]
I ran it with ``1.12.0rc0``, issue still exists.

**Comment by brge17** [comment]
@allenlavoie I can try it on ``tf-nightly``, but I've tested it against the latest and greatest release + release candidate.

That PR is very old...

**Comment by allenlavoie** [comment]
Oh I see, you're using ".hdf5". So we could just add that to _is_hdf5_filepath in https://github.com/tensorflow/tensorflow/commit/34d58ca2de7a67be382fb1c7b7ca4868f6695ee3 . Want to send a PR? It'll be a while before I get to it otherwise.

**Comment by brge17** [comment]
Ya I will np.
