### ISSUE TITLE
[tf.keras] Release 1.12.0 issue in model.predict_generator

### ISSUE THREAD

**Issue by brge17** [tensorflow/tensorflow#22952]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: na
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.12.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: na
- **GCC/Compiler version (if compiling from source)**: na
- **CUDA/cuDNN version**: na
- **GPU model and memory**: na
- **Exact command to reproduce**: na

### Describe the problem
Calling ```model.predict_generator()``` on a loaded model or an uncompiled model produces an error. This does not happen for ``model.predict`` or previous releases of TensorFlow.

### Source code / logs
```python
import numpy as np
import tensorflow as tf


def create_model():
    inputs = tf.keras.layers.Input(shape=(1,))
    outputs = tf.keras.layers.Dense(1)(inputs)
    model = tf.keras.models.Model(inputs=inputs, outputs=outputs)
    return model


model = create_model()

X = np.array([[1]])
print(model.predict(X))

class gen(object):
    """ Dummy data generator. """

    def run(self):
        while True:
            yield np.array([[1]])

print(model.predict_generator(generator=gen().run(), steps=1))
```

```python
line 23, in <module>
    print(model.predict_generator(generator=gen().run(), steps=1))
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2298, in predict_generator
    verbose=verbose)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 354, in predict_generator
    model._make_test_function()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 716, in _make_test_function
    raise RuntimeError('You must compile your model before using it.')
```

**Comment by brge17** [comment]
This is annoying because if you do something along the lines of

```model.load_weights(...)``` --> ```model.predict_generator``` without recompiling you get an error.

**Comment by brge17** [comment]
@raymond-yuan or @pavithrasv could one of you two maybe take a look.

I do not want to have to re-compile the optimizer, metrics, etc... at predict time to upgrade to TensorFlow ``1.12.0``

**Comment by brge17** [comment]
Updating description and title, this bug is present in release ``1.12.0``.

**Comment by henrysky** [comment]
I am also experiencing this bug. Here is another scenario where this bug should be fixed. ``predict_generator()`` should not require the model to be recompiled.

```python3
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras

class DataSequence(keras.utils.Sequence):

    def __init__(self, x_set, batch_size):
        self.x = x_set
        self.batch_size = batch_size

    def __len__(self):
        return np.ceil(len(self.x) / self.batch_size)

    def __getitem__(self, idx):
        return self.x[idx * self.batch_size:(idx + 1) * self.batch_size]

input = keras.layers.Input(shape=[1.])
hidden = keras.layers.Dense(2.)(input)
output = keras.layers.Dense(2.)(hidden)

model = keras.models.Model(inputs=input, outputs=output)
model_2 = keras.models.Model(inputs=input, outputs=hidden)

model.compile(optimizer='adam', loss='mse')
model.fit(np.random.normal(0, 1, (100)), np.random.normal(0, 1, (100, 2)))
model_2.predict(np.random.normal(0, 1, (100)))  # it works with compiling model_2
print("using predict() successfully without compiling model")

generator = DataSequence(np.random.normal(0, 1, (100)), 100)
model_2.predict_generator(generator=generator, steps=1)  # it works with compiling model_2
```

**Comment by brge17** [comment]
Excellent, I will try tf-nightly :) soon.

**Comment by pavithrasv** [comment]
Yes this has been fixed in https://github.com/tensorflow/tensorflow/commit/3ea28fa0056fdd5c0821c6347d86a938a80e8e0c#diff-6561418ac6882a842d78dad52731895b

Thank you!

**Comment by wt-huang** [comment]
Closing as this is resolved
