### ISSUE TITLE
How is loss (and average loss) computed in Canned estimators?

### ISSUE THREAD

**Issue by GSonderling** [tensorflow/tensorflow#22962]
### System information
- **Largely irrelevant, the issue concerns documentation**
- **Tensorflow 1.11 (stable)**

Documentation only specifies:

> loss (mean loss per mini-batch) and the average_loss (mean loss per sample)

I understand that this might seem like enough, but since there are several, very different algorithms for computing loss (absolute, relative, square etc.), this can make a big difference.

Especially if you are comparing your custom estimator, with canned alternatives.

For example, I make my own DNN classifier, I run it and get eval dict with keys loss, accuracy, and global_step.  But does the `loss` key represent the same thing it does in canned equivalent? And even if it does, which algorithm I should pick if I want to compute average loss? 

If you are using the canned estimators as a baseline, and many beginners do, then making wrong assumptions about metrics is the worst possible option.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by GSonderling** [comment]
This is a deficiency in documentation, not a bug report.

**Comment by wt-huang** [comment]
Closing this, feel free to reopen if running into any errors.
