### ISSUE TITLE
"Unknwon layer" error while using custom Keras layer with tf.contrib.distribute.MirroredStrategy

### ISSUE THREAD

**Issue by kami93** [tensorflow/tensorflow#22979]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes. See STLSTM.py in https://gist.github.com/kami93/c49f0cdd19b318f3e2699df13971f7b1
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04.1
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
 N/A
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: Anaconda Python 3.6.6
- **Bazel version (if compiling from source)**: 0.17.2
- **GCC/Compiler version (if compiling from source)**: 7.3.0
- **CUDA/cuDNN version**:9.2
- **GPU model and memory**:Gefroce 1080Ti * 4 (4-way GPU)
- **Exact command to reproduce**: Run predRNN.py in https://gist.github.com/kami93/c49f0cdd19b318f3e2699df13971f7b1

### Describe the problem
Hi. I am getting an "Unknown layer" error while running a custom keras layer with tf.contrib.distribute.MirroredStrategy turned on. The trackback is in the Source code / logs section.

The error is not raised when I omit the "distribute" argument from model compile method call (line 75 of the predRNN.py) so that the training runs without distribution strategy and only a single GPU works.

Breif explanation on predRNN.py:
predRNN.py builds input pipeline, makes, compiles and fits the Keras sequential model which includes the STLSTM2D custom layer.
The training data can be downloaded from http://www.cs.toronto.edu/~nitish/unsupervised_video/ (Moving MNIST dataset)

Breif explanation on STLSTM.py:
STLSTM is a sophisticated convolutional RNN model suggested from PredRNN (Wang et al. 2017, https://papers.nips.cc/paper/6689-predrnn-recurrent-neural-networks-for-predictive-learning-using-spatiotemporal-lstms).

STLSTM.py contains three classes - STLSTM2D, StackedSTLSTMCells, STLSTMCell which inherit from the Keras RNN class(in tensorflow/python/keras/layers/recurrent.py), Keras Layer class, and Keras Layer class, repectively. 

- STLSTM2D  is based on ConvRNN2D class in tensorflow/python/keras/layers/convolutional_recurrent.py. It forms a Keras RNN layer that performs recurrent functions with the STLSTM Cell.

- StackedSTLSTMCells is a wrapper to make a list of multiple STLSTMCells look like a single cell.

- STLSTMCell is based on ConvLSTM2DCell in tensorflow/python/keras/layers/convolutional_recurrent.py. The modification is performed such that STLSTM has an additional hidden state (The M-state) and different operation procedure compared to the ConvLSTM2D.

### Source code / logs
Source code : https://gist.github.com/kami93/c49f0cdd19b318f3e2699df13971f7b1
error traceback : https://pastebin.com/6dPKZrzX

**Comment by ymodak** [comment]
Please take a look at keras documentation for [handling custom layers (or other custom objects) in saved models](https://keras.io/getting-started/faq/#handling-custom-layers-or-other-custom-objects-in-saved-models) if haven't already.

**Comment by kami93** [comment]
> Please take a look at keras documentation for [handling custom layers (or other custom objects) in saved models](https://keras.io/getting-started/faq/#handling-custom-layers-or-other-custom-objects-in-saved-models) if haven't already.

Wow thank you. The custom object scoping resolved my problem.
ex) Make, compile and fit the keras model with custom object under the custom object scope
> with tf.keras.utils.custom_object_scope({'StackedSTLSTMCells':STLSTM.StackedSTLSTMCells,
>                                                                  'STLSTMCell':STLSTM.STLSTMCell}):

>    predRNN = keras.Sequential([
>      STLSTM.STLSTM2D(cells, return_sequences=True, input_shape=(TOTAL_LEN, IMG_SIZE, IMG_SIZE, 1)),
>      keras.layers.Reshape(target_shape=(IMG_SIZE*TOTAL_LEN, IMG_SIZE, FILTERS)),
>      keras.layers.Conv2D(filters=1, kernel_size=1),
>      keras.layers.Reshape(target_shape=(TOTAL_LEN, IMG_SIZE, IMG_SIZE, 1))
>   ])

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
