### ISSUE TITLE
protobuf not seem to be recognized but it is installed

### ISSUE THREAD

**Issue by phishekwa** [tensorflow/tensorflow#22970]
(base) D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection>python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v2_coco.config
Traceback (most recent call last):
  File "legacy/train.py", line 49, in <module>
    from object_detection.builders import dataset_builder
  File "D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection\builders\dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection\data_decoders\tf_example_decoder.py", line 24, in <module>
    from object_detection.protos import input_reader_pb2
  File "D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection\protos\input_reader_pb2.py", line 11, in <module>
    from google.protobuf import descriptor_pb2
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\descriptor_pb2.py", line 1114, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\descriptor.py", line 534, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.FileOptions.php_metadata_namespace"

(base) D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection>python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v2_coco.config
Traceback (most recent call last):
  File "legacy/train.py", line 49, in <module>
    from object_detection.builders import dataset_builder
  File "D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection\builders\dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection\data_decoders\tf_example_decoder.py", line 24, in <module>
    from object_detection.protos import input_reader_pb2
  File "D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection\protos\input_reader_pb2.py", line 11, in <module>
    from google.protobuf import descriptor_pb2
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\descriptor_pb2.py", line 1114, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\descriptor.py", line 534, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.FileOptions.php_metadata_namespace"

Please F1 aka Help

**Comment by phishekwa** [comment]
> (base) D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection>python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v2_coco.config
> Traceback (most recent call last):
> File "legacy/train.py", line 49, in 
> from object_detection.builders import dataset_builder
> File "D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection\builders\dataset_builder.py", line 27, in 
> from object_detection.data_decoders import tf_example_decoder
> File "D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection\data_decoders\tf_example_decoder.py", line 24, in 
> from object_detection.protos import input_reader_pb2
> File "D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection\protos\input_reader_pb2.py", line 11, in 
> from google.protobuf import descriptor_pb2
> File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\descriptor_pb2.py", line 1114, in 
> serialized_options=None, file=DESCRIPTOR),
> File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\descriptor.py", line 534, in **new**
> return _message.default_pool.FindFieldByName(full_name)
> KeyError: "Couldn't find field google.protobuf.FileOptions.php_metadata_namespace"
> 
> (base) D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection>python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v2_coco.config
> Traceback (most recent call last):
> File "legacy/train.py", line 49, in 
> from object_detection.builders import dataset_builder
> File "D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection\builders\dataset_builder.py", line 27, in 
> from object_detection.data_decoders import tf_example_decoder
> File "D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection\data_decoders\tf_example_decoder.py", line 24, in 
> from object_detection.protos import input_reader_pb2
> File "D:\FINAL YEAR\Final Project Fanally\Project\Workshop\TensorFlow\models\object_detection\protos\input_reader_pb2.py", line 11, in 
> from google.protobuf import descriptor_pb2
> File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\descriptor_pb2.py", line 1114, in 
> serialized_options=None, file=DESCRIPTOR),
> File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\descriptor.py", line 534, in **new**
> return _message.default_pool.FindFieldByName(full_name)
> KeyError: "Couldn't find field google.protobuf.FileOptions.php_metadata_namespace"
> 
> Please F1 aka Help

found a solution working:

Uninstalled protobuf           => pip3 uninstall protobuf
and Installed protobuf        => pip3 install protobuf

**Comment by harshini-gadige** [comment]
@phishekwa Glad to know that you are able to use it after reinstalling protobuf. Feel free to close this issue :)
