### ISSUE TITLE
Unable to build libtensorflow_cc.so

### ISSUE THREAD

**Issue by Ali2500** [tensorflow/tensorflow#22980]
I'm trying to build libtensorflow_cc.so so I can utilize the C++ API of TensorFlow in my own project. But when I try to do that using the following command:

`bazel build -c opt //tensorflow:libtensorflow_cc.so`

I eventually get the error:

```
2 errors detected in the compilation of "/tmp/tmpxft_000056f1_00000000-7_spacetobatch_functor_gpu.cu.cpp1.ii".
ERROR: /home.net/aa17gil/tensorflow_from_source/tensorflow/tensorflow/core/kernels/BUILD:3825:1: output 'tensorflow/core/kernels/_objs/batch_space_ops_gpu/spacetobatch_functor_gpu.cu.pic.o' was not created
ERROR: /home.net/aa17gil/tensorflow_from_source/tensorflow/tensorflow/core/kernels/BUILD:3825:1: not all outputs were created or valid
Target //tensorflow:libtensorflow_cc.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1219.021s, Critical Path: 81.53s
INFO: 4992 processes: 4992 local.
FAILED: Build did NOT complete successfully

```

As stated in other issues, there is practically no official documentation or guide for how to build this library. I did go through many older issues, but the solutions proposed there don't work for me.

------------------------

### System information
- **Have I written custom code: No**:
- **OS Platform and Distribution: Ubuntu 14.04**:
- **Mobile device: N/A**:
- **TensorFlow installed from source**:
- **TensorFlow version: cloned from master branch on 10.10.2018**:
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.17.2
- **GCC/Compiler version (if compiling from source)**: GCC 4.8.4
- **CUDA/cuDNN version**: CUDA 8.0, CuDNN 6.0.21
- **GPU model and memory**: Nvidia GTX1050Ti
- **Exact command to reproduce**: `bazel build -c opt //tensorflow:libtensorflow_cc.so`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution

**Comment by wt-huang** [comment]
@Ali2500 The the following command works for me:
```
bazel build --config=opt --config=cuda //tensorflow:libtensorflow_cc.so
```
Try using bazel 0.15.0
