### ISSUE TITLE
lose some early epoch checkpoint file during training

### ISSUE THREAD

**Issue by suzirui123** [tensorflow/tensorflow#22982]
Have I written custom code: Y
OS Platform and Distribution: centos release 6.5
TensorFlow installed from: pip install
TensorFlow version: 1.40
Bazel version: N/A
CUDA/cuDNN version: Cuda 8.0
GPU model and memory: N/A
Exact command to reproduce: N/A
Mobile device: N/A
I found myself losing some checkpoint in the target dir after training. For example, I lose 1-13 epoch checkpoint files after 60-epoch training.
I used tf.train.Saver and tf.train.Supervisor in my code:
`tf.train.Supervisor(
            is_chief=is_chief,
            logdir=FLAGS.log_dir,
            global_step=global_step,
            saver=tf.train.Saver(var_list=var_list,max_to_keep=80,sharded=True),
            save_model_secs=FLAGS.save_model_secs,
            save_summaries_secs=FLAGS.save_summary_secs,
            init_op=tf.global_variables_initializer(),
            local_init_op=tf.group(tf.local_variables_initializer(),tf.tables_initializer())`
where save_model_secs=1800, save_summary_secs=1800
FYI, it costs me about 30 minutes for training 1 epoch.WHY?

**Comment by harshini-gadige** [comment]
@suzirui123 Hi, just to confirm, have you looked into protocol buffer to check the list of checkpoints ?

**Comment by suzirui123** [comment]
@harshini-gadige I'm using distributed_training, could you please tell me where to find the protocol buffer you mentioned?

**Comment by suzirui123** [comment]
@harshini-gadige Do you mean freeze the graph to check the pb of checkpoints? I haven't tried that.

**Comment by harshini-gadige** [comment]
@aselle  - Hi, could you please look into this issue ?

**Comment by harshini-gadige** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
