### ISSUE TITLE
2x slower using post-training quantization from tensorflow-lite

### ISSUE THREAD

**Issue by eugene123tw** [tensorflow/tensorflow#22988]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:  `pip install -U tf-nightly`
- **TensorFlow version (use command below)**: `'1.12.0-dev20181012'`
- **Python version**: 2.7.12

### Describe the problem
I read and run the post-training quantization code from official tensorflow Medium (https://medium.com/tensorflow/introducing-the-model-optimization-toolkit-for-tensorflow-254aca1ba0a3). 
The post said the technique can result in up to 3x faster execution for relevant machine learning models. But I found during inference is 2x slower. 

### Source code / logs
I run the Colab notebook (https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/tutorials/post_training_quant.ipynb) and compare inference time before and after quantization from the *Evaluate the models* section. 

The log before quantization: 
```
Accuracy after 500 images: 0.976000
Accuracy after 1000 images: 0.966000
Accuracy after 1500 images: 0.958667
Accuracy after 2000 images: 0.956500
Accuracy after 2500 images: 0.952400
Accuracy after 3000 images: 0.956667
Accuracy after 3500 images: 0.957429
Accuracy after 4000 images: 0.955000
Accuracy after 4500 images: 0.955333
Accuracy after 5000 images: 0.954800
Accuracy after 5500 images: 0.958182
Accuracy after 6000 images: 0.959000
Accuracy after 6500 images: 0.960462
Accuracy after 7000 images: 0.961571
Accuracy after 7500 images: 0.963600
Accuracy after 8000 images: 0.965250
Accuracy after 8500 images: 0.966471
Accuracy after 9000 images: 0.968222
Accuracy after 9500 images: 0.969158
Accuracy after 10000 images: 0.968000
0.968
42.6 sec
```

The log after quantization: 
```
Accuracy after 500 images: 0.976000
Accuracy after 1000 images: 0.967000
Accuracy after 1500 images: 0.959333
Accuracy after 2000 images: 0.957000
Accuracy after 2500 images: 0.952800
Accuracy after 3000 images: 0.957000
Accuracy after 3500 images: 0.957714
Accuracy after 4000 images: 0.955500
Accuracy after 4500 images: 0.955778
Accuracy after 5000 images: 0.955200
Accuracy after 5500 images: 0.958545
Accuracy after 6000 images: 0.959333
Accuracy after 6500 images: 0.960769
Accuracy after 7000 images: 0.961857
Accuracy after 7500 images: 0.963867
Accuracy after 8000 images: 0.965500
Accuracy after 8500 images: 0.966706
Accuracy after 9000 images: 0.968444
Accuracy after 9500 images: 0.969368
Accuracy after 10000 images: 0.968300
0.9683
74.5 sec
```

The accuracy is basically the same, but it's much slower.

**Comment by cjr0106** [comment]
do you understand the principle of post-training ? how does it achieve the quant ?

**Comment by eugene123tw** [comment]
Why the issue is close?

**Comment by wt-huang** [comment]
It is slower after quantization. During post training the weights are quantized whereas the activations are quantized and dequantized on the fly at inference.

**Comment by zh794390558** [comment]
@wt-huang Does the quantized model will using float at inference?
