### ISSUE TITLE
def TFE_ContextOptionsSetAsync(arg1, async):                                              

### ISSUE THREAD

**Issue by hasibzunair** [tensorflow/tensorflow#22981]
Problem with installing tensorflow in Python 3.7.

Referred to [#20444](https://github.com/tensorflow/tensorflow/issues/20444) but to no avail. :(

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by hasibzunair** [comment]
Closing this. Temporarily working on a different virtual environment with Python 3.6 for my need.

**Comment by Leehon008** [comment]
got this error while trying to install tensorflow. any help is highly entertained
 
from tensorflow.python.pywrap_tensorflow_internal import *
  File "E:\School\WEB\django\twitter-sentiment-analysis-web-app\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 114
    def TFE_ContextOptionsSetAsync(arg1, async):
