### ISSUE TITLE
document error

### ISSUE THREAD

**Issue by gangsir** [tensorflow/tensorflow#230]
I was following the getting started tutorial and found one issue in this http://tensorflow.org/get_started/basic_usage.md#overview. 

there is undefined name "state" in the example of Variables section. I think it should be "var" but I am new to tensorflow. Please confirm and update the doc so that others don't get confused.

**Comment by vrv** [comment]
Thanks for the report -- this has been updated in our repository but not yet pushed to the website.  Will probably be updated this week!
