### ISSUE TITLE
Contact for legal issues

### ISSUE THREAD

**Issue by alviur** [tensorflow/tensorflow#2301]
Good night

Currently my university wants to use Tensorflow for a software project. The lawyers of my university want a letter which says TensorFlow creators allow my university to use his library. Any idea who must I contact for this issue? Thanks a lot.

**Comment by akors** [comment]
Not an export or lawyer, but:
https://github.com/tensorflow/tensorflow/blob/master/LICENSE

It's an apache license, which means you can basically use it (also commercially), you can redistribute it, modify it and are not required to publish your changes or your source code.

https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by girving** [comment]
TensorFlow is an Apache licensed open source project, so there is no need for a specific permission grant (nor do we provide such).
