### ISSUE TITLE
Keras saved_model.simple_save model bigger and bigger

### ISSUE THREAD

**Issue by Coac** [tensorflow/tensorflow#23025]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:  Custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Mint 19 Tara
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.1
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: python script.py

### Describe the problem
When saving successively a keras model using `tf.get_default_graph()`, the size of `saved_model.pb` increase.

![image](https://user-images.githubusercontent.com/7363034/47020409-982a3e80-d159-11e8-80db-e39f47278f03.png)

### Source code / logs
script.py
```
import time

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import *
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import *

if __name__ == '__main__':

    sess = tf.keras.backend.get_session()

    model = Sequential()

    model.add(Dense(units=64, activation='relu', input_dim=4))
    model.add(Dense(units=4, activation='linear'))

    opt = RMSprop(lr=0.1)
    model.compile(loss='mse', optimizer=opt)

    graph = tf.get_default_graph()  # Use the same graph as global thread

    model.predict(np.array([[1, 1, 1, 1], [1, 1, 1, 1]]))

    for _ in range(100):
        time.sleep(1)
        temp_export_path = '/tmp/models/' + str(time.time()).split(".")[0]

        with graph.as_default():
            tf.saved_model.simple_save(
                sess,
                temp_export_path,
                inputs={'state': model.input},
                outputs={t.name: t for t in model.outputs})

```

**Comment by Coac** [comment]
Updated

**Comment by wt-huang** [comment]
@Coac You would need to reset the graph before initiating the model. Also, add longer sleep time between graphs. Here is the code snippet I modified, from which you will get exactly the same file size for all the .pb files.

```
import time

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import *
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import *

if __name__ == '__main__':
    
    for _ in range(100):
        tf.reset_default_graph()
        sess = tf.keras.backend.get_session()

        model = Sequential()
        model.add(Dense(units=64, activation='relu', input_dim=4))
        model.add(Dense(units=4, activation='linear'))

        opt = RMSprop(lr=0.1)
        model.compile(loss='mse', optimizer=opt)

        graph = tf.get_default_graph()  # Use the same graph as global thread

        model.predict(np.array([[1, 1, 1, 1], [1, 1, 1, 1]]))
        time.sleep(10)
        temp_export_path = '/tmp/models/' + str(time.time()).split(".")[0]

        with graph.as_default():
            tf.saved_model.simple_save(
                sess,
                temp_export_path,
                inputs={'state': model.input},
                outputs={t.name: t for t in model.outputs})
```

**Comment by Coac** [comment]
Thanks for your answer, this is working, the size does not increase when resetting the graph each time. 
But we get a new graph and we **lose the trained weights**. 
Can't we get the latest version of the graph exported each time without having the size of the .pb file explodes?

**Comment by wt-huang** [comment]
Glad it worked. To save the latest version of the graph exported every time, you probably want to use `saved_model.builder.SavedModelBuilder()` and define different tags then you can have multiple .pb.

**Comment by Coac** [comment]
I tried using `saved_model.builder.SavedModelBuilder()`, I also get the exported .pb bigger after each call.

What I want to do is training the model, for some time then export it to serve it, then retraining.
Training -> Export -> Training -> Export -> ...

The version using a builder:
```python
import time

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import SGD
from tensorflow.python.saved_model import tag_constants
from tensorflow.python.saved_model.signature_def_utils_impl import predict_signature_def

if __name__ == '__main__':

    sess = tf.keras.backend.get_session()

    model = Sequential()

    model.add(Dense(units=64, activation='relu', input_dim=4))
    model.add(Dense(units=4, activation='linear'))

    opt = SGD(lr=0.01)
    model.compile(loss='mse', optimizer=opt)

    graph = tf.get_default_graph()

    model.predict(np.array([[1, 1, 1, 1], [1, 1, 1, 1]]))

    for _ in range(100):
        with graph.as_default():
            time.sleep(1)
            model.fit(np.array([[1, 1, 1, 1], [1, 1, 1, 1]]), np.array([[1, 1, 1, 1], [1, 1, 1, 1]]))
            temp_export_path = '/tmp/models/' + str(time.time()).split(".")[0]

            # Saving
            builder = tf.saved_model.builder.SavedModelBuilder(temp_export_path)
            signature = predict_signature_def(inputs={'state': model.input},
                                              outputs={t.name: t for t in model.outputs})
            builder.add_meta_graph_and_variables(sess, [tag_constants.SERVING],
                                                 signature_def_map={
                                                     tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY: signature})
            builder.save()

```
The builder instantiation is inside the loop as I would like to save the model to a separate model each time.

**Comment by gadagashwini** [comment]
Hi @Coac,` Tensorflow v1.x `is not actively supporting, we would request you to use `Tensorflow v2.x`. 
You can save the model using `model.save()`, load model using `tf.keras.models.load_model()`. Tensorflow v2.x provides facility to save and load the checkpoints during training. To save weights manually, use [tf.keras.Model.save_weights](https://www.tensorflow.org/api_docs/python/tf/keras/Model#save_weights). By default, [tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras)—and the [Model.save_weights](https://www.tensorflow.org/api_docs/python/tf/keras/Model#save_weights) method in particular—uses the TensorFlow [Checkpoint](https://www.tensorflow.org/guide/checkpoint) format with a .ckpt extension. For more information please refer Tensorflow official site [here](https://www.tensorflow.org/tutorials/keras/save_and_load). Thank you!
