### ISSUE TITLE
Error in C++ Tensorflow to load model trained by python

### ISSUE THREAD

**Issue by sevensix6** [tensorflow/tensorflow#23020]
Using tensorflow1.8 in C++,  I load the model (freezed in *.pb) and creat session with graph. Than when I run the session, error occurs as "Error: RUN FAILED...Invalid argument: Expects arg[0] to be bool but float is peovided".
Anyone suggestions is needed, Please help me!

**Comment by dvicini** [comment]
Did you by any chance use the "optimize_for_inference" script? I recently got a similar error when using this script. What worked for me was to just freeze the model and not run the optimize_for_inference script.

**Comment by sevensix6** [comment]
Thanks for your reply, but I don't use the script, so the problem maybe wrong pb model in freezing process? I also try to load the model by MetaGraphDef class to load "*.meta" file, but occurs "Invalid argument: No Opkernel was registered to support Op 'PyFunc' with these attrs. Registered devices: [CPU], Registered kernels", which confused me...

**Comment by sevensix6** [comment]
> Did you by any chance use the "optimize_for_inference" script? I recently got a similar error when using this script. What worked for me was to just freeze the model and not run the optimize_for_inference script.

Thanks for your reply, but I don't use the script, so the problem maybe wrong pb model in freezing process? I also try to load the model by MetaGraphDef class to load "*.meta" file, but occurs "Invalid argument: No Opkernel was registered to support Op 'PyFunc' with these attrs. Registered devices: [CPU], Registered kernels", which confused me...

**Comment by robinqhuang** [comment]
I am using r1.10. I am using pre-intalled freeze_graph binary, it works well. I guess you may be put wrong output node when during freezing ?

**Comment by wt-huang** [comment]
@dvicini @robinqhuang good suggestions, optimize_for_inference and freeze_graph binary should work. Please post your code snippet here if this is still an issue.

**Comment by wt-huang** [comment]
@dvicini You can use [Graph Transform Tool](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms) to optimize graph for inference then import it.

**Comment by wt-huang** [comment]
Closing as this is resolved, free to reopen if problem persists.
