### ISSUE TITLE
Hyperspectral image classification using tensorflow

### ISSUE THREAD

**Issue by sandeep-25** [tensorflow/tensorflow#23023]
Delivery Status Notification (Failure)Application toolbar
Message Body
Hello sandeep.ladi@gitam.edu,

We're writing to let you know that the group you tried to contact (discuss) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/tensorflow.org/bin/topic.py?topic=25838.

Thanks,

tensorflow.org admins

----- Original message -----

X-Google-Smtp-Source: ACcGV625ngDxZGFv6zxaJTNRD5PlUDFyJNQJK/RowOuC79uaJbT7E4TVqkiThwkQIV8Yc/WPsFZ0
X-Received: by 2002:a5d:44ce:: with SMTP id z14-v6mr19096788wrr.286.1539685981354;
        Tue, 16 Oct 2018 03:33:01 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1539685981; cv=none;
        d=google.com; s=arc-20160816;
        b=E/S3lH6dW8jBpv80GEP3mZyz1KyIDntxI9nZGVOdAbeJS3yOgQ3nq4bp7hre3N/HU8
         9HqA9XkD3dHukXpz06r+2R5F3i2Rbio9TsIfnjdh9b454Ps75DUM7gm1nuxEGojtfeZd
         2RKUTWWKH3a/1dOWecoz0fRibWJd0ByhBNTYW2F+p9hMdg9TAP3m9nuxpLl/bF/r/VAw
         62gIT4ydaIgySfEH6uXHh5dYAab8+96sPnw5wZiAHzO1LpUt766K85dv/6asxCHoMMOR
         M5lzAq1FK+XOfca7bJqn7lt2Vu2YIU7wJbIJs2vQKtLwZcl7SYf20rkFeVGrNQ4zmonY
         zuwg==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=user-agent:message-id:disposition-notification-to:return-receipt-to
         :subject:to:from:date:mime-version;
        bh=OsFzSe3J2uxfPu0m4Xtt3CiGAfo46dWIPdy+i82VhII=;
        b=ePJSnFaP1g6RcKwXYOLK4F+lXEJ8Ul1ycwocH3iAPT6Ga19fNe5HJXhaFcbexJywfr
         G+86clKs6GOA2baW3nqnAl/4rAVGMjQyWIUMBPFHdei28lIjvMo3gyXX3ocxM0XMPP2z
         2vQ2qCJZQBHZegkhMO/z+d1/8a/bjqScVAH+gZOXS0hbQIp23fsx9CsPeM6iX2boAlDB
         q8zh8LkYwMUxA+p0EDdmrflNA2hs9mqqiYaCJJQ2oD7VvqHpUsqdMeczcmck75SvB0xO
         uvPdhrFHdp26RDN2JKj36FInwYHZTnTEKw69UFchUoLBSgzOCdCnhBQlIWyEyDX6LGYQ
         8fUg==
ARC-Authentication-Results: i=1; mx.google.com;
       spf=pass (google.com: domain of sandeep.ladi@gitam.edu designates 103.23.29.142 as permitted sender) smtp.mailfrom=sandeep.ladi@gitam.edu
Return-Path: <sandeep.ladi@gitam.edu>
Received: from mail.gitam.edu (mail.gitam.edu. [103.23.29.142])
        by mx.google.com with ESMTP id s1-v6si12238610wrf.2.2018.10.16.03.33.00
        for <discuss@tensorflow.org>;
        Tue, 16 Oct 2018 03:33:00 -0700 (PDT)
Received-SPF: pass (google.com: domain of sandeep.ladi@gitam.edu designates 103.23.29.142 as permitted sender) client-ip=103.23.29.142;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of sandeep.ladi@gitam.edu designates 103.23.29.142 as permitted sender) smtp.mailfrom=sandeep.ladi@gitam.edu
Received: from mail.gitam.edu (webmail.gitam.edu [192.168.23.28])
    by mail.gitam.edu (Postfix) with ESMTPA id B765722BCC5
    for <discuss@tensorflow.org>; Tue, 16 Oct 2018 16:02:46 +0530 (IST)
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="=_8b103ec7c4f10c51b775e6343c7573ca"
Date: Tue, 16 Oct 2018 16:02:46 +0530
From: sandeep.ladi@gitam.edu
To: discuss@tensorflow.org
Subject: Command to Input Hyperspectral Image dataset to TensorFlow.
Return-Receipt-To: sandeep.ladi@gitam.edu
Disposition-Notification-To: sandeep.ladi@gitam.edu
Message-ID: <e885520003a6c5c626388950aeb89319@gitam.edu>
X-Sender: sandeep.ladi@gitam.edu
User-Agent: GITAM Webmail/1.2.2
X-gitam-MailScanner-Information: Please contact the ISP for more information
X-gitam-MailScanner-ID: B765722BCC5.A15A0
X-gitam-MailScanner: Found to be clean
X-gitam-MailScanner-SpamScore: s
X-gitam-MailScanner-From: sandeep.ladi@gitam.edu
X-Spam-Status: No

--=_8b103ec7c4f10c51b775e6343c7573ca
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=US-ASCII

Dear sir/Madam, 

Greetings of the day. 

I am Mr.Ladi Sandeep Kumar,working as an Assistant Professor in GITAM
University,Visakhapatnam,India.I and my project students are working on
a Project based on Hyperspectral image classification which is an
emerging research topic.The opensource Hyperspectral image datasets are
in .mat files containing reflectance values.We are going to use CNN
technique for image classification using Hyperspectral image dataset of 
Indian pines which is a dataset of 145x145x200 where 145x145 are height
and width of image and 200 is number of channels.There are lot of
resources and guide for using tensorflow CNN toolbox for color image.Can
you please tell me the way and send the code to input the Indian pines
dataset of 145x145 x200 as input to the CNN. 

I will use the tensorFlow toolbox in my  research as well as projects 
to teach my students and quote your website in my publications wherever
I apply tensorflow module.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by sandeep-25** [comment]
Have I written custom code -N/A
OS Platform and Distribution-Ubuntu 14,google collab application,python 3
notebook
TensorFlow installed from-google collab,python 3 notebook,TPU
TensorFlow version-N/A
Bazel version-N/A
CUDA/cuDNN versionN/A
GPU model and memory-TPU available at Google collab
Exact command to reproduce-pixel wise Classification of hyperspectral image
using tensor flow.
Mobile device-Acer Laptop.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
