### ISSUE TITLE
Error parsing bazel version (bazel 0.2.2b)

### ISSUE THREAD

**Issue by gaohuazuo** [tensorflow/tensorflow#2303]
TensorFlow version: v0.8.0
Bazel version: 0.2.2b (installed via deb package)

Command: `bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer --verbose_failures`
Error message:
```
ERROR: /path_to_my_workspace/tensorflow/WORKSPACE:21:1: Traceback (most recent call last):
	File "/path_to_my_workspace/tensorflow/WORKSPACE", line 21
		check_version("0.1.4")
	File "/path_to_my_workspace/tensorflow/tensorflow/tensorflow.bzl", line 22, in check_version
		_parse_bazel_version(native.bazel_version)
	File "/path_to_my_workspace/tensorflow/tensorflow/tensorflow.bzl", line 15, in _parse_bazel_version
		int(number)
invalid literal for int(): "2b".
ERROR: Error evaluating WORKSPACE file.
ERROR: no such package 'external': Package 'external' contains errors.
```

The error seems to be `_parse_bazel_version` not expecting a non decimal character.

**Comment by moon6pence** [comment]
I cannot believe there's another person suffering with same problem, just 30 minutes ago!

**Comment by moon6pence** [comment]
It seems to be fixed in current master. 
https://github.com/tensorflow/tensorflow/commit/3be665fb87ff12c90766afc7ceed63b3c7c69317

**Comment by hholst80** [comment]
Have you tried bazel 0.2.2?

**Comment by gaohuazuo** [comment]
Yes. Bazel 0.2.2 worked perfectly.

**Comment by vrv** [comment]
Are you synced to master?  Or are you on the 0.8 branch?  This is fixed at HEAD, so there should be no reason to downgrade to Bazel 0.2.2 at HEAD on master.
