### ISSUE TITLE
FR: Create/Support an automated hyperparameter selector like TPOT

### ISSUE THREAD

**Issue by boosh** [tensorflow/tensorflow#2305]
Not sure if you've seen TPOT (http://rhiever.github.io/tpot/, introductory blog post at http://www.randalolson.com/2016/05/08/tpot-a-python-tool-for-automating-data-science/) but it would be awesome if you collaborated with them to add something like this to TensorFlow.

**Comment by suiyuan2009** [comment]
I'll work on it

**Comment by alextp** [comment]
Closing because this issue is too broad and keeping it open is unlikely to be helpful.
