### ISSUE TITLE
tf.arg_max docs suggest nonexistent page in 1.12

### ISSUE THREAD

**Issue by martinwicke** [tensorflow/tensorflow#23057]
**System information**
- TensorFlow version: 1.12
- Doc Link: https://www.tensorflow.org/versions/r1.12/api_docs/python/tf/arg_max

**Describe the documentation issue**

the 1.12 page for arg_max mentions this function is deprecated in favor of argmax: "THIS FUNCTION IS DEPRECATED. It will be removed in a future version. Instructions for updating: Use argmax instead"

However, argmax is not documented for 1.12 (it is fine in 1.11).

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device
