### ISSUE TITLE
TFLite benchmark_model cannot be compiled successfully

### ISSUE THREAD

**Issue by leo-nullptr** [tensorflow/tensorflow#23068]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from: source
- TensorFlow version: 1.11.0
- Python version: 3.6.6
- Bazel version: 0.18.0
- GCC/Compiler version: Android Clang NDK 18

**Describe the problem**

When use command in README for benchmark, the compiling failed.

bazel build -c opt \
  --config=android_arm \
  --cxxopt='--std=c++11' \
  tensorflow/contrib/lite/tools/benchmark:benchmark_model

**Any other info / logs**

ERROR: /data/tensorflow/contrib/lite/tools/benchmark/BUILD:19:1: Linking of rule '//tensorflow/contrib/lite/tools/benchmark:benchmark_model' failed (Exit 1)
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/__locale:51: error: undefined reference to 'uselocale'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/__locale:56: error: undefined reference to 'uselocale'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/__locale:56: error: undefined reference to 'uselocale'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/src/locale.cpp:76: error: undefined reference to 'newlocale'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/__locale:51: error: undefined reference to 'uselocale'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/src/locale.cpp:5439: error: undefined reference to 'freelocale'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/__bsd_locale_fallbacks.h:53: error: undefined reference to 'wcsnrtombs'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/__bsd_locale_fallbacks.h:68: error: undefined reference to 'mbsnrtowcs'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/__bsd_locale_fallbacks.h:83: error: undefined reference to 'mbtowc'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/src/locale.cpp:1531: error: undefined reference to 'freelocale'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/locale:739: error: undefined reference to 'strtoll_l'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/locale:739: error: undefined reference to 'strtoll_l'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/locale:779: error: undefined reference to 'strtoull_l'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/locale:779: error: undefined reference to 'strtoull_l'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/locale:779: error: undefined reference to 'strtoull_l'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/locale:779: error: undefined reference to 'strtoull_l'
/usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/include/locale:820: error: undefined reference to 'strtold_l'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by shashishekhar** [comment]
@leo-nullptr : I compiled with android-ndk-r16b and it worked without any issues. Does it work with android-ndk-r16b?

**Comment by leo-nullptr** [comment]
> @leo-nullptr : I compiled with android-ndk-r16b and it worked without any issues. Does it work with android-ndk-r16b?

When I compiled with android-ndk-r16b, it succeed with arm-v7a but failed with arm64-v8a.
SUCCEED: `bazel build --config android_arm --cxxopt=-std=c++11 //tensorflow/contrib/lite/tools/benchmark:benchmark_model`
FAILED: `bazel build --config android_arm64 --cxxopt=-std=c++11 //tensorflow/contrib/lite/tools/benchmark:benchmark_model`

Logs:
`
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:164:11: error: no member named 'vfwscanf' in the global namespace
  using ::vfwscanf;
        ~~^
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:170:11: error: no member named 'vswscanf' in the global namespace
  using ::vswscanf;
        ~~^
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:174:11: error: no member named 'vwscanf' in the global namespace
  using ::vwscanf;
        ~~^
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:191:11: error: no member named 'wcstof' in the global namespace
  using ::wcstof;
        ~~^
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:280:14: error: no member named 'wcstof' in namespace 'std'
  using std::wcstof;
        ~~~~~^
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:283:14: error: no member named 'vfwscanf' in namespace 'std'; did you mean 'fwscanf'?
  using std::vfwscanf;
        ~~~~~^
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:148:11: note: 'fwscanf' declared here
  using ::fwscanf;
          ^
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:286:14: error: no member named 'vswscanf' in namespace 'std'; did you mean 'swscanf'?
  using std::vswscanf;
        ~~~~~^
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:160:11: note: 'swscanf' declared here
  using ::swscanf;
          ^
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:289:14: error: no member named 'vwscanf' in namespace 'std'
  using std::vwscanf;
        ~~~~~^
`

**Comment by leo-nullptr** [comment]
@shashishekhar Is it caused by libc++ in new ndk forced on android P?

**Comment by shashishekhar** [comment]
@leo-nullptr : Does this [workaround](https://github.com/tensorflow/tensorflow/issues/20192#issuecomment-404971539) work for you?

**Comment by leo-nullptr** [comment]
@shashishekhar I have exported ANDROID_NDK_API_LEVEL as 24, and benchmark_model cannot be compiled with NDK r18. Thanks!
