### ISSUE TITLE
Attributes values not inferred by TFE C API (eager mode)

### ISSUE THREAD

**Issue by karllessard** [tensorflow/tensorflow#23060]
I'm trying to enable eager execution mode in Java based on the`TFE_*` methods exposed by TensorFlow C API and I have noticed that those method do not infer attribute values the same way that graph execution does.

For example, the `NodeDefBuilder` class (used in graph execution mode) will infer type attribute values automatically based on the type of the tensors the node receives in input (see [`NodeDefBuilder::SingleInput`](https://github.com/tensorflow/tensorflow/blob/7e0257d953401288bc10dc11d07b418371bbc56d/tensorflow/core/framework/node_def_builder.cc#L123). Eager classes do not. Also, in graph mode, default values are assigned automatically when some attributes are not provided (see [`NodeDefBuilder::Finalize`](https://github.com/tensorflow/tensorflow/blob/7e0257d953401288bc10dc11d07b418371bbc56d/tensorflow/core/framework/node_def_builder.cc#L245)). Again, eager classes do not.

My question is are those features missing by design or should they be part of the eager C API as well? 

I can do a work around in the Java client, as @eaplatanios did for Scala, but I'm tempted to think that this should be implemented in the C API and that the graph and eager methods should be more symmetric to avoid moving this complexity in all the clients.

-----------

Have I written custom code: N/A
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: 1.11
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A
Mobile device: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by karllessard** [comment]
Have I written custom code: N/A
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: 1.11
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A
Mobile device: N/A

**Comment by karllessard** [comment]
Created a PR to address this issue: https://github.com/tensorflow/tensorflow/pull/23468, closing this one.
