### ISSUE TITLE
Error while importing tensorflow after installation 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [tensorflow/tensorflow#23071]
Please help me to solve this problem i am trying from several days. i get this error when i import tensorflow after installation , i am using windows 10 OS. 

>>> import tensorflow as tf
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.umath failed to import
ImportError: numpy.core.umath failed to import
2018-10-18 18:24:15.573678: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr

**Comment by sam081** [comment]
I'll need more info. Please update your numpy and tf versions.

**Comment by MuhammadAsadJaved** [comment]
@sam081  thank you dear it is working now , i have uninstall Numpy and install it again . now it is working.
