### ISSUE TITLE
Tensorflow serving with Retrained Inception graph

### ISSUE THREAD

**Issue by oweingrod** [tensorflow/tensorflow#2307]
Hello!

Are there any plans to release a tutorial similar to the one to use a checkpointed Inception graph with Tensorflow Serving, but with a Retrained Inception graph as created with the [transfer learning tutorial](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/image_retraining/index.md)?

**Comment by petewarden** [comment]
In theory it should be possible to reuse the TensorFlow Serving tutorial and just change the name of the output layer to "final_result", as shown in the label_image example:
https://www.tensorflow.org/versions/master/how_tos/image_retraining/index.html#using-the-retrained-model

Unfortunately the TensorFlow Serving code creates its own model from scratch, and then loads in the checkpoints to fill in the variables. This means that it's not obvious how to convert a plain GraphDef with the weights as constant ops into their format. I'm passing this over to @jharmsen to see if he can offer any advice?

**Comment by oweingrod** [comment]
@jharmsen Do you have any further information on this topic? I am unfortunately still at a standstill.

**Comment by ank286** [comment]
I am interested in serving a retrained-inception graph as well. Is there a way to 'serve' the .pb retrained file that is an output of retrain.py and is used in label_image? Or a way to serve label_image pointing at a .pb file?

**Comment by Neodimi** [comment]
I'm stuck at this point too. Did anyone find a solution?

**Comment by martinwicke** [comment]
@nfiedel can you help with this?

**Comment by nfiedel** [comment]
@fangweili and I were discussing offline. Now that [SessionBundle](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/session_bundle) is in contrib, the next natural step is to update the inception model / retrain.py to directly use the SessionBundle Exporter. Contributions welcome though we may get to it over the coming weeks.

**Comment by Nr90** [comment]
Trying to do the same.
Would be awesome to see an update to inception / retrain.py!

**Comment by theclifbar** [comment]
Also trying to do the same... I think it's safe to say that there are many others who haven't chimed in but would love for this to be added, or documented steps so that we can implement it ourselves.  Are we at least on the right path to use export_meta_graph and Saver.save() to convert the retrained .pb and label files into the metagraph def and checkpoint files needed for TF serving?

**Comment by zign** [comment]
@nfiedel is there update to this topic?

**Comment by tobiaslorenz** [comment]
Might not totally be related to the original question but what worked for me as a workaround is to fully train the inception model from scratch and then export it to serving. Of course, that involves the extra resources needed for the full training run but might be a suitable way for some seeking to serve their own classification model.

**Comment by danielbicho** [comment]
Hello guys, i am stuck at this point. I don't have the resources to train from scratch the inception model, although is something that i want to do soon. Any update on this topic is welcome. Thx

**Comment by drpngx** [comment]
Sorry we don't have the cycles to support that. It's a known problem. It might be worth asking the community on stackoverflow.

**Comment by gunan** [comment]
Automatically closing due to recent activity.
As we moved models out of core TensorFlow repository, this issue may be a better fit for models or serving repositories.

**Comment by shahnawaj5488** [comment]
@petewarden Any walkthrough for the tensorflow serving on custom retrained Inception v3.

**Comment by Pokharaa** [comment]
Please watch this video tutorial. It might help you.
https://www.youtube.com/watch?v=9l2lkQtinx4&t=14s
