### ISSUE TITLE
prediction from tensorflow differs on broadwell and on SkyLake

### ISSUE THREAD

**Issue by ziky90** [tensorflow/tensorflow#23076]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.11.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.18.0
- GCC/Compiler version (if compiling from source): 7.3
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
I have experimented a bit with CNNs for semantic segmentation and it's predictions and I have noticed that for exactly the same network predictions are different regarding the architecture where I deploy the network. I currently see the following state:

`pip install tensorflow` - correct result
`pip install tensorflow-gpu` - correct result (P100)
`bazel build -c opt --copt=-march=broadwell --copt=-mfpmath=both -k //tensorflow/tools/pip_package:build_pip_package` - correct result
`bazel build -c opt --copt=-march=native --copt=-mfpmath=both -k //tensorflow/tools/pip_package:build_pip_package` - different (1-2% mismatch on my tested images) result on SkyLake (but faster prediction than with `--copt=-march=broadwell`)

**NOTE:**
I'm using 32core Google Cloud machines in the us-central1-f zone with CPU option SkyLake.

**Question:**
Is expected the prediction on SkyLake to be different from the prediction on broadwell and GPU on purpose, or should it be exactly the same and I'm just very unlucky here regarding rounding in some libraries underneath the tensorflow?

**Comment by wt-huang** [comment]
You shouldn't see a big difference in semantic segmentation and its predictions between different architectures. Please provide more details or post your code snippet here.
