### ISSUE TITLE
Runmetadata and graph definitions are not mached

### ISSUE THREAD

**Issue by sj6077** [tensorflow/tensorflow#23072]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
source
- TensorFlow version (use command below):
1.6
- Python version:
Python 2.7.12
- Bazel version (if compiling from source):
0.13.0
- GCC/Compiler version (if compiling from source):
5.4.0 2
- CUDA/cuDNN version:
9.0, 7.0
- GPU model and memory:
TitanXP, 12G

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I was trying to match information between graph definition and timeline but they didn't match.
For example, below is a node in graph definition. 
`node {
    name: "AutoParallel-Replica-0-Accum-Apply/model/gradients/model/lm/sampled_softmax_loss/embedding_lookup/Gather_3_grad/Reshape"
    op: "SparseAccumulatorApplyGradient"
    input: "AutoParallel-Accum/model/gradients/model/lm/sampled_softmax_loss/embedding_lookup/Gather_3_grad/Reshape"
    input: "Const_35"
    input: "AutoParallel-Replica-0/model/gradients/model/lm/sampled_softmax_loss/embedding_lookup/Gather_3_grad/Reshape_1"
    input: "AutoParallel-Replica-0/model/gradients/model/lm/sampled_softmax_loss/embedding_lookup/Gather_3_grad/Reshape"
    input: "ToInt64_107"
    device: "/job:worker/task:0/device:CPU:0"
    attr {
      key: "_class"
      value {
        list {
          s: "loc:@AutoParallel-Accum/model/gradients/model/lm/sampled_softmax_loss/embedding_lookup/Gather_3_grad/Reshape"
        }
      }
    }
    attr {
      key: "dtype"
      value {
        type: DT_FLOAT
      }
    }
    attr {
      key: "has_known_shape"
      value {
        b: true
      }
    }
  }
`
However, Runmetadata contains below node stat for the node. The inputs in timeline_label are different with information in the graph node. I want to know the policy or rules to match two different information.
` node_stats {
      node_name: "AutoParallel-Replica-0-Accum-Apply/model/gradients/model/lm/sampled_softmax_loss/embedding_lookup/Gather_3_grad/Reshape"
      all_start_micros: 1539680850138092
      op_start_rel_micros: 10
      op_end_rel_micros: 12405
      all_end_rel_micros: 12418
      memory {
        allocator_name: "cpu_rdma_bfc"
        total_bytes: 2574336
        peak_bytes: 2574336
        allocator_bytes_in_use: 260048896
        allocation_records {
          alloc_micros: 1539680850142050
          alloc_bytes: 2574336
        }
        allocation_records {
          alloc_micros: 1539680850150477
          alloc_bytes: -2574336
        }
      }
      timeline_label: "[cpu_rdma_bfc 2.5MB 2.5MB] AutoParallel-Replica-0-Accum-Apply/model/gradients/model/lm/sampled_softmax_loss/embedding_lookup/Gather_3_grad/Reshape = SparseAccumulatorApplyGradient(AutoParallel-Accum/model/gradients/model/lm/sampled_softmax_loss/embedding_lookup/Gather_3_grad/Reshape, Const, AutoParallel-Replica-0/model/lm/sampled_softmax_loss/embedding_lookup/DynamicPartition:3, AutoParallel-Replica-0/model/gradients/model/lm/sampled_softmax_loss/embedding_lookup_grad/Gather_3_G818, ToInt64_2)"
      scheduled_micros: 1539680850138009
      memory_stats {
      }
    }
`
**Describe the expected behavior**
Input names in graph definition and timeline label in metadata have the same names

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by wt-huang** [comment]
Some of the fields are missing. You can use the latest TensorFlow version then compare graph definition with timeline again.

**Comment by wt-huang** [comment]
Closing as this is resolved, free to reopen if problem persists.
