### ISSUE TITLE
tensorflow-gpu install from source. Bazel tests failed

### ISSUE THREAD

**Issue by ruff21** [tensorflow/tensorflow#23073]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
Ubuntu 16.04 x86_64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
no
- TensorFlow installed from (source or binary): 
source
- TensorFlow version:
1.11
- Python version:
2.7.12
- Installed using virtualenv? pip? conda?:
virtualenv, all dependency packages using pip
- Bazel version (if compiling from source):
0.18.0
- GCC/Compiler version (if compiling from source):
gcc 5.4.0 
- CUDA/cuDNN version: 
9.0 / 7.3.1
- GPU model and memory: 
Nvidia Tesla P100 12Gb

**Describe the problem**
Hello! This is my first post on github, and I apologize in advance if my English is not clear.
I am new to Tensorflow and I try to install it (with gpu support) from source according to the [instructions](https://www.tensorflow.org/install/source#common_installation_problems)
Nvidia 384.145 drivers were pre-installed, and other dependencies too (cuda, cudnn). LD_LIBRARY_PATH and CUDA_HOME variables also set.
The whole installation takes place in virtualenv

**Provide the exact sequence of commands / steps that you executed before running into the problem**

stuck at this stage:
```
git checkout r1.11
bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/lite/...
```

**Any other info / logs**
some output after 
> bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/lite/...

```
//tensorflow/python/kernel_tests:rnn_test                  (9/10 cached) FAILED in 1 out of 10 in 5.3s
  Stats over 10 runs: max = 5.3s, min = 1.8s, avg = 3.2s, dev = 1.2s
  /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/rnn_test/shard_5_of_10/test.log
//tensorflow/contrib/lookup:lookup_ops_test                              FAILED in 4.6s
  /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/contrib/lookup/lookup_ops_test/test.log
//tensorflow/contrib/rpc/python/kernel_tests:rpc_op_test                 FAILED in 0.2s
  /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/contrib/rpc/python/kernel_tests/rpc_op_test/test.log
//tensorflow/core:util_tensor_slice_set_test                             FAILED in 0.1s
  /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/core/util_tensor_slice_set_test/test.log
//tensorflow/go:test                                                     FAILED in 0.1s
  /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/go/test/test.log
//tensorflow/python:build_info_test                                      FAILED in 0.8s
  /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/build_info_test/test.log
//tensorflow/python:flags_test                                           FAILED in 0.8s
  /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/flags_test/test.log
//tensorflow/python:stacktrace_handler_test                              FAILED in 0.8s
  /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/stacktrace_handler_test/test.log
//tensorflow/python/debug:dist_session_debug_grpc_test                   FAILED in 0.7s
  /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/debug/dist_session_debug_grpc_test/test.log
//tensorflow/python/debug:grpc_large_data_test                           FAILED in 0.7s
  /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/debug/grpc_large_data_test/test.log
//tensorflow/python/debug:session_debug_grpc_test                        FAILED in 0.8s
  /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/debug/session_debug_grpc_test/test.log
//tensorflow/python/debug:source_remote_test                             FAILED in 0.8s
  /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/debug/source_remote_test/test.log
//tensorflow/python/keras:image_test                                     FAILED in 5.8s
  /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/keras/image_test/test.log
```
log details of failed tests:
[1_rnn_test.log](https://github.com/tensorflow/tensorflow/files/2491474/1_rnn_test.log)
[2_lookup_ops_test.log](https://github.com/tensorflow/tensorflow/files/2491475/2_lookup_ops_test.log)
[3_rpc_op_test.log](https://github.com/tensorflow/tensorflow/files/2491477/3_rpc_op_test.log)
[4_util_tensor_slice_set.log](https://github.com/tensorflow/tensorflow/files/2491478/4_util_tensor_slice_set.log)
[5_go_test.log](https://github.com/tensorflow/tensorflow/files/2491479/5_go_test.log)
[6_build_info_test.log](https://github.com/tensorflow/tensorflow/files/2491480/6_build_info_test.log)
[7_flags_test.log](https://github.com/tensorflow/tensorflow/files/2491481/7_flags_test.log)
[8_stacktrace_handler_trace.log](https://github.com/tensorflow/tensorflow/files/2491482/8_stacktrace_handler_trace.log)
[9_dist_sess_debug_grpc_test.log](https://github.com/tensorflow/tensorflow/files/2491483/9_dist_sess_debug_grpc_test.log)
[10_grpc_large_data_test.log](https://github.com/tensorflow/tensorflow/files/2491484/10_grpc_large_data_test.log)
[11_sess_debug_grpc_test.log](https://github.com/tensorflow/tensorflow/files/2491485/11_sess_debug_grpc_test.log)
[12_source_remote_test.log](https://github.com/tensorflow/tensorflow/files/2491486/12_source_remote_test.log)
[13_image_test.log](https://github.com/tensorflow/tensorflow/files/2491487/13_image_test.log)

PS: some of theese logs contain error about:

> Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMAF

I hope for your help in solving this issue. Thanks!

**Comment by harshini-gadige** [comment]
@ruff21 Hi, can you try with Bazel 0.15.0 and GCC 4.8 and see if you are running into the same error.

**Comment by ruff21** [comment]
@harshini-gadige Hi, did as suggested - the error is not the same. Now bazel swears at the lack of packages '@mobile_ssd'

tried to test on r1.10 and r1.11

```
ERROR: /home/iict01/tensorflow/tensorflow/examples/android/BUILD:93:1: no such package '@mobile_ssd//': Error downloading [http://storage.googleapis.com/download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_android_export.zip, http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_android_export.zip] to /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/external/mobile_ssd/ssd_mobilenet_v1_android_export.zip: All mirrors are down: [] and referenced by '//tensorflow/examples/android:external_assets'
ERROR: Analysis of target '//tensorflow/examples/android:external_assets' failed; build aborted: no such package '@mobile_ssd//': Error downloading [http://storage.googleapis.com/download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_android_export.zip, http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_android_export.zip] to /home/iict01/.cache/bazel/_bazel_iict01/d9bbc19c8526907df6f203d5223f36ca/external/mobile_ssd/ssd_mobilenet_v1_android_export.zip: All mirrors are down: []

```

**Comment by harshini-gadige** [comment]
@gunan Can you look into this ?

**Comment by gunan** [comment]
The above does not mean the installation has failed.
You have not run configure, so failure of compilation is expected.
Also, TF has many tests, not all of which are passing all the time for every single configuration.
Please see these scripts for the test scripts we are running:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/linux/gpu/run_py3_core.sh
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/linux/gpu/run_cc_core.sh

**Comment by samhodge** [comment]
I can confrm following the instruction on how to build from source verbatim resulted in about 430 errors, but running the script mentioned by @gunan did not result in errors, perhaps the install instructions should be updated to repeat this script rather than worrying users building from source , because I need to to build from source, becaue I have an older CPU without AVX2 instructions
