### ISSUE TITLE
How to interpret feature weights from bucketized and crossed columns from a trained model in TensorFlow

### ISSUE THREAD

**Issue by jingw222** [tensorflow/tensorflow#23087]
```
Have I written custom code: NA
OS Platform and Distribution: Mac
TensorFlow installed from: pip
TensorFlow version: 1.11
Bazel version: NA
CUDA/cuDNN version: NA 
GPU model and memory: NA
Exact command to reproduce: NA 
Mobile device: NA
```

I'm currently running into a problem where I'm not able to fetch features' weight from a linear model in TensorFlow. I know how to do it when the feature columns only consist of ``numeric_column`` or ``categorical_columns_with_vocabulary_list``, unless ``bucketized_column`` or ``crossed_column`` are added additionally, especially because of **hash bins** introduced in ``crossed_column``.

The problem looks like this:

```
import tensorflow as tf
import tensorflow.feature_column as fc

x1 = [1,2,3,4,5,6,7,8]
x2 = [10,20,30,40,50]

x1_fc = fc.bucketized_column('x1', bins=[3,6])
x2_fc = fc.bucketized_column('x2', bins=[20,40])
x1_x_x2_fc = fc.indicator_column(fc.crossed_column([x1_fc, x2_fc], 7))
feature_columns = [x1_fc, x2_fc, x1_x_x2_fc]

# constuct the linear model
model = tf.estimator.LinearClassifier(feature_columns)
```

The question is that when model is trained and ready to do inferences, is there any way to inspect the predictions by looking into the model's each weight of those features (both bucketized and crossed features)? I mean the weights' values can be extracted without an issue, but I struggle to interpret those values associated with my original inputs.

Besides, for my experiences, when I only use ``numeric_column`` in the model, I do notice that the features are ordered alphabetically in the weights layer, which is somewhat weird to me.

[This answer][1] does not seem very natural, and can be hard to implement when feature number grows or the **hash bins** gets large.

  [1]: https://stackoverflow.com/questions/47282229/tensorflow-inspecting-hash-buckets-for-categorical-and-feature-columns

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, along with minimal repro example. Thanks!
