### ISSUE TITLE
Theano-like scan non-sequences

### ISSUE THREAD

**Issue by petrbel** [tensorflow/tensorflow#2308]
It would be nice to add some functionality that allows passing non-sequences to `scan` function (introduced in 0.8.0). [Theano implements this feature](http://deeplearning.net/software/theano/library/scan.html) and it is very useful.

The suggested usage could be (pseudocode):
```python
scan(fn=lambda state, c1, c2, el: state+c1+c2+el,
     elems=[10,20,30],
     initializer=[0],
     non_sequences=[1, 2])
```
The first argument could be the last output (state), then all `non_sequences` could be passed and, finally, the current input `el`. The pseudocode above would produce the following operations:
```
0 +1+2+10 => 13
13+1+2+20 => 26
26+1+2+30 => 59
```

Unfortunatelly I haven't found any hack that would achieve the same behavior (especially when `non_sequences` contain objects other than tensors, such as `GruCells`). Maybe there is some, in that case I would really appreciate some hint :)

I believe that this, together with #2294, would help developers to write their scans equally effectively as they do in theno.

**Comment by yuanbyu** [comment]
Have you tried the following?

```
c1 = tf.constant(1)
c2 = tf.constant(2)
scan(fn=lambda state, el: state+c1+c2+el,
     elems=[10,20,30],
     initializer=[0])
```

**Comment by petrbel** [comment]
@yuanbyu thanks for prompt reply. Well, yes, in such simple case this works.

However, imagine that `c1` is `GruCell`. It is forbidden to access such computational nodes that are not passed directly by scan from the inner function (afaik).

@vojtsek could give more description of the problem with scan and using the variable that are not passed by it.

**Comment by yuanbyu** [comment]
I don't quite understand your `GruCell` example. Could you provide a concrete example?

**Comment by vojtsek** [comment]
@yuanbyu Hi, the actual part of code looks like this:

`state_Tbh = scan(fn=process_turn,
                     elems=tf.transpose(embedded_input_bTte, perm=[1, 0, 2, 3]),
                     initializer=init_state_bh)`

Here we scan through a sequence of states and inputs. The problem is, that we want to use `GRUCell` inside the `process_turn` function. We don't want to initialize it in each turn. If we pass it from the outer scope like you suggested with the constants, it does not compile.

**Comment by yuanbyu** [comment]
Is it a python compile error or a TensorFlow graph build error?

**Comment by petrbel** [comment]
@yuanbyu it is tensorflow error that occurs on graph compilation

**Comment by yuanbyu** [comment]
Would it be possible to create a simple example that could reproduce the problem? It looks like a bug.

**Comment by vojtsek** [comment]
@yuanbyu While I was creating the reproducing example I realised, that we have made different kind of mistake in our code. We just mistakenly thought that this is a problem. My simple example uses the mechanism described above and works just fine, so there is actually no issue to be solved. Sorry for that and thanks for your help.

**Comment by petrbel** [comment]
So just to sum up, TensorFlow offers more comfortable way of passing non-sequences than Theano. Even though I still miss the feature described in #2294, I am happy that this is supported :)

**Comment by gaceladri** [comment]
Sorry for reopening this. @petrbel I am looking for the same function. I am implementing a GRULayer from Theano that have a scan function. It's a little bit late but how did you implemented the `non_sequences` part from the scan function?

**Comment by petrbel** [comment]
@vojtsek do you have the code for @gaceladri ? I can't find it...
