### ISSUE TITLE
Slice all but last element of tensor

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#2309]
I'm trying to slice all but the last element of a tensor, equivalent to python's `a[:-1]`. However, I understand that tensorflow instead uses a start and size rather than start and end for slicing. My current workaround is to do something like this:
```
a = tf.constant([1, 2, 3, 4])
# b = [1, 2, 3]
b = tf.reverse(tf.reverse(a, [True])[1:], [True])
```
This is obviously a bit awkward, and potentially inefficient. Is there a better way to do this?

**Comment by vladfi1** [comment]
I've figured out that I can get the right size even if the shape is `[None]` by using `tf.shape` to get the shape and then subtracting 1 (or whatever desired offset from the end).

**Comment by milsto** [comment]
As much as I have tested, [tf.strided_slice](https://www.tensorflow.org/api_docs/python/tf/strided_slice) supports negative _end_ indexing, i.e. if you specify -N in any dimension for _end_ parameter, you will slice all but last N elements. This works, but is not documented (even thou negative strides are documented)

For example:
```python
a = tf.constant([1, 2, 3, 4, 5])
b = tf.strided_slice(test, [0], [-1], [1])
c = tf.strided_slice(test, [0], [-2], [1])

# shape of b will be (4,)
# shape of c will be (3,)

d = tf.constant([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
e = tf.strided_slice(test, [0, 0], [2, -2], [1, 1])

# shape of e will be (2, 3) 
```

Also, TensorFlow now supports slicing exactly as in numpy, so the flowing would be equivalent to the above examples (and will actually call tf.strided_slice in background as stated in documentation):

```python
a = tf.constant([1, 2, 3, 4, 5])
b = a[:-1]
c = a[:-2]
d = tf.constant([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
e = d[:2, :-2]
```

Everything works with placeholders with None dimensions also. Similar behavior is not supported by [tf.slice](https://www.tensorflow.org/api_docs/python/tf/slice).
