### ISSUE TITLE
Upgrade to protobuf 3.6.1  

### ISSUE THREAD

**Issue by scentini** [tensorflow/tensorflow#23100]
An incompatible change in Bazel: https://github.com/bazelbuild/bazel/issues/6384 breaks Tensorflow on Windows: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/498#3e15d20b-30a5-4071-8c3f-ce7425ce5f35. The breakage comes from using protobuf 3.6.0.

Protobuf 3.6.1 is compatible with the change.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment]
Closing as PR is merged.
