### ISSUE TITLE
Bug: tf.app.run() does not allow to import ipdb

### ISSUE THREAD

**Issue by MarvinTeichmann** [tensorflow/tensorflow#2310]
When using tensorflow with `tf.app.run()` one cannot `import ipdb`. I have tested several Tensorflow Versions and did run Tensorflow in several environments, all of them seems to be affected by this Bug.

The following script provides a minimal Example reproducing the error:

```
#!/usr/bin/env python
import ipdb
import tensorflow as tf


def main(_):
    """Run main function."""
    print("Hello World.")


if __name__ == '__main__':
    tf.app.run()
```

Executing the  script yields the following error message:

```
Traceback (most recent call last):
  File "tensorapp.py", line 14, in <module>
    tf.app.run()
  File "/home/marvin/.virtualenvs/tensorvision/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 29, in run
    main = main or sys.modules['__main__'].main
AttributeError: 'module' object has no attribute 'main'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

### Environment info
Operating System: Linux (varies)

Effected Tensorflow Versions: 0.7.0; 0.7.1; 0.8.0 

1. Which pip package you installed. https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
2. The output from python -c "import tensorflow; print(tensorflow.__version__)": 0.8.0

### Steps to reproduce
1. Run provided script

**Comment by mrry** [comment]
Which version of `ipdb` are you using? It looks like an issue regarding `sys.modules['__main__']` was recently closed: https://github.com/gotcha/ipdb/issues/85.

**Comment by MarvinTeichmann** [comment]
Version 0.10.0. So the cited patch is already applied.

```
pip freeze | grep ipdb
ipdb==0.10.0
pip freeze | grep ipython
ipython==4.2.0
```

**Comment by mrry** [comment]
OK, it looks like `ipdb` does something strange to `sys.modules`:

```python
import sys
print sys.modules['__main__']
import ipdb
print sys.modules['__main__']
```
...yields the following output:
```
$ python script.py
<module '__main__' from 'script.py'>
<module '__main__' (built-in)>]
```

I'm not sure if it's feasible to fix this. Two alternatives present themselves:

1. Call `tf.app.run(main=main)`.
2. Place the `import ipdb` statement in the `main()` function itself.

**Comment by girving** [comment]
@mrry: Feel free to close if you still think fixing it is infeasible.

**Comment by mrry** [comment]
Closing as infeasible.
