### ISSUE TITLE
compile from source fails

### ISSUE THREAD

**Issue by C0NTRIBUTE** [tensorflow/tensorflow#23102]
**System information**
- Ubuntu 18.04
- From source / r1.12
- TensorFlow version:
- Python 3.6.6
- Inside virtualenv
- Bazel 0.18.0
- gcc 6.4.0
- Cuda 9 / Cudnn 7

**The problem**
Building from source, I end up with: 

```
ERROR: /home/dev/tensorflow/tensorflow/core/BUILD:319:1: undeclared inclusion(s) in rule '//tensorflow/core:platform_base':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/platform/env_time.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h'
  '/usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/6/include/stdarg.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.460s, Critical Path: 0.26s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```
This is when I run: 

`bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

Also note that if I repeat the command several times, I don't always get the same error message. After I do `bazel clean` I get: 

```
ERROR: /home/.cache/bazel/_bazel_nnnnn/75c0d842b4eca8fbdb48dc37e31275de/external/protobuf_archive/BUILD:659:1: C++ compilation of rule '@protobuf_archive//:python/google/protobuf/pyext/_message.so' failed (Exit 1)
In file included from external/protobuf_archive/python/google/protobuf/pyext/map_container.cc:33:0:
external/protobuf_archive/python/google/protobuf/pyext/map_container.h:34:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.

```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment]
@C0NTRIBUTE Have you tried installing TensorFlow from binary?
