### ISSUE TITLE
Can tf.sparse_reduce_sum infer shape while keepdims=True?

### ISSUE THREAD

**Issue by gongliyu** [tensorflow/tensorflow#23114]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.11
- Are you willing to contribute it (Yes/No): 
No. Sorry, I'm not familiar with the TF codebase.

**Describe the feature and the current behavior/state.**
tf.sparse_reduce_sum should be able to infer the shape if the input has known shape.
```pythonIn [1]: import tensorflow as tf

In [2]: x = tf.SparseTensor(indices=[[0,0],[1,1]], values=[1,2], dense_shape=[2,2])

In [3]: tf.sparse_reduce_sum(x)
Out[3]: <tf.Tensor 'SparseReduceSum:0' shape=<unknown> dtype=int32>

In [4]: tf.sparse_reduce_sum(x, axis=1, keepdims=True)
Out[4]: <tf.Tensor 'SparseReduceSum_1:0' shape=<unknown> dtype=int32>
```

**Will this change the current api? How?** 
No.
**Who will benefit with this feature?**
Users who use TensorFlow to do graph learning
**Any Other info.**

Hi, please check the following information, thanks!

Have I written custom code
N/A

OS Platform and Distribution
Windows 10

TensorFlow installed from
conda -c anaconda tensorflow-gpu

Bazel version
N/A

CUDA/cuDNN version
9.0/7.1.4

GPU model and memory
Quadro M520 2GB memory

Exact command to reproduce
describe in the original post

Mobile device
N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by gongliyu** [comment]
Hi, please check the following information, thanks!

Have I written custom code
N/A

OS Platform and Distribution
Windows 10

TensorFlow installed from
conda -c anaconda tensorflow-gpu

Bazel version
N/A

CUDA/cuDNN version
9.0/7.1.4

GPU model and memory
Quadro M520 2GB memory

Exact command to reproduce
describe in the original post

Mobile device
N/A

**Comment by gongliyu** [comment]
Hi, please check the following information, thanks!

Have I written custom code
N/A

OS Platform and Distribution
Windows 10

TensorFlow installed from
conda -c anaconda tensorflow-gpu

Bazel version
N/A

CUDA/cuDNN version
9.0/7.1.4

GPU model and memory
Quadro M520 2GB memory

Exact command to reproduce
describe in the original post

Mobile device
N/A

**Comment by yongtang** [comment]
Added a PR #23271 for the fix.

**Comment by wt-huang** [comment]
Thanks for the PR @yongtang
