### ISSUE TITLE
global name 'cuda_toolkit_path_full' is not defined

### ISSUE THREAD

**Issue by toli-belo** [tensorflow/tensorflow#23119]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 18.04.1 LTS  64 bit
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**:   Source
- **TensorFlow Version**:  r.1.11  
- **Python version**:  3.6
- **Bazel version (if compiling from source)**:  0.15.2 (tried/same problem with 0.15.2, 1.16.1, 0.18.0)
- **GCC/Compiler version (if compiling from source)**:  7.3.0
- **CUDA/cuDNN version**:  10.0 / 7.7.3
- **GPU model and memory**: RTX 2080 TI 11GB
- **Exact command to reproduce**:  ./configure with answers below

### Describe the problem
configure fails with following error:

anatolii@workstation:~/tensorflow$ ./configure
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.15.2 installed.
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3

Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.6/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]

Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: 
jemalloc as malloc support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Google Cloud Platform support? [Y/n]: 
Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [Y/n]: 
Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Amazon AWS Platform support? [Y/n]: 
Amazon AWS Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Apache Kafka Platform support? [Y/n]: 
Apache Kafka Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]: 
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with GDR support? [y/N]: 
No GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: 
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with nGraph support? [y/N]: 
No nGraph support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 9.0]: CUDA 10.0

Please specify the location where CUDA CUDA 10.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 

Traceback (most recent call last):
  File "./configure.py", line 1592, in <module>
    main()
  File "./configure.py", line 1527, in main
    set_tf_cuda_version(environ_cp)
  File "./configure.py", line 855, in set_tf_cuda_version
    (tf_cuda_version, cuda_toolkit_path_full))
NameError: global name 'cuda_toolkit_path_full' is not defined

**Comment by ymodak** [comment]
TensorFlow officially supports CUDA 9.0. However it is compatible with CUDA 10.0 but not supported currently. For using TF with cuda 10, you have to build it from sources yourself. You need to update the **"./configure.py"** file with appropriate CUDA, cuDNN versions. You can also take a look at [installations](https://medium.com/@vitali.usau/install-cuda-10-0-cudnn-7-3-and-build-tensorflow-gpu-from-source-on-ubuntu-18-04-3daf720b83fe) done by another users to make it work.

**Comment by toli-belo** [comment]
@ymodak  - sorry I don't see any notes on modifying configure.py at the installations link you mentioned, perhaps you meant that CUDA version is to be typed when running `configure` ? - because that I did, as shown in the issue description above. Please clarify. thanks!

**Comment by ymodak** [comment]
Yes, I see now that you have already mentioned CUDA version 10. Did you add CUDA path variable in the bashrc file? The link in previous comments mentions the changes you need to adopt to build successfully for CUDA 10. I recommend that you follow the tutorial and build again, since I may be missing some points.

**Comment by toli-belo** [comment]
yep, I had modified PATH and LD_LIBRARY_PATH in ~/.profile to reflect /usr/local/cuda-10.0/bin and lib64 respectively.

**Comment by Sergei-Lebedev** [comment]
@toli-belo
I think you need to specify "10.0" instead of "CUDA 10.0" when it asks you for cuda version

**Comment by ymodak** [comment]
Is this still an issue? Did you get a chance to follow the tutorial I sent in previous comment?

**Comment by yangyangxcf** [comment]
I met the same error.
I looked into `configure.py` and found the code below
```python
cuda_toolkit_paths_full = [os.path.join(cuda_toolkit_path, x) for x in cuda_rt_lib_paths]
......(4 lines here)
print('Invalid path to CUDA %s toolkit. %s cannot be found' %
      (tf_cuda_version, cuda_toolkit_path_full))
```
The `print` is where the error happened, so I think it's just a misspelling…
The script wants to tell you that your path to CUDA is invalid, so maybe check again the location you tell the script where CUDA is installed.

**Comment by toli-belo** [comment]
thanks everyone! I was able to build tensorflow with cuda 10
