### ISSUE TITLE
Pure Virtual Method called - build for ARMv7 

### ISSUE THREAD

**Issue by wallarug** [tensorflow/tensorflow#23118]
**System information**
- OS Platform and Distribution:  Linux Debian 8 Jessie
- TensorFlow installed from: source
- TensorFlow version: r1.12
- Python version: 3.4.2
- compiled and built as per instructions on Ubuntu 18.04.1 cross-compile for Raspberry Pi: https://www.tensorflow.org/install/source_rpi

**Problem**
When running tensorflow on my device, the following error is thrown when accessing any cameras using the tensorflow.python.keras.layers.Input() method:
```
pure virtual method called
terminate called without an active exception
Aborted
```
The device uses an R8 ARMv7 processor 

**Commands / Steps**
```
from tensorflow.python.keras.layers import Input
```

```
img_in = Input(shape=(120, 160, 3), name='img_in')
```

**Any other info / logs**

Complete system output:
```
chip@chip:~/mycar$ python3
Python 3.4.2 (default, Sep 26 2018, 05:38:50)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.python.keras.layers import Input
>>> img_in = Input(shape=(120, 160, 3), name='img_in')
pure virtual method called
terminate called without an active exception
Aborted
```

We have done some research on this issue and have not found too many similar cases.  We found one similar issue that stated that removing the marsh flag from compile would resolve the issue, however, this was not the case.

Any help would be greatly appreciated.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tracihuang9** [comment]
@wallarug See if you can upgrade to Raspbian 9 Stretch from Jessie.
Also, try to use pre-built binaries for TensorFlow installation.

**Comment by wt-huang** [comment]
@wallarug See if you can upgrade to Raspbian 9 Stretch from Jessie.
Also, try to use pre-built binaries for TensorFlow installation.

**Comment by wt-huang** [comment]
Closing as this should be resolved by the approach suggested, free to reopen if problem persists

**Comment by rampageservices** [comment]
The target device is not a raspberry pi, it is a CHIP. Please reopen the issue.
