### ISSUE TITLE
Problems when building tensorflow with CUDA

### ISSUE THREAD

**Issue by light82** [tensorflow/tensorflow#23127]
When I built tensorflow from source with CUDA using bazel,I got the following errors:

    external/com_google_absl/absl/strings/string_view.h(496): warning: expression has no effect
    external/com_google_absl/absl/strings/str_cat.h(259): error: expression must have a constant value
    external/com_google_absl/absl/strings/str_cat.h(259): error: expression must have a constant value

I add some codes like `std::cout<<"using cpu for Launch<Device>"<<std::endl;`.Is there anything wrong? Thanks for any help.

**Comment by troycheng** [comment]
also met this problem when compiling tensorflow serving with GPU：
OS: CentOS 7.5.1804
Bazel: 0.18.0
CUDA: 8.0
cuDNN: 7.1.3 for CUDA 8.0

**Comment by wt-huang** [comment]
You can try to install [tensorflow-gpu from anaconda](https://anaconda.org/anaconda/tensorflow-gpu)

**Comment by jinze1994** [comment]
We want to install from source rather than anaconda. Still, I have exactly the same errors when compiling on centos7 too.  @wt-huang

**Comment by peppaseven** [comment]
I also have same issue...
OS: ubuntu 16.04
Bazel: 0.16.0
CUDA: 8.0
cuDNN: 7.1.3 for CUDA 8.0
GCC: 4.9

**Comment by edoardogiacomello** [comment]
Also for me:
OS: ubuntu 16.04
Bazel: 0.19.2
CUDA: 8.0
cuDNN: 7.1.3 for CUDA 8.0
GCC: 5.4

building inside a nvidia/cuda:8.0-cudnn7-devel container.

**Comment by azazhu** [comment]
i met same issue. I use cuda8.0. Is it due to cuda8.0?

**Comment by eLvErDe** [comment]
Why closing... The bug is here for sure and it's probably not that hard to fix....

**Comment by wuyankun** [comment]
Yes, I still meet this bug.
OS:gentoo 
command:emerge  1.12.0
CUDA:cuda 8.0
CUDNN:6.0
gcc:4.9

**Comment by wuyankun** [comment]
Yes, I still meet this bug.
OS:gentoo 
command:emerge  1.12.0
CUDA:cuda 8.0
CUDNN:6.0
gcc:4.9
bazel: 0.20.0

I can cmake the abseil-cpp , there is no error. maybe someone can help to fix it.

**Comment by yunjiangster** [comment]
I have no problem building tensorflow_model_server with only cpu support, but gpu (--config=cuda) fails at link time.

Build Command: 
export TF_NCCL_VERSION=1.3
export TF_NEED_CUDA=1
export NCCL_INSTALL_PATH=/usr/local/cuda
bazel clean --expunge &&  bazel build -c opt --config=cuda --action_env PYTHON_BIN_PATH=~/tf/bin/python tensorflow_serving/model_servers/...

Also tried building tensorflow_serving/model_servers:tensorflow_model_server alone, and got the same error below.

Here is an excerpt of the linking error:
Linking of rule '//tfs/tensorflow_serving/model_servers:tensorflow_model_server' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
...
/usr/bin/ld: external/com_3rd_party/zlib/lib/libz.a(inflate.o): relocation R_X86_64_32S against `zcfree' can not be used when making a shared object; recompile with -fPIC
external/com_3rd_party/zlib/lib/libz.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Target //tfs/tensorflow_serving/model_servers:tensorflow_model_server failed to build
INFO: Elapsed time: 1.149s, Critical Path: 0.15s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

My environment:
OS: Centos 7
CUDA: 9.0
Cudnn: 7.0
gcc 4.8.5
bazel: 0.16.1

**Comment by troycheng** [comment]
@yunjiangster try clean previous build and add `--copt="-fPIC"` and then build again.

**Comment by yunjiangster** [comment]
@troycheng thank you for the thorough advice, very helpful for future reference.  I think the problem was due to other third-party dependencies we added to the build rule, like com_3rd_party/zlib/lib/libz.a. I tried --copt="-fPIC" in the past and that resulted in similar error.

**Comment by troycheng** [comment]
@yunjiangster It's a pleasure. Since the libz.a is compiled standalone, just add -fPIC and recompile zlib again. It's a common problem when building shared/static library.  There are some explanations here, [https://stackoverflow.com/questions/5311515/gcc-fpic-option](url)
