### ISSUE TITLE
Batched gather

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#2313]
This is related to #2170, which describes how to use `tf.gather` to index on the first dimension of a tensor. What I'd like to do now is batch this operation:
```
params = tf.constant([[1, 2], [3, 4], [5. 6]])
indices = tf.constant([0, 1, 0])
gathered = tf.batch_gather(params, indices)
# gathered = [1, 4, 5]
```

**Comment by mrry** [comment]
You might be able to do this using `tf.gather_nd()`, but this will ultimately be addressed by the support for enhanced slicing.

Closing as a duplicate of #206.
