### ISSUE TITLE
openrave gives me segfaults

### ISSUE THREAD

**Issue by mohamadmahdavian** [tensorflow/tensorflow#23140]
Hello Everyone. First of all I have to apologize if my question may not be clear. Because I'm a newbie in Ubuntu.  I tried to install pymanoid package and I was using openrave to test Inverse Kinematic example. After everything was installed correctly when I opened Inverse Kinematic python example I could see the robot but there was something that I thought was an error in terminal:
[0;34mIn [[1;34m1[0;34m]: [0m

I searched about it and someone was suggesting to install lib32ncurses5-dev. After that whenver I open the same python file(IK example) I get segmentation fault and I can't solve the problem. I tried to remove lib32ncurses5-dev and its dependencies, but still I have the same problem. 
Does anyone know how can I fix it?

This is what happens:
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Segmentation fault (core dumped)

**Comment by harshini-gadige** [comment]
@mohamadmahdavian Hi, we request you to post this issue in the relevant github repository as this repo is for Tensorflow related issues. If you think this is a tensorflow issue, please provide further details as asked by tensorflowbutler. Thank you !
