### ISSUE TITLE
Mysterious infinite run

### ISSUE THREAD

**Issue by dy-octa** [tensorflow/tensorflow#23158]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.9.0
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 9.1.85
- GPU model and memory: P100 16GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Update: I've managed to make a minimal example here: https://github.com/tensorflow/tensorflow/issues/23159**
Please close this issue.

        check_vars = model.trainable_variables()  

        check_grad = tf.cond(cond,  

                                  lambda :[g if isinstance(g, tf.Tensor) else 0.0 for g in  

                                           tf.gradients(model.loss, check_vars)],  

                                  lambda : [0.0] * len(check_vars))  

        sess.run(check_grad)  
In my own model (a Tacotron2 implementation), the last line will fall into infinite run and never return when tf is run on GPU and cond holds False, i.e. it should directly return a tensor of zeros, while the results will be correct when tf is run on CPU, or cond holds True.
**Describe the expected behavior**

**Code to reproduce the issue**
I didn't manage to reproduce the case on a model simple enough.
**Other info / logs**

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by dy-octa** [comment]
I've managed to make a minimal example here: #23159
Please close this issue.
