### ISSUE TITLE
Try to build label_image:main.cc on Android

### ISSUE THREAD

**Issue by neverPick** [tensorflow/tensorflow#2316]
1.If I build  tensorflow_jni.cc with the BUILD file in label_image,I added android_binary.it ask me to compile with -std=c++.because the ndk r10e running with GCC4.9.I donot know how to set -std=c++11.
2.If I build it with .mk.and copy the .h files in bazel-genfiles/tensorflow/cc/ops,like array_ops.h etc,  to tensorflow folder,setted include like this
`#include "tensorflow/cc/ops/array_ops.h"
#include "tensorflow/cc/ops/const_op.h"
#include "tensorflow/cc/ops/data_flow_ops.h"
#include "tensorflow/cc/ops/image_ops.h"`...
it give me:
`jni/./tensorflow_jni.cc:132: error: undefined reference to 'tensorflow::ops::Cast(tensorflow::NodeBuilder::NodeOut, tensorflow::DataType, tensorflow::GraphDefBuilder::Options const&)'`
for every tensorflow::ops:: method.it seems,ndk have found the method ,but not compile?
3.Did any guies build label_image:main.cc on Android?
the android demo on tensorflow does not working will with my own graph,retrained by image_retraining .

**Comment by petewarden** [comment]
Sorry you're hitting problems! The best way to tackle this is to update the Android Demo to handle retrained models, so I will work on that.

**Comment by neverPick** [comment]
thx，I am waiting for the new demo now.
