### ISSUE TITLE
Install the latest version whl of tensorflow from Jenkins daily build system, but can not find a part of the directory。

### ISSUE THREAD

**Issue by ismymajia** [tensorflow/tensorflow#2317]
hello, i have a question:

Operating System:
ubuntu 14.04

question：
Install the latest version whl of tensorflow from Jenkins daily build system, but can not find a part of the directory。

If installed from binary pip package, provide:
1. Which pip package you installed.

first download the latest stable package:

http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_CONTAINER_TYPE=CPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/lastStableBuild/

2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

>>> import tensorflow; print(tensorflow.__version__)
0.8.0

### Steps to reproduce
1.  pip uninstall tensorflow
2.  pip install  --upgrade  tensorflow-0.8.0-cp27-none-linux_x86_64.whl  

### What have you tried?
1. in  the  path anaconda2\envs\tensorflow\lib\python2.7\site-packages\tensorflow\models\image dictionary，can not find the alexnet and imagenet dictionary, but can find them from the github path https://github.com/tensorflow/tensorflow/tree/master/tensorflow/models/image.

how can i update to get alexnet and imagenet dictionary?

**Comment by martinwicke** [comment]
I am fixing this for the future. For now, you can simply clone the tensorflow repository (the r0.8 branch if you want to be consistent with your binaries), and copy the `alexnet` and `imagenet` directories from the cloned directory into the `anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/models` directory.
