### ISSUE TITLE
Provide Clear Instructions to build tensorflow from source

### ISSUE THREAD

**Issue by radiantone** [tensorflow/tensorflow#23183]
Hi
  The instructions to build tensorflow from source are not clear, simple or easy to understand.

I would like a concise set of steps to build tensorflow from source for ubuntu 16.04

Thanks+

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment]
@radiantone You can follow the instruction guide. Let us know which part you don't understand.
We do recommend building TensorFlow from source.
