### ISSUE TITLE
CUDA 9.1 and Tensorflow GPU 1.5.0 Visual Studio 2017 and Python 3.6 error

### ISSUE THREAD

**Issue by debadridtt** [tensorflow/tensorflow#23184]
I installed CUDA 9.1, cuDNN 7.31 for CUDA 9.1 and I have installed Visual Studio 2017. However when I run the CUDA samples I get these following outputs:
![capture](https://user-images.githubusercontent.com/24243687/47340754-d2955d80-d6bc-11e8-8f8c-c4dad2375cf6.PNG)
![3](https://user-images.githubusercontent.com/24243687/47340755-d45f2100-d6bc-11e8-8223-2e3146168de0.PNG)

But when I try to fit my model using tensorflow-gpu it show "python.exe" stopped working and then when I click Debug, I get this output inside my Visual Studio 2017:
![2](https://user-images.githubusercontent.com/24243687/47340798-ee006880-d6bc-11e8-8197-b50eb52d57c9.PNG)

Any idea what might fix this issue?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ymodak** [comment]
TensorFlow expects [CUDA 9.0](https://www.tensorflow.org/install/gpu#software_requirements). Please install version 9.0 and change the [path var].(https://www.tensorflow.org/install/gpu#windows_setup).

**Comment by debadridtt** [comment]
Anyway I fixed this issue through this process of installation: https://www.pugetsystems.com/labs/hpc/Install-TensorFlow-with-GPU-Support-on-Windows-10-without-a-full-CUDA-install-1172/
