### ISSUE TITLE
tf.constant does not raise an error if too few values are provided

### ISSUE THREAD

**Issue by shoyer** [tensorflow/tensorflow#2319]
It is difficult to see the current behavior (repeating the final value) being useful for anyone:
```
>>> tf.constant(np.arange(5), shape=(10,)).eval()
array([0, 1, 2, 3, 4, 4, 4, 4, 4, 4])
```

In contrast, there is a sensible error message if too many values are provided:
```
>>> tf.constant(np.arange(5), shape=(3,)).eval()
ValueError: Too many elements provided. Needed at most 3, but received 5
```

I am running the internal version of TensorFlow.

**Comment by mrry** [comment]
This is intentional behavior. Many users write e.g. `tf.constant(4.0, shape=[100, 100])` to generate a tensor filled with a given value. Supporting this for non-scalars is more questionable, but might be required for backwards compatibility.

**Comment by shoyer** [comment]
Should I raise a separate issue for non-scalars then? The behavior is surprising and in my opinion quite likely to result in bugs. It's true that it's documented, though.
