### ISSUE TITLE
Problem mixing tf.cast and tf.control_dependencies

### ISSUE THREAD

**Issue by pisiiki** [tensorflow/tensorflow#23199]
**System information**
- Windows 10 1809.
- TensorFlow installed from (source or binary): binary.
- TensorFlow version (use command below): 1.11.0 (cpu).
- Python version: 3.6.6.

**Describe the current behavior**

Returns inf.

**Describe the expected behavior**

Should return 1.0.

**Code to reproduce the issue**
```
import tensorflow as tf

with tf.Session() as sess:
    n = tf.Variable(initial_value=0, dtype=tf.int32)
    v = tf.Variable(initial_value=1., dtype=tf.float32)

    inc_n = tf.assign_add(n, 1)
    foo = 1. / tf.cast(n, tf.float32)

    with tf.control_dependencies([inc_n]):
        test = tf.assign(v, foo) # doesn't work
        # test = tf.assign(v, 1. / tf.cast(n, tf.float32)) # works

    sess.run(tf.global_variables_initializer())
    print(sess.run(test))
```

**Other info / logs**

Also tested it on ubuntu 18, tf 1.11 gpu (from source, cuda 10), works fine.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by pisiiki** [comment]
OS Platform and Distribution: Windows 10 1809.
Bazel version: N/A (using binary).
CUDA/cuDNN version: N/A (using cpu).
GPU model and memory: N/A (using cpu).
Exact command to reproduce: Source code included.
Mobile device: N/A.

**Comment by wt-huang** [comment]
@pisiiki When using `inc_n = tf.assign_add(n, 1)`, you need to make sure that the 2 args have the same type, which is not the case in the above code.  You would want to fix that before using `tf.control_dependencies()`.

**Comment by wt-huang** [comment]
@pisiiki They are not the same data type, v and foo are not the same type either. The above code has the same issue on Linux and returns inf too. 
The tf.control_dependencies is nothing but a wrapper for Graph.control_dependencies() using the default graph. You can also convert from one data type to the other.

**Comment by pisiiki** [comment]
@wt-huang thanks for the explanation. I have refactored my code to rely less on tf variables. I was trying to limit state copying between python and tf for some sequence modelling experiments but the resulting code was very tricky to write and understand. Also I'm on v1.12 now so I'm good to go now.
