### ISSUE TITLE
What are the differences between cold_start_filter and filter_continuation ?

### ISSUE THREAD

**Issue by StevenLOL** [tensorflow/tensorflow#23202]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: Master
- Doc Link:
https://www.tensorflow.org/api_docs/python/tf/contrib/timeseries/saved_model_utils/cold_start_filter

**Describe the documentation issue**

It is not clear what are the differences between  cold_start_filter and filter_continuation. And in what condition they should be used? 

And for "Filtering refers to updating model state based on new observations." , is the model state == model ? why one should update it  ?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment]
@StevenLOL  
- Both cold_start_filter and filter_continuation update model state based on new observations.
- cold_start_filter starts from the model's default or uninformed state. filter_continuation applies filtering subsequent to cold_start_filter. 
- Model state is not the same as model, the former is being updated with new  observations in features and normally contains previous and current cell information depending on how you build the model. 
- The reason behind filtering is you need to update model state based on new observation in time series.
