### ISSUE TITLE
static_rnn has no remind

### ISSUE THREAD

**Issue by weiyinfu** [tensorflow/tensorflow#23205]
pip show tensorflow-gpu
Name: tensorflow-gpu
Version: 1.11.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: c:\anaconda\lib\site-packages
Requires: protobuf, termcolor, wheel, keras-applications, setuptools, absl-py, grpcio, six, gast, astor, numpy, keras-preprocessing, tensorboard

Lib/site-packages/tensorflow/nn/__init__.py has something wrong

```python
from tensorflow.python.ops.nn import static_rnn  wrong
from tensorflow.python.ops.rnn import static_rnn right
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by harshini-gadige** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new). Please provide all the information it asks. Thank you.

**Comment by weiyinfu** [comment]
When I use RNN, I cannot find the source code of `static_rnn` function.

The below is the reason :
Lib/site-packages/tensorflow/nn/init.py has something wrong

This file is one of the tensorflow-gpu library .
And the reason is wrong package .

* wrong
```python
from tensorflow.python.ops.nn import static_rnn  
```
* right
```python
from tensorflow.python.ops.rnn import static_rnn
```

**Comment by weiyinfu** [comment]
You can write a program like below and try to view the source code of static_rnn

```python
import tensorflow as tf
x=tf.nn.static_rnn
```
