### ISSUE TITLE
TfLiteCameraDemo.apk with NNAPI

### ISSUE THREAD

**Issue by eli7310** [tensorflow/tensorflow#23208]
Can someone please upload a version of TfLiteCameraDemo.apk that supports NNAPI?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment]
You can download TfLiteCameraDemo.apk from [TensorFlow Android Demo App](https://www.tensorflow.org/lite/demo_android) or write your own app to support whichever version.

**Comment by wt-huang** [comment]
Closing as this is resolved, free to reopen if problem persists.
