### ISSUE TITLE
examples/udacity/1_notmnist.ipynb image normalization is not equal to Udacity video

### ISSUE THREAD

**Issue by DKaravolos** [tensorflow/tensorflow#2320]
Hi,
This is just a minor thing, but it might be confusing for people who follow the Udacity course. The video about normalization of the input (https://www.youtube.com/watch?v=0mxNQA95mYE) describes the normalization as: pixel_value - 128 / 128. However the code seems to compute: pixel_value - 128 / 255 (since pixel_depth = 255). This changes the range of the data from -1 to 1 into -0.5 to 0.5 and might be confusing for people who blindly copy the function and expect it to work like in the video.

**Comment by DKaravolos** [comment]
Sorry for posting it here, but I could not find another location to post issues like this.

**Comment by vincentvanhoucke** [comment]
That's true. Maybe what this discrepancy conveys is that it doesn't matter :) Happy to take a PR if you think it should be changed, but please make sure the results don't change in unexpected ways as a result.

**Comment by vincentvanhoucke** [comment]
Closing pending PR since this is not a mandatory fix.

**Comment by DKaravolos** [comment]
You are right, it does not really matter for the tutorial. I was just surprised to see it when I reused the code. I thought it might be worth a comment in the code or the course. But I'm new to this, so do with it as you see fit. (thanks for the videos by the way, they were really useful)
