### ISSUE TITLE
expect delta_delta op for speech

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#23209]
delta_delta is common in speech task, expected to be implemented. And also expect to expand the feature op of audio process in future.

**System information**
- TF1.11
- No

**Describe the feature and the current behavior/state.**
add delta_detla Op to audio feature 

**Who will benefit with this feature?**
people  who doing ASR.

**Any Other info.**

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment]
Along with other transformations, delta_delta is common in speech tasks. You can leverage math libraries such as scipy to write your own function and take advantage of its abundant fft libraries.

**Comment by zh794390558** [comment]
@wt-huang  I want using TF to deploy APP，and make the feature extraction as one part of graph. So the common pipeline of speech is important.

**Comment by zh794390558** [comment]
see https://github.com/didi/delta/blob/master/delta/layers/ops/kernels/delta_delta_op.cc
