### ISSUE TITLE
Different inference time on my computer and server with the same gpu

### ISSUE THREAD

**Issue by ningningG** [tensorflow/tensorflow#23210]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Win10

- TensorFlow installed from (source or binary):
anaconda3

- TensorFlow version (use command below):
tensorflow-gpu1.11.0

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A

- Python version:
python3.6.6

- Bazel version (if compiling from source): N/A

- GCC/Compiler version (if compiling from source): N/A

- CUDA/cuDNN version:
CUDA9.0

- GPU model and memory:
NVIDIA GeForce GTX 1080 Ti  11264MiB

**Describe the current behavior**
I have trained a 2 classified ResNet18， when I use it for inference on different machine, the time is as follow:
about 2.0s on my conputer，
about 1.6s on my workmate's computer (win10,  tensorflow-gpu of version 1.9, python 3.6.6, CUDA9.0,  NVIDIA GeForce GTX 1080 Ti 11264MiB)， 
about 0.65s on a server (Ubuntu16.04, tensorflow-gpu of version 1.9, python 3.6,2, CUDA9.0, NVIDIA GeForce GTX 1080 Ti 11171MiB), 
about 0.22s on another server (Ubuntu16.04,  tensorflow-gpu of version 1.8, python 2.7.13,  CUDA9.0, NVIDIA GeForce GTX 1080 Ti 11171MiB). 
The code is exactly the same, only change is the model path and data path. Why there is so huge difference?

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
model_path = 'D:/proj_tf/models_pb/slice_cor.pb'
image_path = 'D:/proj_tf/data/'
files_in = ['0205_256_06.raw', '0205_256_07.raw', '0205_256_08.raw']
data_image = np.zeros((3, 256, 256, 3), dtype=np.float32)
for index in range(3):
    image_file = os.path.join(image_path, files_in[index])
    data_tmp = np.fromfile(image_file, dtype=np.float32)
    data_tmp.shape = 256, 256
    min_value = data_tmp.min()
    max_value = data_tmp.max()
    data_tmp -= min_value
    data_tmp /= (max_value - min_value)
    for i in range(3):
        data_image[index, :, :, i] = data_tmp
    
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
config = tf.ConfigProto(allow_soft_placement=True, log_device_placement=False)
config.gpu_options.per_process_gpu_memory_fraction = 0.7
sess = tf.Session(config=config)
with gfile.FastGFile(model_path, 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    sess.graph.as_default()
    tf.import_graph_def(graph_def, name="")
    
    sess.run(tf.global_variables_initializer())
    inp = sess.graph.get_tensor_by_name('data:0')
    out = sess.graph.get_tensor_by_name('softmax:0')
    
    start_time = time.time()
    pred_slice = sess.run(out, {inp: data_image})
    end_time = time.time()
    
    print("time for inference : ", end_time - start_time)
    sess.close()   
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Exact command to reproduce
Mobile device
