### ISSUE TITLE
Try to Run Tensorflow on CUP clusters

### ISSUE THREAD

**Issue by bastia1989** [tensorflow/tensorflow#23214]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS release 6.9 
- TensorFlow version: 1.9.0-rc0
- Python version:3.6.5
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

Firstly, I want to run tensorflow on a cluster only with CPU nodes. Therefore no CUDA library is installed and only has the CPU-only version of tensorflow installed. I have many questions on the correct setting. Let's start from the very basic situation:

## 1. node with multiple CPU cores

From this [answer](https://stackoverflow.com/a/37660913/4468490), it propose to set `device_count = {'GPU': 0}` in `tf.ConfigProto` to force the code to be run on CPU only. since my platform has GPUs, so I think this step deosn't work for me. *However*, I am curious on under such setting, how the resources of CPUs are assigned. Will the code only run on only 1 CPU cores or not?

So I turned to [yaroslavvb's example](https://gist.github.com/yaroslavvb/9a5f4a0b613c79152152b35c0bc840b8#file-cpu_device_test-py-L21), but I still have some problems:

1. can I avoid using more statement `with tf.device("/cpu:0"):`, etc?

2. what's the relation between `device_count={"CPU": 8}` and `inter_op_parallelism_threads=3,                    intra_op_parallelism_threads=1`? From the [answer from mrry](https://stackoverflow.com/a/41233901/4468490), I think `inter` controls the distribution with threads working on independent blocks in my graph (say, multiple independent matrix operations), and `intra` works on "internally parallelable" tasks (say, a matrix multiplication). Am I correct?  Back to [yaroslavvb's example](https://gist.github.com/yaroslavvb/9a5f4a0b613c79152152b35c0bc840b8#file-cpu_device_test-py-L21), I think the task is assigned to 4 CPU cores, and `{"CPU": 8}` requests 8 cores. If I am correct, why request more than needed? 

3. how the task is distributed among each CPU cores, without using `with tf.device()` statement?

After all these, here is my code, for a simple MNIST example:
```
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt
import urllib.request, json
import os, sys
import numpy as np
sys.path.append('./stanford-tensorflow-tutorials/examples')
import utils
# This code has been tested with TensorFlow 1.6
import tensorflow as tf
image_size = 28
n_channels = 1
n_classes = 10
n_train = 55000
n_valid = 5000
n_test = 10000
n_epochs = 25
batch_size = 100
mnist_folder = './MNIST_data'
utils.download_mnist(mnist_folder)
train, val, test = utils.read_mnist(mnist_folder, flatten=True)
#mnist_data = input_data.read_data_sets('MNIST_data', one_hot=True)

config = tf.ConfigProto(device_count={"CPU": 6}, # limit to num_cpu_core CPU usage  
                inter_op_parallelism_threads = 6,   
                intra_op_parallelism_threads = 6,
                allow_soft_placement=True,                
                log_device_placement=True)  
                
                
                
                
tf.reset_default_graph()
....
```
I am not sure if this `config` setting makes me be able to use 6 CPU cores. 

Then we move further:
## 2. multiple nodes with multiple CPU cores

I think this belongs to **distributed tensorflow** concept. Is this senario comparable to multiple GPUs running?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
TensorFlow installed from
Bazel version
Exact command to reproduce
Mobile device
