### ISSUE TITLE
verbs: local protection error when doing rdma send

### ISSUE THREAD

**Issue by guoshimin** [tensorflow/tensorflow#23220]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 14.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.9.0
- Python version: 2.7
- Bazel version (if compiling from source): 0.16.1
- GCC/Compiler version (if compiling from source): 6.3
- CUDA/cuDNN version: 9.0
- GPU model and memory: TITAN Xp. 12 GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
When verbs support is enabled, getting

```
mlx5: 4dfe187391fa: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 92005204 0900013b 05cc37d3
2018-09-21 23:48:04.608288: F external/org_tensorflow/tensorflow/contrib/verbs/rdma.cc:451] Check failed: wc_[i].status == IBV_WC_SUCCESS Failed status 
local protection error 4 139821989727968 82
```

**Describe the expected behavior**
Should not produce this error.

**Code to reproduce the issue**
Need substantial infrastructure (RoCE) and code to reproduce.

**Other info / logs**
The `wr`s (verbs work request) that trigger this error has lkey set to 0 and non-zero buffer length, indicating that it's trying to send unregistered memory region.

**Comment by wt-huang** [comment]
Currently a PR is in progress targeting this issue.

**Comment by byronyi** [comment]
@guoshimin could you confirm if #24250 fix your issue? If so, could you close it?

**Comment by guoshimin** [comment]
I'm not in a position to test it since we are still using 1.9. I'll close
my PR for now.
