### ISSUE TITLE
MirroredStrategy error with Object detection retraining

### ISSUE THREAD

**Issue by anilmaddala** [tensorflow/tensorflow#23229]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.4 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):b'v1.11.0-0-gc19e293' 1.11.0
- Python version:3.6.5
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source):5.4.0
- CUDA/cuDNN version:9.1/7.1.2
- GPU model and memory: AWS g2.8large Grid K520 4036MiB

**Describe the current behavior**
Training stops with the attached error log when retraining Mobilenet V2 SSD model.
**Describe the expected behavior**
Trainig should start and use the available 4 GPUs
**Code to reproduce the issue**
Following is the code change I made to https://github.com/tensorflow/models/blob/master/research/object_detection/model_main.py
```
def main(unused_argv):
  flags.mark_flag_as_required('model_dir')
  flags.mark_flag_as_required('pipeline_config_path')

  distribution = tf.contrib.distribute.MirroredStrategy()
  config = tf.estimator.RunConfig(model_dir=FLAGS.model_dir,train_distribute=distribution)
```

**Other info / logs**
Error Log: 
[TF_MirroredStrategy_error.txt](https://github.com/tensorflow/tensorflow/files/2512545/TF_MirroredStrategy_error.txt)

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by anilmaddala** [comment]
@ymodak I will post the issue on StackOverflow as well. Can you please tell what other information is needed? I thought I provided all details asked by the issue template. Thanks.

**Comment by ymodak** [comment]
@anilmaddala Yes you did provide all the info. requested by the template. Actually I didn't update the snippet completely. Now I did.  Apologies.
