### ISSUE TITLE
TFLiteConverter produces empty .tflite file

### ISSUE THREAD

**Issue by Mr-Grieves** [tensorflow/tensorflow#23234]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Adapted code from [here](https://www.tensorflow.org/lite/convert/python_api#exporting_a_graphdef_from_file_)
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly-gpu
- Python version: 3.5
- CUDA/cuDNN version: 9.0
- GPU model and memory: GeForce GTX 980 8GB

**Describe the current behavior**
I am trying to convert a frozen .pb (which I have working with TF Mobile java inference interface) to .tflite format using the python TFLiteConverter API. When I run the code below, it completes without error or warning, except it produces an output file SEGNET.tflite with 0 size.

**Describe the expected behavior**
I would like it you produce a non-zero file...

**Code to reproduce the issue**
I cannot provide the .pb file, but here is the code im using
```
import tensorflow as tf

graph_def_file = "models/SEGNET.pb"
input_arrays = ["input_1"]
output_arrays = ["output_node0"]

converter = tf.contrib.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
tflite_model = converter.convert()
open("SEGNET.tflite", "wb").write(tflite_model)
```
I know that both the input and output are correctly named.

**Comment by Mr-Grieves** [comment]
I have also tried using the command line "tflite_convert" interface and get the same behaviour. 
When I include the "--allow_custom_ops" flag, it does produce a non-empty .tflite, however it does not tell me which ops I should be customizing, and when I try to load this file in my Android app I get the following error:
```
java.lang.IllegalArgumentException: Contents of /file:/android_asset/SEGNET.tflite does not encode a valid TensorFlowLite model: Could not open '/file:/android_asset/SEGNET.tflite'.The model is not a valid Flatbuffer file
  at org.tensorflow.lite.NativeInterpreterWrapper.createModel(Native Method)
  at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:41)
  at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:135)
  at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:112)
  at org.qus.segmentLite.TensorFlowQUSRunnerSegmentLite.create(TensorFlowQUSRunnerSegmentLite.java:117)
```

**Comment by ymodak** [comment]
If you can provide us your model that will be great and if not can you a provide us with a list of ops that you have used in your model?

**Comment by miaout17** [comment]
Hi @Mr-Grieves 

A few additional questions:

* Is there any warning or error message when calling `converter.convert()`?
* If you try `print(len(tflite_model))`, what's the length of the binary bytes?
* If the answer for the last question isn't 0, it may be the case that you didn't close the file so the content isn't flush out. Could you try to write the model like this?

```
with open("SEGNET.tflite", "wb") as f:
  f.write(tflite_model)
```

Thanks!

**Comment by Mr-Grieves** [comment]
Thank you for your quick replies

@ymodak, I cannot provide the .pb file, but here are all the unique operation types within it:

```
Placeholder
Const
Identity
Conv2D
BiasAdd
Relu
MaxPool
Shape
StridedSlice
Mul
ResizeNearestNeighbor
ConcatV2
Sigmoid
```

@miaout17:
- there are no warnings or errors.
- `print(len(tflite_model))` prints 0
- Writing the model in the way you suggested still gives a 0 filesize

**Comment by miaout17** [comment]
@Mr-Grieves Thanks! I will send a commit to fix the error reporting soon. 
Then you can see the error message and we can figure out the next step.

**Comment by miaout17** [comment]
85b85a46c625d0b47cddfa8c7b399f32fe5a3ccc fixes the error reporting. 
Now it should report an error instead of producing an empty file silently. 

You should be able to see the proper error message now. 
I'm closing this bug. Feel free to create a separated issue if you need further help converting your model. Thanks!
