### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xiaosi2017** [tensorflow/tensorflow#23249]
Linux Ubuntu 16.04  
Python 3.5
my cuda vision is 9.2.88
cudnn is 7.1.4
only one gpu : NVIDIA 1080ti
 I use pip to install tf

when I just install tf use " pip install tensorflow==1.8.0 "  ,it's OK ,it can import tensorflow,  but can't use gpu
  when I  pip install tensorflow-gpu==1.8.0 ,  these is error :  ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

use   pip install tensorflow-gpu==1.11.0  or   pip install tensorflow==1.11.0  will get the same error.

**Comment by ppwwyyxx** [comment]
1. Latest TensorFlow __supports__ CUDA 8.0-10.0. CuDNN 6-7.
2. Each TensorFlow binary has to work with the version of CUDA and CuDNN it was built with. If they don't match, you have to change either the TensorFlow binary or the Nvidia softwares.
3. Official latest TensorFlow binaries (the one downloaded by pip or conda) are built with CUDA 9.0, CuDNN 7.
4. If you don't like to change your Nvidia software, you can:
(1) Use non-official binaries built by others. e.g.: https://github.com/mind/wheels/releases, https://github.com/hadim/docker-tensorflow-builder#builds
(2) Build the binaries by yourself from source  with your version of Nvidia software.

**Comment by ymodak** [comment]
Were you able to resolve your issue?  Did you try building TensorFlow 1.11 against CUDA 9.0?

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
