### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by jy03189211** [tensorflow/tensorflow#23247]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
-windows 10pro):
- TensorFlow source (source or binary):
- TensorFlow version:
- Python 3.6:
- Installed  pip:
- GCC/Compiler version (if compiling from source):
cuda 9.0
-gtx760

**Describe the problem**

PS F:\Downloads>  pip install tensorflow-gpu
Collecting tensorflow-gpu
  Using cached https://files.pythonhosted.org/packages/3d/a0/60f72b76915a7c83e336e7f9ccf3a08305c30c7262cd15fedde44e026c3f/tensorflow_gpu-1.11.0-cp36-cp36m-win_amd64.whl
Requirement already satisfied: wheel>=0.26 in f:\development\python\lib\site-packages (from tensorflow-gpu) (0.32.2)
Requirement already satisfied: six>=1.10.0 in f:\development\python\lib\site-packages (from tensorflow-gpu) (1.11.0)
Requirement already satisfied: tensorboard<1.12.0,>=1.11.0 in f:\development\python\lib\site-packages (from tensorflow-gpu) (1.11.0)
Requirement already satisfied: setuptools<=39.1.0 in f:\development\python\lib\site-packages (from tensorflow-gpu) (39.1.0)
Requirement already satisfied: numpy>=1.13.3 in f:\development\python\lib\site-packages (from tensorflow-gpu) (1.15.3)
Requirement already satisfied: keras-applications>=1.0.5 in f:\development\python\lib\site-packages (from tensorflow-gpu) (1.0.6)
Requirement already satisfied: termcolor>=1.1.0 in f:\development\python\lib\site-packages (from tensorflow-gpu) (1.1.0)
Requirement already satisfied: keras-preprocessing>=1.0.3 in f:\development\python\lib\site-packages (from tensorflow-gpu) (1.0.5)
Requirement already satisfied: gast>=0.2.0 in f:\development\python\lib\site-packages (from tensorflow-gpu) (0.2.0)
Requirement already satisfied: protobuf>=3.6.0 in f:\development\python\lib\site-packages (from tensorflow-gpu) (3.6.1)
Requirement already satisfied: grpcio>=1.8.6 in f:\development\python\lib\site-packages (from tensorflow-gpu) (1.16.0)
Requirement already satisfied: astor>=0.6.0 in f:\development\python\lib\site-packages (from tensorflow-gpu) (0.7.1)
Requirement already satisfied: absl-py>=0.1.6 in f:\development\python\lib\site-packages (from tensorflow-gpu) (0.6.0)
Requirement already satisfied: markdown>=2.6.8 in f:\development\python\lib\site-packages (from tensorboard<1.12.0,>=1.11.0->tensorflow-gpu) (3.0.1)
Requirement already satisfied: werkzeug>=0.11.10 in f:\development\python\lib\site-packages (from tensorboard<1.12.0,>=1.11.0->tensorflow-gpu) (0.14.1)
Requirement already satisfied: h5py in f:\development\python\lib\site-packages (from keras-applications>=1.0.5->tensorflow-gpu) (2.8.0)
Installing collected packages: tensorflow-gpu
Exception:
Traceback (most recent call last):
  File "f:\development\python\lib\site-packages\pip\_internal\cli\base_command.py", line 143, in main
    status = self.run(options, args)
  File "f:\development\python\lib\site-packages\pip\_internal\commands\install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "f:\development\python\lib\site-packages\pip\_internal\req\__init__.py", line 49, in install_given_reqs
    **kwargs
  File "f:\development\python\lib\site-packages\pip\_internal\req\req_install.py", line 760, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "f:\development\python\lib\site-packages\pip\_internal\req\req_install.py", line 382, in move_wheel_files
    warn_script_location=warn_script_location,
  File "f:\development\python\lib\site-packages\pip\_internal\wheel.py", line 215, in move_wheel_files
    prefix=prefix,
  File "f:\development\python\lib\site-packages\pip\_internal\locations.py", line 153, in distutils_scheme
    d.parse_config_files()
  File "f:\development\python\lib\distutils\dist.py", line 395, in parse_config_files
    parser.read(filename)
  File "f:\development\python\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "f:\development\python\lib\configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'setup.cfg', line: 1
'<?xml version="1.0" encoding="utf-8"?>\n'

**Comment by jish1398** [comment]
Use conda instead

**Comment by jy03189211** [comment]
> still an issue?

I turned conda. It was solved. Thank you.
