### ISSUE TITLE
Random numbers and tf.less_equal

### ISSUE THREAD

**Issue by chrisblum2** [tensorflow/tensorflow#2325]
### Environment info
Operating System: Ubuntu 16.04 LTS 64-Bit
Installed version of CUDA and cuDNN: none
Tensorflow Version: 0.8.0

### Steps to reproduce
1. When comparing a random variable with a tensor using the tf.less_equal operation, the output result is wrong. I can reproduce the error with the minimal example code shown below. When I use a fixed number rather than a random variable, the output result is correct.

`
import tensorflow as tf
import numpy as np

x=[0,0.3333,0.6666,1] # matrix that I want to compare against another number
x = tf.convert_to_tensor(np.reshape(x,[2,2]), dtype=tf.float32) # turn into tensor
y = tf.random_uniform([1,1], minval=0, maxval=1, dtype=tf.float32, seed=12) # random number
#y = tf.convert_to_tensor(0.63615251, dtype=tf.float32) **# uncomment to use fixed number instead**
**z = tf.less_equal(x,y)**
  
init_op = tf.initialize_all_variables()  
with tf.Session() as sess:
  sess.run(init_op)
  xe = x.eval()
  ye = y.eval()
  ze = z.eval()
  
  print('2-by-2 matrix x:')
  print(xe)
  print(' ')
  print('random value y:')
  print(ye)
  print(' ')
  print('output result of x <= y:')
  print(ze)
`

### I tried:
1. I tried using tf.tile to make "y" the same size as "x"
2. I checked with fixed numbers rather than random numbers; then tf.less_equal works just fine

### Console output of above minimal example
2-by-2 matrix x:
[[ 0.          0.33329999]
 [ 0.66659999  1.        ]]
 
random value y:
[[ 0.63615251]]
 
output result of x <= y:
[[ True False]
 [False False]]

### comment to above example:
0.333... <= 0.636... should be True, not False

**Comment by ajaech** [comment]
When you evaluate z then it will re-evaluate y at that time and produce new random numbers. To evaluate y and z simultaneously then you should do` ye, ze = session.run([y, z])`

**Comment by mrry** [comment]
@ajaech is absolutely right. This is intended behavior: `tf.random_uniform()` and the other random ops produce new random numbers each time they execute, and each call to `{y,z}.eval()` will execute the random op another time.
