### ISSUE TITLE
install tensorflow from source code, run ./configure in virtuealenvwrapper due to issues with missing site.getsitepackages()

### ISSUE THREAD

**Issue by raymond-vincent-wang** [tensorflow/tensorflow#23255]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.11.0
- Python version: 3
- Installed using virtualenv? pip? conda?: virtualenvwrapper
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.2/7.1
- GPU model and memory: Geforce 1060

**Describe the problem**

install tensorflow from source code, run ./configure in virtuealenvwrapper due to issues with missing site.getsitepackages()

**Provide the exact sequence of commands / steps that you executed before running into the problem**

(tensorflow) $python --version
Python 3.5.2
(tensorflow) $ which python
/home/raymond/.virtualenvs/tensorflow/bin/python
(tensorflow) raymond@raymond:~/tensorflow-1.11.0⟫ ./configure 
WARNING: Processed legacy workspace file /home/raymond/tensorflow-1.11.0/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/raymond/.cache/bazel/_bazel_raymond/install/f1e11885a5cc7ba9947679cffb18bf94/_embedded_binaries/A-server.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.18.0 installed.
Please specify the location of python. [Default is /home/raymond/.virtualenvs/tensorflow/bin/python]: 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'site' has no attribute 'getsitepackages'

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by harshini-gadige** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
