### ISSUE TITLE
Undefined reference error when trying to run tensorflow lite model on android

### ISSUE THREAD

**Issue by Nimitz14** [tensorflow/tensorflow#23260]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
yes

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
ubuntu 16.04

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
Samsung A3, armeabi-v7a

I cloned from master (Oct 25), last commit is 670eff0b0f60b9fde8231e927807677a80016904

**Describe the current behavior**

When compiling the app to use the tflite model I get an error:
```
error: undefined reference to 'tflite::InterpreterBuilder::operator()(std::__ndk1::unique_ptr<tflite::Interpreter, std::__ndk1::default_delete<tflite::Interpreter> >*)'
```
I've tried
```
std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile(model_path.c_str());
tflite::ops::builtin::BuiltinOpResolver resolver;
std::unique_ptr<tflite::Interpreter> interpreter;
tflite::InterpreterBuilder(*model, resolver)(&interpreter);
```
As per the [docs here](https://www.tensorflow.org/lite/apis) (note the difference is because they seem to be out of date). As it wasn't working, I came across [a slightly different way](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/examples/minimal/minimal.cc#L53), with
```
tflite::InterpreterBuilder builder(*model.get(), resolver);
builder(&interpreter);
```
but that also did not work. These are the relevant headers I include
```
#include "tensorflow/contrib/lite/model.h"
#include "tensorflow/contrib/lite/interpreter.h"
#include "tensorflow/contrib/lite/kernels/register.h"
```

I followed [this great guide](https://stackoverflow.com/questions/49834875/problems-with-using-tensorflow-lite-c-api-in-android-studio-project) for using tensorflow lite for android. Only thing I did different was some cmake stuff (I don't actually include the flatbuffer files inside my android project, but added them through cmake).

**Describe the expected behavior**

To compile.

**Comment by miaout17** [comment]
Hi Andre, do you mind to take a look or reassign?

**Comment by Nimitz14** [comment]
Forgot to mention: I'm using ndk 17 as I have a dependency that requires it (oboe, also from Google!), when running configure there was a warning saying bazel (0.18, just released) couldn't work with NDK 17 and it would lead to weird compile errors. It seems to me that can't be right though as I've found issues from 6 months ago where it seemed like building with NDK 17 should be alright?

**Comment by Nimitz14** [comment]
I've also tried using ndk16b and ndk15c, as well as setting `ANDROID_NDK_API_LEVEL=21`. Nothing worked.

**Comment by andrehentz** [comment]
I don't think this is related to the NDK. From the error message it looks like you are not linking the TF Lite library into your binary. It could be your android studio setup, or your cmake setup.

**Comment by Nimitz14** [comment]
It was related to the ndk. It worked with NDK 18. You can find a reproducible example in my issue [here](https://github.com/tensorflow/tensorflow/issues/23629).

**Comment by andrehentz** [comment]
Thanks @Nimitz14

**Comment by rikichou** [comment]
@Nimitz14 It.s work, Thanks!!

**Comment by rivergold** [comment]
@Nimitz14 Thanks for the solution.
But I meet the same problem using NDK18. I build tflite from the TensorFlow 1.12 source code. 
Is there any solution?

**Comment by MichaelJayW** [comment]
> It was related to the ndk. It worked with NDK 18. You can find a reproducible example in my issue [here](https://github.com/tensorflow/tensorflow/issues/23629).

Update to NDK 18 works for me. Thanks!
