### ISSUE TITLE
Newer TF post-install python test does not expose CUDA/cuDNN driver problems

### ISSUE THREAD

**Issue by pawarrick** [tensorflow/tensorflow#23261]
**System information** Windows 10
- TensorFlow version: tf-nightly-gpu (Oct. 25. 2018)
- Doc Link:
https://www.tensorflow.org/install/pip

**Describe the documentation issue**
The suggested post-install test:

`python -c "import tensorflow as tf; print(tf.__version__)"
`
passes even when there are unresolved GPU CUDA/cuDNN driver issues.

The test previously suggested exercises the CUDA/cuDNN GPU drivers and seems to be better one to suggest:

`python -c "import tensorflow as tf; hello = tf.constant('Hello, TF'); sess = tf.Session(); print(sess.run(hello))"
`

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
yes

**Comment by lamberta** [comment]
Thanks, but I'd like to avoid the `Session` API.

@alextp Will `tfe.num_gpus()` highlight a bad GPU config?

**Comment by alextp** [comment]
tfe.num_gpus() won't but enable_eager_execution followed by a matmul (of floats) will.
