### ISSUE TITLE
Tensorflow (cpu) missing DLL on import

### ISSUE THREAD

**Issue by BunnyJumps** [tensorflow/tensorflow#23286]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit
- TensorFlow installed from (source or binary): pip install tensorflow; pip install --upgrade tensorflow;
pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.11.0-cp36-cp36m-win_amd64.whl etc.)
- TensorFlow version: Tried multiple from 1.4.0 - 1.11.0
- Python version: Python 3.6
- Installed using virtualenv? pip? conda?: Yes to all 3
- CUDA/cuDNN version: As far as I know I don't need it for the CPU Version.
- GPU model and memory: NA

**Describe the problem**
Can't import Tensorflow, missing DLL:
`
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "venv\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "venv\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "venv\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "venv\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified procedure could not be found.
`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

- Installed vc_redist64.exe
- Open Python
`import tensorflow`

**Any other info / logs**
- I already reinstalled Python completly 
- reinstalled vc_redist multiple times 
- and tried everything I found over google. Not sure if I am messing something up.

**Comment by fidanci** [comment]
https://www.youtube.com/watch?v=HJ9bTO5yYw0
From this source, you can find a solution to the problem.

**Comment by harshini-gadige** [comment]
@BunnyJumps  You may also refer this #17386

**Comment by BunnyJumps** [comment]
> @BunnyJumps You may also refer this #17386

I already, referred to it, it didn't help sadly. I am currently working on a vm running Linux to use tensorflow because I just can't get it to work on Windows

**Comment by BunnyJumps** [comment]
> https://www.youtube.com/watch?v=HJ9bTO5yYw0
> From this source, you can find a solution to the problem.

I think it's not a problem connected to pycharm. I tried to install it over pip and it didn't work. Even though I can install everything else without any problems.

**Comment by mrry** [comment]
@BunnyJumps Can you please try again with the nightly build (`pip install tf-nightly`)? We've added some diagnostics to the loading process that should help to track down the cause of errors like this.

**Comment by ymodak** [comment]
@BunnyJumps Is this still an issue? Did you get a chance to try ?

> @BunnyJumps Can you please try again with the nightly build (`pip install tf-nightly`)? We've added some diagnostics to the loading process that should help to track down the cause of errors like this.

**Comment by BunnyJumps** [comment]
After running `py -m pip install tf-nightly`
I still get on import the dll missing problem. But I am not sure if I should import something else than tensorflow like import tf-nightly or so.

`Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.`

**Comment by mrry** [comment]
This looks like an issue in the version of `protobuf` that's installed, which seems to be incompatible with the version used by TensorFlow.

Can you share the output of running `pip show protobuf` on your machine with us?

**Comment by harshini-gadige** [comment]
@BunnyJumps  Any update ?

**Comment by BunnyJumps** [comment]
Sorry for the late answer.

Currently I get
`
py -m pip show protobuf
Name: protobuf
Version: 3.6.1
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Location: c:\users\\appdata\local\programs\python\python36\lib\site-packages
Requires: setuptools, six
Required-by: tf-nightly, tensorflow, tensorflow-tensorboard, tensorboard, tb-nightly
`

Thing is I already tried multiple protobuf versions from downgrading down to 3.0 etc.

**Comment by mrry** [comment]
Hmm, that's the version I would have expected. It looks like there might be something wrong with that protobuf installation though. If you open a Python shell and execute `from google import protobuf`, do you get a similar error?

(Also, is it possible that there are multiple versions of `protobuf` installed in different virtual environments, and there's a conflict between them?)

**Comment by BunnyJumps** [comment]
No, everything works fine. On
`Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from google import protobuf
>>>`

**Comment by mrry** [comment]
Can you also try executing `from google.protobuf import descriptor` and let us know if that produces the same `ImportError`?

**Comment by BunnyJumps** [comment]
Yeah that one creates the error:
`
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import descriptor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.
>>>
`

**Comment by mrry** [comment]
Thanks for confirming. It looks like this is a bug in the protobuf package, which is probably related to https://github.com/protocolbuffers/protobuf/issues/5046. According to a [comment](https://github.com/protocolbuffers/protobuf/issues/5046#issuecomment-439736098) on that thread, upgrading Python from 3.6.0 to 3.6.1 may solve the problem.

**Comment by fufuninja** [comment]
For tensorflow i'm using `pip3 install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.2.1-cp36-cp36m-win_amd64.whl`

my pip show protobuf is 
`Version: 3.6.1` 

I can confirm upgrading from python 3.6.0 to 3.6.1 works on my machine!

**Comment by BunnyJumps** [comment]
Sorry for the late answer fufuninjas reply fixed the issues! Thanks.
