### ISSUE TITLE
Adding quantize fake quant per channel to TFlite

### ISSUE THREAD

**Issue by synchro10** [tensorflow/tensorflow#23287]
Hello! I was faced with the fact that in the current version of TFlite the operation FakeQuantWithMinMaxVarsPerChannel was not implemented when quantized by means of the utility TFLiteConverter.
In this regard, the question is, is it planned to implement this operation and this type of quantization in TFlite?
And are there any known difficulties in realizing this quantization?

**Comment by harshini-gadige** [comment]
@synchro10  - Hi, please refer to this issue #21526 for the operations need to be added to TFLite.

**Comment by harshini-gadige** [comment]
These type of questions are better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
