### ISSUE TITLE
Issue building C++ Tensorflow r1.6 and r1.7 on 64bit Windows 7 with CMake

### ISSUE THREAD

**Issue by Randryn0** [tensorflow/tensorflow#23296]
**System information**
- OS: Windows 7 Enterprise
- TensorFlow installed from (source or binary): Source
- TensorFlow version: r1.6 and r1.7
- Python version: 3.5
- Installed using virtualenv? pip? conda?: Cmake
- Bazel version (if compiling from source): /
- GCC/Compiler version (if compiling from source): MSVC 19.14
- CUDA/cuDNN version: /
- GPU model and memory: /

The compilation of TensorFlow fails.
This issue occurs when I try to build Tensorflow with the C++ API on my machine running Windows 7 Enterprise (x64) using the provided CMake files since I need this for a standalone project.
I have tested this with the releases r1.6, r1.7, which I have pulled from the repository (for versions above r1.7 the compilation procedure fails due to other reasons; r1.12 cannot be compiled because it fails during CMake).
I have used the official documentation provided [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md), as well as other guides found on the internet (e.g. the two articles found [here](https://joe-antognini.github.io/machine-learning/build-windows-tf) and [here](https://joe-antognini.github.io/machine-learning/windows-tf-project) and another one [here](https://medium.com/@shiweili/building-tensorflow-c-shared-library-on-windows-e79c90e23e6e)).

First I initialise the shell by executing in a VS2017 developer command prompt:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build.

Then I do

cmake .. -A x64 -T host=x64 -DCMAKE_BUILD_TYPE=Release ^
-DSWIG_EXECUTABLE="C:\swigwin-3.0.12\swig.exe" ^
-DPYTHON_EXECUTABLE="C:\anaconda3\envs\tensorflow\python.exe" ^
-DPYTHON_LIBRARIES="C:\anaconda3\envs\tensorflow\libs\python35.lib" ^
-Dtensorflow_BUILD_PYTHON_BINDINGS=OFF ^
-Dtensorflow_ENABLE_GRPC_SUPPORT=OFF ^
-Dtensorflow_BUILD_SHARED_LIB=ON 

and start the build process with

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\MSBuild.exe" ^
/m:1 ^
/p:CL_MPCount=1 ^
/p:Configuration=Release ^
/p:Platform=x64 ^
/p:PreferredToolArchitecture=x64 ALL_BUILD.vcxproj ^
/filelogger

The build fails, the error messages are taken from msbuild.log:

  Creating directories for 'eigen'
  Performing download step (download, verify and extract) for 'eigen'
  -- Downloading...
     dst='C:/tensorflow_r1.6/tensorflow/contrib/cmake/build/downloads/14e1418fcf12.tar.gz'
     timeout='none'
  -- Using src='https://bitbucket.org/eigen/eigen/get/14e1418fcf12.tar.gz'
  -- [download 1% complete]
  [...]
  -- [download 100% complete]
  -- Downloading... done
  -- extracting...
       src='C:/tensorflow_r1.6/tensorflow/contrib/cmake/build/downloads/14e1418fcf12.tar.gz'
       dst='C:/tensorflow_r1.6/tensorflow/contrib/cmake/build/eigen/src/eigen'
  -- extracting... [tar xfz]
  -- extracting... [analysis]
  -- extracting... [rename]
  CMake Error at eigen-stamp/extract-eigen.cmake:51 (file):
    file RENAME failed to rename
  
   C:/tensorflow_r1.6/tensorflow/contrib/cmake/build/eigen/src/ex-eigen1234/eigen-eigen-14e1418fcf12
    to
  
   C:/tensorflow_r1.6/tensorflow/contrib/cmake/build/eigen/src/eigen
  
 because: No such file or directory
  
  
  
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\tensorflow_r1.6\tensorflow\contrib\cmake\build\eigen.vcxproj]
Done executing task "CustomBuild" -- FAILED.
Done building target "CustomBuild" in project "eigen.vcxproj" -- FAILED.
Done Building Project "C:\tensorflow_r1.6\tensorflow\contrib\cmake\build\eigen.vcxproj" (default targets) -- FAILED.

Cheers.

**Comment by ymodak** [comment]
Can you use the latest version of TensorFlow and build by any chance?

**Comment by Randryn0** [comment]
> Can you use the latest version of TensorFlow and build by any chance?

Unfortunately, when I try to build release 1.11 I get 48 errors of the type C1083. Specifically tf_core_lib.vcxproj complains that stringpiece.h cannot find a file, namely ""absl/strings/string_view.h": No such file or directory".

Cheers!

**Comment by gunan** [comment]
Cmake has not been supported for quite a while (even when this issue was reported).
It is possible they were simply broken.
Now that they are fully deleted. I will close this issue.
