### ISSUE TITLE
Need a way to ask users what version of tensorflow they are running

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#233]
And ideally where they got it from.  Something like `tf.version`?

**Comment by girving** [comment]
This would help diagnose stuff likehttps://github.com/tensorflow/tensorflow/issues/229

**Comment by girving** [comment]
This would help diagnose stuff like https://github.com/tensorflow/tensorflow/issues/229

**Comment by vrv** [comment]
https://github.com/numpy/numpy/blob/626eb3748d067ea6e4c4dd308252bfad97df186f/setup.py#L123 is how numpy does it

**Comment by girving** [comment]
Excellent, that looks like a good thing to copy.

**Comment by girving** [comment]
Done: `tf.__version__`.
