### ISSUE TITLE
AttributeError: module '_pywrap_tensorflow_internal' has no attribute 'TFE_DEVICE_PLACEMENT_EXPLICIT_swigconstant'

### ISSUE THREAD

**Issue by demongolem** [tensorflow/tensorflow#23300]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
NA
- TensorFlow installed from (source or binary):
From pip install
- TensorFlow version (use command below):
1.11.0
- Python version:
3.6.6
- Bazel version (if compiling from source):
NA
- GCC/Compiler version (if compiling from source):
NA
- CUDA/cuDNN version:
???
- GPU model and memory:
NA

**Describe the current behavior**
After installing 1.11.0 from pip, whenever I do `import tensorflow as tf`, I get the error in title.  If I downgrade to 1.10.0, the installation appears to be successful, or at least the import command works.

**Describe the expected behavior**
1.11.0 should work out of the box when doing a pip install

**Code to reproduce the issue**
All you need is `import tensorflow as tf` to see the problem

**Other info / logs**
NA

**Comment by harshini-gadige** [comment]
@demongolem  - Reinstall tensorflow 1.11 and try restarting the system.

**Comment by demongolem** [comment]
I have since made it up to 1.11.0 successfully, so I suppose issue resolved..  Perhaps it is as simple as bulletpoint #1, but I don't recall the exact moment when I did reinstall it or all the other dependencies that were involved in updating other libraries I use alongside tensorflow such as keras and spacy.

**Comment by harshini-gadige** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=23300)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=23300)
