### ISSUE TITLE
Missing Documentation: Multiple links return 404 in Python API Guide

### ISSUE THREAD

**Issue by alexaorrico** [tensorflow/tensorflow#23307]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: Version 2.0
- Doc Link: The following docs all have links that return a 404 error:

  - [tensorflow/contrib/util/\_\_init\_\_.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/util/__init__.py)
    - [https://www.tensorflow.org/api_guides/python/contrib.util](https://www.tensorflow.org/api_guides/python/contrib.util)
  - [tensorflow/python/lib/io/python_io.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/lib/io/python_io.py)
    - [https://www.tensorflow.org/api_guides/python/python_io](https://www.tensorflow.org/api_guides/python/python_io)
  - [tensorflow/python/client/client_lib.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/client_lib.py)
    - [https://www.tensorflow.org/api_guides/python/client](https://www.tensorflow.org/api_guides/python/client)
  - [tensorflow/contrib/crf/\_\_init\_\_.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/crf/\_\_init\_\_.py)
    - [https://www.tensorflow.org/api_guides/python/contrib.crf](https://www.tensorflow.org/api_guides/python/contrib.crf)
  - [tensorflow/python/debug/\_\_init\_\_.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/debug/__init__.py)
    - [https://tensorflow.org/api_guides/python/tfdbg](https://tensorflow.org/api_guides/python/tfdbg)
  - [tensorflow/contrib/rnn/\_\_init\_\_.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/__init__.py)
    - [https://tensorflow.org/api_guides/python/contrib.rnn](https://tensorflow.org/api_guides/python/contrib.rnn)
  - [tensorflow/core/api_def/base_api/api_def_SegmentMax.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_SegmentMax.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_SegmentMean.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_SegmentMean.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_SegmentMin.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_SegmentMin.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_SegmentProd.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_SegmentProd.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_SegmentSum.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_SegmentSum.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_UnsortedSegmentMax.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_UnsortedSegmentMax.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_UnsortedSegmentSum.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_UnsortedSegmentSum.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_SparseSegmentSqrtN.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_SparseSegmentSqrtN.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_SparseSegmentMean.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_SparseSegmentMean.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_SparseSegmentMeanWithNumSegments.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_SparseSegmentMeanWithNumSegments.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_SparseSegmentSqrtNWithNumSegments.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_SparseSegmentSqrtNWithNumSegments.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_SparseSegmentSum.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_SparseSegmentSum.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_SparseSegmentSumWithNumSegments.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_SparseSegmentSumWithNumSegments.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_UnsortedSegmentMin.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_UnsortedSegmentMin.pbtxt)
  - [tensorflow/core/api_def/base_api/api_def_UnsortedSegmentProd.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_UnsortedSegmentProd.pbtxt)
    - [https://tensorflow.org/api_guides/python/math_ops#Segmentation](https://tensorflow.org/api_guides/python/math_ops#Segmentation)
  - [tensorflow/contrib/framework/\_\_init\_\_.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/framework/__init__.py)
    - [https://tensorflow.org/api_guides/python/contrib.framework](https://tensorflow.org/api_guides/python/contrib.framework)
  - [tensorflow/contrib/layers/\_\_init\_\_.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/__init__.py)
    - [https://tensorflow.org/api_guides/python/contrib.layers](https://tensorflow.org/api_guides/python/contrib.layers)
  - [tensorflow/python/training/training.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/training.py)
    - [https://www.tensorflow.org/api_guides/python/train](https://www.tensorflow.org/api_guides/python/train)
  - [tensorflow/python/summary/summary.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/summary/summary.py)
    - [https://tensorflow.org/api_guides/python/summary](https://tensorflow.org/api_guides/python/summary)
  - [tensorflow/python/ops/session_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/session_ops.py)
    - [https://tensorflow.org/api_guides/python/session_ops](https://tensorflow.org/api_guides/python/session_ops)
  - [tensorflow/python/ops/string_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/string_ops.py)
    - [https://tensorflow.org/api_guides/python/string_ops](https://tensorflow.org/api_guides/python/string_ops)
  - [tensorflow/python/ops/state_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/state_ops.py)
    - [https://tensorflow.org/api_guides/python/state_ops](https://tensorflow.org/api_guides/python/state_ops)
  - [tensorflow/python/ops/math_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_ops.py)
    - [https://tensorflow.org/api_guides/python/math_ops#segmentation](https://tensorflow.org/api_guides/python/math_ops#segmentation)
  - [tensorflow/python/ops/functional_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/functional_ops.py)
    - [https://tensorflow.org/api_guides/python/functional_ops](https://tensorflow.org/api_guides/python/functional_ops)
  - [tensorflow/python/ops/check_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/check_ops.py)
    - [https://tensorflow.org/api_guides/python/check_ops](https://tensorflow.org/api_guides/python/check_ops)
  - [tensorflow/python/ops/array_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py)
    - [https://tensorflow.org/api_guides/python/array_ops](https://tensorflow.org/api_guides/python/array_ops)
  - [tensorflow/python/ops/control_flow_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/control_flow_ops.py)
    - [https://tensorflow.org/api_guides/python/control_flow_ops](https://tensorflow.org/api_guides/python/control_flow_ops)
  - [tensorflow/python/ops/sparse_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/sparse_ops.py)
    - [https://tensorflow.org/api_guides/python/sparse_ops](https://tensorflow.org/api_guides/python/sparse_ops)

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?** No

**Comment by harshini-gadige** [comment]
@MarkDaoust - Hi Mark, Could you please check this.

**Comment by MarkDaoust** [comment]
Hi Alexa, thanks for the report.

We're trying to clean out the api_guides/ directory. Everything in there was out-dated.

It looks like we were a little over-zealous. 
These broken links will all be deleted when we publish r1.12. In a few days.

I'm going to close this, because I believe there is no further work to do on it. But please re-open if it's still broken after the r1.12 release.

Thanks.
