### ISSUE TITLE
[surface book1] What version of CUDA should be installed on the Microsoft GeForce 940MX?

### ISSUE THREAD

**Issue by littleOStar** [tensorflow/tensorflow#23315]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information** windows 10
- TensorFlow version: 1.11
- Doc Link: https://www.tensorflow.org/install/install_windows?hl=zh-cn

**Describe the documentation issue**

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by rosgori** [comment]
Use the last version

**Comment by littleOStar** [comment]
latest ? 
9.0 ?

**Comment by littleOStar** [comment]
ok, thanks. i will try it.

**Comment by CatJustin** [comment]
The latest maybe 10.0...............

**Comment by littleOStar** [comment]
i'm trying this blog. https://www.anaconda.com/blog/developer-blog/tensorflow-in-anaconda/
it's good way to install tensorflow-gpu.

**Comment by rosgori** [comment]
> latest ?
> 9.0 ?

Yes, that one
