### ISSUE TITLE
(roadmap request)python 3.7 and windows build roadmap

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#23313]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12.0rc
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
build tensorflow with python 3.7 gets error ( related to google protobuf c++ code  ), windows bazel build can't recognize path
**Will this change the current api? How?** 
no
**Who will benefit with this feature?**
almost everyone
**Any Other info.**

protobuf for python 3.7 is stable and published on pip, and tensorflow is not compatible with that.
windows bazel-build has path-related error( which is an exact path ), maybe this is caused by different path-mechanism and/or regional(korean, in my case) encoding-related

could you tensorflowers give us specific roadmap for python 3.7 compatibility and windows 10(for all countries) build support roadmap?

**Comment by devon-ge** [comment]
Once all dependencies are compatible with python 3.7, new version will be released. If I'm right, the developers will finish this by TensorFlow 1.13.

Also see #20517.

**Comment by harshini-gadige** [comment]
@alanpurple  -  Hi, could you please check the latest comment by @fo40225  in the issue 20517.
Also feel free to close this issue as we are maintaining a single issue for Python 3.7 compatibility with TF. Thanks !
