### ISSUE TITLE
No ability to verify a jpeg before decode_jpeg-ing

### ISSUE THREAD

**Issue by JohnAllen** [tensorflow/tensorflow#2331]
Say we are writing images to a dir and feeding them to a TF queue.  If TF goes to read a JPEG that isn't there for some reason or hasn't finished writing, `decode_jpeg` will fail.  Using something like `os.stat()` will not work on the tensor that `decode_csv` returns.

It would be great if we could verify a jpeg is our target image size before decoding so TF doesn't shutdown completely.

**Comment by girving** [comment]
Can you be more specific about the feature you're looking for?  Do you want an op that checks whether a file exists?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen if it is still an issue.
