### ISSUE TITLE
Win10, AMD: Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by diegoxfx** [tensorflow/tensorflow#23321]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Pip
- TensorFlow version: tf nightly gpu [the last one until this date i suppose]
- Python version: 3.6.4 Anaconda
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: APU AMD A10 - AMD GPU R6 M340DX 2GB

**Describe the problem**

I had installed tf cpu in my computer, and then i wanted to use tf in my gpu, so i installed the nightly 
gpu version. After i installed it, i couldn't use more tensorflow

**Provide the exact sequence of commands / steps that you executed before running into the problem**

import tensorflow as tf

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

C:\ProgramData\Anaconda3\lib\imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

C:\ProgramData\Anaconda3\lib\imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: DLL load failed: No se puede encontrar el módulo especificado.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-4-1c24dce58f6f> in <module>()
      3 import numpy as np
      4 import os
----> 5 import tensorflow as tf
      6 import time

~\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py in <module>()
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 from tensorflow.python.tools import component_api_helper as _component_api_helper

~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\dcifuen3\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\dcifuen3\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\dcifuen3\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by rosgori** [comment]
You can only use `tensorflow` with a Nvidia graphics card.

**Comment by diegoxfx** [comment]
> You can only use `tensorflow` with a Nvidia graphics card.

But that's with the usual gpu installation of tensorflow, i used the nightly gpu installation that it's for gpu support in OpenCL, and as you know, AMD uses OpenCL.

I don't know if have to do the issue in the [original repo of the nightly version](https://github.com/benoitsteiner/tensorflow-opencl) (but looking at the issues there, there are many unresponded for a long time) or if i can do it here

**Comment by rosgori** [comment]
Look at this [https://www.tensorflow.org/install/gpu](https://www.tensorflow.org/install/gpu). Unfourtanely, the `tf-nightly-gpu` requires a Nvidia graphics card

**Comment by diegoxfx** [comment]
tf-nightly-gpu uses OpenCL that runs in both Nvidia (OpenCL 1.2) and AMD. tf-nightly-gpu was developed to run tensorflow in gpus different than nvidia, thanks to opencl, but it seems like they're no offering more support, because the last commit was like a year ago, and there are many unresponded issues.

**Comment by rosgori** [comment]
Well, you could try this https://medium.com/tensorflow/amd-rocm-gpu-support-for-tensorflow-33c78cc6a6cf

**Comment by harshini-gadige** [comment]
@diegoxfx  - Is this still an issue ?

**Comment by harshini-gadige** [comment]
@gunan  -  PTAL

**Comment by gunan** [comment]
There is no official support for AMD GPUs yet.
And `tf-nightly-gpu` definitely cannot use OpenCL yet.
You will need to reach out to AMD if you are using ROCm, or Codeplay if you are using opencl.
