### ISSUE TITLE
How can parse_fn be put into tf.data.map without arguments?

### ISSUE THREAD

**Issue by khle08** [tensorflow/tensorflow#23322]
**System information**
- TensorFlow version: 1.10.1

**Describe the documentation issue**
I am familiar with parsing tfrecord back to tensor without using tf.data API. And now I'm trying to use this API to construct a more robust pipeline. The code goes like this:
`def parse_fn(serialized):
    features = {
        'image': tf.FixedLenFeature([], tf.string),
        'label': tf.FixedLenFeature([], tf.int64)
    }
    parse_exp = tf.parse_single_example(serialized=serialized, features=features)
    data = parse_exp['image']
    data = tf.decode_raw(data, tf.uint8)
    data = tf.cast(data, tf.float32)
    return data, parse_exp['label']

def input_fn(data_list, batch_size=32, shuffle_size=1024, prefetch_size=2):
    files = tf.data.Dataset.list_files(data_list)
    dataset = files.interleave(tf.data.TFRecordDataset)
    dataset = dataset.shuffle(buffer_size=shuffle_size)
    dataset = dataset.repeat()
    dataset = dataset.map(parse_fn, num_parallel_calls=4)
    dataset = dataset.batch(batch_size)
    dataset = dataset.prefetch(buffer_size=prefetch_size)
    iterator = dataset.make_one_shot_iterator()
    images_batch, labels_batch = iterator.get_next()
    return {'image': images_batch}, labels_batch`

But based on my knowledge, tfrecord file is a protocol buffer file containing binary data. So here are my 2 consecutive questions...
1. How can tf know which part and which part should be shuffled before parse the file into tf datatype? 
2. How can the parse_fn function be substituted into map func without argument? where will the 'serialized' argument come from? What if I want to add more arguments to parse_fn, what can I do?

Lastly, in this case I use 'label' as the int64List dict name to store data into tfrecord so that I can extract the corresponding data using key 'label' here again. But why I didn't get error when I use the other name as the key in order to get data? This makes me feel weird because when I was using TFRecordReader.read() to extract binary data, it is pretty sensitive that I should use exactly the same key name so that there would be no errors.

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
