### ISSUE TITLE
SpatialSoftmax

### ISSUE THREAD

**Issue by Mona77** [tensorflow/tensorflow#23331]
It seams to me that `width_lin` should be used when we want to look up the corresponding value to x_loc: [this line](https://github.com/tensorflow/tensorflow/blob/6bfb36b241dadfecb345edb0589a8d0ae72dc968/tensorflow/contrib/layers/python/layers/layers_test.py#L3566)
```sh
 x_lin = np.expand_dims(np.array([height_lin[i] for i in x_loc]), 1)
```
should be

```sh
 x_lin = np.expand_dims(np.array([width_lin[i] for i in x_loc]), 1)
```

**Comment by ragulpr** [comment]
Nice catch, this seems true if naming convention `x~width` holds. Since this implies that all tests would be transposed, wouldn't that mean that they *should* fail as is right now?

**Comment by Mona77** [comment]
@ragulpr Thanks for your follow up.
I don't think the tests would fail because somehow even in spatial_softmax layer implementation width and height are reversed, [here](https://github.com/tensorflow/tensorflow/blob/r1.11/tensorflow/contrib/layers/python/layers/layers.py#L2960). 

```sh
      pos_x, pos_y = array_ops.meshgrid(
          math_ops.lin_space(-1., 1., num=height),
          math_ops.lin_space(-1., 1., num=width),
          indexing='ij')
```

**Comment by ragulpr** [comment]
Related, in the discussion #6271 they talk about height and width in that order without raising an eyebrow, so I think we're the ones confused about the (x,y)-convention 😄. I don't think this is a bug then, just a strange convention
