### ISSUE TITLE
download tensorflow to run on  python 3.7.1 : version not satisfied

### ISSUE THREAD

**Issue by gogo027** [tensorflow/tensorflow#23330]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): WIN 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): GITHUB
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Not able to download tensorflow

**Provide the exact sequence of commands / steps that you executed before running into the problem**
C:\WINDOWS\system32> pip install tensorflow
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rosgori** [comment]
Use python 3.6

**Comment by harshini-gadige** [comment]
#17022
