### ISSUE TITLE
Output 'tensorflow/core/kernels/_objs/broadcast_to_op_gpu/broadcast_to_op_gpu.cu.pic.o' was not created

### ISSUE THREAD

**Issue by rosgori** [tensorflow/tensorflow#23339]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.5
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.11
- Python version: 3.6.6
- Installed using virtualenv? pip? conda?: None
- Bazel version (if compiling from source): 0.18.0
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: 8.0 / 7.0.1
- GPU model and memory: GeForce GT 740M; 2004MiB

**Describe the problem**

Every time I  use the `bazel` command to build tensorflow, this error appears:

`ERROR: /home/rosgori/Python/tengpu/tensorflow/tensorflow/core/kernels/BUILD:673:1: output 'tensorflow/core/kernels/_objs/broadcast_to_op_gpu/broadcast_to_op_gpu.cu.pic.o' was not created`

I have used `gcc` version 5.4 and 4.9 and every time a new error appears, some examples:

```
ERROR: /home/rosgori/Python/tengpu/tensorflow/tensorflow/core/kernels/BUILD:2250:1: output 'tensorflow/core/kernels/_objs/resize_nearest_neighbor_op_gpu/resize_nearest_neighbor_op_gpu.cu.pic.o' was not created

ERROR: /home/rosgori/Python/tengpu/tensorflow/tensorflow/contrib/image/BUILD:115:1: output 'tensorflow/contrib/image/_objs/python/ops/_distort_image_ops_gpu/adjust_hsv_in_yiq_op_gpu.cu.pic.o' was not created

ERROR: /home/rosgori/Python/tengpu/tensorflow/tensorflow/core/kernels/BUILD:3360:1: output 'tensorflow/core/kernels/_objs/conv_ops_gpu/conv_ops_gpu_3.cu.pic.o' was not created

ERROR: /home/rosgori/Python/tengpu/tensorflow/tensorflow/core/kernels/BUILD:2178:1: output 'tensorflow/core/kernels/_objs/crop_and_resize_op_gpu/crop_and_resize_op_gpu.cu.pic.o' was not created

ERROR: /home/rosgori/Python/tengpu/tensorflow/tensorflow/core/kernels/BUILD:4355:1: output 'tensorflow/core/kernels/_objs/scatter_op_gpu/scatter_op_gpu.cu.pic.o' was not created

ERROR: /home/rosgori/Python/tengpu/tensorflow/tensorflow/core/kernels/BUILD:3782:1: output 'tensorflow/core/kernels/_objs/batch_space_ops_gpu/spacetobatch_functor_gpu.cu.pic.o' was not created

ERROR: /home/rosgori/Python/tengpu/tensorflow/tensorflow/core/kernels/BUILD:673:1: output 'tensorflow/core/kernels/_objs/broadcast_to_op_gpu/broadcast_to_op_gpu.cu.pic.o' was not created
```
They have something in common, the extension `.cu.pic.o` is in every error. So my questions are: What is the meaning of this error? Can it be fixed?

I even tried `r1.12` today (2018-10-28) with no success. I think it is strange that the build was successful when I tried `r1.10`, so... I don't know what happened there.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`bazel build --verbose_failures -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.1 --copt=-msse4.2 --config=opt --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rosgori** [comment]
As I read other issues, the problem might be CUDA, it should be 9 instead of 8

**Comment by harshini-gadige** [comment]
@rosgori  - Yes you are right. CUDA 9  cuDNN 7 should be used. Please save[ this](https://www.tensorflow.org/install/source#tested_build_configurations) for reference. 
Thanks !
