### ISSUE TITLE
Bug: tf.scatter_update does not update variable with float type on GPU 

### ISSUE THREAD

**Issue by ahatamiz** [tensorflow/tensorflow#23333]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 18.04.1 LTS
- TensorFlow installed from (source or binary): 1.11
- TensorFlow version (use command below): pip 
- Python version: 3.6
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA release 9.0, V9.0.176
- GPU model and memory: TITAN Xp / 12Gb

**Describe the current behavior**

On GPU, tf.scatter_update does not update the variable if the type of the variable is defined as float. However, the same code works without a problem if the code is executed on CPU. If you run the code I provided here for you, you will get random values like the one that comes in the following every time you run the code:  

[array([-0.27238935, -0.11273658, -0.18543988, -0.34574947, -0.4174637 ,
       -0.35478222], dtype=float32), 6]

This problem does not happen on a CPU, or if the variable type is set to integer. 

**Describe the expected behavior**
It should simply update the variable and should output the following in a deterministic manner: 

[array([19., 19., 19., 19., 19., 19.], dtype=float32), 6]

I suppose this is a bug in the caching process involved if the code is run on a GPU.  

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

    import tensorflow as tf
    import os

    os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
    os.environ["CUDA_VISIBLE_DEVICES"]='0'
    def cond(size, i):
	    return tf.less(i,size)

    def body(size, i):
	    b=2*7.5+c

	    with tf.variable_scope("a", reuse=tf.AUTO_REUSE):
		    a = tf.get_variable("a",[6],dtype=tf.float32)

	        a = tf.scatter_update(a,i,b)

	        with tf.control_dependencies([a]):
		        return (size, i+1)

    with tf.Session() as sess:
        c=tf.constant(4.0)
        i = tf.constant(0)
        size = tf.constant(6)
        _,i = tf.while_loop(cond,
                body,
                [size, i])
    
        a = tf.get_variable("a",[6],dtype=tf.float32)
    
        init = tf.initialize_all_variables()
        sess.run(init)
        print(sess.run([a,i]))

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ppwwyyxx** [comment]
This is working as expected.
` sess.run([a,i])` does not define the evaluation order or `a` and `i`.  `a` can be evaluated either before or after or during the loop, and before the loop `a` is randomly initialized. Therefore you can get different results.
See documentation: https://www.tensorflow.org/api_docs/python/tf/Session#run
> Order in which fetches operations are evaluated inside the call is undefined.

**Comment by ahatamiz** [comment]
Thanks for your reply. But what would be the solution then ? how can we force i to be evaluated sooner in the same session as a ? also, as I mentioned before, this problem does not occur if the code is executed on a CPU.

**Comment by ppwwyyxx** [comment]
You can just `sess.run(a)` after finishing `sess.run(i)`.

Another bug in your code above is that the second `get_variable` should be under the variable scope "a", otherwise you're creating a new variable.

**Comment by ppwwyyxx** [comment]
Why the `bug/performance` label? The code is working as expected as far as I can see.

**Comment by ahatamiz** [comment]
Thanks. It works as expected now.

**Comment by harshini-gadige** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=23333)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=23333)
