### ISSUE TITLE
Immediate-mode execution in TensorFlow

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#2334]
Mirror TensorFlow API to provide "numpy/Torch"-like mode for executing TensorFlow programs. 

Briefly, provide a mode where you can do the following: 
```
a = tf.constant([[1,1],[1,1]])   # constant is created
b = tf.constant([[2,2],[2,2]])
c = tf.matmul(a, b)  # executes matrix multiplication
print c                      # transfers contents of c from TensorFlow runtime to Python runtime and prints it

```
Goals
1. No separation between graph-construction and evaluation - each op is executed in TensorFlow runtime the moment the corresponding wrapper is evaluated by Python
2. Reuse of TensorFlow Graph for efficiency. For instance, after float32 addition was performed once, any additional float32 addition operations should be done by reusing previously created OpDef
3. Immediate-style Tensor object implements functions in [3.4.8. Emulating numeric types](https://docs.python.org/2/reference/datamodel.html#emulating-numeric-types) and translates them to appropriate TensorFlow operations 
4. Immediate-style Tensor object keep contents of underlying tensors in TensorFlow runtime and only transfers them to Python when necessary, such when needed for flow control and printing.

Design doc: https://docs.google.com/document/d/1CRfhT2_-EaboFbN1U7gKXlGIVAZ21bWpcl1fOwDZLjw/edit#heading=h.yhcm0hj5bq25

CLA signed (for design doc). I'll start submitting code for this as soon as I figure out github/bazel workflow

@keveman @yuanbyu

**Comment by yaroslavvb** [comment]
This is worked on in request #2346 
atm, Tensorflow-native ops work in immediate-mode, but missing infrastructure to support Python-only ops, which happen to be the most popular ops
Estimating another week to get Python-only ops working

**Comment by girving** [comment]
The new pull request is https://github.com/tensorflow/tensorflow/pull/2595.  I've pinged @yuanbyu for comment.

**Comment by yaroslavvb** [comment]
New pull request is https://github.com/tensorflow/tensorflow/pull/2747

**Comment by keveman** [comment]
@yaroslavvb Can this be closed, then?

**Comment by yaroslavvb** [comment]
@keveman this is the main tracking issue though, those other links are pull requests

**Comment by gunan** [comment]
All the linked PRs seem closed, therefore closing this issue.
Please reopen if this is still being worked on.
