### ISSUE TITLE
OS : Windows 10

### ISSUE THREAD

**Issue by anandh02** [tensorflow/tensorflow#23353]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS : Windows 10
- TensorFlow installed from (source or binary): from pip
- TensorFlow version: 1.11.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): No 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10 
- GPU model and memory: Nvidia 1050Ti

Package             Version
------------------- ----------
tensorflow-gpu      1.11.0

able to see tensorflow gpu installed but when run 

# Creates a graph.
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print(sess.run(c))

I'm getting a error GPU is not avalable, I did go through lot threads but nothing helped me to fix this. I'm a beginner so couldn't understand much where exactly the issue. Can some one help me with this ?

**Comment by harshini-gadige** [comment]
@anandh02  -  Hi, can you please answer the following.

1) Have you installed gpu version of tensorflow ?(i.e pip install tensorflow-gpu)
2) If so, please run below test and see if it's true.
**_tf.test.is_gpu_available(
    cuda_only=False,
    min_cuda_compute_capability=None
)_**
3) Install Microsoft Visual C++ 2015 Redistributable Update 3
4) Use Cuda 9 and cuDNN 7 versions

Please try above and keep posted here. Thank you !

**Comment by anandh02** [comment]
Yes I have installed tensorflow GPU:

**Comment by harshini-gadige** [comment]
Please refer #7653 for the above error.

**Comment by harshini-gadige** [comment]
@anandh02  -  Is this still an issue ?

**Comment by anandh02** [comment]
No it’s not, thanks for the input
