### ISSUE TITLE
Installation problem with Tensorflow hub

### ISSUE THREAD

**Issue by EmilioMezaE** [tensorflow/tensorflow#23361]
Device: Raspberry pi 3B
System information
TensorFlow version: 1.11.0
Python version: 3.5.3

Anyone knows how to install tensorflow hub?

**Comment by vvsvictor** [comment]
https://www.tensorflow.org/hub/installation

**Comment by ymodak** [comment]
Did you try the official TensorFlow Hub installation guide provided in the previous comment?

> https://www.tensorflow.org/hub/installation

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
