### ISSUE TITLE
How to visualizing a model structure in tensorboard when eager execution is open? 

### ISSUE THREAD

**Issue by murdockhou** [tensorflow/tensorflow#23367]
tensorflow-gpu == 1.10.0
python == 3.5

Hello, i want to visualize a model structure in tensorboard when eager execution is open, but i can not find one available solution to do this. In graph mode, we can use tf.summary.writer('', sess) to save model structure, but how to do as same as this under eager mode?

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by murdockhou** [comment]
Thanks very much.

**Comment by zacateras** [comment]
@murdockhou what was your conclusion? Is it in fact impossible to visualize graph in eager mode - as stated in the SO answer?

I found this function: https://www.tensorflow.org/versions/r1.13/api_docs/python/tf/contrib/summary/graph. Unfortunately its  documentation is unclear. Here is a request for elaboration: https://stackoverflow.com/questions/54560627/param-for-tf-contrib-summary-graph.

**Comment by nfelt** [comment]
Answered on StackOverflow here: https://stackoverflow.com/a/54913635/1179226  The documentation does describe this parameter, but in eager mode there is no single overall graph by definition, so there isn't really anything TensorBoard can currently visualize that matches what you are asking for.
