### ISSUE TITLE
Integrating embeddings with language translation

### ISSUE THREAD

**Issue by kishore0905** [tensorflow/tensorflow#23365]
i am using the tensorflow nmt with attention program for language translation 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb

In there i like to add the pretrained word embeddings is there is any way that i can add them and used for predictions

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
