### ISSUE TITLE
How to read particular text from scanned or image file using python with DL library

### ISSUE THREAD

**Issue by Ganeshtpt** [tensorflow/tensorflow#23364]
How to read particular text (like empno,name,salary,etx) from scanned or image file and store in db using python with any one deep learning library (like tensorflow, pytorch,etc)

pls. provide some sample code and which one we can use for this concepts

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
