### ISSUE TITLE
Protobuf error, mismatch with system installed version

### ISSUE THREAD

**Issue by depauwjimmy** [tensorflow/tensorflow#23375]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1 LTS
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.11.0
- Python version: 3.6.6 (virtualenv)
- Bazel version (if compiling from source): 0.17.2
- GCC/Compiler version (if compiling from source): gcc-6 (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424
- CUDA/cuDNN/NCCL version: 9.1/7.1/2.1.15
- GPU model and memory: Quadro M1200

I know this a typical problem and i could compile and install from source using a previous version but this time it's a bit different.

Compile log is : 

```
ERROR: /home/god_kane/Downloads/tensorflow-1.11.0/tensorflow/contrib/nccl/BUILD:24:1: error while parsing .d file: /home/god_kane/.cache/bazel/_bazel_god_kane/380ea18d2d4a7f2f6db5af2f6d4bc750/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/nccl/_objs/python/ops/_nccl_ops_gpu/nccl_manager.pic.d (No such file or directory)
In file included from ./tensorflow/core/framework/variant.h:26:0,
                 from ./tensorflow/core/framework/allocator.h:26,
                 from ./tensorflow/core/framework/tensor.h:20,
                 from ./tensorflow/core/framework/log_memory.h:19,
                 from ./tensorflow/core/common_runtime/gpu/gpu_event_mgr.h:21,
                 from ./tensorflow/contrib/nccl/kernels/nccl_manager.h:31,
                 from tensorflow/contrib/nccl/kernels/nccl_manager.cc:15:
bazel-out/k8-opt/genfiles/tensorflow/core/framework/tensor.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^~~~~
bazel-out/k8-opt/genfiles/tensorflow/core/framework/tensor.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^~~~~
bazel-out/k8-opt/genfiles/tensorflow/core/framework/tensor.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^~~~~
```

Those file are correctly generated with protobuf 3.6.0 which i believe is compiled as third_party.  
What i don't understand is that it seems what is included later are my system protobuf headers and not the one from tensorflow folder resulting in an error.  
I tried to do something dirty to check, installed protobuf from source and created symbolink link to it replacing my system installed version.  
Doing that worked but it's not a valid solution. I also should not need to install my own protobuf version just for using it in python.
The fault seems to be with nccl but i don't know where to look for a more clean fix.

**Comment by hg-tfuser** [comment]
@depauwjimmy  - Please try with Bazel 0.15.0 and GCC 4.8. This is the tested combination and it should work.

**Comment by harshini-gadige** [comment]
@depauwjimmy  - Any update on this ?

**Comment by depauwjimmy** [comment]
Just renaming the /usr/include/google/protobuf folder to something else let me compile without a problem.
I did not had the time to try again with the recommended setup since it's a time consuming process.
I'll keep it in mind if a need to compile again in the future for another platform/version.
Thanks for your time
