### ISSUE TITLE
Can we load a pretrained tensorflow model which don't have metafile?

### ISSUE THREAD

**Issue by Priyabrata-M** [tensorflow/tensorflow#23378]
Hi Team,

I have a pre-trained model which contains "model_gs_19860_0.19.data-00000-of-00001" and "model_gs_19860_0.19.index" but don't have any metafile, is it possible to load this model?

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
