### ISSUE TITLE
Ignoring visible gpu device (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1) with Cuda compute capability 6.1. The minimum required Cuda capability is 7.0

### ISSUE THREAD

**Issue by satishrClemson** [tensorflow/tensorflow#23385]
I downloaded the docker container at (floydhub/tensorflow:1.5.0-gpu.cuda9cudnn7-py3_aws.22). But when I tried to run a sample gpu script I got the "ignoring visible GPU" error mentioned in the title. 

**System information**
- OS Platform and Distribution : Linux Ubuntu 16.04:
- TensorFlow pre installed in docker image:
- TensorFlow version 1.5.0:
- Python version: 3.6.2
- CUDA/cuDNN version: 9.0.176
- GPU model and memory: GeForce GTX 1070 (8GB memory)
- Driver version: 390.87

**Code to reproduce the issue using python**
       import tensorflow as tf
       print(tf.contrib.eager.num_gpus())
  
  Output:
   2018-10-30 18:48:01.232945: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-30 18:48:01.233214: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.695
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 6.59GiB
**2018-10-30 18:48:01.233235: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1168] Ignoring visible gpu device (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1) with Cuda compute capability 6.1. The minimum required Cuda capability is 7.0**.
0

TF 1.5 clearly doesn't require CUDA CC of 7.0. The 1070 has a CC of 6.1 according to NVIDIA which should be enough to support TF1.5. I also have the latest drivers. Someone suggested recompiling TF from source, but that kind of defeats the purpose of using a docker container. Is there any other way? Any pointers will be much appreciated. Thank you.

**Comment by harshini-gadige** [comment]
@satishrClemson  -  Hi, please use CUDA 9 cuDNN 7 for TF v 1.5. Please see below for the details.

![image](https://user-images.githubusercontent.com/42781361/47748837-f9b5d700-dc48-11e8-9097-d3035bc63557.png)

**Comment by satishrClemson** [comment]
I already verified that, as mentioned in the problem description.

**Comment by wdirons** [comment]
The official docker images are here: https://hub.docker.com/r/tensorflow/tensorflow/tags/

The docker image referenced: floydhub/tensorflow:1.5.0-gpu.cuda9cudnn7-py3_aws.22, is not an official image, and when built they specified TF_CUDA_COMPUTE_CAPABILITIES=7.0. An issue could be open against floydhub to have them rebuild the image with expanded TF_CUDA_COMPUTE_CAPABILITIES.

**Comment by wdirons** [comment]
This issue appears fixed if you use the docker image floydhub/1.5.0-gpu.cuda9cudnn7-py3_aws.33, 

The referenced image floydhub/tensorflow:1.5.0-gpu.cuda9cudnn7-py3_aws.22 is 9 months old, and I can see they added TF_CUDA_COMPUTE_CAPABILITIES=3.7,7.0   6 months ago:
https://github.com/floydhub/dockerfiles/blame/master/dl/tensorflow/1.5.0/Dockerfile-py3.gpu.cuda9cudnn7_aws

Future problems with floydhub docker images should be opened against that github repo.

**Comment by satishrClemson** [comment]
Awesome. Thanks @wdirons. Will take it up with Floydhub.
