### ISSUE TITLE
FLOP calculation wrong for matmul with batch dimension

### ISSUE THREAD

**Issue by WuTheFWasThat** [tensorflow/tensorflow#23390]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v1.11.0-rc2-4-gc19e29306c 1.11.0
- Python version: 3.6.5
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
FLOPS is always 0 when specifying batch dimension

**Describe the expected behavior**
FLOPS should be linear in batch dimension

**Code to reproduce the issue**
```
import tensorflow as tf
g = tf.Graph()
with g.as_default():
    b, m, p, q = 2, 25, 16, 9
    A = tf.Variable(tf.zeros([b, m, p]))
    B = tf.Variable(tf.zeros([b, p, q]))
    C = tf.matmul(A,B)

    flops = tf.profiler.profile(g, options = tf.profiler.ProfileOptionBuilder.float_operation())
    print('FLOP should be', b * m * q * 2 * p)
    print('Calculated FLOP', flops.total_float_ops)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by WuTheFWasThat** [comment]
Related: https://github.com/tensorflow/tensorflow/issues/19746

**Comment by harshini-gadige** [comment]
@WuTheFWasThat  - Hi, can you please post the same code snippet and other details in #22071 ?
We can close this issue to avoid duplicates. We will be looking into the issue and post comments in 22071.  Thanks !
