### ISSUE TITLE
translate example is missing '--' in its 'run' command

### ISSUE THREAD

**Issue by hujiewang** [tensorflow/tensorflow#234]
There should be a '--' after 'opt'.
bazel run -c opt -- tensorflow/models/rnn/translate:translate --data_dir <DIR>

**Comment by vrv** [comment]
bazel run [options] [target] -- [--commandlineflags]

**Comment by hujiewang** [comment]
Shouldn't we update the tutorial?  In the translate example, the command is:

bazel run -c opt <...>/models/rnn/translate:translate
  --data_dir [your_data_directory] --train_dir [checkpoints_directory]
  --en_vocab_size=40000 --fr_vocab_size=40000

which doesn't work because it's missing '--'  before arguments

**Comment by vrv** [comment]
We've already fixed it in our internal repo :)  We need to push out the change early this week to both git and the website -- thanks for the feedback!
