### ISSUE TITLE
TPUEstimator cant save checkpoint at google colab

### ISSUE THREAD

**Issue by hadaev8** [tensorflow/tensorflow#23406]
Error recorded from training_loop: File system scheme '[local]' not implemented (file: '/tmp/tmpu0amtet8/model.ckpt-0_temp_b2eedcafbb1e42d1949c6e0ec2f85501')
	 [[node save/SaveV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py:2403)  = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:worker/replica:0/task:0/device:CPU:0"](save/ShardedFilename, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, ReadVariables_2242190548333892376/_1:2, ReadVariables_2242190548333892376/_1, ReadVariables_2242190548333892376/_1:1, ReadVariables_2242190548333892376/_1:5, ReadVariables_2242190548333892376/_1:3, ReadVariables_2242190548333892376/_1:4, ReadVariables_2242190548333892376/_1:8, ReadVariables_2242190548333892376/_1:6, ReadVariables_2242190548333892376/_1:7, ReadVariables_2242190548333892376/_1:11, ReadVariables_2242190548333892376/_1:9, ReadVariables_2242190548333892376/_1:10, ReadVariables_2242190548333892376/_1:14, ReadVariables_2242190548333892376/_1:12, ReadVariables_2242190548333892376/_1:13, ReadVariables_2242190548333892376/_1:17, ReadVariables_2242190548333892376/_1:15, ReadVariables_2242190548333892376/_1:16, ReadVariables_2242190548333892376/_1:20, ReadVariables_2242190548333892376/_1:18, ReadVariables_2242190548333892376/_1:19, ReadVariables_2242190548333892376/_1:23, ReadVariables_2242190548333892376/_1:21, ReadVariables_2242190548333892376/_1:22, ReadVariables_2242190548333892376/_1:26, ReadVariables_2242190548333892376/_1:24, ReadVariables_2242190548333892376/_1:25, ReadVariables_2242190548333892376/_1:29, ReadVariables_2242190548333892376/_1:27, ReadVariables_2242190548333892376/_1:28, ReadVariables_2242190548333892376/_1:32, ReadVariables_2242190548333892376/_1:30, ReadVariables_2242190548333892376/_1:31, ReadVariables_2242190548333892376/_1:35, ReadVariables_2242190548333892376/_1:33, ReadVariables_2242190548333892376/_1:34, ReadVariables_2242190548333892376/_1:38, ReadVariables_2242190548333892376/_1:36, ReadVariables_2242190548333892376/_1:37, ReadVariables_2242190548333892376/_1:41, ReadVariables_2242190548333892376/_1:39, ReadVariables_2242190548333892376/_1:40, ReadVariables_2242190548333892376/_1:44, ReadVariables_2242190548333892376/_1:42, ReadVariables_2242190548333892376/_1:43, ReadVariables_2242190548333892376/_1:47, ReadVariables_2242190548333892376/_1:45, ReadVariables_2242190548333892376/_1:46, ReadVariables_2242190548333892376/_1:50, ReadVariables_2242190548333892376/_1:48, ReadVariables_2242190548333892376/_1:49, ReadVariables_2242190548333892376/_1:53, ReadVariables_2242190548333892376/_1:51, ReadVariables_2242190548333892376/_1:52, ReadVariables_2242190548333892376/_1:56, ReadVariables_2242190548333892376/_1:54, ReadVariables_2242190548333892376/_1:55, ReadVariables_2242190548333892376/_1:59, ReadVariables_2242190548333892376/_1:57, ReadVariables_2242190548333892376/_1:58, ReadVariables_2242190548333892376/_1:62, ReadVariables_2242190548333892376/_1:60, ReadVariables_2242190548333892376/_1:61, ReadVariables_2242190548333892376/_1:65, ReadVariables_2242190548333892376/_1:63, ReadVariables_2242190548333892376/_1:64, ReadVariables_2242190548333892376/_1:68, ReadVariables_2242190548333892376/_1:66, ReadVariables_2242190548333892376/_1:67, ReadVariables_2242190548333892376/_1:71, ReadVariables_2242190548333892376/_1:69, ReadVariables_2242190548333892376/_1:70, ReadVariables_2242190548333892376/_1:74, ReadVariables_2242190548333892376/_1:72, ReadVariables_2242190548333892376/_1:73, ReadVariables_2242190548333892376/_1:77, ReadVariables_2242190548333892376/_1:75, ReadVariables_2242190548333892376/_1:76, ReadVariables_2242190548333892376/_1:80, ReadVariables_2242190548333892376/_1:78, ReadVariables_2242190548333892376/_1:79, ReadVariables_2242190548333892376/_1:83, ReadVariables_2242190548333892376/_1:81, ReadVariables_2242190548333892376/_1:82, ReadVariables_2242190548333892376/_1:86, ReadVariables_2242190548333892376/_1:84, ReadVariables_2242190548333892376/_1:85, ReadVariables_2242190548333892376/_1:89, ReadVariables_2242190548333892376/_1:87, ReadVariables_2242190548333892376/_1:88, ReadVariables_2242190548333892376/_1:92, ReadVariables_2242190548333892376/_1:90, ReadVariables_2242190548333892376/_1:91, ReadVariables_2242190548333892376/_1:95, ReadVariables_2242190548333892376/_1:93, ReadVariables_2242190548333892376/_1:94, ReadVariables_2242190548333892376/_1:98, ReadVariables_2242190548333892376/_1:96, ReadVariables_2242190548333892376/_1:97, ReadVariables_2242190548333892376/_1:101, ReadVariables_2242190548333892376/_1:99, ReadVariables_2242190548333892376/_1:100, ReadVariables_2242190548333892376/_1:104, ReadVariables_2242190548333892376/_1:102, ReadVariables_2242190548333892376/_1:103, ReadVariables_2242190548333892376/_1:107, ReadVariables_2242190548333892376/_1:105, ReadVariables_2242190548333892376/_1:106, ReadVariables_2242190548333892376/_1:110, ReadVariables_2242190548333892376/_1:108, ReadVariables_2242190548333892376/_1:109, ReadVariables_2242190548333892376/_1:113, ReadVariables_2242190548333892376/_1:111, ReadVariables_2242190548333892376/_1:112, ReadVariables_2242190548333892376/_1:116, ReadVariables_2242190548333892376/_1:114, ReadVariables_2242190548333892376/_1:115, ReadVariables_2242190548333892376/_1:119, ReadVariables_2242190548333892376/_1:117, ReadVariables_2242190548333892376/_1:118, ReadVariables_2242190548333892376/_1:122, ReadVariables_2242190548333892376/_1:120, ReadVariables_2242190548333892376/_1:121, ReadVariables_2242190548333892376/_1:125, ReadVariables_2242190548333892376/_1:123, ReadVariables_2242190548333892376/_1:124, ReadVariables_2242190548333892376/_1:126, ReadVariables_2242190548333892376/_1:127, ReadVariables_2242190548333892376/_1:128, ReadVariables_2242190548333892376/_1:129, ReadVariables_2242190548333892376/_1:130)]]

Caused by op 'save/SaveV2', defined at:

Whole code:
https://colab.research.google.com/drive/101FjBAIMVuXyNyeUvq_Vfx-Z6CR3g4df?authuser=1#scrollTo=Sh3TpyAI8Oln

May be i do wrong something

**Comment by harshini-gadige** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. Thank you for your cooperation.

**Comment by harshini-gadige** [comment]
@jhseu   PTAL

**Comment by jhseu** [comment]
You can't save checkpoints locally, but if you have permissions, you can save them through Google Cloud Storage.

**Comment by hadaev8** [comment]
Ok, it doesn't work and problem not in mine code, but isn't it should be fixed?

I want to use colab and tpu.
Docs advise to use TPU estimator. But it doesnt work in colab.

Can I at least disable autosaving? I have not found such an option in docs.

**Comment by jhseu** [comment]
If you set the save_checkpoint options to None, it should disable saving:
https://www.tensorflow.org/api_docs/python/tf/contrib/tpu/RunConfig#save_checkpoints_secs

**Comment by hadaev8** [comment]
Thanks

**Comment by deepakmeena635** [comment]
@jhseu is there any way to fetch the weights after training, back to colab while using estimators,
