### ISSUE TITLE
build with default cuda options fails with "/bin/bash: CUDA_TOOLKIT_PATH: unbound variable"

### ISSUE THREAD

**Issue by wdirons** [tensorflow/tensorflow#23405]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04.5  x86_64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master branch from 10/31/18 - 
- Python version:
- Bazel version (if compiling from source): 0.18.0
- GCC/Compiler version (if compiling from source): 5.4.0 20160609
- CUDA/cuDNN version: 9.0/7
- GPU model and memory: 2x Tesla P100 16 GB

**Describe the current behavior**
Configuring TF to build with CUDA support and choosing all the default option for all the other questions in ./configure including the default for NCCL "Please specify the locally installed NCCL version you want to use. [Default is to use https://github.com/nvidia/nccl]:", the build fails with "/bin/bash: CUDA_TOOLKIT_PATH: unbound variable"

This has been broken since this commit:
https://github.com/tensorflow/tensorflow/commit/fc6cd33c334f88759ce637e29e1586733076e094

Running in the docker container: nvidia/cuda:9.0-cudnn7-devel (for ease of setup)
export TF_NEED_CUDA=1
"" | ./configure
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

failed with:
ERROR: /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/nccl_archive/BUILD.bazel:139:1: Executing genrule @nccl_archive//:device_code_fatbin_h failed (Exit 1)
/bin/bash: CUDA_TOOLKIT_PATH: unbound variable
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 267.057s, Critical Path: 93.66s
INFO: 3606 processes: 3606 local.
FAILED: Build did NOT complete successfully

**Describe the expected behavior**
Build should succeed. 

**Code to reproduce the issue**
export TF_NEED_CUDA=1
"" | ./configure
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Other info / logs**
Fails on both x86 and ppc64le, tried with both bazel 0.15.0 and 0.18.0

**Comment by lypenghao** [comment]
我也遇到了同样的问题，感觉 bazel 就是一个鸡肋

**Comment by wdirons** [comment]
Just tried on a ppc64le redhat container with gcc 4.8.5 and bazel 0.15.0 (cuda10) and the results are the same: 

```
[builder@203325a6deb2 ~]$ bazel version
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.15.0- (@non-git)
Build target: bazel-out/ppc-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 25 03:43:57 2018 (1540439037)
Build timestamp: 1540439037
Build timestamp as int: 1540439037

[builder@203325a6deb2 ~]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[builder@203325a6deb2 tensorflow]$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
.
.
.
ERROR: /home/builder/.cache/bazel/_bazel_builder/3ae15484c762cfa61bbd3dade07b5cf3/external/nccl_archive/BUILD.bazel:139:1: Executing genrule @nccl_archive//:device_code_fatbin_h failed (Exit 1)
/bin/bash: CUDA_TOOLKIT_PATH: unbound variable
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 262.728s, Critical Path: 156.49s
INFO: 4641 processes: 4641 local.
FAILED: Build did NOT complete successfully
```

**Comment by harshini-gadige** [comment]
@gunan  -  PTAL

**Comment by chuckyoufarlie** [comment]
I'm seeing the same while building against CUDA 10 -
CUDA_HOME=/opt/cuda-10.0
CUDA_TOOLKIT_PATH=/opt/cuda-10.0

`$ bazel version  
WARNING: Processed legacy workspace file /scratch/opt/tensorflow-1.12.0/src/tensorflow/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
WARNING: Output base 'homes/fultz/.cache/bazel/_bazel_fultz/a3796d4ff5cfe6f876d63615ff95821d' is on NFS. This may lead to surprising failures and undetermined behavior.
Build label: 0.18.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 31 14:46:05 2018 (1540997165)
Build timestamp: 1540997165
Build timestamp as int: 1540997165

$ CUDA_TOOLKIT_PATH=/opt/cuda-10.0 bazel build --config=noaws --config=nogcp --config=nohdfs --config=noignite --config=nokafka //tensorflow/tools/pip_packa
ge:build_pip_package
...
ERROR: /homes/fultz/.cache/bazel/_bazel_fultz/a3796d4ff5cfe6f876d63615ff95821d/external/nccl_archive/BUILD.bazel:139:1: Executing genrule @nccl_archive//:device_code_fatbin_h failed (Exit 1)
/bin/bash: CUDA_TOOLKIT_PATH: unbound variable
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 41.210s, Critical Path: 26.82s
INFO: 277 processes: 277 local.
FAILED: Build did NOT complete successfully`

**Comment by wdirons** [comment]
This commit appears to fix the problem: https://github.com/tensorflow/tensorflow/commit/456e6927c0c0ff6b497b07875c0043cb59086414

I'm verifying with a build now.
