### ISSUE TITLE
WARNING:tensorflow:Tensor._shape is private, use Tensor.shape instead. Tensor._shape will eventually be removed.

### ISSUE THREAD

**Issue by zkl99999** [tensorflow/tensorflow#23417]
**System information**
- Linux Ubuntu 16.04
- TensorFlow installed from  binary:
- TensorFlow version :1.11
- Python version :3.5
- CUDA/cuDNN version:9.0/7.1
- GPU model and memory:GeForce GTX TITAN X 

**Describe the current behavior**
(tfzkl) ddc@:~/zklcode/leapmotion$ cd /home/zklcode/leapmotion ; env "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" /home/anaconda3/envs/tfzkl/bin/python3.5 /home/ddc/.vscode/extensions/ms-python.python-2018.9.1/pythonFiles/experimental/ptvsd_launcher.py 41383 /home/zklcode/leapmotion/leap/leaptf/tfleap.train.py
dataset shape:(100, 2)
Backend TkAgg is interactive backend. Turning interactive mode on.
WARNING:tensorflow:Tensor._shape is private, use Tensor.shape instead. Tensor._shape will eventually be removed.
WARNING:tensorflow:Tensor._shape is private, use Tensor.shape instead. Tensor._shape will eventually be removed.

my code don`t call tf.shape() function, why show this WARNING? anyone have this issue?

**Comment by zkl99999** [comment]
/home/anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:108: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

how do this happen? is it a bug?

**Comment by harshini-gadige** [comment]
@allenlavoie   PTAL

**Comment by harshini-gadige** [comment]
@tanzhenyu  PTAL

**Comment by harshini-gadige** [comment]
@zkl99999   -  In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by zkl99999** [comment]
my code of following:
`#-*-coding:utf-8 -*-

import numpy as np 
import tensorflow as tf 
from tensorflow.python.tools import freeze_graph
from tensorflow.python.framework import graph_util
import os 
from sklearn.model_selection import train_test_split
import json
import pymysql
import sys

path = os.path.abspath(sys.argv[0])
path = os.path.realpath(sys.argv[0])
dirname,filename = os.path.split(path)
os.chdir(dirname)
cwd = os.getcwd()

#运行结束 失效吗
# sys.path.append('..')


gesture = ["左手","右手","左手悬停","右手悬停","再来一遍"]
n_classes = 4
#N*time 帧数* 一帧的维度
dims =63
time_steps = 60

batch_size = 32

# 1*n   1*60*63
OUT_NAME_NODE = 'predict'
INPUR_NAME_NODE = 'input'

def batch_generator(x_train,y_train,batch_size=batch_size):
    offset = 0
    index = [ i for i in range(len (x_train)) ]
    while True:
        offset +=batch_size

        if offset == batch_size or offset >= y_train.shape[0]:
            
            #切记不能这样刷数据，数据和标签乱了，np.random.shuffle(y_train)
            np.random.shuffle(index)
            
            y_train = y_train[index]
            x_train = x_train[index]

            # [x_train,y_train] = np.random.shuffle([x_train,y_train])
            offset = batch_size

        #offset = (itr * batch_size) % (y_train.shape[0] - batch_size)
  
        batch_x = x_train[offset-batch_size:(offset), :, :]
        batch_y = y_train[offset-batch_size:(offset), :]

        yield (batch_x,batch_y)



def save_one_class_data(label,data,num):
    label_0 = np.where(leap_label ==num)[0]
   
    data_0 =[]

    for i in label_0:
        d_ = leap_data[i]
        data_0.append(d_)

    np.savez("data_0.npz",data_0)

    D = np.load("data_0.npz")
    print(len(D))
    A = D["arr_0"]
    print(len(A))


conn = pymysql.connect(host = "218.68.6.114",user = "leapmotion",passwd = 'leapmotion',db = 'leapmotion_data',port =3306)
cur = conn.cursor()

cur.execute('select * from LeapMachine where id <> 101 and id <=100')

'''
'(('{json}',id))'
'''
data_all = cur.fetchall()


#二维元组转 二维list
data_all = list(data_all)
for c in data_all:
    data_all[data_all.index(c)] = list(c)

print ("dataset shape:{}".format(np.shape(data_all)))

#取数据
'''
['{json,}','{}'],用于json.loads  then,字典取数据和label
'''
data__ = [ i[0] for i in  data_all]

leap_data =  []
leap_label =  []
a=0
for j in data__:
    leap_ = json.loads(j)
    label_ = leap_['ControllerTypeInt']
    data_ = leap_['leapdata']
    
    #print(len(data_),np.shape(data_),a)
    leap_data.append(data_)
    leap_label.append(label_)
    a+=1

#转numpy数组,方便后续操作
# error ValueError: setting an array element with a sequence.



leap_data = np.array(leap_data,dtype= np.float32)
leap_label = np.array (leap_label)


#把每个动作的样本分开存储
#save_one_class_data(leap_label,leap_data,0)
#定义测试数据  和训练数据 ？？？


#打乱 借助index
index = [ i for i in range(len (leap_data)) ]
#in-place 原地计算，返回值为none
np.random.shuffle(index)

leap_data = leap_data[index]
leap_label = leap_label[index]

#one-hot label  N*2

leap_label_oh = tf.one_hot(leap_label,n_classes,on_value=1.0)  

label_np_oh = (np.arange(n_classes) == leap_label[:,None]).astype(np.integer)


X_train,X_test,y_train,y_test = train_test_split(leap_data,label_np_oh,test_size=0.5)

#批量函数，
#hidden lyers
lstm_size = 128
num_layers = 3

keep_prob = 0.5
epoches = 10

learning_rate = 0.0001
training_iters =2000# epoches*(y_train.shape[0]//batch_size)  # epoches * len(train)/batch
max_steps = 100000
display_step = 200
save_every_n = 500

test_log = 5
 #<tf.Operation 'input' type=Placeholder>,
lstm_inputs = tf.placeholder(dtype = np.float32,shape=(None,time_steps,dims),name=INPUR_NAME_NODE)

y = tf.placeholder("float", [None, n_classes])



def get_a_cell(lstm_size,keep_prob):
    lstm = tf.nn.rnn_cell.LSTMCell(num_units = lstm_size)
    ##lstm里面添加dropout
    dropout = tf.nn.rnn_cell.DropoutWrapper(lstm,output_keep_prob=keep_prob)

    return dropout


with tf.name_scope('lstm'):

    # cell = rnn_cell.LSTMCell(n_hidden,state_is_tuple = True)
    # cell = rnn_cell.MultiRNNCell([cell] * 2)

    cell = tf.nn.rnn_cell.MultiRNNCell( [get_a_cell(lstm_size,keep_prob) for _ in range(num_layers)])


    #h0
    initial_state =  cell.zero_state(batch_size,tf.float32)
    # initial_state =  cell.zero_state(None,tf.float32)


    #(batch_size,time_step,cell.output_size),,(batch_size,sell.state_size)
    lstm_outputs,final_state = tf.nn.dynamic_rnn(cell=cell,inputs = lstm_inputs, dtype = tf.float32)#initial_state=initial_state)
  
    # 通过lstm_outputs得到概率
    # seq_output = tf.concat(lstm_outputs,1)
    # x = tf.reshape(seq_output,[-1,lstm_size])

    # with tf.variable_scope('softmax'):
    #时间维度放在第一维，
    output = tf.transpose(lstm_outputs,[1,0,2])
    # last = tf.gather(output,tf.int16 int(output.get_shape())[0] - 1 )
    ##60*batch*128，拿最后一个batch*128，，即横排，时间序列 最后一个时间步输出的数据，N vs1  这一步关键

    lstmlast = tf.gather(output,int(output.get_shape()[0] )- 1 )


# weight = tf.Variable(tf.random_normal([128, n_classes]))
# bias = tf.Variable(tf.random_normal([n_classes]))
# flatten = tf.matmul(lstmlast, weight) + bias
# pred = tf.cast (flatten,tf.float32)


##lstm 输出再加上两层 全连接层
dense1 = tf.layers.dense(inputs = lstmlast,units = 20,activation=tf.nn.relu )
#<tf.Tensor 'las1/Relu:0' shape=(1, 4) dtype=float32>

dense1 =  tf.layers.dropout(dense1,keep_prob)

dense2 = tf.layers.dense(inputs = dense1,units=20,activation=tf.nn.relu)
dense2 =  tf.layers.dropout(dense2,keep_prob)
#  tf.layers.BatchNormalization()


#name 是层节点  predict/BiasAdd
pred = tf.layers.dense(inputs = dense2,units =n_classes,name='output' )#,name='predict' 在这里添加节点 转pb文件 竟然说没有这个节点


logits_scaled = tf.nn.softmax(pred,name=OUT_NAME_NODE)
#层节点，节点output/BiasAdd:0,predict:0
print("层节点，节点{},{}".format(pred.name,logits_scaled.name))

##负数给 值0了    张量名字
# tf.cast 不是一个操作，不是一个节点，所以即使命名，网络图中也没有这个，， 节点  分  计算节点 ？？ 图节点？？  层节点  tensorboard 节点
# pred = tf.cast (tf.matmul(last, weight) + bias,tf.float32,name="predict")
#tf.add(tf.matmul(last, weight) + bias,name="predict")


##第三种写法
#以下这两种 是不是一样的 哪个是预测结果
#prediction = tf.nn.softmax(tf.matmul(last, weight) + bias,name="output")
# with tf.name_scope('output'):
#     pred_  = (tf.matmul(last, weight) + bias)
#     pred =  tf.cast(pred_,tf.float32)  #任意list数据  未归一化的，



# logits_scaled = tf.nn.softmax(pred,name='predict') #归一化了 每个类别的概率，
# allow gradients to flow into the labels input on backprop by default. 输入 未归q一化的logits 
#神经网络输出就是logit，加上softmax 是logit_scaled,,
cross_entropy = tf.nn.softmax_cross_entropy_with_logits_v2(labels=y,logits=pred)
cross_entropy_mean = tf.reduce_mean(cross_entropy,name='cross_entropy_mean')

#add summary
tf.summary.scalar('loss',cross_entropy_mean)

global_step = tf.Variable(0)
#true 阶梯，false 连续变化，每100轮学习率*0.98，
lrexpon = tf.train.exponential_decay(1e-2,global_step,decay_steps=100,decay_rate=0.98,staircase=True)    
# optimizer = tf.train.AdamOptimizer(   learning_rate = lr).minimize(cross_entropy_mean,global_step= global_step)
optimizer = tf.train.AdamOptimizer(   learning_rate = learning_rate).minimize(cross_entropy_mean)

#tf.argmax返回 索引，预测的坐标索引和实际坐标索引，一样， 
correct_pred = tf.equal(tf.argmax(pred,1),  tf.argmax(y,1))
accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float64))
# accuracy = tf.reduce_mean(correct_pred)

tf.summary.scalar('accuracy',accuracy)

merged = tf.summary.merge_all()
#不存在 可以新建目录
log_path = './log3'


init = tf.global_variables_initializer()

saver = tf.train.Saver()
save_path = './model3/'



with tf.Session() as session:
    train_writer = tf.summary.FileWriter(log_path+ '/train',session.graph)
    test_writer = tf.summary.FileWriter(log_path+ '/test')
    
    
    # tmp = sess.run(leap_label_oh)
    # batchdata = batch_generator(leap_data,leap_label_oh,batch_size)
    # print(tmp)
    session.run(init)

    #You can get all of the node names in your model with something like:
    # node_names = [node.name for node in tf.get_default_graph.  as_graph_def().node]
    node_names = [node for node in  session.graph.as_graph_def().node]
    # print(node_names['input'],'\n',node_names['output'])
    # with  open("./sqltest/node_names.txt",'w') as f:
    #     f.write(str(node_names))
    # np.savetxt("./sqltest/node_names.txt",node_names)

    

    graph = tf.get_default_graph() #获得默认的图
    #是一个图
    assert graph is session.graph

    aaa =tf.global_variables()


    #全错误
    # print (tf.get_default_graph.as_graph_def.node_names['predict'])
    # print (session.node_names['predict'])
    
    # print( tf.get_default_graph().get_tensor_by_name("predict"))

    ##可以得到全部的操作  能不能像linux命令  < 
    #python run.py | grep '==my_command=='  > my_command.sh
    nodea = tf.get_default_graph().get_operations()
    # print (tf.get_default_graph().get_operations())

    batch_gen = batch_generator(X_train,y_train,batch_size)
    step =0
    for epoch in range(epoches):

        for itr in range(training_iters):  
            
            batch_x,batch_y  =  next(batch_gen)   
            #error  ValueError: too many values to unpack (expected 2)
            # batch_x_,batch_y_ = batch_generator(X_train,y_train,batch_size)

            # offset = (itr * batch_size) % (y_train.shape[0] - batch_size)
            # batch_x = X_train[offset-batch_size:(offset), :, :]
            # batch_y = y_train[offset-batch_size:(offset), :]



            summary, _, c = session.run([merged, optimizer, cross_entropy_mean],feed_dict={lstm_inputs: batch_x, y : batch_y})
            train_writer.add_summary(summary,itr)
            step += 1
            
            # learing_rate.eval(session=sess)
            # lr= session.run(lrexpon)

            if step % test_log ==0:
                summ= session.run(merged, feed_dict={lstm_inputs: X_test, y: y_test})
                test_writer.add_summary(summ,itr)

            if step % display_step == 0:
                # Calculate batch accuracy
                acc = session.run(accuracy, feed_dict={lstm_inputs: batch_x, y: batch_y})
                # Calculate batch loss
                loss = session.run(cross_entropy_mean, feed_dict={lstm_inputs: batch_x, y: batch_y})

                acc_val = session.run(accuracy, feed_dict={lstm_inputs: X_test, y: y_test})           

                print ("Iter " + str(step) + ", Minibatch Loss= " + \
                    "{:.6f}".format(loss) + ", Training Accuracy= " + \
                    "{:.5f}".format(acc) +", Testing Acc= "+ \
                    "{:.5f}".format(acc_val) )

            if (step % save_every_n == 0):
                saver.save(session, os.path.join(save_path, 'model.ckpt'), global_step=step)
                tf.train.write_graph(session.graph_def,save_path,'raw_graph_def.pb',as_text=False)
            if step >= max_steps or c< 1e-5: #stop early 防止过拟合
                break


    # print('Test accuracy: ',round(session.run(accuracy, feed_dict={lstm_inputs: X_test[:batch_size], y: y_test[:batch_size]}) , 3))
    print('Test accuracy: ',round(session.run(accuracy, feed_dict={lstm_inputs: X_test, y: y_test}) , 3))
    
    ##test   logits_scaled
    test_pred = session.run(pred,feed_dict={lstm_inputs: X_test[:5]})
    test_y = y_test[:5]

    print("test ; {},{}".format(test_pred,test_y))



    test_writer.close()
    train_writer.close()




###把ckpt，meta文件转为 一个pb集成网络参数一起的文件
def ckpt2pb(MODEL_DIR,output_graph):

    if not tf.gfile.Exists(MODEL_DIR):
        tf.gfile.MakeDirs(MODEL_DIR)
 
    checkpoint = tf.train.get_checkpoint_state(MODEL_DIR) 
    input_checkpoint = checkpoint.model_checkpoint_path 
    #拿最新的 model.ckpt-5000 str
    input_checkpoint2 = tf.train.latest_checkpoint(MODEL_DIR)
    
    # output_graph = os.path.join(MODEL_DIR, MODEL_NAME) #PB模型保存路径
    #原模型输出操作节点的名字
    output_node_names = OUT_NAME_NODE 
    #得到图、
    saver = tf.train.import_meta_graph(input_checkpoint2 + '.meta', clear_devices=True) 
    graph = tf.get_default_graph() 
    #返回一个序列化的图
    input_graph_def = graph.as_graph_def()  
    with tf.Session() as sess:
        saver.restore(sess, input_checkpoint2) 

        # print ("predictions : ", sess.run("predict:0", feed_dict={"input:0": [10.0]})) # 测试读出来的模型是否正确，注意这里传入的是输出 和输入 节点的 tensor的名字，不是操作节点的名字

        output_graph_def = graph_util.convert_variables_to_constants(  
            sess,
            input_graph_def,
            output_node_names.split(",") #如果有多个输出节点，以逗号隔开
        )
        with tf.gfile.GFile(output_graph, "wb") as f: #保存模型
            f.write(output_graph_def.SerializeToString()) #序列化输出
    

        #for op in graph.get_operations():
            # print(op.name, op.values())

output_gra = "./frozen/frozen_model3.pb"
MODEL_DIR = save_path
ckpt2pb(MODEL_DIR,output_gra)


`

**Comment by harshini-gadige** [comment]
> @zkl99999 - In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

@zkl99999  -  Any update ?

**Comment by harshini-gadige** [comment]
In "awaiting response" status for more than 3 days. Hence closing this. Please post the updates here if any, we will reopen the issue. Thanks !
