### ISSUE TITLE
install adanet model got wrong 

### ISSUE THREAD

**Issue by cjr0106** [tensorflow/tensorflow#23419]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by cjr0106** [comment]
hi , i want to install the model "adanet"
1 、tensorflow version: 1.7.0
2、installed bazel:  bazel-0.17.2-installer-linux-x86_64.sh
3、but  when  `bazel test -c opt //...` , it got the error:
INFO: Analysed 36 targets (0 packages loaded).
INFO: Found 22 targets and 14 test targets...
FAIL: //adanet/core:estimator_test (shard 11 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_11_of_20/test.log)
FAIL: //adanet/examples:simple_dnn_test (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/examples/simple_dnn_test/test.log)
FAIL: //adanet/core:report_accessor_test (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/report_accessor_test/test.log)
FAIL: //adanet/core:estimator_test (shard 3 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_3_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 17 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_17_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 10 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_10_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 14 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_14_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 7 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_7_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 8 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_8_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 5 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_5_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 2 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_2_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 9 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_9_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 1 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_1_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 15 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_15_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 12 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_12_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 6 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_6_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 13 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_13_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 4 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_4_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 16 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_16_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 19 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_19_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 20 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_20_of_20/test.log)

FAILED: //adanet/core:estimator_test (Summary)
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_11_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_3_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_17_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_10_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_14_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_7_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_8_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_5_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_2_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_9_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_1_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_15_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_12_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_6_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_13_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_4_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_16_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_19_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_20_of_20/test.log
      /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_18_of_20/test.log
FAIL: //adanet/core:estimator_test (shard 18 of 20) (see /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_18_of_20/test.log)
INFO: Elapsed time: 2.128s, Critical Path: 1.47s
INFO: 22 processes: 22 processwrapper-sandbox.
INFO: Build completed, 3 tests FAILED, 23 total actions
//adanet/core:candidate_test                                    (cached) PASSED in 3.5s
//adanet/core:ensemble_test                                     (cached) PASSED in 18.7s
//adanet/core:evaluator_test                                    (cached) PASSED in 2.6s
//adanet/core:freezer_test                                      (cached) PASSED in 4.9s
//adanet/core:input_utils_test                                  (cached) PASSED in 2.2s
//adanet/core:iteration_test                                    (cached) PASSED in 12.2s
//adanet/core:report_materializer_test                          (cached) PASSED in 2.2s
//adanet/core:summary_test                                      (cached) PASSED in 2.1s
//adanet/core:timer_test                                        (cached) PASSED in 2.5s
//adanet/core/subnetwork:generator_test                         (cached) PASSED in 2.1s
//adanet/core/subnetwork:report_test                            (cached) PASSED in 2.0s
//adanet/core:report_accessor_test                                       FAILED in 0.6s
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/report_accessor_test/test.log
//adanet/examples:simple_dnn_test                                        FAILED in 0.6s
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/examples/simple_dnn_test/test.log
//adanet/core:estimator_test                                             FAILED in 20 out of 20 in 0.8s
  Stats over 20 runs: max = 0.8s, min = 0.6s, avg = 0.7s, dev = 0.0s
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_11_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_3_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_17_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_10_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_14_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_7_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_8_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_5_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_2_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_9_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_1_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_15_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_12_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_6_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_13_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_4_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_16_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_19_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_20_of_20/test.log
  /root/.cache/bazel/_bazel_root/015a6089d8b90e272be423ca56fb1611/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_18_of_20/test.log

Executed 3 out of 14 tests: 11 tests pass and 3 fail locally.
INFO: Build completed, 3 tests FAILED, 23 total actions

4 、so when import adanet . it got the error:

>>> import adanet 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/caojinrong/adanet/adanet/__init__.py", line 22, in <module>
    from adanet.core import Ensemble
  File "/home/caojinrong/adanet/adanet/core/__init__.py", line 25, in <module>
    from adanet.core.estimator import Estimator
  File "/home/caojinrong/adanet/adanet/core/estimator.py", line 33, in <module>
    from adanet.core.report_accessor import _ReportAccessor
  File "/home/caojinrong/adanet/adanet/core/report_accessor.py", line 24, in <module>
    from adanet.core import report_pb2 as report_proto
ImportError: cannot import name 'report_pb2'

**Comment by ymodak** [comment]
Hi,
This issue is better suited on [adanet repo](https://github.com/tensorflow/adanet/issues).
Closing this issue, feel free to post this issue on adanet repo. Thanks!
