### ISSUE TITLE
Error in compile  tensorflowr1.8 on windows by vs2015 (Error: LNK1189 ：More than 65535 object restrictions)

### ISSUE THREAD

**Issue by sevensix6** [tensorflow/tensorflow#23416]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Windows 10):
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.8
- Python version:3.6
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:9.0/7
- GPU model and memory:2

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sevensix6** [comment]
I have compiled the tensorlfowr1.8 in Release mode with GPU version and get the tensorflow.dll. When to debug mode, all project have been compiled successed except "tensorflow" project, and I compile it alone (Enable GPU) but Error of "LNK1189 ：More than 65535 object restrictions" occured. Any suggestions? Looking forward your reply~

**Comment by ymodak** [comment]
If possible can you please use the latest version of TensorFlow and build again ?

**Comment by ymodak** [comment]
Is this still an issue for you? Can you please provide following information:
OS Platform and Distribution (e.g., Windows 10):
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
Thanks!

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
