### ISSUE TITLE
NameError name 'uses_learning_phase' is not defined when using Keras TimeDistributed with batch_shape on Input

### ISSUE THREAD

**Issue by rickdzekman** [tensorflow/tensorflow#23425]
I have an LSTM layer where I am using `stateful=True`. As a result I need to specify `batch_shape` on my `Input` layers:

    input_xs = tf.keras.layers.Input(batch_shape=(batch_size,seq_length))

I have a layer where I add a context vector to each input *at each timestep*. I currently achieve this with `TimeDistributed` and a `Lambda` layer as follows:

    concatenator = tf.keras.layers.TimeDistributed(tf.keras.layers.Lambda(lambda x: tf.keras.layers.Concatenate()([x,concat_context])))

But the moment I added the `batch_shape` to my inputs I started getting the following error:

```
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 769, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\keras\layers\wrappers.py", line 250, in call
    unroll=False)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\keras\backend.py", line 3193, in rnn
    outputs, _ = step_function(inputs[0], initial_states + constants)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\keras\layers\wrappers.py", line 242, in step
    uses_learning_phase)
NameError: name 'uses_learning_phase' is not defined
```

This seems related to: https://github.com/keras-team/keras/issues/4178

Would appreciate any thoughts on what is happening here.

**Comment by harshini-gadige** [comment]
@drpngx  PTAL

**Comment by harshini-gadige** [comment]
> Hi @rickdzekman , can u provide the version information for the TF you are running? This might help us understand and narrow down the window for the source of the bug.
> 
> ### System information
> * **What is the top-level directory of the model you are using**:
> * **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
> * **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
> * **TensorFlow installed from (source or binary)**:
> * **TensorFlow version (use command below)**:
> * **Bazel version (if compiling from source)**:
> * **CUDA/cuDNN version**:
> * **GPU model and memory**:
> * **Exact command to reproduce**:
> 
> You can collect some of this information using our environment capture script:
> 
> https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh
> 
> You can obtain the TensorFlow version with
> 
> python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
> 
> ### Describe the problem
> Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
> 
> ### Source code / logs
> Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

@rickdzekman  -  Any update ?

**Comment by rickdzekman** [comment]
Before following up on the bug I thought I would describe my workaround for anyone else experiencing this problem. You can manually implement TimeDistributed using `tf.keras.backend.rnn` like so:

```
def apply_concats(layer,context):
    concat_lambda = tf.keras.layers.Lambda(lambda x: tf.keras.layers.Concatenate()([x,context]))
    input_shape = tf.keras.backend.int_shape(layer)
    def lambda_step(x, _):
        return concat_lambda(x), []

    _, outputs, _ = tf.keras.backend.rnn(
        lambda_step,
        layer,
        initial_states=[],
        input_length=input_shape[1],
        unroll=False
    )
    return outputs

concatenator = tf.keras.layers.Lambda(lambda x: apply_concats(x[0],x[1]),name="input_concat")
concatenated = concatenator([input_sequence,sequence_context])
```

Note: you **must** pass both layers into the lambda otherwise those layers will not be trained. In my case, I first tried passing the `sequence_context` into the function as a closure, this resulted in the weights for the `sequence_context` not being trained.

**Comment by rickdzekman** [comment]
Hi @harshini-gadige

Sorry for the delayed reply.


**What is the top-level directory of the model you are using:**
I'm not sure what this means?

**Have I written custom code (as opposed to using a stock example script provided in TensorFlow):**
I am not using any stock example scripts

**OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**
Windows 10

**TensorFlow installed from (source or binary):**
Binary installed with pip

**TensorFlow version (use command below):**
From my `pip list` >> `tensorflow-gpu      1.11.0`

**CUDA/cuDNN version:**
CUDA Version 9.0.176
cudnn-9.0-windows10-x64-v7.3.0.29

**GPU model and memory:**
GeForce GTX 850M (4.0GB)

**Exact command to reproduce:**
A minimal example to reproduce the error is below:

```
import tensorflow as tf

batch_size = 64
dict_size = 100
word_vec_size = 20
input_length = 10
context_size = 2

input_xs = tf.keras.layers.Input(batch_shape=(batch_size,input_length),dtype="int32",name="input_xs")
context = tf.keras.layers.Input(batch_shape=(batch_size,2),dtype="float32",name="input_context")

word_embedding = tf.keras.layers.Embedding(dict_size, word_vec_size, input_length=input_length, name='word_embedding')
word_vecs = word_embedding(input_xs)

concatenator = tf.keras.layers.TimeDistributed(tf.keras.layers.Lambda(lambda x: tf.keras.layers.Concatenate()([x,context])))
outputs = concatenator(word_vecs)

model = tf.keras.models.Model(inputs=[input_xs,context],outputs=outputs)
```
The full error output:

```
Traceback (most recent call last):
  File "td_error.py", line 18, in <module>
    outputs = concatenator(word_vecs)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 769, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\keras\layers\wrappers.py", line 250, in call
    unroll=False)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\keras\backend.py", line 3193, in rnn
    outputs, _ = step_function(inputs[0], initial_states + constants)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\keras\layers\wrappers.py", line 242, in step
    uses_learning_phase)
NameError: name 'uses_learning_phase' is not defined
```

If I implement the concatenation manually using `tf.keras.backend.rnn` the error goes away but a new problem is introduced:

```
def apply_concats(layer,context):
    concat_lambda = tf.keras.layers.Lambda(lambda x: tf.keras.layers.Concatenate()([x,context]))
    input_shape = tf.keras.backend.int_shape(layer)
    def lambda_step(x, _):
        return concat_lambda(x), []

    _, outputs, _ = tf.keras.backend.rnn(
        lambda_step,
        layer,
        initial_states=[],
        input_length=input_shape[1],
        unroll=False
    )
    return outputs

concatenator = tf.keras.layers.Lambda(lambda x: apply_concats(x,context))
outputs = concatenator(word_vecs)
model = tf.keras.models.Model(inputs=[input_xs,context],outputs=outputs)\
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy')
print(model.summary())
```
The output for `print(model.summary())` shows:
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_xs (InputLayer)        (64, 10)                  0
_________________________________________________________________
word_embedding (Embedding)   (64, 10, 20)              2000
_________________________________________________________________
lambda (Lambda)              (64, 10, 22)              0
=================================================================
Total params: 2,000
Trainable params: 2,000
Non-trainable params: 0
_________________________________________________________________
```
Which does not include the context layer because it is in the Lambda as a closure.

This can be fixed easily enough but I thought it was worth pointing out.

**Comment by plison** [comment]
I can confirm the issue - I got the exact same error when applying a `TimeDistributed` layer with inputs specified with `batch_shape`.

**Comment by qlzh727** [comment]
Hi all, sorry for the very late reply. I was able to repro this issue in 1.11 but not in tf-nightly. This indicates that the issue was recently been fixed. Looking at the code history, @fchollet has some recent global change for the uses_learning_phase, which might already fix the issue.

Can you confirm that whether it as been fixed in the latest head by "pip install -U tf-nightly" or "pip install -U tf-nightly-gpu"?

Thanks.

**Comment by qlzh727** [comment]
Assume the bug has already been fixed from my previous observation, closing the bug for now. Please reopen this issue if there are still outstanding issue.
