### ISSUE TITLE
Deploying TF-TRT model on DLA on NVIDIA Xavier platform

### ISSUE THREAD

**Issue by dhingratul** [tensorflow/tensorflow#23437]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.8
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently the TF-TRT integration only allows to deploy on dGPU or iGPU by changing DEFAULT_CUDA_VISIBLE_DEVICE. However, to deploy on DLA you need to go through native TRT support, which nullifies the USP of TF-TRT(falling back on TF for unsupported ops instead of writing custom ops). Please see https://github.com/nvdla/sw for details.

**Will this change the current api? How?** no

**Who will benefit with this feature?** Everyone deploying TF models on NVIDIA based embedded H/W including Jetson, DRIVE AGX

**Any Other info.**

**Comment by samikama** [comment]
@dhingratul,

Can you clarify what you ask?

**Comment by dhingratul** [comment]
Take a look here,
https://devtalk.nvidia.com/default/topic/1043020/jetson-agx-xavier/running-tensorflow-program-on-igpu-dla-solved-/post/5290874/#5290874

I would like to know if there any WIP to use TF-TRT integration instead of native TRT to use the DLA on DRIVE/Jetson AGX?
