### ISSUE TITLE
Distributed Runtime protos aren't sandbox compatible

### ISSUE THREAD

**Issue by brianretford** [tensorflow/tensorflow#2343]
The master/worker protos don't include their dependent source files in the rules that constitute them in a way that enables tensorflow to be used from a skylark rule. This is annoying.

**Comment by forsake** [comment]
I met this , is  a same issue？

/root/tensorflow/tensorflow/core/BUILD:135:1: null failed: protoc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/tensorflow && \
  exec env - \
  bazel-out/host/bin/google/protobuf/protoc '--cpp_out=bazel-out/local_linux-opt/genfiles/' '--plugin=protoc-gen-grpc=bazel-out/host/bin/external/grpc/grpc_cpp_plugin' '--grpc_out=bazel-out/local_linux-opt/genfiles/' -I. -Igoogle/protobuf/src tensorflow/core/protobuf/master_service.proto): protoc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/tensorflow && \
  exec env - \
  bazel-out/host/bin/google/protobuf/protoc '--cpp_out=bazel-out/local_linux-opt/genfiles/' '--plugin=protoc-gen-grpc=bazel-out/host/bin/external/grpc/grpc_cpp_plugin' '--grpc_out=bazel-out/local_linux-opt/genfiles/' -I. -Igoogle/protobuf/src tensorflow/core/protobuf/master_service.proto).
tensorflow/core/protobuf/master.proto: File not found.

**Comment by b33pr** [comment]
Pretty much, yup. I 'fixed' it by removing the distributed rules from a forked version of Tensorflow, cause I don't care about them right now

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Verify that this is still a problem on the latest version of TensorFlow and reopen if it does.
