### ISSUE TITLE
Bug in tensorflow lite java wrapper

### ISSUE THREAD

**Issue by shivamkhare95** [tensorflow/tensorflow#23449]
In file 
"https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/src/main/java/org/tensorflow/lite/NativeInterpreterWrapper.java" line 286:
  ****/** Gets the number of output tensors. */
  int getOutputTensorCount() {
    return inputTensors.length;
  }****

In this function, output tensors.length should be used instead of inputTensors.length

**Comment by harshini-gadige** [comment]
@andrehentz   PTAL

**Comment by jdduke** [comment]
Wow, good catch, that's a nasty bug. Will have a fix up shortly, thanks for the feedback.
