### ISSUE TITLE
Python client link is broken

### ISSUE THREAD

**Issue by xiaofei06** [tensorflow/tensorflow#23443]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: unrelated, I'm using github ui viewing the code
- Doc Link: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/client_lib.py#L18

**Describe the documentation issue**
This link https://tensorflow.org/api_guides/python/client gives 404

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by harshini-gadige** [comment]
@MarkDaoust  -  PTAL

**Comment by MarkDaoust** [comment]
Hi @xiaofei06, 

Thanks for the report.

Normally I'd just ask you to send a PR, but this is a little bigger than it looks.

It affects ~20 files. A fix is on it's way.
