### ISSUE TITLE
AOT compilation of an Estimator

### ISSUE THREAD

**Issue by volvador** [tensorflow/tensorflow#23459]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:1.11
- **Python version**:2.7
- **Bazel version (if compiling from source)**:NA
- **GCC/Compiler version (if compiling from source)**:NA
- **CUDA/cuDNN version**:NA
- **GPU model and memory**:NA
- **Exact command to reproduce**:NA

I find it very challenging to find in the documentation any help on this important issue.. Indeed, after creating an estimator (canned or custom), one wants to `tf.compile` the resulting predictor, produce the `.so` and link it to one's project..

So I have my calib class in which I define a simple linear estimator

    self.model = tf.estimator.LinearRegressor(
            feature_columns=self.feature_columns,
            model_dir = self.model_dir)

After training, I want to 
1- get the trained model with optimal parameters (load it in my variable self.model)
2- extract the graph and freeze it
3- tf.compile that graph

I could not find any way to do parts 1- and 2-. 
Can you please point me to a good way to it?

**Comment by superbobry** [comment]
StackOverflow is more suited for such questions. 

Steps 1/2 are covered here: https://www.tensorflow.org/guide/saved_model#using_savedmodel_with_estimators

**Comment by volvador** [comment]
This [https://medium.com/google-cloud/optimizing-tensorflow-models-for-serving-959080e9ddbf](url)
helped a lot
