### ISSUE TITLE
Numpy Layer

### ISSUE THREAD

**Issue by Russell91** [tensorflow/tensorflow#2345]
Is there no way for me to create a new layer in python as a function with inputs and outputs as cpu numpy arrays. This would be especially useful for certain custom operations (say an opencv call in the middle of the network, or a special logging layer). But as far as I can tell, it is not available, and one has to go through the hassle of writing a c++ layer and recompiling to be able to get direct access to any data below the symbolic level. Am I missing something?

The fact I can't do this creates massive workarounds. In some cases, I call sess.run() once, getting the result as a numpy array, do my operations, and then call sess.run() again. So there are 2 sess.run() calls for one iteration of training.

**Comment by ajtulloch** [comment]
https://www.tensorflow.org/versions/r0.7/api_docs/python/script_ops.html#py_func

**Comment by Russell91** [comment]
Great, thanks!
