### ISSUE TITLE
Fail to configure on Windows(CMake3.11.0-rc2, VS2015, python3.5.3, swigwin-3.0.12)

### ISSUE THREAD

**Issue by zhenngbolun** [tensorflow/tensorflow#23472]
CMake Warning at CMakeLists.txt:9 (message):
  Your current cmake generator is set to use 32 bit toolset architecture.
  This may cause "compiler out of heap space" errors when building.  Consider
  using the flag -Thost=x64 when running cmake.

Selecting Windows SDK version  to target Windows 10.0.17134.
The C compiler identification is MSVC 19.0.23026.0
The CXX compiler identification is MSVC 19.0.23026.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED
Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED - Failed
Performing Test GCC_OPENMP_SUPPORT
Performing Test GCC_OPENMP_SUPPORT - Failed
Performing Test MSVC_OPENMP_SUPPORT
Performing Test MSVC_OPENMP_SUPPORT - Success
Found PythonInterp: D:/Anaconda3/envs/tensorflow/python.exe (found version "3.5.4") 
Found PythonLibs: D:/Anaconda3/envs/tensorflow/libs/python35.lib (found version "3.5.4") 
Found SWIG: D:/zbl_back/code/swigwin-3.0.12/swig.exe (found version "3.0.12") 
CMake Error at tf_python.cmake:813 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:541 (include)

CMake Error at tf_python.cmake:814 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:541 (include)

CMake Error at tf_python.cmake:815 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:541 (include)

if I use tensorflow_BUILD_PYTHON_BINDINGS=OFF, this error will not happen.

**Comment by harshini-gadige** [comment]
@skye  PTAL

**Comment by skye** [comment]
We now encourage Windows users to build via bazel instead of CMake. See https://www.tensorflow.org/install/source_windows.

I'll mark this contributions welcome for now in case anyone else has a solution though.

**Comment by Prakash19921206** [comment]
Facing same issue with cmake... any update on this?
Thanks & Regards

**Comment by zhenngbolun** [comment]
they advised me to use bazel instead to cmake

**Comment by chaoyueziji** [comment]
I also face the same issue

**Comment by tilakrayal** [comment]
@zhenngbolun,
We can install the tensorflow on Windows using this official document https://www.tensorflow.org/install/source_windows
And Build TensorFlow Lite with CMake on Windows is still available.



Option Name  | Windows
-- | --
TFLITE_ENABLE_RUY | OFF
TFLITE_ENABLE_NNAPI |  N/A
TFLITE_ENABLE_GPU | N/A
TFLITE_ENABLE_XNNPACK | ON
TFLITE_ENABLE_MMAP |N/A

Please take a look for the reference.
https://www.tensorflow.org/lite/guide/build_cmake
https://www.tensorflow.org/lite/guide/build_cmake_arm

Thank you!
