### ISSUE TITLE
Will Python 3.7 support come soon?

### ISSUE THREAD

**Issue by sadatnfs** [tensorflow/tensorflow#23478]
Will Tensorflow support be extended to Python 3.7 anytime in the near future? Given that Miniconda has upgraded their default Python to 3.7,  I imagine there'd be higher demand to install TF on Python 3.7.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian Stretch
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: Master branch
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source): 8.2.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Comment by alanpurple** [comment]
this week, with 1.13.0rc0 ( as far as I know, not so sure )

**Comment by sadatnfs** [comment]
Thanks @alanpurple ! I build TF from source with a bunch of C flags in my Docker so I'll be happy to report to whether/if things break during the build or not!

**Comment by harshini-gadige** [comment]
@sadatnfs  -  Please track #20517 for more updates. Thanks !

**Comment by jerrychong25** [comment]
[Tensorflow 1.13.1](https://github.com/tensorflow/tensorflow/releases/tag/v1.13.1) now supports Python 3.7.

**Comment by jcopps** [comment]
> [Tensorflow 1.13.1](https://github.com/tensorflow/tensorflow/releases/tag/v1.13.1) now supports Python 3.7.

I cannot find the package on this page:
https://www.tensorflow.org/install/pip?lang=python3?
