### ISSUE TITLE
how can i solve this issue on importing tensorflow in linux?

### ISSUE THREAD

**Issue by tlmnader** [tensorflow/tensorflow#23474]
>

****System information****
- OS Platform and Distribution: (Linux Ubuntu 18.04):
- M device (e.HP-proBook) .
- Tensor-flow installed by running on terminal 
pip3 install --upgrade tensorflow-gpu
- TensorFlow version:
- Python version:3.6.6
- Installed using pip.
 -I dont have a CUDA/cuDNN version but  Intelhaswall.
- GPU model :Intel® Haswell Mobile
-memory:7.7 Gi
**the problem is :** 
I cant install and using tensor flow or numpy for object detection algorithms.
I don't know how can i install virtualenv.
I run on terminal
$sudo apt install python-pip python3-pip      
$pip3 install --upgrade tensorflow 
the tensor flow already installed 
but ,,when i run 
$python3
and import tensorflow the error was 
![screenshot from 2018-11-03 09-05-52](https://user-images.githubusercontent.com/44716923/47949282-f708f980-df48-11e8-9032-98813b6a8767.png)

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

______________________________________________________________________

**Any other info / logs**
i dont want to use a black-screen !!! to type a command i want to clone a codes and running it from a GitHub,starting coding .. somone advice me to setup

**Comment by bjascob** [comment]
**tensorflow-gpu** is for computers with an NVidia GPU.  See https://www.tensorflow.org/install/pip.  Assuming you only have the Intel graphics adapter, you'll need to uninstall **tensorflow-gpu** and install **tensorflow**.  This will run on your CPU.  I don't believe there is formal OpenCL/Intel GPU acceleration support but you can google for info on this if you're curious.

**Comment by ymodak** [comment]
Did you try bjascob's suggestion?
You can follow the steps given below to create virtual environment:
virtualenv -p python3 venv-tf-new    
source venv-tf-new/bin/activate   
pip3 install tensorflow

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
