### ISSUE TITLE
AttributeError: 'Estimator' object has no attribute '_distribution'

### ISSUE THREAD

**Issue by rmrao** [tensorflow/tensorflow#23508]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.11
- Python version: 3.6
- CUDA/cuDNN version: 9.2/7.2.1
- GPU model and memory: TitanXp 12Gb

When I use an Estimator with a MirroredDistributionStrategy, I encounter the error "AttributeError: 'Estimator' object has no attribute '_distribution'". This seems to be tied to this [line](https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/python/estimator/estimator.py#L1330), which has `self._distribution.unwrap(per_device_hook)[0]`. I'm pretty sure this should be `self._train_distribution.unwrap(per_device_hook)[0]`.

The estimator is clearly never assigned a '_distribution' attribute (this is the only line on which its referenced) so I assume this is just a typo. Let me know if I'm missing something.

**Comment by nmerrill67** [comment]
Same problem on a fresh install from source from the master branch. I made that change and it works perfectly.

**Comment by harshini-gadige** [comment]
@rmrao  This should not be a problem with TF version 1.12. Have you tried with 1.12 ?

**Comment by harshini-gadige** [comment]
@yuefengz  Any inputs on this ?

**Comment by nmerrill67** [comment]
@harshini-gadige This was broken when I did it on the master branch a few days ago, which is v1.12.

**Comment by rmrao** [comment]
I haven’t tried with 1.12 although the reference to _distribution still exists in the source of 1.12, so not sure that would do anything. I can test later today

**Comment by yuefengz** [comment]
This bug has been fixed in the master. 1.12 does have this bug.

**Comment by harshini-gadige** [comment]
@rmrao  - This issue is fixed and please wait for the next release. Thanks !

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
