### ISSUE TITLE
there is no gen_image_ops.py file

### ISSUE THREAD

**Issue by summerrr** [tensorflow/tensorflow#23512]
from tensorflow.python.ops import gen_image_ops
I want to see the code about non_max_suppression,but it in gen_image_ops,but I don't find it ,so where is the file?

**Comment by ymodak** [comment]
You can find the non_max_suppression code [here : tensorflow/python/ops/image_ops_impl.py](https://github.com/tensorflow/tensorflow/blob/f43d458a318d4d97298710654f1692f6e8364f82/tensorflow/python/ops/image_ops_impl.py#L2067)

**Comment by sabhiram** [comment]
So, the `gen_*` files used in python are essentially the bridge between the C++ definition and the tf code invoked and interpreted from python land. 

I am fairly sure that you would end up generating those files if you did a full build of tensorflow. They are I believe, generated at build time and auto-generated. 

Here are some pointers that might be helpful:
C++ op registration: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/image_ops.cc#L714

C++ op definition:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/non_max_suppression_op.cc#L282

C++ op compute base function (probably what you want):
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/non_max_suppression_op.cc#L127

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
