### ISSUE TITLE
Kernel restarting when running hello world example within docker image

### ISSUE THREAD

**Issue by Bazmundi** [tensorflow/tensorflow#23519]
**System information**
- OS Platform and Distribution is debian 9 amd64:
- Intel based laptop:
- TensorFlow installed from (source or binary): docker image per [https://www.tensorflow.org/install/](https://www.tensorflow.org/install/ )
- TensorFlow version: latest per docker based instructions
- Python version: whatever docker image pulls down
- Installed using virtualenv? pip? conda?: docker image
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
First computation on 1_hello_tensorflow.ipynb causes kernel restart when it is run.  In fact, it appears any code cell that includes imports tensorflow causes kernel restart.  Straight python code cells, including those using other libraries such as numpy (but have not called tensorflow) run.

**Comment by harshini-gadige** [comment]
#9829

**Comment by Bazmundi** [comment]
Ignore @harshini-gadige who has not applied any critical thinking enquiry at all.  Why on earth we would want Microsoft style user help on any forum is beyond me ;)

With a little work, I discovered the version of tensorflow required a cpu instruction my poor old laptop does not have.  I was not running a gpu as I had not installed cuda toolkit (it isn't really tuned for Debian).  So the article @harshini-gadige pointed at was as unfortunately as relevant to the problem as the fact that peanuts are used in making dynamite LOL

I think then I get twice the kudos points, I get the ones @harshini-gadige would have got for erroneously closing the issue AND points for actually closing the issue.

The time limit on responses is otherwise a shoddy IT department's trick for claiming performance where there is none.

**Comment by kazzastic** [comment]
> Ignore @Harshini-Gadige who has not applied any critical thinking enquiry at all. Why on earth we would want Microsoft style user help on any forum is beyond me ;)
> 
> With a little work, I discovered the version of tensorflow required a cpu instruction my poor old laptop does not have. I was not running a gpu as I had not installed cuda toolkit (it isn't really tuned for Debian). So the article @Harshini-Gadige pointed at was as unfortunately as relevant to the problem as the fact that peanuts are used in making dynamite LOL
> 
> I think then I get twice the kudos points, I get the ones @Harshini-Gadige would have got for erroneously closing the issue AND points for actually closing the issue.
> 
> The time limit on responses is otherwise a shoddy IT department's trick for claiming performance where there is none.

Can you please be more precise, how did you solve the issue?
