### ISSUE TITLE
Install from pip, run test and results in "illegal instruction"

### ISSUE THREAD

**Issue by Bazmundi** [tensorflow/tensorflow#23520]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9 AMD 64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Intel Laptop
- TensorFlow installed from (source or binary): pip per [https://www.tensorflow.org/install/pip](https://www.tensorflow.org/install/pip)
- TensorFlow version: 1.11.0
- Python version: 3.5.3
- Installed using virtualenv? pip? conda?: venv per [https://www.tensorflow.org/install/pip](https://www.tensorflow.org/install/pip) 
- Bazel version (if compiling from source):  N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

- set up venv and activate
- pip install tensorflow per [https://www.tensorflow.org/install/pip](https://www.tensorflow.org/install/pip)
- verify install per [https://www.tensorflow.org/install/pip](https://www.tensorflow.org/install/pip)
- import of tensorflow causes "illegal instruction" raised.

**Comment by ymodak** [comment]
I suspect that your CPU doesn't support [AVX instructions](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX) which is a requirement for installing TensorFlow 1.6 and above.

**Comment by Bazmundi** [comment]
Hmm.  I did say AMD64 but that was a furphy.

The laptop is acutally an x64 being an intel i5 which (apparently) has AVX
according to good old wikipedia.

BUT if I look I have a i5 460M chip, which intel tells me has Intel®
SSE4.1, Intel® SSE4.2 extensions.  I am still trying to get my head around
it but yes, if AVX is separated to SSE4.1 and 4.2 then my playing with
tensorflow is kaput.

It the lack of AVX would certainly account for both the docker and pip
install attempts failing.

Thanks ymodak, I will delete my install of tensorflow and look at other
frameworks.

**Comment by Bazmundi** [comment]
In fact, if I run cat /proc/cpuinfo and look at flags there is no avx for
certain.

**Comment by ppwwyyxx** [comment]
Tensorflow 1.6 and above __supports__ CPUs without avx. It is the official release binary (the one you download from pip) that does not support CPUs without avx. To use Tensorflow on old CPUs you'll need to build a binary on your own.

**Comment by Uradamus** [comment]
I was running into this as well. I'm using an old Phenom II CPU. Bit annoying there isn't a way to get a version through pip without the AVX requirement. I personally have no direct use for this project, but a program I was trying to test out depends on it. I'll probably just give up on it, as this is more hassle than it's worth, already wasted way too much time this past week leading up to the discovery that this was the problem all along.

**Comment by Bazmundi** [comment]
Yep. Was only interested in getting a tensor setup going to start learning
about it. Other options out there.
