### ISSUE TITLE
Using tf.data.dataset for inference with high efficiency

### ISSUE THREAD

**Issue by wenmengzhou** [tensorflow/tensorflow#23523]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: master
- Doc Link:  https://www.tensorflow.org/guide/datasets

tf.data.dataset provide a high level api for data importing and preprocessing. It's convenient to be used in training process, however, it is unclear how to use them in the inference scenario.  We want to reuse the data preprocessing code  for inference which using the interface of tf.data.dataset. By google search and self experiment I found the following ways to use tf.data.dataset for inference:

```python
#using a placeholder
x = tf.placeholder(tf.float32, shape=[None,2])
dataset = tf.data.Dataset.from_tensor_slices(x)
data = np.random.sample((100,2))
iter = dataset.make_initializable_iterator() # create the iterator
el = iter.get_next()
with tf.Session() as sess:
    # feed the placeholder with data
    sess.run(iter.initializer, feed_dict={ x: data }) 
    print(sess.run(el)) # output [ 0.52374458  0.71968478]
```

But the way above will bring some cost, Specifically ,there are two main operations:
1.   we must run the function sess.run  one more time
2.   dataset object need be to initialize each time

 is it efficient to do in this way,  Or we need another way to use tf.data.dataset so that we can keep efficiency?

-------------------------------
Update:
using tf.contrib.data.get_single_element  or tf.data.experimental.get_single_element

**Comment by mrry** [comment]
Regarding your update, does using `tf.data.experimental.get_single_element()` work well for your case?

**Comment by wenmengzhou** [comment]
> Regarding your update, does using `tf.data.experimental.get_single_element()` work well for your case?

Yes

**Comment by mrry** [comment]
Great! In that case, I'll close this issue.
