### ISSUE TITLE
How to make output sequence length equal to the input sequence length in seq2seq model?

### ISSUE THREAD

**Issue by tachiang** [tensorflow/tensorflow#23547]
I am trying to formulate a resource mapping problem using seq2seq model where the input sequence length varies and the output sequence length must be equal to the input sequence length.
From the manual of seq2deq in tensorflow, it seems that the output sequence length is determined by the end token or the maximal time step. So how can I make output length exactly equal to input length when building the seq2seq model?

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
