### ISSUE TITLE
Can the ops in pb files be fully supported by android tensorflow  Mobile ?

### ISSUE THREAD

**Issue by hellotf** [tensorflow/tensorflow#23549]
It seems tensorflow mobile(android_tensorflow_lib) contains only part of the  core/kenerns files.
If it is not fully supported ,  can we know how many ops not supported in Tensorflow mobile？

**Comment by ymodak** [comment]
You can refer this [document](https://www.tensorflow.org/lite/tf_ops_compatibility) to know more about TF mobile supported ops.

**Comment by hellotf** [comment]
Are inference  ops on Tensorflow mobile （not tensorflow lite） the same with inference ops in a desktop environment?
Can all the tensorFlow model that's successfully working in a desktop environment also sucessfully working  on a mobile application with Tensorflow mobile?（not  with tensorflow lite）,

**Comment by jdduke** [comment]
> Can all the tensorFlow model that's successfully working in a desktop environment also sucessfully working on a mobile application with Tensorflow mobile?

Unfortunately, not always. TensorFlow Mobile only supports a subset of the desktop ops, kernels and types. At the moment, there's no way to know with 100% certainty a priori that your model will run with TensorFlow Mobile short of actually running it. As an example, take a look at the [Android ops listing](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/core/kernels/BUILD?rcl=221644777&l=5241).
