### ISSUE TITLE
compiled error when build android  TFLite Model Benchmark Tool

### ISSUE THREAD

**Issue by 1icas** [tensorflow/tensorflow#23541]
tensorflow version: 0.12
describle:
when i build the android  TFLite Model Benchmark Tool use the command: 
bazel build -c opt \
--config=android_arm \
--cxxopt='--std=c++11' \
tensorflow/lite/tools/benchmark:benchmark_model

some errors occurs:
no such package '@com_google_absl//absl/base': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/abseil/abseil-cpp/archive/f95179062eb65ce40895cc76f1398cce25394369.tar.gz, https://github.com/abseil/abseil-cpp/archive/f95179062eb65ce40895cc76f1398cce25394369.tar.gz] to /root/.cache/bazel/_bazel_root/2f52c1a17bc0577f4e941b98cd34b371/external/com_google_absl/f95179062eb65ce40895cc76f1398cce25394369.tar.gz: All mirrors are down: [Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext] and referenced by '//tensorflow/lite/kernels/internal:tensor_utils'

build aborted: no such package '@com_google_absl//absl/base': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/abseil/abseil-cpp/archive/f95179062eb65ce40895cc76f1398cce25394369.tar.gz, https://github.com/abseil/abseil-cpp/archive/f95179062eb65ce40895cc76f1398cce25394369.tar.gz] to /root/.cache/bazel/_bazel_root/2f52c1a17bc0577f4e941b98cd34b371/external/com_google_absl/f95179062eb65ce40895cc76f1398cce25394369.tar.gz: All mirrors are down: [Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext]

**Comment by 1icas** [comment]
@jdduke sorry. i can't access to the  https://mirror.bazel.build/github.com/abseil/abseil-cpp/archive/f95179062eb65ce40895cc76f1398cce25394369.tar.gz  from my device

**Comment by jdduke** [comment]
@gunan I'm not sure there's anything we can do if devs can't access mirrors for our dependencies? Do you have any suggestions?

**Comment by 1icas** [comment]
my mistake. sorry
