### ISSUE TITLE
Persistent Concat op bug with mkl dnn

### ISSUE THREAD

**Issue by coreyjadams** [tensorflow/tensorflow#23556]
This issue appears to be related to #17494 which was closed.  I am opening a new issue to return attention to this.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes, and I have produced a boiled down script that can reproduce the problem standalone 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux (RH family), running on Intel Xeon Phi (KNL)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary, from  intel's build: https://software.intel.com/en-us/articles/intel-optimization-for-tensorflow-installation-guide
- TensorFlow version (use command below): 1.11
- Python version: Observed in 3.5 and 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When using the concat operation with mkl_dnn, the operation fails if run after a convolution with the following error message:

```
tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at mkl_concat_op.cc:814 : Aborted: Operation received an exception:Status: 5, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:811
INFO:tensorflow:An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. Error: Operation received an exception:Status: 5, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:811
```

**Describe the expected behavior**

It should not fail to create a concat primitive descriptor

**Code to reproduce the issue**
Please see this gist with the bare minimum python script to reproduce this issue: https://gist.github.com/coreyjadams/35e89feb1fb191c2788792f6268448fc

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by agramesh1** [comment]
@coreyjadams  We fixed the concat descriptor and it has been merged to the master https://github.com/tensorflow/tensorflow/pull/22606  Let us know if this fixes the problem.

**Comment by gzmkl** [comment]
@coreyjadams I have verified with your test script.

**Comment by coreyjadams** [comment]
Sorry for some delay - our compute nodes were down most of last week and I couldn't do any testing.

I am trying to test this but I can not build the master branch of tensorflow - I get an error of `ModuleNotFoundError: No module named 'keras_preprocessing'`.  I have all of the packages suggested here (https://stackoverflow.com/questions/51771039/error-compiling-tensorflow-from-source-no-module-named-keras-applications/51774943#51774943)

Should I open an new issue about this keras_preprocessing issue? FWIW, the build command I am using is 
```
../bazel-0.18.1/output/bazel build --config=mkl -c opt --copt=-g --strip=never --copt='-Wl,rpath=/opt/gcc/7.3.0/snos' --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mavx512f --copt=-mavx512pf --copt=-mavx512cd --copt=-mavx512er --copt='-mtune=knl' --copt="-DEIGEN_USE_VML" --verbose_failures //tensorflow/tools/pip_package:build_pip_package
```

**Comment by coreyjadams** [comment]
Ok.  The build was a pain, but eventually I succeeded.  I can confirm that my test script runs successfully on a Xeon Phi KNL with mkl-dnn, so that's great!

I'm going to close this issue since the fix is working.
