### ISSUE TITLE
skflow example text_classification needs file text_datasets.py

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/tensorflow#2355]
### Environment info
Operating System:

0.8.0

pip version 0.8.0 installation using

sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl

does not install text_datasets.py needed to run several skflow examples using text_classification su as 

tensorflow/tensorflow/examples/skflow/text_classification.py

the location of text_datasets.py is at

tensorflow/tensorflow/contrib/learn/python/learn/datasets/text_datasets.py

See image below comparing the pip installed directory structure with the github structure.

![both](https://cloud.githubusercontent.com/assets/5605614/15260720/47deb1f6-190d-11e6-97cb-02d4ce859929.png)

**Comment by terrytangyuan** [comment]
Have you tried one of the nightly builds? https://github.com/tensorflow/tensorflow#installation

**Comment by hpssjellis** [comment]
sudo pip install --upgrade http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_CONTAINER_TYPE=CPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.8.0-cp27-none-linux_x86_64.whl


Does install the file text_datasets.py I will check tonight if the text_classification examples work.

P.S. I work from the github site at 

https://github.com/hpssjellis/forth-tensorflow.git

which installs skflow and lots of other stuff (R, iJupyter, tensorflow etc) onto cloud9.


Jeremy Ellis
Twitter @rocksetta

**Comment by hpssjellis** [comment]
Thanks Terry. The nightly build fixed the text_classification.py file. Fair bit of number crunching, took about 5 minutes on cloud 9. I think all the text_ ...py files will work now.

P.S.
 All my broken skflow files are in this folder at the moment

https://github.com/hpssjellis/forth-tensorflow/tree/master/skflow-examples/broken

I will move them out of the folder after I test them.

**Comment by terrytangyuan** [comment]
Great. Please close this issue and submit new one if you encounter new problems.

**Comment by hpssjellis** [comment]
Thank you
