### ISSUE TITLE
if i set the inputshape with (None, None, featdim),how can I split the input by second dimention(axis=1)?

### ISSUE THREAD

**Issue by wangyunxiaa** [tensorflow/tensorflow#23552]
I want to have a dynamic input in my net, so, I set the input with 2 unknown dim, (1:batch, 2:sequencelength, 3:feature dims),and I defined another variable to specify the real shape of input in forwarding.
i have a test as followings:

    a = tf.placeholder(tf.float32, shape=[None, None, 40], name = "tensor_a") 
    b = tf.placeholder(tf.int32, shape=[2], name = "tensor_b")  # b[0] indicate the sequence length

    split_tensor_a = split_a(a, b)
    sess = tf.Session()

    array_a = np.logspace(1.0, 2.0, num = 120).reshape(1,3,40)
    array_b = np.array([3, 40])
    feed_dict = {a: array_a, b: array_b}
    split_b_value = sess.run(split_tensor_a, feed_dict = feed_dict)

and the py_func is:

    def split_a(tensor_a, tensor_b):
        sp_tensor =tf.py_func(_split_a, [tensor_a, tensor_b], tf.float32, "split")
        return sp_tensor

    def _split_a(a, b):
        tensor_tup = ()
        newsp_a = np.reshape(a, (-1, b[0], a.shape[-1]))
        for n in range(b[0]):
            tensor_tup = tensor_tup + (newsp_a[:, n, :],)
        print(tensor_tup)
        return tensor_tup

In _split_a I can get the value of tensor_tup, but when I run the sess, I got an error:
`InvalidArgumentError (see above for traceback): pyfunc_0 returns 3 values, but expects to see 1 values.
	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT, DT_INT32], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_tensor_a_0_0, _arg_tensor_b_0_1)]]
`
I want to know how to split the unknown dim of tensor?
If the net has 2 unknown dim,how to deal with the input data by one timestep?
The net has cnn layer and lstm layer, I donot want to change the input shape to (-1, featdim) in cnn layer, but it can only do forward by one time step,  the follwing lstm layer must have shape of (batch, numstep, featdim), so, what should I do ?
Can anyone help me?
Thanks~

**Comment by skye** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
