### ISSUE TITLE
After Tflite toco, conv2d layer becomes depthwiseconv2d.

### ISSUE THREAD

**Issue by ZJPUBG** [tensorflow/tensorflow#23563]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No.
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.10.0
- Python version: 3.6.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: on CPU
- GPU model and memory: on CPU

**Describe the current behavior**
I'm using tensorflow speech_command example's tiny_conv model [from here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/speech_commands). I've trained it and froze it (with quantization set to true) following [the official tutorial](https://www.tensorflow.org/tutorials/sequences/audio_recognition). 
The model itself is simple: one conv2d layer and one fully connected layer.
Now, I send the froze .pb file to tensorflow lite. I can successfully get the .tflite file. However, when I check the model, the original tiny_conv model's conv2d layer becomes a depthwiseconv2d layer.( I have tried several toco converts on other models, they do not have this behavior. ) I'm wondering how could this happen? I have the .pb model shown below, followed by the .tflite model:
![freeze](https://user-images.githubusercontent.com/31113955/48089764-10fd4300-e1ba-11e8-952c-3c25c854103e.JPG)
![tflite](https://user-images.githubusercontent.com/31113955/48089771-165a8d80-e1ba-11e8-9558-2986b76dd9f8.JPG)
As you can see, the conv2d layer becomes depthwiseconv2d.

**Describe the expected behavior**
The expected behavior is after toco, the .tflite still has one conv2d layer and one fully connected layer.

**Code to reproduce the issue**
After training and freezing, in toco, I have following code:
`graph_def_file = "my_frozen.pb"     //This is the .pb file.
input_arrays = ["Reshape_1"]        //This is the name of the input node
output_arrays = ["labels_softmax"]  //This is the name of the ouput node

//This is the main code to call toco
converter = tf.contrib.lite.TocoConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
//Since fake quantization during training, we quantize the graph during converting
converter.inference_type = tf.contrib.lite.constants.QUANTIZED_UINT8
input_arrays = converter.get_input_arrays()
converter.quantized_input_stats = {input_arrays[0] : (0., 2.)}  //mean, std_dev [from this tensorflow tutorial](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/micro_speech)
tflite_model = converter.convert()
open("tiny_conv.tflite", "wb").write(tflite_model)   //The resulting .tflite file.`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ZJPUBG** [comment]
Just in case it's not an issue, I have the same question asked on [stackoverflow](https://stackoverflow.com/questions/53179823/after-tflite-toco-conv2d-layer-becomes-depthwiseconv2d) If you guys know the answer, you can also answer there. Thanks!

**Comment by kairess** [comment]
Anyone solve this issue?

**Comment by akssieg** [comment]
I am facing the similar issue, My model has many convolutional layers and while converting my tensorflow model to .tflite format the TFLiteConverter changes the first convolutional layer into depthwise convolutional layer. Is there any alternative or a way to revert the changes?

**Comment by zj19921221** [comment]
> Anyone solve this issue?

have you ever solve this issue? I met it  but the harsdware did not surpport paramter 'depth multiplier'
