### ISSUE TITLE
TOCO Runtime error: Check failed: array_copy_size[0] != 0

### ISSUE THREAD

**Issue by kamwoh** [tensorflow/tensorflow#23576]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.11
- Python version: 3.6
- Bazel version (if compiling from source): 0.15
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9
- GPU model and memory: Titan XP

Convert frozen graph pb file to tflite, but failed due to some low level problem.

** Error Message **

RuntimeError: TOCO failed see console for info.
b'2018-11-07 13:26:38.105273: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 283 operators, 446 arrays (0 quantized)
2018-11-07 13:26:38.111622: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 283 operators, 446 arrays (0 quantized)
2018-11-07 13:26:38.431863: F tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_concatenation.cc:53] Check failed: array_copy_size[0] != 0 (0 vs. 0)
Aborted (core dumped)'

I am not sure how this happens, I am following all tutorials to convert, the pb file can be read and run. However I am failed to convert pb to tflite.

**Comment by ymodak** [comment]
Can you please point me to the tutorial you are trying?

**Comment by kamwoh** [comment]
I debug my code one line by one line by checking which tensor have error output, then i found out this

```
# conf_data is [1, num_priors, 2] -> [1, 42082, 2]
conf_preds = tf.reshape(conf_data, (num_priors, self.num_classes)) # -> [42082, 2]
print(conf_preds)
conf_preds = tf.transpose(conf_preds, (1, 0)) -> [2, 42082]
print(conf_preds)
conf_preds = tf.nn.softmax(conf_preds, 0) 
return tf.identify(conf_preds, name='output')
# ...more codes...
```
then i get `Check failed: array_copy_size[0] != 0 (0 vs. 0)`

when i change axis of softmax to 1 `tf.nn.softmax(conf_preds, 1)` , then i get `Check failed: axis < input_shape.dimensions_count() (97288360 vs. 3)`

when i remove the softmax line, then i get `axis < input_shape.dimensions_count() (71013160 vs. 3)`

I don't really understand why removing softmax will have different dimensions_count (which output is `tf.transpose`)

when i remove the transpose line (which output is `tf.reshape`)

then tflite convert successful.

hope my information can help debugging.

code to reproduce the error

```
import tensorflow as tf
import numpy as np

class TestModel(object):
    def __init__(self):
        self.conv1 = tf.layers.Conv2D(64, 3, padding='same', activation='relu')  # 32, 32
        self.maxpool1 = tf.layers.MaxPooling2D(2, 2)  # 16, 16

        self.conv2 = tf.layers.Conv2D(64, 3, padding='same', activation='relu')  # 16, 16
        self.maxpool2 = tf.layers.MaxPooling2D(2, 2)  # 8, 8

        self.conv3 = tf.layers.Conv2D(64, 3, padding='same', activation='relu')  # 8, 8
        self.maxpool3 = tf.layers.MaxPooling2D(2, 2)  # 4, 4

        self.flatten = tf.layers.Flatten()
        self.fc1 = tf.layers.Dense(10)

    def __call__(self, input_placeholder):
        out = self.conv1(input_placeholder)
        out = self.maxpool1(out)
        out = self.conv2(out)
        out = self.maxpool2(out)
        out = self.conv3(out)
        out = self.maxpool3(out)
        out = self.flatten(out)
        out = self.fc1(out)
        out = tf.concat((out, out), 1)
        print(out)
        out = tf.reshape(out, (10, 2))
        print(out)
        out = tf.transpose(out, (1, 0))
        print(out)
        out = tf.nn.softmax(out, 0)
        print(out)
        out = tf.identity(out, name='output')
        return out


class TestRunner(object):
    def __init__(self):
        self.graph = tf.Graph()
        self.sess = tf.Session(graph=self.graph)

        with self.graph.as_default():
            with self.sess.as_default():
                self.model = TestModel()
                self.input_placeholder = tf.placeholder(tf.float32, (1, 32, 32, 3), name='input')
                self.output_node = self.model(self.input_placeholder)

                self.sess.run(tf.global_variables_initializer())

    def test_convert_tflite(self):
        print('loading from session')
        converter = tf.contrib.lite.TocoConverter.from_session(self.sess, [self.input_placeholder], [self.output_node])
        print('converting to tflite')
        tflite_model = converter.convert()
        # print(tflite_model)


    def test_run(self):
        inputs = np.random.randn(1, 32, 32, 3)
        outputs = self.sess.run(self.output_node, feed_dict={self.input_placeholder: inputs})
        print(outputs.shape)


if __name__ == '__main__':
    tr = TestRunner()
    tr.test_run()
    tr.test_convert_tflite()
```
output
```
RuntimeError: TOCO failed see console for info.
b'2018-11-08 17:12:34.536423: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 45 operators, 79 arrays (0 quantized)\n2018-11-08 17:12:34.536829: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 45 operators, 79 arrays (0 quantized)\n2018-11-08 17:12:34.537445: F tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_concatenation.cc:53] Check failed: array_copy_size[0] != 0 (0 vs. 0)\nAborted (core dumped)\n'
None
```

**Comment by kamwoh** [comment]
seems like softmax with axis input will cause the error

I try to put softmax before transpose, tflite convert without errors

```
    def __call__(self, input_placeholder):
        out = self.conv1(input_placeholder)
        out = self.maxpool1(out)
        out = self.conv2(out)
        out = self.maxpool2(out)
        out = self.conv3(out)
        out = self.maxpool3(out)
        out = self.flatten(out)
        out = self.fc1(out)
        out = tf.concat((out, out), 1)
        print(out)
        out = tf.reshape(out, (10, 2))
        print(out)
        out = tf.nn.softmax(out)
        print(out)
        out = tf.transpose(out, (1, 0))
        print(out)
        out = tf.identity(out, name='output')
        return out
```

**Comment by andrehentz** [comment]
Yes, most likely softmax is causing the issue. Please refer to: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tf_ops_compatibility.md

> "tf.nn.softmax - as long as tensors are 2D and axis is the last dimension"

Please reopen if that's not the cause.

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
