### ISSUE TITLE
How to reuse kernel weight with tf.keras.layers.Conv2D

### ISSUE THREAD

**Issue by ymcasky** [tensorflow/tensorflow#23572]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: win10
- **TensorFlow installed from (source or binary)**: conda
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: 3.5
- **CUDA/cuDNN version**: 9.0/7.0
- **GPU model and memory**: Titan XP, 12G

I want to reuse kernel weight in keras with tensorflow backend.

My code is as following :

```
from tensorflow.python.keras.layers import  Input
from tensorflow.python.keras import regularizers
def infer3(data_input, Reuse):
    with tf.variable_scope('Network', reuse=Reuse):
        inputs = Input(tensor = data_input)
        network = tf.keras.layers.Conv2D(kernel_size=3, strides=2, filters=64, padding='same',kernel_regularizer=regularizers.l2(1),
                    activation='linear', kernel_initializer="glorot_normal", name='conv1', bias_initializer='zeros')(inputs)

    return network

tf.reset_default_graph() 
input_tensor = tf.placeholder(tf.float32,shape=[BATCH_SIZE,img_H,img_W,1])
output_tensor = tf.placeholder(tf.float32,shape=[BATCH_SIZE,img_H,img_W,1]) 
in_training_mode = tf.placeholder(tf.bool)     


network = infer3(input_tensor,False)
network_test = infer3(input_tensor,True)
```

When I type " tf.trainable_variables() "

It show message:

```
[<tf.Variable 'Network/conv1/kernel:0' shape=(3, 3, 1, 64) dtype=float32>,
 <tf.Variable 'Network/conv1/bias:0' shape=(64,) dtype=float32>,
 <tf.Variable 'Network_1/conv1/kernel:0' shape=(3, 3, 1, 64) dtype=float32>,
 <tf.Variable 'Network_1/conv1/bias:0' shape=(64,) dtype=float32>]
```
How can I reuse kernel weight?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
