### ISSUE TITLE
How can I fix "adding visible gpu devises: 0"

### ISSUE THREAD

**Issue by No-zim** [tensorflow/tensorflow#23573]
Just fixed one problem and now it is refusing to acknowledge that I have a gpu or smth.
On top of that it is not doing anything. Any fixes?

Using Windows 10
Cuda 9
cuDNN 7
GPU - gtx 1080, 8gb
eGPU - razer core x
Python 3.5.3

Using TensorFlow backend.
2018-11-06 22:16:20.031851: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-11-06 22:16:20.718059: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:07:00.0
totalMemory: 8.00GiB freeMemory: 6.59GiB
2018-11-06 22:16:20.718927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0

Solutions tried: 
1. uninstall tensorflow-gpu
   install tensorflow-gpu

2.uninstall tensorflow-gpu
   uninstall protobuf
   install tensorflow-gpu
3. Repeat the previous two couple more times (got desperate)

**Comment by ymodak** [comment]
Its simply stating that it has found 1 available GPU. It is acknowledging the presence of your gpu.

**Comment by No-zim** [comment]
@ymodak Okay, just a quickie: is it okay when i'm running an application it uses 31% CPU and 21.5% GPU or does it just depend on application type (and pc decides which is more appropriate and utilizes one more?)

**Comment by No-zim** [comment]
Anyways, thanks for your help and quick responses @ymodak

**Comment by TomHJ** [comment]
i added below codes, this phenomenon seems disappeared, i do not know the reason 
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
