### ISSUE TITLE
Is it ok for C++ code to link with _pywrap_tensorflow_internal.so?

### ISSUE THREAD

**Issue by tianyapiaozi** [tensorflow/tensorflow#23582]
I have a Python module written in C++, in which tensorflow serving API is used to load saved model and inference. Unfortunately, some part of my Python application has to use tensorflow python module directly. Because there are some common symbols between libtensorflow_cc.so and _pywrap_tensorflow_internal.so, there will be CHECK failure if the Python module is linked with libtensorflow_cc.so. 
The only feasible option seems to link the Python module with _pywrap_tensorflow_internal.so. Is that OK?

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by powderluv** [comment]
@tianyapiaozi did you resolve this issue ? were you able to link to it ?
