### ISSUE TITLE
Getting Started variable name mismatch

### ISSUE THREAD

**Issue by jansichermann** [tensorflow/tensorflow#236]
In http://tensorflow.org/get_started/basic_usage.md#variables

the variable in the example is initialized as `var`, then subsequently referred to as `state`
leading to an obvious NameError:

```
Traceback (most recent call last):
  File "./variables.py", line 8, in <module>
    new_value = tf.add(state, one)
NameError: name 'state' is not defined
```

**Comment by vrv** [comment]
It's updated in our repo, but not on our website yet.  We're going to update the website to reflect the current state of the repo soon.

(We get this question a lot, has it been hard to search for in our existing issues list?)

**Comment by jansichermann** [comment]
apologies @vrv -- just found a previous issue.
