### ISSUE TITLE
tensorflow lite AllocateTensors() error after ResizeInputTensor of mobilenet ssd models

### ISSUE THREAD

**Issue by zjbaby** [tensorflow/tensorflow#23600]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:qualcom 801 platform
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.11
- Python version:
- Bazel version (if compiling from source):1.18
- GCC/Compiler version (if compiling from source):gcc 5.4
- CUDA/cuDNN version:NA
- GPU model and memory:NA

**Describe the current behavior**
I convert ssd_mobilenet_v1_0.75_quantize model to .tflite, I know the model's training input size is 300x300,  I want to use different input tensor size, such as 240x240, so I use the ResizeInputTensor() function,
**But I got an error in AllocateTensors():**
tensorflow/contrib/lite/kernels/reshape.cc:58 num_input_elements != num_output_elements (2700 != 4332)
Node number 36 (RESHAPE) failed to prepare.
Failed to allocate tensors!

How to fix it?

**Describe the expected behavior**
I want to change the input tensor size freely

**Code to reproduce the issue**
`

    std::vector<int> sizes = {1, 240, 240, 3};

    interpreter_->ResizeInputTensor(interpreter_->inputs()[0], sizes);

    if (interpreter_->AllocateTensors() != kTfLiteOk) {
        LOG(INFO) << "Failed to allocate tensors!" << "\n";
        return false;
}`

**Comment by andrehentz** [comment]
We have been tracking this issue internally. Meanwhile, aside from rescaling your input image, the only other workaround is to reconvert the model using --input_shapes=1,240,240,3

**Comment by zjbaby** [comment]
OK,I'll try it

**Comment by srjoglekar246** [comment]
@zjbaby , were you able to convert the model?

**Comment by tofulawrence** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by zjd1988** [comment]
Hi @andrehentz 
when will you fix this?

**Comment by zjbaby** [comment]
@srjoglekar246 @zjd1988 
sorry, I haven't fix it

**Comment by IvyGongoogle** [comment]
meet the same error. have you solved it @srjoglekar246 @zjd1988 @zjbaby

**Comment by srjoglekar246** [comment]
@IvyGongoogle @zjbaby @zjd1988 Apologies for the late response on this. AFAIK, MobileNet SSD has a fixed architecture that only supports 300x300 images. As a result, its not possible to resize inputs for this graph. Your best bet would be to central-crop the image to a 1:1 ratio, and then resize it (maybe with bilinear interpolation). C++ code for this is [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/evaluation/stages/image_preprocessing_stage.cc#L44)

**Comment by IvyGongoogle** [comment]
@srjoglekar246 I find the `sizes` must be `{1, 300, 300, 3}` which is the same input size of ssd tflite model, and then `interpreter_->ResizeInputTensor(interpreter_->inputs()[0], sizes)` works.  But you said `1:1 ratio` is ok?

**Comment by srjoglekar246** [comment]
You would need to crop 1:1 AND resize to (300, 300) :-)
