### ISSUE TITLE
Segmentation Fault on `help(tf.RunMetadata)`

### ISSUE THREAD

**Issue by Salompas** [tensorflow/tensorflow#23607]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave 10.14
- TensorFlow installed from (source or binary): `pip install tensorflow`
- TensorFlow version (use command below): v1.11.0-rc2-4-gc19e29306c 1.11.0
- Python version: 3.6.7

**Describe the current behavior**
`Segmentation fault: 11` and Python crashes.
**Describe the expected behavior**
Print the documentation describing `tf.RunMetadata`.
**Code to reproduce the issue**
```
import tensorflow as tf
help(tf.RunMetadata)
```

**Comment by lucasfariaslf** [comment]
I justed tried it and got the same behavior.

* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 v. 1803
* TensorFlow installed from (source or binary): pip install tensorflow
* TensorFlow version (use command below): v1.8.0-0-g93bc2e2072' 1.8.0
* Python version: 3.6.5

**Comment by ymodak** [comment]
It doesn't look like an issue on TF ends. Please refer this link which addresses [similar behavior] (https://stackoverflow.com/questions/19531969/segmentation-fault-11-in-os-x)

**Comment by lucasfariaslf** [comment]
@ymodak you might be right, though the bug in that link seemed to be OS related. Using `faulthandler` i got:

```
$ python3 -X faulthandler
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> help(tf.RunMetadata)
Fatal Python error: Segmentation fault

Current thread 0x00007f1d87090700 (most recent call first):
  File "/usr/lib/python3.5/inspect.py", line 397 in classify_class_attrs
  File "/usr/lib/python3.5/pydoc.py", line 210 in classify_class_attrs
  File "/usr/lib/python3.5/pydoc.py", line 1276 in docclass
  File "/usr/lib/python3.5/pydoc.py", line 375 in document
  File "/usr/lib/python3.5/pydoc.py", line 1632 in render_doc
  File "/usr/lib/python3.5/pydoc.py", line 1639 in doc
  File "/usr/lib/python3.5/pydoc.py", line 1905 in help
  File "/usr/lib/python3.5/pydoc.py", line 1852 in __call__
  File "/usr/lib/python3.5/_sitebuiltins.py", line 103 in __call__
  File "<stdin>", line 1 in <module>
Segmentation fault (core dumped)
```

**Comment by spitis** [comment]
I am getting this as well, on two separate machines (one Ubuntu 16.04, other Ubuntu 18.04). Also occurs when either run_options or metadata is passed to a tf.Session.run call (e.g., cloning the stable-baselines and running the tests results in core dumped). 

_Separately_, also with the stable-baselines repo, I'm getting an unrelated core dumped when using Tensorflow 1.11.0 or 1.12.0, but not when using 1.10.0. I don't know how to debug this, so am just using 1.10.0 for now.

**Comment by ymodak** [comment]
Closing this issue since its not a TF related bug. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by spitis** [comment]
3 different users reported it for Windows, Mac, and Linux OSes. It's almost definitely a TF-related bug?

**Comment by xjzhou** [comment]
I justed tried it and got the same behavior.

OS: Ubuntu 16.04
TensorFlow installed from: pip install tensorflow
TensorFlow version: 1.12.0
Python version: 3.6.6

**Comment by ymodak** [comment]
@av8ramit  Can you please take a look? Thanks!

**Comment by mikolajolszewski** [comment]
Same still here on the official Amazon Deep Learning AMI.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Deep Learning AMI (Amazon Linux) Version 18.0
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): 1.12
- Python version: 3.6.5

**Comment by sushreebarsa** [comment]
@Salompas Is this still an issue ? We see that you are using old version of tensorflow  1.x which is not actively supported, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors using TF v2, we will get you the right help . Thanks!
