### ISSUE TITLE
Is tensorflow supported in python 2.7?

### ISSUE THREAD

**Issue by PabloDIGITS** [tensorflow/tensorflow#23603]
**System information**
- OS Platform and Distribution: **Linux Ubuntu 16.04**
- Python version: **2.7-64bits**
- Installed using pip: **pip version 9.0.3**
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: 9.1

**Describe the problem**
Hi:
Im trying to install tensorflow with pip with this command:
`pip install tensorflow-gpu`
and the output says:
`Collecting tensorflow-gpu
  Could not find a version that satisfies the requirement tensorflow-gpu (from versions: )
No matching distribution found for tensorflow-gpu
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

Is my python version compatible with tensorflow? I see that are instructions here [https://www.tensorflow.org/install/pip?lang=python2](url) to install tensorflow for python 2.7 but i have the same result.
I want to use Python 2.7 because the other modules I need for my scripts are installed in python 2.7. I have seen in other posts and issues that tensorflow is not compatible with python 2.7, is that true? How can I solve this? Should I try to install the other modules in python 3.5.2?
Thanks for help.

**Comment by PINTO0309** [comment]
@PabloDIGITS 
What about trying the command below?
```
$ sudo pip2 install pip --upgrade
$ sudo -H pip2 install tensorflow-gpu==1.11.0
or
$ sudo -H pip2 install tensorflow-gpu==1.12.0
```

**Comment by PabloDIGITS** [comment]
@PINTO0309 
It give me the same output. But I didnt upgrade pip, the last time I did it it gave me the error 
`Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main`

And i had to downgrade to the 9.0.3 version to work again. Do you think its a pip problem and not an incompatibilty with the python version?

**Comment by PINTO0309** [comment]
@PabloDIGITS
Maybe it is.
What about trying the command below?
```
$ which python2
$ wget https://bootstrap.pypa.io/get-pip.py
$ sudo python2 get-pip.py
```
If you do not do this please try asking with Stackoverflow.
I think that it is better to tell something about the hardware.

**Comment by PabloDIGITS** [comment]
@PINTO0309 
`$ which python2` gives me:
`$ /usr/bin/python2`
The last 2 commands seems to install pip 18.1, and I can execute pip list/freeze without any problem so my pip problem looks like resolved. Thanks for that help.
But the tensorflow problem is still there. I'm going to ask in Stackoveflow and see what happends.

**Comment by PINTO0309** [comment]
@PabloDIGITS 
Although it may have already been settled, I will contact you in case.
If unnecessary information, please ignore below.
If the device you are using is "TX2", you can install Tensorflow1.9 with .whl at the following URL.

**Python2.7**
http://developer.download.nvidia.com/compute/redist/jp33/tensorflow-gpu/tensorflow_gpu-1.9.0+nv18.8-cp27-cp27mu-linux_aarch64.whl
```
$ sudo -E pip2 install tensorflow-gpu/tensorflow_gpu-1.9.0+nv18.8-cp27-cp27mu-linux_aarch64.whl
```

**Python3.5**
http://developer.download.nvidia.com/compute/redist/jp33/tensorflow-gpu/tensorflow_gpu-1.9.0+nv18.8-cp35-cp35m-linux_aarch64.whl
```
$ sudo -E pip3 install tensorflow-gpu/tensorflow_gpu-1.9.0+nv18.8-cp35-cp35m-linux_aarch64.whl
```

**Comment by PabloDIGITS** [comment]
Ok, now it seems installed. I did pip list and tensorflow-gpu shows in the list. The problem was about the arch right? Im using a Jetson TX2.
Now I have 2 questions:
1. What is the -E arg does?
2.The fact that I use sudo (without sudo gives my an error of permissions) for installing will affect to acces the library with a script executed without sudo permissions or that other modules installed without sudo can acces to tensoflow?

Thank you for the help.

**Comment by PINTO0309** [comment]
@PabloDIGITS 
>The problem was about the arch right?

Yes. That's right.

>-- What is the -E arg does?

The "-E" option inherits environment variables.

>for installing will affect to acces the library with a script executed without sudo permissions

>for installing will affect to acces the library with a script executed without sudo permissions
>that other modules installed without sudo can acces to tensoflow?

Use "sudo" only during installation.
The only caveat is that it will not work unless cuda 9.0 is installed with Jet Pack.
I failed because I introduced Jet Pack 3.1 + cuda 8.0.

**Comment by PabloDIGITS** [comment]
@PINTO0309 
Thanks for the response. I did `import tensorflow` and `import clodsa` (my custom library for augmented data that needs tensorflow and doesnt show any error). I will see if I can use the library without any error.
Thanks again.

PD: I have CUDA 9.1 I hope that difference dont cause me any error.

**Comment by hnustxyxm** [comment]
> @PabloDIGITS
> Although it may have already been settled, I will contact you in case.
> If unnecessary information, please ignore below.
> If the device you are using is "TX2", you can install Tensorflow1.9 with .whl at the following URL.
> 
> **Python2.7**
> http://developer.download.nvidia.com/compute/redist/jp33/tensorflow-gpu/tensorflow_gpu-1.9.0+nv18.8-cp27-cp27mu-linux_aarch64.whl
> 
> ```
> $ sudo -E pip2 install tensorflow-gpu/tensorflow_gpu-1.9.0+nv18.8-cp27-cp27mu-linux_aarch64.whl
> ```
> **Python3.5**
> http://developer.download.nvidia.com/compute/redist/jp33/tensorflow-gpu/tensorflow_gpu-1.9.0+nv18.8-cp35-cp35m-linux_aarch64.whl
> 
> ```
> $ sudo -E pip3 install tensorflow-gpu/tensorflow_gpu-1.9.0+nv18.8-cp35-cp35m-linux_aarch64.whl
> ```

Hi，Do you have a 2.7 version of the TensorFlow installation package for Windows operating system? I can't find it.
