### ISSUE TITLE
ERROR: Config value opt is not defined in any .rc file

### ISSUE THREAD

**Issue by 786694836** [tensorflow/tensorflow#23613]
I wanna change .pb file to tflite file , but I failed.

I use the follow commed.

bazel run --config=opt tensorflow/contrib/lite/toco:toco -- \
--input_file=$OUTPUT_DIR/tflite_graph.pb \
--output_file=$OUTPUT_DIR/detect.tflite \
--input_shapes=1,300,300,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 \
--std_values=128 \
--change_concat_input_ranges=false \
--allow_custom_ops

> 
**and it come out the error below:**

WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/abb/tensorflow/tools/bazel.rc
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
ERROR: Config value opt is not defined in any .rc file

So who can help me to solve this issue?

**Comment by mbartosi** [comment]
Do as the warning says:

The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/abb/tensorflow/tools/bazel.rc

add:
import /home/abb/tensorflow/tools/bazel.rc

to .bazelrc file.

**Comment by ymodak** [comment]
@786694836 Is this still an issue? Did you try?

> Do as the warning says:
> 
> The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
> /home/abb/tensorflow/tools/bazel.rc
> 
> add:
> import /home/abb/tensorflow/tools/bazel.rc
> 
> to .bazelrc file.

**Comment by i-chaochen** [comment]
Same issue here.

I added 
import /home/username/tensorflow/tools/bazel.rc

in my  /home/username/tensorflow/tools/bazel.rc, but it doesn't change anything.

**Comment by andrehentz** [comment]
Option 1: add 'import /home/username/tensorflow/tools/bazel.rc' to /home/username/.bazelrc

Option 2: instead of --config=opt, use -c opt

Do any of those work for you?

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by kmaci3k** [comment]
Option 2: instead of --config=opt, use -c opt can work for me (based on tensorflow 1.12)

**Comment by jsonwang** [comment]
please help me , i can't find the bazel.rc file in tensorflow root path, where i can get it ?

**Comment by Keyrainn** [comment]
Unable to run Option2. theres an error. 

```
INFO: Writing tracer profile to 'C:/users/kirin/_bazel_kirin/rtshffit/command.profile.gz'
ERROR: Skipping 'tensorflow/lite/toco:toco': no such package 'research/object_detection/tensorflow/lite/toco': BUILD file not found in any of the following directories.
 - C:/tensorflow1/models/research/object_detection/tensorflow/lite/toco
WARNING: Target pattern parsing failed.
ERROR: no such package 'research/object_detection/tensorflow/lite/toco': BUILD file not found in any of the following directories.
 - C:/tensorflow1/models/research/object_detection/tensorflow/lite/toco
INFO: Elapsed time: 0.515s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by alexatinvert** [comment]
For me the solution was to execute the command from the tensorflow floder, i.e. /home/username/tensorflow/tensorflow/

This folder contains workspace.bzl, which I believe contains the config values

**Comment by aaron-michaux** [comment]
This is a problem when building tagged release `v2.0.0` using `bazel-0.26.1-linux-x86_64`

I get:

```
 > test  -c opt --jobs 4 --config opt //tensorflow/tools/lib_package:libtensorflow_test
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=189
INFO: Reading rc options for 'test' from /home/amichaux/TMP/build-tensorflow/tensorflow_v2.0.0/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --config=v2
INFO: Reading rc options for 'test' from /home/amichaux/TMP/build-tensorflow/tensorflow_v2.0.0/.bazelrc:
  'test' options: --define open_source_build=true --config=v2
INFO: Found applicable config definition build:v2 in file /home/amichaux/TMP/build-tensorflow/tensorflow_v2.0.0/.bazelrc: --define=tf_api_version=2
INFO: Found applicable config definition test:v2 in file /home/amichaux/TMP/build-tensorflow/tensorflow_v2.0.0/.bazelrc: --test_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:v2 in file /home/amichaux/TMP/build-tensorflow/tensorflow_v2.0.0/.bazelrc: --define=tf_api_version=2
INFO: Found applicable config definition test:v2 in file /home/amichaux/TMP/build-tensorflow/tensorflow_v2.0.0/.bazelrc: --test_env=TF2_BEHAVIOR=1
ERROR: Config value opt is not defined in any .rc file
```

**Comment by vaibhavgupta-hike** [comment]
Both of the above solutions did not work for me.

The import command does not work, since there is no file 'bazel.rc' in the specified location, as has previously been mentioned by @jsonwang 

Using -c opt made noi differnce either

**Comment by nobodypengium** [comment]
> Unable to run Option2. theres an error.
> 
> ```
> INFO: Writing tracer profile to 'C:/users/kirin/_bazel_kirin/rtshffit/command.profile.gz'
> ERROR: Skipping 'tensorflow/lite/toco:toco': no such package 'research/object_detection/tensorflow/lite/toco': BUILD file not found in any of the following directories.
>  - C:/tensorflow1/models/research/object_detection/tensorflow/lite/toco
> WARNING: Target pattern parsing failed.
> ERROR: no such package 'research/object_detection/tensorflow/lite/toco': BUILD file not found in any of the following directories.
>  - C:/tensorflow1/models/research/object_detection/tensorflow/lite/toco
> INFO: Elapsed time: 0.515s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded)
> FAILED: Build did NOT complete successfully (0 packages loaded)
> ```

I have the same problem.

**Comment by omatai** [comment]
Option 2 is very confusing due to [this](https://stackoverflow.com/questions/46319386/whats-the-difference-between-c-opt-and-config-opt-when-building-tensorflow-f) - it seems they do COMPLETELY different things...

I got this issue on Windows when I looked at the .tf_configure.bazelrc file after generating it (python ./configure.py) and somehow accidentally deleted it straight after :-( Easy fix: configure again and just run the bazel build command :-)

**Comment by Petros626** [comment]
> 
> 
> Option 1: add 'import /home/username/tensorflow/tools/bazel.rc' to /home/username/.bazelrc
> 
> Option 2: instead of --config=opt, use -c opt
> 
> Do any of those work for you?

hey thank you for your answer, it seems that this works for some people, but in my case i have this issue:
![bazel](https://user-images.githubusercontent.com/62354721/135983141-b56f4695-1fa1-4e53-8a15-3dfbf4506f50.JPG)

**Comment by aspepper** [comment]
Option 2: instead of --config=opt, use -c opt can work for me(based on tf1.12) 

its works for me to Mac OS X Sonoma 14.0 (23A344), Apple Silicon M1.
