### ISSUE TITLE
Why only support tf.train.Int64List? In many case int32 can meet requirements. Int64 will expand the computation.

### ISSUE THREAD

**Issue by fightbob** [tensorflow/tensorflow#23614]
message Example {
 Features features = 1;
};

message Features{
 map<string,Feature> featrue = 1;
};

message Feature{
    oneof kind{
        BytesList bytes_list = 1;
        FloatList float_list = 2;
        Int64List int64_list = 3;
    }
};

Only support bytes_list , float_list, int64_list. Why not support int32_list?

**Comment by fightbob** [comment]
@harshini-gadige any advice? Thx.

**Comment by shoyer** [comment]
Protos use a variable width encoding for integers, so there’s really very little to gain from an int32 type for storing data on disk.

**Comment by fightbob** [comment]
> Protos use a variable width encoding for integers, so there’s really very little to gain from an int32 type for storing data on disk.

@shoyer  But input tensor with data type int64 read from tf.example is inefficient, it consumes more computing resource. In many case int32 meets requirements. Many users try to change input data type, they use tf.cast to convert int64 to int32 .

**Comment by fightbob** [comment]
> Protos use a variable width encoding for integers, so there’s really very little to gain from an int32 type for storing data on disk.

@shoyer But input tensor with data type int64  is inefficient, it consumes more computing resource when tf session train or predict model. In many case int32 meets requirements. Many users try to change input data type, they use tf.cast to convert int64 to int32 .

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
