### ISSUE TITLE
Tensor flow installation problem: import error

### ISSUE THREAD

**Issue by antonszilasi** [tensorflow/tensorflow#2362]
I am having the following issue when I try to install TensorFlow for Python 2.7 on mac OS. This seems to be an issue with Tensor flow's libraries, thank you for your help!

![screen shot 2016-05-14 at 3 11 14 pm](https://cloud.githubusercontent.com/assets/8773483/15266421/badcb0ec-19e7-11e6-9ad5-599c656cba59.png)

**Comment by mrry** [comment]
It looks like your version of `pip` is not installing things into the path that your version of `python` is expecting. Perhaps you have two versions of Python installed? What output do you get from `which pip` and `which python`? (These paths might give a clue....)

**Comment by antonszilasi** [comment]
Strangely I am getting this

![screen shot 2016-05-18 at 1 21 02 pm](https://cloud.githubusercontent.com/assets/8773483/15346446/a394568a-1cfb-11e6-9258-c374601d50b7.png)

**Comment by mrry** [comment]
Which version of OS X are you running? On closer inspection of your first screenshot, the error message is:

```
Symbol not found: ___sincos_stret
```

Looking [elsewhere](http://stackoverflow.com/questions/25926495/symbol-not-found-sincos-stret) suggests that this symbol is only available in OS X 10.9 and above.

**Comment by mrry** [comment]
Closing due to lack of response. Feel free to reopen if you're still having problems (although note that OS X 10.8 or earlier support is probably out of scope...).
