### ISSUE TITLE
how to merge different .ckpt files into a .pf file

### ISSUE THREAD

**Issue by Michael3444** [tensorflow/tensorflow#23626]
I had trained some  networks and saved them into  .ckpt file separately,  There is a connection between these networks, the output of the previous network is the input of the latter network, so here I want to merge these .ckpt files into a .pb file so I could deploy it very conveniently. But I didn't find the relevant tutorial. Had anyone done a similar job like that?

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
