### ISSUE TITLE
TensorFlow Keras Fit Bug Value Error: Dimension -3 must be >= 0

### ISSUE THREAD

**Issue by gmanrocks99** [tensorflow/tensorflow#23635]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
I have written custom code, albeit based off of code from TFLearn.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
This issue is untested on mobile devices.
- TensorFlow installed from (source or binary):
TensorFlow installed from binary.
- TensorFlow version (use command below):
TensorFlow Version: 1.11 
- Python version:
Python Version: 3.6.6
- Bazel version (if compiling from source):
Not Compiled from source
- GCC/Compiler version (if compiling from source):
Not Compiled from source
- CUDA/cuDNN version:
CUDA/cuDNN version 9.0
- GPU model and memory:
NVIDIA GeForce MX150, approx total memory 10097 MB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
When I run the following program, which is supposed to be able to differentiate between images of Cats and Dogs using a convolution model, the program gets stuck at the fit method. It is returning a Value Error: Dimension -3 must be >= 0. I believe all the information in the fit method is correct...

**Describe the expected behavior**
It should complete the training of the model. It has not yet been set up to save it.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
File is attached.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Here is the trace:

2018-11-09 11:45:48.096411: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "C:/Users/gman7/Documents/BIF/Tensor Flow/Programs/Java Examples/Cats vs Dogs/CvD.py", line 128, in <module>
    model.fit(X_train, Y_train, epochs=2, steps_per_epoch=500)
  File "C:\Users\gman7\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1509, in fit
    validation_split=validation_split)
  File "C:\Users\gman7\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 993, in _standardize_user_data
    class_weight, batch_size)
  File "C:\Users\gman7\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1029, in _standardize_weights
    self._set_inputs(x)
  File "C:\Users\gman7\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\checkpointable\base.py", line 426, in _method_wrapper
    method(self, *args, **kwargs)
  File "C:\Users\gman7\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1222, in _set_inputs
    self.build(input_shape=input_shape)
  File "C:\Users\gman7\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 224, in build
    shape = layer.compute_output_shape(shape)
  File "C:\Users\gman7\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 230, in compute_output_shape
    [self.filters])
  File "C:\Users\gman7\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 542, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "C:\Users\gman7\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 542, in <listcomp>
    self._dims = [as_dimension(d) for d in dims_iter]
  File "C:\Users\gman7\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 482, in as_dimension
    return Dimension(value)
  File "C:\Users\gman7\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 42, in __init__
    raise ValueError("Dimension %d must be >= 0" % self._value)
ValueError: Dimension -3 must be >= 0

Process finished with exit code 1

**Comment by gmanrocks99** [comment]
[CvD.zip](https://github.com/tensorflow/tensorflow/files/2567000/CvD.zip)

**Comment by omalleyt12** [comment]
Hi @gmanrocks99 can you provide a minimal example reproducing the issue and copy-paste the code as a comment on this thread?

**Comment by gmanrocks99** [comment]
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Dense, Dropout
from tensorflow.keras.optimizers import Adam

train_data = np.load('train_data.npy')
test_data = np.load('test_data.npy')

train = train_data[:-500]
test = train_data[-500:]

X_train = np.array([i[0] for i in train]).reshape(-1, 50, 50, 1)
Y_train = np.array([i[1] for i in train])

X_test = np.array([i[0] for i in test]).reshape(-1, 50, 50, 1)
Y_test = np.array([i[1] for i in test])

tf.reset_default_graph()
sess = tf.Session()

model = Sequential()

# layer1 = conv_2d, filters = 32, filter size = 5, activation = relu
model.add(Conv2D(filters=32, kernel_size=(5, 5), activation='relu', ))

# layer2 = max_pool_2d, kernels = 5, strides = 5
model.add(MaxPool2D(pool_size=(5, 5), strides=5))

# layer3 = conv_2d, filters = 64, filter size = 5, activation = relu
model.add(Conv2D(filters=64, kernel_size=(5, 5), activation='relu'))

# layer4 = max_pool_2d, kernels = 5, strides = 5
model.add(MaxPool2D(pool_size=(5, 5), strides=5))

# layer5 = conv_2d, filters = 128, filter size = 5, activation = relu
model.add(Conv2D(filters=128, kernel_size=(5, 5), activation='relu'))

# layer6 = max_pool_2d, kernels = 5, strides = 5
model.add(MaxPool2D(pool_size=(5, 5), strides=5))

# layer7 = conv_2d, filters = 64, filter size = 5, activation = relu
model.add(Conv2D(filters=64, kernel_size=(5, 5), activation='relu'))

# layer8 = max_pool_2d, kernels = 5, strides = 5
model.add(MaxPool2D(pool_size=(5, 5), strides=5))

# layer9 = conv_2d, filters = 32, filter size = 5, activation = relu
model.add(Conv2D(filters=32, kernel_size=(5, 5), activation='relu'))

# layer10 = max_pool_2d, kernels = 5, strides = 5
model.add(MaxPool2D(pool_size=(5, 5), strides=5))

# layer11 = fully_connected, units = 1024, activation = relu
model.add(Dense(units=1024, activation='relu'))

# layer12 = dropout, keep_probability = 0.8
model.add(Dropout(rate=0.8))

# layer13 = fully_connected, units = 2, activation = softmax
model.add(Dense(units=2, activation='softmax'))

# layer14 = regression, optimizer = adam, learning rate = LR, loss = categorical cross entropy
model.compile(optimizer=Adam(lr=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# epochs = 1, validation set = (X_test, Y_test), snapshot every 500, progressbar
model.fit(x=X_train, y=Y_train, epochs=1, validation_data=(X_test, Y_test), verbose=1)

**Comment by gmanrocks99** [comment]
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Dense, Dropout
from tensorflow.keras.optimizers import Adam

train_data = np.load('train_data.npy')
test_data = np.load('test_data.npy')

train = train_data[:-500]
test = train_data[-500:]

X_train = np.array([i[0] for i in train]).reshape(-1, 50, 50, 1)
Y_train = np.array([i[1] for i in train])

X_test = np.array([i[0] for i in test]).reshape(-1, 50, 50, 1)
Y_test = np.array([i[1] for i in test])

tf.reset_default_graph()
sess = tf.Session()

model = Sequential()

# layer1 = conv_2d, filters = 32, filter size = 5, activation = relu
model.add(Conv2D(filters=32, kernel_size=(5, 5), activation='relu', ))

# layer2 = max_pool_2d, kernels = 5, strides = 5
model.add(MaxPool2D(pool_size=(5, 5), strides=5))

# layer3 = conv_2d, filters = 64, filter size = 5, activation = relu
model.add(Conv2D(filters=64, kernel_size=(5, 5), activation='relu'))

# layer4 = max_pool_2d, kernels = 5, strides = 5
model.add(MaxPool2D(pool_size=(5, 5), strides=5))

# layer5 = conv_2d, filters = 128, filter size = 5, activation = relu
model.add(Conv2D(filters=128, kernel_size=(5, 5), activation='relu'))

# layer6 = max_pool_2d, kernels = 5, strides = 5
model.add(MaxPool2D(pool_size=(5, 5), strides=5))

# layer7 = conv_2d, filters = 64, filter size = 5, activation = relu
model.add(Conv2D(filters=64, kernel_size=(5, 5), activation='relu'))

# layer8 = max_pool_2d, kernels = 5, strides = 5
model.add(MaxPool2D(pool_size=(5, 5), strides=5))

# layer9 = conv_2d, filters = 32, filter size = 5, activation = relu
model.add(Conv2D(filters=32, kernel_size=(5, 5), activation='relu'))

# layer10 = max_pool_2d, kernels = 5, strides = 5
model.add(MaxPool2D(pool_size=(5, 5), strides=5))

# layer11 = fully_connected, units = 1024, activation = relu
model.add(Dense(units=1024, activation='relu'))

# layer12 = dropout, keep_probability = 0.8
model.add(Dropout(rate=0.8))

# layer13 = fully_connected, units = 2, activation = softmax
model.add(Dense(units=2, activation='softmax'))

# layer14 = regression, optimizer = adam, learning rate = LR, loss = categorical cross entropy
model.compile(optimizer=Adam(lr=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# epochs = 1, validation set = (X_test, Y_test), snapshot every 500, progressbar
model.fit(x=X_train, y=Y_train, epochs=1, validation_data=(X_test, Y_test), verbose=1)

**Comment by gmanrocks99** [comment]
@omalleyt12

**Comment by gmanrocks99** [comment]
Correction:
all
model.add(MaxPool2D(pool_size=(5, 5), strides=5))
replaced with
model.add(MaxPool2D(pool_size=(5, 5))

**Comment by gmanrocks99** [comment]
This works:
model.add(Conv2D(filters=64, kernel_size=(5, 5), activation='relu', ))
model.add(MaxPool2D(pool_size=(5, 5)))

model.add(Conv2D(filters=32, kernel_size=(5, 5), activation='relu', ))
model.add(MaxPool2D(pool_size=(5, 5)))

model.add(Dense(units=1024, activation='relu'))
model.add(Dropout(rate=0.8))
model.add(Dense(units=2, activation='softmax'))

model.compile(optimizer=Adam(lr=0.001), loss='categorical_crossentropy', metrics=['accuracy', 'ce'])
sess.run(tf.global_variables_initializer())
model.fit(x=X_train, y=Y_train, epochs=1, validation_data=(X_test, Y_test), verbose=1)

This does not:

model.add(Conv2D(filters=32, kernel_size=(5, 5), activation='relu', ))
model.add(MaxPool2D(pool_size=(5, 5)))

model.add(Conv2D(filters=64, kernel_size=(5, 5), activation='relu', ))
model.add(MaxPool2D(pool_size=(5, 5)))

model.add(Conv2D(filters=32, kernel_size=(5, 5), activation='relu', ))
model.add(MaxPool2D(pool_size=(5, 5)))

model.add(Dense(units=1024, activation='relu'))
model.add(Dropout(rate=0.8))
model.add(Dense(units=2, activation='softmax'))

model.compile(optimizer=Adam(lr=0.001), loss='categorical_crossentropy', metrics=['accuracy', 'ce'])
sess.run(tf.global_variables_initializer())
model.fit(x=X_train, y=Y_train, epochs=1, validation_data=(X_test, Y_test), verbose=1)

The latter, i added one more conv2d and one more maxpool2D which does not work, no matter the number of filters.

**Comment by gmanrocks99** [comment]
Problem solved: in tflearn padding is by default = 'same' while in keras, padding = 'valid' by default.
