### ISSUE TITLE
Incorrect masking in keras.backend.rnn

### ISSUE THREAD

**Issue by andhus** [tensorflow/tensorflow#23632]
**System information**
```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
('v1.12.0-rc0-2215-g6735dd4799', '1.13.0-dev20181109')
```

**Describe the current behavior**
For correct masking of `output` it is required that `output == states[0]` for  `keras.backend.rnn(..., unroll=False)`, not so with `unroll=True` or in latest version of [keras-team/keras](https://github.com/keras-team/keras). See [this line](https://github.com/tensorflow/tensorflow/blob/d703f64e452f49603a244978b13239ab7aac0168/tensorflow/python/keras/backend.py#L3496) for the reason.

**Describe the expected behavior**
As per this [PR](https://github.com/keras-team/keras/pull/11499) (and discussions in linked issues) it has been established that output should be independent of states. That is, it should _not_ be assumed that `output == states[0]` for `ouput, states = step_function(inputs, previous_states)` in the `keras.backend.rnn` implementation. For details see test below.

**Code to reproduce the issue**
See test below (basically same as [this test added keras-team/keras](https://github.com/keras-team/keras/pull/11499/files#diff-e942014d73bf67b47a3b55f7f7041797R829))

```python
import numpy as np
from tensorflow import keras

def test_rnn_output_and_state_masking_independent():
    num_samples = 2
    num_timesteps = 4
    state_and_io_size = 5
    mask_last_num_timesteps = 2  # for second sample only

    # a step function that just outputs inputs,
    # but increments states +1 per timestep
    def step_function(inputs, states):
        return inputs, [s + 1 for s in states]

    inputs_vals = np.random.random(
        (num_samples, num_timesteps, state_and_io_size))
    initial_state_vals = np.random.random((num_samples, state_and_io_size))
    # masking of two last timesteps for second sample only
    mask_vals = np.ones((num_samples, num_timesteps))
    mask_vals[1, -mask_last_num_timesteps:] = 0

    # outputs expected to be same as inputs for the first sample
    expected_outputs = inputs_vals.copy()
    # but for the second sample all outputs in masked region should be the same
    # as last output before masked region
    expected_outputs[1, -mask_last_num_timesteps:] = \
        expected_outputs[1, -(mask_last_num_timesteps + 1)]

    expected_state = initial_state_vals.copy()
    # first state should be incremented for every timestep (no masking)
    expected_state[0] += num_timesteps
    # second state should not be incremented for last two timesteps
    expected_state[1] += (num_timesteps - mask_last_num_timesteps)

    # verify same expected output for `unroll=true/false`
    inputs = keras.backend.variable(inputs_vals)
    initial_states = [keras.backend.variable(initial_state_vals)]
    mask = keras.backend.variable(mask_vals)
    for unroll in [True, False]:
        last_output, outputs, last_states = keras.backend.rnn(
            step_function,
            inputs,
            initial_states,
            mask=mask,
            unroll=unroll,
            input_length=num_timesteps if unroll else None)

        np.testing.assert_allclose(
            keras.backend.eval(outputs), expected_outputs,
            err_msg="Unexpected output for unroll={}".format(unroll))
        np.testing.assert_allclose(
            keras.backend.eval(last_states[0]), expected_state,
            err_msg="Unexpected state for unroll={}".format(unroll))
```
Gives:
```
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0
Unexpected output for unroll=False
(mismatch 25.0%)
 x: array([0.116687, 0.622734, 0.210443, 0.662715, 0.720813, 0.654062,
       0.936728, 0.451018, 0.471044, 0.560336, 0.133492, 0.228378,
       2.081284, 2.415464, 2.081284, 2.415464], dtype=float32)
 y: array([0.116687, 0.622734, 0.210443, 0.662715, 0.720813, 0.654062,
       0.936728, 0.451018, 0.471044, 0.560336, 0.133492, 0.228378,
       0.133492, 0.228378, 0.133492, 0.228378])
```
**Other info / logs**
There are a few further implications of current implementation addressed by the tests added to keras-team/keras [here](https://github.com/keras-team/keras/pull/11499/files#diff-e942014d73bf67b47a3b55f7f7041797R829))

**Comment by andhus** [comment]
I'm happy to adopt the fixes I made in keras-team/keras to here @fchollet

**Comment by andhus** [comment]
Hi @qlzh727 I see that a fix for this was added in https://github.com/tensorflow/tensorflow/commit/149886979acf87027a188c0851f0cbe41a30f275 So this should be closed?

Could you put me in the loop on the process of bringing features and fixes from keras-team/keras to tensorflow.keras? Do you want contributions for this? I think that there are still issues in current `rnn` implementation here (as in it will not pass all the tests added [here](https://github.com/keras-team/keras/pull/11499))

**Comment by qlzh727** [comment]
Hi @andhus, thanks for the notice. I think this should be closed since I applied same fix to the tf.keras backend.

Currently there is manual sync process to bring fix/updates from keras/keras to tf.keras, usually this happens every few weeks. In this case, since I was aware of the issue on keras side, I just directly applied the same fix on tf.keras, which avoid the long waiting for the sync process.

I will take a close look since u mentioned it might not passing all the tests u have in other PR, will update this issue soon.

**Comment by qlzh727** [comment]
The PR has been merged, mark this as fixed. Thanks @andhus  for the fix.
