### ISSUE TITLE
Calculation precision issue 

### ISSUE THREAD

**Issue by liuyanpunk** [tensorflow/tensorflow#23641]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows with Tensorflow Docker 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:no
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.12
- Python version:2.7
- Bazel version (if compiling from source):na
- GCC/Compiler version (if compiling from source):na
- CUDA/cuDNN version:9, 7.3.1
- GPU model and memory:2080,8G 

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
import tensorflow as tf

def compute_area(sides):
  a = sides[:,0]  # 5.0, 2.3
  b = sides[:,1]  # 3.0, 4.1
  c = sides[:,2]  # 7.1, 4.8
  
  s = (a + b + c) * 0.5   # (a + b) is a short-cut to tf.add(a, b)
  areasq = s * (s - a) * (s - b) * (s - c) # (a * b) is a short-cut to tf.multiply(a, b), not tf.matmul(a, b)
  return tf.sqrt(areasq)

with tf.Session() as sess:
  area = compute_area(tf.constant([
      [3.000000001, 4.0, 5.0],
    ],dtype='float64'))
  result = sess.run(area)
  print(result)  

[6.]

**Describe the expected behavior**
import numpy as np

s = (3.000000001 + 4 + 5) * 0.5
areasq = s * (s - 3.000000001) * (s - 4) * (s - 5)

print(np.sqrt(areasq))

6.000000001999999

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Attached as above 

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

N/A

**Comment by alextp** [comment]
I think this is a matter of print-time precision. If I subtract the tf result from the numpy result I get exactly zero:

```
import tensorflow as tf
import numpy as np
tf.enable_eager_execution()

def compute_area(sides):
  a = sides[:,0] # 5.0, 2.3
  b = sides[:,1] # 3.0, 4.1
  c = sides[:,2] # 7.1, 4.8

  s = (a + b + c) * 0.5 # (a + b) is a short-cut to tf.add(a, b)
  areasq = s * (s - a) * (s - b) * (s - c) # (a * b) is a short-cut to tf.multiply(a, b), not tf.matmul(a, b)
  return tf.sqrt(areasq)

a = compute_area(tf.constant([[3.000000001, 4.0, 5.0],],dtype='float64'))
s = (3.000000001 + 4 + 5) * 0.5
areasq = s * (s - 3.000000001) * (s - 4) * (s - 5)

dif = np.sqrt(areasq) - a.numpy()
dif == 0.
```
(prints array([ True]))
