### ISSUE TITLE
tf.contrib.image.transform lead to a ValueError in new releases of tensorflow

### ISSUE THREAD

**Issue by Goldesel23** [tensorflow/tensorflow#23654]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Manjaro 18.0
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): python-tensorflow-opt-cuda from manjaro repositories 
- TensorFlow version (use command below): 1.11
- Python version: 3.6/3.7
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.0.130-2 /   7.3.0-1
- GPU model and memory: 1080Ti 11GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

After the release that Allow a different output shape from the input in `tf.contrib.image.transform` code that applied this function stopped working with a value error. For exampleon previous versions, using eager execution this worked:

`image = tf.contrib.image.translate(image, random_translation, 'NEAREST') `

But after this change I get a `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`` on `tf.contrib.image.transform` on the condition of the line 273-275 of `tensorflow/tensorflow/contrib/image/python/ops/image_ops.py`, where this condition is triggered (caused by empty output shape call in tf.contrib.image.translate:

```
if output_shape is None:
      output_shape = tensor_util.constant_value(
          array_ops.shape(images)[1:3]) or array_ops.shape(images)[1:3]
```

**Describe the expected behavior**

If instead of `tf.contrib.image.transform` I run it with `output_shape` argument:

`random_transformations = tf.contrib.image.translations_to_projective_transforms(random_shifts)
images = tf.contrib.image.transform(image, random_transformations, 'NEAREST',                                       output_shape=tf.convert_to_tensor(images.numpy().shape[1:3], dtype=np.int32))`

everything goes as expected. So I guess that the issue in on passing output_shape=None in line 122-126 of `tensorflow/tensorflow/contrib/image/python/ops/image_ops.py:

```
def translate(images, translations, interpolation="NEAREST", name=None):
  """Translate image(s) by the passed vectors(s).
  Args:
    images: A tensor of shape (num_images, num_rows, num_columns, num_channels)
        (NHWC), (num_rows, num_columns, num_channels) (HWC), or
        (num_rows, num_columns) (HW). The rank must be statically known (the
        shape is not `TensorShape(None)`.
    translations: A vector representing [dx, dy] or (if images has rank 4)
        a matrix of length num_images, with a [dx, dy] vector for each image in
        the batch.
    interpolation: Interpolation mode. Supported values: "NEAREST", "BILINEAR".
    name: The name of the op.
  Returns:
    Image(s) with the same type and shape as `images`, translated by the given
        vector(s). Empty space due to the translation will be filled with zeros.
  Raises:
    TypeError: If `image` is an invalid type.
  """
  with ops.name_scope(name, "translate"):
    return transform(
        images,
        translations_to_projective_transforms(translations),
        interpolation=interpolation)

```

**Comment by yongtang** [comment]
Added PR #23658 for the fix.
