### ISSUE TITLE
pip install problem:SSLError

### ISSUE THREAD

**Issue by ayqh** [tensorflow/tensorflow#2365]
I encountered " SSLError: hostname 'storage.googleapis.com' doesn't match 'www.google.com' "
after typing "sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl" 
can somebody help me fix this? thanks a lot!

**Comment by 333caowei** [comment]
can you ```import ssl``` in python?

**Comment by mrry** [comment]
This is a known issue with some `pip` installations. The workaround is documented [here](https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#sslerror_ssl_verify_failed): simply download the `.whl` file using `curl` or `wget`, then pass the name of the downloaded file to `pip install` in place of the URL.
