### ISSUE TITLE
Disable warnning logging by default

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/tensorflow#23669]
One of the thing that I prefer pytorch more is that tensorflow are so annoying. Those infor logging such as tensorflow build doesn't with AVX or which gpu I got information does not needed to print out, cause we just doesn't care... those information we can get from nvidia or something else, but in tensorflow itself, we just need the model and logic....

It would make tensorflow more beautiful and wonderful if there are no such annoying information. simpler is better than complex.

**Comment by gunan** [comment]
This is really a tradeoff between two sides of TF users.
On one hand, TF is highly performance sensitive. Anything that can make TF faster, users may want to be aware of it. When we did not have some of these messasges, we received a lot of complaints that TF was silently slow, and users had no idea TF was slow.

On the other end of the spectrum is your point of view, where you would like it to "just work" without any cryptic messages.

Assigning to @martinwicke

**Comment by martinwicke** [comment]
Once we switch to MKL, these will disappear. Otherwise, what Gunhan said.
