### ISSUE TITLE
Help with what version to install?

### ISSUE THREAD

**Issue by user142** [tensorflow/tensorflow#23663]
I have a cuda compute capability 3.0 GPU ,AMD processor and running on windows 10 64bit . So when I checked the official tensorflow website it says requires cuda compute capability 3.5 or higher. 

So which version should I install from the repository to support cuda 3.0 and run on my computer. 

> https://www.tensorflow.org/install/gpu

**Comment by ymodak** [comment]
TensorFlow officially supports NVIDIA GPU. For using AMD gpu you have to compile TensorFlow using OpenCL. Please read this [setup guide] (https://developer.codeplay.com/computecppce/latest/getting-started-with-tensorflow) to get more insights on TensorFlow AMD Setup.

**Comment by user142** [comment]
> TensorFlow officially supports NVIDIA GPU. For using AMD gpu you have to compile TensorFlow using OpenCL. Please read this [setup guide](https://developer.codeplay.com/computecppce/latest/getting-started-with-tensorflow) to get more insights on TensorFlow AMD Setup.

Actually I have a NVIDIA GPU but it is cuda compute capability 3.0 GPU but tensorflow gpu support 3.5. So I was looking for a workaround.

**Comment by mrry** [comment]
That's right: our supported capabilities are 3.5 and 5.2. It may be possible to build for 3.0 from source, but we don't support that configuration, and some of the standard kernels may use features that require a more powerful GPU.
