### ISSUE TITLE
Documents for MirroredStrategy

### ISSUE THREAD

**Issue by sfujiwara** [tensorflow/tensorflow#23664]
**System information**

- TensorFlow version: 1.12
- Doc Link:
  1. https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distribute
  2. https://www.tensorflow.org/api_docs/python/tf/contrib/distribute/MirroredStrategy

**Describe the documentation issue**

[Document i](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distribute) says that `tf.contrib.distribute.MirroredStrategy` is for only the case of "single worker and multi GPUs".
But [document ii](https://www.tensorflow.org/api_docs/python/tf/contrib/distribute/MirroredStrategy) says that `MirroredStrategy` can work in multi-worker (multi-node) cluster.

Which is right?

If [document i](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distribute) is out of date, we have to update it.

**Comment by MarkDaoust** [comment]
It _looks_ like that README is out of date, but I'm no expert on the subject.

@yuefengzhou can you confirm?

**Comment by yuefengz** [comment]
`MirroredStrategy` works for multi-worker cluster but is not recommended. For multi-worker case, please use `CollectiveAllReduceStrategy`.

**Comment by sfujiwara** [comment]
I guess `tf.keras` will be the main stream of TensorFlow high level API because Estimator seems to be moved to [another repository](https://github.com/tensorflow/estimator).

However, `tf.keras` can not use `CollectiveAllReduceStrategy` for multi-worker case (that is spacified [here](https://www.tensorflow.org/guide/keras#multiple_gpus)).

If we want to implement multi-worker case, the best way is use `tf.keras`, convert it to Estimator with `
tf.keras.estimator.model_to_estimator`, and using `CollectiveAllReduceStrategy`?

**Comment by yuefengz** [comment]
@sfujiwara This is right. And we are working on multi-worker support for Keras.

**Comment by ustcyue** [comment]
@yuefengz I recently tested both `MirroredStrategy` and `CollectiveAllReduceStrategy` for various models on a 8 GPU server. I found `CollectiveAllReduceStrategy` is constantly slower than `MirroredStrategy` by about 30%. Is this expected? Or I am missing some configuration? Thanks!

**Comment by yuefengz** [comment]
@ustcyue The 30% sounds huge than what we expected. cc @poxvoculi

**Comment by yuefengz** [comment]
Closing this thread since the discussion for `CollectiveAllReduceStrategy`'s performance has been migrated to https://github.com/tensorflow/tensorflow/issues/24611.
