### ISSUE TITLE
__manage.py__ not found

### ISSUE THREAD

**Issue by dah512** [tensorflow/tensorflow#23660]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.11.6
- TensorFlow installed from (source or binary): source, if this means from tensorflow.org
- TensorFlow version:  TensorFlow version 1.12
- Python version: Python 3.6
- Installed using virtualenv? pip? condo?: installed using pip, conda and in a virtual environment
- Bazel version (if compiling from source): not yet
- GCC/Compiler version (if compiling from source): CPU version
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I installed tensorflow three weeks ago, via pip.  Then tried to start running tutorials or at least verify install.  Kept getting "file not found",  checked "pip list", it was there, but in downloads.  Then after further checking, noted it to be in site-packages under downloads.  I've done the installation as pip, as conda and in a virtual environment.  Comments like "virtualenv" not found frustrated the installation but I was eventually able to get set up a virtual environment.  Last night I tested it using the "pip --upgrade tensorflow", command.  Requirements had been met.  Then I tried opening both keras and tensorflow apps.  Okay,  tensorflow has an outer and inner directory.  No prob.  Still now I get "__manage.py__" not found in package.  Could not copy entire traceback from terminal but using the conda console I still get errors.  Here's a copy of the last commands I tried today and the traceback from the console,...albeit, the terminal traceback is much larger:

python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"

1. File "<ipython-input-1-77841da38ed1>", line 1
    python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
                                                                                                                         ^
SyntaxError: invalid syntax

2.  File "<ipython-input-2-92d0143764a7>", line 1
    python -c "import tensorflow as tf; tf.enable_eager_execution()
                                                                   ^
SyntaxError: EOL while scanning string literal

3.  File "<ipython-input-3-7e790e56de0e>", line 1
    python -c "import tensorflow as tf; tf.enable_eager_execution();
                                                                    ^
SyntaxError: EOL while scanning string literal

4. File "<ipython-input-4-77841da38ed1>", line 1
    python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
                                                                                                                         ^
SyntaxError: invalid syntax
**Provide the exact sequence of commands / steps that you executed before running into the problem**

5.   File "<ipython-input-5-50ca0a742afa>", line 1  [without quotes]
    python -c import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))
                   ^
SyntaxError: invalid syntax
**Any other info / logs**

Trying to copy the terminal log, and traceback.

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by shafi-dayatar** [comment]
I tried the same steps using conda  with Python 3.6 and tensorflow 1.2 version. I didn't face any problems mentioned above. 
```
(tf_python3.6)$ python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
2018-11-12 15:54:04.692350: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
tf.Tensor(526.10333, shape=(), dtype=float32)
```

I am not sure if this is tensorflow issue but I usually prefer conda to install tensorflow.

```
conda create --name tensorflow python=3.6
activate tensorflow
pip install tensorflow
```
Dont forget to activate the tensorflow environment on conda.

**Comment by mohantym** [comment]
Hi @dah512 ,
We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.5 version and MacOs 10.12.6(Sierra) .  let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!
