### ISSUE TITLE
Sparc compatibility

### ISSUE THREAD

**Issue by fuzzy13337** [tensorflow/tensorflow#23677]
<em> Tensorflow Lite Sparc Support tag:feature_template</em>

**System information**
- TensorFlow version: r1.10
- Are you willing to contribute it: if able to 

Tensorflow currently supports intel x86 (Windows,IOS) and ARM (raspberry pi), but not sparc architecture. Would be nice to also have support for sparc architecture.

**Comment by jdduke** [comment]
Closing due to stale history, feel free to re-open if this would still be of value.
