### ISSUE TITLE
Installation of tensorflow r1.10 on windows with visual studio c++ (with gpu) help.

### ISSUE THREAD

**Issue by Afroman1996** [tensorflow/tensorflow#23679]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.10
- Python version:3.6
- Installed using virtualenv? pip? conda?: pip
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 9.2, cuDNN 7.4.1.5
- GPU model and memory: 940mx 2GB Vram

**Describe the problem**
CUDA and cuDNN were succesfully installed. CMake to configure and generate build files for tensorflow was also done. MSBuild to build the ALL_BUILD.vcxproj project was invoked and an error was encountered during this. The error message shown in the command prompt is given below.

**Any other info / logs**
"C:\Users\Allosimanious\Documents\cud\tensorflow-r1.10\tensorflow\contrib\cmake\build\ALL_BUILD.vcxproj" (default targe
t) (1) ->
"C:\Users\Allosimanious\Documents\cud\tensorflow-r1.10\tensorflow\contrib\cmake\build\tensorflow.vcxproj" (default targ
et) (135) ->
"C:\Users\Allosimanious\Documents\cud\tensorflow-r1.10\tensorflow\contrib\cmake\build\tensorflow_static.vcxproj" (defau
lt target) (136) ->
"C:\Users\Allosimanious\Documents\cud\tensorflow-r1.10\tensorflow\contrib\cmake\build\tf_c.vcxproj" (default target) (1
37) ->
(ClCompile target) ->
  C:\Users\Allosimanious\Documents\cud\tensorflow-r1.10\tensorflow/core/distributed_runtime/rpc/grpc_server_lib.h(21):
fatal error C1083: Cannot open include file: 'grpcpp/grpcpp.h': No such file or directory [C:\Users\Allosimanious\Docum
ents\cud\tensorflow-r1.10\tensorflow\contrib\cmake\build\tf_c.vcxproj]

**Comment by skye** [comment]
We no longer officially support the cmake build, and suggest that you use bazel instead: https://www.tensorflow.org/install/source_windows

I'm marking this community support in case anyone else has run into this. cc/ @gunan

**Comment by harshini-gadige** [comment]
@skye  Just to make sure, do all the older versions of TF should be used with bazel ?  Because I see only TF v > 1.10 are supported by Bazel as per the tested build configuration. Please clarify.

**Comment by skye** [comment]
I'm not sure, but given that we're no longer developing the 1.10 branch, I suggest trying the most recent version of TF. @gunan probably knows more.

**Comment by gunan** [comment]
We encourage users to stay with the two latest versions of TF.
Especially if they are building from source.

As for branches, just like @skye mentioned, as soon as we cut a branch we stop developing on that.
any release before the last release (1.12) will only release critical security patches, nothing else will be patched in old release branches.

**Comment by tensorflowbutler** [comment]
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by mohantym** [comment]
Hi @Afroman1996 !
It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. Have you tried [latest version ](https://www.tensorflow.org/install/source_windows)yet ? Thanks!
