### ISSUE TITLE
lite compile error under tensorflow/lite/tools/make

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#23680]
when tflite move from tensorflow/contrib/lite to tensorflow/lite, all shell under lite/tools/make has and error, and should be below.

```bash
cd "$SCRIPT_DIR/../../../.."
```

**Comment by PINTO0309** [comment]
#23672

**Comment by andrehentz** [comment]
It looks like the suggested modification has been already made recently: https://github.com/tensorflow/tensorflow/commit/b4a7f51584d60e26024bb7401e3167704f94d298

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
