### ISSUE TITLE
Can't install on Raspberry pi 3B

### ISSUE THREAD

**Issue by ron159** [tensorflow/tensorflow#23682]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**Raspberry 9** on Pi 3B;Linux version 4.14.79-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1159 SMP Sun Nov 4 17:50:20 GMT 2018

- TensorFlow version:1.12.0
- Python version:**3.5.3**
- Installed using virtualenv? pip? conda?:**pip**

**Describe the problem**

Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip3 install tensorflow

**Any other info / logs**
libatlas-base-dev is already the newest version (3.10.3-1+rpi1).

**Comment by harshini-gadige** [comment]
@ron159  Is this issue resolved ?

**Comment by ron159** [comment]
> @ron159 Is this issue resolved ?

nope,i try to build from source on my pc, but still can not work

**Comment by habibutsu** [comment]
@ron159 Last success RPi build was for python 3.4 (you can download wheel by following link [tensorflow-1.10.0-cp34-none-linux_armv7l.whl](https://storage.googleapis.com/tensorflow-nightly/tensorflow-1.10.0-cp34-none-linux_armv7l.whl)

Currently is not clear what happening with supporting of this build for latest versions of TF

**Comment by metalalive** [comment]
I managed to build Tensorflow v1.12 (release branch) on Raspberry Pi 3B+ , using Bazel 0.19.2 ,
 but my build was for c++ shared library. 
Maybe that might work for building .whl ?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
