### ISSUE TITLE
[Regresssion] TypeError: In op 'ScatterUpdate', input types are not compatible with expected types

### ISSUE THREAD

**Issue by Hoeze** [tensorflow/tensorflow#23691]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09
- Python version: 3.6.6
- Bazel version (if compiling from source): 0.18.0
- GCC/Compiler version (if compiling from source):  8.2.1

**Describe the current behavior**
`tf.scatter_update` keeps failing with TypeError

**Describe the expected behavior**
Should work like with TF 1.11.0

**Code to reproduce the issue**
```python
import tensorflow as tf

x = tf.Variable([1,2,3,4,5])
idx = tf.placeholder(dtype=tf.int32, shape=(None,))
update = tf.placeholder(dtype=tf.int32, shape=(None,))
tf.scatter_update(x, idx, update)
```

This example works with Tensorflow 1.11 but fails with 1.12.
It does not matter whether the shapes of `idx` and `update` are set explicitly or `None`.

**Comment by Hoeze** [comment]
After some debugging I found out that this fails only after running some code I did not identify yet.


Stack trace: 
```python
  File "[...]/tf/rsa/estimator.py", line 86, in map_fn_EM
    updates=tf.transpose(model.estimated_mixture_log_prob)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 296, in scatter_update
    use_locking=use_locking, name=name)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 1210, in scatter_update
    use_locking=use_locking, name=name)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 738, in create_op
    **kwargs)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1748, in __init__
    input_types))
TypeError: In op 'ScatterUpdate', input types ([tf.float64, tf.int32, tf.float64]) are not compatible with expected types ([tf.float64_ref, tf.int32, tf.float64])
```

The exact cause of the raised error in my code is the following:
```python
# inputs
[<tf.Tensor 'ScatterUpdate/Placeholder:0' shape=(2221, 3) dtype=float64>,
 <tf.Tensor 'arg1:0' shape=(?,) dtype=int32>,
 <tf.Tensor 'transpose:0' shape=(?, 3) dtype=float64>]
# input_types
[tf.float64_ref, tf.int32, tf.float64]
```
=> `tf.Tensor 'ScatterUpdate/Placeholder:0' shape=(2221, 3) dtype=float64` is not compatible with `tf.float64_ref`.
`inputs` gets created somewhere in `_apply_op_helper, op_def_library.py`.

**Comment by alextp** [comment]
This is a bug on your code. In some place you're passing a tensor, not a variable, as the first argument to tf.scatter_update.

**Comment by Hoeze** [comment]
@alextp The problem is that I definitely don't do that.
It is 100% sure a tf.Variable.
I used Dataset.reduce() to scan over a dataset and scatter_update in each iteration a feature vector of the length of that Dataset.

**Comment by alextp** [comment]
Can you print the object before each call to scatter_update? Remember that tf ops which consume variables often return tensors, not variables.

**Comment by Hoeze** [comment]
@alextp Thanks for your help, I will try to.

For the moment, I can show you the source code, but it's maybe little bit hard to understand.
Here, I set up a tf.Variable:
https://github.com/theislab/batchglm/blob/a305c6cb1438c9fa728a931fe67b2a1b2f31867f/batchglm/train/tf/rsa/base.py#L379
```python3
mixture_logits = tf.Variable(init_mixture_logits, name="mixture_logits")
[...]
self.mixture_logits_var = mixture_logits
```
This tf.Variable will be passed to `scatter_update` here:
https://github.com/theislab/batchglm/blob/a305c6cb1438c9fa728a931fe67b2a1b2f31867f/batchglm/train/tf/rsa/estimator.py#L83-L87
```python3
mixture_EM_update = tf.scatter_update(
    ref=model_vars.mixture_logits_var,
    indices=idx,
    updates=tf.transpose(model.estimated_mixture_log_prob)
)
```

So, I really don't get how `model_vars.mixture_logits_var` changes its type; 
especially since the same code works in my own `map_reduce` implementation:
https://github.com/theislab/batchglm/blob/4daf7d7f27955764e3871fc8296d1024808ac785/batchglm/train/tf/rsa/estimator.py#L76-L80
