### ISSUE TITLE
unable to detect multiple faces in an image/video

### ISSUE THREAD

**Issue by username2590** [tensorflow/tensorflow#23704]
Hello,
i am building a face detection system for study purposes.
I installed tensorflow for python and developed a code in python for face detection.

If i have a single person in the image/video i am able to detect it.
But with multiple faces only one face is detected and others are ignored.

If anyone can help me i would be thankful to you.

Regards,
Napster

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
