### ISSUE TITLE
installation problem in ubuntu 64 gpu

### ISSUE THREAD

**Issue by deependersingla** [tensorflow/tensorflow#2370]
Tried installing it on ubuntu but getting this error even using Virtualenv:
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow.py", line 11, in <module>
    W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
AttributeError: 'module' object has no attribute 'Variable'
```

### Environment info
Operating System: Ubuntu
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
x86_64 x86_64 x86_64 GNU/Linux
python 2.7.9

Installed version of CUDA and cuDNN: 
```
-rw-r--r-- 1 root root 189170 Jan 12 14:47 /usr/local/cuda-7.5/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Jan 12 14:47 /usr/local/cuda-7.5/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Jan 12 14:47 /usr/local/cuda-7.5/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Jan 12 14:47 /usr/local/cuda-7.5/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Jan 12 14:47 /usr/local/cuda-7.5/lib/libcudart_static.a
```

If installed from binary pip package, provide:
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl

### What have you tried?
1.simple install
2.VirutalEnv install 
Both didn't worked.

**Comment by mrry** [comment]
I think the problem here is that you have a file called `tensorflow.py` in your current directory. Python will interpret `import tensorflow as tf` as an instruction to load that script, rather than the installed TensorFlow module. Renaming that file to something else should fix the problem.

**Comment by deependersingla** [comment]
@mrry Thanks and big facepalm for me :).

**Comment by mrry** [comment]
No problem, it's happened to me a few times too! :)

**Comment by deependersingla** [comment]
Yes, I think its mainly because when we are in terminal we don't see file tree.
