### ISSUE TITLE
please give an introduction of using quantize-aware training with tf.estimator

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#23711]
How to use  `tf.contrib.quantize.*` with tf.estimator or how to using  post_quantize_training model with inference type of int8.  Demo is perferred, thanks.

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by iamhankai** [comment]
@zh794390558 Have you solved this problem?
