### ISSUE TITLE
How to remove NMS ops in mobilenet+ssd model?

### ISSUE THREAD

**Issue by StephenGreat** [tensorflow/tensorflow#23714]
I use mobilenet+ssd for detection with android NN. But  TFLite is not supported for NMS such customized ops.  So I want to remove NMS ops in the .pb model. Is there any method for that?
Or any case of translating mobilnet+ssd to TFLite with android NN?

**Comment by achowdhery** [comment]
Are you following the steps in the [blog post](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193)? If yes, which part is unclear?

**Comment by StephenGreat** [comment]
I fellow the steps on processing my own .pb file. But when using android NNAPI I got the following error. It seems that the tflite model has some custom operations. 
    E/tflite: Custom operations are not supported when using NNAPI.

So how to use NNAPI for accelerating mobile+ssd?

**Comment by StephenGreat** [comment]
I fellow the steps on processing my own .pb file. But when using android NNAPI I got the following error. It seems that the tflite model has some custom operations. 
    E/tflite: Custom operations are not supported when using NNAPI.

So how to use NNAPI for accelerating mobile+ssd?

**Comment by achowdhery** [comment]
If you run export_tflite_ssd_graph.py with the --add_postprocessing_op=false, then you can remove the custom op that will enable you to use NNAPI

**Comment by cabahug2** [comment]
Hello, I exported an ssd model without the post processing op but it looks like the outputs are arrays of uint8 instead of a float32 as the comment block [here](https://github.com/tensorflow/models/blob/35f33abb8fa40053e8791b9144e894169e543869/research/object_detection/export_tflite_ssd_graph.py#L38) says. Is this a typo?

**Comment by achowdhery** [comment]
For a quantized model, the outputs without NMS op are quantized. You will need to convert them to float using zero-point and scale.

**Comment by cabahug2** [comment]
@achowdhery does TFLite have support for the dequantization and NMS ops for Java?

**Comment by mrgloom** [comment]
What if I have custom object detection model (not SSD), but for example [FaceBoxes](https://github.com/TropComplique/FaceBoxes-tensorflow) which also use `tf.image.non_max_suppression` 
https://github.com/TropComplique/FaceBoxes-tensorflow/blob/545ec4f4f3c55c3592ee189ed56a11a3fd017194/src/utils/nms.py#L30

@pkulzc can you eleborate on this?

**Comment by mrtehseen** [comment]
Try using this operation modifier while converting the model to TFLite.
```
converter = tf.lite.TFLiteConverter.from_saved_model("_modelspath_")
converter.post_training_quantize=True
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                        tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
open("litemodel.tflite", "wb").write(tflite_model)
```

**Comment by reactivetype** [comment]
@mrgloom has made a good point. Why is NMS custom ops only supporting SSD model? Is there a plan to support non-SSD models that use `tf.image.non_max_suppression?`

**Comment by MeghnaNatraj** [comment]
Marking issue as resolved due to inactivity. Feel free to re-open this if it's unresolved or file a [new issue](https://github.com/tensorflow/tensorflow/issues/new/choose)

**Comment by tucachmo2202** [comment]
> @mrgloom has made a good point. Why is NMS custom ops only supporting SSD model? Is there a plan to support non-SSD models that use `tf.image.non_max_suppression?`

It can't be now. They are using `TFLite_Detection_PostProcess` in SSD instead of `tf.image.non_max_suppression?`. I want to apply this operation to other models too. If you have any answers, please let me know.
