### ISSUE TITLE
Unable to import tf.keras.optimizers

### ISSUE THREAD

**Issue by srihari-humbarwadi** [tensorflow/tensorflow#23728]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.0
- Python version: 3.6
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: 9.0, 7.0
- GPU model and memory: GTX 1080ti 11gb

**Describe the current behavior**
Cannot import keras.optimizers when done like this
```
from tensorflow.keras.optimizers import *

ImportError                               Traceback (most recent call last)
<ipython-input-17-ea1fa27bfa23> in <module>()
----> 1 from tensorflow.keras.optimizers import *

~/tf/lib/python3.6/site-packages/tensorflow/keras/__init__.py in <module>()
     18 from tensorflow.keras import estimator
     19 from tensorflow.keras import initializers
---> 20 from tensorflow.keras import layers
     21 from tensorflow.keras import losses
     22 from tensorflow.keras import metrics

~/tf/lib/python3.6/site-packages/tensorflow/keras/layers/__init__.py in <module>()
      7 
      8 from tensorflow.python.keras import Input
----> 9 from tensorflow.python.keras.applications.densenet import Activation
     10 from tensorflow.python.keras.applications.densenet import AveragePooling2D
     11 from tensorflow.python.keras.applications.densenet import AveragePooling2D as AvgPool2D

ImportError: cannot import name 'Activation'
```
but this seems to work fine
```
import tensorflow as tf
optim = tf.keras.optimizers.Adam()
```
what weird is that even this works
```
from tensorflow.python.keras.optimizers import *
```

**Comment by deryrahman** [comment]
Have you solved this problem? I face the same problem, but still don't know how to solve it @srihari-humbarwadi

**Comment by MehmetEminELMACI** [comment]
from tensorflow.python.keras.optimizers import RMSprop
My optimizers doesnt work can u help me 
How can ı fix this

**Comment by MehmetEminELMACI** [comment]
The mistake is;
ImportError: cannot import name 'RMSprop' from 'tensorflow.python.keras.optimizers' (C:\Anaconda3\lib\site-packages\tensorflow\python\keras\optimizers.py)

**Comment by mrverdelho** [comment]
> The mistake is;
> ImportError: cannot import name 'RMSprop' from 'tensorflow.python.keras.optimizers' (C:\Anaconda3\lib\site-packages\tensorflow\python\keras\optimizers.py)

I have the same problem.

**Comment by taga93** [comment]
I have the same problem, but not only with optimizers:

```
from tensorflow.python.keras.utils import to_categorical

from tensorflow.python.keras.utils import to_categorical
ImportError: cannot import name 'to_categorical' from 'tensorflow.python.keras.utils'
```

And with optimizers:

```
from tensorflow.python.keras.optimizers import SGD

from tensorflow.python.keras.optimizers import SGD
ImportError: cannot import name 'SGD' from 'tensorflow.python.keras.optimizers'
```

**Comment by azuryl** [comment]
I have the same problem

**Comment by LazyDareDevil** [comment]
ImportError: cannot import name 'Adam' from 'keras.optimizers' (C:\Programming\Python39\lib\site-packages\keras\optimizers.py)
while running Jupyter notebook in VSCode

**Comment by Piyushagg19** [comment]
@LazyDareDevil: I'm facing the same issue. Can you please explain a bit more about '_reducing the importing keas and submodules_'? It would be really great if you could also attach a code snippet. 
Thanks!

**Comment by LazyDareDevil** [comment]
@Piyushagg19 I had importes like:
import tensorflow as tf
from tensorflow import keras
from keras..optimizers import Adam

then I done:
from tensorflow.keras.optimizers import Adam

and it works for me

I think, it's nessesary to add tensorflow before keras

**Comment by Piyushagg19** [comment]
@LazyDareDevil: I did the exact same way but for some reason it is throwing an error.

**Comment by chaymaa22** [comment]
I had the same problem, and i solved it by : 

from tensorflow.keras.optimizers import RMSprop

instead of : 

from keras.optimizers import RMSprop

**Comment by cemdede** [comment]
As @LazyDareDevil mentioned:
`from tensorflow.keras.optimizers import` works.

Then I was able to add:
`adam=Adam(learning_rate = 0.01)` and 
`model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])`

**Comment by ranewad** [comment]
File "F:\python\Project\src\train.py", line 7, in <module>
    from keras.optimizers import Adam
ImportError: cannot import name 'Adam' from 'keras.optimizers' (F:\anaconda3\lib\site-packages\keras\optimizers.py)

I'm facing the issue. anyone solved plz

**Comment by LazyDareDevil** [comment]
@ranewad even if you imported tensorflow or tensorflow.keras, you need to import by using full path for method, like:
from tensorflow.keras.optimizers import Adam

Please, learn how to properly import libraries and functions

**Comment by ranewad** [comment]
@LazyDareDevil ok

**Comment by mikekaylor98** [comment]
"Please, learn how to properly import libraries and functions"

So, why when I do it your way I get even more errors?

**Comment by mikekaylor98** [comment]
> @ranewad even if you imported tensorflow or tensorflow.keras, you need to import by using full path for method, like: from tensorflow.keras.optimizers import Adam
> 
> Please, learn how to properly import libraries and functions

So why do I get more errors when I do it your way?

**Comment by rudSarkar** [comment]
> I had the same problem, and i solved it by :
> 
> from tensorflow.keras.optimizers import RMSprop
> 
> instead of :
> 
> from keras.optimizers import RMSprop

Tried this but not working either I use like `from tensorflow.keras.optimizers import Adam` it showing `Import "tensorflow.keras.optimizers" could not be resolved`

Current version of tensorflow is `2.8.0` should I roll back to 1.x.x ?

**Comment by ChrysthianChrisley** [comment]
The problem is:

Check if you are already importing tensorflor or keras **before** using from tensorflow.keras.optimizers.

You can just use from keras.optimizers import Adam
or something like that.

**Comment by ElwoodHogan** [comment]
im getting this error too.  none of these solutioinshave worked
