### ISSUE TITLE
pybullet.error: createCollisionShape failed.

### ISSUE THREAD

**Issue by JobSmith** [tensorflow/tensorflow#23729]
It is on Ubuntu 16.04LTS, and it shows this error:

![image](https://user-images.githubusercontent.com/15700681/48466407-c1a1bd00-e820-11e8-80f4-695690415552.png)

**Comment by ymodak** [comment]
It doesn't look like an error on TensorFlow's end. Can you please share your bullet-test.py script?

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by JobSmith** [comment]
ok， I have solved it. thank you!

**Comment by csingh27** [comment]
@JobSmith how did you solve it ?

**Comment by sash-a** [comment]
For anyone still looking GEOM_BOX requires the halfExtents argument, even though in the quickstart guide it claims that there is a default. So `p.createCollisionShape(p.GEOM_BOX)` won't work, but `p.createCollisionShape(p.GEOM_BOX, halfExtents=[1, 1, 1])` will

**Comment by WondaRosen** [comment]
@JobSmith 你怎么解决的，我也遇到这个问题了
