### ISSUE TITLE
Sparse Precision Matrix implemetations (for gaussian processes or GMRFs)

### ISSUE THREAD

**Issue by sadatnfs** [tensorflow/tensorflow#23725]
Are there any plans in the near future to implement sparse precision matrix computations for TensorFlow? My main use case when I'll be using this is for models like a Gaussian Process where a sparse precision matrix can be fed in as a Gaussian Markov Random Field to evaluate the GP (the sparse representation of an AR(1) GP is only tri-diagonal whereas the covariance matrix is dense).

Being able to evaluate on sparse matrices would be super helpful in computation speeds I think. Thoughts?

**System information**
- TensorFlow version (you are using): 1.12.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**
Only additions I hope

**Who will benefit with this feature?**
Statistical modelers with high dimensional sparse data

**Any Other info.**

**Comment by sushreebarsa** [comment]
@sadatnfs Older versions of TF(1.x) are not actively supported. Could you refer to this [latest](https://github.com/kaskr/adcomp/blob/master/TMB/inst/include/tmbutils/density.hpp) branch and let us know if it helps?
Thank you!
