### ISSUE TITLE
Build error while building contrib/bigtable

### ISSUE THREAD

**Issue by jxstanford** [tensorflow/tensorflow#23721]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.12 and master (7561099fb65c18bd091751b60fc45550fc5d4805)
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: pyenv
- Bazel version (if compiling from source): 0.19.1
- GCC/Compiler version (if compiling from source): gcc-6 (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424
- CUDA/cuDNN version: 10.0 / 7.4
- GPU model and memory: GTX 1080ti

**Describe the problem**

Error message: ERROR: /home/jxstanford/src/tensorflow/tensorflow/contrib/bigtable/BUILD:53:1: Linking of rule '//tensorflow/contrib/bigtable:p
ython/ops/_bigtable.so' failed (Exit 1) gcc-6 failed: error executing command /usr/bin/gcc-6 -shared -o bazel-out/k8-opt/bin/tensorflow/contri
b/bigtable/python/ops/_bigtable.so ... (remaining 64 argument(s) skipped)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`git checkout r1.12`
`bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/lite/...`

**Any other info / logs**

Build output attached.
(https://github.com/tensorflow/tensorflow/files/2577363/TF_BUILD_OUTPUT.txt)

**Comment by ymodak** [comment]
Try as per the warning message, add following line to **.bazelrc** file:
import /home/jxstanford/src/tensorflow/tools/bazel.rc

**Comment by jxstanford** [comment]
your suggestion resulted in a viable test run, but I still had problems later in the build process. 
 downgrading bazel to 18.1 resolved the problem.

**Comment by ymodak** [comment]
Thanks for sharing your workaround.
