### ISSUE TITLE
Object_detection model supports IOS?

### ISSUE THREAD

**Issue by baihualinxin** [tensorflow/tensorflow#23734]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:MAC 10.14
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:Phone 8
- **TensorFlow installed from (source or binary)**:bazel 
- **TensorFlow version (use command below)**:1.10.0
- **Python version**:3.6
- **Bazel version (if compiling from source)**:0.15.0
- **GCC/Compiler version (if compiling from source)**:NO
- **CUDA/cuDNN version**:NO
- **GPU model and memory**:NO
- **Exact command to reproduce**:NO

### Source code / logs
How to support IOS for object detection？？？
model:ssd_mobilenet_v1_

**Comment by jdduke** [comment]
We're actively working on a port of the existing Android object detection sample to iOS.

**Comment by airman00** [comment]
@jdduke - where? 

would love to contribute

**Comment by jdduke** [comment]
It hasn't yet been staged in the public repo. We're hoping to push the updated samples very early Q1 (or sooner).
