### ISSUE TITLE
Error when using tf.metrics.mean_iou() in eval_metric_ops of tf.estimator.EstimatorSpec()

### ISSUE THREAD

**Issue by mzhaoshuai** [tensorflow/tensorflow#23731]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:_no_
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  _Linux Ubuntu 16.04.5 LTS_。
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:_no_
- **TensorFlow installed from (source or binary)**:_binary_
- **TensorFlow version (use command below)**:_1.11.0_
- **Python version**:_Python 3.5.2_
- **Bazel version (if compiling from source)**:_None_
- **GCC/Compiler version (if compiling from source)**:_None_
- **CUDA/cuDNN version**:_CUDA-9.1/cuDNN-7.0.5_
- **GPU model and memory**: _GTX 1080Ti 11GB, 2 same cards_
- **Exact command to reproduce**:_below_

### Supplementary material
I just pulled the tensorflow's offical docker image and RUN some `pip install ...` instructions.
The tag of the iamge is `1.11.0-devel-gpu-py3`.

### Describe the problem
When I use the code below

```
accuracy = tf.metrics.accuracy(valid_labels, valid_preds)
mean_iou = tf.metrics.mean_iou(valid_labels, valid_preds, params['num_classes'])
print(mean_iou)
eval_metrics = {'px_accuracy': accuracy, 'mean_iou': mean_iou}	
......
return tf.estimator.EstimatorSpec(
		mode=mode,
		predictions=None,
		loss=loss,
		train_op=train_op,
		eval_metric_ops=eval_metrics)
```

It will raise `TypeError`

```
TypeError: eval_metric_ops[mean_iou] must be Operation or Tensor, 
given: <tf.Variable 'mean_iou/AssignAddVariableOp' shape=(21, 21) dtype=float64>
```

And the result of  `print` is

```
(<tf.Tensor 'mean_iou/Select_1:0' shape=() dtype=float32>, 
<tf.Variable 'mean_iou/AssignAddVariableOp' shape=(21, 21) dtype=float64>)
```

I google the error and find the similar issue
https://github.com/tensorflow/tensorflow/issues/20418

So I modify the code
```
accuracy = tf.metrics.accuracy(valid_labels, valid_preds)
mean_iou = tf.metrics.mean_iou(valid_labels, valid_preds, params['num_classes'])
mean_iou = (mean_iou[0], tf.to_float(mean_iou[1]))
print(mean_iou)
eval_metrics = {'px_accuracy': accuracy, 'mean_iou': mean_iou}	
```
Then the code works normally.

So I think there may be something wrong in `tf.metrics.mean_iou`.

A strange thing is that the original code(no `tf.to_float()`) used to work normally......
After I add `distribution strategy`  to the config of the estimator and do some other changes , it broke down.

**Comment by alextp** [comment]
Mustafa, can you make this check in Estimator be less false-positive-friendly? It should take anything convert_to_tensor is happy with, not just things which are exactly tensors or ops.

**Comment by ispirmustafa** [comment]
Hey @pavithrasv, could you please relax the assertion as Alex recommended?
thanks
