### ISSUE TITLE
No TF import library to link custom operators on Windows

### ISSUE THREAD

**Issue by evgal** [tensorflow/tensorflow#23740]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, 64 bits
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary / pip
- TensorFlow version (use command below): 1.12
- Python version: 3.5
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**

The import library tensorflow\python\pywrap_tensorflow_internal.lib is missing. I tried to regenerate it myself from _pywrap_tensorflow_internal.pyd to build my custom operators, but
tf.load_op_library throws the exception tensorflow.python.framework.errors_impl.NotFoundError and does not find the library given in argument. The exception appears in TF_LoadLibrary.

**Describe the expected behavior**

In TF 1.8 the import library tensorflow\python\pywrap_tensorflow_internal.lib is present, but not in TF 1.12. This library is required to build custom operators.

tf.load_op_library is working correctly with TensorFlow 1.8 on my configuration. The same custom operators rebuilt for TF 1.12 are not found by tf.load_op_library, although the paths of the dll given to tf.load_op_library are correct.

**Other info / logs**

Either there is a problem with tf.load_op_library in TF 1.12 contrary to TF 1.8, or there is a mistake in my process to generate the import library from the pyd file (the process is normally used for dll, not pyd).

In all cases, the dll of the custom operator generated with the provided import library in TF 1.8 depends on _pywrap_tensorflow_internal.pyd, whereas the dll generated with my own import library for TF 1.12 depends on pywrap_tensorflow_internal.dll which is a non existing file.

The simplest way to tackle this issue first seems to include again pywrap_tensorflow_internal.lib in the pip package to build custom operators on Windows.

**Comment by evgal** [comment]
I solved this issue by changing the way I generate the import library pywrap_tensorflow_internal.lib. Now the dll of my custom operators depend on _pywrap_tensorflow_internal.pyd instead of pywrap_tensorflow_internal.dll.

I still let the issue opened as the import library pywrap_tensorflow_internal.lib should be included in the pip package as in TF 1.8.

**Comment by mrry** [comment]
@meteorcloudy @gunan This sounds like a potential regression from the switch to Bazel. Does one of you know how to add this file back?

**Comment by meteorcloudy** [comment]
I can send a change to add this file back

**Comment by meteorcloudy** [comment]
Note that `_pywrap_tensorflow_internal.lib` still depends on `_pywrap_tensorflow_internal.pyd` instead of `_pywrap_tensorflow_internal.dll`

**Comment by evgal** [comment]
"Note that _pywrap_tensorflow_internal.lib still depends on _pywrap_tensorflow_internal.pyd"

That is the expected behavior. It does not work if _pywrap_tensorflow_internal.lib depends on _pywrap_tensorflow_internal.dll as this file does not exist, that was my error when I generated the import library myself.

**Comment by evgal** [comment]
I cannot reopen the issue, but the issue persist, the file is still missing in the pip package.

Could you please reintroduce the library _pywrap_tensorflow_internal.lib in the pip pickage ?
