### ISSUE TITLE
Export train-test split in raster/vector format

### ISSUE THREAD

**Issue by fieranisa** [tensorflow/tensorflow#23749]
I want to classify an image using support vector machine algorithm. Then, I imported samples in raster format and applied train-test split to assign 70% for training and 30% for testing. I want to export the samples after being split to vector or raster format. Is it possible to perform such things?

Thanks for your help.

**Comment by ymodak** [comment]
You can explore ArcPy module to import/export data in raster format in Python, if haven't already.

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
