### ISSUE TITLE
Matplotlib incompatibility when using virtualenv

### ISSUE THREAD

**Issue by chrishenx** [tensorflow/tensorflow#2375]
RuntimeError when importing matplotlib.pyplot in a jupyter notebook from a virtual environment:

`RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ`

I have solved the problem using one of the solutions mentioned at: [Matplotlib VirtualEnv FAQ](http://matplotlib.org/faq/virtualenv_faq.html) and that is ok when using python from the command line or a script file, but not with the kernel used in jupyter.

So, the question is: how to create a jupyter kernel that uses a specific bash which properly setups python to use matplotlib within a virtual environment.

Another solution is:
```
import matplotlib  
matplotlib.use('TkAgg')   
import matplotlib.pyplot as plt  
```
But maybe that is not the best thing to do. So, any suggestions?.
Operating System: OS X El capitan
Tensorflow version: 0.8.0

**Comment by shekkizh** [comment]
Just curious why you would post this question here?! This is clearly not an issue in tensorflow.

**Comment by mrry** [comment]
I'm closing this as it doesn't seem relevant to TensorFlow.

**Comment by billautomata** [comment]
for those who find this with a google search - this is the mostly solution I found that worked at getting matplotlib errors to go away even with jupyter notebooks: http://blog.rousek.name/2015/11/29/adventure-with-matplotlib-virtualenv-and-macosx/

I hope this doesn't reopen the ticket.

**Comment by abhimanu** [comment]
For Mac OS X users who still get this issue, the simplest work around I found is to add this line:
`backend: TkAgg`

in ~/.matplotlib/matplotlibrc

https://stackoverflow.com/questions/34977388/matplotlib-runtimeerror-python-is-not-installed-as-a-framework
