### ISSUE TITLE
Can't Enable Eager Execution [tensorflow_gpu==1.12.0]

### ISSUE THREAD

**Issue by IMBurbank** [tensorflow/tensorflow#23753]
I'm following the [Tensorflow Eager Execution Guide](https://www.tensorflow.org/guide/eager) and can't  enable eager execution.

System info:

> tensorflow_gpu 1.12.0 (std binary)
python 3.6.6
linux Mint 19
kernel 4.15.0-38
nvidia geforce 1050ti

Steps to reproduce:

```python
import tensorflow as tf
tf.enable_eager_execution()
tf.executing_eagerly()
# False
```

**Comment by IMBurbank** [comment]
Thanks for the input.

I didn't include jupyter `1.0.0` and IPython `7.1.1` versions in my software stack. 

I can run eager execution on colab, but not locally using a jupyter notebook. With such a simple setup, there aren't many opportunities to go astray. 

It has to have something to do with how jupyter is interacting with tf. Now I'm thinking it's probably on their side. I'll look deeper into the issue and file one there if I can't pinpoint it.

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
