### ISSUE TITLE
TFLite not support variable batch_size of input

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#23768]
I use `tf.estimator.export.build_raw_serving_input_receiver_fn` api with `default_batch_size=None` to export a savedModel, which input shape maybe [None, 3000, 40, 3].  But after convert the model to tflite model , the input shape is [1, 3000, 40, 3].  How can I using tflite with variable batch_size of input.

**Comment by andrehentz** [comment]
Depending on the your model, it might be impossible to create a tflite version that allows resizing of the input tensor.

Although the tflite interpreter allows you to resize the input tensor, the conversion process sometimes hardcodes shapes (supposedly for efficiency reasons). However, it should be possible to convert the model with a fixed batch size, say 5, and use that at inference time.

**Comment by zh794390558** [comment]
@andrehentz So, how can I using with fixed batch size , like 5 ?

**Comment by andrehentz** [comment]
Try running tflite_convert again, with --input_shapes=5,3000,40,3

**Comment by zh794390558** [comment]
@andrehentz I have tried, and see #23799
