### ISSUE TITLE
tensorflow lite: error when convert from keras model .h5

### ISSUE THREAD

**Issue by damhurmuller** [tensorflow/tensorflow#23760]
When I try convert the keras model to tflite, this error appears:
`
TypeError: ('Keyword argument not understood:', 'negative_slope')`

But only with some models like mobilenet and mobilenetv2. When I convert my inceptionv3 and nasnetmobile is Ok. All the models that Im trying to convert was retrained and fine tuned.

Code:
`import numpy as np`
`import tensorflow as tf`
`converter = tf.contrib.lite.TocoConverter.from_keras_model_file('models/mobilenetv2_tune.h5')`
`tflite_model = converter.convert()`
`open("mobilenetv2_model.tflite", "wb").write(tflite_model)`

**Keras version**: 2.2.4
**Tensorflow version**: 1.10.1

**Comment by damhurmuller** [comment]
I solved the problem using the tf-nightly-gpu, probably is some bug with the incompatibility of versions between keras and tensorflow.

**Comment by ymodak** [comment]
That' great. I will close this issue since its resolved.
