### ISSUE TITLE
Build failure on TensorFlow v1.12.0 on s390x

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#23771]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04, 18.04 s390x
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary):  source 
- TensorFlow version: v1.12.0
- Python version:  2.7.x
- Installed using virtualenv? pip? conda?:  Building from source 
- Bazel version (if compiling from source): v0.15.0
- GCC/Compiler version (if compiling from source): 7.0.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**

We are building TensorFlow v1.12.0 from source on Ubuntu 16.04, 18.04 on s390x platform .
Build fails with an error: "`Unknown Target CPU`" 

Bulid command: 
  `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package `

@gunan We haven't observed this Boringssl error with current master build and it's building successfully on s390x. CI link: https://ibmz-ci.osuosl.org/job/TensorFlow_IBMZ_CI/

However while building v1.12.0 (since it is latest stable) , we came across this issue.  
Looks like some code changes made in master which resolves issues related to Boringssl w.r.t. s390x are missing in v1.12.0.

Will the Tensorflow v1.13.0 have the required changes to skip Boringssl for s390x?  Or is there a way to fix build issue in v1.12.0 ? Please let us know.

**Comment by Nayana-ibm** [comment]
@gunan Could you please provide your inputs on this.

**Comment by gunan** [comment]
I think this commit is missing from the release branch.
https://github.com/tensorflow/tensorflow/commit/3914ff714ba4561ecff329012d02c3de027ee4a5
Does this commit fix the issues for you for 1.12?

**Comment by gunan** [comment]
It is possible even https://github.com/tensorflow/tensorflow/commit/3437098ba5b111817ef6ac5906d86934168704b7 is missing from the release and that should definitely exclude all cloud capabilities from s390x builds.

**Comment by Nayana-ibm** [comment]
@gunan the commits that you have mentioned are applicable to master branch.  In [v1.12.0]( https://github.com/tensorflow/tensorflow/blob/v1.12.0/tensorflow/BUILD) ,  gcp or aws support configs are not available.  

For v1.12.0, I have disabled Apache Ignite support throgh ./configure and I could build TensorFlow

`./configure`
```
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.15.0- (@non-git) installed.
Please specify the location of python. [Default is /usr/bin/python]:


Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Do you wish to build TensorFlow with Apache Ignite support? [Y/n]: N
No Apache Ignite support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: N
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: N
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: N
Clang will not be downloaded.

Do you wish to build TensorFlow with MPI support? [y/N]: N
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
Configuration finished
```

Now I will be continuing with test case execution using command: 
`bazel  test --test_timeout 300,450,1200,3600 --build_tests_only -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/core/platform/cloud/... -//tensorflow/contrib/lite/... -//tensorflow/contrib/cloud/... -//tensorflow/java/...`

* Excluding` //tensorflow/java` as it fails with an error '`Building Java resource jar failed`' [#19770]
* Excluding `//tensorflow/core/platform/cloud/` and `//tensorflow/contrib/cloud/` as it gives Boringssl issue for s390x.

**Comment by Nayana-ibm** [comment]
Closing this as TensorFlow can be built on s390x by disabling Apache Ignite support through ./configure
