### ISSUE TITLE
Error on Label's datatype when enable eager execution in Colab 

### ISSUE THREAD

**Issue by dailiang18bb** [tensorflow/tensorflow#23779]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.14.1 - Colab
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: None
- **TensorFlow installed from (source or binary)**: Colab build in
- **TensorFlow version (use command below)**: 1.12.0
- **Python version**: Colab Python2
- **Bazel version (if compiling from source)**: None
- **GCC/Compiler version (if compiling from source)**: None
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**: None

### Describe the problem
When I run the simple DNN on MNIST without eager execution, it works fine. However, when I enable eager execution then fit the model, I got the error said that my `train_labels` and `test_labels` has to be `int64` tensor which are originally `uint8` tensor. The error is shown as below:

`InvalidArgumentError: cannot compute Equal as input #0(zero-based) was expected to be a int64 tensor but is a uint8 tensor [Op:Equal]`

Although, I can fix it by using `train_labels = train_labels.astype(np.int64)` ,It looks like the error should be fixed in the source code.

### Source code to reproduce the issue in Colab

```python

import tensorflow as tf
import numpy as np

tf.enable_eager_execution()

mnist = tf.keras.datasets.mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

train_images = train_images / 255.0
test_images = test_images / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28,28)),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(128, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.compile(optimizer = tf.train.AdamOptimizer(0.001),loss='sparse_categorical_crossentropy',metrics=['accuracy'])

model.summary()

history = model.fit(x = train_images,y = train_labels,validation_split=0.1,batch_size = 256,verbose=2,shuffle = True,epochs=10)

```

### Other info / logs

```Python traceback

InvalidArgumentErrorTraceback (most recent call last)
<ipython-input-6-7bdf2a937371> in <module>()
      5                     verbose=2,
      6                     shuffle = True,
----> 7                     epochs=10)
      8 ###########################################
 .
 .
 .
 .
 .
 .     
      
/usr/local/lib/python2.7/dist-packages/six.pyc in raise_from(value, from_value)
    735 else:
    736     def raise_from(value, from_value):
--> 737         raise value
    738 
    739 

InvalidArgumentError: cannot compute Equal as input #0(zero-based) was expected to be a int64 tensor but is a uint8 tensor [Op:Equal]

```

**Comment by yongtang** [comment]
@dailiang18bb I am able to reproduce with Tensorflow 1.12 but not tf-nightly. Can you give tf-nightly a try and see if the issue has been fixed?

**Comment by ThomasHagebols** [comment]
> ### System information
> * **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
> * **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.14.1 - Colab
> * **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: None
> * **TensorFlow installed from (source or binary)**: Colab build in
> * **TensorFlow version (use command below)**: 1.12.0
> * **Python version**: Colab Python2
> * **Bazel version (if compiling from source)**: None
> * **GCC/Compiler version (if compiling from source)**: None
> * **CUDA/cuDNN version**: None
> * **GPU model and memory**: None
> * **Exact command to reproduce**: None
> 
> ### Describe the problem
> When I run the simple DNN on MNIST without eager execution, it works fine. However, when I enable eager execution then fit the model, I got the error said that my `train_labels` and `test_labels` has to be `int64` tensor which are originally `uint8` tensor. The error is shown as below:
> 
> `InvalidArgumentError: cannot compute Equal as input #0(zero-based) was expected to be a int64 tensor but is a uint8 tensor [Op:Equal]`
> 
> Although, I can fix it by using `train_labels = train_labels.astype(np.int64)` ,It looks like the error should be fixed in the source code.
> 
> ### Source code to reproduce the issue in Colab
> ```python
> import tensorflow as tf
> import numpy as np
> 
> tf.enable_eager_execution()
> 
> mnist = tf.keras.datasets.mnist
> (train_images, train_labels), (test_images, test_labels) = mnist.load_data()
> 
> train_images = train_images / 255.0
> test_images = test_images / 255.0
> 
> model = tf.keras.models.Sequential([
>   tf.keras.layers.Flatten(input_shape=(28,28)),
>   tf.keras.layers.Dense(512, activation=tf.nn.relu),
>   tf.keras.layers.Dropout(0.2),
>   tf.keras.layers.Dense(128, activation=tf.nn.relu),
>   tf.keras.layers.Dropout(0.2),
>   tf.keras.layers.Dense(10, activation=tf.nn.softmax)
> ])
> 
> model.compile(optimizer = tf.train.AdamOptimizer(0.001),loss='sparse_categorical_crossentropy',metrics=['accuracy'])
> 
> model.summary()
> 
> history = model.fit(x = train_images,y = train_labels,validation_split=0.1,batch_size = 256,verbose=2,shuffle = True,epochs=10)
> ```
> 
> ### Other info / logs
> ```python
> InvalidArgumentErrorTraceback (most recent call last)
> <ipython-input-6-7bdf2a937371> in <module>()
>       5                     verbose=2,
>       6                     shuffle = True,
> ----> 7                     epochs=10)
>       8 ###########################################
>  .
>  .
>  .
>  .
>  .
>  .     
>       
> /usr/local/lib/python2.7/dist-packages/six.pyc in raise_from(value, from_value)
>     735 else:
>     736     def raise_from(value, from_value):
> --> 737         raise value
>     738 
>     739 
> 
> InvalidArgumentError: cannot compute Equal as input #0(zero-based) was expected to be a int64 tensor but is a uint8 tensor [Op:Equal]
> ```

An easy workaround it to change the types in y_train and y_test to np.int64.

`import tensorflow as tf
import numpy as np
mnist = tf.keras.datasets.mnist

tf.enable_eager_execution()

(x_train, y_train),(x_test, y_test) = mnist.load_data()
y_train = y_train.astype(np.int64)
y_test = y_test.astype(np.int64)

x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, input_shape=(784,), activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, input_shape=(512,), activation=tf.nn.softmax)
])
model.compile(optimizer=tf.train.AdamOptimizer(),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)`
