### ISSUE TITLE
CudaRoot() during compilation should not be used 

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#23783]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:n/a
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):v1.12.0-0-ga6d8ffae09 1.12.0
- Python version:3.6
- Bazel version (if compiling from source):n/a
- GCC/Compiler version (if compiling from source):n/a
- CUDA/cuDNN version:9.0/7.2
- GPU model and memory:n/a

**Describe the current behavior**
It can be seen from https://github.com/tensorflow/tensorflow/search?q=CudaRoot&unscoped_q=CudaRoot, that the `CudaRoot()` function is used by tensorflow to:

1. Get the path to libdevice library
2. Get the path to ptxas binary 

However, the return value of `CudaRoot()` function is a constant that's determined during compilation.
As a result, tensorflow's XLA cannot work properly, if it is used on a machine where the path to CUDA is different from the compilation machine.

**Describe the expected behavior**

The path to cuda should be dynamically obtained (by configuration or environment variables).

**Code to reproduce the issue**
Using the command in the end of https://medium.com/tensorflow/pushing-the-limits-of-gpu-performance-with-xla-53559db8e473, posted yesterday by @tfboyd .

**Other info / logs**
With XLA, saw errors like:
```
2018-11-15 14:07:40.696214: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:794] Failed to compile ptx to cubin.  Will attempt to let GPU driver compile the ptx. Not found: /usr/local/cuda
-9.0/bin/ptxas not found
```

**Comment by ppwwyyxx** [comment]
Partially addressed by https://github.com/tensorflow/tensorflow/commit/bafb8747983fbcf186ffb063ed39dbb0a18e3c8e, but it's unclear how a user is supposed to use it.

**Comment by hyoo** [comment]
I have a same issue. Can anyone suggest how to inform the new variable to TF code?

**Comment by JainAbhilash** [comment]
Facing similar issues, tried out what @hyoo provided, still didnt work, is there a fix for this?

**Comment by co2e14** [comment]
Is this solved? I'm getting the same issue with it looking at /usr/local/cuda/bin/ptxas instead of where I actually want it to look...

**Comment by pierricklee** [comment]
Same issue, but I encounted it on JAX. I solved by setting two environement variables: 
`export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$PATH"`  
`export XLA_FLAGS='--xla_gpu_cuda_data_dir=/usr/local/cuda/'`
While, you have to point to your cuda path.
After that, run your code as usual:
`python run.py`

**Comment by arnavmehta7** [comment]
I have installed cuda using anaconda, but also have installed locally. What path to put?

**Comment by gowthamkpr** [comment]
@arnavmehta7 This issue is specific to cuda installed locally. If you wanna install it locally, you can follow the instructions mentioned [here](https://github.com/tensorflow/tensorflow/issues/23783#issuecomment-961602522)
