### ISSUE TITLE
tf lite armeabi version is much slower than the nightly aar 

### ISSUE THREAD

**Issue by zjmirving** [tensorflow/tensorflow#23797]
At first I was using  'org.tensorflow:tensorflow-lite:0.0.0-nightly'  aar in my own project. The tf lite model costs 900ms.
      But in my company project, the ndk abiFilters is armeabi.  I changed abiFilters from armeabi-v7a to armeabi. However,  I found the aar not support armeabi.
![image](https://user-images.githubusercontent.com/10142633/48612953-5f35f180-e9c5-11e8-9fde-9faddba7884e.png)
      I compile the armeabi version with the following command, and import so and jar file, but my model costs 4000ms. Is there some wrong with the command ??
bazel build --cxxopt='--std=c++11' //tensorflow/lite/java:tensorflowlite \
--crosstool_top=//external:android/crosstool \
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
--cpu=armeabi

**Comment by aselle** [comment]
@shashishekhar , could you ptal?

**Comment by shashishekhar** [comment]
@zjmirving : You should use -c opt for optimized code.

**Comment by zjmirving** [comment]
> @zjmirving : You should use -c opt for optimized code.

I found an answer in stackoverflow. Is this the reason why the armeabi tf lite  is slow ?
https://stackoverflow.com/questions/7080525/why-use-armeabi-v7a-code-over-armeabi-code

**Comment by shashishekhar** [comment]
@zjmirving : From the original question I gathered that you were using armeabi with Java wrapper and still getting better performance than what you built yourself, in that case right build flags are important.
armeabi-v7a will be better than armeabi

**Comment by FrisaSZ** [comment]
@zjmirving Hi. I'm trying to build tensorflowlite with option --cpu=armeabi, but always fail due to "clang: error: clang frontend command failed with exit code 70". Could you tell me the version of your android sdk and ndk?

**Comment by zjmirving** [comment]
@FrisaSZ ndk is 14, sdk is 26.  I think there is no need to build tensorflowlite with option --cpu=armeabi. Now almost all of the mobiles support armeabi-v7a, you can just assess it.
       String[] abis = new String[]{};
        if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.LOLLIPOP)
        {
            abis = Build.SUPPORTED_ABIS;
        } else {
            abis = new String[]{Build.CPU_ABI,Build.CPU_ABI2};
        }
        for(String abi:abis)
        {
            if(abi.equals("XXX")){
             }
        }
