### ISSUE TITLE
Windows 10 Bazel Build failed 

### ISSUE THREAD

**Issue by Prakash19921206** [tensorflow/tensorflow#23795]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.10
- Python version: 3.5
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): not compiled from source(bazel version: 0.18.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0/7.0
- GPU model and memory: Zotac Gtx 1080ti mini

**Describe the problem**
Build fails with 1 error
initially i tried with cmake, it was giving few errors so started with bazel..no luck since many days! 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
i followed all the steps mentioned [here](https://www.tensorflow.org/install/source) 

`bazel build --copt=-nvcc_options=disable-warnings --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

The reason i'm trying to build from source is because ssd_mobilnet retraining is taking longer than expected (3seconds per step)
resizing of image is happening on cpu and training on gpu.
if both happens on gpu then it should take around half second.

i have attached full build output 
[Build output.txt](https://github.com/tensorflow/tensorflow/files/2588467/Build.output.txt)

i've notived too many `warning LNK4044` in build process

below is the gist of build 

> build --copt=-nvcc_options=disable-warnings --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
> WARNING: Processed legacy workspace file e:\git_projects\tensorflow-experimental\tensorflow/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
> WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
> .
> .
> .
> .
> 
>    Creating library bazel-out/host/bin/tensorflow/cc/ops/image_ops_gen_cc.lib and object bazel-out/host/bin/tensorflow/cc/ops/image_ops_gen_cc.exp
> ERROR: E:/git_projects/tensorflow-experimental/tensorflow/tensorflow/core/kernels/BUILD:2123:1: C++ compilation of rule '//tensorflow/core/kernels:colorspace_op_gpu' failed (Exit 1): msvc_wrapper_for_nvcc.bat failed: error executing command
>   cd C:/users/neuroflares/_bazel_neuroflares/twu4fovw/execroot/org_tensorflow
> .
> .
> .
> .
> 
> 1 error detected in the compilation of "C:/Users/user~1/AppData/Local/Temp/nvcc_inter_files_tmp_dir/colorspace_op_gpu.cu.cpp1.ii".
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> INFO: Elapsed time: 1530.120s, Critical Path: 558.89s
> INFO: 878 processes: 878 local.
> FAILED: Build did NOT complete successfully

What could have gone wrong?
Thanks & Regards

**Comment by andrhua** [comment]
Try bazel 15.0.0 as it [stated](https://www.tensorflow.org/install/source_windows#gpu) to be tested build configuration or cmake. Maybe `bazel clean` before any bazel builds will help.

**Comment by Prakash19921206** [comment]
@andruha, Thanks for your reply.
unfortunately build failed with bazel version 0.15.0 as well!   
infact it failed much early. below is the build output


```
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
...........................................
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
DEBUG: C:/users/user/_bazel_user/twu4fovw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/user/_bazel_user/twu4fovw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/user/_bazel_user/twu4fovw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
DEBUG: C:/users/user/_bazel_user/twu4fovw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/user/_bazel_user/twu4fovw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/user/_bazel_user/twu4fovw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
DEBUG: C:/users/user/_bazel_user/twu4fovw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/user/_bazel_user/twu4fovw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/user/_bazel_user/twu4fovw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
ERROR: E:/git_projects/tensorflow-experimental/tensorflow/tensorflow/tools/pip_package/BUILD:123:1: no such package '@libxsmm_archive//': C:/users/user/_bazel_user/twu4fovw/external/libxsmm_archive/documentation (Directory not empty) and referenced by '//tensorflow/tools/pip_package:licenses'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@libxsmm_archive//': C:/users/user/_bazel_user/twu4fovw/external/libxsmm_archive/documentation (Directory not empty)
INFO: Elapsed time: 784.562s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (74 packages loaded)
    currently loading: @protobuf_archive// ... (2 packages) 
```

i tried msys as well.
it failed with same message as command prompt.

**Comment by andrhua** [comment]
Yeah I'm having tough times to build it for windows too. Considering all gathered information from these several days I think the only way to succeed is to start revert commits and build, as you can see [here](https://github.com/tensorflow/tensorflow#continuous-build-status) now it builds only for Linux and Android

**Comment by Prakash19921206** [comment]
Finally Build succeeded with tensorflow r1.11  (i tried r1.5, 1.9    but they failed)
this time r1.11 build succeeded after 4.5 hours of compilation time! 
before building, when i ran `py config.py` i had turned off `ngraph `support and didn't build with intel `mkl `library

it showed too many warnings while building.. after building the library it showed error when i execute below command 
`bazel-bin\tensorflow\tools\pip_package\build_pip_package C:/tmp/tensorflow_pkg`

first i deleted `simple_console_for_windows.zip`  which was 0 bytes then followed steps mentioned in answer [here ](https://stackoverflow.com/questions/52394305/creating-pip-package-for-tensorflow-with-gpu-support-results-in-0-byte-simple-co/52398168)   [error i was getting is same as asked in question in that link]
finally i got tensorflow .whl file.

i removed the tensorflow which was installed via `pip install tensorflow-gpu `and installed the one that i built.

now again the main problem remains same as asked [here](https://github.com/tensorflow/models/issues/1942)

**Comment by Prakash19921206** [comment]
thought of building r1.12 ,   included everything except RCOM, targeted compute capability 5.0.  yet build failed with below message


```
ERROR: E:/git_projects/tensorflow/tensorflow/compiler/tf2xla/BUILD:97:1: C++ compilation of rule '//tensorflow/compiler/tf2xla:cpu_function_runtime' failed (Exit 2): msvc_wrapper_for_nvcc.bat failed: error executing command
  cd C:/users/neuroflares/_bazel_neuroflares/q6fatijb/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/NeuroFlares/AppData/Local/Programs/Python/Python35/python.exe
    SET PYTHON_LIB_PATH=C:/Users/NeuroFlares/AppData/Local/Programs/Python/Python35/lib/site-packages
    SET TEMP=C:\Users\NEUROF~1\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=5.0
    SET TF_CUDA_VERSION=9.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\NEUROF~1\AppData\Local\Temp
  external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/genfiles /Ibazel-out/x64_windows-opt/bin /Iexternal/nsync /Ibazel-out/x64_windows-opt/genfiles/external/nsync /Ibazel-out/x64_windows-opt/bin/external/nsync /Iexternal/bazel_tools /Ibazel-out/x64_windows-opt/genfiles/external/bazel_tools /Ibazel-out/x64_windows-opt/bin/external/bazel_tools /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/x64_windows-opt/genfiles/external/local_config_sycl /Ibazel-out/x64_windows-opt/bin/external/local_config_sycl /Iexternal/nsync/public /Ibazel-out/x64_windows-opt/genfiles/external/nsync/public /Ibazel-out/x64_windows-opt/bin/external/nsync/public /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /showIncludes /MD /O2 /DNDEBUG -w /arch:AVX /Fobazel-out/x64_windows-opt/bin/tensorflow/compiler/tf2xla/_objs/cpu_function_runtime/cpu_function_runtime.o /c tensorflow/compiler/tf2xla/cpu_function_runtime.cc
.\tensorflow/compiler/tf2xla/cpu_function_runtime.h(71): error C2338:
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 4035.211s, Critical Path: 188.99s
INFO: 3218 processes: 3218 local.
FAILED: Build did NOT complete successfully
```

**Comment by Prakash19921206** [comment]
[someone ](https://stackoverflow.com/questions/52394305/creating-pip-package-for-tensorflow-with-gpu-support-results-in-0-byte-simple-co/52398168?noredirect=1#comment93617530_52398168 )succeeded in building latest release on windows.
so i gave a try with r1.12, started with below command 

`bazel build --define=no_tensorflow_py_deps=true --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

yet build failed with below message



```
ERROR: E:/git_projects/tensorflow/tensorflow/compiler/tf2xla/BUILD:97:1: C++ compilation of rule '//tensorflow/compiler/tf2xla:cpu_function_runtime' failed (Exit 2): msvc_wrapper_for_nvcc.bat failed: error executing command
  cd C:/users/user/_bazel_user/q6fatijb/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/user/AppData/Local/Programs/Python/Python35/python.exe
    SET PYTHON_LIB_PATH=C:/Users/user/AppData/Local/Programs/Python/Python35/lib/site-packages
    SET TEMP=C:\Users\user~1\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=5.0
    SET TF_CUDA_VERSION=9.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\user~1\AppData\Local\Temp
  external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/genfiles /Ibazel-out/x64_windows-opt/bin /Iexternal/nsync /Ibazel-out/x64_windows-opt/genfiles/external/nsync /Ibazel-out/x64_windows-opt/bin/external/nsync /Iexternal/bazel_tools /Ibazel-out/x64_windows-opt/genfiles/external/bazel_tools /Ibazel-out/x64_windows-opt/bin/external/bazel_tools /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/x64_windows-opt/genfiles/external/local_config_sycl /Ibazel-out/x64_windows-opt/bin/external/local_config_sycl /Iexternal/nsync/public /Ibazel-out/x64_windows-opt/genfiles/external/nsync/public /Ibazel-out/x64_windows-opt/bin/external/nsync/public /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /showIncludes /MD /O2 /DNDEBUG -w /arch:AVX /Fobazel-out/x64_windows-opt/bin/tensorflow/compiler/tf2xla/_objs/cpu_function_runtime/cpu_function_runtime.o /c tensorflow/compiler/tf2xla/cpu_function_runtime.cc
.\tensorflow/compiler/tf2xla/cpu_function_runtime.h(71): error C2338:
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 4035.211s, Critical Path: 188.99s
INFO: 3218 processes: 3218 local.
FAILED: Build did NOT complete successfully
```

**Comment by syedm1** [comment]
Release 1.12.0
bazel 0.16.1
turn off winodws defender , bazel clean and stricltly follow these choices during the config 
Do you wish to build TensorFlow with XLA JIT support? [y/N]: n

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: y

Grab a drink and watch! :)

**Comment by Prakash19921206** [comment]
Build succeeded. but probably i'm missing some support library while building, because when i installed the TF that i built, main problem remains same as asked [here](https://github.com/tensorflow/models/issues/1942)

**Comment by ymodak** [comment]
I will close this issue since the build/install related issue is solved which is the subject for this issue. Thanks!

**Comment by racinmat** [comment]
@Prakash19921206  did you build it with XLA JIT or not?

**Comment by CleverCoder** [comment]
After struggling with a ton of issues.. some takeaways:
- Targeting the 1.14 branch...
- Needed to install VS 2017 (community at least) - I had 2019 installed... wasn't good enough. Used procmon to figure this out.
- I couldn't get things to build with the XLA JIT option enabled - after disabling it, the build is still running!!!
- Had to revert to CUDA 10.0 (rather than 10.1) it seems

Google needs to update their build instructions in a SERIOUS way. They are out of date, and given the number of users with NVIDIA cards on WIndows (pretty common), they should put some emphasis on steps needed to build TF with common Intel CPU features enabled (i7's - 8000 series in my case)
