### ISSUE TITLE
Empty input to conv2d causes floating point exception

### ISSUE THREAD

**Issue by hojonathanho** [tensorflow/tensorflow#238]
When empty data is passed into conv2d, the following is displayed, and the program quits:

    Floating point exception (core dumped)

This problem occurs on both Mac (10.9) and Linux (Ubuntu 12.04) in CPU mode (I haven't tried GPU). Here is code that reproduces the problem. 
```python
import numpy as np
import tensorflow as tf

x = tf.placeholder(tf.float32, shape=[None, 28, 28, 1])
conv1_weights = tf.Variable(tf.truncated_normal([5, 5, 1, 32], stddev=0.1))
conv = tf.nn.conv2d(x, conv1_weights, strides=[1, 1, 1, 1], padding='SAME')

with tf.Session() as sess:
    tf.initialize_all_variables().run()
    sess.run([conv], {x: np.empty((0, 28, 28, 1))})
```

**Comment by ebrevdo** [comment]
Can you build from source with the flag "-c dbg" and provide the crash log?

**Comment by vrv** [comment]
I think it's just that the kernel doesn't handle the empty input (e.g., input.NumElements() == 0).

I guess we could check that input or filter are empty, and if so, to produce an empty tensor of the correct shape.

**Comment by vrv** [comment]
We added a simple check here: https://github.com/tensorflow/tensorflow/commit/04f1932f053dd7865b191719b33860270461943a#diff-f9ae051d576c85eab133e77af84c1937R170

Let us know if that doesn't solve the problem (at least for this op -- I'm sure there are others that will pop up).

**Comment by hojonathanho** [comment]
Thanks!
