### ISSUE TITLE
Cannot deploy trained model: google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by spencerkraisler** [tensorflow/tensorflow#23809]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS High Sierra 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.18
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: No GPU

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
When I try to deploy my trained model using this function:
def load_graph(frozen_graph_filename):
	with tf.gfile.GFile(frozen_graph_filename, "rb") as f:
		graph_def = tf.GraphDef()
		graph_def.ParseFromString(f.read())

	with tf.Graph().as_default() as graph:
		tf.import_graph_def(graph_def, name='prefix')
	return graph
I get this error: google.protobuf.message.DecodeError: Error parsing message
at the line that goes:
graph_def.ParseFromString(f.read())

**Describe the expected behavior**
For all my other trained models, this error doesn't pop up, and this method does work. However, this model is one I trained myself. I got it from the export folder the TF Object Detection API made in my folder.

**Code to reproduce the issue**
def load_graph(frozen_graph_filename):
	with tf.gfile.GFile(frozen_graph_filename, "rb") as f:
		graph_def = tf.GraphDef()
		graph_def.ParseFromString(f.read())

	with tf.Graph().as_default() as graph:
		tf.import_graph_def(graph_def, name='prefix')
	return graph

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Traceback (most recent call last):
  File "/Users/spencerkraisler/Desktop/raccoon_tutorial/model_deploy.py", line 27, in <module>
    detection_graph = load_graph(GRAPH_PATH)
  File "/Users/spencerkraisler/Desktop/raccoon_tutorial/model_deploy.py", line 10, in load_graph
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message

**Comment by FredVaugeois** [comment]
Personally, I use this kind of shenanigans to make it work:

def openGraph():
graph = tf.Graph()
graphDef = tf.GraphDef()
with open([path], "rb") as graphFile:
graphDef.ParseFromString(graphFile.read())

with graph.as_default():
tf.import_graph_def(graphDef)

return graph


And then I use this function like this:

graph = openGraph()

with tf.Session(graph=graph) as sess:
blahblahblah




Not much different from you, but maybe creating the graph inside of the function could work? If not, what code are you using to save the graph? It looks like it's litterally an error inside the graph file...

**Comment by frederikschubert** [comment]
This also breaks the [Tensorboard import tool](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/import_pb_to_tensorboard.py) when I try to use it on a model that was trained with [RLlib](https://ray.readthedocs.io/en/latest/rllib.html).

**Comment by anujonthemove** [comment]
I was stuck with a similar error but then I was able to resolve it. Also answered something similar on [stackoverflow](https://stackoverflow.com/questions/49117938/unable-to-use-trained-tensorflow-model/55981972#55981972)

**Comment by mohapatras** [comment]
Here is a solution load the graph. It is working fine.

```
def load_model():
    with tf.gfile.GFile(path, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())

    with tf.Graph().as_default() as graph:
        tf.import_graph_def(graph_def, name="")
    return graph

if __name__=='__main__':
    graph = load_model()
    with tf.Session(graph=graph) as sess:
        for op in graph.get_operations():
            print(op.name)
```
Hope it helps.

**Comment by gadagashwini** [comment]
@spencerkraisler Did you try the solution provided by @mohapatras. Let us know if that helps. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Regilan** [comment]
detection_graph = tf.Graph()
with detection_graph.as_default():
    od_graph_def = tf.compat.v1.GraphDef()
    with tf.io.gfile.GFile(PATH_TO_CRYPT, 'rb') as fid:
        serialized_graph = fid.read()
        od_graph_def.ParseFromString(serialized_graph)
        tf.import_graph_def(od_graph_def, name='')

Hi, I used the same code. But I am getting the following error. I am using TF2.0

DecodeError                               Traceback (most recent call last)
<ipython-input-7-6918b89350a6> in <module>()
     25     with tf.io.gfile.GFile(PATH_TO_CRYPT, 'rb') as fid:
     26         serialized_graph = fid.read()
---> 27         od_graph_def.ParseFromString(serialized_graph)
     28         tf.import_graph_def(od_graph_def, name='')
     29 

DecodeError: Error parsing message

Could anybody help me on this?

**Comment by giangnguyen2412** [comment]
Why there are so many downvotes here? I can not find anything helpful :(

**Comment by jamal-ansary** [comment]
i was using the model from saved_model folder and had the same issue. Get your model from trained_inference_graph folder. it should be sth like: frozen_inference_graph.pb

**Comment by BasicCoder** [comment]
In my case, the protobuffer data that saved by SavedModel API and frozen_graph is different binary formats. You should be careful to use the different save model APIs provided by Tensorflow. According to your descirption, maybe frozen_graph is more suitable way.
You can use two different ways to save [froze_graph()[]:](https://leimao.github.io/blog/Save-Load-Inference-From-TF-Frozen-Graph/)
`# Save check point for graph frozen later
        ckpt_filepath = self.save(directory=directory, filename=filename)
        pbtxt_filename = filename + '.pbtxt'
        pbtxt_filepath = os.path.join(directory, pbtxt_filename)
        pb_filepath = os.path.join(directory, filename + '.pb')
        # This will only save the graph but the variables will not be saved.
        # You have to freeze your model first.
        tf.train.write_graph(graph_or_graph_def=self.sess.graph_def, logdir=directory, name=pbtxt_filename, as_text=True)

        # Freeze graph
        # Method 1
        freeze_graph.freeze_graph(input_graph=pbtxt_filepath, input_saver='', input_binary=False, input_checkpoint=ckpt_filepath, output_node_names='cnn/output', restore_op_name='save/restore_all', filename_tensor_name='save/Const:0', output_graph=pb_filepath, clear_devices=True, initializer_nodes='')
        
        # Method 2
        '''
        graph = tf.get_default_graph()
        input_graph_def = graph.as_graph_def()
        output_node_names = ['cnn/output']

        output_graph_def = graph_util.convert_variables_to_constants(self.sess, input_graph_def, output_node_names)
        # For some models, we would like to remove training nodes
        # output_graph_def = graph_util.remove_training_nodes(output_graph_def, protected_nodes=None)

        with tf.gfile.GFile(pb_filepath, 'wb') as f:
            f.write(output_graph_def.SerializeToString())
        '''`
if you use:
`builder = tf.saved_model.builder.SavedModelBuilder(dump_filepath)` 
to save model, and `graph_def.ParseFromString()` to parse saved model, you will get `google.protobuf.message.DecodeError:Error parsing message`  this Error.

**Comment by no-define** [comment]
if your .pb model came from `tf.export_graph` (which may be convert by onnx), try the way below:
```python
with tf.compat.v1.Session() as sess:
    tf.saved_model.load('/path_to_pb_project',['serve']) 
# tag here may be different ,first time you can run this code with blank tag [ ] ,error report will tell you the tag of metagraph from the path.
```

**Comment by sherigithub** [comment]
> detection_graph = tf.Graph() with detection_graph.as_default(): od_graph_def = tf.compat.v1.GraphDef() with tf.io.gfile.GFile(PATH_TO_CRYPT, 'rb') as fid: serialized_graph = fid.read() od_graph_def.ParseFromString(serialized_graph) tf.import_graph_def(od_graph_def, name='')
> 
> Hi, I used the same code. But I am getting the following error. I am using TF2.0
> 
> DecodeError Traceback (most recent call last) in () 25 with tf.io.gfile.GFile(PATH_TO_CRYPT, 'rb') as fid: 26 serialized_graph = fid.read() ---> 27 od_graph_def.ParseFromString(serialized_graph) 28 tf.import_graph_def(od_graph_def, name='') 29
> 
> DecodeError: Error parsing message
> 
> Could anybody help me on this?

Did you solve this error?
i too had this error in AWS....but works in kaggle with no issues...

how to solve this?????

**Comment by Coder-HHN** [comment]
> if your .pb model came from `tf.export_graph` (which may be converted by onnx), which may be not a frozen_graph, try: 1）use saved_model.loader.load to load **metagraph** 2）get input\output tensor from **signature_def** 3）finally sess.run
> 
> ```python
> sess=tf.compat.v1.Session()
> metagraph=tf.compat.v1.saved_model.loader.load(sess,['serve'],'/path_to_pb_project') 
> # tag here may be different ,first time you can run this code with blank tag [ ] ,error report will tell you the tag of metagraph from the path.
> sig=metagraph.signature_def['serving_default']
> input_dict=dict(sig.inputs)
> output_dict=dict(sig.outputs)
> print(input_dict,'\n',output_dict)
> input_obs_label_0=input_dict['input'].name
> output_stochastic_label_0=output_dict['output'].name
> 
> actual_input={input_obs_label_0:np.random.randn(6,150,224,224)} # fill here with your actual input 
> out=sess.run(output_stochastic_label_0,feed_dict=actual_input)
> print(out)
> ```
> 
> here I use tensorflow2.X also can take the latest saved_model api https://www.tensorflow.org/api_docs/python/tf/saved_model/load if u use tensorflow1.X, the `saved_model.load()` should be `tf.saved_model.loader.load()`

excellent
