### ISSUE TITLE
remove op Save also in remove_training_nodes method

### ISSUE THREAD

**Issue by fumihwh** [tensorflow/tensorflow#23804]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): master branch
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
In current `remove_training_nodes` method, we just remove `CheckNumerics` and `Identity` (conditional).
As `Save` is a training nodes, I think we should remove it also.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
`remove_training_nodes` users.

**Comment by skye** [comment]
I think `remove_training_nodes` is being removed in 2.0, so it might not make sense to update it. @martinwicke do you know what's going on with this?

**Comment by martinwicke** [comment]
Yeah, let's not touch this. In any case, this would be a breaking change, so we'd need a new option, and I don't think this is worth doing.
