### ISSUE TITLE
TFLite:  numeric precision issue in Conv int8 implementation

### ISSUE THREAD

**Issue by jackwish** [tensorflow/tensorflow#23800]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No, but dump the runtime data
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Null
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.11.0 and 1.12.0
- Python version: 3.6
- Bazel version (if compiling from source): 0.16.1
- GCC/Compiler version (if compiling from source): 5.5.0
- CUDA/cuDNN version: No
- GPU model and memory: No

**Describe the current behavior**
When running mobiletnet int8 model, starting from the third Conv(`MobilenetV1/MobilenetV1/Conv2d_2_pointwise/Relu6`), TFLite's output mismatches with another framework.

I looked into it and found that [GetQuantizedConvolutionMultipler()](https://github.com/tensorflow/tensorflow/blob/r1.11/tensorflow/contrib/lite/kernels/kernel_util.cc#L25) generates unexpected results with the calculation `multiplier = input_scale * weight_scale / output_scale`. By *unexpected* I mean the math result is wrong, on my machine at least.

Log example of parameter of `MobilenetV1/MobilenetV1/Conv2d_2_pointwise/Relu6` is as below. Since `input_scale` and `output_scale` are the same, the `real_mulpliter` shall be same as `filter_scale` - more even, these parameters shall be the same for most Conv ops in quantized MobileNetV1.
```conv pre computed args --------------------------
            input scale : 0.023528477177023888
            filter scale : 0.015148180536925793
            output scale : 0.023528477177023888
            real_multiplier: 0.015148180864416702
            output_multiplier: 2081950125
```

**Describe the expected behavior**
Well, the expected behavior is that generates correct result.

**Code to reproduce the issue**
To generates the log in r1.11, try https://github.com/jackwish/tensorflow/tree/d/lite/qconv-r1.11 . Note that, I have already used **[another code style](https://github.com/jackwish/tensorflow/commit/f3677c512ebe06a2dd0dda129ba9ef71de639d87#diff-ca0f46c80fd3cf1f2040be6147a2d8cfR47) such that the output multiplier is correct**.
You can also try [r1.12](https://github.com/jackwish/tensorflow/tree/d/lite/qconv-r1.12) (there is bug in dumping conv outputs here, but the `Prepare()` still has multiplier log).

**Other info / logs**
I was running quantized MobileNetV1  with TFLite on a x86 server. By chance, i noticed that some output of Conv int8 is unexpected. TFLite was invoked through python interfaces, the model comes from [TF model zoo](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md) (the TFLite model inside [MobileNet_v1_1.0_224_quant](http://download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_1.0_224_quant.tgz)). Nothing else special.

Note sure if there is similar behavior on other machine/devices.

**Comment by jackwish** [comment]
I have looked into this a bit further. Far beyond expected, for the *original* multiplier calculation code style and mine, them generates in/correct result for different Conv ops. I have compared them, and list as bellow.
* the indexing of conv starts from 1. Depthwise Conv is ignored (no verification of their result)
* *correct*, means have same multiplier value as my test script, or use any gdb cli.
I am not sure whether the classification accuracy of the network is impacted as I am focus on arithmetic result only.

| which conv | original impl. correct | new impl. correct |
| -------- | -------- | -------- |
| 1     |    yes     |    no     |
| 2     |     no     |    no     |
| 3     |     no     |    yes    |
| 4     |     no     |    yes    |
| 5    |       no     |    no    |
| 6     |     no     |    yes    |
| 7     |     no     |    yes    |
| 8     |     no     |    no     |
| 9     |     no     |    yes    |
| 10    |     no     |    yes    |
| 11    |     no     |    yes    |
| 12   |       no     |    no    |
| 13    |     no     |    yes    |
| 14    |     no     |    yes    |
| 15    |     no     |    no     |

FYI: debug code for [r1.12](https://github.com/jackwish/tensorflow/tree/d/lite/qconv-r1.12) has updated

**Comment by jackwish** [comment]
I think i know what's going on for this issue. Will verify and provide a fix.

**Comment by jackwish** [comment]
PR #24036 addresses Conv's issue. We will look into other precision issue later.

**Comment by suharshs** [comment]
Apologies for the delay, can you describe what you mean by unexpected? What was the result you were getting and what was expected and why?

**Comment by jackwish** [comment]
@suharshs 
> Thanks for the detailed debugging! Apologies for the delay, can you describe what you mean by unexpected? What was the result you were getting and what was expected and why? Specifically, what are you comparing against when you say incorrect/

**expected and unexpected** has been addressed initially in this issue.

**root cause and code**: Check [this code segment](https://github.com/tensorflow/tensorflow/pull/24036/files#diff-ca0f46c80fd3cf1f2040be6147a2d8cfL31) of PR #24036 and you will get it (as we are C++ programmers...).

The code i was looking into is `double product = a * b`, of which `a` and `b` are `float` - the multiplication is in single precision, and casted to double precision.

I assumed that we were expecting a *multiplication in double precision* - as the quantized multiplier is essential.  I was thinking `double product = static_cast<double>(a) * static_cast<double>(b)` is what we want.

**others**
We are working on an internal project which takes TFLite as reference. Sorry that we cannot tell more according to the NDA. Still, the arithmetic issue can be easily reproduced in a tiny  C++ code. And, i have provided test in that PR.

The example of input/output of quantized multiplier function has been given in the **Describe the current behavior** section above and should have been well-described.

Well, since this issue was raised about a month ago, and we have fixed it (pr #24036 ) and turned to some other direction,  we have lost some more-detailed data. Sorry :(

Thank you.

**Comment by suharshs** [comment]
Thanks! I guess I am curious how much of a different in accuracy this was generating for you in your use case if you can share :) Thanks for finding this! Will approve the PR.

**Comment by jackwish** [comment]
> Thanks! I guess I am curious how much of a different in accuracy this was generating for you in your use case if you can share :) Thanks for finding this! Will approve the PR.

You mean the end2end network accuracy? Well, we have not come to that yet. We are basically focus on arithmetic precision currently (though I think our team needs to put more resource on end2end verification... but that's out of my control...).

One interesting part of ML I think is, a software system with better **arithmetic precision** doesn't necessarily mean a better **predication accuracy**. I think you know what i mean... haha :)

**Comment by jackwish** [comment]
Hi there, this numeric precision issue had been fixed by #25302 before. And I notice the fix was reverted in https://github.com/tensorflow/tensorflow/commit/55211a958cc5bb1cf0739c9582f97e0783bf37b4 . May I know why to revert it as there is obvious numeric precision here? If it is because that the numeric eventually impact end2end predicate accuracy, or it is not consistent with TF's implementation (which may also lead to accuracy problem)?

**Comment by suharshs** [comment]
Hi @jackwish , I am so sorry I actually wasn't informed of this getting rolled back internally :(

I dug around and it appears this changed the output values of many model tests, (unclear if it actually impacted accuracy negatively). But since FakeQuant in TF uses float, this change may have caused a meaningful difference, and I think we need more rigorous end2end model accuracy analysis before we move forward. And if we do move forward I think we should resolve this by changing the TFLiteQuantizationParams value to double once and for all rather than performing these localized promotions. 

In particular if we could get the accuracy impact these makes on the released quantized mobilenet v1's that could be a useful data point.

What do you think? 

And again apologies for this getting silently rolled back!

**Comment by jackwish** [comment]
Thank you @suharshs for your reply. I am totally agree with your consideration about the end2end accuracy, which I have not verified yet. And, I think your proposal of *float/double alignment* in TFLite and TF is absolutely the decent solution. All we need is some data. I can work on this, but maybe not that fast - we are lack of some infrastructure :(

Btw, I have a question about the quantization-aware training which I fail to find the answer when looking into detail. As we know, the `contrib.quanize` rewrites the graph by inserting `FakeQuant` ops to where it is needed, and the output of `FakeQuant` is float which has been narrowed to $$[min, max]$$ from float input. This `FakeQuant` float output flows into typical Conv2D (for example) op which is computing in float. So, is the *simulated quantization* forwarding is actually performed in float which has been narrowed to a range that can be represented in INT8?

Thanks.

**Comment by suharshs** [comment]
Yes, the simulated convolution is performed in float with each input and output being effectively "quantized and dequantized".

FakeQuant(x) == Quantize(Dequantize(x))

**Comment by jackwish** [comment]
> Yes, the simulated convolution is performed in float with each input and output being effectively "quantized and dequantized".
> 
> FakeQuant(x) == Quantize(Dequantize(x))

Thank you for the knowledge!
