### ISSUE TITLE
Reduced redundancy in Estimator api

### ISSUE THREAD

**Issue by SumNeuron** [tensorflow/tensorflow#23802]
**System information**
- TensorFlow version (you are using): 1.10+
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**

The TensorFlow estimator api, while a welcomed addition, seems to add a lot of redundancy to the workflow as well as unnecessary complexity. While a prominent goal of the estimator API is to decouple the input pipelines from the model, unfortunately this is not fully realized due to this redundancy and complexity.

# Example

Suppose we wish to make a custom estimator that has an `input_fn` which reads from TF `Record` files via `tf.data.TFRecordDataset(files)` and further, we wish to save our trained model so we can use it later (i.e. we need a `serving_input_reciever_fn`).  

For simplicity lets assume for a single "example" that after our input pipeline we are left with a tensor with shape [2,3], perhaps:

    [[0,0,1],[1,0,0]]

and let us say that contextually we will refer to this feature as "main_input".

Then we now need to wrap this into a `(Sequence)Example` (*NOTE*: see this [S.O. post](https://stackoverflow.com/questions/52035692/tensorflow-v1-10-store-images-as-byte-strings-or-per-channel) for the lack of clarity the documentation provides on how to best do this)

```
# all of input pipeline here

# processed data
main_input = np.array([
    [0, 0, 1],
    [1, 0, 0],
])

# wrap each channel in Feature then wrap all in FeatureList
main_input_feat_list = tf.train.FeatureList(
    feature=[
        tf.train.Feature(float_list=tf.train.FloatList(value=value)) 
        for value in main_input
    ]
)

# wrap in SequenceExample
example = tf.train.SequenceExample(
    context={
        # other stuff could go here
    }, 
    feature_lists=tf.train.FeatureLists(feature_list={
        'main_input': main_input_feat_list,
        # other stuff could go here
    })
)


# write to record
with tf.python_io.TFRecordWriter('demo_example.tfrecord') as writer:
    writer.write(example.SerializeToString())
```

from here, we now need to unwrap this from TF `Record` in our `Estimator`'s `input_fn` using a _different_ api:
```

def parse_record(record):
    return tf.parse_single_sequence_example(
        record, 
        context_features={
            # get context features here
        }, 
        sequence_features={
            'main_input': tf.FixedLenSequenceFeature((3, ), tf.float32), # <---- REDUNDANT
            # get other sequence features here
        }
    )


def input_fn(files:list=['demo_example.tfrecord'], params:dict):
    dataset = tf.data.TFRecordDataset(files).map(lambda record: parse_record(record))
    # reformat dataset to return feature, label pairs
    return dataset


```

Now if we want to use `tf.estimator.BestExporter` we need a `serving_input_receiver_fn` so lets go ahead and get that written:

```
def serving_input_receiver_fn():
    batch_size = None
    main_input = tf.placeholder(tf.float32, (batch_size, 2, 3), name='main_input') # <---- REDUNDANT

   
    features = {'main_input': main_input}
    
    # unclear what the difference is between features and receiver tensors
    receiver_tensors = features
    return  tf.estimator.export.ServingInputReceiver(features, receiver_tensors)


exporter = tf.estimator.BestExporter(
    name='best_exporter', 
    serving_input_receiver_fn= serving_input_receiver_fn,
    exports_to_keep=3
)
```

So while the input pipeline should be decoupled from the model, the model's first layer at the very least is defined by the input. Therefore I should not have to three different times, in three different ways tell TensorFlow what my input features are.

```

        # 1st to write to TF Records 
        feature_lists=tf.train.FeatureLists(feature_list={
            'main_input':  tf.train.FeatureList(
                feature=[
                    tf.train.Feature(float_list=tf.train.FloatList(value=value)) 
                    for value in main_input
                ]
            ),
            # other stuff could go here
        })


        # then to get it out of TF Records with an asymmetric api
        #...
        'main_input': tf.FixedLenSequenceFeature((3, ), tf.float32)
        #...

        # and once more I have to define placeholders for the features in the serving_input_receiver_fn
        main_input = tf.placeholder(tf.float32, (batch_size, 2, 3), name='main_input') # <---- REDUNDANT
        

```

# Proposal to solve

In this [colab](https://colab.research.google.com/drive/1HrSYF1I7rBGaNQ7388Ss3epWPLTloEC6) I demonstrate the fledgling idea of how to solve this, named ["FIO" (Feature Input / Output)](https://pypi.org/project/fio/) whereby instead of having to redefine everything many times over with different apis depending on the case, you can define everything once in a data "schema" e.g.

```
# features here are of an actual example (not batched)
features = {
    'my-feature': 'hi',
    'seq': np.array([
        # ch1, ch2, ch3
        [   1,   1,  1], # element 1
        [   2,   2,  2], # element 2
        [   3,   3,  3], # element 3
        [   4,   5,  6]  # element 4
    ])
}


# here we specify what is needed to encode and decode from `(Sequence)Example` and `TF Records`

SCHEMA = {
    'my-feature': {'length': 'fixed', 'dtype': tf.string,  'shape': []},
    'seq': {
        'length': 'fixed',
        'dtype': tf.int64,
        'shape': [4, 3],
        'encode': 'channels',
        'channel_names': ['A', 'B', 'C'],
        'data_format': 'channels_last'
    }
}
```

then
```

# define our converter
fio = FIO(SCHEMA, etype='example')

# write to example
file = 'example.tfrecord'

example = fio.to_example(features)
with tf.python_io.TFRecordWriter(file) as writer:
    writer.write(example.SerializeToString())

# use a sequence example instead
fio = FIO(SCHEMA, etype='sequence_example', sequence_features=['seq'])
file = 'sequence_example.tfrecord'
with tf.python_io.TFRecordWriter(file) as writer:
    writer.write(example.SerializeToString())

```

where in both cases we can read from records with

```
tf.data.TFRecordDataset(DATASET_FILENAMES).map(lambda r: fio.from_record(r))
```

Thus I propose that TensorFlow add's a new component to the estimator class, which would be the bride between the input pipelines / serving input functions and the `model_fn`. This would be something like the data schema. 

A user can define a data schema instance once and import it into the input pipeline to write their inputs to TF Record, import the same schema into their `Estimator`'s `input_fn` to read from TF `Record`s (or change the TF Record file format slightly so that you do not have define how it should be read, like how I do not have to define the keys in a json file to read a json file) and then once more it can be passed to (or automatically used by the `Estimator`) for the `serving_input_receiver_fn`.  

I believe letting users declaratively, upfront, define what the `Estimator` accepts in terms of data and then not forcing them to, at least trice, re-write what the data is, would be a great simplifier and clean up the `Estimator` api

**Will this change the current api? How?**

Technically, everything "under the hood" could remain the same. The changes would be made to `tf.data` to introduce a `Schema` class which would work as a unifier across the multiple ways of encoding / decoding `tf`/`np` tensors to / from TF Records. In addition, the `Estimator` class would be updated to accept a `tf.data.Schema` instance, from which it would automate the redundancy described above.

**Who will benefit with this feature?**
Anyone who uses the `Estimator` api, anyone who uses `TF Records`, anyone who acknowledges that TensorFlow's documentation is far from complete and examples are needed to bridge how the "high" level apis quite often interface directly with lower (or even the lowest) level apis (e.g. `Estimators` which deal with `Records` or users who want to have an exporter which requires a `ServingInputReceiver`)

**Any Other info.**
Please look at [FIO](https://pypi.org/project/fio/) and generalize this to work as described above.

See these S.O. Posts and their linked Colab's to follow my journey in trying to decipher what should be a high level api, but it turns out to be fairly tethered to lower features.

[optimal way to store tensors at TF Records](https://stackoverflow.com/questions/52035692/tensorflow-v1-10-store-images-as-byte-strings-or-per-channel)

[recovering TF Records](https://stackoverflow.com/questions/52064866/tensorflow-1-10-tfrecorddataset-recovering-tfrecords)

[early stopping](https://stackoverflow.com/questions/52641737/tensorflow-1-10-custom-estimator-early-stopping-with-train-and-evaluate)

[what are serving_input_receiver_fn](https://stackoverflow.com/questions/52874647/tensorflow-v1-10-why-is-an-input-serving-receiver-function-needed-when-checkpoi)

[using an estimator after training](https://stackoverflow.com/questions/53307954/tensorflow-custom-estimator-predict-throwing-value-error)

[defining estimator spec throws error](https://stackoverflow.com/questions/53317235/tensorflow-custom-estimators-defining-estimator-spec-triggers-error)

**Comment by SumNeuron** [comment]
@wt-huang thoughts?

**Comment by SumNeuron** [comment]
@karmel thoughts?

**Comment by karmel** [comment]
In TensorFlow 2.0, we have consolidated and simplified saving/serving logic. Please see https://github.com/tensorflow/community/blob/master/rfcs/20190509-keras-saved-model.md , and specifically [the section on signatures](https://github.com/tensorflow/community/blob/master/rfcs/20190509-keras-saved-model.md#savedmodel-signatures).

**Comment by SumNeuron** [comment]
@karmel I do not see how that is relevant to the redundancy of converting data to Examples, writing to Records, reading from Records, and parsing Records discussed in this issue.

**Comment by karmel** [comment]
It seems that one of the primary endpoints is the ServingInputReceiver, which is being de-emphasized. More broadly, in 2.0, many of these usability issues are resolved using the Keras framework, so we are reticent to change the existing behavior of the Estimator framework. For your purposes, I would recommend hosting the suggested class in your lib, with some added functionality to unwrap and rewrap for passing through estimator.

**Comment by SumNeuron** [comment]
@karmel I understand that the emphasis is to move to TF 2.0..

However, I hope you can also acknowledge why that may not be a sufficient answer.
To my knowledge (and I may very well be wrong), TF 2.0 is still in beta. The key benefits of estimators (e.g. serving and scalable performance), are not fully mirrored in this major release. Further, this is about standardizing the interface of moving data into and out of tf records, which the keras api does not solve.  

Some high level experimental classes like CsvDataset will help in some cases, but there will still be a need for many to work at the example / record level and fixing the inconsistency or at least bolstering the documentation would be in everyone's best interest. 

Consider this StackOverflow question:  https://stackoverflow.com/questions/52035692/tensorflow-v1-10-store-images-as-byte-strings-or-per-channel

There is a multitude of ways of encoding the same tensor into an (Sequence)Example and no where is it stated which way is most optimal for performance, storage, or recovery. Further still, SequenceExample seems to be a superset of the Example functionality (give "context_feature" and "sequence_features"). So it could even be argued to drop Examples all together.

Unless you (TF as an organization) plans on closing of TF Records from the user, then the major release of 2.0 will not solve this issue.

I think, perhaps, this issue could be renamed as "Reduced redundancy in TF (Sequence)Example, TF Records, and parsing thereof".  I initially stated it as relating to the Estimator API as that was the context in which I was using tf records.

**Comment by rmothukuru** [comment]
@SumNeuron,
Sorry for the delayed response. In the **`Tensorflow Version 2.x`**, since we use [TF Keras](https://www.tensorflow.org/api_docs/python/tf/keras) predominantly and don't use [Estimators](https://www.tensorflow.org/guide/estimator) much, can you please let us know if this Feature is still relevant? Thanks!
