### ISSUE TITLE
How to train my dataset(audio samples) in tensorflow ( simple audio recognition).

### ISSUE THREAD

**Issue by vrushalibhokare** [tensorflow/tensorflow#23801]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No , i am using simple audio recognition example 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): https://www.tensorflow.org
- TensorFlow version (use command below):r1.12
- Python version:3.6
- Bazel version (if compiling from source):N.A
- GCC/Compiler version (if compiling from source):N.A
- CUDA/cuDNN version:N.A
- GPU model and memory:N.A

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
When i want to train my own dataset (without url). i already commented --data_url  but i got positional argument error.

**Code to reproduce the issue**
'''
(base) H:\tensorflow-r1.10>python tensorflow/examples/speech_commands/train.py --data_dir=tensorflow/examples/speech_commands/dataset
H:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of
the second argument of issubdtype from `float` to `np.floating` is deprecated. I
n future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/train.py", line 463, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "H:\Anaconda\lib\site-packages\tensorflow\python\platform\app.py", line 1
25, in run
    _sys.exit(main(argv))
  File "tensorflow/examples/speech_commands/train.py", line 107, in main
    FLAGS.testing_percentage, model_settings, FLAGS.summaries_dir)
TypeError: __init__() missing 1 required positional argument: 'summaries_dir'
'''
Where i was wrong and what i needs to do?

**Comment by ymodak** [comment]
The [Simple Audio Recognition](https://www.tensorflow.org/tutorials/sequences/audio_recognition) example  on TensorFlow website works as expected. This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
