### ISSUE TITLE
Build from source r1.12 : tensorflow/tensorflow/contrib/kafka/BUILD:36:1: no such package '@kafka//':

### ISSUE THREAD

**Issue by peterzhang2029** [tensorflow/tensorflow#23817]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.12
- Python version: python2.7.14
- Installed using virtualenv? pip? conda?: source
- Bazel version (if compiling from source): 0.18.0
- GCC/Compiler version (if compiling from source): gcc4.8.5
- CUDA/cuDNN version: cuda9.0
- GPU model and memory: p40 20g

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
./configure
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

After bazel build:
```
WARNING: Duplicate rc file: /home/adamzhangchao/bin/tensorflow/tools/bazel.rc is read multiple times, most recently imported from /home/adamzhangchao/bin/tensorflow/.bazelrc
WARNING: Processed legacy workspace file /home/adamzhangchao/bin/tensorflow/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
DEBUG: /home/adamzhangchao/.cache/bazel/_bazel_adamzhangchao/6492ced5c6ed3f5961e75357254e4c4a/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
ERROR: /home/adamzhangchao/bin/tensorflow/tensorflow/contrib/kafka/BUILD:36:1: no such package '@kafka//': Traceback (most recent call last):
	File "/home/adamzhangchao/bin/tensorflow/third_party/repo.bzl", line 106
		_apply_patch(ctx, ctx.attr.patch_file)
	File "/home/adamzhangchao/bin/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
		fail("patch command is not found, ple...")
patch command is not found, please install it and referenced by '//tensorflow/contrib/kafka:dataset_kernels'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@kafka//': Traceback (most recent call last):
	File "/home/adamzhangchao/bin/tensorflow/third_party/repo.bzl", line 106
		_apply_patch(ctx, ctx.attr.patch_file)
	File "/home/adamzhangchao/bin/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
		fail("patch command is not found, ple...")
patch command is not found, please install it
INFO: Elapsed time: 7.860s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (251 packages loaded)
    currently loading: tensorflow/core/kernels
```

**Comment by leriomaggio** [comment]
Had the same problem on **exactly** the same platform: `centos7`

**Comment by leriomaggio** [comment]
I finally solved this by installing `patch`:

```
sudo yum install patch
```

**Comment by peterzhang2029** [comment]
> I finally solved this by installing `patch`:
> 
> ```
> sudo yum install patch
> ```

Thanks for your advice,  have you met  this error " /home/adamzhangchao/bin/tensorflow/tensorflow/contrib/kafka/BUILD:36:1: no such package '@kafka//': Traceback (most recent call last): " ?

**Comment by gunan** [comment]
@peterzhang2029 that error message is the result of missing `patch` command. Please read the full error message you shared:
```
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@kafka//': Traceback (most recent call last):
	File "/home/adamzhangchao/bin/tensorflow/third_party/repo.bzl", line 106
		_apply_patch(ctx, ctx.attr.patch_file)
	File "/home/adamzhangchao/bin/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
		fail("patch command is not found, ple...")
patch command is not found, please install it
```
It cannot build kafka, because it needs the `patch` command.
