### ISSUE TITLE
Load SavedModel for Estimator API

### ISSUE THREAD

**Issue by SumNeuron** [tensorflow/tensorflow#23824]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.10+
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**

TensorFlow current touts several high level APIs including:

> - Estimators, a high-level API that provides fully-packaged models ready for large-scale training and production.

Focusing on what Estimator's encapsulate:

> Estimators encapsulate the following actions:
> - training
> - evaluation
> - prediction
> - export for serving

there seems to be a glaring omission that straddles prediction and serving.

Where is the import?

Preparing a custom estimator for serving is an arduous journey, so once one has a `saved_model`, it would be nice to be able to load the saved model via the estimator class, rather than the `contrib` module:

```
from tensorflow.contrib import predictor
predict_fn = predictor.from_saved_model('<model-dir>')
```

e.g.

```
est = tf.estimator.Estimator.from_saved_model(model_dir)

# retrain new dataset or whatever, using estimator api rather than SavedModelPredictor
```

perhaps this was left out as it was the goal to only used exported models in the serving context. 

If that is the case, however, then the serving documentation needs critical updates. In addition it (the interface to serving) would benefit from a higher level api centered around estimators rather than any saved model.   

If I have a saved model and it is this easy to predict with it:

```
from tensorflow.contrib import predictor
predict_fn = predictor.from_saved_model('<model-dir>')
predict_fn(<pred_features>)
```

then it should be this easy to get a restful api to my model

```
> tf-serve <model-dir> --host=localhost --port=8000
```

so that I can "GET" my prediction

Now, I could be misinformed. It is very likely I do not understand the tensorflow/serving.git to the fullest and it might very well be that easy. If that is the case, then the documentation needs to be updated to clarify how one can just serve their model. 

**Will this change the current api? How?**

Add a method to the `tf.estimator.Estimator` class `from_saved_model` or `import_saved_model` which allows one to recover the estimator. 

Also if the Estimator API is the high level API that the TF documentation leads me to believe it to be, perhaps make it directly compatible with TF.JS

**Who will benefit with this feature?**

People using the estimator api.

People confused by the obtuse protocol to serve a custom estimator

**Any Other info.**

**Comment by ispirmustafa** [comment]
please check out `tf.contrib.estimator.SavedModelEstimator`

**Comment by ethanyxu** [comment]
Now that `tf.contrib` no longer exist, there is no way of evaluating an estimator from a SavedModel easily. 

`estimator.evaluate()` only takes a `checkpoint_path` argument. However, Estimator does not provide a way to manually save checkpoints.

**Comment by martinmarc** [comment]
> Now that `tf.contrib` no longer exist, there is no way of evaluating an estimator from a SavedModel easily.
> 
> `estimator.evaluate()` only takes a `checkpoint_path` argument. However, Estimator does not provide a way to manually save checkpoints.

Any updates here? As far as my understanding any previously saved estimator model previously using `tf.contrib.estimator.SavedModelEstimator()` is now left out in the cold.

**Comment by tejaslodaya** [comment]
+1 

Any update here would be appreciated! Our models in production are breaking because we're using this in our workflow and recently updated to TF v2
