### ISSUE TITLE
Tensor cpu need cuda?

### ISSUE THREAD

**Issue by pilo21** [tensorflow/tensorflow#23827]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): W7 64 bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 1.12.0
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: not supported by GPU
- GPU model and memory: Geforce GT 330m

**Describe the problem**
i have cpu tensor,couse my video card don't support cuda acceleration.
I have correctly installed tensorflow by pip command,but i got error when import.
some one told me about cuda driver etc,but why i need it if i want use cpu version?
i tryed to use cuda and cudnn,but error persist
i got this error using keras too

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\
tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\
tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper

    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\imp.py", line
243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python36\lib\imp.py", line
343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795
343, in load_dynamic
   

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

**Comment by pilo21** [comment]
i checked and googled all the possibilities,probably is cpu incompatibly with tensors,i downgraded at 1.10.0 and checked the right wheel config.
now seems working but have to test it
my cpu is 720qm (too old)

**Comment by fullarray** [comment]
I see. You will need to invest in a more capable computer in the near future if you want to test newer Tensorflow features.

**Comment by Iamanorange** [comment]
i7-720QM does not support AVX. 
Tensorflow==1.5 is the last (official) version that build w/o AVX.
You can use newer tensorflow by installing a custom build w/o AVX, for example: https://github.com/fo40225/tensorflow-windows-wheel
