### ISSUE TITLE
Event files created by estimator are not closed after training/evaluation

### ISSUE THREAD

**Issue by phil510** [tensorflow/tensorflow#23822]
I'm using the estimator API and a custom implementation of several hyperparameter search methods (random search, hyperband, etc.) to train multiple models and select the best hyperparameters. At the end of the algorithm I would like to delete all the files created during the trainings/evaluations (e.g., the checkpoint files, event files, etc.). I'm trying this with shutil.rmtree; however, I am not able to delete the event files as it appears they are still in use.

Here is an example code - mostly pulled from the Iris example scripts - along with the error to illustrate the issue. The actual code uses a custom estimator implementation instead of the DNNClassifier, but this has the same problem.

```
import tensorflow as tf
import pandas as pd
import os
import shutil

def load_data(y_name='Species'):
    train_url = "http://download.tensorflow.org/data/iris_training.csv"
    test_url = "http://download.tensorflow.org/data/iris_test.csv"

    train_data = pd.read_csv(train_url)
    train_data.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
    test_data = pd.read_csv(test_url)
    test_data.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
    
    train_x = train_data.iloc[:, 0:4]
    train_y = train_data.iloc[:, 4]
    
    test_x = test_data.iloc[:, 0:4]
    test_y = test_data.iloc[:, 4]
    
    return (train_x, train_y), (test_x, test_y)

def train_input_fn(features, labels, batch_size):
    """An input function for training"""
    # Convert the inputs to a Dataset.
    dataset = tf.data.Dataset.from_tensor_slices((dict(features), labels))

    # Shuffle, repeat, and batch the examples.
    dataset = dataset.shuffle(1000).repeat().batch(batch_size)

    # Return the dataset.
    return dataset

def eval_input_fn(features, labels, batch_size):
    """An input function for evaluation or prediction"""
    features=dict(features)
    if labels is None:
        # No labels, use only features.
        inputs = features
    else:
        inputs = (features, labels)

    # Convert the inputs to a Dataset.
    dataset = tf.data.Dataset.from_tensor_slices(inputs)

    # Batch the examples
    assert batch_size is not None, "batch_size must not be None"
    dataset = dataset.batch(batch_size)

    # Return the dataset.
    return dataset

model_dir = os.path.join(os.getcwd(), *['estimator_test', 'test_1'])

(train_x, train_y), (test_x, test_y) = load_data()

# Feature columns describe how to use the input.
my_feature_columns = []
for key in train_x.keys():
    my_feature_columns.append(tf.feature_column.numeric_column(key=key))

# Build 2 hidden layer DNN with 10, 10 units respectively.
classifier = tf.estimator.DNNClassifier(
    feature_columns=my_feature_columns,
    # Two hidden layers of 10 nodes each.
    hidden_units=[10, 10],
    # The model must choose between 3 classes.
    n_classes=3,
    model_dir = model_dir)

# Train the Model.
classifier.train(
    input_fn=lambda: train_input_fn(train_x, train_y, 100),
    steps=100)

# Evaluate the model.
eval_result = classifier.evaluate(
    input_fn=lambda: eval_input_fn(test_x, test_y, 100))

print('\nTest set accuracy: {accuracy:0.3f}\n'.format(**eval_result))

shutil.rmtree(model_dir)
```
Here is the error:
```OSError                                   Traceback (most recent call last)
<ipython-input-40-beccd7cbb56e> in <module>()
----> 1 shutil.rmtree(os.path.join(os.getcwd(), *['estimator_test', 'delete_test_1']))

~\AppData\Local\Continuum\anaconda3\lib\shutil.py in rmtree(path, ignore_errors, onerror)
    492             os.close(fd)
    493     else:
--> 494         return _rmtree_unsafe(path, onerror)
    495 
    496 # Allow introspection of whether or not the hardening against symlink

~\AppData\Local\Continuum\anaconda3\lib\shutil.py in _rmtree_unsafe(path, onerror)
    391         os.rmdir(path)
    392     except OSError:
--> 393         onerror(os.rmdir, path, sys.exc_info())
    394 
    395 # Version using fd-based APIs to protect against races

~\AppData\Local\Continuum\anaconda3\lib\shutil.py in _rmtree_unsafe(path, onerror)
    389                 onerror(os.unlink, fullname, sys.exc_info())
    390     try:
--> 391         os.rmdir(path)
    392     except OSError:
    393         onerror(os.rmdir, path, sys.exc_info())

OSError: [WinError 145] The directory is not empty:
```
I looked at all the files that were open by Python processes, and it's only the event files that are still in use.  I would expect that all files would be closed after training/evaluation are complete. Unfortunately, I cannot find a way to manually close these after training.

On a related note (and this is more of a feature request), it would be great to be able to disable writing summaries in the estimator configuration as the files are pretty large. This would remove the need to delete them after training altogether. 

System information
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.11 (CPU version)
- Python version: 3.6

**Comment by phil510** [comment]
@karmel That's the error, but that's not the underlying issue. rmtree deletes both files and the directory; I believe rmtree first tries to remove all files then deletes the directory. However, the event files are still open, so they cannot be deleted by rmtree. If you check out the files open by the python process, you can see the event files are still open (I did this with psutils).

You can also try to just delete the event file after training in the same script by replacing the last line with os.remove for a specific event file. When I try to delete one of the event files after training, I get this error, which (I believe) is more in line with the underlying issue:
PermissionError: [WinError 5] Access is denied:

Please reopen. Thanks.

**Comment by karmel** [comment]
Re: the feature request in the note above, set both save_summaries_steps and save_summaries_secs to None: 

```
    save_summaries_steps: The frequency, in number of global steps, that the
      summaries are written to disk using a default summary saver. If both
      `save_summaries_steps` and `save_summaries_secs` are set to `None`, then
      the default summary saver isn't used. Default 100.
```

Assigning to @rchao for the file writing issue; presumably the hook is not properly closing the file handles? Not sure if this would be an issue with the summary writer or the hook itself.

**Comment by MajesticKhan** [comment]
This seems to be a windows issue. Furthermore, if you close the python process in windows, the event file is gone assuming that you attempted to delete it and got `PermissionError: [WinError 5] Access is denied:`. 

I tested on linux, and everything ran smoothly.

**Comment by phil510** [comment]
I found a way around this awhile ago, so I thought I'd share in case this is happening to anyone else. Once you are done writing all the summaries, you can clear the file writer cache.

```
cache = tf.summary.FileWriterCache()
cache.clear()
```
After that, I'm able to delete event files and the directory.

**Comment by mohantym** [comment]
Hi @phil510 , The above code in Template is  running with out Error in TF 2.6 through Colab .Attaching [GIST](https://colab.research.google.com/drive/1wmd371wNQMBc6Ixp0rK7Sxt6_8M4JWTG?resourcekey=0-XQ7j7cn1vrpoF3HFZWVmbA#scrollTo=RgiuOY1CL9hm) for reference. Closing this issue as it seems to be resolved in latest version.
