### ISSUE TITLE
When tf.Session(), got error cuDevicePrimaryCtxRetain: CUDA_ERROR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by lightning20** [tensorflow/tensorflow#23820]
When try to create session by tf.Session(), it gave error as below. Not sure how to solve it.

Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.Session()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eliyart/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1511, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/eliyart/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 634, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_NOT_SUPPORTED: operation not supported

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|=====+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   27C    P8    27W / 149W |     16MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|==============================================|
|    0      2075      G   /usr/lib/xorg/Xorg                             9MiB |
|    0      2128      G   /usr/bin/gnome-shell                           6MiB |
+-----------------------------------------------------------------------------+

Any suggestion, thanks. 
alex

**Comment by harshini-gadige** [comment]
Could you please check if [this ](https://stackoverflow.com/questions/41965187/nvidia-device-error-in-tensorflow)helps.

**Comment by FredVaugeois** [comment]
Have you actually installed CUDA/cuDNN following these guides ([1](https://www.tensorflow.org/install/pip), [2](https://www.tensorflow.org/install/gpu))? Also, make sure to use CUDA 9.0 and cuDNN 7.1.4 or cuDNN 7.3.1 for it to work properly...

**Comment by harshini-gadige** [comment]
Closing as this issue is in "awaiting response" status for more than 7 days and did not hear back from the user. Please post your comments if any, we will reopen. Thanks !
