### ISSUE TITLE
Some confusion about Gather OP implement

### ISSUE THREAD

**Issue by candyzone** [tensorflow/tensorflow#23845]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/gather_functor.h#L137
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/gather_functor.h#L139

In TensorFlow master branch, gather_functor::GatherFunctorCPU template specialization when slice_size==10 or slice_size==20, why this two magic number?

**Comment by candyzone** [comment]
@ebrevdo @harshini-gadige please assign to other tensorflower

**Comment by Saduf2019** [comment]
@candyzone 
Could you please try on latest stable version of tf and let us know if this is still an issue.Thanks!

**Comment by Saduf2019** [comment]
Moving this to closed status due to lack of activity.
