### ISSUE TITLE
Run time GPU resources allocation in Tensorflow

### ISSUE THREAD

**Issue by Akhtar303nu** [tensorflow/tensorflow#23842]
Hi
I have developed a model which is  Real time vehicle and person detection using tensor flow as back end in python and have  ten jobs (ten video feed from different cctv camera ) or more than that at run time some time jobs are more than ten or less than ten  jobs ,I want to run ten  jobs at a same time on one  gpu(GT X 1080 memory 8118MiB) using tensor flow  but if i have ten jobs then GPU resources equally distribute to every jobs and if jobs are five then resource equally distributed to five jobs i.e run time GPU resources allocation on the basis of number of available jobs(may be more than ten jobs or less than ten jobs) like cpu use its intelligence when one job/process complete then it release resources and cpu assign these resources to other process so  I want to utilize my whole resources of my GPU at every time
suggest me any approach
Thanks

**Comment by harshini-gadige** [comment]
We encourage to post these type of questions on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
