### ISSUE TITLE
Object detection example for TFLite

### ISSUE THREAD

**Issue by SiddhantKapil** [tensorflow/tensorflow#23848]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12.0
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
I want to add an example for converting an object detection model say, ssd_mobilenet_v1 to TFLite. The code will have a Makefile for setting up everything and a jupyter notebook for showing step by step procedure for conversion.
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
I see that a lot of people ask questions around this as they don't follow the correct procedure. Even I have invested a lot of time in it and I think that a working example can help them in saving a lot of time.
**Any Other info.**
After that, I can even write script for running it on Raspberry Pi 3.

**Comment by SiddhantKapil** [comment]
Hi @aselle, I want your views on this. Will it be a good idea or not?

**Comment by tmm1** [comment]
👍 would like to see this

**Comment by jdduke** [comment]
We have several tutorials for object detection @ https://www.tensorflow.org/lite/models/object_detection/overview.
