### ISSUE TITLE
Error in running pre-compiled binary on tensorflow

### ISSUE THREAD

**Issue by HackersSpirit** [tensorflow/tensorflow#23851]
System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (64-bit)
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
TensorFlow installed from (source or binary): Source
TensorFlow version:1.7 - 1.9
Python version:3.6
Installed using virtualenv? pip? conda?: Git
Bazel version (if compiling from source):No
GCC/Compiler version (if compiling from source): CMake : 3.10.1
CUDA/cuDNN version: No
GPU model and memory: No
Describe the problem
I am trying to run the pre-compiled tensor flow binaries and run the tensorflow example.
I know the support for cmake have been depreciated but i am using  an old version of tensorflow
so need some help in regards.

Provide the exact sequence of commands / steps that you executed before running into the problem
1. Downloading the pre-compiled binary for windows.
2. Included the project in qt-creator
3. Build the project

Any other info / logs:
main.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl tensorflow::ConfigProto::~ConfigProto(void)" (??1ConfigProto@tensorflow@@UEAA@XZ) referenced in function "public: __cdecl tensorflow::SessionOptions::~SessionOptions(void)" (??1SessionOptions@tensorflow@@QEAA@XZ)
main.obj : error LNK2019: unresolved external symbol "public: __cdecl tensorflow::SessionOptions::SessionOptions(void)" (??0SessionOptions@tensorflow@@QEAA@XZ) referenced in function main
main.obj : error LNK2019: unresolved external symbol "class tensorflow::Status __cdecl tensorflow::NewSession(struct tensorflow::SessionOptions const &,class tensorflow::Session * *)" (?NewSession@tensorflow@@YA?AVStatus@1@AEBUSessionOptions@1@PEAPEAVSession@1@@Z) referenced in function main
debug\tensorflowcppNew.exe : fatal error LNK1120: 4 unresolved externals

**Comment by ymodak** [comment]
The standard Python binaries exist only for Python 3.5. Please take a look at [TensorFlow CMake build](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake#tensorflow-cmake-build) to know more.

**Comment by gunan** [comment]
@asimshankar knows more about the c++ libraries.

**Comment by asimshankar** [comment]
Unfortunately, I am not familiar with qt-creator or Windows development enough to provide any useful thoughts here. A cursory look at the error messages suggest that somehow your project isn't linking against the TensorFlow C libraries (`tensorflow.dll` on Windows).

That said, I'm confused about the exact setup here -  how did you install TensorFlow (pip / conda / something else?)? In the questionnaire above, the answer is "git".

Marking as "Community Support" in case other Windows users who use qt-creator can chime in.

**Comment by HackersSpirit** [comment]
@asimshankar : In qt creator you can specify the compiler to use so i am using MSVC compiler.
It's similar using visual studio.
I was able to run the binary build using sse2. The problem is arising with avx2 which i am currently 
trying to figure out.
