### ISSUE TITLE
Tf Lite only support 4D(or less) tensors stack op?

### ISSUE THREAD

**Issue by PK15946** [tensorflow/tensorflow#23855]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, that is a custom model
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):1.12-gpu
- Python version:3.6
- Bazel version (if compiling from source):0.19
- GCC/Compiler version (if compiling from source):5.4
- CUDA/cuDNN version:9.0/7.3.1
- GPU model and memory:GTX 1080 ti

**Describe the current behavior**
I created a custom TensorFlow model and converted it tflite with 
`converter = tf.lite.TFLiteConverter.from_session(sess, [img], [out])`
`tflite_model = converter.convert()`
`open("converted_model.tflite", "wb").write(tflite_model).`
The process was fine. Then I tried to test the file with interpreter. But when I run
`interpreter = tf.lite.Interpreter(model_path="converted_model.tflite")`
 `interpreter.allocate_tensors()`
I get the following runtime error:
`tensorflow/contrib/lite/kernels/pack.cc:38 NumDimensions(input0) < 4 was not true.Node number 14 (PACK) failed to prepare.`

**Code to reproduce the issue**
`z = tf.stack([x, y], axis=3), where x and y both are 4D tensor.` 
What can I do to get the interpreter run? Any help will be appreciated.

**Comment by liyunlu0618** [comment]
Closing for now. Feel free to reopen if you run into any issue.

**Comment by CodingMice** [comment]
I meet the same problem in Tensorflow 1.13.1 (Python2.7), how to fix it...

**Comment by PK15946** [comment]
My case is a bit special, 5D is just a temporary tensor, So I sacrifice the
batch dim because it is 1.
CodingMice <notifications@github.com> 于 2019年6月11日周二 下午7:47写道：

**Comment by CodingMice** [comment]
OK, I have solved it with two tf.reshape. It works though it adds additional ops, thank you
