### ISSUE TITLE
Hard to understand error message 

### ISSUE THREAD

**Issue by ushnish** [tensorflow/tensorflow#2385]
x is a list of list of tensors, and im passing in one list at a time to the rnn but I get this hard to understand error message
 
Traceback (most recent call last):
  File "autoencoder_m.py", line 60, in <module>
    outputs, state = rnn.rnn(cell=dropout_cell, inputs = x[i], initial_state=initial_state, sequence_length=s[i], scope = scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 127, in rnn
    array_ops.pack([batch_size, cell.output_size]), inputs[0].dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 241, in pack
    return gen_array_ops._pack(values, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 916, in _pack
    return _op_def_lib.apply_op("Pack", values=values, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 379, in apply_op
    assert dtype is not None, "Should not fail if dtype is None"
**AssertionError: Should not fail if dtype is None**

Does this mean that x[i][0] is of type None? I already checked that it is `<dtype: 'float32'>`

This is the code I am trying to run, basically trying to run rnn on multiple gpu in the following manner.

```
x = [[tf.placeholder(tf.float32, shape=[batch_size, input_width]) for _ in xrange(max_sequence_length)] for _ in xrange(num_gpu)]
y = [[tf.placeholder(tf.float32, shape=[batch_size, input_width]) for _ in xrange(max_sequence_length)] for _ in xrange(num_gpu)]
s = [tf.placeholder(tf.int32, shape=[batch_size]) for _ in xrange(num_gpu)]
cell = BasicLSTMCell(num_units = hidden_neurons, input_size = [batch_size, input_width])
initial_state = tf.zeros([batch_size, hidden_neurons * 2]) 
dropout_cell = DropoutWrapper(cell, input_keep_prob=0.9, output_keep_prob=1.0)
initial_state = tf.zeros([batch_size, cell.state_size])

gpu_grads = []  
losses = []
opt = tf.train.AdamOptimizer(learning_rate=1e-4, beta1=0.99, beta2=0.97)

for i in xrange(num_gpu):
        gpu_id = '/gpu:'+str(i)
        with tf.device(gpu_id), tf.name_scope(gpu_id) as scope:
                print x[i][0].dtype
                outputs, state = rnn.rnn(cell=dropout_cell, inputs = x[i], initial_state=initial_state, sequence_length=s[i], scope = scope)
```

After this I get average of gradients similar to cifar10 multi gpu tutorial example.

**Comment by mrry** [comment]
This looks like a bad error message. Can you try printing the dtypes of all elements in `x`? My guess is that they have incompatible types....

**Comment by ushnish** [comment]
Thank you for your response. All the dtypes in x appear to be `<dtype: 'float32'>`.

Maybe I'm not doing this the right way, and you can point me in the right direction. Is there something obviously wrong with how I am trying to run rnn on multiple GPU, using the param server paradigm? I'm happy to provide more code if that helps.

**Comment by ushnish** [comment]
@mrry Do you have any idea what can raise this error? It's not the input dtypes themselves

**Comment by mrry** [comment]
The most likely culprit is an invalid value in the list - e.g. one that cannot be converted to a tensor. I'm about to submit a change that will improve the error message here, so it should help to discover the real problem.

**Comment by ushnish** [comment]
Well this is how I am creating the placeholders now.

`x1 = []
x2 = []

y1 = []
y2 = []

for _ in xrange(max_sequence_length):
        with tf.device('/gpu:0'):
                x = tf.placeholder(tf.float32, shape=[batch_size, input_width])
                x1.append(x)
                y = tf.placeholder(tf.float32, shape=[batch_size, input_width])                                                                                                
                y1.append(y)                                                                                                                                                   
        with tf.device('/gpu:1'):                                                                                                                                              
                x = tf.placeholder(tf.float32, shape=[batch_size, input_width])                                                                                                
                x2.append(x)                                                                                                                                                   
                y = tf.placeholder(tf.float32, shape=[batch_size, input_width])                                                                                                
                y2.append(y)                                                                                                                                                   
                                                                                                                                                                               
                                                                                                                                                                               
with tf.device('/gpu:0'):                                                                                                                                                      
                s1 = tf.placeholder(tf.int32, shape=[batch_size])                                                                                                              
                                                                                                                                                                               
                cell1 = BasicLSTMCell(num_units = hidden_neurons, input_size = [batch_size, input_width])                                                                      
                initial_state1 = tf.zeros([batch_size, hidden_neurons * 2], name = 'initial_state1')                                                                           
                                                                                                                                                                               
                with tf.name_scope('/gpu:0') as scope:                                                                                                                         
                        outputs1, state1 = rnn.rnn(cell=cell1, inputs = x1, initial_state=initial_state1, sequence_length=s1, scope = scope)`

**Comment by mrry** [comment]
Looking closer at the exception backtrace, it is failing on [this line](https://github.com/tensorflow/tensorflow/blob/449d122b46d6e7fa2deba151356ffda200d1be7c/tensorflow/python/ops/rnn.py#L128) in `rnn.py`:

```python
array_ops.pack([batch_size, cell.output_size]), inputs[0].dtype)
```

This suggests that either `batch_size` or `cell.output_size` has the wrong type. With the forthcoming change it will be easier to tell which one of these is incorrect, but perhaps you can add some debugging code to find out?

**Comment by ushnish** [comment]
Both of these are `<type 'int'>`, and both have value 32 (I have batch size 32 and so is the number of neurons in my LSTM cell). Should they be some other type?
