### ISSUE TITLE
Error using Estimator export_saved_model (Not found: Key global_step not found in checkpoint)

### ISSUE THREAD

**Issue by burhanbvk** [tensorflow/tensorflow#23854]
Hello,

I am trying to prepare a pre-trained model for google cloud ML. I am trying to use an estimator to export the model. During the loading of the checkpoints by the estimator I get the following error:

```
2018-11-19 13:28:57.526564: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key global_step not found in checkpoint
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key global_step not found in checkpoint
         [[{{node save_1/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]
```

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.12.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Tesla K80

**Code to reproduce the issue**

```
MODEL_DIR='model/'
def decode_image(image_bytes):
    image = tf.image.decode_image(image_bytes)
    image = tf.cast(image, dtype=tf.uint8)
    return image

def serving_input_fn():
    createmodel()
    inputs = {'image_bytes': tf.placeholder(tf.string, shape=(), name="image_bytes")}
    imagebytes = tf.squeeze(inputs['image_bytes']) # make it a scalar
    image = decode_image(imagebytes)
    # make the outer dimension unknown (and not 1)
    image = tf.placeholder_with_default(image, shape=[None, None, None, 3])

    features = {'image_bytes' : image}
    return tf.estimator.export.ServingInputReceiver(features, inputs)

def model_fn(features, labels, mode, params):
    pred = tf.get_default_graph().get_tensor_by_name("fc1_voc12:0")
    return tf.estimator.EstimatorSpec(
        mode=tf.estimator.ModeKeys.PREDICT,
        predictions=pred,
        export_outputs={'pred':tf.estimator.export.PredictOutput(pred)}
        )

estimator = tf.estimator.Estimator(
    model_fn=model_fn,
    model_dir=MODEL_DIR)

estimator.export_savedmodel('deployment_gcp_1', serving_input_fn, strip_default_attrs=True)
```

I have searched this issue quite a bit. There was one bug report for an older version of tensorflow (I think 1.2.0 but I am not sure now). I am able to load and save this model using tf.saved_model.simple_save, and it works when I run predictions on it.

I am not sure if this is a bug or if I am missing something really simple.

**Comment by burhanbvk** [comment]
I have tried the same script on a linux machine, with python2.7, tensorflow 1.4.0 and no longer receive the error. This appears to be a bug, maybe in newer versions of tensorflow or python3.6 and windows.

**Comment by burhanbvk** [comment]
I did some more work on this and the issue appeared on tensorflow 1.4 as well. I managed to work around the issue by loading the chexkpoint, adding a variable named global_step and then exporting it again. Once I did that I was able to use my original code without this error.

**Comment by harshini-gadige** [comment]
@burhanbvk  Glad to know that your issue is resolved.

**Comment by ispirmustafa** [comment]
@harshini-gadige please note that Karmel is the current owner of Estimators for your future references.

**Comment by ispirmustafa** [comment]
@harshini-gadige please let me know where I can find the sheet. I'll update it.
