### ISSUE TITLE
Document about using custom op to build graph in C++

### ISSUE THREAD

**Issue by egolearner** [tensorflow/tensorflow#23867]
**System information**
- TensorFlow version: ALL
- Doc Link: 
Custom op: https://www.tensorflow.org/guide/extend/op
Build graph in c++: https://www.tensorflow.org/guide/extend/cc

**Describe the documentation issue**
Please provide documentation about how to build graph using custom OP.
Related StackOverflow question: https://stackoverflow.com/questions/53384454/how-to-use-custom-op-to-build-tensorflow-graph-in-c

**Comment by dynamicwebpaige** [comment]
Borrowing from the [StackOverflow post linked above](https://stackoverflow.com/questions/53384454/how-to-use-custom-op-to-build-tensorflow-graph-in-c)...

Taking `ZeroOut` from [here](https://www.tensorflow.org/guide/extend/op) as an example, you have to do the following:

```
    class ZeroOut {
     public:
      ZeroOut(const ::tensorflow::Scope& scope, ::tensorflow::Input x);
      operator ::tensorflow::Output() const { return y; }
      operator ::tensorflow::Input() const { return y; }
      ::tensorflow::Node* node() const { return y.node(); }
    
      ::tensorflow::Output y;
    };
    
    ZeroOut::ZeroOut(const ::tensorflow::Scope& scope, ::tensorflow::Input x) {
      if (!scope.ok()) return;
      auto _x = ::tensorflow::ops::AsNodeOut(scope, x);
      if (!scope.ok()) return;
      ::tensorflow::Node* ret;
      const auto unique_name = scope.GetUniqueNameForOp("ZeroOut");
      auto builder = ::tensorflow::NodeBuilder(unique_name, "ZeroOut")
                         .Input(_x)
      ;
      scope.UpdateBuilder(&builder);
      scope.UpdateStatus(builder.Finalize(scope.graph(), &ret));
      if (!scope.ok()) return;
      scope.UpdateStatus(scope.DoShapeInference(ret));
      this -> y = Output(ret, 0);
    }
```

Then you can use it to build a graph:

```
    Scope root = Scope::NewRootScope();

    // Matrix A = [3 2; -1 0]
    auto A = Const(root, { {3, 2}, {-1, 0} });
    auto v = ZeroOut(root.WithOpName("v"), A);
    std::vector<Tensor> outputs;
    ClientSession session(root);

    // Run and fetch v
    TF_CHECK_OK(session.Run({v}, &outputs));
    LOG(INFO) << outputs[0].matrix<int>();
```

**Note**: For TensorFlow inherent ops, code like `ZeroOut class` is autogenerated by a bazel rule. You can imitate that code (e.g. `tensorflow/cc/ops/math_ops.h`) to hand write your own classes, if you only have a few custom ops.

**Comment by rmothukuru** [comment]
@egolearner,
The documentation for Creating a Custom OP is present in the [Tensorflow Site](https://www.tensorflow.org/guide/create_op). Also refer this [Github page](https://github.com/tensorflow/custom-op) for end-to-end code example, as well as Docker images for building and distributing your custom ops. Thanks!
