### ISSUE TITLE
1 error detected in the compilation of "C:/Users/dorp/AppData/Local/Temp/nvcc_in ter_files_tmp_dir/reduce_slice_ops_gpu.cu.compute_70.cpp1.ii".

### ISSUE THREAD

**Issue by dorp92** [tensorflow/tensorflow#23879]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.11/1.12
- Python version:2.6
- Bazel version (if compiling from source):1.18
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:9/9.2
- GPU model and memory:gtx1070 8gb

Used the command:

> C:\Users\dorp\Desktop\tensorflow-1.11.0>bazel build --config=opt --config=cuda -
-define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_pack
age

And got the error
> 1 error detected in the compilation of "C:/Users/dorp/AppData/Local/Temp/nvcc_in
ter_files_tmp_dir/reduce_slice_ops_gpu.cu.compute_70.cpp1.ii".
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 285.274s, Critical Path: 58.63s
INFO: 1550 processes: 1550 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by harshini-gadige** [comment]
@dorp92  Please try wih Bazel 0.15 and CUDA 9, cuDNN 7

**Comment by harshini-gadige** [comment]
Closing as this issue is in "awaiting response" status and did not hear back from the user for more than 7 days. Please post your comments if any, we will reopen. Thanks !

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
