### ISSUE TITLE
In implementation of ConvLSTM,I  want to know where is the w_ci dot C_t-1 in paper formula (3)

### ISSUE THREAD

**Issue by TolicWang** [tensorflow/tensorflow#23870]
```

  def call(self, inputs, state, scope=None):
    cell, hidden = state
    new_hidden = _conv([inputs, hidden], self._kernel_shape,
                       4 * self._output_channels, self._use_bias)
    gates = array_ops.split(
        value=new_hidden, num_or_size_splits=4, axis=self._conv_ndims + 1)

    input_gate, new_input, forget_gate, output_gate = gates
    new_cell = math_ops.sigmoid(forget_gate + self._forget_bias) * cell
    new_cell += math_ops.sigmoid(input_gate) * math_ops.tanh(new_input)
    output = math_ops.tanh(new_cell) * math_ops.sigmoid(output_gate)

    if self._skip_connection:
      output = array_ops.concat([output, inputs], axis=-1)
    new_state = rnn_cell_impl.LSTMStateTuple(new_cell, output)
return output, new_state
```

In this implementation, I wonder where is  w_ci dot C_t-1 appearing in paper formula (3)

**Comment by TolicWang** [comment]
The function `def call()` is the main part implemetation of paper:https://arxiv.org/pdf/1506.04214v1.pdf. But a problem now confused me is that in the main part implementation `w_ci dot C_t-1` has disappeared while it appears in paper formula (3).  Why?

**Comment by drpngx** [comment]
I'm not sure what you mean. The convolution is wrapped into the `_conv` function in that file.

**Comment by TolicWang** [comment]
I wanna say if the implementation of ConvLSTM is based on the LSTM  not the FC-LSTM mentioned in (Convolutional LSTM Network: A Machine Learning Approach for Precipitation Nowcasting).
Because i cannt find the 'peepholes' step in ConvLSTM.

**Comment by mohantym** [comment]
Hi @TolicWang ,Is the issue still replicating in Tensorflow latest Versions ?
As 1.x versions  of Tensorflow has been considered officially considered as end of life, We recommend that you upgrade to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!
