### ISSUE TITLE
DCGAN implementation differs between GitHub and Colab

### ISSUE THREAD

**Issue by mr-ubik** [tensorflow/tensorflow#23875]
There's a difference between the [DCGAN](https://github.com/tensorflow/tensorflow/blob/r1.11/tensorflow/contrib/eager/python/examples/generative_examples/dcgan.ipynb) implementation present on GitHub and the one present in Colab.
Also, they both suffer the same problem as #19643 #23873

**Comment by rthadur** [comment]
This is no longer a issue, as contrib folder has been removed.Thank you
