### ISSUE TITLE
Documentation on fault tolerance in distributed tensorflow

### ISSUE THREAD

**Issue by alkhaled** [tensorflow/tensorflow#2387]
Hi,

I know the white paper describes how Tensorflow handles failures in distributed execution, but the docs for open source tensorflow (specifically: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/distributed/index.md) don't really explain what to expect if a machine goes down in a cluster. It would be nice to know:

1. What the expected behavior is if a machine fails.
2. If it's possible to add a new machine to the cluster if one fails.

Thanks!
Sulaiman

**Comment by girving** [comment]
This type of question is better asked on StackOverflow, since it isn't about an improvement or bug fix to TensorFlow itself.
