### ISSUE TITLE
SparseTensor multiplication in tf.keras.layers.Dense

### ISSUE THREAD

**Issue by sfujiwara** [tensorflow/tensorflow#23872]
**System information**
- TensorFlow version (you are using): 1.12.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
In `keras.layers.Dense`, `tf.sparse_tensor_dense_matmul` is called for SparseTensor as [this](https://github.com/keras-team/keras/blob/master/keras/backend/tensorflow_backend.py#L1093-L1094).
But in `tf.keras`, only `tf.tensordot` (which can not treats SparseTensor) is called as [this](https://github.com/tensorflow/tensorflow/blob/f827bad24efc949e657e141464ea1010c18d812c/tensorflow/python/keras/layers/core.py#L955-L972).

Do you have any plan to treat SparseTensor in `tf.keras`?

**Will this change the current api? How?**
We can fix it simply using `tf.sparse_tensor_dense_matmul`.
If needed, I can create PR.

**Comment by ymodak** [comment]
I believe we have this feature now in TF [tf.sparse.sparse_dense_matmul](https://www.tensorflow.org/api_docs/python/tf/sparse/sparse_dense_matmul). Please reopen if that's not the case. Thanks!
