### ISSUE TITLE
tensorflow1.8 cuda 9.0 cuDNN ubuntu16.04 install wrong

### ISSUE THREAD

**Issue by banbsyip** [tensorflow/tensorflow#23881]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:1.8.0-gpu
- Python version:3.5.2
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):4.4
- CUDA/cuDNN version:9/7
- GPU model and memory:1050 Ti  4g

when i used python to import tensorflow as tf ,there is a problem :ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory. but when i searched the file in the /usr/local/cuda/lib64, there existed a file named libcusolver.so.9.0.

**Comment by harshini-gadige** [comment]
@banbsyip  Request you to use tensorflow 1.11 or 1.12.

**Comment by banbsyip** [comment]
> @banbsyip We encourage users to stay with the two latest versions of TF. Please use tensorflow 1.11 or 1.12. This issue would not occur with these versions.

i run a project with pycharm, it could work,then i uninstall the tensorflow1.8 and installed TensorFlow1.12, the same wrong came again,but i could run the project with pycharm yesterday night. this morning i run the project but failed, it shows taht  "Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above." the detail as fllow:


Using TensorFlow backend.
2018-11-21 09:16:41.195484: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-11-21 09:16:41.195534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-21 09:16:41.195539: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2018-11-21 09:16:41.195543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2018-11-21 09:16:41.195656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3638 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-11-21 09:16:52.238761: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2018-11-21 09:16:52.241850: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
     [[{{node conv1_1/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1_1/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, conv1_1/weights/read)]]
     [[{{node rois/Reshape/_97}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_587_rois/Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cq/桌面/chinese_ocr-master/demo.py", line 21, in <module>
    result, image_framed = ocr.model(image)
  File "/home/cq/桌面/chinese_ocr-master/ocr.py", line 83, in model
    text_recs, img_framed, img = text_detect(img)
  File "/home/cq/桌面/chinese_ocr-master/ctpn/text_detect.py", line 90, in text_detect
    scores, boxes, img, scale = ctpn(img)
  File "/home/cq/桌面/chinese_ocr-master/ctpn/text_detect.py", line 52, in ctpn
    scores, boxes = test_ctpn(sess, net, img)
  File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/fast_rcnn/test.py", line 51, in test_ctpn
    rois = sess.run([net.get_output('rois')[0]],feed_dict=feed_dict)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
     [[node conv1_1/Conv2D (defined at /home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/network.py:167)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1_1/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, conv1_1/weights/read)]]
     [[{{node rois/Reshape/_97}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_587_rois/Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'conv1_1/Conv2D', defined at:
  File "/home/cq/桌面/chinese_ocr-master/demo.py", line 3, in <module>
    import ocr
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/cq/桌面/chinese_ocr-master/ocr.py", line 10, in <module>
    from ctpn.text_detect import text_detect
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/cq/桌面/chinese_ocr-master/ctpn/text_detect.py", line 45, in <module>
    sess, net = load_tf_model()
  File "/home/cq/桌面/chinese_ocr-master/ctpn/text_detect.py", line 30, in load_tf_model
    net = get_network("VGGnet_test")
  File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/factory.py", line 8, in get_network
    return VGGnet_test()
  File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/VGGnet_test.py", line 14, in __init__
    self.setup()
  File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/VGGnet_test.py", line 21, in setup
    .conv(3, 3, 64, 1, 1, name='conv1_1')
  File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/network.py", line 23, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/network.py", line 176, in conv
    conv = convolve(input, kernel)
  File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/network.py", line 167, in <lambda>
    convolve = lambda i, k: tf.nn.conv2d(i, k, [1, s_h, s_w, 1], padding=padding)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 957, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
     [[node conv1_1/Conv2D (defined at /home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/network.py:167)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1_1/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, conv1_1/weights/read)]]
     [[{{node rois/Reshape/_97}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_587_rois/Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by banbsyip** [comment]
> > @banbsyip We encourage users to stay with the two latest versions of TF. Please use tensorflow 1.11 or 1.12. This issue would not occur with these versions.
> 
> i run a project with pycharm, it could work,then i uninstall the tensorflow1.8 and installed TensorFlow1.12, the same wrong came again,but i could run the project with pycharm yesterday night. this morning i run the project but failed, it shows taht "Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above." the detail as fllow:
> 
> Using TensorFlow backend.
> 2018-11-21 09:16:41.195484: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
> 2018-11-21 09:16:41.195534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-11-21 09:16:41.195539: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988] 0
> 2018-11-21 09:16:41.195543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0: N
> 2018-11-21 09:16:41.195656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3638 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
> 2018-11-21 09:16:52.238761: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2018-11-21 09:16:52.241850: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> Traceback (most recent call last):
> File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
> return fn(*args)
> File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
> options, feed_dict, fetch_list, target_list, run_metadata)
> File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
> run_metadata)
> tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> [[{{node conv1_1/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1_1/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, conv1_1/weights/read)]]
> [[{{node rois/Reshape/_97}} = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_587_rois/Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/cq/桌面/chinese_ocr-master/demo.py", line 21, in 
> result, image_framed = ocr.model(image)
> File "/home/cq/桌面/chinese_ocr-master/ocr.py", line 83, in model
> text_recs, img_framed, img = text_detect(img)
> File "/home/cq/桌面/chinese_ocr-master/ctpn/text_detect.py", line 90, in text_detect
> scores, boxes, img, scale = ctpn(img)
> File "/home/cq/桌面/chinese_ocr-master/ctpn/text_detect.py", line 52, in ctpn
> scores, boxes = test_ctpn(sess, net, img)
> File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/fast_rcnn/test.py", line 51, in test_ctpn
> rois = sess.run([net.get_output('rois')[0]],feed_dict=feed_dict)
> File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
> run_metadata_ptr)
> File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
> feed_dict_tensor, options, run_metadata)
> File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
> run_metadata)
> File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> [[node conv1_1/Conv2D (defined at /home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/network.py:167) = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1_1/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, conv1_1/weights/read)]]
> [[{{node rois/Reshape/_97}} = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_587_rois/Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]]
> 
> Caused by op 'conv1_1/Conv2D', defined at:
> File "/home/cq/桌面/chinese_ocr-master/demo.py", line 3, in 
> import ocr
> File "", line 969, in _find_and_load
> File "", line 958, in _find_and_load_unlocked
> File "", line 673, in _load_unlocked
> File "", line 665, in exec_module
> File "", line 222, in _call_with_frames_removed
> File "/home/cq/桌面/chinese_ocr-master/ocr.py", line 10, in 
> from ctpn.text_detect import text_detect
> File "", line 969, in _find_and_load
> File "", line 958, in _find_and_load_unlocked
> File "", line 673, in _load_unlocked
> File "", line 665, in exec_module
> File "", line 222, in _call_with_frames_removed
> File "/home/cq/桌面/chinese_ocr-master/ctpn/text_detect.py", line 45, in 
> sess, net = load_tf_model()
> File "/home/cq/桌面/chinese_ocr-master/ctpn/text_detect.py", line 30, in load_tf_model
> net = get_network("VGGnet_test")
> File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/factory.py", line 8, in get_network
> return VGGnet_test()
> File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/VGGnet_test.py", line 14, in **init**
> self.setup()
> File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/VGGnet_test.py", line 21, in setup
> .conv(3, 3, 64, 1, 1, name='conv1_1')
> File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/network.py", line 23, in layer_decorated
> layer_output = op(self, layer_input, *args, **kwargs)
> File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/network.py", line 176, in conv
> conv = convolve(input, kernel)
> File "/home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/network.py", line 167, in 
> convolve = lambda i, k: tf.nn.conv2d(i, k, [1, s_h, s_w, 1], padding=padding)
> File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 957, in conv2d
> data_format=data_format, dilations=dilations, name=name)
> File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
> op_def=op_def)
> File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
> return func(*args, **kwargs)
> File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
> op_def=op_def)
> File "/home/cq/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1770, in **init**
> self._traceback = tf_stack.extract_stack()
> 
> UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> [[node conv1_1/Conv2D (defined at /home/cq/桌面/chinese_ocr-master/ctpn/lib/networks/network.py:167) = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1_1/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, conv1_1/weights/read)]]
> [[{{node rois/Reshape/_97}} = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_587_rois/Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]]

i changed tensorflow1.12 to 1.9,the problem above disappeared, the new problems as follow:
2018-11-21 14:33:14.477867: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2018-11-21 14:33:14.481006: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2018-11-21 14:33:14.482237: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2018-11-21 14:33:14.483350: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2018-11-21 14:33:14.484005: E tensorflow/stream_executor/cuda/cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2018-11-21 14:33:14.488353: E tensorflow/stream_executor/cuda/cuda_dnn.cc:332] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

**Comment by banbsyip** [comment]
i have to run the command "rm -rf ~/.nv/" after run the project each time, otherwise the problem will appear again, i do not know the reason

**Comment by banbsyip** [comment]
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.7)
config = tf.ConfigProto(allow_soft_placement=True, gpu_options=gpu_options)
sess = tf.Session(config=config)
i found the reason finally, i changed the per_process_gpu_memory_fraction set, it worked. so i colse the issue.

**Comment by mrgloom** [comment]
Have about the same error on Ubuntu 16:
`UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.`

I have installed tensorflow via: `sudo pip3 install tensorflow-gpu==1.12.0`, cuda-9.0 is under `/usr/local/cuda/`.

I have installed cudnn  and it's not helped:
https://gist.github.com/kylemcdonald/3ae0b88a1bf91afc00ba441fe6823a17

**Comment by banbsyip** [comment]
> Have about the same error on Ubuntu 16:
> `UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.`
> 
> I have installed tensorflow via: `sudo pip3 install tensorflow-gpu==1.12.0`, cuda-9.0 is under `/usr/local/cuda/`.
> 
> I have installed cudnn and it's not helped:
> https://gist.github.com/kylemcdonald/3ae0b88a1bf91afc00ba441fe6823a17
https://github.com/tensorflow/tensorflow/issues/6698

**Comment by mrgloom** [comment]
I think in my case it was I Cuda vs CuDnn version mismatch 
https://stackoverflow.com/questions/50622525/which-tensorflow-and-cuda-version-combinations-are-compatible
