### ISSUE TITLE
Error: ...tensorflow/core/common_runtime/bfc_allocator.cc:373] tried to deallocate nullptr

### ISSUE THREAD

**Issue by muarvyn** [tensorflow/tensorflow#23888]
**System information**
Ubuntu 18.04 (bionic);
g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0;
bazel release 0.18.1
Python 2.7.15rc1
- CUDA/cuDNN version: none
- GPU model and memory: none
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/2601035/tf_env.txt)

**Current behavior**
I've built TensorFlow from commit
`git log -1`
`commit a6d8ffae097d0132989ae4688d224121ec6d8f35 (HEAD, tag: v1.12.0, origin/r1.12)`
`Author: Todd Wang <toddwang@gmail.com>`
`Date:   Thu Nov 1 18:35:10 2018 -0700`
`Fix a bug in tpu.py and xla.py that while creating an identity node for control input edges under rewrite context, the parent control flow context is lost. (#23446)
PiperOrigin-RevId: 219724472`
with command line
`bazel build --config=mkl -c opt --copt=-mavx --copt=-mavx2 //tensorflow/tools/pip_package:build_pip_package`
and got the error, repeatedly appearing in terminal:
`E tensorflow/core/common_runtime/bfc_allocator.cc:373] tried to deallocate nullptr`
while attempting to run the example [Text generation using a RNN with eager execution](https://www.tensorflow.org/tutorials/sequences/text_generation).
Also can be reproduced with the package, installed with `pip install https://storage.googleapis.com/intel-optimized-tensorflow/tensorflow-1.11.0-cp27-cp27mu-linux_x86_64.whl `.

**Expected behavior**
Running without error messages.

**Comment by harshini-gadige** [comment]
@muarvyn  Please try with Bazel 0.15, TF version 1.12 and see if you are running into the same error. Please post with your updates.

**Comment by muarvyn** [comment]
>  Please try with Bazel 0.15, TF version 1.12

The same result - "...bfc_allocator.cc:373] tried to deallocate nullptr"

**Comment by alsrgv** [comment]
I'm seeing the same issue running TensorFlow benchmarks with `--xla=True --allow_growth=True`.

**Comment by sidkashyap** [comment]
I see the same error, "...bfc_allocator.cc:373] tried to deallocate nullptr"

**Comment by christopherhesse** [comment]
I see this as well, also using mkl.

**Comment by wosiu** [comment]
the same issue. Tensorflow installed using miniconda:
  - tensorflow=1.12.0=mkl_py36h69b6ba0_0
  - tensorflow-base=1.12.0=mkl_py36h3c3e929_0

**Comment by DennisWangCW** [comment]
I meet with the same issue, any solutions?

**Comment by zhangyafeikimi** [comment]
linux
tensorflow 1.13.1
--config=mkl
--config=xla
same issue

**Comment by wosiu** [comment]
the same issue
tensorflow 1.13.1 cpu

**Comment by preethivenkatesh** [comment]
We are investigating this bug and will update as soon as we have the fix

**Comment by NeoZhangJianyu** [comment]
@muarvyn 
Is this issue present?
If yes, could you update the latest status? so that we could continue supporting.

**Comment by NeoZhangJianyu** [comment]
@muarvyn 

If your issue is disappear, could you close it?
