### ISSUE TITLE
pip install tensorflow not working for py version 3.7.0 and 3.7.1

### ISSUE THREAD

**Issue by gatarelib** [tensorflow/tensorflow#23883]
**System information**
- OS : Win 10
- TensorFlow installed from : pip
- TensorFlow version: 1.12.0
- Python version: 3.7.0 and 3.7.1
- Installed using: pip

`$ python --version`
`Python 3.7.1`
`pip --version`
`pip 18.1`
`pip install tensorflow`

**Comment by harshini-gadige** [comment]
@gatarelib  #20517
