### ISSUE TITLE
Looking for Tensorflow lite C++ Android NDK install instructions

### ISSUE THREAD

**Issue by cathybgyz** [tensorflow/tensorflow#23896]
Can someone provide me documentation or examples of using Tensorflow lite + Android NDK C++.

The only project example is in Java, but I need to use Tensorflow lite with the Android NDK in C++.

I'm also using a Windows 10 computer and have the latest version of Bazel installed.

Any steps, documentation, and example projects for Tensorflow lite + Android NDK C++ would be very beneficial to me and the community..

Thank you for any support

**Comment by jefhai** [comment]
I’d also be interested in setup instructions.

I got android studio to install tflite on the java side pretty easily. How can I get it to work in c++?

**Comment by Nimitz14** [comment]
See this: https://stackoverflow.com/questions/49834875/problems-with-using-tensorflow-lite-c-api-in-android-studio-project

You must use NDK 18. Don't use dropout in your model.

**Comment by jefhai** [comment]
> See this: https://stackoverflow.com/questions/49834875/problems-with-using-tensorflow-lite-c-api-in-android-studio-project
> 
> You must use NDK 18. Don't use dropout in your model.

So are you suggesting by using NDK 18 and having added tensorflow lite to my gradle dependencies it will enable me to using tflite in my C++ code w/ Android NDK?

**Comment by Nimitz14** [comment]
No. Can you not see the link I posted? Read that.

**Comment by jefhai** [comment]
Should I go to NDK 18? or use what this warning suggests it supports?
![image 11-25-18 at 5 59 pm](https://user-images.githubusercontent.com/22269225/48986040-77042880-f0dd-11e8-9ba1-173136bb20c0.jpeg)

**Comment by Nimitz14** [comment]
You should ignore that. See [here](https://github.com/bazelbuild/bazel/issues/4742).

**Comment by cathybgyz** [comment]
@ymodak I got it working on mac and I wrote a blog to introduce this process. Hope it would be helpful to others. [https://zimenglyu.com/android/tensorflow/machinelearning/mobile/english/2018/11/27/tflite-android-ndk-eng.html](url)

**Comment by jefhai** [comment]
@cathybgyz looking forward to your blog! other resources seem more scatterbrained on the subject... Thank you 👍

**Comment by ymodak** [comment]
Awesome. Thanks for your contribution. Can I close this issue now since you have found the workaround solution?

**Comment by cathybgyz** [comment]
Yes.
Thanks

**Comment by cathybgyz** [comment]
@rribani Sorry about that, you can find it [here](https://zimenglyu.com/en/ml/android/tensorflow/2018/11/27/tflite-android-ndk-eng.html)

**Comment by rribani** [comment]
Perfect! Nice tutorial.. Thanks!

**Comment by fzyzcjy** [comment]
Thank you so much!

**Comment by fzyzcjy** [comment]
Is there any easier way to do that, for example, do not build it by oneself? Thanks!

**Comment by suneshp** [comment]
> @ymodak I got it working on mac and I wrote a [blog] to introduce this process. Hope it would be helpful to others. [here](https://zimenglyu.com/android/tensorflow/machinelearning/mobile/english/2018/11/27/tflite-android-ndk-eng.html)

I see the link doesn't work. Can you please help?

**Comment by Cross22** [comment]
Here's the correct link:
https://zimenglyu.com/en/ml/android/tensorflow/2018/11/27/tflite-android-ndk-eng.html

**Comment by limjq45** [comment]
Hi, just wondering if there is an improve in interpreter's performance when porting over to NDK?

**Comment by Parth220** [comment]
For future reference, I had a ton of trouble and that guide helped me set up TF Lite on C++ for Android NDK. @zimenglyu's personal website got changed around a little so the new link is: https://zimenglyu.com/posts/2018-11-27-tflite-android-ndk-eng.

Just dropping it here in case anyone else needs to reference it. Thank you @zimenglyu !
