### ISSUE TITLE
Can we have working example with assets in the documentation for the simple_save?

### ISSUE THREAD

**Issue by jltchiu** [tensorflow/tensorflow#23891]
**System information**
- TensorFlow version: 1.12
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/saved_model/simple_save 

Simple_save seems to be a newer and more standardized saving approach. Since it can also use assets to store vocabularies, I wonder if it is possible to have a working example in document based on keras sentiment analysis system's data? So there is place to look up how to really integrate the entire model (including vocabulary, word embedding, etc) in a single simple_save.

**Comment by annarev** [comment]
@allenlavoie Allen, what is the current best way to save a model and do we have a documentation page for it?

simple_save seems to be deprecated.

**Comment by allenlavoie** [comment]
simple_save won't appear in v2. We do have a SavedModel API: https://www.tensorflow.org/alpha/guide/saved_model

I don't have plans to write a sentiment analysis example, but it does sound useful.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
