### ISSUE TITLE
tflite_simple_example  VerifyVector too few arguments to function call

### ISSUE THREAD

**Issue by wangwenjing** [tensorflow/tensorflow#23899]
**System information**
- iOS 12.1 :
- iPhone7Plus
- TensorFlowLite 1.10.1(pod install):
- 1.10.1:

**Describe the problem**

Pod install in the lite/examples/ios/simple . Pod automatically installed tensorflow lite 1.10.1.  error occurred, say "tensorflow/lite/kernels/register.h" file not found. After I add paths to those header files, I encounter issue "verifier.VerifyVector(min()) too few arguments to function call, expeced 3, have 1".

Any guys have any clue ? Thanks in advance

**Comment by jefhai** [comment]
What’s the function definition? You could also try namespace to ensure you are calling the right function.

**Comment by wangwenjing** [comment]
> What’s the function definition? You could also try namespace to ensure you are calling the right function.

Hi jefhai, It's the "simple" example in folder lite/examples/ios/. I didn't add any my code except the path for  non-founded header files. Then I run the example and error occurred.  I found the **declaration of Verifier:VerifyVector has 3 parameters in flatbuffers.h of tensorflow_lite.frame(v1.10.1) as follows:**
// Common code between vectors and strings.
  bool VerifyVector(const uint8_t *vec, size_t elem_size,
                    const uint8_t **end) const {
    // Check we can read the size field.
    if (!Verify<uoffset_t>(vec)) return false;
    // Check the whole array. If this is a string, the byte past the array
    // must be 0.
    auto size = ReadScalar<uoffset_t>(vec);
    auto max_elems = FLATBUFFERS_MAX_BUFFER_SIZE / elem_size;
    if (!Check(size < max_elems))
      return false;  // Protect against byte_size overflowing.
    auto byte_size = sizeof(size) + elem_size * size;
    *end = vec + byte_size;
    return Verify(vec, byte_size);
  }

**But the caller in schema_generated.h pass only one param:**
 const flatbuffers::Vector<int64_t> ***zero_point()** const {
    return GetPointer<const flatbuffers::Vector<int64_t> *>(VT_ZERO_POINT);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MIN) &&
           verifier.VerifyVector(min()) &&
           VerifyOffset(verifier, VT_MAX) &&
           verifier.VerifyVector(max()) &&
           VerifyOffset(verifier, VT_SCALE) &&
           verifier.VerifyVector(scale()) &&
           VerifyOffset(verifier, VT_ZERO_POINT) &&
           verifier.VerifyVector(**zero_point()**) &&
           verifier.EndTable();
  }

**Comment by aselle** [comment]
@miaout17 , do you have any ideas?

**Comment by miaout17** [comment]
The newest example is using TensorFlowLite 1.12.0 pod and I don't see this happening.
Please reopen if you can still reproduce it. Thanks!
