### ISSUE TITLE
 'LSTMBlockCell' error when loading a model using saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)

### ISSUE THREAD

**Issue by AbdelsalamHaa** [tensorflow/tensorflow#23897]
in the issue below they had the same problem,but there's no much information. btw this is the only issue I found about this.
I hope I can receive more  help by opening this issue. 

_Originally posted by @AbdelsalamHaa in https://github.com/tensorflow/tensorflow/issues/20732#issuecomment-440546353_

**Comment by ymodak** [comment]
Apologies for the delay in response. Is this still an issue for you? Can you please provide the informations asked by the [template](https://github.com/tensorflow/tensorflow/issues/new?template=00-bug-performance-issue.md)? Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
