### ISSUE TITLE
front camera bounding box tracking issue

### ISSUE THREAD

**Issue by jktruimp1** [tensorflow/tensorflow#23919]
Thanks for clicking  in and reading my questions first :)
I want to detect human face by front camera .
I have changed my camera to front, and changed location like this.
` location.left = 288f - result.getLocation().left;`
  ` location.right = 288f - result.getLocation().right;`
      
I have 2 questions.
       1.My code can detect human correctly, but the bounding box tracks in opposite direction(left-            >right. right->left ). Maybe I miss to  edit somewhere's location ?
       2.Another question is , sometimes when target moves, a new bounding box occurs, but the old one    is still there ,too. However,if preview changes a lot (like target leaves quickly, or new target in), the old box will disappear .
If any one have any idea I will appreciate.
I recorded the detection scene and put it below .
[https://reurl.cc/EZ4pv](url)

**Comment by jktruimp1** [comment]
Problem solved!
I change other file’s location, and it works!

**Comment by tomeroto** [comment]
hello, how to fix it? I have same problem.

**Comment by topherbuckley** [comment]
Wishing there were a more elegant solution, but for a hack of the source, you can flip the bounding box from left to right by adding 
```
location.set((TF_OD_API_INPUT_SIZE - location.left), location.top, (TF_OD_API_INPUT_SIZE - location.right), location.bottom);
```
just above [this](https://github.com/tensorflow/examples/blob/f55194adcfafa5cddd57f8c05d42b8a428e9d24b/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/DetectorActivity.java#L204)
