### ISSUE TITLE
Weird behavior of tf.math.reduce_max

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/tensorflow#23914]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 3.6.6
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: 9.0/7
- GPU model and memory: GeForce GTX 1080 Ti, 11G

**Describe the current behavior**
```python
import numpy as np
import tensorflow as tf

# tf.enable_eager_execution()


def test_bug():
    input = tf.convert_to_tensor(np.ones((1, 1, 1, 1), dtype=np.float32))
    x = tf.layers.conv2d(input, 1, (1, 1), activation="tanh",
                         kernel_initializer=tf.initializers.constant(2),
                         use_bias=False)
    max_out = tf.math.reduce_max(x, [1, 2])

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        m = sess.run(max_out)
        m1, _ = sess.run([max_out, x])
        print('m =', m)
        print('m1 =', m1)
        assert np.allclose(m, m1)

test_bug()
```
I'd suppose that the assertion should pass given above code. However, `tf.math.reduce_max` looks very strange:
```
m = [[2.]]
m1 = [[0.9640276]]
```

**Describe the expected behavior**
`m` and `m1` should have the same value and the assertion should pass.
```
m = [[0.9640276]]
m1 = [[0.9640276]]
```

**Code to reproduce the issue**
Listed above.

**Other info / logs**
If eager execution is enabled, then the value of `x` and `max_out` is the same.

**Comment by alextp** [comment]
@rmlarsen this looks like another bug like the earlier one we fixed where grappler is rewriting a node which is being fetched. Can you take a look?

**Comment by alextp** [comment]
I think this bug has been fixed in nightly. Please reopen / comment if I'm wrong.
