### ISSUE TITLE
Inconsistant naming in Estimator documentation

### ISSUE THREAD

**Issue by jltchiu** [tensorflow/tensorflow#23923]
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator

In the section for `export_savedmodel`, it mentioned `export_to_savedmodel` which seems should be `export_savedmodel`. Maybe worth a fix.

**Comment by shivakrishna9** [comment]
I am new here. Can I take this up?

**Comment by yashk2810** [comment]
This looks fixed to me: https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#export_saved_model

Please reopen or submit a PR if not fixed.
