### ISSUE TITLE
Makefile for TFLite under Linux

### ISSUE THREAD

**Issue by pglushkov** [tensorflow/tensorflow#23926]
**System information**
- Linux Ubuntu 16.04
- TensorFlow Lite compilation from source
- TensorFlow version 1.12
- g++ 5.4.0
- GPU / CUDA/cuDNN version - not used

I came across interesting thing in implementation of Makefile for Linux version of TFLite. In particular:
list of compiled sources does not include directory 'tensorflow/lite/core', only some sub-directories from it. This make the compiled 'libtensorflow-lite.a' binary unusable - linker always gives error even on the simplest examples, as e.g. give on this page - https://www.tensorflow.org/lite/apis

By adding line 
$(wildcard tensorflow/lite/core/*.cc) \
I managed to fix this - newly compiled binary now contained all symbols that were previously absent in the binary.

My question is - is this made on purpose for some reason that I've missed or this is just a bug? Could someone from the developers give better explanation? Thanks!

**Comment by aselle** [comment]
Can you provide the exact makefile path you are looking at?

**Comment by pglushkov** [comment]
Hi! 
this one : https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/make/Makefile

**Comment by aselle** [comment]
Yes, that is an oversight, your fix is correct. Thanks!  If you submit a PR that would be awesome!

**Comment by pglushkov** [comment]
Dear Andrew, I'd love to finish the pull-request, but unfortunately Google Bot does no allow me to get past the 'sign the CLA' stage. I've double checked all my e-mails and etc - still cannot find the reason.

**Comment by aselle** [comment]
I'm happy to make the one line fix on your behalf since it is so small if
you are ok with that.

Also, please check the troubleshooting if you haven't
https://opensource.google.com/docs/cla/#troubleshoot

-A

**Comment by pglushkov** [comment]
Sure, please do, I'm totally ok.
