### ISSUE TITLE
transform_graph build  error

### ISSUE THREAD

**Issue by Alicture** [tensorflow/tensorflow#23934]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):Source
- TensorFlow version: Github Master version
- Python version:2.7
- Installed using virtualenv? pip? conda?: None. 
- Bazel version (if compiling from source): 0.18.1
- GCC/Compiler version (if compiling from source):7.3.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Install transform_graph tools from the source using Bazel on my VMware VM Ubuntu 18.04
**Provide the exact sequence of commands / steps that you executed before running into the problem**
cd ~/tensorflow
bazel build tensorflow/tools/graph_transforms:transform_graph

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
And i got random error such as this:
ERROR: /home/zpluo/tensorflow/tensorflow/core/kernels/BUILD:2829:1: C++ compilation of rule '//tensorflow/core/kernels:matrix_square_root_op' failed (Exit 4)
gcc: internal compiler error: Killed (program cc1plus)

PS:Sometime it's the other file can't be built.

**Comment by ymodak** [comment]
Apologies for the delay in response. Is this still an issue?

**Comment by mmkos** [comment]
> Apologies for the delay in response. Is this still an issue?

I also came across this problem just now. 

**System information**

* OS Platform and Distribution: Linux Ubuntu 18.04
* TensorFlow installed from: Source
* TensorFlow version: Github Master version
* Python version: 2.7
* Installed using virtualenv? pip? conda?: None.
* Bazel version (if compiling from source): 0.22.0
* GCC/Compiler version (if compiling from source): 7.3.0

**Comment by ymodak** [comment]
Can you please paste the error? Also what are the steps you followed to install TF?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
