### ISSUE TITLE
 fatal error: cuda/include/cublas_v2.h: No such file or directory

### ISSUE THREAD

**Issue by kxhit** [tensorflow/tensorflow#23939]
Following instructions building tensorflow from source by using bazel, I got error when 
 
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package  --define framework_shared_object=false tensorflow:libtensorflow_cc.so --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"

**System information**
- Linux Ubuntu 16.04
- TensorFlow installed from source
- TensorFlow version: r1.8
- Python version: 3.5
- Installed using virtualenv :
- Bazel version (if compiling from source): 0.18.1
- GCC/Compiler version (if compiling from source): 5.4
- CUDA/cuDNN version: 9.0/7.0
- GPU model and memory: TITAN XP 

my configuration file:
build --action_env PYTHON_BIN_PATH="/home/kx/segmappyenv/bin/python"
build --action_env PYTHON_LIB_PATH="/home/kx/segmappyenv/lib/python3.5/site-packages"
build --force_python=py3
build --host_force_python=py3
build --python_path="/home/kx/segmappyenv/bin/python"
build --define with_jemalloc=true
build --define with_gcp_support=true
build --define with_hdfs_support=true
build --define with_s3_support=true
build --define with_kafka_support=true
build:xla --define with_xla_support=true
build:gdr --define with_gdr_support=true
build:verbs --define with_verbs_support=true
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_CUDA="1"
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda-9.0"
build --action_env TF_CUDA_VERSION="9.0"
build --action_env CUDNN_INSTALL_PATH="/usr/local/cuda-9.0"
build --action_env TF_CUDNN_VERSION="7"
build --action_env TF_NCCL_VERSION="1"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="6.1"
build --action_env LD_LIBRARY_PATH="/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/usr/local/cuda-9.0/lib64:/usr/local/cuda-9.0/extras/CUPTI/lib64"
build --action_env TF_CUDA_CLANG="0"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/gcc"
build --config=cuda
test --config=cuda
build --define grpc_no_ares=true
build:opt --copt=-march=native
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build --copt=-DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK
build --host_copt=-DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK

**Any other info / logs**
build logs:

INFO: From Compiling tensorflow/core/distributed_runtime/master.cc [for host]:
In file included from ./tensorflow/core/platform/default/logging.h:24:0,
                 from ./tensorflow/core/platform/logging.h:25,
                 from ./tensorflow/core/lib/core/status.h:25,
                 from ./tensorflow/core/framework/variant.h:29,
                 from ./tensorflow/core/framework/allocator.h:26,
                 from ./tensorflow/core/common_runtime/device.h:35,
                 from ./tensorflow/core/distributed_runtime/master.h:21,
                 from tensorflow/core/distributed_runtime/master.cc:32:
./tensorflow/core/util/tensor_format.h: In instantiation of 'T tensorflow::GetTensorDim(tensorflow::gtl::ArraySlice<T>, tensorflow::TensorFormat, char) [with T = long long int]':
./tensorflow/core/util/tensor_format.h:372:47:   required from here
./tensorflow/core/util/tensor_format.h:340:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   CHECK(index >= 0 && index < dimension_attributes.size())
                             ^
./tensorflow/core/platform/macros.h:82:47: note: in definition of macro 'TF_PREDICT_FALSE'
 #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
                                               ^
./tensorflow/core/util/tensor_format.h:340:3: note: in expansion of macro 'CHECK'
   CHECK(index >= 0 && index < dimension_attributes.size())
   ^
./tensorflow/core/util/tensor_format.h: In instantiation of 'T tensorflow::GetFilterDim(tensorflow::gtl::ArraySlice<T>, tensorflow::FilterTensorFormat, char) [with T = long long int]':
./tensorflow/core/util/tensor_format.h:381:54:   required from here
./tensorflow/core/util/tensor_format.h:355:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   CHECK(index >= 0 && index < dimension_attribute.size())
                             ^
./tensorflow/core/platform/macros.h:82:47: note: in definition of macro 'TF_PREDICT_FALSE'
 #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
                                               ^
./tensorflow/core/util/tensor_format.h:355:3: note: in expansion of macro 'CHECK'
   CHECK(index >= 0 && index < dimension_attribute.size())
   ^
ERROR: /home/kx/segmappyenv/tensorflow/tensorflow/core/kernels/BUILD:2547:1: C++ compilation of rule '//tensorflow/core/kernels:self_adjoint_eig_v2_op' failed (Exit 1)
In file included from tensorflow/core/kernels/self_adjoint_eig_v2_op_gpu.cc:29:0:
./tensorflow/core/kernels/cuda_solvers.h:26:36: fatal error: cuda/include/cublas_v2.h: No such file or directory
compilation terminated.
INFO: Elapsed time: 383.691s, Critical Path: 52.31s
INFO: 2759 processes: 2759 local.
FAILED: Build did NOT complete successfully

**Comment by byronyi** [comment]
Could you try `bazel clean --expunge` and build again?

**Comment by byronyi** [comment]
Could you try reinstall your CUDA and bazel clean —expunge and build again?

**Comment by kxhit** [comment]
@byronyi  After reinstall CUDA9.0, cudnn7.4 and bazel clean --expunge and build again. 

bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package  --define framework_shared_object=false tensorflow:libtensorflow_cc.so --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"


I got another error:

INFO: From Compiling tensorflow/contrib/lite/toco/dump_graphviz.cc:
In file included from ./tensorflow/contrib/lite/kernels/internal/common.h:42:0,
                 from ./tensorflow/contrib/lite/toco/runtime/types.h:18,
                 from ./tensorflow/contrib/lite/toco/model.h:26,
                 from ./tensorflow/contrib/lite/toco/dump_graphviz.h:20,
                 from tensorflow/contrib/lite/toco/dump_graphviz.cc:15:
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'void vst1q_lane_f32(float32_t*, float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:9673:31: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(ptr) =  *((float*)&ilane);
                               ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'float32_t vgetq_lane_f32(float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:11912:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     return *(float*)&ilane;
                      ^
tensorflow/contrib/lite/toco/dump_graphviz.cc: In function 'void toco::{anonymous}::AppendArrayVal(std::string*, const toco::Array&, int)':
tensorflow/contrib/lite/toco/dump_graphviz.cc:112:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (index >= data.size()) {
               ^
tensorflow/contrib/lite/toco/dump_graphviz.cc:118:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (index >= data.size()) {
               ^
tensorflow/contrib/lite/toco/dump_graphviz.cc:124:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (index >= data.size()) {
               ^
tensorflow/contrib/lite/toco/dump_graphviz.cc:130:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (index >= data.size()) {
               ^
tensorflow/contrib/lite/toco/dump_graphviz.cc: In function 'void toco::DumpGraphviz(const toco::Model&, std::string*)':
tensorflow/contrib/lite/toco/dump_graphviz.cc:323:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int op_index = 0; op_index < ops_to_dump.size(); op_index++) {
                                   ^
ERROR: /home/kx/segmappyenv/tensorflow/tensorflow/python/BUILD:3315:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed (Exit 1)
gcc: error: pywrap_tensorflow_internal_versionscript.lds: No such file or directory
INFO: Elapsed time: 1911.083s, Critical Path: 183.69s
INFO: 4469 processes: 4469 local.
FAILED: Build did NOT complete successfully

**Comment by DEKHTIARJonathan** [comment]
Exact Same issue when building a Docker Image:

```Dockerfile
ENV CI_BUILD_PYTHON=python \
    BAZEL_VERSION='0.15.0' \
    LD_LIBRARY_PATH='/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH' \
    BLAS_INCLUDE='/usr/local/cuda/targets/x86_64-linux/include' \
    BLAS_LIB='/usr/local/cuda/targets/x86_64-linux/lib' \
    TF_NEED_CUDA=1 \
    TF_NEED_TENSORRT=1 \
    TF_CUDA_COMPUTE_CAPABILITIES=5.2,6.0,6.1,7.0,7.5 \
    TF_CUDA_VERSION=10.0 \
    TF_CUDNN_VERSION=7 \
    TF_NCCL_VERSION=2 \
    TF_BUILD_BRANCH='r1.12'

RUN ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1 && \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:${LD_LIBRARY_PATH}

# Set up Bazel.

# Running bazel inside a `docker build` command causes trouble, cf:
#   https://github.com/bazelbuild/bazel/issues/134
# The easiest solution is to set up a bazelrc file forcing --batch.

# Similarly, we need to work around sandboxing issues:
#   https://github.com/bazelbuild/bazel/issues/418
RUN rm -f /etc/bazel.bazelrc && \
    echo "startup --batch" >> /etc/bazel.bazelrc && \
    echo "build --spawn_strategy=standalone --genrule_strategy=standalone" \
        >> /etc/bazel.bazelrc && \
    rm -rf /bazel &&  mkdir /bazel && cd /bazel && \
    curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" \
        -fSsL -O https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh && \
    curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" \
        -fSsL -o /bazel/LICENSE.txt https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE && \
    chmod +x bazel-*.sh && \
    ./bazel-$BAZEL_VERSION-installer-linux-x86_64.sh && \
    cd / && \
    rm -f /bazel/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh

# Get the TF branch for later build
RUN rm -rf /tensorflow && \
    git clone --branch=$TF_BUILD_BRANCH --depth=1 https://github.com/tensorflow/tensorflow.git /tensorflow && \
    cd /tensorflow && \
    tensorflow/tools/ci_build/builds/configured GPU \
    bazel build -c opt --copt=-mavx --config=cuda \
	    --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
        tensorflow/tools/pip_package:build_pip_package && \
    rm /usr/local/cuda/lib64/stubs/libcuda.so.1 && \
    bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip && \
    pip --no-cache-dir install --upgrade /tmp/pip/tensorflow-*.whl && \
    rm -rf /tmp/pip && \
    rm -rf /root/.cache
```

**Comment by kxhit** [comment]
I fixed error `fatal error: cuda/include/cublas_v2.h` by reinstalling CUDA. Finally, I compiled TF1.9 successfully and everything works fine now. I failed executing `bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/lite/...` with TF1.8 but succeed with TF1.9. So make sure you can [bazel test](https://www.tensorflow.org/install/source) successfully. Maybe you can try another version. My problem is fixed so I will close this issue.
