### ISSUE TITLE
Network Bandwidth Un-expected Behavior 

### ISSUE THREAD

**Issue by salemmohammed** [tensorflow/tensorflow#23947]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Linux Ubuntu
- TensorFlow installed from (source or binary): Yes
- TensorFlow version (use command below): 1.11.0
- Python version: 3.5
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: None
- GPU model and memory: No GPU only CPU.

I have a simple model 2.8 MB. I wrote a distributed Tensorflow code with one parameter server and one worker. I measured the network bandwidth for in and out from worker.
I found that worker utilized bandwidth-in is 53 MB and worker utilized bandwidth-out is 26 MB. 
My dataset is MNIST dataset which is 46 MB. 
The total worker and server bandwidth are 92.5 MB.

My question is that I thought I will see only the size of my model in and out from to worker but where these 53, 26 data come from.

This is my code:

https://github.com/salemmohammed/TensorflowDistributedExample/blob/master/PS_Dist1.py

**Comment by salemmohammed** [comment]
@mrry

**Comment by gadagashwini** [comment]
Hi @salemmohammed, Tensorflow v2.x supports ParameterServerStrategy, is a TensorFlow API to distribute training across multiple GPUs, multiple machines, or TPUs. Using this API, you can distribute your existing models and training code with minimal code changes.

You can use `tf.distribute.experimental.ParameterServerStrategy()` to distribute model training.
For more information refer this [link](https://www.tensorflow.org/guide/distributed_training#parameterserverstrategy). Thank you!
