### ISSUE TITLE
Tensorflow In Anaconda not found

### ISSUE THREAD

**Issue by ctripalila** [tensorflow/tensorflow#23956]
Good evening. As I understand tensorflow and keras couldn't be installed in python 3.7 (keras is not used without tensorflow). So I just copy all folders of tensorflow and keras in site-package of anaconda. But system is proceeding with error "No module named 'tensorflow.python' when I try to import tensorflow (folder tensorflow and folder python exist in directory Local\Continuum\anaconda3\Lib\site-packages\). Is there any other opportunity to use module tensorflow and keras in python 3.7?

**Comment by benjamintanweihao** [comment]
You could try building from source but it would be easier to just use Python 3.5/3.6 instead. Is there anything that is stopping you from doing that?
