### ISSUE TITLE
During config, please provide an error or warning if too low of a computer capability is set.

### ISSUE THREAD

**Issue by odinsbane** [tensorflow/tensorflow#23951]
During config, we can request the required computer capabilties to be compiled to. For the newer tensorflows >1.10 we can request using cuda computer capabilities 3.0, but after tensorflow is built it is not usable unless there is a compute capabilties >=3.5.

Seems like a warning would be appropriate especially considering the 4+ hours of compiling afterwards will succeed, but fail when actually attempting to use the built packages.

**Comment by hgadig** [comment]
@gunan  Can this be added as a feature ?

**Comment by gunan** [comment]
I think it does make a lot of sense.
It should be quite straightforward to add it in configure.py
If anyone would like to contribute this, I am happy to review

**Comment by Sudeepam97** [comment]
@gunan I can submit a patch for this. Can you please suggest a good warning message? I have framed this one based on what @odinsbane said, but I'm not sure if its good enough `Warning: compute capabilities >= 3.5 are required for TensorFlow to work`

**Comment by dynamicwebpaige** [comment]
Thanks for the offer to help, @Sudeepam97! We appreciate it. :smile: 

@gunan, @martinwicke - Should the error message shown above be modified to reflect CUDA requirements in TF 2.0 vs TF 1.12?

**Comment by martinwicke** [comment]
No, compute capabilities are independent of the CUDA version. The message is great.

**Comment by Sudeepam97** [comment]
Hi @dynamicwebpaige and @martinwicke. I have submitted a PR for this issue. You can check it out.

**Comment by dynamicwebpaige** [comment]
Thank you, @Sudeepam97! :smile_cat: We appreciate it.
