### ISSUE TITLE
pip install tf-nightly-gpu Does not work

### ISSUE THREAD

**Issue by namtran0110** [tensorflow/tensorflow#23958]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS X El Capitan
- Anaconda
- Pip v.18.1
- Python v.3.6.6 

**Describe the problem**
Could not find a version that satisfies the requirement tf-nightly-gpu (from versions: )
No matching distribution found for tf-nightly-gpu
**Provide the exact sequence of commands / steps that you executed before running into the problem**
Following steps on this:
https://www.youtube.com/watch?v=xQ4i6sDt-Tk&t=120s

**Comment by benjamintanweihao** [comment]
As you can see from https://pypi.org/project/tf-nightly-gpu/#files, the `tf-nightly-gpu` only contains builds for Linux based systems.
