### ISSUE TITLE
Math ops with Tensorflow Lite C++ and Android NDK

### ISSUE THREAD

**Issue by cathybgyz** [tensorflow/tensorflow#23964]
I have successfully installed Tensorflow Lite (C++/so) into an Android product (NDK). I'm looking for the tensorflow math operations, do they exist in tensorflow lite? Or is the sole purpose of tensorflow lite to run inference on models? I also can't seem to find array_ops.h in the tensorflow repository, is this cross complied from some other language?

TLDR: Does tensorflow lite lack math ops and in order to use them you need the full tensorflow?

**Comment by freedomtan** [comment]
In short, YES. But no, there is no full tensorflow on Android (as far as I can remember previous TensorFlow Mobile is a subset of TF). And you can use something like [flex](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/flexl) in TFLite to use TF ops. Check this [doc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/using_select_tf_ops.md) for flex and thie one for  [op list](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tf_ops_compatibility.md)

**Comment by ymodak** [comment]
Closing this issue since explanation given by @freedomtan is correct. Feel free to reopen the issue if have any follow up questions. Thanks!
