### ISSUE TITLE
Trying to optimize graph with optimize_for_inference too many positional arguments

### ISSUE THREAD

**Issue by royp84** [tensorflow/tensorflow#23960]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**

- OS Platform and Distribution : windows 10 X64
- TensorFlow installed from (source or binary): pip install
- TensorFlow version  : 1.7.1
- Python version: 36
- CUDA/cuDNN version: cuda v9.0
- GPU model and memory: Nvidia 1070

**Describe the current behavior**

I'm doing some image recognition with tensorflow. I retrained a CNN based on Inception V3 with my onw data. 

My results are pretty good, I'm now trying to optimize the protobuf in order to use it with TFmobile.
So I'm using optimize_for_inference like this :
python optimize_for_inference.py 
--input="C:\Users\project\Documents\peinture\learn\retrained_graphpeinture.pb" 
--output="C:\Users\project\Documents\peinture\learn\optimized_graph.pb" 
--frozen_graph="True" --input_names="Placeholder" 
--output_names="final_result"

I have in return a message error : File "optimize_for_inference.py", line 92, in main FLAGS.toco_compatible) TypeError: optimize_for_inference() takes 4 positional arguments but 5 were given 

I understand that there are too many arg in the py file. 
I looked at the file line 92, and there is indeed 5 arguments :
output_graph_def = optimize_for_inference_lib.optimize_for_inference(  
input_graph_def,   
FLAGS.input_names.split(","),   
FLAGS.output_names.split(","),   
_parse_placeholder_types(FLAGS.placeholder_type_enum),   
FLAGS.toco_compatible) 

Is my file not the good one ? I don't understand why it doesn't work. I'm pretty sure I'm using the good file (clone form Github). I followed step by step the well known Tensorflow for poets 2 tutorial.Best regards
--

Thanks :)

**Comment by royp84** [comment]
Please help me

**Comment by ymodak** [comment]
Can you use the latest version of TensorFlow and test again?

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
