### ISSUE TITLE
[tensorflow/contrib/lite/toco/tflite/export.cc:192] Unsupported operator: MirrorPad

### ISSUE THREAD

**Issue by jason9693** [tensorflow/tensorflow#23962]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

System information
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
1.12.0
- Python version:
Python 3.6.5 :: Anaconda, Inc.
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

--------------------------------------
I am trying to convert a graph from .pb to .lite format using toco, but I get this error:
2018-11-25 21:58:56.811762: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: MirrorPad

I think MirrorPad is the basic op, Lite shoud support it.

---------------------------------------

**Comment by aselle** [comment]
You need to build from source or use the nightly pip to get htis op. It was just added 11/20/18.

**Comment by stakemura** [comment]
Is MirrorPad now supported as a TF-lite built-in function?
I tried to convert frozen model including MirrorPad ops to tflite using tf-nightly==1.13.0.dev20181129 (Python 3.5 linux ver.) but it failed.
