### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.learn' has no attribute 'datasets'

### ISSUE THREAD

**Issue by sanjaymeena** [tensorflow/tensorflow#2396]
I was running :  tensorflow/tensorflow/examples/skflow/text_classification_cnn.py
 
The line at : dbpedia = learn.datasets.load_dataset('dbpedia') fails with the attribute error . 

Error: AttributeError: module 'tensorflow.contrib.learn' has no attribute 'datasets'

**Comment by terrytangyuan** [comment]
Please install latest version, .e.g. one of the recent nightly builds

**Comment by nguyendn** [comment]
I install version `tensorflow-0.8.0` but I have the same problem

**Comment by mrry** [comment]
@nguyendn: See the answer to #2421. You need to install a **nightly** build to run the examples on the `master` branch, or run the examples from the branch that corresponds to the release (https://github.com/tensorflow/tensorflow/tree/r0.8/tensorflow/examples/skflow).

**Comment by zd123** [comment]
Hey, if you dont want to re-install the nightly build, you can manually download the same dataset.  I've documented ez steps here:  http://stackoverflow.com/questions/37206459/tensorflow-examples-all-fail-due-to-attributeerror-module-object-has-no-attri
