### ISSUE TITLE
TypeError: Type already registered for SparseTensorValue when running 2nd script 

### ISSUE THREAD

**Issue by camhao168** [tensorflow/tensorflow#23974]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N/a
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12
- Python version: 3.6.5
- Bazel version (if compiling from source): 0.17.2
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: 9.0/7.0
- GPU model and memory: GTX 1080 TI (11 GB)

**Describe the current behavior**
When I run a certain script in Spyder at the 1st time, everything flows smoothly. However, when I continue to run another script, following errors occur (which didn't happen at previously built tf 1.10):

> File "/home/haohua/tf_env/lib/python3.6/site-packages/tensorflow/init.py", line 24, in from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import

> File "/home/haohua/tf_env/lib/python3.6/site-packages/tensorflow/python/init.py", line 70, in from tensorflow.python.framework.framework_lib import * # pylint: disable=redefined-builtin

> File "/home/haohua/tf_env/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 30, in from tensorflow.python.framework.sparse_tensor import SparseTensor

> File "/home/haohua/tf_env/lib/python3.6/site-packages/tensorflow/python/framework/sparse_tensor.py", line 248, in pywrap_tensorflow.RegisterType("SparseTensorValue", SparseTensorValue)

> TypeError: Type already registered for SparseTensorValue

My temporary solution is restart the kernel before continuing to run the next script.

But restarting kernel at every single step of running a script (from the 2nd run) is not comfortable. Thus, I would like to ask for a critical solution for such kind of issue.

P/S: [https://stackoverflow.com/questions/53477005/tensorflow-r1-12-typeerror-type-already-registered-for-sparsetensorvalue-when](url) is my question on Stackoverflow. However, I think it is still proper to put this issue here.

**Comment by ymodak** [comment]
Apparently it is IDE related issue. Are you able to execute your code in jupyter notebook?

**Comment by camhao168** [comment]
@ymodak Yes, it works well without restarting kernel in jupyter notebook. Thank you very much. 
Btw, do you have any ideas of fixing the IDE (spyder) itself to avoid such issue?

**Comment by ymodak** [comment]
Awesome. Glad it worked. Unfortunately I have know idea for the spyder ide. You can try posting this issue on [spyder repo](https://github.com/spyder-ide/spyder/issues/new), folks there might know more. I will close this issue now since it has fixed your tf related problem.

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
