### ISSUE TITLE
pyhton code with tensorflow code throws execption in xampp server.

### ISSUE THREAD

**Issue by dranandrao** [tensorflow/tensorflow#23977]
I have a python code in server root folder which has a tensorflow code, when compiled using exec() php command in php, it is throwing exception.

But when executed normally through console it excutes.

I have attached text file which has the exception thrown while executing.
Currently I'm using postman to test the php file.

[output.txt](https://github.com/tensorflow/tensorflow/files/2615237/output.txt)

**Comment by harshini-gadige** [comment]
@dranandrao  You need to use newer version of the library C++ ABI than your system libstdc++ has. 

Request you to provide the information asked as per [this](https://github.com/tensorflow/tensorflow/issues/new?template=00-bug-performance-issue.md) template.
