### ISSUE TITLE
yolo-v3 has correctness issue at tf-nightly

### ISSUE THREAD

**Issue by guizili0** [tensorflow/tensorflow#23970]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):NA
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):  tf-nightly==1.13.0.dev20181115
- Python version: 3.4
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
 Start from tf-nightly==1.13.0.dev20181115, yolo-v3(https://github.com/mystic123/tensorflow-yolo-v3) meet correctness issue, the TF output did not consistent with the previous version
**Describe the expected behavior**
With same command, tf-nightly==1.13.0.dev20181114 can get the right result and plot the bounding box.
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
https://github.com/mystic123/tensorflow-yolo-v3#how-to-run-the-demo
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mahmoud-abuzaina** [comment]
We have seen similar issue with Resnet50 where accuracy drops to a very low number. This commit https://github.com/NervanaSystems/private-tensorflow/commit/0c1eb8861624d6d17c797b70d25330711df5eb2f seems to be causing the issue.

**Comment by guizili0** [comment]
@mahmoud-abuzaina the commit your provided is not the root cause for yolov3, after check, this commit https://github.com/tensorflow/tensorflow/commit/89fa3c5ed66a4e543ba01c31febf3edb417808d0 should be the yolov3 correctness regression commit. this commit update the Eigen version.

**Comment by guizili0** [comment]
Any updates?

**Comment by defaultUser3214** [comment]
something new about it?

**Comment by msymp** [comment]
Hello @martinwicke , can you please check this accuracy issue? Thanks.

**Comment by martinwicke** [comment]
@rmlarsen, @guizili0 pointed at the Eigen update leading to a regression in YOLO quality. 

This is sadly a very ill-defined regression -- @guizili0 do you have any hints as to where this regression may manifest itself, i.e., where (which op) results start to differ?

**Comment by martinwicke** [comment]
@guizili0 did you find this commit via bisection?

**Comment by guizili0** [comment]
@martinwicke it is hard for me to find the regression commit in Eigen, do you have any suggestion about this?

**Comment by msymp** [comment]
@guizili0 , we need to track down the contributor of this regression commit.

**Comment by martinwicke** [comment]
@rmlarsen may have some pointers for where to start.

**Comment by msymp** [comment]
Hi @rmlarsen , we would to track down the correctness issue for yolov3 that this regression commit seems to have introduced.
https://bitbucket.org/eigen/eigen/commits/af207140728002141ce3ff17f6f14cc159965f93
Thanks.

**Comment by willbattel** [comment]
Is this problem still being observed in recently nightly builds?

**Comment by guizili0** [comment]
@willbattel yes, still failed.

**Comment by Saduf2019** [comment]
@guizili0 
Is this still an issue.
