### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by ANeuRoBo** [tensorflow/tensorflow#23971]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):       UBUNTU 18.04 LTS

- TensorFlow installed from (source or binary): 
      https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl

- Python version: 3.6
- Installed using virtualenv? pip? conda?:   conda

2018-11-26 10:47:27.577247: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.2 instructions, but these aren't available on your machine.

cannot import tensorflow installation is successful but its unable to run. need some help!!

**Comment by bjascob** [comment]
You've got 2 options.  

- You can compile TF yourself.  Follow the instructions to install from source.  If you use the flag -march=native, gcc will apply all the correct flags for your CPU.
- You can try to find an unofficial repository that supports your machine and download a wheel from there.  Take a look at [TF Optimized Wheels](https://github.com/mind/wheels).  This is just the first one I found.  There are probably others out there.  Please check for compatibility with Python version, CUDA version, ...

**Comment by binusuresh** [comment]
"You can compile TF yourself. Follow the instructions to install from source. If you use the flag -march=native, gcc will apply all the correct flags for your CPU."


 can u please explain . I am new with Tensorflow.

**Comment by bjascob** [comment]
In that case I would highly recommend finding a pre-built wheel as suggested above.  If instead, you decide to compile from source, instructions can be found at [Build From Source](https://www.tensorflow.org/install/source) .
