### ISSUE TITLE
Can't import tensorflow

### ISSUE THREAD

**Issue by Mohammed-Shoaib** [tensorflow/tensorflow#23983]
**System information**
- OS Platform and Distribution: Windows
- TensorFlow installed from (source or binary): Anaconda
- TensorFlow version: Cannot check as tensorflow cannot be imported
- Python version: Python 3.5.5 :: Anaconda, Inc.
- Installed using virtualenv: conda
- GCC/Compiler version (if compiling from source): (tdm64-1) 5.1.0

**Problem**

I had a working version of tensorflow-gpu. I decided to upgrade it since I had an older version. However, after upgrading it, whenever I try to import it, I now get an error.

I ran the command:

```
conda install -c anaconda tensorflow-gpu 
```
After that it installed and everything went fine. But now, I cannot import tensorflow anymore. The stack trace is shown below.

**Logs**
>Traceback (most recent call last):
  File "C:\Users\Shoaib\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Shoaib\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Shoaib\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Shoaib\Anaconda3\envs\tensorflow\lib\imp.py", line 243, in load
_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Shoaib\Anaconda3\envs\tensorflow\lib\imp.py", line 343, in load
_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified procedure could not be found.

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Shoaib\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\_
_init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\Shoaib\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\p
ython\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Shoaib\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Shoaib\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Shoaib\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Shoaib\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Shoaib\Anaconda3\envs\tensorflow\lib\imp.py", line 243, in load
_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Shoaib\Anaconda3\envs\tensorflow\lib\imp.py", line 343, in load
_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified procedure could not be found.

> Failed to load the native TensorFlow runtime.

> See https://www.tensorflow.org/install/errors

> for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Could anyone please tell me what could be causing this? Any help would be appreciated.
Thank you so much.

**Comment by harshini-gadige** [comment]
@Mohammed-Shoaib  Hi, please refer a similar issue #10033 which helps you to resolve the problem.

**Comment by Mohammed-Shoaib** [comment]
Hi,

I went to the issue before as well, I tried the steps again. According to the solution, I added cuda to my path variable.
According to @mrry I was also supposed to add cuda\bin to my path variable. However, cuda\bin was not present in the cuda directory I had. So I decided to reinstall everything.

Installed cuda toolkit 9.0 and with it I installed cuDNN 7.0.5, followed the steps according to the installation guide. Reinstalled tensorflow-gpu, added cuda and cuda\bin to my path variable. However, I still ended up getting the same error. I am still not sure as to why.

In the end, I just went ahead and installed default tensorflow which is for cpu and I did not get any errors after that. Anyways, I appreciate your help and support, so thank you for that.

**Comment by Mohammed-Shoaib** [comment]
Hi,

I finally got the gpu version of tensorflow working! So, I am still not sure as to what the issue was exactly, but I think as @mrry pointed out, I may have had conflicting versions of CUDA or cuDNN installed. Hence, I decided to start afresh, for the last time.

I followed a YouTube tutorial this time on installing tensorflow for gpu link to which can be found [here](https://www.youtube.com/watch?v=MnMYCPc82xI).

I started off by reinstalling [CUDA Toolkit 9.0](https://developer.nvidia.com/cuda-90-download-archive). I also went ahead and ran the patch files present. Next, I downloaded cuDNN 7.0.5 from the [archive](https://developer.nvidia.com/rdp/cudnn-archive). Took the `cudnn64_7.dll` file from `cudnn-9.0-windows7-x64-v7\cuda\bin` and pasted it in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin`.

With the NVIDIA dependencies installed, it was time to install the python packages. I started off by creating a new virtual environment, then installed all the dependencies and installed the gpu version.
I used Anaconda and the commands are given below:
```
conda  update conda
conda create –n tensorflow-gpu python=3.6 pip
activate tensorflow-gpu
pip install --ignore-installed --upgrade tensorflow-gpu
```
And that's it! After that I had a working version of tensorflow-gpu with no errors.

Thank you so much @harshini-gadige and @mrry for all your help and support! Appreciate it :)

**Comment by harshini-gadige** [comment]
@Mohammed-Shoaib  Glad to know that your issue is resolved. Thank you !

**Comment by harshini-gadige** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=23983)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=23983)

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
