### ISSUE TITLE
What is the encoding of a .tflite file?

### ISSUE THREAD

**Issue by jefhai** [tensorflow/tensorflow#23985]
I'm trying to read the text directly from a .tflite file but I don't know / can't figure out a .tflite's encoding.

Does anyone know what it is? Attached is the .tflite file as a .txt file...

I need to know the encoding so I can read it in correctly for tflite::FlatBufferModel::BuildFromBuffer() to read it right... 

[keras_cifar10.txt](https://github.com/tensorflow/tensorflow/files/2617880/keras_cifar10.txt)

**Comment by jefhai** [comment]
this is what the file looks like in TextEdit on Mac... But loads in binary in every other program...
Java is not reading this correctly using new BufferedReader(new InputStreamReader(tfliteSrt)) method.. Even specifying UTF-8 isn't working...

I haven't found a single way to load the file in C++ NDK land with BuildFromFile... There seems to be no way to get a proper file path from an asset built into the NDK... 
So loading the file text as a string into BuildFromBuffer seems like my best choice...

A little annoyed C++ NDK Tensorflow Lite has so little support for android in terms of documentation and function examples / working code.

Any help would be appreciated

<img width="643" alt="screen shot 2018-11-26 at 8 33 11 pm" src="https://user-images.githubusercontent.com/22269225/49052595-8dcc7d00-f1ba-11e8-8bd5-4636a676af51.png">

**Comment by AryanSethi** [comment]
Any answer to this ?
How are tflite files encoded ?
