### ISSUE TITLE
tensorflow  - gpu issue

### ISSUE THREAD

**Issue by anandh02** [tensorflow/tensorflow#23984]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

System information

OS : Windows 10
TensorFlow installed from (source or binary): from pip
TensorFlow version: 1.11.0
Python version: 3.6
Installed using virtualenv? pip? conda?: conda
Bazel version (if compiling from source): No
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: 10
GPU model and memory: Nvidia 1050Ti

**Describe the problem**
Recently I tried updating my tensor flow and later on, my tensorflow-gpu stopped working.
Now I have downgraded to 1.11.0 but then still my tensorflow-gpu is not working.

nvidia-smi is working fine. 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 416.34       Driver Version: 416.34       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P8    N/A /  N/A |     78MiB /  4096MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|==================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

tf.test.is_gpu_available(
cuda_only=False,
min_cuda_compute_capability=None
)

I ran this, its coming false

then , 
I ran this sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
Device mapping: no known devices.
2018-11-26 17:27:10.277030: I tensorflow/core/common_runtime/direct_session.cc:291] Device mapping:

it's coming empty, I read lot of threads usually people had error with cuda, by installing that it worked for lot of people.

But then in my case things were working fine earlier, now it got messed up and cuda is installed properly.

why should I do?

**Comment by ymodak** [comment]
Duplicate of #2372

**Comment by anandh02** [comment]
I'm Cuda 9, I have downgraded that and still facing the same issue

**Comment by ymodak** [comment]
Your nvidia-smi output reflects that you are using CUDA 10. Can you confirm? I would recommend doing a fresh install using cuda 9 if possible.

**Comment by ymodak** [comment]
Firstly uninstall cuda 10 toolkit 10 and install cuda 9 later. In addition to that you will have to update the environment variables paths as well. Refer this [windows setup guide](https://www.tensorflow.org/install/gpu#windows_setup) to know more.

**Comment by anandh02** [comment]
![image](https://user-images.githubusercontent.com/12907396/49061649-87480080-f1ce-11e8-94ce-26dc2bf8fe1b.png)

I don't have Cuda 10 in my system, I'm not sure why it is showing up in nvidia-smi

**Comment by ymodak** [comment]
@gunan Can you please take a look?

**Comment by anandh02** [comment]
Now i'm getting this error too,

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Tools\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Tools\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Tools\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Tools\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

I checked the other threads regarding this DLL issue with Cuda 10.

But then, I don't have Cuda 10 installed in my system

**Comment by anandh02** [comment]
I fixed the issue, thanks for the help  :)

**Comment by ymodak** [comment]
Glad it worked for you. Can you please comment below the steps you followed? Thanks!

**Comment by anandh02** [comment]
I'm still not sure whats the exact issue is, because in Nvidia-smi still shows Cuda 10.

Steps followed:
Pretty much reinstalled everything from scratch :  tensorflow, tensorflow- gpu, cuda

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
