### ISSUE TITLE
The tensorflow/tensorflow:custom-op is missing from DockerHub

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#24006]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): docker pull tensorflow/tensorflow:custom-op
- TensorFlow version: n/a
- Python version: n/a
- Installed using virtualenv? pip? conda?: `docker pull`
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

While trying to pull `tensorflow/tensorflow:custom-op` to build custom ops, I noticed that `custom-op` tag is missing. (The tag was still there around 11/20/2018)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
ubuntu@ubuntu:~/tensorflow_io$ docker pull tensorflow/tensorflow:custom-op
Error response from daemon: manifest for tensorflow/tensorflow:custom-op not found
```
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by angersson** [comment]
Sorry, this was my bad. I was doing doing some maintenance and deleted the `custom-op` image by mistake. I've restored the tag now.
