### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.lite' has no attribute 'OpsSet'

### ISSUE THREAD

**Issue by hufangjian** [tensorflow/tensorflow#24001]
### System information
- **OS Platform and Distribution (centos7.3)**:
- **TensorFlow installed from  binary:from binary
- **TensorFlow version **:1.12
- **Python version**:3.6
- **CUDA/cuDNN version**:9.1
- **GPU model and memory**:K80

### Describe the problem
when i follow the tensorflow lite tutorial. 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/using_select_tf_ops.md
it gets this error.
### Source code / logs
import tensorflow as tf
import sys
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "1"
converter = tf.lite.TFLiteConverter.from_saved_model('model',input_shapes={"input":[1]})
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                         tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
converter.post_training_quantize = True
tflite_model_quantize = converter.convert()
open("converted_model_quantize_save.tflite", "wb").write(tflite_model_quantize)

INFO:tensorflow:Restoring parameters from model/variables/variables
INFO:tensorflow:The given SavedModel MetaGraphDef contains SignatureDefs with the following keys: {'serving_default'}
INFO:tensorflow:input tensors info: 
INFO:tensorflow:Tensor's key in saved_model's tensor_map: input
INFO:tensorflow: tensor name: input_6:0, shape: (1), type: DT_FLOAT
INFO:tensorflow:output tensors info: 
INFO:tensorflow:Tensor's key in saved_model's tensor_map: out
INFO:tensorflow: tensor name: out_6:0, shape: (1), type: DT_FLOAT
INFO:tensorflow:Restoring parameters from model/variables/variables
INFO:tensorflow:Froze 1 variables.
INFO:tensorflow:Converted 1 variables to const ops.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-2cf72d9b817e> in <module>()
      7 
      8 converter = tf.lite.TFLiteConverter.from_saved_model('model',input_shapes={"input":[1]})
----> 9 converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
     10                          tf.lite.OpsSet.SELECT_TF_OPS]
     11 tflite_model = converter.convert()

AttributeError: module 'tensorflow._api.v1.lite' has no attribute 'OpsSet'

**Comment by aselle** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by utkarsh-VRL** [comment]
I have the same issue trying to convert model using select ops, as described in:
[https://github.com/tensorflow/tensorflow/issues/21526](https://github.com/tensorflow/tensorflow/issues/21526)

Command that I tried:
`
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
`

**OS:** Linux Fedora release 28
**TF version:** 1.13.0-dev20181127 (binary from conda)

**Comment by akotlarsky** [comment]
I have the same problem (module 'tensorflow.contrib.lite.python.lite' has no attribute 'OpsSet') when trying to convert a frozen graph ,pb file to a TensorFlow Lite FlatBuffer file in Raspberry Pi 3B+ by running:

python3 /home/pi/tensorflow/tensorflow/contrib/lite/python/tflite_convert.py --output_file=fruit_model.tflite --graph_def_file=frozen_graph.pb --input_arrays=X --output_arrays=softmax.

I am getting the same error:
AttributeError: module 'tensorflow.contrib.lite.python.lite' has no attribute 'OpsSet'

TensorFlow version is 1.11.0.

Please help.

**Comment by utkarsh-VRL** [comment]
Use `tflite_convert` tool instead of doing the conversion through code. That is what worked for me. I used nightly build for this (week old as of writing this post).

**Comment by alanchiao** [comment]
@hufangjian : please try the nightly build as bug@ suggested and let us know if it works!

**Comment by akotlarsky** [comment]
It does not work for me. I am using TensorFlow version is 1.11.0 on Raspberry Pi.  Here is the command line I am executing:

./tflite_convert --output_file=/home/pi/sols/demo/src/image_classification/network/fruit_models/fruit_model.tflite --graph_def_file=/home/pi/sols/demo/src/image_classification/network/fruit_models/frozen_graph.pb --input_arrays=X --output_arrays=softmax --target_ops=TFLITE_BUILTINS,SELECT_TF_OPS

Here is the error:
RuntimeError: TOCO failed see console for info.
b'/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module \'tensorflow.python.framework.fast_tensor_util\' does not match runtime version 3.5\n  return f(*args, **kwds)\n/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412\n  return f(*args, **kwds)\nTraceback (most recent call last):\n  File "/bin/toco_from_protos", line 7, in <module>\n    from tensorflow.contrib.lite.toco.python.toco_from_protos import main\n  File "/home/pi/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/toco/python/toco_from_protos.py", line 22, in <module>\n    from tensorflow.contrib.lite.toco.python import tensorflow_wrap_toco\n  File "/home/pi/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/toco/python/tensorflow_wrap_toco.py", line 28, in <module>\n    _tensorflow_wrap_toco = swig_import_helper()\n  File "/home/pi/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/toco/python/tensorflow_wrap_toco.py", line 24, in swig_import_helper\n    _mod = imp.load_module(\'_tensorflow_wrap_toco\', fp, pathname, description)\n  File "/usr/lib/python3.5/imp.py", line 242, in load_module\n    return load_dynamic(name, filename, file)\n  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic\n    return _load(spec)\nImportError: /home/pi/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/toco/python/_tensorflow_wrap_toco.so: undefined symbol: _ZN6tflite12tensor_utils27NeonSymmetricQuantizeFloatsEPKfiPaPfS4_S4_\n'

How can I install the nightly build in Raspberry Pi?  Doing this:
pip3 install --user --upgrade tf-nightly
gives me this message:
  Could not find a version that satisfies the requirement tf-nightly (from versions: )
No matching distribution found for tf-nightly

Any other ideas?

**Comment by alanchiao** [comment]
For tf.lite.OpsSet, note that it's available in the Python API as of this [commit](https://github.com/tensorflow/tensorflow/commit/d453dfad7c383db0ded338e8de3142a17d55910b#diff-abf1193f0cce5bd043e7e6d2357448a3) from 12/06, so it won't be available except in the tf-nightly build or the upcoming 1.13 release. 

What bug@ did should work also in the same (if not earlier) nightly build or upcoming release.

As for installing the nightly build on Raspberry Pi, please refer to this [guide](https://www.tensorflow.org/install/pip). The tf-nightly build is on PyPi (https://pypi.org/project/tf-nightly/#files) and if nothing works, I'm not personally too familiar with pip, and I suggest creating a separate issue to get help more quickly (since this is more about installation as opposed to the original issue).

hufangjian@: I'm closing from the above. If it fails, please reopen and I'll look into it more closely.
