### ISSUE TITLE
modify grpc for local_repository

### ISSUE THREAD

**Issue by zzqiang04053080** [tensorflow/tensorflow#2400]
Due to network limited, I modify grpc for local_repository in workspace.bzl file,  as shown below:

  #native.git_repository(
  native.local_repository(
    name = "grpc",
    path = "/home/jason/localDep/grpc/grpc",
    #commit = "3d62fc6",
    #init_submodules = True,
    #remote = "https://github.com/grpc/grpc.git",
  )
And when run  bazel build -c opt --config=cuda --verbose_failures --genrule_strategy=standalone //tensorflow/tools/pip_package:build_pip_package

it will report:

ERROR: /root/.cache/bazel/_bazel_root/5f279d276e3315e6a8baf89d39adcaeb/external/grpc/BUILD:514:1: no such target '//external:nanopb': target 'nanopb' not declared in package 'external' defined by /home/jason/tensor_5_9/tensorflow/WORKSPACE and referenced by '@grpc//:grpc_unsecure'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.535s

Does anyone know why?

**Comment by zzqiang04053080** [comment]
A tangle of problems.....

**Comment by mrry** [comment]
It sounds like you have checked out the `master` branch of gRPC. Subsequent updates have added a new dependency on `nanopb`, which we haven't added to TensorFlow yet. The solution is to check out exactly the named commit `3d62fc6` in your local grpc repository.

**Comment by zzqiang04053080** [comment]
@mrry    yea, it works, thank you !

**Comment by Hwhitetooth** [comment]
@mrry I checked out commit 3d62fc6. But a new issue is incurred.

`missing input file '@grpc//:src/core/lib/support/backoff.h'.`
Could you please help me work it out? Thanks a lot!
