### ISSUE TITLE
MirroredStrategy not work with estimator

### ISSUE THREAD

**Issue by JayYip** [tensorflow/tensorflow#24013]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): Docker
- TensorFlow version (use command below): 1.12.0-rc0
- Python version: 3.5.2
- CUDA/cuDNN version: V9.0.176
- GPU model and memory: TITAN Xp

**Describe the current behavior**
My code looks like
```python
dist_strategy = tf.contrib.distribute.MirroredStrategy()

run_config = tf.estimator.RunConfig(
    train_distribute=dist_strategy,
    log_step_count_steps=10)

estimator = tf.estimator.Estimator(
    model_fn,
    model_dir=params.ckpt_dir,
    params=params,
    config=run_config)

estimator.train(train_input_fn, max_steps=steps)
```

**Describe the expected behavior**
Successfully train.

**Other info / logs**
```log
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 75, in main
    estimator.train(train_input_fn, max_steps=steps)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1181, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1287, in _train_model_distributed
    grouped_estimator_spec = self._train_distribution.call_for_each_tower(
AttributeError: 'MirroredStrategy' object has no attribute 'call_for_each_tower'
```

**Comment by JayYip** [comment]
It seems `Estimator._distribution` is deprecated since r1.10 and replaced by `Estimator._train_distribution` and `Estimator._eval_distribution`. So I did modified the estimator.py as following:

From:
```python
        def get_hooks_from_the_first_device(per_device_hooks):
          return [
              self._distribution.unwrap(per_device_hook)[0]
              for per_device_hook in per_device_hooks
          ]
```
To:
```python
        def get_hooks_from_the_first_device(per_device_hooks):
          return [
              self._train_distribution.unwrap(per_device_hook)[0]
              for per_device_hook in per_device_hooks
          ]
```

Dose this workaround correct? Thanks in advanced.

**Comment by Zantares** [comment]
I got the same issue when run NCF in tensorflow-models, and I has already know that is caused by mismatching API between tensorflow and tensorflow-estimator.

TF deleted this API call_for_each_tower and used call_for_each_replica instead, but the release package of tensorflow-estimator is too old(release on Sep, 12, 2018) that still used the old API.
Tensorflow-estimator has already changed this API in their master, but they didn't release any new package and I didn't find somewhere to submit the issue, so I just answered this issue and hope someone can help to release a new estimator.

**Comment by Zhiqiang-Ye** [comment]
@Zantares @JayYip can we use git to clone the tensorflow-estimator repository (https://github.com/tensorflow/estimator#developing) and build the tensorflow-estimator master branch to walk around this issue？

**Comment by Zantares** [comment]
> @Zantares @JayYip can we use git to clone the tensorflow-estimator repository (https://github.com/tensorflow/estimator#developing) and build the tensorflow-estimator master branch to walk around this issue？

Yes, it' OK if build a locally estimator from the newest master branch. The problem is the release package is too old so that if anyone uses pip install will occur this error.

**Comment by JayYip** [comment]
Close since it's fixed in latest build.
