### ISSUE TITLE
Duplicated variable names with inner tf.keras.layers.Dense layers in eager mode

### ISSUE THREAD

**Issue by ferronsnicola** [tensorflow/tensorflow#24027]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL7 3.10.0-862.11.6.el7.x86_64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): 1.11.0
- Python version: Python 3.6.6 :: Anaconda, Inc.
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**

When creating a custom `tf.keras.Model` with custom `build()` function, the variable name scopes seem not to propagate correctly in `tf.keras.Dense` layers.

**Describe the expected behavior**

Variables of inner `tf.keras.Dense` layers should have different names, such as:
`dense/kernel:0`
`dense/bias:0`
`dense_1/kernel:0`
`dense_1/bias:0`

Right now they have the same name:
`kernel:0`
`bias:0`
`kernel:0`
`bias:0`

This is problematic for saving / loading parameters.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
import tensorflow as tf
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

tf.enable_eager_execution()
tf.executing_eagerly()


class MyModel(tf.keras.Model):
    def __init__(self):
        super().__init__(name='mymodel')
        
        self.f = tf.keras.layers.Dense(units=10)
        self.g = tf.keras.layers.Dense(units=10)

#         Workaround
#         self.f = tf.keras.Sequential([tf.keras.layers.Dense(units=10)])
#         self.g = tf.keras.Sequential([tf.keras.layers.Dense(units=10)])

    def build(self, input_shapes):
        self.f.build(input_shapes[0])
        self.g.build(input_shapes[1])
        self.built = True
    
    def call(self, x, y):
        return self.f(x) + self.g(y)


model = MyModel()
model.build([(None, 5), (None, 3)])

for v in model.variables:
    print(v.name)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by allenlavoie** [comment]
How are you saving and loading? It won't matter for `Model.save_weights` or `tf.train.Checkpoint`, which are the APIs we're moving toward.

**Comment by ferronsnicola** [comment]
I'm using tf.contrib.eager.Saver

**Comment by allenlavoie** [comment]
Thanks for the reminder. I'll add a warning and a note in the documentation. Can you try `Checkpoint`? This MNIST model is a reasonable usage example: https://github.com/tensorflow/models/blob/5324fc6628522eabbff74f2d12f0cc69d3432a2c/official/mnist/mnist_eager.py#L149

**Comment by allenlavoie** [comment]
Saver has been deprecated. Check out the [2.0 checkpointing guide](https://www.tensorflow.org/alpha/guide/checkpoints) for an API which does not depend on variable names.
