### ISSUE TITLE
ValueError: tf.enable_eager_execution must be called at program startup.

### ISSUE THREAD

**Issue by Umar-Ayub** [tensorflow/tensorflow#24023]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
NA
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
1.12.0
- Python version:
3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
9/7
- GPU model and memory:
NVIDIA GTX1080, 8GB

**Describe the current behavior**
Eager execution isn't working on a jupyter notebook with GPU. Have tried restarting the kernel multiple times. I get a ValueError: tf.enable_eager_execution must be called at program startup.

**Describe the expected behavior**
Eager Execution should work. Why isn't it working?

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
`import tensorflow as tf
`tf.enable_eager_execution()

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-e43ec884c055> in <module>()
      5 import numpy as np
      6 import tensorflow as tf
----> 7 tf.enable_eager_execution()
      8 from keras import layers
      9 from keras import models

~\AppData\Local\conda\conda\envs\DLCdependencies\lib\site-packages\tensorflow\python\framework\ops.py in enable_eager_execution(config, device_policy, execution_mode)
   5421         device_policy=device_policy,
   5422         execution_mode=execution_mode,
-> 5423         server_def=None)
   5424 
   5425 

~\AppData\Local\conda\conda\envs\DLCdependencies\lib\site-packages\tensorflow\python\framework\ops.py in enable_eager_execution_internal(config, device_policy, execution_mode, server_def)
   5465     if graph_mode_has_been_used:
   5466       raise ValueError(
-> 5467           "tf.enable_eager_execution must be called at program startup.")
   5468   context.default_execution_mode = context.EAGER_MODE
   5469   # pylint: disable=protected-access

ValueError: tf.enable_eager_execution must be called at program startup.

**Comment by harshini-gadige** [comment]
@Umar-Ayub  Can you please try in the [colab](https://colab.sandbox.google.com/drive/1rCTY1pv9jRG1_SxsOCNlZZRiEYZP5NF5) and let us know if you see the same error ?

**Comment by Umar-Ayub** [comment]
Eager Execution is working fine. I was importing a python module which had keras models inside it and that's why the code was failing since placeholders were being defined in that module.

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
