### ISSUE TITLE
Abs operator not implemented?

### ISSUE THREAD

**Issue by utkarsh-VRL** [tensorflow/tensorflow#24026]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Fedora release 28
- TensorFlow installed from (source or binary): binary (conda)
- TensorFlow version (or github SHA if from source): '1.13.0-dev20181127'

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONV_2D, DEPTHWISE_CONV_2D, L2_NORMALIZATION, MUL, RELU, SQUEEZE, SUB. Here is a list of operators for which you will need custom implementations: Abs.
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by harshini-gadige** [comment]
@utkarsh-VRL  Please refer [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tf_ops_compatibility.md) which gives information about supported ops by TF Lite.
