### ISSUE TITLE
Does XLA GPU ptxas recompile on each session.run()?

### ISSUE THREAD

**Issue by proteneer** [tensorflow/tensorflow#24025]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.12
- Doc Link: https://www.tensorflow.org/xla/tfcompile

**Describe the documentation issue**

I'm seeing undocumented behavior where NVPTXCompiler::CompilePtxOrGetCachedResult(const string& ptx) is being called with new ptx code on each invocation of session.run().

1. Is it intended behavior that XLA JIT is invoked with each session.run() call? I'm currently calling session.run() multiple times by invoking q.dequeue() repeatedly.
2. Currently it takes longer to compile the ptxas code than to actually execute the rest of the code.
3. Should we restructure our code so we minimize the number of session.run() calls to make JIT behave nicely?

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by proteneer** [comment]
To add more information, it looks like putting the dequeue op inside a tf.while_loop() still triggers XLA recompiles.

**Comment by jlebar** [comment]
XLA should invoke ptxas only once per unique compilation unit ("HloModule") that it sees.  In other words, there is caching.

Without seeing your code, what I suspect is that the input shapes are dynamic, so every time we invoke session.run, it's a different HloModule.  See "caveats" section in https://medium.com/tensorflow/pushing-the-limits-of-gpu-performance-with-xla-53559db8e473 for details about this.

You should be able to verify that this is what's happening by setting some flags in the environment variable for debugging.  Full set of flags is in xla.proto.  You could try `XLA_FLAGS= --xla_generate_hlo_text_to=/tmp/whatever` -- you will probably see that each of the modules XLA is compiling is slightly different.

**Comment by proteneer** [comment]
Thanks that's what I suspected as well. I have a custom op that does something like a dynamic partition to create 4 blocks of (?A, 256), (?B, 256), (?C, 256), (?D, 256) where each block 0 <= ?X < 1024. I had hoped that the *worst* case scenario is that it would generate 1024*4=4096 custom ptx blocks for all four possible values of ?A, ?B, ?C, ?D, but the ?X shapes cascades to all downstream operations resulting in lots of Hlomodules. 

PS. I've verified that feeding in the exact same identical batch (resulting in the same ?A, ?B, ?C, ?D) no longer triggers the recompile. 

Is there a way to avoid optimizing over the 0th dimension? I presume we see the same issue in general when we try to train with widely varying batch sizes.

**Comment by jlebar** [comment]
> Is there a way to avoid optimizing over the 0th dimension? I presume we see the same issue in general when we try to train with widely varying batch sizes.

The requirement that all of the dimensions be known upfront is pretty fundamental to XLA.  We actually *are* looking at relaxing this, but it's a really big change and we're in the very beginnings of it right now.

For your purposes what I'd usually recommend is bucketing the 0'th dimension, if that's possible.  That is, instead of generating all possible shapes, pad out to e.g. powers of two.  Dunno if that's possible in your situation.

**Comment by proteneer** [comment]
Thanks - I'll see what I can do to work around the issue. Looking forward to relaxing the constraint. But ofr now, closing this issue.
