### ISSUE TITLE
[ppc64le] Getting error installing a custom tensorflow wheel on Power8 with NVIDIA P100 with anaconda3

### ISSUE THREAD

**Issue by ghltshubh** [tensorflow/tensorflow#24020]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
LSB Version:	:core-4.1-noarch:core-4.1-ppc64le
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.4 (Maipo)
Release:	7.4
Codename:	Maipo

- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.8
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?: conda (anaconda3 5.2)
- Bazel version (if compiling from source): 0.10.0
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: 8.0/ 7.0.5
- GPU model and memory: NVIDIA Tesla P100/ 16 GB

**Describe the problem**
Getting the following error while building a tensorflow wheel on power8 system.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
CUDA_VER=8.0
CUDNN_VER=7.0.5
NCCL_VER=2.3.7-1
BAZEL_VER=0.10.0
TF_VER=1.8.0
CONDA_VER=5.2.0
PY_VER=3.6

#module load cuda/8.0.61-1
CUDA_DIR=$(pwd)/8.0.61-1

#install pre-built anaconda
wget https://repo.anaconda.com/archive/Anaconda3-$CONDA_VER-Linux-ppc64le.sh -O anaconda3.sh
bash ./anaconda3.sh -b -p anaconda3
export PATH=$(pwd)/anaconda3/bin:$PATH
pip install --upgrade pip
pip install keras_applications==1.0.6 --no-deps
pip install keras_preprocessing==1.0.4 --no-deps
#install bazel 
wget https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VER/bazel-$BAZEL_VER-dist.zip
unzip bazel-$BAZEL_VER-dist.zip -d bazel
cd bazel
./compile.sh
export PATH=$(pwd)/output:$PATH
cd ../

#workaround for nccl2 
git clone https://github.com/NVIDIA/nccl
cd nccl
git checkout v$NCCL_VER
make -j160 src.build CUDA_HOME=$CUDA_DIR
make pkg.txz.build CUDA_HOME=$CUDA_DIR
tar -xf  build/pkg/txz/* -C ..
cd ..
ln -s nccl_$NCCL_VER* nccl2
cd nccl_$NCCL_VER*
ln -s LICENSE.txt NCCL-SLA.txt
cd ..

CUDNN_DIR=$CUDA_DIR

#setup env var
export PYTHON_BIN_PATH=$(pwd)/anaconda3/bin/python3
export PYTHON_LIB_PATH=$(pwd)/anaconda3/lib/python$PY_VER/site-packages
export TF_NEED_MKL=0
export CC_OPT_FLAGS="-march=native"
export TF_NEED_JEMALLOC=0
export TF_NEED_GCP=0
export TF_NEED_HDFS=0
export TF_ENABLE_XLA=0
export TF_NEED_OPENCL=0
export TF_NEED_CUDA=1
export TF_CUDA_CLANG=0
export TF_CUDA_VERSION=$CUDA_VER
export CUDA_TOOLKIT_PATH=$CUDA_DIR
export TF_CUDNN_VERSION=$CUDNN_VER
export CUDNN_INSTALL_PATH=$CUDNN_DIR
export TF_CUDA_COMPUTE_CAPABILITIES="6.0"
export TF_NEED_VERBS=0
export TF_NEED_AWS=0
export TF_NEED_NGRAPH=0
export TF_NEED_S3=0
export TF_NEED_GDR=0
export TF_NEED_OPENCL_SYCL=0
export GCC_HOST_COMPILER_PATH=/usr/bin/gcc
export TF_NEED_MPI=0
export TF_NEED_KAFKA=0
export TF_NEED_ROCM=0
export TF_NEED_IGNITE=0
export TF_NEED_TENSORRT=0
export TF_SET_ANDROID_WORKSPACE=0
export TF_NCCL_VERSION=$(echo $NCCL_VER | cut -d. -f1,2)
export NCCL_INSTALL_PATH="$(pwd)/nccl2"
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$CUDA_DIR/lib64/stubs

#build tensorflow
git clone --recursive https://github.com/tensorflow/tensorflow
cd tensorflow
git checkout v$TF_VER
./configure
bazel build -c opt --config=cuda tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package ../tensorflow_pkg

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
ERROR: /autofs/nccs-svm1_home1/shubhankar/summitdev/tensorflow/tensorflow/core/kernels/BUILD:1201:1: output 'tensorflow/core/kernels/_objs/gather_functor_gpu/tensorflow/core/kernels/gather_functor_gpu.cu.pic.o' was not created
INFO: From Compiling tensorflow/core/kernels/quantization_utils.cc:
In file included from tensorflow/core/kernels/quantization_utils.cc:16:0:
./tensorflow/core/kernels/quantization_utils.h:35:0: warning: "GEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK" redefined [enabled by default]
 #define GEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from tensorflow/core/kernels/quantization_utils.cc:16:0:
./tensorflow/core/kernels/quantization_utils.h: In function 'void tensorflow::RequantizeManyInNewRangeReference(const qint32*, tensorflow::int64, float, float, float, float, tensorflow::quint8*)':
./tensorflow/core/kernels/quantization_utils.h:269:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t index = 0; index < count; ++index) {
                                  ^
ERROR: /autofs/nccs-svm1_home1/shubhankar/summitdev/tensorflow/tensorflow/core/kernels/BUILD:1201:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 221.932s, Critical Path: 161.23s
FAILED: Build did NOT complete successfully
```

**Comment by harshini-gadige** [comment]
@ghltshubh  Hi, please use latest tensorflow version with Bazel 0.15.

**Comment by harshini-gadige** [comment]
@wdirons   PTAL as this is related to power8

**Comment by wdirons** [comment]
@ghltshubh, can you attach the full build log as a file. I don't think I'm seeing the real error in the output above.  I do know for TensorFlow 1.8 this fix had to be cherry-picked in. https://github.com/tensorflow/tensorflow/commit/8f8a3c5151a674b3496691af49c3aa063841f292

**Comment by wdirons** [comment]
I don't think it is related to the failure, but should use:

`export CC_OPT_FLAGS='-mcpu=power8 -mtune=power8'`

for the CC_OPT_FLAGS

**Comment by jayfurmanek** [comment]
Another note on the keras add-ons. Since you are using Anaconda, instead of pip you can just:
`conda install  keras-applications`
`conda install keras-preprocessing`

**Comment by ghltshubh** [comment]
@jayfurmanek conda install keras-applications doesn't work. 
```
PackagesNotFoundError: The following packages are not available from current channels:

  - keras_applications

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-ppc64le
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-ppc64le
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-ppc64le
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-ppc64le
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://conda.anaconda.org/conda-forge/linux-ppc64le
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

@wdirons here is the full build log you asked for(I used bazel 0.11.1 but that doesn't matter the error is still the same):
https://gist.github.com/ghltshubh/68784ff142390c4c52bc1061f62e1533

**Comment by jayfurmanek** [comment]
look for `keras-applications` and `keras-preprocessing`

**Comment by jayfurmanek** [comment]
Installing those from Anaconda will pull in `numpy` as well which should get you past that other issue.

I just did a couple builds on my P8/P100 box, similar to what you did above. I did see some cuda kernel errors when building against cuda8.0. I tried again against cuda9.2 and it built fine (assuming you have @wdirons patch, of course)

I'd recommend upgrading your cuda if you can. We really didn't get ppc64le builds fixed upstream until the cuda9.x timeframe.

**Comment by ghltshubh** [comment]
I don't have cuda 9.2 on power8 but cuda 9.0 instead. I will try with 9.0 and hope it works.

**Comment by ghltshubh** [comment]
@wdirons @jayfurmanek why am I getting
```
-bash-4.2$ git cherry-pick 8f8a3c5
fatal: bad revision '8f8a3c5'
```

**Comment by wdirons** [comment]
I can't explain why git cherry-pick is failing. From this page https://help.github.com/articles/commit-exists-on-github-but-not-in-my-local-clone/, the only possible reason I think would be: 
Someone force pushed over the commit.

try this instead:
```
wget https://github.com/tensorflow/tensorflow/commit/8f8a3c5.patch
patch -p1 third_party/png.BUILD 8f8a3c5.patch
```

**Comment by ghltshubh** [comment]
@wdirons Nothing works as of now. I only have the following CUDA versions available I want to know if they can anyhow will help. 

- 8.0.35  
- 8.0.44  
- 8.0.54  
- 8.0.61-1  
- 9.0.69

I have tried 8.0.61-1 with the patch doesn't help. I have tried 9.0.69 that also doesn't help but has a different error output

```
ERROR: /autofs/nccs-svm1_home1/shubhankar/summitdev/tensorflow/third_party/py/numpy/BUILD:11:1: no such package '@local_config_python//': Traceback (most recent call last):
	File "/autofs/nccs-svm1_home1/shubhankar/summitdev/tensorflow/third_party/py/python_configure.bzl", line 291
		_create_local_python_repository(repository_ctx)
	File "/autofs/nccs-svm1_home1/shubhankar/summitdev/tensorflow/third_party/py/python_configure.bzl", line 255, in _create_local_python_repository
		_get_numpy_include(repository_ctx, python_bin)
	File "/autofs/nccs-svm1_home1/shubhankar/summitdev/tensorflow/third_party/py/python_configure.bzl", line 239, in _get_numpy_include
		_execute(repository_ctx, [python_bin, "-c",..."], <2 more arguments>)
	File "/autofs/nccs-svm1_home1/shubhankar/summitdev/tensorflow/third_party/py/python_configure.bzl", line 54, in _execute
		_fail("\n".join([error_msg.strip() if ... ""]))
	File "/autofs/nccs-svm1_home1/shubhankar/summitdev/tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
		fail(("%sPython Configuration Error:%...)))
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
 and referenced by '//third_party/py/numpy:headers'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Loading failed
INFO: Elapsed time: 86.170s
FAILED: Build did NOT complete successfully (108 packages loaded)
```

**Comment by ghltshubh** [comment]
@wdirons I was able to install tf1.8 git checkout 397f04a and it works fine on single node but I need to install horovod as well in order to run it on cluster but I am having issues building horovod from source because tf is missing some sub-directories such as /compiler inside 
/miniconda3/envs/tf_p3.5/lib/python3.5/site- packages/tensorflow/include/tensorflow/ which I was able to copy from tf git repo and build horovod from source but I am not sure if that is it or there are more missing sub-directories.

**Comment by jayfurmanek** [comment]
@ghltshubh To help others, can you post what you did to get past your error.

I did go back and build tf 1.8 against cuda 9.0.176 and had no issues. Was you problem just an environment issue? (didn't have numpy installed?)

**Comment by ghltshubh** [comment]
I have access to CUDA 9.0.69 only. There must have been some changes in the later version 9.0.176 which you used. I just followed the standard procedure that I mentioned in the issue above just use CUDA 8.0.61-1 and tf 1.8 397f04a and it will build fine.
