### ISSUE TITLE
Major memory leak after calling `tf.estimator.DNNClassifier.train` with certain `tf.train` optimizers.

### ISSUE THREAD

**Issue by yoavz** [tensorflow/tensorflow#24047]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Reproduced on OS X and Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: not sure.
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.11 and 1.12 tested
- Python version: 3.6.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: (tested on CPU)
- GPU model and memory: (tested on CPU)

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
When using the pre-canned `DNNClassifier` together with `tf.train.RMSPropOptimizer`, I noticed that a `tf.Graph()` instance is left allocated in memory _after_ an `estimator.train()` call terminates. When running `estimator.train()` in a loop N times, there will be N `tf.Graph()` instances allocated in memory. Therefore, calling `estimator.train()` in a loop will lead to unbounded memory growth, and eventually, an OOM error.

To track down the root cause of this behaviour, I have used the [`objgraph`](https://mg.pov.lt/objgraph/) dependency together with the [`iris premade estimator`](https://github.com/tensorflow/models/blob/master/samples/core/get_started/premade_estimator.py) example. The script is attached in the code section. After 5 iterations of `train()`, the following is a visualization of all the `tf.Graph` instances that exist in memory (a total of 5):

![iter-4](https://user-images.githubusercontent.com/2341691/49243825-2cc3c580-f3c3-11e8-8909-6ef4d41a1f41.png)

You can clearly see that the root cause is a `_slots` attribute on `tf.train.RMSPropOptimizer` that saves a reference to some variable associated with the graph every time `train()` runs. 

I have noticed this behaviour with `tf.train.AdamOptimizer`, `tf.train.RMSPropOptimizer`, and `tf.train.AdadeltaOptimizer`. I would be willing to bet that most provided optimizers that save some state in the optimization procedure run into this same issue. I have observed that this issue does _not_ occur with optimizers that _do not_ save state (see below).

I would also be willing to bet that this issue is not specific to `DNNClassifier` and occurs with many different pre-canned and custom estimators. However, I have not yet investigated reproducing this issue on other types of estimators. 

**Describe the expected behavior**
The expected behaviour is that the `tf.Graph()` instance used by an invocation of `train()` is garbage collected by the Python GC after `train()` terminates. I've observed this expected behaviour when using `tf.train.GradientDescentOptimizer` and `tf.train.AdagradOptimizer`. 

**Code to reproduce the issue**
[memory-leak-example.zip](https://github.com/tensorflow/tensorflow/files/2630449/memory-leak-example.zip)

The above code is a modified version of the [`iris premade estimator`](https://github.com/tensorflow/models/blob/master/samples/core/get_started/premade_estimator.py) example to loop over `train()` multiple times. It requires the [`objgraph`](https://mg.pov.lt/objgraph/) to show the peak memory growth every iteration and generate an visualization of in-memory `tf.Graph` instances. 

Here is an example log provided of an example invocation: `python premade_estimator.py --optimizer=rmsprop`

[rmsprop.log](https://github.com/tensorflow/tensorflow/files/2630465/rmsprop.log)

Note the object growth result after the 5th iteration. As can be seen, 5 `tf.Graph` instances remain in memory, along with all the `Tensor`, `TensorShape`, `Dimension`, and other objects that go along with it.
```
Object growth after iteration 4
tuple                         82229    +14171
list                          21693     +2862
dict                          24251     +2475
TensorShape                    2806      +561
Tensor                         2775      +555
Operation                      2745      +549
_InputList                     2735      +547
Dimension                      2455      +491
cell                           6487      +312
function                      31199      +218
weakref                        5083       +25
Variable                         95       +19
SaveSliceInfo                    90       +18
set                            1409        +8
CondContext                      30        +6
PartitionedVariable              30        +6
type                           3077        +5
builtin_function_or_method     3143        +4
OrderedDict                      48        +1
Condition                        10        +1
deque                            11        +1
_local                            8        +1
Graph                             5        +1
GroupLock                         5        +1
TraceableStack                    5        +1
ScopedTFGraph                     5        +1
_VariableScopeStore               5        +1
_VariableStore                    5        +1
Saver                             5        +1
TFShouldUseWarningWrapper         5        +1
BulkSaverBuilder                  5        +1
VariableScope                     5        +1
Graph written to /var/folders/rc/_2lrng15575d3bsd9t75br840000gn/T/objgraph-sejl5tm3.dot (276 nodes)
Image generated as /tmp/iter-4.png
```

**Comment by karmel** [comment]
@tanzhenyu -- this hopefully won't be an issue with the 2.0 optimizers? Calling train in a loop is fairly standard for multiple epochs, and the fact that it happens only with RMSProp implies it's a bug that should be resolvable. Assigning to you to test with the new optimizers.

**Comment by yoavz** [comment]
@karmel It happens with more than just RMSProp -- I've reproduced it with AdamOptimizer and AdadeltaOptimizer as well. Based on this, I would guess it happens with any optimizer that maintains some state variable during training (e.g. momentum).

**Comment by tanzhenyu** [comment]
@yoavz Karmel was referring to optimizers that currently reside in /python/keras/optimizer_v2. I think they shouldn't create the same issue, but I will test it given some time next week. If you could contribute to the testing that'd be great as well!

**Comment by Viscent** [comment]
It seems that there currently no solution for this bug,however there is a simple workaround for this bug:
By leveraging tensoflow's `warm start` support, we can "split" the total epochs we expect to run into serveral 'parts'. For each 'part' we start a subprocess,the real training will be carried in this subprocess ,and these subprocesses will be started one after another. And, with the help of `warm start`,
each subprocess's training will proceed on with the result(parameters etc,) of the previous subprocess.

For exmple, if we want to run epochs of 62, and suppose each subprocess will at most run 20 epochs(of the total epochs of 100), then we can:
start subprocess1(it run epoches of 20)
subprocess1 finishes
start subprocess2(it run epoches of 20)
subprocess2 finishes
start subprocess3(it run epoches of 20)
subprocess3 finishes
start subprocess3(it run epoches of 2)

**Comment by tanzhenyu** [comment]
Can you try 1) upgrading to latest version, preferably nightly, 2) using tf.keras.optimizers.RMSProp?

**Comment by wurenshangu** [comment]
I've got the same problem.

**Comment by mohantym** [comment]
Hi @yoavz !We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!
