### ISSUE TITLE
Pruning: Multi-GPU support

### ISSUE THREAD

**Issue by barrh** [tensorflow/tensorflow#24043]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): modified models/official/resnet/resnet_model.py to utilize Pruning's masked layers.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v1.10.0
- Python version: 3.5.2
- Bazel version (if compiling from source): 16.1
- GCC/Compiler version (if compiling from source): gcc
- CUDA/cuDNN version: 8/6
- GPU model and memory: x2 nvidia titan Xp

**Describe the current behavior**
Multi-GPU training session of modified tensorflow/models for pruning, the session won't boot.
The same modified Resnet model _does_ execute iff num_gpus=1.

The error is:
ValueError: You must specify an aggregation method to update a MirroredVariable in Tower Context.
Raised from tensorflow/contrib/distribute/python/values.py", line 336

[out_batch64.log](https://github.com/tensorflow/tensorflow/files/2629288/out_batch64.log)

**Comment by harshini-gadige** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by barrh** [comment]
Sure. Just clone my fork of models @ https://github.com/barrh/models

From models directory, call official/resnet/imagenet_main.py.
Make sure to include the following flags:
--rv=2 --sparse --num_gpus=2

**Comment by harshini-gadige** [comment]
> Sure. Just clone my fork of models @ https://github.com/barrh/models
> 
> From models directory, call official/resnet/imagenet_main.py.
> Make sure to include the following flags:
> --rv=2 --sparse --num_gpus=2

@azaks2  Any thoughts?

**Comment by bupt1409** [comment]
I meet the same problem.hope for answer

**Comment by rthadur** [comment]
As the Contrib folder has been depreciated this request is no longer valid. Please check this latest documentation for pruning here https://www.tensorflow.org/model_optimization/guide/pruning . Thank you
