### ISSUE TITLE
The performance of transpose_conv op in TensorFlow Lite

### ISSUE THREAD

**Issue by ljdang** [tensorflow/tensorflow#24059]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
**Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
**Linux Ubuntu 14.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
**Meizu 16th**
- TensorFlow installed from (source or binary):
**benchmark_model is built form source**
- TensorFlow version (use command below):
**master**
- Python version:
**Python 3.5.3**
- Bazel version (if compiling from source):
**0.16.1**
- GCC/Compiler version (if compiling from source):
**4.9.4**
- CUDA/cuDNN version:
**No**
- GPU model and memory:
**N/A**

**Describe the current behavior**
I wanted to deploy a trained model on Android devices with TensorFlow Lite, but it was quite slow.
Then, I profiled the model(.tflite) with the benchmark_model tool, and found that the transpose_conv op took too much time. The summary by node type shown below:
![screenshot from 2018-11-30 11 11 48](https://user-images.githubusercontent.com/21071150/49267677-8f39c600-f496-11e8-9e91-1da5dd9f4603.png)

When I profiled the same model(.pb) used to convert to .tflite, I found that the transpose_conv achieving fast inference speed. The summary by node type shown below:
![screenshot from 2018-11-30 11 04 33](https://user-images.githubusercontent.com/21071150/49269045-d9727580-f49d-11e8-8d4c-84e965350420.png)

It seems like the transpose_conv op in TensorFlow Lite is much slower than that in TensorFlow Mobile?

**Comment by jdduke** [comment]
Thanks for the report, can you provide the exact build options you used to build `benchmark_model` from source? I'm also assuming this was single-threaded execution?

**Comment by ljdang** [comment]
@jdduke I build benchmark_model according to the document TFLite Model Benchmark Tool.(https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark)
bazel build -c opt \
  --config=android_arm \
  --cxxopt='--std=c++11' \
  --copt=-DTFLITE_PROFILING_ENABLED \
  tensorflow/lite/tools/benchmark:benchmark_model

**Comment by jdduke** [comment]
Thanks. More recently we've been recommending "--config=android_arm64" to get the most accurate performance numbers, but I suspect the delta remains the same. We'll take a look, though I should note that it looks like TensorFlow Lite is still ~15-20% faster overall for this model?

It would also help if you could either send me the model (or a minimal repro) directly, or at least give the general sizes used here. Thanks!

**Comment by ljdang** [comment]
@jdduke The models shown here:
[models.zip](https://github.com/tensorflow/tensorflow/files/2719886/models.zip)
And I also found that time cost was quite different with execution within the Android app (tflite.run(imgData, outputArray)).

**Comment by jdduke** [comment]
> And I also found that time cost was quite different with execution within the Android app (tflite.run(imgData, outputArray)).

Can you add some more details about this? How did the performance differ relative to running the native benchmark_model? Is your imgData a ByteBuffer or multi-dimensional array?

**Comment by ljdang** [comment]
@jdduke The model used to test the difference:
[model.zip](https://github.com/tensorflow/tensorflow/files/2753865/model.zip)
The imgData is ByteBuffer, and the outputArray is multi-dimensional array, according to the TFLite Java Demo. The timecost to run model inference is about 170ms.
But I profiled the model with the benchmark_model tool, the summary by node type shown below:
![screenshot from 2019-01-14 10 23 38](https://user-images.githubusercontent.com/21071150/51094314-bbab6680-17e6-11e9-9f05-035cef2c7d57.png)
The timecost is about 62ms.
I also test the experimental Android APK wrapper for the benchmark model, and the timecost is about 62ms.
Maybe there is bug in tensorflow-lite.aar or benchmark_model tool. Please have a look.

**Comment by jdduke** [comment]
Are you using the same shape with the Java demo and benchmark_model? I'm not able to repro the large discrepancy in latency. You might also check the Java demo you build to make sure it's using the 64-bit libraries.

**Comment by stakemura** [comment]
@jdduke In my environment, I confirmed TF Lite is x3 - x10 slower than TF mobile under same model including transpose_conv op, same in/out shape condition on Windows 64bit / MacOS X / Android arm64.
I will show the detail of the benchmark result within days.

**Comment by jdduke** [comment]
Keep in mind that TF mobile enables threading by default, whereas TF lite does not. Please test TF mobile single-threaded to form an accurate comparison.

**Comment by stakemura** [comment]
Thanks. I've already checked both single and multiple threading with C++ benchmark model tool (not Java demo).

**Comment by bjtommychen** [comment]
> @jdduke I build benchmark_model according to the document TFLite Model Benchmark Tool.(https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark)
> bazel build -c opt 
> --config=android_arm 
> --cxxopt='--std=c++11' 
> --copt=-DTFLITE_PROFILING_ENABLED 
> tensorflow/lite/tools/benchmark:benchmark_model

@ljdang 
when I run benchmark_model, avg time cost displayed, but other is empty like below.
would you help on this ?

============================== Run Order ==============================
                     [node type]          [start]         [first]        [avg ms]            [%]          [cdf%]          [mem KB]      [times called]  [Name]

============================== Top by Computation Time ==============================
                     [node type]          [start]         [first]        [avg ms]            [%]          [cdf%]          [mem KB]      [times called]  [Name]

Number of nodes executed: 0
============================== Summary by node type ==============================
                     [Node type]          [count]         [avg ms]          [avg %]         [cdf %]       [mem KB]      [times called]
