### ISSUE TITLE
Android demo build fails with bazel

### ISSUE THREAD

**Issue by Jeanbouvatt** [tensorflow/tensorflow#24066]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
source
- TensorFlow version:
1.12
- Python version:
2.7.15
- Installed using virtualenv? pip? conda?:
pip
- Bazel version (if compiling from source):
0.15.1
- GCC/Compiler version (if compiling from source):
5.5
- CUDA/cuDNN version:
9.2 / 7.1.3
- GPU model and memory:
Nvidia GTX 1080

**Describe the problem**
When trying to build android demo with bazel following the  [README]( https://github.com/tensorflow/tensorflow/tree/r1.12/tensorflow/examples/android) 
Build command with bazel fails.
Thank you for your help. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
(cuda_env)  jean@pc:~/tensorflow$ bazel build //tensorflow/examples/android:tensorflow_demo
(full details of output in logs)
 ...
fatal error: too many errors emitted, stopping now [-ferror-limit=]
11 warnings and 20 errors generated.
Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 78.831s, Critical Path: 18.32s
INFO: 304 processes: 303 local, 1 worker.
FAILED: Build did NOT complete successfully

**Any other info / logs**
[log.txt](https://github.com/tensorflow/tensorflow/files/2632785/log.txt)

**Comment by alanchiao** [comment]
@Jeanbouvatt : I would recommend trying out Tensorflow Lite (see the vision demos [here](https://www.tensorflow.org/lite/demo_android)) as it's currently the recommended on-device inference solution.

It's unclear to me if we are still maintaining //tensorflow/examples/android:tensorflow_demo. Assigning shashishekhar@ to comment.

**Comment by shashishekhar** [comment]
@Jeanbouvatt : I am going to send a patch to fix the instructions, but the error message means that you need to pass --cxxopt='--std=c++11' to build the demo.
So the command should be the following

```bash
bazel build --cxxopt='--std=c++11' -c opt //tensorflow/examples/android:tensorflow_demo
```

**Comment by Jeanbouvatt** [comment]
Thank you for you time, I will try using tensorflow lite.
