### ISSUE TITLE
cann't import tensorflow-gpu 1.12 on windows

### ISSUE THREAD

**Issue by xun6000** [tensorflow/tensorflow#24063]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by FredVaugeois** [comment]
Have you followed all the instructions in this [guide](https://www.tensorflow.org/install/gpu)? You need to make sure your environment variables are correctly set and that you have correctly installed the correct pip package following this [guide](https://www.tensorflow.org/install/pip) -> "pip3 install tensorflow-gpu --upgrade". Also, make sure you have a [CUDA enabled GPU](https://developer.nvidia.com/cuda-gpus) (and that you have indeed installed CUDA/cuDNN - I suggest CUDA 9.0 and cuDNN 7).

**Comment by ymodak** [comment]
Duplicate of #24064
