### ISSUE TITLE
CMake build Tensorflow C++ on Windows 10 Error : Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED - failed

### ISSUE THREAD

**Issue by bwang482** [tensorflow/tensorflow#24076]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version: the latest version
- Python version: 3.6
- Bazel version (if compiling from source): I am using CMake
- GCC/Compiler version (if compiling from source): gcc 6.30
- CUDA/cuDNN version: Installing only the CPU version
- I am also using Microsoft Visual Studio Community 2017 Version 15.9.3, btw

**Describe the problem**
I am following the "Step by step Windows Build" from https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake. However, at step 3, I can't seem to pass `Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED`, which resulting failed building process. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
PS C:\Users\bw\tensorflow\tensorflow\contrib\cmake\build> cmake .. -A x64 -Thost=x64 -DCMAKE_BUILD_TYPE=Release `
>> -DSWIG_EXECUTABLE='C:\Program Files\swigwin-3.0.12\swig.exe' `
>> -DPYTHON_EXECUTABLE='C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe' `
>> -DPYTHON_LIBRARIES='C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\libs\python36.lib'
-- Building for: Visual Studio 15 2017
CMake Warning at CMakeLists.txt:9 (message):
  Your current cmake generator is set to use 32 bit toolset architecture.
  This may cause "compiler out of heap space" errors when building.  Consider
  using the flag -Thost=x64 when running cmake.


-- The C compiler identification is MSVC 19.16.27024.1
-- The CXX compiler identification is MSVC 19.16.27024.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED - Failed
-- Performing Test MSVC_OPENMP_SUPPORT
-- Performing Test MSVC_OPENMP_SUPPORT - Success
-- Found PythonInterp: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/python.exe (found version "3.6.7")
-- Found PythonLibs: optimized;C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/libs/python36.lib;debug;C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/libs/python36_d.lib (found version "3.6.7")
-- Found SWIG: C:/Program Files/swigwin-3.0.12/swig.exe (found version "3.0.12")
CMake Error at tf_python.cmake:811 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:583 (include)


CMake Error at tf_python.cmake:812 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:583 (include)


CMake Error at tf_python.cmake:813 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:583 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/bw/tensorflow/tensorflow/contrib/cmake/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/bw/tensorflow/tensorflow/contrib/cmake/build/CMakeFiles/CMakeError.log".
```

**Any other info / logs**
CMakeOutput.log: https://www.dropbox.com/s/7fweyunxdbmxa1k/CMakeOutput.log?dl=0
CMakeError.log: https://www.dropbox.com/s/tucx0tl6346kdpd/CMakeError.log?dl=0

**Comment by ymodak** [comment]
Can you please switch to following known good configurations and build again:
[Microsoft  Visual Studio 2015](https://www.tensorflow.org/install/source_windows#install_visual_c_build_tools_2015)
Python 3.5

**Comment by bluemonk482** [comment]
Thanks for your reply @ymodak ! I have indeed tried building it with vs 2015 and Python 3.5, and got same error:

>  cmake .. -G 'Visual Studio 14 2015 Win64' -Thost=x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE='C:\Program Files\swigwin-3.
> 0.12\swig.exe'  -DPYTHON_EXECUTABLE='C:\Users\user_1\AppData\Local\Programs\Python\Python35\python.exe'  -DPYTHON_LIBRARIES='C:\Users\user_1\AppData\Local\Programs\Python\Python35\libs\py
> thon35.lib'
> CMake Warning at CMakeLists.txt:9 (message):
>   Your current cmake generator is set to use 32 bit toolset architecture.
>   This may cause "compiler out of heap space" errors when building.  Consider
>   using the flag -Thost=x64 when running cmake.
> 
> 
> -- Selecting Windows SDK version  to target Windows 10.0.17134.
> -- The C compiler identification is MSVC 19.0.24234.1
> -- The CXX compiler identification is MSVC 19.0.24234.1
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED
> -- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED - Failed
> -- Performing Test MSVC_OPENMP_SUPPORT
> -- Performing Test MSVC_OPENMP_SUPPORT - Success
> -- Found PythonInterp: C:/Users/user_1/AppData/Local/Programs/Python/Python35/python.exe (found version "3.5.4")
> -- Found PythonLibs: C:/Users/user_1/AppData/Local/Programs/Python/Python35/libs/python35.lib (found version "3.5.4")
> -- Found SWIG: C:/Program Files/swigwin-3.0.12/swig.exe (found version "3.0.12")
> CMake Error at tf_python.cmake:811 (string):
>   string sub-command REPLACE requires at least four arguments.
> Call Stack (most recent call first):
>   CMakeLists.txt:583 (include)
> 
> 
> CMake Error at tf_python.cmake:812 (string):
>   string sub-command REPLACE requires at least four arguments.
> Call Stack (most recent call first):
>   CMakeLists.txt:583 (include)
> 
> 
> CMake Error at tf_python.cmake:813 (string):
>   string sub-command REPLACE requires at least four arguments.
> Call Stack (most recent call first):
>   CMakeLists.txt:583 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/Users/user_1/tensorflow/tensorflow/contrib/cmake/build/CMakeFiles/CMakeOutput.log".
> See also "C:/Users/user_1/tensorflow/tensorflow/contrib/cmake/build/CMakeFiles/CMakeError.log".

**Comment by mrry** [comment]
(The CMake build is no longer supported by the core TensorFlow team, so I'm marking this issue as "community support".)

**Comment by kumariko** [comment]
@bwang482 We are checking to see if you still need help on this issue? We recommend that you upgrade to 2.7 which is latest stable version of TF . Also please have a look on the [link](https://stackoverflow.com/questions/53585905/cmake-build-tensorflow-c-on-windows-10-error-test-compiler-opt-arch-native-s) and let us know if it helps? Thanks!
