### ISSUE TITLE
Bad broadcasting when multiplying sparse and dense tensors

### ISSUE THREAD

**Issue by javidcf** [tensorflow/tensorflow#24072]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): b'v1.12.0-rc2-3-ga6d8ffae09' 1.12.0
- Python version: 3.6.7 Anaconda 64bit
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**

When multiplying (`*` operator) a sparse tensor `S` with rank `N` with a dense tensor `D` with rank `M`, where `N > M` and `S` and `D` have different but broadcast-compatible shapes, then TensorFlow attempts to perform the multiplication producing and incorrect sparse tensor as a result with the shape of `S`.

**Describe the expected behavior**

TensorFlow should refuse to perform a sparse-dense multiplication that requires broadcasting. This is the case when both tensors have the same rank or the rank of the sparse tensor is less than the rank of the dense tensor, but not when the rank of the sparse tensor is greater.

**Code to reproduce the issue**

```py
import tensorflow as tf

with tf.Graph().as_default(), tf.Session() as sess:
    a = tf.reshape(tf.range(12), [3, 4, 1])
    b = tf.SparseTensor([[0, 0, 1, 0], [0, 0, 3, 0]], [10, 20], [1, 1, 4, 2])
    c = a * b
    print(c.shape)
    # (1, 1, 4, 2)
    print(sess.run(tf.sparse.to_dense(c)))
    # [[[[ 0  0]
    #    [10  0]
    #    [ 0  0]
    #    [60  0]]]]
```

**Other info / logs**
NA

**Comment by yongtang** [comment]
@javidcf I added a PR #24098 for the fix. Please take a look.

**Comment by javidcf** [comment]
@yongtang Thanks, that seems to do a better job at validating the input, although to be honest I'm not familiar enough with the source to know if any other changes are needed. Only one thing, where the comment says `all dims in lhs is smaller or equal`, I think it should be `all dims in lhs is greater or equal`? Or maybe I'm misunderstanding something...

Besides that, I just noticed that these errors are only raised on evaluation. I suppose it would be convenient to raise an error on graph construction when detectable too... but that is a different issue really, for binary sparse ops in general - and also, if sparse broadcasting is planned to be supported at some point in the future, maybe it's not worth the effort.

**Comment by yongtang** [comment]
@javidcf Thanks. You are right and I have updated the PR for the comment. To raise the error on graph construction might requires more and sometimes the dims are not known at the construction time. I will take a look and create a separate PR if possible.
