### ISSUE TITLE
"Keyword argument not understood" - Raspberry Pi

### ISSUE THREAD

**Issue by Mortis19** [tensorflow/tensorflow#24074]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspberry Pi 3B+ (latest dist)
- TensorFlow installed from (source or binary): pip
- TensorFlow version (or github SHA if from source): 1.11.0 (latest from pip)
- Keras version: 2.2.4 (latest from pip)

Hello,
I am trying to accelerate a CNN model in order to run it in python and on my raspberry pi. I've tried using tensorflow lite as a solution to this but I still have no success in converting my keras model to a lite one and use it afterwards. I've tried tflite_convert on the command line but I get the error quoted below. I've also tried using the TocoConverter inside python but I get the same error. Could you help me?

**Provide the text output from tflite_convert**

```
raise TypeError('Keyword argument not understood:' , kwarg)
TypeError: ('Keyword argument not understood:' , u'output_padding')
```

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
