### ISSUE TITLE
TF learn has a problem with discontinuous categorical outputs

### ISSUE THREAD

**Issue by vinhqdang** [tensorflow/tensorflow#2407]
I have a ``train.csv`` which looks like:

```
v1,v2,v3
5,4,10
1,2,5
4,5,20
1,11,50
1,12,20
```

and ``test.csv``:

```
v1,v2
4,5
2,3
2,4
5,6
```

The idea is: the output variable (``v3``) can take four values:  ``5,10,20,50`` and nothing more. It is classification task.

Then code:

```{python}
import numpy as np
import pandas as pd
from tensorflow.contrib import learn

print ("Reading data")

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

print ("Dividing to train and test set")

y_train = df_train ['v3']
X_train = df_train [['v1','v2']]

X_test = df_test[['v1','v2']]

classifier_1 = learn.TensorFlowDNNClassifier(
     hidden_units=[20, 10], 
     n_classes=4, 
     batch_size=128, 
     steps=500, 
     learning_rate=0.05)

# fit
print ("Fitting")
classifier_1.fit(X_train, y_train)
```

Then I have a problem:

```
Traceback (most recent call last):
  File "sample.py", line 26, in <module>
    classifier_1.fit(X_train, y_train)
  File "/Users/qdang/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 254, in fit
    feed_params_fn=self._data_feeder.get_feed_params)
  File "/Users/qdang/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/trainer.py", line 49, in train
    feed_dict = feed_dict_fn()
  File "/Users/qdang/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/io/data_feeder.py", line 281, in _feed_dict_fn
    out.itemset((i, self.y[sample]), 1.0)
IndexError: index 5 is out of bounds for axis 1 with size 4
```

I think the issue is because the absolute value of output value (``5``) is larger than the number of classes (``4``)

**Comment by mouradmourafiq** [comment]
@vinhqdang you need to encode your `y_train` values to `[0, 1, 2, 3]` classes.

```python
y_train = pd.factorize(df_train['v3'])[0]
```

**Comment by vinhqdang** [comment]
Hello,

Afterwards, how could i convert the predicting outputs back to the normal one.

For example, after training a model, and use the model to predict a case, the output is 1.

Of course, 1 is not correct, I need to convert it back to [5,10,20,50] before.

**Comment by terrytangyuan** [comment]
@vinhqdang you'll just save your map somewhere

**Comment by vinhqdang** [comment]
Hi @terrytangyuan yeah, as discussed in gitter, it is a valid workaround and actually I am using it, but it seems not (very) official way.

**Comment by mouradmourafiq** [comment]
@vinhqdang `pd.factorize` return a tuple; the encoded values and the index/labels.

if you need to know what 1 means you just need to save your labels as @terrytangyuan suggested

```python
y_train, label_index = pd.factorize(df_train['v3'])
# label_index[1] would return the original value encoded to 1
```

**Comment by girving** [comment]
This kind of question should be asked on StackOverflow, since it is a question about how to use TensorFlow rather than a bug in TensorFlow itself.
