### ISSUE TITLE
TPU runs as slow as CPU when using keras_to_tpu_model

### ISSUE THREAD

**Issue by WangHexie** [tensorflow/tensorflow#24073]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): [run in colab](https://colab.research.google.com)
- TensorFlow installed from (source or binary):[Pre-installed in colab](https://colab.research.google.com)
- TensorFlow version (use command below):[1.12.0 Pre-installed in colab](https://colab.research.google.com)
- Python version:3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
- CUDA/cuDNN version:
- GPU model and memory: TPU

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
`v1.12.0-0-ga6d8ffae09 1.12.0`
**Describe the current behavior**
I use tf.contrib.tpu.keras_to_tpu_model to make my code be able to run on TPU,but it took 170 hours to finish an epoch while CPU took the same time and GPU took only 40 hours per epoch.I tried to adjust batch size but nothing changed.And I've tested the input function may take up 20% of the run time when running on GPU, so I think it's maybe not the main reason.
**Describe the expected behavior**
Run faster than GPU

**Code to reproduce the issue**
Here is my code:[https://github.com/WangHexie/DHNE/blob/master/src/hypergraph_embedding.py](https://github.com/WangHexie/DHNE/blob/master/src/hypergraph_embedding.py)
Run on colab:         
 1. TPU:[https://colab.research.google.com/gist/WangHexie/30c385509f9cd93be747f04c39f039a4/tpu-error.ipynb](https://colab.research.google.com/gist/WangHexie/30c385509f9cd93be747f04c39f039a4/tpu-error.ipynb)       
 2. GPU：[https://colab.research.google.com/gist/WangHexie/5bfac53bf92ef0ad527f15ddbf8705e1/-gpu-ipynb.ipynb](https://colab.research.google.com/gist/WangHexie/5bfac53bf92ef0ad527f15ddbf8705e1/-gpu-ipynb.ipynb)

**Comment by JeremyCCHsu** [comment]
Same problem here... and strangely, sometimes the TPU model works, but sometime it runs as slow as a CPU model.

**Comment by jvishnuvardhan** [comment]
@WangHexie This is an old issue. Is this still an issue for you. We are not supporting Python2.x and TF1.x any more. I tried running your code with recent `TF1.15.5` and faced different error as shown below. [Here](https://colab.research.google.com/gist/jvishnuvardhan/a57dd3917c7c4d53e43b42430bd31bbb/tpu-error.ipynb) is a gist for reference.

`AttributeError: 'Model' object has no attribute 'target_tensors'`

If this is still an issue, test it with recent `TF2.x`. If you notice any issues with recent TF versions, please provide a standalone code to reproduce the issue. Thanks!

Please close the issue if this was already resolved for you. Thanks!
