### ISSUE TITLE
Inconsistent keras API regarding variable_scope

### ISSUE THREAD

**Issue by unrealwill** [tensorflow/tensorflow#24079]
I am trying to reuse some layers (share the weights), so I've used some variable_scope and inside I created some keras layers. For some type of layers like tf.keras.layers.Dense, the weights are shared, for others like tf.keras.layers.Embedding for example new weights are created instead of being reused.

Probably similar to https://github.com/tensorflow/tensorflow/issues/20426 and https://github.com/tensorflow/tensorflow/issues/14703 

Can you advise a fix as it seems variable_scope are being deprecated in TF2.0 ?

Thanks

```
import tensorflow as tf
import numpy as np

def mlp( s ):
    word_embeddings = tf.get_variable("we",[3, 10])
    emb = tf.nn.embedding_lookup(word_embeddings, s)
    return emb

def mlpkeras( s ):
    emb = tf.keras.layers.Embedding( 3, 10)(s)
    return emb

def mlp2( s ):
    emb = tf.keras.layers.Dense(10)(s)
    return emb

def testEmbeddingTFLayer():
    sess = tf.Session()
    input = tf.placeholder(tf.int32, ((None,20)))

    with (tf.variable_scope("main", reuse=False) ):
        res1 = mlp(input)

    with (tf.variable_scope("main", reuse=True) ):
        res2 = mlp(input)

    sess.run(tf.global_variables_initializer())
    print("TestEmbeddingTFLayer :")
    print( sess.run( [tf.reduce_sum( (res1-res2)**2)] , feed_dict= {input:np.zeros((1,20)) } ) ) 

def testDenseLayer():
    sess = tf.Session()
    input = tf.placeholder(tf.float32, ((None,20)))

    with (tf.variable_scope("main", reuse=False) ):
        res1 = mlp2(input)

    with (tf.variable_scope("main", reuse=True) ):
        res2 = mlp2(input)

    sess.run(tf.global_variables_initializer())
    print("TestDenseLayer : ")
    print( sess.run( [tf.reduce_sum( (res1-res2)**2)] , feed_dict= {input:np.zeros((1,20)) } ) ) 


def testEmbeddingKerasLayer():
    sess = tf.Session()
    input = tf.placeholder(tf.int32, ((None,20)))

    with (tf.variable_scope("main", reuse=False) ):
        res1 = mlpkeras(input)

    with (tf.variable_scope("main", reuse=True) ):
        res2 = mlpkeras(input)

    sess.run(tf.global_variables_initializer())
    print("TestEmbeddingKerasLayer :")
    print( sess.run( [tf.reduce_sum( (res1-res2)**2)] , feed_dict= {input:np.zeros((1,20)) } ) ) 



testEmbeddingTFLayer() 
testDenseLayer()
testEmbeddingKerasLayer()
```
Prints 0 , 0 , and not 0 (expecting 0)

<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 3.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: CUDA Driver Version / Runtime Version          9.2 / 8.0
- GPU model and memory: 1080Ti

**Comment by allenlavoie** [comment]
The plan in 2.x is that variable sharing happens by sharing objects. So instead of being a function, `mlp` could be a `tf.keras.Model` subclass for example, creating its sub-Layers and variables only once and saving them in attributes. Then it would be called twice instead of created twice. This is much more efficient when executing eagerly, and seems to produce fewer hard-to-debug errors.

Does that work for you?

**Comment by unrealwill** [comment]
Not really. It seems to work for the simple cases but still miss some important features.
For example I can't figure how I would do some polyak averaging using the tf.keras.Model API in a generic way.

```
network1 = MyModel1()
network2 = tf.keras.models.clone_model(network1)
varnetwork1 = getVariables( network1 )  
varnetwork2 = getVariables( network2 )
updates = tf.group( [ tf.assign(v2, v2 *polyak + (1-polyak)*v1 )  for (v1,v2) in zip(varnetwork1,varnetwork2) ] )
```
It seems model.trainable_variables behavior is not defined by the API

Keras API is nice for beginners, but it is also quite verbose, (you must declare your layer first in init or build before being able to use them inside call)

Wouldn't this also mean tf.nn and tf.nn.layers shouldn't be use them inside model.__call__ ?

Serialization of Keras Models is also non trivial : 
Once you start sharing weights between two networks. 
```
sm = MySharedModel()
model1 = MyModel( sm )
model2 = MyModel( sm )
savedModel1 = serialize(model1)
savedModel2 = serialize(model2)
loadModel1 = load(savedModel1)
loadModel2 = load(savedModel2)
```
Now loadModel1 and loadModel2 don't share weights.

**Comment by rmothukuru** [comment]
@unrealwill,
Sorry for the delayed response. Can you please confirm if this issue still persists? Thanks!

**Comment by unrealwill** [comment]
out of date
