### ISSUE TITLE
Build failure with Ubuntu 18.04

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#24096]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: f1edf205b290c7fdeefe0b73d27c50a3cab67dcb
- Python version: Python 2.7.15rc1
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): Build label: 0.19.1
- GCC/Compiler version (if compiling from source): gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 
- CUDA/cuDNN version: n/a
- GPU model and memory:n/a

**Describe the problem**

While trying to build tf from source (master branch) on Ubuntu 18.04, the following error surfaces:
```
ERROR: /home/ubuntu/tensorflow/tensorflow/core/BUILD:2211:1: C++ compilation of rule '//tensorflow/core:lib_internal_impl' failed (Exit 1)
In file included from external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/Core:150:0,
                 from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:14,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/lib/random/random_distributions.h:28,
                 from ./tensorflow/core/lib/random/simple_philox.h:24,
                 from ./tensorflow/core/lib/random/distribution_sampler.h:38,
                 from tensorflow/core/lib/random/random_distributions.cc:16:
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/GenericPacketMath.h: In instantiation of 'TgtPacket Eigen::internal::pcast(const SrcPacket&) [with SrcPacket = __vector(2) long long int; TgtPacket = __vector(4) float]':
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/SSE/../Default/GenericPacketMathFunctions.h:25:40:   required from 'Packet Eigen::internal::pfrexp_float(const Packet&, Packet&) [with Packet = __vector(4) float]'
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/SSE/PacketMath.h:574:33:   required from here
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/GenericPacketMath.h:140:10: error: invalid static_cast from type 'const __vector(2) long long int' to type '__vector(4) float'
   return static_cast<TgtPacket>(a);
          ^~~~~~~~~~~~~~~~~~~~~~~~~
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/GenericPacketMath.h: In instantiation of 'TgtPacket Eigen::internal::pcast(const SrcPacket&) [with SrcPacket = __vector(4) float; TgtPacket = __vector(2) long long int]':
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/SSE/../Default/GenericPacketMathFunctions.h:35:37:   required from 'Packet Eigen::internal::pldexp_float(Packet, Packet) [with Packet = __vector(4) float]'
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/SSE/PacketMath.h:578:33:   required from here
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/GenericPacketMath.h:140:10: error: invalid static_cast from type 'const __vector(4) float' to type '__vector(2) long long int'
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/GenericPacketMath.h: In instantiation of 'TgtPacket Eigen::internal::pcast(const SrcPacket&) [with SrcPacket = __vector(4) long long int; TgtPacket = __vector(8) float]':
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/SSE/../Default/GenericPacketMathFunctions.h:25:40:   required from 'Packet Eigen::internal::pfrexp_float(const Packet&, Packet&) [with Packet = __vector(8) float]'
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/AVX/PacketMath.h:423:33:   required from here
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/GenericPacketMath.h:140:10: error: invalid static_cast from type 'const __vector(4) long long int' to type '__vector(8) float'
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/GenericPacketMath.h: In instantiation of 'TgtPacket Eigen::internal::pcast(const SrcPacket&) [with SrcPacket = __vector(8) float; TgtPacket = __vector(4) long long int]':
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/SSE/../Default/GenericPacketMathFunctions.h:35:37:   required from 'Packet Eigen::internal::pldexp_float(Packet, Packet) [with Packet = __vector(8) float]'
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/AVX/PacketMath.h:427:33:   required from here
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/GenericPacketMath.h:140:10: error: invalid static_cast from type 'const __vector(8) float' to type '__vector(4) long long int'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 173.313s, Critical Path: 20.46s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 250 processes: 250 local.
FAILED: Build did NOT complete successfully
```
**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
$ ./configure # with default options
$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
```

**Comment by ymodak** [comment]
TensorFlow is tested against GCC 4 versions, that can be a possible reason for above bazel build failure. Please take a look at [bazel build option](https://www.tensorflow.org/install/source#bazel_build) from this link to know more about GCC compatibility.

**Comment by octogondude** [comment]
Hi, same Problem here with same setup. Trying to compile for AVX512F.

Using the provided build option 

> --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"

does not change the error. I will try with gcc 5 now and report back.

**Comment by octogondude** [comment]
I was able to build sucessfully with gcc-4.

**Comment by byronyi** [comment]
@benoitsteiner Mind to take a look here?

**Comment by byronyi** [comment]
@yongtang @octogondude @ymodak Reverting 029389e0c69919392bd9a0d070d0d58498b0fb1d seems to work.

Ping @ezhulenev

**Comment by DavidNorman** [comment]
I have the same issue.

**Comment by bjascob** [comment]
I'd warn you that AVX512 may not be properly supported.  I've had intermittent system lockups with TF 1.12 and an earlier version when compiling using -march=native on an i9-7940x which enables AVX512 support.  In my case, the code compiled and ran fine but every so often, when running TF, UBT 18.04 would crash with no outward sign what was going on (no overtemp, or kernel log entry,...) 

There's a few issues open related to AVX512.  The suggested answer seems to be to try using MKL instead.  In my case, I'm using a GPU so simply disabling AVX512 was an acceptable option.

**Comment by ezhulenev** [comment]
Is it fixed after https://github.com/tensorflow/tensorflow/commit/43344c5014b2d33074feb6ff537261f9827453a6 ?

**Comment by yongtang** [comment]
Thanks @ezhulenev. I have tried with the latest master and the issue has been resolved 👍

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
