### ISSUE TITLE
Add an ability to terminate tf.data.choose_from_datasets/sample_from_datasets early

### ISSUE THREAD

**Issue by eiennohito** [tensorflow/tensorflow#24105]
**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Don't know

**Describe the feature and the current behavior/state.**
Presently, choose_from_datasets terminates as soon all datasets finish. 
It would be nice ho have an option to terminate as soon as *any* of datasets finish as well.

Suppose you have a main dataset which you use for training and a secondary dataset you mix into your first one. They can be of completely different sizes, but you want training to terminate as soon as main dataset terminates without any regard to the secondary dataset.

**Will this change the current api? How?**
Add a flag to choose_from_datasets/sample_from_datasets

**Who will benefit with this feature?**
Users who write complex tf.data pipelines

**Any Other info.**

**Comment by Squadrick** [comment]
Hey, I'd like to take a crack at this! Is that alright?

**Comment by jsimsa** [comment]
If by taking a crack at this, you mean implementing `take_while` that sounds good to me.

My suggestion is to start by taking a look at how another op that takes a user defined function (e.g. `tf.data.experimental.scan`) is implemented and tested. Here are relevant code pointers for `scan`:

- [python API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/experimental/ops/scan_ops.py)
- [op registration](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/experimental_dataset_ops.cc)
- [C++ kernel implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/experimental/scan_dataset_op.cc)
- [tests](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/experimental/kernel_tests/scan_test.py)

**Comment by Squadrick** [comment]
I'll start working on `take_while`, but before I started I had a couple of questions. 

1. `take_while` will be part of `tf.data.experimental`, but should I make a separate `take_while_ops.py`, or should I include in a pre-existing python file? Are there any pre-existing ops of this type?
2. What should the API of `take_while` look like? Do I make a general `take_while(cond_func)`, where `cond_func` returns a `tf.bool`. Or should it be more specific to this particular case of ending the overall iteration when one or all of the datasets finish?

**Comment by jsimsa** [comment]
1. creating `take_while_ops.py` is fine
2. general purpose `take_while(predicate)` as the API sounds good

**Comment by tilakrayal** [comment]
@eiennohito,
The PR #24645 which was related to the issue was merged. Could you please take a look and let us know if it serves the purpose. Also **take_while** is a transformation that stops dataset iteration based on a `predicate` and please take a look at this official link for the reference. Thank you!
