### ISSUE TITLE
Tensorflow Prebuilt Binaries are compiled for incompatible CUDA and cuDNN libraries

### ISSUE THREAD

**Issue by StealthySemicolon** [tensorflow/tensorflow#24102]
Tensorflow Prebuilt Binaries are compiled for CUDA 9.0 and cuDNN 7.2.1, however, cuDNN 7.2.1 download not available for CUDA 9.0

**Comment by ymodak** [comment]
Can you please provide following information?
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:



**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**


**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by StealthySemicolon** [comment]
It's not a build issue, I was just pointing out that the prebuilt binaries have CUDA and cuDNN versions that are incompatible with each other(i.e. there is no cuDNN 7.2.1 for CUDA 9.0, at least on the cuDNN archives in the nVidia website)

**Comment by ymodak** [comment]
@StealthySemicolon You can find cuDNN 7.2.1 from [cuDNN archive](https://developer.nvidia.com/rdp/cudnn-archive)

**Comment by StealthySemicolon** [comment]
cuDNN 7.2.1 does exist, just not for CUDA 9.0. There is no cuDNN 7.2.1 for CUDA 9.0 in the cuDNN archive.
