### ISSUE TITLE
Duplicate libiomp5.dylib & libmklml.dylib when install TF 1.12 with python 3.6.x using Anaconda3 in Mac OS 10.13

### ISSUE THREAD

**Issue by icyhins** [tensorflow/tensorflow#24106]
**System information**
- OS Platform and Distribution : MacOS 10.13 High Sierra
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.12
- Python version: 3.6.x
- Installed using : Anaconda 3, version 5.3.1

**Describe the problem**
Actually, my program meet a issue as [#23999 ](https://github.com/tensorflow/tensorflow/issues/23999)

I try to deep into the reason which cause the issue, 
and found that when I create a env (name 'py36' in my case) in Anaconda3 with Python 3.6 and install TensorFlow 1.12 ,
there are duplicate files `libiomp5.dylib` & `libmklml.dylib` under path
`~/anaconda3/envs/py36/lib/python3.6/site-packages/_solib_darwin/_U@mkl_Udarwin_S_S_Cmkl_Ulibs_Udarwin___Uexternal_Smkl_Udarwin_Slib/`

which are same files under path 
`~/anaconda3/envs/py36/lib`

No matter I delete which one, the program cannot run well.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Step 1. Install Anaconda 3 (Version 5.3.1)
Step2. Create env using Python 3.6
Step3. Install TensorFlow 1.12 and relative package.

BTW, If I create env (name 'py35' ) using Python 3.5, this issue is gone.
There are no folder `_solib_darwin` be created under `~/anaconda3/envs/py35/lib/python3.5/site-packages/` and no duplicate files `libiomp5.dylib` & `libmklml.dylib`

**Any other info / logs**

**Comment by icyhins** [comment]
My program as follow:
This program will meet issue [#23999](https://github.com/tensorflow/tensorflow/issues/23999)
when install TF 1.12 with python 3.6.x using Anaconda3 in Mac OS 10.13

``` python
import tensorflow as tf
import numpy as np

# Workaround for libiomp5.dylib already initialized.
# import os
# os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'


x_data = np.random.randn(2000, 3)
w_real = [0.3, 0.5, 0.1]
b_real = -0.2

noise = np.random.randn(1, 2000) * 0.1

y_data = np.matmul(w_real, x_data.T) + b_real + noise

NUM_STEPS = 10

g = tf.Graph()
wb_ = []

with g.as_default():
    x = tf.placeholder(tf.float32, shape=[None, 3])
    y_true = tf.placeholder(tf.float32, shape=None)

    with tf.name_scope('inference') as scope:
        w = tf.Variable([[0, 0, 0]], dtype=tf.float32, name='weights')
        b = tf.Variable(0, dtype=tf.float32, name='bias')
        y_predict = tf.matmul(w, tf.transpose(x)) + b

    with tf.name_scope('loss') as scope:
        loss = tf.reduce_mean(tf.square(y_predict - y_true))

    with tf.name_scope('train') as scope:
        learning_rate = 0.5
        optimizer = tf.train.GradientDescentOptimizer(learning_rate)
        train = optimizer.minimize(loss)

    # Before starting, initialize the variables. We will 'run' this first
    init = tf.global_variables_initializer()
    with tf.Session() as sess:
        sess.run(init)
        for step in range(NUM_STEPS):
            sess.run(train, {x: x_data, y_true: y_data})
            if step % 5 == 0:
                print(step, sess.run([w, b]))
                wb_.append(sess.run([w, b]))

        print(NUM_STEPS, sess.run([w, b]))

```

**Comment by paulafortuna** [comment]
I am also having a similar problem!

**Comment by vicpara** [comment]
I have the same problem. It's related to the anaconda `python3` installation of `tensorflow`. For some reason anaconda recommends installing their version of `tensorflow` because it's faster than the official release since it comes with native `mkl` integration.

I fixed the issue by running `conda uninstall tensorflow keras`. This seemed to partially remove the packages.  Then I run `pip install tensorflow keras` which worked successfully. 
Installed them back again with `pip install tensorflow keras`.
This solved my problem.

**Comment by ymodak** [comment]
Closing this issue since its more a likely an issue with anaconda. You can always set a virtual env and run your code as a workaround. Feel free to reopen if have any further problems. Thanks!
