### ISSUE TITLE
What's the problem? (bazel build)

### ISSUE THREAD

**Issue by dhshdi123** [tensorflow/tensorflow#24107]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:1.12
- Python version:3.6.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.17.2
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0/7.4.1
- GPU model and memory: geforce 750

INFO: From Compiling external/grpc/third_party/address_sorting/address_sorting_windows.c:
cl : Command line warning D9002 : ignoring unknown option '-std=c99'

ERROR: C:/users/amsokol/development/tensorflow-build/tensorflow/tensorflow/contrib/lite/schema/BUILD:58:1: Generating flatbuffer files for schema_fbs_srcs: //tensorflow/contrib/lite/schema:schema_fbs_srcs failed (Illegal instruction): bash.exe failed: error executing command
 
 cd C:/users/minsu/_bazel_minsu/lx6zoh4k/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=D:/Program Files
    SET CUDNN_INSTALL_PATH=D:/Program Files
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Users\amsokol\tensorflow-v1.12\Scripts;D:\Program Files\bin;D:\Program Files\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ffmpeg-4.1-win64-static\bin;C:\Users\minsu\AppData\Local\Programs\Python\Python36;C:\Users\minsu\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\minsu\AppData\Local\cuda\bin;C:\bazel;D:\tensorflow\tensorflow\tools\pip_package;C:\msys64\usr\bin;D:\tensorflow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC;C:\Users\minsu\Miniconda3;C:\Users\minsu\Miniconda3\Library\mingw-w64\bin;C:\Users\minsu\Miniconda3\Library\usr\bin;C:\Users\minsu\Miniconda3\Library\bin;C:\Users\minsu\Miniconda3\Scripts;C:\Users\minsu\AppData\Local\Microsoft\WindowsApps
    SET PYTHON_BIN_PATH=C:/Users/amsokol/tensorflow-v1.12/Scripts/python.exe
    SET PYTHON_LIB_PATH=C:/Users/amsokol/tensorflow-v1.12/Lib/site-packages
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=5.0
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  C:/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; for f in tensorflow/contrib/lite/schema/schema.fbs; do bazel-out/x64_windows-opt/bin/external/flatbuffers/flatc --no-union-value-namespacing --gen-object-api  -c -o bazel-out/x64_windows-opt/genfiles/tensorflow/contrib/lite/schema $f; done: bash.exe failed: error executing command
  cd C:/users/minsu/_bazel_minsu/lx6zoh4k/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=D:/Program Files
    SET CUDNN_INSTALL_PATH=D:/Program Files
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Users\amsokol\tensorflow-v1.12\Scripts;D:\Program Files\bin;D:\Program Files\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ffmpeg-4.1-win64-static\bin;C:\Users\minsu\AppData\Local\Programs\Python\Python36;C:\Users\minsu\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\minsu\AppData\Local\cuda\bin;C:\bazel;D:\tensorflow\tensorflow\tools\pip_package;C:\msys64\usr\bin;D:\tensorflow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC;C:\Users\minsu\Miniconda3;C:\Users\minsu\Miniconda3\Library\mingw-w64\bin;C:\Users\minsu\Miniconda3\Library\usr\bin;C:\Users\minsu\Miniconda3\Library\bin;C:\Users\minsu\Miniconda3\Scripts;C:\Users\minsu\AppData\Local\Microsoft\WindowsApps
    SET PYTHON_BIN_PATH=C:/Users/amsokol/tensorflow-v1.12/Scripts/python.exe
    SET PYTHON_LIB_PATH=C:/Users/amsokol/tensorflow-v1.12/Lib/site-packages
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=5.0
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  C:/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; for f in tensorflow/contrib/lite/schema/schema.fbs; do bazel-out/x64_windows-opt/bin/external/flatbuffers/flatc --no-union-value-namespacing --gen-object-api  -c -o bazel-out/x64_windows-opt/genfiles/tensorflow/contrib/lite/schema $f; done
/usr/bin/bash: line 1:  7444 Illegal instruction     bazel-out/x64_windows-opt/bin/external/flatbuffers/flatc --no-union-value-namespacing --gen-object-api -c -o bazel-out/x64_windows-opt/genfiles/tensorflow/contrib/lite/schema $f
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 22.017s, Critical Path: 2.25s
INFO: 47 processes: 47 local.
FAILED: Build did NOT complete successfully

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
