### ISSUE TITLE
SparseTensor file format

### ISSUE THREAD

**Issue by SumNeuron** [tensorflow/tensorflow#24103]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12+
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Currently there does not seem to be a way to save just a `SparseTensor`.
This is problematic as 1. the initialization of an instance can take a _long_ time 2. some models might require a constant sparse tensor. 

This is further supported by the fact that the Saver class is under the `train` api.

I propose a `save_variable` method under `tf.data` which can save _any_ TensorFlow native variable to a file for later retrieval.

In addition, there should be a corresponding `load_variable` method under `tf.data`. 

Notably, unlike TensorFlow Records, `save_variable` should require nothing more than two arguments, `file` (where to save the variable) and `var` (the variable to save) and `load_varriable` should require nothing more than `file`. 

_Any_ necessary information for reconstructing the variable (e.g. shape, class type) can be hashed as a header in the file.

Alternatively, provide users with a serialization function so we can use `pickle` as a short term fix.

**Will this change the current api? How?**

It adds 2 methods to `tf.data`

**Who will benefit with this feature?**

Everyone.

**Any Other info.**

**Comment by jsimsa** [comment]
What exactly do you mean by "initialization of an instance can take a long time"?

Could you perhaps illustrate with an example(s) the use case(s) that this API would benefit?

What prevents you from using `pickle`? I was able to use `pickle` for saving and loading a `tf.SparseTensor`:

```
  import pickle
  import tf as tensorflow

  tf.enable_eager_execution()

  st = tf.SparseTensor(indices=[[0, 0], [0, 1], [0, 2], [1, 0], [3, 0], [3, 1]], values=[1, 2, 3, 4, 5, 6], dense_shape=[4, 3])
  f = open('/tmp/tensor.pickle', 'w')
  pickle.dump(st, f)
  f.close()

  f = open('/tmp/tensor.pickle', 'r')
  st2 = pickle.load(f)
  f.close()

  print(st)
  print(st2)
```
produces
```
SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [3 0]
 [3 1]], shape=(6, 2), dtype=int64), values=tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32), dense_shape=tf.Tensor([4 3], shape=(2,), dtype=int64))
SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [3 0]
 [3 1]], shape=(6, 2), dtype=int64), values=tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32), dense_shape=tf.Tensor([4 3], shape=(2,), dtype=int64))
```

**Comment by SumNeuron** [comment]
@jsimsa thanks for chiming in.

I mean the call `tf.SparseTensor(...)` for relatively large tensors can take a while. For an example, just copy / paste the code from google's rec sys tutorial... although for data I used a matrix with  `shape=(20000, 30000)` and sparsity ≈`0.001` on a system with 100 Gb Ram, 40 cores and a GPU it took ~ 30 minutes to evaluate just `sparse = tf.SparseTensor(...)`, (not in eager execution mode). 

I was unaware pickle would work... some posts (on S.O. / non-official tutorials) stated they had issue with pickling TF objects (but if it works now, that is nice to know...)


e.g. in a colab/  jupyter  notebook 

```
# cell 1
# read or randomly make the dense matrix 

# cell 2
sparse = coo_matrix(dense) 

sparse_indicies = list(zip(
    sparse.row.astype(np.int64).tolist(), 
    sparse.col.astype(np.int64).tolist()
))


# cell 3 takes forever to return
input_tensor = tf.SparseTensor(
    indices     = sparse_indicies,
    values      = (sparse.data).astype(np.float32),
    dense_shape = sparse.shape
)
```

**Comment by rmothukuru** [comment]
@SumNeuron,
Sorry for the delayed response. In **`Tensorflow 2.0`**, as we rarely use [**`Saver`** class is under the **`train`** api](https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/Saver) and we use [tf.saved_model.save](https://www.tensorflow.org/api_docs/python/tf/saved_model/save), can you please let us know if this **`Feature`** is relevant? 

Thanks!
