### ISSUE TITLE
How to integrate KMeansClustering with other module

### ISSUE THREAD

**Issue by huaxiuyao** [tensorflow/tensorflow#24119]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): 1.12.0
- Python version: 3.6

**Problem**
When I want to integrate KMeansClustering into my model, I want to use minibatch kmeans to cluster the output of 2 fully connected layers. However, the error is one tensor of kmeans must be from the same graph as the input tensor. Is there any way to solve it? Thank you!

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
