### ISSUE TITLE
Bug when passing multiple output of Lambda Layer to the Model API

### ISSUE THREAD

**Issue by Anton-Velikodnyy** [tensorflow/tensorflow#24111]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
source
- TensorFlow version (use command below):
1.11.0
- Python version:
3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
5.2.0
- CUDA/cuDNN version:
9/7
- GPU model and memory:
GTX 1080, 8GB

**Describe the current behavior**
Attempting to receive multiple outputs from a lambda layer.  When passing them through the Model API, causes them to have an unexpected behavior. if all the outputs of that lambda layer are stored into a single variable, passing that variable as output for model fails with 
`AssertionError: Could not compute output Tensor...`

Using index[0] gives me behavior I would have expected when receiving with no index specified. Using index 1 or 2 gives same error as not giving an index. TLDR: index 0 gives behavior you would expect from not having an index. Index 1,2 give error same as no index 
**Describe the expected behavior**
specifying no index means that I am accessing a list of tensors, where as specifying an index gives me the tensor at that index.

**Code to reproduce the issue**
```
from tensorflow.python.keras.layers import Input, Lambda
from tensorflow.python.keras.models import Model
import tensorflow as tf
import numpy as np

ins = Input([1])

def test(x):
    return tf.constant(2,name='one'),tf.constant([2]),tf.constant([[2],[4]])

ous = Lambda(test)(ins)
model = Model(ins,ous[0]) # changing this 0 to 1 or 2 fails, removing index also fails
# model = Model(ins,ous) # FAILS
# model = Model(ins,ous[1]) # FAILS

new = model(np.asarray([1]))

with tf.Session() as sess:
    print(sess.run(new))  #(2, array([2], dtype=int32), array([[2], [4]], dtype=int32))
```
**Other info / logs**

**Comment by rmothukuru** [comment]
@Anton-Velikodnyy,
Sorry for the delayed response. Your code works fine even by replacing 0 with 1 or 2, successfully, in the Tensorflow Version 2.4. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/a7a529e24bc41565a6257fd378d76a7e/gh_24111.ipynb) of the working code. Thanks!

**Comment by Anton-Velikodnyy** [comment]
While i don't have a chance to test it currently. I'll close for now unless someone finds a bug with it.
