### ISSUE TITLE
Compute Capability 3.0 GTX 770 

### ISSUE THREAD

**Issue by mbaroody** [tensorflow/tensorflow#24126]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a 
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.8
- Python version: python2.7
- Installed using virtualenv? pip? conda?: pip (but I don't get that far)
- Bazel version (if compiling from source): 0.13.1
- GCC/Compiler version (if compiling from source): gcc 6.4.0
- CUDA/cuDNN version: Cuda 9.0.176/cuDNN 7.4/NCLL 2.3
- GPU model and memory: GTX 770 2GB 256-Bit GDDR5

**Config file**
```
You have bazel 0.13.0 installed.
Please specify the location of python. [Default is /usr/bin/python]:
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]
Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: y
jemalloc as malloc support will be enabled for TensorFlow.
Do you wish to build TensorFlow with Google Cloud Platform support? [Y/n]: n
No Google Cloud Platform support will be enabled for TensorFlow.
Do you wish to build TensorFlow with Hadoop File System support? [Y/n]: n
No Hadoop File System support will be enabled for TensorFlow.
Do you wish to build TensorFlow with Amazon S3 File System support? [Y/n]: n
No Amazon S3 File System support will be enabled for TensorFlow.
Do you wish to build TensorFlow with Apache Kafka Platform support? [Y/n]: n
No Apache Kafka Platform support will be enabled for TensorFlow.
Do you wish to build TensorFlow with XLA JIT support? [y/N]: y
XLA JIT support will be enabled for TensorFlow.
Do you wish to build TensorFlow with GDR support? [y/N]: n
No GDR support will be enabled for TensorFlow.
Do you wish to build TensorFlow with VERBS support? [y/N]: n
No VERBS support will be enabled for TensorFlow.
Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.
Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 9.0]:
Please specify the location where CUDA 9.1 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7.0]: 7.1.4
Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Do you wish to build TensorFlow with TensorRT support? [y/N]: n
No TensorRT support will be enabled for TensorFlow.
Please specify the NCCL version you want to use. [Leave empty to default to NCCL 1.3]: 2.2.12
Please specify the location where NCCL 2 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:/usr/local/cuda/nccl
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 3.0]
Do you want to use clang as CUDA compiler? [y/N]: n
nvcc will be used as CUDA compiler.
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/x86_64-linux-gnu-gcc-7]: /usr/bin/gcc-6
Do you wish to build TensorFlow with MPI support? [y/N]: n
No MPI support will be enabled for TensorFlow.
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.
Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
 --config=mkl          # Build with MKL support.

 --config=monolithic   # Config for mostly static monolithic build.

Configuration finished
```

**Describe the problem**

I have been struggling to build Tensorflow from source with bazel (I've tried releases 0.19.x - 0.13.x). I need to build from source in order to not have AVX instructions and also to used cuda compute capability 3.0. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Most recently, I tried building for GPU support using the latest nightly Docker image. That doesn't support compute capability 3.0, though. I tried [this guide](https://stackoverflow.com/questions/39023581/tensorflow-cuda-compute-capability-3-0-the-minimum-required-cuda-capability-is/50592978) which seemed promising, but could not get bazel to build successfully. Note that I'm using different versions of cuDNN and NCLL from that guide. Should I try the exact versions the OP used? Am I doing something obviously wrong? 

**Any other info / logs**

There are none to show. The failure with Bazel is literally different everytime. I can provide the next failure if it will help

**Some ideas I was going to try next**

-  revert to the versions of cuDNN (7.1.4) and NCCL (2.2.12) that the person from that guide used
- use the versions of gcc (4.8) and bazel (0.10.0) that are listed in the "Tested build configurations" table on the official documentation. Although, doesn't CUDA 9.0 need gcc 6.x? 

I've been working on this on/off for about a month now, would really appreciate a push in the right direction.

**Comment by bjascob** [comment]
There are several places on github with community built wheels for TF you can download and just install.  The cuda 3 compute capability is a common issue.  You should be able to find a prebuilt if you google for it.

**Comment by ymodak** [comment]
Currently we only support CUDA Compute Capability 3.5 or higher. To use compute capability 3.0 you have to build it yourself from the sources. Thanks!

**Comment by mbaroody** [comment]
@ymodak I have been trying to build myself from the sources, I'm here for some guidance. Anywhere you can point me to? @bjascob thanks for the tips, I found some public wheels that I will try today.

**Comment by mbaroody** [comment]
@ymodak Basically I just want to know how I would go about building myself from source. is it as simple as changing
```
_DEFAULT_CUDA_COMPUTE_CAPABILITIES = '3.5,5.2'
```
to
```
_DEFAULT_CUDA_COMPUTE_CAPABILITIES = '3.0,3.5,5.2'
```

**Comment by ymodak** [comment]
I understand. Please take at similar issue #6001.

**Comment by bjascob** [comment]
When you run `./configure` and it asks you what your compute capabilities are just enter 3.0.  You don't need the others unless you are building for multiple cards.  `./configure` will produce the file **.tf_configure.bazelrc**.  In case you're interested, here's what that file looks like on my machine where I specifically asked for CC 3.0 and "haswell" architecture.  Note this is python 3 and Cuda 10 with gcc 7 (default for UBT 18.04)
```build --action_env PYTHON_BIN_PATH="/usr/bin/python3"
build --action_env PYTHON_LIB_PATH="/usr/lib/python3/dist-packages"
build --python_path="/usr/bin/python3"
build --define with_ignite_support=true
build --define with_xla_support=true
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="1"
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda"
build --action_env TF_CUDA_VERSION="10.0"
build --action_env CUDNN_INSTALL_PATH="/usr/local/cuda-10.0"
build --action_env TF_CUDNN_VERSION="7"
build --action_env NCCL_INSTALL_PATH="/usr/lib/x86_64-linux-gnu"
build --action_env NCCL_HDR_PATH="/usr/include"
build --action_env TF_NCCL_VERSION="2"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="3.0"
build --action_env LD_LIBRARY_PATH=":/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
build --action_env TF_CUDA_CLANG="0"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/gcc"
build --config=cuda
test --config=cuda
build:opt --copt=-march=haswell
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
```

This setup, with bazel 0.18.0, works fine for me so you could try it verbatim if you want.

Note that .configure also creates a **.bazelrc** file with the content `import /home/bjascob/Libraries/tensorflow-1.12.0/.tf_configure.bazelrc` which is needed to reference that above config file.  There's also a small oddity that if  **.bazelrc** is there, `./configure` wont run so if you rerun this, delete that file first.

Be sure to run `bazel clean` before building then run...
```
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
sudo -H pip3 install /tmp/tensorflow_pkg/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl
```

**Comment by mbaroody** [comment]
@bjascob that is very helpful, thank you so much. Will try ASAP and report back.

**Comment by mbaroody** [comment]
@ymodak @bjascob it doesn't even ask what compute capability anymore. ./configure just writes 3.5 and above. So what files would I need to edit to compile the latest tensorflow from source for compute capability 3.0? This has to be possible.

**Comment by ymodak** [comment]
@meteorcloudy @gunan Can you please take a look?

**Comment by gunan** [comment]
@chsigg Does the sources still work with Compute capability 3.0?

@mbaroody You can look into the configure script, and change it to use 3.0.
But as we move forward, our source becomes incompatible with older compute capabilities.
We have not been actively making sure 3.0 works, so it is highly likely that build can fail, or your binary may crash.

**Comment by chsigg** [comment]
There is reasonable chance that it still works, because SM 3.5 is relatively similar to SM 3.0.

@mbaroody, you can change the .tf_configure.bazelrc file to switch to SM 3.0 support after you ran configure.

**Comment by ymodak** [comment]
@mbaroody Is this still an issue? Were you able to get it running?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
