### ISSUE TITLE
Error while running sample cpp program in tensorflow

### ISSUE THREAD

**Issue by HackersSpirit** [tensorflow/tensorflow#24123]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:No
- TensorFlow installed from (source or binary):Source
- TensorFlow version (use command below):r1.11
- Python version: 3.6
- Bazel version (if compiling from source): 0.19
- GCC/Compiler version (if compiling from source):msvc 2017
- CUDA/cuDNN version:
- GPU model and memory:

Problem Statement:
I have build tensorflow r1.11 library. During the build it was giving following error:
https://github.com/tensorflow/tensorflow/issues/23402
As a solution to the problem i used the one of the suggested solution on the forum:
bazel build --define=grpc_no_ares=true -c opt //tensorflow:libtensorflow_cc.so
The bazel is built successfully and when i try to run a sample program i get the following error:
:1: error: dependent '..\..\..\..\Downloads\tensorflow-r1.11\bazel-tensorflow-r1.11\external\eigen_archive\unsupported\Eigen\src\SpecialFunctions\arch\CUDA\CudaSpecialFunctions.h' does not exist.
Eariler i have build other version of library but this was not the issue.

**Comment by sanatmpa1** [comment]
@HackersSpirit,

We see you were using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to latest stable version and let us know if the issue still persists in newer versions.we will get you the right help.Thanks!
