### ISSUE TITLE
TFLite Speech recognization app is getting crashed with setUseNNAPI(true)

### ISSUE THREAD

**Issue by Umapraveen** [tensorflow/tensorflow#24120]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):[NO]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):
- Python version: 3.0
- Bazel version (if compiling from source):[bazel release 0.16.1]
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Description: 
Im using the source code from below repo:https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/android/app
Compiled using the readme in above link
The app works fine without any changes.
However when i enable setUseNNAPI(true) for speechActivity the crashes with below logs:

======================================================================
### tflite  : Custom operations are not supported when using NNAPI.
12-03 14:10:16.545  7947  7969 E tflite  : Returning error since TFLite returned failure nnapi_delegate.cc:745.
12-03 14:10:16.545  7947  7969 E tflite  : Failed to build graph for NNAPI
12-03 14:10:16.545  7947  7969 E AndroidRuntime: FATAL EXCEPTION: Thread-3
12-03 14:10:16.545  7947  7969 E AndroidRuntime: Process: org.tensorflow.lite.demo, PID: 7947
12-03 14:10:16.545  7947  7969 E AndroidRuntime: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: 
12-03 14:10:16.545  7947  7969 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
12-03 14:10:16.545  7947  7969 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:140)
12-03 14:10:16.545  7947  7969 E AndroidRuntime: 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:216)
12-03 14:10:16.545  7947  7969 E AndroidRuntime: 	at org.tensorflow.demo.SpeechActivity.recognize(SpeechActivity.java:339)
12-03 14:10:16.545  7947  7969 E AndroidRuntime: 	at org.tensorflow.demo.SpeechActivity.access$100(SpeechActivity.java:67)
12-03 14:10:16.545  7947  7969 E AndroidRuntime: 	at org.tensorflow.demo.SpeechActivity$3.run(SpeechActivity.java:290)
12-03 14:10:16.545  7947  7969 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
==============================================================================
**Other info / logs**
Note:
Image clasification works fine with same changes setUseNNAPI(true)

**Comment by freedomtan** [comment]
@Umapraveen as the message you posted said, 
```
Custom operations are not supported when using NNAPI.
```

The model you used had custom OPs so the TFLite interpreter refused to delegate the model to NNAPI.

To use NNAPI, try either
1. come up your own model with ops supported by TFLite and NNAPI, or
2. split your model and run custom ops on TFLite only

**Comment by ymodak** [comment]
Closing this issue since @freedomtan 's explaination is correct. Feel free to reopen if have any follow up questions. Thanks!

**Comment by fdchiu** [comment]
I had similar crash problem with tensor flow tflite android example code when setUseNNAPI to true:
2019-01-05 13:24:13.982 9314-9331/org.tensorflow.lite.demo E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.demo, PID: 9314
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: 
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:149)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.demo.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:194)
        at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:247)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

The phone used is pixel 2 with android 9. Once I setUseNNAPI to false, the tflite example apk runs normally.
