### ISSUE TITLE
bazel build issue (does not contain a toolchain for CPU 'k8')

### ISSUE THREAD

**Issue by christian-rauch** [tensorflow/tensorflow#24124]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: `master` (6798656ce64201afe7d8d9ed5445cd5114bfd9b4)
- Bazel version (if compiling from source): 0.20.0
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: 10

**Describe the problem**
When building branch `v1.12.0` or current `master` (commit 6798656ce64201afe7d8d9ed5445cd5114bfd9b4) I get the following build error:

`ERROR: cc_toolchain_suite '@local_config_cuda//crosstool:toolchain' does not contain a toolchain for CPU 'k8', you may want to add an entry for 'local|compiler' into toolchains and toolchain_identifier 'local_linux' into the corresponding cc_toolchain rule (see --incompatible_disable_cc_toolchain_label_from_crosstool_proto).`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
- install bazel as described here: https://docs.bazel.build/versions/master/install-ubuntu.html#install-on-ubuntu
- checkout the `v1.12.0` branch or 6798656ce64201afe7d8d9ed5445cd5114bfd9b4
- bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Comment by seank** [comment]
Same issue just came up for me too.

**Comment by vijayshinva** [comment]
I am having the same issue. Is there a way to make it work with Bazel 0.20.0 ?

@seank how did you downgrade your bazel version ?

**Comment by seank** [comment]
In my project it was a 1 char fix(dropped the ':').
"cortex-m3": ":cc-compiler-cortex-m3"    ->     "cortex-m3": "cc-compiler-cortex-m3"

cc_toolchain_suite(
    name = "toolchain",
    # target_cpu | compiler
    toolchains = {
        "armeabi-v7a|gcc": "cc-compiler-armeabi-v7a",
        "k8|compiler": "cc-compiler-k8",
        "cortex-m3": "cc-compiler-cortex-m3",
    },
)

**Comment by christian-rauch** [comment]
@seank Which file is that? Grepping for `cc-compiler-k8` doesn't show me any files.

**Comment by vijayshinva** [comment]
This is the CROSSTOOL file for tensorflow https://github.com/tensorflow/tensorflow/blob/master/third_party/toolchains/gpus/crosstool/CROSSTOOL

It seems to have a valid entry for k8.

**Comment by seank** [comment]
What about the BUILD file?


cc_toolchain_suite(
     name = "toolchain",
     toolchains = {
         "local|compiler": ":cc-compiler-local",
         "darwin|compiler": ":cc-compiler-darwin",
         "x64_windows|msvc-cl": ":cc-compiler-windows",
     },
)

**Comment by subashp** [comment]
Downgrading worked. Thanks! Anyone has working solution for bazel 0.20.0?

**Comment by zcc720** [comment]
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_packageWARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Invocation ID: ae5b088a-4356-4490-ad5c-10b7603e3dc1
DEBUG: /home/zcc/.cache/bazel/_bazel_zcc/ef73f1b213a381f188a64db1d3e2ae98/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
ERROR: cc_toolchain_suite '@local_config_cuda//crosstool:toolchain' does not contain a toolchain for CPU 'k8', you may want to add an entry for 'local|compiler' into toolchains and toolchain_identifier 'local_linux' into the corresponding cc_toolchain rule (see --incompatible_disable_cc_toolchain_label_from_crosstool_proto).
INFO: Elapsed time: 0.059s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

I am having the same issue.Is there anyway to solve this problem?

**Comment by stollcri** [comment]
This is my work around; it's certainly not the right way to do it, but I needed to get it working and this did the trick.

```diff
diff --git a/tensorflow/tools/ci_build/pi/build_raspberry_pi.sh b/tensorflow/tools/ci_build/pi/build_raspberry_pi.sh
index 864278c647..4991018b5f 100755
--- a/tensorflow/tools/ci_build/pi/build_raspberry_pi.sh
+++ b/tensorflow/tools/ci_build/pi/build_raspberry_pi.sh
@@ -15,6 +15,10 @@
 # ==============================================================================
 set -e

+curl -L https://github.com/bazelbuild/bazel/releases/download/0.19.2/bazel-0.19.2-installer-linux-x86_64.sh > bazel-0.19.2-installer-linux-x86_64.sh
+chmod +x bazel-0.19.2-installer-linux-x86_64.sh
+./bazel-0.19.2-installer-linux-x86_64.sh --user
+
 # By default this builds packages for the Pi Two and Three only, since the NEON support
 # this allows makes calculations many times faster. To support the Pi One or Zero, pass
 # PI_ONE as the first argument to the script, for example:
@@ -102,7 +106,7 @@ fi
 export CROSSTOOL_PYTHON_INCLUDE_PATH

 cd ${WORKSPACE_PATH}
-bazel build -c opt ${PI_COPTS} \
+~/bin/bazel build -c opt ${PI_COPTS} \
   --config=monolithic \
   --copt=-funsafe-math-optimizations --copt=-ftree-vectorize \
   --copt=-fomit-frame-pointer --cpu=armeabi \
```

**Comment by mihaimaruseac** [comment]
I'll have to test building with bazel 0.20 and see where it breaks. It will take a while

**Comment by mihaimaruseac** [comment]
I was able to compile with 0.20 safely, cannot reproduce on my end :(

**Comment by cynthiaxhua** [comment]
How do you install an older version of bazel?

**Comment by mihaimaruseac** [comment]
Run the following

```
curl -L https://github.com/bazelbuild/bazel/releases/download/0.19.2/bazel-0.19.2-installer-linux-x86_64.sh > bazel-0.19.2-installer-linux-x86_64.sh
chmod +x bazel-0.19.2-installer-linux-x86_64.sh
./bazel-0.19.2-installer-linux-x86_64.sh --user
```

**Comment by wdirons** [comment]
Same problem on ppc64le when trying for bazel test with cuda

ERROR: cc_toolchain_suite '@local_config_cuda//crosstool:toolchain' does not contain a toolchain for CPU 'ppc', you may want to add an entry for 'local|compiler' into toolchains and toolchain_identifier 'local_linux' into the corresponding cc_toolchain rule (see --incompatible_disable_cc_toolchain_label_from_crosstool_proto).

**Comment by powderluv** [comment]
maybe bazel should have a CI to check that it builds tensorflow before pushing out a release that breaks the biggest user of bazel..

**Comment by mixaz** [comment]
I have somewhat similar issue but downgrading bazel didn't help

**Comment by gunan** [comment]
I think @annarev merged a change to fix this at head.
What commit are you seeing this at?

**Comment by haslo** [comment]
@gunan It certainly happens with https://github.com/tensorflow/tensorflow/releases/tag/v1.12.0. So the currently latest TF release can't be built.

**Comment by byronyi** [comment]
> @gunan It certainly happens with https://github.com/tensorflow/tensorflow/releases/tag/v1.12.0. So the currently latest TF release can't be built on a fresh machine. (We got it to work with [#24124 (comment)](https://github.com/tensorflow/tensorflow/issues/24124#issuecomment-446701570)).

It can be built per se. It is just the Bazel team is releasing frequently, and TF team is releasing frequently based on the lastest Bazel available at that time. If you are building an older release of TF, make sure you are using the corresponding Bazel version, which is probably not the latest one.

**Comment by haslo** [comment]
@byronyi Yeah, of course (though 1.12.0 is the newest release, not an older one). I absolutely think the issue lies with Bazel here.

The main problem I see is that they regularly roll out non backwards compatible releases without providing packages for older versions. So I can't use a package manager to install that older Bazel version, but I have to curl and then manually install it from somewhere - which is at odds with all the documentation of both TF and Bazel. That's pretty annoying IMHO, because I had to dig through issue reports like this one to find a remedy.

But all of this is definitely not the fault of the TensorFlow team or library.

**Comment by ShirinNajdi** [comment]
I am getting almost the same issue in MacBook Pro, macOS High Sierra 10.13.6, bazel version 0.21 and CUDA/cuDNN: 10/7.4:

 bazel build --config=cuda --config=opt --incompatible_remove_native_http_archive=false --incompatible_package_name_is_a_function=false  --apple_platform_type macos --action_env PATH --action_env LD_LIBRARY_PATH --action_env DYLD_LIBRARY_PATH //tensorflow/tools/pip_package:build_pip_package

WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/anaconda3/bin/tensorflow/tools/bazel.rc
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Invocation ID: 65975697-0885-4091-a0f4-446cbcab24c7
DEBUG: /1106218c9bb5e3a2c38e96f5f11850c7/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
**ERROR: /1106218c9bb5e3a2c38e96f5f11850c7/external/local_config_cuda/crosstool/BUILD:5:1: in cc_toolchain_suite rule @local_config_cuda//crosstool:toolchain: cc_toolchain_suite '@local_config_cuda//crosstool:toolchain' does not contain a toolchain for cpu 'darwin'**
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis of target '@local_config_cuda//crosstool:toolchain' failed; build aborted
INFO: Elapsed time: 0,200s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)


Does somebody else experience this problem? Is there a solution for it?

**Comment by byronyi** [comment]
> @byronyi Yeah, of course (though 1.12.0 is the newest release, not an older one). I absolutely think the issue lies with Bazel here.
> 
> The main problem I see is that they regularly roll out non backwards compatible releases without providing packages for older versions. So I can't use a package manager to install that older Bazel version, but I have to curl and then manually install it from somewhere - which is at odds with all the documentation of both TF and Bazel. That's pretty annoying IMHO, because I had to dig through issue reports like this one to find a remedy.
> 
> But all of this is definitely not the fault of the TensorFlow team or library. And also, my problem is solved, so this is just me ranting aimlessly. Apologies.

It is alright. Bazel is still in its 0.x release line so do expect breaking changes. It would be better once it hits 1.0. TF itself is a complex project that is hard to build with any other build systems than the Google internal one (called Blade). I am outside Google, but I guess the open source of Bazel has much reason behind TF. Bazel itself is a good tool, it is just adapting itself to the open source world.

**Comment by hamddan4** [comment]
The answer from [https://github.com/tensorflow/tensorflow/issues/24124#issuecomment-446701570](#24124) wasn't enough for me, I had to uninstall bazel before.

To uninstall it i just removed everything from bazel:
`rm -fr ~/.bazel ~/.bazelrc`
`rm -rf ~/.cache/bazel `
`sudo rm -rf /usr/local/bin/bazel /etc/bazelrc /usr/local/lib/bazel `

Then reinstalled bazel as @mihaimaruseac said:
`curl -L https://github.com/bazelbuild/bazel/releases/download/0.19.2/bazel-0.19.2-installer-linux-x86_64.sh > bazel-0.19.2-installer-linux-x86_64.sh`
`chmod +x bazel-0.19.2-installer-linux-x86_64.sh`
`./bazel-0.19.2-installer-linux-x86_64.sh --user`

**Comment by mihaimaruseac** [comment]
Probably just the cache needed to be removed, based on my understanding of  Bazel/Blaze.

**Comment by christian-rauch** [comment]
I am closing this since the build script now won't proceed without a compatible bazel version.
The recommended way is to install the Debian package from https://github.com/bazelbuild/bazel/releases with the corresponding fixed bazel version (`bazel_<version>-linux-x86_64.deb`) instead of using the repository which always updates to the latest version.

**Comment by VigiZhang** [comment]
I use custom toolchain for clang. The latest tensorflow master branch.
bazel 0.19.2 will get:
ERROR: /home/work/.cache/bazel/_bazel_work/9c49027ece9440387ec9accf0e8cd57b/external/io_bazel_rules_closure/closure/protobuf/closure_proto_library.bzl:66:21: name 'ProtoInfo' is not defined (did you mean 'protos'?)

google tells me to upgrade bazel. But any version above 0.19.2 will get:
in cc_toolchain_suite rule //tools/clang-6.0:toolchain: cc_toolchain_suite '//tools/clang-6.0:toolchain' does not contain a toolchain for cpu 'k8'

anyone could help to solve this?
