### ISSUE TITLE
encrypt decrypt tf lite model in android

### ISSUE THREAD

**Issue by zjmirving** [tensorflow/tensorflow#24139]
I found an issue https://github.com/tensorflow/tensorflow/issues/21501. When i decrypt my model to byte[],  use wrap() method to convert byte[] to HeapByteBuffer, init the Interpreter. The NativeInterpreterWrapper will throw an exception. Is there a way to solve this problem？

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/src/main/java/org/tensorflow/lite/NativeInterpreterWrapper.java
` NativeInterpreterWrapper(ByteBuffer buffer, Interpreter.Options options) {
    if (buffer == null
        || (!(buffer instanceof MappedByteBuffer)
            && (!buffer.isDirect() || buffer.order() != ByteOrder.nativeOrder()))) {
      throw new IllegalArgumentException(
          "Model ByteBuffer should be either a MappedByteBuffer of the model file, or a direct "
              + "ByteBuffer using ByteOrder.nativeOrder() which contains bytes of model content.");
    }
    this.modelByteBuffer = buffer;
    long errorHandle = createErrorReporter(ERROR_BUFFER_SIZE);
    long modelHandle = createModelWithBuffer(modelByteBuffer, errorHandle);
    init(errorHandle, modelHandle, options);
  }`

**Comment by kimchicanh** [comment]
@zjmirving Could you tell me about your solution, I am facing the same problem???

**Comment by zjmirving** [comment]
> @zjmirving Could you tell me about your solution, I am facing the same problem???

ByteBuffer byteBuffer = ByteBuffer.allocateDirect(bytes.length);
byteBuffer.order(ByteOrder.nativeOrder());
byteBuffer.put(bytes);
Interpreter mTFLiteInterpreter = new Interpreter(byteBuffer);

**Comment by JianbangZ** [comment]
@zjmirving are you able to encrypt tflite and decypt successfully? I am facing the same problem. great if you can share some insights.

**Comment by zjmirving** [comment]
> @zjmirving are you able to encrypt tflite and decypt successfully? I am facing the same problem. great if you can share some insights.

ByteBuffer byteBuffer = ByteBuffer.allocateDirect(bytes.length);
byteBuffer.order(ByteOrder.nativeOrder());
byteBuffer.put(bytes);
Interpreter mTFLiteInterpreter = new Interpreter(byteBuffer);

**Comment by JianbangZ** [comment]
@zjmirving Thank you. but how do you encrypt tflite flatbuffer model file?

> > @zjmirving are you able to encrypt tflite and decypt successfully? I am facing the same problem. great if you can share some insights.
> 
> ByteBuffer byteBuffer = ByteBuffer.allocateDirect(bytes.length);
> byteBuffer.order(ByteOrder.nativeOrder());
> byteBuffer.put(bytes);
> Interpreter mTFLiteInterpreter = new Interpreter(byteBuffer);

**Comment by shedeed1** [comment]
@zjmirving hello can you help me out, i tried your code but it is giving me "ByteBuffer is not a valid flatbuffer model"

@JianbangZ did you reach a solution?

**Comment by StanislasGaitUp** [comment]
Here is what I did to solve my problem in Kotlin (exact same than @zjmirving solution)
```kotlin
val byteBuffer = ByteBuffer.allocateDirect(bytes.size)
byteBuffer.order(ByteOrder.nativeOrder())
byteBuffer.put(bytes)
val tflite = Interpreter(buffer)
```

**Comment by BIG-CHENG** [comment]
Thanks!
I have the same problem & this solution works for me

**Comment by Jeanvit** [comment]
> > @zjmirving Could you tell me about your solution, I am facing the same problem???
> 
> ByteBuffer byteBuffer = ByteBuffer.allocateDirect(bytes.length); byteBuffer.order(ByteOrder.nativeOrder()); byteBuffer.put(bytes); Interpreter mTFLiteInterpreter = new Interpreter(byteBuffer);

Worked for me! Thanks!
