### ISSUE TITLE
tf.estimator.Estimator.train fails with 3+ keras layer calls and MirroredStrategy distribution

### ISSUE THREAD

**Issue by dogbox** [tensorflow/tensorflow#24132]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
linux ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
binary (pip install tensorflow-gpu==1.8)
- TensorFlow version (use command below):
1.8.0
- Python version:
2.7.12
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
9.0.176
- GPU model and memory:
GeForce GTX 1080 Ti (11gb memory)

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
When applying a keras layer 3 or more times using tf.contrib.distribute.MirroredStrategy within the run config, training with a tensorflow estimator hits an exception when applying the layer at graph build time:
```
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 314, in __call__
    output = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 671, in __call__
    with scope_context_manager as scope:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1962, in __enter__
    self._current_name_scope.__enter__()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 5974, in __enter__
    % (self._name, self._default_name))
ValueError: At least one of name (None) and default_name (None) must be provided.
```

additional observations:
- runs fine if the layer is applied 2 times (using MirroredStrategy)
- runs fine if the layer is applied 3 times (using OneDeviceStrategy)

**Describe the expected behavior**
`estimator.train` should succeed with multiple gpus and multiple applications of a keras layer.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import numpy as np
import tensorflow as tf


class ConvLayer(tf.keras.layers.Layer):
    def call(self, image):
        shape = (3, 3, 3, 16)
        stddev = 1
        weights = tf.get_variable(
            name='weights',
            initializer=tf.truncated_normal(shape, stddev=stddev),
        )
        conv = tf.nn.conv2d(image, weights, [1, 1, 1, 1], 'SAME')
        return conv


def get_train_op(loss):
    global_step = tf.train.get_global_step()
    optimizer = tf.contrib.optimizer_v2.AdamOptimizer(.001)  # use distribution-aware optimizer
    train_op = optimizer.minimize(loss, global_step=global_step)
    return train_op


def model_fn(features, labels, mode):
    image = features['image']

    # if num_layers >= 3, graph construction will error if more than 1 gpu is used
    num_layers = 3
    layer = ConvLayer()
    values = []
    for _ in xrange(num_layers):
        values.append(layer(image))
    stacked_values = tf.concat(values, axis=0)

    loss = tf.reduce_sum(stacked_values)
    mode = tf.estimator.ModeKeys.TRAIN
    train_op = get_train_op(loss)
    return tf.estimator.EstimatorSpec(mode, loss=loss, train_op=train_op)


def input_fn():

    shape = (100, 100, 3)

    def gen():
        while True:
            image = np.ones(shape, dtype=np.float32)
            yield ({'image': image}, [])

    ds = tf.data.Dataset.from_generator(
        gen,
        ({'image': tf.float32}, tf.float32),
        output_shapes=({'image': tf.TensorShape(shape)}, tf.TensorShape(None)),
    )
    ds = ds.repeat().batch(4)
    return ds


# top-level call
def run():
    gpus = ['/device:GPU:0', '/device:GPU:1']
    # MirroredStrategy fails
    distribution = tf.contrib.distribute.MirroredStrategy(gpus)
    # OneDeviceStrategy works
    # distribution = tf.contrib.distribute.OneDeviceStrategy(gpus[0])

    config = tf.estimator.RunConfig(
        train_distribute=distribution,
        model_dir='/path/to/output'
    )
    estimator = tf.estimator.Estimator(
        model_fn=model_fn,
        config=config,
    )
    estimator.train(
        input_fn=input_fn,
        steps=10,
    )
```

calling `run()` after setting `num_layers` to 1 or 2 works, but fails if `num_layers >= 3`.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 465, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "scott_exp/multigpu.py", line 31, in model_fn
    values.append(layer(image))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 314, in __call__
    output = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 671, in __call__
    with scope_context_manager as scope:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1962, in __enter__
    self._current_name_scope.__enter__()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 5974, in __enter__
    % (self._name, self._default_name))
ValueError: At least one of name (None) and default_name (None) must be provided.
```

full stacktrace: https://gist.github.com/dogbox/dcceda3d7b0c813c139258ea436e73f1

**Comment by dogbox** [comment]
just noting that this issue isn't pressing - i've been able to work around this by explicitly setting variable scopes instead:

```
class ConvLayer(object):
    def __call__(self, image):
        with tf.variable_scope(self.name, reuse=tf.AUTO_REUSE):
            shape = (3, 3, 3, 16)
            stddev = 1
            weights = tf.get_variable(
                name='weights',
                initializer=tf.truncated_normal(shape, stddev=stddev),
            )
            conv = tf.nn.conv2d(image, weights, [1, 1, 1, 1], 'SAME')
            return conv
```

it'd still be nice to use keras layers though, especially since this approach seems to be discouraged [https://github.com/tensorflow/tensorflow/issues/13895#issuecomment-364997554].

**Comment by msymp** [comment]
@joshl This user request is about specific combination where 3+ layers of Keras model are imported into estimators and a distribution strategy is employed. Can you please review this condition?

**Comment by seemuch** [comment]
The usual way of using Keras layers is to have multiple layers (in your case, 3) one after another. What you did was using the same layer 3 times. 
I am not sure what caused your problem, but that is definitely not the common pattern of using Keras layers.

**Comment by isaprykin** [comment]
You are using a Keras Layer.  Please consider the documentation for writing your own layers, including the provided example: https://keras.io/layers/writing-your-own-keras-layers/.  In particular, the weights need to be define as part of `build()` rather than `call()`.  I'd try that.  Please re-open if that doesn't resolve your issue.
