### ISSUE TITLE
Compile Failed Numerous Times

### ISSUE THREAD

**Issue by guopei** [tensorflow/tensorflow#2413]
Ubuntu 14.04
GCC 4.8.4
Cuda 7.5
Cudnn 4.0.7
Bazel 0.2.2b

-----

`bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer`
INFO: Found 1 target...
ERROR: /home/peiguo/.cache/bazel/_bazel_peiguo/67521296d96959142b2d5d303d9c774c/external/re2/BUILD:9:1: undeclared inclusion(s) in rule '@re2//:re2':
this rule is missing dependency declarations for the following files included by 'external/re2/util/rune.cc':
  '/usr/include/stdc-predef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdarg.h'
  '/usr/include/string.h'
  '/usr/include/features.h'
  '/usr/include/x86_64-linux-gnu/sys/cdefs.h'
  '/usr/include/x86_64-linux-gnu/bits/wordsize.h'
  '/usr/include/x86_64-linux-gnu/gnu/stubs.h'
  '/usr/include/x86_64-linux-gnu/gnu/stubs-64.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h'
  '/usr/include/xlocale.h'
  '/usr/include/x86_64-linux-gnu/bits/string3.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h'
  '/usr/include/stdint.h'
  '/usr/include/x86_64-linux-gnu/bits/wchar.h'.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.329s, Critical Path: 2.01s

---

I have tried many times, the error is always undeclared inclusion(s) in rule xxxx, but the xxxx is changing constantly.

**Comment by mrry** [comment]
Does this problem only occur when you build that target with `--config=cuda`?

@damienmg: You've helped out with a few of these errors before, so perhaps you'll have a quick answer. Is there an obvious cause for `/usr/include` not being in the builtin include paths? As far as I can tell it's explicitly defined in `CROSSTOOL` [here](https://github.com/tensorflow/tensorflow/blob/449d122b46d6e7fa2deba151356ffda200d1be7c/third_party/gpus/crosstool/CROSSTOOL#L62).

**Comment by guopei** [comment]
@mrry Yes, it occurs without --config=cuda

**Comment by DKP-90** [comment]
If on amazon use this ami number ami-a19b67c1

**Comment by damienmg** [comment]
Can you try updating to 0.2.3?

Can you upload the file under bazel-out/external/local_config_cc/CROSSTOOL?
What if you try with `--crosstool_top=@bazel_tools//tools/cpp:raw-toolchain`?

**Comment by guopei** [comment]
Thanks for the help! But it still doesn't work.

**Use 0.2.3 doesn't solve the problem. This time error message becomes:**

ERROR: /scratch/peiguo/tensor-flow/tensorflow/tensorflow/core/kernels/BUILD:1267:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:batchtospace_op_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/batchtospace_op_gpu.cu.cc':
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed/limits.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed/syslimits.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdarg.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include/x86intrin.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include/ia32intrin.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include/mmintrin.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include/xmmintrin.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include/mm_malloc.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include/emmintrin.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include/immintrin.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include/fxsrintrin.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include/adxintrin.h'
  '/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include/float.h'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
Target //tensorflow/cc:tutorials_example_trainer failed to build

**# CROSSTOOL:**

major_version: "local"
minor_version: ""
default_target_cpu: "same_as_host"

default_toolchain {
  cpu: "k8"
  toolchain_identifier: "local"
}

default_toolchain {
  cpu: "armeabi-v7a"
  toolchain_identifier: "stub_armeabi-v7a"
}

\# Android tooling requires a default toolchain for the armeabi-v7a cpu.
toolchain {
  abi_version: "armeabi-v7a"
  abi_libc_version: "armeabi-v7a"
  builtin_sysroot: ""
  compiler: "compiler"
  host_system_name: "armeabi-v7a"
  needsPic: true
  supports_gold_linker: false
  supports_incremental_linker: false
  supports_fission: false
  supports_interface_shared_objects: false
  supports_normalizing_ar: false
  supports_start_end_lib: false
  supports_thin_archives: false
  target_libc: "armeabi-v7a"
  target_cpu: "armeabi-v7a"
  target_system_name: "armeabi-v7a"
  toolchain_identifier: "stub_armeabi-v7a"

  tool_path { name: "ar" path: "/bin/false" }
  tool_path { name: "compat-ld" path: "/bin/false" }
  tool_path { name: "cpp" path: "/bin/false" }
  tool_path { name: "dwp" path: "/bin/false" }
  tool_path { name: "gcc" path: "/bin/false" }
  tool_path { name: "gcov" path: "/bin/false" }
  tool_path { name: "ld" path: "/bin/false" }

  tool_path { name: "nm" path: "/bin/false" }
  tool_path { name: "objcopy" path: "/bin/false" }
  tool_path { name: "objdump" path: "/bin/false" }
  tool_path { name: "strip" path: "/bin/false" }
  linking_mode_flags { mode: DYNAMIC }
}

toolchain {
  toolchain_identifier: "local"
  abi_libc_version: "local"
  abi_version: "local"
  builtin_sysroot: ""
  compiler: "compiler"
  compiler_flag: "-U_FORTIFY_SOURCE"
  compiler_flag: "-D_FORTIFY_SOURCE=1"
  compiler_flag: "-fstack-protector"
  compiler_flag: "-Wall"
  compiler_flag: "-Wl,-z,-relro,-z,now"
  compiler_flag: "-B/usr/bin"
  compiler_flag: "-B/usr/bin"
  compiler_flag: "-Wunused-but-set-parameter"
  compiler_flag: "-Wno-free-nonheap-object"
  compiler_flag: "-fno-omit-frame-pointer"
  cxx_builtin_include_directory: "/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include"
  cxx_builtin_include_directory: "/home/.slash_usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed"
  cxx_builtin_include_directory: "/usr/include/c++/4.8"
  cxx_builtin_include_directory: "/usr/include/x86_64-linux-gnu/c++/4.8"
  cxx_builtin_include_directory: "/usr/include/c++/4.8/backward"
  cxx_builtin_include_directory: "/usr/local/include"
  cxx_builtin_include_directory: "/usr/include/x86_64-linux-gnu"
  cxx_builtin_include_directory: "/usr/include"
  cxx_flag: "-std=c++0x"
  host_system_name: "local"
  linker_flag: "-lstdc++"
  linker_flag: "-lm"
  linker_flag: "-no-canonical-prefixes"
  linker_flag: "-Wl,-no-as-needed"
  linker_flag: "-B/usr/bin"
  linker_flag: "-B/usr/bin"
  linker_flag: "-pass-exit-codes"
  linker_flag: "-Wl,--build-id=md5"
  linker_flag: "-Wl,--hash-style=gnu"
  linker_flag: "-Wl,-rpath,/home/peiguo/.cache/bazel/_bazel_peiguo/f093626f144ca8499d84c1ae3f196d29/external/local_config_cc"
  linker_flag: "-L/home/peiguo/.cache/bazel/_bazel_peiguo/f093626f144ca8499d84c1ae3f196d29/external/local_config_cc"
  linker_flag: "-Wl,-rpath,/usr/local/lib"
  linker_flag: "-L/usr/local/lib"
  linker_flag: "-Wl,-rpath,/usr/local/cuda/lib64"
  linker_flag: "-L/usr/local/cuda/lib64"
  linker_flag: "-Wl,-rpath,/usr/local/cuda/lib64"
  linker_flag: "-L/usr/local/cuda/lib64"
  linker_flag: "-Wl,-rpath,/usr/local/cudnn-v4/lib64"
  linker_flag: "-L/usr/local/cudnn-v4/lib64"
  needsPic: true
  objcopy_embed_flag: "-I"
  objcopy_embed_flag: "binary"
  supports_fission: false
  supports_gold_linker: false
  supports_incremental_linker: false
  supports_interface_shared_objects: false
  supports_normalizing_ar: false
  supports_start_end_lib: false
  supports_thin_archives: false
  target_cpu: "k8"
  target_libc: "local"
  target_system_name: "local"
  unfiltered_cxx_flag: "-no-canonical-prefixes"
  unfiltered_cxx_flag: "-fno-canonical-system-headers"
  unfiltered_cxx_flag: "-Wno-builtin-macro-redefined"
  unfiltered_cxx_flag: "-D__DATE__=\"redacted\""
  unfiltered_cxx_flag: "-D__TIMESTAMP__=\"redacted\""
  unfiltered_cxx_flag: "-D__TIME__=\"redacted\""
  tool_path {name: "ar" path: "/usr/bin/ar" }
  tool_path {name: "cpp" path: "/usr/bin/cpp" }
  tool_path {name: "dwp" path: "/usr/bin/dwp" }
  tool_path {name: "gcc" path: "/usr/bin/gcc" }
  tool_path {name: "gcov" path: "/usr/bin/gcov" }
  tool_path {name: "ld" path: "/usr/bin/ld" }
  tool_path {name: "nm" path: "/usr/bin/nm" }
  tool_path {name: "objcopy" path: "/usr/bin/objcopy" }
  tool_path {name: "objdump" path: "/usr/bin/objdump" }
  tool_path {name: "strip" path: "/usr/bin/strip" }

  compilation_mode_flags {
    mode: DBG
    compiler_flag: "-g"
  }
  compilation_mode_flags {
    mode: OPT
    compiler_flag: "-g0"
    compiler_flag: "-O2"
    compiler_flag: "-DNDEBUG"
    compiler_flag: "-ffunction-sections"
    compiler_flag: "-fdata-sections"
    linker_flag: "-Wl,--gc-sections"
  }
  linking_mode_flags { mode: DYNAMIC }
}

**Do you mean use**: `bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer --crosstool_top=@bazel_tools//tools/cpp:raw-toolchain`

**The error message is:** 

WARNING: Config values are not defined in any .rc file: cuda
ERROR: no such package 'tensorflow/cc': BUILD file not found on package path.
INFO: Elapsed time: 0.069s

**Comment by damienmg** [comment]
no without --config=cuda

--config=cuda is the issue on the error message you are showing

**Comment by guopei** [comment]
**Now without --config=cuda:**

`bazel build -c opt //tensorflow/cc:tutorials_example_trainer --crosstool_top=@bazel_tools//tools/cpp:raw-toolchain`
ERROR: Loading of target '@bazel_tools//tools/cpp:raw-toolchain' failed; build aborted: no such target '@bazel_tools//tools/cpp:raw-toolchain': target 'raw-toolchain' not declared in package 'tools/cpp' defined by /home/peiguo/.cache/bazel/_bazel_peiguo/f093626f144ca8499d84c1ae3f196d29/external/bazel_tools/tools/cpp/BUILD.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.080s

**Comment by damienmg** [comment]
Sorry my bad, my memory served me wrong. So here the correct command:
`bazel build -c opt //tensorflow/cc:tutorials_example_trainer --crosstool_top=@bazel_tools//tools/cpp:default-toolchain`

Can you also try:
`bazel build -c opt //tensorflow/cc:tutorials_example_trainer` (without anything else)?

**Comment by guopei** [comment]
@DKP-90 No I am not on Amazon.

**Comment by guopei** [comment]
Thanks @damienmg , `bazel build -c opt //tensorflow/cc:tutorials_example_trainer --crosstool_top=@bazel_tools//tools/cpp:default-toolchain` works out well!

But one more question, is there any solution for building with cuda support?

**Comment by damienmg** [comment]
And what about the second option: `bazel build -c opt //tensorflow/cc:tutorials_example_trainer`?

For CUDA, we should make the previous command work first.

**Comment by guopei** [comment]
This is what I got from `bazel build -c opt //tensorflow/cc:tutorials_example_trainer`

WARNING: /home/peiguo/.cache/bazel/_bazel_peiguo/f093626f144ca8499d84c1ae3f196d29/external/re2/WORKSPACE:1: Workspace name in /home/peiguo/.cache/bazel/_bazel_peiguo/f093626f144ca8499d84c1ae3f196d29/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
WARNING: /scratch/peiguo/tensor-flow/tensorflow/google/protobuf/BUILD:59:16: in includes attribute of cc_library rule //google/protobuf:protobuf_lite: 'src/' resolves to 'google/protobuf/src' not in 'third_party'. This will be an error in the future.
WARNING: /scratch/peiguo/tensor-flow/tensorflow/google/protobuf/BUILD:124:16: in includes attribute of cc_library rule //google/protobuf:protobuf: 'src/' resolves to 'google/protobuf/src' not in 'third_party'. This will be an error in the future.
WARNING: /scratch/peiguo/tensor-flow/tensorflow/google/protobuf/BUILD:266:16: in includes attribute of cc_library rule //google/protobuf:protoc_lib: 'src/' resolves to 'google/protobuf/src' not in 'third_party'. This will be an error in the future.
INFO: Found 1 target...
ERROR: /home/peiguo/.cache/bazel/_bazel_peiguo/f093626f144ca8499d84c1ae3f196d29/external/re2/BUILD:9:1: undeclared inclusion(s) in rule '@re2//:re2':
this rule is missing dependency declarations for the following files included by 'external/re2/util/rune.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdarg.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h'.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.951s, Critical Path: 1.28s

**Comment by damienmg** [comment]
what does `echo | ${CC} -E -xc++ - -v` gives you?

**Comment by guopei** [comment]
echo | ${CC} -E -xc++ - -v
-E: command not found

**Comment by damienmg** [comment]
oops `echo | gcc -E -xc++ - -v` (sorry for the number of command)

**Comment by guopei** [comment]
Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 /home/.slash_usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/cc1plus -E -quiet -v -imultiarch x86_64-linux-gnu -iprefix /home/.slash_usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/ -D_GNU_SOURCE - -mtune=generic -march=x86-64 -fstack-protector -Wformat -Wformat-security
ignoring nonexistent directory "/home/.slash_usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/include"
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/4.8"
ignoring duplicate directory "/home/.slash_usr/bin/../lib/gcc/../../lib/gcc/x86_64-linux-gnu/4.8/include"
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring duplicate directory "/home/.slash_usr/bin/../lib/gcc/../../lib/gcc/x86_64-linux-gnu/4.8/include-fixed"
ignoring nonexistent directory "/home/.slash_usr/bin/../lib/gcc/../../lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/.slash_usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/include
 /home/.slash_usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/include-fixed
 /usr/include/c++/4.8
 /usr/include/x86_64-linux-gnu/c++/4.8
 /usr/include/c++/4.8/backward
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "<stdin>"
COMPILER_PATH=/home/.slash_usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/:/home/.slash_usr/bin/../lib/gcc/x86_64-linux-gnu/:/home/.slash_usr/bin/../lib/gcc/
LIBRARY_PATH=/home/.slash_usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/:/home/.slash_usr/bin/../lib/gcc/x86_64-linux-gnu/:/home/.slash_usr/bin/../lib/gcc/:/home/.slash_usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/:/home/.slash_usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/home/.slash_usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'

**Comment by damienmg** [comment]
`/usr/lib/gcc/x86_64-linux-gnu` is not in the list of include directories returned by gcc which explains why bazel cannot find it. Weird that it found stuff there.

Anyhow, the fix for cuda should be to add the following line:
```
  cxx_builtin_include_directory: "/home/.slash_usr/lib/gcc/"
```
at that line: https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/CROSSTOOL#L62

**Comment by guopei** [comment]
This time it works like magic! 

Thanks a lot, this problem confuses me for at least two days... 

Now I have built Tensorflow from source and I can do [fine-tuning on Inception-V3 model](https://github.com/tensorflow/models/blob/master/inception/README.md#how-to-fine-tune-a-pre-trained-model-on-a-new-task)!

**Comment by mrry** [comment]
Thanks for persevering @guopei and massive thanks to @damienmg for helping! Damien, is there something we could/should do in the TF/Bazel configuration to make this less likely to happen, or is this just a case of adding documentation?

**Comment by damienmg** [comment]
TF CUDA crosstool file should be configured depending on the used C++ compiler, just like we do for the default crosstool in Bazel.

I am a bit more puzzled on how @guopei compiler includes file from /usr/lib/gcc/x86_64-linux-gnu/4.8/include while it is not reported by gcc as a system include directory. But that might just be an issue of setting correctly the CC environment variable.

**Comment by mrry** [comment]
Thanks again. @keveman, sorry for picking on you, but would you be able to make these changes (feel free to reassign if someone else would be better)? It looks like there are some longstanding TODOs in our crosstool from the original OSS release, and we might be able to revisit them now.

**Comment by keveman** [comment]
@damienmg Damien, are you suggesting I add `/home/.slash_usr/lib/gcc/` to the `CROSSTOOL`? Or is this something that should be done via the `configure` script by querying the `gcc` installed on the system?

**Comment by damienmg** [comment]
Yes should be done at configuration step, see my comment on #1157

**Comment by bostonbuddy** [comment]
Hi,

I am getting this error when running:

[code] bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer [/code]


ERROR: /home/audio-dnn/tensorflow/tensorflow/core/kernels/BUILD:855:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:crop_and_resize_op_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/crop_and_resize_op_gpu.cu.cc':
  '/usr/local/cuda-7.5/include/cuda_runtime.h'
  '/usr/local/cuda-7.5/include/host_config.h'
  '/usr/local/cuda-7.5/include/builtin_types.h'
  '/usr/local/cuda-7.5/include/device_types.h'
  '/usr/local/cuda-7.5/include/host_defines.h'
  '/usr/local/cuda-7.5/include/driver_types.h'
  '/usr/local/cuda-7.5/include/surface_types.h'
  '/usr/local/cuda-7.5/include/texture_types.h'
  '/usr/local/cuda-7.5/include/vector_types.h'
  '/usr/local/cuda-7.5/include/channel_descriptor.h'
  '/usr/local/cuda-7.5/include/cuda_runtime_api.h'
  '/usr/local/cuda-7.5/include/cuda_device_runtime_api.h'
  '/usr/local/cuda-7.5/include/driver_functions.h'
  '/usr/local/cuda-7.5/include/vector_functions.h'
  '/usr/local/cuda-7.5/include/vector_functions.hpp'
  '/usr/local/cuda-7.5/include/common_functions.h'
  '/usr/local/cuda-7.5/include/math_functions.h'
  '/usr/local/cuda-7.5/include/math_functions.hpp'
  '/usr/local/cuda-7.5/include/math_functions_dbl_ptx3.h'
  '/usr/local/cuda-7.5/include/math_functions_dbl_ptx3.hpp'
  '/usr/local/cuda-7.5/include/cuda_surface_types.h'
  '/usr/local/cuda-7.5/include/cuda_texture_types.h'
  '/usr/local/cuda-7.5/include/device_functions.h'
  '/usr/local/cuda-7.5/include/device_functions.hpp'
  '/usr/local/cuda-7.5/include/device_atomic_functions.h'
  '/usr/local/cuda-7.5/include/device_atomic_functions.hpp'
  '/usr/local/cuda-7.5/include/device_double_functions.h'
  '/usr/local/cuda-7.5/include/device_double_functions.hpp'
  '/usr/local/cuda-7.5/include/sm_20_atomic_functions.h'
  '/usr/local/cuda-7.5/include/sm_20_atomic_functions.hpp'
  '/usr/local/cuda-7.5/include/sm_32_atomic_functions.h'
  '/usr/local/cuda-7.5/include/sm_32_atomic_functions.hpp'
  '/usr/local/cuda-7.5/include/sm_35_atomic_functions.h'
  '/usr/local/cuda-7.5/include/sm_20_intrinsics.h'
  '/usr/local/cuda-7.5/include/sm_20_intrinsics.hpp'
  '/usr/local/cuda-7.5/include/sm_30_intrinsics.h'
  '/usr/local/cuda-7.5/include/sm_30_intrinsics.hpp'
  '/usr/local/cuda-7.5/include/sm_32_intrinsics.h'
  '/usr/local/cuda-7.5/include/sm_32_intrinsics.hpp'
  '/usr/local/cuda-7.5/include/sm_35_intrinsics.h'
  '/usr/local/cuda-7.5/include/surface_functions.h'
  '/usr/local/cuda-7.5/include/surface_functions.hpp'
  '/usr/local/cuda-7.5/include/texture_fetch_functions.h'
  '/usr/local/cuda-7.5/include/texture_fetch_functions.hpp'
  '/usr/local/cuda-7.5/include/texture_indirect_functions.h'
  '/usr/local/cuda-7.5/include/texture_indirect_functions.hpp'
  '/usr/local/cuda-7.5/include/surface_indirect_functions.h'
  '/usr/local/cuda-7.5/include/surface_indirect_functions.hpp'
  '/usr/local/cuda-7.5/include/device_launch_parameters.h'
  '/usr/local/cuda-7.5/include/cuda_fp16.h'
  '/usr/local/cuda-7.5/include/math_constants.h'
  '/usr/local/cuda-7.5/include/curand_kernel.h'
  '/usr/local/cuda-7.5/include/curand.h'
  '/usr/local/cuda-7.5/include/curand_discrete.h'
  '/usr/local/cuda-7.5/include/curand_precalc.h'
  '/usr/local/cuda-7.5/include/curand_mrg32k3a.h'
  '/usr/local/cuda-7.5/include/curand_mtgp32_kernel.h'
  '/usr/local/cuda-7.5/include/cuda.h'
  '/usr/local/cuda-7.5/include/curand_mtgp32.h'
  '/usr/local/cuda-7.5/include/curand_philox4x32_x.h'
  '/usr/local/cuda-7.5/include/curand_globals.h'
  '/usr/local/cuda-7.5/include/curand_uniform.h'
  '/usr/local/cuda-7.5/include/curand_normal.h'
  '/usr/local/cuda-7.5/include/curand_normal_static.h'
  '/usr/local/cuda-7.5/include/curand_lognormal.h'
  '/usr/local/cuda-7.5/include/curand_poisson.h'
  '/usr/local/cuda-7.5/include/curand_discrete2.h'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
Target //tensorflow/cc:tutorials_example_trainer failed to build



Here is the output of  [code] echo | gcc -E -xc++ - -v [/code] :



Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/4.8/cc1plus -E -quiet -v -imultiarch x86_64-linux-gnu -D_GNU_SOURCE - -mtune=generic -march=x86-64 -fstack-protector -Wformat -Wformat-security
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/4.8"
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/4.8
 /usr/include/x86_64-linux-gnu/c++/4.8
 /usr/include/c++/4.8/backward
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "<stdin>"
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'

I ran the the command suggested by damienmg in above, and they built without error.

Would you please help me.

PS: nvidia driver version is 367.35, and I did not install the driver when I install cuda from runfile.

**Comment by yaroslavvb** [comment]
Maybe add `cxx_builtin_include_directory` pointing to your 7.5 cuda similar to https://github.com/tensorflow/tensorflow/issues/3431

**Comment by bostonbuddy** [comment]
Thank you so much @yaroslavvb , adding the following line to third_party/gpus/crosstool/CROSSTOOL worked:

cxx_builtin_include_directory: "/usr/local/cuda-7.5/include"

**Comment by suharshs** [comment]
Closing as this seems to be resolved. Please reopen or create new issue if I'm wrong.

**Comment by yuye2133** [comment]
bazel build -c opt //tensorflow/cc:tutorials_example_trainer --crosstool_top=@bazel_tools//tools/cpp:default-toolchain

I have used the command to build tensorflow , but how to install tensorflow? 
and I want to know It can be used for gpu?

**Comment by srp1970** [comment]
With latest tensorflow, I have CROSSTOOL.tlp. Should we copy this as CROSSTOOL and make modifications to this (adding cxx_builtin_include_directory)?

**Comment by xuanchien** [comment]
@yuye2133 
Your command is to build and run the example of tensorflow. To install TensorFlow to your python, you have to run the command to build the pip package (wheel) and then install it. Following are copied from TensorFlow website:

```
$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

# To build with GPU support:
$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

# The name of the .whl file will depend on your platform.
$ sudo pip install /tmp/tensorflow_pkg/tensorflow-0.10.0rc0-py2-none-any.whl
```

To test if new installed tensorflow works as you expected, you can try running the following python script, if there is no error then it should be okay.

```
import tensorflow as tf
# Creates a graph.
with tf.device('/gpu:0'):
  a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
  b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
  c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print sess.run(c)
```

**Comment by xuanchien** [comment]
@srp1970 CROSSTOOL.tpl is the same as CROSSTOOL (I have just compiled tensorflow successfully today). There are already some `cxx_builtin_include_directory` in that file, you only need to update it with new paths.
