### ISSUE TITLE
TFLite error: Op builtin_code out of range: 101.

### ISSUE THREAD

**Issue by utkarsh-VRL** [tensorflow/tensorflow#24131]
Used TF nightly (tf-nightly-gpu-1.13.0.dev20181129) to convert a frozen model to .tflite. When I try to load this model in Android, TFLite throws an error: "Op builtin_code out of range: 101, are you using old TFLite binary with newer model?"

I am loading TFLite nightly in my APK like so:

```
dependencies {
compile 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
}
```

What am I missing and what should I do to get this model loaded in Android?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora r28
- TensorFlow installed from (source or binary): binary(conda)
- TensorFlow version (or github SHA if from source):tf-nightly-gpu-1.13.0.dev20181129

**Comment by alanchiao** [comment]
Hi bug@: the op builtin_code 101 points to the ABS operator as we can see in the TFLite schema [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs#L206).
The ABS operator was added to the schema only as of 14 days ago in this [commit](https://github.com/tensorflow/tensorflow/commit/22ff3ec66ef0a2453e353d8b1ed21a1866884381#diff-87671811af2daf75c4211e7582e258de).

I would try recompiling the 0.0.0-nightly build in your demo again and see if it can pick up that commit. Let me know if that works!

**Comment by alanchiao** [comment]
Closing this issue for now. Please reopen if you find that this fix didn't work.
