### ISSUE TITLE
No gradient defined for operation 'MatrixLogarithm'

### ISSUE THREAD

**Issue by HagbardCel** [tensorflow/tensorflow#24146]
I would like to optimize a function containing tf.linalg.logm. However,

LookupError: gradient registry has no entry for: MatrixLogarithm

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by ZhangXiao96** [comment]
Hello, have you solved this issue yet?

**Comment by Randl** [comment]
I think it can be considered a feature request.
