### ISSUE TITLE
I am getting Thread 1: signal SIGABRT while installing the camera example tensorflowlite 

### ISSUE THREAD

**Issue by nihp** [tensorflow/tensorflow#24143]
I am getting Thread 1: signal SIGABRT while installing the camera example tensorflowlite app. Kindly let me know can we able to run this in simulator.

**Comment by ymodak** [comment]
Can you please point me to the link you used to build tensorflowlite application?Thanks!

**Comment by nihp** [comment]
@ymodak  I am following this https://www.tensorflow.org/lite/demo_ios to build tensonflowlite application

**Comment by achowdhery** [comment]
Please add the details on what step gives an error while following the tutorial.

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
