### ISSUE TITLE
ERROR: /root/tensorflow/tensorflow/lite/BUILD:202:1: in cc_library rule //tensorflow/lite:string_util: cycle in dependency graph

### ISSUE THREAD

**Issue by terryaic** [tensorflow/tensorflow#24141]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: 3.6
- Installed using virtualenv? pip? conda?:no
- Bazel version (if compiling from source):0.15
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:none
- GPU model and memory:

**Describe the problem**
when trying to build toco with with_select_tf_ops=true, error happens.

bazel build -c opt  --define=with_select_tf_ops=true //tensorflow/lite/toco:toco 

ERROR: /root/tensorflow/tensorflow/lite/BUILD:202:1: in cc_library rule //tensorflow/lite:string_util: cycle in dependency graph
.......
ERROR: /root/tensorflow/tensorflow/lite/BUILD:202:1: in cc_library rule //tensorflow/lite:string_util: cycle in dependency graph:
    //tensorflow/lite/toco:toco
    //tensorflow/lite/toco:toco_tooling
    //tensorflow/lite/toco/tflite:export
    //tensorflow/lite/toco/tflite:operator
    //tensorflow/lite/toco/tflite:types
.-> //tensorflow/lite:string_util
|   //tensorflow/lite:framework
|   //tensorflow/lite/delegates/flex:delegate
|   //tensorflow/lite/delegates/flex:delegate_only_runtime
|   //tensorflow/lite/delegates/flex:delegate_data
|   //tensorflow/lite/delegates/flex:buffer_map
`-- //tensorflow/lite:string_util
This cycle occurred because of a configuration option
ERROR: Analysis of target '//tensorflow/lite/toco:toco' failed; build aborted

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
