### ISSUE TITLE
InfeedEnqueueTuple placed on TPU device blocks indefinitely

### ISSUE THREAD

**Issue by Keno** [tensorflow/tensorflow#24155]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): N/A
- TensorFlow version (use command below): Cloud nightly
- Python version: N/A
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: Cloud TPUv3

**Describe the current behavior**

There are two documented ways to use the TPU infeed ops:
1. Place them on the CPU device and set device_ordinal to the requisite device
2. Place them on the TPU device and leave device_ordinal empty

The first way works fine, the second way does transfer the data to the device, but then blocks, never returning control to the client. Of note, this deadlock only happens if there is currently an op running on the TPU device (via XRTExecute, but potentially others).

**Describe the expected behavior**

Both methods should work.

**Comment by mohantym** [comment]
Hi @keno!

We are checking to see whether you still need help in this issue .
Would it be possible to share a toy model too to replicate above deadlock.

Thank you!
