### ISSUE TITLE
Feature Request: atrous convolution with stride > 1

### ISSUE THREAD

**Issue by chris-scott** [tensorflow/tensorflow#2415]
I'd like access to strides in atrous_conv2d for learning multi-scale raw audio filters. Using a stride of 1 is computationally infeasible, and as the goal is classification resolution does not need to be preserved.

**Comment by mrry** [comment]
@gpapan: Assigning you based on your contribution of the original op.

**Comment by gpapan** [comment]
@chris-scott, it is a bit tricky to write an efficient implementation for general strides and rate based on the current approach. Note however that if rate is a multiple of stride, i.e., `rate = k * stride` for some positive k, then:

    atrous_conv(input, rate=rate, stride=stride)

is identical to

    atrous_conv(subsample(input, stride), rate=k, stride=1)

Can you adopt something like that in your project?

**Comment by chris-scott** [comment]
@gpapan 
Thank you - I didn't appreciate adding strides was non-trivial. I can take a downsampling approach as you suggest.

**Comment by zhenheny** [comment]
Hi @gpapan ,

Do you have plan implementing atrous conv with general strides?

Thank you
