### ISSUE TITLE
dynamic_rnn claims it supports nested tuples but actually doesn't

### ISSUE THREAD

**Issue by DanielSun94** [tensorflow/tensorflow#24159]
**System information**
- TensorFlow version:  1.12.0
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn

The documentation of dynamic_rnn claims it can accept **nested tuples**. I quote:
> inputs: The RNN inputs. If time_major == False (default), this must be a Tensor of shape: [batch_size, max_time, ...], or a nested tuple of such elements. If time_major == True, this must be a Tensor of shape: [max_time, batch_size, ...], **_or a nested tuple of such elements_**. This may also be a (possibly nested) tuple of Tensors satisfying this property ...

So I write a simple demo to test the feature
```python
# encoding=utf-8-sig
import tensorflow as tf

batch_size = None

# nested tuple
x_placeholder = [tf.placeholder(tf.float32, [batch_size, 10, 20], 'input_1'),
                 [tf.placeholder(tf.float32, [batch_size, 10, 20], 'input_2'),
                 tf.placeholder(tf.float32, [batch_size, 10, 20], 'input_3')]]
sequence_size = tf.placeholder(tf.int32, [batch_size], 'sequence_size')
cell = tf.nn.rnn_cell.LSTMCell(15)
tf.nn.dynamic_rnn(cell=cell, inputs=x_placeholder, sequence_length=sequence_size, 
                  initial_state=None, time_major=True, dtype=tf.float32)
```

and the console raises a error:
> ValueError: Layer lstm_cell_1 expects 1 inputs, but it received 3 input tensors. Inputs received: [<tf.Tensor 'rnn/while/TensorArrayReadV3:0' shape=(10, 20) dtype=float32>, <tf.Tensor 'rnn/while/TensorArrayReadV3_1:0' shape=(10, 20) dtype=float32>, <tf.Tensor 'rnn/while/TensorArrayReadV3_2:0' shape=(10, 20) dtype=float32>]

and I find the place that raise the error
the line 826 of tensorflow/tensorflow/python/ops/rnn.py defines how to generate the new state, i.e.,
```python
call_cell = lambda: cell(input_t, state)
```
In the demo, the cell function is actually __call__() function of LSTMCell. And the documentation of LSTMCell claims the input must be a 2-D tensor. Nevertheless, if we feed a nested tuple to dynamic_rnn function, the input must be a 3-D tensor, so the LSTM raise a error

So, my question is, is dynamic_rnn really support nested tuples ?

**Comment by ebrevdo** [comment]
It's up to your cell to support nested tuples.  LSTMCell cannot handle inputs of this form because the underlying algorithm only handles one input tensor per frame.  You have to write your own `RNNCell` or `LayerRNNCell` if you want to be able to handle more than one tensor per frame.

**Comment by ebrevdo** [comment]
more concretely, you have to do:

```python
class MyCell(LayerRNNCell):
  def __init__(self, ...):
    ...
    self.built = True

  def build(input_shape):
     ...

  def call(inputs, state):
     input0, (input1, input2) = inputs
     # process the 3 tensors above and emit an output and state matching self.output_size, self.state_size
```

**Comment by DanielSun94** [comment]
thank you very much

**Comment by DanielSun94** [comment]
> more concretely, you have to do:
> 
> ```python
> class MyCell(LayerRNNCell):
>   def __init__(self, ...):
>     ...
>     self.built = True
> 
>   def build(input_shape):
>      ...
> 
>   def call(inputs, state):
>      input0, (input1, input2) = inputs
>      # process the 3 tensors above and emit an output and state matching self.output_size, self.state_size
> ```

Thank you very much
