### ISSUE TITLE
Importing tensorflow changes CPU affinity to single core on main thread 

### ISSUE THREAD

**Issue by dizzam** [tensorflow/tensorflow#24172]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux CentOS 6.5
- TensorFlow installed from (source or binary): Anaconda3
- TensorFlow version (use command below): 1.10.0 (1.10.0-mkl_py36hdb377fd_0)
- Python version: 3.6.6

**Describe the current behavior**
Importing tensorflow causes Cpus allowed list to single core on main thread. That is, when I import tensorflow (even not using it). It will break down multi-thread computing of numpy and gensim (only using single core for matrix multiplication or learning model)

**Describe the expected behavior**
Importing tensorflow should not influence the behavior of other toolkits.

**Code to reproduce the issue**
1. Install tensorflow using anaconda and run ipython:
    ```bash
    conda create -n test tensorflow==1.10.0 gensim ipython
    conda activate test
    ipython
    ```

2. Run the following code in ipython:
    ```python
    import tensorflow
    import numpy as np
    from gensim.models import Word2Vec
    ```

3. Check Cpus allowed list for main thread(in another bash):
    ```bash
    cat /proc/<pid>/status | grep Cpus_allowed_list
    ```
    Output (may vary):
    ```bash
    Cpus_allowed_list:      55-72,108-125
    ```

4. Perform matrix multiplication in ipython:
    ```python
    A = np.random.rand(10000, 10000)
    A = A.dot(A.T)
    del A
    ```

5. Check again Cpus allowed list for main thread:
    ```bash
    cat /proc/<pid>/status | grep Cpus_allowed_list
    ```
    
    Output (may vary):
    
    ```bash
    Cpus_allowed_list:      108
    ```
    
    It become single core! **Note if we do not import tensorflow in step 2. Then the output here will be the same as step 3**. Actually the computing in step 4 can be paralleled. But as we will see in step 6, the other toolkit such as gensim will not work using multicore.

6. Run the following code (make sure you have already run the ipython code above):
    ```python
    cpus = 32 # change it depending on your machine setting
    B = np.random.randint(1,100, size=(5000,5000)).astype('str').tolist()
    model = Word2Vec(B, workers=cpus)
    del model
    ```
    
    You can check in top or htop that ipython will only use one core in executing the third line. **However, if we do not import tensorflow, then it will use 32 cpus and all thing will work fine.**

**Other info**
I don't know whether it is a tensorflow issue or numpy issue (since if we exchange S4 and S6, then it will work fine) or just MKL issue (since if we do not use mkl, but use tensorflow-gpu for numpy without mkl, then it cannot doing parallel matrix computing but gensim will work fine). But I considering that it is importing tensorflow that causes the issue, so I hope someone can give me some idea about this problem.

**Comment by penpornk** [comment]
@dizzam  I'm so sorry for the delay, and thank you for the detailed description!

Just a side note: I got this error `ModuleNotFoundError: No module named 'google_compute_engine` from 
```Python
from gensim.models import Word2Vec
```
I got rid of it with `pip install google_compute_engine`. 

I could reproduce the issues on CentOS 7 and Ubuntu 16.04 with both python and ipython. The issue also persists in the latest release (1.12.0). Interestingly, `Cpus_allowed_list` doesn't change if I call `A.dot(A.T)` once before importing TensorFlow. 

I think you are right that this is related to MKL. The issue disappeared when I switched to TensorFlow CPU without MKL.
```
conda install tensorflow-base==1.12.0=eigen_py36h4dcebc2_0
```

I'll see if this also happens outside Anaconda.

**Comment by penpornk** [comment]
Also looping in @claynerobison since I just remembered @agramesh1 is on vacation.

**Comment by jjhelmus** [comment]
When imported the Anaconda mkl tensorflow packages will set the `KMP_BLOCKTIME` and `OMP_PROC_BIND` environment variables, if they are not already set, to values which have been found to give good performance with an MKL enabled Tensorflow.  These variable may have effects on other libraries which use OpenMP or MKL. 

If these default values are not desired either set the before importing tensorflow to a preferred value or unset them after importing tensorflow using:
```Python
import tensorflow # this sets KMP_BLOCKTIME and OMP_PROC_BIND
import os
del os.environ['OMP_PROC_BIND']
del os.environ['KMP_BLOCKTIME']
```

The specific patch which does this can be found in the [tensorflow_recipes repository](https://github.com/AnacondaRecipes/tensorflow_recipes/blob/06ffb0b8bdb099e83411b80bf01042eb2da7d5f2/tensorflow-base-cpu/0008-set-default-openmp-variables.patch).  Note that the "eigen" and "gpu" variants of the tensorflow package do not include this patch.

**Comment by dizzam** [comment]
Thanks for @preethivenkatesh and @jjhelmus . I have solved this issue by your suggestion.
