### ISSUE TITLE
Load multiple tflite models in APP

### ISSUE THREAD

**Issue by xiaogangLi** [tensorflow/tensorflow#24187]
Hi experts,
I got some errors（it seems to be the APP crash or collapse） when I load multiple SSD_mobilenet tflite models for object detection in a APP with sufficient memory,where these models have different the number of classes.  However, APP work well when I only load a model. So, Could I load multiple tflite models in a APP? Could you please give my advises and instruction of solving this problem? Thanks.

**Comment by achowdhery** [comment]
Do you create different interpreter objects? You should be able to create different interpreter instances linked to each model file and run it in the java app.
Please provide code samples and Android Debugger log details to reproduce the issues you are seeing.

Thanks

**Comment by xiaogangLi** [comment]
Thank you for your instruction.This problem has been solved.

**Comment by pitoulambert** [comment]
I have two models .tflite, the face_detector and a custom model for classification of the image. I want that my app detects the boxes of the face then classifies the face with the label. Can someone help me with this please

**Comment by AmalMtibaa** [comment]
Can someone provide the used code to create interpreter instances ?

**Comment by Hina55** [comment]
I also have two models .tflite for object detection and face recognition and want to use these in a single code with single camera view. Please tell me how can i achieve it?

**Comment by Hina55** [comment]
> Thank you for your instruction.This problem has been solved.

Please guide us or share the usable code to solve this problem.

**Comment by Bio-reactor** [comment]
My research work is ultimately developing an app to record sensor data on board a smart phone such as accelerometer, gyroscope etc and classify the type also use camera for object detection. Both of these needs to be on the same android app. Can someone please guide me to any resources on th same.
Thanks in advance!

**Comment by Bio-reactor** [comment]
@xiaogangLi Hi ,
Sounds like an interseting work. Could you please guide me how did you make it work?

Thanks

**Comment by HarshBarash** [comment]
> I also have two models .tflite for object detection and face recognition and want to use these in a single code with single camera view. Please tell me how can i achieve it?
have you solved this problem?

**Comment by HarshBarash** [comment]
> I also have two models .tflite for object detection and face recognition and want to use these in a single code with single camera view. Please tell me how can i achieve it?

**Comment by HarshBarash** [comment]
have you solved this problem?

**Comment by HarshBarash** [comment]
> > Спасибо за инструкцию. Проблема решена.
> 
> Пожалуйста, помогите нам или поделитесь используемым кодом, чтобы решить эту проблему.

have you solved this problem?

**Comment by bineethk** [comment]
> Hi experts, I got some errors（it seems to be the APP crash or collapse） when I load multiple SSD_mobilenet tflite models for object detection in a APP with sufficient memory,where these models have different the number of classes. However, APP work well when I only load a model. So, Could I load multiple tflite models in a APP? Could you please give my advises and instruction of solving this problem? Thanks.

Can you explain how you solved your issue, please?

**Comment by QuynhAnh2703** [comment]
> I have two models .tflite, the face_detector and a custom model for classification of the image. I want that my app detects the boxes of the face then classifies the face with the label. Can someone help me with this please

Hi, I have the same problem as you, did you have a solution?
Can you help me?

**Comment by usertttwm** [comment]
@QuynhAnh2703 Hello, You should crop after face detection
