### ISSUE TITLE
tf.image (CLAHE) contrast limited adaptive histogram equalization.

### ISSUE THREAD

**Issue by Ouwen** [tensorflow/tensorflow#24181]
**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
`tf.image.clahe` would perform contrast limited adapative histogram equalization to enhance images natively on the tensorflow graph.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Those that want to run image processing natively on tensorflow ops.

**Comment by facaiy** [comment]
@aselle @drpngx what do you think?

**Comment by evolu8** [comment]
Yes please! If it can be GPU optimised and support 16 and 32bit float tensors it would also be a huge improvement over OpenCV etc... Especially for high bit depth users, such as in medical imaging.

**Comment by lunasdejavu** [comment]
We really need this since it is much better to do CLAHE after data augmentation since there are some kinds of grids would be on the image after CLAHE. If we combine it with the random rotation  it would turn the grids to the noise of data augmentation.

**Comment by bhack** [comment]
Please check also (TF1) MCLAHE https://github.com/VincentStimper/mclahe/issues/3

**Comment by evolu8** [comment]
**M**CLAHE would be particularly wonderful - yes please!

**Comment by bhack** [comment]
We had a PR proposal for CLAHE. If you want to try to contribute to MCLAHE please coordinate at https://github.com/tensorflow/addons/issues/2359

**Comment by rmothukuru** [comment]
Yeah, there is an [existing PR](https://github.com/tensorflow/addons/pull/2362) to fix this.

**Comment by gadagashwini** [comment]
Hi @Ouwen, There is a library called `tf-clahe`, Contrast-limited adaptive histogram equalization implemented in tensorflow ops. Install package through `pip install tf-clahe`. Thank you!
