### ISSUE TITLE
Cannot convert between a TensorFlowLite buffer with 1072812 bytes and a ByteBuffer with 270000 bytes.

### ISSUE THREAD

**Issue by T-chuangxin** [tensorflow/tensorflow#24190]
**Train model:**
`python3 /Users/tianchuangxin1/hub/examples/image_retraining/retrain.py     
--image_dir /Users/tianchuangxin1/tensorflow_image    
--how_many_training_steps=2000   
----model_dir=/Users/tianchuangxin1/tensorflow_image  
--output_graph  /Users/tianchuangxin1/tensorflow_image/output_graph.pb  
--output_labels /Users/tianchuangxin1/tensorflow_image/output_labels.txt `
**Test model:**
`python3 /Users/tianchuangxin1/tensorflow/tensorflow/examples/label_image/label_image.py \
--graph=/Users/tianchuangxin1/tensorflow_image/output_graph.pb --labels=/Users/tianchuangxin1/tensorflow_image/output_labels.txt \
--input_layer=Placeholder \
--output_layer=final_result \
--image=/Users/tianchuangxin1/tensorflow_image/apple/apple5.jpg
`
**Get the result:**
`2018-12-06 15:16:48.733220: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
apple 0.99963677
watch 0.0003632232`

**Turn to tflite format:**
`tflite_convert \
  --graph_def_file=/Users/tianchuangxin1/tensorflow_image/output_graph.pb \
  --output_file=/Users/tianchuangxin1/tensorflow_image/output_graph.tflite \
  --output_format=TFLITE \
  --input_shape=1,299,299,3 \
  --input_array=Placeholder \
  --output_array=final_result \
  --inference_type=FLOAT \
  --input_data_type=FLOAT `

**All above have none error.**

**But, i got the crash on Android device:**

`java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 1072812 bytes and a ByteBuffer with 270000 bytes.
        at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:221)
        at org.tensorflow.lite.Tensor.setTo(Tensor.java:93)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:141)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:229)
        at org.tensorflow.demo.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:194)
        at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:249)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:159)
        at android.os.HandlerThread.run(HandlerThread.java:61)
`

**Which step wrong , i have no idea! And spend for a long time!!!!**

**Comment by harshini-gadige** [comment]
Closing this as it is in "awaiting response" status for more than 7 days. Feel free to add your comments and we will reopen(if required).

**Comment by AkshaykumarA** [comment]
Try to set the QUANT as FALSE and give a try & Instead of using byte[][] use the Float[][] in your Classifier class. I had a similar issue and its fixed now.
i.e;
    private static final boolean QUANT = false;
                                   &
    float[][] result = new float[1][labelList.size()];
    interpreter.run(byteBuffer, result);
    return getSortedResultFloat(result);

**Comment by harsh204016** [comment]
I try all the above steps but not working  
java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 3136 bytes and a Java Buffer with 9408 bytes.
![image](https://user-images.githubusercontent.com/37452506/74107330-a1cc8680-4b94-11ea-86d2-30c186816dbb.png)
I have  changed the model , labels and input size ...
@T-chuangxin @AkshaykumarA @Harshini-Gadige @lmoroney

**Comment by physine** [comment]
I know I'm late to the party but this might help someone.

I was getting the same error while trying to implement tflite's objects detection model into another java android app. 
I was going wrong by setting ByteBuffer imgData to 300*300 when the model was expecting an image of 300x300 pixels.  
It should have been set to just 300.

The same thing can probably be said about other tflite models that take images as input.

Find more related info at https://www.tensorflow.org/lite/models/object_detection/overview

**Comment by aryanjain28** [comment]
@physine 

I didn't get what are you trying to say here.
I have attached a screenshot here. Please tell me what to change here.

![err](https://user-images.githubusercontent.com/42910418/87653102-ae23c380-c772-11ea-9619-02de418954b4.jpg)

**Comment by Asilbek0444** [comment]
I have same error, please help me
Error
Cannot copy to a TensorFlowLite tensor (image_tensor) with 270000 bytes from a Java Buffer with 1080000 bytes.
        at org.tensorflow.lite.Tensor.throwIfSrcShapeIsIncompatible(Tensor.java:423)
        at org.tensorflow.lite.Tensor.setTo(Tensor.java:189)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:154)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:343)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:196)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:181)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by AkshaykumarA** [comment]
> I have same error, please help me
> Error
> Cannot copy to a TensorFlowLite tensor (image_tensor) with 270000 bytes from a Java Buffer with 1080000 bytes.
> at org.tensorflow.lite.Tensor.throwIfSrcShapeIsIncompatible(Tensor.java:423)
> at org.tensorflow.lite.Tensor.setTo(Tensor.java:189)
> at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:154)
> at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:343)
> at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:196)
> at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:181)
> at android.os.Handler.handleCallback(Handler.java:790)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:164)
> at android.os.HandlerThread.run(HandlerThread.java:65)

Try to set the QUANT as FALSE and give a try & Instead of using byte[][] use the Float[][] in your Classifier class.

**Comment by physine** [comment]
@AkshaykumarA 
tflite's object detection model is quantized so you need to keep it as true.
read this , specifically the part about input, I might help. https://www.tensorflow.org/lite/models/object_detection/overview

@aryanjain28 
that image doesn't help.  What are you trying to do?  Are you trying to add tflite functionallity from scratch into another app or what?
What is the value you [imgData ](https://github.com/tensorflow/examples/blob/1f1ff5b2807ba5f2beccf362aef79332d7cc6216/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java#L78)at run time?  

Do this and see if it works.
private ByteBuffer imgData = 300;

**Comment by yogithesymbian** [comment]
@physine private ByteBuffer imgData = 300 ;
required java.nio.ByteBuffer

**Comment by yogithesymbian** [comment]
i got same error
i have model with this  step
https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/model_maker_image_classification.ipynb

what should i do for clear the error "
```
    java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (input_2) with 602112 bytes from a Java Buffer with 270000 bytes.
        at org.tensorflow.lite.Tensor.throwIfSrcShapeIsIncompatible(Tensor.java:444)
        at org.tensorflow.lite.Tensor.setTo(Tensor.java:189)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:154)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:347)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:196)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:181)
```

**Comment by AngSoonKim** [comment]
Not too sure if it helps, but I managed to solve the issue (thanks to all your hints) by changing the parameter in the DetectorActivity.java

1) private static final int TF_OD_API_INPUT_SIZE = 320; (from 300 to 320 as it was the parameter of the model)
2) private static final boolean TF_OD_API_IS_QUANTIZED = false; (from true to false)

I have also made the following changes:
-Change line 122 from to 132 with the below code on TFLiteObjectDetectionAPIModel.java there are two files in this same name open the interpreter one and not the task one.
press alt+enter to resove error on InputStream then save it

```
    AssetManager am = context.getAssets();
    try (InputStream is = am.open(labelFilename);
         BufferedReader br = new BufferedReader(new InputStreamReader(is))) {
      String line;
      while ((line = br.readLine()) != null) {
        Log.w(TAG, line); d.labels.add(line);
      }
    }
```
following the tutorial by https://www.youtube.com/watch?v=syTKGY-H44E&t=366s (although I am not too sure how it affect the app to run)

I build the model using tensor flow 2 instead of tensor flow 1.

**Comment by srushtipokiya** [comment]
### ### ### ### **_****_**
