### ISSUE TITLE
TypeError: Expected binary or unicode string, got None

### ISSUE THREAD

**Issue by forviq** [tensorflow/tensorflow#24200]
**System information**
- OS Platform and Distribution Linux Ubuntu 16.04
- TensorFlow version (use command below):
- Python version 3.5:
- CUDA/cuDNN version9.0:
- GPU model and memory: tesla k80

**Comment by forviq** [comment]
``` python
model {
  ssd {
    num_classes: 90
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
        reduce_boxes_in_lowest_layer: true
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 3
        box_code_size: 4
        apply_sigmoid_to_scores: false
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            truncated_normal_initializer {
              stddev: 0.03
              mean: 0.0
            }
          }
        }
      }
    }
    feature_extractor {
      type: 'ssd_inception_v2'
      min_depth: 16
      depth_multiplier: 1.0
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          train: true,
          scale: true,
          center: true,
          decay: 0.9997,
          epsilon: 0.001,
        }
      }
      override_base_feature_extractor_hyperparams: true
    }
    loss {
      classification_loss {
        weighted_sigmoid {
        }
      }
      localization_loss {
        weighted_smooth_l1 {
        }
      }
      hard_example_miner {
        num_hard_examples: 3000
        iou_threshold: 0.99
        loss_type: CLASSIFICATION
        max_negatives_per_positive: 3
        min_negatives_per_image: 0
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  batch_size: 24
  optimizer {
    rms_prop_optimizer: {
      learning_rate: {
        exponential_decay_learning_rate {
          initial_learning_rate: 0.004
          decay_steps: 800720
          decay_factor: 0.95
        }
      }
      momentum_optimizer_value: 0.9
      decay: 0.9
      epsilon: 1.0
    }
  }
  fine_tune_checkpoint: "~/models/research/object_detection/ssd_inception_v2_coco_2018_01_28/model.ckpt.*"
  from_detection_checkpoint: true
  # Note: The below line limits the training process to 200K steps, which we
  # empirically found to be sufficient enough to train the pets dataset. This
  # effectively bypasses the learning rate schedule (the learning rate will
  # never decay). Remove the below line to train indefinitely.
  num_steps: 200000
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    ssd_random_crop {
    }
  }
}

train_input_reader: {
  tf_record_input_reader {
    input_path: "~/models/research/object_detection/training/coco_train.record-?????-of-00100"
  }
  label_map_path: "~/models/research/object_detection/data/mscoco_label_map.pbtxt"
}

eval_config: {
  num_examples: 8000
  # Note: The below line limits the evaluation process to 10 evaluations.
  # Remove the below line to evaluate indefinitely.
  max_evals: 10
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "~/models/research/object_detection/training/coco_val.record-?????-of-00010"
  }
  label_map_path: "~/models/research/object_detection/data/mscoco_label_map.pbtxt"
  shuffle: false
  num_readers: 1
}

```

**Comment by forviq** [comment]
``` python
python model_main.py --model_
dir=~/models/research/object_detection/train/ \ --pipeline_config_path=~/models/research/ob
ject_detection/samples/configs/ssd_inception_v2_coco.config \ --alsologtostderr
```

**Comment by forviq** [comment]
and i have
``` python
Traceback (most recent call last):
  File "object_detection/model_main.py", line 109, in <module>
    tf.app.run()
  File "/home/taras_saveniuk/.local/lib/python3.5/site-packages/tensorflow/python/platform/
app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 71, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
  File "/home/taras_saveniuk/models/research/object_detection/model_lib.py", line 536, in c
reate_estimator_and_inputs
    config_override=config_override)
  File "/home/taras_saveniuk/models/research/object_detection/utils/config_util.py", line 9
5, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "/home/taras_saveniuk/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/fi
le_io.py", line 125, in read
    self._preread_check()
  File "/home/taras_saveniuk/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/fi
le_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/taras_saveniuk/.local/lib/python3.5/site-packages/tensorflow/python/util/comp
at.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None
```

**Comment by ymodak** [comment]
Apologies for the delay in response. This issue is more suitable for TensorFlow Models repo. Please post it on models repo from [here](https://github.com/tensorflow/models/issues/new). Thanks!

**Comment by rasastry** [comment]
How did you resolve this?  I am having the same error report.

Appreciate a reply.   Thanks

(tlearn) ramesh@sentry-ramesh:~/projects/perid/tensorflow/models/research$ python object_detection/model_main.py \ --pipeline_config_path=$/home/ramesh/projects/perid/tensorflow/models/training/models/ssd_mobilenet_v1_coc.config \ --model_dir=$/home/ramesh/projects/perid/tensorflow/models/training/models \ --num_train_steps=$2000 \ --sample_1_of_n_eval_examples=$2 \ --alsologtostderr
Traceback (most recent call last):
  File "object_detection/model_main.py", line 109, in <module>
    tf.app.run()
  File "/home/ramesh/anaconda3/envs/tlearn/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 71, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
  File "/home/ramesh/projects/perid/tensorflow/models/research/object_detection/model_lib.py", line 566, in create_estimator_and_inputs
    config_override=config_override)
  File "/home/ramesh/projects/perid/tensorflow/models/research/object_detection/utils/config_util.py", line 95, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "/home/ramesh/anaconda3/envs/tlearn/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/home/ramesh/anaconda3/envs/tlearn/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/ramesh/anaconda3/envs/tlearn/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

**Comment by Shruthi-Sampathkumar** [comment]
> How did you resolve this? I am having the same error report.
> 
> Appreciate a reply. Thanks
> 
> (tlearn) ramesh@sentry-ramesh:~/projects/perid/tensorflow/models/research$ python object_detection/model_main.py \ --pipeline_config_path=$/home/ramesh/projects/perid/tensorflow/models/training/models/ssd_mobilenet_v1_coc.config \ --model_dir=$/home/ramesh/projects/perid/tensorflow/models/training/models \ --num_train_steps=$2000 \ --sample_1_of_n_eval_examples=$2 \ --alsologtostderr
> Traceback (most recent call last):
> File "object_detection/model_main.py", line 109, in 
> tf.app.run()
> File "/home/ramesh/anaconda3/envs/tlearn/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "object_detection/model_main.py", line 71, in main
> FLAGS.sample_1_of_n_eval_on_train_examples))
> File "/home/ramesh/projects/perid/tensorflow/models/research/object_detection/model_lib.py", line 566, in create_estimator_and_inputs
> config_override=config_override)
> File "/home/ramesh/projects/perid/tensorflow/models/research/object_detection/utils/config_util.py", line 95, in get_configs_from_pipeline_file
> proto_str = f.read()
> File "/home/ramesh/anaconda3/envs/tlearn/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
> self._preread_check()
> File "/home/ramesh/anaconda3/envs/tlearn/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
> compat.as_bytes(self.__name), 1024 * 512, status)
> File "/home/ramesh/anaconda3/envs/tlearn/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 61, in as_bytes
> (bytes_or_text,))
> TypeError: Expected binary or unicode string, got None

Were you able to solve this? @rasastry
