### ISSUE TITLE
TypeError: an integer is required executing skflow text classification examples

### ISSUE THREAD

**Issue by servomac** [tensorflow/tensorflow#2420]
Using a nightly build I'm unable to execute the text classification examples in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/skflow (I have tried text_classification.py, text_classification_cnn.py and text_classification_builtin_rnn_model.py).

`$ sudo pip3 install --upgrade http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_CONTAINER_TYPE=CPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=cpu-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl 

$ python3 -c "import tensorflow; print(tensorflow.__version__)"
0.8.0

$ python3 rnn.py
Total words: 822383
Traceback (most recent call last):
  File "rnn.py", line 68, in <module>
    classifier.fit(X_train, y_train, logdir='/tmp/tf_examples/word_rnn')
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 270, in fit
    feed_params_fn=self._data_feeder.get_feed_params)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/trainer.py", line 49, in train
    feed_dict = feed_dict_fn()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/io/data_feeder.py", line 324, in _feed_dict_fn
    out.itemset((i, self.y[sample]), 1.0)
TypeError: an integer is required`

**Comment by twinsken** [comment]
i think this part hasn't been finished yet. You can modify out.itemset((i, self.y[sample]), 1.0) ->> out.itemset((i, int(self.y[sample])), 1.0). Convert the type of y_train and y_test to numpy array. Besides, it has implemented continue_training function.  I test cnn, rnn and character-rnn and character-cnn. Both character-level model cant achieve a baseline model.

**Comment by girving** [comment]
Thanks @alrojo for the upcoming fix!
