### ISSUE TITLE
Spurious syntax highlighting of code blocks in site documentation

### ISSUE THREAD

**Issue by colinmorris** [tensorflow/tensorflow#24204]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: N/A
- Doc Link: Various, but see for example [/community/documentation](https://www.tensorflow.org/community/documentation), [/guide/debugger](https://www.tensorflow.org/guide/debugger), or [/guide/datasets_for_estimators](https://www.tensorflow.org/guide/datasets_for_estimators)

**Describe the documentation issue**
Many of the code blocks in [this guide on Writing Tensorflow Documentation](https://www.tensorflow.org/community/documentation#description_of_the_docstring_sections) are meant to represent markdown, but they're syntax highlighted as... something else. e.g. the word "from" is highlighted as if it were a keyword in:
```
Flips an image horizontally from left to right.
```

These blocks should either have no syntax highlighting, or markdown syntax highlighting (if the library you're using for syntax highlighting allows it).

In some cases, authors have explicitly used a language identifier of 'none' in fenced code blocks, presumably to try to suppress syntax highlighting, but it doesn't look like that's respected when rendering. For example, the first two code blocks in [/guide/debugger](https://www.tensorflow.org/guide/debugger) are tagged 'none' in [the corresponding md file](https://github.com/tensorflow/docs/blob/master/site/en/guide/debugger.md), but the "Accuracy at step..." block is still lit up like a Christmas tree.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
I wish I could, but as far as I can tell, the markdown -> html part of the docs pipeline isn't part of any public repo.

**Comment by epicfaace** [comment]
Any thoughts @lamberta @MarkDaoust ? Here is a screenshot for reference.

![image](https://user-images.githubusercontent.com/1689183/50228406-dcaea200-0375-11e9-990f-921ec896ef33.png)

**Comment by MarkDaoust** [comment]
Thanks for reporting this @colinmorris.

It uses [prettify](https://github.com/google/code-prettify#how-do-i-specify-the-language-of-my-code) to do the syntax highlighting. There doesn't seem to be a markdown option. 

You can use a `<pre>` tag without the "prettyprint" class to render as plain text. 

```
<pre>
Flips an image horizontally from left to right.
</pre>
```

produces on the site.

```
Flips an image horizontally from left to right.
```

Any chance you could send a PR fixing those problems?
(And maybe mention this, and that link to prettify link to community/documentation?)

**Comment by epicfaace** [comment]
Sure. How do I generate documentation locally from https://github.com/tensorflow/docs?

**Comment by MarkDaoust** [comment]
> @MarkDaoust , sure. How do I generate documentation for specific pages locally?

There's no way to preview the final product :(. A lot of the pipeline is built into the site infrastructure, so there's no way to opensource it.
