### ISSUE TITLE
Whether Tf has the operations table?

### ISSUE THREAD

**Issue by Milittle** [tensorflow/tensorflow#24213]
I want to know about TF, whether it has the operations table?
Can any one tell me to know about it?
Thanks.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by Milittle** [comment]
> This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

Sorry about that, thank you.
