### ISSUE TITLE
Bazel test fail. Error deduced conflicting types. 

### ISSUE THREAD

**Issue by legatoo** [tensorflow/tensorflow#24212]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Mac OS Mojave 10.14.1 (18B75)
- TensorFlow installed from (source or binary): source
- TensorFlow version: branch r1.12
- Python version: 3.6.6 
- Installed using virtualenv? pip? conda?: building is in a virtualenv created by `pyenv virtualenv 3.6.6 my_tf_build_env`
- Bazel version (if compiling from source): from source. 0.15.0
- GCC/Compiler version (if compiling from source): Apple LLVM version 10.0.0 (clang-1000.11.45.5)
- CUDA/cuDNN version:  no cuda, build only for cpu
- GPU model and memory: Intel Core i7, 16 GB

**Describe the problem**

I was following the tutorial to build tensorflow from source.  I was on the `r1.12` branch, root directory, typed `bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/lite/...`. Error Message:

![image](https://user-images.githubusercontent.com/1506580/49625289-efd57f80-fa0f-11e8-9ac5-e66542c8ff04.png)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

commands sequence is same as this [tutorial](https://www.tensorflow.org/install/source).
In the `./configure` part, my configuration is like below:

![image](https://user-images.githubusercontent.com/1506580/49625409-61adc900-fa10-11e8-80bf-687a5ca32db0.png)

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by yongtang** [comment]
Added a PR #24237 for the fix.

**Comment by legatoo** [comment]
> Added a PR #24237 for the fix.

Thank you.
