### ISSUE TITLE
something between tf 1.2.1 -> 1.12.0 causing call stack issues in embedded python

### ISSUE THREAD

**Issue by denfromufa** [tensorflow/tensorflow#24211]
https://github.com/pythonnet/pythonnet/issues/792

This code running in pythonnet now crashes:

```
import tensorflow as tf
flags = tf.app.flags
flags.DEFINE_integer("batch_size", 32, "Number of samples per batch")
```

in scriptcs:

```
> #r C:\Python\Python35_64b\lib\site-packages\Python.Runtime.dll
> using Python.Runtime;
> PythonEngine.Initialize();
> dynamic tf = Py.Import("tensorflow");
> tf.app.flags.DEFINE_integer("batch_size", 32, "Number of samples per batch");
ValueError : call stack is not deep enough
```

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing this issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). Thanks!
