### ISSUE TITLE
[Tensorrt] Cannot convert when the batch dimension is changed

### ISSUE THREAD

**Issue by paduck86** [tensorflow/tensorflow#24214]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I'm trying to convert seq2seq model graph to trt graph. 
But it seems that the Reshape OP cannot be converted when the batch dimension is changed.
If possible, do  you have any plan to provide support for this feature?

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by pooyadavoodi** [comment]
@paduck86 You would have to use the dynamic mode if you have dynamic shapes ( set `is_dynamic_op=True` when you call `create_inference_graph`). Could you please try that and let us know if that changes anything?

We are still working on improving TF-TRT with dynamic shapes (e.g. caching). This would affect a lot of models such as object detection and seq2seq. @trevor-m

**Comment by paduck86** [comment]
Thank you very much for your reply.
But there's no change after setting is_dynamic_op=True.
I am particularly struggling with attention module because the module change batch size on 3d*2d matmul operation.
I'll try again tomorrow and if there's another change, I'll answer it again.

**Comment by pooyadavoodi** [comment]
Could you post the log. A small repro would be great too.

Does the conversion crash or some of engines fail during build/execution?

**Comment by trevor-m** [comment]
TensorRT does not support any modification of the batch dimension. They are planning to add support in the future, but it will not be available for a while.

For 3d*2d matmul, I have a workaround that involve changing your model. This will avoid the reshapes on the batch dimension. Are you using tf.layers.Dense()?

Try replacing your layers like so:
```
def linear_proj(x, hidden_size, name='q'):
      with tf.variable_scope(name):
        kernel = tf.get_variable("kernel", shape=[x.get_shape().as_list()[-1], hidden_size])
        with tf.variable_scope("Tensordot", reuse=tf.AUTO_REUSE):
          kernel = tf.expand_dims(kernel, 0)
          return tf.nn.conv1d(x, kernel, 1, 'VALID', data_format='NWC')

# Instead of:
#y = tf.layers.Dense(hidden_size, use_bias=False, name="q")(x)
# Use this:
y = linear_proj(x, hidden_size)
```
You will need to use TF1.13 or later (use master branch for best results).

**Comment by samikama** [comment]
Closing this. Let us know if comment above is not clear.
