### ISSUE TITLE
 After compiling tensorflow for golang, it was found that python tensorflow could not be imported normally.

### ISSUE THREAD

**Issue by wangqiqianggithub** [tensorflow/tensorflow#24217]
when i import tensorflow ,it happend errors.
python 3.6.5, macOS
----> 1 import tensorflow as tf

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/__init__.py in <module>
     22
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25
     26 try:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>
     47 import numpy as np
     48
---> 49 from tensorflow.python import pywrap_tensorflow
     50
     51 from tensorflow.python.tools import component_api_helper

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: __ZN10tensorflow13DeviceFactory10AddDevicesERKNS_14SessionOptionsERKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEPNS4_6vectorIPNS_6DeviceENS8_ISF_EEEE
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Expected in: /Users/wqq/go/src/github.com/tensorflow/tensorflow/bazel-bin/tensorflow/libtensorflow_framework.so
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so

**Comment by harshini-gadige** [comment]
@wangqiqianggithub  We understand that you are having tensorflow import issues with golang. In order to proceed assisting you, request you to fill [this](https://github.com/tensorflow/tensorflow/issues/new/choose) template which helps us to look into this.

**Comment by wangqiqianggithub** [comment]
In fact, I have solved this problem. In the process, I learned that setting environment variables is not very scientific when compiling golang packages, which may affect the import of tensorflow by other languages. After I commented out the following two environment variables, my python was able to use tensorflow normally.`#settting path for golang-tensorflow
  #export DYLD_LIBRARY_PATH=${GOPATH}/src/github.com/tensorflow/tensorflow/bazel-bin/tensorflow
  #export LIBRARY_PATH=${GOPATH}/src/github.com/tensorflow/tensorflow/bazel-bin/tensorflow`
We might want to do the first, which is copy the compiled file into /usr/local/lib。
`sudo cp ${GOPATH}/src/github.com/tensorflow/tensorflow/bazel-bin/tensorflow/libtensorflow.so /usr/local/lib`
the parper link is [https://github.com/tensorflow/tensorflow/tree/master/tensorflow/go](url).
thank you all the same,be happy. @harshini-gadige
