### ISSUE TITLE
SKLearn examples not working in the latest release

### ISSUE THREAD

**Issue by perrohunter** [tensorflow/tensorflow#2421]
I've been trying to run some examples from the provided SKFlow examples located at 

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/skflow

And most fail with dependency failures such as: 

AttributeError: 'module' object has no attribute 'datasets'

For:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/skflow/text_classification_builtin_rnn_model.py

I looked around the source code and some of this modules seem to have been moved around, maybe this examples should be updated or completely removed, I tried adapting the code to work however I ended copying big chunks of source code into the file to make it work.

using tensorflow 0.8

**Comment by mrry** [comment]
The skflow examples in the master branch have changed to use a new API that isn't present in the 0.8 release. There are two options:

1. Download the examples from the `r0.8` branch: https://github.com/tensorflow/tensorflow/tree/r0.8/tensorflow/examples/skflow
2. Install a [nightly version of TensorFlow](https://github.com/tensorflow/tensorflow#installation) and use the examples from the master branch.

**Comment by zd123** [comment]
Hey, if you dont want to re-install the nightly build, you can manually download the same dataset.  I've documented ez steps here:  http://stackoverflow.com/questions/37206459/tensorflow-examples-all-fail-due-to-attributeerror-module-object-has-no-attri
