### ISSUE TITLE
FP16 support on GPU for scatter_max

### ISSUE THREAD

**Issue by ZhouYuChen** [tensorflow/tensorflow#24219]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):  v1.12.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
scatter_max supports fp32, fp64 on GPU and fp16, fp32, fp64 on CPU.
It will be nice if scatte_max can support fp16 on GPU.

**Will this change the current api? How?**
no

**Who will benefit with this feature?**
Everyone who wants to use scatter_max with fp16 in gpu.

**Any Other info.**
```python
import tensorflow as tf

with tf.device("/device:GPU:0"):
  # dtype=tf.float16 won't work in this code sample
  u = tf.constant([[1,6,8], [2,4,9], [3,5,7]]*3, dtype=tf.float32)
  r = tf.get_variable("r", [4, 3], dtype=tf.float32)
  y = tf.scatter_max(r, [0,0,0,1,1,2,2,3,3], u)

  with tf.Session() as sess:
    tf.initialize_all_variables().run()
    print(sess.run(y))
```

**Comment by yongtang** [comment]
Added PR #24224 for float16 support.
