### ISSUE TITLE
Can't use tf.gradients to get the gradients of a tf.gather_np op

### ISSUE THREAD

**Issue by KrisHan999** [tensorflow/tensorflow#24216]
I wanna get the gradients of a tf.gather(params, indices) as for indices, but when I do gradients = tf.gradients(ys=out_1, xs=indices). Gradients is None.

```
params = tf.constant(np.array([[1,2], [3,4]]))
indices = tf.constant(np.array([[[0,0],[0,1]],[[1,1],[0,1]]]))
w = tf.constant(np.random.randn(4,3), dtype=tf.float32)
with tf.Session() as sess:
    out_1 = tf.gather_nd(params=params, indices=indices)
    print(sess.run(out_1))
    gradients = tf.gradients(ys=out_1, xs=indices)
    print(gradients)
    print(sess.run(gradients))
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-c4fb622d33f8> in <module>()
     10     gradients = tf.gradients(ys=out_1, xs=indices)
     11     print(gradients)
---> 12     print(sess.run(gradients))

C:\Users\11198\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

C:\Users\11198\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1135     # Create a fetch handler to take care of the structure of fetches.
   1136     fetch_handler = _FetchHandler(
-> 1137         self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
   1138 
   1139     # Run request and get response.

C:\Users\11198\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py in __init__(self, graph, fetches, feeds, feed_handles)
    469     """
    470     with graph.as_default():
--> 471       self._fetch_mapper = _FetchMapper.for_fetch(fetches)
    472     self._fetches = []
    473     self._targets = []

C:\Users\11198\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py in for_fetch(fetch)
    259     elif isinstance(fetch, (list, tuple)):
    260       # NOTE(touts): This is also the code path for namedtuples.
--> 261       return _ListFetchMapper(fetch)
    262     elif isinstance(fetch, collections.Mapping):
    263       return _DictFetchMapper(fetch)

C:\Users\11198\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py in __init__(self, fetches)
    368     """
    369     self._fetch_type = type(fetches)
--> 370     self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
    371     self._unique_fetches, self._value_indices = _uniquify_fetches(self._mappers)
    372 

C:\Users\11198\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py in <listcomp>(.0)
    368     """
    369     self._fetch_type = type(fetches)
--> 370     self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
    371     self._unique_fetches, self._value_indices = _uniquify_fetches(self._mappers)
    372 

C:\Users\11198\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py in for_fetch(fetch)
    256     if fetch is None:
    257       raise TypeError('Fetch argument %r has invalid type %r' % (fetch,
--> 258                                                                  type(fetch)))
    259     elif isinstance(fetch, (list, tuple)):
    260       # NOTE(touts): This is also the code path for namedtuples.

TypeError: Fetch argument None has invalid type <class 'NoneType'>

**Comment by KrisHan999** [comment]
> tf.gather_nd returns A `Tensor` out_1, and out_1 is not a function of indices.

If there is anyway to calculate the gradient of tf.gather_nd function?  I see there is a `def _GatherNdGrad(op, grad):` in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_grad.py#L355

**Comment by jvishnuvardhan** [comment]
@KrisHan999 This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing this support issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). Thanks!
