### ISSUE TITLE
Why there are two nnapi_delegate.cc with the same name?

### ISSUE THREAD

**Issue by tingxingdong** [tensorflow/tensorflow#24225]
In r1.12

There is one under the folder https://github.com/tensorflow/tensorflow/tree/r1.12/tensorflow/contrib/lite/delegates/nnapi

The other one is 

https://github.com/tensorflow/tensorflow/tree/r1.12/tensorflow/contrib/lite

Can anybody explain what the two files are doing? Can they be named differently? Looks very confusing.

**Comment by tingxingdong** [comment]
https://github.com/tensorflow/tensorflow/tree/r1.12/tensorflow/contrib/lite/delegates/nnapi is used in unit test. 

https://github.com/tensorflow/tensorflow/tree/r1.12/tensorflow/contrib/lite is mostly used

**Comment by achowdhery** [comment]
@tingxingdong Did you resolve your question? If yes, we can close this bug.

**Comment by jdduke** [comment]
We plan on transitioning to using the one in lite/delegates/nnapi. We should probably rename the one in lite/ to avoid confusion, thanks for the report.
