### ISSUE TITLE
No Device Mapped with Tensorflow-gpu - Ubuntu 18.04

### ISSUE THREAD

**Issue by Isabella-C** [tensorflow/tensorflow#24220]
## System information
- OS Platform and Distribution: Ubuntu 18.04.1 LTS x86_64
- TensorFlow installed from (source or binary): Miniconda (used cmd: 'conda install -c anaconda tensorflow-gpu')
- TensorFlow version: Tensorflow-gpu (Tried both 1.12.0 and 1.9.0, and got the same result)
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: Conda
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): GCC 7.3.0
- CUDA/cuDNN version: 9.0
- GPU model and memory: As below.

## CPU and GPU info
CPU: Intel i7-8750H (12) @ 4.100GHz
GPU: NVIDIA GeForce GTX 1070 Mobile
GPU: Intel Device 3e9b

## Describe the problem

It looks like in the 'Device Mapping' section as below, no GPU is linked, though no error msg noted in code. Strangely though, the GPU name/mode has been detected. Would you please help?

Details as below.

Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import os
>>> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
>>> tf.Session(config=tf.ConfigProto(log_device_placement=True))
2018-12-08 00:44:56.363230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2018-12-08 00:44:56.363327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-08 00:44:56.363349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2018-12-08 00:44:56.363370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2018-12-08 00:44:56.363659: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6738 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 6.1)
Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 6.1
2018-12-08 00:44:56.371266: I tensorflow/core/common_runtime/direct_session.cc:288] Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 6.1

<tensorflow.python.client.session.Session object at 0x7f693a136ef0>

## Provide the exact sequence of commands / steps that you executed before running into the problem
 Pretty much followed this post:
https://mc.ai/install-conda-tensorflow-gpu-and-keras-on-ubuntu-18-04/

## GPU Driver Info 

Sat Dec  8 00:56:11 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.57                 Driver Version: 410.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 107...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P3    24W /  N/A |    936MiB /  8119MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1142      G   /usr/lib/xorg/Xorg                           535MiB |
|    0      1313      G   /usr/bin/gnome-shell                         217MiB |
|    0      1941      G   ...quest-channel-token=4040395960093113594   181MiB |
+-----------------------------------------------------------------------------+

## cuDNN ver

cudnn-9.0-linux-x64-v7.1.tgz 

## Full info for CUDA

$ ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 1070 with Max-Q Design"
  CUDA Driver Version / Runtime Version          10.0 / 9.0
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 8120 MBytes (8513978368 bytes)
  (16) Multiprocessors, (128) CUDA Cores/MP:     2048 CUDA Cores
  GPU Max Clock rate:                            1266 MHz (1.27 GHz)
  Memory Clock rate:                             4004 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 2097152 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 10.0, CUDA Runtime Version = 9.0, NumDevs = 1
Result = PASS

## Check if cards are recognised on the bus:
$ lspci | grep -i nvidia
01:00.0 VGA compatible controller: NVIDIA Corporation GP104M [GeForce GTX 1070 Mobile] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GP104 High Definition Audio Controller (rev a1)

## Check Drivers:
$ dmesg | grep NVRM
[    3.286908] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  410.57  Tue Sep 18 23:25:09 CDT 2018 (using threaded interrupts)

Thanks very much in advance!

**Comment by ymodak** [comment]
This means that your GPU is located and linked
> Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6738 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 6.1)

**Comment by Isabella-C** [comment]
Thanks ymodak. But, then why it's 'GPU: 0'?

**Comment by ymodak** [comment]
That's just your device name. If you run **nvidia-smi** in your terminal you should be able to it.

**Comment by Isabella-C** [comment]
Ah, I see. Thanks a lot. I'll close the issue then.
