### ISSUE TITLE
Why not allow feeding and fetching the same tensor?

### ISSUE THREAD

**Issue by RafaelCosman** [tensorflow/tensorflow#2422]
Currently this generates `InvalidArgumentError: Placeholder_2:0 is both fed and fetched.`

It doesn't seem like a particularly useful thing but why not trivially allow this behavior? We might as well allow users to fetch any tensor in the graph.

**Comment by mrry** [comment]
The answer here is that it would require extra code to be written and tested, and&mdash;as you point out&mdash;it's not particularly useful :).
