### ISSUE TITLE
Build Tensorflow 1.12-GPU with CUDA10 Failed On Windows

### ISSUE THREAD

**Issue by rootkitchao** [tensorflow/tensorflow#24233]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):MS Windows10 X64 1809 17763
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.12
- Python version:3.6
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):0.15.0
- GCC/Compiler version (if compiling from source):MSVC2015 Update3
- CUDA/cuDNN version:10.0/7.4.1
- GPU model and memory:NVIDIA Geforce RTX2080TI 11GB *2

**Describe the problem**
I am trying to compile tensorflow from source but failed.Follow the guide on the official website(https://tensorflow.google.cn/install/source_windows) to run bazel build and report an error:
.\tensorflow/compiler/tf2xla/cpu_function_runtime.h(71): error C2338:
......
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 97.739s, Critical Path: 37.10s
INFO: 234 processes: 234 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
N/A

**Comment by ymodak** [comment]
I see that you are using CUDA 10.0. TensorFlow officially supports CUDA 9.0. However you can still use CUDA 10.0 but for that you have to build TensorFlow from sources yourself. You can also take a look at an [attempt](https://www.pugetsystems.com/labs/hpc/Install-TensorFlow-with-GPU-Support-on-Windows-10-without-a-full-CUDA-install-1172/) made by other users to install the same. Thanks!

**Comment by ymodak** [comment]
You also need to install [Visual C++ Build Tools 2015](https://www.tensorflow.org/install/source_windows#install_visual_c_build_tools_2015) and later [update environment path](https://www.tensorflow.org/install/gpu#windows_setup) for cuda,cuDNN,cupti.

**Comment by rootkitchao** [comment]
> You also need to install [Visual C++ Build Tools 2015](https://www.tensorflow.org/install/source_windows#install_visual_c_build_tools_2015) and later [update environment path](https://www.tensorflow.org/install/gpu#windows_setup) for cuda,cuDNN,cupti.

I have reinstalled MS Visual C++ build tools 2015 Update3, reset the environment variable %PATH, bazel still reports an error.

log:
ERROR: D:/code/tensorflow-1.12.0/tensorflow/compiler/tf2xla/BUILD:97:1: C++ compilation of rule '//tensorflow/compiler/tf2xla:cpu_function_runtime' failed (Exit 2): msvc_wrapper_for_nvcc.bat failed: error executing command
  cd C:/users/william/_bazel_william/ll7iqrfr/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\\shared;C:\Program Files (x86)\Windows Kits\8.1\include\\um;C:\Program Files (x86)\Windows Kits\8.1\include\\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/william/AppData/Local/Programs/Python/Python36/python.exe
    SET PYTHON_LIB_PATH=C:/Users/william/AppData/Local/Programs/Python/Python36/lib/site-packages
    SET TEMP=C:\Users\william\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=7.0
    SET TF_CUDA_VERSION=9.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\william\AppData\Local\Temp
  external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/genfiles /Iexternal/nsync /Ibazel-out/x64_windows-opt/genfiles/external/nsync /Iexternal/bazel_tools /Ibazel-out/x64_windows-opt/genfiles/external/bazel_tools /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/x64_windows-opt/genfiles/external/local_config_sycl /Iexternal/nsync/public /Ibazel-out/x64_windows-opt/genfiles/external/nsync/public /Ibazel-out/x64_windows-opt/bin/external/nsync/public /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /showIncludes /MD /O2 /DNDEBUG -w /arch:AVX2 /Fobazel-out/x64_windows-opt/bin/tensorflow/compiler/tf2xla/_objs/cpu_function_runtime/cpu_function_runtime.o /c tensorflow/compiler/tf2xla/cpu_function_runtime.cc

**Comment by ymodak** [comment]
@rootkitchao Is this still an issue for you?

**Comment by rootkitchao** [comment]
@ymodak Yes, I still have not been able to successfully compile Tensorflow-GPU with CUDA10.0.I decided to wait for Tensorflow 2.0.

**Comment by gunan** [comment]
@chsigg and I ran into a similar issue.
We believe we are running into a bug in nvcc.

**Comment by gunan** [comment]
It will, eventually.
But it is likely out of TF control. @chsigg is there a public bug with nvidia we can share?

**Comment by chsigg** [comment]
This is not an nvcc bug, but rather MSVC producing an unexpected size (24 bytes vs 16 bytes) for this class. See https://godbolt.org/z/YDOgqz

This is because MSVC does not merge bit-fields if the size of the types are different (4 bytes for kind_, 8 bytes for size_).

Changing the type of Kind to uint64 should fix it.

**Comment by chsigg** [comment]
Hm, but that would also imply that it's not CUDA 10 specific, but XLA specific (because it's XLA code). Is that possible?

**Comment by chsigg** [comment]
This should be fixed now. I'm closing this issue, please let us know if you are still experiencing issues. Thanks for reporting!

**Comment by rootkitchao** [comment]
Thanks to everyone who helped solve this issue.After disabling XLA, I have been able to successfully compile Tensorflow-GPU with CUDA10.0 and got some FP16 performance improvements.

**Comment by GuoQuanhao** [comment]
SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\shared;C:\Program Files (x86)\Windows Kits\8.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\winrt;
SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;

I want to know can I choose the include path, I have installed several visual studio
