### ISSUE TITLE
window10+cuda10.0+anaconda3+tensorflow-r1.12

### ISSUE THREAD

**Issue by wuqingshan2010** [tensorflow/tensorflow#24241]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):window 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.12
- Python version:3.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):0.20
- GCC/Compiler version (if compiling from source):Visual Studio 2015
- CUDA/cuDNN version:10.0
- GPU model and memory:6.0

**Describe the problem**
  'build' options: --action_env PYTHON_BIN_PATH=C:/Soft/Anaconda3/python.exe --action_env PYTHON_LIB_PATH=C:/Soft/Anaconda3/lib/site-packages --python_path=C:/Soft/Anaconda3/python.exe --define with_ignite_support=true --action_env TF_NEED_OPENCL_SYCL=0 --action_env TF_NEED_ROCM=0 --action_env TF_NEED_CUDA=1 --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0 --action_env TF_CUDA_VERSION=10.0 --action_env CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0 --action_env TF_CUDNN_VERSION=7 --action_env TF_CUDA_COMPUTE_CAPABILITIES=6.0 --action_env TF_CUDA_CLANG=0 --config=cuda --config monolithic --copt=-w --host_copt=-w --verbose_failures --distinct_host_configuration=false --experimental_shortened_obj_file_path=true --define=no_tensorflow_py_deps=true --define=override_eigen_strong_inline=true
ERROR: Config value cuda is not defined in any .rc file
INFO: Invocation ID: 958bce6e-94dc-4d56-932a-6fcdc505865d
**Provide the exact sequence of commands / steps that you executed before running into the problem**
INFO: Reading rc options for 'build' from d:\code\tensorflow-r1.12\.tf_configure.bazelrc:
build --action_env PYTHON_BIN_PATH="C:/Soft/Anaconda3/python.exe"
build --action_env PYTHON_LIB_PATH="C:/Soft/Anaconda3/lib/site-packages"
build --python_path="C:/Soft/Anaconda3/python.exe"
build --define with_ignite_support=true
build:xla --define with_xla_support=true
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="1"
build --action_env CUDA_TOOLKIT_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0"
build --action_env TF_CUDA_VERSION="10.0"
build --action_env CUDNN_INSTALL_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0"
build --action_env TF_CUDNN_VERSION="7"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="6.0"
build --action_env TF_CUDA_CLANG="0"
build --config=cuda
test --config=cuda
build:opt --copt=/arch:AVX
build:opt --define with_default_optimizations=true
build --config monolithic
build --copt=-w --host_copt=-w
build --verbose_failures
build --distinct_host_configuration=false
build --experimental_shortened_obj_file_path=true
build --define=no_tensorflow_py_deps=true
build --define=override_eigen_strong_inline=true
build:v2 --define=tf_api_version=2

**Comment by ymodak** [comment]
Please take a look at following suggestion which worked for other users.
https://github.com/tensorflow/tensorflow/issues/23401#issuecomment-434681778

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
