### ISSUE TITLE
build from source Windows toolchain for CPU error

### ISSUE THREAD

**Issue by dhamma2050** [tensorflow/tensorflow#24240]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.12
- Python version: 3.6
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source):0.20
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0/7.4.1.5
- GPU model and memory: AMD 2700

Building tensorflow from source I followed this description
https://medium.com/@amsokol.com/how-to-build-and-install-tensorflow-gpu-cpu-for-windows-from-source-code-using-bazel-d047d9342b44

I launch bazel and get the following error 
(tensorflow) C:\Users\Stefan\tensorflow-build\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\users\stefan\tensorflow-build\tensorflow/.bazelrc
c:\users\stefan\tensorflow-build\tensorflow/tools/bazel.rc
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated

INFO: Invocation ID: 1f1e1f31-ec58-4119-9c1d-385bb8e68863
ERROR: cc_toolchain_suite '@local_config_cuda//crosstool:toolchain' does not contain a toolchain for CPU 'x64_windows', you may want to add an entry for 'x64_windows|msvc-cl' into toolchains and toolchain_identifier 'local_windows' into the corresponding cc_toolchain rule (see --incompatible_disable_cc_toolchain_label_from_crosstool_proto).
INFO: Elapsed time: 3.855s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

How can I fix this?

Thanks for helping

**Comment by ymodak** [comment]
TensorFlow officially supports NVIDIA® GPU card with CUDA® Compute Capability 3.5 or higher.
Unfortunately AMD gpu cards are not supported at this time. However you can still use TensorFlow CPU version which we support across various platforms.

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
