### ISSUE TITLE
Initializing saver after variables are initialized and queue runners are started causes inconsistent behaviour.

### ISSUE THREAD

**Issue by jwhpryor** [tensorflow/tensorflow#2425]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:  Mac OsX (El Capitain)

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.8.0

If installed from sources, provide the commit hash:

### Steps to reproduce
1.  Run the CNN example provided by tensorflow using a filename queue
2.  Initialize variable and queue runners
3.  Initialize a saver 

### What have you tried?
1.  Tried running the exact same code with a saver that saves no values and no saver.  Simply initializing the saver at the wrong time is sufficient to cause weird behaviour.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
App will crash intermittently somewhere completely unrelated in code (usually native).

I know this is user error, but it would have been really helpful if an exception had been raised.  I wasted a lot of time trying to hunt down a mystery error when it turned out it was the saver all along.  This can be confusing to beginners such as myself.

**Comment by mrry** [comment]
The solution is to start the queue runners after you have finished building the graph (which includes the saver). Does that work for you?

**Comment by jwhpryor** [comment]
Like I said, I understand this is user error.  I just don't see why this shouldn't be disallowed.  As a beginner it's really confusing to see unrelated crashes and there isn't an easy way to debug native code.  

It's an easy mistake to make and the only feedback is random crashing.

**Comment by mrry** [comment]
We've gone back and forth on disallowing it&mdash;for example, we could call `tf.Graph.finalize()` in the `tf.train.start_queue_runners()` method, but that would break a lot of code that *mostly* works. However, it seems reasonable to log an ominous warning, to discourage this kind of code. At least it should help debugging. I'll prepare a change.
