### ISSUE TITLE
Unicode header for cmake build

### ISSUE THREAD

**Issue by jackyko1991** [tensorflow/tensorflow#24251]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.12
- Python version: N/A
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): cmake
- GCC/Compiler version (if compiling from source): MSVC 2015
- CUDA/cuDNN version:  9.0
- GPU model and memory: N/A

**Describe the problem**
[unicode_ops.cc](https://github.com/tensorflow/tensorflow/commits/d09a4a1cf2ef4fd0cda021ae73f942ae8b32598a/tensorflow/core/kernels/unicode_ops.cc) includes the ICU header, however this only available on  https://www.npcglib.org/~stathis/blog/precompiled-icu/ for a pre-built release, with 7zip format

Can anyone help to add this to cmake contrib?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
We encourage users to use bazel to build TensorFlow from sources for windows users as we no longer support cmake builds unfortunately.

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
