### ISSUE TITLE
Not able to read objets from private s3 bucket

### ISSUE THREAD

**Issue by srihari-humbarwadi** [tensorflow/tensorflow#24253]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10, 7.3
- GPU model and memory: 4x 1080ti 11Gb

**Describe the current behavior**
i am not able to access any data from my private s3  bucket, i just keep getting this error
NotFoundError: Object s3://bla/bla does not exist
i have checked that my local machine has aws credentials in ~/.aws/credentials 
not only that i have also tried setting environment variables
```
os.environ['AWS_REGION'] = <my region>
os.environ['AWS_ACCESS_KEY_ID'] = < my creds > 
os.environ['AWS_SECRET_ACCESS_KEY'] = < my creds > 
```
It still doesnt let me access my data from s3
**Code to reproduce the issue**
```
from tensorflow.python.lib.io import file_io
file_io.stat(s3_image_url)
```
s3_image_url is a valid url for s3 object which i confirmed by downloading it with awscli

**logs**
```
2018-12-09 20:42:26.203155: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2018-12-09 20:42:26.203221: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-09 20:42:27.158491: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 403
2018-12-09 20:42:27.158586: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-09 20:42:27.158702: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2018-12-09 20:42:27.158882: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-09 20:42:27.388300: W tensorflow/core/platform/s3/aws_logging.cc:57] Encountered AWSError
SignatureDoesNotMatch
The request signature we calculated does not match the signature you provided. Check your key and signing method.:
2018-12-09 20:42:27.388399: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
```

**Comment by srihari-humbarwadi** [comment]
@harshini-gadige

**Comment by harshini-gadige** [comment]
@srihari-humbarwadi  Can you please try with CUDA 9 and check

**Comment by srihari-humbarwadi** [comment]
@harshini-gadige its the same on pre-built binaries, i tried the cpu version too

**Comment by skye** [comment]
@jhseu are you familiar with the s3 connector? I wonder if we're not escaping the credentials properly or something.

**Comment by jhseu** [comment]
I haven't personally used it, but @yongtang might have some thoughts. What @srihari-humbarwadi described should work.

**Comment by nagads** [comment]
I face the same issue. Appreciate if any progress on this

**Comment by xxllp** [comment]
need help ~~~

**Comment by vnvo2409** [comment]
@srihari-humbarwadi @nagads @xxllp I am working on this issue. Could you elaborate what is a private s3 bucket ? Is it a bucket like this ?
<img width="616" alt="image" src="https://user-images.githubusercontent.com/17511625/102716343-e628c700-430d-11eb-9ed0-b30b04a1d6bb.png">

**Comment by nagads** [comment]
@vnvo2409 thats correct. thanks

**Comment by vnvo2409** [comment]
@nagads 
Could you check your `~/.aws/config` and `~/.aws/credentials` because it said `SignatureDoesNotMatch
The request signature we calculated does not match the signature you provided. Check your key and signing method.:`

and I don't have any problem reading this bucket from Tensorflow ( 2.4 )

**Comment by nagads** [comment]
@vnvo2409 tested with tf  2.4 , works fine now thanks.
are there any plans for changing env variables to make them more generic. as s3 is no longer confined to AWS cloud and adopted by all public clouds. Thanks.

os.environ['AWS_REGION'] = <my region>
os.environ['AWS_ACCESS_KEY_ID'] = < my creds > 
os.environ['AWS_SECRET_ACCESS_KEY'] = < my creds >

**Comment by vnvo2409** [comment]
> are there any plans for changing env variables to make them more generic.

I think no. In fact, we use `aws-sdk-cpp` as the backend for `s3` filesystem so the envs like `AWS_ACCESS_KEY_ID` are actually passed into `aws-sdk-cpp`.

**Comment by tilakrayal** [comment]
Could you take a look at these [comments](https://github.com/tensorflow/tensorflow/issues/24253#issuecomment-750310009) from the [users](https://github.com/tensorflow/tensorflow/issues/24253#issuecomment-750318399) and please try to upgrade to the latest stable v2.9 and let us know if you are facing the same issue. Thank you!

**Comment by srihari-humbarwadi** [comment]
@tilakrayal  This was an old issue (opened in 2018) on a really old release, it's been fixed - Closing
