### ISSUE TITLE
Right bracket missing in code provided by tensorflow tutorial

### ISSUE THREAD

**Issue by NickyChan** [tensorflow/tensorflow#24254]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

I believe that a right bracket is missing at the end of following code segment
```
plt.xlabel("{} {:2.0f}% ({})".format(class_names[predicted_label],
                                100*np.max(predictions_array),
                                class_names[true_label]),
                                color=color)
```
in part *Prediction*.
And the turtorial link is https://www.tensorflow.org/tutorials/keras/basic_classification
Not a big deal.

**Comment by ymodak** [comment]
I copied the tutorial code in an IDE and I think the code segment has balanced braces.
