### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by PenceMataria** [tensorflow/tensorflow#24258]
**System information**
- OS Platform and Distribution (Linux Ubuntu 16.04):
- TensorFlow installed from (binary):
- TensorFlow version: 1.12.0 (tensorflow-gpu)
- Python version:2.7
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 10
- GPU model and memory: NVIDIA GTX 1060 with Max-Q ; 16 gb DDR4 

**Describe the problem**

executing 
```shell
python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
```
gives the error 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pence/venv/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/pence/venv/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/pence/venv/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/pence/venv/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/pence/venv/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/pence/venv/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by ppwwyyxx** [comment]
1. Latest TensorFlow __supports__ CUDA 8.0-10.0. CuDNN 6-7.
2. Each TensorFlow binary has to work with the version of CUDA and CuDNN it was built with. If they don't match, you have to change either the TensorFlow binary or the Nvidia softwares.
3. Official TensorFlow binaries (the one downloaded by pip or conda) are built with CUDA 9.0, CuDNN 7 since TF 1.5. This means you have to use them with CUDA 9.0, CuDNN 7.
4. If you don't like to change your Nvidia software, you can:
(1) Use non-official binaries built by others. e.g.: https://github.com/mind/wheels/releases, https://github.com/hadim/docker-tensorflow-builder#builds, 
https://github.com/inoryy/tensorflow-optimized-wheels
(2) Build the binaries by yourself from source  with your version of Nvidia software.

**Comment by PenceMataria** [comment]
@ppwwyyxx ; Thanks! building from source did work for me. But I am wondering why isn't still there some version of latest tensorflow which were built with CUDA 10? Technically its like one can't TF 1.12 won't work with CUDA 10 if proceeded via binary install eventhough TF1.12 supports CUDA 10!

**Comment by ppwwyyxx** [comment]
If the binary install is on CUDA 10, other people on CUDA 9 will come out and complain about the same error.
I think in the next version the binary build will be on CUDA 10 by default.

**Comment by harshini-gadige** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=24258)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=24258)
