### ISSUE TITLE
Check failed: is_weights() on creating tensorrt inference graph

### ISSUE THREAD

**Issue by alexander-shustanov** [tensorflow/tensorflow#24268]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): r1.12
- Python version: 3.6.7
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: 10.0, 7.4.1.5
- GPU model and memory: GTX 1050ti, 4000mb

I am trying to create optimized inference graph with tensorflow.contrib.tensorrt.create_inference_graph. But when I call the function, it runs for a while, and than fails. The last line at logs is:

```2018-12-10 22:23:42.564811: F tensorflow/contrib/tensorrt/convert/convert_nodes.cc:421] Check failed: is_weights()```

**Comment by harshini-gadige** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by alexander-shustanov** [comment]
[Download freezed graph](https://drive.google.com/file/d/1C7u3bWGubmb616rpV_CZNFVKOMW9JeAC/view?usp=sharing)

```python
import tensorflow as tf
import tensorflow.contrib.tensorrt as trt
import numpy as np
from tensorflow.python.framework import tensor_util
from tensorflow.core.framework import attr_value_pb2
from tensorflow.core.framework import graph_pb2
from tensorflow.core.framework import node_def_pb2

# loading freezed graph def
with tf.gfile.GFile("freezed", "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

# outputs
out_names = ['filtered_detections/map/TensorArrayStack/TensorArrayGatherV3',
 'filtered_detections/map/TensorArrayStack_1/TensorArrayGatherV3',
 'filtered_detections/map/TensorArrayStack_2/TensorArrayGatherV3']

# here I freeze input image dimensions. Without this trt doesn't do any valuable optimizations
shape_proto = tensor_util.tensor_shape.as_shape([None, 800, 800, 3]).as_proto()
graph_def.node[0].attr['shape'].CopyFrom(attr_value_pb2.AttrValue(shape=shape_proto))

graph = tf.Graph()
with graph.as_default():
    tf.import_graph_def(graph_def, name="")

input_tensor = graph.get_tensor_by_name("input_1:0")
output_tensors = [graph.get_tensor_by_name(out + ":0") for out in out_names]

sess = tf.Session(graph=graph)

# check graph is working
zeros = np.zeros((2, 800, 800,3))
%timeit sess.run(output_tensors, feed_dict={input_tensor: zeros})

# we fail here
fused = trt.create_inference_graph(graph_def, out_names,
                                   max_batch_size=2, 
                                   max_workspace_size_bytes=2 << 30,
                                   minimum_segment_size=10,
                                   precision_mode="FP32")
```

**Comment by alexander-shustanov** [comment]
I figured out, that if not to freeze graph `from tensorflow.python.tools import freeze_graph`, but with `tf.graph_util.convert_variables_to_constants` the exception is not raised, and graph is fused normaly. Therefore,  `tensorflow.python.tools.freeze_graph` spawns some layers, that can be normally processed by `trt.create_inference_graph`.

**Comment by samikama** [comment]
@trevor-m @pooyadavoodi  Can you PTAL

**Comment by samikama** [comment]
@trevor-m @pooyadavoodi, any updates. Should I close this?

**Comment by sushreebarsa** [comment]
@alexander-shustanov TF v1.x is no longer actively supported, so we recommend you to kindly upgrade to latest TF version. Could you refer to this migration [doc ](https://www.tensorflow.org/guide/migrate) to know more on this. Please note that tf.contrib no longer exist in Tensorflow 2.x and it's modules were moved. Thank you!
