### ISSUE TITLE
Pruning： RuntimeError: Run called even after should_stop requested.

### ISSUE THREAD

**Issue by YaoLing13** [tensorflow/tensorflow#24267]
Hello， when i run the code "model_pruning example", I change the parameter "max_steps" equal to 500, there is a bug: "RuntimeError: Run called even after should_stop requested." at "mon_sess.run(mask_update_op)". Can you tell me the reason? Thank you very much!

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
