### ISSUE TITLE
TFLite Image recognization app is getting crashed with model Inception_resnet_V2

### ISSUE THREAD

**Issue by Umapraveen** [tensorflow/tensorflow#24263]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):
- Python version:3.0
- Bazel version (if compiling from source):[bazel release 0.16.1]
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**;
Im using the source code from below repo:https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/android/app
Compiled using the readme in above link
The app works fine without any changes.

Enabled:
setUseNNAPI(true) 
Changed buffer size for float model:
DIM_IMG_SIZE_X = 299;
DIM_IMG_SIZE_Y = 299;
IMAGE_MEAN = 128;
IMAGE_STD = 128.0f;

Downloaded float inception resnet v2 model from: https://www.tensorflow.org/lite/models#other_models
unziped and placed in assests folder of source code: tensorflow/tensorflow/contrib/lite/examples/android/app/src/main/assets
Renamed the model name in ClassifierActivity.java

Compiled the app using bazel
While launching the app it crashed with File not found exception as below
====================================================================
12-10 11:09:02.319 15168 15168 I tensorflow: CameraActivity: Camera API lv2?: true
12-10 11:09:02.324 15168 15168 D tensorflow: CameraActivity: onStart org.tensorflow.demo.ClassifierActivity@ada003c
12-10 11:09:02.324 15168 15168 D tensorflow: CameraActivity: onResume org.tensorflow.demo.ClassifierActivity@ada003c
12-10 11:09:02.359 15168 15168 I tensorflow: CameraConnectionFragment: Desired size: 640x480, min size: 480x480
12-10 11:09:02.359 15168 15168 I tensorflow: CameraConnectionFragment: Valid preview sizes: [640x480, 800x600, 864x480, 960x544, 960x720, 1024x576, 1184x656, 1280x720, 1280x960]
12-10 11:09:02.360 15168 15168 I tensorflow: CameraConnectionFragment: Rejected preview sizes: [160x120, 320x176, 320x240, 432x240, 544x288, 640x360, 752x416, 800x448]
12-10 11:09:02.360 15168 15168 I tensorflow: CameraConnectionFragment: Exact size match found.
12-10 11:09:02.361 15168 15168 E TFLiteImageClassifier: Reading labels from: inception_v3_labels.txt
12-10 11:09:02.366 15168 15168 D AndroidRuntime: Shutting down VM
--------- beginning of crash
12-10 11:09:02.368 15168 15168 E AndroidRuntime: FATAL EXCEPTION: main
12-10 11:09:02.368 15168 15168 E AndroidRuntime: Process: org.tensorflow.lite.demo, PID: 15168
12-10 11:09:02.368 15168 15168 E AndroidRuntime: java.lang.RuntimeException: java.io.FileNotFoundException: inception_resnet_v2.tflite
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at org.tensorflow.demo.TFLiteImageClassifier.create(TFLiteImageClassifier.java:124)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at org.tensorflow.demo.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:105)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at org.tensorflow.demo.CameraActivity$5.onPreviewSizeChosen(CameraActivity.java:362)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at org.tensorflow.demo.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:401)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:408)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:64)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:95)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.TextureView.getTextureLayer(TextureView.java:390)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.TextureView.draw(TextureView.java:339)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19082)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.View.draw(View.java:19935)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19073)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.View.draw(View.java:19935)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.View.draw(View.java:20210)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19082)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.View.draw(View.java:19935)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19073)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.View.draw(View.java:19935)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19073)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.View.draw(View.java:19935)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.View.draw(View.java:20210)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at com.android.internal.policy.DecorView.draw(DecorView.java:780)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19082)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3312)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3116)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2485)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7184)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:696)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: Caused by: java.io.FileNotFoundException: inception_resnet_v2.tflite
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at android.content.res.AssetManager.openFd(AssetManager.java:768)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at org.tensorflow.demo.TFLiteImageClassifier.loadModelFile(TFLiteImageClassifier.java:77)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 	at org.tensorflow.demo.TFLiteImageClassifier.create(TFLiteImageClassifier.java:122)
12-10 11:09:02.368 15168 15168 E AndroidRuntime: 
==========================================================================

**Other info / logs**
The same changes for model; Inception_v3 downloaded from : https://www.tensorflow.org/lite/models#other_models

If I re-name model inception_resnet_v2 to inception_v3 the loads the model and works fine

**Comment by achowdhery** [comment]
The app seems to be not able to link to the model file you are providing with the filename. Please look in to checking why that might be the case: check if you are using the absolute/relative filename.

**Comment by Dayananda-V** [comment]
@Umapraveen 
#24740 resolve simmiliar to this problem, please check and confirm same. Thanks

**Comment by liyunlu0618** [comment]
Closing per last comment.
