### ISSUE TITLE
tf.data equivalent for tf.estimator.inputs.numpy_input_fn

### ISSUE THREAD

**Issue by twolodzko** [tensorflow/tensorflow#24265]
**System information**
- TensorFlow version (you are using): 1.11.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Using `tf.estimator.inputs.numpy_input_fn` in current TensorFlow raises deprecation warnings and suggests using tf.data instead. Unfortunately, tf.data does not have exact replacement. Moreover, [`tf.estimator.inputs.numpy_input_fn` seems to be working out-of-box](https://stackoverflow.com/questions/53677345/passing-2gb-data-to-tf-estimator) for some problems where tf.data raises errors and needs workarounds.

**Will this change the current api? How?**

Provide replacement function in tf.data:
`tf.estimator.inputs.numpy_input_fn` -> `tf.data.numpy_input_fn`

**Who will benefit with this feature?**

Anyone using numpy arrays as input for TensorFlow. Especially for arrays >2GB large. 

**Any Other info.**

None.

**Comment by harshini-gadige** [comment]
@karmel  Is there any equivalent op for the same ? Or can this be considered as a feature request ?

**Comment by nomis-g** [comment]
It would be great to have a replacement since the numpy_input_fn is one way of [avoiding large `event` files](https://github.com/tensorflow/tensorboard/issues/1252) when running tf.estimator.

**Comment by yongtang** [comment]
@twolodzko @sgasse I am experimenting with GRPCDataset which allows you to `pull` numpy array data in batches and provide a `tf.data` to be used: https://github.com/tensorflow/io/pull/206

It does not convert numpy array into tf.constant, could take a look if it is useful.

**Comment by rmothukuru** [comment]
@twolodzko,
Can you please let us know if [this PR](https://github.com/tensorflow/io/pull/206) and [this comment](https://github.com/tensorflow/tensorflow/issues/24265#issuecomment-487303248) has implemented the Feature you are looking for? Thanks!

**Comment by twolodzko** [comment]
@rmothukuru @yongtang sounds like it, but hard to give a more specific comment since the issue was raised in 2018, and also TF has undergone some major changes since then.

**Comment by rmothukuru** [comment]
Closing the issue as it has been resolved. Thanks!
