### ISSUE TITLE
When train a model with Dataset, model.predict() does not work properly

### ISSUE THREAD

**Issue by ChesterWQC** [tensorflow/tensorflow#24276]
**Describe the current behavior**
In Tensorflow's guide about feeding a model with dataset: Input tf.data datasets. The way given by the example to use dataset to train and predict cannot work properly.
Version used: **1.12.0**

**Describe the expected behavior**
model.predict() will return the correct predicted value for the given data.

**Code to reproduce the issue**
```
model = tf.keras.Sequential([
layers.Dense(64, activation='relu'),
layers.Dense(64, activation='relu'),
layers.Dense(10, activation='softmax')])
model.compile(optimizer=tf.train.AdamOptimizer(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])
data = np.random.random((1000, 32)).astype(np.float32)
labels = np.random.random((1000, 10)).astype(np.float32)
dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset = dataset.batch(32)
dataset = dataset.repeat()
model.fit(dataset, epochs=10, steps_per_epoch=30)
result = model.predict(data, batch_size=32)
print(result.shape)
```
**Other info / logs**
Stack trace:

> Traceback (most recent call last):
>   File "xxx.py", line 255, in <module>
>     result = model.predict(data, batch_size=32)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py", line 1864, in predict
>     x, check_steps=True, steps_name='steps', steps=steps)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py", line 992, in _standardize_user_data
>     class_weight, batch_size)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py", line 1117, in _standardize_weights
>     exception_prefix='input')
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_utils.py", line 257, in standardize_input_data
>     'expected no data, but got:', data)
> ValueError: ('Error when checking model input: expected no data, but got:', array([[5.7695776e-01, 2.4554299e-01, 6.4072663e-01, ..., 5.3916293e-01,
>         5.7996696e-01, 1.7735572e-05],
>        [9.4239563e-01, 6.3614279e-01, 5.1306045e-01, ..., 3.2898217e-01,
>         1.9013086e-01, 1.5709637e-01],
>        [9.4871348e-01, 3.7692937e-01, 1.2676715e-02, ..., 2.7022544e-01,
>         7.6909864e-01, 8.5889444e-02],
>        ...,
>        [8.3822417e-01, 9.3324584e-01, 8.0759123e-02, ..., 1.3924435e-01,
>         2.8058958e-01, 3.2993883e-01],
>        [8.9985609e-01, 1.6618696e-01, 2.4748170e-01, ..., 5.6301647e-01,
>         6.0354501e-01, 1.3682739e-01],
>        [2.7904582e-01, 8.5806495e-01, 1.5504396e-01, ..., 3.0398217e-01,
>         4.7553891e-01, 4.4561669e-01]], dtype=float32))

**Comment by yongtang** [comment]
@ChesterWQC I could reproduce the issue with tf 1.12.0, but when I tried with tf-nightly it worked fine.

Could you give tf-nightly a try and see if the issue has been fixed?

**Comment by ChesterWQC** [comment]
@yongtang Thanks for the quick response!
I just tried with tf-nightly build, it did behave differently and seems to be working fine.
I was wondering how soon can we expect this bug to be fixed in official release build?
Thanks.

**Comment by yongtang** [comment]
@ChesterWQC I don't know enough about the release schedule, though I assume the changes will show up in 1.13 (not knowing the date yet).

**Comment by ChesterWQC** [comment]
@yongtang Thanks! Good to know that. I'm closing this issue.

**Comment by harshini-gadige** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=24276)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=24276)
