### ISSUE TITLE
TFLITE for microcontroller installation fails

### ISSUE THREAD

**Issue by clamagdeleine** [tensorflow/tensorflow#24289]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by clamagdeleine** [comment]
**System Information**
OS: Linux Ubuntu 16.04
Tensorflow installed from sources
Tensorflow version: master 
python version: python 3.5
No bazel install needed for building this TFLITE for microcontroller
gcc version: g++_5

**Problem**
When installing the dependencies of tensorflow lite for microcontroller with the following command: 
source tensorflow/lite/experimental/micro/tools/make/download_dependencies.sh as explained in the following doc: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro , within the window of my VM, it started to execute and suddenly the window of the VM crashed and nothing got installed nor build. 

**History of commands**
git clone https://github.com/tensorflow/tensorflow.git
sudo apt-get update
sudo apt-get install g++
cd tensorflow
source tensorflow/lite/experimental/micro/tools/make/download_dependencies.sh.

**Comment by petewarden** [comment]
Unfortunately I wasn't able to reproduce this. Are you still seeing it Corine? I'll close it for now, but let me know more reproduction steps and I can reopen it if it's still happening.
