### ISSUE TITLE
wrong command for cloning tensorflow in TF for microcontroller doc

### ISSUE THREAD

**Issue by clamagdeleine** [tensorflow/tensorflow#24286]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: master
- Doc Link: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro

**Describe the documentation issue**

In "Getting Started" chapter, the command for cloning tensorflos is: 

Download the TensorFlow source with git clone https://github.com/tensorflow

It should be : 

git clone https://github.com/tensorflow/tensorflow.git

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

Yes

**Comment by MarkDaoust** [comment]
Thanks for the report @clamagdeleine, 
I've got a fix inflight.

In the future, feel free to send a PR instead of an issue.
