### ISSUE TITLE
tensorflow.data.dataset and producing a sample weight with tf.py_func: ValueError: Found a sample_weight array with shape (?, 1). 

### ISSUE THREAD

**Issue by dmus** [tensorflow/tensorflow#24288]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
1.12
- Python version:
3.6

**Describe the current behavior**

I have a dataset created with tf.data. In the map function that is called a sample_weight is retrieved from a Python dictionary. Because Tensorflow cannot know the shape of an value return by py_func I set the shape by sample_weight.set_shape(1). However, when calling model.fit() this results in

> ValueError: Found a sample_weight array with shape (?, 1). In order to use timestep-wise sample weights, you should specify sample_weight_mode="temporal" in compile(). If you just mean to use sample-wise weights, make sure your sample_weight array is 1D.

**Describe the expected behavior**

I want a 1D sample_weight

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
def get_sample_weight(team, number):
    # Some code
    return np.array([0.5]).astype(np.float32) #return weight

def preprocess_tfrecord_example(example, sample_weights):
    image = tf.image.decode_png(example['detection/encoded'])
    team = example['detection/team_name']

    sample_weight = tf.py_func(get_sample_weight, [team, example['detection/number']], tf.float32)
    sample_weight.set_shape(1)
    image = tf.image.resize_image_with_pad(image,56,108)

    number = tf.expand_dims(tf.cast(example['detection/number'], tf.float32), -1)
    return image/255., number, sample_weight

```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by dmus** [comment]
I solved it with adding an extra map:

```
def set_shapes(x, y, sample_weights):
            return x, y, tf.reshape(sample_weights, (images_per_batch,))

        dataset = dataset.map(set_shapes)

```

However, I don't think this is the nicest solution. So maybe this is a feature request instead of a bug

**Comment by liuguangyuan** [comment]
![1](https://user-images.githubusercontent.com/7778127/49844537-6999ae80-fdfe-11e8-87f4-506b33ba9cd7.jpg)

**Comment by liuguangyuan** [comment]
![1](https://user-images.githubusercontent.com/7778127/49844580-8635e680-fdfe-11e8-9253-92e10507076e.jpg)
很好的

**Comment by liuguangyuan** [comment]
`[kh
lkjll;kll;k](url)`

**Comment by jsimsa** [comment]
The example is not self-contained and thus not reproducible. Closing the issue as the user was able to solve their problem idiomatically (by using existing tf.data transformations).
