### ISSUE TITLE
GloVe implementation for Tensorflow

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tensorflow#2428]
I think [GloVe](http://nlp.stanford.edu/projects/glove/) can be an useful embedding model for NLP.
The patch would be very similar to the current /models/embedding/word2vec

**Comment by mrry** [comment]
We're moving models over to their own repository. Feel free to contribute this to the https://github.com/tensorflow/models repository (or open an issue over there).

**Comment by mrry** [comment]
As a brief update, I just noticed that someone has published an implementation of this model on GitHub: https://github.com/GradySimon/tensorflow-glove

**Comment by Mistobaan** [comment]
Yes, but is far from being mergeable.
I was thinking to also add a faster implementation with specialized tf ops.

There is also the reference code implemented in C that potentially could be
wrapped in one single op in user space.

What would be the preferred way to be part of the model library?

On Thursday, May 19, 2016, Derek Murray <notifications@github.com> wrote:

> As a brief update, I just noticed that someone has published an
> implementation of this model on GitHub:
> https://github.com/GradySimon/tensorflow-glove
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tensorflow/tensorflow/issues/2428#issuecomment-220445588>
>


-- 
LinkedIn: http://linkedin.com/in/fmilo
Twitter: @fabmilo
Github: http://github.com/Mistobaan/
-----------------------
Simplicity, consistency, and repetition - that's how you get through. (Jack
Welch)
Perfection must be reached by degrees; she requires the slow hand of time
(Voltaire)
The best way to predict the future is to invent it (Alan Kay)
