### ISSUE TITLE
Why the source code of tensorflow 1.12.0 after installation is quite different from the source code in github?

### ISSUE THREAD

**Issue by albert-leiming-du** [tensorflow/tensorflow#24280]
I have installed tensorflow 1.12.0, when I check the source code inside python2.7/site-packages, I found some files are quite different from the code in github?

Specifically, /keras/engine/training.py and /keras/engine/training_utiles.py are different.

May I know what is the problem?

**Comment by wdirons** [comment]
When looking at the code in github, make sure you are looking at the code for the tag 1.12.0, and not the code for the default master branch.

For example here is training_utils.py for the 1.12.0 tag:
https://github.com/tensorflow/tensorflow/blob/v1.12.0/tensorflow/python/keras/engine/training_utils.py#L21-L23

That matches what I see on my system for lines 21 thru 23.


It is different from the code in the master branch under development:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training_utils.py#L21-L23

**Comment by albert-leiming-du** [comment]
Thanks for your reply.
What should I do if i want to use the dev code?
May I just copy the keras module of dev code into the tensorflow path?

**Comment by wdirons** [comment]
If you want to use dev code, you need to use the nightly builds

pip install tf-nightly   or (tf-nightly-gpu)

or use the docker container with the name nightly in it:
https://hub.docker.com/r/tensorflow/tensorflow/tags/

**Comment by albert-leiming-du** [comment]
Well, thanks so much for your help.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if have further follow up questions. Thanks!
