### ISSUE TITLE
Compilation failed when building keras model with CTC on TPU

### ISSUE THREAD

**Issue by ASDen** [tensorflow/tensorflow#24296]
**System information**
- Google Colab with TPU

**Describe the current behavior**
Keras model with CTC on TPU gives error

**Describe the expected behavior**
should work as it does on GPU and CPU backends

**Code to reproduce the issue**
I made a small modification to the MNIST TPU example (https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/keras_mnist.ipynb)
just to test whether TPUs currently support CTC
```
def ctc_batch_cost(args):
    y_pred,y_true = args
    input_length = y_true[:,1:2]+5
    label_length = y_true[:,1:2]+5
    return K.ctc_batch_cost(y_true, y_pred, input_length, label_length)
  
inp = tf.keras.Input(shape=(28*28,))
x = l.Reshape(input_shape=(28*28,), target_shape=(28, 28))(inp)
x = l.Dense(10, activation='softmax')(x)
loss = l.Lambda(ctc_batch_cost, output_shape=(1,), name='ctc')([x, inp ])

model = tf.keras.Model(inputs=[inp], outputs=loss)

model.compile(optimizer='adam', 
              loss={'ctc': lambda y_true, y_pred: y_pred},
              metrics=['accuracy'])
```
unfortunately, while this code works with the GPU backend, for the TPU backend, it gives

> RuntimeError: Compilation failed: Compilation failure: Detected unsupported operations when trying to compile graph cluster_1_6470206916041614137_f15n_1[] on XLA_TPU_JIT: Where (No registered 'Where' OpKernel for XLA_TPU_JIT devices compatible with node {{node tpu_139921521852368/ctc/boolean_mask/Where}} = Where[T=DT_BOOL, _device="/device:TPU_REPLICATED_CORE"](tpu_139921521852368/ctc/boolean_mask/Reshape_1)
> 	.  Registered:  device='CPU'; T in [DT_BOOL]
>   device='CPU'; T in [DT_COMPLEX128]
>   device='CPU'; T in [DT_COMPLEX64]
>   device='CPU'; T in [DT_DOUBLE]
>   device='CPU'; T in [DT_FLOAT]
>   device='CPU'; T in [DT_BFLOAT16]
>   device='CPU'; T in [DT_HALF]
>   device='CPU'; T in [DT_INT8]
>   device='CPU'; T in [DT_UINT8]
>   device='CPU'; T in [DT_INT16]
>   device='CPU'; T in [DT_UINT16]
>   device='CPU'; T in [DT_INT32]
>   device='CPU'; T in [DT_INT64]
> ){{node tpu_139921521852368/ctc/boolean_mask/Where}}

is there any workaround for this ? 
CTC has only a CPU implementation, and the GPU backed offloads it to the CPU, why isn't this also the case for TPUs ?

Thanks,

**Comment by ASDen** [comment]
any thoughts ?

Regards,,

**Comment by greeness** [comment]
Same issue as this: https://github.com/tensorflow/tpu/issues/236
Because` tf.where` is called with both `x` and `y` as "None".

**Comment by puneetjindal** [comment]
@ASDen is it solved?

**Comment by rmothukuru** [comment]
@ASDen,
Can you please refer to [this comment](https://github.com/tensorflow/tpu/issues/236#issuecomment-437128153) where the similar issue has been resolved? Thanks!
