### ISSUE TITLE
gtx 1050ti rog mining problem

### ISSUE THREAD

**Issue by Lukkivan** [tensorflow/tensorflow#24291]
ETH: 1 pool is specified
Main Ethereum pool is eu1-etc.ethermine.org:4444
DCR: 0 pool is specified
No AMD cards in the list.

Driver 368.81 is recommended for best performance and compatibility
Be careful with overclocking, use default clocks for first tests
Press "s" for current statistics, "0".."9" to turn on/off cards
CUDA initializing...

NVIDIA Cards available: 1
CUDA Driver Version/Runtime Version: 9.2/6.5
GPU #0: GeForce GTX 1050 Ti, 4096 MB available, 6 compute units, capability: 6.1

Total cards: 1
ETH: Stratum - connecting to 'eu1-etc.ethermine.org' <172.65.232.146> port 4444
ETH: Stratum - Connected (eu1-etc.ethermine.org:4444)
No pool specified for Decred! Ethereum-only mining mode is enabled
ETH: Authorized
ETHEREUM-ONLY MINING MODE ENABLED (-mode 1)
ETH: eth-proxy stratum mode
Watchdog enabled
Remote management is enabled on port 3333

ETH: Cannot find seed that was received from pool!
Setting epoch failed.
ETH: Cannot find seed that was received from pool!
Setting epoch failed.
ETH: 12/11/18-16:34:38 - New job from eu1-etc.ethermine.org:4444
ETH - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:00
ETH: GPU0 0.000 Mh/s
ETH: 12/11/18-16:34:50 - New job from eu1-etc.ethermine.org:4444
ETH - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:00
ETH: GPU0 0.000 Mh/s
ETH: 12/11/18-16:34:52 - New job from eu1-etc.ethermine.org:4444
ETH - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:00
ETH: GPU0 0.000 Mh/s
GPU0 t=26C fan=100%
WATCHDOG: GPU error, you need to restart miner :(
Restarting OK, exit...

what is this help
pls i dont know

**Comment by Lukkivan** [comment]
what is wrong w the gpu?

**Comment by TimZaman** [comment]
How is this related to TensorFlow exactly?

**Comment by Lukkivan** [comment]
idk but i want this shit egt working so

**Comment by harshini-gadige** [comment]
If this is a tensorflow related issue, request you to fill this template and submit a new issue. If it is a non-tensorflow related, request you to raise in the respective repository.
