### ISSUE TITLE
TypeError: List of Tensors when single Tensor expected when using tf.pack()

### ISSUE THREAD

**Issue by 333caowei** [tensorflow/tensorflow#2429]
I  get a confusion problem. I can run  code well on my computer. But when I copy the code to the cluster and run it. I get the error: ```TypeError: List of Tensors when single Tensor expected.``` on this line ```outputs     =   tf.pack(outputs)```.  The input of pack function should be list. That is so wired. Why? The version of TF on cluster is 0.8.

**Comment by mrry** [comment]
What is the version of TF on your computer? (The nightly build contains additional support for automatically packing nested lists of tensors, which will not work with older versions.)

**Comment by 333caowei** [comment]
@mrry  Hi mrry, the version of TF on my computer is 0.7, it works fine on tf.pack(outputs). But the version 0.8 on cluster can not. Can you tell me what  I can do to solve the problem on cluster please?

**Comment by mrry** [comment]
Can you share what the value of `outputs` is?

**Comment by 333caowei** [comment]
@mrry 
Here is the code:
```
w_x2h   = tf.get_variable("w_x2h", [word_dim, 2*hidden_dim])
b_x2h    = tf.get_variable("b_x2h", [2*hidden_dim])
self.x     = tf.placeholder(tf.float32, [None, sentence_length, word_dim])  
self.real_length  = tf.placeholder(tf.int64, [None])  
self.istate_fw      = tf.placeholder(tf.float32, [None, 2*hidden_dim])
self.istate_bw     = tf.placeholder(tf.float32, [None, 2*hidden_dim])

def RNN(x,  istate_fw, istate_bw,   real_length,  w_x2h, b_x2h):
			x = tf.transpose(x, [1, 0, 2]) 
			x = tf.reshape(x, [-1, word_dim]) # (sentence_length*batch_size, word_dim)
			x = tf.matmul(x, w_x2h) + b_x2h
			
			lstm_fw_cell   = rnn_cell.BasicLSTMCell(hidden_dim, forget_bias=1.0)
			lstm_bw_cell   = rnn_cell.BasicLSTMCell(hidden_dim, forget_bias=1.0)

			x = tf.split(0, sentence_length, x) # sentence_length * (batch_size, hidden_dim)
			outputs = rnn.bidirectional_rnn(lstm_fw_cell, lstm_bw_cell, x, initial_state_fw=istate_fw, initial_state_bw=istate_bw, sequence_length=real_length)

			return outputs

outputs  =  RNN(self.x,  self.istate_fw, self.istate_bw, self.real_length, w_x2h, b_x2h)
```

**Comment by mrry** [comment]
It looks like you are using `rnn.bidirectional_rnn()`. The return type of that function changed from [a single tensor in 0.7](https://github.com/tensorflow/tensorflow/blob/657f1d987aca211e775acbccf719e67864a0be70/tensorflow/python/ops/rnn.py#L323) to [a tuple of three tensors in 0.8](https://github.com/tensorflow/tensorflow/blob/4b7bc3174ed67b4a0eb1803537c9d00f132e9ae7/tensorflow/python/ops/rnn.py#L373).

This explains the type error when using two different versions of TensorFlow.

When running on 0.8, you should probably change the last line of your code snippet to ignore the two new return values as follows:

```python
outputs, _, _ = RNN(self.x, self.istate_fw, self.istate_bw, self.real_length, w_x2h, b_x2h)
```

**Comment by 333caowei** [comment]
@mrry Thank you so much!!!
