### ISSUE TITLE
Wheel for binary installation is outdated; consider automating release process

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [tensorflow/tensorflow#243]
[Installation instructions](http://tensorflow.org/get_started/os_setup.md) suggest
```
pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
```
As far as I can tell, content of this wheel is pre- 6b12d081d54b89869e26d9d99828f13de381761e.

In particular, this means that advanced mnist tutorial from trunk fails when run with this binary installation (even after applying workaround from #226):
```
$ python .../tensorflow/g3doc/tutorials/mnist/fully_connected_feed.py
...
Traceback (most recent call last):
  ...
  File ".../tensorflow/g3doc/tutorials/mnist/mnist.py", line 94, in loss
    indices = tf.expand_dims(tf.range(batch_size), 1)
TypeError: range() takes at least 2 arguments (1 given)
```

**Comment by vrv** [comment]
We're just about there now with jenkins, thankfully.

**Comment by caisq** [comment]
Closed by https://github.com/tensorflow/tensorflow/pull/1255
