### ISSUE TITLE
contrib\cmake: version_info.cc not found

### ISSUE THREAD

**Issue by kvcuong** [tensorflow/tensorflow#24306]
**System information**
- OS Windows 10
- TensorFlow version: lastest on master branch
- Python version: 3.5
- GCC/Compiler version (if compiling from source): Visual-studio 14 2015 win64
- CUDA/cuDNN version: 9.0
- GPU model and memory: 6.1/8Gb

**Describe the problem**

I followed the instruction in contrib/cmake to build tensorflow on windows, in generation step: 

`          Configuring done
          CMake Error at tf_core_framework.cmake:332 (add_library):
          Cannot find source file:

    E:/work_space/projectcpp/tensorflow/tensorflow/tensorflow/core/util/version_info.cc

    Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
           .hpp .hxx .in .txx
          Call Stack (most recent call first):
           CMakeLists.txt:587 (include)
`
It seems like a known-bug but it is still there, please help.
Thank

**Comment by harshini-gadige** [comment]
We encourage you to use Bazel instead of Cmake as we no longer support cmake for Windows.

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by VCBE123** [comment]
version_info.cc

```c++
/*  Generated by gen_git_source.py  */
#include <string>
const char* tf_git_version() {return "b'unknown'";}
const char* tf_compiler_version() {return __VERSION__;}
const int tf_cxx11_abi_flag() {
#ifdef _GLIBCXX_USE_CXX11_ABI
  return _GLIBCXX_USE_CXX11_ABI;
#else
  return 0;
#endif
}
const int tf_monolithic_build() {
#ifdef TENSORFLOW_MONOLITHIC_BUILD
  return 1;
#else
  return 0;
#endif
}

```
