### ISSUE TITLE
Failed to compile a graph using XLA AOT? Executing genrule @org_tensorflow//:gen_graph failed

### ISSUE THREAD

**Issue by chrislitianxin** [tensorflow/tensorflow#24300]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04 LTS
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: tf-nightly  -> b'v1.12.0-rc0-3642-g2ce0bec9da' 1.13.0-dev20181203
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: 0.20.0      libprotoc 3.3.0
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: GTX 1080 Ti - 11GB

### Issue 
I am new to XLA compilation and run into some issue while compiling our model. Any help would be appreciated!  I was trying to use tfcompile to compile a pre-trained [ssd_resnet_50_fpn_coco model](http://download.tensorflow.org/models/object_detection/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz) unsuccessfully. I was running into Error message shown below. 

### Code to reproduce the issue:
The `BUILD` file looks like this
```C
load('@org_tensorflow//tensorflow/compiler/aot:tfcompile.bzl', 'tf_library')

tf_library(
    name = 'graph',
    config = 'graph.config.pbtxt',
    cpp_class = 'Graph',
    graph = 'graph.pb',
)
```
`graph.config.pbtxt` looks like this
```JavaScript
feed {
      id {
        node_name: "image_tensor"
      }
      shape {
        dim {
          size: 1
        }
        dim {
          size: 640
        }
        dim {
          size: 640
        }
        dim {
          size: 3
        }
      }
    }
    fetch {
      id {
        node_name: "detection_boxes"
      }
    }
    fetch {
      id {
        node_name: "detection_scores"
      }
    }
    fetch {
      id {
        node_name: "detection_classes"
      }
    }
    fetch {
      id {
        node_name: "num_detections"
      }
    }
```
Then I run `bazel build --show_progress_rate_limit=600 @org_tensorflow//:graph`

> ERROR: /home/syntech/.cache/bazel/_bazel_syntech/186a880d737f29aade7a2d700e840c56/external/org_tensorflow/BUILD:4:1: Executing genrule @org_tensorflow//:gen_graph failed (Exit 1)
INVALID ARGUMENTS: Merge of two inputs that differ on more than one predicate {s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Greater:0,else), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Greater/_303__cf__306:0,then), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/pred_id/_304__cf__307:0,then)} and {s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Greater:0,else), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Greater/_303__cf__306:0,else), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/pred_id/_304__cf__307:0,else)}
	for node {{node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/Merge}}
 tfcompile performs ahead-of-time compilation of a TensorFlow graph,
resulting in an object file compiled for your target architecture, and a
header file that gives access to the functionality in the object file.
A typical invocation looks like this:
  $ tfcompile --graph=mygraph.pb --config=myfile.pbtxt --cpp_class="mynamespace::MyComputation"
usage: bazel-out/host/bin/external/org_tensorflow/tensorflow/compiler/aot/tfcompile
Flags:
	--graph=""                       	string	Input GraphDef file.  If the file ends in '.pbtxt' it is expected to be in the human-readable proto text format, otherwise it is expected to be in the proto binary format.
	--config=""                      	string	Input file containing Config proto.  If the file ends in '.pbtxt' it is expected to be in the human-readable proto text format, otherwise it is expected to be in the proto binary format.
	... ( I have omitted some of the irrelevant output here) 
        ...
        ...
Target @org_tensorflow//:graph failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1373.473s, Critical Path: 57.61s
INFO: 3686 processes: 3686 local.
FAILED: Build did NOT complete successfully

Running with `--verbose_failures` gives 
>INFO: Invocation ID: 7d6f9793-2517-4ea7-afab-faf4fa30eaf9
INFO: Analysed target @org_tensorflow//:graph (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/syntech/.cache/bazel/_bazel_syntech/186a880d737f29aade7a2d700e840c56/external/org_tensorflow/BUILD:4:1: Executing genrule @org_tensorflow//:gen_graph failed (Exit 1): bash failed: error executing command
  (cd /home/syntech/.cache/bazel/_bazel_syntech/186a880d737f29aade7a2d700e840c56/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:/usr/local/cuda-9.0/extras/CUPTI/lib64:/home/syntech/TensorRT-4.0.1.6/lib/ \
    PATH=/home/syntech/tx_dev/venv/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/syntech/bin \
    PYTHON_BIN_PATH=/home/syntech/tx_dev/venv/bin/python \
    PYTHON_LIB_PATH=/home/syntech/tx_dev/venv/lib/python3.5/site-packages \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; CUDA_VISIBLE_DEVICES='\'''\'' bazel-out/host/bin/external/org_tensorflow/tensorflow/compiler/aot/tfcompile --graph=external/org_tensorflow/models/frozen_inference_graph.pb --config=external/org_tensorflow/ssdresnet.config.pbtxt --entry_point=____graph --cpp_class=Model --target_triple=x86_64-pc-linux --out_header=bazel-out/k8-opt/genfiles/external/org_tensorflow/graph.h --out_metadata_object=bazel-out/k8-opt/genfiles/external/org_tensorflow/graph_tfcompile_metadata.o --out_function_object=bazel-out/k8-opt/genfiles/external/org_tensorflow/graph_tfcompile_function.o  ')
Execution platform: @bazel_tools//platforms:host_platform
INVALID ARGUMENTS: Merge of two inputs that differ on more than one predicate {s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Greater:0,else), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Greater/_303__cf__306:0,then), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/pred_id/_304__cf__307:0,then)} and {s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Greater:0,else), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Greater/_303__cf__306:0,else), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/pred_id/_304__cf__307:0,else)}
	for node {{node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/Merge}}

And when I try to compile our own customized SSD-ResNet (with additional preprocessing operation to decode an encoded image string).  The following error occur:
>INFO: Invocation ID: 63eccf9a-fa37-427f-ac89-e746f28c80b5
INFO: Analysed target @org_tensorflow//:graph (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/syntech/.cache/bazel/_bazel_syntech/186a880d737f29aade7a2d700e840c56/external/org_tensorflow/BUILD:4:1: Executing genrule @org_tensorflow//:gen_graph failed (Exit 1)
2018-12-07 15:25:48.709118: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INVALID ARGUMENTS: Detected unsupported operations when trying to compile graph tfcompile on XLA_CPU_JIT: Shape (No registered 'Shape' OpKernel for XLA_CPU_JIT devices compatible with node {{node map/Shape}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_STRING, out_type=DT_INT32
	.  Registered:  device='XLA_CPU_JIT'; out_type in [DT_INT32, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, DT_COMPLEX64, DT_INT64, DT_BOOL, DT_QINT8, DT_QUINT8, DT_QINT32, DT_HALF, DT_UINT32, DT_UINT64]
){{node map/Shape}}

**Comment by chrislitianxin** [comment]
I tried using Graph Transformation Tool to strip the unused/training nodes and fused operations but run into new issues with unsupported operations such as `tf.where()`.  Are there any plans on supporting those in the near future? and are there any work arounds? Thank you!

**Comment by jlebar** [comment]
wrt `tf.where()`, see https://medium.com/tensorflow/pushing-the-limits-of-gpu-performance-with-xla-53559db8e473  We are actively working on making it possible to use this op, but it's a very big change, and at the moment there's really no workaround other than rewriting your model not to use `tf.where`.

I'm going to close this because I'm not sure there's much that we can do immediately, but if you have other questions feel free to ask, I'm not trying to end the conversation or anything.

cc @sanjoy
