### ISSUE TITLE
some bug in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android

### ISSUE THREAD

**Issue by shenyingying** [tensorflow/tensorflow#24307]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): liunx ubuntun 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: huawei mate 9
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):1.12.0
- Python version:3.6
- Bazel version (if compiling from source):no
- GCC/Compiler version (if compiling from source):6
- CUDA/cuDNN version:9.0
- GPU model and memory:2080

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
 I need to transplant my net to mobilephone, first i run the demo in office,it works well,when i change the DetectiorMode to YOLO or MULTIBOX which provide in office code it didn't works
**Describe the current behavior** 
when i change the mode to MULTIBOX there is no predictions
when i change the mode to YOLO, the app is  crash
I wonder if there is no implement in source code,
wondering for you replay
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by shenyingying** [comment]
> @shenyingying : I tried today and didn't see any crash on my Pixel2 .
> Can you include the adb logcat for the crash, also if possible your modifications to the code.

@shashishekhar  hi ,what yolo version you tried,in my application,the yolov2-tiny is ok,the yolov3-tiny isn't work,have you find this issue?

**Comment by shashishekhar** [comment]
@shenyingying : Can you attach the model to the bug or the log for the crash, will be easier to debug.

**Comment by shenyingying** [comment]
@shashishekhar HI guys
`2019-01-03 11:09:26.049 18193-18561/org.tensorflow.demo E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[input], outputs:[output]
    
    --------- beginning of crash
2019-01-03 11:09:26.055 18193-18561/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.demo, PID: 18193
    java.lang.IllegalArgumentException: ConcatOp : Dimensions of inputs should match: shape[0] = [1,1,1,256] vs. shape[13] = [0,1,1,256]
    	 [[{{node concat_13}} = ConcatV2[N=19, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Reshape_228, Reshape_229, Reshape_230, Reshape_231, Reshape_232, Reshape_233, Reshape_234, Reshape_235, Reshape_236, Reshape_237, Reshape_238, Reshape_239, Reshape_240, Reshape_241, Reshape_242, Reshape_243, Reshape_244, Reshape_245, Reshape_246, concat_13/axis)]]
        at org.tensorflow.Session.run(Native Method)
        at org.tensorflow.Session.access$100(Session.java:48)
        at org.tensorflow.Session$Runner.runHelper(Session.java:314)
        at org.tensorflow.Session$Runner.run(Session.java:264)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:228)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:197)
        at org.tensorflow.demo.TensorFlowYoloDetector.recognizeImage(TensorFlowYoloDetector.java:173)
        at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:292)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-01-03 11:09:26.080 701-2668/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.`
this use yolov2.pb not yolov2-tiny throw this exception,can you solve it，ths a lot

**Comment by shenyingying** [comment]
@shashishekhar  there is another question , i can't convert yolov3-tiny.weight to yolov3-tiny.pb in CPU mode ,can you ever try it.

**Comment by shashishekhar** [comment]
@shenyingying : This looks like you are using TensorflowMobile instead of TfLite. From the error it looks like the Concat in your graph is receiving one input with dims [1,1,1,256] and another as [0,1,1,256] which is causing the error.

Can you provide the model and code you are using, I suspect it is an error in feeding inputs. 

For the second question can you attach: yolov3-tiny.weight to the bug.

**Comment by shashishekhar** [comment]
@shenyingying : Please reopen if you are still encountering this issue.
