### ISSUE TITLE
Documentation describes Python 3 Anaconda installation but no support for current Anaconda Python 3 (i.e. Python 3.5)

### ISSUE THREAD

**Issue by hack-r** [tensorflow/tensorflow#2430]
Anaconda uses Python 3.5 as its version of Python 3.

If you follow the [instructions ](https://storage.googleapis.com/tensorflow/linux/cpu/)to install Tensorflow via Anaconda you'll fail with the error 

> not a supported wheel on this platform

presumably because the wheel is made for Python 3.4 instead of 3.5

**Comment by hholst80** [comment]
Workaround is to build from source or rename the wheel file.

**Comment by hack-r** [comment]
Renaming the wheel file with py3-none in place of the version information worked for me.

**Comment by caisq** [comment]
With PR #2585, we now have Linux Python 3.5 whl files built and tested nightly. The links to the whl files and build history can be found in the main README.md: 
https://github.com/tensorflow/tensorflow/

Linux Python 3.5 whl files will also be included in future releases.
