### ISSUE TITLE
Better support for breaking up too-large operations

### ISSUE THREAD

**Issue by orome** [tensorflow/tensorflow#2431]
Unless I'm missing something, the ability to automatically break up calculations that don't fit on a device does not seem to be part of the TensorFlow API. This surprises me since one of the very first things users (at least naive ones like me) encounter in readily accessible GPU machines (e.g. AWS EC2 instances) are memory crashes on GPUs. 

To avoid these errors users have to either give up on GPUs for large parts of their calculations (again, unless I'm missing something) or hand code some form of batching to avoid the crashes (if they can figure out where they're happening, which isn't always easy with such errors).

Shouldn't TensorFlow do this automatically "under the hood", breaking up too-large calculations and merging them, to avoid code like that below?

---

_From a [related question](http://stackoverflow.com/q/37327312/656912) asked on SO:_

I'm puzzled about how to efficiently assign my TensorFlow operations and variables to devices. It's clear that, at least for my implementation of a basic convolutional neural network, placing as many operations as possible on a GPU is desirable. But the GPU I currently have access to has limited memory and results in many warnings of the form

> `Ran out of memory trying to allocate 2.60GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.`

and occasional crashes for certain specific operations, like

> ```
> Ran out of memory trying to allocate 83.74MiB.  See logs for memory state.
> Resource exhausted: OOM when allocating tensor with shape[28000,1,28,28]
> ```

These can be avoided by placing variables on CPUs, but in my implementation, this results in training epochs taking 10 times as long to compute. 

Clearly the ideal policy is to identify specific chunks of code that generate errors, and attempt to place only those on CPUs. But it is unclear to me how to do this, because those calculations can't be isolated from others that require GPU placement to achieve efficiencies.

For example, simply generating predictions on a test set with something like

```
evals = sess.run(tf.argmax(y, 1), feed_dict={x: use_x_all})
```

where `x` is a `tf.placeholder` of inputs to my model, and `y` are the output activations of my network, produces the above error when `use_x_all` is a large array (here with `28000` examples). Attempting to put this calculation alone on a CPU fails, presumably because the network evaluation producing `y` is on the GPU.

Because of this I (seem to) need to resort to approaches like

```
use_x_all, _ = data_loader.stack_data(use_data, as_cols=False)
use_x_split = np.split(use_x_all, splits)
for use_x in use_x_split:
    # ...
    evals_part = sess.run(tf.argmax(y, 1), feed_dict={x: use_x})
    # accumulate evals
```

which clearly doesn't scale.

Is there a better way? Specifically:
- Is there a way to place calculations like the one above on a CPU and still have those calculations for the same graph (e.g. training) run on a GPU?

or, alternatively
- Is there an idiom (like batching) that can be more easily applied in such situations to reduce the memory demands of such calculations?

**Comment by mrry** [comment]
Why does your `np.split(...)` approach not scale? This is an easy way to proceed if your dataset fits in host memory. For larger datasets, you can use the standard reader pipeline to read batches of input at a time: e.g. see the `batch_inputs()` function in the [Inception model](https://github.com/tensorflow/models/blob/dc7791d01c9a6b1fcc40e9e2c1ca107cbd982027/inception/inception/image_processing.py#L407). You could also try [`tf.train.batch()` and related functions](https://www.tensorflow.org/versions/r0.8/api_docs/python/io_ops.html#batching-at-the-end-of-an-input-pipeline) to control how the inputs are batched.

As to why TensorFlow doesn't do this automatically, there are clearly [lots of different ways to do batching](https://www.tensorflow.org/versions/r0.8/api_docs/python/io_ops.html#batching-at-the-end-of-an-input-pipeline), and TensorFlow can't reliably infer the user's intent. Therefore, we provide higher level libraries to allow users to build the appropriate input pipelines.

**Comment by orome** [comment]
@mrry — At least in this context, it's not an issue of the many ways to do batching, but a simple matter of  sequencing: doing something in parts rather than all at once (as in the hand-coded version). What doesn't scale is that I need to ferret out every place where this happens, and write code like I did above.

But I see the problem: its not easily generalized, as you say. The data might need shuffling, there could be various ways to combine the results, and not all of it may fit in memory at once, etc.

So I guess as long as I'm "doing it right", I'm not worried; and the question boils down to that: Is it idiomatic to be manually breaking up and reassembling data fed to TF operations as needed when they result in calculations that are too big for the hardware?

**Comment by orome** [comment]
@mrry — If I've got that right, it would be extremely helpful to see how I might rewrite the full code example in [my SO question](http://stackoverflow.com/q/37327312/656912) to take advantage of some of the related TF API (e.g., `train.batch` and `batch_join`, perhaps).

**Comment by sjperkins** [comment]
@orome I've written a tool called [hypercube](https://github.com/ska-sa/hypercube) to reason about problem sizes and memory requirements that you may find useful.

**Comment by girving** [comment]
This is mostly questions and requests for help rather than an issue, so I'm going to close to keep the issue tracker focused.

**Comment by orome** [comment]
@girving: More of a feature request. What's the home for those?

**Comment by girving** [comment]
@orome: Unfortunately I think the feature request to have TensorFlow automatically shard ops is too broad to leave as a Github issue.

**Comment by orome** [comment]
@girving: Not saying it should be here; but wondering where the home for general discussion of features requests is (where they can evolve to more specific issues).

**Comment by girving** [comment]
discuss@tensorflow.org is one option, but on second thought leaving this as an issue is fine.

**Comment by orome** [comment]
@girving: It's certainly within the scope of what's spelled out in the issue submission template.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Hoeze** [comment]
Hey, I'd like to calculate a matrix multiplication with samples which do not fit into memory.
Now I thought about batching the samples and sum up the results.

In OpenMP this would be a simple omp parallel reduction.
In Tensorflow, it is a rather big bunch of code to write a dedicated input pipeline, create a while loop, assign-adding the values, ...
Also, the user has to decide how big the batches are allowed to be.

Have there been any updates on simplifying this?
I'd love something like a map-reduce option which would automatically decide which batch size it can use.
