### ISSUE TITLE
Build Tensorflow / Tensorflow Lite for Linux on ARM 64 bit

### ISSUE THREAD

**Issue by dimitryn** [tensorflow/tensorflow#24317]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 16
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
Sources
- TensorFlow version:
- Python version:
2.7
- Installed using virtualenv? pip? conda?:
No
- Bazel version (if compiling from source):
15.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Hi , I am looking for a way to BUILD   Tensorflow/Tensorflow  Lite shared c++ library to run on ARM 64 bit with Ubuntu OS.
Thanks.

**Comment by harshini-gadige** [comment]
Please find instructions in [this](https://developer.codeplay.com/computecppce/latest/tensorflow-arm-setup-guide) link which help you to build Tensorflow on ARM.
