### ISSUE TITLE
[tf.keras.layers.LSTM] reset_state performance issue

### ISSUE THREAD

**Issue by eega** [tensorflow/tensorflow#24319]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): modified `tensorflow/python/keras/layers/recurrent.py` to get timings of LSTM reset (see code change below)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): 1.12.0, binary from PyPi
- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 3.6.7
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Time required to execute `tensorflow.keras.Model` `reset_states()` increases non-linearly with the number of stateful `tensorflow.keras.layers.LSTM` units, but only the first time `reset_states()` is called. The second time `reset_states()` it basically doesn't take any time at all.
A few numbers to highlight this - all numbers refer to the reset of a single LSTM (one model layer), not the whole model:
- 2 LSTMs: reset of the first LSTM takes ~20ms and of the last takes ~30ms (could be just a random variation)
- 20 LSTMs: reset of the first LSTM takes ~300ms and of the last ~700ms
- 200 LSTMs: reset of the first LSTM takes ~3500ms and of the last ~7000ms
I traced the delay down to `tensorflow.keras.backend.set_value`, so it obviously is really setting of the state that takes extremely long.

**Describe the expected behavior**
I would expect that the reset of a single LSTM (one model layer) stays constant independent of the number of LSTMs the model consists of. More importantly, I would expect that the time it takes to reset a single LSTM doesn't increase, but is constant for all of the LSTMs of a model..

**Code to reproduce the issue**
Import module `datetime` in `tensorflow/python/keras/layers/recurrent.py` and replace method of `reset_states` of class `RNN` by
```
  def reset_states(self, states=None):
    import datetime
    if not self.stateful:
      raise AttributeError('Layer must be stateful.')
    batch_size = self.input_spec[0].shape[0]
    if not batch_size:
      raise ValueError('If a RNN is stateful, it needs to know '
                       'its batch size. Specify the batch size '
                       'of your input tensors: \n'
                       '- If using a Sequential model, '
                       'specify the batch size by passing '
                       'a `batch_input_shape` '
                       'argument to your first layer.\n'
                       '- If using the functional API, specify '
                       'the batch size by passing a '
                       '`batch_shape` argument to your Input layer.')
    # initialize state if None
    if self.states[0] is None:
      if _is_multiple_state(self.cell.state_size):
        self.states = [
            K.zeros([batch_size] + tensor_shape.as_shape(dim).as_list())
            for dim in self.cell.state_size
        ]
      else:
        self.states = [
            K.zeros([batch_size] +
                    tensor_shape.as_shape(self.cell.state_size).as_list())
        ]
    elif states is None:
      if _is_multiple_state(self.cell.state_size):
        now = datetime.datetime.now()
        for state, dim in zip(self.states, self.cell.state_size):
          K.set_value(state,
                      np.zeros([batch_size] +
                               tensor_shape.as_shape(dim).as_list()))
        print(f"LSTM reset time: {datetime.datetime.now() - now}")  # TODO
      else:
        K.set_value(self.states[0], np.zeros(
            [batch_size] +
            tensor_shape.as_shape(self.cell.state_size).as_list()))
    else:
      if not isinstance(states, (list, tuple)):
        states = [states]
      if len(states) != len(self.states):
        raise ValueError('Layer ' + self.name + ' expects ' +
                         str(len(self.states)) + ' states, '
                         'but it received ' + str(len(states)) +
                         ' state values. Input received: ' + str(states))
      for index, (value, state) in enumerate(zip(states, self.states)):
        if _is_multiple_state(self.cell.state_size):
          dim = self.cell.state_size[index]
        else:
          dim = self.cell.state_size
        if value.shape != tuple([batch_size] +
                                tensor_shape.as_shape(dim).as_list()):
          raise ValueError(
              'State ' + str(index) + ' is incompatible with layer ' +
              self.name + ': expected shape=' + str(
                  (batch_size, dim)) + ', found shape=' + str(value.shape))
        # TODO(fchollet): consider batch calls to `set_value`.
        K.set_value(state, value)
```

Then set `COUNT_LSTMS` to the number of LSTMs that should be used in the following script and execute it:
```
import tensorflow as tf
import numpy as np

COUNT_LSTMS = 200

BATCH_SIZE = 100
UNITS_INPUT_OUTPUT = 5
UNITS_LSTMS = 20
BATCHES_TO_GENERATE = 2
SEQUENCE_LENGTH = 20

# build model
my_input = tf.keras.layers.Input(batch_shape=(BATCH_SIZE,
                                              None,
                                              UNITS_INPUT_OUTPUT))
my_lstm_layers = [tf.keras.layers.LSTM(units=UNITS_LSTMS,
                                       stateful=True,
                                       return_sequences=True)(my_input)
                  for _ in range(COUNT_LSTMS)]
my_output_layer = tf.keras.layers.Dense(UNITS_INPUT_OUTPUT)
my_output = tf.keras.layers.TimeDistributed(my_output_layer)(
    tf.keras.layers.concatenate(my_lstm_layers, axis=-1))
my_model = tf.keras.Model(my_input, my_output)


# generation
pred_input = np.random.randn(BATCH_SIZE, 1, UNITS_INPUT_OUTPUT)

for batch in range(BATCHES_TO_GENERATE):
    print('resetting states')
    my_model.reset_states()
    print(f"start generation of batch {batch}")
    for _ in range(SEQUENCE_LENGTH):
        pred_input = my_model.predict(pred_input, batch_size=BATCH_SIZE)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by rmothukuru** [comment]
@eega,
Sorry for the delayed response. Can you please confirm if the problem still persists? Thanks!

**Comment by tgamauf** [comment]
Sorry, no, I'm not in the position anymore to verify that issue.
