### ISSUE TITLE
with tf.device('/cpu:0') is ignored when using MirroredStrategy

### ISSUE THREAD

**Issue by etragas-fathom** [tensorflow/tensorflow#24326]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
    Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
    Ubuntu 16.04
- TensorFlow installed from (source or binary):
    pip / binary
- TensorFlow version (use command below):
    tf-nightly-gpu==1.13.0.dev20181022
- Python version:
   3.6
- Bazel version (if compiling from source):
    N/A
- GCC/Compiler version (if compiling from source):
    N/A
- CUDA/cuDNN version:
   7.2.1.38
- GPU model and memory:
    8x v100 (16 gb per)

**Describe the current behavior**
If I call with tf.device while my distribution strategy is set to **MirroredStrategy** then my embeddings are forced onto gpu.
```
...
with tf.device('/cpu:0'):
    with tf.variable_scope("testvar"):
        embeddings = tf.get_variable(
            name='weights',
            shape=[10, 5],
            trainable=True)
print(embeddings)
...
```
>>>
MirroredVariable:{'/replica:0/task:0/device:**GPU**:0': <tf.Variable 'fh_universal_transformer_encoder/word_symbol_modality_1917597_300/input_emb/embeddings/weights:0' shape=(1917597, 300)

**Describe the expected behavior**
```
...
with tf.device('/cpu:0'):
    with tf.variable_scope("testvar"):
        embeddings = tf.get_variable(
            name='weights',
            shape=[10, 5],
            trainable=True)
print(embeddings)
...
```
>>>
MirroredVariable:{'/replica:0/task:0/device:**CPU**:0': <tf.Variable 'fh_universal_transformer_encoder/word_symbol_modality_1917597_300/input_emb/embeddings/weights:0' shape=(1917597, 300)

**Comment by harshini-gadige** [comment]
@etragas-fathom  
 to remove GPU from consideration completely, run export 
CUDA_VISIBLE_DEVICES=

  config = tf.ConfigProto(log_device_placement=True)
  config.gpu_options.per_process_gpu_memory_fraction=0.3 # don't hog all vRAM
  config.operation_timeout_in_ms=50000   # terminate on long hangs
  sess = tf.InteractiveSession("", config=config)

**Comment by etragas-fathom** [comment]
Hey @harshini-gadige I appreciate the response. However, my goal isn't to put all my variables on CPU, but instead have a mix of variables on gpu and cpu while using MirroredStrategy. Is that supported by MirrorStrategy?

**Comment by harshini-gadige** [comment]
@josh11b  Any inputs on this ?

**Comment by josh11b** [comment]
MirroredStrategy controls variable placement when you use it, and there is no currently supported API for overriding this. It might work to use strategy.extended.colocate_vars_with(...) to override var placement, but this is not a current API promise.

**Comment by etragas-fathom** [comment]
Thank you @josh11b for clarifying things and @yuefengz for picking up the embedding support. Looking forward to the solution!

**Comment by yuefengz** [comment]
We have a [RFC for embeddings](https://github.com/yuefengz/community/blob/master/rfcs/20190116-embedding-partitioned-variable.md) and will start the implementation soon. So closing this issue.

**Comment by feiga** [comment]
Hi, @yuefengz 
I checked your document and latest code. I'm trying to implement a distributed trainer using MirroredStrategy, which replicates network in each devices. But I would like to force the embedding layers in CPU since it's too big to store in device memory in my task.  Is this supported now?

**Comment by feiga** [comment]
@yuefengz Any comments?
