### ISSUE TITLE
Missing Docker Images referenced in Documentation

### ISSUE THREAD

**Issue by WriteCodeEveryday** [tensorflow/tensorflow#24329]
**System information**
- TensorFlow version: Docker version
- Doc Link: https://www.tensorflow.org/install/docker

**Describe the documentation issue**
In the install with Docker documentation, there are examples of how to pull images by adding multiple parameters together, there is am implicit reference to latest-gpu-jupyter. On [docker-hub](https://hub.docker.com/r/tensorflow/tensorflow/tags/), it appears that tag is no longer valid or is no longer being built. This can cause a confusing error relating to a missing manifest when trying to pull that image.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
Of course, I just need to know if this is a permanent deprecation of latest-gpu-py3-jupyter and latest-gpu-jupyter, or if it's just a mistake, the nightly builds do contain those tags (nightly-gpu-py3-jupyter) for example

**Comment by rudra-ak** [comment]
I am going through this exact issue. I am docker & tf newbie and was looking forward to the docker image to just work. However, latest-*-jupyter does not show up, neither does docker hub shows that. How is one suppose to get this image? Is that image discontinued? If so could someone please update the documentation?

**Comment by rudra-ak** [comment]
The default installation [page](https://www.tensorflow.org/install/) however seems to say that one can get to Jupyter notebooks with normal installation as well `docker run -it -p 8888:8888 tensorflow/tensorflow  # Start a Jupyter notebook server.` I am guessing the notebooks have become default on all images and which would make the need for tag with latest label / tag unnecessary. But the documentation still needs to be consistent so as to not confuse the newbies like me.

**Comment by yashk2810** [comment]
This has been fixed. The tag for jupyter notebook is: `docker pull tensorflow/tensorflow:latest-gpu-jupyter`.

Please reopen if you hit an error.
