### ISSUE TITLE
undefined symbol: _ZN6tflite12tensor_utils27NeonSymmetricQuantizeFloatsEPKfiPaPfS4_S4_\n

### ISSUE THREAD

**Issue by akotlarsky** [tensorflow/tensorflow#24323]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspberry Pi 3B+ Linux
- TensorFlow installed from (source or binary): installed in Python using pip3
- TensorFlow version (use command below):  1.11.0
- Python version: 3.5.3

**Describe the current behavior**
Trying to convert a frozen graph file (.pb) to a TensorFlow Lite FlatBuffer file (.tflite),  Executing this command from the Linux command line:
cd ~/.local/bin
./tflite_convert --output_file=/home/pi/sols/demo/src/image_classification/network/fruit_models/fruit_model.tflite --graph_def_file=/home/pi/sols/demo/src/image_classification/network/fruit_models/frozen_graph.pb --input_arrays=X --output_arrays=softmax

It gives me this error:
RuntimeError: TOCO failed see console for info.
b'/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module \'tensorflow.python.framework.fast_tensor_util\' does not match runtime version 3.5\n  return f(*args, **kwds)\n/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412\n  return f(*args, **kwds)\nTraceback (most recent call last):\n  File "/bin/toco_from_protos", line 7, in <module>\n    from tensorflow.contrib.lite.toco.python.toco_from_protos import main\n  File "/home/pi/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/toco/python/toco_from_protos.py", line 22, in <module>\n    from tensorflow.contrib.lite.toco.python import tensorflow_wrap_toco\n  File "/home/pi/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/toco/python/tensorflow_wrap_toco.py", line 28, in <module>\n    _tensorflow_wrap_toco = swig_import_helper()\n  File "/home/pi/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/toco/python/tensorflow_wrap_toco.py", line 24, in swig_import_helper\n    _mod = imp.load_module(\'_tensorflow_wrap_toco\', fp, pathname, description)\n  File "/usr/lib/python3.5/imp.py", line 242, in load_module\n    return load_dynamic(name, filename, file)\n  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic\n    return _load(spec)\nImportError: /home/pi/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/toco/python/_tensorflow_wrap_toco.so: undefined symbol: _ZN6tflite12tensor_utils27NeonSymmetricQuantizeFloatsEPKfiPaPfS4_S4_\n'

Please help!

**Comment by ymodak** [comment]
Can use the latest tf-nightly build and test again? Thanks!

**Comment by akotlarsky** [comment]
How to install tf-nightly?  

When I try to install, here is what I am getting:

pi@raspberrypi:~ $ pip3 install --user --upgrade tf-nightly
Collecting tf-nightly
  Could not find a version that satisfies the requirement tf-nightly (from versions: )
No matching distribution found for tf-nightly

Any idea?

**Comment by ymodak** [comment]
You can try setting virtual env and test :
virtualenv -p python3 venv-tf-nightly
source venv-tf-nightly/bin/activate
pip3 install tf-nightly

**Comment by akotlarsky** [comment]
Is there a tf-nightly wheel file (.whl) that I could just download and install in my Raspberry Pi?

**Comment by akotlarsky** [comment]
Installing tf-nightly in virtual environment in Raspberry Pi (as you suggested) fails as well:  

(py_env) pi@raspberrypi: $ pip3 install tf-nightly
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting tf-nightly
  Could not find a version that satisfies the requirement tf-nightly (from versions: )
No matching distribution found for tf-nightly

**Comment by akotlarsky** [comment]
Does anybody have any idea about the possible reasons for the undefined symbol error _ZN6tflite12tensor_utils27NeonSymmetricQuantizeFloatsEPKfiPaPfS4_S4_?

**Comment by freedomtan** [comment]
@akotlarsky probably the same problem as #21574. That is, NEON stuff was not linked in.

**Comment by petewarden** [comment]
Since the related #21574 has been closed, closing this one as well. Please reopen if you're still hitting this problem.
