### ISSUE TITLE
Feature needed: configuration file

### ISSUE THREAD

**Issue by thuzhf** [tensorflow/tensorflow#2433]
Is there any configuration file which can be used to configure the default behavior such as which gpu device to use and so on? Just like the .theanorc file in package Theano? If there isn't, I hope some one can add this feature in the future code.

**Comment by mrry** [comment]
This sounds like an potentially useful feature, but it won't be trivial to develop a good version of this. Assigning to @martinwicke for prioritization.

**Comment by martinwicke** [comment]
This does look like a useful feature. There are a number of such configuration options exposed as Environment variables, with appropriate refactoring it would be straightforward to expose them as "check environment, if not set, read from config file, if not found, apply default" in a uniform manner.

**Comment by martinwicke** [comment]
That said, this is not going to be worked on right now, if someone wants to pick it up, I'd be delighted to get a PR.

**Comment by thuzhf** [comment]
@martinwicke I can't find any documents which explain which Environment variables can be set to what in TF, can you please show me a link to some related documents or just give me a heuristic example?

**Comment by martinwicke** [comment]
There are a bunch. The best (and maybe only) way to find out is to grep for `getenv`. I know this is a sad answer.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
