### ISSUE TITLE
TOCO cannot identify dilated convolution correctly

### ISSUE THREAD

**Issue by pinzhenx** [tensorflow/tensorflow#24337]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): N/A
- Python version: N/A
- Bazel version (if compiling from source): 0.19.1
- GCC/Compiler version (if compiling from source): gcc 7.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

In this line of [comment](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/toco/graph_transformations/identify_dilated_conv.cc#L116), it said the `Bias op is required before or after BatchToSpace`. However, in the DeepLab model ([mobilenetv2_coco_voc_trainval](http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_trainval_2018_01_29.tar.gz)), there isn't any BiasAdd around the `BatchToSpace`. So the TOCO will fail to combine a sequence of `SpaceToBatchND` - `(Depthwise)Conv2D` - `BatchToSpaceND` into dilated convolution. Instead, the `SpaceToBatchND` and `BatchToSpaceND` will still remain in the graph.

**Comment by liyunlu0618** [comment]
Is this still an issue with the most recent tf release?

**Comment by ghop02** [comment]
Hi, just want to second this issue:
```
inpt = tf.keras.layers.Input(shape=(257, 257, 3))
out = tf.keras.layers.DepthwiseConv2D(
    kernel_size=64, dilation_rate=2, add_bias=False
)
model = tf.keras.Model(inpt, [out])
```
does not properly convert to a depthwise conv in the output:
![image](https://user-images.githubusercontent.com/1422280/70248416-dcefab00-1748-11ea-976e-7befa2f6ac4d.png)


However this is a temporary workaround to get it to properly identify the pattern:
```
inpt = tf.keras.layers.Input(shape=(257, 257, 3))
out = tf.keras.layers.DepthwiseConv2D(
    kernel_size=64, dilation_rate=2, add_bias=False
)
out = tf.keras.layers.Lambda(lambda x: x + 0.0)
model = tf.keras.Model(inpt, [out])
```
Also, the workaround doesn't work when using the experimental converter.

**Comment by pinzhenx** [comment]
Hi @liyunlu0618,
Seems that this problem still remains

**Comment by mohantym** [comment]
Hi @pinzhenx ! 1.x versions are not supported any more. Feel free to check out [TFLiteconverter](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter) api from 2.8 version though. Thanks!
