### ISSUE TITLE
Broadcasting batch_gather

### ISSUE THREAD

**Issue by MarkGreeny** [tensorflow/tensorflow#24343]
**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

Batch gather works like this

```python3
result[i, .., k] = input[i, ..., k-1, indexes[i, ..., k]]
```
Now, lets say that `indexes.shape == [s1,s2,s3, k]` and `input.shape == [s1, 1, s3]`.  In order to be able to use batch_gather we must do

```python3
input_ = tf.tile(input, (1, s2, 1))
result = tf.batch_gather(input_, indexes)
``` 
which is wasteful, as we needlessly copy the tensor, for tiling.

In case this feature already exists and I missed it, please direct and forgive me.

**Will this change the current api? How?** No

**Who will benefit with this feature?** Most serious users, who work with masks and such.

**Any Other info.**

**Comment by ppwwyyxx** [comment]
I believe what you described can be achieved by `tf.gather_nd`

**Comment by MarkGreeny** [comment]
@ppwwyyxx You are correct. I have now implemented it using gather_nd. I am closing this issue, as the feature is already present, with little work on gather_nd.

**Comment by harshini-gadige** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=24343)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=24343)
