### ISSUE TITLE
Pretrained tensorflow resnet-101 on MPII human pose data

### ISSUE THREAD

**Issue by sebo313** [tensorflow/tensorflow#24344]
Hello,

do you know if a pretrained resnet-101 tensorflow model exists on MPII human pose dataset? I could not find any so far..

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
