### ISSUE TITLE
Can't open tensorflow.org

### ISSUE THREAD

**Issue by AllenIrving** [tensorflow/tensorflow#24340]
I can't open https://www.tensorflow.org/ but I can open https://tensorflow.google.cn, why is that? If tensorflow has changed its URL why didn't update it? When I google tensorflow it also leads to https://www.tensorflow.org, but it cannot be accessed.
Does anyone else having this problem?

**Comment by blairly** [comment]
Most likely a routing issue between your exchange and tensorflow.org - contact your ISP if it hasn't been fixed in a day or two.
