### ISSUE TITLE
ERROR: Installing Tensorflow GPU with CUDA 10.0 for python on Windows

### ISSUE THREAD

**Issue by mikkocaguiat** [tensorflow/tensorflow#24359]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (Windows 10):
- TensorFlow installed from (source):
- TensorFlow version: 1.12
- Python version:3.6
- Installed using pip:
- Bazel version (0.20.0):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:Cuda 10.0 cuDNN 7.3.1
- GPU model and memory: GTX 1060 6GB

I'm installing tensorflowgpu from source and following a guide from https://www.python36.com/how-to-install-tensorflow-gpu-with-cuda-10-0-for-python-on-windows/.
i followed all instructions as far as i know, no errors are seen all through out the installation.

At step 12, i got an error log

Admin@Thesis-CCD MSYS /c/tensorflow/tensorflow
$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --config=monolithic
WARNING: The following configs were expanded more than once: [cuda, monolithic]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
Loading:
Loading: 0 packages loaded
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 1447
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 1187, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 911, in _get_cuda_config
                _cudnn_version(repository_ctx, cudnn_install_base..., ...)
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 614, in _cudnn_version
                auto_configure_fail(("cuDNN version detected from %s...)))
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 317, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: cuDNN version detected from C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include/cudnn.h (7.3.1) does not match TF_CUDNN_VERSION (7)
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 1447
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 1187, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 911, in _get_cuda_config
                _cudnn_version(repository_ctx, cudnn_install_base..., ...)
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 614, in _cudnn_version
                auto_configure_fail(("cuDNN version detected from %s...)))
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 317, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: cuDNN version detected from C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include/cudnn.h (7.3.1) does not match TF_CUDNN_VERSION (7)
INFO: Elapsed time: 0.245s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

ANY HELP ABOUT THIS?

**Comment by jxcong** [comment]
Me Too.
Win10 cuda10+cudnn7.4+bazel0.17.2+tf1.12+python3.6.7

# bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: tensorflow/tools/pip_package
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow-gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 1447
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow-gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 1303, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/tensorflow-gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 217, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/tensorflow-gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 153, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
type 'NoneType' has no method replace(string, string)
WARNING: Target pattern parsing failed.
Analyzing: 0 targets (0 packages loaded)
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow-gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 1447
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow-gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 1303, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/tensorflow-gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 217, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/tensorflow-gpu/tensorflow/third_party/gpus/cuda_configure.bzl", line 153, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
type 'NoneType' has no method replace(string, string)
INFO: Elapsed time: 8.214s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)


who can help me for this quession. thank you very much.

**Comment by ClusterM** [comment]
Same problem.

**Comment by Fighting-JJ** [comment]
same problem

**Comment by kavita-moholkar** [comment]
same problrm

**Comment by hgadig** [comment]
Has everyone tried this with the latest Tensorflow version 1.13 ? Is this the same with 1.13 too ?

**Comment by jvishnuvardhan** [comment]
First, I would suggest you to uninstall python and tensorflow completely from your systems and start a fresh installation by following these [instructions](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12). Please check the tested build configurations for cpu [here](https://www.tensorflow.org/install/source_windows#cpu) and for gpu [here](https://www.tensorflow.org/install/source_windows#gpu). Please note that TF1.12 was built with CUDA9.0 and Bazel 0.15.0. 

Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-1.12.0 | 3.5-3.6 | MSVC 2015 update 3 | Bazel 0.15.0 | 7 | 9

If you want to install TF1.13.1, then you can use CUDA10 (not CUDA 10.1) and Bazel 0.21.0. Please let me know how it progresses. Thanks!

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. Please open a new ticket if the bug persists with latest TF version. Thanks!

**Comment by rlewkowicz** [comment]
@jvishnuvardhan I'm still having this issue. Cuda 10.0, trying to build tensorflow 2 on windows 10. The only reason I'm doing this is to hopefully alleviate severe windows performance issues that are not a problem in a linux environment.
