### ISSUE TITLE
Advanced Tensorflow Neural Network visualization

### ISSUE THREAD

**Issue by JafferWilson** [tensorflow/tensorflow#24368]
I have gone through the beautiful tool given by Tensorflow. I am talking about the Playground. The tool is available at https://github.com/tensorflow/playground.
Even though it an excellent tool but it doesn't help in analyzing the datasets given by the user. It takes its own 2D random numbers and let the people play with it. 
My request for feature is that I want to have a similar tool but it should let the user use their datasets for analyzing the neural network offered by tensorflow.

**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes ofcourse. if I get cleared with how the tool is working. I tried hard to understand but the tool has many hard coded values and is making is difficult to understand.

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?** Never.

**Who will benefit with this feature?**

Everyone who is planning to create a machine learning model and want to start with Tensorflow. The newbie or even Researchers will be benefited by this tool. The visualization will give them a clear idea without any pain.

**Any Other info.**
There isn't anything yet. If there is any in future I will add.

**Comment by ymodak** [comment]
This issue is more suitable on tensorflow/playground repo. Please post this issue on https://github.com/tensorflow/playground/issues. Thanks!
