### ISSUE TITLE
Block Matrix / Block Diagonal Matrix

### ISSUE THREAD

**Issue by mileslucas** [tensorflow/tensorflow#24364]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): python 1.12.0
- Are you willing to contribute it (Yes/No): I would but I have very little knowledge of the TF internals

**Describe the feature and the current behavior/state.**
I am requesting the development of a block diagonal function for tensors. In `scipy` this is included in the `scipy.linalg.block_diag` function. Converted to tensors, it makes sense that given a `[M, K, X, ...]` tensor, when calling the proposed `tf.block_diag` it would return a `[M*K, M*K, X, ...]` matrix with the diagonal elements containing the elements from the `[K, X, ...]` submatrix. This seems to be implemented as a LinearOperator but it is not conducive to the tensor-level functions that exist for the rest of the linear algebra domain.

**Will this change the current api? How?**
No, this should not change current api, only add an extra function

**Who will benefit with this feature?**
I will benefit from this feature, as well as anyone else trying to convert code from numpy/scipy to TF. It is a seemingly standard operator in linear algebra and so it makes sense for it to exist in Tensorflow.

**Any Other info.**
I have a cludgy working version that uses padding and concatenation
Given Tensor `input` of shape `(B, K, K, ...)` will return a Tensor of shape `(K*B, K*B)` zero filled except for the `KxK` diagonal elements
```python
import tensorflow as tf
B, K, = input.shape[:2]
paddings = tf.constant([[0, (B-1)*K)],[0, 0]])
diag = tf.pad(input[0], paddings)
for i in range(1, B):
    paddings = tf.constant([[i*K, (B-i-1)*K],[0, 0]])
    zeros = tf.pad(input[i], paddings)
    diag = tf.concat([diag, zeros], 1)
```

**Comment by harshini-gadige** [comment]
@mileslucas  Please fill this template for a new feature request.

**Comment by mileslucas** [comment]
@harshini-gadige I have edited my comment to fit new template, thank you.

**Comment by danielegrattarola** [comment]
+1

**Comment by sw1sh** [comment]
Hey. Any updates on this? I was looking for a way to efficiently inverse a block matrix. Seems like a way to go is having LinearOperator support anti diagonals, and having LinearOperatorBlockAntiDiag  with LinearOperatorBlock additional to LinearOperatorBlockDiag classes.

**Comment by ziofil** [comment]
bump

**Comment by rmothukuru** [comment]
@mileslucas,
Can you please refer the documentation of [tf.linalg.LinearOperatorBlockDiag](https://www.tensorflow.org/api_docs/python/tf/linalg/LinearOperatorBlockDiag) and check if this is what you are looking for? Thanks!

**Comment by FelixOpolka** [comment]
If I am not mistaken, unlike `scipy.linalg.block_diag`, `tf.linalg.LinearOperatorBlockDiag` does not support non-square sub-matrices.

**Comment by mileslucas** [comment]
Okay, if you want to close the issue that's fine but it's clearly not resolved. It's been 3 years since I opened this and I am no longer using TF or working on the same project (we settled on numpy/scipy for all the math) so I don't want to be the lynch pin for this feature.

**Comment by sushreebarsa** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow version with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release](https://github.com/tensorflow/tensorflow/releases) notes to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!
