### ISSUE TITLE
Set different activation in CuDNNLSTM

### ISSUE THREAD

**Issue by saber7165** [tensorflow/tensorflow#24375]
Can we add an "activation" input arg to CuDNNLSTM where uses can set different activation functions? Basically similar to "activation" input arg in LSTM. 
I see **[this](https://github.com/tensorflow/tensorflow/issues/23297)** but it has been closed (@harshini-gadige).

**Comment by harshini-gadige** [comment]
@saber7165  As I already mentioned in the previous issue, could you please post support related questions in StackOverflow. We strictly encourage users to post only bug/feature request here. Thanks !

**Comment by saber7165** [comment]
@harshini-gadige, don't you consider this as feature request though? LSTM accepts different activation functions, but CuDNNLSM does not. I am asking if this feature can be added to CuDNNLSTM.

**Comment by harshini-gadige** [comment]
@saber7165  Please submit [this](https://github.com/tensorflow/tensorflow/issues/new?template=30-feature-request.md) template. We will look into your feature request.

**Comment by alextp** [comment]
It's not feasible to support this since the underlying cudnn API does not let us choose the activation function for LSTMS: https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnRNNMode_t
