### ISSUE TITLE
meta_graph_transform does not work with default checkpoint_path

### ISSUE THREAD

**Issue by ashokramadass** [tensorflow/tensorflow#24379]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS High Sierra 10.13.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.10.1
- Python version: 3.6.5
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

```
import tensorflow as tf
from tensorflow.saved_model import simple_save
from tensorflow.saved_model import tag_constants
from tensorflow.contrib.meta_graph_transform.meta_graph_transform import (
    meta_graph_transform)

with tf.Session() as sess:
    meta_graph_def = tf.saved_model.loader.load(
        sess,
        [tag_constants.SERVING],
        "1544816647")

    new_meta_def = meta_graph_transform(
        base_meta_graph_def=meta_graph_def,
        input_names=["Placeholder"],
        output_names=["dnn/head/predictions/class_ids", "init_all_tables"],
        transforms=["freeze_graph"],
        tags=[tag_constants.SERVING],
        checkpoint_path=None)

    assert new_meta_def.graph_def
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(new_meta_def.graph_def)

        in_tensor = graph.get_tensor_by_name("import/Placeholder:0")
        out_tensor = graph.get_tensor_by_name("dnn/head/predictions/class_ids:0")
        simple_save(
            sess,
            "./frozen",
            inputs={"inputs": in_tensor},
            outputs={"outputs": out_tensor})
```
Error:
Can't load save_path when it is None.

**Comment by harshini-gadige** [comment]
@ashokramadass  Can you please check the path as the error says, it must be pointing to a wrong or non existing path.

**Comment by ashokramadass** [comment]
@harshini-gadige as per the [docs](https://www.tensorflow.org/api_docs/python/tf/contrib/meta_graph_transform/meta_graph_transform/meta_graph_transform), checkpoint_path can take default as None but as you mentioned, it is verifying the path. I don't want to provide a checkpoint path as I am providing a valid base_meta_graph_def.

**Comment by harshini-gadige** [comment]
@allenlavoie  Could you PTAL

**Comment by allenlavoie** [comment]
I don't know anything about contrib/meta_graph_transform. @suharshs are we keeping this, and if so do you know someone who should look at this bug?

**Comment by sushreebarsa** [comment]
@ashokramadass Is this still an issue ? We see that you are using old version of tensorflow  1.x which is not actively supported, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions .Please refer [this](https://www.tensorflow.org/guide/migrate) guide to migrate from TF v1.x to 2.x . Please open a new issue in case you face any errors using TF v2, we will get you the right help.Thanks!
