### ISSUE TITLE
FailedPreconditionError when using callbacks

### ISSUE THREAD

**Issue by Migdalin** [tensorflow/tensorflow#24371]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
This is a modification of the MNIST tutorial. I have included callbacks for TensorBoard and also for a custom history callback, though that callback has been reduced to a no-op.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10 (Build 17134.471))
Spyder 3.2.8

- TensorFlow installed from (source or binary):  pip install TensorFlow

- TensorFlow version (use command below):  1.12.0
- Python version:  3.6.5; Qt 5.9.4, PyQt5 5.9.2 on Windows
- GPU model and memory:  GeForce GTX 1070 Ti, 8G RAM

**Describe the current behavior**
When I include callbacks to TensorBoard and a custom History callback, I get a FailedPreconditionError.

I was getting a similar error when just trying to use TensorBoard.  Changing the import statement to be more specific (from tensorflow.keras.callbacks import TensorBoard) fixed that one, but then I added the history callback, and it is unhappy again.

**Describe the expected behavior**
I include callbacks and do not get an error.

**Code to reproduce the issue**

import os

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.callbacks import TensorBoard
from keras import backend as K

class LossLearningRateScheduler(keras.callbacks.History):
    """
    *** By fergosuci on Kaggle.com ****
    
    A learning rate scheduler that relies on changes in loss function
    """
    def __init__(self):
        super(LossLearningRateScheduler, self).__init__()

    def on_epoch_begin(self, epoch, logs=None):       
        return K.get_value(self.model.optimizer.lr)

fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

train_images = train_images / 255.0
test_images = test_images / 255.0

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.compile(optimizer=keras.optimizers.SGD(), 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

runNumber = len(os.listdir('logs'))
tensorboard = TensorBoard(log_dir=f"logs/run_{runNumber}", write_grads=True, write_graph=False)
learningRateScheduler = LossLearningRateScheduler()

model.fit(train_images, train_labels, epochs=5, callbacks=[tensorboard, learningRateScheduler])

**Other info / logs**
Traceback (most recent call last):

  File "<ipython-input-7-52fc1b0c66af>", line 1, in <module>
    runfile('D:/Dev/Training/TensorFlow Tutorials/MNIST Fashion/ReproduceIssue.py', wdir='D:/Dev/Training/TensorFlow Tutorials/MNIST Fashion')

  File "D:\dev\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "D:\dev\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Dev/Training/TensorFlow Tutorials/MNIST Fashion/ReproduceIssue.py", line 44, in <module>
    model.fit(train_images, train_labels, epochs=5, callbacks=[tensorboard, learningRateScheduler])

  File "D:\dev\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1639, in fit
    validation_steps=validation_steps)

  File "D:\dev\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 215, in fit_loop
    outs = f(ins_batch)

  File "D:\dev\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 2986, in __call__
    run_metadata=self.run_metadata)

  File "D:\dev\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)

  File "D:\dev\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))

FailedPreconditionError: Error while reading resource variable training_5/SGD/Variable_2 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/training_5/SGD/Variable_2/class tensorflow::Var does not exist.
	 [[{{node training_5/SGD/mul_4/ReadVariableOp}} = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](training_5/SGD/Variable_2)]]

**Comment by Migdalin** [comment]
I never came up with a solution for that issue.

**Comment by divye1995** [comment]
any update on this i m facing the same issue 
Below is my code followed with the error log 
```python
import tensorflow as tf
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt
from keras.callbacks import TensorBoard
import time
#MODEL NAME

# print(tf.__version__)


NAME = "fashion_mnist_28x28_{}".format(int(time.time()))

tensorboard = TensorBoard(log_dir="logs/{}".format(NAME))

fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

model_path="models/{}.h5".format(NAME)

# inspecting data for the fashion-mnist images 
def inspect_data():
    plt.figure()
    plt.imshow(train_images[0])
    plt.colorbar()
    plt.grid(False)
    plt.show()

def pre_process_data():
    global train_images,test_images
    train_images = train_images/255.0
    test_images = test_images/255.0

def show25():
    plt.figure(figsize=(10,10))
    for i in range(25):
        plt.subplot(5,5,i+1)
        plt.xticks([])
        plt.yticks([])
        plt.grid(False)
        plt.imshow(train_images[i],cmap=plt.cm.binary)
        plt.xlabel(class_names[train_labels[i]])
    plt.show()

#pre_process_data()
#show25()

def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28,28)),
        keras.layers.Dense(128,activation=tf.nn.relu),
        keras.layers.Dense(10,activation=tf.nn.softmax)
    ])
    model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
    return model

#model = create_model()
#model.summary()

def train_model():
    model = create_model()
    pre_process_data()
    model.fit(train_images,train_labels,batch_size=32,epochs=5)
    return model

def train_and_save_as_whole():
    # save the model in the HDF5
    trained_model = train_model()
    trained_model.save(model_path)

def read_model_as_whole(showsummary=False):
    model = keras.models.load_model(model_path)
    if showsummary:
        model.summary()
    return model

def read_whole_model_and_evaluate():
    model=read_model_as_whole()
    loss,acc = model.evaluate(test_images,test_labels)
    print("Restored model, accuracy: {:5.2f}%".format(100*acc))


train_and_save_as_whole()

```
Log 
```
2019-01-31 12:28:00.717309: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at resource_variable_ops.cc:420 : Not found: Container localhost does not exist. (Could not find resource: localhost/Adam/iterations)
Traceback (most recent call last):
  File "fashion_mnist_keras_tf.py", line 87, in <module>
    train_and_save_as_whole()
  File "fashion_mnist_keras_tf.py", line 72, in train_and_save_as_whole
    trained_model = train_model()
  File "fashion_mnist_keras_tf.py", line 67, in train_model
    model.fit(train_images,train_labels,batch_size=32,epochs=5,callbacks=[tensorboard])
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1639, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 215, in fit_loop
    outs = f(ins_batch)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2986, in __call__
    run_metadata=self.run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable training/Adam/Variable_1 from Container: localhost.This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/training/Adam/Variable_1)
         [[{{node training/Adam/mul_6/ReadVariableOp}} = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/Adam/Variable_1)]]

```

**Comment by Migdalin** [comment]
I still haven't heard of any fix for this one.

**Comment by GuidoBorrelli** [comment]
Me too

**Comment by vzeman** [comment]
the same problem

My model:
```
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Embedding(len(sp), 10, input_length=max_sequence_len-1))
    model.add(tf.keras.layers.Bidirectional(tf.keras.layers.CuDNNLSTM(500)))
    model.add(tf.keras.layers.Dropout(0.4))
    model.add(tf.keras.layers.Dense(len(sp), activation=tf.keras.activations.softmax))

    model.compile(
        optimizer=tf.keras.optimizers.Adam(),
        loss=tf.keras.losses.categorical_crossentropy,
        metrics=['mae', 'acc', 'accuracy', 'categorical_accuracy']
    )
```

**Comment by omalleyt12** [comment]
I'm unable to reproduce the original issue, could you please try with the latest nightly version of TensorFlow?

**Comment by AndreyStille** [comment]
> **System information**
> 
> * Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
>   This is a modification of the MNIST tutorial. I have included callbacks for TensorBoard and also for a custom history callback, though that callback has been reduced to a no-op.
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
>   Windows 10 (Build 17134.471))
>   Spyder 3.2.8
> * TensorFlow installed from (source or binary):  pip install TensorFlow
> * TensorFlow version (use command below):  1.12.0
> * Python version:  3.6.5; Qt 5.9.4, PyQt5 5.9.2 on Windows
> * GPU model and memory:  GeForce GTX 1070 Ti, 8G RAM
> 
> **Describe the current behavior**
> When I include callbacks to TensorBoard and a custom History callback, I get a FailedPreconditionError.
> 
> I was getting a similar error when just trying to use TensorBoard. Changing the import statement to be more specific (from tensorflow.keras.callbacks import TensorBoard) fixed that one, but then I added the history callback, and it is unhappy again.
> 
> **Describe the expected behavior**
> I include callbacks and do not get an error.
> 
> **Code to reproduce the issue**
> 
> import os
> 
> import tensorflow as tf
> from tensorflow import keras
> from tensorflow.keras.callbacks import TensorBoard
> from keras import backend as K
> 
> class LossLearningRateScheduler(keras.callbacks.History):
> """
> *** By fergosuci on Kaggle.com ****
> 
> ```
> A learning rate scheduler that relies on changes in loss function
> """
> def __init__(self):
>     super(LossLearningRateScheduler, self).__init__()
> 
> def on_epoch_begin(self, epoch, logs=None):       
>     return K.get_value(self.model.optimizer.lr)
> ```
> 
> fashion_mnist = keras.datasets.fashion_mnist
> 
> (train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
> 
> train_images = train_images / 255.0
> test_images = test_images / 255.0
> 
> model = keras.Sequential([
> keras.layers.Flatten(input_shape=(28, 28)),
> keras.layers.Dense(128),
> keras.layers.BatchNormalization(),
> keras.layers.Activation('relu'),
> keras.layers.Dense(10, activation=tf.nn.softmax)
> ])
> 
> model.compile(optimizer=keras.optimizers.SGD(),
> loss='sparse_categorical_crossentropy',
> metrics=['accuracy'])
> 
> runNumber = len(os.listdir('logs'))
> tensorboard = TensorBoard(log_dir=f"logs/run_{runNumber}", write_grads=True, write_graph=False)
> learningRateScheduler = LossLearningRateScheduler()
> 
> model.fit(train_images, train_labels, epochs=5, callbacks=[tensorboard, learningRateScheduler])
> 
> **Other info / logs**
> Traceback (most recent call last):
> 
> File "", line 1, in 
> runfile('D:/Dev/Training/TensorFlow Tutorials/MNIST Fashion/ReproduceIssue.py', wdir='D:/Dev/Training/TensorFlow Tutorials/MNIST Fashion')
> 
> File "D:\dev\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
> execfile(filename, namespace)
> 
> File "D:\dev\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
> exec(compile(f.read(), filename, 'exec'), namespace)
> 
> File "D:/Dev/Training/TensorFlow Tutorials/MNIST Fashion/ReproduceIssue.py", line 44, in 
> model.fit(train_images, train_labels, epochs=5, callbacks=[tensorboard, learningRateScheduler])
> 
> File "D:\dev\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1639, in fit
> validation_steps=validation_steps)
> 
> File "D:\dev\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 215, in fit_loop
> outs = f(ins_batch)
> 
> File "D:\dev\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 2986, in **call**
> run_metadata=self.run_metadata)
> 
> File "D:\dev\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1439, in **call**
> run_metadata_ptr)
> 
> File "D:\dev\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in **exit**
> c_api.TF_GetCode(self.status.status))
> 
> FailedPreconditionError: Error while reading resource variable training_5/SGD/Variable_2 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/training_5/SGD/Variable_2/class tensorflow::Var does not exist.
> [[{{node training_5/SGD/mul_4/ReadVariableOp}} = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](training_5/SGD/Variable_2)]]

Hi, have you solved the issue? I have same problem. Please help if you have solution.
