### ISSUE TITLE
tf.einsum doesn't compute the trace correctly

### ISSUE THREAD

**Issue by ziofil** [tensorflow/tensorflow#24374]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: MacOS Mojave 10.14.1
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12
- Python version: 3.6.6

**Describe the current behavior**
The formula to compute the trace of a matrix with `einsum` computes instead the sum of all the elements of the matrix.

**Describe the expected behavior**
The result should the the sum of the elements on the diagonal (compare with `np.einsum('ii', matrix)`)

**Code to reproduce the issue**
```python
import tensorflow as tf

matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

with tf.Session() as sess:
    print(tf.einsum('ii',matrix).eval())

# 45 (should be 15)
```

**Comment by drpngx** [comment]
That sounds like a serious bug. @ziofil Could you send a fix?

/CC @av8ramit if we have a fix we might want to patch releases.

**Comment by ziofil** [comment]
I wish I was competent enough to send a fix, sorry. How could this escape the tests?
Anyways, I think [here](https://github.com/tensorflow/tensorflow/blob/fbc072b45d4a64e8fcc13783fa6047144a8ace2d/tensorflow/python/ops/special_math_ops.py#L270) is where the sum of all the elements takes place, because if the string is `'ii'`, `axis` is `[0,1]`.

**Comment by drpngx** [comment]
Thanks for the information! I looked briefly into this. This is clearly not ideal, but note that the documentation states that this is not a supported [case](https://github.com/tensorflow/tensorflow/blob/fbc072b45d4a64e8fcc13783fa6047144a8ace2d/tensorflow/python/ops/special_math_ops.py#L182). It's a bug that it doesn't warn, and a feature request that it should work.

**Comment by drpngx** [comment]
Actually, I tried the latest version and it does error out correctly:
```
ValueError: Subscript not supported: an axis appears more than once: ii
```

**Comment by lhendre** [comment]
Hi, I have used Tensorflow for awhile, and was looking for a good place to start contributing.  This seems like a good feature for me to take a start at and I am looking into this

**Comment by drpngx** [comment]
Sounds good. Thank you!

**Comment by lhendre** [comment]
I am working on the issue and testing, things have slowed down a bit on my end due to the holidays but i have blocked time to wrap this up over the weekend.  Ill post and updated status on sunday/monday and if i have made progress ill step back then

**Comment by ziofil** [comment]
@lhendre, could you update us? Thanks 🙏

**Comment by lhendre** [comment]
Hi, Sorry about that I had some family issues but thats been wrapped up and I have made some progress.  I have code that will handle trace correctly with base unit tests, I am right now testing and trying to make sure this is the appropriate way to do this/see if there is any more optimal way.  Ill be attaching this shortly

**Comment by lhendre** [comment]
#25079

**Comment by lhendre** [comment]
The PR has been merged and issue fixed.
