### ISSUE TITLE
TensorFlow Tutorial. TensorFlowLite example app crashes: Tensor shape does not match.

### ISSUE THREAD

**Issue by StephanZmk** [tensorflow/tensorflow#24380]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy S6
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.9
- Python version: 2.7
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): 6
- CUDA/cuDNN version: 9.0/7.14
- GPU model and memory: GeForce GTX 1060 6GB

**Describe the current behavior**
I retrained a ssd_mobilenet_v1 as described in this [guide](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193).
So i converted my model to .tflite as shown under "Running on mobile with TensorFlow Lite"
When i try to run it on my Phone, the App just crashes. So i installed Android Studio and tried to run it from there. Now i got following error:
`Process: org.tensorflow.lite.demo, PID: 12449
    java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [1, 4, 4].
        at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:240)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:116)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:152)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:216)
        at org.tensorflow.demo.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:194)
        at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:249)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)`

The important line, i think, is **Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [1, 4, 4].**

How do i know what tensor shape is needed? Can i change that in the app? Or do i need to change my model in some way?

**Describe the expected behavior**

Running example app with retrained model as shown in the [guide](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193)

**Code to reproduce the issue**
converted the model via:
`bazel run -c opt tensorflow/contrib/lite/toco:toco -- \`
`--input_file=$OUTPUT_DIR/tflite_graph.pb \`
`--output_file=$OUTPUT_DIR/detect.tflite \`
`--input_shapes=1,300,300,3 \`
`--input_arrays=normalized_input_image_tensor \`
`--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  \`
`--inference_type=QUANTIZED_UINT8 \`
`--mean_values=128 \`
`--std_values=128 \`
`--change_concat_input_ranges=false \`
`--allow_custom_ops`

Changes in **DetectorActivity.java** to match my model and labels:
`private static final int TF_OD_API_INPUT_SIZE = 300;`
  `private static final boolean TF_OD_API_IS_QUANTIZED = true;`
  `private static final String TF_OD_API_MODEL_FILE = "detectquant.tflite";`
  `private static final String TF_OD_API_LABELS_FILE = "file:///android_asset/icons4cats.txt";`

**Comment by cathybgyz** [comment]
The error states your are copying [1, 10, 4] to  [1, 4, 4]. 1 fits in 1, but 10 doesn't fit in 4.. therefore you get the error. You could reshape your model or adjust the target object you are copying the tensors too.

Are you trying to work with a custom model inside example software?

Links to the software would be helpful, as well as a description of the model if you cannot provide the code used to generate it.

**Comment by eviansplash** [comment]
Hey, try increasing the number of detections in your java object. In your example app, change NUM_DETECTIONS or whatever it might be called. This will increase the java object shape from you current [1,4,4] to [1,10,4] matching the tensor shape. :)

**Comment by achowdhery** [comment]
Did the abovementioned change resolve your issue regarding app crash?

**Comment by srjoglekar246** [comment]
Closing this, feel free to re-open if the problem still exists.

**Comment by ricardobnjunior** [comment]
@StephanZmk I have the same problem, how did you solve it ?

**Comment by StephanZmk** [comment]
@ricardobnjunior i am not quiet sure anymore. I think using the tf-nightly build did the trick.

**Comment by VirRajpurohit** [comment]
@StephanZmk  what do you mean by tf-nightly build?

**Comment by leaving-voider** [comment]
> Hey, try increasing the number of detections in your java object. In your example app, change NUM_DETECTIONS or whatever it might be called. This will increase the java object shape from you current [1,4,4] to [1,10,4] matching the tensor shape. :)
> 
> Edit: Change it from 4 to 10

非常谢谢，解决了我的问题！
