### ISSUE TITLE
TFLite:Models with multiple inputs and outputs

### ISSUE THREAD

**Issue by Archernarkiu** [tensorflow/tensorflow#24392]
How can I handle the situations when my tensorflow models have mutiple inputs and outputs? It's not possible to give a fixed input_shape, so can any one help?

**Comment by Archernarkiu** [comment]
I've already noticed this 

>Each output should be an array or multi-dimensional array of the supported primitive types, or a ByteBuffer of the appropriate size. _**`Note that some models have dynamic outputs, where the shape of output tensors can vary depending on the input. There's no straightforward way of handling this with the existing Java inference API, but planned extensions will make this possible.`**_

at tensorflow lite's offical API guide, but I wonder is there any possible way to deal with it in C++ source code.
Any help will be appreciated, thanks so much!

**Comment by miunayan** [comment]
Hi, I  met the same problem and have you solved it?

**Comment by laohur** [comment]
how about it now ?

**Comment by laohur** [comment]
ok now!

**Comment by lzc16** [comment]
Hi @laohur !
I have met the same problem. Can you show the example~~
