### ISSUE TITLE
Variable sized tf records

### ISSUE THREAD

**Issue by BornInWater** [tensorflow/tensorflow#24390]
While storing data in tf records, say an image of size (N,3,224,224), its possible to keep N as variable, but is it possible to have another dimension variable. Like I have voxels of objects that I need to store and number of objects in an 3D world is random, so it will be something like (batch_size, num_objects, 128,128,128). Tensorflow does not seem to allow having one more dimension. Is there a way to solve this?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
