### ISSUE TITLE
Equivalent c_api for TFE_Py_RecordGradient

### ISSUE THREAD

**Issue by Oceania2018** [tensorflow/tensorflow#24393]
Hi, I'm trying to implement a C# wrapper for Tensorflow, but stuck in the c_api which is work like `TFE_Py_RecordGradient`.

Is there any equivalent c_api? or any work around?

I want to implement a C# code to do `var x = tf.placeholder(tf.float32, shape: new TensorShape(1024, 1024));`

Any related information will be helpful, thanks.

**Comment by Oceania2018** [comment]
The only clue I've got in the c_api.cc:
```
// Creates a placeholder representing an input to the cond or body graph.
// TODO(skyewm): remove these from final graph
bool CreateInput(const TF_Output& parent_input, TF_Graph* g, const char* name,
                 TF_Output* input, TF_Status* status) {
  TF_OperationDescription* desc = TF_NewOperation(g, "Placeholder", name);
  TF_SetAttrType(desc, "dtype", TF_OperationOutputType(parent_input));
  // TODO(skyewm): set placeholder shape
  TF_Operation* oper = TF_FinishOperation(desc, status);
  if (!status->status.ok()) return false;
  *input = {oper, 0};
  return true;
}
```

**Comment by skye** [comment]
I believe most language bindings that wish to support an TF Eager-like API (e.g. GradientTape) wrap the TFE_* functions in addition to the TF_* functions. Does this help?

**Comment by rmothukuru** [comment]
@Oceania2018,
Can you please respond to the above comment? Thanks!

**Comment by Oceania2018** [comment]
It’s been resolved.
