### ISSUE TITLE
Example word2vec.py

### ISSUE THREAD

**Issue by arieltci** [tensorflow/tensorflow#244]
Error while executing python word2vec.py:

from tensorflow.models.embedding import gen_word2vec as word2vec
ImportError: No module named embedding

**Comment by zhiwei123** [comment]
楼墨迹HK

**Comment by khellan** [comment]
I have submitted a fix for this. Hopefully it'll go through code review and be accepted in the not too distant future.

https://tensorflow-review.googlesource.com/#/c/1142/

**Comment by ZhangBanger** [comment]
@khellan Thanks!

**Comment by khellan** [comment]
@ZhangBanger It was fixed by Google before my patch was merged :)

**Comment by ZhangBanger** [comment]
Does this mean you can run without building from source?

**Comment by khellan** [comment]
That's a good question. I don't really know since I build from source due to some other changes I have. The current binary install is 0.6.0. I guess it should be included.

**Comment by vrv** [comment]
This was fixed a while ago, should be fine in 0.7 and up.

**Comment by ZhangBanger** [comment]
:+1:  danke
