### ISSUE TITLE
Tensorflow GPU installation in Windows 10 with anaconda

### ISSUE THREAD

**Issue by JanVanIm** [tensorflow/tensorflow#24406]
**System information**
- **OS Platform and Distribution**: Windows 10
- **TensorFlow installed from (source or binary)**: I don't know
- **TensorFlow version**: 1.12.0
- **Python version**:  3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)]
- **Installed using virtualenv? pip? conda?**: I don't remember
- **Bazel version (if compiling from source)**: I don't know
- **GCC/Compiler version (if compiling from source)**: I don't know
- **CUDA/cuDNN version**: Cuda compilation tools, release 10.0, V10.0.130 / cuDNN v. 7.4.1
- **GPU model and memory**:  GeForce GT 635M   

**Describe the problem**

I can't install the GPU version of Tensorflow

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I try to install the GPU version of Tensorflow
So I run the following lines in a Windows command prompt

```
conda create --name tf_gpu
activate tf_gpu
conda install tensorflow-gpu
```
After running `conda create --name tf_gpu`, I got the following message 

> Preparing transaction: done
> Verifying transaction: \
> SafetyError: The package for setuptools located at C:\Users\User\Miniconda4\pkgs\setuptools-40.6.2-py36_0
> appears to be corrupted. The path ‘Scripts/easy_install.exe’
> has a sha256 mismatch.
>  reported sha256: 993203a406e04936a07829b1f482fd27d739b640482e213f4c49ea1ee78a5fcf
>  actual sha256: dd0f7f55b91f4c77c6064f6ed3219e3573ae2b4ada1190094887da40d6b7fde1
> SafetyError: The package for wheel located at C:\Users\User\Miniconda4\pkgs\wheel-0.32.3-py36_0
> appears to be corrupted. The path ‘Scripts/wheel.exe’
> has a sha256 mismatch.
>  reported sha256: 993203a406e04936a07829b1f482fd27d739b640482e213f4c49ea1ee78a5fcf
>  actual sha256: e94002e198d87676ccfef870c0648d33d57bd30288ba00dbab112597e223759d
> done
> Executing transaction: done

But I think, that is a minor problem. However, when I run `conda install tensorflow-gpu` I get this 

> 2018–12–16 16:15:23.825085: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
> 2018–12–16 16:15:24.615875: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] **failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected**
> 2018–12–16 16:15:24.623130: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: DESKTOP-85SA7VT
> 2018–12–16 16:15:24.627495: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: DESKTOP-85SA7VT
> Device mapping: no known devices.
> 2018–12–16 16:15:24.645904: I tensorflow/core/common_runtime/direct_session.cc:307] Device mapping:
> .
> 

Is there something wrong with the CUDA/cuDNN installation ?

Tensorflow with CPU does work but not GPU Tensorflow. Thanks

**Comment by franneck94** [comment]
Maybe your graficscard is too old for current Cuda versions.

**Comment by rootkitchao** [comment]
> **System information**
> 
> * **OS Platform and Distribution**: Windows 10
> * **TensorFlow installed from (source or binary)**: I don't know
> * **TensorFlow version**: 1.12.0
> * **Python version**:  3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)]
> * **Installed using virtualenv? pip? conda?**: I don't remember
> * **Bazel version (if compiling from source)**: I don't know
> * **GCC/Compiler version (if compiling from source)**: I don't know
> * **CUDA/cuDNN version**: Cuda compilation tools, release 10.0, V10.0.130 / cuDNN v. 7.4.1
> * **GPU model and memory**:  GeForce GT 635M
> 
> **Describe the problem**
> 
> I can't install the GPU version of Tensorflow
> 
> **Provide the exact sequence of commands / steps that you executed before running into the problem**
> 
> I try to install the GPU version of Tensorflow
> So I run the following lines in a Windows command prompt
> 
> ```
> conda create --name tf_gpu
> activate tf_gpu
> conda install tensorflow-gpu
> ```
> After running `conda create --name tf_gpu`, I got the following message
> 
> > Preparing transaction: done
> > Verifying transaction: 
> > SafetyError: The package for setuptools located at C:\Users\User\Miniconda4\pkgs\setuptools-40.6.2-py36_0
> > appears to be corrupted. The path ‘Scripts/easy_install.exe’
> > has a sha256 mismatch.
> > reported sha256: 993203a406e04936a07829b1f482fd27d739b640482e213f4c49ea1ee78a5fcf
> > actual sha256: dd0f7f55b91f4c77c6064f6ed3219e3573ae2b4ada1190094887da40d6b7fde1
> > SafetyError: The package for wheel located at C:\Users\User\Miniconda4\pkgs\wheel-0.32.3-py36_0
> > appears to be corrupted. The path ‘Scripts/wheel.exe’
> > has a sha256 mismatch.
> > reported sha256: 993203a406e04936a07829b1f482fd27d739b640482e213f4c49ea1ee78a5fcf
> > actual sha256: e94002e198d87676ccfef870c0648d33d57bd30288ba00dbab112597e223759d
> > done
> > Executing transaction: done
> 
> But I think, that is a minor problem. However, when I run `conda install tensorflow-gpu` I get this
> 
> > 2018–12–16 16:15:23.825085: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
> > 2018–12–16 16:15:24.615875: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] **failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected**
> > 2018–12–16 16:15:24.623130: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: DESKTOP-85SA7VT
> > 2018–12–16 16:15:24.627495: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: DESKTOP-85SA7VT
> > Device mapping: no known devices.
> > 2018–12–16 16:15:24.645904: I tensorflow/core/common_runtime/direct_session.cc:307] Device mapping:
> > .
> 
> Is there something wrong with the CUDA/cuDNN installation ?
> 
> Tensorflow with CPU does work but not GPU Tensorflow. Thanks

Tensorflow-GPU requires Nvidia GPUs with CUDA compute capability 3.5 or higher. compute capability of the GT635M is only 2.1(see https://developer.nvidia.com/cuda-gpus).In fact, the GT635M uses the GF106/GF116 chip based on the Fermi architecture.Not the usual Kepler architecture of the Geforce 600 series.The Fermi architecture is too old, and now the Tensorflow GPU is no longer supported.

**Comment by JanVanIm** [comment]
@rootkitchao Thank you for your thorough explanation. By the way when installing Tensorflow with`conda` command it installs CUDA 9.0, not 10.0. 
Do you recommend to use `pip` or `conda` for the installation of Tensorflow ? The regular installation of Tensorflow GPU seems a bit of a struggle.

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
