### ISSUE TITLE
[TFLite] Feature request: Add support for CropAndResize op

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/tensorflow#24407]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): Source
- TensorFlow version (or github SHA if from source): ebe98d94a5340386429da4b6e930b8cda9c7e854
- Are you willing to contribute it (Yes/No): Yes, if feasible / not under current development

```
2018-12-17 15:14:34.782227: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 4345 operators, 7950 arrays (0 quantized)
2018-12-17 15:14:35.080813: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 4054 operators, 7480 arrays (0 quantized)
2018-12-17 15:14:35.472064: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 4054 operators, 7480 arrays (0 quantized)
2018-12-17 15:14:35.713793: F tensorflow/lite/toco/graph_transformations/resolve_constant_slice.cc:59] Check failed: dim_size >= 1 (0 vs. 1)
Aborted (core dumped)
```

Link to a GraphDef or the model: http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_coco_2018_01_28.tar.gz

#### Summary
Currently CropAndResize is not supported in the TFLite runtime, and because of this Faster R-CNN object detection models can not be deployed on mobile. Faster R-CNN has been [shown to outperform SSD models w.r.t accuracy](https://arxiv.org/pdf/1611.10012.pdf), and as compute speed increases it seems intuitive to support this architecture.

My team and I would be interested in adding this functionality, but wanted to make sure that it's feasible and not under current development. Very much related is tensorflow/models/issues/4848, where it was said that there is no fundamental issue with implementing it.

**Comment by achowdhery** [comment]
CropAndResize is one of the select TF ops supported via tflite_convert.

As we work toward fleshing out the builtin op library for TensorFlow Lite, we've been working on an experimental feature that allows using select TensorFlow ops from within the TensorFlow Lite runtime. The goal is to help reduce some of the friction for using models that rely on ops not yet natively supported by TensorFlow Lite (at the cost of increased binary size). This feature requires opting in during model conversion, as well as adding an additional dependency. More details can be found [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/using_select_tf_ops.md](here).

Feedback is very much appreciated (either via GitHub or directly via tflite@tensorflow.org), and we'll be adding and refining functionality over the coming weeks. Cheers.

**Comment by seanpmorgan** [comment]
@achowdhery Thanks this is very informative. Very excited to see the whitelist:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/toco/tflite/whitelisted_flex_ops.cc

**Comment by usamahjundia** [comment]
> @achowdhery Thanks this is very informative. Very excited to see the whitelist:
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/toco/tflite/whitelisted_flex_ops.cc

Did you finally manage to convert FRCNN to TFLITE? If so, how did you do it? I tried converting but ran into errors

**Comment by septra** [comment]
@seanpmorgan In case you were successful in converting the Faster-RCNN model to TFLite could you please provide some details for that? As per my research the the implementation of the ops required to convert the models is still not there and as of now only SSD models can be converted to TFLite.

**Comment by levon-khachatryan** [comment]
Hi all,

Any news about custom implementation of CropAndResize operator @seanpmorgan ?, or about feature allows using select TensorFlow ops from within the TensorFlow Lite runtime @achowdhery ?

**Comment by lev1khachatryan** [comment]
Hi all, 
Any news about custom implementation of CropAndResize operator @seanpmorgan ? or about feature allows using select TensorFlow ops from within the TensorFlow Lite runtime @achowdhery ?

**Comment by seanpmorgan** [comment]
> Hi all,
> Any news about custom implementation of CropAndResize operator @seanpmorgan ? or about feature allows using select TensorFlow ops from within the TensorFlow Lite runtime @achowdhery ?

Use the MLIR `experimental_new_converter` flag and you can use control flow in TFlite:
https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter

**Comment by HarshiniGudipally23** [comment]
> @seanpmorgan In case you were successful in converting the Faster-RCNN model to TFLite could you please provide some details for that? As per my research the the implementation of the ops required to convert the models is still not there and as of now only SSD models can be converted to TFLite.



> @seanpmorgan In case you were successful in converting the Faster-RCNN model to TFLite could you please provide some details for that? As per my research the the implementation of the ops required to convert the models is still not there and as of now only SSD models can be converted to TFLite.

Are you able to convert frcnn model to tflite? I tried and ran into many issues. Please let me know if you have succeeded
