### ISSUE TITLE
Support SparseReduceSum on GPU 

### ISSUE THREAD

**Issue by sh1ng** [tensorflow/tensorflow#24404]
**System information**
- TensorFlow version (you are using): 1.12.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
From a generated trace I see that tensorflow performs SparseReduceSum on CPU while the rest of computation on GPU. I'm using `tf.sparse.reduce_sum`

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Everyone, reduction on CPU kills performance completely. 

**Any Other info.**
Could you point to data structures and/or algorithms that you are going to use, if any?

**Comment by sidhomj** [comment]
this is particularly a problem if loading a graph with this op onto GPU.

**Comment by rmothukuru** [comment]
@sh1ng,
Sorry for the delayed response. Can you please let us know if [tf.raw_ops.SparseReduceSum](https://www.tensorflow.org/api_docs/python/tf/raw_ops/SparseReduceSum?hl=ko.Souten%20Ki%20Beti%20HD%20Jeetendra%20Rekha%20Jaya%20Prada%20Hindi%20Full%20MovieShyam) in the latest **`Tensorflow Version (2.5)`** runs on **`GPU`**? Thanks!

**Comment by kuangllbnu** [comment]
tf.sparse.reduce_sum has been supported on GPU? @sjtusmartboy
