### ISSUE TITLE
Partially-defined shapes and group_norm

### ISSUE THREAD

**Issue by erfannoury** [tensorflow/tensorflow#24409]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `v1.12.0-0-ga6d8ffae09 1.12.0`
- Python version: 3.6.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 9.0
- GPU model and memory: 1080 Ti

**Describe the current behavior**
Given the following minimal code raises an error:
```python
scan_var = tf.placeholder(tf.float32, [None, 128, 128, 64], name='scan')
norm = tf.contrib.layers.group_norm(scan_var, groups=16, channels_axis=3, reduction_axes=(1, 2))
```
When using `tf.contrib.layers.group_norm` with a Tensor that has partially-defined shape (e.g. `[None, H, W, C]`), the following error is raised:
```
TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [None, 128, 128, 16, 4]. Consider casting elements to a supported type.
```
The error is due to [normalization.py#L303](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/contrib/layers/python/layers/normalization.py#L303), since the value of variable `inputs_shape` is `[None, 128, 128, 16, 4]` which cannot be converted to a Tensor. The correct value should be `[-1, 128, 128, 16, 4]`.
This error can be fixed (probably addressing this [TODO](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/contrib/layers/python/layers/normalization.py#L250)) with the addition of the two following lines after Line 252 in `normalization.py`:
```python
original_shape = [-1 if s.value is None else s for s in original_shape]
if len([s for s in original_shape if s == -1]) > 1:
    raise ValueError('Only one axis dimension can be undefined in the input tensor')
```
and the following line after Line 302:
```python
inputs_shape = [-1 if s is None else s for s in inputs_shape]
```

If it seems reasonable I can submit a pull request.

**Comment by ppwwyyxx** [comment]
`contrib.layers.group_norm` might get removed from `tf.contrib` soon, according to https://github.com/tensorflow/community/pull/37. Therefore it may not be worth it to fix it.
Or you can ask the team to keep it in TF in the above PR.

I authored the paper and my version of group norm (which handles partially-defined batch dimension) in TF is [here](https://github.com/tensorpack/tensorpack/blob/79148350eabd6800133a49b101eea4c56e78e4e8/examples/ImageNetModels/vgg16.py#L19-L46).

**Comment by seanpmorgan** [comment]
@ppwwyyxx @erfannoury We'll be adding group_norm as a generalized layer_norm and instance_norm in Addons. tensorflow/addons#6

It'll be refactored though in a similar manner to the keras_contrib [GroupNormalization](https://github.com/keras-team/keras-contrib/blob/master/keras_contrib/layers/normalization.py#L415), so I'm not sure this issue will still be valid in the new implementation. We will at least include a test for it.

**Comment by erfannoury** [comment]
@seanpmorgan this is a good idea. I will then follow the progress of tensorflow/addons#6 for the new implementation of group normalization. This issue probably can be closed then.

**Comment by BilalSaeedLM10** [comment]
Hey Guys!! I am making my own object detector and for that when I go for the training part, I am getting this error:
**Traceback (most recent call last):
  File "train.py", line 51, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\Bilal\Documents\models\research\object_detection\builders\model_builder.py", line 52, in <module>
    from object_detection.models.ssd_mobilenet_v2_feature_extractor import SSDMobileNetV2FeatureExtractor
  File "C:\Users\Bilal\Documents\models\research\object_detection\models\ssd_mobilenet_v2_feature_extractor.py", line 26, in <module>
    from nets.mobilenet import mobilenet_v2
  File "C:\Users\Bilal\Documents\models\research\slim\nets\mobilenet\mobilenet_v2.py", line 89, in <module>
    'normalizer_fn': tf.contrib.layers.group_norm,  # pylint: disable=C0330
AttributeError: module 'tensorflow.contrib.layers' has no attribute 'group_norm'**

Any help ?

**Comment by ppwwyyxx** [comment]
As mentioned above, the function is removed.

**Comment by tejasdixit** [comment]
what's the alternative?

**Comment by ppwwyyxx** [comment]
As mentioned above, an alternative is to use my version of group norm (which handles partially-defined batch dimension).

**Comment by aligokkaya** [comment]
from nets.mobilenet import mobilenet_v2
  File "C:\tensorflow\models\research\slim\nets\mobilenet\mobilenet_v2.py", line 91, in <module>
    'normalizer_fn': contrib_layers.group_norm,  # pylint: disable=C0330
AttributeError: module 'tensorflow.contrib.layers' has no attribute 'group_norm'


any help

**Comment by Davidray053** [comment]
> from nets.mobilenet import mobilenet_v2
> File "C:\tensorflow\models\research\slim\nets\mobilenet\mobilenet_v2.py", line 91, in
> 'normalizer_fn': contrib_layers.group_norm, # pylint: disable=C0330
> AttributeError: module 'tensorflow.contrib.layers' has no attribute 'group_norm'
> 
> any help

do you have the solution now???

**Comment by LeiWang99** [comment]
I've got a problem when using slim.group_norm as 'normalizer_fn=slim.group_norm' for many conv layers, it cannot get the value of batch_size, h and w, so that it cannot use -1 to solve this problem. Did anyone meet this problem?

**Comment by tilakrayal** [comment]
@erfannoury ,
Is this still an issue?
Could you please update TensorFlow to the latest stable version v.2.6 and let us know if you are facing the same error. Thanks!
