### ISSUE TITLE
Tensorflow Lite Dockerfile Error

### ISSUE THREAD

**Issue by gearsmotion789** [tensorflow/tensorflow#24417]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Tensorflow is being installed from the Dockerfile according to https://github.com/tensorflow/models/blob/master/research/object_detection/dockerfiles/android/README.md. I am using CPU - NO GPU. I use Ubuntu 16.04.

**Describe the problem**
When I run "docker build --tag detect-tf .", I get the below error in the terminal. How can I fix it?

Step 3/21 : RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" &&     echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list &&     curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - &&     apt-get update -y && apt-get install google-cloud-sdk -y
 ---> Running in e985c9945ecd
deb http://packages.cloud.google.com/apt cloud-sdk-bionic main
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key output should not be parsed (stdout is not a terminal)
100  1326  100  1326    0     0   5715      0 --:--:-- --:--:-- --:--:--  5715
gpg: failed to start agent '/usr/bin/gpg-agent': No such file or directory
gpg: can't connect to the agent: No such file or directory
gpg: failed to start agent '/usr/bin/gpg-agent': No such file or directory
gpg: can't connect to the agent: No such file or directory
The command '/bin/sh -c export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" &&     echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list &&     curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - &&     apt-get update -y && apt-get install google-cloud-sdk -y' returned a non-zero code: 2

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed the steps from https://github.com/tensorflow/models/blob/master/research/object_detection/dockerfiles/android/README.md.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by achowdhery** [comment]
Are you remove this step in the Dockerfile and manage to build the Docker container?

**Comment by gearsmotion789** [comment]
There are much more other problems in other steps in the Dockerfile too. But do you know how I could fix this step first?

**Comment by talarari** [comment]
This is an old issue but for people that are still running into this, add this before the glcoud install step:
```
RUN apt-get update && apt-get -y install gpg-agent

```

**Comment by MeghnaNatraj** [comment]
Marking issue as resolved due to inactivity. Feel free to re-open this if it's unresolved or file a [new issue](https://github.com/tensorflow/tensorflow/issues/new/choose)
