### ISSUE TITLE
Import Custom C++ Op Error: dynamic module does not define module export function

### ISSUE THREAD

**Issue by jinze1994** [tensorflow/tensorflow#24419]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.4 LTS server
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.12.0
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?: pip3
- GPU model and memory: GTX 1080 12G

**Describe the problem**

I write a custom op by C++ which can work by `tf.load_op_library`. But furthermore, I want to import the function encapsulating the op, which results in `ImportError: dynamic module does not define module export function`. So, how can I import the python function or module which depends on the custom Op?
Thank you very much.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Custom Op C++ file `remap.cc`:
```
#include <unordered_map>
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/op_kernel.h"
#include "tensorflow/core/framework/shape_inference.h"

using namespace tensorflow;

REGISTER_OP("Remap")
.Input("input: int32")
.Input("base: int32")
.Output("output: int32")
.SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
  ::tensorflow::shape_inference::ShapeHandle input;
  TF_RETURN_IF_ERROR(c->WithRank(c->input(1), 1, &input));
  c->set_output(0, c->input(0));
  return Status::OK();
});


class RemapOp : public OpKernel {
public:
  explicit RemapOp(OpKernelConstruction* context) : OpKernel(context) {}

  void Compute(OpKernelContext* context) override {
    // Grab the input tensor
    const Tensor& input_tensor = context->input(0);
    auto input = input_tensor.flat<int32>();
    const Tensor& base_tensor = context->input(1);
    auto base = base_tensor.flat<int32>();

    // Build hash table
    std::unordered_map<int32, int32> map;
    const int base_N = base.size();
    for (int i = 0; i < base_N; i++) {
      map[base(i)] = i;
    }

    // Create an output tensor
    Tensor* output_tensor = NULL;
    OP_REQUIRES_OK(context, context->allocate_output(0, input_tensor.shape(),
          &output_tensor));
    auto output_flat = output_tensor->flat<int32>();

    // Set all elements of output tensor
    const int N = input.size();
    for (int i = 0; i < N; i++) {
      output_flat(i) = map.at(input(i));
    }
  }
};
```

makefile:
```
TF_CFLAGS = $(shell python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))')
TF_LFLAGS = $(shell python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))')

all:
  g++ -std=c++11 -shared remap.cc -o remap.so -fPIC ${TF_CFLAGS} ${TF_LFLAGS} -O2
```

Python function encapsulating the Op `remap.py`:
```
import tensorflow as tf

remap_module = tf.load_op_library('./remap.so')
remap = remap_module.remap

def foo(a):
  ret = remap(a)
  # Do something about ret
  return ret
```

Python `main.py`
```
import tensorflow as tf
from remap import foo

print(foo([1, 2, 3], [1, 2, 3, 4, 5]))
```

Compile the Op by makefile and then run `python main.py`, then we have the error:
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from remap import foo
ImportError: dynamic module does not define module export function (PyInit_remap)
```

**Comment by jinze1994** [comment]
@aselle 
Besides, could you please tell me how to implement the function `remap(input, base)`, which replaces each element in `input` to the indices of `base` by the existing ops?
For example, `remap([[3, 2, 5], [6, 0, 2]], [0, -1, -2, -3, -4, -5, -6])` returns `[[-3, -2, -5], [-6, 0, -2]]`.
The tensor `base` could be large, so we don't want to compare all pairs of these two tensors. On the other hand, `tf.contrib.lookup.HashTable` seems improper owing to keeping the resources in memory among all sessions.

**Comment by chasex** [comment]
@jinze1994 change remap.py to another name (eg. remap_wrap.py) works for me

**Comment by jinze1994** [comment]
@chasex Exactly, thank you very much.

**Comment by Delimited729** [comment]
https://archie-frigate.github.io/VM7xPrskrQSbQe6Nl6lIfgPRTNICIOxzqzCDJ68FKoo3k6QaoIN-5FUg/



got the answer here
