### ISSUE TITLE
ppc64le: no_mkl_dnn_contraction_kernel define causes build failure

### ISSUE THREAD

**Issue by jayfurmanek** [tensorflow/tensorflow#24414]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 ppc64le
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: 3.6
- Installed using virtualenv? pip? conda?:  source
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source):  4.8
- CUDA/cuDNN version:  10.0/7.3
- GPU model and memory: V100

**Describe the problem**
A recent commit (https://github.com/tensorflow/tensorflow/commit/10ef7edc881ee715eaae48656fcb431fe128441f) changed the default contraction kernel to be MKL based. Code was added for non-intel platforms to avoid MKL, but it has an error.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Basic build: `bazel build //tensorflow/tools/pip_package:build_pip_package`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
ERROR: /home/jenkins/workspace/TensorFlow_PPC64LE_GPU_Build/tensorflow/core/kernels/BUILD:610:12: Illegal ambiguous match on configurable attribute "deps" in //tensorflow/core/kernels:eigen_contraction_kernel:
//tensorflow:linux_ppc64le
//tensorflow/core/kernels:no_mkldnn_contraction_kernel
Multiple matches are not allowed unless one is unambiguously more specialized.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: 

/home/jenkins/workspace/TensorFlow_PPC64LE_GPU_Build/tensorflow/core/kernels/BUILD:610:12: Illegal ambiguous match on configurable attribute "deps" in //tensorflow/core/kernels:eigen_contraction_kernel:
//tensorflow:linux_ppc64le
//tensorflow/core/kernels:no_mkldnn_contraction_kernel
Multiple matches are not allowed unless one is unambiguously more specialized.
```

There ends up being multiple matches in the select call:
```
defines = select({
        "//tensorflow:android": [],
        "//tensorflow:arm": [],
        "//tensorflow:ios": [],
        "//tensorflow:linux_ppc64le": [],
        ":no_mkldnn_contraction_kernel": [],
        "//conditions:default": [
            "TENSORFLOW_USE_CUSTOM_CONTRACTION_KERNEL",
            "TENSORFLOW_USE_MKLDNN_CONTRACTION_KERNEL",
        ],
    }),
```
Either the arch-specific entries in the `select` call should be removed, or the `no_mkldnn_contraction_kernel` entry should be removed for this to work. 

I'll follow up with a proposed patch set.

**Comment by TensorFlow-MKL** [comment]
@ezhulenev is already working on it. See https://github.com/tensorflow/tensorflow/pull/24416.

**Comment by jayfurmanek** [comment]
addressed with https://github.com/tensorflow/tensorflow/commit/7c9323bedc48c98be3c07b72ec1d6f4dccdefb35

**Comment by jayfurmanek** [comment]
The fix for this issue was reverted with:

[Temporarily disable MKL-DNN contraction kernels by default] https://github.com/tensorflow/tensorflow/commit/ca8791fc6db991c6c7406f3274ca742d867e0c6b

Temporarily, but its been almost a month.

I had suggested a fix that made sense to me: https://github.com/tensorflow/tensorflow/pull/24416
But it wasn't accepted.

@penpornk What is the plan for this setting in the .bazelrc ?  If the idea is to switch it on and off regularly, please know that it breaks all non Intel builds.

Please advise.

**Comment by jayfurmanek** [comment]
The problem is `tensorflow_mkldnn_contraction_kernel` is only ever defined if on x86_64. So setting it at all (on or off) is a problem for other arches. My attempted fix in https://github.com/tensorflow/tensorflow/pull/24416 was to let that be defined for other arches too, so that disabling it will have an effect.

If I could get clarity on what was unacceptable in https://github.com/tensorflow/tensorflow/pull/24416 perhaps I could change it so this setting would work for everyone. Any feedback?

**Comment by penpornk** [comment]
I'm so sorry for the inconvenience! I forgot that disabling the feature would reintroduce this issue.

> @penpornk What is the plan for this setting in the .bazelrc ? If the idea is to switch it on and off regularly, please know that it breaks all non Intel builds.

We planned to leave it on indefinitely. I switched it off to debug an issue.

> If I could get clarity on what was unacceptable in https://github.com/tensorflow/tensorflow/pull/24416 perhaps I could change it so this setting would work for everyone. Any feedback?

I apologize that we didn't explain properly. Back then, we were about to turn the feature on (i.e., not matching with `no_mkldnn_contraction_kernel`). The following targets don't support the feature so we had to keep them to prevent matching with `//conditions:default`
```
        "//tensorflow:android": [],
        "//tensorflow:arm": [],
        "//tensorflow:ios": [],
        "//tensorflow:linux_ppc64le": [],
```
I'll delete these targets for now and add them back when I re-enable the feature.

If you'd like to contribute to a permanent fix, the conditions are
- Never match with `//conditions:default` for `//tensorflow:android`, `//tensorflow:arm`, `//tensorflow:ios`, and `//tensorflow:linux_ppc64le`, regardless of the `no_mkldnn_contraction_kernel` target.
- If none of the above four target matches, match with `no_mkldnn_contraction_kernel` iff `--define=tensorflow_mkldnn_contraction_kernel=0` is set.

Thank you again for raising this issue!

**Comment by penpornk** [comment]
@jayfurmanek Please let me know whether https://github.com/tensorflow/tensorflow/commit/1a26797203e62390623756fd67e69e7665b69389 has solved the problem. Thank you!

**Comment by jayfurmanek** [comment]
Thanks @penpornk ! What you did in https://github.com/tensorflow/tensorflow/commit/1a26797203e62390623756fd67e69e7665b69389 makes sense to me. I'll give it a shot on ppc64le to confirm.

**Comment by jayfurmanek** [comment]
Confirmed. No dual match on ppc64le when `--define=tensorflow_mkldnn_contraction_kernel=0` is set.
Thanks @penpornk.

Closing this issue.

**Comment by penpornk** [comment]
@jayfurmanek Great. Thank you again for bringing this up and sorry it took us this long!
