### ISSUE TITLE
tf.contrib.ffmpeg: No mention of alternatives after deprecation

### ISSUE THREAD

**Issue by agrinh** [tensorflow/tensorflow#24424]
**System information**
- TensorFlow version: 1.12
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/contrib/ffmpeg/decode_audio

**Describe the documentation issue**
Is there a plan to replace `tf.contrib.ffmpeg`? I currently rely on it in a tf.data pipeline and didn't think it was clear from the docs if there is or is not a plan on replacing the functionality. I would appreciate some clarification in the docs on that matter.

E.g. the [Simple Audio Recognition](https://www.tensorflow.org/tutorials/sequences/audio_recognition) seems to use [audio_ops](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/framework/python/ops/audio_ops.py) which AFAIK is completely missing from the docs. Is this perhaps meant to replace (some of) the functionality of `tf.contrib.ffmpeg`, or is it expected that all of the audio decoding functionality will be phased out from tensorflow?

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
Yes, if clear update recommendations are provided.

**Comment by yongtang** [comment]
@agrinh The tf.contrib.ffmpeg is getting deprecated in tensorflow. However, tensroflow' SIG IO (https://github.com/tensorflow/io) is planing adding support for import video/audio to tf's Dataset. The sig-io itself consists of a collection of extended data ops that could be used in tensorflow.

There is already a PR in sig-io's repo tensorflow/io#30 which adds a `VideoDataset`.

Please take a look if interested.

**Comment by yongtang** [comment]
@agrinh I will close this issue for now. Please open issues in https://github.com/tensorflow/io for additional tensorflow dataset support.
