### ISSUE TITLE
Forced to compile Keras model for inference

### ISSUE THREAD

**Issue by harahu** [tensorflow/tensorflow#24429]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.1
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.12.0
- Python version: 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38)
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
Calling `model.predict()` with a `tf.data.Dataset` as input is only possible when compiling the model first and also providing labels. The `predict` method is supposed to not require compiling before use, but the method `_standardize_user_data` ( called at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training.py#L1113) raises the following exception if model is not compiled, and a (x,y) tuple is returned from the dataset:

> RuntimeError: You must compile a model before training/testing. Use `model.compile(optimizer, loss)`.

If the datset only returns the input tensor(s), x, another exception is raised:

> ValueError: Please provide model inputs as a list or tuple of 2  or 3 elements: (input, target) or (input, target, sample_weights) Received <next_element>

**Describe the expected behavior**
I expect behaviour not to differ from when providing arrays or lists of arrays as input. I should be able to provide a `tf.data.Dataset` as input, that provides a single tensor or a list of tensors.

**Code to reproduce the issue**
```
import tensorflow.keras as keras
import tensorflow.data as data


dataset_values = [1, 2, 3, 4, 5]


def single_element_input_fn():
    return data.Dataset.from_tensor_slices(dataset_values)


def tuple_input_fn():
    dataset = data.Dataset.from_tensor_slices(dataset_values)
    # Spoof some labels in order to satisfy shape requirement
    return dataset.map(lambda x: (x, 0))


model_input = keras.layers.Input(shape=(1, ))
model_output = keras.layers.Activation('tanh')(model_input)
model = keras.models.Model(inputs=model_input, outputs=model_output)

# passing python list of values works
print(model.predict(dataset_values))
try:
    # Raises ValueError
    print(model.predict(single_element_input_fn(), steps=5))
except ValueError as e:
   print(e)
try:
   # Raises RuntimeError
   print(model.predict(tuple_input_fn(), steps=5))
except RuntimeError as e:
    print(e)
```

**Other info / logs**
See code above.

**Comment by omalleyt12** [comment]
Hi @harahu, please call `.batch(<batch_size>)` on your Dataset. When I do that with your example, everything works fine

For example:

```python
def single_element_input_fn():
    return data.Dataset.from_tensor_slices(dataset_values).batch(1)
```

**Comment by harahu** [comment]
@omalleyt12 I originally reported this issue using TF 1.12. I rechecked with that version and the issue still remains, also when using batch as you suggest. You are correct in that it now works in version 1.13.1, when using batch. I guess it might not be worth backporting the fixes. (I, at least have moved on to 1.13.1)

I am, however, unsure if this really is a satisfying solution, because it means that the dimensionality requirements for when you use numpy arrays as input and when you use TF datasets are different. In the example above, if you use:
```python
dataset_values = np.array([1, 2, 3, 4, 5])
```
you get the desired predictions, but you need to use the `batch` method in the dataset. Now, if you rather use:
```python
dataset_values = np.array([[1], [2], [3], [4], [5]])
```
you _still_ get the correct results using the array directly, but you _don't_ need to use batching in the dataset.

In my mind it would make sense that there is a stricter one-to-one mapping between arrays and datasets, particularly when they can be used interchangeably, as in this case. This essentially means either raising exceptions when using the flattened array directly, as in the first example, or somehow inferring that an unbatched dataset should be interpreted as a _single_ batch. My reasoning for this is that I think it is confusing to deal with two slightly different requirements for input shape depending on how I choose to represent it.

Do you think this is a valid point? If so, I think this probably warrants a new issue.

**Comment by omalleyt12** [comment]
Hi @harahu, yes you're correct we are only forward-fixing. Backporting changes like this requires quite a lot of work. 

I see your point about the difference b/t how np arrays and Datasets are handled. Technically the second example you provided is the correct one, it's quite ambiguous in the first example whether Keras should expand to:

(A)
```python
dataset_values = np.array([[1], [2], [3], [4], [5]])
```

or (B):

```python
dataset_values = np.array([[1, 2, 3, 4, 5]])
```

For historical reasons, Keras expands NP arrays to (A) but I'm not sure we want to auto-batch people's Datasets bc of this ambiguity, and bc Datasets can be used for some advanced use cases that this might mess up

**Comment by harahu** [comment]
@omalleyt12 Also, strictly speaking, the original issue isn't entirely resolved. Yes, I am no longer forced to also provide labels in order to satisfy the shape requirements when using a dataset, but if I choose to, for reasons unknown, I still get the error:
``You must compile a model before training/testing. Use `model.compile(optimizer, loss)`.``

So I guess what has changed is the criticality of the issue, not the issue it self. I guess that is something to think about before closing this issue.

A related issue is that if you provide an inappropriate `steps`, value (6, in this example) to `model.predict` when using a dataset as input, you trigger a warning that looks really out of place (note the reference to a training context):
```
WARNING:tensorflow:Your dataset iterator ran out of data; interrupting training.
Make sure that your dataset can generate at least `steps_per_epoch * epochs` batches (in this case, 6 batches).
You may need touse the repeat() function when building your dataset.
```
Both of these issues are obviously the result of reusing code between implementations of `model.predict` and `model.fit`, which I see the appeal in.

**Comment by harahu** [comment]
@omalleyt12 I agree that it might not be desirable to imitate the same leniency when using datasets as well. Assuming this is a quirk of the Keras specification, it is probably also not realistic to tighten up the requirements for array input to match that of dataset. But at a minimum I think it is an idea to document the differences somewhere, so that people like me can avoid confusion and head scratching.
