### ISSUE TITLE
where  'tf.image.resize_bilinear' is defined ?

### ISSUE THREAD

**Issue by hufangjian** [tensorflow/tensorflow#24426]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version:v1.9
- Doc Link:
https://tensorflow.google.cn/api_docs/python/tf/image/resize_bilinear

**Describe the documentation issue**
i want to see the 'tf.image.resize_bilinear' source code.
but i can not find 'tensorflow/python/ops/gen_image_ops.py'.

**Comment by hsgkim** [comment]
`gen_image_ops.py` means the Python API has been generated from C++ code. For this case, the op and the kernel defined respectively at:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/image_ops.cc
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/resize_bilinear_op.cc

**Comment by ymodak** [comment]
Closing this issue since @hsgkim has provided the solution. Feel free to reopen if have any further questions. Thanks!

**Comment by mrtpk123** [comment]
The link to `resize_bilinear_op.cc` is broken. The updated link - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/image/resize_bilinear_op.cc  and it's header is https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/image/resize_bilinear_op.h
