### ISSUE TITLE
Retrain Model & Serv it

### ISSUE THREAD

**Issue by rickstiller** [tensorflow/tensorflow#24421]
Dear Forum Users,

i was creating a Model with retrain.py on Ubuntu 18.04 in a virtual Machine on my Server (https://www.tensorflow.org/hub/tutorials/image_retraining)
Tensorflow is installed via pip installtion. I'm only using CPU.

after testing it with the python label_image.py it works everthing fine and the detection works great!

so i try'd to serve my own model with the tensorflow-serving (https://github.com/tensorflow/serving.git).

on the github serving-example the execution of the model "half_plus_two" works also pretty well and i was able to connect via the RESTful API.

then i try'd to host my own model (out of the /tmp folder from the retrain.py)
i copy'd/renamed the files from the /tmp folders to the structure of the "half plus two" model, like in the example 
"/saved_model_half_plus_two_cpu/" and "/half_plus_two/".

when i try to start the serving via the following cmd:
docker run -t --rm -p 8561:8561 \
   -v "$TESTDATA/saved_model_half_plus_two_cpu:/models/half_plus_two" \
   -e MODEL_NAME=half_plus_two \
   tensorflow/serving &

the application says: "No versions of servable half_plus_two found under base path /models/half_plus_two"
could anyone help?

thank you and regards

**Comment by ymodak** [comment]
This issue is more suitable on TensorFlow Serving repo. Please post it on tensorflow/serving from [here](https://github.com/tensorflow/serving/issues). Thanks!
