### ISSUE TITLE
TF doesn't build for Raspberry Pi

### ISSUE THREAD

**Issue by mixaz** [tensorflow/tensorflow#24420]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux 4.15 x86_64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source, building ci_build.sh from TF distro
- TensorFlow version: latest from master
- Python version: tried both 2.7 and 3
- Installed using virtualenv? pip? conda?: 
- Bazel version (if compiling from source): tried both 0.20.0 and 0.19.2
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

When following instructions at https://www.tensorflow.org/install/source_rpi to cross-compile TF for RPi, the build fails, see log below.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. clone TF source
2. `tensorflow/tools/ci_build/ci_build.sh PI  tensorflow/tools/ci_build/pi/build_raspberry_pi.sh`
3. see the error below

I found following issue but downgrading bazel to 0.19.2 didn't help: https://github.com/tensorflow/tensorflow/issues/24124

Another issue: from build log I see that armv6 was used to build BLAS, but I would expect armv7 instead for RPi 3, and tensorflow/tools/ci_build/pi/build_raspberry_pi.sh should use it. What's going on?

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
 OpenBLAS build complete. (BLAS CBLAS)

  OS               ... Linux             
  Architecture     ... arm               
  BINARY           ... 32bit                 
  C compiler       ... GCC  (command line : /tmp/toolchain_install//tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc)
  Library Name     ... libopenblas_armv6p-r0.3.1.dev.a (Multi threaded; Max num-threads is 4)

To install the library, you can run "make PREFIX=/path/to/your/installation install".

make -j 4 -f Makefile.install install
make[1]: Entering directory `/tmp/openblas_src'
Generating openblas_config.h in /tmp/openblas_install//include
Generating f77blas.h in /tmp/openblas_install//include
Generating cblas.h in /tmp/openblas_install//include
Copying the static library to /tmp/openblas_install//lib
Copying the shared library to /tmp/openblas_install//lib
Generating openblas.pc in /tmp/openblas_install//lib/pkgconfig
Generating OpenBLASConfig.cmake in /tmp/openblas_install//lib/cmake/openblas
Generating OpenBLASConfigVersion.cmake in /tmp/openblas_install//lib/cmake/openblas
Install OK!
make[1]: Leaving directory `/tmp/openblas_src'
Building for the Pi Two/Three, with NEON acceleration
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: f1dbc59c-324c-431f-b0eb-408f1a81c125
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
ERROR: cc_toolchain_suite '@local_config_arm_compiler//:toolchain' does not contain a toolchain for CPU 'armeabi', you may want to add an entry for 'armeabi|compiler' into toolchains and toolchain_identifier 'arm-linux-gnueabihf' into the corresponding cc_toolchain rule (see --incompatible_disable_cc_toolchain_label_from_crosstool_proto).
```

```
$ docker --version
Docker version 18.04.0-ce, build 3d479c0af6
```

**Comment by anilknayak** [comment]
Just curious
After we build the wheel. Does it install libtensorflow.so shared libs?

**Comment by mixaz** [comment]
@anilknayak are you sure it is the same error? We have different error messages, and yours  seems to be related to #24104. Seems that the issue was caused by bazel 0.20, downgrading to 0.19 shall help

Anybody can close this issue? Just I'm building with tensorflow-on-arm and testing if master head builds will take some time...

**Comment by anilknayak** [comment]
I am able to build libtensorflow.so for raspberry pi. I have summarized my approach after searching some issue in github tensorflow. Check otu the stackoverflow link and vote 

https://stackoverflow.com/questions/53874017/error-while-building-libtensorflow-so-on-raspberry-pi/54204267#54204267

**Comment by mixaz** [comment]
Tested - RPi libraries are built OK on the latest HEAD. Closing the ticket.
