### ISSUE TITLE
Ability to Profile Estimators

### ISSUE THREAD

**Issue by jaderabbit** [tensorflow/tensorflow#24428]
**System information**
- TensorFlow version (you are using): 1.12.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

There seems to be no straight-forward way to profile an `Estimator`. As an ML practitioner, being able to check the speed of predictions on a given architecture is *vital*.

**Will this change the current api? How?**

Yes. 

I'd imagine the `estimator.RunConfig` object would take an optional reference to a `tensorflow.RunMetadata` object? I'm not an expert on the way profiling works in tf, so any guidance would be appreciated 

**Who will benefit with this feature?**

Any ML practitioner (which is who the Estimator API was written for, as I understand) will benefit by being able to profile the speed and memory requirements of Estimators on different hardware. This will aid them selecting given architecture over another and determining whether use of a particular model is feasible for throughput requirements. 

**Any Other info.**

**Comment by jnd77** [comment]
I use the ProfilerHook in the following way:
```
hooks = [tf.train.ProfilerHook(save_steps=1, output_dir=model_dir)]
estimator.train(..., hooks=hooks)
```
Can also use with evaluate and predict.
This generates some json files you can visualize with Chrome on chrome://tracing/

**Comment by jaderabbit** [comment]
Thanks! I see there are hooks for the `estimator.predict` too.

**Comment by yacineDZ44** [comment]
Hi ,
I tried the method given by @jnd77  with  predict ,but it give the same error as [https://stackoverflow.com/questions/53828373/profiling-tensorflow-estimators](url)
Is there any solution?

**Comment by smr97** [comment]
> I use the ProfilerHook in the following way:
> 
> ```
> hooks = [tf.train.ProfilerHook(save_steps=1, output_dir=model_dir)]
> estimator.train(..., hooks=hooks)
> ```
> 
> Can also use with evaluate and predict.
> This generates some json files you can visualize with Chrome on chrome://tracing/

Hey, I am able to generate the traces like this, but the program terminates with a ValueError saying that the given tag was already used for this event type (before this error isgt. This happens only when I pass the hook in estimator.eval(), works fine with train. 

What I really wanted was to generate tensorboard visualisation and the traces with the same code, but if I add the hook, then the tensorboard visualisation is not generated due to the above error.

Finally (not related to the above problem), I am not sure if this is even possible, but can we see these times inside of the tensorboard visualisation? If I add this hook in training, I see the time, but that is somehow a cumulative wall-time stamp, and not a per node run-time measure.

**Comment by buracagyang** [comment]
> > I use the ProfilerHook in the following way:
> > ```
> > hooks = [tf.train.ProfilerHook(save_steps=1, output_dir=model_dir)]
> > estimator.train(..., hooks=hooks)
> > ```
> > 
> > 
> > Can also use with evaluate and predict.
> > This generates some json files you can visualize with Chrome on chrome://tracing/
> 
> Hey, I am able to generate the traces like this, but the program terminates with a ValueError saying that the given tag was already used for this event type (the trace is already written before this exception is raised, so I am able to view the trace). This happens only when I pass the hook in estimator.eval(), works fine with train.
> 
> What I really wanted was to generate tensorboard visualisation and the traces with the same code, but if I add the hook, then the tensorboard visualisation is not generated due to the above error.
> 
> Finally (not related to the above problem), I am not sure if this is even possible, but can we see these times inside of the tensorboard visualisation? If I add this hook in training, I see the time, but that is somehow a cumulative wall-time stamp, and not a per node run-time measure.

It worked user with train.But when i use with evaluate and predict,like this:
```
hooks = [tf.train.ProfilerHook(save_steps=1, output_dir=model_dir)] 
estimator.predict(..., hooks=hooks)
estimator.evaluate(..., hooks=hooks)
```

raise ValueError
ValueError: The provided tag was already used for this event type

**Comment by smr97** [comment]
@buracagyang , I got no help on this, so I decided to use a hook I found somewhere on SO (it has been a while, I don't remember who posted it originally). The error seems to be valid, there is indeed some issue with updating the run tag in eval mode. Anyway, the custom hook worked and produced the traces during training and eval both. Here is the code for the hook:

```python
 817 class MetadataHook(SessionRunHook):
 818     def __init__(self, save_steps=None, save_secs=None, output_dir=""):
 819         self._output_tag = "blah-{}"
 820         self._output_dir = output_dir
 821         self._timer = SecondOrStepTimer(every_secs=save_secs,
 822                                         every_steps=save_steps)
 823         self._atomic_counter = 0
 824 
 825     def begin(self):
 826         self._next_step = None
 827         self._global_step_tensor = training_util.get_global_step()
 828         self._writer = tf.summary.FileWriter(self._output_dir,
 829                                              tf.get_default_graph())
 830 
 831         if self._global_step_tensor is None:
 832             raise RuntimeError(
 833                 "Global step should be created to use ProfilerHook.")
 834 
 835     def before_run(self, run_context):
 836         self._request_summary = (self._next_step is None
 837                                  or self._timer.should_trigger_for_step(
 838                                      self._next_step))
 839         requests = {}#{"global_step": self._global_step_tensor}
 840         opts = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
 841         return SessionRunArgs(requests, options=opts)
 842 
 843     def after_run(self, run_context, run_values):
 844         global_step = self._atomic_counter + 1
 845         self._atomic_counter = self._atomic_counter + 1
 846         if self._request_summary:
 847             tf.logging.error(f'global step is {global_step}, atomic counter is {self._atomic_counter}')
 848             fetched_timeline = timeline.Timeline(run_values.run_metadata.step_stats)
 849             chrome_trace = fetched_timeline.generate_chrome_trace_format()
 850             with open(os.path.join(self._output_dir, f'timeline_{global_step}.json'), 'w') as f:
 851                 f.write(chrome_trace)
 852 
 853             self._writer.add_run_metadata(run_values.run_metadata,
 854                                           self._output_tag.format(global_step))
 855             self._writer.flush()
 856         self._next_step = global_step + 1
 857 
 858     def end(self, session):
 859         self._writer.close()
 860 
```
Then you need to plug this into the `eval` call which is simple:
```python
1146             result = estimator.evaluate(input_fn=eval_input_fn,
1147                                         steps=eval_steps,
1148                                         hooks=[
1149                                             #profile_hook
1150                                             MetadataHook(
1151                                                 save_steps=1,
1152                                                 output_dir=FLAGS.output_dir)
1153                                         ])
```
Sorry for the line numbers, it is copy-pasted from vim. This might work with only specific TF versions. I think I tried it with TF1.14 the last time.

Hope this helps! 

Also, while we are on the topic of profiling, I have some questions about the GPU time-trace. I am not sure how to interpret the run-time measurements of the kernels. The profile under `*/GPU/compute:0` is the real kernel run-time or is it just the time taken to schedule the kernel? 
Furthermore, for a sequential network, this would not matter, right? I mean, you can not schedule the matmul kernels for layer `i` unless and until layer `i-1` has finished doing it's matmul. So, unless there are gaps in this timeline (which there aren't), this should be interpreted as the wall-time taken to run the data through this layer, correct?

**Comment by buracagyang** [comment]
@smr97

**Comment by buracagyang** [comment]
@smr97 
Hi, I've tried the method you gave in the code, and it works! Thank you very much!
