### ISSUE TITLE
ImportError: cannot import name grid_rnn

### ISSUE THREAD

**Issue by arita37** [tensorflow/tensorflow#2443]
Docker - Tensor Flow Latest 

### Steps to reproduce
When typing:    from tensorflow.contrib import grid_rnn

i have this message:
ImportError: cannot import name grid_rnn

How can download the contrib part into tensorFlow Docker (in windows) ?

Thanks

**Comment by mrry** [comment]
`tf.contrib.grid_rnn` is only available in the nightly builds of TensorFlow (and it will be in version 0.9).  We don't currently publish nightly docker images, but you can modify the [`Dockerfile`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile) by replacing these lines:

```
# Install TensorFlow CPU version.
ENV TENSORFLOW_VERSION 0.8.0
RUN pip --no-cache-dir install \
    http://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-${TENSORFLOW_VERSION}-cp27-none-linux_x86_64.whl
```

...with:

```
# Install TensorFlow CPU version.
RUN pip --no-cache-dir install \
    http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_CONTAINER_TYPE=CPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
```

Follow the Docker instructions for [building a new image on Windows](https://docs.docker.com/windows/step_four/) to complete the process.

**Comment by arita37** [comment]
I am using this command to download tensorflow....
docker run -it b.gcr.io/tensorflow/tensorflow
I cannot change the docker file on tensorflow side....

What command should I use to install a local dockerfile ?


Thanks, regards

**Comment by mrry** [comment]
Here's a step-by-step tutorial for using Docker on Windows with a custom Dockerfile:

https://docs.docker.com/windows/step_four/

**Comment by arita37** [comment]
ok, But, I got this message when builiding the docker:

Step 7 : COPY jupyter_notebook_config.py /root/.jupyter/
lstat jupyter_notebook_config.py: no such file or directory
