### ISSUE TITLE
tf.nn.depthwise_conv2d issue with float16 => nan output

### ISSUE THREAD

**Issue by lgeo3** [tensorflow/tensorflow#24430]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary (using docker image tensorflow/tensorflow:1.12.0-gpu)
- TensorFlow version (use command below):  ('v1.12.0-0-ga6d8ffae09', '1.12.0')
- Python version: 2.7.12
- CUDA/cuDNN version: cuda 9.0, cudnn 7.2.1
- GPU model and memory: nvidia Tesla V100-DGXS-16GB

**Describe the current behavior**
tf.nn.depthwise_conv2d_native returns nan when used with float16. Multiple call to same sess.run(op) return different results.

**Describe the expected behavior**
No nan in the output. Similar value when running same op multiple times.

**Code to reproduce the issue**

```
import numpy as np
import tensorflow as tf

with tf.Session() as sess:
    tf_input1 = tf.ones(shape=[1, 22, 28, 28], dtype=tf.float16) / 5.0
    tf_input2 = tf.ones(shape=[7, 7, 22, 1], dtype=tf.float16) / 10.0

    mat = tf.random.uniform( [4096,4096], minval=0, maxval=None, dtype=tf.float16, seed=0, name=None)
    res_mat = tf.matmul(mat, mat)
    #res_mat = tf.no_op()  # un-comment this line and the issue dissapears

    sess.run(res_mat)
    res = tf.nn.depthwise_conv2d_native(tf_input1, tf_input2, strides=[1, 1, 1, 1], padding="SAME", data_format='NCHW')
    v1 = sess.run(res)
    sess.run(res_mat)

    v2 = sess.run(res)
    if np.isnan(v2).any():
       print("issue: nan detected")
    np.testing.assert_equal(v1, v2)
```

**Other info / logs**

Issue occurs only on nvidia hardward that support float16 operation (on cpu no issue)
replacing res_mat with tf.no_op() => v1 and v2 are equal without nan
Using float32 => no nan

In my understanding the float16 version of the op does not reinitialized some buffer content.

**Comment by harshini-gadige** [comment]
kjhl

**Comment by angersson** [comment]
@jvishnuvardhan, I'm not familiar with the inner workings of this function. Can you find someone more knowledgeable to check it out, please?

**Comment by gunan** [comment]
similar, I cannot really comment on this. Please reroute.

**Comment by jvishnuvardhan** [comment]
@laurent-george This bug is not related tensorflow. Could you ask it in nvidia community forum? Thanks!
I am closing this as it is better to ask elsewhere and also it is not related to tensorflow. Thanks!

**Comment by reedwm** [comment]
Assigning to @chsigg, as I am not familiar with the depthwise conv code.

**Comment by sanjoy** [comment]
@lgeo3 Your reproducer seems to work fine with 1.14 so I suspect this has already been fixed.  I'll speculatively close this issue for now, but please reopen if there is something more to do here.
