### ISSUE TITLE
TypeError: Can't convert Operation 'MutableHashTable' to Tensor

### ISSUE THREAD

**Issue by chunyang-wen** [tensorflow/tensorflow#24439]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): No
- TensorFlow version (use command below): 1.8.0
- Python version: 3.6.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

meta graph exported by export_meta_graph cannot be imported by import_meta_graph

**Describe the expected behavior**

export_meta_graph and import_meta_graph works.

**Code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow.contrib.lookup.lookup_ops import MutableHashTable
from tensorflow.contrib.lookup.lookup_ops import MutableDenseHashTable

export_dir = 'minimal_saved_model'
#builder = tf.saved_model.builder.SavedModelBuilder(export_dir)

with tf.Session(graph=tf.Graph()) as sess:

    #table = MutableDenseHashTable(key_dtype=tf.int64, \
    # value_dtype=tf.int64, default_value=-1, empty_key=0)
    table = MutableHashTable(key_dtype=tf.int64, value_dtype=tf.int64, default_value=-1)
    aa = tf.get_variable('xxx', shape=(3,))

    meta = tf.train.export_meta_graph()
    saver = tf.train.Saver()


with tf.Session(graph=tf.Graph()) as sess1:
    tf.train.import_meta_graph(meta)
```
**Other info / logs**
related to #11888 . It seems that SaveableObject is not recreated correctly.

stack traces:

```python
  File "minimal_case.py", line 22, in <module>
    tf.train.import_meta_graph(meta)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1970, in import_meta_graph
    return Saver()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1338, in __init__
    self.build()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 813, in _build_internal
    saveables = self._ValidateAndSliceInputs(names_to_saveables)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 661, in _ValidateAndSliceInputs
    names_to_saveables = BaseSaverBuilder.OpListToDict(names_to_saveables)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 629, in OpListToDict
    var = ops.internal_convert_to_tensor(var, as_ref=True)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 6130, in _operation_conversion_error
    name, as_ref))
TypeError: Can't convert Operation 'MutableHashTable' to Tensor (target dtype=None, name=None, as_ref=True)
```

**Comment by kkzheng** [comment]
saver = tf.train.Saver()
meta = tf.train.export_meta_graph(saver_def=saver.as_saver_def())

**Comment by bhack** [comment]
I think we could close this. Also we don't support TF 1.x anymore.

**Comment by kkzheng** [comment]
Hello, i got the same problem. Did you have a solution?

**Comment by chunyang-wen** [comment]
> Hello, i got the same problem. Did you have a solution?

@kkzheng Not yet. But I think what you can do it to replace `import_meta_graph` call by yourself. I encounter the problem when I try to import and export again in order to manipulate the graph. Finally, I gave it up.

**Comment by mohantym** [comment]
I replicated this problem using compatibility mode in [2.8](https://colab.sandbox.google.com/gist/mohantym/26ff856cd8771e5a1370306c25542ccc/github_24439.ipynb#scrollTo=x-Fthhl55aHo).

**Comment by bhack** [comment]
The problem is that we don't have an import test for `MutableHashTable` but only for `StaticHashTable`:
https://github.com/tensorflow/tensorflow/blob/480dd2f0f7dbd6da754b714925f7f4623472ad89/tensorflow/python/kernel_tests/data_structures/lookup_ops_test.py#L413-L431

**Comment by bhack** [comment]
Now it is covered by an expected failing test https://github.com/tensorflow/tensorflow/pull/55200 that we could merge.

We could investigate later how to fix it and collect some hints from the internal team on what kind of PR they want.

**Comment by bhack** [comment]
This is now covered by an expected failing test. 
To contribute this feature with a PR a contributor will need to write the code and pass this test removing the `@unittest.expectedFailure` decorator.

https://github.com/tensorflow/tensorflow/blob/3cb23b56712d2e85e0a97c58cac771dcf40ca7cb/tensorflow/python/kernel_tests/data_structures/lookup_ops_test.py#L3358-L3381

@mihaimaruseac @theadactyl @yarri-oss  Do you think that we could use a special label other the eventually `stat:contributions welcome` when we have a ticket covered by an expected failing test like e.g `stat:test_covered`?
Cause I think It could be really useful for two main goals:
- to set a potential preference on contributing a PR cause we have already a specific that it needs to pass.
- for the @tensorflow/dev-support to not periodically go  to manually check an often not "minimized" gist on Colab against nightly and new  TF releases to verify that the bug/FR wasn't "silently" solved.

**Comment by bhack** [comment]
Can we introduce this specific label for test covered contribution?
@MichaelHudgins @rishikasinha-tf @learning-to-play 

/cc @mihaimaruseac

**Comment by sushreebarsa** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow version with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release](https://github.com/tensorflow/tensorflow/releases) notes to stay up to date with the latest developments which are happening in the Tensorflow space.
Thank you!
