### ISSUE TITLE
tf.contrib.copy_graph.copy_variable_to_graph does not set the shape of copied variable

### ISSUE THREAD

**Issue by EmanueleGhelfi** [tensorflow/tensorflow#24442]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Archlinux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.10
- Python version: 3.6
- CUDA/cuDNN version: cuda 9.0, cudnn 7.1
- GPU model and memory: GeForce GTX 1060

**Describe the current behavior**
Variables copied using tf.contrib.copy_graph.copy_variable_to_graph have unknown shape. This make this function unusable and useless. 

**Describe the expected behavior**
Variables copied using tf.contrib.copy_graph.copy_variable_to_graph should have the same shape of original variables in order to make possible restoring from a checkpoint.

**Code to reproduce the issue**
```python
import tensorflow as tf

x = tf.Variable((), name="x")

g = tf.get_default_graph()

g2 = tf.Graph()

with g2.as_default():
    x2 = tf.contrib.copy_graph.copy_variable_to_graph(x, g2)

print(x.get_shape()) # (0,)
print(x2.get_shape()) # <unknown>
```

**Fixing**
This issue is simply solved by changing lines: 
https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/contrib/copy_graph/python/util/copy_elements.py#L89-L96

to:
```python
  #Initialize the new variable
  with to_graph.as_default():
    new_var = Variable(
        init_value,
        trainable,
        name=new_name,
        collections=collections,
        validate_shape=True)
```

In my opinion there's no reason to set the field `validate_shape` to False, since in order to create the new variable we need to evaluate the old variable to get the init_value, so we have the actual shape of variables.

**Comment by alextp** [comment]
Can you send a pull request?

**Comment by EmanueleGhelfi** [comment]
Yes, I'll send a pull request in the next days.

**Comment by karthi0804** [comment]
Hi, Is this issue fixed in any recent releases?

**Comment by rthadur** [comment]
Contrib has been depreciated here in Tensorflow repo and moved to tensorflow/addons , please reopen the issue in https://github.com/tensorflow/addons/issues if this exists in latest version. Thank you
