### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.saved_model' has no attribute 'saved_keras_model'

### ISSUE THREAD

**Issue by AliceDinh** [tensorflow/tensorflow#24441]
**System information**
- TensorFlow version:1.9.0
- Doc Link: https://github.com/tensorflow/docs/blob/master/site/en/tutorials/keras/save_and_restore_models.ipynb

**Describe the documentation issue**
I followed the notebook and all okies until this line of code:
saved_model_path = tf.contrib.saved_model.save_keras_model(model, "./saved_models")
The error is: 
AttributeError: module 'tensorflow.contrib.saved_model' has no attribute 'saved_keras_model'

**Comment by ymodak** [comment]
You can try running the tutorial on google colab. For executing the script locally I would recommend upgrading your TensorFlow version.

**Comment by AliceDinh** [comment]
Thanks @ymodak, I made it.
