### ISSUE TITLE
How to export eager model as graph, and how to restore object-based checkpoint which generate by eager mode from estimator

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#24443]
How to export eager model as graph, and how to restore object-based checkpoint which generate by eager mode from estimator

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
