### ISSUE TITLE
Tensorflow crashes when trying to feed > 2GiB to TPU

### ISSUE THREAD

**Issue by Keno** [tensorflow/tensorflow#24459]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu Linux 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12
- Python version: N/A
- Bazel version (if compiling from source): Bazel 0.20.0
- GCC/Compiler version (if compiling from source): 7.2.0
- CUDA/cuDNN version: N/A
- GPU model and memory: Cloud TPU

**Describe the current behavior**

I'm trying to feed a cloud TPU (v3) some data. However, whenever the total feed size goes above 2GiB, I get the following crash inside libtensorflow:

```
E1220 02:28:43.129226740   14451 proto_buffer_writer.h:83]   assertion failed: byte_count_ < total_size_

signal (6): Aborted
in expression starting at no file:0
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_ZN4grpc11CoreCodegen11assert_failEPKcS2_i at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow.so (unknown line)
_ZN4grpc17ProtoBufferWriter4NextEPPvPi at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow.so (unknown line)
_ZN6google8protobuf2io17CodedOutputStream7RefreshEv at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow_framework.so (unknown line)
_ZN6google8protobuf2io17CodedOutputStreamC2EPNS1_20ZeroCopyOutputStreamEb at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow_framework.so (unknown line)
_ZNK6google8protobuf11MessageLite25SerializeToZeroCopyStreamEPNS0_2io20ZeroCopyOutputStreamE at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow_framework.so (unknown line)
_ZN4grpc16GenericSerializeINS_17ProtoBufferWriterEN10tensorflow14RunStepRequestEEENS_6StatusERKN6google8protobuf7MessageEPNS_10ByteBufferEPb at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow.so (unknown line)
_ZN4grpc8internal21BlockingUnaryCallImplIN10tensorflow14RunStepRequestENS2_15RunStepResponseEEC1EPNS_16ChannelInterfaceERKNS0_9RpcMethodEPNS_13ClientContextERKS3_PS4_ at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow.so (unknown line)
_ZN10tensorflow4grpc13MasterService4Stub7RunStepEPN4grpc13ClientContextERKNS_14RunStepRequestEPNS_15RunStepResponseE at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow.so (unknown line)
_ZN10tensorflow16GrpcRemoteMaster7RunStepEPNS_11CallOptionsEPNS_21RunStepRequestWrapperEPNS_29MutableRunStepResponseWrapperE at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow.so (unknown line)
_ZN10tensorflow11GrpcSession8RunProtoEPNS_11CallOptionsEPNS_28MutableRunStepRequestWrapperEPNS_29MutableRunStepResponseWrapperE at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow.so (unknown line)
_ZN10tensorflow11GrpcSession9RunHelperERKNS_10RunOptionsERKSt6vectorISt4pairISsNS_6TensorEESaIS7_EERKS4_ISsSaISsEESF_PS4_IS6_SaIS6_EEPNS_11RunMetadataERKSs at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow.so (unknown line)
_ZN10tensorflow11GrpcSession3RunERKNS_10RunOptionsERKSt6vectorISt4pairISsNS_6TensorEESaIS7_EERKS4_ISsSaISsEESF_PS4_IS6_SaIS6_EEPNS_11RunMetadataE at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow.so (unknown line)
_ZL13TF_Run_HelperPN10tensorflow7SessionEPKcPK9TF_BufferRKSt6vectorISt4pairISsNS_6TensorEESaISA_EERKS7_ISsSaISsEEPP9TF_TensorSI_PS4_P9TF_Status at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow.so (unknown line)
TF_SessionRun at /home/keno/.julia/packages/TensorFlow/YWnga/src/../deps/usr/lib/libtensorflow.so (unknown line)
```

**Describe the expected behavior**

Ideally it should work (after all there's 128GiB of HBM on the other side of this pipe so 2GiB is really not unreasonable here), worst case I'd have expected an error status to be returned rather than a hard assert.

**Code to reproduce the issue**

Any code that passes feeds totaling > 2GiB to TF_SessionRun connected over a grpc connection. In this particular example, I was trying to use the `InfeedEnqueueTuple` op (with the inputs being placeholders that I'm feeding).

**Comment by saeta** [comment]
Hey @Keno , I think you're running into the 2 GiB proto-size limit. (Proto sizes are `int32`'s, and so you're starting to overflow the proto headers.) Unfortunately, for reasons, this is unlikely to be switched either to a `uint32` or an `int64`.

**Comment by Keno** [comment]
Could tensorflow somehow chunk the message across multiple protos or at least give me a nicer error message here? Killing the entire client and all its state seems a bit drastic.

**Comment by mhwalker** [comment]
@Keno, Did you ever find a solution / workaround to this issue? Having the same problem.

**Comment by bamine** [comment]
Running into the same issue :S any news ?

**Comment by maxima120** [comment]
have the same. it did work in TF 1.3 .. so i am not sure where these proto bufs are coming from.. whats the solution?
