### ISSUE TITLE
Problem on bazel building target with GPU support(Ubuntu16.04)

### ISSUE THREAD

**Issue by SoarAnyway** [tensorflow/tensorflow#24460]
>>bazel build --config=opt --config=cuda tensorflow/tools/pip_package:build_pi
p_package:
DEBUG: /home/ubuntu/.cache/bazel/_bazel_ubuntu/712f0e98e13675fc83790945ec267f95/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
ERROR: cc_toolchain_suite '@local_config_cuda//crosstool:toolchain' does not contain a toolchain for CPU 'k8', you may want to add an entry for 'local|compiler' into toolchains and toolchain_identifier 'local_linux' into the corresponding cc_toolchain rule (see --incompatible_disable_cc_toolchain_label_from_crosstool_proto).
INFO: Elapsed time: 0.181s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by iweigele** [comment]
I had this problem with bazel-0.18.0. Try 0.19.0 instead.

**Comment by SoarAnyway** [comment]
@iweigele Thank you, I try bazel-0.19.2,this problem is sloved but new problem arise...

ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@icu//': java.io.IOException: thread interrupted

Do u know how to deal?

**Comment by iweigele** [comment]
No, sorry. I haven't seen that one.  I will post back if I come across something helpful though.

**Comment by ymodak** [comment]
Can you please provide following information? Thanks!
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:



**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Comment by SoarAnyway** [comment]
@ymodak 
System information：

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
TensorFlow installed from (source or binary): source
TensorFlow version:1.12.0
Python version:3.6.5
Installed using virtualenv? pip? conda?: pip
Bazel version (if compiling from source):19.2
GCC/Compiler version (if compiling from source):5.4.0
CUDA/cuDNN version: cuda10.0/cuDNN v7.4.1
GPU model and memory: 12G per GPU

**Comment by ymodak** [comment]
Apologies for the delay in response. TensorFlow 2.0 will officially support cuda 10, for TF 1.12 cuda 9 is supported. Can you please switch to cuda 9 and try again? Thanks!

**Comment by ymodak** [comment]
TensorFlow 1.13.0-rc0 is released and comes with GPU binaries built against CUDA 10.
You can give it a try. Thanks!
