### ISSUE TITLE
Unexpected result for tf.sqrt under certain conditions

### ISSUE THREAD

**Issue by rvinas** [tensorflow/tensorflow#24465]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave 10.14.1
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.12.0
- Python version: 3.6

**Describe the current behavior**

The output `a_sqrt_1` of [tf.sqrt](https://www.tensorflow.org/api_docs/python/tf/math/sqrt) in the provided snippet is incorrect. Concretely, when `a` is a [tf.Variable](https://www.tensorflow.org/api_docs/python/tf/Variable) and `a_sqrt` is run together with `a_scaled`, the output `a_sqrt_1` is `a_sqrt_2 ** -1`.

**Describe the expected behavior**
The expected result is `a_sqrt_2`.

**Code to reproduce the issue**
```
import tensorflow as tf

x = 100.0
a = tf.Variable(x)
# a = tf.constant(x)  # Interestingly, it works when `a` is a constant
a_sqrt = tf.sqrt(a)
a_scaled = a / a_sqrt


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    a_sqrt_1, _ = sess.run([a_sqrt, a_scaled])
    print(a_sqrt_1)  # prints 0.1  (!!!)

    a_sqrt_2 = sess.run(a_sqrt)
    print(a_sqrt_2)  # prints 10.0
```

**Comment by ppwwyyxx** [comment]
Tested with nightly tensorflow, the code produces the correct output.
Similar to #23196.
