### ISSUE TITLE
num_examples issue

### ISSUE THREAD

**Issue by ElmiiiRaa** [tensorflow/tensorflow#24473]
For the value of num_examples, what value should we get from the original value? When the amount we get is close to the total number of data.
   Has anyone solved this problem?
 the errors:
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by ElmiiiRaa** [comment]
i think the value  depend's on code ....
