### ISSUE TITLE
How to build from source with hdfs support on. No option in configure?

### ISSUE THREAD

**Issue by legatoo** [tensorflow/tensorflow#24474]
**System information**
- OS Platform and Distribution: Mac OS Mojave 10.14.1 (18B75)
- TensorFlow installed from (source or binary): source
- TensorFlow version: branch r1.12
- Python version: 3.6.6 
- Installed using virtualenv? pip? conda?: building is in a virtualenv created by `pyenv virtualenv 3.6.6 my_tf_build_env`
- Bazel version (if compiling from source): from source. 0.15.0
- GCC/Compiler version (if compiling from source): Apple LLVM version 10.0.0 (clang-1000.11.45.5)
- CUDA/cuDNN version:  no cuda, build only for cpu
- GPU model and memory: Intel Core i7, 16 GB

**Describe the problem**
When I reading threcord in my local hdfs, I encounter error below:

```
  File "/Users/eva/.pyenv/versions/pycharm_v3.6.6/lib/python3.6/site-packages/tensorflow/python/ops/io_ops.py", line 166, in read
    return gen_io_ops.reader_read_v2(self._reader_ref, queue_ref, name=name)
  File "/Users/eva/.pyenv/versions/pycharm_v3.6.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 944, in reader_read_v2
    queue_handle=queue_handle, name=name)
  File "/Users/eva/.pyenv/versions/pycharm_v3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/eva/.pyenv/versions/pycharm_v3.6.6/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/Users/eva/.pyenv/versions/pycharm_v3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/Users/eva/.pyenv/versions/pycharm_v3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): dlopen(libhdfs.dylib, 6): image not found
```
I fallowed [this guide](https://www.tensorflow.org/deploy/hadoop) to set hadoop pathes, and I'm sure my `libhdfs.dylib` is in my `HADOOP_HDFS_HOME`. (I build hadoop natively for mac)

I'm not sure if my tensorflow, which is installed via brew, is hdfs enabled. So I just want to build from source with hdfs enable, but when I run `./configure`, there is no option for hdfs?  My questions are:

1/ is the tensorflow shipped via brew hdfs enabled?
2/ how to build from source with hdfs turn on?

**Comment by jhseu** [comment]
HDFS is already enabled in your installation, otherwise it wouldn't attempt to open the libhdfs.dylib file. I would suggest checking your HDFS installation to see if it's standard. It's possible libhdfs has other dependencies that aren't able to be loaded. macOS lib search paths are weird.

Normally, libhdfs.dylib is supposed to be under $HADOOP_HDFS_HOME/lib/native, but we do attempt to load it from $HADOOP_HDFS_HOME.

**Comment by legatoo** [comment]
I don't know if the hdfs lib is loaded now, because the problem is now changed to `No Java runtime present, requesting install.`. Below is my settings:

![image](https://user-images.githubusercontent.com/1506580/50326480-95ffaa00-0525-11e9-8b18-22ea750b6b96.png)

the code is simple , I just want to read some tfrecord out from local hdfs:
```
import tensorflow as tf
tf.enable_eager_execution()

filenames = ["hdfs://localhost:8020/dataset/training/eval.tfrecord"]
dataset = tf.data.TFRecordDataset(filenames)
value = dataset.make_one_shot_iterator().get_next()

sess = tf.Session()
sess.run(value)
```

I build tensorflow with `--march=native`.
Thank you so much.

**Comment by legatoo** [comment]
I find something else.
1/ for mac, it should be `DYLD_LIBRARY_PATH`, not `LD_LIBRARY_PATH`
2/ it seems using `DYLD_LIBRARY_PATH` to define shared libraries is not the best options. I dont know how dynamic linker works in mac os, but somehow `libjvm.dylib` and `libhdfs.dylib` can not exist at the same time. 

- When I remove `libhdfs.dylib` from `DYLD_LIBRARY_PATH`, error msg is `Error dlopen(hdfs)`, (but at least no jvm issue);
- When I remove `libjvm.dylib` from `DYLD_LIBRARY_PATH`, error msg is (absoluty) `No Java runtime present`;
- When I put them together, error msg still `No Java runtime present`;

**Comment by pranav-kohli** [comment]
I am having a similar issue on mac.
I built hadoop on mac and copied libhdfs.dylib to the HDFS_HOME/lib/native path.
Unfortunately even after that i am getting the below error

```
File "/datarpm/agent/miniconda3/envs/dask-distributed/lib/python3.6/site-packages/tensorflow/python/lib/io/tf_record.py", line 210, in __init__
    compat.as_bytes(path), options._as_record_writer_options(), status)
  File "/datarpm/agent/miniconda3/envs/dask-distributed/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Unknown error: 255
```

I am using the below code to write a tfrecord to hdfs

```
data = {
            'Age': 29,
            'Movie': ['The Shawshank Redemption', 'Fight Club'],
            'Movie Ratings': [9.0, 9.7],
            'Suggestion': 'Inception',
            'Suggestion Purchased': 1.0,
            'Purchase Price': 9.99
        }
        example = tf.train.Example(features=tf.train.Features(feature={
            'Age': tf.train.Feature(
                int64_list=tf.train.Int64List(value=[data['Age']])),
            'Movie': tf.train.Feature(
                bytes_list=tf.train.BytesList(
                    value=[m.encode('utf-8') for m in data['Movie']])),
            'Movie Ratings': tf.train.Feature(
                float_list=tf.train.FloatList(value=data['Movie Ratings'])),
            'Suggestion': tf.train.Feature(
                bytes_list=tf.train.BytesList(
                    value=[data['Suggestion'].encode('utf-8')])),
            'Suggestion Purchased': tf.train.Feature(
                float_list=tf.train.FloatList(
                    value=[data['Suggestion Purchased']])),
            'Purchase Price': tf.train.Feature(
                float_list=tf.train.FloatList(value=[data['Purchase Price']]))
        }))
        with tf.python_io.TFRecordWriter('hdfs://localhost:8020/tmp/test/tf/customer_1.tfrecord') as writer:
            writer.write(example.SerializeToString())
```
Tensorflow version : 1.12.0

**Comment by kashyap-vinay** [comment]
Any update on the above issue related to JDK mismatch.??
Very hard to find why tensorflow jobs are asking for legacy java when accessing hdfs.

**Comment by dulm** [comment]
same problem with @pranav-kohli

**Comment by kashyap-vinay** [comment]
After a year long time, finally we have an update for the above issue.
Turned out to be the compatibility problem between libhdfs and java on Mac.
libhdfs on mac seems to create a mismatch with the java security policy.
 **Switching to OpenJdk solved the issue**.
Let me know if this helps..

**Comment by dylanwwang** [comment]
> 
> 
> same problem with @pranav-kohli

Have you solved the problem yet

**Comment by kumariko** [comment]
@legatoo We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. please check https://github.com/tensorflow/tensorflow/issues/24474#issuecomment-600544122 Thanks!
