### ISSUE TITLE
Can't build TF Model Lite Benchmark tool on Windows

### ISSUE THREAD

**Issue by stakemura** [tensorflow/tensorflow#24475]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 Pro 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:nightly build
- Python version:3.5
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):0.20.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Can't build TF Model Lite Benchmark tool on Windows.
This code seems to dispatch using PLATFORM_WINDOWS macro.
However PLATFORM_WINDOWS is not defined in the first place.
Why not use portable std::this_thread::sleep_for()?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel --output_base $(Build.BinariesDirectory) build -c opt //tensorflow/lite/tools/benchmark:benchmark_model

**Any other info / logs**

```
2018-12-20T15:02:11.7495615Z tensorflow/lite/tools/benchmark/benchmark_model.cc(41): error C3861: 'nanosleep': identifier not found
2018-12-20T15:02:11.7840550Z INFO: Elapsed time: 2.614s, Critical Path: 0.99s
2018-12-20T15:02:11.7840932Z INFO: 0 processes.
2018-12-20T15:02:11.7841202Z FAILED: Build did NOT complete successfully
```
For further information visit [our CI environment](https://dev.azure.com/mlops/build-tflite/_build/results?buildId=11)

**Comment by jdduke** [comment]
Thanks for flagging. We have several platforms that don't have std::thread support, so we can't use that path unconditionally. I'll send out a fix.
