### ISSUE TITLE
quantization aware training in InceptionV3

### ISSUE THREAD

**Issue by lynden7317** [tensorflow/tensorflow#24490]
Hi, 

In the Figure 7 of whitepaper (Quantizing deep convolutional networks for efficient inference 2018), you mentioned that after the "concat" op, the "fQ" op will be inserted. 

however, on the evaluation/training graph of quantized InceptionV3, the "fQ" op is not appear after the "concat" op. 

could you help me to explain this problem?

the version of our Tensorflow is based on v1.12
![insertquant](https://user-images.githubusercontent.com/21340280/50321399-b6226f80-050b-11e9-8913-19c4b935d7a6.png)

Thanks

**Comment by liyunlu0618** [comment]
The rewriter may not be able to handle all possible model architectures. Please take a look at post-training integer quantization if you want to quantize InceptionV3:
https://medium.com/tensorflow/tensorflow-model-optimization-toolkit-post-training-integer-quantization-b4964a1ea9ba
