### ISSUE TITLE
from tensorflow.python.data import Dataset  ModuleNotFoundError: No module named 'tensorflow.python.data'

### ISSUE THREAD

**Issue by Auroratan** [tensorflow/tensorflow#24494]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (windows 10):
- TensorFlow installed from (source or binary):
- TensorFlow version (cpu 1.2.1):
- Python version: 3.6.2

--------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-77-256f8ffc6dfe> in <module>()
----> 1 from tensorflow.python.data import Dataset

ModuleNotFoundError: No module named 'tensorflow.python.data'

**Comment by jvishnuvardhan** [comment]
@Auroratan 
Please provide part of the code which is throwing error. 
Please try import tensorflow.data.Dataset(). Let me know what you get. thanks

**Comment by Auroratan** [comment]
@jvishnuvardhan 
Thank you for your help！ I know my mistake, because the version of tensorflow is 1.2, it is a version problem, I used conda install tensorflow=1.12.0 to solve my problem.

**Comment by jvishnuvardhan** [comment]
@Auroratan Thanks. I will close this.
