### ISSUE TITLE
Cannot convert custom .pb file to .tflite file 

### ISSUE THREAD

**Issue by jieni0615** [tensorflow/tensorflow#24491]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  macOS Mojave, version 10.14.2
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12.0
- **Python version**: 3.6.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

### Describe the problem

I have a custom model pre-trained in Pytorch framework. I have converted it to ONNX model, and then to TensorFlow model, so that it can be further converted to TensorFlow Lite model for deployment on mobile devices. 

I used the tflite_convert command for the conversion,

tflite_convert\
 --graph_def_file=model.pb \
 --output_file=model.lite \
 --input_format=TENSORFLOW_GRAPH \
 --output_format=TFLITE \
 --input_arrays=0 \
 --output_arrays=add_51 \

Yet I got the following error message:

Traceback (most recent call last):
  File "/miniconda3/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/miniconda3/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 412, in main app.run(main=run_main, argv=sys.argv[:1])
  File "/miniconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/miniconda3/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 408, in run_main _convert_model(tflite_flags)
  File "/miniconda3/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 162, in _convert_model output_data = converter.convert()
  File "/miniconda3/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 453, in convert **converter_kwargs)
  File "/miniconda3/lib/python3.6/site-packages/tensorflow/contrib/lite/python/convert.py", line 342, in toco_convert_impl input_data.SerializeToString())
  File "/miniconda3/lib/python3.6/site-packages/tensorflow/contrib/lite/python/convert.py", line 135, in toco_convert_protos(stdout, stderr))

RuntimeError: TOCO failed see console for info.
b"2018-12-20 17:44:31.127219: F tensorflow/contrib/lite/toco/import_tensorflow.cc:2137] Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'\n"
None

The custom pre-trained model is adapted from a Pytorch ResNet model. Therefore I also evaluated converting the ResNet model from the torchvision package to TensorFlow model through the ONNX framework, and further to TensorFlow Lite model. And I got the following error message:

Converting unsupported operation: PyFunc\n2018-12-20 18:09:03.357810: F tensorflow/contrib/lite/toco/import_tensorflow.cc:112] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)\n'
None

I wonder if the errors above were due to some unsupported operators from the model, probably caused from converting Pytorch model to TensorFlow model through the ONNX framework. As I can convert the pre-trained Mobilenet model (https://www.tensorflow.org/lite/models) to tflite model without error on my platform. Thanks.

**Comment by gitman88** [comment]
How did you do this? I created a new conda environment and installed with pip the tf-nightly CPU, but the error is the same: "Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'
Fatal Python error: Aborted". Did you call tflite_convert in some other way?

**Comment by KeremTurgutlu** [comment]
I am getting the same error even when switching from Tensorflow GPU to CPU.

**Comment by migi251** [comment]
> I am getting the same error even when switching from Tensorflow GPU to CPU.

Can you fix it?

**Comment by KeremTurgutlu** [comment]
> Can you fix it?

One fix for dimension mismatch is to have a model like this:

`class Model(nn.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model
    def forward(self,x):
        return self.model(x.permute(0,3,1,2))`

This time I am still having :

`ConverterError: TOCO failed. See console for info.
2019-04-03 14:06:45.559722: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: PyFunc
2019-04-03 14:06:45.571306: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)`

**Comment by DarnelleF** [comment]
Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'\n"

i am using tensorflow 1.12.0 ( ive tried nightly )
i am using cuda* as device ( which is cpu)
and still get this i cant seem to find out how to solve this where do i state that i want nhwc

**Comment by hamlatzis** [comment]
I;ve created a tensorflow mode of my own with custom operator and when I'm trying to convert it to lite I get something similar like it doesn't find my custom operation (MyAdd)

I've tried both command line utilities tflite_convert & toco (with same error): 

tflite_convert --output_file lite_version_model.tflite --saved_model_dir ./SavedModel --output_format TFLITE --allow_custom_ops

toco --output_file lite_model_version.tflite --saved_model_dir ./SavedModel --output_format=TFLITE

**Comment by jayasriospl** [comment]
I am trying to convert .pb to .tflite using ssd mobilenet v1 pets config.
Create .pb file using this command
sudo python export_inference_graph.py --input_type image_tensor --pipeline_config_path /home/ubuntu/training/data/ssd_mobilenet_v1_pets.config --trained_checkpoint_prefix /home/ubuntu/training/data/model.ckpt-78386 --output_directory /home/ubuntu/training/ --input_shape 1,300,300,3
then summarize the frozen_inference_graph.pb

its return this output
Found 1 possible inputs: (name=image_tensor, type=uint8(4), shape=[1,300,300,3])
No variables spotted.
Found 4 possible outputs: (name=detection_boxes, op=Identity) (name=detection_scores, op=Identity) (name=detection_classes, op=Identity) (name=num_detections, op=Identity)
Found 6130346 (6.13M) const parameters, 0 (0) variable parameters, and 187 control_edges
Op types used: 1781 Const, 255 GatherV2, 230 Identity, 224 Reshape, 207 Minimum, 164 Maximum, 116 Slice, 113 Cast, 103 Mul, 99 Sub, 95 ConcatV2, 88 Greater, 82 Where, 82 Split, 72 Add, 63 Pack, 63 StridedSlice, 50 Shape, 50 Unpack, 45 ExpandDims, 43 Squeeze, 41 ZerosLike, 41 NonMaxSuppressionV3, 39 Fill, 37 Tile, 35 Relu6, 35 FusedBatchNorm, 34 Conv2D, 33 RealDiv, 21 Switch, 16 Range, 13 DepthwiseConv2dNative, 12 BiasAdd, 6 Merge, 6 Sqrt, 3 Assert, 3 Equal, 3 Transpose, 2 Exp, 1 All, 1 TopKV2, 1 Size, 1 Sigmoid, 1 Placeholder
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=/home/jayasri/Downloads/ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18/original/frozen_inference_graph.pb --show_flops --input_layer=image_tensor --input_layer_type=uint8 --input_layer_shape=1,300,300,3 --output_layer=detection_boxes,detection_scores,detection_classes,num_detections

Then trying to convert tflite using bazel-bin/tensorflow/lite/toco/toco

But I got this error
tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-05-29 15:46:02.589145: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 2780 operators, 4997 arrays (0 quantized)
2019-05-29 15:46:02.794908: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 2741 operators, 4915 arrays (0 quantized)
2019-05-29 15:46:03.070306: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 2741 operators, 4915 arrays (0 quantized)
2019-05-29 15:46:03.162066: F tensorflow/lite/toco/graph_transformations/resolve_constant_slice.cc:59] Check failed: dim_size >= 1 (0 vs. 1)

Still i can't find the solution

**Comment by luzhen1412** [comment]
I also meet this problem: F tensorflow/lite/toco/import_tensorflow.cc:1994] Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'. I have tried tf-cpu, tf-gpu, tf-nightly-gpu, but I failed. Is there a solution? Thanks.

**Comment by DarnelleF** [comment]
sadly this forum is closed so expect no answers. ive had to put the small project i was working on on hold.

**Comment by Ahwar** [comment]
I have a question Can't The people who are working on tensorflow see these errors.
I have never seen any tensorflow team member commenting on these issues.
Obviously they have better knowledge about these issues

**Comment by YIQIHYM** [comment]
> How did you do this? I created a new conda environment and installed with pip the tf-nightly CPU, but the error is the same: "Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'
> Fatal Python error: Aborted". Did you call tflite_convert in some other way?

Excuse me,Do you solve it?

**Comment by DarnelleF** [comment]
Hi,
I am sorry no i didnt. i was just working on this a few months ago as a
personal project. So there wasnt any reason to actually get it working.
Good luck & Best wishes.

**Comment by liuxufenfeiya** [comment]
I also meet the same problem,and i try all the ways in this page,but it's useless.
finally,i try this way and then solved the problem.
[](https://github.com/paulbauriegel/tensorflow-tools/blob/master/convert-model-to-NHWC.py)
The main solution is use tf.transpose change the NCHW to NHWC.

**Comment by Ahwar** [comment]
The link is not working.

> I also meet the same problem,and i try all the ways in this page,but it's useless.
> finally,i try this way and then solved the problem.
> [https://github.com/paulbauriegel/tensorflow-tools/blob/master/convert-model-to-NHWC.py](url)
> The main solution is use tf.transpose change the NCHW to NHWC.
