### ISSUE TITLE
word2vec tutorial plot labels are incorrect

### ISSUE THREAD

**Issue by davidkretch** [tensorflow/tensorflow#245]
The plot produced by the word2vec tutorial looks like random words.

In tensorflow/tensorflow/g3doc/tutorials/word2vec/word2vec_basic.py line 223 (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/tutorials/word2vec/word2vec_basic.py#L223), the code gets labels for the first 500 words/embeddings by extracting 500 keys from the word dictionary without respect to their indices, using:
```
labels = list(dictionary.keys())[:plot_only]
```

Line 223 should probably be something like the following, since the each key's value is the word index:
```
labels = list(sorted(dictionary, key=dictionary.get))[:plot_only]
```

**Comment by seann999** [comment]
Glad someone also saw this issue.
The words I got in the outputted t-SNE plot were mostly obscure, and weren't anything like the ones shown in the tutorial example plot image.
`labels = [reverse_dictionary[i] for i in xrange(plot_only)]`
also worked for me.

**Comment by vrv** [comment]
@gouwsmeister has a fix out and we'll update the repo soon.  Thanks!

**Comment by vrv** [comment]
Should be fixed at HEAD
