### ISSUE TITLE
Add parameter for exporting TensorFlow models to override existed files

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#24504]
**System information**
- TensorFlow version (you are using): TensorFlow 1.8.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Now we have `saved_model.simple_save()` and `saved_model.builder` APIs to export the TensorFlow models. However, there is no parameter to override the model files if we want to do that. Using extra HDFS APIs to delete remote files requires more dependencies for user's Python scripts. And we can do that with the TensorFlow FileSystem APIs.

**Will this change the current api? How?**

Yes. Add the new parameter for `saved_model.simple_save()` function. It could not override the files by default so it may be compatible with the older versions.

**Who will benefit with this feature?**

The TensorFlow end users.

**Any Other info.**

No.

**Comment by tobegit3hub** [comment]
Here is the source code of Python API to export model if we want to support this, https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/builder_impl.py .

**Comment by annarev** [comment]
Reassigning to Allen since he works on saving models.

**Comment by allenlavoie** [comment]
I'd rather not add an option. The 2.x SavedModel APIs will overwrite without complaining. We can have that behavior by default in the 1.x APIs if someone wants to implement it, as it's a backward compatible change.
