### ISSUE TITLE
Support overriding model files when exporting model with extra parameter 

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#24503]
**System information**
- TensorFlow version (you are using): TensorFlow 1.8.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Now we have `saved_model.simple_save()` and `saved_model.builder` APIs to export the TensorFlow models. However, there is no parameter to override the model files if we want to do that. Using extra HDFS APIs to delete remote files requires more dependencies for user's Python scripts. And we can do that with the TensorFlow FileSystem APIs.

**Will this change the current api? How?**

Yes. Add the new parameter for `saved_model.simple_save()` function. It could not override the files by default so it may be compatible with the older versions.

**Who will benefit with this feature?**

The TensorFlow end users.

**Any Other info.**

No.

**Comment by karmel** [comment]
Thanks, @tobegit3hub , for the request. I am having trouble understanding exactly what you want, though. Can you clarify what the "model files" are here? Do you mean the checkpoint? Why do you want to override them?

**Comment by tobegit3hub** [comment]
Thanks @karmel for the reply. The "model files" means the SavedModel files. We may export the SavedModel multiple times with the same model version and only keep the latest one. Now we get exception if we try to export the SavedModel with the same model path.

**Comment by karmel** [comment]
Simple save is designed to be explicitly simple, and I do not think we should add more arguments to that function. Closing this for now. See also new, 2.0 saved model APIs: https://github.com/tensorflow/community/pull/34
