### ISSUE TITLE
Error message after importing Tensorflow

### ISSUE THREAD

**Issue by julesverneat** [tensorflow/tensorflow#24509]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 7, 64
- 
- TensorFlow installed from source
- TensorFlow version:1.12
- Python version:3.6
- Installed using pip
- 

**Describe the problem**

Ran pip install tensorflow on Anaconda prompt, then wrote the following code on Jupiter notebook:

import tensorflow as tf

a = tf.Variable(1, name="a")
b = tf.Variable(2, name="b")
f = a + b

init = tf.global_variables_initializer()
with tf.Session() as s:
    init.run()
    print( f.eval() )

 got the following error:

ImportError: DLL load failed with error code -1073741795

Please help!

**Comment by julesverneat** [comment]
Error code:

![grafik](https://user-images.githubusercontent.com/42918639/50351733-5b0c6f00-0543-11e9-953e-10c78e5af8fc.png)

![grafik](https://user-images.githubusercontent.com/42918639/50351992-21883380-0544-11e9-9928-376bb648b29e.png)

![grafik](https://user-images.githubusercontent.com/42918639/50352020-42e91f80-0544-11e9-8707-7c370c2394be.png)

**Comment by monjoybme** [comment]
The code is running in my system. Check your Anaconda and TensorFlow installation parts.

**Comment by julesverneat** [comment]
My Anaconda runs well. The installing of Tensorflow went well. Anybody has a applicable idea what i can do?

**Comment by AksBrijSandy** [comment]
Facing same problem with tensorflow CPU version

**Comment by julesverneat** [comment]
A friend told me there is an issue with Anaconda and Tensorflow. The
solution is to create a virtual environment.


Am Fr., 28. Dez. 2018, 01:35 hat AksBrijSandy <notifications@github.com>
geschrieben:

**Comment by ymodak** [comment]
@julesverneat Thanks for sharing your workaround. Closing this issue since activating virtual environment solves the issue for anaconda users.
