### ISSUE TITLE
tf.count_nonzero not working on TPU

### ISSUE THREAD

**Issue by kurnianggoro** [tensorflow/tensorflow#24515]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not Tested
- TensorFlow installed from (source or binary): Not sure (google colab)
- TensorFlow version (use command below): 1.12.0
- Python version: 2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.2
- GPU model and memory: None (TPU)

**Describe the current behavior**
according to the documentation [here](https://cloud.google.com/tpu/docs/tensorflow-ops), tf.count_nonzero is available in TPU, but it returned compilation error when used in TPU.

```
Compilation failure: While rewriting computation to not contain X64 element types, XLA encountered an HLO for which this rewriting is not implemented: %reduce.124.120 = s64[] reduce(s64[1,4]{1,0} %convert.124.113, s64[] %convert.124.115), dimensions={0,1}, to_apply=%total_example_Sum-reduction119, sharding={maximal device=0}, metadata={op_type="Sum" op_name="total_example/Sum"}
	TPU compilation failed
```

**Describe the expected behavior**
tf.count_nonzero is working for TPU

**Code to reproduce the issue**
[Codes](https://colab.research.google.com/drive/14sja1ttnwgxUlIXqCxuAhSh0L9uSa1te) are available in google colab
```
tf.reset_default_graph()

a = np.random.normal(0,10, [8,4]).astype(np.float32)
b = np.random.normal(0,10, [8,4]).astype(np.float32)

x = tf.convert_to_tensor(a)
y = tf.convert_to_tensor(b)


def ops(x,y):
    mask =tf.greater(x,y)
    return tf.count_nonzero(mask, name='total_example')
                     
tpu_ops = tf.contrib.tpu.batch_parallel(ops,inputs=[x,y],num_shards=8)
                     
with tf.Session(tpu_address) as sess:
    sess.run(tf.contrib.tpu.initialize_system())
    out = sess.run(tpu_ops)
    sess.run(tf.contrib.tpu.shutdown_system())
    
print(np.array(a>b).astype(np.uint8))
print(out)
```

**Other info / logs**
The problem seems to be the XLA compilation, casting to tf.int64 is not working in the current tf.count_nonzero chain.
I made a code that similar but convert to float32 instead of int64, and it's working.
```
def count_nonzero(x, axis=None, name='nonzero'):

    count = tf.reduce_sum(
        tf.cast(
            tf.not_equal(x,tf.zeros([],dtype=x.dtype)), 
            dtype=tf.float32, # <-- the original tf.count_nonzero function cast to tf.int64
            name='casting'
        ), 
        axis=axis,
        name=name
    )
    return count
    #return tf.cast(count, tf.int64)

def ops(x,y):
    mask =tf.greater(x,y)
    return count_nonzero(mask, name='total_example')

tpu_ops = tf.contrib.tpu.batch_parallel(ops,inputs=[x,y],num_shards=8)
```

Furthermore, simple casting from bool to int64 is working, so i guess this is related to the XLA optimization

```
def ops(x,y):
    mask =tf.greater(x,y)
    return tf.cast(mask, tf.int64)

tpu_ops = tf.contrib.tpu.batch_parallel(ops,inputs=[x,y],num_shards=8)
```

All [codes](https://colab.research.google.com/drive/14sja1ttnwgxUlIXqCxuAhSh0L9uSa1te) are available on google colab.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by jvishnuvardhan** [comment]
@kurnianggoro I ran your code with `TF1.15.5` and I don't see any error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/75bb5440e96788ccd15b5b69948cc387/count_nonzero-tpu.ipynb).

Please note that there is no support for `TF1.x` anymore. Please feel free to upgrade to `TF2.x` and create a new issue if you face any issue. Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by kurnianggoro** [comment]
@jvishnuvardhan thanks a lot. I already check the gist. There should not be any problem now.  @tensorflowbutler Thank you, everything is okay now. And yes, I am moving to TF 2.
