### ISSUE TITLE
tfdbg memory leak

### ISSUE THREAD

**Issue by liuchangready** [tensorflow/tensorflow#24513]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

System information

Windows 7, 64
TensorFlow installed from source
TensorFlow version:1.8
Python version:3.6
Installed using pip
Describe the problem

        def get_tfdbg_watch_fn(self):
        assert(len(self.reg_list)!=0),"reg_list can not be the empty"
        regex = "|"
        regex = regex.join(self.reg_list)
        raw_regex = "%r" % regex
        def watch_fn(fetches, feeds):
            del fetches, feeds
            return tfdbg.WatchOptions(
                debug_ops=["DebugIdentity"],
                node_name_regex_whitelist=regex,
                tolerate_debug_op_creation_failures=False)
        return  watch_fn

    def run(self,output,feed_fit):
        if self.debug_session is None and self.dump_dirs_count()==0:
            watch_fn = self.get_tfdbg_watch_fn()
            self.debug_session = tfdbg.DumpingDebugWrapperSession(sess=self.sess, session_root=self.session_root, watch_fn=watch_fn,
                                                    log_usage=False)
        if self.debug_session is not None and self.debug_session.run_call_count>=self.dump_dirs_count() :
            self.debug_session.run(output,feed_fit)
            #self.sess.run(output,feed_fit)
            del output
            del feed_fit
        return
hi
i run the tfdbg to get the intermediate tensor of the graph,the tfdbg  works,but when i run the self.debug_session.run more times i find the memory usage is grwoing biger and biger and it finally cause the programe aborted. i use the objgraph to check the python obj used,It dosen't grow after the second run,So i guess maybe there are some c obj leak in tfdbg.
thks

**Comment by sanatmpa1** [comment]
@liuchangready,

We see you were using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to latest stable version and let us know if the issue still persists in newer versions.we will get you the right help.Thanks!
