### ISSUE TITLE
matrix_triangular_solve is much slower on GPUs than on CPUs

### ISSUE THREAD

**Issue by maoshenl** [tensorflow/tensorflow#24528]
I'm running a fully connected mixture density network. What could be the possible reasons that matrix_triangular_solve routine takes much longer to compute on a GPU than on CPU (27ms vs 0.4ms)? I'm seeing similar behavior across different tensorflow verison (python 2.7), eg.

CPU: Intel Haswell (E5-2695 v3)
CUDA version: V9.0.176
tenserflow version : 1.7

GPU: Tesla P100-PCIE-16GB
CUDA version: V10.0.130
tenserflow version: 1.10

![gpu_timeline](https://user-images.githubusercontent.com/5102663/50380990-de63b880-0648-11e9-82ea-a08051b83a55.png)
![cpu_timeline](https://user-images.githubusercontent.com/5102663/50380991-de63b880-0648-11e9-97f4-6f59249b17e3.png)

**Comment by maoshenl** [comment]
The function involved is: 
gmm = tfd.MixtureSameFamily(mixture_distribution=tfd.Categorical(probs=out_p),
                     components_distribution=tfd.MultivariateNormalTriL(loc=out_mu,
                                                        scale_tril=sigma_mat))

**Comment by maoshenl** [comment]
Hi @msymp,  thanks!

I'm using the official NVIDIA Tensorflow singularity container 18.10-py2, directly from their web site:
https://ngc.nvidia.com/catalog/containers/nvidia%2Ftensorflow/tags

As for other information,
OS:  CentOS Version 7
GPU: NVIDIA Tesla P100 Pascal architecture, 16GB/GPU memory

**Comment by rmlarsen** [comment]
What are the dimensions of your matrix? How many such systems are you solving (batch size)? It is expected that triangular solve is slower on GPU for small matrices. I am in the process of adding a code path to call the batched solver in CUDA for large batches of small matrices.
