### ISSUE TITLE
ImportError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by MichaelLi0913** [tensorflow/tensorflow#2452]
I downloaded tensorflow using Anacaonda environment installation (I use python 3.5). When I enter `import tensorflow as tf` it always shows the message: "ImportError: No module named 'tensorflow' Can someone please help me resolve this issue?

**Comment by clsung** [comment]
Can you paste detailed log on the tensorflow installation and execution?

**Comment by wangg12** [comment]
Same question here, @MichaelLi0913 have you solved it?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
