### ISSUE TITLE
Duplicated Gradient issue during TF Lite conversion

### ISSUE THREAD

**Issue by Lyken17** [tensorflow/tensorflow#24525]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Yes
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.0-dev20181222
- Python version: 3.6
- Bazel version (if compiling from source): / 
- GCC/Compiler version (if compiling from source): / 
- CUDA/cuDNN version: 9.1 
- GPU model and memory: 1080 Ti with 11Gib memory

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Code to reproduce the issue**
I was trying to convert the model in https://github.com/MIT-HAN-LAB/ProxylessNAS to TFLite, however, when following the tutorial, I got errors below 

```python
import tensorflow as tf
from proxyless_nas_tensorflow import proxyless_cpu, proxyless_gpu, proxyless_mobile, proxyless_mobile_14

net = proxyless_cpu()
net.is_training = False

converter = tf.lite.TFLiteConverter.from_session(net.sess, [net.images, net.labels], [net.cross_entropy])
tflite_model = converter.convert()
'''
~/anaconda3/envs/tf-nightly/lib/python3.6/site-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str)
    206       stderr = _try_convert_to_unicode(stderr)
    207       raise ConverterError(
--> 208           "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
    209   finally:
    210     # Must manually cleanup files.

ConverterError: TOCO failed. See console for info.
2018-12-22 13:38:13.626047: F tensorflow/core/framework/function.cc:1626] Check failed: GetOpGradFactory()->insert({op, func}).second Duplicated gradient for ReadVariableOp
Aborted (core dumped)
'''
```
Any advice would be appreciated!

**Comment by chenlh14** [comment]
I meet the same problem with you. Any idea?

**Comment by caoyangcr7** [comment]
same problem here...

**Comment by chenlh14** [comment]
@Lyken17 @caoyangcr7 I turned to tf-nightly-1.13.0.dev20181027 and this problem disappeared. But my model after conversion doesn't get the right classification results.

**Comment by IslamSabdelazez** [comment]
i have the same problem and tf-nightly-1.13.0.dev20181027 didn't work for me

**Comment by Gpoxolcku** [comment]
Living hard times suffering the same issue here

**Comment by msymp** [comment]
Hello all, to correctly use the latest TFLiteConverter for r1.12/r1.13 & higher nightly builds, you must use the  tf.contrib.lite.TFLiteConverter Python API instead of tf.lite.TFLiteConverter. Please try your conversions again and report back to us. Thanks.

**Comment by yaxiongma** [comment]
@msymp 
Hi M Srikant~
    I just tried the method you mentioned above：
> tf.contrib.lite.TFLiteConverter Python API instead of tf.lite.TFLiteConverter

But it didn't work.
My tf version is **'1.13.0-dev20181226'**.
Here is part of my code and the error log:

**code:**


`
converter =tf.contrib.lite.TFLiteConverter.from_frozen_graph('data/tflog/pb/feature_extracting_from_fixed_sequence.pb',
                                                      ['adio_sequence'],['adio_sequence'])
converter.post_training_quantize = True
tflite_quantized_model=converter.convert()
`

**error log:**

---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-6-9437387566b3> in <module>
      2                                                       ['adio_sequence'],['adio_sequence'])
      3 converter.post_training_quantize = True
----> 4 tflite_quantized_model=converter.convert()

~/anaconda3/envs/try_new/lib/python3.6/site-packages/tensorflow/lite/python/lite.py in convert(self)
    497           input_tensors=self._input_tensors,
    498           output_tensors=self._output_tensors,
--> 499           **converter_kwargs)
    500     else:
    501       result = _toco_convert_graph_def(

~/anaconda3/envs/try_new/lib/python3.6/site-packages/tensorflow/lite/python/convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, *args, **kwargs)
    443   data = toco_convert_protos(model_flags.SerializeToString(),
    444                              toco_flags.SerializeToString(),
--> 445                              input_data.SerializeToString())
    446   return data
    447 

~/anaconda3/envs/try_new/lib/python3.6/site-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str)
    206       stderr = _try_convert_to_unicode(stderr)
    207       raise ConverterError(
--> 208           "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
    209   finally:
    210     # Must manually cleanup files.

**ConverterError: TOCO failed. See console for info.
2018-12-27 11:01:58.639961: F tensorflow/core/framework/function.cc:1626] Check failed: GetOpGradFactory()->insert({op, func}).second Duplicated gradient for ReadVariableOp
Aborted (core dumped)**

**Comment by yaxiongma** [comment]
My problem was finally solved when switching to **TensorFlow 1.12.0**

**Comment by msymp** [comment]
Great to hear!

**Comment by twalk4821** [comment]
With TensorFlow 1.12.0, I get the original issue again. Which makes sense. That is, not using the nightly build. 

I tensorflow/contrib/lite/toco/import_tensorflow.cc:189] Unsupported data type in placeholder op: 2\n2018-12-30 15:40:54.450020: F tensorflow/contrib/lite/toco/import_tensorflow.cc:2137] Check failed: status.ok() Unexpected value forattribute 'T'. Expected 'DT_FLOAT'\n"
