### ISSUE TITLE
AttributeError: module 'tensorflow.compat' has no attribute 'v1'

### ISSUE THREAD

**Issue by danieljask** [tensorflow/tensorflow#24524]
I ran cnn_mnist.py on my machine but got "AttributeError: module 'tensorflow.compat' has no attribute 'v1'". can anyone solve this problem?

**Comment by larissa95** [comment]
You can run it by changing
train_input_fn = tf.compat.v1.estimator.inputs.numpy_input_fn(
to train_input_fn = tf.estimator.inputs.numpy_input_fn(
and eval_input_fn = tf.compat.v1.estimator.inputs.numpy_input_fn(
to eval_input_fn = tf.estimator.inputs.numpy_input_fn(

basically the reverse than what was done in the last commit:
https://github.com/tensorflow/tensorflow/commit/95e808ba44075dfe0b7db57bb49d2e64a1977a95

**Comment by ymodak** [comment]
Closing this issue since workaround has been provided and [PR](https://github.com/tensorflow/tensorflow/pull/24552) is in process. Thanks!

**Comment by violet17** [comment]
I tried to upgrade tf to 1.13, and problems solved.

**Comment by DejaYang** [comment]
I met a similar bug, that is ' AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v1' ', when I run inference.py of [FPN_tensorflow](https://github.com/DetectionTeamUCAS/FPN_Tensorflow), the source code is `summary_image_v1 = tf.compat.v1.summary.image` .
Then I change the code to `summary_image_v1 = tf.summary.image`, the program can run correctly.

**Comment by toniz** [comment]
because the tensorflow-plot version is higher. so 
 pip install tensorflow-plot==0.3.0
will ok!

**Comment by schauppi2** [comment]
Hello, 
I run into the "same" Problem. I have successfully installed tensorflow-gpu 1.12 on Ubuntu 18.04 with CUDA 9.0 and cudnn 7.1.2 in an anaconda environment (I followed this tutorial: https://medium.com/@redowan/no-bullshit-guide-on-installing-tensorflow-gpu-ubuntu-18-04-18-10-238924cc4a6a).

Then i followed this tutorial for installing object detection models: https://medium.com/@teyou21/setup-tensorflow-for-object-detection-on-ubuntu-16-04-e2485b52e32a

But when i try to python `object_detection/builders/model_builder_test.py` i get following error: 

`Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/home/schaupp/models/research/object_detection/builders/model_builder.py", line 35, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "/home/schaupp/models/research/object_detection/models/faster_rcnn_inception_resnet_v2_feature_extractor.py", line 30, in <module>
    from nets import inception_resnet_v2
  File "/home/schaupp/models/research/slim/nets/inception_resnet_v2.py", line 375, in <module>
    batch_norm_updates_collections=tf.compat.v1.GraphKeys.UPDATE_OPS,
AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v1'
`
I installed exact the same ah few month ago on the same machine but this time it won't work.
I hope someone can help me - i struggled many hours with this problem.

**Comment by ManuBN786** [comment]
> I met a similar bug, that is ' AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v1' ', when I run inference.py of [FPN_tensorflow](https://github.com/DetectionTeamUCAS/FPN_Tensorflow), the source code is `summary_image_v1 = tf.compat.v1.summary.image` .
> Then I change the code to `summary_image_v1 = tf.summary.image`, the program can run correctly.

This worked for me . Thanks

**Comment by hduanac** [comment]
> I tried to upgrade tf to 1.13, and problems solved.

Many thanks. It also worked for me.
