### ISSUE TITLE
Update bazel to 0.20.0 for tensorflow/tensorflow:custom-op

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#24523]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): `docker run -i -t --rm tensorflow/tensorflow:custom-op `
- TensorFlow version: `docker run -i -t --rm tensorflow/tensorflow:custom-op `
- Python version: n/a
- Installed using virtualenv? pip? conda?: docker
- Bazel version (if compiling from source): 0.15.0 (`tensorflow/tensorflow:custom-op`)
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version:n/a
- GPU model and memory:n/

**Describe the problem**
While tensorflow has updated bazel to 0.20.0, The `tensorflow/tensorflow:custom-op` docker image still uses 0.15.0. This cause issues when trying to build a custom op that requires higher versions of bazel (e..g, 0.17.1+).

Please upgrade bazel in `tensorflow/tensorflow:custom-op` to 0.20.0.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
$ docker run -i -t --rm tensorflow/tensorflow:custom-op 
root@ubuntu:/# bazel version
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.15.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 26 12:10:19 2018 (1530015019)
Build timestamp: 1530015019
Build timestamp as int: 1530015019
```
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by yifeif** [comment]
I pushed the first version of tensorflow/tensorflow:nightly-custom-op just now and am in the middle of setting up a nightly release. Please give it a try. Thanks!

**Comment by yongtang** [comment]
@yifeif I tried with `tensorflow/tensorflow:nightly-custom-op` to build custom ops and it works great. Thanks!

**Comment by yifeif** [comment]
Great! Thanks for letting us know.
