### ISSUE TITLE
Building from local docker File

### ISSUE THREAD

**Issue by arita37** [tensorflow/tensorflow#2453]
### Environment info

Operating System:Docker / Win7 64bits

Following instructions here:
https://docs.docker.com/windows/step_four/

Using this docker file:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile

We build the tensorflow file for installation:

We had this error message:
Step 7 : COPY jupyter_notebook_config.py /root/.jupyter/
lstat jupyter_notebook_config.py: no such file or directory

How to solve this issue ?
### What have you tried?

1.
### Logs or other output that would be helpful

(If logs are large, please upload as attachment).

**Comment by ChenZhaobin** [comment]
I met the same problem,how did you solve it ?

**Comment by ChenZhaobin** [comment]
@arita37  I made it ,just copy  the whole git code to the same folder with dockerfile.

**Comment by arita37** [comment]
Ok, good,
What is the docker command line ?
RUN git ???

Thanks

On 24 May 2016, at 13:33, ChenZhaobin <notifications@github.com> wrote:

@arita37 I made it ,just copy the whole git code to the same folder with dockerfile.

―

**Comment by girving** [comment]
@jendap: Want to comment?

**Comment by girving** [comment]
Switching to @caisq.

**Comment by developeralgo8888** [comment]
Answer the damn question ? Hello LOL
" I made it ,just copy the whole git code to the same folder with dockerfile. "   what the BLIP does that mean

**Comment by drpngx** [comment]
Use this file: https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/run_jupyter.sh#L1

Either copy in your directory, or run the docker build directory from there.
