### ISSUE TITLE
[feature request] make MutableHashTableOfScalars and MutableHashTableOfTensors trainable

### ISSUE THREAD

**Issue by shengofsun** [tensorflow/tensorflow#24539]
**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

This issue is related to issue #19324, in which we need some technique to do embedding on a large sparse hash table, so that we can reduce memory usage and the probability of hash collision.

As far as I can see, ops like MutableHashTableOfScalars and MutableHashTableOfTensors in [lookup table ops](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/lookup_ops.cc) can be used to meet this demand. The main problem is that they are not trainable. 

In other words, what we need may be a feature like this:
```
# define a Hash Table
table = tf.contrib.lookup.MutableHashTable(
    key_dtype=tf.string,
    value_dtype=tf.float64,
    default_value=-1)
params = table.lookup(["w1", "w2", "b"])
# define other ops with params
...
# optimize the table
train_op = optimizer.minimize(loss, var_list=[table], global_step=global_step)
```

**Will this change the current api? How?**

Yes, the current API would be changed. 

In order to implement a feature like this, we may need to:
* do modification on the lookup table ops to make it trainable. This involves several parts of fix like:
   1. some fix in python layer as only variables are trainable now.
   2. several new ops may be add in lookup table so that we can update the gradients. 
* modify the api of MutableHashTable, so that we can pass more args, like: 
   1. shard it to different parameter servers.
   2. when value for a key doesn't exist, we can initialize it with different initial value.
   3. we can make the KV pairs have TTL.
* add a new API like embedding_lookup_sparse, or do modification on it.
* make sure the checkpoint for hash tables can work properly

**Who will benefit with this feature?**

As a matter of fact, sparse models in recommend system may benefit with this feature a lot.

**Comment by nolanliou** [comment]
Looking forward to the feature.

**Comment by yejw5** [comment]
@gunan We have tried a roughly implementation at https://github.com/tensorflow/tensorflow/pull/24915 based on class `MutableHashTableOfTensors`. Can you have a look?

**Comment by gunan** [comment]
I would not be the right reviewer of this.
I will reassign to see if we can find a better reviewer.

**Comment by yejw5** [comment]
@gunan Many thanks.
And @jvishnuvardhan could you take some time to revew the codes? Thanks!

**Comment by skye** [comment]
FYI @ebrevdo

**Comment by algorithmdog** [comment]
Looking forward to the feature.

**Comment by Esail** [comment]
this is very useful and important . In China, tensorflow is dramatically used in recommender system. However, when we want to learn something from user's behavior, large embedding layers are always required.

**Comment by liyi193328** [comment]
Looking forward to the feature.

**Comment by Chaos-Ju** [comment]
Looking forward to the feature.

**Comment by tobegit3hub** [comment]
This was discussed in https://github.com/tensorflow/tensorflow/issues/19324 and the RFCs from Tencent/Alibaba are under discussion https://github.com/tensorflow/community/pull/237 .

**Comment by sushreebarsa** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow version with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release](https://github.com/tensorflow/tensorflow/releases) notes to stay up to date with the latest developments which are happening in the Tensorflow space.
Thank you!
