### ISSUE TITLE
The Windows GPU binary from googleapis.com cannot see the GPU device

### ISSUE THREAD

**Issue by hillin** [tensorflow/tensorflow#24534]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-1.12.0.zip
- TensorFlow version: 1.12.0
- Python version: N/A
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 9.0, cuDNN64_7
- GPU model and memory: GeForce 1080 Ti

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

The Windows GPU binary I downloaded from [googleapis.com](https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-1.12.0.zip) seems unable to see the GPU device on my machine. I can only see the CPU device in the return value of `TF_SessionListDevices`:
> $/job:localhost/replica:0/task:0/device:CPU:0 ($CPU)

I tried 1.10.0, 1.11.0 and 1.12.0, and their RC releases, none of them worked.

However I can confirm that the PIP installed tensorflow-gpu can see the GPU device and works well on the same graph:

> 2018-12-24 02:46:37.352485: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> 2018-12-24 02:46:37.687436: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.645
> pciBusID: 0000:1f:00.0
> totalMemory: 11.00GiB freeMemory: 9.10GiB
> 2018-12-24 02:46:37.709856: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
> 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by msymp** [comment]
Hello @hillin , Please install with following procedure and let us know:

TensorFlow supports only 64-bit Python 3.5 on Windows. Test Pip installation on Windows with this distribution of Python:   _https://www.python.org/downloads/release/python-352/_

NOTE: TensorFlow requires MSVCP140.DLL, which may not be installed on your system. If, when you import tensorflow as tf, you see an error about No module named "_pywrap_tensorflow" and/or DLL load failed, check whether MSVCP140.DLL is in your %PATH% and, if not, you should install the Visual C++ 2015 redistributable (x64 version).

To install the GPU version of TensorFlow, enter the following command at a command prompt:
> C:\> pip install --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-0.12.1-cp35-cp35m-win_amd64.whl

**Comment by hillin** [comment]
Hi @msymp , thanks for the response.

The python/PIP version works fine on my side. I'm reporting an issue related to the C++ binary build (which I invokes with C#).
