### ISSUE TITLE
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.

### ISSUE THREAD

**Issue by SumitSarnk** [tensorflow/tensorflow#24548]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rootkitchao** [comment]
The current version of Tensorflow installed via pip uses the AVX instruction set at compile time.This means that your CPU needs to support the AVX instruction set. This instruction set is supported from the second generation of Intel Core CPUs (codenamed SandyBridge). You can compile a Tensorflow from the source that does not use the AVX instruction set. Or find an already compiled one on the internet.

**Comment by ymodak** [comment]
Closing this issue since @rootkitchao has answered the question correctly. Feel free to post if have any issues in building TF from sources. Thanks!

**Comment by triple-tam** [comment]
@rootkitchao I'd like to try out your suggestion, but could I get some more details please? I'm new to such environments, and I am getting the same error.
- I have a GPU, and my TF is installed with GPU-support, so why is it trying to access/match instruction sets with my CPU?
- If it's still necessary for me to fix this CPU issue, where can I find a pre-compiled TF with SSE2 or SSD4_1 instruction support? I couldn't find it via google...
Thanks!

**Comment by triple-tam** [comment]
For others' reference, here is a useful repository of [custom TensorFlow builds](https://github.com/lakshayg/tensorflow-build). I tried installing one of their wheels, but then got "import tf; Illegal Instruction" so it's still a figuring-out-in-process, but maybe you'll have better luck with it

**Comment by mzechmeister** [comment]
I entered the same problem. The readme only says `pip install tensorflow`, but it simply does not work. 
And from this issue, I don't get the solution.
Can you give clear install instructions (I'm on Linux, opensuse)?

**Comment by foobar167** [comment]
Try Anaconda. It has TensorFlow distribution for old CPU.

**Comment by liljohnak** [comment]
FYI, Installing Anaconda works on my old computer.

**Comment by razzOn2calculus** [comment]
> The current version of Tensorflow installed via pip uses the AVX instruction set at compile time.This means that your CPU needs to support the AVX instruction set. This instruction set is supported from the second generation of Intel Core CPUs (codenamed SandyBridge). **You can compile a Tensorflow from the source that does not use the AVX instruction set. Or find an already compiled one on the internet.**

@rootkitchao , could you tell me How do i can use already compiled tensorflow that dont used AVX instruction. 
My cpu seems to not supporting AVX instruction, even it throws dll error while using 1.13.2 or lower version. 
Thanks for the response

**Comment by mehdirezaie** [comment]
I was able to install TF with anaconda on an old Linux system
```Shell
$> conda create -n tensorflow_env tensorflow
$> conda activate tensorflow_env
```

```Python
>>> 
(tensorflow_env) mehdi@moneta:~> python
Python 3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
.
.
.
>>> msg = tf.constant(f"Hello World from {tf.__version__}")
>>> print(msg)
tf.Tensor(b'Hello World from 2.1.0', shape=(), dtype=string)
```

**Comment by convertthinking** [comment]
Remember, when you exclude CPUs without AVX instructions you suggest to throw away systems with up to 48 virtual cores and up to 512Gb of RAM which are still all around and very handy and can feed powerful GPUs.

You are to provide versions that support any instruction set available, it's just a problem of linking existing libraries and should be easy for builders.

I do vote for the issue to be solved.

There are many cases when pip should have a version, not conda. 

If someone find a version for SSE4.2 with GPU please let me know

**Comment by GadgetNutt** [comment]
Just to put in my two cents, I'm very much frustrated as I'm trying to build TF without AVX and to support GPU on Windows 10.  Why are these systems being excluded???  Is someone trying to cut out Nvidia in Windows GPU builds?
