### ISSUE TITLE
Step to Build for Centos 7

### ISSUE THREAD

**Issue by II-VSB-II** [tensorflow/tensorflow#24542]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): Latest
- Are you willing to contribute it (Yes/No): No

Can anyone give the steps for building this for Centos 7.

**Comment by ymodak** [comment]
Unfortunately TensorFlow does not provide official support for Centos. However you can install TensorFlow on Centos by reaching out to [community support](https://gist.github.com/thoolihan/28679cd8156744a62f88).
