### ISSUE TITLE
How to resize segmentation map to the size of input image obtained from Deeplab?

### ISSUE THREAD

**Issue by ahmedbilal** [tensorflow/tensorflow#24541]
Currently, Deeplab v3 return resized (small) image and its corresponding mask. But, I need segmentation mask for the original input image (large)? How can I achieve this?

**Comment by jvishnuvardhan** [comment]
@ahmedbilal 
Please understand that Github is primarily for addressing bugs in installation and performance. [StackOverflow] (https://stackoverflow.com/) is better place to ask/discuss support questions like these.

**Comment by jvishnuvardhan** [comment]
Closing this support issue as GitHub is not a place for support. Thanks!

**Comment by giri-prasad** [comment]
> Currently, Deeplab v3 return resized (small) image and its corresponding mask. But, I need segmentation mask for the original input image (large)? How can I achieve this?

@jvishnuvardhan I've been looking for the exact same thing.. were you able to resize the segmentation mask obtained from Deeplab v3?? Any leads would be helpful ..

**Comment by ahmedbilal** [comment]
> > Currently, Deeplab v3 return resized (small) image and its corresponding mask. But, I need segmentation mask for the original input image (large)? How can I achieve this?
> 
> @jvishnuvardhan I've been looking for the exact same thing.. were you able to resize the segmentation mask obtained from Deeplab v3?? Any leads would be helpful ..

Hi. I was able to resize it but don't recall how. Probably, I had used numpy resizing methods https://docs.scipy.org/doc/numpy/reference/generated/numpy.resize.html
