### ISSUE TITLE
Building from source with bazel: no such package '@local_config_cuda//cuda'

### ISSUE THREAD

**Issue by Maxtoq** [tensorflow/tensorflow#24549]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13 
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.21.0
- CUDA/cuDNN version: 10.0/7.4.2
- GPU model and memory: GTX 960M

**Describe the problem**
I followed the instructions for building Tensorflow from source on the website. But the command 'bazel build...' gives me these errors:

> C:\tensorflow>bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\tensorflow/.bazelrc
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
DEBUG: C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for Visual C++ through registry
DEBUG: C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for default Visual C++ installation directory
DEBUG: C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'PROGRAMFILES(X86)' environment variable is not set, using 'C:\Program Files (x86)' as default
DEBUG: C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1556
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1395, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 239, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 156, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe")
        File "C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 220, in find_msvc_tool
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1556
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1395, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 239, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 156, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe")
        File "C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 220, in find_msvc_tool
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)
INFO: Elapsed time: 1,004s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

I'm new to Tf so I'm kind of lost.
Is there anything I can do ? 

Thanks.

**Comment by rootkitchao** [comment]
Tensorflow 1.13 does not seem to have been officially released, I am not sure that it can be successfully compiled with CUDA10.0.According to your error log, it seems that the location of the MSVC compiler is not properly configured.In addition, as far as I know, using MSVC2017 is likely to encounter some problems, it is recommended to use MSVC2015 Update3.It is recommended to read the guide (https://www.tensorflow.org/install/source_windows) carefully and ensure that all required software is properly installed.
What I can tell you is that after disabling XLA I successfully compiled the master branch and used CUDA10.In addition, the bazel version I used is 0.20.0.I wish you success, thank you.

**Comment by Maxtoq** [comment]
I had actually tried also with MSVC2015 Update 3, with the same result.
I tried again with **MSVC2015 Update 3** and **bazel 0.20.0**. The same error seems to occur (without the part about MSVC2017 though).
Here is the output, with the configuration I made:

> C:\tensorflow>python ./configure.py
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
nul
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: 2e4f3e6d-1ac4-4089-8040-6cc98c820303
You have bazel 0.20.0 installed.
Please specify the location of python. [Default is C:\Users\maxim\AppData\Local\Programs\Python\Python36-32\python.exe]:
Found possible Python library paths:
  C:\Users\maxim\AppData\Local\Programs\Python\Python36-32\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\maxim\AppData\Local\Programs\Python\Python36-32\lib\site-packages]
Do you wish to build TensorFlow with XLA JIT support? [y/N]:
No XLA JIT support will be enabled for TensorFlow.
Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.
Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.
Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 9.0]: 10.0
Please specify the location where CUDA 10.0 toolkit is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0]:
Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]:
Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0]:
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 3.5,7.0]: 5.0
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:
Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.
Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=noignite       # Disable Apacha Ignite support.
        --config=nokafka        # Disable Apache Kafka support.
        --config=nonccl         # Disable NVIDIA NCCL support.

> C:\tensorflow>bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\tensorflow/.bazelrc
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
INFO: Invocation ID: d1c653f2-e12e-4a46-b29e-3d46940aff08
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': in C:/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1556
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1395, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 239, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 156, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe")
        File "C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 230, in find_msvc_tool
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': in C:/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1556
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1395, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 239, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 156, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe")
        File "C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 230, in find_msvc_tool
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)
INFO: Elapsed time: 12,161s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
    Fetching @local_config_cuda; fetching

Does anyone have an idea of what's going wrong ?

Thanks.

**Comment by ymodak** [comment]
CUDA 10 will be officially supported with TensorFlow 2.0 
I would recommend you to switch to cuda 9.0 which is current official supported version if possible.

**Comment by Maxtoq** [comment]
So I tried with CUDA 9.0, and it's still not working. 
I have the same errors: 
> Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': in C:/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda'

> error loading package 'tensorflow/tools/pip_package': in C:/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda'

Weird thing though, even after going back to MSVC 2015 Update 3, the error message still says:
> C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)

I tried again with MSVC 2017 to be sure, still the exact same error.

I don't know what's going on.
Does anyone have a clue ?

Thanks.

**Comment by ymodak** [comment]
Apologies for the delay in response. @Maxtoq  Is this still an issue for you? Can you share your progress till now? We can reopen this issue if required. Thanks!

**Comment by Maxtoq** [comment]
I still have the same issue. But I think the problem is that Bazel can't find the path of MSVC 2015 directories. 
It was looking in the installation directory of Microsoft Visual Studio 2017. I uninstalled it and now Bazel just can't find any path for MSVC.
I posted my issue on the Bazel Stackoverflow to see if they can help.
I don't think we need to reopen this issue, unless someone has an idea. But I think the problem is with Bazel and MSVC, not Tensorflow.
Thanks

**Comment by Maxtoq** [comment]
I found the solution. The problem was that I had badly set the environment variable BAZEL_VS (or BAZEL_VC). I followed the examples given here: https://docs.bazel.build/versions/0.21.0/install-compile-source.html#bootstrap-windows-bootstrap.

**Comment by ymodak** [comment]
I see. Thanks for sharing your solution.
