### ISSUE TITLE
Adding a New Op Error:  can not load the customed file

### ISSUE THREAD

**Issue by StrivingMax** [tensorflow/tensorflow#2455]
### Environment info
Operating System:  Ubuntu 14.04 LTS

Installed version of CUDA and cuDNN: None 

If installed from binary pip package, provide:

1. Which pip package you installed.
I use the command below to install tensorflow.
sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.8.0

### What have you tried?
I have tried to create my new operation, but there was something wrong that made me fail to load the self-defined_tensorflow_op.so. Here are steps which are exactly the same as those in the official tutorial and what I have tried. 

1. Copy the whole content from the official tutorial to create a  file named tensorflow/core/user_ops/zero_out.cc . What is the file is as following.

        #include "tensorflow/core/framework/op.h"

        REGISTER_OP("ZeroOut")
            .Input("to_zero: int32")
            .Output("zeroed: int32");

        \#include "tensorflow/core/framework/op_kernel.h"

        using namespace tensorflow;

        class ZeroOutOp : public OpKernel {
         public:
          explicit ZeroOutOp(OpKernelConstruction* context) : OpKernel(context) {}

          void Compute(OpKernelContext* context) override {
            // Grab the input tensor
            const Tensor& input_tensor = context->input(0);
            auto input = input_tensor.flat<int32>();

            // Create an output tensor
            Tensor* output_tensor = NULL;
            OP_REQUIRES_OK(context, context->allocate_output(0, input_tensor.shape(),
                                                             &output_tensor));
            auto output = output_tensor->template flat<int32>();

            // Set all but the first element of the output tensor to 0.
            const int N = input.size();
            for (int i = 1; i < N; i++) {
              output(i) = 0;
            }

            // Preserve the first input value if possible.
            if (N > 0) output(0) = input(0);
          }
        };

        REGISTER_KERNEL_BUILDER(Name("ZeroOut").Device(DEVICE_CPU), ZeroOutOp);

2. Then I compile the zero_out.cc with following commands:

        TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')

        g++ -std=c++11 -shared zero_out.cc -o zero_out.so -fPIC -I $TF_INC

3. Trying not to miss anything, I also create the BUILD file and run the corresponding commands.

        \# Here is the BUILD file
        load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

        tf_custom_op_library(
            name = "zero_out.so",
            srcs = ["zero_out.cc"],
        )

        \# Then run this command
        $ bazel build -c opt //tensorflow/core/user_ops:zero_out.so

4. When I try to use the new op, the error comes out. 
        \# Run in python 2.7.11, with following command
        import tensorflow as tf
        zero_out_module = tf.load_op_library('zero_out.so')

### Here is the error message
        Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
            File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 71, in load_op_library
                raise errors._make_specific_exception(None, None, error_msg, error_code)
                tensorflow.python.framework.errors.NotFoundError: zero_out.so: cannot open shared object file: No such file or directory

Please help me out with this. I have spent lots of time trying to figure out what is wrong and searching for the answer, but nothing works. Any advice is also will welcome. Thanks

**Comment by keveman** [comment]
`tf.load_op_library` relies on the system provided mechanism to locate the `.so` file, especially if you don't provide the full path to the file. On linux, the directories present in the `LD_LIBRARY_PATH` environment variable are looked up. In your case, when compiling with `g++`, can you try providing the full path to `tf.load_op_library`, most probably `./zero_out.so`?
If you are compiling using bazel, there is an utility function to give you the full path to the `.so`. Look [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/adding_an_op/zero_out_1_test.py#L36) :

    tf.load_op_library(os.path.join(
              tf.resource_loader.get_data_files_path(), 'zero_out_op_kernel_1.so'))

**Comment by keveman** [comment]
Ping. @StrivingMax Does my suggestion work for you?

**Comment by StrivingMax** [comment]
Yes, I have successfully loaded my costumed ops to the python interpreter with the code below

    my_module = tf.load_op_library(
        '/home/my_name/Tools/tensorflow/tensorflow/core/user_ops/my_ops.so'
    )

Thank you very much. I already realized that I could not locate the file and did not know what was wrong. Your advice is exactly the answer.

However, another problem occurs when I run 'my_mudule.my_ops' in 'with tf.Sessin():'.
 
    E tensorflow/core/framework/op_kernel.cc:867] OpKernel ('op: "Fact" device_type: "GPU"     host_memory_arg: "fact"') for unknown op: Fact
    E tensorflow/core/framework/op_kernel.cc:867] OpKernel ('op: "Fact" device_type: "CPU" label:  "Sergey"') for unknown op: Fact
    E tensorflow/core/framework/op_kernel.cc:867] OpKernel ('op: "Fact" device_type: "CPU" label: "sergey"') for unknown op: Fact

I did not do anything with 'Fact.cc' or 'Fact.so'. How can I do to resolve this error?

Again, thank  you very muck for giving me advice.

**Comment by keveman** [comment]
The error seems to indicate that you have the `HostMemory` attribute set for an output arg , and a label called `Sergey` in your kernel specification. However, the code you provided doesn't seem to contain those. Can you please provide the exact code for your custom op?

**Comment by keveman** [comment]
Closing the issue as there seems to be no outstanding action items. @StrivingMax feel free to open again if you feel that this has not been addressed sufficiently.

**Comment by tongda** [comment]
Hi, I got a similar problem.

Operating System: macOS 10.12

Installed version of CUDA and cuDNN: None

TensorFlow 0.11.0 installed from source.

I followed the [add new op](https://www.tensorflow.org/versions/r0.11/how_tos/adding_an_op/index.html) tutorial, adding zero_out.cc file:

    #include "tensorflow/core/framework/op.h"
    
    REGISTER_OP("ZeroOut")
        .Input("to_zero: int32")
        .Output("zeroed: int32");
    
    #include "tensorflow/core/framework/op_kernel.h"
    
    using namespace tensorflow;
    
    class ZeroOutOp : public OpKernel {
     public:
      explicit ZeroOutOp(OpKernelConstruction* context) : OpKernel(context) {}
    
      void Compute(OpKernelContext* context) override {
        // Grab the input tensor
        const Tensor& input_tensor = context->input(0);
        auto input = input_tensor.flat<int32>();
    
        // Create an output tensor
        Tensor* output_tensor = NULL;
        OP_REQUIRES_OK(context, context->allocate_output(0, input_tensor.shape(),
                                                         &output_tensor));
        auto output = output_tensor->flat<int32>();
    
        // Set all but the first element of the output tensor to 0.
        const int N = input.size();
        for (int i = 1; i < N; i++) {
          output(i) = 0;
        }
    
        // Preserve the first input value if possible.
        if (N > 0) output(0) = input(0);
      }
    };
    
    REGISTER_KERNEL_BUILDER(Name("ZeroOut").Device(DEVICE_CPU), ZeroOutOp);

and bazel BUILD file:

    load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")
    
    tf_custom_op_library(
        name = "zero_out.so",
        srcs = ["zero_out.cc"]
    )

then I run:

    bazel build -c opt //tensorflow/core/user_ops:zero_out.so

output:

    INFO: Waiting for response from Bazel server (pid 28589)...
    INFO: Found 1 target...
    Target //tensorflow/core/user_ops:zero_out.so up-to-date:
      bazel-bin/tensorflow/core/user_ops/zero_out.so
    INFO: Elapsed time: 5.115s, Critical Path: 0.00s

The generated shared library located in bazel-bin. When I tried to load it like this:

    tf.load_op_library('/Users/dtong/code/data/tensorflow/bazel-bin/tensorflow/core/user_ops/zero_out.so')

the result:

    python(41716,0x7fffb7e123c0) malloc: *** error for object 0x7f9e9cd2de18: pointer being freed was not allocated
    *** set a breakpoint in malloc_error_break to debug

@keveman could you please help take a look at this problem?

**Comment by sugartom** [comment]
@JakeRenn Hi Jake, I saw similar error message as you did:
```
E tensorflow/core/framework/op_kernel.cc:943] OpKernel ('op: "Fact" device_type: "CPU" label: "sergey"') for unknown op: Fact
E tensorflow/core/framework/op_kernel.cc:943] OpKernel ('op: "Fact" device_type: "CPU" label: "Sergey"') for unknown op: Fact
E tensorflow/core/framework/op_kernel.cc:943] OpKernel ('op: "Fact" device_type: "GPU" host_memory_arg: "fact"') for unknown op: Fact
```
Do you have any thoughts on that? Thanks in advance! :-)
