### ISSUE TITLE
[Perfomance]Dilated/Atrous Conv implementation with cudnn

### ISSUE THREAD

**Issue by MlWoo** [tensorflow/tensorflow#24559]
**System information**
- TensorFlow version (TF 1.12.0):
- Are you willing to contribute it (Yes):

**Describe the feature and the current behavior/state.**
The [doc](https://www.tensorflow.org/api_docs/python/tf/nn/atrous_conv2d) and the [code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/nn_ops.py#L947) shows that dilated conv is implemented with traival ops(space_to_batch->regular conv->batch_to_space in python level. And the python code does not pass dilations parameters to lower level code. However both the registered [dilated conv ops](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/nn_ops.cc#L265), [gpu code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/cuda/cuda_dnn.cc#L2901) and [cpu code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/eigen_spatial_convolutions.h#L1568) are ready to handle with dilatied conv. It is easy to implement dialted conv with cudnn by modifying the python level code.

**Will this change the current api? How?**
NO.

**Who will benefit with this feature?**
who deploy the model which has dilated conv

**Any Other info.**
time of my model reduces from 350ms to 216ms on 1080ti.

**Comment by gunan** [comment]
I am not the correct assignee for this. Please redirect to performance team.

**Comment by rmothukuru** [comment]
@MlWoo,
Sorry for the delayed response. [This comment](https://github.com/tensorflow/tensorflow/pull/25025#issuecomment-473283030) from the PR states:

> I am unable to see exactly what the gain is from doing this. Currently convolution supports dilation as a parameter but this code would not have a backwards pass which works on a CPU.

Also, no one from the Developer Community seems to be interested in this feature. Can you please confirm if we can close this issue? Thanks!
