### ISSUE TITLE
 Tensorflow c++ compile error on linux collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by 95xueqian** [tensorflow/tensorflow#24561]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):
source
- TensorFlow version:
r1.8
- Installed using :
bazel 0.16.1
- GCC/Compiler version (if compiling from source):
5.4.0
- CUDA/cuDNN version:
9.0 / 7.4.2
- GPU model and memory:
GPU
**Describe the problem**

compile TensorFlow C++ 
bazel build --config=monolithic tensorflow:libtensorflow_cc.so
use 
g++ -std=c++11 -o tf_example \
-I/usr/local/include/tf \
-I/usr/local/include/eigen3 \
-g -Wall -D_DEBUG -Wshadow -Wno-sign-compare -w  \
-L/usr/local/lib/libtensorflow_cc \
`pkg-config --cflags --libs protobuf` -ltensorflow_cc test.cpp

to run test.cpp 
have error ：
/tmp/ccPa2mDH.o: In function `main':
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:9: undefined reference to `tensorflow::Scope::NewRootScope()'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:11: undefined reference to `tensorflow::Input::Initializer::Initializer(std::initializer_list<tensorflow::Input::Initializer> const&)'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:11: undefined reference to `tensorflow::ops::Const(tensorflow::Scope const&, tensorflow::Input::Initializer const&)'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:13: undefined reference to `tensorflow::Input::Initializer::Initializer(std::initializer_list<tensorflow::Input::Initializer> const&)'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:13: undefined reference to `tensorflow::ops::Const(tensorflow::Scope const&, tensorflow::Input::Initializer const&)'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:15: undefined reference to `tensorflow::Scope::WithOpName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:15: undefined reference to `tensorflow::ops::MatMul::MatMul(tensorflow::Scope const&, tensorflow::Input, tensorflow::Input, tensorflow::ops::MatMul::Attrs const&)'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:15: undefined reference to `tensorflow::Scope::~Scope()'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:17: undefined reference to `tensorflow::ClientSession::ClientSession(tensorflow::Scope const&)'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:19: undefined reference to `tensorflow::ClientSession::Run(std::vector<tensorflow::Output, std::allocator<tensorflow::Output> > const&, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*) const'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:19: undefined reference to `tensorflow::internal::LogMessageFatal::LogMessageFatal(char const*, int)'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:19: undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:21: undefined reference to `tensorflow::internal::LogMessage::LogMessage(char const*, int, int)'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:21: undefined reference to `tensorflow::internal::LogMessage::~LogMessage()'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:17: undefined reference to `tensorflow::ClientSession::~ClientSession()'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:9: undefined reference to `tensorflow::Scope::~Scope()'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:13: undefined reference to `tensorflow::Scope::~Scope()'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:19: undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:21: undefined reference to `tensorflow::internal::LogMessage::~LogMessage()'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:17: undefined reference to `tensorflow::ClientSession::~ClientSession()'
/usr/Data/newdataset/mask-rcnn/tf_c/tensorflow-1.8.0/test.cpp:9: undefined reference to `tensorflow::Scope::~Scope()'
/tmp/ccPa2mDH.o: In function `tensorflow::TfCheckOpHelper[abi:cxx11](tensorflow::Status, char const*)':
/usr/local/include/tf/tensorflow/core/lib/core/status.h:127: undefined reference to `tensorflow::TfCheckOpHelperOutOfLine[abi:cxx11](tensorflow::Status const&, char const*)'
/tmp/ccPa2mDH.o: In function `tensorflow::TensorShapeRep::~TensorShapeRep()':
/usr/local/include/tf/tensorflow/core/framework/tensor_shape.h:510: undefined reference to `tensorflow::TensorShapeRep::DestructorOutOfLine()'
/tmp/ccPa2mDH.o: In function `tensorflow::core::RefCounted::~RefCounted()':
/usr/local/include/tf/tensorflow/core/lib/core/refcount.h:79: undefined reference to `tensorflow::internal::LogMessageFatal::LogMessageFatal(char const*, int)'
/usr/local/include/tf/tensorflow/core/lib/core/refcount.h:79: undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
/tmp/ccPa2mDH.o: In function `tensorflow::Tensor::operator=(tensorflow::Tensor const&)':
/usr/local/include/tf/tensorflow/core/framework/tensor.h:170: undefined reference to `tensorflow::Tensor::CopyFromInternal(tensorflow::Tensor const&, tensorflow::TensorShape const&)'
/tmp/ccPa2mDH.o: In function `tensorflow::Input::Input(tensorflow::Output const&)':
/usr/local/include/tf/tensorflow/cc/framework/ops.h:204: undefined reference to `tensorflow::Tensor::Tensor()'
/usr/local/include/tf/tensorflow/cc/framework/ops.h:204: undefined reference to `tensorflow::Tensor::~Tensor()'
/tmp/ccPa2mDH.o: In function `tensorflow::Input::Initializer::~Initializer()':
/usr/local/include/tf/tensorflow/cc/framework/ops.h:105: undefined reference to `tensorflow::Tensor::~Tensor()'
/tmp/ccPa2mDH.o: In function `tensorflow::Input::~Input()':
/usr/local/include/tf/tensorflow/cc/framework/ops.h:97: undefined reference to `tensorflow::Tensor::~Tensor()'
/tmp/ccPa2mDH.o: In function `tensorflow::TensorShape::TensorShape(std::initializer_list<long long>)':
/usr/local/include/tf/tensorflow/core/framework/tensor_shape.h:291: undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase(std::initializer_list<long long>)'
/tmp/ccPa2mDH.o: In function `tensorflow::Input::Initializer::Initializer<float, void>(std::initializer_list<float> const&)':
/usr/local/include/tf/tensorflow/cc/framework/ops.h:138: undefined reference to `tensorflow::Tensor::Tensor()'
/usr/local/include/tf/tensorflow/cc/framework/ops.h:141: undefined reference to `tensorflow::Tensor::Tensor(tensorflow::DataType, tensorflow::TensorShape const&)'
/usr/local/include/tf/tensorflow/cc/framework/ops.h:141: undefined reference to `tensorflow::Tensor::~Tensor()'
/usr/local/include/tf/tensorflow/cc/framework/ops.h:141: undefined reference to `tensorflow::Tensor::~Tensor()'
/usr/local/include/tf/tensorflow/cc/framework/ops.h:138: undefined reference to `tensorflow::Tensor::~Tensor()'
/tmp/ccPa2mDH.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* tensorflow::internal::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const*)':
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:184: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::CheckOpMessageBuilder(char const*)'
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:186: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::ForVar2()'
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:187: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::NewString[abi:cxx11]()'
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:184: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:184: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
/tmp/ccPa2mDH.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* tensorflow::internal::MakeCheckOpString<long, int>(long const&, int const&, char const*)':
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:184: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::CheckOpMessageBuilder(char const*)'
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:186: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::ForVar2()'
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:187: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::NewString[abi:cxx11]()'
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:184: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:184: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
/tmp/ccPa2mDH.o: In function `tensorflow::TTypes<float, 2ul, long>::Tensor tensorflow::Tensor::tensor<float, 2ul>()':
/usr/local/include/tf/tensorflow/core/framework/tensor.h:569: undefined reference to `tensorflow::Tensor::CheckTypeAndIsAligned(tensorflow::DataType) const'
/tmp/ccPa2mDH.o: In function `tensorflow::TTypes<float, 1ul, long>::Tensor tensorflow::Tensor::shaped<float, 1ul>(tensorflow::gtl::ArraySlice<long long>)':
/usr/local/include/tf/tensorflow/core/framework/tensor.h:666: undefined reference to `tensorflow::Tensor::CheckTypeAndIsAligned(tensorflow::DataType) const'
/tmp/ccPa2mDH.o: In function `Eigen::DSizes<long, 2> tensorflow::TensorShape::AsEigenDSizes<2>() const':
/usr/local/include/tf/tensorflow/core/framework/tensor_shape.h:463: undefined reference to `tensorflow::TensorShape::CheckDimsEqual(int) const'
/tmp/ccPa2mDH.o: In function `void tensorflow::Tensor::FillDimsAndValidateCompatibleShape<1ul>(tensorflow::gtl::ArraySlice<long long>, std::array<long, 1ul>*) const':
/usr/local/include/tf/tensorflow/core/framework/tensor.h:630: undefined reference to `tensorflow::internal::LogMessageFatal::LogMessageFatal(char const*, int)'
/usr/local/include/tf/tensorflow/core/framework/tensor.h:630: undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
/usr/local/include/tf/tensorflow/core/framework/tensor.h:636: undefined reference to `tensorflow::internal::LogMessageFatal::LogMessageFatal(char const*, int)'
/usr/local/include/tf/tensorflow/core/framework/tensor.h:636: undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
/usr/local/include/tf/tensorflow/core/framework/tensor.h:630: undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
/usr/local/include/tf/tensorflow/core/framework/tensor.h:636: undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
/tmp/ccPa2mDH.o: In function `Eigen::DSizes<long, 2> tensorflow::TensorShape::AsEigenDSizesWithPadding<2>() const':
/usr/local/include/tf/tensorflow/core/framework/tensor_shape.h:470: undefined reference to `tensorflow::TensorShape::CheckDimsAtLeast(int) const'
/usr/local/include/tf/tensorflow/core/framework/tensor_shape.h:473: undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::dims() const'
/usr/local/include/tf/tensorflow/core/framework/tensor_shape.h:474: undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::dim_size(int) const'
/usr/local/include/tf/tensorflow/core/framework/tensor_shape.h:476: undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::dims() const'
/tmp/ccPa2mDH.o: In function `void std::_Destroy<tensorflow::Tensor>(tensorflow::Tensor*)':
/usr/include/c++/5/bits/stl_construct.h:93: undefined reference to `tensorflow::Tensor::~Tensor()'
/tmp/ccPa2mDH.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* tensorflow::internal::MakeCheckOpString<long long, long long>(long long const&, long long const&, char const*)':
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:184: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::CheckOpMessageBuilder(char const*)'
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:186: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::ForVar2()'
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:187: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::NewString[abi:cxx11]()'
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:184: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
/usr/local/include/tf/tensorflow/core/platform/default/logging.h:184: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
collect2: error: ld returned 1 exit status

**Comment by billyceline** [comment]
Got the same problem!

**Comment by 274869388** [comment]
Could you resovel it?

**Comment by gunan** [comment]
I have a feeling this is due to missing `-D_GLIBCXX_USE_CXX11_ABI=1` when building `test.cpp`.
But looks like I completely missed this issue.

I will close this issue now, but please file a new issue if you still see this happening with 2.2, or master.
