### ISSUE TITLE
bazel build failed

### ISSUE THREAD

**Issue by striker890** [tensorflow/tensorflow#24563]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 1809 Build 17763.195
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): compile from source
- TensorFlow version: master
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): Microsoft Build Tools 2015 Update 3
- CUDA/cuDNN version: 10.0
- GPU model and memory: Nvidia RTX 2080 TI, 16GB RAM

**Describe the problem**

Built as in: https://www.tensorflow.org/install/source_windows
-->console output for configuration and build process see below
Build process failed with "C++ compilation of rule '//tensorflow/compiler/xla/service/gpu:fusion_merger' failed (Exit 2): python.exe failed: error executing command"

**Any other info / logs**
console output:
[buildconsole.txt](https://github.com/tensorflow/tensorflow/files/2708791/buildconsole.txt)

**Comment by rootkitchao** [comment]
Compiling Tensorflow-GPU in Windows seems to have some problems with XLA enabled.I also encountered the same issue when compiling Tensorflow-GPU in a similar environment.But disabling XLA can solve this issue.

**Comment by ymodak** [comment]
@striker890 Did you get a chance to try @rootkitchao 's suggestion? Is this still an issue for you?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
