### ISSUE TITLE
leaky_relu - buggy when alpha > 1 or alpha < 0

### ISSUE THREAD

**Issue by sergeigofman** [tensorflow/tensorflow#24566]
tf.nn.leaky_relu() is implemented as math_ops.maximum(alpha * features, features, name=name). This won't work if alpha > 1 or alpha < 0. Although this is not expected, there is nothing that prevents users from setting alpha parameter as such.
A better implementation could be nn.relu(features) - alpha*nn.relu(-features) which won't suffer from the above issue.

**Comment by storm-rain** [comment]
@jvishnuvardhan  Hi，I want to know when this problem will be solved. Thank you
