### ISSUE TITLE
external/png_archive/BUILD:23:1: Executing genrule @png_archive//:configure failed: bash failed

### ISSUE THREAD

**Issue by ElfinFairy** [tensorflow/tensorflow#2457]
### Environment info
Operating System:
Red Hat 4.8.3-9

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
/usr/local/cuda-7.5/ 
cudnn-7.5-linux-x64-v5.0-ga-tgz
libcudnn.so.5

If installed from sources, provide the commit hash:

### Steps to reproduce
1. Getting bazel from https://github.com/bazelbuild/bazel/archive/0.2.3.tar.gz
2. On 18, May , I Get tensor flow via git clone --recurse-submodules https://github.com/tensorflow/tensorflow
3. Running command /home/admin/bazel/bazel_source/bazel-0.2.3/output/bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer --verbose_failures, I got error
external/png_archive/BUILD:23:1: Executing genrule @png_archive//:configure failed

### What have you tried?
1.  After I modified external/png_archive/BUILD:30 by adding CPPFLAGS=\"-I /usr/local/zlib/usr /include\"; LDFLAGS=\"-L /usr/local/zlib/lib64\" in cmd, it would get the error "external/png_archive/BUILD:33:1: C++ compilation of rule '@png_archive//:png' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/admin/.cache/bazel/_bazel_admin/b33b4c76bea799d489291f7bcf5433ae/tensorflow && \
  exec env - \
    PATH=/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/X11R6/bin:/home/zy80232/.local/bin:/home/zy80232/bin \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 -iquote external/png_archive -iquote bazel-out/host/genfiles/external/png_archive -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/host/genfiles/external/png_archive/libpng-1.2.53 -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers '-frandom-seed=bazel-out/host/bin/external/png_archive/_objs/png/external/png_archive/libpng-1.2.53/pngwutil.o' -MD -MF bazel-out/host/bin/external/png_archive/_objs/png/external/png_archive/libpng-1.2.53/pngwutil.d -c external/png_archive/libpng-1.2.53/pngwutil.c -o bazel-out/host/bin/external/png_archive/_objs/png/external/png_archive/libpng-1.2.53/pngwutil.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/png_archive/libpng-1.2.53/pngwutil.c:16:0:
external/png_archive/libpng-1.2.53/png.h:548:18: fatal error: zlib.h"

2. Then I added one extra line in png_archive/BUILD:38 by copts = ["-Iexternal/zlib/usr/include"], and I get the error  "/home/admin/.cache/bazel/_bazel_admin/b33b4c76bea799d489291f7bcf5433ae/external/png_archive/BUILD:33:1: undeclared inclusion(s) in rule '@png_archive//:png':
this rule is missing dependency declarations for the following files included by 'external/png_archive/libpng-1.2.53/pngwio.c':
  'external/zlib/usr/include/zlib.h'
  'external/zlib/usr/include/zconf.h'"

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by vrv** [comment]
Before your changes, what were the full output logs from bazel ? (add `--verbose_failures`)

**Comment by ElfinFairy** [comment]
Hi, Vrv, thanks for your quick response, just paste the whole log as belows:
bazel build --sandbox_debug -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer --verbose_failures 
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /home/admin/.cache/bazel/_bazel_admin/b33b4c76bea799d489291f7bcf5433ae/external/png_archive/BUILD:23:1: Executing genrule @png_archive//:configure failed: bash failed: error executing command 
  (cd /home/admin/.cache/bazel/_bazel_admin/b33b4c76bea799d489291f7bcf5433ae/tensorflow && \
  exec env - \
    PATH=/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/X11R6/bin:/home/zy80232/.local/bin:/home/zy80232/bin:/home/admin/bazel/bazel_source/bazel-0.2.2b/output \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; pushd external/png_archive/libpng-1.2.53; workdir=$(mktemp -d -t tmp.XXXXXXXXXX); cp -a * $workdir; pushd $workdir; ./configure --enable-shared=no --with-pic=no; popd; popd; cp $workdir/config.h bazel-out/local_linux-opt/genfiles/external/png_archive/libpng-1.2.53; rm -rf $workdir;'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/home/admin/.cache/bazel/_bazel_admin/b33b4c76bea799d489291f7bcf5433ae/tensorflow/external/png_archive/libpng-1.2.53 /home/admin/.cache/bazel/_bazel_admin/b33b4c76bea799d489291f7bcf5433ae/tensorflow
/tmp/tmp.l1NdEzzkxa /home/admin/.cache/bazel/_bazel_admin/b33b4c76bea799d489291f7bcf5433ae/tensorflow/external/png_archive/libpng-1.2.53 /home/admin/.cache/bazel/_bazel_admin/b33b4c76bea799d489291f7bcf5433ae/tensorflow
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking how to print strings... printf
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking how to run the C preprocessor... gcc -E
checking for sed... /usr/bin/sed
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for ANSI C header files... (cached) yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for working strtod... yes
checking for memset... yes
checking for pow... no
checking for pow in -lm... yes
checking for zlibVersion in -lz... no
configure: error: zlib not installed
Target //tensorflow/cc:tutorials_example_trainer failed to build
INFO: Elapsed time: 7.337s, Critical Path: 6.10s

**Comment by vrv** [comment]
You probably need to install the zlib development libraries, I guess.
