### ISSUE TITLE
Cannot import tensorflow.spectral

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#24576]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac OS X 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
VERSION=1.13.0-dev20181225
GIT_VERSION=b'v1.12.0-5131-gc6f3c5dc48'
- Python version:
3.6.6
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
I cannot import `tensorflow.spectral`.

**Describe the expected behavior**
It should be possible.

**Code to reproduce the issue**

```python
from tensorflow import spectral
```

**Other info / logs**
Here is the stacktrace:

```python
>>> from tensorflow import spectral
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'spectral'
```

**Comment by martinwicke** [comment]
We removed `tf.spectral` and replaced it with `tf.signal`, which also includes more functional related to signal processing. We should probably update the RFC, but it's probably better to do it once all these changes are solidified.
