### ISSUE TITLE
[Performance] Unnecessary 'memcpy' in Gather Op

### ISSUE THREAD

**Issue by candyzone** [tensorflow/tensorflow#24575]
**Describe the current behavior**
In distributed mode, user define a Graph, 'distribute_runtime' partition graph, register graph, and then run graph, For example as below.
![image](https://user-images.githubusercontent.com/7778833/50445822-3140b700-094c-11e9-8d5e-78418403836f.png)
ps: Gather Op generates a new Tensor (allocation and **memcpy**), Send Op put the Tensor to local Rendezvous's table.
worker: Recv Op triggers GRPC RecvTensorResponse method via remote Rendezvous, calls EncodeTensorToByteBuffer(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/grpc_tensor_coding.cc), if DataTypeCanUseMemcpy==true, encodes tensor with wire format instead of TensorProto serialization. in this case, TensorEncoding doesn't depend on a continuous memory(Gather Op output Tensor)

**Describe the expected behavior**
When Gather Op -> Send Op and Tensor's dtype is simple type, Gather Op's output is a 'IndexedTensor' without memcpy. The 'IndexedTensor' contains some offsets of IDs and a RefCounted TensorBuffer. In GRPC ZeroCopyStream, send the list<pair<pointer, length>> by grpc::Slice.
Performance: reduce a memcpy
Same optimization can apply to other Op, such as: Concat Op, Slice Op ...

**Other info**

**Comment by candyzone** [comment]
@saeta thanks

**Comment by sushreebarsa** [comment]
@candyzone Could you please let us know if this issue still persists?
Some of the arguments are deprecated in tf.gather, please refer to this [doc](https://www.tensorflow.org/api_docs/python/tf/gather) and let us know if it helps?
Thank you!
