### ISSUE TITLE
The performance with profiler seems much slower than normal

### ISSUE THREAD

**Issue by venuswu** [tensorflow/tensorflow#24572]
I found something uninterpretable when profiling with tensorflow profiler.
    The time measured with profiler seems much slower than without it. 
            eg: I translate a sentence with the model Transformer, it takes 70ms normally, but it takes 220ms with profiler. code as follows:
             with tf.contrib.tfprof.ProfileContext('/home/work/tmp/profile') as pctx
        Does profiler take too much overhead? Which part costs so much time?? Does the overhead take place in every op or between ops??

**Comment by qqfish** [comment]
Most of the overhead of tfprof are between steps. It takes a long time to parse the data it collect. So the result is more accurate than it appear.

**Comment by jvishnuvardhan** [comment]
@venuswu Closing this out since I understand it to be resolved, but please let me know if I'm mistaken.
