### ISSUE TITLE
Request for function argument for tf.device in eager mode

### ISSUE THREAD

**Issue by nikhil-dev** [tensorflow/tensorflow#24571]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No custom code.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: Using pip install.
- **TensorFlow version (use command below)**: 1.12
- **Python version**: 2.7.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
In graph mode, `tf.device()` accepts either a device specifier or a function that specifies ops that should run on a specific device. However in eager mode, there's no ability to pass in a function.

It's marked as a todo in the code base, so might be in the pipeline but I'd love to know if there's a rough time estimate/anything in the works?
### Source code / logs
Here's the place in the codebase where its marked as a TODO:
https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/python/framework/ops.py#L4928

**Comment by asimshankar** [comment]
There are currently no plans to pursue this.

That said, could you elaborate on the use case? Quitting from [the documentation](https://www.tensorflow.org/api_docs/python/tf/Graph#device):

```
If it is a function, it will be treated as a function from Operation objects to device name strings, and invoked each time a new Operation is created. The Operation will be assigned to the device with the returned name.
```

With eager execution, there is no `Operation` object, as there is no symbolic execution. So, I'm curious about what function you would be using that doesn't just return a string that can be used.

Perhaps I'm missing something.

**Comment by nikhil-dev** [comment]
Ah ok I didn't realize there's no `Operation` object in eager mode.

My use case is the following: I have a LSTM network with a Gaussian distribution output. I'm using the TF probability library to create a distribution object parametrized by the outputs of my LSTM network. 

One of the methods of this TF Probability distribution object invokes the op `MatrixTriangularSolve` at some point in the call stack. This op seems to be much slower on GPU than on CPU. I was hoping to use the function to force this op to run on CPU. In the forward pass, I can do this using the `tf.device` context manager. But in the backward pass, this seems to get run on the GPU which makes the backward pass painfully slow.

I'd be happy with an alternate solution that forces this op to run on CPU during the backward pass.

**Comment by nikhil-dev** [comment]
@asimshankar Checking to see if you have any inputs/updates regarding the above?

**Comment by nikhil-dev** [comment]
@asimshankar Tried the above. By looking at the output from setting `log_device_placement=True`, I see that during the forward pass, it gets scheduled on CPU (even without the above hack). During the backward pass, `matrix_triangular_solve` still seems to be being placed on the GPU even with the hack.

**Comment by asimshankar** [comment]
@nikhil-dev : I updated the hack in the comment above (https://github.com/tensorflow/tensorflow/issues/24571#issuecomment-453630352), I think it works on the backward pass now too.

**Comment by nikhil-dev** [comment]
Works now - thank you!!

**Comment by rmothukuru** [comment]
@nikhil-dev,
Can you please confirm if we can close this issue as your problem has been resolved with [this comment](https://github.com/tensorflow/tensorflow/issues/24571#issuecomment-454113321)? Thanks!
