### ISSUE TITLE
Redundant summary in KMeansClustering

### ISSUE THREAD

**Issue by IvanUkhov** [tensorflow/tensorflow#24574]
The estimator produces two summaries: `loss` and `loss/raw`. The former is due to the Estimator API, and the latter is due to [this line](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/contrib/factorization/python/ops/kmeans.py#L209). The summaries are identical, and I’m wondering what the reason for keeping the latter is. Is it that the Estimator API can, in some cases, augment the loss passed to it, or is it a leftover from before the API was introduced? Thanks!

**Comment by ymodak** [comment]
@theweiho Can you please take a look? Thanks!

**Comment by IvanUkhov** [comment]
I suppose this one is no longer relevant, as `contrib` has been moved out.
