### ISSUE TITLE
Tf cast function not changing data type of the source variable

### ISSUE THREAD

**Issue by ram1897** [tensorflow/tensorflow#24580]
On using Tf.cast(source_variable,dtype=tf.int64), the datatype of the source variable remains unchanged. If I assign the result of tf.cast to a new_variable, the new_variable's datatype is equal to the "dtype" but source_variable.dtype remains the same.

Example:
source_variable data-type is float32
result = tf.cast(source_variable,tf.int32)
The Data type of "result" is int32, but the datatype of "source_variable" is float32.

How do I change the datatype of the source_variable to int32?

**Comment by jvishnuvardhan** [comment]
@ram1897, tf.cast function is working as expected. tf.cast creates a new tensor with the specified data type and does not alter the original variable. Here is the solution for your question.  

source_variable = tf.cast(source_variable,tf.int32)     

Please understand that Github is primarily for addressing bugs in installation and performance. Stackoverflow is a better place to ask/discuss questions like these.

**Comment by jvishnuvardhan** [comment]
@ram1897 
Please post this @stockoverflow as there is a big community to answer questions like this.
https://stackoverflow.com/questions/35596629/how-to-convert-tf-int64-to-tf-float32

 I think you can use "name" argument to control the name attribute to some extent as shown below.

import tensorflow as tf
x=tf.constant(1)
print(x.dtype)
print(x.name)
name=x.name
name=name.split(':')[0]
print(name)
x=tf.cast(x,tf.float32,name=name)
x=tf.cast(x,tf.float32)
print(x.dtype)
print(x.name)

Please post any followup queries in stackoverflow.

**Comment by ram1897** [comment]
@jvishnuvardhan I have opened up a stackoverflow question 10 days back. No replies from the community there.
**Did you execute the snippet in your comment?**
The two Printing Name functions in your snippet will give you:
Const:0 and Const_1:0 which is the problem which I reported in the first place.
I want both print statements to give the output as Const:0

Is this a **Bug** in Tensorflow or the function is meant to behave like this.

**Comment by jvishnuvardhan** [comment]
Yes. I executed it.
The function is performing as it was intended. 
I think the attribute is only referencing a variable. When you change the type of a variable, it's reference also changes. If you want to use the attribute for some comparison, you could read, split and compare.
Thanks again. This channel is not for support questions like this.
