### ISSUE TITLE
Failed to Build Tensorflow due to extension_dict.cc on Mac OSX

### ISSUE THREAD

**Issue by maisora** [tensorflow/tensorflow#24581]
I am using the latest version of Mac 10.14.1, Python 3.7 (through Anaconda, I then later installed Python 3.6 in an environment to see if it would work, but the same error appears), and Bazel 0.15.0. 
When configuring the install, I put N for everything and used default for all others. 

I then executed the following to build a CPU-only version since I am on a Mac:

bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

After a long time of waiting for the build process, I've hit the following error that caused my build to fail:

```
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package (1 packages loaded).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_maisora/ceb5b62c0dc483a80db02f088b1ce574/external/protobuf_archive/BUILD:659:1: C++ compilation of rule '@protobuf_archive//:python/google/protobuf/pyext/_message.so' failed (Exit 1)
external/protobuf_archive/python/google/protobuf/pyext/extension_dict.cc:184:7: error: assigning to 'char *' from incompatible type 'const char *'
  if (PyString_AsStringAndSize(arg, &name, &name_size) < 0) {
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/protobuf_archive/python/google/protobuf/pyext/extension_dict.cc:56:22: note: expanded from macro 'PyString_AsStringAndSize'
       ((*(charpp) = PyUnicode_AsUTF8AndSize(ob, (sizep))) == NULL? -1: 0): \
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.701s, Critical Path: 2.59s
INFO: 17 processes: 17 local.
FAILED: Build did NOT complete successfully
```

How do I get around this to successfully build tensorflow?

**Comment by maisora** [comment]
This is still an issue, I will try uninstalling anaconda and reinstalling with py36 and report back.

**Comment by ymodak** [comment]
Were you able to get it running yet? Can you please share your progress? Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by milinddeore** [comment]
With exactly same build environment got exactly same error. 
Added information, i tried with tensorflow v1.8.0 and v1.12.0 tags. 
Is there a fix for this?
