### ISSUE TITLE
Why can't Python 2.7 install tensorFlow with windows operating system ?  Does TensorFlow not support Python 27 now? Is there a kind person who can tell me, I really urgent!

### ISSUE THREAD

**Issue by hnustxyxm** [tensorflow/tensorflow#24589]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by ymodak** [comment]
I am afraid you are right. Unfortunately, TensorFlow is not supported on Windows with Python 2.7.
