### ISSUE TITLE
TF Identity - SparseTensor - Not Working

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#24582]
`tf.identity` seems to be not working with SparseTensor. This is a problem, because it makes quite impossible to use them with `tf.control_dependencies`.

Below a very simple example:

```python
import tensorflow as tf

a = tf.SparseTensor([[0,0]], [0], [800, 256])

print_op = tf.print("Hello world")

with tf.control_dependencies([print_op]):
    a = tf.identity(a)
```

```python
TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("SparseTensor_5/indices:0", shape=(1, 2), dtype=int64), values=Tensor("SparseTensor_5/values:0", shape=(1,), dtype=int32), dense_shape=Tensor("SparseTensor_5/dense_shape:0", shape=(2,), dtype=int64)). Consider casting elements to a supported type.
```

**Comment by hgadig** [comment]
What is the tensorflow version you used ? Also please fill [this](https://github.com/tensorflow/tensorflow/issues/new/choose) template which helps us to look into the issue.

**Comment by DEKHTIARJonathan** [comment]
I used the latest version of tensorflow.
I will check with the nightly build version.

**Comment by DEKHTIARJonathan** [comment]
@hgadig so I just tested with the following containers:

* `tensorflow/tensorflow:latest-gpu-py3 (413b9533f92a)` => TF 1.12.0, CUDA 9
* `tensorflow/tensorflow:nightly-gpu-py3 (e06d8999a068)` => TF 1.13.0-dev20181228, CUDA 10

The error is reproducible on both. So it should be live on master ;)

**Comment by helinwang** [comment]
Workaround for SparseTensor:

```
import tensorflow as tf

a = tf.SparseTensor([[0,0]], [0], [800, 256])
print_op = tf.print("Hello world")
with tf.control_dependencies([print_op]):
  a = tf.SparseTensor(a.indices, tf.identity(a.values), a.dense_shape)
```
Note that you must use tf.identity somewhere (e.g., `tf.identity(a.values)`), otherwise TF optimizes away the statement.

**Comment by DEKHTIARJonathan** [comment]
As you said it's a nice workaround, but this operation has a non negligible cost.
Would it be just possible to make sure SparseTensors are supported by the identity operation ?

**Comment by jvishnuvardhan** [comment]
Looks like this was already resolved in recent TF version. I checked it with TF2.8. [Here](https://colab.research.google.com/gist/jvishnuvardhan/4dadabb4bb5fd01305edb7c49fe17423/untitled1170.ipynb) is a gist for reference. 

I am closing this issue as this was resolved. Thanks!
