### ISSUE TITLE
Estimators + tf.data iterators incompatible with eager execution enabled

### ISSUE THREAD

**Issue by traviskaufman** [tensorflow/tensorflow#24592]
> Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

Yes

> OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

MacOS Mojave version 10.14.2

> Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:

N/A

> TensorFlow installed from (source or binary):

binary

> TensorFlow version (use command below):

v1.12.0-rc2-3-ga6d8ffae09 1.12.0

> Python version:

Python 3.6.0

> Bazel version (if compiling from source):

N/A

> GCC/Compiler version (if compiling from source):

N/A

> CUDA/cuDNN version:

N/A

> GPU model and memory:

N/A

**Describe the current behavior**

Say you train an estimator using [tf.estimator.train_and_evaluate](https://www.tensorflow.org/api_docs/python/tf/estimator/train_and_evaluate). The `input_fn` to your estimator returns a [tf.data.Dataset](https://www.tensorflow.org/api_docs/python/tf/data/Dataset). you may want to write a small program to make predictions over a subset of data to sanity-check model training and gain more insight into how your estimator makes predictions, without having to go through the trouble of deploying your model. You may want to, for simplicity, use eager execution to do this. Something like:

```python
import tensorflow as tf; tf.enable_eager_execution()

estimator = tf.estimator.Estimator(
        model.model_fn,
        warm_start_from=tf.train.latest_checkpoint(args.job_dir))
it = model_input_fn().make_one_shot_iterator()

batch = it.get_next() # Returns <features>, <label>
predictions = estimator.predict(lambda: tf.data.Dataset.from_tensor_slices(batch))
print('Prediction:', next(predictions))
print('Label:', batch[1])
```

This currently throws the following error:

```
RuntimeError: Attempting to capture an EagerTensor without building a function.
```

**Describe the expected behavior**

Ideally this would just work? Unless I'm missing something 😄 

**Code to reproduce the issue**

1. Train a toy estimator using `tf.estimator.train_and_evaluate`. Have its input function return a dataset.
1. Write a script similar to the one written above, which basically creates an estimator warm-started from the latest checkpoint in your training job, calls the input function to get the actual labels, then tries to compare that to prediction output from an estimator.

**Other info / logs**

The problem _appears_ to be something that `from_tensor_slices` is doing. Relevant part of my traceback is below

```
 File "WORKDIR/model_evaluation.py", line 61, in <lambda>
    predictions = estimator.predict(lambda: tf.data.Dataset.from_tensor_slices(batch))
  File "PYTHONDIR/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 289, in from_tensor_slices
    return TensorSliceDataset(tensors)
  File "PYTHONDIR/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1565, in __init__
    for i, t in enumerate(nest.flatten(tensors))
  File "PYTHONDIR/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1565, in <listcomp>
    for i, t in enumerate(nest.flatten(tensors))
  File "PYTHONDIR/site-packages/tensorflow/python/framework/ops.py", line 1050, in convert_to_tensor
    as_ref=False)
  File "PYTHONDIR/site-packages/tensorflow/python/framework/ops.py", line 1106, in internal_convert_to_tensor
    raise RuntimeError("Attempting to capture an EagerTensor without "
RuntimeError: Attempting to capture an EagerTensor without building a function.
```

**Comment by yongtang** [comment]
@traviskaufman Would you mind to provide a full reproducible code sample that triggers the error? The code snippet you pasted may not be complete.

**Comment by sadilek** [comment]
I ran into the same issue. I think the problem is that `predict()` runs a new session, and in that context, accessing the EagerTensor is not supported. A workaround I found works is to convert the tensor into a numpy array and convert it with `numpy_input_fn()`:
```
predictions = estimator.predict(tf.estimator.inputs.numpy_input_fn(
  {"foo": features["foo"].numpy()}, shuffle=False))
```

My first attempt was to pass the numpy array into `Dataset.from_tensor_slices()`:
```
predictions = estimator.predict(
  lambda: tf.data.Dataset.from_tensor_slices({"x": features["foo"].numpy()}))
```
But that leads to an infinitely yielding `predictions`. I don't know why.

**Comment by alextp** [comment]
The problem is in these lines:

```
it = model_input_fn().make_one_shot_iterator()

batch = it.get_next() # Returns <features>, <label>
predictions = estimator.predict(lambda: tf.data.Dataset.from_tensor_slices(batch))
```

If you really want to predict on this single batch, going through numpy is the way to go:

```
predictions = estimator.predict(lambda: tf.data.Dataset.from_tensor_slices(batch.numpy()))
```

but this is unusably slow so I think you want to do


```
predictions = estimator.predict(model_input_fn)
```

right?

**Comment by vmirly** [comment]
I have the same issue. If I load a dataset from tensorflow_datasets, then how should I define the input-function. Here is my code:

```python
mnist, info = tfds.load('mnist', with_info=True)

ds_train_orig, ds_test = mnist['train'], mnist['test']

## Step 1: define the input-function
def train_input_fn(dataset, batch_size):
    dataset = dataset.map(lambda x:({'image-pixels':tf.reshape(x['image'], (-1,))}, 
                                    x['label']))
    return dataset.shuffle(1000).repeat().batch(batch_size)

## Step 2: define the feature_column:
image_feature_column = tf.feature_column.numeric_column(key='image-pixels',
                                                        shape=(28*28))

# image_feature_column
# NumericColumn(key='image-pixels', shape=(784,), default_value=None, dtype=tf.float32, normalizer_fn=None)


## Step 3:
dnn_classifier = tf.estimator.DNNClassifier(
    feature_columns=image_feature_column,
    hidden_units=[16, 16],
    n_classes=10)

## Step 4:
dnn_classifier.train(
    input_fn=lambda:train_input_fn(ds_train_orig, batch_size=32),
    #lambda:iris_data.train_input_fn(train_x, train_y, args.batch_size),
    steps=20)
```

But this gives me the same error as given in this thread:
```
RuntimeError: Attempting to capture an EagerTensor without building a function.
```

I tried to convert the data (step-1) to NumPy using the `map()` method like this:
```python
def train_input_fn(dataset, batch_size):
    dataset = dataset.map(lambda x:({'features':x['image'].numpy().flatten()}, 
                                    x['label']))
    return dataset.shuffle(1000).repeat().batch(batch_size)
```
but it says that Tensor object does not have attribute numpy.

Is there any example to use a pre-existing dataset object to use with an estimator?
