### ISSUE TITLE
Multi-tower support on each GPU in MirroredStrategy and estimator

### ISSUE THREAD

**Issue by ZhouYuChen** [tensorflow/tensorflow#24595]
**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
*Feature*:
Add an argument like `num_towers_per_gpu`  in `tf.contrib.distribute.MirroredStrategy` to enable multi-tower computation on each GPU.
*Current state*:
Current `tf.contrib.distribute.MirroredStrategy`'s design is one GPU one tower. It does not support mult-tower on one GPU. It has args `devices`, `num_gpus`, `num_gpus_per_worker`, `cross_tower_ops`, `prefetch_on_device`, `auto_shard_dataset`. We can only set the number of GPUs, and the mirrored strategy will assign one tower to each GPU.

**Will this change the current api? How?**
Yes. It will add a new argument like `num_towers_per_gpu` to `tf.contrib.distribute.MirroredStrategy`.

**Who will benefit with this feature?**
This feature can make it available to assign multiple towers on each GPU. It can maximize GPU utilization.

**Any Other info.**

**Comment by yuefengz** [comment]
Why you want multiple replicas per GPU? We'll probably add multiple GPUs per replica for model parallelism but not the opposite.

**Comment by ZhouYuChen** [comment]
It is difficult to apply the batch training approach to some models with dynamic structures. The computation of each tower in some reinforcement learning tasks is small. I think multiple towers per GPU would be a nice feature for that case.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by rmothukuru** [comment]
@ZhouYuChen,
Sorry for the delayed response. In the Tensorflow Version 2.x, since we use [TF Keras](https://www.tensorflow.org/api_docs/python/tf/keras) predominantly and don't use [Estimators](https://www.tensorflow.org/guide/estimator) much, can you please let us know if this Feature is still relevant? Thanks!

**Comment by ZhouYuChen** [comment]
@rmothukuru 
It is not relevant any more. Thanks!
