### ISSUE TITLE
tensorflow parameter server start with no worker_hosts specific in  cluster def

### ISSUE THREAD

**Issue by piaoyats** [tensorflow/tensorflow#24594]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (1.8.0):
- Are you willing to contribute it (Yes):

**Describe the feature and the current behavior/state.**
I'm setting up a distributed tensorflow with ps and worker. Currently tf.train.Server must accept a ClusterDef to define the total cluster before program start.

If I only use ps to store and update variables, use worker to train. Why PS must need to know the worker hosts addrs before it starts.

Suppose I want to setup 1 ps and 2 worker, the cluster_def shows below

For PS:

```
  cluster = tf.train.ClusterSpec({'ps': {0: 'ps0:2222'}})
```
For worker0:

```
  cluster = tf.train.ClusterSpec({'ps': {0: 'ps0:2222'}, 'worker': {0: 'localhost:0'}})
```
For worker1:

```
 cluster = tf.train.ClusterSpec({'ps': {0: 'ps0:2222'}, 'worker': {1: 'localhost:0'}})
```
I don't need to communicate between worker1 and worker0, If i config this, PS and worker can start, but when call sess.run with train_op ,the following fault will cause:

```
tensorflow.python.framework.errors_impl.InternalError: No worker known as 
/job:worker/replica:0/task:0
     [[Node: gradients/LinearRegression/xw_plus_b_grad/BiasAddGrad_S29 = _Recv[client_terminated=false, recv_device="/job:ps/replica:0/task:0/device:CPU:0", send_device="/job:worker/replica:0/task:0/device:CPU:0", send_device_incarnation=-801089107413104296, tensor_name="edge_78_gradients/LinearRegression/xw_plus_b_grad/BiasAddGrad", tensor_type=DT_FLOAT, _device="/job:ps/replica:0/task:0/device:CPU:0"]()]]
```

Seem when GrpcServer::Init, PS did not know any worker info, its channel_cache is empty, RpcRemoteRendezvous::RecvFromRemoteAsync can not find Worker channel and throw errors. The interesting is worker can connect to ps to fetch variable for forward computing.

I don't know if we have any plan to support this usage. I don't know whether the error here is a bug or by-design?

**Will this change the current api? How?**
No
**Who will benefit with this feature?**
We want to when any worker host crash, we can re-launch another worker to continue train, but the new worker may change ip and port. In this case, If we support this feature, we can do worker FO simply
**Any Other info.**

**Comment by byronyi** [comment]
It’s by design. We use the name “ps” in TensorFlow in its nominal sense, without a specialized PS construct. The current SendRecvOps require both side to be aware of each other’s endpoints for duplex communication. 

For example, before each iteration, the worker needs to call RecvTensor RPC to fetch model parameters. It does not use the same channel to push gradients; instead, the PS calls RecvTensor and fetch gradient tensors. Compared to a specialized PS that provides PULL/PUSH semantics, the SendRecvOps gets handy in more complex case like model parallelism.

As for FO, @saeta posted an excellent explanation here: https://github.com/tensorflow/tensorflow/issues/18880#issuecomment-392842564

**Comment by rmothukuru** [comment]
@piaoyats,
Sorry for the delayed response. There is a detailed example for using [Parameter Server Training in asynchronous mode](https://www.tensorflow.org/tutorials/distribute/parameter_server_training). Can you please take a look and let us know if this is what you are looking for? Thanks!
