### ISSUE TITLE
  java.lang.IllegalArgumentException: ConcatOp : Dimensions of inputs should match: shape[0] = [1,1,1,256] vs. shape[13] = [0,1,1,256]

### ISSUE THREAD

**Issue by shenyingying** [tensorflow/tensorflow#24590]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.12
- Python version:3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:9.0/7.0
- GPU model and memory:ZR390

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
   I use yolov2 to train my model,and transplant it to mobile phone,in office demo https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android
it crash,output this bug:
 2018-12-27 09:41:33.780 17423-17443/org.tensorflow.demo E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[input], outputs:[output]
2018-12-27 09:41:33.783 17423-17443/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.demo, PID: 17423
    java.lang.IllegalArgumentException: ConcatOp : Dimensions of inputs should match: shape[0] = [1,1,1,256] vs. shape[13] = [0,1,1,256]
    	 [[{{node concat_9}} = ConcatV2[N=19, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Reshape_152, Reshape_153, Reshape_154, Reshape_155, Reshape_156, Reshape_157, Reshape_158, Reshape_159, Reshape_160, Reshape_161, Reshape_162, Reshape_163, Reshape_164, Reshape_165, Reshape_166, Reshape_167, Reshape_168, Reshape_169, Reshape_170, concat_9/axis)]]
        at org.tensorflow.Session.run(Native Method) 
It confused me  long time,can anyone help me ,thanks a lot 
**Describe the expected behavior**
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@shenyingying Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support. Github is mainly for addressing bugs in installation and performance. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please open new ticket if you see similar issue. Thanks!
