### ISSUE TITLE
Examples for loop control flow ops (Enter/Leave/NextIteration)

### ISSUE THREAD

**Issue by mjwillson** [tensorflow/tensorflow#246]
These are mentioned tantalisingly in the whitepaper, and code for them seems to be present (although omitted from the docs).

It's not clear at all (to me at least) how to use Enter/Leave/NextIteration to actually construct a loop -- an example would be really nice here :-)

In particular I'm interested in whether recurrent networks could be implemented using these constructs, and if there's a reason you chose not to use them in the examples. Is it a case of the looping stuff not being quite ready enough yet in the open source version? Is it that loop control flow doesn't perform as well?

**Comment by rafaljozefowicz** [comment]
Take a look at: https://github.com/tensorflow/tensorflow/issues/208

**Comment by mjwillson** [comment]
Gotcha. Yeah fair enough in that case -- looking forward to the public API :)

I'd still be interested in a simple example even if the API is subject to change, just to get a flavour of what (might) be to come.

For anyone else curious about this, have a look at the referenced MIT paper (http://csg.csail.mit.edu/CSGArchives/memos/Memo-271.pdf ) in particular figure 13. It looks like D == NextIteration, D_reset == Exit/Leave, and that ⊗ == Merge.

This all makes sense, although it seems you need some way to set up a cyclic connection in the graph, to feed the result of NextIteration back into the loop, and I can't figure out how to do that at the moment with the current python API.

**Comment by vrv** [comment]
De-duping with https://github.com/tensorflow/tensorflow/issues/208
