### ISSUE TITLE
set_random_seed with a value too large for an int fails during later call to random()

### ISSUE THREAD

**Issue by maximsch2** [tensorflow/tensorflow#2460]
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN:  No CUDA

If installed from sources, provide the commit hash: 7d9ab3eb485e6eb1778bad4ef01a1cd95b2d22d9

### Steps to reproduce
```python
import tensorflow as tf
tf.set_random_seed(2 ** 70)
sess = tf.InteractiveSession()
tf.random_normal((1,)).eval()
```
Fails with "Value out of range" exception on eval. 

I'd would prefer that it would either fail on `tf.set_random_seed` or just truncate the seed to fit into the field (as this would be semantically correct behavior). Which one should be a correct one? I'd like to make a PR to fix it.

**Comment by mrry** [comment]
Thanks for noticing this and we'd welcome a PR!

@zheng-xq: Since you wrote this code, do you have a preference for the behavior here?

**Comment by zheng-xq** [comment]
Then truncation is the correct behavior. Thanks for noticing this!
