### ISSUE TITLE
possible bug in examples/speech_commands/test_streaming_accuracy.cc

### ISSUE THREAD

**Issue by Alireza89** [tensorflow/tensorflow#24601]
in tensorflow/tensorflow/examples/speech_commands/test_streaming_accuracy.cc line 247 the following code is not correct:

`const int64 audio_data_end = (sample_count - clip_duration_ms);`
it should be corrected as follows:
`const int64 audio_data_end = (sample_count - clip_duration_samples);`

it is wrong because the dimensions do not match. sample_count is in units [sample] but clip_duration_ms is in [ms] units.
Additionally it gives the following error:
`Segmentation fault (core dumped)`

but if audio_data_end is set correctly as i mentioned above, this error would not occur.

**Comment by yongtang** [comment]
@Alireza89 I think you are correct, do you want to create a PR for that?

**Comment by Alireza89** [comment]
@yongtang  Well I don't have a plan to create a PR for now but if it is actually a bug, I hope it gets corrected in the master branch in the future.

**Comment by yongtang** [comment]
@Alireza89 I have created the PR #24613 for the fix. Thanks for your contribution!

**Comment by petewarden** [comment]
Thanks for the fix! The PR has been reviewed, so closing this now.
