### ISSUE TITLE
[Feature Request] Indexing an array of functions

### ISSUE THREAD

**Issue by nunezpaul** [tensorflow/tensorflow#24605]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently using a tensor to index a list of functions is inconsistent. In order to have the same functionality while training I have to chain together a series of tf.cond statements to accomplish the same task. Currently, this can be done in eager execution but not in outside of it.

Example:

```
import tensorflow as tf

tf.enable_eager_execution()

def mul(a):
    return tf.multiply(a, 10)

def add(a):
    return tf.add(a, 10)

def sub(a):
    return tf.subtract(a, 10)

def div(a):
    return tf.divide(a, 10)

functions = [mul, add, sub, div]
a = tf.ones(shape=(), dtype=tf.float32) * 10

for i in range(10):
    random_op = tf.random_uniform(shape=(), minval=0, maxval=len(functions), dtype=tf.int64)
    result = functions[random_op](a)
    print(random_op, result)
```

Output:
```
tf.Tensor(1, shape=(), dtype=int64) tf.Tensor(20.0, shape=(), dtype=float32)
tf.Tensor(1, shape=(), dtype=int64) tf.Tensor(20.0, shape=(), dtype=float32)
tf.Tensor(1, shape=(), dtype=int64) tf.Tensor(20.0, shape=(), dtype=float32)
tf.Tensor(2, shape=(), dtype=int64) tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0, shape=(), dtype=int64) tf.Tensor(100.0, shape=(), dtype=float32)
tf.Tensor(0, shape=(), dtype=int64) tf.Tensor(100.0, shape=(), dtype=float32)
tf.Tensor(1, shape=(), dtype=int64) tf.Tensor(20.0, shape=(), dtype=float32)
tf.Tensor(1, shape=(), dtype=int64) tf.Tensor(20.0, shape=(), dtype=float32)
tf.Tensor(2, shape=(), dtype=int64) tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0, shape=(), dtype=int64) tf.Tensor(100.0, shape=(), dtype=float32)
```

**Will this change the current api? How?**
I suspect this will require the api to detect the output of the indexing the list to be a function as opposed to a new tensor.
**Who will benefit with this feature?**
This should come as a large benefit to anyone who is performing online data augmentation.
**Any Other info.**

**Comment by skye** [comment]
I think this would basically be implementing [first-class functions](https://en.wikipedia.org/wiki/First-class_function) in TF, i.e. we'd need to represent functions as tensors, so you could use TF's operations with them. This would be pretty cool but unfortunately we don't have the bandwidth to tackle this kind of project right now. I recommend using [tf.case](https://www.tensorflow.org/api_docs/python/tf/case) instead.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by rmothukuru** [comment]
@nunezpaul,
Can you please let us know if using [tf.case](https://www.tensorflow.org/api_docs/python/tf/case) as mentioned in [this comment](https://github.com/tensorflow/tensorflow/issues/24605#issuecomment-461177587) fulfills your request so that we can close this issue? Thanks!
