### ISSUE TITLE
unable to convert the .pb to .tflite as tflite_convert is giving me a problem

### ISSUE THREAD

**Issue by pavanjava** [tensorflow/tensorflow#24609]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- I am working on tensorflow-for-poets-2 and trying to convert the trained model to tflite so that i can port my model to mobile device. which i was not able to do and i am following the hands on from the 
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2-tflite/#0

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)" >> 1.12.0

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
my log when executing the code:

(tensorflow) C:\Users\H156759>python
Python 3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'1.12.0'
>>> exit()

(tensorflow) C:\Users\H156759>tflite_convert --help
Traceback (most recent call last):
  File "C:\Pavans\Anaconda3\envs\tensorflow\Scripts\tflite_convert-script.py", line 6, in <module>
    from tensorflow.contrib.lite.python.tflite_convert import main
ModuleNotFoundError: No module named 'tensorflow.contrib.lite.python.tflite_convert'

**Comment by pavanjava** [comment]
Hi yaxiongma,

you mean to say that i should try tflite on Linux and this will not work on windows ? because my execution environment that i am trying is on Windows currently.

**Comment by pavanjava** [comment]
> If all the ops in your graph are supported by the current TFLite, you can do this successfully in linux environment, and you'd better choose 1.12.0. Don't forget to Check the [**TensorFlow Lite & TensorFlow Compatibility Guide**](https://www.tensorflow.org/lite/tf_ops_compatibility)
> Good luck~

Hi yaxiongma,

you mean to say that i should try tflite on Linux and this will not work on windows ? because my execution environment that i am trying is on Windows currently.

**Comment by yaxiongma** [comment]
@pavanjava  
Yes.
I haven't tried it in Windows. 
good luck

**Comment by pavanjava** [comment]
> @pavanjava
> Yes.
> I haven't tried it in Windows.
> good luck

Thanks yaxiongma,
i will try and let you know. i will keep this issue on hold

**Comment by pavanjava** [comment]
until i try creating the model in linux. closing the issue
