### ISSUE TITLE
Building from source on docker very slow (9 hours)

### ISSUE THREAD

**Issue by Charon77** [tensorflow/tensorflow#24615]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version:  docker: latest-devel-gpu-py3 (image id: d6c139d2fdbf)
- Python version: py3
- Installed using virtualenv? pip? conda?: docker
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
- CUDA/cuDNN version: Cuda compilation tools, release 9.0, V9.0.176
- GPU model and memory: GTX650Ti, 1024MB
- CPU: Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz
- Storage: SSD
- RAM: 8GB

**Describe the problem**
I'm trying to compile GPU TF, but it seems to take forever. I'm now on 9 hours and counting. I'm expecting the compilation time to be much quicker.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

following https://www.tensorflow.org/install/source#gpu_support_2 using
docker: latest-devel-gpu-py3 (image id: d6c139d2fdbf).

Compilation finally ends after writing this at roughly 9 hours and 10 minutes

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

final output logs after completion:
```
[17,524 / 17,527] Compiling tensorflow/contrib/tensor_forest/hybrid/core/ops/k_f|
[17,524 / 17,527] 2 actions running                                             |
    Compiling tensorflow/contrib/tensor_forest/hybrid/core/ops/k_feature_gradien|
[17,525 / 17,528] 2 actions, 1 running                                          |
    Compiling tensorflow/contrib/tensor_forest/hybrid/core/ops/unpack_path_op.cc|
[17,526 / 17,529] 2 actions running                                             |
    Compiling tensorflow/contrib/tensor_forest/hybrid/core/ops/unpack_path_op.cc|
[17,526 / 17,529] 2 actions running                                             |
    Compiling tensorflow/contrib/tensor_forest/hybrid/core/ops/unpack_path_op.cc|
[17,526 / 17,529] 2 actions running                                             |
    Compiling tensorflow/contrib/tensor_forest/hybrid/core/ops/unpack_path_op.cc|
[17,526 / 17,529] 2 actions running                                             |
    Compiling tensorflow/contrib/tensor_forest/hybrid/core/ops/unpack_path_op.cc|
[17,533 / 17,536] 2 actions, 1 running                                          |
    Compiling tensorflow/contrib/tensor_forest/hybrid/core/ops/routing_gradient_|
[17,533 / 17,536] 2 actions, 1 running                                          |
    Compiling tensorflow/contrib/tensor_forest/hybrid/core/ops/routing_gradient_|
[17,537 / 17,538] [-----] Linking tensorflow/contrib/tensor_forest/hybrid/python|
[17,537 / 17,538] Linking tensorflow/contrib/tensor_forest/hybrid/python/ops/_tr|
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:             |
  bazel-bin/tensorflow/tools/pip_package/build_pip_package                      |
INFO: Elapsed time: 75209.586s, Critical Path: 1426.82s                         |
INFO: 14080 processes: 14080 local.                                             |
INFO: Build completed successfully, 17538 total actions                         |
root@61c2126bd1ff:/tensorflow#              
```

**Comment by mihaimaruseac** [comment]
Thank you for the report.

One reason for the slowness is that only 2 CPU jobs were used for building. Though that's mostly linear speedup if you increase to more (on 12 cores I'm seeing builds finish in ~3 hours)

**Comment by Charon77** [comment]
Ah I just realized from the log, that's 75209.586s (20 hours!)
Thank you @mihaimaruseac, I didn't realized the scale of the code. 3 hours on 12 cores corresponds to 18 hours on 2 cores, so I guess the numbers check out.

**Comment by redfish-lee** [comment]
The cpu is also outdated by now.
