### ISSUE TITLE
tf.keras.Model.load_weights failed

### ISSUE THREAD

**Issue by huangbiubiu** [tensorflow/tensorflow#24623]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Both on Ubuntu 16.04 / Windows 10 1803
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.0
- Python version: Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 9.0 & cuDNN 7.1.4
- GPU model and memory: NVIDIA GeForce GTX 1080Ti 12Gb

**Describe the current behavior**

When load a trained keras model (`tf.keras.Model`):
```python3
model.load_weights("./test/trained.h5")
```
It will raise the bug
`ValueError: You are trying to load a weight file containing 1 layers into a model with 0 layers.`

It's discussed in keras repo: https://github.com/keras-team/keras/issues/10417 and  https://github.com/keras-team/keras/issues/11683 and has not been fixed so far.

It still exists in latest keras version but it only happens on `keras >= 2.2.0` (reported by https://github.com/keras-team/keras/issues/10417#issuecomment-402696659). However, it's also exists in `2.1.6-tf` with tensorflow 1.12.

**Describe the expected behavior**
Load the model from the `*.h5` file.

**Code to reproduce the issue**
To reproduce the issue, run the demo:
```python3
import numpy as np
from tensorflow.python.keras.callbacks import ModelCheckpoint
from tensorflow.python.keras.layers import Dense

from files_functions import *

tf.enable_eager_execution()

def measure(y_true, y_pred):
    return tf.reduce_mean(y_pred - y_true)


class DemoNet(tf.keras.Model):
    def __init__(self):
        super(DemoNet, self).__init__()
        self.encoder_layer = Dense(128, input_shape=(128,), activation='tanh')

    def call(self, inputs, training=None, mask=None):
        """Run the model."""
        encoded = self.encoder_layer(inputs)

        return encoded


model = DemoNet()
model.compile(optimizer=tf.train.AdamOptimizer(),
              loss='mse',
              metrics=[measure])

training_input = np.ones((30000, 128)).astype(np.float32)
current_path = "./test/"
save_path = current_path
checkpoint = ModelCheckpoint(save_path + '/trained.h5', monitor='val_loss', verbose=0, save_best_only=True,
                             mode='min',
                             save_weights_only=True)
model.fit(training_input, training_input, epochs=1, batch_size=512, verbose=2, \
          callbacks=[checkpoint], validation_split=0.2)

del model

model = DemoNet()
model.compile(optimizer=tf.train.AdamOptimizer(),
              loss='mse',
              metrics=[measure])

testdata = np.ones((3000, 128))

model.load_weights("./test/trained.h5")
eval = model.evaluate(testdata, testdata, batch_size=512)
```
The demo simpily build a network with one fully connected layer. It will raise the error:
`ValueError: You are trying to load a weight file containing 1 layers into a model with 0 layers.`

The environment of python can be installed by `requrement.txt`:
```
Package             Version   
------------------- ----------
absl-py             0.6.1     
astor               0.7.1     
certifi             2018.11.29
channelnorm-cuda    0.0.0     
chardet             3.0.4     
correlation-cuda    0.0.0     
cycler              0.10.0    
gast                0.2.0     
grpcio              1.16.1    
h5json              1.1.3     
h5py                2.8.0     
idna                2.8       
Keras               2.1.0     
Keras-Applications  1.0.6     
Keras-Preprocessing 1.0.5     
kiwisolver          1.0.1     
lxml                4.2.5     
Markdown            3.0.1     
matplotlib          3.0.2     
numpy               1.15.4    
Pillow              5.2.0     
pip                 18.1      
protobuf            3.6.0     
pyparsing           2.3.0     
python-dateutil     2.7.5     
PyYAML              3.13      
requests            2.21.0    
resample2d-cuda     0.0.0     
scipy               1.1.0     
setuptools          40.6.2    
six                 1.11.0    
tensorboard         1.12.0    
tensorflow-gpu      1.12.0    
termcolor           1.1.0     
urllib3             1.24.1    
Werkzeug            0.14.1    
wheel               0.32.3
```

**Other info / logs**
Trackback of the error:
```
Traceback (most recent call last):
  File "/***/***/test.py", line 51, in <module>
    model.load_weights("./test/trained.h5")
  File "/home/***/anaconda3/envs/transmitter/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1544, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/home/***/anaconda3/envs/transmitter/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 784, in load_weights_from_hdf5_group
    ' layers.')
ValueError: You are trying to load a weight file containing 1 layers into a model with 0 layers.
```

**Comment by kasperfred** [comment]
You didn't initialize the weights when creating the 2nd model. 

When using the model class API, you need to initialize the weights manually. You can do this by training on just a single example. (don't worry the learned weights will be overwritten when you load your own weights) 

You can do this by inserting the following line after you compile the model for the 2nd time. 

```Python
model.fit(training_input[:1], training_input[:1], epochs=1)
```

Alternatively, you can replace your `DemoNet` model with one of the following schemes which automatically initializes the weights. 

For example sequential,
```Python
def DemoNet():
    model = tf.keras.models.Sequential()

    model.add(tf.keras.layers.Dense(128, input_shape=(128,), activation="tanh"))
    
    return model
```

Or using the functional API,
```Python
def DemoNet():
    a = tf.keras.layers.Input(shape=(128,))
    b = tf.keras.layers.Dense(128)(a)
    
    model = tf.keras.models.Model(inputs=a, outputs=b)
    return model
```

Model class + functional

```Python
class DemoModel(tf.keras.Model):
    def __init__(self):
        super(DemoModel, self).__init__()
        self.encoder_layer = Dense(128, input_shape=(128,), activation='tanh')

    def call(self, inputs):
        """Run the model."""
        encoded = self.encoder_layer(inputs)

        return encoded

def DemoNet():
    a = tf.keras.layers.Input(shape=(128,))
    b = DemoModel()(a)
    
    model = tf.keras.models.Model(inputs=a, outputs=b)
    return model
```

**Comment by huangbiubiu** [comment]
@kasperfred Thank you for your help. 
Is it intentional not to initialize the model automatically in model class API? It's confused to initialize weight with `fit()` method. Is it a bug or designed for some reason?

**Comment by kasperfred** [comment]
I'm very new here. As such, I'm not very familiar with what behavior has been left intentional, and which is unintentional. 

I do agree that it's rather confusing having to call `fit` just to overwrite it afterwards. 

However, I think we need a regular contributor or a member who are more familiar with the architectural decisions to determine if this is considered a bug. If it is, I'd be happy to fix it.

**Comment by allenlavoie** [comment]
One option is using the TensorFlow weight format, by using an extension that doesn't include `h5` (or [passing `save_format='tf'` explicitly to save_weights](https://www.tensorflow.org/api_docs/python/tf/keras/models/Model#save_weights)). That will do restore-on-create for variables when loading, so you can `load_weights` and then run `fit` and the variables will be restored before they get used.

**Comment by huangbiubiu** [comment]
@allenlavoie So Keras `h5` model is not compatible with TensorFlow now? I am confused on initializing layers with `fit` method. Is this a bug?

I prefer `ModelCheckpoint` class because it supports more features, like saving the best models, loggings, etc.

**Comment by allenlavoie** [comment]
Not sure what you mean by "not compatible with TensorFlow." The h5 format just doesn't include enough information to restore variables as soon as they're created.

You can use the TF format with ModelCheckpoint if you use `save_weights_only` and leave off the ".h5" suffix.

**Comment by msymp** [comment]
@kasperfred addressed this issue and @allenlavoie has provided a workaround. Hence closing the issue. Thanks.
