### ISSUE TITLE
Master build crash with GPU support testing with OpenSeq2Seq 

### ISSUE THREAD

**Issue by dingguijin** [tensorflow/tensorflow#24626]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9.6 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not Mobile
- TensorFlow installed from (source or binary): Clone from github, master branch
- TensorFlow version (use command below): 1.12
- Python version: 3.5
- Bazel version (if compiling from source): 0.21
- GCC/Compiler version (if compiling from source):  gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
- CUDA/cuDNN version: cuDNN 7.4.1 for CUDA 10.0
- GPU model and memory: GTX2070, 8G

To reproduce:

- Install latest CUDA and cuDNN and make sure CUDA samples and cuDNN samples run successfully. Make sure CUDA things are OK.
- Checkout the latest tensorflow code, configure with cuda, bazel build with --config=opt --config=cuda
- Waiting then create python package and install
- ldd /usr/local/lib/python3.5/site-packages/tensorflow/libtensorflow_framework.so everything is linked correct.

- Download OpenSeq2Seq git clone https://github.com/NVIDIA/OpenSeq2Seq.git
- Run toy test
cd OpenSeq2Seq; python3 run.py --config_file=example_files/speech2text/ds2_toy_config.py --mode=train

**CRASH and generate core dump in libtensorflow_framework.so.**

**Comment by msymp** [comment]
Hello, Can you please step back to the following build: tensorflow_gpu-1.12.0 , gcc 4.8 , bazel 0.15.0 , cuDNN 7 , CUDA 9 , and let us know. Thanks.

**Comment by dingguijin** [comment]
Hi, Thanks for your response.

But I do not have CUDA 9, only CUDA 10 for my RTX card.
If CUDA 10 is helpful, I can try.
One question is 'tensoflow_gpu-1.12.0` the latest release?

Thanks.

**Comment by dingguijin** [comment]
I want to build tensorflow from the latest source not the latest release 1.12. Thanks though.

**Comment by msymp** [comment]
@dingguijin , yes, tensorflow_gpu-1.12.0 is the latest official source to build from, with the above mentioned configuration of CUDA 9 / cuDNN 7. Thanks.
