### ISSUE TITLE
tf.keras.utils.plot_model() raises TypeError: 'InputLayer' object is not iterable

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#24622]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac OS X 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
VERSION="1.13.0-dev20181226" (this is the TF 2.0-preview)
GIT_VERSION="b'v1.12.0-5133-gc343196842'"
- Python version:
3.6.6
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
tf.keras.utils.plot_model() raises `TypeError: 'InputLayer' object is not iterable`

**Describe the expected behavior**
I expect it to save a png image of the model.

**Code to reproduce the issue**

```python
import tensorflow as tf
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(3, input_shape=[2]))
model.add(tf.keras.layers.Dense(1))
tf.keras.utils.plot_model(model, to_file='my_model.png')
```

**Other info / logs**
I ran the code in TF 1.12, no problem.

Here is the traceback in TF 2.0-preview:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/utils/vis_utils.py", line 148, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/utils/vis_utils.py", line 123, in model_to_dot
    for inbound_layer in node.inbound_layers:
TypeError: 'InputLayer' object is not iterable
```

**Comment by yongtang** [comment]
Added a PR #24625 for the fix.

**Comment by ageron** [comment]
Thanks @yongtang , I just tried your fix, works like a charm.

**Comment by jvishnuvardhan** [comment]
Thanks @yongtang. 
Closing this out since it was resolved.

**Comment by nbro** [comment]
I still get this error!

**Comment by talhaanwarch** [comment]
> tf.keras.utils.plot_model

thanks, this worked for me
