### ISSUE TITLE
Tensorflow can find right cudnn in one python file but fail in another

### ISSUE THREAD

**Issue by ZhangYuef** [tensorflow/tensorflow#24636]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution :  `windows 10`
- TensorFlow installed from : `binary`
- TensorFlow version: `1.12.0`
- Python version: `3.5`
- CUDA/cuDNN version: `cuda 9.0 ` & `cudnn 7.4.2`
- GPU model and memory: `Geforce 1060`

**Describe the current behavior**
I am trying to use tensorflow gpu version to train and test my deep learning model. But here comes the problem. When I train my model in one python file things go on well. Tensorflow-gpu can be used properly. Then I save my model as a pretrained on as `grapg.pb` format and try to reuse it in another python file. 

Then I got the following error messages.

**Describe the expected behavior**
Run tensorflow well in both files.

**Code to reproduce the issue**
```
 E tensorflow/stream_executor/cuda/cuda_dnn.cc:363] Loaded runtime CuDNN 
    library: 7.1.4 but source was compiled with: 7.2.1.  CuDNN library major 
    and minor version needs to match or have higher minor version in case of 
    CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN 
    library.  If building from sources, make sure the library loaded at runtime 
    is compatible with the version specified during compile configuration.
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by msymp** [comment]
Hello @ZhangYuef , since you are running on Windows 10, you may need to adjust you cuDNN version (major & minor) for windows such that both save to .pb file program and restore from .pb file program work correctly. Please experiment with latest major/minor version until it works. Let us know. Thanks.

**Comment by msymp** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
