### ISSUE TITLE
model_to_dot() missing from tf.keras although it is documented on keras.io

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#24639]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac OS X 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
VERSION="1.13.0-dev20181226" (this is the TF 2.0-preview)
GIT_VERSION="b'v1.12.0-5133-gc343196842'"
- Python version:
3.6.6
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
The official Keras API is documented at keras.io, and it shows an example using `model_to_dot()` ([here](https://keras.io/visualization/#model-visualization)). The example uses `keras.utils.vis_utils.model_to_dot()`. However, this example does not work when using `tf.keras`, since there is no `tf.keras.utils.vis_utils` package.
I can work around this issue by using: `from tensorflow.python.keras.utils.vis_utils import model_to_dot`, but I believe importing from `tensorflow.python` is frowned upon and may break in the future.

**Describe the expected behavior**
I expect `model_to_dot()` to be available in `tf.keras.utils.vis_utils`, or at least in `tf.keras.utils`.

**Code to reproduce the issue**

```python
from tensorflow import keras
keras.utils.vis_utils.model_to_dot
```

**Other info / logs**
On a related note, `keras.utils.print_summary` is part of the Keras API ([here](https://keras.io/utils/#print_summary)), but absent from `tf.keras.utils`.

`keras.utils.np_utils.to_categorical` is documented [here](https://keras.io/losses/) but absent from `tf.keras.utils.np_utils` (it's in `tf.keras.utils`). This might be an issue with the Keras API rather than with tf.keras.
```

**Comment by ageron** [comment]
I would suggest:
* fixing the Keras API to replace `keras.utils.vis_utils.model_to_dot` with `keras.utils.model_to_dot`
* fixing the Keras API to replace `keras.utils.np_utils.to_categorical` with `keras.utils.to_categorical`
* Adding `model_to_dot` and `print_summary` to `tf.keras.utils`.
I will submit PRs to that effect.

**Comment by ageron** [comment]
I filed a corresponding issue in keras-team/keras: https://github.com/keras-team/keras/issues/11959

**Comment by msymp** [comment]
Hi @ymodak , Please kindly complete review for this PR submitted by @ageron . Thanks.

**Comment by ageron** [comment]
I just submitted a new PR because it seems that my previous PR was insufficient to fix this issue, I also needed to add a `@keras_export` decorator to the `model_to_dot` and `print_summary` function definitions.
