### ISSUE TITLE
Unsupported data type in placeholder op

### ISSUE THREAD

**Issue by twalk4821** [tensorflow/tensorflow#24634]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac OS Mojave
- TensorFlow installed from (source or binary):
pip install tensorflow
- TensorFlow version (or github SHA if from source):
1.12

```
RuntimeError: TOCO failed see console for info.
b"2018-12-30 15:40:54.449737: I tensorflow/contrib/lite/toco/import_tensorflow.cc:189] Unsupported data type in placeholder op: 2\n2018-12-30 15:40:54.450020: F tensorflow/contrib/lite/toco/import_tensorflow.cc:2137] Check failed: status.ok() Unexpected value forattribute 'T'. Expected 'DT_FLOAT'\n"
```

To save the model, I have:
```
// model is an Estimator instance
def export(model):
  model.export_saved_model("tmp/export", serving_input_receiver_fn)
```

and:
```
def serving_input_receiver_fn():
  features = { 'x': tf.placeholder(shape=[1, 100, 100, 1], dtype=tf.as_dtype(np.int32)) }
  return tf.estimator.export.ServingInputReceiver(features, features)
```

As you can see, dtype is np.int32, so I attempt to cast that to a tf type. 

I can attach the full model def on request. 

Thanks.

**Comment by twalk4821** [comment]
The solution to this was not in the placeholder op itself, but in the model declaration. I was using a float64 input type. Switching to float32, and setting dtype=float32 in the placeholder, solved my issue.

**Comment by ayomtuase** [comment]
Please I don't understand how to apply your solution to my problem here

> ConverterError: See console for info.
2021-07-03 18:46:15.428635: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 19
2021-07-03 18:46:15.433220: F tensorflow/lite/toco/import_tensorflow.cc:2690] Check failed: status.ok() Unexpected value for attribute 'T'. Expected 'DT_FLOAT'
Aborted (core dumped)

I am currently using Google Colab and the following cells produced the error

`xception_fold_1 = keras.models.load_model('/content/drive/MyDrive/Datasets/project_models_graphs/xception fold-1.h5')
`

`converter = tf.lite.TFLiteConverter.from_keras_model(xception_fold_1)
converter.experimental_new_converter = False
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE, tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops=True`

`tflite_model = converter.convert()`

`with open('/content/drive/MyDrive/Datasets/project_models_graphs/xception-fold-1.tflite', 'wb') as f:
  f.write(tflite_model)`
