### ISSUE TITLE
Tensorboard histogram_freq is not using GPU: slows down training

### ISSUE THREAD

**Issue by mcguile** [tensorflow/tensorflow#24643]
**System information**
- No custom code
- Ubuntu 18.04
- TensorFlow version 1.11.0
- tf.COMPILER_VERSION = v1.11.0-0-gc19e29306c
- Python version 3.6
- CUDA/cuDNN version 9.0
- GPU model and memory: GTX 1060 6GB

When I run Tensorboard with `histogram_freq = x` where `x != 0`, it uses the CPU at the end of each epoch when Tensorboard writes to logs. 

Usually the GPU is used for the entirety of training and writing to logs and this is also true when `histogram_freq = 0`. 

This [issue] (https://github.com/keras-team/keras/issues/3358) has been mentioned in previous questions but it is dissimilar in that their issue occurs when validation data is passed via a data generator and that histograms are not created - no reference to CPU or GPU. 

I do not use a data generator for validation and histograms appear to be created. This is an issue as writing to logs using CPU seems to take an eternity making the training process up to five times longer.

Notes: 

Training carried out by Keras `fit_generator`.

Training dataset passed by `ImageDataGenerator`.

Validation dataset is passed without data generator.

    tensorboard = TensorBoard(log_dir='../logs/vv2', histogram_freq=1, write_graph=True, write_images=True)
    model.fit_generator(train_generator, 
                                  steps_per_epoch=batch_size, 
                                  epochs=epochs, 
                                  validation_data=(x_test,y_test),
                                  callbacks=[tensorboard])

**Comment by ymodak** [comment]
This issue is more suitable on TenosrFlow Tensorboard repo. Please post it on tensorboard repo from [here](https://github.com/tensorflow/tensorboard/issues). Thanks!
