### ISSUE TITLE
I replaced keras to tensorflow.keras in my project and got OOM with same batch size.

### ISSUE THREAD

**Issue by iperov** [tensorflow/tensorflow#24644]
I would like to completely remove keras dependency from my project and replace it to tensorflow.keras, but it is significantly degrades performance.  
Out Of Memory occurs when I just replace keras to tensorflow.keras with same batch size.
Also epoch train time increased.
Looks like tensorflow.keras unoptimized.
Will tensorflow.keras be optimized in future?

**Comment by jvishnuvardhan** [comment]
@iperov, please provide the code and also follow the guidelines to fill the required details in the (template)[https://github.com/tensorflow/tensorflow/issues/new?template=00-bug-performance-issue.md]. Without the code and other details, it is difficult to find rootcause of the problem. If possible, mention your intention behind removing keras dependency?

**Comment by iperov** [comment]
sorry I cannot provide reproduce right now, because my project is large enough.

Possible reproduce : 
create deep image autoencoder for ~500MB total disk space. 
Find largest not OOM batch size for training for your videocard.
Replace keras to tf.keras and expect issue.

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
