### ISSUE TITLE
tf.contrib.quantize.create_training_graph with tf.keras.activations.relu quantizes before the relu cliping op

### ISSUE THREAD

**Issue by fgr1986** [tensorflow/tensorflow#24641]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.12
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

The use of the param 'max_value' in https://www.tensorflow.org/api_docs/python/tf/keras/activations/relu produces the a quantized graph with the FakeQuant op just after the relu op and not after the automatically inserted clip op.

![Generated graph](https://c2.staticflickr.com/8/7889/31598991447_a5d540f672_b.jpg)

**Describe the expected behavior**

The FakeQuant op should be added after the clip op

**Code to reproduce the issue**
```
...
net = tf.layers.dense(inputs=net,
                              units=units,
                              activation=None,
                              name='dense_' + str(ly_idx),
                              )
net = tf.keras.activations.relu(net,max_value=params['clip_activations'])
...
```

Thanks,

**Comment by msymp** [comment]
Hello @fchollet , user requests that quantization occur after clipping of Relu, not before as shown. Can you please review? Thanks.

**Comment by rmothukuru** [comment]
@fgr1986,
Sorry for the delayed response. Can you please confirm if the issue still persists? If so, please provide a reproducible code so that we can look into it. 

Please refer to the latest [Documentation of Relu Activation function](https://www.tensorflow.org/api_docs/python/tf/keras/activations/relu) and the [Documentation of Quantize](https://www.tensorflow.org/api_docs/python/tf/quantization/quantize) too!

Thanks!

**Comment by fgr1986** [comment]
Shall I try on 1.12? or in the newest 1.X branch? 

Thanks

**Comment by rmothukuru** [comment]
@fgr1986,
Thank you for your response. It would be great if you could try in the latest `2.x` branch as `1.x` is not actively supported.
