### ISSUE TITLE
Why tf.matmul doesn't get zero?

### ISSUE THREAD

**Issue by alexxchen** [tensorflow/tensorflow#24649]
<em>I got a problem when using TensorFlow eager mode that tf.matmul result of two matrixes should obvious be zeros but now different small number as results.</em>

**System information**
- OS Platform and Distribution:Linux Ubuntu 16.04, also on macOS
- TensorFlow installed from:binary
- TensorFlow version :1.12
- Python version:3.6
- GPU model and memory: no GPU, 8GB memory

**Describe the current behavior**
It should be all zeros of the output, but it shows random small values

**Code to reproduce the issue**
` index=np.random.randint(10, size=20)`
 ` grad = tf.one_hot(index, 10, on_value=-0.045, off_value=0.005)`
`  w=tf.constant(0.01, shape=[100, 10])`
`  print(tf.matmul(grad, tf.transpose(w)))`

Is this a bug or something else?

**Comment by DoxasticFox** [comment]
I don't understand why it should be all zeros. AFAICT, all the elements of `grad` will either be `0.005` or `-0.045` (i.e. none will be `0.0`.) Also, all the elements of `w` will be equal to `0.01`. Multiplying (the transpose of) these will result in a non-zero matrix.

**Comment by ppwwyyxx** [comment]
The results should be zeros mathematically but standard floating point numbers simply do not have enough precision to compute the exact results. This seems to be expected results.

**Comment by alexxchen** [comment]
> The results should be zeros mathematically but standard floating point numbers simply do not have enough precision to compute the exact results. This behavior is common and expected.
> 
> e.g.:
> 
> ```
> $python3 -c 'print(sum([0.005 for k in range(6)]))'
> 0.030000000000000002
> ```

Precision was my first thought, but it have different result for the same calculation as follow.
```

import numpy as np
import tensorflow.contrib.eager as tfe
import tensorflow as tf

def main():
  tfe.enable_eager_execution()
  np.set_printoptions(threshold=np.nan)
  index=np.random.randint(10, size=20)
  grad = tf.one_hot(index, 10, on_value=-0.045, off_value=0.005)
  w=tf.constant(0.01, shape=[100, 10])
  print(tf.matmul(grad, tf.transpose(w)))

if __name__ == '__main__':
  main()
```
And floating point shouldn't get the problem of representing 0.005. Calculating 0.005*0.001*9 - 0.0045*0.01=0.

**Comment by ppwwyyxx** [comment]
Your code contains randomness, so getting different result is no surprise.

float32 has no problem representing 0.005. But as I have shown above, it does have problems representing something like this which is very likely to be an intermediate result of your computation:
```
$python3 -c 'print(sum([0.005 * 0.01 for k in range(6)]))'
0.00030000000000000003
```

**Comment by alexxchen** [comment]
> Your code contains randomness, so getting different result is no surprise.
> 
> float32 has no problem representing 0.005. But as I have shown above, it does have problems representing something like this which is very likely to be an intermediate result of your computation:
> 
> ```
> $python3 -c 'print(sum([0.005 * 0.01 for k in range(6)]))'
> 0.00030000000000000003
> ```

The randomness is only about the place of -0.045 in vector when multiplying, which affect the order of adding, but they show different results.

I asked another question in numpy. It seems the problem from original python.
[https://github.com/numpy/numpy/issues/12643](url)

**Comment by ppwwyyxx** [comment]
> which affect the order of adding

and the order of adding may affect results due to precision.

**Comment by alexxchen** [comment]
> > which affect the order of adding
> 
> and the order of adding may affect results due to precision.

Thanks for answering and sorry for my stubborn. Finally I figured out IEEE754 can not represent 0.05 accurately. I forgot the rule to generate binary representation back to university.

**Comment by ymodak** [comment]
Closing this issue since its solved. Please feel free to reopen if have any further questions. Thanks!
