### ISSUE TITLE
Multidimennsionnal input for LSTM Issues

### ISSUE THREAD

**Issue by arita297** [tensorflow/tensorflow#2465]
I have a series of multdimensionnal time series as follow:

Input Xi   i=1..N samples
Xi=[y1,..yk..., yT] K=1..T , yk is a vector, T= 50 (sequence length) with yk= [yk1, ... ykm] m=3 with ykj : Float or Int

Using LSTM Tensor Flow,would like to predict the next step (T+1), given the training of samples like :

Xi=[y1,...., yT]`
The current code gives input form for m=1 (unidimensionnal Y),

input_data = tf.placeholder(tf.float32, [batchSize, numSteps, numInputs])
targets = tf.placeholder(tf.float32, [batchSize, numSteps, numInputs])
Wondering if there is a way to input data if m=2, 3 in the LSTM tensor flow ?

If not, is there a workaround to input multdimensionnal time series ?

Or new devs needs to be done in RNN ?

**Comment by vrv** [comment]
This is a question more appropriate to StackOverflow, unless there is a very concrete feature request here.

**Comment by arita297** [comment]
It means this is not possible.

Can you add this feature in tensor flow ?

Thanks, regards


On 24 May 2016, at 04:05, Vijay Vasudevan <notifications@github.com> wrote:

This is a question more appropriate to StackOverflow, unless there is a very concrete feature request here.

―

**Comment by vrv** [comment]
@ebrevdo, @yuanbyu  to let me know if this is a feasible feature request

**Comment by ebrevdo** [comment]
What is the rank and size of the states that you plan to pass around?

**Comment by arita37** [comment]
Hello,
For example
Input Xi i=1..N samples
     Xi=[y1,..yk..., yT]                      T= 50 (sequence length) 
     with yk= [yk1, ... ykm]      

So, we have 
Xi size :   (m,  1toK_char_size, NsequenceSize)
   i=1... Nsample
   sequenceSize= 50 or 100
   1toK_char_size=  50 
   m= 1 or 2 or 3 (max)

Tensor Ranks is  3  (4 if we account with the samples).
Now, size of the tensor is just:
    m=1,        (1toK_char_size, NsequenceSize)

So m>1 , it would be very helpful for new architectures.
Thanks for replying.

**Comment by ebrevdo** [comment]
You're talking about the input shapes, not the state shapes. rnns accept inputs and emit outputs and state. I'm asking about the shape of the state.

**Comment by arita37** [comment]
It would depend if this Grid LSTM or standard LSTM....

There is the initial transformation:
    S= W . Input
         Input= [Xt, ht]

    (ht_o, mt_o) = LSTM(ht, mt, W)

My questions is :   
 1) Can TensorFlow RNN accept this Input Tensor rank (3 to 5) ?
                   (Nsample, m, 1toK_char_size, NsequenceSize)

 2) The input can be transformed into sub-space through W.....
      But, in order to keep the initial input rank, state dimension would be:
                      ht:  (m2,  d2)     hidden state
                      mt:  (m2, d2)     memory cell

       (Usually, ht is  vector  of size d   for standard LSTM).

       Is this feasible ?
