### ISSUE TITLE
tf.log() is missing although it is still used in many code examples

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#24653]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac OS X 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
VERSION="1.13.0-dev20181226" (this is the TF 2.0-preview)
GIT_VERSION="b'v1.12.0-5133-gc343196842'"
- Python version:
3.6.6
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
`tf.log()` is missing.  It is only available in `tf.math.log()`.

**Describe the expected behavior**
The log function is fundamental and used all the time, it should be available in `tf.log()` (and also in `tf.math.log()`. Especially considering that `tf.exp()` is available. Note that many code examples still show `tf.log()` (try searching for `'tf.log('` in the code base, you will find 12 matches across 8 files).

**Code to reproduce the issue**

```python
import tensorflow as tf
tf.log(42.)
```

**Other info / logs**
I also checked the changes listed in the API names RFC, and I noticed a few discrepancies (I can file a separate issue if necessary):

```
Not deleted: tf.Event
Not deleted: tf.losses
Not deleted: tf.space_to_batch

Not moved: tf.floormod => tf.math.floormod
Not moved: tf.realdiv => tf.math.realdiv
Not moved: tf.SummaryMetadata => tf.summary.SummaryMetadata
Not moved: tf.truncatediv => tf.math.truncatediv
Not moved: tf.truncatemod => math.truncatemod

Not added: tf.batch_to_space_nd
Not added: tf.debugging.is_finite
Not added: tf.debugging.is_inf
Not added: tf.debugging.is_non_decreasing
Not added: tf.debugging.is_strictly_increasing
Not added: tf.debugging.Print
Not added: tf.debugging.verify_tensor_all_finite
Not added: tf.dtypes.bitcast
Not added: tf.initializers.glorot_normal
Not added: tf.initializers.orthogonal_initializer
Not added: tf.initializers.tables_initializer
Not added: tf.initializers.uniform_unit_scaling
Not added: tf.initializers.variance_scaling
Not added: tf.io.PaddingFIFOQueue
Not added: tf.io.PriorityQueue
Not added: tf.io.QueueBase
Not added: tf.io.RandomShuffleQueue
Not added: tf.io.tf_record_iterator
Not added: tf.linalg.matrix_band_part
Not added: tf.linalg.matrix_inverse
Not added: tf.linalg.matrix_solve_ls
Not added: tf.linalg.self_adjoint_eig
Not added: tf.linalg.self_adjoint_eigvals
Not added: tf.math.mod
Not added: tf.math.reduce_join
Not added: tf.quantization.quantize_v2
Not added: tf.random.get_seed
Not added: tf.random.multinomial
Not added: tf.random.random_gamma
Not added: tf.random.random_poisson
Not added: tf.random.set_random_seed
Not added: tf.saved_model.build_tensor_info
Not added: tf.saved_model.get_tensor_from_tensor_info
Not added: tf.saved_model.LEGACY_INIT_OP_KEY
Not added: tf.saved_model.load
Not added: tf.saved_model.main_op
Not added: tf.saved_model.MAIN_OP_KEY
Not added: tf.saved_model.main_op_with_restore
Not added: tf.saved_model.maybe_saved_model_directory
Not added: tf.saved_model.SavedModelBuilder
Not added: tf.saved_model.TRAINING
Not added: tf.sparse.matmul
Not added: tf.sparse.merge
Not added: tf.sparse.placeholder
Not added: tf.sparse.reduce_max_sparse
Not added: tf.sparse.reduce_sum_sparse
Not added: tf.sparse.SparseTensorValue
Not added: tf.summary.HistogramProto
Not added: tf.train.confusion_matrix
```

And `tf.spectral` is called `tf.signal`.

**Comment by martinwicke** [comment]
The code examples will be updated soon, and it isn't surprising that they don't yet work on TF2 (though of course, it would be nice if they did). 

We decided to remove tf.log because there's an unfortunate ambiguity with tf.logging.log. 

Thank you for sending the differences. We have made some changes, and at first glance, these look fine to me. We do have to update the RFC though.

**Comment by ageron** [comment]
Thanks Martin.  I didn't think about `tf.logging.log()`, I see your point, although I would strongly vote in favor of keeping `tf.log()` (math), as I believe way more people are going to be frustrated by `tf.log()` missing than people frustrated by `tf.log()` being math instead of logging, given that:
* TF 1.x had `tf.log()`, and it was math, not logging.
* `exp()` and `log()` always go hand in hand,
* NumPy has `np.log()` (math)
Just my 2 cents.

**Comment by martinwicke** [comment]
@dynamicwebpaige you have the latest on the symbol map. Assigning this issue to you to close when we have an official map we can point to.

**Comment by sayakpaul** [comment]
This is now coming on my way to implement something which includes a decent amount of logarithms. I was wondering has there been a workaround for `tf.log`?

**Comment by janosh** [comment]
FWIW, I agree with @ageron. `tf.log` should have stayed the logarithm.

Having `tf.exp` next to `tf.math.log` just looks weird.

**Comment by ageron** [comment]
Thanks for the update, @rmothukuru. Well I guess it's consistent now, with `log` and `exp` treated the same way, but to be honest I would have much preferred to see a `tf.log()` alias for `tf.math.log()` created instead. I imagine that `tf.exp()` is used all over the place, so it's going to require a lot of search and replace, with potentially a bit of breakage here and there, not to mention code examples being outdated (including in books). Conversely, adding `tf.log()` would break no code at all.
But it's just my opinion of course!I guess there's an effort to make the `tf` namespace as clean as possible, so I can understand.
