### ISSUE TITLE
Quantized tflite model has large sized apk than unquantized

### ISSUE THREAD

**Issue by jennings1716** [tensorflow/tensorflow#24668]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

 I have trained inceptionV3 classification model with custom dataset and got retrained.pb and retrained_labels.txt. I want to use the model in mobile phone and I converted the model using the following code
```
import tensorflow as tf
graph_def_file = "retrained_graph.pb"
input_arrays = ["Mul"]
output_arrays = ["final_result"]
converter = tf.lite.TFLiteConverter.from_frozen_graph(
  graph_def_file,input_arrays,output_arrays)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```
**Describe the current behavior**
I got the tflite model which is of size 85 MB and built an apk file which comes with size 113 MB and I quantized the model with following command

```
tflite_convert \
  --output_file=foo.tflite \
  --graph_def_file=retrained_graph.pb \
  --inference_type=QUANTIZED_UINT8 \
  --input_arrays=Mul \
  --output_arrays=final_result \
  --mean_values=128 \
  --std_dev_values=127 \
  --default_ranges_min=0 \
  --default_ranges_max=6 
```
It gives me a tflite model of size 21 MB and when i use this quantized model to build an apk it generates an apk file of size 135 MB
**Describe the expected behavior**
1. Why the size of the apk file is increased when i use the quantized model ?

2. How to reduce the apk size built with tflite model ?

**Comment by msymp** [comment]
Hello @gargn , can you please let us know if the user's query has been reviewed and being addressed?

**Comment by jennings1716** [comment]
5 days passed.Please address the issue

**Comment by freedomtan** [comment]
@jennings1716, 113 + 21 = 134 ~= 135. Mostly you didn't remove old model.

**Comment by msymp** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
