### ISSUE TITLE
no such package '@png_archive//

### ISSUE THREAD

**Issue by wltjd54** [tensorflow/tensorflow#24669]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): 'Build from source on Windows' TensorFlow Official Website
- TensorFlow version: 
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?: using cmd.exe
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I was trying to build TensorFlow from source in order to solve "Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2" problem.
Although I installed Bazel properly and added necessary environment variables, everytime I tried to build pip packages, which is "bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package", an error called "Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@png_archive//'" always occurs.
I also referred to some issues on the same problem, but none of them solved my problem. Is there anything I need to do? Or should I just install it through pip and ignore "Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2" this message?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
C:\tensorflow>python ./configure.py
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
nul
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: 2c23affd-49a0-4cde-94b2-236aa0a37d76
You have bazel 0.21.0 installed.
Please specify the location of python. [Default is C:\Users\wltjd\AppData\Local\Programs\Python\Python36\python.exe]:

Found possible Python library paths:
  C:\Users\wltjd\AppData\Local\Programs\Python\Python36\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\wltjd\AppData\Local\Programs\Python\Python36\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]: y
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=noignite       # Disable Apacha Ignite support.
        --config=nokafka        # Disable Apache Kafka support.
        --config=nonccl         # Disable NVIDIA NCCL support.

C:\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\tensorflow/.bazelrc
Starting local Bazel server and connecting to it...
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
INFO: Invocation ID: 61281b1e-9316-4ac5-9241-238712f7de45
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@png_archive//': Traceback (most recent call last):
        File "C:/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/tensorflow/third_party/repo.bzl", line 73, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(256) when executing '?C:\msys64_2\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/wltjd/_bazel_wltjd/xv6zejqw/external/png_archive" "-i" "C:/tensorflow/third_party/png_fix_rpi.patch"':
Stdout:
Stderr: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(383): CreateProcessW("C:\users\wltjd\_bazel_wltjd\xv6zejqw\external\png_archive\?C:\msys64_2\usr\bin\bash.exe" -l -c "\"patch\" \"-p1\" \"-d\" \"C:/users/wltjd/_bazel_wltjd/xv6zejqw/external/png_archive\" \"-i\" \"C:(...)): ??? ??? ?? ? ????.
INFO: Elapsed time: 14.881s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (319 packages loaded, 8559 targets configured)
    Fetching @swig; fetching 8s
    Fetching @grpc; fetching 7s
    Fetching @cython; fetching 7s
    Fetching @eigen_archive; fetching 6s
    Fetching @llvm; fetching 5s
    Fetching @icu; fetching 4s
    Fetching @boringssl; fetching 4s
    Fetching @png_archive; fetching

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
You can safely ignore the warning message and continue to use TensorFlow.

**Comment by sheirving** [comment]
same problem! Have you solved it?

**Comment by limenghao** [comment]
Hi, I encountered with the same problem(maybe?), and turned to find that the patch command can only be used in the MSYS2 command terminal, otherwise you need to set the environment. I try the build command in the MSYS2 terminal and it worked fine. Hope helps someone!
