### ISSUE TITLE
Feature request: tensordot

### ISSUE THREAD

**Issue by entron** [tensorflow/tensorflow#2466]
I found one useful tensor operation "tensordot" is missing in tensorflow. [Theano has an implementation of it](http://deeplearning.net/software/theano/library/tensor/basic.html). It would be great to have tensordot also in tensorflow.

**Comment by vrv** [comment]
Duplicate of #216

**Comment by shoyer** [comment]
@vrv tensordot is related to but not exactly the same as a broadcasting matmul -- with tensordot, there is an explicit axes argument.

**Comment by entron** [comment]
`tensordot` can contract multiple indices at the same time which is different with what mentioned in #216

**Comment by vrv** [comment]
Agreed, I just wanted to have one issue that tracks them both, since they are closely related and we already have a billion issues.
