### ISSUE TITLE
NNAPI doesn't support tensors with rank 0 - LeakyRelu?

### ISSUE THREAD

**Issue by wosiu** [tensorflow/tensorflow#24676]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04 + Android 8.1
- TensorFlow installed from (source or binary): Anaconda  
- TensorFlow version (or github SHA if from source): tensorflow 1.12.0 + keras 2.2.4 for converting model using tflite_convert and tensorflow-lite:1.12.0 in Android gradle build config

**Provide the text output from tflite_convert**

```
(update_36) m@m-hp:~/repos/keras_ocr_preproc$ tflite_convert --output_file=android/some_name.tflite --keras_model_file=android/some_name.hdf5
2019-01-03 01:45:35.173445: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-01-03 01:45:35.178794: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
WARNING:tensorflow:No training configuration found in save file: the model was *not* compiled. Compile it manually.
```
..which sounds OK.

**Any other info / logs**

Log from Android 8.1, tensorflow-lite 1.12.0 device: Alcatel 1 dual sim:
```
E/tflite: NNAPI doesn't support tensors with rank 0 (index 16 name class_2/LeakyRelu/alpha)
    Returning error since TFLite returned failure nnapi_delegate.cc:742.
    Failed to build graph for NNAPI
E/AndroidRuntime: FATAL EXCEPTION: DefaultFallbackThread
    Process: eu.yesse.readerdemo.release, PID: 27460
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: @
```

It crashes only when setUseNNAPI is set to true (I know - usage is deprecated in tflite:1.12.0). 
When setUseNNAPI is commented, it seems that fallback to CPU happens and everything works, but slow. 
Also for other Androids <=8.0, it works extremaly slow comparing to evaluation of the same model on iOS devices using CoreML.

**Comment by msymp** [comment]
Hello @aselle , since NNAPI is only available on devices with Android 8.1 or later (by setUseNNAPI), and the fallback is on CPU implementation on older devices, for this user the TFLite throws an error on tensors with rank 0. Can you please advise. Thanks.

**Comment by idstein** [comment]
As far as I understand NNAPI does not support LeakyRelu only Relu Relu1 and Relu6. 

See operator mapping
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/nnapi/nnapi_delegate.cc


NNAPI documentation also does not list it. https://developer.android.com/ndk/reference/group/neural-networks

**Comment by sunzhe09** [comment]
hello guys，I met the same case but my error log is：
2019-02-27 16:37:37.125 29351-29398/? E/tflite: NNAPI doesn't support tensors with rank 0 (index 13 name inference/generator/add_1/y)
2019-02-27 16:37:37.125 29351-29398/? E/tflite: Returning error since TFLite returned failure nnapi_delegate.cc:748.
2019-02-27 16:37:37.125 29351-29398/? E/tflite: Failed to build graph for NNAPI

the op with  tanh as activation and  *0.53+0.5. besides,my relu funtion is self-define leaky_relu,then it
's maxmum in the graph

**Comment by jdduke** [comment]
This should be supported now, can you give it another try?
