### ISSUE TITLE
alternative for tf.contrib.losses.metric_learning.triplet_semihard_loss

### ISSUE THREAD

**Issue by thebeancounter** [tensorflow/tensorflow#24671]
Hi, 
I read that tf contrib is deprecated soon, is there an alternative for triplet loss that will remain in the api?

**Comment by cgarciae** [comment]
Any updates? These functions are super useful.

**Comment by thebeancounter** [comment]
@cgarciae 

I wrote one of my own, looking for some guidance for how to create a PR for it, and maybe someone to give another look at it before that. want to give me a hand?

**Comment by cgarciae** [comment]
@thebeancounter you a repo for this?

**Comment by ymodak** [comment]
@thebeancounter You can send PR on [tensorflow addons repo](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md) to add this feature

**Comment by facaiy** [comment]
Thanks for all :-)
It has been moved to Addons: `tfa.losses.TripletSemiHardLoss`
Please check out, take a try and have fun: 
+ https://github.com/tensorflow/addons
+ https://github.com/tensorflow/addons/blob/master/tensorflow_addons/losses/python/triplet.py
