### ISSUE TITLE
Incorrect relative include paths in include/tensorflow/core/framework/op_def.pb.h when building external c++ files using Windows

### ISSUE THREAD

**Issue by Usherwood** [tensorflow/tensorflow#24672]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from: binary
- TensorFlow version: 1.12.0
- Python version: 3.6.6
- Installed using: pip
- CUDA/cuDNN version: 9.2/7
- GPU model and memory: GeForce GTX 1050 Ti

**Describe the problem**
NOTE this error is not in building Tensorflow, but in building an external library that needs to include Tensorflow, and we believe the problem may be internal to Tensorflow. Apologies if this is in the wrong place.

Hello, I am no expert in Tensorflow or C++ but will try to describe the problem as best as I can. When trying to build an external package that contains .cpp files that need to include Tensorflow the C++ compiler (Visual Studio cl.exe) throws an error as the file Anaconda3\lib\site-packages\tensorflow\include\tensorflow/core/framework/op_def.pb.h cannot find the relevant files in the include directory. It is looking for:
- google/protobuf/stubs/common.h
- unsupported/Eigen/CXX11/Tensor
- absl/strings/string_view.h

The reason I believe this is is that the relative paths have changed on tensorflow 1.12, these files exist but are now stored in different paths. I have tried adding more include paths but then I get further errors and this fix doesn't feel like the correct way to go. 

On older versions of tensorflow (tested 1.4) these include files are at the correct relative paths (as stated above) to tensorflow's include directory

**Provide the exact sequence of commands / steps that you executed before running into the problem**
>> D:\programs_hdd\visual_studio\VC\Tools\MSVC\14.13.26128\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\peter\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\peter\Anaconda3\lib\site-packages\tensorflow\include -ID:\documents\work\bibliotecas_terceiro\tensorflow_qrnn\src -ID:\documents\work\bibliotecas_terceiro\tensorflow_qrnn\src\third_party "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\include" "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\include\cuda" -IC:\Users\peter\Anaconda3\Lib\site-packages\tensorflow\include\third_party\eigen3 -IC:\Users\peter\Anaconda3\Lib\site-packages\tensorflow\include\external\com_google_absl -IC:\Users\peter\Anaconda3\include -IC:\Users\peter\Anaconda3\include -ID:\programs_hdd\visual_studio\VC\Tools\MSVC\14.13.26128\ATLMFC\include -ID:\programs_hdd\visual_studio\VC\Tools\MSVC\14.13.26128\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt" /EHsc /TpD:\documents\work\bibliotecas_terceiro\tensorflow_qrnn\src\fo_pool_op_cpu.cpp /Fobuild\temp.win-amd64-3.6\Release\documents\work\bibliotecas_terceiro\tensorflow_qrnn\src\fo_pool_op_cpu.obj

>> fo_pool_op_cpu.cpp
>> C:\Users\peter\Anaconda3\lib\site-packages\tensorflow\include\tensorflow/core/framework/op_def.pb.h(9): fatal error C1083: Cannot open include file: 'google/protobuf/stubs/common.h': No such file or directory
error: command 
>> 'D:\\programs_hdd\\visual_studio\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

Thank you

**Comment by rmothukuru** [comment]
@Usherwood,
Sorry for the delayed response. Since this issue is more than 2 years old, can you please let us know if it is still relevant? Thanks!
