### ISSUE TITLE
I am getting the following error when exporting keras model to tensorflow

### ISSUE THREAD

**Issue by isheunesutembo** [tensorflow/tensorflow#24687]
from tensorflow.python.saved_model import builder as saved_model_builder
from tensorflow.python.saved_model import utils
from tensorflow.python.saved_model import tag_constants, signature_constants
from tensorflow.python.saved_model.signature_def_utils_impl import build_signature_def, predict_signature_def
from tensorflow.contrib.session_bundle import exporter

export_path = 'plantmodelproduction'
builder = saved_model_builder.SavedModelBuilder(export_path)

signature = predict_signature_def(inputs={'images': new_model.input},
                                  outputs={'scores': new_model.output})

with K.get_session() as sess:
    builder.add_meta_graph_and_variables(sess=sess,
                                         tags=[tag_constants.SERVING],
                                         signature_def_map={'predict': signature})
    builder.save()

INFO:tensorflow:No assets to save.
INFO:tensorflow:No assets to write.
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'IsVariableInitialized_3579:0' shape=() dtype=bool>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "C:\Users\isheunesu\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3287, in run_code
    return outflag  File "<ipython-input-96-dc248f1de322>", line 2, in <module>
    model=load_model('plantdiseasemodel.h5')  File "C:\Users\isheunesu\Anaconda\lib\site-packages\keras\engine\saving.py", line 422, in load_model
    h5dict.close()  File "C:\Users\isheunesu\Anaconda\lib\site-packages\keras\engine\saving.py", line 288, in _deserialize_model
    K.batch_set_value(weight_value_tuples)  File "C:\Users\isheunesu\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py", line 2581, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)  File "C:\Users\isheunesu\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py", line 206, in get_session
    session.run(tf.variables_initializer(uninitialized_vars))  File "C:\Users\isheunesu\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py", line 199, in <listcomp>
    [tf.is_variable_initialized(v) for v in candidate_vars])  File "C:\Users\isheunesu\Anaconda\lib\site-packages\tensorflow\python\util\tf_should_use.py", line 189, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'IsVariableInitialized_3578:0' shape=() dtype=bool>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "C:\Users\isheunesu\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3287, in run_code
    return outflag  File "<ipython-input-96-dc248f1de322>", line 2, in <module>
    model=load_model('plantdiseasemodel.h5')  File "C:\Users\isheunesu\Anaconda\lib\site-packages\keras\engine\saving.py", line 422, in load_model
    h5dict.close()  File "C:\Users\isheunesu\Anaconda\lib\site-packages\keras\engine\saving.py", line 288, in _deserialize_model
    K.batch_set_value(weight_value_tuples)  File "C:\Users\isheunesu\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py", line 2581, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)  File "C:\Users\isheunesu\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py", line 206, in get_session
    session.run(tf.variables_initializer(uninitialized_vars))  File "C:\Users\isheunesu\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py", line 199, in <listcomp>
    [tf.is_variable_initialized(v) for v in candidate_vars])  File "C:\Users\isheunesu\Anaconda\lib\site-packages\tensorflow\python\util\tf_should_use.py", line 189, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
