### ISSUE TITLE
Large Python call overhead in eager mode

### ISSUE THREAD

**Issue by twiecki** [tensorflow/tensorflow#24684]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX Mojave
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.12.0
- Python version: 3.6
- GCC/Compiler version (if compiling from source): 4.2.1
v1.12.0-rc2-3-ga6d8ffae09 1.12.0

We are currently working with Tensorflow Probability as part of PyMC4. The model logp graph is static and rather cheap but the samplers are in python. Thus, for every logp evaluation, we have to evaluate the TF graph. Compared to Theano, this is rather slow (about 20x slower). I suspect that the Python call overhead is just very high, especially in graph mode (see https://github.com/tensorflow/tensorflow/issues/120). 

Eager mode makes things better but it's still about 10x slower, even when using defun. I guess I'm asking how much additional work needs to be done other than giving a call hook directly into compiled code and whether that part is optimized at all.

Here is a notebook with some very basic speed comparisons to Theano: https://gist.github.com/twiecki/43d6b78455ef5812bb90b5522fe7686c

 The difference grows more dramatic in a real-world scenario but the notebook is more involved: https://github.com/aseyboldt/pymc4/blob/london/pymc4_experiment.ipynb

**Comment by iganichev** [comment]
@derifatives has indeed experimented using XLA on CPU to remove TensorFlow Executor's overhead. In his benchmarks, we saw almost 100x improvement. The aesthetics of getting XLA to work well in Eager are pretty bad at the moment and we are actively working through various integration issues.

If this is not pressing, we should have a reasonable story for Eager + Defun + XLA in a couple of weeks. If it is, your best bet is probably to:
  - Use graph mode and [make_callable](https://www.tensorflow.org/api_docs/python/tf/Session#make_callable) to minimize session.run overheads.
  - Use [xla.compile](https://www.tensorflow.org/xla/tutorials/xla_compile) API to eliminate TF Executor overhead. This is important if you have a lot of very cheap ops.

I am not following your exact question "how much additional work needs to be done other than giving a call hook directly into compiled code". What is the compiled code? TF does not compile generated C++ files like Theano does.

**Comment by twiecki** [comment]
@iganichev Thanks, good to hear there is development there.

I tried your suggestions. `make_callable` actually leads to a small improvement.

Using `xla.compile` in eager mode gave:
```
ValueError: When eager execution is enabled, use_resource cannot be set to false.
```
I don't set it to `True` anywhere, fwiw.

and sometimes also:
```
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.
```

In any case, I'm also happy to wait a few weeks and test it again when XLA + Eager play nicely, sounds like that's exactly what I need.

**Comment by msymp** [comment]
Thanks @iganichev . As the work on the Eager mode for XLA / Defun proceeds to completion in a couple of weeks, @twiecki shall resubmit this issue. Closing for now. Thanks.

**Comment by canyon289** [comment]
@msymp Why reopen this issue? Not challenging the decision, just curious!

**Comment by msymp** [comment]
@canyon289 , we keep it open so that @twiecki can rejoin this thread in a couple of weeks after the work on Eager mode completed.

**Comment by twiecki** [comment]
@msymp any progress so far?

**Comment by iganichev** [comment]
Sorry, but nothing significant happened. Other more critical issues have taken precedence. Not sure when somebody will have time to pick this up again.

**Comment by derifatives** [comment]
What's the current status here? Internally, we've been using xla.compile in
Eager mode extensively and successfully.

**Comment by twiecki** [comment]
@derifatives Do you have a small code example to demonstrate how it can be used?

**Comment by iganichev** [comment]
Here is an option to request XLA compilation of tf.functions:
https://github.com/tensorflow/tensorflow/blob/e3b2203323c578cc9a3e1a5bca51d00c050cb18e/tensorflow/python/eager/def_function.py#L977

There is a bit more documentation here:
https://github.com/tensorflow/tensorflow/blob/e3b2203323c578cc9a3e1a5bca51d00c050cb18e/tensorflow/python/eager/def_function.py#L344
