### ISSUE TITLE
C++ include files when linking against headers with wrong type, no long int in code base, erroring about long int type.

### ISSUE THREAD

**Issue by samhodge** [tensorflow/tensorflow#24698]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes I have written code which takes an image from a OpenFX framework and passes it as input to a Tensorflow session in C++, runs the feed forward and returns the result to a pixel buffer

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux CentOS 6.10, using gcc/4.8.5 and bazel 0.11.0 with CUDA 9.1 and cuDNN 7.1.2

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
from source v1.6.0 zip here:
https://github.com/tensorflow/tensorflow/archive/v1.6.0.zip
- TensorFlow version (use command below):
NA

- Python version:
2.7.13 NA
- Bazel version (if compiling from source):
0.11.0
- GCC/Compiler version (if compiling from source):
gcc 4.8.5
- CUDA/cuDNN version:
CUDA 9.1 with 3 updates, cuDNN 7.1.3
- GPU model and memory:
GTX 1060 6Gb

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
the code will no longer compile when I moved to a machine with a GPU 
```

  CXX      Linux-64-debug/rotobot.o
rotobot.cpp: In function ‘void drawMasks(OpenImageIO::v1_6::ImageBuf&, std::unique_ptr<tensorflow::Session>&, OpenImageIO::v1_6::ImageBuf&, std::string&, bool, const bool*, const bool*, const bool*, double, double, double, double, double, double, bool)’:
rotobot.cpp:435:68: error: ‘inputTensor2’ was not declared in this scope
  tensorflow::Status run_status = tfSession->Run({ { "input_image", inputTensor2 },{ "input_image_meta", inputMetadataTensor } },
                                                                    ^
rotobot.cpp:439:11: error: no matching function for call to ‘tensorflow::Session::Run(<brace-enclosed initializer list>, <brace-enclosed initializer list>, <brace-enclosed initializer list>, std::vector<tensorflow::Tensor>*)’
   &outputs);
           ^
rotobot.cpp:439:11: note: candidates are:
In file included from rotobot.cpp:32:0:
/home/sam/dev/tensorflow-1.6.0/tensorflow/core/public/session.h:121:18: note: virtual tensorflow::Status tensorflow::Session::Run(const std::vector<std::pair<std::basic_string<char>, tensorflow::Tensor> >&, const std::vector<std::basic_string<char> >&, const std::vector<std::basic_string<char> >&, std::vector<tensorflow::Tensor>*)
   virtual Status Run(const std::vector<std::pair<string, Tensor> >& inputs,
                  ^
/home/sam/dev/tensorflow-1.6.0/tensorflow/core/public/session.h:121:18: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const std::vector<std::pair<std::basic_string<char>, tensorflow::Tensor> >&’
/home/sam/dev/tensorflow-1.6.0/tensorflow/core/public/session.h:150:18: note: virtual tensorflow::Status tensorflow::Session::Run(const tensorflow::RunOptions&, const std::vector<std::pair<std::basic_string<char>, tensorflow::Tensor> >&, const std::vector<std::basic_string<char> >&, const std::vector<std::basic_string<char> >&, std::vector<tensorflow::Tensor>*, tensorflow::RunMetadata*)
   virtual Status Run(const RunOptions& run_options,
                  ^
/home/sam/dev/tensorflow-1.6.0/tensorflow/core/public/session.h:150:18: note:   candidate expects 6 arguments, 4 provided
In file included from /home/sam/dev/tensorflow-1.6.0/tensorflow/core/framework/tensor.h:23:0,
                 from /home/sam/dev/tensorflow-1.6.0/tensorflow/core/public/session.h:24,
                 from rotobot.cpp:32:
/home/sam/dev/tensorflow-1.6.0/tensorflow/core/framework/types.h: In instantiation of ‘struct tensorflow::DataTypeToEnum<long int>’:
/home/sam/dev/tensorflow-1.6.0/tensorflow/core/framework/tensor.h:566:46:   required from ‘typename tensorflow::TTypes<T, NDIMS>::Tensor tensorflow::Tensor::tensor() [with T = long int; long unsigned int NDIMS = 3ul; typename tensorflow::TTypes<T, NDIMS>::Tensor = Eigen::TensorMap<Eigen::Tensor<long int, 3, 1, long int>, 16, Eigen::MakePointer>]’
rotobot.cpp:1743:53:   required from here
/home/sam/dev/tensorflow-1.6.0/tensorflow/core/framework/types.h:356:3: error: static assertion failed: Specified Data Type not supported
   static_assert(IsValidDataType<T>::value, "Specified Data Type not supported");
   ^
In file included from /home/sam/dev/tensorflow-1.6.0/tensorflow/core/public/session.h:24:0,
                 from rotobot.cpp:32:
/home/sam/dev/tensorflow-1.6.0/tensorflow/core/framework/tensor.h: In instantiation of ‘typename tensorflow::TTypes<T, NDIMS>::Tensor tensorflow::Tensor::tensor() [with T = long int; long unsigned int NDIMS = 3ul; typename tensorflow::TTypes<T, NDIMS>::Tensor = Eigen::TensorMap<Eigen::Tensor<long int, 3, 1, long int>, 16, Eigen::MakePointer>]’:
rotobot.cpp:1743:53:   required from here
/home/sam/dev/tensorflow-1.6.0/tensorflow/core/framework/tensor.h:566:46: error: ‘v’ is not a member of ‘tensorflow::DataTypeToEnum<long int>’

```
**Describe the expected behavior**
The code was compiling previously

The previous build environment was v1.6.0.2-gcbc6580

But was built without CUDA options.

I am linking against 
`
-ltensorflow -ltensorflow_cc and -ltensorflow_framework -lnsync`

and a few more

but I am not compiling yet.

lines 31,32,33 respectively are:

#include <tensorflow/core/platform/init_main.h>
#include <tensorflow/core/public/session.h>
#include <tensorflow/core/framework/tensor_shape.h>

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

lines 31,32,33 respectively are:

#include <tensorflow/core/platform/init_main.h>
#include <tensorflow/core/public/session.h>
#include <tensorflow/core/framework/tensor_shape.h>

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

see:
https://stackoverflow.com/questions/54033100/tensorflow-1-6-0-with-cuda-support-on-centos-6-10-c-linking-against-libtensorf

**Comment by samhodge** [comment]
I have an idea now to recompile on the new machine with identical SHA hash from the github revision without CUDA support and see if I still get the same error.

**Comment by samhodge** [comment]
OK I can compile some old code but not the identical source as is compiling in the otherwise identical virtual machine which is CentOS 6.9
Is there a way to run that virtual machine with access to the GPU, the end goal is to come up with some libraries that are glibc 2.12 compliant.

**Comment by msymp** [comment]
Hello @samhodge , Your query is very systems related.

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

Thanks!

**Comment by samhodge** [comment]
turns out it was a duplicate of https://github.com/tensorflow/tensorflow/issues/20586 but I assumed it was the system, so after installing CentOS 7 CUDA 9.2 and cuDNN 7.3.1 I was able to reproduce the error and then found it was in my code. For the record long int is not supported changing the template from int64_t to int64 made the compiler error go away. Still working on testing the software with GPU acceleration.
