### ISSUE TITLE
tf.keras.backend.batch_normalization documentation equation does not match implementation

### ISSUE THREAD

**Issue by chrisdahlberg** [tensorflow/tensorflow#24690]
**System information**
- TensorFlow version: r1.12
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/keras/backend/batch_normalization

**Describe the documentation issue**
The documentation describes the op as computing 

~~~
output = (x - mean) / (sqrt(var) + epsilon) * gamma + beta
~~~

the op actually computes

~~~
output = (x - mean) / (sqrt(var + epsilon)) * gamma + beta
~~~

with `epsilon` inside the sqrt

Practically, it doesn't really matter where the epsilon is added in actual use.  (I only noticed because I was comparing the output of each layer when translating something from caffe to tensorflow)

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

Maybe eventually, would take me awhile to get around to it

**Comment by yongtang** [comment]
@chrisdahlberg Created a PR #24693 for the fix.

**Comment by msymp** [comment]
The PR #24693 for the fix was closed. Hence we close this issue. Thanks.
