### ISSUE TITLE
translate module not present in binary pip installation

### ISSUE THREAD

**Issue by anuragranj** [tensorflow/tensorflow#247]
The translate module (among others) is a part of source, but not the pip install. Is there a plan for adding it in the binary installation?

**Comment by vrv** [comment]
The translate modules are indeed currently not part of the install (they're currently more of a reference).

We're thinking about how to repackage some of the files in our codebase (e.g., tutorials, docs, example models, etc), so we'll have a better answer for you soon.  Thanks!

**Comment by vrv** [comment]
The translate modules (as well as the other model resources) are for the most part just an example that can be moved / copied.  Some of them  had a few out-of-file helper modules that were not part of the pip package that would break during execution of say, translate.py, but we have added them to the module to get things working as written.

In general, the pip package will probably just be for installing the core tensorflow python library, and any helper libraries to get our tutorials to work.

Users should still git clone the source repo to get access to examples, tutorials, etc, and should write their code assuming they are using the public API, where the public TensorFlow API is defined as what is documented at http://www.tensorflow.org/versions/master/api_docs/index.html

**Comment by vrv** [comment]
Fixed in 0.6.0
