### ISSUE TITLE
TFLite c++ code with TFLite binary gives error using BuildFromBuffer()

### ISSUE THREAD

**Issue by ShariqM** [tensorflow/tensorflow#24709]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac High Sierra 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 2
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): r.12
- Python version: 3.5
- Bazel version (if compiling from source): 0.21
- GCC/Compiler version (if compiling from source): Apple LLVM version 9.1.0 (clang-902.0.39.2)
- CUDA/cuDNN version: 10.1
- GPU model and memory: NVIDIA 2080TI

**Describe the current behavior**
High-Level: I'm trying to built a TFLite Interpreter in C++ running on a Pixel 2. I have successfully loaded my model.tflite binary using the BuildFromFile() API. However, I now want to read the model from the assets/ directory. To do this I believe I am supposed to use the  BuildFromBuffer() API.

I'm using the BuildFromBuffer() API in model.h using a mmapped buffer and not getting a valid model back. Am I supposed to supply some other kind of buffer? See my code below. I get an error about a bad model identifier.

**Describe the expected behavior**
I expected a valid FlatBufferModel to be returned.

**Code to reproduce the issue**
`
            Code that errors:

            AAsset *asset = AAssetManager_open(mgr, tflite_path.c_str(), O_RDONLY);
            off_t start = 0;
            off_t length = AAsset_getLength(asset);
            int mmap_fd_ = AAsset_openFileDescriptor(asset, &start, &length);
            if (mmap_fd_ < 0) {
                LOGE("Failed to open file: %s", tflite_path.c_str());
                AAsset_close(asset);
                return false;
            }
            // MMAP TFLite Binary
            struct stat sb;
            fstat(mmap_fd_, &sb);
            char *mmapped_buffer_ = (char *) mmap(nullptr, sb.st_size, PROT_READ, MAP_SHARED, mmap_fd_,
                                                  0);
            if (mmapped_buffer_ == MAP_FAILED) {
                LOGE("Mmap failed on file: %s", tflite_path.c_str());
                AAsset_close(asset);
                return false;
            }

            // Build the Model
            using namespace tflite;
            std::unique_ptr<FlatBufferModel> model = FlatBufferModel::BuildFromBuffer(mmapped_buffer_,
                                                                                      strlen(mmapped_buffer_));
            if (!model) {
                LOGE("Failed to create FlatBufferModel with file: %s", tflite_path.c_str()); // My code errors here.
                AAsset_close(asset);
                return false;
            }`

`
            Code that runs successfully: 

            const char *external_path = env->GetStringUTFChars(jExternalPath, JNI_FALSE);
            const char *relative_path = "/Download/tflite/1052model.ckpt-303187.tflite";
            char tflite_path[strlen(external_path) + strlen(relative_path)];
            strcpy(tflite_path, external_path);
            strcat (tflite_path, relative_path);

            std::unique_ptr<tflite::FlatBufferModel> model(
                    tflite::FlatBufferModel::BuildFromFile(tflite_path));

            if(!model){
                printf("Failed to mmap model\n");
                exit(0);
            }

            tflite::ops::builtin::BuiltinOpResolver resolver;
            std::unique_ptr<tflite::Interpreter> interpreter;
            if (tflite::InterpreterBuilder(*model, resolver)(&interpreter) == kTfLiteOk) {
                interpreter->Invoke();
                LOGD("TFLiteOk!");
            } else {
                LOGD("TFLite -- NOT -- Ok!");
            }`
**Other info / logs**
Error logs:
19-01-04 12:38:14.953 25181-25181/com.google.sample.oboe.hearsight E/tflite: Model provided has model identifier '
2019-01-04 12:38:14.953 25181-25181/com.google.sample.oboe.hearsight E/AUDIO-APP: Failed to create FlatBufferModel with file: 1052model.ckpt-303187.tflite

**Comment by tofulawrence** [comment]
I'm glad that you found a workaround.

**Comment by lissyx** [comment]
@tofulawrence Can we expect that to work, or is there something blocking this feature fundamentally?

**Comment by tofulawrence** [comment]
I'll let @miaout17 reply.

**Comment by RealLast** [comment]
Hello,

Had the same problem. 
For debugging, I tried to wrote the buffer I read from the assets back to a file on the internal storage.
However when writing the buffer directly, only one byte was written. That surprised me.
So I tried to copy the buffer byte-wise to a string prior to writing it to a file. 
And that worked! So I created a buffer and copied the data over, and built the FlatBuffer from it. 
Later I noticed that although my models were loaded correctly, they did not work properly.
The problem was that I deleted the buffer (that I temporarily created) after creating the interpreter.
But it seems FlatBuffers does not copy any data from it but rather works on the buffer itself. So the buffer has to exist alongside  the FlatBuffer model as long as you want to use it.
Finally, I came up with this:

```
// Open the file from assets in BUFFER_MODE
// Streaming might work too?
AAsset* asset =
            AAssetManager_open(assetManager, this->modelFile.c_str(), AASSET_MODE_BUFFER);

if(asset == NULL)
{
    Logger::printfln("Asset is NULL, probably the asset file that shall"
                                                  "be loaded was not packed into the apk.");
    return false;
}
off_t start;
off_t length;
const int fd = AAsset_openFileDescriptor(asset, &start, &length);


off_t  dataSize = AAsset_getLength(asset);
const void* const memory = AAsset_getBuffer(asset);

// Use as const char*
const char* const memChar = (const char*) memory;

// Create a new Buffer for the FlatBuffer with the size needed.
// It has to exist alongside the FlatBuffer model as long as the model shall exist!
// char* flatBuffersBuffer; (declared in the header file of the class in which I use this).
this->flatBuffersBuffer = new char[dataSize];

Logger::printfln("Copying assets buffer to flatbuffers buffer, size: %d", dataSize);
for(int i = 0; i < dataSize; i++)
{
	this->flatBuffersBuffer[i] = memChar[i];
}

// Build your tflite model from the buffer.
this->model = tflite::FlatBufferModel::BuildFromBuffer(this->flatBuffersBuffer, dataSize);

// Make sure NOT to delete the flatBuffersBuffer now! If you would do it your models won't work!
// As long as you want to use the FlatBuffer model, the flatBuffersBuffer has to exist!

if (this->model)
{
    // And so on...
}
```

**Comment by terryheo** [comment]
You don't need to mmap() and call FlatBufferModel::BuildFromBuffer().
You can use simply FlatBufferModel::BuildFromFile() since it tried mmap() internally.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/model_builder.cc#L52

FYI, you need to set noCompress option for "tflite" extension to use mmap() feature.
https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/app/build.gradle#L21
