### ISSUE TITLE
TensorFlow 2.0 installation issue on Windows (CPU)

### ISSUE THREAD

**Issue by sscardapane** [tensorflow/tensorflow#24705]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (Home Edition)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tf-nightly-2.0-preview
- Python version: 3.6.x
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: NA
- GPU model and memory: NA

On a Windows 10 machine, anytime I try to install the TF 2.0 preview by:

```pip install tf-nightly-2.0-preview```

I obtain the following error message:

**Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-3rfhl_nx\\tf-nightly-2.0-preview\\tf_nightly_2.0_preview-1.13.0.dev20181226.data/purelib/tensorflow/include/tensorflow/include/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorSyclConvertToDeviceExpression.h'**

I tried on three different machines with the same OS, fresh install of Anaconda, fresh environment with all possible 3.6.x versions of Python. I also tried to install directly by the whl file after downloading it from PyPy. Any ideas what I am doing wrong?

**Comment by sscardapane** [comment]
I forgot to mention that a similar error message arises here: #24694.

**Comment by danaugrs** [comment]
I'm having the same exact issue on Windows. Any updates?

**Comment by jvishnuvardhan** [comment]
@sscardapane and @danaugrs Could you follow this [solution](https://github.com/tensorflow/tensorflow/issues/24886) and let us know how it progresses? Thanks!

**Comment by danaugrs** [comment]
@jvishnuvardhan Thanks! The Windows path length limit was the issue. I edited the Windows Registry following the instructions on [this page](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/) to remove the limit.

**Comment by jvishnuvardhan** [comment]
@sscardapane Can you follow solution provided by @danaugrs. Please let me know how it progresses or close the issue if you already resolved. Thanks @danaugrs.

**Comment by sscardapane** [comment]
Thanks, that was the issue.

**Comment by ChrisMLikesMath** [comment]
had a similar issue but on windows 7. after seeing the environment variable underlying issue, tried pip install --user ... which also worked for anyone else who encounters this.
