### ISSUE TITLE
Building Pip package keeps failing

### ISSUE THREAD

**Issue by iseegr8tfuldeadppl** [tensorflow/tensorflow#24716]
**System information**
- OS Platform and Distribution: Windows 10
- Mobile device: Lenovo Z50 Laptop
- TensorFlow installed from (source or binary): source
- TensorFlow version: i'm not sure
- Python version: 3.6
- Installed using virtualenv? pip? conda?: i don't have it installed i cloned the github repository though i ran through issues and been told to not have tensorflow installed before building pip packages
- Bazel version (if compiling from source): 0.18.0
- GCC/Compiler version: i don't know where to find that
- CUDA/cuDNN version: 9.0/7.4.1
- GPU model and memory: NVIDIA GEFORCE 850M

**Describe the problem**
  So After i cloned the tensorflow repository i typed python ./configure.py but then following the steps it didn't show "configuration finished" at the end and neither any errors, so i tried to build the pip packages with gpu support since my gpu supports cuda and that stuff but then it abored due to the issues below but before that it keeps spamming a certain line, and also where am i failing it's been 5 days of purely tensorflow installation i just wanna make things learn!!

```
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (252 packages loaded)
    Fetching https://mirror.bazel.build/.../archive/7f634429a04abc48e2eb041c81c5235816c96514.tar.gz; 360,763b 13s
FAILED: Build did NOT complete successfully (305 packages loaded)
```

**Comment by iseegr8tfuldeadppl** [comment]
hey! so i've bypassed some issues but i'm still getting that spammed line with the fetching below it

**Comment by ymodak** [comment]
Is this still an issue for you? Can you please share the error message?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
