### ISSUE TITLE
Tensor conversion requested dtype float32_ref for Tensor with dtype float32?

### ISSUE THREAD

**Issue by cjjjy** [tensorflow/tensorflow#24714]
Hi:
my program have bug in these code line:
     
               word_embeddings = tf.scatter_nd_update(var_output, error_word_f, sum_all)
                word_embeddings_2 = tf.nn.dropout(word_embeddings, self.dropout_pl)

The error hint as follows:
ValueError: Tensor conversion requested dtype float32_ref for Tensor with dtype float32: 'Tensor("dropout:0", shape=(), dtype=float32)
  ========================================
   it looks  like word_embeddings 's dtype is float32_ref but actual the function tf.nn.dropout  need word_embeddings dtype float32  ,how can i convert word_embeddings's dtype float32_ref to float32 before run  tf.nn.dropout(word_embeddings, self.dropout_pl)?

**Comment by ymodak** [comment]
Have you tried using tf.cast function?

**Comment by ymodak** [comment]
Closing since this is now a duplicate of latest posted issue. Lets track it there.
