### ISSUE TITLE
Problems with building tensorflow

### ISSUE THREAD

**Issue by scorpionsting6x3** [tensorflow/tensorflow#24721]
Hello,

I'm having problems building tensorflow from source using bazel. I am currently using the guide here: (https://medium.com/@amsokol.com/update-2-how-to-build-and-install-tensorflow-gpu-cpu-for-windows-from-source-code-using-bazel-61c26553f7e8)

I have verified that everything is installed correctly, and keep on running into problems when it comes time to build. I have tried multiple versions of bazel, making sure to clean between builds.

**System information**
OS =  windows 7
CPU = i7-4790k
GPU = RTX2070, GTX970

I have decided to stick with bazel 0.19.0 as this is the only version that actually progresses. Others seems to get hung up in one place or another.

bazel info release results in: 
WARNING: The following rc files are no longer being read, please transfer their
contents or import their path into one of the standard rc files:
c:\users\scorpion\development\tensorflow-build\tensorflow/.bazelrc
c:\users\scorpion\development\tensorflow-build\tensorflow/tools/bazel.rc
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
release 0.19.0

--Though I have been able to find individuals reporting similar issues, I have not been able to find a solution to the problem.

When it comes time to build, here is the result:

(tensorflow-v1.12) C:\Users\SCORPION\Development\tensorflow-build\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their
contents or import their path into one of the standard rc files:
c:\users\scorpion\development\tensorflow-build\tensorflow/.bazelrc
c:\users\scorpion\development\tensorflow-build\tensorflow/tools/bazel.rc
Starting local Bazel server and connecting to it...
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: tensorflow/tools/pip_package
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (1 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (2 packages loaded, 0 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (5 packages loaded, 0 targets configured)
ERROR: While resolving toolchains for target //tensorflow/tools/pip_package:simple_console_for_windows: invalid registered toolchain '@local_config_sh//:local_sh_toolchain': no such package '@local_config_sh//': type 'path' has no method replace(string, string)
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: invalid registered toolchain '@local_config_sh//:local_sh_toolchain': no such package '@local_config_sh//': type 'path' has no method replace(string, string)
INFO: Elapsed time: 12.142s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (10 packages loaded, 29 targets configured)
FAILED: Build did NOT complete successfully (10 packages loaded, 29 targets configured)

Any help would be greatly appreciated

Edit:
After playing around with everything, changing bazel to 0.20.0, and reconfiguring, I am now receiving this error:

C:\tensorflow>bazel build --config=opt --cpu=x64_windows --compiler=msvc-cl --incompatible_remove_native_http_archive=false --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

WARNING: The following rc files are no longer being read, please transfer their
contents or import their path into one of the standard rc files:
c:\tensorflow/.bazelrc
c:\tensorflow/tools/bazel.rc
WARNING: The following configs were expanded more than once: [cuda]. For repeata
ble flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
INFO: Invocation ID: 3fb463b2-516b-4fc8-a22f-f30ba60ff8f3
Loading:
Loading: 0 packages loaded
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages l
oaded, 0 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (2 packages l
oaded, 0 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (55 packages
loaded, 62 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (119 packages
 loaded, 2958 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (190 packages
 loaded, 3607 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (224 packages
 loaded, 4739 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (232 packages
 loaded, 4776 targets configured)
ERROR: C:/tensorflow/third_party/eigen3/BUILD:34:1: no such package '@eigen_arch
ive//': Traceback (most recent call last):
        File "C:/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/tensorflow/third_party/repo.bzl", line 69, in _apply_patch
                _wrap_bash_cmd(ctx, ["patch", "-p1", "-d", ctx.pa...)])
        File "C:/tensorflow/third_party/repo.bzl", line 28, in _wrap_bash_cmd
                fail("BAZEL_SH environment variable i...")
BAZEL_SH environment variable is not set and referenced by '//third_party/eigen3
:eigen3'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' fai
led; build aborted: no such package '@eigen_archive//': Traceback (most recent c
all last):
        File "C:/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/tensorflow/third_party/repo.bzl", line 69, in _apply_patch
                _wrap_bash_cmd(ctx, ["patch", "-p1", "-d", ctx.pa...)])
        File "C:/tensorflow/third_party/repo.bzl", line 28, in _wrap_bash_cmd
                fail("BAZEL_SH environment variable i...")
BAZEL_SH environment variable is not set
INFO: Elapsed time: 8.092s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (233 packages loaded, 4776 targets c
onfigured)
FAILED: Build did NOT complete successfully (233 packages loaded, 4776 targets c
onfigured)

All of the bazel environment variables are definitely set though...

Edit 2:
OK! So I finally got it to build correctly (I think). It seems like I got every error that this thing could throw at me, but it was the weekend and I had time to actually work through the logs and errors.

One of the errors it kept snagging on was swig not being present in the /_bazel_scorpion/ folder even though swig was set in environment variables. I decided to copy the swig files over that I had to that folder and that seemed to fix that problem.

Adding the patches, mentioned in the post at the beginning of this comment, helped bypass issues with bazel.rc

I also had to change a const value in a header file to progress past another problem (I apologize, but I have totally forgotten the error thrown and the specific header file. If I find the issue again I will reference it here).

Another was it kept throwing this 'x64_windows' error. Fixed with the '--cpu=x64_windows --compiler=msvc-cl' build option.

Another issue was it kept having problems downloading resources, or at least that's what I was able to gather from the errors it was throwing. Using pip install h5py fixed this issue, and pip install enum34 fixed some other issue I can't remember right now.

I don't remember exactly what this other error was, but I fixed that by having to uninstall .NET 4.7, installing .NET 4, installing whatever package I was trying to install, and then upgrading to .NET 4.7 again. I think it was an SDK referenced somewhere.

Anyways, I was finally able to get it to work by entering:
bazel build --cpu=x64_windows --compiler=msvc-cl --incompatible_remove_native_http_archive=false --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

I initially tried to build from source because it kept on hanging on 'adding available GPU device' for 3-4min when I installed tensorflow-gpu using pip. (On a side note, I had to specifically enter '5.2,7.5' in 'python ./configure' to get this issue to stop happening. This seems like... a really big issue for a lot of people though. Will these issues be fixed in the future?
Best of luck to everyone trying to do this and running into problems. I hope this helps some of you!

**Comment by ymodak** [comment]
@scorpionsting6x3 Thanks for sharing your steps. We can expect smoother builds for cuda 10 starting from TensorFlow 2.0 I will close this issue since its solved.
