### ISSUE TITLE
ExtractImagePatches request

### ISSUE THREAD

**Issue by TheSadRhino** [tensorflow/tensorflow#24720]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 1.12

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONCATENATION, CONV_2D, MAXIMUM, MAX_POOL_2D, MUL, PAD. Here is a list of operators for which you will need custom implementations: ExtractImagePatches.

```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rmothukuru** [comment]
@TheSadRhino,
**`Tensorflow`** has undergone many Upgrades and Advances in past 2 years. Can you please confirm if the API, [tf.image.extract_patches](https://www.tensorflow.org/api_docs/python/tf/image/extract_patches) resolves your issue? Thanks!

**Comment by bhack** [comment]
Probably we could maintain this, upgrade label, and close the fresh duplicate at https://github.com/tensorflow/tensorflow/issues/50344

**Comment by namanbiyani** [comment]
@bhack  How can one give custom define tf.image.extract_patches op for converting model to a tflite model?

**Comment by karimnosseir** [comment]
Replied on the other issue. Closing this duplicate one.
