### ISSUE TITLE
Error building master branch from source

### ISSUE THREAD

**Issue by Shiki-H** [tensorflow/tensorflow#24722]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: master branch
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 18 and 19
- GCC/Compiler version (if compiling from source): 5.4
- CUDA/cuDNN version: 9.0/7.2 and 10.0/7.4
- GPU model and memory: GT 755M

**Describe the problem**

The problem occurred for both gpu and cpu build. I was able to replicate the error on two different machines with set up listed above (i.e. one with cuda 9.0 and cuDNN 7.2 and another with cuda 10.0 and cuDNN 7.4). On both machines, I was able to build tensorflow 1.12 without any issue.

The exact error message is follows:

```bash
ERROR: missing input file '@pasta//:LICENSE'
ERROR: /home/shiki/tensorflow/tensorflow/tools/pip_package/BUILD:235:1: //tensorflow/tools/pip_package:build_pip_package: missing input file '@pasta//:LICENSE'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/shiki/tensorflow/tensorflow/tools/pip_package/BUILD:235:1 1 input file(s) do not exist
```

It seems that the issue is related to dependency with respect to `pasta` which unfortunately I am not familiar with.

**Comment by laochanlam** [comment]
@YellowOldOdd cool you save my time

**Comment by freedomtan** [comment]
this should be fixed by 48d0e4d813b914fc480c51de5c48903b9bcc4cc7.
I created a similar patch, git pull, and found that it was fixed.

**Comment by Shiki-H** [comment]
@YellowOldOdd @freedomtan thanks for the help.

**Comment by Shiki-H** [comment]
closing this issue now since it has been fixed
