### ISSUE TITLE
 AttributeError: module 'tensorflow.python.pywrap_tensorflow' has no attribute 'IsSequenceForData'

### ISSUE THREAD

**Issue by zyq11223** [tensorflow/tensorflow#24739]
I have followed the TensorFlow tutorial, "first_steps_with_tensor_flow.ipynb"  When I ran the code below local , I got  the error messages behind the code below:

from __future__ import print_function

import math

from IPython import display
from matplotlib import cm
from matplotlib import gridspec
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from sklearn import metrics
import tensorflow as tf
from tensorflow.python.data import Dataset

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-f9edf7e7a602> in <module>
----> 1 from tensorflow.python.data import Dataset

~/zhang/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tensorflow/python/data/__init__.py in <module>
     23 
     24 # pylint: disable=unused-import
---> 25 from tensorflow.python.data import experimental
     26 from tensorflow.python.data.ops.dataset_ops import Dataset
     27 from tensorflow.python.data.ops.iterator_ops import Iterator

~/zhang/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tensorflow/python/data/experimental/__init__.py in <module>
     66 # pylint: disable=unused-import
     67 
---> 68 from tensorflow.python.data.experimental.ops.batching import dense_to_sparse_batch
     69 from tensorflow.python.data.experimental.ops.batching import map_and_batch
     70 from tensorflow.python.data.experimental.ops.batching import unbatch

~/zhang/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tensorflow/python/data/experimental/ops/batching.py in <module>
     20 import numpy as np
     21 
---> 22 from tensorflow.python.data.experimental.ops import get_single_element
     23 from tensorflow.python.data.experimental.ops import grouping
     24 from tensorflow.python.data.ops import dataset_ops

~/zhang/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tensorflow/python/data/experimental/ops/get_single_element.py in <module>
     18 from __future__ import print_function
     19 
---> 20 from tensorflow.python.data.ops import dataset_ops
     21 from tensorflow.python.data.util import nest
     22 from tensorflow.python.data.util import sparse

~/zhang/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py in <module>
     26 
     27 from tensorflow.python.compat import compat
---> 28 from tensorflow.python.data.ops import iterator_ops
     29 from tensorflow.python.data.util import nest
     30 from tensorflow.python.data.util import random_seed

~/zhang/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py in <module>
     22 
     23 from tensorflow.python.compat import compat
---> 24 from tensorflow.python.data.ops import optional_ops
     25 from tensorflow.python.data.util import nest
     26 from tensorflow.python.data.util import sparse

~/zhang/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tensorflow/python/data/ops/optional_ops.py in <module>
     20 import abc
     21 
---> 22 from tensorflow.python.data.util import structure
     23 from tensorflow.python.framework import dtypes
     24 from tensorflow.python.framework import ops

~/zhang/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tensorflow/python/data/util/structure.py in <module>
     20 import abc
     21 
---> 22 from tensorflow.python.data.util import nest
     23 from tensorflow.python.framework import dtypes
     24 from tensorflow.python.framework import ops

~/zhang/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tensorflow/python/data/util/nest.py in <module>
     98 
     99 # See the swig file (../../util/util.i) for documentation.
--> 100 is_sequence = _pywrap_tensorflow.IsSequenceForData
    101 
    102 # See the swig file (../../util/util.i) for documentation.

AttributeError: module 'tensorflow.python.pywrap_tensorflow' has no attribute 'IsSequenceForData'

**Comment by jvishnuvardhan** [comment]
@zyq11223, as it is not clear to find the root-cause of the issue, could you fill the following build/installation [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md).  Please report the installation process followed and commands used.

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
