### ISSUE TITLE
Error while building from source with Bazel: in target '//external:cc_toolchain': no such package '@local_config_cc//'

### ISSUE THREAD

**Issue by Maxtoq** [tensorflow/tensorflow#24735]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.20.0

**Describe the problem**
I followed the instructions to build TF from source with bazel. But this error occurs:

> C:\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\tensorflow/.bazelrc
Starting local Bazel server and connecting to it...
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
INFO: Invocation ID: 1a8498c3-1a43-45b0-abe9-317aa5b27e0b
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/cc_configure.bzl", line 51
                configure_windows_toolchain(repository_ctx)
        File "C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 347, in configure_windows_toolchain
                _find_missing_vc_tools(repository_ctx, vc_path)
        File "C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 257, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, vc_path, tool)
        File "C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 230, in find_msvc_tool
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)
INFO: Elapsed time: 4,086s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded)
    Fetching @local_config_cc; fetching

(I did the default configuration)

The weird thing is that it seems to look for a file in MSVC 2017, while I have MSVC 2015 Update 3 installed (I also tried with MSVC 2017, same error).

Note that I had tried building with Cuda 9.0 before and had a similar error ( issue #24549 ).

Is there anything I can do ?

Thanks.

**Comment by Maxtoq** [comment]
Hi,
I tried this and I have the same issue:

> C:\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
DEBUG: C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for Visual C++ through registry
DEBUG: C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\VC
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/cc_configure.bzl", line 51
                configure_windows_toolchain(repository_ctx)
        File "C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in configure_windows_toolchain
                _find_missing_vc_tools(repository_ctx, vc_path)
        File "C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 253, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, vc_path, tool)
        File "C:/users/maxim/_bazel_maxim/xv6zejqw/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 226, in find_msvc_tool
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)
INFO: Elapsed time: 0,651s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

I'm starting to think my installation of Visual Studio Code could be part of the issue.
The folder "Tools" is missing in "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/".

Do you have any clue ?

Thanks

**Comment by msymp** [comment]
@Maxtoq , you may be correct, it has been noticed that MSVC 2015 update 3 is more reliable with r1.12.0 , and since you are building r1.13.0 from source, please investigate this. Thanks.

**Comment by Maxtoq** [comment]
But last try was actually with r1.12.0 and MSVC 2015 Update 3 (and bazel 0.15.0).
The weird thing is that it still tries to look for a file in the folder "../Miscrosoft Visual Studio/2017/".
I'm gonna try to uninstall VS Code and reinstall MSVC 2015 to see if there's a change.

If you have any other idea, I'll take it.

Thanks.

**Comment by msymp** [comment]
Hi @mrry , can you advise what this user may be facing with respect to the MSVC 2017? Thanks.

**Comment by msymp** [comment]
Hi @Maxtoq , I believe you may have narrowed it down. Can you please submit the issue with the Bazel GitHub community, since it is a bazel / MSVC 2015 issue along with your specific environment. Their link is: https://github.com/bazelbuild/bazel/issues
Meanwhile we will close the issue here. Thanks.

**Comment by Maxtoq** [comment]
I'll do that.
Thanks

**Comment by Maxtoq** [comment]
I solved the problem. The problem was I had badly set the environment variable BAZEL_VS (or BAZEL_VC). I followed the examples given here: https://docs.bazel.build/versions/0.21.0/install-compile-source.html#bootstrap-windows-bootstrap.
