### ISSUE TITLE
Issue with deep dream example

### ISSUE THREAD

**Issue by manucarbonell** [tensorflow/tensorflow#2474]
I get this error when creating the session in the Deep Dream notebook example without any modifications. Does anybody know what does exactly mean?
Input: 
```
sess = tf.InteractiveSession(graph=graph)
````
Output
```
Exception AssertionError: AssertionError() in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x1128b5990>> ignored
Exception AssertionError: AssertionError() in <generator object get_controller at 0x1128a5af0> ignored
```
Thanks,
Manu

**Comment by mrry** [comment]
Thanks for raising this! We should have a fix coming out soon.

**Comment by drcrook1** [comment]
Any idea what hte core issue was?  I'm getting the same with RNN.
