### ISSUE TITLE
how to read tflite

### ISSUE THREAD

**Issue by learnerwang** [tensorflow/tensorflow#24755]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by learnerwang** [comment]
System information:Linux Ubuntu 16.04
TensorFlow installed from:binary
TensorFlow version:1.12 cpu
 Dear developers:
    I have transformed the inceptionV3 tflite file using toco, and the type is uint8. I have one task is that to parse the tflite file and transform it to the format I want. The first step is to parse it, I have used tf.contrib.lite.Interpreter to get the tensor shape ,value. But I could not get the  GraphDef using tf.contrib.lite.Interpreter. Is there some way to get the graph and each OP's parameter like convolution stride, kerne size ?
Best regards

**Comment by andrehentz** [comment]
There is no GraphDef equivalent to a .tflite file. If you need to make transformation to the GraphDef, the best approach is to do so before you use toco.
