### ISSUE TITLE
 tf.train.init_from_checkpoint incorrectly raises ValueError

### ISSUE THREAD

**Issue by sharvil** [tensorflow/tensorflow#24756]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v1.12.0-rc2-3-ga6d8ffa 1.12.0
- Python version: 3.5.2
- Bazel version (if compiling from source): 0.16.1
- GCC/Compiler version (if compiling from source): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
- CUDA/cuDNN version: CUDA 9.1, cuDNN 7.1.3
- GPU model and memory: 1080Ti (11178MiB)

**Describe the current behavior**
1. Train a model.
2. Add a new variable to the computation graph.
3. Attempt to initialize the updated graph using `tf.train.init_from_checkpoint`.
4. Notice that a `ValueError` is raised instead of `tf.errors.OpError`.

```
  File ".../model.py", line 53, in warmup
    tf.train.init_from_checkpoint(self._model_dir, {'/': 'model/'})
  File ".../tensorflow/python/training/checkpoint_utils.py", line 187, in init_from_checkpoint
    _init_from_checkpoint, ckpt_dir_or_file, assignment_map)
  File ".../tensorflow/python/training/distribute.py", line 1053, in merge_call
    return self._merge_call(merge_fn, *args, **kwargs)
  File ".../tensorflow/python/training/distribute.py", line 1061, in _merge_call
    return merge_fn(self._distribution_strategy, *args, **kwargs)
  File ".../tensorflow/python/training/checkpoint_utils.py", line 268, in _init_from_checkpoint
    tensor_name_in_ckpt, ckpt_dir_or_file
ValueError: Tensor params (params in /) is not found in [...] checkpoint
```

**Describe the expected behavior**
Documentation for `tf.train.init_from_checkpoint` states that `tf.errors.OpError` should be raised. It's unclear if the docs are wrong or the implementation is wrong but I think it's the implementation.

**Comment by allenlavoie** [comment]
ValueError is a bit more standard/specific than OpError. Does seem like the docstring should be updated. Can you send a PR?

**Comment by sharvil** [comment]
Are there any other code paths in `tf.train.init_from_checkpoint` that could raise `tf.errors.OpError`? If so, simply updating the docstring doesn't seem like the right answer here. I'll also point out that making the doc change would make it harder to distinguish between two pretty distinct error modes: missing variables in graph vs. missing tensors in checkpoints.

**Comment by allenlavoie** [comment]
AFAICT the docstring was never correct. So unless there's a strong use-case for a different exception type I'd say it just needs a docstring update.

**Comment by sharvil** [comment]
Good to know. I won't be able to make the docstring change but hopefully someone can take this on.

**Comment by yongtang** [comment]
@sharvil Created a PR for that.

**Comment by sharvil** [comment]
Nice, thanks for the fix @yongtang!
