### ISSUE TITLE
saved_model_portable_proto target doesn't exist

### ISSUE THREAD

**Issue by lesniewski** [tensorflow/tensorflow#24752]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.5 LTS
- TensorFlow installed from (source or binary): source
- TensorFlow version: v1.12.0
- Python version: 2.7.12
- Bazel version (if compiling from source):
Build label: 63d51e23a26a25116e659a75113ee654a62213c5
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 3 01:24:53 2019 (1546478693)
Build timestamp: 1546478693
Build timestamp as int: 1546478693

- GCC/Compiler version (if compiling from source): 8.2.0

**Describe the problem**

Dangling reference to `//tensorflow/core:saved_model_portable_proto` within `if_mobile()` guard here:
https://github.com/tensorflow/tensorflow/blob/fbbecc81be3b1eab0c15020ce3b0566e60e25c7f/tensorflow/cc/saved_model/BUILD#L50

Seems similar to:
https://github.com/tensorflow/tensorflow/issues/4312

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Caused failure of unrelated `genquery` rule; even though if_mobile was disabled, it seems to error out on undefined dependencies.

**Comment by petewarden** [comment]
Thanks for the report! I don't know when we'll have a chance to work on this, since it's not directly causing a build error, so closing for now.

**Comment by timokau** [comment]
Is there any actual work necessary? Wouldn't it be enough to just remove that  target?

**Comment by vmrob** [comment]
This dangling reference breaks configuration-agnostic Bazel queries (e.g. `bazel query`, not `bazel cquery`).

**Comment by matthewbauer** [comment]
This was fixed in b39b1ed24b4814db27d2f748dc85c10730ae851d btw
