### ISSUE TITLE
TensorFlowLite: failed to load native library: no tensorflowlite_jni in java.library.path

### ISSUE THREAD

**Issue by majiali1995** [tensorflow/tensorflow#24761]
TensorFlowLite: failed to load native library: no tensorflowlite_jni in java.library.path

**Comment by jvishnuvardhan** [comment]
@majiali1995, as it is not clear to find the root-cause of the issue, could you fill the following build/installation [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md).  Please report the installation process followed and commands used.

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by OswinGuai** [comment]
@majiali1995 Have you solved that problem? I met this in the unit test.
