### ISSUE TITLE
tf.estimator support multi saver and train_op for training multi model at the same time

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#24763]

**Comment by jvishnuvardhan** [comment]
@zh794390558, Could you provide more details on the issue? As it is not clear to find the root-cause of the issue with the limited details provided, could you fill the following build/installation [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md).  Please provide any code to reproduce the issue.

**Comment by rmothukuru** [comment]
@zh794390558,
Sorry for the delayed response. Can you please refer the [documentation of Distribution Strategy using Estimators](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_estimator) and let us know if this is what you are looking for? Thanks!
