### ISSUE TITLE
tfdbg gets stuck with nested tf.scan calls

### ISSUE THREAD

**Issue by hsilva664** [tensorflow/tensorflow#24772]
**tfdbg gets stuck with nested tf.scan calls**

I was running https://github.com/hmishra2250/NTM-One-Shot-TF implementation of MANN on Tensorflow and had some problems using tfdbg with it. The code runs fine without the debugger mode, but gets stuck after the first .run() call when wrapped with the debugger. I've tried greatly reducing parameter and batch sizes to see if memory or performance was the issue, but the problem persisted.

After some tweaking, I believe the source of the debugger not responding is due to nested tf.scan calls (file mann/Model.py, fuction step() calls update_tensor from MANN/utils/tf-utils.py). The reason for that is that the program responded fine when I replaced the inner tf.scan call with a tf.zeros corresponding to the needed output.

The weird thing is that https://github.com/vineetjain96/one-shot-mann implementation, which is based on the code mentioned before, works perfectly on tfdbg. The main difference between the implementations is that the second one only uses simple tf.scan calls, without nesting. I find this behavior undesirable and thus report it in this issue.

- Linux Ubuntu 16.04
- TensorFlow 1.12.0 installed from source
- Python 2.7.12
- Bazel 0.21.0
- GCC 5.4.0
- CUDA 10
- cuDNN 7.4
- GeForce GTX 1080; 8GB RAM GDDR5x; PCI-EXP
- Code to reproduce: wrap https://github.com/hmishra2250/NTM-One-Shot-TF main file (Omniglot.py) with tfdbg and run it.

**Comment by msymp** [comment]
Hello @hsilva664 , Just to be aligned, can we back up and build with bazel 0.15.0 , gcc 4.8 , CUDA 9 / cuDNN 7.4 and check if the tfdbg works then?

**Comment by msymp** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
