### ISSUE TITLE
assert_shapes for validating tensor shapes and their relationships to other tensors 

### ISSUE THREAD

**Issue by bodin-e** [tensorflow/tensorflow#24779]
**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I am under the impression that many errors users of TensorFlow (and users of libraries making use of TensorFlow) run into has their source in mistakes in passing it tensors with the correct/expected dimension order (and number of dimensions), especially when many tensors are passed together that have relationships expected of them. Due to broadcasting (something very useful and powerful in itself) or sheer misfortune, these mistakes can easily end up hidden as they may not raise any errors neither at graph construction time nor at graph runtime.

What I suggest is an assert function something like the following (see 'assert_shapes' below): 
```python
def model(x, y, param, other_param):
    assert_shapes({
        ("x", x): ('N', 'Q'),
        ("y", y): ('N', 'D'),
        ("param", param): 'Q',
        ("other param", other_param): 2,
    })
    ...
```
where x, y, param and other_param are tensors. The value of an entry in the dict above are representing the corresponding tensor shape: symbolically or explicitly. In the example above the first dimension of x and y are to always match in size, the second dimension of x must match the size of param and other_param must always have size two. 

If the caller of the code above writes something like:
```python
m = model(
    x=tf.ones([10, 2]),
    y=tf.ones([1, 10]),
    param=tf.ones([2]),
    other_param=tf.ones([2])
)
```
this can raise an error as: AssertionError: Tensor 'y' dim 0 was of size 1 but was expected to be 10 as declared by 'x' dim 0.

A quick demonstrative implementation with some more examples of this can be found here: https://github.com/bodin-e/tensorcheck

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Users interested in catching mistakes in their (or others) code early and explicitly, where the mistakes have to do with tensor shapes and relationships between tensors' shapes.

**Comment by bodin-e** [comment]
Great. I agree fully about the signature change to skip separate/redundant name passing. 

I'll send a pull request in the coming weeks.

**Comment by dynamicwebpaige** [comment]
Closing this issue, as the feature has been added in PR #25422. 

Thanks for your contribution to TensorFlow! 😄
