### ISSUE TITLE
How to freeze low_latency_svdf model?

### ISSUE THREAD

**Issue by auvilink** [tensorflow/tensorflow#24775]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac OSX Mojave 10.14.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
pip install tensorflow (binary)
- TensorFlow version (use command below):
latest
- Python version:
both 2.7 and 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

Trained the low_latency_svdf model according to the tutorial (https://www.tensorflow.org/tutorials/sequences/audio_recognition)

python tensorflow/examples/speech_commands/train \
--model_architecture=low_latency_svdf \
--how_many_training_steps=100000,35000 \
--learning_rate=0.01,0.005

Then try to freeze the graph after finished training:

python tensorflow/examples/speech_commands/freeze.py \
--model_architecture=low_latency_svdf \
--start_checkpoint=/tmp/speech_commands_train/low_latency_svdf.ckpt-135000 \
--output_file=/tmp/my_frozen_graph.pb

Now the errors are:

"  File "/Users/michaelhe/ml/env/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1582, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [256,12] rhs shape= [256,16]"

**Describe the expected behavior**
Should generate pb file

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by msymp** [comment]
@auvilink is executing a widely used speech recognition tutorial of the binary release on MacOS. They seem to observe a shape mismatch error. @allenlavoie can you advise. Thanks.

**Comment by allenlavoie** [comment]
@petewarden do you know who's maintaining the audio recognition example? (This looks like it's more to do with the example itself than saving APIs)

**Comment by auvilink** [comment]
@allenlavoie @petewarden I also copied those files to a linux machine (ubuntu 16.04) and re-tried the same command "python tensorflow/examples/speech_commands/freeze.py 
--model_architecture=low_latency_svdf 
--start_checkpoint=/tmp/speech_commands_train/low_latency_svdf.ckpt-135000 
--output_file=/tmp/my_frozen_graph.pb"

I got the same error:

"    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [12] rhs shape= [16]
	 [[node save/Assign_1 (defined at /home/michael/asr/tensorflowtrain/speech_commands/models.py:154)  = Assign[T=DT_FLOAT, _class=["loc:@final_fc_bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](final_fc_bias, save/RestoreV2:1)]]
"

Thanks guys.

**Comment by auvilink** [comment]
I retrained it and it works now. Thanks guys.
