### ISSUE TITLE
tf.contrib.estimator.early_stopping doesn't work with tf.keras.estimator.model_to_estimator

### ISSUE THREAD

**Issue by philnguyenresson** [tensorflow/tensorflow#24771]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary/pip
- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 3.5

**Describe the current behavior**
tf.keras.estimator.model_to_estimator returns tensorflow.python.estimator.estimator.Estimator class.
tensorflow.contrib.estimator.make_early_stopping_hook checks for tf.estimator.Estimator class.

TypeError: `estimator` must have type `tf.estimator.Estimator`. Got: <class 'tensorflow.python.estimator.estimator.Estimator'>

**Code to reproduce the issue**
model = tf.keras.applications.MobileNetV2()
model.compile(tf.keras.optimizers.Adam(),"categorical_crossentropy")
estimator = tf.keras.estimator.model_to_estimator(model)
early_stop = tf.contrib.estimator.stop_if_no_decrease_hook(estimator, "loss",1) <--crashes

**Comment by yongtang** [comment]
@philnguyenresson I am not able to reproduce with tf-nightly. Can you give tf-nightly a try and see if the issue has been solved or not?

**Comment by philnguyenresson** [comment]
I haven't been able to try tf-nightly, but it does work fine on a more up to date version of tensorflow
