### ISSUE TITLE
TensorRT's create_inference_graph() produced output with too big size

### ISSUE THREAD

**Issue by sonnguyen64** [tensorflow/tensorflow#24789]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow version (use command below): 1.12.0
- Python version: 3.6.7
- CUDA/cuDNN version: 9.0
- GPU model and memory: Titan V

**Describe the current behavior**

I have tried to optimize my custom frozen model to run on TensorRT using `create_inference_graph()`, however, the output was larger than the original model (my model is around 200MB, but after converting it's more than 2GB). When I increased `minimum_segment_size` to 30 or 40, the size was samller but still slightly bigger than the original one.

**Describe the expected behavior**
Smaller size of output graph

**Code to reproduce the issue**

```
trt_graph = trt.create_inference_graph(
        input_graph_def=frozen_graph,
        outputs,
        max_batch_size=64,
        max_workspace_size_bytes=1 << 25,
        precision_mode='FP16',
        minimum_segment_size=10
)
```

**Other info / logs**
Because the model was way too big, I couldn't serialize it to .pb file, so that I had this error:
`[libprotobuf ERROR external/protobuf_archive/src/google/protobuf/message_lite.cc:289] Exceeded maximum protobuf size of 2GB: 2756916500`

**Comment by trevor-m** [comment]
This may be caused by this change: https://github.com/tensorflow/tensorflow/pull/24478

**Comment by msymp** [comment]
Hello @sonnguyen64 , please provide the model as the community has requested. Thanks.

**Comment by sonnguyen64** [comment]
Thanks @samikama, @trevor-m and @msymp a lot for your responses.

Download my model [here](https://drive.google.com/open?id=1cyMN34fkqNsWQLL5X4drGL0Ar6YJTE11). It includes the Tensorflow checkpoint files and conversion code. When running file `convert.py`, it'll have the error about exceeding 2GB.

For the model details, this is the repo I'm using to produce the checkpoint: https://github.com/DeepRNN/visual_question_answering

**Comment by damitkwr** [comment]
I got the same issue with the GNMTv2 model as well. It literally doubled the model size

**Comment by Kuanch** [comment]
This still happens on TF1.13 with TensorRT 5.0.6, InceptionResnetV2 is twice bigger than before tf-trt optimization, independent from any optimization parameters.

**Comment by sanatmpa1** [comment]
@sonnguyen64,

We see you were using an older version of Tensorflow `1.x` which is not officially supported anymore. We recommend that you upgrade to latest stable version and let us know if the issue still persists.Thanks!
