### ISSUE TITLE
Recurrent batch normalization : While_loop and control_depenecies bug

### ISSUE THREAD

**Issue by AzizCode92** [tensorflow/tensorflow#24795]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.8.0
- Python version: 2.7
- Bazel version (if compiling from source): compiled from source 
- GCC/Compiler version (if compiling from source): c++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
- CUDA/cuDNN version: 9.1
- GPU model and memory:  Tesla K80 

**Describe the current behavior**
Adding batch normalization to a bidirectional RNN prevent me from updating the moving_mean and moving_variances during training and inference correctly.
The problem is that both the ```tf.control_dependencies``` and the ``while_loop```  of the dynamic_rnn are executed at the same time. The gradient will find nodes that have input from different frames and will throw errors. 

My error message is  : 
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: node train/update (defined at ...)  has inputs from different frames. 
The input node bidirectional_rnn/fw/fw/while/fw/bnlstm_cell/bnlstm_cell/state/batch_normalization/AssignMovingAvg (defined at ... )  is in frame 'train/Listener/features/layer1/BLSTM/bidirectional_rnn/fw/fw/while/while_context'. The input node train/apply_gradients/Assign (defined at ... )  is in frame ''.
```

**Describe the expected behavior**
The expected behaviour is being able to add the control_dependencies when we have the while_loop context. 
Adding clearer documentation about how to handle the moving_mean and moving_variance in case you have a distributed training.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```python
def _update(self, loss, learning_rate, cluster):
    '''
    create the op to update the model

    args:
        loss: the loss to minimize
        learning_rate: the learning rate
        cluster: the tf cluster

    returns: the update op
    '''

    #create the optimizer
    optimizer = tf.train.AdamOptimizer(learning_rate)

    #create an optimizer that aggregates gradients
    if int(self.conf['numbatches_to_aggregate']) > 0:
        if 'local' in cluster.as_dict():
            num_workers = 1
        else:
            num_workers = len(cluster.as_dict()['worker'])

        optimizer = tf.train.SyncReplicasOptimizer(
            opt=optimizer,
            replicas_to_aggregate=int(
                self.conf['numbatches_to_aggregate']),
            total_num_replicas=num_workers)


    tf.summary.scalar('training_loss', loss,
                      collections=['training_summaries'])

    #get the list of trainable variables
    trainable = tf.trainable_variables()

    #get the list of variables to be removed from the trainable
    #variables
    untrainable = tf.get_collection('untrainable')

    #remove the variables
    trainable = [var for var in trainable
                 if var not in untrainable]

    #compute the gradients
    grads_and_vars = optimizer.compute_gradients(
        loss=loss,
        var_list=trainable)

    with tf.variable_scope('clip'):
        #clip the gradients
        grads_and_vars = [(tf.clip_by_value(grad, -1., 1.), var)
                          for grad, var in grads_and_vars]


    #opperation to apply the gradients
    apply_gradients_op = optimizer.apply_gradients(
        grads_and_vars=grads_and_vars,
        name='apply_gradients')

    #all remaining operations with the UPDATE_OPS GraphKeys
    update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
    print("update_ops {}".format(update_ops))
    print("################")
    #create an operation to update the gradients, the batch_loss
    #and do all other update ops
    update_op = tf.group(
        *([apply_gradients_op] + update_ops),
        name='update')

    return update_op

```
**Other info / logs**

related issues : 
1) https://github.com/tflearn/tflearn/issues/540#issue-197855026
2) https://github.com/tensorflow/tensorflow/issues/6087#issue-193534788

**Comment by AzizCode92** [comment]
Looking down for the implementation of the batch norm I read this comment on the code of the ```tf.contrib.layers.batch_norm```:

>  # Create moving_mean and moving_variance variables and add them to the
    # appropriate collections. We disable variable partitioning while creating
    # them, because assign_moving_average is not yet supported for partitioned
    # variables (this needs to be handled carefully, as it may break
    # the checkpoint backward compatibility).


 [link to the comment](https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/contrib/layers/python/layers/layers.py#L335)

**Comment by msymp** [comment]
Hello @AzizCode92 , confirm that you want this to be treated as documentation issue. Thanks.
Hi @ebrevdo , can we document this moving_mean/moving_variance behavior or is there some workaround? Thanks.

**Comment by AzizCode92** [comment]
Hello @msymp, thank you for your answer. Yes part of my question should be treated as lack of the documentation for handling the moving_mean/moving_variance in case of 
1. bidirectional rnn (how to keep track of the update_op inside the while_loop ).
2. distributed training (maybe extend the batch_norm to include number of gpus (int variable: optional) and it will handle averaging the mean/variance for you during training/inference)


However, the error when we got when handling the control_dependencies inside a while_loop was described by a lot of users before so maybe it should be treated as a bug.

**Comment by mohantym** [comment]
Hi @AzizCode92 !
1.x are not supported anymore. Could you provide a 2.x gist if this issue persists in 2.8 version. 
Thank you!
