### ISSUE TITLE
Regarding merging tensorflow and Arcore in android app

### ISSUE THREAD

**Issue by chiragmak1** [tensorflow/tensorflow#24804]
hello guys i am tryng to merge tensorflow and arcore in android app.i am facing this error ->
Error: Program type already present: android.support.design.widget.CoordinatorLayout$Behavior

and I think that we are merging two diffrent technology so there will be some gradle dependencies  are missing anyone of you has tried doing this can u suggest how can I fix

thanks in advance

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
