### ISSUE TITLE
Building TensorFlow with CMake

### ISSUE THREAD

**Issue by timbrucks** [tensorflow/tensorflow#2480]
I realize that building TensorFlow from CMake is not yet ready for prime time, but I am attempting to push through some of the challenges and issues getting that working on a Mac.

### Environment info

Operating System: Mac, OS X 10.11.5
Using CMake to create a make file (not interested in trying this with XCode yet)
Not currently using CUDA

Installed from sources, commit hash: 787b97e6

### Steps to reproduce

There are some issues with paths to eigen, json and re2 that I have been able to work around but I have run into a roadblock.

Several .cc files in tensorflow/core/framework/ directory attempt to include files that do not exist. The files to be included all end with ".pb_text.h". I assume that these files are (or should be) generated by the protocol buffer compiler. 

For example, from tensorflow/core/framework/attr_value_util.cc:
```
#include "tensorflow/core/framework/attr_value.pb_text.h"
#include "tensorflow/core/framework/tensor.pb_text.h"
```
As a result I get "file not found" errors when building.

### What have you tried?

There are some files in tensorflow/contrib/cmake/build/tensorflow/core/framework with similar names (like attr_value.pb.h and tensor.b.h) which I assume are generated by the protocol buffer compiler. I modified the .cc files which were causing trouble to include these files:
```
#include "tensorflow/core/framework/attr_value.pb.h"
#include "tensorflow/core/framework/tensor.pb.h"
```

That results in errors related to using undeclared identifiers: 

.../tensorflow/tensorflow/core/framework/attr_value_util.cc:44:28: error: use of undeclared
      identifier 'ProtoShortDebugString'
                           ProtoShortDebugString(tensor_proto), ">");

.../tensorflow/tensorflow/core/framework/attr_value_util.cc:62:14: error: use of undeclared
      identifier 'EnumName_DataType'
      return EnumName_DataType(attr_value.type());

(and so on)

**Comment by cg31** [comment]
*.pb_text.h is generated by tools/tools/proto_text, *.pb.h is generated by protoc, they are not the same, so replacing one to the other won't work.

**Comment by timbrucks** [comment]
@cg31 thanks for clarifying which tools generate which files. That was not clear to me. I figured that my attempt at replacing the files would not work, but tried anyway.

I looked around and found that files I need are actually generated when I build TF from source. They are buried deep in the bazel-out directory. So as a complete hack I copied the files I need from there. Definitely not a long-term solution, but it got me past this issue for now.

**Comment by petewarden** [comment]
It may be helpful to look at the work I've been doing to get TensorFlow's C++ core building with a plain makefile:
https://github.com/tensorflow/tensorflow/pull/2440
I build the proto_text tool and use that to generate the needed files.

**Comment by timbrucks** [comment]
Thanks @petewarden. I will give that a try.

**Comment by girving** [comment]
@petewarden @timbrucks What's the status of this?

**Comment by petewarden** [comment]
We don't plan on supporting cmake ourselves, we're putting our effort behind the makefile approach for the core runtime instead. Closing this one, since we're not going to support this method.
