### ISSUE TITLE
TFDBG Segmentation Fault

### ISSUE THREAD

**Issue by dgboy2000** [tensorflow/tensorflow#24817]
TFDBG encounters a seg fault (see output at bottom) when debugging my TF code. Incidentally this code hangs on a GPU, but code and tfdbg both run without incident on CPU only (setting tf.device). As a side note, is tensorflow ever supposed to produce different execution results on CPU and GPU?

- OS Platform and Distribution: AWS Deep Learning Base AMI (Ubuntu) Version 14.0 (ami-012b19f1736b6aae8)
- TensorFlow installed from (source or binary): tensorflow-gpu==1.12.0 installed by pip
- Python version: Python 3.6.7
- CUDA/cuDNN version: 9.0/7.3.1
- GPU model and memory: Tesla V100 with 16130MiB

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem. <== It's not clear why or where the seg fault occurs so I can't generate a minimal test case. I'd be happy to share my full code (a single python file) with you (the TF developers, eg via email) but don't want to post it on github at present.

**Other info / logs**

// Started tfdbg, called run() once to initialize the variables, then invoke_stepper and:

tfdbg> step
  -->(1 / 126)  [  H   ] model/transpose/sub/y
     (2 / 126)  [      ] model/transpose/Range/start
     (3 / 126)  [      ] model/TensorArrayStack/range/start

Continued to model/transpose/sub/y:

Stepper used feeds:
  (No feeds)

Tensor "model/transpose/sub/y":

1

tfdbg> s
     (1 / 126)  [  H   ] model/transpose/sub/y
  -->(2 / 126)  [  H   ] model/transpose/Range/start
     (3 / 126)  [      ] model/TensorArrayStack/range/start
     (4 / 126)  [      ] model/TensorArrayStack/range/delta

Continued to model/transpose/Range/start:

Stepper used feeds:
  (No feeds)

Tensor "model/transpose/Range/start":

0

tfdbg> s
     (1 / 126)  [  H   ] model/transpose/sub/y
     (2 / 126)  [  H   ] model/transpose/Range/start
  -->(3 / 126)  [  H   ] model/TensorArrayStack/range/start
     (4 / 126)  [      ] model/TensorArrayStack/range/delta
     (5 / 126)  [      ] model/transpose/Range/delta

Continued to model/TensorArrayStack/range/start:

Stepper used feeds:
  (No feeds)

Tensor "model/TensorArrayStack/range/start":

0

tfdbg> s
     (2 / 126)  [  H   ] model/transpose/Range/start
     (3 / 126)  [  H   ] model/TensorArrayStack/range/start
  -->(4 / 126)  [  H   ] model/TensorArrayStack/range/delta
     (5 / 126)  [      ] model/transpose/Range/delta
     (6 / 126)  [      ] model/TensorArray/size

Continued to model/TensorArrayStack/range/delta:

Stepper used feeds:
  (No feeds)

Tensor "model/TensorArrayStack/range/delta":

1

tfdbg> s
     (3 / 126)  [  H   ] model/TensorArrayStack/range/start
     (4 / 126)  [  H   ] model/TensorArrayStack/range/delta
  -->(5 / 126)  [  H   ] model/transpose/Range/delta
     (6 / 126)  [      ] model/TensorArray/size
     (7 / 126)  [      ] model/TensorArray

Continued to model/transpose/Range/delta:

Stepper used feeds:
  (No feeds)

Tensor "model/transpose/Range/delta":

1

tfdbg> s
     (4 / 126)  [  H   ] model/TensorArrayStack/range/delta
     (5 / 126)  [  H   ] model/transpose/Range/delta
  -->(6 / 126)  [  H   ] model/TensorArray/size
     (7 / 126)  [      ] model/TensorArray
     (8 / 126)  [      ] model/value/weights

Continued to model/TensorArray/size:

Stepper used feeds:
  (No feeds)

Tensor "model/TensorArray/size":

1

tfdbg> s
Segmentation fault (core dumped)
ubuntu@ip-10-0-0-9:~$

**Comment by hugo-boser** [comment]
i also have a very similar issue except it does not work on both cpu and gpu and it produces segmentationfault after i type run.

**Comment by sanatmpa1** [comment]
>"Segmentation fault error stands for a failure of the parallelization of your training process on the GPU"

Please take a look on the links [ref_1](https://stackoverflow.com/questions/54333809/how-to-remedy-segmentation-fault-core-dumped-error-when-trying-to-fit-a-kera), [ref_2](https://stackoverflow.com/questions/53302958/how-to-debug-tensorflow-segmentation-fault-in-model-fit) to understand more about the same.

**Comment by sanatmpa1** [comment]
@dgboy2000,

We see you were using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to latest stable version and let us know if the issue still persists in newer versions.we will get you the right help.Thanks!
