### ISSUE TITLE
TensorFlow binary was not compiled to use : AVX2 AVX512F FMA

### ISSUE THREAD

**Issue by robcustsup** [tensorflow/tensorflow#24814]
Using the virtualenv install procedure (https://www.tensorflow.org/install/pip)
(venv) user@ubuntu:~$ pip install --upgrade tensorflow

Installing collected packages: tensorflow
Successfully installed tensorflow-1.12.0

(venv) user@ubuntu:~$ python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"

2019-01-09 21:39:35.073563: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
tf.Tensor(276.40582, shape=(), dtype=float32)

I don't know if this is a warning or that TensorFlow is in fact installed.
Ubuntu 18.04
(venv) user@ubuntu:~$ python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
v1.12.0-0-ga6d8ffae09 1.12.0
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Python version**:
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by ymodak** [comment]
Its a warning message which you can safely ignore and continue using TensorFlow. Your TF installation is successful.

**Comment by robcustsup** [comment]
Thanks!

**Comment by adityasingh1993** [comment]
I tried to build tensorflow from source, AVX2 and FMA is fixed but still getting AVX512F warning.
Please suggest the procedure or build parameter to fix AVX512F warning.

**Comment by hongdd** [comment]
>>> tf.__version__sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
2019-03-28 22:10:46.054232: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Device mapping: no known devices.
2019-03-28 22:10:46.063724: I tensorflow/core/common_runtime/direct_session.cc:317] Device mapping:

what is the above instruction meaning?

**Comment by Aaron-DH** [comment]
> I tried to build tensorflow from source, AVX2 and FMA is fixed but still getting AVX512F warning.
> Please suggest the procedure or build parameter to fix AVX512F warning.

Hi , has you fix it?
I had the same problem and build tensorflow from source on intel xeon with:
bazel build --config=opt --config=mkl --copt="-DEIGEN_USE_VML" //tensorflow/tools/pip_package:build_pip_package
but when train with tensorflow still getting this warnning: not compiled to use: AVX512F

**Comment by yourfriend-gaurav-gurjar** [comment]
`

>>> device_name = tf.test.gpu_device_name() 2020-05-16 23:45:25.485785: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA >>> if not device_name: ...   raise SystemError('GPU device not found') ... print('Found GPU at: {}'.format(device_name)) SystemError: GPU device not found Found GPU at:
--
 
>>> | >>>
>>>

`

Hi..! I am also facing this issue.

**Comment by mihaimaruseac** [comment]
Please open new issue, fill in template

**Comment by SarahLynnePu** [comment]
2020-05-28 11:16:19.791171: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-28 11:16:19.819834: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3599930000 Hz
2020-05-28 11:16:19.820503: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x467ba80 executing computations on platform Host. Devices:
2020-05-28 11:16:19.820524: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
tf.Tensor(736.5775, shape=(), dtype=float32)
