### ISSUE TITLE
tf.estimator rebuild graph at per training step

### ISSUE THREAD

**Issue by 777ki** [tensorflow/tensorflow#24826]
hello everyone:
    i'm working on reading source code of tf.estimator, I found a little problem of this implementation，

```python
  def _train_model_default(self, input_fn, hooks, saving_listeners):
    """Initiate training with `input_fn`, without `DistributionStrategies`.
    Args:
      input_fn: A function that provides input data for training as minibatches.
      hooks: List of `tf.train.SessionRunHook` subclass instances. Used for
        callbacks inside the training loop.
      saving_listeners: list of `tf.train.CheckpointSaverListener` objects. Used
        for callbacks that run immediately before or after checkpoint savings.

    Returns:
      Loss from training
    """
    worker_hooks = []
    with ops.Graph().as_default() as g, g.device(self._device_fn):
      random_seed.set_random_seed(self._config.tf_random_seed)
      global_step_tensor = self._create_and_assert_global_step(g)

      # Skip creating a read variable if _create_and_assert_global_step
      # returns None (e.g. tf.contrib.estimator.SavedModelEstimator).
      if global_step_tensor is not None:
        training_util._get_or_create_global_step_read(g)  # pylint: disable=protected-access
      
      features, labels, input_hooks = (
          self._get_features_and_labels_from_input_fn(
              input_fn, model_fn_lib.ModeKeys.TRAIN))
      worker_hooks.extend(input_hooks)
    
      estimator_spec = self._call_model_fn(
          features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
      global_step_tensor = training_util.get_global_step(g)
      return self._train_with_estimator_spec(estimator_spec, worker_hooks,
                                             hooks, global_step_tensor,
                                             saving_listeners)
```
 this code is part of Estimator.training, look at this
```python
 estimator_spec = self._call_model_fn(
          features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
```
it will be called at every training step, that is a build graph operation, i think is called one time at the begining is better, am I right?

**Comment by guptapriya** [comment]
The code you are referring to is called only once everytime you call `estimator.train` to build the graph, and not per training step. the loop over training steps is here:
https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/estimator.py#L1402

Also, stackoverflow might be a better place for a clarification question like this unless you have seen this is actually a bug in practice.

**Comment by 777ki** [comment]
> The code you are referring to is called only once everytime you call `estimator.train` to build the graph, and not per training step. the loop over training steps is here:
> https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/estimator.py#L1402
> 
> Also, stackoverflow might be a better place for a clarification question like this unless you have seen this is actually a bug in practice.

but, this function is called after :  
    estimator_spec = self._call_model_fn(
that  _call_model_fn is  up on  _train_with_estimator_spec fucntion:
https://github.com/tensorflow/estimator/blob/781389ebd8dc87c71711f432e2eae135917429bd/tensorflow_estimator/python/estimator/estimator.py#L1154

so, every estimator.train will call both _call_model_fn and _train_with_estimator_spec at per training step

**Comment by 777ki** [comment]
so, i suggest that : move _call_model_fn to initialize function to build graph, if it still in train function yet, that way  may be  like "copy on write " or "init on first start", but, may be someone like me , we think that train function it can be called in dynamic（dynamic means i can change my input function in every train step， i will call train function for several times)
