### ISSUE TITLE
tensorflow.keras.backend.clip has different semantics than keras.backend.clip.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [tensorflow/tensorflow#24827]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):

TF built from master.

- Are you willing to contribute it (Yes/No):

No

**Describe the feature and the current behavior/state.**

Currently `tensorflow.keras.backend.clip` takes a tensor and two floating point python values for min and max. But a recent PR in keras-team/keras allowed now to pass three tensors for elementwise clipping. The PR I'm talking about is https://github.com/keras-team/keras/pull/11442 . If tensorflow.keras wants to stay compatible with the keras API, this feature should be implemented in `tensorflow.keras`

**Will this change the current api? How?**

No change to the API.

**Who will benefit with this feature?**

All people currently using keras contrib. I need tensorflow.keras API to be entirely compatible with keras-team/keras to avoid using two codebases to support keras and tf.keras. Some layers use this clipping feature and don't work when I change the imports to tf.keras.

**Any Other info.**

**Comment by dynamicwebpaige** [comment]
Gabriel is right: the semantics for `backend.py` in stand-alone Keras support floats, integers, and tensors, while tf.keras [only supports floats and ints](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/backend.py#L2311-L2329).

This would just need a copy / paste of the changes in [`tensorflow_backend.py` and `backend_test.py`](https://github.com/keras-team/keras/pull/11442/files), correct?

**Comment by gabrieldemarmiesse** [comment]
I believe that this issue is fixed.
