### ISSUE TITLE
tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by rpsg35** [tensorflow/tensorflow#24821]
I am  trying to install  tensorflow after activating conda environment using pip
$ conda activate /home/eartaert/anaconda3/
$ pip install --upgrade /home/eartaert/Downloads/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl

 but the following error is coming 

tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.
 

uname -a results are as follows 
Linux ubuntu 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

can anyone help please

**Comment by jvishnuvardhan** [comment]
@rpsg35 Could you follow the instructions [1](https://www.anaconda.com/blog/developer-blog/tensorflow-in-anaconda/), [2](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-tensorflow-on-ubuntu-16-04), and [3](https://towardsdatascience.com/tensorflow-gpu-installation-made-easy-use-conda-instead-of-pip-52e5249374bc). Please let us know how it progresses? Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
