### ISSUE TITLE
tf.contrib.integrate.odeint can only accept time points in increasing order

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#24823]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

currently, tensorflow support odeint function. but it only supports input time points in ascending order. This restriction make solving back propagation of ODENet(https://arxiv.org/abs/1806.07366) impossible. ODENet requires giving initial condition at latter time point and integrate to get the function value of an earlier time point. besides, odeint function of scipy supports input time points given in any order.

**Will this change the current api? How?**

this change would not change the current api. it just loose the restriction to the input time points.

**Who will benefit with this feature?**

researcher who is doing researches with ODENet will be happy to see it.

**Any Other info.**

**Comment by L0drik** [comment]
I would love to see this change implemented as well.

In the meantime, would it be possible to allow backward in time integration for ODEs by simply remove the '_assert_increasing(t)' function in 'tensorflow/tensorflow/contrib/integrate/python/ops/odes.py'? As far as I can tell, this seems to be an unnecessary conditions check (please correct me if I'm wrong). 

**Porposal:**
Remove this code block on line 275, and its calls on line 389, 695 in tensorflow/tensorflow/contrib/integrate/python/ops/odes.py:

    def _assert_increasing(t): 
        assert_increasing = control_flow_ops.Assert(
        math_ops.reduce_all(t[1:] > t[:-1]), ['`t` must be monotonic increasing'])
        return ops.control_dependencies([assert_increasing])

**Comment by richardwth** [comment]
Given the operations in current ODENet do not depend on the specific value of t, you could simply integrate `-ode_func` (negative derivative) with increasing time to solve ODE back in time.

**Comment by breadbread1984** [comment]
OK thx, by the way. by the way, do you know where odeint is in tf2.0?

**Comment by richardwth** [comment]
According to [this blog](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md), odeint is going to be moved to tensorflow/scientific, but I have not found the API documentation for this yet. Guess we'll have to wait.

**Comment by breadbread1984** [comment]
thx

**Comment by shoyer** [comment]
We have a BDF solver in TF-probability now. If anyone is interested in porting over the RK45 solver from tf.contrib.integrate to TF probability, that would be very welcome.

**Comment by rmothukuru** [comment]
@breadbread1984,
Can you please let us know if [tfp.math.ode.Solver](https://www.tensorflow.org/probability/api_docs/python/tfp/math/ode/Solver) is the API that you are looking for? Thanks!
