### ISSUE TITLE
Tensor board installing issue with docker

### ISSUE THREAD

**Issue by newbornking999** [tensorflow/tensorflow#2482]
Hi I'm a new tensor flow installer~
I do not have any experienced with docker or tensor flow and i followed this web-cite 

http://www.netinstructions.com/how-to-install-and-run-tensorflow-on-a-windows-pc/

https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#requirements

![1](https://cloud.githubusercontent.com/assets/19249239/15487824/30c4a332-218b-11e6-8017-6b51cc276439.PNG)

[this screen stopped after showing this image]

![2](https://cloud.githubusercontent.com/assets/19249239/15487829/398ded3e-218b-11e6-8ac8-3bb39792301a.PNG)

[I do not know what they are doing in actual cmd line but it does not work]

Those are the stops I got stock.  can anyone help?

**Comment by vrv** [comment]
After running `docker run -it ...`, it says the Jupyter notebook server is running at http://[your ip]:8888

If you navigate to that address, you should be able to get things running.  Please comment if that's not the case.

**Comment by newbornking999** [comment]
hey #vrv thanks for your comment. I'm new to this so not quite followed what you are saying. 
can you tell me more about your solution?

**Comment by vrv** [comment]
in your terminal, run

`docker run -it gcr.io/tensorflow/tensorflow`

Once that finishes, in your browser go to http://0.0.0.0:8888

**Comment by vrv** [comment]
In addition, you might get more help on StackOverflow, this is only for bug reports and feature requests.

**Comment by newbornking999** [comment]
um.. i can not connect too  http://0.0.0.0:8888

**Comment by vrv** [comment]
Alright, then I'm not really sure -- try asking on StackOverflow and you should get some better advice.

**Comment by tinar9678** [comment]
I also have the same problem. Did you, @newbornking999 ever figure it out?

**Comment by newbornking999** [comment]
I upgraded every version of my mac-os then problem solved
try to upgrade every mac-os

2016-07-07 7:46 GMT+09:00 Tina Ryu <notifications@github.com>:
