### ISSUE TITLE
TfLiteCameraDemo performance of NNAPI on Honor10 View (Kirin 970)

### ISSUE THREAD

**Issue by rafalfirlejczyk** [tensorflow/tensorflow#24830]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO.
I used the TF code from the TFLiteCameraDemo example. Only modified the line 47 in interpreter.cc where I set UseNNAPI(true);
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Honor 10 View (with Kirin970 and NPU)
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): tf: 1.5.0
- Python version: 2.7.15rc1
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): GCC 7.3.0
- CUDA/cuDNN version: None
- GPU model and memory: None

I compiled the demo app twice using two different bazel commands:

case 1. bazel build -c opt --cxxopt='--std=c++11' \
  //tensorflow/lite/java/demo/app/src/main:TfLiteCameraDemo

case 2. bazel build --cxxopt=--std=c++11 //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo --config=android_arm64 --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a

**Describe the current behavior**
I was switching in the app between CPU and NNAPI and checked the execution time.
In case 1 the CPU was faster then NNAPI
In case 2 both CPU and NNAPI gave approximately the same execution time. No real difference in was seen. 

**Describe the expected behavior**
Expected behavior is that the NNAPI time should be much shorter than CPU

**Comment by rafalfirlejczyk** [comment]
My Honor 10 View has Android 9.0.

**Comment by rafalfirlejczyk** [comment]
**No difference.** In both cases CPU and NNAPI, the timings are similar - between 300ms and 400ms - when set to mobilenet V1 floating point model. 
**Does it mean: NO driver available?**  
Setting the model to quantize makes the inference faster for both CPU and floating point case. In both cases I got between 50ms and 150ms. 
**Is setting UseNNAPI(true) needed to activate the driver?**
I set it to **true** before compiling with bazel but I did not see any timing difference with setting to **false**. 
**How to fix it?** 
**Where can I check if Kirin supports the NNAPI?**

**Comment by rafalfirlejczyk** [comment]
According to this source:
**https://www.xda-developers.com/honor-view-10-mini-review/**
Kirin 970 should have the driver and NNAPI support:

_Beyond the dedicated Kirin AI API, the NPU can be accessed through Android’s Neural Networks API (NNAPI), and it supports many popular machine learning platforms such as Facebook’s Caffe2 and Google’s TensorFlow and TensorFlow Lite. In other words, apps with AI-powered features can make the most of the View 10’s hardware._

**Comment by freedomtan** [comment]
As far as I know, there is no standard way to check if there are NN HAL drivers and if they are configured properly. Enable NNAPI debugging may be helpful:
```
> adb shell setprop debug.nn.vlog 1
```
then you can check message with `adb logcat`

**Comment by rafalfirlejczyk** [comment]
thank you.
I followed your advice. Attached is the logcat log.
Here are some filtered lines. You can see a possible problem:
**Device ipuadaptor can't do operation CONV_2D**

[honor10view-nnapi-logcat.txt](https://github.com/tensorflow/tensorflow/files/2749187/honor10view-nnapi-logcat.txt)


01-11 10:50:09.006 26033 28849 I TfLiteCameraDemo: Changing model to mobilenet v1 float device NNAPI
01-11 10:50:09.009 26033 28849 D TfLiteCameraDemo: Created a Tensorflow Lite Image Classifier.
01-11 10:50:09.031 26033 28849 D TfLiteCameraDemo: Timecost to put values into ByteBuffer: 11
01-11 10:50:09.031 26033 28849 I ModelBuilder: setOperandValue for operand 0 size 3456
01-11 10:50:09.031 26033 28849 I ModelBuilder: Saving large value
01-11 10:50:09.031 26033 28849 I ModelBuilder: setOperandValue for operand 1 size 18432
01-11 10:50:09.031 26033 28849 I ModelBuilder: Saving large value
01-11 10:50:09.031 26033 28849 I ModelBuilder: setOperandValue for operand 2 size 1048576
01-11 10:50:09.031 26033 28849 I ModelBuilder: Saving large value
..
..
..
01-11 10:50:09.065   740 13436 I aiserver: IPUNNAdaptor getSupportedOperations_1_1
01-11 10:50:09.065   740 13436 I aiserver: AiModelMngrService getSupportedOperations_1_1
01-11 10:50:09.066   740 13436 E aiserver: AiModelMngrServic::getSupportedOperations_1_1 not relaxed Model.
01-11 10:50:09.066 26033 28849 I ExecutionPlan: Device ipuadaptor can't do operation CONV_2D
01-11 10:50:09.066 26033 28849 I ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(CONV_2D) = 1
01-11 10:50:09.066 26033 28849 I ExecutionPlan: Device ipuadaptor can't do operation DEPTHWISE_CONV_2D
01-11 10:50:09.066 26033 28849 I ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(DEPTHWISE_CONV_2D) = 1
01-11 10:50:09.066 26033 28849 I ExecutionPlan: Device ipuadaptor can't do operation CONV_2D
01-11 10:50:09.066 26033 28849 I ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(CONV_2D) = 1
01-11 10:50:09.066 26033 28849 I ExecutionPlan: Device ipuadaptor can't do operation DEPTHWISE_CONV_2D
01-11 10:50:09.066 26033 28849 I ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(DEPTHWISE_CONV_2D) = 1
01-11 10:50:09.066 26033 28849 I ExecutionPlan: Device ipuadaptor can't do operation CONV_2D
01-11 10:50:09.066 26033 28849 I ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(CONV_2D) = 1
01-11 10:50:09.066 26033 28849 I ExecutionPlan: Device ipuadaptor can't do operation DEPTHWISE_CONV_2D
01-11 10:50:09.066 26033 28849 I ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(DEPTHWISE_CONV_2D) = 1
01-11 10:50:09.066 26033 28849 I ExecutionPlan: Device ipuadaptor can't do operation CONV_2D
01-11 10:50:09.066 26033 28849 I ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(CONV_2D) = 1
01-11 10:50:09.066 26033 28849 I ExecutionPlan: Device ipuadaptor can't do operation DEPTHWISE_CONV_2D
01-11 10:50:09.066 26033 28849 I ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(DEPTHWISE_CONV_2D) = 1
..
..
01-11 10:50:09.243   719 28864 W Misc____: [288a640_64W] saveQRSeamlessInfo, getQRSeamlessMap fail!
01-11 10:50:09.245 26033 26033 D HwAppInnerBoostImpl: asyncReportData com.example.android.tflitecamerademo,2,1,2,0 interval=355
01-11 10:50:09.246   608  2767 E uniperf server: uniPerfEvent doParse failed, cmdId=4400
01-11 10:50:09.247   608  2767 D uniperf hal: do uniPerfEvent failed, cmdId=4400, ret=2
01-11 10:50:09.248   719 28866 I AntiBanding: rollBandingDetectAnalysis: return3.
01-11 10:50:09.248   719 28866 I AntiBanding: judgeContinueFrameDetect(): Into MainAnalysis_1 illegal case , algorithm returned !
..
..
01-11 10:50:09.495 26033 29078 I CpuExecutor: CpuExecutor::run() with request()
01-11 10:50:09.495 26033 29078 I CpuExecutor: CpuExecutor::initializeRunTimeInfo

**Comment by freedomtan** [comment]
That's interesting. `...can't do operation DEPTHWISE_CONV_2D` kinda makes sense to me ('cause the hardware may be designed before Mobilenet V1, so it doesn't support depthwise convolution. But `can't do operation CONV_2D` looks weird. You may want to try older well-known network, such as Inception V3 and SqueezeNet. Check [1] and [2] for some pretrained TFLite models.

[1] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models.md
[2] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/benchmarks.md

**Comment by miaout17** [comment]
@miaowang14 Could you help to comment on this issue?

**Comment by miaowang14** [comment]
I believe the key error msg is the following:
01-11 10:50:09.066 740 13436 E aiserver: AiModelMngrServic::getSupportedOperations_1_1 not relaxed Model.

The main reason is that currently the NPU in Honor 10 View can only accelerate models with relax precision computation (basically FP16 precision). The mobilenet model bundled in the demo is FP32, and by default FP32 models imply full precision FP32 calculation.

You could try enabling relaxed precision by calling Interpreter::SetAllowFp16PrecisionForFp32(true), and then call UseNNAPI(true): https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/interpreter.h#L338

**Comment by miaout17** [comment]
I think `Interpreter::SetAllowFp16PrecisionForFp32(true)` is the key solution. I'm closing the ticket as the question is answered. Please reopen if you have further questions.

**Comment by rafalfirlejczyk** [comment]
I changed  **interpeter.cc** in three places. Please verify if OK

**Line 48**:
for (int i = 0; i < kTfLiteMaxExternalContexts; ++i) {
    external_contexts_[i] = nullptr;
  }

  UseNNAPI(**true**);
}

**Line 150:**
void Interpreter::UseNNAPI(bool allow) { primary_subgraph().UseNNAPI(**true**); }

**Line 165:**
void Interpreter::SetAllowFp16PrecisionForFp32(bool allow); {
  for (auto& subgraph : subgraphs_) {
    subgraph->context()->allow_fp32_relax_to_fp16 = **true**;
  }
}

The changes did not help. NNAPI is not faster

**Comment by miaowang14** [comment]
Is it still showing "Device ipuadaptor can't do operation CONV_2D" with "adb shell setprop debug.nn.vlog 1"?

Just to make sure if the model is running on the NPU.

**Comment by freedomtan** [comment]
If you are not sure how to modify interpreter.cc, since `SetAllowFp16PrecisionForFp32()` is exported Java already, you may want to start from [ImageClassifier.java](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/ImageClassifier.java)

**Comment by bilalsoomro** [comment]
@rafalfirlejczyk Hi, did you find a solution for the slower inference time using NNAPI on that device?

**Comment by y-ich** [comment]
I recently bought MatePad Pro (Kirin 990) and tried [TensorFlow Lite image classification Android example application](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android).

Same as this issue, I observed that enabling NNAPI makes "Inference Time" larger.
At the same time, I observed that /vender/bin/hiaiserver is running even though selecting CPU on "Device", at which you can select one among CPU/GPU/NNAPI.

As /vender/bin/hiaiserver seems Huawei's NPU daemon, I think that NPU is already working even if you select CPU and enabling NNAPI prevents NPU from working for some reason.
