### ISSUE TITLE
[TF Java, Control Flow] Constant nodes created via TF_AddGradients are not in the correct frame

### ISSUE THREAD

**Issue by irenedea** [tensorflow/tensorflow#24837]
**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
We are using TF Java's `graph.addGradients` which calls upon c_api.h's `TF_AddGradients`. Currently the function works fine when called in the outermost frame (frame '')). 

However, we would like to call TF Java's `graph.addGradients` on nodes that are in the same while loop frame. This gives us the error:
```
[error] Exception in thread "main" java.lang.IllegalArgumentException: {{node Gradients/Multiply_1}} has inputs from different frames. The input {{node Gradients/Div_2}} is in frame ''. The input {{node Sub_1}} is in frame 'While'.
```
The issue here is that specifically constant nodes created for the gradient subgraph via `TF_AddGradients`  are not in the correct frame. (The error mentions Multiply and Div nodes because the incorrect frame of constant nodes propagates to those nodes.) Unlike other nodes (Multiply, Sub, Div...), constant nodes do *not* take inputs from other nodes and therefore will always be in the outermost frame (frame '') unless a control input is specified.

**Will this change the current api? How?**
Adding a control edge from a node (let's call this node a pivot) within the while loop frame (frame 'While') to each constant node created by TF_AddGradients to forces the constant node into the while loop frame and our graph will run without error. 

Support for this can be added within the `TF_AddGradients` function.

There is already a loop in the function that does a sanity check on each node. Some simple logic can be added to add a control edge from each newly created constant node to a pivot.

The pivot can be chosen as one of the given inputs to `TF_AddGradients`. This way we ensure that all nodes in the subgraph are in the same frame as the inputs. (Inputs to `TF_AddGradients` must be in the same frame.)

**Who will benefit with this feature?**
Those who want greater usability/flexibility in addGradients will benefit as this will allow addGradients to be called in frames other than the outermost.

**Any Other info.**

Here is a hack-y solution that assumes the pivot is the node created immediately before `TF_AddGradients` is called (rather than using one of the inputs as the pivot).

In `c_api.cc/TF_AddGradients`:
```
...
    // Assumes the pivot is the node created immediately before the gradient nodes.
    // TODO: Use input as pivot.
    Node* pivot = g->graph.FindNodeId(first_new_node_id - 1);

    for (int i = first_new_node_id; i < g->graph.num_node_ids(); ++i) {
      Node* n = g->graph.FindNodeId(i);
      if (n == nullptr) continue;

      // Add control edge from each newly created constant node to the pivot to force
      // the nodes to be in the same frame as pivot.
      if (n->IsConstant()) {
        g->graph.AddControlEdge(pivot, n);
      }
...
```

**Comment by irenedea** [comment]
@melissagrueter @samdow

**Comment by irenedea** [comment]
PR here: https://github.com/tensorflow/tensorflow/pull/24842

**Comment by ymodak** [comment]
PR #25949
