### ISSUE TITLE
I got a problem with Tensorflow installation mac

### ISSUE THREAD

**Issue by newbornking999** [tensorflow/tensorflow#2483]
https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#on-macosx

I followed the all instructions for mac installation
![screen shot 2016-05-24 at 8 49 07 am](https://cloud.githubusercontent.com/assets/19249239/15487984/a0fe6182-218c-11e6-9f75-2697ff446ac5.png)

After I typed "import tensorflow as tf" this shows some error but no idea what those lines mean..

Need help

**Comment by vrv** [comment]
I would step-by-step copy paste the instructions, since you've typed the installation instructions incorrectly.  Please comment further if you have evidence that our existing instructions are not enough.
