### ISSUE TITLE
Bazel build failed building Android demo

### ISSUE THREAD

**Issue by tferrerITBA** [tensorflow/tensorflow#24836]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.12.0
- Python version: 2.7.12
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 0.19.0
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Running the following command:

```
bazel build --cxxopt='--std=c++11' -c opt //tensorflow/examples/android:tensorflow_demo --verbose_failures
```

causes the following build errors:
```
INFO: From ProtoCompile tensorflow/core/example/example.pb.cc:
bazel-out/android-armeabi-v7a-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
bazel-out/android-armeabi-v7a-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
ERROR: /home/glorenz/.cache/bazel/_bazel_glorenz/701fde1b3ff5c4a449c0c2cab4570a97/external/com_google_absl/absl/base/BUILD.bazel:29:1: C++ compilation of rule '@com_google_absl//absl/base:spinlock_wait' failed (Exit 1): clang failed: error executing command 
  (cd /home/glorenz/.cache/bazel/_bazel_glorenz/701fde1b3ff5c4a449c0c2cab4570a97/execroot/org_tensorflow && \
  exec env - \
    ANDROID_BUILD_TOOLS_VERSION=28.0.3 \
    ANDROID_NDK_API_LEVEL=14 \
    ANDROID_NDK_HOME=/home/glorenz/Android/Sdk/ndk-bundle \
    ANDROID_SDK_API_LEVEL=23 \
    ANDROID_SDK_HOME=/home/glorenz/Android/Sdk \
    PATH=/home/glorenz/Workspace/cat-local/cat_test_1/bin:/home/glorenz/bin:/home/glorenz/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/glorenz/.dotnet/tools:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/lib/python2.7/dist-packages \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=0 \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/android-armeabi-v7a-opt/bin/external/com_google_absl/absl/base/_objs/spinlock_wait/spinlock_wait.d '-frandom-seed=bazel-out/android-armeabi-v7a-opt/bin/external/com_google_absl/absl/base/_objs/spinlock_wait/spinlock_wait.o' -iquote external/com_google_absl -iquote bazel-out/android-armeabi-v7a-opt/genfiles/external/com_google_absl -iquote bazel-out/android-armeabi-v7a-opt/bin/external/com_google_absl -iquote external/bazel_tools -iquote bazel-out/android-armeabi-v7a-opt/genfiles/external/bazel_tools -iquote bazel-out/android-armeabi-v7a-opt/bin/external/bazel_tools '--std=c++11' -Wall -Wextra -Wcast-qual -Wconversion-null -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wunused-local-typedefs -Wunused-result -Wvarargs -Wvla -Wwrite-strings -Wno-sign-compare '--sysroot=external/androidndk/ndk/platforms/android-14/arch-arm' -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -c external/com_google_absl/absl/base/internal/spinlock_wait.cc -o bazel-out/android-armeabi-v7a-opt/bin/external/com_google_absl/absl/base/_objs/spinlock_wait/spinlock_wait.o)
In file included from external/com_google_absl/absl/base/internal/spinlock_wait.cc:27:
In file included from external/com_google_absl/absl/base/internal/spinlock_linux.inc:17:
external/androidndk/ndk/platforms/android-14/arch-arm/usr/include/linux/futex.h:28:21: error: field has incomplete type 'struct robust_list'
 struct robust_list __user *next;
                    ^
external/androidndk/ndk/platforms/android-14/arch-arm/usr/include/linux/futex.h:27:8: note: definition of 'robust_list' is not complete until the closing '}'
struct robust_list {
       ^
external/androidndk/ndk/platforms/android-14/arch-arm/usr/include/linux/futex.h:28:27: error: expected ';' at end of declaration list
 struct robust_list __user *next;
                          ^
external/androidndk/ndk/platforms/android-14/arch-arm/usr/include/linux/futex.h:37:27: error: expected ';' at end of declaration list
 struct robust_list __user *list_op_pending;
                          ^
3 errors generated.
Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 176.016s, Critical Path: 25.68s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 340 processes: 328 local, 12 worker.
FAILED: Build did NOT complete successfully
```
This happens when using the most recent commit (with the hashcode `3c4b35297e4b44baaf4cc7ed5b099c586ffa049b`).
However, the build suceeds if the cloned repository is hard reset to the commit with the following hashcode:
`30ebb9b712b2008525944deb47dee8b653f522a3`.
This also happened with bazel 0.21.0, which is the latest version to date.

**Full Log**
[stack.txt](https://github.com/tensorflow/tensorflow/files/2746756/stack.txt)

**Comment by jvishnuvardhan** [comment]
@tferrerITBA Your issue looks similar to the following [1](https://github.com/tensorflow/tensorflow/issues/23673), [2](https://github.com/tensorflow/tensorflow/issues/24841), and [3](https://github.com/tensorflow/tensorflow/issues/24905). Could you follow the solutions in those posts and let us know how it progresses? Thanks!

**Comment by tferrerITBA** [comment]
@jvishnuvardhan the issues mentioned above are different (I did try their solutions, however). In [1](https://github.com/tensorflow/tensorflow/issues/23673) and [2](https://github.com/tensorflow/tensorflow/issues/24841), one of the solutions is to install `libc-ares-dev`, which I did (even though my `.bazelrc` file contains the line `build --define=grpc_no_ares=true`). Nothing changed. The other solution was to add the line `import tools/bazel.rc` but there is no such file in the `master` branch of tensorflow (the one I work on). Instead, I noticed most of the contents of another user's `bazel.rc` are already included in `.bazelrc`. And the bazel version is unlikely to be the problem, as both 0.19.x and 0.21.0 failed to build.
I tried everything in another Ubuntu 16.04 installation but it didn't help. It may be useful to know that `which gcc` returns `/usr/bin/gcc`.

**Comment by case540** [comment]
Dont think im the correct person to assign this to. Not hugely familiar with the android build. Maybe petewarden@

**Comment by kskawinski** [comment]
I have exactly the same issue.

**Comment by kskawinski** [comment]
I found the solution for the building. Follow this: https://github.com/tensorflow/tensorflow/issues/20192

**Comment by jvishnuvardhan** [comment]
@tferrerITBA 
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken.

**Comment by tferrerITBA** [comment]
> I found the solution for the building. Follow this: #20192

Perfect! Changing the line `build --action_env ANDROID_NDK_API_LEVEL="21"` in the file `.tf_configure.bazelrc` worked like a charm. Thanks!

**Comment by NorwayLobster** [comment]
sorry, my friend, i am not familiar with this bazel and Android, where is the .tf_configure.bazelrc file?? i do not find it. plz. thank you very much

**Comment by NorwayLobster** [comment]
@tferrerITBA plz

**Comment by tferrerITBA** [comment]
It most likely depends on how you configured tensorflow in the first place. In the `.bazelrc` file you can see the line `try-import %workspace%/.tf_configure.bazelrc`. I think you are asked to set your workspace's directory after running `./configure`.
