### ISSUE TITLE
Windows 10/Anaconda3: Missing File on install

### ISSUE THREAD

**Issue by ehennis** [tensorflow/tensorflow#24835]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Installed from pip
- TensorFlow version: 2 Preview
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**
I created a virtual environment and tried to install the preview that Martin Wicke suggested on twitter. It failed with a missing file.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Commands from Anaconda3 prompt:
conda create -n tf_daily python=3.6
activate tf_daily
pip install tf-nightly-2.0-preview

Error Message:
(tf_daily) C:\Users\nurl_>pip install tf-nightly-2.0-preview
Collecting tf-nightly-2.0-preview
  Using cached https://files.pythonhosted.org/packages/a6/d9/0499db98422207eb3d7643ee3b8152dd503a85dc2f958f77834aa0a3fcde/tf_nightly_2.0_preview-1.13.0.dev20190108-cp36-cp36m-win_amd64.whl
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\nurl_\\AppData\\Local\\Temp\\pip-install-r8cg1kry\\tf-nightly-2.0-preview\\tf_nightly_2.0_preview-1.13.0.dev20190108.data/purelib/tensorflow/include/tensorflow/include/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorSyclConvertToDeviceExpression.h'

**Comment by martinwicke** [comment]
Anna, do you know what could be wrong here?

**Comment by ehennis** [comment]
I didn't have that option in the group policy section but I was able to update using the registry (https://www.itprotoday.com/windows-10/enable-long-file-name-support-windows-10). After a reboot I was able to install.

Somewhat related, I have a similar issue with Windows limits with a jupyter notebook using a virtual environment. The shortcut path is too long and it crashes. Go Windows.

**Comment by wangzhe258369** [comment]
1. Hit the Windows key, type `gpedit.msc` and press Enter.
2. Navigate to `Local Computer Policy > Computer Configuration > Administrative Templates > System > Filesystem`.
3. Double click the `Enable Win32 long paths` option and enable it.

ref: https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing

**Comment by ehennis** [comment]
@wangzhe258369 I did have the setting at that location. I was down in the NTFS section looking earlier.

**Comment by datomnurdin** [comment]
How about Mac?
