### ISSUE TITLE
tf-nightly-2.0-preview failed to install on my Windows 7/64

### ISSUE THREAD

**Issue by rafalfirlejczyk** [tensorflow/tensorflow#24834]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7/64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 2.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rafalfirlejczyk** [comment]
pip install tf-nightly-2.0-preview does not install on my Windows 7/64


Collecting tf-nightly-2.0-preview
  Using cached https://files.pythonhosted.org/packages/a6/d9/0499db98422207eb3d7643ee3b8152dd503a85dc2f958f77834aa0a3fcde/tf_nightly_2.0_pre
view-1.13.0.dev20190108-cp36-cp36m-win_amd64.whl
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\brm738\\AppData\\Local\\Temp\\pip-in
stall-ku5u1ik5\\tf-nightly-2.0-preview\\tf_nightly_2.0_preview-1.13.0.dev20190108.data/purelib/tensorflow/include/tensorflow/include/externa
l/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorSyclConvertToDeviceExpression.h'

**Comment by rafalfirlejczyk** [comment]
Thank you ymodak.
I installed the vitualenv via pip install and followed your instruction adopting it to the Windows, (yours is for Linux).
My python is mapped to python3.
**virtualenv -p python venv-tf-nightly-2.0
venv-tf-nightly-2.0\Scripts\activate
pip3 install tf-nightly-2.0-preview**

Still get the same environment error:

**(venv-tf-nightly-2.0) C:\Users\brm738>pip3 install tf-nightly-2.0-preview**
Collecting tf-nightly-2.0-preview
  Using cached https://files.pythonhosted.org/packages/5d/ac/238d28669c12d5cac587863ac16fd022b7692049c906be6c4986e64dfb87/tf_nightly_2.0_preview-1.13.0.dev20190110-cp36-cp36m-win_amd64.whl
**Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\brm738\\AppData\\Local\\Temp\\pip-install-yrga1ect\\tf-nightly-2.0-preview\\tf_nightly_2.0_preview-1.13.0.dev20190110.data/purelib/tensorflow/include/tensorflow/include/external/eigen_archive/unsupp orted/Eigen/CXX11/src/Tensor/TensorSyclConvertToDeviceExpression.h'**

**Comment by ymodak** [comment]
Thanks for the information. This issue is likely due to limitation of path length on windows. See a duplicate issue #24835

**Comment by rafalfirlejczyk** [comment]
Not possible to get rid of path length limitation on Windows 7. I have to upgrade to Windows 10

**Comment by ymodak** [comment]
I will close this issue since upgrading your OS can help fix it. Please feel free to reopen if have any further problems. Thanks!

**Comment by lkabongoCS** [comment]
For those who can't upgrade their OS (company policies, ...) and still want to access nightly previews (issue has been solved in alpha version `pip install tensorflow==2.0.0-alpha0`):
- Download the latest wheel matching their configuration from pypi:
-- GPU version here; https://pypi.org/project/tf-nightly-gpu-2.0-preview/#history 
-- CPU version here: https://pypi.org/project/tf-nightly-2.0-preview/#history
- Open the whl with a zip application (like 7-zip)
- Edit the 2 folders names at root level of the archive to remove both the "_preview" and "dev2019XXXX." string in their names
- Extract the RECORD file in the root subfolder ending in .dist-info
- Edit the extracted RECORD file and remove all "_preview" and "dev2019XXXX." strings
- Put the modified RECORD file back into the archive
- Install the wheel with pip using command `pip install <path_to_modified.whl>`

**Comment by dorian821** [comment]
@IkabongoCS thanks for the update and the workaround. After following your instructions, however, I keep running into a directory error:

```
C:\Users\asus>pip install "C:\Users\asus\Downloads\tf_nightly_gpu_2.0_preview-2.0.0.dev20190327-cp36-cp36m-win_amd64.whl"
Processing c:\users\asus\downloads\tf_nightly_gpu_2.0_preview-2.0.0.dev20190327-cp36-cp36m-win_amd64.whl
Requirement already satisfied: protobuf>=3.6.1 in c:\users\asus\anaconda3\lib\site-packages (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (3.6.1)
Requirement already satisfied: six>=1.10.0 in c:\users\asus\anaconda3\lib\site-packages (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (1.10.0)
Requirement already satisfied: google-pasta>=0.1.2 in c:\users\asus\anaconda3\lib\site-packages (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (0.1.4)
Requirement already satisfied: numpy<2.0,>=1.14.5 in c:\users\asus\anaconda3\lib\site-packages (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (1.15.4)
Requirement already satisfied: tb-nightly<1.15.0a0,>=1.14.0a0 in c:\users\asus\anaconda3\lib\site-packages (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (1.14.0a20190301)
Requirement already satisfied: keras-applications>=1.0.6 in c:\users\asus\appdata\roaming\python\python36\site-packages (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (1.0.6)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\asus\anaconda3\lib\site-packages (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (1.1.0)
Collecting tensorflow-estimator-2.0-preview (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327)
  Downloading https://files.pythonhosted.org/packages/ed/d2/7d9931a45b1085c5f74132fd6178982fc8481ee10e2016a7973696da0c92/tensorflow_estimator_2.0_preview-1.14.0.dev2019040100-py2.py3-none-any.whl (352kB)
    100% |████████████████████████████████| 358kB 1.2MB/s
Requirement already satisfied: grpcio>=1.8.6 in c:\users\asus\anaconda3\lib\site-packages (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (1.16.1)
Requirement already satisfied: astor>=0.6.0 in c:\users\asus\anaconda3\lib\site-packages (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (0.7.1)
Requirement already satisfied: absl-py>=0.7.0 in c:\users\asus\anaconda3\lib\site-packages (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (0.7.1)
Requirement already satisfied: gast>=0.2.0 in c:\users\asus\anaconda3\lib\site-packages (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (0.2.2)
Requirement already satisfied: wheel>=0.26 in c:\users\asus\anaconda3\lib\site-packages (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (0.29.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in c:\users\asus\appdata\roaming\python\python36\site-packages (from tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (1.0.5)
Requirement already satisfied: setuptools in c:\users\asus\appdata\roaming\python\python36\site-packages (from protobuf>=3.6.1->tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (39.1.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\asus\anaconda3\lib\site-packages (from tb-nightly<1.15.0a0,>=1.14.0a0->tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (3.0.1)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\asus\anaconda3\lib\site-packages (from tb-nightly<1.15.0a0,>=1.14.0a0->tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (0.12.2)
Requirement already satisfied: h5py in c:\users\asus\anaconda3\lib\site-packages (from keras-applications>=1.0.6->tf-nightly-gpu-2.0-preview==2.0.0.dev20190327) (2.8.0)
Installing collected packages: tensorflow-estimator-2.0-preview, tf-nightly-gpu-2.0-preview
Exception:
Traceback (most recent call last):
  File "c:\users\asus\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 179, in main
    status = self.run(options, args)
  File "c:\users\asus\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "c:\users\asus\anaconda3\lib\site-packages\pip\_internal\req\__init__.py", line 57, in install_given_reqs
    **kwargs
  File "c:\users\asus\anaconda3\lib\site-packages\pip\_internal\req\req_install.py", line 913, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "c:\users\asus\anaconda3\lib\site-packages\pip\_internal\req\req_install.py", line 445, in move_wheel_files
    warn_script_location=warn_script_location,
  File "c:\users\asus\anaconda3\lib\site-packages\pip\_internal\wheel.py", line 428, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: tf-nightly-gpu-2.0-preview==2.0.0.dev20190327 .dist-info directory not found

C:\Users\asus>pip install "C:\Users\asus\Downloads\tf_nightly_gpu_2.0-cp36-cp36m-win_amd64.whl"
tf_nightly_gpu_2.0-cp36-cp36m-win_amd64.whl is not a valid wheel filename.

C:\Users\asus>pip install "C:\Users\asus\Downloads\tf_nightly_gpu_2.0-cp36-cp36m-win_amd64.whl"
tf_nightly_gpu_2.0-cp36-cp36m-win_amd64.whl is not a valid wheel filename.

C:\Users\asus>cd Downloads

C:\Users\asus\Downloads>pip install tf_nightly_gpu_2.0-cp36-cp36m-win_amd64.whl
tf_nightly_gpu_2.0-cp36-cp36m-win_amd64.whl is not a valid wheel filename.

C:\Users\asus\Downloads>pip install tf_nightly_gpu_2.0.whl6
Collecting tf_nightly_gpu_2.0.whl6
  Could not find a version that satisfies the requirement tf_nightly_gpu_2.0.whl6 (from versions: )
No matching distribution found for tf_nightly_gpu_2.0.whl6

C:\Users\asus\Downloads>pip install tf_nightly_gpu_2.0.whl
tf_nightly_gpu_2.0.whl is not a valid wheel filename.
```

**Comment by aaron-maslim** [comment]
Hi @dorian821 , to fix that issue is that you may not rename the .dist-info inside the wheel and also you may not rename the wheel filename. So the places to remove "_preview" and "dev2019XXXX" is the folder (not .dist-info) and the RECORD file.

**Comment by dorian821** [comment]
Hi @aaron-maslim, :+1: thanks a lot! it install just fine!

**Comment by aaron-maslim** [comment]
Great to hear that!

**Comment by RadEdje** [comment]
> Hi @dorian821 , to fix that issue is that you may not rename the .dist-info inside the wheel and also you may not rename the wheel filename. So the places to remove "_preview" and "dev2019XXXX" is the folder (not .dist-info) and the RECORD file. I am in Windows 7 as well btw.

Hi, I did as instructed, 
i only renamed the folders
and then edited the RECORD file without changing the file name..
i'm still getting the error that the file name is still too long


```
Could not install packages due to an EnvironmentError: [WinError 206] The filename or extension is too long: 'C:\\Users\\-----------------\\AppData\\Local\\Temp\\pip-install-s_wy_wb_\\tf-nightly-2.0-preview\\tf_nightly_2.0_preview-2.0.0.dev20190411-cp36-cp36m-win_amd64/tf_nightly_2.0-2.0.0.data/purelib/tensorflow/include/external/absl_py/absl/third_party/unittest3_backport/
```

any other suggestions?
thanks

**Comment by dorian821** [comment]
@RadEdje Hi, I resolved this problem by _only_ renaming the _data_ folder and the file paths in the RECORD file. That is, I left the dist-info folder as it is, unchanged.

**Comment by lkabongoCS** [comment]
I would suggest also renaming the wheel file to make it shorter (only remove `"_preview" and "dev2019XXXX."`), without removing other essential information ([https://stackoverflow.com/questions/33213430/whl-is-not-a-valid-wheel-filename-storing-debug-log-for-failure-in-c](url)).

**Comment by RadEdje** [comment]
> @RadEdje Hi, I resolved this problem by _only_ renaming the _data_ folder and the file paths in the RECORD file. That is, I left the dist-info folder as it is, unchanged.
> 
> In your response, you mention that you renamed the folder**s**, but you should only rename one folder, the data folder.

Hi. thanks for the suggestion.
i tried just renaming the data folder.
same thing.
the file path name is still too long.


```
Could not install packages due to an EnvironmentError: [WinError 206] The filename or extension is too long: 'C:\\Users\\------------------------\\AppData\\Local\\Temp\\pip-install-v3dk57w_\\tf-nightly-2.0-preview\\tf_nightly_2.0_preview-2.0.0.dev20190411-cp36-cp36m-win_amd64/tf_nightly_2.0-2.0.0.data/purelib/tensorflow/include/external/absl_py/absl/third_party/unittest3_backport/'
```

Thanks for the help.
is there anything else i can remove to make the filepath shorter?
I'm on windows 8.1.
python 3.6
using 7zip
and Microsoft VS code to replace/remove all the instances of _preview and the dev numbers in the RECORD file.

**Comment by dorian821** [comment]
for clarity, what exactly have you renamed?

Also, since you're on windows 8, you should be able to extend the file path limit to 30k+ by changing the relevant key in the registry as discussed in the thread here: 

https://github.com/tensorflow/tensorflow/issues/24835

**Comment by RadEdje** [comment]
> for clarity, what exactly have you renamed?
> 
> Also, since you're on windows 8, you should be able to extend the file path limit to 30k+ by changing the relevant key in the registry as discussed in the thread here:
> 
> #24835

Oh... I thought that was only for windows 10.
I'll back read.

anyway here are the renamed folder (singular now as you suggested i only renamed the data folder):

```
tf_nightly_2.0-2.0.0.data
```

Using VS code I replaced/removed all of the instances of 
"_preview" and "dev2019XXXX." strings in the RECORD file but I did not change the file name.

when the
file path name is too long error is no longer seen. A new error shows up.
That's the error that says the 
that a file does not exist.
I think it's in the formatting...

note how the slashes change from

slash `/` to back slash `\\`

just my two cents.

Anyway i'll try to change the registry in windows 8.

**Comment by lkabongoCS** [comment]
I've just tested renaming (removed -preview and .devXXXX) the wheel file, entries in RECORD, the data folder and the dist-info folder, installation works for me.

**Comment by dorian821** [comment]
ok, great. thanks for clarifying. I had the same thought regarding the slash, but it won't be an issue once the wheel is set up properly. 

it looks like you might have grabbed a trailing period in the RECORD file, 

the paths should go from:

tf_nightly_2.0_preview-2.0.0.dev20190401.data/purelib/

to 

tf_nightly_gpu_2.0.data/purelib/

with a period separating 2.0 and data

check to make sure that this is the case.

**Comment by RadEdje** [comment]
> ok, great. thanks for clarifying. I had the same thought regarding the slash, but it won't be an issue once the wheel is set up properly.
> 
> it looks like you might have grabbed a trailing period in the RECORD file,
> 
> the paths should go from:
> 
> tf_nightly_2.0_preview-2.0.0.dev20190401.data/purelib/
> 
> to
> 
> tf_nightly_gpu_2.0.data/purelib/
> 
> with a period separating 2.0 and data
> 
> it looks like you took "dev2019XXXX." and so may have "tf_nightly_gpu_2.0data/purelib/", which is incorrect
> 
> check to make sure that this is the case.


Hi did as you asked, 

unfortuantely same error. the file does not exist:


```
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\----------------------\\AppData\\Local\\Temp\\pip-install-eluview2\\tf-nightly-2.0-preview\\tf_nightly_2.0_preview-2.0.0.dev20190411-cp36-cp36m-win_amd64/tf_nightly_2.0.data/purelib/tensorflow/include/external/com_google_absl/absl/base/internal/low_level_scheduling.h'

```

this is the untouched name of the whl file
```
tf_nightly_2.0_preview-2.0.0.dev20190411-cp36-cp36m-win_amd64.whl
```

here is the name of the DATA folder
```
tf_nightly_2.0.data
```

here is a sample of a string line in the RECORD file (RECORD FILE name also untouched)
this is also the file that's allegedly missing in the error log

```
tf_nightly_2.0.data/purelib/tensorflow/include/external/com_google_absl/absl/base/internal/low_level_scheduling.h,sha256=5x8MD_0rHwmOE3L-IeK-B4bbMU0yJtCNHHWzpOB3Zt0,3985

```

Any suggestions?

thanks again for your patience and help.

**Comment by lkabongoCS** [comment]
@RadEdje  It looks like you removed too many things:
- DATA folder, I have : tf_nightly_2.0-2.0.0.data
- RECORD sample, I have: tf_nightly_2.0-2.0.0.data/purelib/tensorflow/__init__.py,sha256=4cVbFxbZBU5CbfDK9gA9BVyoEcDwwrs93aZrX0pMASE,18489

**Comment by RadEdje** [comment]
@RadEdje It looks like you removed too many things:

DATA folder, I have : tf_nightly_2.0-2.0.0.data
RECORD sample, I have: tf_nightly_2.0-2.0.0.data/purelib/tensorflow/init.py,sha256=4cVbFxbZBU5CbfDK9gA9BVyoEcDwwrs93aZrX0pMASE,18489


Hi, that was my original format.
That did not work either.
:-(

**Comment by RadEdje** [comment]
just wanted to update.
i gave up on windows 8.1
dual booted with ubuntu.
Everything installed and worked flawlessly without a hitch on the linux machine just with the pip install commands. Never found out what I was doing wrong on windows though.
