### ISSUE TITLE
Different with keras.layers.Dropout and tensorflow.keras.layers.Dropout, rate argument

### ISSUE THREAD

**Issue by GzuPark** [tensorflow/tensorflow#24845]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12.0
- Python version: 3.6.2
- CUDA/cuDNN version: 9.0.176 
- GPU model and memory: NVIDIA 1060

* keras version
```python
from keras import layers
from keras import models

model = models.Sequential()
model.add(layers.Conv2D(filters=16, kernel_size=(3, 3), strides=(1, 1), padding='valid', activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D(pool_size=(2, 2), strides=None, padding='valid'))
model.add(layers.Dropout(rate=1.0))
model.add(layers.Flatten())
model.add(layers.Dense(units=1, activation=None))
```
it's fine, but

* tensorflow version
```python
from tensorflow.keras import layers
from tensorflow.keras import models

model = models.Sequential()
model.add(layers.Conv2D(filters=16, kernel_size=(3, 3), strides=(1, 1), padding='valid', activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D(pool_size=(2, 2), strides=None, padding='valid'))
model.add(layers.Dropout(rate=1.0))
model.add(layers.Flatten())
model.add(layers.Dense(units=1, activation=None))
```
it occurred ValueError like below:
```sh
ValueError: keep_prob must be a scalar tensor or a float in the range (0, 1], got 0
```

When I see the [source code line](https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/python/keras/layers/core.py#L142), why it works like `1 - self.rate`?

Related issue #24526

**Comment by omalleyt12** [comment]
`rate` is what fraction of neurons you drop, i.e. everything would be zeros. In general, this is not something users should be able to do. This error is intended, except perhaps it should mention `rate` if the `rate` arg is used rather than `keep_prob`

**Comment by GzuPark** [comment]
@omalleyt12 I can understand what you want to say, but my point is why they use different applied argument between `keras` and `tensorflow.keras`.

**Comment by GzuPark** [comment]
#24526  merged
