### ISSUE TITLE
gpu installation automation

### ISSUE THREAD

**Issue by rnreich** [tensorflow/tensorflow#24846]
installation with gpu is very difficult. could you please publish a one-command script that does the whole process? see a list of the steps here (i wrote them):

https://github.com/rnreich/ubuntu-tensorflow-gpu-all-versions

**Comment by ymodak** [comment]
Thanks for the document!

**Comment by gunan** [comment]
I will close the issue, but thanks for the document!
It will still be discoverable through search, and I am sure it will be very helpful to users.
