### ISSUE TITLE
Add MetaOptimizer option to save the graph after each optimization pass

### ISSUE THREAD

**Issue by samikama** [tensorflow/tensorflow#24843]
Adding an option to MetaOptimizer to dump the graph after each optimization pass will help in development of optimizers and understanding of how the graph is modified before being executed. Currently only final graph is saved if VLOG level is 1. Extending it to the per optimization level is much more useful than saving the final graph, since it is already possible to get final graph through RunMetadata.

**Comment by samikama** [comment]
tagging @azaks2  since we discussed this a few months back and current implementation is not covering this issue.

**Comment by sherryy** [comment]
Resolved in https://github.com/tensorflow/tensorflow/commit/16c0e72b92497587b6f7e1614869066ed122c9e4.
