### ISSUE TITLE
Upgrade tensor flow from 1.9 to 1.12, Using tf.keras : ImportError: cannot import name 'Layer'

### ISSUE THREAD

**Issue by liupeng89** [tensorflow/tensorflow#24847]
'from tensorflow.keras.layers import Embedding, Dense, Input, Dropout, LSTM, Activation, Conv2D, Reshape, Average, Bidirectional'

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-b2fcd5276851> in <module>()
----> 1 from tensorflow.keras.layers import Embedding, Dense, Input, Dropout, LSTM, Activation, Conv2D, Reshape, Average, Bidirectional
      2 from tensorflow.keras.models import Model
      3 from tensorflow.keras.optimizers import Adam
      4 
      5 from tensorflow.keras.losses import binary_crossentropy

/usr/local/lib/python3.5/dist-packages/tensorflow/keras/__init__.py in <module>()
     18 from . import estimator
     19 from . import initializers
---> 20 from . import layers
     21 from . import losses
     22 from . import metrics

/usr/local/lib/python3.5/dist-packages/tensorflow/keras/layers/__init__.py in <module>()
      6 from __future__ import print_function
      7 
----> 8 from tensorflow.python.estimator.keras import Layer
      9 from tensorflow.python.keras import Input
     10 from tensorflow.python.keras.applications.densenet import Activation

ImportError: cannot import name 'Layer'

**Comment by ymodak** [comment]
Can you try,
> from tensorflow.keras.layers import Layer

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks!

**Comment by jmugan** [comment]
I have the same issue. The solution from @liupeng89 does not help. I still get the same error.

**Comment by tkrivachy** [comment]
I had the same issue when upgrading to tensorflow 1.13 (windows, through conda). In the end I just used keras with tensorflow backend, i.e. for this example:
from keras.layers import Embedding, Dense, Input, Dropout, LSTM, Activation, Conv2D, Reshape, Average, Bidirectional

**Comment by bjayakumar** [comment]
I have the same problem.
`pydoc.ErrorDuringImport: problem in tensorflow.keras - ImportError: cannot import name 'Layer'`

Any proper solution for this instead of workaround?

**Comment by liupeng678** [comment]
> I have fixed it just typing "from tensorflow.keras.layers import Embedding, Dense, Input, Dropout, LSTM, Activation, Conv2D, Reshape, Average, Bidirectional'" again. Thanks!

We have the same name.
