### ISSUE TITLE
Fix support for newer bazel versions - Issue 23673 closed with incorrect solution.

### ISSUE THREAD

**Issue by chargrnv** [tensorflow/tensorflow#24841]
I believe https://github.com/tensorflow/tensorflow/issues/23673 was closed incorrectly.

The problem is newer versions of bazel are not reading the bazel.rc that provides:
```
tools/bazel.rc:build --define=grpc_no_ares=true
```

The solution can not be to install ares as this option is supposed to disable the need for it.

Please fix the build process to support newer versions of bazel (in my case, using 0.19.0)

**Comment by jvishnuvardhan** [comment]
This is a stale issue. Please check the issue with latest TensorFlow. If the issue still persists in the newer version of TF, please feel free to reopen it by providing details about the issue and a standalone code to reproduce the issue. Thanks!
