### ISSUE TITLE
Eager Execution Guide link is broken

### ISSUE THREAD

**Issue by ehennis** [tensorflow/tensorflow#24856]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: v2.0
- Doc Link: https://github.com/ehennis/Blog/tree/master/TensorFlow

**Describe the documentation issue**
I was looking through the eager execution documentation and one of the links is missing the extension 'ipynb'. If you click on the "eager execution guide" the link is broken.

Markdown Page: https://github.com/ehennis/Blog/tree/master/TensorFlow.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by ymodak** [comment]
The link you are pointing in this issue is incorrect since you are the owner of the repo.
I think you meant this link for the [eager execution guide](https://github.com/tensorflow/docs/tree/master/site/en/r2/tutorials/eager)

**Comment by ehennis** [comment]
Jeez, copy and paste issue.

Here is the page: https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/eager/index.md. If you look at the link "eager execution guide" it goes to "https://github.com/tensorflow/docs/blob/master/site/en/r2/guide/eager" which gets a 404.

**Comment by ehennis** [comment]
I can edit the original if that would make more sense.

**Comment by ymodak** [comment]
@lamberta Can you please take a look?
> Jeez, copy and paste issue.
> 
> Here is the page: https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/eager/index.md. If you look at the link "eager execution guide" it goes to "https://github.com/tensorflow/docs/blob/master/site/en/r2/guide/eager" which gets a 404.

**Comment by lamberta** [comment]
Fixed in https://github.com/tensorflow/docs/pull/295
Thanks
