### ISSUE TITLE
second max_pool probably is missing in "create_conv_model" function in tensorflow/examples/speech_commands/models.py

### ISSUE THREAD

**Issue by Alireza89** [tensorflow/tensorflow#24854]
in function `create_conv_model()` which is defined in: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/speech_commands/models.py

It seems that the second max pool is missing.
Due to the documentation of the function this should be the layout of the graph:

&nbsp;(fingerprint_input)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v
 [Conv2D]<-(weights)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v
 [BiasAdd]<-(bias)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Relu]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[MaxPool]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v
[Conv2D]<-(weights)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v
[BiasAdd]<-(bias)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Relu]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[MaxPool] <================is this missing???
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v
[MatMul]<-(weights)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v
[BiasAdd]<-(bias)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v

After the first_dropout, max pooling is correctly performed:
`line 272: max_pool = tf.nn.max_pool(first_dropout, [1, 2, 2, 1], [1, 2, 2, 1], 'SAME')`

But I could't find any max pooling after the second_dropout.

**Comment by petewarden** [comment]
Thanks! I think that's just a documentation problem, since I discovered the second max pool was not necessary for that model.
