### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jiujiangxueyuan** [tensorflow/tensorflow#24869]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\acer\\AppData\\Local\\Temp\\pip-build-dvj27vs5\\tf-nightly-gpu-2.0-preview\\tf_nightly_gpu_2.0_preview-1.13.0.dev20181221.data/purelib/tensorflow/include/tensorflow/include/external/eigen_archive/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h'

**Comment by LuckyPigeon** [comment]
Have you install tensorflow-gpu instead of tf-nightly-gpu before?

**Comment by ymodak** [comment]
I am guessing you have a build/install related issue. Can you please provide the following information? Thanks!
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:



**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**


**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Worthy7** [comment]
@LuckyPigeon Should it matter? 
I just had this problem too. 
Is there something missing from the requirements within the `tf-nightly-2.0-gpu-preview` package?

**Comment by LuckyPigeon** [comment]
@Worthy7 
My OS: Ubuntu 18.04 with virtualenv
I install tensorflow-gpu first then install tf-nightly-2.0-gpu-preview and it works.

**Comment by Worthy7** [comment]
So, does this means that tensorflow-gpu is *required* for 2.0? If so, it
should be listed....
