### ISSUE TITLE
tf.sparse.to_dense warns that you should use itself

### ISSUE THREAD

**Issue by urialon** [tensorflow/tensorflow#24873]
**System information**
- TensorFlow version: 1.12
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/sparse/to_dense
- Implemented here: https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/python/ops/sparse_ops.py#L1115

**Describe the documentation issue**
Hi,
The function [`tf.sparse.to_dense`](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/python/ops/sparse_ops.py#L1115), is a wrapper for `tf.sparse_to_dense`. However, [`tf.sparse_to_dense`](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/python/ops/sparse_ops.py#L832) is deprecated and produces a warning that the user should use `tf.sparse.to_dense` instead.

So, the user uses the correct function `tf.sparse.to_dense` but still gets a warning that she should use it.

Example code that produces that warning:
`
s = tf.SparseTensor(indices=[[1,1],[2,2],[3,3]], values=[4,5,6],dense_shape=[3,3])
tf.sparse.to_dense(s)
`

results in a warning:
WARNING:tensorflow:From /home/urialon/.local/lib/python3.6/site-packages/tensorflow/python/ops/sparse_ops.py:1165: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.

So I am not sure - is this the right usage, and just the warnings are wrong?
Thanks!

**Comment by yongtang** [comment]
@urialon I think the issue has been fixed in #24037.

**Comment by urialon** [comment]
Right, thanks!
