### ISSUE TITLE
Documentation on reducing the binary size of tflite library on iOS

### ISSUE THREAD

**Issue by lenaevans** [tensorflow/tensorflow#24871]
**System information**
- TensorFlow version: r1.12
- Doc Link: https://www.tensorflow.org/lite/

**Describe the documentation issue**

The tflite library seems to add around 2.5 MB to my iOS binary, which is far bigger than the 700 kB claimed in the documentation. Are there custom build options for tflite like there was with tfmobile that can help get this library size down? I haven't been able to find documentation on how to do this.

For context, I've tried using both the Pod and also used the build_ios_universal_lib.sh script, but the library size still seems to be around 2.5 MB.

**Comment by lenaevans** [comment]
Nevermind, after compiling with size optimization, this seems to be a non-issue.

**Comment by holyhao** [comment]
@lenaevans hi，how can you set the compiling with size optimization. I build it for android and it gets 3.6M.

**Comment by lenaevans** [comment]
The biggest issue I found for both iOS and android is building for all architectures, which puts multiple copies of tensorflow in the app and thus inflates your size. If you build for specific architectures, you will probably see more reasonable app sizes. (See e.g. [this](https://proandroiddev.com/reducing-apk-size-by-using-abi-filters-and-apk-split-74a68a885f4e) for how to do that).

**Comment by holyhao** [comment]
@lenaevans  sorry ，i did not make it clear. I mean the size of binary size of tflite library. The size of file  libtensorflowLite.so.

**Comment by lenaevans** [comment]
Ohh hm, sorry can't really help there :(. I haven't tried to compile from source for android, the package in the package manager worked fine for me.

**Comment by wangwenjing** [comment]
@lenaevans Hi, i encounter same problem. I got a binary of libtensorflow-lite.a for arm64, it's around 7.5MB. Do you have any idea on how to reduce the size? Thanks in advance.

**Comment by lenaevans** [comment]
I got the library from the build_ios_universal_lib.sh script, and then compiled in xcode with optimizations for space in the compiler settings. At first it looked a lot bigger than it actually was for me because I was looking at the size of the universal framework but once I looked at the size increases of the builds for the individual architectures, the size was a little over 1 MB.

**Comment by wangwenjing** [comment]
@lenaevans Hi, What did you mean by "compiled in xcode with optimizations for space in the compiler settings", you meant to set some settings in Xcode when compile project which use libtensorflow-lite.a  ?  if so, can you tell me what settings you specified ?  I'm a newbie in this area. Thanks a lot.

**Comment by adamdbrw** [comment]
Here's a diff of changes that worked for me to reduce the minimal binary size from ~2.9Mb to ~1.1Mb for Aarch64. Note that not all are necessary and I can't guarantee it works for everyone. My binary was running happily just fine:

```
diff --git a/tensorflow/lite/tools/make/Makefile b/tensorflow/lite/tools/make/Makefile
index 6d4b0c0ce3..f0c398e8a3 100644
--- a/tensorflow/lite/tools/make/Makefile
+++ b/tensorflow/lite/tools/make/Makefile
@@ -55,11 +55,12 @@ LIBS := \
 # There are no rules for compiling objects for the host system (since we don't
 # generate things like the protobuf compiler that require that), so all of
 # these settings are for the target compiler.
-CXXFLAGS := -O3 -DNDEBUG -fPIC
+CXXFLAGS := -Os -DNDEBUG -fPIC -ffunction-sections -fdata-sections -s
 CXXFLAGS += $(EXTRA_CXXFLAGS)
 CFLAGS := ${CXXFLAGS}
 CXXFLAGS += --std=c++11
 LDOPTS := -L/usr/local/lib
+LDFLAGS += -Wl, --gc-sections
 ARFLAGS := -r
 TARGET_TOOLCHAIN_PREFIX :=
 CC_PREFIX :=
```
