### ISSUE TITLE
tensorflow installed but cannot be imported

### ISSUE THREAD

**Issue by BrunoCapron** [tensorflow/tensorflow#24870]
**System information**
- Microsoft Windows 10 Home Single Language
- TensorFlow installed from binary
- TensorFlow version: 1.12.0 but also tried bit 1.5.0 and 1.11.0
- Python version: Python 3.6.8 and also tried 3.5.2
- Installed using virtualenv? pip? conda?: tried using pip and conda
- CUDA/cuDNN version: cannot find a cuda or cudnn file
- GPU model and memory: Nvidia geforce 840 - Total memory 6071 MB of which 2010MB is Video RAM

The installation of tensorflow using the `pip install tensorflow` command was successful but when I test the command `import tensorflow as tf` with `cmd.exe`, I get the following result:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Bruno\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
ModuleNotFoundError: No module named 'tensorflow.python'
```
I tried so many things that i am quite desperate. Can someone please suggest a solution?

**Comment by prachm** [comment]
I am facing a similar problem

System information

Microsoft Windows 10 Home 
TensorFlow installed from .whl
TensorFlow version: tf-nightly-gpu-2.0-preview
Python version: Python 3.6.6
Installed using virtualenv? pip? conda?: pip 
CUDA/cuDNN version: CUDA 10/cuDNN
GPU model and memory: Nvidia geforce 1050
The installation of tensorflow using the pip install tensorflow command was successful but when I test the command import tensorflow as tf using anaconda, I get the following result:

`(TF2wPy36) C:\Users\prach>import tensorflow as tf
'import' is not recognized as an internal or external command,
operable program or batch file.

(TF2wPy36) C:\Users\prach>python tf2-hello.py
Traceback (most recent call last):
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tf2-hello.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\site-packages\tensorflow\__init__.py", line 27, in <module>
    from tensorflow._api.v2 import autograph
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\site-packages\tensorflow\_api\v2\autograph\__init__.py", line 20, in <module>
    from tensorflow._api.v2.autograph import experimental
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\site-packages\tensorflow\_api\v2\autograph\experimental\__init__.py", line 8, in <module>
    from tensorflow.python.autograph import Feature
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\prach\Anaconda3\envs\TF2wPy36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
`

**Comment by narayant** [comment]
Mac OS X EI Captain.Python Anaconda 3.6, am getting the following error when i run "from keras.models import Sequential"


Using TensorFlow backend.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

/Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

/Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

/Applications/Anaconda/anaconda/lib/python3.6/imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

/Applications/Anaconda/anaconda/lib/python3.6/imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: dlopen(/Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _clock_gettime
  Referenced from: /Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-e029ff700625> in <module>()
----> 1 from keras.models import Sequential
      2 from keras.layers import Dense
      3 from keras.layers import LSTM

/Applications/Anaconda/anaconda/lib/python3.6/site-packages/keras/__init__.py in <module>()
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

/Applications/Anaconda/anaconda/lib/python3.6/site-packages/keras/utils/__init__.py in <module>()
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 
      8 # Globally-importable utils.

/Applications/Anaconda/anaconda/lib/python3.6/site-packages/keras/utils/conv_utils.py in <module>()
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

/Applications/Anaconda/anaconda/lib/python3.6/site-packages/keras/backend/__init__.py in <module>()
     87 elif _BACKEND == 'tensorflow':
     88     sys.stderr.write('Using TensorFlow backend.\n')
---> 89     from .tensorflow_backend import *
     90 else:
     91     # Try and load external backend.

/Applications/Anaconda/anaconda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in <module>()
      3 from __future__ import print_function
      4 
----> 5 import tensorflow as tf
      6 from tensorflow.python.framework import ops as tf_ops
      7 from tensorflow.python.training import moving_averages

/Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 try:

/Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 from tensorflow.python.tools import component_api_helper

/Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Applications/Anaconda/anaconda/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Applications/Anaconda/anaconda/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _clock_gettime
  Referenced from: /Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Anaconda/anaconda/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ymodak** [comment]
@prachm  I see that you are trying to install TF 2.0 preview version. Since this is a different issue than the original one, Can you please post a new issue describing your problem? Thanks!
I will close this issue since it's resolved for the author. Thanks!
