### ISSUE TITLE
TFLite Upsample Nearest Neighbors

### ISSUE THREAD

**Issue by yuvdar** [tensorflow/tensorflow#24877]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macos
- TensorFlow installed from (source or binary): 1.12 /  tf-nightly-1.13.0.dev20190112
- TensorFlow version (or github SHA if from source):

command: tflite_convert --keras_model_file=model.h5 --output_file=model.tflite --input_array=input_1 --inference_type=FLOAT --input_shape=1,512,512,3

I'm trying to convert a keras model that has an upsample nearest neighbors op. In tf 1.12 this op is not supported, and I saw it was added later on but not yet in the official release. When I used tf-nightly I get an error:

error:
2019-01-13 09:12:33.214920: I tensorflow/core/grappler/devices.cc:53] Number of eligible GPUs (core count >= 8): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-01-13 09:12:33.215726: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-01-13 09:12:33.275871: E tensorflow/core/grappler/grappler_item_builder.cc:636] Init node initial_conv/kernel/Assign doesn't exist in graph

Is there some commit I can use to convert my model?

**Comment by Kolefn** [comment]
I am running into the same issue. The tflite file is created but instantiating the interpreter with the loaded model throws an error.

**Comment by yuvdar** [comment]
any updates?

**Comment by yuvdar** [comment]
The problem doesn't reproduce with TensorFlow 1.13.0-rc0. As far as I care, this issue can be closed.

**Comment by jvishnuvardhan** [comment]
@Kolefn Could you also try with TF1.13 and let us know whether it resolved the issue or not? Thanks!
