### ISSUE TITLE
how to control the dimension of operation tf.spectral.fft2() 

### ISSUE THREAD

**Issue by YunyanYao** [tensorflow/tensorflow#24879]
Hi TF, I am new here and wondering that

for a tf.tensor (placeholder) normally defined as shape=[batch_size, image_height, image_width, channel_number], along which dimensions would fft2 operate on?

what if I just want to do 2d fft in image domain, i.e. the middle two dimensions of the above fourth-order tensor?

huge thanks

**Comment by YunyanYao** [comment]
Numerically it seems that fft2 acquiescently operates on the first two dimensions of a predefined tensor

**Comment by jvishnuvardhan** [comment]
@YunyanYao Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support. Github is mainly for addressing bugs in installation and performance. Responses to your questions will help others also if you post them on Stackoverflow. Thanks!

**Comment by jvishnuvardhan** [comment]
Please post support related questions in StackOverflow. We encourage users to submit an issue/feature request here. Closing the issue. Thanks!
