### ISSUE TITLE
regression in skflow monitoring code

### ISSUE THREAD

**Issue by laouer** [tensorflow/tensorflow#2487]
Using the version [pip_gpu version #100](http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/100), I noted that a corrected issue by ilblackdragon ([#2063](https://github.com/tensorflow/tensorflow/issues/2063)) re-occurred and a PR from him self [Ref #2063](https://github.com/ilblackdragon/tensorflow/commit/534deda849e389ea625cc3abca632177c95b9534#diff-0ac50f1931e3fc2819c02d8767edb1d3R29) has disappeared in the master code.

Could the issue be corrected and the enhancement reintegrated ?
Cordially

**Comment by ilblackdragon** [comment]
Let me look into this - we have refactored a large chunk of code, including monitoring code so may have missed some parts of functionality.

**Comment by ilblackdragon** [comment]
FYI, got a fix, but after adding some more tests to check that `ValidationMonitor` actually works correctly got a problem with flaky test (result change slightly every time I run) - trying to debug what is happening there. 

We will cherry pick that fix into the 0.9 release though.
