### ISSUE TITLE
Support per channel quantized ops

### ISSUE THREAD

**Issue by shoubhik** [tensorflow/tensorflow#24881]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):1.12
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The current quantization Ops -  [tf.quantization](https://www.tensorflow.org/api_docs/python/tf/quantization), [tf.nn.quantized_conv2d](https://www.tensorflow.org/api_docs/python/tf/quantization) support only per layer quantization. For per channel quantization the `min` and `max` values should be of dimension `[d]`, one for each channel instead of being a single `float` value now.

**Will this change the current api? How?**
Yes. The ops will take `[d]` dimensional `min` and `max` values, one per channel. And the `output_min` and `output_max` would also be  `[d]` dimensional .
**Who will benefit with this feature?**
Anyone who wants to use per channel quantization.
**Any Other info.**

**Comment by cyndwith** [comment]
Do we have per channel quantization support in the tflite converter ?

**Comment by rmothukuru** [comment]
@shoubhik,
Please refer the documentation of [Quantization Spec](https://www.tensorflow.org/lite/performance/quantization_spec) and [Post Training Quantization](https://www.tensorflow.org/lite/performance/post_training_quantization#representation_for_quantized_tensors) which has a mention about Support for **`per Channel Quantized Ops`**. Thanks!
