### ISSUE TITLE
Fusing context and cell output in AttentionWrapper 

### ISSUE THREAD

**Issue by georgesterpu** [tensorflow/tensorflow#24897]
**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
`AttentionWrapper` fuses the `cell_output` and the `context` vector using an `array_ops.concat` operation when specifying an attention layer: [link](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py#L1067)

In my case, this behaviour is not flexible enough, I and would like to be able to define my own function to replace the `concat` operation.

**Will this change the current api? How?**
Similarly to `cell_input_fn`, I would like to have a `attention_layer_fn` in `AttentionWrapper`, which by default will perform a `concat`, preserving the old behaviour. This function would be passed to `_compute_attention`, which could be modified like this:

```
if attention_layer is not None:
  attention_layer_input = attention_layer_fn(cell_output, context)
  attention = attention_layer(attention_layer_input)
else:
  attention = context
```
where
```
if attention_input_fn is None:
  attention_input_fn = (
      lambda cell_output, context: array_ops.concat([cell_output, context], 1))
```

**Who will benefit with this feature?**
TensorFlow users designing new attention architectures may find this feature useful.
The users have to implement their own function taking `cell_output` and `context` as inputs.

**Any Other info.**
I am not a super experienced developer, so I would also like to ask for advice.

I implemented the feature locally and successfully trained a network, but ran into a new problem.

The main goal would be to debug/visualise some internal ops defined by the user inside the new function, just like with `alignment_history`. And here is where things get complicated.

Since these operations are created inside the `while_loop` of `dynamic_rnn`, I'd have to use a `TensorArray` and write the variables at every step (otherwise it says that the operation has been marked as not fetchable), but this also requires `state.time` when calling `write()`. Then the object returned by `write()` should be added to the `AttentionWrapperState`, to show up in the final_state when running `dynamic_rnn`. Is there a simpler way to visualise all the necessary ops inside the envisaged `attention_input_fn` ?

**Comment by ebrevdo** [comment]
@qlzh727 fyi.

**Comment by georgesterpu** [comment]
Hello,
To state the feature a bit more clear, imagine you wanted to debug the ops created in a custom `cell_input_fn`, which is already supported in `AttentionWrapper`. How would you design this ?

Would it be fine to design `cell_input_fn` as a callable with several methods, e.g. `__call__`, `build`, `update`, where you implement all the necessary stuff  from the outside, while `AttentionWrapper` forwards your custom output to another `AttentionWrapperState` member called `payload`, so that you can find everything there in the final state returned by `dynamic_rnn` ?

I am just trying to make it more simple to design new attention architectures, as everybody has their own ideas of what they should look like. Subclassing `AttentionWrapper` would result in a lot of duplicated code. Am I missing here something, such as a more simple way to visualise my variables ?
