### ISSUE TITLE
The Object Detection Tutorial is broken

### ISSUE THREAD

**Issue by dkashkin** [tensorflow/tensorflow#24916]
**System information**
- TensorFlow version: 1.13.0-dev20190114
- Doc Link: https://www.tensorflow.org/lite/
**Describe the documentation issue**
TFLite's home page links to this Object Detection tutorial: https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193 
The tutorial is not compatible with the latest TensorFlow (1.13). It has multiple references to the TOCO convertor which used to be in tensorflow/contrib/lite/toco:toco but has been recently removed. I believe, it has been replaced by TFLiteConverter which has a different interface, so the tutorial needs to be updated. Plus, it would make a lot of sense to provide an iOS specific object detection tutorial. You already have both Android and iOS image classifier tutorials, so it would be sweet to give object detection the same coverage.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

This tutorial must be fixed by somebody who knows how to get TFLiteConverter to work. I gave it a shot but was unable to convert the post-processing operation. I already filed issue 24910 with all the details on this.

**Comment by jdduke** [comment]
The latest tutorial has been updated @ https://www.tensorflow.org/lite/models/object_detection/overview.
