### ISSUE TITLE
When I compile andorid so using bazel build and reference this so in a new project, the generated so will be linked to the absolute path.

### ISSUE THREAD

**Issue by SuperSaiyan30** [tensorflow/tensorflow#24913]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- Linux Ubuntu 16.04
- NA
- TensorFlow installed from source
- Python version: Python 2.7.12
- Bazel version: release 0.21.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 4.9.3-13ubuntu2) 4.9.3
- CUDA/cuDNN version: 
- GPU model and memory:

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Recurring step
1.  Use the following command to compile libtensorflow_demo.so in tensorflow project

bazel build -c opt //tensorflow/examples/android:tensorflow_demo    --crosstool_top=//external:android/crosstool    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain    --cxxopt=-std=c++11    --cpu=arm64-v8a

2. use libtensorflow_inference.so with ndk-build and get libCameraTest.so
the Fragment of Android.mk like this
include $(CLEAR_VARS)
LOCAL_MODULE := libtensorflow_demo-prebuild
LOCAL_SRC_FILES := $(LOCAL_PATH)/lib/libtensorflow_demo.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_PATH := $(MY_PATH)
LOCAL_MODULE := CameraTest
LOCAL_SHARED_LIBRARIES  += libtensorflow_demo-prebuild
LOCAL_CPPFLAGS  += -std=c++11
LOCAL_CFLAGS := -g
LOCAL_LDLIBS    += -llog -landroid -lz 
#LOCAL_SHARED_LIBRARIES += libc libdl

LOCAL_ARM_MODE := arm  
include $(BUILD_SHARED_LIBRARY)

3. use objdump -T libCameraTest.so | grep Needed
i got the follow result
 NEEDED               D:/workspace/new_invisioncontroller/InVisionBTControl_ball_tensorflow/InVisionBTControl_ball_tensorflow/InVisionBTControl_ball_tensorflow/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/libtensorflow_demo.so

**Other info / logs**

**Comment by SuperSaiyan30** [comment]
@jvishnuvardhan ， thank you for reply，
the tensorflow need bazel 0.18.0 at least, i try with bazel 0.18.1 and the issue persists

**Comment by jdduke** [comment]
This does not look related to TensorFlow Mobile, this looks more like an Android toolchain issue in how you're generating your app .so. StackOverflow is probably a better place for this question.
