### ISSUE TITLE
About the MFCC feature in input_data.py

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/tensorflow#24919]
Dear,
In the script,
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/speech_commands/input_data.py](url)
is there any related pdf or other file about the mfcc feature extraction,
Could U help me about this, please?
Any advice or suggestion will be okey.
Thx.

**Comment by ucasiggcas** [comment]
Second,
What's the meaning of the func get_features_range in input_data.py ?
`  # TODO(petewarden): These values have been derived from the observed ranges
  # of spectrogram and MFCC inputs. If the preprocessing pipeline changes,
  # they may need to be updated.`
and also the up words ?
If the sample_rate change, need change the range?
Any help will be good.
Thx

**Comment by jvishnuvardhan** [comment]
@ucasiggcas Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support. Github is mainly for addressing bugs in installation and performance. I found this [paper]
(http://www.cs.cmu.edu/~chanwook/MyPapers/b_li_interspeech_2017.pdf) and there are several resources covering advanced MFCC. Thanks!

**Comment by jvishnuvardhan** [comment]
@ucasiggcas -1 refers to expanding dimensions in the end of the tensor. Please take a look at [here](https://www.tensorflow.org/api_docs/python/tf/expand_dims) for more details. If max_outputs is 1, the summary value tag is 'name/image'. please check [here](https://www.tensorflow.org/api_docs/python/tf/summary/image). Thanks!

I am closing the issue but please post this kind of support questions at Stackoverflow. Thanks!
