### ISSUE TITLE
Compiler error : To build Android TensorFlow library on mac os

### ISSUE THREAD

**Issue by cheer67** [tensorflow/tensorflow#24928]
OS platform : mac os 10.13.6
TensorFlow : source code
TensorFlow : 1.12

Build Cmd:
NDK_ROOT=/Users/cheer67/android_ndk/android-ndk-r15c tensorflow/contrib/makefile/compile_android_protobuf.sh -c

Error Log:

checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking for arm-linux-androideabi-gcc...  arm-linux-androideabi-gcc --sysroot /Users/cheer67/android_ndk/android-ndk-r15c/platforms/android-21/arch-arm
checking whether the C compiler works... no
configure: error: in `/Users/cheer67/tensorflow-master/tensorflow/contrib/makefile/downloads/protobuf':
configure: error: C compiler cannot create executables
See `config.log' for more details
cheer67de-MacBook-Pro:tensorflow-master cheer67$ 

[config.log](https://github.com/tensorflow/tensorflow/files/2758840/config.log)

**Comment by ymodak** [comment]
@resec Can you please take a look? Thanks!

**Comment by cheer67** [comment]
OK

**Comment by ymodak** [comment]
We're trying to deprecate mainline TensorFlow Android builds in favor of TensorFlow Lite. Thus, closing this one.
