### ISSUE TITLE
Building from source the shared library for Raspberry-Pi

### ISSUE THREAD

**Issue by AntoineWeber** [tensorflow/tensorflow#24934]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian Stretch 9.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.9.0
- Python version: 3.5
- Installed using virtualenv? pip? conda?: none
- Bazel version (if compiling from source): 0.11.0
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: none
- GPU model and memory: none

**Describe the problem**
I've been trying to compile tensorflow from source on my raspberry-pi for quite some time and did not succeeded yet.
I followed many different tutorials such as [this](https://www.youtube.com/watch?v=WqCnW_2XDw8) or [this](https://gist.github.com/EKami/9869ae6347f68c592c5b5cd181a3b205) but none of them allowed me to build it successfully.
I arrived to the point that I decided to ask for help. My latest state is trying to build tensorflow 1.9.0 using bazel 0.11.0 (as stated on tensorflow's website that these two versions are compatible). The bazel build goes flawlessly but for the tensorflow build, after ~20'000 seconds, shows the final error : 
tensorflow/tensorflow/BUILD:506:1: Linking of rule '//tensorflow:libtensorflow_cc.so' failed (Exit 1).

The goal would be to load and run a pre-trained model on my own c++ project. The pre-trained model was trained using keras with tensorflow backend version 1.10.1.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
The steps are : 
```
git clone https://github.com/tensorflow/tensorflow.git
git checkout v1.9.0
grep -Rl 'lib64' | xargs sed -i 's/lib64/lib/g'
./configure
bazel build -c opt --config=monolithic --local_resources 1024,1.0,1.0 --verbose_failures //tensorflow:libtensorflow_cc.so
```

**Any other info / logs**

ERROR: /home/pi/cleanTF/tensorflow/tensorflow/BUILD:506:1: Linking of rule '//tensorflow:libtensorflow_cc.so' failed (Exit 1): gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/280abdd112ab916e808922e4ee91ed95/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/local/lib/python3.5/dist-packages \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
  /usr/bin/gcc -shared -o bazel-out/arm-opt/bin/tensorflow/libtensorflow_cc.so -z defs -Wl,--version-script tensorflow/tf_version_script.lds '-Wl,-rpath,$ORIGIN/' -Wl,-soname,libtensorflow_cc.so -pthread-pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread-pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,-S -Wl,@bazel-out/arm-opt/bin/tensorflow/libtensorflow_cc.so-2.params)
bazel-out/arm-opt/bin/tensorflow/core/kernels/_objs/list_kernels/tensorflow/core/kernels/list_kernels.pic.o:list_kernels.cc:function tensorflow::TensorListStack<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'void tensorflow::ConcatCPU<tensorflow::bfloat16>(tensorflow::DeviceBase*, std::vector<std::unique_ptr<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix, std::default_delete<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix> >, std::allocator<std::unique_ptr<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix, std::default_delete<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix> > > > const&, tensorflow::TTypes<tensorflow::bfloat16, 2, int>::Matrix*)'
collect2: error: ld returned 1 exit status
Target //tensorflow:libtensorflow_cc.so failed to build
INFO: Elapsed time: 18838.252s, Critical Path: 14426.26s
FAILED: Build did NOT complete successfully

**Comment by anilknayak** [comment]
Try
https://stackoverflow.com/questions/53874017/error-while-building-libtensorflow-so-on-raspberry-pi/54202653#54202653

**Comment by AntoineWeber** [comment]
@anilknayak The tensorflow build still give me a huge amount of errors, apparently mostly due to my pip version even if when checking my pip version, I have the most recent one (18.1 as of today)

I do not know why it doesn't detect the right pip version.

The exact error is : 
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-NJz6ti/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-HXLX0R-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-NJz6ti/scipy/
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c /install/install_pip_packages.sh' returned a non-zero code: 1

**Comment by anilknayak** [comment]
@AntoineWeber 
Are you building on raspberry pi or cross-compiling it?

**Comment by AntoineWeber** [comment]
I am building it directly on the raspberry pi

**Comment by anilknayak** [comment]
@AntoineWeber 
If you build in raspberry pi, there are lot of things to be done. Anything this will take very long time because of limited memory.

I will suggest to cross compile it. This is very easy, if you follow the stackoverflow page, I have summarized the point. Try once, we will see what is happening then.

**Comment by AntoineWeber** [comment]
@anilknayak 
In your post you mention that you also cross-compiled it for the raspberry pi.

May I ask more informations on which shell script did you run for the bazel build ?
And also how did you cross-compiled protobuf exactly ?

**Comment by anilknayak** [comment]
@AntoineWeber 
**Protobuf:**
git clone https://github.com/google/protobuf.git
cd protobuf
git checkout v3.1.0
./autogen.sh
./configure
make -j 4
sudo make install
sudo ldconfig
**Output**
protoc --version
libprotoc 3.1.0
**Bazel**
wget https://github.com/bazelbuild/bazel/releases/download/0.15.2/bazel-0.15.2-dist.zip
unzip -d bazel bazel-0.15.2-dist.zip
cd bazel
chmod u+w ./* -R
./compile.sh
sudo cp output/bazel /usr/local/bin/

**Comment by jvishnuvardhan** [comment]
@AntoineWeber good to hear you found the solution and Thanks for providing solution here. @anilknayak Thanks for supporting the community. I am closing this issue.
