### ISSUE TITLE
Continuously differentiable eigendecomposition

### ISSUE THREAD

**Issue by Randl** [tensorflow/tensorflow#24930]
**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes, but I'd probably need some guidance.

**Describe the feature and the current behavior/state.**
Currently, when any two eigenvalues are equal, the `tf.gradients( tf.self_adjoint_eig(matrix), matrix) ` function returns NaN. 
It was proposed to return a subgradient (https://github.com/tensorflow/tensorflow/issues/12853) in this case, which equals `v_k^T*v_k` for kth eigenvalue. However, there [exists](https://www.win.tue.nl/analysis/reports/rana06-33.pdf) a procedure which allows to generate continuously differentiable eigendecomposition. This allows to have calculate true gradient (of a particluar decomposition) as soon as eigenbasis exists. Intuitively, if we choose a particular consistent way to choose eigenvectors from subspace, the eigendecomposition would be well defined.

Possibly related issue (same about SVD): https://github.com/tensorflow/tensorflow/issues/13641
**Will this change the current api? How?** The eigendecomposition will probably change in cases it is not unique.

**Who will benefit with this feature?** People dealing with optimizations based on eigenvalues/eigenvectors.

**Comment by Randl** [comment]
ping

**Comment by Randl** [comment]
@rmlarsen as far as I understand, you are the prime developer of linalg related stuff. Could you mentor me on this one or propose someone who could mentor me?

**Comment by rmothukuru** [comment]
@Randl,
Sorry for the delayed response. Can you please let us know if [tf.linalg.eigh](https://www.tensorflow.org/api_docs/python/tf/linalg/eigh) is the API that you are looking for? Thanks!

**Comment by Randl** [comment]
Yes, I think it was fixed by introducing Lorenz broadening here: https://github.com/tensorflow/tensorflow/pull/33808/files#diff-589f3bb3ae164fc660ae23ebe4eceabf5700612ecef44785c47ce788bd8e4584R712
