### ISSUE TITLE
How to eliminate duplicate codes for shape inference

### ISSUE THREAD

**Issue by facaiy** [tensorflow/tensorflow#24945]
**System information**
- TensorFlow version (you are using): tf 2.0-preview
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

When we are looking into issue: https://github.com/tensorflow/addons/issues/12, as @jaingaurav said,  SetShapeFn only works in graph constructing stage. So for eager mode, we have to add the duplicate logic (codes) in the `Compute` method of kernel. 

My question is, can we find a solution to get rid of the duplicate codes for shape inference? Say, SetShapeFn also works in eager mode?

cc @jaingaurav @karmel @seanpmorgan

**Comment by jaingaurav** [comment]
@facaiy: The understanding is that kernels should be written in an resilient manner such that they have the appropriate checks and don't crash on bad input. We could have chosen to run the shape function in eager mode. However, this would incur an unnecessary overhead. It is a bit unfortunate this results in a bit of code duplication at the moment.

**Comment by facaiy** [comment]
I agree that shape checking can incur an unnecessary overhead. Thanks for your explanation. I understand. Perhaps we can address the problem in the future.
