### ISSUE TITLE
tensorflow/third_party/toolchains/gpus/cuda/BUILD

### ISSUE THREAD

**Issue by samikama** [tensorflow/tensorflow#24946]
tensorflow/third_party/toolchains/gpus/cuda/BUILD file contains hard coded paths which would not necessarily true for all systems. Anyway I thought these files were generated through repository gen rules in `third_party/gpus/cuda`. Isn't it the case anymore?

**Comment by gunan** [comment]
@r4nt are these the files we added for new GPU builds we are testing?

**Comment by martinwicke** [comment]
@chsigg This is the issue isas suspecting you may know something about.

**Comment by r4nt** [comment]
I think we should be able to get rid of those again, everything we do for remote configs is under the preconfig directory now, and I believe all uses are switched. Once I'm finished with the fires we have I plan having a large clean-up session and hunting down everything we can delete, but I'll want to make sure I don't find any left-over unconverted use cases :)

**Comment by martinwicke** [comment]
@r4nt how are the fires?

**Comment by r4nt** [comment]
Thanks for pinging - there are still a couple of things on my stack, but this one is small enough to drop it in, code review coming your way.

**Comment by r4nt** [comment]
This has landed in 2e846b14e15d9bf04892e935e293dad1f2ec037a.
