### ISSUE TITLE
Tensorflow random categorical

### ISSUE THREAD

**Issue by brubakerjeff** [tensorflow/tensorflow#24949]
Hi,

I'm running 
https://www.tensorflow.org/tutorials/sequences/text_generation

When I arrive at the line the following error is produced. Is there an import missing?
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

AttributeError                            Traceback (most recent call last)
<ipython-input-23-60a341594c52> in <module>
----> 1 sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
      2 sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

AttributeError: module 'tensorflow._api.v1.random' has no attribute 'categorical'

**System information**
- TensorFlow version: 1.12 Jupyter NoteBooks on Ubuntu
- Doc Link:

**Describe the documentation issue**

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by ymodak** [comment]
I would recommend you to install tf-nightly to execute the tutorial locally. You can also try running the the tutorial in google colab to avoid new tf installation. The tutorial works as expected in the google colab thus should not have issues in nightly version as well.

**Comment by altardivaud** [comment]
I also encounter this issue, so I use:
sampled_indices = tf.random.multinomial(example_batch_predictions[0], num_samples=1)
to bypass the problem instead of categorical.

**Comment by brubakerjeff** [comment]
I had asked on stackoverflow. https://stackoverflow.com/questions/54210128/tensorflow-text-generation/54210177#54210177 Multinomial was renamed to categorical in the newer builds of tensorflow (ergo need to tweak that answer?)?

**Comment by ymodak** [comment]
[tf.random.multinomial](https://github.com/tensorflow/tensorflow/blob/9f30ec59fda6e9134dff2c7d9cc42b3fb455f8b7/tensorflow/python/ops/random_ops.py#L330) will be deprecated starting from TF 1.13rc0
Closing this issue since the work around will be to use tf.random.multinomial if using TF 1.12 or lower. Thanks!
