### ISSUE TITLE
Why compiling tensorflow from source failed which every step was done successfully as in the documentation, in both Windows 10 and Ubuntu

### ISSUE THREAD

**Issue by Bahramudin** [tensorflow/tensorflow#24958]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64Bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 1.12
- Python version: 3.6
- Installed using virtualenv? pip? conda?: 
- Bazel version (if compiling from source): 0.18.0, 0.16. 0.21.0
- GCC/Compiler version (if compiling from source): 7.4, 5.4
- CUDA/cuDNN version: 10.0, 7.4.2
- GPU model and memory: GTX 1080 16GB

**Describe the problem**

I have tried the steps on the official site, and many more tutorials, but it was unable to build successfully.

every time almost throw new kind of error. this is the last error:

> 1 error detected in the compilation of "C:/Users/adil/AppData/Local/Temp/nvcc_inter_files_tmp_dir/eye_functor_gpu.cu.cpp1.ii".
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> INFO: Elapsed time: 171.890s, Critical Path: 58.48s
> INFO: 698 processes: 698 local.
> FAILED: Build did NOT complete successfully

everything installed correctly. 

I think there are a lot of bugs with tensorflow which let me dislike this framework, very hard to compile and also very hard to get the environment ready, it relays on a lot of third party tools which leads sometimes the versions miss match, and also it is long time which Cuda 10 has been come out, but the tf still using 9.0, the same with visual studio 2015 which now it is a long time that people using 2017. Everything that is used in tf is very old, which some user must uninstall their new version and install the older one. Tensorflow must consider this problem to be compatible with new tools and systems.

I am waiting when tf start to support cuda 10?

**Comment by yinguobing** [comment]
I guess the documentation needs to be updated. Try building version 1.11 with CUDA 10.

**Comment by ymodak** [comment]
@Bahramudin We appreciate your interest in using TF framework. TF 1.13.rc1 has released and it supports cuda 10. Please give it a try and let us know if you have any problems. Thanks!

**Comment by Bahramudin** [comment]
@ymodak TF 1.13 not released. When I try 
`pip install --upgrade tensorflow-gpu`
It is the output:

> Requirement already up-to-date: tensorflow-gpu in c:\users\adil\anaconda3\envs\tf\lib\site-packages (1.12.0)

**Comment by ymodak** [comment]
The official TF 1.13 is not released. However you can try,
> pip install tensorflow-gpu==1.13.0-rc2

**Comment by Bahramudin** [comment]
@ymodak OK, then I will wait until it officially released. For now, I am using 1.12

**Comment by ymodak** [comment]
Closing this issue for now. Thanks!
