### ISSUE TITLE
fatal error LNK1120, LNK2019, LNK2001

### ISSUE THREAD

**Issue by jesen8** [tensorflow/tensorflow#24955]
**System information**
- OS Platform and Distribution :    windows 10
- TensorFlow installed from :          source
- TensorFlow version:                     r1.12
- Python version:                            3.5.4
- Installed using :                            exe
- Bazel version :                               0.15.0
- CUDA/cuDNN version:                 10.0, 7.3
- GPU model and memory:             gtx1080ti

after i change the patch from [Aleksandr Sokolovskii's blog](https://medium.com/@amsokol.com/update-1-how-to-build-and-install-tensorflow-gpu-cpu-for-windows-from-source-code-using-bazel-and-c2e86fec9ef2) for modify eigen's error.
and add three lines code from this [#23655](https://github.com/tensorflow/tensorflow/issues/23655) issues of cielavenir's description ,
last ,i run " bazel build --config=opt --config=cuda --config=monolithic //tensorflow:libtensorflow_cc.so" ,at last,i get the below error:

INFO: From Linking tensorflow/core/liblib_internal_impl.a:
android_armv7a_cpu_utils_helper.o : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
random_distributions.o : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
INFO: From Linking tensorflow/libtensorflow_framework.so:
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/lib64'; ignored
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64'; ignored
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/liblibtensorflow_framework.so.ifso and object bazel-out/x64_windows-opt/bin/tensorflow/liblibtensorflow_framework.so.exp
libcuda_platform.lo(cuda_dnn.o) : warning LNK4217: locally defined symbol ?ThenBlasGemm@Stream@stream_executor@@QEAAAEAV12@W4Transpose@blas@2@0_K11MAEBV?$DeviceMemory@M@2@H2HMPEAV52@H@Z (public: class stream_executor::Stream & __cdecl stream_executor::Stream::ThenBlasGemm(enum stream_executor::blas::Transpose,enum stream_executor::blas::Transpose,unsigned __int64,unsigned __int64,unsigned __int64,float,class stream_executor::DeviceMemory<float> const &,int,class stream_executor::DeviceMemory<float> const &,int,float,class stream_executor::DeviceMemory<float> *,int)) imported in function "public: virtual bool __cdecl stream_executor::cuda::CudnnSupport::DoMatMul(class stream_executor::Stream *,class stream_executor::DeviceMemory<float> const &,class stream_executor::DeviceMemory<float> const &,class stream_executor::dnn::BatchDescriptor const &,class stream_executor::dnn::BatchDescriptor const &,class stream_executor::DeviceMemory<float> *)" (?DoMatMul@CudnnSupport@cuda@stream_executor@@UEAA_NPEAVStream@3@AEBV?$DeviceMemory@M@3@1AEBVBatchDescriptor@dnn@3@2PEAV53@@Z)
ERROR: D:/tf3/tensorflow-r1.12/tensorflow/cc/BUILD:456:1: Linking of rule '//tensorflow/cc:ops/math_ops_gen_cc' failed (Exit 1120): link.exe failed: error executing command
  cd C:/users/swls/_bazel_swls/5dz6uozl/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Python35/python.exe
    SET PYTHON_LIB_PATH=C:/Python35/libs/python35.lib
    SET TEMP=C:\Users\swls\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=6.1
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\swls\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/link.exe /nologo /OUT:bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/math_ops_gen_cc /SUBSYSTEM:CONSOLE -Wl,-rpath,../local_config_cuda/cuda/lib64 -Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64 /MACHINE:X64 @bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/math_ops_gen_cc-2.params
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/lib64'; ignored
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64'; ignored
libmath_ops_op_lib.lo(math_ops.o) : error LNK2019: unresolved external symbol "public: __cdecl tensorflow::internal::LogMessageFatal::LogMessageFatal(char const *,int)" (??0LogMessageFatal@internal@tensorflow@@QEAA@PEBDH@Z) referenced in function "public: static class tensorflow::shape_inference::DimensionHandle __cdecl tensorflow::shape_inference::InferenceContext::DimKnownRank(class tensorflow::shape_inference::ShapeHandle,__int64)" (?DimKnownRank@InferenceContext@shape_inference@tensorflow@@SA?AVDimensionHandle@23@VShapeHandle@23@_J@Z)
libcc_op_gen_main.a(cc_op_gen_main.o) : error LNK2001: unresolved external symbol "public: __cdecl tensorflow::internal::LogMessageFatal::LogMessageFatal(char const *,int)" (??0LogMessageFatal@internal@tensorflow@@QEAA@PEBDH@Z)
libcc_op_gen_main.a(cc_op_gen.o) : error LNK2001: unresolved external symbol "public: __cdecl tensorflow::internal::LogMessageFatal::LogMessageFatal(char const *,int)" (??0LogMessageFatal@internal@tensorflow@@QEAA@PEBDH@Z)
libop_gen_lib.a(op_gen_lib.o) : error LNK2001: unresolved external symbol "public: __cdecl tensorflow::internal::LogMessageFatal::LogMessageFatal(char const *,int)" (??0LogMessageFatal@internal@tensorflow@@QEAA@PEBDH@Z)
libmath_ops_op_lib.lo(math_ops.o) : error LNK2019: unresolved external symbol "public: virtual __cdecl tensorflow::internal::LogMessageFatal::~LogMessageFatal(void)" (??1LogMessageFatal@internal@tensorflow@@UEAA@XZ) referenced in function "public: void __cdecl tensorflow::internal::LogMessageFatal::`vbase destructor'(void)" (??_DLogMessageFatal@internal@tensorflow@@QEAAXXZ)
libcc_op_gen_main.a(cc_op_gen_main.o) : error LNK2001: unresolved external symbol "public: virtual __cdecl tensorflow::internal::LogMessageFatal::~LogMessageFatal(void)" (??1LogMessageFatal@internal@tensorflow@@UEAA@XZ)
libcc_op_gen_main.a(cc_op_gen.o) : error LNK2001: unresolved external symbol "public: virtual __cdecl tensorflow::internal::LogMessageFatal::~LogMessageFatal(void)" (??1LogMessageFatal@internal@tensorflow@@UEAA@XZ)
libop_gen_lib.a(op_gen_lib.o) : error LNK2001: unresolved external symbol "public: virtual __cdecl tensorflow::internal::LogMessageFatal::~LogMessageFatal(void)" (??1LogMessageFatal@internal@tensorflow@@UEAA@XZ)
libmath_ops_op_lib.lo(math_ops.o) : error LNK2019: unresolved external symbol "public: __cdecl tensorflow::internal::CheckOpMessageBuilder::CheckOpMessageBuilder(char const *)" (??0CheckOpMessageBuilder@internal@tensorflow@@QEAA@PEBD@Z) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl tensorflow::internal::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@internal@tensorflow@@YAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBH0PEBD@Z)
libcc_op_gen_main.a(cc_op_gen.o) : error LNK2001: unresolved external symbol "public: __cdecl tensorflow::internal::CheckOpMessageBuilder::CheckOpMessageBuilder(char const *)" (??0CheckOpMessageBuilder@internal@tensorflow@@QEAA@PEBD@Z)
libop_gen_lib.a(op_gen_lib.o) : error LNK2001: unresolved external symbol "public: __cdecl tensorflow::internal::CheckOpMessageBuilder::CheckOpMessageBuilder(char const *)" (??0CheckOpMessageBuilder@internal@tensorflow@@QEAA@PEBD@Z)
libmath_ops_op_lib.lo(math_ops.o) : error LNK2019: unresolved external symbol "public: __cdecl tensorflow::internal::CheckOpMessageBuilder::~CheckOpMessageBuilder(void)" (??1CheckOpMessageBuilder@internal@tensorflow@@QEAA@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl tensorflow::internal::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@internal@tensorflow@@YAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBH0PEBD@Z)
libcc_op_gen_main.a(cc_op_gen.o) : error LNK2001: unresolved external symbol "public: __cdecl tensorflow::internal::CheckOpMessageBuilder::~CheckOpMessageBuilder(void)" (??1CheckOpMessageBuilder@internal@tensorflow@@QEAA@XZ)
libop_gen_lib.a(op_gen_lib.o) : error LNK2001: unresolved external symbol "public: __cdecl tensorflow::internal::CheckOpMessageBuilder::~CheckOpMessageBuilder(void)" (??1CheckOpMessageBuilder@internal@tensorflow@@QEAA@XZ)
libmath_ops_op_lib.lo(math_ops.o) : error LNK2019: unresolved external symbol "public: class std::basic_ostream<char,struct std::char_traits<char> > * __cdecl tensorflow::internal::CheckOpMessageBuilder::ForVar2(void)" (?ForVar2@CheckOpMessageBuilder@internal@tensorflow@@QEAAPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl tensorflow::internal::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@internal@tensorflow@@YAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBH0PEBD@Z)
libcc_op_gen_main.a(cc_op_gen.o) : error LNK2001: unresolved external symbol "public: class std::basic_ostream<char,struct std::char_traits<char> > * __cdecl tensorflow::internal::CheckOpMessageBuilder::ForVar2(void)" (?ForVar2@CheckOpMessageBuilder@internal@tensorflow@@QEAAPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ)
......

libop_gen_lib.a(op_gen_lib.o) : error LNK2019: unresolved external symbol "bool __cdecl tensorflow::str_util::CUnescape(class absl::string_view,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?CUnescape@str_util@tensorflow@@YA_NVstring_view@absl@@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z) referenced in function "bool __cdecl tensorflow::ConvertLine(class absl::string_view,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?ConvertLine@tensorflow@@YA_NVstring_view@absl@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@5@@Z)
libop_gen_lib.a(op_gen_lib.o) : error LNK2019: unresolved external symbol "bool __cdecl tensorflow::str_util::ConsumePrefix(class absl::string_view *,class absl::string_view)" (?ConsumePrefix@str_util@tensorflow@@YA_NPEAVstring_view@absl@@V34@@Z) referenced in function "bool __cdecl tensorflow::ConsumeEquals(class absl::string_view *)" (?ConsumeEquals@tensorflow@@YA_NPEAVstring_view@absl@@@Z)
libop_gen_lib.a(op_gen_lib.o) : error LNK2019: unresolved external symbol "bool __cdecl tensorflow::str_util::EndsWith(class absl::string_view,class absl::string_view)" (?EndsWith@str_util@tensorflow@@YA_NVstring_view@absl@@0@Z) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl tensorflow::WordWrap(class absl::string_view,class absl::string_view,int)" (?WordWrap@tensorflow@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@Vstring_view@absl@@0H@Z)
libop_gen_lib.a(op_gen_lib.o) : error LNK2019: unresolved external symbol "public: static bool __cdecl google::protobuf::TextFormat::ParseFromString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class google::protobuf::Message *)" (?ParseFromString@TextFormat@protobuf@google@@SA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVMessage@23@@Z) referenced in function "public: class tensorflow::Status __cdecl tensorflow::ApiDefMap::LoadApiDef(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?LoadApiDef@ApiDefMap@tensorflow@@QEAA?AVStatus@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
libop_gen_lib.a(op_gen_lib.o) : error LNK2019: unresolved external symbol "class tensorflow::Status __cdecl tensorflow::ReadFileToString(class tensorflow::Env *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?ReadFileToString@tensorflow@@YA?AVStatus@1@PEAVEnv@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV45@@Z) referenced in function "public: class tensorflow::Status __cdecl tensorflow::ApiDefMap::LoadFile(class tensorflow::Env *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?LoadFile@ApiDefMap@tensorflow@@QEAA?AVStatus@2@PEAVEnv@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
libop_gen_lib.a(op_gen_lib.o) : error LNK2019: unresolved external symbol "class tensorflow::OpDef_AttrDefDefaultTypeInternal tensorflow::_OpDef_AttrDef_default_instance_" (?_OpDef_AttrDef_default_instance_@tensorflow@@3VOpDef_AttrDefDefaultTypeInternal@1@A) referenced in function "void __cdecl tensorflow::`anonymous namespace'::InitApiDefFromOpDef(class tensorflow::OpDef const &,class tensorflow::ApiDef *)" (?InitApiDefFromOpDef@?A0x86251cb0@tensorflow@@YAXAEBVOpDef@2@PEAVApiDef@2@@Z)
bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/math_ops_gen_cc : fatal error LNK1120: 119 unresolved externals
Target //tensorflow:libtensorflow_cc.so failed to build
INFO: Elapsed time: 2672.865s, Critical Path: 259.43s
INFO: 3296 processes: 3296 local.
FAILED: Build did NOT complete successfully

there is "fatal error LNK1120: 119 unresolved externals" errors,i think it must missing something,,,
is there anyone can help me? any response will appreciate!

**Comment by jesen8** [comment]
does there any one can help me?

**Comment by ymodak** [comment]
@jesen8 Apologies for the delay in response. (Correct me if I am wrong) I see that you are trying to install tf-gpu version with cuda 10. In that case you should try installing TF 1.13.0-rc0 as it comes with pre-built binaries for cuda 10. Let me know if that helps. Thanks!

**Comment by jesen8** [comment]
@ymodak ,thanks,i will take a try and will response you

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
