### ISSUE TITLE
tf.pad docstring is missing description of the "mode" argument

### ISSUE THREAD

**Issue by shoyer** [tensorflow/tensorflow#2496]
The docstring gives examples of using "CONSTANT", "REFLECT" and "SYMMETRIC" modes, but never describes what they actually are.

For example:
- What value is used to pad in constant mode? (The answer is 0.)
- What exactly is the difference between REFLECT and SYMMETRIC? (I don't know.)

**Comment by vrv** [comment]
Cool, thanks for the report.  http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.pad.html is I think where we get these names from -- do you want to send us a PR to fix this?

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py#L922 would be where to add the documentation.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
