### ISSUE TITLE
What input pre-processing is required for TensorFlow Lite pre-trained models

### ISSUE THREAD

**Issue by cumberb1tch** [tensorflow/tensorflow#24966]
TensorFlow Lite framework has some pre-trained models here https://www.tensorflow.org/lite/models

How do I know what pre-processing to input of the network is needed? (scale, mean values)
I'm talking about .pb file with FakeQuant* operation.
I need this to understand where those `min` and `max` parameters of FakeQuant* operation trained with pre-processing or not 

Thank you for your answer!

**Comment by suharshs** [comment]
lol, nice username :)

The tensorflow model (.pb) with FakeQuant ops requires the same preprocessing as the normal float model. So for the image models that is normal inception_preprocessing in the range [0.0f, 1.0f]: https://github.com/tensorflow/models/blob/master/research/slim/preprocessing/inception_preprocessing.py#L256

Some extra info:

The actually quantized uint8 tflite model expects uint8 inputs from [0, 255]. Tensorflow Lite requires information on how that maps to the float [0.0, 1.0] values. These are the std_values and mean_values flags. They can be set using the following.

mean_value = the uint8 value that corresponds to floating point 0.0f. In this case the value is 0.
std_value = The number of uint8 values between 0.0 to 1.0. AKA integer range / float range.

Hope that helps!
