### ISSUE TITLE
Change target name of tensorflow.dll in cmake installation

### ISSUE THREAD

**Issue by Rayndell** [tensorflow/tensorflow#24964]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.8
- Python version: 3.6.3
- Installed using virtualenv? pip? conda?: cmake
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): Visual Studio 2015
- CUDA/cuDNN version: 9.0/7.0
- GPU model and memory: GeForce GTX 1080 Ti (11 GB)

**Describe the problem**

I am trying to build two different versions of TensorFlow 1.8 (one with GPU support and one without). Even if it is deprecated, I use the cmake installation since I had a lot of troubles with bazel. And the cmake installation allows to directly build a shared library as well as a tensorflo.dll file, which suits our need for integration in our applications in Windows.

However, the two versions (with or without GPU) output a dll with the same name (tensorflow.dll), and we will need to have the two different dlls in our applications. I was searching for a way to change the target name (tensorfflow_cpu.dll and tensorflow_gpu.dll for instance), is it possible? I already tried to change the target name in the Visual Studio projet (i.e. tensorflow), but the .lib seems to always reference tensorflow.dll.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sanjoy** [comment]
Closing out this issue because it hasn't been updated in the last year.  Please reopen if this is still relevant.
