### ISSUE TITLE
Support model.fit using targets in a dictionary

### ISSUE THREAD

**Issue by ZackHodari** [tensorflow/tensorflow#24962]
This feature relates to the TensorFlow implementation of the Keras API, specifically relating to the use of `model.fit`
Supporting this feature will improve the simplicity of the use case with TFRecord and multi-task problems (or multiple output streams)

**System information**
- TensorFlow version (you are using): 1.12.0
- Are you willing to contribute it (Yes/No): Yes (if my suggested implementation is sufficient)

**Describe the feature and the current behavior/state.**
Currently `model.fit` supports tensor/list/dict for the inputs `x`, but a dictionary cannot be used for the labels `y`.

**Will this change the current api? How?**
The API will not change, and it will more closely represent the underlying Keras API https://keras.io/models/model/#fit
"y: Numpy array of target (label) data (if the model has a single output), or list of Numpy arrays (if the model has multiple outputs). If output layers in the model are named, you can also pass a dictionary mapping output names to Numpy arrays"

**Who will benefit with this feature?**
Users with multi-task learning problems (or problems with multiple output steams)
Implementations using protos (tf.Example or tf.SequenceExample) and/or TFRecord
Implementations using tf.data.Dataset

**Any Other info.**
As per the handling of `inputs` in [`training_arrays._prepare_feed_values`](https://github.com/tensorflow/tensorflow/blob/aeddcb55fadc0ad9085d71d736ba49c6b69620bf/tensorflow/python/keras/engine/training_arrays.py#L389), we can change [line 429](https://github.com/tensorflow/tensorflow/blob/aeddcb55fadc0ad9085d71d736ba49c6b69620bf/tensorflow/python/keras/engine/training_arrays.py#L429) to the following
```
targets = training_utils.ModelInputs(targets).as_list()
```

If this solution is valid, it may be appropriate to modify [`training_utils.ModelInputs`](https://github.com/tensorflow/tensorflow/blob/aeddcb55fadc0ad9085d71d736ba49c6b69620bf/tensorflow/python/keras/engine/training_utils.py#L1306), either with an abstract `ModelTensors` class, or with a refactored `ModelInputs` class that does not use the word "inputs".

**Comment by hadim** [comment]
Once addressed this issue would allow this kind of code:

```python
import tensorflow as tf

dataset = tf.data.Dataset.from_tensor_slices(dict(x=inputs, y=outputs))
model = tf.keras.Model()
model.compile()
model.fit(dataset)
```

Currently, the above fails with:

```
ValueError: Output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: {'x': <tf.Tensor: id=3235, shape=(2, 1), dtype=float32, numpy=
array([[6.],
       [7.]], dtype=float32)>, 'y': <tf.Tensor: id=3236, shape=(2, 5), dtype=float32, numpy=
array([[30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.]], dtype=float32)>}
```

**Comment by omalleyt12** [comment]
There would be ambiguity in doing this, as it's perfectly valid for users to have inputs named `y`.

Instead, `targets` should be the second element of a tuple when using datasets. I believe that element can be a dict

**Comment by hadim** [comment]
So the only way to pass Dataset to `fit()` would be with a tuple of length 2. The first element will **always** be inputs and the second element will **always** be outputs (targets). Both can be Tensor objects or dict of tensors (or list of tensors)?

If it's already what TF 2.0 assume then I guess I am all good :-)

**Comment by hadim** [comment]
I just tested the following on TF2.0:

```python
def make_dataset(images, labels, batch_size=64, buffer_size=1024, shuffle=True):
    inputs = dict(images=images)
    outputs = dict(labels=labels)
    dataset = tf.data.Dataset.from_tensor_slices((inputs, outputs))
    if shuffle:
        dataset = dataset.shuffle(buffer_size=buffer_size)
    dataset = dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
    dataset = dataset.map(map_func=normalize_fn, num_parallel_calls=8)
    dataset = dataset.batch(batch_size)
    return dataset
```

(I use single Tensor input/output here but it's only for illustration)

And after adding the correct names in my Keras model, everything works like a charm:

```python
model.add(tf.keras.Input(shape=(28, 28, 1), name='images'))
# ...
model.add(tf.keras.layers.Dense(10, activation='softmax', name='labels'))
```

**Comment by hadim** [comment]
(I guess you can close here)
