### ISSUE TITLE
"Upgrade to Tensorflow 2.0" documentation lists wrong TF version

### ISSUE THREAD

**Issue by Matt-Hicks-Bose** [tensorflow/tensorflow#24977]
**System information**
- TensorFlow version: 1.12
- Doc Link: https://github.com/tensorflow/docs/blob/master/site/en/r2/guide/upgrade.md

**Describe the documentation issue**
The document says that `Note: tf_upgrade_v2 is installed automatically by pip install for TensorFlow 1.12 and later.` but looking at the setup.py files this console command is not installed by 1.12, but will be installed in 1.13

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
No

**Comment by martinwicke** [comment]
This has been fixed.
