### ISSUE TITLE
tflite 0.0.0-gpu-experimental still long interference time

### ISSUE THREAD

**Issue by wosiu** [tensorflow/tensorflow#24972]
I tested tflite 0.0.0-gpu-experimental on Android.
Comparing to version 1.12.0, the speed up is quite poor.
Average of total interference time on the devices I tested:

device | Android v | tflite 1.12.0 time | tflite gpu exp time
--------- | ------------ | --------------------- | ------------------------
Huawei p10 lite (was-lx1) | 7.0, API 24 | ~651ms | ~605ms
LGE LG-M200 | 7.0, API 24 | ~1207ms | ~1390ms
Sony Xperia M5 (e5603) | 6.0, API 23 | ~690ms | ~609ms
Xiaomi Redmi 3 | 5.1.1, API 22 | ~942ms | ~800ms
Alcatel TCL 5033D | 8.1.0, API 27 | ~1128ms |  ~1032ms

whereas for the same model on CoreML (iOS platform) it takes much less on an old iPhone.

**Comment by aselle** [comment]
Could you elaborate on what model and what ops you are using in the model. Also, have you tried tflite on iOS?

**Comment by wosiu** [comment]
I'm using mostly conv2d. Indeed I did not anable the delegate in the code.
> "Trying the GPU Delegate on your own model"
> in https://www.tensorflow.org/lite/performance/gpu
After adding `GpuDelegate` it seems to "work".
By "work" I mean I get an exception about  `op code #55 cannot be handled by this delegate...`, but this is no longer a case for this ticket, so I'm closing this one.
Thank you!
