### ISSUE TITLE
Setting up TensorFlow for Development broken on Linux

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#2497]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md

TLDR;
instead of
`ln -s ../bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/* .
`
I had to do
`ln -s ../bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/__main__/* .
`
Ubuntu 15.04, bazel-0.2.3, week-old TensorFlow from head

On MacOS, Bazel 0.2.1-homebrew, the command that works is `ln -s ../bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/* .`

**Comment by vrv** [comment]
cc @kchodorow

**Comment by yaroslavvb** [comment]
Oops, I guess a week-old version is too old. I just synced to head and now the instructions are current

**Comment by kchodorow** [comment]
Ugh, this is inconvenient:

* Bazel 0.2.1 and lower, any TF: the path will be `build_pip_package.runfiles/*`
* Bazel 0.2.2 with TensorFlow before 32fa42a98eb751ee05827535ac47535312b7fa76: `build_pip_package.runfiles/*`
* Bazel 0.2.2, TF after 32fa42a98eb751ee05827535ac47535312b7fa76: `build_pip_package.runfiles/org_tensorflow/*`.
* Bazel 0.2.3, TF before 32fa42a98eb751ee05827535ac47535312b7fa76: `build_pip_package.runfiles/__main__/*`
* Bazel 0.2.3, TF after 32fa42a98eb751ee05827535ac47535312b7fa76: `build_pip_package.runfiles/org_tensorflow/*`

**Comment by yaroslavvb** [comment]
@kchodorow btw, perhaps related, at HEAD I'm seeing following ominous-looking warnings
```

WARNING: /home/yaroslavvb/.cache/bazel/_bazel_yaroslavvb/4361dd5b218cfc4553165f848068d48a/external/highwayhash/WORKSPACE:1: Workspace name in /home/yaroslavvb/.cache/bazel/_bazel_yaroslavvb/4361dd5b218cfc4553165f848068d48a/external/highwayhash/WORKSPACE (@__main__) does not match the name given in the repository's definition (@highwayhash); this will cause a build error in future versions.
WARNING: /home/yaroslavvb/.cache/bazel/_bazel_yaroslavvb/4361dd5b218cfc4553165f848068d48a/external/re2/WORKSPACE:1: Workspace name in /home/yaroslavvb/.cache/bazel/_bazel_yaroslavvb/4361dd5b218cfc4553165f848068d48a/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.

```

**Comment by yaroslavvb** [comment]
BTW, current instructions for latest bazel are a slightly broken:
`ln -s ../bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow* .
`

It should say
`ln -s ../bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/* .`

**Comment by vrv** [comment]
Send a PR to fix?
