### ISSUE TITLE
Unable to install tensorflow 2.0 nightly for python 3.4

### ISSUE THREAD

**Issue by dibya001** [tensorflow/tensorflow#24984]
OS version: Ubuntu 14.04
When I run I get the below output
 pip install tf-nightly-2.0-preview
Collecting tf-nightly-2.0-preview
  Could not find a version that satisfies the requirement tf-nightly-2.0-preview (from versions: )
No matching distribution found for tf-nightly-2.0-preview

**Comment by alanpurple** [comment]
you can use python 3.6

3.4 is outdated and deprecated version

**Comment by jvishnuvardhan** [comment]
@dibya001  Did you try pip install tf-nightly? Thanks!

**Comment by jvishnuvardhan** [comment]
@dibya001 Could you try the [solution](https://github.com/tensorflow/tensorflow/issues/24886) provided here. Please let us know how it progresses. Thanks!

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. Please open new ticket if you see similar issue again. Thanks!
