### ISSUE TITLE
how to flatten a tensor in block-wise

### ISSUE THREAD

**Issue by nounotabe** [tensorflow/tensorflow#24985]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version : 1.12
- Are you willing to contribute it : Yes

**Describe the feature and the current behavior/state.**
A is a tensor with shape `[n,h,w,block_size*block_size]`. I hope to flatten it into `[n,h*block_size,w*block_size,1]`. In Numpy, this can be implemented by:
```python
import numpy as np
A = np.ones((1,2,2,4))
A_flat= np.zeros((1,4,4,1))
block_size = 2
for n in range(A.shape[0]):
    for h in range(A.shape[1]):
        for w in range(A.shape[2]):
            A_flat[n:n+1, h*block_size:(h+1)*block_size, w*block_size:(w+1)*block_size, 0:1] \
                = A[n:n+1, h:h+1, w:w+1, :].reshape(1, block_size, block_size, 1)
```
How can i do it using tensorflow if these functions exist?

**Will this change the current api? How?**
No
**Who will benefit with this feature?**
Some researchers of image processing
**Any Other info.**

**Comment by ppwwyyxx** [comment]
`tf.nn.depth_to_space` does what you want.

**Comment by nounotabe** [comment]
@ppwwyyxx Thank you!
