### ISSUE TITLE
Enable reference code of kernels(internal) in TF-Lite

### ISSUE THREAD

**Issue by babuya7** [tensorflow/tensorflow#24982]
Hi,
I want to benchmark the model based on reference code and Neon optimized code for kernels.So that I  want to enable the reference code implementation while executing the Tensorflow Lite model.

Is there is any way to run reference code ?
I tried to make changes in build file but there is some compilation issues.
Thanks and Regards,
Amar kumar

**Comment by Saduf2019** [comment]
@babuya7 
Could you please try on latest stable version of tf and let us know if this is still an issue.Thanks!
