### ISSUE TITLE
how to use tensorflow read a image from remote hdfs cluster

### ISSUE THREAD

**Issue by lighTQ** [tensorflow/tensorflow#24988]
I need to read the image dataset directly from HDFS and use the tensorflow related API for preprocessing, but according to the official website's tensorflow and HDFS API, I did not get a specific answer. So can explain, for example: how to use the tensorflow related API to read a picture from HDFS and open it with other libraries.

**Comment by jvishnuvardhan** [comment]
@lighTQ Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support. Github is mainly for addressing bugs in installation and performance. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing the issue. Please post support related questions in StackOverflow. We encourage users to submit an issue/feature request here. Thanks!
