### ISSUE TITLE
TFLite GPU Delegate error Initializing

### ISSUE THREAD

**Issue by lcycoding** [tensorflow/tensorflow#24986]
Dear Tensorflow developers,

After trying out the gpu-delegate demo on Android, I reimplemented in my app to try it out on my own model.

My model is the stripped ssd as the official tflite file did.
At the interpreter initialization stage, the gpu delegate seems not working.
On logcat I saw : `Failed to apply delegate: GpuDelegate Prepare: Node is already a consumer of the valueNode number 77 (GpuDelegate) failed to prepare.`

But it worked fine on the official mobilenet-ssd model.

What does this error message suppose to mean?
Or is there anything I need to be careful on TFLite converting?
Anything would be helpful.
Thanks!

**Comment by impjdi** [comment]
Thanks for trying out the GPU delegate.

The GPU delegate re-interprets the TFLite model in the form that is suitable for GPU and does some additional check.  During this check, it must have determined that a consumer-producer pair is present twice.  Probably you have a use case we haven't seen before.  Would it be possible for us to take a look at your model?

**Comment by lcycoding** [comment]
@impjdi 
Thanks for your reply!
I'll need to have my superior's consent to show you the model.

But I have few more questions...
1. In GPU delegate initiation process, what did the interpreter actually do?
    Is there another shader program running behind the app?
    My app's pipeline have its own shader code, changing into proper initialized tflite code will get it hanged.
2. If so, is there any possible solution to avoid these GL conflicts?

Thanks in advance!

**Comment by impjdi** [comment]
@lcycoding 
If network weights etc. are of your concern, you can also send me the network architecture pre-training, if that makes the decision easier :)

1. This is an internal that may change, but roughly, the following happens:
- When you call NewGpuDelegate(), a very simple bookkeeping object is created.
- Then when you call interpreter->ModifyGraphWithDelegate, the GPU backend inspects your TFLite graph def and tells the TFLite framework which ops it can handle and which it can't.  Based on this, TFLite CPU and GPU communicate which parts should be handled by the CPU and which parts by the GPU.
- Then, the GPU backend reshapes the subgraph that it is supposed to handle to a more GPU-friendly form with some optimizations.  After this restructuring, we decide which shader programs need to be prepared and compiled.  When all of these are compiled, the GPU backend is ready.
- Of course, I understand that you are using the Java interface (based on the log you pasted), but these C++ functions are called through JNI.

2. It is okay for you to run other shader code.  What you need to be aware is to keep the GL context consistent.  I will help you if you run into other GL related conflicts, but let's resolve the network issue first :)

**Comment by lcycoding** [comment]
@impjdi 
Here I come again.

We decided to solve our pipeline's issue first since our model might still be changing.

So here's the condition now...
Our pipeline captures frame with GL compute shader and do lots of preprocessing.
In origin pipeline, we pulled out the bitmap from GPU and transform into bytebuffer then do the inference things with quantized tflite model.

Last week, I changed the inference part with GPU delegate mode with properly initialized model ( here I have tried official mobilenet ssd and mobilenet classifier on gpu tutorial page)
The initialize part works great, doesn't come up with any error code.
But right after the program run into `interpreter.runMultipleInputsOutputs` part, my thread stucked...
I looked into Trace these days, it just stucked at `Tensor<init>` method.

Note: Here I didn't use any input/output buffer techniques in advanced GPU tutorial.

Does gpu-experimental have any debug mode to figure out why my inference thread stucked?

Really appreciated for your help. 👍

**Comment by impjdi** [comment]
@lcycoding 

Sorry for the late reply.  Somehow didn't get the email from github directly. :(

> We decided to solve our pipeline's issue first since our model might still be changing.

Sounds good to me.  Please let us know if you run into the issue again.  It could be a toco issue or GPU BE issue, so anything that will let us reproduce the issue would be great.

> But right after the program run into interpreter.runMultipleInputsOutputs part, my thread stucked...

I have to admit I'm not super familiar with TFLite's Java interfaces, but looks like `interpreter.runForMultipleInputsOutputs` does a lot of things.  For starters, can you comment out the input / output tensor `ByteBuffer` thing for now, i.e. leave input tensors uninitialized, and just call `interpreter.run` instead of `interpreter.runForMultipleInputsOutputs`?  If that works, you know the GPU backend is working fine, but it's somewhere in the method that is waiting for additional action to happen.

**Comment by impjdi** [comment]
@lcycoding 
A couple of things to check:
1. Is the model the float model or the quantized model?  GPU backend only supports float.
2. Is the input tensor in float or in uint8?  In other words, if you have the input tensor of size [1, 224, 224, 3], are you feeding 1x224x224x3 bytes or 1x224x224x3xsizeof(float) bytes?

**Comment by impjdi** [comment]
@Icycoding

Thanks for checking!

1. This was expected, because we would have blown up if non-float model.
2. I was hoping that it would be this issue, but looks like that's not the case.  Let me get back to you tomorrow probably with an example for sanity check.

Out of curiosity, what phone are you using?

**Comment by lcycoding** [comment]
@impjdi 
Thanks for your promptly reply!

I've been testing these codes on Mi A2 and Redmi note3.

I think I'll try other compatible phones out today, and also iOS devices 👍 

See you tomorrow, have a good day!

**Comment by impjdi** [comment]
@lcycoding 

According to a quick web search, Mi A2 and Redmi Note 3, they seem to have Adreno 512 and Adreno 510, respectively.  And according to these:

https://www.notebookcheck.net/Qualcomm-Adreno-510.169537.0.html
https://www.notebookcheck.net/Qualcomm-Adreno-512-GPU.299840.0.html

it looks like they both support OpenGL ES 3.1.  So theoretically, they should work.  We don't have any Adreno 510 & 512 devices around, but I'll to find something close and report back.

**Comment by lcycoding** [comment]
Hi @impjdi,
About the hanging issue, I still have no clue where I can do the test.
It just hanged in my app's pipeline, any other demo apps works fine :(

Back to the initialization issue, I noticed that we might have a special use case in network.
Sorry, I still can't let you access our current model.
But please check the following structure code.
```
def resize(x):
  output_shape = [dim * multiple for dim, multiple in zip(x.shape,
                                                          [1, 2, 2, 1])]
  output = tf.concat([x, x], axis=3)
  output = tf.concat([output, output], axis=2)
  output = tf.reshape(
      output, (tf.shape(x) * [1, 2, 2, 1] if not x.shape.is_fully_defined() else
               output_shape))
  output.set_shape(output_shape)
  return output

net = conv2d(feature_map_x, z, 1)
net = resize(net)
net = net + feature_map_y
net_egl = resize(net)
net_egl = net_egl + feature_map_z
```
Basically replace resize_bilinear op to tf.concat steps since tflite doesn't support resize_bilinear
This is a work around we made few months ago. 
This works in normal (non-gpu delegate) mode and quantized mode.
I would say this might be an issue cause we ran into trouble when converting this graph into coreML model. We made another work around for coreML model though.
But I'm not fully understand the process in conversion steps to GPU-friendly model, so I can do nothing :(

If the above information is useful, please let me know 👍

**Comment by impjdi** [comment]
@lcycoding 

re: hanging: Yeah, I've been thinking what would be a barebones binary / source that will allow you to run.  It's not easy to send a binary over from my side... I might have some instructions soon.

re: initialization: I perfectly understand that you cannot disclose your network.  No worries.  The code looks alright to me.  Can you specify the shape / dimensions of everything?  TFLite and TFLite GPU both support resize bilinear.

**Comment by lcycoding** [comment]
@impjdi 
re: initialization:
The whole network's input shape is simple [1,256,256,3]
The shape of these resize blocks are just like making [1, 32, 32, 128] -> [1, 32, 32, 256] -> [1, 32, 64, 256] then reshape into [1, 64, 64, 128]
Is there any information I could provide?

Really appreciated for your help!

**Comment by lcycoding** [comment]
@impjdi 
After we resolved the initialization issue, I tried the same way to cut our model into pieces to test if there are certain Ops getting hanged.

Here are some results and assumptions.
`Conv2D`, `DepthwiseConv2D` are the most important computing node in deep learning models, and also the place hanging issue happen.
If I cut the model into only `tf.tile` or `tf.concat` part, the pipeline wouldn't get stuck. 
So I guess it would only hang on Conv-like operation on GPU.

Note: I've also tested on more devices, such as LG K10 and Shield TV. All of them were dead on this too :(

**Comment by impjdi** [comment]
@lcycoding 

Thanks for further bisecting it to find out the issue.  From what you describe, I suspect (and I might be completely wrong here) that we're trying to use a bigger workgroup size.  Unfortunately, the Java APIs do not print thing happening in the lower level.  Let me try something...

**Comment by lcycoding** [comment]
To all developers wants to migrate gpu delegate into your app:
1. Make sure single operation does not have repeated input source.
2. Make sure your init thread and inference thread are the same :P

Thanks to @impjdi for excellent answers!

**Comment by hvico** [comment]
Hello,

I am trying to adapt the [TFLite Object Detection demo](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android) to use the experimental GPU Delegate.

When I run this using CPU Delegate (inside TFLiteObjectDetectionAPIModel.java) :

tfLite.runForMultipleInputsOutputs(inputArray, outputMap);

I get this exception:

2019-06-09 19:04:05.837 32068-32124/org.tensorflow.lite.examples.detection E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 32068
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Next operations are not supported by GPU delegate:
    CUSTOM TFLite_Detection_PostProcess: Operation is not supported.
    First 98 operations will run on the GPU, and the remaining 1 on the CPU.TfLiteGpuDelegate Invoke: Delegate should run on the same thread where it was initialized.Node number 99 (TfLiteGpuDelegate) failed to invoke.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:149)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:215)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:219)

If I change .runForMultipleInputsOutputs by plan run (inputArray, outputMap) I get other exception:

2019-06-09 19:06:52.276 32472-32526/org.tensorflow.lite.examples.detection E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 32472
    java.lang.IllegalArgumentException: DataType error: cannot resolve DataType of [Ljava.lang.Object;
        at org.tensorflow.lite.Tensor.dataTypeOf(Tensor.java:199)
        at org.tensorflow.lite.Tensor.throwIfTypeIsIncompatible(Tensor.java:257)
        at org.tensorflow.lite.Tensor.getInputShapeIfDifferent(Tensor.java:162)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:132)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:249)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:215)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:219)
        at android.os.Handler.handleCallback(Handler.java:809)
        at android.os.Handler.dispatchMessage(Handler.java:102)

I've seen the code at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo

But it uses plan "run", not runForMultipleInputsOutputs.

Any suggestions? Thanks.
 

> @lcycoding
> 
> Sorry for the late reply. Somehow didn't get the email from github directly. :(
> 
> > We decided to solve our pipeline's issue first since our model might still be changing.
> 
> Sounds good to me. Please let us know if you run into the issue again. It could be a toco issue or GPU backend issue, so anything that will let us reproduce the issue would be great.
> 
> > But right after the program run into interpreter.runMultipleInputsOutputs part, my thread stucked...
> 
> I have to admit I'm not super familiar with TFLite's Java interfaces, but looks like `interpreter.runForMultipleInputsOutputs` does a lot of things. For starters, can you comment out the input / output tensor `ByteBuffer` thing for now, i.e. leave input tensors uninitialized, and just call `interpreter.run` instead of `interpreter.runForMultipleInputsOutputs`? If that works, you know the GPU backend is working fine, but it's somewhere in the method that is waiting for additional action to happen.

**Comment by aleksandrovych** [comment]
Here are some results and assumptions.
Conv2D, DepthwiseConv2D are the most important computing node in deep learning models, and also the place hanging issue happen.

Also have this problem for this command's @lcycoding could you share you solution please?

**Comment by lcycoding** [comment]
@aleksandrovych 
The hanging issue happens because of the inconsistency of the GL Thread.
Just make the initialize process and inference process working on the same thread will solve the problem.

**Comment by aleksandrovych** [comment]
thanks) @lcycoding

**Comment by tgpsantos** [comment]
Hi @lcycoding ! Is there any tutorial or example code on how to initialize and infer in the same thread? Thank you in advance

**Comment by lcycoding** [comment]
@tgpsantos 
Normal code structure will run on the same thread, just try it on your own.

**Comment by tgpsantos** [comment]
I tried to apply it to my own model following  I did try it by following the [tutorial provided by tensorflow](https://www.tensorflow.org/install/gpu) and I've got the following error.

`java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: TfLiteGpuDelegate Invoke: Delegate should run on the same thread where it was initialized.Node number 237 (TfLiteGpuDelegate) failed to invoke.
`

In [this guide](https://www.youtube.com/watch?v=Xkhgre8r5G0) it's also not mentioned how to work with the threads. I am new to Android and I never worked with threads, when I searched for this problem I actually ran into this issue and saw you mentioning the init and running thread being the same. I was hoping this could actually be an "easy" implementation

**Comment by lcycoding** [comment]
@tgpsantos 
Even with this whole package of demo app, it still run into this error?
If the project below does not show error, try to implement it in your way.
To work on threads, that's kind like java issue, not tensorflow-related.
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo

**Comment by yxchng** [comment]
@lcycoding @impjdi Why is repeated input source not allowed? Is there any good reason to not support it?

**Comment by impjdi** [comment]
@yxchng I forgot the details, but it's possible that it's not allowed, due to OpenGL restrictions.

**Comment by yxchng** [comment]
@impjdi In this post, you said resize_bilinear is supported. I just tested. It gives the correct output when align_corners=false but gives blank output when align_corners=true. Is this behavior expected?

**Comment by impjdi** [comment]
@yxchng Well, you can find out what's going on by reading the code.  `//tf/lite/delegates/gpu/gl/kernels/upsampling_bilinear.cc` apparently does not take `align_corners` into consideration which is a bug.  I would file a separate issue rather than piggybacking on this thread.

**Comment by sirius0503** [comment]
> To all developers wants to migrate gpu delegate into your app:
> 
> 1. Make sure single operation does not have repeated input source.
> 2. Make sure your init thread and inference thread are the same :P
> 
> Thanks to @impjdi for excellent answers!

@lcycoding : Can you explain, what you mean by repeated input source? I think I have used my input source `r1` which is an **input layer**, at two places, and whilst the code runs great on the python interpreter, it fails on android saying ` Unexpected failure when preparing tensor allocations: Next operations are not supported by GPU delegate:` giving a list of unsupported operations such as `L2_NORMALIZATION, MEAN, CONV2D` ,etc.

**Comment by lcycoding** [comment]
@sirius0503 
Hi there, the error message is not the same as the condition I mentioned here, I think you might have used some incompatible nodes in your graph.
You might want to check the whole graph with this tutorial https://www.tensorflow.org/lite/performance/gpu_advanced#supported_ops

Note that gpu delegate is more complicated than the normal graph working on python, if the implementation is not done yet, you'll not be able to run the graph in proper mode.

**Comment by sirius0503** [comment]
@lcycoding :  My full error log is as follows: 
```
java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: Next operations are not supported by GPU delegate:
2020-02-25 15:15:57.160 22863-22863/com.valuepitch.intruderdetector W/System.err: CONV_2D: Expected 1 input tensor(s), but node has 2 runtime input(s).
2020-02-25 15:15:57.161 22863-22863/com.valuepitch.intruderdetector W/System.err: CONV_2D: Expected 1 input tensor(s), but node has 3 runtime input(s).
2020-02-25 15:15:57.161 22863-22863/com.valuepitch.intruderdetector W/System.err: L2_NORMALIZATION: Operation is not supported.
2020-02-25 15:15:57.161 22863-22863/com.valuepitch.intruderdetector W/System.err: MEAN: Expected 1 input tensor(s), but node has 2 runtime input(s).
2020-02-25 15:15:57.161 22863-22863/com.valuepitch.intruderdetector W/System.err: SUM: Operation is not supported.
2020-02-25 15:15:57.162 22863-22863/com.valuepitch.intruderdetector W/System.err: TOPK_V2: Operation is not supported.
2020-02-25 15:15:57.162 22863-22863/com.valuepitch.intruderdetector W/System.err: First 0 operations will run on the GPU, and the remaining 186 on th
```
as I see in the link to supported ops for tensorflow gpu, CONV2D is supported, so the other **L2_Normalization,  MEAN, SUM and TOPK_V2 ** are not supported by tensorflow gpu delegate? Also, is **SUM, L2_Normalization, and TOPK_V2** not supported in tflite in general?

**Comment by lcycoding** [comment]
@sirius0503 
The reason why CONV2D is not supported is because it has more than 1 input tensor.
Other tensors are simply not supported yet.

**Comment by BalaVarun123** [comment]
> @aleksandrovych
> The hanging issue happens because of the inconsistency of the GL Thread.
> Just make the initialize process and inference process working on the same thread will solve the problem.

I did initialize and run Interpreter in the same AsyncTask thread. Still this error occurs:caused by: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: TfLiteGpuDelegate Init: ADD: Node 10 is already a consumer of the value 10
    TfLiteGpuDelegate Prepare: delegate is not initialized

**Comment by Feynman1999** [comment]
2021 now , tflite gpu delegate support sum op?
