### ISSUE TITLE
Chief exit without waiting other workers when distributed training with ParameterServerStrategy

### ISSUE THREAD

**Issue by legatoo** [tensorflow/tensorflow#24997]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):centos 7
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): compile using tags/v1.10.0
- Python version: 2.7
- Bazel version (if compiling from source): 0.15.0
- CUDA/cuDNN version: cuda 9.1/cuDNN 7

**Describe the current behavior**
I'm using `tf.Estimator.train_and_evaluate` API and trying to make it work in a distributed environment. According to the doc, the configuration should be simple: set correct TF_CONFIG and pass the DistributeStrategy. 

I have 1chief, 2worker, 1ps, 1evaluator, the training starts with no error, everything seems right, but the training does not stop correctly. Based on my observation, when the training data is not balanced distributed among workers and chief, more specific, when the chief has fewer data. it will exit without waiting other workers. I draw a picture to show the problem:

![xnip2019-01-21_18-33-16](https://user-images.githubusercontent.com/1506580/51469063-6275a100-1dab-11e9-94ef-5731357f5905.jpg)

**Describe the expected behavior**

because only the chief does the checkpoint, I think the chief must wait others finishing, otherwise the model is partially trained and evaluator will not stop.

**Code to reproduce the issue**
```
def create_estimator_and_specs(run_config):
    model_params = tf.contrib.training.HParams(
        batch_size=FLAGS.batch_size,
        learning_rate=FLAGS.learning_rate)

    estimator = tf.estimator.Estimator(
        model_fn=model_fn,
        config=run_config,
        params=model_params
    )

    train_spec = tf.estimator.TrainSpec(
        input_fn=generate_tfrecord_dataset(
            mode=tf.estimator.ModeKeys.TRAIN,
            directory="inputs",
            batch_size=FLAGS.batch_size,
            train_size=FLAGS.train_size,
            epoch=FLAGS.epoch),
        max_steps=FLAGS.max_steps
    )

    eval_spec = tf.estimator.EvalSpec(
        input_fn=generate_tfrecord_dataset(
            mode=tf.estimator.ModeKeys.EVAL,
            directory="inputs",
            batch_size=FLAGS.batch_size,
            train_size=FLAGS.eval_size,
            epoch=FLAGS.epoch),
        throttle_secs=FLAGS.checkpoint_secs
    )

    return estimator, train_spec, eval_spec


train_distribute = ParameterServerStrategy(num_gpus_per_worker=FLAGS.gpu_per_worker)
eval_distribute = MirroredStrategy(num_gpus_per_worker=FLAGS.gpu_per_worker,
                                   cross_tower_ops=cross_tower_ops_lib.AllReduceCrossTowerOps())
run_config = tf.estimator.RunConfig(
    model_dir=FLAGS.model_dir,
    save_checkpoints_secs=FLAGS.checkpoint_secs,
    save_summary_steps=FLAGS.summary_steps,
    keep_checkpoint_max=FLAGS.max_checkpoints,
    train_distribute=train_distribute,
    eval_distribute=eval_distribute)

estimator, train_spec, eval_spec = create_estimator_and_specs(run_config=run_config)
tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
```

TF_CONFIG:
```
chief node:
 {u'cluster': {
   u'ps': [u'ps:12615'], 
   u'chief': [u'chief:20396'], 
   u'worker': [u'worker1:18339', u'worker2:11609'], 
   u'evaluator': [u'evaluator:24352']
   }, 
   u'task': {u'index': 0, u'type': u'chief'}
 }

 woker 0:
 {u'cluster': {
   u'ps': [u'ps:12615'], 
   u'chief': [u'chief:20396'], 
   u'worker': [u'worker1:18339', u'worker2:11609'], 
   u'evaluator': [u'evaluator:24352']
   }, 
   u'task': {u'index': 0, u'type': u'worker'}
 }

 worker 1:
 {u'cluster': {
   u'ps': [u'ps:12615'], 
   u'chief': [u'chief:20396'], 
   u'worker': [u'worker1:18339', u'worker2:11609'],
   u'evaluator': [u'evaluator:24352']
   }, 
   u'task': {u'index': 1, u'type': u'worker'}
 }

evaluator:
{u'cluster': {
  u'ps': [u'ps:12615'], 
  u'chief': [u'chief:20396'], 
  u'worker': [u'worker1:18339', u'worker2:11609'],
  u'evaluator': [u'evaluator:24352']
  }, 
  u'task': {u'index': 0, u'type': u'evaluator'}
}
```

**Other info / logs**
log screenshot
![image](https://user-images.githubusercontent.com/1506580/51469382-3575be00-1dac-11e9-9dc7-9e183d3da095.png)

I did post [a stackoverflow question](https://stackoverflow.com/questions/54252279/estimator-api-training-data-is-unbalance-split-among-workers-chief-may-finish) but no response so far. Please help.

**Comment by legatoo** [comment]
@yuefengz sorry to trouble you, can you help?

**Comment by yuefengz** [comment]
If you make chief wait for other workers, you'll partially lose the benefit of async training which is fault-tolerance of workers. Could you just give chief more data to train?

**Comment by legatoo** [comment]
@yuefengz Thanks for your reply. I am confused about the stop condition also, please correct me.

In my case(data splited among workers), I noticed chief and workers are printing steps while training. In chief node,  it printed as global_step, in worker node, it printed as step.

1. Are these steps referring to the same thing? I mean, do these steps all get from param server, or just local step maintain by themselves?
2. In the `train_and_eval` api document, it says the only stop condition is `trainSpec.max_step` arrives.  So, which step is used to compare against max_step. the `global_step` or `woker_local_step`?

if there is a global_step and tensorflow use global_step against max_step to check stop condition, the chief won't quit earlier, and user can simply set `max_step` to `total_record_cnt/batch`. but based on my observation, none of the workers can reach `total_record_cnt/batch` then quit, because it not has enough data. So I am wondering that, each worker including chief are using local step for stop checking. Am I right? And we are using one `max_step` among unbalanced workers, it is not only early quit chief issue may happen, but also unutilized data？

**Comment by wangdejian** [comment]
problem reproduced in tf version 1.10.0,but no problem with 1.13.0, maybe it is a bug of tf version 1.10.0

**Comment by isaprykin** [comment]
Please re-open if the issue persists in newer versions of tensorflow.

**Comment by ttang235** [comment]
This problem still exists in tf 2.5 (chief exits before worker finishes)

You can verify this using the two files pasted at the end. 
1. Run `bash train.sh`
2. Run `ps aux | grep chief_exit`, and you will see processes for chief, worker, etc
3. Monitor the ~/chief_log and ~/worker_log, when ~/chief_log stops updating, Run `ps aux | grep chief_exit` again, and you will see the chief process is gone, while the worker process is still there.

Note: The worker trains on twice the amount of data of the chief, and that's why chief finishes first

model_chief_exit.py
```python
# -*- coding: utf-8 -*-
import os, json
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
from tensorflow.feature_column import categorical_column_with_hash_bucket, embedding_column
import argparse

tf.logging.set_verbosity(tf.logging.INFO)
parser = argparse.ArgumentParser()
parser.add_argument("-dr", "--distributed_role", help="specify destributed role, chief, evaluator, worker or ps", type=str, default="chief")
args = parser.parse_args()

os.environ["TF_CONFIG"] = json.dumps({
    "cluster": {
        "chief": ["localhost:15000"],
        "worker": ["localhost:15001"],
        "ps": ["localhost:15002"],
        "evaluator": ["localhost:15003"]
    },
    "task": {"type": args.distributed_role, "index": 0}
})

def input_fn():
    if args.distributed_role == 'worker':
        ds = tf.data.Dataset.range(10000000)
    else:
        ds = tf.data.Dataset.range(5000000)
    ds = ds.map(lambda x: ({'video_id':x}, x % 2)).batch(1024)
    return ds

if __name__ == '__main__':
    cat_column = categorical_column_with_hash_bucket('video_id', hash_bucket_size=400000, dtype=tf.int64)
    emb_column = embedding_column(cat_column, dimension=64, combiner='sum', use_safe_embedding_lookup=False)

    strategy = tf.distribute.experimental.ParameterServerStrategy()
    config = tf.estimator.RunConfig(
        save_checkpoints_steps=10000,
        train_distribute=strategy,
        eval_distribute=None
        )
    cls = tf.estimator.DNNClassifier(hidden_units=[512,256], feature_columns=[emb_column], model_dir="/tmp/model2/", config=config)

    train_spec = tf.estimator.TrainSpec(input_fn=input_fn)
    eval_spec = tf.estimator.EvalSpec(input_fn=input_fn)
    tf.estimator.train_and_evaluate(
        cls,
        train_spec,
        eval_spec
    )

```

train.sh
```bash
nohup python model_chief_exit.py -dr ps &> ~/ps_log &
nohup python model_chief_exit.py -dr worker &> ~/worker_log &
nohup python model_chief_exit.py -dr chief &> ~/chief_log &
nohup python model_chief_exit.py -dr evaluator &> ~/eval_log &
```
