### ISSUE TITLE
chief_training_hooks for TPUEstimatorSpec

### ISSUE THREAD

**Issue by patzm** [tensorflow/tensorflow#24999]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes, very much!

**Describe the feature and the current behavior/state.**
Currently, `training_chief_hooks` is not part of the [TPUEstimatorSpec API](https://www.tensorflow.org/api_docs/python/tf/contrib/tpu/TPUEstimatorSpec).
However I saw that they are indeed used, when wrapping the user-supplied `model_fn`:
https://github.com/tensorflow/tensorflow/blob/9331096d56002c7fcb8bae411684b8b78fc196c4/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py#L2755-L2764
From looking at the code, I feel it would be a doable task to extend it in this direction.
In my use-case, I would like to provide an additional, custom `CheckpointSaverHook`.

**Will this change the current api? How?**
yes, extend it:
``` python
TPUEstimatorSpec(
    mode,
    predictions=None,
    loss=None,
    train_op=None,
    eval_metrics=None,
    export_outputs=None,
    scaffold_fn=None,
    host_call=None,
    # new:
    training_chief_hooks=None,
    # end
    training_hooks=None,
    evaluation_hooks=None,
    prediction_hooks=None
)
```

**Who will benefit with this feature?**
Everyone using TPUs and being a bit frustrated that the API is more restrictive than for more general-purpose accelerators (e.g. GPUs).

**Any Other info.**
nope

**Comment by rjpower** [comment]
TPUEstimator uses in-graph replication with a single coordinator.

All hooks are executed on the coordinator node (your VM), so there's no distinction between chief hooks and non-chief hooks.

Feel free to re-open if there's a subtlety I missed here.

**Comment by patzm** [comment]
yes, I guess you are right. The reason behind this issue was the following:
I wanted to create a `CheckpointSaverHook` which uses a custom `Saver`. The `Estimator` API would check if a `CheckpointSaverHook` has already been created and supplied, and only create a default `CheckpointSaverHook` if no one was found. In the `TPUEstimator` API, the `CheckpointSaverHook` is created always.

But eventually I found out that the problem lies somewhere in my custom `Saver` and not the way the `TPUEstimator` deals with the hooks.
