### ISSUE TITLE
How to generate .pbtxt with .cc REGISTER_OP file

### ISSUE THREAD

**Issue by faciler** [tensorflow/tensorflow#24990]
I want to understand exactly  how user_ops generated,  and I found .cc .h op file 
can generated by .pbtxt ,but I'm not konw how to generate .pbtxt with .cc 
REGISTER_OP file .

**Comment by jvishnuvardhan** [comment]
Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support. Github is mainly for addressing bugs in installation and performance. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing the issue but please post this kind of support questions at Stackoverflow. Thanks!
