### ISSUE TITLE
ERROR: The 'test' command is only supported from within a workspace.

### ISSUE THREAD

**Issue by miguelmorin** [tensorflow/tensorflow#24993]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Ubuntu 16.04.5 LTS
- TensorFlow installed from: Docker image `tensorflow/tensorflow:nightly-devel-gpu`
- TensorFlow version: `master` branch
- Python version: 2 and 3
- Installed using: Docker

**Describe the problem**

I set up an Azure virtual machine with `Data Science Virtual Machine` on a `Standard NV6 (6 vcpus, 56 GB memory)`. I ssh into it, run these commands, and get the error in the title.

```
miguelmorin@ds-docker-gpu:~$ sudo docker pull tensorflow/tensorflow:nightly-devel-gpu
...
miguelmorin@ds-docker-gpu:~$ sudo docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
tensorflow/tensorflow   nightly-devel-gpu   abbaea1b533c        6 weeks ago         3.82GB
miguelmorin@ds-docker-gpu:~$ sudo docker run -it abbaea1b533c
root@fa1e7cf2c349:~# export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH"
root@fa1e7cf2c349:~# export flags="--config=opt --config=cuda -k"
root@fa1e7cf2c349:~# bazel test ${flags} //tensorflow/python/...
Extracting Bazel installation...
ERROR: The 'test' command is only supported from within a workspace.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
```

It also fails running the container with `nvidia-docker` instead of `docker`:

```
miguelmorin@ds-docker-gpu:~$ sudo nvidia-docker run -it abbaea1b533c
root@148ea4778aab:~# export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH"
root@148ea4778aab:~# 
root@148ea4778aab:~# export flags="--config=opt --config=cuda -k"
root@148ea4778aab:~# bazel test ${flags} //tensorflow/python/...
Extracting Bazel installation...
ERROR: The 'test' command is only supported from within a workspace.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
```

**Comment by angersson** [comment]
You need to change to the correct directory. As [the TF Docker Hub](https://hub.docker.com/r/tensorflow/tensorflow/) explains, TensorFlow's source code is in /tensorflow_src.
