### ISSUE TITLE
Tensorflow does not build in a python3

### ISSUE THREAD

**Issue by sonfiree** [tensorflow/tensorflow#24995]
**Ubuntu 18.04LTS** 
**TensorFlow installed from (source or binary):**
Source
**TensorFlow version (use command below):**
1.12.0
**Python version:**
3.6.7
**Bazel version (if compiling from source):**
0.19.0

**Source code / logs**

> ERROR: /home/sonfire/tensorflow/tensorflow/core/BUILD:2534:1: Executing genrule //tensorflow/core:version_info_gen failed (Exit 127)
> /usr/bin/env: 'python': No such file or directory
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 595.106s, Critical Path: 14.90s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
> INFO: 438 processes: 438 local.
> FAILED: Build did NOT complete successfully
> 

I don`t used env

**Comment by uranusx86** [comment]
make sure python path is in $PATH

and if you only have python3, link python3 to python by this command
`ln -s your_python_path /usr/local/bin/python`

**Comment by sonfiree** [comment]
I ran everything in env.
And it seems to be compiled already
