### ISSUE TITLE
Out-of-source builds

### ISSUE THREAD

**Issue by jyegerlehner** [tensorflow/tensorflow#250]
The build instructions have us run bazel such that all the build artifacts are dumped right in the source directory. So are we stuck creating a bunch of .gitignore rules? Seems barbaric when the usual approach is to avoid polluting source directory with build artifacts in the first place.

On behalf of all of us who don't know anything about bazel, I'll ask: does it not support out-of-source builds? I spent some time looking, and trying to do a bazel build from somewhere other than the source directory, and haven't had any luck.

**Comment by vrv** [comment]
We could add a .gitignore for "bazel-*" in the short term -- would that be palatable?

**Comment by jyegerlehner** [comment]
Thanks for the quick reply. 

I wouldn't go so far as "palatable". "Swallowable under duress" maybe. Here in the civilized world we usually use cmake. Which, by the way, can be parsed by qtcreator so we have a nice IDE in which to debug. What do you guys do, run gdb on the command line I guess?

**Comment by vrv** [comment]
De-duping with https://github.com/tensorflow/tensorflow/issues/199

**Comment by davidzchen** [comment]
FWIW, Bazel does dump its build artifacts in the source tree but rather creates symlinks to the directories that contain the build artifacts. We opened bazelbuild/bazel#555 to add a Bazel .gitignore to github/gitignore which can easily be used by projects that use Bazel.

From what I understand, most build systems create directories in the source tree that contain the build artifacts. While Autotools supports out-of-tree builds (and some Autotools projects, such as gcc, even recommends this approach), the standard practice for most other build systems seems to be using `.gitignore` to exclude build artifacts.
