### ISSUE TITLE
Tensorflow segmentation fault with RTX 2080Ti CUDA 9.0

### ISSUE THREAD

**Issue by crownk1997** [tensorflow/tensorflow#25002]
<em>Recently, I try to run my previous programming with our new multiple GPUs servers with RTX 2080 Ti. I do not make any about my code which can run successfully on Cuda 9.0 with Tesla V100. I am not sure what the problem is and it seems that there is a problem with Cuda support. When I run the optimizer of Tensorflow, I get the error of segmentation fault. Self-attention GAN is one example that I cannot run successfully. This link is the source code. https://github.com/taki0112/Self-Attention-GAN-Tensorflow</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): Conda
- TensorFlow version (use command below): 1.10.1
- Python version:Python 3.6.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): GCC 7.2.0
- CUDA/cuDNN version: Cuda compilation tools, release 9.0, V9.0.176
- GPU model and memory: RTX 2080Ti

**Describe the current behavior**
Tensorflow can build graph successfully, but when it comes to flow the data into model and update parameters,  it always gives the segmentation fault error. The error is as the following.

generator/attention/h_conv/bias:0 (float32_ref 256) [256, bytes: 1024]
generator/attention/gamma:0 (float32_ref 1) [1, bytes: 4]
generator/up_conv_2/kernel:0 (float32_ref 3x3x256x128) [294912, bytes: 1179648]
generator/up_conv_2/bias:0 (float32_ref 128) [128, bytes: 512]
generator/batch_norm_2/beta:0 (float32_ref 128) [128, bytes: 512]
generator/batch_norm_2/gamma:0 (float32_ref 128) [128, bytes: 512]
generator/up_conv_3/kernel:0 (float32_ref 3x3x128x64) [73728, bytes: 294912]
generator/up_conv_3/bias:0 (float32_ref 64) [64, bytes: 256]
generator/batch_norm_3/beta:0 (float32_ref 64) [64, bytes: 256]
generator/batch_norm_3/gamma:0 (float32_ref 64) [64, bytes: 256]
generator/G_conv_logit/kernel:0 (float32_ref 3x3x64x3) [1728, bytes: 6912]
generator/G_conv_logit/bias:0 (float32_ref 3) [3, bytes: 12]
Total size of variables: 19748741
Total bytes of variables: 78994964
 [*] Reading checkpoints...
 [*] Failed to find a checkpoint
 [!] Load failed...
Segmentation fault (core dumped)

**Describe the expected behavior**
The program should run successfully.

**Code to reproduce the issue**
 Self-attention GAN is one example that I cannot run successfully. This link is the source code. https://github.com/taki0112/Self-Attention-GAN-Tensorflow. Maybe this code is a little bit complex, but it can show you where the problem is.

**Other info / logs**
It seems that there is a version mismatching between the CUDA version and the RTX support, but I am not sure.

**Comment by samikama** [comment]
@crownk1997 I believe you need cuda10 to be able to use Turing generation cards.

**Comment by christianguenter1** [comment]
Please have a look at this tutorial, I am currently facing the same problem. https://www.pytorials.com/how-to-install-tensorflow-gpu-with-cuda-10-0-for-python-on-ubuntu/
