### ISSUE TITLE
FAILED: Build did NOT complete successfully

### ISSUE THREAD

**Issue by miguelmorin** [tensorflow/tensorflow#25007]
**System information**
- OS Platform and Distribution: Ubuntu 16.04.5 LTS
- TensorFlow installed from: Docker image `tensorflow/tensorflow:nightly-devel-gpu`
- TensorFlow version: `master` branch
- Python version: 2 and 3
- Installed using: Docker

**Describe the problem**

I want to submit pull requests and am unable to run the TensorFlow unit tests. I will be happy to add directions to the documentation once I solve the problem.

I set up an Azure virtual machine with Tesla M60 GPUs (the most recent that my academic subscription allows) with the image `Data Science Virtual Machine` on a `Standard NV6 (6 vcpus, 56 GB memory)`. I ssh into it, run these commands, and get the error in the title.

```bash
sudo docker pull tensorflow/tensorflow:nightly-devel-gpu
sudo nvidia-docker run -it abbaea1b533c
```

Then, inside the Docker container:

```bash
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH"
export flags="--config=opt --config=cuda -k"
cd /tensorflow/
bazel test ${flags} //tensorflow/python/...
```

I attach the whole console output, which ends with

```
FAILED: Build did NOT complete successfully
```
[failed_build_log.txt](https://github.com/tensorflow/tensorflow/files/2770095/failed_build_log.txt)

How can I set up a machine that runs TensorFlow's unit tests?

**Comment by angersson** [comment]
I don't see enough information here to know whether or not the Docker setup is to blame. Try building with CPU only first (and the suggested docker flags) to see if that works for you.

**Comment by ppwwyyxx** [comment]
Same issue as #24619 and I've posted a solution there.

**Comment by miguelmorin** [comment]
After some experimentation, I found that choosing another image for the Azure virtual machine fixes this issue. I used `NVIDIA GPU Cloud Image` instead of `Data Science Virtual Machine`, and now the build proceeds until it runs out of space (a `Standard_NV24` gives 32 GiB of disk and Docker lists 17 GiB for the size and 20 GiB for the virtual size). That is another issue and I will close this one.

@ppwwyyxx : although I did not try your solution, I believe it is related. The first error in my log file has a warning after it that mentions `libcuda`:

```
ERROR: /tensorflow/tensorflow/python/BUILD:1741:1: Couldn't build file tensorflow/python/gen_linalg_ops_py_wrappers_cc: Linking of rule '//tensorflow/python:gen_linalg_ops_py_wrappers_cc' failed (Exit 1)
/usr/bin/ld: warning: libcuda.so.1, needed by bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Ulinalg_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so, not found (try using -rpath or -rpath-link)
```

**Comment by miguelmorin** [comment]
A virtual machine with an additional 1 TB disk is able to build:

```
Executed 1045 out of 1045 tests: 511 tests pass and 534 fail locally.
INFO: Build completed, 534 tests FAILED, 24783 total actions
``

I will look into those failures and that is a separate issue.
