### ISSUE TITLE
how to implement the api in pytorch with tensorflow 2.0

### ISSUE THREAD

**Issue by HuangZhanPeng** [tensorflow/tensorflow#25001]
There is two api in pytorch, one is "nn.utils.rnn.pack_padded_sequence", other is "pad_packed_sequence", I want to ask is there any api or implement to achieve the similar function of pytorch in tensorflow 2.0, thank you~~

**Comment by ymodak** [comment]
@ebrevdo Can you PTAL? Thanks

**Comment by ebrevdo** [comment]
If you call `tf.nn.{dynamic_,}rnn` with `sequence_length` vector provided and use padded inputs, it will behave the same as if you used pytorch's pack_padded_sequence.  Specifically, the final state will properly contain the state of the final step for each batch, and the output values in a batch row `b` corresponding to time points after `sequence_length[b]` will be zeroed out.

**Comment by HuangZhanPeng** [comment]
but in tensorflow 2.0, there is no `tf.nn.{dynamic_,}rnn`
