### ISSUE TITLE
Location of Policy Gradient Algorithm in python/grappler for device placement

### ISSUE THREAD

**Issue by ashewx** [tensorflow/tensorflow#25010]
I have been going over this paper: [Device Placement Optimization with Reinforcement Learning](https://arxiv.org/abs/1706.04972) and I have been reviewing the corresponding code within [python/grappler](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/grappler). It seems that the starting point for this code is [graph_placer.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/grappler/graph_placer.py), which sets up the RL model for device placement.

I want to see what happens when I adjust the reinforcement model optimization policies. According to the paper, it is currently using a generic policy gradient algorithm. I'm having a hard time location the mechanism of this algorithm in grappler. Can someone point me towards the location (line number and file) of this code and help explain to me how it works?

**Comment by jvishnuvardhan** [comment]
@ashewx Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from questions. Github is mainly for addressing bugs in installation and performance. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing the issue but please post this kind of support questions at Stackoverflow. Thanks!
