### ISSUE TITLE
TF Build Fails: missing input file '@enum34_archive//:LICENSE'

### ISSUE THREAD

**Issue by mahmoud-abuzaina** [tensorflow/tensorflow#25012]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Cent OS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: master branch
- Python version: 2.7
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): GCC 6.3
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Tensorflow build fails with this error:
ERROR: missing input file '@enum34_archive//:LICENSE'
ERROR: /ec/fm/disks/nrvlab_300G_work01/mabuzain/pr/private-tensorflow/tensorflow/tools/pip_package/BUILD:240:1: //tensorflow/tools/pip_package:build_pip_package: missing input file '@enum34_archive//:LICENSE'

**Comment by ymodak** [comment]
@gunan Can you please take a look at this? Thanks!

**Comment by gunan** [comment]
This is fixed at head.
We rolled back the breaking change, and @revan has fixed the initial issue later.
