### ISSUE TITLE
Bazel Build Tensorflow error

### ISSUE THREAD

**Issue by ajit2678** [tensorflow/tensorflow#25022]
root@gpu-B85M-D3H:/home/gpu/Downloads/tensorflow# bazel build --config=opt --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package
WARNING: Processed legacy workspace file /home/gpu/Downloads/tensorflow/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
Starting local Bazel server and connecting to it...
ERROR: /home/gpu/Downloads/tensorflow/tensorflow/tools/pip_package/BUILD:34:1: Illegal ambiguous match on configurable attribute "deps" in //tensorflow/tools/pip_package:included_headers_gather:
@local_config_cuda//cuda:using_nvcc
@local_config_cuda//cuda:using_clang
Multiple matches are not allowed unless one is unambiguously more specialized.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: 

/home/gpu/Downloads/tensorflow/tensorflow/tools/pip_package/BUILD:34:1: Illegal ambiguous match on configurable attribute "deps" in //tensorflow/tools/pip_package:included_headers_gather:
@local_config_cuda//cuda:using_nvcc
@local_config_cuda//cuda:using_clang
Multiple matches are not allowed unless one is unambiguously more specialized.
INFO: Elapsed time: 4.158s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (198 packages loaded)
    currently loading: tensorflow/core/kernels ... (2 packages)

kindly help me to get sloved

**Comment by jvishnuvardhan** [comment]
@ajit2678 Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. Thanks!

**Comment by ajit2678** [comment]
ERROR: /root/.cache/bazel/_bazel_root/750c4c3f7edf43cdaa78f904ca850347/external/local_config_cuda/cuda/BUILD:1249:1: declared output 'external/local_config_cuda/cuda/cuda/lib/libcudnn.so.7' is a dangling symbolic link
ERROR: /root/.cache/bazel/_bazel_root/750c4c3f7edf43cdaa78f904ca850347/external/local_config_cuda/cuda/BUILD:1249:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 13.777s, Critical Path: 9.38s
INFO: 3 processes: 3 local.
FAILED: Build did NOT complete successfully


Now This error i am getting

•	CUDA 10.0
•	CUDNN 7.3
•	NCCL 2.3

**Comment by jvishnuvardhan** [comment]
@ajit2678 Could you please fill the template as mentioned in my earlier response. Details in the template will help us finding the root-cause and solving the issue. Waiting for your system information [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Thanks!

**Comment by ajit2678** [comment]
**System information**
- OS Platform and Distribution (Linux Ubuntu 16.04):- Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:-NO
- TensorFlow installed from (source or binary):- from Git hub source
- TensorFlow version:-1.8
- Python version:-3.5
- Installed using virtualenv? pip? conda?:- conda
- Bazel version (if compiling from source): - 1.8
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: -10.0/7.3 & nccl 2.3
- GPU model and memory: Geforce GT 610

**Comment by jvishnuvardhan** [comment]
@ajit2678 Could you follow the instructions [here](https://github.com/rnreich/ubuntu-tensorflow-gpu-all-versions) and let us know how it works. I recently used those steps and successfully installed tensorflow-gpu. Thanks!

**Comment by ajit2678** [comment]
I have solved the Problem

**Comment by jvishnuvardhan** [comment]
@ajit2678 Thanks! Have a nice day

**Comment by MoonBlvd** [comment]
I have similar issue when build graph transform. How did you solve yours?

**Comment by ParmpalSinghGill** [comment]
set clang as cuda compiler to No
Do you want to use clang as CUDA compiler? [y/N]: N 
in ./configure  resolve for me
