### ISSUE TITLE
Can not build debug wheel due to zip overflow(linux)

### ISSUE THREAD

**Issue by dmcbeing** [tensorflow/tensorflow#25026]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7.4
- TensorFlow installed from: Source
- TensorFlow version: 3ed46c325f70e2f1521b850b43d2b174101d9472
- Python version: 3.4
- Bazel version (if compiling from source):  0.19.2 (not from source)
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**

Cant create wheel file for a build with debug symbols.

Command:
`./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg`
Output:
`
Fri Jan 18 17:01:09 EET 2019 : === Preparing sources in dir: /tmp/tmp.Qpy8sDXUC9
/tmp/tensorflow /tmp/tensorflow
/tmp/tensorflow
Fri Jan 18 17:01:22 EET 2019 : === Building wheel
warning: no files found matching '*.pyd' under directory '*'
warning: no files found matching '*.pd' under directory '*'
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
warning: no files found matching '*.h' under directory 'tensorflow/include/tensorflow'
warning: no files found matching '*' under directory 'tensorflow/include/Eigen'
warning: no files found matching '*.h' under directory 'tensorflow/include/google'
warning: no files found matching '*' under directory 'tensorflow/include/third_party'
warning: no files found matching '*' under directory 'tensorflow/include/unsupported'
Traceback (most recent call last):
  File "setup.py", line 295, in <module>
    keywords='tensorflow tensor machine learning',
  File "/home1/private/mavridis/.local/lib/python3.4/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home1/private/mavridis/.local/lib/python3.4/site-packages/wheel/bdist_wheel.py", line 250, in run
    wf.write_files(archive_root)
  File "/home1/private/mavridis/.local/lib/python3.4/site-packages/wheel/wheelfile.py", line 122, in write_files
    self.write(path, arcname)
  File "/home1/private/mavridis/.local/lib/python3.4/site-packages/wheel/wheelfile.py", line 136, in write
    self.writestr(zinfo, data, compress_type)
  File "/home1/private/mavridis/.local/lib/python3.4/site-packages/wheel/wheelfile.py", line 139, in writestr
    ZipFile.writestr(self, zinfo_or_arcname, bytes, compress_type)
  File "/usr/lib64/python3.4/zipfile.py", line 1447, in writestr
    data = co.compress(data) + co.flush()
OverflowError: Size does not fit in an unsigned int
`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
First build TF with debug symbols, no GPU support (runs succesfully):

`bazel build --incompatible_remove_native_http_archive=false --incompatible_package_name_is_a_function=false --config=opt -c dbg --strip=never //tensorflow/tools/pip_package:build_pip_package`

Build pip wheel file (FAILS):
`./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg`

**Any other info / logs**

Thanks in advance

**Comment by gunan** [comment]
I think this is simply the package is too big, when you include debug symbols.
Unless pip has support for somehow using 64 bit zip, I do not see how this can be done.

I do not see how we can fix this on TF side, either.

**Comment by dmcbeing** [comment]
> I think this is simply the package is too big, when you include debug symbols.
This was my suspicion as well.
> Unless pip has support for somehow using 64 bit zip, I do not see how this can be done.
> 
> I do not see how we can fix this on TF side, either.
I understand, however what is the 'recomened' aproach to building and debuging of the c++ core?
Building twice would be tediously slow.

Thanks

**Comment by gunan** [comment]
For C++ core debugging, depends on how you use it.
If you are simply using TF as a C++ library, you can use libtensorflow.
For debugging C++ through python, unfortunately we may be blocked on python/pip

**Comment by dmcbeing** [comment]
> For debugging C++ through python, unfortunately we may be blocked on python/pip
Yes this was my conclusion as well.

> For C++ core debugging, depends on how you use it.
> If you are simply using TF as a C++ library, you can use libtensorflow.

Thanks for noting that, i think i can do write unit tests in c++ to stress test the new code and completely bypass the python/pin issues.

Thanks again.

**Comment by BigBug92** [comment]
me too.
I want to pack tensorflow1.12 dbg wheel, and then install using xxx.whl，but i get the same error here.

`root@wuhp000100031:/home/hjj/code/tensorflow# bazel-bin/tensorflow/tools/pip_package/build_pip_package /home/hjj/HuaweiGit/tensorflow_pkg_tf12_dbg
Mon Apr 15 20:10:07 CST 2019 : === Preparing sources in dir: /tmp/tmp.KTUCQY7nMR
/home/hjj/code/tensorflow /home/hjj/code/tensorflow
/home/hjj/code/tensorflow
Mon Apr 15 20:10:24 CST 2019 : === Building wheel
warning: no files found matching '*.pd' under directory '*'
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
warning: no files found matching '*.h' under directory 'tensorflow/include/tensorflow'
warning: no files found matching '*' under directory 'tensorflow/include/Eigen'
warning: no files found matching '*.h' under directory 'tensorflow/include/google'
warning: no files found matching '*' under directory 'tensorflow/include/third_party'
warning: no files found matching '*' under directory 'tensorflow/include/unsupported'
Traceback (most recent call last):
  File "setup.py", line 290, in <module>
    keywords='tensorflow tensor machine learning',
  File "/usr/local/lib/python3.5/dist-packages/setuptools-40.4.3-py3.5.egg/setuptools/__init__.py", line 140, in setup
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/.local/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 254, in run
    wf.write_files(archive_root)
  File "/root/.local/lib/python3.5/site-packages/wheel/wheelfile.py", line 123, in write_files
    self.write(path, arcname)
  File "/root/.local/lib/python3.5/site-packages/wheel/wheelfile.py", line 137, in write
    self.writestr(zinfo, data, compress_type)
  File "/root/.local/lib/python3.5/site-packages/wheel/wheelfile.py", line 140, in writestr
    ZipFile.writestr(self, zinfo_or_arcname, bytes, compress_type)
  File "/usr/lib/python3.5/zipfile.py", line 1573, in writestr
    data = co.compress(data) + co.flush()
OverflowError: Size does not fit in an unsigned int
root@wuhp000100031:/home/hjj/code/tensorflow# `

so, what can i do.
