### ISSUE TITLE
Method to check for GPU op support

### ISSUE THREAD

**Issue by Remper** [tensorflow/tensorflow#2502]
So, given the basic word2vec example being bound to CPU (#514), we can see that `tf.nn.embedding_lookup` doesn't work on GPU. Therefore, ops that use `embedding_lookup` internally doesn't support GPU either (for example, `nce_loss`).
Can we have explicit info in the documentation on which operations are currently GPU-capable and which are not?
For example, are `tf.gather` or `LogUniformCandidateSampler` GPU-capable?

**Comment by Remper** [comment]
@vrv is there a way to check CPU/GPU capabilities of an operation from python? Something like print out a list of available backends for each operation?
Because I could update the documentation myself, but I was wondering if there is a more efficient way than just digging sources one operation at the time.

**Comment by yaroslavvb** [comment]
There doesn't seem to be a more efficient way. Kernel registrations are
done through C++ registry mechanism, so some non-trivial piping would need
to be done to expose it in Python.

**Comment by yaroslavvb** [comment]
BTW, when tracking capabilities through code, one thing to keep in mind is
that there are logical devices and "physical" devices that don't
necessarily coincide. For instance, the following
from core/kernels/cwise_op_add.cc shows that "Add" for int32 is registered
for GPU logical device, but the actual implementation will run on CPU.
(This was done to avoid crossing logical device boundary for efficiency
reasons)

REGISTER_KERNEL_BUILDER(Name("Add")
                            .Device(DEVICE_GPU)
                            .HostMemory("x")
                            .HostMemory("y")
                            .HostMemory("z")
                            .TypeConstraint<int32>("T"),
                        BinaryOp<CPUDevice, functor::add<int32>>);

**Comment by girving** [comment]
The fact that word2vec is bound to CPU is historical: `tf.gather` works fine on GPU now.  I believe `LogUniformCandidateSampler` is still CPU-only, though.

Unfortunately making the docs not depend on kernel registrations helps significantly, and we'd lose those advantages if we presented this information in the docs.  However, a runtime feature for checking which ops have which kernels would be great, so I'll mark this as contributions welcome.

**Comment by ibab** [comment]
A tool that could produce an HTML table with an overview of
 - which ops exist
 - which dtypes are supported
 - which backends are supported

would be pretty amazing when starting out with tensorflow, and would also be useful for making sure that things are defined in a consistent way.
The table could then also be included in the documentation.
(Or should this rather be a feature of TensorBoard?)
This could be built on top of the runtime checking that's the topic of this issue.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by dantkz** [comment]
It's been more than a year, but I can't find any information on the subject. How can one check if a tensorflow operation is running/supported on CPU or GPU? Thanks!

**Comment by albertz** [comment]
I wrote such a function `supported_devices_for_op` [here](https://github.com/rwth-i6/returnn/blob/master/TFUtil.py) ([this commit](https://github.com/rwth-i6/returnn/commit/ed47af101e0f750232c81944be154ff980eb70d9)).
Basically it uses the TF C++ function `tensorflow::KernelsRegisteredForOp` which provides such information.

**Comment by kirk86** [comment]
@dantkz another way to check where your ops are running is using:
`tf.ConfigProto(log_device_placement=True)`
