### ISSUE TITLE
dense to sparse

### ISSUE THREAD

**Issue by gbc8181** [tensorflow/tensorflow#25039]
Since we have sparse to dense op, I think it would be helpful if there is a dense_to_sparse op in Tensorflow. Just like we have a tensor A and it can be converted to a sparse tensor by using a function such as tf. sparse_to_dense(A).

**Comment by msymp** [comment]
@gbc8181 , can you please provide an example why would need this and what exactly do you mean by converting a dense to sparse? Thanks.

**Comment by gbc8181** [comment]
@msymp Hi, I want to multiply two tensors and one of them is sparse; the other is not. If it can be converted to sparse expression, we can save a lot of memory. Thus, we try to convert it to sparse.

**Comment by msymp** [comment]
@gbc8181 , Please use this operation available in TensorFlow:
https://www.tensorflow.org/api_docs/python/tf/sparse/matmul
Thanks.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
