### ISSUE TITLE
Keras subclassed model layers' output shape detection (e.g. for summary)

### ISSUE THREAD

**Issue by inoryy** [tensorflow/tensorflow#25036]
**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Currently output shapes inference of all layers is essentially disabled if model is subclassed, which results in a rather vague "multiple" in model summary. Example:

```python
import tensorflow as tf

class MyModel(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.dense = tf.keras.layers.Dense(1)

    def call(self, inputs, **kwargs):
        return self.dense(inputs)

model = MyModel()
model.build(input_shape=(None, 1))
model.summary()
```

```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense (Dense)                multiple                  2         
=================================================================
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
```

After investigating source code I understand why this happens from a technical point of view, but it is quite frustrating for an end user, especially given that it is quite trivial to infer the shapes manually with given information. I think there should be a way to force `layer.output_shape` recalculation if `model.build()` is manually called. There is of course a risk of mismatching actual input shapes, but that would be responsibility of the `.build()` caller to enforce. 

Alternatively, allow runtime input(s) shape argument to be passed to `model.summary()`, that could be used for one-time shape detection and validation.

**Will this change the current api? How?**

No, not directly. Could possibly affect internal checks if `layer.output_shape` is manually overriden. However, currently that parameter is completely unused for subclassed models, so risk should be low.

**Who will benefit with this feature?**

End users of subclassed model providers who could be interested in inspecting model topology.

**Any Other info.**

I am willing to contribute either option with a little bit of guidance on the direction.

**Comment by jashrathod0** [comment]
Hi. 
Can I help with this issue?

**Comment by jvishnuvardhan** [comment]
@jashrathod0 Please feel free to support any issue here. This is a community helping others in the community. Thanks for coming forward.

**Comment by aminemosbah** [comment]
hi 
great post ,
i m trying to run baloonn detection API Mask_RCNN , and i get stuck with this error 

input that isn't a symbolic tensor

any suggession to work this out ?

**Comment by aminemosbah** [comment]
hi 
great post,
i m trying to run balloon detection API Mask_RCNN , and i get stuck with this error 

input that isn't a symbolic tensor

any suggestion to work this out?

**Comment by marcown** [comment]
Are you working on this? Need help?

same happens for tensorflow 2.0

**Comment by hadim** [comment]
Same issue here on TF 2 nightly.

**Comment by ziyigogogo** [comment]
Same issue here, is there anyway to make the sub-class model able to do things like "model.summary()"?

**Comment by Ja1r0** [comment]
I confront the same issue. In `tf.keras API`, when create a model by define subclass and implement forward pass in method `call`, actually have not build a TF graph. 
The layers in `model.layers` can't get the attributes `layer.input_shape` and `layer.output_shape`. This is because the `layer._inbound_nodes` is an empty list. And in the definition of `layer.input_shape`(also `layer.output_shape`), there is a judgement statement:
```python
if not self._inbound_nodes:
  raise AttributeError('The layer has never been called '
                       'and thus has no defined input shape.')
```
When pass a symbolic tensor to a layer, a `Node` class (define in `keras.engine.base_layer.py`) will append to `layer._inbound_nodes` list. But when create model by subclass and implement forward pass in `call` method, it seems that haven't pass symbolic tensors to each layer. So the `layer._inbound_nodes` is empty list, and then can't get the attribute `layer.input_shape` . This is an example(In `model.summary()` method also need to get the `layer.input_shape`):
```python
import tensorflow as tf

class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
        self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)
    
    def call(self, inputs):
        x = self.dense1(inputs)
        return self.dense2(x)

model = MyModel()
layers = model.layers

for layer in layers:
    name = layer.name
    input_shape = layer.input_shape
    output_shape = layer.output_shape
    print('%s   input shape: %s, output_shape: %s.\n' % (name, input_shape, output_shape))
```
And this is the traceback:
```prompt
Traceback (most recent call last):
  File "draft.py", line 195, in <module>
    test8()
  File "draft.py", line 159, in test8
    input_shape = layer.input_shape
  File "C:\Users\Jairo\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\k
eras\engine\base_layer.py", line 1118, in input_shape
    raise AttributeError('The layer has never been called '
AttributeError: The layer has never been called and thus has no defined input sh
ape.
```
If create a model by `functional API` or `model.Sequential`, things go well:
```python
import tensorflow as tf

inputs = tf.keras.Input(shape=(3,))
x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)
```
or
```python
import tensorflow as tf

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(32, input_shape=(500,)))
model.add(tf.keras.layers.Dense(32))
```
But when the model structure is complicated, I choose to use subclass model and define forward pass in `call`. If can get `layer.input_shape` and `layer.output_shape` when create model by subclass, it will be very convenient.

**Comment by Ja1r0** [comment]
I think I found a solution! When create a model by define subclass and implement forward pass in method 'call'. Two keypoints to use 'model.summary()' successfully: 
- In the definition of method `def call(self, inputs)`, convert the `inputs` to Keras tensor first. Use `tf.keras.Input(input_shape)`
- Call `model.build(input_shape)` before `model.summary()`

Look at this example:
```python
import tensorflow as tf

class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
        self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)
    
    def call(self, inputs):
        inputs = tf.keras.Input(shape=inputs.shape)  # Keypoint 1
        x = self.dense1(inputs)
        x = self.dense2(x)
        return x

model = MyModel()
model.build((50,))  # Keypoint 2

layers = model.layers
for layer in layers:
    name = layer.name
    input_shape = layer.input_shape
    output_shape = layer.output_shape
    print('%s   input shape: %s, output_shape: %s.' % (name, input_shape, output_shape))

model.summary()
```
And this is the result:
```prompt
WARNING:tensorflow:From C:\Users\Jairo\Anaconda3\envs\py35\lib\site-packages\ten
sorflow\python\ops\resource_variable_ops.py:435: colocate_with (from tensorflow.
python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
dense   input shape: (None, 50), output_shape: (None, 4).
dense_1   input shape: (None, 4), output_shape: (None, 5).
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 4)                 204
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 25
=================================================================
Total params: 229
Trainable params: 229
Non-trainable params: 0
_________________________________________________________________
```
I have no idea about the `WARNING` yet.

**Comment by svobora** [comment]
This is a serious issue, rendering subclassing the Model class unusable. Anyone working on this?

**Comment by fchollet** [comment]
You can do all these things (printing input / output shapes) in a Functional or Sequential model because these models are static graphs of layers.

In contrast, a subclassed model is a piece of Python code (a `call` method). There is no graph of layers here. We cannot know how layers are connected to each other (because that's defined in the body of `call`, not as an explicit data structure), so we cannot infer input / output shapes.

Please see this detailed explanation of the differences between Functional/Sequential models and imperative models: https://medium.com/tensorflow/what-are-symbolic-and-imperative-apis-in-tensorflow-2-0-dfccecb01021

**Comment by svobora** [comment]
@fchollet Thank you for the explanation. It seems that there is a misunderstanding in the purpose of subclassing Model. Every tutorial I've seen uses that as encapsulation of static graphs e.g. as ResNet blocks. However, now I understand that they are meant for dynamic graphs, where each `call` could evaluate different graph based on input parameters.

**Comment by zh794390558** [comment]
@fchollet Thanks.

**Comment by randolf-scholz** [comment]
@inoryy and anyone interested, I found a dirty workaround that basically mixes functional API and model subclassing by using `__new__`

```python
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Flatten

class MyModel(tf.keras.Model):
    def __init__(self, *args, **kwargs):
        super().__init__(self._inputs, self._outputs)
        self.compile(optimizer='adam', loss='sparse_categorical_crossentropy')
        
    def __new__(cls, input_shape, num_classes, neurons=100, layers=2):
        cls._inputs = Input( input_shape, dtype=tf.float32, name='inputs' )
        x = Flatten()(cls._inputs)
        for k in range(layers):
            x =  Dense(neurons)(x)
        cls._outputs = Dense(num_classes)(x)
        
        return super().__new__(cls)
    
model = MyModel( (28,28), 10 )
model.summary()
```
This can be useful for example if one wants to write a grid-search wrapper that works with either tensorflow/pytorch/scikit-learn type models.

```python
for HPC in HPCs:
   model = MyModel(**HPC)  # initialize with specific HyperParameterCombination
   model.fit(train_data)
   score = model.evaluate(test_data)
```

**Comment by ixez** [comment]
I borrow the solution from [here](https://stackoverflow.com/questions/55235212/model-summary-cant-print-output-shape-while-using-subclass-model) by adding a `model` method to infer the model explicitly.

The output shape is especially uncertain when with `Dense` layer as it depends on the input shape, so it needs to be inferred with a certain input shape.


```python
import tensorflow as tf
from tensorflow.keras.layers import Input

class MyModel(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.dense = tf.keras.layers.Dense(1)

    def call(self, inputs, **kwargs):
        return self.dense(inputs)

    def model(self):
        x = Input(shape=(1))
        return Model(inputs=[x], outputs=self.call(x))

MyModel().model().summary()
```

**Comment by Danmou** [comment]
I created a mixin class that solves this problem for static models defined with the subclassing API. It automatically defines input and output shapes and dtypes the first time the model or layer is called. See the [gist](https://gist.github.com/Danmou/bafa5c80356fdb2c843eaf38c8597f84) for a complete example, but here's a demonstration:
```python
class ExampleNetwork(Model):
    def __init__(self) -> None:
        super().__init__()
        self.encoder = Sequential([
            Conv2D(filters=32, kernel_size=3, strides=2, activation='relu'),
            Flatten(),
        ])
        self.concat = Concatenate(axis=-1)
        self.dense = Dense(units=100)

    def call(self, inputs: List[tf.Tensor]) -> tf.Tensor:
        encoded = self.encoder(inputs[0])
        joined = self.concat([encoded] + inputs[1:])
        return self.dense(joined)

model = ExampleNetwork()
first_batch = [tf.zeros((1, 64, 64, 3)), tf.zeros((1, 10))]
model(first_batch)
model.summary()
# Model: "example_network_1"
# _________________________________________________________________
# Layer (type)                 Output Shape              Param #
# =================================================================
# sequential_1 (Sequential)    (None, 30752)             896
# _________________________________________________________________
# concatenate (Concatenate)    (None, 30762)             0
# _________________________________________________________________
# dense (Dense)                (None, 100)               3076300
# =================================================================
# Total params: 3,077,196
# Trainable params: 3,077,196
# Non-trainable params: 0
# _________________________________________________________________
print(model.input_shape)
# ListWrapper([TensorShape([None, 64, 64, 3]), TensorShape([None, 10])])
```

@fchollet and other devs, any chance this (or something similar) could become part of `tf.keras.layers.Layer` when it's not explicitly initialized as dynamic?

**Comment by JamesMcGuigan** [comment]
It took a few attempts to get this right.

The first hack method is simply to run dummy data through the model
```
model = ClassCNN()
model( tf.random.uniform(shape=(128,28,28,1)) )  # required to call .summary() before .fit()
model.summary()
```

However a more robust solution involves explictly `.build(input_size)` on the key layers, and then on the model itself inside `__init__()`. 

Not all the layers need to be defined, as some information can be implied. Define the first "real" layer (`Flatten()` is not a layer), plus any `Conv2D()` and `Dropout()` layers, which might require a little bit of math.

Here are some working examples of keras syntax, which fixes the `model.summary()` before `model.fit()` bug:
- https://github.com/JamesMcGuigan/kaggle-digit-recognizer/tree/master/src/keras/examples

```
class ClassCNN(tf.keras.Model):

    def __init__(self, input_shape, output_shape, **kwargs):
        super(ClassCNN, self).__init__()
        self._input_shape  = input_shape   # = (28, 28, 1)
        self._output_shape = output_shape  # = 10

        self.conv1      = Conv2D(32, kernel_size=(3, 3), activation=tf.nn.relu)
        self.conv2      = Conv2D(64, kernel_size=(3, 3), activation=tf.nn.relu)
        self.maxpool    = MaxPooling2D(pool_size=(2, 2))
        self.dropout1   = Dropout(0.25, name='dropout1')
        self.flatten    = Flatten()
        self.dense1     = Dense(128, activation=tf.nn.relu)
        self.dropout2   = Dropout(0.5, name='dropout2')
        self.activation = Dense(self._output_shape, activation=tf.nn.relu)

        self.conv1.build(     (None,) + input_shape )
        self.conv2.build(     (None,) + tuple(np.subtract(input_shape[:-1],2)) + (32,) )
        self.maxpool.build(   (None,) + tuple(np.subtract(input_shape[:-1],4)) + (64,) )
        self.dropout1.build( tuple(np.floor_divide(np.subtract(input_shape[:-1],4),2)) + (64,) )
        self.dropout2.build( 128 )
        self.build(           (None,) + input_shape)


    def call(self, x, training=False, **kwargs):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.maxpool(x)
        if training:  x = self.dropout1(x)
        x = self.flatten(x)
        x = self.dense1(x)
        if training:  x = self.dropout2(x)
        x = self.activation(x)
        return x
```

```
class ClassNN(tf.keras.Model):

    def __init__(self, input_shape, output_shape, **kwargs):
        super(ClassNN, self).__init__()
        self._input_shape  = np.prod(input_shape)  # = (28, 28, 1) = 784
        self._output_shape = output_shape          # = 10

        self.flatten    = tf.keras.layers.Flatten()
        self.dense1     = tf.keras.layers.Dense(128, activation=tf.nn.relu, )
        self.dropout    = tf.keras.layers.Dropout(0.2)
        self.dense2     = tf.keras.layers.Dense(128, activation=tf.nn.softmax)
        self.activation = tf.keras.layers.Dense(self._output_shape, activation=tf.nn.softmax)

        self.dense1.build( self._input_shape)
        self.dropout.build(128)
        self.build( (None, self._input_shape) )


    def call(self, inputs, training=False, **kwargs):
        x = self.flatten(inputs)
        x = self.dense1(x)
        if training: x = self.dropout(x)
        x = self.dense2(x)
        x = self.activation(x)
        return x
```

```
def FunctionalCNN(input_shape, output_shape):
    inputs = Input(shape=input_shape)
    x = Conv2D(32, kernel_size=(3, 3), activation='relu')(inputs)
    x = Conv2D(64, kernel_size=(3, 3), activation='relu')(x)
    x = MaxPooling2D(pool_size=(2, 2))(x)
    x = Dropout(0.25)(x)
    x = Flatten()(x)
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.5)(x)
    x = Dense(output_shape, activation='softmax')(x)

    model = Model(inputs, x, name="FunctionalCNN")
    plot_model(model, to_file=os.path.join(os.path.dirname(__file__), "FunctionalCNN.png"))
    return model
```

```
def SequentialCNN(input_shape, output_shape):
    model = Sequential()
    model.add( Conv2D(32, kernel_size=(3, 3),
                     activation='relu',
                     input_shape=input_shape) )
    model.add( Conv2D(64, (3, 3), activation='relu') )
    model.add( MaxPooling2D(pool_size=(2, 2)) )
    model.add( Dropout(0.25) )
    model.add( Flatten() )
    model.add( Dense(128, activation='relu') )
    model.add( Dropout(0.5) )
    model.add( Dense(output_shape, activation='softmax') )

    plot_model(model, to_file=os.path.join(os.path.dirname(__file__), "SequentialCNN.png"))
    return model
```

However in comparing the accuracy of these models on MINST, `ClassCNN` accuracy is only 36% compared to 75% for `SequentialCNN` / `FunctionalCNN`, despite having the exact same internal structure. 

The only visible difference is that `model.summary()` for `ClassCNN` outputs "Output Shape = multiple", rather than `SequentialCNN` / `FunctionalCNN` which have show a fixed tuple size for layer Output Shape.

```
SequentialCNN   validation: | loss: 1.3756675141198293 | accuracy: 0.7430952
FunctionalCNN   validation: | loss: 1.4285654685610816 | accuracy: 0.7835714
ClassCNN        validation: | loss: 1.9851970995040167 | accuracy: 0.36214286
ClassNN         validation: | loss: 2.302224604288737  | accuracy: 0.09059524
```

**Comment by b-safwat** [comment]
I believe it can be handled this way, which sounds net and clean, isn't it?
https://stackoverflow.com/a/55236388/871418
