### ISSUE TITLE
provide a better error when keras.layers.Dot is called with a tuple instead of a list

### ISSUE THREAD

**Issue by josharian** [tensorflow/tensorflow#25049]
- TensorFlow version: 1.12

`keras.layers.Dot` (functional API) is intended to be called with a list of layers: `Dot(axes=0)([a, b])`.

If you call it with multiple args (`Dot(axes=0)(a, b)`), it provides a useful error message: ```ValueError: A `Dot` layer should be called on a list of 2 inputs.```.

If you call it with a tuple of layers (`Dot(axes=0)((a, b))`, it fails with a cryptic error message: `TypeError: int() argument must be a string, a bytes-like object or a number, not 'TensorShape'`.

There is code at the beginning of `Dot.build` that is intended to help with tuples as well:

```python
  @tf_utils.shape_type_conversion
  def build(self, input_shape):
    # Used purely for shape validation.
    if not isinstance(input_shape, list) or len(input_shape) != 2:
      raise ValueError('A `Dot` layer should be called '
                       'on a list of 2 inputs.')
```

However, when `input_shape` is a tuple, `tf_utils.shape_type_conversion` fails, producing the cryptic error message above, before the helpful error message can kick in.

I just lost a couple of hours to this.

I see two possible fixes:

* Teach `tf_utils.shape_type_conversion` to understand tuples.
* Add another decorator before `tf_utils.shape_type_conversion` to diagnose tuple inputs.

This applies to other keras merge layers as well.

**Comment by pavithrasv** [comment]
Are you still seeing this issue?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
