### ISSUE TITLE
[TFLite] Feature request: Add support for DepthToSpace op 

### ISSUE THREAD

**Issue by stakemura** [tensorflow/tensorflow#25044]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 16.04
- TensorFlow installed from (source or binary):source
- TensorFlow version (or github SHA if from source):1.13

**Provide the text output from tflite_convert**

```
...  Converting unsupported operation: DepthToSpace
```

**Any other info / logs**

DepthToSpace op has been well used for implementing subpixel convolution (aka pixel shuffle) like [this super-resolution task](https://davidreiman.github.io/posts/galaxy-image-super-resolution.html). 
I know SELECT_TF_OPS option. But its binary size is too huge for mobile application.
Would you like to add DepthToSpace to built-in ops?

**Comment by aselle** [comment]
I don't have any objection to a DepthToSpace op being included, but we have not yet prioritized it with the reset of the work. We would welcome contributions if you have time to contribute, but we will likely add it at some point.

**Comment by tejaskhot** [comment]
@aselle @stakemura  Hi, I am interested in using the `depth_to_space` op. Is there a workaround for this in the meantime till it is added to the list of supported ops? I am able to convert my model to tflite by specifying 
```
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops = True # this is for DEPTH_TO_SPACE
```
However, the interpreter fails with the error:
```
ValueError: Didn't find custom op for name 'DEPTH_TO_SPACE' with version 1
Registration failed.
```

**Comment by purva98** [comment]
Hey! When will DepthToSpace be added?

**Comment by mouryareddy** [comment]
If depth_to_space isn’t supported even now, Can you tell me an alternative to depth_to_space which I can convert to tflite.

**Comment by rmothukuru** [comment]
@stakemura,
Sorry for the delayed response. Can you please let us know if [tfl.depth_to_space (TFL::DepthToSpaceOp)](https://www.tensorflow.org/mlir/tfl_ops#tfldepth_to_space_tfldepthtospaceop) is the functionality that you are looking for? Thanks!
