### ISSUE TITLE
tf.nn.sampled_softmax_loss use deprecated sparse_to_dense

### ISSUE THREAD

**Issue by bsnipers** [tensorflow/tensorflow#25043]
tf.nn.sampled_softmax_loss is using the deprecated ops sparse_to_dense (from tensorflow.python.ops.sparse_ops). Could it be replaced by the `tf.sparse.SparseTensor` and `tf.sparse.to_dense` as the warning suggested?

**Comment by yongtang** [comment]
Added a PR #25048 to fix the warning.

**Comment by msymp** [comment]
@ymodak , can you please assist with this. Thanks.
