### ISSUE TITLE
How install tensorflow by python 3.7.2 on windows 10?

### ISSUE THREAD

**Issue by DavidPhysics** [tensorflow/tensorflow#25054]
**System information**
-- Windows version: Windows 10 64 bit
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?: virtualenv 16.2; pip 18.1

**Describe the problem**
I follow the tensorflow installation guide to install tensorflow by cmd methods.
When I input "pip3 install --user --upgrade tensorflow" on cmd, the cmd shows the error messages
that is:
"Collecting tensorflow
Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow"

Q1: Is this problem about the python version problem?
Q2: Does the Tensorflow support the Python 3.7.2 version?

Tensorflow Link: [https://www.tensorflow.org/install/pip](https://www.tensorflow.org/install/pip)
**Provide the exact sequence of commands / steps that you executed before running into the problem**
![image](https://user-images.githubusercontent.com/25798404/51440345-25ed6b00-1d01-11e9-8b0b-df3788807db8.png)

![image](https://user-images.githubusercontent.com/25798404/51440384-7238ab00-1d01-11e9-97fb-f2989aa5bcf0.png)

**Comment by MatthiasRathbun** [comment]
Yes and yes, They are working currently on bringing sypport to python 3.7 on linux systems, but I have no word on Windows. You should create a new env and run 
Conda install python=3.6 which will allow you to install tensorflow.

**Comment by DavidPhysics** [comment]
@MatthiasRathbun 
Q1. Could I create the virtualenv environment to install the tensorflow and python 3.7.2?
I also try to use the virtualenv environment to install tensorflow. The virtualenv is based on the python 3.7.2, but it also has same as this problem. Is it also the same as the version problems?

![image](https://user-images.githubusercontent.com/25798404/51456931-680ebf00-1d8a-11e9-8b3d-e409ff4d4e7b.png)

**Comment by MatthiasRathbun** [comment]
> @MatthiasRathbun
> Q1. Could I create the virtualenv environment to install the tensorflow and python 3.7.2?
> I also try to use the virtualenv environment to install tensorflow. The virtualenv is based on the python 3.7.2, but it also has same as this problem. Is it also the same as the version problems?
> 
> ![image](https://user-images.githubusercontent.com/25798404/51456931-680ebf00-1d8a-11e9-8b3d-e409ff4d4e7b.png)

No, the only reason for mentioning a new env was in case you needed python 3.7. Tensorflow does not support python 3.7 regardless, You would need to install python 3.6 to use tensorflow. That is done by 
`conda install python=3.6` which will install version 3.6.8.

**Comment by petsuter** [comment]
https://www.lfd.uci.edu/~gohlke/pythonlibs/ has unofficial binaries for Windows that support Python 3.7.

When will Tensorflow support Python 3.7 officially?

**Comment by ymodak** [comment]
Closing this issue since @MatthiasRathbun is correct in his explanation. Currently TensorFlow does not officially support Python 3.7. Please switch python 3.6 or lower and try again. Thanks!

**Comment by mazlumtanrikulu** [comment]
Firstly, you should install and setup the anaconda via [anaconda](https://www.anaconda.com/distribution/#download-section) and then follow these steps via [TensorFlow](https://www.tensorflow.org/install/pip). Finally, you can use TensorFlow that is version 1.14 on python 3.7

**Comment by kiranKayaDev** [comment]
can anyone please tell me the  appropriate solution

**Comment by vklodik** [comment]
> 
> 
> can anyone please tell me the appropriate solution

Just install Python3.6
It took me 3 hours for find that's simple solution
