### ISSUE TITLE
[XLA] erf, lgamma, and others do not compute correct values in f16 mode

### ISSUE THREAD

**Issue by jlebar** [tensorflow/tensorflow#25052]
In https://github.com/google-research/bert/pull/255 @thorjohnsen noticed something was wrong with XLA's `erf` implementation in f16 mode.

At first I thought this was just a precision issue, but upon investigation (trying all f16 inputs) I think the problem is worse than this.  Instead, I notice that for ~4476 inputs to erf with large absolute value (i.e. close to +/- inf) over/underflow to nan instead of +/-1.  And with the exception of these nans, all other inputs to erf have small relative error (less than 0.1%).

I notice a similar problem with lgamma, where negative numbers with large absolute value overflow to nan instead of inf.

acosh has the opposite problem, many inputs which cmath returns nan for, we return -inf.  That's probably not as bad but still may be something we should fix.

The lgamma issue at least can be "fixed" by doing the computation in f32 (i.e. `static_cast<f16>(lgamma(static_cast<f32>(x))`) but I don't immediately think this is the right thing to do.  As a starting point, I need to understand the algorithms better.

Many functions also have one or two wrong answers, e.g. when presented with +/-inf.  I suspect that the f32 versions have these problems too.  The f32 versions may also have the same under/overflow problems as the f16 versions, just at more extreme values.  I haven't tested yet.

The issue I'm observing broadly occurs on both CPU and GPU, although CPU in some cases gives slightly different errors (e.g. its acosh seems to be fine, but its asinh has a similar problem [?], returning finite values instead of nan).

**Comment by jlebar** [comment]
cc @benbarsdell @majnemer @hawkinsp

**Comment by jlebar** [comment]
(Off-topic, but I've been interested in fuzzing XLA, and this is a data point: All of these functions are implemented not as XLA primitives, and therefore they can't be checked by a fuzzer that simply generates random HLO and checks that it gives the right answer.)

**Comment by ngimel** [comment]
acosh is returning `inf` instead of `nan` because of sqrt term overflowing in fp16 https://github.com/tensorflow/tensorflow/blob/937ff1b4cf1d954806e075d66198429a6d2312be/tensorflow/compiler/xla/client/lib/math.cc#L306-L308. Then, the result of `log` argument is also `inf` (instead of negative number), and `inf` is returned. Obviously, the same thing happens with fp32, but it would require arguments on the order of 10^19, whereas for half 260 more or less is enough for x^2 to overflow.
asinh is defined across the whole real domain, so it should never return `nan`. 
For erf/erfc, if 2 intermediate values overflow in fp16 (say, `pp` and `pq`), result of an operation on them will be `nan`. Overflows are likely, because many of the coefficient values are large.  
Generally, due to fp16 limited dynamic range we try to not round intermediate results to fp16. But this becomes murkier for special functions where it's hard to come to conclusion at which granularity rounding should or should not occur. I think @benbarsdell's suggestion of following what Eigen does is a good one, and will ensure consistent results between core tensorflow and XLA.

**Comment by jlebar** [comment]
Thanks for your analysis, @ngimel.

> I think @benbarsdell's suggestion of following what Eigen does is a good one, and will ensure consistent results between core tensorflow and XLA.

I'm pretty strongly in the "two wrongs don't make a right" camp.  I think the right approach is to prove that XLA's result is correct (within some stated contract) for all fp16 and fp32 values.  Then we can file bugs against Eigen if necessary.

IOW XLA's goal is not to match Eigen bit-for-bit or bug-for-bug.  Indeed, bit-for-bit or bug-for-bug matching isn't feasible insofar as Eigen implements some of these functions by calling into the C++ standard library (e.g. for lgamma).

**Comment by jlebar** [comment]
(BTW I believe our lgamma is broken at least in part because we compute `sin(pi * x)`, which is nan for large values of x.)

**Comment by jlebar** [comment]
> I think the right approach is to prove that XLA's result is correct (within some stated contract) for all fp16 and fp32 values.

To be clear, perhaps the contract we end up with is the same as what's currently implemented by Eigen!  I suspect we can do better in at least some cases, though.  For example, we're not handling +/- inf properly in some of these functions, and I think we should if it's not too expensive (which I think it shouldn't be).  That would make us strictly better than a putative Eigen implementation that doesn't handle +/- inf, but that's a good thing I think.

**Comment by jlebar** [comment]
FYI I'm actively working on this.  I've improved f16 lgamma some and hope to look at erf soon.

I'm not sure yet if we're going to end up simply applying the hammer of "do all arithmetic in f32", but I think it's useful to push f16 as far as we can without applying that hammer, because I suspect that most of the problems I'm finding when doing arithmetic in f16 will apply just as well to f32, and we don't want to apply the same hammer to f32 and do all the computation at f64 precision.  (At some point this gets out of hand... :smile:)

**Comment by jlebar** [comment]
I've landed my fix for `erf(f16)`; it should show up in OSS within an hour or so and it should show up in bug like the commits above when it does.

According to the exhaustive tests I've set up, we're getting what I'd describe as pretty tight precision bounds (for f16, anyway): All results are within an absolute error of 0.001 or a relative error of 0.0001.

Upcasting to f32 should no longer be necessary.  At least, that's the theory.  @thorjohnsen you may wish to verify this.  :)

**Comment by jlebar** [comment]
I'm going to optimistically close this, although there's more work to be done to get all of the functions up to par.  @thorjohnsen &co, please do not hesitate to re-open.
