### ISSUE TITLE
No mod for int32 no GPU kernel support

### ISSUE THREAD

**Issue by markpwoodward** [tensorflow/tensorflow#2505]
I apologize if this is not actually a issue. When trying to put tf.reduce_mean() on the gpu, I get the following error:
```
tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'gradients/Mean_grad/mod': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available
         [[Node: gradients/Mean_grad/mod = Mod[T=DT_INT32, _device="/device:GPU:0"](gradients/Mean_grad/add, gradients/Mean_grad/Size)]]
```

I am on commit 43a8c49f04a485ffc33b510c27eda77f8f38377c from Tue 5/24/2016.

You can reproduce this by modifying the mnist/convolutional.py file by putting the tf.reduce_mean() and optimizer.minimize() inside "with tf.device('/gpu:0'):" statements.

I am trying to do gradient calculations on their respective gpu towers, but compute_gradients() gets hung up on tf.reduce_mean().

Thank you,
Mark

**Comment by vrv** [comment]
the error message actually says there's no "mod" support for int32 on GPU.

Thankfully, this was fixed yesterday at https://github.com/tensorflow/tensorflow/commit/249106f652591afd0fc36ee4e560c3989287f699 -- can you sync to head and try again?

**Comment by markpwoodward** [comment]
Fix confirmed. thank you!
