### ISSUE TITLE
Failed to build for iOS project using Xcode 10.1: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by andreapavan** [tensorflow/tensorflow#25058]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Mojave 10.14.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.12.0
- Python version: 2.7.10
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.20.0-homebrew
- GCC/Compiler version (if compiling from source): Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a
- Xcode: Version 10.1 (10B61)

**Describe the problem**

Error during compiling iOS app with TF static library. The steps are described below.
After compiling TF library from source, importing it in a blank Xcode project I get the following error:

`ld: symbol(s) not found for architecture x86_64`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Cloned the TF repo with: `git clone https://github.com/tensorflow/tensorflow -b r1.12`
2. Configuring:
```
You have bazel 0.20.0-homebrew installed.
Please specify the location of python. [Default is /usr/bin/python]:


Found possible Python library paths:
  /Library/Python/2.7/site-packages
Please input the desired Python library path to use.  Default is [/Library/Python/2.7/site-packages]

Do you wish to build TensorFlow with Google Cloud Platform support? [Y/n]: n
No Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [Y/n]: n
No Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Amazon AWS Platform support? [Y/n]: n
No Amazon AWS Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Apache Kafka Platform support? [Y/n]: n
No Apache Kafka Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]: N
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with GDR support? [y/N]: N
No GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: N
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: N
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: N
Clang will not be downloaded.

Do you wish to build TensorFlow with MPI support? [y/N]: N
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
Configuration finished 
```
3. Updated makefile for iOS as mentioned in https://github.com/tensorflow/tensorflow/issues/18356 and modified `tensorflow/tensorflow/core/util/work_sharder.cc` file as mentioned by https://github.com/tensorflow/tensorflow/issues/18356#issuecomment-422373566

4. After compiling (successfully) I obtain:

- `tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a`
- `tensorflow/contrib/makefile/gen/protobuf_ios/lib/libprotobuf.a`
- `tensorflow/contrib/makefile/gen/protobuf_ios/lib/libprotobuf-lite.a`

5. I created a new blank Xcode project and following https://stackoverflow.com/questions/37769904/how-to-compile-ios-example-in-tensorflow?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa I linked all the libraries

6. The compile phase ends with errors show below

**Any other info / logs**

`Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::at(unsigned long) const", referenced from:
      google::protobuf::io::Tokenizer::IsIdentifier(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libprotobuf.a(tokenizer.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__grow_by(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >& std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__append_forward_unsafe<std::__1::__wrap_iter<char const*> >(std::__1::__wrap_iter<char const*>, std::__1::__wrap_iter<char const*>) in libprotobuf-lite.a(strutil.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >& std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__append_forward_unsafe<char const*>(char const*, char const*) in libprotobuf.a(strtod.o)
  "std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >)", referenced from:
      std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > > const&) in nsync.a(nsync_semaphore_mutex.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::replace(unsigned long, unsigned long, char const*)", referenced from:
      google::protobuf::EnumDescriptor::DebugString(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, google::protobuf::DebugStringOptions const&) const in libprotobuf.a(descriptor.o)
      google::protobuf::Descriptor::DebugString(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, google::protobuf::DebugStringOptions const&, bool) const in libprotobuf.a(descriptor.o)
  "std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&)", referenced from:
      nsync::nsync_time_sleep(timespec) in nsync.a(time_rep_timespec.o)
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::put(char)", referenced from:
      tensorflow::StatsCalculator::GetShortSummary() const in libtensorflow-core.a(stats_calculator.o)
      tensorflow::StatsCalculator::HeaderString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libtensorflow-core.a(stats_calculator.o)
      tensorflow::StatsCalculator::GetStatsByNodeType() const in libtensorflow-core.a(stats_calculator.o)
      tensorflow::StatsCalculator::GetStatsByMetric(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tensorflow::StatsCalculator::SortingMetric, int) const in libtensorflow-core.a(stats_calculator.o)
      tensorflow::StatsCalculator::GetOutputString() const in libtensorflow-core.a(stats_calculator.o)
      tensorflow::PrintOp::Compute(tensorflow::OpKernelContext*) in libtensorflow-core.a(logging_ops.o)
      tensorflow::PrintV2Op::Compute(tensorflow::OpKernelContext*) in libtensorflow-core.a(logging_ops.o)`

      ...

`  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(long)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >* tensorflow::internal::MakeCheckOpString<int, long>(int const&, long const&, char const*) in libtensorflow-core.a(ctc_loss_calculator.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >* tensorflow::internal::MakeCheckOpString<int, long>(int const&, long const&, char const*) in libtensorflow-core.a(ctc_decoder_ops.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >* tensorflow::internal::MakeCheckOpString<int, long>(int const&, long const&, char const*) in libtensorflow-core.a(pad_op.o)
"operator new(unsigned long)", referenced from:
 protobuf_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2flearner_2eproto::protobuf_AssignDescriptors() in libtensorflow-core.a(learner.pb.o)    tensorflow::boosted_trees::learner::LearnerConfig::LearnerConfig(tensorflow::boosted_trees::learner::LearnerConfig const&) in libtensorflow-core.a(learner.pb.o)
      tensorflow::boosted_trees::learner::TreeRegularizationConfig* google::protobuf::Arena::CreateMessage<tensorflow::boosted_trees::learner::TreeRegularizationConfig>(google::protobuf::Arena*) in libtensorflow-core.a(learner.pb.o)
      tensorflow::boosted_trees::learner::TreeConstraintsConfig* google::protobuf::Arena::CreateMessage<tensorflow::boosted_trees::learner::TreeConstraintsConfig>(google::protobuf::Arena*) in libtensorflow-core.a(learner.pb.o)
      tensorflow::boosted_trees::learner::LearningRateConfig* google::protobuf::Arena::CreateMessage<tensorflow::boosted_trees::learner::LearningRateConfig>(google::protobuf::Arena*) in libtensorflow-core.a(learner.pb.o)
      tensorflow::boosted_trees::learner::LearningRateFixedConfig* google::protobuf::Arena::CreateMessage<tensorflow::boosted_trees::learner::LearningRateFixedConfig>(google::protobuf::Arena*) in libtensorflow-core.a(learner.pb.o)
      tensorflow::boosted_trees::learner::LearningRateLineSearchConfig* google::protobuf::Arena::CreateMessage<tensorflow::boosted_trees::learner::LearningRateLineSearchConfig>(google::protobuf::Arena*) in libtensorflow-core.a(learner.pb.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by andreapavan** [comment]
@msymp Thanks for the reply. Python was 2.7.10. I updated my post. I installed Bazel 1.15.0 from binary installer, but I always the same problem. I think is a problem of linking (or missing linking) of some library. How can I check all the dependencies?

**Comment by msymp** [comment]
@andreapavan , This is apparently a systems issue specifically to the iOS build environment. This does not seem to be a TensorFlow repo issue. Can you check into some iOS community boards for answers? Thanks.

**Comment by jvishnuvardhan** [comment]
@andreapavan Could you try pip install tensorflow==1.10.1 or any other new version (update last few digits).

**Comment by scm-ns** [comment]
You most probably have to link to C++ runtime to the project. The errors are about not being able to link c++ std lib classes.

**Comment by violettomsk** [comment]
There is still no idea to fix this issue, isnt it?

**Comment by violettomsk** [comment]
I got into this trouble some days ago.
Please try my solution to work around this issue.

**Comment by violettomsk** [comment]
https://github.com/violettomsk/xcodesdks

**Comment by aprofromindia** [comment]
this might work (https://github.com/facebook/react-native/issues/23390#issuecomment-463157141)

**Comment by ylipacbio** [comment]
Thank you @violettomsk!

Adding  `-lstdc++` solved a similar issue I saw when compiling C++ program depend on tensorflow 2.1 on macbook.

Without `-lstdc++`, I saw the following error
```
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::compare(unsigned long, unsigned long, char const*, unsigned long) const", referenced from:
      bool std::__1::operator==<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*) in example_trainer-cedf75.o
  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
      std::__1::vector<std::__1::pair<tensorflow::Node*, int>, std::__1::allocator<std::__1::pair<tensorflow::Node*, int> > >::__vallocate(unsigned long) in example_trainer-cedf75.o
```

After adding `-lstdc++`, and edit {LD_LIBRARY_PATH}, compilation and linking worked fine!
```
clang tensorflow/cc/tutorials/example_trainer.cc \
  -I${root_dir}/include \
  -ltensorflow_cc \
  -ltensorflow_framework \
  -L${root_dir}/lib \
  -lstdc++ \
  -o a.out

LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:PATH_TO_MY_TENSORFLOW_LIB ./a.out
```

Really appreciate your suggestions!

**Comment by Saduf2019** [comment]
@andreapavan please confirm if your issue is resolved

**Comment by Saduf2019** [comment]
@andreapavan 
please update as per above comment
