### ISSUE TITLE
Example missing for using the field `tensor_content` with Golang grpc client

### ISSUE THREAD

**Issue by lnshi** [tensorflow/tensorflow#25064]
**Describe the documentation issue**

With my python client i can call my model server properly with the code like this:
```
request.inputs["input"].CopyFrom(
    tf.contrib.util.make_tensor_proto([165, 60, 35],dtype=dtypes.int32)
)
response = stub.Predict(request,30.0)
```

And in python terminal i checked the output of the `make_tensor_proto`, i got something like this:
```
>>> tf.contrib.util.make_tensor_proto([165, 60, 35],dtype=dtypes.int32)
dtype: DT_INT32
tensor_shape {
  dim {
    size: 3
  }
}
tensor_content: "\245\000\000\000<\000\000\000#\000\000\000"
```
**But I cannot make this work with Golang, tried to search with different terms cannot find one example how to fill the `tensor_content` field.**

According to the documentations i got:
```
// Serialized raw tensor content from either Tensor::AsProtoTensorContent or
// memcpy in tensorflow::grpc::EncodeTensorToByteBuffer. This representation
// can be used for all tensor types. The purpose of this representation is to
// reduce serialization overhead during RPC call by avoiding serialization of
// many repeated small items.
TensorContent []byte `protobuf:"bytes,4,opt,name=tensor_content,json=tensorContent,proto3" json:"tensor_content,omitempty"`
```
(do i need to implement the above mentioned `Tensor::AsProtoTensorContent` and `tensorflow::grpc::EncodeTensorToByteBuffer` by myself?)

But tried different ways like:
```
pr          tf.PredictRequest
// Construct the `pr` structure properly.
// ...
pr.Inputs["input"].TensorContent = []byte{165, 60, 35}
```
etc cannot make it work, always resulted in error message:
```
panic: rpc error: code = Internal desc = transport: received the unexpected content-type "text/plain; charset=utf-8"
```

**Also if i want to send such a request in JSON, what should i put in the `tensor_content` field:**
```
{
  "model_spec": {
    "name": "gender",
    "version": "1"
  },
  "inputs": {
    "input": {
      "dtype": 3,
      "tensor_shape": {
        "dim": [
          {
            "size": 3
          }
        ]
      },
      "tensor_content": "WzEsMl0="
    }
  }
}
```

Pls help to provide a proper example in the corresponding docs, thanks.

**Comment by msymp** [comment]
@lnshi , TensorFlow r1.12.0 does not seem to support your Golang interfaces for your planned _Tensor::AsProtoTensorContent_ and _tensorflow::grpc::EncodeTensorToByteBuffer_
You may have to implement them yourself and invoke appropriate TensorFlow APIs.

**Comment by ebrevdo** [comment]
It's somewhat nontrivial for dt.string; but for other data types it's relatively straightforward to implement a hacky version yourself.  Sadly I don't know golang so I can't translate into the language's syntax but basically:

if you have a vector of contiguous memory, the tensor_content is literally just that memory copied through.  So for example if you have a vector of 4 integers, you'd just copy the underlying memory buffer into tensor_content.  Assume a row-major format.

Same with all contiguous memory representations: floats, bools, ints.

BTW for bools, i dont know if golang does this optimization but in c++, std::vector<bool> uses a bitset rep so it's not a direct copy in that one case.  you have to ensure bools are encoded as integers.
