### ISSUE TITLE
Latest commit in deprecation.py breaks R TensorFlow client 

### ISSUE THREAD

**Issue by skeydan** [tensorflow/tensorflow#25067]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Fedora 28
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): nightly (r1.13)
- Python version: 3.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

Hi,

the commit 

https://github.com/tensorflow/tensorflow/commit/b97727bc3c7a9216670f361b639a60ed516917e0#diff-fa5fb3b8d9f512ad269f7eb67903ec2b

breaks the R TensorFlow client which uses embedded Python from R (see https://github.com/rstudio/tfdatasets/issues/17)

Specifically, the line

```
frame = stack[-4 if outer else -3]
```

triggers the error

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  IndexError: list index out of range

Detailed traceback: 
  File "/home/key/anaconda3/envs/tf-master-1215/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 314, in new_func
    _call_location(), decorator_utils.get_qualified_name(func),
  File "/home/key/anaconda3/envs/tf-master-1215/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 103, in _call_location
    frame = stack[-4 if outer else -3]
```

on our side. For us, in one specific example, instead of a list with at least 4 items, `stack` contains a list of 2 tuples, each of which are of length 6.

Unfortunately, this will error and stop execution every time a new deprecation warning is issued.

Current workaround on our side is https://github.com/rstudio/tensorflow/pull/287, however this comes at the cost of totally disabling deprecation warnings.

Is there anything you could do to make this change compatible?

Thanks,
Sigrid

**Comment by martinwicke** [comment]
@jtkeeling could you look at this? I think it's simply a matter of adding bounds checking before accessing the higher levels of the stack.

**Comment by jtkeeling** [comment]
I'll take a look now

**Comment by skeydan** [comment]
Great, thanks so much for reacting this fast! Is there any chance this could still make it into 1.13?

**Comment by martinwicke** [comment]
@aselle would be the decider on that.

**Comment by skeydan** [comment]
Great, thanks a lot for the quick fix, I just tested with the nightly and it works!
@aselle it would be great if you could answer reg. 1.13, we do have a temporary workaround but in case that's not needed we'd remove it :-)
Thanks!
