### ISSUE TITLE
Problem in installing tensorflow on window 8.1

### ISSUE THREAD

**Issue by llAamirll** [tensorflow/tensorflow#25063]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : **window 8.1, 64bit** ,,,intel Core i3-5015U Processor,,,,2.1 GHz Processor,,,,,,4 GB DDR3
- TensorFlow installed from: **conda** 
- Python version: 3.5
- Installed using virtualenv: conda
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0
- GPU model and memory: NVIDIA geforce 820M

**Describe the problem** 

(py35) C:\Users\AAMIR SIDDIQUI>conda install tensorflow
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - tensorflow

Current channels:

  - https://conda.anaconda.org/conda-forge/win-32
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-32
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-32
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-32
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**i tried this also but nothing worked**

(py35) C:\Users\AAMIR SIDDIQUI>conda search tensorflow --channel conda-forge
Loading channels: done

PackagesNotFoundError: The following packages are not available from current cha
nnels:

  - tensorflow

Current channels:

**Comment by rootkitchao** [comment]
This seems to be an issue with anaconda configuration.Suggest another place to ask.

**Comment by msymp** [comment]
@llAamirll , Please try the following steps to do a conda install on Windows for TensorFlow 1.10.0 ; There is no GPU support.
Create a conda environment called tensorflow:
_$ conda create -n tensorflow python=3.5_
A community maintained conda package is available. Use the conda install instructions shown here:
_https://anaconda.org/conda-forge/tensorflow_

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. Please open new ticket if you see similar issue again. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
