### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by trodaway** [tensorflow/tensorflow#25072]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro (version: 1803, build: 17134.523)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A (using a Dell G5 5587 laptop)
- TensorFlow installed from (source or binary): N/A
- TensorFlow version: 1.12.0 (tensorflow-gpu)
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip (via PyCharm installer)
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 9.0
- GPU model and memory: GeForce 1060 with Max-Q Design (version: 24.21.14.1131)

**Describe the problem**
Getting an error regarding the not finding the dll file. The file I presume it's referring to is `‪C:\tools\cuda\bin\cudnn64_7.dll`, which has been added to the path (well, the folder containing it has).

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Downloaded/installed prerequisites according to TensorFlow site
Created virtual environment (within PyCharm)
Installed TensorFlow (using the automatic pip options within PyCharm)
Entered python from the terminal
`import tensorflow`
Error/traceback below produced
Trawled online to try to find solutions.... ending with writing this

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\b5027438\PycharmProjects\DAFNI-UO\venv2\lib\site-packages\tensorflow\__init__.py", l
ine 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\b5027438\PycharmProjects\DAFNI-UO\venv2\lib\site-packages\tensorflow\python\__init__
.py", line 59, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\b5027438\PycharmProjects\DAFNI-UO\venv2\lib\site-packages\tensorflow\core\framework\
graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\b5027438\PycharmProjects\DAFNI-UO\venv2\lib\site-packages\google\protobuf\descriptor
.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by trodaway** [comment]
I've resolved the error following the instructions listed here:
https://stackoverflow.com/questions/52092810/tensorflow-error-dll-load-failed-the-specified-procedure-could-not-be-found/53111377#53111377

Whilst it's working, I think this probably needs addressing in the installation, as it goes against what TensorFlow apparently requires (and therefore installs automatically)!

**Comment by ymodak** [comment]
@trodaway Thanks for the link. Can you please tell which solution worked for you specifically?
Installing tf 1.6 wheel or lowering your protobuf version to 2.6.0

**Comment by trodaway** [comment]
@ymodak It was the lowering of the protobuf version (to 3.6.0) that seemed to do the trick.

**Comment by ymodak** [comment]
Closing since its resolved. Thanks!

**Comment by gladmortal** [comment]
The Fix is not working with tensor-flow 2.0, It require protobuf >= 3.6.1

**Comment by kamarajanis** [comment]
> I've resolved the error following the instructions listed here:
> https://stackoverflow.com/questions/52092810/tensorflow-error-dll-load-failed-the-specified-procedure-could-not-be-found/53111377#53111377
> 
> Whilst it's working, I think this probably needs addressing in the installation, as it goes against what TensorFlow apparently requires (and therefore installs automatically)!

Thank you helped a lot

**Comment by Mostafa-Nakhaei** [comment]
Had the same issue. I was trying to solve it for more than 3 hours and finally Bingo, as easy as the following:
Pip uninstall protobuf
pip install protobuf==3.6.0

**Comment by MIPromis** [comment]
Mostafa-Nakhaei, it's working too by doing the same procedure as you did
