### ISSUE TITLE
Build Model in Python and Run in Java Example

### ISSUE THREAD

**Issue by anjishnu** [tensorflow/tensorflow#2507]
How would one go about doing this, and are there any examples?

**Comment by andrewharp** [comment]
There's no Java API for Tensorflow yet, so this is not possible to do directly.

However, in the Android example project we run inference from Java via JNI: see [tensorflow_jni.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/jni/tensorflow_jni.cc) and [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorflowClassifier.java](TensorflowClassifier.java)

You'll likely want to use [freeze_graph](https://www.tensorflow.org/versions/r0.8/how_tos/tool_developers/index.html#freezing) on your GraphDef first to merge your checkpoint values in, letting you load it all as a self-contained file.
