### ISSUE TITLE
tf.Estimator as checkpointable

### ISSUE THREAD

**Issue by agniszczotka** [tensorflow/tensorflow#25076]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary 
- TensorFlow version (or github SHA if from source): 1.12

**Provide the text output from tflite_convert**

```
ValueError: `Checkpoint` was expecting a checkpointable object (an object derived from `CheckpointableBase`), got <tensorflow.python.estimator.canned.dnn.DNNClassifier object at 0x11b370e48>. If you believe this object should be checkpointable (i.e. it is part of the TensorFlow Python API and manages state), please open an issue.

```

Model:
```
self.classifier = tf.estimator.DNNClassifier(
            feature_columns=my_feature_columns,
            # Two hidden layers of 10 nodes each.
            hidden_units=[10, 10],
            # The model must choose between 3 classes.
            n_classes=3)
```
I want to save checkpoints on demand in different directories. I use external optimizer for hyperparameter search ray-tune, which requires implementation of checkpointing which is control by scheduler from ray-tune optimizations and does not interfere into tf.Estimator internal saving procedure.  tf.train.Checkpoint looks like the perfect choice to save checkpoints on demand, yet does not work with tf.estimotor.

**Comment by allenlavoie** [comment]
Can you use [`Estimator.export_saved_model`](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#export_saved_model)? That will also export the Estimator's graph, but the SavedModel includes a training checkpoint. You could also peek inside the Estimator's model_fn, where there should be a training checkpoint just sitting around (assuming `train` was already called).

I think this would be a great thing to do once Estimator uses functions referencing variables which are accessible outside the Estimator. That is a long way off. (CC @karmel )

**Comment by agniszczotka** [comment]
Hi @allenlavoie. Yes, I could use Estimator.export_saved_model. I prefer to relay on checkpointing, to avoid additional performance bottleneck related to exporting the model.
I implemented a toy example how to use checkpointing with ray.tune and the tf.Estimator [here], which relays on saving checkpoint in the end of tf.Estimator.train()(https://github.com/agniszczotka/PBT-TF.Estimator-with-Ray.Tune/blob/master/trainable_estimator_with_pbt.py). 

Indeed. tf.Estimator as chekpointable would perfect.

**Comment by Saduf2019** [comment]
@agniszczotka 
Could you please try on latest stable version of tf and let us know if this is still an issue.Thanks!
