### ISSUE TITLE
How I can convert .tflite model to a .pb frozen graph or a keras model? 

### ISSUE THREAD

**Issue by WeiyiLi** [tensorflow/tensorflow#25085]
I have a post-training quantized .tflite model and would like to convert it back to either a .pb frozen graph or keras model. How can I achieve this?

I have searched a lot but didn't find any solutions or any hints. Anyone has ideas about this?

**Comment by karimnosseir** [comment]
Hi,
Currently we don't support this, and no plan in the near future.

Thanks

**Comment by paroque28** [comment]
Hi @karimnosseir,
Is there any way I can use a tflite model in TF serving?

**Comment by karimnosseir** [comment]
@paroque28 Not sure what do you mean by TF Serving. If you mean in python then yes.
You can use our Python API.
https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_python

**Comment by paroque28** [comment]
I mean with this: https://www.tensorflow.org/tfx/guide/serving
https://github.com/tensorflow/serving

**Comment by paulo-raca** [comment]
Same here, is there a solution?

Apparently [it was possible before](https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/contrib/lite/toco/g3doc/cmdline_examples.md#convert-a-tensorflow-lite-flatbuffer-back-into-tensorflow-graphdef-format-) and got dropped on TF2.0

However that version was unable to convert my model due an unimplemented operation (PRElu).

I've also seen it done in [hacky ways](https://gist.github.com/tworuler/bd7bd4c6cd9a8fbbeb060e7b64cfa008), but proper tool support would be great
