### ISSUE TITLE
Object Detection API Android demo performance issue

### ISSUE THREAD

**Issue by anamozov** [tensorflow/tensorflow#25083]
**System information**
- Windows 10:
- Android app testing on LG Nexus 5:
- TensorFlow installed from source:
- TensorFlow version: 1.12
**Describe the problem**
I have built Object Detection API Android demo and testing on LG Nexus 5. But it has following performance issue:
After some object is detected e.g. "person", it is keeping to show bounding box and score for last detected object even if the camera is capturing scene with no objects e.g. black screen.  Screenshots are given below.
**Any other info / logs**
Project has been built using following configuration: 
def nativeBuildSystem = 'none'
Trained Model: SSD MobileNet
<b>Screenshots</b>
With object:
![screenshot_20190122-094725](https://user-images.githubusercontent.com/27653152/51506149-1cadec80-1e2e-11e9-9cf6-6582e5448cf3.png)
Without object:
![screenshot_20190122-100945](https://user-images.githubusercontent.com/27653152/51506151-1fa8dd00-1e2e-11e9-9539-a6f5ddd699ce.png)

**Comment by FranciscoSP** [comment]
@anamozov You need to compile the "libtensorflow_demo.so" for your phone architecture, it is used for the tracking. First try to add this to your project: [https://github.com/miyosuda/TensorFlowAndroidDemo/tree/master/app/src/main/jniLibs](url).

**Comment by anamozov** [comment]
As @FranciscoSP the issue is resolved by adding object tracking to the project, which is building the project using bazel.

**Comment by salim124** [comment]
@jvishnuvardhan, @FranciscoSP  I'm also facing one issue in the tenserflow demo app. 
 Issue : Showing lag on camera preview, happening only on google pixel device (Android OS: Pie), Could you please help me this?

**Comment by anamozov** [comment]
@salim124 can you explain the issue in more detail?
