### ISSUE TITLE
Estimator 1.13 doesn't build against Tensorflow 1.13

### ISSUE THREAD

**Issue by jayfurmanek** [tensorflow/tensorflow#25089]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL ppc64le
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13 (preRC)
- Python version: 3.6
- Installed using virtualenv? pip? conda?:  pip install from .whl
- Bazel version (if compiling from source): 19.2
- GCC/Compiler version (if compiling from source): 4.8
- CUDA/cuDNN version: 10.0/7.4
- GPU model and memory: P100/16GB

**Describe the problem**

Tensorflow-Estimator built from the 1.13 branch fails to compile against fully built Tensorflow 1.13

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I used this bazel rc file to build Tensorflow (*not 2.0*)
```
build --action_env PYTHON_BIN_PATH="/home/furmanek/anaconda3/bin/python"
build --action_env PYTHON_LIB_PATH="/home/furmanek/anaconda3/lib/python3.6/site-packages"
build --python_path="/home/furmanek/anaconda3/bin/python"
build --action_env OMP_NUM_THREADS="1"
build:xla --define with_xla_support=true
build --config=xla
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="1"
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda"
build --action_env TF_CUDA_VERSION="10.0"
build --action_env CUDNN_INSTALL_PATH="/usr/local/cuda-10.0"
build --action_env TF_CUDNN_VERSION="7"
build --action_env TF_NCCL_VERSION=""
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="3.5,7.0"
build --action_env TF_CUDA_CLANG="0"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/gcc"
build --config=cuda
test --config=cuda
build:opt --copt=-mcpu=native
build:opt --define with_default_optimizations=true
```

`bazel build tensorflow/tools/pip_package/build_pip_package`
`./bazel-bin/tensorflow/tools/pip_package/build_pip_package ./`
pip install..
`bazel build //tensorflow_estimator/tools/pip_package:build_pip_package`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

TFE Build fail:
```
File "/home/furmanek/.cache/bazel/_bazel_furmanek/fa10fc9090d5b9056cb4055c758fdcae/sandbox/processwrapper-sandbox/1/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/create_tensorflow_estimator.python.estimator_api_1_estimator_python_api_gen_compat_v1.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "/home/furmanek/.cache/bazel/_bazel_furmanek/fa10fc9090d5b9056cb4055c758fdcae/sandbox/processwrapper-sandbox/1/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/create_tensorflow_estimator.python.estimator_api_1_estimator_python_api_gen_compat_v1.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/estimator_lib.py", line 54, in <module>
    from tensorflow_estimator.python.estimator.mode_keys import ModeKeysV2
  File "/home/furmanek/.cache/bazel/_bazel_furmanek/fa10fc9090d5b9056cb4055c758fdcae/sandbox/processwrapper-sandbox/1/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/create_tensorflow_estimator.python.estimator_api_1_estimator_python_api_gen_compat_v1.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/mode_keys.py", line 22, in <module>
    from tensorflow.python.training.mode_keys import ModeKeys
ModuleNotFoundError: No module named 'tensorflow.python.training.mode_keys'
Target //tensorflow_estimator/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.044s, Critical Path: 1.96s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

The problem is this commit (https://github.com/tensorflow/tensorflow/commit/8bcc801a7cd748e7d9d47f0f5d7ebd84a2f2eaea) was done in Tensorflow master, and this commit (https://github.com/tensorflow/estimator/commit/f7640c1aa61e798fdde5001ed42237ab7f941667) is in Estimator 1.13.
It's probably best to pull that Tensorflow commit into Tensorflow 1.13.

Found on ppc64le, but is not platform specific.

**Comment by case540** [comment]
I was able to build Estimator r1.13 against TF r1.13 without issue.

pip install tensorflow==1.13rc0
cd ./estimator_repo
git checkout origin/r1.13
bazel build //tensorflow_estimator/...

Try fetching latest Estimator repo and make sure you're on the branch. Make sure you're building TF from release branch.

**Comment by jayfurmanek** [comment]
Did the Estimator 1.13 branch get reset?
Late last week, it was sitting at much later commit and had additions through January 14th or so.
Now it looks like it branched earlier, before the mode_keys API was added.

We can close this, but man, please somehow let people know if you're going to rewrite history like that. Yikes.

thx!
