### ISSUE TITLE
tf.keras.layers.UpSampling2D - static shapes for ResizeNearestNeighbor are NOT inferred in GraphDef (with `add_shapes=True`)

### ISSUE THREAD

**Issue by sjain-stanford** [tensorflow/tensorflow#25086]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **n/a**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **1.12**
- Python version: **3.6**
- Bazel version (if compiling from source): **n/a**
- GCC/Compiler version (if compiling from source): **n/a**
- CUDA/cuDNN version: **CUDA 9 / cuDNN 7**
- GPU model and memory:  **n/a**

### Premise:
Assume we're given a `GraphDef` that was serialized as `graph.as_graph_def()`. To infer static shapes of every node in this graph and store them as `_output_shapes` attr, TensorFlow [provides](https://www.tensorflow.org/api_docs/python/tf/Graph#as_graph_def) the option`add_shapes=True`.

### Issue:
Let's consider the two APIs that internally use `ResizeNearestNeighbor` kernel:
- `tf.image.resize_nearest_neighbor`
- `tf.keras.layers.UpSampling2D`

The static shape attr (`_output_shapes`) for `ResizeNearestNeighbor` node is correctly inferred when created with `tf.image.resize_nearest_neighbor` API. Yet using `tf.keras.layers.UpSampling2D` results in incomplete shape information for height and width dims.

### Minimal examples:

**Using `tf.image.resize_nearest_neighbor` static shapes are inferred correctly:**
```python3
import tensorflow as tf

# Prepare `GraphDef`
tf.reset_default_graph()
input = tf.placeholder(tf.float32, shape=[None, 26, 128, 256])
output = tf.image.resize_nearest_neighbor(input, (52, 256))
graph_def = tf.get_default_graph().as_graph_def()

# Import `GraphDef` and restore static shapes
tf.reset_default_graph()
with tf.Session(graph=tf.Graph()) as sess:
    tf.import_graph_def(graph_def, name='')
    output_graph_def = tf.get_default_graph().as_graph_def(add_shapes=True)

# Check shapes
for node in output_graph_def.node:
    if node.op == 'ResizeNearestNeighbor':
        print(node.attr["_output_shapes"])
```
**Output**
```
list {
  shape {
    dim {
      size: -1
    }
    dim {
      size: 52
    }
    dim {
      size: 256
    }
    dim {
      size: 256
    }
  }
}
```

**Using `tf.keras.layers.UpSampling2D` static shapes are NOT inferred for H, W:**
```python3
import tensorflow as tf

# Prepare `GraphDef`
tf.reset_default_graph()
input = tf.placeholder(tf.float32, shape=[None, 26, 128, 256])
output = tf.keras.layers.UpSampling2D((2, 2))(input)
graph_def = tf.get_default_graph().as_graph_def()

# Import `GraphDef` and restore static shapes
tf.reset_default_graph()
with tf.Session(graph=tf.Graph()) as sess:
    tf.import_graph_def(graph_def, name='')
    output_graph_def = tf.get_default_graph().as_graph_def(add_shapes=True)

# Check shapes
for node in output_graph_def.node:
    if node.op == 'ResizeNearestNeighbor':
        print(node.attr["_output_shapes"])
```
**Output**
```
list {
  shape {
    dim {
      size: -1
    }
    dim {
      size: -1
    }
    dim {
      size: -1
    }
    dim {
      size: 256
    }
  }
}
```

**Comment by indrasweb** [comment]
Confirmed. This currently breaks TPU models on colab compiled with tf.contrib.tpu.keras_to_tpu_model.

**Comment by sjain-stanford** [comment]
@fchollet - could you please help take a look? Appreciate it!
