### ISSUE TITLE
can't rollback to python 3.6.5 due to recursive dependency between sphinx-doc and python

### ISSUE THREAD

**Issue by xintrac** [tensorflow/tensorflow#25093]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?:Homebrew

**Describe the problem**
I just start learning python programming and wants to use Tensorflow package which requires an order version of Python to be installed. I've searched the web and many recommends using Homebrew for installation. So I tried the following commands but got the errors which I've struggled with for several hours already ...

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Here's the error message i got:
Error: python contains a recursive dependency on itself:
  python depends on sphinx-doc
  sphinx-doc depends on python

**Comment by thecpdubguy** [comment]
I do not think this is a full solution but the temporary workaround that I found to work is this: https://apple.stackexchange.com/a/349379

**Comment by harishperfect** [comment]
Had the same issues, but following these steps got it fixed for me

`$ brew unlink python`

then just install again with `--ignore-dependencies` argument

`$ brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb`

then link python by switching to `python 3.6.5_1`

`$ brew switch python 3.6.5_1`

check if everything went ok

`$ python3 --version`
`Python 3.6.5`

Just to double check if the python is loading from Homebrew

`$ which python3`

If you see `/usr/local/bin/python3`  you are using the Homebrew Python . If you see `/usr/bin/python3`  then you are using the system Python and you likely need to fix your bash profile and/or source it.

**Comment by ThatIndividual** [comment]
@harishperfect when doing this, brew installing 3.6.5 fails precisely when calling sphinx-build, leading to 3.6.5 not being installed at all

**Comment by dedeco** [comment]
I open a question about that on SO: https://stackoverflow.com/questions/54571367/downgrade-to-python-3-6-5-with-brew-error-bin-sh-sphinx-build-command-not-fo

**Comment by dedeco** [comment]
> Had the same issues, but following these steps got it fixed for me
> 
> `$ brew unlink python`
> 
> then just install again with `--ignore-dependencies` argument
> 
> `$ brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb`
> 
> then link python by switching to `python 3.6.5_1`
> 
> `$ brew switch python 3.6.5_1`
> 
> check if everything went ok
> 
> `$ python3 --version`
> `Python 3.6.5`
> 
> Just to double check if the python is loading from Homebrew
> 
> `$ which python3`
> 
> If you see `/usr/local/bin/python3` you are using the Homebrew Python . If you see `/usr/bin/python3` then you are using the system Python and you likely need to fix your bash profile and/or source it.

It doesn't work for me!

**Comment by dedeco** [comment]
I solved:

I solved changing the formula e run locally.


1) Download the original formula 3.6.5 here:

    https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb

2) Comment lines from 199 to 210: 

    cd "Doc" do
      if build.head?
        system bin/"python3", "-m", "venv", "./venv"
        resource("blurb").stage do
          system buildpath/"Doc/venv/bin/python3", "-m", "pip", "install", "-v",
                 "--no-deps", "--no-binary", ":all", "--ignore-installed", "."
        end
      end
    
      system "make", "html"
      doc.install Dir["build/html/*"]
    end

3) Save local as python.rb

4) Run:

    brew install --build-from-source --ignore-dependencies ./python.rb   

5) Use `brew switch python 3.6.5_1` to change to python 3.6

**Comment by andreidore** [comment]
Here is a solution to downgrade python to 3.6.5

https://www.pyimagesearch.com/2019/01/30/macos-mojave-install-tensorflow-and-keras-for-deep-learning/

**Comment by sChalvet** [comment]
Yeah that worked for me

**Comment by ymodak** [comment]
@xintrac Is this still an issue for you? Did you get a chance to try the suggestions posted on this thread yet?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by DannyKong12** [comment]
Sphinx-doc has updated to v2.0, the python 3.6 formula (f2a764ef9...) is attempting to install sphinx using Homebrew, which deprecates functions needed to build docs for python 3.6. Installing a previous version of sphinx won't link since its keg-only, and --force doesn't help. The only way to reinstall after python 3.7 is to not build the docs.

I have uploaded a formulae that seems to work with instructions [here](https://github.com/DannyKong12/homebrew-formulae)

```
brew unlink python                                          # if 3.7 is installed
brew tap dannykong12/formulae
brew install dannykong12/formulae/python
```

It may still be possible to install non-latest sphinx-doc or change the dependency, but I'm not sure how to get it to work

**Comment by rwk506** [comment]
I am also having this problem. As with @dedeco, using @harishperfect's instructions did not work, nor did the instructions for Mojave that included commenting out the python dependency line.

Details on the error I've been fighting, after running the suggested ` brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb` to install (after unlinking 3.7):
```
Last 15 lines from ~/Library/Logs/Homebrew/python/05.make:
2019-05-07 13:05:37 -0700

make
html

mkdir -p build
Using existing Misc/NEWS file
PATH=./venv/bin:$PATH sphinx-build -b html -d build/doctrees -D latex_elements.papersize=  . build/html 
/bin/sh: sphinx-build: command not found
make: *** [build] Error 127

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
csound: add Python bindings https://github.com/Homebrew/homebrew-core/pull/39418
python: gdbm fix https://github.com/Homebrew/homebrew-core/pull/38268
python@2: zlib and gdbm fixes https://github.com/Homebrew/homebrew-core/pull/38241
python@*: setuptools 41.0.1, pip 19.1.1 https://github.com/Homebrew/homebrew-core/pull/39225
brew install gdb with python 3 built, but gdb debug fail https://github.com/Homebrew/homebrew-core/issues/38934
```

I do have sphinx installed:
```
>>> which sphinx-build
/usr/local/bin/sphinx-build
>>> sphinx-build --version
sphinx-build 2.0.1
```
I tried adding this directly to my path and re-attempting an install with Homebrew, but it gives the same error.

I've installed the formulae from @DannyKong12 (THANK YOU) and this seems to work for now.

**Comment by hxmwr** [comment]
> I am also having this problem. As with @dedeco, using @harishperfect's instructions did not work, nor did the instructions for Mojave that included commenting out the python dependency line.
> 
> Details on the error I've been fighting, after running the suggested ` brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb` to install (after unlinking 3.7):
> 
> ```
> Last 15 lines from ~/Library/Logs/Homebrew/python/05.make:
> 2019-05-07 13:05:37 -0700
> 
> make
> html
> 
> mkdir -p build
> Using existing Misc/NEWS file
> PATH=./venv/bin:$PATH sphinx-build -b html -d build/doctrees -D latex_elements.papersize=  . build/html 
> /bin/sh: sphinx-build: command not found
> make: *** [build] Error 127
> 
> Do not report this issue to Homebrew/brew or Homebrew/core!
> 
> These open issues may also help:
> csound: add Python bindings https://github.com/Homebrew/homebrew-core/pull/39418
> python: gdbm fix https://github.com/Homebrew/homebrew-core/pull/38268
> python@2: zlib and gdbm fixes https://github.com/Homebrew/homebrew-core/pull/38241
> python@*: setuptools 41.0.1, pip 19.1.1 https://github.com/Homebrew/homebrew-core/pull/39225
> brew install gdb with python 3 built, but gdb debug fail https://github.com/Homebrew/homebrew-core/issues/38934
> ```
> 
> I do have sphinx installed:
> 
> ```
> >>> which sphinx-build
> /usr/local/bin/sphinx-build
> >>> sphinx-build --version
> sphinx-build 2.0.1
> ```
> 
> I tried adding this directly to my path and re-attempting an install with Homebrew, but it gives the same error.
> 
> I've installed the formulae from @DannyKong12 (THANK YOU) and this seems to work for now.

Have the same issue

**Comment by ClementWalter** [comment]
I suggest using `pyenv` for managing python versions

```
brew install pyenv
brew install pyenv-virtualenv
pyenv install 3.6.5
pyenv virtualenv 3.6.5 my_env
```

**Comment by DanielZambelli** [comment]
Used `brew link python 3.6.5_1`
