### ISSUE TITLE
Export Control Classification Number (ECCN) for Tensorflow

### ISSUE THREAD

**Issue by zygfrydw** [tensorflow/tensorflow#25105]
**System information**
- TensorFlow version: 1.8.0
- Doc Link:

I would like to use Tensorflow in commercial software which will be sold in the U.S. For this reason, the legal department asks me about Export Control Classification Number (ECCN) for Tensorflow library. From my understanding, the open sources software is not subject to [Encryption and Export Administration Regulations (EAR)](https://www.bis.doc.gov/index.php/policy-guidance/encryption/1-encryption-items-not-subject-to-the-ear). 
Can anyone confirm that Tensorflow is not a subject to EAR or point a ECCN class for Tensorflow? 

Does Tensorflow use any encryption functionality, which should be mention when applying for ECCN for software which uses Tensorflow?

**Comment by martinwicke** [comment]
We cannot give you legal advice. 

I can say, however, that TensorFlow is open-source, and that TensorFlow itself does not contain any encryption functionality (although its dependencies may). 

Closing because we won't be able to give legal advice.
