### ISSUE TITLE
Xcode: How to use an static library (a.framework) which force_load  libtensorflow-core.a?

### ISSUE THREAD

**Issue by ronnie-tian** [tensorflow/tensorflow#25104]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iphone 7
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.6
- Python version: 
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

I'm trying to provide an IOS static library as an SDK (named demo.framework) using tensorflow. By tensorflow's instruction, I must link libTensorflow.a with force_load flag in my project. So I link libTensorflow.a with force_load flag in demo.framework's project, and build a library(demo.framework).

In a test, I create a sample app project (appXXX), and link my demo.framework to use the SDK. Compiling was success, but when running it gives the error:

Not found: No session factory registered for the given session options: {target: "" config: } Registered factories are {}.

I try to solve this by link libTensorflow.a with force_load flag for "other link flags" in my appXXX's project, it works fine but that is not what I want (In my option, appXXX needn't be care of tensorflow, it just care of demo.framework). How can I provide a "clean" demo.framework library without force_load any library in appXXX? 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @ronnie-tian ! 1.x versions are not supported anymore. Please create a new issue if it still persists in the 2.9 version. Thank you!
