### ISSUE TITLE
Building error on debian, too many commands in cuda-include genrule

### ISSUE THREAD

**Issue by nmoran** [tensorflow/tensorflow#25107]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): debian buster
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.12
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.17.2 (same observed with 0.15.2 and 0.19.1)
- GCC/Compiler version (if compiling from source): gcc-6
- CUDA/cuDNN version: 9.2.148/7.0.5
- GPU model and memory: Nvidia Ti 1080 8GB

**Describe the problem**
While trying to build tensorflow from source encounter segmentation fault from bash executable which I suspect is caused by a line in an automatically generated script that is too long.

The automatically generated script is `bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda-include.genrule_script.sh` which is generated from the genrule that appears in the automatically generated build file at `/home/myusername/.cache/bazel/_bazel_myusername/01d241adc9daa256c4cb8e009a69aaab/external/local_config_cuda/cuda/BUILD`. This genrule lists approximately 35 thousand as outputs which translates into 35 thousand chained copy statements (which succeed if placed on different lines). 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Clone github repository
2. Checkout r1.12 branch
3. Run `configure` script which results in following in `.tf_configure.bazelrc`
```
build --action_env PYTHON_BIN_PATH="/home/nmoran/anaconda3/bin/python"
build --action_env PYTHON_LIB_PATH="/home/nmoran/anaconda3/lib/python3.7/site-packages"
build --python_path="/home/nmoran/anaconda3/bin/python"
build --define with_ignite_support=true
build --define with_xla_support=true
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="1"
build --action_env CUDA_TOOLKIT_PATH="/usr"
build --action_env TF_CUDA_VERSION="9.2"
build --action_env CUDNN_INSTALL_PATH="/usr/lib/x86_64-linux-gnu"
build --action_env TF_CUDNN_VERSION="7"
build --action_env NCCL_INSTALL_PATH="/usr/local/nccl_2.3.7-1+cuda9.2_x86_64/lib"
build --action_env NCCL_HDR_PATH="/usr/local/nccl_2.3.7-1+cuda9.2_x86_64/lib/../include"
build --action_env TF_NCCL_VERSION="2"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="6.1"
build --action_env TF_CUDA_CLANG="0"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/gcc-6"
build --config=cuda
test --config=cuda
build:opt --copt=-march=native
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
```
4, Attempt to build using
`bazel build --config=opt --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package`

**Any other info / logs**
Error message reported is:
```
ERROR: /home/myusername/.cache/bazel/_bazel_myusername/01d241adc9daa256c4cb8e009a69aaab/external/local_config_cuda/cuda/BUILD:206:1: Executing genrule @local_config_cuda//cuda:cuda-include failed (Segmentation fault): bash failed: error executing command /bin/bash bazel-out/host/genfiles/external/local_config_cuda/cuda/cuda-include.genrule_script.sh                                                                        
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.546s, Critical Path: 0.69s
INFO: 9 processes: 9 local.
FAILED: Build did NOT complete successfully
```

First portion of the genrule that is causing the issues:
```
genrule(
    name = "cuda-include",
    outs = [
        "cuda/include/CL/cl.h",
        "cuda/include/CL/cl_d3d10.h",
        "cuda/include/CL/cl_d3d11.h",
        "cuda/include/CL/cl_dx9_media_sharing.h",
        "cuda/include/CL/cl_dx9_media_sharing_intel.h",
        "cuda/include/CL/cl_egl.h",
        "cuda/include/CL/cl_ext.h",
        "cuda/include/CL/cl_ext_intel.h",
        "cuda/include/CL/cl_gl.h",
        "cuda/include/CL/cl_gl_ext.h",
        "cuda/include/CL/cl_platform.h",
        "cuda/include/CL/cl_va_api_media_sharing_intel.h",
        "cuda/include/CL/cl_version.h",
        "cuda/include/CL/opencl.h",
        "cuda/include/CharLS/charls.h",
        "cuda/include/CharLS/publictypes.h",
        "cuda/include/EGL/egl.h",
        "cuda/include/EGL/eglext.h",
        "cuda/include/EGL/eglextchromium.h",
        "cuda/include/EGL/eglmesaext.h",
        "cuda/include/EGL/eglplatform.h",
        "cuda/include/GL/gl.h",
        "cuda/include/GL/gl_mangle.h",
        "cuda/include/GL/glcorearb.h",
        "cuda/include/GL/glext.h",
        "cuda/include/GL/glu.h",
        "cuda/include/GL/glu_mangle.h",
        "cuda/include/GL/glx.h",
        "cuda/include/GL/glx_mangle.h",
        "cuda/include/GL/glxext.h",
        "cuda/include/GL/glxint.h",
        "cuda/include/GL/glxmd.h",
        "cuda/include/GL/glxproto.h",
        "cuda/include/GL/glxtokens.h",
        "cuda/include/GL/internal/dri_interface.h",
        "cuda/include/GL/internal/glcore.h",
        "cuda/include/KHR/khrplatform.h",
        "cuda/include/OpenEXR/Iex.h",
        "cuda/include/OpenEXR/IexBaseExc.h",
        "cuda/include/OpenEXR/IexErrnoExc.h",
        "cuda/include/OpenEXR/IexExport.h",
        "cuda/include/OpenEXR/IexForward.h",
...
```

**Comment by nmoran** [comment]
Looking a bit deeper, seems something is going wrong when this rule goes from the build file at `./third_party/toolchains/gpus/cuda/BUILD` which lists 980 header files to the automatically generated one in the cache folder which has 35k files. This corresponds to every header file in the `/usr` folder. 

I suspect this is not showing up in other builds as there is a separate folder for cuda (e.g. `/usr/local/cuda`), whereas on debian the cuda headers and libraries get installed to `/usr/include` and `/usr/lib/x86_64-linux-gnu`.

**Comment by jvishnuvardhan** [comment]
@nmoran  Could you follow the instructions [here](https://github.com/rnreich/ubuntu-tensorflow-gpu-all-versions) and let us know how it works. I recently used those steps and successfully installed tensorflow-gpu. If you had already resolved the issue, please close the issue or let us know. Thanks!

**Comment by nmoran** [comment]
@jvishnuvardhan thanks for looking into this issue. The instructions you link to use the nvidia cuda packages on ubuntu which install the cuda libraries and headers to `/usr/local/cuda`. This issue concerns the debian cuda packages on debian systems which install the cuda libraries and headers to `/usr` which then lead to the above issue with the number of header files that the build process attempts to copy to the cache folder. Is it a case that it is only supported to build on systems where the cuda headers are installed in their own folder and not alongside the standard system header files?

**Comment by jvishnuvardhan** [comment]
@nmoran I followed instructions till git clean -xdf. After that I ran the following commands 
sudo pip3 install numpy
sudo pip3 install --upgrade tensorflow-gpu

It worked for me. No issues. Thanks!

**Comment by nmoran** [comment]
@jvishnuvardhan thanks for looking into this further. However you are installing a prebuilt version and not building from source which is where this issue occurs.

**Comment by ymodak** [comment]
If its still an issue; python 3.7 is supported in TF 1.13, TF 1.12 does not have python 3.7 support.
https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md#release-1130
Please build with TF 1.13 for Python 3.7 support. Thanks!

**Comment by nmoran** [comment]
This issue is still present with 1.13 and is not related to the Python version. It can be circumvented by applying the following patch 

```
--- a/third_party/gpus/cuda_configure.bzl
+++ b/third_party/gpus/cuda_configure.bzl
@@ -1192,7 +1192,7 @@ def symlink_genrule_for_dir(
   genrule = _genrule(
       src_dir,
       genrule_name,
-      " && ".join(command),
+      "\n".join(command),
       "\n".join(outs),
   )
   return genrule
```
which results in copy commands being placed on different lines (instead of appended to form a single command). This avoids causing a segmentation fault with the bash interpreter by passing a command that is too big.

This this change the build almost completes, but results in the following error:
```
ImportError: /home/nmoran/.cache/bazel/_bazel_nmoran/8036d860fa88ce032f480e5d19802b14/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZTIN6icu_638ByteSinkE
```
This happens with both python 3.7.2 and python 3.6.8
