### ISSUE TITLE
xavier_initializer documentations claims use of normal distribution but truncated normal is actually being used

### ISSUE THREAD

**Issue by nowozin** [tensorflow/tensorflow#25100]
**System information**
- TensorFlow version: 1.12
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/contrib/layers/xavier_initializer

**Describe the documentation issue**

According to the documentation the Xavier initializer allows use of both the uniform distribution and the normal distribution.  However, when passing `uniform=False` to `xavier_initializer`, the code in `variance_scaling_initializer` actually uses a truncated normal distribution instead, [code link](https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/contrib/layers/python/layers/initializers.py#L146).

The fix would consist of adjusting the documentation to provide details about the truncated Normal sampling.

**Comment by I-Hong** [comment]
@MarkDaoust and @nowozin , is that okay if I amend the description in the document and submit a PR?

**Comment by ymodak** [comment]
Closing this now since the `tf.contrib` module is deprecated. Thanks!
