### ISSUE TITLE
Tensorboard feature request - Text summary

### ISSUE THREAD

**Issue by cgorman** [tensorflow/tensorflow#2510]
Would it be reasonable to add a basic text summary feature to Tensorboard? Personally I've run my network a few dozen times with really minor changes between them for testing and it would be really useful if there was a field where I could put some arbitrary text where I just wrote the key differences in my runs.

For example, on the Events page (or somewhere else) there would be a dropdown, similar to the summaries on the Events and Histograms page, with text I added (either hardcoded or as a script argument) that says what I did differently this run. Maybe I would print out the argument values for each run as well, that would be pretty useful, but basically something where I can say "What did I do with this run again? Why was it different than the one before? Oh yeah I changed the batch size" or "Oh yeah I used my other dataset instead."

Obviously if it's arbitrary text you could maybe use it to write up a description of the network or whatever you want.

**Comment by girving** [comment]
@danmane: Unless you're planning to work on this soon, let's mark as contributions welcome.

**Comment by chihuahua** [comment]
We now have a text summary. See https://www.tensorflow.org/versions/master/api_docs/python/tf/summary/text
