### ISSUE TITLE
Any project about the evaluation of music or piano

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/tensorflow#25118]
Dear,
Is there any project about evaluating the music or piano music,
When we get many datasets of the same music from many people,
How could we evaluate one of them,that is ,the label is the grad of the music is A ,B,C or D, 
or just score between 0~100, Could we do something about this?
Any advice or suggestion will be good.
If U have any question,Please do not hesitate to tell me.
Thx

**Comment by ymodak** [comment]
Probably you can take a look at [TensorFlow Magenta](https://magenta.tensorflow.org/). If you have specific questions related to Magenta project you can post it on [Magenta Github repo](https://github.com/tensorflow/magenta/issues). Thanks!
