### ISSUE TITLE
XLA JIT compiler fails on MLPerf Transformer reference model

### ISSUE THREAD

**Issue by thorjohnsen** [tensorflow/tensorflow#25116]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No, just enabled XLA JIT compilation.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
NVIDIA container based on TF 1.12

- TensorFlow version (use command below):
1.12

- Python version:
3.5.2

- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
10.0.130

- GPU model and memory:
V100 32GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Program exits with the following error message:
2019-01-22 19:29:40.093032: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at retval_op.cc:70 : Internal: Error evaluating model_transformer_decode_decoder_self_attention_bias_mul_0_retval_RetVal input 0 as a compile-time constant.
Error: Unsupported type for iota
2019-01-22 19:29:40.094015: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at xla_ops.cc:408 : Internal: Error evaluating model_transformer_decode_decoder_self_attention_bias_mul_0_retval_RetVal input 0 as a compile-time constant.
Error: Unsupported type for iota
	 [[{{node model_transformer_decode_decoder_self_attention_bias_mul_0_retval_RetVal}} = _Retval[T=DT_FLOAT, index=9](model/Transformer/decode/decoder_self_attention_bias/mul)]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Error evaluating model_transformer_decode_decoder_self_attention_bias_mul_0_retval_RetVal input 0 as a compile-time constant.
Error: Unsupported type for iota
	 [[{{node model_transformer_decode_decoder_self_attention_bias_mul_0_retval_RetVal}} = _Retval[T=DT_FLOAT, index=9](model/Transformer/decode/decoder_self_attention_bias/mul)]]
	 [[{{node cluster_6_1/xla_compile}} = _XlaCompile[Nresources=0, Targs=[DT_INT64, DT_INT32, DT_FLOAT, DT_INT64, DT_INT64, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tconstants=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], function=cluster_6[_XlaCompiledKernel=true, _XlaNumConstantArgs=14, _XlaNumResourceArgs=0], _device="/job:localhost/replica:0/task:0/device:GPU:0"](model/get_train_op/Equal/y, model/get_train_op/gradients/model/Transformer/decode/decoder_stack/layer_0/encdec_attention/layer_normalization/Mean_1_grad/Fill, model/get_train_op/gradients/model/Transformer/decode/decoder_stack/layer_0/encdec_attention/layer_normalization/Mean_1_grad/mod, model/get_train_op/gradients/model/Transformer/encode/embedding_shared_weights/embedding_1/mul_grad/Shape_1, model/loss/smoothing_cross_entropy/softmax_cross_entropy_with_logits/concat/values_0, model/Transformer/encode/embedding_shared_weights/embedding_1/ExpandDims/dim, model/Transformer/decode/decoder_self_attention_bias/Reshape/shape/0, model/Transformer/decode/shift_targets/Pad/paddings, model/Transformer/decode/shift_targets/strided_slice/stack, model/Transformer/decode/shift_targets/strided_slice/stack_1, model/Transformer/decode/shift_targets/strided_slice/stack_2, model/get_train_op/gradients/model/Transformer/encode/dropout/div_grad/Shape_1, model/get_train_op/gradients/model/Transformer/encode/encoder_stack/layer_0/self_attention/layer_normalization/add_grad/Shape_1, model/get_train_op/gradients/model/Transformer/decode/decoder_stack/layer_0/self_attention/layer_normalization/add_grad/Shape_1, global_step/read, model/get_train_op/AssignAdd/_4383, model/Transformer/embedding_shared_weights/embedding_and_softmax/weights/read, IteratorGetNext/_4385, IteratorGetNext/_4387, model/loss/pad_to_same_length/Shape_1/_4389, model/Transformer/encoder_stack/layer_0/self_attention/layer_normalization/layer_norm_scale/read, model/Transformer/encoder_stack/layer_0/self_attention/layer_normalization/layer_norm_bias/read, model/Transformer/decoder_stack/layer_0/self_attention/layer_normalization/layer_norm_scale/read, model/Transformer/decoder_stack/layer_0/self_attention/layer_normalization/layer_norm_bias/read)]]
	 [[{{node model/Transformer/decode/decoder_stack/layer_4/ffn/feed_foward_network/filter_layer/Tensordot/Shape/declustered/_4241}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3582_...eclustered", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transformer/transformer_main.py", line 446, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "transformer/transformer_main.py", line 356, in main
    FLAGS.bleu_threshold)
  File "transformer/transformer_main.py", line 274, in train_schedule
    estimator.train(dataset.train_input_fn, steps=single_iteration_train_steps)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1471, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Error evaluating model_transformer_decode_decoder_self_attention_bias_mul_0_retval_RetVal input 0 as a compile-time constant.
Error: Unsupported type for iota
	 [[{{node model_transformer_decode_decoder_self_attention_bias_mul_0_retval_RetVal}} = _Retval[T=DT_FLOAT, index=9](model/Transformer/decode/decoder_self_attention_bias/mul)]]
	 [[{{node cluster_6_1/xla_compile}} = _XlaCompile[Nresources=0, Targs=[DT_INT64, DT_INT32, DT_FLOAT, DT_INT64, DT_INT64, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tconstants=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], function=cluster_6[_XlaCompiledKernel=true, _XlaNumConstantArgs=14, _XlaNumResourceArgs=0], _device="/job:localhost/replica:0/task:0/device:GPU:0"](model/get_train_op/Equal/y, model/get_train_op/gradients/model/Transformer/decode/decoder_stack/layer_0/encdec_attention/layer_normalization/Mean_1_grad/Fill, model/get_train_op/gradients/model/Transformer/decode/decoder_stack/layer_0/encdec_attention/layer_normalization/Mean_1_grad/mod, model/get_train_op/gradients/model/Transformer/encode/embedding_shared_weights/embedding_1/mul_grad/Shape_1, model/loss/smoothing_cross_entropy/softmax_cross_entropy_with_logits/concat/values_0, model/Transformer/encode/embedding_shared_weights/embedding_1/ExpandDims/dim, model/Transformer/decode/decoder_self_attention_bias/Reshape/shape/0, model/Transformer/decode/shift_targets/Pad/paddings, model/Transformer/decode/shift_targets/strided_slice/stack, model/Transformer/decode/shift_targets/strided_slice/stack_1, model/Transformer/decode/shift_targets/strided_slice/stack_2, model/get_train_op/gradients/model/Transformer/encode/dropout/div_grad/Shape_1, model/get_train_op/gradients/model/Transformer/encode/encoder_stack/layer_0/self_attention/layer_normalization/add_grad/Shape_1, model/get_train_op/gradients/model/Transformer/decode/decoder_stack/layer_0/self_attention/layer_normalization/add_grad/Shape_1, global_step/read, model/get_train_op/AssignAdd/_4383, model/Transformer/embedding_shared_weights/embedding_and_softmax/weights/read, IteratorGetNext/_4385, IteratorGetNext/_4387, model/loss/pad_to_same_length/Shape_1/_4389, model/Transformer/encoder_stack/layer_0/self_attention/layer_normalization/layer_norm_scale/read, model/Transformer/encoder_stack/layer_0/self_attention/layer_normalization/layer_norm_bias/read, model/Transformer/decoder_stack/layer_0/self_attention/layer_normalization/layer_norm_scale/read, model/Transformer/decoder_stack/layer_0/self_attention/layer_normalization/layer_norm_bias/read)]]
	 [[{{node model/Transformer/decode/decoder_stack/layer_4/ffn/feed_foward_network/filter_layer/Tensordot/Shape/declustered/_4241}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3582_...eclustered", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Describe the expected behavior**
Program runs normally.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
1. Clone the mlperf reference from https://github.com/mlperf/training
2. Pass config object to estimator.train that turns global jit compilation on. This is how I did it:
Insert following at line 345 in transformer/transformer_main.py
  config = tf.ConfigProto()
  config.graph_options.optimizer_options.global_jit_level = tf.OptimizerOptions.ON_1
  run_config = tf.estimator.RunConfig(
      model_dir=FLAGS.model_dir,
      session_config=config)
After inserting the above, change line 350 to include run_config:
  estimator = tf.estimator.Estimator(
      model_fn=model_fn, model_dir=FLAGS.model_dir, config=run_config,
      params=params)
3. Change the path /research/transformer to wherever you cloned transformer. This needs to be done in scripts run_preprocessing.sh and run_training.sh
4. Start ./run_and_time.sh. This will download and prepare the training data, which takes a long time. The second time, you can launch ./run_training.sh 1 25 directly in order to avoid downloading the training data 

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jlebar** [comment]
cc @jlebar @sanjoy

**Comment by jlebar** [comment]
cc @thomasjoerg

**Comment by akuegel** [comment]
I have quickly looked into this, and it seems the problem is that this is running with an older version of tensorflow where we didn't support F16 and BF16 in the HloEvaluator. This was added in https://github.com/tensorflow/tensorflow/commit/4143d8d30b1f7d2737426c8c181c88bcd8dba5d5#diff-a685f07f7cd6e728595ee0a72055d248
As you can see, in that change, the error message was also changed to include the type which is not supported, so now you would actually see why it fails instead of just getting "Unsupported type for iota".

**Comment by thorjohnsen** [comment]
This issue appears to have been fixed, Transformer runs fine with XLA enabled in tf-nightly-gpu. I am closing the issue.
