### ISSUE TITLE
Can't import tensorflow-gpu or tensorflow (CPU only) 1.12.0

### ISSUE THREAD

**Issue by ymsaputra** [tensorflow/tensorflow#25117]
Ubuntu: 16.04
Tensorflow installed from Anaconda
Tensorflow version: 1.12.0
Python: Python2.7
CUDA: 9.0
Cudnn: 7.2.1
GPU: Nvidia Quadro P5000 16GB
Command: import tensorflow

[ysaputra@vulcan2 ~]$ python
Python 2.7.13 |Anaconda 4.3.1 (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ysaputra/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/ysaputra/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 47, in <module>
    import numpy as np
  File "/home/ysaputra/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/ysaputra/anaconda2/lib/python2.7/site-packages/numpy/core/__init__.py", line 57, in <module>
    from . import numerictypes as nt
  File "/home/ysaputra/anaconda2/lib/python2.7/site-packages/numpy/core/numerictypes.py", line 111, in <module>
    from ._type_aliases import (
  File "/home/ysaputra/anaconda2/lib/python2.7/site-packages/numpy/core/_type_aliases.py", line 63, in <module>
    _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
  File "/home/ysaputra/anaconda2/lib/python2.7/site-packages/numpy/core/_type_aliases.py", line 63, in <setcomp>
    _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
AttributeError: 'tuple' object has no attribute 'type'
>>> 

I installed new tensorflow-gpu 1.12.0 or tensorflow (CPU only) 1.12.0. However, I have the same problems using import tensorflow after successful installations. It seems the tensorflow is not imported properly. Do you know how to solve it?

**Comment by fix27** [comment]
you must add adjust m.a.x. count red button

**Comment by ymsaputra** [comment]
> you must add adjust m.a.x. count red button

I don't get what do you mean

> Can you please describe the steps you followed to install TF?
> Installing TF CPU version should be fairly easy using pip.

I just simply installed as follows:

pip install --ignore-installed https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.12.0-cp27-none-linux_x86_64.whl for GPU or

pip install --ignore-installed https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp27-none-linux_x86_64.whl

**Comment by ymodak** [comment]
Can you try the setup in a virtual environment as given below:
>virtualenv -p python2 venv-tf
source venv-tf/bin/activate
pip install tensorflow

**Comment by ymsaputra** [comment]
> Can you try the setup in a virtual environment as given below:
> 
> > virtualenv -p python venv-tf
> > source venv-tf/bin/activate
> > pip install tensorflow

Actually, I installed inside Anaconda environment.

**Comment by ymodak** [comment]
@gunan Can you please take a look? Thanks!

**Comment by gunan** [comment]
This looks to be an error in numpy.
Could you check your numpy version?
What do you see when you just try `import numpy as np`
I suspect without even TF, the above will fail.

You may try uninstalling numpy, and installing 1.15.4.
```
pip uninstall numpy
pip install numpy==1.15.4
```

Other than this, you can probably get more help from numpy forums.

**Comment by ymsaputra** [comment]
> pip install numpy==1.15.4

Thanks. It works. In my case, I uninstall numpy 1.16 first and then install 1.15.4. Finally, I install 1.16 version again. Now, tensorflow works well.

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
