### ISSUE TITLE
Trying to build tensorflow from source and fails

### ISSUE THREAD

**Issue by rd16395p** [tensorflow/tensorflow#25111]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): downloaded from github
- Python version: 3.x
- Bazel version (if compiling from source): .18
- GCC/Compiler version (if compiling from source): 6
- CUDA/cuDNN version: 9/7
- GPU model and memory: Quadro K5000

This is my config and error message below, please advise what is a possible fix?
--
./configure
WARNING: Processed legacy workspace file /home/robotlab/Desktop/tensorflow/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/robotlab/.cache/bazel/_bazel_robotlab/install/855b86426ac3a2fcf0dcf5a6fb99b79a/_embedded_binaries/A-server.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.18.0- (@non-git) installed.
Please specify the location of python. [Default is /home/robotlab/.conda/envs/keras_gpu/bin/python]: 

Found possible Python library paths:
  /home/robotlab/.conda/envs/keras_gpu/lib/python3.5/site-packages
Please input the desired Python library path to use.  Default is [/home/robotlab/.conda/envs/keras_gpu/lib/python3.5/site-packages]

Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: y
jemalloc as malloc support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Google Cloud Platform support? [Y/n]: n
No Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [Y/n]: n
No Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Amazon S3 File System support? [Y/n]: n
No Amazon S3 File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Apache Kafka Platform support? [Y/n]: n
No Apache Kafka Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]: y
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with GDR support? [y/N]: n
No GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: n
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 9.0]: 

Please specify the location where CUDA 9.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 

Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7.0]: 

Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:

Do you wish to build TensorFlow with TensorRT support? [y/N]: n
No TensorRT support will be enabled for TensorFlow.

Please specify the NCCL version you want to use. [Leave empty to default to NCCL 1.3]: 2.2.12

Please specify the location where NCCL 2 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:

Invalid path to NCCL 2 toolkit, /usr/local/cuda-9.0/lib/libnccl.so.2 or /usr/local/cuda-9.0/include/nccl.h not found. Please use the O/S agnostic package of NCCL 2
Please specify the NCCL version you want to use. [Leave empty to default to NCCL 1.3]: 

Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 3.0]

Do you want to use clang as CUDA compiler? [y/N]: n
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/x86_64-linux-gnu-gcc-6]: 

Do you wish to build TensorFlow with MPI support? [y/N]: n
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: n

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
Configuration finished
(keras_gpu) robotlab@robotlab:~/Desktop/tensorflow$ bazel build --config=opt --config=cuda --local_resources 2048,.5,1.0 //tensorflow/tools/pip_package:build_pip_package
WARNING: Processed legacy workspace file /home/robotlab/Desktop/tensorflow/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: /home/robotlab/.cache/bazel/_bazel_robotlab/0d7b53c20c90b46f9c06813fc5af2afe/external/grpc/BUILD:1943:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_common.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/robotlab/.cache/bazel/_bazel_robotlab/0d7b53c20c90b46f9c06813fc5af2afe/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: /home/robotlab/.cache/bazel/_bazel_robotlab/0d7b53c20c90b46f9c06813fc5af2afe/external/grpc/BUILD:1943:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_decode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/robotlab/.cache/bazel/_bazel_robotlab/0d7b53c20c90b46f9c06813fc5af2afe/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: /home/robotlab/.cache/bazel/_bazel_robotlab/0d7b53c20c90b46f9c06813fc5af2afe/external/grpc/BUILD:1943:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_encode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/robotlab/.cache/bazel/_bazel_robotlab/0d7b53c20c90b46f9c06813fc5af2afe/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: /home/robotlab/Desktop/tensorflow/tensorflow/contrib/learn/BUILD:17:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
WARNING: /home/robotlab/Desktop/tensorflow/tensorflow/contrib/learn/BUILD:17:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately.
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package (303 packages loaded).
INFO: Found 1 target...
INFO: From Compiling external/snappy/snappy-stubs-internal.cc [for host]:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++
INFO: From Compiling external/snappy/snappy.cc [for host]:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++
INFO: From Compiling external/snappy/snappy-sinksource.cc [for host]:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++
ERROR: /home/robotlab/Desktop/tensorflow/tensorflow/contrib/lite/BUILD:62:1: C++ compilation of rule '//tensorflow/contrib/lite:context' failed (Exit 1)
x86_64-linux-gnu-gcc-6: error: n: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 141.101s, Critical Path: 58.27s
INFO: 243 processes: 243 local.
FAILED: Build did NOT complete successfully
(keras_gpu) robotlab@robotlab:~/Desktop/tensorflow$ bazel build --config=opt --config=cuda --local_resources 2048,.5,1.0 //tensorflow/tools/pip_package:build_pip_package

--
Cheers.

**Comment by ymodak** [comment]
TensorFlow 1.6 and above require cuda compute capability of 3.5 and above for GPU support. The cuda compute capability for your config 3.0 (correct me if I am wrong), that is plausible reason for your build faiilure. However users in the past have managed to build with cuda compute capability 3.0 from sources. You can take a look at [similar attempt](https://github.com/tensorflow/tensorflow/issues/24126) to know more.

**Comment by rd16395p** [comment]
Yes, I have tried that before and I was well aware of this issue going in... the error points to a file named N and I dont know what that is supposed to be.

**Comment by ymodak** [comment]
@gunan Can you PTAL? thanks!

**Comment by rd16395p** [comment]
I actually got a fix. I used NVCC, with Cuda 9.0, CuDNN 7.0, Bazel 2.0, gcc 6, and tf 1.12. If anyone wants a download for CUDA computing 3.0, for python 3.7 on linux, here is the built file. Hope that helps!

https://github.com/rd16395p/tensorflowbuild
