### ISSUE TITLE
Problem about 'placeholder' function

### ISSUE THREAD

**Issue by aitazhixin** [tensorflow/tensorflow#2512]
I installed Tensorflow using Pip in Vmware Simulation Machine Ubuntu Operation System with only CPU Evn.

When I used tensorflow in python 2.7:
>>>import tensorflow as tf
>>>x = tf.placeholder(name="x")

I met one error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: placeholder() takes at least 1 argument (1 given)

This code is an instance in http://download.tensorflow.org/paper/whitepaper2015.pdf

**Comment by vrv** [comment]
The whitepaper is probably out of date / incorrect.  See https://www.tensorflow.org/versions/r0.8/api_docs/python/io_ops.html#placeholder for up to date documentation.

**Comment by aitazhixin** [comment]
>>> x = tf.placeholder(tf.string, name="x")
Thanks!
