### ISSUE TITLE
TF lite has link error when I try to build with build_rpi_lib.sh

### ISSUE THREAD

**Issue by adppark** [tensorflow/tensorflow#25120]
When I try to build for Tensorflow lite(in latest version) occur link error like this.

/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a(nnapi_delegate.o): In function `tflite::NNAPIAllocation::~NNAPIAllocation()':
nnapi_delegate.cc:(.text+0x2c): undefined reference to `NnApiImplementation()'
/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a(nnapi_delegate.o): In function `tflite::NNAPIAllocation::NNAPIAllocation(char const*, tflite::ErrorReporter*)':
nnapi_delegate.cc:(.text+0x110): undefined reference to `NnApiImplementation()'
/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a(nnapi_delegate.o): In function `tflite::NNAPIDelegate::~NNAPIDelegate()':
nnapi_delegate.cc:(.text+0x190): undefined reference to `NnApiImplementation()'
nnapi_delegate.cc:(.text+0x1b4): undefined reference to `NnApiImplementation()'
/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a(nnapi_delegate.o): In function `tflite::addTensorOperands(tflite::Subgraph*, ANeuralNetworksModel*, unsigned int*, std::vector<long long, std::allocator<long long> >*)':
nnapi_delegate.cc:(.text+0x214): undefined reference to `NnApiImplementation()'
/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a(nnapi_delegate.o):nnapi_delegate.cc:(.text+0x504): more undefined references to `NnApiImplementation()' follow
collect2: error: ld returned 1 exit status

how can I fix it?

**Comment by lijiah33** [comment]
I also meet this error,  but it seemed to not  appear in earlier version. I just disable NNApi for the moment. I want to know how to fix it too.

**Comment by mattn** [comment]
I could build this with `tensorflow/lite/nnapi/nnapi_implementation.cc`. But nnapi_implelementation.cc use shm_open. shm_open require build with shared libarry linked to  `-lrt`.

**Comment by mattn** [comment]
But current implementation does not have delegate for GPU on raspberry pi.

**Comment by SherrySheng** [comment]
> I also meet this error, but it seemed to not appear in earlier version. I just disable NNApi for the moment. I want to know how to fix it too.

 I also meet this error, and I want to know how to disable NNApi?

**Comment by jdinkel88** [comment]
> > I also meet this error, but it seemed to not appear in earlier version. I just disable NNApi for the moment. I want to know how to fix it too.
> 
> I also meet this error, and I want to know how to disable NNApi?

in the Makefile (~/tensorflow/lite/tools/make/Makefile) for tflite, you should see this:
BUILD_WITH_NNAPI=true

change it to false and then re-run build_rpi_lib.sh

**Comment by PINTO0309** [comment]
I succeeded in building and testing.
And, Although it is still informal, I tried to enable multithreading.

**PythonAPI Multi Thread - During review, Proposal for @freedomtan**
**[tensorflow/tensorflow#25748](https://github.com/tensorflow/tensorflow/pull/25748)**
**Avoiding build errors, Proposal for @jdinkel88**
**[tensorflow/tensorflow#25120 (comment)](https://github.com/tensorflow/tensorflow/issues/25120#issuecomment-464296755)**

**Build script**
**https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/rpi.md**

**Output destination path**
/home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a
/home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/bin/benchmark_model
/home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/bin/minimal

**Exec test (1) - View summary**
```bash
$ cd /home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/bin
$ ./minimal xxxx.tflite
$ ./minimal xxxx.tflite
$ ./benchmark_model --graph=xxxx.tflite
```

**Exec test (2) - Model load test by Python3**
```bash
$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import tensorflow.contrib.lite as lite
>>> inter = lite.Interpreter(model_path = "xxxx.tflite")
>>> inter.allocate_tensors()
>>> input_details = inter.get_input_details()
>>> print(input_details)
[{'name': 'input', 'quantization': (0.0, 0), 'shape': array([  1, 128, 128,   3]), 'dtype': <class 'numpy.float32'>, 'index': 110}]
```

**Note that you must specify "contrib" at import time.**
`import tensorflow.contrib.lite`

**Comment by dankal444** [comment]
I followed what @PINTO0309 did (or I think so)
1) `git clone https://github.com/tensorflow/tensorflow.git`
2) Edit of `./tensorflow/lite/tools/make/Makefile` file, 
`BUILD_WITH_NNAPI=true`   -->    `BUILD_WITH_NNAPI=false`
3) `./tensorflow/lite/tools/make/download_dependencies.sh`
4) `./tensorflow/lite/tools/make/build_rpi_lib.sh`

It all seems to end succesfully, but when I run:
```
cd /home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv7l/bin
./minimal xxxx.tflite
```
I get error:
`bash: ./minimal: cannot execute binary file: Exec format error`

**Comment by petewarden** [comment]
@aselle, do you have any ideas on this one?

**Comment by 1e100** [comment]
I encountered the same issue with the 64 bit variant of the build script  that I contributed earlier. IMO NNAPI should be disabled in these scripts by default. This can be easily done via a `make` parameter. With it disabled, everything builds fine, and benchmark_model works as expected. If this seems like a reasonable thing to do, I can submit a PR. 

It doesn't seem like #26336 would address the 64-bit build use case. To address it, I think the principled solution would be to define something like `generic-aarc64` target type and handle it similarly in the makefile. I'll suggest it in the issue separately.

**Comment by lolz0r** [comment]
I also experienced this error; it appears that rolling back to an earlier version of Tensorflow fixed this:
` git checkout r1.95`

**Comment by PINTO0309** [comment]
I made Tensorflow v2.0.0-alpha + Tensorflow Lite v1.0 (MultiThread enabled) stand alone installer. 
For RaspberryPi3.
Since it is an alpha version, there may be many bugs.
**https://github.com/PINTO0309/Tensorflow-bin.git**
**tensorflow-2.0.0a0-cp35-cp35m-linux_armv7l.whl**

**Comment by dibet** [comment]
About 
https://github.com/tensorflow/tensorflow/issues/25120#issue-402094367

I fix it as follow

in the file: ./tensorflow/lite/tools/make/targets/linux_makefile.inc

append LIBS += -lrt

**Comment by jvishnuvardhan** [comment]
This is a stale issue. 
Based on above comments, it looks like this was resolved. I will close this issue. Please feel free to reopen if this is still an issue with recent TF lite versions. Thanks!
