### ISSUE TITLE
DNNClassifier estimator train shows unsupported feed type error occasionally 

### ISSUE THREAD

**Issue by raaaaay-c** [tensorflow/tensorflow#25133]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 'v1.12.0-rc2-3-ga6d8ffae09' 1.12.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:  9.0
- GPU model and memory: GeForce GTX 1070 with Max-Q Design

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I have a dataset contains labels with true and false, and a column of English test.
Labels are converted to 1 and 0 as below:
```
      review                                          opinion
0              1  cls late nite music club with shoji tabuchi wh...
1              0  new south valley subdivision taking shape the ...
2              0  celtics visit lakers aim to avoid fourth strai...
3              1  russia signs ceasefire agreement with reservat...
4              1  new j c penney ceo to have limited role report...

```
The data are split into train_df and test_df then created an input_fn for training.

```
 train_input_fn = tf.estimator.inputs.pandas_input_fn(
    train_df, train_df['review'],batch_size=40, num_epochs=5, shuffle=True)
```
When I reach 
```estimator.train(input_fn=train_input_fn, steps=1000)```

It shows 

`tensorflow.python.framework.errors_impl.InternalError: Unsupported feed type`

But after I change the label to floats by df['review'] = df['review']*1.0 
```
      review                                          opinion
0              1.0  cls late nite music club with shoji tabuchi wh...
1              0.0  new south valley subdivision taking shape the ...
2              0.0  celtics visit lakers aim to avoid fourth strai...
3              1.0  russia signs ceasefire agreement with reservat...
4              1.0  new j c penney ceo to have limited role report...

```
The train function works again. 

But this problem occurs occasionally, estimator.train works well if I have review labels in integer with 0 and 1 as the data in the first table.

**Describe the expected behavior**
```estimator.train(input_fn=train_input_fn, steps=1000)``` 
should works without showing unsupported type

**Comment by raymonduui** [comment]
The data type is dtype('int64') while the type of df['review'] is pandas.core.series.Series . Thank you !

**Comment by damnedOperator** [comment]
Same Problem here for me. Ensured that data types in the target column are int64. Still getting an `tensorflow.python.framework.errors_impl.InternalError: Unsupported object type float
`

**Comment by sanatmpa1** [comment]
@raaaaay-c,

Have you checked if you had any rows with missing values like `df[df['review'].isnan()]` since NaN is a special type of floating point value. 

Also since this issue was with TF 1.x and the official support is ended for the same. Can you try updating the latest stable version `2.6.0` and let us know if you still face any challenges with the same. Thanks!
