### ISSUE TITLE
[Feature Request] [python API] make tf.RefVariable._strided_slice_assign public

### ISSUE THREAD

**Issue by mcskatkat** [tensorflow/tensorflow#25136]
**System information**
- TensorFlow version (you are using): 1.12 .0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently slice assignment is (publicly) accessible only indirectly through `strided_slice()` using the `var` kwarg, in a rather convoluted way creating a closure and adding it as an attribute to the generated op.
As a side effect this also adds an unnecessary (and mostly inaccessible) `strided_slice` op, bloating the graph needlessly.

**Will this change the current api? How?**
It will add a public `tf.Variable.strided_slice_assign()` with exactly the same interface as the existing protected version.
The protected function is already de-facto part of the API when called using the supported slicing + assign() syntax, so there is no functional change. It will also not interfere with any existing code using that syntax.

**Who will benefit with this feature?**
People with use cases similar to mine:
I have a rather elaborate slice assign operation than needs to be repeated on several variables, using the same slice. Naively one would just repeat 
`V[...elaborate slicing here...].assign(something)` for all variables V. This creates lots and lots of ops in the graph as the entire index expression gets replicated for each variable, plus the unnecessary and unused `strided_slice` read operation.
Instead one could create the tensors for the indexing (begin, end, stride, masks) once, and then repeatedly call `.strided_slice_assign` for all the variables, resulting in a concise and manageable subgraph.

 I realize that the vast majority of people never call `strided_slice()` or `strided_slice_assign()` directly. However, for the same few for which `strided_slice()` is publicly available, so should `strided_slice_assign()` be.

**Any Other info.**
None

**Comment by alextp** [comment]
The unnecessary ops in the graph, including the redundant read, can be easily pruned at execution time, so they shouldn't cost anything. Also calling strided_slice directly is _really hard_; the correspondence between the subjective python slicing arguments and what the op expects is nontrivial.

For these reasons I don't think we should expose this method.
