### ISSUE TITLE
Tensorflow v2 Limit GPU Memory usage

### ISSUE THREAD

**Issue by cassianocasagrande** [tensorflow/tensorflow#25138]
Need a way to prevent TF from consuming all GPU memory, on v1, this was done by using something like:
```
opts = tf.GPUOptions(per_process_gpu_memory_fraction=0.5)
sess = tf.Session(config=tf.ConfigProto(gpu_options=opts))

```

On v2 there is no Session and GPUConfig on tf namespace.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 18.04.1 (AWS EC2 P2)
- TensorFlow installed from (source or binary): pip install tf-nightly-2.0-preview
- TensorFlow version (use command below):'1.13.0-dev20190117'
- Python version:Python 3.6.5
- CUDA/cuDNN version: 10.0
- GPU model and memory: Tesla K80 12GB

**Comment by ymodak** [comment]
Is per_process_gpu_memory_fraction option not limiting the gpu memory allocation in your case. You can try tf.Session.reset() before starting the second session to set a different memory fraction.

**Comment by martinwicke** [comment]
@jaingaurav also transferring this issue to you since you'll be working on it (soon).

**Comment by jaingaurav** [comment]
A number of new API were added in `tf.config` namespace to support this use case. Please let me know if there is anything we missed regarding this specific issue.

Note that here you'd probably have to setup a virtual gpu with a fixed memory limit. Please let us know if there is a strong reason to support the `per_process_gpu_memory_fraction` option.

**Comment by penguinmenac3** [comment]
The two common settings you earlier used with sessions are found in `tf.config.gpu`. You should probably set them before you start working with any tensors and variables. (tested with 2.0.0-alpha0)
```python
import tensorflow as tf
tf.config.gpu.set_per_process_memory_fraction(0.75)
tf.config.gpu.set_per_process_memory_growth(True)

# your model creation, etc.
model = MyModel(...)
```

@jaingaurav As a use case: I typically use this when _developing on my local machine_ and I want firefox to work well while training a network in the background. Otherwise firefox commonly crashes when you open a new tab because no gpu memory is left. Generally those types of settings are usefull to keep your _local machine_ usable while you have a network training in the background, while happily using your pc (with some stutters of course). However, this works perfectly fine with the current alpha version. :)

**Comment by jaingaurav** [comment]
@penguinmenac3: The new API still supports setting memory growth on a physical GPU. However, this would eventually use up all of the memory. If you'd like to limit the memory growth I'd suggest setting up a single virtual GPU with a memory limit. That way you can ensure that you have the necessary memory allocated upfront and it shouldn't intrude with your other desktop apps. Note that when setting a memory limit, the defined memory is allocated upfront.

Try installing the 2.0 nightly and let me know if that works for you. It'd be great to know given that I removed the `tf.config.gpu.set_per_process_memory_fraction` API, and I'd like to ensure that your use case is covered.

**Comment by matth79** [comment]
> I'd suggest setting up a single virtual GPU with a memory limit.

Do you have a documentation reference?

**Comment by jaingaurav** [comment]
@matth79: Please see the `docstring tf.config.experimental.set_virtual_device_configuration` in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/config.py#L524. This should be part of the generated docs once we release 1.14 or the next 2.0 build.

**Comment by FarzanT** [comment]
@jaingaurav 
Hello, do you know how one can use the tf.config in a Keras session?
Previously, we did:
```
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.8
config.gpu_options.allow_growth = True
set_session(tf.Session(config=config))
```
But now it's
```
tensorflow.config.gpu.set_per_process_memory_fraction(0.75)
tensorflow.config.gpu.set_per_process_memory_growth(True)
```
But how do we pass this session's configuration to Keras? `tf.Session()` is no longer available.

Thank you

**Comment by jaingaurav** [comment]
@FarzanT: Thanks for identifying this issue. I think you've uncovered an issue with the keras API and interaction with 2.0 when using custom session options. We are looking to get this addressed right away.

**Comment by jaingaurav** [comment]
@FarzanT: We just submitted the fix. Essentially all you should need to do is call the tf.config APIs and then keras should internally create a ConfigProto based on what you set.

Also, the `tf.keras.backend.set_session` call has now been removed from the v2 API, since it is not applicable in a v2 world. Note the `tf.keras.backend.set_session` symbol is still available in `tf.compat.v1` as is `tf.Session()`.

**Comment by FarzanT** [comment]
@jaingaurav: Thank you very much. I see that `tf.config.gpu` was moved to `tf.config.experimental`, as I moved from the alpha version to the nightly releases. Unfortunately, I can't find the option to set the memory fraction used (`tensorflow.config.gpu.set_per_process_memory_growth`). Has this option been removed?

Thank you

**Comment by jaingaurav** [comment]
@FarzanT: That API was removed in favor of using virtual GPU devices with a fixed limit. See https://www.tensorflow.org/alpha/guide/using_gpu#limiting_gpu_memory_growth.

**Comment by tobegit3hub** [comment]
Currently we can follow the official document to do that although the APIs are tedious now.

```
gpus = tf.config.experimental.list_physical_devices('GPU')

tf.config.experimental.set_virtual_device_configuration(gpus[0], [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])
```

**Comment by obarak** [comment]
@jaingaurav - regarding:
> @FarzanT: We just submitted the fix. Essentially all you should need to do is call the tf.config APIs and then keras should internally create a ConfigProto based on what you set.
> 
> Also, the `tf.keras.backend.set_session` call has now been removed from the v2 API, since it is not applicable in a v2 world. Note the `tf.keras.backend.set_session` symbol is still available in `tf.compat.v1` as is `tf.Session()`.

As of TF 2.0.0, it seems Keras doesn't pick up the `tf.config.experimental.set_memory_growth(gpu, True)` setting...

**Comment by germanjke** [comment]
> gpus = tf.config.experimental.list_physical_devices('GPU')
> 
> tf.config.experimental.set_virtual_device_configuration(gpus[0], [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-35-d1a1e7bd7d96> in <module>
      1 gpus = tf.config.experimental.list_physical_devices('GPU')
      2 
----> 3 tf.config.experimental.set_virtual_device_configuration(gpus[0], [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])
~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\config.py in set_virtual_device_configuration(device, virtual_devices)
    554     virtual_devices: (optional) Need to update
    555   """
--> 556   context.context().set_virtual_device_configuration(device, virtual_devices)
~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\context.py in set_virtual_device_configuration(self, dev, virtual_devices)
   1269     if self._context_handle is not None:
   1270       raise RuntimeError(
-> 1271           "Virtual devices cannot be modified after being initialized")
   1272 
   1273     self._virtual_device_map[dev] = virtual_devices

RuntimeError: Virtual devices cannot be modified after being initialized
```

have this error on your solution. can you explain me what is Virtual devices and why i can't modify them?

have same problem with memory growth and i don't know what to do with TF2

**Comment by jaingaurav** [comment]
germanjke@ what are you executing prior to this call? If you've executed any ops its too late for us to reconfigure the virtual device. The virtual device is simply a way of slicing up a physical device in separate devices with a fixed memory limit.

**Comment by germanjke** [comment]
@jaingaurav 
The problem was that I had discovered too many JupyterNotebooks. When I closed them, launched one and rebooted kernel everything works. Thank you very much!

**Comment by jpambrun** [comment]
`tf.config.experimental.set_memory_growth(gpu, True)` has no effect for me neither. Is there any known workaround? Alternatively, is there a way to get memory usage from the internal tensorflow allocator (I can't find any documentation on the topic)?

**Comment by biendltb** [comment]
This solution works for me in TF 2.0.0  with RTX 2080 GPU. 

`
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.2
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
`

**Comment by colt18** [comment]
> 
> 
> `tf.config.experimental.set_memory_growth(gpu, True)` has no effect for me neither. Is there any known workaround? Alternatively, is there a way to get memory usage from the internal tensorflow allocator (I can't find any documentation on the topic)?

Same goes for me. Have you been able to figure something out?

**Comment by 12343954** [comment]
> This solution works for me in TF 2.0.0 with RTX 2080 GPU.
> 
> ```
> from tensorflow.compat.v1 import ConfigProto
> from tensorflow.compat.v1 import InteractiveSession
> 
> config = ConfigProto()
> config.gpu_options.per_process_gpu_memory_fraction = 0.2
> config.gpu_options.allow_growth = True
> session = InteractiveSession(config=config)
> ```

above works for me , in TF(gpu)2.0 + RTX2060 6GB + CUDA 10.0 + cuDNN 7.6.5
----------------------------------------------------------------------------------------------------
not works below
https://www.tensorflow.org/alpha/guide/using_gpu#limiting_gpu_memory_growth
```
gpus = tf.config.experimental.list_physical_devices('GPU')

tf.config.experimental.set_virtual_device_configuration(gpus[0], [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])
```

**Comment by VeLKerr** [comment]
@12343954 , what error are you seeing? 

There is a typo in this line:
```
tf.config.experimental.set_memory_growth(gpu, True)
```

You haven't `gpu` variable but `gpus`. `gpus` is a list so you need use the element, e.g. `gpus[0]`.

**Comment by 12343954** [comment]
> @12343954 , what error are you seeing?
> 
> There is a typo in this line:
> 
> ```
> tf.config.experimental.set_memory_growth(gpu, True)
> ```
> 
> You haven't `gpu` variable but `gpus`. `gpus` is a list so you need use the element, e.g. `gpus[0]`.

@VeLKerr Thank you for reminding this, i forgot to copy the full codes.

**Comment by kapilkd13** [comment]
Hi, Is there a reason why tf support gpu memory fraction, instead of memory size(ex. 4gb).
I have build an API, which might be spawned on 8gb or 16gb gpu based on availability. I need to change the fraction accordingly.
Currently I need to obtain available memory from nvidia-smi, and generate appropriate ratio.

**Comment by wuxiaohua1011** [comment]
The following worked for me: 

First use `nvidia-smi` to see if you have any extremely intensive programs running, use
`sudo kill -9 PROCESS_ID` to kill it if you do

Before executing any tensorflow code, put this code:
```
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)
```
And then execute whatever you want. 

Tensorflow v2 has great doc regarding how to use GPU here: [https://www.tensorflow.org/guide/gpu](https://www.tensorflow.org/guide/gpu)

**Comment by fuomag9** [comment]
Does anyone have a black screen in games after receiving " Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED" in tensorflow during training? I've found no solution to this other than rebooting, it fixes both the error (temporarily because it can happen again randomly) and the game issue (which would make it connected to the error itself)

**Comment by Pranav-India** [comment]
Hi @wuxiaohua1011  

In the solution you have mentioned , can limit the amount of memory getting allocated e.g. if I want to use only 70% of the gpu to run my code and keep rest 30% for operations(like running simulation) ?

Thank you

**Comment by pedrohpf** [comment]
Tried everything and nothing was working, turns out I was running this code I had found somewhere to check my GPU:

`from tensorflow.python.client import device_lib`
`device_lib.list_local_devices()`

After removing this and using `set_memory_growth` as others have commented, tensorflow stopped using all my gpu memory. Had no idea that line would affect memory to the point of ignoring `set_memory_growth`, but I guess it did...

**Comment by Zabjaku** [comment]
> Tried everything and nothing was working, turns out I was running this code I had found somewhere to check my GPU:
> 
> `from tensorflow.python.client import device_lib` `device_lib.list_local_devices()`
> 
> After removing this and using `set_memory_growth` as others have commented, tensorflow stopped using all my gpu memory. Had no idea that line would affect memory to the point of ignoring `set_memory_growth`, but I guess it did...

Hi @pedrohpf 

Sorry am new to Tensorflow. Where did you find the code `device_lib.list_local_devices()`? Also where should i put the `set_memory_growth` code? Is it in the model_main_tf2.py?
Thank you.

**Comment by pedrohpf** [comment]
Hello @Zabjaku

At that time I was trying to set tensorflow memory growth so it wouldn't automatically occupy all the memory. So I had used the following code for that, as others have mentioned something similar:

```
devices = tf.config.list_physical_devices('GPU')
try:
    tf.config.experimental.set_memory_growth(devices[0], True)
    print("Success in setting memory growth")
except:
    print("Failed to set memory growth, invalid device or cannot modify virtual devices once initialized.")
```

However, that wasn't working and I was not sure the reason why.
I then happened to remove a certain line of code that I had used before to check if everything was being setup correctly. That code was the following:

```
from tensorflow.python.client import device_lib
device_lib.list_local_devices()
```

After removing this, the previous code of `set_memory_growth` started working correctly. I'm still not sure why that happens, but this is what I found out at the time.

Let me be clear though, the use of `device_lib.list_local_devices()` is what was causing my initial memory growth not working problem. This might give some insight: https://stackoverflow.com/questions/38559755/how-to-get-current-available-gpus-in-tensorflow

I'm not sure where you _should_ put the code in your example. I'm assuming model_main_tf2.py is the main script you use to run everything? I simply used the `set_memory_growth` code right after importing everything in my program.

**Comment by Zabjaku** [comment]
Hi all,

Would like to share how I 'fixed' the OOM issue after trying conuntless of install and uninstall and searching online. Seems like it is a must to install the cuda toolkit from nvidia (https://developer.nvidia.com/cuda-toolkit) (I was hesitant to do it as i am afraid it might affect my previous Tf1, which was working perfectly). After installing the toolkit, the training was able to run without having to add `set_memory_growth`. Also a cause of OOM is too large a `batch_size`, can try from 1 and work your way up. Below are my sys info:

Anaconda: Python 3.8.12
Tensorflow, keras : 2.7.0
cudatoolkit: 11.2.0
cudnn: 8.1.0.77
Graphics card: Nvidia 2070, 12GB
Windows 10

Hope this helps:)

**Comment by tommydino93** [comment]
None of the solutions proposed above worked for me.

What worked (with TF 2.4) was changing the data loading of the `tf.data.Dataset`. Specifically, I switched from using `from_tensor_slices` to using `from_generator`. I am tackling semantic segmentation with volumes of shape 64x64x64. Here's some pseudo code:

```python
input_volumes_list = [...]  # list containing the input volumes that have shape 64x64x64
input_masks_list = [...]  # list containing the corresponding segmentation masks also of shape 64x64x64

# define generator function
def generator_images_and_masks():
    for idx in range(len(input_volumes_list)):
        # extract one image and the corresponding mask
         img = input_volumes_list[idx]
         mask = input_masks_list[idx]

         # convert to TF tensors
         img_tensor = tf.convert_to_tensor(img, dtype=tf.float32)
         mask_tensor = tf.convert_to_tensor(mask, dtype=tf.float32)

         yield img_tensor, mask_tensor

# create dataset using generator function and specifying shapes and dtypes
dataset = tf.data.Dataset.from_generator(generator_images_and_masks, 
                                         output_signature=(tf.TensorSpec(shape=(64, 64, 64), dtype=tf.float32),
                                                           tf.TensorSpec(shape=(64, 64, 64), dtype=tf.float32)))


```
When doing this I don't get the GPU memory error anymore
