### ISSUE TITLE
Build of 1.13 //tensorflow/python/eager:pywrap_tfe_lib fails with internal compiler error: unexpected expression ‘I’ of kind template_parm_index

### ISSUE THREAD

**Issue by Xaenalt** [tensorflow/tensorflow#25144]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Fedora 28
cuda-cusparse-10.0.130-1.fc28.x86_64
cuda-cufft-devel-10.0.130-1.fc28.x86_64
cuda-nvjpeg-devel-10.0.130-1.fc28.x86_64
cuda-cublas-10.0.130-1.fc28.x86_64
cuda-nvrtc-devel-10.0.130-1.fc28.x86_64
cuda-gcc-c++-7.3.1-2.fc28.x86_64
nvidia-driver-cuda-libs-415.27-1.fc28.x86_64
cuda-cublas-devel-10.0.130-1.fc28.x86_64
cuda-extra-libs-10.0.130-1.fc28.x86_64
cuda-nvtx-10.0.130-1.fc28.x86_64
cuda-cusparse-devel-10.0.130-1.fc28.x86_64
cuda-cupti-10.0.130-1.fc28.x86_64
cuda-gcc-7.3.1-2.fc28.x86_64
cuda-cudart-devel-10.0.130-1.fc28.x86_64
cuda-nvjpeg-10.0.130-1.fc28.x86_64
cuda-curand-10.0.130-1.fc28.x86_64
cuda-npp-devel-10.0.130-1.fc28.x86_64
cuda-cudnn-devel-7.4.2.24-1.fc28.x86_64
bazel-0.21.0-1.fc28.x86_64
cuda-nvgraph-devel-10.0.130-1.fc28.x86_64
cuda-nvgraph-10.0.130-1.fc28.x86_64
cuda-cusolver-devel-10.0.130-1.fc28.x86_64
cuda-npp-10.0.130-1.fc28.x86_64
cuda-cudart-10.0.130-1.fc28.x86_64
cuda-nvml-devel-10.0.130-1.fc28.x86_64
nvidia-driver-cuda-415.27-1.fc28.x86_64
cuda-cusolver-10.0.130-1.fc28.x86_64
cuda-cupti-devel-10.0.130-1.fc28.x86_64
cuda-devel-10.0.130-1.fc28.x86_64
cuda-libs-10.0.130-1.fc28.x86_64
cuda-nvtx-devel-10.0.130-1.fc28.x86_64
cuda-10.0.130-1.fc28.x86_64
cuda-curand-devel-10.0.130-1.fc28.x86_64
cuda-nvrtc-10.0.130-1.fc28.x86_64
cuda-cufft-10.0.130-1.fc28.x86_64
cuda-cudnn-7.4.2.24-1.fc28.x86_64

- **TensorFlow version (use command below)**: 1.13
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: bazel-0.21.0-1.fc28.x86_64
- **GCC/Compiler version (if compiling from source)**: cuda-gcc-7.3.1-2.fc28.x86_64
- **CUDA/cuDNN version**: cuda-cudnn-7.4.2.24-1.fc28.x86_64
- **GPU model and memory**: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] 11GB RAM
- **Exact command to reproduce**: 
- # ./configure                                                                                           
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: fdbe3c4d-e72c-4726-a665-e2bc04669f74
You have bazel 0.21.0- (@non-git) installed.
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3

Found possible Python library paths:
  /usr/local/lib/python3.6/site-packages
  /usr/lib64/python3.6/site-packages
  /usr/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.6/site-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: 
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10.0]: 

Please specify the location where CUDA 10.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /usr

Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: 

Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is /usr]: 

Do you wish to build TensorFlow with TensorRT support? [y/N]: 
No TensorRT support will be enabled for TensorFlow.

Please specify the locally installed NCCL version you want to use. [Default is to use https://github.com/nvidia/nccl]: 

Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 3.5,7.0]: 6.1

Do you want to use clang as CUDA compiler? [y/N]: 
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: /usr/bin/cuda-gcc

Do you wish to build TensorFlow with MPI support? [y/N]: 
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: 
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=noignite       # Disable Apacha Ignite support.
        --config=nokafka        # Disable Apache Kafka support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished

- # bazel build --local_resources 2048,6,1.0 --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
...
...
ERROR: /home/spryor/git/tensorflow/tensorflow/python/eager/BUILD:10:1: C++ compilation of rule '//tensorflow/python/eager:pywrap_tfe_lib' failed (Exit 1)
tensorflow/python/eager/pywrap_tfe_src.cc: In function ‘void TFE_Py_Execute(TFE_Context*, const char*, const char*, TFE_InputTensorHandles*, PyObject*, TFE_OutputTensorHandles*, TF_Status*)’:
tensorflow/python/eager/pywrap_tfe_src.cc:685:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < inputs->size() && TF_GetCode(out_status) == TF_OK;
                     ~~^~~~~~~~~~~~~~~~
In file included from tensorflow/python/eager/pywrap_tfe_src.cc:23:0:
external/com_google_absl/absl/types/variant.h: In substitution of ‘template<long unsigned int I, class T> using variant_alternative_t = typename absl::variant_alternative::type [with long unsigned int I = I; T = absl::variant<tensorflow::TensorShape, _object*>]’:
external/com_google_absl/absl/types/variant.h:581:7:   required by substitution of ‘template<class T, long unsigned int I, class Tj, typename std::enable_if<(std::is_assignable<Tj&, T>::value && std::is_constructible<Tj, T>::value), void>::type* <anonymous> > absl::variant<tensorflow::TensorShape, _object*>& absl::variant<tensorflow::TensorShape, _object*>::operator=<T, I, Tj, <enumerator> >(T&&) [with T = const absl::variant<tensorflow::TensorShape, _object*>&; long unsigned int I = <missing>; Tj = <missing>; typename std::enable_if<(std::is_assignable<Tj&, T>::value && std::is_constructible<Tj, T>::value), void>::type* <anonymous> = <missing>]’
tensorflow/python/eager/pywrap_tfe_src.cc:914:20:   required from here
external/com_google_absl/absl/types/variant.h:581:7: internal compiler error: unexpected expression ‘I’ of kind template_parm_index
       class Tj = absl::variant_alternative_t<I, variant>,
       ^~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 600.890s, Critical Path: 104.25s
INFO: 3259 processes: 3259 local.
FAILED: Build did NOT complete successfully

### Describe the problem
Attempting to build r1.13 on Fedora 28 with the given packages/etc results in a build error

[tensorflow_build.log](https://github.com/tensorflow/tensorflow/files/2789013/tensorflow_build.log)

**Comment by aselle** [comment]
@gunan, is this related to the gcc problems you were mentioning to me yesterday?

**Comment by gunan** [comment]
The one I ran into is more around this one:
http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1647
This is I think fixed with  patch releases to GCC.

Not sure about the compiler error reported on this issue.

**Comment by makalaia** [comment]
I'm having the same issue when trying to compile Tensorflow 1.13.1, I'm using bazel 0.21.0 on amazon linux. 

I've tried with gcc versions 7.3.0, 7.3.1, 7.4.0, 8.3.0 and got the same error on all of them. Do anyone have a solution for this?

**Comment by makalaia** [comment]
Managed to build it for skylake(-march=skylake-avx512) , using:
bazel: 0.19.2
protobuf: 3.5.2
python: 3.7
gcc: 8.2.0

**Comment by grahamwhiteuk** [comment]
I'm getting the same compiler error, using:
- Fedora 29 and the NVidia Drivers + Cuda 10.0 libraries from [Negativo 17](https://negativo17.org/repos/nvidia/fedora-29/x86_64/)
- bazel: 0.19.2
- protobuf: 3.5.0
- python: 3.7.3
- gcc: 7.3.1
- cuda: 10.0
- cudnn: 7.4.2
- nccl: 2.4.2

I've attempted to match my versions as closely as possible to the [tested build configurations](https://www.tensorflow.org/install/source#linux) but still bombing out with similar output:

```
ERROR: /path truncated for privacy/tensorflow-r1.13/tensorflow/compiler/xla/service/BUILD:3025:1: C++ compilation of rule '//tensorflow/compiler/xla/service:maybe_owning_device_memory' failed (Exit 1)
In file included from ./tensorflow/compiler/xla/service/maybe_owning_device_memory.h:20:0,
                 from tensorflow/compiler/xla/service/maybe_owning_device_memory.cc:16:
external/com_google_absl/absl/types/variant.h: In substitution of 'template<long unsigned int I, class T> using variant_alternative_t = typename absl::variant_alternative::type [with long unsigned int I = I; T = absl::variant<xla::OwningDeviceMemory, stream_executor::DeviceMemoryBase>]':
external/com_google_absl/absl/types/variant.h:501:7:   required by substitution of 'template<class T, long unsigned int I, class Tj, absl::enable_if_t<std::is_constructible<Tj, T>::value, void>* <anonymous> > constexpr absl::variant<xla::OwningDeviceMemory, stream_executor::DeviceMemoryBase>::variant(T&&) [with T = absl::variant<xla::OwningDeviceMemory, stream_executor::DeviceMemoryBase>; long unsigned int I = <missing>; Tj = <missing>; absl::enable_if_t<std::is_constructible<Tj, T>::value, void>* <anonymous> = <missing>]'
./tensorflow/compiler/xla/service/maybe_owning_device_memory.h:29:7:   required from here
external/com_google_absl/absl/types/variant.h:501:7: internal compiler error: unexpected expression 'I' of kind template_parm_index
       class Tj = absl::variant_alternative_t<I, variant>,
       ^~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 506.735s, Critical Path: 50.03s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 3097 processes: 3097 local.
FAILED: Build did NOT complete successfully
```

**Comment by jarednielsen** [comment]
Same error here. This occurs on an Amazon Linux x1.32xlarge instance, in the stock Python 3.6 conda environment.

**Comment by kumariko** [comment]
@Xaenalt We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. Thanks!

**Comment by Xaenalt** [comment]
I haven't tried in a while, I'll close it to get it out of the queue, I'll reopen a diff issue for new versions if I hit anything
