### ISSUE TITLE
Profiler hook causes exception

### ISSUE THREAD

**Issue by tadeegan** [tensorflow/tensorflow#25147]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No. I am using 1.12.0

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 14. Docker 16.
- TensorFlow installed from (source or binary): binary whl
- TensorFlow version (use command below): 1.12.0
- Python version: 2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory: Repros on both local 1080ti + TitanV and 8xV100 on gcloud

```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
('v1.12.0-0-ga6d8ffae09', '1.12.0')
```

**Describe the current behavior**

```
INFO:tensorflow:loss = 0.28926048, step = 0
2019-01-23 22:36:02.026095: I tensorflow/stream_executor/dso_loader.cc:151] successfully opened CUDA library libcupti.so.9.0 locally
pure virtual method called
terminate called without an active exception
Aborted (core dumped)
```

**Describe the expected behavior**

**Code to reproduce the issue**

```python
        hooks = []
        if self.params.profile:
            profile_destination = '/'.join([self.params.job_dir, 'profiler'])
            tf.logging.info("Profiling session to: {}".format(profile_destination))
            profiler_hook = tf.train.ProfilerHook(save_steps=30,
                                                    output_dir=profile_destination,
                                                    show_memory=True)
            hooks.append(profiler_hook)

        # Build train and eval specs
        train_spec = tf.estimator.TrainSpec(
            input_fn=lambda: self.model.input_tf_dataset(DataSplitKey.TRAIN),
            max_steps=self.params.train_steps,
            hooks=hooks,
        )
```

**Comment by tadeegan** [comment]
Any tips on debugging this would be much appreciated. I am using the mirrored strategy.

**Comment by tadeegan** [comment]
Installing these fixes the issue. There seems to be a cuda incompatibility even in the gcloud ml engine docker container.

```
sudo apt install libcudnn7=7.2.1.38-1+cuda9.0
sudo apt install libnccl2=2.2.13-1+cuda9.0
```

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks for the workaround.
