### ISSUE TITLE
Is there tf_cuda_cc_binary rule in TF?

### ISSUE THREAD

**Issue by d0u9** [tensorflow/tensorflow#25154]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  RHEL 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.4
- Python version: 2.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.9.0
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: 9.0
- GPU model and memory: k40m

**Describe the problem**

I want to put a simple cuda cupti program(Eg, the official CUPTI samples) in TF for some tests. But I can't find any `tf_cuda_cc_binary` rule in TF. So, my question is: how could I put such raw cuda souce in TF, and compile them by bazel?

**Comment by gunan** [comment]
You should not need a separate target. You can depend on these targets in your cc_binary to pull in cupti: `tensorflow/tensorflow/core/profiler/internal/gpu:cupti_wrapper` I think we have targets for all of these under stream executor, and you can just depend on those as well, like `tensorflow/stream_executor/cuda:cupti_stub`
