### ISSUE TITLE
How to measure every node flops form tflite model？

### ISSUE THREAD

**Issue by wangshankun** [tensorflow/tensorflow#25155]
benchmark_model  or profile only have run time and memory，i  also want to get flops from node

**Comment by freedomtan** [comment]
if what you want is estimating FLOPS, you can check what TensorFlow benchmark_mode does, check [its code](
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/benchmark/benchmark_model.cc#L148-L212) does.

**Comment by ymodak** [comment]
Closing since its resolved. Thanks!
