### ISSUE TITLE
eager.function.defun bypasses Autograph even when autograph=True

### ISSUE THREAD

**Issue by ktaebum** [tensorflow/tensorflow#25159]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): nightly (1.13.0-dev20190118)
- Python version: 3.5.2
- CUDA/cuDNN version: 9.0
- GPU model and memory: NVIDIA TITAN Xp (12196MB)

**Describe the current behavior**

From tensorflow 1.13, there is integration between autograph and tf.eager.function.defun (alias of tf.function in tf2.0 maybe?) 
The logic flow is if programmer enables `autograph` option as `True` in `defun` decorator,
`func_graph_from_py_func` function in `tf.python.framework.func_graph.py` will be called with `autograph=True`.
Inside that function, it will call `converted_call` which is defined in `autograph.impl.api.py` and convert py_function to graph_funcion via autograph lib

However, inside `converted_call`, it should shows some log information about conversion in current version, but in my simplest example, it does not in actual execution.
Moreover, if I add some redundant print statement inside converted_call, it prints nothing.
I think rewrapping autograph wrapper in line 445-446 inside of `tf.python.framework.func_graph.py` does not wrap autograph's `converted_call`

**Describe the expected behavior**

The program should print some logging information in autograph conversion
e.g. autograph converted code information

**Code to reproduce the issue**

```
import tensorflow as tf

from tensorflow.python import autograph
from tensorflow.python.eager.function import defun

tf.enable_eager_execution()

@defun(autograph=True)
def add(x, y):
    return x + y

print(add(tf.constant(4), tf.constant(3))
```

**Other info / logs**

I think this issue occurs because
Inside `unwrap` function in `tf.python.util.tf_decorator.py`, it does nothing if `innermost_decorator` is `None`
Thus, if I change line 445-446 in `tf.python.framework.func_graph.py` as 
```
converted_func = tf_decorator.make_decorator(original_func, wrapper)
if not hasattr(python_func, '_tf_decorator'):
    python_func = converted_func
else:
    tf_decorator.rewrap(python_func, original_func, converted_func)
```
it works.

**Comment by mdanatg** [comment]
Thank you for the detailed report and tracking down the fix! Sorry for the delay.

Your suspicion is right, `defun` is a precursor of `function` in 2.0. In integrates with a stable version of autograph, one which converts control flow only.
We recently changed the logging mechanism in Autograph to make it easier to control. It is also quite verbose now. You can now enable it either by calling [tf.autograph.set_verbosity](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/autograph/set_verbosity) or by setting the `AUTOGRAPH_VERBOSITY` environment variable. Levels are 0-4, with 0 being no logging and 1 showing the generated code.
Unfortunately, logging doesn't seem to redirect to the cell output in Jupyter - that is a bug we're working to fix. But it should show up in the kernel logs.

I'm looking to replicate the bug, but it seems to be gone. Here are the commands I ran:

```
!pip install tf-nightly
```

```
import tensorflow as tf

print(tf.__version__)
```

1.13.0-dev20190207

```
from tensorflow.python import autograph
from tensorflow.python.eager.function import defun

tf.enable_eager_execution()

@defun(autograph=True)
def add(x, y):
    return x + y

print(add(tf.constant(4), tf.constant(3)))
```

tf.Tensor(7, shape=(), dtype=int32)

Please reopen the issue if it still occurs on your side of if you have further questions.

**Comment by mdanatg** [comment]
After a bit more digging into the logging, it seems that defun indeed does not call Autograph! I'll look into applying the fix you suggested.
