### ISSUE TITLE
Error while calling TFLite interpreter - cannot import name cloud

### ISSUE THREAD

**Issue by Zeit42** [tensorflow/tensorflow#25168]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian Stretch 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not Applicable
- TensorFlow installed from (source or binary):whl file
- TensorFlow version: 1.12.0
- Python version: 3.5
- Installed using virtualenv? pip? conda?: Pip3
- Bazel version (if compiling from source): Not applicable
- GCC/Compiler version (if compiling from source): Not applicable
- CUDA/cuDNN version: Not applicable
- GPU model and memory: Not applicable

**Describe the problem**
I'm using a Raspberry Pi 3B+, with Raspbian Stretch as my OS.

I installed Tensorflow 1.12 using [this guide](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi), I downloaded the latest versions of TensorFlow and Protobuf, but as I was trying out [this guide](https://github.com/freedomtan/tensorflow/blob/deeplab_tflite_python/tensorflow/contrib/lite/examples/python/object_detection.py), I hit an error:

`File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/__init__.py", line 39, in <module>
    from tensorflow.contrib import cloud
ImportError: cannot import name 'cloud'` 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
The steps that I had followed are based off of the guide linked above, I had used the updated compiled TensorFlow wheels and the updated Protobuf as well.

Here are the exact steps I took:
TensorFlow Lite Guide

You may do the following in the RPi itself, or connect via SSH

If you encounter the “Remote Host Identification has changed” message, you may have to edit the ~/.ssh/known_hosts file.
sudo nano ~/.ssh/known_hosts

remove the line for the IP Address of the RPi

1. Delete bloatware
$ sudo apt-get purge wolfram-engine
$ sudo apt-get purge libreoffice*
$ sudo apt-get clean
$ sudo apt-get autoremove

2. Install Dependencies
$ sudo apt-get update
$ sudo apt-get dist-upgrade

3. Install Tensorflow
$ mkdir tf && cd tf

check: https://github.com/lhelontra/tensorflow-on-arm/releases 
for latest tensorflow releases

$ wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.12.0/tensorflow-1.12.0-cp35-none-linux_armv7l.whl

$ sudo pip3 install /home/pi/tf/tensorflow-1.12.0-cp35-none-linux_armv7l.whl

$ sudo apt-get install libatlas-base-dev
$ sudo pip3 install pillow lxml jupyter matplotlib cython
$ sudo apt-get install python-tk

3. Install OpenCV
$ sudo apt-get install libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev
$ sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
$ sudo apt-get install libxvidcore-dev libx264-dev
$ sudo apt-get install qt4-dev-tools
$ pip3 install opencv-python

4. Install Protobuf
$ sudo apt-get install autoconf automake libtool curl
check https://github.com/protocolbuffers/protobuf/releases/ 
for latest releases
$ wget https://github.com/google/protobuf/releases/download/v3.6.1/protobuf-all-3.6.1.tar.gz
$ tar -zxvf protobuf-all-3.6.1.tar.gz
$ cd protobuf-3.6.1
$ ./configure
$ make
$ make check
$ sudo make install
$ cd python
$ export LD_LIBRARY_PATH=../src/.libs
$ python3 setup.py build --cpp_implementation 
$ python3 setup.py test --cpp_implementation
$ sudo python3 setup.py install --cpp_implementation
$ export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
$ export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=3
$ sudo ldconfig
$ protoc
$ sudo reboot now

$ cd ~
$ mkdir tensorflow1 && cd tensorflow1
$ git clone --recurse-submodules https://github.com/tensorflow/models.git

$ sudo nano ~/.bashrc
Add: export PYTHONPATH=$PYTHONPATH:/home/pi/tensorflow1/models/research:/home/pi/tensorflow1/models/research/slim

$ cd /home/pi/tensorflow1/models/research
$ protoc object_detection/protos/*.proto --python_out=.

$ cd /home/pi/tensorflow1/models/research/object_detection
$ wget http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz
$ tar -xzvf ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz

Then I ran:
$ python3
>> from tensorflow.contrib.lite.python import interpreter as interpreter_wrapper
 But I hit an error, as shown below:

**Any other info / logs**
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 47, in <module>
    import numpy as np
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/__init__.py", line 187, in <module>
    from .testing import Tester
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/usr/lib/python3.5/unittest/__init__.py", line 64, in <module>
    from .main import TestProgram, main
  File "/usr/lib/python3.5/unittest/main.py", line 7, in <module>
    from . import loader, runner
  File "/usr/lib/python3.5/unittest/runner.py", line 8, in <module>
    from .signals import registerResult
  File "/usr/lib/python3.5/unittest/signals.py", line 1, in <module>
    import signal
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/signal/__init__.py", line 42, in <module>
    from tensorflow.contrib.signal.python.ops.mel_ops import linear_to_mel_weight_matrix
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/__init__.py", line 39, in <module>
    from tensorflow.contrib import cloud
ImportError: cannot import name 'cloud'

I've checked the __init__.py code, and I'm kind of clueless as to what or how to approach this. I'm not sure if it's safe to just comment the line out. 

Has anyone solved this issue?

**Comment by petewarden** [comment]
Unfortunately we can't support external builds like https://github.com/lhelontra/tensorflow-on-arm/releases, since we're not in control of how they're built.

**Comment by weishengchong** [comment]
Hi @Zeit42,

>File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/__init__.py", line 39, in <module> from >tensorflow.contrib import cloud ImportError: cannot import name 'cloud'

I have the same error, would you please kindly share your insights? Thanks.

My system infor
tensorflow-1.13.1-cp35-none-linux_aarch64.whl
Linux firefly 4.4.52 #16 SMP Thu Apr 27 17:56:29 HKT 2017 aarch64 aarch64 aarch64 GNU/Linux
rk3399

Hi  @petewarden,
> can't support external builds like https://github.com/lhelontra/tensorflow-on-arm/releases, 

Noted. Thanks.

`
    interpreter = tf.contrib.lite.Interpreter(model_path=tflitefile)
  File "/media/root/usb16g1/venv/tf1.13/lib/python3.5/site-packages/tensorflow/python/util/lazy_loader.py", line 61, in __getattr__
    module = self._load()
  File "/media/root/usb16g1/venv/tf1.13/lib/python3.5/site-packages/tensorflow/python/util/lazy_loader.py", line 44, in _load
    module = importlib.import_module(self.__name__)
  File "/media/root/usb16g1/venv/tf1.13/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/media/root/usb16g1/venv/tf1.13/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 30, in <module>
    from tensorflow.contrib import cloud
ImportError: cannot import name 'cloud'
`
