### ISSUE TITLE
os.environ["CUDA_DEVICE_ORDER"] ='0' not work in tensorflow 

### ISSUE THREAD

**Issue by policeme** [tensorflow/tensorflow#25164]
I have two GPU, I want to create 2 graph in 2 GPU, first graph in first GPU, second graph in second GPU.

when I create first graph in first GPU, I use os.environ["CUDA_DEVICE_ORDER"] ='0'
2.when I create second graph in second GPU, I use os.environ["CUDA_DEVICE_ORDER"] = '1', but second graph still create on first GPU, I try many different ways, but it still not work.
It's a bug?  Please help me. 
@ry @jmhodges @eggie5 @bmabey @djones

**Comment by ymodak** [comment]
duplicate #25152
