### ISSUE TITLE
what is the FFT size of the tensorflow.audio_contrib.audio_spectrogram in input_audio.py?

### ISSUE THREAD

**Issue by jenweilee** [tensorflow/tensorflow#25167]
in input_audio.py, is the FFT size equal to window_size?
spectrogram = contrib_audio.audio_spectrogram(
          background_clamp,
          window_size=model_settings['window_size_samples'],
          stride=model_settings['window_stride_samples'],
          magnitude_squared=True)

if it is, should the window size be 2's power? because most of time the FFT size is equal to 2's power.

**Comment by jvishnuvardhan** [comment]
Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. Github is mainly for addressing bugs in installation and performance. Thanks!
