### ISSUE TITLE
Reason for big performance difference between TFLite and TF Mobile app? Protobuf and .tflite file as reason?

### ISSUE THREAD

**Issue by defaultUser3214** [tensorflow/tensorflow#25172]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No I used the DetectorActivity of android mobile demo app (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) and the TensorFlow Lite demo app (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 18.04.1 LTS and LineageOS Android 8.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Oneplus 5
- TensorFlow installed from (source or binary): compiled from source with cuda 10 and bazel
- TensorFlow version ( use command below): in Python 2.7 (command python): (tf.GIT_VERSION, tf.VERSION) = ('v1.12.0-0-ga6d8ffae09', '1.12.0') in Python 3.6.7 (command python3): b'v1.9.0-rc2-5108-g4e06be5f8f' 1.12.0-rc0 
- Python version: Python 2.7.15rc1 and Python 3.6.7
- Bazel version (if compiling from source): either 0.20.0 or 0.21.0 (I don't know with which version I compiled the tensorflow installed in python but I used 0.20.0 in order to execute the bazel commands for the transform of the protobuf to the tflite file - I think it wasn't possible to use bazel 0.21 therefore)
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: Cuda 10.0 und cuDNN 7.3.1
- GPU model and memory:  GeForce GTX 970, RAM total: 16345820 and RAM swap: 2097148

**Describe the current behavior**

Because the calculation of  the classification and the bounding boxes in the DetectorActivity (from https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) with the model ssd_mobilenet_v1_android_export.pb (https://www.dropbox.com/home/Modelfile?preview=ssd_mobilenet_v1_android_export.pb) took 200ms - I rely to the runtime of the native method run in the TensorFlowInferenceInterface.class - I compared the runtime of the native method run() in the Interpreter.class of the classifier (no bounding boxes) from the tensorflow lite example app under https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo with the models "mobilenet_v1_1.0_224.tflite" and "mobilenet_v1_1.0_224_quant.tflite" that were autodonwloaded into asserts. So I assumed that that huge performance is because of the fact that the TFLite example app uses a model ending with .tflite and the mobile app a protobuf file. 
Is this a possible reason or is bounding box calculation such a expensive operation? On model zoo the ssd_mobilenet_v1 model should be provide results within ~30 ms. 

On https://www.tensorflow.org/lite/apis#loading_a_model_2 under the heading Running Model Inference I found a hint to https://www.tensorflow.org/lite/convert/cmdline_examples. This points out that you have to optimize you model. Can the fact that the .pb files aren't optimezed be another reason for the bad performance? 

**Describe the expected behavior**
I expected that the runtime for classification (and bounding box calculation) in Tensorflow lite and Tensorflow mobile demo app doesn't differ so much!
**Code to reproduce the issue**
1) download the two demo apps and import them to Android Studio
2) print you a timestamp before and after the execution of the following methods:
- Tensorflow Lite demo app: In the ImageClassifier.java in the method classifyFrame 

` long startTime = SystemClock.uptimeMillis();
    runInference();
    long endTime = SystemClock.uptimeMillis();
    Log.d(TAG, "Timecost to run model inference: " + Long.toString(endTime - startTime));`

- Tensorflow Mobile demo app: in DetectorActivity in the method processImage() runInBackground {} put the code 
`                        final long startTime = SystemClock.uptimeMillis();
                        final List<Classifier.Recognition> results = detector.recognizeImage(croppedBitmap);
                        lastProcessingTimeMs = SystemClock.uptimeMillis() - startTime;` 
around the recognizeImage() method.

**Other info / logs**

**Comment by defaultUser3214** [comment]
The reason why I did this is the fact that I get the error described in #25171 when I include a model generated from a protobuf file. Apart from that, I couldn't find a .tflite and the suiting .pb file in the web in the model zoo and the web.

**Comment by shashishekhar** [comment]
@defaultUser3214 : Those numbers are probably not on device numbers. You can use one of the [benchmarking tools](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/benchmark) to benchmark the model if you want to test the model latency outside your app.
