### ISSUE TITLE
ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.

### ISSUE THREAD

**Issue by victorinno** [tensorflow/tensorflow#25173]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 10 64bits

- TensorFlow installed from (source or binary): anaconda
- TensorFlow version: 1.12.0
- Python version: 3.6.5 | Acaconda INC
- Installed using virtualenv? pip? conda?:conda

- CUDA/cuDNN version: none, there is no card board
- GPU model and memory: none

**Describe the problem**
I can´t run keras installed by anaconda in a pc without car board.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
runfile('C:/Users/CAST/Desktop/train/IA_2.py', wdir='C:/Users/CAST/Desktop/train')
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-1-1706b5d23745>", line 1, in <module>
    runfile('C:/Users/CAST/Desktop/train/IA_2.py', wdir='C:/Users/CAST/Desktop/train')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/CAST/Desktop/train/IA_2.py", line 16, in <module>
    import keras

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ymodak** [comment]
I suspect you have installed TF - GPU version. Can you please confirm? Also can you please describe the steps you followed to install TF? Thanks!

**Comment by victorinno** [comment]
Ymodak, how can I check that?

About the installation process I used anaconda and selected the TensorFlow and Keras package for installation.

**Comment by victorinno** [comment]
ymodak this is the result:

> Solving environment: done
> 
> 
> ==> WARNING: A newer version of conda exists. <==
>   current version: 4.5.12
>   latest version: 4.6.2
> 
> Please update conda by running
> 
>     $ conda update -n base -c defaults conda
> 
> 
> 
> ## Package Plan ##
> 
>   environment location: C:\ProgramData\Anaconda3
> 
>   added / updated specs:
>     - keras
> 
> 
> The following NEW packages will be INSTALLED:
> 
>     libgpuarray:         0.7.6-hfa6e2cd_1003       conda-forge
>     mako:                1.0.7-py_1                conda-forge
>     pygpu:               0.7.6-py36h452e1ab_1000   conda-forge
>     theano:              1.0.4-py36h6538335_1000   conda-forge
>     vs2015_win-64:       14.0.25123-h17c34da_3     conda-forge
> 
> The following packages will be UPDATED:
> 
>     certifi:             2018.4.16-py36_0                      --> 2018.4.16-py36_0          conda-forge
>     conda:               4.5.12-py36_0                         --> 4.6.2-py36_0              conda-forge
> 
> The following packages will be DOWNGRADED:
> 
>     keras:               2.2.4-0                               --> 2.2.2-py36_0              conda-forge
>     keras-applications:  1.0.6-py36_0                          --> 1.0.4-py_1                conda-forge
>     keras-base:          2.2.4-py36_0                          --> 2.2.2-py36_0
>     keras-preprocessing: 1.0.5-py36_0                          --> 1.0.2-py_1                conda-forge
>     tensorboard:         1.12.0-py36he025d50_0                 --> 1.10.0-py36_0             conda-forge
>     tensorflow:          1.12.0-gpu_py36ha5f9131_0             --> 1.10.0-py36_0             conda-forge
>     tensorflow-base:     1.12.0-gpu_py36h6e53903_0             --> 1.10.0-gpu_py36h6e53903_0
> 
> Proceed ([y]/n)? y
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done

**Comment by ymodak** [comment]
It shows that you have TF-GPU installed on your system. Since you don't have a compatible gpu config on your system you can uninstall the tf-gpu version and install regular tf version.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
