### ISSUE TITLE
Accept h5py.Group in tf.keras save/load functions

### ISSUE THREAD

**Issue by bolau** [tensorflow/tensorflow#25181]
**System information**
- TensorFlow version (you are using): 1.13
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**
The save_model function in tf.keras.models currently accepts a filepath or a h5py.File model.
It would be nice if this was generalized to accepting h5py.Group objects. This makes it possible to store more than one model in one h5py file, or combine it with other objects.
This change has been implemented in keras.io as well (I'm not the OP), and it would be very nice to see this in TF.keras as well: 
* https://github.com/keras-team/keras/issues/10905 
* https://github.com/keras-team/keras/pull/10912

**Will this change the current api? How?**
save_model and load_model would accept filepaths and h5py.Group, which is more general.

**Who will benefit with this feature?**
Everybody using the keras h5py saving/loading options who wants to store complexer models such as ensembles.

Happy to provide a PR if this has a chance to be merged.

Best, Boris

**Comment by ymodak** [comment]
It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thanks!

**Comment by bolau** [comment]
Just a noob question for now: what branch should I work from?

**Comment by ymodak** [comment]
You can [submit a PR](https://help.github.com/en/articles/creating-a-pull-request) referencing master branch. Thanks!

**Comment by mihaimaruseac** [comment]
Please CC me if you do a PR for this.

**Comment by lsgrep** [comment]
Hi @bolau,  This has gone silent for a while, and can I take the torch from your hands and work on this one?

**Comment by JohanMollevik** [comment]
@lsgrep I would appreciate if you or someone else takes this up, I was sad to discover that this feature has not yet been transferred from keras to tensorflow.keras

**Comment by Saduf2019** [comment]
@bolau 
his issue is resolved in the latest tf version, please verify an revert.
