### ISSUE TITLE
IExecutionContext in TRTEngineOp is non thread-safe. 

### ISSUE THREAD

**Issue by lijianSE** [tensorflow/tensorflow#25187]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home: CentOS 7
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.11
- Python version: 2.7
- Bazel version (if compiling from source): 0.18
- GCC/Compiler version (if compiling from source): gcc 5.4
- CUDA/cuDNN version: cuda-10.0, cudnn 7.3, tensorrt 5.0
- GPU model and memory: Nvidia P40

**Describe the Problem**
We are using DirectSession to do inference with c++ code in gpu environment. The model using TRTEngineOp to improve performance. But TRTEngineOp maintain a engine_map to process input.  This map used to keep tensorrt engines and their tensorrt execution context for given batch size. 
The tensorrt engine(nvinfer1::ICudaEngine) is thread safety. But the tensorrt execution context(nvinfer1::IExecutionContext) is non thread-safe. So it will crashed when session processing two same batch_size task in the same time.

**Describe the expected behavior**
We hope the engine_map in TRTEngineOp can maintain a pair, which the first value can be tensorrt engine.  the sescond value can be a tensorrt context pool.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Crashed when session process two task in the same time.
<pre><code>
2019-01-25 11:57:59.952217: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_event.cc:48] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-01-25 11:57:59.952296: F external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:274] Unexpected Event status: 1
2019-01-25 11:57:59.952430: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:1011] could not synchronize on CUDA context: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered :: *** Begin stack trace ***

	clone
*** End stack trace ***
<code><pre>

**Comment by samikama** [comment]
@trevor-m @pooyadavoodi  Can you PTAL

**Comment by samikama** [comment]
@trevor-m @pooyadavoodi, I believe this is fixed. Is that correct?

**Comment by sanjoy** [comment]
I believe this was fixed in https://github.com/tensorflow/tensorflow/commit/e51fa30400b3a469b03111b25344bc47bdff96bd.  Please reopen if not.
