### ISSUE TITLE
Analysis of target '//tensorflow/contrib/resampler:resampler_ops_xla_test_gpu' failed

### ISSUE THREAD

**Issue by taurandat** [tensorflow/tensorflow#25195]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.13
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: CUDA 10, cudnn 7.4.2
- GPU model and memory: 2 x RTX 2080 Ti

**Describe the problem**

During the build process described on the tensorflow website for r1.13, the command bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/... fails due to not finding the package '@com_google_protobuf//'. The full error message is:

```
ERROR: /media/titan/resources/oss/machine-learning/Google/tensorflow/tensorflow/tensorflow/contrib/resampler/BUILD:103:1: in deps attribute of py_test rule //tensorflow/contrib/resampler:resampler_ops_xla_test_gpu: '//tensorflow/compiler/tf2xla/kernels:resampler_ops' does not have mandatory providers: 'py'. Since this rule was created by the macro 'tf_xla_py_test', the error might have been caused by the macro implementation in /media/titan/resources/oss/machine-learning/Google/tensorflow/tensorflow/tensorflow/compiler/tests/build_defs.bzl:94:20
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Create new conda environment
2. Install Bazel using binary installer
3. Install dependencies for the build
4. Run `./configure` in the cloned repo with `r1.13` checked-out
5. Run `bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/...`

Then I encounter the mentioned error.

**Comment by yoyolin** [comment]
Came across the same issue when running the test `bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/...`. Searched online everywhere but couldn't solve it. I had to ignore the test and went on to build the package using `bazel build --config=opt --config=cuda --config=mkl //tensorflow/tools/pip_package:build_pip_package`. To my surprise the build was successful and installing `tensorflow 1.13` was successful too. I tested several applications and also tried training, everything went on smoothly without reporting any bug. 

Now I am not sure why is it like this. Anyone knows?

**Comment by gunan** [comment]
Unfortunately, TF tests include a lot of tests that are only valid in very specific cases. Therefore, the test command we have in the build instructions can fail a lot erroneously. @lamberta Maybe we should remove the "bazel test" command from install from source instructions.

**Comment by lamberta** [comment]
@gunan While it would be nice to have an easy way to test this, I agree this command seems to change enough that keeping it up to date is a pain. I have a CL out to remove this section.

**Comment by gunan** [comment]
Also, I added the necessary tag filters to the bazelrc, which should help with this. Closing the issue.
