### ISSUE TITLE
How to do distributed training with multi-gpus

### ISSUE THREAD

**Issue by bitianchi** [tensorflow/tensorflow#25196]
Hi, I got a problem of doing synchronous training on distributed training. I want to use multi-machines with multi-GPUs on distributed training. But I can't find any material about it. Is here any one giving me some help? Thanks a lot.

Here is part of my code.

    with tf.device("/job:worker/task:%d" % FLAGS.task_index, cluster=cluster):
            global_step = tf.Variable(0, name="global_step", trainable=False)
            alpha = dynamic_lrate(hparams, global_step)
            optimizer = tf.contrib.opt.LazyAdamOptimizer(alpha, beta1=0.9, beta2=0.997, epsilon=1e-9)
            rep_op = tf.train.SyncReplicasOptimizer(optimizer,
                                                    replicas_to_aggregate=len(worker_hosts),
                                                    total_num_replicas=len(worker_hosts),
                                                    use_locking=True)

            """in RNNModel contains multi-gpus"""
            model = RNNModel(None, hparam_list, train_ds, tf.estimator.ModeKeys.TRAIN, rep_op, global_step)
            valid_model = RNNModel(model.graph, hparam_list, valid_ds, tf.estimator.ModeKeys.PREDICT, rep_op, global_step)

            train_op = model.train_op

            init_token_op = rep_op.get_init_tokens_op()
            chief_queue_runner = rep_op.get_chief_queue_runner()

            saver = saver_mod.Saver(max_to_keep=hparams.max_save,
                            var_list=model.all_vars)

            sv = tf.train.Supervisor(is_chief=(FLAGS.task_index==0),
                                     logdir=log_dir,
                                     saver=saver,
                                     global_step=global_step,
                                     save_summaries_secs=3600,
                                     save_model_secs=hparams.sfreq)

            with sv.prepare_or_wait_for_session(server.target, config=config) as sess:
                if FLAGS.task_index == 0 and issync == 1:
                    sv.start_queue_runners(sess, [chief_queue_runner])
                    sess.run(init_token_op)

                #tf.global_variables_initializer().run()

                idx = 0
                max_bleu_score = -10.0
                best_path = os.path.join(log_dir, "model_best")
                total_accu = 0.0
                total_size = 0
                for epoch in range(FLAGS.maxsteps):
                    training_step = sess.run([global_step])
                    step_num = int(training_step[0])

                    res = sess.run([model.tower_print_loss,
                                    model.tower_accu,
                                    #model.tower_print_loss_2,
                                    #model.tower_accu_2,
                                    model.batch_size,
                                    #model.fsrc,
                                    #model.ftgt,
                                    train_op
                                    ])

**Comment by bitianchi** [comment]
with this code, work:1 always prints "Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized" but work:0 is training

**Comment by seemuch** [comment]
Please refer to this doc: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distribute#multi-worker-training

And look here for examples: https://github.com/tensorflow/ecosystem/tree/master/distribution_strategy
