### ISSUE TITLE
TensorflowLite GPU + DeepLab porting

### ISSUE THREAD

**Issue by ilous12** [tensorflow/tensorflow#25193]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.12
- Python version:2.7
- Bazel version (if compiling from source):n/a
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:9.0
- GPU model and memory:k80 + 12GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I tried to work Tensorflowlite +gpu + deeplabv3_257_mv_gpu.tflite, but not working
runInference was success.
(1) how can use output (pixelClasses)? Can u give sample code? I attached my code.
(2) performance was very slow 600ms~900ms

[ImageSegmentation.zip](https://github.com/tensorflow/tensorflow/files/2795483/ImageSegmentation.zip)

```
  protected float[][][][] pixelClasses;
  pixelClasses = new float[1][getImageSizeX()][getImageSizeY()][21];
 Bitmap classifyFrame(Bitmap bitmap, SpannableStringBuilder builder) {
        if (tflite == null) {
            Log.e(TAG, "Image classifier has not been initialized; Skipped.");
            builder.append(new SpannableString("Uninitialized Classifier."));
            return bmp;
        }
        convertBitmapToByteBuffer(bitmap);
        long startTime = SystemClock.uptimeMillis();
        runInference();
        long endTime = SystemClock.uptimeMillis();
        Log.d(TAG, "Timecost to run model inference: " + Long.toString(endTime - startTime));
        int batchNum = 0;
        float[][][][] output = pixelClasses;
         for(int x = 0; x < getImageSizeX(); x++) {
            for (int y = 0; y < getImageSizeY(); y++) {
                pixels[x * bmp.getHeight() + y] = argb(100, (int)(output[batchNum][y][x][2]), (int)(output[batchNum][y][x][1]), (int)(output[batchNum][y][x][0]));
            }
        }
        bmp.setPixels(pixels, 0, bmp.getWidth(), 0, 0, bmp.getWidth(), bmp.getHeight());
        return bmp;
    }
```

**Describe the expected behavior**
overlay color.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Did you get a chance to look at [tensorflow-lite-now-faster-with-mobile-gpus-doc](https://medium.com/tensorflow/tensorflow-lite-now-faster-with-mobile-gpus-developer-preview-e15797e6dee7?linkId=62443226)

**Comment by ilous12** [comment]
@ymodak Thanks you comment. I did try but i want to have example code. Can you give sample?

Anyone help me.

**Comment by ymodak** [comment]
Also refer [TensorFlow Lite GPU Delegate Tutorial](https://www.tensorflow.org/lite/performance/gpu)

**Comment by impjdi** [comment]
@ilous12 

My understanding is that the model has 21 classes:

https://medium.freecodecamp.org/how-to-use-deeplab-in-tensorflow-for-object-segmentation-using-deep-learning-a5777290ab6b

And given the dimensions, I would *assume* that a pixel at position [1, H, W, C] would indicate the probability of the pixel [H, W] belonging to class C.  Thus, you would want to find out which channel has the max value for the pixel [H, W] and then mark that pixel as belonging to a "person" or a "bird".

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ilous12** [comment]
Hi guys. Thanks your helps.

I has a question.

When I saw deeplabv3plus codes, input_name was "ImageTensor" and output_name was "SemanticPredictions".

But deeplabv3_257_mv_gpu.tflite was inputname : sub_7, out_name : resizeBilinear_3.
I did not understand why is different ?

And I trained deeplab3plus(https://github.com/tensorflow/models/tree/master/research/deeplab), I checked by tensorboard, there is no resizeBilinear_3.

tell me why anybody.

**Comment by impjdi** [comment]
@ilous12 

re: input

I have not run deeplabv3plus code you am referring to, but it looks like the input tensor usually goes through some normalization, e.g. 2.0 * (x / 255.0) - 1.0.  Apparently that has been removed, assuming the user would take care of the normalization before running the input.

re: output

I do see multiple resize bilinears in the model file?  https://github.com/tensorflow/models/blob/master/research/deeplab/model.py
Must be one of those resize bilinears.  _3 is just appended to avoid name collision.

**Comment by anilsathyan7** [comment]
We tried the same models and it was giving around 500ms on (OnePlus3 with Adreno 530) with proper segmentation mask.
Try using a smaller input size for better performance (at cost of accuracy offcourse).. 
See:https://github.com/intel/webml-polyfill/tree/master/examples/semantic_segmentation/model 
for model conversion commands.
Also if we use quantized version of same model with multiple threads it seems to give a better performance than Float models on CPU.
Hope you have tried official gpu demo app from repo for classification(i.e  from tensorflow/tensorflow/lite/java/demo).
We can use an 'argmax' function to get pixel classes from the output.
Also, if we can use the gpu memory efficiently without additional copying (like: camera bytes->bitmap->intpixels-> model) as mentioned in the documentation, may be we can get better speed up overall...

**Comment by freedomtan** [comment]
@ilous12 the GPU delegate doesn't support ops before sub_7 and after ResizeBilinear_3 yet. With tools, such as [`//tensorflow/tools/graph_transforms:summarize_graph`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/summarize_graph_main.cc), you should be able to see ResizeBilinear_3.

**Comment by essalahsouad** [comment]
@freedomtan 

> @ilous12 the GPU delegate doesn't support ops before sub_7 and after ResizeBilinear_3 yet. With tools, such as //tensorflow/tools/graph_transforms:summarize_graph, you should be able to see ResizeBilinear_3

i have trained deeplab on custom dataset,but when i visualise my trained model on netron i notice that it contains only sub_2 not sub_7 and resizeBilinear_2 not resize_3 even using this script 
[https://github.com/tensorflow/models/blob/master/research/deeplab/local_test_mobilenetv2.sh](https://github.com/tensorflow/models/blob/master/research/deeplab/local_test_mobilenetv2.sh)
i got the same architecture 
so when i deploy the model on mobile i got a slow segmentation, is'it the problem because of the sub2 and resizeBilinear or what??
`tflite_convert ----output_format=TFLITE --inference_type=FLOAT --inference_input_type=FlOAT --input_arrays=sub_2 --input_shapes=1,257,257,3 --output_arrays=ResizeBilinear_2 --output_file=mobilenet.tflite --grap-def=mobilenet.pb --mean_values=128 --std_dev_values=127 --allow_custom_ops --post_training_quantize`

**Comment by ZJamm1993** [comment]
Why it should be `out_pixel[c] = (input_pixel[c] - input_mean) / input_std;` in `ProcessInputWithFloatModel` function?
