### ISSUE TITLE
Error on using feature_columns with tf.keras

### ISSUE THREAD

**Issue by jimzhu** [tensorflow/tensorflow#25209]
**System information**
- TensorFlow version: 1.12
- Doc Link: https://github.com/tensorflow/docs/blob/b4d8d7096099c2b0a7df6a0564bf6eca8c96c4a0/site/en/tutorials/structured_data/feature_cols_keras.ipynb

**Describe the documentation issue**
when comment `tf.enable_eager_execution()`, the demo code fails. 

`ValueError: logits and labels must have the same shape ((32, 1) vs (32,))`

**Comment by wolffg** [comment]
This error doesn't appear in 2.0 under https://www.tensorflow.org/tutorials/structured_data/feature_columns, and we've upgraded our testing since then.  I'm closing this as fixed; thank you for bug report!
