### ISSUE TITLE
Error for using tensorflow on Ubuntu 14:04 with TITAN x

### ISSUE THREAD

**Issue by SalemAmeen** [tensorflow/tensorflow#2520]
Operating System:
   ubuntu 14.04
 ======================================================================  
Installed version of CUDA and cuDNN: 
 cuDNN v4 , CUDA 7.5

tensorflow)sal@sal-All-Series:~/tensorflow$ ls -l /home/sal/cuda/lib64/libcud*
lrwxrwxrwx 1 sal sal       15 Aug 21  2015 /home/sal/cuda/lib64/libcudnn.so -> libcudnn.so.7.0
lrwxrwxrwx 1 sal sal       17 Mar  1 18:27 /home/sal/cuda/lib64/libcudnn.so.4 -> libcudnn.so.4.0.7
-rw-rw-r-- 1 sal sal 61453024 Mar  1 18:27 /home/sal/cuda/lib64/libcudnn.so.4.0.7
lrwxrwxrwx 1 sal sal       18 Aug 21  2015 /home/sal/cuda/lib64/libcudnn.so.7.0 -> libcudnn.so.7.0.64
-rwxrwxr-x 1 sal sal 48217000 Aug 21  2015 /home/sal/cuda/lib64/libcudnn.so.7.0.64
-rw-rw-r-- 1 sal sal 62025862 Mar  1 18:27 /home/sal/cuda/lib64/libcudnn_static.a
(tensorflow)sal@sal-All-Series:~/tensorflow$ 

======================================================================

1. Virtualenv installation # I am not sure if this the answer

2. (tensorflow)sal@sal-All-Series:~/tensorflow$ python -c "import tensorflow; print(tensorflow.__version__)
"
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:99] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib64/:/home/sal/torch/install/lib::/usr/local/cuda-7.5/lib64:/opt/OpenBLAS-no-openmp/lib
I tensorflow/stream_executor/cuda/cuda_dnn.cc:1562] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.8.0
(tensorflow)sal@sal-All-Series:~/tensorflow$ 

===================================
I am trying to import tensorflow and use it with my TITAN X GPU and I
I think I have cuda installed as I use it with caffe and Torch7 even though I tried to install it from the beginning but same message I kept receiving. Any help please.
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:99] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib64/:/home/sal/torch/install/lib::/usr/local/cuda-7.5/lib64:/opt/OpenBLAS-no-openmp/lib
I tensorflow/stream_executor/cuda/cuda_dnn.cc:1562] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
>>>

**Comment by vrv** [comment]
You erased all the information we ask in our issue template, can you please include all that information so we can provide more help?

**Comment by SalemAmeen** [comment]
Sorry for that I have update it

**Comment by vrv** [comment]
It looks like your symlinks aren't set up properly -- you have both v3 and v4 installed, libcudnn.so points to so.7.0, which is v3

Secondly, your LD_LIBRARY_PATH doesn't have /home/sal/cuda/lib64 in it

**Comment by SalemAmeen** [comment]
Could you please tell me how I can sort them out?

**Comment by SalemAmeen** [comment]
Could you please tell me how I can sort them out?

**Comment by vrv** [comment]
Remove the existing libcudnn files and recopy libcudnn (just for v4).  You can Google for better instructions about how to set LD_LIBRARY_PATH.

**Comment by GoingMyWay** [comment]
After untar the cudnn

```
[root@localhost cudnn]# cd include/
[root@localhost include]# mv cudnn.h /usr/local/cuda/include/
[root@localhost include]# cd ../lib64/
[root@localhost lib64]# mv * /usr/local/cuda/lib
```
And it is ok

```
[root@localhost ~]# python
Python 2.7.5 (default, Sep 15 2016, 22:37:39) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as f
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally

```
