### ISSUE TITLE
lite: non-standard variable-length arrays

### ISSUE THREAD

**Issue by shibe2** [tensorflow/tensorflow#25215]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- TensorFlow installed from (source or binary): source
- TensorFlow version: commit [01dec19](https://github.com/tensorflow/tensorflow/tree/01dec19e827ab46ff7ff5dbd6142ba5a26efc4da)
- GCC/Compiler version (if compiling from source): gcc 8.2.1 20181127

**Describe the problem**

Structures `TfLiteIntArray` and `TfLiteFloatArray` have flexible array member `data`, which is not supported by the C++ standard. The header file name "c_api_internal.h" suggests that it's "C API" and "internal API", but it gets indirectly included by user C++ code via "interpreter.h". Although in practice it may not cause problems other than compiler warnings, it may still worth rewriting in standard C++ if the fix is easy and doesn't interfere with other code.

I propose using arrays of length 1:

    typedef struct {
      int size;
      int data[1];
    } TfLiteIntArray;

    typedef struct {
      int size;
      float data[1];
    } TfLiteFloatArray;

The dynamic size then can be calculated as follows:

    offsetof(TfLiteIntArray, data) + sizeof(int) * size

and

    offsetof(TfLiteFloatArray, data) + sizeof(float) * size

I checked that the dynamic size is always obtained via the functions `TfLiteIntArrayGetSizeInBytes` and `TfLiteFloatArrayGetSizeInBytes`. So only these functions would need to be changed, and no other code is affected.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Compile tensorflow/tensorflow/lite/examples/minimal/minimal.cc with -Wpedantic.

**Comment by jdduke** [comment]
Changing this could be problematic for historical reasons, but might be worth considering.

@karimnosseir any thoughts?

**Comment by pkgoogle** [comment]
Hi @shibe2, we no longer support dynamic input shapes for tflite: https://www.tensorflow.org/lite/guide/inference#run_inference_with_dynamic_shape_model, is your request here still valid?
