### ISSUE TITLE
lite: incorrectly written comparison in slice.cc

### ISSUE THREAD

**Issue by shibe2** [tensorflow/tensorflow#25214]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): commit [01dec19](https://github.com/tensorflow/tensorflow/tree/01dec19e827ab46ff7ff5dbd6142ba5a26efc4da)
- GCC/Compiler version (if compiling from source): gcc 8.2.1 20181127

**Describe the current behavior**

An assertion in [tensorflow/lite/kernels/slice.cc](https://github.com/tensorflow/tensorflow/blob/01dec19e827ab46ff7ff5dbd6142ba5a26efc4da/tensorflow/lite/kernels/slice.cc#L120):

    TF_LITE_ENSURE(context, NumDimensions(begin) == NumDimensions(size) == 1);

It evaluates the first `==` and then compares the result (true or false) with 1. It's probably not what's intended.

**Describe the expected behavior**

Based on the description of Slice, I believe, it should be:

    TF_LITE_ENSURE(context, NumDimensions(begin) == 1 && NumDimensions(size) == 1);

**Comment by yongtang** [comment]
@shibe2 it makes sense. Would you like to open a PR for it?

**Comment by shibe2** [comment]
@yongtang I can create PR.

**Comment by petewarden** [comment]
We weren't able to get to this fix in the last year, so closing the issue since we're unlikely to be able to work on it. Please reopen if you think this is a mistake.
