### ISSUE TITLE
Using transform_graph to quantize yolo-tiny-v2, performance & mAP drops. 

### ISSUE THREAD

**Issue by jasonwu1977** [tensorflow/tensorflow#25211]
I am using tranform_graph to quantize darkflow's tiny-yolo-v2 *.pb
[https://github.com/thtrieu/darkflow](https://github.com/thtrieu/darkflow)

found several issues
1. when i use video to do inference (or images) the performance drops to very low with gpu enable
from **5.xx fps to 1.xx fps**, and i can feel the images inference speed drops, by input with lots of pictures.

2. after use tranform_graph's quantization, the mAP drops from **68% to 13%** (with my 500 pics selcted from pascal_voc2012)
the function i used list below
```
../tensorflow-src/tensorflow/bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph=_151875_12_28_02_36_51_tiny-yolo-v2.pb  --inputs='input' --outputs='output' --out_graph=_151875_12_28_02_36_51_tiny-yolo-v2.quantize_node.pb --transforms='remove_nodes(op=Identity, op=CheckNumerics)
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  quantize_nodes
  strip_unused_nodes
  merge_duplicate_nodes
  sort_by_execution_order'
```

3. after quantize mAP drops, i use "insert_logging" & "freeze_requantization_ranges"
tried to bring back mAP with that pascal_voc selected 500 pictures
but the mAP drops to **0%.**

4. i wrote a script try to fix the logging file
I go thorough logging with single image, one by one 
if the mAP goes up, i merge with the last highest mAP ...
until the last image
so comes out with a valid logging file, which bring back the mAP to **62%** 

now the questions are
1. is that possible to quantize yolo-tiny-v2?
because the mAP and performance drops so much (even thou the mAP can be adjust back)
2. are there any other neural network models that you suggest me to use? 
my target is to create some quantized small models for running on ic chips
3. does that means logging and freeze_requantization_ranges might not suitable for tiny-yolo-v2?

Thanks for your time for reading this

== cat /etc/issue ===============================================
Linux 8fbb96ca119d 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.5 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
Yes

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux 8fbb96ca119d 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy                 1.15.4
protobuf              3.6.1
tensorflow-gpu        1.12.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.12.0
tf.GIT_VERSION = v1.12.0-0-ga6d8ffae09
tf.COMPILER_VERSION = v1.12.0-0-ga6d8ffae09
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /usr/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Sat Jan 26 05:56:00 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro GV100        Off  | 00000000:18:00.0 Off |                  Off |
| 40%   54C    P0    50W / 250W |      1MiB / 32508MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro GV100        Off  | 00000000:3B:00.0 Off |                  Off |
| 40%   54C    P0    50W / 250W |      0MiB / 32508MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so.9.0.176

**Comment by petewarden** [comment]
We're deprecating the graph transform tool, and recommend TF Lite for quantization, so I'm closing this one.
