### ISSUE TITLE
"ModuleNotFoundError : No module named 'keras' " Error while 'import keras' in Spyder(Python 3.5) launched through a environment with python 3.5 .

### ISSUE THREAD

**Issue by Amith4504** [tensorflow/tensorflow#25226]
**System information**
- Windows 8.1
- TensorFlow version: 1.10.0
- Python version:3.5
- Installed using  conda
- GCC/Compiler version

I had created a new conda environment named py35 for using spyder. py35 with Python3.5. I had also installed theano,tensorflow and keras using conda install commands with env activated . In admin cmd import command works fine for all three libraries. But in Spyder it return the error "ModuleNotFoundError: No module named  'keras'"

**Comment by ymodak** [comment]
Please take a look at a similar [issues](https://github.com/keras-team/keras/issues/4889)
