### ISSUE TITLE
TF Lite works wrong on quantized TF Hub retrained Inception V3 mnist model

### ISSUE THREAD

**Issue by dpinthinker** [tensorflow/tensorflow#25228]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS High Sierra 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Android Emulator
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly 1.13.0.dev20190123
- Python version:3.7.1
- Bazel version (if compiling from source):NA
- GCC/Compiler version (if compiling from source):NA
- CUDA/cuDNN version:NA
- GPU model and memory:NA

**Describe the current behavior**
- Using TF Hub to retrain Inception V3 for mnist images
- Converting the retrained model to quantized model
- Deploy the converted quantized model to Android App
- The quantized TF Lite works wrong like below:
![image](https://user-images.githubusercontent.com/2778945/51802538-1385ab00-2286-11e9-8297-cd9c7c3c5350.png)

**Describe the expected behavior**
- The mnist images are well classified.

**Code to reproduce the issue**
https://github.com/dpinthinker/TFGrocery/tree/master/MnistClassifier

**Comment by shashishekhar** [comment]
@dpinthinker : Can it be due to your preprocessing 
https://github.com/dpinthinker/TFGrocery/blob/master/MnistClassifier/app/src/main/java/com/dpthinker/mnistclassifier/model/InceptionQuantizedModelConfig.java

Check quantized preprocessing and difference between quantized and floating point here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/android/app/src/main/java/org/tensorflow/demo/TFLiteObjectDetectionAPIModel.java#L164

**Comment by dpinthinker** [comment]
Thank you, Shashi.

It means I need to remove the getImageMean and getImageSTD methods.

Could you tell me when should I call the getImageMean and getImageSTD
methods?


Shashi <notifications@github.com> 于 2019年1月29日周二 上午7:57写道：

**Comment by shashishekhar** [comment]
@dpinthinker : Correct or use 0 mean and 1 std if you want to keep your code.

Image is RGB so pixels have value in range [0-255] for each channel.
The floating point model is trained with [-1.0, 1.0] as inputs, so the colors are converted from 0-255 to  [-1.0, 1.0].

However quantized model uses uin8_t which have values is between 0-255, so we don't need to do preprocessing.

**Comment by dpinthinker** [comment]
@shashishekhar 
Thank you!
After removing mean and std, it still works wrong.
<img width="392" alt="2019-01-30 7 57 18" src="https://user-images.githubusercontent.com/2778945/51948779-d75c7100-2464-11e9-8bc7-182d904d8108.png">

It is the problem of my converted model?

**Comment by ANSHUMAN87** [comment]
@dpinthinker : Using TF Hub to retrain Inception V3 for mnist images  --> for this can u plz share the url@tf-hub which module u used. And what was the test accuracy while retraining.

Also one question, did u check post retraining about the same image prediction before quantization and post quantization. We cant judge a model, by just one image prediction, it has to be some bunch of images, and make the score for the model.

Also i think it would be better, if u can share the code from step 1 to end. It will help review your steps followed for any mistakes.

**Comment by dpinthinker** [comment]
@ANSHUMAN87 
# Retraining Model with TFHub
Using default retrain.py's default model, as following
python3.6 [retrain.py](https://github.com/tensorflow/hub/raw/master/examples/image_retraining/retrain.py
) --image_dir mnist_imgs/

It should be `https://tfhub.dev/google/imagenet/inception_v3/feature_vector/1`

# Retrained model works fine

```
python3.6 label_image.py --graph=output_graph.pb --labels=output_labels.txt --input_layer=Placeholder --output_layer=final_result --image=s3.jpg
2019-02-02 08:18:24.687863: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
3 0.92819667
2 0.027902907
5 0.018210107
9 0.010902734
7 0.0056838035
```

# Converting to float TFLite model and deploy
It works fine, using the following cmd to convert.
```
tflite_convert \
  --output_file=inceptionv3_mnist.tflite \
  --graph_def_file=output_graph.pb \
  --input_shape=1,299,299,3 \
  --input_arrays=Placeholder \
  --output_arrays=final_result
```

# Converting to Quantized TFLite model and deploy 
It works wrong, using the following cmd to convert.
```
tflite_convert \
  --output_file=inceptionv3_mnist_quantized_uint8.tflite \
  --graph_def_file=output_graph.pb \
  --input_shape=1,299,299,3 \
  --inference_type=QUANTIZED_UINT8 \
  --input_arrays=Placeholder \
  --output_arrays=final_result \
  --mean_values=128 \
  --std_dev_values=127 \
  --default_ranges_min=0 \
  --default_ranges_max=255
```

**Comment by suharshs** [comment]
What values are your inputs during float training preprocessed to?

Based on those values you have to set std_value and mean_value accordingly. 

The quantized model expects [0,255] inputs, but also expects these values to map to float.
mean_value = an integer value from [0,255] that corresponds to float 0.0f.
std_value = 255 / (float_max - float_min)

**Comment by dpinthinker** [comment]
@suharshs 

Thank you for your detailed answer. 

The preprocessed floating model used is from TFHub. The url of it is [https://tfhub.dev/google/imagenet/inception_v3/feature_vector/1](https://tfhub.dev/google/imagenet/inception_v3/feature_vector/1)

But I didn't find any info of the std_value and mean_value from it.
If possible, could you help loop the tfhub guys in this issue?

**Comment by suharshs** [comment]
The link you provided says: "The input images are expected to have color values in the range [0,1]". This means the mean_value and std_value can be computed using those formulas above, mapping [0, 255] to [0, 1].
mean_value  = 0. 
std_value = 255/ (1-0) = 255

Thanks!

**Comment by dpinthinker** [comment]
@suharshs Sorry to reply late. It is still not working. So sad!

**Comment by suharshs** [comment]
Hi @dpinthinker ,

Based on feedback that the contrib/quantize quantization-aware training tool is a bit brittle and hard to use on some model architectures, we have released a [post-training integer quantization tool](https://medium.com/tensorflow/tensorflow-model-optimization-toolkit-post-training-integer-quantization-b4964a1ea9ba), that requires a small calibration dataset. Please take a look at the [tutorial](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tutorials/post_training_integer_quant.ipynb) and give it a try, it should work much better! And let us know if you run into any issues.

Closing this issue, since we are rethinking and working on an api to replace contrib/quantize quantization-aware-training (although post-training quantization above should be sufficient for the majority of use cases).

This flow does not require std values or mean values.

Thanks!
-Suharsh
