### ISSUE TITLE
Duplicated Java outer classname

### ISSUE THREAD

**Issue by YuanWenqing** [tensorflow/tensorflow#25222]
**Describe the current behavior**
Option values of `java_outer_classname` in `tensorflow/compiler/tf2xla/host_compute_metadata.proto` and `tensorflow/compiler/tf2xla/tf2xla.proto` are the same, result in protoc failure for Java:

~~~
> protoc: stdout: . stderr: tensorflow/compiler/xla/rpc/xla_service.proto: warning: Import tensorflow/compiler/xla/xla_data.proto but not used.
  tensorflow/core/protobuf/replay_log.proto: warning: Import tensorflow/core/framework/graph.proto but not used.
  tensorflow/core/protobuf/replay_log.proto: warning: Import tensorflow/core/protobuf/cluster.proto but not used.
  org/tensorflow/tf2xla/Tf2XlaProtos.java: Tried to write the same file twice.
~~~

**Describe the expected behavior**
protoc succeeds without error.
`java_outer_classname` in `tensorflow/compiler/tf2xla/host_compute_metadata.proto` may be renamed to `HostComputeMetadataProtos`

**Code to reproduce the issue**

Just protoc

**Other info / logs**

**Comment by jvishnuvardhan** [comment]
@YuanWenqing  Could you describe more about the issue and context. Is this error during installation?

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by YuanWenqing** [comment]
@jvishnuvardhan I think this issue is just a compiling error when both `tensorflow/compiler/tf2xla/tf2xla.proto` and `tensorflow/compiler/tf2xla/host_compute_metadata.proto` are put in input files, no matter with operating system or architecture. Try this command:

~~~shell
mkdir /tmp/tf
cd /path/to/tensorflow-project
protoc --proto_path=. --java_out=/tmp/tf tensorflow/compiler/tf2xla/tf2xla.proto tensorflow/compiler/tf2xla/host_compute_metadata.proto
~~~

Then you'll get:
~~~bash
org/tensorflow/tf2xla/Tf2XlaProtos.java: Tried to write the same file twice.
~~~

Let me explain my situation to make this issue more clear and what happens. Actually what I need is a jar including all proto class from tensorflow and serving. Compiling of proto files in serving depends on proto files in tensorflow, so I put them all in one project and build them, like <https://github.com/YuanWenqing/tensorflow4j>. As you can see in the previous, building failed because of duplicated java_outer_classname option value in these two proto files.
Hope it is clear now :)

**Comment by nsthorat** [comment]
@jvishnuvardhan I’m not sure why I was added to this, I work on TensorFlow.js and have no state here :)

**Comment by jvishnuvardhan** [comment]
@jlebar Could you please take a look at this issue? Thanks!

**Comment by jlebar** [comment]
@jvishnuvardhan I'm also not sure why I was added to this -- I work on XLA.

**Comment by jvishnuvardhan** [comment]
@YuanWenqing Is this still an issue. I know this is a stale issue. I am not sure whether it was resolved or not. Could you check with recent TF versions and let us know whether the issue persists. thanks!

**Comment by YuanWenqing** [comment]
I suppose this issue is very clear and just a typo mistake. 

Look at these two files and check:

[tensorflow/compiler/tf2xla/host_compute_metadata.proto](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/host_compute_metadata.proto)
[tensorflow/compiler/tf2xla/tf2xla.proto](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/tf2xla.proto)

They both share the same `java_outer_classname` option value, so that error `org/tensorflow/tf2xla/Tf2XlaProtos.java: Tried to write the same file twice.` encountered when compiling proto files under `tensorflow/compiler/tf2xla` into java.

I see there is a naming convention in this project for the `java_outer_classname` option value: a snake-to-camel conversion from the filename and then `Protos` suffix appended. So `java_outer_classname` option value should be like `HostComputeMetadataProtos` in file [tensorflow/compiler/tf2xla/host_compute_metadata.proto](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/host_compute_metadata.proto) , but now `Tf2XlaProtos` is there. 

Isn't this a simple typo mistake, right?

**Comment by learndeep** [comment]
Still facing the same issue. @YuanWenqing Any solution or update on the issue?

**Comment by YuanWenqing** [comment]
> Still facing the same issue. @YuanWenqing Any solution or update on the issue?

No better solution but correct it manually ╮(╯▽╰)╭

**Comment by learndeep** [comment]
@sjamesr @jvishnuvardhan Please help with this. We are still facing the same issue while compiling proto to java sources.

**Comment by sushreebarsa** [comment]
@YuanWenqing Could you please check with recent TF version 2.6.0 and let us know whether the issue persists. Thanks!
