### ISSUE TITLE
tf.saved_model.save() exports a model with an empty method_name

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#25234]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac OS X 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
VERSION='2.0.0-preview'
GIT_VERSION="b'v1.12.0-6502-g76aa6cf917'"
- Python version:
3.6.8
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
Saving a Keras model with `tf.saved_model.save()` works, but the `method_name` is empty, so deploying the model to TensorFlow Serving fails.

**Describe the expected behavior**
I expect the `method_name` to be equal to `"tensorflow/serving/predict"`.

**Code to reproduce the issue**

```python
import tensorflow as tf
from tensorflow import keras
import numpy as np
import os

X_train = np.random.rand(100, 3)
y_train = np.random.rand(100, 1)
model = keras.models.Sequential([keras.layers.Dense(1)])
model.compile(loss="mse", optimizer="sgd")
model.fit(X_train, y_train)

model_version = 1
model_path = os.path.join("my_model", str(model_version))
os.makedirs(model_path)
tf.saved_model.save(model, model_path)
```

Next inspect the saved model:

```bash
$ saved_model_cli show --dir my_model/1 --all
```

Notice that the `method_name` is empty.

**Other info / logs**

Here is the output I get (I added comments marked with `# <=`):

```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID   # <= what is this?
        shape: unknown_rank # <= what is this?
        name: NoOp
  Method name is:   # <= empty method name

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_1'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 3)
        name: serving_default_input_1:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_1'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: StatefulPartitionedCall:0
  Method name is:  # <= empty, should be tensorflow/serving/predict
```

**Comment by ageron** [comment]
Workaround: if I save the model using `keras.experimental.export()`, the saved model has a correct `method_name`.

**Comment by 7PintsOfCherryGarcia** [comment]
Can tf.saved_model.save() save with additional MetaGraphDef in order to have tag 'train'?
