### ISSUE TITLE
 failed to process “api_def_Conv2D.pbtxt”: Attribute explicit_paddings not defined in base api for Conv2D

### ISSUE THREAD

**Issue by davidgtunity** [tensorflow/tensorflow#25232]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  -
`Mac OS X 10.13.6`
- TensorFlow version (use command below): - 
```
tf.VERSION = 1.12.0
tf.GIT_VERSION = v1.12.0-rc2-3-ga6d8ffae09
tf.COMPILER_VERSION = v1.12.0-rc2-3-ga6d8ffae09
Sanity check: array([1], dtype=int32)
```
- Python version:
`Python 3.6.5`

**Describe the current behavior**
Hi, I try to run tensorflow using golang, </br>
When I execute the following command: </br>`go generate github.com/tensorflow/tensorflow/tensorflow/go/op` </br>
I get this error: </br>
```
2019/01/27 18:21:15 failed to process “api_def_Conv2D.pbtxt”: Attribute explicit_paddings not defined in base api for Conv2D
exit status 1
op/generate.go:18: running “go”: exit status 1
```

**Comment by ymodak** [comment]
@asimshankar Can you PTAL? Thanks

**Comment by bioothod** [comment]
This is because your local libtensorflow.so has been compiled against older tree, which doesn't include commit ec81825aaf7e848d9f8ddffdf1e0d20aebe9172c which introduced this new attribute

**Comment by ymodak** [comment]
@davidgtunity 
Is this still an issue for you? Did you try this suggestion? 
> This is because your local libtensorflow.so has been compiled against older tree, which doesn't include commit [ec81825](https://github.com/tensorflow/tensorflow/commit/ec81825aaf7e848d9f8ddffdf1e0d20aebe9172c) which introduced this new attribute

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
