### ISSUE TITLE
tensorflow.contrib.lite.Interpreter.invoke() crashes 

### ISSUE THREAD

**Issue by YakirYehuda** [tensorflow/tensorflow#25231]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac os - Mojave
- TensorFlow installed from (source or binary): from pip
- TensorFlow version (use command below):  from pip -'v1.12.0-rc2-3-ga6d8ffae09', '1.12.0'
- Python version: 3.6

**Describe the current behavior**
Hey. 
-im building a test model from a net I designed for OCR. 
-The model is running fine on Tensorflow mobile and I get good results (the model is running fine and I have NO errors).
-All the work is in python.
-Part of the work is to convert the model to 'lite' and running it on mobile, I do it with this code : 

 ```
  input_arrays = ["input"]
  output_arrays = ["output"]
  converter = lite.TFLiteConverter.from_frozen_graph(
  forzen_file_path, input_arrays, output_arrays, input_shapes=shape)
  converter.allow_custom_ops = True
  tflite_model = converter.convert()
  open(output_path, "wb").write(tflite_model)
```

This part is working well. 

- Using the following code (obtained from the docs ) Im checking the conversion:

   ```
    interpreter = lite.Interpreter(model_path=lite_model)
    interpreter.allocate_tensors()

    # Get input and output tensors.
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    # Test model on random input data.
    input_shape = input_details[0]['shape']
    input_type = input_details[0]['dtype']
    random_sample = np.random.random_sample(input_shape)
    input_data = np.array(random_sample, dtype=input_type)
    interpreter.set_tensor(input_details[0]['index'], input_data)

    interpreter.invoke() <---- crash! SIGSEGV 11 
    output_data = interpreter.get_tensor(output_details[0]['index'])



And I get a crash with no details on what happened:

```
2019-01-27 17:45:08.423844: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

```

I've tried to compile tensorflow and debug it myself but google uses bazel and I cant get it to import on CLion (with the bazel plugin). 

Does anybody knows what is going on? 

**Describe the expected behavior**
Not crashing :)

**Code to reproduce the issue**
I'm not allowed to share the model but i've shared the conversion and the interpreter code above. 

**Other info / logs**
I want to state again these few things:
- The model runs well on Tensorflow (not lite)
- The conversion runs well with no errors. 
- The crash occurs when calling interpreter.invoke() 

**Thank you!**

**Comment by YakirYehuda** [comment]
I wanted to add and it might help, 
Out work is based on this project:
https://github.com/IBM/tensorflow-hangul-recognition

**Comment by Oktai15** [comment]
@YakirYehuda did you fix a problem?

**Comment by Oktai15** [comment]
@ymodak can we do something with it as workaround?

**Comment by Oktai15** [comment]
@YakirYehuda my problem was related with tensors with shapes > 4. It turned out that TFLite can’t do any operation with them.

**Comment by liyunlu0618** [comment]
Please try what @Oktai15 suggested and feel free to reopen if there's still problem.

**Comment by bmabir17** [comment]
I have the same problem
I was able to convert the [mask-rcnn from matterport](https://github.com/matterport/) using [this script](https://gist.github.com/bmabir17/754a6e0450ec4fd5e25e462af949cde6 ) with tflite 1.3


But now i am facing a segmentation error, when i try to run inference with the tflite interpreter (Tried both 1.3 and 2.0 tflite versions)
```python
def load_tf_model(model_path="mask_rcnn_coco_256_exp.tflite"):
    interpreter = tf.lite.Interpreter(model_path)
    # Get input tensors.
    input_details = interpreter.get_input_details()
    interpreter.resize_tensor_input(input_details[0]['index'],(1,256,256,3))
    interpreter.allocate_tensors()

    # Get output tensors.
    output_details = interpreter.get_output_details()
    # Test model on random input data.
    input_shape = input_details[0]['shape']
    input_data = np.array(np.random.random_sample((1, 256, 256,3)), dtype=np.float32)
    interpreter.set_tensor(input_details[0]['index'], input_data)
    interpreter.invoke()

    # The function `get_tensor()` returns a copy of the tensor data.
    # Use `tensor()` in order to get a pointer to the tensor.
    output_data = interpreter.get_tensor(output_details['index'])
    print(output_data)
```

**Comment by UcefMountacer** [comment]
Hey @bmabir17 

I have the same issue, I converted from a modified version of matterport mask rcnn (tf v2) and the session crashes when I invoke the interpreter. Also, isn't there other inputs beside the image ? 

@Oktai15 Can you explain further. Our model gets an input of 3 tensors :

```
interpreter.set_tensor(input_details[0]['index'], image)
interpreter.set_tensor(input_details[1]['index'], A)
interpreter.set_tensor(input_details[2]['index'], B)
```

image.shape = (1,1024,1024,3)

**Comment by Oktai15** [comment]
> Hey @bmabir17
> 
> I have the same issue, I converted from a modified version of matterport mask rcnn (tf v2) and the session crashes when I invoke the interpreter. Also, isn't there other inputs beside the image ?
> 
> @Oktai15 Can you explain further. Our model gets an input of 3 tensors :
> 
> ```
> interpreter.set_tensor(input_details[0]['index'], image)
> interpreter.set_tensor(input_details[1]['index'], A)
> interpreter.set_tensor(input_details[2]['index'], B)
> ```
> 
> image.shape = (1,1024,1024,3)

I suppose your model uses 4D-tensor (or more) in the middle of architecture and it’s the problem for TFLite, i.e it is not only for input, but also for every inner tensors

**Comment by tgeffroyModuleus** [comment]
Hi @Oktai15

I am facing an issue where it seems that the interpreter crashes while using an input tensor of shape length equaled to 5.
I don't find the documentation describing this tensor dimension constraint. Do you have one?
Also, is it normal that the interpreter just crash without any error message?
I think it should be logged.
