### ISSUE TITLE
Code example to save a custom model with a serve() method fails

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#25235]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes and No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac OS X 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
VERSION='2.0.0-preview'
GIT_VERSION="b'v1.12.0-6502-g76aa6cf917'"
- Python version:
3.6.8
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
The [documentation](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/saved_model/save) of the `tf.saved_model.save()` function shows a code example to save a custom model with a `serve()` method, but it fails:
1. when subclassing the `keras.models.Model` class, it is compulsory to define a `call()` method (or else you get `NotImplementedError: When subclassing the Model class, you should implement a call method.`.
2. when saving the model as shown in the code example, I get `ValueError: Exporting an object with no tf.saved_model.save(..., signatures=...) argument specified, and with more than one @tf.function-decorated method attached to it: ['_default_save_signature', 'serve']. The signature keys for these functions are ambiguous. Specify signature functions explicitly.`

However it works if I define a `call()` method and I specify the signature explicitly.

**Describe the expected behavior**
Perhaps the documentation just needs to be fixed to add a `call()` method and an explicit `signature` argument, but it would be nicer if it could work without having to do that.

**Code to reproduce the issue**

```python
import tensorflow as tf
from tensorflow import keras

(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()

class MyModel(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.probas = keras.layers.Dense(10, activation="softmax")
    @tf.function(input_signature=[
        tf.TensorSpec(shape=[None], dtype=tf.string)])
    def serve(self, serialized):
        expected_features = {
            "image": tf.io.FixedLenFeature([28 * 28], dtype=tf.float32)
        }
        examples = tf.io.parse_example(serialized, expected_features)
        return self.probas(examples["image"])
    def call(self, inputs):
        return self.probas(inputs)

m = MyModel()
m.compile(loss="sparse_categorical_crossentropy", optimizer="sgd")
m.fit(X_train.reshape(-1, 28*28), y_train)
tf.saved_model.save(m, "my_model_test",
    signatures=m.serve.get_concrete_function(
        tf.TensorSpec(shape=[None], dtype=tf.string, name="serialized_inputs")))
```

You can try removing the `call()` method, it will fail. You can also try removing the `signatures` argument in the `tf.saved_model.save()` call, it will fail.

**Other info / logs**

Here is the output I get when I don't specify the signature:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-424-4d06f50f5010> in <module>
      2 m.compile(loss="sparse_categorical_crossentropy", optimizer="sgd")
      3 m.fit(X_train.reshape(-1, 28*28), y_train)
----> 4 tf.saved_model.save(m, "my_model_test")#,
      5 #    signatures=m.serve.get_concrete_function(
      6 #        tf.TensorSpec(shape=[None], dtype=tf.string, name="serialized_inputs")))

~/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py in save(obj, export_dir, signatures)
    820 
    821   if signatures is None:
--> 822     signatures = _find_function_to_export(saveable_view)
    823   signatures = _canonicalize_signatures(signatures)
    824 

~/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py in _find_function_to_export(saveable_view)
    144            "keys for these functions are ambiguous. Specify signature "
    145            "functions explicitly.").format(
--> 146                [previous_attribute_name, name]))
    147     exported_function = value
    148     previous_attribute_name = name

ValueError: Exporting an object with no tf.saved_model.save(..., signatures=...) argument specified, and with more than one @tf.function-decorated method attached to it: ['_default_save_signature', 'serve']. The signature keys for these functions are ambiguous. Specify signature functions explicitly.
```

**Comment by allenlavoie** [comment]
This works for me now (with a cast to float so fit() works). Probably after https://github.com/tensorflow/tensorflow/commit/24cc2f6d0b86674a34e831357eb60d70d54190e7

Thanks for the report.
