### ISSUE TITLE
Build issue of "cannot find symbol class Fill where T is a type-variable: T extends Object declared in class Zeros" still persists, when building Bazel. 

### ISSUE THREAD

**Issue by anamozov** [tensorflow/tensorflow#25239]
**System information**
- Ubuntu 16.04 LTS:
- TensorFlow installed from source:
- TensorFlow version 1.12:
- Python version 2.7:
- Bazel version 0.21.0:

**Describe the problem**
I am going to build Tensorflow Object Detection API Android demo using Bazel which is **def nativeBuildSystem = 'bazel'** But got the following error _**error: cannot find symbol class Fill where T is a type-variable: T extends Object declared in class Zeros **_
I followed the instruction given [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/README.md](url). All steps were completed, except this [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/README.md#android-studio-with-bazel](url), which is building the demo using Android Studio and Bazel. This step is important for my project since Object tracking option requires Bazel. 

**Any other info / logs**
 _**Android Studio Version: 3.3**_
_**Gradle version: 3.3.0**_
Any of the instructions and suggestions in either [https://github.com/tensorflow/tensorflow/issues/21431](url), or [https://github.com/tensorflow/tensorflow/issues/23457](url) **DID NOT HELP**, however issues were closed.

**Comment by akshayudnur** [comment]
I got the same issue.

**Comment by anamozov** [comment]
@akshayudnur do you have any news so far?

**Comment by gunan** [comment]
Routing to @jdduke as this looks like an android build issue.

**Comment by jdduke** [comment]
Just to confirm, this is a *build* error, not a runtime error? Can you provide the full dump of the error and surrounding output?

**Comment by anamozov** [comment]
@jdduke Sorry for late reply. This is a BUILD ERROR. 
The problem is when I build tensorflow demo using bazel with following command **bazel build --cxxopt='--std=c++11' -c opt //tensorflow/examples/android:tensorflow_demo** in terminal, it succeed, but when I try to build using Android Studio it shows following error in tensorflow/tensorflow/java/src/main/java/org/tensorflow/op/core/Zeros.java file:
_**error: cannot find symbol class Fill
where T is a type-variable:
T extends Object declared in class Zeros
**_;
_**error: cannot find symbol class Fill
where T is a type-variable:
T extends Object declared in class Zeros
**_;
_**error: cannot find symbol variable Fill
where T is a type-variable:
T extends Object declared in class Zeros
**_.

**Comment by jdduke** [comment]
As mentioned in the TensorFlow Dev Summit today, TensorFlow Mobile is being deprecated. It's highly unlikely that we'll continue supporting the gradle-based builds for the TFMobile samples. Is there a reason you cannot use TensorFlow Lite?

That said, it looks like this is an issue with the codegen dependency, as the Fill class is dynamically generated. Maybe there have been some more recent changes in how these classes are generated, but I haven't really followed the TensorFlow Java efforts.

**Comment by anamozov** [comment]
@jdduke The main reason why I am using TFMobile with Basel build option is object tracking function. With TFMobile I was able to build (on terminal) Android Demo with Object tracking option. So far, I could not Object tracking work with TensorFlow Lite.

**Comment by jdduke** [comment]
> However, I could not Object tracking work with TensorFlow Lite so far

Could you be more specific? Are you not able to use https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android?

**Comment by anamozov** [comment]
> Are you not able to use https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android?

Exactly. When the application starts toast with "Object tracking support not found" text comes out. 
As I mentioned earlier, with TFMobile and Bazel I was I able to build the app (only on terminal) with Object tracking support. 
In conclusion, I want  **Object tracking** support to work.

**Comment by jdduke** [comment]
The object tracking is really just a clever way of masking the latency of the actual SSD inference. There's no reason you can't use the object tracking code in your own project with TFLite. The reason it doesn't work in that sample is 1) latency is now much lower, and approaching real-time, allowing independent detection, and 2) the TFLite detection sample was a fork of the TF detection sample, but it was decided not to pull in the [extra, more complicated object tracking code](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android/jni/object_tracking).

**Comment by grwlf** [comment]
Hi, I see the same error in current r2.0 release.

> As mentioned in the TensorFlow Dev Summit today, TensorFlow Mobile is being deprecated

I would suggest to highlight the fact that `examples/android` is related to deprecated TensorFlow Mobile project. It is not clear from the documentation.

Could you please specify where can I find TFLite examples in v2.0 ?

**Comment by grwlf** [comment]
> Hi, I see the same error in current r2.0 branch.
> 
> > As mentioned in the TensorFlow Dev Summit today, TensorFlow Mobile is being deprecated
> 
> I would suggest to highlight the fact that `examples/android` is related to deprecated TensorFlow Mobile project. It is not clear from the documentation.
> 
> Could you please specify where can I find TFLite examples in v2.0 ?

Answering to myself: For TF 2.0 compatible demos seems to live in https://github.com/tensorflow/examples
