### ISSUE TITLE
deeplab with tensorflow lite + gpudelegate issue

### ISSUE THREAD

**Issue by ilous12** [tensorflow/tensorflow#25238]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

I tried to build deeplab (input_image + float32) and succeeded

# modified export_model.py # line:77

```
//input_image = tf.placeholder(tf.uint8, [1, None, None, 3], name=_INPUT_NAME)
input_image = tf.placeholder(tf.float32, [1, None, None, 3], name=_INPUT_NAME)
```

S. I converted below command and succeeded

tflite_convert \
  --output_file=deeplab_257_float.tflite \
  --graph_def_file=$PB_FILE \
  --output_format=TFLITE \
  --input_arrays=ImageTensor \
  --output_arrays=SemanticPredictions \
  --input_shapes=1,257,257,3 \
  --inference_input_type=FLOAT \
  --target_ops=TFLITE_BUILTINS,SELECT_TF_OPS \
  --inference_type=FLOAT \
  --mean_values=128 \
  --std_dev_values=127 \

But. when i  try to run on android, I saw below issue.

` java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: WARNING: op code #38 cannot be handled by this delegate.  Only the first 32 ops will run on the GPU, and the remaining 88 on the CPU.GpuDelegate Prepare: First dimension is supposed to be BATCH and always equal to 1.Node number 120 (GpuDelegate) failed to prepare.`

what's wrong with my model?

deeplabv3_257_mv_gpu.tflite is working.

# Can you tell me about how can I do that?
# Can you tell me about your tflite_convert command?

**Describe the expected behavior**

working.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by freedomtan** [comment]
if you inspect the `deeplabv3_257_mv_gpu.tflite` you mentioned, you can find that its input node is `sub_7` and output node is `ResizeBilinear_3`. That is, preprocessing ops and ops after `ResizeBilinear_3` are removed.

**Comment by ilous12** [comment]
nice answer thanks.

**Comment by Ayush517** [comment]
Is this issue still there or is it solved?

**Comment by ilous12** [comment]
@freedomtan I tried to change the input and out by belows command like 

> deeplabv3_257_mv_gpu.tflite

> tflite_convert \
>  --output_file=$TF_FILE \
>  --graph_def_file=$PB_FILE \
>  --output_format=TFLITE \
>  --input_arrays=sub_7 \
>  --output_arrays=ResizeBilinear_2 \
>  --inference_input_type=FLOAT \
>  --inference_type=FLOAT \

Is it right way?
