### ISSUE TITLE
Error building tensorflow pip package

### ISSUE THREAD

**Issue by mrevow** [tensorflow/tensorflow#25237]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.12
- Python version: 3.6.4
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): cl 19.16.27025.1
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Get error when building the pip package from build_pip_package:

> error in tensorflow setup command:
> 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'< 1.14.0'"

This error only appears after a recent pull request (2019/01/26)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

_Get clean copy of tensorflow_ 
`git pull`

 _Build CPU version_
`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

 _Build  pip package:_
`bazel-bin\tensorflow\tools\pip_package\build_pip_package.exe tmp/tensorflow_pkg`

> Sun Jan 27 14:02:41 PST 2019 : === Preparing sources in dir: /tmp/tmp.YaQ7qcBkdZ
> Unzipping simple_console_for_windows.zip to create runfiles tree...
> Unzip finished.
> /e/src/gitClones/tensorflow /e/src/gitClones/tensorflow
> /e/src/gitClones/tensorflow
> Sun Jan 27 14:05:55 PST 2019 : === Building wheel
> error in tensorflow setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'< 1.14.0'"

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Digging into this I believe the issue is at line 61 in [setup.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L61) 
which was introduced by c4388465d0d04ed90c814a11216217d19a8267e8

I made this change locally and the problem goes away

> @@ -58,7 +58,7 @@ REQUIRED_PACKAGES = [
>      'six >= 1.10.0',
>      'protobuf >= 3.6.1',
>      'tensorboard >= 1.12.0, < 1.13.0',
> **-    'tensorflow_estimator >= 1.13.0 < 1.14.0',**
> **+    'tensorflow_estimator >= 1.13.0, < 1.14.0',**
>      'termcolor >= 1.1.0',
>  ]

cc @case540

**Comment by yongtang** [comment]
This issue is related to PR #25221.

**Comment by Dayananda-V** [comment]
This issue is resolved with PR #25244

**Comment by ToughLife** [comment]
I got the same error on Ubuntu 18.04, CUDA 10, Anaconda 3 (Python 3.7).
Does the 'tensorflow_estimator' means numpy?

**Comment by ToughLife** [comment]
Thanks for @yongtang and @Dayananda-V, through the method in PR #25221, the error is solved.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
