### ISSUE TITLE
A question about tflite inference

### ISSUE THREAD

**Issue by ai-libo** [tensorflow/tensorflow#25243]
Hello, i use aware training method get a quantize model ,so in the tflite inference implementation, which part processes "zero_point"(Such as input and filter data should be combined with offset)  in the convolution code of tflite? Could you please give me a link？ thanks

**Comment by suharshs** [comment]
Hello, the zero_point gets set to the filter_offset here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/conv.cc#L414

Then it gets used in the kernel here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/reference/reference_ops.h#L383
