### ISSUE TITLE
[Docker] include jupyter_http_over_ws in Jupyter Docker images

### ISSUE THREAD

**Issue by dkarlovi** [tensorflow/tensorflow#25247]
**System information**
- TensorFlow version (you are using): `tensorflow/tensorflow:nightly-gpu-py3-jupyter`
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**

Following [these instructions](https://research.google.com/colaboratory/local-runtimes.html), it requires to have `jupyter_http_over_ws` Jupyter extension to work. The current Docker image doesn't seem to have it (or I'm mistaken, please correct if so).

Having the Docker Jupyter images have this preinstalled would allow for this integration to be made more straightforward.

**Will this change the current api? How?**

No.

**Who will benefit with this feature?**

Any Docker Jupyter users using Google's Colaboratory (or other frontend using the interface).

**Any Other info.**

N/A.

**Comment by yongtang** [comment]
Added a PR #25255, Will let the docker file maintainers to decide if it will be merged or not.
