### ISSUE TITLE
Keras & Estimator: 'MeanMetricWrapper' object has no attribute '__name__'

### ISSUE THREAD

**Issue by tarrade** [tensorflow/tensorflow#25259]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.14.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary, using pip
- TensorFlow version (use command below): b'v1.12.0-4728-ga8e5c41c5b' 1.13.0-rc0
- Python version: 3.6.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Buid a simple Sequencial model using Keras. It works well with Keras `model.fit()`. Now converting this model to be used with estimator` tf.keras.estimator.model_to_estimator(keras_model=model)`. Then using `train()` then the code crashed with:
 'MeanMetricWrapper' object has no attribute '__name__'

**Describe the expected behavior**
The same code was runing with tf 1.12 and I could train the model using estimator

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

The code can be find in the following notebook:
https://github.com/tarrade/proj_DL_models_and_pipelines_with_GCP/blob/master/notebook/08_Example_mnist_keras_estimator_tf_1_13.ipynb

```
def baseline_model():
    # create model
    model = tf.keras.Sequential()
 
    # hidden layer
    model.add(tf.keras.layers.Dense(dim_input, 
                    input_dim=dim_input, 
                    kernel_initializer=tf.keras.initializers.he_normal(),
                    bias_initializer=tf.keras.initializers.Zeros(),
                    activation='relu'))
    # last layer
    model.add(tf.keras.layers.Dense(num_classes, 
                    kernel_initializer=tf.keras.initializers.he_normal(),
                    bias_initializer=tf.keras.initializers.Zeros(),
                    activation='softmax'))

    optimiser=tf.keras.optimizers.Adam(lr=0.01, beta_1=0.9)
    # Compile model
    model.compile(loss='categorical_crossentropy', 
                  optimizer=optimiser, 
                  metrics=['accuracy'])
    return model
```

`model = baseline_model()`

```
def input_dataset_fn(x_data, y_data, batch_size=128, mode=tf.estimator.ModeKeys.TRAIN):
    
    if mode == tf.estimator.ModeKeys.PREDICT:
        tf.logging.info("input_dataset_fn: PREDICT, {}".format(mode))
    elif mode == tf.estimator.ModeKeys.EVAL:
        tf.logging.info("input_dataset_fn: EVAL, {}".format(mode))
    elif mode == tf.estimator.ModeKeys.TRAIN:
        tf.logging.info("input_dataset_fn: TRAIN, {}".format(mode))
    
    dataset = tf.data.Dataset.from_tensor_slices((x_data, y_data))
   
    if mode == tf.estimator.ModeKeys.TRAIN:
        num_epochs = FLAGS.epoch
        dataset = dataset.shuffle(buffer_size=FLAGS.shuffle_buffer_size, seed=2)# depends on sample size
    else:
        num_epochs = FLAGS.epoch # to use validation data with keras
    dataset = dataset.repeat(num_epochs)
    dataset = dataset.batch(batch_size=batch_size, drop_remainder=True)
    dataset = dataset.prefetch(FLAGS.prefetch_buffer_size)

    return dataset
```

`estimator_train_model = tf.keras.estimator.model_to_estimator(keras_model=model)`

```
estimator_train_model.train(input_fn=lambda: input_dataset_fn(x_train, y_train, mode=tf.estimator.ModeKeys.TRAIN, batch_size=FLAGS.batch_size),
                            steps=10)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
INFO:tensorflow:Calling model_fn.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-123-a7db13f8b1dd> in <module>
      1 # Fit the model (using estimator.train and data.Dataset)
      2 estimator_train_model.train(input_fn=lambda: input_dataset_fn(x_train, y_train, mode=tf.estimator.ModeKeys.TRAIN, batch_size=FLAGS.batch_size),
----> 3                             steps=10)
      4 
      5 #estimator_train_model.train(input_fn=get_train_input_fn,

~/anaconda3/envs/env_gcp_dl_1_13/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    352 
    353       saving_listeners = _check_listeners_type(saving_listeners)
--> 354       loss = self._train_model(input_fn, hooks, saving_listeners)
    355       logging.info('Loss for final step: %s.', loss)
    356       return self

~/anaconda3/envs/env_gcp_dl_1_13/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_model(self, input_fn, hooks, saving_listeners)
   1181       return self._train_model_distributed(input_fn, hooks, saving_listeners)
   1182     else:
-> 1183       return self._train_model_default(input_fn, hooks, saving_listeners)
   1184 
   1185   def _train_model_default(self, input_fn, hooks, saving_listeners):

~/anaconda3/envs/env_gcp_dl_1_13/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_model_default(self, input_fn, hooks, saving_listeners)
   1211       worker_hooks.extend(input_hooks)
   1212       estimator_spec = self._call_model_fn(
-> 1213           features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
   1214       global_step_tensor = training_util.get_global_step(g)
   1215       return self._train_with_estimator_spec(estimator_spec, worker_hooks,

~/anaconda3/envs/env_gcp_dl_1_13/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _call_model_fn(self, features, labels, mode, config)
   1169 
   1170     logging.info('Calling model_fn.')
-> 1171     model_fn_results = self._model_fn(features=features, **kwargs)
   1172     logging.info('Done calling model_fn.')
   1173 

~/anaconda3/envs/env_gcp_dl_1_13/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/keras.py in model_fn(features, labels, mode)
    286       loss = model.total_loss
    287 
--> 288       eval_metric_ops = _convert_keras_metrics_to_estimator(model)
    289 
    290     # Set train_op only during train.

~/anaconda3/envs/env_gcp_dl_1_13/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/keras.py in _convert_keras_metrics_to_estimator(model)
    231     for i, metric_name in enumerate(model.metrics):
    232       if callable(metric_name):
--> 233         metric_name = metric_name.__name__
    234       eval_metric_ops[metric_name] = metrics_module.mean(
    235           model.metrics_tensors[i])

AttributeError: 'MeanMetricWrapper' object has no attribute '__name__'

**Comment by tarrade** [comment]
could it be an installation issue ? I installed it using pip. Before (1.12 installed with conda), I didn't have a  separate package tensorflow-estimator 
tensorboard               1.12.2                    <pip>
tensorflow                1.13.0rc0                 <pip>
tensorflow-estimator      1.10.12                   <pip>

**Comment by aselle** [comment]
A known bug in the RC0 is that it doesn't force the upgrade of estimator to the correct version. Can you try forcing an upgrade of tensorflow-estimator to 1.13.0rc0 i.e.

pip install --upgrade tensorflow==1.13.0rc0 tensorflow-estimator==1.13.0rc0

This matches more what we will be doing in the RC1.

**Comment by ShikhaSingh10** [comment]
tensorboard               2.2.2                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.2.0                    pypi_0    pypi
tensorflow-estimator      2.2.0                    pypi_0    pypi
tensorflow-probability    0.10.0                   pypi_0    pypi

Can anyone help me out, what is the issue here?
