### ISSUE TITLE
TF 2.0 Conversion Script does not have a replacement for tf.contrib.eager.defun(train_step).

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25257]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): 2.0
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Submitting on behalf of @victordibia. Thanks, Victor! 😊

**Describe the expected behavior**

I used the TF 2.0 conversion script to convert my DCGAN sample from tf1.x to tf2.0.

It suggested use of tf.compat.v1.losses.sigmoid_cross_entropy  (previously in contrib), but am unclear if this has same behaviour as tf.nn.softmax_cross_entropy_with_logits. The script did not recommend a replacement for tf.contrib.eager.defun(train_step).

**Code to reproduce the issue**
https://github.com/victordibia/tf2/blob/master/dcgan/dcgan.py

**Other info / logs**
Friction log: https://docs.google.com/document/d/1Sv6INZzqLUUChy46jeawX1FdO1rG5aAjjGde7wOSBb8/edit?usp=sharing

**Comment by alextp** [comment]
softmax_cross_entropy_with_logits and sigmoid_cross_entropy definitely do not have the same behavior. Can you link me to a message suggesting one for the other? It's a bug.

tf.contrib.eager.defun can usually be replaced with tf.function but variable creation semantics are slightly different, so we can't make the transition automatically.

**Comment by martinwicke** [comment]
the direct replacement for `tf.contrib.losses.softmax_cross_entropy` is `tf.compat.v1.losses.tf.losses.softmax_cross_entropy`.

I would welcome a PR adding this to `tf_upgrade_v2.py`.

**Comment by victordibia** [comment]
I confirm that the `tf_upgrade_v2` script **already** does this replacement. 
I (incorrectly) assumed that `losses.softmax_cross_entropy` may have moved to some other location in the tf2.0 api. Thanks Martin.
I think this issue can be closed now.
