### ISSUE TITLE
tf.nn.bias_add and tf.add as checkpointable

### ISSUE THREAD

**Issue by agniszczotka** [tensorflow/tensorflow#25258]
Please consider adding operation to checkpointable such as add, multiply, etc. Checkpointable does not work with any operands tf.keras.layers.add, tf.nn.bias_add, tf.add, +

**Comment by jvishnuvardhan** [comment]
@agniszczotka Could you provide more details about the features you are looking and the context of usage of those features. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
