### ISSUE TITLE
Usage of tf_stack.extract_stack in registry.py breaks TensorFlow R client

### ISSUE THREAD

**Issue by skeydan** [tensorflow/tensorflow#25262]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Fedora 29
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): nightly
- Python version: 3.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

Hi,

this usage of `tf_stack` in registry.py

```
stack = tf_stack.extract_stack()
user_function = stack[2]
```

breaks the TensorFlow for R client, because at that point, when called from R `stack` is of length 2, with both elements being of length 6.

This is analogous to the recently fixed https://github.com/tensorflow/tensorflow/issues/25067
(thank you @jtkeeling)

It would be awesome if this could still be fixed for the 1.13 release, as I'm aware of no workaround and we have users that want to register a custom gradient.

Many thanks!

**Comment by jtkeeling** [comment]
Yes, this is entirely analogous to #25067. I've authored a fix and sent for review.

**Comment by skeydan** [comment]
Great thank you for the quick fix!!!

**Comment by martinwicke** [comment]
This is fixed right (cf other issue)?

**Comment by jtkeeling** [comment]
@martinwicke This is another piece of code that uses tf_stack. I've sent you another change that fixes this one.

**Comment by martinwicke** [comment]
Thanks! We'll wait for that to close.
