### ISSUE TITLE
TypeError: Failed to convert object of type <class 'tensorlayer.layers.PReluLayer'> to Tensor. Contents:   Last layer is: PReluLayer. Consider casting elements to a supported type.

### ISSUE THREAD

**Issue by Dee-Ma** [tensorflow/tensorflow#25260]
I am using tensorflow to construct CNN model. However, I got two errors when using tf.image.resize_images function:

1st error: TypeError: Expected binary or unicode string, got <tensorlayer.layers.PReluLayer object at 0x0000000031962D68>

2nd error: TypeError: Failed to convert object of type <class 'tensorlayer.layers.PReluLayer'> to Tensor. Contents:   Last layer is: PReluLayer. Consider casting elements to a supported type.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- TensorFlow version (use command below): 1.8.0
- Python version: 3.5
- CUDA/cuDNN version: 9.0.167 (CUDA)
- GPU model and memory: P6000

**Describe the current behavior**
The part of the code is:

'conv4 = Conv2d(conv3_bn_relu_pool, 256, (3, 3), (1, 1), act=None, padding='SAME', W_init=w_init, name='conv4')
        conv4_bn = BatchNormLayer(conv4, act=tf.identity, is_train=is_train, gamma_init=g_init, name='conv4_bn')
        conv4_bn_relu = PReluLayer(conv4_bn, name='conv4_bn_relu')
    
    ################################Deconvolution (up-sample + Conv)#########################
        
        deconv1_upsample = tf.image.resize_images(conv4_bn_relu, size=[64, 64], method=1)'

**Comment by ymodak** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by Dee-Ma** [comment]
Hi ymodak,


Thanks for your help. The problem has been solved and I have closed the issue.


________________________________

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
