### ISSUE TITLE
How Java calls the estimator model?

### ISSUE THREAD

**Issue by mrchor** [tensorflow/tensorflow#25271]
Hello, I would like to ask how Java calls the estimator model. Is there any sample code to see?

**Comment by jvishnuvardhan** [comment]
@mrchor Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. Github is mainly for addressing bugs in installation and performance. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing the issue as it is not related to Bug/Performance or Build/Installation. Thanks!
