### ISSUE TITLE
build tensorflow-r1.13 fails

### ISSUE THREAD

**Issue by guoguo11191** [tensorflow/tensorflow#25277]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Red Hat 4.8.2-16
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source 
- TensorFlow version:r1.13
- Python version:python2.7
- Installed using virtualenv? pip? conda?:bazel
- Bazel version (if compiling from source):0.22.0, 0.19.1, 0.18.0
- GCC/Compiler version (if compiling from source):4.8.2
- CUDA/cuDNN version:
- GPU model and memory:CPU

**Describe the problem**
cannot fetch @bazel_toolchains when building tensorflow-r1.13

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 8c0b66e8-db86-4ac7-a5db-052c331926db
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@bazel_toolchains//repositories': java.io.IOException: thread interrupted
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@bazel_toolchains//repositories': java.io.IOException: thread interrupted
INFO: Elapsed time: 142.844s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @bazel_toolchains; fetching 140s

**Comment by guoguo11191** [comment]
my fault，http proxy error

**Comment by hzx829** [comment]
How do you solve proxy error?(From Tencent...)
