### ISSUE TITLE
TensorFlow build for raspberry pi, Python 3.6

### ISSUE THREAD

**Issue by jytug** [tensorflow/tensorflow#25296]
Hello,

**System information**
- TensorFlow version (you are using): HEAD
- Are you willing to contribute it? Yes

**Describe the feature and the current behavior/state.**
Currently, [this page](https://www.tensorflow.org/install/source_rpi) provides instructions on how to build a TF pip package for raspberry pi. However, it limits Python 3 versions to `3.4`, which is not officially supported by some popular packages (including `pandas`), which makes using `2.7` the only reasonable solution.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Raspberry Pi developers

**Comment by freedomtan** [comment]
FYR. I didn't try Python 3.6, but I guess it works. I use the following to build tensorflow pip wheel with clang on RPI 3 B+.
```
CC=clang CXX=clang+= bazel build --config opt \
--config=noaws --config=nogcp --config=nohdfs --config=noignite --config=nokafka \
--local_resources 2048.0,1,1 \
--copt=-march=armv7-a --copt=-mfpu=neon-vfpv4 \
--copt=-ftree-vectorize --copt=-funsafe-math-optimizations \
--copt=-fomit-frame-pointer --copt=-DRASPBERRY_PI --cxxopt=-Wno-c++11-narrowing \
--host_copt=-DRASPBERRY_PI --host_copt=-Wno-c++11-narrowing \
--host_copt=-march=armv7-a --host_copt=-mfpu=neon-vfpv4 \
--host_copt=-fomit-frame-pointer \
//tensorflow/tools/pip_package:build_pip_package --linkopt=-Wl,--no-keep-memory
```

**Comment by bennuttall** [comment]
The Python 3.5 wheel is simply the 3.4 wheel renamed. Have you tried downloading the wheel and renaming it?

```bash
wget https://www.piwheels.org/simple/tensorflow/tensorflow-1.11.0-cp35-none-linux_armv7l.whl
mv tensorflow-1.11.0-cp35-none-linux_armv7l.whl tensorflow-1.11.0-cp36-none-linux_armv7l.whl
sudo pip3 install tensorflow-1.11.0-cp36-none-linux_armv7l.whl
```

I have a feeling this will work. If you can confirm, I'll add these copies to the piwheels index.

**Comment by paulaksm** [comment]
> The Python 3.5 wheel is simply the 3.4 wheel renamed. Have you tried downloading the wheel and renaming it?
> 
> ```shell
> wget https://www.piwheels.org/simple/tensorflow/tensorflow-1.11.0-cp35-none-linux_armv7l.whl
> mv tensorflow-1.11.0-cp35-none-linux_armv7l.whl tensorflow-1.11.0-cp36-none-linux_armv7l.whl
> sudo pip3 install tensorflow-1.11.0-cp36-none-linux_armv7l.whl
> ```
> 
> I have a feeling this will work. If you can confirm, I'll add these copies to the piwheels index.

It works! 
As expected, it outputs a runtime warning regarding a mismatch between compiletime version (3.4) and runtime version (3.6). This warning also appears when running Python 3.5 version.

`python -c "import tensorflow as tf"`

> /home/pi/.virtualenvs/keras/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
return f(*args, **kwds)
/home/pi/.virtualenvs/keras/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
return f(*args, **kwds)

**Comment by petewarden** [comment]
That's good to know, thanks for the investigation! I'll close this one for now, and aim to create official 3.6 binaries using this approach soon.

**Comment by bennuttall** [comment]
Tensorflow 1.12.0 is now available from piwheels.org for Python 2.7, 3.4, 3.5, 3.6 and 3.7 for Arm v6 and v7.

**Comment by freegroup** [comment]
Installing tensorflow 1.12.0 didn't work for me. I have always the runtime error (see issue https://github.com/tensorflow/tensorflow/issues/23840) 

```sh
python3 --version
3.5.3

pip3 install tensorflow==1.12.0

python3 -c "import tensorflow as tf"
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)


cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

``` 

in the end I need a working openCV, tensorflow, python3 enviroment....but I'm unable to get this up and running.

I wonder why there is no OS image available for download for this purpose. This combination is used so often but I could only find Rasberry images for media centers, schools or gaming. For OpenCV/Tensorflow on a normal Raspberry I was not successful....yes there is Coral....but a special camera is required - not the official Rasberry Camera v2 is supported.

**Comment by bennuttall** [comment]
> Installing tensorflow 1.12.0 didn't work for me. I have always the runtime error

It's not a runtime error. It's a RuntimeWarning. Tensorflow still works.
