### ISSUE TITLE
Dictionary as model targets for subclassed Keras models

### ISSUE THREAD

**Issue by shoyer** [tensorflow/tensorflow#25299]
It is currently possible to build subclassed Keras models with a dict of tensors as inputs, but not as outputs, e.g.,
```python
import tensorflow as tf

tf.enable_eager_execution()

class MyModel(tf.keras.Model):
  def call(self, inputs):
    return inputs
  
model = MyModel()
model.compile(tf.keras.optimizers.Adam(), 'mean_squared_error')
inputs = labels = {'a': tf.range(5.0)}
model.fit(x=inputs, y=labels)
```
This results in the error:
```python-stacktrace
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-21d4cae99b87> in <module>()
     10 model.compile(tf.keras.optimizers.Adam(), 'mean_squared_error')
     11 inputs = labels = {'a': tf.range(5.0)}
---> 12 model.fit(x=inputs, y=labels)

/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    900         steps=steps_per_epoch,
    901         validation_split=validation_split,
--> 902         shuffle=shuffle)
    903 
    904     # Prepare validation data.

/tensorflow/python/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, check_steps, steps_name, steps, validation_split, shuffle, extract_tensors_from_dataset)
   2458           all_inputs += list(y_input)
   2459         elif isinstance(y_input, dict):
-> 2460           raise ValueError('You cannot pass a dictionary as model targets.')
   2461         else:
   2462           if (not isinstance(y_input, np.ndarray) and

ValueError: You cannot pass a dictionary as model targets.
```

I'd like to build Keras models that receive and output tensors as dictionaries -- would it be reasonable to add support for this? It currently works to specify inputs as a dict, but not labels for training moels.

**System information**
- TensorFlow version (you are using): development version
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**
No, this currently results in an error.

**Who will benefit with this feature?**
Users building complex models that want to keep track of multiple tensors by name instead of by position.

**Any Other info.**

**Comment by jvishnuvardhan** [comment]
Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. Thanks!

**Comment by hadim** [comment]
I confirm the same behavior on the latest TF 2.0 nightly. `tf.keras.Model` can use dict as inputs (training with `model.fit()`) but does not accept dict as outputs.

When using `tf.keras.Sequential`, both inputs and outputs can be dict (you need to set the name of the layers according to the keys in your inputs/outputs).

**Comment by karmel** [comment]
The current paradigm requires that model outputs are array-like. Why do you need to output dicts? Would [multiple outputs](https://keras.io/getting-started/functional-api-guide/#multi-input-and-multi-output-models) work for your use-case instead?

**Comment by shoyer** [comment]
It is perhaps worth noting that it is already supported to pass multiple outputs into a subclassed model as a list:
```python
import tensorflow as tf

tf.enable_eager_execution()

class MyModel(tf.keras.Model):
  def call(self, inputs):
    return [inputs['a'], 2 * inputs['b']]
  
model = MyModel()
model.compile(tf.train.AdamOptimizer(), 'mean_squared_error')
inputs = {'a': tf.range(5.0), 'b': tf.range(5.0, 10.0)}
labels = [tf.range(5, 10), tf.range(5, 10)]
model.fit(x=inputs, y=labels)
```
Outputs:
```
WARNING:tensorflow:The list of trainable weights is empty. Make sure that you are not setting model.trainable to False before compiling the model.
5/5 [==============================] - 0s 1ms/sample - loss: 76.0000 - output_1_loss: 25.0000 - output_2_loss: 51.0000
```

Here, e.g., these lines in `keras/engine/training.py`:
https://github.com/tensorflow/tensorflow/blob/38264f1bf2b69e241323b575738091f701b883e1/tensorflow/python/keras/engine/training.py#L2432-L2440

"Multiple outputs" by name appear to currently only be supported with the functional API. In principle, I could use the functional API for this, insofar as any subclassing model could be written functionally. But I much prefer writing a subclass: my model has complex domain specific logic, and I vastly prefer being between able to debug it in eager mode.

**Comment by jnd77** [comment]
My use case for a dict is to manage a configurable model, where the outputs are not always the same.
It is possible to do it via a list, but it is quite cumbersome to know what's the output order depending on the configuration. I also find the code much more readable inside the model:

```
   def call(self, inputs):
       image = inputs[Inputs.IMAGE]
       bounding_box = inputs[Inputs.BOUNDING_BOX]
       ...
       outputs = {Outputs.CLASS_LOGITS: class_logits} 
       if self.mask:
            outputs[Outputs.OBJECT_MASK]=  masks
       return outputs
```

**Comment by applenob** [comment]
> The current paradigm requires that model outputs are array-like. Why do you need to output dicts? Would [multiple outputs](https://keras.io/getting-started/functional-api-guide/#multi-input-and-multi-output-models) work for your use-case instead?

When we need to apply the loss to a specific output and target, we can send a dict to `loss` .
```python
loss = {"MyOutput1": "MyLoss"}
targets = {"MyOutput1": y1, "MyOutput2": y2}
outputs = {"MyOutput1": out1, "MyOutput2": out2}
```

Now, we have to send loss by keras default output name:

```python
loss = {"output_1": "MyLoss"}
targets = y1
outputs = [out1, out2]
```

**Comment by hadim** [comment]
In my case, it's more a general question than for a specific use-case.

I thought it was natural to have the same API for inputs/outputs for both `tf.keras.Sequential` and `tf.keras.Model`. And also the same API between inputs and outputs. What is the reason why dict could be used for inputs and not for outputs?

**Comment by hadim** [comment]
In the same spirit, it should be possible to specify inputs shape from  dict of shapes using `tf.function` or `model._set_inputs()`.

Consider the following code:

```python
import tempfile

import numpy as np
import tensorflow as tf

class MyModel(tf.keras.Model):

    def __init__(self):
        super().__init__()
        self.layer = tf.keras.layers.Dense(64)

    @tf.function(input_signature=[tf.TensorSpec((None, 128, 128), tf.float32)])
    def call(self, inputs):
        return self.layer(inputs)

model = MyModel()

batch_size = 16
inputs = np.random.random((batch_size, 128, 128)).astype('float32')
outputs = model(inputs)

print(inputs.shape, outputs.shape)

model_path = tempfile.mkdtemp()
tf.saved_model.save(model, model_path)
```

Saving the model will fail without `tf.function` because the model has not been fitted. Since such a model can be trained with a dict as inputs:

```python
inputs = dict(input1=np.random.random(28, 28), input2=(16, 16, 3))
model.fit(inputs)
```

Then we should be able to do the following that currently fails:

```python
import numpy as np
import tensorflow as tf

class MyModel(tf.keras.Model):

    def __init__(self):
        super().__init__()
        self.layer = tf.keras.layers.Dense(64)

    @tf.function(input_signature=dict(input1=tf.TensorSpec((None, 128, 128), tf.float32),
                                      input2=tf.TensorSpec((None, 28, 28), tf.float32)))
    def call(self, inputs):
        return self.layer(inputs)

model = MyModel()

batch_size = 16
inputs = np.random.random((batch_size, 128, 128)).astype('float32')
outputs = model(inputs)
```

(again the above will also fail if using `model._set_inputs()` instead of `tf.function`)

Let me know if I should open a new issue about it.

**Comment by cottrell** [comment]
I've noticed this too. Basically the functional API model(inputs=..., outputs=...) appears to work with outputs=dict but subclass API, while it *runs*, returns a list. 

It would be good to either kill the dict input/output feature across all model APIs or enable it. There should be one true way of doing things across the API. It would be interesting to understand why if this is tricky or not possible for some reason.

**Comment by jinfagang** [comment]
this not work on tensorflow 2.0:

```python
 dataset, _ = tfds.load('tf_flowers', with_info=True)
    train_dataset = dataset['train']
    train_dataset = train_dataset.shuffle(100).map(preprocess).batch(12).repeat()
    print(train_dataset)

    # init model
    model = build_model()
    logging.info('model loaded.')

    if use_keras_fit:
        # train_images = train_dataset['image']
        # train_labels = train_dataset['label']
        model.compile(
            optimizer='adam',
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy'])
        model.fit(train_dataset.take(1), epochs=50)
```

**Comment by hadim** [comment]
@karmel any chance to see that feature implemented? Nested data (dict) are supported in a lot of places (model's input and `tf.data.Dataset` for example, it would be really nice to see it supported in model's outputs.

It's semantically stronger than a simple list where you need to "remember" what each position is.

**Comment by ghannum** [comment]
Is there any progress on this? I have models with lots of outputs, which were no problem in TF1.X but are now a big hassle. Not having labels for the outputs affects more than how the data is fed. As an example, the loss names now need to be rather cryptic 'output_x'. The metric callbacks are now filled with 'output_1: accuracy', 'output_2: accuracy', etc, making them rather useless for visual inspection. Tensorboard is similarly difficult to work with.

**Comment by cottrell** [comment]
@ghannum I think this now works. Always use the subclass API at the moment to begin with and I think it will save hassle. And just write a custom train loop as it will be more explicit when things fail.

import tensorflow as tf

```
class Model(tf.keras.models.Model):
    def __init__(self):
        super().__init__()

    @tf.function
    def call(self, inputs):
        return dict(a=tf.convert_to_tensor(1), b=tf.convert_to_tensor(2))

```

**Comment by ghannum** [comment]
Thanks for the feedback. I've tried the subclass approach as you've shown, but the fit_generator is very explicit about not taking dicts. 'ValueError: You cannot pass a dictionary as model target.'

I am considering writing a custom loop, but the fit_generator encompasses a ton of useful code, including handling of metrics, callbacks, validation, progress bars, workers, etc. That's a lot of work and things that can wrong to fix a simple oversight of the API. It's a shame, since dicts are supported in 1.X, but have been dropped for some reason in 2.X (only for fit_generator). Named outputs are an important part of developing complex / multi-task models. Hopefully they get support again in the near future.

**Comment by ghannum** [comment]
Thanks for the advice. I actually managed to find a solution by not using the subclass approach. Returning a dict seems to be supported for functional models.

**Comment by tgsmith61591** [comment]
This is something my company would really like to see implemented as well. We've implemented a number of custom model architectures via the subclass API, and due to the nature of the problems we're solving, a dictionary of labels is necessary (the multiple targets are different ranks, and our custom loss layers know how to handle different targets). Is there any plan for this to be implemented in future versions?

**Comment by r-wheeler** [comment]
Bump. This issue makes training on multiple objectives / multiple loss functions rather difficult when y is multiple targets managed by python dictionaries.

**Comment by wuhy08** [comment]
It seems it is supported now. I tried the following code without any error:


```
import tensorflow as tf

class DictModel(tf.keras.models.Model):

    def __init__(self, **kwargs):
        super(DictModel, self).__init__(**kwargs)

    def call(self, inputs, training=None, mask=None):
        out1 = tf.add(inputs, tf.convert_to_tensor(1.))
        out2 = tf.add(inputs, tf.convert_to_tensor(2.))
        return {"output_1": out1, "output_2": out2}

def main():
    model = DictModel()

    model.compile(tf.keras.optimizers.Adam(),
                  loss={"output_1": tf.keras.losses.MeanSquaredError(),
                        "output_2": tf.keras.losses.MeanSquaredError()})

    inputs = tf.range(5.0)
    labels = {'output_1': tf.range(5.0), 'output_2': tf.range(5.0)}

    model.fit(x=inputs, y=labels)

if __name__ == '__main__':
    main()
```

**Comment by ymodak** [comment]
Dictionary mapping is supported now with `model.fit`. Thanks!
https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit

**Comment by jttaufa** [comment]
Are there any plans to make dict inputs supported for `model.predict`?
