### ISSUE TITLE
Data augmentation on 4-D or 5-D data

### ISSUE THREAD

**Issue by pldelisle** [tensorflow/tensorflow#25295]
Hi, 

I would like to request a new feature.

**System information**
- TensorFlow version (you are using): 1.12, compiled with CUDA 10, NCCL, CuDNN7.
- Are you willing to contribute it (Yes/No): Maybe, but as a student, time is a real constraint.

**Describe the feature and the current behavior/state.**
I would like to have data augmentation functions that accept 4-D arrays with shape [width, height, depth, channels] or 5-D Tensor of shape [batch, width, height, depth, channels]. Current supported format is only 4-D [batch, height, width, channels] or 3-D Tensor of shape [height, width, channels]. 
Having functions like random rotation, random shear, and/or random flip for this data shape would be useful.

**Will this change the current api? How?** 
No.

**Who will benefit with this feature?** 
Any people that works like me in medical imaging and have to deal with 3D data.

**Comment by mrry** [comment]
We'd welcome contributions for this feature!

**Comment by musikisomorphie** [comment]
Hi @mrry, I would like to contribute to this feature. Will it be okay for you?

**Comment by mrry** [comment]
Sure, thanks for contributing!

**Comment by musikisomorphie** [comment]
> Sure, thanks for contributing!

Great, I will let you know if I make some progress.

**Comment by musikisomorphie** [comment]
Hi @pldelisle, I found out that there are three modules of tensorflow related to data/image augmentation, that is, 

> keras-preprocessing/keras_preprocessing/image/image_data_generator.py
> tensorflow/tensorflow/python/ops/image_ops_impl.py
> tensorflow/tensorflow/contrib/image/python/ops/image_ops.py

Only keras' can directly achieve random shear op, which is basically numpy implementation. Is the keras' function the one you want us to update? Or you can show me your data processing pipeline
, so I know which function I should work on.

**Comment by musikisomorphie** [comment]
@mrry,  could you help me pin down the function that I need to work on? As I said to @pldelisle,  
there are three possible modules of tensorflow related to data/image augmentation, 

> keras-preprocessing/keras_preprocessing/image/image_data_generator.py
> tensorflow/tensorflow/python/ops/image_ops_impl.py
> tensorflow/tensorflow/contrib/image/python/ops/image_ops.py

which one should I extend to high rank data?

**Comment by pldelisle** [comment]
Hi all. Sorry I was out for the weekend.

My data processing pipeline is, at the moment, in the following DataProvider class:

```
class DataProvider(object):

    def __init__(self, path, subset, config):
        """
        Data provider for multimodal MRI.
        :param tfrecord_path: path to the TFRecords
        :param subset: the subset (train, validation, test) the data set will be instantiate with.
        :param config: A JSON configuration file for hyper parameters.
        """

        self._path = path
        self._subset = subset
        self._subject_batch_size = config.get("subject_batch_size", 1)
        self._shuffle = config.get("shuffle", True)
        self._use_fp16 = config.get("use_fp16", False)
        self._patch_shape = config.get("volume")["patch_size"]
        self._width = config.get("width", 240)
        self._height = config.get("height", 240)
        self._depth = config.get("depth", 155)
        self._n_channels = config.get("n_channels", 1)
        self._batch_size = config.get("batch_size", 32)
        self._n_modalities = config.get("n_modalities", 4)
        self._use_weight_map = config.get("use_weight_map", True)

        if self._use_weight_map:
            self._n_total_modalities = self._n_modalities + 2
        else:
            self._n_total_modalities = self._n_modalities + 1

        # Declare a Sampler object here if required.

    def _get_filename(self):
        """
        Returns the file name associated to the data set's subset.
        :return: A string containing the complete path and file name.
        """
        return os.path.join(self._path, self._subset + ".tfrecords")

    def _training_parser(self, serialized_example):
        """
        Parses a single tf.Example which contains multiple modalities and label tensors.
        :param serialized_example: A TFRecord serialized example.
        :return: A tuple containing all parsed image modalities, segmentation and weight_map with slice dimensions.
        """

        # input format.
        features = tf.parse_single_example(
            serialized_example,
            features={
                "flair": tf.FixedLenFeature(self._width * self._height * self._depth * self._n_channels,
                                            tf.int64),
                "t1": tf.FixedLenFeature(self._width * self._height * self._depth * self._n_channels,
                                         tf.int64),
                "t1ce": tf.FixedLenFeature(self._width * self._height * self._depth * self._n_channels,
                                           tf.int64),
                "t2": tf.FixedLenFeature(self._width * self._height * self._depth * self._n_channels,
                                         tf.int64),
                "segmentation": tf.FixedLenFeature(self._width * self._height * self._depth * self._n_channels,
                                                   tf.int64),
                "weight_map": tf.FixedLenFeature(self._width * self._height * self._depth * self._n_channels,
                                                 tf.float32),
                "original_shape": tf.FixedLenFeature(4,
                                                     tf.int64),
                "slices": tf.FixedLenFeature(9,
                                             tf.int64),

            })

        flair = features["flair"]
        t1 = features["t1"]
        t1ce = features["t1ce"]
        t2 = features["t2"]
        segmentation = features["segmentation"]
        weight_map = features["weight_map"]
        original_shape = features["original_shape"]
        slices = features["slices"]

        # Reshape from [depth * height * width] to [depth, height, width, channel] using serialized image shape.
        flair = tf.reshape(flair, original_shape)
        t1 = tf.reshape(t1, original_shape)
        t1ce = tf.reshape(t1ce, original_shape)
        t2 = tf.reshape(t2, original_shape)
        segmentation = tf.reshape(segmentation, original_shape)
        weight_map = tf.reshape(weight_map, original_shape)

        if self._use_fp16:
            flair = tf.cast(flair, dtype=tf.float16)
            t1 = tf.cast(t1, dtype=tf.float16)
            t1ce = tf.cast(t1ce, dtype=tf.float16)
            t2 = tf.cast(t2, dtype=tf.float16)
            segmentation = tf.cast(segmentation, dtype=tf.float16)
            weight_map = tf.cast(weight_map, dtype=tf.float16)

        else:
            flair = tf.cast(flair, dtype=tf.float32)
            t1 = tf.cast(t1, dtype=tf.float32)
            t1ce = tf.cast(t1ce, dtype=tf.float32)
            t2 = tf.cast(t2, dtype=tf.float32)
            segmentation = tf.cast(segmentation, dtype=tf.float32)
            weight_map = tf.cast(weight_map, dtype=tf.float32)

        return flair, t1, t1ce, t2, segmentation, weight_map, slices

    def _crop_image(self, flair, t1, t1ce, t2, segmentation, weight_map, slices):
        """
        Crop modalities.
        :param flair: FLAIR modality of an image.
        :param t1: T1 modality of an image.
        :param t1ce: T1ce modality of an image.
        :param t2: T2 modality of an image.
        :param segmentation: Labels of an image.
        :param weight_map: Associated weight map of an image.
        :return: Randomly cropped 3D patches from image's set.
        """

        stack = tf.stack([flair, t1, t1ce, t2, segmentation, weight_map], axis=-1)

        stack = stack[slices[0]:slices[2]:slices[1], slices[3]:slices[5]:slices[4], slices[6]:slices[8]:slices[7], :, :]

        # Randomly crop a [self._patch_size, self._patch_size, self._patch_size, 1] section of the image using
        # TensorFlow built-in function.
        image = tf.random_crop(stack, [self._patch_shape, self._patch_shape, self._patch_shape, self._n_channels,
                                       self._n_total_modalities])

        [flair, t1, t1ce, t2, segmentation, weight_map] = tf.unstack(image, self._n_total_modalities, axis=-1)

        return flair, t1, t1ce, t2, segmentation, weight_map

    def _filter(self, flair, t1, t1ce, t2, segmentation, weight_map):

        stack = tf.stack([flair, t1, t1ce, t2, segmentation, weight_map], axis=-1)

        valid_idx = tf.where(tf.math.reduce_sum(stack, axis=(0, 1, 2, 3)) > 0)

        stack = tf.boolean_mask(stack, valid_idx, axis=-1)

        [flair, t1, t1ce, t2, segmentation, weight_map] = tf.unstack(stack, self._n_total_modalities, axis=-1)

        return flair, t1, t1ce, t2, segmentation, weight_map


    def input(self):
        """
        Return a TensorFlow data set object containing inputs.
        :return: dataset: TensorFlow data set object.
        """

        # Get file names for this data set.
        filename = self._get_filename()

        with tf.name_scope("inputs"):
            # Instantiate a new data set based on a provided TFRecord file name. Generate a Dataset with raw records.
            dataset = tf.data.TFRecordDataset(filename)

            # Parse records. Returns 1 volume with all its modalities.
            dataset = dataset.map(map_func=self._training_parser,
                                  num_parallel_calls=1)

            # Prefetch 10 subject. Adjust with available system RAM.
            dataset = dataset.prefetch(10)

            if self._subset == "train" or "validation":
                min_queue_examples = int(
                    DataProvider.num_examples_per_epoch(self._subset) * 0.10)

                # Ensure that the capacity is sufficiently large to provide good random
                # shuffling.
                dataset = dataset.shuffle(buffer_size=min_queue_examples + 2 * self._batch_size)

                # Repeat indefinitely.
                dataset = dataset.repeat()

                # Returns randomly cropped images.
                dataset = dataset.map(self._crop_image, num_parallel_calls=self._batch_size)

                # Filter inputs for only non-zero patches.
                dataset = dataset.filter(self._filter)

            # Batch 3D patches. Here, we want (training batch / number of modalities) samples per modality,
            # which is usually 32 / 4 = 8 patches per modality.
            dataset = dataset.batch(int(self._batch_size / self._n_modalities))

            # Prepare for next iterations.
            dataset = dataset.prefetch(10 * self._batch_size)

            return dataset

    @staticmethod
    def num_examples_per_epoch(subset):
        if subset == "train":
            # Return the number of volumes in training dataset.
            return int(230)
        if subset == "validation":
            # Return the number of volumes in validation dataset.
            return int(29)
        if subset == "test":
            # Return the number of volumes in test dataset.
            return int(26)
```

I would like to add data augmentation in it. I already do random crop of it after slicing the image to only non-zero voxels (these are brain MRI scans which has multiple modalities). 

Since Contrib is going to be removed with Tensorflow 2.0 (if I remember well), I think the `tensorflow/tensorflow/python/ops/image_ops_impl.py` or `keras-preprocessing/keras_preprocessing/image/image_data_generator.py` would be preferable.

**Comment by musikisomorphie** [comment]
> Hi all. Sorry I was out for the weekend.
> 
> My data processing pipeline is, at the moment, in the following DataProvider class:
> 
> ```
> class DataProvider(object):
> 
>     def __init__(self, path, subset, config):
>         """
>         Data provider for multimodal MRI.
>         :param tfrecord_path: path to the TFRecords
>         :param subset: the subset (train, validation, test) the data set will be instantiate with.
>         :param config: A JSON configuration file for hyper parameters.
>         """
> 
>         self._path = path
>         self._subset = subset
>         self._subject_batch_size = config.get("subject_batch_size", 1)
>         self._shuffle = config.get("shuffle", True)
>         self._use_fp16 = config.get("use_fp16", False)
>         self._patch_shape = config.get("volume")["patch_size"]
>         self._width = config.get("width", 240)
>         self._height = config.get("height", 240)
>         self._depth = config.get("depth", 155)
>         self._n_channels = config.get("n_channels", 1)
>         self._batch_size = config.get("batch_size", 32)
>         self._n_modalities = config.get("n_modalities", 4)
>         self._use_weight_map = config.get("use_weight_map", True)
> 
>         if self._use_weight_map:
>             self._n_total_modalities = self._n_modalities + 2
>         else:
>             self._n_total_modalities = self._n_modalities + 1
> 
>         # Declare a Sampler object here if required.
> 
>     def _get_filename(self):
>         """
>         Returns the file name associated to the data set's subset.
>         :return: A string containing the complete path and file name.
>         """
>         return os.path.join(self._path, self._subset + ".tfrecords")
> 
>     def _training_parser(self, serialized_example):
>         """
>         Parses a single tf.Example which contains multiple modalities and label tensors.
>         :param serialized_example: A TFRecord serialized example.
>         :return: A tuple containing all parsed image modalities, segmentation and weight_map with slice dimensions.
>         """
> 
>         # input format.
>         features = tf.parse_single_example(
>             serialized_example,
>             features={
>                 "flair": tf.FixedLenFeature(self._width * self._height * self._depth * self._n_channels,
>                                             tf.int64),
>                 "t1": tf.FixedLenFeature(self._width * self._height * self._depth * self._n_channels,
>                                          tf.int64),
>                 "t1ce": tf.FixedLenFeature(self._width * self._height * self._depth * self._n_channels,
>                                            tf.int64),
>                 "t2": tf.FixedLenFeature(self._width * self._height * self._depth * self._n_channels,
>                                          tf.int64),
>                 "segmentation": tf.FixedLenFeature(self._width * self._height * self._depth * self._n_channels,
>                                                    tf.int64),
>                 "weight_map": tf.FixedLenFeature(self._width * self._height * self._depth * self._n_channels,
>                                                  tf.float32),
>                 "original_shape": tf.FixedLenFeature(4,
>                                                      tf.int64),
>                 "slices": tf.FixedLenFeature(9,
>                                              tf.int64),
> 
>             })
> 
>         flair = features["flair"]
>         t1 = features["t1"]
>         t1ce = features["t1ce"]
>         t2 = features["t2"]
>         segmentation = features["segmentation"]
>         weight_map = features["weight_map"]
>         original_shape = features["original_shape"]
>         slices = features["slices"]
> 
>         # Reshape from [depth * height * width] to [depth, height, width, channel] using serialized image shape.
>         flair = tf.reshape(flair, original_shape)
>         t1 = tf.reshape(t1, original_shape)
>         t1ce = tf.reshape(t1ce, original_shape)
>         t2 = tf.reshape(t2, original_shape)
>         segmentation = tf.reshape(segmentation, original_shape)
>         weight_map = tf.reshape(weight_map, original_shape)
> 
>         if self._use_fp16:
>             flair = tf.cast(flair, dtype=tf.float16)
>             t1 = tf.cast(t1, dtype=tf.float16)
>             t1ce = tf.cast(t1ce, dtype=tf.float16)
>             t2 = tf.cast(t2, dtype=tf.float16)
>             segmentation = tf.cast(segmentation, dtype=tf.float16)  # Cast to FP16 because ongoing operations do not support mixed types (tf.Stack in random_crop).
>             weight_map = tf.cast(weight_map, dtype=tf.float16)
> 
>         else:
>             flair = tf.cast(flair, dtype=tf.float32)
>             t1 = tf.cast(t1, dtype=tf.float32)
>             t1ce = tf.cast(t1ce, dtype=tf.float32)
>             t2 = tf.cast(t2, dtype=tf.float32)
>             segmentation = tf.cast(segmentation, dtype=tf.float32)  # Cast to FP32 because ongoing operations do not support mixed types (tf.Stack in random_crop).
>             weight_map = tf.cast(weight_map, dtype=tf.float32)
> 
>         return flair, t1, t1ce, t2, segmentation, weight_map, slices
> 
>     def _crop_image(self, flair, t1, t1ce, t2, segmentation, weight_map, slices):
>         """
>         Crop modalities.
>         :param flair: FLAIR modality of an image.
>         :param t1: T1 modality of an image.
>         :param t1ce: T1ce modality of an image.
>         :param t2: T2 modality of an image.
>         :param segmentation: Labels of an image.
>         :param weight_map: Associated weight map of an image.
>         :return: Randomly cropped 3D patches from image's set.
>         """
> 
>         stack = tf.stack([flair, t1, t1ce, t2, segmentation, weight_map], axis=-1)
> 
>         stack = stack[slices[0]:slices[2]:slices[1], slices[3]:slices[5]:slices[4], slices[6]:slices[8]:slices[7], :, :]
> 
>         # Randomly crop a [self._patch_size, self._patch_size, self._patch_size, 1] section of the image using
>         # TensorFlow built-in function.
>         image = tf.random_crop(stack, [self._patch_shape, self._patch_shape, self._patch_shape, self._n_channels,
>                                        self._n_total_modalities])
> 
>         [flair, t1, t1ce, t2, segmentation, weight_map] = tf.unstack(image, self._n_total_modalities, axis=-1)
> 
>         return flair, t1, t1ce, t2, segmentation, weight_map
> 
>     def _filter(self, flair, t1, t1ce, t2, segmentation, weight_map):
> 
>         stack = tf.stack([flair, t1, t1ce, t2, segmentation, weight_map], axis=-1)
> 
>         valid_idx = tf.where(tf.math.reduce_sum(stack, axis=(0, 1, 2, 3)) > 0)
> 
>         stack = tf.boolean_mask(stack, valid_idx, axis=-1)
> 
>         [flair, t1, t1ce, t2, segmentation, weight_map] = tf.unstack(stack, self._n_total_modalities, axis=-1)
> 
>         return flair, t1, t1ce, t2, segmentation, weight_map
> 
> 
>     def input(self):
>         """
>         Return a TensorFlow data set object containing inputs.
>         :return: dataset: TensorFlow data set object.
>         """
> 
>         # Get file names for this data set.
>         filename = self._get_filename()
> 
>         with tf.name_scope("inputs"):
>             # Instantiate a new data set based on a provided TFRecord file name. Generate a Dataset with raw records.
>             dataset = tf.data.TFRecordDataset(filename)
> 
>             # Parse records. Returns 1 volume with all its modalities.
>             dataset = dataset.map(map_func=self._training_parser,
>                                   num_parallel_calls=1)
> 
>             # Prefetch 10 subject. Adjust with available system RAM.
>             dataset = dataset.prefetch(10)
> 
>             if self._subset == "train" or "validation":
>                 min_queue_examples = int(
>                     DataProvider.num_examples_per_epoch(self._subset) * 0.10)
> 
>                 # Ensure that the capacity is sufficiently large to provide good random
>                 # shuffling.
>                 dataset = dataset.shuffle(buffer_size=min_queue_examples + 2 * self._batch_size)
> 
>                 # Repeat indefinitely.
>                 dataset = dataset.repeat()
> 
>                 # Returns randomly cropped images.
>                 dataset = dataset.map(self._crop_image, num_parallel_calls=self._batch_size)
> 
>                 # Filter inputs for only non-zero patches.
>                 dataset = dataset.filter(self._filter)
> 
>             # Batch 3D patches. Here, we want (training batch / number of modalities) samples per modality,
>             # which is usually 32 / 4 = 8 patches per modality.
>             dataset = dataset.batch(int(self._batch_size / self._n_modalities))
> 
>             # Prepare for next iterations.
>             dataset = dataset.prefetch(10 * self._batch_size)
> 
>             return dataset
> 
>     @staticmethod
>     def num_examples_per_epoch(subset):
>         if subset == "train":
>             # Return the number of volumes in training dataset.
>             return int(230)
>         if subset == "validation":
>             # Return the number of volumes in validation dataset.
>             return int(29)
>         if subset == "test":
>             # Return the number of volumes in test dataset.
>             return int(26)
> ```
> I would like to add data augmentation in it. I already do random crop of it after slicing the image to only non-zero voxels (these are brain MRI scans which has multiple modalities). Having random rotation or random flip would be great. Shearing in medical image doesn't necessary add value to the pipeline, so it wouldn't be a priority.
> 
> Since Contrib is going to be removed with Tensorflow 2.0 (if I remember well), I think the `tensorflow/tensorflow/python/ops/image_ops_impl.py` or `keras-preprocessing/keras_preprocessing/image/image_data_generator.py` would be preferable.

Ok, @pldelisle, once I make some progress I will let you know.

**Comment by musikisomorphie** [comment]
@a6802739, I already opened a PR for this issue. But you can leave some comments to my PR if you like.

**Comment by a6802739** [comment]
@musikisomorphie Could you please give me the link for your PR?

**Comment by musikisomorphie** [comment]
@a6802739, https://github.com/tensorflow/tensorflow/pull/26269

**Comment by gadagashwini** [comment]
@pldelisle,
You can use `tf.keras.preprocessing.image.ImageDataGenerator()` to accomplish data Augmentation.

```
import tensorflow as tf
import numpy as np

#input and output
x_train = np.random.normal(size=(128,128,128,3))
 
datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    featurewise_center=True,
    featurewise_std_normalization=True,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    validation_split=0.2)
datagen.fit(x_train)
```

**Comment by mohantym** [comment]
Hi @pldelisle !

Inline with the above [comment](https://github.com/tensorflow/tensorflow/issues/25295#issuecomment-1059047223) , Just wanted to clear that you can reshape the 5D to 4D data (N,C,H,W) format , do the augmentation like above and reshape it back to 5D data. 

Attached relevant [thread ](https://stackoverflow.com/questions/66907861/how-do-you-augment-4-dimensional-images/66911301#66911301)for reference.

Thank you!
