### ISSUE TITLE
Need help, how to choose one column of a tensor

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#253]
predict_op = tf.argmax(py_x, 1) # at predict time, evaluate the argmax of the logistic regression

here what to do if I want to choose one column of py_x, like py_x[1] ?

Also it would be of great help if we have example of showing how to do text classification using tensorflow( sparse feature). 

Example of showing how to evaluate using auc instead of  precision is greatly appreciated.

**Comment by vrv** [comment]
I think tf.slice(...) might be what you want for getting 1 column.  Let us know if that doesn't work!

You might also want to follow https://github.com/tensorflow/tensorflow/issues/206 

As for text classification: I'm sure that will be added over time (either by us or externally).
