### ISSUE TITLE
How can I pass a parameter for ever examples in a tensor?

### ISSUE THREAD

**Issue by poppintiger** [tensorflow/tensorflow#25303]
I have a many sequence sentence with different length，and I padded all sentence with same length 100 ，I  got a input tensor with shape:  (1000, 100, 10) ，but I want pass the real valid length of every length information together with input tensor, and use the parameter to do some calculates, how can I suppose to do?

I have a one way that is create a new input with shape(1000,100,1)，padded with all valid length of every examples. But when I want use the parameter as a indice to do the slice of the input tensor, how can I convert a tensor to a number to do,say : tensor[: ,slice,: ]?

**Comment by poppintiger** [comment]
@jvishnuvardhan OK, thank you so much!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
