### ISSUE TITLE
Cannot run Tensorflow example for Android on Windows 

### ISSUE THREAD

**Issue by riccitensor** [tensorflow/tensorflow#2530]
I am trying to run Tensorflow example for Android on an ARM emulator (Android 5.0.1, API 21), but it does not run. What can be the reason for that?

> 05-25 17:14:31.340: E/AndroidRuntime(1189): FATAL EXCEPTION: main 05-25 17:14:31.340: E/AndroidRuntime(1189): Process: org.tensorflow.demo, PID: 1189 05-25 17:14:31.340: E/AndroidRuntime(1189): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.tensorflow.demo-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libtensorflow_demo.so" 05-25 17:14:31.340: E/AndroidRuntime(1189): at java.lang.Runtime.loadLibrary(Runtime.java:366) 05-25 17:14:31.340: E/AndroidRuntime(1189): at java.lang.System.loadLibrary(System.java:989) 05-25 17:14:31.340: E/AndroidRuntime(1189): at org.tensorflow.demo.TensorflowClassifier.(TensorflowClassifier.java:47) 05-25 17:14:31.340: E/AndroidRuntime(1189): at org.tensorflow.demo.TensorflowImageListener.(TensorflowImageListener.java:55) 05-25 17:14:31.340: E/AndroidRuntime(1189): at org.tensorflow.demo.CameraConnectionFragment.(CameraConnectionFragment.java:452) 05-25 17:14:31.340: E/AndroidRuntime(1189): at org.tensorflow.demo.CameraConnectionFragment.newInstance(CameraConnectionFragment.java:271) 05-25 17:14:31.340: E/AndroidRuntime(1189): at org.tensorflow.demo.CameraActivity.onCreate(CameraActivity.java:33) 05-25 17:14:31.340: E/AndroidRuntime(1189): at android.app.Activity.performCreate(Activity.java:5937) 05-25 17:14:31.340: E/AndroidRuntime(1189): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)

**Comment by andrewharp** [comment]
Hi, how are you building the Tensorflow demo? Are you building the native library as well? Can you check in your .apk (it's a zip file) to see if the .so file is actually there?

**Comment by riccitensor** [comment]
Hi, I am using Eclipse 4.2.1 to import and build the demo app. I am not building the native library. Also, there's no .SO file in the .APK.

**Comment by andrewharp** [comment]
Right, the .so file is the native library that contains the actual Tensorflow code. Eclipse can't do all the building by itself (unless you configure extra build steps to handle the native libs).

There are instructions for building in the Android example's [README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/README.md) file which will cover the native compilation as well.

**Comment by andrewharp** [comment]
Closing, please reopen if you need specific help building the demo (though currently we don't officially support building on Windows).
