### ISSUE TITLE
Failed to build tensorflow pip package from source in dockerfile provided under tools folder

### ISSUE THREAD

**Issue by rickyzhang82** [tensorflow/tensorflow#25304]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Docker image nvidia/cuda:9.0-base-ubuntu16.04 provided by tensorflow/tensorflow/tools/dockerfiles/dockerfiles/nvidia-devel.Dockerfile

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
NA
- TensorFlow installed from (source or binary):
NA

- TensorFlow version:
v1.12.0

- Python version:
3.5

- Installed using virtualenv? pip? conda?:
NONE

- Bazel version (if compiling from source):
20.0

- GCC/Compiler version (if compiling from source):
gcc 5.4

- CUDA/cuDNN version:
CUDA 9

- GPU model and memory:
1050ti

**Describe the problem**
Build failed in Bazel.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Checkout tensorflow release tag v.1.12 commit a6d8ffae097d0132989ae4688d224121ec6d8f35.
1. Build image `docker build -f ./dockerfiles/nvidia-devel.Dockerfile --build-arg USE_PYTHON_3_NOT_2=True -t tf-nvidia-devel-python3 .`
1. Run container `docker run --runtime=nvidia  -v /home/Ricky/repo/github/tensorflow:/tensorflow -it tf-nvidia-devel-python3`
1. Run `\.configure` as a sane person, eg enable CUDA and etc.
1. Run ` bazel build -k //tensorflow/tools/pip_package:build_pip_package`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
root@252b84b2aa65:/tensorflow# bazel build -k //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/tensorflow/tools/bazel.rc
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=130
INFO: Reading rc options for 'build' from /tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/local/lib/python3.5/dist-packages --python_path=/usr/bin/python3 --define with_ignite_support=true --define with_xla_support=true --action_env TF_NEED_OPENCL_SYCL=0 --action_env TF_NEED_ROCM=0 --action_env TF_NEED_CUDA=1 --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda --action_env TF_CUDA_VERSION=9.0 --action_env CUDNN_INSTALL_PATH=/usr/lib/x86_64-linux-gnu --action_env TF_CUDNN_VERSION=7 --action_env TENSORRT_INSTALL_PATH=/usr/lib/x86_64-linux-gnu --action_env TF_TENSORRT_VERSION=4.1.2 --action_env NCCL_INSTALL_PATH=/usr/lib/x86_64-linux-gnu --action_env NCCL_HDR_PATH=/usr/include --action_env TF_NCCL_VERSION=2 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,7.0 --action_env LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64 --action_env TF_CUDA_CLANG=0 --action_env GCC_HOST_COMPILER_PATH=/usr/bin/gcc --config=cuda
ERROR: Config value cuda is not defined in any .rc file
INFO: Invocation ID: ef2903c5-eec1-4d50-8f50-cb88cfc320e1
```

Please don't take it personally. But you guys write a very very very bad dockerfile which doesn't handle the build tools dependency carefully. I found that bazel is 0.22!

```
root@effd8d74a22c:/# bazel version
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: f740cfea-bba1-4a08-b04c-c41c4cd39a8b
Build label: 0.22.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jan 28 12:58:08 2019 (1548680288)
Build timestamp: 1548680288
Build timestamp as int: 1548680288
```

**Comment by jvishnuvardhan** [comment]
@rickyzhang82 Could you try the latest docker version. There were some issues that were cleared in the recent docker file. Please let us know how it progresses. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this hoping it was resolved by using newer docker. Please let me know if I am mistaken. Thanks!
