### ISSUE TITLE
TensorFLow v1.13.0rc0 tflite_convert fails to convert TensorFlow model with FusedBatchNormalization layers

### ISSUE THREAD

**Issue by ruffles1** [tensorflow/tensorflow#25301]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Fedora 26
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.0rc0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: Nvidia Tesla P100

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
tflite_convert fails to convert simple conv2d model with batch norm file to .tflite. The trained model was frozen to a .pb file using freeze_graph. It fails with the following errors:

tflite_convert --graph_def_file=frozen_saved_model.pb --output_file=frozen_saved_model.tflite --input_shapes="1,28,28,1" --input_arrays=conv2d_input --output_arrays=dense_1/Softmax

Traceback (most recent call last):
  File "/virtualenv/tf-1.13.0-gpu/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 426, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node batch_normalization_v1/cond/ReadVariableOp/Switch was passed float from batch_normalization_resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/virtualenv/tf-1.13.0-gpu/bin/tflite_convert", line 10, in <module>
    sys.exit(main())
  File "/virtualenv/tf-1.13.0-gpu/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 442, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/virtualenv/tf-1.13.0-gpu/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/virtualenv/tf-1.13.0-gpu/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 438, in run_main
    _convert_model(tflite_flags)
  File "/virtualenv/tf-1.13.0-gpu/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 122, in _convert_model
    converter = _get_toco_converter(flags)
  File "/virtualenv/tf-1.13.0-gpu/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 109, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/virtualenv/tf-1.13.0-gpu/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 274, in from_frozen_graph
    _import_graph_def(graph_def, name="")
  File "/virtualenv/tf-1.13.0-gpu/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 501, in new_func
    return func(*args, **kwargs)
  File "/virtualenv/tf-1.13.0-gpu/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: Input 0 of node batch_normalization_v1/cond/ReadVariableOp/Switch was passed float from batch_normalization_v1/gamma:0 incompatible with expected resource.

**Describe the expected behavior**
A TensorFlow Lite version of the frozen model file should have been generated by the tool.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

import tensorflow as tf
import tensorflow.keras.optimizers as optimizers
import tensorflow.keras.losses as losses
from tensorflow.keras.datasets import mnist

(train_x, train_y), _ = mnist.load_data()

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(28,28,1),
                 kernel_regularizer=regularizers.l1(reg_weight)))
model.add(Conv2D(64, (3, 3), activation='relu', kernel_regularizer=regularizers.l1(reg_weight)))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu', kernel_regularizer=regularizers.l1(reg_weight)))
model.add(Dense(10, activation='softmax', kernel_regularizer=regularizers.l1(reg_weight)))

model.compile(optimizer=optimizers.Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(train_x, train_y, batch_size=64, epochs=2, verbose=1)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by LukeBolly** [comment]
Any update or workarounds for this?

**Comment by ruffles1** [comment]
The workaround I'm using is to replace tf.keras.layers.BatchNormalization layers with tf.layers.batch_normalization(fused=False). tflite_convert converts the model successfully with this. 

"fused=False" is needed if converting to a quantized flatbuffer file (in my case, I'm training with fake quantization nodes). 

Otherwise, there will be errors regarding missing min/max information in the graph:

`2019-03-25 15:04:13.845816: F tensorflow/lite/toco/tooling_util.cc:1702] Array batch_normalization_v1/FusedBatchNorm_mul_0, which is an input to the Add operator producing the output array batch_normalization_v1/FusedBatchNorm, is lacking min/max data, which is necessary for quantization. If accuracy matters, either target a non-quantized output format, or run quantized training with your model from a floating point checkpoint to change the input graph to contain min/max information. If you don't care about accuracy, you can pass --default_ranges_min= and --default_ranges_max= for easy experimentation.`

**Comment by hahadashi** [comment]
> The workaround I'm using is to replace tf.keras.layers.BatchNormalization layers with tf.layers.batch_normalization(fused=False). tflite_convert converts the model successfully with this.

you just add the only property "fused=False" in tf.layers.batch_normalization when you training???

**Comment by NEU-Gou** [comment]
@ruffles1 Thank you for the workaround. I noticed tf.keras.layer.BatchNormalization also has the "fused" parameter and I tried to set "fused=False". But now the tf.contrib.quantize.create_training_graph() only inserts fakequant nodes to partial of my graph... Did you try to use BatchNorm from tf.keras?

**Comment by hahadashi** [comment]
> @ruffles1 Thank you for the workaround. I noticed tf.keras.layer.BatchNormalization also has the "fused" parameter and I tried to set "fused=False". But now the tf.contrib.quantize.create_training_graph() only inserts fakequant nodes to partial of my graph... Did you try to use BatchNorm from tf.keras?

他不是说用tf.layer.bn代替么？

**Comment by NEU-Gou** [comment]
@ruffles1 @hahadashi  I figured out my problem. Currently (r1.13), BN layer has to be followed by an activation layer (say relu) to be recognized by contrib/quantize. Since my network does have linear Conv-BN layer, it will complain about lacking min/max for FusedBN node when convert to quantized TFLite model.

**Comment by ruffles1** [comment]
@NEU-Gou I just tried your suggestion, and unfortunately, fake quant ops are still failing to be added to the batch norm ops. I get the same error when converting to tflite. Could you please share an example of a working model that includes fused batch norm and fake quant ops?

**Comment by hahadashi** [comment]
> @NEU-Gou I just tried your suggestion, and unfortunately, fake quant ops are still failing to be added to the batch norm ops. I get the same error when converting to tflite. Could you please share an example of a working model that includes fused batch norm and fake quant ops?

you try the 1.13??

**Comment by ruffles1** [comment]
@hahadashi Yes, I'm on 1.13.1

**Comment by NEU-Gou** [comment]
@ruffles1 Double checked your error massage. Seems that it's a problem related to tf.keras.backend.learning_phase. Did you try to run "tf.keras.backend.set_learning_phase(1)" in training and when converting, BEFORE loading the .pb model, run "tf.keras.backend.set_learning_phase(0)".

**Comment by hahadashi** [comment]
> @ruffles1 Double checked your error massage. Seems that it's a problem related to tf.keras.backend.learning_phase. Did you try to run "tf.keras.backend.set_learning_phase(1)" in training and when converting, BEFORE loading the .pb model, run "tf.keras.backend.set_learning_phase(0)".

can you try a training experiment on you env, a net including  tf.nn.conv2d + tf.layers.batch_normalization + tf.nn.relu.

**Comment by LukeBolly** [comment]
I resolved it by saving the trained weights, clearing the session, setting the learning phase, loading the model back, then restoring the trained weights into the (now evaluation) model. Doing this removes all of the 'switch' ops from the graph which relate to the BatchNorm layers and converts your dropout nodes to identity ops. The model can then be frozen like usual.

```
trained_model.save_weights(output_weights)

tf.keras.backend.clear_session()
tf.keras.backend.set_learning_phase(0)    # This is the important part
eval_model = model_build_function()
eval_model.load_weights(output_weights, by_name=True)
```

**Comment by ruffles1** [comment]
@LukeBolly This is more or less what I've been dong to quantize aware train a model with batch norm. My problem is when training with fused batch norm layers. In this case, the conversion will fail, even with using the method you've described. Have you tested with fused batch norm layers?

**Comment by NEU-Gou** [comment]
@ruffles1 @hahadashi I tried a few different setting and figured some "requirements" for the contrib/quantize/create_train(eval)_graph to work:
- For CONV2D+BN+ReLU, the CONV2D op has to be "use_bias=False"
- For CONV2D with bias, it CANNOT followed by BN layer

Hope this is helpful. Good luck

**Comment by hahadashi** [comment]
> @ruffles1 @hahadashi I tried a few different setting and figured some "requirements" for the contrib/quantize/create_train(eval)_graph to work:
> 
> * For CONV2D+BN+ReLU, the CONV2D op has to be "use_bias=False"
> * For CONV2D with bias, it CANNOT followed by BN layer
> 
> Hope this is helpful. Good luck

thanks，

which api to call the BN layer??(tf.layers.batch_normalization or??) and which tf version you using??

**Comment by NEU-Gou** [comment]
@hahadashi I'm using r1.13 and tf.keras.layers

**Comment by hahadashi** [comment]
thanks


发自我的iPhone

------------------ Original ------------------

**Comment by miaout17** [comment]
It seems the original script has some bugs (Keras complaining shape mismatch etc). I fixed the script and tried to call `TFLiteConverter.from_keras_model_file` directly, and everything works fine (with 1.13.0rc0 and 1.13.1). 

The takeaway is you don't need to call freeze_graph by yourself when using a Keras model. It seems `TFLiteConverter` does a better job for you. 
 
The script that works on my machine:
```
import tensorflow as tf
import tensorflow.keras.optimizers as optimizers
import tensorflow.keras.losses as losses
from tensorflow.keras.datasets import mnist

(train_x, train_y), _ = mnist.load_data()

from tensorflow.keras.layers import *
from tensorflow.keras.models import *
regularizers = tf.keras.regularizers

reg_weight = 0.00001

model = Sequential()
model.add(Reshape((28, 28, 1), input_shape=(28, 28)))
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(28,28,1),
                 kernel_regularizer=regularizers.l1(reg_weight)))
model.add(Conv2D(64, (3, 3), activation='relu', kernel_regularizer=regularizers.l1(reg_weight)))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu', kernel_regularizer=regularizers.l1(reg_weight)))
model.add(Dense(10, activation='softmax', kernel_regularizer=regularizers.l1(reg_weight)))

model.compile(optimizer=optimizers.Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

train_x = train_x[:100, :, :]
train_y = train_y[:100]
model.fit(train_x, tf.keras.utils.to_categorical(train_y), batch_size=64, epochs=2, verbose=1)
model.save("/tmp/25301.h5")
converter = tf.lite.TFLiteConverter.from_keras_model_file("/tmp/25301.h5")
tfl = converter.convert()
print(len(tfl))
```

Closing this. Feel free to reopen if there's unresolved questions.
