### ISSUE TITLE
[Docs] Do not link to symbols within code blocks

### ISSUE THREAD

**Issue by RicCu** [tensorflow/tensorflow#25306]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.12, 1.13, 2.0
- Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/TFRecordDataset#map

**Describe the documentation issue**
The [documentation's symbol resolver](https://github.com/tensorflow/docs/blob/58e99a76ebd4b533fed5591147441ee3f6db3dae/tools/tensorflow_docs/api_generator/parser.py#L119) will automatically replace all appearances of \`tf.symbol\` with markdown links to the symbol's definition, which is generally great, however when these symbols appear 
within code blocks (e.g. in [usage examples](https://github.com/tensorflow/tensorflow/blob/09696450acc1a69dcac4717de87ee4f30544865a/tensorflow/python/data/ops/dataset_ops.py#L912)) the inserted link cannot be rendered correctly, and is interpreted as a plain string like `<a href="../../tf/Tensor"><code>tf.Tensor</code></a>`. Thus, it would be best if symbols within code blocks are not replaced by links, or by links that do render correctly (AFAIK links cannot be placed within code blocks). 

Note: I have only observed this behavior in comments within code blocks.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
Yes, I could submit a PR. However I'm unsure as to the best strategy to efficiently determine if the symbol lies within a code block. I imagine that one could split the strings by re matching ` ``` ` and then deciding whether or not to `re.sub` the current section of the docstring, but this much string manipulation might be somewhat costly.

**Comment by yashk2810** [comment]
This has been fixed.
