### ISSUE TITLE
FastParseExample hash collision

### ISSUE THREAD

**Issue by yann-yy** [tensorflow/tensorflow#25313]
**System information**
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):  1.12.0
- Python version: 2.7
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): GCC4.8.5

**Describe the current behavior**
build config index retry always failed.
code in `tensorflow/core/util/example_proto_fast_parsing.cc` function `FastParseExample`
[https://github.com/tensorflow/tensorflow/blob/a93f06d160955c99bc279a419902ac40824a2cab/tensorflow/core/util/example_proto_fast_parsing.cc#L988](url)
ok flag is not reset to true. And this will fail for 1000 times, if hash collision is found at first time.
**Describe the expected behavior**
 reset ok flag and rehash with new seed, so that retry logic will work

**Comment by jvishnuvardhan** [comment]
@yann-yy were you able to build and install TF? Please provide OS? If the build is failing, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#linux). Thanks!

**Comment by yann-yy** [comment]
> @yann-yy were you able to build and install TF? Please provide OS? If the build is failing, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#linux). Thanks!

hi, @jvishnuvardhan ,
    Thanks for your reply. This is not a build issue. And I have submit a [pull request](https://github.com/tensorflow/tensorflow/pull/25449) to fix this. This issue could be closed.

**Comment by jvishnuvardhan** [comment]
@yann-yy Thank you! I am closing this issue. Thanks again!

**Comment by mihaimaruseac** [comment]
I think this should be kept open until the PR with the fix lands

**Comment by mihaimaruseac** [comment]
Thank you for #29121, fixing this
