### ISSUE TITLE
Binary prediction with LSTM

### ISSUE THREAD

**Issue by korosig** [tensorflow/tensorflow#25326]
I'm trying to implement an LSTM model to make binary (or multiclass) classification from raw log data(Mooc courses log data -> user-level droput/grade prediction ). I have read lots of publication and tutorials which seems to be what I'm looking for, but couldn't find any example on how to use it.

Do you have a link or something about this topic? (RNN, ConvLSTM2D, LSTM, GRU on Keras or TF)

**Comment by ymodak** [comment]
This can be a good [document](https://www.tensorflow.org/tutorials/keras/basic_text_classification) to start binary text classification problems.
