### ISSUE TITLE
Error when restoring model using an Embedding layer

### ISSUE THREAD

**Issue by werner-rammer** [tensorflow/tensorflow#25327]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.0
- Python version: 3.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 10.0
- GPU model and memory: RTX 2070 (8GB)

**Describe the current behavior**
Attempts to restore a frozen Keras model including an "Embedding" layer fail. The same problem appears when `tf.graph_util.convert_variables_to_constants()` and `tf.import_graph_def()` are used.
The error is:
```
Traceback (most recent call last):

  File "<ipython-input-11-95d358f9d586>", line 3, in <module>
    tf.import_graph_def(sg)

  File "/home/werner/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)

  File "/home/werner/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 431, in import_graph_def
    raise ValueError(str(e))

ValueError: Input 0 of node import/state/embedding_lookup was passed float from import/state/embeddings:0 incompatible with expected resource.
```
I tried:
* Saving the model with `tensorflow.saved_model.simple_save()`, then running the `freeze_graph` script to generate a frozen model, then loading the frozen model again in C++ / Python. The same error.

* `convert_variables_to_constants()`, and ` tf.import_graph_def()` the graph -> same error.

**Code to reproduce the issue**

Minimal model:
```
from tensorflow.keras.layers import Embedding, Dense, Input
from tensorflow.keras.models import Model
from tensorflow.keras import backend as K
import tensorflow as tf

sinput = Input(shape=(1,),  name='state_input', dtype='int32')
sinput_em = Embedding(output_dim=16, input_dim=100, input_length=1, name="state")(sinput)
model = Model(inputs=[sinput], outputs=[sinput_em]) 
model.compile(loss={'state': 'sparse_categorical_crossentropy' },   optimizer='adam')
```

* Steps when `save_model()` is used:

```
### Save model
from tensorflow.saved_model import simple_save
simple_save(K.get_session(),
            "SavedModel/testembedding",
            inputs={"state_input": sinput },
            outputs={'state': sinput_em})
# then run the script:
#  ~/.local/bin/freeze_graph  --input_saved_model_dir=SavedModel/testembedding --output_graph=frozenemb.pb  --output_node_names=state/embedding_lookup/Identity_1 --clear_devices

# try to load again:
frozen_graph="frozenemb.pb"
with tf.gfile.GFile(frozen_graph, "rb") as f:
    restored_graph_def = tf.GraphDef()
    restored_graph_def.ParseFromString(f.read())


with tf.Graph().as_default() as graph:
    tf.import_graph_def(
        restored_graph_def,
        input_map=None,
        return_elements=None,
        name=""
        )

# -> error in import_graph_def()
```

* OR steps when `convert_variables_to_constants()` is used:

```
def serialize_graph(model):
    g = tf.graph_util.convert_variables_to_constants(
        tf.keras.backend.get_session(),
        tf.keras.backend.get_session().graph.as_graph_def(),
        #[n.name for n in tf.keras.backend.get_session().graph.as_graph_def().node],
        [t.op.name for t in model.outputs]
    )
    return g

sg = serialize_graph(model)

newg = tf.Graph()
with newg.as_default():
   tf.import_graph_def(sg) # -> error
   
```

**Other info / logs**
Seems to be related to #21889 (the error message is different)

**Comment by karmel** [comment]
Can you try using the [tf.keras.experimental.export](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/experimental/export)? This handles Keras models more gracefully.

**Comment by werner-rammer** [comment]
Hi, thanks for the suggestion!
I tried `tf.keras.experimental.export`, and the export itself works fine. However, the same error remains when I try to load the graph after freezing. Here is my code:

```
# define the model, the one used now has an additional softmax layer, then:
saved_to_path = tf.keras.experimental.export(
      model, 'SavedModel/testembedding')

# import works fine
# Load the saved keras model back.
model_prime = tf.keras.experimental.load_from_saved_model(saved_path_model)
model_prime.summary()

# freezing:
from tensorflow.python.tools import freeze_graph
from tensorflow.python.saved_model import tag_constants

input_saved_model_dir = saved_to_path
output_graph_filename = "SaveFiles/testemb.pb"
output_node_names = "out/Softmax"  
input_binary = False
input_saver_def_path = False
restore_op_name = None
filename_tensor_name = None
clear_devices = False
input_meta_graph = False
checkpoint_path = None
input_graph_filename = None
saved_model_tags = tag_constants.SERVING

freeze_graph.freeze_graph(input_graph_filename, input_saver_def_path,
                            input_binary, checkpoint_path, output_node_names,
                              restore_op_name, filename_tensor_name,
                              output_graph_filename, clear_devices, "", "", "",
                              input_meta_graph, input_saved_model_dir,
                            saved_model_tags)

# load again, -> ERROR: ValueError: Input 0 of node state/embedding_lookup was passed float from state/embeddings:0 incompatible with expected resource.
frozen_graph="SaveFiles/testemb.pb"
with tf.gfile.GFile(frozen_graph, "rb") as f:
    restored_graph_def = tf.GraphDef()
    restored_graph_def.ParseFromString(f.read())


with tf.Graph().as_default() as graph:
    tf.import_graph_def(
        restored_graph_def,
        input_map=None,
        return_elements=None,
        name=""
        )

```

Any more ideas?

**Comment by disha3** [comment]
@werner-rammer , I am getting the same error, did you find a solution for this?

**Comment by SVDmodel** [comment]
@disha3 , unfortunately not! Bad thing is that in the not-too-distant future I'll really need this ...

**Comment by gargn** [comment]
cebce4a should fix this issue. Please reopen if it's still an issue.

**Comment by werner-rammer** [comment]
Thanks! When I use the changed  version of `graph_util_impl.py` (by copying the file to my local pyhton lib) it works!
Looks as if the mentioned commit above fixes the issue.
Thanks again!

**Comment by veqtor** [comment]
Can you please merge this to master, it's been since April 18, the merge is tagged with 1.12.1 but it's not even in master, so we can't verify or even use graph freezing (if it works, I don't know if it does).

What happened to this PR?

Why is it only in this "testkevinbonz repo"?

This is a breaking bug that makes it impossible to freeze saved_models that contain embeddings, so much for the "keras by default", also, the bug breaks BERT for me

**Comment by zepen** [comment]
> Thanks! When I use the changed version of `graph_util_impl.py` (by copying the file to my local pyhton lib) it works!
> Looks as if the mentioned commit above fixes the issue.
> Thanks again!

changed version of `graph_util_impl.py`？which vesion？ i have same problem need your help。

**Comment by werner-rammer** [comment]
Hi,
well I simply copied from the github-repo:
https://github.com/tensorflow/tensorflow/blob/cebce4a2b5e33a06a1c92772008082895568f10a/tensorflow/python/tools/freeze_graph.py

and updated the file locally in the python lib (maybe just search for freeze_graph.py on your machine).

**Comment by HuizhenShu** [comment]
problem solved -- replace local graph_util_impl.py with https://github.com/tensorflow/tensorflow/blob/cebce4a2b5e33a06a1c92772008082895568f10a/tensorflow/python/framework/graph_util_impl.py
