### ISSUE TITLE
tf.data.Dataset error in documentation

### ISSUE THREAD

**Issue by Herlderlord** [tensorflow/tensorflow#25320]
**System information**
- TensorFlow version: 1.12.0
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/data/Dataset#zip

**Describe the documentation issue**
I have tested the code provided in the documentation. Here the code : 

```
from tensorflow.data import Dataset # i have added my own


# NOTE: The following examples use `{ ... }` to represent the
# contents of a dataset.
a = { 1, 2, 3 }
b = { 4, 5, 6 }
c = { (7, 8), (9, 10), (11, 12) }
d = { 13, 14 }

# The nested structure of the `datasets` argument determines the
# structure of elements in the resulting dataset.
Dataset.zip((a, b)) == { (1, 4), (2, 5), (3, 6) }
Dataset.zip((b, a)) == { (4, 1), (5, 2), (6, 3) }

# The `datasets` argument may contain an arbitrary number of
# datasets.
Dataset.zip((a, b, c)) == { (1, 4, (7, 8)),
                            (2, 5, (9, 10)),
                            (3, 6, (11, 12)) }

# The number of elements in the resulting dataset is the same as
# the size of the smallest dataset in `datasets`.
Dataset.zip((a, d)) == { (1, 13), (2, 14) }
```

Here the error provided by the system:
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    Dataset.zip((a, b)) == { (1, 4), (2, 5), (3, 6) }
  File "/home/idolon/.virtualenvs/research/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 612, in zip
    return ZipDataset(datasets)
  File "/home/idolon/.virtualenvs/research/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2037, in __init__
    raise TypeError(message)
TypeError: The argument to `Dataset.zip()` must be a nested structure of `Dataset` objects.
```

I don't really understand what is Dataset and how it works, there's no explicit examples of its functionalities. What can we do with it ? How to build a dataset, how it's used, and how to show data. We have only examples on official datasets but what about making our own datasets ? Maybe i've not found the correct documentation page because of my bad english mastering. 

So, is it an error of the documentation or just me that have not followed correctly the doc ?
Best regards.

**Comment by mrry** [comment]
Yes, this part of the comment was supposed to imply that the code is not runnable as is:

```python
# NOTE: The following examples use `{ ... }` to represent the
# contents of a dataset."
```

We did this to keep the examples short,  but I can see why this might cause confusion! We'd welcome contributions to improve the readability (and testability) of the comments here.

/cc @jsimsa FYI

**Comment by ThomasHagebols** [comment]
@mrry I was interested to work on this for my first commit to TensorFlow. What do you think of the following? I can make a pull request if you like

```
a = Dataset.from_tensor_slices(tf.range(1, 4))  # [ 1, 2, 3 ]
b = Dataset.from_tensor_slices(tf.range(4, 7))  # [ 4, 5, 6 ]
c = Dataset.from_tensor_slices(tf.reshape(tf.range(7,13), (3,2)))  # [ [7, 8], [9, 10], [11, 12] ]
d = Dataset.from_tensor_slices(tf.range(13, 15))  # [ 13, 14 ]

# The nested structure of the `datasets` argument determines the
# structure of elements in the resulting dataset.
Dataset.zip((a, b)) # ==> [ [1, 4], [2, 5], [3, 6] ]
Dataset.zip((b, a)) # ==> [ [4, 1], [5, 2], [6, 3] ]

# The `datasets` argument may contain an arbitrary number of
# datasets.
Dataset.zip((a, b, c))  # ==> [ [1, 4, [7, 8]],
                        #       [2, 5, [9, 10]],
                        #       [3, 6, [11, 12]] ]
    
# The number of elements in the resulting dataset is the same as
# the size of the smallest dataset in `datasets`.
Dataset.zip((a, d))  # ==> [ [1, 13], [2, 14] ]
```

**Comment by mrry** [comment]
Thanks @ThomasHagebols! That mostly looks good with just one nit: the difference between tuples and lists is significant here, so please use `(...)` when the elements will be made up of tuples, e.g.:

```
Dataset.zip((a, b, c))  # ==> [ (1, 4, [7, 8]),
                        #       (2, 5, [9, 10]),
                        #       (3, 6, [11, 12]) ]
```

**Comment by ThomasHagebols** [comment]
@mrry Thanks for the feedback. I noticed that there are several code examples that are not executable and a bit vague in python/data/ops/dataset_ops.py. If you want I can fix the documentation of the methods concatenate, map, flat_map and interleave in the same pull request.

**Comment by mrry** [comment]
The more the merrier, thanks!

**Comment by ritwik12** [comment]
I guess this can be closed, is there anything remaining for this issue?
