### ISSUE TITLE
The docker image of gcr.io/tensorflow/tensorflow-full does not exist

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#2533]
We follow the [official docs](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker) and try to pull this image but it doesn't exist.

```
root@do:~# docker pull gcr.io/tensorflow/tensorflow-full
Using default tag: latest
Pulling repository gcr.io/tensorflow/tensorflow-full
Tag latest not found in repository gcr.io/tensorflow/tensorflow-full
```

After searching in StackOverflow and we found `b.gcr.io/tensorflow/tensorflow-full` works.

### Environment info
Operating System: Ubuntu 16.10

### Steps to reproduce
1. docker pull gcr.io/tensorflow/tensorflow-full(not work)

### What have you tried?
1. docker pull b.gcr.io/tensorflow/tensorflow-full(work)

**Comment by vrv** [comment]
(Which link should we use?  gcr.io/tensorflow/tensorflow or b.gcr.io/tensorflow/tensorflow-full ?

**Comment by ShunyuanZ** [comment]
Which version should I use, if I would like to practice with "inception-v3" model, as described in this tutorial?
tutorial link:https://www.tensorflow.org/versions/r0.8/tutorials/image_recognition/index.html#image-recognition

I pulled b.gcr.io/tensorflow/tensorflow-full, but couldn't find the source code "classify_image.py" under this directory "tensorflow/models/image/imagenet". In fact, there is no such a folder named "imagenet".

**Comment by jendap** [comment]
I will update the documentation. It has to be very old. I don't think "full" was even in the original release 0.5.0.

There are basically two images:
1) gcr.io/tensorflow/tensorflow - smaller but cpu only
2) gcr.io/tensorflow/tensorflow:0.8.0-gpu - bigger but supports nvidia cuda

If you have nvidia gpu use the second otherwise the first.

BTW: Do you really have ubuntu 16.10? :-)

**Comment by tobegit3hub** [comment]
Thanks @jendap for fixing this. We use Ubuntu 16.10 for dev environment, not production 😃
