### ISSUE TITLE
[BUG] gradients of `tf.cond` with float64 breaks with ResourceVariable

### ISSUE THREAD

**Issue by mayou36** [tensorflow/tensorflow#25339]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 3 tried: binary and head (w & w/o xla)
- TensorFlow version (use command below): 1.12 resp. head
- Python version:3.6
- Bazel version (if compiling from source):irrelevant
- GCC/Compiler version (if compiling from source):irrelevant
- CUDA/cuDNN version: irrelevant
- GPU model and memory: irrelevant

**Describe the current behavior**
Using a (resource!) Variable in tf.cond (and everything in tf.float64) breaks the gradient computation with an error like:
```python
TypeError: Tensors in list passed to 'inputs' of 'Merge' Op have types [float64, float32] that don't all match.
```

In gradients_impl.py, _GradientsHelper (line 805) are ZerosLikeOutsideLoop produced with op.This produces in control_flow_ops.py, line 1469, (iff the variable dtype is resource) zeros with 
```python
array_ops.zeros(gen_resource_variable_ops.variable_shape(switch_val))
```
This uses the dtype of the op.outputs. But for a resource dtype, this creates float32 zeros (which then collides with all the other float64 around). Any other type therefore works.

Tried (next to binary 1.12) also against Master/HEAD with and without XLA (on TF compilation). Same error

Solution: no idea how to get the datatype out there or something. Sorry.

**Code to reproduce the issue**
```python
import tensorflow as tf

var1 = tf.get_variable('var1', initializer=tf.constant(42., dtype=tf.float64), use_resource=True)
with tf.Session() as sess:
    sess.run(var1.initializer)
    res = tf.constant(0., dtype=tf.float64)
    cond1 = tf.cond(tf.constant(True), lambda: res, lambda: res + var1)
    grad_cond = tf.gradients(cond1, var1)
```

**Comment by skye** [comment]
Can you try setting the environment variable TF_ENABLE_CONTROL_FLOW_V2=1 and seeing if you still get an error? (If setting the env var in code, make sure to do it before importing tf).

**Comment by mayou36** [comment]
@skye I still get the error, yes (both with 1.12 and head)

**Comment by rmothukuru** [comment]
@mayou36,
Sorry for the delayed response. Your code could be run without any error in the **`Tensorflow Version 1.15.2`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/477abf7964ce7c71691ea425107c0052/gh_25339.ipynb) of the working code. Thanks!

**Comment by mayou36** [comment]
Hi no worries, many thanks!
