### ISSUE TITLE
2.0 Reference Models: NCF Model (TPU with Keras)

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25346]
This is an implementation of the **Neural Collaborative Filtering** (NCF) framework with Neural Matrix Factorization (NeuMF) model as described in the [Neural Collaborative Filtering](https://arxiv.org/abs/1708.05031) paper. Current implementation is based on the code from the authors' [NCF code](https://github.com/hexiangnan/neural_collaborative_filtering) and the Stanford implementation in the [MLPerf Repo](https://github.com/mlperf/reference/tree/master/recommendation/pytorch).

**Neural Collaborative Filtering** is a general framework for collaborative filtering of recommendations in which a neural network architecture is used to model user-item interactions. Unlike traditional models, NCF does _not_ resort to Matrix Factorization (MF) with an inner product on latent features of users and items. It replaces the inner product with a multi-layer perceptron that can learn an arbitrary function from data.

For the TensorFlow 1.x equivalent, please refer [here](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/official/recommendation/README.md).

The purpose of this issue is to migrate models into the TF 2.0 Keras API. Each migrated model must be eager and distribution compatible, with tests, and all associated engineering artifacts.

**Comment by ogsharma** [comment]
Hi guys, do you have a date for us in terms of when we can expect an NCF implementation in tensorflow 2.x?

**Comment by chunduriv** [comment]
@ogsharma,

Sorry for the late response.

For NCF implementation in `Tensorflow 2.x`. Please refer [here](https://github.com/tensorflow/models/blob/master/official/recommendation/README.md). Thank you.

**Comment by chunduriv** [comment]
@dynamicwebpaige,

Thank you for opening this issue. Could refer to the latest [neumf_model.py](https://github.com/tensorflow/models/blob/master/official/recommendation/neumf_model.py) for NCF model (TPU with Keras) implementation.

Please feel free to close this issue if it is resolved. Thank you.
