### ISSUE TITLE
Library Conversion: Open AI Baselines

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25349]
**[OpenAI Baselines](https://github.com/openai/baselines)** is a set of high-quality implementations of reinforcement learning algorithms. These algorithms make it easier for the research community to replicate, refine, and identify new ideas, and creates solid baselines to build research on top of.

The purpose of this ticket will be to migrate the OpenAI Baselines library to the TF 2.0 API.

- Convert OpenAI Baselines library.
- Run unit tests.
- Ensure processes are well understood.

For more information on OpenAI baselines, check out their blog post [here](https://blog.openai.com/openai-baselines-dqn/) - and be sure to amble around their [website](https://openai.com/), as well as the OpenAI [gym](http://gym.openai.com/)!

**Comment by navneet-nmk** [comment]
I believe even google [dopamine](https://github.com/google/dopamine) needs an update to tf 2.0

**Comment by ffahleraz** [comment]
Hi I have previously worked on some projects with OpenAI Baselines, can I have a try on this?

**Comment by tomerk** [comment]
Adding @tanzhenyu as an assignee here because he's been taking a lead on this & on coordinating with the OpenAI team. Zhenyu, do you have any part of the migration in mind that you feel open source contributors would be able to assist with right now?

**Comment by tanzhenyu** [comment]
Sorry for the delay. Yes it'd be great to get some help from external contributors. @ffahleraz would you be able to help on one or two algos?

**Comment by josiahbjorgaard** [comment]
@tanzhenyu I'd be happy to assist as well! I could help with an algorithm or two. Would that be useful?

**Comment by tanzhenyu** [comment]
@josiahbjorgaard Yep that'd be very helpful. The discussion with OpenAI is to first port things to my own repo. I have already done so with PPO/A2C/DDPG, and working on DQN right now. We can use help on 1) GAIL, 2) ACER, 3) ACKTR, 4) HER, 5) TRPO.
Here's my repo: https://github.com/tanzhenyu/baselines-tf2. You can branch and make PR directly, and once everything is finalized we can port to OpenAI master branch.
I have written most util methods that are required, so hopefully the work required for each algo is stand-alone. @josiahbjorgaard @ffahleraz Let me know what algos you want to grab.

**Comment by josiahbjorgaard** [comment]
@tanzhenyu I'll start on ACER

**Comment by 8bitmp3** [comment]
> I believe even google [dopamine](https://github.com/google/dopamine) needs an update to tf 2.0

[TF-Agents](https://github.com/tensorflow/agents) is prioritized over Dopamine - @dynamicwebpaige. 

If anyone is interested, there's also Stable Baselines - a TensorFlow-based fork of OpenAI's Baselines: https://github.com/Stable-Baselines-Team/stable-baselines with ACER, A2C, ACKTR, HER, PPO2, SAC etc. Full blog post [here](https://towardsdatascience.com/stable-baselines-a-fork-of-openai-baselines-reinforcement-learning-made-easy-df87c4b2fc82).

**Comment by MoritzTaylor** [comment]
@tanzhenyu I will start on ACKTR, if no one works already on this.

**Comment by 8bitmp3** [comment]
> @tanzhenyu I will start on ACKTR, if no one works already on this.

Go for it @MoritzTaylor - handing the ownership over to you - you may be a lot quicker 👍

**Comment by tanzhenyu** [comment]
@MoritzTaylor Sounds good. Have fun and let me know how I could help!

**Comment by seungjaeryanlee** [comment]
I will start working on GAIL! :rocket:

**Comment by tanzhenyu** [comment]
@MoritzTaylor @josiahbjorgaard @seungjaeryanlee 
Gently ping to check the status on your end :-)

Some update from my side: I have merged the current local repo into baselines [tf2 branch](https://github.com/openai/baselines/pull/978), you could either sync from there or sync from my repo (since I will probably continue working on hindsight experience replay).

And let me know how I can help!

**Comment by MoritzTaylor** [comment]
@tanzhenyu 
I have converted most of the files. The only thing I still need to convert is the Kronecker Factor Optimizer, which is a little bit harder. After I finished to convert the optimizer I want to do some testing. I'll try to complete the conversion in the next few days.

I sync already from your repo to be up to date with your commits.

**Comment by tanzhenyu** [comment]
@MoritzTaylor Ah yes, KFAC is a great optimizer and unfortunately we don't include them in TF core.

**Comment by tanzhenyu** [comment]
@josiahbjorgaard @seungjaeryanlee Gently ping and let me know if you need additional help.

**Comment by josiahbjorgaard** [comment]
@tanzhenyu Somebody else should take over mine. I haven't had a chance to get anywhere with it.

**Comment by tanzhenyu** [comment]
@josiahbjorgaard Alright.

**Comment by araffin** [comment]
> > I believe even google [dopamine](https://github.com/google/dopamine) needs an update to tf 2.0
> 
> [TF-Agents](https://github.com/tensorflow/agents) is prioritized over Dopamine - @dynamicwebpaige.
> 
> If anyone is interested, there's also Stable Baselines - a TensorFlow-based fork of OpenAI's Baselines: https://github.com/Stable-Baselines-Team/stable-baselines with ACER, A2C, ACKTR, HER, PPO2, SAC etc. Full blog post [here](https://towardsdatascience.com/stable-baselines-a-fork-of-openai-baselines-reinforcement-learning-made-easy-df87c4b2fc82).

Yes, we would like also to support tf 2.0 in the future for stable baselines.
In short, it is OpenAI baselines with a nice API (scikit learn like) + documentation + new algorithms (SAC, TD3)
The main repo url: https://github.com/hill-a/stable-baselines
Documentation: https://stable-baselines.readthedocs.io/en/master/

@dynamicwebpaige Should I open a new issue for that?

**Comment by avnishn** [comment]
@tanzhenyu if there are any open issues that a community contributor can help with, I'd be more than happy to help!

**Comment by tanzhenyu** [comment]
@avnishn can you help with converting [ACER](https://github.com/openai/baselines/tree/master/baselines/acer) to TF2?

**Comment by avnishn** [comment]
Sure thing! Is there a date that you need it by?

**Comment by tanzhenyu** [comment]
@avnishn Probably in a month or two. I don't have much bandwidth to make this at the moment, but ACER should be pretty straightforward compared to other algs. Let me know if you run into any issues.

**Comment by MoritzTaylor** [comment]
@tanzhenyu 
Sorry that I did not finished already, even I said last time, that I am finish soon. Fortunately I have more time now.
I reach out because I want to ask if it is possible to rewrite KFAC from ground up, since it is not as obvious to transform the TF1 code of it to TF2 as I thought? I think rewriting it, could be easier here, since I've tried to preserve most of the main code so far.

**Comment by tanzhenyu** [comment]
@MoritzTaylor Yes that makes sense to rewrite while maintaining most of the main logic.

**Comment by siyavash** [comment]
@tanzhenyu It seems nobody has taken TRPO, I'd be happy to help with that or any other alogs.

**Comment by tanzhenyu** [comment]
> @tanzhenyu It seems nobody has taken TRPO, I'd be happy to help with that or any other alogs.

[Here](https://github.com/openai/baselines/tree/tf2/baselines/trpo_mpi).

**Comment by siyavash** [comment]
@tanzhenyu it seems TRPO is rewritten. If there are any open issues that I can help with, I'd be very happy to help!

**Comment by zkx741481546** [comment]
> @tanzhenyu
> 对不起，我还没完成，即使我上次说过，我也快完成了。幸运的是我现在有更多时间。
> 我伸出援手是因为我想问是否有可能从头开始重写KFAC，因为将其TF1代码转换为TF2并不像我想的那么明显？我认为在这里重写它可能会更容易，因为到目前为止我一直尝试保留大多数主要代码。

Have you finished KFAC yet? I cloned your KFAC.py and got an error 
AttributeError: 'KfacOptimizer' object has no attribute '_update_stats_op'

**Comment by nbro** [comment]
@araffin It seems that you don't have big plans to upgrade stable-baselines to TF 2, although you already started another Github project, but you are apparently investing your time more on stable-baselines-3 with PyTorch. TF 2.0 is more widely used than PyTorch, so I feel this is somehow a mistake.

**Comment by araffin** [comment]
> @araffin It seems that you don't have big plans to upgrade stable-baselines to TF 2, although you already started another Github project, but you are apparently investing your time more on stable-baselines-3 with PyTorch. TF 2.0 is more widely used than PyTorch, so I feel this is somehow a mistake.

i already replied to you in the SB issue, but for others the answers about our choice to use PyTorch are in https://github.com/hill-a/stable-baselines/issues/366 and https://github.com/hill-a/stable-baselines/issues/733

**Comment by tanzhenyu** [comment]
I'm gonna close this issue, given the OpenAI Baseline conversions is complete under branch tf-2. We don't have intermediate plans to support StableBaselines.
