### ISSUE TITLE
2.0 Reference Models: Transformer (1 GPU, 8 GPU with dist strat and Keras)

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25342]
**Transformer** is a neural network architecture that solves sequence to sequence problems using attention mechanisms. Unlike traditional neural seq2seq models, Transformer does not involve recurrent connections. The attention mechanism learns dependencies between tokens in two sequences. Since attention weights apply to all tokens in the sequences, the Transformer model is able to easily capture long-distance dependencies.

See the paper [Attention is All You Need](https://arxiv.org/abs/1706.03762) for more background.

For the TensorFlow 1.x equivalent, please refer [here](https://github.com/tensorflow/models/tree/master/official/transformer).

The purpose of this issue is to migrate models into the TF 2.0 Keras API. Each migrated model must be eager and distribution compatible, with tests, and all associated engineering artifacts.

**Comment by guptapriya** [comment]
The code is done, we need better documentation for usage before we close this bug.

**Comment by saberkun** [comment]
Transformer V2 initial documentation is checked in with usage guide.
We can close this bug. Tody and the team will work on adding more stats there.

**Comment by guptapriya** [comment]
Thanks @saberkun !
