### ISSUE TITLE
Library Conversion: OpenSeq2Seq

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25353]
**[OpenSeq2Seq](https://github.com/NVIDIA/OpenSeq2Seq)** is a toolkit for distributed and mixed-precision training of sequence-to-sequence (seq2seq) models, created by the researchers at NVIDIA.

OpenSeq2Seq is built using TensorFlow and provides all the necessary building blocks for training encoder-decoder models for neural machine translation, automatic speech recognition, speech synthesis, and language modeling. For documentation and TensorFlow 1.x installation instructions, check [here](https://nvidia.github.io/OpenSeq2Seq/).

The purpose of this ticket will be to migrate OpenSeq2Seq to the TF 2.0 API.

- Convert all existing OpenSeq2Seq code.
- Run unit tests.
- Ensure processes are well understood.

**Comment by a6802739** [comment]
@dynamicwebpaige, could I have a see on this for my first contribution?

**Comment by qlzh727** [comment]
Thanks @dynamicwebpaige for filing this issue. Since the conversion work will be a collaboration between me and Boris on Nvidia side, I will cc him once I got his github user name. Also the code will be committed to Nvidia's repo instead of tensorflow.

**Comment by qlzh727** [comment]
https://github.com/tensorflow/addons/pull/72

**Comment by georgesterpu** [comment]
Hi @dynamicwebpaige @qlzh727 @borisgin
Is Nvidia's OpenSeq2Seq still being migrated to TF 2.0 ? 
I have re-implemented our AV speech toolkit for this latest version of tensorflow using tensorflow/addons/seq2seq (thanks @qlzh727 for all your help so far), yet I am facing a memory leak issue. Was wondering if I could have a look at some code samples in OpenSeq2Seq.

Thanks,
George
