### ISSUE TITLE
seq2seq running problem

### ISSUE THREAD

**Issue by KingAndQueen** [tensorflow/tensorflow#2535]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Ubuntu 14 
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

If installed from sources, provide the commit hash:

### Steps to reproduce
1. copy all files in models/rnn/translate/ to ~/myworkfold/ 
2. run the translate.py like this: python translate.py --data_dir ./ --train_dir ./   ... (it works well )
3. But, when i change the code from "from tensorflow.model.rnn.translate import seq2seq_model" to "import seq2seq_model" in translate.py (in order to use the file seq2seq.py in myworkfold, note that all files are copied form models/rnn/translate/ wothout any change ) 
it errors like this:
Traceback (most recent call last):
  File "my_translate.py", line 279, in <module>
    tf.app.run()
  File "/home/ubuntu/yangqichuan/my_tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "my_translate.py", line 276, in main
    train()
  File "my_translate.py", line 142, in train
    model = create_model(sess, False)
  File "my_translate.py", line 121, in create_model
    forward_only=forward_only)
  File "/home/ubuntu/yangqichuan/my_tensorflow/my_seq2seq/my_seq2seq_model.py", line 152, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/home/ubuntu/yangqichuan/my_tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/seq2seq.py", line 961, in model_with_buckets
    decoder_inputs[:bucket[1]])
  File "/home/ubuntu/yangqichuan/my_tensorflow/my_seq2seq/my_seq2seq_model.py", line 151, in <lambda>
    lambda x, y: seq2seq_f(x, y, False),
  File "/home/ubuntu/yangqichuan/my_tensorflow/my_seq2seq/my_seq2seq_model.py", line 115, in seq2seq_f
    feed_previous=do_decode)
TypeError: embedding_attention_seq2seq() takes at least 6 arguments (7 given)

## What have you tried?
1.i do the same operation for model  LSTM models/rnn/ptb . tensorflow works well
2. if i change back the translate.py file it also works well

What happened ?
### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by lukaszkaiser** [comment]
There was a code change not that long ago that added a new argument (embedding_size) to the call of embedding_attention_seq2seq. It looks a bit like you've mixed the versions, maybe copied a newer file while still using old TensorFlow PIP?

**Comment by girving** [comment]
Closing, since @lukaszkaiser seems to have explained the problem.  We don't support mixing models defined in the tensorflow repo with a different version of tensorflow.

**Comment by KingAndQueen** [comment]
Thanks a lot! It's the problem. TF 0.8 has a new way to call function embedding_attention_seq2seq.
