### ISSUE TITLE
Feature: TensorBoard compatibility with TF 2.0.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25356]
**Overview**
The `tf.summary` module from TF 1.x will be replaced by a new API that differs as follows:

1. The **data-format-specific parts** will be defined in `tensorboard.summary`.
2. The **generated summary events** will use a more extensible "wire format".
3. The **write-side code** will use the V2 summary-writing API (today's `tf.contrib.summary`).

**Background**
Today three sets of summary ops exist: `tf.summary`, `tf.contrib.summary`, and `tb.summary` (aka `tensorboard.summary`).  They differ across two main dimensions: the "summary-writing API" which determines how user code calls the ops, and the "wire format" of how the summary data gets encoded in event files.  Both dimensions have legacy (V1) and new (V2) styles.  The proposed new summary ops fill in the (V2, V2) quadrant of this grid:

|                                                | V1 (FileWriter, merge_summaries) | V2 (create_file_writer, eager-compatible) |
|------------------------------------------------|----------------------------------|-------------------------------------------|
| V1 (dedicated fields per type in tf.Summary)   | `tf.summary`    | `tf.contrib.summary`                        |
| V2 (extensible tensor format, plugin metadata) | `tb.summary`  | [proposed] `tf.summary`  in TF 2.0, exporting symbols from `tb.summary`  |

**Comment by dynamicwebpaige** [comment]
#25524, #24632

**Comment by cottrell** [comment]
Are there any examples or docs in development about this? I am not at all clear on what the intended tensorboard usage is in (the evolving) tensorflow 2.0 api.

**Comment by nfelt** [comment]
@cottrell Yes, there are some new TensorBoard tutorials designed with the TF 2.0 alpha in mind on our new TensorBoard documentation site: https://www.tensorflow.org/tensorboard/r2/get_started

**Comment by HugoDLopes** [comment]
Is there any example using the high-level Estimator's API? I can only find tutorials with keras API. If not, can anyone give an example with `LinearClassifier` for example?

**Comment by nfelt** [comment]
@HugoDLopes I believe the default Estimator usage should still work with TensorBoard as they did in 1.x - if you point TensorBoard at the model directory used by your Estimator, the default metrics should still appear.

It doesn't yet work out of the box to use the TF 2.0 tf.summary API in custom Estimator code unless you set up the writing logic yourself; the plan is to either make that work as well as 1.x or we can add tutorials.  But that's only for custom Estimator model functions, not canned estimators.
