### ISSUE TITLE
Library Conversion: TF Probability

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25350]
**[TensorFlow Probability](https://www.tensorflow.org/probability/)** (TFP) is a Python library built on TensorFlow that makes it easy to combine probabilistic models and deep learning on modern hardware (TPU, GPU). It's for data scientists, statisticians, ML researchers, and practitioners who want to encode domain knowledge to understand data and make predictions. TFP includes:

- A wide selection of probability distributions and bijectors.
- Tools to build deep probabilistic models, including probabilistic layers and the Edward2 language.
- Variational inference and Markov chain Monte Carlo.
- Optimizers such as Nelder-Mead, BFGS, and SGLD.

The purpose of this ticket will be to migrate TF Probability to the TF 2.0 API.

- Convert TF Probability library.
- Run unit tests.
- Ensure processes are well understood.

**Comment by alextp** [comment]
This has been fixed, thanks to @jvdillon @jaingaurav and others!

**Comment by zhangandyx** [comment]
Is this currently in the nightly build?

**Comment by jaingaurav** [comment]
@zhangandyx: Yes please use the tfp-nightly pip package. @jvdillon might be able to comment more on the specific release plans.

**Comment by jvdillon** [comment]
We can cut a stable release after tf 1.14
