### ISSUE TITLE
Feature: Unify argument names (~70).

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25357]

**Comment by amahendrakar** [comment]
@aselle,
Can we please close this issue since it is marked as done in TensorFlow 2.0? Thanks!

**Comment by kumariko** [comment]
@dynamicwebpaige Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).Also can you please elaborate about your Feature and please specify the Use Cases for this feature. Thanks!
