### ISSUE TITLE
Library Conversion: Sonnet

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25355]
**[Sonnet](https://github.com/deepmind/sonnet/tree/master/docs)** is an open-source library built on top of TensorFlow, created by researchers at **[DeepMind](https://deepmind.com/)**. The main purpose of Sonnet is to first construct Python objects which represent some part of a neural network, and then separately connect these objects into the TensorFlow computation graph.

For more information about Sonnet, check out [DeepMind's announcement](https://deepmind.com/blog/open-sourcing-sonnet/).

The purpose of this ticket will be to migrate the Sonnet library to the TF 2.0 API.

- Convert all existing Sonnet code.
- Run unit tests.
- Ensure processes are well understood.

**Comment by alextp** [comment]
@tomhennigan is working on this AFAIK

**Comment by tomhennigan** [comment]
WIP!

**Comment by bhack** [comment]
What about deepmind graph_nets? https://github.com/deepmind/graph_nets/

**Comment by dynamicwebpaige** [comment]
@bhack - It looks like [**Graph Nets**](https://github.com/deepmind/graph_nets/) has dependencies on both **Sonnet** and **TensorFlow Probability** - which means that those libraries would need to be converted to TF 2.0 before Graph Nets could start migrating. 😊

If you'd like to help test the upgrade process for any of the above, though, or to take a stab at porting TensorFlow 1.x code to 2.0, we would appreciate it!

**Comment by dynamicwebpaige** [comment]
You can use now use Sonnet with TensorFlow 2.0 (code available on [this branch](https://github.com/deepmind/sonnet/tree/v2)). A package will be placed on PyPI within the next few months, and this comment will be updated with a link.

Try it out and let us know what you think! 😄
