### ISSUE TITLE
Feature: TensorFlow Lite compatibility with TF 2.0.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25361]
**Problem**
TensorFlow 2.0 introduces features that are not supported by the conversion process used to convert TensorFlow models to TensorFlow Lite models. This issue will track the changes that must be made in order to support the conversion process in TensorFlow 2.0.

**Goals:**

- Add support for converting TensorFlow models generated in TensorFlow 2.0.
- Continue to support conversion for SavedModels generated in TensorFlow 1.X.
- Support conversion for Keras model files generated in TensorFlow 1.X and 2.0.

**Non-goals:**

- Continue to support conversion for frozen GraphDefs generated in TensorFlow 1.X. The related API will be deprecated in 2.0.

**Comment by dynamicwebpaige** [comment]
#25575

**Comment by willbattel** [comment]
What is the status of TFLite at this point? Are we able to use it with TF2 yet? I see this is marked as "Done" in the TF2 project, but I'd appreciate an explicit indicator on this. Thanks!

**Comment by gargn** [comment]
Documentation on converting a 2.0 model to TFLite is available here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/r2/convert/index.md

**Comment by gargn** [comment]
The final documentation is available here: https://www.tensorflow.org/lite/r2/convert/.

**Comment by reactivetype** [comment]
I see a commit on this in https://github.com/tensorflow/tensorflow/commit/d6a7c6a4a6894cfc2de38bab192d6f615071e419
Does it mean nightly has it working already?

**Comment by gargn** [comment]
@reactivetype Correct. The converter is working in the nightly (`tf-nightly-2.0-preview`).
