### ISSUE TITLE
Testing: TF 2.0 with TensorFlow Datasets (TFDS).

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25367]
TFDS is now ready for testing, sans the LMDB dataset!

https://github.com/tensorflow/datasets/issues/34

**Comment by rsepassi** [comment]
TFDS will begin testing against the TF 2.0 preview in the next week or two. And the TF tutorials that use TFDS will also be tested. Tomer Kaftan (does he have a github handle?) was looking into adding tests for them.

**Comment by lc0** [comment]
I was not aware of this ticket wanted to just experiment, and seems like there are still dependencies on contrib like https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/__init__.py#L90

**Comment by rsepassi** [comment]
Yup, will update here when TFDS is 2.0-ready.

**Comment by EmanueleGhelfi** [comment]
I've tested tf2.0 and TFDS in #25414

**Comment by rsepassi** [comment]
TFDS now supports TF 2.0. Woohoo!
