### ISSUE TITLE
Feature: TF Serving compatibility with TF 2.0.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25363]
**[TensorFlow Serving](https://www.tensorflow.org/serving/)** is a flexible, high-performance serving system for machine learning models, designed for production environments. Serving makes it easy to deploy new algorithms and experiments, while keeping the same server architecture and APIs. TensorFlow Serving provides out-of-the-box integration with TensorFlow models, but can be easily extended to serve other types of models and data.

The purpose of this issue is to upgrade Serving to be TF 2.0 compliant. The system must be eager and distribution compatible, with tests, and all associated engineering artifacts.

**Comment by amygdala** [comment]
Is this still current?  I've seen some presos that suggest that TF-serving does support TF 2.0.

**Comment by joaqo** [comment]
Its on the done column in https://github.com/orgs/tensorflow/projects/4#card-17112802 so I would assume its complete, right?

**Comment by Chqbelief** [comment]
Tensorflow2.0 training model，What is the compatibility in tf-serving？

**Comment by Chqbelief** [comment]
Tensorflow2.0 training model，Has compatibility been fully achieved on tf-serving?

**Comment by QiJune** [comment]
Any update on this? Thanks!

**Comment by avatsaev** [comment]
hello?

**Comment by Njerschow** [comment]
Would appreciate any update on this if possible!

**Comment by neil-119** [comment]
We trained a model with the `tf.keras` API and created a SavedModel with Keras. We then tried to deploy it to tf-serving, but we're getting:
```
No versions of servable XX found under base path /models/XX
```
I verified that the SavedModel exists in that path. It was exported like so:
```
model = tf.keras.models.load_model("model.h5", custom_objects={'KerasLayer':hub.KerasLayer})
model.save(some_path_here, save_format="tf")
```
Can someone confirm whether this issue was resolved or not?

**Comment by rthadur** [comment]
This is already been supported.Closing the request.
