### ISSUE TITLE
Documentation: TF 2.0 docs and tutorials.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25366]
Documentation and tutorials are a critical piece of every open-source project, and a developer's first impression of the product. The purpose of this issue will be to track the creation, migration, and translations for TensorFlow 2.0 docs.

For more information, check out the example notebooks we have available [here](https://github.com/tensorflow/docs/tree/master/site/en/r2), as well as the [TF 2.0 upgrade guide](https://github.com/tensorflow/docs/blob/master/site/en/r2/guide/upgrade.md) and the [Effective 2.0 Style Guide](https://github.com/tensorflow/docs/blob/master/site/en/r2/guide/effective_tf2.md).

**Comment by dynamicwebpaige** [comment]
#25587

**Comment by Shashankjain12** [comment]
Hey @dynamicwebpaige can i know about any specific functions which needs some docs!?

**Comment by PriyanshChaudhary** [comment]
@dynamicwebpaige  in this documentation, do we have to implement the high-level APIs without using the graph execution. Since sessions are not being used anymore.?

**Comment by Amin-Tgz** [comment]
Tensorflow 2.x resources such as corresponding tutorials, blogs, codes and videos:
https://github.com/Amin-Tgz/Awesome-TensorFlow-2
I hope to be useful
