### ISSUE TITLE
Feature: Google Colab compatibility with TF 2.0.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25365]
**[Colaboratory](https://colab.research.google.com/)** is a free research tool for machine learning education and research. It’s a Jupyter notebook environment that requires no setup to use. Colab works with most major browsers, and is most thoroughly tested with desktop versions of Chrome and Firefox.

The purpose of this issue will be to track TF 2.0 compatibility with Colab.

**Comment by lc0** [comment]
I wonder what would be the transition period. Since for some time people would still have models with TF1 and just upgrading over night could be pretty radical.

I mean potentially colab can introduce another param for  runtime or `Notebook settings`, something like different cuda drivers

**Comment by dynamicwebpaige** [comment]
Looks like [CUDA 10 support has landed for Google Colab](https://github.com/tensorflow/tensorflow/issues/25081#issuecomment-460912076)!

**Comment by jvishnuvardhan** [comment]
I am closing the tracking issue as it was resolved. `TF2.0` is completely compatible with Colab. Thanks!
