### ISSUE TITLE
Feature: TensorFlow.js compatibility with TF 2.0.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25360]
- Function inlining issue.
- [SavedModel breaks in TensorFlow.js](https://github.com/tensorflow/tfjs/issues/1123).

**Comment by amahendrakar** [comment]
@dynamicwebpaige, @allenlavoie
Can we please close this issue since it is marked as done in TensorFlow 2.0? Thanks!
