### ISSUE TITLE
Feature: TF Hub compatibility with TF 2.0.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25362]
**[TensorFlow Hub](https://www.tensorflow.org/hub/)** is a library for the publication, discovery, and consumption of reusable parts of machine learning models. A module is a self-contained piece of a TensorFlow graph, along with its weights and assets, that can be reused across different tasks in a process known as transfer learning. 

Transfer learning can:
- Train a model with a smaller dataset,
- Improve generalization, and
- Speed up training.

The purpose of this issue is to migrate modules in TF Hub into the TF 2.0 Keras API. Each migrated module must be eager and distribution compatible, with tests, and all associated engineering artifacts.

**Comment by andreyryabov** [comment]
is there a way to import existing 1.x tf-hub models to tf 2.0 ?

**Comment by andresusanopinto** [comment]
Status update: when building tensorflow and tensorflow_hub from HEAD, most hub 1.x modules can be loaded via `hub.load()` in eager mode. In which case one can use: "m.signatures["default"]" to access the methods.

**Comment by andresusanopinto** [comment]
Status update: tensorflow-hub 0.5 was released and together with tensorflow release 2.0.0b1 many old modules are now loadable with `hub.load()` and usable in eager mode.

**Comment by dynamicwebpaige** [comment]
Awesome! Thanks for updating, @andresusanopinto. 😄 

Closing out this ticket, and moving status to **Done** on the project tracker.

**Comment by omoindrot** [comment]
Would be great to have a clean tutorial somewhere on how to use TensorFlow Hub with TF 2.0.

For now, this script works for me on older modules but it's not perfect:

```python
module_url = "https://tfhub.dev/google/imagenet/resnet_v2_50/feature_vector/3"

module = hub.load(module_url, tags=[])
# This is not very clean
model = module.signatures["default"]

images = tf.random.uniform((10, 224, 224, 3))
features = model(images)

# `model` returns a dict so I need to get the default key
features = features["default"]
```

**Comment by AntGul** [comment]
This should not be closed until fully documented.
