### ISSUE TITLE
Documentation: Updating tutorials to use TensorFlow Datasets (TFDS).

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25364]
**[TensorFlow Datasets (TFDS)](https://www.tensorflow.org/datasets/api_docs/python/tfds)** is a collection of datasets ready-to-use with TensorFlow. Each dataset is defined as a `tfds.core.DatasetBuilder`, which encapsulates the logic to download the dataset and construct an input pipeline, as well as contains the dataset documentation (version, splits, number of examples, etc.).

The purpose of this issue is to migrate all tutorials to use TensorFlow Datasets, and to be compliant with the TF 2.0 API. Each migrated tutorial must be eager and distribution compatible, with tests, and all associated engineering artifacts.

**Comment by piyush-kgp** [comment]
I want to contribute. 
Is this referring to imports like https://github.com/tensorflow/tensorflow/blob/226398bd70d6369dd97fa9cf4bee94af9a05f1d0/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py#L33 where we would maybe want to import data from Tensorflow Datasets:
```
import tensorflow_datasets as tfds
ds_train, ds_test = tfds.load(name="mnist", split=["train", "test"])
```

**Comment by dynamicwebpaige** [comment]
Hi, @piyush-kgp! Thanks for the offer to help - we appreciate it! 😊

For more information on `tf.data.Datasets`, check [here](https://github.com/tensorflow/datasets).

@rsepassi would be the best contact, and is working with @yashk2810 + several other members of the TensorFlow team to get tutorials ready for TF 2.0. Also make sure to follow progress on these two issues for TFDS support and testing: [#31](https://github.com/tensorflow/datasets/issues/31), #25367 .

**Ryan, Yash** - are there any tutorials on GitHub right now that Piyush could help migrate?

**Comment by rsepassi** [comment]
That’s great, thanks @piyush-kgp. TFDS is now TF 2.0-ready and can be used in the tutorials. @yashk2810 and his colleagues can coordinate work on the tutorials.
