### ISSUE TITLE
TF 2.0: API symbol renames design review.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25375]
TensorFlow 1.x has over 2000 endpoints total including over 500 endpoints in the root namespace. As number of symbols grows, it is important to maintain a clear structure to aid discoverability.

Certain API symbol placements could be improved:

- Some namespaces were created recently and might not contain all the corresponding symbols. For e.g. `tf.math` namespace was added recently. Symbols such as `tf.round` are not in `tf.math` namespace even though logically they belong in that namespace.
- Some symbols are included in the root namespace even though they are rarely used (for e.g. `tf.zeta`).
- Some symbols currently start with a prefix that could really be replaced by introducing a subnamespace (for e.g. `tf.string_strip` vs `tf.strings.strip`, `tf.sparse_maximum` vs `tf.sparse.maximum`).
- Certain deep hierarchies seem redundant and could be flattened (for e.g. `tf.saved_model.signature_constants.CLASSIFY_INPUTS` could be moved to `tf.saved_model.CLASSIFY_INPUTS`).
- To keep clear structure and reduce duplication, we want to collect all layers, losses and metrics under the `tf.keras` namespace.
- In general, we want to balance flatness and browsability. Flat hierarchies allow for shorter endpoint names that are easy to remember (for e.g. `tf.add` vs `tf.math.add`). At the same time subnamespaces support easier browsability (for e.g. `tf.math` namespace would contain all math functions making it easier to discover available symbols).

Additional information about API symbol renames in TensorFlow 2.0 can be found in the RFC [here](https://github.com/tensorflow/community/blob/master/rfcs/20180827-api-names.md).

**Comment by annarev** [comment]
This has been done a while back. RFC: https://github.com/tensorflow/community/pull/16
