### ISSUE TITLE
Failed in v1.13.0-rc0 docker file build

### ISSUE THREAD

**Issue by rickyzhang82** [tensorflow/tensorflow#25390]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
Just used the tensorflow/tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile in v1.13.0-rc0 tag.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Here is the bug:

https://github.com/tensorflow/tensorflow/blob/a8e5c41c5bbe684a88b9285e07bd9838c089e83b/tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile#L71

**Provide the exact sequence of commands / steps that you executed before running into the problem**

If the condition is false, bash return 1. Thus, it breaks docker build image process.

PLEASE PLEASE PLEASE find a guy who knows dockerfile and bash to write a build script. The quality of build process is absolutely unacceptable.

I tried last stable release v1.12.0 and recent release candidate. They all failed.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by angersson** [comment]
Looks like you're right. Thanks! I've prepared an internal change that will resolve this, so I'm closing the issue.

However, in future bug reports, please do not be so rude.
