### ISSUE TITLE
Feature Request: tf.diag with a parameter to choose the diagonal 

### ISSUE THREAD

**Issue by devmessias** [tensorflow/tensorflow#25398]
**System information**
- TensorFlow version (you are using):'1.12.0'
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
In the current version tf.diag only allow creating a tensor with the main diagonal filled. 
```python
# 'diagonal' is [[1, 2, 3, 4], [5, 6, 7, 8]]

and diagonal.shape = (2, 4)

tf.matrix_diag(diagonal) ==> [[[1, 0, 0, 0]
                                     [0, 2, 0, 0]
                                     [0, 0, 3, 0]
                                     [0, 0, 0, 4]],
                                    [[5, 0, 0, 0]
                                     [0, 6, 0, 0]
                                     [0, 0, 7, 0]
                                     [0, 0, 0, 8]]]

which has shape (2, 4, 4)
```
Numpy has an extra parameter, k. The default value of k is zero. When k=0  np.diag has the same behavior than tf.diag. However, setting k>0 (k<0) the user fill, or select, a diagonal above (below) the main diagonal.

```python
x = np.arange(9).reshape((3,3))
 np.diag(x, k=0)
#array([0, 4, 8])
np.diag(x, k=1)
# array([1, 5])
np.diag([1,5], k=1)
#array([[0, 1, 0],
#      [0, 0, 5],
#       [0, 0, 0]])
```

**Who will benefit with this feature?**
 In general, tridiagonal matrices are quite common in mathematics and physics.

**Comment by facaiy** [comment]
@rmlarsen @ebrevdo What do you think? [numpy.diag](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.diag.html)

**Comment by JCatesPH** [comment]
@rmlarsen @facaiy @ebrevdo 
Is there any progress on implementing the above request? We are currently working a project that desperately needs this. Currently, using the _kwarg_ k gives "Unexpected keyword argument k" error, despite the following documentation pages showing it as a valid keyword argument: 
[https://www.tensorflow.org/api_docs/python/tf/linalg/set_diag](url)
[https://www.tensorflow.org/api_docs/python/tf/linalg/diag](url)

**Comment by ziofil** [comment]
I had missed this feature request when I opened #31304.
I need it as well, it seems like a logical improvement of the current diagonal constructor.

**Comment by devmessias** [comment]
This functionality was recently added 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py#L1955

**Comment by devmessias** [comment]
@JCatesPH If you're really desperate I got around that

https://github.com/stdogpkg/emate/blob/0d94da36ab0f1128b5614d3176d472622e3cbc88/emate/utils/tfops/misc.py#L99

https://github.com/stdogpkg/emate/blob/0d94da36ab0f1128b5614d3176d472622e3cbc88/emate/symmetric/tfops/slq.py#L85
