### ISSUE TITLE
[Docs] Minor nit in the performance overview page

### ISSUE THREAD

**Issue by rahulunair** [tensorflow/tensorflow#25397]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.12.0
- Doc Link: https://www.tensorflow.org/guide/performance/overview

**Describe the documentation issue**
A minor nit, i the performance overview page change /Alexne**x**/Alexne**t**/

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
yes

**Comment by ymodak** [comment]
Thanks for the report. Can you please send a PR for this?
