### ISSUE TITLE
"reuse" argument in tf.layers.Dense documentation should be renamed to "_reuse"

### ISSUE THREAD

**Issue by HanGuo97** [tensorflow/tensorflow#25393]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.12
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/layers/Dense

**Describe the documentation issue**
`reuse` is no longer a valid argument, and should be replaced with `_reuse` instead. Passing reuse to Dense will cause the following error:

```python
TypeError: ('Keyword argument not understood:', 'reuse')
```
**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by facaiy** [comment]
@HanGuo97 Would you like creating a PR to fix the issue?

**Comment by Sudeepam97** [comment]
@HanGuo97 and @facaiy is anyone of you working on this issue? I am trying to start contributing to Tensorflow and this looks like a good starting point. I can work on this if it has not been assigned yet.

**Comment by facaiy** [comment]
Welcome, feel free to take a try, @Sudeepam97 . Ping me if you need any help later :-)

**Comment by HanGuo97** [comment]
My bad for the delayed response, was offline for the last couple of days due to the lunar new year, I’ll make a PR sometime today.

**Comment by Sudeepam97** [comment]
Looks like @HanGuo97 has fixed this issue. I suppose it can be closed now.

**Comment by facaiy** [comment]
Yes, thank @HanGuo97 for your contribution :-)

@Sudeepam97 I think #25564 is also a good issue for starter if you're interested in it.

**Comment by Sudeepam97** [comment]
@facaiy Thank you for pointing it out. I'll take a look at it.
