### ISSUE TITLE
Tensorflow: ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by g4usat** [tensorflow/tensorflow#25411]
Hello,
Am a newbie and just started learning about deep learning and in the process,
I've installed Tensorflow on my Windows 10 laptop(cpu only no gpu) using Anaconda3 64bit and I have python3.6.2 installed on it. I verified the installation of Tensorflow at the command prompt by typing in for c:\'activate tensorflow' and typed python at (tensorflow) C:\python to get to python shell with >>> prompt and then I had print a  'Hello' string assigned to a variable and printed it by using Session() and it displayed  successfully.

However, when I opened up my jupyter notebook from Anaconda and typed the below command  
import tensorflow as tf
tf.__version__
to verify if everything was good, it gave the below errors.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b6f7b46cc0dd> in <module>()
----> 1 import tensorflow as tf
      2 tf.__version__
ImportError: DLL load failed: The specified procedure could not be found.

I checked on google but couldn't find this error..all I saw was errors related to 'specific module could not be founded and some other error issues related to specific module. But, what am getting is 'specific procedure could not be found.

Appreciate if you can help me fix this burning issue..
Thank you!
-----------------------------------------------------------------------------------------
Error Log:
C:\Users\kshet\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py in <module>()
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 try:

C:\Users\kshet\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\__init__.py in <module>()
     57 
     58 # Protocol buffers
---> 59 from tensorflow.core.framework.graph_pb2 import *
     60 from tensorflow.core.framework.node_def_pb2 import *
     61 from tensorflow.core.framework.summary_pb2 import *

C:\Users\kshet\AppData\Roaming\Python\Python36\site-packages\tensorflow\core\framework\graph_pb2.py in <module>()
      4 import sys
      5 _b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
----> 6 from google.protobuf import descriptor as _descriptor
      7 from google.protobuf import message as _message
      8 from google.protobuf import reflection as _reflection

C:\Users\kshet\AppData\Roaming\Python\Python36\site-packages\google\protobuf\descriptor.py in <module>()
     45   import binascii
     46   import os
---> 47   from google.protobuf.pyext import _message
     48   _USE_C_DESCRIPTORS = getattr(_message, '_USE_C_DESCRIPTORS', False)
     49 

ImportError: DLL load failed: The specified procedure could not be found.

**Comment by ymodak** [comment]
Please refer this [link](http://mathalope.co.uk/2017/05/31/how-to-import-tensorflow-from-python-console-jupyter-console-qtconsole-notebook-and-ipython-notebook/)  for  importing TF in Jupyter.

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
