### ISSUE TITLE
Tensorflow Lite Multiple Choice Test example app

### ISSUE THREAD

**Issue by ArriFerrari** [tensorflow/tensorflow#25412]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I would like an example app where the user is presented with a multiple choice test, 4-5 questions. One of the questions should allow a numerical input with a decimal (float). The questions could be simple things like 2x+1=3... x=?
The example app would take these user inputs and classify the set of responses by a letter grade "A", "B", "C" or "F". After hitting a "Submit" button the app runs the model and displays a big letter grade on a new page. Then we give the user the option to re-do the test.

I could contribute a trained model from a sample data set that I could generate from test questions/answers in the desktop version of Tensorflow.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Mobile developers trying to get a handle on Tensorflow Lite. This would give a better starting point in Tensorflow Lite for passing other forms of inputs (not sensor based) through a pre-trained model. 

**Any Other info.**
This particular demo app would be more useful in its symbolic sense than the practical function.

**Comment by jvishnuvardhan** [comment]
This is a stale issue. Since the issue opened, there were lot of improvements in the TF lite guides and tutorials that can be used to accomplish your task. The following is the link to the TF Lite Guides

https://www.tensorflow.org/lite/guide/

I am closing this issue. Feel free to open a new issue if there is any specific bug or performance issue related TF lite. Thanks!
