### ISSUE TITLE
There are some error when convert Mask RCNN model to .tflite

### ISSUE THREAD

**Issue by noah003** [tensorflow/tensorflow#25415]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**: 0.22.0
- **CUDA/cuDNN version**: cuda9.0/cuDNN7.4
- **GPU model and memory**: GTX 1080/8G
- **Exact command to reproduce**:

### Describe the problem
i trained mask rcnn using object detection API, and frozen the mode successfully, but i encountered some problems when i convert  .pb file to .tflite file, following is my command

```
tflite_convert \
  --graph_def_file=/path/to/frozen_inference_graph.pb \
  --output_file=optimized_graph.lite \
  --output_format=TFLITE \
  --output_arrays=detection_masks,detection_classes,detection_boxes,detection_scores,num_detections \
  --inference_input_type=FLOAT \
  --input_shapes=1,224,224,3 \
  --input_arrays=image_tensor \
  --inference_type=FLOAT
```
the output_array is the same with output_node_names form research/object_detection/exporter.py
### Source code / logs
error
```
tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: CropAndResize_1\n2019-01-31 16:16:52.071330: I 
tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 7262 operators, 13617 arrays (0 quantized)\n2019-01-31 16:16:52.843219: I 
tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 7208 operators, 13526 arrays (0 quantized)\n2019-01-31 16:16:54.116685: I 
tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 7208 operators, 13526 arrays (0 quantized)\n2019-01-31 16:16:54.363824: F 
tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_slice.cc:59] Check failed: dim_size >= 1 (0 vs. 1)\nAborted (core dumped)\n'None
```

**Comment by ajinkya933** [comment]
Apparently it supports segmentation model trained on mobilenetv2+deeplabv3 [This is the DeepLab model trained on Cityscapes] by google. I actually tried to convert mask rcnn to TF-Lite but no luck so far. If you like here is my GitHub post for this question https://github.com/tensorflow/tensorflow/issues/27101 (http://download.tensorflow.org/models/deeplabv3_mnv2_cityscapes_train_2018_02_05.tar.gz)

**Comment by NicholaiStaalung** [comment]
@noah003 did u find a solution?

**Comment by noah003** [comment]
@NicholaiStaalung haven't not

**Comment by bmabir17** [comment]
@noah003 are you converting the mask rcnn model found in this repo https://github.com/matterport/Mask_RCNN/releases/tag/v2.0 ?

**Comment by mohantym** [comment]
Hi @noah003 ! Can you check these threads for MRCNN to tflite conversion.  [1](https://github.com/matterport/Mask_RCNN/issues/563#issuecomment-832002326),[ 2](https://github.com/matterport/Mask_RCNN/issues/563#issuecomment-571236568) . Thanks!
