### ISSUE TITLE
`tf.contrib.framework.is_tensor` is not available/exported in 2.0

### ISSUE THREAD

**Issue by darthdeus** [tensorflow/tensorflow#25418]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-dev20190126
- Python version: 3.6.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

The [tf.contrib.framework.is_tensor](https://www.tensorflow.org/api_docs/python/tf/contrib/framework/is_tensor) function is not exported in TF 2.0, even though it is defined outside of contrib in the current master version, in [tensorflow/python/framework/tensor_util.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/tensor_util.py#L935-L950).

It is neither in the [list of exported symbols](https://www.tensorflow.org/versions/r2.0/api_docs/python?hl=en), nor in [the tensorflow/addons repo](https://github.com/tensorflow/addons).

**Describe the expected behavior**

`is_tensor` should probably be exported in regular TF 2.0 API, since it is already defined outside of contrib and being used all over the place within the TF sources.

**Code to reproduce the issue**

N/A

**Other info / logs**

N/A

**Comment by alextp** [comment]
It's @tomerk who has it

**Comment by tomerk** [comment]
This has been fixed in head.
