### ISSUE TITLE
TF 2.0: Release binaries for Python 3.5 and 3.7.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25429]

**Comment by annarev** [comment]
+@dynamicwebpaige is this issue for TF 2.0 preview?

**Comment by dynamicwebpaige** [comment]
@annarev - I don't think this is a blocker for the preview; just intended to be an issue to track. Thanks for working on it! :)

(cc: @martinwicke to keep me honest)

**Comment by perfinion** [comment]
This should also list all the other projects that are required and in what order. eg: I've been looking through tensorflow/estimator and it looks like it will be required for TF2.0 (but not 1.13?).

So far it looks like:
first install: keras_applications, keras_preprocessing
build and install tensorflow/tensorflow
then tensorflow/estimator, tensorboard etc

**Comment by martinwicke** [comment]
@annarev, @goldiegadde is this done?

**Comment by dynamicwebpaige** [comment]
@martinwicke I see wheels for [Python 3.5 and Python 3.7](https://pypi.org/project/tf-nightly-gpu-2.0-preview/#files) on PyPi.

**Comment by martinwicke** [comment]
@dynamicwebpaige @annarev it seems to me this issue can be closed? Please reopen if I misunderstood.

@zh794390558 the conda packages are community supported, we do not build those.

**Comment by dsmilkov** [comment]
The Python 3.7 wheels are not present in the latest nightly (20190618): https://pypi.org/project/tf-nightly-gpu-2.0-preview/2.0.0.dev20190618/#files

But they were present in 20190314 for example: https://pypi.org/project/tf-nightly-gpu-2.0-preview/2.0.0.dev20190314/#files

This leads to the following error in MacOS with python 3.7:
```
pip install tf-nightly-2.0-preview
No matching distribution found for tf-nightly-2.0-preview
```

**Comment by feature-engineer** [comment]
https://pypi.org/project/tf-nightly-gpu-2.0-preview/#files has packages for linux only for python 2.7, 3.3, 3.4, 3.5 and 3.7 - and windows only for python 3.6 - so, Linux doesn't have a package for python 3.6 (which is the version in Ubuntu LTS repos), and windows only has a package for python 3.6...

**Comment by annarev** [comment]
I checked https://pypi.org/project/tensorflow/#files so I will assume this issue went away. Feel free to open a new bug if the issue resurfaces.
