### ISSUE TITLE
2.0 Reference Models: ResNet V1.5 (TPU with Keras)

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25435]
Deep residual networks, or ResNets for short, proposed the breakthrough idea of identity mappings in order to enable training of very deep convolutional neural networks. This issue will track the creation of 1 GPU and 8 GPU TF 2.0-compatible implementations of ResNet for the ImageNet dataset.

See the following papers for more background:

[1] [Deep Residual Learning for Image Recognition](https://arxiv.org/pdf/1512.03385.pdf) by Kaiming He, Xiangyu Zhang, Shaoqing Ren, and Jian Sun, Dec 2015.

[2] [Identity Mappings in Deep Residual Networks](https://arxiv.org/pdf/1603.05027.pdf) by Kaiming He, Xiangyu Zhang, Shaoqing Ren, and Jian Sun, Jul 2016.

For the TensorFlow 1.x equivalent, please refer [here](https://github.com/tensorflow/models/tree/master/official/resnet).

**Comment by sayoojbk** [comment]
is someone working on this issue ?

**Comment by jhseu** [comment]
Yes, it'll work soon.

**Comment by sayoojbk** [comment]
And ya could you tell me if the implementation would be similar to the GPU version ? :https://github.com/tensorflow/tensorflow/issues/25340
Actually I wanted to make changes to the identity block of resnet like changing the dilation rate of the 3x3 conv or something like that. So will such a parameter be added or something?  Cause I am actually working on a segmentation task using dilated convolution at this indentity block. If such a parameter is added it would be great if not would like to work on this task.

**Comment by dynamicwebpaige** [comment]
Closing out this issue, as ResNet support has landed.
