### ISSUE TITLE
tf.ConfigProto usage on TF 2.0

### ISSUE THREAD

**Issue by samsamoa** [tensorflow/tensorflow#25446]
On TensorFlow 1.X, there are various important parameters set by passing `tf.ConfigProto` to `tf.Session(config=...)` or `tf.enable_eager_execution(config=...)`.  For example, to use `NCCL`, it is useful to set the visible GPUs for a session with `config.gpu_options.visible_device_list`.

My understanding is that TensorFlow 2.0 no longer has a way to set this configuration — both `tf.Session` and `tf.enable_eager_execution` are gone.  Is there an alternate way to set this config?

[Related StackOverflow question](https://stackoverflow.com/questions/54485110/whats-the-equivalent-of-initializing-a-tf-session-with-tf-configproto-in-tensor)
CC @girving @allenlavoie

**Comment by dynamicwebpaige** [comment]
Potentially related: #25138.

**Comment by martinwicke** [comment]
Gaurav is working on a proper replacement, it's not ready yet, for now please use compat.v1.

**Comment by girving** [comment]
We don't know how to use `compat.v1` to do this.  If there is a way, would it be possible to answer the Stackoverflow question so that it would be possible for us to try TF 2?  The implication from @allenlavoie was that no workaround existed.

**Comment by martinwicke** [comment]
(and you should be able to use tf.compat.v1.ConfigProto to create the
config parameter)

**Comment by martinwicke** [comment]
No. We will split ConfigProto and replace it with a number of function
configuring different parts of the runtime. You can wait for that if you
want: what will definitely be true is that any future solution here will
require only a local change.

**Comment by jaingaurav** [comment]
@samsamoa: I've landed a fix to #25138. I'm continuing to work on additional config options. Could you please share which specific options are of interest to you?

**Comment by girving** [comment]
@jaingaurav I use `config.device_count['GPU']` and `config.gpu_options.visible_device_list` currently.

**Comment by cottrell** [comment]
> @samsamoa: I've landed a fix to #25138. I'm continuing to work on additional config options. Could you please share which specific options are of interest to you?

allow_growth appears to be an essential hack to fix some cudnn issue on rtx20xx devices.

config.gpu_options.allow_growth = True
config.log_device_placement = True  # to log device placement (on which device the operation ran)

**Comment by jaingaurav** [comment]
A number of new API were added in `tf.config` namespace to support this use case. Please let me know if there is anything we missed regarding this specific issue.

**Comment by opcecco** [comment]
Looks like you can do this in TF 2.0 now like this:
```
gpu_devices = tf.config.experimental.list_physical_devices('GPU')
for device in gpu_devices:
    tf.config.experimental.set_memory_growth(device, True)
```

**Comment by leimao** [comment]
Check https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth

**Comment by mehdishafiei** [comment]
@opcecco you are a lifesaver. 
Thank you.

**Comment by Kokonut133** [comment]
> Looks like you can do this in TF 2.0 now like this:
> 
> ```
> gpu_devices = tf.config.experimental.list_physical_devices('GPU')
> for device in gpu_devices:
>     tf.config.experimental.set_memory_growth(device, True)
> ```

I have placed this right before defining a keras Model() instance and compiling it. My taskmanager yet still shows that indepdently all video card memory is taken. What am I doing wrong?

**Comment by RoboEvangelist** [comment]
how do we add this in C++?

**Comment by martinwicke** [comment]
The C++ API still uses sessions, so use the session config as you would in 1.x.
