### ISSUE TITLE
Feed batch of images to Tensorflow model in Golang

### ISSUE THREAD

**Issue by anilknayak** [tensorflow/tensorflow#25441]
I have tried all the methods but did not succeed to make a batch processing of images in Go Tensorflow.

I have been following this test case for the inception model. I tried many things but did not work.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/example_inception_inference_test.go#L199

Could anyone help me? I really appreciate any help.

**Comment by ymodak** [comment]
duplicate #25440
