### ISSUE TITLE
Feature: modify the TF 2.0 upgrade script to convert .ipynb files. 

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25448]
Currently, the [TensorFlow 2.0 upgrade script](https://github.com/tensorflow/docs/blob/master/site/en/r2/guide/upgrade.md) only supports Python (`.py`) files, not Jupyter notebooks (`.ipynb`). This can make converting documentation frustrating and time consuming.

The purpose of this issue is to **modify the upgrade script to accept a Jupyter notebook, convert it from TensorFlow 1.x to TF 2.0, and to export out a replacement notebook**.

For more information, contact @VikramTiwari, @JerryKurata, and @lc0.

**Comment by dynamicwebpaige** [comment]
![image](https://user-images.githubusercontent.com/3712347/52246764-d16af380-289b-11e9-9019-eb74134f4a86.png)

**Comment by dynamicwebpaige** [comment]
Friendly reminder that @lc0 is amazing and http://tf2up.ml is something you should check out. :slightly_smiling_face: 

Closing!

**Comment by Adarsh-K** [comment]
I didn't get it, what to do exactly?
