### ISSUE TITLE
Incorrect Hann window calculation in spectrogram kernel

### ISSUE THREAD

**Issue by deeply** [tensorflow/tensorflow#25451]
**System information**
- Have I written custom code: No
- OS Platform and Distribution:  N/A
- Mobile device:  N/A
- TensorFlow installed from:  N/A
- TensorFlow version : master
- Python version:  N/A
- Bazel version:  N/A
- GCC/Compiler version:  N/A
- CUDA/cuDNN version:  N/A
- GPU model and memory:  N/A

**Describe the current behavior**
In [tensorflow/core/kernel/spectrogram.cc](https://github.com/tensorflow/tensorflow/blob/d08271d73c9f7d399d16917b47fcfda74806dd02/tensorflow/core/kernels/spectrogram.cc#L34) Hann window is calculated as blow: 
`(*window)[i] = 0.5 - 0.5 * cos((2 * pi * i) / window_length);`

**Describe the expected behavior**
According to definition of Hann window [https://en.wikipedia.org/wiki/Hann_function](https://en.wikipedia.org/wiki/Hann_function), which should be:
`(*window)[i] = 0.5 - 0.5 * cos((2 * pi * i) / (window_length - 1));`

Please correct me if I missed anything.

**Comment by petewarden** [comment]
Thanks, that's a good spot! The current behavior is inherited from some Google internal code, which we want to keep compatibility with if possible. I'm hoping the slight difference isn't causing you any issues. If it is, please add some details and reopen, thanks again for the report!

**Comment by deeply** [comment]
The difference should be all right if training and inference use the same code. Thanks for clarification.
