### ISSUE TITLE
Memory detected less than real value

### ISSUE THREAD

**Issue by REFunction** [tensorflow/tensorflow#25452]
I used tf-1.13-python. But when I ran 'tf.Session()', I found it had only 8.99GB free memory instead of 11GB, which was confirmed with 'nvidia-smi', task manager and GPU-Z.

CUDA:10.0
CUDNN:7.4.1
System:win 10

>>> tf.Session()
2019-02-02 16:02:17.833936: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that thi
s TensorFlow binary was not compiled to use: AVX2
2019-02-02 16:02:18.143034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.665
pciBusID: 0000:26:00.0
totalMemory: 11.00GiB freeMemory: 8.99GiB
2019-02-02 16:02:18.148745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-02-02 16:02:19.078669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor w
ith strength 1 edge matrix:
2019-02-02 16:02:19.081929: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-02-02 16:02:19.083860: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-02-02 16:02:19.086029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:loc
alhost/replica:0/task:0/device:GPU:0 with 8661 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus
 id: 0000:26:00.0, compute capability: 7.5)

**Comment by REFunction** [comment]
> @REFunction Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. Thanks!

**Note** that the same problem occuerred after I installed tensorflow 1.12 compiled by someone based on CUDA 10.0. So I think this problem may **not only belongs to tf-1.13rc0, but many versions on Windows platforms**. I guess perhaps Windows 10 (or more Windows versions, may be drivers) has some features to avoid that a graphics card uses too much GPU memory. As we know, there are often some programs occupying a small amount of memory, but as for me, other programs only consume almost 100MB while 2GB cannot be  thought available. So strange, right?

**I am sorry for not providing details. You can get them below.**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 1809 17763.107
- TensorFlow installed from (source or binary):"pip3 install tensorflow-gpu==1.13rc0"
- TensorFlow version:1.13rc0
- Python version:3.6.8
- Installed using virtualenv? pip? conda?:pip
- CUDA/cuDNN version:CUDA 10.0 cnDNN 7.4.2
- GPU model and memory:Don't understand but 2080ti 11GB



**Describe the problem**：Finished above

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Finished above, just tf.Session()


**Any other info / logs**
No.

**Comment by smit-hinsu** [comment]
This issue is discussed on the NVIDIA forum and seems to be a known issue with windows.
https://devtalk.nvidia.com/default/topic/996667/gtx-980ti-6gb-only-have-4-97gb-memory-available-with-win10-64/
