### ISSUE TITLE
Feature: Update the environment capture script for system information.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25461]
The current [**environment capture script for TensorFlow**](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh) does not provide all of the system information required for filing bug or performance issues:

- **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04)
- **Mobile device** (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device
- TensorFlow installed from (**source or binary**)
- **TensorFlow version** (use command below)
- **Python** version
- **Bazel** version (if compiling from source)
- **GCC/Compiler** version (if compiling from source)
- **CUDA/cuDNN** version
- **GPU model** and memory

The purpose of this issue would be to modify the environment capture script to print as much of the information above as possible to an end user's console, or to create an extension of the TensorFlow Python API (similar to fastai's [`collect_env.py`](https://github.com/fastai/fastai/blob/110d29d7a407409399c77916b2453e7408a3a450/fastai/utils/collect_env.py) that accomplishes the same goal.

**Comment by a6802739** [comment]
@dynamicwebpaige  is this appropriate for a beginner to try for the first contribution?

I'm interested in this, hope I could get some advice and tackle this issue.

**Comment by dynamicwebpaige** [comment]
@a6802739 - thanks for the offer to upgrade the environment capture script! 😊

Adding information for one or more of the bullet-points above (or even comments describing what the current upgrade script does, line by line!) would be a great first issue, and I'd be happy to chat about next steps. Please feel free to send me an email ([webpaige@google.com](mailto:webpaige@google.com)).

**Comment by a6802739** [comment]
@dynamicwebpaige , Thank you very much, I will try to add one system information for the current `environment capture script` first.
 And I will ask for your help if I met some problems, hope it wouldn't bother you too much.
Thank you again.

**Comment by scouvreur** [comment]
Hi @a6802739 - can I give you some help on this issue ?

**Comment by scouvreur** [comment]
Sure ! I will work on the GCC/Compiler, CUDA/cuDNN versions and the GPU model and memory

**Comment by Ryan-Qiyu-Jiang** [comment]
I made a pr for 
* TensorFlow installed from (**source or binary**)
* **Python** version
* **Bazel** version (if compiling from source)
https://github.com/tensorflow/tensorflow/pull/25673

tensorflow version seemed already part of output,
wasn't sure how to confirm source or binary so I added location install info,
if it's installed under python/site-packages it's a good sign tf was installed from binary

didn't add unit tests
pls let me know if I need to correct anything, first contrib too :p

**Comment by scouvreur** [comment]
Hi @dynamicwebpaige, I just submitted a pull request #25679 with the features I mentioned above

**Comment by dynamicwebpaige** [comment]
Thanks so much for your contributions! We appreciate it - and including this information in the environment capture script will certainly help folks who are filing issues. 🙏 

(cc: @martinwicke @alextp)

**Comment by a6802739** [comment]
@dynamicwebpaige, I have submitted a pull request #25833, please have a look at that. Thanks!

**Comment by josiahbjorgaard** [comment]
@dynamicwebpaige @a6802739 @scouvreur 
Is there anything left to do for this issue?

**Comment by ymodak** [comment]
Closing this issue since the PR has merged. Thanks!
