### ISSUE TITLE
Confusing embedding_lookup docstring, incorrect use of the word "partition"

### ISSUE THREAD

**Issue by kuprel** [tensorflow/tensorflow#2547]
The wording in the docstring for nn.embedding_lookup is confusing and refers to subsets as partitions (https://www.tensorflow.org/versions/r0.8/api_docs/python/nn.html#embedding_lookup)

A partition of a set X is a set of nonempty subsets of X such that every element x in X is in exactly one of these subsets (https://en.wikipedia.org/wiki/Partition_of_a_set)

Here is an example of incorrect usage:
"For instance, 13 ids are split across 5 partitions as: [[0, 5, 10], [1, 6, 11], [2, 7, 12], [3, 8], [4, 9]]"
That is actually 1 partition of the 13 ids, not 5 partitions.

And this is just really confusing:
"If len(params) > 1, each element id of ids is partitioned between the elements of params according to the partition_strategy. In all strategies, if the id space does not evenly divide the number of partitions, each of the first (max_id + 1) % len(params) partitions will be assigned one more id."

**Comment by aselle** [comment]
It's an interesting point. It is true that the mathematical definition of a partition is as you say. On the other hand the idea that a partition is actually synonymous with "disjoint subset" is actually really common in CS. Consider disk partitions and memory partitions where a "disk partition" is considered the subset of the disk. So I'm not sure... someone who thinks about things from that common usage would find this totally clear.

The argument for changing it is that the documentation sort of uses both interpretations.  "This function is used to perform parallel lookups on the list of tensors in params. It is a generalization of tf.gather(), where params is interpreted as a partition of a larger embedding tensor."  Here we should probably say "interpreted as partitions of a larger embedding tensor" to be consistent with the CS common usage.

**Comment by aselle** [comment]
Closing automatically due to lack of recent activity.
