### ISSUE TITLE
tf2.0 - tf.keras.optimizers.Optimizer.get_updates() does not work

### ISSUE THREAD

**Issue by ZhiqingXiao** [tensorflow/tensorflow#25472]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux-4.14.79+-x86_64-with-Ubuntu-18.04-bionic
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-dev20190203
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
When keras optimizer's get_updates() function is called, it raises error "RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead."

**Describe the expected behavior**
I expect it returns correct operators that can be used to build keras function that changes weights.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
from tensorflow import keras
model = keras.Sequential()
model.add(keras.layers.Dense(1, input_shape=(1,)))
model.compile(optimizer='adam', loss='mse')
loss = keras.losses.mse(model.input, model.output)
updates = model.optimizer.get_updates(params=model.trainable_weights, loss=loss)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Traceback:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-f4bb57df0d91> in <module>()
      5 loss = keras.losses.mse(model.input, model.output)
      6 model.optimizer.get_updates(
----> 7         params=model.trainable_weights, loss=loss)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py in get_updates(self, loss, params)
    440 
    441   def get_updates(self, loss, params):
--> 442     grads = self.get_gradients(loss, params)
    443     grads_and_vars = list(zip(grads, params))
    444     self._assert_valid_dtypes([

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py in get_gradients(self, loss, params)
    353     """
    354     loss = self._scale_loss(loss)
--> 355     grads = gradients.gradients(loss, params)
    356     if None in grads:
    357       raise ValueError("An operation has `None` for gradient. "

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_impl.py in gradients(ys, xs, grad_ys, name, colocate_gradients_with_ops, gate_gradients, aggregation_method, stop_gradients, unconnected_gradients)
    156         ys, xs, grad_ys, name, colocate_gradients_with_ops,
    157         gate_gradients, aggregation_method, stop_gradients,
--> 158         unconnected_gradients)
    159   # pylint: enable=protected-access
    160 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_util.py in _GradientsHelper(ys, xs, grad_ys, name, colocate_gradients_with_ops, gate_gradients, aggregation_method, stop_gradients, unconnected_gradients, src_graph)
    545   """Implementation of gradients()."""
    546   if context.executing_eagerly():
--> 547     raise RuntimeError("tf.gradients is not supported when eager execution "
    548                        "is enabled. Use tf.GradientTape instead.")
    549   if src_graph is None:

RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.
```

**Comment by ymodak** [comment]
This is fixed TF 2.0 nightly '2.0.0-dev20190718' 
Thanks!
