### ISSUE TITLE
tf.distribution.Normal memory leak on calls to sample() 

### ISSUE THREAD

**Issue by brancoliticus** [tensorflow/tensorflow#25473]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
- TensorFlow installed from (source or binary):
pip3 installation
- TensorFlow version (use command below):
12.0
- Python version:
3.6.7

**Describe the current behavior**
Type in the code below and watch memory usage increase.

**Describe the expected behavior**
Type in the code below and see no memory usage increases.

**Code to reproduce the issue**

    import tensorflow as tf

    dist=tf.distributions.Normal(loc=0., scale=1.)

    for i in range(1_000_000):
        a=dist.sample()

**Comment by brancoliticus** [comment]
I thought it was a good repro for a problem in a 300 lines of code program, but seems like I'll just have to search for another way to give a reasonable reproduction.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
