### ISSUE TITLE
C- How to draw bounding-box using tensorflow c_api

### ISSUE THREAD

**Issue by Ashokcharu** [tensorflow/tensorflow#25480]
### In python 
I did object detection, Its working fine. Same thing I want to do in C

Here is the code to detect the object object in python

Calling boxes, like following:

```
image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
detection_boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
detection_scores = detection_graph.get_tensor_by_name('detection_scores:0')
detection_classes = detection_graph.get_tensor_by_name('detection_classes:0')
num_detections = detection_graph.get_tensor_by_name('num_detections:0')
```
similarly for scores, and classes.

Then just called them in session run.

```
(boxes, scores, classes, num) = sess.run(
    [detection_boxes, detection_scores, detection_classes, num_detections],
    feed_dict={image_tensor: image_expanded})
```
Now Drawing the results of the detection

```
vis_util.visualize_boxes_and_labels_on_image_array(
    image,
    np.squeeze(boxes),
    np.squeeze(classes).astype(np.int32),
    np.squeeze(scores),
    category_index,
    use_normalized_coordinates=True,
    line_thickness=8,
    min_score_thresh=0.80)
```
Now I can able to view the image and detect the object(face).

`cv2.imshow('Object detector', image)`

Question :

**C language**

Now my question is how can I Feed the image data's into graph and detect the object in that image as well as draw the rectangle box using C Programming.

**Comment by jvishnuvardhan** [comment]
Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Thanks!

**Comment by Ashokcharu** [comment]
Above I had explained everything????

I got the graph data from the trained graph.

Then I passed both image data and graph data into **TF_SessionRun** . After done passing data's, When I view ` cvShowImage("Face Detection", img);`. It's not detecting the face.

Above I posted my full code please check.

Atleast, If any one will give idea!!!, That will be great help.

Thanks

**Comment by tika64208** [comment]
TF_Tensor * imgTensor = TF_NewTensor(TF_UINT8, dims, 4, img->imageData, img->imageSize, &deallocator, NULL);
try "img->imageData"

**Comment by Ashokcharu** [comment]
@tika64208  It's not working....

**Comment by tika64208** [comment]
Have you solved your problem？

 a similar problem  puzzle me 

`#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "c_api.h"


#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

TF_Buffer* read_file(const char* file);  
void free_buffer(void* data, size_t length) { free(data); }
void deallocator(void* ptr, size_t len, void* arg) { free((void*)ptr); }


TF_Buffer* read_file(const char* file) {     
    printf("debug %s  %d \n",file,__LINE__);                                             
  FILE *f = fopen(file, "rb");
  
  
    printf("debug %p  %d \n",f,__LINE__);
  fseek(f, 0, SEEK_END);
  long fsize = ftell(f);                                                                  
  fseek(f, 0, SEEK_SET);  //same as rewind(f);                                            

    printf("debug  %d \n",__LINE__);
  void* data = malloc(fsize);                                                             
  fread(data, fsize, 1, f);
  fclose(f);

    printf("debug  %d \n",__LINE__);
  TF_Buffer* buf = TF_NewBuffer();                                                        
  buf->data = data;
  buf->length = fsize;                                                                    
  buf->data_deallocator = free_buffer;                                                    
  return buf;
}	

int testgettensor(char* filepath)
{
	
    printf("debug  %d \n",__LINE__);
	TF_Buffer* graph_def = read_file("./model.pb");   
  printf("graph_def %p \n",graph_def);                   
  TF_Graph* graph = TF_NewGraph();
  TF_Status* status = TF_NewStatus();                                                     
  TF_ImportGraphDefOptions* opts = TF_NewImportGraphDefOptions();                        
  TF_GraphImportGraphDef(graph, graph_def, opts, status);
  TF_DeleteImportGraphDefOptions(opts);
  if (TF_GetCode(status) != TF_OK) {
          fprintf(stderr, "ERROR: Unable to import graph %s\n", TF_Message(status));        
          return 1;
  }
  
  fprintf(stdout, "Successfully imported graph\n");                                          
  TF_SessionOptions* opt = TF_NewSessionOptions();
  TF_Session* sess = TF_NewSession(graph, opt, status);
  //TF_DeleteSessionOptions(opt);
  if (TF_GetCode(status) != TF_OK) {
    fprintf(stderr, "ERROR: Unable to create session %s\n", TF_Message(status));
    return 1;
  }
  fprintf(stdout, "Successfully session created\n");



	int w, h, n;
	float *data = stbi_loadf(filepath, &w, &h, &n, 0);
	 if(!data) {
    printf("Failed to laodiamge");
  }
  
  
    printf("debug  %d \n",__LINE__);
  int64_t dims[] = {1, w, h, n };
  float tmpdata[100*100*3]={0};
  
	TF_Tensor * imgTensor = TF_NewTensor(TF_FLOAT, dims, 4, data, w*h*n*sizeof(float), &deallocator, NULL);


    printf("debug  %d \n",__LINE__);
  
  TF_Operation* input_image_op = TF_GraphOperationByName(graph, "x");
  if(!input_image_op) {
    printf("Failed to find Op '%s'", "image_tensor");
    return 1;
  }
  
    printf("debug  %d \n",__LINE__);
  TF_Output image_input;
  image_input.oper = input_image_op;
  image_input.index = 0;
  TF_Output inputs[1] = {image_input};
  
  
  
  TF_Operation* logits_eval_op = TF_GraphOperationByName(graph, "logits_eval");
  if(!logits_eval_op) {
    printf("Failed to find Op '%s'", "num_detections");
    return 1;
  }
  TF_Output num_detection_output;
  num_detection_output.oper = logits_eval_op;
  num_detection_output.index = 0;
  TF_Output outputs[1] = {num_detection_output};
  TF_Tensor* output_tensors[1];
  
  TF_SessionRun(sess, NULL, 
                &image_input, &imgTensor, 1,
                outputs, output_tensors, 1,
                NULL, 0,
                NULL, status);
                
               
	printf("TF_SessionRun: %s\n", TF_Message(status));
	  if(TF_GetCode(status) != TF_OK) {
    printf("It's coming here");
    printf("%s\n", TF_Message(status));
  }
  else {

    printf("Ran successfully\n");
    float* f = (float*)TF_TensorData(output_tensors[0]);
    printf("TF data %f\n", f[0]);
    printf("TF data %f\n", f[1]);
    printf("TF data %f\n", f[2]);
    printf("TF data %f\n", f[3]);
    printf("TF data %f\n", f[4]);
    
    printf("TF data %d\n", TF_TensorType(output_tensors[0]));

  
  
  return 0;
}

int main(int argc, char** argv) {
    printf("Hello from TensorFlow C library version\n");
    
    printf("Failed to laodiamge\n");
    testgettensor(argv[1]);
   // testLoadModel();
    return 0;
}
`
this code can run ,but wrong result

**Comment by sanatmpa1** [comment]
@Ashokcharu ,

From your codes, I think you were using `TF 1.X` version and its officially considered as end of life, can you update to recent stable version `2.6.0` and let us know if the problem still persists. Here's a [documentation](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/draw-bounding-boxes) of drawing bounding boxes using C++ API. Let us know if it helps. Thanks!
