### ISSUE TITLE
Build tensorflow from source[centos]

### ISSUE THREAD

**Issue by jw447** [tensorflow/tensorflow#25499]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: v1.12.0
- Python version: 3.5
- Installed using virtualenv? pip? conda?: none
- Bazel version (if compiling from source): 0.18.0
- GCC/Compiler version (if compiling from source): GCC8.2.0
- CUDA/cuDNN version: cudatoolkit9.1/cudnn7.4.2
- GPU model and memory:
K20

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I've finished `./configure` and trying to `bazel test` or `bazel build` as instructed in manual.

When I tried to `bazel test` with `bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/lite/...`, I got the following error message [gist](https://gist.github.com/jw447/a191d193b17926fd98f23ce1232d3d28)

When I tried to 'bazel build' with `bazel build --config=opt --config=mkl --config=monolithic --config=cuda //tensorflow/tools/pip_package:build_pip_package`, I got the following error message [gist](https://gist.github.com/jw447/bdfb2aef5dddc2552958115e5cc21f4b).

For the second problem, installing a newer version of glibc is temporarily unavailable. I'm wondering if both questions are triggered by the same reason, the version of glibc?

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by goern** [comment]
@sub-mod could you have a look at this, why have we not build a py35 wheel file?

**Comment by gunan** [comment]
Now that we have the manylinux 2010 packages, they should work out of the box with centos 6 or later.
Anything older may not work.
