### ISSUE TITLE
edit_distance_op.cc contains suspicious explicit divide by zeros

### ISSUE THREAD

**Issue by cg31** [tensorflow/tensorflow#2550]
In edit_distance_op.cc, there are several code pieces like:

if (normalize_) output_t(loc) /= 0.0;

is there any specific purpose doing that? As I know, dividing by 0 is not an advocated idea.

**Comment by vrv** [comment]
uh, good question.  @ebrevdo

**Comment by ebrevdo** [comment]
Probably a bug. Will take a closer look on Monday.

**Comment by ebrevdo** [comment]
Working on this now.

**Comment by ebrevdo** [comment]
Fixed at head.
