### ISSUE TITLE
ROCm build doesn't detect GPU

### ISSUE THREAD

**Issue by Dekken** [tensorflow/tensorflow#25527]
**System information**
- OS Platform and Distribution  Ubuntu 18.10
- TensorFlow installed from source
- TensorFlow version tensorflow-1.13.0rc0-cp36-cp36m-linux_x86_64.whl
- Python version: 3.6
- Installed using pip with wheel built from source:
- Bazel version 0.21:
- GCC/Compiler version 8.2:
- CUDA/cuDNN version N/A:
- GPU model and memory: AMD Vega RX 64 

**Describe the problem**

Selecting ROCm in "./configure" doesn't find GPU in "tf.session()"

**Comment by jvishnuvardhan** [comment]
@Dekken Were you able to successfully install tf_gpu? I have followed the following [resource](https://github.com/rnreich/ubuntu-tensorflow-gpu-all-versions) and installed tf_gpu successfully. Could you try it. You might need to modify few things like CUDA version and drivers etc. Please let me know how it progresses. Thanks!

**Comment by Dekken** [comment]
I can install the ROCM deb file and it's fine, but I think that link is sure for Nvidia GPUs no?

**Comment by whchung** [comment]
logic for ROCm in upstream TensorFlow is not complete yet, to the very least we need #25596 in.
For now please use downstream fork from AMD at: https://github.com/ROCmSoftwarePlatform/tensorflow-upstream

**Comment by Dekken** [comment]
fair enough, just seems a bit odd to have the config option IMO
