### ISSUE TITLE
Normal.log_cdf raises exception when called with float64

### ISSUE THREAD

**Issue by Gonzalo933** [tensorflow/tensorflow#25520]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): 
Binary (pip)
- TensorFlow version (use command below): 
v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 
Python 3.6.4 :: Anaconda, Inc.

**Describe the current behavior**

Calling Normal.log_cdf(x) with a float64 raises a TypeError exception.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
import tensorflow as tf

normal = tf.distributions.Normal(loc=0.0, scale=1.0)
normal.log_cdf(tf.constant(3.5, dtype=tf.float32))  # Operation created successfully as expected
normal.log_cdf(tf.constant(3.5, dtype=tf.float64))  # Exception
```

Exception is:

> TypeError: Input 'y' of 'Sub' Op has type float32 that does not match type float64 of argument 'x'.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[trace.txt](https://github.com/tensorflow/tensorflow/files/2831779/trace.txt)

**Comment by ebrevdo** [comment]
(probably you want loc=np.float64(0.0), scale=np.float(1.0)) to make the Normal distribution's dtype float64.

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25520)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25520)
