### ISSUE TITLE
local_conv1d and local_conv2d are missing from the tensorflow.keras.backend namespace.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [tensorflow/tensorflow#25546]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Keras-team/keras provides `local_conv1d` and `local_conv2d` in `keras.backend`. tf.keras doesn't expose them. It's a compatibility issue between keras and tensorflow.keras. See https://keras.io/backend/ .

**Will this change the current api? How?**

It will add two functions to `tensorflow.keras.backend`

**Who will benefit with this feature?**

In keras-contrib, we expect keras and tf.keras to have the same public API. If the two are not compatibles, there are things that we can't do. 

**Any Other info.**

**Comment by yongtang** [comment]
@gabrieldemarmiesse Added a PR #25556 to export `local_conv1d` and `local_conv2d` in `tf.keras.backend`.
