### ISSUE TITLE
Virtualenv installation failure

### ISSUE THREAD

**Issue by yayosh** [tensorflow/tensorflow#2554]
Environment info
Operating System: OS X 10.10.3

We followed the "Download and Setup" docs and tried to create a Virtualenv environment in the directory ~/tensorflow but it didn't work well.

```
$ virtualenv --system-site-packages ~/tensorflow

Using base prefix '/Applications/Canopy.app/appdata/canopy-1.7.2.3327.macosx-x86_64/Canopy.app/Contents'
New python executable in /Users/xxx/tensorflow/tensorflow/bin/python
dyld: Library not loaded: @rpath/Python
  Referenced from: /Users/xxx/tensorflow/tensorflow/bin/python
  Reason: no suitable image found.  Did find:
    /Users/xxx/tensorflow/tensorflow/bin/../Python: not a file
ERROR: The executable /Users/xxx/tensorflow/tensorflow/bin/python is not functioning
ERROR: It thinks sys.prefix is u'/Users/xxx/tensorflow' (should be u'/Users/xxx/tensorflow/tensorflow')
ERROR: virtualenv is not compatible with this system or executable
```

In my execution environment, -p option is needed as below.

```
  $ virtualenv --system-site-packages -p /Library/Frameworks/Python.framework/Versions/3.5/bin/python3 ~/tensorflow
```

I think the result of the above command is influenced by the execution environment, so please add the -p option.

**Comment by aselle** [comment]
It seems like you must have installed Python 3 on your own before installing tensorflow. On my El Capitan machine I do not have /Library/Frameworks/Python.framework at all. Could you let me know how you did that so I can attempt to reproduce this.

**Comment by girving** [comment]
Closing for now, but please comment if more information is available and I'm happy to reopen.

**Comment by jkjangles** [comment]
I came across this thread while trying to solve my issue. Checking to see if this has a solution. On my OS Sierra 10.12.3 machine, I have Conda 1.4.3 (python 3.x) installed. Thanks.

**Comment by yuanzhong90** [comment]
I have the same question with @jkjangles . On my OS Sierra 10.12.3 machine, I have Conda 4.3.16, python 3.5.2 installed. Thanks a lot. Has @jkjangles solved this problem?

**Comment by jkjangles** [comment]
Yes, it is solved. install via conda.

**Comment by leonlee723** [comment]
virtualenv --system-site-packages -p /System/Library/Frameworks/Python.framework/Versions/3.6/bin/python3 /Users/lile/developer/TensorFlow
Running virtualenv with interpreter /System/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
Using base prefix '/System/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/lile/developer/TensorFlow/bin/python3
Also creating executable in /Users/lile/developer/TensorFlow/bin/python
ERROR: The executable /Users/lile/developer/TensorFlow/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/System/Library/Frameworks/Python.framework/Versions/3.6' (should be '/Users/lile/developer/TensorFlow')
ERROR: virtualenv is not compatible with this system or executable

**Comment by everttrollip** [comment]
If you are still struggling, and experiencing this issue:

`ERROR: virtualenv is not compatible with this system or executable`

Have you tried installing virtualenv with conda and trying again?

`conda install virtualenv`
