### ISSUE TITLE
input_shapes error converting model to tflite

### ISSUE THREAD

**Issue by GustavZ** [tensorflow/tensorflow#25549]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS High Sierra
- TensorFlow installed from (source or binary): over pip
- TensorFlow version (use command below): 1.12
- Python version: 3.6.5
- Bazel version (if compiling from source): 0.22.0

I get an error when converting a modified mobilenet_v1 (posenet to be exact)  frozen graph (.pb) with `input_shapes={'image':[1,225,225,3]} `to tflite.
When changing it to [1,224,224,3] it works.
I am using the function `tf.contrib.lite.TocoConverter.from_frozen_graph()`

The error is:
```
I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 213 operators, 318 arrays (0 quantized)\n2019-02-06 13:28:17.720907: 
I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 213 operators, 318 arrays (0 quantized)\n2019-02-06 13:28:17.732215: 
F tensorflow/contrib/lite/toco/graph_transformations/propagate_fixed_sizes.cc:991]  Check failed: height_with_paddings % block_height == 0 (1 vs. 0)\n'
None
```

**Comment by andrehentz** [comment]
See https://github.com/tensorflow/tensorflow/issues/23600 for a possible dupe.

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25549)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25549)

**Comment by sjoshi30** [comment]
Hi @gustavz, Were you able to solve this issue ? 
I am also getting this error. I can convert with 224 but the accuracy is greatly affected.
