### ISSUE TITLE
No TF import library to link custom operators on Windows

### ISSUE THREAD

**Issue by evgal** [tensorflow/tensorflow#25551]
I cannot reopen the issue here: https://github.com/tensorflow/tensorflow/issues/23740

But the issue persists, the file is still missing in the pip package as of today in TensorFlow 1.12.

Could you please reintroduce the library _pywrap_tensorflow_internal.lib in the pip pickage ? It is required to build custom ops on Windows platform.

Thanks,

**Comment by ymodak** [comment]
@meteorcloudy Can you PTAL? Thanks!

**Comment by meteorcloudy** [comment]
@evgal This issue is fixed by https://github.com/tensorflow/tensorflow/commit/4beea30ec8a231a12b9183f631608a6af64b8172, but it will only be released in 1.13

You can also cherry-pick this commit to build your own TF pip package that contains the import library.

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25551)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25551)
