### ISSUE TITLE
TensorRT version in  TensorFlow 1.13.0-rc0 ?

### ISSUE THREAD

**Issue by rohith14** [tensorflow/tensorflow#25559]
What version of TensorRT does TensorFlow 1.13.0-rc0 support?  I don't see any mention about TensorRT in the release notes [link](https://github.com/tensorflow/tensorflow/releases/tag/v1.13.0-rc0)

Thanks

**Comment by ymodak** [comment]
@samikama Can you PTAL? Thanks!

**Comment by pooyadavoodi** [comment]
The GPU builds of 1.13 are built against TRT5.0, but TRT4 is also supported.

**Comment by ymodak** [comment]
Closing this issue since it was answered by @pooyadavoodi . Feel free to reopen if have any folow up questions. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25559)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25559)

**Comment by rohith14** [comment]
Thanks
