### ISSUE TITLE
ImportError: No module named 'tensorflow' in official Docker image

### ISSUE THREAD

**Issue by fx-practic** [tensorflow/tensorflow#25558]
**System information**
- Windows 10 x64:
- Official tensorflow-jupiter Docker container (without GPU support), latest 06 Feb 2019
- TensorFlow version: unable to know
- Python version: sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)

**Describe the problem**
`import tensorflow as tf ` command causing this error:

> ImportError                               Traceback (most recent call last)
> <ipython-input-7-7f6e5ebe327b> in <module>()
> ----> 1 import tensorflow as tf
> ImportError: No module named 'tensorflow'
>

**Comment by fx-practic** [comment]
UPD: 6 Feb 2019 11:06 PM GMT docker image updated, but it not helps.

**Comment by angersson** [comment]
There was a bug in our Docker CI scripts that pushed broken images. Now that they've been fixed, I verified that this works on Linux:

```
docker run -it --rm tensorflow/tensorflow:latest-jupyter python -c 'import tensorflow as tf'
```

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25558)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25558)

**Comment by dearboll** [comment]
I found the same error with 
`docker run -it --rm tensorflow/tensorflow:devel-gpu  python -c 'import tensorflow as tf'`

**Comment by angersson** [comment]
@dearboll The `devel` tags are for developers to make changes *to* TensorFlow. They do not have TensorFlow installed by default.

**Comment by dearboll** [comment]
@angersson Got it. Thanks a lot.

**Comment by KaramAbuaisha** [comment]
@angersson I'm new to this and I had the same issue - `ImportError: No module named tensorflow`... how can install tensorflow in the devel images? I would like to test the changes I've made which are only changing ` ENV TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,6.1,7.0 ` to include 5.0

**Comment by pesekon2** [comment]
Today I have pulled a TF image and the problem still seems to be there. 
Image: `tensorflow/tensorflow:devel-gpu-py3`
System: `Debian 10`

I can install tensorflow-gpu through pip inside the container, but I would expect it to be already installed as it is a TF image.

**Comment by sandeepsinghsengar** [comment]
@angerson but how to chnage the gpu version under docker run -it --rm tensorflow/tensorflow:latest-jupyter. I would like to work on tensorflow 2.2.0, but it is providing only tf 2.4.1
