### ISSUE TITLE
When using MirroredStrategy in keras, custom callbacks receive an incorrect model instance 

### ISSUE THREAD

**Issue by ksachdeva** [tensorflow/tensorflow#25569]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9
- GPU model and memory:

**Describe the current behavior**

A keras custom callback typically has an access to the "model" object. There are many use cases where the access to model in a callback is required. 

When MirroredStrategy is used there is still access to "model" object however its type is not `tf.keras.models.Model` rather it is `DistributedModel`

When training such a model tensorflow generates following warnings -

```
WARNING:tensorflow:Your input callback is not one of the predefined Callbacks that supports DistributionStrategy. You might encounter an error if you access one of the model's attributes as part of the callback since these attributes are not set. You can access each of the individual distributed models using the `_grouped_model` attribute of your original model.
```

Inside the custom callback in this scenario self.model.layers is set to [] i.e. length is zero.

**Describe the expected behavior**

There are couple of issues with the existing behavior -:

a) Ideally one should not be required to change the code in the callbacks. But that is an ideal situation; it is understandable to some extent that in cases such as MirroredStrategy a custom callback may require extra conditions.

b) However, what is strange or rather would be considered  ill advised is the warning generated by tensorflow i.e. "You can access each of the individual distributed models using the `_grouped_model` attribute of your original model"

The warning seems to suggest that one should try to access an `undocumented` and `private` property of an object. 

Also there is no `_grouped_model` attribute on self.model anyways; the one that I see is `_original_model`

That said, the expected behavior is to document if a custom callback is to be designed considering some of the caveats when using MirroredStrategy and provide a public attribute and/or method to have access to the original model.

**Code to reproduce the issue**

Here is an example created to reproduce this behavior (with the workaround) -

https://github.com/ksachdeva/tensorflow-bugs/tree/mirroredstrategy-model-access-in-callback

**Comment by koon-kai** [comment]
Same question.

**Comment by RitchieAlpha** [comment]
Same Question

**Comment by anj-s** [comment]
ksachdeva@ we have a new scope API that you can use that might help with this issue. You instantiate a strategy and open a scope. Within this scope you define and compile your Keras model. Here is an example of its usage: https://www.tensorflow.org/tutorials/distribute/keras#keras_api

Please reopen if you still run into issues with a custom callback model. Thanks!
