### ISSUE TITLE
Can LSTM be fully quantized for inference?

### ISSUE THREAD

**Issue by bkanaki** [tensorflow/tensorflow#25563]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (or github SHA if from source): 1.13.0-rc0

**Problem Summary and Errors Encountered**

I am trying to have the LSTM version from TFLite ([here](https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/lite/experimental/examples/lstm/tflite_lstm.py)) quantized for inference through TFLite. 

I use `tf.contrib.quantize.create_training_graph()` for training and have added fake quant node after the input. But I think the use of `tf.unstack()` creates a problem when using the 'static_rnn()`

The model is as below:

```
input_frequency_size = model_settings['dct_coefficient_count']
input_time_size = model_settings['spectrogram_length']
fingerprint_4d = tf.reshape(fingerprint_input, 
                              [-1, input_time_size, input_frequency_size])
num_classes = model_settings['label_count']
projection_units = model_size_info[0]
LSTM_units = model_size_info[1]
with tf.name_scope("LSTM-Layer"):
  with tf.variable_scope("lstm"):
    lstm_cell = TFLiteLSTMCell(num_units=LSTM_units,
                                 use_peepholes=True,
                                 num_proj=projection_units)
    lstm_input = tf.unstack(fingerprint_4d, input_time_size, 1)
    # lstm_input = tf.fake_quant_with_min_max_args(lstm_input)
    _, last = tf.nn.static_rnn(cell=lstm_cell, inputs=lstm_input,
                                   dtype=tf.float32)
    # tf.quantization.fake_quant_with_min_max_args(last)
    flow = last[-1]

with tf.name_scope("Output-Layer"):
  W_o = tf.get_variable('W_o', shape=[projection_units, num_classes],
                          initializer=tf.contrib.layers.xavier_initializer())
  b_o = tf.get_variable('b_o', shape=[num_classes],
                          initializer=tf.constant_initializer(0.01))
  logits = tf.add(tf.matmul(flow, W_o), b_o)
```

After training, I freeze the graph and use the following script to convert to TF lite:

```
graph_def_file = "frozen_graph.pb"  # This is the .pb file.
input_arrays = ["mfcc_data"]            # This is the name of the input node
output_arrays = ["labels_softmax"]  # This is the name of the output node

# This is the main code to call tflite converter (i.e. toco)
converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
# Since fake quantization used during training, we can quantize the graph during converting
converter.inference_type = tf.lite.constants.QUANTIZED_UINT8
converter.reorder_across_fake_quant = True
input_arrays = converter.get_input_arrays()
converter.quantized_input_stats = {input_arrays[0] : (227., 1.)}  # mean, std_dev
tflite_model = converter.convert()
open("lstm-tflite.tflite", "wb").write(tflite_model)   # The resulting .tflite file.
```

But this then gives error as below:
```
ConverterError: TOCO failed. See console for info.
2019-02-06 11:57:30.492529: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1098 operators, 1429 arrays (0 quantized)
2019-02-06 11:57:30.560084: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1098 operators, 1429 arrays (0 quantized)
2019-02-06 11:57:30.646273: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 573 operators, 853 arrays (1 quantized)
2019-02-06 11:57:30.675022: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 573 operators, 853 arrays (1 quantized)
2019-02-06 11:57:30.686976: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After pre-quantization graph transformations pass 1: 522 operators, 802 arrays (1 quantized)
2019-02-06 11:57:30.703210: F tensorflow/lite/toco/tooling_util.cc:1702] Array LSTM-Layer/lstm/unstack, which is an input to the Concatenation operator producing the output array LSTM-Layer/lstm/rnn/tf_lite_lstm_cell/concat, is lacking min/max data, which is necessary for quantization. If accuracy matters, either target a non-quantized output format, or run quantized training with your model from a floating point checkpoint to change the input graph to contain min/max information. If you don't care about accuracy, you can pass --default_ranges_min= and --default_ranges_max= for easy experimentation.
```

I try to add the fake quant nodes manually after the unstack as you can see in the commented code above, but this will give an error from `static_rnn` because it will not remain a sequence anymore resulting in the following error while training:

```
Traceback (most recent call last):
  File "train.py", line 324, in <module>
    tf.app.run(main=main)
  File "C:\Users\bhargav\AppData\Local\Continuum\miniconda3\envs\tf113cpu\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 140, in main
    logits, dropout_prob = models.create_model(
  File "C:\Users\bhargav\Documents\audio\keyword-spotting\models.py", line 58, in create_model
    model_size_info, is_training)
  File "C:\Users\bhargav\Documents\audio\keyword-spotting\models.py", line 198, in create_lstm_tflite_model
    dtype=tf.float32)
  File "C:\Users\bhargav\AppData\Local\Continuum\miniconda3\envs\tf113cpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\bhargav\AppData\Local\Continuum\miniconda3\envs\tf113cpu\lib\site-packages\tensorflow\python\ops\rnn.py", line 1290, in static_rnn
    raise TypeError("inputs must be a sequence")
TypeError: inputs must be a sequence
```

I want to know if the full quantization of LSTM will be supported any time in near future. If GraphDef is needed, let me know.

**Comment by bkanaki** [comment]
Is there any update on this? Please let us know.

**Comment by ebrevdo** [comment]
@aselle ptal?

**Comment by xddkdx** [comment]
Hi all,
Since it's April, I'm wondering if someone has idea on this one? I got the same issue, and it looks like I'm not alone here. 
@ebrevdo @aselle

**Comment by TF-Deve** [comment]
Same issue here. Any progress on quantization-aware training for LSTM/RNN?

**Comment by jianlijianli** [comment]
Hi bkanaki, xddkdx, TF-deve, thanks for reaching out. We are actively working on fully quantized LSTM in the following areas:
1) quantization-aware training for LSTM and post-training quantization for LSTM; each of the two options can be used to produce fully quantized LSTM model, depending on one's use case.
2) fully quantized LSTM op that runs the model. TFLite already has a basic fully quantized LSTM (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/reference/reference_ops.h#L1887) and it is being expanded to include more features such as peephole, cifg, projection etc.

Both parts are needed to fully support quantized LSTM and we are making progress. Please stay tuned.

**Comment by TF-Deve** [comment]
> Hi bkanaki, xddkdx, TF-deve, thanks for reaching out. We are actively working on fully quantized LSTM in the following areas:
> 
> 1. quantization-aware training for LSTM and post-training quantization for LSTM; each of the two options can be used to produce fully quantized LSTM model, depending on one's use case.
> 2. fully quantized LSTM op that runs the model. TFLite already has a basic fully quantized LSTM (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/reference/reference_ops.h#L1887) and it is being expanded to include more features such as peephole, cifg, projection etc.
> 
> Both parts are needed to fully support quantized LSTM and we are making progress. Please stay tuned.

Hi @jianlijianli , thanks for your reply! In point 1, you mentioned that post-training quantization also produces fully quantized LSTM? I thought post-training quantization still uses float32 kernels during inference (please correct me if I'm wrong). So I guess I'm not very clear about the definition of "fully quantization"? Thanks.

**Comment by jianlijianli** [comment]
Hi TF-Deve, apologies for the delay. You are right that at this moment post-training quantization is using float32 activation (and uint8 weight and does quantization on the fly inside the kernel). The "fully quantized" I mentioned means a scheme that everything is integer and this is what we are currently working on. Stay tuned:)

**Comment by robot-nano** [comment]
@jianlijianli Area you finished "fully quantized" LSTM?

**Comment by OctaM** [comment]
Hello @jianlijianli , is this still "work in progress"? Because it's been 1 and a half years since this is work in progress and no updates.

**Comment by tbec** [comment]
Hi @jianlijianli, do you have any information on the progress of this work?

**Comment by ebrevdo** [comment]
TFLite has a well documented post-training quantization path documented
here, new since I last checked this bug.

https://www.tensorflow.org/lite/performance/post_training_quantization

Have you tried that?

**Comment by tbec** [comment]
Hi @ebrevdo, thanks for responding. I have used post-training quantization and am unable to convert an LSTM using full integer quantization, although I've had no issues with dynamic range quantization of LSTM models.

**Comment by jgorham** [comment]
hey @ebrevdo , I'm also having issues when trying to fully quantize a (keras) LSTM to int8. I'm running code like the following:
```
    representative_dataset_generator = build_representative_dataset_generator(
        [s.shape.as_list() for s in model.inputs],
        params,
    )

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset_generator
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    tflitemodel = converter.convert()
```
and seeing this in response:
```
  File "/Users/jax/code/www/tools/model_release/convert_to_tflite.py", line 137, in convert_tf2_to_tflite
    return converter.convert()
  File "/Users/jax/code/www/venv/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 874, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "/Users/jax/code/www/venv/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 632, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/Users/jax/code/www/venv/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 449, in _calibrate_quantize_model
    calibrate_quantize = _calibrator.Calibrator(result)
  File "/Users/jax/code/www/venv/lib/python3.7/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 60, in __init__
    raise ValueError("Failed to parse the model: %s." % e)
ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.
```
is this a known issue? fwiw, if i comment out the lines relevant to quantization, the convert call is successful.

**Comment by ebrevdo** [comment]
@liufengdb is our TFLite post-training-quantization expert so I've asked him to answer these questions.

**Comment by liufengdb** [comment]
Hi Jackson, just want to confirm that you are using the latest tf version 2.4. (Your stack shows you are still using old converter).

**Comment by jgorham** [comment]
thanks @ebrevdo !

yes, @liufengdb , i tried both `2.4.0` and `2.4.1`. is there an easy to force my local package to use the new converter?

**Comment by nyadla-sys** [comment]
@liufengdb :Using LSTM op in my model and could verify accuracy using TF, TFLIte float32 models.
https://colab.research.google.com/drive/1LIqNXYszOB4eUHFhqnbGLESdZs4Ipu_n?usp=sharing
However when I generate TFLite int8 model using post training quantization and int8 model doesnot work with my test data.
Note: If I use uint8 post training quantization it works fine and only for int8 quantization is not working with LSTM op

**Comment by Xhark** [comment]
@nyadla-sys You have to put quantized output as follow this doc: https://www.tensorflow.org/lite/performance/post_training_quantization

For your case, validation code for int8 model should be:

    input_scale, input_zero_point = input_details[0]["quantization"]
    spectrogram = np.array(spectrogram)
    spectrogram = spectrogram / input_scale + input_zero_point
    q_spectrogram = np.array(spectrogram, dtype=np.int8).reshape(1,49, 257)
    tflite_interpreter_quant_int8.set_tensor(input_details[0]['index'], q_spectrogram )
    tflite_interpreter_quant_int8.invoke()
    tflite_q_model_predictions = tflite_interpreter_quant_int8.get_tensor(output_details[0]['index'])
    print(tflite_q_model_predictions)
    # print("\nPrediction results shape:", tflite_q_model_predictions.shape)
    # print("\nPrediction results shape:",np.array(tflite_q_model_predictions, dtype=np.int8))
    output_scale, output_zero_point = output_details[0]["quantization"]
    tflite_model_predictions = (np.array(tflite_q_model_predictions, dtype=np.float32) - output_zero_point) * output_scale
    tflite_pred_dataframe = pd.DataFrame(tflite_model_predictions)
    tflite_pred_dataframe.columns = commands
    print(tflite_pred_dataframe)


It seems better than before, but I'm not so sure why uint8 and int8 result is different even if makes validation code correctly.
uint8 and int8 TFLite both uses int8 LSTM op, and I checked all tensors related to LSTM op (weights and input, by called get_tensor on python interpreter) are same but has different output. I guess TFLite kernel (unidirectional_sequence_lstm) may have some issue?

**Comment by Xhark** [comment]
@nyadla-sys If you use 
    spectrogram = np.array(spectrogram)
    spectrogram = np.clip(np.floor(spectrogram / input_scale + input_zero_point), 0, 255) # for uint8 validation
    spectrogram = np.clip(np.floor(spectrogram / input_scale + input_zero_point), -128, 127) # for int8 validation

then int8 and uint8 model output seems almost same. Interestingly with floor and without floor makes huge difference.
Would you please check it works?

**Comment by nyadla-sys** [comment]
@Xhark Thanks for your time and will try as mentioned above 
However I tried below for int8 model and it works for me.
    spectrogram_t = np.array(spectrogram, dtype=np.uint8).reshape(1,49, 257)
    spectrogram_t = np.array(spectrogram_t-128, dtype=np.int8)
    tflite_interpreter_quant.set_tensor(input_details[0]['index'],spectrogram_t )

**Comment by nyadla-sys** [comment]
@Xhark It works and thanks

**Comment by sushreebarsa** [comment]
@bkanaki Could you please let us know if this issue still persists in TF v2.5 ? Thank you!

**Comment by nyadla-sys** [comment]
@bkanaki ,Yes, please see the below links. 
https://github.com/nyadla-sys/tflite-micro/tree/micro_speech_lstm_with_training/tensorflow/lite/micro/examples/micro_speech_lstm/train

https://colab.research.google.com/github/nyadla-sys/tflite-micro/blob/upload_lstm/tensorflow/lite/micro/kernels/xtensa/examples/micro_speech_lstm/train/micro_speech_with_lstm_op.ipynb

**Comment by bkanaki** [comment]
Closing this as I have moved on to a different project a long time ago, the links above seem to be working well.

**Comment by wellido** [comment]
Do quantization aware training supports LSTM/GRU layers now?

**Comment by StuartIanNaylor** [comment]
https://github.com/breizhn/DTLN/issues/66#issuecomment-1312917350 with the above provided some great info on this and it would be so good to get static int8 quntisation for frameworks such as ArmNN to npu's or micro.
Does anyone know the state of play with dev for this or even an ETA?

Thanks

**Comment by JorgeRuizDev** [comment]
> Do quantization aware training supports LSTM/GRU layers now?

TFMOT does not support LSTM QAT
QKeras has some kind of compatibility

**Comment by mohantym** [comment]
Hi @JorgeRuizDev @wellido !
Have you checked [fusion code lab](https://github.com/tensorflow/tensorflow/issues/25563) method and inferred against int 8 quantization.
What I have observed till now that LSTM/RNN model does not work in GPU model when select ops operators are included but works in fusion code lab.

Thank you!

**Comment by 529669517** [comment]
Do quantization aware training supports SimpleRNN layers now?
