### ISSUE TITLE
Linear alpha shape does not match the number of input channels.Node number 9 (GpuDelegate) failed to prepare.

### ISSUE THREAD

**Issue by ksekine** [tensorflow/tensorflow#25579]
Dear TensorFlow developer,

I implemented my custom model in my app. And I tried to set GPU delegate.  
But if I instantiate `Interpreter` with GPU delegate option, the following error occurs.  
```
Linear alpha shape does not match the number of input channels.Node number 9 (GpuDelegate) failed to prepare.
```
What does this error message suppose to mean?  
Or is there anything I need to be careful on TFLite converting?  
Anything would be helpful.  
Thanks!  

The model I used is here.
[classify.tflite.zip](https://github.com/tensorflow/tensorflow/files/2839976/classify.tflite.zip)

**Comment by ksekine** [comment]
Thank you for your reply.  
Issue template is shown below.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: on Simulator and on Samsung Galaxy S8
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 0.0.0-gpu-experimental
- Python version: N/A
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A
- Android Studio version: 3.3

**Describe the problem**
I implemented my custom model in my app following the [TensorFlow Lite GPU Delegate Tutorial](https://www.tensorflow.org/lite/performance/gpu).  
The code of essensial part is below. The model I used in this code is already attached on above comment.  
```
import org.tensorflow.lite.Interpreter;
import org.tensorflow.lite.experimental.GpuDelegate;

GpuDelegate delegate = new GpuDelegate();
Interpreter.Options options = (new Interpreter.Options()).addDelegate(delegate);
Interpreter interpreter = new Interpreter(model, options);
```

When `interpreter` is instantiated, the following error occurs.  
```
Linear alpha shape does not match the number of input channels.Node number 9 (GpuDelegate) failed to prepare. 
```

What does this error message suppose to mean?  
Need any special process when converting to tflite model in order to use GPU delegate?  
Thanks!

**Comment by jdduke** [comment]
@impjdi have you observed this before?

**Comment by impjdi** [comment]
@jdduke No, I haven't seen this, but then again, I haven't seen models with PReLU flying by (that's where you get this error message).

@ksekine Sorry for quite a belated response on this; I just got looped in.  The error message means that the tensor shapes and network don't match.  It was checking whether the tensor's channel size matches the linear alpha vector size in PReLU, but looks like there was a mismatch?

**Comment by ksekine** [comment]
Thanks for the information that PReLU is the cause.  
I can work around this issue by removing PReLU from the model.  
So I'll close this issue if no one else is in trouble.
