### ISSUE TITLE
Could you please include small examples with the functions embedded in real code with the documentation?

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/tensorflow#25587]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0 preview
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Could you please include small examples with the functions embedded in real code with the documentation?

**Will this change the current api? How?**
Make the usage more elucidate.

**Who will benefit with this feature?**
All the new and intermediate users.

**Any Other info.**
For example, you can see this documentation API doc: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/audio/decode_wav

This is the function call, but there isn't any boilerplate code to show the sequence of its usage.  This is just one example.  All the function call should be similar.

**Comment by MarkDaoust** [comment]
Hi @shyamalschandra, 

Thanks for your interest. This is a known issue. There are thousands of functions, it's just a question of prioritization.

If you have any examples like this that you'd like to contribute, these `api_docs` files are generated from the python docstrings. We should welcome submissions.

But I don't see added value in keeping this bug open.

**Comment by shyamalschandra** [comment]
@MarkDaoust: Shouldn't you wait for more people to respond before negating the suggestion or feature request?

**Comment by MarkDaoust** [comment]
@shyamalschandra I don't mean to give the impression that I'm negating your request!

The request is 100% valid. I agree that it's something we should work on.

Issues in the tracker here however are more helpful if they're precise and achievable. Like "better docs for tf/audio/decode_wav"

This overall task would make sense to track with a spread-sheet and issues for the 100 most popular apis. This is just such a big task, that it doesn't fit in 1 of these bugs.  Who would we assign it to? How would we know if we're done?

**Comment by Sri-vatsa** [comment]
Would love to help with the documentation by writing some functional examples. Is there already a plan to work with the 100 most popular apis?

**Comment by MarkDaoust** [comment]
I believe @dynamicwebpaige is working on setting up a package to make doc sprints simpler for community groups.

> Would love to help with the documentation by writing some functional examples.

The python api_docs are (mostly) generated from the from python doc-strings, and the pages on tensorflow.org (usually) link back to the right code page here.

If you see something wrong, and know how to fix it please send us a PR. It's usually pretty simple to get docs-fixes merged.

**Comment by shyamalschandra** [comment]
What happened?  It has been more 235 days.  What happened?

**Comment by MarkDaoust** [comment]
@Sri-vatsa : I don't know if there's a public list, but whatever's important to you may be important to someone else. If you send improvements to the python docstrings we'll accept them.

@shyamalschandra : One actionable development is that  TensorFlow now encourages the ["doctest" format](https://docs.python.org/3/library/doctest.html) for code examples.  

If you use carets `>>>` instead of code fences "```" the example in the doc will be run as a unit test. Any contribution converting an example to a real runnable doctest example is encouraged.
