### ISSUE TITLE
Edit Distance Matrix for CTC

### ISSUE THREAD

**Issue by vidursatija** [tensorflow/tensorflow#25580]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12.2
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The input will be labels and the predicted output(from ctc greedy/beam decoder, SparseTensor). It will calculate the following 4 things:
1. The edit distance between the output and the ground truth
2. Substitution Matrix: It will store all the entries where a value was substituted in the output to reach the ground truth. Shape = [n_symbols, n_symbols]. Like the confusion matrix
3. Insertion Matrix: It will store all the insertions to be made in the output to reach the grond truth. Shape = [n_symbols]
4. Deletion Matrix: It will store all the deletions to be made in the output to reach the grond truth. Shape = [n_symbols]

**Will this change the current api? How?**

**Who will benefit with this feature?**
The target audience is everyone who uses edit distance(word error rate, letter error rate) as a metric and wants to know where the model is failing. The 3 matrices will be quite helpful to debug errors in the output. 

**Any Other info.**
I'm willing to contribute. I can write it well in Python, C/C++. I want ideas from people and a little help in writing the tensorflow op

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
