### ISSUE TITLE
tf_upgrade_v2 upgrade script should do absl-py conversions

### ISSUE THREAD

**Issue by jaingaurav** [tensorflow/tensorflow#25598]
Currently the tf_upgrade_v2 upgrade script changes uses of tf.app, tf.flags & tf.logging to tf.compat.v1.*. It seems that is would be more elegant for us to simply add the necessary absl-py imports and modify the code to use those instead.

**Comment by kumariko** [comment]
@jaingaurav Could you please let us know if you still need help on this issue? Thanks!
