### ISSUE TITLE
Bug in tf.image.resize_images

### ISSUE THREAD

**Issue by maxfiedler** [tensorflow/tensorflow#25591]
### System information

I am running Ubuntu 18.0.4 on my PC with CUDA-10 and Python 3.6 and Pillow 5.4.1
```
libcudnn7:
  Installed: 7.4.1.5-1+cuda10.0
  Candidate: 7.4.2.24-1+cuda10.0
```
with Tensorflow version `b'v1.12.0-0-ga6d8ffae09' 1.12.0`

### Describe the problem
I am trying to resize an image with `tf.image.resize_images` using all available methods but I am getting completely crappy results for anything except NEAREST_NEIGHBOR

For example simply loading this image from the test set of Imagenet
![ilsvrc2012_test_00000002](https://user-images.githubusercontent.com/4192637/52434595-fff10480-2b0f-11e9-8e2c-6358b81760fe.JPEG)

I get colorful pixel salad if I put it through `resize_bilinear`
see code and output below.

### Source code / logs
To reproduce place the code and the image file above in the same folder or adjust the file-path accordingly:
```
import tensorflow as tf
from PIL import Image
import time
import numpy as np

file_read = tf.read_file('ILSVRC2012_test_00000002.JPEG')
loaded_image = tf.image.decode_jpeg(file_read, channels=3)
reshape_image = tf.expand_dims(loaded_image, 0)
resized_image = tf.image.resize_bilinear(reshape_image, size=[510, 520], align_corners=False)
resized_image_v2 = tf.image.resize_images(reshape_image, size=[300, 320],
                                          method=tf.image.ResizeMethod.BILINEAR, align_corners=False)
# resized_image_v2 = tf.image.resize_images(reshape_image, size=[300, 320],
                                          method=tf.image.ResizeMethod.NEAREST_NEIGHBOR, align_corners=True)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    orig_image = sess.run(loaded_image)
    resized_v1 = sess.run(resized_image)
    resized_v2 = sess.run(resized_image_v2)
    orig_img = Image.fromarray(orig_image, 'RGB')
    resized_v1_img = Image.fromarray(np.squeeze(resized_v1), 'RGB')
    resized_v2_img = Image.fromarray(np.squeeze(resized_v2), 'RGB')
    orig_img.show()
    resized_v1_img.show()
    resized_v2_img.show()
    time.sleep(10)
    orig_img.close()
    resized_v1_img.close()
    resized_v2_img.close()
```
This produces for the original image:
![original_image](https://user-images.githubusercontent.com/4192637/52435280-ba353b80-2b11-11e9-8a38-494195b5f3a4.jpg)

for the larger resize: 
![resize_large](https://user-images.githubusercontent.com/4192637/52435296-c4573a00-2b11-11e9-9c4b-cad0f1a4ea2d.jpg)

for the smaller resize:
![resize_small](https://user-images.githubusercontent.com/4192637/52435319-d1742900-2b11-11e9-80b2-9e4261e5ab26.jpg)

I get similar crappy results if I set `align_corners=True`

However if I use `method=tf.image.ResizeMethod.NEAREST_NEIGHBOR` (i.e. the commented out line), I get a descent result
![resize_small2](https://user-images.githubusercontent.com/4192637/52435620-9a524780-2b12-11e9-9140-4ff7a168a595.jpg)

With `BICUBIC` and `AREA` the results are similar pixel garbage as with `BILINEAR`

Am I missing something here? This seems to be seriously broken.

**Comment by maxfiedler** [comment]
Trying the same with OpenCV gives me perfectly reasonable results for both Bilinear and Nearest Neighbor
```
import cv2


file_read = cv2.imread('ILSVRC2012_test_00000002.JPEG')

resized_image_bl = cv2.resize(file_read, dsize=(300, 320), interpolation=cv2.INTER_LINEAR)
resized_image_nn = cv2.resize(file_read, dsize=(300, 320), interpolation=cv2.INTER_NEAREST)

cv2.imshow('original_image', file_read)
cv2.imshow('bilinear image', resized_image_bl)
cv2.imshow('NN image', resized_image_nn)

cv2.waitKey(0)  # waits until a key is pressed
cv2.destroyAllWindows()  # destroys the window showing image
```

**Comment by maxfiedler** [comment]
Never mind. I simply did not catch that BILINEAR converts the Tensor automatically to tf.float32 ...
a simple numpy `astype(np.uint8)` solves the mytery ...
Grrrr

**Comment by jvishnuvardhan** [comment]
@maxfiedler Thanks for resolving and posting the solution here. Thanks again!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25591)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25591)
