### ISSUE TITLE
Python 3.7 (nightly) TF 1.12, GLIBC 2.23 import failure on Centos 7.5

### ISSUE THREAD

**Issue by apiszcz** [tensorflow/tensorflow#25593]
Using Centos 7.5 which has glibc2.17, tensorflow nightly build fails on import
Since updating glibc on Centos appears is not advised, is their a hard requirement for GLIBC 2.23?
Thank you.

ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /python3.7/site                                                                          -packages/tensorflow/python/_pywrap_tensorflow_internal.so)

**Comment by ymodak** [comment]
Python 3.7 will be supported in the official release.

**Comment by apiszcz** [comment]
Thanks, we are trying to get all platforms to 3.7, (from 3.5) will wait for 1.13, thank you!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25593)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25593)

**Comment by racinmat** [comment]
Using Tensorflow 1.14, installed via pip in Centos with python 3.7.4, the issue persists, and sme error is thrown

**Comment by JHyeok** [comment]
This issue has not been resolved. Same issue `ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found`

Using
python 3.7.4
Tensorflow 1.14.0
