### ISSUE TITLE
Transpose convolution layer for tensorflow (was deconvolution)

### ISSUE THREAD

**Issue by panmari** [tensorflow/tensorflow#256]
Has anyone already started implementing a deconvolutional layer for tensorflow as it's used e. g. here https://github.com/stokasto/caffe ? Is anyone else interested in such a functionality or is there any trivial way to implement this using the existing tensors?

**Comment by vincentvanhoucke** [comment]
It's here:
https://github.com/tensorflow/tensorflow/blob/1d76583411038767f673a0c96174c80eaf9ff42f/tensorflow/python/ops/nn_ops.py#L24
Not sure why it's not exposed in the documentation yet, possibly because the API isn't considered stable.

**Comment by panmari** [comment]
Cool, thanks for pointing me there!

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/1d76583411038767f673a0c96174c80eaf9ff42f/tensorflow/python/ops/nn_ops.py#L29 suggests it isn't agreed that the op is doing deconvolution.  Hence why it wasn't made public yet.

**Comment by suhangpro** [comment]
"deconvolution" has been used as a synonym for transposed convolution in recent computer vision literature, especially in ConvNet related work. I believe this "deconv2d" is exactly the op most people will be using for either upsampling or visualization purposes.

**Comment by girving** [comment]
@vincentvanhoucke: I'm happy to expose it in the public API as long as we're fine with the misleading name.

**Comment by vincentvanhoucke** [comment]
@girving I remember being very, very confused when the term 'deconvolution' started popping up in the literature for this operator. I blame Matt (Zeiler) ;-) I had to go back to his papers to convince myself of what they were doing and that it had nothing to do with actually deconvolving the input.
Matt Zeiler calls the entire stack Deconvolution Networks:
http://www.matthewzeiler.com/pubs/iccv2011/iccv2011.pdf
but only ever refers to this operator as a 'projection operator' as far as I can tell.
Caffe calls it Deconvolution (@Yangqing) :
http://caffe.berkeleyvision.org/doxygen/classcaffe_1_1DeconvolutionLayer.html

Since 'deconv' is apparently here to stay, should we consider making the name a bit more explicit? On the table from my POV:
1- transpose_deconv2d()
2- project_deconv2d()
3- deconv2d()

Note that I actually don't know what an alternative 'deconv2d' might look like. The process of deconvolving an input is ill-posed and there are many ways to go about it, so it's possible that option 3 is just fine as long as there is an abundance of documentation. @shlens and @josh11b might have opinions on the matter.

**Comment by suhangpro** [comment]
Another option is 'convt' (short for convolution transpose), which is adopted by [matconvnet](http://www.vlfeat.org/matconvnet/mfiles/vl_nnconvt/).

**Comment by girving** [comment]
I think `transpose_conv2d` or `conv2d_transpose` are the cleanest names.  `transpose_deconv2d` implies it is the inverse transpose of `conv2d`.  `convt` is clever but very easy to mistake for `conv`.

**Comment by vincentvanhoucke** [comment]
conv2d_transpose SGTM, it would put it jut after conv2d in alphabetical ordering. We should emphasize in the doc that it's what's often referred as 'deconv' or 'deconvolution', so that it shows up if anyone searches the docs for those terms.

**Comment by jeffschecter** [comment]
The current implementation crashes the Python kernel when given an output shape with a -1 in the first dimension. It would be helpful to throw a Python error and document this limitation, as ops produced by similar functions (eg conv2d) handle the scenario just fine.

**Comment by girving** [comment]
@jeffschecter: What kind of error do you get with the kernel crash?  This may be the same thing as #449, in which case it's fixed in 5de908567355337fdebd997fb5c60993cbe9ba2e and will be part of 0.6.0 soon.  That is, it should still generate exceptions, but will no longer crash the process.

**Comment by girving** [comment]
@jeffschecter: Oops, no, it's an independent bug.  I'll fix that now.  Thanks for the catch.

**Comment by futurely** [comment]
There are many algorithms to deconvolve an image. For easier extensibility in the future and to avoid being locked in a specific implementation, the public API should add a parameter to reflect which method is used and call the corresponding internal function.
`def deconv2d(value, filter, output_shape, strides, padding = 'SAME', method = 'transpose', name=None)`
`def _deconv2d_transpose(value, filter, output_shape, strides, padding = 'SAME', name=None)`

https://reference.wolfram.com/language/ref/ImageDeconvolve.html
http://mathworld.wolfram.com/Deconvolution.html

**Comment by girving** [comment]
@futurely: I'm not sure what you mean by those references, since they are to actual deconvolution ops.  There are many ways to perform deconvolution, but the transpose of convolution is not one of them.

**Comment by futurely** [comment]
For example, if blind deconvolution is implemented too, users can switch between different deconvolution algorithm with the following code. It's stylistic difference but may be a bit easier to use than to change potentially multiple occurrences of `deconv2d_transpose` and `deconv2d_blind`.
```python
method = 'blind'
# method = 'transpose'
deconv2d(..., method = method)
```

**Comment by girving** [comment]
@futurely: Feature requests about deconvolution should go in a separate issue.  This thread is about the transpose of convolution, which is unrelated.

**Comment by josh11b** [comment]
The transpose-convolution operator already exists in TF, I think it is one of the conv_2d_backprop_*() functions.  If we were to give it another name as part of exposing it in the api, I'd prefer conv_2d_transpose or some such and having documentation that some sources mistakenly refer to that op as deconvolution.  I think we should not contribute to the misuse of the deconvolution term -- it leads to things like futurely@'s confusion.

**Comment by girving** [comment]
Yep, Vincent and I agreed on `conv2d_transpose` earlier in the thread.

**Comment by ry** [comment]
How do you use deconv2d for upsampling?

**Comment by girving** [comment]
@ry: Questions like that are better suited to stackoverflow.  This thread should stay focused on the  missing `conv2d_transpose` op.  (However: it isn't related to upsampling, you may be looking for `tf.resize_bilinear` and friends).

**Comment by marshalmace** [comment]
from my understanding, it should be called as "inverse convolution" instead of "transpose convolution".
Ax=b 
=> (A inverse)Ax=(A inverse)b
=> Ix=(A inverse)b
=> x=(A inverse)b

here x is input (layer), A is kernel, b is output (layer)
