### ISSUE TITLE
~40% slow down since 1.13.0.dev20190202

### ISSUE THREAD

**Issue by gehring** [tensorflow/tensorflow#25606]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: public Colab instance and Debian
- TensorFlow installed from (source or binary): binary
- TensorFlow version: >= 1.13.0.dev20190202
- Python version: 3.6.7
- CUDA/cuDNN version: 10
- GPU model and memory: K80 (originally occurred on T4 and V100)

**Describe the current behavior**
Performance on some simple looped graphs has worsen by ~40% in between 1.13.0.dev20190201 and 1.13.0.dev20190202 and still exists in the current nightly build (see provided colab). This slow down was consistent across VMs and GPUs when running my research code. The provided code is my best attempt at boiling it down.

Here are the results from the colab benchmark copied for convenience. The `num_batched_iter` partially unrolls the `tf.while_loop` body for that many iterations to reduce its overhead and leverage other graph optimizations. Before the first timed `sess.run(...)` call, 5 warm-up call are made. Results reported aggregate 40 different runs. The colab runtimes were completely reset before benchmarking each version. 

On the newest tf-nightly-gpu build, I got:
```
1.13.0-dev20190207
Benchmarking simple_loop_case...
name                                                                         mean        min        max     q=0.05     q=0.95
----------------------------------------------------------------------  ---------  ---------  ---------  ---------  ---------
simple loop, num_batched_iter=1, back_prop=False, test_converge=True    0.526553   0.512475   0.551661   0.51285    0.543843
simple loop, num_batched_iter=1, back_prop=False, test_converge=False   1.18145    1.15179    1.2054     1.16411    1.1976
simple loop, num_batched_iter=20, back_prop=False, test_converge=True   0.0664629  0.0633538  0.0774522  0.0636203  0.0729571
simple loop, num_batched_iter=20, back_prop=False, test_converge=False  0.249716   0.238131   0.261069   0.241182   0.259239
```
Here are the results on the version just before the issue appears:
```
1.13.0-dev20190201
Benchmarking simple_loop_case...
name                                                                         mean        min        max     q=0.05     q=0.95
----------------------------------------------------------------------  ---------  ---------  ---------  ---------  ---------
simple loop, num_batched_iter=1, back_prop=False, test_converge=True    0.519208   0.483462   0.570542   0.487508   0.569501
simple loop, num_batched_iter=1, back_prop=False, test_converge=False   1.21199    1.18047    1.24812    1.18563    1.23686
simple loop, num_batched_iter=20, back_prop=False, test_converge=True   0.0483549  0.0455515  0.0589228  0.0463824  0.0505414
simple loop, num_batched_iter=20, back_prop=False, test_converge=False  0.175403   0.168438   0.192948   0.169144   0.18713
```

**Code to reproduce the issue**
https://gist.github.com/gehring/4e7bd9b6f0c5d73c545777236fc507d0

**Comment by gehring** [comment]
The issue still remains in the most recent nightly build:
```
1.13.0-dev20190212
Benchmarking simple_loop_case...
name                                                                        mean        min        max    q=0.05     q=0.95
----------------------------------------------------------------------  --------  ---------  ---------  --------  ---------
simple loop, num_batched_iter=1, back_prop=False, test_converge=True    0.569304  0.551403   0.60731    0.556146  0.585934
simple loop, num_batched_iter=1, back_prop=False, test_converge=False   1.24792   1.21103    1.37319    1.21408   1.31663
simple loop, num_batched_iter=20, back_prop=False, test_converge=True   0.071491  0.0682344  0.0827348  0.068548  0.0796988
simple loop, num_batched_iter=20, back_prop=False, test_converge=False  0.244619  0.236556   0.25513    0.237421  0.250926
```

**Comment by jvishnuvardhan** [comment]
@gehring Is this still an issue for you. As `TF1.x` is out of support, can you try `TF2.x` [Here](https://colab.research.google.com/gist/jvishnuvardhan/8a7574cc3c93cd008607e6d87b853788/tf_perf_issues.ipynb) is a gist comparing `TF1.13` and `TF1.15`. Thanks!

I am closing this issue. Please open a new issue if the issue persists performance issue with `TF2.x` version. Thanks!
