### ISSUE TITLE
Building tensorflow from Source for arm64

### ISSUE THREAD

**Issue by TropSpirit** [tensorflow/tensorflow#25608]
Hi All,

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.12.0
- Bazel installed version : 0.21.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): gcc 7.3 
- CUDA/cuDNN version: N/A
- GPU model and memory: N/a

I'm trying to build tensorflow from source on arm64 (aarch64) but got stucked at the following:

INFO: From Compiling tensorflow/core/kernels/diag_op.cc [for host]:
tensorflow/core/kernels/diag_op.cc:118:1: warning: multi-line comment [-Wcomment]
 // `new_index = i1*(s2*...sk*s1*...*sk) + i2*(s3*...*sk*s1*...*sk) +... + \
 ^
**ERROR: /home/rock64/tensorflow/tensorflow/core/kernels/BUILD:2187:1: C++ compilation of rule '//tensorflow/core/kernels:resource_variable_ops' failed (Exit 4)**
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3734.152s, Critical Path: 279.33s
INFO: 4043 processes: 4043 local.
FAILED: Build did NOT complete successfully

Bazel installed version : 0.21.0
Tensorflow : 1.12.0
installed gcc-aarch64-linux-gnu & g++-aarch64-linux-gnu

**Comment by jvishnuvardhan** [comment]
@TropSpirit I am closing this issue as it was a duplicate issue #25607 . Please fill the template in that open issue then we will try to resolve as soon as possible. In future, please don't create duplicate issues. Thanks!

**Comment by TropSpirit** [comment]
@jvishnuvardhan  this is not duplicate #25607 is error while using cross compile and this issue #25608 is directly compiling/building from source on arm64 bit processor and i'm getting this error. Two different issues.

**Comment by jvishnuvardhan** [comment]
@TropSpirit Sorry for the mistake. Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Thanks!

**Comment by jvishnuvardhan** [comment]
@TropSpirit If the issue was resolved, please close it. Thanks!

**Comment by Estom** [comment]
HEY，i got the same issue. changing the bazel version do not work. Is it the reason of gcc version?
