### ISSUE TITLE
Docker image tensorflow/tensorflow:latest-gpu failed to use nvidia/cuda image

### ISSUE THREAD

**Issue by lucasbsimao** [tensorflow/tensorflow#25618]
Hello guys,

I am facing some problems when running image tensorflow/tensorflow:latest-gpu. When I try to execute the command ( which is found in [docs](https://www.tensorflow.org/install/docker#examples_using_gpu-enabled_images) ) :

```shell
docker run --runtime=nvidia -it --rm tensorflow/tensorflow:latest-gpu \
   python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
```

I get the following error:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting
container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running
prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: 
[/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --
compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=7142 
/var/lib/docker/overlay2/c2f4ac7d7d905051e77682447a97f563cbdf7ccf2fe43afccdb521350adab0f4/mer
ged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: brand = tesla\\\\n\\\"\"": unknown.

```
It may be caused by not properly installed NVidia driver, as seen [here](https://devtalk.nvidia.com/default/topic/1046289/cuda-setup-and-installation/command-quot-docker-run-runtime-nvidia-rm-nvidia-cuda-9-0-base-nvidia-smi-quot-fails-with-error-/).
But turns out that when I try to run the following command ( also seen in [docs](https://www.tensorflow.org/install/docker#gpu_support) ):

```shell
docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
```

It gives me the same error. The above command only runs correctly when I run it with the nvidia/cuda:9.0-base image, specified in NVidia [github README](https://github.com/NVIDIA/nvidia-docker#ubuntu-140416041804-debian-jessiestretch):

```shell
docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi
```

I think it is a problem with tensorflow:lastest-gpu, which may be linking its image with nvidia/cuda:latest  instead of nvidia/cuda:9.0-base image.
Is anyone else facing the same issue?

My configuration:
Ubuntu 18.04.1
GeForce 930M
Driver nvidia-driver-390 version 390.77, installed via Softwares and Updates.

## EDIT
TF version: Latest docker image tensorflow/tensorflow:latest-gpu which following the [docs](https://www.tensorflow.org/install/docker) does not need CUDA installed, just the driver.

**Comment by jvishnuvardhan** [comment]
@lucasbsimao Please fill the [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Which TF version, CUDA/cuDNN, python etc you installed? Thanks!

**Comment by lucasbsimao** [comment]
> @lucasbsimao Please fill the [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Which TF version, CUDA/cuDNN, python etc you installed? Thanks!

According to [TensorFlow docs](https://www.tensorflow.org/install/docker) there is no need of previous installation of python or CUDA. Just Nvidia driver.

**Comment by angersson** [comment]
A bug (which has been fixed) in our Docker release CI led to the `latest-` tagged images containing CUDA 10 libraries but TF 1.12 (which needs CUDA 9). The images have been updated so that they use CUDA 10 and TF 1.13rc1 (which needs CUDA 10). Sorry about the confusion.

I think your driver is too old to support CUDA 10 (see [NVidia's compatibility table](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility__table-toolkit-driver)). If that's the case, you can either use one of the numbered 1.12 tags or upgrade your device driver to a version that supports CUDA 10 and TF 1.13.

**Comment by huan** [comment]
I ran into this issue today on my Ubuntu 18.04 box.

Fixed by installing the CUDA 10 by the following command:

```sh
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb \
    && sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub \
    && sudo apt-get update \
    && sudo dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb \
    && sudo apt-get update \
    && sudo apt-get install -y cuda
```

### See

- [Install CUDA 10 on Ubuntu 18.04](https://deeptalk.lambdalabs.com/t/docker-error-response-from-daemon-oci-runtime-create-failed-nvidia-container-cli-requirement-error-unsatisfied-condition-cuda-10-0/769)

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25618)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25618)

**Comment by puren** [comment]
Hello, 

I have the same problem.
I use:
Ubuntu 16.04 
GeForce GTX 1080 Ti
nvidia driver version: 384.130

Tensorflow and other cuda related code runs without any problem.

But in Docker, I have the following problem.
When I run
`sudo docker run --runtime=nvidia -it --rm tensorflow/tensorflow:latest-gpu  python -c "import tensorflow as tf; print('Hello world')"
`
I get the following error:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=8886 /var/lib/docker/overlay2/43f665d0f341d27c84a4341e45f405ea2aba058a4be79c421cdf893ae3df459e/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: brand = tesla\\\\n\\\"\"": unknown.
`



When I run 
`sudo docker run --runtime=nvidia -it --rm nvidia/cuda:9.0-base nvida-smi
`
it runs without an issue:
```
Wed Mar  6 21:41:54 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   41C    P5    37W / 250W |      0MiB / 11170MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

So I tried to to run tensorflow with cuda 9.0 as well:
`sudo docker run --runtime=nvidia -it --rm nvidia/cuda:9.0-base tensorflow/tensorflow:latest-gpu  python -c "import tensorflow as tf; print('Hello world')"`

But it doesn't allow me to run tensorflow with "nvidia/cuda:9.0-base":
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"tensorflow/tensorflow:latest-gpu\": stat tensorflow/tensorflow:latest-gpu: no such file or directory": unknown.`

Is there a way to select cuda version while running tensorflow in docker?

**Comment by MakeCent** [comment]
> Hello,
> 
> I have the same problem.
> I use:
> Ubuntu 16.04
> GeForce GTX 1080 Ti
> nvidia driver version: 384.130
> 
> Tensorflow and other cuda related code run without any problem.
> 
> But in Docker, I have the following problem.
> When I run
> `sudo docker run --runtime=nvidia -it --rm tensorflow/tensorflow:latest-gpu python -c "import tensorflow as tf; print('Hello world')" `
> I get the following error:
> `docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=8886 /var/lib/docker/overlay2/43f665d0f341d27c84a4341e45f405ea2aba058a4be79c421cdf893ae3df459e/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: brand = tesla\\\\n\\\"\"": unknown. `
> 
> When I run
> `sudo docker run --runtime=nvidia -it --rm nvidia/cuda:9.0-base nvida-smi `
> it runs without an issue:
> 
> ```
> Wed Mar  6 21:41:54 2019       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 384.130                Driver Version: 384.130                   |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 108...  Off  | 00000000:01:00.0 Off |                  N/A |
> |  0%   41C    P5    37W / 250W |      0MiB / 11170MiB |      2%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+
> ```
> 
> So I tried to to run tensorflow with cuda 9.0 as well:
> `sudo docker run --runtime=nvidia -it --rm nvidia/cuda:9.0-base tensorflow/tensorflow:latest-gpu python -c "import tensorflow as tf; print('Hello world')"`
> 
> But it doesn't allow me to run tensorflow with "nvidia/cuda:9.0-base":
> `docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"tensorflow/tensorflow:latest-gpu\": stat tensorflow/tensorflow:latest-gpu: no such file or directory": unknown.`
> 
> Is there a way to select cuda version while running tensorflow in docker?

I think angersson's answer has already showed you the answer. You cannot not select cuda version, but you can select the version of tensorflow image from docker. Which means, when you pull image from docker hub, don't tag tensorflow image with "latest-gpu" (which do not comply with cuda 9.0). Instead, pull image with TF 1.12 (to specify what tag should be used for this, go to the official github site of tensorflow docker). Then you code may work well.
Actually, due to your so powerful GPU, the better choice for you is to upgrade you gpu driver upto larger than 410.48. Then you can use both latest tensorflow image and CUDA 10.0
