### ISSUE TITLE
Segmentation fault - Convolution in tflite

### ISSUE THREAD

**Issue by ved27** [tensorflow/tensorflow#25614]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution : Linux Ubuntu 16.04
- TensorFlow installed from github:
- TensorFlow version tf 1.13:
- Python version: 3.6
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 5.4.0 20160609
- CUDA : 9.0
- RAM : 32GB

Hi,

I encountered a segmentation fault in the Im2Col of Convolution while running a tflite model.
I observed that when the Im2Col buffer size >  2GB, this crash occurs. 
For example : 
input : 1x828x1000x32 ; output: 1x828x1000x3  ;kernel: 9x9  does not crash

but for 
input:1x832x100x32 ; output: 1x832x1000x3; kernel 9x9  convolution crashes.

I want to know if there is any memory limit for convolution in tflite to run ?

I kindly request you to let me know this. sooner the better

Awaiting you reply,
Vedavyas.

**Comment by jvishnuvardhan** [comment]
@ved27 Could you share some reproducible code and also please mention what is your OS. Please provide as many details as possible to resolve this faster. Thanks!

**Comment by ved27** [comment]
Hi ,

 I'm unable to share the exact code. However, I am able to reproduce the issue setting the above input shapes and kernel sizes in the testing code of quantized convolution in tflite.
 
Awaiting your reply,

**Comment by ved27** [comment]
Hi,

I kindly request you to look into this soon, as it would be helpful for me to rule out the models which seem to take high memory.


Awaiting your reply,

**Comment by ved27** [comment]
Hi,

I kindly request you to address this issue. It has almost been 9 days. 
Thankful if someone can give me a confirmation on the memory limitation of tflite 


Regards,

**Comment by ANSHUMAN87** [comment]
@ved27 : Did you encounter this issue while running some model? If yes, would you be able to share the model? (Just for my reference).

Any way i have found the root-cause for your issue.
### **NOTE:** As of now TFLite does not have any memory limit for convolution.
I have verified with 3GB memory allocation, there is no issue.

But in your case, the **root-cause is classic "Integer overflow"**.

Currently GEMM supports limited by (row * col < 2^31).
As in your case it has exceeded the limit, it is leading to memory corruption.

Currently i am working on a solution for this, will keep you updated if anything come up.

Would suggest to use models which has lower memory requirement(lower than 2^31) for Convolution currently.
If my post helped you, would appreciate if you close this issue.
Please feel free to post if anything from your end, Thanks.

**Comment by ved27** [comment]
Yeah. I debugged and found the root cause earlier.
There has been inconsistency between the datatype usage in various parts of tflite . (int / size_t / unsigned int ). 

And ultimately the GEMM's limitation , causing the crash to occur.  

 I wished a better implementation of convolution in tflite. Implementations other than Im2Col, such as Kn2row can be deployed .

Thank you much
