### ISSUE TITLE
Make of benchmark tool

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#25610]
Is there a make to build benchmark tool instead of bazel?

**Comment by jvishnuvardhan** [comment]
Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
