### ISSUE TITLE
How to get the minimum and maximum cuda compute capability for the given version of TensorFlow.

### ISSUE THREAD

**Issue by bwolfus** [tensorflow/tensorflow#25616]
Hello, is any way to get the supported versions of compute capablity. 
An exemplary function could look like this:
`>>>import tensorflow as tf`
`>>>tf.get_supported_compute_capablity()`
`(3.0, 7.0)`

**System information**
- TensorFlow version 1.10:
- Are you willing to contribute it (Yes/No): Yes

**Comment by gunan** [comment]
Minimum compute capability can be seen here:
https://www.tensorflow.org/install/gpu#hardware_requirements

If we are not supporting this value, that means we have a bug.
While the API is an interesting idea, I think our docs cover this. And this is a pretty stable value that I don't think a new API symbol is that useful.

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25616)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25616)
