### ISSUE TITLE
Could I possibly count the detected object in tensorflow?

### ISSUE THREAD

**Issue by teffanymae** [tensorflow/tensorflow#25619]
here is my code 

import os
import cv2
import numpy as np
import tensorflow as tf
import sys

sys.path.append("..")

from utils import label_map_util
from utils import visualization_utils as vis_util
from api import object_counting_api

MODEL_NAME = 'inference_graph'
IMAGE_NAME = 'tree.png'

CWD_PATH = os.getcwd()

PATH_TO_CKPT = os.path.join(CWD_PATH,MODEL_NAME,'frozen_inference_graph.pb')

PATH_TO_LABELS = os.path.join(CWD_PATH,'training','labelmap.pbtxt')

PATH_TO_IMAGE = os.path.join(CWD_PATH,IMAGE_NAME)

NUM_CLASSES = 2

label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)

detection_graph = tf.Graph()
with detection_graph.as_default():
    od_graph_def = tf.GraphDef()
    with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
        serialized_graph = fid.read()
        od_graph_def.ParseFromString(serialized_graph)
        tf.import_graph_def(od_graph_def, name='')

    sess = tf.Session(graph=detection_graph)

image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')

detection_boxes = detection_graph.get_tensor_by_name('detection_boxes:0')

detection_scores = detection_graph.get_tensor_by_name('detection_scores:0')
detection_classes = detection_graph.get_tensor_by_name('detection_classes:0')

num_detections = detection_graph.get_tensor_by_name('num_detections:0')

image = cv2.imread(PATH_TO_IMAGE)
image_expanded = np.expand_dims(image, axis=0)

(boxes, scores, classes, num) = sess.run(
    [detection_boxes, detection_scores, detection_classes, num_detections],
    feed_dict={image_tensor: image_expanded})

vis_util.visualize_boxes_and_labels_on_image_array(
    image,
    np.squeeze(boxes),
    np.squeeze(classes).astype(np.int32),
    np.squeeze(scores),
    category_index,
    use_normalized_coordinates=True,
    line_thickness=1,
    min_score_thresh=0.50)

cv2.imshow('Object detector', image)

cv2.waitKey(0)

cv2.destroyAllWindows()

**Comment by aniketbote** [comment]
You can count the number of objects detected/ bounding boxes printed by making slight change in visualization_utils which is placed in the utils folder which you are importing.
In the visualization_utils, search for the function "**visualize_boxes_and_labels_on_image_array**".
In the function there is a for loop  stated like "**for box, color in box_to_color_map.items():**".
To count the number of objects detected all you have to do is count the number of times the for loop runs when call the function.
In my repository the line number of the above for loop is : **720**

Do tell if it worked ;)

**Comment by jvishnuvardhan** [comment]
@teffanymae Please try @aniketbote solution.
As this is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by teffanymae** [comment]
Thank you very much!! T_T

what I did is add this code at **756**

  tree = (len(box_to_color_map.items()))
  cv2.putText(image,'Tree count: ' + str(tree),(10,150),font,0.5,(255,255,0),1,cv2.LINE_AA)

**Comment by teffanymae** [comment]
last question.. T_T

how to resize the output video and image??

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. In future, please post this kind of support questions in Stackoverflow. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25619)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25619)

**Comment by mahamatnoumai** [comment]
> Thank you very much!! T_T
> 
> what I did is add this code at **756**
> 
> tree = (len(box_to_color_map.items()))
> cv2.putText(image,'Tree count: ' + str(tree),(10,150),font,0.5,(255,255,0),1,cv2.LINE_AA)

how to increment all count in the videos and finally print the total of all count 

@teffanymae  @aniketbote
