### ISSUE TITLE
MirroredStrategy, dataset sharding, notion of keras epoch - inconsistent and confusing

### ISSUE THREAD

**Issue by ksachdeva** [tensorflow/tensorflow#25620]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Both
- TensorFlow version (use command below): 1.12
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 1080 Ti

**Background**

While I understand that in machine learning community the notion/concept of epoch may vary a bit, one of the more widely adopted definition is - an epoch is to go over all the samples of the dataset once. To some extent it is consistent with keras api as where in the fit API we provide 'steps_per_epoch' as an indicator of when an 'epoch' is to be considered finished and most of the time steps_per_epoch is computed  to be equal to the number of batches of your training dataset.

[I also appreciate that this definition is bit lose because if one is performing augmentation then above given definition of epoch starts to get bit murky]

**Setup**

I am trying to perform multi-gpu training using MirroredStrategy and Keras. My setup is - one machine with multiple gpus. In other words, not using the ClusterSpec i.e. not really "distributed" amongst many different machines.

**Observed Behavior**

I would expect that if I have a dataset of 100 samples and 2 GPUs, MirroredStrategy would distribute 50 samples to each GPU. An epoch will be done when both GPUs would have seen 50 samples each. Each GPU will see a portion of dataset reserved for it. In other words, they would see distinct samples.

A quick look at the API (https://www.tensorflow.org/api_docs/python/tf/contrib/distribute/MirroredStrategy) makes you believe that if you set `auto_shard_dataset` to True you may achieve above goal. However, after looking in the source code I can see that `auto_shard_dataset` is taken into consideration when a multi-worker/cluster setup is used (https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/contrib/distribute/python/mirrored_strategy.py#L481).

This means that in my setup every GPUs would get 100 samples therefore the notion of 1 epoch in this case is essentially going over the dataset `twice` (but in parallel)

**Expected Behavior**

It is often interesting to evaluate the performance of a network after 1 epoch (given the more widely accepted definition/convention of epoch amongst others i.e. an epoch is to go over the dataset once). 

Given that MirroredStrategy does take the parameter `auto_shard_dataset` i.e. you (the tensorflow authors) did take notion of dividing the dataset in parts in consideration,  my question would be why it is not being used for the setup (1 machine multiple gpus) described above ?

**Comment by nikitamaia** [comment]
Hi @ksachdeva, I know this is a late response, but in case this is all still confusing, I hope this explanation helps.

If using tf.distribute.MirroredStrategy in TF2 with the Keras API, the behavior is what you expect. If you have 100 examples in a batch, and 2 GPUs, then each GPU will receive 50 examples. You can see this point [documented here](https://www.tensorflow.org/guide/distributed_training#using_tfdistributestrategy_with_tfkerasmodelfit). In multi-worker training, sharding data into multiple parts is needed to ensure convergence and performance, and the tf.distribute.Strategy API takes care of this automatically in a multi-worker set up at the file level (although you can disable the auto_shard_policy) but this is not needed when just using a single machine with multiple GPUs.

**Comment by ksachdeva** [comment]
Thanks @nikitamaia
