### ISSUE TITLE
tf.reshape function error using lambda layer in tensorflow backend keras

### ISSUE THREAD

**Issue by pachpandepriti** [tensorflow/tensorflow#25629]
Example - size of spectrum is (2240,1)
def rehape(spectrum):
    N_Sub=32
   spectrum=tf.manip.reshape(encode_complex,[(tf.size(encode_complex)/N_Sub),N_Sub])
   return spectrum
The resulting size is (2240,1) instead of (70,32)
Can anyone help me where I am going wrong?
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Sudeepam97** [comment]
> Example - size of spectrum is (2240,1)
> def rehape(spectrum):
> N_Sub=32
> spectrum=tf.manip.reshape(encode_complex,[(tf.size(encode_complex)/N_Sub),N_Sub])
> return spectrum

What is encode_complex? If you're trying to reshape `spectrum`, the command should be...
`spectrum = tf.manip.reshape(spectrum, [ (tf.size(spectrum) / N_Sub), N_Sub])`

Also, please keep in mind that this panel is meant for "code/doc bugs, performance issues, feature requests and build/installation issues". Your issue is essentially a question for [stackoverflow](https://stackoverflow.com/).

**Comment by pachpandepriti** [comment]
I tried that still doesn't work. I get same output

**Comment by jvishnuvardhan** [comment]
@pachpandepriti 
spectrum=tf.zeros([2240,1], tf.int32) 
N_Sub=32
spectrum = tf.manip.reshape(spectrum, [(tf.size(spectrum) / N_Sub), N_Sub])

Please note that reshape fun looks for a tensor as input. The above worked for me and the final shape was (70,32) as you are expecting.

In future, please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25629)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25629)
