### ISSUE TITLE
TopKV2 Op incorrectly requiring scalar input for k

### ISSUE THREAD

**Issue by wickstopher** [tensorflow/tensorflow#25621]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave 10.14.2
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): ('v1.12.0-rc2-3-ga6d8ffae09', '1.12.0')
- Python version: 2.7.10

**Describe the current behavior**
I want to be able to compute the top k results for different values of k in a batched evaluation metric. (e.g. for sample 1, compute top 2, sample 2 compute top 1, etc.)
tf.nn.top_k is throwing a `ValueError` despite clearly using the `TopKV2` op under the hood.

the following toy example illustrates the problem:

```
import tensorflow as tf

y_true = tf.constant([[0., 1., 1., 0], [0., 1., 0., 0.], [0., 0., 0., 1]])  
y_pred = tf.constant([[.1, 0.4, 0.4, .1], [.1, .7, .1, .1], [.1, .1, .1, .7]])

(confidences, indices) = tf.nn.top_k(y_pred, tf.constant([2, 1, 2]))
```

I get the following error: 

`ValueError: This Input must be scalar but has rank 1 for 'TopKV2_20' (op: 'TopKV2') with input shapes: [3,4], [3] and with computed input tensors: input[1] = <2 1 2>`

Diving into the source code, it would seem that the TopKV2 op is _precisely_ intended for varying values of k, however, something at a higher level is preventing my code from utilizing this functionality. Additionally, there is a `top_kv2` function in `gen_nn_ops.py` that is not exported for use.

**Describe the expected behavior**

That the TopKV2 op functions as specified, or that the `top_kv2` python binding is exposed.

**Comment by jvishnuvardhan** [comment]
@wickstopher the tf.nn.top_k op is expecting a scalar and you are providing a tensor. Please check an implementation [here](https://stackoverflow.com/questions/40808772/tensorflow-top-n-values-in-tensor) and [here](https://www.tensorflow.org/api_docs/python/tf/math/top_k) is the TF resource.

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
