### ISSUE TITLE
I want to reshape Tensor of shape[None,19,19,25] to [None,19,19,5,5] .Can anyone help me out

### ISSUE THREAD

**Issue by Alok-Baba** [tensorflow/tensorflow#25639]
I want to reshape Tensor of shape[None,19,19,25] to [None,19,19,5,5] .Can anyone help me out

**Comment by jvishnuvardhan** [comment]
import numpy as np
import tensorflow as tf
a=tf.placeholder(tf.int32,shape=[None,19,19,25],name='Const')
a2 = tf.reshape(a, [-1, 19,19,5,5])           # -1 means "all"
a2.shape

In future, Please post this kind of support questions in Stackoverflow as there is a big community to support.  GitHub is mainly for Build/Installation and Bug/Performance issues. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25639)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25639)
