### ISSUE TITLE
Tensorflow v1.13.0-rc1 compilation fails.  Bazel 0.19.0

### ISSUE THREAD

**Issue by nkdsoft** [tensorflow/tensorflow#25632]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: Source. 
- TensorFlow version:  v1.13.0-rc1
- Python version: 3.6
- Installed using:  within a conda virtual environment
- Bazel version: 0.19.0 /  0.19.2 / 0.20.0 / 0.21.0  (same results)
- GCC/Compiler version: 4.8.5
- CUDA/cuDNN version: 10.0
- GPU model and memory: RTX 2070 8,192 MB

**Describe the problem**
The compilation fails.  After running 
` bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/...`
I get the following output:
`
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
ERROR: /home/f/GithubProyects/tensorflow/tensorflow/python/keras/api/BUILD:9:1: file '//tensorflow/python/tools/api/generator:api_init_files.bzl' does not contain symbol 'KERAS_API_INIT_FILES'
ERROR: /home/f/GithubProyects/tensorflow/tensorflow/python/keras/api/BUILD:10:1: file '//tensorflow/python/tools/api/generator:api_init_files_v1.bzl' does not contain symbol 'KERAS_API_INIT_FILES_V1'
ERROR: /home/f/GithubProyects/tensorflow/tensorflow/python/keras/api/BUILD:16:20: Traceback (most recent call last):
	File "/home/f/GithubProyects/tensorflow/tensorflow/python/keras/api/BUILD", line 12
		gen_api_init_files(name = "keras_python_api_gen", api...", <5 more arguments>)
	File "/home/f/GithubProyects/tensorflow/tensorflow/python/keras/api/BUILD", line 16, in gen_api_init_files
		KERAS_API_INIT_FILES_V1
name 'KERAS_API_INIT_FILES_V1' is not defined
ERROR: /home/f/GithubProyects/tensorflow/tensorflow/python/keras/api/BUILD:33:20: Traceback (most recent call last):
	File "/home/f/GithubProyects/tensorflow/tensorflow/python/keras/api/BUILD", line 28
		gen_api_init_files(name = "keras_python_api_gen_com...", <7 more arguments>)
	File "/home/f/GithubProyects/tensorflow/tensorflow/python/keras/api/BUILD", line 33, in gen_api_init_files
		KERAS_API_INIT_FILES_V1
name 'KERAS_API_INIT_FILES_V1' is not defined
ERROR: /home/f/GithubProyects/tensorflow/tensorflow/python/keras/api/BUILD:50:20: Traceback (most recent call last):
	File "/home/f/GithubProyects/tensorflow/tensorflow/python/keras/api/BUILD", line 45
		gen_api_init_files(name = "keras_python_api_gen_com...", <7 more arguments>)
	File "/home/f/GithubProyects/tensorflow/tensorflow/python/keras/api/BUILD", line 50, in gen_api_init_files
		KERAS_API_INIT_FILES
name 'KERAS_API_INIT_FILES' is not defined (did you mean 'gen_api_init_files'?)
ERROR: package contains errors: tensorflow/python/keras/api
DEBUG: /home/f/.cache/bazel/_bazel_f/b274795d451be3987cc86fcb20dc5b5b/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
DEBUG: /home/f/.cache/bazel/_bazel_f/b274795d451be3987cc86fcb20dc5b5b/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:224:17: @//tensorflow/tools/lib_package:libtensorflow_jni: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/f/.cache/bazel/_bazel_f/b274795d451be3987cc86fcb20dc5b5b/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:224:17: @//tensorflow/tools/lib_package:common_deps: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/f/.cache/bazel/_bazel_f/b274795d451be3987cc86fcb20dc5b5b/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:224:17: @//tensorflow/tools/lib_package:cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/f/.cache/bazel/_bazel_f/b274795d451be3987cc86fcb20dc5b5b/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:224:17: @//tensorflow/tools/lib_package:eager_cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/f/.cache/bazel/_bazel_f/b274795d451be3987cc86fcb20dc5b5b/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:224:17: @//tensorflow/tools/lib_package:clib: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/f/.cache/bazel/_bazel_f/b274795d451be3987cc86fcb20dc5b5b/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:224:17: @//tensorflow/tools/lib_package:clicenses: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
ERROR: error loading package 'tensorflow/python/keras/api': Package 'tensorflow/python/keras/api' contains errors
INFO: Elapsed time: 3.717s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (417 packages loaded)
`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`
  cd ~/tensorflow
 ./configure 
 bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/...
`

**Additional Info**
Some weeks ago I compiled successfully tf v1.12 (and If i remember correctly also tf v1.13-rc0 with Cuda 10.0  and a previous Bazel version (0.17.2). 
This time (with v1.13-rc1) I first got an error saying that I needed Bazel >= 0.19.0  so thats why i installed that version. But now I have those Error messages...

**Comment by nkdsoft** [comment]
I am closing this issue. After deleting the tensorflow directory and cloning it again I don't get those errors anymore. Looks like there were some Bazel generated files in the folder (not tracket by git) that were causing the problems.    I have not been able to compile but now the errors are different.

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25632)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25632)
