### ISSUE TITLE
tf.rnn wrappers are incompatible with tf.keras.layers cells

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#25641]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed: binary
- TensorFlow version: `2.0.0-dev20190206`
- Python version: 3.6.6

**Describe the current behavior**

In the TensorFlow 2.0 preview, the `tf.rnn.DropoutWrapper` and `tf.rnn.ResidualWrapper` wrappers are incompatible with cells from `tf.keras.layers`. It raises an error for missing a `zero_state` method.

**Describe the expected behavior**

The classes in `tf.rnn` should be compatible with cells defined in `tf.keras.layers`.

**Code to reproduce the issue**

```python
import tensorflow as tf

cell = tf.keras.layers.LSTMCell(10)
cell = tf.rnn.ResidualWrapper(cell)
cell.get_initial_state(batch_size=4, dtype=tf.float32)
```

**Other info / logs**

```text
Traceback (most recent call last):
  File "test/rnn_v2.py", line 5, in <module>
    cell.get_initial_state(batch_size=4, dtype=tf.float32)
  File "/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 307, in get_initial_state
    return self.zero_state(batch_size, dtype)
  File "/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1545, in zero_state
    return self._cell.zero_state(batch_size, dtype)
AttributeError: 'LSTMCell' object has no attribute 'zero_state'
```

(If this API is not ready yet, please ignore this issue.)

**Comment by yongtang** [comment]
Added a PR #25646 for the fix.

**Comment by qlzh727** [comment]
This should be fixed by https://github.com/tensorflow/tensorflow/commit/76a22b340814425b6a8b6e0c0bb81bcd162c458b and https://github.com/tensorflow/tensorflow/commit/42a1de008f301fb2d4c575ef5f817b5513156328

**Comment by qlzh727** [comment]
Btw, the tf.rnn.* namespace has been moved to tf.nn.RNNCell* to consolidate the namespace.

**Comment by lycanthropes** [comment]
How about the progress?I also meet the same problems.

**Comment by jvishnuvardhan** [comment]
@lycanthropes As mentioned by @qlzh727 it was resolved in TF2.0.0-alpha0 by 
```
!pip install tensorflow==2.0.0-alpha0
import tensorflow as tf

cell = tf.keras.layers.LSTMCell(10)
cell = tf.nn.RNNCellResidualWrapper(cell)
cell.get_initial_state(batch_size=4, dtype=tf.float32)
```

**Comment by alexv1247** [comment]
I have the same issues with the dropoutwrapper in 1.13. 
it states that a lstm cell has no attribute zero state.

**Comment by qlzh727** [comment]
Btw, the tf.nn.RNNCell*Wrapper has different implementation between v1 and v2 TF binary. You will probably still hit the same issue if you are using TF 1.x binary.
