### ISSUE TITLE
Keras Concatenate : AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by sangeet259** [tensorflow/tensorflow#25659]
I am using Google Colab.
Here is a small code I have written:
```python
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout, Conv1D, Reshape, Concatenate

branch1 = Sequential()
branch1.add(Conv1D(2,3,activation='tanh',input_shape=(100, 1)))
branch1.add(Conv1D(4,3,activation='tanh'))
branch1.add(Conv1D(6,3,activation='tanh'))
branch1.add(Dropout(0.2))
branch1.add(Conv1D(8,3,activation='tanh'))
branch1.add(Conv1D(10,3,activation='relu'))
branch1.add(Flatten())
branch1.add(Dense(10))


branch2 = Sequential()
branch2.add(Dense(10,input_dim=1))
branch2.add(Dense(10,activation='linear'))

# Concatenate([branch1,branch2])


model = Sequential()
model.add(Concatenate([branch1, branch2]))
model.add(Dense(1,activation='relu'))
# branch1.add(Dropout(0.4))
model.add(Dense(1,activation='relu'))
model.compile(loss='mean_squared_error', optimizer='rmsprop')

model_info = model.fit([data_cnn,data_mw], target, epochs=1000, batch_size=100, verbose=2,validation_data=([val_data_cnn,val_data_mw],val_target))
```

Some Info about data : 
*  `data_cnn` : type = numpy.ndarray | shape = (2580, 100, 1) 
*  `data_mw` : type = numpy.ndarray | shape = (2580, 1)
*  `val_data_cnn` : type = numpy.ndarray | shape = (645, 100, 1)
*  `val_data_mw` : type = numpy.ndarray | shape = (645, 1)

Link to the notebook : https://colab.research.google.com/drive/1kpopbk_4u7Tsuaxoc9EbRCKzN1aZ4kSM

**Comment by sangeet259** [comment]
And here is the traceback that I got:
```python
AttributeError                            Traceback (most recent call last)
<ipython-input-93-668d2c5caf25> in <module>()
      1 
----> 2 model_info = model.fit([data_cnn,data_mw], target, epochs=1000, batch_size=100, verbose=2,validation_data=([val_data_cnn,val_data_mw],val_target))

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, max_queue_size, workers, use_multiprocessing, **kwargs)
    774         steps=steps_per_epoch,
    775         validation_split=validation_split,
--> 776         shuffle=shuffle)
    777 
    778     # Prepare validation data.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, check_steps, steps_name, steps, validation_split, shuffle)
   2287         else:
   2288           cast_inputs = x
-> 2289         self._set_inputs(cast_inputs)
   2290     else:
   2291       dict_inputs = isinstance(self.inputs, dict)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpointable/base.py in _method_wrapper(self, *args, **kwargs)
    440     self._setattr_tracking = False  # pylint: disable=protected-access
    441     try:
--> 442       method(self, *args, **kwargs)
    443     finally:
    444       self._setattr_tracking = previous_value  # pylint: disable=protected-access

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _set_inputs(self, inputs, outputs, training)
   2501         input_shape = (None,)
   2502       else:
-> 2503         input_shape = (None,) + tuple(inputs.shape[1:])
   2504       self._build_input_shape = input_shape
   2505 

AttributeError: 'list' object has no attribute 'shape'
```

**Comment by Sudeepam97** [comment]
`model.fit` requires numpy arrays. This error occurs when you are using normal python lists and not numpy arrays. You might want to check if `data_cnn`, `data_mw` etc. were all initialized as proper numpy arrays using `np.array()`.

**Comment by sangeet259** [comment]
Hey, @Sudeepam97 they are indeed proper numpy arrays. 
And I don't need to concatenate the arrays. I need to pass multiple inputs to my models.
So I don't see how `np.concatenate would help :confused:

**Comment by Sudeepam97** [comment]
`data_cnn` and `data_mw` are numpy arrays, your error is because of the fact that writing
`[data_cnn, data_mw]` concatenates them and returns a python list.

Try to run this to get a better understanding of what I mean...
`import numpy as np`
`a = np.array([ [[1, 2]], [[2, 3]], [[3, 4]] ])`
`print (a)`
`print (a.shape)`
`b = np.array([ [[2]], [[3]], [[4]] ])`
`print (a)`
`print (b.shape)`
`c = [a, b]`
`print (c)`
`print (c.shape)`

**Comment by sangeet259** [comment]
I get that `[data_cnn, data_mw]` is a list. 
But **that is how you are supposed to** pass inputs to the `model.fit()` in case your model has multiple inputs. _(If you see my model definition you can see there are two branches which I accept two inputs)_

See this : https://stackoverflow.com/a/43196972/6507303

Also see the Concatenation documentation at : https://keras.io/layers/merge/#Concatenate
It says it accepts "a list of inputs".

**Comment by Sudeepam97** [comment]
> I get that `[data_cnn, data_mw]` is a list.
> But **that is how you are supposed to** pass inputs to the `model.fit()` in case your model has multiple inputs. _(If you see my model definition you can see there are two branches which I accept two inputs)_
> 
> See this : https://stackoverflow.com/a/43196972/6507303
> 
> Also see the Concatenation documentation at : https://keras.io/layers/merge/#Concatenate
> It says it accepts "a list of inputs".

Oh, pardon me. Indeed in this case, this is how you'll pass inputs to `fit()`. I can't help you any more without actually running your code and I'll have to study this architecture so please allow some time. Meanwhile, Someone else may also help you out. As a final note, I am not observing any `model.compile` statement, maybe your error is because your model with two inputs is not compiled?

**Comment by sangeet259** [comment]
Sorry, I forgot to include the `compile()` here. It's there in the actual code.
Doesn't make a difference.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
