### ISSUE TITLE
Distributed training using grpc+verbs got an assertion in verbs/rdma.cc:1557

### ISSUE THREAD

**Issue by highfly22** [tensorflow/tensorflow#25656]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
Custom code using tf.estimator.DNNLinearCombinedClassifier
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): privileged ubuntu 16.04 docker 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
source built with verbs feature
bazel build --config=mkl -c opt --config=verbs //tensorflow/tools/pip_package:build_pip_package

- TensorFlow version (use command below): 1.12.0
- Python version: python3.6
- Bazel version (if compiling from source): 0.18
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10)
- CUDA/cuDNN version: N/A
- GPU model and memory: CPU only

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

b'v1.12.0-5-g7317495' 1.12.0

**Describe the current behavior**
I deployed one chief, one PS and one worker with protocol 'grpc+verbs'. This case uses only CPU device. The master and PS works properly. The worker meets an assertion, and exits.
Switched to protocol grpc, the code works well.
The result of rping shows that RDMA configure is good.

```
2019-02-11 14:16:19.248897: F tensorflow/contrib/verbs/rdma.cc:1557] Check failed: mr_ != nullptr  No memory region found for address 0x7f1b40000bc0: /job:ps/replica:0/task:0/device:CPU:0;dc5bce4913999973;/job:worker/replica:0/task:0/device:CPU:0;edge_247_report_uninitialized_variables_1/VarIsInitializedOp_4;0:0
```

**Describe the expected behavior**
The worker should run normally.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
    server = tf.train.Server(cluster_spec,
                           job_name=job_name,
                           task_index=task_index,
                            protocol = 'grpc+verbs')

  estimator = tf.estimator.DNNLinearCombinedClassifier(...)
  estimator.train()
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[worker-20190211-141600.log](https://github.com/tensorflow/tensorflow/files/2850045/worker-20190211-141600.log)

**Comment by preethivenkatesh** [comment]
@highfly22 Could you please check if this workload runs free of errors in a non-mkl build?

**Comment by highfly22** [comment]
It seems the contrib/verbs modules is out of date. 

The method RdmaMgr::RegMemVisitors of verbs/rdma_mgr.cc try to register allocation visitor in the ProcessState. But the ProcessState allocator is not the default one any more.

I added a class ProcessStateAllocatorFactory, and register this class. Then the assertion dismissed.
This issue will appear in the mkl build.

```
namespace {
class ProcessStateAllocatorFactory : public AllocatorFactory {
 public:
  Allocator* CreateAllocator() {
    return ProcessState::singleton()->GetCPUAllocator(0);
  }

  SubAllocator* CreateSubAllocator(int numa_node) {
    return 0;
  }
};

REGISTER_MEM_ALLOCATOR("ProcessStateCPUAllocator", 200, ProcessStateAllocatorFactory);
}
```

**Comment by byronyi** [comment]
I believe it’s fixed in current master with #24250. Could you try again?

**Comment by byronyi** [comment]
@jvishnuvardhan I believe this issue has been fixed. Could you close it?

**Comment by jvishnuvardhan** [comment]
Thanks @byronyi . I am closing the issue. Thanks!
