### ISSUE TITLE
Trigger point of object detection in tensorflow lite

### ISSUE THREAD

**Issue by chiragmak10** [tensorflow/tensorflow#25667]
I am doing object detection using tensorflow  lite. My code detects the object & add a label with it & also display the label with it, but after that, I want to display the label of an object which is detected separately.
& I want that point (trigger point) in code from where the label is displayed .
can you please help me to find out code .
 I am giving link of  my source code :
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/android

**Comment by jvishnuvardhan** [comment]
@chiragmak10 Could you mention more details about the issue and its context. Please provide as many details as possible to find a solution faster. Also, I noticed that you forgot to provide link to your source code. The link you provided is from TF Lite examples. Thanks!

**Comment by anilmaddala** [comment]
@chiragmak10 If your referring to the label on the tracked output, its being set at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/android/app/src/main/java/org/tensorflow/demo/tracking/MultiBoxTracker.java#L188

**Comment by jvishnuvardhan** [comment]
Closing this support issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). Thanks!
