### ISSUE TITLE
TFL Detect app crash while using NNAPI

### ISSUE THREAD

**Issue by sarmadidrees** [tensorflow/tensorflow#25660]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **Xiaomi Mi 8**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **1.12**
- Python version: **3.5**
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: **9.0/7.5**
- GPU model and memory: **GTX 1050 - 4GB**

**Describe the current behavior**
I am trying to build the [TF Lite detect app](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/android) with using NNAPI, but when I set useNNAPI to **true** it crashes with an exception:
`Process: org.tensorflow.lite.demo, PID: 32661
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: 
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:145)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:229)
        at org.tensorflow.demo.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:196)
        at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:247)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

But, when I set useNNAPI to **false** it runs without any issue. On the other hand, I also tried to use NNAPI with [TFL Classifier app](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/android/app/src/main/java/org/tensorflow/demo/TFLiteImageClassifier.java) and it runs flawlessly (it means there is no problem with my phone). The question is that, is it possible to use NNAPI with detector app or not? 

**Code to reproduce the issue**
Changed few lines in [TFLiteObjectDetectionAPIModel.java](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/android/app/src/main/java/org/tensorflow/demo/TFLiteObjectDetectionAPIModel.java#L120):
`
d.tfliteOptions.setUseNNAPI(true);
    try {
       d.tfLite = new Interpreter(loadModelFile(assetManager, modelFilename), d.tfliteOptions);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by freedomtan** [comment]
Post-processing ops of the model used by the App are not supported by NNAPI.

**Comment by sarmadidrees** [comment]
Thanks for your answer. Do you have any update when will NNAPI support that Post-processing op?

**Comment by jdduke** [comment]
The new NNAPI delegate should support this path, and doesn't require the full model be delegated.
