### ISSUE TITLE
Type Error caused by using AttentionCellWrapper: Tensors cannot be iterated.

### ISSUE THREAD

**Issue by yhshu** [tensorflow/tensorflow#25665]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Manjaro Illyria 18.0.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:no mobile device related
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below): ('v1.12.0-0-ga6d8ffae09', '1.12.0')
- Python version:2.7.15
- Bazel version (if compiling from source):installed from binary
- GCC/Compiler version (if compiling from source):installed from binary
- CUDA/cuDNN version:no CUDA
- GPU model and memory:no computing GPU

**Describe the current behavior**
I am trying to add tf.contrib.rnn.AttentionCellWrapper to tf.nn.rnn_cell.GRUCell. Before adding the wrapper, the program is completely running normally. After adding the wrapper, the program reports an error shown in the traceback below.

The error `Tensor objects are only iterable when eager execution is enabled` is confusing me, since I have tried enable the eager execution and the results are the same.
I have changed GRUCell to LSMMCell or other RNN-related Cell and the results are the same.
I have tried multiple tensorflow versions and the results are the same.
The code I am modifying is the same as [this code](https://github.com/Songweiping/GRU4Rec_TensorFlow/blob/master/model.py), and what I am trying is to add AttentionCellWrapper between 126 and 127 lines.

**Describe the expected behavior**
The program should just work fine without any error. All the changes I made compared to the normal code were to add the AttentionCellWrapper.
The official documentation also has no explanation for the cause of this error.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

As described above, the normal code with a AttentionCellWrapper, and the function that triggered the error is as follows. The complete code also covers other files in the [repo](https://github.com/Songweiping/GRU4Rec_TensorFlow).

```
def build_model(self):
        
        self.X = tf.placeholder(tf.int32, [self.batch_size], name='input')
        self.Y = tf.placeholder(tf.int32, [self.batch_size], name='output')
        self.state = [tf.placeholder(tf.float32, [self.batch_size, self.rnn_size], name='rnn_state') for _ in xrange(self.layers)]
        self.global_step = tf.Variable(0, name='global_step', trainable=False)

        with tf.variable_scope('gru_layer'):
            sigma = self.sigma if self.sigma != 0 else np.sqrt(6.0 / (self.n_items + self.rnn_size))
            if self.init_as_normal:
                initializer = tf.random_normal_initializer(mean=0, stddev=sigma)
            else:
                initializer = tf.random_uniform_initializer(minval=-sigma, maxval=sigma)
            embedding = tf.get_variable('embedding', [self.n_items, self.rnn_size], initializer=initializer)
            softmax_W = tf.get_variable('softmax_w', [self.n_items, self.rnn_size], initializer=initializer)
            softmax_b = tf.get_variable('softmax_b', [self.n_items], initializer=tf.constant_initializer(0.0))

            cell = rnn_cell.GRUCell(self.rnn_size, activation=self.hidden_act)
            attn_cell = tf.contrib.rnn.AttentionCellWrapper(cell, attn_length=20)  # state_is_tuple is True by default
            drop_cell = rnn_cell.DropoutWrapper(attn_cell, output_keep_prob=self.dropout_p_hidden)
            stacked_cell = rnn_cell.MultiRNNCell([drop_cell] * self.layers)
            
            inputs = tf.nn.embedding_lookup(embedding, self.X)
            output, state = stacked_cell(inputs, tuple(self.state))
            self.final_state = state

        if self.is_training:
            '''
            Use other examples of the minibatch as negative samples.
            '''
            sampled_W = tf.nn.embedding_lookup(softmax_W, self.Y)
            sampled_b = tf.nn.embedding_lookup(softmax_b, self.Y)
            logits = tf.matmul(output, sampled_W, transpose_b=True) + sampled_b
            self.yhat = self.final_activation(logits)
            self.cost = self.loss_function(self.yhat)
        else:
            logits = tf.matmul(output, softmax_W, transpose_b=True) + softmax_b
            self.yhat = self.final_activation(logits)

        if not self.is_training:
            return

        self.lr = tf.maximum(1e-5,tf.train.exponential_decay(self.learning_rate, self.global_step, self.decay_steps, self.decay, staircase=True)) 
        
        '''
        Try different optimizers.
        '''
        #optimizer = tf.train.AdagradOptimizer(self.lr)
        optimizer = tf.train.AdamOptimizer(self.lr)
        #optimizer = tf.train.AdadeltaOptimizer(self.lr)
        #optimizer = tf.train.RMSPropOptimizer(self.lr)

        tvars = tf.trainable_variables()
        gvs = optimizer.compute_gradients(self.cost, tvars)
        if self.grad_cap > 0:
            capped_gvs = [(tf.clip_by_norm(grad, self.grad_cap), var) for grad, var in gvs]
        else:
            capped_gvs = gvs 
        self.train_op = optimizer.apply_gradients(capped_gvs, global_step=self.global_step)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "/home/syh/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/183.5429.31/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/syh/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/183.5429.31/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/syh/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/183.5429.31/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/run/media/syh/0D11080D0D11080D/workspace/Recommender-System/exp/GRU4Rec_TensorFlow-master/main.py", line 86, in <module>
    gru4rec = model.GRU4Rec(sess, args)
  File "/run/media/syh/0D11080D0D11080D/workspace/Recommender-System/exp/GRU4Rec_TensorFlow-master/model.py", line 72, in __init__
    self.build_model()
  File "/run/media/syh/0D11080D0D11080D/workspace/Recommender-System/exp/GRU4Rec_TensorFlow-master/model.py", line 142, in build_model
    output, state = multi_cell(inputs, tuple(self.state))
  File "/run/media/syh/0D11080D0D11080D/workspace/Recommender-System/exp/venv/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 233, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/run/media/syh/0D11080D0D11080D/workspace/Recommender-System/exp/venv/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/run/media/syh/0D11080D0D11080D/workspace/Recommender-System/exp/venv/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/run/media/syh/0D11080D0D11080D/workspace/Recommender-System/exp/venv/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1486, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/run/media/syh/0D11080D0D11080D/workspace/Recommender-System/exp/venv/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1282, in __call__
    output, new_state = self._cell(inputs, state, scope=scope)
  File "/run/media/syh/0D11080D0D11080D/workspace/Recommender-System/exp/venv/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 233, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/run/media/syh/0D11080D0D11080D/workspace/Recommender-System/exp/venv/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/run/media/syh/0D11080D0D11080D/workspace/Recommender-System/exp/venv/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/run/media/syh/0D11080D0D11080D/workspace/Recommender-System/exp/venv/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/rnn_cell.py", line 1190, in call
    state, attns, attn_states = state
  File "/run/media/syh/0D11080D0D11080D/workspace/Recommender-System/exp/venv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 459, in __iter__
    "Tensor objects are only iterable when eager execution is "
TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.
```

**Comment by drpngx** [comment]
Could you:

    * print out what "state" is?
    * trace down where the state comes from and who creates it?

**Comment by lzw429** [comment]
`state`: `<type 'tuple'>: (<tf.Tensor 'rnn_state:0' shape=(50, 100) dtype=float32>,)`
\_\_len\_\_ = 1

`state` is returned by this statement `output, state = multi_cell(inputs, tuple(self.state))`
where 
`self.state = [tf.placeholder(tf.float32, [self.batch_size, self.rnn_size], name='rnn_state') for _ in xrange(self.layers)]`
`multi_cell = rnn_cell.MultiRNNCell([cell] * self.layers)`
`inputs = tf.nn.embedding_lookup(embedding, self.X)`

`state` is created by `class RNNCell` in `tensorflow/python/ops/rnn_cell_impl.py`
However, I can't see `state` is created by which statement in class `RNNCell` through the debugger.

**Comment by ibunny01** [comment]
I come across the same issue with you, but I was trying to use `AttentionCellWrapper` for `tf.nn.dynamic_rnn`:
```python
                # RNN
                gru_cell = rnn.GRUCell((self.rnn_size), activation=self.hidden_act)
                # attention
                if self.ATTENTION:
                    atten_cell = rnn.AttentionCellWrapper(gru_cell, attn_length=40, state_is_tuple=True)
                    drop_cell = rnn.DropoutWrapper(atten_cell, output_keep_prob=self.dropout)
                else:
                    drop_cell = rnn.DropoutWrapper(gru_cell, output_keep_prob=self.dropout)
                
                rnn_outputs, final_state = tf.nn.dynamic_rnn(drop_cell, inputs, sequence_length=self.seqlen,
                                                            initial_state=self.init_state)
                
```
If `self.ATTENTION` is False, everything is ok, but once added `AttentionCellWrapper` to the cell, it would get the same error message above.

**Comment by lzw429** [comment]
> I come across the same issue with you, but I was trying to use `AttentionCellWrapper` for `tf.nn.dynamic_rnn`:
> 
> ```python
>                 # RNN
>                 gru_cell = rnn.GRUCell((self.rnn_size), activation=self.hidden_act)
>                 # attention
>                 if self.ATTENTION:
>                     atten_cell = rnn.AttentionCellWrapper(gru_cell, attn_length=40, state_is_tuple=True)
>                     drop_cell = rnn.DropoutWrapper(atten_cell, output_keep_prob=self.dropout)
>                 else:
>                     drop_cell = rnn.DropoutWrapper(gru_cell, output_keep_prob=self.dropout)
>                 
>                 rnn_outputs, final_state = tf.nn.dynamic_rnn(drop_cell, inputs, sequence_length=self.seqlen,
>                                                             initial_state=self.init_state)
>                 
> ```
> 
> If `self.ATTENTION` is False, everything is ok, but once added `AttentionCellWrapper` to the cell, it would get the same error message above.

If the architecture of your model is seq2seq, maybe you could try to use tf.contrib.seq2seq.AttentionWrapper instead.

**Comment by ibunny01** [comment]
> > I come across the same issue with you, but I was trying to use `AttentionCellWrapper` for `tf.nn.dynamic_rnn`:
> > ```python
> >                 # RNN
> >                 gru_cell = rnn.GRUCell((self.rnn_size), activation=self.hidden_act)
> >                 # attention
> >                 if self.ATTENTION:
> >                     atten_cell = rnn.AttentionCellWrapper(gru_cell, attn_length=40, state_is_tuple=True)
> >                     drop_cell = rnn.DropoutWrapper(atten_cell, output_keep_prob=self.dropout)
> >                 else:
> >                     drop_cell = rnn.DropoutWrapper(gru_cell, output_keep_prob=self.dropout)
> >                 
> >                 rnn_outputs, final_state = tf.nn.dynamic_rnn(drop_cell, inputs, sequence_length=self.seqlen,
> >                                                             initial_state=self.init_state)
> >                 
> > ```
> > 
> > 
> > If `self.ATTENTION` is False, everything is ok, but once added `AttentionCellWrapper` to the cell, it would get the same error message above.
> 
> If the architecture of your model is seq2seq, maybe you could try to use tf.contrib.seq2seq.AttentionWrapper instead.

Thanks for your suggestion, but I'm not trying to build a `seq2seq`, my model is for item recommendation, so I don't need a decoder (or in other word my decoder is just an item embedding vector which is doing inner product with the RNN encoder's output vector) . And what I'm doing is trying to add Attention mechanism to my RNN encoder (GRU/LSTM), so in this kind of situation, what kind of wrapper should I use? ( I've tried `AttentionCellWrapper` but it got me wrong )

**Comment by lzw429** [comment]
> > > I come across the same issue with you, but I was trying to use `AttentionCellWrapper` for `tf.nn.dynamic_rnn`:
> > > ```python
> > >                 # RNN
> > >                 gru_cell = rnn.GRUCell((self.rnn_size), activation=self.hidden_act)
> > >                 # attention
> > >                 if self.ATTENTION:
> > >                     atten_cell = rnn.AttentionCellWrapper(gru_cell, attn_length=40, state_is_tuple=True)
> > >                     drop_cell = rnn.DropoutWrapper(atten_cell, output_keep_prob=self.dropout)
> > >                 else:
> > >                     drop_cell = rnn.DropoutWrapper(gru_cell, output_keep_prob=self.dropout)
> > >                 
> > >                 rnn_outputs, final_state = tf.nn.dynamic_rnn(drop_cell, inputs, sequence_length=self.seqlen,
> > >                                                             initial_state=self.init_state)
> > >                 
> > > ```
> > > 
> > > 
> > > If `self.ATTENTION` is False, everything is ok, but once added `AttentionCellWrapper` to the cell, it would get the same error message above.
> > 
> > 
> > If the architecture of your model is seq2seq, maybe you could try to use tf.contrib.seq2seq.AttentionWrapper instead.
> 
> Thanks for your suggestion, but I'm not trying to build a `seq2seq`, my model is for item recommendation, so I don't need a decoder (or in other word my decoder is just an item embedding vector which is doing inner product with the RNN encoder's output vector) . And what I'm doing is trying to add Attention mechanism to my RNN encoder (GRU/LSTM), so in this kind of situation, what kind of wrapper should I use? ( I've tried `AttentionCellWrapper` but it got me wrong )

In fact, this is also what I am trying to do. But I did not find that TensorFlow r1.12 has any similar wrapper. And of course, pytorch does not have a similar wrapper...

**Comment by lzw429** [comment]
This issue persists after updating the tensorflow version to 1.13.1.

**Comment by eric-0x72** [comment]
Any updates on this?

**Comment by lzw429** [comment]
> Any updates on this?

In fact, the API has been canceled in tensorflow 2.0 and the problem has not been resolved.

**Comment by eric-0x72** [comment]
> > Any updates on this?
> 
> In fact, the API has been canceled in tensorflow 2.0 and the problem has not been resolved.

Good to know. Thanks

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
