### ISSUE TITLE
NNAPI does not accept the reshape operation with the -1 parameter

### ISSUE THREAD

**Issue by AndrzejKRK** [tensorflow/tensorflow#25661]
**System information**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
* Mobile device: Xiaomi Mi MIX 2S (Android 9, API 28)
* TensorFlow Lite version on Android: 0.0.0-gpu-experimental

**Provide the text output from tflite_convert**

```
tflite_convert \
--graph_def_file=tflite_graph.pb \
--output_file=detect.tflite \
--input_shapes=1,300,300,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='raw_outputs/class_predictions','raw_outputs/box_encodings' \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 \
--std_dev_values=128 \
--change_concat_input_ranges=false \
--allow_custom_ops
```

**Describe the current behavior**

I use SSD mobilenet V1 model from [zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md). When I try to use this model in an Android application using NNAPI, I get an error message. The problem is that the Reshape operation has the new shape [1, -1, 91]. Will it be possible to use Reshape with the -1 parameter in NNAPI. And is it possible to change this parameter to static without retraining the model?

**Comment by singhniraj08** [comment]
@AndrzejKRK,

As mentioned in [Android developers website](https://developer.android.com/ndk/guides/neuralnetworks#tensors_of_unknown_rank), 
Android 9 (API level 28) introduced model operands of unknown dimensions but known rank (the number of dimensions). Android 10 (API level 29) introduced tensors of unknown rank, as shown in [ANeuralNetworksOperandType](https://developer.android.com/ndk/reference/struct/a-neural-networks-operand-type).

Hope this helps. Thank you!
