### ISSUE TITLE
Docker images with tags `1.13.0rc0` and `1.13.0rc0-py3` contains wrong version of TensorFlow Estimator

### ISSUE THREAD

**Issue by dmitrievanthony** [tensorflow/tensorflow#25669]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 17.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **-**
- TensorFlow installed from (source or binary): **Binary/Docker**
- TensorFlow version: **???**
- Python version: **2.7**, **3.5**
- Installed using virtualenv? pip? conda?: **Docker**
- Bazel version (if compiling from source): **-**
- GCC/Compiler version (if compiling from source): **-**
- CUDA/cuDNN version: **-**
- GPU model and memory: **-**

The problem is that Docker [images](https://hub.docker.com/r/tensorflow/tensorflow/tags) with tags `1.13.0rc0` and `1.13.0rc0-py3` contains wrong version of `tensorflow_estimator` (this [repository](https://github.com/tensorflow/estimator)).

Just to show:
```
$ docker run -it tensorflow/tensorflow:1.13.0rc0 bash

________                               _______________                
___  __/__________________________________  ____/__  /________      __
__  /  _  _ \_  __ \_  ___/  __ \_  ___/_  /_   __  /_  __ \_ | /| / /
_  /   /  __/  / / /(__  )/ /_/ /  /   _  __/   _  / / /_/ /_ |/ |/ / 
/_/    \___//_/ /_//____/ \____//_/    /_/      /_/  \____/____/|__/

root@d1f1dd416bdd:/# pip show tensorflow_estimator
pip show tensorflow_estimator
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Name: tensorflow-estimator
Version: 1.10.12
```

**Comment by dmitrievanthony** [comment]
I guess it's related to https://github.com/tensorflow/tensorflow/issues/25611.

**Comment by angersson** [comment]
Hmm. I'm not sure if we can handle this in a good way. TF submodules like `tensorflow-estimator`  aren't guaranteed (as far as I know) to have a pre-release version that aligns with TensorFlow's prerelease versions. And they're not guaranteed to be available when the final images are built, either -- they're not orchestrated by the same release team, I don't think.

One possible fix would be to adjust the CI such that Docker images based on pre-releases provide `--pre` to `pip install`, although that would apply to every available package specified in the command line.

@gunan, do you have any thoughts on this?

**Comment by dmitrievanthony** [comment]
Actually, this problem was already discussed in https://github.com/tensorflow/tensorflow/issues/25165 and it looks like the correct version of estimator in our case is [1.13.0rc0](https://pypi.org/project/tensorflow-estimator/1.13.0rc0/).

My problem is that without correct version of `estimator` some functionality of distributed learning doesn't work in `tensorflow`. In my local case I fixed it building Docker image with `pip3 install tensorflow_estimator==1.13.0rc0` layer. 

Besides, Docker image of `tensorflow` version `1.13.0rc1` seems to have a correct version of `estimator` out of the box.

**Comment by angersson** [comment]
Oh, I see. I forgot about the Pip installation specifications.

It looks like the dependency was incorrectly specified in rc0. That's a bug in TF, not in the Docker containers, so I don't think this needs any attention, especially since rc1 is working fine.
