### ISSUE TITLE
Android Example utils fail on models > 64MB

### ISSUE THREAD

**Issue by kuza55** [tensorflow/tensorflow#2566]
I've been trying to get started with tensorflow and I wanted to use an image recognition model I trained in the android example, but when I tried to replace the models in the example with my model, it would crash without a lot of information.

I finally figure out that ReadFileToProto in jni_utils.cc does not support reading files larger than 64MB: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/jni/jni_utils.cc#L107

Adding these lines seemed to fix the issue of not being able to load my graph at all:

    ::google::protobuf::io::CodedInputStream coded_stream(&adaptor);
    coded_stream.SetTotalBytesLimit(1024LL << 20, 512LL << 20);

    coded_stream.Skip(start);
    CHECK(message->ParseFromCodedStream(&coded_stream));

I'm probably not the first to stumble into this problem, but I feel like I just wasted hours of my life on a trivially avoidable problem and I hope no-one else has to waste time on that little bit of protobuf trivia.

**Comment by aselle** [comment]
There are some known issues with protobuf and large files that we need to work on. Thank you for tracking it down and the report.

**Comment by petewarden** [comment]
Thanks for the report @kuza55! I'll work on getting a patch into the Android example.

**Comment by petewarden** [comment]
I've got your suggested fix checked in @kuza55, thanks for that. I'm closing this as fixed.

**Comment by petewarden** [comment]
This should actually be fixed now.
