### ISSUE TITLE
Functional safety compliance

### ISSUE THREAD

**Issue by abhi278** [tensorflow/tensorflow#25687]
We want to use Tensorflow for building Deep Learning based models in production for Automotive. 
The Automotive industry requires strict compliance with ISO 26262 for functional safety.

One of the clause in ISO 26262 is “the classification of all the software tools used in development shall be performed according to ISO 26262-8, clause 11 ‘Confidence in the use of software tools’”.
Such classification report basically means the tool (in this case Tensorflow) is functionally safe to use.

Is it possible to get such a classification report for Tensorflow? Whom to contact for this topic
Thanks.

**Comment by MarkDaoust** [comment]
Hi @abhi278,  

Please see: https://github.com/tensorflow/tensorflow/blob/master/LICENSE#L145

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25687)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25687)
