### ISSUE TITLE
Running the transformer model with Tensor2Tensor using Mesh-Tensorflow(GPU implementation)

### ISSUE THREAD

**Issue by Raviteja1996** [tensorflow/tensorflow#25686]
Hello I posted the below concern in mesh-tensorflow and tensor2tensor GitHub issues but did not get any response. So I am posting here if any one can help me about this issue.

I am trying to run the transformer model with Tensor2tensor using mesh-tensorflow (GPU-implementation) but I am facing few errors.

I am attaching my error log also.

**steps to reproduce:**

PROBLEM=translate_enfr_wmt32k
MODEL=mtf_transformer
HPARAMS=mtf_transformer_paper_tr_0_mesh_8
DATA_DIR=$HOME/t2t_data
TMP_DIR=/tmp/t2t_datagen
TRAIN_DIR=$HOME/t2t_train/$PROBLEM/$MODEL-$HPARAMS
mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

datagen:
t2t-datagen \
--data_dir=$DATA_DIR \
--tmp_dir=$TMP_DIR \
--problem=$PROBLEM

train:
t2t-trainer \
--data_dir=$DATA_DIR \
--problem=$PROBLEM \
--model=$MODEL \
--hparams_set=$HPARAMS \
--output_dir=$TRAIN_DIR \
--train_steps=10
[mesh-error.txt](https://github.com/tensorflow/tensorflow/files/2854483/mesh-error.txt)

**Comment by Raviteja1996** [comment]
Hello any updates yet?

**Comment by jvishnuvardhan** [comment]
@Raviteja1996 Please 
This is not related to TensorFlow Core.  This repo is mainly for addressing bugs in installation and performance related to TF Core.  
Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. Thanks!
