### ISSUE TITLE
Compile issue for TF Lite for Android NDK wit TF ops enabled

### ISSUE THREAD

**Issue by tbirn** [tensorflow/tensorflow#25688]
**System information**
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: v1.13.0-rc0
- Python version: 3
- Bazel version: 0.21.0
- GCC/Compiler version (if compiling from source): NDK r14b, r18b, clang
- CUDA/cuDNN version: -
- GPU model and memory: -
- Android SDK/NDK API level: 21

**When trying to build TFlite as shared library for Android with the experimental TF ops enabled, I get an compile error**

**Steps**

Added the Android target to the _tensorflow/lite/BUILD_:
```
cc_binary( 
    name = "libtensorflowLite.so",
    linkopts=[
        "-shared", 
        "-Wl,-soname=libtensorflowLite.so",
    ],
    linkshared = 1,
    copts = tflite_copts(),
    deps = [
        ":framework",
        "//tensorflow/lite/kernels:builtin_ops",
        "//tensorflow/lite/delegates/flex:delegate"
    ],
)
```
I added the _flex_delegate_ as documented  [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/using_select_tf_ops.md)

Build with command:
```
bazel build //tensorflow/lite:libtensorflowLite.so --crosstool_top=//external:android/crosstool --cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11"
```

I tried with NDK version r18b and r14b 

**Any other info / logs**

This is the important part of the log:
```
[0m [91m[562 / 928] Compiling tensorflow/core/kernels/cwise_op_add_1.cc; 46s local ... (2 actions, 1 running)
[0m [91m[573 / 928] Compiling tensorflow/core/kernels/cwise_op_mul_1.cc; 22s local ... (2 actions running)
[0m [91m[574 / 928] Compiling tensorflow/core/kernels/cwise_op_mul_1.cc; 152s local ... (2 actions running)
[0m [91m[574 / 928] Compiling tensorflow/core/kernels/cwise_op_mul_1.cc; 301s local ... (2 actions running)
[0m [91m[574 / 928] Compiling tensorflow/core/kernels/cwise_op_mul_1.cc; 474s local ... (2 actions running)
[0m [91m[574 / 928] Compiling tensorflow/core/kernels/cwise_op_mul_1.cc; 672s local ... (2 actions running)
[0m [91m[574 / 928] Compiling tensorflow/core/kernels/cwise_op_mul_1.cc; 900s local ... (2 actions running)
[0m [91m[574 / 928] Compiling tensorflow/core/kernels/cwise_op_mul_1.cc; 1223s local ... (2 actions running)
[0m [91m[574 / 928] Compiling tensorflow/core/kernels/cwise_op_mul_1.cc; 1552s local ... (2 actions running)
[0m [91m[574 / 928] Compiling tensorflow/core/kernels/cwise_op_mul_1.cc; 1971s local ... (2 actions running)
[0m [91m[574 / 928] Compiling tensorflow/core/kernels/cwise_op_mul_1.cc; 2415s local ... (2 actions running)
[0m [91m[574 / 928] Compiling tensorflow/core/kernels/cwise_op_mul_1.cc; 2923s local ... (2 actions running)
[0m [91m[574 / 928] Compiling tensorflow/core/kernels/cwise_op_mul_1.cc; 3507s local ... (2 actions running)
[0m [91mERROR: /tensorflow_src/tensorflow/core/kernels/BUILD:5770:1: C++ compilation of rule '//tensorflow/core/kernels:android_tensorflow_kernels' failed (Exit 254)
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Android (4751641 based on r328903) clang version 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242ddd5815e4a043907ea9004281) (https://android.googlesource.com/toolchain/llvm 1d739ffb0366421d383e04ff80ec2ee591315116) (based on LLVM 7.0.2svn)
Target: armv7-none-linux-android
Thread model: posix
InstalledDir: external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/cwise_op_mul_1-574804.cpp
clang: note: diagnostic msg: /tmp/cwise_op_mul_1-574804.sh
clang: note: diagnostic msg:
********************
[0m [91mTarget //tensorflow/lite:libtensorflowLite.so failed to build
[0m [91mUse --verbose_failures to see the command lines of failed build steps.
[0m [91mINFO: Elapsed time: 4707.414s, Critical Path: 3871.01s
INFO: 564 processes: 564 local.
[0m [91mFAILED: Build did NOT complete successfully
[0m [91mFAILED: Build did NOT complete successfully
```

I am looking forward to any advice if this is even possible in the current experimental stage
Thanks,
Thomas

**Comment by jdduke** [comment]
Can you paste the contents of the `.tf_configure.bazelrc` file in the root source directory (where you ran ./configure)? Thanks.

**Comment by tbirn** [comment]
Here you go:

```
build --action_env PYTHON_BIN_PATH="/usr/local/bin/python"
build --action_env PYTHON_LIB_PATH="/usr/local/lib/python3.5/dist-packages"
build --python_path="/usr/local/bin/python"
build:xla --define with_xla_support=true
build --config=xla
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="0"
build --action_env TF_DOWNLOAD_CLANG="0"
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
```

**Comment by freedomtan** [comment]
@tbirn You may want to check if the compiler was killed because of memory pressure.

**Comment by tbirn** [comment]
@freedomtan That is certainly the case. I tried again on a more powerful machine in the cloud and it compiled w/o error.

Thanks for the help.

**Comment by suneshp** [comment]
I have problem in using C++ APIs on android. We have to build a C++ library that access TF Lite. Our library is used by Android application. Can you please share working sample and instructions?

**Comment by freedomtan** [comment]
[TFLite Android examples](https://www.tensorflow.org/lite/examples/) use Java to access underlying C++ libraries. You may want to start from them.

**Comment by jdduke** [comment]
The [label_image](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/label_image) and [minimal](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/minimal) example demonstrate C++ API usage. You can use those APIs together with the native [libtensorflowlite.so](https://github.com/tensorflow/tensorflow/blob/182fce37819b22bc94b444a851ababf94c464259/tensorflow/lite/BUILD#L414) library.

**Comment by freedomtan** [comment]
@suneshp Yes, as @jdduke said you can take a look at label_image and minimal too. When TFLite was released in late 2017, I got so excited. Then it came to me that there are Android Apps, which uses Java API which uses JNI to call C++ APIs, but there were no working C++ API command line example, so I read TFLite source code and wrote the label_image for TFLite as an exercise and a tool for myself. I mean, so far it seems the most reliable doc and example are in source code :-)

**Comment by suneshp** [comment]
Thank you both. I will try and update the thread.

Sent from Yahoo Mail on Android 
 
  On Wed, Mar 13, 2019 at 8:02 PM, freedomtan<notifications@github.com> wrote:   
@suneshp Yes, as @jdduke said you can take a look at label_image and minimal too. When TFLite was released in late 2017, I got so excited. Then it came to me that there are Android Apps, which uses Java API which uses JNI to call C++ APIs, but there were no working C++ API command line example, so I read TFLite source code and wrote the label_image for TFLite as an exercise and a tool for myself. I mean, so far it seems the most reliable doc and example are in source code :-)

**Comment by hamlatzis** [comment]
> @suneshp [TFLite Android examples](https://www.tensorflow.org/lite/examples/) use Java to access underlying C++ libraries. You may want to start from them.

All the samples are for models with built-in operations, what about custom operations? I've followed the documentation (https://www.tensorflow.org/lite/guide/ops_custom#defining_the_kernel_in_the_tensorflow_lite_runtime) but don't know how to register my custom operation from Java. 

So when in the image_classification sample I try to use my model there is an exception informing me that my custom operation cannot be found, which is logical because I haven't registered it.

**Comment by jdduke** [comment]
@hamlatzis are you able to use bazel to build the native libraries? That is, if you can run:

```
bazel build --cxxopt='--std=c++11' -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
 //tensorflow/lite/java:tensorflow-lite
```

You can either:

 1) [Add your sources here and explicitly add your custom op to the BuiltinOpResolver](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/src/main/native/builtin_ops_jni.cc#L25), then rebuild the library.
  2) Create your own `std::unique_ptr<OpResolver> tflite::CreateOpResolver()` method implementation, and then link that into the native library in [his build rule](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/src/main/native/BUILD#L56) (instead of builtin_ops_jni.cc) and rebuild the native library.

We considered adding direct support for passing along custom ops through Java, but the reality is you'd have to write your own JNI bindings to pass through your native custom op, and at that point you may already be doing things in native code anyway. We're happy to reconsider if there is demand, and we could do something like what we've done with the [Delegate.java](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/src/main/java/org/tensorflow/lite/Delegate.java) class.

**Comment by hamlatzis** [comment]
https://github.com/tensorflow/tensorflow/issues/25688#issuecomment-494466083

Yes that's how I built my .aar file and following the documentation I have added my custom ops. Tomorrow when I'm back at the office I'll check the rest of your guidelines

thnx

**Comment by hamlatzis** [comment]
https://github.com/tensorflow/tensorflow/issues/25688#issuecomment-494466083

@jdduke just modified my code and it worked thnx

![2019-05-22_09h44_36](https://user-images.githubusercontent.com/761700/58153395-938db180-7c77-11e9-9e7b-46d88e3a3f30.png)


(sorry for the Greek labels in the image)

**Comment by jdduke** [comment]
Nice! Glad it worked.

We'll work on updating the documentation on using custom ops to explicitly call out how to do this with the Java bindings. Thanks for flagging the issue!
