### ISSUE TITLE
in the website "https://tensorflow.google.cn",the experience of auto-scroll is so bad for  focusing on the content. I wish it could be improved.Tks

### ISSUE THREAD

**Issue by tensorflow2019** [tensorflow/tensorflow#25682]
in the website "https://tensorflow.google.cn",the experience of auto-scroll is so bad for  focusing on the content. I wish it could be improved. Thanks.

**Comment by wolffg** [comment]
Could we get more detail on this?  

* Browser and version?
* How are you invoking autoscroll?
* Which pages are causing issues?

**Comment by wolffg** [comment]
No response; closing, but please re-file if you want to tell us about accessibility issues.
