### ISSUE TITLE
FFT parallelized over feature maps, minibatches and within each 2-D transform

### ISSUE THREAD

**Issue by eduardo4jesus** [tensorflow/tensorflow#25697]
# Performance Issue

Note: This is not a bug, but it is a performance issue that I have faced, and it might or might not lead to a new feature request. So, I am bringing this up here for discussion.

**System information**
- I am using Kaggle Kernels for running my tensorflow code with the GPU option enabled.

Environment Information:
> You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
> You can also obtain the TensorFlow version with
> `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
> 
> 

Output:
> b'v1.12.0-0-ga6d8ffae09' 1.12.0

# The Issue
**Context**

I reproduced this [paper](https://www.groundai.com/project/fast-training-of-convolutional-networks-through-ffts/) that basically learns CNN maps in the frequency domain. However, when I run it and compare the epoch time on training of regular CNNs, that operates in the spatial domain, against using FFTs, that operates in the frequency domain, the FFT version is much slower. For experiments, I implemented the LeNet-5 and used the MNIST dataset.

| Experiment | Description | Avrg Epoch Time  | Wall time | Acc |
|:------------:|:-----------:|:-----------------:|-----------|-----|
|  MNIST - Baseline LeNet CNN | Baseline | 1.67633 s  | 25.2 s   | 98.79416 |
| MNIST - Mathieu LeNet CNN | Frequency Domain Convolutions | 5.69431 s | 56.4 s   | 97.26562 |

The paper, that claims a faster CNN, comes with the following note:

> Current GPU implementations of the FFT such as cuFFT are designed to parallelize over individual transforms. This can be useful for computing a limited number of transforms on large inputs, but is not suitable for our task since we are performing many FFTs over relatively small inputs. Therefore, we developed a custom CUDA implementation of the Cooley-Tukey FFT algorithm which enabled us to parallelize over feature maps, minibatches and within each 2-D transform. Note that 2-D FFTs lend themselves naturally to parallelization since they can be decomposed into two sets of 1-D FFTs (one over rows and the other over columns), and each set can be done in parallel.

I had no clue on how this implementation optimization would occur, so I put [this question](https://dsp.stackexchange.com/questions/54903/how-to-custom-optimize-cufft-for-a-mini-batch-of-multi-channel-images) up to an online community. I assume the paper is accurate on its claim, since one of the authors is the father of CNN, LeCan. So, the only feasible thing I could do, given the answer I got and my lack of understanding on actual `CUDA` development, was to check for the tensorflow implementation and see if`cufftPlanMany` is somehow used. And it is indeed somehow used.

**Problem**

Up to this point, I don't know how to reproduce the technique described in that paper. I wish I knew. If there is a better way to run FFT operations, I believe that lots of applications could benefit from it. In additional, the paper mention some memory considerations of their implementation. But I think that it is a separe issue. 
> Note that by keeping the Fourier representations in memory for all layers after the forward pass, we could avoid recomputing several of the FFTs during the backward pass. However, this might become pro- hibitively expensive in terms of memory for large networks. Therefore we reuse the same memory for all the different convolutions in the network, so that the necessary amount of memory is de- termined only by the largest convolution layer.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25697)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25697)
