### ISSUE TITLE
Enable Keras Applications with pretrained Weights to be used inside the Estimator API

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/tensorflow#25693]
Examples like #25670 show you that is impossible to use Keras Applications inside the Estimator API. The issue has to do with some global tensors that Keras creates by itself that live or were created in a separate session, thus, when the Estimator API wants to construct the `model_fn` it raises an error saying that it found a Tensor from a different graph.

I think Keras should be modified to avoid this behavior, TFHub is nice but it doesn't let you use arbitrary input shapes.

**Comment by karmel** [comment]
@cgarciae Have you tried to use [model_to_estimator](https://www.tensorflow.org/api_docs/python/tf/keras/estimator/model_to_estimator)? I believe that might work in this case.

**Comment by cgarciae** [comment]
@karmel Tested, it doesn't work.

**Comment by karmel** [comment]
@cgarciae -- thanks; can you provide the code snippet and error output? Thanks--

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
