### ISSUE TITLE
pip install tf-nightly-2.0-preview on Windows 10: missing file TensorSyclConvertToDeviceExpression.h

### ISSUE THREAD

**Issue by tarrade** [tensorflow/tensorflow#25692]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: tf-nightly-2.0-preview==2.0.0.dev20190208
- Python version:3.6.6 
- Installed using virtualenv? pip? conda?: pip (18.0)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Cannot install  TF2.0 preview package for Windows 10 (private Windows 10 machine, admin, no proxy) because TensorSyclConvertToDeviceExpression.h is missing

One file cannot be found:
xxx/Eigen/CXX11/src/Tensor/TensorSyclConvertToDeviceExpression.h'

I used pip install tf-nightly-2.0-preview==2.0.0.dev20190208 --no-clean and I could see that such file doesn't exist

**Provide the exact sequence of commands / steps that you executed before running into the problem**

pip install tf-nightly-2.0-preview==2.0.0.dev20190208

Collecting tfds-nightly (from -r C:\Users\steph\condaenv.19qkhena.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a6/66/8da21433386f85e2c5665c830ee86e79518f73e019846083513b84665d29/tfds_nightly-1.0.0.dev201902120105-py3-none-any.whl (393kB)
    100% |████████████████████████████████| 399kB 6.6MB/s
Collecting tf-nightly-2.0-preview==2.0.0.dev20190208 (from -r C:\Users\steph\condaenv.19qkhena.requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/79/87/b2b471ad6df83f3b66fdc3bbe119f88f776307fb5a994be86b76184709b9/tf_nightly_2.0_preview-2.0.0.dev20190208-cp36-cp36m-win_amd64.whl (42.1MB)
    100% |████████████████████████████████| 42.1MB 728kB/s
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\steph\\AppData\\Local\\Temp\\pip-install-hwy1u5dr\\tf-nightly-2.0-preview\\tf_nightly_2.0_preview-2.0.0.dev20190208.data/purelib/tensorflow/include/tensorflow/include/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorSyclConvertToDeviceExpression.h'

CondaValueError: pip returned an error 
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

same command a above in verbose mode (selection):

Using version 2.0.0.dev20190208 (newest of versions: 2.0.0.dev20190208)
  Created temporary directory: C:\Users\steph\AppData\Local\Temp\pip-unpack-00jv942o
  Looking up "https://files.pythonhosted.org/packages/79/87/b2b471ad6df83f3b66fdc3bbe119f88f776307fb5a994be86b76184709b9/tf_nightly_2.0_preview-2.0.0.dev20190208-cp36-cp36m-win_amd64.whl" in the cache
  Current age based on date: 290
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 290
  Using cached https://files.pythonhosted.org/packages/79/87/b2b471ad6df83f3b66fdc3bbe119f88f776307fb5a994be86b76184709b9/tf_nightly_2.0_preview-2.0.0.dev20190208-cp36-cp36m-win_amd64.whl
  Downloading from URL https://files.pythonhosted.org/packages/79/87/b2b471ad6df83f3b66fdc3bbe119f88f776307fb5a994be86b76184709b9/tf_nightly_2.0_preview-2.0.0.dev20190208-cp36-cp36m-win_amd64.whl#sha256=5b29449c373e7fb2fcd188cb6b0006facfb8da3414c0d555223cdce6307b1442 (from https://pypi.org/simple/tf-nightly-2-0-preview/)
Could not install packages due to an EnvironmentError.
Traceback (most recent call last):
  File "C:\Users\steph\Anaconda3\envs\env_gcp_dl_2_0\lib\site-packages\pip\_internal\commands\install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "C:\Users\steph\Anaconda3\envs\env_gcp_dl_2_0\lib\site-packages\pip\_internal\resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\Users\steph\Anaconda3\envs\env_gcp_dl_2_0\lib\site-packages\pip\_internal\resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\steph\Anaconda3\envs\env_gcp_dl_2_0\lib\site-packages\pip\_internal\resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\steph\Anaconda3\envs\env_gcp_dl_2_0\lib\site-packages\pip\_internal\operations\prepare.py", line 283, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "C:\Users\steph\Anaconda3\envs\env_gcp_dl_2_0\lib\site-packages\pip\_internal\download.py", line 836, in unpack_url
    progress_bar=progress_bar
  File "C:\Users\steph\Anaconda3\envs\env_gcp_dl_2_0\lib\site-packages\pip\_internal\download.py", line 677, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "C:\Users\steph\Anaconda3\envs\env_gcp_dl_2_0\lib\site-packages\pip\_internal\utils\misc.py", line 578, in unpack_file
    flatten=not filename.endswith('.whl')
  File "C:\Users\steph\Anaconda3\envs\env_gcp_dl_2_0\lib\site-packages\pip\_internal\utils\misc.py", line 478, in unzip_file
    fp = open(fn, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\steph\\AppData\\Local\\Temp\\pip-install-uvd9so6x\\tf-nightly-2.0-preview\\tf_nightly_2.0_preview-2.0.0.dev20190208.data/purelib/tensorflow/include/tensorflow/include/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorSyclConvertToDeviceExpression.h'
Cleaning up...

**Comment by jvishnuvardhan** [comment]
@tarrade There is a common issue with Windows10 where path length is restricted by default. Please check this [resource](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/) to remove that restriction and then install TF. There are several users [reported](https://github.com/tensorflow/tensorflow/issues/24835) similar issue. Please let us know how it progresses. Thanks!

**Comment by tarrade** [comment]
@jvishnuvardhan thanks a lot. I installed more than 300 packages with pip and conda and never saw that. You are right the path was 273 characters long and allowing to have more than 260 characters as mention in your link fixed the issue. Thanks a lot

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25692)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25692)
