### ISSUE TITLE
Adding DecodeJpeg Op to Android results in build errors (jpeg-9a is missing)

### ISSUE THREAD

**Issue by kuza55** [tensorflow/tensorflow#2570]
I tried to add the jpeg libraries to the Android build so that I could easily use the model I trained using the transfer learning example, after adding the decode_jpeg_op.cc and removing the jpeg exclude from the android core libraries I ran into issues with the jpeg-9a includes from this file not being anywhere in the repo:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/jpeg.h#L26

I'm not sure if this library being missing is just an oversight or whether this is unsupported at the moment. I can probably deal with it not being there by stripping that node out of my graph, it just seems to be a random sharp edge

**Comment by kuza55** [comment]
I guess I can't really deal with this since Graphs are considered append-only? As per http://stackoverflow.com/questions/34235225/is-it-possible-to-modify-an-existing-tensorflow-computation-graph

I did find some information on how to copy graphs: https://codesachin.wordpress.com/2015/11/20/recursively-copying-elements-from-one-graph-to-another-in-tensorflow/ but that seems like it's liable to break since it's digging into the graph internals...

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/strip_unused.py might be useful for you, potentially?

**Comment by kuza55** [comment]
@vrv Thank you very much! That seems to get me one step closer, but when I specify DecodeJpeg as my input node, and then try to import the graph I get the following error:

ValueError: graph_def is invalid at node u'Cast': Input tensor 'DecodeJpeg:0' Cannot convert a tensor of type float32 to an input of type uint8.

Cast is the node that DecodeJpeg feeds into. When I set Cast as my input node it works fine though, so

**Comment by aselle** [comment]
As you seem to have been able to resolve your problem, I am closing the issue for now.

**Comment by kuza55** [comment]
@aselle I managed to resolve my issue with a workaround, but the jpeg.h file I linked to still references header files not in the repo. It's not enabled on Android by default, but still seems broken...

**Comment by Shaikjalal** [comment]
@kuza55 kuza55, 

Mate, I too have the same issue "No OpKernel was registered to support Op 'DecodeJpeg'" I changed the input in Jni file to DecodeJpeg:0 and also tried to strip the graph of unused nodes, still same issue.
help.

**Comment by andrewharp** [comment]
@Shaikjalal Are you sure it's getting stripped out? You should be passing bypassing the DecodeJpeg node completely on Android.

@kuza55 Agreed that the code seems to imply we support jpeg on Android, which is inconsistent with the fact that we don't. I'll take a look at providing a better error message in the invalid configurations.

**Comment by andrewharp** [comment]
@kuza55 jpeg.h and png.h have been updated to explicitly exclude mobile builds so that it's clear we don't support them there.

**Comment by maelp** [comment]
@andrewharp the jpeg decoding libraries seem to be indeed excluded from build, but they are used in the ios example code, is there something to do to add them?

**Comment by Shaikjalal** [comment]
@andrewharp sorry the strip_unused wasn't stripping it.
I recently updated to 0.9 version and now I get a protobuf error when running the strip_unused script any ideas.
bazel build tensorflow/python/tools:strip_unused && bazel-bin/tensorflow/python/tools/strip_unused --input_graph=/BBGraph/output_graph.pb --output_graph=/tmp/stripped_graph.pb --input_node_names=cast --output_node_names=final_result
INFO: Waiting for response from Bazel server (pid 47771)...
INFO: Found 1 target...
Target //tensorflow/python/tools:strip_unused up-to-date:
  bazel-bin/tensorflow/python/tools/strip_unused
INFO: Elapsed time: 13.801s, Critical Path: 0.00s
Traceback (most recent call last):
  File "/Users/Jz/tensorflow/bazel-bin/tensorflow/python/tools/strip_unused.runfiles/tensorflow/python/tools/strip_unused.py", line 118, in <module>
    tf.app.run()
  File "/Users/Jz/tensorflow/bazel-bin/tensorflow/python/tools/strip_unused.runfiles/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/Users/Jz/tensorflow/bazel-bin/tensorflow/python/tools/strip_unused.runfiles/tensorflow/python/tools/strip_unused.py", line 115, in main
    FLAGS.placeholder_type_enum)
  File "/Users/Jz/tensorflow/bazel-bin/tensorflow/python/tools/strip_unused.runfiles/tensorflow/python/tools/strip_unused.py", line 86, in strip_unused
    text_format.Merge(f.read(), input_graph_def)
  File "/Users/Jz/tensorflow/lib/python2.7/site-packages/google/protobuf/text_format.py", line 309, in Merge
    return MergeLines(text.split('\n'), message, allow_unknown_extension)
  File "/Users/Jz/tensorflow/lib/python2.7/site-packages/google/protobuf/text_format.py", line 346, in MergeLines
    _ParseOrMerge(lines, message, True, allow_unknown_extension)
  File "/Users/Jz/tensorflow/lib/python2.7/site-packages/google/protobuf/text_format.py", line 371, in _ParseOrMerge
    allow_unknown_extension)
  File "/Users/Jz/tensorflow/lib/python2.7/site-packages/google/protobuf/text_format.py", line 425, in _MergeField
    name = tokenizer.ConsumeIdentifier()
  File "/Users/Jz/tensorflow/lib/python2.7/site-packages/google/protobuf/text_format.py", line 764, in ConsumeIdentifier
    raise self._ParseError('Expected identifier.')
google.protobuf.text_format.ParseError: 2:1 : Expected identifier.

**Comment by andrewharp** [comment]
@Shaikjalal What's the command line you're giving to strip_unused? It sounds like it's not reading from a valid text-format protobuf file.

**Comment by andrewharp** [comment]
@maelp Sorry, I'm not sure what you mean. AFAICT libjpeg and libpng are specifically excluded from all mobile builds. The makefile-base ios build uses https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/gen_file_lists.sh to create the source file list, and this excludes png and jpeg files.

You should be able to get them build if you start by adding them to the dependency tree for //tensorflow/core:android_tensorflow_lib_lite. We just aren't supporting that right now as there are built-in image manipulation options available on mobile platforms.

**Comment by Shaikjalal** [comment]
@andrewharp this is the command line i am running 
bazel-bin/tensorflow/python/tools/strip_unused --input_graph=/BBGraph/output_graph.pb --output_graph=/tmp/stripped_graph.pb --input_node_names=cast --output_node_names=final_result

**Comment by maelp** [comment]
@andrewharp: sorry it was related to the bug #2754 that I closed -- it was linked to the model I downloaded from the web which included some operations that are not in the mobile app, but the link to the model has been updated

**Comment by andrewharp** [comment]
@Shaikjalal Can you try running strip_unused with --input_binary=true? It may be trying to read a binary proto as if it were text format.

**Comment by Shaikjalal** [comment]
@andrewharp Thanks that worked, I will try load the new graph in the demo and see if it infers, fingers crossed. :)
Cheers!

**Comment by deepaksuresh** [comment]
@kuza55 Did you use bazel or makefile to add `DecodeJpeg` to android?
