### ISSUE TITLE
TypeError: Expected config_proto to be a ConfigProto

### ISSUE THREAD

**Issue by dthomas888** [tensorflow/tensorflow#25704]
python /root/tensorflow/tensorflow/examples/image_retraining/retrain.py \
        --image_dir /home/training/data/images \
        --how_many_training_steps=4000 \
        --eval_step_interval=100 \       
        --output_graph /home/training/data/graph.pb \
        --summaries_dir /home/training/data/summaries \
        --output_labels /home/training/data/output_labels.txt \
        --bottleneck_dir /home/training/data/bottleneck/ \
        --intermediate_store_frequency 1000 \
        --intermediate_output_graphs_dir /home/training/data/intermediate \
        --saved_model_dir /home/training/data/saved_model       
        
        
     tensorflowjs_converter \
        --input_format=tf_saved_model \
        --output_node_names='final_result' \
        --saved_model_tags=serve \
        /home/training/data/saved_model/ \
        /home/training/data/saved_model_web/

Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0212 21:48:38.775988 139652780599104 deprecation.py:323] From /usr/lib/python2.7/site-packages/tensorflow/python/tools/freeze_graph.py:161: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
W0212 21:48:42.307756 139652780599104 deprecation.py:323] From /usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py:1277: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W0212 21:48:44.036837 139652780599104 deprecation.py:323] From /usr/lib/python2.7/site-packages/tensorflow/python/tools/freeze_graph.py:232: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
W0212 21:48:44.037100 139652780599104 deprecation.py:323] From /usr/lib/python2.7/site-packages/tensorflow/python/framework/graph_util_impl.py:246: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
Traceback (most recent call last):
  File "/bin/tensorflowjs_converter", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/tensorflowjs/converters/converter.py", line 322, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/usr/lib/python2.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_pb.py", line 294, in convert_tf_saved_model
    skip_op_check=skip_op_check, strip_debug_ops=strip_debug_ops)
  File "/usr/lib/python2.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_pb.py", line 129, in optimize_graph
    rewriter_config, meta_graph, cluster=get_cluster())
  File "/usr/lib/python2.7/site-packages/tensorflow/python/grappler/tf_optimizer.py", line 36, in OptimizeGraph
    type(config_proto))
TypeError: Expected config_proto to be a ConfigProto, saw type <class 'tensorflow.core.protobuf.rewriter_config_pb2.RewriterConfig'>

**Comment by bidakos** [comment]
@dthomas888 have you managed to do it?

**Comment by ymodak** [comment]
Is this still an issue? This issue is more appropriate on TensorFlowJS repository. The folks in TFJS repo may guide you better. Please post it on [tensorflow/tfjs](https://github.com/tensorflow/tfjs/issues) repo. Thanks!
