### ISSUE TITLE
Dataset iterator is stalled indefinitely with corrupt TFRecord despite using `ignore_errors`

### ISSUE THREAD

**Issue by sjain-stanford** [tensorflow/tensorflow#25700]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 3.6
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 9/7
- GPU model and memory: n/a

Creating this issue per @mrry's [suggestion](https://github.com/tensorflow/tensorflow/issues/12701#issuecomment-462799443) with minimal code to reproduce the issue.

cc @guillaumekln You're [right](https://github.com/tensorflow/tensorflow/issues/13463#issuecomment-462654013), what I'm seeing may not have to do with `OutofRangeError`, but the execution stalls indefinitely when it encounters corrupt data within a TFRecord, despite using `tf.data.experimental.ignore_errors()`.

#### Example Data (for snippets below)
- [clean.tfrecord](https://drive.google.com/uc?export=view&id=1Y2yV67jAvYhqz8OJLPV7v0BN2w1Feps9)
- [corrupt.tfrecord](https://drive.google.com/uc?export=view&id=1Fh7Vah0i_XaGqdb724NIhUIZpR_t5YiG)

#### With `clean.tfrecord`:
```python3
import tensorflow as tf

filenames = ['/data/clean.tfrecord']
#filenames = ['/data/corrupt.tfrecord']

dataset = tf.data.TFRecordDataset(filenames)
dataset = dataset.apply(tf.data.experimental.ignore_errors())
dataset = dataset.batch(64)
dataset = dataset.repeat(1)

iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

with tf.Session() as sess:
    i = 0
    while True:
        try:
            print(i, sess.run(next_element).shape)
            i = i + 1
        except tf.errors.OutOfRangeError:
            print("Dataset complete")
            break
```

#### Output:
```
0 (64,)
1 (64,)
2 (64,)
3 (64,)
4 (64,)
5 (64,)
6 (64,)
7 (64,)
8 (64,)
9 (64,)
10 (64,)
11 (64,)
12 (64,)
13 (64,)
14 (64,)
15 (64,)
16 (64,)
17 (64,)
18 (64,)
19 (35,)
Dataset complete
```

#### With `corrupt.tfrecord`:
```python3
import tensorflow as tf

#filenames = ['/data/clean.tfrecord']
filenames = ['/data/corrupt.tfrecord']

dataset = tf.data.TFRecordDataset(filenames)
dataset = dataset.apply(tf.data.experimental.ignore_errors())
dataset = dataset.batch(64)
dataset = dataset.repeat(1)

iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

with tf.Session() as sess:
    i = 0
    while True:
        try:
            print(i, sess.run(next_element).shape)
            i = i + 1
        except tf.errors.OutOfRangeError:
            print("Dataset complete")
            break
```

#### Output:
```
0 (64,)
1 (64,)
2 (64,)
3 (64,)
4 (64,)
5 (64,)
6 (64,)
7 (64,)
8 (64,)
9 (64,)
10 (64,)
11 (64,)
12 (64,)
(execution stalled indefinitely here)
```

Not sure why the corrupt files within the TFRecord aren't being ignored with `tf.data.experimental.ignore_errors()`. @mrry any idea?

**Comment by yongtang** [comment]
I think the issue was that, when ignore_errors is used, the same file will repeat as the file_index is not moved forward to completion.

Created a PR #25705 for a shortcut fix. 

Not very familiar with this part of the code, maybe there are some better ways of fixing it? /cc @mrry

**Comment by sjain-stanford** [comment]
Thanks @yongtang!

**Comment by jvishnuvardhan** [comment]
Thanks @yongtang. @sjain-stanford If your issue was resolved by @yongtang , then please close it or let me know. Thanks

**Comment by sjain-stanford** [comment]
@jvishnuvardhan Seems like this will close automatically when #25705 is merged. I can let you know once I test the fix though (need to build from source).
