### ISSUE TITLE
The number of non-zero element exceed 32-bits integer

### ISSUE THREAD

**Issue by binfoo1993** [tensorflow/tensorflow#25701]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Centos 7
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source):  1.12.0

**Provide the text output from tflite_convert**

```
InvalidArgumentError (see above for traceback): Number of non-zero elements exceeds int32 range [[node graphconvolution_1/mul (defined at /home/fuqiang/anaconda3/envs/python3.6/lib/python3.6/site-packages/gcn-1.0 py3.6.egg/gcn/layers.py:27)  = SparseDenseCwiseMul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](graphconvolution_1/GatherV2, graphconvolution_1/GatherV2_1, graphconvolution_1/Identity, graphconvolution_1/truediv)]]
```
I was running a model using a sparse tensor whose number of non-zero elements exceed int32 range. And I got this.

Does that mean I can't do sparsedenseMul on any sparse tensor whose number of non-zero elements exceeds int32 range?

**Comment by yongtang** [comment]
Added a PR #25702 to remove the limitation.
