### ISSUE TITLE
Version/Build supporting python3.7 on macOS 10.11.x?

### ISSUE THREAD

**Issue by benknoble** [tensorflow/tensorflow#25711]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.11.6
- TensorFlow installed from (source or binary): `pip` (unclear)
- TensorFlow version: 1.9-1.13
- Python version: 3.7
- Installed using virtualenv? pip? conda?: `pip`

**Describe the problem**

I've tried `pip` installing versions 1.9 all the way up to 1.13 on the machine described above. All failed either because the `.so` was built for macOS 10.12 or with the `async` failures mentioned in another issue (I don't have the reference handy). After fixing those, I ran into other issues: sometimes similar, one time a 3.6 (compile-time) != 3.7 (runtime) error.

Effectively, no matter which of the versions I tried, `python -c 'import tensorflow'` failed.

I've spent the better part of 2 hours hoping to find a (relatively painless) way to install tensorflow on my setup: I find it hard to believe python 3.7 supports macOS 10.11.6 but tensorflow somehow doesn't.

I would really appreciate either
1) an explanation of why this setup is not supported; or
2) an explanation of what version to use/what steps to take in order to install tensorflow and have it work.

N.B. upgrading to macOS 10.12 is not really a suitable option for me right now, otherwise I'd have done it.

**Comment by av8ramit** [comment]
Hi @benknoble 

1. For most of the python binaries on MacOS we build for pypi, we only support 10.12+ for MacOS. For Python3.7 I believe it's actually 10.13+. 

2. You can always try [building from source](https://www.tensorflow.org/install/source#setup_for_linux_and_macos). 

Hope this helps!

**Comment by av8ramit** [comment]
Closing this issue for now due to lack of activity.
