### ISSUE TITLE
Tensorflow Build fail on rockchip arm64

### ISSUE THREAD

**Issue by TropSpirit** [tensorflow/tensorflow#25710]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 64 bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.8.0
- Python version: 2.7
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.12.0
- GCC/Compiler version (if compiling from source):  gcc version 7.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

Tensorflow build ERROR:

**Build command** 
**bazel build -c opt --copt="-funsafe-math-optimizations" --copt="-ftree-vectorize" --copt="-fomit-frame-pointer" --verbose_failures tensorflow/tools/pip_package:build_pip_package**

**ERROR: /home/rock64/tensorflow/tensorflow/core/kernels/BUILD:2529:1: C++ compilation of rule '//tensorflow/core/kernels:matrix_exponential_op' failed (Exit 4): gcc failed: error executing command** 
  (cd /home/rock64/.cache/bazel/_bazel_rock64/c534027a01b43b19fa0469dd5f97fd9f/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/rock64/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -g0 -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK '-std=c++0x' -g0 -MD -MF bazel-out/host/bin/tensorflow/core/kernels/_objs/matrix_exponential_op/tensorflow/core/kernels/matrix_exponential_op.pic.d '-frandom-seed=bazel-out/host/bin/tensorflow/core/kernels/_objs/matrix_exponential_op/tensorflow/core/kernels/matrix_exponential_op.pic.o' -fPIC -DEIGEN_MPL2_ONLY -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DTENSORFLOW_USE_ABSL -DTF_USE_SNAPPY -iquote . -iquote bazel-out/host/genfiles -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/host/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/host/genfiles/external/local_config_sycl -iquote external/com_google_absl -iquote bazel-out/host/genfiles/external/com_google_absl -iquote external/nsync -iquote bazel-out/host/genfiles/external/nsync -iquote external/gif_archive -iquote bazel-out/host/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/host/genfiles/external/jpeg -iquote external/protobuf_archive -iquote bazel-out/host/genfiles/external/protobuf_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/host/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/host/genfiles/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/host/genfiles/external/fft2d -iquote external/highwayhash -iquote bazel-out/host/genfiles/external/highwayhash -iquote external/png_archive -iquote bazel-out/host/genfiles/external/png_archive -iquote external/zlib_archive -iquote bazel-out/host/genfiles/external/zlib_archive -isystem external/eigen_archive -isystem bazel-out/host/genfiles/external/eigen_archive -isystem external/nsync/public -isystem bazel-out/host/genfiles/external/nsync/public -isystem external/gif_archive/lib -isystem bazel-out/host/genfiles/external/gif_archive/lib -isystem external/protobuf_archive/src -isystem bazel-out/host/genfiles/external/protobuf_archive/src -isystem external/farmhash_archive/src -isystem bazel-out/host/genfiles/external/farmhash_archive/src -isystem external/png_archive -isystem bazel-out/host/genfiles/external/png_archive -isystem external/zlib_archive -isystem bazel-out/host/genfiles/external/zlib_archive -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare -fno-exceptions '-ftemplate-depth=900' -pthread -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow/core/kernels/matrix_exponential_op.cc -o bazel-out/host/bin/tensorflow/core/kernels/_objs/matrix_exponential_op/tensorflow/core/kernels/matrix_exponential_op.pic.o)
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1788.353s, Critical Path: 102.71s
FAILED: Build did NOT complete successfully

Here GCC version info:
**rock64@rockpro64:/usr/share/doc/gcc-7$ gcc -v**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/7/lto-wrapper
**Target: aarch64-linux-gnu**
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
**gcc version 7.3.0 (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04)**

**Comment by TropSpirit** [comment]
any update on this ? I'm running this on RK3399 pine board and getting following error

**Comment by freedomtan** [comment]
FYI, with large enough swap space and patience, I was able to build recent master branch on an arm64 platform running Debian rootfs. What I used

1. my patches, https://github.com/tensorflow/tensorflow/pull/16175
2. bazel 0.22.0
3. gcc version 8.2.0 (Debian 8.2.0-20)
4. 
```
bazel build --config opt \
--config=noaws --config=nogcp --config=nohdfs \
--config=noignite --config=nokafka --config=nonccl \
--local_resources 1024,2,2 \
--linkopt=-Wl,--no-keep-memory \
--define tensorflow_mkldnn_contraction_kernel=0 \
//tensorflow/tools/pip_package:build_pip_package
```

**Comment by TropSpirit** [comment]
@freedomtan Still getting the error. with latest tensorflow and bazel 0.22.0

Tensroflow version : Master branch  (with your changes #16175 )
Bazel version : 0.22.0
gcc -v 
gcc version 8.2.0 (Ubuntu 8.2.0-1ubuntu2~18.04)

**ERROR: /home/rock64/Documents/tensorflow/tensorflow/core/kernels/BUILD:3012:1: C++ compilation of rule '//tensorflow/core/kernels:matrix_square_root_op' failed (Exit 1)**
gcc: fatal error: Killed signal terminated program cc1plus
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11834.180s, Critical Path: 4097.51s
INFO: 1171 processes: 1171 local.
FAILED: Build did NOT complete successfully

And here is the build command 
bazel build --jobs 1 --config opt --config=noaws --config=nogcp --config=nohdfs --config=noignite --config=nokafka --config=nonccl --local_resources 1024,2,2 --linkopt=-Wl,--no-keep-memory --define tensorflow_mkldnn_contraction_kernel=0 //tensorflow/tools/pip_package:build_pip_package

**Comment by freedomtan** [comment]
@TropSpirit Do you have large enough swap space? Did you check system issues, such as memory pressure and thermal problem?

**Comment by TropSpirit** [comment]
Thanks @freedomtan 
finally today i was able to build completely. I guess it was swap space or memory going of range. Every time it failed i was rebooting the machine and ran the same command to continue the build from where it failed. 

**Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 1626.568s, Critical Path: 47.03s
INFO: 260 processes: 260 local.
INFO: Build completed successfully, 302 total actions
rock64@rockpro64:~/Documents/tensorflow$ ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg**

**Comment by klorinczi** [comment]
I have similar problem described here:
https://groups.google.com/a/tensorflow.org/forum/#!topic/developers/GEV7Z76Cws4

Using Debian 10 Buster, Python v2.7.
I try to build specific tensorflow v1.14.0 without avx2 support, because I get following error:
Nov  4 17:12:32 moodle37 kernel: [9773297.574293] traps: python2.7[4570] trap invalid opcode ip:7fb9b74bca59 sp:7ffdb7605e10 error:0 in libtensorflow_framework.so.1[7fb9b6d97000+18f8000]

Got following error on build:
**ERROR: /root/inst/tensorflow_src/tensorflow/core/kernels/BUILD:3255:1: C++ compilation of rule '//tensorflow/core/kernels:matrix_square_root_op' failed (Exit 1): gcc failed: error executing command**

I will try to make more space on drive root.
