### ISSUE TITLE
_pywrap_tensorflow.so: Undefined symbol "_ZN9perftools8gputools3rng10RngSupport13kMinSeedBytesE"

### ISSUE THREAD

**Issue by lf94** [tensorflow/tensorflow#2571]
Hello,

I am trying to bring TensorFlow support to FreeBSD. Considering there is Mac support, I figured FreeBSD support couldn't be too bad to work on. I have hit a few snags along the way but nothing show stopping yet. My latest problem is I'm getting an undefined symbol error. I do not want gpu support for the FreeBSD port, but I can see ::perftools::gputools are scattered all throughout the source code. If you could give me any feedback as to what to look into to fix this, that'd be great.

### Environment info
Operating System: FreeBSD 10.3
Installed version of CUDA and cuDNN: None

If installed from sources, provide the commit hash: d8eb4bb6470d4cb3d0f67f2111a39fa50f1c28e5

### Steps to reproduce
1. Build TensorFlow on FreeBSD 10.3 with Clang 3.8
2. Try to import tensorflow in Python3 REPL

### Things I've tried
I also tried this with Python 2. Same results.

### Logs or other output that would be helpful
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.4/site-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.4/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python3.4/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/usr/local/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: /usr/local/lib/python3.4/site-packages/tensorflow/python/_pywrap_tensorflow.so: Undefined symbol "_ZN9perftools8gputools3rng10RngSupport13kMinSeedBytesE"
```

**Comment by mrry** [comment]
Not sure if this is related, but this symbol is special-cased for `#if defined(__APPLE__)`, so it might be relevant:

https://github.com/tensorflow/tensorflow/blob/e39d8feebb9666a331345cd8d960f5ade4652bba/tensorflow/stream_executor/rng.cc#L44

**Comment by lf94** [comment]
That is probably exactly it. I will add an || defined(_BSD_SOURCE) to my local copy.

**Comment by aselle** [comment]
Awesome. When you get it working on FreeBSD, please feel free to submit a pull request

**Comment by lf94** [comment]
After removing that define, TensorFlow runs on FreeBSD 10.3. To anyone reading this, there is another place where defined(__APPLE__) that caused problems (ENOENT undefined error). You may or may not run into it, but if you do just go into the source and edit the causing file. Very small change.

```
[lee@ ~/3rdparty/]$ python
Python 2.7.11 (default, May  7 2016, 01:22:47) 
[GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> import tensorflow as tf 
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
can't determine number of CPU cores: assuming 4
can't determine number of CPU cores: assuming 4
>>> print(sess.run(hello))
Hello, TensorFlow!
>>> a = tf.constant(10)
>>> b = tf.constant(32)
>>> print(sess.run(a + b))
42
>>> :)
```

This is so great!

I will try to formalize a pull request or the required changes to get it working for others.
