### ISSUE TITLE
 KeyError in Serve-DualProtoBuf.py

### ISSUE THREAD

**Issue by sreenupadidapu** [tensorflow/tensorflow#25716]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by sreenupadidapu** [comment]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-da7bde60a553> in <module>()
----> 1 features = encoder_forward_pass(sess, "Images/gen_plane.png")

<ipython-input-2-e5cc47d4db69> in encoder_forward_pass(sess, image_path)
     14 
     15 def encoder_forward_pass(sess, image_path):
---> 16     in1 = graph.get_tensor_by_name("encoder/InputImage:0")
     17     out1 = graph.get_tensor_by_name("encoder/Preprocessed_JPG:0")
     18     feed_dict = {in1: image_path}

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in get_tensor_by_name(self, name)
   3662       raise TypeError("Tensor names are strings (or similar), not %s." %
   3663                       type(name).__name__)
-> 3664     return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
   3665 
   3666   def _get_tensor_by_tf_output(self, tf_output):

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in as_graph_element(self, obj, allow_tensor, allow_operation)
   3486 
   3487     with self._lock:
-> 3488       return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
   3489 
   3490   def _as_graph_element_locked(self, obj, allow_tensor, allow_operation):

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in _as_graph_element_locked(self, obj, allow_tensor, allow_operation)
   3528           raise KeyError("The name %s refers to a Tensor which does not "
   3529                          "exist. The operation, %s, does not exist in the "
-> 3530                          "graph." % (repr(name), repr(op_name)))
   3531         try:
   3532           return op.outputs[out_n]

KeyError: "The name 'encoder/InputImage:0' refers to a Tensor which does not exist. The operation, 'encoder/InputImage', does not exist in the graph."

**Comment by sreenupadidapu** [comment]
plz help me

**Comment by ymodak** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
