### ISSUE TITLE
TF_SessionRun_wrapper: expected all values in input dict to be ndarray  (GPU nightly build)

### ISSUE THREAD

**Issue by roymiles** [tensorflow/tensorflow#25729]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
       I have used the basic example from: https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/1_Introduction/basic_operations.py along with my own code. I have also made a SO question on the matter (https://stackoverflow.com/questions/54678961/tf-sessionrun-wrapper-expected-all-values-in-input-dict-to-be-ndarray) 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.13.0-dev20190208  (GPU nightly build)
- Python version: Python 3.7.1
- CUDA/cuDNN version: V10.0.130 / 
- GPU model and memory: RTX 2070, 8GB

**Describe the current behavior**

I am running into this error "TF_SessionRun_wrapper: expected all values in input dict to be ndarray" for even very basic examples. I am aware that v1.13 nightly is unstable, but building from source on Windows is very inconvenient (I have tried many times).  What should I do/is there anything I can do? 

--- I will try Python 3.6.x when back home ---

**Comment by roymiles** [comment]
I have since fixed the issue.

**Comment by manikTharaka** [comment]
Was it an issue with your code or was it a bug in the TF codebase ?

**Comment by yugushihuang** [comment]
@roymiles How did you fix the issue?

**Comment by roymiles** [comment]
Sorry for the late reply. Turns out there were some incompatible versions with some dependencies. This is not a bug in the TF codebase.

**Comment by chris-schertenlieb** [comment]
@roymiles Any chance you recall which dependencies? I'm having this issue.

**Comment by dalematt** [comment]
I did a complete upgrade on my anaconda installation and that fixed the problem.

**Comment by Angus-Lee** [comment]
"pip uninstall numpy" for two times
then "pip install numpy"
you may have two numpy version in your computer
