### ISSUE TITLE
avg/max_pool3d description has a bug.

### ISSUE THREAD

**Issue by ruihou** [tensorflow/tensorflow#2573]
In file:
[tensorflow/g3doc/api_docs/python/functions_and_classes/shard0/tf.nn.avg_pool3d.md
](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard0/tf.nn.avg_pool3d.md)
[tensorflow/g3doc/api_docs/python/functions_and_classes/shard4/tf.nn.max_pool3d.md
](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard4/tf.nn.max_pool3d.md)
Original:
<b>`ksize`</b>: A list of `ints` that has length `>= 5`.
    1-D tensor of length 5. The size of the window for each dimension of
    the input tensor. Must have `ksize[0] = ksize[1] = 1`.

I think
`ksize[0] = ksize[1] = 1`. should change to `ksize[0] = ksize[4] = 1`, according to the test file https://github.com/tensorflow/tensorflow/blob/712e41cf8b316ef2c33c6dd7fd6ade2b4e93ddc0/tensorflow/python/kernel_tests/pooling_ops_3d_test.py#L48

**Comment by aselle** [comment]
This looks to be the case, and it seems like MaxPool3D, MaxPoolGrad3D, AvgPoolGrad3D all have the same issue. Thanks.
