### ISSUE TITLE
Failed to load native tensorflow 

### ISSUE THREAD

**Issue by saikrishnadas** [tensorflow/tensorflow#25753]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- **Windows 7**
- **pip install tensorflow-gpu**
- Python version: **3.6.6**
- Installed using virtualenv? pip? conda?: **pip**
- CUDA/cuDNN version: **CUDA 8.0 cuDNN 7.1**
- GPU model and memory: **Model : Quadro 4000 , Memory : 18GB**

Installed using pip install tensorflow-gpu (No error, perfectly installed)
While importing tensorflow , i got a error : **Failed to load native tensorflow .ImportError: DLL load failed: The specified module could not be found**

**Comment by ymodak** [comment]
You need to update your cuda and cudnn versions.
For TF 1.12 you can install cuda 9.0 and
for TF 1.13.0-rc2 you can install cuda 10

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
