### ISSUE TITLE
[question][tflite][java] How to allocate mulit dimensional output array to feed in interpreter.run()

### ISSUE THREAD

**Issue by GustavZ** [tensorflow/tensorflow#25751]
I try to run a version `posenet `on an android app with tflite.
The app is based on the GPU delegate demo:
https://medium.com/tensorflow/tensorflow-lite-now-faster-with-mobile-gpus-developer-preview-e15797e6dee7
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo

Posenet takes an Image as Input and computes as output multiple arrays of the shape:
`1x14x14x17,  1x14x14x34, 1x14x14x32,  1x14x14x32`

I know how to allocate a bytbuffer for the image, so thats not the problem.
But how do i allocate a buffer for that output to be able to successfully feed the input and output buffer to the interpreter like:
```
import org.tensorflow.lite.Interpreter;
Interpreter tflite;

ByteBuffer input = null;
input = ByteBuffer.allocateDirect(...);
output = ?

tflite.run(input,output);
```

I tried something like this for the float version:
```
float[][][][] output = null;
output = new float[1*14*14*17][1*14*14*34][1*14*14*32][1*14*14*32];
```
but this leads to a memory oom. So how do I correctly allocate a buffe for the output with an array with the right dimensions. (I am not so used to java, more to python)

EDIT:
and I also tried something like this, but java does not allow it:
```
float[][][][] out1 = new float[1][14][14][17];
float[][][][] out2 = new float[1][14][14][34];
float[][][][] out3 = new float[1][14][14][32];
float[][][][] out4 = new float[1][14][14][32];
float[] output = new float[out1, out2, out3, out4];
```

**Comment by freedomtan** [comment]
For models with multiple inputs, or multiple outputs, use: `interpreter.runForMultipleInputsOutputs(inputs, map_of_indices_to_outputs);` rather than `interpreter.run()`. See my dirty benchmark [code](https://github.com/freedomtan/glDelegateBench/blob/master/app/src/main/java/com/mediatek/gldelegatebench/MainActivity.java#L209-L212) for GPU delegate.

**Comment by GustavZ** [comment]
I tried it your way before, but it did not work.
But I will try again and report.

Furthermore, how can you access the computed output of the model?
I need it to feed it the Multi Pose decoding algorithm.

**Comment by freedomtan** [comment]
Multiplication is used to calculate memory size needed for ByteBuffer, e.g., for (1, 23, 17, 17) floating point tensor, we need 1x23x23x17x4 bytes. Why ByteBuffer? It's supposed to be much faster than array of objects (considering object serialization/deserialization overhead).

How to get outputs? After calling `interpreter.runForMultipleInputsOutputs()`, use
[`getOutputTensor()`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/src/main/java/org/tensorflow/lite/Interpreter.java#L332-L340) to get output tensors.

**Comment by GustavZ** [comment]
@freedomtan alright makes sense.
But If I define as output buffer a BytBuffer, do I get the same object back for getOutputTensor() if I define the output buffer as a generic multi dimensional array?

I ask because I need to apply the multi person decoding algorithm on it, and for my feeling its easier on generic arrays as i am not to familiar with javas tensorflow library.

btw is it possible to cast an tensor into an array, with somehting like this:
```
outTensor = getOutputTensor();
float[][] outArray = new float[?][?];
outArray = outTensor.copyTo(outArray);
```

**Comment by freedomtan** [comment]
Surely you can use multi-dimension array instead of ByteBuffer. As far as I can remember, the `Tensor` class doesn't provide public methods to access data, you still have to deal with original data. If you use ByteBuffer, `interpreter.runForMultipleInputsOutputs()` will pass it thru JNI. If you use other kind of array of objects, they will be copied to a ByteBuffer and the result will copied back to the array of objects you provide.

And as far as I can remember, you can cast ByteBuffer to FloatBuffer (`aByteBuffer.asFloatBuffer()`), and get a float array from FloatBuffer (`aFloatBuffer.arrary()`).

**Comment by GustavZ** [comment]
Usingf an java multidimensional array does not work in this case as something like the following does not work (do you know another way to create such an array?):
```
float[][][][] out1 = new float[1][14][14][17];
float[][][][] out2 = new float[1][14][14][34];
float[][][][] out3 = new float[1][14][14][32];
float[][][][] out4 = new float[1][14][14][32];
float[] outputs = new float[out1, out2, out3, out4];
```
So when using your `Map<Integer, Object> allocateOutputBuffers(int[] shapes)`  function approach, after running the tflite interpreter with `interpreter.runForMultipleInputsOutputs()` how can i access each (of the four) output tensors and cast them to an java multidimensional arrays?
`.asFloatBuffer()` or `.arrary()` is not callable on this.

`interpreter.getOutputTensor(i)` returns `org.tensorflow.lite.Tensors` which I dont know how to convert and 

`outputs.get(i)` returns  `java.nio.HeapByteBuffers`, but how to I convert them to arrays to apply the decoding algorithm on them?

Thank you very much for your help

**Comment by freedomtan** [comment]
I guess what you want is something like
```
Map<Integer, Object> outputs = new HashMap<>();
outputs.put(0, out1)
outputs.put(1, out2)
outputs.put(2, out3)
outputs.put(3, out4)
```
Then, no casting is needed. Just a bit slow.

You may want to check [source code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/src/main/java/org/tensorflow/lite/Interpreter.java#L252-L276)  of `interpreter.runForMultipleInputsOutputs()`

**Comment by GustavZ** [comment]
yeah I also came up with this solution. 
I guess for my needs there is currently no better way than this, as dealing with tflite.getOutputTensors() and also the HeapByteBuffer does not really work for me.

**Comment by adesgautam** [comment]
And if i want to input multiple inputs ? How to convert 2 TensorBuffers to Objects and pass to runForMultipleInputsOutputs ?

**Comment by Marshmallow-zurb-ink** [comment]
The solution's in hand https://stackdev.space/questions/what-is-causing-the-result-of-this-code-to-be-111111
