### ISSUE TITLE
Complex zero to the power zero is nan

### ISSUE THREAD

**Issue by thevincentadam** [tensorflow/tensorflow#25752]
This is a simple yet dramatic bug: 
0^0 does not return 1 for complex numbers  (left zero complex) !

**System information**

- OS Platform and Distribution : Linux Ubuntu 16.04 LTS
- TensorFlow installed from binary : pip 
- TensorFlow version : b'v1.13.0-rc1-0-g54c5616308' 1.13.0-rc1
- Python version: Python 3.5.2

**Describe the current behavior**

`tf.pow(tf.complex(0., 0.), 0)` returns `nan + nan j`

**Describe the expected behavior**

It should be `1 + 0j` as is returned by `np.complex(0., 0.)**0`

**Code to reproduce the issue**

`z = tf.complex(0., 0.);
sess = tf.Session();
sess.run( tf.pow(z, 0) )`

**Comment by awav** [comment]
True for TF2.0 preview as well:

```python
In [12]: tf.complex(0., 0.) ** 0
Out[12]: <tf.Tensor: id=13, shape=(), dtype=complex64, numpy=(nan+nanj)>
```

**Comment by yongtang** [comment]
My guess is that, `tf.pow(tf.complex(0., 0.), 0)` is casted to 
```
tf.pow(tf.complex(0., 0.), tf.complex(0., 0.))
```
,  and C++'s `std::pow` is used, which results in  `nan + nan j`.

The fix may not be straightforward, as it likely may impact the existing APIs.

**Comment by angersson** [comment]
@jvishnuvardhan I don't know very much about this. Can you find a more fitting reviewer, please?

**Comment by rmlarsen** [comment]
@thevincentadam thanks for letting us know. I'll send out a fix, probably sometime next week.

**Comment by ziofil** [comment]
Hello, any progress on this issue?

**Comment by vdutor** [comment]
I'm running into the same problem with TensorFlow 2.0. What is the status of this issue?

**Comment by gadagashwini** [comment]
Issue is replicating with Tf 2.1 and tf-nightly
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/0a8985cbc57b9023cead7a0083c284c1/untitled441.ipynb) . Thanks

**Comment by ravikyram** [comment]
Issue replicating with TF 2.2-rc3. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/02bc714d61ad2f4b3003c29ef19222de/untitled816.ipynb).Thanks!

**Comment by saikumarchalla** [comment]
TensorFlow calls Eigen. Eigen calls std::pow. std::pow(0, 0) is implementation defined. 
https://en.cppreference.com/w/cpp/numeric/complex/pow

To elaborate, mathematically z^0 is not well defined for |z| = 0 because the angle of z is indeterminate. It may be convenient to choose to follow the pattern for |z| > 0, for which z^0 is 1 + 0i, but it is an implementation choice.
