### ISSUE TITLE
gpudelegate + mobilenet_v1_1.0_224.tflite on a gles 3.1 device that reports MAX_WORK_COMPUTE_GROUP_INVOCATIONS = 256

### ISSUE THREAD

**Issue by pontiusnn** [tensorflow/tensorflow#25759]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
* OS Platform and Distribution: Linux Ubuntu 16.04
* Mobile device:  device running Android P and gpu with OpenGL ES 3.1  support
* TensorFlow Lite version on Android: 0.0.0-gpu-experimental
* Test app: TfLiteCameraDemo + GpuDelegate + mobilenet_v1_1.0_224.tflite

**Describe the current behavior**
Hello,
I have been trying to get TfLiteCameraDemo  working through the GpuDelegate on an Android P device with a gpu supporting opengles 3.1.
I am trying to run mobilenet v1_1 float model.

According to  OpenGL ES 3.1 spec, the total number of compute shader invocations in a single local work group (i.e. the product of all three values used to describe the local work group size) must not exceed the value reported for GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS. This limit is guaranteed to be no lower than 128.

The compute shaders being prepared by tensorfllow Gpu Delegate seem to not check this restriction and just try to dispatch  shaders with with a workgroup size of 1024 :
 " layout(local_size_x = 16, local_size_y = 8, local_size_z = 8) in", 
irrespective of what the platform declares for GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS.

Due to this, the shaders fail to compile. This particular gpu supports a workgroup size of 256, which is above the minum 128 required by gles 3.1 spec.

Gpu Delegate  webpage doesn't mention any other requirements except a device with  OpenGl ES >=  3.1.

Is there any chance the code can be tailored to check the limits  reported by the device and change the shaders accordingly?

Thank you

**Comment by freedomtan** [comment]
I ran into the same problem on a device with `GL_MAX_COMPUTE_WORKGROUP_INVOCATIONS == 512`. Yes, as @pontiusnn suggested, `GL_MAX_COMPUTE_WORKGROUP_INVOCATIONS` should be checked and respected.
```
...
java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: GpuDelegate Prepare: Shader compilation failed: Compile failed.
    ERROR: Work group size (16x8x8 = 1024) exceeds GL_MAX_COMPUTE_WORKGROUP_INVOCATIONS (512).
    ERROR: main() function is missing.
    2 compilation errors. No code generated
...
```

**Comment by impjdi** [comment]
@pontiusnn 

Thanks for trying out the GPU delegate, and sorry that it has taken so long to respond; must have missed this post somehow :(

The sad news about the proper way to get `GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS` is to query the GL driver, but not all vendors implement to return the correct numbers.  Then, from  `glGetIntegerv(GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS, &max_work_group_invocations)`,
we may have a bad `max_work_group_invocations` resulting in a problem.  For now, until open-source is ready (coming soon ;) we're really working hard on it), there is unfortunately no way for you to change that.

If you let us know the exact information about your phone (make, model, GPU, GL driver etc.), that'd be great for some data point.

**Comment by freedomtan** [comment]
@impjdi I ran into this on in-house prototype phone. I'll be in the TensorFlow Dev Summit. Maybe I can give you some of the phone at next week.

**Comment by impjdi** [comment]
@freedomtan 

Sounds good.  I'm not giving a talk at TF dev-summit, but can swing by.  Just let me know :)

**Comment by freedomtan** [comment]
@impjdi How to reach you then? My email is freedom@computer.org

**Comment by pontiusnn** [comment]
Hi,
Thank you for your reply.
From your post I understand that this could be a vendor's fault in not implementing correctly glGetIntegerv(GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS,...).
This is not the case on my GPU. The device reports 256 for this limit, but the gpudelegate still goes ahead and runs shaders with size of 1024.

I am working with a Broadcom VC5 GPU, so probably not something you have access to test.
It is a GPU that is gles3.1 conformant and this limit is tested by one of the khronos cts tests.

If you are saying that the code that generates the shaders takes into consideration these limits but something else goes wrong I will wait till gpudelegate is open sourced. Looking forward to it.

Thank you.

**Comment by impjdi** [comment]
@freedomtan 

Thanks for handing over the phone for investigation.  Yes, it looks like there was a bug re: workgroup sizes which is fixed currently in our codebase.  Currently, we are not 100% certain whether we should roll out a new binary or whether we should just let users wait and open source a month or two later.

**Comment by impjdi** [comment]
I will close this bug as it is fixed internally.  Should go out with the next GPU release, either open source or another binary release.

**Comment by freedomtan** [comment]
@impjdi Thanks for your help.

**Comment by munum** [comment]
Hi @impjdi I'm having the exact same issue on Redmi 6:
```
     Caused by: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: WARNING: op code #38 cannot be handled by this delegate.  Only the first 25 ops will run on the GPU, and the remaining 85 on the CPU.GpuDelegate Prepare: Shader compilation failed: Compile failed.
    ERROR: Work group size (16x8x8 = 1024) exceeds GL_MAX_COMPUTE_WORKGROUP_INVOCATIONS (512).
    ERROR: main() function is missing.
    ERROR: 2 compilation errors. No code generated.
```

Is there a way to set `max_work_group_invocations` now?

Thanks

**Comment by impjdi** [comment]
@munum 

Hi Michael, the last time I got the report was on the very first release.  Do you know the version of the AAR you are using?

https://bintray.com/google/tensorflow/tensorflow-lite

**Comment by munum** [comment]
@impjdi I see. I've just tried `0.0.1-gpu-experimental` and the error is now gone. However, I'm actually using [`deeplab_mnv2_pascal_train_aug`](http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz), but I get no meaningful result when gpu is turned on. Basically all pixels are classified to the same class. It works fine with CPU though. Any idea why this might be the case?
