### ISSUE TITLE
Missing clean_dep call in tf_custom_op_library_additional_deps

### ISSUE THREAD

**Issue by Alfus** [tensorflow/tensorflow#25762]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.0-rc0
- Python version: 3.5
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: 10

**Describe the problem**

I believe the 'if_windows' part of 
https://github.com/tensorflow/tensorflow/blob/248016edd1555315c4db540e668d42b95292c2c7/tensorflow/tensorflow.bzl#L1469
is missing a call to clean_deps() and should be:

    ] + if_windows([clean_dep("//tensorflow/python:pywrap_tensorflow_import_lib")])

Note that I am not actually using windows, and my custom op builds and works fine. However, when I call:

    bazel query "deps(//learning/tensorflow_ops:custom_op_tf.so)"

I get the error

    ERROR: learning/tensorflow_ops/BUILD:9:1: no such package 'tensorflow/python': BUILD file not found on package path and referenced by '//learning/tensorflow_ops:custom_op_tf.so_check_deps'
    ERROR: Evaluation of query "deps(//learning/tensorflow_ops:custom_op_tf.so)" failed: errors were encountered while computing transitive closure

**Comment by jvishnuvardhan** [comment]
@Alfus Sorry for the delay. Could you check whether this issue is persisting with latest version of TF? Thanks!

**Comment by Alfus** [comment]
The issue still remains at the current master. Note that this problem will only show up when including the tf source as an external repo (this is the case that clean_dep is designed to fix)

**Comment by gunan** [comment]
I completely missed this issue.
@yifeif you were working with custom ops on windows.
Could you patch the suggested fix here?
