### ISSUE TITLE
Different behavior between Keras and tensorflow.keras in v1.13.0rc1 on placeholder and variable

### ISSUE THREAD

**Issue by duguyue100** [tensorflow/tensorflow#25764]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
 - TensorFlow installed from (source or binary): Binary I suppose
- TensorFlow version (use command below): 1.13.0rc1
- Python version: 3.6

**Describe the current behavior**

So I'm teaching a course and decide to use `tensorflow.keras` instead of Keras.
I then noticed how the two systems handle the `placeholder` and `variable` are different even though
they are using the same backend. I was trying to compile a simple adding function:

```python
# variable can be initialized with a value like this
init_variable_1 = np.zeros(shape=(2, 2))
variable_1 = K.variable(value=init_variable_1)

# variable can also be initialized with particular functions like this
variable_2 = K.ones(shape=(2, 2))

add_tensor = variable_1+variable_2
add_function = K.function(inputs=[variable_1, variable_2],
                          outputs=(add_tensor,))
```

Until this line, both Keras and `tensorflow.keras` allow me to run without errors or warning.

However, for the following code, Keras can pass while `tensorflow.keras features an error:

```
a = np.array([[1, 3], [2, 4]], dtype=np.float32)
b = np.array([[3, 2], [5, 6]], dtype=np.float32)

print(add_function((a,b)))
```

The error is:

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-8-4df03c3d618b> in <module>()
     10 print(a, b)
     11 
---> 12 print(add_function((a,b)))
     13 
     14 # notice that the add_function created is independent of the variables

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py in __call__(self, inputs)
   3074 
   3075     fetched = self._callable_fn(*array_vals,
-> 3076                                 run_metadata=self.run_metadata)
   3077     self._call_fetch_callbacks(fetched[-len(self._fetches):])
   3078     return nest.pack_sequence_as(self._outputs_structure,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1437           ret = tf_session.TF_SessionRunCallable(
   1438               self._session._session, self._handle, args, status,
-> 1439               run_metadata_ptr)
   1440         if run_metadata:
   1441           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    526             None, None,
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive
    530     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: ResourceHandleToInputTensor() received non-DT_RESOURCE Tensor: 1
	 [[{{node _arg_Variable_0_0}}]]
```

**Describe the expected behavior**

So the API `function` defines the input should be a list of `placeholders`.
So either someone (maybe @fchollet) need to change the definition in the API so both `placeholder` and `variable` are fine to be valid inputs (looks like they can be compiled fine in both systems). And make `tensorflow.keras` correct also. Or limit the input tensors to be `placeholder`s where some type checks need to be done.

By the way, I'm not sure this os a specific bug in v1.13.0rc1 and v1.12 or it happens to other releases as well since I was using Colab.

Regards,
Yuhuang.

**Comment by jvishnuvardhan** [comment]
@duguyue100 For me both are giving same output. Could you provide the code you are using to reproduce the bug? Thanks!

**Comment by duguyue100** [comment]
Hi @jvishnuvardhan, here it is in Colab notebook:

https://colab.research.google.com/drive/1W4KtanniPfgX4OoTTADsO-g_QFvQ1CSM

**Comment by duguyue100** [comment]
Just tested on my local machine which has the specs: Ubuntu 16.04+Python 3.6+TensorFlow 1.12+CUDA 9, it reports the same error as in the Colab notebook:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dgywork/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2986, in __call__
    run_metadata=self.run_metadata)
  File "/home/dgywork/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/dgywork/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: ResourceHandleToInputTensor() received non-DT_RESOURCE Tensor: 1
	 [[{{node _arg_Variable_1_0_0}} = _Arg[T=DT_RESOURCE, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
	 [[{{node _arg_Variable_2_0_1/_13}} = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_9__arg_Variable_2_0_1", tensor_type=DT_RESOURCE, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```

**Comment by duguyue100** [comment]
any feedback on this? @jvishnuvardhan

**Comment by duguyue100** [comment]
@ymodak, any update on this?

**Comment by tanzhenyu** [comment]
I think it should be able to receive any symbolic tensor, can you try converting you variable via tf.convert_to_tensor before feeding into the function?

**Comment by duguyue100** [comment]
@tanzhenyu Apply `tf.convert_to_tensor` on the variables works. Then there must be an issue in the Keras implementation then because the program still doesn't work applying the `convert_to_tensor` function. In the meantime, the backend of standalone Keras can use variables as placeholders apparently.

**Comment by rmothukuru** [comment]
@duguyue100,
Sorry for the delayed response. Can you please confirm if this issue is resolved, as you stated:

> Apply tf.convert_to_tensor on the variables works.  

Thanks!

**Comment by duguyue100** [comment]
> @duguyue100,
> Sorry for the delayed response. Can you please confirm if this issue is resolved, as you stated:
> 
> > Apply tf.convert_to_tensor on the variables works.
> 
> Thanks!

Thanks!
