### ISSUE TITLE
Unable to set estimator.model_dir after estimator initialization

### ISSUE THREAD

**Issue by adt123** [tensorflow/tensorflow#25772]
## System information:
Tensorflow version: 1.9.0 (installed from binary)
Python version: 3.6.8

## Problem
Setting the value of `estimator.model_dir` _after_ the estimator has already been created does not work.  I specifically want to set the value of this after initialization, but only see a way to set it _during_ initialization.  Is there a reason that tensorflow does not support setting the `model_dir` after estimator creation? If not, is there a viable workaround?

## Source code:
```
classifier = tf.estimator.DNNClassifier(
    feature_columns=some_feature_classifier,
    hidden_units=[10, 10],
    n_classes=3)
# other code...
classifier.model_dir = "/tmp/model_dir_file"
```

## Error message:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File "<stdin>" in <module>
----> 1 classifier.model_dir = "/tmp/model_dir_file"

AttributeError: can't set attribute
```

Thank you!

**Comment by Sayan-Paul** [comment]
It is a variable in DNNClassfier's super class Estimator but not DNNClassifier. Hence you cannot access it through DNNClassifier. Moreover, these API's are all deprecated and you might want to consider migrating to the new ones.

**Comment by jvishnuvardhan** [comment]
As suggested by @Sayan-Paul , @adt123 Could you use newer Tensorflow version and test your model? Thanks!

**Comment by adt123** [comment]
Hmm, I tried running the same code in my original post with Tensorflow 1.12.0, and received the same error message when trying to set `classifier.model_dir` to some other value. Should I be setting this variable through the super class?
Thanks!

**Comment by Sayan-Paul** [comment]
The class DNNClassifier is deprecated so you should use the new estimator module which is at a different location tf.estimator. In the new one, you can give the model_dir as a paramter of `Estimator`.

Sayan Paul
sayan.paul6@gmail.com (mailto:sayan.paul6@gmail.com)

**Comment by jvishnuvardhan** [comment]
@adt123 could you use latest TF version and follow @Sayan-Paul suggestion to solve this issue. If it was already solved, please close the issue. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!
