### ISSUE TITLE
What does a dim tensor have a dimension with 0-size? such as tf.Tensor([], shape=(2, 2, 0), dtype=int32)

### ISSUE THREAD

**Issue by dMokaMoka** [tensorflow/tensorflow#25777]
- tensorShapes may have an 0-size dimension, but when are they going to be applied? Could you give me an example? This troubles me a lot...  THANKS A LOT!

for example  `tf.one_hot`  
On the implementation side, Tensorflow turns out to be verifying that `depth>= 0`, which are going to generate the tensor with a dimension with 0-size

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
