### ISSUE TITLE
Build error during TF build from the source with XLA enabled

### ISSUE THREAD

**Issue by nickeys** [tensorflow/tensorflow#25773]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: v1.12.0
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip without virtualenv
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source): I'm not sure what version I'm using but, I'm using VS2015 and _MSC_VER is 1900
- CUDA/cuDNN version: CUDA v9.0.176 / cuDNN v7.4.2.24
- GPU model and memory: GTX960M (2GB)

**Describe the problem**
I want to build TF from source with XLA enabled.
So, I tried to build, configuring XLA to be enabled.
But the result was build failed and the log seems to say that 'xla_data.pb.h' file is having some trouble for TS build.
I could not find the real file (xla_data.pb.h), even if the log points where the file exist (bazel-out/x64_windows-opt/genfiles\tensorflow/compiler/xla/xla_data.pb.h), because the path of the file is temporary during the build as I know.
Because even if I modify the bazel's temporary file, this problem would not be resolved radically, I want to find other way for this problem.
Could you give me some help about this problem ?

Thanks!

**Provide the exact sequence of commands / steps that you executed before running into the problem**

> C:\tensorflow>python ./configure.py
> WARNING: Running Bazel server needs to be killed, because the startup options are different.
> WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
> You have bazel 0.15.0 installed.
> Please specify the location of python. [Default is C:\Users\nickeys\AppData\Local\Programs\Python\Python36\python.exe]:
> 
> 
> Found possible Python library paths:
>   C:\Users\nickeys\AppData\Local\Programs\Python\Python36\lib\site-packages
> Please input the desired Python library path to use.  Default is [C:\Users\nickeys\AppData\Local\Programs\Python\Python36\lib\site-packages]
> 
> Do you wish to build TensorFlow with Apache Ignite support? [Y/n]: N
> No Apache Ignite support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with XLA JIT support? [y/N]: Y
> XLA JIT support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with ROCm support? [y/N]:
> No ROCm support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with CUDA support? [y/N]: Y
> CUDA support will be enabled for TensorFlow.
> 
> Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 9.0]:
> 
> 
> Please specify the location where CUDA 9.0 toolkit is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0]:
> 
> 
> Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]:
> 
> 
> Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0]:
> 
> 
> Please specify a list of comma-separated Cuda compute capabilities you want to build with.
> You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
> Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 3.5,7.0]: 5.0
> 
> 
> Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:
> 
> 
> Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
> Eigen strong inline overridden.

And then,

> C:\tensorflow>bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
INFO: From ProtoCompile tensorflow/core/protobuf/replay_log.pb.cc:
tensorflow/core/protobuf/replay_log.proto: warning: Import tensorflow/core/protobuf/cluster.proto but not used.
tensorflow/core/protobuf/replay_log.proto: warning: Import tensorflow/core/framework/graph.proto but not used.
ERROR: C:/tensorflow/tensorflow/compiler/xla/service/cpu/BUILD:536:1: C++ compilation of rule '//tensorflow/compiler/xla/service/cpu:runtime_fft' failed (Exit 2): msvc_wrapper_for_nvcc.bat failed: error executing command
  cd C:/users/nickeys/_bazel_nickeys/xv6zejqw/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/nickeys/AppData/Local/Programs/Python/Python36/python.exe
    SET PYTHON_LIB_PATH=C:/Users/nickeys/AppData/Local/Programs/Python/Python36/lib/site-packages
    SET TEMP=C:\Users\nickeys\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=5.0
    SET TF_CUDA_VERSION=9.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\nickeys\AppData\Local\Temp
  external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/genfiles /Iexternal/nsync /Ibazel-out/x64_windows-opt/genfiles/external/nsync /Iexternal/bazel_tools /Ibazel-out/x64_windows-opt/genfiles/external/bazel_tools /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/x64_windows-opt/genfiles/external/local_config_sycl /Iexternal/protobuf_archive /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive /Iexternal/nsync/public /Ibazel-out/x64_windows-opt/genfiles/external/nsync/public /Ibazel-out/x64_windows-opt/bin/external/nsync/public /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/protobuf_archive/src /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive/src /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive/src /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /showIncludes /MD /O2 /DNDEBUG -w /arch:AVX -DEIGEN_AVOID_STL_ARRAY /Fobazel-out/x64_windows-opt/bin/tensorflow/compiler/xla/service/cpu/_objs/runtime_fft/runtime_fft.o /c tensorflow/compiler/xla/service/cpu/runtime_fft.cc
bazel-out/x64_windows-opt/genfiles\tensorflow/compiler/xla/xla_data.pb.h(242): error C2059: syntax error: 'constant'
bazel-out/x64_windows-opt/genfiles\tensorflow/compiler/xla/xla_data.pb.h(242): error C3805: 'constant': unexpected token, expected either '}' or a ','
bazel-out/x64_windows-opt/genfiles\tensorflow/compiler/xla/xla_data.pb.h(249): error C2065: 'TOKEN': undeclared identifier
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2765.994s, Critical Path: 2700.12s
INFO: 2934 processes: 2934 local.
FAILED: Build did NOT complete successfully
```

**Comment by alvaroslm** [comment]
looks like a global enum value conflicting with some already defined symbol

**Comment by alexrobomind** [comment]
This is a conflict between the generated enum entry OPAQUE in xla_data.pb.h (line 290)

`OPAQUE = 14,`
(generated out of tensorflow/compiler/xla/xla_data.proto - line 74)

 and an identically named preprocessor macro in the Windows 10 SDK (in my case ...\Windows 10 SDK\include\10.0.10586.0\um\wingdi.h line 1872):

`#define OPAQUE              2`

The include chain that leads to the error:

 .\tensorflow/compiler/xla/util.h <- Root target causing the issue
 -.\tensorflow/compiler/xla/status_macros.h
 --.\tensorflow/compiler/xla/types.h
 ---.\tensorflow/core/framework/numeric_types.h
 ----.\third_party/eigen3/unsupported/Eigen/CXX11/Tensor
 -----external/eigen_archive\unsupported/Eigen/CXX11/Tensor
 ------...\Windows 10 SDK\include\10.0.10586.0\um\windows.h
 -------...\Windows 10 SDK\include\10.0.10586.0\um\wingdi.h <- Preprocessor definition
 -.\tensorflow/compiler/xla/xla_data.pb.h <- Location of error, generated by protoc

I hope this helps in deciding on how to resolve this issue.

**Comment by gunan** [comment]
@alexrobomind thank you very much for the information!
@tatianashp could you reassign this issue to an appropriate owner to make the needed changes?

**Comment by jlebar** [comment]
I would prefer to fix this in Eigen rather than modifying our protocol buffers not to clash with this most awful of headers.

It's not clear to me how much Eigen really needs to include windows.h from its main header file, as it seems we're only trying to define a few integer types?  An added bonus of not including windows.h would be faster build times for all of TF on Windows (since *everything* is going to pull in TF numeric_types.h and windows.h is huge).

If `Tensor` must include `windows.h` then I guess it's up to it to #undef the macros that we're clashing with.

@rmlarsen are you the right owner?

**Comment by alexrobomind** [comment]
If Eigen for some reason absolutely needs windows.h they could also use

```
#define NOGDI
#include <windows.h>
#undef NOGDI
```
This would disable the Graphics Device Interface, which is pretty much all of wingdi.h, including the offending macro definition, without disabling the rest of windows.h.

**Comment by Stepiii** [comment]
Maybe we should make a pull request to [eigen](https://bitbucket.org/eigen/eigen/pull-requests/). Or modify the enum entry `OPAQUE` in `tensorflow/compiler/xla/xla_data.proto`. What do you think @jlebar and @rmlarsen ?

**Comment by jlebar** [comment]
Modifying the proto would be a breaking change for us.  We would strongly
prefer that this be fixed in Eigen.

**Comment by rmlarsen** [comment]
I would recommend sending a pull request to Eigen. Please add me as
reviewer.

**Comment by alexrobomind** [comment]
If Eigen cannot change their includes, one could also add an undef to third_party\eigen3\unsupported\Eigen\CXX11\Tensor

```
...
// On Windows, Eigen will include Windows.h, which defines various
// macros that conflict with TensorFlow symbols. Undefine them here to
// prevent clashes.
#undef DeleteFile
#undef ERROR
#undef LoadLibrary
...
```

It seems like this is not the first time this problem appeared.

**Comment by Stepiii** [comment]
@alexrobomind I've tried:
```c++
#undef OPAQUE
```
But it does not work.

**Comment by alexrobomind** [comment]
@Stepiii
Indeed, i do get the same error, but this time the include chain leading to wingdi.h is a different one. Also, it's a different target (//tensorflow/compiler/xla/service:hlo).

 .\tensorflow/compiler/xla/service/dynamic_parameter_binding.h
  external/com_google_absl\absl/container/flat_hash_map.h
   external/com_google_absl\absl/container/internal/raw_hash_map.h
     external/com_google_absl\absl/container/internal/hashtablez_sampler.h
      external/com_google_absl\absl/synchronization/mutex.h
       external/com_google_absl\absl/synchronization/internal/kernel_timeout.h
        external/com_google_absl\absl/time/clock.h
         external/com_google_absl\absl/time/time.h
          D:\Programme\Windows 10 SDK\include\10.0.10586.0\um\winsock2.h
           D:\Programme\Windows 10 SDK\include\10.0.10586.0\um\windows.h
            D:\Programme\Windows 10 SDK\include\10.0.10586.0\um\wingdi.h
   .\tensorflow/compiler/xla/xla_data.pb.h

**Comment by Stepiii** [comment]
@alexrobomind It is more like:

.\tensorflow/compiler/xla/service/dynamic_parameter_binding.h
-external/com_google_absl\absl/container/flat_hash_map.h
--external/com_google_absl\absl/container/internal/raw_hash_map.h
**---external/com_google_absl\absl/container/internal/raw_hash_set.h**
----external/com_google_absl\absl/container/internal/hashtablez_sampler.h
-----external/com_google_absl\absl/synchronization/mutex.h
------external/com_google_absl\absl/synchronization/internal/kernel_timeout.h
...

But it doesn't matter
@jlebar and @rmlarsen How could we prevent including that `wingdi.h` ?

**Comment by jlebar** [comment]
Ugh.  If absl is including Windows headers, I am not sure there is much hope and we may have to take the breaking change in XLA.  But let's check with ABSL folks.

/me summons @misterg

**Comment by jlebar** [comment]
ABSL folks are open to changing ABSL not to include windows.h and other Windows headers from ABSL headers.

It sounds like @rmlarsen is not going to write the Eigen PR.  I'm wondering if one of you might be willing to do this?

**Comment by crazyn2** [comment]
@alexrobomind can you give us more details to solve the errors step by step

**Comment by jlebar** [comment]
Upon further investigation with ABSL team, this is looking difficult to fix in ABSL.

Moreover, they pointed out that because this proto is part of XLA's public API, even if we fixed ABSL and Eigen, that wouldn't unbreak the build for anyone else who includes this header plus windows.h.

I've sent out a proposal internally to rename the OPAQUE enumerator and take the breaking change.

**Comment by jlebar** [comment]
cc @EricWF from ABSL team.

**Comment by tatianashp** [comment]
Justin,

Thank you for handling this problem on XLA side!

[catching up with the email after travel]

**Comment by alexrobomind** [comment]
@crazyn2 The fix that I applied is exactly what @Stepiii uploaded in his commit(s). Unfortunately, this is only a partial fix, since Eigen is not the only route including windows.h (and therefore also wingdi.h). Sorry for the late response.

**Comment by crazyn2** [comment]
@alexrobomind I avioded this problem just cancling the XLA JIK support additionally.

**Comment by Stepiii** [comment]
@crazyn2 It seems that you cannot build tensorflow with XLA on windows. That is the issue.

**Comment by jlebar** [comment]
I am working on renaming the enumerator to make this work.  Separately, we
need to turn on xla in our windows builds so that we catch issues like this.

One worry is that when I renames OPAQUE we will just run into another
problem.  I guess we'll see.

**Comment by jlebar** [comment]
I have renamed OPAQUE to OPAQUE_TYPE.  LMK if you run into additional problems.
