### ISSUE TITLE
Image resizing codes of iOS example camera apps might be wrong

### ISSUE THREAD

**Issue by brownbro** [tensorflow/tensorflow#25784]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- TensorFlow installed from (source or binary): N/A
- TensorFlow version (use command below): N/A

**Describe the current behavior**

I think `in_x = (y * image_width) / wanted_input_width;` statements (mentioned below) would be `in_x = (x * image_width) / wanted_input_width;`. (The former perhaps rotates the input image?)

- https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/ios/camera/CameraExampleViewController.mm#L302

```
  for (int y = 0; y < wanted_input_height; ++y) {
    float *out_row = out + (y * wanted_input_width * wanted_input_channels);
    for (int x = 0; x < wanted_input_width; ++x) {
      const int in_x = (y * image_width) / wanted_input_width; <--
      const int in_y = (x * image_height) / wanted_input_height; <--
      tensorflow::uint8 *in_pixel =
          in + (in_y * image_width * image_channels) + (in_x * image_channels);
      float *out_pixel = out_row + (x * wanted_input_channels);
      for (int c = 0; c < wanted_input_channels; ++c) {
        out_pixel[c] = (in_pixel[c] - input_mean) / input_std;
      }
    }
```

- https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/ios/camera/CameraExampleViewController.mm#L133

```
void ProcessInputWithFloatModel(
    uint8_t* input, float* buffer, int image_width, int image_height, int image_channels) {
  for (int y = 0; y < wanted_input_height; ++y) {
    float* out_row = buffer + (y * wanted_input_width * wanted_input_channels);
    for (int x = 0; x < wanted_input_width; ++x) {
      const int in_x = (y * image_width) / wanted_input_width; <--
      const int in_y = (x * image_height) / wanted_input_height; <--
      uint8_t* input_pixel =
          input + (in_y * image_width * image_channels) + (in_x * image_channels);
      float* out_pixel = out_row + (x * wanted_input_channels);
      for (int c = 0; c < wanted_input_channels; ++c) {
        out_pixel[c] = (input_pixel[c] - input_mean) / input_std;
      }
    }
  }
}
```

**Comment by jvishnuvardhan** [comment]
@brownbro Could you provide any results showing the bug? Thanks!

**Comment by zhukaihan** [comment]
The x and y values of the inputs are flipped. Its affect is that the output are flipped as well. 

Therefore, the images from original code will have predictions that is flipped according to the diagonal line. As shown below (an incorrect image): 
![original_5](https://user-images.githubusercontent.com/7332407/55710749-244a4f80-59a0-11e9-81c5-2a6987f5464b.PNG)

**Images from original code (incorrect):**
```
const int in_x = (y * image_width) / wanted_input_width;
const int in_y = (x * image_height) / wanted_input_height;
```
![original_4](https://user-images.githubusercontent.com/7332407/55710623-dd5c5a00-599f-11e9-9dc8-78ac2ad92a97.PNG)
![original_3](https://user-images.githubusercontent.com/7332407/55710624-dd5c5a00-599f-11e9-8386-4211303a5171.PNG)
![original_2](https://user-images.githubusercontent.com/7332407/55710625-ddf4f080-599f-11e9-90d9-e513604ccc61.PNG)
![original_1](https://user-images.githubusercontent.com/7332407/55710626-ddf4f080-599f-11e9-843a-f871f3cd4295.PNG)


**Images from corrected code:**
```
const int in_x = (x * image_width) / wanted_input_width;
const int in_y = (y * image_height) / wanted_input_height;
```
![correct_4](https://user-images.githubusercontent.com/7332407/55710627-ddf4f080-599f-11e9-84ea-5cd3744b3427.PNG)
![correct_3](https://user-images.githubusercontent.com/7332407/55710630-ddf4f080-599f-11e9-9eb9-89d558863b4b.PNG)
![correct_2](https://user-images.githubusercontent.com/7332407/55710632-de8d8700-599f-11e9-8174-35e8cd3f0749.PNG)
![correct_1](https://user-images.githubusercontent.com/7332407/55710635-de8d8700-599f-11e9-86da-5cf38b758136.PNG)

**Other information:**
* Demo from cloning the repository from GitHub. 
* Using SSD with post processing with export_tflite_ssd_graph.py and tflite_convert. Thus, the output will include bounding boxes. 
* Using TensorFlowLiteGpuExperimental 0.0.1

**Comment by mohantym** [comment]
Hi @brownbro! 
It seems you are using  older versions(1.x versions) of Tensorflow. We recommend that you upgrade  your code base to 2.x  versions as many features and bug fixes has been done in newer versions and let us know if the issue still persists in newer versions. Thanks!
