### ISSUE TITLE
image shift and interpolation

### ISSUE THREAD

**Issue by chris12766** [tensorflow/tensorflow#25788]
I am trying to shift all images in a batch and have 'NEAREST' interpolation. For some reason, the resulting images are interpolated with black pixels... Is this a bug?

`
 translations = [100,0] * len(img_batch_list)
 img_batch = tf.contrib.image.translate(img_batch,
                                        translations,
                                        interpolation='NEAREST',
                                        name="shift")
`

**Comment by ymodak** [comment]
Please take a look at [similar issue](https://github.com/tensorflow/tensorflow/issues/25591). Probably this will help.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
