### ISSUE TITLE
How can i build static framework for tf-lite under 300kb for iOS?

### ISSUE THREAD

**Issue by wangwenjing** [tensorflow/tensorflow#25781]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: master
- Doc Link:https://www.tensorflow.org/lite/overview

**Describe the documentation issue**

Dear supporter,
   I found "Smaller in size: TensorFlow Lite is smaller than 300KB when all supported operators are linked and less than 200KB when using only the operators needed for supporting InceptionV3 and Mobilenet." under TensorFlow Lite highlights. 
    I got libtensorflow-lite.a for each archtecture afte using build_ios_universal_lib.sh script. Binary size is far bigger, around 7.5MB. How can I get one smaller than 300KB?  Do I need to do any optimization on compiling and how?

**Comment by MadahaCEO** [comment]
I have the same problem，has been looking for a solution.

**Comment by wangwenjing** [comment]
@jvishnuvardhan  Do we got any progress on this issue?  I still had no clue on this problem.

**Comment by wangwenjing** [comment]
@aselle  ?

**Comment by rockyrhodes** [comment]
Have you looked at the tensorflow lite micro code?  tensorflow/lite/experimental/micro  Targeted at very small footprint implementations, but very new (and incomplete) at this point.  I'm not sure how to build a library of the size indicated in the docs.  Maybe @jdduke can comment?

**Comment by jdduke** [comment]
When you say "binary size" is bigger, are you measuring the size impact on the actual iOS app? Or just the static library? Looking at just the static library size is misleading, as it ignores all the size reduction that will occur from op stripping (selective registration) as well as symbol stripping (which is controlled by your build options).

See [this guide](https://www.tensorflow.org/lite/guide/inference#customizing_the_kernel_library) for information on how to trim some of the builtin operators. If you know exactly which ops are used by your model, you can create a custom `OpResolver` and register only the ops you need. When your app is actually built/linked, it should trim away unused code.

**Comment by wangwenjing** [comment]
@jdduke  hi, I mean static library.  there is no size impact on actual iOS app if I only drag the libtensorflow-lite.a into my Xcode project without using it. How can I quick test the size impact as all iOS examples using downloaded .framework ?   when the "selective registration" happens , who trigger it and how does it work?  which option you mean when you say "controlled by your build options", tf-lite build option? Xcode build option?

**Comment by lenaevans** [comment]
The guide is pretty vague on how to trim the built-in operators; is there more specific documentation particularly for iOS/android? The size impact on the actual iOS app is about 1.2 MB just for the framework, so trimming it down would be very useful.

**Comment by jdduke** [comment]
Agreed that the documentation could be more explicit. You can start by creating a `MutableOpResolver`, and then adding only the kernels used by your model. There's an example of doing this [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/models/smartreply/predictor.cc#L76), which takes advantage of a bazel build rule for generating only the ops used by a specific model. If you can't use the bazel build rule to generate that code, you'll have to manually add each op yourself ([this code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/register.cc) demonstrates how this is done for the `BuiltinOpResolver`).

**Comment by lenaevans** [comment]
Thanks @jdduke I'll try that out

**Comment by lenaevans** [comment]
Worked great! Thanks so much for your help @jdduke

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Comment by laohur** [comment]
@jdduke fellowed by your example，got “l17_ops_registration.cc” which contains only 12 operators .  but it seems not reduce library size when i include it . How to use it properly? thanks!

**Comment by jdduke** [comment]
So, using the MutableOpResolver approach won't change the size of the *static* library, but it should shrink the size of the actual binary that gets produced in an app, as the unneeded code/symbols can be stripped.

**Comment by laohur** [comment]
> 
> 
> So, using the MutableOpResolver approach won't change the size of the _static_ library, but it should shrink the size of the actual binary that gets produced in an app, as the unneeded code/symbols can be stripped.

Oh，is there another way to reduce static library?
here is my BUILD file.  Only a "cc_binary + static" .so can be loaded ok in unity(c#).

> cc_binary(
    name = "Prophet.so",
    srcs = ["minimal.h", "Prophet.cc",   ],
    linkopts = tflite_linkopts() + select({
        "//tensorflow:android": [
            "-pie",  # Android 5.0 and later supports only PIE
            "-lm",  # some builtin ops, e.g., tanh, need -lm
        ],
        "//conditions:default": [],
    }),
    deps = [
        "//tensorflow/lite:framework",
        "//tensorflow/lite/c:c_api_internal",
        "//tensorflow/lite/kernels:builtin_ops",
        "//tensorflow/lite:builtin_op_data",
        "//tensorflow/lite/schema:schema_fbs",
    ],
    linkshared = True,
)

**Comment by laohur** [comment]
> 
> 
> Agreed that the documentation could be more explicit. You can start by creating a `MutableOpResolver`, and then adding only the kernels used by your model. There's an example of doing this [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/models/smartreply/predictor.cc#L76), which takes advantage of a bazel build rule for generating only the ops used by a specific model. If you can't use the bazel build rule to generate that code, you'll have to manually add each op yourself ([this code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/register.cc) demonstrates how this is done for the `BuiltinOpResolver`).


a little  confusion：
i got "_ops_registration.cc". 
it is ok when extract codes to "lib.cc",
but wrong when "lib.cc" include "_ops_registration.cc" and BUILD file is  srcs = ["llib.h" ,"_ops_registration.cc", "lib.cc"].

**Comment by laohur** [comment]
> 
> 
> Agreed that the documentation could be more explicit. You can start by creating a `MutableOpResolver`, and then adding only the kernels used by your model. There's an example of doing this [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/models/smartreply/predictor.cc#L76), which takes advantage of a bazel build rule for generating only the ops used by a specific model. If you can't use the bazel build rule to generate that code, you'll have to manually add each op yourself ([this code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/register.cc) demonstrates how this is done for the `BuiltinOpResolver`).

why cann't recently on fresh source?

> 
  bazel build tensorflow/python/tools:print_selective_registration_header && \   
bazel-bin/tensorflow/python/tools/print_selective_registration_header \  
   --graphs=models_arm64/1.pb > ops_to_register.h

> <long int, 1>; int packet_size = 4; bool inner_dim_contiguous = false; bool inner_dim_reordered = true; int Alignment = 0]':
./tensorflow/core/kernels/eigen_spatial_convolutions.h:308:11: warning: 'orig_r' may be used uninitialized in this function [-Wmaybe-uninitialized]
./tensorflow/core/kernels/eigen_spatial_convolutions.h:308:11: warning: 'orig_r' may be used uninitialized in this function [-Wmaybe-uninitialized]
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target //tensorflow/python/tools:print_selective_registration_header failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 724.181s, Critical Path: 123.60s
INFO: 2191 processes: 2191 local.
FAILED: Build did NOT complete successfully
