### ISSUE TITLE
Error importing TensorFlow nightly gpu (docker)

### ISSUE THREAD

**Issue by bkazi** [tensorflow/tensorflow#25799]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: Docker
- TensorFlow version: nightly-gpu
- Python version: 2
- CUDA version: Driver Version: 410.79 CUDA Version: 10.0
- GPU model and memory: Nvidia Tesla P100 16280MiB

(similar issue when installed from pip, not in a container with cuDNN v7 not sure if this would affect the Docker container)

**Describe the problem**
Using `tensorflow/tensorflow:nightly-gpu` image with the following code
```python
import tensorflow as tf

print("hello world")
```
yields
```
Floating point exception (core dumped)
```
as output

Using `tensorflow/tensorflow:latest-gpu` image works perfectly

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Fresh installation of ubuntu 18.04  
installed nvidia drivers and cuda through `apt-get` 
verified by building code samples and running the `deviceQuery` executable as described [here](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#running-binaries)

installed docker as described [here](https://docs.docker.com/install/linux/docker-ce/ubuntu/) and nvidia-docker as described [here](https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0))

same issue when using version installed from pip (`pip install --user tf-nightly-gpu`), not in a container
cuDNN v7, installation verified by running [mnistCUDNN](https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#verify) example

**Any other info / logs**
Running through gdb (not in a container, using pip version as above) gives the following
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4088700 (LWP 4806)]
[New Thread 0x7ffff3887700 (LWP 4807)]
[New Thread 0x7fffef086700 (LWP 4808)]
[New Thread 0x7fffec885700 (LWP 4809)]
[New Thread 0x7fffec084700 (LWP 4810)]
[New Thread 0x7fffe9883700 (LWP 4811)]
[New Thread 0x7fffe5082700 (LWP 4812)]
[New Thread 0x7fffe2881700 (LWP 4813)]
[New Thread 0x7fffe0080700 (LWP 4814)]
[New Thread 0x7fffdd87f700 (LWP 4815)]
[New Thread 0x7fffdb07e700 (LWP 4816)]
[New Thread 0x7fffd887d700 (LWP 4817)]
[New Thread 0x7fffd607c700 (LWP 4818)]
[New Thread 0x7fffd387b700 (LWP 4819)]
[New Thread 0x7fffd107a700 (LWP 4820)]
[New Thread 0x7fffce879700 (LWP 4821)]
[New Thread 0x7fffcc078700 (LWP 4822)]
[New Thread 0x7fffcb877700 (LWP 4823)]
[New Thread 0x7fffc7076700 (LWP 4824)]
[New Thread 0x7fffc4875700 (LWP 4825)]
[New Thread 0x7fffc2074700 (LWP 4826)]
[New Thread 0x7fffbf873700 (LWP 4827)]
[New Thread 0x7fffbf072700 (LWP 4828)]

Thread 1 "python" received signal SIGFPE, Arithmetic exception.
0x00007fff83ffdeba in _GLOBAL__sub_I_jit_avx512_common_conv_kernel.cpp ()
   from /home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
```

**Comment by angersson** [comment]
This looks like an issue in the nightly pip packages, not with the docker images specifically (thank you for mentioning that the problem also appears outside of Docker). @jvishnuvardhan, could you find a more fitting assignee, please?

**Comment by twopisoft** [comment]
I am seeing similar SIGFPE when doing import on a system that is running CentOS 6.7 and no GPU. I am using TensorFlow 1.10 from Anaconda 5.3 (python 2.7.15). It also happens with TensorFlow 1.12. 

`Program received signal SIGFPE, Arithmetic exception.
0x00007fffda47f846 in _GLOBAL__sub_I_jit_avx512_common_conv_kernel.cpp () from /home/user1/anaconda2/lib/python2.7/site-packages/tensorflow/python/../libtensorflow_framework.so`

**Comment by jvishnuvardhan** [comment]
@bkazi Could you check with later version of TF and let us know whether the bug persists? Thanks!

**Comment by bkazi** [comment]
Tried it on a fresh Ubuntu 18.04 VM
Followed the [GPU support guide](https://www.tensorflow.org/install/gpu) to install drivers and libs
Driver Version: 418.40.04    CUDA Version: 10.1
Python 3.6.7
TensorFlow 1.13.1
and it works! 👍

**Comment by jvishnuvardhan** [comment]
@bkazi Thanks for the confirmation. I am closing this issue. Thanks!
