### ISSUE TITLE
[TF 2.0 API Docs] tf.AggregationMethod

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25794]
### Existing URLs containing the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/AggregationMethod

### Description of issue (what needs changing):

* **Correct Links**
https://github.com/tensorflow/tensorflow/blob/master/python/ops/gradients_util.py is incorrect. The correct link should be https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/gradients_util.py.

* **Clear Description**
The description is not opinionated about when to use this symbol, and unclear on what aggregation methods for combining gradients would be useful for. 

* **Usage Example**
No usage example is provided.

* **Parameters Defined**
Parameters are poorly defined, and not formatted appropriately.

* **Returns Defined**
Returns are not defined.

* **Raises Listed and Defined**
Errors are not defined.

* **Visuals, if Applicable**
No visuals are included.

**Comment by Rajiv2605** [comment]
@dynamicwebpaige I'm interested in working on this issue!

**Comment by Ayush517** [comment]
@dynamicwebpaige Can I please work on this?

**Comment by dynamicwebpaige** [comment]
@Rajiv2605 @Ayush517 - Absolutely! Any contributions that improve our API docs are extremely welcome. 😊

**Comment by Ayush517** [comment]
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/AggregationMethod
While opening the link on this page, I am getting redirected to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/gradients_util.py which is the correct link mentioned in the issue. It's working fine I think.

**Comment by bharatnishant** [comment]
Is this issue still open as it still has an open status?

**Comment by jackwangshanghai** [comment]
How to use tf.AggregationMethod in tf2.0. 
In tf1.0 it can be passthrough the 
optimizer.minimize(loss, method_aggregation =  tf.AggregationMethod.EXPERIMANTAL_TREE)
And it can help if GPU is OOM.
But how to use that in TF 2.0?

**Comment by chinmoysarangi** [comment]
Hi @dynamicwebpaige ,

Is this issue still Open? Asking so that I can work on it?

Thanks and Gratitude!

**Comment by animeshseemendra** [comment]
I am interested to work on it. Can I ? @dynamicwebpaige

**Comment by MarkDaoust** [comment]
Hi @chinmoysarangi, 

Paige has a [lot of these bugs](https://www.tensorflow.org/community/contribute/docs_ref), I doubt she working on this particular one right now.

Also if you're working on api pages be sure to have a look at [this doc](https://www.tensorflow.org/community/contribute/docs_ref).

**Comment by cyberShaw** [comment]
Is the issue still open? I'm interested to contribute

**Comment by vadera11jeet** [comment]
can I work on this issue?

**Comment by MarkDaoust** [comment]
The links on this page are fixed.
