### ISSUE TITLE
Can't rename checkpoint directories

### ISSUE THREAD

**Issue by Storyyeller** [tensorflow/tensorflow#25795]
**System information**
- TensorFlow version (you are using): 1.12.0
- Are you willing to contribute it (Yes/No): Probably, but I'm not sure exactly what needs to be changed and/or what change would be considered acceptable

**Describe the feature and the current behavior/state.**
Currently, if you rename or copy a checkpoint directory, tensorflow will refuse to load checkpoints from it. This is because it looks in the `checkpoint` file in that directory and loads a filepath from the protobuf. If that filepath doesn't match, it refuses to load any checkpoints for some reason.

**Will this change the current api? How?**
It will make loading checkpoints work as expected. I am not sure if anyone is relying on the current behavior.

**Who will benefit with this feature?**
Anyone who wants to easily back up and restore their checkpoints.

**Any Other info.**
I am not the first person to run into this issue. I see it was already reported [here](https://github.com/tensorflow/tensorflow/issues/13186) but that issue was closed with a request to resubmit (which apparently never happened).

**Comment by allenlavoie** [comment]
Assuming you're using `tf.train.Saver`, this is the `save_relative_paths` argument to `__init__`.
