### ISSUE TITLE
can not import libcublas.so.9.0 in centos7 systemctl service

### ISSUE THREAD

**Issue by policeme** [tensorflow/tensorflow#25797]
I try to put a service into systemctl service, so I write a systemctl service command. But when I run this systemctl service, it occur ImportError, my error message is below!
![image](https://user-images.githubusercontent.com/30991932/52897039-72e23580-320a-11e9-836e-af54822007e4.png)

this is my systemctl service command detail.
![image](https://user-images.githubusercontent.com/30991932/52897052-a8871e80-320a-11e9-8ecf-324ad1cd8297.png)

but when I import tensorflow in python command, it correct.
![image](https://user-images.githubusercontent.com/30991932/52897066-cbb1ce00-320a-11e9-9e7b-399f4beffd94.png)

this is my environment.
tensorflow=1.12
cuda=9.0
cudnn=7.4

Is this a bug of tensorflow 1.12

**Comment by policeme** [comment]
Can anyone help me. Please!

**Comment by BenjaminChoou** [comment]
Have you exported your Cuda path to PATH?

**Comment by policeme** [comment]
this is my ~/.bashrc detail. but it still not work.
![image](https://user-images.githubusercontent.com/30991932/52897616-a1174380-3211-11e9-8b9b-4b8eaf2b95d0.png)

**Comment by policeme** [comment]
And this is my path detail.
![image](https://user-images.githubusercontent.com/30991932/52897635-c4da8980-3211-11e9-92e1-41fa02285927.png)

**Comment by BenjaminChoou** [comment]
And what's the output of `ls /usr/local/cuda-9.0/lib64/`? It should include 'libcublas.so.9.0'.

**Comment by policeme** [comment]
It's include


from Alimail iPhone
 ------------------Original Mail ------------------

**Comment by BenjaminChoou** [comment]
> It's include from Alimail iPhone ------------------Original Mail ------------------ From:BenjaminChou <notifications@github.com> Date:2019-02-16 18:52:06 Recipient:tensorflow/tensorflow <tensorflow@noreply.github.com> CC:Cally <mx15025700935@aliyun.com>, Author <author@noreply.github.com> Subject:Re: [tensorflow/tensorflow] can not import libcublas.so.9.0 in centos7 systemctl service (#25797) And what's the output of ls /usr/local/cuda-9.0/lib64/? It should include 'libcublas.so.9.0'. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

It is quite weird. How about try this?
`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
If this won't work, I believe there's some wrong configuration. But I am not sure without extra info. You could follow the cuda & cudnn installations provided by Nvidia. And try to build the tensorflow from source. Sorry can't help u.

**Comment by policeme** [comment]
Not mind. can i keep the question open util i solve the problem?


from Alimail iPhone
 ------------------Original Mail ------------------

**Comment by BenjaminChoou** [comment]
> Not mind. can i keep the question open util i solve the problem? from Alimail iPhone ------------------Original Mail ------------------ From:BenjaminChou <notifications@github.com> Date:2019-02-16 19:25:04 Recipient:tensorflow/tensorflow <tensorflow@noreply.github.com> CC:Cally <mx15025700935@aliyun.com>, Author <author@noreply.github.com> Subject:Re: [tensorflow/tensorflow] can not import libcublas.so.9.0 in centos7 systemctl service (#25797) It's include from Alimail iPhone ------------------Original Mail ------------------ From:BenjaminChou notifications@github.com Date:2019-02-16 18:52:06 Recipient:tensorflow/tensorflow tensorflow@noreply.github.com CC:Cally mx15025700935@aliyun.com, Author author@noreply.github.com Subject:Re: [tensorflow/tensorflow] can not import libcublas.so.9.0 in centos7 systemctl service (#25797) And what's the output of ls /usr/local/cuda-9.0/lib64/? It should include 'libcublas.so.9.0'. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. It is quite weird. How about try this? python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)" If this won't work, I believe there's some wrong configuration. But I am not sure without extra info. You could follow the cuda & cudnn installations provided by Nvidia. And try to build the tensorflow from source. Sorry can't help u. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Why not? Wish someone could help u.

**Comment by jvishnuvardhan** [comment]
@policeme DId you try the installation instructions at Tensorflow [website](https://www.tensorflow.org/install/source)? or check the solution provided at this [resource](https://github.com/tensorflow/tensorflow/issues/25557). Please let me know how it progresses. Thanks!

**Comment by policeme** [comment]
@jvishnuvardhan  you want to me installing the bazel?

**Comment by jvishnuvardhan** [comment]
@policeme It looks like there is a configuration issue. You could uninstall current TF and build TF from source using the resource i provided to you or any other good resource. Please let me know how it progresses. Thanks!

**Comment by policeme** [comment]
@jvishnuvardhan  sorry it's difficult to uninstall current TF, because the current TF is in product environment, sorry.
this is my steps of install tensorflow-gpu
1. install Anaconda3
   a. yum install -y bzip2
   b.add environment path of anaconda3
   c. install tensorflow-gpu
2. install cuda-9.0
    a. Wget https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda_9.0.176_384.81_linux-run 
    b. install cuda-toolkit, just install cuda-tookit during install cuda-9.0, not install others, like opengl and so on.
3.install cudnn 7.4
    a. download from cudnn website, version is 7.4
    b. copy cudnn file into cuda-9.0
        1) cp include/* /usr/local/cuda-9.0/inlcude/
        2) cp lib64/lib* /usr/local/cuda-9.0/lib64/
4. add environment of cuda-9.0
    a. sudo vim /etc/profile
    b. export PATH=/usr/local/cuda-9.0/bin:$PATH
    c. export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH
     d.source /etc/profile

finish install tensorlfow-gpu

Do I had some error install steps?

**Comment by jvishnuvardhan** [comment]
@policeme I wrote the installation [steps](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12/blob/master/README.md) for installing TF1.12_gpu on Windows 10 system. The steps are similar to what you mentioned. From my experience when you install through Anaconda( for TF_gpu), some of the CUDA paths are not referenced correctly. I think it is better to install NVDIA drivers, CUDA, cuDNN, visual studio IDE, and python before installing tennsorflow_gpu. Please check the steps I listed and follow similar procedure and let me know how it progresses. Thanks!

**Comment by policeme** [comment]
@jvishnuvardhan I installed the NVIDIA driver before install Anaconda, my GPU model is NVIDIA V100 16G

**Comment by jvishnuvardhan** [comment]
@policeme Not sure about Anaconda. If you could follow the steps I listed and some thing is not working, then I could help. There is no support for Anaconda based installation. You could check stackoverflow or closed Anaconda related issues on GitHub. I will close the issue. Thanks!
