### ISSUE TITLE
Speed of benchmark code in CPU windows is much slower than ubuntu

### ISSUE THREAD

**Issue by onzone** [tensorflow/tensorflow#25798]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 and Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12
- Python version: 3.5
- Bazel version (if compiling from source):0.18
- GCC/Compiler version (if compiling from source): MSVC 14 in windows 
- CUDA/cuDNN version: N/A
- GPU model and memory:N?A

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I have built the tensorflow v1.12. from source using bazel with the following configuration: 
```
build --action_env PYTHON_BIN_PATH="C:/Python35/python.exe"
build --action_env PYTHON_LIB_PATH="C:/Python35/lib/site-packages"
build --python_path="C:/Python35/python.exe"
build:ignite --define with_ignite_support=true
build:xla --define with_xla_support=true
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="0"
build --action_env TF_DOWNLOAD_CLANG="0"
build:opt --copt=/arch:AVX
build:opt --define with_default_optimizations=true
build --config monolithic
build --copt=-w --host_copt=-w
build --verbose_failures
build --distinct_host_configuration=false
build --experimental_shortened_obj_file_path=true
build --define=no_tensorflow_py_deps=true
build:v2 --define=tf_api_version=2
```
After succesful build I ran the benchmark code provided in "tensorflow/tools/benchmark/benchmark_model_main.cc".  But I see the speed in windows is much slower(almost twice) than in ubuntu.In windows the inference time is on average ~25 ms and in ubuntu the timing is ~14ms. I am using the same machine in dual boot mode.

**Code to reproduce the issue**
tensorflow/tools/benchmark/benchmark_model_main.cc

**Comment by subhasis1990** [comment]
I have tried to reproduce the results in my end and the timing difference is very much consistent. I have dual-booted my machine with Windows 10 and Ubuntu 16.0. I have listed down the timing that I found for a single forward pass of the network. Timings are calculated by averaging over 1000 iterations. I have used the example code given in the tensorflow repo(tensorflow/examples/label_image/label_image.py). I have used python 3.5 in each of the setting and use the command "pip3 install --upgrade tensorflow==1.12" to install tensorflow. I have used the model "inception_v3_2016_08_28_frozen.pb" mentioned in the example.
![timing_tf_different_platforms](https://user-images.githubusercontent.com/16721547/53478604-3b427b80-3a9d-11e9-9116-608504b008e0.PNG)
The code for getting the inference time is as follows and the model can be found by executing following link:
https://storage.googleapis.com/download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz
`
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse

import numpy as np
import tensorflow as tf

import time

def load_graph(model_file):
  graph = tf.Graph()
  graph_def = tf.GraphDef()

  with open(model_file, "rb") as f:
    graph_def.ParseFromString(f.read())
  with graph.as_default():
    tf.import_graph_def(graph_def)

  return graph


def read_tensor_from_image_file(file_name,
                                input_height=299,
                                input_width=299,
                                input_mean=0,
                                input_std=255):
  input_name = "file_reader"
  output_name = "normalized"
  file_reader = tf.read_file(file_name, input_name)
  if file_name.endswith(".png"):
    image_reader = tf.image.decode_png(
        file_reader, channels=3, name="png_reader")
  elif file_name.endswith(".gif"):
    image_reader = tf.squeeze(
        tf.image.decode_gif(file_reader, name="gif_reader"))
  elif file_name.endswith(".bmp"):
    image_reader = tf.image.decode_bmp(file_reader, name="bmp_reader")
  else:
    image_reader = tf.image.decode_jpeg(
        file_reader, channels=3, name="jpeg_reader")
  float_caster = tf.cast(image_reader, tf.float32)
  dims_expander = tf.expand_dims(float_caster, 0)
  resized = tf.image.resize_bilinear(dims_expander, [input_height, input_width])
  normalized = tf.divide(tf.subtract(resized, [input_mean]), [input_std])
  sess = tf.Session()
  result = sess.run(normalized)

  return result


def load_labels(label_file):
  label = []
  proto_as_ascii_lines = tf.gfile.GFile(label_file).readlines()
  for l in proto_as_ascii_lines:
    label.append(l.rstrip())
  return label


if __name__ == "__main__":
  file_name = "grace_hopper.jpg"
  model_file = \
    "inception_v3_2016_08_28_frozen.pb"
  label_file = "imagenet_slim_labels.txt"
  input_height = 299
  input_width = 299
  input_mean = 0
  input_std = 255
  input_layer = "input"
  output_layer = "InceptionV3/Predictions/Reshape_1"
  max_run=1000

  parser = argparse.ArgumentParser()
  parser.add_argument("--image", help="image to be processed")
  parser.add_argument("--graph", help="graph/model to be executed")
  parser.add_argument("--labels", help="name of file containing labels")
  parser.add_argument("--input_height", type=int, help="input height")
  parser.add_argument("--input_width", type=int, help="input width")
  parser.add_argument("--input_mean", type=int, help="input mean")
  parser.add_argument("--input_std", type=int, help="input std")
  parser.add_argument("--input_layer", help="name of input layer")
  parser.add_argument("--output_layer", help="name of output layer")
  args = parser.parse_args()

  if args.graph:
    model_file = args.graph
  if args.image:
    file_name = args.image
  if args.labels:
    label_file = args.labels
  if args.input_height:
    input_height = args.input_height
  if args.input_width:
    input_width = args.input_width
  if args.input_mean:
    input_mean = args.input_mean
  if args.input_std:
    input_std = args.input_std
  if args.input_layer:
    input_layer = args.input_layer
  if args.output_layer:
    output_layer = args.output_layer

  graph = load_graph(model_file)
  t = read_tensor_from_image_file(
      file_name,
      input_height=input_height,
      input_width=input_width,
      input_mean=input_mean,
      input_std=input_std)

  input_name = "import/" + input_layer
  output_name = "import/" + output_layer
  input_operation = graph.get_operation_by_name(input_name)
  output_operation = graph.get_operation_by_name(output_name)
  

  #warm-up run  
  config_proto = tf.ConfigProto(intra_op_parallelism_threads=8,inter_op_parallelism_threads=1)
  sess = tf.Session(graph=graph, config=config_proto)
  
  results = sess.run(output_operation.outputs[0], {input_operation.outputs[0]: t})  

  avg_inference_time=0.0
  for iter in range(max_run):
      start=time.time()
      results = sess.run(output_operation.outputs[0], {input_operation.outputs[0]: t})  
      inference_time = time.time() - start
      avg_inference_time += inference_time
      print('inference_time: '+str(inference_time))

  avg_inference_time /= max_run
  print('avg inference time: '+str(avg_inference_time))`

**Comment by subhasis1990** [comment]
I have tried to reproduce the results in my end and the timing difference is very much consistent. I have dual-booted my machine with Windows 10 and Ubuntu 16.0. I have listed down the timing that I found for a single forward pass of the network. Timings are calculated by averaging over 1000 iterations. I have used the example code given in the tensorflow repo(tensorflow/examples/label_image/label_image.py). I have used python 3.5 in each of the setting and use the command "pip3 install --upgrade tensorflow==1.12" to install tensorflow. I have used the model "inception_v3_2016_08_28_frozen.pb" mentioned in the example.
![timing_tf_different_platforms](https://user-images.githubusercontent.com/16721547/53478604-3b427b80-3a9d-11e9-9116-608504b008e0.PNG)
The code for getting the inference time is as follows and the model can be found by executing following link:
https://storage.googleapis.com/download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse

import numpy as np
import tensorflow as tf

import time

def load_graph(model_file):
  graph = tf.Graph()
  graph_def = tf.GraphDef()

  with open(model_file, "rb") as f:
    graph_def.ParseFromString(f.read())
  with graph.as_default():
    tf.import_graph_def(graph_def)

  return graph


def read_tensor_from_image_file(file_name,
                                input_height=299,
                                input_width=299,
                                input_mean=0,
                                input_std=255):
  input_name = "file_reader"
  output_name = "normalized"
  file_reader = tf.read_file(file_name, input_name)
  if file_name.endswith(".png"):
    image_reader = tf.image.decode_png(
        file_reader, channels=3, name="png_reader")
  elif file_name.endswith(".gif"):
    image_reader = tf.squeeze(
        tf.image.decode_gif(file_reader, name="gif_reader"))
  elif file_name.endswith(".bmp"):
    image_reader = tf.image.decode_bmp(file_reader, name="bmp_reader")
  else:
    image_reader = tf.image.decode_jpeg(
        file_reader, channels=3, name="jpeg_reader")
  float_caster = tf.cast(image_reader, tf.float32)
  dims_expander = tf.expand_dims(float_caster, 0)
  resized = tf.image.resize_bilinear(dims_expander, [input_height, input_width])
  normalized = tf.divide(tf.subtract(resized, [input_mean]), [input_std])
  sess = tf.Session()
  result = sess.run(normalized)

  return result


def load_labels(label_file):
  label = []
  proto_as_ascii_lines = tf.gfile.GFile(label_file).readlines()
  for l in proto_as_ascii_lines:
    label.append(l.rstrip())
  return label


if __name__ == "__main__":
  file_name = "grace_hopper.jpg"
  model_file = \
    "inception_v3_2016_08_28_frozen.pb"
  label_file = "imagenet_slim_labels.txt"
  input_height = 299
  input_width = 299
  input_mean = 0
  input_std = 255
  input_layer = "input"
  output_layer = "InceptionV3/Predictions/Reshape_1"
  max_run=1000

  parser = argparse.ArgumentParser()
  parser.add_argument("--image", help="image to be processed")
  parser.add_argument("--graph", help="graph/model to be executed")
  parser.add_argument("--labels", help="name of file containing labels")
  parser.add_argument("--input_height", type=int, help="input height")
  parser.add_argument("--input_width", type=int, help="input width")
  parser.add_argument("--input_mean", type=int, help="input mean")
  parser.add_argument("--input_std", type=int, help="input std")
  parser.add_argument("--input_layer", help="name of input layer")
  parser.add_argument("--output_layer", help="name of output layer")
  args = parser.parse_args()

  if args.graph:
    model_file = args.graph
  if args.image:
    file_name = args.image
  if args.labels:
    label_file = args.labels
  if args.input_height:
    input_height = args.input_height
  if args.input_width:
    input_width = args.input_width
  if args.input_mean:
    input_mean = args.input_mean
  if args.input_std:
    input_std = args.input_std
  if args.input_layer:
    input_layer = args.input_layer
  if args.output_layer:
    output_layer = args.output_layer

  graph = load_graph(model_file)
  t = read_tensor_from_image_file(
      file_name,
      input_height=input_height,
      input_width=input_width,
      input_mean=input_mean,
      input_std=input_std)

  input_name = "import/" + input_layer
  output_name = "import/" + output_layer
  input_operation = graph.get_operation_by_name(input_name)
  output_operation = graph.get_operation_by_name(output_name)
  

  #warm-up run  
  config_proto = tf.ConfigProto(intra_op_parallelism_threads=1,inter_op_parallelism_threads=1)
  sess = tf.Session(graph=graph, config=config_proto)
  
  results = sess.run(output_operation.outputs[0], {input_operation.outputs[0]: t})  

  avg_inference_time=0.0
  for iter in range(max_run):
      start=time.time()
      results = sess.run(output_operation.outputs[0], {input_operation.outputs[0]: t})  
      inference_time = time.time() - start
      avg_inference_time += inference_time
      print('inference_time: '+str(inference_time))

  avg_inference_time /= max_run
  print('avg inference time: '+str(avg_inference_time))
```

**Comment by penpornk** [comment]
Thank you for reporting and confirming the issue, and I'm sorry for my delay! I'll try to look into this next week!

**Comment by franticguy** [comment]
Hi, I am facing the same problem. Has anyone solved this?

**Comment by penpornk** [comment]
Not yet. I'm having my hands full with other issues. Will try to look at this soon or find other people  to do so. Sorry for the delay!

**Comment by mohantym** [comment]
Hi @onzone ! Is this issue still valid in the 2.8 version too?
