### ISSUE TITLE
[TF 2.0 API Docs] tf.math.acos

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25802]
**System information**
- TensorFlow version: 2.0
- Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/acos

**Describe the documentation issue**

Documentation for `tf.math.acos` is created from a generated file, `python/ops/gen_math_ops.py`. It would be excellent to have a link to the files that are used to generate `gen_math_ops.py` - so a user could make modifications quickly, without having to search through `tensorflow/tensorflow`.

`tf.math.acos` could use a clear description, usage examples, and example visuals. A great template to model this on could be [`numpy.arccos`](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.arccos.html).

Users also experience obfuscated errors from unexpected arguments (ex: strings, Booleans, and even just `int`s). Some examples are shared below. The file used to generate this error is located [here](https://github.com/tensorflow/tensorflow/blob/e1d20b3b4f25047679cf34107f8d87329cc9070f/tensorflow/core/common_runtime/eager/execute.cc#L201). All `tf.math.*` operations and the operations they influence (e.g., `tf.linspace`) would experience these same obfuscated XLA errors.

```
InvalidArgumentError: Invalid cast from floating point type to S32 in ConstantR0WithType.
	 [[{{node Acos}}]] [Op:Acos]
```

```
InternalError: Could not find valid device for node.
Node: {{node Acos}}
All kernels registered for op Acos :
  device='XLA_CPU'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_COMPLEX128, DT_HALF]
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_COMPLEX128, DT_HALF]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
 [Op:Acos]
```

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
I shall certainly try! :)

**Comment by Sudeepam97** [comment]
Hi @dynamicwebpaige. I searched through the tensorflow repo, and it looks like one needs to edit the .pbtxt files inside `tensorflow/tensorflow/core/api_def/base_api` to modify the documentation. Can you confirm this?

**Comment by dynamicwebpaige** [comment]
@Sudeepam97 I _believe_ that the `gen_math_ops.py` file is generated from [`tensorflow.bzl`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl). There are C++ kernels located [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/kernels) for each op - most of the mathematical operations live in that repo. :slightly_smiling_face: 

cc: @MarkDaoust @lamberta to keep me honest, though! Do we have a recommended process for updating those docs?

**Comment by dynamicwebpaige** [comment]
@Sudeepam97 Just confirmed that you are correct! Apologies for the confusion - the `.pbtxt`files in [`/base_api`](https://github.com/tensorflow/tensorflow/tree/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/core/api_def/base_api) still create the documentation for several of the TF 2.0 math endpoints.

Let me take a look at your PR; we might need to tweak the syntax a little bit (format is a special flavor of markdown). Check out [this](https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/core/api_def/base_api/api_def_Pow.pbtxt) endpoint for a usage example.

**Comment by Sudeepam97** [comment]
@dynamicwebpaige, that's great! Please take your time to review the PR, I'll be happy to work on any changes that are necessary. :smile: 
I seem to understand how to modify the API docs now. I can work on other similar issues as well.

**Comment by SSaishruthi** [comment]
@dynamicwebpaige 
Created 5 PRs covering some of the math functions. Working on other functions.

**Comment by parasgoyal12** [comment]
I would love contributing to this. Please tell me how to proceed as I am newcomer.

**Comment by rohanreddych** [comment]
@SSaishruthi are there any ops left to do

**Comment by mihaimaruseac** [comment]
Just a note for people working on this: if you add python doctests, please make sure to do so in Python files, not in base_api/api_def files as those are the APIs for other languages too.

**Comment by Harsh188** [comment]
#42496

**Comment by Harsh188** [comment]
Looks like the changes made to `tf.math.acos` and `tf.math.add` were not merged with the previous PRs. I have opened a new PR to address this. Since this is my first PR I'm limiting the number of changes I make to only the `.pbtxt` files. Once I get this sorted out I will begin to modify `.Docs` in `math_ops.cc` to reflect the changes.

**Comment by imrahul361** [comment]
is anyone working on this issue? @dynamicwebpaige

**Comment by mihaimaruseac** [comment]
#42619 solved this

The [nightly version](https://www.tensorflow.org/api_docs/python/tf/math/acos?version=nightly) has updated docstring.
