### ISSUE TITLE
TensorBoard logging batch level metrics with tf.keras

### ISSUE THREAD

**Issue by Threynaud** [tensorflow/tensorflow#25801]
This is something that has been added quite recently in the Keras library, see discussion [there](https://github.com/keras-team/keras/issues/6692):
"It'd be useful if there was some batch-level logging in TensorBoard when using the TensorBoard callback (as defined in keras/callbacks.py). I think this'd be generally useful when trying to keep track of stats between epochs."

Currently using the `TensorBoard` callback like so will only log metrics at the end of each epoch, which can quickly become a problem for big datasets:
```
tensorboard = TensorBoard(log_dir="logs/{}".format(time()))
model.fit(x=training_set, epochs=epochs, validation_data=validation_set, callbacks=[tensorboard])
```

This is already merged in the Keras library, see [here](https://github.com/keras-team/keras/pull/11152).

**Comment by jvishnuvardhan** [comment]
@Threynaud Please fill the system information as requested in template [here](https://github.com/tensorflow/tensorflow/issues/new?template=30-feature-request.md). Thanks!

**Comment by yongtang** [comment]
@Threynaud From the source code it looks like the feature has already been added in tensorflow.keras:


https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L1131-L1136

**Comment by Threynaud** [comment]
Indeed, I guess I only had a look at the 1.12 documentation! Thanks for pointing this out @yongtang !
