### ISSUE TITLE
ERROR: /home/max/tensorflow/tensorflow/python/eager/BUILD:10:1: undeclared inclusion(s) in rule '//tensorflow/python/eager:pywrap_tfe_lib':

### ISSUE THREAD

**Issue by lorenzesz** [tensorflow/tensorflow#25817]
****System information**

* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
* Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
* TensorFlow installed from (source or binary): source
* TensorFlow version: 1.13.0rc2
* Python version: 3.7.2
* Installed using virtualenv? pip? conda?: pip
* Bazel version (if compiling from source): 0.22
* GCC/Compiler version (if compiling from source): 6.5.0
* CUDA/cuDNN version: 10.0/7.3
* GPU model and memory: RTX 2070 and 8GB

**Describe the problem**

ERROR: /home/max/tensorflow/tensorflow/python/eager/BUILD:10:1: undeclared inclusion(s) in rule '//tensorflow/python/eager:pywrap_tfe_lib':
this rule is missing dependency declarations for the following files included by 'tensorflow/python/eager/pywrap_tensor.cc':
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/arrayobject.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/ndarrayobject.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/ndarraytypes.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_common.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/numpyconfig.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/_numpyconfig.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_endian.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_cpu.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/utils.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/_neighborhood_iterator_imp.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/__multiarray_api.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_interrupt.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/ufuncobject.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_math.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_common.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/arrayobject.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/__ufunc_api.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build**

**Comment by lorenzesz** [comment]
downgrade to Python 2 fixed this.

**Comment by jvishnuvardhan** [comment]
@lorenzesz Did you try TF2.0-preview? Thanks!

**Comment by lorenzesz** [comment]
I have compiled it with python 3.6 now. 2.0 is not ready for development, but I can compile for testing this night.

**Comment by jvishnuvardhan** [comment]
@lorenzesz Is this issue resolved? If yes, please close the issue. Thanks!

**Comment by racinmat** [comment]
Does it work with python 3? I don't believe you can compile tensorflow only with python 2.
