### ISSUE TITLE
toco: error: argument --output_file is required

### ISSUE THREAD

**Issue by inakaaay** [tensorflow/tensorflow#25811]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
`IMAGE_SIZE=224
toco \
  --input_file=tf_files/retrained_graph.pb \
  --output_file=tf_files/optimized_graph.tflite \
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --input_shape=1,${IMAGE_SIZE},${IMAGE_SIZE},3 \
  --input_array=input \
  --output_array=final_result \
  --inference_type=FLOAT \
  --input_data_type=FLOAT`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Im using windows subsytems for linux
- TensorFlow version (use command below):
tensorflow 1.12
- Python version:
2.7

**Describe the current behavior**
i want to convert my custom model to tflite as stated in [this](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2-tflite/#2) but it gives a toco error saying toco: error: argument --output_file is required

**Other info / logs**

this was the whole log:
`usage: toco [-h] --output_file OUTPUT_FILE
            (--graph_def_file GRAPH_DEF_FILE | --saved_model_dir SAVED_MODEL_DIR | --keras_model_file KERAS_MODEL_FILE)
            [--output_format {TFLITE,GRAPHVIZ_DOT}]
            [--inference_type {FLOAT,QUANTIZED_UINT8}]
            [--inference_input_type {FLOAT,QUANTIZED_UINT8}]
            [--input_arrays INPUT_ARRAYS] [--input_shapes INPUT_SHAPES]
            [--output_arrays OUTPUT_ARRAYS]
            [--saved_model_tag_set SAVED_MODEL_TAG_SET]
            [--saved_model_signature_key SAVED_MODEL_SIGNATURE_KEY]
            [--std_dev_values STD_DEV_VALUES] [--mean_values MEAN_VALUES]
            [--default_ranges_min DEFAULT_RANGES_MIN]
            [--default_ranges_max DEFAULT_RANGES_MAX]
            [--post_training_quantize] [--drop_control_dependency]
            [--reorder_across_fake_quant]
            [--change_concat_input_ranges {TRUE,FALSE}] [--allow_custom_ops]
            [--converter_mode {DEFAULT,TOCO_FLEX,TOCO_FLEX_ALL}]
            [--dump_graphviz_dir DUMP_GRAPHVIZ_DIR] [--dump_graphviz_video]
toco: error: argument --output_file is required`

**Comment by ymodak** [comment]
duplicate #20984

**Comment by inakaaay** [comment]
already solved this with reinstalling tensorflow as `pip install – user tensorflow==1.12.0 –ignore-installed`
