### ISSUE TITLE
[TF 2.0 API Docs] tf.compat.path_to_str

### ISSUE THREAD

**Issue by rohanmeh** [tensorflow/tensorflow#25826]
**System information**
- TensorFlow version: 2.0
- Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/compat/path_to_str

### Existing URLs containing the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/compat/path_to_str

### Description of issue (what needs changing):
* **Correct Links**
  https://github.com/tensorflow/tensorflow/blob/master/python/util/compat.py is incorrect. The correct link should be https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/compat.py.
* **Clear Description**
  There could be a description of use cases where using this symbol would be appropriate. 
* **Raises Listed and Defined**
  Errors are not defined.
* **Visuals, if Applicable**
I do not think visuals are necessary for the symbol.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by ParthS007** [comment]
@rohanmeh Is this Issue still exist?
I would like to fix this.

**Comment by rohanmeh** [comment]
@parths007 pretty sure it still exists.

**Comment by mihaimaruseac** [comment]
Solved by #27335, additional attempt in #28502 came too late
