### ISSUE TITLE
tf.data.experimental.make_csv_dataset unable to handle missing data

### ISSUE THREAD

**Issue by RylanSchaeffer** [tensorflow/tensorflow#25825]
I believe this is a bug. I've been unable to get `tf.data.experimental.make_csv_dataset` to work with a CSV that contains missing data. As a toy example, suppose I have a single CSV file `example.csv` with the following contents:

```
date, value
D1,1017.1
D2, NA
```

When I run the following code, I receive the following error: `tensorflow.python.framework.errors_impl.InvalidArgumentError: Field 1 in record is not a valid float:  NA [Op:IteratorGetNextSync]`
```
import tensorflow as tf

tf.enable_eager_execution()
dataset = tf.data.experimental.make_csv_dataset(
            file_pattern=filenames,
            column_names=['date', 'value'],
            column_defaults=[tf.string, tf.float32],
            header=True,
            field_delim=',',
            na_value='NA'
        )
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()
```

Am I misusing the function? How am I supposed to specify that `NA` should be interpreted as a missing value? Replacing `NA` with a literal empty string results in the same problem:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Field 1 is required but missing in record! [Op:IteratorGetNextSync]`

My system's details:

- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 3.6

**Comment by RylanSchaeffer** [comment]
Someone on SO point out that the error is caused by specifying the `column_defaults` argument, which forces the default to be a float32 dtype only. I have two follow up questions. First, how could I have discovered that interaction? I just reread the documentation and that behavior isn't clear to me at all. Second, if I remove column_defaults, then missing floating values are replaced by 0s, whereas if I replace the missing floating values in the CSV with 'NA', then tf.data.experimental.make_csv_dataset sets dtype=object. How do I keep the column type as tf.float32 while maintaining the NAs?

**Comment by mrry** [comment]
Rachel, I think this is a feature request for better missing value handling in `make_csv_dataset()`

**Comment by rachellim** [comment]
Is the issue here the space character before the NA in your data? Matching the na_value requires an exact match. What if you did `na_value=" NA"`?

**Comment by rachellim** [comment]
@RylanSchaeffer

**Comment by RylanSchaeffer** [comment]
@rachellim I just tried, but it doesn't seem to make a difference. I created `test.csv` in a directory 


```
$ head test.csv 
date,value
D1,1017.1
D2,NA

```

Here's the exact code that I ran with Python 3 from the same directory containing `test.csv`:

```
import tensorflow as tf

filenames = ['test.csv']

tf.enable_eager_execution()
dataset = tf.data.experimental.make_csv_dataset(
            file_pattern=filenames,
            column_names=['date', 'value'],
            column_defaults=[tf.string, tf.float32],
            header=True,
            field_delim=',',
            na_value='NA',
            batch_size=1
        )
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()
```

But I received the same error:

```
>>> next_element = iterator.get_next()
2019-02-21 16:42:53.228099: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at iterator_ops.cc:1031 : Invalid argument: Field 1 is required but missing in record!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 623, in get_next
    return self._next_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 564, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2266, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 2, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Field 1 is required but missing in record! [Op:IteratorGetNextSync]
```

**Comment by rachellim** [comment]
Oh, I see. There are two different behaviors here, depending on whether you specify `column_defaults`:
1) If you specify `column_defaults` as a type (vs a value, e.g. 0.0), it treats the field as 'required', i.e. NA values not permitted. This is stated in the documentation: "If a dtype is provided instead of a tensor, the column is also treated as required. " I'll improve the error message here so that it's clearer.
2) If `column_defaults` is not provided, it tries to infer the column types from the data. This respects the `na_value` parameter, so it should correctly infer the type to be `tf.float` if you supply the correct NA value. Let me know if you find any issues with this.

These two statements should give you your expected behavior:
```
dataset = tf.data.experimental.make_csv_dataset(
            file_pattern=filenames,
            column_names=['date', 'value'],
            column_defaults=[tf.string, 3.14],  # or any other float default value you want here; missing values will default to this value
            header=True,
            field_delim=',',
            na_value='NA',
            batch_size=1
        )
```

```
dataset = tf.data.experimental.make_csv_dataset(
            file_pattern=filenames,
            column_names=['date', 'value'],
            header=True,
            field_delim=',',
            na_value='NA',
            batch_size=1
        )   # no column_defaults, na values default to empty string or 0
```

**Comment by RylanSchaeffer** [comment]
Hmm, my interpretation of "If a dtype is provided instead of a tensor, the column is also treated as required. " meant that the column itself needs to exist, not that every row in the column needs to have a value consistent with the specified type.

That said, I don't think either of the two solutions is what I'm looking for. In the first option, 'NA' will be converted to the specified float (e.g. 3.14 in the above example), and in the second option, 'NA' will be converted to the default float(e.g. 0.0). But I want the resulting tensor to contain `nan`. For example, in numpy, I can do `np.array([0., float('nan')])` and this returns `array([ 0., nan])`. 

So maybe this issue should be a feature request, not a bug?

**Comment by rachellim** [comment]
Ah, I see - I'll clarify the docstring to make that clearer.

What about doing `column_defaults=[tf.string, tf.constant(float('nan'), tf.float32)]`? That should make NA values for the second column become `nan`.

**Comment by RylanSchaeffer** [comment]
Fantastic! Thank you :)
