### ISSUE TITLE
[TF 2.0 API Docs] tf.keras.activations.serialize

### ISSUE THREAD

**Issue by rohanmeh** [tensorflow/tensorflow#25828]
**System information**
- TensorFlow version: 2.0
- Doc Link: https://www.tensorflow.org/versions/r1.13/api_docs/python/tf/keras/activations/serialize
* **Correct Links** https://github.com/tensorflow/tensorflow/blob/master/python/keras/activations.py is incorrect. The correct link should be https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/activations.py.
* **Clear Description**
  The description is not opinionated about when to use this symbol, or what happens when arguments are passed to the symbol.
* **Usage Example**
  No usage example is provided.
* **Parameters Defined**
  Parameters are poorly defined, and not formatted appropriately.
* **Returns Defined**
  Returns are not defined.
* **Raises Listed and Defined**
  Errors are not defined.

**Comment by lunayach** [comment]
It's a documentation of Python r1.13, and the link correctly sends us to https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/keras/activations.py
@dynamicwebpaige @rohanmeh  Am I missing soemthing here?

**Comment by jmammen** [comment]
Is someone currently working on this?

**Comment by onlyanegg** [comment]
I can handle this. I can also do the deserialize function. Do we need a separate issue / pr for that?

**Comment by asmitapoddar** [comment]
I have updated the entire activations doc including the functions `get`, `serialize`, `deserialize`, `linear` etc. and created a pull request.

**Comment by MarkDaoust** [comment]
@asmitapoddar, I'll go review that for you.
