### ISSUE TITLE
Tensorflow save & restore without using filesystem

### ISSUE THREAD

**Issue by cosmir17** [tensorflow/tensorflow#25839]
**System information**
- TensorFlow version (you are using): Up to date
- Are you willing to contribute it (Yes/No): Python is not my daily driver language

**Describe the feature and the current behavior/state.**
I would like to retrieve(instead of save) training information and restore it to a tensorflow session when necessary (without using file system). I want to bypass filesystem.

I have looked the followings and searched but was not successful.

https://www.tensorflow.org/guide/saved_model
https://stackoverflow.com/questions/33759623/tensorflow-how-to-save-restore-a-model

Why does this feature not appear already present?

**Will this change the current api? How?**

**Who will benefit with this feature?**
Distributed system, would be an easier way to persist and handle training data

**Any Other info.**
(as a side note, not important, this Tensorflow approach using filesystem might be plausible for Python. Nonetheless, I am using Scala Tensorflow and I would like to bypass the filesystem entirely and use Cassandra DB for a distributed environment. If I know how to do it in Python. It might be a similar approach in the Scala version, if not using the main APIs, by using byte codes, etc..)

**Comment by yongtang** [comment]
@cosmir17 The save and restore of models in tensorflow are done through a `file system` plugin system. It does not mean you have to use a file system, it only means there should be a "file read & write" like API. TF naturally support gcs (with `gs://...`) and s3 (with `s3://...`) which technically not exactly a file systems. Apache Ignite is also supported through `igfs://`.

For Cassandra, an implementation will be needed to have a file systems like interface to communicate and save/restore from Cassandra.

The file systems supports have been mostly moved to sig-io:
https://github.com/tensorflow/io

and there is a google group for discussion:
https://groups.google.com/a/tensorflow.org/forum/#!forum/io

**Comment by cosmir17** [comment]
@yongtang, thank you for your clarification. Yes, Tensorflow uses file system as a way of persisting training data (both implicitly and explicitly).
**1. I wanted to know a line of code or method that I can use to extract training data(as an object) and import it to (tf)session when necessary without me handling file path etc **
2. Cassandra, I am using Scala as I noted in the post, there is already a way to integrate with Cassandra (akka, persistence) so it won't be an issue.

**Comment by cosmir17** [comment]
I am closing this ticket. I should have asked for a Java tensorflow approach.
