### ISSUE TITLE
On the return values of bidirectional_rnn

### ISSUE THREAD

**Issue by jihunchoi** [tensorflow/tensorflow#2583]
Due to the overhead of `tf.concat` operations, it is recommended to use `state_is_tuple` flag in recurrent neural network layers.
However, I found that in `bidirectional_rnn` implementation, `outputs` (first return value) is returned as a concatenation of `outputs_fw` and `outputs_bw`.
Is there any reason that it should return the concatenated one?
I think it is trace of the days where concatenated states are used, and it would be nice to return forward and backward outputs separately.
It seems that it can be implemented simply without breaking backward compatibility, by adding a flag indicating what should be returned.

**Comment by ebrevdo** [comment]
We don't currently support the output being a tuple, only the state.  This should wait until we support the output_shape being a (possibly nested) tuple.  Then we can add this change.

**Comment by jihunchoi** [comment]
I don't understand exactly; can't we just return two variables `outputs_fw` and `outputs_bw` separately?
is there a reason that `outputs` should be a single variable?
I think the typical usage of `bidirectional_rnn` is to multiply `outputs` with a weight matrix of shape `(2 * hidden_size, vocab_size)`, which is identical with adding two results of multiplying weight matrices of `(hidden_size, vocab_size)` to forward and backward outputs.
In my opinion, separating two would give a performance gain and a bit more flexibility.

**Comment by ebrevdo** [comment]
For backwards compatibility reasons, we can't change bidirectional_rnn.  However we have an open PR implementing dynamic bidirectional rnn, and we can change the signature there to emit the final states.

**Comment by ebrevdo** [comment]
Indeed - your dynamic bidirectional rnn PR is the one i'm talking about ;)
