### ISSUE TITLE
YOLOv3 TFLite GPU and CPU perform at same speed

### ISSUE THREAD

**Issue by yeminnhtut** [tensorflow/tensorflow#25834]
**System information**
- Have I written custom code: No
- OS Platform and Distribution: Android
- Mobile device: Google Pixel, Google Pixel 2 and Xiaomi 6
- TensorFlow installed from: Binary 
  `implementation 'org.tensorflow:tensorflow-lite:0.0.0-gpu-experimental'`
- TensorFlow version: 1.13.0
- Python version: 3.6
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
Model inference time is the same for GPU and CPU (~5500 ms)

**Describe the expected behavior**
Expecting it to be faster on GPU

**Code to reproduce the issue**
```
Interpreter.Options options = new Interpreter.Options();
GpuDelegate delegate = new GpuDelegate();
options.addDelegate(delegate);
// loadModelFile is the same with that function in the sample
Interpreter tflite = new Interpreter(loadModelFile(this), options);

Map<Integer, Object> output = new HashMap<>();
float[][][][] output1 = new float[1][19][19][255];
float[][][][] output2 = new float[1][38][38][255];
output.put(0, output1);
output.put(1, output2);

tflite.runForMultipleInputsOutputs(getInput(), output);

private Object[] getInput() {
  Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.drawable.dog_cycle_car);
  // Mat and Improc are from OpenCV
  Mat mat = new Mat();
  Mat convertedMat = new Mat();
  Mat resizedMat = new Mat();
  Utils.bitmapToMat(bitmap, mat);
  mat.convertTo(convertedMat, CvType.CV_8UC1);
  Size size = new Size(608.0, 608.0);
  Imgproc.resize(convertedMat, resizedMat, size, 0.0, 0.0, Imgproc.INTER_AREA);
  Bitmap resizedBitmap = Bitmap.createBitmap(resizedMat.cols(), resizedMat.rows(), Bitmap.Config.ARGB_8888);
  Utils.matToBitmap(resizedMat, resizedBitmap);
  ByteBuffer imgData = convertBitmapToByteBuffer(resizedBitmap);
  Object[] inputArray = new Object[1];
  inputArray[0] = imgData;
  return inputArray;
}
```

The model I used https://drive.google.com/open?id=1XqNO1Qo5CJwzeP1d0w-mOyyk7DWJKfkk

**Comment by freedomtan** [comment]
For mobile phones, the YOLOv3 model you provided is a big one. It's likely to be IO-bounded.

**Comment by wangyiwei0306** [comment]
@yeminnhtut 
I also find the processing time is almost the same. But I encountered another question, when I add GPU delegate the processing results are totally different between CPU and GPU, may you heou lp me?

Expecting your answers!
Thank you very much.
https://github.com/tensorflow/tensorflow/issues/35378 this link is my problem.

**Comment by karimnosseir** [comment]
Are you still facing an issue ? Can you rerun and share the newest data ?

Thanks

**Comment by wangyiwei0306** [comment]
I'm very happy to tell you that this is not an problem now.
