### ISSUE TITLE
[TF 2.0 API Docs] tf.lite.TFLiteConverter

### ISSUE THREAD

**Issue by margaretmz** [tensorflow/tensorflow#25844]
**System information**
- TensorFlow version: 2.0
- Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/lite/TFLiteConverter

**Describe the documentation issue**

- **Links** (Fixed)

Incorrect - https://github.com/tensorflow/tensorflow/blob/master/lite/python/lite.py
Correct - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/lite.py

- **Description** (In PR #26067) 

This is used to convert from a TensorFlow "GraphDef or SavedModel" into either a TFLite FlatBuffer or graph visualization.

Should be "…GraphDef, Saved Model or tf.keras model…"

- **Usage example** (In PR #26067) 

This line of code should be repeated for each of the methods
open("converted_model.tflite", "wb").write(tflite_model)

- **Parameters Defined** (Fixed)

Missing 2 parameters
- optimizations
- representative_dataset

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?** 

Yes

**Comment by Ayush517** [comment]
Is this issue still unsolved? The PR seems to have solved it but it isn't still merged? Does that mean something is still left?

**Comment by margaretmz** [comment]
I'm waiting for PR $26067 to merge.
