### ISSUE TITLE
[tflite][java] how to deal with result of runForMultipleInputsOutputs()

### ISSUE THREAD

**Issue by GustavZ** [tensorflow/tensorflow#25841]
I am running posenet on android with tflite.
The model has multiple output arrays with the following dimensions:
`1x14x14x17, 1x14x14x34, 1x14x14x32, 1x14x14x32`

Therefore running the java tfliter interpreter with
```
import org.tensorflow.lite.Interpreter;
Interpreter tflite;
tflite.runForMultipleInputsOutputs(inputs,outputs)
```

i can access the four output tensors with `tflite.getOutputTensor(i)` or with `outputs.get(i)` (with i el. [0,3]) as `outputs` is a `HashMap` filled with `java.nio.HeapByteBuffer` objects.

How can I convert these outputs or tflite tensors to java multi-dimensional arrays (something like `float[][][][];`) to be able to perform mathematical computations on them?

**Comment by GustavZ** [comment]
Defining the outputs like the following lets you work with native java arrays, which is what i wanted:

    out1 = new float[1][14][14][17];
    out2 = new float[1][14][14][34];
    out3 = new float[1][14][14][32];
    out4 = new float[1][14][14][32];
    Map<Integer, Object> outputs = new HashMap<>();
    outputs.put(0, out1);
    outputs.put(1, out2);
    outputs.put(2, out3);
    outputs.put(3, out4);

**Comment by JianbangZ** [comment]
@gustavz I couldn't find any documents teaching running posenet on Android with the given tflite model file. Do you know the image input size for the given "multi_person_mobilenet_v1_075_float.tflite"?

**Comment by superying** [comment]
@JianbangZ  [  1 353 257   3] is the input size for the given "multi_person_mobilenet_v1_075_float.tflite".

**Comment by LiuPangYao** [comment]
input is use the same function?

**Comment by lincredibleJC** [comment]
@LiuPangYao Yes if you look at the Intepreter source code here
https://github.com/tensorflow/tensorflow/blob/6353d940289a225cfbc104cc647b3c6970077faa/tensorflow/lite/java/src/main/java/org/tensorflow/lite/Interpreter.java#L245
, you'll realise that run() uses runForMultipleInputsOutputs() with but just with one output.

**Comment by lmy931** [comment]
Anyone run  "multi_person_mobilenet_v1_075_float.tflite" successfully on Android or iOS?

**Comment by joker2017** [comment]
Hey. I have the same problem in ios swift. Tell me how to do this operation in swift

**Comment by drzraf** [comment]
```java
// The shape of *1* output's tensor
int[] OutputShape;
// The type of the *1* output's tensor
DataType OutputDataType;
// The multi-tensor ready storage
outputProbabilityBuffers = new HashMap<>();

ByteBuffer x;
// For each model's tensors (there are getOutputTensorCount() of the for this tflite model)
for (int i = 0; i < tflite.getOutputTensorCount(); i++) {
    OutputShape = tflite.getOutputTensor(i).shape();
    OutputDataType = tflite.getOutputTensor(i).dataType();
    x = TensorBuffer.createFixedSize(OutputShape, OutputDataType).getBuffer();
    outputProbabilityBuffers.put(i, x);
    LOGGER.d("Created a buffer of %d bytes for tensor %d.", x.limit(), i);
}
LOGGER.d("Created a tflite output of %d output tensors.", outputProbabilityBuffers.size());
```

https://stackoverflow.com/a/60368924/5441588

**Comment by stevelaclasse** [comment]
> Anyone run "multi_person_mobilenet_v1_075_float.tflite" successfully on Android or iOS?

https://github.com/tensorflow/tensorflow/issues/44821#issuecomment-1003115362
