### ISSUE TITLE
tf.test.gpu_device_name() allocated all GPU memory

### ISSUE THREAD

**Issue by asimonov** [tensorflow/tensorflow#25848]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
no 

- TensorFlow installed from (source or binary):
binary

- TensorFlow version (use command below):
1.4.1

- Python version:
3.6

- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):

- CUDA/cuDNN version:
8.0

- GPU model and memory:
1050Ti / 4Gb

**Describe the current behavior**
My code was 'checking for GPU' by calling tf.test.gpu_device_name()
Then it would go to set GPUoptions to allow_growth.
It caused tf to allocate full GPU memory for the process.
If I remove tf.test.gpu_device_name() then allow_growth works as expected.

**Describe the expected behavior**
tf.test.gpu_device_name() to NOT allocate GPU memory. Only starting a session should.

**Code to reproduce the issue**
-

**Other info / logs**
-

**Comment by ymodak** [comment]
In order to expedite the trouble shooting process can you please provide minimal code snippet to validate the issue reported here. Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
