### ISSUE TITLE
Why tf.image.decode_jpeg is slower than cv2.imread ?

### ISSUE THREAD

**Issue by FangxiangFeng** [tensorflow/tensorflow#2584]

**Comment by aselle** [comment]
Could you quantify how much slower tensor flow's read is vs opencv's?  They are both using libjpeg, so it seems like they should be close.

**Comment by FangxiangFeng** [comment]
@aselle Thanks for your reply. I just use the following code to test the speed of tf.image.decode_jpeg. It takes about 10ms + for one image.  However, cv2.imread only takes 1ms.  

def test_tf_image(path):
  with tf.device('/cpu:0'): 
    img = tf.read_file(path)
    image = tf.image.decode_jpeg(img, channels=3)
    
  with tf.Session() as sess:
    start = time.time()
    out = sess.run(image)
    print time.time() - start

**Comment by FangxiangFeng** [comment]
@aselle  Because of this, I can't find the solution to extract AlexNet fc7 features 1000 images per second. It's easy to make it in Caffe. Can you give me some suggestions?

**Comment by aselle** [comment]
If you built tensorflow yourself make sure you used "-c opt" on the bazel command line to compile in optimized mode.

**Comment by girving** [comment]
@FangxiangFeng: Can you check whether the slowness is the `tf.read_file` bit or the `tf.image.decode_jpeg` bit?  As Andy said, I don't know why our call into libjpeg would be slower than opencv's.

**Comment by FangxiangFeng** [comment]
@aselle I have tried both the released  v0.8 package and tensorflow built by myself. They produced the same result.  
@girving tf.read_file takes about 5ms.

**Comment by girving** [comment]
You may be timing initialization cost, not just the actual operations.  When you call `sess.run` the first time it does some setup work.  What do you get for

    def test_tf_image(path):
      with tf.device('/cpu:0'): 
        img = tf.read_file(path)
        image = tf.image.decode_jpeg(img, channels=3)

      with tf.Session() as sess:
        start = time.time()
        for i in xrange(1000):
          out = sess.run(image)
        print time.time() - start

**Comment by FangxiangFeng** [comment]
@girving Thanks.  I will close this issue.

**Comment by girving** [comment]
@FangxiangFeng: Does that mean the timings with 1000 iterations looked different?  If so, what were they?

**Comment by FangxiangFeng** [comment]
@girving. Yes, your code takes about 100ms to process 1000 images.

**Comment by Complovr** [comment]
@lin65505578 that could be from the way tensorflow decodes the images. try the decode_jpeg method with dct_method='INTEGER_ACCURATE' argument
