### ISSUE TITLE
Add lower() to string operations

### ISSUE THREAD

**Issue by arwengriffioen** [tensorflow/tensorflow#25857]
**System information**
- TensorFlow version (you are using):  1.10 and 1.12
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Add the string `lower()` function to the tf.string class.
Current state has no way to lower case input strings. This requires it to be done at dataset build time which reduces dataset flexibility

**Will this change the current api? How?**
Would add extra functionality

**Who will benefit with this feature?**
All users doing natural language processing

**Any Other info.**

**Comment by yongtang** [comment]
Added a PR #25859 with `strings.lower()` and `strings.upper()`.
