### ISSUE TITLE
freeze_graph unable to initialize local_variables

### ISSUE THREAD

**Issue by jtressle** [tensorflow/tensorflow#25856]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

Yes, I discovered this bug when running custom code.  However, I am attaching an example that illustrates the issue.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Version 10.14.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Tensorflow-cpu installed via PIP
- TensorFlow version (use command below): 1.12
- Python version: 1.12
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

When freezing a graph with a local variable, freeze_graph has an error stating "Attempting to use uninitialized value...".  The local variable in question was initialized via:

```
	with tf.variable_scope(tf.get_variable_scope(),reuse=tf.AUTO_REUSE):
		b_init = tf.constant(10.0, shape=[2, 1], dtype="float32",name = 'bi')
		b = tf.get_variable('b',initializer=b_init,collections=[tf.GraphKeys.LOCAL_VARIABLES])
```

I'm able to create a saved model and run the saved model.  However, I'm trying to freeze another graph for optimization.  This error will go away if I remove the 'LOCAL_VARIABLES' flag.  However, this variable then becomes global, which causes an issue with reloading my checkpoint (Tensorflow is unable to find the variable in the checkpoint).

**Describe the expected behavior**

I'd expect freeze_graph to initialize 'b' using 'b_init'.

**Code to reproduce the issue**

```
import os, sys, json
import tensorflow as tf
from tensorflow.python.lib.io import file_io

from tensorflow.core.framework import variable_pb2
from tensorflow.python.framework import ops
from tensorflow.python.ops import variables
from tensorflow.python.framework.ops import register_proto_function

from tensorflow.python.saved_model import tag_constants
from tensorflow.python.tools import freeze_graph
from tensorflow.python import ops
from tensorflow.tools.graph_transforms import TransformGraph

#flags
tf.app.flags.DEFINE_integer('model_version',1,'Models version number.')
tf.app.flags.DEFINE_string('export_model_dir','../model_batch/versions', 'Directory where model will be exported to')

FLAGS = tf.app.flags.FLAGS

def main(_):
	''' main function'''
	a = tf.placeholder(dtype = tf.float32, shape = [2,1])

	with tf.variable_scope(tf.get_variable_scope(),reuse=tf.AUTO_REUSE):
		b_init = tf.constant(10.0, shape=[2, 1], dtype="float32",name = 'bi')
		b = tf.get_variable('b',initializer=b_init,collections=[tf.GraphKeys.LOCAL_VARIABLES])

	b = tf.assign(b,a)
	c = []

	for d in range(5):
		b = b * 1.1

	c.append(b)
	c = tf.identity(c,name = 'c')

	init = tf.group(tf.global_variables_initializer(),
                   tf.local_variables_initializer())

	with tf.Session() as sess:

		#init
		sess.run(init)
		print(tf.get_default_graph().get_collection(tf.GraphKeys.LOCAL_VARIABLES))

		#create saved model builder class
		export_path_base = FLAGS.export_model_dir
		export_path = os.path.join(
			tf.compat.as_bytes(export_path_base),
			tf.compat.as_bytes(str(FLAGS.model_version)))

		if tf.gfile.Exists(export_path):
			print ('Removing previous artifacts')
			tf.gfile.DeleteRecursively(export_path)

		#inputs
		tensor_info_a  = tf.saved_model.utils.build_tensor_info(a)

		#outputs
		tensor_info_c = tf.saved_model.utils.build_tensor_info(c)

		print('Exporting trained model to', export_path)
		builder = tf.saved_model.builder.SavedModelBuilder(export_path)

		#define signatures
		prediction_signature = (
			tf.saved_model.signature_def_utils.build_signature_def(
				inputs={'cameras': tensor_info_a},
				outputs = {'depthmap' : tensor_info_c},
				method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME))

		builder.add_meta_graph_and_variables(
			sess, [tf.saved_model.tag_constants.SERVING],
			signature_def_map = {'predict_batch': prediction_signature})

		#export model
		builder.save(as_text=True)

		writer = tf.summary.FileWriter("output_batch", sess.graph)
		writer.close()

	#load graph from saved model
	print ('Freezing graph')
	initializer_nodes = ''
	output_node_names = 'c'
	saved_model_dir = os.path.join(FLAGS.export_model_dir,str(FLAGS.model_version))
	output_graph_filename = os.path.join(saved_model_dir,'frozen_graph.pb')

	freeze_graph.freeze_graph(
		input_saved_model_dir=saved_model_dir,
		output_graph=output_graph_filename,
		saved_model_tags = tag_constants.SERVING,
		output_node_names=output_node_names,
		initializer_nodes=initializer_nodes,
		input_graph=None,
		input_saver=False,
		input_binary=False,
		input_checkpoint=None,
		restore_op_name=None,
		filename_tensor_name=None,
		clear_devices=False)

if __name__ == '__main__':
	tf.app.run()
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jtressle** [comment]
I wasn't able to include local_variables in my frozen graph, but I did come up with a work around.

The initial problem was that my checkpoint was created from a graph that contained local_variables.  Unfortunately, freezing the graph produced the error:

`Attempting to use uninitialized value...`

What I did to work-around the issue was to change the local variables to untrainable global variables.  I then filtered out the global variables not in my checkpoint using the following solution:

[https://stackoverflow.com/a/39142780/6693924](https://stackoverflow.com/a/39142780/6693924)

I'm able to create a savedModel and freeze its graph.

Regarding the issue above, the problem is not unique to local variables.  I experienced the same issue when adding variable 'b' to any collection group other than 'global'.

**Comment by ymodak** [comment]
@jtressle Can we close this issue now, since you have found a workaround?

**Comment by eddienewton** [comment]
@ymodak yes we should be able to close it.  Thanks for circling back.

One suggestion could be to add a note to either https://www.tensorflow.org/guide/variables or https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py mentioning only global variables can be saved in a frozen graph?   

Thoughts?

**Comment by jtressle** [comment]
@ymodak yes we should be able to close it. Thanks for circling back.

One suggestion: can we add a note to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py mentioning only global variables can be saved in a frozen graph?

Thanks!

**Comment by ymodak** [comment]
Great. Thanks for the suggestion. @allenlavoie
