### ISSUE TITLE
Can't detected GPU using pycharm CUDA_ERROR_NO_DEVICE

### ISSUE THREAD

**Issue by MattHuntebrinker** [tensorflow/tensorflow#25862]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version: 1.12.0
- Python version:3.6.8
- Installed using virtualenv? pip? conda?:pip
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 9.0   7.4.2
- GPU model and memory: GeForce GTX 1070 8gb

When running on command line, it seems my graphics card can be detected, but when running in pycharm, i'm getting failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

![image](https://user-images.githubusercontent.com/35086049/52987994-242bcb80-33c3-11e9-9f5d-6c791f7525f4.png)

![image](https://user-images.githubusercontent.com/35086049/52988006-3443ab00-33c3-11e9-8327-aa1db2145a85.png)

![image](https://user-images.githubusercontent.com/35086049/52988031-56d5c400-33c3-11e9-87b8-31df048c4bcd.png)

I've searched the internet and can't find a solution. Thanks for helping!

**Comment by ymodak** [comment]
Can you try setting cuda,cupti, cudnn paths to your environment variables in PyCharm?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ColleenKuang** [comment]
I have the same problem too...
My system information:
* OS Platform and Distribution: Windows 10
* Pytorch version: 1.0.1
* Python version:3.6.5
* Installed using virtualenv? pip? conda?:pip
* CUDA/cuDNN version: 9.0 7.4.2
* GPU model and memory: GeForce RTX 2070 8gb and GeForce GTX 1050 8gb
Here's the result in the terminal 
![](https://user-images.githubusercontent.com/13173313/56232298-03c27980-60b3-11e9-846e-b47396067e74.png)
And the result from Pycharm with the same code:
![](https://user-images.githubusercontent.com/13173313/56232603-c14d6c80-60b3-11e9-8d50-7df50a6a87c3.png)
In Pycharm, it can only detect 1 GPU(the GeForce GTX 1050)
