### ISSUE TITLE
When the TF 2.0 stable edition releases ？

### ISSUE THREAD

**Issue by BigBigWolf-AI** [tensorflow/tensorflow#25883]
I really want to know！ Anyone could tell me？ Thank You！

**Comment by jvishnuvardhan** [comment]
@BigBigWolf-AI Team is working very hard on TF2.0. As of now, release date is not announced yet. 

I am closing the issue as it is not related to build/install or bug/performance. Thanks!

**Comment by BigBigWolf-AI** [comment]
OK! I have known that! Thanks!
