### ISSUE TITLE
Migration Guide from Tensorflow Android to Tensorflow Lite

### ISSUE THREAD

**Issue by karloberas** [tensorflow/tensorflow#25880]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): Tensorflow Android 1.12.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
I'm currently using a custom frozen model in .pb format for real-time face detection with Tensorflow Android. Everything is working fine except that the model is quite heavy and my app stops working from time to time. Logcat shows that the ActivityManager force closes my app, which I think is because it is using too many resources despite running in a different thread. Tensorflow Lite seems to be a good solution with continuous support and better performance. I want to migrate my existing solution to TFLite but I can't find any clear documentation on how to do so. The TensorFlowInferenceInterface methods and parameters are very different from Interpreter in TFLite. 

I followed the TFLiteObjectDetectionAPIModel samples for both Tensorflow Android and TFLite but I can't follow on the differences as someone who is not familiar with Tensorflow. Please provide documentation on how to migrate especially when you are deprecating Tensorflow Android already.

**Will this change the current api? How?**
I think no if there is proper documentation.

**Who will benefit with this feature?**
Developers currently using Tensorflow Android with performance issues

**Any Other info.**
None

**Comment by Ayush517** [comment]
@karloberas Are these the documents you were looking for?
https://www.tensorflow.org/lite/convert
https://www.tensorflow.org/lite/convert/cmdline_examples

**Comment by buaadf** [comment]
Is there any tflite demo on Android using C++ API rather than Java API? I got different result and inference time with tflite-nightly `implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'` after I rebuild my project

**Comment by jdduke** [comment]
Can you be more specific about the result/inference differences you're observing using the Java APIs? One thing to note is that using multi-dimensional Java arrays can yield surprisingly poor performance results, which is why we recommend using flat ByteBuffer input/output types.

**Comment by Macilias** [comment]
I just converted our internal project by following the changes on the examples, and the migration is still failing because of either one of the issues:
1. `Cannot convert between a TensorFlowLite buffer with 30420 bytes and a ByteBuffer with 2076672 bytes.`
2. `Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/pad.cc:74 SizeOfDimension(op_context->paddings, 0) != op_context->dims (4 != 1)Node number 0 (PAD) failed to prepare.`

is there any clear documentation of differences between android and lite and its migration?

**Comment by jdduke** [comment]
If you need to resize the input tensor, you should first call Interpreter.resizeInputTensor(`inputIndex`, `newShape`). Otherwise, when you feed the interpreter a flat ByteBuffer, it will try to fit that buffer into the existing tensor's buffer.

What shape did you use during conversion? And what shape are you using for your input data?

**Comment by Macilias** [comment]
Good point @jdduke. We have been feeding in a long float array with only one dimension (since it worked that way with tensorflow android) but the expected shape should be different.
We figured we can obtain the current output shape that way:
``` 
int[] shape = recognizer.tfLite.getOutputTensor(0).shape();
float[][][][]  tfOutput = new float[shape[0]][shape[1]][shape[2]][shape[3]];
``` 

now it works :)

**Comment by Macilias** [comment]
Now - where its running with unquantized model, we try to switch to quantized and are facing the old issue: 
```  
java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 2076672 bytes and a ByteBuffer with 519168 bytes.
```
We are not using `runForMultipleInputsOutputs` but could this be an issue here?
PS. 
We switch numBytesPerChannel accordingly and still the obtained source from the tensor looks the same after loading the quantized model.

Thanks for any advice.

**Comment by rmothukuru** [comment]
@karloberas,
Can you please refer to [TF Lite Android Guide](https://www.tensorflow.org/lite/guide/android) and let us know if it helps? Also, please refer to [TF Lite Guide](https://www.tensorflow.org/lite/guide) for more detailed documentation on different aspects of `TF Lite`. Thanks!
