### ISSUE TITLE
Rename atrous_conv2d to dilated_conv2d?

### ISSUE THREAD

**Issue by ry** [tensorflow/tensorflow#2588]
The name comes from French "à trous" so it seems there should be an extra underscore in there at least... but this is still unintelligible to non-french speakers. Better would be to use the English word 'dilated'.

**Comment by vrv** [comment]
Seems reasonable to add another alias so that dialated_conv2d == atrous_conv2d.  You can add the alias into nn_ops.py like we do for other kinds of renames here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_ops.py#L1212

**Comment by ry** [comment]
May I make dialated_conv2d the default name (particularly in the documentation) and leave atrous_conv2d as the alias?

**Comment by vrv** [comment]
@gpapan what do you think?

**Comment by tobin** [comment]
Surprisingly, the correct spelling seems to be "dilated".

**Comment by ry** [comment]
@tobin oops, thanks

**Comment by gpapan** [comment]
@ry I prefer atrous_conv2d.

I will reserve the name dilation for the morphological operation https://en.wikipedia.org/wiki/Dilation_(morphology) which will be added very soon to TF.

We used the term "atrous convolution" in the CVPR 2015 paper:
http://www.cv-foundation.org/openaccess/content_cvpr_2015/html/Papandreou_Modeling_Local_and_2015_CVPR_paper.html
before the term "dilated convolution" was proposed in https://arxiv.org/abs/1511.07122.

**Comment by ry** [comment]
ok
