### ISSUE TITLE
TensorBoard: Add select all or none in side panel

### ISSUE THREAD

**Issue by skearnes** [tensorflow/tensorflow#259]
It would be helpful if TensorBoard supported selecting all or none of the models listed in the side panel. I often work in a directory with many models but only want to look at a few of them and end up unchecking a lot of boxes.

**Comment by danmane** [comment]
There's now a toggle all runs button in the runs pane [example](https://www.tensorflow.org/tensorboard/cifar.html#events)

**Comment by Ademord** [comment]
@decentralion your photo is no longer available and the button is nowhere to be found.

**Comment by Ademord** [comment]
update for everyone else who didnt see it after 3 years of it fading into the background
![image](https://user-images.githubusercontent.com/4501464/150681902-e6a54b10-33f2-44ad-ab69-f9ca05202a16.png)
