### ISSUE TITLE
Batch Normalization renorm with tensorflow_hub

### ISSUE THREAD

**Issue by amirmazaheri1990** [tensorflow/tensorflow#25901]
Hi,

I have observed an issue in Tensorflow hub and batch normalization. It seems that I cannot have a batch normalization layer with renorm in a module. Consider the following short script:
```
import tensorflow as tf
import tensorflow_hub as hub



def myfunc():
    input = tf.placeholder(tf.float32, [5, 10])
    output = tf.layers.batch_normalization(input, renorm = True)

    outputs = dict(default=output)
    inputs = dict(input_txt=input)
    hub.add_signature(inputs=inputs, outputs=outputs)

g_spec = hub.create_module_spec(myfunc)
```
which gives me the following error:

> Traceback (most recent call last):
  File "..../codes/5/test.py", line 16, in <module>
    g_spec = hub.create_module_spec(myfunc)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_hub/native_module.py", line 189, in create_module_spec
    if err: raise ValueError(err)
ValueError: A state-holding node x of a module's graph (e.g., a Variable op) must not be subject to a tf.colocate_with(y) constraint unless y is also a state-holding node.
Details: node 'batch_normalization/renorm_mean_weight' has op 'VarHandleOp', which counts as state-holding, but Operation.colocation_groups() == [b'loc:@batch_normalization/Read/ReadVariableOp']. 

The problem does NOT exist with ```renorm=False```.

Is there anything that I am missing? I have not found similar problem on Stackoverflow.

**Comment by ymodak** [comment]
Thanks for your interest in using TensorFlow Hub. I think these issue can be better addressed in TensorFlow Hub repo. Please post it in TF Hub repo from [here](https://github.com/tensorflow/hub/issues). Thanks!
