### ISSUE TITLE
tflite_convert - ValueError: Invalid tensors 'input' were found.

### ISSUE THREAD

**Issue by AliceDinh** [tensorflow/tensorflow#25922]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (use command below): 1.12
- Python version: 3.6.7
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: No
- GPU model and memory: No

**Describe the current behavior**
I want to convert mobilenet_v1_0.50_128 frozen graph using tflite_convert or toco to a TensorFlow Lite model, but I get the following error:
```
2019-02-20 16:09:37.352780: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "c:\users\alice\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

  File "c:\users\alice\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)

  File "C:\Users\Alice\Anaconda3\Scripts\tflite_convert.exe\__main__.py", line 9, in <module>

  File "c:\users\alice\anaconda3\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 442, in main
    app.run(main=run_main, argv=sys.argv[:1])

  File "c:\users\alice\anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)

  File "c:\users\alice\anaconda3\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)

  File "c:\users\alice\anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))

  File "c:\users\alice\anaconda3\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 438, in run_main
    _convert_model(tflite_flags)

  File "c:\users\alice\anaconda3\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 122, in _convert_model
    converter = _get_toco_converter(flags)

  File "c:\users\alice\anaconda3\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 109, in _get_toco_converter
    return converter_fn(**converter_kwargs)

  File "c:\users\alice\anaconda3\lib\site-packages\tensorflow\lite\python\lite.py", line 387, in from_frozen_graph
    sess.graph, input_arrays)

  File "c:\users\alice\anaconda3\lib\site-packages\tensorflow\lite\python\convert_saved_model.py", line 189, in get_tensors_from_tensor_names
    ",".join(invalid_tensors)))

ValueError: Invalid tensors 'input' were found.
```

**Code to reproduce the issue**
I run the following command:
`tflite_convert --output_file=tflite_convert --output_file=F:/mobilenet_v1_0.50_128/frozen_graph.tflite --graph_def_file=F:/mobilenet_v1_0.50_128/frozen_graph.pb --input_arrays=input --output_arrays=MobilenetV1/Predictions/Reshape_1`

**Comment by yangchengtest** [comment]
I have the same problem in window10.

**Comment by AliceDinh** [comment]
I don't know what happened but this morning the `mobilenet_v1_0.50_128/frozen_graph.pb` is converted successfully by `tflite_convert`:
![image](https://user-images.githubusercontent.com/20389638/53139285-be566400-35bb-11e9-9c27-e2f4536e1de0.png)
But if I change to my trained model, the mentioned error appear. Anyone please tell me about the `--output_arrays=MobilenetV1/Predictions/Reshape_1`, if I change to my trained model (SSD-FPN Mobilenet V1), what output arrays of mine?

**Comment by jyotirmayghosh** [comment]
I have the same problem when I am trying to convert frozen_face_grapy.pb file to .tflite file.

But if you try with the code in [document](https://www.tensorflow.org/lite/convert/python_api) with files provided by them, it is converting properly.

Can anyone tell me, what is this input_tensor? And what is the expected value?

**Comment by AmitPrajapati1902** [comment]
Hello,

I'm facing same problem here

Here is the command that i'm executing to generate .pb i am successfuly generate it.

IMAGE_SIZE=224
ARCHITECTURE="mobilenet_1_1.0_${IMAGE_SIZE}"

python retrain.py  
 --bottleneck_dir=tf_files/bottlenecks   
 --how_many_training_steps=500   
 --model_dir=tf_files/models/   
 --summaries_dir=tf_files/training_summaries/"${ARCHITECTURE}"  
  --output_graph=tf_files/retrained_graph.pb   
  --output_labels=tf_files/retrained_labels.txt   
  --architecture="${ARCHITECTURE}"  
  --image_dir=tf_files/flower_photos

Once i am trying to create that .pb to .tflite get fail with same error "ValueError: Invalid tensors 'input' were found."

tflite_convert \
  --output_file=foo.tflite \
  --graph_def_file=retrained_graph.pb \
  --input_arrays=input \
  --output_arrays=MobilenetV1/Predictions/Reshape_1

**Comment by cedricve** [comment]
same issue, any ideas?

**Comment by vijay1131** [comment]
Same issue here as well

**Comment by likhilkt** [comment]
any solution for this ?

**Comment by likhilkt** [comment]
not sure if this approach is right. im using mobilnetv2
i tried printing available values from convert_saved_model.py
print(tensor_name_to_tensor) -  this will give all the valid values. 
i used  --input_arrays=module_apply_default/MobilenetV2/input (which is available in print)
this is working for me. converted model tested in android device.

**Comment by PrakharPrashantSingh** [comment]
Same error i am also facing.... any solution?

**Comment by AmitPrajapati1902** [comment]
Hello guys, please follow this stackoverflow url it may help you for it, i just use older one poets demo and its working fine with latest mobilenet version.

**Comment by Davari393** [comment]
> Hello,
> 
> I'm facing same problem here
> 
> Here is the command that i'm executing to generate .pb i am successfully generate it.
> 
> ```
> IMAGE_SIZE=224
> ARCHITECTURE="mobilenet_1_1.0_${IMAGE_SIZE}"
> 
> python retrain.py  
>  --bottleneck_dir=tf_files/bottlenecks   
>  --how_many_training_steps=500   
>  --model_dir=tf_files/models/   
>  --summaries_dir=tf_files/training_summaries/"${ARCHITECTURE}"  
>   --output_graph=tf_files/retrained_graph.pb   
>   --output_labels=tf_files/retrained_labels.txt   
>   --architecture="${ARCHITECTURE}"  
>   --image_dir=tf_files/flower_photos
> ```
> 
> Once i am trying to create that .pb to .tflite get fail with same error "ValueError: Invalid tensors 'input' were found."
> 
> ```
> tflite_convert \
>   --output_file=foo.tflite \
>   --graph_def_file=retrained_graph.pb \
>   --input_arrays=input \
>   --output_arrays=MobilenetV1/Predictions/Reshape_1
> ```

i want to know what is input array actually?what should i put there?

**Comment by gargn** [comment]
Try loading your model into TensorBoard to try and visualize what the input array might be. In general, it's the Placeholders that are being passed into the graph at the start.

It is not possible to debug this issue without investigating the specific model. If you are unable to determine the input arrays, please provide a TensorFlow model file.

**Comment by gargn** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by 774219268** [comment]
遇到ValueError: Invalid tensors 'input/input_data:0' were found.
同样问题，请问有谁解决了吗？帮我， 'input/input_data:0' 是我测试pb模型是的输入变量名，但是转tflite时，报上述错误。谢谢。。。

**Comment by theAB316** [comment]
> 遇到ValueError: Invalid tensors 'input/input_data:0' were found.
> 同样问题，请问有谁解决了吗？帮我， 'input/input_data:0' 是我测试pb模型是的输入变量名，但是转tflite时，报上述错误。谢谢。。。

Hi, 
I had the same issue. Don't pass the port ':0' in your input array. 
Try just 'input/input_data'. 

Should work.

**Comment by A5mad** [comment]
I had the same issue when I tried to convert my trained model that used the inception_v3 model. There are the parameters that finally worked for me when I tried converting using tflite_convert:

`–graph_def_file=myfile.pb –output_file=output.tflite –input_format=TENSORFLOW_GRAPHDEF –output_format=TFLITE –-input_shape=1,299,299,3 —input_array=ResizeBilinear –output_array=final_result –inference_type=FLOAT –input_type=FLOAT`
