### ISSUE TITLE
tensorflow Module object has no attribute keras.

### ISSUE THREAD

**Issue by ujur007** [tensorflow/tensorflow#25933]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Pip install...
- TensorFlow version: latest
- Python version: python 2.12.15
- Installed using virtualen? pip? conda?:pip/virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Cuda 9.2
- GPU model and memory: NVIDIA MX150

**Describe the problem**
I have tried to install tensorflow with gpu support both with pip and virualenv several times, I have got following erros. anyone has idea?

> `python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow.py", line 2, in <module>
    mnist = tf.keras.datasets.mnist
AttributeError: 'module' object has no attribute 'keras'`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
I suspect its a due to lower tf version.  What's your tf version? Can you try updating tf
```pip install -U tensorflow```

**Comment by ujjwalrathod007** [comment]
Hi, I have 1.12.0

Is there any requirement for CUDA version?

`Name: tensorflow
Version: 1.12.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /.local/lib/python3.6/site-packages
Requires: tensorboard, protobuf, keras-applications, wheel, astor, absl-py, termcolor, grpcio, numpy, six, gast, keras-preprocessing
Required-by: 
`

**Comment by ujjwalrathod007** [comment]
I think there was some CUDA toolkit problem, it worked after following 

[https://medium.com/@taylordenouden/installing-tensorflow-gpu-on-ubuntu-18-04-89a142325138](url)

**Comment by ymodak** [comment]
Yes, if you are using TF 1.12 gpu version then you have to install cuda 9.0. I will close this issue since you have found the solution. Thanks!
