### ISSUE TITLE
error import tensorflow

### ISSUE THREAD

**Issue by quartermaine** [tensorflow/tensorflow#25937]
System information
OS Platform: Windows 10 x64
TensorFlow installed from: pip install tensorflow-gpu
Python version: 3.5.3
CUDA/cuDNN version: CUDA10.0 / cuDNN v7.4.2
GPU model and memory: GTX 1060
Exact command to reproduce: import tensorflow
Describe the problem
It is impossible to import tensorflow in my present environment.I am getting the following error.
---------------------------------------------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

~\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~\Anaconda2\envs\python3\lib\imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

~\Anaconda2\envs\python3\lib\imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: DLL load failed: Δεν ήταν δυνατό να εντοπιστεί η καθορισμένη λειτ. μονάδα.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-2-566d4aa4fae9> in <module>
      1 
----> 2 import tensorflow

~\Anaconda2\envs\python3\lib\site-packages\tensorflow\__init__.py in <module>
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 try:

~\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\__init__.py in <module>
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 from tensorflow.python.tools import component_api_helper

~\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Δεν ήταν δυνατό να εντοπιστεί η καθορισμένη λειτ. μονάδα.

**Comment by jvishnuvardhan** [comment]
@quartermaine Could you follow more detailed instructions [here](https://www.tensorflow.org/install/pip) and let me know how it progresses. Thanks!

**Comment by quartermaine** [comment]
@jvishnuvardhan I follow the instructions that you mention and the resources given but still no success.

**Comment by quartermaine** [comment]
@jvishnuvardhan I follow the instructions that you mention and the resources given but still no success.

**Comment by jvishnuvardhan** [comment]
@quartermaine Could you uninstall tensorflow and python completely and please follow the instructions [here](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12). Please let me know how it progresses. Thanks!

**Comment by quartermaine** [comment]
Yes,I finally manage to make the installation everything works.Thank you for the detailed guide

**Comment by jvishnuvardhan** [comment]
@quartermaine Good to know it worked. I am closing this issue. Thanks again!
