### ISSUE TITLE
Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [tensorflow/tensorflow#25935]
Tensorflow doesn't build with Bazel incompatible flags.
Based on our CI (https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags/builds/95), the following flags will fail:

* `--incompatible_new_actions_api`
* `--incompatible_no_support_tools_in_action_inputs`
* `--incompatible_no_transitive_loads`
* `--incompatible_disable_deprecated_attr_params`
* `--incompatible_disallow_load_labels_to_cross_package_boundaries`

From what I've seen, updating the dependency on rules_closure will fix some of the problems.

For `--incompatible_no_transitive_loads`, the simplest is to reexport some symbols explicitly (see https://github.com/bazelbuild/bazel/issues/5636).

If you run `buildifier --lint=fix tensorflow/tensorflow.bzl`, it will also fix some issues.

Let me know if you need help
(bug also filed inside Google: b/124051098)

**Comment by AliceDinh** [comment]
I got error when converting tfmodel (.pb) to tflite (.lite): Unable to load package for '//tensorflow/tools/def_file_filter:def_file_filter_configure.bzl': BUILD file not found on package path
Is that because of incompatibility?

**Comment by brandjon** [comment]
Add `--incompatible_remove_old_python_version_api` to that list. I'm flipping this flag to true now, for release in Bazel 0.25. The fix #26752 will bump TF's min required Bazel version to 0.22.

**Comment by gunan** [comment]
I am sorry for dropping this issue.
I saw that Yun has done many of these changes.

**Comment by gunan** [comment]
I am sorry to forget. I think this is complete. We even were able to build TF with bazel 3.0 now.
