### ISSUE TITLE
numpy.dtype size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by prhbrt** [tensorflow/tensorflow#25934]
## Cleanest reproduction:

Run in a GPU Google Colaboratory session:

    !pip3 install tensorflow-gpu==1.13.0rc2 numpy==1.15.0
    !python3.6 -c 'import tensorflow'

However, how I came across the issue:

**System information**
- Ubuntu 18.04
- Dell XPS 15 2016 laptop
- installed a binary using pip3 install tensorflow-gpu==1.13.0rc2
- TensorFlow version: 1.13.0rc2
- Python 3.6.5
- virtualenv with python3.6 and pip3
- N/A did not installed from source
- N/A did not compiled from source
- cuda 10.0 / libcudnn7_7.4.2.24-1+cuda10.0_amd64.deb
- GPU model and memory:

    NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0
    GeForce GTX 960M
    91MiB /  2004MiB

## Problem:

Warning when importing tensorflow, only when numpy version is 1.15.0

    /home/herbert/.virtualenvs/actigraph/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      return f(*args, **kwds)
    /home/herbert/.virtualenvs/actigraph/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      return f(*args, **kwds)

## Commands to reproduce:

    pip3 install tensorflow-gpu==1.13.0rc2 numpy==1.15.0
    python3.6 -c 'import tensorflow'

## Commands to fix:

    pip3 install tensorflow-gpu==1.13.0rc2 numpy==1.16.1
    python3.6 -c 'import tensorflow'

Or probably, leave the version of numpy out (`==1.16.1`) and include `-U` to upgrade to the newest numpy.

    pip3 install -U tensorflow-gpu==1.13.0rc2 numpy
    python3.6 -c 'import tensorflow'

**Comment by prinsherbert** [comment]
If wondering, I installed `tensorflow-gpu==1.13.0rc2` because I upgraded to cuda 10.0 from cuda 9.0 and didn't want to go through the hassle of downgrading cuda for compatibility with a stable tf, due to the risk of messing up the nvidia-drivers and killing my desktop environment.

Therefore I figured using a `rc2` tf is less troublesome, expecting the stable tf `1.13` to arrive soon.

**Comment by facaiy** [comment]
duplication of #21225

As @feranick said:
> The problem is in numpy itself. This will be fixed in numpy v. 1.15.1
> [numpy/numpy#11628](https://github.com/numpy/numpy/issues/11628)

**Comment by facaiy** [comment]
@av8ramit Hi, Amit, can we increase the minimum version of numpy to 1.15.1?  https://github.com/tensorflow/tensorflow/blob/9d508106b32eb6518912501d29a80ff9967dfe05/tensorflow/tools/pip_package/setup.py#L57

**Comment by prinsherbert** [comment]
> @av8ramit Hi, Amit, can we increase the minimum version of numpy to 1.15.1?

Yes, that was my point, these warnings and the potential side-effects should not appear after `pip install`ing tensorflow.

**Comment by prinsherbert** [comment]
> duplication of #21225

Sorry, I checked for all issues with dtype in the title, but missed this one

**Comment by av8ramit** [comment]
Thanks for pointing this out. @facaiy or @prinsherbert please create a PR and I'll approve it.

**Comment by prinsherbert** [comment]
I can't for at least the next two months, sorry

Op di 2 apr. 2019 20:00 schreef Amit Patankar <notifications@github.com>:

**Comment by mohantym** [comment]
We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.5  version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!
