### ISSUE TITLE
Measuring the prediction accuracy for the tensorflow-lite android version

### ISSUE THREAD

**Issue by spaul13** [tensorflow/tensorflow#25945]
I am using the tensorflow-lite version (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo). Can anyone please tell me how to compute the object detection accuracy or prediction accuracy while using this?

**Comment by jdduke** [comment]
This is a very general question, and better suited for posting on StackOverflow. Are you interesting in testing the runtime accuracy against novel images? Or against the original source training/validation data set? In any case, if you wouldn't mind posting on StackOverflow you'll get a more appropriate response.

**Comment by spaul13** [comment]
@jdduke, thanks for the reply and the suggestion. FYI, I want to get the runtime accuracy against novel images. AS I observed the detection time on the phone using the GPU is really fast (~30 ms) for floatMobileNet classifier but what I observed the accuracy is really bad. can the prediction probability be treated as runtime prediction accuracy? although the threshold value seems really less 0.3, mentioned in the code. Any suggestion on calculating runtime prediction accuracy will be highly helpful.

**Comment by jdduke** [comment]
The probability, while related to accuracy, is quite different.

If you're seeing dramatically different results between the GPU path and the CPU path, that could be a bug. If you could provide an image/screenshot of an example that is wrong on the GPU (and right on the CPU), that would help.

**Comment by spaul13** [comment]
@jdduke , for CPU and GPU the results are the same but predictions are mostly wrong. That's my concern.

**Comment by jdduke** [comment]
In general, the MobileNet classification models only make claims about the source data set (ImageNet), for which it achieves ~70% accuracy (see https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet). There are only 1000 labels in that set, so it's unsurprising that you're not seeing perfect accuracy across arbitrary images, but you should be getting close for common objects.
