### ISSUE TITLE
add tf.assert for GPU (maybe also host-memory Const[string] for GPU) was: dynamic_rnn GPU support error 

### ISSUE THREAD

**Issue by markpwoodward** [tensorflow/tensorflow#2594]
When attempting to place dynamic_rnn on the gpu, I get the following error:

```
tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'RNN/Assert/data_2': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available
         [[Node: RNN/Assert/data_2 = Const[dtype=DT_STRING, value=Tensor<type: string shape: [] values:  but saw shape: >, _device="/device:GPU:0"]()]]
```

Full traceback:

```
Traceback (most recent call last):
  File "test_model2_parallel_buffered.py", line 84, in <module>
    sess.run(init_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 333, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 573, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 648, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 668, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'RNN/Assert/data_2': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available
         [[Node: RNN/Assert/data_2 = Const[dtype=DT_STRING, value=Tensor<type: string shape: [] values:  but saw shape: >, _device="/device:GPU:0"]()]]
Caused by op u'RNN/Assert/data_2', defined at:
  File "test_model2_parallel_buffered.py", line 47, in <module>
    tower_logits_t = model.inference(frames_t, seq_length_t, BATCH_SIZE)
  File "/home/woodward/ml/football_plays/model2.py", line 73, in inference
    _, rnn_state_final_t = tf.nn.dynamic_rnn(rnn_cell, rnn_inputs_t, sequence_length=seq_length_t, initial_state=rnn_initial_state_t, swap_memory=True, time_major=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 567, in dynamic_rnn
    [_assert_has_shape(sequence_length, [batch_size])]):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 562, in _assert_has_shape
    packed_shape, " but saw shape: ", x_shape])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/logging_ops.py", line 58, in Assert
    return gen_logging_ops._assert(condition, data, summarize, name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 37, in _assert
    summarize=summarize, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 410, in apply_op
    as_ref=input_arg.is_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 664, in convert_n_to_tensor
    ret.append(convert_to_tensor(value, dtype=dtype, name=n, as_ref=as_ref))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 620, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 166, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1224, in __init__
    self._traceback = _extract_stack()
```

It seems to have some problem with a tensor shape, but I can't deduce why. This error does not occur if I enclose the tf.nn.dynamic_rnn(...) call in a tf.device('/cpu:0') statement. I am on commit 0050a205bc5521a563ee66baa3b73373d4c0e62e from mid last week.

I am doing data parallel processing and am trying to keep as much as possible on each GPU.

**Comment by mrry** [comment]
It looks like you might need `allow_soft_placement=True` in your Session configuration (`tf.Session(config=tf.ConfigProto(allow_soft_placement=True))`), but let's check with @ebrevdo to see if there's a more systematic solution.

**Comment by markpwoodward** [comment]
Thank you. I agree, as with explicitly placing the dynamic_rnn call on the cpu, the error does not occur when I include soft_placement in the config. But my goal is actually to put it on the gpu, if possible.

**Comment by girving** [comment]
@markpwoodward: If you do soft placement, it will put anything it can on the GPU and use the CPU for the rest, which is exactly what you want here (since assert is CPU only).

**Comment by ebrevdo** [comment]
`dynamic_rnn` runs some dynamic assertions on the input, making sure things are within bounds, etc.  the error you're seeing is the static assertion message (a string) trying to get allocated on the GPU.  Since we don't mix strings with GPUs, we lack a const string op mapped to the GPU.  That's the error you're seeing.  I think it's fine for error checking and error strings to sit on the CPU, but perhaps we should consider a Const[string] that is declared for GPU but stores data on the host?  Either way, you should be fine with soft placement here.  @girving  @mrry  think host-memory const string GPU op is a reasonable thing?

**Comment by girving** [comment]
@ebrevdo: We should avoid adding more lies about which things are on the CPU vs. GPU (too many of these related to int32 already).  In any case, the actual problem here is that `tf.assert` itself is CPU only.  Maybe the ideal fix is to add a GPU version of `tf.assert`, specifying HostMemory for the string argument?

**Comment by markpwoodward** [comment]
Thank you. This makes sense. I do understand the distinction between hard placement and soft placement.

Seeing that something in dynamic_rnn did not have a GPU implementation (requiring soft placement) made me hope that, if only there were a GPU implementation for that operation, then I would get a huge speedup. :) Of course, those operations might not have any impact on performance.

I should probably just look at the graph for dynamic_rnn and see what was placed on the CPU, rather than forcing dynamic_rnn onto the GPU and then posting a github issue when it complains. My apologies. Feel free to close this.

**Comment by girving** [comment]
@markpwoodward: No worries, thank you for the report!  We might close, but we might also rename it to "add tf.assert for gpu" in order to fix the other underlying issue.

**Comment by ebrevdo** [comment]
Thanks!

**Comment by ebrevdo** [comment]
@girving can you assign to appropriate folks?

**Comment by girving** [comment]
I'll leave it as contributions welcome for now.  Happy to accept PRs if someone wants to make a GPU version of `tf.assert`!

**Comment by xtknight** [comment]
I can't really quite understand the implications of this. Does this prevent LSTMs from being placed on the GPU?

I'm trying to do multi-GPU which requires explicit assignment of GPU devices, and suddenly when I start explicitly designing devices I start hitting this assert op that's apparently not supported on GPU. But I don't understand how it was running fine on a single GPU in the first place?

What I do know is that I commented out the assert, explicitly defined GPU devices and multi-GPU code is working very well now. But I am left with a lot of confusion as well.

**Comment by ebrevdo** [comment]
You need to enable soft placement when creating the session.  It's a
configuration o parameter in tf.ConfigProto.

**Comment by alextp** [comment]
Closing as soft placements solves the issue.
