### ISSUE TITLE
[TF 2.0 API Docs] tf.image.non_max_suppression

### ISSUE THREAD

**Issue by RajeshThallam** [tensorflow/tensorflow#25959]
### Existing URLs containing the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/image/non_max_suppression#aliases

### Description of issue (what needs changing):

* **Correct Links**
  https://github.com/tensorflow/tensorflow/blob/master/python/ops/image_ops_impl.py is incorrect. The correct link should be https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py.

* **Clear Description**
  The description is not opinionated about when to use this symbol and unclear how arguments effect the functionality.

* **Usage Example**
  Usage example is mixed into the description, not formatted and not self-contained

* **Parameters Defined**
  Parameters are defined correctly with expected formats.

* **Returns Defined**
  Returns are defined correctly with expected formats.

* **Raises Listed and Defined**
  Errors are not defined.

* **Visuals, if Applicable**
  No visuals are included.

**Comment by Ayush517** [comment]
@RajeshThallam The link on the url seems to be working with the correct link.

**Comment by scouvreur** [comment]
Hi @RajeshThallam @dynamicwebpaige - do you mind if I take this ?

**Comment by RajeshThallam** [comment]
@scouvreur , please go ahead.

**Comment by Ayush517** [comment]
> @scouvreur , please go ahead.

Maybe I don't understand the issue properly but the link seems to be working correctly. Am I missing something?

**Comment by RajeshThallam** [comment]
@Ayush517 , links were incorrect when the issue was reported. There was a commit that fixed the link. I think it may be the [doc generator](https://github.com/tensorflow/docs/blob/094df83829d17ba582c275772373bb1eee498713/tools/tensorflow_docs/api_generator/generate_lib.py)

**Comment by scouvreur** [comment]
Got it @Ayush517 @RajeshThallam - you can close this issue then

**Comment by pythogeeker** [comment]
I just checked the links and they seem to be working properly..

**Comment by RajeshThallam** [comment]
Closing the issue as docs are updated.
