### ISSUE TITLE
keras `Model.compile` with loss/metrics dict and multiple outputs from same layer

### ISSUE THREAD

**Issue by jackd** [tensorflow/tensorflow#25955]
## System information
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- Python version: ('v1.12.0-7354-gedbd8a15b9', '1.13.0-dev20190203') - also present in 2.0 preview
- CUDA/cuDNN version: 10.0 / 7
- GPU model and memory: quadro k620

## Current Behaviour
Keras' `model.compile` with dict losses matches provided loss functions with outputs passed into the constructor via each output's _layer name_. This is not unique in the case where multiple model outputs come from the same layer.

## Expected Behaviour
I would expect usages of lists/dicts to be consistent between losses, metrics, labels and outputs - i.e. if any are lists, they must all be lists of the same length, and if any are dicts they must all be dicts with the same set of keys. Requiring output layers to be named consistently with the key in the corresponding labels dictionary seems completely bamboozling to me, e.g. if building a hybrid model with a classification output and 'class_index' key in the labels one would have to name the final layer 'class_index' even if it outputs logits/softmax activations.

This is likely a breaking change. At the very least I would expect an error to be raised if `output_names` are not unique and users pass in dictionaries for either `loss` or `metrics` in `Model.fit`.

## Code to Reproduce
```python
import tensorflow as tf
# network that maps 1 input to 2 separate outputs
x = tf.keras.layers.Input(shape=(1,), dtype=tf.float32)
x2 = tf.keras.layers.Dense(2)(x)
y, z = tf.keras.layers.Lambda(
    lambda x2: tf.unstack(x2, axis=-1), name='x2_unstack')(x2)
# y = tf.keras.layers.Lambda(tf.identity, name='y')(y)
# z = tf.keras.layers.Lambda(tf.identity, name='z')(z)  # current work-around
model = tf.keras.models.Model(inputs=x, outputs=dict(y=y, z=z))

print(model.outputs)
# [
#  <tf.Tensor 'x2_unstack/unstack:0' shape=(None,) dtype=float32>,
# <tf.Tensor 'x2_unstack/unstack:1' shape=(None,) dtype=float32>
# ]
# somewhat unexpected as not the same as the value passed to constructor, but ok...
print(model.output_names)
# ['x2_unstack', 'x2_unstack']
# surely that's going to cause issues later...

model.compile('SGD', loss={'x': 'mse', 'y': 'logcosh'})
# ValueError: Unknown entry in loss dictionary: y.
# Only expected following keys: ['x2_unstack', 'x2_unstack']

model.fit(x=x_data, y=dict(y=y_data, z=z_data))  # expected way of using fit
```

**Comment by ymodak** [comment]
Is this still an issue with latest version TF 2.4? Thanks!

**Comment by jackd** [comment]
Looks all good now.
