### ISSUE TITLE
MKL Link error libiomp5md.lib library is corrupt

### ISSUE THREAD

**Issue by eloi-loomai** [tensorflow/tensorflow#25952]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.13.0rc1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.22
- GCC/Compiler version (if compiling from source): visual studio 17
- CUDA/cuDNN version: 7.4.2
- GPU model and memory: titan xp, 12GB ram

When I run ```bazel build --config=opt --config=mkl --linkopt="/FORCE:MULTIPLE" -k //tensorflow:libtensorflow.so```

I get this error at link time:
```
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/link.exe /nologo /DLL /SUBSYSTEM:CONSOLE -defaultlib:advapi32.lib -DEFAULTLIB:advapi32.lib -Wl,-rpath,../local_config_cuda/cuda/lib64 -Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64 /MACHINE:X64 /FORCE:MULTIPLE @bazel-out/x64_windows-opt/bin/tensorflow/libtensorflow.so-2.params
Execution platform: @bazel_tools//platforms:host_platform
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/lib64'; ignored
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64'; ignored
LINK : warning LNK4044: unrecognized option '/lpthread'; ignored
external\mkl_windows\lib\libiomp5md.lib : fatal error LNK1127: library is corrupt
```

Is there any workaround?

**Any other info / logs**
I have mkl 2019-update 2 installed and set in my PATH env.

**Comment by preethivenkatesh** [comment]
Hi, 
The mkl library on windows is currently experiencing several issues at the time of linking and a patch with a fix will be made available either this week or next week. Please try again when we have the new library released. Also, I see that your VS version is 2017 instead of 2015. Please ensure that the necessary installs are available as per the doc available here https://www.tensorflow.org/install/source_windows

**Comment by preethivenkatesh** [comment]
#25213

**Comment by preethivenkatesh** [comment]
@eloi-loomai The issue should be resolved now, please try the resolution provided in the above issue

**Comment by saudet** [comment]
@preethivenkatesh I'm also encountering this issue with more recent versions of Bazel (at least 0.25.3) and Visual Studio 2017. It looks like the trick that resolved issue #25213 doesn't work anymore. Bazel uses `/WHOLEARCHIVE` regardless.

**Comment by saudet** [comment]
I've found that launching with `bazel build --nolegacy_whole_archive ...` seems to do the trick though.

**Comment by saudet** [comment]
Actually, this was the same as issue #25213 after all. The patch wasn't getting applied properly. With it, Bazel doesn't use `/WHOLEARCHIVE` and no errors occur with Visual Studio 2017 either.

**Comment by TensorFlow-MKL** [comment]
closing as this issue is fixed
