### ISSUE TITLE
Cannot find cudnn.h under ~ but I really have it there !

### ISSUE THREAD

**Issue by nasica88** [tensorflow/tensorflow#25960]
**System information**
- OS Platform and Distribution : Redhat 7.5 ppc64le
- TensorFlow installed from source
- TensorFlow version: v1.12.0
- Python version: 3.6.5  (anaconda3 v5.2)
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source):  4.8.5
- CUDA/cuDNN version: 9.2/7.4.2
- GPU model and memory: V100 16GB

**Describe the problem**

I am trying to build tensorflow r1.12 using bazel 0.15 on Redhat 7.5 ppc64le.

I am stuck with the following error.

    [u0017649@sys-97184 tensorflow]$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 
    ...
    ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package 
    '@local_config_cuda//cuda': Traceback (most recent call last):
        File 
    "/home/u0017649/files/tensorflow/third_party/gpus/cuda_configure.bzl", line 1447
                _create_local_cuda_repository(repository_ctx)
        File 
    "/home/u0017649/files/tensorflow/third_party/gpus/cuda_configure.bzl", line 1187, in 
    _create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File 
    "/home/u0017649/files/tensorflow/third_party/gpus/cuda_configure.bzl", line 911, in _get_cuda_config
                _cudnn_version(repository_ctx, cudnn_install_base..., ...)
        File 
    "/home/u0017649/files/tensorflow/third_party/gpus/cuda_configure.bzl", line 582, in _cudnn_version
                _find_cudnn_header_dir(repository_ctx, cudnn_install_base...)
       File 
    "/home/u0017649/files/tensorflow/third_party/gpus/cuda_configure.bzl", line 869, in 
    _find_cudnn_header_dir
                auto_configure_fail(("Cannot find cudnn.h under %s" ...))
        File 
    "/home/u0017649/files/tensorflow/third_party/gpus/cuda_configure.bzl", line 317, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

    Cuda Configuration Error: Cannot find cudnn.h under /usr/local/cuda-9.2/targets/ppc64le-linux/lib

I do have a soft link for cudnn.h under /usr/local/cuda-9.2/targets/ppc64le-linux/lib as below.

    [u0017649@sys-97184 tensorflow]$ ls -l /usr/local/cuda-9.2/targets/ppc64le-linux/lib/cudnn.h
    lrwxrwxrwx. 1 root root 57 Feb 20 10:15 /usr/local/cuda-9.2/targets/ppc64le-linux/lib/cudnn.h -> /usr/local/cuda-9.2/targets/ppc64le-linux/include/cudnn.h

Any comments, pls ?

**Comment by nasica88** [comment]
After reading tensorflow/third_party/gpus/cuda_configure.bzl, I could solve this by the following.  

$ sudo ln -sf /usr/local/cuda-9.2/targets/ppc64le-linux/include/cudnn.h  /usr/include/cudnn.h

**Comment by ymodak** [comment]
Thanks for sharing the workaround. Closing this issue since its resolved. Thanks!
