### ISSUE TITLE
Is it mandatory to use same version of Tensorflow for TFLite conversion

### ISSUE THREAD

**Issue by vinayonchip** [tensorflow/tensorflow#25969]
**System information**
- OS Platform and Distribution : Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version:3.6.5
- Installed using virtualenv
- Bazel version (if compiling from source):0.21.0
- GCC/Compiler version (if compiling from source):5.4.0

**Problem description**
I have trained a custom model using Tensorflow 1.9 binary. Now I want to convert graph to tflite. Is it mandatory to use same  Tensorflow 1.9 for this conversion or can I use the latest version of TF ?

**Comment by srjoglekar246** [comment]
I don't think it should be an issue. As long as it contains supported ops, the model should convert just fine. Let us know if you have any issues!

**Comment by vinayonchip** [comment]
Hi @srjoglekar246. Thank you for your confirmation.
