### ISSUE TITLE
Udacity readme docker command should not remove container

### ISSUE THREAD

**Issue by BarneyL** [tensorflow/tensorflow#2596]
The Udacity readme at 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/README.md
suggests starting Docker like this:

`docker run -p 8888:8888 -it --rm b.gcr.io/tensorflow-udacity/assignments:0.5.0`

The `--rm` causes the container to get removed once you end the session, which deletes all your progress so far in the class. It would be better to not suggest `--rm` so that the docker container can then be resumed at a later time.

**Comment by vincentvanhoucke** [comment]
Fair enough. I'll take a PR if you'd like.

**Comment by siddharth-agrawal** [comment]
This issue should probably be closed.
