### ISSUE TITLE
Able to access nodes/namespace from a graph for downloaded models

### ISSUE THREAD

**Issue by prateethvnayak** [tensorflow/tensorflow#25974]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
For example, I download a pre-trained model from zoo such as mobilenet. After loading the graph into the session, is there a way to access the higher-level nodes which pertain to layer only. When we access nodes in the graph right now it just gives all the nodes including the ones connected to training and everything. Is there are way to access say only the convolution input/output nodes. 
Currently when you find out the conv weights node and use `node.input` it gives a `mul` node before it. However, i would be looking for the `pooling` layer node or the `activation` node. So is there a way to have a super-view level without the help of tensorboard always. Helps while working on server. Kind of a simple mapping summarizing the model
**Will this change the current api? How?**
yes. the current nodes in the graph_def have attribute `input`. It can be tailored to another attribute say `node.main_input` which gives the next important layer input instead of a low-level op like `mul` or `add`
**Who will benefit with this feature?**
working on remote servers and not able to pull up tensorboard always. Its painful to port the browser always. 
**Any Other info.**
Similar to model.summary() in Keras which gives the overview of the model

**Comment by rmothukuru** [comment]
@prateethvnayak,
Sorry for the delayed response. AFIAK, the functionality you are looking for is possible with [tf.keras.applications.mobilenet.MobileNet](https://www.tensorflow.org/api_docs/python/tf/keras/applications/mobilenet/MobileNet). Can you please let us know if it helps? Thanks!

**Comment by Saduf2019** [comment]
@prateethvnayak 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
