### ISSUE TITLE
Stateful version of contrib.summary.always_record_summaries

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorflow#25981]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13.0-dev20190219'
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
When using summaries in the V2 system, summaries are meant to be written in a context manager created by `summary.always_record_summaries()` or `record_summaries_every_n_global_steps`:

```python
from tensorflow.contrib import summary
...
with summary.always_record_summaries():
    summary.scalar(...)
```

I think it would be useful to have a non-context version of these functions as well. Something like

```python
summary.do_always_record_summaries(True)
summary.scalar(...)  # This will write to the event file
```

This is analogous to how summary writers have both a `as_default()` method for creating a context manager and a `set_as_default` for changing global state.

**Will this change the current api? How?**

The`contrib.summary` module (which I believe is slated to become the main `summary` module in 2.0) will have new methods added.

**Who will benefit with this feature?**

People who are interactively using TensorFlow (especially in eager mode) from a REPL or notebook for small-scale experiments or learning TensorFlow. It's (IMO) useful to write summaries in a quick one-off fashion for immediate visualization in tensorboard. It's tedious on the REPL to make sure all those  calls are wrapped in a wordy and easy-to-forget `with summary.always_record_summaries(): ...`

**Any Other info.**

**Comment by jvishnuvardhan** [comment]
@malmaud Could you post this in Tensorboard issue [here](https://github.com/tensorflow/tensorboard/issues). Tensorboard group is very active so you get faster response. Thanks!

**Comment by malmaud** [comment]
I could, but I'm a little confused - this issue is about the TensorFlow API for writing event files, not  about consuming or visualizing them. So I'm a little unsure how it relates to tensorboard.

**Comment by jvishnuvardhan** [comment]
@malmaud Even EventFileWriter is also taken care by Tensorboard team. Please open it there. Thanks!

**Comment by malmaud** [comment]
I see, thank you!
