### ISSUE TITLE
[TF 2.0 API Docs] tf.keras.applications.MobileNetV2

### ISSUE THREAD

**Issue by JTunis** [tensorflow/tensorflow#25988]
**Existing URLs containing the issue:**
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/applications/MobileNetV2

**Description of issue (what needs changing):**
- __Correct Links__:
https://github.com/tensorflow/tensorflow/blob/master/python/keras/applications/__init__.py is incorrect
The correct link should be:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/__init__.py

* __Clear Description__:
The description does not describe what this symbol does or when it should be 

* __Usage Example__:
No usage example is provided.

* __Parameters Defined__:
Parameters are not defined.

* __Returns Defined__:
Returns are not defined.

* __Raises Listed and Defined__:
Errors are not listed or defined.

* __Visuals, if Applicable__:
No visuals are included.

**Comment by JTunis** [comment]
Since the actual model implementation, including parameters, returns, and errors, is in `keras_applications` (https://github.com/keras-team/keras-applications/blob/master/keras_applications/mobilenet_v2.py), I have a few questions: 
* What would be the best approach to reference this in TF docs?
* Is it still worth pointing the definition link to `__init__.py` in `python/keras/applications`? 
* Is there already a plan for replicating/sharing documentation between Keras and tf.keras?

**Comment by dynamicwebpaige** [comment]
@JTunis Thanks so much for the interest in contributing to TF 2.0 API documentation! We appreciate it, and these are excellent questions. I believe the best approach for modifying this endpoint in TF 2.0 docs would be to modify the docstrings for the [`mobilenet_v2.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/mobilenet_v2.py) file in `tensorflow/tensorflow`. 

All of the documentation for the models listed in [`tf.keras.applications`](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/applications) (VGG16, Xception, etc.) is currently pointing at the [`__init__.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/__init__.py) file; we'll want to make similar changes for each of them, as well, or confirm that we can safely point to the [documentation you referenced](https://github.com/keras-team/keras-applications/blob/master/keras_applications/mobilenet_v2.py) in the Keras project. There is no current plan to migrate documentation from Keras endpoints to their matching `tf.keras` symbols, but we would love to have help!

cc: @MarkDaoust @lamberta to make sure that I'm pointing you in the right direction. 🙂

**Comment by JTunis** [comment]
Happy to take over the documentation of all `tf.keras.applications`. I do think I'd like to play with pointing to `keras-applications`, so that changes are reflected in the TF2.0 docs, or, minimally, adding a link to the actual implementations.

Maybe I'll start with migrating documentation from `keras-applications` to `tf.keras.applications` manually so that there's some useful documentation for users, then depending on the progress of #25341, work on either pointing to `tf.keras` implementations or `keras-applications` implementations.

**Comment by Sri-vatsa** [comment]
@JTunis would love to help as well! Need help with anything?

**Comment by JTunis** [comment]
@Sri-vatsa Totally! I've been struggling to figure out how to point the docs generator to the appropriate file to generate the markdown docs. Some things that I've poked:
* `generate2.py` located [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docs/generate2.py). As it's looping through the results of the parser, it seems to be generating the doc from the markdown from the first appearance of the MobileNetV2 API that it encounters, which seems to be from `python/keras/api/_v2/keras/applications/mobilenet_v2/__init__.py`. Unfortunately, we can't change the docs there because the file is auto-generated from [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/tools/api/generator)
* Maybe I'm making this harder than it has to be, but simply changing docstrings in `mobilenet_v2.py` doesn't change the generated markdown files.

Let me know if you can figure out how to resolve this, then it should be pretty easy to start banging out the docs for all of `tf.keras.applications`

**Comment by Sri-vatsa** [comment]
@JTunis I haven't had a lot of time to look at it yet but from an initial examination, it seems like the docstrings for Keras files have a different format than what is used in Tensorflow. 
Take a look at the corresponding docstring [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/dataset_ops.py) for `tf.data.dataset` api [here](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/Dataset). 

For Keras, the modules are injected from `keras.applications.MobileNetV2` [here](https://github.com/keras-team/keras-applications/blob/master/keras_applications/mobilenet_v2.py). So, I believe that your approach of modifying the`mobilenet_v2.py` might be the solution. Can I check what you have tried changing in `mobilenet_v2.py`?

**Comment by Sri-vatsa** [comment]
@JTunis Figured out how to fix the issue. It is an issue with docstrings within Python Decorators. I have tested the fix locally by checking the readme files generated through `generate2.py`. It is a simple fix by wrapping the Keras functions using the `wraps` decorator from Python's `functools` library.  

1) Modify `tensorflow/tensorflow/python/keras/applications/__init__.py` [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/__init__.py). Import `wraps` from `functools` by adding `from functools import wraps` to the top of the file. Add `@wraps(base_fun)` to the function `keras_modules_injection(base_fun)` 

2) Add docstrings to `mobilenet_v2.py` or any other models in `tf.keras.applications`.

@dynamicwebpaige Regarding the documentation for `tf.keras.applications`, what is the best way to update the documentation? For now, I am thinking of copying the relevant docstrings from `keras_applications`. Would that be alright?

I will clean things up locally and make a PR over this weekend.

**Comment by JTunis** [comment]
@Sri-vatsa Awesome, once your PR is in we can work to divvy up the rest of the the `tf.keras.application` models. 
As far as the docs for each model, I was also thinking of mostly copying relevant docstrings from `keras_applications` and maybe also linking to the implementation (at least until the `tf.keras` implementations are done). There was also a good transfer learning with `tf.keras.applications` models example that I wanted to link to, but I can't seem to find it right now.
