### ISSUE TITLE
Compiling model with tf.keras.optimizers.SGD optimiser in eager execution mode throws an exception

### ISSUE THREAD

**Issue by mjarosie** [tensorflow/tensorflow#25983]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): 
- TensorFlow version: 1.12.0
- Python version: 3.6.8

**Describe the current behavior**
When trying to build a simple model in eager execution mode using SGD as an optimiser the following exception is thrown:
```ValueError: optimizer must be an instance of tf.train.Optimizer, not a <class 'tensorflow.python.keras.optimizers.SGD'>```

**Describe the expected behavior**
I'd expect the SGD optimiser to be usable in eager execution mode.

**Code to reproduce the issue**
```
import tensorflow as tf
tf.enable_eager_execution()

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(50, input_shape=(10, )))
model.add(tf.keras.layers.Activation('relu'))
model.add(tf.keras.layers.Dense(3))
model.add(tf.keras.layers.Activation('sigmoid'))

sgd = tf.keras.optimizers.SGD(lr=0.1, decay=0.000225, momentum=0.5)

model.compile(optimizer=sgd,
              loss='categorical_crossentropy',
              metrics=['accuracy'])
```

**Other info / logs**---------------------------------------------------------------------------
```
ValueError                                Traceback (most recent call last)
<ipython-input-1-3ec239d3547d> in <module>
     12 model.compile(optimizer=sgd,
     13               loss='categorical_crossentropy',
---> 14               metrics=['accuracy'])

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\checkpointable\base.py in _method_wrapper(self, *args, **kwargs)
    472     self._setattr_tracking = False  # pylint: disable=protected-access
    473     try:
--> 474       method(self, *args, **kwargs)
    475     finally:
    476       self._setattr_tracking = previous_value  # pylint: disable=protected-access

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, distribute, **kwargs)
    408       raise ValueError(
    409           'optimizer must be an instance of tf.train.Optimizer, not '
--> 410           'a %s' % type(optimizer))
    411 
    412     self.optimizer = optimizers.get(optimizer)

ValueError: optimizer must be an instance of tf.train.Optimizer, not a <class 'tensorflow.python.keras.optimizers.SGD'>
```

**Comment by yongtang** [comment]
@mjarosie With tf 1.13.0rc2 I am not able to repeat the error. I think the issue may have been resolved. Could you retry with `tensorflow==1.13.0rc2`?

**Comment by mjarosie** [comment]
I confirm - the problem doesn't persist. I'm closing the issue then. Cheers!

**Comment by ranajkh** [comment]
@mjarosie I have the same problem. Can you help me plz?

**Comment by mjarosie** [comment]
@ranajkh have you tried updating Tensorflow?

**Comment by ranajkh** [comment]
@mjarosie my Tensorflow version is '2.1.0' .
