### ISSUE TITLE
reset_states() failure in a stateful network with initial_states set and training in batch - TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by huan** [tensorflow/tensorflow#25985]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-dev20190217
- Python version: 3.5.2
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 10
- GPU model and memory: GTX 1080 8G

**Describe the current behavior**

As @manojrege said from https://github.com/keras-team/keras/issues/11148, when we use `initial_states` with RNN in some case, we will get an exception:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/manoj/Desktop/repos/yane/yane/LSTM/manytomanyLSTM.py", line 137, in <module>
    incremental_train(space)
  File "/Users/manoj/Desktop/repos/yane/yane/LSTM/manytomanyLSTM.py", line 128, in incremental_train
    model.reset_states()
  File "/usr/local/lib/python3.6/site-packages/keras/engine/topology.py", line 1968, in reset_states
    layer.reset_states()
  File "/usr/local/lib/python3.6/site-packages/keras/layers/recurrent.py", line 681, in reset_states
    batch_size = self.input_spec[0].shape[0]        
TypeError: 'NoneType' object is not subscriptable
```

There's another issue talking about this problem at #25852

**Describe the expected behavior**

Should not throw exception.

**Code to reproduce the issue**

```py
import tensorflow as tf

# import pdb; pdb.set_trace()
inputs = tf.keras.layers.Input(batch_shape=(1, 1, 1))

state_h = tf.keras.layers.Input(batch_shape=(1, 1))
state_c = tf.keras.layers.Input(batch_shape=(1, 1))

states = [state_h, state_c]

decoder_out = tf.keras.layers.LSTM(1, stateful=True)(
    inputs,
    initial_state=states
)

model = tf.keras.Model([inputs, state_h, state_c], decoder_out)
model.reset_states()
```

**Other info / logs**

I can confirm that the Pull Request https://github.com/keras-team/keras/pull/11149/files can fix this problem.

**Comment by qlzh727** [comment]
This should be now fixed by https://github.com/tensorflow/tensorflow/commit/83df61b4d4ad11f3b8cf05ee98d29e6fb5e25506.

**Comment by huan** [comment]
Thanks, that's awesome.
