### ISSUE TITLE
run_metadata should be preserved when session run fails

### ISSUE THREAD

**Issue by guoshimin** [tensorflow/tensorflow#25990]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 14.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12.0
- Python version: 2.7
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: 9.0/7
- GPU model and memory: Titan Xp 12GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
run_metadata is empty when a session run fails.

**Describe the expected behavior**
run_metadata should be saved even (especially?) when session run fails.

**Code to reproduce the issue**
```
with tf.device("/GPU:0"):
    input = tf.random_uniform(dtype=tf.float32, shape=[5, 100, 100, 3], name="input")
    resize = tf.image.resize_bilinear(input, [99999, 99999], align_corners=True)  # OOM
run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
run_metadata = tf.RunMetadata()
with tf.Session() as sess:
    try:
        sess.run(resize, options=run_options, run_metadata=run_metadata)
    finally:
        run_metadata_str = str(run_metadata)
        if run_metadata_str:
            print(run_metadata_str)
        else:
            print("No run_metadata")

```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by facaiy** [comment]
@mrry Hi, Derek. What do you think?

**Comment by mrry** [comment]
It's a totally reasonable suggestion, but I don't think it will be a high priority with the [deprecation of `tf.Session` in TF 2.0](https://github.com/tensorflow/community/pull/20). If anything, it might make more sense to ensure this behavior on calls to a `tf.function`.

**Comment by guoshimin** [comment]
@mrry Is there any way to use RunMetadata with tf.function now? The doc you linked mentions a doc at go/tf-2.0-function-api but obviously it's not accessible externally.

**Comment by guoshimin** [comment]
I tried the following code and it seems to be working as intended:

```
from tensorflow.python.eager import context

@tf.function
def make_input():
    return tf.random.uniform(dtype=tf.float32, shape=[5, 100, 100, 3], name="input")

@tf.function
def resize(input):
    return tf.image.resize(input, [20000, 20000], align_corners=True)

context.enable_run_metadata()
try:
    with tf.device("/device:GPU:0"):
        output = resize(make_input())
finally:
    print(context.export_run_metadata().step_stats)
```

I'll close the issue and if someone wants to have this behavior with sessions they can take a look at #25991
