### ISSUE TITLE
ImportError: cannot import name cloud

### ISSUE THREAD

**Issue by TropSpirit** [tensorflow/tensorflow#25994]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No, using stock tensorflow 
- Python version: 2.7
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source): gcc version 8.2.0 (Debian 8.2.0-20)
- CUDA/cuDNN version: No
- GPU model and memory: No

== cat /etc/issue ===============================================
Linux rockpro64 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
VERSION="18.04.1 LTS (Bionic Beaver)"
VERSION_ID="18.04"
VERSION_CODENAME=bionic

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 8.2.0-1ubuntu2~18.04) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a ImportError: cannot import name cloud=====================================================
Linux rockpro64 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

== check pips ===================================================
numpy                         1.16.1   
protobuf                      3.6.1    
tensorflow                    1.12.0   
tensorflow-aarch64            1.2      
tensorflow-estimator          1.13.0rc0

== check for virtualenv =========================================
False

== tensorflow import ============================================
Limited tf.compat.v2.summary API due to missing TensorBoard installation
tf.VERSION = 1.12.0
tf.GIT_VERSION = v1.12.0-8122-g7328add9da
tf.COMPILER_VERSION = v1.12.0-8122-g7328add9da
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

rock64@rockpro64:~/Documents$ python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
**('v1.12.0-8122-g7328add9da', '1.12.0')**

following is the error. NO module name cloud.

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 44, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 31, in <module>
    from tensorflow.contrib import cloud
**ImportError: cannot import name cloud**

**Comment by ymodak** [comment]
Please take a look at duplicate issue #23976

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
