### ISSUE TITLE
Excess amount of deprecated warning in tf1.13

### ISSUE THREAD

**Issue by henrysky** [tensorflow/tensorflow#25996]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7.6.1810
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.13.0rc2
- Python version: 3.6.5
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: 10/7.3.1
- GPU model and memory: Titan Xp

**Describe the current behavior**
 Even a script as simple as below have thrown 3 deprecated warnings
```python
import tensorflow as tf
import numpy as np

input = tf.keras.layers.Input(shape=(20,))
output = tf.keras.layers.Dense(2)(input)
model = tf.keras.models.Model(inputs=input, outputs=output)
model.compile(loss='mse', optimizer='sgd')

model.fit(np.random.normal(0, 1, (200, 20)), np.random.normal(0, 1, (200, 2)))
```

```
WARNING:tensorflow:From /home/henrysky/.local/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
```

```
WARNING:tensorflow:From /home/henrysky/.local/lib/python3.6/site-packages/tensorflow/python/keras/utils/losses_utils.py:170: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
```

```
WARNING:tensorflow:From /home/henrysky/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
```

**Describe the expected behavior**
Little to no deprecated warning. I mean it is deprecated warning should be shown to user when user write their own code using low level tensorflow function. But the code as simple as above using high level function thrown 3 warnings??

**Code to reproduce the issue**
see above

**Other info / logs**
see above

**Comment by facaiy** [comment]
Welcome to contribute. Would you like to fix those depressed warning?

**Comment by henrysky** [comment]
> Welcome to contribute. Would you like to fix those depressed warning?

At least those warnings about tf.cast are fixed in master branch already. Is it possible to cherry pick them to r1.13 branch??

**Comment by facaiy** [comment]
I'm afraid not since r1.3 branch had been cut before. Would you like to use tf-nightly? Or just wait for next version? Sorry for the inconvenience.

**Comment by henrysky** [comment]
It is okay for me, just a bit annoying to see all these deprecated warning. But it is probably not ideal for new users using tensorflow keras to see all these warnings and confuse them.

I think tensorflow should make sure all these deprecated warnings are fixed in the next 1.x or 2.x release.

**Comment by facaiy** [comment]
Agreed. See more discussion in https://groups.google.com/a/tensorflow.org/forum/#!msg/developers/C2c6T9Hrh4I/RayJkLPbAgAJ

Let's close the issue because some deprecated warnings have been fixed in the master branch as you said?

**Comment by henrysky** [comment]
ok

**Comment by bwolfus** [comment]
I have the same issue in TF 1.13.1.

```
WARNING	From C:\python36\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
```

```
WARNING	From C:\python36\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
```

```
WARNING	From C:\python36\lib\site-packages\keras\backend\tensorflow_backend.py:3368: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
```


```
WARNING	From C:\python36\lib\site-packages\tensorflow\python\ops\math_grad.py:102: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
```

**Comment by facaiy** [comment]
Hi, @bwolfus . I think some deprecated warnings has been clear in the master branch, and it will take effect in the next release (perhaps 1.14 or 2.0). And if not, we welcome contributions to fix it.

**Comment by bwolfus** [comment]
Hi, @facaiy. Thank you for your answer. In that case I will wait for the new version.

**Comment by maxima120** [comment]
I think this is totally wrong direction you guys took here. Its like a man from a street turns into an aerospace company and demands to switch off all the low fuel warning because they distract him from watching naughty movies..

what you might want to do is to have a warning level users can set on tensorflow session (similar to C compiler).. like use warnings_level=0 to no warnings.

**Comment by EliasHasle** [comment]
@maxima120 I think this is different. The warnings are in principle to the TF developers, since they arise from code that is not up to date with the current API. They are merely a nuisance to users.

**Comment by facaiy** [comment]
> I think this is totally wrong direction you guys took here. Its like a man from a street turns into an aerospace company and demands to switch off all the low fuel warnings in all aircrafts because they distract him from watching naughty movies..
> 
> what you might want to do is to have a warning level users can set on tensorflow session (similar to C compiler).. like use warnings_level=0 to no warnings.

You might misunderstand us. What we mean here is to fix those deprecated warnings (replace the deprecated op by its new candidate).

**Comment by evrial** [comment]
> I think this is totally wrong direction you guys took here. Its like a man from a street turns into an aerospace company and demands to switch off all the low fuel warnings in all aircrafts because they distract him from watching naughty movies..
> 
> what you might want to do is to have a warning level users can set on tensorflow session (similar to C compiler).. like use warnings_level=0 to no warnings.

More likely aerospace company don't use their own product with 130k stars on GH, which has blinking warning lights all the time and no fucks given because opensource.

**Comment by iperov** [comment]
```
import tensorflow
import logging
logging.getLogger('tensorflow').setLevel(logging.ERROR)
```

**Comment by zchrissirhcz** [comment]
@iperov I've tried your pasted solution but still got annoying warnings.

**Comment by iperov** [comment]
@zchrissirhcz 

```
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # tf log errors only
import tensorflow as tf
import logging
logging.getLogger('tensorflow').setLevel(logging.ERROR)
```
I don't have any warnings. Tested in DeepFaceLab.

**Comment by evrial** [comment]
`tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)`
is the only one and correct method. Works on any version too.

**Comment by zchrissirhcz** [comment]
@evrial No, what you paste is still not working. Actually what I'm using in the very begging of my imports is:
```Python
# coding: utf-8
import tensorflow as tf
import os

if type(tf.contrib) != type(tf): tf.contrib._warning = None
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# Only use CPU:
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
```

And after re-directing the stdout of my program to a file, the console still gives warning output, e.g.
```
WARNING:tensorflow:From /home/zz/soft/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/zz/soft/miniconda3/lib/python3.7/site-packages/tensorflow/python/profiler/internal/flops_registry.py:142: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.remove_training_nodes
WARNING:tensorflow:From /home/zz/soft/miniconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
```

**Comment by zchrissirhcz** [comment]
> @zchrissirhcz
> 
> ```
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # tf log errors only
> import tensorflow as tf
> import logging
> logging.getLogger('tensorflow').setLevel(logging.ERROR)
> ```
> 
> I don't have any warnings. Tested in DeepFaceLab in tf 1.13.2 .

You don't have any warning doesn't mean other people don't get any warnings.

**Comment by iperov** [comment]
> ```python
> # coding: utf-8
> import tensorflow as tf
> import os
> 
> if type(tf.contrib) != type(tf): tf.contrib._warning = None
> tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
> 
> # Only use CPU:
> os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
> os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
> ```

seriously you don't see what is wrong with your code?

**Comment by zchrissirhcz** [comment]
@iperov Please preciously describe what you mean "wrong". There's no error in my code, only stdout and warnings, and warnings are from TensorFlow inside. I don't thinks this is wrong, and I think people who reach here are all in situations like me: dislike the warnings throwed by TensorFlow and would like to turn off them. What you pasted **does** eliminate some common warnings, **However it is still not enough to eliminate all the warnings**.

**Comment by iperov** [comment]
look at my code again. If you don't see the differences, wash your eyes and look again.

**Comment by zchrissirhcz** [comment]
@iperov If you mean what I should attention is:
```
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
```

instead of mine:
```
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
```

Then, I think you don't understant what this switch mean. 3 standards for fatal message, while 2 standands for error. This different won't affect the warning output.

**Comment by iperov** [comment]
![sdf](https://user-images.githubusercontent.com/8076202/84634057-517a8200-af02-11ea-87f9-6992e32339ad.jpg)

**Comment by zchrissirhcz** [comment]
@iperov  Actually I just tried remove my previous imports, and replace with you pasted, i.e.

```pytho
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # tf log errors only
import tensorflow as tf
import logging
logging.getLogger('tensorflow').setLevel(logging.ERROR)
```

But it is still warning. I think you just mis-understanding me.

**Comment by zchrissirhcz** [comment]
@iperov Actually I don't know DeepFaceLab until you mentioned it. It's not persuasive to prove what you paste is definitely correct for other people's program. You'd better say "it would most possibly remove other people's warnings but not 100% sure".

**Comment by Dreamcouple** [comment]
WARNING:tensorflow:From D:\tensorflow_object_Detection\TFODCourse\tfodc\lib\site-packages\tensorflow\python\util\dispatch.py:1082: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.


i too have these error , how to rectify this???, it takes so much long time to perform even after 2hrs also, it remains at same leve
![tf](https://user-images.githubusercontent.com/98043231/185156382-ea585d98-dc78-488a-866f-65757a8cb005.png)
