### ISSUE TITLE
simplify contributing process

### ISSUE THREAD

**Issue by bbodenmiller** [tensorflow/tensorflow#26]
Currently the contributing process is rather complex... I have to use another website, clone the repo, and more. I'm just interested in making some minor tweaks to the documentation that normally can be done with just a few clicks using GitHub.

**Comment by mdda** [comment]
As a timesaver, I wrote up the process in a [blog post](http://blog.mdda.net/ai/2015/11/10/contributing-to-tensorflow/) (mostly because compared to GitHub, the process is poor).

**Comment by vrv** [comment]
Thanks!  We'll use this bug to track the improvements to the contribution process, which we are working on improving.

**Comment by bhack** [comment]
:+1+

**Comment by bhack** [comment]
This [Github Gerrit plugin](https://gerrit.googlesource.com/plugins/github/) could be evaluated

**Comment by bhack** [comment]
Is [this googlebot](https://github.com/google/ExoPlayer/pull/948#issuecomment-155787996) behaviour on other Google projects on github enought to let collect directly PRs here? If you want to get a pass with Gerrit you can also use the Gerrit github plugin I've already mentioned.

**Comment by bhack** [comment]
Also nice  to evaluate is https://github.com/facebook/mention-bot

**Comment by bhack** [comment]
@vrv github history/log is full of "TensorFlow: Merging changes from internal". Not very readable.

**Comment by martinwicke** [comment]
You're correct. We're working on the process. It'll get better.

**Comment by bhack** [comment]
@martinwicke Google [
ExoPlayer](https://github.com/google/ExoPlayer) like github management could be a starting point.

**Comment by vrv** [comment]
@bhack: fixed our scripts to have more informative / separate commits: https://github.com/tensorflow/tensorflow/commits/master

Hope that helps a bit.

**Comment by bhack** [comment]
@vrv If you don't rewrite the history and push force now some info will be lost forever here. Related, do you don't like the Gerrit plugin I suggested? Why other Google projects like ExoPlayer seems to have a more "natural" relation with github?

**Comment by bhack** [comment]
The last commit seems to have the same description https://github.com/tensorflow/tensorflow/commit/091ed8cd4db82212fc6395ce4f1edf6b55ea2181

**Comment by vrv** [comment]
@bhack: other projects probably have a more natural relation with github because they only have one source of truth.  We have git, and we have our internal repository that we also contribute to actively, so the merge commit is unavoidable when trying to merge two different lineages.

That being said, now that we've moved to individual commits, the merge commit shouldn't be that bad.  And it's basically the same as the merge commit from a pull request on github.

**Comment by bhack** [comment]
@vrv OK but why not the Gerrit github plugin? For the history in last commit I still see the same message see https://github.com/tensorflow/tensorflow/commit/deff101b27e2d3d2d0f68417991e9183bdcd3256

**Comment by vrv** [comment]
We are looking at that plugin as one potential option.

The last commit will always be a 'merge commit' message.  https://github.com/BVLC/caffe/commit/79539180edc73d3716149fb28e07c67a45896be1 is the same, except we don't have a github pull request to reference, since the source isn't from github.  Is there a better 'merge commit' message you would like?

**Comment by bhack** [comment]
@vrv https://github.com/BVLC/caffe/commit/79539180edc73d3716149fb28e07c67a45896be1 reference the related PR. I don't know so well Gerrit to tell you what reference get in the script to not let merge description be always the same.

**Comment by martinwicke** [comment]
@vrv: Should we just include the two commits hashes that were merged in the title?

**Comment by bhack** [comment]
For subscribers of this Issue the policy on PRs it is changed. Please see the new versions of [CONTRIBUTING.md](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md)

**Comment by bhack** [comment]
@vrv In the caffe example you posted we have a description "Add ifdef in CuDNNConvolutionLayer for cuDNN v4". Can we recover some kind of info like this from Gerrit to put in the history. Actually I if want to move trough the history I need to always check file changes of internal merges cause descriptions are uninformative.

**Comment by vrv** [comment]
The merge commit is merging a series of commits from our internal repository.  https://github.com/tensorflow/tensorflow/commit/8b5d9ed13f188662dde7cce75362cd2394bde40c is just the merge of the four previous commits, which each individually have the descriptions and change history you want.

For now, I'd suggest just skipping the "Merge commits from internal" commits when looking through the history.  Maybe soon we can just have the merge commit message identify which commit hashes it merged so it's more easily linked.

**Comment by bhack** [comment]
Yes what I mean is if that upstream "gerrit commits" merges are assimilable to a PR as conceptual description. If so probably you could use this concept in the merge description. I.e. many project ask to squash commits on PRs before mergining. But if that are sparse uncorrelated commit I think not description make sense.

**Comment by martinwicke** [comment]
There is the equivalent of potentially many unrelated PRs in any such
merge, that's why it's hard to find a decent description for the sum of
them.

**Comment by vrv** [comment]
We've switched to github and there are ongoing improvements to automated testing, etc.  But the basics have been improved, so closing this catch-all bug.
