### ISSUE TITLE
Issue in running the models of tensorflow

### ISSUE THREAD

**Issue by harshita-pal** [tensorflow/tensorflow#26003]
Hi,I want to know how to run various models like mobile net, image net, resnet  .Is there any particular set of steps to run these models or any official tensorflow tutorial to follow.Kindly guide me for the same.
Right Now i am following these steps:
1. sudo apt install python3-dev python3-pip
2. sudo pip3 install -U virtualenv
3. virtualenv --system-site-packages -p python3 ./venv
4. source ./venv/bin/activate
5. pip install --upgrade pip
6. pip list
7. pip install --upgrade tensorflow
8. pip install -U --user pip six numpy wheel mock
9. pip install -U --user keras_applications==1.0.6 --no-deps
10. pip install -U --user keras_preprocessing==1.0.5 --no-deps
11. git clone https://github.com/tensorflow/tensorflow.git
12. git clone https://github.com/tensorflow/models.git
12. cd tensorflow

(Python version-3.5.2
virtual env version-16.04
pip version-19.0.3)

Please Help!

****

**Comment by ymodak** [comment]
You can refer to the instructions posted on https://github.com/tensorflow/models/tree/master/official and further the markdown files of different models in official directory.
