### ISSUE TITLE
Support python 3.x based Tensorflow in docker image

### ISSUE THREAD

**Issue by jediweon** [tensorflow/tensorflow#2600]
I'm trying to use tensorflow on Docker environment, and it turns out that tensorflow package is missing in python 3.4 dist-package in official docker image. Is there any reason for not supporting it?

**Comment by hnykda** [comment]
Yes, it would be great to have Python 3 docker images, since there are installations available for 3.4 and even 3.5.

**Comment by mrry** [comment]
@caisq: Do you know how much effort it would be to add this?

**Comment by gunan** [comment]
@caisq has already taken care of this, as far as I know.
Please see our *py3 docker images. in dockerhub.
