### ISSUE TITLE
Install Tensorflow GPU with CUDA 10.0 on windows

### ISSUE THREAD

**Issue by Sission** [tensorflow/tensorflow#26002]
Hi guys. I am new to the tensorflow. I would like to install Tensorflow-Gpu with my RTX2080ti graphic card. I followed this instruction 
https://www.pytorials.com/how-to-install-tensorflow-gpu-with-cuda-10-0-for-python-on-windows/

However, when I do the Step 12. The error shows up.

bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

Because RTX 2080 ti only support Cuda 10.0, it is very difficult for me to install tensorflow. Anyone can help me with this error or provide another useful instruction? Thanks a lot!!

**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from: source
- TensorFlow version: 1.12
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.17
- CUDA/cuDNN version: cuda 10.0 cuDNN 7.4.2
- GPU model and memory: Nvidia RTX 2080ti

**The Error**
p_packageuild --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: tensorflow/tools/pip_package
DEBUG: C:/users/shica/_bazel_shica/wvk7snnt/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/shica/_bazel_shica/wvk7snnt/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/shica/_bazel_shica/wvk7snnt/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 1447
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 1303, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 217, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 153, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
type 'NoneType' has no method replace(string, string)
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 1447
                _create_local_cuda_repository(repository_ctx)
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 1303, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 217, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 153, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
type 'NoneType' has no method replace(string, string)
INFO: Elapsed time: 1.561s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by ymodak** [comment]
Please install TensorFlow version 1.13.0-rc2 it supports cuda 10.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
