### ISSUE TITLE
tensorflow c++ crash

### ISSUE THREAD

**Issue by oldoldman** [tensorflow/tensorflow#26013]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win 10 64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version:1.12.0
- Python version: N/A
- Installed using virtualenv? pip? conda?:N/A
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

I build tensorflow manually , and write an simple test using c++ api , the crash dump is as follow ,
please help !!!

```
0:000> kn
 # Child-SP          RetAddr           Call Site
00 00000056`4cf0f880 00007ff7`2111d70d tfdemo!_invoke_watson+0x18 [minkernel\crts\ucrt\src\appcrt\misc\invalid_parameter.cpp @ 224] 
01 00000056`4cf0f8b0 00007ff7`2111d77d tfdemo!_invalid_parameter+0xad [minkernel\crts\ucrt\src\appcrt\misc\invalid_parameter.cpp @ 112] 
02 00000056`4cf0f8f0 00007ff7`20d53c19 tfdemo!_invalid_parameter_noinfo_noreturn+0x19 [minkernel\crts\ucrt\src\appcrt\misc\invalid_parameter.cpp @ 126] 
03 00000056`4cf0f930 00007ff7`20d4cf58 tfdemo!std::_Adjust_manually_vector_aligned+0x79
04 00000056`4cf0f980 00007ff7`20d58222 tfdemo!std::_Deallocate<16,0>+0x28
05 00000056`4cf0f9b0 00007ff7`20d57487 tfdemo!std::allocator<char>::deallocate+0x22
06 00000056`4cf0f9e0 00007ff7`20d506bc tfdemo!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy_deallocate+0x87
07 00000056`4cf0fa30 00007ff7`20d5c39c tfdemo!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> >+0x1c
08 00000056`4cf0fa70 00007ff7`20d5bc8f tfdemo!tensorflow::NodeBuilder::~NodeBuilder+0x1c
09 00000056`4cf0faa0 00007ff7`20d5ad37 tfdemo!tensorflow::ops::NoOp::NoOp+0x23f
0a 00000056`4cf0fd30 00007ff7`20d5ad89 tfdemo!demo2+0x27
0b 00000056`4cf0fd90 00007ff7`210d4d4c tfdemo!main+0x9
0c (Inline Function) --------`-------- tfdemo!invoke_main+0x22 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 78] 
0d 00000056`4cf0fdc0 00007ffa`94543034 tfdemo!__scrt_common_main_seh+0x10c [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 283] 
0e 00000056`4cf0fe00 00007ffa`948f3691 KERNEL32!BaseThreadInitThunk+0x14
0f 00000056`4cf0fe30 00000000`00000000 ntdll!RtlUserThreadStart+0x21
```

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by oldoldman** [comment]
have found the reason

**Comment by lihas** [comment]
> have found the reason

And what is the reason?
