### ISSUE TITLE
tf.data.experimental.bucket_by_sequence_length

### ISSUE THREAD

**Issue by dingevin** [tensorflow/tensorflow#26011]
I wanted to read speech data from tfrecord and use tf.data.experimental.bucket_by_sequence_length to bucketing data by seq_len, but i have same error when use it. here is my code:
`

    fea_conf = dict([
    ('SOS_ID', 2),
    ('EOS_ID', 3),
    ('BATCH_SIZE', 2),
    ('FRAME_SIZE', 80),
    ('GRAPHEME_TARGET_SEQUENCE_LENGTH', 620),])

     def read_TFRecord(file_pattern, symbol):
         """read tfrecord."""
          file_pattern = os.path.join(file_pattern, '%s.tfrecords-*'%symbol)
          def ParseAndProcess(record):
             """Parses a serialized tf.Example record."""
             features = [
                 ('uttid', tf.VarLenFeature(tf.string)),
                 ('label', tf.VarLenFeature(tf.int64)),
                 ('frames', tf.VarLenFeature(tf.float32)),
              ]
              example = tf.parse_single_example(record, dict(features))
              fval = {k: v.values for k, v in six.iteritems(example)}
              fval['frames'] = tf.reshape(
                  fval['frames'], shape=[-1, fea_conf['FRAME_SIZE']])
              src_paddings = tf.ones([tf.shape(fval['frames'])[0]], dtype=tf.float32)

              fval['label'] = tf.reshape(fval['label'], shape=[1, -1])
              tgt_labels = tf.concat(
                  [tf.cast(fval['label'], tf.int32),
              tf.fill([1,fea_conf['GRAPHEME_TARGET_SEQUENCE_LENGTH']-tf.shape(fval['label'])[-1]], 
                  fea_conf['EOS_ID'])],
                  axis=1
              )
              tgt_ids = tf.concat(
                  [tf.fill([1,1], fea_conf['SOS_ID']),
              tf.slice(tgt_labels, [0,0], [1, fea_conf['GRAPHEME_TARGET_SEQUENCE_LENGTH']-1])],
                  axis=1
              )
              tgt_paddings = tf.concat(
                  [tf.zeros([1, tf.shape(fval['label'])[-1]+1], dtype=tf.float32),
              tf.ones([1, fea_conf['GRAPHEME_TARGET_SEQUENCE_LENGTH']-tf.shape(fval['label'])[-1]-1], 
                  dtype=tf.float32)],
                  axis=1
              )
              return (fval['uttid'], tgt_ids, tgt_labels, tgt_paddings, fval['frames'], src_paddings)
          def element_length_fn(example): #(uttids, tgt_ids, tgt_labels, tgt_paddings, frames, src_paddings):
              print(type(example))
              batch_size = tf.shape(example)[0]
              return feature_length

           dataset_factory = tf.data.TFRecordDataset
           dataset = (
                  tf.data.Dataset.list_files(
                        file_pattern.lstrip('tfrecord:'), shuffle=True).apply(
                             tf.data.experimental.parallel_interleave(
                                  dataset_factory,
                                  cycle_length=1,
                                  sloppy=True)))
            dataset = dataset.apply(
                  tf.data.experimental.bucket_by_sequence_length(
                        element_length_func=element_length_fn,
                               bucket_batch_sizes= [256, 128, 64],
                               bucket_boundaries=[100, 300],
                               #padded_shapes=([None], [1, None], [1, None], [1, None], [None, 80], [None]),
           ))
           #dataset = dataset.shuffle(500)
           dataset = dataset.map(
                  ParseAndProcess, num_parallel_calls=1)
           #dataset = dataset.padded_batch(
           #   fea_conf['BATCH_SIZE'], padded_shapes=([None], [1, None], [1, None], [1, None], [None, 80], [None]))
           dataset = dataset.repeat()
           iterator = dataset.make_one_shot_iterator()
           input_batch = iterator.get_next()

           return input_batch[0], input_batch[1], input_batch[2], input_batch[3], input_batch[4], input_batch[5]
`
when i run my code, the error is occur:   ValueError: slice index 0 of dimension 0 out of bounds. for 'strided_slice' (op: 'StridedSlice') with input shapes: [0], 1, 1, 1 and with computed input tensors: input1 = <0>, input[2] = <1>, input[3] = <1>, that i don't konw how to use tf.data.experimental.bucket_by_sequence_length with tfrecordes to buckets.  i just know that code[https://stackoverflow.com/questions/50606178/tensorflow-tf-data-dataset-and-bucketing](url)；
can anybody tell me how to use it or give me a sample to handle variable length data.

**Comment by dingevin** [comment]
i have modified def element_length_fn  to:
`
def element_length_fn(example):
    return tf.shape(example)
`
but get this error: Dimensions must be equal, but are 3 and 0 for 'LessEqual' (op: 'LessEqual') with input shapes: [3], [0].   i think this's my reason of error, but i don't know how to modify it.

**Comment by mrry** [comment]
Ryan added this transformation, so I'll let him comment on the usage question.

**Comment by rsepassi** [comment]
`element_length_func` should be a function from an element in the `Dataset` to a scalar `int32` (i.e. a `Tensor` of shape `()` and type `tf.int32`), which is the length of the element. This determines which bucket the example will be routed to (the buckets are specified by `bucket_boundaries`). Then examples in each bucket will be batched together with batch sizes specified with `bucket_batch_sizes`.

**Comment by kiunthmo** [comment]
> i have modified def element_length_fn to:
> `def element_length_fn(example): return tf.shape(example)`
> but get this error: Dimensions must be equal, but are 3 and 0 for 'LessEqual' (op: 'LessEqual') with input shapes: [3], [0]. i think this's my reason of error, but i don't know how to modify it.

Unpack the example?

**Comment by rsepassi** [comment]
You may want `tf.size(example)` which returns a scalar. `tf.shape` returns a vector of the sizes of each dimension.
