### ISSUE TITLE
RaggedTile op results in XlaCompile error when calculating gradients

### ISSUE THREAD

**Issue by danecor** [tensorflow/tensorflow#26015]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.13.6
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): Both 1.13.0rc2 and tf-nightly
- Python version: 3.6.8
- CUDA/cuDNN version: no GPU
- GPU model and memory: no GPU

**Describe the current behavior**
Gradient operations on ragged arrays requiring an implicit RaggedTile op result in
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'product/RaggedTile/Tile' has no attr named '_XlaCompile'. 

**Describe the expected behavior**
Gradients can be determined without error.

**Code to reproduce the issue**

```
import tensorflow as tf
import numpy as np

np_arr = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.]])
myvar = tf.get_variable('myvar', initializer=np_arr)
ragged = tf.ragged.constant([[0,1,2],[1,2],[1]])
with tf.name_scope('gather'):
    ragged_gather = tf.gather(myvar, ragged)
with tf.name_scope('product'):
    product = tf.math.multiply(ragged_gather, ragged_gather, name='prod')
with tf.name_scope('output'):
    output = tf.reduce_sum(product**2, name='output')

sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(sess.run(ragged_gather))
# <tf.RaggedTensorValue [[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]], [[4.0, 5.0, 6.0], [7.0, 8.0, 9.0]], [[4.0, 5.0, 6.0]]]>
print(sess.run(output))
# 32745.0

grads = tf.gradients(output, myvar)
# tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'product/RaggedTile/Tile' has no attr named '_XlaCompile'.

```
[full_traceback.txt](https://github.com/tensorflow/tensorflow/files/2895038/full_traceback.txt)

**Comment by danecor** [comment]
Note: I don't seem to have this problem in eager mode. At the moment my work-around is to implement the code in eager.

**Comment by ymodak** [comment]
The latest tf nightly build fixes this issue. Feel free to reopen if have further questions. Thanks!
