### ISSUE TITLE
TypeError: can only concatenate list (not "tuple") to list

### ISSUE THREAD

**Issue by huan** [tensorflow/tensorflow#26026]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
* Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
* Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
* TensorFlow installed from (source or binary): binary
* TensorFlow version (use command below): 2.0.0-dev20190217
* Python version: 3.5.2
* Bazel version (if compiling from source): n/a
* GCC/Compiler version (if compiling from source): n/a
* CUDA/cuDNN version: 10
* GPU model and memory: GTX 1080 8G

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

```
Traceback (most recent call last):
  File "t.py", line 16, in <module>
    model(data)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 620, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/sequential.py", line 248, in call
    outputs = layer(inputs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/recurrent.py", line 713, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 620, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/recurrent.py", line 2132, in call
    return [output] + states
TypeError: can only concatenate list (not "tuple") to list
```

**Describe the expected behavior**

Should not throw exception

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```py
import tensorflow as tf

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Masking())
model.add(tf.keras.layers.GRU(
    units=1,
    # Set `return_state` to `True` will cause the TypeError:
    #   "can only concatenate list (not "tuple") to list"
    return_state=True,
))

data = [1.]
data = tf.convert_to_tensor(data)
data = tf.reshape(data, (1, 1, 1))

model(data)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

1. If we do not use `tf.keras.layers.Masking`, then it will not throw the exception
1. If we do not use `return_state`, then it will not throw the exception

The problem is at:

https://github.com/tensorflow/tensorflow/blob/2ae06ca49145bfee2e5e98c64ae5cbe064a58a33/tensorflow/python/keras/layers/recurrent.py#L2134

Which the `state` returned from `K.rnn` is a `tuple` instead of a `list`, so that ` [output] + states` will fail and throw exception.

https://github.com/tensorflow/tensorflow/blob/2ae06ca49145bfee2e5e98c64ae5cbe064a58a33/tensorflow/python/keras/layers/recurrent.py#L2107

**Comment by qlzh727** [comment]
Thanks for reporting the issue, I will take a look within this week.

**Comment by qlzh727** [comment]
Fixed.
