### ISSUE TITLE
unable to import tensor flow and keras

### ISSUE THREAD

**Issue by KashishDesai** [tensorflow/tensorflow#26025]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip installed using the tensorflow guide
- TensorFlow version: tried with pip install tensorflow, pip install tensorflow==1.5, pip install tensorflow==1.4
- Python version: 3.6.0
- Installed using virtualenv? pip? conda?: in command line using pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: intel core i5

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
python 3.6 is installed and I have pip installed tensorflow==1.4 still receiving that error

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
C:\Users\kashish\myFlask>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kashish\AppData\Local\Programs\Python\Python36\lib\site-package
s\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\kashish\AppData\Local\Programs\Python\Python36\lib\site-package
s\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\kashish\AppData\Local\Programs\Python\Python36\lib\site-package
s\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\kashish\AppData\Local\Programs\Python\Python36\lib\site-package
s\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.
>>>

**Comment by KashishDesai** [comment]
I also installed microsoft visual c++ 2015 redistributable, still getting errors. and few of the similar problem suggested to uninstall tensorflow and try lower versions of it because it worked for them, I have tried those as well, still stuck with this problem. Help Me!!
Thanks

it successfully installs keras and tensorflow but then creates error while importing them

**Comment by ymodak** [comment]
TF 1.5 is very old version. Why don't you install the latest one? You can simple do,
> pip install tensorflow
No need to specify version. It will grab the latest one.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
