### ISSUE TITLE
SplitPath should split on both forward slashes and backslashes on Windows

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorflow#26021]
Currently, on Unix, SplitPath splits only on forward slashes; on
Windows, it splits on forward slashes _unless_ there are no forward
slashes in the string, in which case it splits on backslashes. This is
confusing, and inconsistent with platform APIs like [`_wmkdir`], which
interpret both `\` and `/` as valid path delimiters.

For instance, `CreateRecursiveDirectory(r"foo\bar/baz\quux")` fails on
Windows. This _should_ be broken into `["foo", "bar", "baz", "quux"]`,
but actually becomes `["foo", "bar", "baz\quux"]`. When `CreateDir` is
called on each of those components in sequence, it creates `foo`, then
creates `foo/bar`, then tries to create `foo/bar/baz\quux`, which fails
because the directory `foo/bar/baz` does not exist.

(Googlers, see <http://b/125762969> for an example of this error.)

The whole situation is a bit less clean than one might hope, because the
TF filesystem API prefers to use `/`-separators everywhere while people
in Python-land prefer to use `os.path.join` to insert the proper
platform-specific path separator. But it seems clear that the current
behavior, where the delimiter used depends on what characters are in the
string, is undesirable, and that being consistent with native APIs is a
better choice.

[`_wmkdir`]: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/mkdir-wmkdir?view=vs-2017

cc @nfelt

**Comment by sushreebarsa** [comment]
@wchargin Sorry for the late response!
Could you please let us know if the issue still persists in latest TF versions as older versions are not actively supported ?
Thank you!

**Comment by tilakrayal** [comment]
@wchargin,
The related PR's which are raised has been merged already. 

https://github.com/tensorflow/tensorflow/commit/e19d945009bdb44cfab63b344373258084c4bf8b
https://github.com/tensorflow/tensorflow/commit/e91d746e0bf0c1c6faa0c7281466acad8b7290fd

Below changes are updated in the respective file.
```
      logdir, 'plugins', 'profile',
      datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S'))
```
Thank you!
