### ISSUE TITLE
I having an issue that tensorflow is throwing "Failed to load the native Tensorflow runtime".

### ISSUE THREAD

**Issue by vishwasmehra** [tensorflow/tensorflow#26035]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: *Windows 10 Home*
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.12.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 9.2, cuDNN 7.4.1.5
- GPU model and memory: gtx 1050, 4gb DDR5
-Driver version: 398.35
-Laptop RAM: 8GB
-Platform : Anaconda3 64-bit for python 3.6

Below is the error that it keep on getting. I also looked for the solution that asked me to install Microsoft c++ redistributable 2015. After installing that as well the error persists.
*****
runfile('C:/Users/vishw/.spyder-py3/temp.py', wdir='C:/Users/vishw/.spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-1-5780f59638b8>", line 1, in <module>
    runfile('C:/Users/vishw/.spyder-py3/temp.py', wdir='C:/Users/vishw/.spyder-py3')

  File "C:\Users\vishw\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\vishw\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/vishw/.spyder-py3/temp.py", line 1, in <module>
    import tensorflow as tf

  File "C:\Users\vishw\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\Users\vishw\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\vishw\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\vishw\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\vishw\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\vishw\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\vishw\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\vishw\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors
*******
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I need a bit of help here. If you need more information about hardware so i am using MSI GF638RC with gtx1050 nvidia graphic card.

I ran a basic tensorflow code to print hello tensorflow to test. 

Thank you !

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
In addition to installing MSVC 2015 you also you have lower your cuda version to 9.0 since TF 1.12 come with pre-built binaries to support cuda 9.0 In addition to that you will have to set appropriate cuda, cudnn paths. Please refer this [windows setup](https://www.tensorflow.org/install/gpu#windows_setup) guide o this.

**Comment by vishwasmehra** [comment]
@ymodak I tried to install cuda 9.0 but it is showing me not compatible with your driver version. Should i go and still install it ?

**Comment by ymodak** [comment]
Yes that should be fine, CUDA 9.0 accepts 384.81 and higher Nvidia drivers.

**Comment by vishwasmehra** [comment]
Thanks the problem got resolved. Really appreciate it !!

**Comment by ymodak** [comment]
Awesome! I will close this issue now. Thanks!

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
