### ISSUE TITLE
Switching between TF 1.x and TF 2.0 in the API browser loses the context

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#26047]
**System information**
- TensorFlow version: from 
- Doc Link:

**Describe the documentation issue**
When I'm browsing the documentation, I often need to switch from TF 1.x to TF 2.0 or vice versa. Unfortunately, the context is lost when I do that.
For example, visit the `tf.constant` documentation for TF 2.0:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/constant
Then from the drop down menu at the top (labeled "API r2.0"), select any TF 1.x version. Notice that you do not land on the `tf.constant` page.
The same is true in the reverse direction.

This also makes it hard to find TF 2.0 documentation by searching: I generally land on a TF 1.x page, when I switch to TF 2.0 the context is lost.

Of course, many functions have been removed or moved, but this should not be a problem, since most of them are still available in `tf.compat.v1`.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
Why not, but I would need someone to point me to the code that handles this.

**Comment by ageron** [comment]
I just noticed that the context is lost whenever I switch to any other TF version, not just to/from TF 2.0. I think I recall that context used to be preserved (I may be wrong). I didn't notice it until now because I was usually only interested in the latest TF version, so I didn't need to switch often. Now I do, and I think as TF 2.0 usage grows, people are going to need to switch more often too.

**Comment by lamberta** [comment]
Hey Aurélien,
It's a good point and something we've discussed, but not prepared to invest the site infra in (at least at this time with the run-up to TF 2).
When TF 2 is out of preview and released, that will be the default experience for tensorflow.org. We will continue to host some older 1.x API docs, but for narrative docs, we will point users off to our [tensorflow/docs](https://github.com/tensorflow/docs) repo, which will contain the navigable markdown docs in a release branch.

**Comment by Saduf2019** [comment]
@ageron please confirm if you still face the issue

**Comment by Saduf2019** [comment]
Moving this to closed status as there is no response
