### ISSUE TITLE
Tensorflow r1.12 CPU-only build fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by Davide-sd** [tensorflow/tensorflow#26042]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Not yet installed, trying to build from source
- TensorFlow version: r1.12
- Python version: 2.7.15rc1
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

While bulding tensorflow r1.12 CPU only for Python 2.7, the build fails with the following error:

`ERROR: /home/davide/Downloads/tensorflow/tensorflow/python/estimator/api/BUILD:12:1: Executing genrule //tensorflow/python/estimator/api:estimator_python_api_gen failed (Exit 1)`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
git clone https://github.com/tensorflow/tensorflow.git 
cd tensorflow
git checkout r1.12
./configure
```

This is the configuration file (`.tf_configure.bazelrc`):

```
build --action_env PYTHON_BIN_PATH="/usr/bin/python"
build --action_env PYTHON_LIB_PATH="/usr/local/lib/python2.7/dist-packages"
build --python_path="/usr/bin/python"
build:ignite --define with_ignite_support=true
build:xla --define with_xla_support=true
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="0"
build --action_env TF_DOWNLOAD_CLANG="0"
build:opt --copt=-march=native
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
```

Because I'm using bazel 0.19.2, I opened the file .bazelrc and added at the beginning the command `import /home/davide/Downloads/tensorflow/tools/bazel.rc`

`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
ERROR: /home/davide/Downloads/tensorflow/tensorflow/python/estimator/api/BUILD:12:1: Executing genrule //tensorflow/python/estimator/api:estimator_python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/home/davide/.cache/bazel/_bazel_davide/621bc5cc8d05a8843bd67c8ac5065abd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/estimator/api/create_tensorflow.python.estimator_api_2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 510, in <module>
    main()
  File "/home/davide/.cache/bazel/_bazel_davide/621bc5cc8d05a8843bd67c8ac5065abd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/estimator/api/create_tensorflow.python.estimator_api_2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 503, in main
    importlib.import_module(args.package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/davide/.cache/bazel/_bazel_davide/621bc5cc8d05a8843bd67c8ac5065abd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/estimator/api/create_tensorflow.python.estimator_api_2.runfiles/org_tensorflow/tensorflow/python/estimator/__init__.py", line 25, in <module>
    import tensorflow.python.estimator.estimator_lib
  File "/home/davide/.cache/bazel/_bazel_davide/621bc5cc8d05a8843bd67c8ac5065abd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/estimator/api/create_tensorflow.python.estimator_api_2.runfiles/org_tensorflow/tensorflow/python/estimator/estimator_lib.py", line 22, in <module>
    from tensorflow.python.estimator.canned.baseline import BaselineClassifier
  File "/home/davide/.cache/bazel/_bazel_davide/621bc5cc8d05a8843bd67c8ac5065abd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/estimator/api/create_tensorflow.python.estimator_api_2.runfiles/org_tensorflow/tensorflow/python/estimator/canned/baseline.py", line 50, in <module>
    from tensorflow.python.estimator import estimator
ImportError: cannot import name estimator
tf.estimator package not installed.
tf.estimator package not installed.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8147.753s, Critical Path: 232.48s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 6805 processes: 6805 local.
FAILED: Build did NOT complete successfully
```

**Comment by freedomtan** [comment]
as shown in the error message
```
from tensorflow.python.estimator import estimator
ImportError: cannot import name estimator
tf.estimator package not installed.
tf.estimator package not installed.
```
You may want to either `pip install tensorflow-estimator==1.2.0` or `pip install tensorflow==1.2.0` before building your own version.

**Comment by Davide-sd** [comment]
Ok, I will try. In the meantime I have successfully build version 1.11 without installing `tensorflow-estimator==1.2.0` or `tensorflow==1.2.0`.

**Comment by ymodak** [comment]
@Davide-sd Is this still an issue? Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by andrewor14** [comment]
Just want to add that I ran into this exact same problem (installing 1.12 from source) with the same error. For me the issue was that I had previously pip installed tensorflow 1.13. The way I fixed it was simply `pip uninstall tensorflow` and `pip uninstall tensorflow-estimator`.
