### ISSUE TITLE
tensorflow 1.12.0 install package requires protobuf>=3.6.1 but comes with protobuf==3.6.0

### ISSUE THREAD

**Issue by zhuoyw** [tensorflow/tensorflow#26045]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

('v1.12.0-0-ga6d8ffae09', '1.12.0')

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

If you download the Python 2.7 CPU-only official whl file (following https://www.tensorflow.org/install/pip) https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp27-none-linux_x86_64.whl, you will see that it requires protobuf>=3.6.1.

However, after you extract it and see the include files, they are protobuf==3.6.0.

**Describe the expected behavior**

The protobuf version should be consistent.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

wget https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp27-none-linux_x86_64.whl
unzip tensorflow-1.12.0-cp27-none-linux_x86_64.whl
less tensorflow-1.12.0.dist-info/metadata.jsoin 
less tensorflow-1.12.0.data/purelib/tensorflow/include/google/protobuf/stubs/common.h

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gunan** [comment]
Ideally it should be consistent, but most packages are expected to be compatible between patch release versions.
Unless this is causing a breakage for you, this is not a problem.
