### ISSUE TITLE
Feature request: space_to_depth with overlapping blocks (like im2col)

### ISSUE THREAD

**Issue by dbbert** [tensorflow/tensorflow#2605]
Currently [tf.space_to_depth](https://www.tensorflow.org/versions/r0.7/api_docs/python/array_ops.html#space_to_depth) only works for rearranging non-overlapping blocks into depth. It would be nice if also worked for overlapping blocks, with an extra parameter to set the stride:
- A stride equal to the block size would be equivalent to the current non-overlapping behavior.
- A stride equal to 1 would be equivalent to an im2col operation.

An im2col-like operation could be used to easily implement a locally connected layer ("convolution with unshared weights"), by combining it with an elementwise multiplication with the matrix that contains the local filters, followed by a summation along the channel dimension.

**Comment by jyshee** [comment]
I tried to use[ tf.extract_image_patches](https://www.tensorflow.org/versions/r0.9/api_docs/python/array_ops.html#extract_image_patches) to implement a locally layer and run into an error:

LookupError: No gradient defined for operation 'local/ExtractImagePatches' (op type: ExtractImagePatches) 

I checked that  tf.space_to_depth has the gradient definition but  tf.extract_image_patches does not. And it seems not easy for me to implement the gradient. Any advice?

**Comment by bodokaiser** [comment]
@jyshee did you get this working?
