### ISSUE TITLE
tf-lite: allocateTensors never returns

### ISSUE THREAD

**Issue by BorisMansencal** [tensorflow/tensorflow#26060]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- I Have written custom code inspired from the tf-lite demo https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo. The code and model is here: https://github.com/BorisMansencal/tflite_test0
- OS Platform and Distribution: I build with up-to-date Android Studio 3.3.1 on macOS 10.13.6
- Mobile device: tested both on Nokia 7 Plus (TA-1046) with Android 9/API 28, and Motorola Moto G5S (XT1794) with Android 8.1.0/API 27.
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): I use tensorflow-lite:0.0.0-nightly

**Describe the current behavior**

My code uses tf-lite for image segmentation.
It works correctly on Nokia 7 Plus (TA-1046) with Android 9/API 28.
It does not work on Motorola Moto G5S (XT1794) with Android 8.1.0/API 27. 

**Describe the expected behavior**

My code is doing image segmentation using a U-Net DNN architecture.  
It is inspired from the the tf-lite demo example. It returns an image, instead of a classification.

The code is available here: https://github.com/BorisMansencal/tflite_test0
When run on on mobile device, you should see an image and a "run" button. You click on the "run" button and when the inference is finished, you should see an image : with white where the object was detected, black elsewhere.

It works correctly on Nokia 7 Plus (TA-1046) with Android 9/API 28, but not on Motorola Moto G5S (XT1794) with Android 8.1.0/API 27.

It should work on any device with API 26 Android version.

**Code to reproduce the issue**
https://github.com/BorisMansencal/tflite_test0

**Other info / logs**

When I run the application in the debugger, from Android Studio, on the Motorola Moto G5S , I can see that the call to the Interpreter constructor (called at ImageClassifier.java:59) never returns.
If I step into the Interpreter constructor, the problem seems to come from void NativeInterpreterWrapper::init(long errorHandle, long modelHandle, Options options): the call to allocateTensors(this.interpreterHandle, errorHandle) never returns.

**Comment by BorisMansencal** [comment]
I have also checked the same code on Motorola Moto G6 with Android 8.0.0/API 26, and I have the same issue.

**Comment by BorisMansencal** [comment]
I have updated the code on the repository to be able to use it on Android 7/API 24.
So far, I have the following results:

 | smartphone model | android version/API level | result |
 | -------------------- | -------------------- | ------------- |
 | Nokia 7 Plus (TA-1046) | Android 8.1/API 27 | OK |
 | Nokia 7 Plus (TA-1046) | Android 9/API 28 | OK |
 | Nokia 6.1 (TA-1043) | Android 9/API 28 | OK |
 | Samsung Galaxy S7 Edge | Android 7/API 24 | OK |
 | Motorola Moto G5S (XT1794) | Android 8.1/API 27 | **NOK** |
 | Motorola Moto G6 | Android 8.0/API 26 | **NOK** |

**Comment by aselle** [comment]
Sorry did you reach a resolution on this issue?

**Comment by mohantym** [comment]
Hi @BorisMansencal ! 
I could not find any issue with Android 8.1 ,  Pixel 4xl and TF 2.8 through Android Chipmunk. Could you let us know from your end.
Thank you!
