### ISSUE TITLE
Many operations don't support uint64

### ISSUE THREAD

**Issue by hjfreyer** [tensorflow/tensorflow#26069]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.14.2
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): b'unknown' 1.13.0-rc1
- Python version: Python 3.7.2
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

I've encountered several operations that support int64 but not uint64, without any clear reasoning. `tf.equal`, `tf.fill`, `tf.where`, and `tf.stack`, for example, give errors like:

    InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Pack' used by node stack (defined at <stdin>:4) with these attrs: [T=DT_UINT64, axis=0, N=2]

**Describe the expected behavior**

Functions that work for int64s should also work for uint64s when the behavior would be the same.

**Code to reproduce the issue**

https://gist.github.com/hjfreyer/31ab2dd2d85d1a509272af1c5e011dde
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by yongtang** [comment]
@hjfreyer Most of the operations in TF does not support uint64. There are some historical and reality reasons as far as I know. One is the binary size which could be really big if all signed and unsigned int (8/16/32/64) are enabled. Also, some integer types does not work on GPU for certain math operations yet. 

By default, `int8`, `uint8`, `int16`, `uint16`, `int32`, `int64` are supported for most of the ops. `uint32` and `uint64` are supported for `bitwise` ops additionally. There are also some ops that are merely memory/type manipulation (like `cast`) so `uint32` and `uint64` are supported as well.

From the list you provide, `tf.equal`, `tf.fill`, `tf.where`, and `tf.stack`, my guess is that they will not be supported, unless `uint32` and `uint64` are added to the default list and applies to almost all other ops.

This might take some time and might need guidance from api team I believe.

**Comment by karmel** [comment]
(For API owners) We can take a look when there is a specific proposal to review.

**Comment by csachs** [comment]
> @hjfreyer Most of the operations in TF does not support uint64. There are some historical and reality reasons as far as I know. One is the binary size which could be really big if all signed and unsigned int (8/16/32/64) are enabled. Also, some integer types does not work on GPU for certain math operations yet.
> 
> By default, `int8`, `uint8`, `int16`, `uint16`, `int32`, `int64` are supported for most of the ops. `uint32` and `uint64` are supported for `bitwise` ops additionally. There are also some ops that are merely memory/type manipulation (like `cast`) so `uint32` and `uint64` are supported as well.
> 
> From the list you provide, `tf.equal`, `tf.fill`, `tf.where`, and `tf.stack`, my guess is that they will not be supported, unless `uint32` and `uint64` are added to the default list and applies to almost all other ops.
> 
> This might take some time and might need guidance from api team I believe.

@yongtang is there some definitive list what is to be supported, or what shouldn't?
e.g. I just stumbled over the fact that for dtype `tf.uint16` operator == is not implemented … something I would file as a bug, however if it is `wontfix`, then this should be documented somewhere …

I just took a look at more combinations:
```python 
import tensorflow as tf
from tensorflow.python.framework.errors_impl import NotFoundError

dtypes = set([dtype for dtype in tf.dtypes.__dict__.values() if isinstance(dtype, tf.dtypes.DType)]) - {tf.resource, tf.variant}

for dtype in dtypes:
    a = tf.zeros(1, dtype=dtype)
    try:
        print(dtype, a == a)
    except NotFoundError:
        print(dtype, 'operator == not implemented')
```
```
> TF_CPP_MIN_LOG_LEVEL=3 python test.py
<dtype: 'float32'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'float64'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'int32'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'uint8'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'int16'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'int8'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'string'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'complex64'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'int64'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'bool'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'qint8'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'quint8'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'qint32'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'bfloat16'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'qint16'> operator == not implemented
<dtype: 'quint16'> operator == not implemented
<dtype: 'uint16'> operator == not implemented
<dtype: 'complex128'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'float16'> tf.Tensor([ True], shape=(1,), dtype=bool)
<dtype: 'uint32'> operator == not implemented
<dtype: 'uint64'> operator == not implemented
```

So `qint16`, `quint16`, `uint16`, `uint32`, `uint64` don't even have an equality operator implemented … that makes those datatypes very rudimentary.

**Comment by yongtang** [comment]
@csachs I added a PR #38288 for uint16, uint32, and uint64 for tf.math.equal and tf.math.not_equal.

**Comment by ravikyram** [comment]
@hjfreyer 

I am not seeing any issue with TF version ,1.15,2.x.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/d8387b0dd947a2537fd55d3aec87267f/untitled123.ipynb).Please,verify once and close the issue.Thanks!

**Comment by csachs** [comment]
@ravikyram 
The problems raised in my comment remain open.
Furthermore, there seems a regression, in earlier versions:
`tf.zeros(1, tf.qint16)` worked, now it doesn't.
Should I open another issue?

**Comment by yongtang** [comment]
@csachs The tf.zeros issue is being addressed in PR #41421 (tf.zeros uses FillOp implicitly).

**Comment by ravikyram** [comment]
@csachs 

The tf.zeros issue is being addressed in PR #41421 also got merged. Can you please verify once.Thanks!

**Comment by yongtang** [comment]
Added a PR #41795 to cover qint8/quint8/qint16/quint16 for `tf.math.[equal|not_equal]`.

**Comment by csachs** [comment]
> @csachs
> 
> The tf.zeros issue is being addressed in PR #41421 also got merged. Can you please verify once.Thanks!

Thank you @ravikyram , using version 2.4.0-dev20200728 , the `tf.zeros` issue is fixed.

However the larger code snippet above does not run (producing a new error); I guess it will resolve with https://github.com/tensorflow/tensorflow/pull/41795 .

**Comment by yongtang** [comment]
Most of the dtypes in https://github.com/tensorflow/tensorflow/issues/26069#issuecomment-604608722 are already supported now except for `tf.qint32` (with `tf.zeros`). Added a PR #46313 to add `tf.qint32` for `tf.zeros`.

**Comment by yongtang** [comment]
The support of tf.qint16 and tf.quint16 for tf.stack is being added in #46404

**Comment by rmothukuru** [comment]
@hjfreyer,
With @yongtang's PRs, many operations support uint64 now (**`Tensorflow Version 2.4.1`**). Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/4f4124c514714df8fe4456a3c589209f/gh_26069.ipynb) of the Working Code. Thanks!
