### ISSUE TITLE
skflow  multiple_gpu.py error

### ISSUE THREAD

**Issue by hrishikeshvganu** [tensorflow/tensorflow#2606]
When I execute python multiple_gpu.py I get following error. I have verified that my installation has cudnn v7 and cuda ( since I can run the translate.py example on gpu)

tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'logistic_regression/HistogramSummary_3/tag': Could not satisfy explicit device specification
 '/device:GPU:1' because no supported kernel for GPU devices is available
         [[Node: logistic_regression/HistogramSummary_3/tag = Const[dtype=DT_STRING, value=Tensor<type: string shape: [] values: logistic_regression.bias>, _device="/device:GPU:1"]()]]
Caused by op u'logistic_regression/HistogramSummary_3/tag', defined at:
  File "multiple_gpu.py", line 39, in <module>
    classifier.fit(X_train, y_train)
  File "/home/ubuntu/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 242, in fit

**Comment by ilblackdragon** [comment]
@vrv you worked on device assignment - what could lead to such error?

**Comment by vrv** [comment]
We don't support datatype string on GPUs, so something is assigning the HistogramSummary or related op on GPU when it shouldn't be.  Not sure without seeing the source code.

**Comment by ilblackdragon** [comment]
Code is here: https://github.com/tensorflow/tensorflow/blob/5a5a25ea3ebef623e07fb9a46419a9df377a37a5/tensorflow/examples/skflow/multiple_gpu.py

But I think problem is coming from:
```
with tf.device('/gpu:2'):
   ... some gpu computation ...
   tf.histogram(..)
   ... some more gpu computation ...
```

Either way, for this case we should just convert the test to the new `Estimator` that doesn't add automatic histograms.
