### ISSUE TITLE
 no such attribute 'downloaded_file_path' in 'http_file' rule

### ISSUE THREAD

**Issue by LuWei6896** [tensorflow/tensorflow#26073]
**System information**
- OS Platform and Distribution :Linux Ubuntu 16.04
- TensorFlow installed from :source code
- TensorFlow version:https://github.com/tensorflow/tensorflow
- Installed using bazel(bazel build tensorflow/cc:cc_ops):
- Bazel version (0.15.0):
- GCC/Compiler version (5.4.0):
**Describe the problem**
when i use bazel(bazel build tensorflow/cc:cc_ops) to buid the tensorflow source code from "https://github.com/tensorflow/tensorflow",there is some error as below:
WARNING: while reading option defaults file '/home/luwei/ML/tensorflow/tensorflow-master/.bazelrc':
  invalid command name 'try-import'.
WARNING: while reading option defaults file '/home/luwei/ML/tensorflow/tensorflow-master/.bazelrc':
  invalid command name 'try-import'.
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:101:9: //external:bazel_gpg: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:110:9: //external:docker_gpg: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:119:9: //external:gcloud_gpg: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:128:9: //external:launchpad_openjdk_gpg: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:138:9: //external:golang_release: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:147:9: //external:debian8_clang_release: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:155:9: //external:ubuntu16_04_clang_release: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:164:9: //external:debian8_libcxx_release: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:172:9: //external:ubuntu16_04_libcxx_release: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0141_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0150_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0152_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0161_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0171_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0172_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0180_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0181_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0190_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0192_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0200_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0210_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:196:9: //external:azul_open_jdk: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/luwei/.cache/bazel/_bazel_luwei/496db56b93dce7ae9ba21590959da509/external/bazel_toolchains/repositories/repositories.bzl:204:9: //external:azul_open_jdk_src: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.051s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build tensorflow/cc:cc_ops

**Any other info / logs**
  no!

**Comment by angersson** [comment]
You need a newer version of Bazel to build TensorFlow. Please follow the instructions at https://www.tensorflow.org/install/source: when you run the `./configure` script, it will tell you if your version of Bazel can be used to build TF (right now, the minimum version is `0.19.0`).
