### ISSUE TITLE
latest TensorBoard broken in Safari

### ISSUE THREAD

**Issue by goldsborough** [tensorflow/tensorflow#2607]
Since about a week now there seems something wrong with the TensorBoard demo at https://www.tensorflow.org/tensorboard/index.html#events. The graph shows nicely, but neither events nor histograms show up. This problem seems to be only with the demo -- everything shows up just fine when I run the corresponding code (`mnist_tensorboard.py`) locally.

**Comment by danmane** [comment]
It's working for me on both Chrome and Firefox. Can you provide some screenshots of how it looks on your machine, along with console output?

**Comment by danmane** [comment]
Also, please include info on what operating system + browser you are using.

**Comment by goldsborough** [comment]
I'm using Safari on OS X 10.11. I'm attaching screenshots below. It looks the same on Safari on iOS. I don't have any console output to show because I'm just referencing your own tensorboard demo that you're hosting at tensorflow.org. TensorBoard is working fine with that model when I run it locally, it's just this online demo of yours that seems to be broken.
![screen shot 2016-06-02 at 19 27 45](https://cloud.githubusercontent.com/assets/6429851/15754399/4aeb3676-28f8-11e6-8a82-5456dfbf17d8.png)
![screen shot 2016-06-02 at 19 28 09](https://cloud.githubusercontent.com/assets/6429851/15754400/4b0d1228-28f8-11e6-9b3e-43391b658e02.png)

**Comment by danmane** [comment]
OK, I've put in a fix upstream. Thanks for the report, otherwise the next release of TensorBoard would have been broken in Safari. 

Note, it may take several days before this change is reflected on the website.

**Comment by orome** [comment]
What do I need to do to install a version with this fix. Is an updated `.whl` available?

(I've installed `mac/tensorflow-0.9.0rc0-py2-none-any.whl`.)

**Comment by danmane** [comment]
We need https://github.com/tensorflow/tensorflow/pull/2786 to merge into 0.9 for 0.9 to be fixed.
Then, you can rebuild the .whl yourself using the build_pip_package script, or wait for us to publish an updated whl.
