### ISSUE TITLE
tf.spectral.dct length argument not implemented

### ISSUE THREAD

**Issue by doublejtoh** [tensorflow/tensorflow#26074]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
1.12.0
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
tf.spectral.dct has parameter "n" which is length of the transform. In https://github.com/tensorflow/tensorflow/blob/a68fec0c77a4c99d4306cd3e987b4f6f548a8112/tensorflow/python/ops/signal/dct_ops.py#L33~L34, It seems it is not implemented when it is not None. Is there any detailed plan to implement this?

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**

**Any Other info.**

**Comment by rryan** [comment]
I have no immediate plans to implement this (though it's been on my TODO list for a long time), and would welcome a community contribution to add it! The underlying RFFT op supports a length parameter so it should be fairly easy.

**Comment by kmh4321** [comment]
I can have a look at this if its open.

**Comment by kmh4321** [comment]
@rryan working on this issue and will raise a PR soon.

**Comment by kmh4321** [comment]
@rryan this issue can be closed as the above PR is approved.

**Comment by yongtang** [comment]
Close the issue as the PR has been merged.
