### ISSUE TITLE
Model Memory requirements

### ISSUE THREAD

**Issue by Geeks-Sid** [tensorflow/tensorflow#26070]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Want to print memory requirement of the model given a particular input size, batch size and a Structure of a model. It would cause Optimal GPU usage and also give a fair idea on what batch size should be.
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
Everyone who doesn't have a lot of compute and needs to know more specifics of the model
**Any Other info.**

**Comment by rmothukuru** [comment]
@Geeks-Sid,
Can you please let us know if [Tensorflow Profiler](https://www.tensorflow.org/guide/profiler) is what you are looking for? Thanks!

**Comment by Geeks-Sid** [comment]
Switched to torch in March 2019. Sorry for the issue.
