### ISSUE TITLE
Problem with keras implementation of Tensorflow

### ISSUE THREAD

**Issue by DHOFM** [tensorflow/tensorflow#26081]
Hi,
TF Version: b'v1.13.0-rc1-2-gb6141b06f5' 1.13.0-rc1

I have switched a keras implementation to tensorflow.keras. My intention is to give the TPUs a try. The original model trains on GPU. The tensorfow version cancels and shows a different model output: 

Original output is:

Model summary...
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                    
==================================================================================================
input_1 (InputLayer)            (None, 224, 224, 3)  0                                           
__________________________________________________________________________________________________
mobilenet_1.00_224 (Model)      (None, 7, 7, 1024)   3228864     input_1[0][0]                   
__________________________________________________________________________________________________
global_average_pooling2d_1 (Glo (None, 1024)         0           mobilenet_1.00_224[1][0]        
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 1024)         0           global_average_pooling2d_1[0][0]
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 1024)         1049600     dropout_1[0][0]                 
__________________________________________________________________________________________________
gender (Dense)                  (None, 2)            2050        dense_1[0][0]                   
__________________________________________________________________________________________________
age (Dense)                     (None, 21)           21525       dense_1[0][0]                   
==================================================================================================
Total params: 4,302,039
Trainable params: 4,280,151
Non-trainable params: 21,888

**Tensorflow Keras Version is:**

Model summary...
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                    
==================================================================================================
input_1 (InputLayer)            (None, 224, 224, 3)  0                                           
__________________________________________________________________________________________________
mobilenet_1.00_224 (Model)      (None, 7, 7, 1024)   3228864     input_1[0][0]                   
__________________________________________________________________________________________________
global_average_pooling2d (Globa (None, 1024)         0           mobilenet_1.00_224[1][0]        
__________________________________________________________________________________________________
dropout (Dropout)               (None, 1024)         0           global_average_pooling2d[0][0]  
__________________________________________________________________________________________________
dense (Dense)                   (None, 1024)         1049600     dropout[0][0]                   
__________________________________________________________________________________________________
gender (Dense)                  (None, 2)            2050        dense[0][0]                     
__________________________________________________________________________________________________
age (Dense)                     (None, 21)           21525       dense[0][0]                     
==================================================================================================
Total params: 4,302,039
Trainable params: 4,280,151
Non-trainable params: 21,888
_____________________________________________________________
 

What I see is the missing _1 in dropout, dense and so on. 

This results in the following error when trying to train:
ValueError: Output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: [{'input_1':...

Kind regards,

Dirk

**Comment by ymodak** [comment]
You can execute your model correctly using GPU however it fails on TPU. Is my interpretation correct on this? Also in order to expedite the trouble-shooting process, can you please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by DHOFM** [comment]
@ymodak Thanks. No the TPU is not the problem. The problem is the Keras implementation of tensor flow. I need to use tf.keras because of the TPU, but training also fails using tf.keras on a GPU. The only difference I see is the _1 and so on in the layers, so keras starts with _1, tf. keras starts without _x But i do not think that this is the problem, I have plotted both models for better understanding.
The code is derived from https://github.com/KinarR/age-gender-estimator-keras
I wanted to give several implementations for a gender estimator a try (keras, tensor flow native) and so on, because I am evaluating this at the moment. My Changes are: Changing all Keras to tensorflow.keras. Assuming "image_dim_ordering = 'tf'" in MobileNetDeepEstimator because we are on tensorflow. And of course the tpu stuff. So the model is build in 

`class MobileNetDeepEstimator:
    def __init__(self, image_size, alpha, num_neu, weights=None):

        """if K.image_dim_ordering() == "th":
            logging.debug("image_dim_ordering = 'th'")
            self._channel_axis = 1
            self._input_shape = (3, image_size, image_size)
        else:"""
        if (1==1):
            logging.debug("image_dim_ordering = 'tf'")
            self._channel_axis = -1
            self._input_shape = (image_size, image_size, 3)
            self.alpha = alpha
            self.num_neu = num_neu
            self.weights = weights
            self.FC_LAYER_SIZE = 1024

    def __call__(self):
        logging.debug("Creating model...")

        inputs = Input(shape=self._input_shape)
        model_mobilenet = MobileNet(input_shape=self._input_shape, alpha=self.alpha, depth_multiplier=1, dropout=1e-3,
                                    include_top=False, weights=self.weights, input_tensor=None, pooling=None)

        x = model_mobilenet(inputs)

        feat_a = GlobalAveragePooling2D()(x)
        feat_a = Dropout(0.5)(feat_a)
        feat_a = Dense(self.FC_LAYER_SIZE, activation="relu")(feat_a)

        pred_g_softmax = Dense(2, activation='softmax', name='gender')(feat_a)
        pred_a_softmax = Dense(self.num_neu, activation='softmax', name='age')(feat_a)

        model = Model(inputs=inputs, outputs=[pred_g_softmax, pred_a_softmax])

        return model`

and compiled to

`pu_model = tf.contrib.tpu.keras_to_tpu_model(
    model,
    strategy=tf.contrib.tpu.TPUDistributionStrategy(
        tf.contrib.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
        #tf.contrib.cluster_resolver.TPUClusterResolver(tpu='grpc://10.46.4.42:8470')
    )
    )

    tpu_model.compile(
        optimizer=tf.keras.optimizers.SGD(lr=0.001,),
        loss=tf.keras.losses.sparse_categorical_crossentropy,
        metrics={'gender': 'accuracy',
                 'age': 'accuracy'},
    )`

**Comment by DHOFM** [comment]
And these are the models Keras is the original on, tfkeras is the one, that won't work (tf.keras implementation)
![kerasmodel_plot](https://user-images.githubusercontent.com/27775323/53403892-ce53b680-39b4-11e9-91d3-e7ac299e2511.png)
![tfkerasmodel_plot](https://user-images.githubusercontent.com/27775323/53403907-d3b10100-39b4-11e9-81d3-a5a2388ad709.png)

**Comment by DHOFM** [comment]
**tf.keras:**

![tfkerasmodel_plot](https://user-images.githubusercontent.com/27775323/53403907-d3b10100-39b4-11e9-81d3-a5a2388ad709.png)

**Comment by DHOFM** [comment]
I've done some more investigation and tested tf.keras and keras in an virtualenv on my Mac. I can reproduce the behavior. The trining works with keras while tf.keras throws the exception. It seems to be a problem with the generator. The generator is used like this:

```
hist = tpu_model.fit_generator(
        image_generator.flow(mode='train'),
        steps_per_epoch=int(len(train_keys) / batch_size),
        epochs=nb_epochs,
        callbacks=callbacks,
        validation_data=image_generator.flow('val'),
        validation_steps=int(len(val_keys) / batch_size)
    )

```

and the image_generator:

```
image_generator = ImageGenerator(ground_truth_data, batch_size,
                                     input_shape[:2],
                                     train_keys, val_keys,
                                     path_prefix=images_path,
                                     vertical_flip_probability=0
                                     )
 class ImageGenerator(object):
...

def flow(self, mode='train'):
        while True:
            if mode == 'train':
                logging.debug('alive...')
                shuffle(self.train_keys)
                keys = self.train_keys
            elif mode == 'val' or mode == 'demo':
                shuffle(self.validation_keys)
                keys = self.validation_keys
            else:
                raise Exception('invalid mode: %s' % mode)

            inputs = []
            targets = []
            for key in keys:
                image_path = self.path_prefix + key
                image_array = imread(image_path)
                image_array = imresize(image_array, self.image_size)

                num_image_channels = len(image_array.shape)
                if num_image_channels != 3:
                    continue

                ground_truth = self.ground_truth_data[key]

                image_array = image_array.astype('float32')
                if mode == 'train' or mode == 'demo':
                    image_array = self.transform(image_array)[0]

                if self.grayscale:
                    image_array = cv2.cvtColor(image_array.astype('uint8'),
                                               cv2.COLOR_RGB2GRAY).astype('float32')
                    image_array = np.expand_dims(image_array, -1)

                inputs.append(image_array)
                targets.append(ground_truth)
                if len(targets) == self.batch_size:
                    inputs = np.asarray(inputs)
                    targets = np.asarray(targets)

                    gender = np_utils.to_categorical(targets[:, 0], 2)
                    # Quantizing the age

                    age_bins = np.linspace(0, 100, 21)
                    age_step = np.digitize(targets[:, 1], age_bins)
                    age_quantized = np_utils.to_categorical(age_step, 21)

                    if mode == 'train' or mode == 'val':
                        inputs = self.preprocess_images(inputs)
                        yield self._wrap_in_dictionary(inputs, gender, age_quantized)
                    if mode == 'demo':
                        yield self._wrap_in_dictionary(inputs, gender, age_quantized)
                    inputs = []
                    targets = []
```

So the exception as mentioned above is:

> Output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: [{'input_1': array([[[[-0.79948485, -0.8227509 , -0.85790277],          [-0.79948485, -0.8227509 , -0.85790277],          [-0.79064566, -0.81391174, -0.84906363],          ...,          [-0.7384317 , -0.7693655 , -0.8045173 ],          [-0.7384317 , -0.7693655 , -0.8045173 ],          [-0.7384317 , -0.7693655 , -0.8045173 ]],          [[-0.79948485, -0.8227509 , -0.85790277],          [-0.79948485, -0.8227509 , -0.85790277],          [-0.79064566, -0.81391174, -0.84906363],          ...,          [-0.7384317 , -0.7693655 , -0.8045173 ],          [-0.7384317 , -0.7693655 , -0.8045173 ],          [-0.7384317 , -0.7693655 , -0.8045173 ]],          [[-0.79948485, -0.8227509 , -0.85790277],          [-0.79948485, -0.8227509 , -0.85790277],          [-0.79064566, -0.81391174, -0.84906363],          ...,          [-0.7384317 , -0.7693655 , -0.8045173 ],          [-0.7384317 , -0.7693655 , -0.8045173 ],          [-0.7384317 , -0.7693655 , -0.8045173 ]],          ...,          [[-0.32190108, -0.34516716, -0.3649835 ],          [-0.32190108, -0.34516716, -0.3649835 ],          [-0.3130619 , -0.33632797, -0.35614425],          ...,          [ 0.18057775,  0.14964402,  0.09915662],          [ 0.189417  ,  0.15848315,  0.10799599],          [ 0.189417  ,  0.15848315,  0.10799599]],          [[-0.32190108, -0.34516716, -0.3649835 ],          [-0.32190108, -0.34516716, -0.3649835 ],          [-0.3130619 , -0.33632797, -0.35614425],          ...,          [ 0.22477376,  0.19384003,  0.14335251],          [ 0.23361301,  0.20267916,  0.15219176],          [ 0.23361301,  0.20267916,  0.15219176]],          [[-0.32190108, -0.34516716, -0.3649835 ],          [-0.32190108, -0.34516716, -0.3649835 ],          [-0.3130619 , -0.33632797, -0.35614425],          ...,          [ 0.24245238,  0.2115184 ,  0.16103113],          [ 0.2512914 ,  0.22035766,  0.16987014],          [ 0.2512914 ,  0.22035766,  0.16987014]]],          [[[ 0.11772168,  0.13635767,  0.1170119 ],          [ 0.11052775,  0.12916386,  0.1098181 ],          [ 0.11052775,  0.12916386,  0.1098181 ],          ...,          [ 0.36219227,  0.38082862,  0.3481512 ],          [ 0.35499847,  0.3736347 ,  0.34095728],          [ 0.35499847,  0.3736347 ,  0.34095728]],          [[ 0.11772168,  0.13635767,  0.1170119 ],          [ 0.11052775,  0.12916386,  0.1098181 ],          [ 0.11052775,  0.12916386,  0.1098181 ],          ...,          [ 0.35499847,  0.3736347 ,  0.34095728],          [ 0.35499847,  0.3736347 ,  0.34095728],          [ 0.35499847,  0.3736347 ,  0.34095728]],          [[ 0.11052775,  0.12916386,  0.1098181 ],          [ 0.11052775,  0.12916386,  0.1098181 ],          [ 0.11052775,  0.12916386,  0.1098181 ],          ...,          [ 0.35499847,  0.3736347 ,  0.34095728],          [ 0.35499847,  0.3736347 ,  0.34095728],          [ 0.35499847,  0.3736347 ,  0.34095728]],          ...,          [[ 0.22574973,  0.24438608,  0.23837173],          [ 0.22574973,  0.24438608,  0.23837173],          [ 0.23294365,  0.25158   ,  0.24556577],          ...,          [-0.5251232 , -0.5531473 , -0.5724931 ],          [-0.5251232 , -0.5531473 , -0.5724931 ],          [-0.5179293 , -0.54595345, -0.5652993 ]],          [[ 0.23294365,  0.25158   ,  0.24556577],          [ 0.23294365,  0.25158   ,  0.24556577],          [ 0.23294365,  0.25158   ,  0.24556577],          ...,          [-0.5251232 , -0.5531473 , -0.5724931 ],          [-0.5251232 , -0.5531473 , -0.5724931 ],          [-0.5251232 , -0.5531473 , -0.5724931 ]],          [[ 0.23294365,  0.25158   ,  0.24556577],          [ 0.23294365,  0.25158   ,  0.24556577],          [ 0.23294365,  0.25158   ,  0.24556577],          ...,          [-0.5179293 , -0.54595345, -0.5652993 ],          [-0.5251232 , -0.5531473 , -0.5724931 ],          [-0.5251232 , -0.5531473 , -0.5724931 ]]],          [[[-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          ...,          [-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ]],          [[-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          ...,          [-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ]],          [[-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          ...,          [-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ]],          ...,          [[-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          ...,          [-0.87843734, -0.8746458 , -0.8314029 ],          [-0.9052509 , -0.90145934, -0.85821646],          [-0.9320644 , -0.9282729 , -0.88503003]],          [[-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          ...,          [-0.90702516, -0.8872958 , -0.84405285],          [-0.9338387 , -0.91410935, -0.8708664 ],          [-0.9454712 , -0.9416797 , -0.8984368 ]],          [[-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          [-1.        , -1.        , -1.        ],          ...,          [-0.920432  , -0.9007026 , -0.85745966],          [-0.94724554, -0.9275161 , -0.88427323],          [-0.9606523 , -0.9409229 , -0.89768   ]]],          ...,          [[[ 0.03327799,  0.30924726,  0.528203  ],          [ 0.03327799,  0.30924726,  0.528203  ],          [ 0.03327799,  0.30924726,  0.528203  ],          ...,          [ 0.0780406 ,  0.39597082,  0.528203  ],          [ 0.0780406 ,  0.39597082,  0.528203  ],          [ 0.0780406 ,  0.39597082,  0.528203  ]],          [[ 0.03327799,  0.30924726,  0.528203  ],          [ 0.03327799,  0.30924726,  0.528203  ],          [ 0.03327799,  0.30924726,  0.528203  ],          ...,          [ 0.08412147,  0.40205193,  0.528203  ],          [ 0.08412147,  0.40205193,  0.528203  ],          [ 0.08412147,  0.40205193,  0.528203  ]],          [[ 0.03327799,  0.30924726,  0.528203  ],          [ 0.03327799,  0.30924726,  0.528203  ],          [ 0.03327799,  0.30924726,  0.528203  ],          ...,          [ 0.12301791,  0.43255615,  0.528203  ],          [ 0.12301791,  0.43255615,  0.528203  ],          [ 0.12301791,  0.43255615,  0.528203  ]],          ...,          [[-0.53515565, -0.5277369 , -0.3423922 ],          [-0.50475085, -0.49733198, -0.31198746],          [-0.48042697, -0.47300816, -0.28766358],          ...,          [-0.9477527 , -0.83962744, -0.7214205 ],          [-0.9173479 , -0.8092226 , -0.6910157 ],          [-0.893024  , -0.78489876, -0.66669184]],          [[-0.5290747 , -0.5216558 , -0.33631128],          [-0.49258888, -0.48517007, -0.2998255 ],          [-0.5169128 , -0.50949395, -0.3241493 ],          ...,          [-0.94315565, -0.86020696, -0.7336079 ],          [-0.9188318 , -0.83588314, -0.709284  ],          [-0.88842696, -0.80547833, -0.67887914]],          [[-0.52299374, -0.51557493, -0.33023036],          [-0.468265  , -0.4608462 , -0.2755016 ],          [-0.53515565, -0.5277369 , -0.3423922 ],          ...,          [-0.9619255 , -0.8789769 , -0.7355933 ],          [-0.9370747 , -0.85412604, -0.7275269 ],          [-0.91275084, -0.82980216, -0.703203  ]]],          [[[ 0.7429316 ,  0.6751132 ,  0.5103228 ],          [ 0.7535478 ,  0.7189033 ,  0.55411303],          [ 0.7535478 ,  0.7516738 ,  0.62709653],          ...,          [ 0.25413465,  0.1983062 , -0.03242844],          [ 0.16746819,  0.11763465, -0.11310005],          [ 0.11637974,  0.06654608, -0.16418856]],          [[ 0.6699481 ,  0.6021297 ,  0.4373393 ],          [ 0.7137382 ,  0.6459197 ,  0.48112953],          [ 0.7535478 ,  0.72620165,  0.56141126],          ...,          [ 0.2542832 ,  0.19845474, -0.02628493],          [ 0.18859804,  0.13276958, -0.09197009],          [ 0.14557302,  0.09573948, -0.13499516]],          [[ 0.5458759 ,  0.47805762,  0.31326723],          [ 0.6042627 ,  0.5364444 ,  0.37165403],          [ 0.6991414 ,  0.6313231 ,  0.4665327 ],          ...,          [ 0.26081645,  0.19899309, -0.01975167],          [ 0.21779156,  0.16196299, -0.06277668],          [ 0.18936312,  0.13952959, -0.091205  ]],          ...,          [[-0.03483921, -0.22855121, -0.37535673],          [-0.04943597, -0.24314797, -0.3899535 ],          [-0.07133102, -0.26504302, -0.41184855],          ...,          [-0.0747655 , -0.08862936, -0.00762731],          [-0.0747655 , -0.08862936, -0.00762731],          [-0.0747655 , -0.08862936, -0.00762731]],          [[-0.03483921, -0.22855121, -0.37535673],          [-0.04943597, -0.24314797, -0.3899535 ],          [-0.07133102, -0.26504302, -0.41184855],          ...,          [-0.11125726, -0.12512118, -0.04411906],          [-0.11855567, -0.13241953, -0.05141747],          [-0.11855567, -0.13241953, -0.05141747]],          [[-0.03483921, -0.22855121, -0.37535673],          [-0.04943597, -0.24314797, -0.3899535 ],          [-0.07133102, -0.26504302, -0.41184855],          ...,          [-0.1331523 , -0.14701623, -0.06601417],          [-0.14045072, -0.15431458, -0.07331252],          [-0.147749  , -0.16161293, -0.08061087]]],          [[[-0.89266884, -0.9059861 , -0.91916364],          [-0.89266884, -0.9059861 , -0.91916364],          [-0.89266884, -0.9059861 , -0.91916364],          ...,          [-0.89266884, -0.9059861 , -0.91916364],          [-0.89266884, -0.9059861 , -0.91916364],          [-0.89266884, -0.9059861 , -0.91916364]],          [[-0.89266884, -0.9059861 , -0.91916364],          [-0.89266884, -0.9059861 , -0.91916364],          [-0.89266884, -0.9059861 , -0.91916364],          ...,          [-0.89266884, -0.9059861 , -0.91916364],          [-0.89266884, -0.9059861 , -0.91916364],          [-0.89266884, -0.9059861 , -0.91916364]],          [[-0.89266884, -0.9059861 , -0.91916364],          [-0.89266884, -0.9059861 , -0.91916364],          [-0.89266884, -0.9059861 , -0.91916364],          ...,          [-0.89266884, -0.9059861 , -0.91916364],          [-0.89266884, -0.9059861 , -0.91916364],          [-0.89266884, -0.9059861 , -0.91916364]],          ...,          [[-0.8745992 , -0.9059861 , -0.91916364],          [-0.8745992 , -0.9059861 , -0.91916364],          [-0.8745992 , -0.9059861 , -0.91916364],          ...,          [ 0.71699464,  0.45771182,  0.22694933],          [ 0.71699464,  0.45771182,  0.22694933],          [ 0.71699464,  0.45771182,  0.22694933]],          [[-0.79437065, -0.83606863, -0.91916364],          [-0.79462796, -0.8457861 , -0.91916364],          [-0.794566  , -0.8457241 , -0.91916364],          ...,          [ 0.7069906 ,  0.44770753,  0.21694505],          [ 0.7069906 ,  0.44770753,  0.21694505],          [ 0.7069906 ,  0.44770753,  0.21694505]],          [[-0.7443499 , -0.7860478 , -0.91916364],          [-0.7446072 , -0.79576534, -0.91916364],          [-0.74454516, -0.79570335, -0.91916364],          ...,          [ 0.74700713,  0.4877243 ,  0.2569617 ],          [ 0.74700713,  0.4877243 ,  0.2569617 ],          [ 0.74700713,  0.4877243 ,  0.2569617 ]]]], dtype=float32)}, {'gender': array([[1., 0.],        [0., 1.],        [0., 1.],        [1., 0.],        [1., 0.],        [1., 0.],        [0., 1.],        [1., 0.],        [0., 1.],        [1., 0.],        [0., 1.],        [1., 0.],        [1., 0.],        [1., 0.],        [1., 0.],        [1., 0.],        [1., 0.],        [1., 0.],        [0., 1.],        [1., 0.],        [0., 1.],        [1., 0.],        [1., 0.],        [0., 1.],        [1., 0.],        [0., 1.],        [0., 1.],        [1., 0.],        [0., 1.],        [0., 1.],        [0., 1.],        [1., 0.]], dtype=float32), 'age': array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 1., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.],        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,         0., 0., 0., 0., 0.]], dtype=float32)}]

**Comment by DHOFM** [comment]
so now I tested if the generator generates a tuple and voila it does not:

```
zzn = next(image_generator.flow(mode='train'))
    if not isinstance(zzn, tuple):
        logging.debug("error generator tuple")

```

So the exception seems to be correct. But Keras has no problem with this. The exception is thrown in tensorflow/python/keras/engine/training_generator.py

Is there a different behavior between tf.keras and keras regarding the training generator?

**Comment by DHOFM** [comment]
So changing the generator to generate tuples with
`yield tuple(self._wrap_in_dictionary(inputs, gender, age_quantized))`

solves the problem, but I suggest that Keras implementation will find its way to tensorflow, so we get more flexibility(!)

Now I get a new exception in this case its a TPU Problem (the code works without tpu now):

> RuntimeError: Compilation failed: Compilation failure: Detected unsupported operations when trying 

> to compile graph cluster_15366487156777984482[] on XLA_TPU_JIT: Placeholder (No registered 'Placeholder' OpKernel for XLA_TPU_JIT devices compatible with node {{node tpu_139872799811176/input_2}}
> 	.  Registered:  device='TPU'
>   device='CPU'
>   device='GPU'
>   device='XLA_CPU'
> ){{node tpu_139872799811176/input_2}}

**Comment by ymodak** [comment]
@DHOFM Thanks for the thorough investigation. Now that you have filed a new issue explaining the newly discovered error, can we close this thread and track it there.

**Comment by DHOFM** [comment]
@ymodak Yes this thread can be closed. Should I open a feature requester my suggestion that Keras implementation will find its way to tensorflow, so we get more flexibility ??

**Comment by ymodak** [comment]
Yes, please post a feature request explaining the same. Thanks!
