### ISSUE TITLE
Changes within the base SSD mobilenet v1 structure

### ISSUE THREAD

**Issue by kamauz** [tensorflow/tensorflow#26087]
I have to import the ssd_mobilenetv1_coco_2018 pretrained model inside PyTorch so I have to manage the specific chosen architecture in the code. I noticed that the first layers of the classification/box prediction have less output than the others (12 instead of 24). 
Isn't it a standard implementation?
Does this involve directly the number of anchors that will be built?

Thanks

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
