### ISSUE TITLE
tf.one_hot crashes when indices is tf.uint8

### ISSUE THREAD

**Issue by elmirador** [tensorflow/tensorflow#26099]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 / Windows 7
- TensorFlow installed from (source or binary): Official pip source (tensorflow-gpu)
- TensorFlow version (use command below): 1.12.0
- Python version: 3.6
- CUDA/cuDNN version: 9.0 / 7.5
- GPU model and memory: 1080Ti / 12GB

**Describe the current behavior**
tf.one_hot crashes when the indices tensor has dtype=tf.uint8
The error message shows `Check failed: new_num_elements == NumElements()`

**Code to reproduce the issue**
https://gist.github.com/elmirador/4fc5148e5044478d668237209d265eac

**Other info / logs**
I've also tested under TF 1.4.1 and TF 1.10.0 (both on GPU) on different machines, both have the same problem.

**Comment by bono1567** [comment]
Hello, I am new to the tensorflow community and which going thorugh the code I couldn't find gen_array_ops. If possible I would like to contribute to the issue.

**Comment by elmirador** [comment]
> Hello, I am new to the tensorflow community and which going thorugh the code I couldn't find gen_array_ops. If possible I would like to contribute to the issue.

`gen_array_ops.py` is located under `tensorflow/python/ops/`.
You can't find it on github because `gen_array_ops` is generated during building.
Basically it's a wrapper around the underlying C++ code of tensorflow. If you're interested, the C++ code of one_hot ops is located at 'tensorflow/core/kernels/one_hot_op.cc'.

**Comment by annarev** [comment]
@bono1567 Don't know if you had a chance to look into it and thank you for your interest!
Since you haven't posted an update for a while and I just looked into it, I will submit a fix now.
