### ISSUE TITLE
sorry, unimplemented: non-trivial designated initializers not supported

### ISSUE THREAD

**Issue by herbakamil** [tensorflow/tensorflow#26093]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
-  OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: commit a2bb5db1bf7931b0dc2cd08e53b8798489568198
- Python version: 2.7.15rc1
- Installed using virtualenv? pip? conda?: sources
- Bazel version (if compiling from source): 0.20.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**
During compilation I get an error: sorry, unimplemented: non-trivial designated initializers not supported.
It can be solved by setting all function pointers to null and applying initialization in order as in the struct defintion.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel test --verbose_failures tensorflow/lite/delegates/nnapi:nnapi_delegate

**Any other info / logs**
I attach diff which fixes this error for me.
[diff.txt](https://github.com/tensorflow/tensorflow/files/2901455/diff.txt)

**Comment by herbakamil** [comment]
@jdduke do you use at Google some internal compilers which behave differently from gcc on officially provided TF Docker images? That would explain why it passes within Google CI and it fails on TF docker image.

**Comment by jdduke** [comment]
Our internal compiler version is different than that used in our Docker builds, yes. Feel free to propose a PR and I'd be happy to approve. Could you confirm which NDK version is used in the Docker builds?

**Comment by herbakamil** [comment]
I think there's no NDK in the Tensorflow docker image
