### ISSUE TITLE
Warnings raised for deprecated collections.abc usage.

### ISSUE THREAD

**Issue by NeilGirdhar** [tensorflow/tensorflow#26095]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): b'v1.13.0-rc1-0-g63c13ff' 1.13.0-rc1
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: irrelevant

**Describe the current behavior**
TensorFlows raises warnings like:
```
jumping/simulation/test/test_simulation.py::test_gpu_inference[Device.tensorflow]
  /home/neil/.pyenv/versions/3.7.0/lib/python3.7/site-packages/tensorflow/python/util/nest.py:823: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    _pywrap_tensorflow.RegisterType("Mapping", _collections.Mapping)

jumping/simulation/test/test_simulation.py::test_gpu_inference[Device.tensorflow]
  /home/neil/.pyenv/versions/3.7.0/lib/python3.7/site-packages/tensorflow/python/util/nest.py:824: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    _pywrap_tensorflow.RegisterType("Sequence", _collections.Sequence)

jumping/simulation/test/test_simulation.py::test_gpu_inference[Device.tensorflow]
  /home/neil/.pyenv/versions/3.7.0/lib/python3.7/site-packages/tensorflow/python/training/checkpointable/util.py:448: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

```
**Describe the expected behavior**
These warnings should not be raised.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import warnings
warnings.simplefilter("error")
import tensorflow
```

**Other info / logs**
I can do this if the patch will be accepted.

**Comment by jvishnuvardhan** [comment]
@NeilGirdhar Could you try the solution provided [here](https://stackoverflow.com/questions/35911252/disable-tensorflow-debugging-information) to disable warnings, errors etc. If that was not solving, please provide a code to reproduce the issue. Thanks!

**Comment by NeilGirdhar** [comment]
@jvishnuvardhan What does the tensorflow log level have to do with anything?  The warnings I'm talking about are raise by Python.  The problem is that tensorflow needs to fix its imports.

**Comment by gunan** [comment]
For 1.13, the branch is blosed unless we have security issues. BUt I am happy to accept this patch for master.
