### ISSUE TITLE
[TF 2.0] optimizer_v2.get_updates() eager mode problem

### ISSUE THREAD

**Issue by danaugrs** [tensorflow/tensorflow#26098]
**TF Version: 2.0.0-dev20190214
Windows 10
Anaconda Python 3.6.5
GPU: GeForce GTX 1070 Max-Q Design
[Tensorflow 2.0 (gpu) nightly](https://pypi.org/project/tf-nightly-gpu-2.0-preview/) installed via pip.**

**Describe the current behavior**
Calling [`<AnyOptimizerV2>.get_updates(params=my_model.trainable_weights, loss=my_loss)`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L447) fails with any `my_loss` (due to eager mode being on):

```
    actor_updates = self.optimizer_actor.get_updates(params=self.actor.trainable_weights, loss=None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py", line 448, in get_updates
    grads = self.get_gradients(loss, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py", line 361, in get_gradients
    grads = gradients.gradients(loss, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 547, in _GradientsHelper
    raise RuntimeError("tf.gradients is not supported when eager execution "
RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.
```
Globally disabling eager execution via `tf.compat.v1.disable_eager_execution()` fixes this particular issue but I don't want to globally disable eager mode! I'd like to know how the 2.0 API is intended to be used in this case.

**Describe the expected behavior**
Since the gradient computation is happening internally I expected behavior similar to TF1 i.e. computation of gradients in graph mode in this case. Also I don't want to use `tf.GradientTape` every time I want to compute the gradient instances - instead I want to obtain the update ops so they can be passed to a [`tf.keras.backend.function`](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/backend/function) which can then be executed on demand to compute and apply the gradients. For more context please see [here](https://stackoverflow.com/questions/54856829/tensorflow-2-0-tf-keras-api-eager-mode-vs-graph-mode).

**Code to reproduce the issue**
```
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dense

my_model = Sequential([Dense(1, activation='relu', input_shape=(5,))])
my_loss = -tf.reduce_mean(my_model.output)
my_optim = Adam()
updates = my_optim.get_updates(params=my_model.trainable_weights, loss=my_loss)
```
Edit: this has also been noticed here: https://github.com/tensorflow/tensorflow/issues/25472

**Comment by danaugrs** [comment]
@alextp I removed [the check for eager mode](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/gradients_util.py#L557-L559) as you suggested but then it fails shortly after:

```
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 600, in <listcomp>
    from_ops = [t.op for t in xs]
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 934, in op
    "Tensor.op is meaningless when eager execution is enabled.")
```

Any ideas?

**Comment by alextp** [comment]
Ah, so it's a little more complex than that. I think a better fix is done inside keras proper by entering the keras graph before keras calls tf.gradients, in get_updates. @robieta do you know what the best place to do this is?

**Comment by danaugrs** [comment]
I made [a pull request](https://github.com/tensorflow/tensorflow/pull/26142) that seems to fix this issue but then the next line in my code fails - it attempts to use the computed updates inside a `tf.keras.backend.function`. Both lines are shown below (the first one now works with the PR).
```
actor_updates = self.optimizer_actor.get_updates(params=self.actor.trainable_weights, loss=vv)
self.actor_train_on_batch = tf.keras.backend.function(inputs=[state_input], outputs=[self.actor(state_input)], updates=actor_updates)
```
The stack trace:
```
  self.actor_train_on_batch = tf.keras.backend.function(inputs=[state_input], outputs=[self.actor(state_input)], updates=actor_updates)
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 3235, in function
  return EagerExecutionFunction(inputs, outputs, updates=updates, name=name)
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 3156, in __init__
  add_sources=True, handle_captures=True, base_graph=source_graph)
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\lift_to_graph.py", line 222, in lift_to_graph
  add_sources=add_sources))
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\lift_to_graph.py", line 87, in _map_subgraph
  elif op.type == "Placeholder":
```

**Comment by alextp** [comment]
Can you post the full stack trace? Something fishy seems to be going on here.

@robieta I think you wrote the exception-raising code, so reassigning this issue to you.

**Comment by danaugrs** [comment]
```
Traceback (most recent call last):
  File "C:/projects/huskarl/examples/ddpg-pendulum.py", line 37, in <module>
    agent = hk.agent.DDPG(actor=actor, critic=critic, nsteps=2)
  File "C:\projects\huskarl\huskarl\agent\ddpg.py", line 56, in __init__
    self.actor_train_on_batch = tf.keras.backend.function(inputs=[state_input], outputs=[self.actor(state_input)], updates=actor_updates)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 3235, in function
    return EagerExecutionFunction(inputs, outputs, updates=updates, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 3156, in __init__
    add_sources=True, handle_captures=True, base_graph=source_graph)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\lift_to_graph.py", line 222, in lift_to_graph
    add_sources=add_sources))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\lift_to_graph.py", line 87, in _map_subgraph
    elif op.type == "Placeholder":
AttributeError: 'NoneType' object has no attribute 'type'
```

**Comment by robieta** [comment]
In general I would say the code block at the top is something of an anti-pattern, because it's sort of splitting the difference between keras / non-keras and graph / non-graph. I would offer the following two approaches as alternatives. (Depending on your preference.)

Boilerplate:
```
import numpy as np
import tensorflow as tf
tf.enable_v2_behavior()

from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dense

def pretty_print_weights(model):
  """Ugly comprehension to make pretty strings."""
  print(", ".join([" ".join(["{:.3f}" for _ in w]).format(
        *w.flatten().tolist()) for w in model.get_weights()]))
```

The "I want Keras to handle it for me" way:
```
my_model = Sequential([Dense(1, activation='relu', input_shape=(5,))])
class ReduceMeanLoss(tf.keras.losses.Loss):
  def call(self, y_true, y_pred):
    return -tf.reduce_mean(y_pred)
my_model.compile(loss=ReduceMeanLoss(), optimizer=Adam())
```

And an example train loop:
```
pretty_print_weights(my_model)

# I've chosen `.train_on_batch` just because it's closer to manually applying
# gradients, but `.fit` works too.
for _ in range(100):
  my_model.train_on_batch(
      tf.random.uniform((16, 5)),
      tf.zeros((16,))  # unused since the loss ignored y_true
  )
pretty_print_weights(my_model)
```
` `
` `
` `
The "I want to handle my own updates" way:
```
my_model = Sequential([Dense(1, activation='relu', input_shape=(5,))])
my_optim = Adam()

@tf.function  # Decorating with tf.function will kick the function body into a
              # Graph context.
def my_train_fn(inputs):
  outputs = my_model(inputs)
  print(outputs, "   <=== This is a symbolic Tensor, and this print only runs during tracing.")
  my_loss = -tf.reduce_mean(outputs)
  updates = my_optim.get_updates(params=my_model.trainable_weights, loss=my_loss)

  # We take advantage of the automatic control dependencies of tf.function here,
  # so updates still gets executed when we run the function.
```

And an analogous training loop looks like:
```
pretty_print_weights(my_model)
for _ in range(100):
  my_train_fn(tf.random.uniform((16, 5)))
pretty_print_weights(my_model)
```

Finally, I haven't covered it but it's possible to call the entire thing under a `tf.Graph` scope of your own in which case Keras will treat that as the default graph. (This, for instance, is how Estimator works.) So if you really want to manage your own graph that is an option as well. But it can be rather irksome to get back to eager land because the function that we use in keras is a private symbol. (ConcreteFunction: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/eager/function.py#L463) If there wind up being lots of people who want to make eager compatible functions out of their graphs it might make sense to reassess whether there should be a public way to do that.

I realize that was something of a brain dump; let me know if you have any questions!

**Comment by danaugrs** [comment]
@robieta thanks for the brain dump 😄. I've used that first method many times. But in this particular case I don't think either method you provided works without significant modifications, if at all. To provide more context - I'm working on [a reinforcement learning library](https://github.com/danaugrs/huskarl) and am implementing several algorithms - this latest one being [DDPG](https://arxiv.org/abs/1509.02971). The idea is fairly simple - there are two networks - the actor (which takes in a state and outputs an action) and the critic (which takes a state and an action and outputs the value of that action). Training the critic is straightforward and I do it using `model.train_on_batch`.

<img align="right" height=300 src=https://user-images.githubusercontent.com/5261448/53881965-c79bf380-3ff3-11e9-88db-3479fedeacc3.png>

Training the actor, however, is more complicated. I need to connect the actor's action output to the critic's action input, then given a state (which is fed to both critic and actor) backpropagate `-mean(critic_output)` through the critic and then through the actor, and then only apply the updates to the actor network. See diagram ➡️.

I was able to implement that quite concisely in TF 1.* - full snippet below:

``` python
# To train the actor we want to change its weights such that it picks the action that has the highest possible value
state_input = self.critic.input[1]
critic_output = self.critic([self.actor(state_input), state_input])
actor_updates = self.optimizer_actor.get_updates(params=self.actor.trainable_weights, loss=-tf.keras.backend.mean(critic_output))
self.actor_train_on_batch = tf.keras.backend.function(inputs=[state_input], outputs=[self.actor(state_input)], updates=actor_updates)
```

Then the training routine becomes beautifully simple:

``` python
self.critic.train_on_batch([np.array(action_batch), np.array(state_batch)], target_qvals)
self.actor_train_on_batch([np.array(state_batch)])
```

I think this usage of the `tf.keras` API is extremely useful.

**Why doesn't this work anymore in TF 2.0? Is that intended (@fchollet)?**

**Comment by robieta** [comment]
Ahh. Thanks for the explanation. So it looks like what is happening is that with https://github.com/tensorflow/tensorflow/pull/26142 the gradients are now being computed symbolically, but somewhere in the apply process we're applying them to the variables in an eager fashion.

The issue that you're seeing is that when you call `keras.backend.function`, it tries to lift the relevant subgraph from the keras global graph into an execution graph, but fails because the update is eager rather than graph. So a temporary fix would be:
```
my_model = Sequential([Dense(1, activation='relu', input_shape=(5,))])
my_loss = -tf.reduce_mean(my_model.output)
my_optim = Adam()

# This is a hack to force the entire update calculation to be computed
# with the keras global graph to unblock in the short term.
with my_loss.graph.as_default():
  updates = my_optim.get_updates(params=my_model.trainable_weights, loss=my_loss)

my_fn = tf.keras.backend.function(inputs=my_model.inputs, outputs=my_model.outputs, updates=updates)
pretty_print_weights(my_model)

for _ in range(100):
  my_fn(tf.random.uniform((16,5)))
pretty_print_weights(my_model)
```

More broadly, two improvement to TensorFlow spring to mind:
1) The variable updates on symbolic inputs should probably also be symbolic. @alextp @tanzhenyu Does this make more sense to do in the optimizer or variable class?

2) The graph lifting code should check if there are invalid inputs and should provide an appropriate error message. (I can handle that.)

Thanks for pointing out this issue!

**Comment by robieta** [comment]
https://github.com/tensorflow/tensorflow/commit/46924b2f7bc4262b2c4b36841d393741113594ca should resolve this issue. (The optimizer classes will now check if any updates are symbolic and return a symbolic apply op if so.) That change should already have been picked up in the latest `tf-nightly` build. Feel free to reopen this issue if you encounter any issues.

(2) is going to be covered as part of a broader effort to improve error messaging.

Happy RL-ing!

**Comment by danaugrs** [comment]
I finally tried removing the workaround using version `2.0.0-alpha0` but the problem is still there!

With workaround (works):
```python
my_loss = -tf.keras.backend.mean(critic_output)
with my_loss.graph.as_default():
    actor_updates = self.optimizer_actor.get_updates(params=self.actor.trainable_weights, loss=my_loss)
self.actor_train_on_batch = tf.keras.backend.function(inputs=[state_input], outputs=[self.actor(state_input)], updates=actor_updates)
```

Without workaround (fails, but used to work in TF1):
```python
my_loss = -tf.keras.backend.mean(critic_output)
actor_updates = self.optimizer_actor.get_updates(params=self.actor.trainable_weights, loss=my_loss)
self.actor_train_on_batch = tf.keras.backend.function(inputs=[state_input], outputs=[self.actor(state_input)], updates=actor_updates)
```

Full stack trace:
```
C:\projects\huskarl\examples>python ddpg-pendulum.py
2019-05-03 14:16:18.351214: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "ddpg-pendulum.py", line 37, in <module>
    agent = hk.agent.DDPG(actor=actor, critic=critic, nsteps=2)
  File "c:\projects\huskarl\huskarl\agent\ddpg.py", line 48, in __init__
    actor_updates = self.optimizer_actor.get_updates(params=self.actor.trainable_weights, loss=-tf.keras.backend.mean(critic_output))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py", line 448, in get_updates
    grads = self.get_gradients(loss, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py", line 361, in get_gradients
    grads = gradients.gradients(loss, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 558, in _GradientsHelper
    raise RuntimeError("tf.gradients is not supported when eager execution "
RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.
```
It's the same original problem - seems like it was never fixed. Can you guys reopen and take a look?

**Comment by danaugrs** [comment]
I just upgraded to `2.0.0-beta0` and was able to remove the workaround! Thanks!
