### ISSUE TITLE
Cross-compilation from Windows 10 to Ubuntu 16.04

### ISSUE THREAD

**Issue by mat100payette** [tensorflow/tensorflow#26094]
**System information**
- TensorFlow version: TF r1.12.0 if possible
- Doc Link: N/A

**Describe the documentation issue**
I can't find any official tutorial on how to cross-compile Tensorflow on the main platforms other than the less-than-descriptive official tutorial to cross-compile for the Pi. I'm not sure if this is more of a Doc issue than a Feature request but I was looking for any help compiling for Ubuntu 16.04 from a Windows 10 machine. Since there are quite a bunch of error-prone steps to cross-compiling, as there are many options to configure and files to write in a specific way, I would really benefit from some guidance, even if minimal. There are a few tutorials on Medium, but those dont't target the same platforms and/or are old.

Is this something that could be added to Tensorflow's website ?

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
No, unless I manage to do it myself.

**Comment by mat100payette** [comment]
Any update on the question ? Not sure what that status means

**Comment by mohantym** [comment]
Hi @mat100payette!
We are checking to see whether you still need help in this issue . Have you checked this thread for installation in Ubuntu ? [link1](https://www.tensorflow.org/install/pip#ubuntu),[link2](https://www.tensorflow.org/install/source).Thanks!
