### ISSUE TITLE
Kenlm in tf.nn.ctc_beam_search_decoder

### ISSUE THREAD

**Issue by SibtainRazaJamali** [tensorflow/tensorflow#26096]
Please integrate Kenlm feature in tf.nn.ctc decoder. Because it is very hard to build tensorflow bindings from source. There are always issue with bazel version not matching with tf version.If every thing goes fine still there are issues such as missing libraries.So there should be some easy way to add a language model scoring with ctc_decoder.

**Comment by a6802739** [comment]
@brevdo, If you don't mind, could I have a try for this? And hope you could give me some reference, Thanks.

**Comment by SibtainRazaJamali** [comment]
yes of course.
Mozilla Deep speech model have customized the tensorflow. This version supports building binaries for Kenlm language model scoring for ctc decoder.
https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md
Similary, facebook wav2letter++ also have these binaries for c++ but they are hard to build.
https://github.com/facebookresearch/wav2letter/tree/master/src/decoder
last
Nvidia OpenSeq2Seq toolkit also gives the building instructions for ctc_decoder with language model
https://nvidia.github.io/OpenSeq2Seq/html/installation.html

**Comment by a6802739** [comment]
@SibtainRazaJamali, Thanks for all your reference, I'll talk with you if I met some problems.
