### ISSUE TITLE
Building a REPL for tensorflow

### ISSUE THREAD

**Issue by arieltci** [tensorflow/tensorflow#261]
Would an interactive CLI in the spirit of pgcli that would be build on top of python-prompt-toolkit is a good step forward?

**Comment by vrv** [comment]
Sounds like an interesting idea - feel free to create a repo that does this and update this issue if you do!

**Comment by arieltci** [comment]
Why did you close it? I want to hear ideas and comment, if people see any
potential use in that...

**Comment by vrv** [comment]
I would probably ask on the discuss mailing list to get more community input :).

**Comment by arieltci** [comment]
And the link for this discuss mailing list?


Sent with Mixmax

On Wed, Nov 18, 2015 at 7:51 PM, Vijay Vasudevan < notifications@github.com > wrote:
I would probably ask on the discuss mailing list to get more community input :).

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/resources/index.md#community
