### ISSUE TITLE
per_process_gpu_memory_fraction=1 does not allocate all of the memory

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#2610]
Seeing this on TF 0.8 with a Titan X. If I don't specify gpu_options at all, the memory allocated to TF is 11736MB. If I set per_process_gpu_memory_fraction=1.0, I only get 11127MB allocated. It's a small difference, but enough to make my large model crash, while the default allocations lets it just squeak in.

**Comment by vrv** [comment]
Can you log https://github.com/tensorflow/tensorflow/blob/ecc6c5ae3dcec7ea263a010ae2b6b1f7dc0da1a8/tensorflow/core/common_runtime/gpu/gpu_device.cc#L622 those two values there and let me know what they return in this case?  I'm a bit confused about how 'total' can ever be less than 'available'.

**Comment by alquraishi** [comment]
Hmmm, it may not be memory allocation _per se_ that's changing. I haven't logged those values yet but I tried running a smaller model and it too ran out of memory. This new one consumes about half as much memory and so it should have no trouble running. The only other thing I changed is to set allow_growth=False, but that is the default anyway, isn't it? And along with per_process_gpu_memory_fraction=1.0, it should have no effect, no?

I have no problem running much smaller models with per_process_gpu_memory_fraction set as low as 0.33, so I have gotten it to work, but it's the largish models that are giving me errors.

I can log the variables you mentioned, but there's no way to do this other than changing the C++ code and recompiling correct? I can do that but it'll take me a little bit of time because I have jobs currently running.

**Comment by vrv** [comment]
Yeah, there's no way to change it without a recompile -- basically my expectation of what is being reported by the device (through the StreamExecutor->DeviceMemory() call) appears to be wrong, so I don't know what the right fix until I can see what behavior you're running into.

**Comment by vrv** [comment]
Cc @zheng-xq in case he knows better

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
