### ISSUE TITLE
KeyError: "The name 'input:0' refers to a Tensor which does not exist. The operation, 'input', does not exist in the graph."

### ISSUE THREAD

**Issue by sumit1212** [tensorflow/tensorflow#26128]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by jvishnuvardhan** [comment]
@sumit1212 I noticed this as a duplicate issue as you posted it on original "tf-face-recognition" Repo and that is correct place for this issue. Closing this issue here. Thanks!
