### ISSUE TITLE
 //tensorflow/contrib/layers:normalization_test fails with Assertion error

### ISSUE THREAD

**Issue by kbhute-ibm** [tensorflow/tensorflow#26135]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):     Linux Ubuntu 16.04 s390x
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.12.0
- Python version: 2.7.12
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
python tensorflow/contrib/layers/python/layers/normalization_test.py fails on s390x with following parameters
input_shape = (1, 100, 100, 1)
data_format =  'NCHW' and 
tolerance = 1e-3
mu = 1e2
sigma = 0.1

**Describe the expected behavior**
It should pass on s390x like on Intel.

**Code to reproduce the issue**
python tensorflow/contrib/layers/python/layers/normalization_test.py Or
bazel test -c dbg  //tensorflow/contrib/layers:normalization_test

root@1da9d9e529b7:/home/test/tensorflow# python tensorflow/contrib/layers/python/layers/normalization_test.py
..name:  GroupNorm/Reshape_2
......................name:  InstanceNorm/instancenorm/add_1
....F.........
FAIL: testOutputBigInput4DNCHW (__main__.InstanceNormTest)

Traceback (most recent call last):
  File "tensorflow/contrib/layers/python/layers/normalization_test.py", line 172, in testOutputBigInput4DNCHW
    self.doOutputTest((1, 100, 100, 1), 'NCHW', tol=1e-3)
  File "tensorflow/contrib/layers/python/layers/normalization_test.py", line 155, in doOutputTest
    self.assertAllClose(expected_mean, mean, rtol=tol, atol=tol)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 1591, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 1561, in _assertAllCloseRecursive
    (path_str, path_str, msg)))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 1496, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg="\n".join(msgs), equal_nan=True)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=0.001
Mismatched value: a is different from b.
not close where = (array([0, 0, 0, 0, 0, 0]), array([ 8, 34, 44, 78, 87, 89]))
not close lhs = [ 0.  0.  0.  0.  0.  0.]
not close rhs = [-0.00105469 -0.00128662  0.00124512  0.00106445 -0.00124512 -0.00104004]
not close dif = [ 0.00105469  0.00128662  0.00124512  0.00106445  0.00124512  0.00104004]
not close tol = [ 0.00100105  0.00100129  0.00100125  0.00100106  0.00100125  0.00100104]
dtype = float64, shape = (1, 100)
(mismatch 6.0%)
 x: array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,...
 y: array([[  2.612305e-04,   1.684570e-04,  -1.342773e-04,  -1.684570e-04,
         -7.495117e-04,  -3.417969e-05,  -5.371094e-05,   6.567383e-04,
         -1.054688e-03,   2.319336e-04,  -1.318359e-04,  -3.222656e-04,...

----------------------------------------------------------------------
Ran 38 tests in 16.724s

FAILED (failures=1)

**Comment by kbhute-ibm** [comment]
This seems related to https://github.com/tensorflow/tensorflow/issues/16540. 

Please note that along with testOutputBigInput4DNCHW, 4 other subtests are failing, testOutputSmallInput5DNCHW, testOutputBigInput5DNHWC, testOutputBigInput5DNCHW, testOutputBigInput4DNHWC.

As mentioned in the issue https://github.com/tensorflow/tensorflow/issues/16540, with increasing tolerance as below it passes the test case:

```diff
def testOutputBigInput4DNCHW(self):
-self.doOutputTest((1, 100, 100, 1), 'NCHW', tol=1e-3)
+self.doOutputTest((1, 100, 100, 1), 'NCHW', tol=4e-3)
```

Also those also pass on passing dtype=dtypes.float64 as an argument in [doOutputTest function](https://github.com/tensorflow/tensorflow/blob/v1.12.0/tensorflow/contrib/layers/python/layers/normalization_test.py#L115):

```diff
reduced_axes = tuple(reduced_axes)

-inputs = random_ops.random_uniform(input_shape, seed=0) * sigma + mu
+inputs = random_ops.random_uniform(input_shape, seed=0, dtype=dtypes.float64) * sigma + mu
output_op = normalization.instance_norm(
  inputs, center=False, scale=False, data_format=data_format)
with self.cached_session() as sess:
```

I am not aware even if I dont pass dtype=dtypes.float64, it shows this value in assertion log:

**dtype = float64**, shape = (1, 100) but after manually passing this argument, it passes the test case.

Could you please guide me where it automatically takes this dtype from? Is there any way it treats LittleEndian and BigEndian machines and choose dtype accordingly? 

Thanks in advance :)

**Comment by kbhute-ibm** [comment]
Hi @gunan Could you please share your inputs of this? 

/CC @Nayana-ibm

**Comment by gunan** [comment]
the changes look ok to me.
could you run these tests with these changes with --runs_per_test=100 just to make sure they are not flaky?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by kbhute-ibm** [comment]
Hi @gunan,

With --runs_per_test=100 test cases still pass which shows tests are not flaky. We are raising PR for the same. 

Thanks for your support.

**Comment by martinwicke** [comment]
I'm reopening this since we're still discussing the associated PR.

**Comment by kbhute-ibm** [comment]
Hi @martinwicke 
While debugging //tensorflow/contrib/layers:normalization_test further and keeping your inputs  https://github.com/tensorflow/tensorflow/pull/26692#issuecomment-482172077 in mind, we have following solution to fix the normalization_test. 
Please find below the changes:

```diff
diff --git a/tensorflow/contrib/layers/python/layers/normalization.py b/tensorflow/contrib/layers/python/layers/normalization.py
index 76b03ff514..a871707c9e 100644
--- a/tensorflow/contrib/layers/python/layers/normalization.py
+++ b/tensorflow/contrib/layers/python/layers/normalization.py
@@ -27,7 +27,8 @@ from tensorflow.python.ops import init_ops
 from tensorflow.python.ops import math_ops
 from tensorflow.python.ops import nn
 from tensorflow.python.ops import variable_scope
-
+from tensorflow.python.framework import dtypes
+import sys

 __all__ = [
     'group_norm',
@@ -91,6 +92,11 @@ def instance_norm(inputs,
     ValueError: If rank or channels dimension of `inputs` is undefined.
   """
   inputs = ops.convert_to_tensor(inputs)
+
+  # Cast `inputs` array to float64 if machine is big endian
+  if sys.byteorder == "big" and inputs.dtype.base_dtype == dtypes.float32:
+    inputs = math_ops.cast(inputs, dtypes.float64)
+
   inputs_shape = inputs.shape
   inputs_rank = inputs.shape.ndims
```
Please let us know your inputs on this.

**Comment by kbhute-ibm** [comment]
Hi @martinwicke,
Could you please put your response on above solution?

**Comment by kbhute-ibm** [comment]
Hi @martinwicke Did you get chance to look at above changes?
@frreiss Please share if you have any inputs on this?

**Comment by martinwicke** [comment]
I was OOO for a while, thank you for your patience.

This looks fine to me.

**Comment by frreiss** [comment]
@kbhute-ibm this fix should be ok for now. 

The numeric instability that is happening here worries me, so I'll look into the underlying issue a bit more. Hopefully it's just due to different register sizes across architectures.

**Comment by kbhute-ibm** [comment]
The corresponding PR is merged which resolves this issue. So closing the issue. Thanks.
