### ISSUE TITLE
Estimator.train doesn't respect the RunConfig keep_checkpoint_max limit

### ISSUE THREAD

**Issue by keotic** [tensorflow/tensorflow#26136]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
UBUNTU 16.04.5 LTS (Xenial Xerus)
- TensorFlow installed from (source or binary):
pip version 1.12 tensorflow-gpu
- TensorFlow version (use command below):
1.12.0
- Python version:
3.5

- CUDA/cuDNN version:
9.0
- GPU model and memory:
Tesla V100 16G

**Describe the current behavior**
Running Estimator training as follows, should only keep 1 checkpoint file version (latest)
instead all checkpoints are kept.

session_config = tf.ConfigProto()
session_config.allow_soft_placement = True

run_conf = RunConfig(
            model_dir=out_dir,
            save_summary_steps=400,
            save_checkpoints_steps=5000,
            keep_checkpoint_max=1,
            session_config=session_config,
            tf_random_seed=None, 
            keep_checkpoint_every_n_hours=None,
            log_step_count_steps=10000, 
            train_distribute=None, 
            device_fn=None,
            protocol=None,
            eval_distribute=None,
            experimental_distribute=None
        )

estimator = tf.estimator.Estimator(
            model_fn=model.build_model_fn,
            config=run_config,
            params=params
        )

**Describe the expected behavior**
Only keep_checkpoint_max checkpoints should be saved

**Comment by awlego** [comment]
I also am seeing this bug, but in the opposite direction. If if I set the limit to 1000 it only keeps the default 5 checkpoints.

**Comment by crystina-z** [comment]
any solution to this? facing the same problem as well: `save_summary_steps`, `save_checkpoints_steps` are totally ignored

**Comment by sachinprasadhs** [comment]
I didn't face any issue while running this code and by keeping ` _keep_checkpoint_max=1` in the example [here](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/estimator.ipynb#scrollTo=oGFY5nW_B3YU).

**Comment by sachinprasadhs** [comment]
Closing this issue as it was fixed in the recent Tensorflow version. Please feel free to reopen the issue if you still have a concern. Thanks!
