### ISSUE TITLE
v1.13.1 CUDA Compilation fails on Windows 10 

### ISSUE THREAD

**Issue by rishi-rranjan** [tensorflow/tensorflow#26148]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):Source
- TensorFlow version:.1.13.1
- Python version:3.6
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):0.21
- GCC/Compiler version (if compiling from source):VS 2017 SDK 10.0.17763.132
- CUDA/cuDNN version:7.4.2
- GPU model and memory: 1060M, 6 GB

**Describe the problem**
Compilation on Windows 10 with CUDA 10 fails. 
**Provide the exact sequence of commands / steps that you executed before running into the problem**

- set PATH=C:\Users\Rishi\AppData\Local\Programs\Python\Python36;%PATH%
- SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;%PATH%
- SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64;%PATH%
- set PATH=c:\tools\cuda\bin;%PATH%
- set BAZEL_SH=C:\tools\msys64\usr\bin\bash.exe
- git clone --recursive https://github.com/tensorflow/tensorflow.git
- cd tensorflow
- git checkout v1.13.1
- pip3 install six numpy wheel
- pip3 install keras_applications==1.0.6 --no-deps
- pip3 install keras_preprocessing==1.0.5 --no-deps
- set PATH=c:\tools\bazel;%PATH%
- set PATH=C:\tools\msys64\usr\bin;%PATH%
- set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_201
- python ./configure.py
- bazel build --config=opt --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xtr1common(87): note: see reference to class template instantiation 'std::integral_constant<bool,false>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xtr1common(88): note: see reference to class template instantiation 'std::is_same<_Ty1,_Ty2>' being compiled
INFO: From Linking tensorflow/lite/toco/python/_tensorflow_wrap_toco.so:
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/lib64'; ignored
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64'; ignored
LINK : warning LNK4044: unrecognized option '/ldl'; ignored
LINK : warning LNK4044: unrecognized option '/lpthread'; ignored
LINK : warning LNK4044: unrecognized option '/ldl'; ignored
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/lite/toco/python/lib_tensorflow_wrap_toco.so.ifso and object bazel-out/x64_windows-opt/bin/tensorflow/lite/toco/python/lib_tensorflow_wrap_toco.so.exp
libcuda_platform.lo(cuda_dnn.o) : warning LNK4217: locally defined symbol ?ThenBlasGemm@Stream@stream_executor@@QEAAAEAV12@W4Transpose@blas@2@0_K11MAEBV?$DeviceMemory@M@2@H2HMPEAV52@H@Z (public: class stream_executor::Stream & __cdecl stream_executor::Stream::ThenBlasGemm(enum stream_executor::blas::Transpose,enum stream_executor::blas::Transpose,unsigned __int64,unsigned __int64,unsigned __int64,float,class stream_executor::DeviceMemory<float> const &,int,class stream_executor::DeviceMemory<float> const &,int,float,class stream_executor::DeviceMemory<float> *,int)) imported in function "public: virtual bool __cdecl stream_executor::cuda::CudnnSupport::DoMatMul(class stream_executor::Stream *,class stream_executor::DeviceMemory<float> const &,class stream_executor::DeviceMemory<float> const &,class stream_executor::dnn::BatchDescriptor const &,class stream_executor::dnn::BatchDescriptor const &,class stream_executor::DeviceMemory<float> *)" (?DoMatMul@CudnnSupport@cuda@stream_executor@@UEAA_NPEAVStream@3@AEBV?$DeviceMemory@M@3@1AEBVBatchDescriptor@dnn@3@2PEAV53@@Z)
libutils.a(utils.o) : warning LNK4217: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported in function "bool __cdecl tensorflow::grappler::NodeIsOnCpu(class tensorflow::NodeDef const *)" (?NodeIsOnCpu@grappler@tensorflow@@YA_NPEBVNodeDef@2@@Z)
ERROR: C:/sw/temp/tensorflow/tensorflow/tensorflow/BUILD:573:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash.exe failed: error executing command
  cd C:/users/rishi/_bazel_rishi/t6earjat/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=c:/tools/cuda
    SET PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\bin
    SET PYTHON_BIN_PATH=C:/Users/Rishi/AppData/Local/Programs/Python/Python36/python.exe
    SET PYTHON_LIB_PATH=C:/Users/Rishi/AppData/Local/Programs/Python/Python36/lib/site-packages
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=3.5,7.0
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  C:/tools/msys64/usr/bin/bash.exe bazel-out/x64_windows-opt/genfiles/tensorflow/tf_python_api_gen_v1.genrule_script.sh
Execution platform: @bazel_tools//platforms:host_platform
Traceback (most recent call last):
  File "\\?\C:\Users\Rishi\AppData\Local\Temp\Bazel.runfiles_md1fa9q2\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\Rishi\AppData\Local\Temp\Bazel.runfiles_md1fa9q2\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\Rishi\AppData\Local\Temp\Bazel.runfiles_md1fa9q2\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Rishi\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Rishi\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Users\Rishi\AppData\Local\Temp\Bazel.runfiles_md1fa9q2\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\C:\Users\Rishi\AppData\Local\Temp\Bazel.runfiles_md1fa9q2\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "\\?\C:\Users\Rishi\AppData\Local\Temp\Bazel.runfiles_md1fa9q2\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "\\?\C:\Users\Rishi\AppData\Local\Temp\Bazel.runfiles_md1fa9q2\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\Rishi\AppData\Local\Temp\Bazel.runfiles_md1fa9q2\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\Rishi\AppData\Local\Temp\Bazel.runfiles_md1fa9q2\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Rishi\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Rishi\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 8639.073s, Critical Path: 1339.78s
INFO: 2615 processes: 2615 local.
FAILED: Build did NOT complete successfully
`

**Comment by rishi-rranjan** [comment]
@ymodak Opening this as new issue.

**Comment by rishi-rranjan** [comment]
I had to merge https://github.com/tensorflow/tensorflow/issues/22387.

**Comment by jvishnuvardhan** [comment]
@rishi-rranjan Could try the instruction [here](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12) that worked for installing TF1.12_gpu successfully. Follow the process listed but use newer version of CUDA10 (CUDA9.0 was used). Please let me know how it progresses. Thanks!

**Comment by rootkitchao** [comment]
I tried to compile Tensorflow 1.12 + CUDA10 under windows10 before.But the compiler I am using is MSVC2015 R3.I am not sure that MSVC2017 can work correctly.And trying to downgrade the version of bazel is sometimes useful.

**Comment by rishi-rranjan** [comment]
@jvishnuvardhan I am trying to compile TF since i have some custom operators which I will need to link against some dependencies. I will install pip package and see if I can compile my custom operators with that itself. 

@rootkitchao Thanks for the pointer. I am use VS 2017 extensively for all my projects but will try VS 2015 on other setup if I am not able to compile my operators with VS2017.

**Comment by rishi-rranjan** [comment]
@jvishnuvardhan I was able to install TF 1.13.1 with your instruction. I will check if I can compile my custom operators with this install. if it works for me, I don't need to compile TF and will close this issue.

**Comment by rishi-rranjan** [comment]
Closing this as I am able to successfully compile tensorflow/examples/adding_an_op.

**Comment by jvishnuvardhan** [comment]
@rishi-rranjan Good to know that it worked for you. Thanks!
