### ISSUE TITLE
Tensorflow 1.13.1 not available on pypi

### ISSUE THREAD

**Issue by andrewsmartin** [tensorflow/tensorflow#26140]
Hello! I see that 1.13.1 has been released yesterday, but it seems like it's not yet on pypi. When will it be available?

**Comment by bwolfus** [comment]
I have the same problem. I can't get new TF by pip.

**Comment by XiaomoWu** [comment]
I have the same issue! I can't use tensorboard on Python 3.7 unless update to 1.13.1.

**Comment by drewszurko** [comment]
Now available on PyPI - https://pypi.org/project/tensorflow/1.13.1/
