### ISSUE TITLE
Tensorflow 1.13 - can't deprecate tf.layers.conv2d - no existing replacement

### ISSUE THREAD

**Issue by jtressle** [tensorflow/tensorflow#26145]
I'm updating to Tensorflow 1.13 from 1.12.

tf.layers.conv2d is being deprecated.  

The note states:
```
conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv2d instead.
``` 

First, there is no 'keras.layers.conv2d'.  This is a 'keras.layers.Conv2D', but that is a different function and a direct replacement for 'tf.layers.Conv2D'.  

Therefore, either make a 'keras.layers.conv2d' function or remove the deprecation warning for 'tf.layers.conv2d'.  

Here's the link to the conv2d fuction.

https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/python/layers/convolutional.py

Thanks,

**Comment by jclevesque** [comment]
I am in the same situation. I want a functional API, is that going away for good?

**Comment by colibri17** [comment]
Same here!

**Comment by qlzh727** [comment]
We are consolidating the high level APIs and remove duplications. Under the hood, tf.conv2d is using exactly the same code as tf.keras.layers.Conv2D. The functional API is just a wrapper around the keras API. With the new keras layer API, the existing tf.conv2d can be rewrite as follow:

```
# Old functional API
output = tf.conv2d(inputs, *other_args)

# New OO API
output = tf.keras.layers.Conv2D(*other_args)(inputs)
```

**Comment by eddienewton** [comment]
@qlzh727 so before closing this issue, can you simply update the documentation and warning one gets?  

The current documentation is wrong.  It leads users to a non-existing function.  The documentation should simply state what you just wrote above.  

Thanks,

**Comment by jtressle** [comment]
@qlzh727 can you simply update the documentation and warning one gets?

The current documentation is wrong. It leads users to a non-existing function. The documentation should simply state what you just wrote above.

Thanks

**Comment by qlzh727** [comment]
Ack, will send a update for doc very soon.

**Comment by qlzh727** [comment]
Its actually been fixed in https://github.com/tensorflow/tensorflow/commit/a4f5558529a56d72bdcec9c0c8d0a3fb2a91fb64, but hasn't reach the stable release yet.

**Comment by jtressle** [comment]
@qlzh727 awesome thanks for taking care of it!
