### ISSUE TITLE
Python 3.6.8 and Tensorflow 1.12.0 not working on windows 2008 R2

### ISSUE THREAD

**Issue by akrana** [tensorflow/tensorflow#26141]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 2008 R2 64-bit
- TensorFlow installed from (source or binary): source (pip install tensorflow)
- TensorFlow version: 1.12.0
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip
- GPU model and memory: 4GB RAM

**Describe the problem**

I'm trying to import the tensorflow 1.12.0 library in python 3.6.8 but at the initial stage itself in getting following error.
Please help me out with the same.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Successfully installed tensorflow-1.12.0

C:\Tensorflow\models\research>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load
_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load
_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\_
_init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\p
ython\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\p
ython\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load
_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load
_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by akrana** [comment]
Tensorflow installation logs if required

C:\Tensorflow\models\research>pip install tensorflow
Collecting tensorflow
  Using cached https://files.pythonhosted.org/packages/05/cd/c171d2e33c0192b04560ce864c26eba83fed888
fe5cd9ded661b2702f2ae/tensorflow-1.12.0-cp36-cp36m-win_amd64.whl
Requirement already satisfied: keras-applications>=1.0.6 in c:\users\administrator\appdata\local\pro
grams\python\python36\lib\site-packages (from tensorflow) (1.0.7)
Requirement already satisfied: absl-py>=0.1.6 in c:\users\administrator\appdata\local\programs\pytho
n\python36\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: tensorboard<1.13.0,>=1.12.0 in c:\users\administrator\appdata\local\p
rograms\python\python36\lib\site-packages (from tensorflow) (1.12.2)
Requirement already satisfied: numpy>=1.13.3 in c:\users\administrator\appdata\local\programs\python
\python36\lib\site-packages (from tensorflow) (1.16.1)
Requirement already satisfied: wheel>=0.26 in c:\users\administrator\appdata\local\programs\python\p
ython36\lib\site-packages (from tensorflow) (0.33.1)
Requirement already satisfied: grpcio>=1.8.6 in c:\users\administrator\appdata\local\programs\python
\python36\lib\site-packages (from tensorflow) (1.18.0)
Requirement already satisfied: astor>=0.6.0 in c:\users\administrator\appdata\local\programs\python\
python36\lib\site-packages (from tensorflow) (0.7.1)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\administrator\appdata\local\programs\pyt
hon\python36\lib\site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: protobuf>=3.6.1 in c:\users\administrator\appdata\local\programs\pyth
on\python36\lib\site-packages (from tensorflow) (3.6.1)
Requirement already satisfied: six>=1.10.0 in c:\users\administrator\appdata\local\programs\python\p
ython36\lib\site-packages (from tensorflow) (1.12.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in c:\users\administrator\appdata\local\pr
ograms\python\python36\lib\site-packages (from tensorflow) (1.0.9)
Requirement already satisfied: gast>=0.2.0 in c:\users\administrator\appdata\local\programs\python\p
ython36\lib\site-packages (from tensorflow) (0.2.2)
Requirement already satisfied: h5py in c:\users\administrator\appdata\local\programs\python\python36
\lib\site-packages (from keras-applications>=1.0.6->tensorflow) (2.9.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\administrator\appdata\local\programs\pyth
on\python36\lib\site-packages (from tensorboard<1.13.0,>=1.12.0->tensorflow) (3.0.1)
Requirement already satisfied: werkzeug>=0.11.10 in c:\users\administrator\appdata\local\programs\py
thon\python36\lib\site-packages (from tensorboard<1.13.0,>=1.12.0->tensorflow) (0.14.1)
Requirement already satisfied: setuptools in c:\users\administrator\appdata\local\programs\python\py
thon36\lib\site-packages (from protobuf>=3.6.1->tensorflow) (40.6.2)
Installing collected packages: tensorflow
Successfully installed tensorflow-1.12.0

**Comment by jvishnuvardhan** [comment]
@akrana I think for some reason, tensorflow was not installed correctly. I had this issue earlier and resolved it. Please uninstall python and tensorflow Then reinstall using the instructions [here](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12). Thanks!

**Comment by akrana** [comment]
Hello, 
I did uninstall the Python 3.6.8, reinstall Python.
Uninstall tensorflow, reinstall it. Still I was facing same issue
I degraded the python to 3.6.6 and reinstall tensorflow, Im still facing the issue as follow

<Quote>
C:\Users\Administrator>pip uninstall tensorflow
Uninstalling tensorflow-1.12.0:
  Would remove:
    c:\users\administrator\appdata\local\programs\python\python36\lib\site-packa
ges\tensorflow-1.12.0.dist-info\*
    c:\users\administrator\appdata\local\programs\python\python36\lib\site-packa
ges\tensorflow\*
    c:\users\administrator\appdata\local\programs\python\python36\scripts\freeze
_graph.exe
    c:\users\administrator\appdata\local\programs\python\python36\scripts\saved_
model_cli.exe
    c:\users\administrator\appdata\local\programs\python\python36\scripts\tensor
board.exe
    c:\users\administrator\appdata\local\programs\python\python36\scripts\tflite
_convert.exe
    c:\users\administrator\appdata\local\programs\python\python36\scripts\toco.e
xe
    c:\users\administrator\appdata\local\programs\python\python36\scripts\toco_f
rom_protos.exe
Proceed (y/n)? y
  Successfully uninstalled tensorflow-1.12.0

C:\Users\Administrator>pip install tensorflow
Collecting tensorflow
  Downloading https://files.pythonhosted.org/packages/bf/58/34bfa8fa17f863333611
72b3b502e805195180f19a7496ad0f6149138d55/tensorflow-1.13.1-cp36-cp36m-win_amd64.
whl (63.1MB)
    100% |████████████████████████████████| 63.1MB 69kB/s
Requirement already satisfied: numpy>=1.13.3 in c:\users\administrator\appdata\l
ocal\programs\python\python36\lib\site-packages (from tensorflow) (1.16.1)
Collecting tensorflow-estimator<1.14.0rc0,>=1.13.0 (from tensorflow)
  Downloading https://files.pythonhosted.org/packages/bb/48/13f49fc3fa0fdf916aa1
419013bb8f2ad09674c275b4046d5ee669a46873/tensorflow_estimator-1.13.0-py2.py3-non
e-any.whl (367kB)
    100% |████████████████████████████████| 368kB 6.6MB/s
Requirement already satisfied: grpcio>=1.8.6 in c:\users\administrator\appdata\l
ocal\programs\python\python36\lib\site-packages (from tensorflow) (1.18.0)
Requirement already satisfied: keras-applications>=1.0.6 in c:\users\administrat
or\appdata\local\programs\python\python36\lib\site-packages (from tensorflow) (1
.0.7)
Requirement already satisfied: gast>=0.2.0 in c:\users\administrator\appdata\loc
al\programs\python\python36\lib\site-packages (from tensorflow) (0.2.2)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\administrator\appdat
a\local\programs\python\python36\lib\site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: wheel>=0.26 in c:\users\administrator\appdata\loc
al\programs\python\python36\lib\site-packages (from tensorflow) (0.33.1)
Requirement already satisfied: astor>=0.6.0 in c:\users\administrator\appdata\lo
cal\programs\python\python36\lib\site-packages (from tensorflow) (0.7.1)
Requirement already satisfied: six>=1.10.0 in c:\users\administrator\appdata\loc
al\programs\python\python36\lib\site-packages (from tensorflow) (1.12.0)
Requirement already satisfied: absl-py>=0.1.6 in c:\users\administrator\appdata\
local\programs\python\python36\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: protobuf>=3.6.1 in c:\users\administrator\appdata
\local\programs\python\python36\lib\site-packages (from tensorflow) (3.6.1)
Requirement already satisfied: keras-preprocessing>=1.0.5 in c:\users\administra
tor\appdata\local\programs\python\python36\lib\site-packages (from tensorflow) (
1.0.9)
Collecting tensorboard<1.14.0,>=1.13.0 (from tensorflow)
  Downloading https://files.pythonhosted.org/packages/fa/7b/3ee06856ec30d5136cd2
002408df1d111fcff269f3691147dbf3b8dc0ba2/tensorboard-1.13.0-py3-none-any.whl (3.
2MB)
    100% |████████████████████████████████| 3.2MB 6.6MB/s
Collecting mock>=2.0.0 (from tensorflow-estimator<1.14.0rc0,>=1.13.0->tensorflow
)
  Downloading https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f
1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 3.9MB/s
Requirement already satisfied: h5py in c:\users\administrator\appdata\local\prog
rams\python\python36\lib\site-packages (from keras-applications>=1.0.6->tensorfl
ow) (2.9.0)
Requirement already satisfied: setuptools in c:\users\administrator\appdata\loca
l\programs\python\python36\lib\site-packages (from protobuf>=3.6.1->tensorflow)
(40.6.2)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\administrator\appda
ta\local\programs\python\python36\lib\site-packages (from tensorboard<1.14.0,>=1
.13.0->tensorflow) (0.14.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\administrator\appdata
\local\programs\python\python36\lib\site-packages (from tensorboard<1.14.0,>=1.1
3.0->tensorflow) (3.0.1)
Collecting pbr>=0.11 (from mock>=2.0.0->tensorflow-estimator<1.14.0rc0,>=1.13.0-
>tensorflow)
  Downloading https://files.pythonhosted.org/packages/8c/7f/fed53b379500fd889707
d1f6e61c2a35e12f2de87396894aff89b017d1d6/pbr-5.1.2-py2.py3-none-any.whl (107kB)
    100% |████████████████████████████████| 112kB 6.6MB/s
Installing collected packages: pbr, mock, tensorflow-estimator, tensorboard, ten
sorflow
  Found existing installation: tensorboard 1.12.2
    Uninstalling tensorboard-1.12.2:
      Successfully uninstalled tensorboard-1.12.2
Successfully installed mock-2.0.0 pbr-5.1.2 tensorboard-1.13.0 tensorflow-1.13.1
 tensorflow-estimator-1.13.0

C:\Users\Administrator>python
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_impor
t_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\imp.py
", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\imp.py
", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_impor
t_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\imp.py
", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\imp.py
", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>
<Unquote>

**Comment by jvishnuvardhan** [comment]
@akrana Looking at the error log, I see the tensorflow was not uninstalled completely for some reason. Did you follow the instructions I provided? Could you follow that and let me know if that solved installation issue? Thanks!

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. Please open a new ticket when new information is available. Thanks!

**Comment by maazqureshi446** [comment]
m
