### ISSUE TITLE
CUDA 8.0 support

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#2614]
NVidia CUDA 7.5 distribution for Ubuntu only goes up to Ubuntu 15.04 which is EOL'ed already. So it would be useful to have CUDA 8.0 support which is provided for Ubuntu 16.04

**Comment by vrv** [comment]
There is already a bug for this I think. On mobile but you should be able to search

**Comment by yaroslavvb** [comment]
sorry, should've searched better, https://github.com/tensorflow/tensorflow/issues/2559
