### ISSUE TITLE
Why deprecate tf.layers.dense?

### ISSUE THREAD

**Issue by chwang85** [tensorflow/tensorflow#26144]
In the tensorflow 1.13 document of tf.layers.dense, there is a warning:
Warning: THIS FUNCTION IS DEPRECATED. It will be removed in a future version. Instructions for updating: Use keras.layers.dense instead.

I am very confused, because this function is very easy to use, and I used it very frequently. Why do you deprecate it? 

By the way, I did not find the alternative “keras.layers.dense”, there is only "keras.layers.Dense"

**Comment by jvishnuvardhan** [comment]
@chwang85 Thanks for finding this typo. Please use "keras.layers.Dense". Thanks!

**Comment by chwang85** [comment]
> @chwang85 Thanks for finding this typo. Please use "keras.layers.Dense". Thanks!

But why deprecate tf.layers.dense()?
But why deprecate tf.layers.dense()?
But why deprecate tf.layers.dense()?

**Comment by chwang85** [comment]
> @chwang85 Thanks for finding this typo. Please use "keras.layers.Dense". Thanks!

Why do not you deprecate tf.Session()?

**Comment by chwang85** [comment]
It is ridiculous to deprecate tf.layers.dense()
Do you really care about the requirements of TF developers?

**Comment by MarkDaoust** [comment]
Hi @chwang85,

The plan for TensorFlow2 is, as we're doing with eager mode,  to tie state variables to python objects. The problem with `tf.layers.dense` is that it that it relies on hidden global state.

So from now on we're recommending people use the Object-oriented versions. But, we're not deleting `dense` anytime soon.

With tf2 `import tensorflow.compat.v1 as tf` should work for most programs that ran in TensorFlow 1.
We're working on extensive migration guides, that will be published here soon:

https://github.com/tensorflow/docs/tree/master/site/en/r2/guide

**Comment by chwang85** [comment]
Thanks for explaining. Just one more question: 
For "outputs = tf.layers.dense(inputs, units)", in the future, is it proper to change it to "outputs = tf.layers.Dense(units).apply(inputs)"?

**Comment by wookayin** [comment]
`tf.layers.Dense(256)(inputs)`

**Comment by chwang85** [comment]
thanks. but this still seems weird. DL models is already very complicated, why use oop to make it more complicated?

**Comment by MarkDaoust** [comment]
My feeling is that it makes it less complicated: It gives a clear separation defining my network, and running my network, the magic re-use in the old "function" style is tricky, at best. OOP also gives a clear answer to the question of "where is the state for this layer?": it's in the object.

And @chwang85, could you send us a patch PR for the typo?

**Comment by chwang85** [comment]
OK.
But why use "tf.keras.layers.Dense" rather than "tf.layers.Dense" to replace "tf.layers.dense"? Does that mean "tf.layers.Dense" will also be deprecated in the future?

**Comment by MarkDaoust** [comment]
`tf.keras.layers.Dense` and `tf.layers.Dense` will both be the same object.

**Comment by mihaimaruseac** [comment]
Obsoleted by #26844

**Comment by Traeyee** [comment]
Awful apis, awful warning, awful backward compatibility.

**Comment by misssprite** [comment]
> > @chwang85 Thanks for finding this typo. Please use "keras.layers.Dense". Thanks!
> 
> Why do not you deprecate tf.Session()?

Aha, `tf.Session()` is no longer needed in eager mode, which is the default mode of tf 2.0.

**Comment by sbrl** [comment]
How does this affect of Tensorflow.js?
