### ISSUE TITLE
[docs] (non) determinism in TF

### ISSUE THREAD

**Issue by mpekalski** [tensorflow/tensorflow#26147]
**Describe the feature and the current behavior/state.**
A documentation explaining determinism and sources of non determinism in TF applications. It should cover things from having multiple readers, seeds in the specific ops, seed in numpy, PYTHONHASHSEED, non-deterministic ops in CUDA (and why TF does not support passing deterministic flag even though it would be slower), `TF_CUDNN_USE_AUTOTUNE`, and probably some others I do not know about.

**Who will benefit with this feature?**
I take part in many Kaggle competitions and very often people there have problems with non-determinism in NN.

**Comment by jvishnuvardhan** [comment]
@mpekalski Can you please check this https://www.tensorflow.org/api_docs/python/tf/config/experimental/enable_op_determinism. This will enable your code to run deterministically at the cost of some computational time. Thanks!
