### ISSUE TITLE
need guide to build with CUDA 10.1

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#26150]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu18.04.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.13.1
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): >=0.21.0
- GCC/Compiler version (if compiling from source):  7.3.0
- CUDA/cuDNN version: 10.1/7.5
- GPU model and memory:  RTX2080Ti GDDR6 11GB

**Describe the problem**

with CUDA 10.1 came out, build process is messing

there are soft links like . ***.so.10 which points to ****.so.10.1.105 . but tensorflow builder looks for ****.10.0 or ****.10.1

they should point to ***.10 . not ***.10.1 or ****.10.0

and libcublas and libnvblas loacation has been changed to /usr/lib/x86_64-linux-gnu

**Comment by alanpurple** [comment]
and question, does windows gpu binary 1.13.1 works with CUDA10.1?

**Comment by YanzheL** [comment]
I also have the same issue.
I upgraded CUDA (and related libs) to 10.1 from ubuntu 18.04 by apt-get, and did a clean tensorflow compile from source on master branch (commit id 31f770fa9fa8e32606fca7333349ce5c722fc199).
Then it shows errors:
```
trinity@trinity-x:~/tensorflow$ bazel build --config=opt  --config=mkl //tensorflow/tools/pip_package:build_pip_package
INFO: Invocation ID: f3a8fbaa-0655-46d5-9cd8-6d221a29d56e
DEBUG: /home/trinity/.cache/bazel/_bazel_trinity/6f70dc6b75b9c02c6ff4af3478bba3ac/external/build_bazel_rules_apple/apple/repositories.bzl:35:5: 
WARNING: `build_bazel_rules_apple` depends on `bazel_skylib` loaded from https://github.com/bazelbuild/bazel-skylib.git (tag 0.6.0), but we have detected it already loaded into your workspace from None (tag None). You may run into compatibility issues. To silence this warning, pass `ignore_version_differences = True` to `apple_rules_dependencies()`.

ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': in /home/trinity/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/trinity/tensorflow/third_party/gpus/cuda_configure.bzl", line 1501
		_create_local_cuda_repository(repository_ctx)
	File "/home/trinity/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266, in _create_local_cuda_repository
		_find_libs(repository_ctx, cuda_config)
	File "/home/trinity/tensorflow/third_party/gpus/cuda_configure.bzl", line 859, in _find_libs
		_find_cuda_lib("cublas", repository_ctx, cpu_value, c..., ...)
	File "/home/trinity/tensorflow/third_party/gpus/cuda_configure.bzl", line 773, in _find_cuda_lib
		find_lib(repository_ctx, [("%s/%s%s" % (bas...], ...)))
	File "/home/trinity/tensorflow/third_party/gpus/cuda_configure.bzl", line 750, in find_lib
		auto_configure_fail(("No library found under: " + ",...)))
	File "/home/trinity/tensorflow/third_party/gpus/cuda_configure.bzl", line 341, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: No library found under: /usr/local/cuda-10.1/lib64/libcublas.so.10.1, /usr/local/cuda-10.1/lib64/stubs/libcublas.so.10.1, /usr/local/cuda-10.1/lib/powerpc64le-linux-gnu/libcublas.so.10.1, /usr/local/cuda-10.1/lib/x86_64-linux-gnu/libcublas.so.10.1, /usr/local/cuda-10.1/lib/x64/libcublas.so.10.1, /usr/local/cuda-10.1/lib/libcublas.so.10.1, /usr/local/cuda-10.1/libcublas.so.10.1
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': in /home/trinity/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/trinity/tensorflow/third_party/gpus/cuda_configure.bzl", line 1501
		_create_local_cuda_repository(repository_ctx)
	File "/home/trinity/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266, in _create_local_cuda_repository
		_find_libs(repository_ctx, cuda_config)
	File "/home/trinity/tensorflow/third_party/gpus/cuda_configure.bzl", line 859, in _find_libs
		_find_cuda_lib("cublas", repository_ctx, cpu_value, c..., ...)
	File "/home/trinity/tensorflow/third_party/gpus/cuda_configure.bzl", line 773, in _find_cuda_lib
		find_lib(repository_ctx, [("%s/%s%s" % (bas...], ...)))
	File "/home/trinity/tensorflow/third_party/gpus/cuda_configure.bzl", line 750, in find_lib
		auto_configure_fail(("No library found under: " + ",...)))
	File "/home/trinity/tensorflow/third_party/gpus/cuda_configure.bzl", line 341, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: No library found under: /usr/local/cuda-10.1/lib64/libcublas.so.10.1, /usr/local/cuda-10.1/lib64/stubs/libcublas.so.10.1, /usr/local/cuda-10.1/lib/powerpc64le-linux-gnu/libcublas.so.10.1, /usr/local/cuda-10.1/lib/x86_64-linux-gnu/libcublas.so.10.1, /usr/local/cuda-10.1/lib/x64/libcublas.so.10.1, /usr/local/cuda-10.1/lib/libcublas.so.10.1, /usr/local/cuda-10.1/libcublas.so.10.1
INFO: Elapsed time: 0.167s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
    Fetching @local_config_cuda; fetching
```

**Comment by YanzheL** [comment]
BTW, why tensorflow must specify minor release version number of CUDA, such as '10.0' instead of using major release version '10'?
It would be better if tensorflow regards the minor version number mismatch as a warning, not an error during compilation.
Thanks.

**Comment by cliffwoolley** [comment]
This has to do with a change in the SONAMEs of CUDA Toolkit libraries starting in CUDA 10.1.  We will submit a PR to allow compatibility both before and after that change.  @nluehr

**Comment by ymodak** [comment]
@alanpurple  The Official `tensorflow-gpu` 1.13 binaries are built with cuda 10.0, cudnn 7. Can you please switch to cuda 10.0 and build again. Thanks!

**Comment by alanpurple** [comment]
@ymodak 

I made links to 10.1 so files but still has an error building . #26155

**Comment by alvaroslm** [comment]
I managed to build it in windows but you've got to copy some of the libraries (some have 101 or 10 in their name vs 100 for all of them in cuda 10). But I'm running into another issue, if I try to use Cudnn in recurrent layers from C++ it's crashing (it used to work with tf 1.10.1 and cuda 9). I've tried all cudnn versions supported by cuda 10, to no avail. I'm downgrading to Cuda 10.0 and recompiling TF as we speak. It's incredible that there's nowhere in the documentation or the repository where I can check which versions are tested... it's a terrible waste of my time (and don't get me started on the gazillion bugs I have to work around every time I build this).

By the way, which version of cudnn are you officially using for the TF 1.13.1 / Cuda 10.0 combination?

**Comment by alanpurple** [comment]
@ymodak 

anyway can we expect next official binary release is with CUDA 10.1?

**Comment by mazar** [comment]
This may be a problem with CUDA 10.1 libraries being stored differently in compare to 10.0. To build tag v1.13.1 with CUDA 10.1, I created some symlinks to allow the build to start:

```
sudo cp /usr/lib/x86_64-linux-gnu/libcublas.so.10.1.0.105 /usr/local/cuda-10.1/lib64/
sudo ln -s /usr/local/cuda-10.1/lib64/libcublas.so.10.1.0.105 /usr/local/cuda-10.1/lib64/libcublas.so.10.1
sudo ln -s /usr/local/cuda-10.1/lib64/libcublas.so.10.1 /usr/local/cuda-10.1/lib64/libcublas.so
sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcusolver.so.10 /usr/local/cuda-10.1/lib64/libcusolver.so.10.1
sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcurand.so.10 /usr/local/cuda-10.1/lib64/libcurand.so.10.1
sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcufft.so.10 /usr/local/cuda-10.1/lib64/libcufft.so.10.1
```

Then entered CUDA version 10.1 and CuDNN version 7.5.0 during configure. 
Unfortunately I got to some other problem which is explained in [26155](https://github.com/tensorflow/tensorflow/issues/26155).

**Comment by ymodak** [comment]
@ymodak Support for CUDA 10.1 is on our future road map but unfortunately won't be dealt immediately. As of now you have to switch to cuda 10 for using pre-built binaries. Thanks!

**Comment by alvaroslm** [comment]
> 
> 
> @alanpurple Support for CUDA 10.1 is on our future road map but unfortunately won't be dealt immediately. As of now you have to switch to cuda 10 for using pre-built binaries. Thanks!

It would be extremely helpful to know that beforehand (the documentation is stale and hard to find). We wouldn't be wasting lots time trying different versions of everything if we knew what TF is being successfully built with.

**Comment by gunan** [comment]
https://www.tensorflow.org/install/gpu#software_requirements

**Comment by alvaroslm** [comment]
> 
> 
> https://www.tensorflow.org/install/gpu#software_requirements

Thank you for updating the info. Just 5 days ago (according to the cached version on Google), there was no mention of CUDA 10 or even Ubuntu 18.04, or even specific Tensorflow versions on that page.

I'm happy to see info on the current TF gpu version 1.13 has just popped up on the tested build configs page too: https://www.tensorflow.org/install/source#tested_build_configurations

**Comment by kgizdov** [comment]
This is due to conflicting behaviour at configure/build time and runtime. Have a look at the patch in #28093 for a temporary workaround.

**Comment by Student-HXJ** [comment]
> This may be a problem with CUDA 10.1 libraries being stored differently in compare to 10.0. To build tag v1.13.1 with CUDA 10.1, I created some symlinks to allow the build to start:
> 
> ```
> sudo cp /usr/lib/x86_64-linux-gnu/libcublas.so.10.1.0.105 /usr/local/cuda-10.1/lib64/
> sudo ln -s /usr/local/cuda-10.1/lib64/libcublas.so.10.1.0.105 /usr/local/cuda-10.1/lib64/libcublas.so.10.1
> sudo ln -s /usr/local/cuda-10.1/lib64/libcublas.so.10.1 /usr/local/cuda-10.1/lib64/libcublas.so
> sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcusolver.so.10 /usr/local/cuda-10.1/lib64/libcusolver.so.10.1
> sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcurand.so.10 /usr/local/cuda-10.1/lib64/libcurand.so.10.1
> sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcufft.so.10 /usr/local/cuda-10.1/lib64/libcufft.so.10.1
> ```
> 
> Then entered CUDA version 10.1 and CuDNN version 7.5.0 during configure.
> Unfortunately I got to some other problem which is explained in [26155](https://github.com/tensorflow/tensorflow/issues/26155).

and my /usr/lib/x86_64-linux-gnu/libcublas.so.10.2.0.168, is the same way for 10.1?

**Comment by eboujlal** [comment]
> This may be a problem with CUDA 10.1 libraries being stored differently in compare to 10.0. To build tag v1.13.1 with CUDA 10.1, I created some symlinks to allow the build to start:
> 
> ```
> sudo cp /usr/lib/x86_64-linux-gnu/libcublas.so.10.1.0.105 /usr/local/cuda-10.1/lib64/
> sudo ln -s /usr/local/cuda-10.1/lib64/libcublas.so.10.1.0.105 /usr/local/cuda-10.1/lib64/libcublas.so.10.1
> sudo ln -s /usr/local/cuda-10.1/lib64/libcublas.so.10.1 /usr/local/cuda-10.1/lib64/libcublas.so
> sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcusolver.so.10 /usr/local/cuda-10.1/lib64/libcusolver.so.10.1
> sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcurand.so.10 /usr/local/cuda-10.1/lib64/libcurand.so.10.1
> sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcufft.so.10 /usr/local/cuda-10.1/lib64/libcufft.so.10.1
> ```
> 
> Then entered CUDA version 10.1 and CuDNN version 7.5.0 during configure.
> Unfortunately I got to some other problem which is explained in [26155](https://github.com/tensorflow/tensorflow/issues/26155).

You saved my day !

**Comment by eboujlal** [comment]
> > This may be a problem with CUDA 10.1 libraries being stored differently in compare to 10.0. To build tag v1.13.1 with CUDA 10.1, I created some symlinks to allow the build to start:
> > ```
> > sudo cp /usr/lib/x86_64-linux-gnu/libcublas.so.10.1.0.105 /usr/local/cuda-10.1/lib64/
> > sudo ln -s /usr/local/cuda-10.1/lib64/libcublas.so.10.1.0.105 /usr/local/cuda-10.1/lib64/libcublas.so.10.1
> > sudo ln -s /usr/local/cuda-10.1/lib64/libcublas.so.10.1 /usr/local/cuda-10.1/lib64/libcublas.so
> > sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcusolver.so.10 /usr/local/cuda-10.1/lib64/libcusolver.so.10.1
> > sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcurand.so.10 /usr/local/cuda-10.1/lib64/libcurand.so.10.1
> > sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcufft.so.10 /usr/local/cuda-10.1/lib64/libcufft.so.10.1
> > ```
> > 
> > 
> > Then entered CUDA version 10.1 and CuDNN version 7.5.0 during configure.
> > Unfortunately I got to some other problem which is explained in [26155](https://github.com/tensorflow/tensorflow/issues/26155).
> 
> and my /usr/lib/x86_64-linux-gnu/libcublas.so.10.2.0.168, is the same way for 10.1?



> > This may be a problem with CUDA 10.1 libraries being stored differently in compare to 10.0. To build tag v1.13.1 with CUDA 10.1, I created some symlinks to allow the build to start:
> > ```
> > sudo cp /usr/lib/x86_64-linux-gnu/libcublas.so.10.1.0.105 /usr/local/cuda-10.1/lib64/
> > sudo ln -s /usr/local/cuda-10.1/lib64/libcublas.so.10.1.0.105 /usr/local/cuda-10.1/lib64/libcublas.so.10.1
> > sudo ln -s /usr/local/cuda-10.1/lib64/libcublas.so.10.1 /usr/local/cuda-10.1/lib64/libcublas.so
> > sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcusolver.so.10 /usr/local/cuda-10.1/lib64/libcusolver.so.10.1
> > sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcurand.so.10 /usr/local/cuda-10.1/lib64/libcurand.so.10.1
> > sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcufft.so.10 /usr/local/cuda-10.1/lib64/libcufft.so.10.1
> > ```
> > 
> > 
> > Then entered CUDA version 10.1 and CuDNN version 7.5.0 during configure.
> > Unfortunately I got to some other problem which is explained in [26155](https://github.com/tensorflow/tensorflow/issues/26155).
> 
> and my /usr/lib/x86_64-linux-gnu/libcublas.so.10.2.0.168, is the same way for 10.1?

Yes the same way, Try it ^ ^

**Comment by edowson** [comment]
Fix for building TensorFlow-1.13.1 with CUDA-10.1 libraries:
```bash
# libcublas
sudo cp /usr/lib/x86_64-linux-gnu/libcublas.so.10.2.0.168 /usr/local/cuda-10.1/lib64/
sudo ln -s /usr/local/cuda-10.1/lib64/libcublas.so.10.2.0.168 /usr/local/cuda-10.1/lib64/libcublas.so.10.1
sudo ln -s /usr/local/cuda-10.1/lib64/libcublas.so.10.1 /usr/local/cuda-10.1/lib64/libcublas.so

# libcusolver, libcurand, libcufft
sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcusolver.so.10 /usr/local/cuda-10.1/lib64/libcusolver.so.10.1
sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcurand.so.10 /usr/local/cuda-10.1/lib64/libcurand.so.10.1
sudo ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcufft.so.10 /usr/local/cuda-10.1/lib64/libcufft.so.10.1
```

**Comment by elachkarcharbel** [comment]
Hello everyone,
if you want to keep CUDA10.1 just install the new release of tensorflow 2.0, it will work for sure.
use this for python2:  pip install tf-nightly-gpu-2.0-preview
use this for pyhton3: pip3 install tf-nightly-2.0-preview
### ### ###

**Comment by gunan** [comment]
Hi @elachkarcharbel I am pretty sure we are building those two packages with cuda 10.

**Comment by marcusmueller** [comment]
@elachkarcharbel can confirm these are linked against CUDA 10.0, not 10.1.

**Comment by nluehr** [comment]
TensorFlow 1.14.0 builds against CUDA 10.1 pretty easily. I just needed to `export TF_CUDA_PATHS=/usr,/usr/local/cuda` (were the latter is the cuda 10.1 install location) before running configure.

**Comment by JonnoFTW** [comment]
In addition to @edowson I had to do:

```bash
sudo cp /usr/include/cublas* /usr/local/cuda-10.1/include/
```

You may also need to set your `LD_LIBRARY_PATH` when running anything that uses the GPU:

```bash
export LD_LIBARY_PATH=/usr/local/cuda/lib64
```

**Comment by edowson** [comment]
@JonnoFTW I've updated my [tf-build/Dockerfile](https://github.com/edowson/docker-tensorflow/blob/master/ubuntu/xenial/tf-build/Dockerfile#L227-L234) to incorporate those changes.

There's a [tf-base](https://github.com/edowson/docker-tensorflow/tree/master/ubuntu/xenial/tf-base) docker image in there that uses the [tf-build](https://github.com/edowson/docker-tensorflow/tree/master/ubuntu/xenial/tf-build) output, to generate a base tf-2.0.0-beta1 docker image.

I was compiling with Intel MKL libraries, so perhaps that's why I didn't get any build errors due to missing cublas headers.
```
bazel build --config=opt --config=mkl --config=v2 //tensorflow/tools/pip_package:build_pip_package
```

Did you get any errors about missing cublas headers while building?

**Comment by JonnoFTW** [comment]
The only error I got was that it couldn't find a header file:

```
ERROR: /localstore/tensorflow-1.13.2/tensorflow/stream_executor/BUILD:89:1: C++ compilation of rule '//tensorflow/stream_executor:cuda_platform' failed (Exit 1)
tensorflow/stream_executor/cuda/cuda_blas.cc:16:10: fatal error: cuda/include/cublas_v2.h: No such file or directory
 #include "cuda/include/cublas_v2.h"
```
Copying the header files fixed it for me.

**Comment by jinfagang** [comment]
```
Cuda Configuration Error: None of the libraries match their SONAME: /usr/local/cuda-10.1/lib64/libcublas.so.10.1
```

checkout into r2.0, building error.

from master, build success

**Comment by CLIsVeryOK** [comment]
@alanpurple is right, libcublas and libnvblas loacation has been changed to /usr/lib/x86_64-linux-gnu

**Comment by jverce** [comment]
> In addition to @edowson I had to do:
> 
> ```shell
> sudo cp /usr/include/cublas* /usr/local/cuda-10.1/include/
> ```
> 
> You may also need to set your `LD_LIBRARY_PATH` when running anything that uses the GPU:
> 
> ```shell
> export LD_LIBARY_PATH=/usr/local/cuda/lib64
> ```

I achieved similar results by trying a similar approach. However I'm having runtime issues when trying to import `tensorflow_addons`:
```
In [1]: import tensorflow_addons as tfa                                                                                                                                                                                                     
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-1-8e92e93ce06e> in <module>
----> 1 import tensorflow_addons as tfa

~/.pyenv/versions/3.6.8/envs/OpenNMT-tf/lib/python3.6/site-packages/tensorflow_addons/__init__.py in <module>
     19 
     20 # Local project imports
---> 21 from tensorflow_addons import activations
     22 from tensorflow_addons import callbacks
     23 from tensorflow_addons import image

~/.pyenv/versions/3.6.8/envs/OpenNMT-tf/lib/python3.6/site-packages/tensorflow_addons/activations/__init__.py in <module>
     19 from __future__ import print_function
     20 
---> 21 from tensorflow_addons.activations.gelu import gelu
     22 from tensorflow_addons.activations.hardshrink import hardshrink
     23 from tensorflow_addons.activations.lisht import lisht

~/.pyenv/versions/3.6.8/envs/OpenNMT-tf/lib/python3.6/site-packages/tensorflow_addons/activations/gelu.py in <module>
     23 
     24 _activation_ops_so = tf.load_op_library(
---> 25     get_path_to_datafile("custom_ops/activations/_activation_ops.so"))
     26 
     27 

~/.pyenv/versions/3.6.8/envs/OpenNMT-tf/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py in load_op_library(library_filename)
     59     RuntimeError: when unable to load the library or get the python wrappers.
     60   """
---> 61   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     62 
     63   op_list_str = py_tf.TF_GetOpList(lib_handle)

NotFoundError: /home/jay/.pyenv/versions/3.6.8/envs/OpenNMT-tf/lib/python3.6/site-packages/tensorflow_addons/custom_ops/activations/_activation_ops.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
```

**Comment by jamessmith90** [comment]
8 months and no release. Lol 
Is Google even funding Tensorflow ?

**Comment by thesby** [comment]
Terrible experience, 1 year later, no update happens
