### ISSUE TITLE
Eigen/CXX11/../../../Eigen/src/Core/GenericPacketMath.h error: invalid operands to binary expression ('const double2' and 'const double2') pxor(const Packet& a, const Packet& b) { return a ^ b; }

### ISSUE THREAD

**Issue by shuifeixiang** [tensorflow/tensorflow#26159]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from: source 
- TensorFlow version: r1.99 and latest
- Python version: 3.5
- Installed using virtualenv? pip? conda?: 
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0/7.0 and 8.0/7.0
- GPU model and memory: Geforce 1050 Ti

**Describe the problem**
**external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/GenericPacketMath.h:211:51: error: invalid operands to binary expression ('const double2' and 'const double2')
pxor(const Packet& a, const Packet& b) { return a ^ b; }
**

**Comment by jvishnuvardhan** [comment]
@shuifeixiang Can you describe how you installed TF? can you print TF version 
$ import tensorflow as tf
$print(tf.__version__)?

If TF was not installed correctly, it is better to start fresh. Uninstall python, and tensorflow then reinstall them using the instructions [here](https://github.com/rnreich/ubuntu-tensorflow-gpu-all-versions). Please let me know how it progresses. Thanks!

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. Please open a new ticket when you have new information. Thanks!
