### ISSUE TITLE
Tensorflow Lite on GPU failed on Android Pi9.0

### ISSUE THREAD

**Issue by guoyinchen** [tensorflow/tensorflow#26161]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Android Pi9.0 with NXP i.MX8QM
- TensorFlow installed from (source or binary):
Build from source based on https://www.tensorflow.org/lite/performance/gpu_advanced
- TensorFlow version (or github SHA if from source):
commit ad78d08bd1d03238d434d3d214a1de56f22d7601 (HEAD -> imx_r1.98, origin/r1.98)
Author: A. Unique TensorFlower <gardener@tensorflow.org>
Date:   Wed Feb 13 12:35:06 2019 -0800

    [TF:XLA] Mark a test as not running on XLA due to different flows.

    The test is not run because it is to test a part of grappler not used with XLA:GPU.

    This is change is a no-op. It makes explicit a default value and adds comments.

    PiperOrigin-RevId: 233807945

**Any other info / logs**
02-27 14:37:26.750  4532  4618 E AndroidRuntime: FATAL EXCEPTION: CameraBackground
02-27 14:37:26.750  4532  4618 E AndroidRuntime: Process: android.example.com.tflitecamerademo, PID: 4532
02-27 14:37:26.750  4532  4618 E AndroidRuntime: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: WARNING: op code #43 cannot be handled by this delegate.  Onl.
02-27 14:37:26.750  4532  4618 E AndroidRuntime:
02-27 14:37:26.750  4532  4618 E AndroidRuntime:        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
02-27 14:37:26.750  4532  4618 E AndroidRuntime:        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:83)
02-27 14:37:26.750  4532  4618 E AndroidRuntime:        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:60)
02-27 14:37:26.750  4532  4618 E AndroidRuntime:        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:224)
02-27 14:37:26.750  4532  4618 E AndroidRuntime:   at com.example.android.tflitecamerademo.ImageClassifier.recreateInterpreter(ImageClassifier.java:168)
02-27 14:37:26.750  4532  4618 E AndroidRuntime:        at com.example.android.tflitecamerademo.ImageClassifier.useGpu(ImageClassifier.java:176)
02-27 14:37:26.750  4532  4618 E AndroidRuntime:        at com.example.android.tflitecamerademo.Camera2BasicFragment.lambda$updateActiveModel$0$Camera2BasicFragment(Camera2BasicFragment.ja)
02-27 14:37:26.750  4532  4618 E AndroidRuntime:        at com.example.android.tflitecamerademo.Camera2BasicFragment$$Lambda$0.run(Unknown Source:24)
02-27 14:37:26.750  4532  4618 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
02-27 14:37:26.750  4532  4618 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)

**Comment by freedomtan** [comment]
Does the NXP i.MX8QM  OpenGL ES 3.1 Compute Shader?

**Comment by guoyinchen** [comment]
> Does the NXP i.MX8QM OpenGL ES 3.1 Compute Shader?

Yes. i.MX8QM support the ES3.1 compute shader.

**Comment by impjdi** [comment]
@guoyinchen 

Thanks for trying out the GPU delegate.  Well, the error message says that op #43 is SQUEEZE, so the first part of the graph (until SQUEEZE) is supposed to be run on GPU, and the rest on CPU.  TFLite framework is supposed to handle GPU / CPU transition smoothly, and I'm actually surprised that it gets a fatal error.  I wonder whether it has multiple subgraphs inside.

Is it possible for you to share the TFLIte model with me?

**Comment by guoyinchen** [comment]
@impjdi 
I use the one mobilenet_v1_1.0_224.tflite which can be fetched from http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz
I used the default android app in tensorflow git as https://github.com/tensorflow/tensorflow/tree/r1.13/tensorflow/lite/java/demo

**Comment by freedomtan** [comment]
@guoyinchen Some NXP materials, such as [this](https://www.nxp.com/products/processors-and-microcontrollers/arm-based-processors-and-mcus/i.mx-applications-processors/i.mx-8-processors/i.mx-8-family-arm-cortex-a53-cortex-a72-virtualization-vision-3d-graphics-4k-video:i.MX8), says OpenGL ES 3.0. So I am not sure if 3.1 Compute Shader is supported. I tried the GPU Delegate on various platforms and wrote a [quick-and-dirty benchmark](https://github.com/freedomtan/glDelegateBench) program before. On platforms with GL ES 3.1 Compute Shader, the only problem I met so far was https://github.com/tensorflow/tensorflow/issues/25759.  And as @impjdi said, SQUEEZE not supported should not be a problem.

**Comment by guoyinchen** [comment]
@freedomtan 
the website dont have the correct info. we will have it updated. And actually we have es31 CTS to test our i.MX8QM. It can pass those CTS.  Do you have some sample code for us to check which API you use to query those GPU info?

**Comment by freedomtan** [comment]
@guoyinchen I don't work for Google. @impjdi does. I just use GPU Delegate, don't have any query.

**Comment by impjdi** [comment]
Not officially announced yet, but FYI: GPU code is now visible at:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/gpu

if you need the code for better insight what is happening.

**Comment by terryheo** [comment]
Let's close this issue. Please let me know if this is still happening with recent TFLite releases.
