### ISSUE TITLE
Tensorflow not working with vGPUs (when the machine is not in pass-through mode)

### ISSUE THREAD

**Issue by MrinalJain17** [tensorflow/tensorflow#26168]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **Binary**
- TensorFlow version: **1.12.0**
- Python version: **3.6.8**
- Installed using virtualenv? pip? conda?: **Conda**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **CUDA 9.2; CuDNN 7.3**
- GPU model and memory: **NVIDIA Tesla V100 (16 GB)**

**Describe the problem**

I was using TF for experimenting with seq2seq models on a VM that had access to a Tesla V100 GPU (in pass-through mode). Recently, that VM was restricted to use a vGPU (with 50% of the memory - Q8 variant of V100), and hence it was not is pass-through mode anymore. With this change, Tensorflow stopped working, and gave `UNKNOWN_CUDA_ERROR`.

I would like to know if Tensorflow could be used with Virtual GPUs (not in pass-through mode).
If yes, any helpful resource for achieving the same would be much appreciated.

Thanks.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```python
import tensorflow as tf
print(tf.test.is_gpu_available())
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
Attempting to fetch value instead of handling error
Internal: failed initializing StreamExecutor for CUDA Device Ordinal 0
```

*(Currently, I do not have the full traceback unfortunately).*

**Comment by gunan** [comment]
I think this should be redirected to GPU or GPU performance team, seems like a low level GPU driver issue?

**Comment by MrinalJain17** [comment]
@jvishnuvardhan @tatianashp Hey guys. Any update on this would be really useful.
