### ISSUE TITLE
Add speech recognition while true with webcam

### ISSUE THREAD

**Issue by ArjunAJS143** [tensorflow/tensorflow#26162]
is there any way to add speech recognition so that it will respond to our emotions if we speak .please help me or else is there any alternative way to record the audio file and check the input then it will speak with us

**Comment by jvishnuvardhan** [comment]
@ArjunAJS143 This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
