### ISSUE TITLE
Memory Fault (Coredumped) java

### ISSUE THREAD

**Issue by Arkariian** [tensorflow/tensorflow#26164]
Hi!

When i try to run this Hello World TF example, when the program is ending, appears this message "Memory Fault(Coredumped)"

Machine:
-java 1.7.64
-SO: Red Hat 7.3
Cores: 4
RAM: 8 gb

Example Code:

`
import org.tensorflow.Graph;
import org.tensorflow.Session;
import org.tensorflow.Tensor;
import org.tensorflow.TensorFlow;

public class HelloTF {
	
  public static void main(String[] args) throws Exception {
    try (Graph g = new Graph()) {
      final String value = "Hello from " + TensorFlow.version();

      // Construct the computation graph with a single operation, a constant
      // named "MyConst" with a value "value".
      try (Tensor t = Tensor.create(value.getBytes("UTF-8"))) {
        // The Java API doesn't yet include convenience functions for adding operations.
        g.opBuilder("Const", "MyConst").setAttr("dtype", t.dataType()).setAttr("value", t).build();
      }
      catch(Exception e) {
    	  System.out.println("Try 1");
    	  e.printStackTrace();
      }

      // Execute the "MyConst" operation in a Session.
      try (Session s = new Session(g);
           Tensor output = s.runner().fetch("MyConst").run().get(0)) {
        System.out.println(new String(output.bytesValue(), "UTF-8"));
        s.close();
      }
      catch(Exception e) {
    	  System.out.println("Try 2");
    	  e.printStackTrace();

      }
    }
    catch(Exception e) {
  	  System.out.println("Try 3");
  	  e.printStackTrace();
    }
    System.out.println("END");
  }

}`

POM:
`<project>
       
     <modelVersion>4.0.0</modelVersion>
     <groupId>org.myorg</groupId>
     <artifactId>hellotf</artifactId>
     <version>1.0.0</version>
    
     <properties>
       <exec.mainClass>HelloTF</exec.mainClass>
       <maven.compiler.source>1.7</maven.compiler.source>
       <maven.compiler.target>1.7</maven.compiler.target>  
     </properties>
    
     <dependencies>
       
       <dependency>
         <groupId>org.tensorflow</groupId>
         <artifactId>tensorflow</artifactId>
         <version>1.7.0</version>
       </dependency>

    </dependencies>

</project>`

Any Help?

thanks!

**Comment by jvishnuvardhan** [comment]
@Arkariian This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
