### ISSUE TITLE
Where to place 'tf.contrib.quantize.create_training_graph'  during multi-gpu Quantization-aware training?

### ISSUE THREAD

**Issue by Zhengtq** [tensorflow/tensorflow#26165]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):**Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:No
- TensorFlow installed from (source or binary):**By pip**
- TensorFlow version (use command below):**1.11.0**
- Python version:**2.7**
- Bazel version (if compiling from source):No
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I follow "quantization aware training" tutorial in tensorflow to retrain my already trained floating point  model. And I wrote a muli-gpu version to do the stuff. Actually, I have written two snippets of training code, the first code snippet is :
```python
with tf.variable_scope(tf.get_variable_scope()):
    for i in xrange(len(GPU_NUM_ID)):
       with tf.device('/gpu:%d' % GPU_NUM_ID[i]):
              with tf.name_scope('%s_%d' % ('cnn_mg', i)) as scope:
                     images, labels = ut._load_batch_filename()  
                            logits, out_data = inference(images, reuse=tf.AUTO_REUSE,  num_classes=LABEL_NUM)
                            loss ,accuracy_sep = _tower_loss_depth(scope, logits, labels)
                            tf.get_variable_scope().reuse_variables()
                            grads = optimizer.compute_gradients(loss_total_sep)
                            tower_grads.append(grads)   

tf.contrib.quantize.create_training_graph(quant_delay=DELAY_STEP)
```
The second snippet of the training code is:
```python
with tf.variable_scope(tf.get_variable_scope()):

    for i in xrange(len(GPU_NUM_ID)):
       with tf.device('/gpu:%d' % GPU_NUM_ID[i]):
              with tf.name_scope('%s_%d' % ('cnn_mg', i)) as scope:
                     images, labels = ut._load_batch_filename()  
                            logits, out_data = inference(images, reuse=tf.AUTO_REUSE,  num_classes=LABEL_NUM)
                            with tf.variable_scope(tf.get_variable_scope(), reuse=tf.AUTO_REUSE): 
                                   tf.contrib.quantize.create_training_graph(quant_delay=DELAY_STEP)
                            loss ,accuracy_sep = _tower_loss_depth(scope, logits, labels)
                            tf.get_variable_scope().reuse_variables()
                            grads = optimizer.compute_gradients(loss_total_sep)
                            tower_grads.append(grads)
```

**Describe the expected behavior**
What I have found is: The second code snippet if 1.5 times faster than the first  code snippet  with the same training setting.I want to know why this happens and  I want know which code snippet is the tensorflow recommended code snippet. 
However, When I update my tensorflow version to 1.12.0, the second version(faster) could cause some error("tensorflow Graph is invalid, contains a cycle"). Dose this mean I have to slow down my multi-gpu Quantization-aware training in the future version of tensorflow?

**Comment by iamhankai** [comment]
Have you solved this problem? 

Do you know where to insert the code when using tf.Estimator?

**Comment by kumariko** [comment]
@Zhengtq We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. Thanks!
