### ISSUE TITLE
CRF functions in TensorFlow 2.0

### ISSUE THREAD

**Issue by invencode** [tensorflow/tensorflow#26167]
Hello,

It seems like CRF (tensorflow.contrib.crf) is moving to tensorflow/probability in TensorFlow 2.0. 
(https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md)

but, I couldn't find them on https://github.com/tensorflow/probability.
 
Where can I find CRF related features in TensorFlow 2.0?

**Comment by dynamicwebpaige** [comment]
@invencode It does not look like `tf.contrib.crf` has been migrated to either the core TensorFlow 2.0 API or to TensorFlow Probability. If your code base is dependent on this symbol and you are interested in migrating it to TF 2.0, we could take a look at including it in the [addons](http://www.github.com/tensorflow/addons) repo.

Are you interested in helping migrate `tf.contrib.crf` to `tensorflow/addons`?

cc: @martinwicke @seanpmorgan

**Comment by seanpmorgan** [comment]
Hi @invencode currently addons is planning to move CRF https://github.com/tensorflow/addons/issues/22 but its unlikely to make the first release. The move requires adapting the code to use [Keras RNN Cell](https://github.com/tensorflow/community/blob/master/rfcs/20180920-unify-rnn-interface.md) in TF2.

Addons is always looking for more contributors and maintainers, so if you're interested as @dynamicwebpaige suggested please reach out in the issue.

**Comment by a6802739** [comment]
@dynamicwebpaige @seanpmorgan, could I have try on this part?

**Comment by soloice** [comment]
@a6802739 Any progress?

**Comment by Squadrick** [comment]
We've ported CRF to TF2.0: https://github.com/tensorflow/addons/commit/47e687725eb4d65e45498e67a9026177fda684dd

This issue can be closed.

**Comment by facaiy** [comment]
Thank you, @Squadrick
