### ISSUE TITLE
[Feature Request, INQ] Add functionality for INQ implementation

### ISSUE THREAD

**Issue by Vooblin** [tensorflow/tensorflow#26172]
**System information**
- TensorFlow version (you are using): 1.12.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

My suggestion is related with the [article](https://arxiv.org/pdf/1702.03044.pdf) about Incremental Network Quantization (INQ) method of weights quantization.

Firstly for INQ implementation it is necessary to create integer convolution operation and matrix multiplication operation with bit shift instead of multiplication. I also want to create an API for weights partitions with certain choices of elements (for example, the absolute value maximum).

Suggested API will be low-level. High-level API will be a next step of my contributing. It is also interesting to add this feature to TFLite.

**Will this change the current api? How?**
Yes, There will be added new functions for convolution and matmul with bit shift.

**Who will benefit with this feature?**
The INQ method reduces the weight of the model, and also performs a bit shift instead of floating point multiplication.

**Any Other info.**

**Comment by sachinprasadhs** [comment]
Providing more information on the paper ciation details for visibility. https://scholar.google.com/scholar?q=Incremental+Network+Quantization:+Towards+Lossless+CNNs+with+Low-Precision+Weights&hl=en&as_sdt=0,5
