### ISSUE TITLE
TensorFlow master build failing on Ubuntu18.04 x86

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#26177]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: master as on today 
- Python version:  2.7.x
- Bazel version (if compiling from source): 0.19.0 ( installed using bazel-0.19.0-installer-linux-x86_64.sh)
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**
Tensorflow build fails with an error:

In file included from external/hwloc/include/private/private.h:29:0,
                 from external/hwloc/hwloc/traversal.c:11:
external/hwloc/include/private/misc.h:491:10: fatal error: xlocale.h: No such file or directory
 #include "xlocale.h"
          ^~~~~~~~~~~
compilation terminated.

**Steps to reproduce:**
 git clone https://github.com/tensorflow/tensorflow/
cd tensorflow
./configure

./configure
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.19.0 installed.
Please specify the location of python. [Default is /usr/bin/python]:

Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: N
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: N
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: N
Clang will not be downloaded.

Do you wish to build TensorFlow with MPI support? [y/N]: N
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=noignite       # Disable Apache Ignite support.
        --config=nokafka        # Disable Apache Kafka support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished

 bazel --host_jvm_args="-Xms512m" --host_jvm_args="-Xmx1024m"  build  -c opt  //tensorflow/toockage:build_pip_package

**Comment by Nayana-ibm** [comment]
Looks like glibc version is upgraded on Ubuntu 18.04
ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27

As mentioned [here](https://sourceware.org/ml/libc-alpha/2017-08/msg00010.html , https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27xlocale.h.27) ,  The nonstandard header <xlocale.h> has been removed.

This comes through third_party code hwloc (https://github.com/tensorflow/tensorflow/tree/master/third_party/hwloc)

Any workaround for this? I am not sure about functionality impact  if we disable including xlocale.h.

**Comment by Nayana-ibm** [comment]
Or should downgrade gcc ( build from source or installing particular version) ?

**Comment by wdirons** [comment]
A hack I've seen elsewhere is:

`ln -s /usr/include/locale.h /usr/include/xlocale.h`

Really the build should be using locale.h and not xlocale.h

**Comment by Nayana-ibm** [comment]
@wdirons ya..This hack worked. 

 I was also looking for gcc version which might mentioned by TensorFlow community.

**Comment by Nayana-ibm** [comment]
Btw looks like community has made changes around xlocale.h through this [commit](https://github.com/tensorflow/tensorflow/commit/d624b1d75a640c50be281d8b921d62dbd6149f2a).
Will try building TensorFlow master again .

**Comment by ymodak** [comment]
@Nayana-ibm Is this still an issue? Did you get a chance to build TF again? Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by gunan** [comment]
I think we can also work around the problem by unsetting `HAVE_XLOCALE_H`
however, I cannot even find where we are setting it in the first place :/

**Comment by gunan** [comment]
Looks like https://github.com/tensorflow/tensorflow/pull/26156 fixed this.
