### ISSUE TITLE
Side effects induced by attribute and slice operators must be limited in Python control flow.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#26189]
With `autograph=True`, wrapping ConvND in a `tf.function` works as expected with `use_bias=True`; but `use_bias=False` would fail. Code works as expected with `autograph=True`.

Error message received:

```
AttributeError: 'ConvND' object has no attribute 'b'.
```

**Comment by aaandrewww** [comment]
Sorry for the delay in closing. This was fixed on March 18th.
