### ISSUE TITLE
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 

### ISSUE THREAD

**Issue by steige2** [tensorflow/tensorflow#26183]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
$ uname -a
Linux e1.carbonate.uits.iu.edu 3.10.0-862.6.3.el7.x86_64 #1 SMP Fri Jun 15 17:57:37 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.12.0
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 0.22.0
- git version: 2.13.0
- GCC/Compiler version (if compiling from source): gcc (GCC) 6.3.0
- CUDA/cuDNN version: 10.0/7.4.2
- GPU model and memory: NVIDIA V100 16GB and NVIDIA P100 16GB

**Describe the problem**
Attempting to build from source, build does not complete.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package (383 packages loaded, 19566 targets configured). INFO: Found 1 target... ERROR: /gpfs/home/s/t/steige/Carbonate/.cache/bazel/_bazel_steige/7e49ffaa2aeff17b57c88f7f5097a06c/external/gif_archive/BUILD.bazel:8:1: undeclared inclusion(s) in rule '@gif_archive//:gif': this rule is missing dependency declarations for the following files included by 'external/gif_archive/lib/openbsd-reallocarray.c': '/N/soft/rhel7/gcc/6.3.0/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/stddef.h' '/N/soft/rhel7/gcc/6.3.0/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/stdint.h' Target //tensorflow/tools/pip_package:build_pip_package failed to build Use --verbose_failures to see the command lines of failed build steps. INFO: Elapsed time: 811.872s, Critical Path: 46.61s INFO: 20 processes: 20 local. FAILED: Build did NOT complete successfully

**Comment by jvishnuvardhan** [comment]
@steige2 Please check the tested build configurations [here](https://www.tensorflow.org/install/source#linux). There could be path reference issues in CUDA/cuDNN folders. Please check whether CUDA and cuDNN paths are referencing correctly or not. 
Either upgrade TF1.12 to TF1.13rc2 or downgrade Bazel and CUDA versions. Thanks!

**Comment by steige2** [comment]
Fixed it, I believe some of the dependencies were guilt with a different version of gcc, blew away the entire stack, started over with TF1.12, everything built just fine

**Comment by ddm198** [comment]
thinks your for your contribution.
