### ISSUE TITLE
[TF 2.0 API Docs] tf.keras

### ISSUE THREAD

**Issue by margaretmz** [tensorflow/tensorflow#26197]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>
**System information**
- TensorFlow version: 2.0
- Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras

**Describe the documentation issue**

**Links** 
"Defined in python/keras/api/_v2/keras/__init__.py" is pointing to a broken link:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/api/_v2/keras/__init__.py

**Description**
Currently it has "Detailed documentation and user guides are available at keras.io."
It would be better to point users to https://www.tensorflow.org/guide/keras, otherwise the experience feels broken.

It would be great to list some key differences between tf.keras vs Keras as an independent project (keras.io). Or at least point out there is no 1:1 mapping and what each one has and the other one doesn't have. This has been discussed in blog posts and forums but the official documentation should at least have a high level overview with a few sentences.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
Yes

**Comment by Praneet460** [comment]
I would be happy to do that. Soon I will update you with my work.

**Comment by dynamicwebpaige** [comment]
Thank you, Praneet! Please feel free to reach out if you have any questions. :slightly_smiling_face:

**Comment by Praneet460** [comment]
Hello, @dynamicwebpaige  I tried to find out the respective file in `tensorflow/docs/site/en` which I need to edit but I am not able to track it down. I would be happy if you help me a little bit in finding the appropriate file.

**Comment by Ayush517** [comment]
@dynamicwebpaige Is this the file that we need to edit https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/api/generator/api_init_files.bzl ?
I read some other issues and found that .bzl are used for generating modules but I am not sure if this is the one.

**Comment by shashvatshahi1998** [comment]
I would also love to contribute

**Comment by Ayush517** [comment]
@dynamicwebpaige Can you please help me with this

> @dynamicwebpaige I read some other issues and found that .bzl and **init**.py files are used for generating modules but I am not sure if these are the files we need to change. Can you please help .
> 
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/__init__.py
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/api/generator/api_init_files.bzl

**Comment by amanp592** [comment]
I would love to contribute to this!! please assign me this

**Comment by amanp592** [comment]
@dynamicwebpaige I search for the respective file but didn't find it in the docs repository of tensorflow. please direct me to the desired file for this issue.

**Comment by copperwiring** [comment]
@margaretmz I wanted to give a shot at documenting the difference between tf.keras and keras.io .Can you point me to good resources (blogs etc.) which I can use for the proper documentation. What word count and line count are we looking at?

**Comment by singhsuryansh12** [comment]
I would love to work on this. Can I please get a chance?

**Comment by yashk2810** [comment]
Both the things were fixed: https://github.com/tensorflow/tensorflow/pull/33443

Regarding difference between keras.io vs tensorflow.org/keras, contributions welcome :)

**Comment by Saduf2019** [comment]
@margaretmz Could you please confirm if this issue is resolved as per the previous comment.

**Comment by margaretmz** [comment]
There are a few things here:

- **Broken link on page**: I no longer see any broken links. So we are good on this.
- My comment on "Detailed documentation and user guides are available at **keras.io**". It is still pointed to keras.io. I thought keras.io is no longer really an active project any more. Why are we still point docs there?
- Thanks all for volunteering to document the different between tf.keras and keras.io. Not sure if there is any point in doing so though. Keras.io is no longer having any new releases and tf.keras will be moved into the original Keras repo. So there is really just tf.Keras.

**Comment by Saduf2019** [comment]
As the issue has been addressed moving this ticket to closed status.

**Comment by yashk2810** [comment]
>  "Detailed documentation and user guides are available at keras.io". It is still pointed to keras.io

@margaretmz Fixed in nightly: https://www.tensorflow.org/api_docs/python/tf/keras?version=nightly
