### ISSUE TITLE
TF 1.13.1 on Raspberry Pi 3B+ __init__.py gives an error: No module named 'tensorflow.python'. How to use static library file?

### ISSUE THREAD

**Issue by Zeit42** [tensorflow/tensorflow#26196]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian 9.8
- Mobile device if the issue happens on mobile device: Raspberry Pi Model 3 B+
- TensorFlow installed from (source or binary): Source I think
- TensorFlow version: 1.13.1
- Python version: 3.5
- Installed using virtualenv? pip? conda?: Native Compile
- Bazel version (if compiling from source): Not Applicable
- GCC/Compiler version (if compiling from source): 6.3.0 20170516
- CUDA/cuDNN version: Not Applicable
- GPU model and memory: Not Applicable

**Describe the problem**
I followed [this guide](https://www.tensorflow.org/lite/rpi) on how to compile TensorFlow Lite Natively on the Raspberry Pi. I cloned the tensorflow repo on the home folder, and then executed the scripts accordingly. I had to adjust the swapsize [as descrbied here](https://github.com/tensorflow/tensorflow/issues/26158#issuecomment-468089490), for the Compile to successfully run.

Back in the home folder, when I try to run:

` ~$ python3`
`>>> import tensorflow as tf`

I don't get any errors.

My goal is to run Object Detection on RaspberryPi using TF-Lite, [and I found this sample code](https://github.com/freedomtan/tensorflow/blob/deeplab_tflite_python/tensorflow/contrib/lite/examples/python/object_detection.py)

But when I tried to do his tensorflow import:

`>>> from tensorflow.contrib.lite.python import interpreter as interpreter_wrapper`

It didn't work because of course, in TF 1.13.1, the `lite` folder is no longer under `contrib`

But when I do:

`>>> from tensorflow.lite.python import interpreter as interpreter_wrapper`

I get: `ImportError: No module named 'tensorflow.lite'`

But when I do:

`>>> from tensorflow.tensorflow.lite.python import interpreter as interpreter_wrapper`

I get:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/pi/tensorflow/tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
> ImportError: No module named 'tensorflow.python'

When going to the `__init__.py` file (located in ~/tensorflow/tensorflow), the line in question is:
> from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

The error then becomes:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/pi/tensorflow/tensorflow/__init__.py", line 25, in <module>
>     from tensorflow.tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "/home/pi/tensorflow/tensorflow/python/__init__.py", line 49, in <module>
>    from tensorflow.python import pywrap_tensorflow
> ImportError: No module named 'tensorflow.python'

It's clear that in python code, I have to import Tensorflow as if I'm navigating through the file system.

Having downloaded the tensorflow repo to the home folder, and executing the python3 command from there, importing the tensorflow code had me going through the file structure.

And now that the __init__.py file is encountering problems in importing, I'm not sure how to edit the import paths, and I don't think I should. 

I have a feeling that I did not compile tensorflow properly.

How are we even supposed to use the libtensorflow-lite.a static library file?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Go get yourself an RPi, install Raspbian (not through NOOBS).
2. Download the Tensorflow repo in the home folder. Adjust your swapsize [by doing this](https://github.com/tensorflow/tensorflow/issues/26158#issuecomment-468089490). Then follow [the instructions in this link](https://www.tensorflow.org/lite/rpi)
3. After generating the static library, go back to the home folder and run python3 and the commands I tried above.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

The complete logs are above.

**Comment by petewarden** [comment]
It looks like you're trying to use TensorFlow Lite on the Raspberry Pi? The recommended way to do this is to build just the library itself, which you can find instructions for here:
https://www.tensorflow.org/lite/guide/build_rpi
