### ISSUE TITLE
Errors while building Tensorflow 1.12

### ISSUE THREAD

**Issue by OtakuSenpai** [tensorflow/tensorflow#26198]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Void Linux glibc x86_64
- TensorFlow installed from (source or binary): Source
- TensorFlow version: r1.12
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip, no virtualenv
- Bazel version (if compiling from source): 0.22
- GCC/Compiler version (if compiling from source): 8.2.0
- CUDA/cuDNN version: No
- GPU model and memory: None

**Describe the problem**

Hello guys, I'm trying to build TF in a non Debian based distro. But what I'm getting is this error, as referrenced by [this windows build from source](https://github.com/tensorflow/tensorflow/issues/24721), especially related to eigen.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
bazel build --incompatible_remove_native_http_archive=false --config=opt --copt=-mavx --copt=-mavx2 --config=monolithic //tensorflow/tools/pip_package:build_pip_package
INFO: Invocation ID: 851c2110-08b2-4ed8-a7b0-4c995b8388e9
DEBUG: /home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/build_bazel_rules_apple/apple/repositories.bzl:35:5: 
WARNING: `build_bazel_rules_apple` depends on `bazel_skylib` loaded from https://github.com/bazelbuild/bazel-skylib.git (tag 0.6.0), but we have detected it already loaded into your workspace from None (tag None). You may run into compatibility issues. To silence this warning, pass `ignore_version_differences = True` to `apple_rules_dependencies()`.

INFO: Build options --compiler and --cpu have changed, discarding analysis cache.
ERROR: /home/neel/Programming_Workspace/Not-My-Repos/tensorflow/third_party/eigen3/BUILD:34:1: no such package '@eigen_archive//': Traceback (most recent call last):
	File "/home/neel/Programming_Workspace/Not-My-Repos/tensorflow/third_party/repo.bzl", line 106
		_apply_patch(ctx, ctx.attr.patch_file)
	File "/home/neel/Programming_Workspace/Not-My-Repos/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
		fail("patch command is not found, ple...")
patch command is not found, please install it and referenced by '//third_party/eigen3:eigen3'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@eigen_archive//': Traceback (most recent call last):
	File "/home/neel/Programming_Workspace/Not-My-Repos/tensorflow/third_party/repo.bzl", line 106
		_apply_patch(ctx, ctx.attr.patch_file)
	File "/home/neel/Programming_Workspace/Not-My-Repos/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
		fail("patch command is not found, ple...")
patch command is not found, please install it
INFO: Elapsed time: 3.142s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (42 packages loaded, 470 targets c\
onfigured)
    currently loading: tensorflow/core/kernels
    Fetching @eigen_archive; fetching
    Fetching @double_conversion; fetching
```

**Any other info / logs**

I just cloned the latest repo from git and checked out TF r1.12 last commit. 
After that I passed only CPU options to "configure" and also had to install pip3.
I also installed eigen3 package from my distro's repos, but no help.
I don't know what to do, eigen does seem to be in the TF/tools/ folder but bazel doesn't import it. Please help !!

Here's the folder structure of "third_parties" folder:
```
ls ./third_party/
android                     libxsmm.BUILD
arm_neon_2_x86_sse.BUILD    linenoise.BUILD
astor.BUILD                 llvm
aws                         lmdb.BUILD
backports_weakref.BUILD     mkl
boringssl                   mkl_dnn
BUILD                       mpi
clang_toolchain             mpi_collectives
codegen.BUILD               nanopb.BUILD
com_google_absl.BUILD       nasm
common.bzl                  nccl
cub.BUILD                   ngraph
curl.BUILD                  ortools
cython.BUILD                pasta
double_conversion.BUILD     pcre.BUILD
eigen3                      png.BUILD
eigen.BUILD                 png_fix_rpi.patch
enum34.BUILD                pprof.BUILD
examples                    protobuf
farmhash.BUILD              py
fft2d                       python_runtime
flatbuffers                 repo.bzl
gast.BUILD                  six.BUILD
gif.BUILD                   snappy.BUILD
git                         sqlite.BUILD
googleapis.BUILD            swig.BUILD
gpus                        sycl
grpc                        systemlibs
hadoop                      tensorrt
highwayhash                 termcolor.BUILD
hwloc                       tflite_mobilenet.BUILD
icu                         tflite_mobilenet_float.BUILD
jpeg                        tflite_mobilenet_quant.BUILD
jsoncpp.BUILD               tflite_ovic_testdata.BUILD
kafka                       tflite_smartreply.BUILD
keras_applications_archive  toolchains
kissfft                     zlib.BUILD
```
Heres my git branches:
```
git branch
  master
* r1.12

git show --oneline r1.12

a6d8ffae09 (HEAD -> r1.12, tag: v1.12.0) Fix a bug in tpu.py and xla.py that while creating an identity node for control input edges under rewrite context, the parent control flow context is lost. (#23446)
diff --git a/tensorflow/contrib/compiler/xla.py b/tensorflow/contrib/compiler/xla.py
index 873b03580d..83d9d8c54a 100644
--- a/tensorflow/contrib/compiler/xla.py
+++ b/tensorflow/contrib/compiler/xla.py
@@ -179,14 +179,11 @@ class XLACompileContext(control_flow_ops.XLAControlFlowContext):
     if external_control_inputs:
       # Use an identity to pull control inputs as data inputs. Note that we
       # ignore ops which don't have outputs. TODO(phawkins): fix that.
-      with ops.control_dependencies(None):
-        self.Enter()
-        external_control_inputs = [
-            array_ops.identity(x.outputs[0]).op
-            for x in external_control_inputs
-            if x.outputs
-        ]
-        self.Exit()
+      external_control_inputs = [
+          array_ops.identity(x.outputs[0]).op

**Comment by OtakuSenpai** [comment]
Update:
---------
I had somehow messed up the git repo of tensorflow, and after git fetching the whole repo, I still get this error:
```
bazel build --incompatible_remove_native_http_archive=false --config=opt --copt=-mavx --copt=-mavx2 //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/neel/Programming_Workspace/Not-My-Repos/tensorflow/tools/bazel.rc
INFO: Invocation ID: 69f627fb-d42c-470a-a1dc-e81bfedaaeba
ERROR: /home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/protobuf_archive/BUILD:591:1: Traceback (most recent call last):
	File "/home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/protobuf_archive/BUILD", line 591
		internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
	File "/home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/protobuf_archive/protobuf.bzl", line 269, in internal_gen_well_known_protos_java
		Label(("%s//protobuf_java" % REPOSITOR...))
	File "/home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/protobuf_archive/protobuf.bzl", line 269, in Label
		REPOSITORY_NAME
builtin variable 'REPOSITORY_NAME' is referenced before assignment.
ERROR: /home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/protobuf_archive/BUILD:373:1: Target '@protobuf_archive//:android' contains an error and its package is in error and referenced by '@protobuf_archive//:protoc'
ERROR: /home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/protobuf_archive/BUILD:373:1: Target '@protobuf_archive//:msvc' contains an error and its package is in error and referenced by '@protobuf_archive//:protoc'
ERROR: /home/neel/Programming_Workspace/Not-My-Repos/tensorflow/tensorflow/contrib/boosted_trees/proto/BUILD:35:1: Target '@protobuf_archive//:protobuf_python_genproto' contains an error and its package is in error and referenced by '//tensorflow/contrib/boosted_trees/proto:tree_config_proto_py_genproto'
ERROR: /home/neel/Programming_Workspace/Not-My-Repos/tensorflow/tensorflow/contrib/boosted_trees/proto/BUILD:35:1: Target '@protobuf_archive//:protoc' contains an error and its package is in error and referenced by '//tensorflow/contrib/boosted_trees/proto:tree_config_proto_py_genproto'
ERROR: /home/neel/Programming_Workspace/Not-My-Repos/tensorflow/tensorflow/contrib/boosted_trees/proto/BUILD:35:1: Target '@protobuf_archive//:protobuf_python' contains an error and its package is in error and referenced by '//tensorflow/contrib/boosted_trees/proto:tree_config_proto_py'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 24.438s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (87 packages loaded, 538 targets c\
onfigured)
    currently loading: tensorflow/core/kernels
    Fetching @absl_py; fetching
```

**Comment by OtakuSenpai** [comment]
OK, so supposedly I was using the flag "-std=c++17" during configuration steps, and according to [this](https://github.com/bazelbuild/bazel/issues/5728) useful link, it should be C++11.
But then again it still gives another error(:weary:) and idk lol:

```
bazel build --incompatible_remove_native_http_archive=false --config=opt --copt=-mavx --copt=-mavx2 //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/neel/Programming_Workspace/Not-My-Repos/tensorflow/tools/bazel.rc
WARNING: ignoring _JAVA_OPTIONS in environment.
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 21869764-322c-4760-a2a6-8154b2fb6acf
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@kafka//': Traceback (most recent call last):
	File "/home/neel/Programming_Workspace/Not-My-Repos/tensorflow/third_party/repo.bzl", line 106
		_apply_patch(ctx, ctx.attr.patch_file)
	File "/home/neel/Programming_Workspace/Not-My-Repos/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
		fail("patch command is not found, ple...")
patch command is not found, please install it
INFO: Elapsed time: 26.139s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (225 packages loaded, 3756 targets\
 configured)
    Fetching @com_google_absl; fetching 9s
    Fetching @double_conversion; fetching
    Fetching @aws; fetching
    Fetching @kafka; fetching
```

**Comment by OtakuSenpai** [comment]
So, here it goes...
I for Kafka i found [this](https://github.com/tensorflow/tensorflow/issues/23817) issue helpful, but then again i felt into another issue with the '@io_bazel_rules_closure//closure' package. 

Here's a log of the command:

```
bazel build //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/neel/Programming_Workspace/Not-My-Repos/tensorflow/tools/bazel.rc
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: ignoring _JAVA_OPTIONS in environment.
Starting local Bazel server and connecting to it...
ERROR: /home/neel/Programming_Workspace/Not-My-Repos/tensorflow/WORKSPACE:3:1: name 'http_archive' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package
INFO: Elapsed time: 5.856s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

According to [this](https://github.com/tensorflow/tensorflow/issues/7497) issue, it happens either due to [not using Oracle JDK](https://github.com/tensorflow/tensorflow/issues/7497#issuecomment-355743662) or having [OpenJDK's certs being old](https://github.com/tensorflow/tensorflow/issues/7497#issuecomment-388485871). The later I tried using this command, and then copying it to the correct position for my distro(/usr/lib/jvm/openjdk-1.8.0_202/jre/lib/security/):

```
mkcacerts -f /etc/ssl/certs.pem -o cacerts -k $(which keytool) -s $(which openssl)
```

Both of these didn't help. If this doesn't get solve then I don't think I'll be able to use C++ for Tensorflow, and be forced to use Python.

Note 
------
I was initially doing the building using bazel 0.22. Then later on while surfing the net I saw that building Tensorflow using older versions of bazel give strange issues like [this one](https://github.com/tensorflow/tensorflow/issues/22898) which i got reference from [this one](https://github.com/google/flatbuffers/pull/5174).

Hope this helps anyone. If someone can solve this issue then please suggest a workaround.

**Comment by gunan** [comment]
In your initial error log,  I see this:
```
patch command is not found, please install it
```

Could you try that?

**Comment by OtakuSenpai** [comment]
Yeah, my distro doesn't include patch command by default.
I had to install it then run them. The results above where with patch installed.

**Comment by gunan** [comment]
I think many errors I see are due to configure script not being run properly, I know for sure that "REPOSITORY_NAME" issue is due to that.

Moreover, I think your bazel version may be too new. For 1.12, we used 0.15 to build the branch.
https://www.tensorflow.org/install/source#linux
And I think 0.22 is not even tested with 1.13 yet.

**Comment by OtakuSenpai** [comment]
Ok let me try with bazel 0.15

**Comment by OtakuSenpai** [comment]
Ok, on the same system with same everything, and using bazel 0.15 I'm getting this error:
```
bazel build //tensorflow/tools/pip_package:build_pip_package
WARNING: ignoring _JAVA_OPTIONS in environment.
Starting local Bazel server and connecting to it...
.............................
WARNING: /home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/grpc/BUILD:1992:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_common.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: /home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/grpc/BUILD:1992:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_decode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: /home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/grpc/BUILD:1992:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_encode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/grpc/bazel/grpc_build_system.bzl:172:12
ERROR: /home/neel/Programming_Workspace/Not-My-Repos/tensorflow/tensorflow/tools/pip_package/BUILD:132:1: no such package '@icu//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz, https://github.com/unicode-org/icu/archive/release-62-1.tar.gz] to /home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/icu/release-62-1.tar.gz: Checksum was 33d08fc296d7ca8165ff1091f61ea998b61139aec353c295168b49407123099b but wanted e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761 and referenced by '//tensorflow/tools/pip_package:licenses'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@icu//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz, https://github.com/unicode-org/icu/archive/release-62-1.tar.gz] to /home/neel/.cache/bazel/_bazel_neel/e655abc18ce719a580533b95739e1032/external/icu/release-62-1.tar.gz: Checksum was 33d08fc296d7ca8165ff1091f61ea998b61139aec353c295168b49407123099b but wanted e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761
INFO: Elapsed time: 408.008s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (191 packages loaded)
```
Hope that helps.

**Comment by gunan** [comment]
```
Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz, https://github.com/unicode-org/icu/archive/release-62-1.tar.gz]
```
Network issues?

**Comment by OtakuSenpai** [comment]
No, my network is working fine. I even downloaded other >200 bazel packages plus some study videos later. Idk.
Maybe I could try to wget that host. But it's almost 11pm.  Maybe tomorrow.

**Comment by gunan** [comment]
Bazel reports that it had difficulty downloading those specific links, so even if your network is working fine,  bazel is having problems with your network.

**Comment by OtakuSenpai** [comment]
So what should I do? To resolve that issue?

**Comment by gunan** [comment]
You can try running wget, and seeing if that works. if it does not, you may be behind a firewall, or may need a proxy. If it does works, it may just be a flake.

**Comment by OtakuSenpai** [comment]
Can you give an example of using wget along with bazel. It was hectic this 5 days and I'm unsure where to place the downloaded packages in the tensor flow directory.
Thanks alot

**Comment by mcjjin** [comment]
Hi guys I have the same error with 
bazel build tensorflow/tools/graph_transforms:summarize_graph

INFO: Invocation ID: 21b504b6-1730-45a1-b022-0a26498210e3
ERROR: D:/workspaces/tensorflow/third_party/eigen3/BUILD:34:1: no such package '@eigen_archive//': Traceback (most recent call last):
        File "D:/workspaces/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "D:/workspaces/tensorflow/third_party/repo.bzl", line 73, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "D:/workspaces/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/kobe/_bazel_kobe/xjytsuoi/external/eigen_archive" "-i" "D:/workspaces/tensorflow/third_party/eigen3/gpu_packet_math.patch"':
Stdout:
Stderr: /usr/bin/bash: patch: 鏈壘鍒板懡浠? and referenced by '//third_party/eigen3:eigen3'
ERROR: Analysis of target '//tensorflow/tools/graph_transforms:summarize_graph' failed; build aborted: no such package '@eigen_archive//': Traceback (most recent call last):
        File "D:/workspaces/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "D:/workspaces/tensorflow/third_party/repo.bzl", line 73, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "D:/workspaces/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/kobe/_bazel_kobe/xjytsuoi/external/eigen_archive" "-i" "D:/workspaces/tensorflow/third_party/eigen3/gpu_packet_math.patch"':
Stdout:
Stderr: /usr/bin/bash: patch: 鏈壘鍒板懡浠?Analyzing: target //tensorflow/tools/graph_transforms:summarize_graph (1 paINFO: Elapsed time: 4.763s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 2 targets configured)
    Fetching @eigen_archive; fetching 4s

**Comment by yonghenghuanmie** [comment]
> 
> 
> Hi guys I have the same error with
> bazel build tensorflow/tools/graph_transforms:summarize_graph
> 
> INFO: Invocation ID: 21b504b6-1730-45a1-b022-0a26498210e3
> ERROR: D:/workspaces/tensorflow/third_party/eigen3/BUILD:34:1: no such package '@eigen_archive//': Traceback (most recent call last):
> File "D:/workspaces/tensorflow/third_party/repo.bzl", line 106
> _apply_patch(ctx, ctx.attr.patch_file)
> File "D:/workspaces/tensorflow/third_party/repo.bzl", line 73, in _apply_patch
> _execute_and_check_ret_code(ctx, cmd)
> File "D:/workspaces/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
> fail("Non-zero return code({1}) when ...))
> Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/kobe/_bazel_kobe/xjytsuoi/external/eigen_archive" "-i" "D:/workspaces/tensorflow/third_party/eigen3/gpu_packet_math.patch"':
> Stdout:
> Stderr: /usr/bin/bash: patch: 鏈壘鍒板懡浠? and referenced by '//third_party/eigen3:eigen3'
> ERROR: Analysis of target '//tensorflow/tools/graph_transforms:summarize_graph' failed; build aborted: no such package '@eigen_archive//': Traceback (most recent call last):
> File "D:/workspaces/tensorflow/third_party/repo.bzl", line 106
> _apply_patch(ctx, ctx.attr.patch_file)
> File "D:/workspaces/tensorflow/third_party/repo.bzl", line 73, in _apply_patch
> _execute_and_check_ret_code(ctx, cmd)
> File "D:/workspaces/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
> fail("Non-zero return code({1}) when ...))
> Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/kobe/_bazel_kobe/xjytsuoi/external/eigen_archive" "-i" "D:/workspaces/tensorflow/third_party/eigen3/gpu_packet_math.patch"':
> Stdout:
> Stderr: /usr/bin/bash: patch: 鏈壘鍒板懡浠?Analyzing: target //tensorflow/tools/graph_transforms:summarize_graph (1 paINFO: Elapsed time: 4.763s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (1 packages loaded, 2 targets configured)
> Fetching @eigen_archive; fetching 4s

I solved this problem just few minutes ago.
https://github.com/tensorflow/tensorflow/issues/21880#issuecomment-476599931

**Comment by gunan** [comment]
I was simply recommending running wget from your terminal with the links that are failing to download. I do not think you can run "bazel with wget", or vice versa.

Closing the issue, as the remaining problem is a network issue on user side, and we cannot do anything from our end, as all of our servers and mirrors are live and green from our end. Maybe check your firewall, or contact your network administrator or ISP.
