### ISSUE TITLE
models/image/mnist/convolutional.py failed on GTX 980!

### ISSUE THREAD

**Issue by mmrezaie** [tensorflow/tensorflow#262]
NVidia Driver Ver: 355.11

I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:345] Aggregate Region Memory: 2990620672 (2.79GiB)
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:347] Aggregate Chunk Memory: 2903089152 (2.70GiB)

Probably because GPU has only 4GB of memory.

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/issues/136 - deduping
