### ISSUE TITLE
How to run the examples/android in Windows Environment?

### ISSUE THREAD

**Issue by Ekinkit** [tensorflow/tensorflow#26205]
**System information**
Windows 8 cpu
- TensorFlow installed from (source or binary):
- TensorFlow version:1.12.0
- Python version:3.6
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):no

**Describe the problem**
I have searched a huge amounts of information about how to use this example but the problem is that most of people are using it on the linux OS. I don't know how to run it on my Windows OS with android studio. Need I install .jar & .so file?And how to deploy the android studio?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by Ayush517** [comment]
@Ekinkit Hi! I have mentioned some links below. Can you please take a look at these.

TFLite code Repository : https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite
TFLite Website Guide : https://www.tensorflow.org/lite/overview
TFLite Github Guide : https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/guide/android.md

As stated by @jvishnuvardhan , try posting this question at Stackoverflow and close this issue. Thank you 😄

**Comment by Ekinkit** [comment]
@Ayush517 Thank you for your reply~
