### ISSUE TITLE
TensorFlow device GPU:0 was not registered

### ISSUE THREAD

**Issue by YoussefShoeb** [tensorflow/tensorflow#26208]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Red Hat Enterprise Linux Server release 7.4
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.10.0
- Python version: 3.6.6
- CUDA/cuDNN version: V9.2.88
- GPU model and memory: Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz

**Describe the current behavior**
Currently I am using distributed Tensorflow to connect two machines one with only a CPU(ps) and one with a CPU and GPU(worker), the worker machine runs only the cluster and server commands followed by a join command and then remains idle, 
the training algorithm is run on the ps machine after defining the cluster and the server and then the training is run but I get "E tensorflow/core/grappler/clusters/utils.cc:128] Not found: TensorFlow device GPU:0 was not registered" between each epoch of training and it is not run on the gpu (the delay is very big)
**Describe the expected behavior**
the training should be able to run on the GPU of the worker machine

**Code to reproduce the issue**
Code run on the worker machine :
import tensorflow as tf

cluster = tf.train.ClusterSpec({
    "worker": [
        "172.24.145.121:2222",
    ],
    "ps": [
        "172.24.145.14:2222"
    ]})
server = tf.train.Server(cluster, job_name="worker", task_index=0)
server.join()

and on the ps machine:
import tensorflow as tf
import time
from tensorflow.examples.tutorials.mnist import input_data

cluster = tf.train.ClusterSpec({
    "worker": [
        "172.24.145.121:2222",
    ],
    "ps": [
        "172.24.145.14:2222"
    ]})
server = tf.train.Server(cluster, job_name="ps", task_index=0)

tf.logging.set_verbosity(tf.logging.ERROR)
mnist = input_data.read_data_sets("/tmp/data",one_hot=True)

n_nodes_hl1=500
n_nodes_hl2=500
n_nodes_hl3=500

n_classes = 10
batch_size = 100
x = tf.placeholder('float',[None, 784],name="x")
y = tf.placeholder('float',name="y_pred")

def neural_network_model(data):
    with tf.device("/job:worker/task:0/gpu:0"):
    	hidden_1_layer= {'weights':tf.Variable(tf.random_normal([784, n_nodes_hl1]),name="layer1_w"),
                    	'biases':tf.Variable(tf.random_normal([n_nodes_hl1]),name="layer1_b")}

    	hidden_2_layer= {'weights':tf.Variable(tf.random_normal([n_nodes_hl1, n_nodes_hl2]),name="layer2_w"),
                	    'biases':tf.Variable(tf.random_normal([n_nodes_hl2]),name="layer2_b")}

    	hidden_3_layer= {'weights':tf.Variable(tf.random_normal([n_nodes_hl2, n_nodes_hl3]),name="layer3_w"),
            	        'biases':tf.Variable(tf.random_normal([n_nodes_hl3]),name="layer3_b")}

    	output_layer= {'weights':tf.Variable(tf.random_normal([n_nodes_hl3, n_classes]),name="output_w"),
        	            'biases':tf.Variable(tf.random_normal([n_classes]),name="output_b")}

    l1= tf.add(tf.matmul(data,hidden_1_layer['weights']),hidden_1_layer['biases'],name="l1")
    l1= tf.nn.relu(l1)

    l2= tf.add(tf.matmul(l1,hidden_2_layer['weights']),hidden_2_layer['biases'],name="l2")
    l2= tf.nn.relu(l2)

    l3= tf.add(tf.matmul(l2,hidden_3_layer['weights']),hidden_3_layer['biases'],name="l3")
    l3= tf.nn.relu(l3)

    output= tf.add(tf.matmul(l3,output_layer['weights']),output_layer['biases'],name="output")

    return output

def train_neural_network(x):
    prediction=neural_network_model(x)
    cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits_v2(logits=prediction,labels=y))

    optimizer = tf.train.AdamOptimizer().minimize(cost)

    hm_epoch = 10
   with tf.Session(server.target) as sess:
        sess.run(tf.global_variables_initializer())
        for epoch in range(hm_epoch):
            epoch_loss =0 
            start_time = time.time()
            for _ in range(int(mnist.train.num_examples/batch_size)): #(X_train.size/(28*28))
                epoch_x,epoch_y=mnist.train.next_batch(batch_size)  
                _,c = sess.run([optimizer, cost], feed_dict = {x:epoch_x, y:epoch_y})
                epoch_loss += c
            duration = time.time()-start_time
            print('Epoch', epoch+1,'completed out of ',hm_epoch,'loss: ',epoch_loss)
            correct = tf.equal(tf.argmax(prediction,1),tf.argmax(y,1))
            accuracy = tf.reduce_mean(tf.cast(correct,'float'))
            print('Accuracy:' ,accuracy.eval({x:mnist.test.images,y:mnist.test.labels}),' Duration: ' ,duration)
train_neural_network(x)

**Other info / logs**
 E tensorflow/core/grappler/clusters/utils.cc:128] Not found: TensorFlow device GPU:0 was not registered

**Comment by frankchn** [comment]
Can you run the following to check whether TensorFlow is actually seeing your GPUs? If not, you might want to try reinstalling CUDA/CuDNN and TensorFlow (make sure you are using the GPU binaries for TF).

Alternatively, you might also want to try our docker images with a bunch of those built-in: https://www.tensorflow.org/install/docker

```
import tensorflow as tf
with tf.Session() as s:
  print(s.list_devices())
```

**Comment by YoussefShoeb** [comment]
TensorFlow sees the GPU if I run the master session from the node that has the GPU, but if I start the master session is from the node that only has cpu I get the TensorFlow device GPU:0 was not registered, even though I can run variables on the cpu of the other node that has both the GPU and CPU

**Comment by frankchn** [comment]
So if you do something like

```
import tensorflow as tf
s = tf.Session(master="grpc://remote.server.ip.address:port")
print(s.list_devices())
```

you won't see GPU, but if you run that snippet locally you will? I wonder if the local version you run with Python is different somehow than the remote server you start?

**Comment by YoussefShoeb** [comment]
Well, When I ran this snippet it `import tensorflow as tf
s = tf.Session(master="grpc://remote.server.ip.address:port")
print(s.list_devices())` it shows all the devices correctly and after a bit of testing there is indeed improved performance which shows that the GPU of the remote server is being used, but 
> E tensorflow/core/grappler/clusters/utils.cc:128] Not found: TensorFlow device GPU:0 was not registered

> 

Keeps showing up between each of the epoch's in training when the the master session is initiated on the node with only the cpu.  I don't get this error when I initiate the master session and run the training on the node that contains the gpu and cpu, and use the other cpu node remotely.

**Comment by frankchn** [comment]
Can you show what `s.list_devices()` return? Also, in your original script, you are assigning tasks to `/job:worker/task:0/gpu:0`, however the [canonical TensorFlow device names](https://www.tensorflow.org/guide/using_gpu#using_multiple_gpus) for GPUs are in the format `/job:worker/task:0/device:gpu:0`, so that might be an issue as well.

**Comment by YoussefShoeb** [comment]
ok after changing from `/job:worker/task:0/gpu:0` to `/job:worker/task:0/device:GPU:0` there was no difference i still get the 
> `E tensorflow/core/grappler/clusters/utils.cc:128] Not found: TensorFlow device GPU:0 was not registered` 

> 

and `s.list_devices()` returns `W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:349] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
[_DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 268435456), _DeviceAttributes(/job:worker/replica:0/task:0/device:GPU:0, GPU, 11281927373), _DeviceAttributes(/job:ps/replica:0/task:0/device:CPU:0, CPU, 268435456)]`
The same devices are there if i run the session from locally or remotely the only difference is if I run it remotely i dont get the
> `E tensorflow/core/grappler/clusters/utils.cc:128] Not found: TensorFlow device GPU:0 was not registered`

**Comment by frankchn** [comment]
> The same devices are there if i run the session from locally or remotely the only difference is if I run it remotely i dont get the

Do you mean if you run it locally on the machine with the GPU you don't get the error?

Can you also try passing in a cluster_def when you create the session?

```
cluster_spec = tf.train.ClusterSpec( ... )
cluster_def = cluster_spec.as_cluster_def()
with tf.Session(target=master, config=tf.ConfigProto(cluster_def=cluster_def, log_device_placement=True)):
  ...
```

**Comment by YoussefShoeb** [comment]
Yes, if I run it locally on the machine with the GPU I don't get the error, also if I run the session remotely on the machine with the GPU using the CPU machine I don't get the error (using the ` tf.Session("grpc://remote.server.ip.address:port")` ), but if I start the session on the machine with only the CPU I get the error.

**Comment by YoussefShoeb** [comment]
when i try to pass the cluster_def when I create the session I get this error
`tensorflow.python.framework.errors_impl.InvalidArgumentError: The ClusterSpec names the job and task index to be the same names that were provided when the server booted. This is currently not allowed. Job: ps, task index: 0`

**Comment by frankchn** [comment]
Can you create both `tf.train.Server`s without passing in the ClusterSpec? ClusterSpec propagation only works when there are no conflicting types.

**Comment by YoussefShoeb** [comment]
Yes

**Comment by frankchn** [comment]
So does it work without the ClusterSpec?

**Comment by frankchn** [comment]
Closing issue for now, feel free to re-open if this continues to be an issue.

**Comment by colmantse** [comment]
@frankchn Hi, do you mean the clusterspec for the server.start() and server.join() are different thats why it raises "Not found: TF GPU device with id 0 was not registered." ? because i got the same issue as well but i thought tf.train.Server must take clusterspec as argument.

**Comment by frankchn** [comment]
@colmantse Can you open another issue with more complete details? That error happens when TensorFlow cannot detect GPUs in your system.

**Comment by colmantse** [comment]
hi, thanks for the prompt reply. I suspect it has to do with me passing the wrong configproto when starting the server. i will come back tmr if it is not the case. many thanks!
