### ISSUE TITLE
tf.graph_util.convert_variables_to_constants converts a different  pb parameters with orginal ckpt

### ISSUE THREAD

**Issue by liuheng92** [tensorflow/tensorflow#26203]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
**The result using 'tf.graph_util.convert_variables_to_constants' api is different with 'freeze_graph.freeze_graph'**
when i use 'freeze_graph.freeze_graph',  the result is same as ckpt， but different with the output when i use use 'tf.graph_util.convert_variables_to_constants' api. Why???

```python
# using 'tf.graph_util.convert_variables_to_constants' api
    with tf.get_default_graph().as_default():
        input_images = tf.placeholder(tf.float32, shape=[None, None, None, 3], name = 'input_images')
        

        input_images = readdata.mean_image_subtraction(input_images)

        with slim.arg_scope(resnet_v1.resnet_arg_scope(weight_decay=1e-5)):
            outputs, _ = resnet_v1.resnet_v1_50(input_images,  is_training=False, scope='resnet_v1_50', num_classes=FLAGS.num_classes)
            saver = tf.train.Saver()

            with tf.Session(config=tf.ConfigProto(allow_soft_placement=True)) as sess:
                tf.train.write_graph(sess.graph.as_graph_def(), '.', 'resnet50.pbtxt', as_text=False)
                saver.restore(sess, '../model.ckpt-5723')

                pb_file_path = 'model_5723.pb'
                constant_graph = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def,["resnet_v1_50/predictions/Softmax"])

                with tf.gfile.FastGFile(pb_file_path, mode='wb') as f:
                    f.write(constant_graph.SerializeToString())
```
```python
#using 'freeze_graph' api
    with tf.get_default_graph().as_default():
        input_images = tf.placeholder(tf.float32, shape=[None, None, None, 3], name = 'input_images')
        

        input_images = readdata.mean_image_subtraction(input_images)

        with slim.arg_scope(resnet_v1.resnet_arg_scope(weight_decay=1e-5)):
            outputs, _ = resnet_v1.resnet_v1_50(input_images,  is_training=False, scope='resnet_v1_50', num_classes=FLAGS.num_classes)

            saver = tf.train.Saver()

            with tf.Session(config=tf.ConfigProto(allow_soft_placement=True)) as sess:
                tf.train.write_graph(sess.graph.as_graph_def(), '.', 'resnet50.pbtxt', as_text=False)

                freeze_graph.freeze_graph('./resnet50.pbtxt', "", True, '../model.ckpt-5723', "resnet_v1_50/predictions/Softmax", "save/restore_all", "save/Const:0","model_freeze.pb", True, "")
                
```
**Describe the expected behavior**
using 'tf.graph_util.convert_variables_to_constants' api , the output parameters should be same as ckpt.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by skye** [comment]
@petewarden do you know anything about graph freezing functionality?

Unfortunately I think tf.graph_util.convert_variables_to_constants is deprecated, so I'm not sure if we have the bandwidth to address this.

**Comment by liuheng92** [comment]
> @petewarden do you know anything about graph freezing functionality?
> 
> Unfortunately I think tf.graph_util.convert_variables_to_constants is deprecated, so I'm not sure if we have the bandwidth to address this.

oh, I see. I found a warning in [tensorflow api docs](https://www.tensorflow.org/api_docs/python/tf/graph_util/convert_variables_to_constants). But I am using old version(1.4.0), there is no api named "tf.compat.v1.graph_util.convert_variables_to_constants". So which api can I use for converting ckpt to pb？"freeze_graph.freeze_graph" api？

**Comment by skye** [comment]
cc @gargn

**Comment by gargn** [comment]
`freeze_graph.freeze_graph` calls `tf.graph_util.convert_variables_to_constants` it is likely a problem with how you are loading your checkpoints with the Saver. I would suggest looking at how `freeze_graph.freeze_graph` restores the checkpoint files in order to see what is going wrong.

Loading `pbtxt` + checkpoints file can look something more like the following:
```
import os
import google3
import tensorflow as tf
from google.protobuf import text_format

def load_graph_in_session(pbtxt_file, checkpoint_file, sess):
  """Loads the graph into the provided session.

  Args:
    pbtxt_file: Text based graph.
    checkpoint_file: Checkpoints file.
    sess: tf.Session to load the graph into.
  """
  # Load pbtxt into GraphDef.
  graph_def = tf.GraphDef()
  with tf.gfile.FastGFile(pbtxt_file, 'r') as f:
    text_format.Merge(f.read(), graph_def)
  _ = tf.import_graph_def(graph_def, name='')

  # Restore variables from checkpoint file.
  var_list = {}
  reader = tf.train.NewCheckpointReader(checkpoint_file)
  var_to_shape_map = reader.get_variable_to_shape_map()

  for key in var_to_shape_map:
    try:
      tensor = sess.graph.get_tensor_by_name(key + ':0')
    except KeyError:
      # This tensor doesn't exist in the graph (for example it's
      # 'global_step' or a similar housekeeping element) so skip it.
      continue
    var_list[key] = tensor

  checkpoint_version = tf.train.SaverDef.V2
  saver = tf.train.Saver(var_list=var_list, write_version=checkpoint_version)
  saver.restore(sess, checkpoint_file)
```

If this doesn't work, can you provide the model files (pbtxt + checkpoint files that you are using), or the minimal model files required to reproduce your error as well as a minimal script to reproduce the error.

**Comment by liuheng92** [comment]
hi, I can't reproduce this issue now. But I get different output results between from ckpt and from pb, though they have same values

**Comment by liuheng92** [comment]
hi, @gargn , I couldn't reproduce this issue. Though ckpt values are as same as pb's, but the inference results are difference. If there is a possible you known why this happens.

**Comment by liuheng92** [comment]
I can't reproduce this issue now. Maybe it's my mistake. sorry for bothering you.
