### ISSUE TITLE
app_loader failure at tensorflow.org makes website unusable

### ISSUE THREAD

**Issue by brisk022** [tensorflow/tensorflow#26210]
**System information**
- TensorFlow version: N/A
- Doc Link: https://www.tensorflow.org/

My locale is set to uk_UA. When I visit https://www.tensorflow.org/, the app_loader.js tries to load https://www.gstatic.com/devrel-devsite/v138ceba75b8052825cb18f1c6025ea06485e9d36137e0fd82d2d54619f803209/tensorflow/js/devsite_app__uk.js (notice the added '__uk' suffix). The file does not exist. Since devsite_app.js provides the main functionality, none of the links, buttons, and selectors that use JavaScript are operational. This includes the top nav bar, the side nav bar, and the search. It also makes it very hard to navigate to APIs and to browse the API pages. It is not possible to change the language, because the language drop-down is also using JavaScript.

The problem persists across different browsers (Firefox, Safari, Chrome, Vivaldi) and I assume it also affects other locales for which a localised devsite_app.js is not available (for instance, Belarusian be, Croatian hr, etc.)

Ideally, the app_loader should check whether the localised version exists. If not, it should load the unlocalised version instead.

I'm sorry if this is not the right place for the bug. However, it is directly related to the documentation and I could not find any other places to submit.

**Comment by lamberta** [comment]
Thanks, Roman.

I've filed an an internal bug against site infra: b/126800213

**Comment by lamberta** [comment]
Marked as fixed in b/116473083
I think this is the same issue as https://github.com/tensorflow/tensorflow/issues/26449
