### ISSUE TITLE
No registered 'Placeholder' OpKernel for XLA_TPU_JIT devices compatible with node {{node tpu_139872799811176/input_2}}

### ISSUE THREAD

**Issue by DHOFM** [tensorflow/tensorflow#26214]
Please have a look at my original post here: https://github.com/tensorflow/tensorflow/issues/26081
 It is no longer a tf.keras problem - now I get 

> RuntimeError: Compilation failed: Compilation failure: Detected unsupported operations when trying to compile graph cluster_15366487156777984482[] on XLA_TPU_JIT: Placeholder (No registered 'Placeholder' OpKernel for XLA_TPU_JIT devices compatible with node {{node tpu_139872799811176/input_2}}
> 	.  Registered:  device='TPU'
>   device='CPU'
>   device='GPU'
>   device='XLA_CPU'
> ){{node tpu_139872799811176/input_2}}

**Comment by jvishnuvardhan** [comment]
@DHOFM Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by DHOFM** [comment]
two weeks ago, I opened this thread, now I have new results:
i reinvented the code and got my training working on TPUs. For this I used a CNN. The CNN trains on TPU without any problem. Changing only the model to mobile net from tf.keras: `from tensorflow.keras.applications import MobileNet` brings us back the error.

![cnn_model_plot](https://user-images.githubusercontent.com/27775323/54422150-1e997b00-470e-11e9-91ac-cc0975681b78.png)
![mobnet_model_plot](https://user-images.githubusercontent.com/27775323/54422155-21946b80-470e-11e9-9606-3652a394de65.png)

You can see the difference in the plot I attached cnn (workin) and (mobnet) not working. Please excuse the large number instead of input layer in con-plot, sometimes plot_model has a problem.

So I guess the mobilenet pertained model of tf.keras is not compatible to TPUs.

**Comment by rjpower** [comment]
Thanks for this report. We're deprecating the tf.contrib.tpu.keras_to_tpu_model functionality in favor of DistributionStrategy, which should be available in the next TF release.

We will confirm that keras.applications work with DistributionStrategy TPU API.

**Comment by ravikyram** [comment]
@DHOFM 

Please, let us know if the issue still persists.Thanks!

**Comment by maxima120** [comment]
I have similar problem with 2.1 using DistributionStrategy. Shall I create new ticket?

**Comment by rjpower** [comment]
Thanks, please do create a new ticket (ideally with a reproduction)!
