### ISSUE TITLE
option for returning *state* sequences in tf.keras.layers.rnn

### ISSUE THREAD

**Issue by andrebeu** [tensorflow/tensorflow#26215]
**System information**
- TensorFlow version (you are using): 1.13
- Are you willing to contribute it (Yes/No): No

Currently tf.keras.layers.RNN has an option for returning the sequnces of outputs `return_sequences`, and an option for returning the final state `return_state`.  Sometimes it is useful to analyze the trajectory of c-states for a given sequence of inputs. Therefore I'd like to recommend including an option to `return_state_sequences` where just like `return_sequences` returns a sequence of outputs, `return_state_sequences` returns the sequence of internal states.

**Comment by oholimoli** [comment]
Is it still not possible to return the states as a sequence?
I'm trying to implement an easy buffer for a subsequent RNN but I need the state as sequence too, not only the last one.

```

import tensorflow as tf
import numpy as np
from tensorflow.keras import backend as K

inputs = np.random.random([2, 7, 4]).astype(np.float32)

class kRNNCell(tf.keras.layers.AbstractRNNCell):
    def __init__(self, units, **kwargs):
        self.units = units
        super().__init__(**kwargs)
    @property
    def output_size(self):
    	return self.units
    @property
    def state_size(self):
        return self.units
    def build(self, input_shape):
        self.built = True
    def call(self, inputs, states):
        prev_output = states[0]
        return prev_output, inputs

rnn_cells = [kRNNCell(4) for _ in range(6)]

stacked_rnn = tf.keras.layers.StackedRNNCells(rnn_cells)

stacked_rnn_layer = tf.keras.layers.RNN(stacked_rnn, return_sequences=False,
      return_state=True)

output = stacked_rnn_layer(inputs)

print(inputs)
print(tf.stack(output, axis=1)[:,:]) # <= this should be a sequence for the next layer
```

**Comment by mohantym** [comment]
Hi @andrebeu !We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!

**Comment by andrebeu** [comment]
hi @mohantym NB this was two years ago, I think i was on the current version.

**Comment by mohantym** [comment]
Hi @andrebeu ,Could you close this issue then?
