### ISSUE TITLE
Any plan to support control flow in TF lite?

### ISSUE THREAD

**Issue by yongwww** [tensorflow/tensorflow#26233]
Seems TF lite doesn't support object detection models like rcnn (https://github.com/tensorflow/tensorflow/issues/19293), I guess it was due to the control flow stuff, is there any plan/timeline to add the support?

**Comment by achowdhery** [comment]
Hi, We support single shot detectors such MobileNet SSD and FPN via the [custom op implementation for NMS ](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/detection_postprocess.cc). We will support control flow in TF Lite soon.

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. If you think I made a mistake, please open another issue. Thanks!
