### ISSUE TITLE
Build failure on s390x on hwloc 

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#26242]
**System information**

    * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04

    * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA

    * TensorFlow installed from (source or binary): source

    * TensorFlow version: master as on today

    * Python version:  2.7.x

    * Bazel version (if compiling from source): 0.19.0 

    * GCC/Compiler version (if compiling from source): gcc 7.3.0, glibc 2.28

    * CUDA/cuDNN version: NA

    * GPU model and memory: NA

**Describe the problem**
Tensorflow build fails with an error:

```
ERROR: /home/jenkins/.cache/bazel/_bazel_jenkins/14d9bef57f8e4d2a0eef0de174c4144b/external/hwloc/BUILD.bazel:212:1: C++ compilation of rule '@hwloc//:hwloc' failed (Exit 1)
In file included from external/hwloc/hwloc/topology-x86.c:23:0:
external/hwloc/hwloc/topology-x86.c: In function 'cpuid_or_from_dump':
external/hwloc/include/private/cpuid-x86.h:67:3: error: inconsistent operand constraints in an 'asm'
   __asm__(
   ^~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by Nayana-ibm** [comment]
Tensorflow CI is failing on dependency hwloc. This is a new dependency added to TensorFlow recently.  
hwloc contains arch specific assembly code which Z don't have support. 

CI link: https://ibmz-ci.osuosl.org/job/TensorFlow_IBMZ_CI/2147/console

**Comment by Nayana-ibm** [comment]
hwloc contains Intel specific assembly code which fails on s390x.  Can you please advise if we can disable this feature? What impact it can make?

**Comment by wdirons** [comment]
ppc64le had the same error, I submitted https://github.com/tensorflow/tensorflow/pull/26220 to fix.

**Comment by jayfurmanek** [comment]
#26220 is merged now. @Nayana-ibm , I see a successful build here:
https://ibmz-ci.osuosl.org/job/TensorFlow_IBMZ_CI/2154/

Should we close this one out?

**Comment by Nayana-ibm** [comment]
Yes. Build is successful after #26220  commit. 
Closing the issue. 

Thanks @wdirons
