### ISSUE TITLE
Compiling TF 1.12 failes under CentOS 6: name 'http_archive' is not defined

### ISSUE THREAD

**Issue by eugenmk** [tensorflow/tensorflow#26249]
**System information**
- _CentOS release 6.9 (Final), Kernel: 4.15.0-45-generic, x86_64_
- TensorFlow installed from (source or binary): _source_
- TensorFlow version: _1.12.0_
- Python version: _3.6.8, 64bit_
- Bazel version (if compiling from source): _Build label: 0.23.0- (@non-git)_ 
   actually Bazel, is build from source too.
- GCC/Compiler version (if compiling from source): _gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)_
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the problem**
I want to use TensorFlow under the system (actually inside a Docker container) specified above (the Linux/GCC/Python versions are fixed).  I get the following error while executing ` bazel build -c opt //tensorflow/tools/pip_package:build_pip_package`

    ERROR: /usr/src/tensorflow/WORKSPACE:3:1: name 'http_archive' is not defined
    ERROR: Error evaluating WORKSPACE file
    ERROR: error loading package '': Encountered error while reading extension 
        file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error
        loading package 'external': Could not load //external package
    ERROR: error loading package '': Encountered error while reading extension 
        file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error 
        loading package 'external': Could not load //external package
    INFO: Elapsed time: 1.276s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (0 packages loaded)
    FAILED: Build did NOT complete successfully (0 packages loaded)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

    FROM amd64/centos:6.9
    
    RUN yum -y install gcc openssl-devel bzip2-devel wget centos-release-scl
    
    # Install bazel
    WORKDIR /usr/src
    RUN yum -y install java-1.8.0-openjdk-devel devtoolset-6
    
    RUN wget https://github.com/bazelbuild/bazel/releases/download/0.23.0/bazel-0.23.0-dist.zip \
        && unzip bazel-*.zip -d /bazel
    
    # Set PATH, because "scl enable" does not have any effects to "docker build"
    ENV PATH /opt/rh/devtoolset-6/root/usr/bin:$PATH
    
    RUN cd /bazel \
        && scl enable devtoolset-6 bash \
        && ./compile.sh \
        && mkdir -p /my/bin/ \
        && cp output/bazel /my/bin \
        && exit
    
    # Install Python new build
    RUN wget https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tgz
    RUN tar xzf Python-3.6.8.tgz
    
    WORKDIR /usr/src/Python-3.6.8
    RUN ./configure --enable-optimizations
    RUN make altinstall
    
     # Install pip
    RUN wget https://bootstrap.pypa.io/get-pip.py
    RUN python3.6 get-pip.py
    
    RUN pip3 install -U pip six numpy wheel mock \
        && pip3 install -U keras_applications==1.0.6 --no-deps \
        && pip3 install -U keras_preprocessing==1.0.5 --no-deps
    
    # Build Tensorflow
    WORKDIR /usr/src/
    RUN yum -y install git

    RUN git clone https://github.com/tensorflow/tensorflow.git \
        && cd /usr/src/tensorflow \
        && git checkout v1.12.0 
    
    WORKDIR /usr/src/tensorflow
    RUN scl enable devtoolset-6 bash \
       && export \
          PATH=$PATH:/my/bin \
          PYTHON_BIN_PATH=/usr/local/bin/python3.6 \
          PYTHON_LIB_PATH=/usr/local/lib/python3.6/site-packages/ \
          TF_NEED_JEMALLOC=0 \
          TF_NEED_GCP=0 \
          TF_NEED_HDFS=0 \
          TF_NEED_S3=0 \
          TF_ENABLE_XLA=0 \
          TF_NEED_GDR=0 \
          TF_NEED_VERBS=0 \
          TF_NEED_OPENCL=0 \
          TF_NEED_CUDA=0 \
          TF_NEED_MPI=0 \
       && ./configure \
       && echo "import /usr/src/tensorflow/tools/bazel.rc" > /usr/src/tensorflow/.bazelrc \
       && bazel build -c opt //tensorflow/tools/pip_package:build_pip_package \
       && mkdir -p /tmp/tensorflow_pkg \
       && bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg \
       && exit

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

    [Non relevant Docker cache logs above]
    
    Step 21/21 : RUN scl enable devtoolset-6 bash    && export       PATH=$PATH:/my/bin       PYTHON_BIN_PATH=/usr/local/bin/python3.6       PYTHON_LIB_PATH=/usr/local/lib/python3.6/site-packages/       TF_NEED_JEMALLOC=0       TF_NEED_GCP=0       TF_NEED_HDFS=0       TF_NEED_S3=0       TF_ENABLE_XLA=0       TF_NEED_GDR=0       TF_NEED_VERBS=0       TF_NEED_OPENCL=0       TF_NEED_CUDA=0       TF_NEED_MPI=0    && ./configure    && echo "import /usr/src/tensorflow/tools/bazel.rc" > /usr/src/tensorflow/.bazelrc    && bazel build -c opt //tensorflow/tools/pip_package:build_pip_package    && exit
     ---> Running in e006e5ffc788
    WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
    /usr/src/tensorflow/tools/bazel.rc
    Extracting Bazel installation...
    WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
    You have bazel 0.23.0- (@non-git) installed.
    Do you wish to build TensorFlow with Apache Ignite support? [Y/n]: Apache Ignite support will be enabled for TensorFlow.
    
    Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: No OpenCL SYCL support will be enabled for TensorFlow.
    
    Do you wish to build TensorFlow with ROCm support? [y/N]: No ROCm support will be enabled for TensorFlow.
    
    Do you wish to download a fresh release of clang? (Experimental) [y/N]: Clang will not be downloaded.
    
    Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
    
    Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: Not configuring the WORKSPACE for Android builds.
    
    Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
    	--config=mkl         	# Build with MKL support.
    	--config=monolithic  	# Config for mostly static monolithic build.
    	--config=gdr         	# Build with GDR support.
    	--config=verbs       	# Build with libverbs support.
    	--config=ngraph      	# Build with Intel nGraph support.
    Configuration finished
    Starting local Bazel server and connecting to it...
    Loading: 
    Loading: 0 packages loaded
    ERROR: /usr/src/tensorflow/WORKSPACE:3:1: name 'http_archive' is not defined
    ERROR: Error evaluating WORKSPACE file
    ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package
    ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package
    INFO: Elapsed time: 1.276s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (0 packages loaded)
    FAILED: Build did NOT complete successfully (0 packages loaded)
    ERROR: Service 'mysys_replica' failed to build: The command '/bin/sh -c scl enable devtoolset-6 bash    && export       PATH=$PATH:/my/bin       PYTHON_BIN_PATH=/usr/local/bin/python3.6       PYTHON_LIB_PATH=/usr/local/lib/python3.6/site-packages/       TF_NEED_JEMALLOC=0       TF_NEED_GCP=0       TF_NEED_HDFS=0       TF_NEED_S3=0       TF_ENABLE_XLA=0       TF_NEED_GDR=0       TF_NEED_VERBS=0       TF_NEED_OPENCL=0       TF_NEED_CUDA=0       TF_NEED_MPI=0    && ./configure    && echo "import /usr/src/tensorflow/tools/bazel.rc" > /usr/src/tensorflow/.bazelrc    && bazel build -c opt //tensorflow/tools/pip_package:build_pip_package    && exit' returned a non-zero code: 1

**Comment by KasparPeterson** [comment]
I have the exact same problem on Ubuntu 18.04. I hope my steps help as well.
```
# Python Dependencies
sudo apt install python3-dev python3-pip
pip3 install -U --user six numpy wheel mock
pip3 install -U --user keras_applications==1.0.6 --no-deps
pip3 install -U --user keras_preprocessing==1.0.5 --no-deps

# Installing Bazel
sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python
wget https://github.com/bazelbuild/bazel/releases/download/0.23.0/bazel-0.23.0-installer-linux-x86_64.sh
chmod +x bazel-0.23.0-installer-linux-x86_64.sh
./bazel-0.23.0-installer-linux-x86_64.sh --user

# Downloading TensorFlow source code
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout r1.12

# Configure the build
./configure
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
```

**Comment by joshpencheon** [comment]
Same issue for me, on CentOS 7.

**Comment by joshpencheon** [comment]
I was able to get past this by adding the following to the `WORKSPACE` file, prior to the `http_archive` call:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
```

**Comment by KasparPeterson** [comment]
I found a workaround by using an older version of bazel(0.17.2)
Hope this helps.

**Comment by eugenmk** [comment]
Thank you,

for both workarounds more errors appear. I think there is something not configured correctly in my case...

@joshpencheon 
> I was able to get past this by adding the following to the `WORKSPACE` file, prior to the `http_archive` call:
> 
> ```
> load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
> ```

Afterwards I get the following

    starting local Bazel server and connecting to it...
    Loading: 
    Loading: 0 packages loaded
    ERROR: /root/.cache/bazel/_bazel_root/cbe8b06b94787a6b39e59564d90f2497/external/io_bazel_rules_closure/closure/compiler/closure_js_deps.bzl:82:17: Traceback (most recent call last):
    	File "/root/.cache/bazel/_bazel_root/cbe8b06b94787a6b39e59564d90f2497/external/io_bazel_rules_closure/closure/compiler/closure_js_deps.bzl", line 78
    		rule(implementation = _impl, attrs = {"...")}, ..."})
    	File "/root/.cache/bazel/_bazel_root/cbe8b06b94787a6b39e59564d90f2497/external/io_bazel_rules_closure/closure/compiler/closure_js_deps.bzl", line 82, in rule
    		attr.label_list(cfg = "data", allow_files = True)
    Using cfg = "data" on an attribute is a noop and no longer supported. Please remove it. You can use --incompatible_disallow_data_transition=false to temporarily disable this check.
    ERROR: error loading package '': in /root/.cache/bazel/_bazel_root/cbe8b06b94787a6b39e59564d90f2497/external/io_bazel_rules_closure/closure/defs.bzl: Extension file 'closure/compiler/closure_js_deps.bzl' has errors
    ERROR: error loading package '': in /root/.cache/bazel/_bazel_root/cbe8b06b94787a6b39e59564d90f2497/external/io_bazel_rules_closure/closure/defs.bzl: Extension file 'closure/compiler/closure_js_deps.bzl' has errors
    INFO: Elapsed time: 1.884s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (0 packages loaded)
    FAILED: Build did NOT complete successfully (0 packages loaded)


@KasparPeterson For the second workaround
> I found a workaround by using an older version of bazel(0.17.2)
> Hope this helps.


 Now I get the following error

     ERROR: /usr/src/tensorflow/tensorflow/contrib/kafka/BUILD:36:1: no such package '@kafka//': Traceback (most recent call last):
    	File "/usr/src/tensorflow/third_party/repo.bzl", line 106
    		_apply_patch(ctx, ctx.attr.patch_file)
    	File "/usr/src/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
    		fail("patch command is not found, ple...")
    patch command is not found, please install it and referenced by '//tensorflow/contrib/kafka:dataset_kernels'
    ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@kafka//': Traceback (most recent call last):
    	File "/usr/src/tensorflow/third_party/repo.bzl", line 106
    		_apply_patch(ctx, ctx.attr.patch_file)
    	File "/usr/src/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
    		fail("patch command is not found, ple...")
    patch command is not found, please install it
    INFO: Elapsed time: 8.806s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (261 packages loaded)
    FAILED: Build did NOT complete successfully (261 packages loaded)

**Comment by joshpencheon** [comment]
@eugenmk yes I got stuck going down that route, and followed @KasparPeterson 's approach of downgrading `bazel` instead. 

```
patch command is not found, please install it
```

Should be resolveable with `yum install patch`.

I'm now having problems along the lines of tensorflow/tensorflow#15129

```
undefined reference to `clock_gettime'
```

...and have as yet been unable to resolve; I think possibly because of anaconda including a different version of `gcc`.

**Comment by eugenmk** [comment]
Using the dowgraded bazel with installed `patch` helped me forward. 
I didn't get the error about undefined reference yet. but after some other fixes I'm at the the following now

    ERROR: /root/.cache/bazel/_bazel_root/cbe8b06b94787a6b39e59564d90f2497/external
        /lmdb/BUILD.bazel:8:1: C++ compilation of rule '@lmdb//:lmdb' failed (Exit 1)
    cc1: error: unrecognized command line option "-fcolor-diagnostics"
    cc1: error: unrecognized command line option "-fno-canonical-system-headers"
    Target //tensorflow/tools/pip_package:build_pip_package failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    INFO: Elapsed time: 58.638s, Critical Path: 0.12s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully
    FAILED: Build did NOT complete successfully

There are hints to upgrade GCC, but this is not possible for my case. I'm relying on the specified version.

**Comment by joshpencheon** [comment]
I've finally got the build to succeed, and didn't come across that issue @eugenmk - but perhaps `
bazel clean -expunge`, as described on tensorflow/tensorflow#15849, might help?

**Comment by alessandromarchetti** [comment]
Had the same exact problem while building graph_transforms tool from r1.11 with latest bazel 0.23.0

Solved by using bazel 0.17.2

**Comment by jvishnuvardhan** [comment]
@eugenmk Could you follow the suggestion listed by the users to resolve the issue. Some time it is better to build it freshly by uninstalling and reinstalling. If it was resolved, then please close the issue. Thanks!

**Comment by eugenmk** [comment]
I achieved the same error as @joshpencheon 

    undefined reference to `clock_gettime'

For solving it, I needed to add ['-lrt'] at different locations of `tensorflow/tensorflow.bzl` file (not sure if all locations are required). Now it compiles, but the tests fails to compile with same link error. At least I can install the python package and import it. Still I have to check if it works properly.

** The changes I did to the `tensorflow/tensorflow.bzl` (Currently I do them manually inside the docker container)
tensorflow/tensorflow.bzl:

	def tf_cc_shared_object(
		name,
		srcs = [],
		deps = [],
		data = [],
		linkopts = [],
		framework_so = tf_binary_additional_srcs(),
		kernels = [],
		**kwargs):
	    native.cc_binary(
		name = name,
		srcs = srcs + framework_so,
		deps = deps + tf_binary_dynamic_kernel_deps(kernels),
		linkshared = 1,
		data = data + tf_binary_dynamic_kernel_dsos(kernels),
		linkopts = linkopts + _rpath_linkopts(name) + select({
		    clean_dep("//tensorflow:darwin"): [
		        "-Wl,-install_name,@rpath/" + name.split("/")[-1],
		    ],
		    clean_dep("//tensorflow:windows"): [],
		    "//conditions:default": [
		        "-Wl,-soname," + name.split("/")[-1],
		    ],
	-        }),
	+        }) + ['-lrt'],
		**kwargs
	    )

	--------------------------
	ef tf_cc_binary(
		name,
		srcs = [],
		deps = [],
		data = [],
		linkopts = [],
		copts = tf_copts(),
		kernels = [],
		**kwargs):
	    native.cc_binary(
		name = name,
		copts = copts,
		srcs = srcs + tf_binary_additional_srcs(),
		deps = deps + tf_binary_dynamic_kernel_deps(kernels) + if_mkl_ml(
		    [
		        clean_dep("//third_party/mkl:intel_binary_blob"),
		    ],
		),
		data = data + tf_binary_dynamic_kernel_dsos(kernels),
	-        linkopts = linkopts + _rpath_linkopts(name),
	+        linkopts = linkopts + _rpath_linkopts(name) + ['-lrt'],
		**kwargs
	    )

	--------------------------

	def tf_cc_test(
		[...]
	   native.cc_test(
		name = "%s%s" % (name, suffix),
		srcs = srcs + tf_binary_additional_srcs(),
		copts = tf_copts() + extra_copts,
		linkopts = select({
		    clean_dep("//tensorflow:android"): [
		        "-pie",
		    ],
		    clean_dep("//tensorflow:windows"): [],
		    clean_dep("//tensorflow:darwin"): [
		        "-lm",
		    ],
		    "//conditions:default": [
		        "-lpthread",
		        "-lm",
		    ],
	-        }) + linkopts + _rpath_linkopts(name),
	+        }) + linkopts + _rpath_linkopts(name) + ['-lrt'],


	--------------------------
	def tf_cuda_only_cc_test(
		...
		deps = deps + tf_binary_dynamic_kernel_deps(kernels) +
		       if_cuda_is_configured([
		           clean_dep("//tensorflow/core:cuda"),
		           clean_dep("//tensorflow/core:gpu_lib"),
		       ]) +
		       if_rocm_is_configured([
		           clean_dep("//tensorflow/core:gpu_lib"),
		       ]),
	-        linkopts = if_not_windows(["-lpthread", "-lm"]) + linkopts + _rpath_linkopts(name) + ['-lrt'],
	+        linkopts = if_not_windows(["-lpthread", "-lm"]) + linkopts + _rpath_linkopts(name),
		linkstatic = linkstatic or select({
		    # cc_tests with ".so"s in srcs incorrectly link on Darwin
		    # unless linkstatic=1.
		    # TODO(allenl): Remove Mac static linking when Bazel 0.6 is out.
		    clean_dep("//tensorflow:darwin"): 1,
		    "//conditions:default": 0,
		}),
		tags = tags + tf_cuda_tests_tags(),
	    )

	--------------------------

	def tf_cc_test_mkl(
		...
	 native.cc_test(
		    name = src_to_test_name(src),
		    srcs = if_mkl([src]) + tf_binary_additional_srcs(),
		    copts = tf_copts(),
		    linkopts = select({
		        clean_dep("//tensorflow:android"): [
		            "-pie",
		        ],
		        clean_dep("//tensorflow:windows"): [],
		        "//conditions:default": [
		            "-lpthread",
		            "-lm",
		        ],
	-            }) + _rpath_linkopts(src_to_test_name(src)),
	+            }) + _rpath_linkopts(src_to_test_name(src)) + ['-lrt'],
		    deps = deps + tf_binary_dynamic_kernel_deps(kernels) + mkl_deps(),
		    data = data + tf_binary_dynamic_kernel_dsos(kernels),
		    linkstatic = linkstatic,

My current Dockerfile:

	FROM amd64/centos:6.9

	RUN yum -y install gcc openssl-devel bzip2-devel wget centos-release-scl

	# Install bazel
	# source: https://blog.abysm.org/2016/06/building-tensorflow-centos-6/
	WORKDIR /usr/src
	RUN yum -y install java-1.8.0-openjdk-devel devtoolset-6

	RUN wget https://github.com/bazelbuild/bazel/releases/download/0.17.2/bazel-0.17.2-dist.zip \
	#RUN wget https://github.com/bazelbuild/bazel/releases/download/0.23.0/bazel-0.23.0-dist.zip \
	    && unzip bazel-*.zip -d /bazel

	RUN gcc --version -v
	# Set PATH, because "scl enable" does not have any effects to "docker build"
	ENV PATH /opt/rh/devtoolset-6/root/usr/bin:$PATH

	RUN cd /bazel \
	    && scl enable devtoolset-6 bash \
	    && ./compile.sh \
	    && mkdir -p /my/bin/ \
	    && cp output/bazel /my/bin \
	    && exit

	# Install Python new build
	RUN wget https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tgz
	RUN tar xzf Python-3.6.8.tgz

	WORKDIR /usr/src/Python-3.6.8
	RUN ./configure --enable-optimizations
	RUN make altinstall

	 # Install pip
	RUN wget https://bootstrap.pypa.io/get-pip.py
	RUN python3.6 get-pip.py

	RUN pip3 install -U pip six numpy wheel mock \
	    && pip3 install -U keras_applications==1.0.6 --no-deps \
	    && pip3 install -U keras_preprocessing==1.0.5 --no-deps

	# ... Build Tensorflow
	WORKDIR /usr/src/
	RUN yum -y install git
	RUN git clone https://github.com/tensorflow/tensorflow.git \
	    && cd /usr/src/tensorflow \
	    && git checkout v1.12.0 

	RUN yum -y install patch g++

	RUN ln -s /usr/local/bin/python3.6 /usr/local/bin/python

	WORKDIR /usr/src/tensorflow
        ###### NOTE
       # AFTER editing of the tensorflow.bzl
      # NEED to execute manually the following steps inside the Docker container. 
	RUN scl enable devtoolset-6 bash \
	   && export \
	#      PATH=/usr/lib/gcc/x86_64-redhat-linux/4.4.7:/usr/local/bin:$PATH:/my/bin \
	      PATH=/usr/local/bin:$PATH:/my/bin \
	      PYTHON_BIN_PATH=/usr/local/bin/python3.6 \
	      PYTHON_LIB_PATH=/usr/local/lib/python3.6/site-packages/ \
	      TF_NEED_JEMALLOC=0 \
	      TF_NEED_GCP=0 \
	      TF_NEED_HDFS=0 \
	      TF_NEED_S3=0 \
	      TF_ENABLE_XLA=0 \
	      TF_NEED_GDR=0 \
	      TF_NEED_VERBS=0 \
	      TF_NEED_OPENCL=0 \
	      TF_NEED_CUDA=0 \
	      TF_NEED_MPI=0 \
	   && ./configure \
	   && sed -i '1i import /usr/src/tensorflow/tools/bazel.rc' /usr/src/tensorflow/.bazelrc \
	   && sed -i '2i load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")' /usr/src/tensorflow/WORKSPACE \
           # TODO: Provide the appropriate target architecture.
	   # && bazel build --march=XXX -c opt //tensorflow/tools/pip_package:build_pip_package \
	   && bazel clean --expunge \
	#   && bazel build --linkopt='-lrt' -c opt //tensorflow/tools/pip_package:build_pip_package \
	#   && mkdir -p /tmp/tensorflow_pkg \
	#   && bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg \
	#   && exit
	      
 I don't want to close the issue, since it not really tested. And I want to provide the Dockerfile for others.

Hope can do it in couple of days.

**Comment by gunan** [comment]
I believe you need an older version of bazel for compiling 1.12 branch.
Please see here for the configurations we tested for building from sources:
https://www.tensorflow.org/install/source#linux

**Comment by gunan** [comment]
After 1.12, our configure script reports what is the minimum and maximum version of bazel you need to use to build TF.
Sorry for the inconvenience, and hopefully we do not run into such issues moving forward.

**Comment by Sam-DevZ** [comment]
For everyone reading this from Google, in case you're not familiar with/are using HomeBrew, I fixed it with:

```
brew uninstall bazel
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/b729cc3bcf6feeb1f49a5f24a509db39926bf1c9/Formula/bazel.rb
```
