### ISSUE TITLE
wav_io needs to accept wav files which has 'JUNK' chunk before 'fmt ' chunk

### ISSUE THREAD

**Issue by combacsa** [tensorflow/tensorflow#26247]
**System information**
- TensorFlow version (you are using): 1.12.0
- Are you willing to contribute it (Yes/No): Not yet decided

**Describe the feature and the current behavior/state.**
Sometimes we encounter wav files which has `JUNK` chunk before `fmt `chunk. CPython's wave module handles this kind of wav files [by skipping those unnecessary chunk](https://github.com/python/cpython/blob/3.6/Lib/wave.py#L125). But tensorflow's wav_io module [expects `fmt ` chunk comes immediately after `WAVE` tag](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/wav/wav_io.cc#L220). As a consequence, those wav files with `JUNK` chunk, which is playable by media file players, generates *Header mismatch* InvalidArgument error.

As a conclusion, we need to implement, I may call it as, unnecessary chunk skipping functionality on wav_io.

**Will this change the current api? How?**
I expect that api won't be affected at all.

**Who will benefit with this feature?**
Those who are handling wide variety of wav files would be benefit with this feature, as they do not have to do some preprocessing(removing `JUNK` chunk manually all the time).

**Any Other info.**
[Kaldi toolkit's handling of wav input](https://github.com/kaldi-asr/kaldi/blob/master/src/feat/wave-reader.cc#L135) would be a good reference.

**Comment by yongtang** [comment]
@combacsa Do you have a small sample file with `JUNK` chunk? I can help create a fix if there is a sample file I could verify.

**Comment by jvishnuvardhan** [comment]
@combacsa Could you share a sample file as requested by @yongtang . If it was resolved with latest TF version, please close the issue. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity, but please let me know if I'm mistaken. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by carlthome** [comment]
@jvishnuvardhan this issue should be reopened. This is still an issue in `tfio.IOTensor.from_audio(path)` and tf.audio.decode_wav(tf.io.read_file(path))` on the latest stable release of TensorFlow and TensorFlow I/O.

**tf.audio.decode_wav**
>InvalidArgumentError: Header mismatch: Expected fmt  but found JUNK [Op:DecodeWav]

**tfio.IOTensor.from_audio**
>InvalidArgumentError: WAV file must contains `fmt ` mark [Op:IO>WAVReadableInit]

**Comment by carlthome** [comment]
And @yongtang, here's an example with a JUNK header:

[example.zip](https://github.com/tensorflow/tensorflow/files/3784317/example.zip)

Seems that it might be about being compatible with CD players and so on: https://www.daubnet.com/en/file-format-riff

**Comment by yongtang** [comment]
@carlthome added a PR in tensorflow/io (https://github.com/tensorflow/io/pull/594)

**Comment by SmileTM** [comment]
@yongtang
Hi, this problem still exists in Tensorflow2.0， could you solve it ？  

Audio WAV files from iOS are not read by Tensorflow audio_ops.decode_wav: Header mismatch: Expected fmt but found JUNK #32382

**Comment by yongtang** [comment]
@SmileTM In https://github.com/tensorflow/io, the latest nightly `pip3 install tensorflow-io-nightly` you can use `tfio.audio.decode_wav`  which should fix this issue.

**Comment by SmileTM** [comment]
> @SmileTM In https://github.com/tensorflow/io, the latest nightly `pip3 install tensorflow-io-nightly` you can use `tfio.audio.decode_wav` which should fix this issue.

It works well. Thank you. 
I think this new `tfio.audio` code should be merged to `tf.audio` .

**Comment by MemoonaTahira** [comment]
Hello @yongtang,

I am using transfer learning for audio using this [tutorial](https://www.tensorflow.org/tutorials/audio/transfer_learning_audio) and I have a few wav files with 'BEXT' chunk and it throws an error. Screenshot attached. 

I am using tensorflow-gpu 2.6 and I tried first with just tfio 0.20.0,
and then after installing tensorflow-io-nightly  0.20.0.dev20210815170710

I have recreated the function load_16k_mono() as discussed here on this thread with `tfio.audio.decode_wav` instead of `tf.audio.decode_wav`

Both functions are exactly same. However, when I use audio files processed through this function for training, I still get the same error.


> 2021-08-17 16:13:21.912804: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at audio_video_wav_kernels.cc:315 : Out of range: EOF reached
> 2021-08-17 16:13:21.916281: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at decode_wav_op.cc:55 : Invalid argument: Data too short when trying to read string
> Traceback (most recent call last):
>   File "C:\Users\Mona\anaconda3\envs\lisnen_work\lib\contextlib.py", line 135, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "C:\Users\Mona\anaconda3\envs\lisnen_work\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2833, in variable_creator_scope
>     yield
>   File "C:\Users\Mona\anaconda3\envs\lisnen_work\lib\site-packages\keras\engine\training.py", line 1184, in fit
>     tmp_logs = self.train_function(iterator)
>   File "C:\Users\Mona\anaconda3\envs\lisnen_work\lib\site-packages\tensorflow\python\eager\def_function.py", line 885, in __call__
>     result = self._call(*args, **kwds)
>   File "C:\Users\Mona\anaconda3\envs\lisnen_work\lib\site-packages\tensorflow\python\eager\def_function.py", line 917, in _call
>     return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
>   File "C:\Users\Mona\anaconda3\envs\lisnen_work\lib\site-packages\tensorflow\python\eager\function.py", line 3039, in __call__
>     return graph_function._call_flat(
>   File "C:\Users\Mona\anaconda3\envs\lisnen_work\lib\site-packages\tensorflow\python\eager\function.py", line 1963, in _call_flat
>     return self._build_call_outputs(self._inference_function.call(
>   File "C:\Users\Mona\anaconda3\envs\lisnen_work\lib\site-packages\tensorflow\python\eager\function.py", line 591, in call
>     outputs = execute.execute(
>   File "C:\Users\Mona\anaconda3\envs\lisnen_work\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
>     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
> tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
>   (0) Invalid argument:  Function invocation produced OutOfRangeError: EOF reached
> 	 [[{{node PartitionedCall/IO>AudioDecodeWAV}}]]
> 	 [[IteratorGetNext]]
>   (1) Invalid argument:  Function invocation produced OutOfRangeError: EOF reached
> 	 [[{{node PartitionedCall/IO>AudioDecodeWAV}}]]
> 	 [[IteratorGetNext]]
> 	 [[IteratorGetNext/_2]]
> 0 successful operations.
> 0 derived errors ignored. [Op:__inference_train_function_31415]
> 
> Function call stack:
> train_function -> train_function
> 
> 2021-08-17 16:13:29.065415: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at decode_wav_op.cc:55 : Invalid argument: Header mismatch: Expected fmt  but found bext


Here is the full code:

```
import tensorflow as tf
import tensorflow_io as tfio

## tried first with regular tfio, and then after installing tfio nightly

@tf.function
def load_wav_16k_mono(filename):
    """ Load a WAV file, convert it to a float tensor, resample to 16 kHz single-channel audio. """
    file_contents = tf.io.read_file(filename)
    wav, sample_rate = tf.audio.decode_wav(
          file_contents,
          desired_channels=1)
    wav = tf.squeeze(wav, axis=-1)
    sample_rate = tf.cast(sample_rate, dtype=tf.int64)
    wav = tfio.audio.resample(wav, rate_in=sample_rate, rate_out=16000)
    return wav


@tf.function
def load_wav_16k_mono_modified(filename):
    file_contents = tf.io.read_file(filename)

    wav = tfio.audio.decode_wav(file_contents, dtype=tf.int16)
    wav = wav[:, 0]
    wav = tf.cast(wav, tf.float32)

    _, sample_rate = tf.audio.decode_wav(file_contents, desired_channels=1)
    sample_rate = tf.cast(sample_rate, dtype=tf.int64)
    wav = tfio.audio.resample(wav, rate_in=sample_rate, rate_out=16000)

    return wav

testing_wav_file_name = tf.keras.utils.get_file('miaow_16k.wav',
                                                'https://storage.googleapis.com/audioset/miaow_16k.wav',
                                                cache_dir='./',
                                                cache_subdir='test_data')

load_wav_16k_mono (testing_wav_file_name)
load_wav_16k_mono_modified (testing_wav_file_name)

```
I also saw this [code](https://github.com/tensorflow/io/pull/594/files) in one of the issues, and it is handling bext chunks, but probably not tfio.audio.wave_decode?

**Comment by yongtang** [comment]
@MemoonaTahira I created an issue in https://github.com/tensorflow/io/issues/1503, let's follow up there.
