### ISSUE TITLE
InvalidArgumentError Incompatible shapes when multi_gpu_model used on LSTM model in TF 2.0

### ISSUE THREAD

**Issue by ghego** [tensorflow/tensorflow#26245]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-dev20190228
- Python version: 3.7
- CUDA/cuDNN version: 10/7.4
- GPU model and memory:  Tesla M60 on AWS g3.8xlarge

**Describe the current behavior**
`multi_gpu_model` fails to parallelize LSTM model. Things I've tried without success:
- setting  `cpu_relocation=True` parameter
- disabling eager mode

**Describe the expected behavior**
the code below should run instead of giving an error.

**Code to reproduce the issue**

```python
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding
from tensorflow.keras.utils import multi_gpu_model

vocab_size= 20000
maxlen=80

(X_train, y_train), (X_test, y_test) = \
    imdb.load_data(num_words=vocab_size)

X_train_pad = pad_sequences(X_train, maxlen=maxlen)
X_test_pad = pad_sequences(X_test, maxlen=maxlen)

with tf.device('/cpu:0'):
    model = Sequential([
        Embedding(vocab_size, 100, input_length=maxlen),
        LSTM(64, dropout=0.2, recurrent_dropout=0.2),
        Dense(1, activation='sigmoid')
    ])

model = multi_gpu_model(model, 2)

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(X_train_pad, y_train,
          batch_size=2048,
          epochs=2,
          shuffle=True)
```

**Other info / logs**

```python
W0301 07:00:25.055628 139938579490560 tf_logging.py:161] <tensorflow.python.keras.layers.recurrent.UnifiedLSTM object at 0x7f45f84f5470>: Note that this layer is not optimized for performance. Please use tf.keras.layers.CuDNNLSTM for better performance on GPU.

Epoch 1/2

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-6-827e285c76cb> in <module>
     33           batch_size=2048,
     34           epochs=2,
---> 35           shuffle=True)

~/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    871           validation_steps=validation_steps,
    872           validation_freq=validation_freq,
--> 873           steps_name='steps_per_epoch')
    874 
    875   def evaluate(self,

~/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
    349 
    350         # Get outputs.
--> 351         batch_outs = f(ins_batch)
    352         if not isinstance(batch_outs, list):
    353           batch_outs = [batch_outs]

~/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/backend.py in __call__(self, inputs)
   3215         value = math_ops.cast(value, tensor.dtype)
   3216       converted_inputs.append(value)
-> 3217     outputs = self._graph_fn(*converted_inputs)
   3218     return nest.pack_sequence_as(self._outputs_structure,
   3219                                  [x.numpy() for x in outputs])

~/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
    523       raise TypeError("Keyword arguments {} unknown. Expected {}.".format(
    524           list(kwargs.keys()), list(self._arg_keywords)))
--> 525     return self._call_flat(args)
    526 
    527   def _filtered_call(self, args, kwargs):

~/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args)
    592     # Only need to override the gradient in graph mode and when we have outputs.
    593     if context.executing_eagerly() or not self.outputs:
--> 594       outputs = self._inference_function.call(ctx, args)
    595     else:
    596       self._register_gradient()

~/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args)
    380             attrs=("executor_type", executor_type,
    381                    "config_proto", config),
--> 382             ctx=ctx)
    383       # Replace empty list with None
    384       outputs = outputs or None

~/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     64     else:
     65       message = e.message
---> 66     six.raise_from(core._status_to_exception(e.code, message), None)
     67   except TypeError as e:
     68     if any(ops._is_keras_symbolic_tensor(x) for x in inputs):

~/miniconda3/envs/tf2/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Incompatible shapes: [1024,64] vs. [2048,64]
	 [[{{node sequential_5_1/unified_lstm_5/while/body/_1008/mul_6}}]]
	 [[training_3/RMSprop/gradients/loss_5/dense_5_loss/binary_crossentropy/Mean_grad/Prod/_842]] [Op:__inference_keras_scratch_graph_32546]
```

**Comment by qlzh727** [comment]
Thanks for reporting the issue and sorry for the late reply. Let me take some time to troubleshoot the issue.

**Comment by ghego** [comment]
Thanks @qlzh727, let me know if I can help you with anything.

**Comment by ghego** [comment]
Is `multi_gpu_model` not recommended any longer with TF 2.0 ?

**Comment by qlzh727** [comment]
In 2.0  we will recommend user to use distribution strategy. Having said that, I don't see the multi_gpu_model gets deprecated, @fchollet, should we actually deprecate multi_gpu_model in v2 since istribution strategy is the new recommended way for model sharding?

**Comment by ghego** [comment]
Update on this bug:
replacing `LSTM(64, dropout=0.2, recurrent_dropout=0.2)` with `LSTM(64, dropout=0.2)` in the model definition runs fine, albeit the warnings:

```python
W0321 18:52:50.309778 140426690877184 tf_logging.py:161] <tensorflow.python.keras.layers.recurrent.UnifiedLSTM object at 0x7fb7748c2748>: Note that this layer is not optimized for performance. Please use tf.keras.layers.CuDNNLSTM for better performance on GPU.
W0321 18:52:50.793717 140426690877184 deprecation.py:506] From /home/ubuntu/miniconda3/envs/myenv/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4081: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
```

I suspect the problem is somewhere in the new bundled LSTM layer that automatically chooses where to allocate the weights and whether to use CuDNN or not. In fact CuDNN layers need to be on the GPU and do not support `recurrent_dropout`.

Also, notice that when the LSTM layer is defined without the recurrent dropout, it's allocated on the GPU regardless of the context setter. This seems similar to #26244

**Comment by qlzh727** [comment]
Interesting, thanks for sharing the finding, which will narrow down the cause of the issue. 

Regarding to the device context, it has been recently updated with https://github.com/tensorflow/tensorflow/commit/584ad2f575ffc644accb8f0d8c4e1038edd42412. You can try updating your installed TF with nightly-2.0-preview and it should fixed issue.

**Comment by ghego** [comment]
Looks like nightly builds are not available for mac py3.7? I get: 

```bash
$ pip install tf-nightly-2.0-preview
Collecting tf-nightly-2.0-preview
  Could not find a version that satisfies the requirement tf-nightly-2.0-preview (from versions: )
No matching distribution found for tf-nightly-2.0-preview
```

I'll try on linux

**Comment by kylekyle** [comment]
Still getting this error in `2.1.0`. Am I doing something wrong? I also get the `No matching distribution` error trying to install the nightly build on Ubuntu ....

**Comment by kylekyle** [comment]
Switching to `MirroredStrategy` seemed to fix it. Although I still can't install the nightly build ....

**Comment by rmothukuru** [comment]
@ghego,
It is recommended to use [Distribution Strategy](https://www.tensorflow.org/api_docs/python/tf/distribute) over **`multi_gpu_model`**. Even the documentation of **`multi_gpu_model`** is not available in the [Tensorflow Site](https://www.tensorflow.org/api_docs/python/tf/keras/utils/multi_gpu_model?language=zh_cn). 
Please refer the documentation for [Distributed Training using Keras](https://www.tensorflow.org/tutorials/distribute/keras) and [Distributed Training Using Tensorflow](https://www.tensorflow.org/guide/distributed_training) for more information
Thanks!

**Comment by ghego** [comment]
Yes, this issue is 3 years old. I'm aware that Distribution Strategy is the way to go. I'll close it.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
