### ISSUE TITLE
cuda 9 or 10

### ISSUE THREAD

**Issue by helonayala** [tensorflow/tensorflow#26254]
TF installation via pip is pointing to 1.13.1, requiring CUDA 10, while in the documentation it's mentioned CUDA 9

In order to install via pip for cuda 9 one should
> pip3 install tensorflow-gpu==1.12.0

see
https://github.com/tensorflow/tensorflow/issues/26209

**Comment by jvishnuvardhan** [comment]
@helonayala Could you point us where you are seeing CUDA 9 for TF 1.13.1? Please check release notes [here](https://github.com/tensorflow/tensorflow/releases/tag/v1.13.1) that mentions "TensorFlow GPU binaries are now built against CUDA 10". As the TF.1.13.1 was built against CUDA10, it will look for CUDA10 path. If you have CUDA9.0, please upgrade it to CUDA 10 and then install tensorflow. Thanks!

**Comment by blemke** [comment]
On https://www.tensorflow.org/install/gpu it suggests CUDA 9.0 for Tensorflow generally, but doesn't specifically mention 1.13.1.

I had issues using CUDA 10.1 with Tensorflow 1.13.1, but resolved them by switching to CUDA 10.0

**Comment by helonayala** [comment]
yep, in the link @blemke  provided

**Comment by jvishnuvardhan** [comment]
Thanks @helonayala @blemke. Those instructions are for TF 1.12. Team is working on updating them for latest version. Stay tuned. Thanks!

Closing this issue.

**Comment by FiReTiTi** [comment]
Same issue for me.
The cluster I use only contains Cuda 9.0, and when I reinstalled tensorflow it automatically installed 1.13.1, which didn't support Cuda 9.
So I downgraded the version to 1.12.2 and it worked.

**Comment by SteffenEpp** [comment]
Hello together, 

do I have to build tensorflow from source to get it running on a compute capability of 3.0?
Or can i just install it with: "pip3 install tensorflow-gpu==1.12.2" ?

**Comment by zacario-li** [comment]
> Hello together,
> 
> do I have to build tensorflow from source to get it running on a compute capability of 3.0?
> Or can i just install it with: "pip3 install tensorflow-gpu==1.12.2" ?

@SteffenEpp use python3.5, then pip install tensorflow-gpu==1.12.2
