### ISSUE TITLE
Support matrix_inverse in XLA

### ISSUE THREAD

**Issue by volvador** [tensorflow/tensorflow#26258]
It seems MatrixInverse op is not supported in the XLA. 

Indeed, trying to `tf.compile` a graph containing a `tf.matrix_inverse` op yields the following error 

    No registered 'MatrixInverse' OpKernel for XLA_CPU_JIT devices compatible with node 

Can you please add that support?

In the meanwhile, can you suggest a workaround to compile a graph containing a matrix_inverse operation? I thought about re-writing the matrix_inverse in terms of LU decomposition, but LU is not supported neither.

**Comment by ymodak** [comment]
@jlebar

**Comment by jlebar** [comment]
> Can you please add that support?

We aren't actively working on this, but patches would be welcome.  See e.g. the recent patches to add Cholesky support.

> In the meanwhile, can you suggest a workaround to compile a graph containing a matrix_inverse operation? 

The workaround is not to use tfcompile.  In JIT mode, you can use autoclustering to avoid sending unsupported operations to XLA.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
