### ISSUE TITLE
MPI call makes `//tensorflow:tf_python_api_gen_v1` fail when building tf-1.12.0 or 1.13.1 on Cray system

### ISSUE THREAD

**Issue by rsarm** [tensorflow/tensorflow#26253]
**System information**
- Cray XC 50 (both login node and compute nodes)
- Bazel-0.18.1 and 0.21.0
- TensorFlow-1.12.0 and 1.13.1
- Python-3.6.5
- GCC-6.2.0
- CUDA-9.1
- cuDNN-7.1.4

**Describe the problem**
We are encountering the following error when building TensorFlow-1.12.0 or 1.13.1:
```
ERROR: /path/to/my/installation/tensorflow-1.13.1/tensorflow/BUILD:573:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 255): bash failed: error executing command 
  (echo of the command that failed)
```
This continues with the echo of the command that failed 
```
/bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/k8-opt/bin/tensorflow/python_api_1_tf_python_api_gen_v1 ...
```
an then at the end there is this
```
Execution platform: @bazel_tools//platforms:host_platform
[Fri Mar  1 09:31:29 2019] [unknown] Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(537): 
MPID_Init(246).......: channel initialization failed
MPID_Init(638).......:  PMI2 init failed: 1 
aborting job:
Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(537): 
MPID_Init(246).......: channel initialization failed
MPID_Init(638).......:  PMI2 init failed: 1 
```
One gets this when trying to run an MPI program on the login node (which is the desired behavior in our system). The message appears twice as if something is trying to execute an MPI program with 2 ranks during the installation. I don't manage to find where this is coming from. The error also occurs if building on a compute node. Is there any option in Bazel to avoid this?

This doesn't happen for TensorFlow-1.11.0 or other older versions that we have build.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Our choices on the `configure` phase for tf-1.13.1 (the same we use for other versions we have compiled):
```
Do you wish to build TensorFlow with XLA JIT support? No
Do you wish to build TensorFlow with OpenCL SYCL support? No
Do you wish to build TensorFlow with ROCm support? No
Do you wish to build TensorFlow with CUDA support? Yes
Please specify the CUDA SDK version you want to use: 9.1
Please specify the cuDNN version you want to use: 7.1.4
Do you wish to build TensorFlow with TensorRT support? No
Please specify the locally installed NCCL version you want to use: 2.2.13
Please specify a list of comma-separated Cuda compute capabilities you want to build with: 6.0
Do you want to use clang as CUDA compiler? No
Please specify which gcc should be used by nvcc as the host compiler: /path/to/gcc-6.2.0
Do you wish to build TensorFlow with MPI support? No
Please specify optimization flags "--config=opt" : -march=native
Android builds? No
```
The bazel command is:
```
bazel build --verbose_failures --distinct_host_configuration=false --action_env=PYTHONPATH=$PYTHONPATH --config=cuda --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.2 --copt=-msse4.1 --cxxopt='-D_GLIBCXX_USE_CXX11_ABI=0' -c opt //tensorflow/tools/pip_package:build_pip_package && bazel-bin/tensorflow/tools/pip_package/build_pip_package $BUILDDIR
```

We also edit `third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl` to replace the paths to the compilers, but this is always the same for every version that we build.

**Comment by rsarm** [comment]
Found the problem. My installation of `h5py`, which is a dependency of `keras_applications`, seemed to have been corrupted. Reinstalling it solved the issue. Sorry for the misunderstanding.

**Comment by jvishnuvardhan** [comment]
Thanks! I am closing the issue as it was resolved. Please open a new ticket if you see similar issue again. Thanks!
