### ISSUE TITLE
Tf.Keras metrics issue 

### ISSUE THREAD

**Issue by AkbarAlam** [tensorflow/tensorflow#26250]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary): Source ( Pip ) 
- TensorFlow version (use command below): 1.13
- Python version: 3.6.7

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

> 1.13.1

**Describe the current behavior**
I need to use Keras metric while compiling an LSTM model. it is getting compiled. But when I started to train I am getting error.

my code looks as follows : 

```
model = Sequential()
model.add(LSTM (120,activation = "tanh", input_shape=(timesteps,dim), return_sequences=True))
model.add(LSTM(120, activation = "tanh", return_sequences=True))
model.add(LSTM(120, activation = "tanh", return_sequences=True))
model.add(LSTM(120, activation = "tanh", return_sequences=True))
model.add(LSTM(120, activation = "tanh", return_sequences=True))
model.add(LSTM(120, activation = "tanh", return_sequences=True))
model.add(Dense(dim))
model.compile(optimizer="adam", loss="mse",  metrics=[tf.keras.metrics.Precision()])

history = model.fit(data,data, 
                    epochs=100,
                    batch_size=10,
                    validation_split=0.2,
                    shuffle=True,
                    callbacks=[ch]).history
```

There error I am getting as follows

> InvalidArgumentError: assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:x (dense_3/BiasAdd:0) = ] [[[2.72658144e-06 1.17555362e-06 1.96436554e-06...]]...] [y (metrics_3/precision_1/Cast/x:0) = ] [0] [[{{node metrics_3/precision_1/assert_greater_equal/Assert/AssertGuard/Assert}}]]

**Comment by qlzh727** [comment]
Assigning to Pavithra who is the owner of metric/loss.

**Comment by pavithrasv** [comment]
@AkbarAlam Precision metric takes predictions as probabilities, hence the error `predictions must be >= 0`. For this you will need to add `sigmoid` (if dim == 1) or `softmax` (for dim > 1) activation function to the last dense layer.

**Comment by AkbarAlam** [comment]
@pavithrasv Thanks for the input. Let me check if that  works

**Comment by AkbarAlam** [comment]
@pavithrasv I dont know if this is the right config. But as you suggested I have done it
 
it looks as follows

```
model = Sequential()
model.add(LSTM (120,activation = "tanh", input_shape=(timesteps,dim), return_sequences=True))
model.add(LSTM(120, return_sequences=True))
model.add(LSTM(120, return_sequences=True))
model.add(LSTM(120, return_sequences=True))
model.add(LSTM(120, return_sequences=True))
model.add(LSTM(120, return_sequences=True))
model.add(Dense(dim, activation="softmax"))
```

**Comment by pavithrasv** [comment]
Output of the LSTM layer will be 3D (samples, timesteps, features) because of return_sequences being enabled. Are the labels/targets in your data 3D ?

**Comment by jvishnuvardhan** [comment]
@AkbarAlam Is this resolved? If it was not resolved, please provide a  simple standalone code to reproduce the issue. Thanks!

**Comment by jvishnuvardhan** [comment]
@AkbarAlam Did you try @pavithrasv suggestion? If this was not resolved, can you please share a standalone code to reproduce the issue? Thanks!

**Comment by AkbarAlam** [comment]
I am so sorry guys for late response. The project was over long ago and the use case was changed. Right now I can't reproduce it anymore
