### ISSUE TITLE
Good first issue tag?

### ISSUE THREAD

**Issue by raybellwaves** [tensorflow/tensorflow#26276]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: N/A
- Doc Link: https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md

**Describe the documentation issue**

Is there a 'good first issue' tag similar to the one used in pandas-dev?
https://github.com/pandas-dev/pandas#contributing-to-pandas-
I see there is a contributions welcome tag 
https://github.com/tensorflow/tensorflow/labels/stat%3Acontributions%20welcome

Perhaps I could add a sentence saying that:
If you want to contribute but you're not sure where to start, take a look at the issues with the "contributions welcome" label. These are issues that we believe are particularly well suited for outside contributions *and first time contributors*, often because we probably won't get to them right now. If you decide to start on an issue, leave a comment so that other people know that you're working on it. If you want to help out, but not alone, use the issue comment thread to coordinate.

I'm sure that could be worded better.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by dynamicwebpaige** [comment]
@raybellwaves - We will be adding this over the weekend. :slightly_smiling_face:

**Comment by kunakl07** [comment]
I would like to solve this issue.Can I contribute?

**Comment by dynamicwebpaige** [comment]
Added the tag `good first issue`, as well as `help wanted`, and will continue to populate! Thanks for the suggestion -- and please make sure to suggest in comments if you feel that an issue would be a good first project for a newcomer. :slightly_smiling_face:

**Comment by jayam30** [comment]
Hey Please assign me any good firs issue
