### ISSUE TITLE
window import bug

### ISSUE THREAD

**Issue by wm901115nwpu** [tensorflow/tensorflow#26273]
python3.7
tensorflow 1.13.1
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-03-02 10:16:10.848675: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr

**Comment by henrysky** [comment]
I do think it is related to the bug I have reported before but tensorflow ignored #25636 

Tensorflow windows build seems to need numpy>1.16

**Comment by jvishnuvardhan** [comment]
@wm901115nwpu In some cases, I think there are compatibility issues between modules when you install TF using conda. Could you uninstall python and tensorflow and reinstall following the instructions [here](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12). Please let me know how it progresses. For Faster resolutions, Please provide the details requested at issue template [here](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Thanks!

**Comment by wm901115nwpu** [comment]
I install a cpu version.

**Comment by wm901115nwpu** [comment]
I completely result in from numpy version, when I upgrade numpy version 1.16, it works.

**Comment by jvishnuvardhan** [comment]
@wm901115nwpu Please check required packages [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py). Please close if your issue was resolved. In future, double check version of required packages before you install TF through Anaconda. Thanks!

REQUIRED_PACKAGES = [
    'absl-py >= 0.7.0',
    'astor >= 0.6.0',
    'gast >= 0.2.0',
    'google_pasta >= 0.1.2',
    'keras_applications >= 1.0.6',
    'keras_preprocessing >= 1.0.5',
    'numpy >= 1.14.5, < 2.0',
    'six >= 1.10.0',
    'protobuf >= 3.6.1',
    'tensorboard >= 1.13.0, < 1.14.0',
    'tensorflow_estimator >= 1.13.0rc0, < 1.14.0rc0',
    'termcolor >= 1.1.0',
]

**Comment by jvishnuvardhan** [comment]
@wagonhelm I agree with @henrysky . This is related to #25636. So I will close this issue and keep the issue #25636 open until it is resolved. Thanks!

**Comment by ctmckee** [comment]
I also get this error when trying to use tensorflowjs_converter
