### ISSUE TITLE
tf.image.crop_and_resize() - weird alignment behavior?

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#26278]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):n/a
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:n/a
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):b'v1.13.0-rc2-0-gc865ec5621' 1.13.0-rc2
- Python version:3.7
- Bazel version (if compiling from source):n/a
- GCC/Compiler version (if compiling from source):n/a
- CUDA/cuDNN version:n/a
- GPU model and memory:n/a

This is a follow up on https://github.com/tensorflow/tensorflow/issues/6720#issuecomment-468830039 about `tf.image.crop_and_resize`. (cc @martinwicke )

Suppose I have an image that looks like this:
```
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
```
I wanted to crop the 2x2 patch that contains `[[6, 7], [11, 12]]`, and upsample it to 4x4. I expect to get the following outputs:
```
[[ 4.5  5.   5.5  6. ]
 [ 7.   7.5  8.   8.5]
 [ 9.5 10.  10.5 11. ]
 [12.  12.5 13.  13.5]]
```
I think this is a reasonable expectation. The above output, is also what I got if I do "resize_and_crop" instead of `tf.image.crop_and_resize`, __after the fix__ https://github.com/tensorflow/tensorflow/commit/371c96df55a7b23eb8d8496fb477b473fd137fcc yesterday that addressed the alignment issues in resize op.
```python
import tensorflow as tf
import numpy as np
from tensorflow.python.ops.image_ops_impl import resize_images_v2
arr = np.arange(25).astype('float32').reshape(5, 5)
input4D = tf.reshape(arr, [1, 5, 5, 1])
resize = resize_images_v2(input4D, [10, 10], method='bilinear')[0,:,:,0]   # resize
print(resize[2:6,2:6])  # crop
# print expected output
```
See a Colab proof in https://colab.research.google.com/drive/1ojDErHyG_4v3vwdi3xYwpdtyxShYM9a6#scrollTo=-T1zLhI5uumV

OK, what is the correct "boxes" I should provide for `crop_and_resize`, in order to get the above output?
Here is what the document says:

> boxes: A Tensor of type float32. A 2-D tensor of shape [num_boxes, 4]. The i-th row of the tensor specifies the coordinates of a box in the box_ind[i] image and is specified in normalized coordinates [y1, x1, y2, x2]. A normalized coordinate value of y is mapped to the image coordinate at y * (image_height - 1), so as the [0, 1] interval of normalized image height is mapped to [0, image_height - 1] in image height coordinates. We do allow y1 > y2, in which case the sampled crop is an up-down flipped version of the original image. The width dimension is treated similarly. Normalized coordinates outside the [0, 1] range are allowed, in which case we use extrapolation_value to extrapolate the input image values.

It turns out, that the correct "boxes" I should use, is: `[3/16, 3/16, 9/16, 9/16]`. If you cannot tell why it is 3/16 and 9/16 from the above documentation, you and I are on the same page:
```python
import tensorflow as tf
import numpy as np
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()

# want to crop 2x2 out of a 5x5 image, and resize to 4x4
image = np.arange(25).astype('float32').reshape(5, 5)
target = 4
print(tf.image.crop_and_resize(
    image[None, :, :, None],
    np.asarray([[3/16,3/16,9/16,9/16]]), [0], [target, target])[0][:, :, 0])
# print expected output
```

The crop_and_resize function has weird alignment issues like those fixed in #6720 . It's less of a problem than #6720 because at least we can provide some box coordinates to make it work as expected, and you can say it's just how this function is defined. 
There is actually [a formula](https://github.com/tensorpack/tensorpack/blob/1cdd2e9efb6ffe3066a010e677ef9e76547faaa3/examples/FasterRCNN/modeling/model_box.py#L104-L135) that I use in my code to compute the coordinates in order to use this function. 

But I do hope this function can have a better-defined behavior and fit reasonable expectation. In my experiments this ill-posed behavior actually hurt my models (which I believe also hurt other models like TF's object detection).

**Comment by tpet** [comment]
I am not sure, how upsampling
```
[[6, 7],
 [11, 12]]
```
with interpolation would get you to
```
[[ 4.5  5.   5.5  6. ]
 [ 7.   7.5  8.   8.5]
 [ 9.5 10.  10.5 11. ]
 [12.  12.5 13.  13.5]]
```
where there are values outside the source values.

**Comment by ppwwyyxx** [comment]
It was not outside the source values because the source is the 5x5 image.

**Comment by tpet** [comment]
Ah, thanks, I thought the crop happens before resize.

**Comment by ppwwyyxx** [comment]
@johnpjf The `crop_and_resize` op also has the half-pixel issue, which can be seen at https://github.com/tensorflow/tensorflow/blob/c95e5bcd98b35c2688577262038da645a2088de4/tensorflow/core/kernels/crop_and_resize_op.cc#L237-L248

Since you fixed this issue in the resize ops, I'm wondering whether this op is on your radar and is there a plan to fix it soon?

**Comment by lsy323** [comment]
Hi @ppwwyyxx ,

May I ask why the expected output is
```
[[ 4.5  5.   5.5  6. ]
[ 7.   7.5  8.   8.5]
[ 9.5 10.  10.5 11. ]
[12.  12.5 13.  13.5]]
```

I executed your code:
``` python
import tensorflow as tf
import numpy as np
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()
from tensorflow.python.ops.image_ops_impl import resize_images_v2
arr = np.arange(25).astype('float32').reshape(5, 5)
input4D = tf.reshape(arr, [1, 5, 5, 1])
resize = resize_images_v2(input4D, [10, 10], method='bilinear')[0,:,:,0]   # resize
print(resize[2:6,2:6])  # crop
# print expected output
```

The "resize" tensor is:
```
[[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4. ]
 [ 2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  6.5]
 [ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9. ]
 [ 7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 11.5]
 [10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14. ]
 [12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5 16.5]
 [15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19. ]
 [17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 21.5]
 [20.  20.5 21.  21.5 22.  22.5 23.  23.5 24.  24. ]
 [20.  20.5 21.  21.5 22.  22.5 23.  23.5 24.  24. ]]
```
So the cropped tensor is:
```
[[ 6.   6.5  7.   7.5]
 [ 8.5  9.   9.5 10. ]
 [11.  11.5 12.  12.5]
 [13.5 14.  14.5 15. ]]
```

Actually, the output above makes sense to me. I'm wondering why this is different from the expected result in your original post. Would you please give me a brief explanation on this?

Thanks so much and happy new year!

**Comment by rmothukuru** [comment]
@ppwwyyxx,
Can you please respond to the above comment? Thanks!

**Comment by ppwwyyxx** [comment]
@rmothukuru  the above comment is incorrect.

@lsy323 Unlike what you commented, the output of the code I provide, using a new enough tensorflow, is:
```
[[ 4.5  5.   5.5  6. ]
 [ 7.   7.5  8.   8.5]
 [ 9.5 10.  10.5 11. ]
 [12.  12.5 13.  13.5]]
```
which is shown in this colab: https://colab.research.google.com/drive/1ojDErHyG_4v3vwdi3xYwpdtyxShYM9a6?usp=sharing

**Comment by PrimeF** [comment]
@ppwwyyxx I'm using your formula to determine the coordinates to use (https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/modeling/model_box.py#L105), however, I'm not able to reproduce your results by using `boxes = tf.convert_to_tensor([[1., 1., 2., 2.]])` to get the patch `[[6,7], [11,12]`.

Has something changed in the meantime with regard to the alignment behaviour of `tf.image.crop_and_resize()`?

**Comment by ppwwyyxx** [comment]
It prints expected output:
```python
import tensorflow as tf
import numpy as np

# want to crop 2x2 out of a 5x5 image, and resize to 4x4
image = np.arange(25).astype('float32').reshape(5, 5)
target = 4

def transform_fpcoor_for_tf(boxes, image_shape, crop_shape):
    x0, y0, x1, y1 = tf.split(boxes, 4, axis=1)

    spacing_w = (x1 - x0) / tf.cast(crop_shape[1], tf.float32)
    spacing_h = (y1 - y0) / tf.cast(crop_shape[0], tf.float32)

    imshape = [tf.cast(image_shape[0] - 1, tf.float32), tf.cast(image_shape[1] - 1, tf.float32)]
    nx0 = (x0 + spacing_w / 2 - 0.5) / imshape[1]
    ny0 = (y0 + spacing_h / 2 - 0.5) / imshape[0]

    nw = spacing_w * tf.cast(crop_shape[1] - 1, tf.float32) / imshape[1]
    nh = spacing_h * tf.cast(crop_shape[0] - 1, tf.float32) / imshape[0]

    return tf.concat([ny0, nx0, ny0 + nh, nx0 + nw], axis=1)

box = tf.constant([1.0, 1, 3, 3])
box = tf.reshape(box, (1, 4))
print(tf.image.crop_and_resize(
    image[None, :, :, None],
    transform_fpcoor_for_tf(box, (5, 5), (4, 4)), [0], [target, target])[0][:, :, 0])
# [[ 4.5  5.   5.5  6. ]
#  [ 7.   7.5  8.   8.5]
#  [ 9.5 10.  10.5 11. ]
#  [12.  12.5 13.  13.5]]
```

**Comment by PrimeF** [comment]
Thanks for the example code!
My question is, however, why the coordinates of the lower right point are defined as `(3, 3)`.
This seems to be that it should rather be `(2,2)`, if we use zero-indexed coordinates.

**Comment by kenfranko** [comment]
Going back to the original question.  If you want to crop out `[[6, 7], [11, 12]]` and upscale to 4x4, what you want is:
```
tf.image.crop_and_resize(
    image[None, :, :, None],
    np.asarray([[0.25,0.25,0.5,0.5]]), [0], [target, target]
```
The cropping results in:
```
[[6, 7],
 [11, 12]]
```

Scaling it up using bilinear interpolation results in:
```
[[ 6.         6.3333335  6.666667   7.       ]
 [ 7.666667   8.         8.333334   8.666667 ]
 [ 9.333334   9.666667  10.000001  10.333334 ]
 [11.        11.333333  11.666667  12.       ]]
```
If you instead did nearest interpolation you would get:
```
[[ 6.  6.  7.  7.]
 [ 6.  6.  7.  7.]
 [11. 11. 12. 12.]
 [11. 11. 12. 12.]]
```

I think the two key things are:
* The boxes represent the image dimensions and not pixels.  In this case the value `6` is at location `[0.25, 0.25]` and `12` is at location `[0.5, 0.5]`. 
* The crop occurs before the resize.  

```
import tensorflow as tf
import numpy as np
from tensorflow.python.ops.image_ops_impl import resize_images_v2
arr = np.arange(25).astype('float32').reshape(5, 5)
input4D = tf.reshape(arr, [1, 5, 5, 1])
resize = resize_images_v2(input4D, [10, 10], method='bilinear')[0,:,:,0]   # resize
print(resize[2:6,2:6])  # crop
# print expected output
```
is not equivalent because resize_images_v2 extrapolates the values to scale up the images.  Using crop and resize first crops the image and then scales up the cropped image.

**Comment by ppwwyyxx** [comment]
I disagree with:

>  The cropping results in:
[[6, 7],
 [11, 12]]
Scaling it up using bilinear interpolation results in:
[[ 6.         6.3333335  6.666667   7.       ]
 [ 7.666667   8.         8.333334   8.666667 ]
 [ 9.333334   9.666667  10.000001  10.333334 ]
 [11.        11.333333  11.666667  12.       ]]

This is wrong, proved by the code below:
```
arr = np.array([[6, 7], [11, 12]]).reshape(2, 2)
out = tf.image.resize(arr[..., None], (4, 4), method=tf.image.ResizeMethod.BILINEAR)
print(out[..., 0])
-> tf.Tensor(
[[ 6.    6.25  6.75  7.  ]
 [ 7.25  7.5   8.    8.25]
 [ 9.75 10.   10.5  10.75]
 [11.   11.25 11.75 12.  ]], shape=(4, 4), dtype=float32)
```

The result printed above agrees with the "expected result" in my original issue, which is:
```
[[ 4.5  5.   5.5  6. ]
 [ 7.   7.5  8.   8.5]
 [ 9.5 10.  10.5 11. ]
 [12.  12.5 13.  13.5]]
```
They only differ at boundaries, due to the extrapolation issue that you mentioned.

**Comment by ppwwyyxx** [comment]
For more context, I understand that the results would match if I resize `[[6, 7], [11, 12]]` into 4x4 using TFv1's `resize_images(align_corners=True)`. However, `align_corners=True` was removed for good after #6720 and don't exist in TFv2. That's why this issue is a follow up of #6720 that we're still using the weird (and bad for many models) alignment behavior.

**Comment by johnpjf** [comment]
In JAX we solved this by exposing the underlying scale and
translate operation which makes it easy to make use any alignment you want.
I have a really old, mostly abandoned CL for TF to do this, if people are
interested, or if someone wanted to take it over:

https://critique.corp.google.com/cl/279127434
