### ISSUE TITLE
`tensorflow.python.client.device_lib.list_local_devices()`  crushes when none of GPU has enough free memory

### ISSUE THREAD

**Issue by yoshihikoueno** [tensorflow/tensorflow#26275]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.10

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
Binary

- TensorFlow version (use command below):
1.13.1

- Python version:
3.6.7

- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
CUDA10.0/cuDNN _7.5.0.56

- GPU model and memory:
0: GTX 1060 TI 6GB
1: GTX 1050 Ti 4GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
b'v1.13.1-0-g6612da8951' 1.13.1

**Describe the current behavior**
If I run list_local_devices() in order to get the number of GPUs available while almost all of memory is already allocated on all the GPUs, the process crashes due to CUDA_ERROR_OUT_OF_MEMORY.
There's no problem at all if at least one GPU has substantial amount of free memory.

Error Message:

> 2019-03-02 12:26:38.852155: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-03-02 12:26:38.989613: W tensorflow/compiler/xla/service/platform_util.cc:240] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 6370295808
> 2019-03-02 12:26:38.999115: W tensorflow/compiler/xla/service/platform_util.cc:240] unable to create StreamExecutor for CUDA:1: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 4236312576
> 2019-03-02 12:26:38.999399: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
> 

**Describe the expected behavior**
If none of GPUs is available, it could just return the empty list, not crushing itself.
I wrote my code for training a model in the way it fully makes use of all the available resources, but I have another code for doing various stuff and I want it to run on CPU when GPU is not available.
I expected get_available_gpus() to return the empty list when none of them is available.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```python
from tensorflow.python.client import device_lib

def get_available_gpus():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos if x.device_type == 'GPU']

get_available_gpus()
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

the result of `nvidia-smi`

```
Sat Mar  2 12:41:52 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  On   | 00000000:01:00.0  On |                  N/A |
| 40%   55C    P2    41W / 120W |   6033MiB /  6075MiB |     51%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 105...  On   | 00000000:03:00.0 Off |                  N/A |
| 30%   41C    P0    N/A /  75W |   3997MiB /  4040MiB |     59%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1960      G   /usr/lib/xorg/Xorg                            27MiB |
|    0      2557      G   /usr/bin/gnome-shell                          60MiB |
|    0     13385      C   python                                      5933MiB |
|    1     13385      C   python                                      3985MiB |
+-----------------------------------------------------------------------------+

```

Here is my current workaround
```python
def get_available_gpus(workaround=True):
    if workaround:
        ret = os.spawnl(os.P_WAIT, python_path, python_path, 'metax/get_num_gpus.py')
        if ret < 0:
            # detecting aborted process
            return []
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos if x.device_type == 'GPU']
```
For now, I'm creating a child process to see if it crushes.

**Comment by mrry** [comment]
I'm not sure why this was assigned to me: please reassign to someone working on the GPU or Eager runtime components.

**Comment by sanjoy** [comment]
@jaingaurav I'm able to reproduce this by running a program that allocates all GPU memory and then concurrently launching the snippet in the issue description.  Do you know what the correct fix is here?

**Comment by sushreebarsa** [comment]
@yoshihikoueno We see that you are using old version of tensorflow (1.x)which is officially considered as end of life, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions.Please open a new issue in case you face any errors, we will get you the right help .Hence moving this to closed status.Thanks
