### ISSUE TITLE
Disabling tf.cond name scope

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#26283]
**System information**
- TensorFlow version: 2.0
- Are you willing to contribute it: No

**Describe the feature and the current behavior/state.**

With all variables name being resolved via `name_scope` in TensorFlow 2.0, mixing tf.cond and variable creation can lead to unexpected or inconvenient results. Please consider this class that implements a conditional logic for inference but not training (here, reading a cached value):

```python
class MyModel(tf.keras.layers.Layer):

    def __init__(self):
        super(MyModel, self).__init__()
        self.linear = tf.keras.layers.Dense(10)

    def call(self, x, cache=None, training=None):
        if training or cache is None:
            return self.linear(x)
        else:
            return tf.cond(
                tf.equal(tf.shape(cache)[0], 0),
                true_fn=lambda: self.linear(x),
                false_fn=lambda: cache)
```

This creates incompatible variable names in inference.

**Training:**

```python
x = tf.zeros([3, 5])
model = MyModel()
_ = model(x, training=True)
print(model.trainable_variables)
```

```text
[<tf.Variable 'my_model/dense/kernel:0' shape=(5, 10) dtype=float32>, <tf.Variable 'my_model/dense/bias:0' shape=(10,) dtype=float32>]
```

**Inference:**

```python
x = tf.zeros([3, 5])
cache = tf.ones([0, 5])
model = MyModel()
_ = model(x, cache=cache, training=False)
print(model.trainable_variables)
```

```text
[<tf.Variable 'my_model/cond/dense/kernel:0' shape=(5, 10) dtype=float32>, <tf.Variable 'my_model/cond/dense/bias:0' shape=(10,) dtype=float32>]
```

The developer should then fiddle with the name or build the layer beforehand but I believe this code should just work. In V1, this could be fixed by setting the `tf.cond` name to:

```python
tf.get_default_graph().get_name_scope() + "/"
```

but there is no alternative in V2.

**Will this change the current api? How?**

There should be a way (e.g. argument) to disable the name scope introduced by `tf.cond`. Making this the default behavior is maybe unreasonable to ask.

**Who will benefit with this feature?**

People applying conditional logic on layers during inference but not during training.

**Any Other info.**

There are 2 real world examples in the project I maintain, [OpenNMT-tf](https://github.com/OpenNMT/OpenNMT-tf):

* When dynamically decoding from a Transformer model, the decoder can cache the projection of the encoder output: https://github.com/OpenNMT/OpenNMT-tf/blob/v1.21.0/opennmt/layers/transformer.py#L466-L476. To mitigate the scope issue, I manually build the layer before the `tf.cond`.
* When generating from a language model, we should either get the initial decoder state or the context state (if a context exists): https://github.com/OpenNMT/OpenNMT-tf/blob/v1.21.0/opennmt/models/language_model.py#L83-L87. In this case, I know that `self.name` is the top level name scope and use it directly.

**Comment by alextp** [comment]
Why is having differently named variables a problem? With the tf v2 object-based checkpointing TF does not rely on variable names for anything (other than deprecated parameter server training).

**Comment by guillaumekln** [comment]
> With the tf v2 object-based checkpointing TF does not rely on variable names for anything (other than deprecated parameter server training).

Sorry I missed that.

So this is a non issue for V2 and I guess there is little motivation to change that for V1. Thanks!
