### ISSUE TITLE
Changing the default initializer globally for tf.keras.layers

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#26282]
**System information**
- TensorFlow version: 2.0
- Are you willing to contribute it: No

**Describe the feature and the current behavior/state.**

For V1 `tf.layers`, one could set a default initializer to the global variable scope:

```python
with tf.variable_scope(name, initializer=...):
  ...
```

In V2 `tf.keras.layers`, the default initializer is hardcoded to `initializers.glorot_uniform()`. I currently see 2 imperfect ways to change the default initializer globally:

* change the initializer to every layers that are created **but** this is not convenient for large models
* implement a manual assignation loop **but** AFAIK there is no clean way to detect if the variable initializer is the default one or an initializer that was explicitly passed by the developer (typically a constant initialization).

**Will this change the current api? How?**

I think the most user friendly approach to this is to add an endpoint to globally change the default initializer: each layer created after this statement will use this initializer by default.

**Who will benefit with this feature?**

Anyone who wants to easily apply a global initialization strategy while still ensuring that specific initializer can be set locally.

---

Any recommendation to achieve this with the current code is of course appreciated.

**Comment by alextp** [comment]
I think this is the kind of thing we're running away from in tf v2. If you want to do it you can use your own layer-wrapping mechanism to do that.

**Comment by jiarenyf** [comment]
I think everyone wants to easily apply a global initialization strategy.

**Comment by alextp** [comment]
Because we do not want to add more global-behavior-changing endpoints to TF's API.

Instead I recommend you do things like wrapping keras layers into something that passes a global initializer in your code, and use the wrapped layers instead. With some metaprogramming this is not too much code, and doesn't push complexity into TF.
