### ISSUE TITLE
can not find tensor flow/contrib/lite/java/demo this demo

### ISSUE THREAD

**Issue by chenjiaoAngel** [tensorflow/tensorflow#26292]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I want to download tensor flow code to install TFLite  in my android phone. But in tensorflow directory, I don not find tensorflow/contirbute/lite this directory. 
code : https://github.com/tensorflow/tensorflow, branch is master
And I hope you can provide install_docs to help me install and run model in Android 
Thanks very much

**Comment by Ayush517** [comment]
Hi! I have mentioned some links below. Can you please take a look at these.

TFLite code Repository : https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite
TFLite Website Guide : https://www.tensorflow.org/lite/overview
TFLite Github Guide : https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/guide/android.md

Is this what you were asking for?

**Comment by chenjiaoAngel** [comment]
ok, TFlite can support  ssd-mobilenet  model? And shufflenet, shuffle net-v1 model support in TFLite?

**Comment by Ayush517** [comment]
Ssd-mobilenet and Shufflenet-v2 are supported I think but I am not sure of Shufflenet-v1 in TFLite. 
@jvishnuvardhan Can you please verify this. Thanks :)

**Comment by ymodak** [comment]
```lite``` folder has moved out of contrib. You should find it on ```[tensorflow/tensorflow/lite/](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite)``` as mentioned by @Ayush517  in previous comments

**Comment by chenjiaoAngel** [comment]
Thanks, I have find that and build success

**Comment by chenjiaoAngel** [comment]
1.

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
