### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Garfield2013** [tensorflow/tensorflow#26298]
I get the following error message:

> 'ImportError: DLL load failed: The specified module could not be found.'.

when I run the following code:

> python -c 'import tensorflow as tf; print(tf.__version__)'

Please check this screenshoot to see the list of my environment variables and the error message itself.
https://www.screencast.com/t/PsEXiaM0S

I'm running Windows 10 PRO and I'm using Geforce RTX 2070 and TensorFlow-GPU 1.13.1

I have installed the following:

1. Python 3.6.7
2. Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24215 (could not be installed - legacy now)
2. Microsoft Visual C++ 2017 Redistributable (x64) - 14.16.27027
3. Microsoft Visual C++ Build Tools - 15.9.28307.423
4. msys2-x86_64-20180531.exe
5. Cuda_10.1.105_win10_network
6. Cudnn 7.4.1.5 or 7.5 (I tried both)
7. Nvidia driver 419.17-desktop-win10-64bit-international-whql.exe

**Comment by Garfield2013** [comment]
It solved it like this:

1. Uninstalled CUDA 10.1
2. Restarted
3. Installed CUDA 10.0

Thats it! :)

/Cheers peps!

**Comment by Bixi81** [comment]
Under Windows 10 / Py 3.6.x / with RTX2080, the combination of CUDA 10.0 (not 10.1) - as pointed out by Garfield2013 - with cuDNN 7.5.0 works. Don't forget to add the location of the cuDNN *.dll file(s) (this is /bin/ folder in the CUDA dir) to your PATH under Windows.
Tensorflow can be installed using `pip install tensorflow-gpu` (Version 1.13.1 as of April 12, 2019)
