### ISSUE TITLE
Archlinux Installation using pip!

### ISSUE THREAD

**Issue by mmrezaie** [tensorflow/tensorflow#263]
Probably this should be mentioned in the documentation that for distros like archlinux that use python 3 by default users can do this use virtualenv like this:

virtualenv --python=python2.7 --system-site-packages

**Comment by lrepno** [comment]
Or you can just use python2.7 and corresponding version of pip :) 

I had no troubles with that when I've been installing it.

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/issues/1, when resolved, will add support for python 3 -- at that point hopefully this issue will go away :)

**Comment by Zenol** [comment]
Nb : If you are using archlinux, you are now using python 3.5 and not 3.4, so you have to rename the package.
Otherwise you'll get a `tensorflow-0.6.0-cp34-none-linux_x86_64.whl is not a supported wheel on this platform.` message.

**Comment by hgaiser** [comment]
@Zenol, could you elaborate a bit more? What needs to be renamed? I seem to be facing this issue.

**Comment by Zenol** [comment]
You can rename `tensorflow-0.6.0-cp34-none-linux_x86_64.whl` into `tensorflow-0.6.0-cp35-none-linux_x86_64.whl`. 34 / 35 is actually the version number.

**Comment by hgaiser** [comment]
Thanks, will try that!

**Comment by Maradonna90** [comment]
@Zenol : So I have downloaded the tensorflow-0.6.0-cp34-none-linux-x86_64.whl, renamed it into tensorflow-0.6.0-cp35-none-linux-x86_64.whl. The installation itself went successfully. But when i try the minimal example from the tutorial I get the "magical number" error.

`Python 3.5.0 (default, Sep 20 2015, 11:28:25) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 50, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/usr/lib/python3.5/site-packages/tensorflow/python/framework/framework_lib.py", line 62, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/usr/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 24, in <module>
    import copy
ImportError: bad magic number in 'copy': b'\xd1\xf2\r\n'
`
Anything I did wrong?
