### ISSUE TITLE
ValueError: as_list() is not defined on an unknown TensorShape.

### ISSUE THREAD

**Issue by rajathpatel23** [tensorflow/tensorflow#26305]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 pro
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.12.0
- Python version:3.6.0
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:9.0
- GPU model and memory:Nvidida1070/ 8GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
It gives an error when I am calling the unknown shape tensor into the dynamic_rnn function
**Describe the expected behavior**

**Code to reproduce the issue**
`def LSTM_model(embed, lstm_sizes, keep_prob_, batch_size):
     lstms = [tf.contrib.rnn.BasicLSTMCell(size) for size in lstm_sizes]
     drops = [tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob_) for lstm in lstms]
     cell = tf.contrib.rnn.MultiRNNCell(drops)
     initial_state = cell.zero_state(batch_size, tf.float64)
     lstm_outputs, final_state = tf.nn.dynamic_rnn(cell, embed, initial_state=initial_state)
     return lstm_outputs, final_state`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
`
  File "<ipython-input-2-fc074b4d9b11>", line 23, in <module>
    output_data, final_state = LSTM_model(e_tr1, lstm_size, keep_prob_, batch_size)

  File "C:\Users\rpsworker\Documents\GitHub\KGE-FE-SR_1\NAM_Modified\test_LSTM.py", line 54, in LSTM_model
    lstm_outputs, final_state = tf.nn.dynamic_rnn(cell, embed, initial_state=initial_state)

  File "C:\ProgramData\Anaconda3\envs\new_ten\lib\site-packages\tensorflow\python\ops\rnn.py", line 664, in dynamic_rnn
    dtype=dtype)

  File "C:\ProgramData\Anaconda3\envs\new_ten\lib\site-packages\tensorflow\python\ops\rnn.py", line 733, in _dynamic_rnn_loop
    const_time_steps, const_batch_size = inputs_got_shape[0].as_list()[:2]

  File "C:\ProgramData\Anaconda3\envs\new_ten\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 904, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")

ValueError: as_list() is not defined on an unknown TensorShape.`

**Comment by rajathpatel23** [comment]
My issue has been address in the issue [4588](https://github.com/tensorflow/tensorflow/issues/4588), however the solution is not very clear, hence reopening a new issue here

**Comment by ymodak** [comment]
The code snippet provided looks incomplete. In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here. Thanks!

**Comment by rajathpatel23** [comment]
Here is the well formatted code with the error
```
def LSTM_model(embed, lstm_sizes, keep_prob_, batch_size):
    lstms = [tf.contrib.rnn.BasicLSTMCell(size) for size in lstm_sizes]
    drops = [tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob_) for lstm in lstms]
    cell = tf.contrib.rnn.MultiRNNCell(drops)
    initial_state = cell.zero_state(batch_size, tf.float64)
    lstm_outputs, final_state = tf.nn.dynamic_rnn(cell, embed, initial_state=initial_state)
    return lstm_outputs, final_state
```
```
File "", line 23, in 
output_data, final_state = LSTM_model(e_tr1, lstm_size, keep_prob_, batch_size)

File "C:\Users\rpsworker\Documents\GitHub\KGE-FE-SR_1\NAM_Modified\test_LSTM.py", line 54, in LSTM_model
lstm_outputs, final_state = tf.nn.dynamic_rnn(cell, embed, initial_state=initial_state)

File "C:\ProgramData\Anaconda3\envs\new_ten\lib\site-packages\tensorflow\python\ops\rnn.py", line 664, in dynamic_rnn
dtype=dtype)

File "C:\ProgramData\Anaconda3\envs\new_ten\lib\site-packages\tensorflow\python\ops\rnn.py", line 733, in _dynamic_rnn_loop
const_time_steps, const_batch_size = inputs_got_shape[0].as_list()[:2]

File "C:\ProgramData\Anaconda3\envs\new_ten\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 904, in as_list
raise ValueError("as_list() is not defined on an unknown TensorShape.")

ValueError: as_list() is not defined on an unknown TensorShape.`
```
Minor issue when passing embedding vector from the embedding layer to the TensorFlow function tf.nn.dynamic_rnn() function.Not able to pass it directly as a tensor, as the tensor shape is unknown, the function is not able to recognize the actual shape and it gives the error.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by rajathpatel23** [comment]
Thank you for the help. I will go ahead and close the issue

**Comment by pjsjongsung** [comment]
@rajathpatel23 did you manage to solve this issue?
I'm getting the same error from model.fit when passing two tensors(input and label) using dataset_from_generator, but no issues when passing the two tensors manually

**Comment by miaoweiwei** [comment]
My program has the same problem, [this is my Colaboratory](https://colab.research.google.com/drive/1kVSJzt4FzqdtIdqx0UOYXC0C6Zqb1nVL)
