### ISSUE TITLE
Trouble Importing TensorFlow

### ISSUE THREAD

**Issue by pbcubes** [tensorflow/tensorflow#26304]
**System information**
- Windows 10 Home

- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.13.1
- Python version: 3.6.0
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

**Describe the problem**
I installed python 3.6.0 to make sure that tensorflow could run, because before i had python 3.7.1. Then I installed tensorflow via "pip install tensorflow". The installation was successful, but when trying to import tensorflow I got the error message shown below. I am unsure of what to do next, please help. PS: I am running this on a Lenovo ideapad 100, so there is not a dedicated graphics card or gpu.

**Any other info / logs**
File "c:\Users\patri_yllzc1c\Desktop\TensorFlow Projects\NumberGuessCNN.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\patri_yllzc1c\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\patri_yllzc1c\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\patri_yllzc1c\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\patri_yllzc1c\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by Ayush517** [comment]
This error signals a mismatch between protobuf and TensorFlow versions.

Take the following steps to fix this error:

Uninstall TensorFlow.
Uninstall protobuf (if protobuf is installed).
Reinstall TensorFlow, which will also install the correct protobuf dependency.

https://stackoverflow.com/questions/42006320/tensorflow-pip-installation-issue-cannot-import-name-descriptor

**Comment by jvishnuvardhan** [comment]
@pbcubes Please follow @Ayush517 suggestion and the link also has couple of other solutions, if you like them. Please let me know how it progresses. Please close the issue if it was resolved. Thanks!

**Comment by Ayush517** [comment]
@pbcubes Any progress?

**Comment by pbcubes** [comment]
I fixed it after reinstalling it.
