### ISSUE TITLE
[TF 2.0] StridedSlice issue with empty slice.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#26302]
Empty arrays cause TypeErrors with `StridedSlice`. A one-liner to reproduce would be:

```python
 tf.constant([1, 2, 3])[tf.constant([], dtype=tf.int32)]
```

Which returns:

```
TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got <tf.Tensor: id=1, shape=(0,), dtype=int32, numpy=array([], dtype=int32)>
```

The numpy equivalent:

```python
np.array([1, 2, 3])[np.array([], dtype=np.int32)]
```

works as expected.

**Comment by hanyi-ye** [comment]
I met the same problem, and I found that if we are using tensor, we could just convert it into numpy by "tensor.numpy()" in tf2.

**Comment by ravikyram** [comment]
Could reproduce the issue with TF version 2.2.0-dev20200319. Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/3c0794133681c3d337bb72c13300d00e/untitled735.ipynb). Thanks!

**Comment by hanyi-ye** [comment]
I get it. Thanks for your notification.


| |
yhy_workspace
|
|
邮箱：yhy_workspace@163.com
|

Signature is customized by Netease Mail Master

On 03/19/2020 19:44, ravikyram wrote:

Could reproduce the issue with TF version 2.2.0-dev20200319. Please, find the gist here.. Thanks!

**Comment by ravikyram** [comment]
I tried in colab with TF versions 2.2,2.3-rc1, nightly versions(`2.4.0-dev20200712`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/b005cb70fa2f4fa9fb440f643a0b8098/untitled129.ipynb).Thanks!

**Comment by sachinprasadhs** [comment]
@dynamicwebpaige , you can convert Tensor to Numpy and then perform slicing like below. 
import tensorflow as tf
```
tf.constant([1, 2, 3]).numpy()[tf.constant([], dtype=tf.int32)]

array([], dtype=int32)
```

Also you can perform Tensor slicing like numpy using [tf.slice ](https://www.tensorflow.org/guide/tensor_slicing#extract_tensor_slices)
```
t1 = tf.constant([1, 2, 3])

print(tf.slice(t1,
               begin=[0],size=[0]))

tf.Tensor([], shape=(0,), dtype=int32)
```
Please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/e2f55aa1b91c9831680c7a3681044114/26302.ipynb).
