### ISSUE TITLE
tf.python no longer available in 1.13.1?

### ISSUE THREAD

**Issue by greaber** [tensorflow/tensorflow#26306]
Sorry if this is not exactly a documentation bug, but it is, for us, a big change in 1.13.1 that is not addressed in the release notes.

I realize that tf.python was never part of the public API, but it used to be available, and after upgrading from 1.12, it isn't any longer.  The reason we need it is that it is heavily used internally by tensorflow code, and occasionally we need to "vendor" some of this code.  It would be really inconvenient to do this by maintaining our own fork of tensorflow; instead we just copied a python file from the tensorflow source into our repo and made the changes we needed.  Is there some way to keep doing this in 1.13.1 with minimal changes (i.e., not finding all the uses of tf.python and changing them to their public api equivalents)?  (Also, btw, why do the python parts of the Tensorflow source use tf.python so much in the first place?  Couldn't they just use the public api?)

**Comment by MarkDaoust** [comment]
Hi @greaber, 

Interesting, I don't see a `tf.python` in 1.12 either.

Anyway,  the module is still available.

Have you tried patching it in with something like this as the first lines in your program:

```
from tensorflow import python as tf_python
tensorflow.python = tf_python
```

I bet that will get you unstuck.
