### ISSUE TITLE
tf.Data Pipeline using interleave starts fast then becomes extremely slow 

### ISSUE THREAD

**Issue by mehdi-beng** [tensorflow/tensorflow#26309]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 7
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.13
- **Python version**: 3.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9
- **GPU model and memory**: GTX 980 4GB
- **Exact command to reproduce**:

### Describe the problem

I am building a pipeline to feed a DNNRegressor model and the issue is that the input pipeline becomes extremely slow after the first few 100's steps.

I have thousands of TFRecord files of varying size (from 10MB to 3GB in size). Each input has 1038 columns. 
I am trying to create batches of size 512 with 1 "row" from each TFRecord file (each file has correlated data so I need 1 line from each of the 512 files being interleaved to have a "shuffled" batch). To do this,
I am using the Data.interleave method which seems perfect for my case.

Problem is the input is super fast at the start but gets painfully slow after the first 100's of steps.
CPU usage goes quickly from 100% at the start to near 0% as the pipeline becomes slower. However the disk read speed remains always at  > 60 MBps. What is the issue ? Are the smaller files straggling the pipeline in someway ?

I have tried using parralel interleave but that was even slower

### Source code / logs

```
def parse_tf(example):
    with tf.device('/cpu:0'):
        parsed_features = tf.parse_example(example, feature)
        feats = parsed_features
        labels = parsed_features.pop('labels')
        return feats, labels


def tf_input_fn(batch_size):
    with tf.device('/cpu:0'):
        files = os.listdir('D:/data/data')
        files = ['D:/data/data/' + file for file in files]

        dataset = (tf.data.Dataset.from_tensor_slices(files)
                   .interleave(lambda x:
                               tf.data.TFRecordDataset(x),
                               cycle_length=batch_size, block_length=1, num_parallel_calls=8)).batch(batch_size).map(
            parse_tf, num_parallel_calls=1)

        dataset = dataset.prefetch(100)
        return dataset


if __name__ == "__main__":

    batch_size_ = 512

    data = tf_input_fn(batch_size_)
    data_next = data.make_one_shot_iterator().get_next()
    ctr = 0
    with tf.Session() as data_sess:
        data_sess.run(tf.global_variables_initializer())
        tld_start = dt.datetime.now()
        try:
            while True:
                tld_out = data_sess.run(data_next)
                ctr += 1
                if ctr % 100 == 0:
                    tld_end = dt.datetime.now()
                    print("Time for 100 steps: " + str(tld_end - tld_start))
                    tld_start = dt.datetime.now()
                    ctr = 0
        except tf.errors.OutOfRangeError:
            print("Done")
```

Logs:

```
Time for 100 steps: 0:00:04.547647
Time for 100 steps: 0:00:03.132636
Time for 100 steps: 0:00:02.839416
Time for 100 steps: 0:00:02.639220
Time for 100 steps: 0:00:02.492228
Time for 100 steps: 0:00:01.991023
Time for 100 steps: 0:00:12.380473
Time for 100 steps: 0:00:29.162056
Time for 100 steps: 0:00:23.747592
Time for 100 steps: 0:00:28.041797
Time for 100 steps: 0:00:28.309055
Time for 100 steps: 0:00:26.240207
Time for 100 steps: 0:00:27.894402
Time for 100 steps: 0:00:25.832465
Time for 100 steps: 0:00:27.795538
Time for 100 steps: 0:00:28.219248
Time for 100 steps: 0:00:26.962029
Time for 100 steps: 0:00:24.568246
Time for 100 steps: 0:00:29.052262
Time for 100 steps: 0:00:27.003928
Time for 100 steps: 0:00:27.839937
Time for 100 steps: 0:00:28.380154
Time for 100 steps: 0:00:27.109850
Time for 100 steps: 0:00:28.234840
```

**Comment by sahilbadyal** [comment]
facing the same issue on distributed set up in r1.12 @mehdi-beng. CPU utilization and Global Steps/sec drop after some initial steps in my case.

**Comment by sahilbadyal** [comment]
facing the same issue in my distributed implementation

**Comment by mehdi-beng** [comment]
@sahilbadyal Hope we can get some help. I have 750 Million inputs I want to train on. At this speed it will take months for 1 epoch.

**Comment by mehdi-beng** [comment]
@rohan100jain can you check this out if you have the time please. Thank you !!

**Comment by wookayin** [comment]
I am doubtful this is a bug.

```
        data_sess.run(tf.global_variables_initializer())
```

You are creating a new op into the graph **at every iteration**, that must be why it slows down. Store the initializer as `init_op`, for instance, and just execute it without re-creating new ops.

**Comment by mehdi-beng** [comment]
@sahilbadyal I got it fixed. For me it was the HDD read speed not keeping up and becoming bottleneck. 
The TFRecord format is pretty big on volume, try using : tf.io.TFRecordCompressionType.GZIP) when creating your TFRecords.

The file will be 1/5th of the size once compressed making it easier for the HDD. The CPU will take the additional load to decompress each line. But CPU is harder to bottleneck than the HDD read speed. Good luck !

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if have further problems. Thanks!
