### ISSUE TITLE
Inconsistent encoding leads to AttributeError

### ISSUE THREAD

**Issue by mingyr** [tensorflow/tensorflow#26307]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N/A
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Red Hat 7.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): compiled from source
- TensorFlow version (use command below): r13.1
- Python version: 3.6.3
- Bazel version (if compiling from source): 0.22
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: 10.0
- GPU model and memory: P5000/16G

DeepMind open-sourced the implementation of IMPALA: https://github.com/deepmind/scalable_agent

For parallelism, they wrap a mechanism which is class-based in doing so, the file is: https://github.com/deepmind/scalable_agent/blob/master/py_process.py

There is a code snippet at the beginning of the file:

```
  class Zeros(object):
    def __init__(self, dim0):
      self._dim0 = dim0
    def compute(self, dim1):
      return np.zeros([self._dim0, dim1], dtype=np.int32)
    @staticmethod
    def _tensor_specs(method_name, kwargs, constructor_kwargs):
      dim0 = constructor_kwargs['dim0']
      dim1 = kwargs['dim1']
      if method_name == 'compute':
        return tf.contrib.framework.TensorSpec([dim0, dim1], tf.int32)
  with tf.Graph().as_default():
    p = py_process.PyProcess(Zeros, 1)
    result = p.proxy.compute(2)
    with tf.train.SingularMonitoredSession(
        hooks=[py_process.PyProcessHook()]) as session:
      print(session.run(result))  # Prints [[0, 0]].

```
however, when I tried to run it, I got the following error:

```
2019-03-01 17:37:16.260732: W tensorflow/core/framework/op_kernel.cc:1389] Unknown: AttributeError: 'Zeros' object has no attribute 'b'compute''
Traceback (most recent call last):

  File "/home/yuming/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/data/yuming/eeg-dpg/py_process.py", line 89, in py_call
    raise result

AttributeError: 'Zeros' object has no attribute 'b'compute''

```

I suspect maybe there is a mismatch between encoding, but not for sure, since I have no problem in running the code if I use Python 2.7.

Could anyone please take some effort on looking into it?

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by mingyr** [comment]
I already post on stackoverflow but got no answer there. I would think it is a bug, I would guess potentially there is a different encoding representation of python interpreter which is distinguished from source code encoding.

Kindly suggest you try the problem because it is quite easy to re-produce but not that easy to fix.

**Comment by jvishnuvardhan** [comment]
@mingyr could you post it in DeepMind Repo [here](https://github.com/deepmind/scalable_agent/issues). Thanks!
