### ISSUE TITLE
Random Uniform Not Supported for TFlite Conversion

### ISSUE THREAD

**Issue by Zaxa13** [tensorflow/tensorflow#26300]
**System **information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): tf-nightly 1.14.1

**Describe the Problem**
Trying to convert frozen tensorflow model to .tflite so I can use it on my android phone, but conversion fails due to RandomUniform OP being unsupported.

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). 
Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). 
Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, DIV, FLOOR, MAX_POOL_2D, MUL, SHAPE, SPLIT, SUB. 
Here is a list of operators for which you will need custom implementations: RandomUniform.

```

**Any other info / logs**

Toco command used

tflite_convert 
--output_file=segmentleaves.tflite 
--graph_def_file=frozenGraph/frozen_model.pb 
--input_shapes=1,224,224,3 
--input_arrays=image_input 
--output_arrays=layer7_out

**Comment by vgg4resnet** [comment]
yes，i have been seeking for a solution  for the  unsupported RandomUniform  ops these days，when  it can be solved

**Comment by jdduke** [comment]
The Random operators should be available using our [experimental pipeline for using select TensorFlow ops](https://www.tensorflow.org/lite/guide/ops_select). Feel free to re-open if you encounter issues using that pipeline. Cheers.

**Comment by Zaxa13** [comment]
> 
> 
> The Random operators should be available using our [experimental pipeline for using select TensorFlow ops](https://www.tensorflow.org/lite/guide/ops_select). Feel free to re-open if you encounter issues using that pipeline. Cheers.

Hi, thanks for this.  Using this I am now able to create the .tflite file.
I have followed the rest of the guide but am unable to run my app after adding the tensorflow-lite-with-select-tf-ops.aar module to the app.

When running the app and trying to use tflite I now get the error:
`No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)`

Is this caused by me building it incorrectly? or is this a known issue?

**Comment by jdduke** [comment]
You might need to clean your build. Are you using the select-tf-ops.aar in place of the regular tflite aar?

**Comment by Zaxa13** [comment]
Yes, I have added the select-tf-ops.aar file and added it to my dependencies in place of the regular tensorflow lite and then cleaned and rebuilt my project.  Are there any additional steps not listed in the page you linked?

**Comment by jdduke** [comment]
Hmm, that might be caused by failure to actually load the library. Are you running on an x86 emulator? I believe we only ship arm64 libs for the select-tf-ops library. Can you look at the extended log for anything that mentions something like "TensorFlowLite: failed to load native library"?

**Comment by Zaxa13** [comment]
I'm running it on a pixel 2 xl, but you are correct about the error message.

`W/System.err: TensorFlowLite: failed to load native library: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/base.apk", zip file "/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_dependencies_apk.apk", zip file "/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_resources_apk.apk", zip file "/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_0_apk.apk", zip file "/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_1_apk.apk", zip file "/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_2_apk.apk", zip file "/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_3_apk.apk", zip file "/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_4_apk.apk", zip file "/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_5_apk.apk", zip file "/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_6_apk.apk", zip file "/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_7_apk.apk", zip file "/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_8_apk.apk", zip file "/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/lib/arm64, /data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/base.apk!/lib/arm64-v8a, /data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/nehartley.za.shrubnet-STg6ZQZ0cqj1gnGF4hCSXA==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libtensorflowlite_jni.so"
`

Can you suggest how to fix this?

**Comment by jdduke** [comment]
Can you look at the contents of your APK to make sure the library is present? Or can you attach the gradle rule for including the .aar?

**Comment by Zaxa13** [comment]
Inside the APK there is libtensorflowlite_flex_jni.so inside /lib/amreabi-v7a, so I assume that is what you are referring to as I can find no other files referencing tensorflow.
In build.gradle I added the line
`implementation project(':tensorflow-lite-with-select-tf-ops')`
to import the new module.  Is this what you mean?

**Comment by jdduke** [comment]
Is your project configured to use arm32? How exactly did you build the .aar?
