### ISSUE TITLE
Trained model inference on GPU of nvidia TX2 get poor result  even error result

### ISSUE THREAD

**Issue by xuefengxiaoyang** [tensorflow/tensorflow#26310]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:nvidia TX2
- TensorFlow installed from (source or binary):binary from https://nvidia.box.com/v/JP33-TF1-11-0-py35-wTRT
- TensorFlow version (use command below):1.110
- Python version:3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:CUDA9.0 cudnn 7.15
- GPU model and memory:8G

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I trained the model on the server and deployed the same version of tensorflow on TX2, but when I run the trained model with the GPU on TX2, I get a lot worse than on the server, but running the model on the CPU of TX2 does not cause this problem.
**Describe the expected behavior**
1. The result of running on the GPU of the server should be the same as the result of the GPU running on TX2. There should not be such a big gap.
2. The GPU running result on TX2 should be the same as the CPU running result on TX2.
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by samikama** [comment]
@jvishnuvardhan Can you please update to a more recent version of jetpack and TF version. Also could you please clarify what do you mean by a lot worse?

**Comment by MeisonP** [comment]
@xuefengxiaoyang  hello, did you get the answer of this issue? I am facing the same problem, trained model, the TX2 GPU inference result diff with PC inference result.

**Comment by MeisonP** [comment]
I got  the answer,  just change the Compute Capability of ARCH to match your edge device. for TX2, its 6.2

**Comment by sanjoy** [comment]
Closing since it looks like this is resolved as per https://github.com/tensorflow/tensorflow/issues/26310#issuecomment-541312223
