### ISSUE TITLE
[FR] A better way instead of  `while True: sess.run(..)`

### ISSUE THREAD

**Issue by ghostplant** [tensorflow/tensorflow#26318]
I'd like to make tensorflow as the inference backend, and there are quantities of inference inputs to handle.

Currently, tensorflow manages multiple inference inputs as different execution triggers of `sess.run`, e.g:

```python
while True:
    sess.run(infer_op)
```

However, the throughput is very bad because every inference task will run through python runtime and also tensorflow scheduler, so I require something like this **directly**:

```python
    sess.run(tf.loop_forever(infer_op))
```

You can assume the infer_op read inputs from an one_shot_iterator, and I never want this loop to stop just like it is a long-run server.

Anyway to do this at the moment, or the possibility to support this op like `tf.loop_forever` ?

You can also share a simple hack in tensorflow source code to make the `sess.run` (in C++ session) to repeat same computing again without returning data to python session. Thanks!

**Comment by ghostplant** [comment]
`tf.loop_forever` might not be a valid TF_OP that decorates a compute graph, so I think this solution might be reasonable:

```sh
sess.run(infer_op, loop_forever=True)
```

**Comment by ghostplant** [comment]
Using `tf.while_loop(0 < 1, ..)` might be a little ugly to understand, and it also requires to check the answer for each run of the body, which is not 

so strongly suggest creating an OP named `tf.loop_forever()` not to wait and check the answer very time, and this is very necessary for GPU-based operator because we don't want to launch unnecessary kernels to do this meaningless check, or copy device memory to host memory and related synchronization.

**Comment by Gonzalo933** [comment]
I think tensorflow doesn't have a break statement. So implementing an operation for which the only way of stopping it is by killing the process seems to go against a lot of principles. 

I don't think the overhead of checking a simple condition like `tf.while_loop(True, ..)` is going to be noticeable.

**Comment by ghostplant** [comment]
@Gonzalo933 An ugly problem for `tf.while_loop(True, body, ..)` is there are output shape restriction among `cond`, `body` and `loop_vars`, and I have to output something from `body` for checking even if it is not needed, thus it doesn't support many existing ops while a ideal `tf.loop_forever` should be expected to support.

Just a example, `tf.group` it can be the final wrapper of train_op to get away with I/O sychronization from GPU to CPU after the body terminates its execution, but `tf.while_loop` doesn't work for this case:

```python
train_op = tf.matmul([[4]], [[5]])
graph = tf.group(train_op)

loop = tf.while_loop(lambda i: True, lambda i: body=graph, [])
sess.run(loop)
```

So how to make `tf.while_loop` work like `tf.loop_forever(any_op)`?

**Comment by alvaroslm** [comment]
> 
> 
> I think tensorflow doesn't have a break statement. So implementing an operation for which the only way of stopping it is by killing the process seems to go against a lot of principles.
> 
> I don't think the overhead of checking a simple condition like `tf.while_loop(True, ..)` is going to be noticeable.

Everything is noticeable in TF. It shouldn't be, but it is. There are unintended consequences for everything.

**Comment by ghostplant** [comment]
There are 2 problems using `tf.while_loop` than ideal `tf.loop_forever`:
1) Performance: `while_loop` has to wait for a body answer before it can decide whether to schedule another body execution, so this is apparently in a synchronous style which is much inefficient to feed tasks to GPU, so the latency between adjacent body execution is high;
2) Not for all TF_Ops: it can not fully support all operations so it should not be a good loop_forever alternative;

I think either enhancing `while_loop` or extending `loop_forever` is needed, otherwise, TF engine would be only good in terms of offline batch processing, not efficient for lots of tasks with low-latency requirement.

**Comment by ghostplant** [comment]
break statement is not needed because the `sess.run` could be break or interrupt by any long-run operators that can return non-OK status, so the task could be terminated and handled by a surrounding `try: .. expect: ..` which is not strange.

**Comment by ghostplant** [comment]
I think the solution should be extending an `loop_forever` for struct `RunOptions`, and if it is enabled, the `RunAsync` implementation in `direct_session.cc` could be looping executed.

Another advantage for support `loop_forever` is that it could fully replace the Tensorflow C++ programming which is very uncommon (also, complex tool chain is needed, source code is needed, building takes too much time, ..) to most users.

Tensorflow can development a series of stateful operators not pass through python runtime, which could engine most long run services efficiently using Tensorflow engine.

If `tf.loop_forever` breaks some graph principles, this option should be set at sess.run(.., run_forever=True) which is not enabled by default.

Any agreement? or any supporting plans? If true, I volunteer to handle this feature.

**Comment by rmothukuru** [comment]
Closing this issue as per [mrry's comment in the PR 26561](https://github.com/tensorflow/tensorflow/pull/26561#issuecomment-471751819). Thanks!
