### ISSUE TITLE
tf.function creates a new concrete function multiple times for the same inputs

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#26311]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
MacOSX 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (use command below <= needs to be updated to TF2):
tf.version.VERSION: '2.0.0-dev20190303'
tf.version.GIT_VERSION: 'v1.12.0-9460-gbfa3fcead3'
- Python version:
3.6.8
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
When calling a TF function multiple times with the same arguments, the function keeps getting traced and more and more new concrete functions get generated. This will hinder performance and waste RAM.

**Describe the expected behavior**
I expect a function to be trace just once for a given set of inputs.

**Code to reproduce the issue**

```python
import tensorflow as tf

@tf.function
def f(x):
    print("  Tracing with shape", x.shape)
    return x ** 3

for round in range(5):
    print("Round", round)
    f(tf.constant(3.))
    f(tf.constant(4.))
    f(tf.constant([[1., 2.]]))
    f(tf.constant([[]]))
    f(tf.constant([[3., 4.], [5., 6.]]))
    f(tf.constant([[7., 8.], [9., 10.], [11., 12.]]))        
    print()
```

When you run this, you see that `f()` gets traced at every round, but it should only be traced during round 0.

Also, not sure if this is related or if I should file another issue, but I noticed this:

```python
cf1 = f.get_concrete_function(tf.TensorSpec(shape=[], dtype=tf.float32))
cf2 = f.get_concrete_function(tf.constant(0.))
assert cf1 is cf2  # AssertionError
```

**Other info / logs**
Here is the output:

```
Round 0
  Tracing with shape ()
  Tracing with shape (1, 2)
  Tracing with shape (1, None)
  Tracing with shape (None, 2)

Round 1
  Tracing with shape (1, None)
  Tracing with shape (None, 2)

Round 2
  Tracing with shape (1, None)
  Tracing with shape (None, 2)

Round 3
  Tracing with shape (1, None)
  Tracing with shape (None, 2)

Round 4
  Tracing with shape (1, None)
  Tracing with shape (None, 2)
```

**Comment by allenlavoie** [comment]
Thank you for the report! There should be a fix landing any minute.

The `get_concrete_function` issue is different; feel free to file another issue if it's causing an issue (I think that's much less serious). Basically we treat TensorSpecs and opaque Python objects for caching purposes at the moment. We can treat them like Tensors, although we'd probably want to re-trace if the TensorSpec's `name` changed.

**Comment by ageron** [comment]
Thanks @allenlavoie . The TensorSpec thing is not a big deal, you're right, no need to file an issue if it doesn't break anything.
