### ISSUE TITLE
tf.image.grayscale_to_rgb is not taking a grayscale image going into bugs 

### ISSUE THREAD

**Issue by Mainak431** [tensorflow/tensorflow#26324]
*System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  ubuntu 16.04
- TensorFlow installed from (source or binary): pip installed
- TensorFlow version (use command below): 1.12
- Python version: 2.7

Code- 
import tensorflow as tf
import matplotlib.pyplot
import matplotlib.pyplot as plt

fname = '/media/titan/ACER DATA/Mainak/ytfvideo/resized/Aaron_Eckhartimage_00001.jpg'
img = matplotlib.pyplot.imread(fname)

tf_img = tf.convert_to_tensor(img)
tf_img = tf.image.grayscale_to_rgb(tf_img)
brght_img = tf.image.flip_left_right(tf_img)
plt.imshow(img)
plt.show()
**Aaron_Eckhartimage_00001.jpg is a grayscale image
Error-

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    tf_img = tf.image.grayscale_to_rgb(tf_img)
  File "/home/titan/Documents/cpuenv/local/lib/python2.7/site-packages/tensorflow/python/ops/image_ops_impl.py", line 1530, in grayscale_to_rgb
    rgb.set_shape(images.get_shape()[:-1].concatenate([3]))
  File "/home/titan/Documents/cpuenv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 561, in set_shape
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 120 and 3. Shapes are [40,120] and [40,3].

**Comment by FlashTek** [comment]
You see this exception because your grayscale image does not have a valid shape. Inside tensorflow a grayscale image is defined as a `3D` tensor whose last dimension is size 1. This is different from `matplotlibs` definition. Therefore, you can fix this be using:
    
    tf_img = tf.convert_to_tensor(img.reshape((*img.shape, 1))

I created a pull request to give users a better feedback _why_ the operation fails if you try using it on an input with invalid shapes.

**Comment by Mainak431** [comment]
@FlashTek  Or we can update the function code to work both on 3D and 2D tensor. It will be a one line change. If you want i can do it separately in a pull request.
