### ISSUE TITLE
error building on Windows 10: Python Configuration Error: Problem getting numpy include path.

### ISSUE THREAD

**Issue by effiek9999** [tensorflow/tensorflow#26335]
- Windows 10
- TensorFlow installed from source following these instructions: https://www.tensorflow.org/install/source_windows
- TensorFlow version:
- Python version: 3.7 installed with Anaconda, in ../Anaconda3/python
- Bazel version (if compiling from source): 0.23.0
- CUDA/cuDNN version: 10.1/7
- GPU model and memory: Geoforce GTX 1080Ti

Running this command: 

bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

c:\Users\Usertytell_admin\tensorflow>bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
DEBUG: C:/users/usertytell_admin/_bazel_tytell_admin/oimkit2z/external/build_bazel_rules_apple/apple/repositories.bzl:35:5:
WARNING: `build_bazel_rules_apple` depends on `bazel_skylib` loaded from https://github.com/bazelbuild/bazel-skylib.git (tag 0.6.0), but we have detected it already loaded into your workspace from None (tag None). You may run into compatibility issues. To silence this warning, pass `ignore_version_differences = True` to `apple_rules_dependencies()`.

ERROR: C:/users/usertytell_admin/tensorflow/third_party/py/numpy/BUILD:11:1: no such package '@local_config_python//': Traceback (most recent call last):
        File "C:/users/usertytell_admin/tensorflow/third_party/py/python_configure.bzl", line 344
                _create_local_python_repository(repository_ctx)
        File "C:/users/usertytell_admin/tensorflow/third_party/py/python_configure.bzl", line 296, in _create_local_python_repository
                _get_numpy_include(repository_ctx, python_bin)
        File "C:/users/usertytell_admin/tensorflow/third_party/py/python_configure.bzl", line 276, in _get_numpy_include
                _execute(repository_ctx, [python_bin, "-c",..."], <2 more arguments>)
        File "C:/users/usertytell_admin/tensorflow/third_party/py/python_configure.bzl", line 56, in _execute
                _fail("\n".join([error_msg.strip() if ... ""]))
        File "C:/users/usertytell_admin/tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
                fail(("%sPython Configuration Error:%...)))
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Usertytell_admin\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\Usertytell_admin\Anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.
Is numpy installed?
 and referenced by '//third_party/py/numpy:headers'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 14.234s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (235 packages loaded, 3598 targets configured)
    currently loading: tensorflow/lite/kernels
    Fetching @eigen_archive; Restarting. 4s
    Fetching @local_config_python; fetching
    Fetching @highwayhash; fetching

**Comment by jvishnuvardhan** [comment]
@effiek9999 What is the version number of tensorflow and numpy? Can you check the requirement of TF1.13.1 [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py). TF1.13.1 was built against CUDA10. If you want to use CUDA 10.1, use latest version of TF and check whether CUDA and cuDNN are referencing correct paths. Best things is to install CUDA10 drivers. First, uninstall python and tensorflow and reinstall following the instructions [here](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12/blob/master/README.md) but use new version of CUDA and cuDNN. 

As another user suggested [here](https://github.com/tensorflow/tensorflow/issues/26182#issuecomment-468882301), you can do
conda install cudatoolkit
conda install cudnn

Please let me know how it progresses. Thanks!

**Comment by effiek9999** [comment]
My numpy version is 1.16.2, and I am getting TensorFlow directly from the github master branch. I will try these suggestions, thank you.

**Comment by HarryHHung** [comment]
I had the same problem until I downgraded my Bazel to version 0.20.

**Comment by jvishnuvardhan** [comment]
@effiek9999 Please check #26182 for any workarounds and solutions. Please close the ticker if your issue was resolved. Thanks!

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. Please open a new ticket if you see similar issue again. Thanks!
