### ISSUE TITLE
GPU Support build instructions suggest old Docker image

### ISSUE THREAD

**Issue by LGTrader** [tensorflow/tensorflow#26333]
**System information**
- Linux Ubuntu 18.04.2 LTS:
- TensorFlow installed from Docker image: 1.13.1-gpu-py3-jupyter
- TensorFlow version: Should be 1.13.1
- Python version: From Docker, appears to be 3.5.2
- Installed using pip: NA - don't get that far
- Bazel version (if compiling from source): Missing in docker image?
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda-10 from Docker image
- GPU model and memory:

processor       : 11
vendor_id       : GenuineIntel
cpu family      : 6
model           : 44
model name      : Intel(R) Core(TM) i7 CPU       X 980  @ 3.33GHz
stepping        : 2
microcode       : 0x13
cpu MHz         : 1630.792
cache size      : 12288 KB
physical id     : 0
siblings        : 12
core id         : 10
cpu cores       : 6
apicid          : 21
initial apicid  : 21
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt aes lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid dtherm ida arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 6675.50
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

THE PROBLEM: The Docker image tensorflow/tensorflow:1.13.1-gpu-py3-jupyter doesn't build as per the instructions here:

https://www.tensorflow.org/install/source#gpu_support_2

Using the tensorflow/tensorflow:1.13.1-gpu-py3-jupyter Docker image the build fails at the first step. (./configure) There's nothing in the /tensorflow directory.

Using the tensorflow/tensorflow:nightly-devel-gpu-py3 Docker image everything works fine and after being built tensorflow can be imported in python within the Docker container. In this image there is source code in /tensorflow.

ALSO, in this Docker container /usr/local/lib has only python3.5. In the nightly-devel-gpu-py image there is a bazel directory

**Comment by angersson** [comment]
Hmm... those docs may be out of date; `nightly-devel-gpu-py3` is a legacy Docker image. `devel-gpu-py3` is the newer equivalent with `/tensorflow_src`. [Our Docker Hub page](https://hub.docker.com/r/tensorflow/tensorflow/) may help explain our available tags.

Ping @lamberta

**Comment by LGTrader** [comment]
OK, devel-gpu-py3 appears to have all the pieces I was looking for. I've pulled a copy of the image and have started a build using the commands on the old possibly out-of-date page. I'll report back tomorrow as to the results.

Thanks for the help and I need to learn about this ping thing going on here! :-)

**Comment by LGTrader** [comment]
devel-gpu-py3 appears to be Ubuntu 16.04 LTS, I'm 18.04 LTS which is python-3.6. After installing python-3.5 on my system I am able to run tensorflow in a virtual environment created using python-3.5 and it see my GTX 960 so it's a big win. Thanks! However is there a 18.04/python-3.6 Docker image to make it a more direct install on Ubuntu 18.04 LTS?

**Comment by angersson** [comment]
The images are all based on Ubuntu 16.04 (some of the older images were updated to 18.04, but are no longer used) -- we just haven't had the time to update them (you can find the infrastructure in tensorflow/tools/dockerfiles, if you are interested in updating them). You can still use the 16.04-based images if you don't mind using the older Python versions.

**Comment by lamberta** [comment]
Hi. Can someone update these files with the correct info? Thanks
https://github.com/tensorflow/docs/blob/master/site/en/install/docker.md
https://github.com/tensorflow/docs/blob/master/site/en/install/source.md

**Comment by TristanMeng** [comment]
tensorflow:1.13.1-gpu-py3-jupyter has cudnn? 
How to view？

**Comment by angerson** [comment]
This issue has been resolved now that the docs have been updated.
