### ISSUE TITLE
ref type problem merging simple graphs

### ISSUE THREAD

**Issue by TanCari** [tensorflow/tensorflow#26346]
Hi guys, the following simple graph is compiled correctly on my computer:

graph_unique = tf.Graph()

with graph_unique.as_default():
    v = tf.get_variable(name='v', shape=[2], dtype=tf.float64)
    x = v[:1]
    y = v[1:]
    c = tf.add(x, y, name='c')
    gra = tf.gradients([c], [x])
    

When I try to write it as a stack of two graphs, though, I get an error.
I guess it is related with this post and I beg for some help.
Here my procedure:

adr_big = ''   # please add a valid addres 
adr_small = '' #       "          "

graph_small = tf.Graph()

with graph_small.as_default():
    v = tf.get_variable(name='v', shape=[2], dtype=tf.float64)
    x = tf.identity(v[:1], name='x')
    y = tf.identity(v[1:], name='y')
    s_small = tf.train.Saver()
    
with tf.Session(graph=graph_small) as sess:
    sess.run(tf.global_variables_initializer())
    s_small.save(sess, adr_small)
    
    
graph_big = tf.Graph()

with graph_big.as_default():
    a = tf.get_variable(name='a', shape=[1], dtype=tf.float64)
    b = tf.get_variable(name='b', shape=[1], dtype=tf.float64)
    c = tf.add(a, b, name='c')
    s = tf.train.Saver()
    
with tf.Session(graph=graph_big) as sess:
    sess.run(tf.global_variables_initializer())
    s.save(sess, adr_big)
    
    
    
graph_together = tf.Graph()

with graph_together.as_default():
    tf.train.import_meta_graph(adr_small+'.meta', import_scope='g_small')
    x = graph_together.get_tensor_by_name('g_small/x:0')
    y = graph_together.get_tensor_by_name('g_small/y:0')
    tf.train.import_meta_graph(adr_big+'.meta', import_scope='g_big', input_map={'a:0':x, 'b:0':y})
    c = graph_together.get_tensor_by_name('g_big/c:0')
    gra = tf.gradients([c],[x])
    

Tensorflow says:
[...]
InvalidArgumentError: Input 0 of node gg/a/Assign was passed double from g_small/x:0 incompatible with expected double_ref.
During handling of the above exception, another exception occurred:
[...]
ValueError: Input 0 of node gg/a/Assign was passed double from g_small/x:0 incompatible with expected double_ref.

Please notice: everything works correctly if the definition of graph_small above is replaced with the following one:  

with graph_small.as_default():
    tf.get_variable(name='x', shape=[1], dtype=tf.float64)
    tf.get_variable(name='y', shape=[1], dtype=tf.float64)
    s_small = tf.train.Saver()  
    
Thanx a lot!

**Comment by TanCari** [comment]
PS: Here above is just an attempt to obtain what I actually need.
Maybe there are better ways. Here under I describe my esential
goal.


Given the graph

with graph_small.as_default():
    v = tf.get_variable(name='v', shape=[2], dtype=tf.float64)
    x = tf.identity(v[:1], name='x')
    y = tf.identity(v[1:], name='y')
    
it is easy to build it up to the following one by simply adding 
variables:

with graph_together.as_default():
    tf.train.import_meta_graph(adr_small+'.meta', import_scope='g_small')
    x = graph_together.get_tensor_by_name('g_small/x:0')
    y = graph_together.get_tensor_by_name('g_small/y:0')
    tf.train.import_meta_graph(adr_big+'.meta', import_scope='g_big', input_map={'a:0':x, 'b:0':y})
    c = graph_together.get_tensor_by_name('g_big/c:0')
    gra = tf.gradients([c],[x])
    

Suppose now, that we start from the following graph, instead:

with graph_big.as_default():
    a = tf.get_variable(name='a', shape=[1], dtype=tf.float64)
    b = tf.get_variable(name='b', shape=[1], dtype=tf.float64)
    c = tf.add(a, b, name='c')
    s = tf.train.Saver()
    
How can we the get to "graph_together" defined above? In other words, 
how can we add variables not "downstream" but "upstream"? 
It would be eesential for me, that everything than works correctly with
gradients and hessians.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
