### ISSUE TITLE
TF_CPP_MIN_LOG_LEVEL=3 does not work after upgrading to 1.13.1

### ISSUE THREAD

**Issue by abhiboost** [tensorflow/tensorflow#26348]
After upgrading to 1.13.1, the `TF_CPP_MIN_LOG_LEVEL` does not seem to work for certain warnings.
For example, I get the following warnings even if log level is set to 3:

```
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.

```

**Comment by ymodak** [comment]
Can you test against tf-nightly and see if the behavior still persists? Thanks!

**Comment by abhiboost** [comment]
@ymodak , apparently, doing it this way worked! 

thanks!

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by RAGHURAM-SADINENI** [comment]
> You can try this instead,
> 
> ```python
> import tensorflow as tf
> tf.logging.info('TensorFlow')
> INFO:tensorflow:TensorFlow
> tf.logging.set_verbosity(tf.logging.ERROR)
> tf.logging.info('TensorFlow')
> ```

Can you explain these statements??

**Comment by ktsumura** [comment]
Does anyone know how to do this in C++?

**Comment by codeananda** [comment]
> You can try this instead,
> 
> ```python
> import tensorflow as tf
> tf.logging.info('TensorFlow')
> INFO:tensorflow:TensorFlow
> tf.logging.set_verbosity(tf.logging.ERROR)
> tf.logging.info('TensorFlow')
> ```

Note that, since TF 2.0 does not have `tf.logging`, you would need to do 

```python
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "1" # or "0", "2", or "3"

import logging
logger = tf.get_logger()
logger.setLevel(logging.ERROR) # or logging.INFO, logging.WARNING, etc.
```
