### ISSUE TITLE
When dose reusebale variable sync between device?

### ISSUE THREAD

**Issue by sun9700** [tensorflow/tensorflow#2634]
I want to validate model under training after certain iterations on train set.
The switch between train and validate is controlled by global set.
Training is on GPU:1, while validation is on CPU:0.
If share the variable between GPU and CPU using  tf.get_variable_scope().reuse_variables()
when dose the two copy sync?
Every time after GPU apply_gradients or CPU used them in seesion.run(op on CPU)?

**Comment by vrv** [comment]
This is a question for StackOverflow
