### ISSUE TITLE
Wrong outputs of "tensorflow.python.ops.distributions.util.fill_triangular_inverse"

### ISSUE THREAD

**Issue by ZhangXiao96** [tensorflow/tensorflow#26354]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 14.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6

**Describe the current behavior**
tensorflow.python.ops.distributions.util.fill_triangular_inverse didn't give the right outputs.

**Code to reproduce the issue**
import tensorflow as tf
from tensorflow.python.ops.distributions.util import fill_triangular_inverse
import numpy as np

sess = tf.InteractiveSession()
a = np.arange(1, 17).reshape((1, 4, 4))
"""
a = [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]
"""

T = fill_triangular_inverse(a, upper=True)
t = sess.run(T)

"""
t = [ 1  2  3  4 21 21 21 21 21 21]]
"""

**Comment by kraglemylego** [comment]
Why was this closed, it still doesn't work? I don't understand this output

**Comment by ZhangXiao96** [comment]
> Why was this closed, it still doesn't work? I don't understand this output

It doesn't work the way we think. The function only works for the lower-triangular or upper-triangular matrix with the rest part equaling zero, which is also explained in its doc. 

  Example:
  ```python
  fill_triangular_inverse(
    [[4, 0, 0],
     [6, 5, 0],
     [3, 2, 1]])
  # ==> [1, 2, 3, 4, 5, 6]
  fill_triangular_inverse(
    [[1, 2, 3],
     [0, 5, 6],
     [0, 0, 4]], upper=True)
  # ==> [1, 2, 3, 4, 5, 6]
  ````
