### ISSUE TITLE
fatal error: tensorflow/cc/ops/array_ops.h

### ISSUE THREAD

**Issue by allendred** [tensorflow/tensorflow#26357]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

I use c++ API
 
**Describe the problem**
fatal error: tensorflow/cc/ops/array_ops.h
**Provide the exact sequence of commands / steps that you executed before running into the problem**

cant find array_ops.h
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
tensorflow/tensorflow/cc/ops/standard_ops.h:19:41: fatal error: tensorflow/cc/ops/array_ops.h:

**Comment by yuefengz** [comment]
Could you give us more detail? How you run it? What is the error message?

**Comment by allendred** [comment]
> Could you give us more detail? How you run it? What is the error message?

#include <fstream>
#include <utility>
#include <vector>
#include <Eigen/Core>
#include <Eigen/Dense>

#include "tensorflow/cc/ops/const_op.h"
#include "tensorflow/contrib/image/kernels/image_ops.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/graph.pb.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/graph/default_device.h"
#include "tensorflow/core/graph/graph_def_builder.h"
#include "tensorflow/core/lib/core/errors.h"
#include "tensorflow/core/lib/core/stringpiece.h"
#include "tensorflow/core/lib/core/threadpool.h"
#include "tensorflow/core/lib/io/path.h"
#include "tensorflow/core/lib/strings/stringprintf.h"
#include "tensorflow/core/platform/env.h"
#include "tensorflow/core/platform/init_main.h"
#include "tensorflow/core/platform/logging.h"
#include "tensorflow/core/platform/types.h"
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/util/command_line_flags.h"

using namespace std;
using namespace tensorflow;
using namespace tensorflow::ops;
using tensorflow::Flag;
using tensorflow::Tensor;
using tensorflow::Status;
using tensorflow::string;
using tensorflow::int32;

error:

In file included from /home/j/tf_test/minist/tensorflow-c-mnist/tf.cpp:11:0:
/home/tensorflow/tensorflow/cc/ops/standard_ops.h:19:41: fatal error: tensorflow/cc/ops/array_ops.h: 
compilation terminated.
CMakeFiles/tf_test.dir/build.make:62: recipe for target 'CMakeFiles/tf_test.dir/tf.cpp.o' failed
make[2]: *** [CMakeFiles/tf_test.dir/tf.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tf_test.dir/all' failed
make[1]: *** [CMakeFiles/tf_test.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

repo:https://github.com/zhangcliff/tensorflow-c-mnist

**Comment by sushreebarsa** [comment]
@allendred Is this still an issue ? Please make sure you're using TF v2.4 or later as TF v1.x is not actively supported. Please let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors using TF v2, we will get you the right help.Thanks!
