### ISSUE TITLE
[TF 2.0] Checkpoint breaking change for RNN.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#26350]
**Type of breakage**: Breakage with changing code.

**APIs that are affected**: 

1. [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn)
2. [`tf.nn.static_rnn`](https://www.tensorflow.org/api_docs/python/tf/nn/static_rnn)
3. [`tf.nn.bidirectional_dynamic_rnn`](https://www.tensorflow.org/api_docs/python/tf/nn/bidirectional_dynamic_rnn)
4. [`tf.nn.static_bidirectional_rnn`](https://www.tensorflow.org/api_docs/python/tf/nn/static_bidirectional_rnn)
5. All cells within the [`tf.nn.rnn_cell.*`](https://www.tensorflow.org/api_docs/python/tf/nn/rnn_cell) module.

**Description of change**: The current TensorFlow RNN code is going to be replaced by `tf.keras` RNNs in TensorFlow 2.0. User will need to update their code to use the new Keras API. The weights of the Keras RNN cell are different from the existing TensorFlow RNN cell.

**Variable name change map**: The RNN cell weights are in a different format between existing TensorFlow RNN cells and Keras cells. There is currently no direct mapping for that.

**Target time window**: Undecided since the update requires a non-trivial user side change.

**Comment by muddham** [comment]
@dynamicwebpaige In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by karmel** [comment]
Unassigning myself, as this is more of an FYI than a solvable problem.

**Comment by Saduf2019** [comment]
@dynamicwebpaige 
Please let us know if this issue can be moved to closed status.

**Comment by NitinSaini18** [comment]
AttributeError: module 'tensorflow.compat.v1' has no attribute 'contrib'
I am facing this error while using rnn model in my code. Although I used 
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
help me how can I solve it
