### ISSUE TITLE
running the tflite model with a video input?

### ISSUE THREAD

**Issue by aravindchaluvadi** [tensorflow/tensorflow#26355]
I want to give the  tflite object detection model an recorded video input instead of an live streaming video
is that possible?

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by wwdok** [comment]
> I want to give the tflite object detection model an recorded video input instead of an live streaming video
> is that possible?

@aravindchaluvadi Hi,  I want to do this recently, do you have the python script now ? If have, can you share with me ? Thanks !
