### ISSUE TITLE
win10vc2017build failed

### ISSUE THREAD

**Issue by kerwinxu** [tensorflow/tensorflow#26352]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (win10):
- TensorFlow installed from (source or binary): source r1.12
- TensorFlow version: 1.12
- Python version: python 3.7 (anaconda)
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.22
- GCC/Compiler version (if compiling from source): vc 2017
- CUDA/cuDNN version:cuda:10.0/cudnn:7.5
- GPU model and memory: Nvidia Geforce 840M

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

python ./configure.py
...
bazel build -c opt --copt=/arch:AVX2  --config=cuda  --copt=-nvcc_options=disable-warnings //tensorflow/tools/pip_package:build_pip_package  --local_resources 2048,.5,1.0

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

external/com_google_absl\absl/meta/type_traits.h(338): error: static assertion failed with "Not compliant with std::is_trivially_copy_assignable; Standard: true, Implementation: false"
          detected during:
            instantiation of class "absl::is_trivially_copy_assignable<T> [with T=Eigen::Index]"
external/com_google_absl\absl/types/optional.h(267): here
            processing of template argument list for "absl::optional_internal::optional_data" based on template argument <tensorflow::int64>
external/com_google_absl\absl/types/optional.h(485): here
            instantiation of class "absl::optional<T> [with T=tensorflow::int64]"
.\tensorflow/core/framework/allocator.h(68): here

1 error detected in the compilation of "D:/Temp/nvcc_inter_files_tmp_dir/dense_update_functor_gpu.cu.cpp1.ii".
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 7092.230s, Critical Path: 846.02s
INFO: 1705 processes: 1705 local.
FAILED: Build did NOT complete successfully

but std::is_trivially_copy_assignable is ok .
i build the below source 

#include <iostream>

#include <iostream>
#include <utility>
#include <type_traits>
struct Foo { int n; };

int main()
{
    std::cout << "Hello World!\n"; 
	std::cout << std::boolalpha
		<< "Foo is trivially copy-assignable? "
		<< std::is_trivially_copy_assignable<Foo>::value << '\n'
		<< "int[2] is copy-assignable? "
		<< std::is_copy_assignable<int[2]>::value << '\n'
		<< "int is nothrow copy-assignable? "
		<< std::is_nothrow_copy_assignable<int>::value << '\n';
}

outpub the below 
Hello World!
Foo is trivially copy-assignable? true
int[2] is copy-assignable? false
int is nothrow copy-assignable? true

**Comment by alvaroslm** [comment]
I tried vs 2017 too at first and I had to switch to 2015, which works ok. If I remember correctly nvcc was to blame. That was for TF 1.10, I'm now using 1.13 and vs 2015 still works ok.

**Comment by jvishnuvardhan** [comment]
@kerwinxu Please uninstall python and tensorflow and reinstall freshly using the instructions [here](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12). If you want to use Bazel 0.22.0 and CUDA 10.0, then please install TF 1.13.1. Please check [here](https://www.tensorflow.org/install/source_windows#gpu) for tested build configurations. Please let me know how it progresses. Thanks!

**Comment by kerwinxu** [comment]
> I tried vs 2017 too at first and I had to switch to 2015, which works ok. If I remember correctly nvcc was to blame. That was for TF 1.10, I'm now using 1.13 and vs 2015 still works ok.

Thank you , the problem are vc 2017  and  cuda 10 . 

### **Donot build Gpu version with vc 2017  , vc 2017 is incompatible with cuda 10 .  I build gpu version with vc 2015 and cuda 9.0**

**Comment by lissyx** [comment]
@jvishnuvardhan We are hitting the same but on master branch, with VC 14.0 (should be 2015ish) and CUDA 10.0.

**Comment by lissyx** [comment]
> @jvishnuvardhan We are hitting the same but on master branch, with VC 14.0 (should be 2015ish) and CUDA 10.0.

Just to make it clear, the exact same setup works well with CUDA 10.0 and r1.13

**Comment by lissyx** [comment]
> > @jvishnuvardhan We are hitting the same but on master branch, with VC 14.0 (should be 2015ish) and CUDA 10.0.
> 
> Just to make it clear, the exact same setup works well with CUDA 10.0 and r1.13

Our master branch was a couple of days / few weeks old, merging current helps going over that issue.
