### ISSUE TITLE
extend_with_weight_decay function doesn't exist? 

### ISSUE THREAD

**Issue by miktoki** [tensorflow/tensorflow#26360]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.12
- Doc Link: 
https://www.tensorflow.org/versions/r1.12/api_docs/python/tf/contrib/opt/AdamWOptimizer
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/opt/python/training/weight_decay_optimizers.py

**Describe the documentation issue**
In `MomentumWOptimizer`, `AdamWOptimizer` and `DecoupledWeightDecayExtension` the documentation refers to `extend_with_weight_decay`:

```python
  extend_with_weight_decay(tf.train.MomentumOptimizer,
                           weight_decay=weight_decay)
  ```
AFAIK there is no "`extend_with_weight_decay`", only "`extend_with_decoupled_weight_decay`", which seems to serve a similar purpose:

```python
MyAdamW = extend_with_decoupled_weight_decay(tf.train.AdamOptimizer)
  # Create a MyAdamW object
  optimizer = MyAdamW(weight_decay=0.001, learning_rate=0.001)
```
Is my understanding correct?
I could submit a PR if necessary

**Comment by mingxingtan** [comment]
You are right, it should be extend_with_decoupled_weight_decay. 

Would be great if you can create a PR to fix this issue. Thanks!

**Comment by miktoki** [comment]
#26433

**Comment by PhilJd** [comment]
@miktoki Thanks for finding this issue! I'm currently moving these optimizers into addons (tensorflow/addons#164), I've fixed documentation there. Thanks again!

**Comment by mingxingtan** [comment]
Close the issue since it is resolved.
