### ISSUE TITLE
[TF 2.0] Add skip_empty argument to tf.strings.split so that tf.string_split can be deprecated.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#26368]
There were two split functions defined in TensorFlow 1.13:

1. [`tf.string_split`](https://www.tensorflow.org/api_docs/python/tf/string_split)
2. [`string_split_v2`](https://github.com/tensorflow/tensorflow/pull/19650)

We have consolidated these two ops into [`tf.strings.split`](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/strings/split) in TF 2.0:

```
tf.strings.split(
    source,
    sep=None,
    maxsplit=-1
)
```
 and wish to deprecate `tf.string_split`. However, `tf.strings.split` is missing the `skip_empty` functionality included in `string_split`:

```
tf.string_split(
    source,
    delimiter=' ',
    skip_empty=True
)
```

This feature request would be to **include `skip_empty` functionality for `tf.strings.split`**.

**Comment by lhendre** [comment]
Ill take a quick look tonight at it

**Comment by lhendre** [comment]
So I have some code I am testing on my local fork, but an issue I am running against is that it uses the library gen_string_ops which is machine generated,  I am not quite sure how to approach this

**Comment by mikeza** [comment]
> So I have some code I am testing on my local fork, but an issue I am running against is that it uses the library gen_string_ops which is machine generated, I am not quite sure how to approach this

It appears the function signature will need to be modified in the python section as well as the core/ops section and the skip_empty functionality will need to be implemented in the core/kernels section.

@dynamicwebpaige, just to be clear, the skip_empty specifies that the function will not return empty strings in the list of resulting strings?

**Comment by lhendre** [comment]
#26475 . I have added in the needed changes with the unit tests.  I am right now working on end to end tests(compiling takes some time on my machine) and am ensuring clean code standards.  I have opened up a PR for any feedback.

**Comment by shashvatshahi1998** [comment]
i have added added skip_empty in string_split_v2 file and merged it accordingly

**Comment by mikeza** [comment]
> #26475 . I have added in the needed changes with the unit tests. I am right now working on end to end tests(compiling takes some time on my machine) and am ensuring clean code standards. I have opened up a PR for any feedback.

It's pretty rude to take me explaining what to do and opening a PR while I'm building the project. But whatever. Why did you change the default in python to False?

> i have added added skip_empty in string_split_v2 file and merged it accordingly

Sorry, but the OP asked to "include skip_empty functionality" which requires more significant changes than modifying the Python function signature.

**Comment by lhendre** [comment]
I'm sorry if this appears rude, but I was also in the process of building the project as was previously stated and had work done as well.  
When tf.strings.split is called elsewhere in the code, based on the other unit tests, it appears to expect the function to work as if the default value is false.  So I went with that approach.  Do you think it should be changed to handle a default of true?

**Comment by mikeza** [comment]
> When tf.strings.split is called elsewhere in the code, based on the other unit tests, it appears to expect the function to work as if the default value is false. So I went with that approach. Do you think it should be changed to handle a default of true?
It just seems as though the default value should be consistent in the Python and C code. The expected default will have to be decided by someone from the tensorflow team, but maybe they should all be False.

**Comment by lhendre** [comment]
Ill update it shortly then

**Comment by lhendre** [comment]
Updated to default to true, Ill leave the question in the pr review as well though

**Comment by lhendre** [comment]
Quick update, the review requested we do this Post-processing. I am in the process of working on that and have asked him to review what I have so far for that type of solution.  Any thoughts?

**Comment by lhendre** [comment]
The review has requested this be done entirely in preprocessing and made a separate issue

**Comment by dynamicwebpaige** [comment]
Design guidance (as of 06-03-2019) is that the `skip_empty` argument should be removed from `tf.strings.split` (filtering after the fact introduces difficulties). Closing out this issue as working as intended. Apologies for confusion, and thank you for working on this!
