### ISSUE TITLE
ModuleNotFoundError: No module named 'gast'

### ISSUE THREAD

**Issue by sayred1** [tensorflow/tensorflow#26376]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Custom code - https://github.com/SeongokRyu/augmented-GCN

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
GNU/Linux 

- TensorFlow installed from (source or binary):
conda install -c conda-forge tensorflow 

- TensorFlow version (use command below):
1.12.0

- Python version:
Python 3.6.8 

- GPU model and memory:
Processor type - x86_64

Memory:         total - 62G,    used - 58G,   free - 4.3G

**Describe the problem**
Been utilizing tensorflow 1.10.0 for a weeks or so, and the custom code I've been running gave me no issues. After updating to 1.12.0 today, I get an error rooting from the `tf.get_variable()` function: ModuleNotFoundError: No module named 'gast'.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Before running into the problem I updated tensorflow with `conda update tensorflow=1.12.0` then proceeded to run a script that calls the function which raised the problem.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

<img width="1047" alt="screen shot 2019-03-05 at 21 23 10" src="https://user-images.githubusercontent.com/35546511/53857913-eca94b80-3f8c-11e9-9c9f-7a23260928f0.png">

**Comment by DachuanZhao** [comment]
Hi,@sayred1 
I guess you can run the following command to solve it:
`pip install gast`

**Comment by paythonme** [comment]
i got this error when i install gast
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::tqdm-4.32.1-py_0'.
CondaError: Cannot link a source that does not exist. C:\Python-Anaconda\Anaconda3\Scripts\conda.exe
Attempting to roll back.

**Comment by armansamimi** [comment]
> Hi,@sayred1
> I guess you can run the following command to solve it:
> `pip install gast`

when i did this command, cmd told me that "Requirement already satisfied: gast in c:\users\asus\anaconda3\lib\site-packages (0.2.2)" , but in my Spyder still this error is repeated . please help me

**Comment by zgushonka** [comment]
try 
```
pip uninstall gast
pip install tensorflow
```

**Comment by elfelround** [comment]
ERROR: tensorflow-gpu 2.2.0 has requirement gast==0.3.3, but you'll have gast 0.2.2 which is incompatible.
ERROR: tensorflow-gpu 2.2.0 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 2.0.0 which is incompatible.
ERROR: tensorflow-gpu 2.2.0 has requirement tensorflow-estimator<2.3.0,>=2.2.0, but you'll have tensorflow-estimator 2.0.0 which is incompatible.

so i had this error and i downgraded gast and others cause the previous message was asking for a downgrade but upon downgrading then the flag was asking upgrade, not sure if it has to do with me having both installed tensofrlow and tensorflow-gpu
