### ISSUE TITLE
Centos7.6+python37+tensorflow1.13.1 : ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#26378]
```
Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow


Traceback (most recent call last):
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
CentOS Linux release 7.6.1810 (Core)
- TensorFlow installed from (source or binary):
pip install tensorflow
- TensorFlow version:
1.13.1
- Python version:
Python 3.7.1
- Installed using virtualenv? pip? conda?:
pip install tensorflow

**Describe the problem**
I think the problem is that the version of gcc is 4.8 on Centos7.6.
What should I do to install tensorflow1.13 with Centos7+python37 ?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
$ pip install tensorflow
$ python 
>>> import tensorflow
```

**Comment by Leslie-Fang** [comment]
what's your libstdc++.so.6 linked version?.

**Comment by Leslie-Fang** [comment]
Build gcc 6.3, you would get libstdc++.so.6.0.22. Create  libstdc++.so.6 soft-link to it, may solve your problem

**Comment by DachuanZhao** [comment]
Hi,@Leslie-Fang, 
The libstdc++.so.6 linked version is libstdc++.so.6.0.19 on Centos7.6
I don't want to change the system file in` /lib64` because it maybe bring other problems.
Is there any soluiton to solve it without using `sudo`

**Comment by Leslie-Fang** [comment]
```strings /usr/lib64/libstdc++.so.6.0.19 | grep CXXABI_ ``` to check whether `CXXABI_1.3.8'.
If not, you could use latest lib version. Set the LD_LIBRARY_PATH before you run TF, so this lib would only be effective in this shell.

**Comment by DachuanZhao** [comment]
Hi,@Leslie-Fang 
the result is :
```
-bash-4.2$ strings /usr/lib64/libstdc++.so.6.0.19 | grep CXXABI_
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1
```
How can I install the latest lib version without `sudo`?

**Comment by Leslie-Fang** [comment]
Build GCC6.3, you will get the libstdc++.so.6.0.22

**Comment by DachuanZhao** [comment]
Hi,@Leslie-Fang 
Building GCC6.3 needs `sudo`.Is there any solution else?

**Comment by Leslie-Fang** [comment]
@DachuanZhao Could you search libstdc++.so.6.0.22 online? I think it's available.

**Comment by tamkaho** [comment]
Has this been resolved yet?

**Comment by JamesHWade** [comment]
Just wanted to add that I have this issue, as well. Very similar configuration as OP.

**Comment by Ben-USC** [comment]
same issue here, does anyone know how to resolve?

**Comment by marklakata** [comment]
We have several versions of python available to use. I had this problem which I tried to use python/3.7.3, because it was compiled with gcc/6.4 (on a different system), but our system only has gcc/6.3.1 support.  I found that we have an older version of python (3.6.2) that was compiled with gcc/4.8.5, so I switched to that, and then `import tensorflow` worked just fine.

So the workaround is to install a version of python that is compatible (or older) with gcc on your system. 

When you run python, it immediately prints out the version of gcc support to the console, and you can check the version of gcc install with `gcc --version`.

I bet that if you recompile python3 on your system, then tensorflow will run.

This combination worked for me:

`$ python3
Python 3.6.2 (default, Jul 27 2017, 20:29:23)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux

$ gcc --version
gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)
`
(python older than gcc)

**Comment by anilkumar2444** [comment]
It gave me same error when I tried to install with pip. I am using conda. I tried with conda (conda install tensorflow). It worked.

**Comment by dynamicwebpaige** [comment]
Looping back on this issue - would it be possible to add a more informative error message detailing @marklakata's [explanation](https://github.com/tensorflow/tensorflow/issues/26378#issuecomment-486345435)?

@martinwicke

**Comment by ha-lins** [comment]
> We have several versions of python available to use. I had this problem when I tried to use python/3.7.3, because it was compiled with gcc/6.4 (on a different system), but our system only has gcc/6.3.1 support. I found that we have an older version of python (3.6.2) that was compiled with gcc/4.8.5, so I switched to that, and then `import tensorflow` worked just fine.
> 
> So the workaround is to install a version of python that is compatible (or older) with gcc on your system.
> 
> When you run python, it immediately prints out the version of gcc support to the console, and you can check the version of gcc install with `gcc --version`.
> 
> I bet that if you recompile python3 on your system, then tensorflow will run.
> 
> This combination worked for me:
> 
> ```
> $ python3
> Python 3.6.2 (default, Jul 27 2017, 20:29:23)
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
> 
> $ gcc --version
> gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)
> ```
> 
> (python older than gcc)

I tried to reinstall the lower version of python with the older version gcc and it worked. Thanks!
> $ conda install python==3.6.0  (the former version is 3.6.1)

**Comment by mohantym** [comment]
Hi @DachuanZhao ! Could you please visit [here ](https://www.tensorflow.org/install)for more details on errors and installation procedures.  We  also see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!
