### ISSUE TITLE
TensorFlow Lite Android nightly runs inference x2 faster than latest version 1.13.1

### ISSUE THREAD

**Issue by pabloppp** [tensorflow/tensorflow#26385]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: OnePlus 6
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `org.tensorflow:tensorflow-lite:0.0.0-nightly` / `org.tensorflow:tensorflow-lite:1.13.1`

**Describe the current behavior**
I am a contributor of [this library](https://github.com/the-super-toys/glimpse-android) where we use TensorFlow lite to run a custom model.
When using the `org.tensorflow:tensorflow-lite:0.0.0-nightly` verstion of tensorflow lite we achieve an inference time of 22ms (the model setup takes about 5ms).
If we just change the version to `org.tensorflow:tensorflow-lite:1.13.1` without changing anything else in our code, the inference time goes up to 40ms (the model setup now takes less than 1ms).

Why could this be happening? Is this a bug or the nightly version will always provide a faster inference?

**Comment by pabloppp** [comment]
A couple more details:
In order to measure the inference latency, we use the following snippet:
```kotlin
val timings = TimingLogger("GlimpseDebug", "predict")
val intpr = Interpreter(rawModel, Interpreter.Options().apply { setNumThreads(1) })
timings.addSplit("init interpreter")
intpr.run(inputBuffer, output)
timings.addSplit("inference")
timings.dumpToLog()
```
This is the output using `org.tensorflow:tensorflow-lite:0.0.0-nightly`
<img width="212" alt="captura de pantalla 2019-03-06 a las 9 30 14" src="https://user-images.githubusercontent.com/4237014/53866745-8fe07c00-3ff2-11e9-8453-1721c99068e1.png">


While this is the output using `org.tensorflow:tensorflow-lite:1.13.1` (nothing else changes)
<img width="205" alt="captura de pantalla 2019-03-06 a las 9 32 35" src="https://user-images.githubusercontent.com/4237014/53866852-d2a25400-3ff2-11e9-98cc-9339f48ac295.png">

**Comment by buaadf** [comment]
I found that(on Android) differen't tensorflow-lite version would lead to different inference time, and tflight-nightly updates every day, so if I rebuild the project, I'll get totally different inference time, sometimes even the results are different.

**Comment by jvishnuvardhan** [comment]
@pabloppp This is a stale issue. Many bugs have been fixed in the latest TF version. Could you please execute your code using Latest Version 2.6 (and tf-nightly) and let us know if the issue still persists? 

Also, please note that we are not supporting TF1.x. Thanks!
