### ISSUE TITLE
tf2.0, tf.keras cannot be automatically completed in pycharm

### ISSUE THREAD

**Issue by aikudexiaohai** [tensorflow/tensorflow#26383]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by nxphi47** [comment]
Also have this issue

**Comment by JACKHAHA363** [comment]
Same here

**Comment by winterwindwang** [comment]
i also have this issue

**Comment by winterwindwang** [comment]
i found the solution in https://intellij-support.jetbrains.com/hc/en-us/community/posts/360002486739-PyCharm-cannot-import-tensorflow-keras.The method is use `from tensorflow.python import keras`,and it worked in my sitution

**Comment by ttbrunner** [comment]
> i found the solution in https://intellij-support.jetbrains.com/hc/en-us/community/posts/360002486739-PyCharm-cannot-import-tensorflow-keras.The method is use `from tensorflow.python import keras`,and it worked in my sitution

Just a quick word of warning for anyone reading this: this CAN break functionality with newer TF2 versions (>=2.0.0rc0). See this issue: https://github.com/tensorflow/tensorflow/issues/32646

So for anyone who suddenly experiences Keras optimizers crashing after upgrading their TF2 version, consider undoing this workaround.

**Comment by louis925** [comment]
tf.keras also can't be automatically completed in VS Code. Bazel test also can't find the tf.keras. Only the tf.python.keras exists.
