### ISSUE TITLE
Tensorflow GPU Installation Requirement Issues

### ISSUE THREAD

**Issue by thirdlastletter** [tensorflow/tensorflow#26382]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tensorflow-gpu 1.12.0
- Python version: 3.5.2
- Installed using virtualenv? pip? conda?: virtualenv pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version :CUDA Version 10.0.130/ cuDNN 7.4.1
- GPU model and memory: GeForce GTX 108 

I am trying to install TensorFlow using 
`pip install --upgrade tensorflow-gpu`

I end up with the following messages:

`tensorflow 1.12.0 has requirement tensorboard<1.13.0,>=1.12.0, but you'll have tensorboard 1.13.1` `which is incompatible.`
`symfit 0.4.6 has requirement scipy>=1.0, but you'll have scipy 0.17.0 which is incompatible.`
`scikit-image 0.14.1 has requirement pillow>=4.3.0, but you'll have pillow 3.1.2 which is incompatible.`

`Cannot uninstall 'enum34'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

I am not sure how to reinstall the individual components with their correct version (tensorboard, symfit, scikit-image).

**Comment by Culeshovi** [comment]
You can just uninstall any package by running '''pip uninstall pillow''' and then you can install package with required version like '''pip install pillow==4.3.0'''

**Comment by thirdlastletter** [comment]
ok thank you!
