### ISSUE TITLE
building error on win7 with VS2015: ADD_LIBRARY for library tf_contrib_tpu_ops without any source files

### ISSUE THREAD

**Issue by cj741** [tensorflow/tensorflow#26386]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win7 X64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source 
- TensorFlow version:1.13.1
- Python version:3.6
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):cmake
- GCC/Compiler version (if compiling from source):vs 2015
- CUDA/cuDNN version:no cuda
- GPU model and memory:no gpu

**Describe the problem**
when I use cmake GUI config TF, it show me the folowing error message:
"You have called ADD_LIBRARY for library tf_contrib_tpu_ops without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/tpu/ops"
It looks no "ops" under tensorflow/contrib/tpu, anyone have idea how to find the relate source files or how to block the tpu module in config file?
many thanks~
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
We highly encourage you to use bazel to build TF, unfortunately we do not support cmake builds for TF. Thanks!

**Comment by cj741** [comment]
Thanks ymodak! 
Do you have a introduction of how to build TF from bazel? Could you give me a link?
Thanks!

**Comment by ymodak** [comment]
You are welcome. 
Here are the links you asked for,
Build from source - https://www.tensorflow.org/install/source_windows
Build from pip - https://www.tensorflow.org/install/pip  (select windows in step 1 and 2)

**Comment by cj741** [comment]
Thanks ymodak,
I have a try~

**Comment by cj741** [comment]
Hi ymokak,
I have looked the link you provided, it looks to show how to build a .whl package. What I want is build a .sln C++ project for vs2015. Since there is no folder  "ops" under the tensorflow/contrib/tpu, I got failure when I configure. Do you have idea on that?
Thanks~

**Comment by ymodak** [comment]
@cj741 Were you able to solve this issue?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by cj741** [comment]
Hi ymodak,
I still have the following problem, when I generate the sln file. I think the problem is all the source files were moved to "tensorflow/core/tpu", do you have idea how to change the path from "tensorflow/contrib/tpu/ops" to "tensorflow/core/tpu"? 

"You have called ADD_LIBRARY for library tf_contrib_tpu_ops without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at tf_python.cmake:217 (message):
  Python module not found: tensorflow/contrib/tpu/ops"

thanks,
Jin

**Comment by DavideCatto** [comment]
> Hi ymodak,
> I still have the following problem, when I generate the sln file. I think the problem is all the source files were moved to "tensorflow/core/tpu", do you have idea how to change the path from "tensorflow/contrib/tpu/ops" to "tensorflow/core/tpu"?
> 
> "You have called ADD_LIBRARY for library tf_contrib_tpu_ops without any source files. This typically indicates a problem with your CMakeLists.txt file
> CMake Error at tf_python.cmake:217 (message):
> Python module not found: tensorflow/contrib/tpu/ops"
> 
> thanks,
> Jin

Modify _tf_core_kernels.cmake_ with all wrong path dependencies. Also tf_core_ops.cmake have same path to change. 
I'm using tensorflow r1.14, Visual Studio 2015, no python bindings, only c++ interface.

**Comment by shayan-h72** [comment]
> @cj741 Were you able to solve this issue?

[https://github.com/tensorflow/tensorflow/commit/a45d4bd80c3d93466a8daf641fe699c6d00096f2](url)
