### ISSUE TITLE
build_info is missing CUDA build information

### ISSUE THREAD

**Issue by javidcf** [tensorflow/tensorflow#26395]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): b'v1.12.0-rc2-3-ga6d8ffae09' 1.12.0
- Python version: 3.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: CUDA 9.0 cuDNN 7.0.5
- GPU model and memory: NVIDIA Titan V

**Describe the current behavior**

The internal `build_info` module can be used to query information about the build, importing it like:

```py
from tensorflow.python.platform import build_info
```

 However, while in previous versions you could get for things like `build_info.cuda_version_number` or `build_info.cudnn_version_number`, now the only available relevant attribute is `build_info.is_cuda_build` (and in TensorFlow 1.13.1 also `build_info.msvcp_dll_name`).

**Describe the expected behavior**

The `build_info` module should also contain information about CUDA version among other things.

**Code to reproduce the issue**

```py
from tensorflow.python.platform import build_info
print(build_info.cuda_version_number)
# AttributeError: module 'tensorflow.python.platform.build_info' has no attribute 'cuda_version_number'
```

**Other info / logs**

The `build_info` module is generated during the build process by [`gen_build_info.py`](https://github.com/tensorflow/tensorflow/blob/v1.13.1/tensorflow/tools/build_info/gen_build_info.py). Looking through the source, it seems the now deprecated CMake build system would fill this information in [`tensorflow/contrib/cmake/CMakeLists.txt`](https://github.com/tensorflow/tensorflow/blob/v1.13.1/tensorflow/contrib/cmake/CMakeLists.txt#L557-L563), that would be used by the command defined in [`tensorflow/contrib/cmake/tf_python.cmake`](https://github.com/tensorflow/tensorflow/blob/v1.13.1/tensorflow/contrib/cmake/tf_python.cmake#L239-L240), which actually called [`gen_build_info.py`](https://github.com/tensorflow/tensorflow/blob/v1.13.1/tensorflow/tools/build_info/gen_build_info.py). Now however the corresponding Bazel build rule in [`tensorflow/tensorflow.bzl`](https://github.com/tensorflow/tensorflow/blob/v1.13.1/tensorflow/tensorflow.bzl#L2011-L2019) only provides the build type (`"cuda"` or `"cpu"`) and recently also `msvcp_dll_name` on Windows.

Even though this is not a public API, it seems like a step backwards to miss this information with respect to the CMake build system.

**Comment by mrry** [comment]
@meteorcloudy This regressed when we switched to using Bazel for the build on Windows. Is there a way to pass the CUDA and cuDNN version information to the genrule [here](https://github.com/tensorflow/tensorflow/blob/v1.13.1/tensorflow/tensorflow.bzl#L2011-L2019) so that we get the better error messages again?

**Comment by meteorcloudy** [comment]
OK, I will take a look!

**Comment by pavlexander** [comment]
So what is the resolution to this problem?

getting
> AttributeError: module 'tensorflow.python.platform.build_info' has no attribute 'cuda_version_number'

using tensorflow, tensorflow-gpu `2.4.0-rc1`
