### ISSUE TITLE
str_cat.h(267): error :expression must have a constant value

### ISSUE THREAD

**Issue by wuyankun** [tensorflow/tensorflow#26391]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):gentoo 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:No, intel PC
- TensorFlow installed from (source or binary): source
- TensorFlow version:1.12.0 and 1.13.0-r2
- Python version:3.4.3
- Installed using virtualenv? pip? conda?:no 
- Bazel version (if compiling from source):0.20.0
- GCC/Compiler version (if compiling from source): 4.9.3
- CUDA/cuDNN version:8.0/6.0
- GPU model and memory:Geferfoce 1050Ti

external/com_google_absl/absl/strings/string_view.h(496): warning: expression has no effect
external/com_google_absl/absl/strings/str_cat.h(267): error: expression must have a constant value
external/com_google_absl/absl/strings/str_cat.h(267): error: expression must have a constant value

**Comment by jvishnuvardhan** [comment]
@wuyankun Could you provide more details on the issue and its context? Were you able to successfully install TF? Could you provide a code to reproduce the bug? Please provide more details to find root-cause of the issue. Thanks!

**Comment by wuyankun** [comment]
Package:    sci-libs/tensorflow-1.12.0
Repository: gentoo
Maintainer: perfinion@gentoo.org
USE:        abi_x86_64 amd64 cpu_flags_x86_sse cpu_flags_x86_sse2 cuda elibc_glibc kernel_linux python_targets_python2_7 python_targets_python3_4 userland_GNU
FEATURES:   nostrip preserve-libs sandbox splitdebug userpriv usersandbox
Checking for at least 5 GiB RAM ...
Checking for at least 5 GiB disk space at "/var/tmp/portage/sci-libs/tensorflow-1.12.0/temp" ...

>>> Unpacking source...
>>> Unpacking tensorflow-1.12.0.tar.gz to /var/tmp/portage/sci-libs/tensorflow-1.12.0/work
>>> Unpacking tensorflow-patches-1.12.0.tar.bz2 to /var/tmp/portage/sci-libs/tensorflow-1.12.0/work
Copying fft.tgz to bazel distdir as oourafft-20061228.tgz
Copying fd6845384b86.tar.gz to bazel distdir as eigen-fd6845384b86.tar.gz
Copying 48cd2c3f351ff188bc85684b84a91b6e6d17d896.tar.gz to bazel distdir as abseil-cpp-48cd2c3f351ff188bc85684b84a91b6e6d17d896.tar.gz
Copying dbb96841cc0a5fb2664c37822803b06dab20c7d1.tar.gz to bazel distdir as bazelbuild-rules_closure-dbb96841cc0a5fb2664c37822803b06dab20c7d1.tar.gz
Copying 3992066a95b823efc8ccc1baf82a1cfc73f6e9b8.zip to bazel distdir as double-conversion-3992066a95b823efc8ccc1baf82a1cfc73f6e9b8.zip
Copying 816a4ae622e964763ca0862d9dbd19324a1eaf45.tar.gz to bazel distdir as farmhash-816a4ae622e964763ca0862d9dbd19324a1eaf45.tar.gz
Copying 38ebac7b059e84692f53e5938f97a9943c120d98.zip to bazel distdir as gemmlowp-38ebac7b059e84692f53e5938f97a9943c120d98.zip
Copying fd3d9af80465e4383162e4a7c5e2f406e82dd968.tar.gz to bazel distdir as highwayhash-fd3d9af80465e4383162e4a7c5e2f406e82dd968.tar.gz
Copying 03d856977ecbaac87e598c0c4bafca96761b9ac7.tar.gz to bazel distdir as nvidia-nccl-03d856977ecbaac87e598c0c4bafca96761b9ac7.tar.gz
Copying 1.8.0.zip to bazel distdir as cub-1.8.0.zip
Copying backports.weakref-1.0rc1.tar.gz to bazel distdir
>>> Source unpacked in /var/tmp/portage/sci-libs/tensorflow-1.12.0/work
>>> Preparing source in /var/tmp/portage/sci-libs/tensorflow-1.12.0/work/tensorflow-1.12.0 ...
Applying 0001-Make-AWS-GCP-HDFS-Kafka-and-Ignite-default-on-but-in.patch ...
Applying 0002-systemlibs-unbundle-icu.patch ...
Applying 0003-systemlibs-Unbundle-protobuf.patch ...
Applying 0004-no_support-flags-were-negated-so-did-not-work.patch ...
Applying 0005-Use-Starlark-version-of-http_archive.patch ...
Applying 0006-Add-k8-to-toolchains.patch ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-libs/tensorflow-1.12.0/work/tensorflow-1.12.0 ...
Setting CUDA version: 8.0
Setting CUDNN version: 6.0
Extracting Bazel installation...
WARNING: ignoring LD_PRELOAD in environment.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: 07e4ebc7-e002-4c6b-ae9d-b5f2b3e40245
You have bazel 0.20.0- (@non-git) installed.
NVIDIA: failed to execute `/usr/bin/nvidia-modprobe -u`: Permission denied.
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 3.5]: 

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=gdr         	# Build with GDR support.
	--config=verbs       	# Build with libverbs support.
	--config=ngraph      	# Build with Intel nGraph support.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=noignite    	# Disable Apacha Ignite support.
	--config=nokafka     	# Disable Apache Kafka support.
Configuration finished
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-libs/tensorflow-1.12.0/work/tensorflow-1.12.0 ...
bazel --bazelrc=/var/tmp/portage/sci-libs/tensorflow-1.12.0/temp/bazelrc --output_base=/var/tmp/portage/sci-libs/tensorflow-1.12.0/work/tensorflow-1.12.0-bazel-base build --nobuild //tensorflow:libtensorflow_framework.so //tensorflow:libtensorflow.so //tensorflow:libtensorflow_cc.so
WARNING: ignoring LD_PRELOAD in environment.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO:Invocation ID: 62d945b0-af42-4b34-a9a8-fc9ba6a0858b
Loading:
32mLoading:0 packages loaded
    currently loading: tensorflow
    Fetching @local_config_cuda; fetching
    Fetching @local_config_rocm; Restarting.

bazel --bazelrc=/var/tmp/portage/sci-libs/tensorflow-1.12.0/temp/bazelrc --output_base=/var/tmp/portage/sci-libs/tensorflow-1.12.0/work/tensorflow-1.12.0-bazel-base build //tensorflow:libtensorflow_framework.so //tensorflow:libtensorflow.so
WARNING: ignoring LD_PRELOAD in environment.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: dd7e0bfa-b412-4a1a-8d17-a8780e43d75d


In file included from ./tensorflow/core/framework/common_shape_fns.h:22:0,
                 from ./tensorflow/core/framework/resource_mgr.h:25,
                 from ./tensorflow/core/common_runtime/device.h:43,
                 from ./tensorflow/core/common_runtime/device_set.h:23,
                 from ./tensorflow/core/grappler/clusters/cluster.h:24,
                 from ./tensorflow/core/grappler/costs/graph_properties.h:22,
                 from tensorflow/core/grappler/costs/graph_properties.cc:16:
./tensorflow/core/util/tensor_format.h: In function 'tensorflow::TensorShape tensorflow::ShapeFromFormat(tensorflow::TensorFormat, tensorflow::int64, tensorflow::gtl::ArraySlice<long long int>, tensorflow::int64)':
./tensorflow/core/util/tensor_format.h:501:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (format == FORMAT_NHWC_VECT_W && dim == spatial.size() - 1) {
                                             ^
In file included from tensorflow/core/grappler/costs/graph_properties.cc:31:0:
./tensorflow/core/grappler/utils.h: In function 'int tensorflow::grappler::NodePositionIfSameNode(const string&, const string&)':
./tensorflow/core/grappler/utils.h:117:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       std::distance(input_it, input_name.end()) < node_name.size()) {
                                                 ^
tensorflow/core/grappler/costs/graph_properties.cc: In member function 'tensorflow::Status tensorflow::grappler::SymbolicShapeRefiner::UpdateFunction(const tensorflow::NodeDef*)':
tensorflow/core/grappler/costs/graph_properties.cc:501:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < grappler_function_item.inputs().size(); ++i) {
                       ^
tensorflow/core/grappler/costs/graph_properties.cc:556:55: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       } else if (ic->input_tensors_as_shapes().size() > i &&
                                                       ^
tensorflow/core/grappler/costs/graph_properties.cc:599:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (port_id >= output_properties.size()) {
                   ^
tensorflow/core/grappler/costs/graph_properties.cc: In member function 'tensorflow::Status tensorflow::grappler::SymbolicShapeRefiner::UpdateNode(const tensorflow::NodeDef*, bool*)':
tensorflow/core/grappler/costs/graph_properties.cc:697:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (c->output_tensors_as_shapes.size() > src_output) {
                                                ^
tensorflow/core/grappler/costs/graph_properties.cc: In member function 'bool tensorflow::grappler::SymbolicShapeRefiner::EquivalentShapesAndTypes(const std::vector<tensorflow::shape_inference::ShapeAndType>&, const std::vector<tensorflow::shape_inference::ShapeAndType>&) const':
tensorflow/core/grappler/costs/graph_properties.cc:869:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < st1.size(); ++i) {
                       ^
tensorflow/core/grappler/costs/graph_properties.cc: In member function 'tensorflow::Status tensorflow::grappler::SymbolicShapeRefiner::AddFunction(const tensorflow::NodeDef*)':
tensorflow/core/grappler/costs/graph_properties.cc:896:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (grappler_function_item.inputs().size() > function_node->input_size()) {
                                                ^
tensorflow/core/grappler/costs/graph_properties.cc: In static member function 'static tensorflow::Status tensorflow::grappler::GraphProperties::UpdateEnqueue(const tensorflow::NodeDef*, const std::unordered_map<const tensorflow::NodeDef*, const tensorflow::NodeDef*>&, tensorflow::grappler::SymbolicShapeRefiner*, bool*)':
tensorflow/core/grappler/costs/graph_properties.cc:1501:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 1; i < ctx->input_types.size(); ++i) {
                     ^
tensorflow/core/grappler/costs/graph_properties.cc: In member function 'tensorflow::Status tensorflow::grappler::GraphProperties::InferStatically(bool)':
tensorflow/core/grappler/costs/graph_properties.cc:1688:57: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         } else if (ic->input_tensors_as_shapes().size() > i &&
                                                         ^
tensorflow/core/grappler/costs/graph_properties.cc:1715:57: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         } else if (ctx->output_tensors_as_shapes.size() > i &&
                                                         ^
In file included from ./tensorflow/core/platform/default/logging.h:24:0,
                 from ./tensorflow/core/platform/logging.h:25,
                 from ./tensorflow/core/lib/core/status.h:25,
                 from ./tensorflow/core/lib/core/errors.h:21,
                 from ./tensorflow/core/framework/tensor_shape.h:23,
                 from ./tensorflow/core/framework/partial_tensor_shape.h:20,
                 from ./tensorflow/core/framework/attr_value_util.h:23,
                 from ./tensorflow/core/framework/node_def_util.h:22,
                 from ./tensorflow/core/framework/shape_inference.h:20,
                 from ./tensorflow/core/grappler/costs/graph_properties.h:21,
                 from tensorflow/core/grappler/costs/graph_properties.cc:16:
./tensorflow/core/util/tensor_format.h: In instantiation of 'T tensorflow::GetTensorDim(tensorflow::gtl::ArraySlice<T>, tensorflow::TensorFormat, char) [with T = long long int; tensorflow::gtl::ArraySlice<T> = absl::Span<const long long int>]':
./tensorflow/core/util/tensor_format.h:452:47:   required from here
./tensorflow/core/util/tensor_format.h:420:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   CHECK(index >= 0 && index < dimension_attributes.size())
                             ^
./tensorflow/core/platform/macros.h:87:47: note: in definition of macro 'TF_PREDICT_FALSE'
 #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
                                               ^
./tensorflow/core/util/tensor_format.h:420:3: note: in expansion of macro 'CHECK'
   CHECK(index >= 0 && index < dimension_attributes.size())
   ^
./tensorflow/core/util/tensor_format.h: In instantiation of 'T tensorflow::GetFilterDim(tensorflow::gtl::ArraySlice<T>, tensorflow::FilterTensorFormat, char) [with T = long long int; tensorflow::gtl::ArraySlice<T> = absl::Span<const long long int>]':
./tensorflow/core/util/tensor_format.h:461:54:   required from here
./tensorflow/core/util/tensor_format.h:435:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   CHECK(index >= 0 && index < dimension_attribute.size())
                             ^
./tensorflow/core/platform/macros.h:87:47: note: in definition of macro 'TF_PREDICT_FALSE'
 #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
                                               ^
./tensorflow/core/util/tensor_format.h:435:3: note: in expansion of macro 'CHECK'
   CHECK(index >= 0 && index < dimension_attribute.size())
   ^

In file included from tensorflow/core/grappler/utils.cc:16:0:
./tensorflow/core/grappler/utils.h: In function 'int tensorflow::grappler::NodePositionIfSameNode(const string&, const string&)':
./tensorflow/core/grappler/utils.h:117:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       std::distance(input_it, input_name.end()) < node_name.size()) {
                                                 ^
tensorflow/core/grappler/utils.cc: In function 'void tensorflow::grappler::PermuteNodesInPlace(tensorflow::GraphDef*, std::vector<int>*, bool)':
tensorflow/core/grappler/utils.cc:327:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     while (n != (*permutation)[n]) {
              ^
tensorflow/core/grappler/utils.cc: In member function 'std::string tensorflow::grappler::SimpleGraphView::PrintToString() const':
tensorflow/core/grappler/utils.cc:500:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int j = 0; j < outputs(i).size(); ++j) {
                       ^
    Compiling .../contrib/cloud/kernels/bigquery_table_accessor.cc; 10s local
    Compiling tensorflow/core/kernels/sequence_ops.cc; 8s local
    Compiling tensorflow/core/kernels/searchsorted_op_gpu.cu.cc; 2s local
    [-----] Linking tensorflow/core/kernels/libcolorspace_op_gpu.pic.lo

INFO: From Compiling tensorflow/contrib/cloud/kernels/bigquery_table_accessor.cc:
[984 / 1,066]8 actions running
    Compiling tensorflow/core/kernels/svd_op_complex64.cc; 141s local
    Compiling tensorflow/core/kernels/svd_op_complex128.cc; 134s local
    Compiling .../core/kernels/data/group_by_window_dataset_op.cc; 21s local
    Compiling tensorflow/core/kernels/data/iterator_ops.cc; 21s local
    Compiling .../contrib/cloud/kernels/bigquery_table_accessor.cc; 11s local
    Compiling tensorflow/core/kernels/sequence_ops.cc; 8s local
    Compiling tensorflow/core/kernels/searchsorted_op_gpu.cu.cc; 2s local
    Linking tensorflow/core/kernels/libcolorspace_op_gpu.pic.lo; 0s local

Ktensorflow/contrib/cloud/kernels/bigquery_table_accessor.cc: In function 'tensorflow::Status tensorflow::{anonymous}::ParseJson(tensorflow::StringPiece, Json::Value*)':
tensorflow/contrib/cloud/kernels/bigquery_table_accessor.cc:35:16: warning: 'Reader' is deprecated (declared at /usr/include/jsoncpp/json/reader.h:35): Use CharReader and CharReaderBuilder instead [-Wdeprecated-declarations]
   Json::Reader reader;
                ^
[984 / 1,066] 8 actions running
    Compiling tensorflow/core/kernels/svd_op_complex64.cc; 141s local
    Compiling tensorflow/core/kernels/svd_op_complex128.cc; 134s local
    Compiling .../core/kernels/data/group_by_window_dataset_op.cc; 21s local
    Compiling tensorflow/core/kernels/data/iterator_ops.cc; 21s local
    Compiling .../contrib/cloud/kernels/bigquery_table_accessor.cc; 11s local
    Compiling tensorflow/core/kernels/sequence_ops.cc; 8s local
    Compiling tensorflow/core/kernels/searchsorted_op_gpu.cu.cc; 2s local
    Linking tensorflow/core/kernels/libcolorspace_op_gpu.pic.lo; 0s local

[988 / 1,071] 8 actions running
    Compiling tensorflow/core/kernels/svd_op_complex64.cc; 141s local
    Compiling tensorflow/core/kernels/svd_op_complex128.cc; 134s local
    Compiling .../core/kernels/data/group_by_window_dataset_op.cc; 21s local
    Compiling tensorflow/core/kernels/data/iterator_ops.cc; 21s local
    Compiling tensorflow/core/kernels/sequence_ops.cc; 8s local
    Compiling tensorflow/core/kernels/searchsorted_op_gpu.cu.cc; 3s local
    Compiling .../distributed_runtime/device_resolver_distributed.cc; 0s local
    Compiling .../core/kernels/matrix_solve_ls_op_complex64.cc; 0s local

[989 / 1,071] 8 actions, 7 running
    Compiling tensorflow/core/kernels/svd_op_complex64.cc; 141s local
    Compiling tensorflow/core/kernels/svd_op_complex128.cc; 134s local
    Compiling .../core/kernels/data/group_by_window_dataset_op.cc; 22s local
    Compiling tensorflow/core/kernels/data/iterator_ops.cc; 21s local
    Compiling tensorflow/core/kernels/searchsorted_op_gpu.cu.cc; 3s local
    Compiling .../distributed_runtime/device_resolver_distributed.cc; 0s local
    Compiling .../core/kernels/matrix_solve_ls_op_complex64.cc; 0s local
    [-----] Linking tensorflow/core/kernels/libsequence_ops.pic.lo

[990 / 1,072] 8 actions running
    Compiling tensorflow/core/kernels/svd_op_complex64.cc; 142s local
    Compiling tensorflow/core/kernels/svd_op_complex128.cc; 135s local
    Compiling .../core/kernels/data/group_by_window_dataset_op.cc; 22s local
    Compiling tensorflow/core/kernels/data/iterator_ops.cc; 22s local
    Compiling tensorflow/core/kernels/searchsorted_op_gpu.cu.cc; 3s local
    Compiling .../distributed_runtime/device_resolver_distributed.cc; 1s local
    Compiling .../core/kernels/matrix_solve_ls_op_complex64.cc; 0s local
    Compiling tensorflow/core/kernels/matrix_solve_ls_op_double.cc; 0s local

INFO: From Compiling tensorflow/core/kernels/data/group_by_window_dataset_op.cc:
[990 / 1,072] 8 actions running
    Compiling tensorflow/core/kernels/svd_op_complex64.cc; 142s local
    Compiling tensorflow/core/kernels/svd_op_complex128.cc; 135s local
    Compiling .../core/kernels/data/group_by_window_dataset_op.cc; 22s local
    Compiling tensorflow/core/kernels/data/iterator_ops.cc; 22s local
    Compiling tensorflow/core/kernels/searchsorted_op_gpu.cu.cc; 4s local
    Compiling .../distributed_runtime/device_resolver_distributed.cc; 1s local
    Compiling .../core/kernels/matrix_solve_ls_op_complex64.cc; 1s local
    Compiling tensorflow/core/kernels/matrix_solve_ls_op_double.cc; 0s local

[KIn file included from ./tensorflow/core/framework/dataset.h:26:0,
                 from ./tensorflow/core/kernels/data/dataset.h:18,
                 from ./tensorflow/core/kernels/data/captured_function.h:23,
                 from tensorflow/core/kernels/data/group_by_window_dataset_op.cc:20:
./tensorflow/core/framework/model.h: In constructor 'tensorflow::data::model::SharedState::SharedState(tensorflow::int64, std::shared_ptr<tensorflow::mutex>, std::shared_ptr<tensorflow::condition_variable>)':
./tensorflow/core/framework/model.h:46:9: warning: 'tensorflow::data::model::SharedState::value' will be initialized after [-Wreorder]
   int64 value;
         ^
./tensorflow/core/framework/model.h:44:26: warning:   'std::shared_ptr<tensorflow::mutex> tensorflow::data::model::SharedState::mu' [-Wreorder]
   std::shared_ptr<mutex> mu;
                          ^
./tensorflow/core/framework/model.h:40:12: warning:   when initialized here [-Wreorder]
   explicit SharedState(int64 value, std::shared_ptr<mutex> mu,
            ^
    Compiling .../distributed_runtime/device_resolver_distributed.cc; 6s local
    Compiling .../core/kernels/matrix_solve_ls_op_complex64.cc; 6s local
    Compiling tensorflow/core/kernels/matrix_solve_ls_op_double.cc; 6s local
    Compiling .../core/kernels/matrix_solve_ls_op_complex128.cc; 5s local
    Compiling tensorflow/core/kernels/matrix_solve_ls_op_float.cc; 0s local


[Kexternal/com_google_absl/absl/strings/string_view.h(496): warning: expression has no effect

external/com_google_absl/absl/strings/str_cat.h(259): error: expression must have a constant value

external/com_google_absl/absl/strings/str_cat.h(259): error: expression must have a constant value

2 errors detected in the compilation of "/var/tmp/portage/sci-libs/tensorflow-1.12.0/temp/tmpxft_00003ad6_00000000-7_searchsorted_op_gpu.cu.cpp1.ii".
[994 / 1,074] 8 actions running
    Compiling tensorflow/core/kernels/svd_op_complex64.cc; 148s local
    Compiling tensorflow/core/kernels/svd_op_complex128.cc; 141s local
    Compiling tensorflow/core/kernels/searchsorted_op_gpu.cu.cc; 9s local
    Compiling .../distributed_runtime/device_resolver_distributed.cc; 6s local
    Compiling .../core/kernels/matrix_solve_ls_op_complex64.cc; 6s local
    Compiling tensorflow/core/kernels/matrix_solve_ls_op_double.cc; 6s local
    Compiling .../core/kernels/matrix_solve_ls_op_complex128.cc; 5s local
    Compiling tensorflow/core/kernels/matrix_solve_ls_op_float.cc; 0s local


ERROR: /var/tmp/portage/sci-libs/tensorflow-1.12.0/work/tensorflow-1.12.0/tensorflow/core/kernels/BUILD:891:1: output 'tensorflow/core/kernels/_objs/searchsorted_op_gpu/searchsorted_op_gpu.cu.pic.o' was not created
[994 / 1,074] 8 actions running
    Compiling tensorflow/core/kernels/svd_op_complex64.cc; 148s local
    Compiling tensorflow/core/kernels/svd_op_complex128.cc; 141s local
    Compiling tensorflow/core/kernels/searchsorted_op_gpu.cu.cc; 9s local
    Compiling .../distributed_runtime/device_resolver_distributed.cc; 6s local
    Compiling .../core/kernels/matrix_solve_ls_op_complex64.cc; 6s local
    Compiling tensorflow/core/kernels/matrix_solve_ls_op_double.cc; 6s local
    Compiling .../core/kernels/matrix_solve_ls_op_complex128.cc; 5s local
    Compiling tensorflow/core/kernels/matrix_solve_ls_op_float.cc; 0s local


ERROR: /var/tmp/portage/sci-libs/tensorflow-1.12.0/work/tensorflow-1.12.0/tensorflow/core/kernels/BUILD:891:1: not all outputs were created or valid
[994 / 1,074] 8 actions running
    Compiling tensorflow/core/kernels/svd_op_complex64.cc; 148s local
    Compiling tensorflow/core/kernels/svd_op_complex128.cc; 141s local
    Compiling tensorflow/core/kernels/searchsorted_op_gpu.cu.cc; 9s local
    Compiling .../distributed_runtime/device_resolver_distributed.cc; 6s local
    Compiling .../core/kernels/matrix_solve_ls_op_complex64.cc; 6s local
    Compiling tensorflow/core/kernels/matrix_solve_ls_op_double.cc; 6s local
    Compiling .../core/kernels/matrix_solve_ls_op_complex128.cc; 5s local
    Compiling tensorflow/core/kernels/matrix_solve_ls_op_float.cc; 0s local


Elapsed time: 580.201s, Critical Path: 162.87s
[1,002 / 1,074] no action

702 processes: 702 local.
[1,002 / 1,074] no action

FAILED: Build did NOT complete successfully

 Build did NOT complete successfully
 ERROR: sci-libs/tensorflow-1.12.0::gentoo failed (compile phase):
 ebazel failed
 Call stack:
 ebuild.sh, line  133:  Called src_compile
 environment, line 4755:  Called ebazel 'build' '//tensorflow:libtensorflow_framework.so' '//tensorflow:libtensorflow.so'
 environment, line 2018:  Called die
 The specific snippet of code:
 "${@}" || die "ebazel failed"
 If you need support, post the output of `emerge --info '=sci-libs/tensorflow-1.12.0::gentoo'`,
 the complete build log and the output of `emerge -pqv '=sci-libs/tensorflow-1.12.0::gentoo'`.
 The complete build log is located at '/var/tmp/portage/sci-libs/tensorflow-1.12.0/temp/build.log'.
 The ebuild environment file is located at '/var/tmp/portage/sci-libs/tensorflow-1.12.0/temp/environment'.
 [31;01m*[0m Working directory: '/var/tmp/portage/sci-libs/tensorflow-1.12.0/work/tensorflow-1.12.0'
 [31;01m*[0m S: '/var/tmp/portage/sci-libs/tensorflow-1.12.0/work/tensorflow-1.12.0'

**Comment by wuyankun** [comment]
Portage 2.2.28 (python 3.4.3-final-0, default/linux/amd64/13.0/desktop/kde, gcc-4.9.3, glibc-2.22-r4, 4.4.111-gentoo+ x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.4.111-gentoo+-x86_64-Intel-R-_Core-TM-_i7-4710MQ_CPU_@_2.50GHz-with-gentoo-2.2
KiB Mem:    16374512 total,  13126992 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Tue, 26 Jul 2016 00:45:01 +0000
sh bash 4.3_p42-r1
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
app-shells/bash:          4.3_p42-r1::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.20.2::gentoo
dev-lang/python:          2.7.10-r1::gentoo, 3.4.3-r1::gentoo, 3.5.2::gentoo
dev-util/cmake:           3.3.1-r1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.19.1::gentoo
sys-apps/sandbox:         2.10-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.3::gentoo (virtual/os-headers)
sys-libs/glibc:           2.22-r4::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-ggdb -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/sandbox.d /etc/splash /etc/terminfo"
CXXFLAGS="-ggdb -O2 -pipe"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news nostrip parallel-fetch preserve-libs protect-owned sandbox sfperms splitdebug strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://mirrors.163.com/gentoo/"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acc acl acpi alsa amd64 ap berkdb bindist bluetooth branding bzip2 cairo cdda cdr cli consolekit cracklib crypt cups cxx dbus debug declarative dri dri3 dts dvd dvdr eap-sim emboss encode exif fam fasteap firefox flac fortran gdbm gif glamor gpm gtk hs2-0 iconv ipv6 jpeg kde kipi lcms ldap libnotify mad mmx mmxext mng modules mp3 mp4 mpeg multilib ncurses nls nptl ogg opengl openmp p2p pam pango pcre pdf phonon plasma png policykit ppds qt3support qt5 readline sdl seccomp semantic-desktop session sna spell sse sse2 startup-notification svg tcpd tdls tiff truetype udev udisks uncommon-eap-types unicode upower usb uxa vorbis wps wxwidgets x264 xattr xcb xcomposite xinerama xml xscreensaver xv xvid xvmc zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx sse sse2 mmxext" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="keyboard mouse evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby20 ruby21" USERLAND="GNU" VIDEO_CARDS="intel i915" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, MAKEOPTS, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON

**Comment by wuyankun** [comment]
@jvishnuvardhan , thanks for your help .maybe you can see the issue  #23127, there are some more info.

**Comment by wuyankun** [comment]
I just switch to cuda 9.0 , the issues is gone, I don't know why, If I can use cuda 8.0 , will be more better

**Comment by jvishnuvardhan** [comment]
@wuyankun Please check tested build configurations [here](https://www.tensorflow.org/install/source_windows#gpu).
For TF1.12, it was built with cuda9.0 which means some of the dependencies will be looking for paths referencing cuda9.0.

Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-1.12.0 | 3.5-3.6 | MSVC 2015 update 3 | Bazel 0.15.0 | 7 | 9

If you want to use cuda8.0, then you need to downgrade to TF1.4.0 which is not recommended as there were lot of improvements over the time. Please close the issue if everything is working fine. Thanks!
