### ISSUE TITLE
Kubernetes GPU Docs & k8s-compatible Docker Images

### ISSUE THREAD

**Issue by bartoszkp** [tensorflow/tensorflow#26393]
- TensorFlow version: 1.13.1
- Doc Link: https://www.tensorflow.org/install/gpu

The existing documentation on how to setup TensorFlow with docker&GPU is great. Unfortunately it doesn't work with Kubernetes. This [Kubernetes Engine GPUs](https://cloud.google.com/kubernetes-engine/docs/how-to/gpus) guide suggest using "nvidia/cuda:10.0-runtime-ubuntu18.04" docker image. TensorFlow docs suggest "tensorflow/tensorflow:latest-gpu". 

Ideally, we could use them both as base images, but that's impossible. 

And of course this depends also on which VM image you're using for the k8s nodes.

It would be great if the docs provide some guidance on this setup. 

It would be really awesome if a docker image compatible with one of k8s VM images was available containing both the necessary NVidia support for a k8s node and complete tensorflow-gpu package environment.

**Comment by angersson** [comment]
Thanks for your suggestions. As far as I know, we don't have the resources to focus on Kubernetes-specific Dockerfiles right now (@lamberta or @dynamicwebpaige may be able to comment on whether or not there are plans for docs). I'd welcome a contribution to our dockerfiles repository, though.

**Comment by a6802739** [comment]
@angersson, could I have a try for this?

**Comment by bartoszkp** [comment]
@angersson Thanks for your reply. I did try really hard to construct a working image for more than a week, but it seems it requires some more expertise (or it's just me ;) ). I've tried both - starting from the "tensorflow/tensorflow:latest-gpu" and trying to include things missing from k8s point of view or starting from the k8s NVidia image and installing tensorflow and dependencies.

**Comment by angersson** [comment]
@a6802739 Sure, I'd be happy to review a PR.

@bartoszkp No worries -- Dockerfiles are notoriously hard to get working correctly.

**Comment by D1abloRUS** [comment]
@bartoszkp You can see an example of how to build under kubernetes https://github.com/puzl-ee/tensorflow

**Comment by mohantym** [comment]
Hi @bartoszkp ! Have you checked these threads on deploying Tensorflow model through serving on kubernetes? R [1](https://www.tensorflow.org/tfx/serving/serving_kubernetes) ,[2](https://aws.amazon.com/blogs/compute/tensorflow-serving-on-kubernetes-spot-instances/) .

**Comment by bartoszkp** [comment]
@mohantym Hello! Thanks for the comment. I've completely lost context on this one and do not have time to pursue it again. But hopefully this thread will be helpful for other visitors! Cheers! :-)

**Comment by mohantym** [comment]
Ok @bartoszkp ! Thanks for replying . Closing this issue for now. Please post on [TF serving](https://github.com/tensorflow/serving) repo  if you need further assistance.
