### ISSUE TITLE
DLL load failed with error code -1073741795, Win 7

### ISSUE THREAD

**Issue by nouranik** [tensorflow/tensorflow#26390]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): installation from https://www.tensorflow.org/install/pip
- TensorFlow version: 1.13
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: both pip, virtualenv
- Bazel version (if compiling from source):no
- GCC/Compiler version (if compiling from source): no
- CUDA/cuDNN version: tried with all CUDA8, CUDA7.5,CUDA9
- GPU model and memory:

**Describe the problem**
I tried different version of python and tensorflow and check the script for selecting CUDA version,  it has the same error. Also I installed airflow but desn't work!!!!!!
**Provide the exact sequence of commands / steps that you executed before running into the problem**
Traceback (most recent call last):
  File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_t
ensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_t
ensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_t
ensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", l
ine 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__
.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_t
ensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_t
ensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_t
ensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_t
ensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by nouranik** [comment]
I tried all of the tensorflow versions only 1.5 works and I need tensorflow 1.12 version.
regards,
Azadeh.

**Comment by jmatthewpeters** [comment]
I have the same problem.  Clean pip install of tensorflow on python 3.7
System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 7
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
TensorFlow installed from (source or binary): installation from https://www.tensorflow.org/install/pip
TensorFlow version: 1.13
Python version: 3.7.2
Installed using virtualenv? pip? conda?: pip
Bazel version (if compiling from source):no
GCC/Compiler version (if compiling from source): no
CUDA/cuDNN version: no CUDA
GPU model and memory:
Describe the problem

PS C:\Users\i102604> python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py
", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_in
ternal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_in
ternal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 24, in <
module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 4
9, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py
", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py
", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_in
ternal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_in
ternal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> quit()

**Comment by sumchat** [comment]
I got the same error even with CPU version tensorflow-1.9.0-cp36-cp36m-win_amd64.whl in windows 10.
So frustrating

**Comment by nouranik** [comment]
> I have the same problem. Clean pip install of tensorflow on python 3.7
> System information
> 
> OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 7
> Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
> TensorFlow installed from (source or binary): installation from https://www.tensorflow.org/install/pip
> TensorFlow version: 1.13
> Python version: 3.7.2
> Installed using virtualenv? pip? conda?: pip
> Bazel version (if compiling from source):no
> GCC/Compiler version (if compiling from source): no
> CUDA/cuDNN version: no CUDA
> GPU model and memory:
> Describe the problem
> 
> PS C:\Users\i102604> python
> Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import tensorflow as tf
> > > > Traceback (most recent call last):
> > > > File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py
> > > > ", line 58, in 
> > > > from tensorflow.python.pywrap_tensorflow_internal import *
> > > > File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_in
> > > > ternal.py", line 28, in 
> > > > _pywrap_tensorflow_internal = swig_import_helper()
> > > > File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_in
> > > > ternal.py", line 24, in swig_import_helper
> > > > _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> > > > File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
> > > > return load_dynamic(name, filename, file)
> > > > File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
> > > > return _load(spec)
> > > > ImportError: DLL load failed with error code -1073741795
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "", line 1, in 
> File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow__init__.py", line 24, in <
> module>
> from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
> File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python__init__.py", line 4
> 9, in 
> from tensorflow.python import pywrap_tensorflow
> File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py
> ", line 74, in 
> raise ImportError(msg)
> ImportError: Traceback (most recent call last):
> File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py
> ", line 58, in 
> from tensorflow.python.pywrap_tensorflow_internal import *
> File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_in
> ternal.py", line 28, in 
> _pywrap_tensorflow_internal = swig_import_helper()
> File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_in
> ternal.py", line 24, in swig_import_helper
> _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
> return load_dynamic(name, filename, file)
> File "C:\Users\i102604\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
> return _load(spec)
> ImportError: DLL load failed with error code -1073741795
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions. Include the entire stack trace
> above this error message when asking for help.
> 
> > > > quit()

in advance thanks for your help. but how come to install tensorflow on python 3.7 while it is mentioned on its official website compatible with python 3.6?
I have problem with cpu version!

**Comment by jvishnuvardhan** [comment]
Could you follow the instructions listed [here](https://github.com/tensorflow/tensorflow/issues/26451#issuecomment-471079686). @nouranik In future, please don't create duplicate issues #26451. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Comment by azhar2ds** [comment]
I have the same Issue.  

****
ImportError: DLL load failed with error code -1073741795
from tensorflow.python import pywrap_tensorflow
****

I have spend 60hours trying to import. But unfortunately no success.
I tried with python3.8 and python3.7 with tensorflow 1.5- 2.2 on pycharm and jupyter note book.. But no success.. 

Can someone  please help me

**Comment by azhar2ds** [comment]
Performed the steps 5 times again and again....But still same error message 1073741795

OS: win 7. 
64bit
1) Uninstalled tensorflow, python, anaconda, pycharm.
2) Reinstall python 3.7 and the anaconda and pycharm and tensorflow1.15.0 (tried all other versions too).
3) Install  Microsoft Visual C++ Redistributable (All Versions)
3) Then created new virtual environment and then activated. 
4) After that able to install tensorflow but 
5) Tried to import tensorflow. But unable to import. Gives same error 1073741795. 
Same error message in jupyter notebook, pycharm and in CLI.

Can somebody please give me solution to this

**Comment by jvishnuvardhan** [comment]
@azhar2ds Please create a new issue with the details of your system (fill the template). Thanks!

**Comment by suganth1997** [comment]
I solved it with the help of this repo https://github.com/fo40225/tensorflow-windows-wheel 

Seems like processors that don't support AVX instructions (old processors) won't work with official build of tensorflow.
