### ISSUE TITLE
[tensorflow.org] Devsite Code Container not working properly

### ISSUE THREAD

**Issue by Ayush517** [tensorflow/tensorflow#26399]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 2.0
- Doc Link: https://www.tensorflow.org/install

**Describe the documentation issue**
[Link](https://drive.google.com/file/d/10G-wS5A_QQ1ma7YRLdCpUVmist-J3t-N/view?usp=sharing)
As seen in the .gif file in the link uploaded, the code container for "Download a Package" section isn't working correctly. On decreasing window size, the code container initially gets cut into half without a scroll feature and then gets completely deleted from the webpage.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
Yes

**Comment by Ayush517** [comment]
@lamberta @ymodak Can anybody please redirect me to specific file that needs to be edited for fixing the issue. I tried finding it but couldn't find it.

**Comment by lamberta** [comment]
This appears to be fixed. Thanks
