### ISSUE TITLE
Unable to Build Android Example

### ISSUE THREAD

**Issue by astellato** [tensorflow/tensorflow#264]
Getting an error when building the Android example.  Have run into protobuf build issues on Mac OS X before, is this related?

Mac OS X - 10.11.1

Output:
$ bazel build //tensorflow/examples/android:tensorflow_demo -c opt --copt=-mfpu=neon --verbose_failures
INFO: Found 1 target...
INFO: From Compiling google/protobuf/src/google/protobuf/arena.cc:
src/main/tools/process-wrapper.c:119: execvp(argv[0], argv): No such file or directory
ERROR: /Users/astellato/Desktop/tensorflow/google/protobuf/BUILD:29:1: C++ compilation of rule '//google/protobuf:protobuf_lite' failed: false failed: error executing command 
  (cd /private/var/tmp/_bazel_astellato/e1414493f08fd994c717215d0d5d2bb5/tensorflow && \
  exec env - \
    INTERCEPT_LOCALLY_EXECUTABLE=1 \
    PATH=/Users/astellato/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/share/npm/bin:/Users/astellato/Development/Android/sdk/platform-tools:/Users/astellato/Development/Android/sdk/tools:/Users/astellato/Development/Android/ndk/android-ndk-r10d:/Users/astellato/bin \
    TMPDIR=/var/folders/3z/18r1p7zn1x74lqpkv377thpc0000gn/T/ \
  /bin/false '-mfpu=neon' -iquote . -iquote bazel-out/android-stub_armeabi-v7a-opt/genfiles -isystem google/protobuf/src -isystem bazel-out/android-stub_armeabi-v7a-opt/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare '-Wno-error=unused-function' '-frandom-seed=bazel-out/android-stub_armeabi-v7a-opt/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/arena.pic.o' -MD -MF bazel-out/android-stub_armeabi-v7a-opt/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/arena.pic.d -fPIC -c google/protobuf/src/google/protobuf/arena.cc -o bazel-out/android-stub_armeabi-v7a-opt/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/arena.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: false failed: error executing command 
  (cd /private/var/tmp/_bazel_astellato/e1414493f08fd994c717215d0d5d2bb5/tensorflow && \
  exec env - \
    INTERCEPT_LOCALLY_EXECUTABLE=1 \
    PATH=/Users/astellato/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/share/npm/bin:/Users/astellato/Development/Android/sdk/platform-tools:/Users/astellato/Development/Android/sdk/tools:/Users/astellato/Development/Android/ndk/android-ndk-r10d:/Users/astellato/bin \
    TMPDIR=/var/folders/3z/18r1p7zn1x74lqpkv377thpc0000gn/T/ \
  /bin/false '-mfpu=neon' -iquote . -iquote bazel-out/android-stub_armeabi-v7a-opt/genfiles -isystem google/protobuf/src -isystem bazel-out/android-stub_armeabi-v7a-opt/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare '-Wno-error=unused-function' '-frandom-seed=bazel-out/android-stub_armeabi-v7a-opt/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/arena.pic.o' -MD -MF bazel-out/android-stub_armeabi-v7a-opt/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/arena.pic.d -fPIC -c google/protobuf/src/google/protobuf/arena.cc -o bazel-out/android-stub_armeabi-v7a-opt/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/arena.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 4.001s, Critical Path: 0.18s

**Comment by andrewharp** [comment]
Hi, what is the content of your google/protobuf directory? If empty, try git cloning the repo with the --recursive flag to grab all of the Tensorflow submodules.

**Comment by astellato** [comment]
Submodules were good to go, but the NDK directory was commented in the build file.
