### ISSUE TITLE
build error with OpenMPI

### ISSUE THREAD

**Issue by steige2** [tensorflow/tensorflow#26403]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux xxxx 3.10.0-862.6.3.el7.x86_64 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 0.13 (downloaded 6/Mar/2019)
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source): 4.8.5 
- CUDA/cuDNN version: 10.0/7.4.2
- GPU model and memory: NVIDIA V100, P100 both 16GB

**Describe the problem**  Build fails with MPI support enabled

**Provide the exact sequence of commands / steps that you executed before running into the problem**
$ bazel build --config=opt --config=noaws --config=nogcp --config=nohdfs --config=noignite --config=nokafka --config=cuda //tensorflow/tools/pip_package:build_pip_package
.....
3 errors detected in the compilation of "/tmp/tmpxft_000633d8_00000000-7_ring.cu.compute_60.cpp1.ii".
ERROR: /N/dc2/projects/osg-storage/tensorflow/tensorflow/contrib/mpi_collectives/BUILD:40:1: output 'tensorflow/contrib/mpi_collectives/_objs/python/ops/_mpi_ops_gpu/ring.cu.pic.o' was not created
ERROR: /N/dc2/projects/osg-storage/tensorflow/tensorflow/contrib/mpi_collectives/BUILD:40:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

It seems a patch for this was described here: https://github.com/tensorflow/tensorflow/issues/17437 about a year ago, it would be very useful if this could be included in the current release.

**Comment by byronyi** [comment]
As in TF 2.0, all contrib projects including the MPI support will be removed from the TF core, which means this patch will not be merged here.

MPI and MPI collectives will be migrated to tensorflow/networking. Although the migration process is still undergoing, we do not have sufficient support from the community to the MPI collectives. You are encouraged to help :)

**Comment by steige2** [comment]
Thanks for the info, I found the "enable MPI support" configuration option suggestive. I'll remove it from my configuration files.

**Comment by B3N50N** [comment]
@steige2 can you explain more detail for how you fix this error?

**Comment by steige2** [comment]
I accepted the default to this configuration question:
Do you wish to build TensorFlow with MPI support? [y/N]
that is, solved the problem by NOT building with MPI support.
