### ISSUE TITLE
libpthread.so error with android demo

### ISSUE THREAD

**Issue by lizzyAtkinson1989** [tensorflow/tensorflow#2640]
Operating System: OSX Yosemite 10.10.5

Followed the [virtualenv installation instructions](https://github.com/hamidb/tensorflow/blob/api20/tensorflow/g3doc/get_started/os_setup.md#virtualenv-installation-virtualenv_install)
 
r11 release

I followed [these](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) instructions to run the android demo

Have tried Bazel releases 0.2.3, 0.2.2, 0.2.1 and 0.1.4
Have the latest sdk and ndk

Have tried with all the sdk and ndk info uncommented in Workspace and with the ndk commented out

I get as far as 
`$ bazel build //tensorflow/examples/android:tensorflow_demo`

and I get the following errors:

`ERROR: /Users/lizzya/Documents/tensorflow-master/tensorflow/examples/android/BUILD:41:1: Linking of rule '//tensorflow/examples/android:libpthread.so' failed: false failed: error executing command 
  (cd /private/var/tmp/_bazel_lizzya/3ad59cfd62098d64f5760266c321e9a2/tensorflow-master && \
  exec env - \
  /bin/false -o bazel-out/android-stub_armeabi-v7a-fastbuild/bin/tensorflow/examples/android/libpthread.so -shared -Wl,-S -Wl,@bazel-out/android-stub_armeabi-v7a-fastbuild/bin/tensorflow/examples/android/libpthread.so-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: false failed: error executing command 
  (cd /private/var/tmp/_bazel_lizzya/3ad59cfd62098d64f5760266c321e9a2/tensorflow-master && \
  exec env - \
  /bin/false -o bazel-out/android-stub_armeabi-v7a-fastbuild/bin/tensorflow/examples/android/libpthread.so -shared -Wl,-S -Wl,@bazel-out/android-stub_armeabi-v7a-fastbuild/bin/tensorflow/examples/android/libpthread.so-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
process-wrapper: execvp("/bin/false", ...): No such file or directory
Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 1.509s, Critical Path: 0.16s

`

**Comment by aselle** [comment]
I'm not sure what's going on there, but it looks like /bin/false is failing with no such file directory on execvp. That could be because Mac OS has /bin/false in /usr/bin/false instead. Could you try ln -s /usr/bin/false to /bin/false and see if it gets any further?

**Comment by andrewharp** [comment]
Bazel 0.2.3 doesn't support NDK r11. Support was added in commit https://github.com/bazelbuild/bazel/commit/abdaff492440b373bacd016d772ef73611a27901, which will probably be in 0.2.4. Until then I'd suggest using r10e.

As far as libpthread.so in particular, this file is actually not even necessary for the android build. It's just that protobuf assumes it will be there, so I had to add a workaround to tensorflow/examples/android/BUILD. The newer version of the protobuf library is more intelligent about adding the option, but we haven't upgraded TF to it yet.

You can try editing protobuf/BUILD and remove the pthreads entry from LINK_OPTS, and also remove all references to libpthread from tensorflow/examples/android/BUILD.

Hopefully switching to  NDK r10e and trying to excise libpthread.so from the build will solve your problem, but if it doesn't please update with the new error.

**Comment by andrewharp** [comment]
For reference you can find links to download NDK r10e here: https://github.com/tensorflow/tensorflow/issues/1468

**Comment by lizzyAtkinson1989** [comment]
Thank you, this solved my issue.
