### ISSUE TITLE
[TF 2.0] tf.summary built-in support in Estimator

### ISSUE THREAD

**Issue by nfelt** [tensorflow/tensorflow#26408]
This feature request tracks making the Estimator summary-writing logic provide built-in support for the TF 2.0 tf.summary.scalar(), image(), etc. ops.

Background: the TF 1.x summary ops are supported automatically in Estimator via use of the `tf.estimator.RunConfig` option for `save_summary_steps`, which uses `tf.estimator.SummarySaverHook` under the hood. This means that Estimator model code can invoke `tf.summary.scalar()` and it will Just Work - the framework takes care of collecting the summary at the correct step or time interval and writing it out to the model output directory.

Currently, to use TF 2.0 summary ops, one needs to set up the summary writer, step tracking, etc. logic by hand.

**Comment by LoicDagnas** [comment]
Hello @nfelt, 
Is it still the case in the freshly released TensorFlow 2.0?
If yes, do you have an example of a minimal estimator (or link to documentation) which saves custom scalar summary?

Thanks in advance

**Comment by kumariko** [comment]
@nfelt We are checking to see if you still need help on this issue . could you please check with latest released `TF2.7` and let us know if the issue still persists in newer versions. Thanks!

**Comment by nfelt** [comment]
@kumariko this is more of a feature request than a bug, so yes it will persist in all versions unless it's implemented.
