### ISSUE TITLE
[TF 2.0] summary API migration paths

### ISSUE THREAD

**Issue by nfelt** [tensorflow/tensorflow#26405]
This feature request tracks adding and improving migration paths in tf_upgrade_v2 to handle the various summary APIs.

The goal state is:
1) 1.x tf.summary migrated to tf.compat.v1.summary by default (done)
2) 1.x tf.summary migrated to tf.compat.v2.summary where possible to do correctly (not done, may not be feasible)
3) 1.x tf.contrib.summary migrated to tf.compat.v2.summary with best-effort correctness (partly done)

For (2) it's not possible to do this correctly in all cases because the summary APIs depend on non-local context in different ways (e.g. file writer creation works differently) and return different results (1.x returns a Summary protocol buffer, 2.x a boolean). It might be worth seeing if we can add an option to the upgrade script to indicate a preference for the conservative approach (stick with tf.compat.v1) or the more aggressive upgrade (migrate to tf.compat.v2, but more likely to be broken).

For (3) we can't migrate to compat.v1 because contrib is not exposed in v1, so migrating to V2 is the only path forwards. Migration rules here are only partially implemented (for `scalar`, `audio`, `image`, and `histogram`). We still need rules for migrating the actual writer and recording control symbols.

Tracked internally at b/124529441.

**Comment by Ayush517** [comment]
@nfelt Can you please help me understanding this issue a little better. So, basically the main thing we need to do here is changing all occurrences of tf.summary with tf.compat.v2.summary and tf.contrib.summary migrated with tf.compat.v2.summary. Did I understanding this correctly?

**Comment by nfelt** [comment]
So this issue is for tracking making the migration tooling and docs better, not for actually documenting the migration paths in the issue itself.

But the short version is that if you're using tf.contrib.summary, the new TF 2.0 API is pretty similar except that recording is on by default so you don't need always_record_summaries() any more.  If you're using tf.summary, the calls to `scalar()`, `histogram()`, etc. look the same, but the file writer works quite differently.  There's a brief overview of the new API at the bottom of this page on effective TF 2.0: https://www.tensorflow.org/alpha/guide/effective_tf2#use_tfmetrics_to_aggregate_data_and_tfsummary_to_log_it

As I make the migration tooling better and add documentation, I'll update this issue.

**Comment by Ayush517** [comment]
@nfelt Is there something I can help with?

**Comment by nfelt** [comment]
This is essentially done aside from getting better docs, which https://github.com/tensorflow/tensorboard/pull/2514 should address.

**Comment by kumariko** [comment]
@nfelt Could you please let us know if we can close the issue with the merged [PR](https://github.com/tensorflow/tensorboard/pull/2514) ? Thanks!

**Comment by nfelt** [comment]
We can consider this closed.
