### ISSUE TITLE
Add Minor Versions for cuDNN & CUDA in Tested build configurations tables

### ISSUE THREAD

**Issue by CA4GitHub** [tensorflow/tensorflow#26410]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.12
- Doc Link: https://www.tensorflow.org/install/source#tested_build_configurations

**Describe the documentation issue**
The tested build configurations table does not supply adequate information for the user since it does not provide minor versions for the cuDNN and CUDA tested in the build.  Please add this information.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by ymodak** [comment]
Tested config for TF 1.12 is `CUDA 9.0` and `cuDNN 7.2.1`
https://github.com/tensorflow/tensorflow/blob/5b900cfe4b3b848f577315a0dde09a729f770e95/tensorflow/tools/docker/Dockerfile.devel-gpu#L16
TF 1.12 and below versions are obsolete. `CUDA` and `cuDNN` minor versions are provided for TF 1.13.1 and above versions.
