### ISSUE TITLE
Segmentation fault when loading SSD-MobileNetV1 into TF Lite calibration tool

### ISSUE THREAD

**Issue by ajarthurs** [tensorflow/tensorflow#26412]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Arch Linux (4.20.1-arch1-1-ARCH SMP PREEMPT)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary):
Source
- TensorFlow version (use command below):
TensorFlow Git commit ID: 12606ff846566dd842444f27f7fed4f911a58580
TensorFlow Models Git commit ID: [`338088d`](https://github.com/tensorflow/models/commit/338088df1782c0bf2dc105170730f2230edf2df7)
- Python version:
3.7.2
- Bazel version (if compiling from source):
0.21.0-1
- GCC/Compiler version (if compiling from source):
8.2.1
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
In Python, calling `tensorflow.lite.python.optimize.calibrator.Calibrator(float32_tflite_ssd_mobilenetv1_model_contents)` leads to a segmentation-fault.

**Describe the expected behavior**
No segmentation-fault when instantiating `Calibrator` with the floating-point SSD-MobileNetV1 TF Lite model.

**Code to reproduce the issue**

```bash
$ wget  http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz
$ tar vxf ssd_mobilenet_v1_coco_2018_01_28.tar.gz
$ cd ssd_mobilenet_v1_coco_2018_01_28
<Configure paths in pipeline.config to point to COCO dataset and label-map (see tensorflow/models/research/object_detection/data/mscoco_label_map.pbtxt)>
$ python <Path to workspace>/tensorflow/models/research/object_detection/export_tflite_ssd_graph.py --pipeline_config_path=pipeline.config --trained_checkpoint_prefix=model.ckpt --output_directory=. --add_postprocessing
$ toco --graph_def_file=tflite_graph.pb --output_file=float32.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --inference_type=FLOAT --mean_values=128 --std_dev_values=128 --change_concat_input_ranges=false --allow_custom_ops
```
```python
# load_model_into_calibrator.py
from tensorflow.lite.python.optimize import calibrator

with open('float32.tflite', 'rb') as f:
  quantizer = calibrator.Calibrator(f.read())
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

`gdb` full backtrace attached.
[gdb-backtrace.txt](https://github.com/tensorflow/tensorflow/files/2938277/gdb-backtrace.txt)

**Comment by ajarthurs** [comment]
The custom post-processor appended to the said TF Lite model's outputs is causing the segmentation fault. Excluding it as demonstrated below works. But, I would like to know how or if custom operators are supported by the TF Lite calibration tool.

```bash
$ toco --graph_def_file=tflite_graph.pb --output_file=float32.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays='raw_outputs/box_encodings','raw_outputs/class_predictions','anchors' --inference_type=FLOAT --mean_values=128 --std_dev_values=128 --change_concat_input_ranges=false
$ python load_model_into_calibrator.py
```

**Comment by shashishekhar** [comment]
@ajarthurs: Right now the calibrator does not support custom ops, which detection_postprocess is. However it should not crash, but rather give an error message.
@jianlijianli : This is related to custom op support, for this bug we at least need to report an error.

**Comment by lissyx** [comment]
> @ajarthurs: Right now the calibrator does not support custom ops, which detection_postprocess is. However it should not crash, but rather give an error message.
> @jianlijianli : This is related to custom op support, for this bug we at least need to report an error.

I can confirm the crash. We are running into the same on DeepSpeech model, and the crash happens at https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/lite/tools/optimize/calibration/logging_op_resolver.cc#L30

This is because https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/lite/tools/optimize/calibration/logging_op_resolver.cc#L27-L28 `base_resolver` cannot find the op because `base_resolver.FindOp(op_and_version.first, op_and_version.second);` is indeed `TfLiteRegistration* BuiltinOpResolver::FindOp(tflite::BuiltinOperator op, int version)`.

A quick fix is checking for `base_registration` against `nullptr` and continue: it will `RuntimeError` at least.

**Comment by lissyx** [comment]
Indeed, custom ops are taken care of since r1.15, so maybe this should just be closed: that ship has sailed ...

**Comment by ajarthurs** [comment]
Awhile ago, I settled for removing `detection_postprocess` from the rest of the graph. Wasn't sure if you guys were resolving the seg-fault with an error message, but it sounds like this issue has gone stale. So, I agree; let's close this.
