### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.lite' has no attribute 'Optimize' version 1.13

### ISSUE THREAD

**Issue by jyang356** [tensorflow/tensorflow#26413]
following the Post-training quantization guide,
```
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
AttributeError: module 'tensorflow._api.v1.lite' has no attribute 'Optimize'
```
i want to convert the mnist model, full code here
```
from __future__ import absolute_import, division, print_function
import os
import tensorflow as tf
from tensorflow import keras

tf.__version__

(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()

train_labels = train_labels[:1000]
test_labels = test_labels[:1000]

train_images = train_images[:1000].reshape(-1, 28 * 28) / 255.0
test_images = test_images[:1000].reshape(-1, 28 * 28) / 255.0

# Returns a short sequential model
def create_model():
  model = tf.keras.models.Sequential([
    keras.layers.Dense(512, activation=tf.keras.activations.relu, input_shape=(784,)),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(10, activation=tf.keras.activations.softmax)
  ])
  
  model.compile(optimizer=tf.keras.optimizers.Adam(),
                loss=tf.keras.losses.sparse_categorical_crossentropy,
                metrics=['accuracy'])
  
  return model


# Create a basic model instance
model = create_model()
model.fit(train_images, train_labels, epochs=5)
model.summary()
model.save('my_mnist_v2.h5')

converter = tf.lite.TFLiteConverter.from_keras_model_file("my_mnist_v2.h5")
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
tflite_quant_model = converter.convert()
```
tf version 1.13

**Comment by sunejas** [comment]
Hello @jyang356 ,
Iam facing the same error message. Were you able to resolve it? kindly let me know the solution.

**Comment by samsterckval** [comment]
Same problem, following

**Comment by anjelo95** [comment]
same problem, following

**Comment by sunejas** [comment]
I wasnt able to solve the above problem, but proceeded with following code to save quantized model:

```
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
tflite_model = converter.convert()
open("model.tflite", "wb").write(tflite_model)
#converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.post_training_quantize=True
tflite_quantized_model=converter.convert()
open("quantized_model.tflite", "wb").write(tflite_quantized_model)
```

**Comment by anjelo95** [comment]
thank you, your solution is valid also with  : 
`tf.lite.TFLiteConverter.from_keras_model_file(saved_model_dir)` instead of `converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)`

**Comment by anonym24** [comment]
@sunejas I did that but now I get this error:

`"invalid shape '{1}'.".format(_tensor_name(tensor), shape_list))
ValueError: None is only supported in the 1st dimension. Tensor 'image_tensor' has invalid shape '[None, None, None, 3]'.`

**Comment by 2h4dl** [comment]
Thank you @sunejas, I refered to the code you post. Just add one line and make it.

```
    converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_path)
   
    # added code to convert model to a quantized tflite format.
    converter.post_training_quantize = True

    tflite_model = converter.convert()
    open("converted_model.tflite", "wb").write(tflite_model)
    print("convert model to tflite format done.")
```

**Comment by ignvinay** [comment]
I tried this method of calling post_training_quantize=True.
But when i call interpreter, the inference code of Tensorflow and Tensorflow lite does not match.
Is there any setting to be done in Interepreter ?

graph_def_file = "C:/Users/GF63/Downloads/tf2_tflite_issues/mobilenet_v1_1.0_224/frozen_graph.pb"
input_arrays = ["input"]
output_arrays = ["MobilenetV1/Predictions/Softmax"]
converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
# This is to be used for post quantization
#converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
#converter.optimizations = [tf.lite.constants.QUANTIZED_UINT8]

# Integer quantization.
converter.post_training_quantize=True
#converter.inference_type = tf.lite.constants.QUANTIZED_UINT8
#converter.quantized_input_stats = {input_arrays[0] : (0., 1.)}

tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
interpreter = tf.lite.Interpreter(model_path="converted_model.tflite")
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
input_shape = input_details[0]['shape']

input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

This output_data compared against Tensorflow inference are different.
Any ideas ?

**Comment by 2h4dl** [comment]
> I tried this method of calling post_training_quantize=True.
> But when i call interpreter, the inference code of Tensorflow and Tensorflow lite does not match.
> Is there any setting to be done in Interepreter ?
> 
> ```
> graph_def_file = "C:/Users/GF63/Downloads/tf2_tflite_issues/mobilenet_v1_1.0_224/frozen_graph.pb"
> input_arrays = ["input"]
> output_arrays = ["MobilenetV1/Predictions/Softmax"]
> converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
> 
> converter.post_training_quantize=True
> 
> tflite_model = converter.convert()
> open("converted_model.tflite", "wb").write(tflite_model)
> interpreter = tf.lite.Interpreter(model_path="converted_model.tflite")
> interpreter.allocate_tensors()
> input_details = interpreter.get_input_details()
> output_details = interpreter.get_output_details()
> input_shape = input_details[0]['shape']
> 
> input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
> interpreter.set_tensor(input_details[0]['index'], input_data)
> interpreter.invoke()
> output_data = interpreter.get_tensor(output_details[0]['index'])
> print(output_data)
> ```
> 
> This output_data compared against Tensorflow inference are different.
> Any ideas ?

I found you use a random sample to forward, maybe you need feed  the same data to both format of models.

**Comment by ignvinay** [comment]
Yes, I am feeding same data to both. I believe random does not matter , as long as i am feeding same data to tflite and tensorflow.

**Comment by user-vm** [comment]
@jyang356 's original error was because the Optimizers attribute was added in 1.13.1, which I think was available at the time of OP's post.

**Comment by jyang356** [comment]
Yes, i checked the older version and found one that did the same thing but with a different name/function. 

Sorry, i was very busy at that time and completely forgot it. i can't find my source code now, probably deleted, because it's just the "hello world" code from git.

**Comment by ignvinay** [comment]
So is this bug from 1.13 ?
or is there any correction/workaround possibility to code ?

**Comment by user-vm** [comment]
> So is this bug from 1.13 ?
> or is there any correction/workaround possibility to code ?

How different are the outputs? I'm getting the same difference between pb and quantized in both 1.13.0rc2 and 1.14.0, so it doesn't seem to be 1.13-specific. Some difference is to be expected. I think the 'scale' attribute in the UINT8 tensors (the convolution weights) more or less give an idea about the magnitude of the error you can expect.
