### ISSUE TITLE
How to install tensorflow2.0 in cuda9?

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/tensorflow#26418]
Any way to specific a cuda version with tensorflow2.0 alpha version? To  reinstall cuda is really risky, cause there are many other projects based on caffe which does not support an advanced cuda

**Comment by Ayush517** [comment]
@jinfagang Is there any version of Tensorflow already installed on your system?

**Comment by jvishnuvardhan** [comment]
@jinfagang TF2.0 was built with CUDA10.0. But, I think you can use CUDA9.0 with TF2.0. You need to make sure that the CUDA and cuDNN are referenced correctly. Thanks!

**Comment by meteorcloudy** [comment]
@jvishnuvardhan Sorry, I'm not the correct person to be assigned

**Comment by jvishnuvardhan** [comment]
@jinfagang You need to build TF2.0 from source, then you can use CUDA 9.0 which you already have it. Please don't use binaries as they are built with CUDA10.0 and some of the dependencies will be looking for CUDA 10.0 paths. Please let us know how it progresses. Thanks!

**Comment by jvishnuvardhan** [comment]
@jinfagang Please check the resource [here](https://www.tensorflow.org/install/source). Thanks!

**Comment by jinfagang** [comment]
@jviereck Thanks u, I never built tensorflow successfully yet, most reason is that it downloads too many dependencies and some using google which blocked in China................ I meant if there any wheel just like pytorch does provide difference version built on cuda 9 with cudnn 7

**Comment by jvishnuvardhan** [comment]
@jinfagang Do you have access to https://github.com/tensorflow/tensorflow/tags and https://pypi.org/project/tensorflow-gpu/? You could download from those locations. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Comment by Rhyssiyan** [comment]
I don't find the tf2.0 package built with cuda9.0 from https://github.com/tensorflow/tensorflow/tags and https://pypi.org/project/tensorflow-gpu/. And it's troublesome for me to install tf by building. Finally, I give up and adopt the shell from https://github.com/phohenecker/switch-cuda to switch cuda version as a temporary solution.

**Comment by SmileTM** [comment]
@jvishnuvardhan you are right.  I have succeeded to build TF2.0 with CUDA9 and cudnn6.7  from source. Now it's working grateful. Thanks.

**Comment by jvishnuvardhan** [comment]
> as a temporary solution.



> I don't find the tf2.0 package built with cuda9.0 from https://github.com/tensorflow/tensorflow/tags and https://pypi.org/project/tensorflow-gpu/. And it's troublesome for me to install tf by building. Finally, I give up and adopt the shell from https://github.com/phohenecker/switch-cuda to switch cuda version as a temporary solution.

Tensorflow2.0 officially built with cuda10.0. There are community built binaries are there but not sure whether they have anything you are looking. Please [check some here](https://github.com/tensorflow/tensorflow/issues/28022#issuecomment-485357906). Thanks

**Comment by sudonto** [comment]
hi @SmileTM will you share the binary for us? thanks.

**Comment by SmileTM** [comment]
> hi @SmileTM will you share the binary for us? thanks.

@sudonto  ，hi
This binary may not be useful to you , because it was modified based on my configuration.
if you need the binary, you must bazel the  binary  in your configuration.
you can refer [my method](https://s-tm.cn/2019/09/28/%E9%82%A3%E4%BA%9B%E5%B9%B4%E8%B5%B0%E8%BF%87%E7%9A%84%E5%9D%91-tf2-gpu%E5%AE%89%E8%A3%85/).

**Comment by bestpredicts** [comment]
> > hi @SmileTM will you share the binary for us? thanks.
> 
> @sudonto ，hi
> This binary may not be useful to you , because it was modified based on my configuration.
> if you need the binary, you must bazel the binary in your configuration.
> you can refer [my method](https://s-tm.cn/2019/09/28/%E9%82%A3%E4%BA%9B%E5%B9%B4%E8%B5%B0%E8%BF%87%E7%9A%84%E5%9D%91-tf2-gpu%E5%AE%89%E8%A3%85/).

hello,  I meet some probleam by your blog,  can  I add  your . qq .  or can  u share the tensorflow 2.0 which build by cuda9.0?

**Comment by SmileTM** [comment]
> > > hi @SmileTM will you share the binary for us? thanks.
> > 
> > 
> > @sudonto ，hi
> > This binary may not be useful to you , because it was modified based on my configuration.
> > if you need the binary, you must bazel the binary in your configuration.
> > you can refer [my method](https://s-tm.cn/2019/09/28/%E9%82%A3%E4%BA%9B%E5%B9%B4%E8%B5%B0%E8%BF%87%E7%9A%84%E5%9D%91-tf2-gpu%E5%AE%89%E8%A3%85/).
> 
> hello, I meet some probleam by your blog, can I add your . qq . or can u share the tensorflow 2.0 which build by cuda9.0?


我不确定 是否能给您 提供帮助。
qq 183637818

**Comment by SmileTM** [comment]
> hi @SmileTM will you share the binary for us? thanks.
The binary in the here. But i am not sure ,it works well in your machine.
https://github.com/SmileTM/Tensorflow2.0-GPU-CUDA9.0
