### ISSUE TITLE
GPU placement of tf.nn.conv2d during tf.data.Dataset.map call causes UnimplementedError (NHWC)

### ISSUE THREAD

**Issue by sbrodehl** [tensorflow/tensorflow#26411]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Linux 4.20.13-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 27 19:10:28 UTC 2019 x86_64 GNU/Linux`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): `community python-tensorflow-opt-cuda`
- TensorFlow version (use command below): `1.13.1`
- Python version: `3.7.2`
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: `10.1 / 7.5`
- GPU model and memory: `Geforce GTX 1080 Ti 11GB`

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Evaluation of `tf.nn.conv2d` in a `tf.data.Dataset.map` call fails during `Session.run()` call of `tf.data.iterator.get_next()` with error:
```python
tensorflow.python.framework.errors_impl.UnimplementedError: Generic conv implementation only supports NHWC tensor format for now.
```
See the full error log and the attached code below for the full example.

It seems that the graph is successfully created, but the evaluation of the `tf.nn.conv2d` call (which is implicitly placed on the GPU) is not possible.
This is somehow related to the fact that this `tf.nn.conv2d` call is wrapped in a `tf.data.Dataset.map` call.
Setting `data_format="NHWC"` or `use_cudnn_on_gpu=False` procudes the same error.

**Describe the expected behavior**
`tf.nn.conv2d` should be evaluated, which is done iff the convolution is explicitly placed on the CPU (e.g. `with tf.device('/cpu:0'):` or `CUDA_VISIBLE_DEVICES=""`).

**Code to reproduce the issue**
```python
import tensorflow as tf


class IteratorInitializerHook(tf.train.SessionRunHook):
    """Hook to initialise data iterator after Session is created."""

    def __init__(self, func=None):
        super(IteratorInitializerHook, self).__init__()
        self.iterator_initializer_func = func

    def after_create_session(self, session, coord):
        """Initialise the iterator after the session has been created."""
        self.iterator_initializer_func(session)


if __name__ == '__main__':

    def apply_kernel(tensor, kernel=tf.random_normal([3, 3])):
        t = tf.expand_dims(tensor, 0)
        t = tf.expand_dims(t, -1)
        k = tf.expand_dims(kernel, -1)
        k = tf.expand_dims(k, -1)

        # TODO the following line fails during Session.run
        #  call of tf.data.Iterator.get_next() (last line in this file)
        tf_conv = tf.nn.conv2d(t, k, [1, 1, 1, 1], "SAME")
        return tf.squeeze(tf_conv)

    def do_some_things(x, y):
        x = apply_kernel(x)
        return x, y

    n, image_shape = 100, [256, 256]

    ds = tf.data.Dataset.from_tensor_slices((
        tf.random_uniform([n] + image_shape), tf.random_uniform([n])
    ))
    ds = ds.map(do_some_things)
    iterator = tf.data.Iterator.from_structure(ds.output_types, ds.output_shapes)
    data = iterator.get_next()
    ds_init_op = iterator.make_initializer(ds)

    with tf.train.SingularMonitoredSession(
            hooks=[IteratorInitializerHook(lambda s: s.run(ds_init_op))],
            config=tf.ConfigProto(log_device_placement=True)
    ) as sess:
        _ = sess.run(data)
```

**Other info / logs**
Here is the full error log, including device placements.
[tf-conv-NHWC-issue.log](https://github.com/tensorflow/tensorflow/files/2938294/tf-conv-NHWC-issue.log)

Here is a zipped version of the python example
[tf-conv-NHWC-issue.py.zip](https://github.com/tensorflow/tensorflow/files/2938289/tf-conv-NHWC-issue.py.zip)

Not sure if this is important, but it seems that all tensorflow ops from the function which is called by `tf.data.Dataset.map` are not showing up in the device placement logs.

**Comment by mrry** [comment]
I think the problem here is a bug in an optimization pass that's causing the `Dataset.map()`, which should be placed on **CPU**, to be rewritten to use a version of `tf.nn.conv2d()` that is only available on GPU.

Can you try disabling the layout optimizer as follows and let us know if this works?

```python
# ...
config = tf.ConfigProto(log_device_placement=True)
config.graph_options.rewrite_options.layout_optimizer = 2  # RewriterConfig.OFF

    with tf.train.SingularMonitoredSession(
            hooks=[IteratorInitializerHook(lambda s: s.run(ds_init_op))],
            config=config
    ) as sess:
        _ = sess.run(data)
```

**Comment by sbrodehl** [comment]
Thanks for the fast reply @mrry!

Indeed, the snippet you posted works fine, whichout any errors!

**Comment by sbrodehl** [comment]
Added the original logfile and example script in the top post

>Here is the full error log, including device placements.
> [tf-conv-NHWC-issue.log](https://github.com/tensorflow/tensorflow/files/2938294/tf-conv-NHWC-issue.log)
>
> Here is a zipped version of the python example
> [tf-conv-NHWC-issue.py.zip](https://github.com/tensorflow/tensorflow/files/2938289/tf-conv-NHWC-issue.py.zip)

**Comment by mrry** [comment]
Thanks for confirming!

@ezhulenev It looks like one of the function optimization passes in Grappler is applying the layout optimizer under the assumption that all devices will be available inside the function. Is there a way to inhibit this optimization, e.g. when the function is named in an attr that's passed to a CPU-only op? (At least for tf.data, there's another chance to run optimizers in the TFDataMetaOptimizer, /cc @rachellim.)

**Comment by ezhulenev** [comment]
I think it's the problem in layout optimizer, function body node does not have assigned devices, but layout optimizer "approximates" the placer with https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/optimizers/layout_optimizer.cc#L574 and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/costs/virtual_placer.cc#L82.

Current plan is to remove function optimization from Grappler in it's current form, this problem should go away after that. But that's at few weeks away.

/cc @rmlarsen @andyly

**Comment by ezhulenev** [comment]
FYI internal issue for that is b/126811947

**Comment by sbrodehl** [comment]
Is there anything I can do to help resolve this issue?

**Comment by ezhulenev** [comment]
Can you try to explicitly set device to CPU inside function body. I think that might work as well.

**Comment by sbrodehl** [comment]
Yes, when the device is explicitly set to `tf.device('/cpu:0')` everything works as expected.

**Comment by omoindrot** [comment]
@mrry : is there any plan to have GPU support for `tf.data.Dataset.map`?

An example use case would be to extract frozen features from a pretrained network while loading images, then caching the dataset to avoid computing again those features.

I've asked the same question [here](https://github.com/tensorflow/hub/issues/140#issuecomment-524255004), when I got this error trying to run a TF Hub module in `tf.data.Dataset.map`:
>`NotFoundError: No registered 'MapDataset' OpKernel for GPU devices compatible with node {{node MapDataset}}`

**Comment by aligokalppeker** [comment]
> Can you try to explicitly set device to CPU inside function body. I think that might work as well.

That's a quite precise solution which handles my problem right away. I have used tf.device("/cpu:0") in the outer portions of the body but the layout optimization error was still given. But when placed in the body itself, the problem has got away.

Thanks...

**Comment by markostam** [comment]
Setting to `tf.device('/cpu:0')` worked for me as well on 1.15.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by sbrodehl** [comment]
I think the issue is solved in 2.x, maybe @ezhulenev can confirm that internal issue b/126811947 is closed?

**Comment by aligokalppeker** [comment]
I don't use this function in my tensorflow environment. You can confirm it as resolved.

**Comment by sachinprasadhs** [comment]
@sbrodehl , Yes the internal issue is closed, you can go ahead and close this issue, if you don't have any further questions. Thanks!

**Comment by sbrodehl** [comment]
Thank you very much for the confirmation!
