### ISSUE TITLE
TF Tutorial refers to cudnn-7.5-linux-x64-v4.tgz

### ISSUE THREAD

**Issue by viksit** [tensorflow/tensorflow#2642]
In the GPU installation section.

Except, all the obvious sources on the [nvidia website](https://developer.nvidia.com/rdp/cudnn-download) only seem to have cudnn-7.0-linux-x64-v4.tgz. 

Is this a typo, or a reference to a now unavailable resource?

**Comment by vrv** [comment]
cudnn is not publicly available, you must register with nvidia to get them.

The notes say

"Uncompress and copy the cuDNN files into the toolkit directory. Assuming the toolkit is installed in /usr/local/cuda, run the following commands (edited to reflect the cuDNN version you downloaded):"

which should illustrate that you might need to edit the version.

**Comment by viksit** [comment]
Ah the reason I asked is that I'm facing two issues. 

- the pip installed version of tensorflow relies on cuda7.5 and cudnn4.
- however, configuring tensorflow with 7.5 and cudnn4 before compiling tensorflow serving fails. It succeeds however with cuda7.0 and cudnn4.

I was wondering if there exists a version of that file as referenced in the tutorial that may solve the problem.

**Comment by kmmbvnr** [comment]
@vrv after the registration, there is no cudnn4 for cuda7.5 on the nvidia cuddn downloads page.
![cudnn download nvidia developer](https://cloud.githubusercontent.com/assets/282529/18237095/3890434e-734f-11e6-993d-4b4e12c3f430.png)
