### ISSUE TITLE
How to predict images using trained mobilenet model?

### ISSUE THREAD

**Issue by harshita-pal** [tensorflow/tensorflow#26425]
Hi ,I somehow managed to train my mobile net model but i want to know with the model trained, how can i  use it to make predictions about images?
Kindly Suggest it will be a great help!

**Comment by Ayush517** [comment]
@harshita-pal Can you please try going through this [Link](https://www.tensorflow.org/hub/tutorials/image_retraining). It contains step-by-step procedure and instructions to manage the model.
Let us know if you still need help 😄

**Comment by jvishnuvardhan** [comment]
@harshita-pal In future, Please post this kind of support questions in stackoverflow. We would like to keep GitHub less cluttered for open source developers. Close the issue as soon as possible. Thanks!

**Comment by umang752** [comment]
I am implementing MobileNet Modal but it is not giveing me a relevent result see : https://prnt.sc/mwuz3r
this is a Iphone and it is saying Remote.
can I trained my own modal ?

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
