### ISSUE TITLE
Syntax Error in Udacity example code

### ISSUE THREAD

**Issue by CJDennis** [tensorflow/tensorflow#26421]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.8
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 10.0
- GPU model and memory: nVIDIA GTX 1050 Ti

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
A syntax error is raised.

**Describe the expected behavior**
The example code should work without modifications.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
The first code block on:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/1_notmnist.ipynb

gives an error when it tries to execute:
```python
# Config the matplotlib backend as plotting inline in IPython
%matplotlib inline
```
`SyntaxError: invalid syntax`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Ayush517** [comment]
If you are not using Jupyter IPython notebook, just comment out (or delete) the line, everything will work fine and a separate plot window will be opened if you are running your python script from the console.
If you want to make use of the line, install Jupyter IPython and run the notebook through that.
Let me know if the issue still exists. Thanks :)

**Comment by CJDennis** [comment]
@Ayush517 Thanks! The tutorial didn't mention Jupyter anywhere that I saw. It also wasn't obvious how to get the .py code running in Jupyter, but I've got it working now!

**Comment by Ayush517** [comment]
If it's resolved, you can close the issue 😄 
Just let us know if you have any more issues. Thanks
