### ISSUE TITLE
Cannot import tensorflow

### ISSUE THREAD

**Issue by anirbankonar123** [tensorflow/tensorflow#26429]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution  Linux Ubuntu 18.04):
- TensorFlow installed from (source or binary): pip3 install -U tf-nightly-gpu-2.0-preview
- TensorFlow version: cannot be imported
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Import Error : 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

~/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~/anaconda3/lib/python3.6/imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

~/anaconda3/lib/python3.6/imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-1ceb9a7c68bc> in <module>()
      2 import time
      3 
----> 4 import tensorflow as tf
      5 from tensorflow.python.ops import lookup_ops
      6 

~/.local/lib/python3.6/site-packages/tensorflow/__init__.py in <module>()
     25 import sys as _sys
     26 
---> 27 from tensorflow._api.v2 import audio
     28 from tensorflow._api.v2 import autograph
     29 from tensorflow._api.v2 import bitwise

~/.local/lib/python3.6/site-packages/tensorflow/_api/v2/audio/__init__.py in <module>()
      6 from __future__ import print_function as _print_function
      7 
----> 8 from tensorflow.python.ops.gen_audio_ops import decode_wav
      9 from tensorflow.python.ops.gen_audio_ops import encode_wav
     10 

~/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

~/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/ubuntu/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ubuntu/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.
**Any other info / logs**
Installed Anaconda using : wget https://repo.anaconda.com/archive/Anaconda3-5.0.0-Linux-x86_64.sh
python3 --version gives python 3.6.2
Installed tensorflow 2 using cmd : pip3 install -U tf-nightly-gpu-2.0-preview

Opened Jupyter notebook and doing : import tensorflow as tf

**Comment by wookayin** [comment]
You should wrap the code in a fenced codeblocks using three backticks ( ``` ).

The error message says: `ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory` --- you should have CUDA 10 installed.

**Comment by anirbankonar123** [comment]
Hi,
I was using : pip3 install -U tf-nightly-gpu-2.0-preview , which is a gpu
version, and I was doing in AWS EC2 t2large CPU instance.
Now I have installed : tensorflow==2.0.0-alpha0,
Getting a diff issue: its not finding this in jupyter :ModuleNotFoundError:
No module named 'tensorflow'

Pls see log here , I am in virtualenv, and also able to print Tensorflow
version from cmd line. But the same does not work in jupyter.

 (venv) ubuntu@ip-172-31-22-38:~$ python3 -c "import tensorflow as tf;
print(tf.__version__);"

2.0.0-alpha0

 Followed the steps : https://www.tensorflow.org/install/pip


Please help.

Thanks

**Comment by Ayush517** [comment]
Did you install tensorflow from source? Are you running jupyter from the source directory? 
You need to run Jupyter notebook from source directory. Or if you are using a virtual environment(venv), you need to install Tensorflow in that too in order for Jupiter notebook to import it.
Let me know if this resolves your issue. Thanks :)

**Comment by anirbankonar123** [comment]
Pls see here the steps:
I am activating venv, and the fact its activated is proven by the
tensorflow version which i can print out from cmdline:
ubuntu@ip:~$ source activate venv
(venv) ubuntu@ip:~$ python3 -c "import tensorflow as tf;
print(tf.__version__); "
2.0.0-alpha0
(venv) ubuntu@ip:~$ jupyter notebook

but then the same error msg : ModuleNotFoundError: No module named
'tensorflow'

Cant believe my eyes :) Maybe will reinstall evthing.

**Comment by Ayush517** [comment]
@anirbankonar123 If you really want to reinstall, I would recommend you to install via Anaconda. It'll be much easier to manage your packages through that.

**Comment by jvishnuvardhan** [comment]
@anirbankonar123 I don't see any issue. check the image [here](https://screenshot.googleplex.com/d9OAKP6x4E8). 

By default, when you enter like (venv) ubuntu@ip:~$ jupyter notebook, a jupyter dashboard opens up like [this](https://screenshot.googleplex.com/beEJn01vtqg) 
then go to your venv folder like [this](https://screenshot.googleplex.com/5HVwQCUf69A). Then run the commands. It will work. Please close once you verify it. 

In future, please post support questions in stackoverflow. We should this GitHub uncluttered for the open source developers. Thanks!

**Comment by anirbankonar123** [comment]
Thanks, actually I was doing evthing fine, had a small issue . Had to start up a kernel properly before starting up Jupyter : 
cmd : ipython kernel install --user --name=.venv  (was doing this but with name=venv, missed the . (dot) !).
Thanks for the responses, appreciate it.
Closing the issue.
Thanks
