### ISSUE TITLE
tf.contrib.training.HParams domain interval support

### ISSUE THREAD

**Issue by moritzmeister** [tensorflow/tensorflow#26436]
Hi, this is my first issue/feature request. I hope it's relevant :)

I am currently working on hyperparameter optimisation and would like to use the HParams API but in my eyes there is a feature missing. Instead of having a discrete list of values for a parameter, I would like to represent a feasible interval, from which I can take values.

**Describe the feature and the current behavior/state.**
Currently, the HParams class holds a set of hyperparameters as name-value pairs, that is a discrete set of values for each of the hyperparameters. I would like to be able to specify also the feasible interval from which the values are coming. Also the TensorBoard api for reporting experiment summaries provides the possibility to report the domain interval and I think it would be handy to have this information in the HParams class, too.

The TensorBoard API let's you specify the `domain_discrete` but you could also provide `domain_interval`.
```
api_pb2.HParamInfo(name='num_units',  
                             display_name='Number of units',  
                             type=api_pb2.DATA_TYPE_FLOAT64,  
                             domain_discrete=num_units_list_val),
```

**Will this change the current api? How?**
Yes, this would require changing the API such that the User can also specify the interval of a parameter, for example:

```
add_hparam(
    name,
    value,
    start,
    end
)
```

Furthermore, the data structure would need to be changed to save the interval.
[Tensor2Tensor has something similar](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/layers/common_hparams.py) with RangedHParams.

**Who will benefit with this feature?**
Anyone working with intervals for hyperparameters compared to a fixed set of discrete values.

**System information**
- TensorFlow version (you are using): r1.12
- Are you willing to contribute it (Yes/No): Yes, I am happy to help, but this would be my first contribution and I would need guidance

**Comment by mohantym** [comment]
Hi @moritzmeister !
We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!

**Comment by moritzmeister** [comment]
Yes, this is outdated, will close.
