### ISSUE TITLE
using HParams with TPU v2 PODs broken

### ISSUE THREAD

**Issue by patzm** [tensorflow/tensorflow#26437]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.0
- Python version: 2.7
- CUDA/cuDNN version: 9.0 / 7
- GPU model and memory: T4, 16 GB
- TPU type: v2-32
- TPU TensorFlow version: 1.12.0

**Describe the current behavior**
The distribution to the pod fails with
1. `AttributeError: 'TPUContext' object has no attribute 'is_input_sharded_per_core'` if passing a user-provided `tf.contrib.training.HParams` instance to the `TPUEstimator`. Use `--use_hparams` argument in the demo script.
2. `AttributeError: 'dict' object has no attribute 'batch_size'` if no `HParams` are provided. Use `--nouse_hparams` argument in the demo script.

**Describe the expected behavior**
I expect `params` in the `model_fn` and `input_fn` to be an instance of `tf.contrib.training.HParams`, hence its parameters should be accessible as attributes. However in 2.) `params` is a python `dict`.

I expect to be able to use the `TPUEstimator` with my own `HParams`.

**Code to reproduce the issue**
See https://gist.github.com/ceaed6f7c2ed027da35fe5fbbe0056ae
Help:
```bash
USAGE: tpu_hparams.py [flags]
flags:

tpu_hparams.py:
  --num_cores: The number of TPU cores in the pod.
    (default: '32')
    (an integer)
  --project: The project name, the TPU is instantiated in.
    (default: '')
  --tpu: The TPU name.
    (default: '')
  --[no]use_hparams: To avoid the bug.
    (default: 'true')
  --zone: The zone name, the TPU is instantiated in.
    (default: '')
```

**Other info / logs**
What causes the issues?
1. If a user provides `params`, then the `TPUEstimator` adds the `TPUContext` to `params` by calling
https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py#L1528-L1531
This triggers the `add_param` or `set_param` methods. If `set_param` is used because the key `context` was not found in `params`, then `_cast_to_type_if_compatible` is invoked before setting the parameter. Unfortunately this triggers a casting / copy operation:
https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/contrib/training/python/training/hparam.py#L187
Because the syntax of the `TPUContext` only requires one positional argument
https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/contrib/tpu/python/tpu/tpu_context.py#L43-L55
a new `TPUContext` is initialized, where the `_internal_ctx` is set to the `TPUContext` instance, which itself actually contains a instance of `_InternalTPUContext`.

How could this be solved?
* create a clone / copy constructor for `HParams`
* use deep cloning? In case of standard types, this would instantiate a new one as well, if I am not mistaken.
* fix the problem in the `TPUEstimator` by always using instances of `HParams` and setting `context` before, so we add the `context` by calling `add_hparam`, which does not use the type casting, instead of `set_hparam`.

2. `hparams` suddenly is a `dict`, not a instance of `HParams`.

**Comment by patzm** [comment]
a hotfix would be to pass `hparams` as a `dict` like so
```python
estimator = tf.contrib.tpu.TPUEstimator(
    use_tpu=True,
    model_fn=model_fn,
    config=config,
    params=params.__dict__,
    train_batch_size=128
)
```

**Comment by patzm** [comment]
btw I am motivated to implement a fix as well. At the moment though I am not sure which way is the best. Especially because I am not aware of any reasoning behind the way it is implemented now.

**Comment by rjpower** [comment]
Thanks for the bug report and apologies for the slow reply.

This issue has been fixed (by fixing the behavior of `HParams.set_param`). It should show up in the tf-nightly build today, and will be available with the next release of TensorFlow.

In the meantime, as you mention you can use a dictionary instead of the HParams object as a workaround. Sorry for the inconvenience!

**Comment by patzm** [comment]
cool great to hear that 👍
