### ISSUE TITLE
[doc] dead link in "Build and load a SavedModel"

### ISSUE THREAD

**Issue by csukuangfj** [tensorflow/tensorflow#26431]
**System information**
- TensorFlow version: master
- Doc Link: https://www.tensorflow.org/guide/saved_model

**Describe the documentation issue**

The link <https://www.tensorflow.org/tfx/guide/serving/serving_basic> for "TensorFlow serving" is no long available in the doc [Build and load a SavedModel](https://www.tensorflow.org/guide/saved_model#build_and_load_a_savedmodel)

**Comment by jvishnuvardhan** [comment]
@csukuangfj Correct two links are not working.
1. First "Tensorflow Serving" in this [section](https://www.tensorflow.org/guide/saved_model#build_and_load_a_savedmodel) . -- this is what you found.
2. "instructions" in this [section](https://www.tensorflow.org/guide/saved_model#load_and_serve_a_savedmodel_in_tensorflow_serving). 
Thanks for pointing them. We will take care of them. Thanks!

**Comment by MarkDaoust** [comment]
Both fixes are in the source files, there will be some delay to push to the site.
