### ISSUE TITLE
[Tflite] Unable to convert model to tflite with uneven input dimension

### ISSUE THREAD

**Issue by gustavz** [tensorflow/tensorflow#26435]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS High Sierra
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.13
- Python version: 3.6.5
- Bazel version (if compiling from source): - 
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

Hi I have a fully convolutional CNN model (PoseNet to be precise), which is therefore able to process input of any dimension.

Converting the model to tflite works perfectly with even Input dimensions like 224x224.
But I need it to get converted with uneven Input Dimensions something like 225x225 or 289x289.

Setting these uneven input dimension in toco/ the tflite converter results in the following error:
```
RuntimeError: TOCO failed see console for info.
b'2019-03-07 10:20:29.334193: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] 
Before Removing unused ops: 213 operators, 318 arrays (0 quantized)\n2019-03-07 10:20:29.340266: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] 
Before general graph transformations: 213 operators, 318 arrays (0 quantized)\n2019-03-07 10:20:29.348270: F tensorflow/contrib/lite/toco/graph_transformations/propagate_fixed_sizes.cc:991] 
Check failed: height_with_paddings % block_height == 0 (1 vs. 0)\n'
```

Questions:

1. Why does tflite need fixed input dimensions? (I suppose this reduces necessary computations and therefore allow faster inference)
2. Why is it not possible to convert a model to tflite with uneven Input Dimensions even though the model is fully convolutional and can therefore generally handle those dimensions?
3. Is there a workaround to fix my problem?
4. Additional: Can someone who knows posenet explain to me why it needs this +1 padding to even input dimensions: (line 109 in: https://github.com/tensorflow/tfjs-models/blob/master/posenet/src/util.ts)

Thank you very much in advance!

**Comment by flankechen** [comment]
I am facing the same problem, I think tflite Interpreter needs a fixed input dimension to feed data for faster runtime. 
one walk around might be fixe the input size to target size. but fully conv operation usually comes with pyramid, multiple input size could be fixed.
But, this means multiple .tflite file. I don't think this is worth trying.
Some better way of fully conv runs with tflite is really needed.

currently, I am using the old style .pb like to run a fully conv net on mobile, which is ok though

**Comment by jvishnuvardhan** [comment]
@gustavz This is a stale issue. 

Many bugs have been fixed in the latest TF version. Could you please execute your code using Latest Version 2.6 (and `tf-nightly`) and let us know if the issue still persists? If it persists with latest TF versions, can you please share a simple standalone code to reproduce the issue?

Also, please note that we are not supporting TF1.x. Thanks!
