### ISSUE TITLE
Tensorboard not opening in jupyter notebook

### ISSUE THREAD

**Issue by Sagarsharma4244** [tensorflow/tensorflow#26441]
I am trying to open tensorboard inside jupyter notebook with the command 
`% tensorboard --logdir keras`.
But I am getting 
**localhost refused to connect.**
Specifications:

- Jupyter notebook= 5.7.5
- Python = 3.6.7
- Windows =10
-  tensorflow = 2.0.0-alpha0

**Code**
```
from kaggle_data import load_data, preprocess_data, preprocess_labels
import numpy as np
import matplotlib.pyplot as plt

X_train, labels = load_data('../data/kaggle_ottogroup/train.csv', train=True)
X_train, scaler = preprocess_data(X_train)
Y_train, encoder = preprocess_labels(labels)

X_test, ids = load_data('../data/kaggle_ottogroup/test.csv', train=False)
X_test, _ = preprocess_data(X_test, scaler)

nb_classes = Y_train.shape[1]
print(nb_classes, 'classes')

dims = X_train.shape[1]
print(dims, 'dims')

import tensorflow as tf
from keras.layers import Dense, Activation

dims = X_train.shape[1]
print(dims, 'dims')
print("Building model...")
nb_classes = Y_train.shape[1]
print(nb_classes, 'classes')
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(nb_classes, input_shape=(dims,), activation='sigmoid'))
model.compile(optimizer = 'sgd', loss='categorical_crossentropy')
model.fit(X_train, Y_train,epochs=1,callbacks=[tf.keras.callbacks.TensorBoard('keras')] )

%load_ext tensorboard.notebook
%tensorboard --logdir keras
```

**Comment by Ayush517** [comment]
Hi @Sagarsharma4244, It's working absolutely fine on my system.
Maybe a host based firewall has been set to block all TCP ports or block IP 127.0.0.1 localhost. Maybe, You need to reboot the machine to clear O/S issues. Try resetting your network adapters too.
Let me know how it goes. Thanks :)

**Comment by Sagarsharma4244** [comment]
Initially when I  installed 2.0 and tensorboard extension, it did work once.  I did try to reboot the system but that didn't affect the result.

**Comment by wookayin** [comment]
What are the port numbers, etc.? (e.g. `tensorboard.notebook.list()`) Are you certain that the tensorboard is running on your "localhost", not on a remote machine?

**Comment by jvishnuvardhan** [comment]
@Sagarsharma4244 Please post tensorboard related issues to Tensorboard group [here](https://github.com/tensorflow/tensorboard/issues). It's very active team who will support your questions faster. Thanks!
