### ISSUE TITLE
Add SAMD21 or SAMD51 TensorFlow Lite for Microcontrollers

### ISSUE THREAD

**Issue by sabas1080** [tensorflow/tensorflow#26447]
A widely used platform is the SAMD21 and SAMD51 family with a large number of development boards
https://www.adafruit.com/product/4064
https://www.adafruit.com/product/2772
https://www.sparkfun.com/products/13672

Support:
- C++11
- Arduino
- Circuitpython
- Makecode
- Rust

they should be considered to be ported

**System information**
- TensorFlow version (you are using): Lite
- Are you willing to contribute it (Yes/No): I can help with test

Thanks!

**Comment by sabas1080** [comment]
Adafruit have an example https://github.com/adafruit/Adafruit_TFLite_Micro_Speech

**Comment by wangtz** [comment]
Thanks for the pointer. I don't think that we have enough bandwidth to cover this board. Since Adafruit already their work open sourced. Are you interested in contributing this work to TF? Thanks,

**Comment by petewarden** [comment]
Moving to contributions welcome.

**Comment by mohantym** [comment]
Hi @sabas1080 !
We are just checking whether you still need any assistance. 
Both SAMD21 and SAMD51 are 32 based Architecture (Arduino family) . So current lite documentation on  microcontrollers with should work on them too (convert model to tflite, get the .cc file to import it from Arduino library)

Attached relevant thread for reference. [1](https://github.com/tensorflow/tensorflow/issues/57031#issuecomment-1209578177), [2](https://www.digikey.com/es/en/maker/projects/tensorflow-lite-for-microcontrollers-kit-quickstart/1b372b69e44f4d988b5363741a61882d). 
Thank you!

**Comment by sabas1080** [comment]
@mohantym thanks

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
