### ISSUE TITLE
cpu build failed with openmpi

### ISSUE THREAD

**Issue by peggy0135** [tensorflow/tensorflow#26448]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : ubuntu 18.04 (64-bit FriendlyDesktop image file based on Ubuntu desktop 18.04 64bit)
- Mobile device: friendlyARM's NanoPC-T4
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.13.0
- Python version:3.6
- Installed using virtualenv? pip? conda?: non
- Bazel version (if compiling from source):0.19.2
- GCC/Compiler version (if compiling from source): gcc 7.3
- CUDA/cuDNN version: non
- GPU model and memory: non

**Describe the problem**
missing links related to OpenMPI(ex:mpi.h, libmpi.so, ...)
when building with bazel 
error message: tensorflow/pyhton/4301:0 missing input file thirdparty/mpi:mpi:h

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Ayush517** [comment]
Can you please try doing this :
sudo apt install libopenmpi-dev
pip install mpi4py

**Comment by peggy0135** [comment]
fix by creating the links in thirdparty/mpi manually

**Comment by jvishnuvardhan** [comment]
@peggy0135 Could you specify what options you selected for config?  Could you follow several other user's [issues](https://github.com/tensorflow/tensorflow/issues?q=is%3Aissue+mpi+is%3Aclosed) that had similar bug like you. I see some are relevant to you. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!
