### ISSUE TITLE
TensorFlow 1.13.1 with Docker under Raspbian Stretch

### ISSUE THREAD

**Issue by gounthar** [tensorflow/tensorflow#26459]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Docker version 18.09.0, build 4d60db4 on top of Linux stf-provider 4.14.34-hypriotos-v7+ #1 SMP Sun Apr 22 14:57:31 UTC 2018 armv7l GNU/Linux. Raspbian is 9.8 in the Docker container.
- TensorFlow installed from binary: `pip3 install tensorflow`
- TensorFlow version: 1.13.1 
- Python version: 3.5.3
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: nope

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```bash
root@ed47bf54107c:/tmp# python3 -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
```

gives

```bash
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
tf.Tensor(-611.39856, shape=(), dtype=float32)
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
If you ever want to give it a try, here is the image:

```bash
docker pull gounthar/tensorflow-armv7:1.13
```

I tried another image from the Data Science Docker Stack:

```bash
fedec07fb96b        elswork/tf-opencv:latest   "/bin/bash"              4 minutes ago       Up 4 minutes                                        practical_dirac
```
and I got the same kind of error:

```bash
root@fedec07fb96b:/# python3 tensorFlow.py
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
```

**Comment by freegroup** [comment]
I have the same problem as mentioned in this issue https://github.com/tensorflow/tensorflow/issues/23840

....ticket is closed without solution.

**Comment by petewarden** [comment]
The warnings shouldn't result in any bad behavior, they're just a nuisance. We have recently updated our RPi pip packages to Py 3.7, so you should no longer see the log warnings on that version. Closing, since it doesn't result in any actual errors.
