### ISSUE TITLE
[TF2 Upgrade] contrib usage and several other TF 1.x APIs uncaught by TF2 upgrade script

### ISSUE THREAD

**Issue by zmjjmz** [tensorflow/tensorflow#26461]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian 8
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): pip binary
- TensorFlow version (use command below): TF 2 nightly as of 3/7/19 (comparison version is 1.13.1
- Python version: 3.4.2
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**

In order to make sure that my crusty old TF 1.x code works on TF 2, I'm using the `tf_upgrade_v2` script [as documented](https://github.com/tensorflow/docs/blob/master/site/en/r2/guide/upgrade.md). 

However, on the first bit of [code](https://gist.github.com/zmjjmz/2ee2090233217c0d1be2dc975e5c3a47) I tried I was told that it 'Detected 0 issues that require attention', and the report it gave was essentially blank. Additionally, the diff between the old file and the new file showed no changes!

This would have been great, except there's a few things that are very obviously incorrect.

- On lines 42 and 43, there's a use of `tf.contrib.lookup` which should be moved to `tf.lookup`.
- On line 63 there's a call to `tf.sparse_tensor_to_dense` which should be moved to `tf.sparse.to_dense`
- On lines 118-121 there's a tf.Session context and a `tables_initializer` which no longer exist.

**Describe the expected behavior**

I would hope that the above 4 issues would be pointed out by the upgrade script as needing my attention, even if it cannot (for some reason, although I imagine the one on line 63 can be done with a string replacement) fix them automatically. 

Note: I still haven't gotten this script (despite some manual upgrading) to work on TF2, but it (pre-manual upgrade) works fine on TF 1.13.1, although it gives me a bunch a bunch of deprecation warnings :)

**Code to reproduce the issue**

See the attached [gist](https://gist.github.com/zmjjmz/2ee2090233217c0d1be2dc975e5c3a47)

**Comment by annarev** [comment]
The script currently assumes that import has the form "import tensorflow as tf". However, the snippet you linked just uses "import tensorflow".
We should definitely update documentation and may be look into supporting other import names. Thank you for catching that and sorry for the trouble!

**Comment by zmjjmz** [comment]
Ok, I can confirm that it works as expected when I do that.

**Comment by amahendrakar** [comment]
@zmjjmz,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by annarev** [comment]
I think the only outstanding task was adding a note to documentation. Just checked our documentation here: https://www.tensorflow.org/guide/upgrade has this sentence:
"The script assumes that tensorflow is imported using `import tensorflow as tf.`"
So, I am closing this issue.
