### ISSUE TITLE
[CI] The PR Checks of TenrsorFlow are broken.

### ISSUE THREAD

**Issue by leemgs** [tensorflow/tensorflow#26467]
It is strange. It seems that the PR Checks are suddenly broken. Anyone why this issue is still not fixed?
As you can see, Many PRs have been not reviewed by reviewers because the Tensorflow CI facilities are still a running status. BTW, Why this issue is generated? What is a possible reasons? Who is in charge of the CI facilities of the TensorFlow github repository?

```bash
* Ubuntu CC Expected — Waiting for status to be reported  Required
* Ubuntu Sanity Expected — Waiting for status to be reported  Required
* import/copybara Expected — Waiting for status to be reported  Required
```

* Screenshot: 

![image](https://user-images.githubusercontent.com/82404/54006477-d5db4280-41a0-11e9-974f-2708aa2f39ec.png)

![image](https://user-images.githubusercontent.com/82404/54006516-f6a39800-41a0-11e9-98b0-b45a32135c78.png)

**Comment by ymodak** [comment]
The behavior you see here is expected. It says that those tests are required but are waiting to be initialized. Once we trigger the build tests their status will be updated accordingly.

**Comment by leemgs** [comment]
>> Ubuntu CC Expected — Waiting for status to be reported
>It says that those tests are required but are waiting to be initialized. 

@ymodak It seems that the tests are too slow when PRs are submitted.  Are the slow tests generated from the too many pull requests (PRs)?
