### ISSUE TITLE
Tensorflow.loadLibrary() not working on Windows

### ISSUE THREAD

**Issue by saif-ellafi** [tensorflow/tensorflow#26468]
Running:

`TensorFlow.loadLibrary("ner-dl/win/_lstm_ops.so")`

Returns:

```
java.lang.UnsatisfiedLinkError: ner-dl\win\_lstm_ops.so not found
	at org.tensorflow.TensorFlow.loadLibrary(TensorFlow.java:47)
```

We're trying to load contrib .so files dynamically from java API. These .so files are generated on Windows by installing tensorflow through pip. Using python 3.6.8 to do so and retrieving them from the library source code. These libraries are from tensorflow.contrib, since this is what we're using on our graphs. To me, this sounds like a path resolving issue, since it's the same error than making up an invented path.

Works fine when using appropriate .so files on Linux and Mac.

Same happens if using absolute paths btw:
```
java.lang.UnsatisfiedLinkError: C:\Users\saifa\IdeaProjects\spark-nlp\src\main\resources\ner-dl\win\_lstm_ops.so not found
	at org.tensorflow.TensorFlow.loadLibrary(TensorFlow.java:47)
```

It seems this also happened to this poor guy here:
https://stackoverflow.com/questions/50115117/using-ops-from-tensorflow-contrb-on-windows-via-java-api

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
`TensorFlow.loadLibrary("ner-dl/win/_lstm_ops.so")`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
Binary from pip
- TensorFlow version (use command below):
`b'v1.12.0-rc2-3-ga6d8ffae09' 1.12.0`
- Python version:
Using Java API
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Running
`TensorFlow.loadLibrary("ner-dl/win/_lstm_ops.so")`
returns 
```
java.lang.UnsatisfiedLinkError: ner-dl\win\_lstm_ops.so not found
	at org.tensorflow.TensorFlow.loadLibrary(TensorFlow.java:47)
```

**Describe the expected behavior**
Should be able to load libraries dynamically on Windows. This works fine from Linux and Mac.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
`TensorFlow.loadLibrary("ner-dl/win/_lstm_ops.so")`

**Comment by ymodak** [comment]
@asimshankar Can you PTAL? Thanks!

**Comment by asimshankar** [comment]
Unfortunately, dynamic library loading in Windows is not supported yet AFAIR.
I might be mis-remembering, but dynamically loading shared libraries doesn't work on Python on Windows either, right?

@allenlavoie @sjamesr @gunan  might have more details on this and might be able to explain what needs to happen to make this possible.

**Comment by gunan** [comment]
@meteorcloudy as he helped us a lot with shared objects on windows.
I think we finally had custom ops working on windows. Were they using loadLibrary?

**Comment by meteorcloudy** [comment]
Dynamically loading shared libraries works in Python on Windows, but I never tired using Java API so it might still be not supported.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by saifjsl** [comment]
Hi, I am still interested on this issue. Was closed by bot. Still opening, still happening.

**Comment by asimshankar** [comment]
I noticed that the `loadLibrary` call is loading a `.so` file. Shouldn't it be loading a `.dll` file? Does `ner-dl\win\_lstm_ops.so` exist?

**Comment by saifjsl** [comment]
Yes, the file exists. the error is the same if you make up a file name. The same code works on linux and mac. I am not sure if it should be a .dll. If so, I'd like to know where to get the lstm contrib libs for windows.

**Comment by onewhl** [comment]
Hi everyone! I faced with the same problem when I tried to load "tf.contrib" using TensorFlow Java API on Windows (for Linux Ubuntu works fine).  
I found answer how to solve this : [link](https://stackoverflow.com/questions/50115117/using-ops-from-tensorflow-contrb-on-windows-via-java-api). But there is another problem -> unable to load model. 
So, how do we solve this problem?

**Comment by ymodak** [comment]
@asimshankar Can you PTAL? Thanks!

**Comment by asimshankar** [comment]
@sjamesr : Could you take a look? (I haven't been working on TensorFlow for a while now :))

**Comment by carlosuc3m** [comment]
Has there been any advance on this?

**Comment by sjamesr** [comment]
Will take a look, sorry for the delay.

**Comment by asadkhilji** [comment]
Hi, is this problem resolved ?

**Comment by onewhl** [comment]
Hi @sjamesr , any updates on the issue?

**Comment by onewhl** [comment]
@sjamesr, @asimshankar, any updates?

**Comment by saif-ellafi** [comment]
Hi, this issue is no longer valid since Tensorflow 1.15, given contrib libraries are handled differently.

**Comment by Saduf2019** [comment]
@saif-ellafi 
Please confirm if we may moved this to closed status.

**Comment by maziyarpanahi** [comment]
@Saduf2019 I can confirm this issue can be closed. Me and Saif work on the same project and this issue is no longer presents in 1.15.x


Many thanks.

**Comment by saif-ellafi** [comment]
I confirm this can be closed. Thanks
