### ISSUE TITLE
segment erro:tensorflow/tensorflow/examples/label_image/main.cc

### ISSUE THREAD

**Issue by allendred** [tensorflow/tensorflow#26464]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):r1.13
- Python version:3.6
- Bazel version (if compiling from source):0.23
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:9.0/7.0
- GPU model and memory:1080ti/11gb

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
tensorflow/tensorflow/examples/label_image/main.cc
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
i think the reason is "TF_RETURN_IF_ERROR(env->NewRandomAccessFile(filename, &file));"
https://github.com/tensorflow/tensorflow/blob/5fad2f50d610fdb765f4f99c7e0531b7a3ddbe94/tensorflow/examples/label_image/main.cc#L100

**Comment by allendred** [comment]
I make a mistake
here
https://github.com/tensorflow/tensorflow/blob/5fad2f50d610fdb765f4f99c7e0531b7a3ddbe94/tensorflow/examples/label_image/main.cc#L103

**Comment by allendred** [comment]
If I commente out this ，it's ok.

**Comment by jvishnuvardhan** [comment]
@allendred Is it resolved or still an issue? Could you provide more details on the issue and provide a code to reproduce the bug? Thanks!

**Comment by allendred** [comment]
> @allendred Is it resolved or still an issue? Could you provide more details on the issue and provide a code to reproduce the bug? Thanks!

I changged to another demo(detection),abondon the function ("read_entirefiles"),so it works

**Comment by jvishnuvardhan** [comment]
@allendred Thanks for the confirmation. I will close the issue. Thanks!
