### ISSUE TITLE
The use of graph_editor.graph_replace

### ISSUE THREAD

**Issue by OnceJune** [tensorflow/tensorflow#26473]
Hi, I'm quite new to tensorflow and I came from this question: [tensorflow-replace-an-operation-with-an-other](https://stackoverflow.com/questions/47081900/tensorflow-replace-an-operation-with-an-other) , which is asked quite a long time ago and I've got similar need.
I have a tacotron model, freezed, with LSTMBlockCell and dynamic_rnn involved, which seems to not have a quantization version in tensorflow/tools/graph_transforms/quantize_nodes. 
The idea is that quant the weights and bias, and replace things in the graph first, maybe add dequant nodes later and modify the lstmblockcell itself. I tried to process the first step in this way:

```
tensors = [n for n in session.graph.as_graph_def().node]
for t in tensors:
  if 'lstm_cell' in t.name:
    lstm_cell = graph.get_tensor_by_name(t.name + ':0')
    val = session.run(lstm_cell)
    quant_val = quant_weights(val)
    new_t = tf.convert_to_tensor(quant_val, np.uint8)
    tf.contrib.graph_editor.graph_replace(lstm_cell, {lstm_cell : new_t})
```
And it returned:
```
Traceback (most recent call last):
  File "edit_graph.py", line 131, in <module>
    load('my_graph.pb')
  File "edit_graph.py", line 100, in load
    tf.contrib.graph_editor.graph_replace(lstm_cell, {lstm_cell : new_t}, reuse_dst_scope = True)
  File "/home/admin/.local/lib/python3.6/site-packages/tensorflow/contrib/graph_editor/transform.py", line 736, in graph_replace
    raise ValueError("Targets and replacements are not connected!")
ValueError: Targets and replacements are not connected!
```
Could you kindly point out the mistake I made? Thanks in advance.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
