### ISSUE TITLE
Where is gen_experimental_dataset_ops?

### ISSUE THREAD

**Issue by linrio** [tensorflow/tensorflow#26480]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.0.0

**Provide the text output from tflite_convert**

```
from tensorflow.python.ops import gen_experimental_dataset_ops
```
in `tensorflow/python/data/experimental/ops/batching.py`
Is it the `gen_experimental_dataset_ops` disappeared? I can not find where the `gen_experimental_dataset_ops` is defined.

**Comment by mrry** [comment]
It's a generated file. The easiest way to see its contents might be to download and install a PIP package, and look at the library source.

**Comment by oiabtt** [comment]
> It's a generated file. The easiest way to see its contents might be to download and install a PIP package, and look at the library source.
I met the same problem,  gen_experimental_dataset_ops.py is not in Tensorflow project. Is it removed to other place?
