### ISSUE TITLE
ImportError: cannot import name 'Activation'

### ISSUE THREAD

**Issue by marcown** [tensorflow/tensorflow#26482]
Hi,

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No. Just importing.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Manjaro
- TensorFlow installed from (source or binary):
via pip install tensorflow
- TensorFlow version (use command below):
1.13.1
- Python version:
3.6

**Describe the current behavior**

with tensorflow-1.13.1 one cannot import keras.Model and keras.layer with

from tensorflow.keras import Model

-> this gives the following error:

    from tensorflow.python.keras.applications.densenet import Activation; ImportError: cannot import name 'Activation'

**Describe the expected behavior**
Expected that I can do the following import:
from tensorflow.keras import Model

**Other info / logs**

However, importing with

from tensorflow import keras 

and then use keras.Model or keras.layer works fine

**Comment by ymodak** [comment]
I was able to execute ```python from tensorflow.keras import Model``` successfully in TF 1.13.1
Can you please try updating your keras version?
