### ISSUE TITLE
Be able to save a stateful operation

### ISSUE THREAD

**Issue by Silb78dg** [tensorflow/tensorflow#26493]
**System information**
- TensorFlow version (you are using): tf 1.13
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Current behavior is the saver will crash trying to save a stateful operation.
Feature behavior is the saver will have an additional option to save stateful operation with the known limitation that you will loose the state of your operation.

This could be useful if you want to save the state of your dataset iterator but your pipeline contains stateful operation (random crop for example).

**Will this change the current api? How?**
Yes, by adding a new option?

**Who will benefit with this feature?**
Anyone who wants to save a stateful operation.

**Any Other info.**

**Comment by allenlavoie** [comment]
Sorry, not my department. Shivani, this sounds like an Iterator saving request. Are you the right person to triage those issues?

**Comment by tilakrayal** [comment]
Hi @Silb78dg,
Sorry for the delay. Could you elaborate about your Feature. Also, please specify the use-cases for this feature. Thank you!
