### ISSUE TITLE
Bazel always rebuild all code even I just modify single cpp file when config=cuda is used 

### ISSUE THREAD

**Issue by ttyio** [tensorflow/tensorflow#26498]
**System information**

- TensorFlow version (you are using): master branch
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
When I change any file in tensorflow/compiler, bazel always rebuild all code when config=cuda is used, I did not hit the bug after remove config=cuda.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Anyone who follow https://www.tensorflow.org/install/source

**Any Other info.**

**Comment by jvishnuvardhan** [comment]
Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. Thanks!

**Comment by gunan** [comment]
Unfortunately, that is the artifact of how TF code and build rules are organized.
Many files are included in many targets, and it will trigger almost a full rebuild.

Modular tensorflow will help with this, but until that lands, I am afraid I cannot really offer a solution to this.

**Comment by pooyadavoodi** [comment]
Would it make sense to delete `config=cuda` from the docs here? Looks like it's not needed?
https://www.tensorflow.org/install/source#gpu_support

**Comment by ArtificialArchitect** [comment]
No, you can't get rid of that. Bazel is meant to be distributed. If you have some old PCs you can make a small farm or grid to help speed it up. They have clusters and grids and can compile it in minutes.

**Comment by gunan** [comment]
@perfinion for recommendations here.
I have some internal hacks I use so I may not be as familiar as him with this issue.

**Comment by sushreebarsa** [comment]
@ttyio Could you try to explore using Bazel's manual --noincompatible_action_toolchain flag. This can help Bazel reuse certain build artifacts if they haven't truly changed. 
Please have a look at this doc reference. Kindly raise a new ticket if you still have any concern using latest TF version?
Thank you!

**Comment by ttyio** [comment]
Thank you, I have not build TF a a while, closing
