### ISSUE TITLE
[TF 2.0 API Docs] tf.math.atan and tf.math.asin

### ISSUE THREAD

**Issue by Sudeepam97** [tensorflow/tensorflow#26492]
**System information**
- TensorFlow version: 2.0
- Doc Links:
   tf.math.atan: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/atan
   tf.math.asin: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/asin

**Describe the documentation issue**
Documentation for `tf.math.asin` and `tf.math.atan` is created from a generated file, `python/ops/gen_math_ops.py`. The documentation can be modified by editing the appropriate `.pbtxt` files within the `tensorflow/tensorflow/core/api_def/base_api` directory of the source repository.

Both of these math operations could use a clear description, usage examples, and a list specifying the errors raised by these operations.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
Definitely :smile:

**Comment by gadagashwini** [comment]
@Sudeepam97, Can we close the issue since the associated PR has been merged. Thanks!
