### ISSUE TITLE
Using Custom Loss in Keras 

### ISSUE THREAD

**Issue by diego898** [tensorflow/tensorflow#26490]
**System information**
- Uses a basic CNN MNIST Keras example
- CentOS7
- TensorFlow installed from: Anaconda
- TensorFlow version: Both 1.12-gpu and 2.0.0-alpha0-cpu
- Python version: 3.6

**Describe the current behavior**
I am trying to use a custom loss function in Keras. Ive simplified its use below, and discover that if I try to personally "touch" `y_pred` and `y_true` in anyway (even trivially as seen below), the model:

- Does **not** achieve high accuracy/categorgical accuracy/etc.
- **Does** achieve "low-loss"

In the code below I try to basic approaches:

1. `customLossThatWorks` is just an alias for a built in loss - This gets me to a low loss value, and high accuracy
2. Any of the other losses that actually "touch" the `y_` arguments, even one that is directly copied and pasted, achieve the same low loss, but not accuracy.

**Describe the expected behavior**
Write a custom loss that works, as per the documentation.

**Code to reproduce the issue**
```
import tensorflow as tf
import tensorflow.keras.backend as K
from tensorflow.keras import datasets, layers, models

(train_images, train_labels), (test_images, test_labels) = datasets.mnist.load_data()

train_images = train_images.reshape((60000, 28, 28, 1))
test_images = test_images.reshape((10000, 28, 28, 1))

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

def customLossThatWorks():
    return tf.keras.losses.sparse_categorical_crossentropy

# def customLoss(y_true, y_pred):
#     return K.sparse_categorical_crossentropy(y_true, y_pred)

# def customLoss():
#     def loss(y_true,y_pred):
#         return K.sparse_categorical_crossentropy(y_true, y_pred)
#     return loss
    
# def customLoss():
#     def loss(y_true,y_pred):
#         return tf.keras.losses.sparse_categorical_crossentropy(y_true,y_pred)
#     return loss

# copied from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/losses.py#L867
def customLoss(y_true, y_pred, from_logits=False, axis=-1):
    return K.sparse_categorical_crossentropy(
      y_true, y_pred, from_logits=from_logits, axis=axis)

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))
model.compile(loss=customLoss, optimizer='adam', metrics=['accuracy', 'categorical_accuracy'])
model.fit(train_images, train_labels, epochs=1)
```

**Other info / logs**
* **Note**: If the custom loss function handles `y_pred` and `y_true` directly, you just pass the function without invoking it: `=customLoss` vs `=customLoss()`

* Run the above, commenting out different versions of the loss and changing the compilation line accordingly: `model.compile(loss=customLoss(), optimizer='adam', metrics=['accuracy', 'categorical_accuracy'])` to observe the behavior
* The answer in #16721 and the [SO question](https://stackoverflow.com/questions/48654851/customized-loss-in-tensorflow-with-keras) generated from it, don't address this problem.

**Comment by timudk** [comment]
Your code does not even run, as you have to feed customLoss() with y_true and y_pred:

Traceback (most recent call last):
  File "test.py", line 43, in <module>
    model.compile(loss=customLoss(), optimizer='adam', metrics=['accuracy', 'categorical_accuracy'])
TypeError: customLoss() missing 2 required positional arguments: 'y_true' and 'y_pred'

**Comment by diego898** [comment]
@timudk I've updated the code - specifically changing this one line:

FROM:
```
model.compile(loss=customLoss(), optimizer='adam', metrics=['accuracy', 'categorical_accuracy'])
```

TO:
```
model.compile(loss=customLoss, optimizer='adam', metrics=['accuracy', 'categorical_accuracy'])
```

When the loss function handles `y_pred` and `y_true` directly, you just pass the function without invoking it.

**Comment by timudk** [comment]
@diego898 Thanks, I got it.

So I replaced:
`def customLoss(y_true, y_pred, from_logits=False, axis=-1):
    return K.sparse_categorical_crossentropy(
      y_true, y_pred, from_logits=from_logits, axis=axis)`

with

`def customLoss(y_true, y_pred, from_logits=False, axis=-1):
	return tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)`

and even this does not work, which seems really weird.

**Comment by timudk** [comment]
@diego898 

Okay, it seems like I found the mistake, change axis to axis=1. Training seems to work fine after this change.

**Comment by diego898** [comment]
Hey @timudk, according to the docs I only have to handle `y_true` and `y_pred` directly and it should work. For example, see one of the other customLosses that are commented out. 

Also, when you say "works fine" what do you mean? One of my problems is that it reports low loss, but also low accuracy in certain cases.

**Comment by timudk** [comment]
@diego898 

I have figured out what the problem is. When you use your custom loss, Keras things that accuracy=categorical_accuracy. Just change 
`model.compile(loss=customLoss, optimizer='adam', metrics=['accuracy', 'categorical_accuracy'])`

to 

`model.compile(loss=customLoss, optimizer='adam', metrics=['sparse_categorical_accuracy', 'categorical_accuracy'])`

and you should not see a difference between your custom loss and tf.keras.losses.sparse_categorical_crossentropy.

I hope this helps :)

**Comment by diego898** [comment]
@timudk - thank you I thought TF was doing something behind the scenes automatically that was failing in one case. Im not sure this is the intended behavior, so I will open a new issue to discuss it.
