### ISSUE TITLE
[TF 2.0 API Documentation Issue] `tf.lookup.StaticHashTable` usage example is incorrect

### ISSUE THREAD

**Issue by zmjjmz** [tensorflow/tensorflow#26497]
**System information**
- TensorFlow version: 2.0 preview
- Doc Link: [`tf.lookup.StaticHashTable`](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/lookup/StaticHashTable#class_statichashtable)

**Describe the documentation issue**

The example usage describes using `StaticHashTable.init.run()`, which is not possible since there is no `init` attribute (and it's missing from the documentation). [This comment](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/ops/lookup_ops.py#L321) in `lookup_ops.py` indicates that it's definitely not the correct way to initialize the table in TF 2.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

I don't think so, because I really have no idea what the correct way to initialize the table is :)

I've tried a few things [as shown here](https://gist.github.com/zmjjmz/81138b0d62764fabe00085cd7091dd14#file-tokenize_layer_tf2-py-L50) but to no avail, usually ending in a `FailedPreconditionError` :(

**Comment by shashvatshahi1998** [comment]
I am not getting any such example, please can anybody guide me

**Comment by zmjjmz** [comment]
The example I'm referring to is in the doc link, and is (as of writing) 
```
table = tf.lookup.StaticHashTable(
    tf.KeyValueTensorInitializer(keys, values), -1)
out = table.lookup(input_tensor)
table.init.run()
print(out.eval())
```

**Comment by jstamand** [comment]
This issue also causing me some headaches -- any updates?

**Comment by amahendrakar** [comment]
@zmjjmz,
The documentation and usage example for [tf.lookup.StaticHashTable](https://www.tensorflow.org/api_docs/python/tf/lookup/StaticHashTable) have been updated from TF v2.0. 

And I was able to run the usage example without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/0b912a9f4c1c2f5b67e046a89733b67a/26497.ipynb). Could you please take a look at it and let us know if this is still an issue. Thanks!

**Comment by zachary-jablons-okcupid** [comment]
Hey @amahendrakar 

This works. Thanks!

- Zach

**Comment by amahendrakar** [comment]
@zachary-jablons-okcupid,
Thank you for the update.

Closing the issue as it is resolved. Please feel free to re-open if necessary.
