### ISSUE TITLE
Trouble running a tutorial file

### ISSUE THREAD

**Issue by jaelim** [tensorflow/tensorflow#265]
Hi,

I'm trying to run all tutorials, and I'm stuck with fully_connected_feed.py as it produced following error:
Traceback (most recent call last):

  File "fully_connected_feed.py", line 15, in <module>
    import tensorflow.python.platform
  File "/home/pilotwarela0/Development/tensorflow/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/home/pilotwarela0/Development/tensorflow/tensorflow/python/__init__.py", line 15, in <module>
    from tensorflow.core.framework.graph_pb2 import *
ImportError: No module named core.framework.graph_pb2

I managed to track down the location of module:

/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/

So, added this path to PYTHONPATH with this:

PYTHONPATH="${PYTHONPATH}:/usr/local/lib/python2.7/dist-packages/tensorflow/"
export PYTHONPATH

It didn't work. So, I tried this solution by adding the lines:

import sys
sys.path.append("/usr/local/lib/python2.7/dist-packages/tensorflow/")

in ~/tensorflow/tensorflow/python/platform/__init__.py

None of these solution worked out for me. What am I doing wrong here? Could you please suggest a correct way to solve this problem?

**Comment by vrv** [comment]
"ImportError: No module named core.framework.graph_pb2" happens typically when you're trying to run in the same directory as the root of the source tree.  If you change into a different directory, does the problem go away?

**Comment by jaelim** [comment]
HI,

Thanks for replying. I copied fully_connected_feed.py into a new folder, and executed this in command python as before:

python fully_connected_feed.py

First, it produced the same error:

Traceback (most recent call last):
  File "fully_connected_feed.py", line 19, in <module>
    from tensorflow.g3doc.tutorials.mnist import input_data
ImportError: No module named g3doc.tutorials.mnist

I updated the PYTHONPATH as follows:

PYTHONPATH="${PYTHONPATH}:/home/pilotwarela0/Development/tensorflow"
export PYTHONPATH

and now arrived at the same error:

Traceback (most recent call last):
  File "fully_connected_feed.py", line 15, in <module>
    import tensorflow.python.platform
  File "/home/pilotwarela0/Development/tensorflow/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/home/pilotwarela0/Development/tensorflow/tensorflow/python/__init__.py", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
ImportError: No module named core.framework.graph_pb2

So, I wanted to check if I can import the module in python:

>>> from tensorflow.core.framework.graph_pb2 import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pilotwarela0/Development/tensorflow/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/home/pilotwarela0/Development/tensorflow/tensorflow/python/__init__.py", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
ImportError: No module named core.framework.graph_pb2

I tried to update the PYTHONPATH again, but not difference is produced.

**Comment by jaelim** [comment]
According to this, it's allowed to execute the source in root dir:

http://tensorflow.org/get_started/os_setup.html#train-your-first-tensorflow-neural-net-model

I tried the example as shown, but I encountered the same problem. I installed tensorflow on Ubuntu with this instruction:

# For CPU-only version
$ pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

And in python, I was able to import the tensorflow with no problem:

python> import tensorflow

**Comment by vrv** [comment]
That link is showing old contents: we've updated our git repo with the new instructions (as you note, the instructions on the website doesn't work).

Can you get things to work if you use virtualenv and use the binary pip install, by any chance?

**Comment by jaelim** [comment]
Unfortunately even in virtulaenv, fully_connected_feed.py neither worked in nor out of the source root. However, I was able to execute the convolutional.py.

Could you please try to run fully_connected_feed.py yourself as found in the git source?

**Comment by jaelim** [comment]
The problem is fixed. All is good.

**Comment by vrv** [comment]
Sorry, I didn't get a chance to look at this myself -- do you mind explaining what you did so others who run into the same problem might know the answer?

**Comment by jaelim** [comment]
Turns out, I had a wrong PYTHONPATH taking the first place, so it failed to find the correct module path. Here, I had this in the first place:

PYTHONPATH="${PYTHONPATH}:/home/pilotwarela0/Development/tensorflow"

The solution was to clear out this incorrect PYTHONPATH, then add the correct path again to the first place with this:

PYTHONPATH="${PYTHONPATH}:/usr/local/lib/python2.7/dist-packages/"
export PYTHONPATH

Make sure to check your path with this: echo $PYTHONPATH
