### ISSUE TITLE
Session crashed for an unknown reason

### ISSUE THREAD

**Issue by sta017** [tensorflow/tensorflow#26516]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
 
 import tensorflow as tf

- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
After installing tensorflow 2.0 in colab,  on executing command 'import tensorflow as tf', I get and error message "**Your session crashed for an unknown reason**."
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

    The code below is from the Colab tutorials for TF2.0 in Boosted Tree Models.

from __future__ import absolute_import, division, print_function
import numpy as np
import pandas as pd
from IPython.display import clear_output
!pip install tensorflow==2.0.0-alpha0
import tensorflow as tf
tf.random.set_seed(123)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Ayush517** [comment]
<img width="1680" alt="Screenshot 2019-03-10 at 5 21 16 PM" src="https://user-images.githubusercontent.com/31190928/54084615-ee8e5880-4358-11e9-98e9-224b1cda667d.png">
@sta017 The code you provided works correctly when I tried executing it.

**Comment by jvishnuvardhan** [comment]
As @Ayush517 mentioned, I don't see any issue? Only first line need to be updated as (from __future__ import absolute_import, division, print_function) shown in @Ayush517 screenshot. Thanks!

I am closing this issue as it was not related to build/Installation or Bug/performance. Please post this kind of support questions in Stackoverflow. Thanks!
