### ISSUE TITLE
Build Tensorflow 2.0 Alpha From Source

### ISSUE THREAD

**Issue by wf0312** [tensorflow/tensorflow#26519]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.14
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0 alpha
- Python version: 3.7.2
- Bazel version (if compiling from source): 0.20
- GCC/Compiler version (if compiling from source): Apple LLVM version 10.0.0 (clang-1000.10.44.4)
- CUDA/cuDNN version: No
- GPU model and memory: No

**Describe the problem**
Builded Tensorflow 2.0 Alpha from source but tf does not enable eager by default.
What should I do to enable eager by default

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build --config=opt --config=noaws --config=nohdfs --config=noignite --config=nokafka --config=nonccl --config=nogcp //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**

import tensorflow as tf
In[3]: tf.__version__
Out[3]: '2.0.0-alpha0'
tf.executing_eagerly()
Out[4]: False
a = tf.ones(shape=(3, 2))
a
Out[6]: <tf.Tensor 'ones:0' shape=(3, 2) dtype=float32>

**Comment by yongtang** [comment]
I haven't tried the 2.0 alpha version of the source code, but I remember you need to pass `--config=v2` to enable 2.0 for master branch.  Maybe you could pass `--config=v2` to give it a try?

**Comment by wf0312** [comment]
Thanks, it worked

**Comment by md-k-sarker** [comment]
Using `--config=v2` from master branch is building `1.13.1` version  `tensorflow-1.13.1-xxx.whl`. 
Build command: 
`bazel --output_base=$tf_deps/ \
 --config=v2 \
--copt="-O3" --copt="-g" -s -c opt \
//tensorflow/tools/pip_package:build_pip_package`

After installing it also shows 1.13.1 when using. `tf.__version__`

```
import tensorflow as tf
tf.__version__
1.13.1
```
