### ISSUE TITLE
tf.print() support of `sep` and `end` arguments

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#26510]
**System information**
- TensorFlow version (you are using):
tf.version.GIT_VERSION: 'v1.12.0-9807-ga86f6286b4'
tf.version.VERSION: '2.0.0-dev20190308'
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
Right now `tf.print()` does not support the `sep` and `end` arguments of Python's `print()` function.

**Will this change the current api? How?**
Yes, it will add two more optional arguments to the `tf.print()` function.

**Who will benefit with this feature?**
Everyone who wants to use `tf.print()` just as naturally as Python's `print()` function.

**Any Other info.**
The following code demonstrates how you could use this new feature to display progress during training:

```python
import tensorflow as tf

# Uncomment these lines to see the expected output
#tf.print = print
#tf.function = lambda f: f
#tf.range = range

@tf.function
def train(n_epochs, n_steps):
    for epoch in tf.range(1, n_epochs + 1):
        tf.print("Epoch ", epoch, "/", n_epochs, sep="")
        for step in tf.range(1, n_steps + 1):
            tf.print("\rStep ", step, "/", n_steps, sep="", end="")
            # ... training loop
        tf.print()

train(n_epochs=10, n_steps=10000)
```

The expected output looks like this:

```
Epoch 1/10
Step 10000/10000
Epoch 2/10
Step 10000/10000
Epoch 3/10
Step 10000/10000
Epoch 4/10
Step 10000/10000
Epoch 5/10
Step 10000/10000
Epoch 6/10
Step 578/10000   <= in progress
```

**Comment by ymodak** [comment]
Closing this issue since the PR has been merged. Tested against tf-nightly-2.0-preview (2.0.0-dev20190605). Thanks!
