### ISSUE TITLE
[TF 2.0 API Docs] tf.argsort

### ISSUE THREAD

**Issue by mandroid6** [tensorflow/tensorflow#26533]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version:  2.0
- Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/argsort

**Describe the documentation issue**

- **Usage example**
  No usage example is provided.

- **Visuals, if Applicable**
  No visuals are included.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by yashk2810** [comment]
It has a usage example now. I don't think it needs a visual. Closing because it seems fixed: https://www.tensorflow.org/api_docs/python/tf/argsort
