### ISSUE TITLE
[TF 2.0 API Docs] tf.math.argmin

### ISSUE THREAD

**Issue by mandroid6** [tensorflow/tensorflow#26532]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version:  2.0
- Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/argmin

**Describe the documentation issue**

- **Usage example**
  No usage example is provided.

- **Visuals, if Applicable**
  No visuals are included.

- **Raises listed and defined**
  No raises listed

Much like #26530, documentation for tf.math.argmin is created from a generated file ``python/ops/gen_math_ops.py``; a link to the file that generates ``python/ops/gen_math_ops.py`` would be handy for users.

Related files to be updated: ``tensorflow/core/api_def/base_api/api_def_ArgMin.pbtxt``, ``/tensorflow/core/ops/math_ops.cc``
**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by jvishnuvardhan** [comment]
@mandroid6 Could you combine This and six similar issues (you created) into one issue? We can close all those issues to reduce overhead for the developers. Thanks!

**Comment by jvishnuvardhan** [comment]
Here I am combining four more similar issues (#26534, #26535, #26537, and #26538) with this issue. I am closing the similar issue to reduce overhead on triaging similar issues. Thanks!

1. System information (#26534)

TensorFlow version: 2.0
Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/unstack

2. System information (#26535)

TensorFlow version: 2.0
Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/unique

3. System information (#26537)

TensorFlow version: 2.0
Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/zeros

4. System information (#26538)

TensorFlow version: 2.0
Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/zeros_initializer

Thanks!

**Comment by mihaimaruseac** [comment]
A part of the work on this enlarged issue has been done in #26540. @mandroid6 do you want to make a single PR with the rest of the documentation (`tf.unstack`, `tf.unique`, `tf.zeros`, `tf.zeros_initializer`) and then we can close this? Just to make sure we're not forgetting anything.

**Comment by mandroid6** [comment]
@mihaimaruseac yes will make a single PR for these documentation issues `` tf.unstack``,`` tf.unique``, ``tf.zeros``, ``tf.zeros_initializer`` and also ``tf.zeros_like``.

**Comment by mihaimaruseac** [comment]
@mandroid6 any new PRs for the rest of the issues?

**Comment by jvishnuvardhan** [comment]
I am closing this issue as docs for the four ops are updated in the TF website. Please feel free to reopen if I am mistaken. Thanks!
