### ISSUE TITLE
[TF 2.0 API Docs] tf.math.argmax

### ISSUE THREAD

**Issue by mandroid6** [tensorflow/tensorflow#26530]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version:  2.0
- Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/argmax

**Describe the documentation issue**

- **Usage example**
  No usage example is provided.

- **Visuals, if Applicable**
  No visuals are included.

- **Raises listed and defined**
  No raises listed

Much like #25802, documentation for tf.math.argmax is created from a generated file ``python/ops/gen_math_ops.py``; a link to the file that generates ``python/ops/gen_math_ops.py`` would be handy for users.

Related files to be updated: ``tensorflow/core/api_def/base_api/api_def_ArgMax.pbtxt``, ``/tensorflow/core/ops/math_ops.cc``
**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by jvishnuvardhan** [comment]
@mandroid6 Can you create single issue with all the similar modifications? It is too much overhead to work on 8 similar issues and it will be better for everyone (including you). Could you combine rest of the seven similar issues into one issue? Thanks!

**Comment by mandroid6** [comment]
@jvishnuvardhan Yes sure,my understanding was to create individual issues so that new GSoC students could easily pick them up as their first task 😃. 
Will combine them into a single issue by tomorrow!

**Comment by jvishnuvardhan** [comment]
@mandroid6 Are you going to create single issue? please let me know so that i can close other 8 similar issues. Thanks!

**Comment by mandroid6** [comment]
@jvishnuvardhan still waiting to combine them as new students have already started working on individual issues. Please wait till tomorrow. Thanks

**Comment by jvishnuvardhan** [comment]
@mandroid6 Thanks for your support.

**Comment by ParthS007** [comment]
@Mandar-Shinde Can I take reference from [here](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.argmax.html?highlight=argmax#numpy.argmax) for adding examples just like it is mentioned in this Issue - https://github.com/tensorflow/tensorflow/issues/25802

**Comment by mihaimaruseac** [comment]
Closing this in favor of #26532 as work has been done on #26540 for both this and that
