### ISSUE TITLE
[TF 2.0 API Docs] tf.zeros_like

### ISSUE THREAD

**Issue by mandroid6** [tensorflow/tensorflow#26539]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version:  2.0
- Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/zeros_like

**Describe the documentation issue**

- **Raises listed and defined**
  No raises listed

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by ParthS007** [comment]
@mandroid6 @jvishnuvardhan I want to work on this Issue. can you please help me get started with updating docs. Thanks

**Comment by mandroid6** [comment]
@ParthS007 yes sure. Just find the relevant py file and update the doc string in the *zeros_like* function. 

Also can you take up other similar issues which require docstring update, it would be helpful to have a single PR for them!

**Comment by jvishnuvardhan** [comment]
I agree with @mandroid6. I would be happy to see a single (mostly two) PR(s) to close these 8 similar issues. Thanks @ParthS007 .

**Comment by ParthS007** [comment]
okay @mandroid6 @jvishnuvardhan I am going through the Issues and will ask here if I face any difficulty.
Thanks for the responses. :+1:

**Comment by ParthS007** [comment]
@mandroid6 Do I have to make PR in this repo: https://github.com/tensorflow/docs

**Comment by jvishnuvardhan** [comment]
@ParthS007 Create a PR in TF/TF repo [here](https://github.com/tensorflow/tensorflow/pulls). Thanks!

**Comment by ParthS007** [comment]
okay @jvishnuvardhan, Will send a PR soon :+1:

**Comment by ParthS007** [comment]
@mandroid6 @jvishnuvardhan What I have to update exactly?
I have found the functions `zeros_like` is defined here - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py#L1876
What more should I add in the documentation?
Thanks for the help. :+1:

**Comment by mandroid6** [comment]
Update the docstring of the functions you need to improve the documentation
of.

**Comment by adammichaelwood** [comment]
`zeros_like` does not raise any errors directly, and we do not list transitive raises
