### ISSUE TITLE
CUDA_VISIBLE_DEVICES not working?

### ISSUE THREAD

**Issue by fancyerii** [tensorflow/tensorflow#2653]
gpu0 is used by other guys, So I want to use another gpu to run cifar10_train(cifar10_multi_gpu_train).
But it seems that tensorflow still try to use gpu0 even I specify CUDA_VISIBLE_DEVICES=2

$ CUDA_VISIBLE_DEVICES=2 python ~/tensorflow2/lib/python2.7/site-packages/tensorflow/models/image/cifar10/cifar10_train.py --data_dir ~/cifar10_data --train_dir ~/cifar10_train_gpu
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:08:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:08:00.0)
F tensorflow/stream_executor/cuda/cuda_dnn.cc:427] could not set cudnn filter descriptor: CUDNN_STATUS_BAD_PARAM
Aborted (core dumped)

$ nvidia-smi
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:04:00.0     Off |                  N/A |
| 32%   70C    P2   100W / 250W |  10135MiB / 12287MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:05:00.0     Off |                  N/A |
| 22%   41C    P0    73W / 250W |     23MiB / 12287MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 0000:08:00.0     Off |                  N/A |
| 22%   41C    P0    67W / 250W |     23MiB / 12287MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 0000:09:00.0     Off |                  N/A |
| 22%   42C    P0    74W / 250W |     23MiB / 12287MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX TIT...  Off  | 0000:84:00.0     Off |                  N/A |
| 22%   39C    P0    75W / 250W |     23MiB / 12287MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX TIT...  Off  | 0000:85:00.0     Off |                  N/A |
| 22%   39C    P0    69W / 250W |     23MiB / 12287MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX TIT...  Off  | 0000:88:00.0     Off |                  N/A |
| 22%   38C    P0    74W / 250W |     23MiB / 12287MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX TIT...  Off  | 0000:89:00.0     Off |                  N/A |
| 22%   38C    P0    69W / 250W |     23MiB / 12287MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      7266    C   /some/app       10111MiB

**Comment by fancyerii** [comment]
CUDA_VISIBLE_DEVICES is working but tensorflow still say "/gpu0".
see https://github.com/tensorflow/tensorflow/issues/2033
it works if I build tensorflow from source

**Comment by wenmin-wu** [comment]
I think tensorflow will automatically number the gpu form 0 to (NUM_CUDA_VISIBLE_DEVICES - 1). check the `pciBusID` of the GPU may be the correct option.
