### ISSUE TITLE
TensorFlow Official website tutorials error

### ISSUE THREAD

**Issue by flyingsalmon** [tensorflow/tensorflow#26531]
**System information**
- TensorFlow version:
- Doc Link: https://tensorflow.google.cn/tutorials/keras/basic_classification#preprocess_the_data

**Describe the documentation issue**
plt.show()  missing

**Comment by jvishnuvardhan** [comment]
@flyingsalmon I can see the following
plt.figure()
plt.imshow(train_images[0])
plt.colorbar()
plt.grid(False)
plt.show()

Could you remove cache and open again? Thanks!

**Comment by flyingsalmon** [comment]
@jvishnuvardhan I'm visiting the Chinese version, and can't see it.

**Comment by MarkDaoust** [comment]
Hi @flyingsalmon, 

Thanks for the report.

We try to keep these up to date.
But there is some lag on translation.

There's no extra action anyone needs to take for this.
This will be fixed when the translation is through the pipeline.
