### ISSUE TITLE
 ModuleNotFoundError: No module named 'tensorflow.compat.v2'

### ISSUE THREAD

**Issue by cpoptic** [tensorflow/tensorflow#26546]
Was going through the Jupyter notebook on TFP that was associated with the TF Dev Summit:

https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Probabilistic_Layers_Regression.ipynb
Run

Running the line 

`import tensorflow.compat.v2 as tf`

Returns the error:

> ModuleNotFoundError: No module named 'tensorflow.compat.v2'

Running tf.VERSION shows it's 1.13. 

I'm assuming this is related to not having TF 2.0 installed, and only having T 1.13 installed.
Is a separate, 2nd installation of TF (2.0) needed to import tensorflow.compat.v2 or can both be installed into the same virtual environment?

Just want to make sure installing both alongside each other won't break either or both.

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

> b'unknown' 1.13.1

**Comment by jvishnuvardhan** [comment]
@cpoptic Could you try changing "v2" to "v1". Like
import tensorflow.compat.v1 as tf

It worked for me. Please let us know how it progresses. We will correct the typo. Thanks!

**Comment by cpoptic** [comment]
Yes that works, but the issue is with the tensorflow_probability

```
# import tensorflow.compat.v2 as tf
import tensorflow.compat.v1 as tf
import tensorflow_probability as tfp

tf.enable_v2_behavior()
```

> 
AttributeError: module 'tensorflow.compat' has no attribute 'v2'


> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-6713d3750cfa> in <module>
     17 # import tensorflow.compat.v2 as tf
     18 import tensorflow.compat.v1 as tf
---> 19 import tensorflow_probability as tfp
     20 
     21 tf.enable_v2_behavior()

/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_probability/__init__.py in <module>
     76 
     77 # from tensorflow_probability.google import staging  # DisableOnExport
---> 78 from tensorflow_probability.python import *  # pylint: disable=wildcard-import
     79 from tensorflow_probability.python.version import __version__
     80 # pylint: enable=g-import-not-at-top

/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_probability/python/__init__.py in <module>
     27 from tensorflow_probability.python import mcmc
     28 from tensorflow_probability.python import monte_carlo
---> 29 from tensorflow_probability.python import optimizer
     30 from tensorflow_probability.python import positive_semidefinite_kernels
     31 from tensorflow_probability.python import stats

/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_probability/python/optimizer/__init__.py in <module>
     28 from tensorflow_probability.python.optimizer.proximal_hessian_sparse import minimize as proximal_hessian_sparse_minimize
     29 from tensorflow_probability.python.optimizer.proximal_hessian_sparse import minimize_one_step as proximal_hessian_sparse_one_step
---> 30 from tensorflow_probability.python.optimizer.sgld import StochasticGradientLangevinDynamics
     31 from tensorflow_probability.python.optimizer.variational_sgd import VariationalSGD
     32 

/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_probability/python/optimizer/sgld.py in <module>
     32 
     33 
---> 34 class StochasticGradientLangevinDynamics(tf.compat.v2.optimizers.Optimizer):
     35   """An optimizer module for stochastic gradient Langevin dynamics.
     36 

AttributeError: module 'tensorflow.compat' has no attribute 'v2'

**Comment by joyalbin** [comment]
@cpoptic just want to add my observation here,
in my understanding `tensorflow-probability` is not installed along with `tensorflow`.
Could please try with your test script after installing `pip install --user --upgrade tensorflow-probability`
Hope this will help you

**Comment by cpoptic** [comment]
Yes I ran   pip install tensorflow and pip install tensorflow-probability
 separately
So I'm double sure they are both installed

**Comment by joyalbin** [comment]
@cpoptic  Can you please check in which path` tensorflow-probability` got installed and that python path only is used?

**Comment by samiratzn** [comment]
is this problem solved? please help I faced the same error.

**Comment by met45** [comment]
I am having the same error as well

**Comment by salml** [comment]
I am having the same error.

**Comment by jonjo442** [comment]
Had the same issue, if you cloned the github repo, make sure to checkout the v0.6.0-rc1 tag to run the examples with the 0.6.0 version from pip. I guess the examples in master is made to work with tf2.
Works for me at least..

**Comment by miguelmorin** [comment]
I don't have that issue with TensorFlow 1.13 and this installation of probability:

```bash
git clone -b r0.6 --single-branch git@github.com:tensorflow/probability.git
```

**Comment by jvishnuvardhan** [comment]
@cpoptic Can you follow the suggestion by @jonjo442 and let us know whether your issue resolved or not. thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Comment by s4sarath** [comment]
ModuleNotFoundError: No module named 'tensorflow.compat.v2' , it is still there. tf probability version is 0.6 and tensorflow version is 1.13

**Comment by s4sarath** [comment]
ModuleNotFoundError: No module named 'tensorflow.compat.v2' , it is still there. tf probability version is 0.6 and tensorflow version is 1.13

**Comment by sehargul-123** [comment]
i have installed tensorflow==1.8.0, i have to run a file in order to star my training. but I am getting this error.
ModuleNotFoundError: No module named 'tensorflow.compat' 
then i wrote this command "pip install tensorflow.compat" i got following error
ERROR: Could not find a version that satisfies the requirement tensorflow.compat (from versions: none)
ERROR: No matching distribution found for tensorflow.compat

**Comment by MarkDaoust** [comment]
Hi Everyone, 

When this was published, it required tf-nightly or any of preview releases of tensorflow
-2.0. That was the original source of confusion.

The tf.compat.v2 module was added in 1.14. Upgrade to 1.14 , 1.15, or 2.0  and this will work fine.

```
pip install -U "tensorflow==1.15" 
pip install -U "tensorflow==2.0" 
```
There is absolutely no way to run it with 1.13, or 1.8, sorry!

**Comment by nstamen0vah** [comment]
> i have installed tensorflow==1.8.0, i have to run a file in order to star my training. but I am getting this error.
> ModuleNotFoundError: No module named 'tensorflow.compat'
> then i wrote this command "pip install tensorflow.compat" i got following error
> ERROR: Could not find a version that satisfies the requirement tensorflow.compat (from versions: none)
> ERROR: No matching distribution found for tensorflow.compat

I am getting the same error when importing tensorflow.compat.v1 as tf. Any further suggestions as I would like to use tensorflow==1.8.0?

**Comment by himanshisyadav** [comment]
I have tensorflow 1.4.0 with Cuda 8 and cudnn 7. And I get the following error. 

`    import tensorflow.compat.v1 as tf
ImportError: No module named 'tensorflow.compat'
`

After installing `tensorflow-probability`, I still get the same error.

**Comment by MarkDaoust** [comment]
@himanshisyadav upgrade to at least TF 1.14.

**Comment by himanshisyadav** [comment]
@MarkDaoust I looked the tensorflow_gpu version for CUDA 8 and CudNN 7 and it was 1.4.1. Now, I am getting a bunch of warnings and the script won't run. 

Why should I upgrade 1.14?

**Comment by himanshisyadav** [comment]
@MarkDaoust I fixed it by install tf-nightly-gpu.

**Comment by Cesarcuna** [comment]
If your problem is with RASA CORE, in my case, I executed the following commands:
pip install -U tensorflow==1.15 
pip install -U tensorflow==2.0 
pip install -U gast==0.3.3
pip install -U tf-nightly-gpu
pip install -U tensorboard==1.15.0
pip install -U tensorflow==1.15

**Comment by rychter** [comment]
@MarkDaoust  

> pip install -U "tensorflow==2.0"

  <- worked for me

**Comment by Roc-J** [comment]
pip install -U "tensorflow==2.0" is ok

**Comment by SharadSirsat** [comment]
I am facing an issue with module not found error "tf.compat.v1" for this. I have Tensorflow version1.14 installed. I did pip un-install TensorFlow & installed it again..same did with tensorflow_estimator and tensorflow_probability.

**Comment by csingh27** [comment]
Still have the issue

**Comment by MarkDaoust** [comment]
One common way to get stuck in a particular tensorflow version is to have an old version of python or pip.

If you try to install a specific version and it fails then check your python and pip versions.

```
pip install -U "tensorflow==1.15.*"
pip install -U "tensorflow==2.2.*"
```

`pip install tensorflow` only gets you the latest version if those are up to date.

**Comment by aimalrehman92** [comment]
> I am facing an issue with module not found error "tf.compat.v1" for this. I have Tensorflow version1.14 installed. I did pip un-install TensorFlow & installed it again..same did with tensorflow_estimator and tensorflow_probability.

@SharadSirsat did this work as a solution to  "tensorflow.compat.v1"  or are you saying that the problem exists even when you reinstalled TF?

**Comment by jaihonikhil** [comment]
`!pip install -U "tensorflow==2.0" `

I was facing similar issues but this solved the problem for me. Thanks!

**Comment by Genius-farmer** [comment]
I followed the steps above. However, I am still getting error.

I cannot upgrade tensorflow==2.0 due to my project requirements. 
I can only use tensorflow==1.14.0 , tensorflow-gpu==1.5.0

I am getting
`ModuleNotFoundError: No module named 'tensorflow.compat'`

How do I go about solving it?

**Comment by userdarius** [comment]
Same here

**Comment by Ananyapam7** [comment]
Idk if this is solved or not, but upgrading to tensorflow 2.0 solved the issue for me.

**Comment by diman82** [comment]
Solution: https://github.com/tensorflow/tensorflow/issues/38800#issuecomment-660535430

**Comment by marwazaa** [comment]
@cpoptic @miguelmorin I have the same problem with tensorflow 1.13.1, please how i can fix it

**Comment by miguelmorin** [comment]
@marwazaa I no longer use TensorFlow, sorry. Can you try the latest version of TensorFlow, or at least version 2?

**Comment by CL500Coupe** [comment]
I'm getting error with: import tensorflow.compat.v2 as tf

**Comment by Roc-J** [comment]
你的来信已收到，谢谢！

**Comment by MatchaCookies** [comment]
> I followed the steps above. However, I am still getting error.
> 
> I cannot upgrade tensorflow==2.0 due to my project requirements. I can only use tensorflow==1.14.0 , tensorflow-gpu==1.5.0
> 
> I am getting `ModuleNotFoundError: No module named 'tensorflow.compat'`
> 
> How do I go about solving isa

> I followed the steps above. However, I am still getting error.
> 
> I cannot upgrade tensorflow==2.0 due to my project requirements. I can only use tensorflow==1.14.0 , tensorflow-gpu==1.5.0
> 
> I am getting `ModuleNotFoundError: No module named 'tensorflow.compat'`
> 
> How do I go about solving it?

same situation. I can only use tensorflow==1.4
did you solve it?

**Comment by Roc-J** [comment]
你的来信已收到，谢谢！

**Comment by ZamirKhurshid** [comment]
I have changed with import tensorflow.compat.v2 as tf v2 to vi as wll but it not work 
ModuleNotFoundError: No module named 'tensorflow.compat'

**Comment by Roc-J** [comment]
你的来信已收到，谢谢！

**Comment by zkb2001** [comment]
I use:
import tensorflow.v2.feature_column as fc

then it works

**Comment by Roc-J** [comment]
你的来信已收到，谢谢！
