### ISSUE TITLE
Timing hook giving wrong execution time

### ISSUE THREAD

**Issue by anirbankonar123** [tensorflow/tensorflow#26544]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google colab env
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): !pip3 install -U tensorflow-gpu==2.0.0-alpha0
- TensorFlow version (use command below): 2.0.0-alpha0
- Python version:3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

Timing hook is showing the training time as 12.11 sec, whereas elapsed time from python by getting time info before and after the step is : 70.4 sec

Timing hook and elapsed time should be same within a limit
[Fashion_mnist_estimators.zip](https://github.com/tensorflow/tensorflow/files/2949587/Fashion_mnist_estimators.zip)

**Code to reproduce the issue**
Attached ehere

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@anirbankonar123 Please check it again with a Stopwatch. On my Mac it took 85.64 sec and it was correct as my stopwatch showed 87 sec. 
Please post these kind of support questions in stackoverflow. Thanks!

**Comment by anirbankonar123** [comment]
As I mentioned, I hv checked number of times, time given by Time hook is
much less than elapsed time rpted by time lib of python. The variation is
significant. Its a bug.

its not something for stackoverflow, as i am not getting stuck up in a
syntax, or dnt know how to use something.

Thanks,
Anirban

**Comment by jvishnuvardhan** [comment]
@anirbankonar123 Could you provide a link to the file as you shared in other issue? Thanks!

**Comment by anirbankonar123** [comment]
Sure, heres the link
https://colab.research.google.com/drive/1_F13vQd_G_imOyrVtO7Sauw7O9tQvoWM

Thanks
