### ISSUE TITLE
Unable to install on Raspbian Stretch with Virtual Environments

### ISSUE THREAD

**Issue by GuidoBartoli** [tensorflow/tensorflow#26551]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian Stretch Lite
- TensorFlow installed from (source or binary): using `pip` 
- TensorFlow version: 1.12
- Python version: 2.7
- Installed using virtualenv? pip? conda?: `virtualenv`

**Describe the problem**
I wanted to install Tensorflow for Python 2.7 over a clean install of Raspbian Stretch Lite on Raspberry Pi 3 B+, these are the steps I followed before encountering the problem:

1. `sudo apt-get update && sudo apt-get upgrade`
1. `wget https://bootstrap.pypa.io/get-pip.py`
1. `sudo python3 get-pip.py`
1. `sudo pip install virtualenv virtualenvwrapper`
1. `nano ~/.bashrc` (_add standard paths for virtualenvs_)
1. `source .bashrc`
1. `mkvirtualenv tf -p python2`
1. `sudo apt-get install libhdf5-serial-dev libopenblas-dev liblapack-dev libeigen3-dev python-dev`
1. `pip install tensorflow`
`  Could not find a version that satisfies the requirement tensorflow (from versions: )`
`No matching distribution found for tensorflow`

Any idea why it did not find the Tensorflow package? Isn't `(from versions: )` strange since it should detect the installed Python?

Many thanks

**UPDATE**: I tried also creating a Python 3 virtual environment and repeat the installation, but I receive the same error

**Comment by petewarden** [comment]
This seems like a virtualenv issue, since the pip works otherwise, so I don't think we can help on this unfortunately.
