### ISSUE TITLE
tf-2.0.0-alpha0 bazel build failure in Docker - Extension file not found. Unable to load package for '//tensorflow:version_check.bzl':

### ISSUE THREAD

**Issue by LGTrader** [tensorflow/tensorflow#26553]
**System information**
- Linux Ubuntu 18.04.2 LTS:
- TensorFlow installed from tar.gz source file
- TensorFlow version: 2.0.0.alpha0
- Python version: 3.5.2 (provided in Docker image)
- Build inside Docker container (https://www.tensorflow.org/install/source#gpu_support_2)
- Bazel version - 0.19.2 (provided in docker image)
- GCC/Compiler version (if compiling from source): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)  (provided in docker image)
- CUDA/cuDNN version: /usr/local/cuda-10.0 (provided in docker image)
- GPU model and memory: i7 980x  - no AVX instruction set so building locally with GPU support

**Describe the problem**
The bazel build step fails with the following messages:

root@67e84911cbdf:/tensorflow# bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Repository rule 'build_bazel_rules_swift' returned: {"remote": "https://github.com/bazelbuild/rules_swift.git", "commit": "001736d056d7eae20f1f4da41bc9e6f036857296", "shallow_since": "2019-01-18", "init_submodules": False, "verbose": False, "strip_prefix": "", "patches": [], "patch_tool": "patch", "patch_args": ["-p0"], "patch_cmds": [], "name": "build_bazel_rules_swift"}
ERROR: error loading package '': Extension file not found. Unable to load package for '//tensorflow:version_check.bzl': BUILD file not found on package path
ERROR: error loading package '': Extension file not found. Unable to load package for '//tensorflow:version_check.bzl': BUILD file not found on package path
INFO: Elapsed time: 8.103s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
root@67e84911cbdf:

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Following the instructions here: https://www.tensorflow.org/install/source#gpu_support_2

NOTE: These instructions work fine for the included tf-1.12 source and I've used them with a different Docker image for tf-1.13/

1) Start a Docker container using this command to mount a tf-2.0.0 directory within Docker

docker run --runtime=nvidia -it -w /tensorflow -v /home/mark/Docker_Run:/mnt -v /home/mark/CODE/tensorflow-2.0.0-alpha0:/tensorflow_source -e HOST_PERMS="$(id -u):$(id -g)"     tensorflow/tensorflow:devel-gpu-py3 bash

This image provides python-3.5.2, bazel-0.19.2 & cuda-10. It has a /tensorflow_src directory with tf-1.12 and nothing in the /tensorflow directory.

2) Copy the tf-2.0.0-alpha0 code from the external mounted /tensorflow_source directory into the internal /tensorflow directory:

rm -rf /tensorflow
mkdir /tensorflow
cp -R /tensorflow_source/. /tensorflow

3) Run the configure step accepting all default values

cd /tensorflow
./configure

4) Run the bazel build step which fails with the message above.

NOTE: I've looked at a lot of Docker images and felt this one had the right stuff other than the alpha0 tensorflow codebase. If there's a better docker image or a better way to get the alpha0 code into the Docker image than mounting it outside of Docker please advise.

**Comment by xinyuwl** [comment]
When I compiled tensorflow2.0-alpha0 with the source code in conda, I encountered the same problem with the following error message. 

Loading: 
Loading: 0 packages loaded
ERROR: error loading package '': Encountered error while reading extension file 'swift/repositories.bzl': no such package '@build_bazel_rules_swift//swift': Traceback (most recent call last):
	File "/home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/bazel_tools/tools/build_defs/repo/git.bzl", line 166
		_clone_or_update(ctx)
	File "/home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/bazel_tools/tools/build_defs/repo/git.bzl", line 72, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
error cloning build_bazel_rules_swift:
+ cd /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external
+ rm -rf /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/build_bazel_rules_swift /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/build_bazel_rules_swift
+ git clone --depth=1 https://github.com/bazelbuild/rules_swift.git /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/build_bazel_rules_swift
+ git -C /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/build_bazel_rules_swift reset --hard tags/0.6.0
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/build_bazel_rules_swift fetch --depth=1 origin tags/0.6.0:tags/0.6.0
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/build_bazel_rules_swift fetch origin tags/0.6.0:tags/0.6.0
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
ERROR: error loading package '': Encountered error while reading extension file 'swift/repositories.bzl': no such package '@build_bazel_rules_swift//swift': Traceback (most recent call last):
	File "/home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/bazel_tools/tools/build_defs/repo/git.bzl", line 166
		_clone_or_update(ctx)
	File "/home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/bazel_tools/tools/build_defs/repo/git.bzl", line 72, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
error cloning build_bazel_rules_swift:
+ cd /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external
+ rm -rf /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/build_bazel_rules_swift /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/build_bazel_rules_swift
+ git clone --depth=1 https://github.com/bazelbuild/rules_swift.git /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/build_bazel_rules_swift
+ git -C /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/build_bazel_rules_swift reset --hard tags/0.6.0
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/build_bazel_rules_swift fetch --depth=1 origin tags/0.6.0:tags/0.6.0
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /home/wangli/.cache/bazel/_bazel_wangli/4e43e44ac24356d1161b2a510501b361/external/build_bazel_rules_swift fetch origin tags/0.6.0:tags/0.6.0
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
INFO: Elapsed time: 7.566s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (0 packages loaded)


And System information
Linux centos 7:
TensorFlow version: 2.0.0.alpha0
Python version: 3.6
Bazel version - 0.19.2 (provided in docker image)
GCC/Compiler version 4.8

Compile only the pure CPU version, using the compile command:
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
--

**Comment by tfboyd** [comment]
ping @angersson

**Comment by tfboyd** [comment]
Can you (austin) verify the build works on the image, if needed we can escalate to the GPU team to get a clear ownership.

**Comment by angersson** [comment]
Thanks for the ping, I missed this. I'm testing the builds now, but it'll take a while to get results.

**Comment by angersson** [comment]
@tfboyd @goldiegadde This seems like a use case for the development docker images I didn't plan for. I can't build the released 2.0 source because our latest `devel` image has a version of Bazel that is too new (the `devel` images, which are built nightly, were only planned to support building from master).

So I can't build from the 2.0.0 alpha release's source code, but the latest `devel` image does build the included source code as well as the current master after a `git pull`. I can also build the `r2.0` branch with no problem, so this... *seems* like WAI, although this issue indicates that the availability of the source code may be confusing.

**Comment by LGTrader** [comment]
Austin,
   First, thanks for your efforts.

   Second, before you move on could you possibly clarify a couple of things?

1) When you say 'the latest devel image does build the included source code
as well as the current master after a git pull'is this inside a Docker
image with GPU support? For my needs I can use any r2.0 version with GPU
support. What docker image and what git pull commands so that I can
duplicate here.

2) I have managed to build r2.0-alpha without GPU support outside of Docker
using just regular Kubuntu and Python-3.6 and bazel-0.23.0 using

git clone https://github.com/tensorflow/tensorflow.git -b r2.0
--single-branch

and then generally following the instructions on the tensorflow website. I
don't know if it functions correctly yet. I will be attempting to add GPU
support later this week.

   Any info you can poss on about getting the right Docker image and
getting it updated to duplicate your results would be appreciated.

Thanks,
Mark
