### ISSUE TITLE
Does "TensorFlow-experimental" has a new version for iOS?  

### ISSUE THREAD

**Issue by yaoliangjun** [tensorflow/tensorflow#26555]
"TensorFlow-experimental" pod's version now is 1.1.1，I need a new version to match the latest source code, and how can I build a "TensorFlow-experimental" framework?

**Comment by yyoon** [comment]
This is an old issue, and hopefully you've figured it out already, but let me close the loop here.

The new standard way of using TensorFlow on iOS is via `TensorFlowLiteSwift` / `TensorFlowLiteObjC` pods. Please refer to the official [iOS quickstart guide](https://www.tensorflow.org/lite/guide/ios).
