### ISSUE TITLE
[1.13] Incomplete information in the warning message on using tf.contrib.predictor

### ISSUE THREAD

**Issue by suyash** [tensorflow/tensorflow#26579]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.13.1
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/contrib/predictor/from_saved_model https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/saved_model/load https://www.tensorflow.org/alpha/guide/keras/saving_and_serializing

**Describe the documentation issue**

On using `tf.contrib.predictor.from_saved_model` to get predictions from a saved_model, the warning message says that there _will_ be a new function to load saved models in TensorFlow 2.0, and nothing else.

Specifically, consider the following snippet of code (from https://colab.research.google.com/github/suyash/transformer/blob/master/imdb_sentiment_demo.ipynb)

```py
p = predictor.from_saved_model(
    export_dir, 
    input_names={"input_text": "input_text:0"}, 
    output_names={
        "prediction": "dense/Softmax:0",
        "attention_0": "attention/attention_weights:0",
        "attention_1": "attention_1/attention_weights:0",
    },
)
outputs = p({"input_text": inputs})
print(outputs["prediction"])
print(outputs["attention_0"])
print(outputs["attention_1"])
```

This prints the following warning message

```
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/predictor/saved_model_predictor.py:153: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
```

I have trying to figure out extracting multiple outputs from the same saved model. The current guide for saved models at alpha (https://www.tensorflow.org/alpha/guide/keras/saving_and_serializing) does not provide information on loading, while the equivalent for stable (https://www.tensorflow.org/guide/saved_model) does.

I am trying to use the new `tf.saved_model.load` function. I have prepared a demo for my use-case at https://colab.research.google.com/gist/suyash/2c7e5b77ea4d94d5c3b8c3e178d06878. Specifically, I create a model with dense layers, convert it to an estimator, trained it while defining an `Exporter` for evaluation checkpoints.

Now, when I load using the new function, I am able to obtain values for the `dense_2` tensor, however in an equivalent scenario, how do I get the values of the `dense_1` tensor in the current approach. As I show in my predictor example, the output of the predictor will have 3 keys, "prediction", "attention_0" and "attention_1". How do I get the output of the "dense_1" tensor in my 2.0 example?

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by ymodak** [comment]
@allenlavoie Can you PTAL? Thanks!

**Comment by allenlavoie** [comment]
So basically you want to fetch an intermediate Tensor? The loaded signatures do have a .prune method which takes input and output Tensors from the function graph and gives you a new function (`signature_function.graph` will get to the Tensor objects).

The documentation for prune() should be improved; it needs a docstring and should probably take Tensor names instead of just Tensors. And we should add a pointer to the 2.x guide to the contrib predictor depreciation warning.

**Comment by suyash** [comment]
@allenlavoie I am not seeing anything about a prune method [on the documentation page for tf.saved_model.load](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/saved_model/load), where can I find that. Is there also some place I can find equivalent 2.x code for fetching intermediate values from saved_models.

**Comment by jvishnuvardhan** [comment]
@suyash I think this was resolved already. I see the prune method mentioned almost in the end of [this page](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/saved_model/load). 

I am closing this issue. Please feel free to reopen if I am mistaken. Thanks!
