### ISSUE TITLE
CPU int8 inference

### ISSUE THREAD

**Issue by vignesh-irtt** [tensorflow/tensorflow#26571]
Ubuntu 16.04
- TensorFlow version (you are using):1.12
- Are you willing to contribute it (Yes/No):No

**Describe the feature and the current behavior/state.** When will conv layer support **int8** in **cpu**

**Will this change the current api? How?** Add int8 datatype

**Who will benefit with this feature?** Inference time will be reduced in cnn models

**Any Other info.**

**Comment by Leslie-Fang** [comment]
I think the TF build wheel with mkldnn on the TF main page already support INT8 inference on CPU

**Comment by tanzhenyu** [comment]
According to the above comment seems it's fixed.
