### ISSUE TITLE
SparseTensor takes ages to initialize and can not be saved independently

### ISSUE THREAD

**Issue by SumNeuron** [tensorflow/tensorflow#26576]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): sorta
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.11
- Python version: 3.5
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 9
- GPU model and memory: Titan 

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

It takes a while for me to generate a `SparseTensor`

```python
# dense is an n x m matrix

sparse = coo_matrix(dense) # almost instantaneous 

# for legibility
sparse_indicies = list(zip(
    sparse.row.astype(np.int64).tolist(), 
    sparse.col.astype(np.int64).tolist()
)) # almost instantaneous

type_casted = (sparse.data).astype(np.float32) # almost instantaneous

# takes ages (ok it takes several minutes...)
input_tensor = tf.SparseTensor(
    indices     = sparse_indicies,
    values      = type_casted,
    dense_shape = sparse.shape
) 

# save to file so I can load it to memory locally if it exists.

```

How can I save it just by itself? I have tried pickle and npy without success.

```python
import pickle, numpy as np

filename = os.path.expanduser('~/tmp/test.tmp')

with open(fn, 'wb') as f:
    pickle.dump(input_tensor, f)
    # throws "TypeError: can't pickle _thread.RLock objects"


np.save(fn, input_tensor)
# throws "TypeError: can't pickle _thread.RLock objects"


```

**Describe the expected behavior**

either SparseTensor should be more performant in initialization or should be saveable as a pickle object so I don't always have to re-initialize it

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
(see above)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by SumNeuron** [comment]
sparse.shape is modest in size (200,000 x 50,000)

**Comment by ebrevdo** [comment]
This is expensive probably because it's creating a protobuf representation of the constant sparse tensor values and storing that constant in the graph.

It depends on what you're trying to do.  for examle, you could create a tf.sparse_placeholder instead of a SparseTensor, serialize your indices values etc in pure python/numpy, and feed them to a tensorflow graph via the `session.run(..., feed_dict={my_sparse_placeholder: tf.SparseTensorValue(numpy_arrays)})`

**Comment by mohantym** [comment]
Hi @SumNeuron ! we are  checking to see if you are still looking for assistance in this issue.
Could you please try on latest stable version of  TF 2.6  and let us know if this is still an issue.Thanks!
