### ISSUE TITLE
Pip No matching distribution found for tensorflow-gpu==2.0.0-alpha0

### ISSUE THREAD

**Issue by JamesQFreeman** [tensorflow/tensorflow#26578]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by JamesQFreeman** [comment]
pip install -U --pre tensorflow-gpu==2.0.0-alpha0

Then I got these:

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting tensorflow-gpu==2.0.0-alpha0
  Could not find a version that satisfies the requirement tensorflow-gpu==2.0.0-alpha0 (from versions: 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0, 1.13.1)
No matching distribution found for tensorflow-gpu==2.0.0-alpha0

**Comment by akshoop** [comment]
When I encountered a similar sounding error, I realized my problem was that I had Python 3.7.2 (32-bit) installed.

You need to have installed Python 3.7.2 **(64-bit)** in order to execute `pip install tensorflow==2.0.0-alpha0`

Hope this helps.

**Comment by JamesQFreeman** [comment]
Thanks, I think I was running 64-bit version python37.
However, I solved it by directly download and install .whl file from https://pypi.org/project/tensorflow-gpu/2.0.0a0/#files

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if have any further problems. Thanks!

**Comment by lgggy** [comment]
After
```
pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade tensorflow-gpu==2.0.0
```
I got
```
No matching distribution found for tensorflow-gpu==2.0.0
```
and I can see `2.0.0a0, 2.0.0b0, 2.0.0b1` is available.
My Python3 version is 3.6.8.

Because some days ago, I've already install tensorflow(cpu) in my windows PC, and tf.__version__ is 2.0.0, and I want to install tensorflow-gpu in my linux server, if I choose to install tensorflow-gpu==2.0.0a0, it will show that tf.__version__ is 2.0.0-alpha0.

I want to know if my pip3 instruction was wrong.
Thanks a lot.

**Comment by mihaimaruseac** [comment]
`python -m pip install --upgrade pip`.

**Comment by ividal** [comment]
> `python -m pip install --upgrade pip`.

This did it for me; pip later was able to see tf 2.0.0. (FTR using python 3.6.8 on ubuntu 18.04.)

**Comment by lgggy** [comment]
Thanks a lot. Finally, I uninstalled my python 2.0, and use the similar instruction above(aims to upgrade my pip) to solve my problem.

**Comment by Mithun-MK** [comment]
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.0.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-gpu==2.0.0


"any thing could be done for this error?"

**Comment by mihaimaruseac** [comment]
> `python -m pip install --upgrade pip`.

(https://github.com/tensorflow/tensorflow/issues/26578#issuecomment-543286872)

Please read previous replies. Please note that we are not yet releasing python 3.8 pip. Please note that we don't release pip for python interpreters running on 32 bits. Please note that `pip debug --verbose` gives you a list of tags of pips that can be installed and you can check on pypi if those tags are present for the package.

If none of the above help, please open a new issue, filling in the template

**Comment by sergiosdev** [comment]
#Win Python 3.6.0
python -m pip install --upgrade tensorflow-gpu

**Comment by sergiosdev** [comment]
python -m pip install tensorflow==2.0

**Comment by a3diti** [comment]
Some people might have issue related to having a **mac** and using old version of `tensorflow` or `tensorflow-gpu` as found here https://github.com/tensorflow/tensorflow/issues/8251#issuecomment-617080152

**Comment by mihaimaruseac** [comment]
There is no GPU for mac
