### ISSUE TITLE
Tensorflow Lite Java Interpreter methods throw Exceptions, but this is not in the method declaration

### ISSUE THREAD

**Issue by joepmoritz** [tensorflow/tensorflow#26584]
Methods such as `Interpreter.run` throw Java exceptions originating from native, but the method declaration does not include `throws Exception`. It would be helpful to beginners to include this. Thanks!

**Comment by ymodak** [comment]
I see that it this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>


**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):



**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by joepmoritz** [comment]
**System information**

TensorFlow version (you are using): 1.13.1
Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

The current Tensorflow Lite Java API does not declare that `Interpreter.run` can throw exceptions. However, the underlying code does throw exceptions, often containing useful debug information. If a call to `Interpreter.run` is not wrapped in a try/catch block, any exception thrown will cause the thread to break silently (seen on Android), making this difficult to debug.

This feature request asks for `Interpreter.run` to correctly declare which exceptions it can possibly throw. This likely involves similar fixes in the `NativeInterpreterWrapper` class.

**Will this change the current api? How?**

Yes, as mentioned above.

**Who will benefit with this feature?**

This will affect code where calls to `Interpreter.run` have not been wrapped in a try/catch block. This will result in a compiler error, notifying the programmer that it is a good idea to add a try/catch block and log any error message. This can help them find future errors more easily.

The Android example in the Tensorflow Github repository does not use a try/catch block (and I consider that a *bad* idea).

Any Other info.

**Comment by jdduke** [comment]
@lu-wang-g and @xunkai55 , would one of you mind taking a pass at improving the documentation here? Thanks!

**Comment by lu-wang-g** [comment]
No problem. I'll take a look at that.

**Comment by lu-wang-g** [comment]
@joepmoritz The public APIs in Interpreter.java have been documented with exceptions in a recent code change. None of those exceptions are checked exceptions, therefore they are not declared in the method declaration. Feel free to let us know if you have any comments. Thanks!
