### ISSUE TITLE
module 'tensorflow' has no attribute 'zeroes' in Graph guide

### ISSUE THREAD

**Issue by tcl326** [tensorflow/tensorflow#26588]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.12.0
- Doc Link: https://www.tensorflow.org/guide/graphs

**Describe the documentation issue**

On the documentation an example was given using tf.zeroes().

However, the module 'tensorflow' has no attribute 'zeroes'. 

```
with tf.device("/job:ps/task:0"):
  weights_1 = tf.Variable(tf.truncated_normal([784, 100]))
  biases_1 = tf.Variable(tf.zeroes([100]))

with tf.device("/job:ps/task:1"):
  weights_2 = tf.Variable(tf.truncated_normal([100, 10]))
  biases_2 = tf.Variable(tf.zeroes([10]))

with tf.device("/job:worker"):
  layer_1 = tf.matmul(train_batch, weights_1) + biases_1
  layer_2 = tf.matmul(train_batch, weights_2) + biases_2
```
The documentation should use tf.zeros() instead

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
yes

**Comment by pymit** [comment]
https://github.com/tensorflow/docs/pull/383
