### ISSUE TITLE
Getting error - "tf.gfile.Stat()" gets result that "file does not exist", but it does exists

### ISSUE THREAD

**Issue by helenykwang** [tensorflow/tensorflow#26598]
There are files in "neg" directory:
In [81]: tf.gfile.ListDirectory("s3://lookalike-sample/novel_user/ds=20190310/neg")
Out[81]:
['_SUCCESS',
 'part-00002.gz',
 'part-00003.gz',
 'part-00004.gz']

But when I input:
tf.gfile.Stat("s3://lookalike-sample/novel_user/ds=20190310/neg/part-00002.gz")

getting error:
NotFoundError: Object s3://lookalike-sample/novel_user/ds=20190310/neg/part-00002.gz does not exist

- OS Platform and Distribution ( Linux Ubuntu 16.04):
- TensorFlow version 1.8.0
- Python version:2.7.4

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
