### ISSUE TITLE
from tensorflow.contrib import layers -> Cannot import name autograph

### ISSUE THREAD

**Issue by jcrevoisier** [tensorflow/tensorflow#26599]
'from tensorflow.contrib import layers'

This simple line ends up with the following error : ImportError: cannot import name autograph

Why ?

**Comment by pymit** [comment]
https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md

**Comment by ymodak** [comment]
@jcrevoisier What version of TF are you using? Can you switch to TF 1.12 or TF 1.13.1?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by miladnoori1996** [comment]
hey @ymodak, im using TF 1.13 on a nvidia xavier trying top get better performance from my image segmentation model implemented in keras. when importing tensorflow.contrib it gives me the same ERROR "cannot import name autograph"

**Comment by tenshis** [comment]
Did you solve it? I'm having the same issue

**Comment by ymodak** [comment]
@tenshis @miladnoori1996  Please post a new issue and provide all information asked by the template. Thanks!
