### ISSUE TITLE
Writing to S3 fails occasionally

### ISSUE THREAD

**Issue by terrykong** [tensorflow/tensorflow#26597]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
ubuntu 16.04 (docker)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
pip installed into docker image
- TensorFlow version (use command below):
1.12.0-gpu
- Python version:
3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Occasionally when I write to an S3 file like so:
```python
def s3_print(*args,**kwargs):
    with tf.gfile.GFile('s3://bucket/log.txt','a') as f:
        print(*args,**kwargs, file=f)
```
I get errors like this
```
Traceback (most recent call last):
  File "/root/train.py", line 602, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/root/train.py", line 289, in main
    s3_print('Distinct elements: {}'.format(elements))
  File "/root/train.py", line 113, in tee_print
    print(*args,**kwargs, file=f)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 208, in __exit__
    self.close()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 240, in close
    pywrap_tensorflow.Set_TF_Status_from_Status(status, ret_status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: XAmzContentSHA256Mismatch: Unable to parse ExceptionName: XAmzContentSHA256Mismatch Message:
```

**Describe the expected behavior**

**Other info / logs**
Googling the keyword `XAmzContentSHA256Mismatch` led me to a bunch of s3 related issues, so I'm guessing that's related.

I'm not sure how to work around this problem so any guidance would be appreciated.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
