### ISSUE TITLE
[tf.keras.layers.LSTM] Initializer fails with input_length parameter

### ISSUE THREAD

**Issue by yugoren** [tensorflow/tensorflow#26590]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
```
4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- TensorFlow installed from (source or binary): `conda` as binary.
- TensorFlow version (use command below): `1.10`, `1.12`, and `1.13` confirmed
- Python version: `Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16)`

(The following are irrelevant since I'm not even running with a session or in eager mode)
- CUDA/cuDNN version: CUDA 9.0
- GPU model and memory: `GeForce GTX TITAN X`

**MWE**
```
import tensorflow as tf
lstm = tf.keras.layers.LSTM(512, input_length=32)
```
**Current behavior**
Here's `python` error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/anaconda/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2230, in __init__
    **kwargs)
  File "~/.local/anaconda/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/layers/recurrent.py", line 462, in __init__
    super(RNN, self).__init__(**kwargs)
  File "~/.local/anaconda/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 474, in _method_wrapper
    method(self, *args, **kwargs)
  File "~/.local/anaconda/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 138, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'input_length')
```

**Expected behavior**
`LSTM` class inherits from `RNN`, which has `input_length` as a parameter as described [here](https://www.tensorflow.org/versions/r1.13/api_docs/python/tf/keras/layers/RNN). Therefore the constructor of `RNN` should use this parameter but it does not as you can see [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/recurrent.py#L391-L399) in the code.

**Comment by facaiy** [comment]
@qlzh727 Qianli, are you a good person to look at this?

**Comment by qlzh727** [comment]
Yes, I will take a look within this week.

**Comment by qlzh727** [comment]
Ah, seems that it is an error in the documentation, the input_length is no longer needed and is inferred from the input tensor shape. I will fix the documentation soon.

**Comment by qlzh727** [comment]
This should now be fixed.
