### ISSUE TITLE
How to input a list of string values to Estimator

### ISSUE THREAD

**Issue by xionghhcs** [tensorflow/tensorflow#26594]
# I want to use tfhub'emlo to build a text classifier, but the elmo need a string values placeholder. in order to input feature to estimator, I need to use the tf.feature_column building the input feature columns.But how can i input a list of string values to estimator?

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
