### ISSUE TITLE
Getting error - Expects arg[0] to be float but uint8 is provided while using bytebuffer for image data in tensorflow inference.

### ISSUE THREAD

**Issue by saraswathykrk** [tensorflow/tensorflow#26596]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, but have only modified the model name in tensorflow/examples/android and tried passing bytebuffer of bytes for the imagedata.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Yes, android phones - one plus 6
- TensorFlow installed from (source or binary): github/tensorflow
- TensorFlow version (use command below):1.13.1
- Python version: 3.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I have modified the tensorflow/examples/android/demo to use my custom tf model(created from mobilenet_v1 trained for posenet tfjs). Instead of float values, am passing the image as a byte buffer using the below code:-

private String[] outputNames;
ByteBuffer imgData = null;

        imgData =
                ByteBuffer.allocateDirect(
                          DIM_BATCH_SIZE  //1
                * getImageSizeX()    //513
                * getImageSizeY()    //513
                * DIM_PIXEL_SIZE   //3
                * getNumBytesPerChannel());    //4
        imgData.order(ByteOrder.nativeOrder());

        int pixel = 0;

        for (int i = 0; i < 513; ++i) {
            for (int j = 0; j < 513; ++j) {
                final int val = intValues[pixel++];
                imgData.putFloat( ((val >> 16) & 0xFF));
                imgData.putFloat( ((val >> 8) & 0xFF));
                imgData.putFloat( (val & 0xFF));
            }
        }

Image size is 513 * 513.

1. The interfaceinference.feed is running without any issues.

inferenceInterface.feed(inputName, imgData, 1, inputSize, inputSize, 3, 4);

2. It fails when I try to run interfaceinference.run.

inferenceInterface.run(outputNames, logStats);

Here outputNames is a String[]. Although in the tensorflow interface.java code, it seems to handle the feed for Byte Buffers, the tensor created is a byte buffer - uint8. Then how is the run failing?

**Describe the expected behavior**

The inferenceInterface.run should be able to handle bytebuffer inputs as it is being handled in feed. 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

Code is provided above. Can reuse the existing model as in tensorflow/examples/android/demo and modify the TensorflowImageClassifier.java to pass the input image as a byteBuffer.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

    
    --------- beginning of crash
2019-03-12 11:46:54.161 3453-3469/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.demo, PID: 3453
    java.lang.IllegalArgumentException: Expects arg[0] to be float but uint8 is provided
        at org.tensorflow.Session.run(Native Method)
        at org.tensorflow.Session.access$100(Session.java:48)
        at org.tensorflow.Session$Runner.runHelper(Session.java:314)
        at org.tensorflow.Session$Runner.run(Session.java:264)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:228)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:197)

**Comment by mabdullahrafique** [comment]
No answer ?

**Comment by atlantiswqq** [comment]
[#34186 ](https://github.com/tensorflow/tensorflow/issues/34186)
i have the same problem.

**Comment by atlantiswqq** [comment]
i sloved

**Comment by JoeHRIsaac** [comment]
How?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
