### ISSUE TITLE
Issues with running compiled versions of tensorflow for different machines and CFLAGS

### ISSUE THREAD

**Issue by jam3st** [tensorflow/tensorflow#26595]
This is a bug  related to https://bugs.gentoo.org/show_bug.cgi?id=679714.

Here is the system information:
**### System information**
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**2019-03-12 05:23:07.606918: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.**

Actual system is an IvyBridge non AVX2 CPU. GCC version 8.3.0. No LTO. Simple use flags. 

How did this happen? I compiled tensor flow on my build machine. The build machine has loads of RAM big fans and is suited for compling stuff. I wanted to run tensorflow on my notebook, which was a bit older and more limited. I tried building tensor flow from the gentoo ebuild directly, with specific CPU flags for the CPU that I was going to run tensorflow on. I then ran into the gentoo bug 679714. This is where the libtensorflow_framework.so is missing the symbol __cpu_model (the flags I used on the build machine were **-O2 -march=ivybridge -mcx16 -msahf -mno-movbe -maes -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.1 -msse4.2 -mno-lzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mtune=ivybridge -minline-all-stringops -finline-functions -fmerge-all-constants**). I changed the CFLAGS to "-### O2" only and tensorflow ran fine on the build machine. I tried to run a python script (python versions 3.6 and 2.7) found was told that the CPU didn't support AVX2.

**Comment by gunan** [comment]
@perfinion may have an idea.
According to this, `-mno-avx2` should disable avx2, but I did not go through all flags.
https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/x86-Options.html#x86-Options

So it is possible, within so many flags one of the enabled things is using avx2, and gcc is not handling all flag combinations correctly (which is not unheard of).

**Comment by jam3st** [comment]
No those flags are from gcc-march=native for IvyBridge. To my knowledge and that of wikipedia there are no know IvyBridge CPUs that have support AVX2. https://en.wikipedia.org/wiki/Advanced_Vector_Extensions

There are many many things that it could possibly be, but given the fact that these flags have remained constant for a few gcc versions and when I compile and AVX2 program with explicit AVX2 code I get a compiler error, I think that the odds of it being a GCC error are small.

Anyhow, its almost the end of like for IvyBridge, so I would not worry about it, unless others are whining.
