### ISSUE TITLE
Cannot create a SavedModel with a DenseFeatures layer

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#26591]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
MacOSX 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
VERSION='2.0.0-dev20190311'
GIT_VERSION='v1.12.0-9917-gf988edacf4'
- Python version:
3.6.8
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
Cannot create a `SavedModel` with a `DenseFeatures` layer, I get an exception: `AttributeError: 'str' object has no attribute 'shape'` (see full stacktrace below).

**Describe the expected behavior**
I except to be able to save any tf.keras model (except those with dynamic layers) that uses only standard layers.

**Code to reproduce the issue**

```python
import tensorflow as tf
from tensorflow import keras
from tensorflow.train import Example, Features, Feature, FloatList
import numpy as np

# Create a simple TFRecord file
ages = np.random.rand(100)*50 + 20
heights = np.random.rand(100)*40 + 150
weights = 0.75 * heights - 75. + ages * 0.1 + np.random.rand(100) * 20
with tf.io.TFRecordWriter("weights.tfrecord") as f:
    for ex_age, ex_height, ex_weight in zip(ages, heights, weights):
        example = Example(features=Features(feature={
            "age": Feature(float_list=FloatList(value=[ex_age])),
            "height": Feature(float_list=FloatList(value=[ex_height])),
            "weight": Feature(float_list=FloatList(value=[ex_weight]))
        }))
        f.write(example.SerializeToString())

# Create a TFRecordDataset to read the data
age = tf.feature_column.numeric_column("age")
height = tf.feature_column.numeric_column("height")
weight = tf.feature_column.numeric_column("weight")
columns = [age, height, weight]
feature_descriptions = tf.feature_column.make_parse_example_spec(columns)
def parse_examples(serialized_examples):
    features = tf.io.parse_example(serialized_examples,
                                   feature_descriptions)
    targets = features.pop("weight")
    return features, targets
dataset = tf.data.TFRecordDataset(["weights.tfrecord"])
dataset = dataset.shuffle(100).batch(32).map(parse_examples)

# Create, train and use the model with a DenseFeatures layer
model = keras.models.Sequential([
    keras.layers.DenseFeatures(columns[:-1]),
    keras.layers.Dense(1)
])
model.compile(loss="mse", optimizer=keras.optimizers.SGD(lr=1e-5))
history = model.fit(dataset, epochs=5)
y_pred = model.predict({"age": tf.constant([25.]),
                        "height": tf.constant([180.])})

# Saving using the save() method works fine
model.save("my_weight_model.h5")

# Saving to a SavedModel fails
tf.saved_model.save(model, "my_weight_model.savedmodel") # AttributeError!
```

**Other info / logs**
Here is the stacktrace:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-116-5ddc1d5acd67> in <module>
     39 
     40 model.save("my_weight_model.h5")
---> 41 tf.saved_model.save(model, "my_weight_model.savedmodel")

~/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py in save(obj, export_dir, signatures)
    773   if signatures is None:
    774     signatures = signature_serialization.find_function_to_export(
--> 775         checkpoint_graph_view)
    776 
    777   signatures = signature_serialization.canonicalize_signatures(signatures)

~/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/saved_model/signature_serialization.py in find_function_to_export(saveable_view)
     63   # If the user did not specify signatures, check the root object for a function
     64   # that can be made into a signature.
---> 65   functions = saveable_view.list_functions(saveable_view.root)
     66   signature = functions.get(DEFAULT_SIGNATURE_ATTR, None)
     67   if signature is not None:

~/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py in list_functions(self, obj)
    109     obj_functions = self._functions.get(obj, None)
    110     if obj_functions is None:
--> 111       obj_functions = obj._list_functions_for_serialization()  # pylint: disable=protected-access
    112       self._functions[obj] = obj_functions
    113     return obj_functions

~/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in _list_functions_for_serialization(self)
   1793   def _list_functions_for_serialization(self):
   1794     return {
-> 1795         '_default_save_signature': saving_utils.trace_model_call(self)
   1796     }
   1797 

~/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/saving/saving_utils.py in trace_model_call(model, input_signature)
     76     for input_tensor, input_name in zip(inputs, input_names):
     77       input_specs.append(tensor_spec.TensorSpec(
---> 78           shape=input_tensor.shape, dtype=input_tensor.dtype,
     79           name=input_name))
     80     # The input signature of the call function is a list with one element, since

AttributeError: 'str' object has no attribute 'shape'
```

**Comment by ageron** [comment]
Awesome, thanks for the quick fix.

**Comment by joetoth** [comment]
Thanks, I was having the same issue, but it seemed to reveal another issue:
TypeError: input_signature must be either a tuple or a list, received <class 'dict'>

Using: https://files.pythonhosted.org/packages/57/08/8e39ef54e3aeaf35f87a5703df01cf1e5d11f1ac4ff0e7939191f22945de/tf_nightly_gpu_2.0_preview-2.0.0.dev20190315-cp37-cp37m-manylinux1_x86_64.whl

import os
from os.path import expanduser

from absl import app
import tensorflow as tf
import tensorflow_datasets as tfds

MODEL_DIR = '/tmp/tensorflow'
NUM_TRAIN_EPOCHS = 1

def mkmapfn(specs):
  def mapfn(example):
    x = tf.io.parse_single_example(example, specs)
    y = x.pop('label')
    x['image'] = tf.reshape(tf.image.decode_image(x['image']), [28, 28, 1])
    return x, y

  return mapfn


def get_tfds_pattern(name, split):
  _, info = tfds.load(name, with_info=True)
  file_pattern = os.path.join(
      expanduser(tfds.core.utils.constants.DATA_DIR), info.full_name,
      '*{}*'.format(split))
  return file_pattern


def get_tfds_filenames(name, split):
  pattern = get_tfds_pattern(name, split)
  return tf.io.gfile.glob(pattern)

def main(args):
  filenames = get_tfds_filenames('mnist', 'train')

  image = tf.feature_column.numeric_column('image', shape=[28, 28, 1])

  columns = [image]

  specs = tf.feature_column.make_parse_example_spec(columns)
  specs['label'] = tf.io.FixedLenFeature((), dtype=tf.int64, default_value=0)
  specs['image'] = tf.io.FixedLenFeature((), dtype=tf.string, default_value='')

  ds = tf.data.TFRecordDataset(filenames)
  ds = ds.map(mkmapfn(specs))
  ds = ds.take(1000)
  ds = ds.batch(128, drop_remainder=True)

  model = tf.keras.models.Sequential([
    tf.keras.layers.DenseFeatures(columns),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
  ])

  model.compile(
      optimizer='rmsprop',
      loss='categorical_crossentropy',
      metrics=['accuracy'])
  model.fit(ds)
  tf.saved_model.save(model, MODEL_DIR)


if __name__ == '__main__':
  app.run(main)


raceback (most recent call last):
  File "/home/joetoth/projects/psycho/psy/automl/auto_layer.py", line 65, in <module>
    app.run(main)
  File "/home/joetoth/.local/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/joetoth/.local/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/joetoth/projects/psycho/psy/automl/auto_layer.py", line 61, in main
    tf.saved_model.save(model, MODEL_DIR)
  File "/home/joetoth/.local/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 775, in save
    checkpoint_graph_view)
  File "/home/joetoth/.local/lib/python3.7/site-packages/tensorflow/python/saved_model/signature_serialization.py", line 65, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/home/joetoth/.local/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 111, in list_functions
    obj_functions = obj._list_functions_for_serialization()  # pylint: disable=protected-access
  File "/home/joetoth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1804, in _list_functions_for_serialization
    '_default_save_signature': saving_utils.trace_model_call(self)
  File "/home/joetoth/.local/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 89, in trace_model_call
    @def_function.function(input_signature=input_signature, autograph=False)
  File "/home/joetoth/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 980, in decorated
    experimental_autograph_options=experimental_autograph_options))
  File "/home/joetoth/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 286, in __init__
    python_function, input_signature)
  File "/home/joetoth/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 962, in from_function_and_signature
    kwargs_to_include, input_signature)
  File "/home/joetoth/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1001, in __init__
    "list, received " + str(type(input_signature)))
TypeError: input_signature must be either a tuple or a list, received <class 'dict'>

**Comment by allenlavoie** [comment]
@joetoth huh, yeah I can reproduce. Surprised the unit test didn't cover that too. Will take a look.

**Comment by allenlavoie** [comment]
There was a special case for single-element sequences that was broken. Should be fixed now. Thank you for the reports!

**Comment by nareshr8** [comment]
I am not able to create a model by joining Dense on top of DenseFeatures. When I do that it is complaining that Dense Features doesnt have shape attribute.

` for i in range(hidden_layers):
---> 77         l= tf.keras.layers.Dense(hidden_units, activation='relu')(l)
     78         # l=layers.Dropout(dropout_rate)(l)
     79     pred= tf.keras.layers.Dense(horizon, name='out')(l)

/local_disk0/pythonVirtualEnvDirs/virtualEnv-ffd3b642-1ea5-4fc2-92b2-4a9b2d684b8b/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    674         # Eager execution on data tensors.
    675         with backend.name_scope(self._name_scope()):
--> 676           self._maybe_build(inputs)
    677           with base_layer_utils.autocast_context_manager(
    678               input_list, self._mixed_precision_policy.should_cast_variables):

/local_disk0/pythonVirtualEnvDirs/virtualEnv-ffd3b642-1ea5-4fc2-92b2-4a9b2d684b8b/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
   1863 
   1864     input_spec.assert_input_compatibility(
-> 1865         self.input_spec, inputs, self.name)
   1866     input_list = nest.flatten(inputs)
   1867     if input_list and self._dtype is None:

/local_disk0/pythonVirtualEnvDirs/virtualEnv-ffd3b642-1ea5-4fc2-92b2-4a9b2d684b8b/lib/python3.5/site-packages/tensorflow/python/keras/engine/input_spec.py in assert_input_compatibility(input_spec, inputs, layer_name)
    107         spec.min_ndim is not None or
    108         spec.max_ndim is not None):
--> 109       if x.shape.ndims is None:
    110         raise ValueError('Input ' + str(input_index) + ' of layer ' +
    111                          layer_name + ' is incompatible with the layer: '

AttributeError: 'DenseFeatures' object has no attribute 'shape'`

Can Someone help

**Comment by anavanab99** [comment]
> I am not able to create a model by joining Dense on top of DenseFeatures. When I do that it is complaining that Dense Features doesnt have shape attribute.
> 
> ` for i in range(hidden_layers):
> ---> 77 l= tf.keras.layers.Dense(hidden_units, activation='relu')(l)
> 78 # l=layers.Dropout(dropout_rate)(l)
> 79 pred= tf.keras.layers.Dense(horizon, name='out')(l)
> 
> /local_disk0/pythonVirtualEnvDirs/virtualEnv-ffd3b642-1ea5-4fc2-92b2-4a9b2d684b8b/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py in **call**(self, inputs, *args, **kwargs)
> 674 # Eager execution on data tensors.
> 675 with backend.name_scope(self._name_scope()):
> --> 676 self._maybe_build(inputs)
> 677 with base_layer_utils.autocast_context_manager(
> 678 input_list, self._mixed_precision_policy.should_cast_variables):
> 
> /local_disk0/pythonVirtualEnvDirs/virtualEnv-ffd3b642-1ea5-4fc2-92b2-4a9b2d684b8b/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
> 1863
> 1864 input_spec.assert_input_compatibility(
> -> 1865 self.input_spec, inputs, self.name)
> 1866 input_list = nest.flatten(inputs)
> 1867 if input_list and self._dtype is None:
> 
> /local_disk0/pythonVirtualEnvDirs/virtualEnv-ffd3b642-1ea5-4fc2-92b2-4a9b2d684b8b/lib/python3.5/site-packages/tensorflow/python/keras/engine/input_spec.py in assert_input_compatibility(input_spec, inputs, layer_name)
> 107 spec.min_ndim is not None or
> 108 spec.max_ndim is not None):
> --> 109 if x.shape.ndims is None:
> 110 raise ValueError('Input ' + str(input_index) + ' of layer ' +
> 111 layer_name + ' is incompatible with the layer: '
> 
> AttributeError: 'DenseFeatures' object has no attribute 'shape'`
> 
> Can Someone help

I encountered the same problem, did you solve it?I  can't solve it without trying for a long time
