### ISSUE TITLE
how to build armeabi-v7a tensorflow-lite.a with ndk?

### ISSUE THREAD

**Issue by nongcunshaoye** [tensorflow/tensorflow#26605]

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
