### ISSUE TITLE
Can I attach a c++ object to a tensor so that the object can be forwarded through the network and share the same lifetime with the tensor?

### ISSUE THREAD

**Issue by x10000year** [tensorflow/tensorflow#26601]
I'm trying to develop a complex network in which, some custom c++ ops output c++ objects that are to be received by other custom ops.  One solution is by serializing the c++ object into a byte tensor, but this way adds (de)serialization overhead. Another solution is only outputting the address of the object and storing the actual object as a data member of the c++ op instance, but this way only works in graph mode. Is there a better solution for this problem? Thank you.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
