### ISSUE TITLE
TensorFlow 1.13 build fails with MPI support

### ISSUE THREAD

**Issue by marcjoos-phd** [tensorflow/tensorflow#26610]
**System information:**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7.4
- TensorFlow installed from source
- TensorFlow version: 1.13
- Python version: 3.6.4
- Bazel version: 0.19 (recompiled from https://copr-be.cloud.fedoraproject.org/results/vbatts/bazel/fedora-27-x86_64/00823004-bazel/bazel-0.19.1-1.fc27.src.rpm since Bazel version provided by COPR for RHEL 7.4 is 0.23, that is not compatible with TensorFlow 1.13)
- GCC/Compiler version: GCC 4.8.5 
- with no CUDA support
- Open MPI version: 2.0.4

**Problem description:**
Build fails with MPI support with the following message:

```
ERROR: /tmp/tensorflow/sources/tensorflow/tensorflow/BUILD:573:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
[<machine>:30644] mca_base_component_repository_open: unable to open mca_patcher_overwrite: <path-to-openmpi-2.0.4>/lib/openmpi/mca_patcher_overwrite.so: undefined symbol: mca_patcher_base_patch_t_class (ignored)
[<machine>:30644] mca_base_component_repository_open: unable to open mca_shmem_posix: <path-to-openmpi-2.0.4>/lib/openmpi/mca_shmem_posix.so: undefined symbol: opal_show_help (ignored)
[<machine>:30644] mca_base_component_repository_open: unable to open mca_shmem_sysv: <path-to-openmpi-2.0.4>/lib/openmpi/mca_shmem_sysv.so: undefined symbol: opal_show_help (ignored)
[<machine>:30644] mca_base_component_repository_open: unable to open mca_shmem_mmap: <path-to-openmpi-2.0.4>/lib/openmpi/mca_shmem_mmap.so: undefined symbol: opal_show_help (ignored)
--------------------------------------------------------------------------
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_shmem_base_select failed
  --> Returned value -1 instead of OPAL_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_init failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[<machine>:30644] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
I must say that I am clueless since I cannot understand which script/program is launched that triggers this error. If I understand well, it crashes while applying `tensorflow:tf_python_api_gen_v1` rule that comes from `tensorflow/BUILD`, but it is unclear to me where this rule is actually applied.

**Sequence of commands:**
```
./configure
/usr/local/bin/bazel --output_user_root=/tmp/bazel/build build --config=opt  //tensorflow/tools/pip_package:build_pip_package --distdir=builddeps
```

**Additional infos:**
- My Open MPI installation is working flawlessly appart from this issue.
- Note that I am building TensorFlow behind a proxy and was therefore forced to download all the required dependencies in a `distdir` folder.
- I first tried to build TensorFlow from master, but had first another issue (`InitPartial` signature change was not reported in `tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc` and I had to patch this file) but ended up with a similar build fail.
- For the sake of completeness, I also gave a try with GNU 8.2.0 -- even though I doubted it had anything to do with the problem at stake.

**Comment by gunan** [comment]
From our side, MPI is a community maintained feature.
@tatianashp does Intel help with maintaining MPI support?

**Comment by gunan** [comment]
Maybe @jhseu has knowledge of the party that supports MPI.

**Comment by tatianashp** [comment]
I don't think Intel supports MPI in TensorFlow. Adding @agramesh1  just in case.

**Comment by byronyi** [comment]
@jbedorf mind to take a look here?

**Comment by jbedorf** [comment]
That is a weird error, especially given that it happens during the build process. Could it be that there is a Python package installed that loads MPI libraries, e.g. `mpi4py`?

**Comment by agramesh1** [comment]
@tatianashp  Thanks, will see if we can help.  Pinging @TensorFlow-MKL .

**Comment by wei-v-wang** [comment]
Hi @marcjoos-phd ,  
At Intel we test TensorFlow with multinode CPU and MPI frequently. Currently the recommended way of trying distributed training on CPU is via horovod. ResNet50 are most frequently tested, but the good thing is that multi-node training of CPU with horovod does *not* require you to build TensorFlow with MPI. Just remember to use --config=mkl to turn on Intel optimizations with MKL :)
FYI: some blogs published by Intel might be of help: https://ai.intel.com/using-intel-xeon-for-multi-node-scaling-of-tensorflow-with-horovod/
Recently I tested that using TF v1.13.1 and horovod 0.13.1, and cnn_tf_v1.13_compatible branch of this repo should just work for CPU. Commands are similar to the commands in the above blog. Both Intel MPI and OpenMPI work, you can start with OpenMPI (e.g. OpenMPI 3.0). 

there is also an Intel white paper on distributed training on CPU architecture: https://builders.intel.com/docs/aibuilders/best-practices-for-scaling-deep-learning-training-and-inference-with-tensorflow-on-intel-xeon-processor-based-hpc-infrastructures.pdf

Feel free to let us know of your questions. And thank you from Intel for trying distributed training with CPU!

**Comment by wei-v-wang** [comment]
To clarify the better bazel build instruction (for CPU) is 
/usr/local/bin/bazel --output_user_root=/tmp/bazel/build build --config=mkl --config=opt  //tensorflow/tools/pip_package:build_pip_package --distdir=builddeps

Before you run the above bazel command, while you configure TF, reply "N" to "build TF with MPI?"[y/N]

**Comment by TensorFlow-MKL** [comment]
MPI question on 1.13 is addressed, closing this issue. 1.14 is tracked under a different ticket. Please reopen if you continue to experience the issue.
