### ISSUE TITLE
Keras Error: Variable does not exist, or was not created with tf.get_variable()

### ISSUE THREAD

**Issue by jvishnuvardhan** [tensorflow/tensorflow#26629]
```
import tensorflow.keras as ks
def scope_error_test():
    input_holder = tf.placeholder(dtype=tf.float32,
                                  shape=(None, 368, 368, 3),
                                  name='input')
    with tf.variable_scope("scope_1"):
        with tf.variable_scope("scope_2"):
            conv1 = ks.layers.Conv2D(kernel_size=7,
                                     filters=64,
                                     strides=2,
                                     padding='same',
                                     activation=tf.nn.relu,
                                     name='conv1')(input_holder)
            pool1 = ks.layers.MaxPool2D(pool_size=3, padding='same',
                                        strides=2,
                                        name='pool1')(inputs=conv1)
    print(pool1.get_shape().as_list())
with tf.Session() as sess:
        scope_error_test()
        sess.run(tf.global_variables_initializer())
        print(tf.global_variables())
        with tf.variable_scope('', reuse=True):
            for variable in tf.global_variables():
                var_name = variable.name.split(':')[0]
                var_tf = tf.get_variable(var_name)
```

In this example code, I want to understand why I get this error: ValueError: Variable scope_1/scope_2/conv1/kernel does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

Note: I used tensorflow.contrib.layers instead of tensorflow.keras.layers and It was working correctly! Could be a bug !?

I have tried tensorflow 1.9.0 and tensorflow 1.12.0

**Comment by umbrellalalalala** [comment]
In [keras document](https://keras.io/layers/convolutional/), there is a sentence:
>This layer creates a convolution kernel

So when you tried:
```
conv1 = ks.layers.Conv2D(..., name='conv1')
```
A variable 'conv1/kernel ' would be created in current scope 'scope_1/scope_2/'.

According to what you got, I think it's probably your reuse was true. You could check reuse by:
```
print tf.get_variable_scope().reuse
```
If you got True, then ran `conv1 = ks.layers.Conv2D(..., name='conv1')`, it would reuse the variable defined earlier. But It was the first time you defined `scope_1/scope_2/conv1/kernel` , so you got that error.

Now, it's worthwhile to try:
```
with tf.variable_scope(tf.get_variable_scope(), reuse=tf.AUTO_REUSE):
```
Put this before `conv1=...`, and don't ignore code indent.

**Comment by Gouiaa** [comment]
@umbrellalalalala Thanks for your answer. However, it does not work. Did you try it on your machine before write it here ? I have already provide  a minimal working example to help other reproduce the error and try to correct it.

**Comment by umbrellalalalala** [comment]
@Gouiaa All right, the question in this page has no code indent, and I mistook it as a problem I solved the other day. I'm sorry that before I answered on your question page, I didn't read your indented question again.

I'm curious about this problem after read it again. If I work it out on my pycharm, I will write it here.

**Comment by tanzhenyu** [comment]
Why do you have "with tf.variable_scope('', reuse=True):"?

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!
