### ISSUE TITLE
contrib/session_bundle does not work with python3

### ISSUE THREAD

**Issue by DomenicD** [tensorflow/tensorflow#2662]
Branch r0.9 
### Environment info
Operating System: Ubuntu 14.4

Installed version of CUDA and cuDNN: no

### Steps to reproduce
1.  ./configure -> python path = /usr/local/bin/python3
2.  bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

Error with:
//tensorflow/contrib/session_bundle/example:export_half_plus_two

### What have you tried?
1.  Cloning branch r0.8, which does not include the broken target, works

**Comment by girving** [comment]
Can we see the full error message?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
