### ISSUE TITLE
Export tf.lookup.TextFileIndex in 2.0

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#26622]
**System information**
- TensorFlow version: `2.0.0.dev20190311`
- Are you willing to contribute it: No

**Describe the feature and the current behavior/state.**

The exported class `tf.lookup.TextFileInitializer` takes as argument `key_index` and `value_index` but the enum `TextFileIndex` is not available via the API.

The `tf.lookup` module should export this enum.

**Will this change the current api? How?**

This will add a new symbol covered by backward compatibility guarantees.

**Who will benefit with this feature?**

Users of `tf.lookup.TextFileInitializer`.

**Comment by yongtang** [comment]
Added PR #26644 for the fix.
