### ISSUE TITLE
Pypi file for tensorflow-gpu 1.10.1 for Python 3.6 manylinux is zero bytes

### ISSUE THREAD

**Issue by GabrielF00** [tensorflow/tensorflow#26628]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Amazon Linux 2012.3
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.10.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I have a requirements.txt file that contains the following:

```
tensorflow-gpu==1.10.1 \
    --hash=sha512:cf7ee7c41166f936c06b4041efab5d901019cc0b6caba69e6645bcb5886243dfcf072f71119692eec31359585da3bede39f208e75e3b7dc84d9c99fe33cf18d6 \
    --hash=sha512:ae6d1c332e8128435f61cab9ae8a770aac897eafa94f4abc4937a9d288622bc717e73663f1941f0211b6effadf6ac08d20a70829a48e5663f2f3638e8e61b9ff
```
I use the following command in my Dockerfile to install tensorflow-gpu and other dependencies:
```
RUN pip install --no-deps --upgrade-strategy only-if-needed --no-cache-dir --require-hashes -r ./$REQUIREMENTS_TF_FILE
```
However, I get an error that the hash of the file downloaded from Pypi doesn't match the hash in my requirements file. I went to the Pypi website and tried to download the file [tensorflow_gpu-1.10.1-cp36-cp36m-manylinux1_x86_64.whl](https://files.pythonhosted.org/packages/3f/c3/000755084b5e7b5a11df1b9166a54936075ec280b7a615cecce42973fc8b/tensorflow_gpu-1.10.1-cp36-cp36m-manylinux1_x86_64.whl ). I found that the file is zero bytes!

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Apologies for the delay in response. Is this still an issue? I did download the tf wheel from the link you provided, the file size is around 253 mb. Can you please confirm? Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by GabrielF00** [comment]
@ymodak The file downloads fine now. I'm not sure what the issue was, but it looks like it got resolved. Thanks
