### ISSUE TITLE
Improve tf_compile to allow emitting HLO module instead of/in addition to executable

### ISSUE THREAD

**Issue by gmagogsfm** [tensorflow/tensorflow#26627]
Currently tf_compile (tensorflow/compiler/aot) always emits executable. But there are use cases where dumping HLO module is more desired. This is a tracking bug to implement it.

**Comment by sushreebarsa** [comment]
@gmagogsfm While XLA Flags not directly supported by tf_compile, you can leverage XLA flags like --xla_generate_hlo_text_to=<output_dir> during tf.function tracing or conversion. This allows generating HLO text files, but might require additional steps to integrate with tf_compile.  

Thank you!
