### ISSUE TITLE
No improvement in performance of mobilenet_v1_1.0_224 on TFLite for GPU

### ISSUE THREAD

**Issue by FedyuninV** [tensorflow/tensorflow#26620]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 8.0.0
- Mobile device: Samsung S9+, Sony XPeria XZ2
- TensorFlow installed from (source or binary): binary `'org.tensorflow:tensorflow-lite:0.0.0-gpu-experimental'`
- TensorFlow version (use command below): - (used pretrained *.tflite file)
- Python version: - (used pretrained *.tflite file)
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: Exynos 9810 Octa (Samsung), Sanpdragon 845 (Sony)

**Describe the current behavior**

No differences in performance for Samsung S9+ between CPU and GPU versions.

**Describe the expected behavior**

According to [this TensorFlow's article on Medium](https://medium.com/tensorflow/tensorflow-lite-now-faster-with-mobile-gpus-developer-preview-e15797e6dee7) expected at least 3x improvement.

**Code to reproduce the issue**
TFLite archive for MobileNet v1 (224x224) has been downloaded from link from [article, mentioned above](https://medium.com/tensorflow/tensorflow-lite-now-faster-with-mobile-gpus-developer-preview-e15797e6dee7)

Code:
```java
    private final int ImageHeight = 224;
    private final int ImageWidth = 224;
    private final int ImageChannels = 3;
    private final int ImageSize = ImageHeight * ImageWidth * ImageChannels;

    private final String tfliteFileName = "mobilenet_v1_1.0_224.tflite";

    public String run(Context context, AssetManager assetManager) throws IOException {
        AssetFileDescriptor fd = assetManager.openFd(tfliteFileName);
        FileChannel fileChannel = new FileInputStream(fd.getFileDescriptor()).getChannel();
        MappedByteBuffer model =
            fileChannel.map(FileChannel.MapMode.READ_ONLY, fd.getStartOffset(), fd.getDeclaredLength());

        int runCount = 100;
        long elapsedTime = 0;

        GpuDelegate delegate = new GpuDelegate();
        Interpreter.Options options = (new Interpreter.Options()).addDelegate(delegate);

        try(Interpreter tflite = new Interpreter(model, options)) {
            Map<Integer, Object> output = new HashMap<Integer, Object>();
            output.put(Integer.valueOf(0), new float[1][1001]);

            Object inputData = 0;
            float[][][][] in = new float[1][ImageHeight][ImageWidth][ImageChannels];
            // For example: filling blob uniformly from -5. to 5. in Channel-first format.
            int pos = 0;
            for(int c = 0; c < ImageChannels; ++c) {
                for(int j = 0; j < ImageHeight; ++j) {
                    for(int i = 0; i < ImageWidth; ++i) {
                        in[0][j][i][c] = 10 * (float)(pos++) / (ImageSize - 1) - 5;
                    }
                }
            }
            inputData = in;
            Object[] input = new Object[] { inputData };
            tflite.runForMultipleInputsOutputs(input, output);

            for (int i = 0; i < runCount; i++) {
                // run the second time to make sure all the buffers (and other lazy stuff) have been initialized
                long timeStart = System.currentTimeMillis();
                tflite.runForMultipleInputsOutputs(input, output);
                float[][] res = (float[][]) output.get(0);
                elapsedTime += System.currentTimeMillis() - timeStart;
            }
        }

        delegate.close();

        return "RUN completed: " + (elapsedTime / runCount) + " ms";
    }
```
**Other info / logs**

***Samsung (Exynos GPU)***

Version with GPUDelegate is a little bit slower (170 ms per run vs 140 ms)

***Sony XPeria (Sanpdragon GPU)***

Version with GPUDelegate is a little bit faster (102 ms per run vs 125 ms).

The warning `WARNING: op code #42 cannot be handled by this delegate.` **does not** appear in LogCat during the execution, so it doesn't look like GpuDelegate couldn't handle some operation.

**Comment by freedomtan** [comment]
Either ~140 ms or ~170 ms looks too slow. See [my numbers on Pixel 2](https://github.com/freedomtan/glDelegateBench/blob/master/README.md) and [S9 numbers from @Burgomehl](https://github.com/freedomtan/glDelegateBench/issues/2)

**Comment by FedyuninV** [comment]
@freedomtan I've checked my config and found out that my Samsung has Exynos onboard. That's why I checked this app on Sony Xperia XZ2 with Snapdragon 845 and got some improvement, but not even close to mentioned in the article (125 ms per run vs 102 ms). Updated info in PR message. Is it OK, or performance should be better?

**Comment by FedyuninV** [comment]
@freedomtan May be there are some other conditions (for ex. targetSdkVersion or anything else) in project properties which could have a huge effect on performance?

**Comment by freedomtan** [comment]
@FedyuninV I don't have either Snapdragon 845 or Samsung S9 phones. I did find an newly released Xiaomi Mi 9, a 855 phone, to run [my little program](https://github.com/freedomtan/glDelegateBench/blob/master/README.md). 

|model name|CPU 1 thread (ms)|CPU 4 threads (ms) |GPU (ms)|
|----------|------------:|-------------:|---:|
|Mobilenet | 39 | 35 | 15 |
|PoseNet   | 48 | 47 | 19 |
|DeepLab V3| 61 | 64 | 65 |
|Mobilenet SSD V2 COCO| 69 | 75 | 36 |

Performance numbers of 845 are supposed to between 835's and 855's.

Note that when doing benchmark / measurement, the first runs usually are slower because some initialization overheads.

**Comment by impjdi** [comment]
@FedyuninV 

Thanks for trying out the GPU delegate.  I got an S8 (Exynos) see CPU 255,126us vs GPU FP16 17,792us (buffers) & 33,979 (textures), averaged over 20 runs.  IIRC the developer preview was set to textures, (we now have logic to switch to buffers if it's faster on a particular device), but you should see some improvement.

I'll try to dig up whether we also have an S9 (Exynos).

We don't have the Sony XPeria, so I couldn't check that.

Anyway, you should see some improvement when using the GPU delegate, and it puzzles me why you run into this issue.  I don't think it's a device capability issue.

`
            long timeStart = System.currentTimeMillis();
            for (int i = 0; i < runCount; i++) tflite.runForMultipleInputsOutputs(input, output);
            long timeEnd = System.currentTimeMillis();
            return "RUN completed: " + ((timeEnd - timeStart) / runCount) + " ms";
`

should give you the timing without interrupts for getting the system time.

**Comment by impjdi** [comment]
@FedyuninV 

Btw, are you able to get the `GpuDelegate` with just `new`?  Shouldn't you use the `GpuDelegateHelper.isGpuDelegateAvailable()` & `GpuDelegateHelper.createGpuDelegate()`?

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/ImageClassifier.java#L174

**Comment by FedyuninV** [comment]
@impjdi 

I'll be able to continue research on Monday.

About `new GpuDelegate();`: I used [this tutorial](https://www.tensorflow.org/lite/performance/gpu#trying_the_gpu_delegate_on_your_own_model).

**Comment by freedomtan** [comment]
@impjdi `new GpuDelegate()` works for me.

**Comment by impjdi** [comment]
@freedomtan Wow, didn't know.  I live in the C++ world.
@FedyuninV Sorry for the confusion.  Apparently, that also works.

**Comment by FedyuninV** [comment]
@freedomtan Your program shows improvements (101 cpu, 16 gpu). I have to go deeper. As soon as I find the cause of fails of my program I'll close the issue.

**Comment by impjdi** [comment]
Not officially announced yet, but FYI: GPU code is now visible at:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/gpu

if you need the code for better insight what is happening.

**Comment by pouyaAB** [comment]
@FedyuninV Did you found the source of the problem? I am facing the same problem.
