### ISSUE TITLE
Add a origin url param to load_data function in keras.datasets

### ISSUE THREAD

**Issue by BrikerMan** [tensorflow/tensorflow#26636]
**System information**
- TensorFlow version (you are using): 2.0.0-alpha0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

`keras.datasets` is a nice place for beginners to start, but `storage.googleapis.com` is blocked in some country, it makes it impossible to directly download the dataset. I propose to add a URL param to the `load_data` function of the dataset. So we could provide some mirror URL for users in our country.

**Will this change the current API? How?**
Yes, will add a param with default value None to all `load_data` function in `tensorflow/python/keras/datasets`

**Who will benefit with this feature?**

All new beginners in countries blocked `storage.googleapis.com`

**Any Other info.**

**Comment by ymodak** [comment]
This issue is more suitable keras repo since keras.datasets is maintained by keras team. Please post it on [keras github repo](https://github.com/keras-team/keras/issues). Thanks!
