### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by peyifyp** [tensorflow/tensorflow#26634]
I have this error, how can i solve this problem?

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_tfrecord.py", line 17, in <module>
    import tensorflow as tf
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ymodak** [comment]
Please provide following info:
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:



**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**


**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by peyifyp** [comment]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
   Pro 64-bit (10.0, biuld 17134)
   - TensorFlow installed from (source or binary): from source
   - TensorFlow version: 1.13.1
   - Python version:  python 3.6
   - Installed using virtualenv? pip? conda?: conda
   - CUDA/cuDNN version: CUDA:9.0 / cuDNN: v9
   - GPU model and memory:    memory:8192MB RAM

**Comment by ymodak** [comment]
Thanks for providing the info. Did you add cuda to your path?
Take a look at this [windows setup guide for gpu support](https://www.tensorflow.org/install/gpu#windows_setup) if haven't already.
You need to add sub folders: ```bin``` , ```include``` and ```lib`` to the path. Can you please try adding them as well?

**Comment by peyifyp** [comment]
yes i have add cuda in my path. The attachment is my added path.

**Comment by peyifyp** [comment]
shall i need the NVIDIA package launcher for my cudnna and cuda? if need
may i know the  Product Series,  Product Type and  Product suitable for my
laptop? i have try to download the driver but it cannot work. thanks

**Comment by ymodak** [comment]
ah I see you are using cuda 9.0. TF 1.13.1 comes with pre built cuda 10.0 binaries. So please upgrade to cuda 10.0 and make sure to add path as well.

**Comment by peyifyp** [comment]
thanks for your suggestion.

**Comment by ymodak** [comment]
@peyifyp Were able to install TF? Any updates yet.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
