### ISSUE TITLE
about  deeplearning models center repository.

### ISSUE THREAD

**Issue by 1991wangliang** [tensorflow/tensorflow#26633]
The technology of in-depth learning has been developed for a long time. At present, it is not clear whether there is a model library of the type of Maven docker central library. If not, I hope we can build it. If there is, please let me know. Thanks.

**Comment by ymodak** [comment]
I believe this is a feature request. Can you elaborate more by providing following information asked by the template? Thanks

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):



**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
