### ISSUE TITLE
How To build And deploy Tensor flow label_image code wit Qt Envirnment

### ISSUE THREAD

**Issue by nmmane** [tensorflow/tensorflow#26648]
**System information**
- Linux Ubuntu 16.04
- TensorFlow installed from source
- TensorFlow version:1.7.0
- Python version:Python 2.7.12
- Installed using  pip
- Bazel version (if compiling from source):Build label: 0.23.1
- GCC/Compiler version (if compiling from source):gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 
- CUDA/cuDNN version: CUDA10
- GPU model and memory:nvidia  6GB

<em>
I have build and test the tensor flow with label_image test code. I have used bazel on ubuntu 16.04 (x64) system. I have build and test both the python and c++ code.

Now I want to build the label_image c++ code with my project in Qt.
         For the same i have tried to build my project by including -ltensorflow_framework generated via tensor flow build through bazel, but not succeeded.

Also I have tried by building label_image as library and tried to include this label_image output in my Qt Project, but this was also not sccessfull.

 Can you please let me know the best way to complete my task (build label_image c++ code with Qt)?
        I am interested to build the tensor flow with gpu support.

please point me to the exact example or step by step guide to build the target.
</em>

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
