### ISSUE TITLE
Documentation link broken for what is transfer learning?

### ISSUE THREAD

**Issue by Shrutihegde13** [tensorflow/tensorflow#26649]
Doc Link: https://www.tensorflow.org/js/tutorials/transfer/image-classification

The above link is broken.

**Comment by ymodak** [comment]
Thanks for catching this. Indeed following links seem to be broken under [what is transfer learning](https://www.tensorflow.org/js/tutorials/transfer/what_is_transfer_learning)
[Build a transfer-learning based image classifier](https://www.tensorflow.org/js/tutorials/transfer/image-classification)
[Build a transfer-learning based audio recognizer](https://www.tensorflow.org/js/tutorials/transfer/audio-recognizer)

**Comment by Shrutihegde13** [comment]
Can I fix this?

**Comment by tafsiri** [comment]
@Shrutihegde13 Thanks for the offer to help! It looks like we already have a PR pending that fixes this so i'll look into getting that merged.

**Comment by tafsiri** [comment]
Fix has been submitted. Will update once its been deployed.

**Comment by tafsiri** [comment]
FIx is deployed.
