### ISSUE TITLE
Testing guide page not exist (404)

### ISSUE THREAD

**Issue by Jasonnor** [tensorflow/tensorflow#26645]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.13
- Doc Link: https://www.tensorflow.org/api_guides/python/test

**Describe the documentation issue**
[Testing guide](https://www.tensorflow.org/api_guides/python/test) not exist which linked from [tf.test page](https://www.tensorflow.org/api_docs/python/tf/test).

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
I don't know if the page originally exists. 🤔

**Comment by dynamicwebpaige** [comment]
Thanks for filing the issue! The link you referenced is pointing to a [Testing Guide](https://web.archive.org/web/20180908070834/https://tensorflow.org/api_guides/python/test) we had historically; but I do not think has been upgraded to TF 2.0.

@MarkDaoust, do you know if we have plans to update the guide?

**Comment by krishnap25** [comment]
The testing guide is still missing. 

I went to [this page](https://www.tensorflow.org/api_docs/python/tf/test), 
which points to the testing guide, but I only see a 404 error. See 
[here](https://www.tensorflow.org/api_guides/python/test).

**Comment by Saduf2019** [comment]
@Jasonnor 
@krishnap25 
could you please confirm if the issue still persist

**Comment by Jasonnor** [comment]
Not see a 404 now, but the link of test guild on [this page](https://www.tensorflow.org/api_docs/python/tf/test) is same as it(api page). 🤣
