### ISSUE TITLE
tensorflow serving embedding get Truncate？

### ISSUE THREAD

**Issue by BilleChu** [tensorflow/tensorflow#26656]
NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: embedding_1/Cast = Cast[DstT=DT_INT32, SrcT=DT_FLOAT, Truncate=false, _output_shapes=[[?,15]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_input_1_0_0). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).%0A%09 [[Node: embedding_1/Cast = Cast[DstT=DT_INT32, SrcT=DT_FLOAT, Truncate=false, _output_shapes=[[?,15]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_input_1_0_0)]]|

**Comment by ymodak** [comment]
This issue is more appropriate on TensorFlow Serving repo. Please post it on [TF Serving](https://github.com/tensorflow/serving/issues) from here. 
 Thanks!
