### ISSUE TITLE
Dataset object is not an iterator, although I can iterate on it.

### ISSUE THREAD

**Issue by galeone** [tensorflow/tensorflow#26658]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Archlinux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-dev20190312
- Python version: 3.6
- CUDA/cuDNN version: 10
- GPU model and memory: 1080 Ti

**Describe the current behavior**

> TypeError: 'DatasetV1Adapter' object is not an iterator

**Describe the expected behavior**:

Should fetch the first element of the iterator, thus print 10.

**Code to reproduce the issue**

```python
import tensorflow as tf

def real_gen():
    for _ in range(10):
        yield 10.0

dataset = tf.data.Dataset.from_generator(real_gen, (tf.float32))
# Fails
print(next(dataset))
```

Since I can iterate on the dataset using a for loop

```python
# It works
for real in dataset:
    print(real)
```

I do expect I can treat the dataset as an iterator, thus extracting the next element by calling `next(dataset)`.

**Comment by mrry** [comment]
A Dataset is not the same thing as an iterators, so this is expected behavior. You can think of a TensorFlow iterator as the combination of a Dataset **and** a current position in that Dataset.

You can create an iterator from a dataset using `iter(dataset)`, so the following code should work (in TensorFlow 2.0, or with eager execution enabled):

```python
import tensorflow as tf

def real_gen():
    for _ in range(10):
        yield 10.0

dataset = tf.data.Dataset.from_generator(real_gen, tf.float32)
iterator = iter(dataset)
print(next(iterator))
```

**Comment by galeone** [comment]
Hi @mrry and thank you for the quick response.

I understand a dataset is not the same thing as an iterator and I'll use your solution to convert the dataset to a Python iterator when working in eager mode.

However, I found a (related?) issue when wrapping a dataset into a `tf.function`.

A code that loops using Tensorflow primitives (like `for i in tf.range(10)`) can be converted into its graph representation without any problem, while a code that creates a python iterator from a dataset object (like you suggested, using `iter(dataset)`) can't.

Moreover, maybe because we are in the early stage of the development, I'm unable to convert a loop that loops over a dataset to its graph representation.

```python
import tensorflow as tf

def real_gen():
    for i in range(10):
        yield i

dataset = tf.data.Dataset.from_generator(real_gen, (tf.float32))

@tf.function
def itertest():
    tf.print(next(iter(dataset)))
itertest()

@tf.function
def loopiter():
    for real in dataset:
        tf.print(real)
loopiter()
```

The `itertest()` call fails because `RuntimeError: dataset.__iter__() is only supported when eager execution is enabled.`

While the `loopiter()` call fails because `tensorflow.python.framework.errors_impl.NotFoundError: Function __inference_Dataset_flat_map_flat_map_fn_22 is not defined.
         [[{{node ReduceDataset}}]] [Op:__inference_loopiter_35]`

Should I open a new issue for this or it is a known and desired behavior?

**Comment by galeone** [comment]
I'm going to create a new issue

**Comment by elfelround** [comment]
findinf a similar issue when
