### ISSUE TITLE
resize_image_with_pad is not available as described in documentation

### ISSUE THREAD

**Issue by meyerjo** [tensorflow/tensorflow#26651]
**System information**
- TensorFlow version: 2.0.0-alpha
- Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/image/resize_image_with_pad

**Describe the documentation issue**
This is not available in 2.0.0 it is renamed as tf.image.resize_with_pad

**Comment by shashvatshahi1998** [comment]
i am not getting what the real issue is?

**Comment by meyerjo** [comment]
Just to clarify. This is an issue as the documentation is not updated in accordance to the renaming in TF2.0

```cmd
>>> import tensorflow as tf
>>> tf.__version__
'2.0.0-alpha0'
>>> tf.image.resize_image_with_pad
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow._api.v2.image' has no attribute 'resize_image_with_pad'
>>> tf.image.resize_with_pad
<function resize_image_with_pad_v2 at 0x7f9cb26b86a8>
```

**Comment by facaiy** [comment]
@drpngx does we rename the op in purpose?

https://github.com/tensorflow/tensorflow/blob/b244682665372a4e5aaf16b13a54d1dba2613c57/tensorflow/python/ops/image_ops_impl.py#L1370-L1371

**Comment by drpngx** [comment]
I think @meyerjo is right, the symbol is exported as `tf.image.resize_with_pad` in 2.0 and not `resize_image_with_pad`, which is v1, so the published doc is incorrect.

It is just a matter of re-running the docs generation and uploading the new version.

You can check what docs would be generated with:
```
bazel-bin/third_party/tensorflow/tools/docs/generate2 --output_dir=/tmp/tf2_docs_preview
```
I ran that locally and it produces the right docs. I'm leaving that issue open until we update the site.

**Comment by drpngx** [comment]
It looks like this has been fixed.
