### ISSUE TITLE
Benchmarker of tensorflow/lite initialize tensorflow

### ISSUE THREAD

**Issue by mattn** [tensorflow/tensorflow#26668]
Current implementation of tensorflow/lite/testing have initialization of TensorFlow core.

https://github.com/tensorflow/tensorflow/blob/069c503b4ac5bf4c89aeb38332685e427e0d3e03/tensorflow/lite/testing/init_tensorflow.cc#L23-L30

Why this is needed? Benchmarker always include binary of tensorflow. I think this is enough.

```diff
diff --git a/tensorflow/lite/testing/init_tensorflow.cc b/tensorflow/lite/testing/init_tensorflow.cc
index ed4d123744..d8d639f410 100644
--- a/tensorflow/lite/testing/init_tensorflow.cc
+++ b/tensorflow/lite/testing/init_tensorflow.cc
@@ -20,12 +20,5 @@ limitations under the License.
 #include "tensorflow/core/platform/init_main.h"
 
 namespace tflite {
-void InitTensorFlow() {
-  static const char* kFakeName = "fake program name";
-  int argc = 1;
-  char* fake_name_copy = strdup(kFakeName);
-  char** argv = &fake_name_copy;
-  ::tensorflow::port::InitMain(kFakeName, &argc, &argv);
-  free(fake_name_copy);
-}
+void InitTensorFlow() {}
 }  // namespace tflite
```

**Comment by haozha111** [comment]
I believe this is needed at least in this test:
https://github.com/tensorflow/tensorflow/blob/5b24fba0857394dab67359963726b3bcce071575/tensorflow/lite/tools/benchmark/benchmark_plus_flex_main.cc#L16

Basically, in flex mode, TF Lite will fall back to use TF ops, and that's the reason we need to include tensorflow core dependencies. Note that not all TF Lite benchmark tests need import core TF.
