### ISSUE TITLE
Using create_training_graph with act_quant not found error 

### ISSUE THREAD

**Issue by asjmasjm** [tensorflow/tensorflow#26664]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (use command below):
1.9.0
- Python version:
3.6
- CUDA/cuDNN version:
9.0
- GPU model and memory:

After the addition of the quantization training code like:

    ......
    full_precision_graph = tf.get_default_graph()
    with tf.variable_scope(params['model_scope']):
    build_the_network()
    tensorflow.contrib.quantize.create_training_graph(input_graph=full_precision_graph, quant_delay=0)
    ......

I intend to train a int8 model from a pre-trained f32 ckpt model. However, the error raised as 

    ......
    netname/act_quant/max not found in checkpoint
    ......

I am wondering if something wrong with my usage of the quantization creating. I only defined the train quantization net and the screen did print out something like the following information before the error occurred

    ......
    INFO:tensorflow:Skipping netname/conv3_eltwise4/add, because its followed by an activation.
    ....

**Comment by asjmasjm** [comment]
Okay I know the problem. No such error if I train from the scratch...So what's the correct way to train from a pre-trained f32 model that contains no elements like /act_quant/max?

**Comment by asjmasjm** [comment]
I kinda solved it...In case of fine-tuning from full-precision model without quantization parameters like .../act_quant/min, one just restore the weight and let the graph fill the default quantization parameters. Passing the tf.saver APIs using the existed weights and biases will do this. And I think the current tf APIs is enough to achives this and no need of extra support for this. Anyway, thanks for the attention from @ymodak.

**Comment by petewarden** [comment]
Thanks for the update, closing since it seems to be worked around now.

**Comment by shnamin** [comment]
@asjmasjm what is the workaround? I am using the export_inference_graph.py to export a quantized model, but I am getting the error FeatureExtractor/MobilenetV3/Conv/conv_quant/max not found in checkpoint. I have trained the model myself (starting from f32 but trained a quantized model).

**Comment by UndeadBlow** [comment]
Problem still unsolved.

**Comment by LLNLanLeN** [comment]
I'm also experiencing this issue as well, any insights or solutions would be great
