### ISSUE TITLE
Repeatedly allocating a graph and summary writer leaks memory

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#26684]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): I have
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): `v1.12.0-10061-gf3954bf900 1.13.1`
- Python version: 3.7.2
- Bazel version (if compiling from source): 0.23.1
- GCC/Compiler version (if compiling from source): `Apple LLVM version 10.0.0 (clang-1000.11.45.5)`
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

Repeatedly allocating a graph and making a summary writer leaks memory.

**Describe the expected behavior**

Memory should be freed when the graph leaves scope.

**Code to reproduce the issue**

```
#!/usr/bin/env python3

import resource
import tensorflow as tf

prev = 0
while True:
    peak = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    print(f'peak memory = {peak:,} (+{peak-prev:,})')
    prev = peak

    with tf.Graph().as_default(), tf.init_scope():
        tf.contrib.summary.create_file_writer('/tmp/tb')
```

**Other info / logs**

Here's what the output looks like:

```
peak memory = 174,493,696 (+174,493,696)
  
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

peak memory = 202,215,424 (+27,721,728)
peak memory = 202,264,576 (+49,152)
peak memory = 202,309,632 (+45,056)
peak memory = 202,358,784 (+49,152)
peak memory = 202,432,512 (+73,728)
peak memory = 202,473,472 (+40,960)
peak memory = 202,522,624 (+49,152)
peak memory = 202,567,680 (+45,056)
peak memory = 202,604,544 (+36,864)
peak memory = 202,641,408 (+36,864)
peak memory = 202,694,656 (+53,248)
peak memory = 202,739,712 (+45,056)
peak memory = 202,784,768 (+45,056)
peak memory = 202,829,824 (+45,056)
peak memory = 202,878,976 (+49,152)
peak memory = 202,919,936 (+40,960)
peak memory = 202,981,376 (+61,440)
peak memory = 203,026,432 (+45,056)
peak memory = 203,067,392 (+40,960)
...
peak memory = 999,665,664 (+49,152)
peak memory = 999,718,912 (+53,248)
peak memory = 999,768,064 (+49,152)
peak memory = 999,817,216 (+49,152)
peak memory = 999,866,368 (+49,152)
peak memory = 999,915,520 (+49,152)
peak memory = 999,964,672 (+49,152)
peak memory = 1,000,009,728 (+45,056)
peak memory = 1,000,058,880 (+49,152)
peak memory = 1,000,108,032 (+49,152)
peak memory = 1,000,161,280 (+53,248)
peak memory = 1,000,202,240 (+40,960)
peak memory = 1,000,255,488 (+53,248)
...
```

**Comment by girving** [comment]
Forgot that I was using a slightly messy TensorFlow tree.  I've reconfirmed that the bug persists at https://github.com/tensorflow/tensorflow/pull/26705, which is 5b24fba0857394dab67359963726b3bcce071575 plus a one line header include addition to make it build on my machine.

**Comment by girving** [comment]
No more TF bugs, @skye? :)

**Comment by skye** [comment]
@nfelt are you familiar with summary writers?

**Comment by girving** [comment]
@skye To clarify what I wrote wasn't intended to ask you to do anything, was just expressing sympathy as a fellow ex-tensorflow person who occasionally gets added to bugs.

**Comment by skye** [comment]
Haha no worries @girving, I just switched teams this week, so still figuring out what to do with all my github issues :)

**Comment by nfelt** [comment]
Thanks for the report.  I can reproduce this against last night's `tf-nightly` on both macOS and Linux (for anyone else reproducing, maxrss is in bytes on macOS but kb on linux, so the raw numbers are about 1000x smaller).

I also could still reproduce this even with `tf.init_scope()` removed.

cc @alextp if you have any intuition about what might be causing this.

**Comment by alextp** [comment]
@rohan100jain I think the issue is that SUMMARY_WRITER_INIT_OP keeps a strong reference to the graph instead of a weak reference, so the graph can never be GC'd.

**Comment by girving** [comment]
It looks like there are two problems, one large and one small:

**Large:** Every `tf.Operation` has a strong reference to the graph it lives inside (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L1921).  This should probably be a weak reference.  This is presumably the cause of the leak, since we store a long lived reference to the op in `_SUMMARY_WRITER_INIT_OP ` at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/summary_ops_v2.py#L221.

**Small:** `_SUMMARY_WRITER_INIT_OP` should be something like a https://docs.python.org/3/library/weakref.html#weakref.WeakKeyDictionary with keys being the graphs, not keys being strings that live forever.  Even if we fix the large issue the small issue would remain, and thus pretty much any use of `_graph_key` is a bug.

**Comment by girving** [comment]
Update: I made a brief attempt at removing that one reference, but it didn't work, so I think there are others.  Probably a more concerted push is required.

**Comment by girving** [comment]
@alextp @rohan100jain Did you get a chance to look at this?  I want to make sure it isn't dropped, since it's blocking my upgrade of TensorFlow.

**Comment by alextp** [comment]
@nfelt can you look?

**Comment by girving** [comment]
What's the likely ETA here?  I'm still blocked from upgrading due to this, so if no one is planning to fix I'd like to know for my own planning purposes.

**Comment by nfelt** [comment]
I will try to take a closer look today, but if _SUMMARY_WRITER_INIT_OP isn't the main issue then I don't have a good guess at what the leak might be so it may take some time to figure this out.

Just so I understand, which upgrade path exactly are you blocked on?  Is this upgrading from tf.summary to tf.contrib.summary?  Or did you notice that this leak occurs across a TF version update?

**Comment by girving** [comment]
@nfelt Thanks!  The leak appears going from TensorFlow 1.12 to 1.13, so it's blocking the 1.13 upgrade (and therefore also my Python 3.7 upgrade).

**Comment by girving** [comment]
Note that it's quite possibly I simply failed to fix the `_SUMMARY_WRITER_INIT_OP` reference, but as I mentioned it does seem like every use of `_graph_key` is a bug, and therefore it feels likely that there are other strong references.

**Comment by martinwicke** [comment]
Can you check whether using `gc` frees the graph?

I.e., is this a simple reference cycle problem, or is a reference to the graph kept hidden someplace?

**Comment by martinwicke** [comment]
Ah... Of course as long as the summary init op reference exists, that won't help.

**Comment by girving** [comment]
Nope, `gc.collect` has no effect.

**Comment by nfelt** [comment]
Per discussion with @alextp I think what's easiest here is to revert the part of https://github.com/tensorflow/tensorflow/commit/aa8f428a9310b3fd8371bddf612e480b27618b2e that changed this from a graph collection to a python dict.  That seems very likely to be the root cause, and it was changed due to deprecation of global collections, but this is a 1.x-only usage anyway, and that seems like the easiest way to fix the regression.

**Comment by girving** [comment]
That sounds good.  Arguably global variables with references to graphs should be even more deprecated. :)

**Comment by girving** [comment]
I've confirmed that this fixes both my minimized test case and my unminimized test case.  Thank you @nfelt!

**Comment by nfelt** [comment]
Glad to hear that :)
