### ISSUE TITLE
build from src for //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#26685]
commit e7f508844eab13927f32abdb5d7f0eb4e91caee0
**System information**

== cat /etc/issue ===============================================
Linux luban-350 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="7 (Core)"
VERSION_ID="7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

== are we in docker =============================================
Yes

== compiler =====================================================
c++ (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux luban-350 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy                            1.14.1   
protobuf                         3.5.2    
tensorflow                       1.5.0rc1 
tensorflow-tensorboard           1.5.1    

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.5.0-rc1
tf.GIT_VERSION = v1.5.0-rc1-4-g04b3f6c
tf.COMPILER_VERSION = v1.5.0-rc1-4-g04b3f6c
Sanity check: array([1], dtype=int32)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
  File "tensorflow/python/platform/self_check.py", line 27, in <module>
    raise ImportError("Could not import tensorflow. Do not import tensorflow "
ImportError: Could not import tensorflow. Do not import tensorflow from its source directory; change directory to outside the TensorFlow source tree, and relaunch your Python interpreter from there.

== env ==========================================================
LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Thu Mar 14 15:31:33 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.72       Driver Version: 410.72       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   25C    P0    52W / 250W |     10MiB / 22919MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 00000000:03:00.0 Off |                  N/A |
| N/A   22C    P0    53W / 250W |     10MiB / 22919MiB |     64%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           Off  | 00000000:83:00.0 Off |                  N/A |
| N/A   41C    P0    70W / 250W |  16779MiB / 22919MiB |     93%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           Off  | 00000000:84:00.0 Off |                  N/A |
| N/A   23C    P0    53W / 250W |     10MiB / 22919MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0.61
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-10.0/lib64/libcudart_static.a
/usr/local/cuda-10.0/lib64/libcudart.so.10.0.130
/usr/local/cuda-10.0/doc/man/man7/libcudart.7
/usr/local/cuda-10.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-9.0/doc/man/man7/libcudart.7
/usr/local/cuda-9.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-9.0/lib64/libcudart.so.9.0.176
/usr/local/cuda-9.0/lib64/libcudart_static.a
[luban@luban-350 tensorflow]$ 

**Describe the problem**

bazel  build -c opt -- //tensorflow/python/tools/...

**Any other info / logs**
```
cc1plus: warning: unrecognized command line option '-Wno-writable-strings'
ERROR: /home/luban/zhanghui/tensorflow/tensorflow/python/keras/api/BUILD:28:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/luban/.cache/bazel/_bazel_luban/64ebbf8410c89b3c0f2d97b092db8898/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/luban/.cache/bazel/_bazel_luban/64ebbf8410c89b3c0f2d97b092db8898/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 83, in <module>
    from tensorflow.python import keras
  File "/home/luban/.cache/bazel/_bazel_luban/64ebbf8410c89b3c0f2d97b092db8898/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/keras/__init__.py", line 30, in <module>
    from tensorflow.python.keras import datasets
  File "/home/luban/.cache/bazel/_bazel_luban/64ebbf8410c89b3c0f2d97b092db8898/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/keras/datasets/__init__.py", line 25, in <module>
    from tensorflow.python.keras.datasets import imdb
  File "/home/luban/.cache/bazel/_bazel_luban/64ebbf8410c89b3c0f2d97b092db8898/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/keras/datasets/imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/home/luban/.cache/bazel/_bazel_luban/64ebbf8410c89b3c0f2d97b092db8898/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/__init__.py", line 21, in <module>
    import keras_preprocessing
ImportError: No module named keras_preprocessing
INFO: Elapsed time: 2623.895s, Critical Path: 178.05s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 11634 processes: 11634 local.
FAILED: Build did NOT complete successfully
```

**Comment by GreatBoyFriend** [comment]
I  have the same problem, can you tell me how to solve it ?

**Comment by muglikar** [comment]
Me too.

> commit [e7f5088](https://github.com/tensorflow/tensorflow/commit/e7f508844eab13927f32abdb5d7f0eb4e91caee0)
> **System information**
> 
> == cat /etc/issue ===============================================
> Linux luban-350 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> VERSION="7 (Core)"
> VERSION_ID="7"
> CENTOS_MANTISBT_PROJECT_VERSION="7"
> REDHAT_SUPPORT_PRODUCT_VERSION="7"
> 
> == are we in docker =============================================
> Yes
> 
> == compiler =====================================================
> c++ (GCC) 8.3.0
> Copyright (C) 2018 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions. There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> == uname -a =====================================================
> Linux luban-350 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> 
> == check pips ===================================================
> numpy 1.14.1
> protobuf 3.5.2
> tensorflow 1.5.0rc1
> tensorflow-tensorboard 1.5.1
> 
> == check for virtualenv =========================================
> False
> 
> == tensorflow import ============================================
> tf.VERSION = 1.5.0-rc1
> tf.GIT_VERSION = v1.5.0-rc1-4-g04b3f6c
> tf.COMPILER_VERSION = v1.5.0-rc1-4-g04b3f6c
> Sanity check: array([1], dtype=int32)
> Traceback (most recent call last):
> File "", line 1, in
> File "tensorflow/**init**.py", line 24, in
> from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
> File "tensorflow/python/**init**.py", line 49, in
> from tensorflow.python import pywrap_tensorflow
> File "tensorflow/python/pywrap_tensorflow.py", line 25, in
> from tensorflow.python.platform import self_check
> File "tensorflow/python/platform/self_check.py", line 27, in
> raise ImportError("Could not import tensorflow. Do not import tensorflow "
> ImportError: Could not import tensorflow. Do not import tensorflow from its source directory; change directory to outside the TensorFlow source tree, and relaunch your Python interpreter from there.
> 
> == env ==========================================================
> LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:
> DYLD_LIBRARY_PATH is unset
> 
> == nvidia-smi ===================================================
> Thu Mar 14 15:31:33 2019
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 410.72 Driver Version: 410.72 CUDA Version: 10.0 |
> |-------------------------------+----------------------+----------------------+
> | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
> | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
> |===============================+======================+======================|
> | 0 Tesla P40 Off | 00000000:02:00.0 Off | N/A |
> | N/A 25C P0 52W / 250W | 10MiB / 22919MiB | 100% Default |
> +-------------------------------+----------------------+----------------------+
> | 1 Tesla P40 Off | 00000000:03:00.0 Off | N/A |
> | N/A 22C P0 53W / 250W | 10MiB / 22919MiB | 64% Default |
> +-------------------------------+----------------------+----------------------+
> | 2 Tesla P40 Off | 00000000:83:00.0 Off | N/A |
> | N/A 41C P0 70W / 250W | 16779MiB / 22919MiB | 93% Default |
> +-------------------------------+----------------------+----------------------+
> | 3 Tesla P40 Off | 00000000:84:00.0 Off | N/A |
> | N/A 23C P0 53W / 250W | 10MiB / 22919MiB | 99% Default |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes: GPU Memory |
> | GPU PID Type Process name Usage |
> |=============================================================================|
> +-----------------------------------------------------------------------------+
> 
> == cuda libs ===================================================
> /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0.61
> /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart_static.a
> /usr/local/cuda-10.0/lib64/libcudart_static.a
> /usr/local/cuda-10.0/lib64/libcudart.so.10.0.130
> /usr/local/cuda-10.0/doc/man/man7/libcudart.7
> /usr/local/cuda-10.0/doc/man/man7/libcudart.so.7
> /usr/local/cuda-9.0/doc/man/man7/libcudart.7
> /usr/local/cuda-9.0/doc/man/man7/libcudart.so.7
> /usr/local/cuda-9.0/lib64/libcudart.so.9.0.176
> /usr/local/cuda-9.0/lib64/libcudart_static.a
> [luban@luban-350 tensorflow]$
> 
> **Describe the problem**
> 
> bazel build -c opt -- //tensorflow/python/tools/...
> 
> **Any other info / logs**
> 
> ```
> cc1plus: warning: unrecognized command line option '-Wno-writable-strings'
> ERROR: /home/luban/zhanghui/tensorflow/tensorflow/python/keras/api/BUILD:28:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
> Traceback (most recent call last):
>   File "/home/luban/.cache/bazel/_bazel_luban/64ebbf8410c89b3c0f2d97b092db8898/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
>     from tensorflow.python.tools.api.generator import doc_srcs
>   File "/home/luban/.cache/bazel/_bazel_luban/64ebbf8410c89b3c0f2d97b092db8898/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 83, in <module>
>     from tensorflow.python import keras
>   File "/home/luban/.cache/bazel/_bazel_luban/64ebbf8410c89b3c0f2d97b092db8898/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/keras/__init__.py", line 30, in <module>
>     from tensorflow.python.keras import datasets
>   File "/home/luban/.cache/bazel/_bazel_luban/64ebbf8410c89b3c0f2d97b092db8898/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/keras/datasets/__init__.py", line 25, in <module>
>     from tensorflow.python.keras.datasets import imdb
>   File "/home/luban/.cache/bazel/_bazel_luban/64ebbf8410c89b3c0f2d97b092db8898/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/keras/datasets/imdb.py", line 25, in <module>
>     from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
>   File "/home/luban/.cache/bazel/_bazel_luban/64ebbf8410c89b3c0f2d97b092db8898/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/__init__.py", line 21, in <module>
>     import keras_preprocessing
> ImportError: No module named keras_preprocessing
> INFO: Elapsed time: 2623.895s, Critical Path: 178.05s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
> INFO: 11634 processes: 11634 local.
> FAILED: Build did NOT complete successfully
> ```

Me too have same issue. How to fix it?

**Comment by yaniv148** [comment]
See https://github.com/tensorflow/tensorflow/issues/36903 which worked for me. Basically:

pip3 install Keras-Preprocessing
