### ISSUE TITLE
Iterate on dataset/iterator when using @tf.function

### ISSUE THREAD

**Issue by galeone** [tensorflow/tensorflow#26687]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Archlinux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-dev20190312
- Python version: 3.6
- CUDA/cuDNN version: 10
- GPU model and memory: 1080 Ti

**Describe the current behavior**

Can't convert the dataset/iterator to its graph representation: I'm forced to loop in eager mode, but I want to have a graph representation of the loop too (since I need to export a SavedModel that contains the loop itself).

**Describe the expected behavior**

The iterator / the dataset should be converted in its graph representation.

**Code to reproduce the issue**

A code that loops using Tensorflow primitives (like `for i in tf.range(10)`) can be converted into its graph representation without any problem, while a code that creates a python iterator from a dataset object (using `iter(dataset)`) can't.

Moreover, maybe because we are in the early stage of the development, I'm unable to convert a loop that loops over a dataset to its graph representation.

```python
import tensorflow as tf

def real_gen():
    for i in range(10):
        yield i

dataset = tf.data.Dataset.from_generator(real_gen, (tf.float32))

@tf.function
def itertest():
    tf.print(next(iter(dataset)))
itertest()

@tf.function
def loopiter():
    for real in dataset:
        tf.print(real)
loopiter()
```

The `itertest()` call fails because `RuntimeError: dataset.__iter__() is only supported when eager execution is enabled.`

While the `loopiter()` call fails because `tensorflow.python.framework.errors_impl.NotFoundError: Function __inference_Dataset_flat_map_flat_map_fn_22 is not defined.
         [[{{node ReduceDataset}}]] [Op:__inference_loopiter_35]`

**Comment by jsimsa** [comment]
I am closing this issue as this should now be supported as for TF 1.14 and TF 2.0-beta. Please verify and if you encounter a problem re-open this issue with up-to-date information.
