### ISSUE TITLE
remove SpaceToBatchND, Mul, BatchToSpaceND, Add Ops for tflite

### ISSUE THREAD

**Issue by ilous12** [tensorflow/tensorflow#26693]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No):NO

**Describe the feature and the current behavior/state.** 

I saw "deeplabv3_257_mv_gpu's network and there is no below ops.

> SpaceToBatchND, Mul, BatchToSpaceND, Add

I want to change it like that.

Thanks.

**Will this change the current api? How?** NO

**Who will benefit with this feature?** Everyone

**Any Other info.** None

**Comment by jvishnuvardhan** [comment]
@ilous12 Could you explain your issue with more details? Thanks!

**Comment by ilous12** [comment]
hi @jvishnuvardhan 

I uploaded Visualized image for models. Network nodes are different and I painted a circle on our tflite network. What should I do to configure like google's deeplabv3_257_mv_gpu?

**google's deeplabv3_257_mv_gpu**
![deeplabv3_257_mv_gpu](https://user-images.githubusercontent.com/3174693/54402090-180b0380-470e-11e9-91a2-fa41f5f130a9.png)

**our converted tflite model** Problem
![deeplab_257_gpu](https://user-images.githubusercontent.com/3174693/54402117-31ac4b00-470e-11e9-864c-3c9bfdb8cd31.png)

**Comment by ilous12** [comment]
please let me know if you know to exclude operations.

**Comment by ilous12** [comment]
I resolved. Thanks

**Comment by jvishnuvardhan** [comment]
@ilous12 If possible, provide a solution here so that it might be helpful to the community. Thanks!

**Comment by SanthoshRajendiran** [comment]
#26474 

Not able to obtain speed up of Depthwise Conv2d Version 2, as flatten_atrous_conv is applied. Need suggestion on what kind of other conversion mechanism is there to obtain the advantages of Depthwiseconv2d.. Is there any other mechanism other than applying flatten_atrous_conv, to remove batch_to_space and space_to_batch?

**Comment by ajinkya933** [comment]
@ilous12 how did you  exclude operations?? I don't think its possible
