### ISSUE TITLE
the elapse time shown in timeline not match with count by hand

### ISSUE THREAD

**Issue by cklsoft** [tensorflow/tensorflow#26690]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 2.7.5
- CUDA/cuDNN version: 10/7
- GPU model and memory: 16G

**Describe the current behavior**

I have ran a program and use time.time()-start_time to calculate the elapse time (I have run 1000 times to get the average time), which is 5ms. But when use timeline in one run, I got 10ms+. So I doubt that, does `FULL_TRACE` will cost more time?

**Comment by jvishnuvardhan** [comment]
@cklsoft I think you can write time for each iteration into a file and check mean, standard deviation, etc. I think it is possible that FULL TRACE will cost couple of ms. 

Please post this kind of support questions in Stackoverflow. There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
