### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by kinsumliu** [tensorflow/tensorflow#267]
http://tensorflow.org/tutorials/mnist/pros/index.md#build_a_multilayer_convolutional_network

"See the Computation Graph section of Basic Usage for more detail."

Basic Usage
old: http://tensorflow.org/get_started/basic_usage.md
new: http://tensorflow.org/get_started/index.html#basic-usage

Computation Graph
old: http://tensorflow.org/get_started/basic_usage.md#the-computation-graph
new: http://tensorflow.org/get_started/index.html#the-computation-graph

**Comment by asseldonk** [comment]
I also found two broken links in this file: 
tensorflow/models/rnn/README.md

```
-* [RNN Tutorial](http://tensorflow.org/tutorials/recurrent/index.md)
-* [Sequence-to-Sequence Tutorial](http://tensorflow.org/tutorials/seq2seq/index.md)
```

**Comment by vrv** [comment]
Links are working now I think.
