### ISSUE TITLE
keras: Enabling eager mode breaks weights setting per kwargs in Layer constructors

### ISSUE THREAD

**Issue by kpe** [tensorflow/tensorflow#26700]
Enabling eager mode breaks the ability to specify layer weights in the constructor.

For example passing all-zeros weights to a dense layer results in all zero outputs (for `use_bias=False`). 
This is however not the case if eager mode is enabled, as the zero weights are not set; it seems to be known (see TODO by @fchollet), but I can't see why `set_weights` should not be called in non-eager mode: https://github.com/tensorflow/tensorflow/blob/5f071f2eb2321a8e4f46f16f706e9d743ec55554/tensorflow/python/keras/engine/base_layer.py#L660

to easily reproduce comment in/out the `tf.enable_eager_execution()` bellow:

```python
import unittest
import numpy as np
from tensorflow.python import keras as tfk
import tensorflow as tf

#tf.enable_v2_behavior()
tf.enable_eager_execution()

class EagerWeightsTest(unittest.TestCase):

    def test_eager_weights(self):
        weights = np.zeros((10, 11))                           # use zero weights
        dense = tfk.layers.Dense(units=11, input_shape=(10,),
                                 weights=[weights],
                                 use_bias=False)

        model = tfk.models.Sequential()
        model.add(dense)
        model.compile("adam", tfk.losses.mae)

        logits = model.predict(np.random.random((3, 10)))

        self.assertTrue(np.allclose(np.zeros((3, 11)),          # expect zero outputs
                                    logits))

```

**Comment by ymodak** [comment]
This is fixed with latest tf-nightly build version '1.15.0-dev20190808'. Thanks!
