### ISSUE TITLE
cannot use a placeholder dependent tensor as a initializer in get_variable

### ISSUE THREAD

**Issue by Nitinsiwach** [tensorflow/tensorflow#26716]
How does one go about creating variables with placeholders dependent tensors as initializers? The following graph breaks down with:

    InvalidArgumentError: You must feed a value for placeholder 'Placeholder_1' with dtype float
    	 [[node Placeholder_1 (defined at <ipython-input-10-b8d54264dc85>:3)  = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

My code:

    tf.reset_default_graph()
    a = tf.placeholder(dtype=tf.float32,shape=())
    d = tf.placeholder(dtype=tf.float32,shape=())
    b = tf.get_variable(name='b',initializer=d)
    c=a+d
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        print(sess.run(c, feed_dict={a:5.,d:10.}))

The documentation on initializers in tensorflow says:
>Initializer for the variable if one is created. Can either be an initializer object or a Tensor. If it's a Tensor, its shape must be known unless validate_shape is False.

However if i comment out the line where i create b the code seems to run. My fetch is not even dependent upon b.

How do i go about creating variables that initialize according to some placeholder?

**Comment by Near-Tam** [comment]
It doesn't need "sess.run(tf.global_variables_initializer())" because you has already initialize b as d, just run "print(sess.run(c, feed_dict={a:5.,d:10.}))" is ok.

**Comment by Near-Tam** [comment]
tf.reset_default_graph()
a = tf.placeholder(dtype=tf.float32,shape=())
d = tf.placeholder(dtype=tf.float32,shape=())
b = tf.get_variable(name='b',initializer=d)
c=a+d
with tf.Session() as sess:
    # sess.run(tf.global_variables_initializer())
    print(sess.run(c, feed_dict={a:5.,d:10.}))

**Comment by Nitinsiwach** [comment]
What if i want to run `tf.global_variables_initializer()`? 

```
a = tf.placeholder(dtype=tf.float32,shape=())
b = tf.get_variable(name='b',initializer=a)
e = tf.get_variable(name='e',initializer=tf.constant(2.))
c=a+b+e
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(c, feed_dict={a:5.}))
```

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
