### ISSUE TITLE
Docker latest images are using tf 2.0.0a0

### ISSUE THREAD

**Issue by SimSimY** [tensorflow/tensorflow#26715]
**System information**
- Have I written custom code: **No**
- OS Platform and Distribution: **Linux Ubuntu 16.04**
- TensorFlow installed from: **binary**
- TensorFlow version (use command below): **2.0.0a0** (script is however broken, see below)
- Python version: 2.7.12 / 3.5.2
- CUDA/cuDNN version: **any**
- GPU model and memory: **any**

> You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
> You can also obtain the TensorFlow version with
> python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
> 
While this is not the issue itself, its worth mentioning that both are broken 
```
Traceback (most recent call last):
  File "/tmp/check_tf.py", line 2, in <module>
    print("tf.VERSION = %s" % tf.VERSION)
AttributeError: 'module' object has no attribute 'VERSION'
```

**Describe the current behavior**
**The Docker `latest` family contains tensorflow version 2.0.0a0.** 

**Describe the expected behavior**
The Docker `latest` family should contain  tensorflow version 1.13.*. 

According to the docs (and docker convention), the `latest` docker images should contain the latest  **stable** version, as in 1.13 while the nightly images should contain the unstable images, such us alphas, betas and RCs
**Code to reproduce the issue**
`docker run -it --rm tensorflow/tensorflow  pip list 2>&1 | grep tensorflow`
`docker run -it --rm tensorflow/tensorflow:latest-py3  pip list 2>&1 | grep tensorflow`
(the issue persists in docker versions as well)

**Other info / logs**
<img width="311" alt="Screen Shot 2019-03-14 at 22 56 17" src="https://user-images.githubusercontent.com/1699509/54392157-8f5d7a80-46af-11e9-8b00-9e4e1979db6a.png">

**Comment by SimSimY** [comment]
Also: 
docker run --rm -it tensorflow/tensorflow:1.12.0-gpu-py3 
is actually jupyter version

**Comment by angersson** [comment]
Thanks for reporting this. It looks like it's probably a mistake in the way our CI handles PyPi pre-releases. "Latest" usually refers to pre-releases, but since 2.0 is more of an alpha, the CI gets confused with PyPI's limited classification system.

In the meantime, if you run into this, please use the numbered tag directly instead of "latest", which will be accurately tagged.

**Comment by angersson** [comment]
With regards to the 1.12.0 images, only the images newer than 1.13 use the newer Dockerfiles, and we haven't rebuilt them to avoid breaking anyone who depends on the old structure. There's a note about this at the top of the Docker Hub repository.

**Comment by angersson** [comment]
I've fixed the underlying issue and re-tagged the `latest` images to be based on the `1.13.1` images. Thanks!
