### ISSUE TITLE
image_retraining example creates inconsistently named nodes when run multiple times

### ISSUE THREAD

**Issue by kuza55** [tensorflow/tensorflow#2671]
I don't know if this is a thing you want to support, but I've been running the image_retraining example from Jupyter like so:

FLAGS._parse_flags()
FLAGS.image_dir = '/data/corpus'
FLAGS.output_graph = '/data/output_graph4.pb'
FLAGS.output_labels = '/data/output_labels4.txt'
FLAGS.bottleneck_dir = '/data/bottleneck/'
FLAGS.model_dir = '/data/imagenet/'

main('')

Unlike the example, I end up running the example multiple times in the same python process, and .: in the same default graph, so everything after the first run is badly named when output, i.e. instead of being named DecodeJpeg, I found DecodeJpeg_3

Adding tf.reset_default_graph() to the top of main fixes this.

**Comment by girving** [comment]
This is expected behavior.  TensorFlow ensures that names are unique within the same graph, so if you generate the same ops twice without changing graphs you'll get different names.

**Comment by trinity77** [comment]
Trigger update_date
