### ISSUE TITLE
Large Variation in Compute Times

### ISSUE THREAD

**Issue by xilenteyex** [tensorflow/tensorflow#26713]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1 LTS
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12.0
- Python version: Python 2.7.15rc1
- Bazel version (if compiling from source): 0.21
- GCC/Compiler version (if compiling from source): (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: 10.0/7.4.2
- GPU model and memory: NVIDIA Corporation GP104GL [Quadro P5000] (2 GPUs)

**Describe the current behavior**
I am running a toy matrix multiplication example multiple times on TensorFlow ([code here](https://github.com/xilenteyex/toy_matmul_tf)). When I look into the timeline for multiple iterations, I see an increase in the time to compute the same graph over multiple iterations. Specifically, look at these three timelines:
[Timeline 1](https://github.com/xilenteyex/toy_matmul_tf/blob/master/logs/timeline_matmul_2.15_1_.ctf.json)
[Timeline 3](https://github.com/xilenteyex/toy_matmul_tf/blob/master/logs/timeline_matmul_2.15_3_.ctf.json)
[Timeline 8](https://github.com/xilenteyex/toy_matmul_tf/blob/master/logs/timeline_matmul_2.15_8_.ctf.json)
For **MatMul_25**, [first iteration](https://github.com/xilenteyex/toy_matmul_tf/blob/master/logs/timeline_matmul_2.15_1_.ctf.json) shows compute time to be ~8000 ms, while [3rd iteration](https://github.com/xilenteyex/toy_matmul_tf/blob/master/logs/timeline_matmul_2.15_3_.ctf.json) shows that compute time is ~15000 ms and [8th iteration](https://github.com/xilenteyex/toy_matmul_tf/blob/master/logs/timeline_matmul_2.15_8_.ctf.json) shows that compute time is ~27000 ms.

**Describe the expected behavior**
I expect compute times of the same matrix multiplication operation to be stay similar over multiple iterations instead of increasing linearly. Is this the expected behavior or am I missing something ?

**Code to reproduce the issue**
[code to rerun the toy example can be found here.](https://github.com/xilenteyex/toy_matmul_tf)

**Other info / logs**
[Timelines generated when I ran the code are in this folder](https://github.com/xilenteyex/toy_matmul_tf/tree/master/logs)

**Comment by xilenteyex** [comment]
I am trying to write a custom graph partitioner and am stuck on this issue for a very long time. If someone can help me figure this out, it will be great. Thanks!

**Comment by xilenteyex** [comment]
@penpornk, it will be great if can comment on this issue.
Thanks!

**Comment by penpornk** [comment]
@xilenteyex I'm so sorry for the delay! I'll look into this soon!

**Comment by penpornk** [comment]
Cc'ing our GPU expert, @reedwm, as I mostly work on the CPU side.

**Comment by jvishnuvardhan** [comment]
@xilenteyex This is a stale issue. Looks like this was resolved in recent TF1.x version. I have tried your code with `TF1.15.5` on colab and I cannot reproduce the issue. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/d9108463d8a114d71d69c1ec4bd9ae96/untitled1033.ipynb#scrollTo=lm7rbzxeXUYy)

Also, please note that there is no support for `TF1.x` issues.

I am closing this issue as this was resolved. Please feel free to reopen the issue (if it persists) after testing with `TF2.x`. Thanks!
