### ISSUE TITLE
how to use the saved model after trained to detect new pictures

### ISSUE THREAD

**Issue by michaelmart77** [tensorflow/tensorflow#26719]
Hi all,
this might be repeated question.
I trained classifier on cats, dogs. and saved the model. Now I want to use the saved trained model to detect new pictures. How to do this? Is there a code for this?

Thanx

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
