### ISSUE TITLE
Numpy operation on List of Tensor is considerably slow.

### ISSUE THREAD

**Issue by HanGuo97** [tensorflow/tensorflow#26711]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Docker
- TensorFlow version (use command below): 2.0.0-alpha
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.
- GPU model and memory: V100

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Numpy operations on a list of Tensor is considerably slow. Commands to reproduce the results and corresponding time are shown below in the screenshot below.

![image](https://user-images.githubusercontent.com/18187806/54388179-8f3f8980-4673-11e9-8009-a076402333c4.png)

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rmothukuru** [comment]
@HanGuo97,
I executed your code with the **`latest version of Tensorflow (2.4.1)`**  and observed that the **`Numpy Operation`** on **`List`** of **`Tensor`** is faster enough. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/587dd5ce7c60fc9fb835eb17253eb106/gh_26711.ipynb) of the working code. Thanks!

**Comment by HanGuo97** [comment]
Thanks!
