### ISSUE TITLE
densetnet.pb not correct result

### ISSUE THREAD

**Issue by lyuchuny3** [tensorflow/tensorflow#26726]
Hi, 
I download to model from https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/densenet_2018_04_27.tgz
There are:
* densenet.pb
* label.txt
* readme.md (said that densenet.pb use vgg_preprocess)
inside `densenet_2018_04_27`:

 I try one random picture `bike.jpg`, the result top1 is `828`. However, the 828-th category in `label.txt` is not something like bike.

My proprocess is:
```
 img=cv2.imread(img_path)
 img=cv2.resize(img_path,(224,224))
 img=img.astype(np.float32)[...,::-1]
 img-=[123.68,116.78,103.94]
 img/=128.
```

**Comment by jvishnuvardhan** [comment]
@lyuchuny3 
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. If you think this could be a bug then please fill the template and provide a code (GitHub gist) to reproduce the bug. Thanks!
