### ISSUE TITLE
libc.so.6 : GLIBC_2.14 not found. Instruct Tensorflow to look for glibc in custom path.

### ISSUE THREAD

**Issue by kitmonisit** [tensorflow/tensorflow#26728]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1
- Python version: 3.6.2
- Installed using virtualenv? pip? conda?: Still at build phase
- Bazel version (if compiling from source): 0.20.0
- GCC/Compiler version (if compiling from source): gcc-5.5.0 (installed from Linuxbrew)
- CUDA/cuDNN version: N/A
- GPU model and memory: 16GB RAM

**Describe the problem**

My computer has a rather old `glibc-2.12` and since I'm not an admin, there's nothing I can do to change that. Upon trying to build Tensorflow, I'd get an error along the lines of `$SECRET_PATH/lib64/libc.so.6 : GLIBC_2.14 not found`, which implies that the Tensorflow build system looks for `glibc` in the standard system paths.

However, I have been able to install `glibc-2.23` into `$HOME/.linuxbrew`. I cannot simply do `LD_LIBRARY_PATH=$HOME/.linuxbrew/lib:$LD_LIBRARY_PATH <tensorflow build commands>` because it would segfault all the other utilities.

How do I instruct the Tensorflow build system to look for `glibc` within `$HOME/.linuxbrew`? Which files should I edit?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
$ cd ~
$ mkdir build-bazel
$ cd build-bazel
$ wget https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-dist.zip
$ unzip bazel-0.20.0-dist.zip
$ env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
$ cd ~
$ mkdir build-tensorflow
$ cd build-tensorflow
$ wget https://codeload.github.com/tensorflow/tensorflow/zip/v1.13.1 -O tensorflow-1.13.1.zip
$ unzip tensorflow-1.13.1.zip
$ cd tensorflow-1.13.1
$ PATH=$HOME/build-bazel/output:$PATH ./configure
$ PATH=$HOME/build-bazel/output:$PATH bazel build --config=monolithic //tensorflow/tools/pip_package:build_pip_package
```

In another issue #26432, I had succeeded in building Tensorflow with Python 3.7.2 (installed from Linuxbrew, and likely linked with the Linuxbrew `glibc-2.23`). In this issue, however, I am building it with Python 3.6.2 (official office Python), which I suspect may have been linked with the old `glibc-2.12`.

For various reasons I need to build with Python 3.6.2.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gunan** [comment]
I think you can use these options of bazel to direct it to use different toolchains.
Before trying each environment change, you may need to run `bazel clean --expunge`
https://docs.bazel.build/versions/master/be/make-variables.html#custom_variables
