### ISSUE TITLE
[Feature] Support RISCV with tfcompile --target_tuple

### ISSUE THREAD

**Issue by arcbbb** [tensorflow/tensorflow#26727]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
third_party/llvm/llvm.autogenerated.BUILD supports AArch64, ARM, PowerPC, and X86 in llvm_target_list, so I can use 'tfcompile --target_triple=aarch64-none-android' to generate  AArch64 ELF object.
It seems the tool that generates llvm.autogenerated.BUILD is not released yet, I suggest adding a RISCV target in llvm.autogenerated.BUILD.

**Will this change the current api? How?**
No.
**Who will benefit with this feature?**
People who use RISCV cpus.
**Any Other info.**

**Comment by gunan** [comment]
@jpienaar do you think we can add this?
I am guessing there may be other build bugs we can encounter, but after llvm.autogenerated.BUILD is updated, the community can take over and fix those.

**Comment by jpienaar** [comment]
Yes it could be added. As Gunan mentioned a caveat is that it would be best effort.

@bixia1 for visibility as she knows this area better than me.
