### ISSUE TITLE
[doc] use links in deprecation notice

### ISSUE THREAD

**Issue by ngc92** [tensorflow/tensorflow#26739]
Many deprecated functions currently contain a notice such as
```
Warning: THIS FUNCTION IS DEPRECATED. It will be removed in a future version. Instructions for updating: Use tf.data.experimental.ignore_errors().
```
It would be really nice if the suggested replacement would actually link to the corresponding documentation.

**Comment by jvishnuvardhan** [comment]
@ngc92 I think this was resolved. As you requested, the deprecation warning includes link to the corresponding documentation. For example, please check [this page](https://www.tensorflow.org/api_docs/python/tf/compat/v1/data/Dataset) on TF website. Thanks!

I am closing this issue as this was resolved. Feel free to reopen if I am mistaken. Thanks!
