### ISSUE TITLE
Expected to see 2 array(s), but instead got the following list of 1 arrays

### ISSUE THREAD

**Issue by StephenLouis** [tensorflow/tensorflow#26733]
I want to create a model that receive one image and compute the image by two Softmax(two output). The code is:

-------------------------------------------------
`base_model = InceptionV3(include_top=False)`
`x = base_model.output`
`x = GlobalAveragePooling2D()(x)`

# first Softmax
`x_1 = Dense(1024, activation='relu')(x)`
`predictions_1 = Dense(4, activation='softmax')(x_1)`

# second Softmax
`x_2 = Dense(1024, activation='relu')(x)`
`predictions_2 = Dense(4, activation='softmax')(x_2)`

`my_model = Model(inputs=base_model.input, outputs=[predictions_1,predictions_2])`

# train
`my_model.compile(...)`
`my_model.fit_generator(...)`
-------------------------------------------------

When training, I got error:

ValueError: 
Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],...

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
