### ISSUE TITLE
[TF2.0] Embedding batch_input_shape not aware of distribute.MirroredStrategy()

### ISSUE THREAD

**Issue by tlkh** [tensorflow/tensorflow#26763]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes, modified an [example from Seedbank](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/sequences/text_generation.ipynb#scrollTo=MtCrdfzEI2N0) to use with TF2.0
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip binary
- TensorFlow version (use command below): ` 2.0.0-alpha0`; `git v1.12.0-9492-g2c319fb415`
- Python version: 3.6
- Bazel version (if compiling from source): NIL
- GCC/Compiler version (if compiling from source): NIL
- CUDA/cuDNN version: 10.0
- GPU model and memory: V100 16GB

**Describe the current behavior**

1. when `batch_input_shape` is **not** specified in `tf.keras.layers.Embedding`
With or without `distribute.MirroredStrategy()`, model works perfectly fine
2. when `batch_input_shape` **is** specified in `tf.keras.layers.Embedding`
Without `distribute.MirroredStrategy()`, model works perfectly fine, But with `distribute.MirroredStrategy()`, **`tf.data.Dataset` splits the inputs to the model correctly, but the model's expected input is not correct**

* The model replicas **each** expect `batchsize_per_replica * replica` (the un-split output from `Dataset`) instead of  `batchsize_per_replica` (split output from `Dataset`).
* If the model's `batch_input_shape` or `Dataset` output is adjusted to match the above expectation, the keras Model immediately errors out as it expects `batchsize_per_replica * replica`, split to `batchsize_per_replica` as an input to **each** model replica.

"Illustrated Example":
```
> batchsize = 4*128
> batchsize_per_replica = 128
> model batch_input_shape = 4*128
> model replica expects 4*128 causing error

> batchsize = 4*128
> batchsize_per_replica = 128
> model batch_input_shape = 128
> model expects 4*128 causing error
```

It seems like the problem is everywhere else, the batch size etc. is calculated correctly, except when `batch_input_shape` is specified in `tf.keras.layers.Embedding`. If anyone is wondering why we need to specify this, this is for stateful RNNs to work.

**Describe the expected behavior**

When the scope is `distribute.MirroredStrategy()`, `tf.keras.layers.Embedding` specified `batch_input_shape` should also be divided by the number of replicas.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

The notebook below contains code that will reproduce the error on a **multi-GPU** system. On Colab, there is only one GPU hence it runs fine, since `distribute.MirroredStrategy()` only creates one replica. However, with two or more replicas on a multi-GPU system, the error is observed.

[Notebook presented on Google Colab](https://colab.research.google.com/drive/1R3h2Jf9rKCsi952KLcg7b8PtPyyXgx6b)

There is a header/section that shows the model training with and without `distribute.MirroredStrategy()`. 

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Following the Colab notebook above, when training is run on a 4 GPU system (overall `batch_size=128`, `batchsize_per_replica=32`), the error is:

```
Invalid input_h shape: [1,128,256] [1,32,256]
	 [[{{node replica_3/unified_lstm_2/CudnnRNN}}]]
	 [[replica_1/loss/dense_1_loss/loss/weighted_loss/broadcast_weights/assert_broadcastable/is_valid_shape/else/_48/has_valid_nonscalar_shape/then/_207/has_invalid_dims/concat/_374]] [Op:__inference_keras_scratch_graph_10991]
```

Notebook that shows the entire run resulting in the above error can be seen [here](https://nbviewer.jupyter.org/github/tlkh/arxiv-lm/blob/master/tf_distributed_embedding_bugreport.ipynb)

If you modify `batch_input_shape` to match for `batchsize_per_replica` (32):

```
ValueError: The batch output shape of your `Dataset` is 128, which is incompatible with the specified batch size of your Input Layer: 32
```

In all cases, `model.summary()` gives the same result:

```
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
embedding_1 (Embedding)      (128, None, 128)          8320      
_________________________________________________________________
unified_lstm_2 (UnifiedLSTM) (128, None, 256)          394240    
_________________________________________________________________
unified_lstm_3 (UnifiedLSTM) (128, None, 256)          525312    
_________________________________________________________________
dense_1 (Dense)              (128, None, 65)           16705     
=================================================================
Total params: 944,577
Trainable params: 944,577
Non-trainable params: 0
```

**The exact same code will run fine on single GPU system even with `distribute.MirroredStrategy()` as the scope**, you can [view Colab demo](https://colab.research.google.com/drive/1R3h2Jf9rKCsi952KLcg7b8PtPyyXgx6b)

**Comment by tlkh** [comment]
#26245 shows a similar error, but somewhat different in nature

1. That one is with Keras `multi_gpu_model` (I believe this is not recommended any more with TF2.0?)
2. That one gives an error even when `batch_input_shape` is not specified, whereas in my case it works fine

**Comment by ghego** [comment]
@tlkh why is `multi_gpu_model` not recommended with TF 2.0 any longer?

**Comment by tlkh** [comment]
@ghego With TF 2.0, tf.Keras works out of the box with `tf.distribute.MirroredStrategy`. My own experience is that it is much nicer to use. Check out: https://www.tensorflow.org/alpha/tutorials/distribute/keras

**Comment by ghego** [comment]
yep, I've seen that. Thanks

**Comment by qlzh727** [comment]
Assigning to Priya since this seems to be related with distribution strategy. Please reassign to someone who owns the embedding if the fix should be on that side.

**Comment by isaprykin** [comment]
It should be fixed after https://github.com/tensorflow/tensorflow/commit/a3f9c59153203020dcd008527db5247deefad95a.  Could you please try and re-open if that doesn't help?
