### ISSUE TITLE
Improve testing infrastructure to prevent breaking open source builds

### ISSUE THREAD

**Issue by samikama** [tensorflow/tensorflow#26776]
Recently pushes to the master branch done by tensorflow gardener frequently breaking the open source builds from the master and that is hindering the development on top of the tree by requested/suggested by google engineers through various configurations. Would it be possible to improve the testing of internal to external merges to make sure that opensource builds are not broken by a push from internal repositories?.

For example a push made today left master in broken state. In line https://github.com/tensorflow/tensorflow/blob/9a43dfeac58477c37cb356e3759b053d2bbd0247/tensorflow/tensorflow.bzl#L2189
some environment variables are referred however bazel clears the environment for genrules, we end up with an error message like below and can't build TF right now. It is possible to fix such issues but it likely to cost time for multiple people. Would it be possible to add a test that does a build with the instructions at [installation/build from source](https://www.tensorflow.org/install/source) still works.

`   (cd /ssdscratch/.cache/bazel/_bazel_skama/184fadfe649ebd4ee26f07bbb482f004/execroot/org_tensorflow && \
  exec env - \
    PATH=/ssdscratch/work/XLAInt8/tensorflow/build/bin:/home/skama/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorflow/tools/build_info/gen_build_info --raw_generate "bazel-out/host/genfiles/tensorflow/python/platform/build_info.py" --build_config cuda --key_value  cuda_version_number=${TF_CUDA_VERSION} cudnn_version_number=${TF_CUDNN_VERSION} ')
Execution platform: @bazel_tools//platforms:host_platform
/bin/bash: TF_CUDA_VERSION: unbound variable
Target //tensorflow/tools/pip_package:build_pip_package failed to build
`

**Comment by sushreebarsa** [comment]
@samikama Could you please let us know if this is still an issue ?Thanks!
