### ISSUE TITLE
[TF2.0] Possibly wrong path to decode_predictions in keras

### ISSUE THREAD

**Issue by Sri-vatsa** [tensorflow/tensorflow#26778]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version: 3.6.5_1/2.7.15
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

Currently, Mobilenet_V2 Keras in `tensorflow/python/keras/applications/mobilenet_v2.py` references the function `decode_predictions` from `keras_applications.mobilenet_v2` [here](https://github.com/keras-team/keras-applications/blob/master/keras_applications/mobilenet_v2.py)
 
**Describe the expected behavior**

`decode_predictions` seems to be from `keras_applications.imagenet_utils` [here](https://github.com/keras-team/keras-applications/blob/master/keras_applications/imagenet_utils.py) instead. 

**Code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.
NA

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
NA

**Comment by Sri-vatsa** [comment]
If this is not intended, I will create a PR to fix it.

**Comment by ymodak** [comment]
The ```mobilenet_v2.py```  and ```imagenet_utils.py``` are referencing the decode_predictions correctly.
