### ISSUE TITLE
LSTM simple example 

### ISSUE THREAD

**Issue by RadjaHachilif** [tensorflow/tensorflow#26771]
Hello,
I'm writing a simple LSTM function that executes the following operations on a random input x:

i{t}=sigma(W{i}x{t}+R{i}h{t-1}+b{i})
f{t}=sigma(W{f}x{t}+R{f}h{t-1}+b{f})
o{t}=sigma(W{o}x{t}+R{o}h{t-1}+b{o})
c'{t}=tanh(W{c}x{t}+R{c}h{t-1}+b{c})
c{t}=f{t} o c{t-1}+i{t} o c'{t}
h{t}=o{t} o tanh(c{t})

To test the performance of my code I want to use Tensorflow XLA. With all the examples I found, I could not create a simple function as this ( I couldn't find out how to initialize a random size input with random values, initialize weights and define the output size)
Could anyone help me implement this function using Tensorflow XLA ?

**Comment by ymodak** [comment]
@jlebar

**Comment by jlebar** [comment]
Hi, @RadjaHachilif.

Github Issues are for bugs in TensorFlow, not for support requests.  There are separate mailing lists for this.  See https://www.tensorflow.org/community/forums.  Or you can try StackOverflow.

I know it can be frustrated to be told "good question, wrong venue", but if we don't keep these separate, our processes will fall apart in a bad way.

We try to be very up-front about this.  When you filed the bug, you should have seen some text  that links to https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md.

To save you a round-trip, when answering your question on a mailing list I'd need more information to help you.  What is the exact TensorFlow code you are running, and how have you attempted to enable XLA?  What version of TF are you running, and on what operating system?  That sort of thing.  (I believe some of these are actually requested when you file a github issue?)  The more details you can provide the more likely it is that you'll be able to get assistance.

I'm going to close this bug.  Good luck getting help!

**Comment by jlebar** [comment]
(@ymodak fyi is it possible to get responses like the above when someone files a bug that's not actually a bug?  Would save some dev time.)

**Comment by ymodak** [comment]
@jlebar Sure will make a note of it. Thanks for taking a look.
