### ISSUE TITLE
How do I allow growth with eager execution?

### ISSUE THREAD

**Issue by catskillsresearch** [tensorflow/tensorflow#26777]
This is a generic question.   I am working locally from a copy of [a Colab notebook](https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb), which uses eager execution.

I notice that the notebook allocates all of the memory on my GPU right away.  So I can track what commands use what memory, I would like it to not do that.  According to [this StackOverflow article:](https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory) I should do this in the code before it grabs all the memory:

```
config = tf.ConfigProto()
config.gpu_options.allow_growth=True
sess = tf.Session(config=config)
```

However, I notice that with eager execution, there is no Session.

So question/bug/feature request: How do I allow growth with eager execution?

**Comment by Mean-Street** [comment]
According to the [doc](https://www.tensorflow.org/api_docs/python/tf/enable_eager_execution), `enable_eager_execution` takes a config as argument the same way your session does. Simply do:
```python
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
tf.enable_eager_execution(config=config)
```

**Comment by catskillsresearch** [comment]
Thanks, that answers my question!
