### ISSUE TITLE
[TF2.0] Optimizer for Linear models

### ISSUE THREAD

**Issue by siinn** [tensorflow/tensorflow#26789]
**System information**
- TensorFlow version: 2.0.0-alpha0
- Doc Link: 
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/estimator/LinearEstimator
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/estimator/LinearClassifier
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/estimator/LinearRegressor

**Describe the documentation issue**

The examples in these documents use tf.train.FtrlOptimizer which is not available in TF2.0.
```python
# Or estimator using the FTRL optimizer with regularization.
estimator = LinearRegressor(
    feature_columns=[categorical_column_a,
                     categorical_feature_a_x_categorical_feature_b],
    optimizer=tf.train.FtrlOptimizer(
      learning_rate=0.1,
      l1_regularization_strength=0.001
    ))
```

I tried to use tf.optimizers.Ftrl instead, but it gives the following error:

```python
# Or estimator using the FTRL optimizer with regularization.
estimator = LinearRegressor(
    feature_columns=[categorical_column_a,
                     categorical_feature_a_x_categorical_feature_b],
    optimizer=tf.optimizers.Ftrl(
      learning_rate=0.1,
      l1_regularization_strength=0.001
    ))

ValueError: The given object is not an Optimizer instance. Given: <tensorflow.python.keras.optimizer_v2.ftrl.Ftrl object
at 0x1293a32b0>
```

I think the documentation should be updated, but I am not sure the correct way of defining optimizer. Could please someone take a look at this?

Thanks,

**Comment by yhliang2018** [comment]
@siinn `tf.optimizers.Ftrl` or `tf.optimizers.Ftrl` should be the correct optimizer to use with LinearRegressor in TF 2.0. 
The error `ValueError: The given object is not an Optimizer instance. Given: <tensorflow.python.keras.optimizer_v2.ftrl.Ftrl object
at 0x1293a32b0>` indicates you are using LinearRegressorV1. Could you verify LinearRegressorV2 is indeed called? 

The docstrings have been updated. Thanks.
