### ISSUE TITLE
Confusing documentation for  to tf.Graph in Tensorflow 2

### ISSUE THREAD

**Issue by canyon289** [tensorflow/tensorflow#26781]
**System information**

> tensorflow-estimator-2.0-preview==1.14.0.dev2019031500
> tensorflow-probability==0.5.0

- Doc Link : https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/Graph

**Describe the documentation issue**
I believe for TF2 these docs can be more explicit that tf.Graph should not be used directly, and instead provide guidance similar to what Alex does in his talk
https://www.youtube.com/watch?v=Up9CvRLIIIw

The wording that `A default Graph is always registered` is confusing in TF2 verbiage. and I believe the warning that the graph will not be executed eagerly should also be made more prominent, potentially by moving it up.

The confusion compounds because after using this method the user is left with a `tf.Tensor` but we're advised not to use `tf.Session` so it's not entirely clear what should be done next to evaluate the graph.

Some of my confusion is visible in this thread (Big thanks to @brianwa84 for the help)
https://github.com/pymc-devs/pymc4/pull/93#issuecomment-473490764 for reference

Thanks in advance!

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
If I can get some help on how to word things correctly then yes

**Comment by amahendrakar** [comment]
@canyon289,
The documentation has been updated for TensorFlow v2.4. Could you please take a look at it and let us know if this is still an issue? Thanks!

**Comment by canyon289** [comment]
I doubt it is. Thanks @amahendrakar
