### ISSUE TITLE
[tflite][java] Interpreter.reset_all_variables() is not supported on Android.

### ISSUE THREAD

**Issue by MiloslavPalaxo** [tensorflow/tensorflow#26786]
`Interpreter` does not support `reset_all_variables()` in the current Android API of TF Lite.

This function is critical for RNNs because without it all the batches after the first one produce wrong results.

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- Mobile device: Pixel 3 XL
- TensorFlow installed from: binary
- TensorFlow version: v1.12.0-9708-gafab5b3 1.14.1-dev20190306
- Python version: Python 3.7.1

**Comment by Ayush517** [comment]
@MiloslavPalaxo Can you please fill the template. Thanks :)

**Comment by MiloslavPalaxo** [comment]
Done. Sorry for that.

**Comment by Saduf2019** [comment]
We see that you are using old version of tensorflow which is out of support window, We recommend that you upgrade to 2.6.0 and let us know if the issue still persists in newer versions. Please open a new issue in case you face any errors, Hence moving this to closed status.Thanks!
