### ISSUE TITLE
tf.Tensor documentation in TF2

### ISSUE THREAD

**Issue by galeone** [tensorflow/tensorflow#26783]
**System information**
- TensorFlow version: 2.0 alpha
- Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/Tensor

**Describe the documentation issue**

The documentation of `tf.Tensor` in the 2.0 section is still about the `tf.Tensor` as a symbolic tensor that contains the result of a  `tf.Operation` and it states that the only way to get its value is to use a `tf.Session` to run the node.

This is no more the truth in tf2:

- `tf.Session` is no more available
- `tf.Tensor` holds the value of the computation and we can extract it using `.numpy()`.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

Yes, I can submit a PR if needed - in the PR I can remove any reference to `tf.Session` and replace the introduction, explaining what is a `tf.Tensor` in Tensorflow 2.0.

**Comment by shashvatshahi1998** [comment]
I just want to confirm that whether  we have to remove tf.session() from class Tensor description or from complete ops.py wherever it is ,eigther in description or in function.

**Comment by wolffg** [comment]
This is updated in nightly.  Thanks!
