### ISSUE TITLE
Tensorflow Keras not adding trainable variable to Model in TF 1.13 (works in TF 1.12)

### ISSUE THREAD

**Issue by ablanch5** [tensorflow/tensorflow#26792]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13
- Python version: 3.6 (also tried 3.7)
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: GeForce 840M 8gigs ram

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I am trying to add a trainable variable y to my model. The following code adds a trainable variable y to my model in TF 1.12. It does not work in TF 1.13

    y = K.variable([0.0], dtype=tf.float32, name='y')
    add_y = Lambda(lambda x: tf.math.add(x,y))
    add_y.trainable_weights.append(y)

**Describe the expected behavior**
Model should be updated with the variable y as a trainable weight

**Code to reproduce the issue**

    import tensorflow as tf
    import tensorflow.keras.backend as K
    from tensorflow.keras import Model
    from tensorflow.keras.layers import Input, Lambda
    inputs = Input(shape=(1,))
    y = K.variable([0.0], dtype=tf.float32, name='x')
    add_y = Lambda(lambda x: tf.math.add(x,y))
    add_y.trainable_weights.append(y)
    outputs = add_y(inputs)
    model = Model(inputs=inputs, outputs=outputs)
    model.summary()

Model.summary() shows no trainable variables
**Other info / logs**
NONE

**Comment by omalleyt12** [comment]
Hi @ablanch5, that's bc in TF1.13 `.trainable_weights` is a computed property. 

I have a few ideas of what you could do here. The easiest is that, as of the latest nightly (but not as of TF1.13), TF Keras Lambda Layers can actually include variables, so you could do:

```
add_y = Lambda(lambda x: tf.math.add(x,K.variable([0.0], dtype=tf.float32, name='x')))
```

The most robust way to do this though (and the way that would work in all versions of Keras) is to create your own subclass Layer:

```
class Bias(tf.keras.layers.layer):
  def build(self, input_shape):
    self.bias = self.add_weight(shape=(), initializer='zeros', dtype=tf.float32, name='x')

  def call(self, inputs):
    return inputs + self.bias
```

**Comment by ablanch5** [comment]
Thanks so much for your answer

**Comment by cottrell** [comment]
Does this work in tf 2.0? Does not seem so.

**Comment by omalleyt12** [comment]
@cottrell i.e. you want a Variable that is unconnected to the inputs of your Model? I would suggest using the subclassed API in that case. Note that in the case above, the inputs of your Model are completely ignored
