### ISSUE TITLE
Can't install on ubuntu

### ISSUE THREAD

**Issue by mariuspoliac** [tensorflow/tensorflow#268]
New to ubuntu

Trying to install tensorflow using

$ sudo pip ...

I get:

......

  "Cannot compile 'Python.h'. Perhaps you need to "

SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-yiRxwW-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/numpy
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)

$

Any help is greatly appreciated

**Comment by vrv** [comment]
Did you do as suggested and apt-get install python-dev ?

**Comment by mariuspoliac** [comment]
Thanks much vrv!

After

$ sudo apt-get install python-dev

the tenorflow installation worked

Thanks again!

**Comment by leaf918** [comment]
solved my problem,thks.:)

**Comment by mark-liuyanjun** [comment]
it works.

**Comment by leaf918** [comment]
work for me too.
2015年12月22日 20:48，"mark-liuyanjun" <notifications@github.com>写道：
