### ISSUE TITLE
tflite runtime error with depthwise conv2D 

### ISSUE THREAD

**Issue by roymiles** [tensorflow/tensorflow#26806]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows/Ubuntu
- TensorFlow installed from (source or binary): Tried source and binary
- Python version: 3.6
- CUDA/cuDNN version: 10/7.3
- GPU model and memory: RTX 2070

**Describe the current behavior**

I run into the following error when trying to run a tflite model.
`RuntimeError: tensorflow/lite/kernels/depthwise_conv.cc:104 params->depth_multiplier * SizeOfDimension(input, 3) != SizeOfDimension(filter, 3) (0 != 6)Node number 7 (DEPTHWISE_CONV_2D) failed to prepare.`

The code runs fine normally, just not after exporting to tflite.
https://www.tensorflow.org/lite/guide/ops_compatibility -> States that the op is supported. 
I know it has been used for the MobileNet variants before.
I specified rate=[1,1] and the input kernel is constant (tf.constant).

This error has also been reported in the comments of https://github.com/tensorflow/tensorflow/issues/20798
I have tried with tf v1.12.0 and v2.0.

**Describe the expected behavior**
In my case, the depth multiplier should be 1 and the size of the input channel dimension should be 6. 
I'm not sure why it says it is 0?

**Code to reproduce the issue**
I will provide a small snippet of code to reproduce the error, if it is not well known.

**Comment by StefanBelgica** [comment]
Any update on this issue? I have a similar problem with running depthwise convolutions on a Raspberry Pi.

**Comment by liyunlu0618** [comment]
Please provide code to reproduce. Thanks!

**Comment by windmaple** [comment]
New MLIR converter should have fixed this bug. 
set experimental_new_converter=True

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by sushreebarsa** [comment]
@roymiles Please update as per the above comment and let us know if this issue still persists ? Thanks!

**Comment by roymiles** [comment]
My apologies, I haven't been working with tflite for a while and I do not have the code to reproduce this problem.

**Comment by sushreebarsa** [comment]
@roymiles thanks for the update ,please let us know if you want to move this issue to closed status ? Thanks !
