### ISSUE TITLE
tf.keras.losses.SparseCategoricalCrossentropy bug

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [tensorflow/tensorflow#26801]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):pip
- TensorFlow version (use command below):2.0.0-alpha0 , cpu version
- Python version:3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
try the demo in  tf.keras.losses.SparseCategoricalCrossentropy code annotation:
  cce = tf.keras.losses.SparseCategoricalCrossentropy()
  loss = cce([0, 1, 2],  [[.9, .05, .05], [.5, .89, .6], [.05, .01, .94]])
  print('Loss: ', loss.numpy()) 

got error:          AttributeError: 'list' object has no attribute 'dtype'

**Comment by ymodak** [comment]
In order to expedite the trouble shooting process, Can you please provide the link to the demo you are referring to? Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
