### ISSUE TITLE
[TF2.0] Unknown TensorShape error when convert tf.keras model to tflite

### ISSUE THREAD

**Issue by StarRiverSD** [tensorflow/tensorflow#26818]
*Environment*
Win 7 64bit
PyCharm
Anaconda Python 3.6
tensorflow-gpu 2.0.0a0

*issue*
I trained a tf.keras model, now I want to convert it to tflite file.
The following is my implement:

saved_model.save(model, 'testM')
model = tf.saved_model.load('testM')
concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]

converter = tf.lite.TFLiteConverter.from_concrete_function(concrete_func)
tflite_model = converter.convert()
open("new_classificaton.tflite", "wb").write(tflite_model)

When I execute it with PyCharm, the following error log is reported:

Traceback (most recent call last):
  File "E:/Keras/PycharmProjects/7241/HelloTF2/HelloWorld.py", line 73, in <module>
    tflite_model = converter.convert()
  File "C:\ProgramData\Anaconda3\envs\HelloTF2\lib\site-packages\tensorflow\lite\python\lite.py", line 261, in convert
    shape_list = tensor.get_shape().as_list()
  File "C:\ProgramData\Anaconda3\envs\HelloTF2\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 1128, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
ValueError: as_list() is not defined on an unknown TensorShape.

Is this a bug? Or I misunderstand the api usage?

**Comment by ymodak** [comment]
Apologies for the delay in response. You have to create a concrete function before the model conversion to tf lite. Please take a look at an [example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/r2/convert/python_api.md#exporting-a-keras-model-).

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by 0dd1er** [comment]
Same for me: tf.__version__ = '2.0.0-alpha0'

```
pretrained_model = tf.keras.applications.MobileNet()
tf.saved_model.save(pretrained_model, "tmp_mobilenet/1/")
loaded = tf.saved_model.load("tmp_mobilenet/1/")
infer = loaded.signatures["serving_default"]
converter = tf.lite.TFLiteConverter.from_concrete_function(infer)
converter.convert()
```

results in 
`ValueError: as_list() is not defined on an unknown TensorShape`
