### ISSUE TITLE
Gesture Classification Web App (many bugs on JS code)

### ISSUE THREAD

**Issue by gbobeff** [tensorflow/tensorflow#26810]
- index.js : function loadModel does not exist
line **32** `const mobilenet = await tf.loadModel(
`
i replaced it for `loadLayersModel` as the only function with a similar name
`const mobilenet = await tf.loadLayersModel(`

- ui.js : two missing carry return
line **151** `} ui.donePredicting =`
replaced by 
`}`
`ui.donePredicting =`
line **181** `} let mouseDown = false;`
replaced by 
`}`
`let mouseDown = false;`

- webcam.js
line 39 ` const webcamImage = tf.fromPixels(this.webcamElement);`

i replaced it for `browser.fromPixels`, i found it inspecting tfjs.js code
` const webcamImage = tf.browser.fromPixels(this.webcamElement);`

after those changes application worked correctly ...

**Comment by gbobeff** [comment]
Perhaps local js code (index.js, ui.js and wbecam.js) was code with respect to previous version of `tfjs.js` (i mean not for the latest at least)
`<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest"> </script>`

**Comment by ymodak** [comment]
This issue is more suitable on tfjs repo. The folks maintaining tfjs repo may guide you better. Please post it on tfjs from [here](https://github.com/tensorflow/tfjs/issues). Thanks!

**Comment by gbobeff** [comment]
Done ([1412](https://github.com/tensorflow/tfjs/issues/1412))
Thanks
