### ISSUE TITLE
Update README.md file of Tensorflow Lite Android example

### ISSUE THREAD

**Issue by arp95** [tensorflow/tensorflow#26831]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.7.1
- Doc Link: - 

**Describe the documentation issue**

Update the README.md file of Tensorflow Lite Android Example.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

Yes.

**Comment by ymodak** [comment]
Can you please provide the doc link and elaborate on the issue? Thanks!

**Comment by arp95** [comment]
@ymodak i have updated the readme as seen in the pr. Please review.

**Comment by ravikyram** [comment]
@arp95 

Documentation has been updated in latest TF versions.Closing the issue.Please, feel free to reopen if necessary.Thanks!
