### ISSUE TITLE
TOCO/TFLite Converter not working

### ISSUE THREAD

**Issue by reorder-cv** [tensorflow/tensorflow#26833]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.14.1-dev20190314
- Python version: Python3.5.2
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I am trying to convert a yolo model to tflite, I have generated the .pb file. I am able to get predictions working on Tensorflow using a session run. While converting the same .pb file to tflite through the python api it throws the following error 

ConverterError: TOCO failed. See console for info.
2019-03-18 16:34:02.329321: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1012 operators, 1562 arrays (0 quantized)
2019-03-18 16:34:02.392648: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1012 operators, 1562 arrays (0 quantized)
2019-03-18 16:34:03.052789: F tensorflow/lite/toco/graph_transformations/propagate_fixed_sizes.cc:722] Check failed: start_array.data_type == ArrayDataType::kInt32 Range op inputs must be int32.
Fatal Python error: Aborted

Current thread 0x00007f254cb60700 (most recent call first):
 File "/usr/local/lib/python3.5/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute
 File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251 in _run_main
 File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300 in run
 File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 40 in run
 File "/usr/local/lib/python3.5/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main
 File "/usr/local/bin/toco_from_protos", line 11 in <module>
Aborted (core dumped)

If i do it using the tflite_convert commandline function I am able to generate the tflite file however the predictions are horrible and they are not working at all. 

When I am predicting using tensorflow graph the output tensor is as follows:

array([[[-9.8978394e+01, -1.3161835e+01,  1.3285416e+02, ...,
         8.2985699e-02,  7.4172002e-01,  3.4630752e-01],
       [-4.7924599e+01, -1.0267001e+02,  9.4346962e+01, ...,
         3.8488835e-02,  7.7538919e-01,  4.5305699e-01],
       [-1.7301196e+02, -1.9800723e+02,  2.0602176e+02, ...,
         1.3685286e-02,  7.9602063e-01,  5.4424524e-01],
       ...,
       [ 3.9877176e+02,  4.0956854e+02,  4.2418051e+02, ...,
         5.5837166e-01,  4.6688780e-01,  3.5518968e-01],
       [ 4.0362198e+02,  3.9286102e+02,  4.1983481e+02, ...,
         7.3692095e-01,  4.5420480e-01,  5.1171225e-01],
       [ 3.8272733e+02,  4.0869794e+02,  4.4242825e+02, ...,
         6.1386418e-01,  6.0733950e-01,  3.9755249e-01]]], dtype=float32)

Output tensor from tensorflow lite for same image and same configuration
array([[[-7.69360809e+01, -9.79493904e+00,  1.13176025e+02, ...,
         4.96306121e-02,  5.01996398e-01,  5.42349815e-01],
       [-4.04162636e+01, -8.99354248e+01,  8.99407501e+01, ...,
         1.81048810e-02,  4.99900073e-01,  7.85123646e-01],
       [-1.43075928e+02, -1.83144836e+02,  1.79637024e+02, ...,
         4.17280197e-03,  6.15250051e-01,  8.26103389e-01],
       ...,
       [ 3.99175842e+02,  4.08667114e+02,  4.26062622e+02, ...,
         5.26856482e-01,  5.87077022e-01,  3.69019330e-01],
       [ 4.06181152e+02,  3.69634338e+02,  4.14379700e+02, ...,
         8.10274899e-01,  4.71839100e-01,  6.61600232e-01],
       [ 3.91825989e+02,  4.08976501e+02,  4.34132080e+02, ...,
         5.45497298e-01,  6.76900625e-01,  4.91856068e-01]]],
     dtype=float32)

Code to convert graph to tflite [not working]: 
tflite_yolo_model='test.tflite'
with tf.Session(graph=frozenGraph,config=config) as sess:
   frozen_graph_def = tf.graph_util.convert_variables_to_constants(
     sess, sess.graph_def, ['output_boxes'])
converter=tf.lite.TFLiteConverter.from_frozen_graph(frozen_model,['inputs'],['output_boxes'])
converter.target_ops=[tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model=converter.convert()
#tflite_model=tf.lite.toco_convert(frozen_graph_def, input_tensors=[img_resized],output_tensors=[boxes])
open(tflite_yolo_model, "wb").write(tflite_model)

**Comment by willbattel** [comment]
Which YOLO model is this? v2? v3? Also is it the full YOLO model or Tiny YOLO?

**Comment by reorder-cv** [comment]
> Which YOLO model is this? v2? v3? Also is it the full YOLO model or Tiny YOLO?

Full YOLOv3

**Comment by willbattel** [comment]
And what did you do to initially convert it from Darknet to Tensorflow?

**Comment by sirius8050** [comment]
You can try tensorflow==1.10.0.

**Comment by reorder-cv** [comment]
> And what did you do to initially convert it from Darknet to Tensorflow?

I tried using tools from 
- https://github.com/mystic123/tensorflow-yolo-v3
- https://github.com/jinyu121/DW2TF

and used the .pb files generated from these two tools.

**Comment by reorder-cv** [comment]
> You can try tensorflow==1.10.0.

I was able to convert to tflite format with 1.12.0 after a lot of issues however if i try to use the interpreter using the same version it says that some operations are not suppored 'ResizeNearest'

**Comment by sirius8050** [comment]
> > You can try tensorflow==1.10.0.
> 
> I was able to convert to tflite format with 1.12.0 after a lot of issues however if i try to use the interpreter using the same version it says that some operations are not suppored 'ResizeNearest'

You can try to quickly create a tensorflow1.10.0 environment with the virtual environment under Linux. I have tried to use TF1.13.0 for a mistake. I am not very clear about whether it is possible to use TF1.12.0.

**Comment by ymodak** [comment]
Can you try converting your model using [```TFLITE_BUILTINS```, ```SELECT_TF_OPS```](https://www.tensorflow.org/lite/guide/ops_select) if haven't already?

**Comment by wenredo** [comment]
Hello, I am doing exactly the same and I have that same issue also? Did you find any solution to it?

**Comment by wenredo** [comment]
I already tried and with tensorflow 1.12.0 it is not possible since the library tf.lite is not included in this version, it is in tensorflow 1.13.0 only

**Comment by DarnelleF** [comment]
i am using the nightly build of tensorflow
python 3.6.6
os mac

i've got a .h5 saved model
using 

```
converter = tf.lite.TFLiteConverter.from_keras_model_file('model.h5')
    converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                        tf.lite.OpsSet.SELECT_TF_OPS]
    tflite_model = converter.convert()
    open("model.tflite",'wb').write(tflite_model)
```


it fails while trying to convert
and i get



 ```
File "loadtrain.py", line 51, in <module>
    tflite_model = converter.convert()
  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 729, in convert
    **converter_kwargs)
  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 410, in toco_convert_impl
    input_data.SerializeToString())
  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 176, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-03-25 01:02:13.314209: F tensorflow/lite/toco/import_tensorflow.cc:2599] Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'
Fatal Python error: Aborted

Current thread 0x00000001194505c0 (most recent call first):
  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute
  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/absl/app.py", line 251 in _run_main
  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/absl/app.py", line 300 in run
  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40 in run
  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main
  File "/Users/darnelle/anaconda3/bin/toco_from_protos", line 10 in <module>

```

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. 
We encourage other users facing similar problems to post a separate issue by providing all the information asked by the template. Thanks!

**Comment by reorder-cv** [comment]
> Can you try converting your model using [`TFLITE_BUILTINS`, `SELECT_TF_OPS`](https://www.tensorflow.org/lite/guide/ops_select) if haven't already?

I have tried this but it still does not work properly.

**Comment by reorder-cv** [comment]
> Hello, I am doing exactly the same and I have that same issue also? Did you find any solution to it?

I've not found a solution to this yet.

**Comment by reorder-cv** [comment]
> i am using the nightly build of tensorflow
> python 3.6.6
> os mac
> 
> i've got a .h5 saved model
> using
> 
> ```
> converter = tf.lite.TFLiteConverter.from_keras_model_file('model.h5')
>     converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
>                         tf.lite.OpsSet.SELECT_TF_OPS]
>     tflite_model = converter.convert()
>     open("model.tflite",'wb').write(tflite_model)
> ```
> 
> it fails while trying to convert
> and i get
> 
> ```
> File "loadtrain.py", line 51, in <module>
>    tflite_model = converter.convert()
>  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 729, in convert
>    **converter_kwargs)
>  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 410, in toco_convert_impl
>    input_data.SerializeToString())
>  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 176, in toco_convert_protos
>    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
> tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
> 2019-03-25 01:02:13.314209: F tensorflow/lite/toco/import_tensorflow.cc:2599] Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'
> Fatal Python error: Aborted
> 
> Current thread 0x00000001194505c0 (most recent call first):
>  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute
>  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/absl/app.py", line 251 in _run_main
>  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/absl/app.py", line 300 in run
>  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40 in run
>  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main
>  File "/Users/darnelle/anaconda3/bin/toco_from_protos", line 10 in <module>
> ```

How did you get the .h5 file? You need to change the data format while converting from yolo weights to other format

**Comment by reorder-cv** [comment]
> > > You can try tensorflow==1.10.0.
> > 
> > 
> > I was able to convert to tflite format with 1.12.0 after a lot of issues however if i try to use the interpreter using the same version it says that some operations are not suppored 'ResizeNearest'
> 
> You can try to quickly create a tensorflow1.10.0 environment with the virtual environment under Linux. I have tried to use TF1.13.0 for a mistake. I am not very clear about whether it is possible to use TF1.12.0.

I am not able to get it to work on TF 1.10.0

**Comment by DarnelleF** [comment]
Model.save('model.h5')

**Comment by DarnelleF** [comment]
> > i am using the nightly build of tensorflow
> > python 3.6.6
> > os mac
> > i've got a .h5 saved model
> > using
> > ```
> > converter = tf.lite.TFLiteConverter.from_keras_model_file('model.h5')
> >     converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
> >                         tf.lite.OpsSet.SELECT_TF_OPS]
> >     tflite_model = converter.convert()
> >     open("model.tflite",'wb').write(tflite_model)
> > ```
> > it fails while trying to convert
> > and i get
> > ```
> > File "loadtrain.py", line 51, in <module>
> >    tflite_model = converter.convert()
> >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 729, in convert
> >    **converter_kwargs)
> >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 410, in toco_convert_impl
> >    input_data.SerializeToString())
> >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 176, in toco_convert_protos
> >    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
> > tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
> > 2019-03-25 01:02:13.314209: F tensorflow/lite/toco/import_tensorflow.cc:2599] Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'
> > Fatal Python error: Aborted
> > 
> > Current thread 0x00000001194505c0 (most recent call first):
> >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute
> >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/absl/app.py", line 251 in _run_main
> >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/absl/app.py", line 300 in run
> >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40 in run
> >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main
> >  File "/Users/darnelle/anaconda3/bin/toco_from_protos", line 10 in <module>
> > ```
> 
> How did you get the .h5 file? You need to change the data format while converting from yolo weights to other format

i used model.save('model.h5') method

how do i change the data format im new to machine learning and A.i

i noticed the error said the data format is NHWC WHICH since im new i have no idea what

**Comment by reorder-cv** [comment]
> > > i am using the nightly build of tensorflow
> > > python 3.6.6
> > > os mac
> > > i've got a .h5 saved model
> > > using
> > > ```
> > > converter = tf.lite.TFLiteConverter.from_keras_model_file('model.h5')
> > >     converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
> > >                         tf.lite.OpsSet.SELECT_TF_OPS]
> > >     tflite_model = converter.convert()
> > >     open("model.tflite",'wb').write(tflite_model)
> > > ```
> > > it fails while trying to convert
> > > and i get
> > > ```
> > > File "loadtrain.py", line 51, in <module>
> > >    tflite_model = converter.convert()
> > >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 729, in convert
> > >    **converter_kwargs)
> > >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 410, in toco_convert_impl
> > >    input_data.SerializeToString())
> > >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 176, in toco_convert_protos
> > >    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
> > > tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
> > > 2019-03-25 01:02:13.314209: F tensorflow/lite/toco/import_tensorflow.cc:2599] Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'
> > > Fatal Python error: Aborted
> > > 
> > > Current thread 0x00000001194505c0 (most recent call first):
> > >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute
> > >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/absl/app.py", line 251 in _run_main
> > >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/absl/app.py", line 300 in run
> > >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40 in run
> > >  File "/Users/darnelle/anaconda3/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main
> > >  File "/Users/darnelle/anaconda3/bin/toco_from_protos", line 10 in <module>
> > > ```
> > 
> > 
> > How did you get the .h5 file? You need to change the data format while converting from yolo weights to other format
> 
> i used model.save('model.h5') method
> 
> how do i change the data format im new to machine learning and A.i
> 
> i noticed the error said the data format is NHWC WHICH since im new i have no idea what

This might help [https://stackoverflow.com/questions/47014306/freeze-graph-with-different-data-format] .

**Comment by SirCastic1** [comment]
Same Issue .
Model saves succesfully in tensorflow
While converting using code:

`import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()
tf.enable_eager_execution

converter = tf.lite.TFLiteConverter.from_saved_model('C:/Users/ajayb/OneDrive/Desktop/roj/SM/1557730360',signature_key='predict')
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
`

> 

Current thread 0x000023d8 (most recent call first):
  File "c:\users\ajayb\appdata\local\programs\python\python36\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 33 in execute
  File "c:\users\ajayb\appdata\local\programs\python\python36\lib\site-packages\absl\app.py", line 251 in _run_main
  File "c:\users\ajayb\appdata\local\programs\python\python36\lib\site-packages\absl\app.py", line 300 in run
  File "c:\users\ajayb\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\platform\app.py", line 40 in run
  File "c:\users\ajayb\appdata\local\programs\python\python36\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 59 in main
  File "C:\Users\ajayb\AppData\Local\Programs\Python\Python36\Scripts\toco_from_protos.exe\__main__.py", line 9 in <module>
  File "c:\users\ajayb\appdata\local\programs\python\python36\lib\runpy.py", line 85 in _run_code
  File "c:\users\ajayb\appdata\local\programs\python\python36\lib\runpy.py", line 193 in _run_module_as_main

>

**Comment by weishengchong** [comment]
@SirCastic1,@reorder-cv 

similar issue, do you have any ideas? Thanks!

  File "/root/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 205, in toco_convert_protos
    **"TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
/bin/sh: 1: toco_from_protos: not found**

environment and codes
print(tensorflow.__version__)
1.13.1

```
import tensorflow
from tensorflow import lite

model_name = "tf_serving_keras_mobilenetv2"
model_path = f"models/{model_name}.h5"
converter = lite.TFLiteConverter.from_keras_model_file(model_path)
tfmodel = converter.convert()
open ("model.tflite" , "wb").write(f"models/{tfmodel}")
```

**Comment by SirCastic1** [comment]
> 
> 
> @SirCastic1,@reorder-cv
> 
> similar issue, do you have any ideas? Thanks!
> 
> File "/root/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 205, in toco_convert_protos
> **"TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr)) tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info. /bin/sh: 1: toco_from_protos: not found**
> 
> environment and codes
> print(tensorflow.**version**)
> 1.13.1
> 
> ```
> import tensorflow
> from tensorflow import lite
> 
> model_name = "tf_serving_keras_mobilenetv2"
> model_path = f"models/{model_name}.h5"
> converter = lite.TFLiteConverter.from_keras_model_file(model_path)
> tfmodel = converter.convert()
> open ("model.tflite" , "wb").write(f"models/{tfmodel}")
> ```

Tried the tflite converter using commandline?
For me it says 

    `ValueError: No 'serving_default' in the SavedModel's SignatureDefs. Possible values are 'predict'.`

Unfortunately I am not sure how to set serving_default as 'predict' in command line. I am only able  to set using python api which is failing me.

**Comment by weishengchong** [comment]
@SirCastic1,
solved with correction at the bold text

print(tensorflow.__version__)
1.14.1-dev20190513

```
import tensorflow
from tensorflow import lite

model_name = "tf_serving_keras_mobilenetv2"
dir="/N/share/project/weisheng/build/mobilenet_v2/keras/models"
model_path = f"{dir}/{model_name}.h5"
converter = lite.TFLiteConverter.from_keras_model_file(model_path)
tfmodel = converter.convert()
open (f"{dir}/model.tflite" , "wb").write(**tfmodel**)
```

**Comment by bayesian-mind** [comment]
What happened with this, did anyone find the solution? I am encountering the same issue while converting the .pb model to .tflite using `TFLiteConverter.from_frozen_graph`.

**Comment by DarnelleF** [comment]
> What happened with this, did anyone find the solution? I am encountering the same issue while converting the .pb model to .tflite using `TFLiteConverter.from_frozen_graph`.

this was a small personal project i was interested in. and since i couldnt find any solution or help about NHWC

**Comment by taichuai** [comment]
> 发生了什么事，有人找到解决方案了吗？在使用将.pb模型转换为.tflite时遇到相同的问题`TFLiteConverter.from_frozen_graph`。

i meet this problem too, but i can't solve it

**Comment by bmabir17** [comment]
@reorder-cv I am also facing a similar problem while converting my tensorflowModel.pb to tflite using toco 1.13.1.

I was going through the converted model and found that tflite converted model has some difference compared with the original model.pb(saved before conversion to tflite).
It seems the range op conversion has some problem. And  this seems to be the input for the expand dims.
_Tensorflow Model(original)_ [Model Link](https://drive.google.com/file/d/1DLzCOb9p8c_s86qNW_7QIsyikfRjkhK9/view?usp=sharing)
![tensorflow_range](https://user-images.githubusercontent.com/5344072/85119479-a3454400-b243-11ea-946f-ad6ece115221.png)


_Tflite Model(converted)_ [Model Link](https://drive.google.com/file/d/1Naomfft5yA7nbto_8aD72S2bC-GCW6rM/view?usp=sharing)
![tflite_range](https://user-images.githubusercontent.com/5344072/85119483-a50f0780-b243-11ea-835d-9fa2c77deba9.png)

Can anyone help why is this happening? 
P.S the model conversion showed no error. 
[My conversion code](https://gist.github.com/bmabir17/754a6e0450ec4fd5e25e462af949cde6)

N.B I have also opened [another issue](https://github.com/tensorflow/tensorflow/issues/39179) for running the model on andorid
