### ISSUE TITLE
Trying to play alarm when it detects a person on android using tesnorflow

### ISSUE THREAD

**Issue by rojanulak** [tensorflow/tensorflow#26838]
I am trying to play a sound when i detect a person and it does not process more images while sound is playing and wait n number of seconds after the sound stops playing before it processes any more images. this is to prevent overlapping sounds being played. 
I made changes to the line number below , it plays the sound when it detects an object that i tell it to, but problem is it does not detect anything after that it just freezes. 

https://github.com/rojanulak/MarsRoverPhoto/blob/master/tensorflow-master/tensorflow/examples/android/src/org/tensorflow/demo/DetectorActivity.java#L331
https://github.com/rojanulak/MarsRoverPhoto/blob/master/tensorflow-master/tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java#L215

**Comment by jvishnuvardhan** [comment]
@rojanulak Interesting application. However, this is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
