### ISSUE TITLE
SVD segfaults when given a 0x0 matrix

### ISSUE THREAD

**Issue by amilsted** [tensorflow/tensorflow#26843]
**System information**
- Have I written custom code: Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 on WSL, also Colab
- TensorFlow installed from (source or binary): binary (pip, no GPU)
- TensorFlow version (use command below): b'v1.13.1-0-g6612da8951' 1.13.1
- Python version: 3.6.8 (anaconda)

**Describe the current behavior**
Running `tf.svd([[]])` leads to a segfault.

**Describe the expected behavior**
This should probably raise an exception. Numpy returns something meaningless in this case, so is not a very good role model!

**Code to reproduce the issue**
```python
import tensorflow as tf
tf.enable_v2_behavior()
tf.svd([[]])
```

**Comment by jvishnuvardhan** [comment]
@amilsted This is a stale issue. `TF1.x` is no more supported. 

However, I couldn't reproduce the segfault when I ran your code with `TF2.5`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/28bed80469ead33f617f80e1d05680cd/untitled.ipynb). Thanks!

I am closing this issue as this was resolved in recent `TF 2.5` version. Please feel free to reopen I am mistaken. Thanks!
