### ISSUE TITLE
SVD handles small singular values poorly

### ISSUE THREAD

**Issue by amilsted** [tensorflow/tensorflow#26842]
**System information**
- Have I written custom code: Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 on WSL, also Colab
- TensorFlow installed from (source or binary): binary (pip, no GPU)
- TensorFlow version (use command below): b'v1.13.1-0-g6612da8951' 1.13.1
- Python version: 3.6.8 (anaconda)

**The problem**
Performing an SVD of [this float32 matrix](https://github.com/tensorflow/tensorflow/files/2979211/matrix.zip) using `tf.svd()` (on CPU) results in `NaN` values in the `u` and `v` factors (no `NaN`s in the singular values). Numpy's (MKL's) SVD copes with this matrix fine, and returns many more nonzero singular values than the TF implementation. TF's SVD seems to zero singular values below a threshold. This is fine, assuming these values would have otherwise been inaccurate. However, the NaN's occur in the singular vectors corresponding to the *nonzero* singular values. Note also that not all the singular values are in descending order! This seems like a bug.

**Describe the expected behavior**
TensorFlow's SVD should be more robust to poorly-conditioned matrices.

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
tf.enable_v2_behavior()
M = np.load("matrix.npy")
s_tf, u, v = tf.svd(M)
print(tf.norm(u).numpy(), tf.norm(v).numpy())  # prints "nan nan"

u, s_np, vh = np.linalg.svd(M)
print(np.linalg.norm(u), np.linalg.norm(vh))  # prints some numbers

print(s_np)
print(s_tf.numpy())  # smaller singular values are zeroed
```

I think this is essentially the same as #8905, except that here I am using single precision. The ability of the SVD to handle ill-conditioned matrices is important for our application.

**Comment by refraction-ray** [comment]
This is also similar to https://github.com/tensorflow/tensorflow/issues/9234. Actually, the following code
```python
import tensorflow as tf
tf.enable_eager_execution() # for tf 1.x
a = tf.ones([1000,1000]) #  ones as very ill conditioned matrix
tf.linalg.svd(a) # default device cpu
```
is enough to trigger segfault. This can be reproduced in current default google colab setup (tf1.15) and my local intel optimized tf2.0 enviroment (it is worth noting that svd doesn't call mkl routine even for intel optimized tf, observed by set `export MKL_VERBOSE=1`). SVD op on GPU is ok with no error or nan, though.

I think it is urgent to shift the implementation of SVD op to ?gesdd instead of ?gesvd, just like what pytorch does https://github.com/pytorch/pytorch/pull/11194. The speed difference is huge as one can benchmark by the following script in jupyter:

```python
def svd_time_benchmark(shape):
    a = np.random.uniform(size=shape)
    print("numpy")
    %timeit _ = np.linalg.svd(a)
    print("scipy lapack svd")
    %timeit _ = sp.linalg.lapack.dgesvd(a)
    print("scipy lapack sdd")
    %timeit _ = sp.linalg.lapack.dgesdd(a)
    print("tf cpu")
    a1 = tf.constant(a)
    with tf.device("/cpu:0"):
        %timeit _ = tf.linalg.svd(a1)
    print("tf gpu")
    with tf.device("/gpu:0"):
        %timeit _ = tf.linalg.svd(a1)
    print("torch cpu")
    a2 = torch.Tensor(a,  device=torch.device("cpu")).double()
    %timeit _ = torch.svd(a2)
    print("torch gpu")
    a3 = torch.Tensor(a).cuda().double()
    %timeit _ = torch.svd(a3)
```

Some typical results for 2 * Xeon 5120 or 1 * 2080TI is the following: (1000*1000 random matrix)
```
numpy
240 ms ± 3.71 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
scipy lapack svd
1.14 s ± 23.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
scipy lapack sdd
227 ms ± 7.79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
tf cpu
1.14 s ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
tf gpu
4.55 s ± 8.83 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
torch cpu
223 ms ± 3.04 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
torch gpu
280 ms ± 6.17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

The GPU implementation of SVD op in tensorflow (provided by cuSolver) is even more terrible than GPU one in pytorch (provided by MAGMA).

**Comment by sachinprasadhs** [comment]
Was able to reproduce the error in Tensorflow 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/27082cbbdeac4a85d13bf99439d03137/26842.ipynb).

**Comment by sanatmpa1** [comment]
Issue still persists in `2.6.0` and `nightly`. Please find the [gist here](https://colab.research.google.com/gist/sanatmpa1/e26298a50f49bc631d0af7f91e339ab4/-26842.ipynb)

**Comment by chunduriv** [comment]
@amilsted, 

In TF2.8,  performing SVD on [float32 matrix](https://github.com/tensorflow/tensorflow/files/2979211/matrix.zip) using `tf.linalg.svd` is not resolving `nan` values. Please refer working code in below

```
import numpy as np
import tensorflow as tf
M = np.load("/content/matrix.npy")
s_tf, u, v = tf.linalg.svd(M)
print(tf.norm(u).numpy(), tf.norm(v).numpy())  # prints numbers

u, s_np, vh = np.linalg.svd(M)
print(np.linalg.norm(u), np.linalg.norm(vh))  # prints some numbers

print(s_np)
print(s_tf.numpy())  # smaller singular values are zeroed

```
Output:

```
5.477226 5.477226
5.4772253 5.477226
[9.77897823e-01 5.65093160e-01 1.04811348e-01 6.05672747e-02
 7.85748195e-03 4.54080291e-03 8.41993780e-04 4.86606063e-04
 2.66959745e-04 1.54069436e-04 2.80844815e-05 1.62863889e-05
 3.77984588e-06 1.93174515e-06 1.70036151e-06 7.51239611e-07
 2.24312146e-07 1.46480673e-07 1.21382556e-07 7.53865947e-08
 2.85008515e-08 1.02735411e-08 5.70611380e-09 4.51371784e-09
 8.06139488e-10 6.21039220e-10 4.09449308e-10 1.06046845e-10
 9.64607214e-12 6.45445774e-13]
[9.7789788e-01 5.6509316e-01 1.0481135e-01 6.0567260e-02 7.8574596e-03
 4.5407927e-03 8.4199262e-04 4.8662108e-04 2.6695864e-04 1.5406855e-04
 2.8083754e-05 1.6289438e-05 3.7796808e-06 1.9856384e-06 1.7609195e-06
 7.3070817e-07 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
```

Thanks!

**Comment by amilsted** [comment]
Looks like this is still a problem, judging by the recent comments.

**Comment by cantonios** [comment]
Yes, this is still a problem - and it's an Eigen issue: [#2491](https://gitlab.com/libeigen/eigen/-/issues/2491)

**Comment by cantonios** [comment]
Now fixed in Eigen.
