### ISSUE TITLE
Cannot feed single element in ELMo TF-HUB embedder

### ISSUE THREAD

**Issue by simonefrancia** [tensorflow/tensorflow#26846]
Hi,
I am working in building a Deep Neural Network Classifier starting from an ELMo embedding module that embeds string, using Tensorflow Hub Module. I am using this model definition:

```
url = "https://tfhub.dev/google/elmo/2"
embed = hub.Module(url, trainable=True)

def make_elmo_embedding(x):
    embeddings = embed(tf.squeeze(tf.cast(x, tf.string)), signature="default", as_dict=True)["elmo"]
    return embeddings

# elmo embedding dimension
elmo_dim = 1024

# Input Layers
elmo_input = Input(shape=(None, ), dtype="string")

# Hidden Layers
elmo_embedding = Lambda(make_elmo_embedding, output_shape=(None, elmo_dim))(elmo_input)


x = Bidirectional(LSTM(128, dropout=0.2, recurrent_dropout=0.2))(elmo_embedding)
x = Dense(32, activation='relu')(x)
predict = Dense(2, activation='sigmoid')(x)
model = Model(inputs=[elmo_input], outputs=predict)
model.compile(loss='mse', optimizer='sgd')
```
This code works ok if the input of my network is a list with more than two strings, for example ['hello' , 'my name is Simone']. 
If my input is a list with only one element (['hello']), this error appears: 

```
tensorflow.python.framework.errors_impl.InvalidArgumentError:
 input must be a vector, got shape: [] .   [[{{node lambda_1/module_apply_default/StringSplit}}]]
```
This error is reproducible both in training mode ( batch_size = 1) and inference mode ( if I want to make inference on 1 element for example). 

Looking at the error ```node lambda_1/module_apply_default/StringSplit}``` I think that the problem is in the Lambda layer, for the fact that in function ```make_elmo_embedding``` the tf.squeeze operation cancels the dimension = 1 and the input vector results of dimension = []. I tried to delete ```tf.squeeze``` but other errors occured. 
What you suggest to solve this situation in order to make this model definition compatible both for single and multiple example lists? 

Thanks
I am using Tensorflow 1.13.1

**Comment by jvishnuvardhan** [comment]
@simonefrancia In future, please post TF_Hub related issues in the Hub [Repo](https://github.com/tensorflow/hub/issues). Thanks!

**Comment by tapos12** [comment]
Hi, I am facing the same problem when sample size is (batch_size)*iteration + 1, it produces the same error `tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: input must be a vector, got shape: []
	 [[{{node lambda_1_1/module_1_apply_default/StringSplit}}]]
  (1) Invalid argument: input must be a vector, got shape: []
	 [[{{node lambda_1_1/module_1_apply_default/StringSplit}}]]
	 [[_arg_bidirectional_1/keras_learning_phase_0_3/_1329]]
`

Since you've closed the issue already, did you fix the bug? @simonefrancia

**Comment by serdarbozoglan** [comment]
I am also having the same issue. Could you address please?

**Comment by ghost1917** [comment]
The root cause of this issue is `tf.squeeze `, that reduces all dimensions that equal 1 and if you have only 1 example, n_samples dimension is reduced as well.
To overcome it you should specify axis, that could be removed during the squeezing.
```
tf.squeeze(z, axis=1)
```
This version of Keras lambda function works for me:

```
def make_elmo_embedding(x):
    embeddings = embed(tf.squeeze(tf.cast(x, tf.string), axis=1), signature="default", as_dict=True)["elmo"]
    return embeddings
```
