### ISSUE TITLE
For Python what happens to tf.contrib.data.AUTOTUNE in 2.0 as contrib is not there in 2.0 and what do we use instead ?

### ISSUE THREAD

**Issue by sarc007** [tensorflow/tensorflow#26852]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by hadim** [comment]
Try `tf.data.experimental.AUTOTUNE` maybe?

**Comment by ocampesato** [comment]
@hadim: that worked for me .... thanks!

**Comment by sarc007** [comment]
Should I close the issue team @ocampesato , @hadim @jvishnuvardhan  as it is working with @hadim  suggested code please update?

**Comment by jvishnuvardhan** [comment]
Thanks @hadim for resolving the issue. I am closing the issue. Thanks!
