### ISSUE TITLE
ImportError when I use  "from tensorflow.models.rnn import rnn, rnn_cell"

### ISSUE THREAD

**Issue by 333caowei** [tensorflow/tensorflow#2685]
I install tensorflow on a new cluster and try to run program on it. 
But I get this error:
```ImportError("This module is deprecated.  Use tf.nn.rnn_* instead.")```, 

from this line: 
```from tensorflow.models.rnn import rnn, rnn_cell```. 

It seems the new version of TF has changed the way to import rnn, but I don't know how to fix it. (version of TF is 0.9)

**Comment by girving** [comment]
Try `tf.nn.rnn_cell` and similar.

**Comment by KendallWeihe** [comment]
I'm having the same issue. I'm confused, where should `tf.nn.rnn_cell` be placed?

**Comment by ems7** [comment]
I am having the same issue, I tried replacing `from tensorflow.models.rnn import rnn_cell` with
`tensorflow.nn.rnn_cell` but this gives the error `tensorflow.nn.rnn`

**Comment by KendallWeihe** [comment]
No, there are two ways to do it. just like throughout the code you see
tf.nn.something

that would work, and you would get rid of the import tensorflow.models.rnn.

and what that means is that it is placed in tensorflow.python.ops

so I just replaced tensorflow.models.rnn with tensorflow.python.ops

**Comment by amrqura** [comment]
from tensorflow.python.ops.rnn_cell import BasicLSTMCell

works for me.

**Comment by lingz** [comment]
In this case the error message is out of date and someone should patch it right?

**Comment by alvations** [comment]
Possibly some repackaging needs to be done because currently importing using namespaces returns `ImportError`:

```
>>> import tensorflow as tf
>>> tf.__version__
'0.9.0'
>>> from tensorflow.nn import rnn, rnn_cell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'tensorflow.nn'

>>> tf.nn.rnn
<function rnn at 0x7f79cf35ea60>
>>> tf.nn.rnn_cell
<module 'tensorflow.python.ops.rnn_cell' from '/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell.py'>
```

Is there an existing issue to allow namespaces in tensorflow?

**Comment by Cynthia0629** [comment]
I have this problem ,anyone can help?


File "/home/cynthia/Downloads/tensorflow-r0.7/tensorflow/models/image/cifar10/cifar10.py", line 47, in <module>
    from tensorflow.models.image.cifar10 import cifar10_input
ImportError: No module named 'tensorflow.models'

**Comment by ai-coder** [comment]
If you are having this error
```
ImportError: No module named 'tensorflow.models'
```
The tensorflow models are not included in tensorflow. You will have to download the tensorflow models zip from GitHub and paste them to the tensorflow folder in python packages.

**Comment by KarimElshaweish** [comment]
from tensorflow.python.keras._impl.keras.utils import data_utils
just write it

**Comment by Miraclelucy** [comment]
so I just replaced tensorflow.models.rnn with tensorflow.python.ops 
it did work
