### ISSUE TITLE
Tensorflow Hardware Requirements

### ISSUE THREAD

**Issue by Terizian** [tensorflow/tensorflow#26866]
Does the tensorflow library require a CPU with AVX support? It's not mentioned anywhere in the documentation. I've tried import tensorflow on several machines and it only fails in the machine without AVX support.

**Comment by ymodak** [comment]
Please take a look at [hardware requirements for TF](https://www.tensorflow.org/install/pip#hardware-requirements).

**Comment by Terizian** [comment]
> Please take a look at [hardware requirements for TF](https://www.tensorflow.org/install/pip#hardware-requirements).

I don't know how I missed out on that! Thanks a lot. I have been unsuccessfully trying to set up a machine with an E7 CPU that has no AVX support. I will look for alternatives.

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
