### ISSUE TITLE
What is the corresponding API for tf.nn.rnn_cell._linear in tf 2.0?

### ISSUE THREAD

**Issue by ChaoYue0307** [tensorflow/tensorflow#26868]
Just as the title suggests, I want to adopt an older version code to tf2.0, thanks

**Comment by ymodak** [comment]
You can convert your TF 1.X code to 2.X by using [```tf_upgrade_v2 utility```](https://github.com/tensorflow/docs/blob/master/site/en/r2/guide/upgrade.md#upgrade-code-to-tensorflow-20)

**Comment by ChaoYue0307** [comment]
> You can convert your TF 1.X code to 2.X by using [`tf_upgrade_v2 utility`](https://github.com/tensorflow/docs/blob/master/site/en/r2/guide/upgrade.md#upgrade-code-to-tensorflow-20)

Sorry, I tried using the single line of command to upgrade the script, but the old issue just remains.

**Comment by dynamicwebpaige** [comment]
Thanks for the question, @ChaoYue0307! This is an endpoint that was deprecated in an earlier version of TensorFlow. The recommended path for TF 2.0 would be to refactor your code to use `tf.keras.layers.RNN`.

**Comment by ymodak** [comment]
Closing this issue since it's resolved. Feel free to reopen if required. Thanks!
