### ISSUE TITLE
TF 2.0: tf.stack can cause a segmentation fault

### ISSUE THREAD

**Issue by csachs** [tensorflow/tensorflow#26879]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Linux Ubuntu 18.04
- Mobile device: N/A
- TensorFlow installed from: binary
- TensorFlow version: 2.0.0-alpha0, 2.0.0-dev20190319
- Python version: 3.6.7
- Bazel version: N/A
- GCC/Compiler version: N/A
- CUDA/cuDNN version: 10.1 / 7.4.2
- GPU model and memory: GeForce GTX 1080 Ti (11 GB)

**Describe the current behavior**
The Python interpreter crashes with SIGSEGV (Segmentation Fault); according to gdb the fault occurs in ```EagerTensor_CheckExact(_object const*) ()```.

**Describe the expected behavior**
No segmentation fault.
Ideally a stacked tensor returned (I was adapting code I developed interactively in eager execution mode, where it worked, in a Jupyter notebook for addition to a Keras based model), or an error that the argument cannot be a tensor (this is the TF1 behavior):
```
TypeError: Expected list for 'values' argument to 'pack' Op, not <tf.Tensor 'input_1:0' shape=(?, 128, 128, 1) dtype=float32>.
``` 

**Code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow.keras.layers import Input

print(tf.__version__)

input_ = Input((128, 128, 1), dtype='float32')
print(input_)
output = tf.stack(input_, axis=1)
```

**Comment by Gurpreetsingh9465** [comment]
@csachs @dynamicwebpaige  i found that there is no check about the type of values in tf2.0 but this check was there in tf 1.x , according to docs it should be a list or tuple.
so, by adding these lines in `ops/gen_array_ops pack function.`
`
    if not isinstance(values, (list, tuple)):
      raise TypeError(
          "Expected list for 'values' argument to "
          "'pack' Op, not %r." % values)
` 
solves this issue.
but this file is machine generated @dynamicwebpaige mam, can you guide me with this.

**Comment by yongtang** [comment]
I think the issue is located in:
https://github.com/tensorflow/tensorflow/blob/ca1f0ce1b9e82e9577a2439c1c40cf38d4694c40/tensorflow/python/eager/pywrap_tfe_src.cc#L1835-L1843

The `PySequence_Fast_GET_ITEM` tries to access item which should be wrapped with `PySequence_Fast` instead.

Created a PR #27133 to fix the segmentation fault issue.

**Comment by Gurpreetsingh9465** [comment]
@yongtang thanks for the PR :+1:

**Comment by kenseii** [comment]
It seems to still occur when calling the predict method on a model loaded with tf.keras.models import load_model, though if i import load_model from keras not in tf2 all works well.

is there a way of solving this?

**Comment by yongtang** [comment]
@kenseii if the issue persist, can you open a new issue with all the details so that the issue could be reproduced reliably? That will help triage and debug the issue.
