### ISSUE TITLE
My Changing on Tensorflow is not work

### ISSUE THREAD

**Issue by SunAriesCN** [tensorflow/tensorflow#2688]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
OS X EI Capitan version 10.11.5

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

If installed from sources, provide the commit hash:

### Steps to reproduce
1.Change the file cifar10_input.py with adding some print in it.
2.rebuild my tensorflow as the https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#installing-from-sources WHICH Section "Setting up TensorFlow for Development" instruction.
3.And when I back to cifar10 to run the cifar10_train.py, I found nothing have changed about my revised.

### What have you tried?
1.I try the instruction from other section "Create the pip package and install" 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by girving** [comment]
Unfortunately this is too little information, and I am having trouble parsing your sentences.  It sounds like you added a print statement or similar and it didn't show up when run.  This is probably a simple shell error, not an issue with TensorFlow itself.

**Comment by SunAriesCN** [comment]
Not only for print I had ever tried to remove some code, could cause program crash  i.e. def ...., from cifar10_input.py. And When I run cifar10_train.py, it can work well.

**Comment by girving** [comment]
Unfortunately I still don't understand your issue, but I suspect it is closer to a StackOverflow question than a problem with TensorFlow.  You could try posting your code changes, or you could try posting them on StackOverflow with the `tensorflow` tag.

**Comment by SunAriesCN** [comment]
Actually, I think I just want to know how to correctly install my tensorflow with some code changed by myself. And I guess the reason why my change is unavailable, is that my tensorflow library is old, the before code without my change. So I think what I really need, just a correct method to develop and install tensorflow with python

**Comment by girving** [comment]
Okay, I'll close for now.  Let us know if you have further issues, but we'll probably need more details for those too if so.

**Comment by SunAriesCN** [comment]
-.-! But I have no idea about how to develop and install my own code....cloud you give me some method with detail?

**Comment by girving** [comment]
@SunAriesCN: Questions about how to write new code on top of TensorFlow belong better on StackOverflow.
