### ISSUE TITLE
Error when importing tensorflow: DLL load failed

### ISSUE THREAD

**Issue by mwappner** [tensorflow/tensorflow#26899]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.13.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: using CPU

**Describe the problem**

Originaly, when importing python module keras with tensorflow backend ar error ocurred when importing. To be sure, I simply imported tensorflow and same error was shown: 

> ImportError: DLL load failed: Specified module could not be found.
> 
> Failed to load the native TensorFlow runtime.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Open python in conda prompt or using spyder console:
`import tensorflow`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

> import tensorflow
> Traceback (most recent call last):
> 
>   File "<ipython-input-2-d6579f534729>", line 1, in <module>
>     import tensorflow
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> 
> ImportError: Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\ProgramData\Anaconda3\lib\imp.py", line 243, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\ProgramData\Anaconda3\lib\imp.py", line 343, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: No se puede encontrar el módulo especificado.
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.

**Comment by ymodak** [comment]
From the error message, I suspect you have installed tf-gpu version. Please take a look at duplicate #22794
Also can you please share  TF installation process you followed? Thanks!

**Comment by mwappner** [comment]
I had looked at that issue, but since I' not using a GPU, I figured I [didn't need to install CUDA](https://www.quora.com/What-is-CUDA-If-we-can-perform-TensorFlows-computation-directly-from-a-GPU-then-why-do-we-actually-need-it). 
When I check my conda enviorment, it says I have tensorflow (not tensorflow-gpu) installed, as well as tensorboard, tensorflow-base and tensorflow-estimator (and keras, but I don't think that's an issue. However, I just notised it also says that the build used is gpu_py36h0fff12a_0, so maybe GUP?
To install I'm prety sure I simply did `conda install tensorflow`.

**Comment by ymodak** [comment]
Thanks for the confirmation. Can you please describe the procedure you followed to install TF?
Also did you get a chance to take a look at [install guide on TF website](https://www.tensorflow.org/install/pip)?

**Comment by mwappner** [comment]
I hadn't read it, but it doesn't quite apply, I think. My python instalation uses Anaconda and in this machine I have a single enviorment I'm using. In that enviorment I ran `conda install tensorflow` to install.

The linked installation guide suggests using `pip install --upgrade tensorflow` and a virtualenv. I was told that as long as I can install something using conda I should, since it is better at checking for conflicts and keeping a clean path. Instad of Visual Studio 2015, I have Visual studio 2017, version 1.27.1, to be specific. Also, I did "Make sure long paths are enabled on Windows."

**Comment by mwappner** [comment]
Just to be sure I did the following in an anaconda prompt:

- I tried `conda update tensorflow`, which did nothing since I have a fresh installation.

- I tried `pip install --upgrade pip`, which did nothing.

- I ran `conda update pip` to actually update it, since my pip is a conda installation.

- I ran `pip install --update tensorflow`, which installed something, but I still get the same problem in python.

**Comment by ymodak** [comment]
Apologies for the delay in response.
*TensorFlow release binaries (CPU/GPU) version 1.6 and higher are prebuilt with AVX instruction sets.*  
See [hardware requirements][1] to know more.  

Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:  

* Try Google Colab to use TensorFlow.    
 * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use ```pip install``` to install any other preferred TF version.  
    * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task. 
    * All you need is a good internet connection and you are all set.  
* Try to build TF from sources by changing CPU optimization flags.


  [1]: https://www.tensorflow.org/install/pip#hardware-requirements

**Comment by mwappner** [comment]
Hm... That's very good to know, thanks! However, for whatever reason, after reinstalling anaconda yet again (I had broken my installation doing something else), Keras (and tensorflow) ended up working no problem. I don't recall doing anything differently. Thanks!

**Comment by ymodak** [comment]
You are welcome. Closing this issue now since it's resolved. Thanks!

**Comment by gunan** [comment]
Anaconda packages are not built by the TF team.
So the packages you get by `pip install` or `conda install` are different.
The conda packages may be more compatible.
