### ISSUE TITLE
LLVM JIT / Runtime Code Re Optimisation

### ISSUE THREAD

**Issue by sirinath** [tensorflow/tensorflow#269]
Some optimisations may not be apparent when statical set up. Perhaps TensorFlow can do some staging and optimisation of the execution while running based on usage patterns.

Perhaps you can borrow some ideas from projects related to: https://scala-lms.github.io/

**Comment by vrv** [comment]
De-duping this with: https://github.com/tensorflow/tensorflow/issues/164 (try not to consolidate discussion about a feature request or topic if possible -- otherwise it makes it hard for us to keep track of all these issues :).  We'll split them into new issues if needed though).

**Comment by sirinath** [comment]
OK. Updated the above issue.
