### ISSUE TITLE
Multiple CheckpointSavers when using MonitoredTrainingSession

### ISSUE THREAD

**Issue by bdod6** [tensorflow/tensorflow#26906]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS High Sierra
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 2.7.14
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory: None

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

I'm currently using MonitoredTrainingSession and passing it the CheckpointSaverHook. It works fine for new models. When I want to restore a model, I give a path to the `checkpoint_dir` arg. However, this also inits the default CheckpointSaver, and it will double save checkpoints in the directory. This is evident if I change `checkpoint_basename` as I get duplicate checkpoints at each global step.

**Describe the expected behavior**

I would not expect the default CheckpointSaver to init, and instead use the params given by the CheckpointSaverHook. 

**Code to reproduce the issue**

```
...
    initializer_hook = _DatasetInitializerHook(init_train, self.train_tfrecords_glob,
                                               queue_name=self.tensorq_name)
    summary_hook = tf.train.SummarySaverHook(save_steps=50, save_secs=None, summary_op=summary_op)
    logging_hook =  tf.train.LoggingTensorHook(tensors={'step': global_step, 'loss': loss,
                                                        'accuracy': acc_op}, 
                                                         every_n_iter=logging_step)
    saver = tf.train.Saver(max_to_keep=2)
    saver_hook = tf.train.CheckpointSaverHook(checkpoint_dir=self.ckpt_dir, 
                                              saver=saver, save_steps=save_step,
                                              checkpoint_basename='latest_model')
    step_hook = tf.train.StepCounterHook(every_n_steps=logging_step)

    hooks = [summary_hook, logging_hook]

    # Checkpoint Saver - Check for new model
    if self.new_model:
      logging.info('Starting New Model...existing ckpts will be deleted')
      hooks.extend([saver_hook, step_hook])
      fl = [f for f in os.listdir(self.ckpt_dir)]
      for f in fl:
        os.remove(os.path.join(self.ckpt_dir, f))
      checkpoint_dir =  None

    else:
      checkpoint_dir = self.ckpt_dir
      hooks.append(saver_hook)
    
    # Start Training
    with tf.train.MonitoredTrainingSession(
        checkpoint_dir=checkpoint_dir,
        hooks=[initializer_hook],
        chief_only_hooks=hooks,
        log_step_count_steps=logging_step,
        config=tf.ConfigProto(allow_soft_placement=True)) as mon_sess:
        while not mon_sess.should_stop():
          mon_sess.run(training_op)

    logging.info("Training Completed")
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by xiejw** [comment]
Passed to karmel for triage. 

As far as I remember, Estimator has dedup code but likely not in MonitoredTrainingSession

**Comment by mohantym** [comment]
Hi @bdod6 ! 
We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!
