### ISSUE TITLE
Cannot add metric to Estimator with binary_classification_head

### ISSUE THREAD

**Issue by PawelFaron** [tensorflow/tensorflow#26904]
I created custom Estimator that uses binary_classification_head. During training I can see only loss and global step in tensorboard.
I was trying to add metric using tf.contrib.estimator.add_metrics but it doesn't work (don't know why). 
I was also trying to add it using similar approach to this one but also with no luck:
https://stackoverflow.com/questions/50120073/tensorflow-metrics-with-custom-estimator
Could you please advise me how can I add some metrics to this?

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
