### ISSUE TITLE
Specs

### ISSUE THREAD

**Issue by phquanta** [tensorflow/tensorflow#26907]
Tensorflow: version 1.7.0 (CPU based installation)
Python: 3.6
OS: Windows 8.1
OS Name	Microsoft Windows 8.1
Version	6.3.9600 Build 9600
Other OS Description 	Not Available
System Model	XPS 8700
Processor	Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz, 3601 Mhz, 4 Core(s), 8 Logical 
Installed Physical Memory (RAM)	24.0 GB
GPU: Nvidia GTX 1050Ti
IDE: Spyder 3.3.1

Aslo this operation

j=1

aa=self.sess.run(tf.map_fn(lambda x: (tf.tensordot(x[0],x[1],0)),elems=tf.convert_to_tensor(self.vt[:,j,:]), tf.convert_to_tensor(self.ht[:,j,:])),dtype=tf.float64))

is twice as slow compared  to:

[np.outer(self.vt[i,j,:],self.ht[i,j,:])*expF[i] for i in self.lRepls]

self.lRepls=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
np.shape(self.vt)=(16,10,784)
np.shape(self.ht)=(16,10,340)

**Comment by jvishnuvardhan** [comment]
@phquanta Could you try latest version of TF and check whether the bug persists? There were lots of improvements between TF1.7.0 to TF1.13.1 or TF2.0. Some of the ops run much faster than previous version. Please let me know what you think? Thanks!

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. Please open a new ticket if you see similar issue again. Thanks!
