### ISSUE TITLE
r2.0-alpha compile on Ubuntu 18.04 has not installed tensorboard nor tf_upgrade_v2 properly

### ISSUE THREAD

**Issue by kshaeffer** [tensorflow/tensorflow#26918]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): AWS Ubuntu 18.04 server
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source from Github
git clone https://github.com/tensorflow/tensorflow.git tfgit
Cloning into 'tfgit'...
remote: Enumerating objects: 2136, done.
remote: Counting objects: 100% (2136/2136), done.
remote: Compressing objects: 100% (985/985), done.
remote: Total 539589 (delta 1286), reused 1621 (delta 1145), pack-reused 537453
Receiving objects: 100% (539589/539589), 319.72 MiB | 39.79 MiB/s, done.
Resolving deltas: 100% (433795/433795), done.
Checking out files: 100% (16348/16348), done.

- TensorFlow version: r2.0-alpha
git checkout r2.0
Branch 'r2.0' set up to track remote branch 'r2.0' from 'origin'.
Switched to a new branch 'r2.0'
- Python version: 3.6.7
$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux

- Installed using virtualenv? pip? condo?:
Installed at /usr/lib/python3/dist-packages/tensorflow

- Bazel version (if compiling from source):
# wget https://github.com/bazelbuild/bazel/releases/download/0.23.0/bazel-0.23.0-installer-linux-x86_64.sh
# chmod 700 bazel-0.23.0-installer-linux-x86_64.sh
# ./bazel-0.23.0-installer-linux-x86_64.sh

- GCC/Compiler version (if compiling from source):
$ gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

- CUDA/cuDNN version: Not supported
- GPU model and memory: Not supported

**Describe the problem**

tensor board is not properly installed.
$ tensorboard --logdir=./statsGraph
tensorboard: command not found

Also tf_upgrade_v2 script is not installed properly:

$ tf_upgrade_v2.py
tf_upgrade_v2.py: command not found

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I can get tensorboard to run like this:

$ python3 -m tensorboard.main --logdir=./statsGraphs/
TensorBoard 1.14.0a20190301 at http://***.***.***.***:**** (Press CTRL+C to quit)

**Any other info / logs**
[uploadTF2BUILDlogs.txt](https://github.com/tensorflow/tensorflow/files/2986598/uploadTF2BUILDlogs.txt)

I cannot get tf_upgrade_v2.py script to work:

/usr/lib/python3/dist-packages/tensorflow/tools/compatibility# python3 -m tf_upgrade_v2.py --infile /srv/projects/t1/LSTMBlockCell4HLDropoutAdam.py --outfile /srv/projects/t1/LSTMBlockCell4HLDropoutAdam_v2.py
/usr/bin/python3: Error while finding module specification for 'tf_upgrade_v2.py' (AttributeError: module 'tf_upgrade_v2' has no attribute '__path__')

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by kshaeffer** [comment]
I have been able to get tf_upgrade_v2.py to run. And it does process the file as expected.

$ python3 -m tensorflow.tools.compatibility.tf_upgrade_v2_main --infile ../../t1LSTMBlockCell4HLDropoutAdam.py --outfile ../../t1LSTMBlockCell4HLDropoutAdam_v2.py

My understanding is I should not need to run it this way. Presume it is not properly installed.

**Comment by annarev** [comment]
Sorry for delay replying.
Which command do you run to build TensorFlow? Do you run build_pip_package? (see instructions here: https://www.tensorflow.org/install/source)

I just tried building TF package from source, installing it in a clean env and both tf_upgrade_v2 and tensorboard work as expected.

For reference, these are the steps I followed:
```bash
python3 -m venv venv
source venv/bin/activate
pip install keras_applications==1.0.4
pip install keras_preprocessing==1.0.2
pip install h5py==2.8.0
pip install grpcio portpicker scipy tf-estimator-nightly wheel

git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow/
git checkout r2.0

export TF_NEED_CUDA=0
yes "" | ./configure

bazel build --config=opt --config=v2 //tensorflow/tools/pip_package:build_pip_package --incompatible_disallow_dict_plus=false
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
```
That last command would output a wheel file to `/tmp/tensorflow_pkg`. Note that I pass in `--incompatible_disallow_dict_plus=false` due to bazel version I use (otherwise I see an error that asks to pass that flag). You might or might not need that flag.
Now, we can install the package we just built in a different virtual environment.
```bash
deactivate
cd ..
python3 -m venv tf_package_venv
source tf_package_venv/bin/activate
pip install /tmp/tensorflow_pkg/tensorflow-2.0.0a0-cp36-cp36m-linux_x86_64.whl
```

**Comment by annarev** [comment]
nm I see that you do run `build_pip_package` in the log.
There are a couple of things I noticed:
1. To get 2.0 version of the APIs, pass `--config=v2` when building `build_pip_package`
2. Upgrade script command is `tf_upgrade_v2` instead of `tf_upgrade_v2.py`

**Comment by kshaeffer** [comment]
Rebuilt r2.0 alpha from source. Used --config=v2. This gives me the v2 API. Thanks. Tensor board is continuing to fail to start up.

Tensor board version 1.14.0a20190301 continues to fail to startup:

$ tensorboard --logdir='statsGraphs'
tensorboard: command not found

$ python3 -m tensorboard.main --logdir='statsGraphs'
TensorBoard 1.14.0a20190301 at http://ip-25-18-48-51:6006 (Press CTRL+C to quit)

$ tf_upgrade_v2
tf_upgrade_v2: command not found

Attaching the build log for your information.
[tfalpha_r2.0.buildlog.txt](https://github.com/tensorflow/tensorflow/files/3123044/tfalpha_r2.0.buildlog.txt)

**Comment by annarev** [comment]
This is strange. Do you see `tensorboard` and `tf_upgrade_v2` scripts if you just install `tensorflow==2.0.0a0` instead of building from source?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
