### ISSUE TITLE
iOS example compile error

### ISSUE THREAD

**Issue by yun1988822** [tensorflow/tensorflow#26924]
iOS example app compile error because "third_party/tensorflow/core/framework/types.h" file not found. (Xcode 10.1)

I can fix this bug by modify 
`#include "third_party/tensorflow/core/framework/types.h" `
to
`#include "tensorflow/core/framework/types.h" `
(tensorflow/tensorflow/examples/ios/simple/ios_image_load.h # line20)

Many thanks!

**Comment by yyoon** [comment]
Seems to be fixed by https://github.com/tensorflow/tensorflow/pull/31506. Closing.
