### ISSUE TITLE
how to edit kernel weight at certain global_step using estimator

### ISSUE THREAD

**Issue by chengyuz** [tensorflow/tensorflow#26935]
i want to set some weights to zero at certation global step.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
