### ISSUE TITLE
How to use tf.embedding_lookup_sparse_with_distributed_aggregation in feature_column&estimator ?

### ISSUE THREAD

**Issue by ericyue** [tensorflow/tensorflow#26938]
Hi, I want to use `tf.embedding_lookup_sparse_with_distributed_aggregation`  in my training program. The model is built with tf.estimator and tf.feature_column . 

But the default is using `safe_embedding_lookup_sparse ` which will cost lots of network traffic.  

So what is the best way to use distributed_aggregation with feature_column ? 

 I think one way is to modify tf.feature_colmun source code. but is there any others ?

**Comment by jvishnuvardhan** [comment]
@ericyue Could you provide more details and a short code to demonstrate the issue? Thanks!

**Comment by ericyue** [comment]
@jvishnuvardhan   When I use `tf.feature_column.embedding_column`, it creates embeddings and do embedding-lookup using   `tf.contrib.layers.safe_embedding_lookup_sparse`by default,  which will cost lots of network traffic within the parameter-server and workers.  So I want to known is there a elegant way to replace `tf.contrib.layers.safe_embedding_lookup_sparse` with `tf.embedding_lookup_sparse_with_distributed_aggregation` ?

**Comment by ericyue** [comment]
I will prepare a simple demo for this case

**Comment by ericyue** [comment]
@jvishnuvardhan  Can you give me some advice about this? thanks :)

**Comment by ericyue** [comment]
@jhseu @jvishnuvardhan Can you give me some advice about this? thanks :)

**Comment by jhseu** [comment]
One option would be to subclass EmbeddingColumn and override the _get_dense_tensor_internal_helper mmethod.

**Comment by ericyue** [comment]
@jhseu  Yes, I think about this before, by modifying the source code and build with bazel a new python lib.  

Is this the best practice right now ? : )

**Comment by hudengjunai** [comment]
@ericyue hi, I come up with the same problem like you.  when I train a wide&deep&cross model . use feature_column and embedding_lookup, the network io is very big( about 10Gbps) which have harm to train efficiency. I have find the meituan technical report [美团WDL优化](https://tech.meituan.com/2018/04/08/tensorflow-performance-bottleneck-analysis-on-hadoop.html) . Did you solve your problem? can you give me some adivces?

**Comment by sushreebarsa** [comment]
@ericyue tf.feature_colmun and tf.estimator apis are deprecated. Could you please move this issue to closed status and file a new request for an equivalent API?
Thank you!
