### ISSUE TITLE
Typo in the section "3. Install the TensorFlow pip package"

### ISSUE THREAD

**Issue by shaolinkhoa** [tensorflow/tensorflow#26937]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version:
- Doc Link: https://www.tensorflow.org/install/pip

**Describe the documentation issue**
In the "Install TensorFlow with pip", section "3. Install the TensorFlow pip package", the sentence "**tensorflow==2.0.0-alpha0-gpu** —Preview TF 2.0 Alpha build with GPU support (unstable, Ubuntu and Windows)" is wrong.
It's should "**tensorflow-gpu==2.0.0-alpha0**" instead of "**tensorflow==2.0.0-alpha0-gpu**"

Because I can't install with "pip install --upgrade tensorflow==2.0.0-alpha0-gpu"

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by dynamicwebpaige** [comment]
Thanks for letting us know! :slightly_smiling_face: 

I made the change, and you can track progress on the PR here:
https://github.com/tensorflow/docs/pull/402
