### ISSUE TITLE
Can we have demo CNN application using ARM micro controller with Camera for object detection please?

### ISSUE THREAD

**Issue by ramkumarkoppu** [tensorflow/tensorflow#26933]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): Experimental Micro-controller version
- Are you willing to contribute it (Yes/No): Not now.

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by wangtz** [comment]
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/micro_vision might the closest example code for now. It's still image classification not yet detection though.

**Comment by petewarden** [comment]
I'm closing this as we do have a vision example available now.
