### ISSUE TITLE
[TF2.0] ref types in TF1 vs TF2

### ISSUE THREAD

**Issue by Sklan** [tensorflow/tensorflow#26941]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:No
- TensorFlow installed from (source or binary):Binary
- TensorFlow version (use command below):2.0.0-alpha0 and 1.13.0
- Python version:3.6

**TensorFlow 1.13.0**
```python
import tensorflow as tf
import numpy as np
print(tf.__version__)
x = np.random.randn(3, 4)
x_tf = tf.Variable(x)
print(x_tf.dtype)
```
```python
1.13.1
<dtype: 'float64_ref'>
```
**TensorFlow 2.0.0-alpha0**
```python
import tensorflow as tf
import numpy as np
print(tf.__version__)
x = np.random.randn(3, 4)
x_tf = tf.Variable(x)
print(x_tf.dtype)
```
```python
2.0.0-alpha0
<dtype: 'float64'>
```
While playing around with TensorFlow 2.0, I noticed that there is a difference in calling ```tf.Variable```.  Just wanted to know if ```_ref``` is being phased out in TF2.0?

**Comment by alextp** [comment]
Yes, ref is no longer a thing in tf v2.
