### ISSUE TITLE
Allocation of ram/memory while training 50 gb of data

### ISSUE THREAD

**Issue by xyzdcgan** [tensorflow/tensorflow#26940]
Hello,

I am training a model and my specs are 

Tesla K80 GPU  12 GB ram
61 gb ram physical ram

my training data set is of 50 gb

I want to know that how tensorflow use the memory for loading the data as it gives "OOM" error,
while loading images/dataset how it load whether loads all the in gpu and doesn't utilize the ram 
as while training it uses gpu so does it do half data on ram and half data on gpu, i want to know allocation of memory and how tensorflow does that.

And what if i want to use both gpu and cpu for tensorflow so it doesn't have memory issue so total i will have 61 + 12 gb of ram which can load dataset efficiently.

Can anyone give me exact details that how tensorflow does the computation and allocation of memory for dataset. 

Thanks

**Comment by jvishnuvardhan** [comment]
@xyzdcgan Please check there are lot of info on latest TF website. Here is link to [distribution_strategy](https://www.tensorflow.org/guide/distribute_strategy) and this [link](https://www.tensorflow.org/guide/using_gpu) might be helpful.

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
