### ISSUE TITLE
why do i get empty array at tf.keras.Sequential(layers).trainable_variables?

### ISSUE THREAD

**Issue by PaulNicolasHunter** [tensorflow/tensorflow#26948]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- TensorFlow version: 2.0.0-alpha0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip

**why do I get empty array ?**

I'm trying to follow tf2.0 tuts on the website to perform a simple perceptron but seems like the package manager isn't able to pick up the new release but also not throwing any error.
what could be the reason to this?

![well](https://user-images.githubusercontent.com/26624903/54701853-c920fc00-4b5b-11e9-9fcd-ff39fff60284.jpg)

**Comment by allenlavoie** [comment]
The Layers aren't built yet. You can either pass an input_shape to Sequential, which will build everything, or you can call build() explicitly. You can also call the model with data and they will build automatically.

Whichever option, the Layer just needs to know its input shape before it can create its variables.
