### ISSUE TITLE
EagerTensor.numpy() fails with string dtype when called from py_function on GPU

### ISSUE THREAD

**Issue by woodshop** [tensorflow/tensorflow#26951]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7.1
- Bazel version (if compiling from source): 0.20.0 
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: 10.0
- GPU model and memory: Tesla K80

**Describe the current behavior**
When a `py_function` op is defined for GPU (the default if one is available), and it calls a function that takes a string argument, a `RuntimeError` is raised if one attempts to access the value of the argument by calling `EagerTensor.numpy()`.

If the `py_function` op is defined for CPU no error is raised.

**Describe the expected behavior**
One of the following:
  - String arguments are disallowed for a `py_function` running on GPU, and the TF documentation explains this behavior.
  - The value of a string argument is accessible in the scenario described above.

**Code to reproduce the issue**
This does not work:
```python
def func_with_string_arg(arg):
    return arg.numpy()

with tf.Graph().as_default():
    tf_arg = tf.convert_to_tensor('abcdef')
    ret = tf.py_function(
        func_with_string_arg,
        [tf_arg],
        tf.dtypes.string
    )
    with tf.Session() as sess:
        print(sess.run(ret))
```

Snippet of the error:
```
UnknownError: RuntimeError: Error copying tensor to device: CPU:0. Can't copy 38 bytes of a tensor into another with 32 bytes buffer.
Traceback (most recent call last):

  File "/home/asarroff/anaconda3/envs/tf-1.13.1/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 205, in __call__
    return func(device, token, args)

  File "/home/asarroff/anaconda3/envs/tf-1.13.1/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 107, in __call__
    ret = self._func(*args)

  File "<ipython-input-5-590852b9a5d8>", line 2, in func_with_string_arg
    return arg.numpy()

  File "/home/asarroff/anaconda3/envs/tf-1.13.1/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 725, in numpy
    return self._cpu_nograd()._numpy()  # pylint: disable=protected-access

  File "/home/asarroff/anaconda3/envs/tf-1.13.1/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 892, in _cpu_nograd
    return self._copy_nograd(context.context(), "CPU:0")

  File "/home/asarroff/anaconda3/envs/tf-1.13.1/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 840, in _copy_nograd
    new_tensor = self._copy_to_device(context=ctx._handle, device=device_name)

RuntimeError: Error copying tensor to device: CPU:0. Can't copy 38 bytes of a tensor into another with 32 bytes buffer.


	 [[{{node EagerPyFunc}}]]
	 [[{{node EagerPyFunc}}]]
```

This works:
```python
with tf.Graph().as_default():
    tf_arg = tf.convert_to_tensor('abcdef')
    with tf.device('/device:CPU:*'):
        ret = tf.py_function(
            func_with_string_arg,
            [tf_arg],
            tf.dtypes.string
        )
    with tf.Session() as sess:
        print(sess.run(ret))
```

**Comment by frantracer** [comment]
I am having this issue with 2.0.0-rc0, is this problem supposed to be fixed in that release?

**Comment by RomanSteinberg** [comment]
The same problem for TF 2.0.

**Comment by jvishnuvardhan** [comment]
@RomanSteinberg @frantracer As your issue is related to `TF2.0`, Please create a new issue with details and a standalone code to reproduce the issue. Thanks!

**Comment by rmothukuru** [comment]
@woodshop,
I've executed your code in Tensorflow Version 1.15 and it works without any error. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/760cf674d64dc60aa440105692133ed7/gh_26951.ipynb) of the working code. Thanks!
