### ISSUE TITLE
tensorflow/core/kernels/slice_op_gpu.cu.cc is never referenced in any BUILD file

### ISSUE THREAD

**Issue by reuben** [tensorflow/tensorflow#26956]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13
- Python version: 3.6
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10
- GPU model and memory: N/A

**Describe the problem**

This file: https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/core/kernels/slice_op_gpu.cu.cc

Is never referenced anywhere in the tree. When building with CUDA and a dependency on [//tensorflow/core/kernels:strided_slice_op](https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/core/kernels/BUILD#L119), it fails at link time with errors like this one:

undefined reference to `tensorflow::functor::Slice<Eigen::GpuDevice, signed char, 5>::operator()(Eigen::GpuDevice const&, Eigen::TensorMap<Eigen::Tensor<signed char, 5, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorMap<Eigen::Tensor<signed char const, 5, 1, long>, 16, Eigen::MakePointer>, Eigen::DSizes<long, 5> const&, Eigen::DSizes<long, 5> const&)'

The problem seems to be that [tensorflow::HandleStridedSliceCase](https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/core/kernels/strided_slice_op_impl.h#L95) will call `functor::Slice` if the slice is a "simple slice", so when the template is instantiated for GPU [here](https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/core/kernels/strided_slice_op_impl.h#L284-L290) it references the undefined GPU version of `functor::Slice`.

Seems to me like somewhere in tensorflow/core/kernels/BUILD should be referencing slice_op_gpu.cu.cc, maybe the strided_slice_op target?

**Comment by gunan** [comment]
It is referenced through the bazel macros we define.
Here is the build rule for `slice_op`
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/BUILD#L1107
As you can see it also has a dependency on `strided_slice_op`

This rule is an instance of tf_kernel_library. That is defined here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl#L1262

This rule automatically includes `prefix.cu.cc` files to be built:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl#L1314

I will close this issue to avoid confusion.
Please file a new issue with the build failure you are seeing.

**Comment by reuben** [comment]
@gunan The problem is that `strided_slice_op` does not have a dependency on `stride_op`, not the other way around. Here's the build rule for `strided_slice_op`: https://github.com/tensorflow/tensorflow/blob/93a7be53a9c314b1e4dc35fc97d5be8367e8fc01/tensorflow/core/kernels/BUILD#L121-L159
