### ISSUE TITLE
freeze_graph successful from command line but fails from Python file

### ISSUE THREAD

**Issue by willbattel** [tensorflow/tensorflow#26965]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): tf-nightly-gpu `v1.12.0-10390-ge9a2281040 1.14.1-dev20190319`
- Python version: 3.5.2
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 10.0, cuDNN 7.5.0 for CUDA 10.0
- GPU model and memory: GeForce GTX 1070 8GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

I have a GraphDef and checkpoint I am trying to freeze.  I am able to do so from the command line, but not from a Python file.

**Describe the expected behavior**

I expect the behavior from the Python file to match the CLI behavior. I am referencing [the args on freeze_graph.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py#L77) and failing to find an issue with my usage.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

This is my CLI command that works:
```
python3 -m tensorflow.python.tools.freeze_graph
    --input_graph=mygraph.pb
    --input_checkpoint=mygraph.ckpt
    --input_binary=true
    --output_graph=frozen_graph.pb
    --output_node_names=mygraph/convolutional10/BiasAdd,mygraph/convolutional13/BiasAdd
```

And this is my attempted Python file.
```
from tensorflow.python.tools import freeze_graph

freeze_graph.freeze_graph(
    'mygraph.pb', # input_graph_def
    None, # input_saver_def
    'mygraph.ckpt', # input_checkpoint
    'mygraph/convolutional10/BiasAdd,mygraph/convolutional13/BiasAdd', # output_node_names
    None, # restore_op_name
    None, # filename_tensor_name
    'frozen_graph.pb', # output_graph
    False, # clear_devices
    "", # initializer_nodes
    "" # variable_names_whitelist
    )
```

If I don't include the `variable_names_whitelist` arg at the end, then I get this error: `TypeError: freeze_graph() missing 1 required positional argument: 'initializer_nodes'`. If I do include it, then I get past that weird error and encounter this one instead: `tensorflow.python.framework.errors_impl.NotFoundError: mygraph/convolutional10/BiasAdd,mygraph/convolutional13; No such file or directory`. Not sure what to make of either of these errors. Why is it using the `output_node_names` to find a file? Also, why is it truncating the string? `mygraph/convolutional10/BiasAdd,mygraph/convolutional13` ≠ `mygraph/convolutional10/BiasAdd,mygraph/convolutional13/BiasAdd`

Any ideas? Thanks.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

See above.

**Comment by petewarden** [comment]
Nupur, are you able to take a look at this? Thanks for your help!

**Comment by gargn** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Additionally, given that `freeze_graph.py` is going to be deprecated with 2.0, I am closing this issue. Thanks!
