### ISSUE TITLE
tf.compat.v2.summary.scalar has no attribute 'summary_scope'

### ISSUE THREAD

**Issue by kshaeffer** [tensorflow/tensorflow#26960]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes, I have a minimal test file
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):
tf.__version__
'2.0.0-alpha0'
- Python version:
$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
- Bazel version (if compiling from source): binary installer version 0.23
- GCC/Compiler version (if compiling from source):
$ gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: Not supported
- GPU model and memory: Not supported

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

tf.compat.v2.summary.scalar("stddev",_st,step=count,description='stddev')
is being processed as an _api.v1.summary

**Describe the expected behavior**

tf.compat.v2.summary.scalar("stddev",_st,step=count,description='stddev')
is processed as an _api.v2.summary

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

    tf_sdata = tf.convert_to_tensor(sdata,dtype=tf.float32,name="tf_sdata")
    tfdata_stddev = tf.data.Dataset.from_tensor_slices(tf_sdata[:,0])

    tfstddev_iter = tfdata_stddev.__iter__()

    stats_writer = tf.compat.v2.summary.create_file_writer(logs_path,max_queue=10,flush_millis=120000,
            filename_suffix='.stats',name='stats_writer')

    count = 1
    for _st in tfstddev_iter:
        tf.compat.v2.summary.scalar("stddev",_st,step=count,description='stddev')
        count += 1

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Traceback (most recent call last):
  File "./tf2summary_bug.py", line 71, in <module>
    tf.compat.v2.summary.scalar("stddev",_st,step=count,description='stddev')
  File "/usr/lib/python3/dist-packages/tensorboard/plugins/scalar/summary_v2.py", line 55, in scalar
    with tf.summary.summary_scope(
AttributeError: module 'tensorflow._api.v1.summary' has no attribute 'summary_scope'

**Comment by meyerjo** [comment]
I think you need to mark the `stats_writer` as default. Either by calling `stats_writer.set_as_default()` (do not directly add this call to the creation of the SummaryFileWriter [#25976]) or by setting up the summary scope like this:

```python
with stats_writer.as_default():
    count = 1
    for _st in tfstddev_iter:
        tf.compat.v2.summary.scalar("stddev",_st,step=count,description='stddev')
        count += 1
```

**Comment by kshaeffer** [comment]
meyerjo, thank you for your comment.
I tried the context: with stats_writer.as_default():
This produced the same Traceback:

Traceback (most recent call last):
  File "./tf2summary_bug.py", line 72, in <module>
    tf.compat.v2.summary.scalar("stddev",_st,step=count,description='stddev')
  File "/usr/lib/python3/dist-packages/tensorboard/plugins/scalar/summary_v2.py", line 55, in scalar
    with tf.summary.summary_scope(
AttributeError: module 'tensorflow._api.v1.summary' has no attribute 'summary_scope'

I do not see why this would need a custom summary scope. The problem seems to be the code is executing in the summary_v2.py code as expected and encountering a v1.summary object that is not expected. I could be wrong. Just thinking out loud.
