### ISSUE TITLE
Add a `length` or size attribute to the `tf.data.Dataset`

### ISSUE THREAD

**Issue by 00krishna** [tensorflow/tensorflow#26966]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):
Tensorflow version 1.13.1, running on Ubuntu linux 18.04 LTS x64. Yes, I would be willing to contribute. 

**Describe the feature and the current behavior/state.**
The feature request is to add a length or size method on the `tf.data.Dataset` class. This would allow users to check the number of records in a dataset without having to iterate through the entire dataset. 

Here is a simple use case. I have a bunch of images and labels that I encode to TFRecords format for Tensorflow. The data wrote to the TFRecords format with no trouble, and I can open the dataset with `tf.data.TFRecordDataset()`. I was even able to decode the images and make sure that the data was properly encoded. So far so good. 

However, one challenge is that there does not seem to be an easy way to find the number of records that were encoded into the TFRecords file. One thing I would like to check is whether the number of records encoded to the TFRecords file is equal to the number of images in the source directory. Right now the only way to count the records is to setup the `tf.data.Dataset()`, setup the parse function, the batches, and the iterator. And then I would need to iterate through the dataset in order to count the number of records. This seems to be a lot of work to do a simple check on the number of examples encoded to the TFRecords file. 

Another caveat is that a user could just look at the size of a TFRecords file to get a sense if all of the data is encoded. But this approach has problems because the data encoding to string makes the size of the TFRecords vary substantially (plus or minus) from the sum of the sizes of the individual image and label files. So that metric does not really clarify whether all the data has been encoded. 

**Will this change the current api? How?**
This would change the `tf.data.Dataset` api. Seems like this would just add an additional method to the `Dataset` class to check for length, just as is done in `numpy` or `pandas`, etc. Even tensors have a `shape` attribute.

I understand that the `Dataset` API is an iterator and is deliberately setup to not load all data into memory. So that is fine. But users still need to check that the data they are putting into the TFRecords files still need to check/test that the data is encoded properly. 

**Who will benefit with this feature?**
Any user who uses the `tf.data.Dataset` API to pass data into Tensorflow. This feature will simplify checks/tests to ensure data credibility.

**Any Other info.**
Here are some Stack Exchange posts that show the cumbersome way to do this kind of check today. And even then I am not sure that these approaches are entirely successful. 

https://stackoverflow.com/questions/51871573/is-there-a-way-to-get-the-size-of-tfrecord-file-and-the-size-of-one-example-in-i

https://stackoverflow.com/questions/42799007/number-of-examples-in-each-tfrecord

https://stackoverflow.com/questions/39196955/how-to-get-the-total-number-of-entries-contained-in-a-tfrecord-file

**Comment by jsimsa** [comment]
The tf.data API provides the [cardinality](https://www.tensorflow.org/api_docs/python/tf/data/experimental/cardinality) method which returns the cardinality of a dataset (when the cardinality can be computed efficiently from the cardinality of its inputs). Unfortunately, the method will return "unknown" for TFRecord dataset as there is no other way to determine the number of records in a TFRecord file then reading the entire file to the end.

**Comment by Harrypotterrrr** [comment]
I am still waiting for this feature of tf 2.x

**Comment by jsimsa** [comment]
In general, to compute the size of the dataset, one would need to run:

```
i = 0
for elem in dataset: 
  i = i + 1
```

Which is simple enough for users to run themselves (note that this can hang if the input dataset is infinite).

**Comment by Harrypotterrrr** [comment]
I use a counter var to store the number of input when I build the data loader. but still, I think it will be more convenient for the user to get dataset.length such kind of attribute.

**Comment by jsimsa** [comment]
I agree that it would be convenient but I also think that the expectation should be that `dataset.length` does not have to evaluate the entire input pipeline to return a value (nevermind the fact that it would need to solve the halting the problem to determine whether the input pipeline is finite). In other words, I don't think it makes sense to have a "length" attribute.

`cardinality` already provides the information when readily available (i.e. when it is known without having to execute the input pipeline). In cases when `cardinality` cannot be computed without executing the input pipeline, users can compute the information using three lines of code, which in my opinion more clearly communicates the fact that computation of cardinality may in general take a long time.

**Comment by mehran66** [comment]
sum(1 for _ in test_ds.unbatch()) works for me but having sth like dataset.length that does not evaluate the entire input pipeline would be very convenient.
