### ISSUE TITLE
All images were broken in Chinese document (404)

### ISSUE THREAD

**Issue by Ethan-yt** [tensorflow/tensorflow#26978]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version:
- Doc Link: https://www.tensorflow.org/guide/premade_estimators

**Describe the documentation issue**

All images were broken in guide pages.
For example:
https://www.tensorflow.org/images/tensorflow_programming_environment.png
in 
https://www.tensorflow.org/guide/premade_estimators

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by Ayush517** [comment]
Everything's working fine on my browser
<img width="1680" alt="Screenshot 2019-03-21 at 5 52 04 PM" src="https://user-images.githubusercontent.com/31190928/54751828-19eb3000-4c02-11e9-85ce-1813dca763e7.png">

**Comment by Ethan-yt** [comment]
```
curl 'https://www.tensorflow.org/images/tensorflow_programming_environment.png' -H 'authority: www.tensorflow.org' -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7' --compressed -I
HTTP/1.1 200 Connection established

HTTP/2 404
content-type: text/html; charset=utf-8
strict-transport-security: max-age=31536000; includeSubdomains
x-frame-options: SAMEORIGIN
x-xss-protection: 0
x-content-type-options: nosniff
x-cloud-trace-context: fbf6907010d1ba7603f98fe89425f75e
content-length: 38065
date: Thu, 21 Mar 2019 13:11:43 GMT
server: Google Frontend
alt-svc: quic=":443"; ma=2592000; v="46,44,43,39"


curl 'https://www.tensorflow.org/images/tensorflow_programming_environment.png' -H 'authority: www.tensorflow.org' -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' -H 'accept-encoding: gzip, deflate, br'  -I
HTTP/1.1 200 Connection established

HTTP/2 200
content-type: image/png
strict-transport-security: max-age=31536000; includeSubdomains
x-frame-options: SAMEORIGIN
x-xss-protection: 0
x-content-type-options: nosniff
x-cloud-trace-context: 07623ca89bcd658a37ee646a4b5fb73d
content-length: 59845
date: Thu, 21 Mar 2019 13:15:29 GMT
server: Google Frontend
alt-svc: quic=":443"; ma=2592000; v="46,44,43,39"

```
Maybe it is because of the language. After removing `accept-language` it shows 200.


@Ayush517 Is it still working in Chinese version?

**Comment by lamberta** [comment]
Had some server issues earlier that seemed to have been resolved. These both seem to work now:
* https://tensorflow.google.cn/guide/premade_estimators?hl=zh-cn
* https://www.tensorflow.org/guide/premade_estimators?hl=zh-cn

Please re-open if you run into this again. Thanks
