### ISSUE TITLE
Error file not found, when running protoc command. (use tensorflow  Objection detection api tutorial )

### ISSUE THREAD

**Issue by OsamaNaeem1995** [tensorflow/tensorflow#26981]
<

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 64 bit
- 
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1
- Python version: 3.5.3
- Installed using virtualenv? pip? conda?: pip

**Problem Description*
I am trying to run "introduction use tensorflow objection detection api tutorial" 
https://pythonprogramming.net/introduction-use-tensorflow-object-detection-api-tutorial/  

. I have installed protoc version 3.7.0 for my 64bit windows 10. I extracted the protoc file into the models-master/research directory. 

When i run the following command 
 **protoc object_detection/protos/*.proto --python_out=** 

i get the following error 

 **_### no such file or directory_** 
  

How do i solve this error ?

**Comment by Ayush517** [comment]
Is this given on the official website?
Please use official Tensorflow [Link](https://github.com/tensorflow/models/tree/master/research/object_detection) instead of third party tutorials.

**Comment by OsamaNaeem1995** [comment]
yeah the 'protoc' command was mentioned in the website, i gave you the link.

**Comment by ymodak** [comment]
Did you run the ``` protoc object_detection/protos/*.proto --python_out=.``` from command from the ```tensorflow/models/research/``` directory? Can you please confirm? Thanks!

**Comment by OsamaNaeem1995** [comment]
I ran it in the directory u mentioned and it run fine. But when I went on
to run the code it could not recognize the  .proto files it had to import.
Giving an error
error in " cannot import from utils"

**Comment by ymodak** [comment]
Apologies for the delay in response. tensorflow/models repo can be a good platform to discuss tensorflow object detection api tutorial related questions. Please post on [tensorflow/models](https://github.com/tensorflow/models/issues) repo if still facing problems. Thanks!
