### ISSUE TITLE
[TF 2.0 API Docs] tf.math modules, new endpoints, gen_math_ops.py

### ISSUE THREAD

**Issue by 8bitmp3** [tensorflow/tensorflow#26984]
**System information**
- TensorFlow version: 2.0 alpha
- Doc links: 
`tf.math` module-related, including:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/log
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/less
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/less_equal
... and **many more** - a lot of endpoints mentioned below affected

**Describe the documentation issue**

Similar to [26530](https://github.com/tensorflow/tensorflow/issues/26530), [25802](https://github.com/tensorflow/tensorflow/issues/25802), [25846](https://github.com/tensorflow/tensorflow/issues/25846)

(May be similar to [26532](https://github.com/tensorflow/tensorflow/issues/26532) but has to do with `gen_math_ops.py` not `[math_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_ops.py)`.)

- **Incorrect links:**
Missing links to ?non-existent `...python/ops/gen_math_ops.py`

Since [1.10](https://github.com/tensorflow/tensorflow/blob/67a4cbbc7cacdbc33b2adb44f1b08b5a0dbc3186/RELEASE.md):
```
New symbols have been added to the following modules: tf.debugging, tf.dtypes, tf.image, tf.io, tf.linalg, tf.manip, **tf.math**, tf.quantization, tf.strings
```

`...python/ops/gen_math_ops.py` has been referenced a bunch of times e.g. [here](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math/log
) but does not appear to exist or cannot be easily found. There are similar issues with examples, raises, etc for some if not all of the [following](https://github.com/tensorflow/tensorflow/blob/67a4cbbc7cacdbc33b2adb44f1b08b5a0dbc3186/RELEASE.md): 
```
New endpoints in tf.math module namespace: tf.math.acos, tf.math.acosh, tf.math.add, tf.math.asin, tf.math.asinh, tf.math.atan, tf.math.atan2, tf.math.atanh, tf.math.betainc, tf.math.ceil, tf.math.cos, tf.math.cosh, tf.math.digamma, tf.math.equal, tf.math.erfc, tf.math.exp, tf.math.expm1, tf.math.floor, tf.math.greater, tf.math.greater_equal, tf.math.igamma, tf.math.igammac, tf.math.invert_permutation, tf.math.less, tf.math.less_equal, tf.math.lgamma, tf.math.log, tf.math.log1p, tf.math.logical_and, tf.math.logical_not, tf.math.logical_or, tf.math.maximum, tf.math.minimum, tf.math.not_equal, tf.math.polygamma, tf.math.reciprocal, tf.math.rint, tf.math.rsqrt, tf.math.segment_max, tf.math.segment_mean, tf.math.segment_min, tf.math.segment_prod, tf.math.segment_sum, tf.math.sin, tf.math.sinh, tf.math.softplus, tf.math.softsign, tf.math.squared_difference, tf.math.tan, tf.math.unsorted_segment_max, tf.math.unsorted_segment_min, tf.math.unsorted_segment_prod, tf.math.unsorted_segment_sum, tf.math.zeta
```

- **Usage examples**
Needs examples for each of tf.math calculations e.g.
`tf.math.log(42.)` returns
```
<tf.Tensor: id=5, shape=(), dtype=float32, numpy=3.7376697>
```

- **Raises**
Not listed/defined. Obfuscated error from unexpected args (e.g. strings)

E.g. `tf.math.log('hello log')` gives this long error message for a simple natural log calculation. As @dynamicwebpaige said [here](https://github.com/tensorflow/tensorflow/issues/25802) all tf.math.* operations and the operations they influence ... would experience these same obfuscated XLA errors.
```
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-7-208ff95958ff> in <module>()
----> 1 tf.math.log('hello log')

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py in log(x, name)
   5327       try:
   5328         return log_eager_fallback(
-> 5329             x, name=name, ctx=_ctx)
   5330       except _core._SymbolicException:
   5331         pass  # Add nodes to the TensorFlow graph.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py in log_eager_fallback(x, name, ctx)
   5376   _attrs = ("T", _attr_T)
   5377   _result = _execute.execute(b"Log", 1, inputs=_inputs_flat, attrs=_attrs,
-> 5378                              ctx=_ctx, name=name)
   5379   _execute.record_gradient(
   5380       "Log", _inputs_flat, _attrs, _result, name)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     64     else:
     65       message = e.message
---> 66     six.raise_from(core._status_to_exception(e.code, message), None)
     67   except TypeError as e:
     68     if any(ops._is_keras_symbolic_tensor(x) for x in inputs):

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InternalError: Could not find valid device for node.
Node: {{node Log}}
All kernels registered for op Log :
  device='XLA_CPU'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
 [Op:Log]
```

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
Ok

**Comment by shashvatshahi1998** [comment]
I am not getting tf.math.log in math_ops.py

**Comment by mihaimaruseac** [comment]
Just a note for people working on this: if you add python doctests, please make sure to do so in Python files, not in `base_api/api_def` files as those are the APIs for other languages too.

**Comment by jvishnuvardhan** [comment]
@8bitmp3 Looks like this was resolved. Can we close this issue? Thanks
