### ISSUE TITLE
[TF2.0a0] Distribute Strategies and Summary Writer don't work together

### ISSUE THREAD

**Issue by meyerjo** [tensorflow/tensorflow#26980]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-alpha0
- Python version: python 3.6
- CUDA/cuDNN version: 10.1
- GPU model and memory: TITAN X

**Describe the current behavior**
I am trying to use tf.summary at the same time as using distribute strategies. However, the call to `strategy.experimental_run` seems to end the scope of the `summary_writer`. I have initialized it properly, but it is not available to me. I have tried passing the SummaryWriter object directly as another parameter of the train_step but it does not work and fails with the error message. Somehow, the scope seems to be lost through the experimental_run call.

```[ops/summary_ops_v2.py:608] ValueError: No step set via 'step' argument or tf.summary.experimental.set_step()```

For the most part, I followed this guide on how to work with DuplicateStrategies: 
https://www.tensorflow.org/alpha/tutorials/distribute/training_loops

**Describe the expected behavior**
Being able to write to write to the summary from within the training loop.

**Code to reproduce the issue**
```python
import tensorflow as tf

def train_step(input, s_writer):
  with s_writer.as_default():
    tf.summary.scalar('test', 0)

def distributed_train(s_writer):
  return strategy.experimental_run(
    lambda x: train_step(x, s_writer), train_iterator)

if __name__ == '__main__':
  dataset = tf.data.Dataset.from_tensor_slices(
    (tf.random.uniform([5, 100])))

  strategy = tf.distribute.MirroredStrategy()
  summary_writer = tf.summary.create_file_writer('/tmp/test')

  with summary_writer.as_default() as summary_scope:
    with strategy.scope():

      train_iterator = strategy.make_dataset_iterator(dataset)
      train_iterator.initialize()

      tf.summary.experimental.set_step(0)
      # This works
      train_step(None, summary_writer)

      # This fails
      distributed_train(summary_writer)
```

**Comment by guptapriya** [comment]
Thanks for reporting, we will take a look at it.

**Comment by er91** [comment]
Issue identified, fix is on the way (should be submitted today)

**Comment by er91** [comment]
Hi Johannes,

Could you please test if https://github.com/tensorflow/tensorflow/commit/7bdb838313d322773908cf8368c03ec98117ad55 solves your issue?

Thanks!

**Comment by meyerjo** [comment]
I guess it is already included in the most recent nightly, isn't it? It seems to be working now.

**Comment by er91** [comment]
Yeah nightly is less than one day old.

Good to know it works for you :-) 

Closing this issue.
