### ISSUE TITLE
Keras: Bug when creating a custom layer without inputs

### ISSUE THREAD

**Issue by nairouz** [tensorflow/tensorflow#26996]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): 1.13
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the expected behavior**
I want to implement a Keras custom layer without any input, just trainable weights. This kind of layers is very important for visualization (e.g., [Understanding Deep Image Representations by Inverting Them](https://arxiv.org/abs/1412.0035))

**Code to reproduce the issue**
 
    class Simple(Layer):

        def __init__(self, output_dim, **kwargs):
           self.output_dim = output_dim
           super(Simple, self).__init__(**kwargs)

        def build(self):
           self.kernel = self.add_weight(name='kernel', shape=self.output_dim, initializer='uniform', trainable=True)
           super(Simple, self).build()  

        def call(self):
           return self.kernel

        def compute_output_shape(self):
           return self.output_dim

    X = Simple((1, 784))()

**Other info / logs**

I am getting an error message:

`__call__() missing 1 required positional argument: 'inputs'`

**Comment by meyerjo** [comment]
You can just create `__call__(self, inputs=None)`, can't you?

**Comment by nairouz** [comment]
Nope.
`None values not supported.`

**Comment by adalca** [comment]
@nairouz , did you ever write a complete version of this layer?
