### ISSUE TITLE
2.0 Reference Models: MobileNetv2 (TPU with dist strat and Keras)

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#26997]
**MobileNetV2** is a significant improvement over [MobileNetV1](https://research.googleblog.com/2017/06/mobilenets-open-source-models-for.html) and pushes the state of the art for mobile visual recognition including classification, object detection and semantic segmentation. It builds upon the ideas from MobileNetV1, using depthwise separable convolution as efficient building blocks. However, V2 introduces two new features to the architecture: 

1. Linear bottlenecks between the layers, and 
2. Shortcut connections between the bottlenecks1.

The research team's academic paper describes MobileNetV2 in detail: https://arxiv.org/abs/1801.04381.

An example of MobileNetV2 implemented with Slim can be found [here](https://colab.research.google.com/github/tensorflow/models/blob/master/research/slim/nets/mobilenet/mobilenet_example.ipynb).

The purpose of this issue is to migrate models into the TF 2.0 Keras API. Each migrated model must be eager and distribution compatible, with tests, and all associated engineering artifacts.

**Comment by rok** [comment]
@dynamicwebpaige I'd like to contribute this.

**Comment by kumariko** [comment]
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues),To know more see;[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)

**Comment by kumariko** [comment]
@dynamicwebpaige Could you please have a look on the [link1](https://github.com/tensorflow/models/blob/master/research/object_detection/models/keras_models/mobilenet_v2.py) , [link2](https://colab.research.google.com/github/rok/models/blob/mobilenet_v2_tpu_with_dist_strat_and_keras/research/object_detection/mobilenet_v2_example.ipynb) , [link3](https://www.tensorflow.org/api_docs/python/tf/keras/applications/mobilenet_v2/MobileNetV2) and let us know if it helps?  
If you still need help on this issue please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues),To know more see; [https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) Thanks!
