### ISSUE TITLE
tf.train.Example?

### ISSUE THREAD

**Issue by xksteven** [tensorflow/tensorflow#2699]
In the file

https://github.com/tensorflow/tensorflow/blob/r0.9/tensorflow/examples/how_tos/reading_data/convert_to_records.py#L64

What does  tf.train.Example()  do?  I couldn't find it anywhere in the documentation.

**Comment by mrry** [comment]
It's a protocol buffer that is commonly used as the data format for training and evaluation examples in TensorFlow. The format is defined here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/example/example.proto

The `tf.train.Example()` call instantiates a new protocol buffer, and fills in some of its fields.
