### ISSUE TITLE
in nmt_with_attention,the gru layer in decoder confuse me

### ISSUE THREAD

**Issue by sailist** [tensorflow/tensorflow#26990]
[nmt_with_attention file link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb)
In the Decoder class, the gru layer is defined, and it is used in `call()` function, the code is:
```python
output, state = self.gru(x)
```

My question is, the gru cell state may not be updated? In the same batch, every timestamp use the same cell state? Is my understand correct?
```python
output, state = self.gru(x,initial_state=context_vector)
```
I then use this code and retrained the model, there is no obvious difference. Maybe someone can help me...

Forgive my lame English.

**Comment by sailist** [comment]
The loss when I use context_vector as the gru's initial_state
···
Epoch 5 Batch 0 Loss 0.4456
···

**Comment by ymodak** [comment]
@yashk2810 Can you PTAL? Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by hihell** [comment]
same problem here, in decoder:
`output, state = self.gru(x)`
decoder call is called by time step, this will make decoder GRU stateless, there is no previous state passed to this time step.
and after I change it to stateful:
`output, state = self.gru(x, initial_state = hidden)` 
the model's loss is increased compare to the stateless model
can anyone explain?
