### ISSUE TITLE
2.0 Reference Models: MobileNetV2 (1 GPU, 8 GPU with dist strat and Keras)

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#26998]
**MobileNetV2** is a significant improvement over [MobileNetV1](https://research.googleblog.com/2017/06/mobilenets-open-source-models-for.html) and pushes the state of the art for mobile visual recognition including classification, object detection and semantic segmentation. It builds upon the ideas from MobileNetV1, using depthwise separable convolution as efficient building blocks. However, V2 introduces two new features to the architecture: 

1. Linear bottlenecks between the layers, and 
2. Shortcut connections between the bottlenecks1.

The research team's academic paper describes MobileNetV2 in detail: https://arxiv.org/abs/1801.04381.

An example of MobileNetV2 implemented with Slim can be found [here](https://colab.research.google.com/github/tensorflow/models/blob/master/research/slim/nets/mobilenet/mobilenet_example.ipynb).

The purpose of this issue is to migrate models into the TF 2.0 Keras API. Each migrated model must be eager and distribution compatible, with tests, and all associated engineering artifacts.

**Comment by captain-pool** [comment]
@dynamicwebpaige I'ld like to work on this. can you please assign this to me?

**Comment by captain-pool** [comment]
@dynamicwebpaige Can You give me some pointers how to start? I went through the repository to find something where the model is implemented. However all I found is that there's no implementation of mobiilenet_v2 in tensorflow. The model is being imported from keras_applications and the appropriate object is returned when tf.keras.applications.MobileNetV2 is invoked.
**REF:**
 https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/mobilenet_v2.py#L31-L32

**Comment by kumariko** [comment]
@dynamicwebpaige Look like you are looking for the following feature [link1]([url](url)) , [link2](https://keras.io/api/applications/mobilenet/)

If you think the above is not the feature you are looking, please feel free to open a PR in [keras-team/keras](https://github.com/keras-team/keras/issues) repository.
Please note that Keras development moved to [keras-team/keras](https://github.com/keras-team/keras/issues) repository to focus on only keras. Thanks!
