### ISSUE TITLE
Warning while creating Session on Mac OS X: can't determine number of CPU cores

### ISSUE THREAD

**Issue by delip** [tensorflow/tensorflow#27]
While creating a Session, I get this warning (using pre-built whl on OSX). Any ideas?

```
s = tf.Session()
can't determine number of CPU cores: assuming 4
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 4
can't determine number of CPU cores: assuming 4
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 4
```

**Comment by vrv** [comment]
Hi delip, we fixed this in https://github.com/tensorflow/tensorflow/commit/430a054d6134f00e5188906bc4080fb7c5035ad5 -- when we mint our next version of the pip binaries, this should be fixed.   Thanks for your report!

**Comment by delip** [comment]
Excellent!

**Comment by gynsolomon** [comment]
thanks!

**Comment by delip** [comment]
Just want to confirm that this warning went away with the latest build. I will be closing this. Thanks!
