### ISSUE TITLE
[TF 2.0] Documentation still mentions _ref types

### ISSUE THREAD

**Issue by Sklan** [tensorflow/tensorflow#27005]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version:2.0.0-alpha
- Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/dtypes/DType

**Describe the documentation issue**
The documentation of TF 2.0 still mentions ```_ref``` types even though it is no longer a thing.
Related issue #26941.

 
**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
Yes

**Comment by dynamicwebpaige** [comment]
Removing:

> In addition, variants of these types with the _ref suffix are defined for reference-typed tensors.

As well as:

```python
DType(T)       .is_compatible_with(DType(T).as_ref) == True
DType(T).as_ref.is_compatible_with(DType(T))        == False
DType(T).as_ref.is_compatible_with(DType(T).as_ref) == True
```

from the reference documentation. Thanks for alerting us to this issue!
