### ISSUE TITLE
TF2 has tf.floor but not tf.ceil

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#27003]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):n/a
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):archlinux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:n/a
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):tf-nightly-gpu-2.0-preview-2.0.0.dev20190319
- Python version:3.7
- Bazel version (if compiling from source):n/a
- GCC/Compiler version (if compiling from source):n/a
- CUDA/cuDNN version:n/a
- GPU model and memory:n/a

```python
import tensorflow as tf
print(tf.floor)
print(tf.ceil)
```
prints:
```
<function floor at 0x7fad8ad08950>
Traceback (most recent call last):
  File "a.py", line 6, in <module>
    print(tf.ceil)
AttributeError: module 'tensorflow' has no attribute 'ceil'
```
`tf.ceil` is only accessible through `tf.math.ceil` now. But `tf.floor` still exists.

I expect the two functions to either both exist or both not exist.

**Comment by dynamicwebpaige** [comment]
The replacement operation for `tf.ceil` in TF 2.0 is `tf.math.ceil`.

**Comment by shashvatshahi1998** [comment]
i am not getting the link , where i can contribute as in documentation it is written that tf.math.ceil() is in tensorflow/python/ops/gen_math_ops.py but there is no such file in tensorflow codebase.

**Comment by gshashank84** [comment]
The gen_math_ops.py file is missing in repo of Tensorflow 2.0.0-alpha0, but the functions of this file are working :confused:

**Comment by yongtang** [comment]
Added a PR #27068 for the fix to deprecate tf.floor in TF 2.0.

**Comment by jvishnuvardhan** [comment]
@ppwwyyxx most of the math ops are moved under tf.math.*. Both the ceil and floor are in TF as `tf.math.ceil` and `tf.math.floor`. As @alextp mentioned in the related PR https://github.com/tensorflow/tensorflow/pull/27068 that `TF2 API frozen, so we can't remove it anymore.`

I am closing this issue. Feel free to reopen if you have any concerns. Thanks!
