### ISSUE TITLE
tf.dataset failed to correctly load image data

### ISSUE THREAD

**Issue by SystemErrorWang** [tensorflow/tensorflow#27027]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Debian GNU/Linux 8 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
None
- TensorFlow installed from (source or binary):
conda install 
- TensorFlow version (use command below):
tensorflow-gpu1.12.0rc0
- Python version:
python 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
cuda 9.2 with cdunn7.3.1
- GPU model and memory:
nvidia1080ti, 11gb

**Describe the current behavior**

i tried to use tf.dataset api to build a custom dataloader, all the images are in .jpg format and rgb color space with exact 3 channels (i double checked this using opencv to load images and numpy to print image shape). then i got this error:

InvalidArgumentError (see above for traceback): Cannot batch tensors with different shapes in component 0. First element had shape [270,270,3] and element 92 had shape [270,270,1].

**Code to reproduce the issue**
```
def load_function(image_path, label_path, crop_size=256):
        image = tf.read_file(image_path)
        image = tf.image.decode_jpeg(image)
        image = tf.image.resize_images(image, [270, 270])
        image = tf.image.random_crop(image, [crop_size, crop_size, 3])
        label = tf.read_file(label_path)
        label = tf.image.decode_png(label)
        label = tf.image.resize_images(label, [270, 270])
        label = tf.image.random_crop(label, [crop_size, crop_size, 1])
        return image, label
```

**Comment by jsimsa** [comment]
What the error indicates is that the 92nd image has different shape ([270, 270, 3] vs. [270, 270, 1]) then the previous 91 images. 

My recommendation would be to remove `batch` from your input pipeline and then iterate through your input pipeline one by one, printing out the shape and image name to identify the problematic image.

This is problem with your data, not with tf.data.
