### ISSUE TITLE
"ERROR: Cannot find './util/python/python_lib'"

### ISSUE THREAD

**Issue by jplu** [tensorflow/tensorflow#2703]
Hello,

I have the following error when I try to compile the pip package from the source code.

### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Feb  9 18:48 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.4
lrwxrwxrwx 1 root root       17 Feb  9 18:48 /usr/local/cuda/lib64/libcudnn.so.4 -> libcudnn.so.4.0.7
-rwxrwxr-x 1 root root 61453024 Feb  8 23:12 /usr/local/cuda/lib64/libcudnn.so.4.0.7
-rw-rw-r-- 1 root root 62025862 Feb  8 23:12 /usr/local/cuda/lib64/libcudnn_static.a
```
If installed from sources, provide the commit hash: ea9e00a630f91a459dd5858cb22e8cd1a666ba4e

### Steps to reproduce
1. git clone https://github.com/tensorflow/tensorflow
2. cd tensorflow
3. ./configure
4. bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
5. bazel build -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures

### Logs or other output that would be helpful

```
ERROR: /home/plu/git/tensorflow/util/python/BUILD:14:1: Executing genrule //util/python:python_check failed: bash failed: error executing command 
  (cd /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/packages/bin:.:/homes/plu/docker/:/usr/local/cuda-7.5/bin/:/homes/plu/bin/:/usr/local/openmpi-1.10.1/bin/ \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; OUTPUTDIR="bazel-out/host/genfiles/util/python/"; util/python/python_config.sh --check && touch $OUTPUTDIR/python_checked'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: bash failed: error executing command 
  (cd /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/packages/bin:.:/homes/plu/docker/:/usr/local/cuda-7.5/bin/:/homes/plu/bin/:/usr/local/openmpi-1.10.1/bin/ \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; OUTPUTDIR="bazel-out/host/genfiles/util/python/"; util/python/python_config.sh --check && touch $OUTPUTDIR/python_checked'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.


ERROR: Cannot find './util/python/python_lib'.  Did you run configure?
```

But, I do have this folder locally in the Tensorflow repository. Did I do something wrong? Or it is a bug coming from Tensorflow?

Thanks in advance for any help!

**Comment by girving** [comment]
Did you run configure?

**Comment by jplu** [comment]
Hello,

Yes I did run, configure as it is written in the "Steps to reproduce" section of my previous post :-)

**Comment by girving** [comment]
@jplu: I saw that, but one can never be too careful when triaging hundreds of issues. :)

Can you add a `pwd` line to `python_config.sh` to see what directory it's in?  I'm not sure how Bazel genrules work, so it's possible that the BUILD file should declare some dependencies.

**Comment by jplu** [comment]
@girving: No worries I understand :)

I put a ```pwd``` command right after the licence header and run once again

```bazel build -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures```

But nothing is displayed:

```
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures
WARNING: Output base '/homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7' is on NFS. This may lead to surprising failures and undetermined behavior.
......
INFO: Found 1 target...
ERROR: /home/plu/git/tensorflow/util/python/BUILD:14:1: Executing genrule //util/python:python_check failed: bash failed: error executing command 
  (cd /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/packages/bin:.:/homes/plu/docker/:/usr/local/cuda-7.5/bin/:/homes/plu/bin/:/usr/local/openmpi-1.10.1/bin/ \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; OUTPUTDIR="bazel-out/host/genfiles/util/python/"; util/python/python_config.sh --check && touch $OUTPUTDIR/python_checked'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: bash failed: error executing command 
  (cd /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/packages/bin:.:/homes/plu/docker/:/usr/local/cuda-7.5/bin/:/homes/plu/bin/:/usr/local/openmpi-1.10.1/bin/ \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; OUTPUTDIR="bazel-out/host/genfiles/util/python/"; util/python/python_config.sh --check && touch $OUTPUTDIR/python_checked'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/tensorflow


ERROR: Cannot find './util/python/python_lib'.  Did you run configure?


Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 15.143s, Critical Path: 2.45s
```

**Comment by girving** [comment]
@jplu You might need a flag to bazel to get it to not suppress stdout.  Not which that that is, though; `bazel help build` doesn't make it obvious.  The high tech option is `pwd > ~/blah`.

**Comment by jplu** [comment]
The redirect command did the thing, I had to think about this solution before...

Anyway, here the path:

```/homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/tensorflow```

**Comment by girving** [comment]
@damienmg We have a `python_check` genrule that verifies that a symbolic link to a directory exists.  I think the check is failing since we don't depend on the symbolic link.  Can one put a symbolic link to a directory in a normal filegroup, or is something special required?

https://github.com/tensorflow/tensorflow/blob/master/util/python/BUILD#L14

On the other hand, @martinwicke, I suppose if we add `python_lib` as a dependency then `python_check` will fail with a less informative error message.  Thoughts?  I imagine this error message has a significant role in reducing filed issues, so it'd be bad to make it worse.

**Comment by damienmg** [comment]
FWIW: the path was in the output :) `/homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/tensorflow`

The test that check a symlink is printing a more comprehensive message about it not being a symlink, or did I read the script wrong?

**Comment by damienmg** [comment]
(and nothing special required with symlinks, but remember that when running, most files will actually be symlinks while directories will be recreated).

**Comment by martinwicke** [comment]
Can we just use all_files as a data depedency for python_check? That will not fail (since it's just a glob), and if nothing is there, we'll still see it's not there and get our nice message.

**Comment by girving** [comment]
@martinwicke Seems reasonable.  Want to assign it to someone?

**Comment by ebrevdo** [comment]
This used to work out of the box, no?  Sounds like a bug was recently introduced.

**Comment by martinwicke** [comment]
Olivia, can you change the BUILD file in util/python to have a filegroup containing all files in the directory, like this:

filegroup(
    name = "configure_files",
    data = glob([
        "*",
    ])
)

(syntax may be screwy), and add that as a data dependency to the python_check target?

And then make sure it works... I hadn't seen this before.

**Comment by martinwicke** [comment]
@jplu can you check whether #2958 fixes your problem?

**Comment by jplu** [comment]
Sorry for the delay I was not able to use this computer until now.

Unfortunately the problem still remains :-(

```
WARNING: Output base '/homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7' is on NFS. This may lead to surprising failures and undetermined behavior.
WARNING: /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/external/protobuf/WORKSPACE:1: Workspace name in /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
WARNING: /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/external/re2/WORKSPACE:1: Workspace name in /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
WARNING: /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/external/highwayhash/WORKSPACE:1: Workspace name in /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/external/highwayhash/WORKSPACE (@__main__) does not match the name given in the repository's definition (@highwayhash); this will cause a build error in future versions.
WARNING: /home/plu/git/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
INFO: Found 1 target...
ERROR: /home/plu/git/tensorflow/util/python/BUILD:14:1: Executing genrule //util/python:python_check failed: bash failed: error executing command 
  (cd /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/packages/bin:.:/homes/plu/docker/:/usr/local/cuda-7.5/bin/:/homes/plu/bin/:/usr/local/openmpi-1.10.1/bin/ \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; OUTPUTDIR="bazel-out/local_linux-opt/genfiles/util/python/"; util/python/python_config.sh --check && touch $OUTPUTDIR/python_checked'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.


ERROR: Cannot find './util/python/python_lib'.  Did you run configure?


Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2.326s, Critical Path: 0.59s
```

I have done a fresh new clone corresponding to the commit https://github.com/tensorflow/tensorflow/commit/84225a2b612fe748c9c923f0c1cb8471911c3b77

**Comment by jmchen-g** [comment]
@caisq Could you take a look at this please?

**Comment by pjoz** [comment]
I had this same issue in the closed tickets referenced above, @jmchen-g thanks for re-opening this one.

**Comment by jplu** [comment]
Hello,

I have tested with the commit fefe52c that contains the fix proposed by @plutoshe. Unfortunately the issue still remains :(

```
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures
WARNING: Output base '/homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7' is on NFS. This may lead to surprising failures and undetermined behavior.
WARNING: /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/external/protobuf/WORKSPACE:1: Workspace name in /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
WARNING: /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/external/re2/WORKSPACE:1: Workspace name in /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
WARNING: /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/external/highwayhash/WORKSPACE:1: Workspace name in /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/external/highwayhash/WORKSPACE (@__main__) does not match the name given in the repository's definition (@highwayhash); this will cause a build error in future versions.
WARNING: /home/plu/git/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
INFO: Found 1 target...
ERROR: /home/plu/git/tensorflow/util/python/BUILD:14:1: Executing genrule //util/python:python_check failed: bash failed: error executing command 
  (cd /homes/plu/.cache/bazel/_bazel_plu/5fecb6612d2e95475ff53a54e377c3f7/tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/packages/bin:.:/homes/plu/docker/:/usr/local/cuda-7.5/bin/:/homes/plu/bin/:/usr/local/openmpi-1.10.1/bin/ \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; OUTPUTDIR="bazel-out/local_linux-opt/genfiles/util/python/"; util/python/python_config.sh --check && touch $OUTPUTDIR/python_checked'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.


ERROR: Cannot find './util/python/python_lib'.  Did you run configure?


Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1.909s, Critical Path: 0.20s
```

Don't hesitate to ask me if you need other information to help you to debug.

**Comment by martinwicke** [comment]
what's your bazel version?

**Comment by jplu** [comment]
I'm using Bazel 0.2.3

**Comment by pjoz** [comment]
I'm using bazel 0.2.2 with the same error

**Comment by martinwicke** [comment]
Which python did you specify when running `configure`? Also, can you run `/bin/bash`?

**Comment by pjoz** [comment]
Python specified is /usr/local/bin/python (version Python 2.7.11)

Ran /bin/bash before the install instructions with no change in result.

**Comment by jplu** [comment]
The specified Python is:

```
/usr/bin/python --version
Python 2.7.6
```

I also can run ```/bin/bash```:

```
/bin/bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by martinwicke** [comment]
Ok. I'm just stabbing at the dark -- I cannot reproduce this and I'm wondering what the difference between our installations might be.

Can you try running using docker just to see if that works?

**Comment by jplu** [comment]
It works via Docker:

```
docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow
Unable to find image 'gcr.io/tensorflow/tensorflow:latest' locally
latest: Pulling from tensorflow/tensorflow
759d6771041e: Pull complete 
8836b825667b: Pull complete 
c2f5e51744e6: Pull complete 
a3ed95caeb02: Pull complete 
b1a230d2f7d7: Pull complete 
f4bd848af23b: Pull complete 
9ff2d28f3bea: Pull complete 
de3ac9a732b6: Pull complete 
ba1ff7fd8338: Pull complete 
8b638dd1001b: Pull complete 
4c3f9ea22d7e: Pull complete 
Digest: sha256:8ae5229583adf18c1e50ac7fbf4c25301aef186eb3cc7c23d85999328a72ac4b
Status: Downloaded newer image for gcr.io/tensorflow/tensorflow:latest
[I 06:05:16.943 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
/usr/local/lib/python2.7/dist-packages/widgetsnbextension/__init__.py:30: UserWarning: To use the jupyter-js-widgets nbextension, you'll need to update
    the Jupyter notebook to version 4.2 or later.
  the Jupyter notebook to version 4.2 or later.""")
[W 06:05:16.965 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 06:05:16.966 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 06:05:16.969 NotebookApp] Serving notebooks from local directory: /notebooks
[I 06:05:16.969 NotebookApp] 0 active kernels 
[I 06:05:16.969 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 06:05:16.969 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

**Comment by jplu** [comment]
When I run:

```
util/python/python_config.sh --check
```

I get the same error.

**Comment by jplu** [comment]
Once the run of ```./configure``` is finished the environement variable ```$PYTHON_BIN_PATH``` is not set and makes crash the command:

```
util/python/python_config.sh --setup
```

**Comment by jplu** [comment]
Ok, I found the issue, the script ```./configure``` creates two symlinks in the folder ```util/python/```:

- ```python_include -> /usr/include/python2.7```
- ```python_lib -> /usr/lib/python2.7/site-packages```

The problem is that the folder ```/usr/lib/python2.7/site-packages``` doesn't exists for me.

**Comment by martinwicke** [comment]
Interesting. We actually ask distutils for this path (see [utils/python/python_config.sh](https://github.com/tensorflow/tensorflow/blob/master/util/python/python_config.sh)), so it appears distutils is misconfigured. We could switch to an [alternative method](http://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory), but I'm not at all sure it's better in general.

**Comment by jplu** [comment]
The main problem is that people might have multiple location for their Python's packages. So why not checking the ```$PYTHONPATH``` variable? As this variable as to be updated to include all the path that are not "Python standardized" and that we want to use in general.

**Comment by martinwicke** [comment]
Let's see if I understood:

Let's say `distutils` lies to us and gives us a non-existent path (as in your case). What should we do next? We could ask the `site` module and see if it gives us an existing path (would it in your case?). If that fails also, we can ask the user. We should make sure the user gives us a path which is in `$PYTHONPATH`, otherwise it's very unlikely to work.

**Comment by jplu** [comment]
Yes you have understood. If a Python lib is not in the standard location or in ```$PYTHONPATH``` then it is not possible to use it as Python will not know where are the files to import.

For example for my case, my ```$PYTHONPATH``` looks like this:

```
echo $PYTHONPATH
/home/plu/git/deepdetect/clients/python/:/usr/local/python/lib/python2.7/site-packages/:/home/plu/git/caffe/python
```

If I run the interactive python and do ```import caffe``` I can load all the files in my current environment. In the case I remove ```/home/plu/git/caffe/python``` from my ```$PYTHONPATH``` and redo an ```import caffe``` I will get an ```ImportError: No module named caffe```

So I think, by just checking this environment variable we should be safe, but we never know. Nevertheless, checking the ```site``` is for me not enough, as for me:

```
>>> import site; site.getsitepackages()
['/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
```

I get only those two, and not the others contained in my ```$PYTHONPATH``` which mean that if someone prefer to compile every package itself and put them in a specific location, we will miss them. So for me the steps to do are the following:

1. use ```site``` to get a first list
2. merge the result with the content of ```$PYTHONPATH```
3. ask the user if all the path are well known, otherwise ask him to add the wanted other paths

**Comment by martinwicke** [comment]
@itsmeolivia can you look into modifying the python setup to include the workflow outlined by @jplu?

**Comment by jplu** [comment]
Perfect! Everything is compiling like a charm with this fix

Thanks a lot!
