### ISSUE TITLE
gpu doesn't report error when id is actually out of range in tf.nn.embedding_lookup(embed, ids) 

### ISSUE THREAD

**Issue by StarYoung** [tensorflow/tensorflow#27033]
- TensorFlow version (use command below):1.13
- Python version:3.6

```
import tensorflow as tf
x = tf.constant(999)
#with tf.device('/cpu:0'):
#    voc_emb = tf.get_variable(name="voc_emb", dtype=tf.float32, shape=[3, 12])
#    embedded_x = tf.nn.embedding_lookup(voc_emb, x)
voc_emb = tf.get_variable(name="voc_emb", dtype=tf.float32, shape=[3, 12])
embedded_x = tf.nn.embedding_lookup(voc_emb, x)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(embedded_x))
```

the following above I run on cpu and gpu separately, 
while cpu reports:
InvalidArgumentError (see above for traceback): indices = 999 is not in [0, 3)
	 [[node embedding_lookup (defined at test.py:24) ]]

but gpu just give an output like this:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

**Comment by chwang85** [comment]
If back-propagation goes through `embedded_x`, will there be an error?

**Comment by StarYoung** [comment]
> If back-propagation goes through `embedded_x`, will there be an error?

Just figured this out, see:
https://www.tensorflow.org/api_docs/python/tf/nn/embedding_lookup

> validate_indices: DEPRECATED. If this operation is assigned to CPU, values in indices are always validated to be within range. If assigned to GPU, out-of-bound indices result in safe but unspecified behavior, which may include raising an error.

**Comment by chwang85** [comment]
I know that, but if you back-propagate to `embedded_x`, there will be an error even on GPU...

**Comment by sanatmpa1** [comment]
@StarYoung ,

We see that this issue is using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to latest stable version and let us know if the issue still persists in newer versions.we will get you the right help.Thanks!
