### ISSUE TITLE
math_ops.div_no_nan support for float16

### ISSUE THREAD

**Issue by jacobzweig** [tensorflow/tensorflow#27044]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: 1.14.1-dev20190306
- Python version: 3.6
- CUDA/cuDNN version: 1.01
- GPU model and memory: M60

**Describe the current behavior**
math_ops.div_no_nan only allows `float32` or `float64`, this limits the ability to use `MirroredStrategy` with `float16`

**Comment by shashvatshahi1998** [comment]
there is no problem I will add the feature in core of math_ops soon.

**Comment by shashvatshahi1998** [comment]
I got some issues in my pull request, sorry for that but you can do it on your own go to TensorFlow's/core/ops/math_ops.cc and search for DivNoNan and add required dtypes in its attributes

**Comment by yongtang** [comment]
The issue seems to have been fixed in:
https://github.com/tensorflow/tensorflow/commit/11245e46584b2e610ee7ea8258978bfcef1f5c26

**Comment by jacobzweig** [comment]
Excellent, thanks @shashvatshahi1998 and @yongtang!
