### ISSUE TITLE
tf.Module doesn't see variables from keras layers

### ISSUE THREAD

**Issue by cericson** [tensorflow/tensorflow#27046]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-alpha0
- Python version: 3.6.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
User-defined subclasses of `tf.Module` do not recognize and include variables from keras layer object members.

**Describe the expected behavior**
Subclassing `tf.Module` should expose the variables (not to mention training_variables) from all sub-computations, including keras layers, so long as these computations are set as members of the class.

**Code to reproduce the issue**
This came from a TF2.0 port of the pytorch dynamic graph example [here](https://pytorch.org/tutorials/beginner/pytorch_with_examples.html#pytorch-control-flow-weight-sharing).
```
import tensorflow as tf
import numpy as np
import random

class DynamicNet(tf.Module):
    def __init__(self, D_in, H, D_out):
        self.input_linear = tf.keras.layers.Dense(H, input_dim=D_in)
        self.middle_linear = tf.keras.layers.Dense(H, input_dim=H)
        self.output_linear = tf.keras.layers.Dense(D_out, input_dim=H)

    def __call__(self, x):
        h_relu = tf.maximum(self.input_linear(x), 0)
        for _ in range(random.randint(0, 3)):
            h_relu = tf.maximum(self.middle_linear(h_relu), 0)
        y_pred = self.output_linear(h_relu)
        return y_pred

N, D_in, H, D_out = 64, 1000, 100, 10

x = np.random.randn(N, D_in)

model = DynamicNet(D_in, H, D_out)
model(x)
assert len(model.variables) > 0
```
(This particular example can be fixed by manually defining a `@property` variables which combines the variables members from each of the Dense layers into one list, but I think this partially defeats the point of using `tf.Module`).

**Other info / logs**
I'm not completely sure this is a bug/oversight, or if `tf.Module` was never intended to be compatible with keras layers. If that's the case, perhaps this is more appropriately categorized as a feature request. It seems like a natural thing to be able to do based on the the [tf.Module RFC](https://github.com/tensorflow/community/blob/master/rfcs/20190117-tf-module.md).

**Comment by zakizhou** [comment]
After `tf.Module` becomes the base class for `tf.keras.layers.Layer` this issue will be fixed, but I don't know when

**Comment by tomhennigan** [comment]
Hi all, the `tf.keras` team are working on making Module the base class for Layer. I think @qlzh727 is working on it this quarter.

As a temporary hack you can make a reference to the layer variables inside the module:

```python
class DenseModule(tf.Module):
  def __init__(self):
    super(DenseModule, self).__init__()
    self._layer = tf.keras.layers.Dense(64)

  def __call__(self, x):
    y = self._layer(x)
    # Keep a reference to layer variables so Module can find them.
    self._k_variables = self._layer.variables
    return y
```

**Comment by zakizhou** [comment]
@tomhennigan is there a timeline for it? will it get done in official 20. release?

**Comment by zakizhou** [comment]
Hi @tomhennigan, is there a timeline for it? will it get done in 2.0 release?

**Comment by tomhennigan** [comment]
I hope so, I worked with the Keras team last month to remove known blockers (e.g. e866995aff7) and I think it should be possible to do before 2.0 if we don't find more blockers.

**Comment by qlzh727** [comment]
Yes, the plan is to have keras.layer use module as base class, and we plan to have this feature in 2.0 release. I am actively working on it right now.

**Comment by qlzh727** [comment]
https://github.com/tensorflow/tensorflow/commit/23c8fd4ca3452865ac9ef1359f74cd0039908b59 should fix this issue.

**Comment by tomhennigan** [comment]
I've tested this at head and @qlzh727's fix does indeed make your example pass.
