### ISSUE TITLE
tf.train.BytesList should accept bytearray as an input type

### ISSUE THREAD

**Issue by aaron-jencks** [tensorflow/tensorflow#27047]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13
- Are you willing to contribute it (Yes/No): I don't know how to write a *.proto file, so no

**Describe the feature and the current behavior/state.**

If something is called a `BytesList`, then I should be allowed to pass in a `bytearray` to it
Currently I cannot.
For example:
```
import tensorflow as tf
img = bytearray([1, 2, 3, 4])
print(img)
feat = tf.train.Feature(bytes_list=tf.train.BytesList(value=[img]))
```

**Will this change the current api? How?**

It will make the tf.train.BytesList class more intuitive to use

**Who will benefit with this feature?**

Everyone trying to do image recognition

**Any Other info.**

**Comment by gshashank84** [comment]
The argument **value** accepts list of bytes as an argument, **not** bytearray in ``tf.train.BytesList``.

So here you can implement the above code -
```python
import tensorflow as tf
img = bytes([1,2,3,4])
print(img)
feat = tf.train.Feature(bytes_list=tf.train.BytesList(value=[img]))
```

**Comment by jvishnuvardhan** [comment]
@iggy12345 Please let us know whether it was resolved or not? If it was not resolved, please describe the feature with more details and context. Provide a use case where the feature is useful. Thanks!

**Comment by jvishnuvardhan** [comment]
I could reproduce the issue with TF1.12. and TF1.13.1. Thanks!

**Comment by sushreebarsa** [comment]
@aaron-jencks TensorFlow's tf.train.BytesList expects a list of bytes objects. You could achieve this by converting your bytearray to bytes before using it in the BytesList.

```

import tensorflow as tf

img = bytearray([1, 2, 3, 4])  # Create a bytearray
img_bytes = bytes(img)  # Convert bytearray to bytes

feat = tf.train.Feature(bytes_list=tf.train.BytesList(value=[img_bytes]))

```
Please have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/82cde18c784127c874e9a3f84158ba68/27047.ipynb).
Thank you!
