### ISSUE TITLE
tf.sparse: limited functionality

### ISSUE THREAD

**Issue by erikchwang** [tensorflow/tensorflow#27042]
1. `tf.sparse.sparse_dense_matmul` only support matrix of rank 2, why cannot it support higher ranks?
2. `tf.sparse.to_dense` cannot support back-propagation at least in and before TF 1.13
3. there is no element-wise multiplication for sparse tensors similar to tf.multiply
4. there is no matmul between two sparse tensors

**Comment by chwang85** [comment]
By the way, before deprecating old components, would you please complete the current functionality? It seems that TF is very good at deprecating widely used functions, but poor at improving its weak points

**Comment by mihaimaruseac** [comment]
Sparse tensors have been added recently and they're under constant work. The deprecation needed for TF2.0 is orthogonal to this, thus unrelated. Let's try to keep things on topic, please.

**Comment by chwang85** [comment]
See #6391
The issues about sparse tensors have been there for at least 2.5 years

**Comment by mihaimaruseac** [comment]
My bad, I was wrong

**Comment by wangwei-cmd** [comment]
use tf.reshape unroll the batch matix to rank 2 matrix, then use tf.sparse.sparse_dense_matmul
