### ISSUE TITLE
Is the task type "master" for distributed training deprecated?

### ISSUE THREAD

**Issue by sfujiwara** [tensorflow/tensorflow#27058]
Should task type "master" be immediately replaced with "chief"?
For example, `CollectiveAllReduceStrategy` only use "chief" (not "master") and "worker":
https://github.com/tensorflow/tensorflow/blob/36f817a9f3e7d2339cb53b91ddc508b3e25ab761/tensorflow/python/distribute/multi_worker_util.py#L159-L161

However, in some environment such as Google Cloud ML Engine, environment variable `TF_CONFIG` with "master" (not "chief"), "worker", and "ps".

Do you have any plan to keep compatibility?

**Comment by yuefengz** [comment]
Hi, we don't have plans to support "master" job right now. GCP also doesn't have a strong reason to use "master". So for now, we'll stick to "chief".

**Comment by sdll** [comment]
@yuefengz, this results in a bad experience with AI Platform, since `MultiWorkerMirroredStrategy` fails because it get confused about `master`. I would love to see this documented somewhere.
