### ISSUE TITLE
tf.Session and tf.ConfigProto do not work in the new TF2.0

### ISSUE THREAD

**Issue by joehoeller** [tensorflow/tensorflow#27053]
tf.Session and tf.ConfigProto do not work in the new TF2.0; what other options do I have?

with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as session:
        result = session.run(sum_operation)
        print(result)

**Comment by shaolinkhoa** [comment]
I suggest you read this [guide for tensorflow 2.0](https://www.tensorflow.org/alpha/guide/effective_tf2)

**Comment by joehoeller** [comment]
I patched it with tf.compat.v1 & it still fails.

**Comment by dynamicwebpaige** [comment]
`tf.ConfigProto` will be split and replaced into other functions ([ref](https://github.com/tensorflow/tensorflow/issues/25446#issuecomment-460516411)). If `tf.compat.v1.ConfigProto` is not working, however, that would be an issue.

```python
with tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(log_device_placement=True)) as session:
  result = session.run(sum_operation)
  print(result)
```

Can you try running the code snippet above?

**Comment by joehoeller** [comment]
@dynamicwebpaige thank you for that. I’ll try & follow up tomorrow and let you know. Thank you kindly.

**Comment by jvishnuvardhan** [comment]
@joehoeller Is this resolved? If it was resolved, please close the issue. Thanks!

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. But, please let me know if I'm mistaken.

**Comment by nekofugu** [comment]
neither gpu_options.allow_growth nor gpu_options.per_process_gpu_memory_fraction work.
GPU is allocated entirely regardless what values those options are set to.

**Comment by vmgustavo** [comment]
Trying to limit the number of cores being used by TF with ConfigProto doesn't work:

```
config = tf.compat.v1.ConfigProto(
        intra_op_parallelism_threads=1,
        inter_op_parallelism_threads=1
    )

session = tf.compat.v1.Session(config=config)
```

By changing the value of the arguments it does change the number of threads being executed but I couldn't get a single core execution.
