### ISSUE TITLE
~\Anaconda3\lib\imp.py......ImportError: DLL load failed: The specified module could not be found - Win10 Pro, Core I3 with AMD Radeon HD7500M Accelerator!

### ISSUE THREAD

**Issue by hemantjnypc** [tensorflow/tensorflow#27059]
Hi All,

Facing error -  _ImportError: DLL load failed: The specified module could not be found!_

Can anyone provide a 'working' env info for **AMD Radeon HD7500M** GPU alongside the following:

Win10 Pro, FU 1803
Core I3 3rd Gen (2370M), 4GB
CUDA ver.10.0.130
CUDNN ver 7.3.1 for 10.0_0
Anaconda 2018.12
Py 3.7.1
Tensorflow-gpu 1.13.1 - Installed using 'Conda' in an 'Anaconda prompt'!

Thanks!

**Comment by lostmsu** [comment]
@hemantjnypc tensorflow-gpu only works with NVidia cards. You need tensorflow-rocm.
Also, your GPU might be too old even for that.

**Comment by hemantjnypc** [comment]
Thanks! Shall check!

**Comment by ymodak** [comment]
Closing this issue since above explanation is correct. Feel free to reopen if facing difficulties any further difficulties. Thanks!
