### ISSUE TITLE
Deeplab TypeError: MonitoredTrainingSession() got an unexpected keyword argument 'summary_dir'

### ISSUE THREAD

**Issue by Telang8100** [tensorflow/tensorflow#27055]
When i am running train.py file for pascal voc dataset then fallowing error occures
file "train.py", line 500, in <module>
    tf.app.run()
  File "/home/suraj/anaconda2/envs/tensor/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 492, in main
    hooks=[stop_hook]) as sess:
TypeError: MonitoredTrainingSession() got an unexpected keyword argument 'summary_dir'

**Comment by blairhan** [comment]
What is your tf version? The keyword summary_dir is introduced in tf1.10 so if you version is below that you can solve the problem by upgrading tf version.

**Comment by shashvatshahi1998** [comment]
@Telang8100 before raising any issue you should always mention the environ on which you are working that is your :- 
1) Tensorflow version you are using
2) Your operating system
3) Piece of code causing issue

**Comment by ymodak** [comment]
Since this issue is related to [DeepLab](https://github.com/tensorflow/models/tree/master/research/deeplab#deeplab-deep-labelling-for-semantic-image-segmentation). Its better suited on tensorflow/models repo. Please post it on [tensorflow/models](https://github.com/tensorflow/models/issues/new). Thanks!

**Comment by Telang8100** [comment]
> What is your tf version? The keyword summary_dir is introduced in tf1.10 so if you version is below that you can solve the problem by upgrading tf version.

Thanks..
The issue is solved by upgrading tensorflow_gpu to 1.10
