### ISSUE TITLE
Unable to import tensorflow in Gpu after successful  installation

### ISSUE THREAD

**Issue by NaveenGandla** [tensorflow/tensorflow#27052]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Anaonda 
- TensorFlow version: 1.13.1
- Python version: 3.7
- Installed using virtualenv? pip? conda?: conda 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0
- GPU model and memory: nvidia getforce Gtx- 4GB 

**Describe the problem**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-fc42d8cf7cab> in <module>
----> 1 import tensorflow as tf
      2 from tensorflow.keras.callbacks import TensorBoard
      3 from tensorflow.keras import models,layers,optimizers
      4 from tensorflow.keras.models import Sequential
      5 from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Dropout, Flatten,BatchNormalization

~\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 from tensorflow._api.v1 import app

~\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     61 
     62 # Framework
---> 63 from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
     64 from tensorflow.python.framework.versions import *
     65 from tensorflow.python.framework import config

~\Anaconda3\lib\site-packages\tensorflow\python\framework\framework_lib.py in <module>
     23 # Classes used when building a Graph.
     24 from tensorflow.python.framework.device import DeviceSpec
---> 25 from tensorflow.python.framework.ops import Graph
     26 from tensorflow.python.framework.ops import Operation
     27 from tensorflow.python.framework.ops import Tensor

~\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in <module>
     42 from tensorflow.python.eager import tape
     43 from tensorflow.python.framework import c_api_util
---> 44 from tensorflow.python.framework import composite_tensor
     45 from tensorflow.python.framework import device as pydev
     46 from tensorflow.python.framework import dtypes

~\Anaconda3\lib\site-packages\tensorflow\python\framework\composite_tensor.py in <module>
     24 
     25 from tensorflow.python import pywrap_tensorflow
---> 26 from tensorflow.python.util import nest
     27 
     28 

~\Anaconda3\lib\site-packages\tensorflow\python\util\nest.py in <module>
    104 _is_mapping = _pywrap_tensorflow.IsMapping
    105 _is_attrs = _pywrap_tensorflow.IsAttrs
--> 106 _is_composite_tensor = _pywrap_tensorflow.IsCompositeTensor
    107 
    108 

AttributeError: module 'tensorflow.python.pywrap_tensorflow' has no attribute 'IsCompositeTensor'

**Any other info / logs**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-fc42d8cf7cab> in <module>
----> 1 import tensorflow as tf
      2 from tensorflow.keras.callbacks import TensorBoard
      3 from tensorflow.keras import models,layers,optimizers
      4 from tensorflow.keras.models import Sequential
      5 from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Dropout, Flatten,BatchNormalization

~\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 from tensorflow._api.v1 import app

~\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     61 
     62 # Framework
---> 63 from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
     64 from tensorflow.python.framework.versions import *
     65 from tensorflow.python.framework import config

~\Anaconda3\lib\site-packages\tensorflow\python\framework\framework_lib.py in <module>
     23 # Classes used when building a Graph.
     24 from tensorflow.python.framework.device import DeviceSpec
---> 25 from tensorflow.python.framework.ops import Graph
     26 from tensorflow.python.framework.ops import Operation
     27 from tensorflow.python.framework.ops import Tensor

~\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in <module>
     42 from tensorflow.python.eager import tape
     43 from tensorflow.python.framework import c_api_util
---> 44 from tensorflow.python.framework import composite_tensor
     45 from tensorflow.python.framework import device as pydev
     46 from tensorflow.python.framework import dtypes

~\Anaconda3\lib\site-packages\tensorflow\python\framework\composite_tensor.py in <module>
     24 
     25 from tensorflow.python import pywrap_tensorflow
---> 26 from tensorflow.python.util import nest
     27 
     28 

~\Anaconda3\lib\site-packages\tensorflow\python\util\nest.py in <module>
    104 _is_mapping = _pywrap_tensorflow.IsMapping
    105 _is_attrs = _pywrap_tensorflow.IsAttrs
--> 106 _is_composite_tensor = _pywrap_tensorflow.IsCompositeTensor
    107 
    108 

AttributeError: module 'tensorflow.python.pywrap_tensorflow' has no attribute 'IsCompositeTensor'

**Comment by ymodak** [comment]
You need to upgrade to [cuda 10.0 for using TF 1.13.1](https://www.tensorflow.org/install/gpu). Thanks!
