### ISSUE TITLE
Where is the api of PhasedLSTM in tensorflow 2.0.0 alpha? 

### ISSUE THREAD

**Issue by ChaoYue0307** [tensorflow/tensorflow#27060]
Just like the title suggests, where can I find the PhasedLSTM api, or there is still lacking of that? Thanks

**Comment by dynamicwebpaige** [comment]
`tf.contrib.rnn.PhasedLSTM` was deprecated, as outlined [here](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md#list-of-projects); however, it is in the process of being replaced with the new RNN API and [`tf.keras.layers.*`](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers). In the mean time, you should be able to recreate the `PhasedLSTM` functionality you need using the latter.

**Comment by ymodak** [comment]
Closing this issue since it was resolved. Feel free to reopen if have any additional questions. Thanks!

**Comment by newey01c** [comment]
I'd like to make use of Phased LSTMs for a project I'm working on; do you have any information about when this is likely to be integrated into the `tf,keras.layers` API?
