### ISSUE TITLE
Support for Kotlin Native?

### ISSUE THREAD

**Issue by SAGARSURI** [tensorflow/tensorflow#27064]
As I see there is a full support for swift language now and I believe it will surely replace python as the primary language for building deep learning models by software developers. Will I see the same for Kotlin Native?

**Comment by martinwicke** [comment]
We have no plans for this currently. However, there is a proposal for a SIG-JVM (
https://github.com/tensorflow/community/pull/86), that would likely be the right place to discuss Kotlin bindings/integration.
