### ISSUE TITLE
TensorFlow stopped working with custom ops built with GCC5

### ISSUE THREAD

**Issue by alsrgv** [tensorflow/tensorflow#27067]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly >= 20190321
- Python version: Python 2, Python 3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 5.4.0-6ubuntu1~16.04.11
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
TensorFlow fails with segmentation fault when using custom ops built with gcc5.  The segmentation fault originates from usage of `std::function` on the interface boundary, introduced in https://github.com/tensorflow/tensorflow/commit/41e7b3ca0abfd7e40a82ae38f96a9fbfeecb0ee5.

**Describe the expected behavior**
Custom ops built with gcc5 should continue working with TF built with gcc4.

**Code to reproduce the issue**
```
$ docker run -it tensorflow/tensorflow:nightly
# apt install -y mpich
# pip install horovod
# cat > test.py
import tensorflow as tf
import horovod.tensorflow as hvd
hvd.init()
sess = tf.Session()
sess.run(hvd.allreduce(tf.constant(1.0)))
^D
# python test.py
```

Outputs:
```
root@011ee61f092e:/# python test.py
2019-03-24 00:25:51.898835: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-24 00:25:51.910390: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-03-24 00:25:51.914924: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4269380 executing computations on platform Host. Devices:
2019-03-24 00:25:51.914981: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Segmentation fault (core dumped)
root@011ee61f092e:/#
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

The reason for this issue is the fact that definition of `std::function` has changed between gcc4 and gcc5.

gcc4:` _M_invoke(const _Any_data& __functor, _ArgTypes... __args)`
gcc5: `_M_invoke(const _Any_data& __functor, _ArgTypes&&... __args)`

While this change is ABI-compatible, it produced segfault in situation where gcc4-compiled code is calling function defined in gcc5-compiled plugin.

Short repro:

Prepare files:
```
$ cat > std_function_fw.h
#include <functional>
int call_me(std::function<int(int)> f);
^D
$ cat > std_function_fw.cc
#include "std_function_fw.h"
int call_me(std::function<int(int)> f) {
	return f(42);
}
^D
$ cat > std_function_client.cc
#include <iostream>
#include "std_function_fw.h"
int main(int argc, char **argv) {
	std::cout << call_me([](int val) { return val + 201808; }) << std::endl;
}
^D
```

Mount to gcc4 docker (e.g. `debian:jessie`):
```
# g++ --std=c++11 -fPIC std_function_fw.cc -shared -o libstd_function_fw.so
# g++ --std=c++11 -fPIC std_function_client.cc -o std_function_client -lstd_function_fw -L.
# LD_LIBRARY_PATH=. ./std_function_client
<will work>
```

Mount to gcc5 docker (e.g. `ubuntu:16.04`), keep `libstd_function_fw.so`:
```
# g++ --std=c++11 -fPIC std_function_client.cc -o std_function_client -lstd_function_fw -L.
# LD_LIBRARY_PATH=. ./std_function_client
<will crash>
```

Proposed solution is to revert https://github.com/tensorflow/tensorflow/commit/41e7b3ca0abfd7e40a82ae38f96a9fbfeecb0ee5 and keep using function pointers on the plugin interface boundary w/o using `std::function`.

**Comment by alsrgv** [comment]
cc @martinwicke, plugins built with gcc5 are broken

**Comment by martinwicke** [comment]
@gunan @sjamesr FYI

**Comment by gunan** [comment]
@yifeif 
I think for everything except python 3.7 pip packages, this is WAI.
We build using GCC 4.8. Sometime in April, hopefully our binaries should become more compatible. Until then, you need to build with gcc 4.8

**Comment by alsrgv** [comment]
@gunan, it used to work correctly until https://github.com/tensorflow/tensorflow/commit/41e7b3ca0abfd7e40a82ae38f96a9fbfeecb0ee

What is the proposed change that will improve this in April?

**Comment by gunan** [comment]
Interesting, I would have expected to see ABI issues.
Ubuntu 14.04 is going EOL, so we have to upgrade our build environment. We are exploring how we can make things backwards compatible with a new build environment.

**Comment by alsrgv** [comment]
Back in the day we've added `tf.sysconfig.get_compile_flags()` to get around ABI incompatibility, and gcc4/gcc5 interop was working fine until three days ago.

Since Horovod and many other custom ops are compiled on the user machine, and most users have gcc5+, its not a good user experience to ask them to install gcc4.

Can we revert https://github.com/tensorflow/tensorflow/commit/41e7b3ca0abfd7e40a82ae38f96a9fbfeecb0ee until you upgrade the build system?

**Comment by gunan** [comment]
We can consider reverting, but if you use `std::string` you just wont be able to compile an add on to TF using GCC 5 or more recent. Our custom OP guide provides a docker container which guarantees that if you use that to compile your add ons, the compiled objects will work.

Considering @sjamesr's work is to get us to a fully ABI compatible state, I will check with him before rolling back, to see how important this change in his greater tassk.

**Comment by alsrgv** [comment]
`std::string` actually works fine with `-D_GLIBCXX_USE_CXX11_ABI=0`, which is returned by `tf.sysconfig.get_compile_flags()` if TF is compiled with gcc4.

I’m only aware of the issue with `std::function` which is not fixed by _GLIBCXX_USE_CXX11_ABI.

**Comment by gunan** [comment]
I understand your frustration, however this is just how C++ ABI is. There are no standards governing how C++ ABI is generated, so an arbitrary change may break you at any given time. That is why we are right now pushing for https://github.com/tensorflow/community/pull/77. @sjamesr is working on creating a C ABI we can use that can remove  all ABI restrictions. Unfortunately, until that is ready, for custom ops all we can guarantee is what is documented in our [custom-op guide](https://github.com/tensorflow/custom-op)

I think we have a prototype of a kernel that uses a C API ready, and we have a few changes preparing in the pipeline to help with the situation. But until then I unfortunately have to ask you to use our docker container to build any C++ add-ons to TF.

**Comment by alsrgv** [comment]
C API sounds great!  I'd love not to have to worry about C++ ABI compatibility anymore.  Happy to be one of the early adopters.

Is there any update on whether reverting https://github.com/tensorflow/tensorflow/commit/41e7b3ca0abfd7e40a82ae38f96a9fbfeecb0ee would impede the progress of that work?  While I understand that C++ ABI has little theoretical guarantees across compiler versions, in practice this compatibility has been working fine for the last two years for a vast majority of users.  `_GLIBCXX_USE_CXX11_ABI` does a pretty good job with allowing backward compatibility, and `std::function` is one of the outliers, rather than a common pattern.

Asking users to compile plugins like Horovod in a custom-op container is a pretty bad user experience because Horovod requires environment such as CUDA, NCCL, and MPI to have the same version as what'd be used on the host.

Because of that, it'd be great if we could keep using existing C++ API with the revert until we can cut over to C API.

**Comment by gunan** [comment]
Unfortunately, All I can offer is creating a docker container based on our custom op containers to provide an environment to build.
We have created these containers, because such issues has been hitting our users continuously. So for your simple example, you are only now hitting the issue. However, we have seen with tensorflow/compression or tensorflow/lingvo that withour the referenced change, they are hitting similar ABI issues.

**Comment by alsrgv** [comment]
OK, fair enough.  What's the timeline for C API and/or moving your build system to gcc5+?

**Comment by gunan** [comment]
For moving TF builds to gcc5+, we are  aiming end of april, the latest.
For C API, I would defer to @sjamesr

**Comment by alsrgv** [comment]
Got it, TF 1.14.0 still planned on GCC 4.8 then?

**Comment by gunan** [comment]
90% yes. If by some miracle, we manage to pull it off and migrate builds would it be difficult to migrate your workflows?

BTW, the toolchains we are testing right now are centos6 + devtoolset7, to achieve manylinux 2010 compatibility.

**Comment by alsrgv** [comment]
I expect it to be easy, could you share a WIP wheel built with centos6 + devtoolset7 file for me to try out early?

**Comment by r4nt** [comment]
I have a centos7+devtoolset7 image, and am working on a centos6 one - centos6 is unfortunately hard to target from debian, so I have to jump through some hoops.

**Comment by njzjz** [comment]
Is devtoolset7 gcc-7? I tried to compile custom ops with gcc-7, but when loading it I catch a `undefined symbol` error.
```
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/deepmd/_prod_force_grad.py", line 15, in <module>
    op_grads_module = tf.load_op_library(module_file)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/deepmd/libop_grads.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by njzjz** [comment]
> Is devtoolset7 gcc-7? I tried to compile custom ops with gcc-7, but when loading it I catch a `undefined symbol` error in both TF 2.0 and TF 1.15-rc2.
> 
> ```
>   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/deepmd/_prod_force_grad.py", line 15, in <module>
>     op_grads_module = tf.load_op_library(module_file)
>   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
>     lib_handle = py_tf.TF_LoadLibrary(library_filename)
> tensorflow.python.framework.errors_impl.NotFoundError: /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/deepmd/libop_grads.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
> ```

Found the reason: I need to add `-D_GLIBCXX_USE_CXX11_ABI=0`.
