### ISSUE TITLE
How Can I set input shape of Subclass Model ?

### ISSUE THREAD

**Issue by RRoundTable** [tensorflow/tensorflow#27063]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tensorflow 1.13
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
in subclass model,

 def call(self,x):

When I call my mode(subclass) at first time, I can't check batch_size(None).

If I want to concatenate multiple layers, the model check input shape.

but it can't

How can I set input shape of subclass model?

    def call(self,x):
        """ Forward """
        # [x,y]=Lambda(lambda x:[x[0],x[1]], output_shape=[-1,self.opt.ncond,self.opt.nc,self.opt.height,self.opt.width])(x)
        inputs = Reshape((self.opt.ncond * self.opt.nc, self.opt.height, self.opt.width))(x)  # batch_size, shape
        target = Reshape((self.opt.npred * self.opt.nc, self.opt.height, self.opt.width))(self.y)
        g_pred_v = K.variable(self.deterministic(inputs), name="g_pred_v")
        r=K.abs(g_pred_v-target) # residual
        z=self.phi_network_conv(r)
        s = self.deterministic.get_layer()[0](inputs)
        h=concatenate([s,z], axis=1) # concatenate
        # shape=K.int_shape(s)
        # h=Reshape((shape[1]*2, shape[2],shape[3]))(h)
        pred_f = self.f_network_decoder(h)
        return pred_f

    def get_target(self,y):
        # input layer
        self.y=y

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by RRoundTable** [comment]
thanks!
