### ISSUE TITLE
Relationship between batch size and CUDA load in deep learning task

### ISSUE THREAD

**Issue by catskillsresearch** [tensorflow/tensorflow#27062]
I am learning about machine translation by running this TensorFlow example on my GPU in my home PC: https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb

My GPU has 6GB of VRAM. I have to reduce the batch size to get the example code not to run out of memory on the GPU. With trial and error, I find a batch size (minimum is 1) where the code runs and uses the most memory. I notice that, as I reduce the batch size, the CUDA core load as reported by Windows Task Manager GPU view goes down.

The application described in the link above creates a complex TensorFlow network. I don't know whether Tensorflow creates one copy of the network or multiple copies to load the GPU.

If it can create multiple copies, is there a TensorFlow switch for that? I don't think memory speed should be a bottleneck in feeding the GPU. That is, I should be able to optimize between batch size or number of jobs resident in the GPU, and number of compute networks in the GPU.

Is there an easy way in TensorFlow to assess the size in CUDA cores of a compute network?

Question: What are the factors I can use to optimize CUDA load in a small GPU with a large deep learning task?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by catskillsresearch** [comment]
I did that.  Here are some unanswered threads:
- https://stackoverflow.com/questions/55313399/relationship-between-batch-size-and-cuda-load-in-deep-learning-task
- https://datascience.stackexchange.com/questions/47918/how-can-i-increase-cuda-load-on-a-tensorflow-deep-learning-task-after-reducing-b?noredirect=1#comment54931_47918

It's safe to say that
- You can count the number of people in the world on one or two hands that truly understand how Tensorflow consumes memory and cores in the GPU
- I will be getting a lot more familiar with this: https://github.com/tensorflow/profiler-ui and this; https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/profiler
- I will be getting more familiar with nvidia-smi and re-acquainting myself with NVidia Parallel NSight if I can run that on Python.exe and get anything out of it.

Memory and core usage is an area that is truly opaque and confusing in TensorFlow, and there is no good venue to learn about it, I just have to grind it out.
