### ISSUE TITLE
Celery hangs with Tensorflow shared model

### ISSUE THREAD

**Issue by Narzhan** [tensorflow/tensorflow#27074]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 on Docker (18.03)
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6
- CUDA/cuDNN version: No gpu
- GPU model and memory: No gpu
- Celery 4.2.2, Keras 2.2.4

**Scenario**
I'm running a Celery worker which handless ml requests for prediction using LSTM NN. I'm loading the model in a main worker which passes it to the worker process as reference so that the model is not loaded all the time in a concurrent set-up. 

**Describe the current behavior**
When the request comes the execution hangs indefinitely when it hits the access to the passed model reference.  I've searched for a solution and found that the sessions cannot be shared across process which is the cause of the hang. I've tried several solutions which are mentioned lower. However only changing back end to Theano solved the issue. Is there any other solution for this issue or I have to keep loading model in worker who uses it for prediction? Or I am doing something wrong?  

**Describe the expected behavior**
I would like the set-up to work with Tensorflow as is with Theano that is to share a reference with workers to save memory. 

**Code to reproduce the issue**
```
main.py

from keras.models import load_model
from celery import Celery, states
from celery import Task

class DomainAnalyzer(Task):
    ignore_result = True
    def __init__(self):
        self.model = load_model("lstm_model.h5")

    def run(self, data):
        try:
            preprocessor = Preprocessor(data, self.model)
            data = preprocessor.predict_data()
            return data 
        except Exception as e:
            print(e)

app = Celery('worker', broker="broker")
app.register_task(DomainAnalyzer())

if __name__ == '__main__':
    app.start()
```
```
worker.py

class Preprocessor:

    def __init__(self, data: str, model):
        self.data= data
        self.model = model

    def data_analysis(self):
        return self.model.predict(self.data)
```

### Tried solution 1.
I've specified the multiprocessing start method. 
`multiprocessing.set_start_method('spawn', force=True)`

### Tried solution 2.
Passing graph object in worker
```
import tensorflow as tf
self.model = load_model("lstm_model.h5")
self.model._make_predict_function()
self.graph = tf.get_default_graph()
preprocessor = Preprocessor(data, self.model, self.graph)
```

In worker:
```
def data_analysis(self):
     with self.graph.as_default():
         return self.model.predict(self.data)

```
### Tried solution 3. (currently only one which works)
Use Theano :(

**Comment by karmel** [comment]
Can you clarify what your high-level goal is? To run a server for inference? If so, we would recommend you check out TensorFlow Serving: https://www.tensorflow.org/tfx/guide/serving . We do not currently support Celery or have existing examples, so it's hard to help you debug here.

**Comment by Narzhan** [comment]
Yes, I'm building something of that sort, that is an extensible rest API service which provides some analysis. I've checked TensorFlow Serving during analysis but I'm not sure about the possibility of tweaking and further extensibility. Are you planning on making Tensorflow Celery friendly or rather multiprocess friendlier? Do you know any other workarounds for the general scenario (parallel model use) which could solve the issue apart from those mentioned?

**Comment by karmel** [comment]
There are no plans for integrating with Celery currently AFAIK. You could load multiple copies of the model into multiple processes, but other than that, I would encourage the use of TF Serving, which is what we use internally for this.

**Comment by Narzhan** [comment]
Ok, I'll try that

**Comment by gaoyibin0001** [comment]
celery workers serving with billiard, not multiprocessing
