### ISSUE TITLE
Typo in doc: `tf.keras.losses.CategoricalCrossentropy`

### ISSUE THREAD

**Issue by XiaomoWu** [tensorflow/tensorflow#27070]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.13
- Doc Link: [tf.keras.losses.CategoricalCrossentropy](https://www.tensorflow.org/api_docs/python/tf/keras/losses/CategoricalCrossentropy#class_categoricalcrossentropy)

**Describe the documentation issue**
In the example code 

```
loss = cce(
    [[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]],
    [[.9, .05, .05], [.5, .89, .6], [.05, .01, .94]])
```

I think the second array in the second line should be `[.05, .89, .06]` instead of `[.5, .89, .6]`, as they're supposed to be summed to one.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by dynamicwebpaige** [comment]
Thank you for noticing this and submitting the PR! Approving now. 🙂

**Comment by yashk2810** [comment]
Thank you so much. Fixed in nightly: https://www.tensorflow.org/api_docs/python/tf/keras/losses/CategoricalCrossentropy?version=nightly#class_categoricalcrossentropy
