### ISSUE TITLE
tensorflow 1.13.1 on linux on python 3.7 (not osx) uses -D_GLIBCXX_USE_CXX11_ABI=1 -- this behavior is undocumented and/or unspecified

### ISSUE THREAD

**Issue by cosmicexplorer** [tensorflow/tensorflow#27078]
### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Linux Ubuntu 18.04.2`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: *N/A*
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version: `1.13.1`
- Python version: `3.7`
- Installed using virtualenv? pip? conda?: **pip** -- see excerpt in pantsbuild/pants#7424
- Bazel version (if compiling from source): *N/A*
- GCC/Compiler version (if compiling from source): `7.3.0`
- CUDA/cuDNN version: *N/A*
- GPU model and memory: *N/A*

### Problem
- `tensorflow==1.13.1`, specifically only on `Linux` for python `3.7`, uses `-D_GLIBCXX_USE_CXX11_ABI=1`, which contradicts the documentation at https://www.tensorflow.org/guide/extend/op#build_the_op_library, which specifically says that `-D_GLIBCXX_USE_CXX11_ABI=0` is used.
  - This caused an opaque compile error when building a custom operator in C++ in pants (see pantsbuild/pants#7417).
  - **Is this ABI change intentional?**
- **This does not affect any user who is building from source nor any user/tool which relies on `tensorflow.sysconfig.get_compile_flags()` to get compile flags.**
- *(tangential)* `self.test_session()` is deprecated, but is also used in the documentation at https://www.tensorflow.org/guide/extend/op.

### Exact commands / steps
pantsbuild/pants#7424 has command line logs from linux and osx to show that `tensorflow==1.13.1` on python 3.7 uses `-D_GLIBCXX_USE_CXX11_ABI=1` on linux, but not osx.

### Background
In pants, we are imitating the instructions in the tutorial, but we are not using the `tf.sysconfig` API right now (see pantsbuild/pants#7046). We had set `-D_GLIBCXX_USE_CXX11_ABI=0` for all tensorflow compiles, and found a failure when trying to run testing for our tensorflow example custom op project when trying to set up a python 3.7 Linux CI shard. This is not blocking us -- we have a well-functioning workaround in pantsbuild/pants#7424, but we would like to know if this change is intentional and whether we should expect new tensorflow releases to also use the newer C++ ABI.

**Comment by cosmicexplorer** [comment]
Noting that https://github.com/tensorflow/tensorflow/issues/26826#issuecomment-474680451 is likely the cause of this. Setting `-D_GLIBCXX_USE_CXX11_ABI=0` in the ubuntu builds for the binary `1.13.1` artifact on python 3.7 seems like it would work to resolve this, if it is in fact unintentional. To be clear about severity, this only affects consumers of the tensorflow binary wheel which do not use `tensorflow.sysconfig.get_compile_flags()`, which is likely to be a small number of users.

**Comment by gunan** [comment]
@yifeif Is this documented in github.com/tensorflow/custom-op ?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
