### ISSUE TITLE
`tk.layers.CuDNNLSTM` is not compatible with `tk.layers.StackedRNNCells`

### ISSUE THREAD

**Issue by xlnwel** [tensorflow/tensorflow#27087]
I follow the official document and write the following code to create a stack of RNN cells using Tensorflow 1.13 on GPU

```python
import tensorflow.keras as tk

lstm = [tk.layers.CuDNNLSTM(128) for _ in range(2)]
cells = tk.layers.StackedRNNCells(lstm)
```
However, I receive the error message:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-30-1b47a86eb8ab> in <module>
>       2 # x = tf.placeholder(tf.float32, (4, 100, 128))
>       3 lstm = [tk.layers.CuDNNLSTM(128) for _ in range(2)]
> ----> 4 lstm = tk.layers.StackedRNNCells(lstm)
> 
> ~/anaconda3/envs/gym/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py in __init__(self, cells, **kwargs)
>      74         raise ValueError('All cells must have a '
>      75                          '`state_size` attribute. '
> ---> 76                          'received cells:', cells)
>      77     self.cells = cells
>      78     # reverse_state_order determines whether the state size will be in a reverse
> 
> ValueError: ('All cells must have a `state_size` attribute. received cells:', [<tensorflow.python.keras.layers.cudnn_recurrent.CuDNNLSTM object at 0x13aa1c940>])

Is this a bug, or do I do it wrong?

**Comment by gshashank84** [comment]
One of the reasons is that the ```tf.keras.layers.CuDNNLSTM``` has been removed in 2.0 from ```tf.keras```. I suggest you must use ```tf.keras.layers.MultiRNNCell``` for now. But keep in mind that both **CuDNNLSTM** and **MultiRNNCell** has been removed in future versions, thats why the **StackedRNNCell** does not support it.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by xlnwel** [comment]
Sorry for responding late. I've posted it to [Stackoverflow](https://stackoverflow.com/questions/55324307/how-to-implement-a-stacked-rnns-in-tensorflow), and someone told me it is a bug and suggested me to ask it here...Which class is recommended to use then if I want to get the optimized performance on GPU?

**Comment by xlnwel** [comment]
I've followed the [TF2.0 document](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/LSTM), and wrote the code
```python
tf.reset_default_graph()
x = tf.placeholder(tf.float32, [None, 5, 10])
lstm = tk.layers.LSTM(10, return_sequences=True, return_state=True)
# lstm = tk.layers.StackedRNNCells([lstm])
initial_state = lstm.get_initial_state(x)
y, h, c = lstm(x, initial_state=initial_state)
```
If I uncomment line4, the same error occurs. I've also tried using `LSTMCell`, but it cannot return sequences. And it somehow requires a 2-D tensor as input? I'd be appreciated for any helps

**Comment by qlzh727** [comment]
I think this is working as intended. Either StackedRNNCells or StackedRNNCells only works with Cell, not layer. The difference between the cell and layer in RNN is that cell will only process one time step within the whole sequence, whereas the layer will process the whole sequence. You can treat RNN layer as:
```
for t in whole_time_steps:
  output_t, state_t = cell(input_t, state_t-1)
```

If you want to stack 2 LSTM layers to together with cudnn in 1.x, you can do:

```
l1 = tf.layers.CuDNNLSTM(128, return_sequence=True)
l2 = tf.layers.CuDNNLSTM(128)
l1_output = l1(input)
l2_oupput = l2(l1_output) 
```

In tf 2.x, we unify the cudnn and normal implementation together, you can just change the example above with tf.layers.LSTM(128, return_sequence=True), which will use the cudnn impl if available.
