### ISSUE TITLE
Build Failure: Cannot link XLA allocator with CUDA 10.1 and GCC 7.2.1

### ISSUE THREAD

**Issue by kgizdov** [tensorflow/tensorflow#27083]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ArchLInux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?: system install to `/usr`
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source): GCC 7.2.1
- CUDA/cuDNN version: 10.1
- GPU model and memory: n/a

**Describe the problem**
Compiling Tensorflow results in failing the final linking step when linking the XLA GPU fusion instruction allocators.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```bash
export PYTHON_BIN_PATH=/usr/bin/python
export USE_DEFAULT_PYTHON_LIB_PATH=1
export TF_NEED_JEMALLOC=1
export TF_NEED_KAFKA=0
export TF_NEED_OPENCL_SYCL=0
export TF_NEED_AWS=0
export TF_NEED_GCP=0
export TF_NEED_HDFS=0
export TF_NEED_S3=0
export TF_ENABLE_XLA=1
export TF_NEED_GDR=0
export TF_NEED_VERBS=0
export TF_NEED_OPENCL=0
export TF_NEED_MPI=0
export TF_NEED_TENSORRT=0
export TF_NEED_NGRAPH=0
export TF_NEED_IGNITE=0
export TF_NEED_ROCM=0
export TF_SET_ANDROID_WORKSPACE=0
export TF_DOWNLOAD_CLANG=0
export TF_NCCL_VERSION=2.3
export NCCL_INSTALL_PATH=/usr
export CC_OPT_FLAGS="-march=x86-64"
export TF_NEED_CUDA=1
export GCC_HOST_COMPILER_PATH=/usr/bin/gcc-7
export TF_CUDA_CLANG=0
export CUDA_TOOLKIT_PATH=/opt/cuda
export TF_CUDA_VERSION=$($CUDA_TOOLKIT_PATH/bin/nvcc --version | sed -n 's/^.*release \(.*\),.*/\1/p')
export CUDNN_INSTALL_PATH=/usr/lib
export TF_CUDNN_VERSION=$(sed -n 's/^#define CUDNN_MAJOR\s*\(.*\).*/\1/p' /usr/include/cudnn.h)
export TF_CUDA_COMPUTE_CAPABILITIES=3.5,3.7,5.0,5.2,5.3,6.0,6.1,6.2,7.0,7.2,7.5
./configure
bazel \
    build --config=opt \
      //tensorflow:libtensorflow.so \
      //tensorflow:libtensorflow_cc.so \
      //tensorflow:install_headers \
      //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package ${srcdir}/tmp
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```bash
ERROR: /build/tensorflow/src/tensorflow-1.13.1-cuda/tensorflow/BUILD:463:1: Linking of rule '//tensorflow:libtensorflow.so' failed (Exit 1)
/usr/bin/ld: bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/gpu/libinstruction_fusion.pic.a(instruction_fusion.pic.o): in function `xla::gpu::GpuInstructionFusion::FusionWouldBeTooLarge(xla::HloInstruction const*, xla::HloInstruction const*)':
instruction_fusion.cc:(.text._ZN3xla3gpu20GpuInstructionFusion21FusionWouldBeTooLargeEPKNS_14HloInstructionES4_+0x7c): undefined reference to `std::allocator<xla::HloInstruction const*>::allocator()'
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 4415.531s, Critical Path: 2250.52s
INFO: 15052 processes: 15052 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by dynamicwebpaige** [comment]
Potentially related: https://github.com/tensorflow/tensorflow/pull/26230

**Comment by gunan** [comment]
Redirecting to Tatiana for triage.

**Comment by sanjoy** [comment]
Hi Konstantin,

Are you still interested in getting this fixed?  If yes, it might be best if you send a PR (and assign it to me for review) since that way I don't have to figure out how to reproduce your build environment.

**Comment by kgizdov** [comment]
Newer versions solved it, so I don't particularly need a specific solution to this. Thanks.
