### ISSUE TITLE
Export user_data from TfLiteContext

### ISSUE THREAD

**Issue by mattn** [tensorflow/tensorflow#27093]
**System information**
- TensorFlow version (you are using): 13fe6ef76e9f882584fe63a2b7f292266dedf847
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Thinking binding of Python or Java, no way to map TfLiteContext to Python/Java objcet. Current implementation of TfLiteRegistration does not have user_data to store object that can be used for mapping Python or Java. So we can't implement custom op with Python or Java.

```cpp
  static TfLiteRegistration registration = {
      .init = nullptr,
      .free = nullptr,
      .prepare =
          [](TfLiteContext* context, TfLiteNode* node) {
              // call Python/Java
             //PyObject* obj = context->user_data;
          }
   };
```
If TfLiteContext have user_data (typed void*), we can call Python or Java in the function (init/free/prepare/...).

**Will this change the current api? How?**

So I suggest to add field user_data into TfLiteContext and TfLiteRegistration.

```cpp
registration.user_data = GetMyUserData();
```
```cpp
MyUserData* my_user_data = (MyUserData*)context->user_data;
```

**Who will benefit with this feature?**

The authors of binding for Python/Java or [Me](https://github.com/mattn/go-tflite)

**Any Other info.**

However, we need more APIs to implement custom op which is implemened with C.

ex: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/models/smartreply/ops

**Comment by mattn** [comment]
This is a patch I expected.
```diff
diff --git a/tensorflow/lite/c/c_api_internal.h b/tensorflow/lite/c/c_api_internal.h
index 4cffd2927d..12f08328dd 100644
--- a/tensorflow/lite/c/c_api_internal.h
+++ b/tensorflow/lite/c/c_api_internal.h
@@ -468,6 +468,10 @@ typedef struct TfLiteContext {
 
   // Pointer to the op-level profiler, if set; nullptr otherwise.
   void* profiler;
+
+  // Pointer to the `user_data`. This is used to be passed extra data from
+  // TfLiteRegistration.
+  void* user_data;
 } TfLiteContext;
 
 typedef struct _TfLiteRegistration {
@@ -527,6 +531,10 @@ typedef struct _TfLiteRegistration {
   // Note: It is the responsibility of the registration binder to set this
   // properly.
   int version;
+
+  // Pointer to the `user_data`. This is used to pass extra data to
+  // TfLiteContext.
+  void* user_data;
 } TfLiteRegistration;
 
 // The flags used in `TfLiteDelegate`. Note that this is a bitmask, so the
diff --git a/tensorflow/lite/core/subgraph.h b/tensorflow/lite/core/subgraph.h
index e336140c12..79dc822c9e 100644
--- a/tensorflow/lite/core/subgraph.h
+++ b/tensorflow/lite/core/subgraph.h
@@ -304,6 +304,7 @@ class Subgraph {
   void* OpInit(const TfLiteRegistration& op_reg, const char* buffer,
                size_t length) {
     if (op_reg.init == nullptr) return nullptr;
+    context_->user_data = op_reg.user_data;
     return op_reg.init(context_, buffer, length);
   }
 
@@ -311,6 +312,7 @@ class Subgraph {
   void OpFree(const TfLiteRegistration& op_reg, void* buffer) {
     if (op_reg.free == nullptr) return;
     if (buffer) {
+      context_->user_data = op_reg.user_data;
       op_reg.free(context_, buffer);
     }
   }
@@ -318,12 +320,14 @@ class Subgraph {
   // Prepare the given 'node' for execution.
   TfLiteStatus OpPrepare(const TfLiteRegistration& op_reg, TfLiteNode* node) {
     if (op_reg.prepare == nullptr) return kTfLiteOk;
+    context_->user_data = op_reg.user_data;
     return op_reg.prepare(context_, node);
   }
 
   // Invoke the operator represented by 'node'.
   TfLiteStatus OpInvoke(const TfLiteRegistration& op_reg, TfLiteNode* node) {
     if (op_reg.invoke == nullptr) return kTfLiteError;
+    context_->user_data = op_reg.user_data;
     return op_reg.invoke(context_, node);
   }
 
```

**Comment by aselle** [comment]
Thanks for the patch, @miaout17, could you ptal?

**Comment by tilakrayal** [comment]
@mattn,
Could you please confirm whether the mentioned above changes are reflected in the **c_api_internal.h** file.


```
  std::function<const TfLiteRegistration_V3*(void* user_data, const char* op,
                                             int version)>
```

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/c_api_internal.h#L74
Thank you!

**Comment by mattn** [comment]
C API is not available?

**Comment by tilakrayal** [comment]
@mattn,
Could you please check the below **C_API** file  where the **TfLiteRegistration** was available. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/core/c/c_api.h#L221

Could you please check and let us know if this helps. Thank you!

**Comment by mattn** [comment]
Sorry about delay. Recently, I confirmed this working good. Thank you.
