### ISSUE TITLE
Build Tensorflow r1.13 with verbs and gdr report rdma error

### ISSUE THREAD

**Issue by as754770178** [tensorflow/tensorflow#27095]
cmd : ` bazel build --config=opt --config=cuda --config=gdr --config=verbs --distdir=/home/bazel_package //tensorflow/tools/pip_package:build_pip_package`
Due to network problems, I downloaded the dependencies in advance.
And I have install  the SW stack (libibverbs, etc..)
```
	sudo yum install jemalloc
	sudo yum install jemalloc-devel
	sudo yum install libibverbs
	sudo yum install libibverbs-devel
```

Error info:
```
bazel-out/k8-opt/genfiles/tensorflow/core/protobuf/config.pb_text.cc:882:9: note: 'map_value' was declared here
   int32 map_value;
         ^
ERROR: /home/zgz/submit_code/tensorflow/tensorflow/contrib/verbs/BUILD:105:1: C++ compilation of rule '//tensorflow/contrib/verbs:rdma_mgr' failed (Exit 1)
In file included from tensorflow/contrib/verbs/rdma_mgr.cc:18:0:
./tensorflow/contrib/verbs/rdma_mgr.h: In static member function 'static void tensorflow::RdmaMgr::RegMemVisitors()':
./tensorflow/contrib/verbs/rdma_mgr.h:50:16: error: invalid use of member 'tensorflow::RdmaMgr::rdma_adapter_' in static member function
   RdmaAdapter* rdma_adapter_;
                ^
tensorflow/contrib/verbs/rdma_mgr.cc:282:40: error: from this location
     int32_t bus_id = TryToReadNumaNode(rdma_adapter_->context_->device) + 1;
                                        ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 80.943s, Critical Path: 51.17s
INFO: 2025 processes: 2025 local.
FAILED: Build did NOT complete successfully
```

please tell me how to fix this.

**Comment by byronyi** [comment]
Sorry that the verbs fix #24250 did not make into r1.13. Let us know if you met any other problems with that fix.

**Comment by as754770178** [comment]
I only saw you discussing how to solve in  #24250 .
I want to know what should I do? Can I change the code according to `https://patch-diff.githubusercontent.com/raw/tensorflow/tensorflow/pull/24250.patch` what you mentioned in #22455 . I hurry to compile tf1.13 with GDR and Verbs.

**Comment by byronyi** [comment]
Yes, could you try that? 

```
curl https://patch-diff.githubusercontent.com/raw/tensorflow/tensorflow/pull/24250.patch | git apply
```

**Comment by lxl910915** [comment]
asd

**Comment by as754770178** [comment]
OK, I try it Now.

**Comment by as754770178** [comment]
I fix the issue, but only modify  `rdma_mgr.cc` and `verbs_server_lib.cc` . Do I still need to modify other files?

**Comment by byronyi** [comment]
I don’t know. Did you get it working?

**Comment by as754770178** [comment]
Now I compile sucessfully. I find many diff in 24250.patch, but when I exec `24250.patch`, only modify `rdma_mgr.cc` and `verbs_server_lib.cc` . 

Due to network problem, my server can not exec `curl https://patch-diff.githubusercontent.com/raw/tensorflow/tensorflow/pull/24250.patch | git apply`. So I manually  create a file `24250.patch` .  Do I still need to manually modify other files that show in 24250.patch?

现在我已经编译成功了。
由于网络问题，我的服务器节点无法访问`https://patch-diff.githubusercontent.com/raw/tensorflow/tensorflow/pull/24250.patch`, 所以我创建文件`24250.patch`并拷贝网站上内容，上传到服务器。 在服务器执行`git apply 24250.patch`，然后执行`git diff`，发现只修改了 `rdma_mgr.cc` 和 `verbs_server_lib.cc`。
但在`https://patch-diff.githubusercontent.com/raw/tensorflow/tensorflow/pull/24250.patch`上显示修改了很多文件，我现在是否需要将其他文件手动修改？

**Comment by byronyi** [comment]
If it’s working it’s working. 

Let us know when you find that it’s not :)
