### ISSUE TITLE
Micro speech tutorial - wav_to_features script fails with "ImportError: No module named enum"

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tensorflow#27109]
I'm following the instructions in the [micro_speech tutorial](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro/examples/micro_speech#creating-your-own-model)

I'm on OSX 10.14.2

When I get to the step to generate the test data files, and run the command:

```bash
bazel run tensorflow/examples/speech_commands:wav_to_features -- \
--input_wav=${HOME}/speech_commands_test_set_v0.02/yes/f2e59fea_nohash_1.wav \
--output_c_file=yes_features_data.cc \
--window_stride=20 --preprocess=average --quantize=1
```

I eventually get to an error "ImportError: No module named enum":

> ERROR: /Users/danoved/Source/thesis/speech-rec/tensorflow/tensorflow/BUILD:713:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
> Traceback (most recent call last):
>   File "/private/var/tmp/_bazel_danoved/be5220cf895eff30f56ec50496f58755/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
>     from tensorflow.python.tools.api.generator import doc_srcs
>   File "/private/var/tmp/_bazel_danoved/be5220cf895eff30f56ec50496f58755/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 63, in <module>
>     from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
>   File "/private/var/tmp/_bazel_danoved/be5220cf895eff30f56ec50496f58755/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 52, in <module>
>     from tensorflow.python.framework.importer import import_graph_def
>   File "/private/var/tmp/_bazel_danoved/be5220cf895eff30f56ec50496f58755/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 28, in <module>
>     from tensorflow.python.framework import function
>   File "/private/var/tmp/_bazel_danoved/be5220cf895eff30f56ec50496f58755/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 37, in <module>
>     from tensorflow.python.ops import resource_variable_ops
>   File "/private/var/tmp/_bazel_danoved/be5220cf895eff30f56ec50496f58755/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/ops/resource_variable_ops.py", line 41, in <module>
>     from tensorflow.python.ops import variables
>   File "/private/var/tmp/_bazel_danoved/be5220cf895eff30f56ec50496f58755/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/ops/variables.py", line 20, in <module>
>     import enum  # pylint: disable=g-bad-import-order
> ImportError: No module named enum
> Target //tensorflow/examples/speech_commands:wav_to_features failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 3774.946s, Critical Path: 286.02s
> INFO: 10376 processes: 10376 local.
> FAILED: Build did NOT complete successfully
> FAILED: Build did NOT complete successfully

**Comment by gshashank84** [comment]
It seems to me that you have not installed **enum** Module.

You can easily do that by ```pip install enum```

**Comment by ymodak** [comment]
> It seems to me that you have not installed **enum** Module.
> 
> You can easily do that by `pip install enum`

Did this help resolve your issue?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by mrgloom** [comment]
```
sudo pip install enum
WARNING: The directory '/Users/my_user/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/my_user/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting enum
  Downloading https://files.pythonhosted.org/packages/02/a0/32e1d5a21b703f600183e205aafc6773577e16429af5ad3c3f9b956b07ca/enum-0.4.7.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: /usr/local/lib/python3.6/site-packages/setuptools/version.py:1: UserWarning: Module enum was already imported from /usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/enum.py, but /private/tmp/pip-install-_d714hex/enum is being added to sys.path
      import pkg_resources
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-_d714hex/enum/setup.py", line 24, in <module>
        version = main_module.__version__
    AttributeError: module 'enum' has no attribute '__version__'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-_d714hex/enum/
```
