### ISSUE TITLE
dataset memory cache runs out of memory

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#27128]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory: 

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I use tf.dataset.cache to cache data and it will run out of my computer's memory
**Describe the expected behavior**
cache won't run out of memory
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
``` python
dataset.cache()
```

If we can use some cache storages just like leveldb which will provide high performance and will avoid memory leak.

**Comment by achandraa** [comment]
Thank you for reaching out to us. Can you please provide minimum reproducible code snippet and the error log to help us proceed further and verify what is going wrong

**Comment by fsx950223** [comment]
> Thank you for reaching out to us. Can you please provide minimum reproducible code snippet and the error log to help us proceed further and verify what is going wrong

Yeah,I will have a try with leveldb

**Comment by jvishnuvardhan** [comment]
@fsx950223 Could you describe more details about the issue and its context? Thanks!

**Comment by fsx950223** [comment]
> @fsx950223 Could you describe more details about the issue and its context? Thanks!

If I use memory cache, it will run out of my memory.I won't use file cache because I read data from tfrecords and file cache just read data and write it to another file,it's useless for me.
Anyway to avoid memory leak and provide high performance

**Comment by jsimsa** [comment]
If your experiment runs out of memory when using `tf.data.Dataset.cache()` it means that your data does not fit into computers memory. This is not an indication of a memory leak but the intended behavior of your workload. The API is not intended to be using for caching only a subset of your dataset in memory.

**Comment by Strateus** [comment]
I see similar behavior, and my dataset is about 1Gb, but it fills out 22Gb of free memory

**Comment by FalsoMoralista** [comment]
> I see similar behavior, and my dataset is about 1Gb, but it fills out 22Gb of free memory

That's probably because you have decoded/decompressed your data and stored raw bytes in the memory
