### ISSUE TITLE
Tensorflow with Pyinstaller

### ISSUE THREAD

**Issue by thematrixduo** [tensorflow/tensorflow#2712]
It seems that Tensorflow does not work with Pyinstaller. I was trying to build a Tensorflow script into a executable file using Pyinstaller on Ubuntu. However the following error is reported:

tensorflow.python.framework.errors.NotFoundError: tensorflow/contrib/layers/python/ops/_bucketization_op.so: cannot open shared object file: No such file or directory

### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN:  None
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

### Steps to reproduce
1. Pyinstaller tensorflow_script.py
2. ./tensorflow_script

**Comment by girving** [comment]
@martinwicke: Do we support Pyinstaller?  I've never heard of it. 

@thematrixduo: Where did you get `tensorflow_script.py`?

**Comment by martinwicke** [comment]
I don't know what pyinstaller is, and consequently I'm certain that we don't support it.

**Comment by martinwicke** [comment]
(It is likely that whatever dependency resolution pyinstaller uses to determine which extensions to include in its package does not pick up the correct files. That would be an issue with pyinstaller. You can look at the build_pip_package target to find out what needs to be included for all of TensorFlow.)

**Comment by thematrixduo** [comment]
@girving tensorflow_script.py is just an example tensorflow script.

**Comment by martinwicke** [comment]
If you're talking about a python package, create a pip package, and depend on the tensorflow package.

If you're talking about an application, this would depend on the platform you're targeting, and there's no answer that would fit all.
