### ISSUE TITLE
[Feature Request] tf.data.Dataset.batch to return RaggedTensor when batching different shape Tensors

### ISSUE THREAD

**Issue by jnd77** [tensorflow/tensorflow#27129]
**System information**
- TensorFlow version (you are using): TF 1.13.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Currently, when working with a tf.data.Dataset and batching together Tensors which have different shapes result in an error.
The new feature would return a RaggedTensor instead, which would also require tf.data.Dataset to handle RaggedTensor.

**Will this change the current api? How?**
API would be the same. Instead of an error, the Dataset might contain RaggedTensors.

**Who will benefit with this feature?**
Anyone working with tensors with different shapes.

**Any Other info.**

**Comment by achandraa** [comment]
Thank you for your suggestion. We will have a look and revert on the same further.

**Comment by gauravmishra** [comment]
This is now done. Please give it a try and let us know if there are any issues.
