### ISSUE TITLE
Issue while importing sugartensor --- tensorflow has no attribute core - SOLVED

### ISSUE THREAD

**Issue by sravan938** [tensorflow/tensorflow#27127]
I am using versions:
Tensorflow 1.13.1
Python 3.6
Sugartensor (0.0.2.4)

```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-5db6f289462a> in <module>
     17 '''
     18 from __future__ import print_function
---> 19 import sugartensor as tf
     20 import numpy as np
     21 from prepro import *

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\myenv\lib\site-packages\sugartensor\__init__.py in <module>
      1 from __future__ import absolute_import
----> 2 from tensorflow import *
      3 
      4 from .sg_util import sg_opt
      5 from .sg_main import *

AttributeError: module 'tensorflow' has no attribute 'core'

```

**Comment by jvishnuvardhan** [comment]
Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by sravan938** [comment]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows - Anaconda- Jupyter Notebook 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A



**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
# -*- coding: utf-8 -*-
'''
Evaluation.
We simulate typing in the mobile environment.
In most smartphones, words are suggested on the top of the keyboard area
so the user can choose their intended word before finishing his typing.
Suppose the user always select the word if it is on the center of suggestion bar
(the top candidate). We call it a `responsive keystroke (rk)`. We can evaluate the performance
of the predictive engine by counting the number of responsive keystrokes
compared to the number of original keystrokes, which we call `full keystrokes (fk)`.
Finally, the evaluation is conducted by calculating how many numbers of keystrokes
were saved by the predictive engine. We call the metric `keystroke savings rate (ksr)`.
ksr = (fk - rk) / fk
 
For the test 64 English paragraphs,
the generated model predicts a word per letter including a space.
'''
from __future__ import print_function
import sugartensor as tf
import numpy as np
from prepro import *
from train import ModelGraph
import codecs

def main(): 
    g = ModelGraph(mode="test")
        
    with tf.Session() as sess:
        tf.sg_init(sess)

        # restore parameters
        saver = tf.train.Saver()
        saver.restore(sess, tf.train.latest_checkpoint('asset/train'))
        print("Restored!")
        mname = open('asset/train/checkpoint', 'r').read().split('"')[1] # model name
        
        X, Y = load_test_data()
        char2idx, idx2char = load_char_vocab()
        word2idx, idx2word = load_word_vocab()
        
        results = []
        rk = 0
        num_para = 1
        num_char = 1
        for x, y in zip(X, Y):
            stop_counting = False
            x = np.concatenate( (np.zeros((Hyperparams.seqlen-1,)), 
                                 x[-np.count_nonzero(x):]))# lstrip and zero-pad
            
            para = "".join([idx2char[idx] for idx in x])
            
            chars, targets = [], [] # targets: the word that the char composes
            for word in "".join(para).split():
                chars.append(" ")
                targets.append(word)
                for char in word:
                    chars.append(char)
                    targets.append(word)
            
            prefix = "" 
            preds = set()
            for i, char_target in enumerate(zip(chars, targets)):
                char, target = char_target
                oov = ""
                if target not in word2idx: 
                    oov = "oov"
                
                if i > Hyperparams.seqlen:
                    ctx = np.array(x[i - Hyperparams.seqlen:i], np.int32) # 
                    
                    if char == " ":
                        stop_counting = False
                        preds = set()
                        
                    if not stop_counting:
                        logits = sess.run(g.logits, {g.x: np.expand_dims(ctx, 0)}) #(1, 20970)
                        while 1:
                            pred = np.argmax(logits, -1)[0] # (1,)
                            if pred in preds:
                                logits[:, pred] = -100000000
                            else:
                                break
                        
                        rk += 1
                        
                        predword = idx2word.get(pred)    
                        if predword == target: # S
                            stop_counting = True
                        preds.add(pred)
                    
                    results.append(u"{},{},{},{},{},{},{}".format(num_char, num_para, char, target, oov, predword, rk) )
                    num_char += 1
            
            num_para += 1
            
        with codecs.open('data/output_{}_rk_{}.csv'.format(mname, rk), 'w', 'utf-8') as fout:
            fout.write("\n".join(results))
                                        
if __name__ == '__main__':
    main()
    print("Done")

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-5db6f289462a> in <module>
     17 '''
     18 from __future__ import print_function
---> 19 import sugartensor as tf
     20 import numpy as np
     21 from prepro import *

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\myenv\lib\site-packages\sugartensor\__init__.py in <module>
      1 from __future__ import absolute_import
----> 2 from tensorflow import *
      3 
      4 from .sg_util import sg_opt
      5 from .sg_main import *

AttributeError: module 'tensorflow' has no attribute 'core'

from tensorflow import *
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-9e8f41c82356> in <module>
----> 1 from tensorflow import *

AttributeError: module 'tensorflow' has no attribute 'core'

**Comment by sravan938** [comment]
Please help me to solve this

**Comment by sravan938** [comment]
Installing right Python version (3.5) and tensorflow version (1.0) solved the issue

**Comment by aryachiranjeev** [comment]
> Installing right Python version (3.5) and tensorflow version (1.12.0) solved the issue

 Issue while importing sugartensor --- tensorflow has no attribute core

**Comment by aryachiranjeev** [comment]
Installing right Python version (3.5) and tensorflow version (1.12.0) 

Issue while importing sugartensor --- tensorflow has no attribute core

**Comment by aryachiranjeev** [comment]
Python version (3.5) and tensorflow version (1.12.0) 

Issue while importing sugartensor --- tensorflow has no attribute core

**Comment by aryachiranjeev** [comment]
@sravan938  how did you solve this issue. please help me with this

**Comment by sravan938** [comment]
@aryachiranjeev I have uninstalled all the previously installed python versions. Created a environment with python version 3.5  and then installed tensorflow version (1.0) which solved the issue
