### ISSUE TITLE
save_weights/load_weights with custom layer does not work in tensorflow 1.13.1, but work in tf 2.0.0a0

### ISSUE THREAD

**Issue by ductri** [tensorflow/tensorflow#27139]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, but very basic
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary (conda)
- TensorFlow version (use command below): 1.13.1 and 2.0.0a0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
In summary, I created a custom model in Model Subclassing style, which contained only 1 custom layer. After initial, I dumped its trainable weights to file and then restored it, by using save_weights and load_weights functions. The trainable weights before and after saving were different.

I also ran the same test on Tensorflow 2.0.0a0, and it turned out the latter version did not get this phenomenon. 
**Describe the expected behavior**
The trainable weights before and after saving should be the same, as they are in TF 2.0.0a0.

**Code to reproduce the issue**
My custom layer:
```
class EncodingLayer(tf.keras.layers.Layer):
    def __init__(self, out_size):
        super().__init__()
        self.rnn_layer = tf.keras.layers.GRU(out_size, return_sequences=True, return_state=True, recurrent_initializer='glorot_uniform')

    def call(self, X, **kwargs):
        output, state = self.rnn_layer(X)
        return output, state
```
The main part:
```
class EncodingModel(tf.keras.Model):

    def __init__(self):
        super().__init__()
        self.encoder_layer = EncodingLayer(out_size=1)

    def infer(self, inputs):
        output, state = self.encoder_layer(inputs)
        return output


if __name__ == '__main__':
    # Comment line below for running in TF 2.0
    tf.enable_eager_execution()

    # shape == (2, 3, 2)
    inputs = tf.convert_to_tensor([
        [[1., 2.], [2., 3.], [4., 4.]],
        [[1., 2.], [2., 3.], [4., 4.]],
    ])

    model = EncodingModel()

    # Just for building the graph
    model.infer(inputs)

    print('Before saving model: ', model.trainable_weights[0].numpy().mean())
    model.save_weights('weight')

    new_model = EncodingModel()
    new_model.infer(inputs)
    new_model.load_weights('weight')
    print('Loaded model: ', new_model.trainable_weights[0].numpy().mean())
```

**Other info / logs**
The result when running in TF 1.13.1:
```
Before saving model:  0.28864467
Loaded model:  0.117300846
```
The result when running in TF 2.0.0a0:
```
Before saving model:  -0.06922924
Loaded model:  -0.06922924
```

**Comment by allenlavoie** [comment]
Yep, we recently enabled sub-Layer tracking for Layer, as Network/Model has been doing for a while. 1.14 when it comes out will have Layer doing this tracking as well. In the meantime you may need to use tf.keras.Model rather than Layer if you're composing other Layers.
