### ISSUE TITLE
missing 2.0.0 alpha custom estimator guide

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#27132]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 2.0.0-alpha.0
- Doc Link: https://www.tensorflow.org/alpha/guide/keras/estimators

**Describe the documentation issue**

It's confusing since abundant guide stuff were uploaded, since no guide for custom estimator, just an example of using boostedClassifier

Is tf.keras.Model replacing tf.estimator?

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by Nimishkhurana** [comment]
It is available here: https://www.tensorflow.org/alpha/guide/migration_guide#using_a_custom_model_fn

**Comment by alanpurple** [comment]
@Nimishkhurana 
Thanks a lot, it seems like estimator is deprecated since that document shows lots of "compat.v1"

**Comment by ymodak** [comment]
Estimators are supported in 2.0 however the custom estimators will run in TF 1.X style in 2.0
