### ISSUE TITLE
how to assign values in Tensor according to the indices?

### ISSUE THREAD

**Issue by karlTUM** [tensorflow/tensorflow#2713]
I want to assign values in a tensor according to the indices.

For example, According to the pooling values and the corresponding indices output of `tf.nn.max_pool_with_argmax`, I want to put these pooling values back into the original unpooling Tensor given the indices.

According to the trick in [Adjust Single Value within Tensor — TensorFlow](http://stackoverflow.com/questions/34685947/adjust-single-value-within-tensor-tensorflow/34686952#34686952)
I can recreate sparse tensor with the indices.
But here is the problem: `tf.SparseTensor`  should input the unflattened indices i.e. the ndims coordinates list. 
If I use this method, how to unravel the flattened indices obtained by `tf.nn.max_pool_with_argmax` to the normal indices?
If I do not use this method, is there any way in Tensorflow to achieve this work?
Thank you very much.

**Comment by JianKangtum** [comment]
Has anyone came across the same problem?

**Comment by JianKangtum** [comment]
@vrv @mrry @girving 
Thank you very much.

**Comment by karlTUM** [comment]
I also post my question in stackoverflow:
http://stackoverflow.com/questions/37679697/in-tensorflow-how-to-assign-values-in-tensor-according-to-the-indices

**Comment by girving** [comment]
Thank you for posting the question as StackOverflow!  See also #2075.
