### ISSUE TITLE
Should `fold_constants` be before or after `flatten_atrous_conv`

### ISSUE THREAD

**Issue by lee-bin** [tensorflow/tensorflow#27146]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: v1.13.1
- Doc Link: https://github.com/tensorflow/tensorflow/blob/v1.13.1/tensorflow/tools/graph_transforms/README.md#flatten_atrous_conv

**Describe the documentation issue**
The `flatten_atrous_conv` section lists `Prerequisites: fold_constants`, whereas in the main paragraph, it says `You will need to make sure you run fold_constants after this transform.`
So should `fold_constants` be before or after `flatten_atrous_conv`?

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
I assume it's before `flatten_atrous_conv`, so I submitted a PR.
https://github.com/tensorflow/tensorflow/pull/27145

**Comment by MarkDaoust** [comment]
Hey @suharshs, any idea about the answer? or more generally the status of GraphTransform Tool?

**Comment by rmothukuru** [comment]
@lee-bin,
Can you please let us know if this change is still relevant as we don't use `Graph Transform Tool` much in **`Tensorflow 2.x`** ? Thanks!
