### ISSUE TITLE
keras.metrics.MeanIoU - AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by JamesTownend** [tensorflow/tensorflow#27150]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-alpha0
- Python version: 3.7.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: not relevant
- GPU model and memory: not relevant

**Describe the current behavior**
The example given for tf.keras.metrics.MeanIoU returns `AttributeError: 'list' object has no attribute 'shape'`. If I convert the lists to tf arrays as input, it runs without error.

**Describe the expected behavior**
The example given in the tf.keras.metrics.MeanIoU documentation should run without error.

**Code to reproduce the issue**
This is the example given in the docs with error message returned when ran:

```python
m = tf.keras.metrics.MeanIoU(num_classes=2)
m.update_state([0, 0, 1, 1], [0, 1, 0, 1])
# cm = [[1, 1],
#      [1, 1]]
# sum_row = [2, 2], sum_col = [2, 2], true_positives = [1, 1]
# iou = true_positives / (sum_row + sum_col - true_positives))
# result = (1 / (2 + 2 - 1) + 1 / (2 + 2 - 1)) / 2 = 0.33
print('Final result: ', m.result().numpy())  # Final result: 0.33
```

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-75e080c0562a> in <module>
      1 m = tf.keras.metrics.MeanIoU(num_classes=2)
----> 2 m.update_state([0, 0, 1, 1], [0, 1, 0, 1])
      3 # cm = [[1, 1],
      4 #      [1, 1]]
      5 # sum_row = [2, 2], sum_col = [2, 2], true_positives = [1, 1]

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/utils/metrics_utils.py in decorated(metric_obj, *args, **kwargs)
     69     """Decorated function with `add_update()`."""
     70 
---> 71     update_op = update_state_fn(*args, **kwargs)
     72     if update_op is not None:  # update_op will be None in eager execution.
     73       metric_obj.add_update(update_op, inputs=True)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py in update_state(self, y_true, y_pred, sample_weight)
   2273     """
   2274     # Flatten the input if its rank > 1.
-> 2275     if y_pred.shape.ndims > 1:
   2276       y_pred = array_ops.reshape(y_pred, [-1])
   2277 

AttributeError: 'list' object has no attribute 'shape'
```

**Comment by pavithrasv** [comment]
Thank you for the PR.

**Comment by pavithrasv** [comment]
Closing this issue as PR is merged.
