### ISSUE TITLE
SmartReply  Tensorflow Lite 

### ISSUE THREAD

**Issue by singh728om** [tensorflow/tensorflow#27154]
I'm visited in github repo on tensorflow but there are showing source code batch files not found when i want try to clone repo...

**Comment by Ayush517** [comment]
@jvishnuvardhan This isn't a bug/build issue, right?

**Comment by jvishnuvardhan** [comment]
@singh728om Please find instructions [here](https://help.github.com/en/articles/cloning-a-repository) to clone a repo on Github. 

In future, please post this kind od support questions on [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by singh728om** [comment]
Thankss..for This..but i know how to clone repo...i tell you just ..one
time i visited in Tensorflow lite  repo for auto reply system bit .in .that
repo no source code ..showing after cloning n also there were not available
for clone i was visited through path n raw file ..but it..didn't
work..that's why i discuss..with you sir...sorry..for...posting in git...

**Comment by jvishnuvardhan** [comment]
@singh728om Try it again and let me know which links are not working, and please also post with more details so that we can resolve it faster. Thanks!

**Comment by singh728om** [comment]
sure...i will..thankss..lot..for..support..me..to ask doubts...
