### ISSUE TITLE
Add a lite version of libtensorflow-core to Makefile

### ISSUE THREAD

**Issue by StephenOman** [tensorflow/tensorflow#2716]
The tensorflow iOS libraries created by the makefile have a very large footprint ( > 90 MB ).

To help reduce the size of apps, there should also be a lite version of the libraries, possibly based on the Bazel android_tensorflow_lib_lite target.

Note that Apple prevents apps larger than 100 MB from being downloaded over the air.

**Comment by petewarden** [comment]
@StephenOman we've reduced the footprint to about 11MB per architecture, which we're still working on shrinking but should be a lot more usable. Can you let me know if you're seeing that reduction too?

**Comment by StephenOman** [comment]
Thanks @petewarden. Will check it out.

**Comment by StephenOman** [comment]
I'm still getting libs between 75MB and 90MB per architecture based on a clean clone of the head last night and running build_all_ios.sh. Has the reduced footprint configuration been added to the main repo?

**Comment by petewarden** [comment]
It has, but one thing I realize I haven't documented well is passing in optimization flags to the build process. After doing that I see a single-architecture executable for the simple example of around 14MB (about 11MB for the lib and 3MB for the app code I think).

```bash
tensorflow/contrib/makefile/compile_ios_tensorflow.sh "-Os"
```

**Comment by StephenOman** [comment]
That's better than I'm getting. With that compiler option, I'm seeing approx 30/31 MB per lib per architecture.

For information, this is my gcc:

```
makefile $  gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include
dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
makefile $
```


Also note that build_all_ios.sh doesn't pass command line arguments to compile_ios_tensorflow.sh. That caught me out when I tried your suggestion!

**Comment by petewarden** [comment]
Good point on the build_all not passing through arguments, I should look at that.

Are you seeing this when you build the Simple example at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/ios_examples/simple ? The reason I'm asking is that the size of the libs on disk and the final size they contribute to an executable can be pretty different, so I want to check how you're building your final binary.

**Comment by StephenOman** [comment]
I've followed the instructions as outlined in the docs and at the moment, I'm still seeing 30MB libs on the disk.

The Simple example generates an app of 68MB on disk (building it in Xcode IDE). I haven't changed anything from the downloaded files.

**Comment by petewarden** [comment]
Are you building with release settings? I see a binary size of 13Mb when building the library with "-Os" (now the default with build_all_ios.sh) and then choosing Release in Edit Schemes in Xcode.

**Comment by StephenOman** [comment]
Yes thanks that works now. I see Simple App binary is 15.3MB on the disk.

Before I close this out, what is the purpose of the android_tensorflow_lib_lite collection in the Bazel BUILD in tensorflow/core?

**Comment by petewarden** [comment]
That's to have a version of the library that doesn't include any operators, so we can pick and choose exactly which implementations we use to reduce the code size even further. That's still a work in progress  though.
