### ISSUE TITLE
[TF 2.0 API Docs] tf.bitcast and tf.bitwise.*

### ISSUE THREAD

**Issue by hksonngan** [tensorflow/tensorflow#27166]
**System information**
- TensorFlow version: 2.0
- Doc Link: 
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/bitcast
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/bitwise/bitwise_and
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/bitwise/bitwise_or
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/bitwise/bitwise_xor
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/bitwise/bitwise_invert
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/bitwise/right_shift
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/bitwise/left_shift

**Describe the documentation issue**
* Correct links? No
* Clear Description?  Yes
* Usage Example? No
* Parameters Defined? Yes
* Returns defined? Yes
* Raises listed and defined? No
* Visuals, if applicable? No

same as #26492, #26532 documentation for tf.bitcast and tf.bitwise.* is created from a generated file, python/ops/gen_array_ops.py, and made incorrect link to source code.
The documentation can be modified by editing the appropriate .pbtxt files within the tensorflow/tensorflow/core/api_def/base_api directory of the source repository.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
yes

**Comment by Ayush517** [comment]
I think the pbtxt files present [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/api_def/base_api) are responsible for the documentation of these operations.

**Comment by shashvatshahi1998** [comment]
Ya link is incorrect in the documentation, but whats the correct location where i can add some example in tf.bitcast

**Comment by hksonngan** [comment]
you can find *.pbtxt here tensorflow/tensorflow/core/api_def/base_api/
api_def_Bitcast.pbtxt
api_def_BitwiseAnd.pbtxt
api_def_BitwiseOr.pbtxt
api_def_BitwiseXor.pbtxt

@dynamicwebpaige ping.

**Comment by shashvatshahi1998** [comment]
Ok thanks

**Comment by gadagashwini** [comment]
Closing this issue since the associated PR has been merged. Feel free to reopen if the problem still persists. Thanks!
