### ISSUE TITLE
Documentation Request: WALSModel with shard

### ISSUE THREAD

**Issue by SumNeuron** [tensorflow/tensorflow#27161]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: script built around docs
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: n/a
- **TensorFlow installed from (source or binary)**: conda gpu version
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: 10
- **GPU model and memory**: Quadro 16GiB
- **Exact command to reproduce**: `ex.run()` (see comments below)

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

This request comes with an associated [colab](https://colab.research.google.com/drive/1oJDfvIWnf7sY5uFcJ7XhTSEdA1n_3Jxv#scrollTo=8pqa0A7BUrG-)

Further, this documentation request stems from @walidk 's response on issue #26928 where 
it is suggested to shard the input matrix based on [wals_test.py](https://github.com/tensorflow/tensorflow/blob/f07558116ac7c90858cf0572a1bca1e50e208a37/tensorflow/contrib/factorization/python/ops/wals_test.py#L141)

While the code is relevant, it is not necessarily clear how to apply it to the [colab](https://colab.research.google.com/drive/1oJDfvIWnf7sY5uFcJ7XhTSEdA1n_3Jxv#scrollTo=8pqa0A7BUrG-)

Why?

1. there is `WALSModel` (used in the [colab](https://colab.research.google.com/drive/1oJDfvIWnf7sY5uFcJ7XhTSEdA1n_3Jxv#scrollTo=8pqa0A7BUrG-) ) and `WALSMatrixFactorization` (used in the linked test code). They seem the same, but what is the difference? Is that code compatible with `WALSModel`?

2. both `WALSModel` and `WALSMatrixFactorization` have `num_row_shards=1` / `num_col_shards=1` as arguments. It is unclear if these would automatically shard the input matrix.

3. as test code, it is not necessarily commented for pedagogical purposes

4. as test code, it is not exactly a MWE demonstrating just what is needed to handle shard an input matrix and train accordingly. Should both rows and cols be sharded at the same time? 

5. part of the test code may work against the goal of sharding (or it is also likely I do not full understand it):

e.g.

```python
....
 def _fn():
      ...
      sp_mat = self.np_array_to_sparse(np_matrix)
      sp_mat_t = sparse_ops.sparse_transpose(sp_mat) #<--- if goal is to shard input matrix because it is too large, why make 2?
      ...
...
```

I understand that this request it is a bit of an "advanced"  documentation and that those contributing to TF are very busy - especially with v2. However I feel like this is a valid request as:

1. the current documentation for `WALSModel` and `WALSMatrixFactorization` is already more than MWE including session supervisors (although leaning more towards pseudo code in some places which may make it more confusing than need be)

2. the current documentation for the built in arguments `num_row_shards` / `col` state "number of shards to use", which gives no indication that the linked test code is even needed or where it should be introduced

3. the current documentation hints at sharding (e.g. `transposed_matrix_slices_from_queue_for_worker_shard`) but assumes the user knows how to set that up.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by SumNeuron** [comment]
@walidk I started a [colab](https://colab.research.google.com/drive/1xGe3lRiKnwPuhc1FfgdZiayEE8rQQwvM) trying to fill out / finish the pseudo-code for `WALSModel`

**Comment by wileeam** [comment]
One of the motivations for the request of WALS implementation in TF 2.0 I did few days ago in #27107 is precisely because of this (in the part I point to distribute the implementation where possible).
It will be great to try to solve this as it will smooth the move of this method to TF 2.0...

**Comment by SumNeuron** [comment]
@walidk anything?

**Comment by sachinprasadhs** [comment]
Since `contrib` has been depreciated in `Tensorflow 2.x `and `WALS` is not supported as well in `TF 2.x`, you could try [Neural Collaborative Filtering (NCF)](https://github.com/tensorflow/models/tree/08bb9eb5ad79e6bceffc71aeea6af809cc78694b/official/recommendation) which is similar to that.
Feel free to open a new request if you have any issues.
