### ISSUE TITLE
TensorflowLite Convert error

### ISSUE THREAD

**Issue by liakopyangsir** [tensorflow/tensorflow#27176]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 1.18

**Provide the text output from tflite_convert**

```
# Copy and paste here
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, EXPAND_DIMS, FULLY_CONNECTED, MAX_POOL_2D, RESHAPE, SQUEEZE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: Merge, Switch.
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
As the output suggests, you have to build a custom operation to add those ops. Please take a look at this [faq](https://www.tensorflow.org/lite/guide/faq#models_operations) to know more. Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
