### ISSUE TITLE
[TF 2.0 alpha] Tutorial "Loading Data" wrong link path 

### ISSUE THREAD

**Issue by shaolinkhoa** [tensorflow/tensorflow#27182]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: Tensorflow 2.0 alpha
- Doc Link: 
[Load images with tf.data](https://www.tensorflow.org/alpha/tutorials/load_data/images)
[Using TFRecords and tf.Example](https://www.tensorflow.org/alpha/tutorials/load_data/tf_records)

**Describe the documentation issue**
[Load images with tf.data](https://www.tensorflow.org/alpha/tutorials/load_data/images) and [Using TFRecords and tf.Example](https://www.tensorflow.org/alpha/tutorials/load_data/tf_records) have wrong links to Colab and github.

They should link to 
https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/load_data/images.ipynb
https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/load_data/tf_records.ipynb

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by Ayush517** [comment]
@shaolinkhoa The issue has been updated and commits are approved. You can close this issue. Thank you for letting us know :)

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks all.
