### ISSUE TITLE
[TF 2.0 alpha] Fix "Load images with tf.data" to run on window

### ISSUE THREAD

**Issue by shaolinkhoa** [tensorflow/tensorflow#27180]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: Tensorflow 2.0 alpha
- Doc Link: Tutorial [Load images with tf.data](https://www.tensorflow.org/alpha/tutorials/load_data/images)

**Describe the documentation issue**
Tutorial [Load images with tf.data](https://www.tensorflow.org/alpha/tutorials/load_data/images) will have an error if it runs on windows because of the backslash of the path in this cell.
```
import IPython.display as display

def caption_image(image_path):
    image_rel = pathlib.Path(image_path).relative_to(data_root)
    return "Image (CC BY 2.0) " + ' - '.join(attributions[str(image_rel)].split(' - ')[:-1])
```

So I fixed it by replacing the backslash with the slash.
import IPython.display as display

```
def caption_image(image_path):
    image_rel = pathlib.Path(image_path).relative_to(data_root)
    image_rel = str(image_rel)
    image_rel=image_rel.replace('\\','/')
    str_return = "Image (CC BY 2.0) " + ' - '.join(attributions[str(image_rel)].split(' - ')[:-1]) 
    return str_return

```

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by MostafaGazar** [comment]
`Pathlib.Path` should create either a `WindowsPath` or a `PosixPath` based on your OS (takes care of slashes and backslashes under the hood). 

Can you share some information about your setup, like what python version you are running etc...

**Comment by shaolinkhoa** [comment]
Sure. I'm using Anaconda, python 3.6.8 on win10. I run the code on Jupyter notebook 5.7.4.
Pathlib takes care of the path but those picture's paths in "LICENSE.txt" are using the backslash.
Ex:
```
import os
attributions = (data_root/"LICENSE.txt").open(encoding='utf-8').readlines()[4:]
attributions = [line.split(' CC-BY') for line in attributions]
attributions = dict(attributions)
```
The dict `attributions `has the key `daisy/7568630428_8cf0fc16ff_n.jpg`
So when we use  `str_return = "Image (CC BY 2.0) " + ' - '.join(attributions[str(image_rel)].split(' - ')[:-1])` to extract the author name of the picture by the key it will get error because the image_path is still the `WindowsPath` `daisy\7568630428_8cf0fc16ff_n.jpg` after we converted it to string.

**Comment by ymodak** [comment]
@Ayush517 Can you please take a look at this issue? Thanks!

**Comment by lamberta** [comment]
This tutorial uses `os.path.sep` now: https://www.tensorflow.org/tutorials/load_data/images
