### ISSUE TITLE
RNN related API documents

### ISSUE THREAD

**Issue by hunkim** [tensorflow/tensorflow#2719]
Do you have any plan to release the RNN related API documents? I still cannot find them in TensorFlow R0.9 API doc: https://www.tensorflow.org/versions/r0.9/api_docs/python/index.html.

This was also asked in StackOverflow: http://stackoverflow.com/questions/37159372/.

**Comment by ebrevdo** [comment]
The API docs will be updated soon; as we *just* released the RNN docs in HEAD.  Not sure if this will end up in 0.9 or the next version.  @martinwicke?

**Comment by martinwicke** [comment]
Can you check the 0.9 docs? If the docs are there they're there.

**Comment by ebrevdo** [comment]
@martinwicke for some reason they don't show up.

**Comment by hunkim** [comment]
I also noticed.

**Comment by ebrevdo** [comment]
Should be fixed. Reopen if it's still an issue.
