### ISSUE TITLE
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'decode'

### ISSUE THREAD

**Issue by phambao** [tensorflow/tensorflow#27191]
i ran on Google Colab and saw error at the start of training model. 
----> 8     for (batch, (img_tensor, target)) in enumerate(dataset):
--->545   def __next__(self):  # For Python 3 compatibility
--> 546     return self.next()
--> 575       return self._next_internal()
--> 567             output_shapes=self._flat_output_shapes)
-> 1848       _six.raise_from(_core._status_to_exception(e.code, message), None)
UnknownError: AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'decode'
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 205, in __call__
    return func(device, token, args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 107, in __call__
    ret = self._func(*args)

  File "<ipython-input-45-2085415d85d1>", line 2, in map_func
    img_tensor = np.load(img_name.decode('utf-8')+'.npy')

**Comment by muddham** [comment]
@phambao Request you to please fill the template with infrastructure details so that we can suggest you the solution.

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Lamicc** [comment]
I suppose you encountered this problem while running the Image Captioning tutorial.
[https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/text/image_captioning.ipynb](url)

I solved this problem by replacing a line in `map_func` :
replace `img_tensor = np.load(img_name.decode('utf-8')+'.npy')`
with
`img_tensor = np.load(img_name.numpy().decode('utf-8')+'.npy')`
