### ISSUE TITLE
Non-uniform FFT layer

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#27193]
**System information**
- TensorFlow version (you are using): 1.13
- Are you willing to contribute it (Yes/No): Yes (but I only know how to code in Python)

**Describe the feature and the current behavior/state.**
Have a layer similar to the fft layer that will implement the non-uniform FFT.

**Will this change the current api? How?** This will allow to have one more option when using the signal module, `nfft`.

**Who will benefit with this feature?** People working with neural networks involving Non-uniform FFT. The main application I know of is MRI, but according to the [Wikipedia page](https://en.wikipedia.org/wiki/Non-uniform_discrete_Fourier_transform) there may be more applications. In particular, I think computed tomography can make use of it to accelerate acquisition times.

**Any Other info.** Since the NuFFT is not based on the FFT it would require a custom kernel and is therefore not trivial to implement. I haven't looked much into it but it could potentially make use of the [Flatiron Institute library](https://finufft.readthedocs.io/en/latest/).

**Comment by muddham** [comment]
Thanks for your contribution. we will keep this noted.

**Comment by aselle** [comment]
@zaccharieramzi. While this is an interesting possible feature, we have no plans to work on it currently. Let us know if you plan to start this work. It could easily go external to to TF in a custom op library to start and prove out the usability of the feature. Thanks!

**Comment by zaccharieramzi** [comment]
Sure. So for the record I have been working on it in this PR: https://github.com/odlgroup/odl/pull/1488. 

It still needs some polishing to fit the requirements of `odl` but I am using it as is currently in a project and it seems to work as expected.

**Comment by zaccharieramzi** [comment]
So I understood better how non-uniform fft works (which is definitely based on the fft, apologies), and I translated this code from pytorch to tf.
The result is [here](https://github.com/zaccharieramzi/tfkbnufft).

**Comment by rmothukuru** [comment]
@zaccharieramzi,
Can you please let us know if we can close this issue as it has been implemented? Thanks!

**Comment by zaccharieramzi** [comment]
Well it has been implemented but not in TensorFlow itself.
Closing anyway as I think it won't be the case in the near future, and the current solution is satisfying.
