### ISSUE TITLE
Tflite JNI wraps seems failing to release int array.

### ISSUE THREAD

**Issue by Xiadalei** [tensorflow/tensorflow#27202]
Hi, it seems that current impl of tflite jni overlooked ref release for array, And the current tflite really could make JNI reference table overflow some phones with Android 4.4.4 (API 19).

How: 
Just invoke `resizeInput` every time you run interpreter, even put the same int array to it. You can see the reference table is booming.

version:
I've tried 1.13.1 and 0.0.0-nightly, it's the same.

the relevant code is [here](https://github.com/tensorflow/tensorflow/blob/c18034bc927f733e5e5a43d0c421775f969e0d04/tensorflow/lite/java/src/main/native/nativeinterpreterwrapper_jni.cc#L104)

The strange thing is the code above, althrough didn't deal with release in some situation, should work fine with same int array.

**Comment by jdduke** [comment]
You're absolutely right, will push a fix shortly.
