### ISSUE TITLE
Error when restoring model using an LSTM layer

### ISSUE THREAD

**Issue by jgehw** [tensorflow/tensorflow#27201]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 1803
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
Reincarnation of bug #25327 for different layer type (LSTM rather than Embedding). After applying fix [cebce4a](https://github.com/tensorflow/tensorflow/commit/cebce4a2b5e33a06a1c92772008082895568f10a) for bug #25327, the code provided below results in `ValueError: Input 0 of node lstm/while/ReadVariableOp/Enter_1 was passed float from lstm/kernel_1:0 incompatible with expected resource.`.

**Describe the expected behavior**
Should restore model rather than raise error.

**Code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow import keras
# from tensorflow.python.framework import graph_util
import graph_util_fixed as graph_util  # using file with fix cebce4a
from tensorflow.python.framework import graph_io
from tensorflow.python.platform import gfile

model = keras.models.Sequential()
model.add(keras.layers.Embedding(0x1000, output_dim=128))
model.add(keras.layers.LSTM(512))
model.add(keras.layers.Dense(1, activation="sigmoid"))

sess = keras.backend.get_session()
output_node_names = [node.op.name for node in model.outputs]
constant_graph = graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(), output_node_names)
graph_io.write_graph(constant_graph, ".", "test.pb", as_text=False)

with tf.Session() as sess:
    with gfile.FastGFile("test.pb", "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        sess.graph.as_default()
        tf.import_graph_def(graph_def, name="")
```

**Comment by karmel** [comment]
@jgehw For saving and restoring, we would recommend you use tf.keras.Model.save() or tf.keras.experimental.export_saved_model(model). These will export to the Keras serialization format and the TF Saved Model format, respectively, both of which can be restored.

**Comment by jgehw** [comment]
@karmel Thanks for your hint. The code I provided was just a minimalistic example. Restoration of the model (i.e. the last 6 lines) is to be done using the tensorflow C bindings from a different program written in C++. I'd love to just call tf.keras.models.load_model() if it was available in the C bindings; the example code I provided was just my desperate try to get a tf.keras.Model saved in a way loadable using the tensorflow C bindings. Please correct me if I'm wrong or if there's a better way to achieve this.

**Comment by qlzh727** [comment]
Assigning this to Kathy who is working on the save/load model. From my understanding of save/load model, we don't have strong support on c bindings. I will leave this to Kathy and Karmel for final answer.

**Comment by karmel** [comment]
I don't entirely follow the use case and what you want, but the saved model loader provided from the TF C++ API will work with the models produced from tf.keras.experimental.export_saved_model, at least for inference: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/saved_model/loader.h#L50

**Comment by jgehw** [comment]
@karmel Thanks for pointing me to tf.keras.experimental.export_saved_model. I verified that this works in my setting, too. Provided that this experimental API will become regular API one day and not get removed, this obsoletes my code reproducing the issue.
