### ISSUE TITLE
install page wrong for version 2.0 alpha

### ISSUE THREAD

**Issue by zadeck** [tensorflow/tensorflow#27203]
on page https://www.tensorflow.org/install/pip

change "tensorflow==2.0.0-alpha0" to "tensorflow==2.0.0-a0"    (two instances)
change "tensorflow-gpu==2.0.0-alpha0" to "tensorflow-gpu==2.0.0-a0"
change "tensorflow==2.0.0-alpha0-gpu" to "tensorflow-gpu==2.0.0-a0"

on page https://www.tensorflow.org/install/gpu

change "tensorflow==2.0.0-alpha0" to "tensorflow==2.0.0-a0" 

i had to make these changes on my ubuntu-18-04 system to get it to install.

**Comment by ymodak** [comment]
```pip install tensorflow-gpu==2.0.0-alpha0``` and
```pip install tensorflow==2.0.0-alpha0``` work as expected.
I was able to download the wheel and install it successfully.

**Comment by zadeck** [comment]
you are right, they are both there.  I had tried "tensorflow==2.0.0-alpha0-gpu" and when that did not work just went looking around and came across the a0 aliases. 

I do believe that that "tensorflow==2.0.0-alpha0-gpu" reference is actually wrong, but the others are correct.

**Comment by ymodak** [comment]
Yes you are right about the ```tensorflow==2.0.0-alpha0-gpu``` we have to correct it. Thanks!

**Comment by ymodak** [comment]
@zadeck It has been fixed now. Thanks!
