### ISSUE TITLE
[TF2.0] How to build with Api v.2

### ISSUE THREAD

**Issue by ericpts** [tensorflow/tensorflow#27204]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian Buster
- TensorFlow version: v2.0.0-alpha0
- Python version: 3.7
- Bazel version (if compiling from source): 0.23.0
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: 10 / 7

**Describe the problem**

I have tried compiling TF 2.0 from source, because my platform has a libc which is too old for the normal distribution.
I have followed the instructions from here: https://www.tensorflow.org/install/source.

It compiles successfully, however it seems that the created package still uses the old v1 api.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```bash
git checkout v2.0.0-alpha0

bazel build --local_resources 4096,25,1 --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

./bazel-bin/tensorflow/tools/pip_package/build_pip_package --nightly_flag /tmp/tensorflow_pkg

pip3 install tf_nightly-2.0.0a0-cp37-cp37m-linux_x86_64.whl --user
```

I then get the error

```
AttributeError: module 'tensorflow._api.v1.summary' has no attribute 'create_file_writer'
```

**Comment by ali2210** [comment]
Steps
     Bazel -Ok
     tensorflow Ok
     cd ${GOPATH}/src/github.com/tensorflow/tensorflow
     ./configure
      python ok
      python-packages ok
      tensorflow xtla  Yes
      tensorflow cuda no
      tensorflow roc support Yes
      tensorflow mip support no
      fresh clang yes
      bazel build -c opt ok
android support no 
sudo cp ${GOPATH}/src/github.com/tensorflow/tensorflow/bazel-bin/tensorflow/libtensorflow.so /usr/local/lib       fail
sudo cp ${GOPATH}/src/github.com/tensorflow/tensorflow/bazel-bin/tensorflow/libtensorflow_framework.so /usr/local/lib fail
export LIBRARY_PATH=${GOPATH}/src/github.com/tensorflow/tensorflow/tensorflow pass
build fail 
Kindly share me how i build tensorflow go

**Comment by ericpts** [comment]
I found out the solution was adding a `--define=tf_api_version=2` flag to the bazel invocation:

```bash
bazel build --local_resources 2048,25,2 --define=tf_api_version=2 --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

**Comment by wdirons** [comment]
Add '--config=v2' to the bazel command line should be enough,

**Comment by ali2210** [comment]
Configuration had finished successfully, but Libtensorflow.so can't find.
That's why build failed. How to do that? Please help me
This Message send through secure channel called BBM

**Comment by jvishnuvardhan** [comment]
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Please open new issue for other questions. Thanks!
