### ISSUE TITLE
TensorFlowLiteSwift performance problem with bitcode enabled on iOS

### ISSUE THREAD

**Issue by jpangburn** [tensorflow/tensorflow#27209]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, I converted the [SpeechCommands example](https://github.com/tensorflow/examples/tree/master/lite/examples/speech_commands/ios/SpeechCommands) to use the TensorFlowLiteSwift API instead of the C wrapper in the original example.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPad Mini 2 real device and iPhone 6s simulator
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): latest commit is 95e72f827f8aa0c352d6e1f47ffeec58fe4c9ec9 from March 22.
- Python version: N/A for this problem
- Bazel version (if compiling from source): 0.23.2
- GCC/Compiler version (if compiling from source):
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.5.0

- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Compiling the TensorFlowLiteC_framework with bitcode support enabled slows down model inference on the sample model from ~72 ms (without bitcode support) to ~1200 ms (with bitcode support).

**Describe the expected behavior**
Would be nice if performance was approximately equivalent.

**Code to reproduce the issue**
Compile the TensorFlowLiteC_framework without bitcode support:
bazel build tensorflow/lite/experimental/c:TensorFlowLiteC_framework -c opt --ios_multi_cpus=x86_64,armv7,arm64
Then for comparison compile it with bitcode support:
bazel build tensorflow/lite/experimental/c:TensorFlowLiteC_framework -c fastbuild --ios_multi_cpus=x86_64,armv7,arm64 --apple_bitcode=embedded --copt=-fembed-bitcode

Use these with the experimental TensorFlowLiteSwift CocoaPod (not yet publicly available, see #25800 for reference) to perform a model inference on a real device or a simulator.  Regardless of debug/release build, if you use the framework with bitcode support in it then performance suffers greatly.

**Other info / logs**

If it would help to provide my Xcode project, I'm happy to provide it.  The Podfile would need to be modified to locate your own build CocoaPods because the TensorFlowLiteC pod uses the framework in question and it's not yet publicly available.

**Comment by jdduke** [comment]
Is `-c fastbuild` required for bitcode support? In general, we don't really make any promises about performance in debug builds, particularly debug builds running on emulators.

**Comment by jpangburn** [comment]
On the referenced issue #25800 @temrich said we needed that switch for bitcode support at least until bazel 0.24 is available.  You think that switch (vs `-c opt`) is what's making all the difference?  Nothing to do with bitcode?

Regarding emulators, I think the numbers above were my numbers on a real device.  Simulator is much faster, but with somewhat similar ratios of performance to a real device.

**Comment by jpangburn** [comment]
@temrich just released a publicly available `TensorFlowLiteSwift` pod and it doesn't have this problem.  Performance is the same with/without bitcode enabled so I'm closing this issue.
