### ISSUE TITLE
TF2.0 distribution strategy hanging on keras

### ISSUE THREAD

**Issue by md-k-sarker** [tensorflow/tensorflow#27207]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux release 7.5.1804 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source 
 from [tf2.0 branch](https://github.com/tensorflow/tensorflow/tree/v2.0.0-alpha0)
- TensorFlow version (use command below): 2.0.0a0
- Python version: 3.5.2
- Bazel version (if compiling from source): 19.2
- GCC/Compiler version (if compiling from source): 6.3
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
Trying to run simple example on cpu in distributed mode according to the documentation.  [tf2.0 documentation](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/r2/guide/distribute_strategy.ipynb) 

If I run the code using only python py_file.py then it is running fine. 
If I run it by setting TF_CONFIG environment variable with only 2 different node or even a single node then it is hanging. 

It hangs after generating this information: 
2019-03-27 11:44:19.963538: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  AVX512F FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2019-03-27 11:44:19.976632: I tensorflow/core/common_runtime/process_util.cc:92] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
WARNING: Logging before flag parsing goes to stderr.
W0327 11:44:19.979773 47985184916416 deprecation.py:506] From /panfs/users/mdkamruz/anaconda3/envs/py352_otf2.0_source/lib/python3.5/site-packages/tensorflow/python/ops/init_ops.py:1257: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0327 11:44:20.015144 47985184916416 distribute_coordinator.py:825] `eval_fn` is not passed in. The `worker_fn` will be used if an "evaluator" task exists in the cluster.
W0327 11:44:20.015259 47985184916416 distribute_coordinator.py:829] `eval_strategy` is not passed in. No distribution strategy will be used for evaluation.
2019-03-27 11:44:20.021537: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:250] Initialize GrpcChannelCache for job worker -> {0 -> localhost:3002}
2019-03-27 11:44:20.027697: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:359] Started server with target: grpc://localhost:3002
2019-03-27 11:44:20.027718: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:363] Server already started (target: grpc://localhost:3002)
W0327 11:44:20.095507 47985184916416 distribute_coordinator.py:825] `eval_fn` is not passed in. The `worker_fn` will be used if an "evaluator" task exists in the cluster.
W0327 11:44:20.095634 47985184916416 distribute_coordinator.py:829] `eval_strategy` is not passed in. No distribution strategy will be used for evaluation.
W0327 11:44:20.097250 47985184916416 distributed_training_utils.py:933] ModelCheckpoint callback is not provided. Workers will need to restart training if any fails.

**Describe the expected behavior**
It should run smoothly as described in the documentation. 

**Code to reproduce the issue**
Python code: 

```
dataset = tf.data.Dataset.from_tensors(([1.], [1.])).repeat(100).shuffle(buffer_size=10000).batch(10)
# single node
ds_strategy=tf.distribute.MirroredStrategy()
# cross_device_ops=tf.distribute.HierarchicalCopyAllReduce()
# multinode
# ds_strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
with ds_strategy.scope():
    model = tf.keras.Sequential([tf.keras.layers.Dense(1, input_shape=(1,))])
    model.compile(loss='mse', optimizer='sgd')
    model.fit(dataset,epochs=200)

```
TF_CONFIG environment variable: 
```
export TF_CONFIG='{
    "cluster": {
          "worker": ["IP_ADDR:3001"]
          },
    "task": {"type": "worker", "index": 0}
}'
# for single node multi worker
export TF_CONFIG='{
    "cluster": {
          "worker": ["IP_ADDR:3001","IP_ADDR:3002"]
          },
    "task": {"type": "worker", "index": 0}
}'
# for multinode 
# node 1 and similar for node 2
export TF_CONFIG='{
    "cluster": {
          "worker": ["IP_ADDR_1:3001","IP_ADDR_2:3002"]
          },
    "task": {"type": "worker", "index": 0}
}'
```

**Other info / logs**
Running on cpu, machine don't have any gpu

**Comment by lcycoding** [comment]
According to the provided document.
`tf.distribute.MirroredStrategy support synchronous distributed training on multiple GPUs on one machine. `

So running dist strat on cpu does not make sense...

**Comment by Keepmoving-ZXY** [comment]
> According to the provided document.
> `tf.distribute.MirroredStrategy support synchronous distributed training on multiple GPUs on one machine. `
> 
> So running dist strat on cpu does not make sense...

The nccl leads to tensorflow hang all the time no matter local training or multiworker training.

**Comment by ymodak** [comment]
The tutorial you have referenced works fine using google colab. Please give it a try using google colab. Thanks!

**Comment by Keepmoving-ZXY** [comment]
It seems that google colab do not provide GPU, so TensorFlow will not use `nccl` library to reduce, it can not  repeat the problem.

**Comment by ymodak** [comment]
You can select gpu accelerator under edit > notebook settings > hardware accelerator

**Comment by Keepmoving-ZXY** [comment]
But there is only one GPU in google colab, in which case tensorflow will not choose `nccl` to do reduction.

**Comment by guoshimin** [comment]
Not sure if the same issue, but I also experienced frequent hanging when using MultiWorkerMirroredStrategy with nccl. TF 2.0.0-alpha0 uses nccl 2.3.5-5. I modified the tensorflow source to use 2.3.7-1 instead and that seems to have fixed the issue. The [release notes](https://github.com/NVIDIA/nccl/releases/tag/v2.3.7-1) for 2.3.7-1 mentions
> Fixed a hang during bootstrap due to socket reuse.

**Comment by md-k-sarker** [comment]
I used master branch source code to build tensorflow 2.0 and seems it is working. Hence closing the issue.
