### ISSUE TITLE
[TF2.0] Syntax highlighting in PyCharm

### ISSUE THREAD

**Issue by evancasey** [tensorflow/tensorflow#27214]
Has anyone here had any success using tensorflow==2.0.0-alpha in pycharm? The new module organization is making it hard for PyCharm to infer namespaces correctly. 

For example, if I import as `tf.python.keras` syntax highlighting is fine and run time fails but if I import as `tf.keras` syntax highlight fails and run time works.

**Comment by MostafaGazar** [comment]
Works fine, have you checked your PyCharm Python Interpreter settings.

https://youtrack.jetbrains.com/issues/PY is probably a better place to report this.

**Comment by evancasey** [comment]
Thx!! Closing this since it looks like the issue has already been reported there.

https://youtrack.jetbrains.com/issue/PY-34174
https://youtrack.jetbrains.com/issue/PY-33034
