### ISSUE TITLE
tensorflow  performance of model evaluation using C++ is very lower than  using python. The model was trained by python ,and freezed to loaded by c++.

### ISSUE THREAD

**Issue by u4lr451** [tensorflow/tensorflow#2721]
tensorflow evaluation using c++  has very lower performance, 100 times lower than using python. 
1.The  model was trained using python,  freezed(using freeze_graph.py tool),  and then loaded by c++. 
2.The evaluation speed :  1K+/s using python ,VS 10/s using C++.

**Comment by prb12** [comment]
Please could you provide more detail about what you are trying to do here, in particular could you provide the code you are trying to 'freeze' and the exact command lines used to build and execute both the 'fast' and 'slow' versions.

@petewarden  - could you please take a look at this once the above information is provided.

**Comment by kakashidan** [comment]
@petewarden  I also had the same problem. I tested ```tensorflow/examples/label_image/main.cc``` and it took 5 seconds or more to predict the result. However, evaluation tested using python only took 0.5 seconds more or less.
Do you have any idea about the difference about performance?

**Comment by vrv** [comment]
If compiling the binary using bazel, I suspect you are not compiling your binary with -c opt or --copt=-mavx  on the command lines.  But we'd need more information to debug this anyway.

**Comment by kakashidan** [comment]
@vrv Thank you very much! 
It really helps.

**Comment by u4lr451** [comment]
@vrv thanks for you comment,  bazel need build binary with option   --config=cuda to enable GPU.

**Comment by abhigoku10** [comment]
@vrv Hi can you pls elaborate on the compilation part. I compile using bazel of my c++ code yet it takes more time than my python
