### ISSUE TITLE
raspberry pi 3B+ BERT

### ISSUE THREAD

**Issue by kzh22** [tensorflow/tensorflow#27216]
how to use BERT on tensorflow for raspberry pi?

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by kzh22** [comment]
thank you.
