### ISSUE TITLE
Tensorflow Installation for C does not work for Ubuntu 18.04 CUDA 10

### ISSUE THREAD

**Issue by jtang10** [tensorflow/tensorflow#27225]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.12
- Python version: N/A. Downloading C library from [Install TensorFlow for C](https://www.tensorflow.org/install/lang_c)
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: RTX 2080 Ti

**Problem Description**
Trying to use the pre-built C library for my project. Followed through the step in [Install Tensorflow for C](https://www.tensorflow.org/install/lang_c). However, when I tried to compile the hello_tf.c, it prompted a bunch of errors such as 
```
/opt/tensorflow/lib/libtensorflow.so: undefined reference to tensorflow::Status tensorflow::FunctionLibraryDefinition::GetAttr<bool>(tensorflow::Node const&, std::string const&, bool*) const'.
```
At the very start it gave a warning stating that
```
/usr/bin/ld: warning: libcublas.so.9.0, needed by /opt/tensorflow/lib/libtensorflow.so, not found (try using -rpath or -rpath-link)
``` 
so I believe it is because this pre-built is only for CUDA 9.0 but I have 10.0 installed on my machine. I cannot find any officially provided 10.0 build, but here is a workaround. 

**Workaround**
Basically after you built TF from source, there is a pre-built binary for C API in bazel-bin directory (inspired by [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/lib_package/README.md)). **DO NOT** follow the steps in the previous link to test and build it again. I have done that and it broke my old build so my Tensorflow Go didn't work anymore and I have to build again. I guess the reason was that it had a default configuration which didn't work with my system, while the formal build from the source steps let you configure your CUDA version, etc. Anyway, you can do the following:
 
1. Build the Tensorflow from source( follow the instructions [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md))
2. The C API that is suitable to your machine is generated in `bazel-bin/tensorflow/tools/lib_package/libtensorflow.tar.gz`. Use this instead of downloading from TF.
3. Follow the remaining steps in [Install Tensorflow for C](https://www.tensorflow.org/install/lang_c)

**Proposal to fix**
While this is not a problem for me anymore, I just want to leave it here so someone won't have to go through this as I did. Also, if CUDA version is the actually reason that failed my installation, I hope someone in charge of this adding the CUDA version into the filename to notify people.

**Comment by ymodak** [comment]
Apologies for the delay in response and thanks for sharing your investigation. 
TF 1.12 supports cuda 9.0 whereas TF 1.13.1 and above support cuda 10.0
We have mentioned this information on the [tf website](https://www.tensorflow.org/install/gpu#software_requirements). Thanks!
