### ISSUE TITLE
No way to use string type with Lite C APIs.

### ISSUE THREAD

**Issue by mattn** [tensorflow/tensorflow#27223]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10, Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: a26413ef0a179dd93b5228b031de83dce97a8684
- Python version: 3.7 but I'm writing TfLite with C
- Installed using virtualenv? pip? conda?: see above
- Bazel version (if compiling from source): see above
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**

I'm trying to implement smartreply using go-tflite. Most of features can be implemented with C APIs. But no way to manipulate dynamic-buffer. Do you have plan to add APIs for dynamic-buffers?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

No way to explain to reproduce.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. Thanks!

**Comment by mattn** [comment]
Updated

**Comment by jdduke** [comment]
Thanks for flagging. Yes, we're still finalizing both the C++/C APIs for string tensor interop. This is definitely on our radar.

**Comment by mattn** [comment]
If the API will be implemented, I want to specify allocator type since the buffer might be passed from the external.

**Comment by jdduke** [comment]
@karimnosseir can you follow up on this one?

**Comment by mohantym** [comment]
Hi @mattn !
We are checking whether you are still looking for assistance in this issue. Have you checked [inference_with_metadata ](https://www.tensorflow.org/lite/inference_with_metadata/task_library/nl_classifier#run_inference_in_c)documentation of lite for text classification.


Thank you!
