### ISSUE TITLE
tf1.13 can be installed with cuda8.0, cudnn5.1 but tf1.6 cannot

### ISSUE THREAD

**Issue by yangjingyi** [tensorflow/tensorflow#27231]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by yangjingyi** [comment]
Ubuntu 16.04
Cuda 8.0
Cudnn 5.1
tensorflow pip3 install tensorflow install tf1.13 sucessfully
but I cannot install tf1.4 with pip install tensorflow-gpu==1.6.0 (https://pypi.org/project/tensorflow-gpu/1.6.0/)

**Comment by gadagashwini** [comment]
@yangjingyi Please find instructions in this [link](https://www.tensorflow.org/install/gpu#linux_setup) which help you to install Tensorflow GPU on Linux Ubuntu platform. Please let me know how it progresses.

**Comment by ymodak** [comment]
@yangjingyi You can download the tensorflow 1.6 wheels from this [page](https://pypi.org/project/tensorflow-gpu/1.6.0/#files). Further you can pip install the downloaded wheels to install tf. Hope this helps. Thanks!
