### ISSUE TITLE
Build Issue on windows - cd command does not change drive without /d flag

### ISSUE THREAD

**Issue by phil20686** [tensorflow/tensorflow#27246]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 10:
- TensorFlow installed from (source or binary): building
- TensorFlow version: Master
- Python version: 3.6
- Bazel version (if compiling from source):23.0
- GCC/Compiler version (if compiling from source):VS2015
- CUDA/cuDNN version:7.1
- GPU model and memory:GTX970

**Describe the problem**

When building with bazel the it fails with the following 

`ERROR: D:/phil/python/tensorflow/tensorflow/core/BUILD:2676:1: Executing genrule //tensorflow/core:version_info_gen failed (Exit 1): bash.exe failed: error executing command
  cd C:/users/username/_bazel_username/frxyltss/execroot/org_tensorflow

  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1

   <more set parameters>

  C:/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/x64_windows-opt/bin/tensorflow/tools/git/gen_git_source.exe --generate external/local_config_git/gen/spec.json external/local_config_git/gen/head external/local_config_git/gen/branch_ref "bazel-out/x64_windows-opt/genfiles/tensorflow/core/util/version_info.cc" --git_tag_override=${GIT_TAG_OVERRIDE:-}

Execution platform: @bazel_tools//platforms:host_platform

D:\Phil\Virtual Environments\tensorflow_compilation\Scripts\python.exe: can't find '__main__' module in 'C:\\users\\yvann'
Target //tensorflow/tools/pip_package:build_pip_package failed to build`

The cause of this is that the tensorflow source directory is on the D drive, but the temporary files are created in the windows user directory that is on the C drive. On windows the cd command does not change drive by default. Thus the line 
`cd C:/users/username/_bazel_username/frxyltss/execroot/org_tensorflow`
will not change the directory if the current working directory is on the D drive. This can be fixed by making the above line cd /d <path> which will then change drive. Alternatively you can insert cd D:
This command appears to be autogenerated but i cannot easily see how to change it.

**Comment by meteorcloudy** [comment]
Thanks for the reporting, this is a Bazel issue. 
I created an Bazel issue at https://github.com/bazelbuild/bazel/issues/7904

**Comment by meteorcloudy** [comment]
As explained in https://github.com/bazelbuild/bazel/issues/7904
> What "bazel build -s" prints is decorational.
Bazel doesn't actually shell out to cmd.exe (or Bash, or cd) to change the directory.

So Bazel didn't actually run any cd command, so the build error is caused by some other problem, probably in some TF script.

**Comment by meteorcloudy** [comment]
Where does `C:\users\yvann` come from?

**Comment by sanatmpa1** [comment]
@phil20686,

We are checking to see if you still need help on this issue. We recommend that you upgrade to `2.6` which is latest stable version of TF and let us know if the issue still persists in newer versions. You can use this [guide](https://www.tensorflow.org/install/source_windows) as a reference while building TF for windows.Thanks!
