### ISSUE TITLE
:gather_string failed (Exit 127)

### ISSUE THREAD

**Issue by dssangan** [tensorflow/tensorflow#27242]
Hello all, 

I'm having issues installing tensorflow on my windows system using bazel. If there is any other alternative or fix please let me know

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Build 17134
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: Yes
- **TensorFlow version (use command below)**: Latest version (I'm building it off current master, can't see which version it is)
- **Python version**: 3.6.6
- **Bazel version (if compiling from source)**: 0.23.2
- **GCC/Compiler version (if compiling from source)**: Using VS2017 with v140 toolkit
- **CUDA/cuDNN version**: CUDA; 10.1.105 cudnn:7.5.0
- **GPU model and memory**: GTX 1060 6GB
- **Exact command to reproduce**:
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
python ./configure.py
bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true --copt=-nvcc_options=disable-warnings //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
HItting this error
ERROR: C:/users/darshan/tensorflow/tensorflow/lite/python/testdata/BUILD:35:1: Executing genrule //tensorflow/lite/python/testdata:gather_string failed (Exit 127): bash.exe failed: error executing command
### Source code / logs
INFO: From Linking tensorflow/lite/toco/toco:
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/lib64'; ignored
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64'; ignored
LINK : warning LNK4044: unrecognized option '/ldl'; ignored
LINK : warning LNK4044: unrecognized option '/ldl'; ignored
LINK : warning LNK4044: unrecognized option '/ldl'; ignored
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/lite/toco/toco.lib and object bazel-out/x64_windows-opt/bin/tensorflow/lite/toco/toco.exp
libcudnn_plugin.lo(cuda_dnn.o) : warning LNK4217: locally defined symbol ?ThenBlasGemm@Stream@stream_executor@@QEAAAEAV12@W4Transpose@blas@2@0_K11MAEBV?$DeviceMemory@M@2@H2HMPEAV52@H@Z (public: class stream_executor::Stream & __cdecl stream_executor::Stream::ThenBlasGemm(enum stream_executor::blas::Transpose,enum stream_executor::blas::Transpose,unsigned __int64,unsigned __int64,unsigned __int64,float,class stream_executor::DeviceMemory<float> const &,int,class stream_executor::DeviceMemory<float> const &,int,float,class stream_executor::DeviceMemory<float> *,int)) imported in function "public: virtual bool __cdecl stream_executor::gpu::CudnnSupport::DoMatMul(class stream_executor::Stream *,class stream_executor::DeviceMemory<float> const &,class stream_executor::DeviceMemory<float> const &,class stream_executor::dnn::BatchDescriptor const &,class stream_executor::dnn::BatchDescriptor const &,class stream_executor::DeviceMemory<float> *)" (?DoMatMul@CudnnSupport@gpu@stream_executor@@UEAA_NPEAVStream@3@AEBV?$DeviceMemory@M@3@1AEBVBatchDescriptor@dnn@3@2PEAV53@@Z)
ERROR: C:/users/darshan/tensorflow/tensorflow/lite/python/testdata/BUILD:35:1: Executing genrule //tensorflow/lite/python/testdata:gather_string failed (Exit 127): bash.exe failed: error executing command
  cd C:/users/darshan/_bazel_darshan/jojkqojs/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1
    SET CUDNN_INSTALL_PATH=C:/Program Files/cuda
    SET PATH=D:\Programs\msys2\usr\bin;D:\Programs\msys2\bin;D:\Programs\Python Installed\Scripts\;D:\Programs\Python Installed\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files (x86)\GnuWin32\bin;C:\Program Files\Git\cmd;D:\Software\MPC;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Java\jre1.8.0_181\bin;C:\Program Files\PuTTY\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.1\;C:\Users\Darshan\AppData\Local\Microsoft\WindowsApps;C:\Users\Darshan\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Darshan\AppData\Roaming\Dashlane\6.5.0.12978\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\Darshan\AppData\Roaming\Dashlane\6.5.0.12978\ucrt;C:\Users\Darshan\AppData\Roaming\Dashlane\6.5.0.12978\bin\Qt;C:\Users\Darshan\AppData\Roaming\Dashlane\6.5.0.12978\ucrt;C:\Users\Darshan\AppData\Roaming\Dashlane\6.5.0.12978\bin\Ssl;C:\Users\Darshan\AppData\Local\GitHubDesktop\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\extras\CUPTI\lib64;D:\Programs\Python Installed;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\tools;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include;D:\Programs;C:\Program Files\Java\jdk1.8.0_201;D:\Programs\msys2\usr\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC;
    SET PYTHON_BIN_PATH=D:/Programs/Python Installed/python.exe
    SET PYTHON_LIB_PATH=D:/Programs/Python Installed/lib/site-packages
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=6.1
    SET TF_CUDA_VERSION=10.1
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  D:/Programs/msys2/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/x64_windows-opt/bin/tensorflow/lite/toco/toco --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --input_file=tensorflow/lite/python/testdata/gather.pbtxt --output_file=bazel-out/x64_windows-opt/genfiles/tensorflow/lite/python/testdata/gather_string.tflite --input_arrays=input,indices --output_arrays=output
Execution platform: @bazel_tools//platforms:host_platform
C:/users/darshan/_bazel_darshan/jojkqojs/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/tensorflow/lite/toco/toco: error while loading shared libraries: cudnn64_7.dll: cannot open shared object file: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 126.000s, Critical Path: 24.69s
INFO: 32 processes: 32 local.
FAILED: Build did NOT complete successfully

Previously I tried another combination of tensorflow-1.12 and bazel-0.15, everything else was same. But I kept running into another which I looked around a lot and there were threads about it but no solution. So I started all over with latest version. (My protobuf version is 5.6.0, saw in another thread where they downgraded it to 5.2.1. I don't know if it will really help me here since I'm configuring the latest version to work on my system)

Any and all help is really appreciated!!

--
Thanks
Best Regards

**Comment by ymodak** [comment]
The latest version of TF 1.13.1 support cuda 10.0 Can you please downgrade your cuda version to 10.0 and build again. Thanks!

**Comment by dssangan** [comment]
What version of Cudnn?

**Comment by dssangan** [comment]
> The latest version of TF 1.13.1 support cuda 10.0 Can you please downgrade your cuda version to 10.0 and build again. Thanks!

What version of Cudnn should I use?

**Comment by ymodak** [comment]
cuDNN >= 7.4.1 should be fine. https://developer.nvidia.com/cudnn

**Comment by dssangan** [comment]
> cuDNN >= 7.4.1 should be fine. https://developer.nvidia.com/cudnn

I have 7.5.0, I will give it a shot and let you know by tomorrow end of the day.


Thank you so much!!! <3

**Comment by dssangan** [comment]
It worked, thank you for all the help!!
