### ISSUE TITLE
tf.data input pipeline got strange bug with tensorflow-gpu

### ISSUE THREAD

**Issue by ZeliangSu** [tensorflow/tensorflow#27245]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Linux Ubuntu 16.04
- Mobile device if the issue happens on mobile device: Dell Precision Tower 7910
- TensorFlow installed from (source or binary): tensorflow-gpu 1.12.0
- TensorFlow version (use command below): tensorflow-gpu 1.12.0
- Installed from: conda
- Python version: python 3.6
- GCC/Compiler version (if compiling from source): 6.5.0
- CUDA/cuDNN version: 9.2 but nvcc 7.5
- GPU model and memory:Quadro M4000

**Describe the current behavior**
The following code worked fine with tensorflow-cpu 1.12.0 but not with the gpu version.
I got error:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: transpose expects a vector of size 5. But input(1) is a vector of size 4
	 [[{{node gradients/Conv1/Conv2D_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](IteratorGetNext/_19, PermConstNHWCToNCHW-LayoutOptimizer)]]
	 [[{{node mean_squared_error/num_present/broadcast_weights/assert_broadcastable/AssertGuard/Assert/Switch_2/_37}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_63_me...t/Switch_2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```
Here's the traceback:

> Traceback (most recent call last):
>   File "/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
>     return fn(*args)
>   File "/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
>     run_metadata)

Another thread on parallel threw:

> Traceback (most recent call last):
>   File "20190328_.py", line 52, in <module>    sess.run([train_op])
>   File "/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
>     run_metadata_ptr)
>   File "/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
>   File "/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
>     raise type(e)(node_def, op, message)

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import h5py
import threading
import numpy as np
import tensorflow as tf

# make some random img data
for i in range(100):
    with h5py.File('./test_{}.h5'.format(i), 'w') as f:
        f.create_dataset('X', shape=(1000, 100, 100), dtype='float32', data=np.random.rand(10**7).reshape(1000, 100, 100))
        f.create_dataset('y', shape=(1000, 100, 100), dtype='float32', data=np.random.rand(10**7).reshape(1000, 100, 100))
        print(threading.get_ident())

# params
num_cores = 3
shuffle_size = 1
batch_size = 1

# read .h5 file
def parse_file(f):
    print(f.decode('utf-8'))
    with h5py.File(f.decode("utf-8"), 'r') as fi:
        X = fi['X'][:].reshape(1000, 100, 100, 1)
        y = fi['y'][:].reshape(1000, 100, 100, 1)
        print(threading.get_ident())  # to see the thread id
        return X, y

# py_func wrapper
def parse_file_tf(filename):
    return tf.py_func(parse_file, [filename], [tf.float32, tf.float32])

# input pipeline
files = tf.data.Dataset.list_files('./test_*.h5')
dataset = files.map(parse_file_tf, num_parallel_calls=num_cores)
dataset = dataset.batch(batch_size).shuffle(shuffle_size).prefetch(10)
it = dataset.make_initializable_iterator()
iter_init_op = it.initializer
X_it, y_it = it.get_next()

# simplest model
with tf.name_scope("Conv1"):
    W = tf.get_variable("W", shape=[3, 3, 1, 1],
                         initializer=tf.contrib.layers.xavier_initializer())
    b = tf.get_variable("b", shape=[1], initializer=tf.contrib.layers.xavier_initializer())
    layer1 = tf.nn.conv2d(X_it, W, strides=[1, 1, 1, 1], padding='SAME') + b
    out = tf.nn.relu(layer1)

loss = tf.reduce_mean(tf.losses.mean_squared_error(labels=y_it, predictions=out))
train_op = tf.train.AdamOptimizer(learning_rate=0.0001).minimize(loss)

# session
sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(iter_init_op)
sess.run([train_op])
sess.close()
```
Thanks for your help

**Comment by ymodak** [comment]
Can you please update your code by changing the argument ```data_format="NCHW"``` given in ```tf.nn.conv2d``` function? By default it is set to ```"NHWC"```

**Comment by ZeliangSu** [comment]
@ymodak Thank you for your reply. I think the problem comes from the convention or mechanism of tf.data.  My case is that one batch contains one sample of multiple images. You can understand like 1000 color channels. Consequently my CNN see one batch of one image of dimension rank-4 (1000, 100, 100, 1) instead of 1000 batches of images of dimension rank-3 (100, 100, 1). I did try to reshape the image to (1, 100, 100, 1000) but it seems that tensorflow supports maximum 4 channels. I got around this programming issue by separating each channel as one image and load them in a batch (like tradition). However, physically it doesn't make any sense since channels will be passed by same convolution kernels.

**Comment by xavysp** [comment]
> @ymodak Thank you for your reply. I think the problem comes from the convention or mechanism of tf.data. My case is that one batch contains one sample of multiple images. You can understand like 1000 color channels. Consequently my CNN see one batch of one image of dimension rank-4 (1000, 100, 100, 1) instead of 1000 batches of images of dimension rank-3 (100, 100, 1). I did try to reshape the image to (1, 100, 100, 1000) but it seems that tensorflow supports maximum 4 channels. I got around this programming issue by separating each channel as one image and load them in a batch (like tradition). However, physically it doesn't make any sense since channels will be passed by same convolution kernels.

Good morning @ZeliangSu   I think my problem is in the same line. After checking in [ StackOverflow](https://stackoverflow.com/questions/55375435/cannot-add-tensor-to-the-batch-number-of-elements-does-not-match/56002510#56002510) I cannot solve the error displayed below:
```
mer_summary, self.global_step, lr])
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [400,400,1], [batch]: [400,400,3]
	 [[node IteratorGetNext (defined at run_model.py:254) ]]

Caused by op 'IteratorGetNext'
```
Whenever the numbers of iteration were 90 it was working properly, since I changed the dataset with 6480 iterations the input tensor does not match the batch size. Actually, my input size is [400, 400, 3] and the target [400, 400, 3], the prediction size is [400,400,1]. To compute the loss function I use tf.image.rgb_to_grayscale().

 Here the definition of my dataset:

`# Training
        train_list = data_cache['train_paths']
        train_list = np.array(train_list)
        train_data = tf.data.Dataset.from_tensor_slices((train_list[:,0],train_list[:,1]))
        train_data = train_data.shuffle(1000)
        train_data = train_data.map(self.load_train_edge, num_parallel_calls=4)
        train_data = train_data.batch(self.bs)
        train_data = train_data.prefetch(self.bs)
        train_iter = train_data.make_initializable_iterator()
        train_img,train_targ = train_iter.get_next()
        # train_iter_init_op = train_iter.initializer
        # Validation
        val_list = data_cache['val_paths']
        val_list = np.array(val_list)
        val_data = tf.data.Dataset.from_tensor_slices((val_list[:,0],val_list[:,1]))
        val_data  = val_data.map(self.load_train_edge, num_parallel_calls=4)
        val_data = val_data.batch(self.bs)
        val_iter = val_data.make_initializable_iterator()
        val_img, val_targ = val_iter.get_next()`

The function in map is:

```
    def load(self,image_file):
        input_img = tf.io.read_file(image_file[0])
        input_img = tf.image.decode_jpeg(input_img)

        real_img = tf.io.read_file(image_file[1])
        real_img=tf.image.decode_png(real_img)
        real_img = tf.cast(real_img, tf.float32)
        input_img = tf.cast(input_img, tf.float32)
        return input_img, real_img

    def random_crop_edge(self,input_img,real_img):
        if np.random.random() > 0.5:
            stacked_img = tf.stack([input_img, real_img], axis=0)
            cropped_img = tf.image.random_crop(stacked_img, size=[2, self.img_height, self.img_height, 3])
            input_img, real_img = cropped_img[0], cropped_img[1]
        else:
            input_img = tf.image.resize(input_img, size=[self.img_height, self.img_width],
                                        method=tf.image.ResizeMethod.NEAREST_NEIGHBOR, align_corners=True)
            real_img = tf.image.resize(real_img, size=[self.img_height, self.img_width],
                                       method=tf.image.ResizeMethod.NEAREST_NEIGHBOR, align_corners=True)
            input_img = tf.reshape(input_img, [self.img_height, self.img_width, 3])
            real_img = tf.reshape(real_img, [self.img_height, self.img_width, 3])
        return input_img, real_img

    def load_train_edge(self,input_paths, target_path):
        input_img, real_img = self.load([input_paths, target_path])
        input_img, real_img = self.random_crop_edge(input_img, real_img)
        return input_img, real_img
```
System information

    Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes a little bit

    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04

    TensorFlow installed from (source or binary): binary

    TensorFlow version (use command below): 1.13.1

    Python version: 3.7

    Bazel version (if compiling from source):

    GCC/Compiler version (if compiling from source):

    CUDA/cuDNN version: 10.0 

    GPU model and memory: GeForce GTX TITAN X

    CPU Make & Model: Intel(R) Xeon(R) CPU E5-1620 v3

    Data Drive: 

Did you solve your problem? please help me :'( @ymodak @ZeliangSu @jsimsa

**Comment by jsimsa** [comment]
The error you are seeing suggests that you are trying to create a batch of tensors that have incompatible shapes (both `[400, 400, 3]` and `[400, 400, 1]`).

You should be able to identify the mismatch by printing the shapes of the elements in your input pipeline:

```
train_list = data_cache['train_paths']
train_list = np.array(train_list)
train_data = tf.data.Dataset.from_tensor_slices((train_list[:,0],train_list[:,1]))
train_data = train_data.map(self.load_train_edge, num_parallel_calls=4)
train_iter = train_data.make_initializable_iterator()
get_next = train_iter.get_next()

with tf.Session() as sess:
  print(sess.run(train_iter.initializer))
  while True:
    try:
      image, target = sess.run(get_next)
      print(image.shape, target.shape)
    except errors.OutOfRangeError:
      pass
```

**Comment by xavysp** [comment]
> The error you are seeing suggests that you are trying to create a batch of tensors that have incompatible shapes (both `[400, 400, 3]` and `[400, 400, 1]`).
> 
> You should be able to identify the mismatch by printing the shapes of the elements in your input pipeline:
> 
> ```
> train_list = data_cache['train_paths']
> train_list = np.array(train_list)
> train_data = tf.data.Dataset.from_tensor_slices((train_list[:,0],train_list[:,1]))
> train_data = train_data.map(self.load_train_edge, num_parallel_calls=4)
> train_iter = train_data.make_initializable_iterator()
> get_next = train_iter.get_next()
> 
> with tf.Session() as sess:
>   print(sess.run(train_iter.initializer))
>   while True:
>     try:
>       image, target = sess.run(get_next)
>       print(image.shape, target.shape)
>     except errors.OutOfRangeError:
>       pass
> ```

I will try that way but before this, I have printed the size of every single input and target, and all of them matched.

Thanks 
Xavier

**Comment by D4n1aLLL** [comment]
> 
> 
> The error you are seeing suggests that you are trying to create a batch of tensors that have incompatible shapes (both `[400, 400, 3]` and `[400, 400, 1]`).
> 
> You should be able to identify the mismatch by printing the shapes of the elements in your input pipeline:
> 
> ```
> train_list = data_cache['train_paths']
> train_list = np.array(train_list)
> train_data = tf.data.Dataset.from_tensor_slices((train_list[:,0],train_list[:,1]))
> train_data = train_data.map(self.load_train_edge, num_parallel_calls=4)
> train_iter = train_data.make_initializable_iterator()
> get_next = train_iter.get_next()
> 
> with tf.Session() as sess:
>   print(sess.run(train_iter.initializer))
>   while True:
>     try:
>       image, target = sess.run(get_next)
>       print(image.shape, target.shape)
>     except errors.OutOfRangeError:
>       pass
> ```

Can you tell me how to load my tfrecord? The code before train_list = data_cache['train_paths'] is missing. I have the same problem.

**Comment by rmothukuru** [comment]
@ZeliangSu,
Sorry for the delayed response. Can you please let us know if your issue is resolved as per [jsimsa's comment](https://github.com/tensorflow/tensorflow/issues/27245#issuecomment-489726216). Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
