### ISSUE TITLE
helper_functions.inc (Google howto fail)

### ISSUE THREAD

**Issue by ludwigschreier** [tensorflow/tensorflow#27250]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): VMware Ubuntu 18.04.2
- TensorFlow installed from (source or binary): according to howto (see description of problem)
- TensorFlow version: according to howto (see description of problem)
- Python version: latest
- Installed using virtualenv? pip? conda?: according to howto (see description of problem)
- Bazel version (if compiling from source): not installed
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: NA
- GPU model and memory: VMware

**Describe the problem**

ludwig1@ubuntu:~/dev$ make -f tensorflow/tensorflow/lite/experimental/micro/tools/make/Makefile test
tensorflow/tensorflow/lite/experimental/micro/tools/make/Makefile:5: tensorflow/lite/experimental/micro/tools/make/helper_functions.inc: No such file or directory
/bin/sh: 1: [[: not found
make: *** No rule to make target 'tensorflow/lite/experimental/micro/tools/make/helper_functions.inc'.  Stop.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Following howto: https://codelabs.developers.google.com/codelabs/sparkfun-tensorflow/#2

Used command: "make -f tensorflow/lite/experimental/micro/tools/make/Makefile test"

**Any other info / logs**
NA

**Comment by wdirons** [comment]
I believe you need to `cd tensorflow`, after the `git clone` so your in the correct directory when the command is run.

i.e. it should be  `make -f tensorflow/lite/experimental/micro/tools/make/Makefile test`
and not `make -f tensorflow/tensorflow/lite/experimental/micro/tools/make/Makefile test`

The 2nd command tells me your in the wrong directory.

**Comment by ludwigschreier** [comment]
It works, thanks! Ticket can be closed.

**Comment by ymodak** [comment]
Closing since its resolved. Thanks!
