### ISSUE TITLE
TensorFlow 1.x to TensorFlow 2.x

### ISSUE THREAD

**Issue by Yudonggeun** [tensorflow/tensorflow#27267]
tf.contrib.training.HParams is TensorFlow 1.x
How can I use tf.contrib.training.HParams in 2.x?

**Comment by shashvatshahi1998** [comment]
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

This is the way in which you can use this function in tensorflow 2.x.

**Comment by Yudonggeun** [comment]
WOW, Thank you!!

**Comment by timsainb** [comment]
Is `tf.contrib.training.HParams` getting removed from tf 2.0 completely? Is there an alternative in 2.0?

**Comment by jinfagang** [comment]
@shafi-dayatar  ```
    hparams = tf.contrib.training.HParams(
AttributeError: module 'tensorflow.compat.v1' has no attribute 'contrib'


```

**Comment by coolkidmacho** [comment]
Yes I need help with this aswell
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
doesnt work for me

**Comment by AfvanMoopen** [comment]
same here tf.disable_v2_behavior() is not working ?
