### ISSUE TITLE
[doc] broken link in tf.logging

### ISSUE THREAD

**Issue by csukuangfj** [tensorflow/tensorflow#27269]
**System information**
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/logging

**Describe the documentation issue**
> Defined in **tensorflow/_api/v1/logging/ _ _ init _ _.py**.

The link for _ _ init _ _.py is broken: https://www.tensorflow.org/code/stable/tensorflow/_api/v1/logging/__init__.py

https://www.tensorflow.org/api_docs/python/tf/logging

**Comment by shashvatshahi1998** [comment]
what is its original link

**Comment by csukuangfj** [comment]
@shashvatshahi1998 

you can click the links of other functions in the same page and you'll find the expected link.
Then a pullrequest.

**Comment by shashvatshahi1998** [comment]
So we have to just put the correct link for tf.logging in tensorflow guide, thats the only issue???

**Comment by shashvatshahi1998** [comment]
There is a file for changing links and I am not getting the link of that sheet where we can edit the link which is on the guide page of tf.logging

**Comment by shashvatshahi1998** [comment]
Actually tf.logging is removed in new version of TF that is 2.0.0 so that's why the link their is of no use as tensorflow is focussing to change complete documentation for TF2.0. You can also refer to issue #26662

**Comment by muddham** [comment]
@csukuangfj   Thanks for bringing this to our notice. We will take a look and resolve it. Thanks!

**Comment by jvishnuvardhan** [comment]
For me, except __init__.py link (https://www.tensorflow.org/code/stable/tensorflow/_api/v1/logging/__init__.py) everything else is working. Thanks!

**Comment by md-k-sarker** [comment]
Faced no logging module in tensorflow 2.0, which is obvious. Any update on this? 
And if logging is not available in tensorflow 2.0 what is the alternative for logging, pure python logging?

**Comment by MarkDaoust** [comment]
> pure python logging?

I think that's it, or absl_py logging?
