### ISSUE TITLE
if I use feature_column.embedding_column, how to get embedding variables?

### ISSUE THREAD

**Issue by Lihengwannafly** [tensorflow/tensorflow#27268]
```
uid = fc.categorical_column_with_hash_bucket("uid", 10000, dtype=tf.int64)
item_id = fc.categorical_column_with_hash_bucket("item_id", 10000, dtype=tf.int64)
uid_embed = fc.embedding_column(uid, 64)
item_id_embed = fc.embedding_column(item_id, 64)
```
I want to extract the embedding matrix for other task, how to implement this idea?

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by sjtusmartboy** [comment]
Any idea on this problem? Is it solved
