### ISSUE TITLE
Incorrect flops calculation for operations with complex numbers

### ISSUE THREAD

**Issue by saugatkandel** [tensorflow/tensorflow#27266]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Red Hat 4.8.5-16
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): via Anaconda
- TensorFlow version (use command below): 1.12
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Code to reproduce the issue**
```
tf.reset_default_graph()
x = tf.constant(2 + 3j, dtype='complex64')
y = tf.constant(3 + 2j, dtype='complex64')
z = x * y

session = tf.Session()
session.run(tf.global_variables_initializer())

run_meta = tf.RunMetadata()
opts = tf.profiler.ProfileOptionBuilder.float_operation()    
flops = tf.profiler.profile(run_meta=run_meta, cmd='op', options=opts) 
print(flops.total_float_ops) 
```
The output is:
```
1
```

**Describe the current behavior**
Multiplication of complex numbers typically requires 6 floating point operations (4 real multiplications and 2 real additions) and not just 1 floating point operation. The [functions that calculate the flops statistics](https://github.com/tensorflow/tensorflow/blob/f43d458a318d4d97298710654f1692f6e8364f82/tensorflow/python/profiler/internal/flops_registry.py) do not seem to distinguish between floats and complex numbers.

**Expected behavior**
For complex numbers, addition and multiplication should require 2 and 6 flops (with real numbers) respectively.

**Comment by saugatkandel** [comment]
I ended up customizing the flops registry of tensorflow to account for complex numbers:

https://github.com/saugatkandel/second-order-phase-retrieval/blob/master/benchmarks/ops/tensorflow/flops_registry_custom.py

**Comment by jvishnuvardhan** [comment]
@saugatkandel the link in your post (flops_registry_custom.py) throws 404 error. Thanks!

**Comment by penpornk** [comment]
@saugatkandel Thank you for reporting the issue! If you have already fixed this in your branch, please consider opening a PR so we can merge it in.

**Comment by jvishnuvardhan** [comment]
@saugatkandel Correct location of your code
https://github.com/saugatkandel/second-order-phase-retrieval/blob/master/sopt/benchmarks/ops/tensorflow/flops_registry_custom.py
Thanks!

**Comment by saugatkandel** [comment]
@jvishnuvardhan  Yes, that is the code  - thanks!

@penpornk Since I am modifying the RegisterStatistics class from tensorflow.python.framework.ops in addition to the the flops registry, I am not sure if a PR is appropriate?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by bhack** [comment]
Can we close this?

**Comment by sanatmpa1** [comment]
@saugatkandel, 

Can you please respond to the above comment.If you think PR is not appropriate, can you please let us know how you want this issue to be resolved. Thanks!

**Comment by saugatkandel** [comment]
For my work, I used some custom code to account for complex64 numbers:

https://github.com/saugatkandel/sopt/blob/master/sopt/benchmarks/ops/tensorflow/flops_registry_custom.py

Note that my "fix" only applies to complex64 numbers (not complex128), and is intended for TensorFlow 1.x code.  This is quite limited and is not a full fix for the issue at hand. 

Since I am no longer working on this project, I will not be able to make the appropriate changes and submit a PR. As such, someone at TensorFlow might have to make the appropriate fixes.

**Comment by sushreebarsa** [comment]
@saugatkandel TF v1.x is no longer supported. We recommend you to upgrade to the latest TF versions(2.8 or above) and refer to this [doc](https://www.tensorflow.org/guide/migrate). Thank you!
