### ISSUE TITLE
The training value of tf.keras.Model.call() becomes None when tf.keras.Model.fit(). (tf2.0.0-alpha0)

### ISSUE THREAD

**Issue by taxio** [tensorflow/tensorflow#27275]
I read the [document](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/Model#__call__) and implemented a model with `tf.keras.Model` as a subclass, but the value of training argument becomes `None`.

Is this a bug? Or is my understanding wrong? This is a basic question, but please let me know.

Here is the simplified code.

```python
import numpy as np
import tensorflow as tf
import tensorflow.keras as tfk


class MyLayer(tfk.layers.Layer):
    def __init__(self):
        super(MyLayer, self).__init__()

    def call(self, inputs, training=None):
        # got: Tensor("keras_learning_phase:0", shape=(), dtype=bool)
        print("layer training arg: ", training)
        
        return inputs


class MyModel(tfk.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.l1 = MyLayer()

    def call(self, inputs, training=None):
        # want: Tensor("keras_learning_phase:0", shape=(), dtype=bool)  got: None
        print("model training arg: ", training)
        
        inputs = self.l1(inputs)
        return inputs


if __name__ == '__main__':
    x = np.zeros((1, 2))
    model = MyModel()
    model.compile(loss="mse", optimizer="sgd")
    model.fit(x, x, epochs=1)

```

**System information**

- macOS Mojave 10.14.3
- TensorFlow installed from : pip
- TensorFlow version: 2.0.0a0
- Python version: 3.5.6 (using pyenv)

**Comment by yudongqiu** [comment]
:+1: I noticed the same bug and I'm also interested in the solution.

I use Ubuntu 16.04.1, Python 3.7 in Anaconda, Tensorflow installed from pip:
```
>>> print(tf.__version__)
2.0.0-alpha0
print(tf.keras.__version__)
2.2.4-tf
```

**Comment by omalleyt12** [comment]
Thanks for the bug! Was able to repro, will update when a fix is available

**Comment by omalleyt12** [comment]
A fix should now be available in the latest nightly :)
