### ISSUE TITLE
/tensorflow/lite/experimental/c/c_api_types.h is not readable on Windows filesystem.

### ISSUE THREAD

**Issue by mattn** [tensorflow/tensorflow#27282]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: f089b3180ec7ddecd503d6d499cd6977c22b8f11
- Python version: No
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): gcc 8.3
- CUDA/cuDNN version: No
- GPU model and memory: No

**Describe the problem**

`/tensorflow/lite/experimental/c/c_api_types.h` is symbolic link to `/tensorflow/lite/c/c_api_internal.h`.  On DOS compatible file system, it is replaced with following text file.
```
../../c/c_api_internal.h
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Clone repository, and make sure file `/tensorflow/lite/experimental/c/c_api_types.h`  is NOT a symbolic link on Windows.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

No

**Comment by mattn** [comment]
I suggest that the file `c_api_types.h` is replaced to be:

```
#include "tensorflow/lite/c/c_api_internal.h"
```

Or fix all files which include `c_api_types.h` to include `c_api_internal.h`.

**Comment by jdduke** [comment]
We'll be removing the symlink in the next week or so, which should resolve the problem. Is this breaking your build?

**Comment by mattn** [comment]
As I mentioned above, symbolic link is not created with git clone. Windows Git makes plain text file that the path is written.

**Comment by stakemura** [comment]
@jdduke Do you have any plans to introduce patch #27427?
This issue is important for us.

**Comment by jdduke** [comment]
Apologies for the delay, hoping to land a fix by EOD. Thanks for your patience.

**Comment by mattn** [comment]
@jdduke do you mean exerimental feature will be merged into standard feature soon?

**Comment by jdduke** [comment]
Yes we're hoping to migrate the C API bindings out of experimental.
