### ISSUE TITLE
GPU Memory Leak for eager mode, tf.scatter_nd_update.

### ISSUE THREAD

**Issue by irvingzhang0512** [tensorflow/tensorflow#27288]
- Have I written custom code : yes
- OS Platform and Distribution : ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: v1.12.0
- Python version: 3.6.8
- CUDA/cuDNN version: 9.2/7.2.1
- GPU model and memory: Tesla P40, 24GB

when i use `tf.scatter_nd_update`, if ref is tf.int32 Variable, everything is fine. if ref is tf.float32 Variable, then there is a memory leak.

i hope the folloing code will reproduce the bug.

```python
import os
import tensorflow as tf
from tensorflow.contrib.memory_stats import BytesInUse

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "2"
config = tf.ConfigProto(allow_soft_placement=True)
config.gpu_options.allow_growth = True
tf.enable_eager_execution(config=config)

for i in range(10):
    ref = tf.zeros((128, 21, 4), dtype=tf.int32)
    indices = tf.zeros([128, 2], dtype=tf.int32)
    updates = tf.ones([128, 4], dtype=tf.int32)
    update = tf.scatter_nd_update(tf.Variable(ref), indices, updates)
    tf.set_random_seed(1)
    print(BytesInUse().numpy())

print('------------------------------------')

for i in range(10):
    ref = tf.zeros((128, 21, 4), dtype=tf.float32)
    indices = tf.zeros([128, 2], dtype=tf.int32)
    updates = tf.ones([128, 4], dtype=tf.float32)
    update = tf.scatter_nd_update(tf.Variable(ref), indices, updates)
    tf.set_random_seed(1)
    print(BytesInUse().numpy())
```

when i run the code, get the following results

```
1280
1280
1280
1280
1280
1280
1280
1280
1280
1280
------------------------------------
89344
132608
175616
261376
303616
347648
389632
433664
475648
519680
```

**Comment by alextp** [comment]
Can you remove allow_growth and add a "import gc; gc.collect()" before printing the bytes in use to confirm it's not an issue just of the python gc taking a while to run?

**Comment by irvingzhang0512** [comment]
@alextp hi, thanks for your reply. i add `import gc; gc.collect()` and get the same result.

codes

```python
import os
import tensorflow as tf
from tensorflow.contrib.memory_stats import BytesInUse

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "2"
config = tf.ConfigProto(allow_soft_placement=True)
config.gpu_options.allow_growth = True
tf.enable_eager_execution(config=config)

for i in range(10):
    ref = tf.zeros((128, 21, 4), dtype=tf.int32)
    indices = tf.zeros([128, 2], dtype=tf.int32)
    updates = tf.ones([128, 4], dtype=tf.int32)
    update = tf.scatter_nd_update(tf.Variable(ref), indices, updates)
    tf.set_random_seed(1)
    import gc; gc.collect()
    print(BytesInUse().numpy())

print('------------------------------------')

for i in range(10):
    ref = tf.zeros((128, 21, 4), dtype=tf.float32)
    indices = tf.zeros([128, 2], dtype=tf.int32)
    updates = tf.ones([128, 4], dtype=tf.float32)
    update = tf.scatter_nd_update(tf.Variable(ref), indices, updates)
    tf.set_random_seed(1)
    import gc; gc.collect()
    print(BytesInUse().numpy())
```

results
```
1280
1280
1280
1280
1280
1280
1280
1280
1280
1280
------------------------------------
89344
132608
175616
261376
303616
347648
389632
433664
475648
519680
```

**Comment by alextp** [comment]
@jaingaurav can you look at this?

**Comment by alextp** [comment]
Also does this also reproduce on tf nightly? 1.12 is a little old and it had some known memory leaks.

**Comment by irvingzhang0512** [comment]
I do know there are some known memory leaks for v1.12.0
#19671, this issue mentioned that `tf.set_random_seed(1)` can fix the known issue.
BTW, I haven't use tf nightly before, I may have a try latter.

**Comment by irvingzhang0512** [comment]
tf nightly gpu can reproduce the bug.

**Comment by irvingzhang0512** [comment]
@jaingaurav could you please look at this?

**Comment by jaingaurav** [comment]
@irvingzhang0512: A little swamped at the moment, but I plan on starting work on this bug next week.

**Comment by XuesongYang** [comment]
same issue here, any updates? @irvingzhang0512  btw, tf.set_random_seed(x) workaround could assign any value for x, right?

**Comment by irvingzhang0512** [comment]
@XuesongYang yes, i think `tf.set_random_seed(x)` clears eager mode caches by calling `pywrap_tensorflow.TFE_ContextClearCaches(self._context_handle)`. so any value works.

**Comment by pmwaniki** [comment]
at what point do you add tf.set_random_seed(1). i placed the line before model.compile() but i'm still having problems. I have to comment out tf.enable_eager_execution() otherwise my RAM gets depleted and computer freezes.

**Comment by alextp** [comment]
@jaingaurav this is serious enough we should at least triage it before the 2.0 RC

**Comment by jaingaurav** [comment]
I believe I'm able to reproduce this in a unit test now. Working on finding the source of the leak.
