### ISSUE TITLE
TensorBoard inception v3 visualization is horizontal and almost unusable

### ISSUE THREAD

**Issue by kuza55** [tensorflow/tensorflow#2729]
### Environment info
Operating System: Linux x64 GPU

Installed version of CUDA and cuDNN: CUDA 7.5, cuDNN v4

If installed from binary pip package, provide: 0.8.0

I've been trying to retrain the inception v3 network using the image_retraining example, and then the inception v3 model in the models repo.

The image_retraining model[1] seems to visualize vertically and it relatively straight forward to look at.

The model from the models repo[2] visualizes horizontally, making zooming in and exploring the model really tricky.

[1] http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz
[2] http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz

**Comment by danmane** [comment]
Thanks for the report. In the coming few months we're planning to prioritize making the graph visualizer more useful on a wider range of models; we'll revisit this issue then. For now, I'm going to close this to keep issue tracking manageable.
