### ISSUE TITLE
Python module generated by `tf.load_op_library` contains no custom ops

### ISSUE THREAD

**Issue by dMokaMoka** [tensorflow/tensorflow#27307]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.13.1
- Python version:3.6
- Bazel version (if compiling from source):0.19.2-dist
- GCC/Compiler version (if compiling from source):5.4.0
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Problem**
I followed the instructions on https://tensorflow.google.cn/guide/extend/op to customize my own OPs step by step. For simple verification, I used the fact OP that comes with tensorflow (I also tried my own OP). I add BUILD file in the same directory with fact.cc 
```
load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

tf_custom_op_library(
    name = "fact.so",
    srcs = ["fact.cc"],
)
```
and then build 
```
bazel build --config opt //tensorflow/core/user_ops:fact.so
```
But when I use fact.so as the instructions describe:
```
# python
import tensorflow as tf
fact_module = tf.load_op_library('./fact.so')
fact_module.fact
```
I got following errors
```
Traceback (most recent call last):
  File "/tmp/remote_python/main.py", line 10, in <module>
    fact_module.fact
AttributeError: module '670cc8cfec5b6d3b8635f39bd583d769' has no attribute 'fact'
```
Is this normal?

**Comment by dMokaMoka** [comment]
This is due to the fact that I have installed tensorflow with my own op...

**Comment by sjtusmartboy** [comment]
@dMokaMoka hi, what do you mean by 'installed tensorflow with my own op'?

**Comment by yank666** [comment]
Did you solve that? I meet same error ,  but when i chang usr_op name to FactStr ( "Fact" to "FactStr"), error no more  appear，i dont figure out how it run normal
