### ISSUE TITLE
Document stride parameter for XlaBuilder::Slice

### ISSUE THREAD

**Issue by satnam6502** [tensorflow/tensorflow#27305]
Doc Link: https://www.tensorflow.org/xla/operation_semantics
The documentation for [XlaBuilder::Slice](https://www.tensorflow.org/xla/operation_semantics#slice) does not mention the stride parameter.

**Comment by lamberta** [comment]
In [xla_builder.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/client/xla_builder.h#L1206), the signature looks like:
```
XlaOp Slice(XlaOp operand, absl::Span<const int64> start_indices,
            absl::Span<const int64> limit_indices,
            absl::Span<const int64> strides);
```
In the docs, it looks like: `Slice(operand, start_indices, limit_indices)`
