### ISSUE TITLE
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by traian-d** [tensorflow/tensorflow#27306]
I am getting the error mentioned above when trying to use TF GPU.
My setup is as follows:
OS: Ubuntu 16.04
Python 3.5.2
Tensorflow: tensorflow-gpu 1.13.1
Cuda version: 10.0
libcublas.so.10.0 is present in /usr/local/cuda-10.0/lib64
/usr/local/cuda-10.0/lib64 is added to PATH and LD_LIBRARY_PATH.

Other Github issue threads related to similar issues didn't help.

I would be grateful for any help/suggestions, thanks!

**Comment by Mainak431** [comment]
This is a very common error while setting up tensorflow gpu.
You are using GPU. 
Here Cuda is not installed correctly. 
So, Libcublas version is not found. This Libcublas version is speaking of the required Cuda version 10.0 to be compatible with this tensorflow version. (Still sometimes there are gotchas which means incompatibility with the version of Cuda, CuDNN and Tensorflow-gpu)

Make sure you have installed - cuda-libraries . 

sudo apt-get install cuda-libraries-<version>

For detailed help on how to install and work on tensorflow-gpu you can see my blog here. 

https://medium.com/@mainakdutta76/gpu-configuration-for-deep-learning-f35a8bf0f5e1

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. But, please let me know if I'm mistaken.

**Comment by SubigyaPanta** [comment]
I have the same problem.
OS: Ubuntu 16.04
Python: 3.6
Tensorflow: 1.13
Nvidia Driver version: 410.78
Cuda version: 10.0

When I import Keras, I get this error. I haven't used tensorflow standalone. Help.

**Comment by Mainak431** [comment]
What is the version of tensorflow-gpu?  And what is the version of CUDNN?

**Comment by SubigyaPanta** [comment]
I have installed cudnn 7.4.2
This is what I get when verifying Cudnn installation:
![cudnn-test-passed](https://user-images.githubusercontent.com/2729048/57148333-93766080-6df3-11e9-88af-5fa727660cd0.png)

What other cuda-libraries do I need to install ?

**Comment by Mainak431** [comment]
pip install cuda-libraries-10-1

And even after this if it fails.

Check my blog here.

**Comment by PointCloudNiphon** [comment]
My cuda is 10.1,  and now have the same mistakes with yours ,ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
please give me a hand.

**Comment by Mainak431** [comment]
@pointcloudniphon please go through the link.  If you are using Tf 2.0 alpha , you need to install CUDA 10.0 and CUDNN 7.4. Else downgrade your tensorflow to 1.8.0. Follow this link  https://medium.com/@mainakdutta76/gpu-configuration-for-deep-learning-f35a8bf0f5e1. Thanks.
