### ISSUE TITLE
TensorBoard feature request: Search for Node

### ISSUE THREAD

**Issue by kuza55** [tensorflow/tensorflow#2730]
I have been trying to retrain the inception v3 network and TensorBoard has been the only real way to introspect the network and it's implementation so far.

It would be very useful to be able to find nodes in the graph, by name or other properties. E.g. in my case I am interested in seeing the total_loss node that is being defined here: https://github.com/tensorflow/models/blob/master/inception/inception/inception_train.py#L120 To get a greater idea of what it is linked to.

**Comment by girving** [comment]
Does `tf.Graph.get_operations` or `tf.Graph.get_operation_by_name` work for you?

**Comment by kuza55** [comment]
This is for the TensorBoard GUI, rather than the tensorflow API.

**Comment by girving** [comment]
@danmane Care to comment?  Should we mark this contributions welcome?

**Comment by danmane** [comment]
I'm assigning nikhil and daniel to take a look, since it's a graph explorer question. But I also pre-emptively marked it contributions welcome...

**Comment by chihuahua** [comment]
This issue has been migrated to tensorflow/tensorboard#76 because TensorBoard has migrated to a new repo (outside of tensorflow/tensorflow).
