### ISSUE TITLE
BasicLSTMCell performances questions

### ISSUE THREAD

**Issue by COthello** [tensorflow/tensorflow#27309]
I was reading tf code now, but not understand following comments: why "+", "*" performances are bad? can anyone help to explain? Thanks!

**Note that using `add` and `multiply` instead of `+` and `*` gives a
performance improvement. So using those at the cost of readability.**

    add = math_ops.add
    multiply = math_ops.multiply
    new_c = add(multiply(c, sigmoid(add(f, forget_bias_tensor))),
                multiply(sigmoid(i), self._activation(j)))
    new_h = multiply(self._activation(new_c), sigmoid(o))

**Comment by jvishnuvardhan** [comment]
Most of the tf.math_ops are optimized for performance and are also very useful for graph based calculations. 
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by COthello** [comment]
> Most of the tf.math_ops are optimized for performance and are also very useful for graph based calculations.
> This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this issue as it is a support question that is suited for Stackoverflow. Thanks!
