### ISSUE TITLE
[TF 2.0] tf.summary.histogram error

### ISSUE THREAD

**Issue by ericpts** [tensorflow/tensorflow#27311]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian Testing
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): '2.0.0-dev20190327'
- Python version: 3.7

**Describe the current behavior**

I want to log gradients and weights of the model as it is training, using `tf.summary.histogram()`.
It seems that the function is not properly implemented, however, as using it results in an error:
```
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/plugins/histogram/summary_v2.py", line 67, in histogram
    tensor = _buckets(data, bucket_count=buckets)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/plugins/histogram/summary_v2.py", line 85, in _buckets
    with tf.name_scope('buckets', values=[data, bucket_count]):
```

**Describe the expected behavior**

`tf.summary.histogram()` should properly log histogram data.

**Code to reproduce the issue**
``` python3
import tensorflow as tf

tf.summary.histogram(
    'test',
    [1.0, 2.0, 3.0],
    step=1,
)
```

**Other info / logs**

```
  File "dat.py", line 6, in <module>
    step=1,
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/plugins/histogram/summary_v2.py", line 67, in histogram
    tensor = _buckets(data, bucket_count=buckets)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/plugins/histogram/summary_v2.py", line 85, in _buckets
    with tf.name_scope('buckets', values=[data, bucket_count]):
TypeError: __init__() got an unexpected keyword argument 'values'
```

**Comment by shashvatshahi1998** [comment]
Example:- 
summary = tf.Summary(value=[tf.Summary.Value(tag=tag, histo=hist)])
writer.add_summary(summary, step)
writer.flush()

placeholder = tf.placeholder(tf.float32)

tf.summary.histogram('N(0,1)', placeholder)
summaries = tf.summary.merge_all()
writer = tf.summary.FileWriter('./summaries')

__Last two line are what you are missing__

**Comment by ericpts** [comment]
@shashvatshahi1998 I used your code and I get the following error:
```
Traceback (most recent call last):
  File "dat.py", line 3, in <module>
    ph = tf.placeholder(tf.float32)
AttributeError: module 'tensorflow' has no attribute 'placeholder'
```

It seems that `tf.placeholder()` does not exist anymore in the TF 2.0 API.

**Comment by shashvatshahi1998** [comment]
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

This is the way in which you can use this function in tensorflow 2.x.

**Comment by ericpts** [comment]
But then will the rest of my code work? Since it is written in the 2.0 API?

**Comment by shashvatshahi1998** [comment]
pip install --upgrade tb-nightly
try this for upgrading tb nightly and then run your initial code.

**Comment by ericpts** [comment]
I can confirm that this fixed the problem!

With `tb-nightly` version `1.14.0a20190319`, the code now runs correctly.

Thank you very much for the help :)
