### ISSUE TITLE
[MMAP allocation] Error compilation for Window 10 using MVSC 2017

### ISSUE THREAD

**Issue by Arritmic** [tensorflow/tensorflow#27319]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Windows 10 Pro
- TensorFlow installed from: source
- TensorFlow version: 1.12.0
- Python version: No
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): MVSC 2017
- CUDA/cuDNN version: No
- GPU model and memory: No
- IDE: Qt 4.8,2
- Build system: Cmake 3.14

**Describe the problem**
Trying to compile Tensorflow Lite for Windows I am having the next error in the lines 17 and 20 of the file <em>mmap_allocation.cc</em>: 
- `sys/mman.h no such file or directory`
-` unistd.h file not found `

<img width="1920" alt="error_tflite" src="https://user-images.githubusercontent.com/9532966/55277989-1301a300-530f-11e9-9621-86144bd2e34e.png">

**Comment by ymodak** [comment]
We no longer officially support the cmake build, and suggest that you use bazel instead: https://www.tensorflow.org/install/source_windows

**Comment by Arritmic** [comment]
Okey, thank you for the info. Let's start with Bazel.
Apart from that, I solved the problem by setting CXX17 like below is shown:
   ```
 set_property(TARGET tensorflow-lite PROPERTY CXX_STANDARD 17)
    set_property(TARGET tensorflow-lite PROPERTY CXX_STANDARD_REQUIRED ON)
```
