### ISSUE TITLE
import results in Recursion-Error

### ISSUE THREAD

**Issue by jaba166** [tensorflow/tensorflow#27312]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
    `import tensorflow`
    `import kivy`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Windows 10
- TensorFlow installed from (source or binary): pip install (I guess it's binary)
- TensorFlow version (use command below): v1.12.0-9492-g2c319fb415, 2.0.0-alpha0
- Python version: 3.7 (Anaconda Win64)
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
Hundreds of messages ` WARNING: Logging before flag parsing goes to stderr.`, finally `RecursionError: maximum recursion depth exceeded while calling a Python object`. Output attached here: [tst.txt](https://github.com/tensorflow/tensorflow/files/3025303/tst.txt)

**Describe the expected behavior**
- no error by importing both packages
- independent behaviour from the order of imports

**Code to reproduce the issue**

    import tensorflow
    import kivy
order is important. kivy version is 1.10.1 - not sure if installed by pip or conda...

**Other info / logs**

Seems to be an issue with incompatible setup of `logging` - but as the error is raised in Tensorflow code, that's where it needs to be fixed.

**Comment by jvishnuvardhan** [comment]
@jaba166 Is there any error if you run only "import tensorflow". Were you able to import each of those two packages separately. It might be an issue from kivy package as all error log points to kivy.  It is better to post in kivy repo [here](https://github.com/kivy/kivy/issues). Thanks!

**Comment by jaba166** [comment]
I can import each one separately, no problem. I can also import them in the
other order.

I can also import kivy with the latest tensorboard 1 without issues in any
order. That alone clearly indicates a tensorflow2 issue.

In addition, if you look at the recursion error traceback its tensorflow2
creating the unbounded recursion.

Even if kivy would do sth wrong, its not correct that tensorflow2 is
entering a loop. And tf1 didn't.

jjm


Vishnuvardhan Janapati <notifications@github.com> schrieb am Di., 2. Apr.
2019, 23:40:

**Comment by jaba166** [comment]
not sure if the build/install tag is correct as the package is correctly built and installed. Instead it seems the initialization of the `logging` module the culprit.

**Comment by annarev** [comment]
This also happens with tf-nightly and seems to do with absl library that we depend on:
https://github.com/abseil/abseil-py

**Comment by SmartWaddles** [comment]
Hello, everyone. Just checked - kivy with  tensorflow==1.13.0rc0 works fine. 
If I'm trying to use it with tensorflow-1.14.0, I'm getting the following error:
Hundreds of messages WARNING: Logging before flag parsing goes to stderr. 
and recursion limit exceeding error after that.
Both packages are installed via PIP in Anaconda environment. I hope it will help someone.

**Comment by rmothukuru** [comment]
@jaba166,
Your code could be executed successfully, without any error. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/49a05fb1caf13edcc1c1aa7dd3d74c55/gh_27312.ipynb) of the working code. Thanks!

**Comment by jaba166** [comment]
Works in tensorflow 2.4.1 - thanks!
