### ISSUE TITLE
Please add "Abandon 996" badge in this project to support us.

### ISSUE THREAD

**Issue by firedom** [tensorflow/tensorflow#27317]
---------------------------
- Add this [badge](https://github.com/996icu/996.ICU/blob/master/externals/instruction.md) - to your project to support 996.ICU.  
- 把这个[徽章](https://github.com/996icu/996.ICU/blob/master/externals/instruction.md)加入你的项目来支持996.ICU
![https://996.icu](https://img.shields.io/badge/link-996.icu-red.svg)
--------------------------------------------
Chinese software engineers are protesting against the country ’ s 996 work schedule.
An unleagal work schedule (9a.m. ~ 9p.m., 6 days a week) .
Search 996.icu to support us !!

中国的程序员正在网上发起反抗 996 工作制的运动
“ 996 ”工作制，即每天早 9 点到岗，一直工作到晚上 9 点，每周工作 6 天。
请搜索 996.icu 支持我们 ！
---------------------------
# Working Men of All developers, Unite!

**Comment by bofeiw** [comment]
Please support us.

**Comment by mwsht** [comment]
illegal not unleagal.

**Comment by Naville** [comment]
I guess human evolution left some individuals behind.

Damn : (

**Comment by ewilderj** [comment]
TensorFlow issues isn't the right place for this discussion.
