### ISSUE TITLE
Feature Request: Exporting Model to Eigen Only Environments

### ISSUE THREAD

**Issue by raddy** [tensorflow/tensorflow#2731]
This would be insanely useful. I understand that some operations don't map cleanly to Eigen operations. 

[https://github.com/riga/tfdeploy](https://github.com/riga/tfdeploy) addresses a similar goal and has a reasonable approach to handle custom ops. 

An API where the eigen only computational graph is generated and the ability to "plug in" missing ops?

**Comment by prb12** [comment]
Given limited resources, this is not something which we are currently planning to work on.
