### ISSUE TITLE
TFLite delegates/gpu/libmetal_delegate.a is missing

### ISSUE THREAD

**Issue by willbattel** [tensorflow/tensorflow#27325]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave (10.14.1)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Not installed.
- TensorFlow version: master branch (latest commit 6353d940289a225cfbc104cc647b3c6970077faa)
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?: Not installed, just calling shell scripts from repo
- Bazel version (if compiling from source): 0.18.0
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Attempting to build iOS Metal TFLite Delegate with `create_ios_frameworks.sh` yields the following error:

```
$ tensorflow/lite/lib_package/create_ios_frameworks.sh -g
Starting
File /path/to/tensorflow/tensorflow/lite/lib_package/../delegates/gpu/libmetal_delegate.a doesn't exist.
It's requried for building TFLite Framework with GPU. Aborting.
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

This is how I am attempting to create the iOS framework:
```
$ tensorflow/lite/tools/make/download_dependencies.sh
$ tensorflow/lite/tools/make/build_ios_universal_lib.sh
$ tensorflow/lite/lib_package/create_ios_frameworks.sh -g
```

I saw that the `-g` flag got added to `create_ios_frameworks.sh` in 59d535a0df17eaf3033bbff73ef4e1e1988c454e. Without the flag, I am able to successfully build the framework but, as expected, the GPU is not utilized.

I know the GPU delegates only got open-sourced a couple of days ago, and before that I had unsurprisingly been getting the same error but with `metal_delegate.h`, which was added in fb772b781b011471dec443e1f3cd6b664958b767. Is `libmetal_delegate.a` supposed to be present or is it still pending open-sourcing?

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

N/A

**Comment by freedomtan** [comment]
With one line modification to
```diff
diff --git a/tensorflow/lite/delegates/gpu/metal_delegate.mm b/tensorflow/lite/delegates/gpu/metal_delegate.mm
index 66bfb043e5..b71881b73f 100644
--- a/tensorflow/lite/delegates/gpu/metal_delegate.mm
+++ b/tensorflow/lite/delegates/gpu/metal_delegate.mm
@@ -23,7 +23,7 @@
 #include <string>
 #include <vector>
 
-#include "third_party/absl/types/span.h"
+#include "absl/types/span.h"
 #include "tensorflow/lite/builtin_ops.h"
 #include "tensorflow/lite/c/c_api_internal.h"
 #include "tensorflow/lite/delegates/gpu/common/convert.h"
```

With something like
```bash
bazel build --apple_platform_type ios --ios_multi_cpus=arm64 \
tensorflow/lite/delegates/gpu:metal_delegate
```
you can get arm64 `bazel-tensorflow/bazel-out/apl-ios_arm64-opt/bin/tensorflow/lite/delegates/gpu/libmetal_delegate.a`.

**Comment by willbattel** [comment]
@freedomtan thank you, your solution did work. After modifying `metal_delegate.mm` I was able to build `libmetal_delegate.a` which allowed `create_ios_frameworks.sh` to run with the `-g` flag.

This issue should probably remain open until this workaround is no longer necessary.

**Comment by freedomtan** [comment]
I sent a PR just now :-)

**Comment by weinixuehao** [comment]
@fredbertsch 
![image](https://user-images.githubusercontent.com/17869361/59912414-8e737c00-9448-11e9-8e6a-04ecb53303f2.png)

![image](https://user-images.githubusercontent.com/17869361/59912439-97fce400-9448-11e9-9acf-c8d408694f3b.png)

what was wrong ?

**Comment by freedomtan** [comment]
@weinixuehao How did you build your `libmeta_delegate.a`? iPhone emulator is x86_64 based, make sure you have x86_64 stuff in it.

**Comment by weinixuehao** [comment]
@freedomtan 
I built with below commands
![image](https://user-images.githubusercontent.com/17869361/60001804-ddfcb680-9699-11e9-97e9-2285c27e62de.png)
arm64 and x86_64 is ok but i need armv7 armv7s as my xcode project valid architecture is 
![image](https://user-images.githubusercontent.com/17869361/60001879-0edceb80-969a-11e9-9f8b-233b304b18c0.png)

**Comment by freedomtan** [comment]
interesting, why do you need 32-bit binaries? iPhone 6s has 64-bit CPUs. I think you can simply remove armv7 and armv7s. Anyway, something like 
```
build --apple_platform_type ios --ios_multi_cpus=armv7 
//tensorflow/lite/delegates/gpu:metal_delegate 
```
should work. And as far as I can remember bazel doesn't support armv7s.

**Comment by weinixuehao** [comment]
@freedomtan
I am newbie to ios and tensorflowlite binary like 
![image](https://user-images.githubusercontent.com/17869361/60025814-ffc36100-96cc-11e9-8b59-b23825a1f983.png)
So i am worried the following two problems.
1、if metal_delegate binary only arm64 will cause compilation problems? 
2、iphone5 has 32-bit CPUS will cause crash problems?

Why tensorflowlite has armv7, armv7s, arm64 ... but metal_delegate only has arm64 is OK? 
I`m very puzzled!

**Comment by freedomtan** [comment]
I don't think Metal (the API) supports iOS devices older than A7 (iPhone 5s). That is, there is no reason to worry about iPhone 5 (A6).

**Comment by weinixuehao** [comment]
@freedomtan
Thanks! 
Please help me debug this issue If you have enough time.
https://github.com/tensorflow/tensorflow/issues/29864

**Comment by weinixuehao** [comment]
@freedomtan 
It need too many dependency libs after reference metal lib otherwise throw undefined symbol ...
Why bazel do not merge to one lib after built successfully? Maybe bazel has this option but i do not know
![image](https://user-images.githubusercontent.com/17869361/60067704-4dc47d00-973e-11e9-9b5b-910ca61a1492.png)

**Comment by LK** [comment]
@weinixuehao instead of building the bazel target `metal_delegate`, build `metal_delegate_fully_linked.a` — this gives you a single archive file with all dependencies included. https://docs.bazel.build/versions/master/be/objective-c.html#objc_library_implicit_outputs

**Comment by thameslu** [comment]
> With one line modification to
> 
> ```diff
> diff --git a/tensorflow/lite/delegates/gpu/metal_delegate.mm b/tensorflow/lite/delegates/gpu/metal_delegate.mm
> index 66bfb043e5..b71881b73f 100644
> --- a/tensorflow/lite/delegates/gpu/metal_delegate.mm
> +++ b/tensorflow/lite/delegates/gpu/metal_delegate.mm
> @@ -23,7 +23,7 @@
>  #include <string>
>  #include <vector>
>  
> -#include "third_party/absl/types/span.h"
> +#include "absl/types/span.h"
>  #include "tensorflow/lite/builtin_ops.h"
>  #include "tensorflow/lite/c/c_api_internal.h"
>  #include "tensorflow/lite/delegates/gpu/common/convert.h"
> ```
> 
> With something like
> 
> ```shell
> bazel build --apple_platform_type ios --ios_multi_cpus=arm64 \
> tensorflow/lite/delegates/gpu:metal_delegate
> ```
> 
> you can get arm64 `bazel-tensorflow/bazel-out/apl-ios_arm64-opt/bin/tensorflow/lite/delegates/gpu/libmetal_delegate.a`.

I run the command below : 

```
bazel build --apple_platform_type ios --ios_multi_cpus=arm64 \
tensorflow/lite/delegates/gpu:metal_delegate
```
but there is an error like this :
 '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'ios_arm64'

Could you tell me how to fix it ? thx a lot

**Comment by sanjoy** [comment]
> Could you tell me how to fix it ? thx a lot

Looks like this is a question for @freedomtan ?

> @freedomtan thank you, your solution did work. After modifying `metal_delegate.mm` I was able to build `libmetal_delegate.a` which allowed `create_ios_frameworks.sh` to run with the `-g` flag.
> 
> This issue should probably remain open until this workaround is no longer necessary.

The workaround is [no longer necessary](https://github.com/tensorflow/tensorflow/blob/a592eff24bdae523970ec636d38d8c6b221de40a/tensorflow/lite/delegates/gpu/metal_delegate.mm#L29) so I'm closing the issue.

**Comment by freedomtan** [comment]
@sanjoy oops, didn't notice that. 

@thameslu in case didn't find the solution yet, I think you probably need to "run the `./configure` script in the root TensorFlow checkout directory, and answer "Yes" when the script asks if you wish to build TensorFlow with iOS support", as described in the [build TF Lite for iOS](https://www.tensorflow.org/lite/guide/build_ios#configure_workspace_and_bazelrc) guide

**Comment by thameslu** [comment]
> ensorFlow with iOS support", as described in the [build TF Lite for iOS](https://www.tensorflow.org/lite/guide/build_ios#configure_workspace_and_bazelrc) guide

thank you, i will have a try @sanjoy  @freedomtan

**Comment by lei522** [comment]
@thameslu hi, How did you solve the problem? when i use metal delegate on ios i have the similar problem as follow,
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_TFLInferenceContext", referenced from:
      objc-class-ref in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::BuildModel(TfLiteContext*, TfLiteDelegateParams const*, tflite::gpu::Model<tflite::gpu::TensorRef<tflite::gpu::StrongShape<(tflite::gpu::Layout)10> > >*)", referenced from:
      tflite::gpu::metal::(anonymous namespace)::DelegatePrepare(TfLiteContext*, TfLiteDelegate*)::$_1::__invoke(TfLiteContext*, char const*, unsigned long) in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "_OBJC_CLASS_$_TFLBufferConvert", referenced from:
      objc-class-ref in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::GetOpsToReplace(TfLiteContext*)", referenced from:
      tflite::gpu::metal::(anonymous namespace)::DelegatePrepare(TfLiteContext*, TfLiteDelegate*) in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::GetElementsSizeForPHWC4(tflite::gpu::StrongShape<(tflite::gpu::Layout)10> const&)", referenced from:
      tflite::gpu::metal::(anonymous namespace)::DelegatePrepare(TfLiteContext*, TfLiteDelegate*)::$_1::__invoke(TfLiteContext*, char const*, unsigned long) in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::metal::ValidateOptimizeModel(std::__1::vector<unsigned int, std::__1::allocator<unsigned int> > const&, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> > const&, std::__1::vector<std::__1::shared_ptr<tflite::gpu::metal::ComputeTaskDescriptor>, std::__1::allocator<std::__1::shared_ptr<tflite::gpu::metal::ComputeTaskDescriptor> > > const&, std::__1::vector<std::__1::shared_ptr<tflite::gpu::metal::ComputeTaskDescriptor>, std::__1::allocator<std::__1::shared_ptr<tflite::gpu::metal::ComputeTaskDescriptor> > >*)", referenced from:
      tflite::gpu::metal::(anonymous namespace)::DelegatePrepare(TfLiteContext*, TfLiteDelegate*)::$_1::__invoke(TfLiteContext*, char const*, unsigned long) in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::ApplyGeneralTransformations(tflite::gpu::ModelTransformer*)", referenced from:
      tflite::gpu::metal::(anonymous namespace)::DelegatePrepare(TfLiteContext*, TfLiteDelegate*)::$_1::__invoke(TfLiteContext*, char const*, unsigned long) in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::metal::Compile(tflite::gpu::Model<tflite::gpu::TensorRef<tflite::gpu::StrongShape<(tflite::gpu::Layout)10> > > const&, tflite::gpu::metal::RuntimeOptions const&, std::__1::vector<std::__1::shared_ptr<tflite::gpu::metal::ComputeTaskDescriptor>, std::__1::allocator<std::__1::shared_ptr<tflite::gpu::metal::ComputeTaskDescriptor> > >*)", referenced from:
      tflite::gpu::metal::(anonymous namespace)::DelegatePrepare(TfLiteContext*, TfLiteDelegate*)::$_1::__invoke(TfLiteContext*, char const*, unsigned long) in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::metal::CreateComputeProgram(id<MTLDevice>, NSString*, NSString, NSDictionary<NSString, NSString>*, id<MTLComputePipelineState> __autoreleasing*)", referenced from:
      _TFLGpuDelegateCreate in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

and i have tried this,
	 tensorflow-1.15.4 % lipo -info tensorflow/lite/gen/ios_frameworks/tensorflow_lite_gpu.framework/libmetal_delegate.a 
Non-fat file: tensorflow/lite/gen/ios_frameworks/tensorflow_lite_gpu.framework/libmetal_delegate.a is architecture: arm64

could you help me build the metal delegate framework correctly and run the tflite model with gpu on iphone?

**Comment by lei522** [comment]
@thameslu ，hi，How did you solve the problem? when i use metal delegate on ios i have the similar problem as follow,

`_OBJC_CLASS_$_TFLInferenceContext", referenced from:
      objc-class-ref in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::BuildModel(TfLiteContext*, TfLiteDelegateParams const*, tflite::gpu::Model<tflite::gpu::TensorRef<tflite::gpu::StrongShape<(tflite::gpu::Layout)10> > >*)", referenced from:
      tflite::gpu::metal::(anonymous namespace)::DelegatePrepare(TfLiteContext*, TfLiteDelegate*)::$_1::__invoke(TfLiteContext*, char const*, unsigned long) in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "_OBJC_CLASS_$_TFLBufferConvert", referenced from:
      objc-class-ref in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::GetOpsToReplace(TfLiteContext*)", referenced from:
      tflite::gpu::metal::(anonymous namespace)::DelegatePrepare(TfLiteContext*, TfLiteDelegate*) in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::GetElementsSizeForPHWC4(tflite::gpu::StrongShape<(tflite::gpu::Layout)10> const&)", referenced from:
      tflite::gpu::metal::(anonymous namespace)::DelegatePrepare(TfLiteContext*, TfLiteDelegate*)::$_1::__invoke(TfLiteContext*, char const*, unsigned long) in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::metal::ValidateOptimizeModel(std::__1::vector<unsigned int, std::__1::allocator<unsigned int> > const&, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> > const&, std::__1::vector<std::__1::shared_ptr<tflite::gpu::metal::ComputeTaskDescriptor>, std::__1::allocator<std::__1::shared_ptr<tflite::gpu::metal::ComputeTaskDescriptor> > > const&, std::__1::vector<std::__1::shared_ptr<tflite::gpu::metal::ComputeTaskDescriptor>, std::__1::allocator<std::__1::shared_ptr<tflite::gpu::metal::ComputeTaskDescriptor> > >*)", referenced from:
      tflite::gpu::metal::(anonymous namespace)::DelegatePrepare(TfLiteContext*, TfLiteDelegate*)::$_1::__invoke(TfLiteContext*, char const*, unsigned long) in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::ApplyGeneralTransformations(tflite::gpu::ModelTransformer*)", referenced from:
      tflite::gpu::metal::(anonymous namespace)::DelegatePrepare(TfLiteContext*, TfLiteDelegate*)::$_1::__invoke(TfLiteContext*, char const*, unsigned long) in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::metal::Compile(tflite::gpu::Model<tflite::gpu::TensorRef<tflite::gpu::StrongShape<(tflite::gpu::Layout)10> > > const&, tflite::gpu::metal::RuntimeOptions const&, std::__1::vector<std::__1::shared_ptr<tflite::gpu::metal::ComputeTaskDescriptor>, std::__1::allocator<std::__1::shared_ptr<tflite::gpu::metal::ComputeTaskDescriptor> > >*)", referenced from:
      tflite::gpu::metal::(anonymous namespace)::DelegatePrepare(TfLiteContext*, TfLiteDelegate*)::$_1::__invoke(TfLiteContext*, char const*, unsigned long) in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
  "tflite::gpu::metal::CreateComputeProgram(id<MTLDevice>, NSString*, NSString, NSDictionary<NSString, NSString>*, id<MTLComputePipelineState> __autoreleasing*)", referenced from:
      _TFLGpuDelegateCreate in libmetal_delegate.a(metal_delegate_bf7d4aad90502bdf5c67c8a69622de9d.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

and i have tried this,
tensorflow-1.15.4 % lipo -info tensorflow/lite/gen/ios_frameworks/tensorflow_lite_gpu.framework/libmetal_delegate.a
Non-fat file: tensorflow/lite/gen/ios_frameworks/tensorflow_lite_gpu.framework/libmetal_delegate.a is architecture: arm64

could you help me build the metal delegate framework correctly and run the tflite model with gpu on iphone?
