### ISSUE TITLE
Add a "tf.contrib.*" warning to tf_upgrade_v2 upgrade script

### ISSUE THREAD

**Issue by yselivonchyk** [tensorflow/tensorflow#27340]
Tensorflow 1.13 and 2.0 come with the support of tf_upgrage_v2 script.
The script ignores imports and usage of parts of tf.contrib.* package that is no longer available in TF2.0. Due to that converted script fails with "_ModuleNotFoundError: No module named 'tensorflow.contrib'_". I suggest adding a user warning/error to the script to notify the user about incompatible library being used.

**Comment by shashvatshahi1998** [comment]
i opened tf_upgrade_v2 script and found that there is a warning already:
 contrib_warning = (
        ast_edits.ERROR,
        "<function name> cannot be converted automatically. tf.contrib will not"
        " be distributed with TensorFlow 2.0, please consider an alternative in"
        " non-contrib TensorFlow, a community-maintained repository, or fork "
        "the required code."
)

**Comment by yselivonchyk** [comment]
You are right. At the very least, it should be a bug and not a feature request then.

Yet, after reinstalling TF `pip install --upgrade tf-nightly-2.0-preview` just now and running` tf_upgrade_v2 --infile WhatWhereAutoencoder.py --outfile test.py` on a script containing lines like `import tensorflow.contrib.slim as slim` or  `slim.conv2d(input, 16, [5, 5])` I got no warning.

**Comment by shashvatshahi1998** [comment]
Then we have to add that warning at its correct location from where that warning become effective.

**Comment by armando-fandango** [comment]
> i opened tf_upgrade_v2.py and found that there is a warning already:
> contrib_warning = (
> ast_edits.ERROR,
> " cannot be converted automatically. tf.contrib will not"
> " be distributed with TensorFlow 2.0, please consider an alternative in"
> " non-contrib TensorFlow, a community-maintained repository, or fork "
> "the required code."
> )

For the features moved to other repos such as `probability` or `addons`, the upgrade script can probably give more information regarding where the feature has been moved to.

**Comment by ymodak** [comment]
@yselivonchyk Apologies for the delay in response.  If you change ```slim.conv2d(input, 16, [5, 5])``` to ```tensorflow.contrib.slim.conv2d(input, 16, [5, 5])``` the required warning message will be triggered.
