### ISSUE TITLE
benchmark_model is much slower than expected

### ISSUE THREAD

**Issue by georgeokelly** [tensorflow/tensorflow#27346]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: MI 8
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 
- Python version: 2.7
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
I use the benchmark_model to run the inference of models with tflite, but the speed of Mobilenet is rather slow on Snapdragon 845, which is nearly **166 ms**. (According to the [performance site](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/benchmarks.md), I expect that it could run faster than 100 ms.) I wonder whether it is built with NEON or not, and is there anything else I should do to make this problem fixed.

```
adb shell /data/local/tmp/benchmark_model  --graph=/data/local/tmp/tflite_model/mobilenet_v1_1.0_224.tflite   --num_threads=4 --warmup_runs=3 --num_runs=50 --use_nnapi=true
STARTING!
Min num runs: [50]
Min runs duration (seconds): [1]
Inter-run delay (seconds): [-1]
Num threads: [4]
Benchmark name: []
Output prefix: []
Min warmup runs: [3]
Min warmup runs duration (seconds): [0.5]
Graph: [/data/local/tmp/tflite_model/mobilenet_v1_1.0_224.tflite]
Input layers: []
Input shapes: []
Use nnapi : [1]
Allow fp16 : [0]
nnapi error: unable to open function ANeuralNetworksModel_relaxComputationFloat32toFloat16
Loaded model /data/local/tmp/tflite_model/mobilenet_v1_1.0_224.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
Initialized session in 175.762ms
Running benchmark for at least 3 iterations and at least 0.5 seconds
count=4 first=157773 curr=166340 min=155120 max=170646 avg=162470 std=6283

Running benchmark for at least 50 iterations and at least 1 seconds
count=50 first=173787 curr=167988 min=151156 max=179750 avg=166446 std=6661

Average inference timings in us: Warmup: 162470, Init: 175762, no stats: 166446
```

**Describe the expected behavior**
The speed of Mobilenet's inference on Snapdragon 845 is expected faster than 100 ms. And how could I know whether the benchmark is built with NEON or not?

**Code to reproduce the issue**
1. `git clone --recurse-submodules https://github.com/tensorflow/tensorflow.git`
2. 
```
./configure 
You have bazel 0.22.0 installed.
Please specify the location of python. [Default is /usr/bin/python]: 

Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.

Do you wish to build TensorFlow with MPI support? [y/N]: n
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: -march='armv8-a' -mfpu='neon'

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: y
Searching for NDK and SDK installations.

Please specify the home path of the Android NDK to use. [Default is /home/tfl/Android/Sdk/ndk-bundle]: 

Please specify the home path of the Android SDK to use. [Default is /home/tfl/Android/Sdk]: 

Please specify the Android SDK API level to use. [Available levels: ['26', '27', '28']] [Default is 28]: 27

Please specify an Android build tools version to use. [Available versions: ['26.0.3', '27.0.3', '28.0.3']] [Default is 28.0.3]: 27.0.3

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=gdr         	# Build with GDR support.
	--config=verbs       	# Build with libverbs support.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=noignite    	# Disable Apache Ignite support.
	--config=nokafka     	# Disable Apache Kafka support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished
```
3. 
```
bazel build -c opt \
  --config=android_arm64 \
  --cxxopt='--std=c++11' \
  tensorflow/lite/tools/benchmark:benchmark_model
```
4. 
```
adb push bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model /data/local/tmp
adb shell chmod +x /data/local/tmp/benchmark_model
adb shell /data/local/tmp/benchmark_model  --graph=/data/local/tmp/tflite_model/mobilenet_v1_1.0_224.tflite   --num_threads=4 --warmup_runs=3 --num_runs=50 --use_nnapi=true
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by freedomtan** [comment]
@georgeokelly what do you want check measure? TFLite interpreter CPU time, just like the [performance page](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/benchmarks.md) you referred to? If yes, 

1. don't use `--use_nnapi=true`
2. you may want to use `taskset` as suggested in the performance page

**Comment by georgeokelly** [comment]
Hi @freedomtan I am measuring the inference time with CPU only. I also tried with `--use_nnapi=true` or `taskset` but it didn't help. At last I do what described on [benchmark/android](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/android/README.md) and it works (which means the run time is about 44 ms rather than 166 ms using mobilenet v1). Now I am little confused that when use 
```
bazel build -c opt \
  --config=android_arm64 \
  --cxxopt='--std=c++11' \
  tensorflow/lite/tools/benchmark/android:benchmark_model
```
instead of 
```
bazel build -c opt \
  --config=android_arm64 \
  --cxxopt='--std=c++11' \
  tensorflow/lite/tools/benchmark:benchmark_model
```
the inference time of the same model is quite different, like one is built with NEON while the other is not.

**Comment by freedomtan** [comment]
@georgeokelly I mean don't use `--use_nnapi=true`. Anyway, you are comparing two difference models. What described in the  [benchmark/android](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/android/README.md) page is to benchmark a quantized model (`mobilenet_quant_v1_224.tflite`) and what you described above is to benchmark floating point model (`mobilenet_v1_1.0_224.tflite`).

**Comment by georgeokelly** [comment]
@freedomtan  I mean I have tried many commands with `--use_nnapi=true` or without that, but it makes little difference for me because the time is always more than 100 ms. BTW, to make it clear, here is my testing result.

model|time1|time2
:--:|:--:|:--:
mobilenet|~160 ms|~40 ms
mobilenet_quant|~60 ms|~20 ms

time1 is tested by benchmark:benchmark_model
time2 is tested by android:benchmark_model

My device is MI 8 with snapdragon 845 and time2 is exactly what I expect, and now you could see the difference.

**Comment by freedomtan** [comment]
FYR, on Pixel 2 (snapdragon 835),
- `taskset f0 ./benchmark_model --graph=mobilenet_v1_1.0_224_quant.tflite --num_threads=4`: ~ 20 ms
- `taskset f0 ./benchmark_model --graph=mobilenet_v1_1.0_224_quant.tflite --num_threads=1`: ~ 60 ms

The `benchmark_model` is built with
```
bazel build --config=android_arm64 tensorflow/lite/tools/benchmark:benchmark_model
```

If your results are much worse than what I got, either your system or something in TFLite is wrong (it seems there are some ongoing TFLite kernel rewriting/optimization recently).

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
