### ISSUE TITLE
RNN: tensorflow.python.framework.errors.InvalidArgumentError: indices[15,0] = 10535 is not in [0, 10000)

### ISSUE THREAD

**Issue by mrgreen7** [tensorflow/tensorflow#2734]
Hey. I adapted the example file (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/ptb_word_lm.py) to work on my training data. Unfortunately as soon as the training data exceeds a certain size I'm getting an error: http://pastebin.com/JkV7MCQk What could be the issue? How can I debug this?

Might it be an issue with the training data? (http://s000.tinyupload.com/index.php?file_id=02347215266721316111)

**Comment by mrgreen7** [comment]
Hey. Just saw that the vocabulary size is a parameter you have to define manually? Seems not very intuitive for me as it can be computed automatically.

**Comment by hauluk** [comment]
Hello! How do you get rid of these error? It seems I run into the same problem. Maybe you can share your experience ?

**Comment by tkngoutham** [comment]
@hauluk  from the above comment we can see that we must calculate size of vocabulary explicitly and then supply it as parameter, then we will not get this error. :).

**Comment by hauluk** [comment]
The problem was the trained model can't find the word in the embedding matrix. That means I used a different vocabulary for training and prediction. Because of the fixed vocabulary I needed the same vocabulary for train and new data.

**Comment by jakedailey1** [comment]
+1 for anyone using labels originated in another language (like Lua, R) that count or index starting with 1

**Comment by yufengzhixing** [comment]
I got the same problem,and I have get the right answer.Thank you!

**Comment by shijial** [comment]
@yufengzhixing 
I got the same problem, but I haven't solved the problem. Could you share your solution? Thank you!

**Comment by hauluk** [comment]
Hi!

I didn't used the same data set for predicting and training. That was my
solution.

Hope i could help you.

Am 25.07.2017 3:24 vorm. schrieb "shijial" <notifications@github.com>:

**Comment by huangbiubiu** [comment]
Why not calculate `vocab_size` automatically? Are there any reasons?

**Comment by apohl1111** [comment]
It's also worth noting that I get a similar error if the vocab.tags.txt doesn't contain "O", even if the training doesn't use "O".

**Comment by fooSynaptic** [comment]
for ngram model this will yield tremendous headaches exception for ngram-map was store in the model parameter, you cannot even delete the related tuples.
