### ISSUE TITLE
Building tensorflow wheel met error `clang: error: no input files`

### ISSUE THREAD

**Issue by a6802739** [tensorflow/tensorflow#27342]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
 Darwin Kernel Version 18.0.0, Mac OS 10.14
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from:
build from source
- TensorFlow version:
Master branch
- Python version:
2.7
- Installed using virtualenv? pip? conda?:
No
- Bazel version (if compiling from source):
0.23.2
- GCC/Compiler version (if compiling from source):
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
- CUDA/cuDNN version:
without it
- GPU model and memory:
without GPU.

**Describe the problem**
I want to build tensorflow from source, use command:
```
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
```
And here is result:
```
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 5926.109s, Critical Path: 623.43s
INFO: 10670 processes: 10670 local.
INFO: Build completed successfully, 11295 total actions
```
Then I try to build the `wheel`, use command:
```
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
```
But got error:
```
warning: no files found matching '*.pyd' under directory '*'
warning: no files found matching '*.pd' under directory '*'
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
warning: no files found matching '*.h' under directory 'tensorflow/include/tensorflow'
warning: no files found matching '*' under directory 'tensorflow/include/Eigen'
warning: no files found matching '*.h' under directory 'tensorflow/include/google'
warning: no files found matching '*' under directory 'tensorflow/include/third_party'
warning: no files found matching '*' under directory 'tensorflow/include/unsupported'
clang: error: no input files
error: command 'clang' failed with exit status 1
```

**Comment by ymodak** [comment]
@a6802739 Apologies for the delay in response. Is this still an issue? Thanks!

**Comment by a6802739** [comment]
@ymodak, it's fixed now.

**Comment by ymodak** [comment]
That's great to hear. Can you please share your solution? It may help other users coming across this issue in the future. Thanks!
