### ISSUE TITLE
-D_GLIBCXX_DEBUG compiler flag causes prediction failure

### ISSUE THREAD

**Issue by seanxhughes** [tensorflow/tensorflow#27357]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**

- OS Platform and Distribution Linux Ubuntu 18.04
- TensorFlow installed from source: v1.13.1
- Bazel version 0.21
- GCC/Compiler version: gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 

**Describe the current behavior**

-D_GLIBCXX_DEBUG compiled example code gives:

Invalid argument: Must specify at least one target to fetch or execute.

Compiled without this flag:

Run session successfully
Tensor<type: float shape: [] values: 6>
output value: 6

**Code to reproduce the issue**

#include <tensorflow/core/platform/env.h>
#include <tensorflow/core/public/session.h>
#include <iostream>

int main(int argc, char **argv)
{

    tensorflow::GraphDef GraphDef;
    tensorflow::Session* Session = nullptr;
    tensorflow::Status Status;

    Status = tensorflow::ReadBinaryProto(tensorflow::Env::Default(), argv[1], &GraphDef);
    if (!Status.ok())
    {
      printf("Error reading graph definition from %s: %s\n", argv[1], Status.ToString().c_str());
      return false;
    }

    Session = tensorflow::NewSession(tensorflow::SessionOptions());
    if (Session == nullptr)
    {
      printf("Could not create Tensorflow session.\n");
      return false;
    }

    Status = Session->Create(GraphDef);
    if (!Status.ok())
    {
      printf("Error creating graph: %s\n", Status.ToString().c_str());
      return false;
    }

    //predict

    tensorflow::Tensor a(tensorflow::DT_FLOAT, tensorflow::TensorShape());
    a.scalar<float>()() = 3.0;

    tensorflow::Tensor b(tensorflow::DT_FLOAT, tensorflow::TensorShape());
    b.scalar<float>()() = 2.0;

    std::vector<std::pair<std::string, tensorflow::Tensor>> inputs = {
      { "a", a },
      { "b", b },
    };

    std::vector<tensorflow::Tensor> outputs;

    auto status = Session->Run(inputs, {"c"}, {}, &outputs);
    if (!status.ok()) {
      std::cerr << status.ToString() << std::endl;
      return 1;
    } else {
      std::cout << "Run session successfully" << std::endl;
    }

    auto output_c = outputs[0].scalar<float>();
    std::cout << outputs[0].DebugString() << std::endl;
    std::cout << "output value: " << output_c() << std::endl;
    Session->Close();

    return 0;
}

**Other info / logs**

The simple graph file attached - supply its path as a command line argument
[graph.pb.gz](https://github.com/tensorflow/tensorflow/files/3027851/graph.pb.gz)

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by seanxhughes** [comment]
Hi,

Could you explain your comments please.

Did you manage to reproduce the problem. At the very least  the error message generated ("Invalid argument: Must specify at least one target to fetch or execute") is incorrect as when compiled without the debug flag the sample application executes cleanly, meaning these arguments were supplied as they are hard coded. 

If this is neither a bug or a feature request what is it ?

Thanks 

Sean
