### ISSUE TITLE
Broken link https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing

### ISSUE THREAD

**Issue by miguelangel** [tensorflow/tensorflow#27351]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: API r1.13
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing

**Describe the documentation issue**
A _404 - Page not found_ error is displayed when clicking on the link in the paragraph below:

> Additional documentation can be found [on the keras site](https://keras.io/preprocessing/), 

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by muddham** [comment]
@miguelangel Thanks for bringing this to our notice. We will take a look.

**Comment by wolffg** [comment]
This link has been removed.
