### ISSUE TITLE
Include TF in keras.models.load_model for custom functions

### ISSUE THREAD

**Issue by kmader** [tensorflow/tensorflow#27364]
**System information**
- TensorFlow version (you are using): Latest
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

```
from keras import models, layers
import tensorflow as tf
in_tensor = layers.Input((50, 1), name='InSpeech')
def sum_tensor(x):
  return tf.reduce_sum(x, 1)
sum_out = layers.Lambda(sum_tensor, name='SumTensor')(in_tensor)
k_model = models.Model(inputs=[in_tensor],
            outputs=[sum_out])
k_model.save('sum_model.h5')
```

Loading the model

```
models.load_model('sum_model.h5')
```

or 

```
tf.lite.TFLiteConverter.from_keras_model_file('sum_model.h5')
```

Results in the error message:
```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py in sum_tensor(x)
      3 in_tensor = layers.Input((50, 1), name='InSpeech')
      4 def sum_tensor(x):
----> 5   return tf.reduce_sum(x, 1)
      6 sum_out = layers.Lambda(sum_tensor, name='SumTensor')(in_tensor)
      7 k_model = models.Model(inputs=[in_tensor],

NameError: name 'tf' is not defined
```

While running `models.load_model('sum_model.h5', custom_objects={'tf': tf})` works fine. Unfortunately with the tflite wrapper function to convert models you cannot specify custom objects.

**Will this change the current api? How?**

No, it would just make the default custom objects include tensorflow.

**Who will benefit with this feature?**

Anyone using simple tensorflow-derived lambda functions inside of the HDF5 models in Keras. In particular people hoping to convert the models to tflite.

**Comment by ymodak** [comment]
Closing this issue based on the explanation given in corresponding PR. Feel free to reopen if have any further questions. Thanks!

**Comment by kmader** [comment]
@ymodak I have since commented on the PR, while the solution is correct it doesn't allow for saving models (as far as I can tell) with the keras hdf5 format. 

Another use case for the issue is with EfficientNet's use of `tf.nn.swish` which isn't available in keras
