### ISSUE TITLE
Installation error on Ubuntu 16.04 64bit machine - $(PYTHON_BIN_PATH) not defined.

### ISSUE THREAD

**Issue by maniteja123** [tensorflow/tensorflow#2736]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
```
uname -a
Linux ubuntu 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
CUDA not installed

If installed from sources, provide the commit hash:
https://github.com/tensorflow/tensorflow/commit/592675b2b8d1cabbf923638942ea6f200abe353a

### Steps to reproduce
1. Install the source using ``bazel build -c opt //tensorflow/tools/pip_package:build_pip_package``
2. The necessary packages are installed but the error `` in cmd attribute of genrule rule //tensorflow/contrib/session_bundle/example:half_plus_two: $(PYTHON_BIN_PATH) not defined. `` is raised.
3. The fork is on par with the upstream master.

### What have you tried?
1. Have tried to search for similar issues, but couldn't find anything. Please point to the correct issue in case I am missing some existing issue.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

```
Extracting Bazel installation...
.........
INFO: Waiting for response from Bazel server (pid 8938)...
WARNING: /home/maniteja/.cache/bazel/_bazel_maniteja/98850693c9ebf4963f7f6ed5da9dc97a/external/protobuf/WORKSPACE:1: Workspace name in /home/maniteja/.cache/bazel/_bazel_maniteja/98850693c9ebf4963f7f6ed5da9dc97a/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
WARNING: /home/maniteja/.cache/bazel/_bazel_maniteja/98850693c9ebf4963f7f6ed5da9dc97a/external/highwayhash/WORKSPACE:1: Workspace name in /home/maniteja/.cache/bazel/_bazel_maniteja/98850693c9ebf4963f7f6ed5da9dc97a/external/highwayhash/WORKSPACE (@__main__) does not match the name given in the repository's definition (@highwayhash); this will cause a build error in future versions.
WARNING: /home/maniteja/.cache/bazel/_bazel_maniteja/98850693c9ebf4963f7f6ed5da9dc97a/external/re2/WORKSPACE:1: Workspace name in /home/maniteja/.cache/bazel/_bazel_maniteja/98850693c9ebf4963f7f6ed5da9dc97a/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
WARNING: /home/maniteja/FOSS/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
ERROR: /home/maniteja/FOSS/tensorflow/tensorflow/contrib/session_bundle/example/BUILD:45:9: in cmd attribute of genrule rule //tensorflow/contrib/session_bundle/example:half_plus_two: $(PYTHON_BIN_PATH) not defined.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 1356.436s
```

Thanks for your time. Please let me know if any additional information is needed.

**Comment by girving** [comment]
Did you run `configure`?

**Comment by maniteja123** [comment]
Sorry my mistake. Thanks a lot. I didn't run ``configure`` this time though have been doing that when trying to install on 32 bit machine. Now it is building. Apologies for the noise.
