### ISSUE TITLE
tensorflow-gpu(1.13.1) tf.gradients()

### ISSUE THREAD

**Issue by INERKIDFYN** [tensorflow/tensorflow#27378]
I want to know where I'm wrong.

![捕获](https://user-images.githubusercontent.com/42964873/55328415-e3919880-54be-11e9-99e9-c6d61e445c53.PNG)
![捕获1](https://user-images.githubusercontent.com/42964873/55328494-0d4abf80-54bf-11e9-8beb-2734bc09f706.PNG)

**Comment by ppwwyyxx** [comment]
Your variables are of integer types (because you initialize them with integers) and mathematically there is no gradient defined on integer types so you cannot evaluate them.

This is expected.

**Comment by INERKIDFYN** [comment]
@ppwwyyxx Thank you very much!  The problem is solved.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks!
