### ISSUE TITLE
Docs load really slow 

### ISSUE THREAD

**Issue by JaspervDalen** [tensorflow/tensorflow#27379]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>
System information

    chrome
    Internet speed 120+ Mbps
    TensorFlow version: all
    Doc Link: all pages

It takes a really long time to load the docs. Navigating to another page can take 10+ seconds to load a new page.

**Comment by jvishnuvardhan** [comment]
@JaspervDalen It is really strange. 
1. Do you have any Firewall? It never took more than a second or two even with low internet speeds (6 Mbps download). 
2. Can you check with other browsers (IE, Firefox, Safari etc...)
3. typically how much it takes to open other websites (ex. news.google.com)

Please provide as many details as possible to find root-cause of the issue. Thanks!

**Comment by JaspervDalen** [comment]
@jvishnuvardhan now that I check it at home (I mostly use the tensorflow docs at work) it is a lot faster (about 3 seconds). But it is across machines (my colleagues also have the same issues) and across browsers. We haven't noticed any issues witha ny other websites. I will look tomorrow for a firewall or something.

**Comment by jvishnuvardhan** [comment]
@JaspervDalen Thanks for quick reply. Could you mention location (Europe, Asia, ...) from where you are accessing and also mention whether you notice any specific pages in [TF website](https://www.tensorflow.org/) that are taking more time than others. thanks!

**Comment by lamberta** [comment]
Pages with iframes can take longer to load (like the home page).
I've also noticed pages with lots of code snippets can take longer to fill in, but should start rendering quickly.
But, as Vishnuvardhan said, any specific pages and your region would be helpful it it's not an internal configuration issue.

**Comment by JaspervDalen** [comment]
@lamberta  It is really all pages, I can switch between all pages of the docs and all load in about 10 seconds. Today I looked at https://www.tensorflow.org/api_docs/python/tf/map_fn, https://www.tensorflow.org/api_docs/python/tf/meshgrid both really slow and https://www.tensorflow.org/api_docs/python/tf/range all took about 10 seconds. I work in Nijmegen (the netherlands), however my home is also in nijmegen (but another provider).

**Comment by JaspervDalen** [comment]
Ok after testing, it is mainly firefox 66.0.2 with ublock origin as add blocker (no other add-ons). In chrome it is a lot quicker (but still slow with about 2/3 seconds per loading of a page)

**Comment by jvishnuvardhan** [comment]
@JaspervDalen Last time you mentioned it took 10 seconds per page, and now it is taking 2/3 seconds per page. What did you change? Just curious. Thanks!

**Comment by JaspervDalen** [comment]
@jvishnuvardhan chrome is 3 second Firefox stil 10. When i tested it before with chrome it also took a long time. I think it was because i use a lot of tabs. However Firefox still has the problem

**Comment by lamberta** [comment]
Can't reproduce but will keep an eye on site performance. Tracking an internal ticket b/133423244 for another issue.
