### ISSUE TITLE
Generating fully-quantized models in Pre-trained checkpoints (.chkpt) or GraphDef (.pb)  format

### ISSUE THREAD

**Issue by nullbyte91** [tensorflow/tensorflow#27381]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):1.12.0-rc2
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
By Using the TensorFlow Lite Converter tflite_convert to optimize the TensorFlow graphs and convert them to the TensorFlow Lite format for 8-bit inference. 

Can we have a feature to optimize the TensorFlow graphs and convert them to .chkpt or .pb format?  So, We can Initialize the WB in tensorflow and do inference with 8-bit.

**Will this change the current API? How?**
No

**Who will benefit with this feature?**
The developers who want only Int-8 quantization model(WB) and not depend on TFLite.

**Any Other info.**
No

**Comment by jvishnuvardhan** [comment]
@nullbyte91 Could you describe the feature and its context with little more detailas? Thanks!

**Comment by nullbyte91** [comment]
@jvishnuvardhan 
I'm trying to understand quantize aware training with cifarnet from models/research/slim/nets/ and Extract INT8 WB and dump it in checkpoints (.chkpt) or GraphDef (.pb) format not tflite. 
 
**Prepare a network for quantization and training:**
   Add fake quantization layers to the model graph by adding tf.contrib.quantize.create_training_graph() before optimization procedure and train the network. For example, 
I train the network for 10000 steps and used tf.contrib.quantize.create_training_graph(quant_delay=90000). The value 90000 indicates that the model will be trained for 90000 steps with floating-point weights and activations, before the quantization process begins.

**Prepare the Graph for Inference:**
1. Add fake quantization layers to the graph by adding tf.contrib.quantize.create_eval_graph() before graph_def = graph.as_graph_def(). 
2. Export the inference graph to a protobuf file. For CifarNet this is done using:
python export_inference_graph.py --model_name=cifarnet --dataset_name=cifar10 --
output_file=/tmp/cifarnet_inf_graph.pb.
3. Freeze the graph using the freeze_graph tool. You can specify any checkpoint during training for this. The command to freeze the graph is:
python -m tensorflow.python.tools.freeze_graph \
--input_graph=<your_graph_location> \
--input_checkpoint=<your_chosen_checkpoint> \
--input_binary=true \
--output_graph=<output_directory> \
--ouput_node_names=<output_nodes>

**If we look at the Quantization aware training doc from Tensorflow,
The previously demonstrated after-rewrite eval graph only simulates quantization. To generate real fixed-point computations from a trained quantization model, convert it to a fixed-point kernel. TensorFlow Lite supports this conversion from the graph resulting from create_eval_graph.**

**Quantize the Graph:**
tflite_convert --graph_def_file=<your_frozen_graph> \
--output_file=<your_chosen_output_location> \
--input_format=TENSORFLOW_GRAPHDEF \
--output_format=TFLITE \
--inference_type=QUANTIZED_UINT8 \
--output_arrays=<your_output_arrays> \
--input_arrays=<your_input_arrays> \
--mean_values=<mean of input training data> \
--std_dev_values=<standard deviation of input training data>

But, It converts frozen graph which has a fake quantization layer to fully-quantized TensorFlow Lite model. I actually want to skip this part, converts the frozen graph to .chpt or .pb format.

There are tools available(flatbuffer, netron) to view and extract the information from the tflite file. But, None of them converts into numpy array, .pb or .chpt format. It just a visualization tool.

Please let me know, If you requires any other information.

**Comment by jasonaidm** [comment]
I also have this demand (pb format quantization model), please help us, thanks! @jvishnuvardhan

**Comment by steve3nto** [comment]
I would also like to estimate the performance drop from uint8 quantization of both weights and activations, but without having to use tflite. 
It would be nice to be able to have a frozen_graph.pb with quantized operations that can be evaluated using regular tensorflow inference.

**Comment by ZhangShuoAlreadyExists** [comment]
Hi @nullbyte91 ,  

I also need fully quantized models for inference in Tensorflow. I found this issue raised several months ago. Do you have any way to convert to .pb format now?

**Comment by nullbyte91** [comment]
@ZhangShuoAlreadyExistst No. There is a way to dump the tfLite Quantization numbers to JSON format but its a tedious task.

**Comment by ZhangShuoAlreadyExists** [comment]
@nullbyte91  Thanks for your reply.

**Comment by aluds123** [comment]
Hi @nullbyte91 ,
can you guide me how to use quantization aware with a pretrain weight(32bit)(ckpt)?
I have already trained a 32bit weight. Can I make it be a pretrain weight and train by quantization aware(tf.contrib.quantize.create_training_graph(quant_delay=300000))?

Thank you.

**Comment by pedroska777** [comment]
I aslo like to have this feature. It would be nice if we can have a quantization in regular tensorflow.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!
