### ISSUE TITLE
Tensorflow 2.0: Optimizer.minimize ('Adam' object has no attribute 'minimize')

### ISSUE THREAD

**Issue by ikamensh** [tensorflow/tensorflow#27386]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave
- TensorFlow installed from (source or binary): latest 2.0.0-alpha0 via pycharm
- TensorFlow version (use command below): 2.0.0-alpha0
- Python version: 3.7

For my Reinforcement Learning application, I need to be able to apply custom gradients / minimize changing loss function. According to documentation [https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/optimizers/Optimizer], it should be possible with Optimizer.minimize() function. However, my pip-installed version appears not to have this feature at all.

https://stackoverflow.com/questions/55459087/tensorflow-2-0-optimizer-minimize-adam-object-has-no-attribute-minimize

My code:

```
from tensorflow.python.keras.optimizers import Adam, SGD
print(tf.version.VERSION)
optim = Adam()
optim.minimize(loss, var_list=network.weights)
```
output:

```
2.0.0-alpha0
Traceback (most recent call last):
  File "/Users/ikkamens/Library/Preferences/PyCharmCE2018.3/scratches/testo.py", line 18, in <module>
    optim.minimize(loss, var_list=network.weights)
AttributeError: 'Adam' object has no attribute 'minimize'
```

**Comment by yongtang** [comment]
@ikamensh I think instead of 
```
from tensorflow.python.keras.optimizers import Adam, SGD
```
, you should use `tf.keras.optimizers`.

The `tf.keras.optimizers` is the one exposed in 2.0. 

`tensorflow.python.keras.optimizers` is internal and is not routed to 2.0 API.

**Comment by ikamensh** [comment]
Right, the source of my confusion was that tf.keras is prompting an IDE warning:
Cannot find reference 'keras' in '__init__.py'

Actually running the code works. Should __init__.py be modified to remove this confusion?

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by jvishnuvardhan** [comment]
I noticed your [Stackoverflow post](https://stackoverflow.com/questions/55459087/tensorflow-2-0-optimizer-minimize-adam-object-has-no-attribute-minimize). That is the right place for support type question. Thanks!

**Comment by ikamensh** [comment]
Do you agree that __init__.py should be modified to allow IDEs to discover these right paths? 

> Right, the source of my confusion was that tf.keras is prompting an IDE warning:
> Cannot find reference 'keras' in '__init__.py'
> 
> Actually running the code works. Should __init__.py be modified to remove this confusion?

**Comment by jvishnuvardhan** [comment]
Closing this as the stackoverflow is correct place for this issue.
