### ISSUE TITLE
Confusion about how bucketized feature columns work

### ISSUE THREAD

**Issue by ssubraveti** [tensorflow/tensorflow#27398]
I had some confusion about how bucketized feature columns represent input to the model. According to the [blog post on feature columns](https://developers.googleblog.com/2017/11/introducing-tensorflow-feature-columns.html), when we bucketize a feature like `year` this puts each value in buckets based on the defined boundaries, and creates a binary vector, turning on each bucket based on the input value, but the example in the [documentation](https://www.tensorflow.org/api_docs/python/tf/feature_column/bucketized_column) shows the output as a single integer. I'm confused as to how the input is to the model when using a bucketized column..
**System information**
- TensorFlow version:
1.4.0
- Doc Link:
https://www.tensorflow.org/api_docs/python/tf/feature_column/bucketized_column

**Comment by muddham** [comment]
@ssubraveti This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by ssubraveti** [comment]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>


**System information**
- TensorFlow version:
1.4.0
- Doc Link:
https://www.tensorflow.org/api_docs/python/tf/feature_column/bucketized_column
https://www.tensorflow.org/guide/feature_columns

**Describe the documentation issue**
So the reason I think this is an issue is because the blog post and the documentation for `bucketized_feature_column` seem to say different things about how the preprocessing is done. The blog post mentions this example of a feature like year, and the illustration shows that depending on the boundaries(for the example in question, the boundaries for the bucketized_column are 1960, 1980 and 2000), and if the year value `<1960` the input to the model is represented as `[1,0,0,0]`,
and if the value is `>=1960`, but `<1980`, the input to the model is `[0,1,0,0]`, and if the value is `>=1980` but `<2000`, the input to the model is represented as `[0,0,1,0]`, and if year `>=2000`, the input to the model is represented as `[0,0,0,1]`. But the documentation for `bucketized_column`, says the following:

```
boundaries = [0, 10, 100]
input tensor = [[-5, 10000]
                [150,   10]
                [5,    100]]

output = [[0, 3]
          [3, 2]
          [1, 3]]

```
Maybe I'm misunderstanding this, but does this mean that the indices of the buckets are input to the model, instead of the one-hot representation described by the blog post?-

**Comment by jvishnuvardhan** [comment]
@ssubraveti The article came out longback (~1.5 years) and there were lot of changes. The doc link you are referring corresponds to TF1.13 where as the blog corresponds to TF1.4.

Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by ssubraveti** [comment]
@jvishnuvardhan thanks for the reply. I did post the question on stackoverflow as well, but this does seem to be an issue with documentation.

I did actually look at the documentation for 1.4 as well, and the documentation there(https://github.com/tensorflow/docs/blob/r1.4/site/en/api_docs/api_docs/python/tf/feature_column/bucketized_column.md) has the same mismatch with what the blog post says. I just want to understand if I can expect the output of bucketized_column to be a one hot encoded vector of features, or if the feature is just converted to the bucket index. If I'm to believe the documentation on this, the model input is going to be a feature that is the index of the bucket it belongs to, and does this mean that there is a mistake in the article?

**Comment by ssubraveti** [comment]
Closing this because it seems like the model input is a one-hot encoded vector for a bucketized feature based on the dimensions of the weight matrix for the first hidden layer. I still think this should be mentioned explicitly in the documentation.
