### ISSUE TITLE
labe_image bazel build failed! 

### ISSUE THREAD

**Issue by WenguoLi** [tensorflow/tensorflow#27395]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version: 1.12
- Python version:2.7
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):0.24.0
- GCC/Compiler version (if compiling from source): gcc  5.4.0 20160609
- CUDA/cuDNN version: 9.0
- GPU model and memory:

**Describe the problem**

To build label_image for android ARMv8:

```
> bazel build --config android_arm64 --config monolithic --cxxopt=-std=c++11 \
  //tensorflow/lite/examples/label_image:label_image
```

error infor:
```
ERROR: /home/apuser/deeplearning/tensorflow/tensorflow-master/tensorflow/lite/kernels/internal/BUILD:496:1: no such package '@com_google_absl//absl/base': java.io.IOException: Error downloading [http://mirror.tensorflow.org/github.com/abseil/abseil-cpp/archive/2c8421e1c6cef0da9e8a20b01c15256ec9ec116d.tar.gz, https://github.com/abseil/abseil-cpp/archive/2c8421e1c6cef0da9e8a20b01c15256ec9ec116d.tar.gz] to /home/apuser/.cache/bazel/_bazel_apuser/4972b2c1cfd6d41e3f1f5f386fde1d1a/external/com_google_absl/2c8421e1c6cef0da9e8a20b01c15256ec9ec116d.tar.gz: All mirrors are down: [Connection reset, GET returned 404 Not Found] and referenced by '//tensorflow/lite/kernels/internal:tensor_utils'
ERROR: Analysis of target '//tensorflow/lite/examples/label_image:label_image' failed; build aborted: no such package '@com_google_absl//absl/base': java.io.IOException: Error downloading [http://mirror.tensorflow.org/github.com/abseil/abseil-cpp/archive/2c8421e1c6cef0da9e8a20b01c15256ec9ec116d.tar.gz, https://github.com/abseil/abseil-cpp/archive/2c8421e1c6cef0da9e8a20b01c15256ec9ec116d.tar.gz] to /home/apuser/.cache/bazel/_bazel_apuser/4972b2c1cfd6d41e3f1f5f386fde1d1a/external/com_google_absl/2c8421e1c6cef0da9e8a20b01c15256ec9ec116d.tar.gz: All mirrors are down: [Connection reset, GET returned 404 Not Found]

```

**Comment by freedomtan** [comment]
as shown in the error message you posted, 
```
Error downloading [http://mirror.tensorflow.org/github.com/abseil/abseil-cpp/archive/2c8421e1c6cef0da9e8a20b01c15256ec9ec116d.tar.gz, https://github.com/abseil/abseil-cpp/archive/2c8421e1c6cef0da9e8a20b01c15256ec9ec116d.tar.gz] to ...
```

Mostly, it's problem of your internet connection, e.g., behind a firewall or proxy

**Comment by WenguoLi** [comment]
Thanks,  the reason is that the version of bazel is too new.
