### ISSUE TITLE
ExponentialMovingAverage.average duplicates the current scope name

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#2740]
Using tensorflow nightly.

```python
import tensorflow as tf
with tf.name_scope('scope'):
    x = tf.Variable(42, dtype=tf.float32)
    ema = tf.train.ExponentialMovingAverage(decay=0.9)
    apply_op = ema.apply([x])
    average = ema.average(x)
    print average.name   # 'scope/scope/Variable/ExponentialMovingAverage:0'
    print ema.average_name(x)  # 'scope/Variable/ExponentialMovingAverage'
```

**Comment by ppwwyyxx** [comment]
The problem seems to come from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/slot_creator.py#L83, where the name of an op is used to create a variable. But the name of the op already contain the current scope, therefore the variable to create will contain the scope twice.

**Comment by ppwwyyxx** [comment]
It's been a while. I suppose this is a bug right?..

**Comment by aselle** [comment]
Yes that looks like a bug. I'm asking the author of the code to do the quick fix.

**Comment by aselle** [comment]
Unfortunately, after checking internally, fixing this bug would result in losing backward compatibility, which we would like to avoid both for internal and external users. So, right now, I am closing the issue.
@girving, @mrry

**Comment by rafaljozefowicz** [comment]
Isn't it true that ExponentialMovingAverage is used currently almost always outside any scopes? It shouldn't break (many) existing use cases. If I remember correctly, the class simply doesn't work well if the scope name is duplicated and users have to do manual hacking to fix the variable names.

The workaround that I'm using currently is to wrap the class with
```python
with tf.name_scope(None):
   ema = tf.train.ExponentialMovingAverage(...)
   # [rest of the code]
```

**Comment by strategist333** [comment]
It's not just ExponentialMovingAverage, but also the accumulators used by optimizers that have this behavior. Anyone who's using either of these inside a scope of any kind would suffer backwards-incompatible checkpoints due to the naming difference. Especially given there is an easy workaround (i.e. do not create / use ExponentialMovingAverage or Optimizers inside a name scope), the pain that fixing this would cause outweights the benefits.

**Comment by rafaljozefowicz** [comment]
We don't need to share the `create_slot` function between EMA and optimizers. It's essentially just a variable creation.

**Comment by strategist333** [comment]
Two notes: 
1. `create_slots` is more than just a variable creation -- there's some subtle logic in there to deal with properly supporting slots for partitioned variables. So I'd think reusing the logic makes sense.
2. Even if we were to only fix this for `ExponentialMovingAverage`, it would still be a backwards-incompatible graph change for anyone who was using EMA inside a name scope.

**Comment by ppwwyyxx** [comment]
Is it possible to keep the compatibility for now but print a warning about
a future change that will break compatibility (similar to numpy) ?

2016年6月28日 下午3:29，"strategist333" <notifications@github.com>写道：

**Comment by girving** [comment]
@ppwwyyxx I'm not sure I follow.  How would we be able to safely break backwards compatibility in the future?  An advance warning that models will break is not a sufficient fix.

**Comment by ppwwyyxx** [comment]
I mean it will provide a time window for people to make necessary changes to prepare for a future break. But right it won't safely break compatibility.

**Comment by girving** [comment]
@ppwwyyxx I don't think it is worth making this change.  The name fix would be nice, and I agree that the current code is a mistake, but there is a high bar for breaking existing models.

**Comment by ppwwyyxx** [comment]
On latest tensorflow, the `with tf.name_scope(None)` hack still introduces variables with duplicated scope name:
```python
def f():
    v = tf.get_variable('W', [1])
    v = v + 1
    #print v.name
    with tf.name_scope(None):
        ema = tf.train.ExponentialMovingAverage(decay=0.9, name='EMA')
        emaop = ema.apply([v])
        average_v = ema.average(v)

with tf.variable_scope('scope'):
    f()
print([k.name for k in tf.global_variables()])
```
will print:
```
[u'scope/W:0', u'scope/add/EMA:0', u'scope/scope/add/EMA/biased:0', 
u'scope/scope/add/EMA/local_step:0']
```

**Comment by ppwwyyxx** [comment]
The recently-introduced new variables in EMA also brings error when using with reuse=True.
The example below seems like a common pattern in batch normalization. It works before.
```python
def f(v):
    ema = tf.train.ExponentialMovingAverage(0.9)
    vema = ema.apply([v])
    return vema

with tf.variable_scope('s'):
    v1 = tf.get_variable('W', shape=[])
    v1 = v1 + 1
    f(v1)
with tf.variable_scope('s', reuse=True):
    v2 = tf.get_variable('W', shape=[])
    v2 = v2 + 1
    f(v2)
```
```
ValueError: Variable s/s_1/s_1/add/ExponentialMovingAverage/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
```

**Comment by joel-shor** [comment]
There are a number of TF paradigms that previously worked because ExponentialMovingAverage didn't respect variable scopes (see https://github.com/tensorflow/tensorflow/issues/5652, for example). In the case you have here, I'm not sure that I understand the semantics of what you are trying to do: regardless of debiasing, it is an error to call apply on the same variable multiple times: "ValueError: If the moving average of one of the variables is already being computed." (from `ExponentialMovingAverage` description of `apply`). Are you arguing that the wrong error message is thrown in this case?

**Comment by ppwwyyxx** [comment]
@joel-shor Oh. You can change 'W' to 'W2' and move it outside of the scope, it still throws error. I'm only trying to point out that EMA cannot work inside reuse=True.

**Comment by joel-shor** [comment]
1. The issue should be fixed currently; zero_debias is no longer the default in ExponentialMovingAverage.
2. There is a strong possibility that is will be the default in the future.
3. ExponentialMovingAverage create variables, so for future safety you might consider using it as if it respected variable scopes (ie don't put it in resuse=True variable scopes that it doesn't need to be in)

**Comment by ppwwyyxx** [comment]
@joel-shor Thanks. Since there are dedicated issues for the bug we can use them to track. This issue is more about the naming -- and I see there are still very long variable names with duplicated scopes for the newly-introduced biased/local_step variables. Should there be a fix for this?
```python
def f(v):
    ema = tf.train.ExponentialMovingAverage(0.9)
    vema = ema.apply([v])
    return vema
with tf.variable_scope('s'):
    v1 = tf.get_variable('W', shape=[10,10,10,10])
    v1 = v1 + 1
    f(v1)
print [k.name for k in tf.all_variables()]
# [u's/W:0', u's/s/add/ExponentialMovingAverage:0', u's/s/s/add/ExponentialMovingAverage/biased:0', u's/s/s/add/ExponentialMovingAverage/local_step:0']
```

**Comment by joel-shor** [comment]
We are not going to fix this behavior. The reason is that there are two relevant scopes: the scope that the variable was created in, and the scope that the EMA was created in. There will be potential ambiguity if one is removed. Since removing the duplication isn't clearly better, we're going to keep this behavior.

**Comment by nainadhingra2012** [comment]
Hi @joel-shor,  I am facing the same problem while trying to reuse batch-normalization in a network which is used twice. I get error "/convnet_branch/conv1_1_bn/moments/Squeeze/ExponentialMovingAverage/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?"

Can you suggest how to deal with this problem, I read all the above comments but couldn't figure out how it could be solved.

Thanks a lot!

**Comment by shimafoolad** [comment]
Hi @nainadhingra2012. On tensorflow 1.12.0, I had the same problem and fixed it by adding the line: 

            with tf.variable_scope(tf.get_variable_scope(), reuse=tf.AUTO_REUSE):

before ema.apply
