### ISSUE TITLE
longer latency after post-training quantization on NVIDIA Jetson TX2

### ISSUE THREAD

**Issue by dannykuo25** [tensorflow/tensorflow#27401]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
I modified the tutorial below to convert my customized models to print inference latency.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 16.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
NVIDIA Jetson TX2
- TensorFlow installed from (source or binary):
source
- TensorFlow version (use command below):
1.12.0
- Python version:
3.5.2
- CUDA/cuDNN version:
V9.0.252
- GPU model and memory:
GPU model: NVIDIA Pascal™, 256 CUDA cores
memory: 8 GB 128 bit LPDDR4

**Describe the problem**
I modified the tutorial below to convert three customized models to print inference latency.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tutorials/post_training_quant.ipynb

In the 3-layer and 9-layer model,, the inference time of tflite model is shorter than the original one.
However, in resnet50 model, the inference time of tflite model is NOT shorter than the original one.
I summarized the time table and graph below.
![圖片](https://user-images.githubusercontent.com/40556694/55369939-36089e80-552b-11e9-925f-67ec4908b4f4.png)

I read the closed issue #23759:longer latency after post-training quantization. In that issue, the explanation of the longer latency is because the speed-up of integer arithmetic require special/optimized instructions/kernels, while such optimizations are not done on desktop CPU.
Is this explanation applicable to NVIDIA Jetson TX2?

**Any other info / logs**
Include any logs or source code
[tflite.zip](https://github.com/tensorflow/tensorflow/files/3031972/tflite.zip)
 that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by thiagoalmedeiros** [comment]
@dannykuo25 Did you understand the results? I have the same problem with other models like Yolo Tiny, for example. I know that the tiny YOLO is not optimized, but where could I understand this optimization?

Did you have any progress about this problem?

**Comment by dannykuo25** [comment]
@thiagoalmedeiros Hi there! Unfortunately I find it hard to understand the integer arithmetic optimization. So I turned to study other compression topics like pruning and sparsifying regularizer on activation functions.

**Comment by liyunlu0618** [comment]
TFLite only provides optimized integer kernels on mobile CPU (Arm NEON isa, to be more specific). There's no guarantee on other platforms.
