### ISSUE TITLE
Build TFLite Model Benchmark Tool with GPU delegate?

### ISSUE THREAD

**Issue by stakemura** [tensorflow/tensorflow#27402]
**System information**
- TensorFlow version (you are using):nightly-build
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
I'm trying to build TFLite Model Benchmark Tool with GPU delegate on Android and iOS devices.
But unfortunately, It seems to be too difficult for me especially on iOS.
Would you like to provide bazel script to build TFLite Model Benchmark Tool with GPU delegate?

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Anyone using the TFLite.

**Any Other info.**

**Comment by freedomtan** [comment]
for Android, it's quite easy. I had a quick hack couple days ago. I don't think it would be much harder on iOS. See https://github.com/freedomtan/tensorflow/commit/04996cac4a2400523c6e85a19ebcb590ea23ff5a. And if you just want to check the performance of GPU Delegate, I had quick-and-dirty GPU Delegate enabled apps for [android](https://github.com/freedomtan/glDelegateBench/) and [iOS](https://github.com/freedomtan/glDelegateBenchmark/)

**Comment by stakemura** [comment]
@freedomtan 
I appreciate your reply.
Your grateful patches including label_image_gl_delegate are quite helpful for me.
By the way, do you have any plan for submitting pull requests?

**Comment by freedomtan** [comment]
Patches for label_image, yes, I'll do it later. For benchmark_model, need to find a better way, current one is too hacky :-)

**Comment by freedomtan** [comment]
@stakemura I sent PR for label_image https://github.com/tensorflow/tensorflow/pull/27464.

**Comment by WenguoLi** [comment]
When build label_image with  GPU Delegate ,  some errors:

```
ERROR: /home/apuser/tensorflow/tensorflow-master/tensorflow/lite/delegates/gpu/gl/BUILD:108:1: C++ compilation of rule '//tensorflow/lite/delegates/gpu/gl:egl_context' failed (Exit 1)
In file included from tensorflow/lite/delegates/gpu/gl/egl_context.cc:16:
./tensorflow/lite/delegates/gpu/gl/egl_context.h:40:17: error: use of undeclared identifier 'EGL_NO_CONFIG_KHR'
        config_(EGL_NO_CONFIG_KHR) {}
                ^
tensorflow/lite/delegates/gpu/gl/egl_context.cc:105:49: error: use of undeclared identifier 'EGL_NO_CONFIG_KHR'
  return CreateContext(display, shared_context, EGL_NO_CONFIG_KHR, egl_context);
                                                ^
2 errors generated.

```

**Comment by gadagashwini** [comment]
Closing this issue since the associated PR has been merged. Feel free to reopen if the problem still persists. Thanks!
