### ISSUE TITLE
tf.data.Iterator won't release memory when reinitialized

### ISSUE THREAD

**Issue by yluo16** [tensorflow/tensorflow#27414]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.10.1
- Python version: 3.6.6
- CUDA/cuDNN version: 9.0
- GPU model and memory: NVIDIA GTX1080Ti, 11GB GPU/ 64 GB RAM

**Describe the current behavior**
When testing my model, I had several batches of images with batch size equals to 10. As the images are large, I loaded them from hard drive every time. My code is structured as <br />
```python
iterator = tf.data.Iterator.from_structure(output_types=tf.float32, output_shapes=[1536, 1536, 2])
output  = model_fn(iterator.get_next())
for images in files:
    dataset = tf.data.Dataset.from_tensor_slices(tf.constant(images))
    sess.run(iterator.make_initializer(dataset))
    output_value = []
    for _ in range(10):
        output_value.append(sess.run(output))
``` 
Here each of my `images` is a numpy array with a size of [10, 1536, 1536, 2].<br />
While the code running, the memory usage is growing fast -- every image set it read in stayed there in the memory.

**Describe the expected behavior**
I'm expecting the iterator release the memory each time it reinitialized.

**Code to reproduce the issue**
For a reproducible test, I also tried this, to see if the memory leakage is due to something else:
```python
import tensorflow as tf
import numpy as np
iterator = tf.data.Iterator.from_structure(output_types=tf.float64, output_shapes=[1536,1536,2])
sess = tf.InteractiveSession()
for i in range(100):
    data = tf.constant(np.random.rand(10,1536,1536,2))
    dataset = tf.data.Dataset.from_tensor_slices(data)
    ite_data = iterator.make_initializer(dataset)
    sess.run(ite_data)
```
I can still see a huge memory usage when executing this.

**Comment by shashvatshahi1998** [comment]
https://github.com/tensorflow/tensorflow/issues/23904

**Comment by shashvatshahi1998** [comment]
@yluo16 visit this issue you will get little bit help.

**Comment by yluo16** [comment]
> @yluo16 visit this issue you will get little bit help.

Thanks for advising. I'm sorry for raising a existing issue... Maybe I should upgrade to TF 2.0.

**Comment by ymodak** [comment]
Closing since #23904 captures the explanation of behavior observed in this issue. Feel free to reopen if still have further problems. Thanks!
