### ISSUE TITLE
tf.gather shows an error in presence of different dtype tensor under tf.function

### ISSUE THREAD

**Issue by caissalover** [tensorflow/tensorflow#27417]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): Source (1st April 2019)
- TensorFlow version (use command below): v2.0
- Python version: 3
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: 10.0, 7.5.0
- GPU model and memory: Zotac GTX 1060, 6GB

**Describe the current behavior**
tf.gather throws error in presence of another independent tensor inside tf.function

**Describe the expected behavior**
Run smoothly

**Code to reproduce the issue**

    import tensorflow as tf

    a = tf.Variable(tf.random.normal([10]))
    b = tf.Variable(tf.random.uniform([10], minval=-1, maxval=1, dtype=tf.dtypes.int32))
    value = tf.Variable(tf.random.normal([10]))

    print(a.numpy)
    print(b.numpy)

    @tf.function
    def run():
        for j in tf.range(10):

            var = tf.gather(a, j)
            tf.print(var)

            var_int = tf.gather(b, j)
            tf.print(var_int)

    run()

**Information**
When you comment out the float variable, it functions correctly with a warning. When both the int32 and float 32 are present, tf.gather shows an error as shown below.

**Other info / logs**
File "test.py", line 20, in <module>
    run()
  File "/home/caissalover/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 437, in __call__
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/caissalover/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 559, in _filtered_call
    (t for t in nest.flatten((args, kwargs))
  File "/home/caissalover/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 633, in _call_flat
    outputs = self._inference_function.call(ctx, args)
  File "/home/caissalover/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 416, in call
    ctx=ctx)
  File "/home/caissalover/.local/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 66, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot place the graph because a reference or resource edge connects colocation groups with incompatible assigned devices: /job:localhost/replica:0/task:0/device:CPU:0 vs /job:localhost/replica:0/task:0/device:GPU:0. The edge src node is while/exit/_27 , and the dst node is while [Op:__inference_run_98]

**Comment by achandraa** [comment]
Thank you for reaching out to us. Can you please provide minimum reproducible code snippet to help us proceed further and verify what is going wrong

**Comment by caissalover** [comment]
@achandraa , the code I'm converting to 2.0 is proprietary so I cannot share and also is quite messy. I haven't been able to determine what's causing it and make minimum reproducible code, I'll update it as soon as I find out the error cause. What I know for sure is an op is available for GPU and tf2.0 is not being able to place it there. Above is the terminal output. https://github.com/tensorflow/tensorflow/issues/26244 is closely linked with my issue. Eager execution and conv2d both are used in my case above as concern shown in the issue 26244.

**Comment by caissalover** [comment]
@achandraa I have updated the error and I'm sure it's much better than the earlier post. Let me know. Thanks.

**Comment by jvishnuvardhan** [comment]
@caissalover I ran your script in google colab with TF2.0 and it worked as expected. Please check the output below. Could you try running it in colab.sandbox.google.com? You could also upgrade TF2.0 and check whether the bug persists or not. Thanks!

<bound method ResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
array([-0.7555967 , -1.0448577 , -0.08942685,  0.09107728,  0.25068387,
        1.6492767 , -0.40207562, -0.7407482 , -1.7115227 , -0.6381878 ],
      dtype=float32)>>
<bound method ResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(10,) dtype=int32, numpy=array([ 0, -1,  0,  0,  0,  0, -1,  0,  0, -1], dtype=int32)>>
-0.755596697
0
-1.04485774-1

-0.0894268528
0
00.091077283

0.250683874
001.64927673


-0.402075619
-1
-0.7407482270

-1.7115227
0
-0.638187826
-1

**Comment by caissalover** [comment]
Colab shows no warning. Maybe someone fixed the bug after 1st April. Will update and let you know.

**Comment by caissalover** [comment]
Yes, this is resolved. Please close this. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing this issue as it was resolved. Thanks!
