### ISSUE TITLE
ValueError: Invalid tensors 'Mul' were found.

### ISSUE THREAD

**Issue by jennings1716** [tensorflow/tensorflow#27429]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.
Python:2.7
tensorflow:1.9

python script
`input_arrays= ["Mul"]
output_arrays=["final_result"]
converter = tf.contrib.lite.TocoConverter.from_frozen_graph(graph_def_file,input_arrays,output_arrays)
tflite_model = converter.convert()
open("model.tflite", "wb").write(tflite_model)`

It was working fine a month before.Now it shows the following error

  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert_saved_model.py", line 205, in get_tensors_from_tensor_names
    ",".join(invalid_tensors)))
ValueError: Invalid tensors 'Mul' were found.

**Comment by jvishnuvardhan** [comment]
@jennings1716 You mentioned it was working well a month before. What was the change you made recently? Did you upgrade tensorflow or python or any other dependencies?Could you provide a code to reproduce bug? Could you try it in Google [colab](https://colab.sandbox.google.com) to verify whether it is working or not. Can you also try to upgrade your code to latest TF. Thanks!

**Comment by jennings1716** [comment]
Hi @jvishnuvardhan It was working fine... When I use the same input and output tensor names for the tflite conversion i got the error... Then I changed the tensor names to 
input array = "lambda_1/Mul"
output array = "model_2/model_1/dense_2/Softmax"
It works with above names... I wonder why...?

**Comment by jvishnuvardhan** [comment]
@jennings1716 Could you check with TF1.13.1 and see whether the bug persists with latest version. You could also try TF2.0. Thanks!

**Comment by jennings1716** [comment]
Hi @jvishnuvardhan It is working for python 3.5( Mul,final_result) But for Python 2.7 there remains the bug
