### ISSUE TITLE
Clearing Tensorflow-Keras GPU memory

### ISSUE THREAD

**Issue by sepehrghafari** [tensorflow/tensorflow#27433]
I'm fitting a model in a for loop,but i'm getting an error that my gpu's memory is full. I'm using Keras in Anaconda spyder ide.My gpu is asus gtx 1060 6gb.

I've also used codes like : K.clear_session() , gc.collect() , tf.reset_default_graph() , del custom_model but none of them worked. Gpu properties say's 98% of memory is full. enter image description here

Nothing flush gpu memory except numba.cuda.close() but won't allow me to use my gpu again. The only way to clear it is restarting kernel and rerun my code.

I'm looking for any script code to add my code allow me to use my code in for loop and clear gpu in every loop.

Part of my code :

image_input = Input(shape=(224, 224, 3))
base_model = Xception(input_tensor=image_input, include_top=False,weights='imagenet')
base_model.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])
hist = base_model.fit(X,Y,epochs=2)

**System information**
- Have I written custom code :
- Windows 10 64-bit
- TensorFlow installed from conda install tensorflow-gpu
- TensorFlow version: 1.3
- Python version: 3.6
- CUDA/cuDNN version: 9.2
- GPU model and memory: Asus GTX 1060 6gb

**Comment by amanp592** [comment]
@sepehrghafari 

Try using: 

gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction = 0.333)
sess = tf.Session(config = tf.ConfigProto(gpu_options = gpu_options)

This command will only use 33.3% of your GPU memory and will prevent the following error. You can play with the number here and can use any number of your choice!

Update me if it worked!

**Comment by sepehrghafari** [comment]
@amanp592 
Thank you for replying ,
I got error when i use this cause when i load imagenet weights,it needs memory and this code slows running time. i don't have out of memory issue in single run. I need a script to clear GPU memory in every loop.

**Comment by muddham** [comment]
@sepehrghafari In order to expedite the troubleshooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by sepehrghafari** [comment]
@muddham I wrote my code in comment. I have no problem with code, my issue is i want to compile and run and train simple training session with Keras with any Pre-trained models like Xception ,VGG or Resnet, multiple times is a single run, in order to do this i put my whole code in for. but after loading Pre-trained models, GPU memory gets about 80-90% full. In second loop of for i got OOM error.
I tried K.clear_session() , gc.collect() , tf.reset_default_graph() , del model but none of them flush the GPU memory.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. If you think this is a bug, please provide a short code and error trace so that we can reproduce the bug and resolve it. Thanks!

**Comment by sepehrghafari** [comment]
I found solition in this article :
https://github.com/keras-team/keras/issues/12625

So i close this title, thanks everyone who participated.
