### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution' in Verify installation

### ISSUE THREAD

**Issue by timoveldt** [tensorflow/tensorflow#27435]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: not applicable
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tensorflow-gpu 2.0.0a0
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: virtualenv + pip
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): - 
- CUDA/cuDNN version: 10.0/7.5.0.56
- GPU model and memory: NVIDIA GTX 1080 Max-Q

**Describe the problem**
I've just followed the installation guides for tensorflow 2.0 (see above) from:
- https://www.tensorflow.org/install/pip
- https://www.tensorflow.org/install/gpu#software_requirements
The final step is to "Verify the install" (see the pip link above) which gives me the following output:
```
$ python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'
```

Which I did not expect/hope to see.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
- Follow the guides mentioned above.
- Create all the environment variables. 
-- Path within venv then contains: 
```
D:\dev\project\project-venv\
D:\dev\tools\cuda\cudnn-10.0-windows10-x64-v7.5.0.56\cuda\bin;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;
C:\ProgramData\DockerDesktop\version-bin;
C:\Program Files\Docker\Docker\Resources\bin;
D:\dev\tools\oraclexe\oraclexe\app\oracle\product\11.2.0\server\bin;
C:\Program Files\Python36\Scripts\;
C:\Program Files\Python36\;
C:\Program Files\Microsoft MPI\Bin\;
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;
C:\ProgramData\Oracle\Java\javapath;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Program Files\dotnet\;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
D:\dev\tools\putty\;
C:\Program Files\TortoiseSVN\bin;
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;
C:\Program Files\nodejs\;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\WINDOWS\System32\OpenSSH\;
C:\dev\tools\python\python3.6.7\Scripts\;
C:\dev\tools\python\python3.6.7\;
C:\Program Files\Python36\Scripts\;
C:\Program Files\Python36\;
C:\Users\tve21314\AppData\Local\Microsoft\WindowsApps;
D:\dev\tools\maven\apache-maven-3.5.3\bin;
C:\Program Files\Java\jdk1.8.0_201\bin;
C:\Program Files\Java\jre1.8.0_201\bin;
C:\Program Files\Git\bin;
C:\Users\tve21314\AppData\Local\Programs\Microsoft VS Code\bin;
C:\Users\tve21314\AppData\Roaming\npm;
```
- Finally run from within the venv:
```python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- The traceback again:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'
```

- If I use ```python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random_normal([1000, 1000])))"``` the error becomes:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'random_normal'
```

**Comment by p9i** [comment]
Hi, I have the same issue.

I install tensorflow on my MacBook pro based on the page: https://www.tensorflow.org/install,  
$pip3 install tensorflow==2.0.0-alpha0
It works.

I install tensorflow with pip3 step by step too: https://www.tensorflow.org/install/pip. It almost works, but the last step 'verify the install': 
$python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'

Thank you.

**Comment by lynscott** [comment]
Same issue here.

Ubuntu 18.04
CUDA 10.0
virtualenv + pip
NVIDIA GTX 1060
Python 3.6.7

Attribute errors for both eager execution & random_normal, but installs successfully.

**Comment by ymodak** [comment]
@timoveldt @p9i @lynscott  Thanks for reporting this issue. We have to update our docs to address TF 2.0 install verification.
```AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'```

Eager execution is enabled by default in TF 2.0 Therefore we need not enable it explicitly.
```AttributeError: module 'tensorflow' has no attribute 'random_normal'```
TF 2.0 comes with new [aliases](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/random/normal#aliases) for random_normal

**Comment by timoveldt** [comment]
@ymodak That fixed it!

Nice to see that I was on the right track by removing the eager execution. I never would've guest that the next step was in the aliases. 

I'm trying to contribute the actual fix, but I've got some hoops to jump through :)

**Comment by ymodak** [comment]
Glad it worked. Thanks for submitting the PR. I will close this issue now.
