### ISSUE TITLE
Errors with tensorflow-gpu 2.0 alpha0

### ISSUE THREAD

**Issue by loveunk** [tensorflow/tensorflow#27432]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tensorflow-gpu 2.0 alpha0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cudatoolkit 10.0.130, and cudnn 7.5
- GPU model and memory: NVIDIA GTX 1070/6GB

**Describe the problem**
I have installed tensorflow-gpu 2.0alpha0, cudatoolkit 10.0.130, and cudnn 7.5 in a windows 10.

TensorFlow 2.0 works well with CPU, but encounters errors while running with GPU.

Errors messages are as bellow:
```
2019-04-02 23:47:38.646661: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-04-02 23:47:38.666653: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2019-04-02 23:47:38.666842: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
```

I think the main issue is "Could not dlopen library 'nvcuda.dll'".

However, I have installed the latest NVIDIA driver (version 419.67), and 'nvcuda.dll' can be found in C:\Windows\System32\nvcuda.dll.

The issue is also posted in [stackoverflow](https://stackoverflow.com/questions/55478968/errors-with-tensorflow-gpu-2-0alpha0).

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@loveunk Could you check this [issue](https://github.com/tensorflow/tensorflow/issues/19266) which is similar to your issue but for older TF version. If those solutions doesn't work, could you uninstall and reinstall CUDA and cuDNN? Please let us know how it progresses. Thanks!

**Comment by loveunk** [comment]
@jvishnuvardhan It does not work. The same error exists.

**Comment by jvishnuvardhan** [comment]
@loveunk  Could you uninstall and reinstall CUDA and cuDNN? Can you try some solutions that were listed in some of GitHub issues and Stackoverflow? This is more related to NVIDIA's CUDA so they might have solutions in their GitHub repo. Thanks!

**Comment by loveunk** [comment]
@jvishnuvardhan I have tried several different penitential solutions, including reinstalling CUDA Toolkit and cuDNN. Unfortunately, none of them work.

Currently, it's hard to judge whether this issue is more related to CUDA than tensorflow. 

I have write some test win32 application with C++ to load 'nvcuda.dll',  it can be found and loaded to the program successfully.

**Comment by omnihaand** [comment]
YMMV, but we had the same issue with tensorflow-gpu 2.0.0-beta0. Here's how we got around it:

conda create -n tf_beta python=3.6 cudnn cudatoolkit cudatoolkit-dev pip; conda activate tf_beta; pip install tensorflow-gpu==2.0.0-beta0

For alpha0, this seems to work on our 2080ti rig:

conda create -n tf_alpha python=3.6 cudnn cudatoolkit cudatoolkit-dev pip; conda activate tf_alpha; pip install tensorflow-gpu==2.0.0-alpha0


System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Xubuntu 18.04
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary): source
TensorFlow version: tensorflow-gpu 2.0 alpha0 & beta0
Python version: 3.6
Installed using virtualenv? pip? conda?: conda with pip
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: cudatoolkit 10.0.130, and cudnn 7.5
GPU model and memory: 2x NVIDIA RTX 2080 TI / 11G x 2 (NVLink 22G)

**Comment by jvishnuvardhan** [comment]
@loveunk Is this resolved. If yes, please close the issue. Thanks!

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!
