### ISSUE TITLE
Tensorflow lite model inference time increases when adding JNI on Android

### ISSUE THREAD

**Issue by buaadf** [tensorflow/tensorflow#27443]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS10.14.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: HW P9, Mi8, Oneplus 5, VIVOX9, HuaWei Honor V9....
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):  1.13.0.dev20190126
- Python version: 2.7/3.7(both tryed)

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

I use tflite model (quantization-aware training and fully quantized with toco) and deploy on Android for segmentation task. I got correct output of the model, and the inference time is 30ms(1 thread), 17ms(2 threads), 15ms(3 threads). However, when i add some post-processing with C++(JNI), the inference time (only the function `Interpreter.run(input, output)`  run time)increases to 47ms(1 thread), 34ms(2 threads) , 30ms(3 threads), respectively, and I got the same inference time even though I didn't use the post-processing (just put the jni code in my project). 
When I use post-processing with java code, the inference time is 30ms(1 thread), 17ms(2 threads), 15ms(3 threads) again, so I guess JNI would influence the inference time.

**Describe the expected behavior**
Get same inference time with JNI on Android.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
just add some jni code to the official demo would got the same issue.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@buaadf Could you provide a code to reproduce bug? what are the commands used to convert model?
Could you try TF1.13.1 (master) and/or TF2.0.0.alpha, or tf-nightly to check whether the bug is persistent with recent TF versions. Thanks!

**Comment by buaadf** [comment]
I have tried with 1.13.1 and nightly, the bug is pesistent..

**Comment by buaadf** [comment]
I finally found the reason, the demo with and  without jni use armeabi_v7 and arm64_v8a , respectively.
