### ISSUE TITLE
[Enhancement] Automatically chose either memory or storage to cache in tf.data API

### ISSUE THREAD

**Issue by GCRVL** [tensorflow/tensorflow#27449]
**System information**
- TensorFlow version (you are using): 1.13
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
At the moment, one has to keep in mind what the systems resources will be when using the tf.data pipeline API. Specifically, when using the https://www.tensorflow.org/api_docs/python/tf/data/Dataset#cache operation, I have to ask myself whether it's worth caching the data and whether to do so in memory or storage.

As I both switch systems and datasets a lot I often chose wrong and end up with filled swap memory or extremely slow epochs because I have caching disabled.

What I would like to see, although I understand the complexities involved, is some sort of dynamic cache where the systems itself decides what to use (memory, storage or no caching), depending on available resources and the computations to cache.

A intermediate solution might be one where the user can select how much memory (percentage) to use to cache and for the remaining required cache to use storage so we get some hybrid memory/storage solution.

**Will this change the current api? How?**
It will either add to it or change the current cache() parameters. How and what's best here is not up to me.

**Who will benefit with this feature?**
Anyone using the tf.data API looking to improve performance.

**Comment by tilakrayal** [comment]
@While using tf.data API, when caching to a file, the cached data will persist across runs. Even the first iteration through the data will read from the cache file. Changing the input pipeline before the call to .cache() will have no effect until the cache file is removed or the filename is changed. Kindly please take a look at this official doc link for the [reference](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#cache). Thank you!
