### ISSUE TITLE
ImportError: DLL load failed: Access is denied.

### ISSUE THREAD

**Issue by Nriver** [tensorflow/tensorflow#27451]
**System information**  

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit  
- TensorFlow installed from (source or binary): pip  
- TensorFlow version: 1.12.0  
- Python version: 3.6.7 64bit  
- Installed using virtualenv? pip? conda?: No virtualenv. Direct install with pip. No conda. Virtualenv tried, but result is the same.  
- CUDA/cuDNN version: cuda_9.0.176_win10, cudnn-9.0-windows10-x64-v7.5.0.56  
- GPU model and memory: RTX2070 8G  
- CPU model: intel i5-9400f (CPU without integrated GPU)  

**Describe the problem**

To be clear, this is NOT a issue about the dll files that can not be found. Files are there, but something is wrong with the previlige.

I recently built a new windows 10 PC and installed tensorflow on it. The installation was successful, but I had to run the code with Administrator. Otherwise a simple import code like "import tensorflow as tf" would result in "ImportError: DLL load failed: Access is denied" if I try to run it without "Run as Administrator". The code did work flawlessly if I choose to run as admin though. But on my old notebook I could execute without admin previlige.

The installations on my new and old computer were the same, so the software version and system environment variables should not be the problem. I am wondering why this is happening and is there any way I can get rid of the "run as admin" process which is rather danger and annoying for every time I want to run the code.

**Any other info / logs**

```
3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Access is denied.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hello tensorflow.py", line 12, in <module>
    import tensorflow as tf
  File "C:\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Access is denied.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by ymodak** [comment]
duplicate #26059

**Comment by Nriver** [comment]
I just find the way to reproduce the error. Create another user on Windows 10, and you will find that when you try to execute any tensorflow related code the "DLL load failed: Access is denied" would come out.

I think there is a problem with multiple users on Windows 10 for tensorflow. The only user who can correct start tensorflow is the first one install your system with. Any later created user would counter this kind of problem.

**Comment by dksb** [comment]
Did you install tensorflow as an admin? This seems like standard OS security mechanism than an issue with tensorflow. You may want to install it as the user you want to run the code as. Or check pip documentation for user specific install: https://pip.pypa.io/en/stable/user_guide/#user-installs

**Comment by cosmo86** [comment]
One thing worked for me is to turn off the firewall on your PC. Mine was called 360 Fire Wall. After I turned it off, everything worked well
