### ISSUE TITLE
Workaround for self-attention using tf.matmul

### ISSUE THREAD

**Issue by stefan-falk** [tensorflow/tensorflow#27457]
We are currently trying to convert a tensorflow model to a tf-lite graph. In particular we are working on a transformer which uses self-attention. The problem with that operation seems to be that `tf.matmul` receives two non-constant inputs which is, according to [the docs](https://www.tensorflow.org/lite/guide/ops_compatibility), not allowed:

> `tf.matmul` - *as long as the second argument is constant and transposition is not used*

This seems like a major limitation for the self-attention mechanism. Is there any workaround available for this?

(see also [stackoverflow question](https://stackoverflow.com/questions/55491752/workaround-for-using-tf-matmul-with-two-non-constant-inputs))

**Comment by renjie-liu** [comment]
Currently matmul is not fully supported by tflite, and it will be resolve into fully_connected op during conversion.

since your use case self-attention needs it, we can definitely look into it.

do you have a model help us debug?

thanks!

**Comment by jaeyoo** [comment]
Hi @stefan-falk ,

Sorry for belated, I saw that this transformer example is well converted into TFLite with tf-nightly.
https://www.tensorflow.org/tutorials/text/transformer
Could you try it?

**Comment by lcmeng** [comment]
@renjie-liu It seems that the Keras MultiHeadAttention has been massaged to use fully_connected, instead of BatchMatMul, during the TFLite conversion. Can you please confirm that and point me to where that is done? TIA.

**Comment by renjie-liu** [comment]
It's being done here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/tf_tfl_passes.cc#L216-L219

**Comment by lcmeng** [comment]
Hi @renjie-liu , thank you for the quick reply. I verified that the `unfold_batchmatmul` is an attribute of `TFLiteConverterBase`, which is the base class of  `TFLiteConverterBaseV1`. 

However, in my experiment, a multi-head attention implemented in TF1 still results in `BatchMatMul` after conversion by `tf.compat.v1.lite.TFLiteConverter`. Can you please confirm whether `BatchMatMul` in TF1 models can be unfolded by `tf.compat.v1.lite.TFLiteConverter`?

**Comment by lcmeng** [comment]
I've included the implementation below. There are two calls to `tf.linalg.matmul()` to compute the attention score and attention probability matrices. Converting this TF1 model with `tf.compat.v1.lite.TFLiteConverter` produces `BatchMatMul` instead of the unfolded implementation with FC. 

```
  qkv = tf.layers.dense(inputs, embed_dim*3, name=name+'/atten/qkv')

  bh_size, seq_len = tf.shape(inputs)[0], tf.shape(inputs)[1]

  # compute query, key, value matrices
  qkv = tf.reshape(qkv, shape=(bh_size, seq_len, 3, nb_heads, -1))
  qkv = tf.transpose(qkv, perm=(2, 0, 3, 1, 4))
  q, k, v = tf.split(qkv, num_or_size_splits=3)
  q, k, v = [tf.squeeze(t, axis=0) for t in (q, k, v)]

  # compute self attention weights, 'bhid,bhdi->bhii'
  dots = tf.linalg.matmul(q, k, transpose_b=True, name=name+'/atten/atten_score') * scale
  attn = tf.nn.softmax(dots, axis=-1)

  # compute weighted value matrix, 'bhii,bhid->bhid'
  out = tf.linalg.matmul(attn, v, name=name+'/atten/atten_prob')
  out = tf.transpose(out, perm=(0, 2, 1, 3))
  out = tf.reshape(out, shape=(bh_size, seq_len, embed_dim))

  # compute layer output
  out = tf.layers.dense(out, embed_dim, name=name+'/atten/proj')
```

**Comment by renjie-liu** [comment]
Unroll batch_matmul is the default behavior however it only works when the input shape is static, I think if you set a static shape, the batch_matmul should be unrolled.

**Comment by lcmeng** [comment]
Thanks for pointing that out. Problem solved!

**Comment by mohantym** [comment]
Hi @stefan-falk !

We are checking whether you are still looking for any assistance in this issue. TF.matmul is supported now in[ built-in ops](https://www.tensorflow.org/lite/guide/ops_compatibility) . To enable select ops conversion, Please use [select ops ](https://www.tensorflow.org/lite/guide/ops_select#convert_a_model )syntax before model conversion.

Thank you!
