### ISSUE TITLE
running digits.py

### ISSUE THREAD

**Issue by jbohart** [tensorflow/tensorflow#2745]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:MAC OSX El Captain

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
tensorflow
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.8.0

If installed from sources, provide the commit hash:

### Steps to reproduce
1.run run digits.py from examples in tensorflow/tensorflow/examples/skflow directory
2.
3.

### What have you tried?
1. BaseModel __init__ does except argument - perhaps i need to update tensorflow but not sure how to using pip
 
### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by girving** [comment]
What error message are you seeing?

**Comment by jbohart** [comment]
This is error message:
TypeError                                 Traceback (most recent call last)
<ipython-input-66-aa3e49af45b1> in <module>()
     49 
     50 if __name__ == '__main__':
---> 51   tf.app.run()

/Users/joe/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.pyc in run(main)
     28   f._parse_flags()
     29   main = main or sys.modules['__main__'].main
---> 30   sys.exit(main(sys.argv))

<ipython-input-66-aa3e49af45b1> in main(unused_argv)
     39 
     40   # Fit
---> 41   regressor.fit(x_train, y_train, steps=5000, batch_size=1)
     42 
     43   # Predict and score

TypeError: fit() got an unexpected keyword argument 'steps'

Thanks.

**Comment by girving** [comment]
@jbohart Could you give me the unmangled traceback?  Somehow you've managed to strip away all the file information showing what code is involved.

**Comment by jbohart** [comment]
not sure best way to do this. i've attached the code i'm running to get the error.
Tried various combinations of: python -m trace --trace test.py and using import traceback with print_tb to no avail. 
[test.py.txt](https://github.com/tensorflow/tensorflow/files/308247/test.py.txt)

**Comment by girving** [comment]
@ispirmustafa: Is `regressor.fit` supposed to take a steps argument?

**Comment by aselle** [comment]
@ispirmustafa friendly ping to take a look.

**Comment by ispirmustafa** [comment]
Hi,
Not providing steps means training will continue forever or until input is
exhausted.

**Comment by ispirmustafa** [comment]
Yes, fit supposed to take a steps. Default is None which means run infinitely or until input is exhausted.

**Comment by girving** [comment]
Seems fixed in the code, but I'm not a tf.learn person regardless.  @jbohart Can you confirm this is fixed?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when additional information becomes available.

**Comment by jbohart** [comment]
testing:
#1:
clone latest repo
cd examples/skflow
python digits.py
got error below
#2: 
sudo pip install tensorflow --upgrade
python digits.py
got same error below 

error:
Traceback (most recent call last):
  File "digits.py", line 52, in <module>
    val_monitor = monitors.ValidationMonitor(X_val, y_val, every_n_steps=50)
TypeError: __init__() got an unexpected keyword argument 'every_n_steps'

thx.

**Comment by martinwicke** [comment]
The monitors interface has changes recently, this may or may not work for 0.8.0. @jbohart are you also running on 0.8.0?

**Comment by jbohart** [comment]
Yes, I'm running 0.8.0.

**Comment by terrytangyuan** [comment]
@jbohart Could you try the latest version? It should be there now. [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/monitors.py#L606)
