### ISSUE TITLE
[TF 2.0 Build] Bazel version checking bug when compiling from source

### ISSUE THREAD

**Issue by hanmingliu2** [tensorflow/tensorflow#27450]
**System information**
- OS: macOSMojave 10.14.4 Beta
- Device: MacBook Pro
- TensorFlow version: 2.0.0 alpha0
- Python version: 3.7.3
- Bazel version (if compiling from source): 0.24.0
- GCC/Compiler version (if compiling from source): Apple LLVM 10.0
- CUDA/cuDNN version: None
- GPU model and memory: Intel HD640

**Problem Description**

**Bazel 0.24.0 is correctly installed in my system but tensorflow failed to recognize it and logged the following when compiling from source:**
`
You have bazel 0.24.0 installed.
Please downgrade your bazel installation to version 0.24 or lower to build TensorFlow! To downgrade: download the installer for the old version (from https://github.com/bazelbuild/bazel/releases) then run the installer.
`

This can be reproduced by running` ./configure` when following the official **'Build From Source'** instructions. I have investigated the issue and realize that it is caused by incorrect conversion of bazel version info to integer in **'configure.py'**.

After adding print statements at line 472, 474, 476 of **'configure.py'**, such bug is easy to see:
```python3
min_version_int = convert_version_to_int(min_version)
print('min version required:', min_version_int)
curr_version_int = convert_version_to_int(curr_version)
print('currently installed version:', curr_version_int)
max_version_int = convert_version_to_int(max_version)
print('maximum version allowed:', max_version_int)
```
**Then  running** `./configure` **again produces:**
```
min version required: 19000
currently installed version: 24000
maximum version allowed: 24
You have bazel 0.24.0 installed.
Please downgrade your bazel installation to version 0.24 or lower to build TensorFlow! To downgrade: download the installer for the old version (from https://github.com/bazelbuild/bazel/releases) then run the installer.
```
The version checking logic in **'configure.py'** relies on such conversion.
Below is the version checking logic from line 475 to 493 in  **'configure.py'**:
```python3
# Check if current bazel version can be detected properly.
  if not curr_version_int:
    print('WARNING: current bazel installation is not a release version.')
    print('Make sure you are running at least bazel %s' % min_version)
    return curr_version

  print('You have bazel %s installed.' % curr_version)

  if curr_version_int < min_version_int:
    print('Please upgrade your bazel installation to version %s or higher to '
          'build TensorFlow!' % min_version)
    sys.exit(1)
  if (curr_version_int > max_version_int and
      'TF_IGNORE_MAX_BAZEL_VERSION' not in os.environ):
    print('Please downgrade your bazel installation to version %s or lower to '
          'build TensorFlow! To downgrade: download the installer for the old '
          'version (from https://github.com/bazelbuild/bazel/releases) then '
          'run the installer.' % max_version)
    sys.exit(1)
```

I am very willing to contribute to a fix to this issue. I will create a pull request soon after I fully tested my solution on this.
Thank you very much.

**Comment by ymodak** [comment]
Thanks for catching this and raising new [issue](https://github.com/tensorflow/tensorflow/issues/27575) to address this problem. I will close this issue now.
