### ISSUE TITLE
[TF 2.0 API Docs] tf.keras.Model

### ISSUE THREAD

**Issue by 8bitmp3** [tensorflow/tensorflow#27461]
**System information**
- TensorFlow version: 2.0 alpha
- Doc Link: 
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/Model
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training.py

**Describe the documentation issue**

**- Links:**

A link to **_Keras Functional API in TensorFlow_** would be appreciated for those who are new to `(tf.)Keras` and TensorFlow 1.x and 2.0 - https://www.tensorflow.org/alpha/guide/keras/functional. E.g. See this Keras Model class API doc: https://keras.io/models/model/#model-class-api.

**- Description:**

Taking into account this is a 'heavy' module it may not be easy to write good docs for `tf.keras.Model`. Since `tf.keras` is a crucial API to TF 2.0, so let's make the docs a delight to read. The current documentation for `tf.keras.Model` is a bit incomprehensible for a novice or experienced user.

In terms of user experience for someone who is new or not new to TF, maybe the description should be improved and follow the keras.io docs more closely. For instance, arguments under `compile` were apparently copy-pasted from `keras.Model` docs (https://keras.io/models/model/). However, you have to scroll all the way down to see them here: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/Model#compile (_update: maybe because Methods etc are listed in alphabetical order which is not intuitive_).

The description at keras.io is neater and more organized imo. It starts with a short description and jumps to args from `compile`. I'd suggest we follow the same structure.

Also, as in https://keras.io/models/model/, we should include a link to the guide to **_Keras Functional API in TensorFlow_** - https://www.tensorflow.org/alpha/guide/keras/functional - which is quite well written.

**- Examples:**

Not enough examples - they are mentioned here and there. See UX issues above under Description. Recommend to rewrite it to follow the original `keras.Model` module - https://keras.io/models/model/#model-class-api - along with examples. 

**- Parameters, Returns, Raises:**

UX issues - see Description above.

**- Visuals:**

Recommend to add visuals from https://www.tensorflow.org/alpha/guide/keras/functional

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
Yes, let's make `tf.keras` docs awesome.

**Comment by amanp592** [comment]
@8bitmp3 I want to work on this can you assign me this??

**Comment by amanp592** [comment]
@8bitmp3 I searched out into the docs repository but did'nt the file for tf.keras documentation can be please help me in finding the appropriate files.

**Comment by 8bitmp3** [comment]
It's a known issue. This is the original: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras. But the `__init__` URL is broken - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/api/_v2/keras/__init__.py lands you on a 404. @margaretmz has raised it here https://github.com/tensorflow/tensorflow/issues/26197

> @8bitmp3 I searched out into the docs repository but did'nt the file for tf.keras documentation can be please help me in finding the appropriate files.

**Comment by amanp592** [comment]
@8bitmp3 I am working on it and will keep you updated

**Comment by muddham** [comment]
@8bitmp3 In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by amanp592** [comment]
@8bitmp3 I found out that the API docs will be generated with the help of api_generator we have to create a build_doc API with the help of api_generator API to create docs! but I didn't get how this would be done!

**Comment by lamberta** [comment]
Is this issue still valid?
We now automatically links in the 2.0 ref docs to places it's used in the guide and tutorials. See the second section here: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/Model

**Comment by 8bitmp3** [comment]
> Is this issue still valid?
> We now automatically links in the 2.0 ref docs to places it's used in the guide and tutorials. See the second section here: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/Model

@lamberta Just noticed the new layout and links—I think it looks awesome 🙌 Thanks a bunch 👍 I shall close the issue
