### ISSUE TITLE
tf-nightly: cannot find -ltensorflow_framework (new naming convention?)

### ISSUE THREAD

**Issue by tgaddair** [tensorflow/tensorflow#27468]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian Jessie, macOS Mojave
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.14.1-dev20190402
- Python version: 2.7.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

When building [Horovod](https://github.com/horovod/horovod), we link against the `libtensorflow_framework.so` using `tf.sysconfig.get_link_flags()`.  

The most recent nightly builds (starting 2019-04-02) have replaced `libtensorflow_framework.so` with two separate .so files: `libtensorflow_framework.so.1` and `libtensorflow_framework.so.1.13.1`.  However, `tf.sysconfig.get_link_flags()` still references [-ltensorflow_framework](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/sysconfig.py#L78), which causes our build process to fail.

We found that replacing this line with `flags.append('-l:libtensorflow_framework.so.1')` fixed the issue with gcc.

My question is: is this intended to be the new library organization for TensorFlow going forward? If we were to submit a PR to update `tf.sysconfig` to use the correct libraries filenames, is that expected to work for the foreseeable future, or are these new artifacts temporary or accidents?  Alternatively, could your build process be updated to generate symlinks so `tf.sysconfig` will continue to work as is?

Thanks.

**Comment by alsrgv** [comment]
cc @gunan @martinwicke

**Comment by martinwicke** [comment]
@perfinion this looks related to #22797? Maybe we just have to change sysconfig to match?

**Comment by alsrgv** [comment]
Fixed by #27493, can be closed. Thanks!
