### ISSUE TITLE
[TF 2.0 API Docs] tf.keras.Sequential

### ISSUE THREAD

**Issue by 8bitmp3** [tensorflow/tensorflow#27463]
**System information**
- TensorFlow version: 2.0 alpha
- Doc Link:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/Sequential
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/sequential.py

**Describe the documentation issue**

**- Description:**

The order of _Properties_ and _Methods_ is alphabetical, probably by TF doc design. With a large doc for an arguably popular module such as `tf.keras.Sequential` navigating around it may be confusing to the user. Perhaps we should start with the most important ones e.g. `compile` and `fit` under Methods. Since `tf.keras.Sequential`, like many other modules/classes, expands on `keras.Sequential` it would still be logical to list certain Properties, Methods etc in the beginning (at the top of the page) in order of importance for better UX. See: https://keras.io/models/sequential/ as a good example where these are not in alphabetical order.

Also, in the beginning after a short intro ("inherits from `Model`... a linear stack of layers"), a link to "Build a Simple Model" (with `tf.keras.Sequential`) in TensorFlow would be cool for those who are new to `(tf.)Keras`/TF - https://www.tensorflow.org/alpha/guide/keras/overview#sequential_model. Also, the official Keras.io docs include a URL in https://keras.io/models/sequential/ to "Getting started with the Keras Sequential model": https://keras.io/getting-started/sequential-model-guide.

**- Examples:**

There already is an example right in the beginning. Maybe adding adding a separate link to or copying an example from this Sequential notebook would be cool too - https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/quickstart/beginner.ipynb (source: https://www.tensorflow.org/alpha/guide/keras/overview#sequential_model)

**- Parameters**

Inconsistent. Some reformatting may be needed e.g. input_shape -> `input_shape`. 
Also, both _Arguments_ and _Args_ are used throughout the doc.

**- Returns, Raises:**

Sometimes exist, sometimes not - creates a UX issue because of inconsistency.

**- Visuals:**

A simple one similar to https://www.tensorflow.org/alpha/guide/keras/functional would be appreciated.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
For sure.

**Comment by shashvatshahi1998** [comment]
I will love to work on the issue

**Comment by yashk2810** [comment]
We are linking off to guides now: https://www.tensorflow.org/api_docs/python/tf/keras/Sequential?version=nightly

Regarding the ordering, this is being tracked internally and being worked on. Closing this for now. Please reopen if something is not fixed :)
